In [12]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import os
pd.options.mode.chained_assignment = None
import optuna
import time
from sklearn.metrics import r2_score, mean_squared_error
from sklearn.model_selection import cross_val_score, KFold, StratifiedKFold, train_test_split
from xgboost import XGBRegressor
from catboost import CatBoostRegressor
from lightgbm import LGBMRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression, Ridge, ElasticNet
from sklearn.neighbors import KNeighborsRegressor
from sklearn.neural_network import MLPRegressor
from sklearn.svm import SVR
from sklearn.preprocessing import StandardScaler, RobustScaler
import pickle
from collections import defaultdict

### Preparación datasets

In [30]:
# Cargamos los csv de los tifs
path = "saved_files/dataset"
depth = "lt_1"
dfs = {}
all_datasets = False
for archivo in os.listdir(path):
    if all_datasets:
        if f"{depth}" in archivo:
            nombre_sin_extension = os.path.splitext(archivo)[0]  # sin .csv
            ruta_completa = os.path.join(path, archivo)
            dfs[nombre_sin_extension] = pd.read_csv(ruta_completa)
    else:
        if archivo.endswith(f"{depth}_features.csv"):
            nombre_sin_extension = os.path.splitext(archivo)[0]  # sin .csv
            ruta_completa = os.path.join(path, archivo)
            dfs[nombre_sin_extension[:-9]] = pd.read_csv(ruta_completa)

In [22]:
dfs.keys()

dict_keys(['C2RCC_rhown_5x5_depth_gt_3', 'C2X_rhown_5x5_depth_gt_3', 'C2X_rhow_3x3_depth_gt_3', 'C2X_rhow_9x9_depth_gt_3', 'C2X_rhown_1x1_depth_gt_3', 'TOA_9x9_depth_gt_3', 'C2X-Complex_rhow_3x3_depth_gt_3', 'C2X-Complex_rhown_5x5_depth_gt_3', 'C2RCC_rhow_3x3_depth_gt_3', 'C2X-Complex_rhown_1x1_depth_gt_3', 'TOA_5x5_depth_gt_3', 'C2X-Complex_rhow_9x9_depth_gt_3', 'C2RCC_rhow_5x5_depth_gt_3', 'TOA_1x1_depth_gt_3', 'C2X-Complex_rhown_3x3_depth_gt_3', 'C2X_rhown_9x9_depth_gt_3', 'C2X_rhow_5x5_depth_gt_3', 'C2RCC_rhown_3x3_depth_gt_3', 'C2X-Complex_rhow_5x5_depth_gt_3', 'C2RCC_rhow_1x1_depth_gt_3', 'C2RCC_rhow_9x9_depth_gt_3', 'C2RCC_rhown_9x9_depth_gt_3', 'TOA_3x3_depth_gt_3', 'C2X-Complex_rhow_1x1_depth_gt_3', 'C2X_rhown_3x3_depth_gt_3', 'C2X-Complex_rhown_9x9_depth_gt_3', 'C2RCC_rhown_1x1_depth_gt_3', 'C2X_rhow_1x1_depth_gt_3'])

In [194]:
dfs["C2RCC_rhow_1x1_depth_lt_1"]

,Date,Buoy,Latitude,Longitude,rhow_B1,rhow_B2,rhow_B3,rhow_B4,rhow_B5,rhow_B6,...,dif_rel_4bands_rhow_B2_B5_B3_B4,dif_rel_4bands_rhow_B2_B5_B4_B3,dif_rel_4bands_rhow_B3_B2_B4_B5,dif_rel_4bands_rhow_B3_B2_B5_B4,dif_rel_4bands_rhow_B3_B4_B5_B2,dif_rel_4bands_rhow_B3_B5_B4_B2,dif_rel_4bands_rhow_B4_B2_B5_B3,dif_rel_4bands_rhow_B4_B3_B5_B2,sum_norm_3bands_rhow_B2_B4_B3,sum_norm_3bands_rhow_B3_B5_B4
0,2016-08-09,CTD1,4187246,695025,0.010973,0.017248,0.033436,0.016780,0.012437,0.003690,...,-0.606,0.885,0.589,1.197,1.272,1.716,0.601,-0.219,0.671,0.914
1,2016-08-09,CTD2,4181518,693105,0.007180,0.010530,0.019375,0.011021,0.008281,0.002545,...,-0.486,0.703,0.509,1.089,0.972,1.293,0.619,-0.218,0.721,0.910
2,2016-08-09,CTD3,4181698,695238,0.007966,0.011565,0.020111,0.010630,0.007752,0.002311,...,-0.400,0.963,0.368,1.010,1.222,1.675,0.534,-0.142,0.701,0.906
3,2016-08-09,CTD4,4180266,698264,0.008062,0.010310,0.014764,0.008631,0.006252,0.001894,...,-0.062,1.064,0.052,0.708,1.104,1.524,0.414,-0.022,0.755,0.898
4,2016-08-09,CTD6,4176009,695829,0.008603,0.013129,0.023304,0.010864,0.007707,0.002229,...,-0.442,1.237,0.365,1.066,1.558,2.196,0.497,-0.121,0.659,0.908
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
446,2023-05-25,CTD8,4174178,693048,0.016512,0.029853,0.043600,0.007112,0.004319,0.001135,...,0.781,6.749,-0.186,0.853,5.986,9.856,0.139,0.018,0.503,0.945
447,2023-05-25,CTD9,4171106,693183,0.007081,0.012752,0.026582,0.009738,0.006888,0.001995,...,-0.879,1.485,0.671,1.377,2.190,3.095,0.505,-0.174,0.572,0.922
448,2023-05-25,CTD10,4170388,695646,0.007636,0.014290,0.026969,0.006672,0.004333,0.001186,...,-0.745,3.050,0.348,1.238,3.739,5.756,0.306,-0.056,0.508,0.930
449,2023-05-25,CTD11,4169609,700351,0.007547,0.014033,0.026831,0.007324,0.004826,0.001328,...,-0.756,2.635,0.394,1.253,3.320,5.038,0.342,-0.071,0.523,0.927
450,2023-05-25,CTD12,4173438,695414,0.010524,0.019697,0.033400,0.006790,0.004274,0.001145,...,-0.310,4.406,0.107,1.066,4.702,7.471,0.217,-0.014,0.499,0.937

In [29]:
# Para seleccionar manualmente qué dataframes nos quedamos
# Si leemos por profundidad ya no hace falta esto
dfs_to_keep = [
    "C2X_1x1_merge_depth_lt_1", "C2X_3x3_merge_depth_lt_1", "C2X_5x5_merge_depth_lt_1", 
    "C2X-Complex_1x1_merge_depth_lt_1", "C2X-Complex_3x3_merge_depth_lt_1", "C2X-Complex_5x5_merge_depth_lt_1",
    "C2RCC_1x1_merge_depth_lt_1", "C2RCC_3x3_merge_depth_lt_1", "C2RCC_5x5_merge_depth_lt_1",
    "TOA_1x1_merge_depth_lt_1", "TOA_3x3_merge_depth_lt_1", "TOA_5x5_merge_depth_lt_1",
]

#dfs = {k: dfs[k] for k in dfs_to_keep if k in dfs}

In [31]:

# Limpiamos valores nulos
for nombre_df, df in dfs.items():
    for band_set in ["rhow", "rhown","rtoa"]:
        dfs[nombre_df] = df.dropna()

In [32]:
def get_season(month):
    if month in [12, 1, 2]:
        return 'Invierno'
    elif month in [3, 4, 5]:
        return 'Primavera'
    elif month in [6, 7, 8]:
        return 'Verano'
    else:
        return 'Otoño'
    

def get_zone(buoy):
    if buoy in ["CTD1", "CTD2", "CTD3", "CTD4"]:
        return 'Zona-1'
    elif buoy in ["CTD6", "CTD8", "CTD9", "CTD10", "CTD12"]:
        return 'Zona-2'
    elif buoy in ["CTD7"]:
        return 'Zona-3'
    elif buoy in ["CTD11"]:
        return 'Zona-4'

In [33]:

for nombre_df, df in dfs.items():
    # Marcamos las columnas de CHl alta (equivalente a quantile(0.93))
    df["High_Chl"] = df["Chl"]>5
    # Sacamos la estación de cada fecha
    df['Date'] = pd.to_datetime(df['Date'])
    df['Season'] = df['Date'].dt.month.apply(get_season)
    
    # Etiquetamos la zona de la observación (comentado porque para aplicar el modelo habría que segmentar todo el Mar Menor - se puede hacer por px)
    # df['Zone'] = df['Buoy'].apply(get_zone)
    # Ponemos las columnas como categóricas, para Season y Zone
    for col in df.select_dtypes(include='object').columns:
        df[col] = df[col].astype('category')

    df = pd.concat([df.drop(columns=["Season"]),pd.get_dummies(df["Season"])], axis=1)
    dfs[nombre_df] = df

In [53]:
# Filtro para quitar columnas muy correlacionadas de cada dataset - de momento no lo usamos
def filtrar_columnas(df):

    # 1. Separar columnas numéricas y no numéricas
    df_numericas = df.select_dtypes(include='number')
    df_no_numericas = df.select_dtypes(exclude='number')

    # 2. Calcular la correlación con 'Chl' solo entre columnas numéricas
    correlaciones = df_numericas.corr()['Chl'].drop('Chl')

    # 3. Filtrar predictores numéricos con correlación significativa
    umbral_corr = 0.1
    columnas_utiles = correlaciones[correlaciones.abs() >= umbral_corr].index.tolist()

    # 4. Reconstruir el DataFrame con:
    # - Las columnas numéricas útiles
    # - La columna objetivo 'Chl'
    df_filtrado = pd.concat([df[columnas_utiles + ['Chl']]], axis=1)

    # Calcular la matriz de correlación entre predictores
    corr_matrix = df_filtrado.drop(columns='Chl').corr().abs()

    # Seleccionar columnas a eliminar (altamente correlacionadas entre sí)
    upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(bool))
    columnas_redundantes = [col for col in upper.columns if any(upper[col] > 0.98)]

    # Eliminar redundantes
    df_final = pd.concat([df_filtrado.drop(columns=columnas_redundantes), df_no_numericas], axis=1)
    df_final = df_final.drop(columns=["Date", "Buoy"])

    return df_final


# for nombre_df, df in dfs.items():
#     dfs[nombre_df] = filtrar_columnas(df)

In [34]:
model_params ={
    "XGB" : {
        'n_estimators': 1000,
        'learning_rate': 0.01,
        'max_depth': 7,
        'min_child_weight': 3,
        'subsample': 0.9,
        'colsample_bytree': 0.9,
        'device': 'cpu',
        'objective': 'reg:squarederror',
        'tree_method': 'hist',
        'enable_categorical': True,
        #'early_stopping_rounds': 50,
        'eval_metric': 'rmse'
        },

    "LBM" : {
        'learning_rate': 0.05,
        'num_leaves': 20,
        'max_depth': 7,
        'min_child_samples': 3,
        'subsample': 0.6,
        'colsample_bytree': 0.9,
        'n_estimators': 1000,
        'objective': 'regression',
        'metric': 'rmse',
        'boosting_type': 'gbdt',
        'device': 'cpu',  
        'verbosity': -1,
        #'early_stopping_rounds': 50
        },

    "MLP": {
        'hidden_layer_sizes': (100,),
        'activation': 'relu',
        'solver': 'adam',
        'alpha': 0.0001,
        'learning_rate': 'constant',
        'learning_rate_init': 0.001,
        'max_iter': 200,
        'shuffle': True,
        'random_state': None,
        'tol': 1e-4,
        'n_iter_no_change': 25,
        'verbose': False,
        'early_stopping': True,
        'validation_fraction': 0.2
        },

    "SVR": {
        'kernel': 'sigmoid',        
        'C': 1.0,               
        'epsilon': 0.1,           
        'gamma': 'scale',        
        'shrinking': True,
        'tol': 1e-3,
        'max_iter': -1,          
        'verbose': False,
    },

    "KNN": {
        'n_neighbors': 5,
        'weights': 'uniform',      
        'algorithm': 'auto',      
        'leaf_size': 30,
        'p': 2,                    
        'metric': 'minkowski',
        'n_jobs': -1             
    },

    "RF": {
        'n_estimators': 100,         
        'criterion': 'squared_error',
        'max_depth': 10,         
        'min_samples_split': 2,
        'min_samples_leaf': 1,    
        'bootstrap': True,
        'random_state': 42,
        'verbose': 0
    },

    "CAT": {
        'iterations': 1000,
        'learning_rate': 0.03,
        'depth': 6,
        'l2_leaf_reg': 3.0,
        'loss_function': 'RMSE',
        'eval_metric': 'RMSE',
        'random_seed': 42,
        'allow_writing_files': False,
        'early_stopping_rounds': 50,
        'verbose': False
    },

    "EN": {
        'alpha': 1.0,              # fuerza de regularización
        'l1_ratio': 0.5,           # mezcla entre L1 (lasso) y L2 (ridge)
        'fit_intercept': True,
        'max_iter': 1000,
        'tol': 1e-4,
        'selection': 'cyclic',
        'random_state': 42
    }

}


models = {
    "XGB": XGBRegressor(**model_params['XGB']),
    "LBM": LGBMRegressor(**model_params['LBM']),
    "MLP": MLPRegressor(**model_params['MLP']),
    #"SVR": SVR(**model_params['SVR']),
    "KNN": KNeighborsRegressor(**model_params['KNN']),
    #"LR": LinearRegression().
    "RF": RandomForestRegressor(**model_params['RF']),
    "CAT": CatBoostRegressor(**model_params["CAT"]),
    "EN":  ElasticNet(**model_params["EN"])
}

### Entrenamiento con parámetros por defecto

In [35]:
results = {}

for nombre_df, df in list(dfs.items()):
    #print(nombre_df)
    df = df.iloc[:,4:]

    # Para usar solamente bandas, sin combinaciones
    # if 'TOA' in nombre_df:
    #     # TOA solamente con las bandas, parece que las combinaciones solo meten ruido
    #     df = df.iloc[:,np.r_[0:14, 58:60]]
    # if 'rhow' in nombre_df and 'rhown' not in nombre_df:
    #     df = df.iloc[:,np.r_[0:9, 53:55]]
    # if 'rhown' in nombre_df:
    #     df = df.iloc[:,np.r_[0:7, 51:53]]

    train, test = train_test_split(df, test_size=0.2, random_state=42, stratify=df["High_Chl"]) # TEST 20% TRAIN 80%
    target = "Chl"

    train, val = train_test_split(train, test_size=0.25, random_state=42, stratify=train["High_Chl"]) # TRAIN 60% VAL 20% TEST%

    X_train = train.drop(columns=[target,"High_Chl"])
    X_val = val.drop(columns=[target, "High_Chl"])
    X_test = test.drop(columns=[target, "High_Chl"])
    y_train = train[target]
    y_val = val[target]
    y_test = test[target]

    
    scaler_X = RobustScaler()
    scaler_y = RobustScaler()
    X_train_scaled = scaler_X.fit_transform(X_train)
    X_val_scaled = scaler_X.transform(X_val)
    X_test_scaled = scaler_X.transform(X_test)
    y_train_scaled = scaler_y.fit_transform(y_train.values.reshape(-1, 1)).ravel()
    
    results[nombre_df] = {name: {'RMSE': None, 'R2': None} for name in models}
    val_preds = {}
    test_preds = {}

    for name, model in models.items():
        print(f"Fitting {name} for {nombre_df}")
        if name in ["MLP", "SVR", "KNN", "LR", "EN"]:
            model.fit(X_train_scaled, y_train_scaled)
            #test_pred = model.predict(X_test_scaled)
            val_pred = scaler_y.inverse_transform(model.predict(X_val_scaled).reshape(-1, 1)).ravel()
            test_pred = scaler_y.inverse_transform(model.predict(X_test_scaled).reshape(-1, 1)).ravel()
        else:
            model.fit(X_train, y_train)
            val_pred = model.predict(X_val)
            test_pred = model.predict(X_test)

        val_preds[name] = val_pred
        test_preds[name] = test_pred

        rmse = np.sqrt(mean_squared_error(y_test, test_pred))
        r2 = r2_score(y_test, test_pred)

        results[nombre_df][name]['RMSE'] = rmse.round(2)
        results[nombre_df][name]['R2'] = r2.round(2)

    # Meta-modelo
    meta_X = np.vstack([val_preds[model] for model in models]).T
    meta_y = y_val.values
    meta_model = Ridge().fit(meta_X, meta_y)

    # Predicción final ensemble
    test_meta_X = np.vstack([test_preds[model] for model in models]).T
    ensemble_pred = meta_model.predict(test_meta_X)

    rmse_ens = np.sqrt(mean_squared_error(y_test, ensemble_pred))
    r2_ens = r2_score(y_test, ensemble_pred)

    results[nombre_df]["Ensemble"] = {
        "RMSE": round(rmse_ens, 2),
        "R2": round(r2_ens, 2)
    }

Fitting XGB for C2RCC_rhow_5x5_depth_lt_1
Fitting LBM for C2RCC_rhow_5x5_depth_lt_1
Fitting MLP for C2RCC_rhow_5x5_depth_lt_1
Fitting KNN for C2RCC_rhow_5x5_depth_lt_1
Fitting RF for C2RCC_rhow_5x5_depth_lt_1
Fitting CAT for C2RCC_rhow_5x5_depth_lt_1
Fitting EN for C2RCC_rhow_5x5_depth_lt_1
Fitting XGB for C2X-Complex_rhown_3x3_depth_lt_1
Fitting LBM for C2X-Complex_rhown_3x3_depth_lt_1
Fitting MLP for C2X-Complex_rhown_3x3_depth_lt_1
Fitting KNN for C2X-Complex_rhown_3x3_depth_lt_1
Fitting RF for C2X-Complex_rhown_3x3_depth_lt_1
Fitting CAT for C2X-Complex_rhown_3x3_depth_lt_1
Fitting EN for C2X-Complex_rhown_3x3_depth_lt_1
Fitting XGB for TOA_9x9_depth_lt_1
Fitting LBM for TOA_9x9_depth_lt_1
Fitting MLP for TOA_9x9_depth_lt_1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fitting KNN for TOA_9x9_depth_lt_1
Fitting RF for TOA_9x9_depth_lt_1
Fitting CAT for TOA_9x9_depth_lt_1
Fitting EN for TOA_9x9_depth_lt_1
Fitting XGB for C2X_rhow_3x3_depth_lt_1
Fitting LBM for C2X_rhow_3x3_depth_lt_1
Fitting MLP for C2X_rhow_3x3_depth_lt_1
Fitting KNN for C2X_rhow_3x3_depth_lt_1
Fitting RF for C2X_rhow_3x3_depth_lt_1
Fitting CAT for C2X_rhow_3x3_depth_lt_1
Fitting EN for C2X_rhow_3x3_depth_lt_1
Fitting XGB for C2RCC_rhow_9x9_depth_lt_1
Fitting LBM for C2RCC_rhow_9x9_depth_lt_1
Fitting MLP for C2RCC_rhow_9x9_depth_lt_1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fitting KNN for C2RCC_rhow_9x9_depth_lt_1
Fitting RF for C2RCC_rhow_9x9_depth_lt_1
Fitting CAT for C2RCC_rhow_9x9_depth_lt_1
Fitting EN for C2RCC_rhow_9x9_depth_lt_1
Fitting XGB for C2X-Complex_rhown_5x5_depth_lt_1
Fitting LBM for C2X-Complex_rhown_5x5_depth_lt_1
Fitting MLP for C2X-Complex_rhown_5x5_depth_lt_1
Fitting KNN for C2X-Complex_rhown_5x5_depth_lt_1
Fitting RF for C2X-Complex_rhown_5x5_depth_lt_1
Fitting CAT for C2X-Complex_rhown_5x5_depth_lt_1
Fitting EN for C2X-Complex_rhown_5x5_depth_lt_1
Fitting XGB for C2X_rhown_9x9_depth_lt_1
Fitting LBM for C2X_rhown_9x9_depth_lt_1
Fitting MLP for C2X_rhown_9x9_depth_lt_1
Fitting KNN for C2X_rhown_9x9_depth_lt_1
Fitting RF for C2X_rhown_9x9_depth_lt_1
Fitting CAT for C2X_rhown_9x9_depth_lt_1
Fitting EN for C2X_rhown_9x9_depth_lt_1
Fitting XGB for TOA_3x3_depth_lt_1
Fitting LBM for TOA_3x3_depth_lt_1
Fitting MLP for TOA_3x3_depth_lt_1
Fitting KNN for TOA_3x3_depth_lt_1
Fitting RF for TOA_3x3_depth_lt_1
Fitting CAT for TOA_3x3_depth_lt_1
Fitting EN for TOA_3x3_depth_lt_1
Fitting XGB for C2X-Complex_rhown_9x9_depth_lt_1
Fitting LBM for C2X-Complex_rhown_9x9_depth_lt_1
Fitting MLP for C2X-Complex_rhown_9x9_depth_lt_1
Fitting KNN for C2X-Complex_rhown_9x9_depth_lt_1
Fitting RF for C2X-Complex_rhown_9x9_depth_lt_1
Fitting CAT for C2X-Complex_rhown_9x9_depth_lt_1
Fitting EN for C2X-Complex_rhown_9x9_depth_lt_1
Fitting XGB for C2X-Complex_rhow_3x3_depth_lt_1
Fitting LBM for C2X-Complex_rhow_3x3_depth_lt_1
Fitting MLP for C2X-Complex_rhow_3x3_depth_lt_1
Fitting KNN for C2X-Complex_rhow_3x3_depth_lt_1
Fitting RF for C2X-Complex_rhow_3x3_depth_lt_1
Fitting CAT for C2X-Complex_rhow_3x3_depth_lt_1
Fitting EN for C2X-Complex_rhow_3x3_depth_lt_1
Fitting XGB for C2X_rhow_1x1_depth_lt_1
Fitting LBM for C2X_rhow_1x1_depth_lt_1
Fitting MLP for C2X_rhow_1x1_depth_lt_1
Fitting KNN for C2X_rhow_1x1_depth_lt_1
Fitting RF for C2X_rhow_1x1_depth_lt_1
Fitting CAT for C2X_rhow_1x1_depth_lt_1
Fitting EN for C2X_rhow_1x1_depth_lt_1
Fitting XGB for C2RCC_rhown_1x1_depth_lt_1
Fitting LBM for C2RCC_rhown_1x1_depth_lt_1
Fitting MLP for C2RCC_rhown_1x1_depth_lt_1
Fitting KNN for C2RCC_rhown_1x1_depth_lt_1
Fitting RF for C2RCC_rhown_1x1_depth_lt_1
Fitting CAT for C2RCC_rhown_1x1_depth_lt_1
Fitting EN for C2RCC_rhown_1x1_depth_lt_1
Fitting XGB for C2X_rhown_1x1_depth_lt_1
Fitting LBM for C2X_rhown_1x1_depth_lt_1
Fitting MLP for C2X_rhown_1x1_depth_lt_1
Fitting KNN for C2X_rhown_1x1_depth_lt_1
Fitting RF for C2X_rhown_1x1_depth_lt_1
Fitting CAT for C2X_rhown_1x1_depth_lt_1
Fitting EN for C2X_rhown_1x1_depth_lt_1
Fitting XGB for C2RCC_rhown_9x9_depth_lt_1
Fitting LBM for C2RCC_rhown_9x9_depth_lt_1
Fitting MLP for C2RCC_rhown_9x9_depth_lt_1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fitting KNN for C2RCC_rhown_9x9_depth_lt_1
Fitting RF for C2RCC_rhown_9x9_depth_lt_1
Fitting CAT for C2RCC_rhown_9x9_depth_lt_1
Fitting EN for C2RCC_rhown_9x9_depth_lt_1
Fitting XGB for C2X_rhow_5x5_depth_lt_1
Fitting LBM for C2X_rhow_5x5_depth_lt_1
Fitting MLP for C2X_rhow_5x5_depth_lt_1
Fitting KNN for C2X_rhow_5x5_depth_lt_1
Fitting RF for C2X_rhow_5x5_depth_lt_1
Fitting CAT for C2X_rhow_5x5_depth_lt_1
Fitting EN for C2X_rhow_5x5_depth_lt_1
Fitting XGB for C2X_rhown_5x5_depth_lt_1
Fitting LBM for C2X_rhown_5x5_depth_lt_1
Fitting MLP for C2X_rhown_5x5_depth_lt_1
Fitting KNN for C2X_rhown_5x5_depth_lt_1
Fitting RF for C2X_rhown_5x5_depth_lt_1
Fitting CAT for C2X_rhown_5x5_depth_lt_1
Fitting EN for C2X_rhown_5x5_depth_lt_1
Fitting XGB for C2X_rhow_9x9_depth_lt_1
Fitting LBM for C2X_rhow_9x9_depth_lt_1
Fitting MLP for C2X_rhow_9x9_depth_lt_1
Fitting KNN for C2X_rhow_9x9_depth_lt_1
Fitting RF for C2X_rhow_9x9_depth_lt_1
Fitting CAT for C2X_rhow_9x9_depth_lt_1
Fitting EN for C2X_rhow_9x9_depth_lt_1
Fitting XGB for C2X_rhown_3x3_depth_lt_1
Fitting LBM for C2X_rhown_3x3_depth_lt_1
Fitting MLP for C2X_rhown_3x3_depth_lt_1
Fitting KNN for C2X_rhown_3x3_depth_lt_1
Fitting RF for C2X_rhown_3x3_depth_lt_1
Fitting CAT for C2X_rhown_3x3_depth_lt_1
Fitting EN for C2X_rhown_3x3_depth_lt_1
Fitting XGB for C2RCC_rhown_5x5_depth_lt_1
Fitting LBM for C2RCC_rhown_5x5_depth_lt_1
Fitting MLP for C2RCC_rhown_5x5_depth_lt_1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fitting KNN for C2RCC_rhown_5x5_depth_lt_1
Fitting RF for C2RCC_rhown_5x5_depth_lt_1
Fitting CAT for C2RCC_rhown_5x5_depth_lt_1
Fitting EN for C2RCC_rhown_5x5_depth_lt_1
Fitting XGB for TOA_1x1_depth_lt_1
Fitting LBM for TOA_1x1_depth_lt_1
Fitting MLP for TOA_1x1_depth_lt_1
Fitting KNN for TOA_1x1_depth_lt_1
Fitting RF for TOA_1x1_depth_lt_1
Fitting CAT for TOA_1x1_depth_lt_1
Fitting EN for TOA_1x1_depth_lt_1
Fitting XGB for C2X-Complex_rhow_5x5_depth_lt_1
Fitting LBM for C2X-Complex_rhow_5x5_depth_lt_1
Fitting MLP for C2X-Complex_rhow_5x5_depth_lt_1
Fitting KNN for C2X-Complex_rhow_5x5_depth_lt_1
Fitting RF for C2X-Complex_rhow_5x5_depth_lt_1
Fitting CAT for C2X-Complex_rhow_5x5_depth_lt_1
Fitting EN for C2X-Complex_rhow_5x5_depth_lt_1
Fitting XGB for C2X-Complex_rhow_9x9_depth_lt_1
Fitting LBM for C2X-Complex_rhow_9x9_depth_lt_1
Fitting MLP for C2X-Complex_rhow_9x9_depth_lt_1
Fitting KNN for C2X-Complex_rhow_9x9_depth_lt_1
Fitting RF for C2X-Complex_rhow_9x9_depth_lt_1
Fitting CAT for C2X-Complex_rhow_9x9_depth_lt_1
Fitting EN for C2X-Complex_rhow_9x9_depth_lt_1
Fitting XGB for C2X-Complex_rhow_1x1_depth_lt_1
Fitting LBM for C2X-Complex_rhow_1x1_depth_lt_1
Fitting MLP for C2X-Complex_rhow_1x1_depth_lt_1
Fitting KNN for C2X-Complex_rhow_1x1_depth_lt_1
Fitting RF for C2X-Complex_rhow_1x1_depth_lt_1
Fitting CAT for C2X-Complex_rhow_1x1_depth_lt_1
Fitting EN for C2X-Complex_rhow_1x1_depth_lt_1
Fitting XGB for C2X-Complex_rhown_1x1_depth_lt_1
Fitting LBM for C2X-Complex_rhown_1x1_depth_lt_1
Fitting MLP for C2X-Complex_rhown_1x1_depth_lt_1
Fitting KNN for C2X-Complex_rhown_1x1_depth_lt_1
Fitting RF for C2X-Complex_rhown_1x1_depth_lt_1
Fitting CAT for C2X-Complex_rhown_1x1_depth_lt_1
Fitting EN for C2X-Complex_rhown_1x1_depth_lt_1
Fitting XGB for C2RCC_rhow_3x3_depth_lt_1
Fitting LBM for C2RCC_rhow_3x3_depth_lt_1
Fitting MLP for C2RCC_rhow_3x3_depth_lt_1
Fitting KNN for C2RCC_rhow_3x3_depth_lt_1
Fitting RF for C2RCC_rhow_3x3_depth_lt_1
Fitting CAT for C2RCC_rhow_3x3_depth_lt_1
Fitting EN for C2RCC_rhow_3x3_depth_lt_1
Fitting XGB for TOA_5x5_depth_lt_1
Fitting LBM for TOA_5x5_depth_lt_1
Fitting MLP for TOA_5x5_depth_lt_1
Fitting KNN for TOA_5x5_depth_lt_1
Fitting RF for TOA_5x5_depth_lt_1
Fitting CAT for TOA_5x5_depth_lt_1
Fitting EN for TOA_5x5_depth_lt_1
Fitting XGB for C2RCC_rhown_3x3_depth_lt_1
Fitting LBM for C2RCC_rhown_3x3_depth_lt_1
Fitting MLP for C2RCC_rhown_3x3_depth_lt_1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fitting KNN for C2RCC_rhown_3x3_depth_lt_1
Fitting RF for C2RCC_rhown_3x3_depth_lt_1
Fitting CAT for C2RCC_rhown_3x3_depth_lt_1
Fitting EN for C2RCC_rhown_3x3_depth_lt_1
Fitting XGB for C2RCC_rhow_1x1_depth_lt_1
Fitting LBM for C2RCC_rhow_1x1_depth_lt_1
Fitting MLP for C2RCC_rhow_1x1_depth_lt_1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fitting KNN for C2RCC_rhow_1x1_depth_lt_1
Fitting RF for C2RCC_rhow_1x1_depth_lt_1
Fitting CAT for C2RCC_rhow_1x1_depth_lt_1
Fitting EN for C2RCC_rhow_1x1_depth_lt_1

In [36]:
# Para hacer un dataframe con multiindex en el que se vea todo

rows = []

for df_name, model_scores in results.items():
    row = {}
    for model_name, metrics in model_scores.items():
        for metric_name, value in metrics.items():
            # Clave: (métrica, modelo) → orden correcto para columnas
            row[(metric_name, model_name)] = value
    rows.append((df_name, row))

df_results = pd.DataFrame.from_dict(dict(rows), orient="index")
df_results.columns = pd.MultiIndex.from_tuples(df_results.columns, names=["Metric", "Model"])
df_results = df_results.sort_index(axis=1, level=0)
df_results = df_results.sort_index(axis=0)

In [37]:
df_results

Metric                              R2                                         \
Model                              CAT    EN Ensemble   KNN   LBM   MLP    RF
C2RCC_rhow_1x1_depth_lt_1         0.55  0.32     0.76  0.65  0.52  0.71  0.67
C2RCC_rhow_3x3_depth_lt_1         0.65  0.33     0.60  0.63  0.42  0.48  0.62
C2RCC_rhow_5x5_depth_lt_1         0.67  0.37     0.75  0.64  0.64  0.65  0.70
C2RCC_rhow_9x9_depth_lt_1         0.79  0.37     0.78  0.62  0.76  0.70  0.74
C2RCC_rhown_1x1_depth_lt_1        0.52  0.30     0.58  0.68  0.65  0.28  0.65
C2RCC_rhown_3x3_depth_lt_1        0.59  0.31     0.69  0.61  0.59  0.64  0.58
C2RCC_rhown_5x5_depth_lt_1        0.66  0.36     0.71  0.67  0.59  0.74  0.67
C2RCC_rhown_9x9_depth_lt_1        0.82  0.36     0.77  0.62  0.71  0.71  0.74
C2X-Complex_rhow_1x1_depth_lt_1   0.68  0.36     0.67  0.64  0.65  0.55  0.60
C2X-Complex_rhow_3x3_depth_lt_1   0.72  0.37     0.66  0.60  0.60  0.62  0.61
C2X-Complex_rhow_5x5_depth_lt_1   0.71  0.41     0.59  0.58  0.56  0.57  0.57
C2X-Complex_rhow_9x9_depth_lt_1   0.80  0.50     0.69  0.64  0.73  0.61  0.69
C2X-Complex_rhown_1x1_depth_lt_1  0.69  0.40     0.66  0.69  0.61  0.63  0.59
C2X-Complex_rhown_3x3_depth_lt_1  0.68  0.37     0.62  0.56  0.54  0.39  0.57
C2X-Complex_rhown_5x5_depth_lt_1  0.73  0.44     0.64  0.62  0.65  0.23  0.65
C2X-Complex_rhown_9x9_depth_lt_1  0.77  0.50     0.71  0.67  0.61  0.64  0.66
C2X_rhow_1x1_depth_lt_1           0.69  0.62     0.80  0.60  0.78  0.59  0.62
C2X_rhow_3x3_depth_lt_1           0.64  0.47     0.45  0.62  0.49  0.43  0.57
C2X_rhow_5x5_depth_lt_1           0.52  0.54     0.62  0.57  0.44  0.46  0.45
C2X_rhow_9x9_depth_lt_1           0.70  0.65     0.67  0.70  0.70  0.65  0.68
C2X_rhown_1x1_depth_lt_1          0.58  0.53     0.52  0.50  0.40  0.59  0.51
C2X_rhown_3x3_depth_lt_1          0.60  0.32     0.67  0.51  0.38  0.59  0.53
C2X_rhown_5x5_depth_lt_1          0.52  0.43     0.50  0.45  0.13  0.37  0.43
C2X_rhown_9x9_depth_lt_1          0.65  0.60     0.61  0.55  0.56  0.66  0.63
TOA_1x1_depth_lt_1                0.35  0.01     0.37  0.37  0.18  0.11  0.14
TOA_3x3_depth_lt_1                0.60  0.02     0.44  0.42  0.43  0.53  0.48
TOA_5x5_depth_lt_1                0.59  0.04     0.45  0.46  0.41  0.22  0.54
TOA_9x9_depth_lt_1                0.60  0.04     0.49  0.46  0.38  0.50  0.42

Metric                                  RMSE                                   \
Model                              XGB   CAT    EN Ensemble   KNN   LBM   MLP
C2RCC_rhow_1x1_depth_lt_1         0.51  3.18  3.93     2.36  2.82  3.30  2.55
C2RCC_rhow_3x3_depth_lt_1         0.57  2.80  3.92     3.00  2.90  3.64  3.43
C2RCC_rhow_5x5_depth_lt_1         0.72  2.73  3.79     2.41  2.86  2.86  2.84
C2RCC_rhow_9x9_depth_lt_1         0.83  2.17  3.80     2.24  2.96  2.33  2.61
C2RCC_rhown_1x1_depth_lt_1        0.53  3.31  3.99     3.10  2.70  2.83  4.04
C2RCC_rhown_3x3_depth_lt_1        0.75  3.04  3.96     2.67  2.96  3.06  2.86
C2RCC_rhown_5x5_depth_lt_1        0.66  2.76  3.82     2.55  2.74  3.06  2.42
C2RCC_rhown_9x9_depth_lt_1        0.84  2.05  3.82     2.29  2.93  2.56  2.58
C2X-Complex_rhow_1x1_depth_lt_1   0.59  2.72  3.81     2.75  2.87  2.82  3.20
C2X-Complex_rhow_3x3_depth_lt_1   0.63  2.53  3.79     2.79  3.03  3.00  2.96
C2X-Complex_rhow_5x5_depth_lt_1   0.58  2.56  3.65     3.07  3.09  3.16  3.13
C2X-Complex_rhow_9x9_depth_lt_1   0.63  2.13  3.38     2.64  2.84  2.47  2.96
C2X-Complex_rhown_1x1_depth_lt_1  0.58  2.64  3.69     2.77  2.65  3.00  2.92
C2X-Complex_rhown_3x3_depth_lt_1  0.65  2.71  3.77     2.92  3.18  3.22  3.73
C2X-Complex_rhown_5x5_depth_lt_1  0.69  2.46  3.58     2.87  2.94  2.83  4.20
C2X-Complex_rhown_9x9_depth_lt_1  0.62  2.30  3.38     2.55  2.74  2.96  2.85
C2X_rhow_1x1_depth_lt_1           0.66  2.64  2.94     2.11  3.01  2.21  3.06
C2X_rhow_3x3_depth_lt_1           0.49  2.88  3.48     3.53  2.96  3.41  3.60
C2X_rhow_5x5_depth_lt_1           0.48  3.30  3.23     2.95  3.11  3.58  3.51
C2X_rhow_9x9_depth_lt_1           0.61  2.63  2.82     2.76  2.60  2.60  2.82
C2X_rhown_1x1_depth_lt_1          0.52  3.09  3.27     3.31  3.37  3.70  3.05
C2X_rhown_3x3_depth_lt_1          0.42  3.00  3.92     2.73  3.35  3.76  3.06
C2X_rhown_5x5_depth_lt_1          0.33  3.31  3.61     3.38  3.53  4.44  3.78
C2X_rhown_9x9_depth_lt_1          0.60  2.82  3.03     2.98  3.20  3.16  2.76
TOA_1x1_depth_lt_1                0.17  2.86  3.51     2.80  2.82  3.20  3.33
TOA_3x3_depth_lt_1                0.33  2.23  3.50     2.65  2.70  2.67  2.42
TOA_5x5_depth_lt_1                0.38  2.26  3.47     2.61  2.60  2.71  3.12
TOA_9x9_depth_lt_1                0.35  2.23  3.47     2.53  2.59  2.79  2.49

Metric
Model                               RF   XGB
C2RCC_rhow_1x1_depth_lt_1         2.72  3.33
C2RCC_rhow_3x3_depth_lt_1         2.94  3.11
C2RCC_rhow_5x5_depth_lt_1         2.63  2.53
C2RCC_rhow_9x9_depth_lt_1         2.43  1.96
C2RCC_rhown_1x1_depth_lt_1        2.82  3.27
C2RCC_rhown_3x3_depth_lt_1        3.10  2.39
C2RCC_rhown_5x5_depth_lt_1        2.75  2.80
C2RCC_rhown_9x9_depth_lt_1        2.44  1.92
C2X-Complex_rhow_1x1_depth_lt_1   3.03  3.04
C2X-Complex_rhow_3x3_depth_lt_1   2.97  2.91
C2X-Complex_rhow_5x5_depth_lt_1   3.11  3.10
C2X-Complex_rhow_9x9_depth_lt_1   2.67  2.89
C2X-Complex_rhown_1x1_depth_lt_1  3.05  3.08
C2X-Complex_rhown_3x3_depth_lt_1  3.13  2.81
C2X-Complex_rhown_5x5_depth_lt_1  2.83  2.65
C2X-Complex_rhown_9x9_depth_lt_1  2.80  2.95
C2X_rhow_1x1_depth_lt_1           2.93  2.79
C2X_rhow_3x3_depth_lt_1           3.12  3.40
C2X_rhow_5x5_depth_lt_1           3.53  3.43
C2X_rhow_9x9_depth_lt_1           2.70  2.99
C2X_rhown_1x1_depth_lt_1          3.32  3.29
C2X_rhown_3x3_depth_lt_1          3.27  3.65
C2X_rhown_5x5_depth_lt_1          3.59  3.89
C2X_rhown_9x9_depth_lt_1          2.92  3.02
TOA_1x1_depth_lt_1                3.28  3.22
TOA_3x3_depth_lt_1                2.56  2.89
TOA_5x5_depth_lt_1                2.40  2.78
TOA_9x9_depth_lt_1                2.70  2.85

In [243]:
df_results

Metric                              R2                                         \
Model                              CAT    EN Ensemble   KNN   LBM    LR   MLP
C2RCC_rhow_1x1_depth_lt_1         0.60  0.32     0.77  0.65  0.62  0.64  0.78
C2RCC_rhow_3x3_depth_lt_1         0.62  0.33     0.79  0.63  0.63  0.47  0.78
C2RCC_rhow_5x5_depth_lt_1         0.67  0.37     0.78  0.64  0.65  0.64  0.80
C2RCC_rhow_9x9_depth_lt_1         0.78  0.37     0.69  0.62  0.70  0.49  0.77
C2RCC_rhown_1x1_depth_lt_1        0.51  0.30     0.72  0.68  0.62  0.44  0.77
C2RCC_rhown_3x3_depth_lt_1        0.62  0.31     0.78  0.61  0.62  0.48  0.76
C2RCC_rhown_5x5_depth_lt_1        0.64  0.36     0.69  0.67  0.64  0.62  0.81
C2RCC_rhown_9x9_depth_lt_1        0.81  0.36     0.74  0.62  0.70  0.55  0.77
C2X-Complex_rhow_1x1_depth_lt_1   0.68  0.36     0.43  0.64  0.70  0.15  0.72
C2X-Complex_rhow_3x3_depth_lt_1   0.71  0.37     0.51  0.60  0.56  0.10  0.72
C2X-Complex_rhow_5x5_depth_lt_1   0.71  0.41     0.63  0.58  0.67 -2.23  0.73
C2X-Complex_rhow_9x9_depth_lt_1   0.80  0.50     0.74  0.64  0.81  0.41  0.77
C2X-Complex_rhown_1x1_depth_lt_1  0.73  0.40     0.77  0.69  0.68  0.55  0.72
C2X-Complex_rhown_3x3_depth_lt_1  0.67  0.37     0.53  0.56  0.60  0.54  0.72
C2X-Complex_rhown_5x5_depth_lt_1  0.71  0.44     0.78  0.62  0.65  0.49  0.72
C2X-Complex_rhown_9x9_depth_lt_1  0.79  0.50     0.79  0.67  0.74  0.45  0.80
C2X_rhow_1x1_depth_lt_1           0.68  0.62     0.74  0.60  0.59  0.08  0.55
C2X_rhow_3x3_depth_lt_1           0.62  0.47     0.52  0.62  0.59 -0.88  0.65
C2X_rhow_5x5_depth_lt_1           0.48  0.54     0.69  0.57  0.50  0.54  0.76
C2X_rhow_9x9_depth_lt_1           0.68  0.65     0.70  0.70  0.67  0.37  0.79
C2X_rhown_1x1_depth_lt_1          0.61  0.53     0.59  0.50  0.52  0.33  0.53
C2X_rhown_3x3_depth_lt_1          0.61  0.32     0.69  0.51  0.60  0.03  0.66
C2X_rhown_5x5_depth_lt_1          0.50  0.43     0.60  0.45  0.43  0.72  0.71
C2X_rhown_9x9_depth_lt_1          0.68  0.60     0.76  0.55  0.59  0.47  0.77
TOA_1x1_depth_lt_1                0.36  0.01     0.24  0.37  0.45  0.27  0.41
TOA_3x3_depth_lt_1                0.63  0.02     0.45  0.42  0.51  0.45  0.50
TOA_5x5_depth_lt_1                0.60  0.04     0.49  0.46  0.42  0.38  0.57
TOA_9x9_depth_lt_1                0.60  0.04     0.42  0.46  0.54 -0.03  0.68

Metric                                              RMSE                       \
Model                               RF   SVR   XGB   CAT    EN Ensemble   KNN
C2RCC_rhow_1x1_depth_lt_1         0.62  0.30  0.39  3.00  3.93     2.28  2.82
C2RCC_rhow_3x3_depth_lt_1         0.61  0.33  0.58  2.94  3.92     2.20  2.90
C2RCC_rhow_5x5_depth_lt_1         0.70  0.35  0.78  2.72  3.79     2.23  2.86
C2RCC_rhow_9x9_depth_lt_1         0.71  0.33  0.65  2.26  3.80     2.66  2.96
C2RCC_rhown_1x1_depth_lt_1        0.56  0.30  0.58  3.33  3.99     2.54  2.70
C2RCC_rhown_3x3_depth_lt_1        0.59  0.32  0.76  2.94  3.96     2.25  2.96
C2RCC_rhown_5x5_depth_lt_1        0.71  0.35  0.77  2.85  3.82     2.65  2.74
C2RCC_rhown_9x9_depth_lt_1        0.76  0.33  0.82  2.07  3.82     2.43  2.93
C2X-Complex_rhow_1x1_depth_lt_1   0.60  0.23  0.66  2.71  3.81     3.59  2.87
C2X-Complex_rhow_3x3_depth_lt_1   0.62  0.28  0.59  2.57  3.79     3.33  3.03
C2X-Complex_rhow_5x5_depth_lt_1   0.58  0.29  0.59  2.56  3.65     2.90  3.09
C2X-Complex_rhow_9x9_depth_lt_1   0.68  0.22  0.53  2.14  3.38     2.43  2.84
C2X-Complex_rhown_1x1_depth_lt_1  0.59  0.33  0.61  2.49  3.69     2.27  2.65
C2X-Complex_rhown_3x3_depth_lt_1  0.53  0.36  0.64  2.75  3.77     3.27  3.18
C2X-Complex_rhown_5x5_depth_lt_1  0.65  0.32  0.73  2.55  3.58     2.23  2.94
C2X-Complex_rhown_9x9_depth_lt_1  0.69  0.29  0.53  2.17  3.38     2.17  2.74
C2X_rhow_1x1_depth_lt_1           0.62  0.23  0.60  2.68  2.94     2.45  3.01
C2X_rhow_3x3_depth_lt_1           0.57  0.27  0.48  2.95  3.48     3.29  2.96
C2X_rhow_5x5_depth_lt_1           0.47  0.24  0.51  3.42  3.23     2.64  3.11
C2X_rhow_9x9_depth_lt_1           0.68  0.21  0.74  2.69  2.82     2.63  2.60
C2X_rhown_1x1_depth_lt_1          0.53  0.23  0.48  2.96  3.27     3.05  3.37
C2X_rhown_3x3_depth_lt_1          0.50  0.27  0.46  2.98  3.92     2.66  3.35
C2X_rhown_5x5_depth_lt_1          0.39  0.24  0.44  3.37  3.61     3.01  3.53
C2X_rhown_9x9_depth_lt_1          0.60  0.21  0.54  2.68  3.03     2.36  3.20
TOA_1x1_depth_lt_1                0.16  0.12  0.16  2.82  3.51     3.08  2.82
TOA_3x3_depth_lt_1                0.46  0.13  0.39  2.15  3.50     2.61  2.70
TOA_5x5_depth_lt_1                0.51  0.13  0.32  2.24  3.47     2.53  2.60
TOA_9x9_depth_lt_1                0.42  0.14  0.36  2.23  3.47     2.70  2.59

Metric
Model                              LBM    LR   MLP    RF   SVR   XGB
C2RCC_rhow_1x1_depth_lt_1         2.95  2.88  2.22  2.94  3.98  3.72
C2RCC_rhow_3x3_depth_lt_1         2.91  3.45  2.23  2.96  3.91  3.10
C2RCC_rhow_5x5_depth_lt_1         2.83  2.85  2.12  2.59  3.84  2.23
C2RCC_rhow_9x9_depth_lt_1         2.63  3.41  2.29  2.56  3.90  2.82
C2RCC_rhown_1x1_depth_lt_1        2.94  3.57  2.28  3.15  4.00  3.09
C2RCC_rhown_3x3_depth_lt_1        2.93  3.42  2.34  3.04  3.93  2.35
C2RCC_rhown_5x5_depth_lt_1        2.84  2.92  2.10  2.56  3.85  2.29
C2RCC_rhown_9x9_depth_lt_1        2.59  3.20  2.30  2.35  3.90  2.00
C2X-Complex_rhow_1x1_depth_lt_1   2.61  4.39  2.53  3.02  4.17  2.80
C2X-Complex_rhow_3x3_depth_lt_1   3.16  4.52  2.52  2.95  4.05  3.04
C2X-Complex_rhow_5x5_depth_lt_1   2.76  8.57  2.47  3.11  4.01  3.05
C2X-Complex_rhow_9x9_depth_lt_1   2.10  3.68  2.27  2.68  4.20  3.26
C2X-Complex_rhown_1x1_depth_lt_1  2.68  3.19  2.54  3.06  3.91  2.98
C2X-Complex_rhown_3x3_depth_lt_1  3.01  3.24  2.53  3.25  3.82  2.85
C2X-Complex_rhown_5x5_depth_lt_1  2.84  3.42  2.54  2.81  3.92  2.49
C2X-Complex_rhown_9x9_depth_lt_1  2.43  3.53  2.14  2.63  4.00  3.27
C2X_rhow_1x1_depth_lt_1           3.04  4.56  3.20  2.94  4.19  3.03
C2X_rhow_3x3_depth_lt_1           3.07  6.54  2.84  3.12  4.07  3.44
C2X_rhow_5x5_depth_lt_1           3.36  3.22  2.35  3.48  4.16  3.33
C2X_rhow_9x9_depth_lt_1           2.72  3.77  2.17  2.70  4.25  2.44
C2X_rhown_1x1_depth_lt_1          3.29  3.92  3.27  3.26  4.18  3.43
C2X_rhown_3x3_depth_lt_1          3.01  4.70  2.80  3.36  4.08  3.50
C2X_rhown_5x5_depth_lt_1          3.59  2.54  2.55  3.71  4.15  3.57
C2X_rhown_9x9_depth_lt_1          3.06  3.46  2.26  3.00  4.24  3.22
TOA_1x1_depth_lt_1                2.63  3.01  2.73  3.24  3.32  3.25
TOA_3x3_depth_lt_1                2.47  2.61  2.50  2.60  3.29  2.77
TOA_5x5_depth_lt_1                2.70  2.79  2.32  2.46  3.30  2.92
TOA_9x9_depth_lt_1                2.39  3.59  2.00  2.69  3.28  2.83

### Optimización de hiperparámetros

In [292]:
def objective(trial, df, target, model_name):
    df = df.iloc[:,4:]
    # Mismos splits que para el entrenamiento
    train, test = train_test_split(df, test_size=0.2, random_state=42, stratify=df["High_Chl"]) # TEST 20% TRAIN 80%
    target = "Chl"
    train, val = train_test_split(train, test_size=0.25, random_state=42, stratify=train["High_Chl"])

    X = train.drop(columns=[target, 'High_Chl'])
    y = train[target]
    y_class = train["High_Chl"]

    # Definimos los folds
    skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
    
    oof_preds = np.zeros(len(train))  # Almacenar las predicciones OOF

    start = time.time()
    
    if model_name == "LBM":
        params = {
            'objective': 'regression',
            'metric': 'rmse',
            'boosting_type': 'gbdt',
            'device': 'cpu',  # usa CPU/GPU
            'verbosity': -1,
            'learning_rate': trial.suggest_float('learning_rate', 0.005, 0.1, log=True),
            'num_leaves': trial.suggest_categorical('num_leaves', [20, 40, 60, 80]),
            'max_depth': trial.suggest_int('max_depth', 5, 8),
            'min_child_samples': trial.suggest_int('min_child_samples', 5, 25),
            'subsample': trial.suggest_float('subsample', 0.6, 1.0),
            'colsample_bytree': trial.suggest_float('colsample_bytree', 0.6, 1.0),
            'n_estimators': trial.suggest_categorical('n_estimators', [500, 1000, 2000])
        }

    if model_name == "XGB":
        params = {
            'n_estimators': trial.suggest_categorical('n_estimators', [500, 1000, 2000]),
            'learning_rate': trial.suggest_float('learning_rate', 0.005, 0.1, log=True),
            'max_depth': trial.suggest_int('max_depth', 5, 8),
            'min_child_weight': trial.suggest_int('min_child_weight', 1, 4),
            'subsample': trial.suggest_float('subsample', 0.6, 1.0),
            'colsample_bytree': trial.suggest_float('colsample_bytree', 0.6, 1.0),
            'device': 'cpu',
            'objective': 'reg:squarederror',
            'tree_method': 'hist',
            'enable_categorical': True,
            'eval_metric': 'rmse'
        }
    
    if model_name == "MLP":
        # Así para evitar warning de definir como tuple
        hidden_options = {
            '50': (50,),
            '100': (100,),
            '100_50': (100, 50),
            '128_64': (128, 64)
        }
        key = trial.suggest_categorical('hidden_layer_sizes', list(hidden_options.keys()))
        params = {
            'hidden_layer_sizes': hidden_options[key],
            #'hidden_layer_sizes': trial.suggest_categorical('hidden_layer_sizes', [(50,), (100,), (100, 50), (128, 64)]),
            'activation': trial.suggest_categorical('activation', ['relu', 'tanh']),
            'solver': trial.suggest_categorical('solver', ['adam', 'sgd']),
            'alpha': trial.suggest_float('alpha', 1e-5, 1e-1, log=True),
            'learning_rate': trial.suggest_categorical('learning_rate', ['constant', 'adaptive']),
            'learning_rate_init': trial.suggest_float('learning_rate_init', 1e-4, 1e-2, log=True),
            'max_iter': 200,
            'n_iter_no_change': 25,
            'early_stopping': True,
            'validation_fraction': 0.2,
            'random_state': 42,
            'verbose': False
        }

    if model_name == "SVR":
        params = {
            'kernel': trial.suggest_categorical('kernel', ['rbf', 'sigmoid']),
            'C': trial.suggest_float('C', 0.1, 10.0, log=True),
            'epsilon': trial.suggest_float('epsilon', 0.01, 0.2),
            'gamma': trial.suggest_categorical('gamma', ['scale', 'auto']),
            'shrinking': True,
            'tol': 1e-3,
            'max_iter': -1,
            'verbose': False
        }

    if model_name == "KNN":
        params = {
            'n_neighbors': trial.suggest_int('n_neighbors', 3, 15),
            'weights': trial.suggest_categorical('weights', ['uniform', 'distance']),
            'algorithm': 'auto',
            'leaf_size': trial.suggest_int('leaf_size', 10, 40),
            'p': 2,  # 1 = manhattan, 2 = euclídea
            'metric': 'minkowski',
            'n_jobs': -1
        }

    if model_name == "LR":
        # No sirve de mucho, pero por completitud
        params = {
            'fit_intercept': trial.suggest_categorical('fit_intercept', [True, False]),
            'positive': trial.suggest_categorical('positive', [True, False]),
        }

    if model_name == "RF":
        params = {
            'n_estimators': trial.suggest_categorical('n_estimators', [100, 300, 500]),
            'max_depth': trial.suggest_int('max_depth', 5, 15),
            'min_samples_split': trial.suggest_int('min_samples_split', 2, 10),
            'min_samples_leaf': trial.suggest_int('min_samples_leaf', 1, 5),
            'bootstrap': trial.suggest_categorical('bootstrap', [True, False]),
            'random_state': 42,
            'verbose': 0
        }

    if model_name == "CAT":
        params = {
            'iterations': trial.suggest_categorical('iterations', [500, 1000, 2000]),
            'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.1, log=True),
            'depth': trial.suggest_int('depth', 4, 10),
            'l2_leaf_reg': trial.suggest_float('l2_leaf_reg', 1.0, 10.0),
            'loss_function': 'RMSE',
            'eval_metric': 'RMSE',
            'random_seed': 42,
            'early_stopping_rounds': 50,
            'verbose': False,
        }

    if model_name == "EN":
        params = {
            'alpha': trial.suggest_float('alpha', 1e-4, 10.0, log=True),
            'l1_ratio': trial.suggest_float('l1_ratio', 0.0, 1.0),
            'fit_intercept': True,
            'max_iter': 1000,
            'tol': 1e-4,
            'selection': 'cyclic',
            'random_state': 42
        }

    # Cargamos el modelo correspondiente
    model = models[model_name](**params)

    
    for fold, (train_idx, val_idx) in enumerate(skf.split(X, y_class)):
        print(f"Fold {fold+1}")
        
        X_train, X_val = X.iloc[train_idx], X.iloc[val_idx]
        y_train, y_val = y.iloc[train_idx], y.iloc[val_idx]

        if model_name in ["MLP", "SVR", "KNN", "LR", "EN"]:
            scaler_X = RobustScaler()
            scaler_y = RobustScaler()
            X_train_scaled = scaler_X.fit_transform(X_train)
            X_val_scaled = scaler_X.transform(X_val)
            y_train_scaled = scaler_y.fit_transform(y_train.values.reshape(-1, 1)).ravel()
            model.fit(X_train_scaled, y_train_scaled)
            y_pred = scaler_y.inverse_transform(model.predict(X_val_scaled).reshape(-1, 1)).ravel()
        else:
            model.fit(X_train, y_train)
            y_pred = model.predict(X_val)
        
        oof_preds[val_idx] = y_pred


    print(f"Running time: {time.time() - start:.1f} sec")
    # Calculamos el RMSE OOF
    rmse_score = np.sqrt(mean_squared_error(y, oof_preds))
    r2 = r2_score(y, oof_preds)
    print(f"OOF RMSE: {rmse_score:.2f} | R2: {r2:.2f}")
    
    return r2

In [293]:
models = {
    "XGB": XGBRegressor,
    "LBM": LGBMRegressor,
    "MLP": MLPRegressor,
    "SVR": SVR,
    "KNN": KNeighborsRegressor,
    "LR": LinearRegression,
    "RF": RandomForestRegressor,
    "CAT": CatBoostRegressor,
    "EN":  ElasticNet
}

def run_optuna(df, target, n_trials, model_name):
    results = {}

    print(f"Buscando mejores hiperparámetros para {model_name}...")
    study = optuna.create_study(direction='maximize')
    study.optimize(lambda trial: objective(trial, df, target, model_name), n_trials=n_trials, timeout= 600)
    
    print(f"\n✅ {model_name} - Mejor R2: {study.best_value:.2f}")
    print(f"📋 Parámetros: {study.best_params}\n")
    
    results[model_name] = {
        'best_params': study.best_params,
        'best_score': study.best_value,
        'study': study
    }
    return results

#df = dfs["C2X_rhown_3x3_depth_lt_1"]

# all_results = {}
n_trials = 25
# for model_name in models.keys():
#     all_results[model_name] = run_optuna(df, "Chl", n_trials, model_name)
global_results = {}

for df_name, df in dfs.items():
    print(f"🔍 Optimizando en {df_name}...")
    for model_name in models.keys():
        key = (df_name, model_name)
        result = run_optuna(df, "Chl", n_trials, model_name)
        global_results[key] = result[model_name]

[I 2025-07-11 16:08:52,346] A new study created in memory with name: no-name-b643c892-28af-4ffa-a3d5-07df1c04bcc9

🔍 Optimizando en C2RCC_rhow_5x5_depth_lt_1...
Buscando mejores hiperparámetros para XGB...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:09:01,324] Trial 0 finished with value: 0.6786606658483075 and parameters: {'n_estimators': 1000, 'learning_rate': 0.03363059712784438, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.7354620669213784, 'colsample_bytree': 0.926760985439751}. Best is trial 0 with value: 0.6786606658483075.

Running time: 9.0 sec
OOF RMSE: 1.97 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:09:11,214] Trial 1 finished with value: 0.610822465595559 and parameters: {'n_estimators': 2000, 'learning_rate': 0.0849999376336989, 'max_depth': 5, 'min_child_weight': 1, 'subsample': 0.9414025251441294, 'colsample_bytree': 0.9559502088665054}. Best is trial 0 with value: 0.6786606658483075.

Running time: 9.9 sec
OOF RMSE: 2.16 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:09:31,963] Trial 2 finished with value: 0.6731363337863433 and parameters: {'n_estimators': 2000, 'learning_rate': 0.021014421069903613, 'max_depth': 8, 'min_child_weight': 2, 'subsample': 0.7777510285901503, 'colsample_bytree': 0.7702695346839499}. Best is trial 0 with value: 0.6786606658483075.

Running time: 20.7 sec
OOF RMSE: 1.98 | R2: 0.67
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:09:35,135] Trial 3 finished with value: 0.6758244878964926 and parameters: {'n_estimators': 500, 'learning_rate': 0.0112536702764176, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.845160924737885, 'colsample_bytree': 0.982309358138255}. Best is trial 0 with value: 0.6786606658483075.

Running time: 3.2 sec
OOF RMSE: 1.97 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:09:42,208] Trial 4 finished with value: 0.6793529417133285 and parameters: {'n_estimators': 1000, 'learning_rate': 0.00550346367135371, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.8067086336735839, 'colsample_bytree': 0.9881298003306842}. Best is trial 4 with value: 0.6793529417133285.

Running time: 7.1 sec
OOF RMSE: 1.96 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:09:49,890] Trial 5 finished with value: 0.6662379182506648 and parameters: {'n_estimators': 1000, 'learning_rate': 0.07117154830883762, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.6462557690173296, 'colsample_bytree': 0.8275250667631827}. Best is trial 4 with value: 0.6793529417133285.

Running time: 7.7 sec
OOF RMSE: 2.00 | R2: 0.67
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:10:03,588] Trial 6 finished with value: 0.6652062943056638 and parameters: {'n_estimators': 2000, 'learning_rate': 0.044536498669195235, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.8005529913916307, 'colsample_bytree': 0.9229313003846936}. Best is trial 4 with value: 0.6793529417133285.

Running time: 13.7 sec
OOF RMSE: 2.01 | R2: 0.67
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:10:15,970] Trial 7 finished with value: 0.6724400974834112 and parameters: {'n_estimators': 1000, 'learning_rate': 0.010379881088570997, 'max_depth': 8, 'min_child_weight': 2, 'subsample': 0.6609112726439025, 'colsample_bytree': 0.9226619104150539}. Best is trial 4 with value: 0.6793529417133285.

Running time: 12.4 sec
OOF RMSE: 1.98 | R2: 0.67
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:10:24,875] Trial 8 finished with value: 0.6859039004930162 and parameters: {'n_estimators': 1000, 'learning_rate': 0.017502296969350004, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.9451414331404476, 'colsample_bytree': 0.7884669895873917}. Best is trial 8 with value: 0.6859039004930162.

Running time: 8.9 sec
OOF RMSE: 1.94 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:10:28,098] Trial 9 finished with value: 0.6738356712313927 and parameters: {'n_estimators': 500, 'learning_rate': 0.04761449873882993, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.8928030905217696, 'colsample_bytree': 0.9732903128943}. Best is trial 8 with value: 0.6859039004930162.

Running time: 3.2 sec
OOF RMSE: 1.98 | R2: 0.67
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:10:36,837] Trial 10 finished with value: 0.6850549892241052 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01919430924115159, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.989334971108048, 'colsample_bytree': 0.6221496715183171}. Best is trial 8 with value: 0.6859039004930162.

Running time: 8.7 sec
OOF RMSE: 1.95 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:10:47,146] Trial 11 finished with value: 0.6814896392226362 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01875029802350627, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.9999951431942774, 'colsample_bytree': 0.6013464801117835}. Best is trial 8 with value: 0.6859039004930162.

Running time: 10.3 sec
OOF RMSE: 1.96 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:10:54,164] Trial 12 finished with value: 0.6909050584740044 and parameters: {'n_estimators': 1000, 'learning_rate': 0.0130122114774817, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.999414860283199, 'colsample_bytree': 0.6267787883870157}. Best is trial 12 with value: 0.6909050584740044.

Running time: 7.0 sec
OOF RMSE: 1.93 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:11:01,971] Trial 13 finished with value: 0.6929370474490688 and parameters: {'n_estimators': 1000, 'learning_rate': 0.011459665750357641, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.9205746835338623, 'colsample_bytree': 0.6912888985023633}. Best is trial 13 with value: 0.6929370474490688.

Running time: 7.8 sec
OOF RMSE: 1.92 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:11:10,126] Trial 14 finished with value: 0.6939365275964477 and parameters: {'n_estimators': 1000, 'learning_rate': 0.008950301899598287, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.8935541677588088, 'colsample_bytree': 0.6814636086640992}. Best is trial 14 with value: 0.6939365275964477.

Running time: 8.1 sec
OOF RMSE: 1.92 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:11:14,655] Trial 15 finished with value: 0.6751427600615036 and parameters: {'n_estimators': 500, 'learning_rate': 0.006485411236794229, 'max_depth': 6, 'min_child_weight': 1, 'subsample': 0.8747925859726051, 'colsample_bytree': 0.6986273410065509}. Best is trial 14 with value: 0.6939365275964477.

Running time: 4.5 sec
OOF RMSE: 1.98 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:11:22,913] Trial 16 finished with value: 0.6968446713876776 and parameters: {'n_estimators': 1000, 'learning_rate': 0.008062416895617461, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.9261298417244266, 'colsample_bytree': 0.6940355228875539}. Best is trial 16 with value: 0.6968446713876776.

Running time: 8.3 sec
OOF RMSE: 1.91 | R2: 0.70
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:11:32,578] Trial 17 finished with value: 0.6816066856774985 and parameters: {'n_estimators': 1000, 'learning_rate': 0.007777957344066632, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.854672271960095, 'colsample_bytree': 0.7085179396903637}. Best is trial 16 with value: 0.6968446713876776.

Running time: 9.7 sec
OOF RMSE: 1.96 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:11:46,398] Trial 18 finished with value: 0.683967215437841 and parameters: {'n_estimators': 2000, 'learning_rate': 0.008230611864037922, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.7429380351828193, 'colsample_bytree': 0.737964942536621}. Best is trial 16 with value: 0.6968446713876776.

Running time: 13.8 sec
OOF RMSE: 1.95 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:11:52,416] Trial 19 finished with value: 0.6874443704802212 and parameters: {'n_estimators': 500, 'learning_rate': 0.005260351922726516, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.9026812015375248, 'colsample_bytree': 0.8531119883581977}. Best is trial 16 with value: 0.6968446713876776.

Running time: 6.0 sec
OOF RMSE: 1.94 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:12:00,272] Trial 20 finished with value: 0.678591727392535 and parameters: {'n_estimators': 1000, 'learning_rate': 0.031587275491196214, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.8347944937052237, 'colsample_bytree': 0.6620822203644307}. Best is trial 16 with value: 0.6968446713876776.

Running time: 7.8 sec
OOF RMSE: 1.97 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:12:07,964] Trial 21 finished with value: 0.6899215281204478 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01370292024534046, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.9377191583023423, 'colsample_bytree': 0.6836496991274451}. Best is trial 16 with value: 0.6968446713876776.

Running time: 7.7 sec
OOF RMSE: 1.93 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:12:16,068] Trial 22 finished with value: 0.6977084098853871 and parameters: {'n_estimators': 1000, 'learning_rate': 0.008490905014217147, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.9117231361249971, 'colsample_bytree': 0.7381845712236873}. Best is trial 22 with value: 0.6977084098853871.

Running time: 8.1 sec
OOF RMSE: 1.91 | R2: 0.70
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:12:24,174] Trial 23 finished with value: 0.6895349095717234 and parameters: {'n_estimators': 1000, 'learning_rate': 0.00836827318982966, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.8768224458818907, 'colsample_bytree': 0.7412171185292592}. Best is trial 22 with value: 0.6977084098853871.

Running time: 8.1 sec
OOF RMSE: 1.93 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:12:34,533] Trial 24 finished with value: 0.6735914008235351 and parameters: {'n_estimators': 1000, 'learning_rate': 0.0070871823059809776, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.9637332776398859, 'colsample_bytree': 0.7456595383303942}. Best is trial 22 with value: 0.6977084098853871.
[I 2025-07-11 16:12:34,534] A new study created in memory with name: no-name-f24761c0-d4df-4712-b383-59be0010c477

Running time: 10.4 sec
OOF RMSE: 1.98 | R2: 0.67

✅ XGB - Mejor R2: 0.70
📋 Parámetros: {'n_estimators': 1000, 'learning_rate': 0.008490905014217147, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.9117231361249971, 'colsample_bytree': 0.7381845712236873}

Buscando mejores hiperparámetros para LBM...
Fold 1
Fold 2
Fold 3

[I 2025-07-11 16:12:34,944] Trial 0 finished with value: 0.5783375019597115 and parameters: {'learning_rate': 0.014708472440505499, 'num_leaves': 40, 'max_depth': 5, 'min_child_samples': 24, 'subsample': 0.7703862056637745, 'colsample_bytree': 0.7821236443360082, 'n_estimators': 1000}. Best is trial 0 with value: 0.5783375019597115.

Fold 4
Fold 5
Running time: 0.4 sec
OOF RMSE: 2.25 | R2: 0.58
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 16:12:35,377] Trial 1 finished with value: 0.5815040381139336 and parameters: {'learning_rate': 0.04091366899937118, 'num_leaves': 40, 'max_depth': 5, 'min_child_samples': 15, 'subsample': 0.8855958335954428, 'colsample_bytree': 0.8136215748945863, 'n_estimators': 1000}. Best is trial 1 with value: 0.5815040381139336.

Fold 5
Running time: 0.4 sec
OOF RMSE: 2.24 | R2: 0.58
Fold 1
Fold 2

[I 2025-07-11 16:12:35,714] Trial 2 finished with value: 0.6132163191469162 and parameters: {'learning_rate': 0.006854567751757085, 'num_leaves': 60, 'max_depth': 8, 'min_child_samples': 12, 'subsample': 0.8477175440361847, 'colsample_bytree': 0.6384564359211511, 'n_estimators': 500}. Best is trial 2 with value: 0.6132163191469162.

Fold 3
Fold 4
Fold 5
Running time: 0.3 sec
OOF RMSE: 2.16 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:12:35,990] Trial 3 finished with value: 0.595807238482148 and parameters: {'learning_rate': 0.02739371575464374, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 9, 'subsample': 0.6336283037958877, 'colsample_bytree': 0.8779200523605662, 'n_estimators': 500}. Best is trial 2 with value: 0.6132163191469162.

Running time: 0.3 sec
OOF RMSE: 2.20 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:12:36,237] Trial 4 finished with value: 0.5720220189002052 and parameters: {'learning_rate': 0.05309586929498909, 'num_leaves': 80, 'max_depth': 5, 'min_child_samples': 14, 'subsample': 0.6922651958929851, 'colsample_bytree': 0.9484635153899637, 'n_estimators': 500}. Best is trial 2 with value: 0.6132163191469162.

Running time: 0.2 sec
OOF RMSE: 2.27 | R2: 0.57
Fold 1
Fold 2
Fold 3

[I 2025-07-11 16:12:36,714] Trial 5 finished with value: 0.5753431242979345 and parameters: {'learning_rate': 0.01270512499889815, 'num_leaves': 60, 'max_depth': 6, 'min_child_samples': 22, 'subsample': 0.7888014416576707, 'colsample_bytree': 0.7535497695949754, 'n_estimators': 1000}. Best is trial 2 with value: 0.6132163191469162.

Fold 4
Fold 5
Running time: 0.5 sec
OOF RMSE: 2.26 | R2: 0.58
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:12:37,747] Trial 6 finished with value: 0.6031250217664486 and parameters: {'learning_rate': 0.010950730204619093, 'num_leaves': 40, 'max_depth': 7, 'min_child_samples': 20, 'subsample': 0.6530570591781483, 'colsample_bytree': 0.793789669700327, 'n_estimators': 2000}. Best is trial 2 with value: 0.6132163191469162.

Running time: 1.0 sec
OOF RMSE: 2.18 | R2: 0.60
Fold 1
Fold 2
Fold 3

[I 2025-07-11 16:12:38,082] Trial 7 finished with value: 0.581513890863621 and parameters: {'learning_rate': 0.013539336667100122, 'num_leaves': 20, 'max_depth': 8, 'min_child_samples': 14, 'subsample': 0.7259253170061906, 'colsample_bytree': 0.7277482258090023, 'n_estimators': 500}. Best is trial 2 with value: 0.6132163191469162.

Fold 4
Fold 5
Running time: 0.3 sec
OOF RMSE: 2.24 | R2: 0.58
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 16:12:38,586] Trial 8 finished with value: 0.5731761237407104 and parameters: {'learning_rate': 0.018412868473118026, 'num_leaves': 40, 'max_depth': 7, 'min_child_samples': 18, 'subsample': 0.7396207778799728, 'colsample_bytree': 0.6091821125067219, 'n_estimators': 1000}. Best is trial 2 with value: 0.6132163191469162.

Fold 5
Running time: 0.5 sec
OOF RMSE: 2.26 | R2: 0.57
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 16:12:39,067] Trial 9 finished with value: 0.6012868916687004 and parameters: {'learning_rate': 0.007910893428260712, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 16, 'subsample': 0.8484097471990308, 'colsample_bytree': 0.7713265141798422, 'n_estimators': 1000}. Best is trial 2 with value: 0.6132163191469162.

Fold 5
Running time: 0.5 sec
OOF RMSE: 2.19 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:12:40,528] Trial 10 finished with value: 0.6603418081780603 and parameters: {'learning_rate': 0.005099002917410783, 'num_leaves': 60, 'max_depth': 8, 'min_child_samples': 6, 'subsample': 0.9723186731255311, 'colsample_bytree': 0.6048206898700607, 'n_estimators': 2000}. Best is trial 10 with value: 0.6603418081780603.

Running time: 1.5 sec
OOF RMSE: 2.02 | R2: 0.66
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:12:42,101] Trial 11 finished with value: 0.6608652992809261 and parameters: {'learning_rate': 0.0051217055677700175, 'num_leaves': 60, 'max_depth': 8, 'min_child_samples': 5, 'subsample': 0.9990302824152548, 'colsample_bytree': 0.6007049635458502, 'n_estimators': 2000}. Best is trial 11 with value: 0.6608652992809261.

Running time: 1.6 sec
OOF RMSE: 2.02 | R2: 0.66
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:12:43,722] Trial 12 finished with value: 0.661553224674015 and parameters: {'learning_rate': 0.005358791298774515, 'num_leaves': 60, 'max_depth': 8, 'min_child_samples': 5, 'subsample': 0.9932983148816839, 'colsample_bytree': 0.6888334967634573, 'n_estimators': 2000}. Best is trial 12 with value: 0.661553224674015.

Running time: 1.6 sec
OOF RMSE: 2.02 | R2: 0.66
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:12:45,663] Trial 13 finished with value: 0.6595565231508402 and parameters: {'learning_rate': 0.08298627108145196, 'num_leaves': 60, 'max_depth': 7, 'min_child_samples': 5, 'subsample': 0.9936249640908185, 'colsample_bytree': 0.6883165973197799, 'n_estimators': 2000}. Best is trial 12 with value: 0.661553224674015.

Running time: 1.9 sec
OOF RMSE: 2.02 | R2: 0.66
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:12:46,963] Trial 14 finished with value: 0.6179521079730974 and parameters: {'learning_rate': 0.005075279499655344, 'num_leaves': 60, 'max_depth': 8, 'min_child_samples': 9, 'subsample': 0.9279005563818443, 'colsample_bytree': 0.679350425045368, 'n_estimators': 2000}. Best is trial 12 with value: 0.661553224674015.

Running time: 1.3 sec
OOF RMSE: 2.14 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:12:48,124] Trial 15 finished with value: 0.6284903661924881 and parameters: {'learning_rate': 0.008587368651166459, 'num_leaves': 80, 'max_depth': 7, 'min_child_samples': 8, 'subsample': 0.934850934058759, 'colsample_bytree': 0.6669779775301631, 'n_estimators': 2000}. Best is trial 12 with value: 0.661553224674015.

Running time: 1.2 sec
OOF RMSE: 2.11 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:12:49,464] Trial 16 finished with value: 0.6401391488932116 and parameters: {'learning_rate': 0.006655192478564493, 'num_leaves': 60, 'max_depth': 8, 'min_child_samples': 11, 'subsample': 0.9390107978985863, 'colsample_bytree': 0.6950703170509681, 'n_estimators': 2000}. Best is trial 12 with value: 0.661553224674015.

Running time: 1.3 sec
OOF RMSE: 2.08 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:12:51,081] Trial 17 finished with value: 0.6632213469440267 and parameters: {'learning_rate': 0.022185978632140526, 'num_leaves': 60, 'max_depth': 8, 'min_child_samples': 5, 'subsample': 0.9954147898146568, 'colsample_bytree': 0.8503820302706597, 'n_estimators': 2000}. Best is trial 17 with value: 0.6632213469440267.

Running time: 1.6 sec
OOF RMSE: 2.01 | R2: 0.66
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:12:52,270] Trial 18 finished with value: 0.6382864984273178 and parameters: {'learning_rate': 0.026248483582790617, 'num_leaves': 60, 'max_depth': 7, 'min_child_samples': 11, 'subsample': 0.8762670465334397, 'colsample_bytree': 0.8928611685122552, 'n_estimators': 2000}. Best is trial 17 with value: 0.6632213469440267.

Running time: 1.2 sec
OOF RMSE: 2.08 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:12:53,982] Trial 19 finished with value: 0.6362663726604789 and parameters: {'learning_rate': 0.09640712398582552, 'num_leaves': 80, 'max_depth': 8, 'min_child_samples': 7, 'subsample': 0.9570883420440911, 'colsample_bytree': 0.8396896019905913, 'n_estimators': 2000}. Best is trial 17 with value: 0.6632213469440267.

Running time: 1.7 sec
OOF RMSE: 2.09 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:12:55,301] Trial 20 finished with value: 0.6202389662123856 and parameters: {'learning_rate': 0.04493124212946322, 'num_leaves': 60, 'max_depth': 7, 'min_child_samples': 8, 'subsample': 0.9098176091092582, 'colsample_bytree': 0.8651988584407669, 'n_estimators': 2000}. Best is trial 17 with value: 0.6632213469440267.

Running time: 1.3 sec
OOF RMSE: 2.14 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:12:57,007] Trial 21 finished with value: 0.6607235796664407 and parameters: {'learning_rate': 0.009689117638491123, 'num_leaves': 60, 'max_depth': 8, 'min_child_samples': 5, 'subsample': 0.9952470693289606, 'colsample_bytree': 0.9915404179308678, 'n_estimators': 2000}. Best is trial 17 with value: 0.6632213469440267.

Running time: 1.7 sec
OOF RMSE: 2.02 | R2: 0.66
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:12:58,601] Trial 22 finished with value: 0.667321133437436 and parameters: {'learning_rate': 0.02073824304970037, 'num_leaves': 60, 'max_depth': 8, 'min_child_samples': 5, 'subsample': 0.9938714541767556, 'colsample_bytree': 0.7278831706716934, 'n_estimators': 2000}. Best is trial 22 with value: 0.667321133437436.

Running time: 1.6 sec
OOF RMSE: 2.00 | R2: 0.67
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:13:00,004] Trial 23 finished with value: 0.6345417341436652 and parameters: {'learning_rate': 0.02135965000090923, 'num_leaves': 60, 'max_depth': 8, 'min_child_samples': 7, 'subsample': 0.9625093109447423, 'colsample_bytree': 0.7264780991107086, 'n_estimators': 2000}. Best is trial 22 with value: 0.667321133437436.

Running time: 1.4 sec
OOF RMSE: 2.10 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:13:01,353] Trial 24 finished with value: 0.6032531684144627 and parameters: {'learning_rate': 0.017412582015948794, 'num_leaves': 60, 'max_depth': 8, 'min_child_samples': 9, 'subsample': 0.8995564949859128, 'colsample_bytree': 0.7259538194427065, 'n_estimators': 2000}. Best is trial 22 with value: 0.667321133437436.
[I 2025-07-11 16:13:01,354] A new study created in memory with name: no-name-00ef6016-a5bc-4325-8be9-4a4b7916d596

Running time: 1.3 sec
OOF RMSE: 2.18 | R2: 0.60

✅ LBM - Mejor R2: 0.67
📋 Parámetros: {'learning_rate': 0.02073824304970037, 'num_leaves': 60, 'max_depth': 8, 'min_child_samples': 5, 'subsample': 0.9938714541767556, 'colsample_bytree': 0.7278831706716934, 'n_estimators': 2000}

Buscando mejores hiperparámetros para MLP...
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 16:13:02,315] Trial 0 finished with value: 0.4279900710746396 and parameters: {'hidden_layer_sizes': '50', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.0002042179911354663, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00042193323932791766}. Best is trial 0 with value: 0.4279900710746396.

Fold 5
Running time: 1.0 sec
OOF RMSE: 2.62 | R2: 0.43
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 16:13:04,616] Trial 1 finished with value: 0.36881340572028765 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0009994024725738452, 'learning_rate': 'constant', 'learning_rate_init': 0.0001283596872114088}. Best is trial 0 with value: 0.4279900710746396.

Running time: 2.3 sec
OOF RMSE: 2.75 | R2: 0.37
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 16:13:07,326] Trial 2 finished with value: 0.4732835443009714 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.059787687658012685, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0002904008720247523}. Best is trial 2 with value: 0.4732835443009714.

Running time: 2.7 sec
OOF RMSE: 2.52 | R2: 0.47
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 16:13:09,840] Trial 3 finished with value: 0.5625142450584153 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.07857269300324146, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0011552251597902563}. Best is trial 3 with value: 0.5625142450584153.

Running time: 2.5 sec
OOF RMSE: 2.29 | R2: 0.56
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:13:11,412] Trial 4 finished with value: 0.6952192016688827 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.06370161371015381, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00508103158718387}. Best is trial 4 with value: 0.6952192016688827.

Running time: 1.6 sec
OOF RMSE: 1.91 | R2: 0.70
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 16:13:13,399] Trial 5 finished with value: 0.4278896219495645 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.0022638938109279874, 'learning_rate': 'constant', 'learning_rate_init': 0.0001444753133110803}. Best is trial 4 with value: 0.6952192016688827.

Running time: 2.0 sec
OOF RMSE: 2.62 | R2: 0.43
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 16:13:13,965] Trial 6 finished with value: 0.4634725869650391 and parameters: {'hidden_layer_sizes': '50', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.0012342244754806704, 'learning_rate': 'constant', 'learning_rate_init': 0.0018607081263564236}. Best is trial 4 with value: 0.6952192016688827.

Fold 5
Running time: 0.6 sec
OOF RMSE: 2.54 | R2: 0.46
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:13:15,088] Trial 7 finished with value: 0.6150568105739951 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.09659020737729306, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00181684596689348}. Best is trial 4 with value: 0.6952192016688827.

Running time: 1.1 sec
OOF RMSE: 2.15 | R2: 0.62
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 16:13:17,273] Trial 8 finished with value: 0.472100071879361 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.00038816435509514164, 'learning_rate': 'constant', 'learning_rate_init': 0.00010185117034308944}. Best is trial 4 with value: 0.6952192016688827.

Running time: 2.2 sec
OOF RMSE: 2.52 | R2: 0.47
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 16:13:20,300] Trial 9 finished with value: 0.34172346641242013 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 1.1193087960221481e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00022292695109015463}. Best is trial 4 with value: 0.6952192016688827.

Running time: 3.0 sec
OOF RMSE: 2.81 | R2: 0.34
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:13:21,179] Trial 10 finished with value: 0.6764863143326632 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.00882154183564605, 'learning_rate': 'adaptive', 'learning_rate_init': 0.008974286102617439}. Best is trial 4 with value: 0.6952192016688827.

Running time: 0.9 sec
OOF RMSE: 1.97 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 16:13:22,021] Trial 11 finished with value: 0.676529389107416 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.010174006391138503, 'learning_rate': 'adaptive', 'learning_rate_init': 0.009778288532042259}. Best is trial 4 with value: 0.6952192016688827.

Fold 5
Running time: 0.8 sec
OOF RMSE: 1.97 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:13:23,052] Trial 12 finished with value: 0.6815760970771472 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.012689934706814307, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00886469547631148}. Best is trial 4 with value: 0.6952192016688827.

Running time: 1.0 sec
OOF RMSE: 1.96 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:13:24,156] Trial 13 finished with value: 0.6406211245395232 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.018552546318333356, 'learning_rate': 'adaptive', 'learning_rate_init': 0.003773160813306813}. Best is trial 4 with value: 0.6952192016688827.

Running time: 1.1 sec
OOF RMSE: 2.08 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:13:25,192] Trial 14 finished with value: 0.6395704304092713 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.020664862959822835, 'learning_rate': 'adaptive', 'learning_rate_init': 0.004350343427957234}. Best is trial 4 with value: 0.6952192016688827.

Running time: 1.0 sec
OOF RMSE: 2.08 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:13:26,660] Trial 15 finished with value: 0.6988355877442272 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.005677603912486301, 'learning_rate': 'adaptive', 'learning_rate_init': 0.004569000726524064}. Best is trial 15 with value: 0.6988355877442272.

Running time: 1.5 sec
OOF RMSE: 1.90 | R2: 0.70
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:13:28,230] Trial 16 finished with value: 0.6943859156462062 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.003910264521815323, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0043610107735626655}. Best is trial 15 with value: 0.6988355877442272.

Running time: 1.6 sec
OOF RMSE: 1.92 | R2: 0.69
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

[I 2025-07-11 16:13:29,980] Trial 17 finished with value: 0.5970159668032375 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.00017129774640148123, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0025561954868468773}. Best is trial 15 with value: 0.6988355877442272.

Running time: 1.7 sec
OOF RMSE: 2.20 | R2: 0.60
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

[I 2025-07-11 16:13:32,476] Trial 18 finished with value: 0.5619442458643602 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.03795982514473716, 'learning_rate': 'constant', 'learning_rate_init': 0.0008197950990040773}. Best is trial 15 with value: 0.6988355877442272.

Running time: 2.5 sec
OOF RMSE: 2.29 | R2: 0.56
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

[I 2025-07-11 16:13:35,086] Trial 19 finished with value: 0.5558901905301348 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'adam', 'alpha': 3.501201219785624e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0007498501071532671}. Best is trial 15 with value: 0.6988355877442272.

Running time: 2.6 sec
OOF RMSE: 2.31 | R2: 0.56
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:13:36,699] Trial 20 finished with value: 0.6902842018658197 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.004667571094352756, 'learning_rate': 'adaptive', 'learning_rate_init': 0.005801045635119308}. Best is trial 15 with value: 0.6988355877442272.

Running time: 1.6 sec
OOF RMSE: 1.93 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:13:38,255] Trial 21 finished with value: 0.6940235862808315 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.003974280844288013, 'learning_rate': 'adaptive', 'learning_rate_init': 0.004897936389043672}. Best is trial 15 with value: 0.6988355877442272.

Running time: 1.5 sec
OOF RMSE: 1.92 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:13:39,962] Trial 22 finished with value: 0.6043745993839554 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.004595401549356461, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0032292670525547436}. Best is trial 15 with value: 0.6988355877442272.

Running time: 1.7 sec
OOF RMSE: 2.18 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:13:41,609] Trial 23 finished with value: 0.6860505885627282 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.031882298121903324, 'learning_rate': 'adaptive', 'learning_rate_init': 0.006611703692497563}. Best is trial 15 with value: 0.6988355877442272.

Running time: 1.6 sec
OOF RMSE: 1.94 | R2: 0.69
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 16:13:42,457] Trial 24 finished with value: 0.36037394758392927 and parameters: {'hidden_layer_sizes': '50', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.001422540762551467, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0023713624947277016}. Best is trial 15 with value: 0.6988355877442272.
[I 2025-07-11 16:13:42,459] A new study created in memory with name: no-name-c27298ff-cdde-4e8e-82ed-d1604a53c7a9
[I 2025-07-11 16:13:42,550] Trial 0 finished with value: 0.2924277614288163 and parameters: {'kernel': 'rbf', 'C': 1.0752586235770745, 'epsilon': 0.18117853267702455, 'gamma': 'scale'}. Best is trial 0 with value: 0.2924277614288163.

Fold 5
Running time: 0.8 sec
OOF RMSE: 2.77 | R2: 0.36

✅ MLP - Mejor R2: 0.70
📋 Parámetros: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.005677603912486301, 'learning_rate': 'adaptive', 'learning_rate_init': 0.004569000726524064}

Buscando mejores hiperparámetros para SVR...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.92 | R2: 0.29
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 16:13:42,623] Trial 1 finished with value: 0.08594281482848132 and parameters: {'kernel': 'sigmoid', 'C': 0.20702785795731554, 'epsilon': 0.1417072574958557, 'gamma': 'auto'}. Best is trial 0 with value: 0.2924277614288163.
[I 2025-07-11 16:13:42,702] Trial 2 finished with value: 0.1500818007768997 and parameters: {'kernel': 'rbf', 'C': 0.2507901684384531, 'epsilon': 0.05976880448343545, 'gamma': 'scale'}. Best is trial 0 with value: 0.2924277614288163.
[I 2025-07-11 16:13:42,776] Trial 3 finished with value: -27.01071068383332 and parameters: {'kernel': 'sigmoid', 'C': 2.715972366665252, 'epsilon': 0.18286371870550297, 'gamma': 'scale'}. Best is trial 0 with value: 0.2924277614288163.

Fold 5
Running time: 0.1 sec
OOF RMSE: 3.31 | R2: 0.09
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.20 | R2: 0.15
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 18.35 | R2: -27.01
Fold 1
Fold 2
Fold 3

[I 2025-07-11 16:13:42,851] Trial 4 finished with value: -42.22517774295128 and parameters: {'kernel': 'sigmoid', 'C': 4.626862495515479, 'epsilon': 0.19459888570240672, 'gamma': 'auto'}. Best is trial 0 with value: 0.2924277614288163.
[I 2025-07-11 16:13:42,932] Trial 5 finished with value: -24.20167598265111 and parameters: {'kernel': 'sigmoid', 'C': 2.5612812699643794, 'epsilon': 0.1422715269601556, 'gamma': 'scale'}. Best is trial 0 with value: 0.2924277614288163.
[I 2025-07-11 16:13:43,002] Trial 6 finished with value: 0.13420335162274333 and parameters: {'kernel': 'rbf', 'C': 0.2103025952796188, 'epsilon': 0.09374536282495165, 'gamma': 'auto'}. Best is trial 0 with value: 0.2924277614288163.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 22.79 | R2: -42.23
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 17.40 | R2: -24.20
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.23 | R2: 0.13
Fold 1
Fold 2

[I 2025-07-11 16:13:43,084] Trial 7 finished with value: 0.5723442485072779 and parameters: {'kernel': 'rbf', 'C': 8.626634589375012, 'epsilon': 0.13885755984134074, 'gamma': 'scale'}. Best is trial 7 with value: 0.5723442485072779.
[I 2025-07-11 16:13:43,163] Trial 8 finished with value: -100.71404251077455 and parameters: {'kernel': 'sigmoid', 'C': 7.220593046640033, 'epsilon': 0.021806749924237635, 'gamma': 'auto'}. Best is trial 7 with value: 0.5723442485072779.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.27 | R2: 0.57
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 34.96 | R2: -100.71
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:13:43,240] Trial 9 finished with value: -137.1880437049621 and parameters: {'kernel': 'sigmoid', 'C': 6.249265612427432, 'epsilon': 0.11044620274037026, 'gamma': 'scale'}. Best is trial 7 with value: 0.5723442485072779.
[I 2025-07-11 16:13:43,319] Trial 10 finished with value: 0.23996575674065745 and parameters: {'kernel': 'rbf', 'C': 0.6218253082846064, 'epsilon': 0.13661794822559076, 'gamma': 'scale'}. Best is trial 7 with value: 0.5723442485072779.
[I 2025-07-11 16:13:43,394] Trial 11 finished with value: 0.28451561646959767 and parameters: {'kernel': 'rbf', 'C': 0.9999439786176145, 'epsilon': 0.169095983911972, 'gamma': 'scale'}. Best is trial 7 with value: 0.5723442485072779.

Running time: 0.1 sec
OOF RMSE: 40.75 | R2: -137.19
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.02 | R2: 0.24
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.93 | R2: 0.28
Fold 1
Fold 2
Fold 3

[I 2025-07-11 16:13:43,469] Trial 12 finished with value: 0.21272026202192518 and parameters: {'kernel': 'rbf', 'C': 0.46917517295107625, 'epsilon': 0.16438304586910488, 'gamma': 'scale'}. Best is trial 7 with value: 0.5723442485072779.
[I 2025-07-11 16:13:43,552] Trial 13 finished with value: 0.3679717807671653 and parameters: {'kernel': 'rbf', 'C': 1.9393168221299009, 'epsilon': 0.10417211277857212, 'gamma': 'scale'}. Best is trial 7 with value: 0.5723442485072779.
[I 2025-07-11 16:13:43,635] Trial 14 finished with value: 0.5815325106326689 and parameters: {'kernel': 'rbf', 'C': 9.6042692041952, 'epsilon': 0.08926651898086169, 'gamma': 'scale'}. Best is trial 14 with value: 0.5815325106326689.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.08 | R2: 0.21
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.76 | R2: 0.37
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.24 | R2: 0.58
Fold 1

[I 2025-07-11 16:13:43,724] Trial 15 finished with value: 0.5808736315223293 and parameters: {'kernel': 'rbf', 'C': 9.669071980484928, 'epsilon': 0.0665572569320503, 'gamma': 'scale'}. Best is trial 14 with value: 0.5815325106326689.
[I 2025-07-11 16:13:43,812] Trial 16 finished with value: 0.585376445090346 and parameters: {'kernel': 'rbf', 'C': 9.973087703929847, 'epsilon': 0.06464202847072528, 'gamma': 'scale'}. Best is trial 16 with value: 0.585376445090346.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.24 | R2: 0.58
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.23 | R2: 0.59
Fold 1
Fold 2
Fold 3

[I 2025-07-11 16:13:43,898] Trial 17 finished with value: 0.4757756921402104 and parameters: {'kernel': 'rbf', 'C': 4.291403744407377, 'epsilon': 0.04328416093218952, 'gamma': 'scale'}. Best is trial 16 with value: 0.585376445090346.
[I 2025-07-11 16:13:43,980] Trial 18 finished with value: 0.0979680196187489 and parameters: {'kernel': 'rbf', 'C': 0.11923112939391317, 'epsilon': 0.07970088741824156, 'gamma': 'auto'}. Best is trial 16 with value: 0.585376445090346.
[I 2025-07-11 16:13:44,064] Trial 19 finished with value: 0.45470893292687975 and parameters: {'kernel': 'rbf', 'C': 3.6282205535815657, 'epsilon': 0.03215040592137175, 'gamma': 'scale'}. Best is trial 16 with value: 0.585376445090346.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.51 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.29 | R2: 0.10
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.56 | R2: 0.45

[I 2025-07-11 16:13:44,146] Trial 20 finished with value: 0.3244107929655773 and parameters: {'kernel': 'rbf', 'C': 1.4420035234118007, 'epsilon': 0.04698432349924439, 'gamma': 'scale'}. Best is trial 16 with value: 0.585376445090346.
[I 2025-07-11 16:13:44,234] Trial 21 finished with value: 0.5495168068894426 and parameters: {'kernel': 'rbf', 'C': 7.579733272171924, 'epsilon': 0.06892475221107114, 'gamma': 'scale'}. Best is trial 16 with value: 0.585376445090346.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.85 | R2: 0.32
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.33 | R2: 0.55
Fold 1
Fold 2
Fold 3

[I 2025-07-11 16:13:44,323] Trial 22 finished with value: 0.5802423467594077 and parameters: {'kernel': 'rbf', 'C': 9.51584750060351, 'epsilon': 0.08955842646965526, 'gamma': 'scale'}. Best is trial 16 with value: 0.585376445090346.
[I 2025-07-11 16:13:44,421] Trial 23 finished with value: 0.5002578347311921 and parameters: {'kernel': 'rbf', 'C': 5.332080078082694, 'epsilon': 0.012195800745011968, 'gamma': 'scale'}. Best is trial 16 with value: 0.585376445090346.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.25 | R2: 0.58
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.45 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 16:13:44,512] Trial 24 finished with value: 0.5837030996100157 and parameters: {'kernel': 'rbf', 'C': 9.854779286889352, 'epsilon': 0.06698081923412605, 'gamma': 'scale'}. Best is trial 16 with value: 0.585376445090346.
[I 2025-07-11 16:13:44,513] A new study created in memory with name: no-name-2e0a207a-edc2-41ba-a1d1-023d5969d32d
[I 2025-07-11 16:13:44,581] Trial 0 finished with value: 0.5712673252052914 and parameters: {'n_neighbors': 13, 'weights': 'uniform', 'leaf_size': 12}. Best is trial 0 with value: 0.5712673252052914.
[I 2025-07-11 16:13:44,648] Trial 1 finished with value: 0.6115999863306377 and parameters: {'n_neighbors': 10, 'weights': 'uniform', 'leaf_size': 23}. Best is trial 1 with value: 0.6115999863306377.

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.24 | R2: 0.58

✅ SVR - Mejor R2: 0.59
📋 Parámetros: {'kernel': 'rbf', 'C': 9.973087703929847, 'epsilon': 0.06464202847072528, 'gamma': 'scale'}

Buscando mejores hiperparámetros para KNN...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.27 | R2: 0.57
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.16 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 16:13:44,712] Trial 2 finished with value: 0.7606619021774778 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'leaf_size': 39}. Best is trial 2 with value: 0.7606619021774778.
[I 2025-07-11 16:13:44,797] Trial 3 finished with value: 0.5966371618688109 and parameters: {'n_neighbors': 9, 'weights': 'uniform', 'leaf_size': 17}. Best is trial 2 with value: 0.7606619021774778.
[I 2025-07-11 16:13:44,875] Trial 4 finished with value: 0.671258165247234 and parameters: {'n_neighbors': 11, 'weights': 'distance', 'leaf_size': 16}. Best is trial 2 with value: 0.7606619021774778.

Fold 5
Running time: 0.1 sec
OOF RMSE: 1.70 | R2: 0.76
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.20 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.99 | R2: 0.67
Fold 1
Fold 2

[I 2025-07-11 16:13:44,942] Trial 5 finished with value: 0.6653908562119693 and parameters: {'n_neighbors': 12, 'weights': 'distance', 'leaf_size': 19}. Best is trial 2 with value: 0.7606619021774778.
[I 2025-07-11 16:13:45,011] Trial 6 finished with value: 0.72753274735572 and parameters: {'n_neighbors': 5, 'weights': 'uniform', 'leaf_size': 10}. Best is trial 2 with value: 0.7606619021774778.
[I 2025-07-11 16:13:45,075] Trial 7 finished with value: 0.6426695564907445 and parameters: {'n_neighbors': 14, 'weights': 'distance', 'leaf_size': 24}. Best is trial 2 with value: 0.7606619021774778.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.01 | R2: 0.67
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.81 | R2: 0.73
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.07 | R2: 0.64
Fold 1
Fold 2
Fold 3

[I 2025-07-11 16:13:45,142] Trial 8 finished with value: 0.7606619021774778 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'leaf_size': 24}. Best is trial 2 with value: 0.7606619021774778.
[I 2025-07-11 16:13:45,208] Trial 9 finished with value: 0.72753274735572 and parameters: {'n_neighbors': 5, 'weights': 'uniform', 'leaf_size': 29}. Best is trial 2 with value: 0.7606619021774778.
[I 2025-07-11 16:13:45,282] Trial 10 finished with value: 0.7881537821929324 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 40}. Best is trial 10 with value: 0.7881537821929324.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.70 | R2: 0.76
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.81 | R2: 0.73
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.60 | R2: 0.79
Fold 1
Fold 2

[I 2025-07-11 16:13:45,357] Trial 11 finished with value: 0.7018505804897301 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'leaf_size': 40}. Best is trial 10 with value: 0.7881537821929324.
[I 2025-07-11 16:13:45,432] Trial 12 finished with value: 0.7881537821929324 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 39}. Best is trial 10 with value: 0.7881537821929324.
[I 2025-07-11 16:13:45,501] Trial 13 finished with value: 0.7881537821929324 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 34}. Best is trial 10 with value: 0.7881537821929324.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.89 | R2: 0.70
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.60 | R2: 0.79
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.60 | R2: 0.79
Fold 1

[I 2025-07-11 16:13:45,580] Trial 14 finished with value: 0.7881537821929324 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 33}. Best is trial 10 with value: 0.7881537821929324.
[I 2025-07-11 16:13:45,655] Trial 15 finished with value: 0.6754295818903499 and parameters: {'n_neighbors': 8, 'weights': 'distance', 'leaf_size': 36}. Best is trial 10 with value: 0.7881537821929324.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.60 | R2: 0.79
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.97 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.60 | R2: 0.79

[I 2025-07-11 16:13:45,726] Trial 16 finished with value: 0.7881537821929324 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 30}. Best is trial 10 with value: 0.7881537821929324.
[I 2025-07-11 16:13:45,801] Trial 17 finished with value: 0.7018505804897301 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'leaf_size': 38}. Best is trial 10 with value: 0.7881537821929324.
[I 2025-07-11 16:13:45,873] Trial 18 finished with value: 0.7255516451294483 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'leaf_size': 29}. Best is trial 10 with value: 0.7881537821929324.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.89 | R2: 0.70
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.82 | R2: 0.73
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:13:45,946] Trial 19 finished with value: 0.6356131532843676 and parameters: {'n_neighbors': 15, 'weights': 'distance', 'leaf_size': 34}. Best is trial 10 with value: 0.7881537821929324.
[I 2025-07-11 16:13:46,020] Trial 20 finished with value: 0.7472013408768465 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'leaf_size': 36}. Best is trial 10 with value: 0.7881537821929324.
[I 2025-07-11 16:13:46,093] Trial 21 finished with value: 0.7881537821929324 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 32}. Best is trial 10 with value: 0.7881537821929324.

Running time: 0.1 sec
OOF RMSE: 2.09 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.74 | R2: 0.75
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.60 | R2: 0.79
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 16:13:46,166] Trial 22 finished with value: 0.7472013408768465 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'leaf_size': 37}. Best is trial 10 with value: 0.7881537821929324.
[I 2025-07-11 16:13:46,242] Trial 23 finished with value: 0.7881537821929324 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 40}. Best is trial 10 with value: 0.7881537821929324.
[I 2025-07-11 16:13:46,314] Trial 24 finished with value: 0.7472013408768465 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'leaf_size': 35}. Best is trial 10 with value: 0.7881537821929324.
[I 2025-07-11 16:13:46,315] A new study created in memory with name: no-name-cab6d48a-a8b1-4b07-8348-f121d40de4c7

Fold 5
Running time: 0.1 sec
OOF RMSE: 1.74 | R2: 0.75
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.60 | R2: 0.79
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.74 | R2: 0.75

✅ KNN - Mejor R2: 0.79
📋 Parámetros: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 40}

Buscando mejores hiperparámetros para LR...
Fold 1
Fold 2
Fold 3

[I 2025-07-11 16:13:46,394] Trial 0 finished with value: 0.060173072867762856 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 0 with value: 0.060173072867762856.
[I 2025-07-11 16:13:46,481] Trial 1 finished with value: 0.060173072876988365 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 1 with value: 0.060173072876988365.
[I 2025-07-11 16:13:46,562] Trial 2 finished with value: 0.34303738144161766 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 2 with value: 0.34303738144161766.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.36 | R2: 0.06
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.36 | R2: 0.06
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.81 | R2: 0.34

[I 2025-07-11 16:13:46,625] Trial 3 finished with value: 0.34303738144161766 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 2 with value: 0.34303738144161766.
[I 2025-07-11 16:13:46,690] Trial 4 finished with value: 0.34303738144161766 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 2 with value: 0.34303738144161766.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.81 | R2: 0.34
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.81 | R2: 0.34
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:13:46,771] Trial 5 finished with value: 0.060173072876988365 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 2 with value: 0.34303738144161766.
[I 2025-07-11 16:13:46,849] Trial 6 finished with value: 0.34765539553365565 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 6 with value: 0.34765539553365565.
[I 2025-07-11 16:13:46,936] Trial 7 finished with value: 0.060173072876988365 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 6 with value: 0.34765539553365565.

Running time: 0.1 sec
OOF RMSE: 3.36 | R2: 0.06
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.80 | R2: 0.35
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.36 | R2: 0.06
Fold 1
Fold 2

[I 2025-07-11 16:13:47,058] Trial 8 finished with value: 0.060173072867762856 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 6 with value: 0.34765539553365565.
[I 2025-07-11 16:13:47,163] Trial 9 finished with value: 0.060173072867762856 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 6 with value: 0.34765539553365565.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.36 | R2: 0.06
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.36 | R2: 0.06
Fold 1
Fold 2

[I 2025-07-11 16:13:47,251] Trial 10 finished with value: 0.34765539553365565 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 6 with value: 0.34765539553365565.
[I 2025-07-11 16:13:47,315] Trial 11 finished with value: 0.34765539553365565 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 6 with value: 0.34765539553365565.
[I 2025-07-11 16:13:47,377] Trial 12 finished with value: 0.34765539553365565 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 6 with value: 0.34765539553365565.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.80 | R2: 0.35
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.80 | R2: 0.35
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.80 | R2: 0.35
Fold 1
Fold 2
Fold 3

[I 2025-07-11 16:13:47,442] Trial 13 finished with value: 0.34765539553365565 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 6 with value: 0.34765539553365565.
[I 2025-07-11 16:13:47,507] Trial 14 finished with value: 0.34765539553365565 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 6 with value: 0.34765539553365565.
[I 2025-07-11 16:13:47,569] Trial 15 finished with value: 0.34765539553365565 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 6 with value: 0.34765539553365565.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.80 | R2: 0.35
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.80 | R2: 0.35
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.80 | R2: 0.35
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:13:47,633] Trial 16 finished with value: 0.34765539553365565 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 6 with value: 0.34765539553365565.
[I 2025-07-11 16:13:47,700] Trial 17 finished with value: 0.34765539553365565 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 6 with value: 0.34765539553365565.
[I 2025-07-11 16:13:47,769] Trial 18 finished with value: 0.34765539553365565 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 6 with value: 0.34765539553365565.
[I 2025-07-11 16:13:47,830] Trial 19 finished with value: 0.34765539553365565 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 6 with value: 0.34765539553365565.

Running time: 0.1 sec
OOF RMSE: 2.80 | R2: 0.35
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.80 | R2: 0.35
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.80 | R2: 0.35
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.80 | R2: 0.35

[I 2025-07-11 16:13:47,894] Trial 20 finished with value: 0.34765539553365565 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 6 with value: 0.34765539553365565.
[I 2025-07-11 16:13:47,978] Trial 21 finished with value: 0.34765539553365565 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 6 with value: 0.34765539553365565.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.80 | R2: 0.35
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.80 | R2: 0.35
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:13:48,044] Trial 22 finished with value: 0.34765539553365565 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 6 with value: 0.34765539553365565.
[I 2025-07-11 16:13:48,109] Trial 23 finished with value: 0.34765539553365565 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 6 with value: 0.34765539553365565.
[I 2025-07-11 16:13:48,169] Trial 24 finished with value: 0.34765539553365565 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 6 with value: 0.34765539553365565.
[I 2025-07-11 16:13:48,170] A new study created in memory with name: no-name-b5520481-a4ce-492d-8aa2-4b6a0f13cfde

Running time: 0.1 sec
OOF RMSE: 2.80 | R2: 0.35
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.80 | R2: 0.35
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.80 | R2: 0.35

✅ LR - Mejor R2: 0.35
📋 Parámetros: {'fit_intercept': True, 'positive': True}

Buscando mejores hiperparámetros para RF...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:13:53,804] Trial 0 finished with value: 0.6233316906281453 and parameters: {'n_estimators': 300, 'max_depth': 11, 'min_samples_split': 7, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 0 with value: 0.6233316906281453.

Running time: 5.6 sec
OOF RMSE: 2.13 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:14:04,920] Trial 1 finished with value: 0.5712093185062375 and parameters: {'n_estimators': 500, 'max_depth': 9, 'min_samples_split': 9, 'min_samples_leaf': 5, 'bootstrap': False}. Best is trial 0 with value: 0.6233316906281453.

Running time: 11.1 sec
OOF RMSE: 2.27 | R2: 0.57
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:14:15,717] Trial 2 finished with value: 0.5713147364791451 and parameters: {'n_estimators': 500, 'max_depth': 8, 'min_samples_split': 9, 'min_samples_leaf': 5, 'bootstrap': False}. Best is trial 0 with value: 0.6233316906281453.

Running time: 10.8 sec
OOF RMSE: 2.27 | R2: 0.57
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:14:17,552] Trial 3 finished with value: 0.5171557233112023 and parameters: {'n_estimators': 100, 'max_depth': 5, 'min_samples_split': 6, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 0 with value: 0.6233316906281453.

Running time: 1.8 sec
OOF RMSE: 2.41 | R2: 0.52
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:14:25,867] Trial 4 finished with value: 0.6043425676408753 and parameters: {'n_estimators': 500, 'max_depth': 10, 'min_samples_split': 10, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 0 with value: 0.6233316906281453.

Running time: 8.3 sec
OOF RMSE: 2.18 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:14:40,796] Trial 5 finished with value: 0.48552259006186216 and parameters: {'n_estimators': 500, 'max_depth': 11, 'min_samples_split': 3, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 0 with value: 0.6233316906281453.

Running time: 14.9 sec
OOF RMSE: 2.49 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:14:44,891] Trial 6 finished with value: 0.6078710071895022 and parameters: {'n_estimators': 300, 'max_depth': 6, 'min_samples_split': 9, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 0 with value: 0.6233316906281453.

Running time: 4.1 sec
OOF RMSE: 2.17 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:14:47,291] Trial 7 finished with value: 0.6414665012510317 and parameters: {'n_estimators': 100, 'max_depth': 9, 'min_samples_split': 7, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 7 with value: 0.6414665012510317.

Running time: 2.4 sec
OOF RMSE: 2.08 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:14:54,075] Trial 8 finished with value: 0.654967523458972 and parameters: {'n_estimators': 300, 'max_depth': 8, 'min_samples_split': 10, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 8 with value: 0.654967523458972.

Running time: 6.8 sec
OOF RMSE: 2.04 | R2: 0.65
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:14:57,762] Trial 9 finished with value: 0.6057905970799295 and parameters: {'n_estimators': 300, 'max_depth': 5, 'min_samples_split': 5, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 8 with value: 0.654967523458972.

Running time: 3.7 sec
OOF RMSE: 2.18 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:15:04,943] Trial 10 finished with value: 0.5930967602453174 and parameters: {'n_estimators': 300, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 4, 'bootstrap': False}. Best is trial 8 with value: 0.654967523458972.

Running time: 7.2 sec
OOF RMSE: 2.21 | R2: 0.59
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:15:07,258] Trial 11 finished with value: 0.6385377240700718 and parameters: {'n_estimators': 100, 'max_depth': 8, 'min_samples_split': 7, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 8 with value: 0.654967523458972.

Running time: 2.3 sec
OOF RMSE: 2.08 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:15:10,070] Trial 12 finished with value: 0.5614291717978551 and parameters: {'n_estimators': 100, 'max_depth': 13, 'min_samples_split': 4, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 8 with value: 0.654967523458972.

Running time: 2.8 sec
OOF RMSE: 2.30 | R2: 0.56
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:15:12,188] Trial 13 finished with value: 0.5962399196296955 and parameters: {'n_estimators': 100, 'max_depth': 7, 'min_samples_split': 7, 'min_samples_leaf': 4, 'bootstrap': False}. Best is trial 8 with value: 0.654967523458972.

Running time: 2.1 sec
OOF RMSE: 2.20 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:15:19,519] Trial 14 finished with value: 0.5902359553280436 and parameters: {'n_estimators': 300, 'max_depth': 9, 'min_samples_split': 10, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 8 with value: 0.654967523458972.

Running time: 7.3 sec
OOF RMSE: 2.22 | R2: 0.59
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:15:22,012] Trial 15 finished with value: 0.6537453385630649 and parameters: {'n_estimators': 100, 'max_depth': 12, 'min_samples_split': 8, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 8 with value: 0.654967523458972.

Running time: 2.5 sec
OOF RMSE: 2.04 | R2: 0.65
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:15:24,411] Trial 16 finished with value: 0.5903987552289007 and parameters: {'n_estimators': 100, 'max_depth': 13, 'min_samples_split': 8, 'min_samples_leaf': 4, 'bootstrap': False}. Best is trial 8 with value: 0.654967523458972.

Running time: 2.4 sec
OOF RMSE: 2.22 | R2: 0.59
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:15:32,136] Trial 17 finished with value: 0.5923492800160877 and parameters: {'n_estimators': 300, 'max_depth': 13, 'min_samples_split': 10, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 8 with value: 0.654967523458972.

Running time: 7.7 sec
OOF RMSE: 2.21 | R2: 0.59
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:15:37,019] Trial 18 finished with value: 0.6129118283171129 and parameters: {'n_estimators': 300, 'max_depth': 15, 'min_samples_split': 8, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 8 with value: 0.654967523458972.

Running time: 4.9 sec
OOF RMSE: 2.16 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:15:39,485] Trial 19 finished with value: 0.6537453385630649 and parameters: {'n_estimators': 100, 'max_depth': 12, 'min_samples_split': 8, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 8 with value: 0.654967523458972.

Running time: 2.5 sec
OOF RMSE: 2.04 | R2: 0.65
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:15:41,866] Trial 20 finished with value: 0.5904413071772732 and parameters: {'n_estimators': 100, 'max_depth': 11, 'min_samples_split': 5, 'min_samples_leaf': 4, 'bootstrap': False}. Best is trial 8 with value: 0.654967523458972.

Running time: 2.4 sec
OOF RMSE: 2.22 | R2: 0.59
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:15:44,350] Trial 21 finished with value: 0.6537453385630649 and parameters: {'n_estimators': 100, 'max_depth': 12, 'min_samples_split': 8, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 8 with value: 0.654967523458972.

Running time: 2.5 sec
OOF RMSE: 2.04 | R2: 0.65
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:15:46,807] Trial 22 finished with value: 0.6553477841661829 and parameters: {'n_estimators': 100, 'max_depth': 14, 'min_samples_split': 9, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 22 with value: 0.6553477841661829.

Running time: 2.5 sec
OOF RMSE: 2.04 | R2: 0.66
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:15:49,418] Trial 23 finished with value: 0.5754231751919411 and parameters: {'n_estimators': 100, 'max_depth': 14, 'min_samples_split': 9, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 22 with value: 0.6553477841661829.

Running time: 2.6 sec
OOF RMSE: 2.26 | R2: 0.58
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:15:51,876] Trial 24 finished with value: 0.6558410067121344 and parameters: {'n_estimators': 100, 'max_depth': 14, 'min_samples_split': 10, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 24 with value: 0.6558410067121344.
[I 2025-07-11 16:15:51,877] A new study created in memory with name: no-name-6b04b6c7-8c07-4061-8fec-6e1bf1a98fe9

Running time: 2.5 sec
OOF RMSE: 2.03 | R2: 0.66

✅ RF - Mejor R2: 0.66
📋 Parámetros: {'n_estimators': 100, 'max_depth': 14, 'min_samples_split': 10, 'min_samples_leaf': 3, 'bootstrap': False}

Buscando mejores hiperparámetros para CAT...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:15:56,898] Trial 0 finished with value: 0.6844133043366227 and parameters: {'iterations': 1000, 'learning_rate': 0.05531806621346526, 'depth': 5, 'l2_leaf_reg': 3.7652675643149927}. Best is trial 0 with value: 0.6844133043366227.

Running time: 5.0 sec
OOF RMSE: 1.95 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:16:39,390] Trial 1 finished with value: 0.6981396725424782 and parameters: {'iterations': 1000, 'learning_rate': 0.04958202152737033, 'depth': 8, 'l2_leaf_reg': 2.3439091922308166}. Best is trial 1 with value: 0.6981396725424782.

Running time: 42.5 sec
OOF RMSE: 1.90 | R2: 0.70
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:17:25,937] Trial 2 finished with value: 0.7074540860130001 and parameters: {'iterations': 500, 'learning_rate': 0.04397752455655506, 'depth': 9, 'l2_leaf_reg': 5.471952057773002}. Best is trial 2 with value: 0.7074540860130001.

Running time: 46.5 sec
OOF RMSE: 1.87 | R2: 0.71
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:17:29,171] Trial 3 finished with value: 0.683803639021515 and parameters: {'iterations': 1000, 'learning_rate': 0.021125792860986727, 'depth': 4, 'l2_leaf_reg': 9.589063257533377}. Best is trial 2 with value: 0.7074540860130001.

Running time: 3.2 sec
OOF RMSE: 1.95 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:18:03,966] Trial 4 finished with value: 0.7117095594085446 and parameters: {'iterations': 2000, 'learning_rate': 0.05210869822845941, 'depth': 7, 'l2_leaf_reg': 4.122617409966653}. Best is trial 4 with value: 0.7117095594085446.

Running time: 34.8 sec
OOF RMSE: 1.86 | R2: 0.71
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:19:36,058] Trial 5 finished with value: 0.7080130212798632 and parameters: {'iterations': 1000, 'learning_rate': 0.011491720767561069, 'depth': 9, 'l2_leaf_reg': 1.9693701408179058}. Best is trial 4 with value: 0.7117095594085446.

Running time: 92.1 sec
OOF RMSE: 1.87 | R2: 0.71
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:19:44,163] Trial 6 finished with value: 0.7075092470416227 and parameters: {'iterations': 1000, 'learning_rate': 0.015325944823572727, 'depth': 6, 'l2_leaf_reg': 2.0186529737559313}. Best is trial 4 with value: 0.7117095594085446.

Running time: 8.1 sec
OOF RMSE: 1.87 | R2: 0.71
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:19:48,262] Trial 7 finished with value: 0.6884187183559245 and parameters: {'iterations': 500, 'learning_rate': 0.011216451913748484, 'depth': 6, 'l2_leaf_reg': 1.110229268762572}. Best is trial 4 with value: 0.7117095594085446.

Running time: 4.1 sec
OOF RMSE: 1.94 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:19:51,515] Trial 8 finished with value: 0.6767795400579104 and parameters: {'iterations': 1000, 'learning_rate': 0.023556745794463325, 'depth': 4, 'l2_leaf_reg': 6.245504773055591}. Best is trial 4 with value: 0.7117095594085446.

Running time: 3.2 sec
OOF RMSE: 1.97 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:21:24,572] Trial 9 finished with value: 0.6913428092866427 and parameters: {'iterations': 1000, 'learning_rate': 0.04040132049206501, 'depth': 9, 'l2_leaf_reg': 6.67098243754694}. Best is trial 4 with value: 0.7117095594085446.

Running time: 93.1 sec
OOF RMSE: 1.93 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:22:04,701] Trial 10 finished with value: 0.6915927220326574 and parameters: {'iterations': 2000, 'learning_rate': 0.09355343942364318, 'depth': 7, 'l2_leaf_reg': 8.117997652000646}. Best is trial 4 with value: 0.7117095594085446.

Running time: 40.1 sec
OOF RMSE: 1.93 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:27:32,785] Trial 11 finished with value: 0.6871470228152416 and parameters: {'iterations': 2000, 'learning_rate': 0.07952350018161301, 'depth': 10, 'l2_leaf_reg': 3.957215605289747}. Best is trial 4 with value: 0.7117095594085446.
[I 2025-07-11 16:27:32,786] A new study created in memory with name: no-name-180bb588-a2b5-4f0a-a28f-bcbd71bbf31b
[I 2025-07-11 16:27:32,868] Trial 0 finished with value: 0.4444998609078801 and parameters: {'alpha': 0.8296452958664656, 'l1_ratio': 0.3263505599423905}. Best is trial 0 with value: 0.4444998609078801.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.439e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.294e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.909e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.101e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.222e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 16:27:32,984] Trial 1 finished with value: 0.42490786503896305 and parameters: {'alpha': 0.003999182694766448, 'l1_ratio': 0.19814958297522944}. Best is trial 0 with value: 0.4444998609078801.

Running time: 328.1 sec
OOF RMSE: 1.94 | R2: 0.69

✅ CAT - Mejor R2: 0.71
📋 Parámetros: {'iterations': 2000, 'learning_rate': 0.05210869822845941, 'depth': 7, 'l2_leaf_reg': 4.122617409966653}

Buscando mejores hiperparámetros para EN...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.58 | R2: 0.44
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.63 | R2: 0.42

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.903e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.413e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.360e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.417e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.247e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 16:27:33,120] Trial 2 finished with value: 0.4378285265027225 and parameters: {'alpha': 0.005773902374748177, 'l1_ratio': 0.357951634155121}. Best is trial 0 with value: 0.4444998609078801.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.60 | R2: 0.44
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.361e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.324e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.499e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.876e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.117e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 16:27:33,251] Trial 3 finished with value: 0.4178385267045006 and parameters: {'alpha': 0.003459999935343727, 'l1_ratio': 0.2432960049365792}. Best is trial 0 with value: 0.4444998609078801.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.249e+01, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.157e-01, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.462e-01, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.055e+00, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.085e+01, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 16:27:33,372] Trial 4 finished with value: 0.5090399278921918 and parameters: {'alpha': 0.025356709557489084, 'l1_ratio': 0.3930134974846008}. Best is trial 4 with value: 0.5090399278921918.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.64 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.43 | R2: 0.51
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.004e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.697e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.833e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.076e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.036e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 16:27:33,507] Trial 5 finished with value: 0.43749882726081135 and parameters: {'alpha': 0.005393892314308583, 'l1_ratio': 0.016909042599563162}. Best is trial 4 with value: 0.5090399278921918.
[I 2025-07-11 16:27:33,639] Trial 6 finished with value: 0.5278466271262563 and parameters: {'alpha': 0.056512720425779144, 'l1_ratio': 0.28835072281421514}. Best is trial 6 with value: 0.5278466271262563.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.60 | R2: 0.44
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.38 | R2: 0.53

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.850e+01, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.249e-01, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.902e+00, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.253e+01, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.121e+01, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 16:27:33,828] Trial 7 finished with value: 0.4790288232102169 and parameters: {'alpha': 0.012841034512254846, 'l1_ratio': 0.5984863794753169}. Best is trial 6 with value: 0.5278466271262563.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 2.50 | R2: 0.48
Fold 1

[I 2025-07-11 16:27:34,007] Trial 8 finished with value: 0.529686585715338 and parameters: {'alpha': 0.089499035932936, 'l1_ratio': 0.3334007533969384}. Best is trial 8 with value: 0.529686585715338.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 2.38 | R2: 0.53
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.136e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.319e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.704e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.964e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.767e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 16:27:34,163] Trial 9 finished with value: 0.4345894646516799 and parameters: {'alpha': 0.005055672001475474, 'l1_ratio': 0.13545850483992583}. Best is trial 8 with value: 0.529686585715338.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.356e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.423e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.61 | R2: 0.43
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.405e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.647e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.465e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 16:27:34,313] Trial 10 finished with value: 0.33199909501400093 and parameters: {'alpha': 0.00011673636552771353, 'l1_ratio': 0.9011239114491469}. Best is trial 8 with value: 0.529686585715338.
[I 2025-07-11 16:27:34,414] Trial 11 finished with value: 0.4679585998275495 and parameters: {'alpha': 0.43724414169609627, 'l1_ratio': 0.5811024750812792}. Best is trial 8 with value: 0.529686585715338.

Running time: 0.1 sec
OOF RMSE: 2.83 | R2: 0.33
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.53 | R2: 0.47
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:27:34,518] Trial 12 finished with value: 0.5215348573849116 and parameters: {'alpha': 0.11817989189970605, 'l1_ratio': 0.7612443012063688}. Best is trial 8 with value: 0.529686585715338.
[I 2025-07-11 16:27:34,632] Trial 13 finished with value: 0.006977824779891284 and parameters: {'alpha': 5.979835386704528, 'l1_ratio': 0.4551409062633652}. Best is trial 8 with value: 0.529686585715338.

Running time: 0.1 sec
OOF RMSE: 2.40 | R2: 0.52
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.45 | R2: 0.01
Fold 1
Fold 2
Fold 3

[I 2025-07-11 16:27:34,787] Trial 14 finished with value: 0.5188980453741324 and parameters: {'alpha': 0.1394308061162772, 'l1_ratio': 0.1054472770073584}. Best is trial 8 with value: 0.529686585715338.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.460e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.750e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.639e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.585e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.685e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 16:27:34,925] Trial 15 finished with value: 0.35168250638834264 and parameters: {'alpha': 0.0005517016631549356, 'l1_ratio': 0.5370963287602277}. Best is trial 8 with value: 0.529686585715338.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.40 | R2: 0.52
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.79 | R2: 0.35
Fold 1
Fold 2

[I 2025-07-11 16:27:35,034] Trial 16 finished with value: 0.5312698908238697 and parameters: {'alpha': 0.08964080137119776, 'l1_ratio': 0.7078437314999355}. Best is trial 16 with value: 0.5312698908238697.
[I 2025-07-11 16:27:35,173] Trial 17 finished with value: 0.30207729939369576 and parameters: {'alpha': 1.7408325197165684, 'l1_ratio': 0.7243299084505821}. Best is trial 16 with value: 0.5312698908238697.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.37 | R2: 0.53
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.90 | R2: 0.30

[I 2025-07-11 16:27:35,314] Trial 18 finished with value: 0.49120179552469945 and parameters: {'alpha': 0.28838835186652473, 'l1_ratio': 0.9979205023247893}. Best is trial 16 with value: 0.5312698908238697.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.47 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:27:35,424] Trial 19 finished with value: -0.00027817151752640434 and parameters: {'alpha': 8.790246635634578, 'l1_ratio': 0.6845898868122401}. Best is trial 16 with value: 0.5312698908238697.
[I 2025-07-11 16:27:35,540] Trial 20 finished with value: 0.5284621376412003 and parameters: {'alpha': 0.034296799050841036, 'l1_ratio': 0.8348704717537061}. Best is trial 16 with value: 0.5312698908238697.

Running time: 0.1 sec
OOF RMSE: 3.47 | R2: -0.00
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.38 | R2: 0.53
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:27:35,641] Trial 21 finished with value: 0.5321671127533365 and parameters: {'alpha': 0.03976939481572569, 'l1_ratio': 0.8424265339854451}. Best is trial 21 with value: 0.5321671127533365.
[I 2025-07-11 16:27:35,758] Trial 22 finished with value: 0.5287160685777982 and parameters: {'alpha': 0.09225067848207301, 'l1_ratio': 0.8802021242481465}. Best is trial 21 with value: 0.5321671127533365.

Running time: 0.1 sec
OOF RMSE: 2.37 | R2: 0.53
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.38 | R2: 0.53
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 16:27:35,893] Trial 23 finished with value: 0.5109385503363509 and parameters: {'alpha': 0.023099381054364036, 'l1_ratio': 0.6494328408588296}. Best is trial 21 with value: 0.5321671127533365.
[I 2025-07-11 16:27:36,040] Trial 24 finished with value: 0.4931042817631006 and parameters: {'alpha': 0.2624831102565647, 'l1_ratio': 0.7952791398982674}. Best is trial 21 with value: 0.5321671127533365.
[I 2025-07-11 16:27:36,042] A new study created in memory with name: no-name-abe1f1d5-3e9d-4b08-8498-5f81186f85db

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.42 | R2: 0.51
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.47 | R2: 0.49

✅ EN - Mejor R2: 0.53
📋 Parámetros: {'alpha': 0.03976939481572569, 'l1_ratio': 0.8424265339854451}

🔍 Optimizando en C2X-Complex_rhown_3x3_depth_lt_1...
Buscando mejores hiperparámetros para XGB...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:27:39,876] Trial 0 finished with value: 0.6039755119615513 and parameters: {'n_estimators': 500, 'learning_rate': 0.008411618492088012, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.6808445332931096, 'colsample_bytree': 0.8083845856733793}. Best is trial 0 with value: 0.6039755119615513.

Running time: 3.8 sec
OOF RMSE: 2.18 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:27:50,556] Trial 1 finished with value: 0.5918681092804603 and parameters: {'n_estimators': 2000, 'learning_rate': 0.07109990656168903, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.6144991205060487, 'colsample_bytree': 0.8588946578834635}. Best is trial 0 with value: 0.6039755119615513.

Running time: 10.7 sec
OOF RMSE: 2.21 | R2: 0.59
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:27:59,160] Trial 2 finished with value: 0.6269539954442394 and parameters: {'n_estimators': 1000, 'learning_rate': 0.012378502428467301, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.9497125430053464, 'colsample_bytree': 0.6405421041414481}. Best is trial 2 with value: 0.6269539954442394.

Running time: 8.6 sec
OOF RMSE: 2.12 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:28:04,114] Trial 3 finished with value: 0.6106536226625331 and parameters: {'n_estimators': 500, 'learning_rate': 0.014596710854497087, 'max_depth': 8, 'min_child_weight': 3, 'subsample': 0.7404381497146754, 'colsample_bytree': 0.8966006663909057}. Best is trial 2 with value: 0.6269539954442394.

Running time: 4.9 sec
OOF RMSE: 2.16 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:28:10,443] Trial 4 finished with value: 0.6241833403738025 and parameters: {'n_estimators': 1000, 'learning_rate': 0.09456745839006572, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.7703909216204122, 'colsample_bytree': 0.9201325031726737}. Best is trial 2 with value: 0.6269539954442394.

Running time: 6.3 sec
OOF RMSE: 2.13 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:28:14,003] Trial 5 finished with value: 0.6086757361146753 and parameters: {'n_estimators': 500, 'learning_rate': 0.00970523461720822, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.6727629193505665, 'colsample_bytree': 0.7048521974759887}. Best is trial 2 with value: 0.6269539954442394.

Running time: 3.6 sec
OOF RMSE: 2.17 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:28:23,545] Trial 6 finished with value: 0.6356857121697519 and parameters: {'n_estimators': 2000, 'learning_rate': 0.07578695164557896, 'max_depth': 5, 'min_child_weight': 1, 'subsample': 0.6814009184102182, 'colsample_bytree': 0.9591552787137627}. Best is trial 6 with value: 0.6356857121697519.

Running time: 9.5 sec
OOF RMSE: 2.09 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:28:32,330] Trial 7 finished with value: 0.6359620348245725 and parameters: {'n_estimators': 1000, 'learning_rate': 0.03892072964197776, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.9099324305020938, 'colsample_bytree': 0.8147029332092626}. Best is trial 7 with value: 0.6359620348245725.

Running time: 8.8 sec
OOF RMSE: 2.09 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:28:40,498] Trial 8 finished with value: 0.6341967158193607 and parameters: {'n_estimators': 1000, 'learning_rate': 0.039396802092815944, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.9547178422125987, 'colsample_bytree': 0.9858684007935585}. Best is trial 7 with value: 0.6359620348245725.

Running time: 8.2 sec
OOF RMSE: 2.10 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:28:52,337] Trial 9 finished with value: 0.6238432232798943 and parameters: {'n_estimators': 2000, 'learning_rate': 0.05204331846159931, 'max_depth': 8, 'min_child_weight': 1, 'subsample': 0.7985970312924724, 'colsample_bytree': 0.9772409257278653}. Best is trial 7 with value: 0.6359620348245725.

Running time: 11.8 sec
OOF RMSE: 2.13 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:29:00,818] Trial 10 finished with value: 0.6025048148485026 and parameters: {'n_estimators': 1000, 'learning_rate': 0.026985564916073287, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.8725119647282221, 'colsample_bytree': 0.7425784412272783}. Best is trial 7 with value: 0.6359620348245725.

Running time: 8.5 sec
OOF RMSE: 2.19 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:29:12,957] Trial 11 finished with value: 0.6317940571294927 and parameters: {'n_estimators': 2000, 'learning_rate': 0.035821233746674536, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.8761822670594619, 'colsample_bytree': 0.8093680800189565}. Best is trial 7 with value: 0.6359620348245725.

Running time: 12.1 sec
OOF RMSE: 2.10 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:29:21,742] Trial 12 finished with value: 0.6568430977739732 and parameters: {'n_estimators': 2000, 'learning_rate': 0.05883287671138505, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.8838687864977884, 'colsample_bytree': 0.6032440232711282}. Best is trial 12 with value: 0.6568430977739732.

Running time: 8.8 sec
OOF RMSE: 2.03 | R2: 0.66
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:29:31,106] Trial 13 finished with value: 0.6242232487061083 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01872924381902607, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.8760985409449948, 'colsample_bytree': 0.6068650796518904}. Best is trial 12 with value: 0.6568430977739732.

Running time: 9.4 sec
OOF RMSE: 2.13 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:29:47,340] Trial 14 finished with value: 0.6071440554713586 and parameters: {'n_estimators': 2000, 'learning_rate': 0.0056936623388839785, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.9957059601181606, 'colsample_bytree': 0.7348126774145738}. Best is trial 12 with value: 0.6568430977739732.

Running time: 16.2 sec
OOF RMSE: 2.17 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:29:58,217] Trial 15 finished with value: 0.6073153128200408 and parameters: {'n_estimators': 2000, 'learning_rate': 0.04635729262974685, 'max_depth': 8, 'min_child_weight': 4, 'subsample': 0.8391723666631318, 'colsample_bytree': 0.6778782065331209}. Best is trial 12 with value: 0.6568430977739732.

Running time: 10.9 sec
OOF RMSE: 2.17 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:30:05,617] Trial 16 finished with value: 0.6317990850956121 and parameters: {'n_estimators': 1000, 'learning_rate': 0.025087212562702264, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.9233834744743306, 'colsample_bytree': 0.7810810729266463}. Best is trial 12 with value: 0.6568430977739732.

Running time: 7.4 sec
OOF RMSE: 2.10 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:30:12,507] Trial 17 finished with value: 0.6145212571039258 and parameters: {'n_estimators': 1000, 'learning_rate': 0.06376325174017745, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.8310470625786014, 'colsample_bytree': 0.8592413032584112}. Best is trial 12 with value: 0.6568430977739732.

Running time: 6.9 sec
OOF RMSE: 2.15 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:30:25,195] Trial 18 finished with value: 0.6398020742356234 and parameters: {'n_estimators': 2000, 'learning_rate': 0.03125331566455384, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.9145013537121391, 'colsample_bytree': 0.7541586276940422}. Best is trial 12 with value: 0.6568430977739732.

Running time: 12.7 sec
OOF RMSE: 2.08 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:30:36,977] Trial 19 finished with value: 0.6072062672021977 and parameters: {'n_estimators': 2000, 'learning_rate': 0.030783920267803223, 'max_depth': 8, 'min_child_weight': 2, 'subsample': 0.9895311883660587, 'colsample_bytree': 0.6541017624633554}. Best is trial 12 with value: 0.6568430977739732.

Running time: 11.8 sec
OOF RMSE: 2.17 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:30:49,393] Trial 20 finished with value: 0.6192856956429262 and parameters: {'n_estimators': 2000, 'learning_rate': 0.018339505082009662, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.9233626853650205, 'colsample_bytree': 0.7468131932342099}. Best is trial 12 with value: 0.6568430977739732.

Running time: 12.4 sec
OOF RMSE: 2.14 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:30:59,760] Trial 21 finished with value: 0.6482858505784747 and parameters: {'n_estimators': 2000, 'learning_rate': 0.05175226926837329, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.9050143120556025, 'colsample_bytree': 0.8486832785649077}. Best is trial 12 with value: 0.6568430977739732.

Running time: 10.4 sec
OOF RMSE: 2.06 | R2: 0.65
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:31:10,688] Trial 22 finished with value: 0.6039536066501638 and parameters: {'n_estimators': 2000, 'learning_rate': 0.05453823282180435, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.842150465159579, 'colsample_bytree': 0.8572188864124793}. Best is trial 12 with value: 0.6568430977739732.

Running time: 10.9 sec
OOF RMSE: 2.18 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:31:19,438] Trial 23 finished with value: 0.6380818865463277 and parameters: {'n_estimators': 2000, 'learning_rate': 0.08639946276600126, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.9084570628152437, 'colsample_bytree': 0.9044727593960857}. Best is trial 12 with value: 0.6568430977739732.

Running time: 8.7 sec
OOF RMSE: 2.09 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:31:29,120] Trial 24 finished with value: 0.6453447829394965 and parameters: {'n_estimators': 2000, 'learning_rate': 0.04658644528426943, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.9578060398644608, 'colsample_bytree': 0.6126443202730597}. Best is trial 12 with value: 0.6568430977739732.
[I 2025-07-11 16:31:29,122] A new study created in memory with name: no-name-d1eb1dc4-2841-479b-8bd0-49953a75cd0e

Running time: 9.7 sec
OOF RMSE: 2.06 | R2: 0.65

✅ XGB - Mejor R2: 0.66
📋 Parámetros: {'n_estimators': 2000, 'learning_rate': 0.05883287671138505, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.8838687864977884, 'colsample_bytree': 0.6032440232711282}

Buscando mejores hiperparámetros para LBM...
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 16:31:29,424] Trial 0 finished with value: 0.5439749099864002 and parameters: {'learning_rate': 0.011162538800985004, 'num_leaves': 40, 'max_depth': 8, 'min_child_samples': 20, 'subsample': 0.702020437067187, 'colsample_bytree': 0.7942402647499232, 'n_estimators': 500}. Best is trial 0 with value: 0.5439749099864002.

Fold 5
Running time: 0.3 sec
OOF RMSE: 2.34 | R2: 0.54
Fold 1
Fold 2
Fold 3

[I 2025-07-11 16:31:29,724] Trial 1 finished with value: 0.6017366999582985 and parameters: {'learning_rate': 0.07290696431125891, 'num_leaves': 60, 'max_depth': 7, 'min_child_samples': 24, 'subsample': 0.6697217468470814, 'colsample_bytree': 0.8221167208265269, 'n_estimators': 500}. Best is trial 1 with value: 0.6017366999582985.

Fold 4
Fold 5
Running time: 0.3 sec
OOF RMSE: 2.19 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:31:30,429] Trial 2 finished with value: 0.6244027520606386 and parameters: {'learning_rate': 0.07196015722605156, 'num_leaves': 60, 'max_depth': 7, 'min_child_samples': 7, 'subsample': 0.7054001203419882, 'colsample_bytree': 0.6452192277194082, 'n_estimators': 1000}. Best is trial 2 with value: 0.6244027520606386.

Running time: 0.7 sec
OOF RMSE: 2.12 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 16:31:31,458] Trial 3 finished with value: 0.5570374529006772 and parameters: {'learning_rate': 0.006124847560769465, 'num_leaves': 80, 'max_depth': 7, 'min_child_samples': 22, 'subsample': 0.799940164101887, 'colsample_bytree': 0.8073377816606819, 'n_estimators': 2000}. Best is trial 2 with value: 0.6244027520606386.

Fold 5
Running time: 1.0 sec
OOF RMSE: 2.31 | R2: 0.56
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 16:31:31,799] Trial 4 finished with value: 0.5924990128380083 and parameters: {'learning_rate': 0.020338544963102067, 'num_leaves': 80, 'max_depth': 8, 'min_child_samples': 12, 'subsample': 0.939277419450968, 'colsample_bytree': 0.7847440531684621, 'n_estimators': 500}. Best is trial 2 with value: 0.6244027520606386.

Fold 5
Running time: 0.3 sec
OOF RMSE: 2.21 | R2: 0.59
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:31:33,159] Trial 5 finished with value: 0.6325561782796116 and parameters: {'learning_rate': 0.02554609009094569, 'num_leaves': 60, 'max_depth': 8, 'min_child_samples': 7, 'subsample': 0.704501308396438, 'colsample_bytree': 0.6101368732100921, 'n_estimators': 2000}. Best is trial 5 with value: 0.6325561782796116.

Running time: 1.4 sec
OOF RMSE: 2.10 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:31:34,353] Trial 6 finished with value: 0.6050191418647319 and parameters: {'learning_rate': 0.007693015134670705, 'num_leaves': 80, 'max_depth': 7, 'min_child_samples': 14, 'subsample': 0.8180774043632599, 'colsample_bytree': 0.8829340931892606, 'n_estimators': 2000}. Best is trial 5 with value: 0.6325561782796116.

Running time: 1.2 sec
OOF RMSE: 2.18 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:31:35,324] Trial 7 finished with value: 0.565504461967156 and parameters: {'learning_rate': 0.00853925385908214, 'num_leaves': 60, 'max_depth': 6, 'min_child_samples': 9, 'subsample': 0.8242669294084195, 'colsample_bytree': 0.6197782895831468, 'n_estimators': 2000}. Best is trial 5 with value: 0.6325561782796116.

Running time: 1.0 sec
OOF RMSE: 2.29 | R2: 0.57
Fold 1
Fold 2
Fold 3

[I 2025-07-11 16:31:35,778] Trial 8 finished with value: 0.5779487857074648 and parameters: {'learning_rate': 0.09119238378099931, 'num_leaves': 60, 'max_depth': 5, 'min_child_samples': 18, 'subsample': 0.812578969274423, 'colsample_bytree': 0.8648695473106676, 'n_estimators': 1000}. Best is trial 5 with value: 0.6325561782796116.

Fold 4
Fold 5
Running time: 0.4 sec
OOF RMSE: 2.25 | R2: 0.58
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 16:31:36,245] Trial 9 finished with value: 0.5904378601022131 and parameters: {'learning_rate': 0.04186643293362598, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 21, 'subsample': 0.6675223051811523, 'colsample_bytree': 0.6804818794805417, 'n_estimators': 1000}. Best is trial 5 with value: 0.6325561782796116.

Fold 5
Running time: 0.5 sec
OOF RMSE: 2.22 | R2: 0.59
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:31:37,838] Trial 10 finished with value: 0.6406627605997834 and parameters: {'learning_rate': 0.02278721739708334, 'num_leaves': 20, 'max_depth': 8, 'min_child_samples': 6, 'subsample': 0.6114129125477802, 'colsample_bytree': 0.9602183321224028, 'n_estimators': 2000}. Best is trial 10 with value: 0.6406627605997834.

Running time: 1.6 sec
OOF RMSE: 2.08 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:31:39,589] Trial 11 finished with value: 0.6187930180834019 and parameters: {'learning_rate': 0.023403132572186836, 'num_leaves': 20, 'max_depth': 8, 'min_child_samples': 5, 'subsample': 0.6143207788680375, 'colsample_bytree': 0.9960365054213722, 'n_estimators': 2000}. Best is trial 10 with value: 0.6406627605997834.

Running time: 1.7 sec
OOF RMSE: 2.14 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:31:40,991] Trial 12 finished with value: 0.6230015432918183 and parameters: {'learning_rate': 0.021504224377532986, 'num_leaves': 20, 'max_depth': 8, 'min_child_samples': 10, 'subsample': 0.6231130285253857, 'colsample_bytree': 0.983474506175506, 'n_estimators': 2000}. Best is trial 10 with value: 0.6406627605997834.

Running time: 1.4 sec
OOF RMSE: 2.13 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:31:42,773] Trial 13 finished with value: 0.64022129093034 and parameters: {'learning_rate': 0.03949742591421202, 'num_leaves': 40, 'max_depth': 8, 'min_child_samples': 5, 'subsample': 0.7523089118013275, 'colsample_bytree': 0.7132994227656936, 'n_estimators': 2000}. Best is trial 10 with value: 0.6406627605997834.

Running time: 1.8 sec
OOF RMSE: 2.08 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:31:44,012] Trial 14 finished with value: 0.6574985310707853 and parameters: {'learning_rate': 0.04162474407952709, 'num_leaves': 40, 'max_depth': 5, 'min_child_samples': 5, 'subsample': 0.9266985587468115, 'colsample_bytree': 0.7248233128276992, 'n_estimators': 2000}. Best is trial 14 with value: 0.6574985310707853.

Running time: 1.2 sec
OOF RMSE: 2.03 | R2: 0.66
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:31:44,881] Trial 15 finished with value: 0.6137266939716717 and parameters: {'learning_rate': 0.036841484548595343, 'num_leaves': 40, 'max_depth': 5, 'min_child_samples': 16, 'subsample': 0.9957069120298143, 'colsample_bytree': 0.7374298552982904, 'n_estimators': 2000}. Best is trial 14 with value: 0.6574985310707853.

Running time: 0.9 sec
OOF RMSE: 2.15 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 16:31:45,915] Trial 16 finished with value: 0.5966926476085046 and parameters: {'learning_rate': 0.0142921917746523, 'num_leaves': 40, 'max_depth': 6, 'min_child_samples': 11, 'subsample': 0.8941629638935846, 'colsample_bytree': 0.9402930327241324, 'n_estimators': 2000}. Best is trial 14 with value: 0.6574985310707853.

Fold 5
Running time: 1.0 sec
OOF RMSE: 2.20 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:31:47,014] Trial 17 finished with value: 0.6288654016991273 and parameters: {'learning_rate': 0.05217773375111687, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 8, 'subsample': 0.8818798148551159, 'colsample_bytree': 0.9180487556479344, 'n_estimators': 2000}. Best is trial 14 with value: 0.6574985310707853.

Running time: 1.1 sec
OOF RMSE: 2.11 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 16:31:47,297] Trial 18 finished with value: 0.5975044518002854 and parameters: {'learning_rate': 0.01661621115014351, 'num_leaves': 40, 'max_depth': 6, 'min_child_samples': 13, 'subsample': 0.9951651739024203, 'colsample_bytree': 0.7350379307089616, 'n_estimators': 500}. Best is trial 14 with value: 0.6574985310707853.

Fold 5
Running time: 0.3 sec
OOF RMSE: 2.20 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 16:31:47,909] Trial 19 finished with value: 0.6407765642462105 and parameters: {'learning_rate': 0.031214533111687072, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 5, 'subsample': 0.8956868761837207, 'colsample_bytree': 0.8644218795110981, 'n_estimators': 1000}. Best is trial 14 with value: 0.6574985310707853.

Fold 5
Running time: 0.6 sec
OOF RMSE: 2.08 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 16:31:48,427] Trial 20 finished with value: 0.6223421276085505 and parameters: {'learning_rate': 0.030901174094962597, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 16, 'subsample': 0.9212881777119551, 'colsample_bytree': 0.861163764071203, 'n_estimators': 1000}. Best is trial 14 with value: 0.6574985310707853.

Fold 5
Running time: 0.5 sec
OOF RMSE: 2.13 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:31:49,084] Trial 21 finished with value: 0.6257800740628965 and parameters: {'learning_rate': 0.04946196138399401, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 5, 'subsample': 0.8634928148345296, 'colsample_bytree': 0.9690944324581193, 'n_estimators': 1000}. Best is trial 14 with value: 0.6574985310707853.

Running time: 0.7 sec
OOF RMSE: 2.12 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 16:31:49,693] Trial 22 finished with value: 0.6275800636600868 and parameters: {'learning_rate': 0.030804911854760534, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 7, 'subsample': 0.9462836722220449, 'colsample_bytree': 0.9279294353631342, 'n_estimators': 1000}. Best is trial 14 with value: 0.6574985310707853.

Fold 5
Running time: 0.6 sec
OOF RMSE: 2.12 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 16:31:50,155] Trial 23 finished with value: 0.5742167089633253 and parameters: {'learning_rate': 0.015636509628101432, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 9, 'subsample': 0.7662920248982299, 'colsample_bytree': 0.8937120260730304, 'n_estimators': 1000}. Best is trial 14 with value: 0.6574985310707853.

Fold 5
Running time: 0.5 sec
OOF RMSE: 2.26 | R2: 0.57
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:31:51,399] Trial 24 finished with value: 0.6512655517208783 and parameters: {'learning_rate': 0.054704955854032726, 'num_leaves': 40, 'max_depth': 5, 'min_child_samples': 5, 'subsample': 0.9629169967813177, 'colsample_bytree': 0.7615352282239011, 'n_estimators': 2000}. Best is trial 14 with value: 0.6574985310707853.
[I 2025-07-11 16:31:51,400] A new study created in memory with name: no-name-f8d820bb-6a0a-419f-9a89-d2fb9753f099

Running time: 1.2 sec
OOF RMSE: 2.05 | R2: 0.65

✅ LBM - Mejor R2: 0.66
📋 Parámetros: {'learning_rate': 0.04162474407952709, 'num_leaves': 40, 'max_depth': 5, 'min_child_samples': 5, 'subsample': 0.9266985587468115, 'colsample_bytree': 0.7248233128276992, 'n_estimators': 2000}

Buscando mejores hiperparámetros para MLP...
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 16:31:52,812] Trial 0 finished with value: 0.5276658538314605 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'relu', 'solver': 'adam', 'alpha': 3.381782812802012e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00048758899050421257}. Best is trial 0 with value: 0.5276658538314605.

Fold 4
Fold 5
Running time: 1.4 sec
OOF RMSE: 2.38 | R2: 0.53
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

[I 2025-07-11 16:31:54,316] Trial 1 finished with value: 0.5192817551939696 and parameters: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.01642452558011563, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00042829067803239787}. Best is trial 0 with value: 0.5276658538314605.

Running time: 1.5 sec
OOF RMSE: 2.40 | R2: 0.52
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 16:31:56,586] Trial 2 finished with value: 0.4855415376950625 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.015555619250722904, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00023284370084001996}. Best is trial 0 with value: 0.5276658538314605.

Running time: 2.3 sec
OOF RMSE: 2.49 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:31:57,952] Trial 3 finished with value: 0.4679311451198108 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.0009116508214966294, 'learning_rate': 'constant', 'learning_rate_init': 0.006456101361624033}. Best is trial 0 with value: 0.5276658538314605.

Running time: 1.4 sec
OOF RMSE: 2.53 | R2: 0.47
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 16:31:59,104] Trial 4 finished with value: 0.5159536354065664 and parameters: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.00742975108980752, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0010478892131184378}. Best is trial 0 with value: 0.5276658538314605.

Fold 5
Running time: 1.1 sec
OOF RMSE: 2.41 | R2: 0.52
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

[I 2025-07-11 16:32:00,549] Trial 5 finished with value: 0.4181291257166124 and parameters: {'hidden_layer_sizes': '50', 'activation': 'relu', 'solver': 'adam', 'alpha': 3.398785045780945e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00013297629110755346}. Best is trial 0 with value: 0.5276658538314605.

Running time: 1.4 sec
OOF RMSE: 2.64 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:32:01,401] Trial 6 finished with value: 0.30932712317721833 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.001581291454877448, 'learning_rate': 'constant', 'learning_rate_init': 0.0042599388988114875}. Best is trial 0 with value: 0.5276658538314605.

Running time: 0.8 sec
OOF RMSE: 2.88 | R2: 0.31
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 16:32:02,341] Trial 7 finished with value: 0.464752384104942 and parameters: {'hidden_layer_sizes': '50', 'activation': 'relu', 'solver': 'adam', 'alpha': 1.5069018764787468e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.0042059257328950815}. Best is trial 0 with value: 0.5276658538314605.

Fold 4
Fold 5
Running time: 0.9 sec
OOF RMSE: 2.54 | R2: 0.46
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 16:32:03,857] Trial 8 finished with value: 0.4880191818755115 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.06176653820919371, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0003743864380576506}. Best is trial 0 with value: 0.5276658538314605.

Fold 5
Running time: 1.5 sec
OOF RMSE: 2.48 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:32:05,310] Trial 9 finished with value: 0.49991336976299616 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.00024330296749278463, 'learning_rate': 'adaptive', 'learning_rate_init': 0.005779320030742124}. Best is trial 0 with value: 0.5276658538314605.

Running time: 1.4 sec
OOF RMSE: 2.45 | R2: 0.50
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

[I 2025-07-11 16:32:07,565] Trial 10 finished with value: 0.46794329551779734 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 9.203225073983915e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.0013030195466670787}. Best is trial 0 with value: 0.5276658538314605.

Running time: 2.2 sec
OOF RMSE: 2.53 | R2: 0.47
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

[I 2025-07-11 16:32:09,773] Trial 11 finished with value: 0.4788007877968934 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.004591990977524824, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0004891095120333045}. Best is trial 0 with value: 0.5276658538314605.

Running time: 2.2 sec
OOF RMSE: 2.50 | R2: 0.48
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

[I 2025-07-11 16:32:12,708] Trial 12 finished with value: 0.4778326246227592 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.05321259072295791, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0006606703677383469}. Best is trial 0 with value: 0.5276658538314605.

Running time: 2.9 sec
OOF RMSE: 2.50 | R2: 0.48
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 16:32:14,962] Trial 13 finished with value: 0.5093211640407704 and parameters: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.0003731084734603107, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00010450234756497876}. Best is trial 0 with value: 0.5276658538314605.

Running time: 2.2 sec
OOF RMSE: 2.43 | R2: 0.51
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 16:32:16,123] Trial 14 finished with value: 0.49849926283202095 and parameters: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'adam', 'alpha': 7.645635683937252e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.001979738700800398}. Best is trial 0 with value: 0.5276658538314605.

Fold 5
Running time: 1.2 sec
OOF RMSE: 2.45 | R2: 0.50
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

[I 2025-07-11 16:32:18,096] Trial 15 finished with value: 0.47286433436193565 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.0018955866450107116, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00025888200750494067}. Best is trial 0 with value: 0.5276658538314605.

Running time: 2.0 sec
OOF RMSE: 2.52 | R2: 0.47
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 16:32:19,415] Trial 16 finished with value: 0.5102956842317616 and parameters: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'sgd', 'alpha': 1.3420073292216223e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0021565838132447976}. Best is trial 0 with value: 0.5276658538314605.

Running time: 1.3 sec
OOF RMSE: 2.43 | R2: 0.51
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 16:32:20,639] Trial 17 finished with value: 0.5218112834638202 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.017015540454808922, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00056639133770473}. Best is trial 0 with value: 0.5276658538314605.

Fold 4
Fold 5
Running time: 1.2 sec
OOF RMSE: 2.40 | R2: 0.52
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

[I 2025-07-11 16:32:22,407] Trial 18 finished with value: 0.5491650073239971 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.000337334069702823, 'learning_rate': 'constant', 'learning_rate_init': 0.0007315625366372503}. Best is trial 18 with value: 0.5491650073239971.

Running time: 1.8 sec
OOF RMSE: 2.33 | R2: 0.55
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

[I 2025-07-11 16:32:23,972] Trial 19 finished with value: 0.5524014895800109 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.00020730496460716715, 'learning_rate': 'constant', 'learning_rate_init': 0.0007661035235554581}. Best is trial 19 with value: 0.5524014895800109.

Running time: 1.6 sec
OOF RMSE: 2.32 | R2: 0.55
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

[I 2025-07-11 16:32:25,301] Trial 20 finished with value: 0.5841563192771925 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0003573998959502826, 'learning_rate': 'constant', 'learning_rate_init': 0.0021264571227200104}. Best is trial 20 with value: 0.5841563192771925.

Running time: 1.3 sec
OOF RMSE: 2.24 | R2: 0.58
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

[I 2025-07-11 16:32:26,726] Trial 21 finished with value: 0.58928775013719 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.00029263185289869385, 'learning_rate': 'constant', 'learning_rate_init': 0.0019044566385725953}. Best is trial 21 with value: 0.58928775013719.

Running time: 1.4 sec
OOF RMSE: 2.22 | R2: 0.59
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

[I 2025-07-11 16:32:28,103] Trial 22 finished with value: 0.584633917746114 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0001487720177435641, 'learning_rate': 'constant', 'learning_rate_init': 0.002409118698396056}. Best is trial 21 with value: 0.58928775013719.

Running time: 1.4 sec
OOF RMSE: 2.23 | R2: 0.58
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

[I 2025-07-11 16:32:29,475] Trial 23 finished with value: 0.5852765905807322 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0007100033429809107, 'learning_rate': 'constant', 'learning_rate_init': 0.0025103592488012875}. Best is trial 21 with value: 0.58928775013719.

Running time: 1.4 sec
OOF RMSE: 2.23 | R2: 0.59
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:32:30,759] Trial 24 finished with value: 0.613640426476394 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0007892560801364265, 'learning_rate': 'constant', 'learning_rate_init': 0.0030861230712521974}. Best is trial 24 with value: 0.613640426476394.
[I 2025-07-11 16:32:30,761] A new study created in memory with name: no-name-e90c4363-9991-4cd3-8441-5e813e4196c6
[I 2025-07-11 16:32:30,851] Trial 0 finished with value: -8.02839706127431 and parameters: {'kernel': 'sigmoid', 'C': 1.4609966589580918, 'epsilon': 0.18228263019087207, 'gamma': 'scale'}. Best is trial 0 with value: -8.02839706127431.
[I 2025-07-11 16:32:30,924] Trial 1 finished with value: -1.0565448759017362 and parameters: {'kernel': 'sigmoid', 'C': 0.5017898339535595, 'epsilon': 0.02087373092458226, 'gamma': 'scale'}. Best is trial 1 with value: -1.0565448759017362.

Running time: 1.3 sec
OOF RMSE: 2.15 | R2: 0.61

✅ MLP - Mejor R2: 0.61
📋 Parámetros: {'hidden_layer_sizes': '100_50', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0007892560801364265, 'learning_rate': 'constant', 'learning_rate_init': 0.0030861230712521974}

Buscando mejores hiperparámetros para SVR...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 10.42 | R2: -8.03
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 4.97 | R2: -1.06
Fold 1
Fold 2
Fold 3

[I 2025-07-11 16:32:30,998] Trial 2 finished with value: 0.24519089876515687 and parameters: {'kernel': 'rbf', 'C': 0.7953047203076653, 'epsilon': 0.022310915904817392, 'gamma': 'scale'}. Best is trial 2 with value: 0.24519089876515687.
[I 2025-07-11 16:32:31,068] Trial 3 finished with value: 0.3023363926927405 and parameters: {'kernel': 'rbf', 'C': 1.2175983573769664, 'epsilon': 0.12003445860235297, 'gamma': 'scale'}. Best is trial 3 with value: 0.3023363926927405.
[I 2025-07-11 16:32:31,136] Trial 4 finished with value: 0.448516534244613 and parameters: {'kernel': 'rbf', 'C': 5.264670566844495, 'epsilon': 0.09791010765732884, 'gamma': 'auto'}. Best is trial 4 with value: 0.448516534244613.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.01 | R2: 0.25
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.90 | R2: 0.30
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.57 | R2: 0.45
Fold 1
Fold 2
Fold 3

[I 2025-07-11 16:32:31,208] Trial 5 finished with value: -42.48855351188513 and parameters: {'kernel': 'sigmoid', 'C': 3.546809139572075, 'epsilon': 0.01711715329104672, 'gamma': 'scale'}. Best is trial 4 with value: 0.448516534244613.
[I 2025-07-11 16:32:31,279] Trial 6 finished with value: -0.009342011335983225 and parameters: {'kernel': 'sigmoid', 'C': 0.44982242346398765, 'epsilon': 0.13481988816905585, 'gamma': 'auto'}. Best is trial 4 with value: 0.448516534244613.
[I 2025-07-11 16:32:31,350] Trial 7 finished with value: -189.23283068743189 and parameters: {'kernel': 'sigmoid', 'C': 7.85901236363411, 'epsilon': 0.09829100531889147, 'gamma': 'scale'}. Best is trial 4 with value: 0.448516534244613.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 22.86 | R2: -42.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.48 | R2: -0.01
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 47.81 | R2: -189.23
Fold 1
Fold 2
Fold 3

[I 2025-07-11 16:32:31,422] Trial 8 finished with value: -53.887604591276606 and parameters: {'kernel': 'sigmoid', 'C': 4.030051979160109, 'epsilon': 0.14933814671503595, 'gamma': 'scale'}. Best is trial 4 with value: 0.448516534244613.
[I 2025-07-11 16:32:31,493] Trial 9 finished with value: 0.020621569746111734 and parameters: {'kernel': 'sigmoid', 'C': 0.2960377206741797, 'epsilon': 0.06639463142514589, 'gamma': 'scale'}. Best is trial 4 with value: 0.448516534244613.
[I 2025-07-11 16:32:31,566] Trial 10 finished with value: 0.0647826581304537 and parameters: {'kernel': 'rbf', 'C': 0.12769711092316197, 'epsilon': 0.08042449867468954, 'gamma': 'auto'}. Best is trial 4 with value: 0.448516534244613.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 25.68 | R2: -53.89
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.43 | R2: 0.02
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.35 | R2: 0.06
Fold 1
Fold 2

[I 2025-07-11 16:32:31,640] Trial 11 finished with value: 0.3357996775328874 and parameters: {'kernel': 'rbf', 'C': 1.7838151141483987, 'epsilon': 0.12512106983525625, 'gamma': 'auto'}. Best is trial 4 with value: 0.448516534244613.
[I 2025-07-11 16:32:31,717] Trial 12 finished with value: 0.37248967753797146 and parameters: {'kernel': 'rbf', 'C': 2.644913398059098, 'epsilon': 0.16450779488085324, 'gamma': 'auto'}. Best is trial 4 with value: 0.448516534244613.
[I 2025-07-11 16:32:31,793] Trial 13 finished with value: 0.471468756551108 and parameters: {'kernel': 'rbf', 'C': 9.813043204611303, 'epsilon': 0.1916668482169918, 'gamma': 'auto'}. Best is trial 13 with value: 0.471468756551108.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.83 | R2: 0.34
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.75 | R2: 0.37
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.52 | R2: 0.47

[I 2025-07-11 16:32:31,872] Trial 14 finished with value: 0.4717009664080015 and parameters: {'kernel': 'rbf', 'C': 9.910598767358806, 'epsilon': 0.19232584702065708, 'gamma': 'auto'}. Best is trial 14 with value: 0.4717009664080015.
[I 2025-07-11 16:32:31,950] Trial 15 finished with value: 0.46443217500848744 and parameters: {'kernel': 'rbf', 'C': 7.994381002748662, 'epsilon': 0.19824975961143382, 'gamma': 'auto'}. Best is trial 14 with value: 0.4717009664080015.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.52 | R2: 0.47
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.54 | R2: 0.46
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 16:32:32,027] Trial 16 finished with value: 0.46668537611411653 and parameters: {'kernel': 'rbf', 'C': 8.34615461486472, 'epsilon': 0.1707452298147702, 'gamma': 'auto'}. Best is trial 14 with value: 0.4717009664080015.
[I 2025-07-11 16:32:32,105] Trial 17 finished with value: 0.471604341260325 and parameters: {'kernel': 'rbf', 'C': 9.960589681843537, 'epsilon': 0.19721035834820777, 'gamma': 'auto'}. Best is trial 14 with value: 0.4717009664080015.
[I 2025-07-11 16:32:32,178] Trial 18 finished with value: 0.35684161843393936 and parameters: {'kernel': 'rbf', 'C': 2.2385488192057643, 'epsilon': 0.1547846407780964, 'gamma': 'auto'}. Best is trial 14 with value: 0.4717009664080015.

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.53 | R2: 0.47
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.52 | R2: 0.47
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.78 | R2: 0.36
Fold 1
Fold 2

[I 2025-07-11 16:32:32,253] Trial 19 finished with value: 0.43722949039722003 and parameters: {'kernel': 'rbf', 'C': 4.680808712972642, 'epsilon': 0.17736271821771052, 'gamma': 'auto'}. Best is trial 14 with value: 0.4717009664080015.
[I 2025-07-11 16:32:32,324] Trial 20 finished with value: 0.060133899210777275 and parameters: {'kernel': 'rbf', 'C': 0.11993324155690979, 'epsilon': 0.05202339288939567, 'gamma': 'auto'}. Best is trial 14 with value: 0.4717009664080015.
[I 2025-07-11 16:32:32,400] Trial 21 finished with value: 0.4712666849587124 and parameters: {'kernel': 'rbf', 'C': 9.777531592538734, 'epsilon': 0.19508319613015324, 'gamma': 'auto'}. Best is trial 14 with value: 0.4717009664080015.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.60 | R2: 0.44
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.36 | R2: 0.06
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.52 | R2: 0.47
Fold 1

[I 2025-07-11 16:32:32,476] Trial 22 finished with value: 0.44767081824819543 and parameters: {'kernel': 'rbf', 'C': 5.538104390931548, 'epsilon': 0.1986333397571966, 'gamma': 'auto'}. Best is trial 14 with value: 0.4717009664080015.
[I 2025-07-11 16:32:32,556] Trial 23 finished with value: 0.4568989239568101 and parameters: {'kernel': 'rbf', 'C': 6.2926769454947005, 'epsilon': 0.14536981338458843, 'gamma': 'auto'}. Best is trial 14 with value: 0.4717009664080015.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.58 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.55 | R2: 0.46
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:32:32,632] Trial 24 finished with value: 0.390391252739568 and parameters: {'kernel': 'rbf', 'C': 3.076481602281127, 'epsilon': 0.18349674556025705, 'gamma': 'auto'}. Best is trial 14 with value: 0.4717009664080015.
[I 2025-07-11 16:32:32,633] A new study created in memory with name: no-name-5b410ce1-129c-47bd-ba80-e01e0e49298e
[I 2025-07-11 16:32:32,693] Trial 0 finished with value: 0.5634181785723564 and parameters: {'n_neighbors': 11, 'weights': 'uniform', 'leaf_size': 11}. Best is trial 0 with value: 0.5634181785723564.
[I 2025-07-11 16:32:32,753] Trial 1 finished with value: 0.5515286789439761 and parameters: {'n_neighbors': 12, 'weights': 'uniform', 'leaf_size': 28}. Best is trial 0 with value: 0.5634181785723564.
[I 2025-07-11 16:32:32,812] Trial 2 finished with value: 0.6955469440108317 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'leaf_size': 11}. Best is trial 2 with value: 0.6955469440108317.

Running time: 0.1 sec
OOF RMSE: 2.71 | R2: 0.39

✅ SVR - Mejor R2: 0.47
📋 Parámetros: {'kernel': 'rbf', 'C': 9.910598767358806, 'epsilon': 0.19232584702065708, 'gamma': 'auto'}

Buscando mejores hiperparámetros para KNN...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.29 | R2: 0.56
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.32 | R2: 0.55
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.91 | R2: 0.70
Fold 1
Fold 2

[I 2025-07-11 16:32:32,876] Trial 3 finished with value: 0.6500343298579653 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'leaf_size': 40}. Best is trial 2 with value: 0.6955469440108317.
[I 2025-07-11 16:32:32,938] Trial 4 finished with value: 0.6500343298579653 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'leaf_size': 36}. Best is trial 2 with value: 0.6955469440108317.
[I 2025-07-11 16:32:32,997] Trial 5 finished with value: 0.6500343298579653 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'leaf_size': 40}. Best is trial 2 with value: 0.6955469440108317.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.05 | R2: 0.65
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.05 | R2: 0.65
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.05 | R2: 0.65
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 16:32:33,059] Trial 6 finished with value: 0.5867691918652256 and parameters: {'n_neighbors': 7, 'weights': 'uniform', 'leaf_size': 32}. Best is trial 2 with value: 0.6955469440108317.
[I 2025-07-11 16:32:33,121] Trial 7 finished with value: 0.5634181785723564 and parameters: {'n_neighbors': 11, 'weights': 'uniform', 'leaf_size': 23}. Best is trial 2 with value: 0.6955469440108317.
[I 2025-07-11 16:32:33,180] Trial 8 finished with value: 0.5634181785723564 and parameters: {'n_neighbors': 11, 'weights': 'uniform', 'leaf_size': 22}. Best is trial 2 with value: 0.6955469440108317.
[I 2025-07-11 16:32:33,239] Trial 9 finished with value: 0.7012966245681302 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 16}. Best is trial 9 with value: 0.7012966245681302.

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.23 | R2: 0.59
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.29 | R2: 0.56
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.29 | R2: 0.56
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.89 | R2: 0.70

[I 2025-07-11 16:32:33,307] Trial 10 finished with value: 0.6135307729669508 and parameters: {'n_neighbors': 15, 'weights': 'distance', 'leaf_size': 17}. Best is trial 9 with value: 0.7012966245681302.
[I 2025-07-11 16:32:33,378] Trial 11 finished with value: 0.7012966245681302 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 10}. Best is trial 9 with value: 0.7012966245681302.
[I 2025-07-11 16:32:33,445] Trial 12 finished with value: 0.7012966245681302 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 16}. Best is trial 9 with value: 0.7012966245681302.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.16 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.89 | R2: 0.70
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.89 | R2: 0.70

[I 2025-07-11 16:32:33,517] Trial 13 finished with value: 0.7012966245681302 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 17}. Best is trial 9 with value: 0.7012966245681302.
[I 2025-07-11 16:32:33,587] Trial 14 finished with value: 0.6230621829091003 and parameters: {'n_neighbors': 8, 'weights': 'distance', 'leaf_size': 10}. Best is trial 9 with value: 0.7012966245681302.
[I 2025-07-11 16:32:33,653] Trial 15 finished with value: 0.6955469440108317 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'leaf_size': 15}. Best is trial 9 with value: 0.7012966245681302.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.89 | R2: 0.70
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.13 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.91 | R2: 0.70

[I 2025-07-11 16:32:33,728] Trial 16 finished with value: 0.6968581092557494 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'leaf_size': 21}. Best is trial 9 with value: 0.7012966245681302.
[I 2025-07-11 16:32:33,795] Trial 17 finished with value: 0.6395580991004299 and parameters: {'n_neighbors': 9, 'weights': 'distance', 'leaf_size': 14}. Best is trial 9 with value: 0.7012966245681302.
[I 2025-07-11 16:32:33,861] Trial 18 finished with value: 0.7012966245681302 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 19}. Best is trial 9 with value: 0.7012966245681302.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.91 | R2: 0.70
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.08 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.89 | R2: 0.70

[I 2025-07-11 16:32:33,930] Trial 19 finished with value: 0.6230621829091003 and parameters: {'n_neighbors': 8, 'weights': 'distance', 'leaf_size': 25}. Best is trial 9 with value: 0.7012966245681302.
[I 2025-07-11 16:32:33,998] Trial 20 finished with value: 0.6135307729669508 and parameters: {'n_neighbors': 15, 'weights': 'distance', 'leaf_size': 13}. Best is trial 9 with value: 0.7012966245681302.
[I 2025-07-11 16:32:34,065] Trial 21 finished with value: 0.7012966245681302 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 17}. Best is trial 9 with value: 0.7012966245681302.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.13 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.16 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.89 | R2: 0.70
Fold 1

[I 2025-07-11 16:32:34,137] Trial 22 finished with value: 0.6955469440108317 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'leaf_size': 13}. Best is trial 9 with value: 0.7012966245681302.
[I 2025-07-11 16:32:34,205] Trial 23 finished with value: 0.6968581092557494 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'leaf_size': 19}. Best is trial 9 with value: 0.7012966245681302.
[I 2025-07-11 16:32:34,274] Trial 24 finished with value: 0.6968581092557494 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'leaf_size': 10}. Best is trial 9 with value: 0.7012966245681302.
[I 2025-07-11 16:32:34,275] A new study created in memory with name: no-name-1940ec1d-c2b7-445c-9843-4223d30f7fc5

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.91 | R2: 0.70
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.91 | R2: 0.70
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.91 | R2: 0.70

✅ KNN - Mejor R2: 0.70
📋 Parámetros: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 16}

Buscando mejores hiperparámetros para LR...
Fold 1
Fold 2

[I 2025-07-11 16:32:34,357] Trial 0 finished with value: -1.109477509555699 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 0 with value: -1.109477509555699.
[I 2025-07-11 16:32:34,432] Trial 1 finished with value: -0.14990513404622652 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 1 with value: -0.14990513404622652.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 5.03 | R2: -1.11
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.72 | R2: -0.15
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:32:34,515] Trial 2 finished with value: -1.109477509551517 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 1 with value: -0.14990513404622652.
[I 2025-07-11 16:32:34,600] Trial 3 finished with value: -1.109477509551517 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 1 with value: -0.14990513404622652.
[I 2025-07-11 16:32:34,674] Trial 4 finished with value: -0.1495363584594449 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 4 with value: -0.1495363584594449.

Running time: 0.1 sec
OOF RMSE: 5.03 | R2: -1.11
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 5.03 | R2: -1.11
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.72 | R2: -0.15
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 16:32:34,733] Trial 5 finished with value: -0.14990513404622652 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 4 with value: -0.1495363584594449.
[I 2025-07-11 16:32:34,791] Trial 6 finished with value: -0.14990513404622652 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 4 with value: -0.1495363584594449.
[I 2025-07-11 16:32:34,849] Trial 7 finished with value: -0.14990513404622652 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 4 with value: -0.1495363584594449.
[I 2025-07-11 16:32:34,904] Trial 8 finished with value: -0.14990513404622652 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 4 with value: -0.1495363584594449.

Fold 5
Running time: 0.1 sec
OOF RMSE: 3.72 | R2: -0.15
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.72 | R2: -0.15
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.72 | R2: -0.15
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.72 | R2: -0.15
Fold 1
Fold 2

[I 2025-07-11 16:32:34,966] Trial 9 finished with value: -0.1495363584594449 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 4 with value: -0.1495363584594449.
[I 2025-07-11 16:32:35,110] Trial 10 finished with value: -1.109477509551517 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 4 with value: -0.1495363584594449.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.72 | R2: -0.15
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 5.03 | R2: -1.11
Fold 1

[I 2025-07-11 16:32:35,200] Trial 11 finished with value: -0.1495363584594449 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 4 with value: -0.1495363584594449.
[I 2025-07-11 16:32:35,259] Trial 12 finished with value: -0.1495363584594449 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 4 with value: -0.1495363584594449.
[I 2025-07-11 16:32:35,316] Trial 13 finished with value: -0.1495363584594449 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 4 with value: -0.1495363584594449.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.72 | R2: -0.15
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.72 | R2: -0.15
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.72 | R2: -0.15
Fold 1
Fold 2
Fold 3

[I 2025-07-11 16:32:35,375] Trial 14 finished with value: -0.1495363584594449 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 4 with value: -0.1495363584594449.
[I 2025-07-11 16:32:35,434] Trial 15 finished with value: -0.1495363584594449 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 4 with value: -0.1495363584594449.
[I 2025-07-11 16:32:35,493] Trial 16 finished with value: -0.1495363584594449 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 4 with value: -0.1495363584594449.
[I 2025-07-11 16:32:35,551] Trial 17 finished with value: -0.1495363584594449 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 4 with value: -0.1495363584594449.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.72 | R2: -0.15
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.72 | R2: -0.15
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.72 | R2: -0.15
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.72 | R2: -0.15

[I 2025-07-11 16:32:35,634] Trial 18 finished with value: -1.109477509551517 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 4 with value: -0.1495363584594449.
[I 2025-07-11 16:32:35,709] Trial 19 finished with value: -0.1495363584594449 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 4 with value: -0.1495363584594449.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 5.03 | R2: -1.11
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.72 | R2: -0.15
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:32:35,767] Trial 20 finished with value: -0.1495363584594449 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 4 with value: -0.1495363584594449.
[I 2025-07-11 16:32:35,825] Trial 21 finished with value: -0.1495363584594449 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 4 with value: -0.1495363584594449.
[I 2025-07-11 16:32:35,884] Trial 22 finished with value: -0.1495363584594449 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 4 with value: -0.1495363584594449.
[I 2025-07-11 16:32:35,940] Trial 23 finished with value: -0.1495363584594449 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 4 with value: -0.1495363584594449.

Running time: 0.1 sec
OOF RMSE: 3.72 | R2: -0.15
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.72 | R2: -0.15
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.72 | R2: -0.15
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.72 | R2: -0.15
Fold 1
Fold 2
Fold 3

[I 2025-07-11 16:32:36,000] Trial 24 finished with value: -0.1495363584594449 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 4 with value: -0.1495363584594449.
[I 2025-07-11 16:32:36,001] A new study created in memory with name: no-name-5248bfd2-3f6c-49de-bf3d-ad6a785526aa

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.72 | R2: -0.15

✅ LR - Mejor R2: -0.15
📋 Parámetros: {'fit_intercept': False, 'positive': True}

Buscando mejores hiperparámetros para RF...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:32:40,131] Trial 0 finished with value: 0.5507149675315078 and parameters: {'n_estimators': 300, 'max_depth': 6, 'min_samples_split': 9, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 0 with value: 0.5507149675315078.

Running time: 4.1 sec
OOF RMSE: 2.32 | R2: 0.55
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:32:41,914] Trial 1 finished with value: 0.44276768777885256 and parameters: {'n_estimators': 100, 'max_depth': 5, 'min_samples_split': 9, 'min_samples_leaf': 4, 'bootstrap': False}. Best is trial 0 with value: 0.5507149675315078.

Running time: 1.8 sec
OOF RMSE: 2.59 | R2: 0.44
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:32:43,228] Trial 2 finished with value: 0.5849854858272416 and parameters: {'n_estimators': 100, 'max_depth': 5, 'min_samples_split': 5, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 2 with value: 0.5849854858272416.

Running time: 1.3 sec
OOF RMSE: 2.23 | R2: 0.58
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:32:47,552] Trial 3 finished with value: 0.5291639298919076 and parameters: {'n_estimators': 300, 'max_depth': 13, 'min_samples_split': 4, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 2 with value: 0.5849854858272416.

Running time: 4.3 sec
OOF RMSE: 2.38 | R2: 0.53
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:32:51,999] Trial 4 finished with value: 0.5370208351602235 and parameters: {'n_estimators': 300, 'max_depth': 8, 'min_samples_split': 9, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 2 with value: 0.5849854858272416.

Running time: 4.4 sec
OOF RMSE: 2.36 | R2: 0.54
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:32:53,450] Trial 5 finished with value: 0.5302534028221932 and parameters: {'n_estimators': 100, 'max_depth': 11, 'min_samples_split': 4, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 2 with value: 0.5849854858272416.

Running time: 1.4 sec
OOF RMSE: 2.38 | R2: 0.53
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:32:56,088] Trial 6 finished with value: 0.48823422833103247 and parameters: {'n_estimators': 100, 'max_depth': 14, 'min_samples_split': 6, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 2 with value: 0.5849854858272416.

Running time: 2.6 sec
OOF RMSE: 2.48 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:32:57,686] Trial 7 finished with value: 0.5557410376626213 and parameters: {'n_estimators': 100, 'max_depth': 12, 'min_samples_split': 10, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 2 with value: 0.5849854858272416.

Running time: 1.6 sec
OOF RMSE: 2.31 | R2: 0.56
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:32:59,939] Trial 8 finished with value: 0.434954025248395 and parameters: {'n_estimators': 100, 'max_depth': 8, 'min_samples_split': 5, 'min_samples_leaf': 4, 'bootstrap': False}. Best is trial 2 with value: 0.5849854858272416.

Running time: 2.2 sec
OOF RMSE: 2.61 | R2: 0.43
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:33:08,974] Trial 9 finished with value: 0.5829259682691161 and parameters: {'n_estimators': 500, 'max_depth': 15, 'min_samples_split': 5, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 2 with value: 0.5849854858272416.

Running time: 9.0 sec
OOF RMSE: 2.24 | R2: 0.58
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:33:22,849] Trial 10 finished with value: 0.5335382382287791 and parameters: {'n_estimators': 500, 'max_depth': 9, 'min_samples_split': 2, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 2 with value: 0.5849854858272416.

Running time: 13.9 sec
OOF RMSE: 2.37 | R2: 0.53
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:33:32,094] Trial 11 finished with value: 0.5783117809374336 and parameters: {'n_estimators': 500, 'max_depth': 15, 'min_samples_split': 7, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 2 with value: 0.5849854858272416.

Running time: 9.2 sec
OOF RMSE: 2.25 | R2: 0.58
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:33:40,995] Trial 12 finished with value: 0.5875310178598356 and parameters: {'n_estimators': 500, 'max_depth': 10, 'min_samples_split': 2, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 12 with value: 0.5875310178598356.

Running time: 8.9 sec
OOF RMSE: 2.23 | R2: 0.59
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:33:48,896] Trial 13 finished with value: 0.5872259686138811 and parameters: {'n_estimators': 500, 'max_depth': 7, 'min_samples_split': 2, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 12 with value: 0.5875310178598356.

Running time: 7.9 sec
OOF RMSE: 2.23 | R2: 0.59
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:33:57,860] Trial 14 finished with value: 0.5875310178598356 and parameters: {'n_estimators': 500, 'max_depth': 10, 'min_samples_split': 2, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 12 with value: 0.5875310178598356.

Running time: 9.0 sec
OOF RMSE: 2.23 | R2: 0.59
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:34:06,785] Trial 15 finished with value: 0.5875310178598356 and parameters: {'n_estimators': 500, 'max_depth': 10, 'min_samples_split': 3, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 12 with value: 0.5875310178598356.

Running time: 8.9 sec
OOF RMSE: 2.23 | R2: 0.59
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:34:16,769] Trial 16 finished with value: 0.6046231595240374 and parameters: {'n_estimators': 500, 'max_depth': 10, 'min_samples_split': 2, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 16 with value: 0.6046231595240374.

Running time: 10.0 sec
OOF RMSE: 2.18 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:34:26,865] Trial 17 finished with value: 0.5992019930142822 and parameters: {'n_estimators': 500, 'max_depth': 12, 'min_samples_split': 3, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 16 with value: 0.6046231595240374.

Running time: 10.1 sec
OOF RMSE: 2.19 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:34:42,167] Trial 18 finished with value: 0.5403528190774471 and parameters: {'n_estimators': 500, 'max_depth': 12, 'min_samples_split': 3, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 16 with value: 0.6046231595240374.

Running time: 15.3 sec
OOF RMSE: 2.35 | R2: 0.54
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:34:52,208] Trial 19 finished with value: 0.5992019930142822 and parameters: {'n_estimators': 500, 'max_depth': 12, 'min_samples_split': 3, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 16 with value: 0.6046231595240374.

Running time: 10.0 sec
OOF RMSE: 2.19 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:35:01,472] Trial 20 finished with value: 0.579697359262342 and parameters: {'n_estimators': 500, 'max_depth': 13, 'min_samples_split': 7, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 16 with value: 0.6046231595240374.

Running time: 9.3 sec
OOF RMSE: 2.25 | R2: 0.58
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:35:11,597] Trial 21 finished with value: 0.5992019930142822 and parameters: {'n_estimators': 500, 'max_depth': 12, 'min_samples_split': 3, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 16 with value: 0.6046231595240374.

Running time: 10.1 sec
OOF RMSE: 2.19 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:35:21,304] Trial 22 finished with value: 0.5969917192006471 and parameters: {'n_estimators': 500, 'max_depth': 11, 'min_samples_split': 4, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 16 with value: 0.6046231595240374.

Running time: 9.7 sec
OOF RMSE: 2.20 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:35:31,263] Trial 23 finished with value: 0.6003612788784969 and parameters: {'n_estimators': 500, 'max_depth': 11, 'min_samples_split': 3, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 16 with value: 0.6046231595240374.

Running time: 10.0 sec
OOF RMSE: 2.19 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:35:40,439] Trial 24 finished with value: 0.5970111850267232 and parameters: {'n_estimators': 500, 'max_depth': 9, 'min_samples_split': 4, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 16 with value: 0.6046231595240374.
[I 2025-07-11 16:35:40,440] A new study created in memory with name: no-name-4c06eb53-bbba-47e4-92af-c985f2d1e9b0

Running time: 9.2 sec
OOF RMSE: 2.20 | R2: 0.60

✅ RF - Mejor R2: 0.60
📋 Parámetros: {'n_estimators': 500, 'max_depth': 10, 'min_samples_split': 2, 'min_samples_leaf': 1, 'bootstrap': True}

Buscando mejores hiperparámetros para CAT...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:38:18,261] Trial 0 finished with value: 0.7013949389650374 and parameters: {'iterations': 1000, 'learning_rate': 0.03321071871637441, 'depth': 10, 'l2_leaf_reg': 2.3939913640438526}. Best is trial 0 with value: 0.7013949389650374.

Running time: 157.8 sec
OOF RMSE: 1.89 | R2: 0.70
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:38:28,437] Trial 1 finished with value: 0.698041532355484 and parameters: {'iterations': 2000, 'learning_rate': 0.010744773756669755, 'depth': 5, 'l2_leaf_reg': 6.492804537236944}. Best is trial 0 with value: 0.7013949389650374.

Running time: 10.2 sec
OOF RMSE: 1.90 | R2: 0.70
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:38:36,978] Trial 2 finished with value: 0.703770513862101 and parameters: {'iterations': 500, 'learning_rate': 0.05855195796928237, 'depth': 7, 'l2_leaf_reg': 3.9733126523880253}. Best is trial 2 with value: 0.703770513862101.

Running time: 8.5 sec
OOF RMSE: 1.89 | R2: 0.70
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:39:15,980] Trial 3 finished with value: 0.7011436368474161 and parameters: {'iterations': 1000, 'learning_rate': 0.02473468021840742, 'depth': 8, 'l2_leaf_reg': 9.500709366649561}. Best is trial 2 with value: 0.703770513862101.

Running time: 39.0 sec
OOF RMSE: 1.90 | R2: 0.70
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:40:39,174] Trial 4 finished with value: 0.7035170141399072 and parameters: {'iterations': 1000, 'learning_rate': 0.05276909151717579, 'depth': 9, 'l2_leaf_reg': 6.848367793656706}. Best is trial 2 with value: 0.703770513862101.

Running time: 83.2 sec
OOF RMSE: 1.89 | R2: 0.70
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:42:02,968] Trial 5 finished with value: 0.708127026178391 and parameters: {'iterations': 1000, 'learning_rate': 0.022540257801375238, 'depth': 9, 'l2_leaf_reg': 1.133073971146791}. Best is trial 5 with value: 0.708127026178391.

Running time: 83.8 sec
OOF RMSE: 1.87 | R2: 0.71
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:44:50,153] Trial 6 finished with value: 0.6996862174707082 and parameters: {'iterations': 2000, 'learning_rate': 0.023937088391500584, 'depth': 9, 'l2_leaf_reg': 3.1827227843719688}. Best is trial 5 with value: 0.708127026178391.

Running time: 167.2 sec
OOF RMSE: 1.90 | R2: 0.70
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:45:03,838] Trial 7 finished with value: 0.6957978208991622 and parameters: {'iterations': 1000, 'learning_rate': 0.052754188056788894, 'depth': 7, 'l2_leaf_reg': 7.326162280767455}. Best is trial 5 with value: 0.708127026178391.

Running time: 13.7 sec
OOF RMSE: 1.91 | R2: 0.70
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:45:05,415] Trial 8 finished with value: 0.6827118315850678 and parameters: {'iterations': 500, 'learning_rate': 0.06797577537873446, 'depth': 4, 'l2_leaf_reg': 9.509821935650278}. Best is trial 5 with value: 0.708127026178391.

Running time: 1.6 sec
OOF RMSE: 1.95 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:45:12,515] Trial 9 finished with value: 0.7011926943032554 and parameters: {'iterations': 1000, 'learning_rate': 0.016148905045756876, 'depth': 6, 'l2_leaf_reg': 1.4362189172142918}. Best is trial 5 with value: 0.708127026178391.

Running time: 7.1 sec
OOF RMSE: 1.89 | R2: 0.70
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:46:24,245] Trial 10 finished with value: 0.6706351852088639 and parameters: {'iterations': 500, 'learning_rate': 0.010525555790234849, 'depth': 10, 'l2_leaf_reg': 4.642499505036827}. Best is trial 5 with value: 0.708127026178391.
[I 2025-07-11 16:46:24,246] A new study created in memory with name: no-name-9ef96b9b-16b8-4a41-b171-6b073d14af82
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.632e+00, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.250e+00, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.904e+00, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.367e+00, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.160e+00, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 16:46:24,346] Trial 0 finished with value: 0.4765882823903774 and parameters: {'alpha': 0.014155560173112822, 'l1_ratio': 0.5260907704650059}. Best is trial 0 with value: 0.4765882823903774.
[I 2025-07-11 16:46:24,426] Trial 1 finished with value: 0.492647386063934 and parameters: {'alpha': 0.06579098533497037, 'l1_ratio': 0.882150685584886}. Best is trial 1 with value: 0.492647386063934.

Running time: 71.7 sec
OOF RMSE: 1.99 | R2: 0.67

✅ CAT - Mejor R2: 0.71
📋 Parámetros: {'iterations': 1000, 'learning_rate': 0.022540257801375238, 'depth': 9, 'l2_leaf_reg': 1.133073971146791}

Buscando mejores hiperparámetros para EN...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.51 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.47 | R2: 0.49
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.955e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.715e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.724e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.069e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.877e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 16:46:24,551] Trial 2 finished with value: -0.1985959669741093 and parameters: {'alpha': 0.00011858578887035016, 'l1_ratio': 0.2594911559994816}. Best is trial 1 with value: 0.492647386063934.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.578e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.438e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.195e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.746e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.80 | R2: -0.20
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.686e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 16:46:24,668] Trial 3 finished with value: -0.19685493899573037 and parameters: {'alpha': 0.00021639410220079193, 'l1_ratio': 0.663686937565564}. Best is trial 1 with value: 0.492647386063934.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.411e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.922e+01, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.526e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.586e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.152e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 16:46:24,794] Trial 4 finished with value: 0.4429438145042547 and parameters: {'alpha': 0.006379983571790573, 'l1_ratio': 0.19968877739345015}. Best is trial 1 with value: 0.492647386063934.

Running time: 0.1 sec
OOF RMSE: 3.79 | R2: -0.20
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.59 | R2: 0.44
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:46:24,879] Trial 5 finished with value: 0.49165212872473796 and parameters: {'alpha': 0.06947237554037146, 'l1_ratio': 0.5191824125558913}. Best is trial 1 with value: 0.492647386063934.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.459e+01, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.160e+00, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.564e+01, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.963e+01, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.522e+01, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 16:46:25,011] Trial 6 finished with value: 0.4247302662987762 and parameters: {'alpha': 0.004899935125457658, 'l1_ratio': 0.5405946622781194}. Best is trial 1 with value: 0.492647386063934.

Running time: 0.1 sec
OOF RMSE: 2.47 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.63 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:46:25,097] Trial 7 finished with value: 0.4926254373139273 and parameters: {'alpha': 0.1526993057179395, 'l1_ratio': 0.4291328340693841}. Best is trial 1 with value: 0.492647386063934.
[I 2025-07-11 16:46:25,197] Trial 8 finished with value: 0.493476899138121 and parameters: {'alpha': 0.09854689672024648, 'l1_ratio': 0.5128227159204264}. Best is trial 8 with value: 0.493476899138121.
[I 2025-07-11 16:46:25,279] Trial 9 finished with value: 0.4895790222371327 and parameters: {'alpha': 0.18927923922961915, 'l1_ratio': 0.4428774507540495}. Best is trial 8 with value: 0.493476899138121.

Running time: 0.1 sec
OOF RMSE: 2.47 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.47 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.48 | R2: 0.49
Fold 1

[I 2025-07-11 16:46:25,378] Trial 10 finished with value: 0.42232049344876843 and parameters: {'alpha': 3.1622700343489356, 'l1_ratio': 0.008948706622583291}. Best is trial 8 with value: 0.493476899138121.
[I 2025-07-11 16:46:25,469] Trial 11 finished with value: 0.2542001293850973 and parameters: {'alpha': 1.2306158650088925, 'l1_ratio': 0.9893504740556515}. Best is trial 8 with value: 0.493476899138121.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.63 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.99 | R2: 0.25
Fold 1
Fold 2

[I 2025-07-11 16:46:25,569] Trial 12 finished with value: 0.4250297605022657 and parameters: {'alpha': 0.617321477366432, 'l1_ratio': 0.8795043310957031}. Best is trial 8 with value: 0.493476899138121.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.416e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.795e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.598e+01, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.399e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.116e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 16:46:25,703] Trial 13 finished with value: 0.0066586929967201725 and parameters: {'alpha': 0.0010925280417424712, 'l1_ratio': 0.723467438739114}. Best is trial 8 with value: 0.493476899138121.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.63 | R2: 0.43
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.45 | R2: 0.01
Fold 1

[I 2025-07-11 16:46:25,816] Trial 14 finished with value: 0.4875244764111205 and parameters: {'alpha': 0.03501833383906636, 'l1_ratio': 0.8038689298306099}. Best is trial 8 with value: 0.493476899138121.
[I 2025-07-11 16:46:25,905] Trial 15 finished with value: -0.00027817151752640434 and parameters: {'alpha': 8.956443883823583, 'l1_ratio': 0.989978828693474}. Best is trial 8 with value: 0.493476899138121.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.48 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.47 | R2: -0.00
Fold 1
Fold 2

[I 2025-07-11 16:46:26,014] Trial 16 finished with value: 0.49017622524125715 and parameters: {'alpha': 0.23195237442174726, 'l1_ratio': 0.30367228462875906}. Best is trial 8 with value: 0.493476899138121.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.921e+01, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.199e+01, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.496e+01, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.615e+01, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.144e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 16:46:26,152] Trial 17 finished with value: 0.12820047156316305 and parameters: {'alpha': 0.0016517407898463943, 'l1_ratio': 0.6763250958396841}. Best is trial 8 with value: 0.493476899138121.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.48 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.24 | R2: 0.13

[I 2025-07-11 16:46:26,255] Trial 18 finished with value: 0.4882420732302927 and parameters: {'alpha': 0.03467190427840774, 'l1_ratio': 0.8507032505125365}. Best is trial 8 with value: 0.493476899138121.
[I 2025-07-11 16:46:26,349] Trial 19 finished with value: 0.46675937935470035 and parameters: {'alpha': 0.7664596434237045, 'l1_ratio': 0.13461308957998042}. Best is trial 8 with value: 0.493476899138121.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.48 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.53 | R2: 0.47
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.068e+01, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.353e+00, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.112e+00, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.021e+01, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.548e+00, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 16:46:26,477] Trial 20 finished with value: 0.4674926218139328 and parameters: {'alpha': 0.00976316965294509, 'l1_ratio': 0.6295507532865939}. Best is trial 8 with value: 0.493476899138121.
[I 2025-07-11 16:46:26,573] Trial 21 finished with value: 0.49524674353798837 and parameters: {'alpha': 0.13606272144746426, 'l1_ratio': 0.29414025605506305}. Best is trial 21 with value: 0.49524674353798837.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.53 | R2: 0.47
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.46 | R2: 0.50

[I 2025-07-11 16:46:26,676] Trial 22 finished with value: 0.4933459356809605 and parameters: {'alpha': 0.08235471076044944, 'l1_ratio': 0.3260738999712818}. Best is trial 21 with value: 0.49524674353798837.
[I 2025-07-11 16:46:26,770] Trial 23 finished with value: 0.4794383817413783 and parameters: {'alpha': 0.3381787719601626, 'l1_ratio': 0.36426647773614007}. Best is trial 21 with value: 0.49524674353798837.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.47 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.50 | R2: 0.48
Fold 1

[I 2025-07-11 16:46:26,887] Trial 24 finished with value: 0.496557290116995 and parameters: {'alpha': 0.09663056847398992, 'l1_ratio': 0.1369199420011986}. Best is trial 24 with value: 0.496557290116995.
[I 2025-07-11 16:46:26,888] A new study created in memory with name: no-name-4ec07dda-46b8-486f-8959-7658818119d0

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.46 | R2: 0.50

✅ EN - Mejor R2: 0.50
📋 Parámetros: {'alpha': 0.09663056847398992, 'l1_ratio': 0.1369199420011986}

🔍 Optimizando en TOA_9x9_depth_lt_1...
Buscando mejores hiperparámetros para XGB...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:46:32,519] Trial 0 finished with value: 0.704598955801957 and parameters: {'n_estimators': 1000, 'learning_rate': 0.008782432546249913, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.6098786312367778, 'colsample_bytree': 0.9050948620438275}. Best is trial 0 with value: 0.704598955801957.

Running time: 5.6 sec
OOF RMSE: 2.06 | R2: 0.70
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:46:38,232] Trial 1 finished with value: 0.6876643139207848 and parameters: {'n_estimators': 1000, 'learning_rate': 0.005081564239425179, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.757430452465799, 'colsample_bytree': 0.9518674504346039}. Best is trial 0 with value: 0.704598955801957.

Running time: 5.7 sec
OOF RMSE: 2.11 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:46:47,042] Trial 2 finished with value: 0.6793713572930025 and parameters: {'n_estimators': 2000, 'learning_rate': 0.03878031291026211, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.853773341542166, 'colsample_bytree': 0.7430619066166777}. Best is trial 0 with value: 0.704598955801957.

Running time: 8.8 sec
OOF RMSE: 2.14 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:46:56,180] Trial 3 finished with value: 0.6856656912265645 and parameters: {'n_estimators': 2000, 'learning_rate': 0.04602880397565294, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.9452222167535242, 'colsample_bytree': 0.7558193767090309}. Best is trial 0 with value: 0.704598955801957.

Running time: 9.1 sec
OOF RMSE: 2.12 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:47:08,759] Trial 4 finished with value: 0.6525749574766642 and parameters: {'n_estimators': 2000, 'learning_rate': 0.01882596420697029, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.9314302758327453, 'colsample_bytree': 0.8510499705181911}. Best is trial 0 with value: 0.704598955801957.

Running time: 12.6 sec
OOF RMSE: 2.23 | R2: 0.65
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:47:19,392] Trial 5 finished with value: 0.6751829529122906 and parameters: {'n_estimators': 2000, 'learning_rate': 0.014850119088409764, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.6130047741540383, 'colsample_bytree': 0.892670728415031}. Best is trial 0 with value: 0.704598955801957.

Running time: 10.6 sec
OOF RMSE: 2.16 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:47:25,787] Trial 6 finished with value: 0.7107346566255919 and parameters: {'n_estimators': 1000, 'learning_rate': 0.013029384541501212, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.7612887857837007, 'colsample_bytree': 0.8242019354795606}. Best is trial 6 with value: 0.7107346566255919.

Running time: 6.4 sec
OOF RMSE: 2.03 | R2: 0.71
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:47:29,161] Trial 7 finished with value: 0.6459575911617013 and parameters: {'n_estimators': 500, 'learning_rate': 0.05757733319971274, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.9932607251135046, 'colsample_bytree': 0.8283408009190151}. Best is trial 6 with value: 0.7107346566255919.

Running time: 3.4 sec
OOF RMSE: 2.25 | R2: 0.65
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:47:34,994] Trial 8 finished with value: 0.6654677937721469 and parameters: {'n_estimators': 500, 'learning_rate': 0.006234380295621712, 'max_depth': 8, 'min_child_weight': 1, 'subsample': 0.8815642145017016, 'colsample_bytree': 0.810781280194179}. Best is trial 6 with value: 0.7107346566255919.

Running time: 5.8 sec
OOF RMSE: 2.19 | R2: 0.67
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:47:38,824] Trial 9 finished with value: 0.6639787449494725 and parameters: {'n_estimators': 500, 'learning_rate': 0.0445865890743996, 'max_depth': 6, 'min_child_weight': 1, 'subsample': 0.8810344425597403, 'colsample_bytree': 0.8400358719985137}. Best is trial 6 with value: 0.7107346566255919.

Running time: 3.8 sec
OOF RMSE: 2.19 | R2: 0.66
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:47:43,243] Trial 10 finished with value: 0.7333586869788931 and parameters: {'n_estimators': 1000, 'learning_rate': 0.09753680383740422, 'max_depth': 8, 'min_child_weight': 3, 'subsample': 0.7262136436494508, 'colsample_bytree': 0.6034642558535326}. Best is trial 10 with value: 0.7333586869788931.

Running time: 4.4 sec
OOF RMSE: 1.95 | R2: 0.73
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:47:47,398] Trial 11 finished with value: 0.724195468488317 and parameters: {'n_estimators': 1000, 'learning_rate': 0.09726361061767538, 'max_depth': 8, 'min_child_weight': 3, 'subsample': 0.7350579876294687, 'colsample_bytree': 0.6046177680706223}. Best is trial 10 with value: 0.7333586869788931.

Running time: 4.1 sec
OOF RMSE: 1.99 | R2: 0.72
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:47:51,869] Trial 12 finished with value: 0.7339530341960728 and parameters: {'n_estimators': 1000, 'learning_rate': 0.09152782294673709, 'max_depth': 8, 'min_child_weight': 3, 'subsample': 0.7025566564893392, 'colsample_bytree': 0.6066719858961065}. Best is trial 12 with value: 0.7339530341960728.

Running time: 4.5 sec
OOF RMSE: 1.95 | R2: 0.73
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:47:56,315] Trial 13 finished with value: 0.7351452017395188 and parameters: {'n_estimators': 1000, 'learning_rate': 0.0941414719200959, 'max_depth': 8, 'min_child_weight': 4, 'subsample': 0.687461094864037, 'colsample_bytree': 0.6036063776594468}. Best is trial 13 with value: 0.7351452017395188.

Running time: 4.4 sec
OOF RMSE: 1.95 | R2: 0.74
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:48:02,261] Trial 14 finished with value: 0.7306125712679588 and parameters: {'n_estimators': 1000, 'learning_rate': 0.02797183471062539, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.6665841227042337, 'colsample_bytree': 0.6737857047301136}. Best is trial 13 with value: 0.7351452017395188.

Running time: 5.9 sec
OOF RMSE: 1.96 | R2: 0.73
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:48:07,847] Trial 15 finished with value: 0.7251444322667764 and parameters: {'n_estimators': 1000, 'learning_rate': 0.07345438415371744, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.6750700868087461, 'colsample_bytree': 0.6938088042064497}. Best is trial 13 with value: 0.7351452017395188.

Running time: 5.6 sec
OOF RMSE: 1.98 | R2: 0.73
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:48:14,572] Trial 16 finished with value: 0.7248181078765858 and parameters: {'n_estimators': 1000, 'learning_rate': 0.027969624241129913, 'max_depth': 8, 'min_child_weight': 4, 'subsample': 0.6865134522257611, 'colsample_bytree': 0.6614909044185762}. Best is trial 13 with value: 0.7351452017395188.

Running time: 6.7 sec
OOF RMSE: 1.98 | R2: 0.72
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:48:19,532] Trial 17 finished with value: 0.7109734731894772 and parameters: {'n_estimators': 1000, 'learning_rate': 0.06968415890289707, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.8100940131310226, 'colsample_bytree': 0.6450013842676091}. Best is trial 13 with value: 0.7351452017395188.

Running time: 5.0 sec
OOF RMSE: 2.03 | R2: 0.71
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:48:25,640] Trial 18 finished with value: 0.6915847988670608 and parameters: {'n_estimators': 1000, 'learning_rate': 0.0668614027245105, 'max_depth': 8, 'min_child_weight': 4, 'subsample': 0.8112428687105597, 'colsample_bytree': 0.728928391417671}. Best is trial 13 with value: 0.7351452017395188.

Running time: 6.1 sec
OOF RMSE: 2.10 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:48:28,950] Trial 19 finished with value: 0.7510546854967972 and parameters: {'n_estimators': 500, 'learning_rate': 0.03587187536212219, 'max_depth': 8, 'min_child_weight': 3, 'subsample': 0.6414704974641332, 'colsample_bytree': 0.6372324135122972}. Best is trial 19 with value: 0.7510546854967972.

Running time: 3.3 sec
OOF RMSE: 1.89 | R2: 0.75
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:48:31,835] Trial 20 finished with value: 0.7287401102590714 and parameters: {'n_estimators': 500, 'learning_rate': 0.032078661646179944, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.6411217893640688, 'colsample_bytree': 0.6967138365420262}. Best is trial 19 with value: 0.7510546854967972.

Running time: 2.9 sec
OOF RMSE: 1.97 | R2: 0.73
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:48:34,971] Trial 21 finished with value: 0.72329048698033 and parameters: {'n_estimators': 500, 'learning_rate': 0.09757270322859793, 'max_depth': 8, 'min_child_weight': 3, 'subsample': 0.7035620928211221, 'colsample_bytree': 0.630592592974961}. Best is trial 19 with value: 0.7510546854967972.

Running time: 3.1 sec
OOF RMSE: 1.99 | R2: 0.72
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:48:38,057] Trial 22 finished with value: 0.7391531341697792 and parameters: {'n_estimators': 500, 'learning_rate': 0.05236463275787683, 'max_depth': 8, 'min_child_weight': 3, 'subsample': 0.6447351305812494, 'colsample_bytree': 0.6301319161905545}. Best is trial 19 with value: 0.7510546854967972.

Running time: 3.1 sec
OOF RMSE: 1.93 | R2: 0.74
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:48:41,293] Trial 23 finished with value: 0.7275052255879815 and parameters: {'n_estimators': 500, 'learning_rate': 0.05422946852192261, 'max_depth': 8, 'min_child_weight': 3, 'subsample': 0.6445027862375746, 'colsample_bytree': 0.7066548496297398}. Best is trial 19 with value: 0.7510546854967972.

Running time: 3.2 sec
OOF RMSE: 1.97 | R2: 0.73
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:48:44,640] Trial 24 finished with value: 0.6904498381824198 and parameters: {'n_estimators': 500, 'learning_rate': 0.038679874608405794, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.6529704563443313, 'colsample_bytree': 0.7712870435558887}. Best is trial 19 with value: 0.7510546854967972.
[I 2025-07-11 16:48:44,641] A new study created in memory with name: no-name-36464348-dfaf-44f2-91e0-4922cf6b49cc

Running time: 3.3 sec
OOF RMSE: 2.10 | R2: 0.69

✅ XGB - Mejor R2: 0.75
📋 Parámetros: {'n_estimators': 500, 'learning_rate': 0.03587187536212219, 'max_depth': 8, 'min_child_weight': 3, 'subsample': 0.6414704974641332, 'colsample_bytree': 0.6372324135122972}

Buscando mejores hiperparámetros para LBM...
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 16:48:45,406] Trial 0 finished with value: 0.5850021083100854 and parameters: {'learning_rate': 0.026725181067313926, 'num_leaves': 20, 'max_depth': 8, 'min_child_samples': 7, 'subsample': 0.6557887048173284, 'colsample_bytree': 0.9377166180175058, 'n_estimators': 1000}. Best is trial 0 with value: 0.5850021083100854.

Fold 5
Running time: 0.8 sec
OOF RMSE: 2.44 | R2: 0.59
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:48:46,264] Trial 1 finished with value: 0.7497824816772293 and parameters: {'learning_rate': 0.015311009821112925, 'num_leaves': 40, 'max_depth': 5, 'min_child_samples': 13, 'subsample': 0.6903005820153549, 'colsample_bytree': 0.647778640316801, 'n_estimators': 2000}. Best is trial 1 with value: 0.7497824816772293.

Running time: 0.9 sec
OOF RMSE: 1.89 | R2: 0.75
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 16:48:47,099] Trial 2 finished with value: 0.695880582667723 and parameters: {'learning_rate': 0.00839092944033308, 'num_leaves': 60, 'max_depth': 8, 'min_child_samples': 25, 'subsample': 0.8872686239651357, 'colsample_bytree': 0.8978727375831184, 'n_estimators': 2000}. Best is trial 1 with value: 0.7497824816772293.

Fold 5
Running time: 0.8 sec
OOF RMSE: 2.09 | R2: 0.70
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 16:48:47,518] Trial 3 finished with value: 0.579335652012162 and parameters: {'learning_rate': 0.04009086831920929, 'num_leaves': 60, 'max_depth': 8, 'min_child_samples': 6, 'subsample': 0.8053226671676444, 'colsample_bytree': 0.9943431400620159, 'n_estimators': 500}. Best is trial 1 with value: 0.7497824816772293.

Fold 5
Running time: 0.4 sec
OOF RMSE: 2.45 | R2: 0.58
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:48:48,807] Trial 4 finished with value: 0.6760675943805605 and parameters: {'learning_rate': 0.08119889080550734, 'num_leaves': 20, 'max_depth': 8, 'min_child_samples': 11, 'subsample': 0.7896417684029697, 'colsample_bytree': 0.7667734921222668, 'n_estimators': 2000}. Best is trial 1 with value: 0.7497824816772293.

Running time: 1.3 sec
OOF RMSE: 2.15 | R2: 0.68
Fold 1
Fold 2
Fold 3

[I 2025-07-11 16:48:49,252] Trial 5 finished with value: 0.7245376858519366 and parameters: {'learning_rate': 0.018346692304383166, 'num_leaves': 40, 'max_depth': 7, 'min_child_samples': 22, 'subsample': 0.9260242873553501, 'colsample_bytree': 0.6969783340415474, 'n_estimators': 1000}. Best is trial 1 with value: 0.7497824816772293.

Fold 4
Fold 5
Running time: 0.4 sec
OOF RMSE: 1.98 | R2: 0.72
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:48:50,337] Trial 6 finished with value: 0.6255626983699316 and parameters: {'learning_rate': 0.06589372756531588, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 6, 'subsample': 0.8541374159689152, 'colsample_bytree': 0.9120089653549075, 'n_estimators': 2000}. Best is trial 1 with value: 0.7497824816772293.

Running time: 1.1 sec
OOF RMSE: 2.31 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 16:48:50,627] Trial 7 finished with value: 0.5810821843267022 and parameters: {'learning_rate': 0.015748627966794295, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 9, 'subsample': 0.9668080628212171, 'colsample_bytree': 0.7684338268499094, 'n_estimators': 500}. Best is trial 1 with value: 0.7497824816772293.

Fold 5
Running time: 0.3 sec
OOF RMSE: 2.45 | R2: 0.58
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:48:52,018] Trial 8 finished with value: 0.7118807689639962 and parameters: {'learning_rate': 0.08420584463484687, 'num_leaves': 80, 'max_depth': 7, 'min_child_samples': 5, 'subsample': 0.7836313478584169, 'colsample_bytree': 0.6401138691183594, 'n_estimators': 2000}. Best is trial 1 with value: 0.7497824816772293.

Running time: 1.4 sec
OOF RMSE: 2.03 | R2: 0.71
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:48:52,264] Trial 9 finished with value: 0.7299693433138308 and parameters: {'learning_rate': 0.07460815509091831, 'num_leaves': 40, 'max_depth': 7, 'min_child_samples': 23, 'subsample': 0.6800158209533207, 'colsample_bytree': 0.9227033403747815, 'n_estimators': 500}. Best is trial 1 with value: 0.7497824816772293.

Running time: 0.2 sec
OOF RMSE: 1.96 | R2: 0.73
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:48:53,149] Trial 10 finished with value: 0.7147490455063779 and parameters: {'learning_rate': 0.005911353264766793, 'num_leaves': 40, 'max_depth': 5, 'min_child_samples': 16, 'subsample': 0.6042169592704626, 'colsample_bytree': 0.6060708559115381, 'n_estimators': 2000}. Best is trial 1 with value: 0.7497824816772293.

Running time: 0.9 sec
OOF RMSE: 2.02 | R2: 0.71
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 16:48:53,449] Trial 11 finished with value: 0.6270843064721279 and parameters: {'learning_rate': 0.011153045133738616, 'num_leaves': 40, 'max_depth': 6, 'min_child_samples': 17, 'subsample': 0.6951255219113908, 'colsample_bytree': 0.8654841523746649, 'n_estimators': 500}. Best is trial 1 with value: 0.7497824816772293.

Fold 5
Running time: 0.3 sec
OOF RMSE: 2.31 | R2: 0.63
Fold 1
Fold 2
Fold 3

[I 2025-07-11 16:48:53,743] Trial 12 finished with value: 0.7375972714193135 and parameters: {'learning_rate': 0.0360854687814494, 'num_leaves': 40, 'max_depth': 6, 'min_child_samples': 13, 'subsample': 0.7168501031615352, 'colsample_bytree': 0.8311029935694244, 'n_estimators': 500}. Best is trial 1 with value: 0.7497824816772293.

Fold 4
Fold 5
Running time: 0.3 sec
OOF RMSE: 1.94 | R2: 0.74
Fold 1
Fold 2

[I 2025-07-11 16:48:54,006] Trial 13 finished with value: 0.7364403772227177 and parameters: {'learning_rate': 0.03031887064826821, 'num_leaves': 40, 'max_depth': 5, 'min_child_samples': 13, 'subsample': 0.7312759465118279, 'colsample_bytree': 0.8377836716946079, 'n_estimators': 500}. Best is trial 1 with value: 0.7497824816772293.

Fold 3
Fold 4
Fold 5
Running time: 0.3 sec
OOF RMSE: 1.94 | R2: 0.74
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 16:48:54,496] Trial 14 finished with value: 0.7507228192950756 and parameters: {'learning_rate': 0.04397213412834972, 'num_leaves': 80, 'max_depth': 6, 'min_child_samples': 18, 'subsample': 0.7359161631066482, 'colsample_bytree': 0.7037071484276278, 'n_estimators': 1000}. Best is trial 14 with value: 0.7507228192950756.

Fold 5
Running time: 0.5 sec
OOF RMSE: 1.89 | R2: 0.75
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:48:54,934] Trial 15 finished with value: 0.7408690835381277 and parameters: {'learning_rate': 0.048647597714093216, 'num_leaves': 80, 'max_depth': 5, 'min_child_samples': 19, 'subsample': 0.611830267337282, 'colsample_bytree': 0.6900302190035889, 'n_estimators': 1000}. Best is trial 14 with value: 0.7507228192950756.

Running time: 0.4 sec
OOF RMSE: 1.92 | R2: 0.74
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:48:55,419] Trial 16 finished with value: 0.7189552200795664 and parameters: {'learning_rate': 0.013649551259587087, 'num_leaves': 80, 'max_depth': 6, 'min_child_samples': 20, 'subsample': 0.7499152417993168, 'colsample_bytree': 0.7134840852779152, 'n_estimators': 1000}. Best is trial 14 with value: 0.7507228192950756.

Running time: 0.5 sec
OOF RMSE: 2.00 | R2: 0.72
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:48:55,897] Trial 17 finished with value: 0.750032286432335 and parameters: {'learning_rate': 0.020190051416137174, 'num_leaves': 80, 'max_depth': 5, 'min_child_samples': 14, 'subsample': 0.6596775337165242, 'colsample_bytree': 0.6508981714022175, 'n_estimators': 1000}. Best is trial 14 with value: 0.7507228192950756.

Running time: 0.5 sec
OOF RMSE: 1.89 | R2: 0.75
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:48:56,397] Trial 18 finished with value: 0.7481783111029194 and parameters: {'learning_rate': 0.023296463730856296, 'num_leaves': 80, 'max_depth': 6, 'min_child_samples': 18, 'subsample': 0.6472991155078284, 'colsample_bytree': 0.7406620088234126, 'n_estimators': 1000}. Best is trial 14 with value: 0.7507228192950756.

Running time: 0.5 sec
OOF RMSE: 1.90 | R2: 0.75
Fold 1
Fold 2
Fold 3

[I 2025-07-11 16:48:56,843] Trial 19 finished with value: 0.7476553987523072 and parameters: {'learning_rate': 0.05156996723367983, 'num_leaves': 80, 'max_depth': 5, 'min_child_samples': 15, 'subsample': 0.8498751442893913, 'colsample_bytree': 0.6579435713491166, 'n_estimators': 1000}. Best is trial 14 with value: 0.7507228192950756.

Fold 4
Fold 5
Running time: 0.4 sec
OOF RMSE: 1.90 | R2: 0.75
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:48:57,393] Trial 20 finished with value: 0.7013066901296621 and parameters: {'learning_rate': 0.020953069223774108, 'num_leaves': 80, 'max_depth': 6, 'min_child_samples': 10, 'subsample': 0.7583176933059871, 'colsample_bytree': 0.6071793628209547, 'n_estimators': 1000}. Best is trial 14 with value: 0.7507228192950756.

Running time: 0.5 sec
OOF RMSE: 2.07 | R2: 0.70
Fold 1
Fold 2
Fold 3

[I 2025-07-11 16:48:57,847] Trial 21 finished with value: 0.7375630058554363 and parameters: {'learning_rate': 0.012453746988662431, 'num_leaves': 80, 'max_depth': 5, 'min_child_samples': 14, 'subsample': 0.6661959478937176, 'colsample_bytree': 0.6628596391815954, 'n_estimators': 1000}. Best is trial 14 with value: 0.7507228192950756.

Fold 4
Fold 5
Running time: 0.4 sec
OOF RMSE: 1.94 | R2: 0.74
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:48:58,726] Trial 22 finished with value: 0.700708531511697 and parameters: {'learning_rate': 0.010524851018447256, 'num_leaves': 80, 'max_depth': 5, 'min_child_samples': 12, 'subsample': 0.716791699296474, 'colsample_bytree': 0.6422181468119998, 'n_estimators': 2000}. Best is trial 14 with value: 0.7507228192950756.

Running time: 0.9 sec
OOF RMSE: 2.07 | R2: 0.70
Fold 1
Fold 2
Fold 3

[I 2025-07-11 16:48:59,183] Trial 23 finished with value: 0.7352189001451993 and parameters: {'learning_rate': 0.01824871024074669, 'num_leaves': 60, 'max_depth': 5, 'min_child_samples': 16, 'subsample': 0.6347730043063883, 'colsample_bytree': 0.725439487863506, 'n_estimators': 1000}. Best is trial 14 with value: 0.7507228192950756.

Fold 4
Fold 5
Running time: 0.5 sec
OOF RMSE: 1.95 | R2: 0.74
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 16:48:59,651] Trial 24 finished with value: 0.735198065047094 and parameters: {'learning_rate': 0.026504988776930992, 'num_leaves': 80, 'max_depth': 6, 'min_child_samples': 21, 'subsample': 0.6939466256913454, 'colsample_bytree': 0.6794858968317454, 'n_estimators': 1000}. Best is trial 14 with value: 0.7507228192950756.
[I 2025-07-11 16:48:59,652] A new study created in memory with name: no-name-69517c31-71d0-44c8-88dd-e9fc6c7749d3

Fold 5
Running time: 0.5 sec
OOF RMSE: 1.95 | R2: 0.74

✅ LBM - Mejor R2: 0.75
📋 Parámetros: {'learning_rate': 0.04397213412834972, 'num_leaves': 80, 'max_depth': 6, 'min_child_samples': 18, 'subsample': 0.7359161631066482, 'colsample_bytree': 0.7037071484276278, 'n_estimators': 1000}

Buscando mejores hiperparámetros para MLP...
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 16:49:00,796] Trial 0 finished with value: 0.3276174776402204 and parameters: {'hidden_layer_sizes': '50', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.017622817625572048, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0004815681127796483}. Best is trial 0 with value: 0.3276174776402204.

Running time: 1.1 sec
OOF RMSE: 3.10 | R2: 0.33
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 16:49:03,213] Trial 1 finished with value: 0.5795752642687293 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.006197528481456607, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00023474176634457575}. Best is trial 1 with value: 0.5795752642687293.

Running time: 2.4 sec
OOF RMSE: 2.45 | R2: 0.58
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 16:49:05,169] Trial 2 finished with value: 0.11768270927353175 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'sgd', 'alpha': 1.2917739922095403e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.00010719639787126706}. Best is trial 1 with value: 0.5795752642687293.

Running time: 2.0 sec
OOF RMSE: 3.55 | R2: 0.12
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 16:49:06,979] Trial 3 finished with value: 0.7267615362708123 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.0011999966477146578, 'learning_rate': 'adaptive', 'learning_rate_init': 0.005350652466948534}. Best is trial 3 with value: 0.7267615362708123.

Running time: 1.8 sec
OOF RMSE: 1.98 | R2: 0.73
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 16:49:08,521] Trial 4 finished with value: 0.058135205015222846 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.0011975044646171747, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00010624045014740698}. Best is trial 3 with value: 0.7267615362708123.

Running time: 1.5 sec
OOF RMSE: 3.67 | R2: 0.06
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 16:49:10,642] Trial 5 finished with value: 0.46374752009561704 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.009625270604133004, 'learning_rate': 'constant', 'learning_rate_init': 0.0006399071830957782}. Best is trial 3 with value: 0.7267615362708123.

Running time: 2.1 sec
OOF RMSE: 2.77 | R2: 0.46
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 16:49:12,267] Trial 6 finished with value: 0.2208908777847336 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.016880273030927987, 'learning_rate': 'constant', 'learning_rate_init': 0.00022190788897854044}. Best is trial 3 with value: 0.7267615362708123.

Running time: 1.6 sec
OOF RMSE: 3.34 | R2: 0.22
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 16:49:13,359] Trial 7 finished with value: 0.3233643104054581 and parameters: {'hidden_layer_sizes': '50', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.008677062934740383, 'learning_rate': 'constant', 'learning_rate_init': 0.00046499459921499326}. Best is trial 3 with value: 0.7267615362708123.

Running time: 1.1 sec
OOF RMSE: 3.11 | R2: 0.32
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 16:49:15,204] Trial 8 finished with value: 0.580416566052927 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0298943259125796, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0003130258677133846}. Best is trial 3 with value: 0.7267615362708123.

Running time: 1.8 sec
OOF RMSE: 2.45 | R2: 0.58
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 16:49:16,388] Trial 9 finished with value: 0.5879621888971028 and parameters: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.06355415189883996, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0032069746867402203}. Best is trial 3 with value: 0.7267615362708123.

Fold 5
Running time: 1.2 sec
OOF RMSE: 2.43 | R2: 0.59
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:49:16,953] Trial 10 finished with value: 0.7428765752453157 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 5.284705751001716e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0072093516185713444}. Best is trial 10 with value: 0.7428765752453157.

Running time: 0.6 sec
OOF RMSE: 1.92 | R2: 0.74
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:49:17,542] Trial 11 finished with value: 0.753658164002937 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 4.942440869894174e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.008991466183990703}. Best is trial 11 with value: 0.753658164002937.

Running time: 0.6 sec
OOF RMSE: 1.88 | R2: 0.75
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:49:18,138] Trial 12 finished with value: 0.7401059910579794 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 2.138310041821882e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.009268756147106223}. Best is trial 11 with value: 0.753658164002937.

Running time: 0.6 sec
OOF RMSE: 1.93 | R2: 0.74
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 16:49:19,028] Trial 13 finished with value: 0.7368174874820463 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 6.557965543918215e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00195601029114616}. Best is trial 11 with value: 0.753658164002937.

Fold 5
Running time: 0.9 sec
OOF RMSE: 1.94 | R2: 0.74
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:49:19,694] Trial 14 finished with value: 0.7480356805244889 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.00015369759272612955, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00917643392899883}. Best is trial 11 with value: 0.753658164002937.

Running time: 0.7 sec
OOF RMSE: 1.90 | R2: 0.75
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 16:49:20,734] Trial 15 finished with value: 0.7407179464104352 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.00015976568091616452, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0014795343547406989}. Best is trial 11 with value: 0.753658164002937.

Fold 5
Running time: 1.0 sec
OOF RMSE: 1.93 | R2: 0.74
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 16:49:21,378] Trial 16 finished with value: 0.7092851779202465 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0002944474031308174, 'learning_rate': 'adaptive', 'learning_rate_init': 0.004168761734747884}. Best is trial 11 with value: 0.753658164002937.

Fold 5
Running time: 0.6 sec
OOF RMSE: 2.04 | R2: 0.71
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 16:49:21,947] Trial 17 finished with value: 0.32132916225468955 and parameters: {'hidden_layer_sizes': '50', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0003356784769722454, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0023648187107151593}. Best is trial 11 with value: 0.753658164002937.

Fold 5
Running time: 0.6 sec
OOF RMSE: 3.12 | R2: 0.32
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 16:49:23,126] Trial 18 finished with value: 0.5236786192778947 and parameters: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'adam', 'alpha': 4.948255513998851e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.0012504010018792907}. Best is trial 11 with value: 0.753658164002937.

Running time: 1.2 sec
OOF RMSE: 2.61 | R2: 0.52
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:49:23,691] Trial 19 finished with value: 0.7322635979608658 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0023212031469903058, 'learning_rate': 'adaptive', 'learning_rate_init': 0.009773928156620638}. Best is trial 11 with value: 0.753658164002937.

Running time: 0.6 sec
OOF RMSE: 1.96 | R2: 0.73
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 16:49:24,481] Trial 20 finished with value: 0.725036601070183 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.00023662546260947288, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0052472069529271225}. Best is trial 11 with value: 0.753658164002937.

Fold 5
Running time: 0.8 sec
OOF RMSE: 1.98 | R2: 0.73
Fold 1
Fold 2
Fold 3

[I 2025-07-11 16:49:25,132] Trial 21 finished with value: 0.7429565675800134 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 6.759788375794325e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.007207967251601501}. Best is trial 11 with value: 0.753658164002937.

Fold 4
Fold 5
Running time: 0.6 sec
OOF RMSE: 1.92 | R2: 0.74
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:49:25,763] Trial 22 finished with value: 0.74281162031102 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.00013027228120305513, 'learning_rate': 'adaptive', 'learning_rate_init': 0.006583071358257713}. Best is trial 11 with value: 0.753658164002937.

Running time: 0.6 sec
OOF RMSE: 1.92 | R2: 0.74
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 16:49:26,476] Trial 23 finished with value: 0.7496081304302321 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 2.49053084090934e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0035139146129884754}. Best is trial 11 with value: 0.753658164002937.

Fold 5
Running time: 0.7 sec
OOF RMSE: 1.89 | R2: 0.75
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:49:27,424] Trial 24 finished with value: 0.7069186674658126 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 2.4676005423083104e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0034256165669401834}. Best is trial 11 with value: 0.753658164002937.
[I 2025-07-11 16:49:27,426] A new study created in memory with name: no-name-7a4598f0-f74c-45ba-89e6-1b8e57972fb7
[I 2025-07-11 16:49:27,528] Trial 0 finished with value: 0.10750133623197289 and parameters: {'kernel': 'rbf', 'C': 1.2481429687114576, 'epsilon': 0.026150548047427703, 'gamma': 'auto'}. Best is trial 0 with value: 0.10750133623197289.
[I 2025-07-11 16:49:27,603] Trial 1 finished with value: 0.19108490857020888 and parameters: {'kernel': 'rbf', 'C': 1.4634326999546274, 'epsilon': 0.026117805966931106, 'gamma': 'scale'}. Best is trial 1 with value: 0.19108490857020888.

Running time: 0.9 sec
OOF RMSE: 2.05 | R2: 0.71

✅ MLP - Mejor R2: 0.75
📋 Parámetros: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 4.942440869894174e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.008991466183990703}

Buscando mejores hiperparámetros para SVR...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.57 | R2: 0.11
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.40 | R2: 0.19
Fold 1
Fold 2

[I 2025-07-11 16:49:27,674] Trial 2 finished with value: 0.24538807412563968 and parameters: {'kernel': 'rbf', 'C': 1.897214835888449, 'epsilon': 0.13043030573327288, 'gamma': 'scale'}. Best is trial 2 with value: 0.24538807412563968.
[I 2025-07-11 16:49:27,748] Trial 3 finished with value: -0.07673323249660036 and parameters: {'kernel': 'sigmoid', 'C': 0.6911546350096278, 'epsilon': 0.09623235206106845, 'gamma': 'auto'}. Best is trial 2 with value: 0.24538807412563968.
[I 2025-07-11 16:49:27,818] Trial 4 finished with value: -0.11707562071924538 and parameters: {'kernel': 'sigmoid', 'C': 0.7886722748138852, 'epsilon': 0.1996318843291831, 'gamma': 'auto'}. Best is trial 2 with value: 0.24538807412563968.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.28 | R2: 0.25
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.92 | R2: -0.08
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 4.00 | R2: -0.12
Fold 1

[I 2025-07-11 16:49:27,895] Trial 5 finished with value: -3.414286565409742 and parameters: {'kernel': 'sigmoid', 'C': 1.5326748425315815, 'epsilon': 0.17274598284031342, 'gamma': 'scale'}. Best is trial 2 with value: 0.24538807412563968.
[I 2025-07-11 16:49:27,965] Trial 6 finished with value: 0.13434179456439999 and parameters: {'kernel': 'rbf', 'C': 0.9439015716779474, 'epsilon': 0.1971389266533263, 'gamma': 'scale'}. Best is trial 2 with value: 0.24538807412563968.
[I 2025-07-11 16:49:28,035] Trial 7 finished with value: -0.07629796669813005 and parameters: {'kernel': 'sigmoid', 'C': 0.18194897848375371, 'epsilon': 0.072296048740055, 'gamma': 'scale'}. Best is trial 2 with value: 0.24538807412563968.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 7.94 | R2: -3.41
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.52 | R2: 0.13
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.92 | R2: -0.08

[I 2025-07-11 16:49:28,109] Trial 8 finished with value: -1.317029889363181 and parameters: {'kernel': 'sigmoid', 'C': 2.264549650921575, 'epsilon': 0.1574741345851526, 'gamma': 'auto'}. Best is trial 2 with value: 0.24538807412563968.
[I 2025-07-11 16:49:28,183] Trial 9 finished with value: -15.670550146156526 and parameters: {'kernel': 'sigmoid', 'C': 3.19385358970511, 'epsilon': 0.06910629049323175, 'gamma': 'scale'}. Best is trial 2 with value: 0.24538807412563968.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 5.76 | R2: -1.32
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 15.44 | R2: -15.67
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 16:49:28,262] Trial 10 finished with value: 0.5581275431182127 and parameters: {'kernel': 'rbf', 'C': 8.369332636515223, 'epsilon': 0.12690703513475554, 'gamma': 'scale'}. Best is trial 10 with value: 0.5581275431182127.
[I 2025-07-11 16:49:28,342] Trial 11 finished with value: 0.5729132721916651 and parameters: {'kernel': 'rbf', 'C': 9.357085628387868, 'epsilon': 0.13578326687595543, 'gamma': 'scale'}. Best is trial 11 with value: 0.5729132721916651.
[I 2025-07-11 16:49:28,419] Trial 12 finished with value: 0.5633512179619411 and parameters: {'kernel': 'rbf', 'C': 8.636475928216406, 'epsilon': 0.1363572701533687, 'gamma': 'scale'}. Best is trial 11 with value: 0.5729132721916651.

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.51 | R2: 0.56
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.47 | R2: 0.57
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.50 | R2: 0.56
Fold 1
Fold 2

[I 2025-07-11 16:49:28,499] Trial 13 finished with value: 0.5776686845232404 and parameters: {'kernel': 'rbf', 'C': 9.972464370426488, 'epsilon': 0.1390615243836335, 'gamma': 'scale'}. Best is trial 13 with value: 0.5776686845232404.
[I 2025-07-11 16:49:28,577] Trial 14 finished with value: 0.44724955826036195 and parameters: {'kernel': 'rbf', 'C': 4.6484066013803025, 'epsilon': 0.10345666722338102, 'gamma': 'scale'}. Best is trial 13 with value: 0.5776686845232404.
[I 2025-07-11 16:49:28,654] Trial 15 finished with value: 0.4824653401102207 and parameters: {'kernel': 'rbf', 'C': 5.3632141773346245, 'epsilon': 0.16064384702544013, 'gamma': 'scale'}. Best is trial 13 with value: 0.5776686845232404.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.46 | R2: 0.58
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.81 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.72 | R2: 0.48

[I 2025-07-11 16:49:28,730] Trial 16 finished with value: 0.023778406192354162 and parameters: {'kernel': 'rbf', 'C': 0.4278726577269505, 'epsilon': 0.07845479110999298, 'gamma': 'scale'}. Best is trial 13 with value: 0.5776686845232404.
[I 2025-07-11 16:49:28,808] Trial 17 finished with value: 0.5735831099212484 and parameters: {'kernel': 'rbf', 'C': 9.399598974305714, 'epsilon': 0.14750022461603501, 'gamma': 'scale'}. Best is trial 13 with value: 0.5776686845232404.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.74 | R2: 0.02
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.47 | R2: 0.57
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 16:49:28,884] Trial 18 finished with value: 0.3306835588437388 and parameters: {'kernel': 'rbf', 'C': 4.510049512349084, 'epsilon': 0.17056052442169906, 'gamma': 'auto'}. Best is trial 13 with value: 0.5776686845232404.
[I 2025-07-11 16:49:28,959] Trial 19 finished with value: -0.06383839811007719 and parameters: {'kernel': 'rbf', 'C': 0.10292917529215823, 'epsilon': 0.15406686541303644, 'gamma': 'scale'}. Best is trial 13 with value: 0.5776686845232404.
[I 2025-07-11 16:49:29,034] Trial 20 finished with value: 0.34049898236758647 and parameters: {'kernel': 'rbf', 'C': 2.9514753119497557, 'epsilon': 0.11916134546969995, 'gamma': 'scale'}. Best is trial 13 with value: 0.5776686845232404.

Fold 5
Running time: 0.1 sec
OOF RMSE: 3.09 | R2: 0.33
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.90 | R2: -0.06
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.07 | R2: 0.34
Fold 1
Fold 2
Fold 3

[I 2025-07-11 16:49:29,114] Trial 21 finished with value: 0.5758498848939437 and parameters: {'kernel': 'rbf', 'C': 9.759409201367564, 'epsilon': 0.14302996377361982, 'gamma': 'scale'}. Best is trial 13 with value: 0.5776686845232404.
[I 2025-07-11 16:49:29,191] Trial 22 finished with value: 0.5158945744724592 and parameters: {'kernel': 'rbf', 'C': 6.392154266904004, 'epsilon': 0.14704471314026413, 'gamma': 'scale'}. Best is trial 13 with value: 0.5776686845232404.
[I 2025-07-11 16:49:29,267] Trial 23 finished with value: 0.3765671584111153 and parameters: {'kernel': 'rbf', 'C': 3.383838796133941, 'epsilon': 0.17798475814672407, 'gamma': 'scale'}. Best is trial 13 with value: 0.5776686845232404.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.46 | R2: 0.58
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.63 | R2: 0.52
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.99 | R2: 0.38
Fold 1

[I 2025-07-11 16:49:29,345] Trial 24 finished with value: 0.529508413082927 and parameters: {'kernel': 'rbf', 'C': 7.023261963733132, 'epsilon': 0.11528235339105501, 'gamma': 'scale'}. Best is trial 13 with value: 0.5776686845232404.
[I 2025-07-11 16:49:29,347] A new study created in memory with name: no-name-d365ac06-6589-41d0-9da2-af4a86abe4de
[I 2025-07-11 16:49:29,407] Trial 0 finished with value: 0.40853612517611704 and parameters: {'n_neighbors': 13, 'weights': 'uniform', 'leaf_size': 33}. Best is trial 0 with value: 0.40853612517611704.
[I 2025-07-11 16:49:29,466] Trial 1 finished with value: 0.5897826441441967 and parameters: {'n_neighbors': 7, 'weights': 'uniform', 'leaf_size': 11}. Best is trial 1 with value: 0.5897826441441967.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.59 | R2: 0.53

✅ SVR - Mejor R2: 0.58
📋 Parámetros: {'kernel': 'rbf', 'C': 9.972464370426488, 'epsilon': 0.1390615243836335, 'gamma': 'scale'}

Buscando mejores hiperparámetros para KNN...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.91 | R2: 0.41
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.42 | R2: 0.59
Fold 1
Fold 2
Fold 3

[I 2025-07-11 16:49:29,529] Trial 2 finished with value: 0.7792909633973581 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'leaf_size': 35}. Best is trial 2 with value: 0.7792909633973581.
[I 2025-07-11 16:49:29,617] Trial 3 finished with value: 0.5048791709275628 and parameters: {'n_neighbors': 9, 'weights': 'uniform', 'leaf_size': 25}. Best is trial 2 with value: 0.7792909633973581.
[I 2025-07-11 16:49:29,676] Trial 4 finished with value: 0.6708837325414748 and parameters: {'n_neighbors': 8, 'weights': 'distance', 'leaf_size': 22}. Best is trial 2 with value: 0.7792909633973581.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.78 | R2: 0.78
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.66 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.17 | R2: 0.67
Fold 1
Fold 2
Fold 3

[I 2025-07-11 16:49:29,738] Trial 5 finished with value: 0.6018107905845962 and parameters: {'n_neighbors': 11, 'weights': 'distance', 'leaf_size': 36}. Best is trial 2 with value: 0.7792909633973581.
[I 2025-07-11 16:49:29,798] Trial 6 finished with value: 0.537576672929843 and parameters: {'n_neighbors': 15, 'weights': 'distance', 'leaf_size': 25}. Best is trial 2 with value: 0.7792909633973581.
[I 2025-07-11 16:49:29,855] Trial 7 finished with value: 0.7889007264172183 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 34}. Best is trial 7 with value: 0.7889007264172183.
[I 2025-07-11 16:49:29,915] Trial 8 finished with value: 0.7010783451973885 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'leaf_size': 29}. Best is trial 7 with value: 0.7889007264172183.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.39 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.57 | R2: 0.54
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.74 | R2: 0.79
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.07 | R2: 0.70

[I 2025-07-11 16:49:29,977] Trial 9 finished with value: 0.7889007264172183 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 26}. Best is trial 7 with value: 0.7889007264172183.
[I 2025-07-11 16:49:30,043] Trial 10 finished with value: 0.6811195498485286 and parameters: {'n_neighbors': 5, 'weights': 'uniform', 'leaf_size': 40}. Best is trial 7 with value: 0.7889007264172183.
[I 2025-07-11 16:49:30,107] Trial 11 finished with value: 0.7889007264172183 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 17}. Best is trial 7 with value: 0.7889007264172183.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.74 | R2: 0.79
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.14 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.74 | R2: 0.79
Fold 1

[I 2025-07-11 16:49:30,179] Trial 12 finished with value: 0.7485936194968826 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'leaf_size': 30}. Best is trial 7 with value: 0.7889007264172183.
[I 2025-07-11 16:49:30,247] Trial 13 finished with value: 0.7889007264172183 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 19}. Best is trial 7 with value: 0.7889007264172183.
[I 2025-07-11 16:49:30,312] Trial 14 finished with value: 0.7150711723652357 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'leaf_size': 30}. Best is trial 7 with value: 0.7889007264172183.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.90 | R2: 0.75
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.74 | R2: 0.79
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.02 | R2: 0.72
Fold 1

[I 2025-07-11 16:49:30,383] Trial 15 finished with value: 0.6018107905845962 and parameters: {'n_neighbors': 11, 'weights': 'distance', 'leaf_size': 40}. Best is trial 7 with value: 0.7889007264172183.
[I 2025-07-11 16:49:30,452] Trial 16 finished with value: 0.7889007264172183 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 28}. Best is trial 7 with value: 0.7889007264172183.
[I 2025-07-11 16:49:30,518] Trial 17 finished with value: 0.7485936194968826 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'leaf_size': 14}. Best is trial 7 with value: 0.7889007264172183.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.39 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.74 | R2: 0.79
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.90 | R2: 0.75
Fold 1

[I 2025-07-11 16:49:30,589] Trial 18 finished with value: 0.46215864894572967 and parameters: {'n_neighbors': 10, 'weights': 'uniform', 'leaf_size': 33}. Best is trial 7 with value: 0.7889007264172183.
[I 2025-07-11 16:49:30,657] Trial 19 finished with value: 0.7792909633973581 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'leaf_size': 22}. Best is trial 7 with value: 0.7889007264172183.
[I 2025-07-11 16:49:30,725] Trial 20 finished with value: 0.7010783451973885 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'leaf_size': 36}. Best is trial 7 with value: 0.7889007264172183.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.77 | R2: 0.46
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.78 | R2: 0.78
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.07 | R2: 0.70
Fold 1

[I 2025-07-11 16:49:30,798] Trial 21 finished with value: 0.7889007264172183 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 19}. Best is trial 7 with value: 0.7889007264172183.
[I 2025-07-11 16:49:30,867] Trial 22 finished with value: 0.7792909633973581 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'leaf_size': 16}. Best is trial 7 with value: 0.7889007264172183.
[I 2025-07-11 16:49:30,936] Trial 23 finished with value: 0.7889007264172183 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 21}. Best is trial 7 with value: 0.7889007264172183.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.74 | R2: 0.79
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.78 | R2: 0.78
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.74 | R2: 0.79
Fold 1

[I 2025-07-11 16:49:31,007] Trial 24 finished with value: 0.7150711723652357 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'leaf_size': 14}. Best is trial 7 with value: 0.7889007264172183.
[I 2025-07-11 16:49:31,008] A new study created in memory with name: no-name-801a06e7-43d9-4c4b-8542-6a2ac7487305
[I 2025-07-11 16:49:31,085] Trial 0 finished with value: 0.20508620432049451 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 0 with value: 0.20508620432049451.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.02 | R2: 0.72

✅ KNN - Mejor R2: 0.79
📋 Parámetros: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 34}

Buscando mejores hiperparámetros para LR...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.37 | R2: 0.21
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:49:31,165] Trial 1 finished with value: 0.20508620432049451 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 0 with value: 0.20508620432049451.
[I 2025-07-11 16:49:31,254] Trial 2 finished with value: 0.20508620432049451 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 0 with value: 0.20508620432049451.
[I 2025-07-11 16:49:31,338] Trial 3 finished with value: 0.20508620432049451 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 0 with value: 0.20508620432049451.

Running time: 0.1 sec
OOF RMSE: 3.37 | R2: 0.21
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.37 | R2: 0.21
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.37 | R2: 0.21
Fold 1
Fold 2

[I 2025-07-11 16:49:31,417] Trial 4 finished with value: 0.21056516902481348 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 4 with value: 0.21056516902481348.
[I 2025-07-11 16:49:31,476] Trial 5 finished with value: 0.209802111682735 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 4 with value: 0.21056516902481348.
[I 2025-07-11 16:49:31,534] Trial 6 finished with value: 0.21056516902481348 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 4 with value: 0.21056516902481348.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.36 | R2: 0.21
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.36 | R2: 0.21
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.36 | R2: 0.21
Fold 1
Fold 2
Fold 3

[I 2025-07-11 16:49:31,614] Trial 7 finished with value: 0.20508620432049451 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 4 with value: 0.21056516902481348.
[I 2025-07-11 16:49:31,703] Trial 8 finished with value: 0.20508620431853974 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 4 with value: 0.21056516902481348.
[I 2025-07-11 16:49:31,779] Trial 9 finished with value: 0.21056516902481348 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 4 with value: 0.21056516902481348.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.37 | R2: 0.21
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.37 | R2: 0.21
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.36 | R2: 0.21

[I 2025-07-11 16:49:31,858] Trial 10 finished with value: 0.209802111682735 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 4 with value: 0.21056516902481348.
[I 2025-07-11 16:49:31,924] Trial 11 finished with value: 0.21056516902481348 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 4 with value: 0.21056516902481348.
[I 2025-07-11 16:49:31,983] Trial 12 finished with value: 0.21056516902481348 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 4 with value: 0.21056516902481348.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.36 | R2: 0.21
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.36 | R2: 0.21
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.36 | R2: 0.21

[I 2025-07-11 16:49:32,046] Trial 13 finished with value: 0.21056516902481348 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 4 with value: 0.21056516902481348.
[I 2025-07-11 16:49:32,107] Trial 14 finished with value: 0.209802111682735 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 4 with value: 0.21056516902481348.
[I 2025-07-11 16:49:32,166] Trial 15 finished with value: 0.21056516902481348 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 4 with value: 0.21056516902481348.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.36 | R2: 0.21
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.36 | R2: 0.21
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.36 | R2: 0.21
Fold 1
Fold 2

[I 2025-07-11 16:49:32,228] Trial 16 finished with value: 0.21056516902481348 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 4 with value: 0.21056516902481348.
[I 2025-07-11 16:49:32,288] Trial 17 finished with value: 0.21056516902481348 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 4 with value: 0.21056516902481348.
[I 2025-07-11 16:49:32,347] Trial 18 finished with value: 0.209802111682735 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 4 with value: 0.21056516902481348.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.36 | R2: 0.21
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.36 | R2: 0.21
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.36 | R2: 0.21
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:49:32,407] Trial 19 finished with value: 0.21056516902481348 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 4 with value: 0.21056516902481348.
[I 2025-07-11 16:49:32,468] Trial 20 finished with value: 0.21056516902481348 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 4 with value: 0.21056516902481348.
[I 2025-07-11 16:49:32,527] Trial 21 finished with value: 0.21056516902481348 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 4 with value: 0.21056516902481348.
[I 2025-07-11 16:49:32,587] Trial 22 finished with value: 0.21056516902481348 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 4 with value: 0.21056516902481348.

Running time: 0.1 sec
OOF RMSE: 3.36 | R2: 0.21
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.36 | R2: 0.21
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.36 | R2: 0.21
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.36 | R2: 0.21
Fold 1
Fold 2

[I 2025-07-11 16:49:32,649] Trial 23 finished with value: 0.21056516902481348 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 4 with value: 0.21056516902481348.
[I 2025-07-11 16:49:32,713] Trial 24 finished with value: 0.21056516902481348 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 4 with value: 0.21056516902481348.
[I 2025-07-11 16:49:32,714] A new study created in memory with name: no-name-d8fe1d79-bdcb-424c-9196-9bb08ce8c0fd

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.36 | R2: 0.21
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.36 | R2: 0.21

✅ LR - Mejor R2: 0.21
📋 Parámetros: {'fit_intercept': False, 'positive': True}

Buscando mejores hiperparámetros para RF...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:49:43,554] Trial 0 finished with value: 0.7817380240819898 and parameters: {'n_estimators': 500, 'max_depth': 13, 'min_samples_split': 5, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 0 with value: 0.7817380240819898.

Running time: 10.8 sec
OOF RMSE: 1.77 | R2: 0.78
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:49:55,259] Trial 1 finished with value: 0.709643002630959 and parameters: {'n_estimators': 500, 'max_depth': 7, 'min_samples_split': 7, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 0 with value: 0.7817380240819898.

Running time: 11.7 sec
OOF RMSE: 2.04 | R2: 0.71
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:50:03,115] Trial 2 finished with value: 0.6435631370907056 and parameters: {'n_estimators': 500, 'max_depth': 7, 'min_samples_split': 5, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 0 with value: 0.7817380240819898.

Running time: 7.9 sec
OOF RMSE: 2.26 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:50:04,999] Trial 3 finished with value: 0.7311178482236884 and parameters: {'n_estimators': 100, 'max_depth': 12, 'min_samples_split': 4, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 0 with value: 0.7817380240819898.

Running time: 1.9 sec
OOF RMSE: 1.96 | R2: 0.73
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:50:18,783] Trial 4 finished with value: 0.6360349005250086 and parameters: {'n_estimators': 500, 'max_depth': 9, 'min_samples_split': 7, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 0 with value: 0.7817380240819898.

Running time: 13.8 sec
OOF RMSE: 2.28 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:50:30,245] Trial 5 finished with value: 0.6645292568915528 and parameters: {'n_estimators': 500, 'max_depth': 7, 'min_samples_split': 2, 'min_samples_leaf': 4, 'bootstrap': False}. Best is trial 0 with value: 0.7817380240819898.

Running time: 11.5 sec
OOF RMSE: 2.19 | R2: 0.66
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:50:33,204] Trial 6 finished with value: 0.7145004108138866 and parameters: {'n_estimators': 100, 'max_depth': 11, 'min_samples_split': 3, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 0 with value: 0.7817380240819898.

Running time: 3.0 sec
OOF RMSE: 2.02 | R2: 0.71
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:50:34,835] Trial 7 finished with value: 0.5592152607553501 and parameters: {'n_estimators': 100, 'max_depth': 14, 'min_samples_split': 6, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 0 with value: 0.7817380240819898.

Running time: 1.6 sec
OOF RMSE: 2.51 | R2: 0.56
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:50:44,341] Trial 8 finished with value: 0.723735478798765 and parameters: {'n_estimators': 500, 'max_depth': 13, 'min_samples_split': 5, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 0 with value: 0.7817380240819898.

Running time: 9.5 sec
OOF RMSE: 1.99 | R2: 0.72
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:50:54,153] Trial 9 finished with value: 0.7628237344821116 and parameters: {'n_estimators': 500, 'max_depth': 13, 'min_samples_split': 7, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 0 with value: 0.7817380240819898.

Running time: 9.8 sec
OOF RMSE: 1.84 | R2: 0.76
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:50:59,901] Trial 10 finished with value: 0.7704142159502518 and parameters: {'n_estimators': 300, 'max_depth': 10, 'min_samples_split': 10, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 0 with value: 0.7817380240819898.

Running time: 5.7 sec
OOF RMSE: 1.81 | R2: 0.77
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:51:05,853] Trial 11 finished with value: 0.7705505383904844 and parameters: {'n_estimators': 300, 'max_depth': 15, 'min_samples_split': 10, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 0 with value: 0.7817380240819898.

Running time: 5.9 sec
OOF RMSE: 1.81 | R2: 0.77
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:51:11,837] Trial 12 finished with value: 0.7705505383904844 and parameters: {'n_estimators': 300, 'max_depth': 15, 'min_samples_split': 10, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 0 with value: 0.7817380240819898.

Running time: 6.0 sec
OOF RMSE: 1.81 | R2: 0.77
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:51:17,886] Trial 13 finished with value: 0.7719820383310944 and parameters: {'n_estimators': 300, 'max_depth': 15, 'min_samples_split': 9, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 0 with value: 0.7817380240819898.

Running time: 6.0 sec
OOF RMSE: 1.81 | R2: 0.77
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:51:23,749] Trial 14 finished with value: 0.7598119721588963 and parameters: {'n_estimators': 300, 'max_depth': 13, 'min_samples_split': 8, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 0 with value: 0.7817380240819898.

Running time: 5.9 sec
OOF RMSE: 1.85 | R2: 0.76
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:51:27,770] Trial 15 finished with value: 0.7641577909380797 and parameters: {'n_estimators': 300, 'max_depth': 5, 'min_samples_split': 8, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 0 with value: 0.7817380240819898.

Running time: 4.0 sec
OOF RMSE: 1.84 | R2: 0.76
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:51:33,594] Trial 16 finished with value: 0.7582573429016096 and parameters: {'n_estimators': 300, 'max_depth': 15, 'min_samples_split': 9, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 0 with value: 0.7817380240819898.

Running time: 5.8 sec
OOF RMSE: 1.86 | R2: 0.76
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:51:39,887] Trial 17 finished with value: 0.7801090338401799 and parameters: {'n_estimators': 300, 'max_depth': 11, 'min_samples_split': 5, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 0 with value: 0.7817380240819898.

Running time: 6.3 sec
OOF RMSE: 1.77 | R2: 0.78
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:51:55,445] Trial 18 finished with value: 0.5957389753737206 and parameters: {'n_estimators': 500, 'max_depth': 11, 'min_samples_split': 4, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 0 with value: 0.7817380240819898.

Running time: 15.6 sec
OOF RMSE: 2.40 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:51:57,392] Trial 19 finished with value: 0.7829409353104928 and parameters: {'n_estimators': 100, 'max_depth': 9, 'min_samples_split': 5, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 19 with value: 0.7829409353104928.

Running time: 1.9 sec
OOF RMSE: 1.76 | R2: 0.78
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:51:59,101] Trial 20 finished with value: 0.650909609302541 and parameters: {'n_estimators': 100, 'max_depth': 9, 'min_samples_split': 2, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 19 with value: 0.7829409353104928.

Running time: 1.7 sec
OOF RMSE: 2.23 | R2: 0.65
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:52:01,037] Trial 21 finished with value: 0.7829409353104928 and parameters: {'n_estimators': 100, 'max_depth': 9, 'min_samples_split': 5, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 19 with value: 0.7829409353104928.

Running time: 1.9 sec
OOF RMSE: 1.76 | R2: 0.78
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:52:03,013] Trial 22 finished with value: 0.7805346183825409 and parameters: {'n_estimators': 100, 'max_depth': 9, 'min_samples_split': 4, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 19 with value: 0.7829409353104928.

Running time: 2.0 sec
OOF RMSE: 1.77 | R2: 0.78
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:52:04,802] Trial 23 finished with value: 0.7674212757843389 and parameters: {'n_estimators': 100, 'max_depth': 8, 'min_samples_split': 6, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 19 with value: 0.7829409353104928.

Running time: 1.8 sec
OOF RMSE: 1.82 | R2: 0.77
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:52:06,916] Trial 24 finished with value: 0.783606369853559 and parameters: {'n_estimators': 100, 'max_depth': 10, 'min_samples_split': 3, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 24 with value: 0.783606369853559.
[I 2025-07-11 16:52:06,917] A new study created in memory with name: no-name-971a5248-b6b1-4cee-88d7-4722184872d4

Running time: 2.1 sec
OOF RMSE: 1.76 | R2: 0.78

✅ RF - Mejor R2: 0.78
📋 Parámetros: {'n_estimators': 100, 'max_depth': 10, 'min_samples_split': 3, 'min_samples_leaf': 1, 'bootstrap': True}

Buscando mejores hiperparámetros para CAT...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:52:09,003] Trial 0 finished with value: 0.809451341296095 and parameters: {'iterations': 500, 'learning_rate': 0.08503794443091717, 'depth': 5, 'l2_leaf_reg': 3.2141045481833688}. Best is trial 0 with value: 0.809451341296095.

Running time: 2.1 sec
OOF RMSE: 1.65 | R2: 0.81
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:52:13,433] Trial 1 finished with value: 0.8156371157135378 and parameters: {'iterations': 1000, 'learning_rate': 0.012871392440404021, 'depth': 5, 'l2_leaf_reg': 3.1160453140442455}. Best is trial 1 with value: 0.8156371157135378.

Running time: 4.4 sec
OOF RMSE: 1.62 | R2: 0.82
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:52:22,651] Trial 2 finished with value: 0.8084250517411221 and parameters: {'iterations': 2000, 'learning_rate': 0.03517395371441399, 'depth': 5, 'l2_leaf_reg': 2.8564168964976564}. Best is trial 1 with value: 0.8156371157135378.

Running time: 9.2 sec
OOF RMSE: 1.66 | R2: 0.81
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:55:08,442] Trial 3 finished with value: 0.809277063277392 and parameters: {'iterations': 2000, 'learning_rate': 0.04674475101564263, 'depth': 9, 'l2_leaf_reg': 2.000870655481962}. Best is trial 1 with value: 0.8156371157135378.

Running time: 165.8 sec
OOF RMSE: 1.65 | R2: 0.81
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:55:10,608] Trial 4 finished with value: 0.8001876562663843 and parameters: {'iterations': 500, 'learning_rate': 0.062192520080697804, 'depth': 5, 'l2_leaf_reg': 1.8170773838613385}. Best is trial 1 with value: 0.8156371157135378.

Running time: 2.2 sec
OOF RMSE: 1.69 | R2: 0.80
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:55:16,439] Trial 5 finished with value: 0.7844330614025369 and parameters: {'iterations': 2000, 'learning_rate': 0.09615872403932897, 'depth': 4, 'l2_leaf_reg': 6.491286440136083}. Best is trial 1 with value: 0.8156371157135378.

Running time: 5.8 sec
OOF RMSE: 1.76 | R2: 0.78
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:55:18,719] Trial 6 finished with value: 0.8138351877555363 and parameters: {'iterations': 500, 'learning_rate': 0.02956786421343621, 'depth': 5, 'l2_leaf_reg': 1.205046236435901}. Best is trial 1 with value: 0.8156371157135378.

Running time: 2.3 sec
OOF RMSE: 1.63 | R2: 0.81
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:55:32,950] Trial 7 finished with value: 0.8103251108531033 and parameters: {'iterations': 1000, 'learning_rate': 0.010143722542571025, 'depth': 7, 'l2_leaf_reg': 1.9144808538304061}. Best is trial 1 with value: 0.8156371157135378.

Running time: 14.2 sec
OOF RMSE: 1.65 | R2: 0.81
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:56:00,427] Trial 8 finished with value: 0.7934277447362883 and parameters: {'iterations': 2000, 'learning_rate': 0.09312702729827632, 'depth': 7, 'l2_leaf_reg': 4.579034571623182}. Best is trial 1 with value: 0.8156371157135378.

Running time: 27.5 sec
OOF RMSE: 1.72 | R2: 0.79
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:56:03,659] Trial 9 finished with value: 0.8056730714846311 and parameters: {'iterations': 500, 'learning_rate': 0.03490088058778943, 'depth': 6, 'l2_leaf_reg': 7.927035734177964}. Best is trial 1 with value: 0.8156371157135378.

Running time: 3.2 sec
OOF RMSE: 1.67 | R2: 0.81
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:58:25,589] Trial 10 finished with value: 0.7681302477316729 and parameters: {'iterations': 1000, 'learning_rate': 0.010018734944450635, 'depth': 10, 'l2_leaf_reg': 9.908663170893625}. Best is trial 1 with value: 0.8156371157135378.

Running time: 141.9 sec
OOF RMSE: 1.82 | R2: 0.77
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:58:28,483] Trial 11 finished with value: 0.8047675355013044 and parameters: {'iterations': 1000, 'learning_rate': 0.020146087238917833, 'depth': 4, 'l2_leaf_reg': 1.0283235410158742}. Best is trial 1 with value: 0.8156371157135378.

Running time: 2.9 sec
OOF RMSE: 1.67 | R2: 0.80
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:58:31,984] Trial 12 finished with value: 0.8076419418163392 and parameters: {'iterations': 500, 'learning_rate': 0.02163070420949696, 'depth': 6, 'l2_leaf_reg': 4.276444315293938}. Best is trial 1 with value: 0.8156371157135378.

Running time: 3.5 sec
OOF RMSE: 1.66 | R2: 0.81
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:58:38,992] Trial 13 finished with value: 0.8107784351209134 and parameters: {'iterations': 1000, 'learning_rate': 0.019054648604465107, 'depth': 6, 'l2_leaf_reg': 3.6838948146375565}. Best is trial 1 with value: 0.8156371157135378.

Running time: 7.0 sec
OOF RMSE: 1.64 | R2: 0.81
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:59:15,388] Trial 14 finished with value: 0.8000798568815789 and parameters: {'iterations': 1000, 'learning_rate': 0.014716190708968058, 'depth': 8, 'l2_leaf_reg': 6.116621010148246}. Best is trial 1 with value: 0.8156371157135378.

Running time: 36.4 sec
OOF RMSE: 1.69 | R2: 0.80
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:59:16,976] Trial 15 finished with value: 0.7951145064944473 and parameters: {'iterations': 500, 'learning_rate': 0.026717931167141818, 'depth': 4, 'l2_leaf_reg': 5.1512449407098355}. Best is trial 1 with value: 0.8156371157135378.

Running time: 1.6 sec
OOF RMSE: 1.71 | R2: 0.80
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:59:21,168] Trial 16 finished with value: 0.8118511941543467 and parameters: {'iterations': 1000, 'learning_rate': 0.014491477730687338, 'depth': 5, 'l2_leaf_reg': 2.7906417311959557}. Best is trial 1 with value: 0.8156371157135378.

Running time: 4.2 sec
OOF RMSE: 1.64 | R2: 0.81
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:59:39,761] Trial 17 finished with value: 0.8208954506904806 and parameters: {'iterations': 500, 'learning_rate': 0.05271300176975567, 'depth': 8, 'l2_leaf_reg': 1.17791064424655}. Best is trial 17 with value: 0.8208954506904806.

Running time: 18.6 sec
OOF RMSE: 1.60 | R2: 0.82
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:00:16,600] Trial 18 finished with value: 0.8126911146076634 and parameters: {'iterations': 1000, 'learning_rate': 0.050618874018832714, 'depth': 8, 'l2_leaf_reg': 2.3846606522714424}. Best is trial 17 with value: 0.8208954506904806.

Running time: 36.8 sec
OOF RMSE: 1.64 | R2: 0.81
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:00:35,347] Trial 19 finished with value: 0.7974644411780099 and parameters: {'iterations': 500, 'learning_rate': 0.06381432671755352, 'depth': 8, 'l2_leaf_reg': 3.742049838282174}. Best is trial 17 with value: 0.8208954506904806.

Running time: 18.7 sec
OOF RMSE: 1.70 | R2: 0.80
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:01:48,489] Trial 20 finished with value: 0.7983470070596423 and parameters: {'iterations': 500, 'learning_rate': 0.04317419842778337, 'depth': 10, 'l2_leaf_reg': 6.683582707916139}. Best is trial 17 with value: 0.8208954506904806.

Running time: 73.1 sec
OOF RMSE: 1.70 | R2: 0.80
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:02:29,912] Trial 21 finished with value: 0.8003202622716576 and parameters: {'iterations': 500, 'learning_rate': 0.028548994441566746, 'depth': 9, 'l2_leaf_reg': 1.019818527370578}. Best is trial 17 with value: 0.8208954506904806.
[I 2025-07-11 17:02:29,913] A new study created in memory with name: no-name-b35908bf-1f74-4115-9953-8c784decf1e4
[I 2025-07-11 17:02:30,011] Trial 0 finished with value: 0.17743099108041327 and parameters: {'alpha': 0.2541600761593004, 'l1_ratio': 0.05727550449765073}. Best is trial 0 with value: 0.17743099108041327.
[I 2025-07-11 17:02:30,095] Trial 1 finished with value: 0.18413445081176016 and parameters: {'alpha': 0.26462907623278953, 'l1_ratio': 0.23168010405081563}. Best is trial 1 with value: 0.18413445081176016.

Running time: 41.4 sec
OOF RMSE: 1.69 | R2: 0.80

✅ CAT - Mejor R2: 0.82
📋 Parámetros: {'iterations': 500, 'learning_rate': 0.05271300176975567, 'depth': 8, 'l2_leaf_reg': 1.17791064424655}

Buscando mejores hiperparámetros para EN...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.43 | R2: 0.18
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.42 | R2: 0.18
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.838e+02, tolerance: 3.043e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.424e+02, tolerance: 2.664e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.231e+02, tolerance: 2.195e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.769e+02, tolerance: 2.302e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.272e+02, tolerance: 2.844e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 17:02:30,225] Trial 2 finished with value: 0.05274042944464563 and parameters: {'alpha': 0.0009044956932287488, 'l1_ratio': 0.7304879018296011}. Best is trial 1 with value: 0.18413445081176016.
[I 2025-07-11 17:02:30,317] Trial 3 finished with value: 0.00517035643570618 and parameters: {'alpha': 2.9177926521635915, 'l1_ratio': 0.2744104380637422}. Best is trial 1 with value: 0.18413445081176016.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.68 | R2: 0.05
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.77 | R2: 0.01
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.080e+02, tolerance: 3.043e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.369e+02, tolerance: 2.664e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.164e+02, tolerance: 2.195e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.074e+02, tolerance: 2.302e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.341e+02, tolerance: 2.844e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 17:02:30,457] Trial 4 finished with value: 0.05601225269036425 and parameters: {'alpha': 0.0003136603103380688, 'l1_ratio': 0.10332720380329108}. Best is trial 1 with value: 0.18413445081176016.
[I 2025-07-11 17:02:30,541] Trial 5 finished with value: -0.0003636740809507266 and parameters: {'alpha': 2.035397925785627, 'l1_ratio': 0.7880429129397899}. Best is trial 1 with value: 0.18413445081176016.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.67 | R2: 0.06
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.78 | R2: -0.00
Fold 1

[I 2025-07-11 17:02:30,627] Trial 6 finished with value: 0.019423151894242263 and parameters: {'alpha': 0.759619220511948, 'l1_ratio': 0.7620930067202089}. Best is trial 1 with value: 0.18413445081176016.
[I 2025-07-11 17:02:30,711] Trial 7 finished with value: 0.0852511520280459 and parameters: {'alpha': 0.789281917516462, 'l1_ratio': 0.34306508660486057}. Best is trial 1 with value: 0.18413445081176016.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.74 | R2: 0.02
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.62 | R2: 0.09
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 17:02:30,797] Trial 8 finished with value: 0.10567115162662766 and parameters: {'alpha': 0.36186802265008616, 'l1_ratio': 0.7258178153596301}. Best is trial 1 with value: 0.18413445081176016.
[I 2025-07-11 17:02:30,886] Trial 9 finished with value: 0.005856926244224403 and parameters: {'alpha': 2.188607164207107, 'l1_ratio': 0.5510662797213045}. Best is trial 1 with value: 0.18413445081176016.

Fold 5
Running time: 0.1 sec
OOF RMSE: 3.58 | R2: 0.11
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.77 | R2: 0.01
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.494e+01, tolerance: 3.043e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.185e+00, tolerance: 2.664e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.216e+01, tolerance: 2.195e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.352e+00, tolerance: 2.302e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.785e+01, tolerance: 2.844e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 17:02:31,004] Trial 10 finished with value: 0.014388020509036425 and parameters: {'alpha': 0.007113301386937835, 'l1_ratio': 0.9869255489828384}. Best is trial 1 with value: 0.18413445081176016.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.087e+02, tolerance: 3.043e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.713e+02, tolerance: 2.664e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.210e+02, tolerance: 2.195e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.304e+02, tolerance: 2.302e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.084e+02, tolerance: 2.844e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 17:02:31,144] Trial 11 finished with value: 0.134009148053029 and parameters: {'alpha': 0.07090537629381324, 'l1_ratio': 0.007503099146375189}. Best is trial 1 with value: 0.18413445081176016.

Fold 5
Running time: 0.1 sec
OOF RMSE: 3.75 | R2: 0.01
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.52 | R2: 0.13
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.913e-01, tolerance: 3.043e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.234e-01, tolerance: 2.664e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 17:02:31,287] Trial 12 finished with value: 0.12100617859495788 and parameters: {'alpha': 0.04386475963347743, 'l1_ratio': 0.22969058919195567}. Best is trial 1 with value: 0.18413445081176016.
[I 2025-07-11 17:02:31,385] Trial 13 finished with value: 0.185185225032251 and parameters: {'alpha': 0.13897820186205936, 'l1_ratio': 0.45100352922882336}. Best is trial 13 with value: 0.185185225032251.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.55 | R2: 0.12
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.41 | R2: 0.19
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.725e+01, tolerance: 3.043e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.736e+02, tolerance: 2.664e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.979e+01, tolerance: 2.195e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.713e+01, tolerance: 2.302e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.000e+02, tolerance: 2.844e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 17:02:31,517] Trial 14 finished with value: 0.06668100936763788 and parameters: {'alpha': 0.007758732370728092, 'l1_ratio': 0.402226711718279}. Best is trial 13 with value: 0.185185225032251.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.380e+01, tolerance: 3.043e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.228e+01, tolerance: 2.664e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.135e+01, tolerance: 2.195e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.795e+01, tolerance: 2.302e-01
  model = cd_fast.enet_coordinate_descent(

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.65 | R2: 0.07
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.132e+01, tolerance: 2.844e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 17:02:31,642] Trial 15 finished with value: 0.06141288554629787 and parameters: {'alpha': 0.008153011875444557, 'l1_ratio': 0.5380580405289999}. Best is trial 13 with value: 0.185185225032251.
[I 2025-07-11 17:02:31,758] Trial 16 finished with value: 0.17499356055078152 and parameters: {'alpha': 0.10830443503622404, 'l1_ratio': 0.4369823173560618}. Best is trial 13 with value: 0.185185225032251.

Running time: 0.1 sec
OOF RMSE: 3.66 | R2: 0.06
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.43 | R2: 0.17
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:02:31,846] Trial 17 finished with value: 0.0012863804953689995 and parameters: {'alpha': 7.356293830943438, 'l1_ratio': 0.18955801861018073}. Best is trial 13 with value: 0.185185225032251.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.880e+00, tolerance: 2.664e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 17:02:31,982] Trial 18 finished with value: 0.08130679935129648 and parameters: {'alpha': 0.021094156133577634, 'l1_ratio': 0.5975949604047787}. Best is trial 13 with value: 0.185185225032251.

Running time: 0.1 sec
OOF RMSE: 3.78 | R2: 0.00
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.62 | R2: 0.08
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 17:02:32,082] Trial 19 finished with value: 0.18499832171412756 and parameters: {'alpha': 0.2661922388654534, 'l1_ratio': 0.29292369001843116}. Best is trial 13 with value: 0.185185225032251.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.896e+02, tolerance: 3.043e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.141e+02, tolerance: 2.664e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.857e+02, tolerance: 2.195e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.619e+02, tolerance: 2.302e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.576e+02, tolerance: 2.844e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 17:02:32,242] Trial 20 finished with value: 0.05930255947033558 and parameters: {'alpha': 0.002914547869211546, 'l1_ratio': 0.3358183967554104}. Best is trial 13 with value: 0.185185225032251.

Fold 5
Running time: 0.1 sec
OOF RMSE: 3.41 | R2: 0.18
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 3.67 | R2: 0.06
Fold 1

[I 2025-07-11 17:02:32,371] Trial 21 finished with value: 0.17542832179011425 and parameters: {'alpha': 0.18650671752270645, 'l1_ratio': 0.15834595456085987}. Best is trial 13 with value: 0.185185225032251.
[I 2025-07-11 17:02:32,468] Trial 22 finished with value: 0.0762015945595802 and parameters: {'alpha': 0.6632430410533197, 'l1_ratio': 0.45084892321286624}. Best is trial 13 with value: 0.185185225032251.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.43 | R2: 0.18
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.63 | R2: 0.08
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.845e-01, tolerance: 3.043e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.517e+00, tolerance: 2.664e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 17:02:32,608] Trial 23 finished with value: 0.09492055066626714 and parameters: {'alpha': 0.025729396456597563, 'l1_ratio': 0.31555881943466413}. Best is trial 13 with value: 0.185185225032251.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.60 | R2: 0.09
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 17:02:32,727] Trial 24 finished with value: 0.19433741163378648 and parameters: {'alpha': 0.11724858580646791, 'l1_ratio': 0.6392112277468219}. Best is trial 24 with value: 0.19433741163378648.
[I 2025-07-11 17:02:32,728] A new study created in memory with name: no-name-727e9f36-d6d3-4dbb-b5b1-a2eee3a3d5a2

Fold 5
Running time: 0.1 sec
OOF RMSE: 3.39 | R2: 0.19

✅ EN - Mejor R2: 0.19
📋 Parámetros: {'alpha': 0.11724858580646791, 'l1_ratio': 0.6392112277468219}

🔍 Optimizando en C2X_rhow_3x3_depth_lt_1...
Buscando mejores hiperparámetros para XGB...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:02:39,201] Trial 0 finished with value: 0.41451392133145426 and parameters: {'n_estimators': 1000, 'learning_rate': 0.008322960806969546, 'max_depth': 6, 'min_child_weight': 1, 'subsample': 0.611557753948735, 'colsample_bytree': 0.6277013471973537}. Best is trial 0 with value: 0.41451392133145426.

Running time: 6.5 sec
OOF RMSE: 2.65 | R2: 0.41
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:02:53,752] Trial 1 finished with value: 0.42913187868897495 and parameters: {'n_estimators': 2000, 'learning_rate': 0.009792167888686422, 'max_depth': 8, 'min_child_weight': 4, 'subsample': 0.6733585473362264, 'colsample_bytree': 0.9523883664154817}. Best is trial 1 with value: 0.42913187868897495.

Running time: 14.5 sec
OOF RMSE: 2.62 | R2: 0.43
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:02:56,945] Trial 2 finished with value: 0.3737109657725589 and parameters: {'n_estimators': 500, 'learning_rate': 0.09011201106018235, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.7695463585823198, 'colsample_bytree': 0.7418303110985478}. Best is trial 1 with value: 0.42913187868897495.

Running time: 3.2 sec
OOF RMSE: 2.74 | R2: 0.37
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:03:09,255] Trial 3 finished with value: 0.2837844551963601 and parameters: {'n_estimators': 2000, 'learning_rate': 0.006997171950214244, 'max_depth': 5, 'min_child_weight': 1, 'subsample': 0.9783244724168065, 'colsample_bytree': 0.8375285795271703}. Best is trial 1 with value: 0.42913187868897495.

Running time: 12.3 sec
OOF RMSE: 2.93 | R2: 0.28
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:03:12,527] Trial 4 finished with value: 0.3888858436263867 and parameters: {'n_estimators': 500, 'learning_rate': 0.017718336209912748, 'max_depth': 6, 'min_child_weight': 1, 'subsample': 0.7124432952123256, 'colsample_bytree': 0.7335272225582716}. Best is trial 1 with value: 0.42913187868897495.

Running time: 3.3 sec
OOF RMSE: 2.71 | R2: 0.39
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:03:20,185] Trial 5 finished with value: 0.4043190817069948 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01410051980715059, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.6927790414206598, 'colsample_bytree': 0.8365261318837891}. Best is trial 1 with value: 0.42913187868897495.

Running time: 7.6 sec
OOF RMSE: 2.68 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:03:23,915] Trial 6 finished with value: 0.38395886269227475 and parameters: {'n_estimators': 500, 'learning_rate': 0.0071676577399601244, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.880296815918312, 'colsample_bytree': 0.6515285728033726}. Best is trial 1 with value: 0.42913187868897495.

Running time: 3.7 sec
OOF RMSE: 2.72 | R2: 0.38
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:03:38,895] Trial 7 finished with value: 0.3451609311353697 and parameters: {'n_estimators': 2000, 'learning_rate': 0.019492465521474465, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.8715330889841253, 'colsample_bytree': 0.9700907437519068}. Best is trial 1 with value: 0.42913187868897495.

Running time: 15.0 sec
OOF RMSE: 2.81 | R2: 0.35
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:03:41,177] Trial 8 finished with value: 0.4119403430404832 and parameters: {'n_estimators': 500, 'learning_rate': 0.08246573702340843, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.7573905179127806, 'colsample_bytree': 0.7006387401723175}. Best is trial 1 with value: 0.42913187868897495.

Running time: 2.3 sec
OOF RMSE: 2.66 | R2: 0.41
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:03:51,718] Trial 9 finished with value: 0.3719138349746418 and parameters: {'n_estimators': 2000, 'learning_rate': 0.09552183249524746, 'max_depth': 8, 'min_child_weight': 3, 'subsample': 0.8327638233926872, 'colsample_bytree': 0.9079248396054085}. Best is trial 1 with value: 0.42913187868897495.

Running time: 10.5 sec
OOF RMSE: 2.75 | R2: 0.37
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:04:05,141] Trial 10 finished with value: 0.45809434053977327 and parameters: {'n_estimators': 2000, 'learning_rate': 0.04297375526724459, 'max_depth': 8, 'min_child_weight': 4, 'subsample': 0.6114711569881693, 'colsample_bytree': 0.9933355222457546}. Best is trial 10 with value: 0.45809434053977327.

Running time: 13.4 sec
OOF RMSE: 2.55 | R2: 0.46
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:04:18,929] Trial 11 finished with value: 0.44602560861893714 and parameters: {'n_estimators': 2000, 'learning_rate': 0.035107333640942935, 'max_depth': 8, 'min_child_weight': 4, 'subsample': 0.6192764251578472, 'colsample_bytree': 0.9953212102349055}. Best is trial 10 with value: 0.45809434053977327.

Running time: 13.8 sec
OOF RMSE: 2.58 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:04:32,153] Trial 12 finished with value: 0.43883530518532554 and parameters: {'n_estimators': 2000, 'learning_rate': 0.044765536875577217, 'max_depth': 8, 'min_child_weight': 4, 'subsample': 0.6012515449131289, 'colsample_bytree': 0.9847350899315929}. Best is trial 10 with value: 0.45809434053977327.

Running time: 13.2 sec
OOF RMSE: 2.60 | R2: 0.44
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:04:45,766] Trial 13 finished with value: 0.43231934923252313 and parameters: {'n_estimators': 2000, 'learning_rate': 0.036440407756083856, 'max_depth': 8, 'min_child_weight': 3, 'subsample': 0.6421949948559015, 'colsample_bytree': 0.9011443296316477}. Best is trial 10 with value: 0.45809434053977327.

Running time: 13.6 sec
OOF RMSE: 2.61 | R2: 0.43
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:04:59,045] Trial 14 finished with value: 0.38349813996875504 and parameters: {'n_estimators': 2000, 'learning_rate': 0.03889351543988314, 'max_depth': 8, 'min_child_weight': 3, 'subsample': 0.720562049541755, 'colsample_bytree': 0.9994826879437854}. Best is trial 10 with value: 0.45809434053977327.

Running time: 13.3 sec
OOF RMSE: 2.72 | R2: 0.38
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:05:11,597] Trial 15 finished with value: 0.436365019670925 and parameters: {'n_estimators': 2000, 'learning_rate': 0.028819280384545756, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.6510806098809577, 'colsample_bytree': 0.9061155377842752}. Best is trial 10 with value: 0.45809434053977327.

Running time: 12.5 sec
OOF RMSE: 2.60 | R2: 0.44
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:05:18,013] Trial 16 finished with value: 0.27958398848836163 and parameters: {'n_estimators': 1000, 'learning_rate': 0.06102416692586754, 'max_depth': 8, 'min_child_weight': 3, 'subsample': 0.9460836438906972, 'colsample_bytree': 0.8552311898113808}. Best is trial 10 with value: 0.45809434053977327.

Running time: 6.4 sec
OOF RMSE: 2.94 | R2: 0.28
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:05:29,857] Trial 17 finished with value: 0.45531590836087377 and parameters: {'n_estimators': 2000, 'learning_rate': 0.055230238985723934, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.6331846169626478, 'colsample_bytree': 0.9417558848431712}. Best is trial 10 with value: 0.45809434053977327.

Running time: 11.8 sec
OOF RMSE: 2.56 | R2: 0.46
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:05:41,114] Trial 18 finished with value: 0.4348641544192676 and parameters: {'n_estimators': 2000, 'learning_rate': 0.05609003867511441, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.7474611939476482, 'colsample_bytree': 0.9327128173029525}. Best is trial 10 with value: 0.45809434053977327.

Running time: 11.3 sec
OOF RMSE: 2.61 | R2: 0.43
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:05:48,273] Trial 19 finished with value: 0.3864455848367191 and parameters: {'n_estimators': 1000, 'learning_rate': 0.025564271796058392, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.8016288459119785, 'colsample_bytree': 0.7924551538161295}. Best is trial 10 with value: 0.45809434053977327.

Running time: 7.2 sec
OOF RMSE: 2.72 | R2: 0.39
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:05:59,165] Trial 20 finished with value: 0.4354970980694872 and parameters: {'n_estimators': 2000, 'learning_rate': 0.05693253185149682, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.6699658742599579, 'colsample_bytree': 0.875600493950265}. Best is trial 10 with value: 0.45809434053977327.

Running time: 10.9 sec
OOF RMSE: 2.60 | R2: 0.44
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:06:13,079] Trial 21 finished with value: 0.43220771848569695 and parameters: {'n_estimators': 2000, 'learning_rate': 0.0315182039388762, 'max_depth': 8, 'min_child_weight': 4, 'subsample': 0.6353393239479974, 'colsample_bytree': 0.9547347191898053}. Best is trial 10 with value: 0.45809434053977327.

Running time: 13.9 sec
OOF RMSE: 2.61 | R2: 0.43
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:06:26,346] Trial 22 finished with value: 0.4275196610383619 and parameters: {'n_estimators': 2000, 'learning_rate': 0.04681549954220224, 'max_depth': 8, 'min_child_weight': 4, 'subsample': 0.6245129867905423, 'colsample_bytree': 0.9973691641987384}. Best is trial 10 with value: 0.45809434053977327.

Running time: 13.3 sec
OOF RMSE: 2.62 | R2: 0.43
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:06:38,118] Trial 23 finished with value: 0.41753102519557084 and parameters: {'n_estimators': 2000, 'learning_rate': 0.0643454606329111, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.6840246481845671, 'colsample_bytree': 0.9257014570729563}. Best is trial 10 with value: 0.45809434053977327.

Running time: 11.8 sec
OOF RMSE: 2.65 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:06:51,921] Trial 24 finished with value: 0.4626729633693569 and parameters: {'n_estimators': 2000, 'learning_rate': 0.005073225186908113, 'max_depth': 8, 'min_child_weight': 4, 'subsample': 0.6059690230568425, 'colsample_bytree': 0.9542374874967058}. Best is trial 24 with value: 0.4626729633693569.
[I 2025-07-11 17:06:51,923] A new study created in memory with name: no-name-dbebaf76-9417-46ac-8165-89edd8f830a6

Running time: 13.8 sec
OOF RMSE: 2.54 | R2: 0.46

✅ XGB - Mejor R2: 0.46
📋 Parámetros: {'n_estimators': 2000, 'learning_rate': 0.005073225186908113, 'max_depth': 8, 'min_child_weight': 4, 'subsample': 0.6059690230568425, 'colsample_bytree': 0.9542374874967058}

Buscando mejores hiperparámetros para LBM...
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 17:06:52,738] Trial 0 finished with value: 0.3584836928449172 and parameters: {'learning_rate': 0.04078855824301994, 'num_leaves': 80, 'max_depth': 8, 'min_child_samples': 5, 'subsample': 0.6828366957226915, 'colsample_bytree': 0.9312853638280811, 'n_estimators': 1000}. Best is trial 0 with value: 0.3584836928449172.

Fold 5
Running time: 0.8 sec
OOF RMSE: 2.78 | R2: 0.36
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:06:53,443] Trial 1 finished with value: 0.3606553472317082 and parameters: {'learning_rate': 0.09288664461100649, 'num_leaves': 60, 'max_depth': 7, 'min_child_samples': 5, 'subsample': 0.6300212479090528, 'colsample_bytree': 0.7565357677249536, 'n_estimators': 1000}. Best is trial 1 with value: 0.3606553472317082.

Running time: 0.7 sec
OOF RMSE: 2.77 | R2: 0.36
Fold 1
Fold 2
Fold 3

[I 2025-07-11 17:06:53,895] Trial 2 finished with value: 0.28967452539201943 and parameters: {'learning_rate': 0.01617245575621322, 'num_leaves': 80, 'max_depth': 5, 'min_child_samples': 9, 'subsample': 0.8976910811821268, 'colsample_bytree': 0.9883202637144446, 'n_estimators': 1000}. Best is trial 1 with value: 0.3606553472317082.

Fold 4
Fold 5
Running time: 0.4 sec
OOF RMSE: 2.92 | R2: 0.29
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:06:54,736] Trial 3 finished with value: 0.31156226216490135 and parameters: {'learning_rate': 0.09051029562797072, 'num_leaves': 40, 'max_depth': 5, 'min_child_samples': 18, 'subsample': 0.8530822594382053, 'colsample_bytree': 0.8151766584842726, 'n_estimators': 2000}. Best is trial 1 with value: 0.3606553472317082.

Running time: 0.8 sec
OOF RMSE: 2.88 | R2: 0.31
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:06:55,856] Trial 4 finished with value: 0.3201229375426927 and parameters: {'learning_rate': 0.08128492329070501, 'num_leaves': 80, 'max_depth': 8, 'min_child_samples': 17, 'subsample': 0.7892945943293047, 'colsample_bytree': 0.7216047407719217, 'n_estimators': 2000}. Best is trial 1 with value: 0.3606553472317082.

Running time: 1.1 sec
OOF RMSE: 2.86 | R2: 0.32
Fold 1
Fold 2
Fold 3

[I 2025-07-11 17:06:56,218] Trial 5 finished with value: 0.4841044867464147 and parameters: {'learning_rate': 0.005849380680569026, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 7, 'subsample': 0.6122104334511537, 'colsample_bytree': 0.7554534645600801, 'n_estimators': 500}. Best is trial 5 with value: 0.4841044867464147.

Fold 4
Fold 5
Running time: 0.4 sec
OOF RMSE: 2.49 | R2: 0.48
Fold 1
Fold 2

[I 2025-07-11 17:06:56,448] Trial 6 finished with value: 0.41886373609172756 and parameters: {'learning_rate': 0.00508165853422073, 'num_leaves': 40, 'max_depth': 7, 'min_child_samples': 24, 'subsample': 0.9482341403976184, 'colsample_bytree': 0.7042921131165181, 'n_estimators': 500}. Best is trial 5 with value: 0.4841044867464147.

Fold 3
Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 2.64 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:06:57,356] Trial 7 finished with value: 0.337328843706584 and parameters: {'learning_rate': 0.034936355542932916, 'num_leaves': 20, 'max_depth': 8, 'min_child_samples': 23, 'subsample': 0.8267962012051285, 'colsample_bytree': 0.7516546428338142, 'n_estimators': 2000}. Best is trial 5 with value: 0.4841044867464147.

Running time: 0.9 sec
OOF RMSE: 2.82 | R2: 0.34
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 17:06:58,183] Trial 8 finished with value: 0.3048015185793024 and parameters: {'learning_rate': 0.013184686807357623, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 8, 'subsample': 0.7870590392207792, 'colsample_bytree': 0.7696852964742782, 'n_estimators': 2000}. Best is trial 5 with value: 0.4841044867464147.

Fold 5
Running time: 0.8 sec
OOF RMSE: 2.89 | R2: 0.30
Fold 1

[I 2025-07-11 17:06:58,442] Trial 9 finished with value: 0.4083332837173107 and parameters: {'learning_rate': 0.009596432104522322, 'num_leaves': 60, 'max_depth': 6, 'min_child_samples': 20, 'subsample': 0.7613887125376471, 'colsample_bytree': 0.9384223355930823, 'n_estimators': 500}. Best is trial 5 with value: 0.4841044867464147.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.3 sec
OOF RMSE: 2.67 | R2: 0.41
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:06:58,705] Trial 10 finished with value: 0.41569388491888637 and parameters: {'learning_rate': 0.005903760665775627, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 12, 'subsample': 0.6189396991302204, 'colsample_bytree': 0.6019898566797545, 'n_estimators': 500}. Best is trial 5 with value: 0.4841044867464147.

Running time: 0.3 sec
OOF RMSE: 2.65 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:06:58,938] Trial 11 finished with value: 0.39663953093521787 and parameters: {'learning_rate': 0.005248423794656727, 'num_leaves': 40, 'max_depth': 7, 'min_child_samples': 25, 'subsample': 0.9973971008381094, 'colsample_bytree': 0.6648678874938669, 'n_estimators': 500}. Best is trial 5 with value: 0.4841044867464147.

Running time: 0.2 sec
OOF RMSE: 2.69 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 17:06:59,254] Trial 12 finished with value: 0.3695019089328294 and parameters: {'learning_rate': 0.00855075595461465, 'num_leaves': 40, 'max_depth': 7, 'min_child_samples': 13, 'subsample': 0.9875120196747765, 'colsample_bytree': 0.8432711833767077, 'n_estimators': 500}. Best is trial 5 with value: 0.4841044867464147.

Fold 5
Running time: 0.3 sec
OOF RMSE: 2.75 | R2: 0.37
Fold 1
Fold 2
Fold 3

[I 2025-07-11 17:06:59,541] Trial 13 finished with value: 0.41674686469542677 and parameters: {'learning_rate': 0.007542185767831995, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 21, 'subsample': 0.9151459545924638, 'colsample_bytree': 0.6831330267928754, 'n_estimators': 500}. Best is trial 5 with value: 0.4841044867464147.

Fold 4
Fold 5
Running time: 0.3 sec
OOF RMSE: 2.65 | R2: 0.42
Fold 1

[I 2025-07-11 17:06:59,821] Trial 14 finished with value: 0.3497129019312003 and parameters: {'learning_rate': 0.018142883785159655, 'num_leaves': 40, 'max_depth': 6, 'min_child_samples': 14, 'subsample': 0.7084237339293424, 'colsample_bytree': 0.8538634811119347, 'n_estimators': 500}. Best is trial 5 with value: 0.4841044867464147.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.3 sec
OOF RMSE: 2.80 | R2: 0.35
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 17:07:00,121] Trial 15 finished with value: 0.3563196828774273 and parameters: {'learning_rate': 0.012250975390839542, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 10, 'subsample': 0.9340124854468713, 'colsample_bytree': 0.6428996018110249, 'n_estimators': 500}. Best is trial 5 with value: 0.4841044867464147.

Fold 5
Running time: 0.3 sec
OOF RMSE: 2.78 | R2: 0.36
Fold 1
Fold 2
Fold 3

[I 2025-07-11 17:07:00,386] Trial 16 finished with value: 0.32354455766461987 and parameters: {'learning_rate': 0.0286769116497786, 'num_leaves': 40, 'max_depth': 6, 'min_child_samples': 16, 'subsample': 0.7243983042646447, 'colsample_bytree': 0.7074907454901516, 'n_estimators': 500}. Best is trial 5 with value: 0.4841044867464147.

Fold 4
Fold 5
Running time: 0.3 sec
OOF RMSE: 2.85 | R2: 0.32
Fold 1
Fold 2

[I 2025-07-11 17:07:00,675] Trial 17 finished with value: 0.415721424963012 and parameters: {'learning_rate': 0.00640738914478516, 'num_leaves': 60, 'max_depth': 8, 'min_child_samples': 20, 'subsample': 0.8698266769827135, 'colsample_bytree': 0.7878792293429097, 'n_estimators': 500}. Best is trial 5 with value: 0.4841044867464147.

Fold 3
Fold 4
Fold 5
Running time: 0.3 sec
OOF RMSE: 2.65 | R2: 0.42
Fold 1

[I 2025-07-11 17:07:00,914] Trial 18 finished with value: 0.3950394842156284 and parameters: {'learning_rate': 0.0051447385382785114, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 25, 'subsample': 0.6689364886799243, 'colsample_bytree': 0.6254282645394827, 'n_estimators': 500}. Best is trial 5 with value: 0.4841044867464147.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 2.70 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 17:07:01,425] Trial 19 finished with value: 0.3465000025550947 and parameters: {'learning_rate': 0.010013242689812019, 'num_leaves': 40, 'max_depth': 6, 'min_child_samples': 8, 'subsample': 0.9597070970291387, 'colsample_bytree': 0.7174881221286012, 'n_estimators': 1000}. Best is trial 5 with value: 0.4841044867464147.

Fold 5
Running time: 0.5 sec
OOF RMSE: 2.80 | R2: 0.35
Fold 1
Fold 2

[I 2025-07-11 17:07:01,771] Trial 20 finished with value: 0.3470693281926983 and parameters: {'learning_rate': 0.024815646755864954, 'num_leaves': 20, 'max_depth': 8, 'min_child_samples': 11, 'subsample': 0.7472689372797328, 'colsample_bytree': 0.8928975339731974, 'n_estimators': 500}. Best is trial 5 with value: 0.4841044867464147.

Fold 3
Fold 4
Fold 5
Running time: 0.3 sec
OOF RMSE: 2.80 | R2: 0.35
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:07:02,031] Trial 21 finished with value: 0.42995074041771286 and parameters: {'learning_rate': 0.007338739203169411, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 22, 'subsample': 0.9190743652114647, 'colsample_bytree': 0.6790751035005038, 'n_estimators': 500}. Best is trial 5 with value: 0.4841044867464147.

Running time: 0.3 sec
OOF RMSE: 2.62 | R2: 0.43
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 17:07:02,286] Trial 22 finished with value: 0.4307869733964824 and parameters: {'learning_rate': 0.007191274040746021, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 22, 'subsample': 0.9449822636900987, 'colsample_bytree': 0.6799448628701521, 'n_estimators': 500}. Best is trial 5 with value: 0.4841044867464147.

Fold 5
Running time: 0.3 sec
OOF RMSE: 2.62 | R2: 0.43
Fold 1
Fold 2
Fold 3

[I 2025-07-11 17:07:02,542] Trial 23 finished with value: 0.4300677799093171 and parameters: {'learning_rate': 0.007291549200930173, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 22, 'subsample': 0.8794158750736332, 'colsample_bytree': 0.6632427016467375, 'n_estimators': 500}. Best is trial 5 with value: 0.4841044867464147.

Fold 4
Fold 5
Running time: 0.3 sec
OOF RMSE: 2.62 | R2: 0.43
Fold 1
Fold 2

[I 2025-07-11 17:07:02,814] Trial 24 finished with value: 0.3906295947084524 and parameters: {'learning_rate': 0.011479662638880641, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 19, 'subsample': 0.8775541821616488, 'colsample_bytree': 0.6470715835165266, 'n_estimators': 500}. Best is trial 5 with value: 0.4841044867464147.
[I 2025-07-11 17:07:02,815] A new study created in memory with name: no-name-c9daad87-9d5e-4a97-873a-b8f255746d05

Fold 3
Fold 4
Fold 5
Running time: 0.3 sec
OOF RMSE: 2.71 | R2: 0.39

✅ LBM - Mejor R2: 0.48
📋 Parámetros: {'learning_rate': 0.005849380680569026, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 7, 'subsample': 0.6122104334511537, 'colsample_bytree': 0.7554534645600801, 'n_estimators': 500}

Buscando mejores hiperparámetros para MLP...
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 17:07:04,043] Trial 0 finished with value: 0.4050922482541559 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.016149967764106314, 'learning_rate': 'adaptive', 'learning_rate_init': 0.002998932897384522}. Best is trial 0 with value: 0.4050922482541559.

Running time: 1.2 sec
OOF RMSE: 2.67 | R2: 0.41
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5
Running time: 1.4 sec
OOF RMSE: 2.82 | R2: 0.34

[I 2025-07-11 17:07:05,448] Trial 1 finished with value: 0.3404923381059153 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.07716558501524398, 'learning_rate': 'constant', 'learning_rate_init': 0.0027108208277644144}. Best is trial 0 with value: 0.4050922482541559.

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 17:07:06,941] Trial 2 finished with value: 0.36441475503005794 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.0578886205616607, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00011665388306510216}. Best is trial 0 with value: 0.4050922482541559.

Running time: 1.5 sec
OOF RMSE: 2.76 | R2: 0.36
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 17:07:07,443] Trial 3 finished with value: 0.2932327019492268 and parameters: {'hidden_layer_sizes': '50', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.0010880092227940911, 'learning_rate': 'constant', 'learning_rate_init': 0.0008976017406789964}. Best is trial 0 with value: 0.4050922482541559.

Fold 4
Fold 5
Running time: 0.5 sec
OOF RMSE: 2.91 | R2: 0.29
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 17:07:08,344] Trial 4 finished with value: 0.4208771818953999 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.03999764809807905, 'learning_rate': 'constant', 'learning_rate_init': 0.0008496574892566896}. Best is trial 4 with value: 0.4208771818953999.

Fold 5
Running time: 0.9 sec
OOF RMSE: 2.64 | R2: 0.42
Fold 1
Fold 2
Fold 3

[I 2025-07-11 17:07:08,984] Trial 5 finished with value: 0.373008155068145 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.00023698843336673243, 'learning_rate': 'constant', 'learning_rate_init': 0.009373401865672613}. Best is trial 4 with value: 0.4208771818953999.

Fold 4
Fold 5
Running time: 0.6 sec
OOF RMSE: 2.74 | R2: 0.37
Fold 1

[I 2025-07-11 17:07:09,307] Trial 6 finished with value: 0.43850914348052095 and parameters: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.015249564148417213, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00391554675417595}. Best is trial 6 with value: 0.43850914348052095.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.3 sec
OOF RMSE: 2.60 | R2: 0.44
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 17:07:11,594] Trial 7 finished with value: 0.29029608355372394 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 6.247193804860836e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00014972088383269263}. Best is trial 6 with value: 0.43850914348052095.

Running time: 2.3 sec
OOF RMSE: 2.92 | R2: 0.29
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 17:07:13,026] Trial 8 finished with value: 0.4166963194275992 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.006990866187651599, 'learning_rate': 'constant', 'learning_rate_init': 0.00039309729428347234}. Best is trial 6 with value: 0.43850914348052095.

Running time: 1.4 sec
OOF RMSE: 2.65 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:07:13,895] Trial 9 finished with value: 0.4039783129697845 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.0031588233184305925, 'learning_rate': 'constant', 'learning_rate_init': 0.0019825791481369376}. Best is trial 6 with value: 0.43850914348052095.

Running time: 0.9 sec
OOF RMSE: 2.68 | R2: 0.40
Fold 1
Fold 2
Fold 3

[I 2025-07-11 17:07:14,539] Trial 10 finished with value: 0.31827458944905573 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'relu', 'solver': 'adam', 'alpha': 2.9894422151294982e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.008620548198253577}. Best is trial 6 with value: 0.43850914348052095.

Fold 4
Fold 5
Running time: 0.6 sec
OOF RMSE: 2.86 | R2: 0.32
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 17:07:15,172] Trial 11 finished with value: 0.4208745415945577 and parameters: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.016048804561286233, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0007050443245526265}. Best is trial 6 with value: 0.43850914348052095.

Running time: 0.6 sec
OOF RMSE: 2.64 | R2: 0.42
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3
Fold 4

[I 2025-07-11 17:07:16,037] Trial 12 finished with value: 0.37970229338166006 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.033189732699631415, 'learning_rate': 'constant', 'learning_rate_init': 0.0003498938387541543}. Best is trial 6 with value: 0.43850914348052095.

Fold 5
Running time: 0.9 sec
OOF RMSE: 2.73 | R2: 0.38
Fold 1

[I 2025-07-11 17:07:16,421] Trial 13 finished with value: 0.4200823357643795 and parameters: {'hidden_layer_sizes': '50', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0020865580803820457, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0018294887759662084}. Best is trial 6 with value: 0.43850914348052095.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.4 sec
OOF RMSE: 2.64 | R2: 0.42
Fold 1
Fold 2
Fold 3

[I 2025-07-11 17:07:16,750] Trial 14 finished with value: 0.42900277746408255 and parameters: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0002358884963511107, 'learning_rate': 'constant', 'learning_rate_init': 0.004341052218481475}. Best is trial 6 with value: 0.43850914348052095.

Fold 4
Fold 5
Running time: 0.3 sec
OOF RMSE: 2.62 | R2: 0.43
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:07:17,081] Trial 15 finished with value: 0.42835505355268333 and parameters: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0002687929286070355, 'learning_rate': 'adaptive', 'learning_rate_init': 0.004725390179810764}. Best is trial 6 with value: 0.43850914348052095.

Running time: 0.3 sec
OOF RMSE: 2.62 | R2: 0.43
Fold 1
Fold 2
Fold 3

[I 2025-07-11 17:07:17,423] Trial 16 finished with value: 0.42606189354303237 and parameters: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.00016334660835413465, 'learning_rate': 'constant', 'learning_rate_init': 0.004473694503027252}. Best is trial 6 with value: 0.43850914348052095.

Fold 4
Fold 5
Running time: 0.3 sec
OOF RMSE: 2.63 | R2: 0.43
Fold 1
Fold 2
Fold 3

[I 2025-07-11 17:07:17,893] Trial 17 finished with value: 0.41950973550149195 and parameters: {'hidden_layer_sizes': '50', 'activation': 'relu', 'solver': 'adam', 'alpha': 1.2862745735792188e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.005379101823308155}. Best is trial 6 with value: 0.43850914348052095.

Fold 4
Fold 5
Running time: 0.5 sec
OOF RMSE: 2.64 | R2: 0.42
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 17:07:18,760] Trial 18 finished with value: 0.2575784094882855 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0005047440101504625, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0013887021579064038}. Best is trial 6 with value: 0.43850914348052095.

Fold 4
Fold 5
Running time: 0.9 sec
OOF RMSE: 2.99 | R2: 0.26
Fold 1

[I 2025-07-11 17:07:19,075] Trial 19 finished with value: 0.3996710934922796 and parameters: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.005195638329961791, 'learning_rate': 'constant', 'learning_rate_init': 0.006077704154009053}. Best is trial 6 with value: 0.43850914348052095.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.3 sec
OOF RMSE: 2.69 | R2: 0.40
Fold 1

[I 2025-07-11 17:07:19,429] Trial 20 finished with value: 0.42726533934498534 and parameters: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0009190026161625061, 'learning_rate': 'constant', 'learning_rate_init': 0.0030609108189585056}. Best is trial 6 with value: 0.43850914348052095.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.3 sec
OOF RMSE: 2.62 | R2: 0.43
Fold 1

[I 2025-07-11 17:07:19,762] Trial 21 finished with value: 0.44147982292583554 and parameters: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.00013513916207160778, 'learning_rate': 'adaptive', 'learning_rate_init': 0.004133225692173275}. Best is trial 21 with value: 0.44147982292583554.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.3 sec
OOF RMSE: 2.59 | R2: 0.44
Fold 1

[I 2025-07-11 17:07:20,094] Trial 22 finished with value: 0.4410411945514393 and parameters: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'adam', 'alpha': 9.715584150031195e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0040883397589015795}. Best is trial 21 with value: 0.44147982292583554.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.3 sec
OOF RMSE: 2.59 | R2: 0.44
Fold 1
Fold 2

[I 2025-07-11 17:07:20,475] Trial 23 finished with value: 0.42446084866813916 and parameters: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'adam', 'alpha': 8.816882787237969e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0014260723022176205}. Best is trial 21 with value: 0.44147982292583554.

Fold 3
Fold 4
Fold 5
Running time: 0.4 sec
OOF RMSE: 2.63 | R2: 0.42
Fold 1

[I 2025-07-11 17:07:20,786] Trial 24 finished with value: 0.38530104412371924 and parameters: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'adam', 'alpha': 3.483889610047506e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.007107677652923212}. Best is trial 21 with value: 0.44147982292583554.
[I 2025-07-11 17:07:20,788] A new study created in memory with name: no-name-1e6414bf-548e-4028-8268-ff38612a34b9

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.3 sec
OOF RMSE: 2.72 | R2: 0.39

✅ MLP - Mejor R2: 0.44
📋 Parámetros: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.00013513916207160778, 'learning_rate': 'adaptive', 'learning_rate_init': 0.004133225692173275}

Buscando mejores hiperparámetros para SVR...
Fold 1
Fold 2

[I 2025-07-11 17:07:20,877] Trial 0 finished with value: 0.15407240580418624 and parameters: {'kernel': 'rbf', 'C': 0.670417962069225, 'epsilon': 0.07684713185160243, 'gamma': 'scale'}. Best is trial 0 with value: 0.15407240580418624.
[I 2025-07-11 17:07:20,951] Trial 1 finished with value: 0.3827033188701211 and parameters: {'kernel': 'rbf', 'C': 4.901102703542147, 'epsilon': 0.062362346519350964, 'gamma': 'scale'}. Best is trial 1 with value: 0.3827033188701211.
[I 2025-07-11 17:07:21,014] Trial 2 finished with value: 0.19228036126964243 and parameters: {'kernel': 'rbf', 'C': 1.1069401779622994, 'epsilon': 0.19891813264378058, 'gamma': 'auto'}. Best is trial 1 with value: 0.3827033188701211.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.19 | R2: 0.15
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.72 | R2: 0.38
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.12 | R2: 0.19
Fold 1

[I 2025-07-11 17:07:21,083] Trial 3 finished with value: 0.1545940093407684 and parameters: {'kernel': 'rbf', 'C': 0.6576149267267933, 'epsilon': 0.02011108077599765, 'gamma': 'scale'}. Best is trial 1 with value: 0.3827033188701211.
[I 2025-07-11 17:07:21,153] Trial 4 finished with value: 0.19465083695107344 and parameters: {'kernel': 'rbf', 'C': 1.2054279383858817, 'epsilon': 0.019412407365354083, 'gamma': 'auto'}. Best is trial 1 with value: 0.3827033188701211.
[I 2025-07-11 17:07:21,216] Trial 5 finished with value: 0.17310548462906294 and parameters: {'kernel': 'rbf', 'C': 0.854039262305799, 'epsilon': 0.15745034979561165, 'gamma': 'scale'}. Best is trial 1 with value: 0.3827033188701211.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.19 | R2: 0.15
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.11 | R2: 0.19
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.15 | R2: 0.17
Fold 1

[I 2025-07-11 17:07:21,287] Trial 6 finished with value: -0.30597798889582317 and parameters: {'kernel': 'sigmoid', 'C': 0.3677793312468939, 'epsilon': 0.0828735090618148, 'gamma': 'scale'}. Best is trial 1 with value: 0.3827033188701211.
[I 2025-07-11 17:07:21,354] Trial 7 finished with value: 0.05463440864199309 and parameters: {'kernel': 'rbf', 'C': 0.19730209418999894, 'epsilon': 0.01038256390917089, 'gamma': 'scale'}. Best is trial 1 with value: 0.3827033188701211.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.96 | R2: -0.31
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.37 | R2: 0.05
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:07:21,444] Trial 8 finished with value: 0.35117144462638095 and parameters: {'kernel': 'rbf', 'C': 4.650931754417496, 'epsilon': 0.1932453065547778, 'gamma': 'auto'}. Best is trial 1 with value: 0.3827033188701211.
[I 2025-07-11 17:07:21,514] Trial 9 finished with value: -0.13863938282597954 and parameters: {'kernel': 'sigmoid', 'C': 0.2848882066017966, 'epsilon': 0.06939815983506453, 'gamma': 'scale'}. Best is trial 1 with value: 0.3827033188701211.
[I 2025-07-11 17:07:21,588] Trial 10 finished with value: -342.10935403163455 and parameters: {'kernel': 'sigmoid', 'C': 9.474479471089072, 'epsilon': 0.12542965250248705, 'gamma': 'auto'}. Best is trial 1 with value: 0.3827033188701211.

Running time: 0.1 sec
OOF RMSE: 2.79 | R2: 0.35
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.70 | R2: -0.14
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 64.21 | R2: -342.11
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 17:07:21,665] Trial 11 finished with value: 0.3634643638768257 and parameters: {'kernel': 'rbf', 'C': 5.288223448041256, 'epsilon': 0.18417784732986936, 'gamma': 'auto'}. Best is trial 1 with value: 0.3827033188701211.
[I 2025-07-11 17:07:21,745] Trial 12 finished with value: 0.31437829874036405 and parameters: {'kernel': 'rbf', 'C': 3.2059589097585146, 'epsilon': 0.13260086461453896, 'gamma': 'auto'}. Best is trial 1 with value: 0.3827033188701211.
[I 2025-07-11 17:07:21,820] Trial 13 finished with value: 0.2841415489394704 and parameters: {'kernel': 'rbf', 'C': 2.4517619693358634, 'epsilon': 0.051106706286170867, 'gamma': 'auto'}. Best is trial 1 with value: 0.3827033188701211.

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.77 | R2: 0.36
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.87 | R2: 0.31
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.93 | R2: 0.28
Fold 1
Fold 2

[I 2025-07-11 17:07:21,897] Trial 14 finished with value: -212.12840768879593 and parameters: {'kernel': 'sigmoid', 'C': 9.372874981428424, 'epsilon': 0.16387663226673843, 'gamma': 'scale'}. Best is trial 1 with value: 0.3827033188701211.
[I 2025-07-11 17:07:21,974] Trial 15 finished with value: 0.3681828615947509 and parameters: {'kernel': 'rbf', 'C': 5.366147342762163, 'epsilon': 0.10545544511289856, 'gamma': 'auto'}. Best is trial 1 with value: 0.3827033188701211.
[I 2025-07-11 17:07:22,048] Trial 16 finished with value: 0.26539372125753746 and parameters: {'kernel': 'rbf', 'C': 2.077840651336923, 'epsilon': 0.10714504636197957, 'gamma': 'auto'}. Best is trial 1 with value: 0.3827033188701211.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 50.61 | R2: -212.13
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.76 | R2: 0.37
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.97 | R2: 0.27

[I 2025-07-11 17:07:22,125] Trial 17 finished with value: 0.3871156828257647 and parameters: {'kernel': 'rbf', 'C': 5.150444245966143, 'epsilon': 0.04836521756366091, 'gamma': 'scale'}. Best is trial 17 with value: 0.3871156828257647.
[I 2025-07-11 17:07:22,202] Trial 18 finished with value: -8.111516575494898 and parameters: {'kernel': 'sigmoid', 'C': 1.699827397892588, 'epsilon': 0.043018025723691164, 'gamma': 'scale'}. Best is trial 17 with value: 0.3871156828257647.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.71 | R2: 0.39
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 10.46 | R2: -8.11
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 17:07:22,280] Trial 19 finished with value: 0.35632354608117645 and parameters: {'kernel': 'rbf', 'C': 3.712160711824222, 'epsilon': 0.04607819402809432, 'gamma': 'scale'}. Best is trial 17 with value: 0.3871156828257647.
[I 2025-07-11 17:07:22,355] Trial 20 finished with value: 0.01830709751623716 and parameters: {'kernel': 'rbf', 'C': 0.10491773615493542, 'epsilon': 0.06065312804916019, 'gamma': 'scale'}. Best is trial 17 with value: 0.3871156828257647.
[I 2025-07-11 17:07:22,430] Trial 21 finished with value: 0.39316170809189943 and parameters: {'kernel': 'rbf', 'C': 5.87322198935266, 'epsilon': 0.10763947100281152, 'gamma': 'scale'}. Best is trial 21 with value: 0.39316170809189943.

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.78 | R2: 0.36
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.43 | R2: 0.02
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.70 | R2: 0.39
Fold 1
Fold 2

[I 2025-07-11 17:07:22,512] Trial 22 finished with value: 0.40319978800850387 and parameters: {'kernel': 'rbf', 'C': 7.37608759185077, 'epsilon': 0.08922522130781191, 'gamma': 'scale'}. Best is trial 22 with value: 0.40319978800850387.
[I 2025-07-11 17:07:22,590] Trial 23 finished with value: 0.40296502377453547 and parameters: {'kernel': 'rbf', 'C': 7.316074609000999, 'epsilon': 0.090804884042737, 'gamma': 'scale'}. Best is trial 22 with value: 0.40319978800850387.
[I 2025-07-11 17:07:22,667] Trial 24 finished with value: 0.4048960366780281 and parameters: {'kernel': 'rbf', 'C': 7.926155854189685, 'epsilon': 0.09039948325118322, 'gamma': 'scale'}. Best is trial 24 with value: 0.4048960366780281.
[I 2025-07-11 17:07:22,668] A new study created in memory with name: no-name-b38ad7e0-5fa1-4d2a-b8dd-7df557afca64

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.68 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.68 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.67 | R2: 0.40

✅ SVR - Mejor R2: 0.40
📋 Parámetros: {'kernel': 'rbf', 'C': 7.926155854189685, 'epsilon': 0.09039948325118322, 'gamma': 'scale'}

Buscando mejores hiperparámetros para KNN...

[I 2025-07-11 17:07:22,727] Trial 0 finished with value: 0.4769719157701532 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'leaf_size': 30}. Best is trial 0 with value: 0.4769719157701532.
[I 2025-07-11 17:07:22,788] Trial 1 finished with value: 0.4516397646660718 and parameters: {'n_neighbors': 15, 'weights': 'distance', 'leaf_size': 34}. Best is trial 0 with value: 0.4769719157701532.
[I 2025-07-11 17:07:22,846] Trial 2 finished with value: 0.47184504510171466 and parameters: {'n_neighbors': 13, 'weights': 'distance', 'leaf_size': 31}. Best is trial 0 with value: 0.4769719157701532.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.51 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.57 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.52 | R2: 0.47
Fold 1
Fold 2
Fold 3

[I 2025-07-11 17:07:22,908] Trial 3 finished with value: 0.4605005090491876 and parameters: {'n_neighbors': 14, 'weights': 'distance', 'leaf_size': 38}. Best is trial 0 with value: 0.4769719157701532.
[I 2025-07-11 17:07:22,968] Trial 4 finished with value: 0.48304408775319274 and parameters: {'n_neighbors': 9, 'weights': 'distance', 'leaf_size': 25}. Best is trial 4 with value: 0.48304408775319274.
[I 2025-07-11 17:07:23,023] Trial 5 finished with value: 0.4329330836368168 and parameters: {'n_neighbors': 13, 'weights': 'uniform', 'leaf_size': 34}. Best is trial 4 with value: 0.48304408775319274.
[I 2025-07-11 17:07:23,078] Trial 6 finished with value: 0.4472970567177287 and parameters: {'n_neighbors': 7, 'weights': 'uniform', 'leaf_size': 26}. Best is trial 4 with value: 0.48304408775319274.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.55 | R2: 0.46
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.49 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.61 | R2: 0.43
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.58 | R2: 0.45
Fold 1

[I 2025-07-11 17:07:23,138] Trial 7 finished with value: 0.4769719157701532 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'leaf_size': 31}. Best is trial 4 with value: 0.48304408775319274.
[I 2025-07-11 17:07:23,198] Trial 8 finished with value: 0.440075916251484 and parameters: {'n_neighbors': 10, 'weights': 'uniform', 'leaf_size': 14}. Best is trial 4 with value: 0.48304408775319274.
[I 2025-07-11 17:07:23,255] Trial 9 finished with value: 0.47401409500392533 and parameters: {'n_neighbors': 12, 'weights': 'distance', 'leaf_size': 27}. Best is trial 4 with value: 0.48304408775319274.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.51 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.59 | R2: 0.44
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.51 | R2: 0.47
Fold 1
Fold 2
Fold 3

[I 2025-07-11 17:07:23,321] Trial 10 finished with value: 0.4379722028689661 and parameters: {'n_neighbors': 9, 'weights': 'uniform', 'leaf_size': 19}. Best is trial 4 with value: 0.48304408775319274.
[I 2025-07-11 17:07:23,390] Trial 11 finished with value: 0.4586765791642886 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 21}. Best is trial 4 with value: 0.48304408775319274.
[I 2025-07-11 17:07:23,455] Trial 12 finished with value: 0.48417177792451804 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'leaf_size': 22}. Best is trial 12 with value: 0.48417177792451804.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.60 | R2: 0.44
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.55 | R2: 0.46
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.49 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 17:07:23,523] Trial 13 finished with value: 0.48304408775319274 and parameters: {'n_neighbors': 9, 'weights': 'distance', 'leaf_size': 20}. Best is trial 12 with value: 0.48417177792451804.
[I 2025-07-11 17:07:23,593] Trial 14 finished with value: 0.48417177792451804 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'leaf_size': 11}. Best is trial 12 with value: 0.48417177792451804.
[I 2025-07-11 17:07:23,657] Trial 15 finished with value: 0.48417177792451804 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'leaf_size': 10}. Best is trial 12 with value: 0.48417177792451804.

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.49 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.49 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.49 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:07:23,721] Trial 16 finished with value: 0.48417177792451804 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'leaf_size': 14}. Best is trial 12 with value: 0.48417177792451804.
[I 2025-07-11 17:07:23,791] Trial 17 finished with value: 0.4769719157701532 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'leaf_size': 11}. Best is trial 12 with value: 0.48417177792451804.
[I 2025-07-11 17:07:23,852] Trial 18 finished with value: 0.41991374398179304 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'leaf_size': 18}. Best is trial 12 with value: 0.48417177792451804.
[I 2025-07-11 17:07:23,914] Trial 19 finished with value: 0.4860740106565894 and parameters: {'n_neighbors': 11, 'weights': 'distance', 'leaf_size': 15}. Best is trial 19 with value: 0.4860740106565894.

Running time: 0.1 sec
OOF RMSE: 2.49 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.51 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.64 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.49 | R2: 0.49

[I 2025-07-11 17:07:23,982] Trial 20 finished with value: 0.4860740106565894 and parameters: {'n_neighbors': 11, 'weights': 'distance', 'leaf_size': 22}. Best is trial 19 with value: 0.4860740106565894.
[I 2025-07-11 17:07:24,048] Trial 21 finished with value: 0.4860740106565894 and parameters: {'n_neighbors': 11, 'weights': 'distance', 'leaf_size': 22}. Best is trial 19 with value: 0.4860740106565894.
[I 2025-07-11 17:07:24,112] Trial 22 finished with value: 0.4860740106565894 and parameters: {'n_neighbors': 11, 'weights': 'distance', 'leaf_size': 16}. Best is trial 19 with value: 0.4860740106565894.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.49 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.49 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.49 | R2: 0.49
Fold 1

[I 2025-07-11 17:07:24,190] Trial 23 finished with value: 0.4860740106565894 and parameters: {'n_neighbors': 11, 'weights': 'distance', 'leaf_size': 24}. Best is trial 19 with value: 0.4860740106565894.
[I 2025-07-11 17:07:24,275] Trial 24 finished with value: 0.4860740106565894 and parameters: {'n_neighbors': 11, 'weights': 'distance', 'leaf_size': 16}. Best is trial 19 with value: 0.4860740106565894.
[I 2025-07-11 17:07:24,276] A new study created in memory with name: no-name-958fa3b1-3bbb-4d68-b9c3-06493ca5e614
[I 2025-07-11 17:07:24,332] Trial 0 finished with value: 0.30740115287747094 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: 0.30740115287747094.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.49 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.49 | R2: 0.49

✅ KNN - Mejor R2: 0.49
📋 Parámetros: {'n_neighbors': 11, 'weights': 'distance', 'leaf_size': 15}

Buscando mejores hiperparámetros para LR...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.88 | R2: 0.31

[I 2025-07-11 17:07:24,415] Trial 1 finished with value: 0.2571380523847113 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 0 with value: 0.30740115287747094.
[I 2025-07-11 17:07:24,505] Trial 2 finished with value: 0.2571380523847113 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 0 with value: 0.30740115287747094.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.99 | R2: 0.26
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.99 | R2: 0.26
Fold 1
Fold 2

[I 2025-07-11 17:07:24,584] Trial 3 finished with value: 0.2571380523782685 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 0 with value: 0.30740115287747094.
[I 2025-07-11 17:07:24,667] Trial 4 finished with value: 0.30752474310345035 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 4 with value: 0.30752474310345035.
[I 2025-07-11 17:07:24,723] Trial 5 finished with value: 0.30740115287747094 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 4 with value: 0.30752474310345035.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.99 | R2: 0.26
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.88 | R2: 0.31
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.88 | R2: 0.31
Fold 1
Fold 2

[I 2025-07-11 17:07:24,782] Trial 6 finished with value: 0.30752474310345035 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 4 with value: 0.30752474310345035.
[I 2025-07-11 17:07:24,855] Trial 7 finished with value: 0.2571380523847113 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 4 with value: 0.30752474310345035.
[I 2025-07-11 17:07:24,930] Trial 8 finished with value: 0.2571380523782685 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 4 with value: 0.30752474310345035.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.88 | R2: 0.31
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.99 | R2: 0.26
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.99 | R2: 0.26
Fold 1
Fold 2

[I 2025-07-11 17:07:25,022] Trial 9 finished with value: 0.2571380523782685 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 4 with value: 0.30752474310345035.
[I 2025-07-11 17:07:25,099] Trial 10 finished with value: 0.30752474310345035 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 4 with value: 0.30752474310345035.
[I 2025-07-11 17:07:25,156] Trial 11 finished with value: 0.30752474310345035 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 4 with value: 0.30752474310345035.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.99 | R2: 0.26
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.88 | R2: 0.31
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.88 | R2: 0.31
Fold 1

[I 2025-07-11 17:07:25,217] Trial 12 finished with value: 0.30752474310345035 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 4 with value: 0.30752474310345035.
[I 2025-07-11 17:07:25,277] Trial 13 finished with value: 0.30752474310345035 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 4 with value: 0.30752474310345035.
[I 2025-07-11 17:07:25,333] Trial 14 finished with value: 0.30752474310345035 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 4 with value: 0.30752474310345035.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.88 | R2: 0.31
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.88 | R2: 0.31
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.88 | R2: 0.31
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 17:07:25,390] Trial 15 finished with value: 0.30752474310345035 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 4 with value: 0.30752474310345035.
[I 2025-07-11 17:07:25,448] Trial 16 finished with value: 0.30752474310345035 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 4 with value: 0.30752474310345035.
[I 2025-07-11 17:07:25,504] Trial 17 finished with value: 0.30752474310345035 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 4 with value: 0.30752474310345035.
[I 2025-07-11 17:07:25,560] Trial 18 finished with value: 0.30752474310345035 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 4 with value: 0.30752474310345035.

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.88 | R2: 0.31
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.88 | R2: 0.31
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.88 | R2: 0.31
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.88 | R2: 0.31
Fold 1
Fold 2

[I 2025-07-11 17:07:25,619] Trial 19 finished with value: 0.30752474310345035 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 4 with value: 0.30752474310345035.
[I 2025-07-11 17:07:25,678] Trial 20 finished with value: 0.30752474310345035 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 4 with value: 0.30752474310345035.
[I 2025-07-11 17:07:25,733] Trial 21 finished with value: 0.30752474310345035 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 4 with value: 0.30752474310345035.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.88 | R2: 0.31
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.88 | R2: 0.31
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.88 | R2: 0.31
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.88 | R2: 0.31

[I 2025-07-11 17:07:25,789] Trial 22 finished with value: 0.30752474310345035 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 4 with value: 0.30752474310345035.
[I 2025-07-11 17:07:25,847] Trial 23 finished with value: 0.30752474310345035 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 4 with value: 0.30752474310345035.
[I 2025-07-11 17:07:25,904] Trial 24 finished with value: 0.30752474310345035 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 4 with value: 0.30752474310345035.
[I 2025-07-11 17:07:25,905] A new study created in memory with name: no-name-6e68c50c-8b25-4fa2-b203-355cd7f5fe21

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.88 | R2: 0.31
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.88 | R2: 0.31

✅ LR - Mejor R2: 0.31
📋 Parámetros: {'fit_intercept': False, 'positive': True}

Buscando mejores hiperparámetros para RF...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:07:28,564] Trial 0 finished with value: 0.117167351430846 and parameters: {'n_estimators': 100, 'max_depth': 11, 'min_samples_split': 5, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 0 with value: 0.117167351430846.

Running time: 2.7 sec
OOF RMSE: 3.26 | R2: 0.12
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:07:33,724] Trial 1 finished with value: 0.38658085783142837 and parameters: {'n_estimators': 300, 'max_depth': 9, 'min_samples_split': 6, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 1 with value: 0.38658085783142837.

Running time: 5.2 sec
OOF RMSE: 2.72 | R2: 0.39
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:07:35,789] Trial 2 finished with value: 0.12142745021707257 and parameters: {'n_estimators': 100, 'max_depth': 6, 'min_samples_split': 10, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 1 with value: 0.38658085783142837.

Running time: 2.1 sec
OOF RMSE: 3.25 | R2: 0.12
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:07:37,330] Trial 3 finished with value: 0.38174142274913003 and parameters: {'n_estimators': 100, 'max_depth': 10, 'min_samples_split': 7, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 1 with value: 0.38658085783142837.

Running time: 1.5 sec
OOF RMSE: 2.73 | R2: 0.38
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:07:41,306] Trial 4 finished with value: 0.3744273547613741 and parameters: {'n_estimators': 300, 'max_depth': 5, 'min_samples_split': 6, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 1 with value: 0.38658085783142837.

Running time: 4.0 sec
OOF RMSE: 2.74 | R2: 0.37
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:07:46,639] Trial 5 finished with value: 0.37383232602219996 and parameters: {'n_estimators': 300, 'max_depth': 9, 'min_samples_split': 7, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 1 with value: 0.38658085783142837.

Running time: 5.3 sec
OOF RMSE: 2.74 | R2: 0.37
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:07:47,936] Trial 6 finished with value: 0.3911398519430693 and parameters: {'n_estimators': 100, 'max_depth': 5, 'min_samples_split': 9, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 6 with value: 0.3911398519430693.

Running time: 1.3 sec
OOF RMSE: 2.70 | R2: 0.39
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:07:49,690] Trial 7 finished with value: 0.38915881625724347 and parameters: {'n_estimators': 100, 'max_depth': 11, 'min_samples_split': 8, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 6 with value: 0.3911398519430693.

Running time: 1.7 sec
OOF RMSE: 2.71 | R2: 0.39
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:07:54,095] Trial 8 finished with value: 0.39367068340005607 and parameters: {'n_estimators': 300, 'max_depth': 7, 'min_samples_split': 9, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 8 with value: 0.39367068340005607.

Running time: 4.4 sec
OOF RMSE: 2.70 | R2: 0.39
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:08:01,903] Trial 9 finished with value: 0.10045976368099885 and parameters: {'n_estimators': 300, 'max_depth': 9, 'min_samples_split': 10, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 8 with value: 0.39367068340005607.

Running time: 7.8 sec
OOF RMSE: 3.29 | R2: 0.10
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:08:13,723] Trial 10 finished with value: 0.11624972657052413 and parameters: {'n_estimators': 500, 'max_depth': 14, 'min_samples_split': 2, 'min_samples_leaf': 5, 'bootstrap': False}. Best is trial 8 with value: 0.39367068340005607.

Running time: 11.8 sec
OOF RMSE: 3.26 | R2: 0.12
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:08:21,166] Trial 11 finished with value: 0.3929612480638771 and parameters: {'n_estimators': 500, 'max_depth': 7, 'min_samples_split': 9, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 8 with value: 0.39367068340005607.

Running time: 7.4 sec
OOF RMSE: 2.70 | R2: 0.39
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:08:28,766] Trial 12 finished with value: 0.3951619674944291 and parameters: {'n_estimators': 500, 'max_depth': 7, 'min_samples_split': 4, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 12 with value: 0.3951619674944291.

Running time: 7.6 sec
OOF RMSE: 2.70 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:08:36,015] Trial 13 finished with value: 0.37965621326596377 and parameters: {'n_estimators': 500, 'max_depth': 7, 'min_samples_split': 3, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 12 with value: 0.3951619674944291.

Running time: 7.2 sec
OOF RMSE: 2.73 | R2: 0.38
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:08:43,291] Trial 14 finished with value: 0.37965621326596377 and parameters: {'n_estimators': 500, 'max_depth': 7, 'min_samples_split': 4, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 12 with value: 0.3951619674944291.

Running time: 7.3 sec
OOF RMSE: 2.73 | R2: 0.38
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:08:48,254] Trial 15 finished with value: 0.39801167334890364 and parameters: {'n_estimators': 300, 'max_depth': 15, 'min_samples_split': 4, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 15 with value: 0.39801167334890364.

Running time: 5.0 sec
OOF RMSE: 2.69 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:08:55,547] Trial 16 finished with value: 0.37415808669465445 and parameters: {'n_estimators': 500, 'max_depth': 14, 'min_samples_split': 4, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 15 with value: 0.39801167334890364.

Running time: 7.3 sec
OOF RMSE: 2.74 | R2: 0.37
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:09:03,339] Trial 17 finished with value: 0.37931340126343727 and parameters: {'n_estimators': 500, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 15 with value: 0.39801167334890364.

Running time: 7.8 sec
OOF RMSE: 2.73 | R2: 0.38
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:09:12,028] Trial 18 finished with value: 0.14347549620660327 and parameters: {'n_estimators': 300, 'max_depth': 12, 'min_samples_split': 4, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 15 with value: 0.39801167334890364.

Running time: 8.7 sec
OOF RMSE: 3.21 | R2: 0.14
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:09:20,380] Trial 19 finished with value: 0.3960344129526533 and parameters: {'n_estimators': 500, 'max_depth': 13, 'min_samples_split': 5, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 15 with value: 0.39801167334890364.

Running time: 8.3 sec
OOF RMSE: 2.69 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:09:24,944] Trial 20 finished with value: 0.3789198945186796 and parameters: {'n_estimators': 300, 'max_depth': 13, 'min_samples_split': 5, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 15 with value: 0.39801167334890364.

Running time: 4.6 sec
OOF RMSE: 2.73 | R2: 0.38
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:09:33,310] Trial 21 finished with value: 0.3956320874716359 and parameters: {'n_estimators': 500, 'max_depth': 15, 'min_samples_split': 3, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 15 with value: 0.39801167334890364.

Running time: 8.4 sec
OOF RMSE: 2.69 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:09:41,726] Trial 22 finished with value: 0.3956320874716359 and parameters: {'n_estimators': 500, 'max_depth': 15, 'min_samples_split': 3, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 15 with value: 0.39801167334890364.

Running time: 8.4 sec
OOF RMSE: 2.69 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:09:50,102] Trial 23 finished with value: 0.39537847975948803 and parameters: {'n_estimators': 500, 'max_depth': 14, 'min_samples_split': 3, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 15 with value: 0.39801167334890364.

Running time: 8.4 sec
OOF RMSE: 2.70 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:09:59,208] Trial 24 finished with value: 0.3923075655833064 and parameters: {'n_estimators': 500, 'max_depth': 13, 'min_samples_split': 5, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 15 with value: 0.39801167334890364.
[I 2025-07-11 17:09:59,209] A new study created in memory with name: no-name-bc28f411-ee64-4016-a8ea-31ecc3e34216

Running time: 9.1 sec
OOF RMSE: 2.70 | R2: 0.39

✅ RF - Mejor R2: 0.40
📋 Parámetros: {'n_estimators': 300, 'max_depth': 15, 'min_samples_split': 4, 'min_samples_leaf': 3, 'bootstrap': True}

Buscando mejores hiperparámetros para CAT...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:13:01,409] Trial 0 finished with value: 0.5020901746821778 and parameters: {'iterations': 2000, 'learning_rate': 0.014055584655013302, 'depth': 9, 'l2_leaf_reg': 1.5655403361430114}. Best is trial 0 with value: 0.5020901746821778.

Running time: 182.2 sec
OOF RMSE: 2.45 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:13:15,878] Trial 1 finished with value: 0.4268595080676515 and parameters: {'iterations': 2000, 'learning_rate': 0.08773553485822198, 'depth': 6, 'l2_leaf_reg': 5.880915172891007}. Best is trial 0 with value: 0.5020901746821778.

Running time: 14.5 sec
OOF RMSE: 2.62 | R2: 0.43
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:14:31,050] Trial 2 finished with value: 0.4176956581270007 and parameters: {'iterations': 500, 'learning_rate': 0.014353303330904349, 'depth': 10, 'l2_leaf_reg': 7.142257718750266}. Best is trial 0 with value: 0.5020901746821778.

Running time: 75.2 sec
OOF RMSE: 2.65 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:14:37,283] Trial 3 finished with value: 0.45788875424844677 and parameters: {'iterations': 2000, 'learning_rate': 0.09263646533059823, 'depth': 4, 'l2_leaf_reg': 8.485468867301282}. Best is trial 0 with value: 0.5020901746821778.

Running time: 6.2 sec
OOF RMSE: 2.55 | R2: 0.46
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:17:38,820] Trial 4 finished with value: 0.44246279383182585 and parameters: {'iterations': 2000, 'learning_rate': 0.02377462015151827, 'depth': 9, 'l2_leaf_reg': 8.511002058048767}. Best is trial 0 with value: 0.5020901746821778.

Running time: 181.5 sec
OOF RMSE: 2.59 | R2: 0.44
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:17:59,122] Trial 5 finished with value: 0.4496129936986053 and parameters: {'iterations': 500, 'learning_rate': 0.05434472617017285, 'depth': 8, 'l2_leaf_reg': 5.2248174835668575}. Best is trial 0 with value: 0.5020901746821778.

Running time: 20.3 sec
OOF RMSE: 2.57 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:18:02,430] Trial 6 finished with value: 0.4863307300151587 and parameters: {'iterations': 1000, 'learning_rate': 0.0618470927605472, 'depth': 4, 'l2_leaf_reg': 5.661652089919626}. Best is trial 0 with value: 0.5020901746821778.

Running time: 3.3 sec
OOF RMSE: 2.48 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:19:33,450] Trial 7 finished with value: 0.4930898956678095 and parameters: {'iterations': 1000, 'learning_rate': 0.04582662953177604, 'depth': 9, 'l2_leaf_reg': 1.8061949352547675}. Best is trial 0 with value: 0.5020901746821778.

Running time: 91.0 sec
OOF RMSE: 2.47 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:21:03,414] Trial 8 finished with value: 0.4579527594866134 and parameters: {'iterations': 1000, 'learning_rate': 0.027316053712913017, 'depth': 9, 'l2_leaf_reg': 5.953754003174132}. Best is trial 0 with value: 0.5020901746821778.
[I 2025-07-11 17:21:03,415] A new study created in memory with name: no-name-d162b12a-02b3-49de-8014-2045b411271c
[I 2025-07-11 17:21:03,501] Trial 0 finished with value: 0.42522746437907755 and parameters: {'alpha': 0.20249181417414955, 'l1_ratio': 0.10211541533501067}. Best is trial 0 with value: 0.42522746437907755.
[I 2025-07-11 17:21:03,579] Trial 1 finished with value: 0.4198795393705381 and parameters: {'alpha': 1.447501939450387, 'l1_ratio': 0.4020634015518426}. Best is trial 0 with value: 0.42522746437907755.

Running time: 90.0 sec
OOF RMSE: 2.55 | R2: 0.46

✅ CAT - Mejor R2: 0.50
📋 Parámetros: {'iterations': 2000, 'learning_rate': 0.014055584655013302, 'depth': 9, 'l2_leaf_reg': 1.5655403361430114}

Buscando mejores hiperparámetros para EN...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.63 | R2: 0.43
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.64 | R2: 0.42
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.554e+01, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.938e+01, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.773e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.323e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.484e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 17:21:03,706] Trial 2 finished with value: 0.33145847772569226 and parameters: {'alpha': 0.002899043728137619, 'l1_ratio': 0.46191980342382777}. Best is trial 0 with value: 0.42522746437907755.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.465e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.571e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.366e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.038e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.187e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 17:21:03,828] Trial 3 finished with value: 0.11919570258908663 and parameters: {'alpha': 0.00021348626501482934, 'l1_ratio': 0.029146972343346622}. Best is trial 0 with value: 0.42522746437907755.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.83 | R2: 0.33
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.25 | R2: 0.12

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.176e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.404e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.531e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.908e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.801e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 17:21:03,956] Trial 4 finished with value: 0.3887064782364048 and parameters: {'alpha': 0.00630187073633873, 'l1_ratio': 0.05164187251343433}. Best is trial 0 with value: 0.42522746437907755.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.423e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.539e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.71 | R2: 0.39
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.338e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.010e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.136e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 17:21:04,078] Trial 5 finished with value: 0.10932328984750761 and parameters: {'alpha': 0.00011680933802544081, 'l1_ratio': 0.04371637903375247}. Best is trial 0 with value: 0.42522746437907755.
[I 2025-07-11 17:21:04,172] Trial 6 finished with value: 0.4256170712722742 and parameters: {'alpha': 0.7458193314687079, 'l1_ratio': 0.7402939336279012}. Best is trial 6 with value: 0.4256170712722742.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.296e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.439e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(

Fold 5
Running time: 0.1 sec
OOF RMSE: 3.27 | R2: 0.11
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.63 | R2: 0.43
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.233e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.887e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.963e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 17:21:04,295] Trial 7 finished with value: 0.10464513866337954 and parameters: {'alpha': 0.00012027181949535714, 'l1_ratio': 0.5762342427894073}. Best is trial 6 with value: 0.4256170712722742.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.824e-01, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(

Fold 5
Running time: 0.1 sec
OOF RMSE: 3.28 | R2: 0.10
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.167e+00, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 17:21:04,520] Trial 8 finished with value: 0.4053703603545702 and parameters: {'alpha': 0.06802322040204759, 'l1_ratio': 0.03206044790890772}. Best is trial 6 with value: 0.4256170712722742.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.760e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.038e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.301e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.511e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.349e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 17:21:04,643] Trial 9 finished with value: 0.39587543698892325 and parameters: {'alpha': 0.008568856348796533, 'l1_ratio': 0.08125862330755751}. Best is trial 6 with value: 0.4256170712722742.

Fold 5
Running time: 0.2 sec
OOF RMSE: 2.67 | R2: 0.41
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.69 | R2: 0.40
Fold 1
Fold 2
Fold 3

[I 2025-07-11 17:21:04,733] Trial 10 finished with value: -0.00027817151752640434 and parameters: {'alpha': 7.606110965825775, 'l1_ratio': 0.9260734162958602}. Best is trial 6 with value: 0.4256170712722742.
[I 2025-07-11 17:21:04,831] Trial 11 finished with value: 0.4227828398792781 and parameters: {'alpha': 0.2592578039012334, 'l1_ratio': 0.770194121584354}. Best is trial 6 with value: 0.4256170712722742.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.47 | R2: -0.00
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.63 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 17:21:04,921] Trial 12 finished with value: 0.427546243871184 and parameters: {'alpha': 0.3220459814508188, 'l1_ratio': 0.2982520235866915}. Best is trial 12 with value: 0.427546243871184.
[I 2025-07-11 17:21:05,019] Trial 13 finished with value: 0.42223775954299947 and parameters: {'alpha': 1.4212509483234355, 'l1_ratio': 0.3065724610150002}. Best is trial 12 with value: 0.427546243871184.

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.62 | R2: 0.43
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.63 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:21:05,120] Trial 14 finished with value: 0.4201594605437472 and parameters: {'alpha': 1.0577815183790127, 'l1_ratio': 0.654580652508741}. Best is trial 12 with value: 0.427546243871184.
[I 2025-07-11 17:21:05,248] Trial 15 finished with value: 0.23704235426966724 and parameters: {'alpha': 7.915923326465116, 'l1_ratio': 0.2579076338547998}. Best is trial 12 with value: 0.427546243871184.

Running time: 0.1 sec
OOF RMSE: 2.64 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.03 | R2: 0.24
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 17:21:05,357] Trial 16 finished with value: 0.41947828220744376 and parameters: {'alpha': 0.038685563290011805, 'l1_ratio': 0.9793001434852047}. Best is trial 12 with value: 0.427546243871184.
[I 2025-07-11 17:21:05,485] Trial 17 finished with value: 0.4240473065874617 and parameters: {'alpha': 0.2831678025206545, 'l1_ratio': 0.7836791439765679}. Best is trial 12 with value: 0.427546243871184.

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.64 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.63 | R2: 0.42
Fold 1
Fold 2

[I 2025-07-11 17:21:05,623] Trial 18 finished with value: 0.42564054109634253 and parameters: {'alpha': 0.7734626259971726, 'l1_ratio': 0.23926517503161515}. Best is trial 12 with value: 0.427546243871184.
[I 2025-07-11 17:21:05,755] Trial 19 finished with value: 0.41545813181623437 and parameters: {'alpha': 0.08479280438970077, 'l1_ratio': 0.21249546748907283}. Best is trial 12 with value: 0.427546243871184.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.63 | R2: 0.43
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.65 | R2: 0.42

[I 2025-07-11 17:21:05,858] Trial 20 finished with value: 0.3153806682335012 and parameters: {'alpha': 4.342937365278308, 'l1_ratio': 0.38304545202728035}. Best is trial 12 with value: 0.427546243871184.
[I 2025-07-11 17:21:05,966] Trial 21 finished with value: 0.42926146852697855 and parameters: {'alpha': 0.5852246372071594, 'l1_ratio': 0.18267486333733565}. Best is trial 21 with value: 0.42926146852697855.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.87 | R2: 0.32
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.62 | R2: 0.43

[I 2025-07-11 17:21:06,074] Trial 22 finished with value: 0.4286626283392265 and parameters: {'alpha': 0.3015558500837444, 'l1_ratio': 0.21816270462979667}. Best is trial 21 with value: 0.42926146852697855.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.62 | R2: 0.43
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:21:06,185] Trial 23 finished with value: 0.42086718353433916 and parameters: {'alpha': 0.1334961853574984, 'l1_ratio': 0.14711203416087648}. Best is trial 21 with value: 0.42926146852697855.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.151e+01, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.150e+01, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.735e+00, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.812e+01, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.095e-01, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 17:21:06,327] Trial 24 finished with value: 0.4039383421501346 and parameters: {'alpha': 0.017867296149265674, 'l1_ratio': 0.33410787294852656}. Best is trial 21 with value: 0.42926146852697855.
[I 2025-07-11 17:21:06,329] A new study created in memory with name: no-name-272df5b5-2d8b-474f-bff4-da545a781ccb

Running time: 0.1 sec
OOF RMSE: 2.64 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.68 | R2: 0.40

✅ EN - Mejor R2: 0.43
📋 Parámetros: {'alpha': 0.5852246372071594, 'l1_ratio': 0.18267486333733565}

🔍 Optimizando en C2RCC_rhow_9x9_depth_lt_1...
Buscando mejores hiperparámetros para XGB...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:21:09,993] Trial 0 finished with value: 0.621603231558853 and parameters: {'n_estimators': 1000, 'learning_rate': 0.0994839865614177, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.8804574421178255, 'colsample_bytree': 0.7889719711698322}. Best is trial 0 with value: 0.621603231558853.

Running time: 3.7 sec
OOF RMSE: 2.13 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:21:12,767] Trial 1 finished with value: 0.6364759172353127 and parameters: {'n_estimators': 500, 'learning_rate': 0.021460185679933536, 'max_depth': 5, 'min_child_weight': 1, 'subsample': 0.873420074212055, 'colsample_bytree': 0.818379206291999}. Best is trial 1 with value: 0.6364759172353127.

Running time: 2.8 sec
OOF RMSE: 2.09 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:21:16,115] Trial 2 finished with value: 0.5512191591595261 and parameters: {'n_estimators': 500, 'learning_rate': 0.07012421009458922, 'max_depth': 8, 'min_child_weight': 4, 'subsample': 0.6502162230276783, 'colsample_bytree': 0.9373244381671307}. Best is trial 1 with value: 0.6364759172353127.

Running time: 3.3 sec
OOF RMSE: 2.32 | R2: 0.55
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:21:24,080] Trial 3 finished with value: 0.6200465348416699 and parameters: {'n_estimators': 1000, 'learning_rate': 0.009901004039689656, 'max_depth': 8, 'min_child_weight': 2, 'subsample': 0.7340239600437244, 'colsample_bytree': 0.688612190276296}. Best is trial 1 with value: 0.6364759172353127.

Running time: 8.0 sec
OOF RMSE: 2.14 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:21:26,758] Trial 4 finished with value: 0.6038120015137456 and parameters: {'n_estimators': 500, 'learning_rate': 0.055343437367440185, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.6251723464458618, 'colsample_bytree': 0.9105260282809879}. Best is trial 1 with value: 0.6364759172353127.

Running time: 2.7 sec
OOF RMSE: 2.18 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:21:46,683] Trial 5 finished with value: 0.6330709754808288 and parameters: {'n_estimators': 2000, 'learning_rate': 0.006415774267646745, 'max_depth': 8, 'min_child_weight': 1, 'subsample': 0.8459439485032346, 'colsample_bytree': 0.8035627878647542}. Best is trial 1 with value: 0.6364759172353127.

Running time: 19.9 sec
OOF RMSE: 2.10 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:21:53,855] Trial 6 finished with value: 0.5812337710081403 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01262576893910161, 'max_depth': 8, 'min_child_weight': 4, 'subsample': 0.7554741542256758, 'colsample_bytree': 0.7640983540743356}. Best is trial 1 with value: 0.6364759172353127.

Running time: 7.2 sec
OOF RMSE: 2.24 | R2: 0.58
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:21:59,472] Trial 7 finished with value: 0.6239457383911222 and parameters: {'n_estimators': 500, 'learning_rate': 0.028253182021646388, 'max_depth': 8, 'min_child_weight': 1, 'subsample': 0.7482283702102552, 'colsample_bytree': 0.8438092505766762}. Best is trial 1 with value: 0.6364759172353127.

Running time: 5.6 sec
OOF RMSE: 2.13 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:22:06,837] Trial 8 finished with value: 0.6160092684925442 and parameters: {'n_estimators': 2000, 'learning_rate': 0.06886136102608724, 'max_depth': 8, 'min_child_weight': 2, 'subsample': 0.8829982469518923, 'colsample_bytree': 0.6361306418592804}. Best is trial 1 with value: 0.6364759172353127.

Running time: 7.4 sec
OOF RMSE: 2.15 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:22:14,089] Trial 9 finished with value: 0.6138247473677363 and parameters: {'n_estimators': 1000, 'learning_rate': 0.020057536618280348, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.9105699712168568, 'colsample_bytree': 0.8669119630919997}. Best is trial 1 with value: 0.6364759172353127.

Running time: 7.2 sec
OOF RMSE: 2.15 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:22:18,138] Trial 10 finished with value: 0.61213490474017 and parameters: {'n_estimators': 500, 'learning_rate': 0.030911799977968012, 'max_depth': 6, 'min_child_weight': 1, 'subsample': 0.9549738380877482, 'colsample_bytree': 0.9998296558844048}. Best is trial 1 with value: 0.6364759172353127.

Running time: 4.0 sec
OOF RMSE: 2.16 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:22:34,480] Trial 11 finished with value: 0.631766367120732 and parameters: {'n_estimators': 2000, 'learning_rate': 0.00520115359221458, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.8273579005537584, 'colsample_bytree': 0.7316432513529574}. Best is trial 1 with value: 0.6364759172353127.

Running time: 16.3 sec
OOF RMSE: 2.10 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:22:51,607] Trial 12 finished with value: 0.6286435749468643 and parameters: {'n_estimators': 2000, 'learning_rate': 0.005069069197843316, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.8366910544475727, 'colsample_bytree': 0.840271545640482}. Best is trial 1 with value: 0.6364759172353127.

Running time: 17.1 sec
OOF RMSE: 2.11 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:23:02,985] Trial 13 finished with value: 0.5929804375195933 and parameters: {'n_estimators': 2000, 'learning_rate': 0.009722481477382564, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.9937677496365503, 'colsample_bytree': 0.6992559520564116}. Best is trial 1 with value: 0.6364759172353127.

Running time: 11.4 sec
OOF RMSE: 2.21 | R2: 0.59
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:23:06,899] Trial 14 finished with value: 0.6333972882196284 and parameters: {'n_estimators': 500, 'learning_rate': 0.01658990876618808, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.8006263248943599, 'colsample_bytree': 0.8227319277085229}. Best is trial 1 with value: 0.6364759172353127.

Running time: 3.9 sec
OOF RMSE: 2.10 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:23:11,079] Trial 15 finished with value: 0.6265567570180187 and parameters: {'n_estimators': 500, 'learning_rate': 0.017804338436761213, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.7772669245688076, 'colsample_bytree': 0.8962905830655435}. Best is trial 1 with value: 0.6364759172353127.

Running time: 4.2 sec
OOF RMSE: 2.12 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:23:13,594] Trial 16 finished with value: 0.5826554714878203 and parameters: {'n_estimators': 500, 'learning_rate': 0.043797744389304984, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.7096073334143523, 'colsample_bytree': 0.9713289312558668}. Best is trial 1 with value: 0.6364759172353127.

Running time: 2.5 sec
OOF RMSE: 2.24 | R2: 0.58
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:23:16,460] Trial 17 finished with value: 0.6187891911174921 and parameters: {'n_estimators': 500, 'learning_rate': 0.014787284147693267, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.6926666533739135, 'colsample_bytree': 0.8160587036796352}. Best is trial 1 with value: 0.6364759172353127.

Running time: 2.9 sec
OOF RMSE: 2.14 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:23:20,415] Trial 18 finished with value: 0.6444636050148718 and parameters: {'n_estimators': 500, 'learning_rate': 0.030745077375263705, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.8042059735991965, 'colsample_bytree': 0.7511243939675886}. Best is trial 18 with value: 0.6444636050148718.

Running time: 4.0 sec
OOF RMSE: 2.07 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:23:22,828] Trial 19 finished with value: 0.6212213180490465 and parameters: {'n_estimators': 500, 'learning_rate': 0.030150759406887013, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.9382151936063785, 'colsample_bytree': 0.6324833043458957}. Best is trial 18 with value: 0.6444636050148718.

Running time: 2.4 sec
OOF RMSE: 2.13 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:23:26,289] Trial 20 finished with value: 0.6321548941638866 and parameters: {'n_estimators': 500, 'learning_rate': 0.04051135616353308, 'max_depth': 6, 'min_child_weight': 1, 'subsample': 0.8847953022969607, 'colsample_bytree': 0.7608913653024725}. Best is trial 18 with value: 0.6444636050148718.

Running time: 3.5 sec
OOF RMSE: 2.10 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:23:30,165] Trial 21 finished with value: 0.636192729810373 and parameters: {'n_estimators': 500, 'learning_rate': 0.024248426374749697, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.7994894887045577, 'colsample_bytree': 0.7365247276910496}. Best is trial 18 with value: 0.6444636050148718.

Running time: 3.9 sec
OOF RMSE: 2.09 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:23:33,980] Trial 22 finished with value: 0.620207886939212 and parameters: {'n_estimators': 500, 'learning_rate': 0.02267297345331927, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.8034162269841622, 'colsample_bytree': 0.7111901868716433}. Best is trial 18 with value: 0.6444636050148718.

Running time: 3.8 sec
OOF RMSE: 2.14 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:23:37,962] Trial 23 finished with value: 0.6174929867025332 and parameters: {'n_estimators': 500, 'learning_rate': 0.024066239096499367, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.8540354535482615, 'colsample_bytree': 0.6671330726615443}. Best is trial 18 with value: 0.6444636050148718.

Running time: 4.0 sec
OOF RMSE: 2.14 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:23:41,308] Trial 24 finished with value: 0.6322350804498534 and parameters: {'n_estimators': 500, 'learning_rate': 0.03863564309228118, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.7881444704243846, 'colsample_bytree': 0.7565903021237778}. Best is trial 18 with value: 0.6444636050148718.
[I 2025-07-11 17:23:41,309] A new study created in memory with name: no-name-4bebc252-0cb2-41c1-89aa-46f75345760c

Running time: 3.3 sec
OOF RMSE: 2.10 | R2: 0.63

✅ XGB - Mejor R2: 0.64
📋 Parámetros: {'n_estimators': 500, 'learning_rate': 0.030745077375263705, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.8042059735991965, 'colsample_bytree': 0.7511243939675886}

Buscando mejores hiperparámetros para LBM...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:23:42,376] Trial 0 finished with value: 0.4773891621103996 and parameters: {'learning_rate': 0.029886737521125462, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 8, 'subsample': 0.6638500028036205, 'colsample_bytree': 0.6885269019631708, 'n_estimators': 2000}. Best is trial 0 with value: 0.4773891621103996.

Running time: 1.1 sec
OOF RMSE: 2.51 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 17:23:43,207] Trial 1 finished with value: 0.4135125899315074 and parameters: {'learning_rate': 0.08625111767562656, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 17, 'subsample': 0.6357742472933154, 'colsample_bytree': 0.8582680267515186, 'n_estimators': 2000}. Best is trial 0 with value: 0.4773891621103996.

Fold 5
Running time: 0.8 sec
OOF RMSE: 2.65 | R2: 0.41
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 17:23:43,629] Trial 2 finished with value: 0.5069241967462852 and parameters: {'learning_rate': 0.07858053622215633, 'num_leaves': 40, 'max_depth': 5, 'min_child_samples': 13, 'subsample': 0.7613720244357808, 'colsample_bytree': 0.8753009168001114, 'n_estimators': 1000}. Best is trial 2 with value: 0.5069241967462852.

Fold 5
Running time: 0.4 sec
OOF RMSE: 2.43 | R2: 0.51
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:23:44,049] Trial 3 finished with value: 0.4993629754972917 and parameters: {'learning_rate': 0.006578666160017835, 'num_leaves': 60, 'max_depth': 5, 'min_child_samples': 11, 'subsample': 0.8644180772250303, 'colsample_bytree': 0.790603477586719, 'n_estimators': 1000}. Best is trial 2 with value: 0.5069241967462852.

Running time: 0.4 sec
OOF RMSE: 2.45 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 17:23:44,822] Trial 4 finished with value: 0.4737520058320962 and parameters: {'learning_rate': 0.010088335383023941, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 14, 'subsample': 0.6943374546578008, 'colsample_bytree': 0.7021644387504168, 'n_estimators': 2000}. Best is trial 2 with value: 0.5069241967462852.

Fold 5
Running time: 0.8 sec
OOF RMSE: 2.51 | R2: 0.47
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:23:45,911] Trial 5 finished with value: 0.4765621200668835 and parameters: {'learning_rate': 0.012157770168494706, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 9, 'subsample': 0.8134128051897896, 'colsample_bytree': 0.7991962308275484, 'n_estimators': 2000}. Best is trial 2 with value: 0.5069241967462852.

Running time: 1.1 sec
OOF RMSE: 2.51 | R2: 0.48
Fold 1
Fold 2
Fold 3

[I 2025-07-11 17:23:46,275] Trial 6 finished with value: 0.5361897008189089 and parameters: {'learning_rate': 0.006244282517130954, 'num_leaves': 80, 'max_depth': 8, 'min_child_samples': 9, 'subsample': 0.8050532136263763, 'colsample_bytree': 0.6222669538632591, 'n_estimators': 500}. Best is trial 6 with value: 0.5361897008189089.

Fold 4
Fold 5
Running time: 0.4 sec
OOF RMSE: 2.36 | R2: 0.54
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:23:47,505] Trial 7 finished with value: 0.41167071513192577 and parameters: {'learning_rate': 0.09515451668347409, 'num_leaves': 40, 'max_depth': 8, 'min_child_samples': 14, 'subsample': 0.9342853874737399, 'colsample_bytree': 0.8846873962716646, 'n_estimators': 2000}. Best is trial 6 with value: 0.5361897008189089.

Running time: 1.2 sec
OOF RMSE: 2.66 | R2: 0.41
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:23:48,603] Trial 8 finished with value: 0.5006931547369959 and parameters: {'learning_rate': 0.006582713740206957, 'num_leaves': 60, 'max_depth': 8, 'min_child_samples': 17, 'subsample': 0.8143871047748782, 'colsample_bytree': 0.7548508496990107, 'n_estimators': 2000}. Best is trial 6 with value: 0.5361897008189089.

Running time: 1.1 sec
OOF RMSE: 2.45 | R2: 0.50
Fold 1
Fold 2
Fold 3

[I 2025-07-11 17:23:48,990] Trial 9 finished with value: 0.47027564581256476 and parameters: {'learning_rate': 0.011490513151937814, 'num_leaves': 80, 'max_depth': 5, 'min_child_samples': 15, 'subsample': 0.6776154518743364, 'colsample_bytree': 0.6237686952505429, 'n_estimators': 1000}. Best is trial 6 with value: 0.5361897008189089.

Fold 4
Fold 5
Running time: 0.4 sec
OOF RMSE: 2.52 | R2: 0.47
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:23:49,275] Trial 10 finished with value: 0.521247070310267 and parameters: {'learning_rate': 0.02801799807192451, 'num_leaves': 80, 'max_depth': 8, 'min_child_samples': 23, 'subsample': 0.997464580087877, 'colsample_bytree': 0.999245267352491, 'n_estimators': 500}. Best is trial 6 with value: 0.5361897008189089.

Running time: 0.3 sec
OOF RMSE: 2.40 | R2: 0.52
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 17:23:49,541] Trial 11 finished with value: 0.5422790600943588 and parameters: {'learning_rate': 0.03153212248036586, 'num_leaves': 80, 'max_depth': 8, 'min_child_samples': 25, 'subsample': 0.9579939322889638, 'colsample_bytree': 0.998643848936765, 'n_estimators': 500}. Best is trial 11 with value: 0.5422790600943588.

Fold 5
Running time: 0.3 sec
OOF RMSE: 2.35 | R2: 0.54
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:23:49,913] Trial 12 finished with value: 0.45120509222772187 and parameters: {'learning_rate': 0.043958800778055314, 'num_leaves': 80, 'max_depth': 7, 'min_child_samples': 5, 'subsample': 0.9039818808565085, 'colsample_bytree': 0.9733282332016783, 'n_estimators': 500}. Best is trial 11 with value: 0.5422790600943588.

Running time: 0.4 sec
OOF RMSE: 2.57 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:23:50,148] Trial 13 finished with value: 0.5376316043158531 and parameters: {'learning_rate': 0.01808416793459333, 'num_leaves': 80, 'max_depth': 6, 'min_child_samples': 25, 'subsample': 0.9997059200085806, 'colsample_bytree': 0.603894104534038, 'n_estimators': 500}. Best is trial 11 with value: 0.5422790600943588.

Running time: 0.2 sec
OOF RMSE: 2.36 | R2: 0.54
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 17:23:50,406] Trial 14 finished with value: 0.5308671913492559 and parameters: {'learning_rate': 0.01746866099783546, 'num_leaves': 80, 'max_depth': 6, 'min_child_samples': 25, 'subsample': 0.9962658064425111, 'colsample_bytree': 0.9373581272760863, 'n_estimators': 500}. Best is trial 11 with value: 0.5422790600943588.

Fold 5
Running time: 0.3 sec
OOF RMSE: 2.37 | R2: 0.53
Fold 1
Fold 2
Fold 3

[I 2025-07-11 17:23:50,657] Trial 15 finished with value: 0.5331350170645222 and parameters: {'learning_rate': 0.04721178353657509, 'num_leaves': 80, 'max_depth': 6, 'min_child_samples': 21, 'subsample': 0.957084430406341, 'colsample_bytree': 0.7128742837617014, 'n_estimators': 500}. Best is trial 11 with value: 0.5422790600943588.

Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 2.37 | R2: 0.53
Fold 1
Fold 2

[I 2025-07-11 17:23:50,926] Trial 16 finished with value: 0.48971744235514203 and parameters: {'learning_rate': 0.019054316503901277, 'num_leaves': 80, 'max_depth': 6, 'min_child_samples': 20, 'subsample': 0.8844324919363171, 'colsample_bytree': 0.9307597553102595, 'n_estimators': 500}. Best is trial 11 with value: 0.5422790600943588.

Fold 3
Fold 4
Fold 5
Running time: 0.3 sec
OOF RMSE: 2.48 | R2: 0.49
Fold 1

[I 2025-07-11 17:23:51,174] Trial 17 finished with value: 0.5500419427436437 and parameters: {'learning_rate': 0.04405372538922755, 'num_leaves': 80, 'max_depth': 7, 'min_child_samples': 25, 'subsample': 0.9482342769195646, 'colsample_bytree': 0.6529119045727767, 'n_estimators': 500}. Best is trial 17 with value: 0.5500419427436437.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 2.33 | R2: 0.55
Fold 1

[I 2025-07-11 17:23:51,445] Trial 18 finished with value: 0.5254462382434331 and parameters: {'learning_rate': 0.05220736330315401, 'num_leaves': 60, 'max_depth': 7, 'min_child_samples': 21, 'subsample': 0.9353639723139173, 'colsample_bytree': 0.6631552363745453, 'n_estimators': 500}. Best is trial 17 with value: 0.5500419427436437.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.3 sec
OOF RMSE: 2.39 | R2: 0.53
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 17:23:51,750] Trial 19 finished with value: 0.5144303370446803 and parameters: {'learning_rate': 0.03548729642652684, 'num_leaves': 40, 'max_depth': 8, 'min_child_samples': 18, 'subsample': 0.8463029295835434, 'colsample_bytree': 0.747158159502833, 'n_estimators': 500}. Best is trial 17 with value: 0.5500419427436437.

Fold 5
Running time: 0.3 sec
OOF RMSE: 2.42 | R2: 0.51
Fold 1
Fold 2
Fold 3

[I 2025-07-11 17:23:52,049] Trial 20 finished with value: 0.5056892386186937 and parameters: {'learning_rate': 0.06197243506084663, 'num_leaves': 80, 'max_depth': 7, 'min_child_samples': 23, 'subsample': 0.7435576919797376, 'colsample_bytree': 0.8266790367359109, 'n_estimators': 500}. Best is trial 17 with value: 0.5500419427436437.

Fold 4
Fold 5
Running time: 0.3 sec
OOF RMSE: 2.44 | R2: 0.51
Fold 1
Fold 2

[I 2025-07-11 17:23:52,294] Trial 21 finished with value: 0.5444588845205975 and parameters: {'learning_rate': 0.02418914555709243, 'num_leaves': 80, 'max_depth': 6, 'min_child_samples': 25, 'subsample': 0.9554742243336592, 'colsample_bytree': 0.6104257623485481, 'n_estimators': 500}. Best is trial 17 with value: 0.5500419427436437.

Fold 3
Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 2.34 | R2: 0.54
Fold 1
Fold 2

[I 2025-07-11 17:23:52,552] Trial 22 finished with value: 0.5271720857066406 and parameters: {'learning_rate': 0.026386841558787708, 'num_leaves': 80, 'max_depth': 6, 'min_child_samples': 23, 'subsample': 0.9435812705066042, 'colsample_bytree': 0.6459191586112943, 'n_estimators': 500}. Best is trial 17 with value: 0.5500419427436437.

Fold 3
Fold 4
Fold 5
Running time: 0.3 sec
OOF RMSE: 2.38 | R2: 0.53
Fold 1

[I 2025-07-11 17:23:52,793] Trial 23 finished with value: 0.5497417756742953 and parameters: {'learning_rate': 0.03436929788893177, 'num_leaves': 80, 'max_depth': 7, 'min_child_samples': 25, 'subsample': 0.9015159646992438, 'colsample_bytree': 0.6597567392626819, 'n_estimators': 500}. Best is trial 17 with value: 0.5500419427436437.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 2.33 | R2: 0.55
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:23:53,081] Trial 24 finished with value: 0.506619915844732 and parameters: {'learning_rate': 0.03907199588717175, 'num_leaves': 80, 'max_depth': 7, 'min_child_samples': 19, 'subsample': 0.9040336035846357, 'colsample_bytree': 0.6719673868109265, 'n_estimators': 500}. Best is trial 17 with value: 0.5500419427436437.
[I 2025-07-11 17:23:53,082] A new study created in memory with name: no-name-d4d68112-87ca-451d-951a-b21655c87be8

Running time: 0.3 sec
OOF RMSE: 2.43 | R2: 0.51

✅ LBM - Mejor R2: 0.55
📋 Parámetros: {'learning_rate': 0.04405372538922755, 'num_leaves': 80, 'max_depth': 7, 'min_child_samples': 25, 'subsample': 0.9482342769195646, 'colsample_bytree': 0.6529119045727767, 'n_estimators': 500}

Buscando mejores hiperparámetros para MLP...
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 17:23:54,465] Trial 0 finished with value: 0.5547928155507553 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.0008150430218423266, 'learning_rate': 'constant', 'learning_rate_init': 0.0033602225639971497}. Best is trial 0 with value: 0.5547928155507553.

Running time: 1.4 sec
OOF RMSE: 2.31 | R2: 0.55
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:23:56,094] Trial 1 finished with value: 0.5208403088120365 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0022610195194571925, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0009678467024715508}. Best is trial 0 with value: 0.5547928155507553.

Running time: 1.6 sec
OOF RMSE: 2.40 | R2: 0.52
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 17:23:57,915] Trial 2 finished with value: 0.5864238252112229 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'sgd', 'alpha': 1.3735421679763306e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.008407428962200763}. Best is trial 2 with value: 0.5864238252112229.

Running time: 1.8 sec
OOF RMSE: 2.23 | R2: 0.59
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 17:23:59,590] Trial 3 finished with value: 0.35008025629651796 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 4.180523217152712e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0001751533790675157}. Best is trial 2 with value: 0.5864238252112229.

Running time: 1.7 sec
OOF RMSE: 2.79 | R2: 0.35
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 17:24:00,555] Trial 4 finished with value: 0.43062181740590666 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'relu', 'solver': 'sgd', 'alpha': 1.2270099272905115e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.0006251944351504291}. Best is trial 2 with value: 0.5864238252112229.

Fold 4
Fold 5
Running time: 1.0 sec
OOF RMSE: 2.62 | R2: 0.43
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 17:24:01,056] Trial 5 finished with value: 0.3867198175461012 and parameters: {'hidden_layer_sizes': '50', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.006536381124260303, 'learning_rate': 'constant', 'learning_rate_init': 0.00011970619639216946}. Best is trial 2 with value: 0.5864238252112229.

Fold 4
Fold 5
Running time: 0.5 sec
OOF RMSE: 2.71 | R2: 0.39
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 17:24:02,627] Trial 6 finished with value: 0.4745876227321272 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.00015976608317444388, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00016561046795600403}. Best is trial 2 with value: 0.5864238252112229.

Running time: 1.6 sec
OOF RMSE: 2.51 | R2: 0.47
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:24:03,936] Trial 7 finished with value: 0.557350177109929 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.007477664904688385, 'learning_rate': 'constant', 'learning_rate_init': 0.000676663648919431}. Best is trial 2 with value: 0.5864238252112229.

Running time: 1.3 sec
OOF RMSE: 2.31 | R2: 0.56
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 17:24:05,452] Trial 8 finished with value: 0.5318270294829814 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.002226845362782859, 'learning_rate': 'constant', 'learning_rate_init': 0.0023864739589621723}. Best is trial 2 with value: 0.5864238252112229.

Running time: 1.5 sec
OOF RMSE: 2.37 | R2: 0.53
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 17:24:05,892] Trial 9 finished with value: 0.41185400871861244 and parameters: {'hidden_layer_sizes': '50', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.042697636204193166, 'learning_rate': 'constant', 'learning_rate_init': 0.00404850793451975}. Best is trial 2 with value: 0.5864238252112229.

Fold 5
Running time: 0.4 sec
OOF RMSE: 2.66 | R2: 0.41
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:24:06,458] Trial 10 finished with value: 0.6490654760594676 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.00018774819440246876, 'learning_rate': 'adaptive', 'learning_rate_init': 0.009661697868037085}. Best is trial 10 with value: 0.6490654760594676.

Running time: 0.6 sec
OOF RMSE: 2.05 | R2: 0.65
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 17:24:06,981] Trial 11 finished with value: 0.6348130788087802 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.00012977485647411882, 'learning_rate': 'adaptive', 'learning_rate_init': 0.009823718487725296}. Best is trial 10 with value: 0.6490654760594676.

Fold 5
Running time: 0.5 sec
OOF RMSE: 2.09 | R2: 0.63
Fold 1
Fold 2
Fold 3

[I 2025-07-11 17:24:07,567] Trial 12 finished with value: 0.6368444839337972 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.00021581983640776826, 'learning_rate': 'adaptive', 'learning_rate_init': 0.007430600153626327}. Best is trial 10 with value: 0.6490654760594676.

Fold 4
Fold 5
Running time: 0.6 sec
OOF RMSE: 2.09 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 17:24:08,182] Trial 13 finished with value: 0.6100619243459446 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.00029198838474808617, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0050921433544952755}. Best is trial 10 with value: 0.6490654760594676.

Fold 5
Running time: 0.6 sec
OOF RMSE: 2.16 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:24:08,962] Trial 14 finished with value: 0.5672458880706517 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0005210225445032822, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0013962352165339785}. Best is trial 10 with value: 0.6490654760594676.

Running time: 0.8 sec
OOF RMSE: 2.28 | R2: 0.57
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:24:09,564] Trial 15 finished with value: 0.6362020533019176 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 5.6599497642115183e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.006360598907783893}. Best is trial 10 with value: 0.6490654760594676.

Running time: 0.6 sec
OOF RMSE: 2.09 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:24:10,375] Trial 16 finished with value: 0.5570007165286297 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 4.713802321808732e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.002018492789888059}. Best is trial 10 with value: 0.6490654760594676.

Running time: 0.8 sec
OOF RMSE: 2.31 | R2: 0.56
Fold 1
Fold 2
Fold 3

[I 2025-07-11 17:24:10,823] Trial 17 finished with value: 0.3307274458862034 and parameters: {'hidden_layer_sizes': '50', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.00018913053523019, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00044696764834002185}. Best is trial 10 with value: 0.6490654760594676.

Fold 4
Fold 5
Running time: 0.4 sec
OOF RMSE: 2.84 | R2: 0.33
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:24:11,842] Trial 18 finished with value: 0.5262379957979029 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.09389494834659967, 'learning_rate': 'adaptive', 'learning_rate_init': 0.003156263218084026}. Best is trial 10 with value: 0.6490654760594676.

Running time: 1.0 sec
OOF RMSE: 2.39 | R2: 0.53
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 17:24:12,420] Trial 19 finished with value: 0.5992639332055397 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0020593815683322934, 'learning_rate': 'adaptive', 'learning_rate_init': 0.005438583281161704}. Best is trial 10 with value: 0.6490654760594676.

Fold 5
Running time: 0.6 sec
OOF RMSE: 2.19 | R2: 0.60
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 17:24:13,818] Trial 20 finished with value: 0.4934614591886558 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.00044173638141584013, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00031090519779782184}. Best is trial 10 with value: 0.6490654760594676.

Fold 5
Running time: 1.4 sec
OOF RMSE: 2.47 | R2: 0.49
Fold 1
Fold 2
Fold 3

[I 2025-07-11 17:24:14,400] Trial 21 finished with value: 0.642909561612463 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 4.7637738169725227e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.006686205004102845}. Best is trial 10 with value: 0.6490654760594676.

Fold 4
Fold 5
Running time: 0.6 sec
OOF RMSE: 2.07 | R2: 0.64
Fold 1
Fold 2
Fold 3

[I 2025-07-11 17:24:14,961] Trial 22 finished with value: 0.6318222490833227 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 7.711400392035488e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.007370308281053394}. Best is trial 10 with value: 0.6490654760594676.

Fold 4
Fold 5
Running time: 0.6 sec
OOF RMSE: 2.10 | R2: 0.63
Fold 1
Fold 2
Fold 3

[I 2025-07-11 17:24:15,544] Trial 23 finished with value: 0.6049298412489201 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 2.1158751534221536e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.004934472039748571}. Best is trial 10 with value: 0.6490654760594676.

Fold 4
Fold 5
Running time: 0.6 sec
OOF RMSE: 2.18 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:24:16,059] Trial 24 finished with value: 0.6364632768411602 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 2.4952256217745775e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.009766209090869619}. Best is trial 10 with value: 0.6490654760594676.
[I 2025-07-11 17:24:16,061] A new study created in memory with name: no-name-da85c122-b929-4121-9e2e-c870a7d82caf
[I 2025-07-11 17:24:16,146] Trial 0 finished with value: 0.14388161295267488 and parameters: {'kernel': 'rbf', 'C': 0.22912394717058532, 'epsilon': 0.11939099477462367, 'gamma': 'auto'}. Best is trial 0 with value: 0.14388161295267488.
[I 2025-07-11 17:24:16,207] Trial 1 finished with value: 0.15562798434914205 and parameters: {'kernel': 'rbf', 'C': 0.25575231697731504, 'epsilon': 0.19236041017293457, 'gamma': 'auto'}. Best is trial 1 with value: 0.15562798434914205.

Running time: 0.5 sec
OOF RMSE: 2.09 | R2: 0.64

✅ MLP - Mejor R2: 0.65
📋 Parámetros: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.00018774819440246876, 'learning_rate': 'adaptive', 'learning_rate_init': 0.009661697868037085}

Buscando mejores hiperparámetros para SVR...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.21 | R2: 0.14
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.19 | R2: 0.16
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 17:24:16,278] Trial 2 finished with value: -16.08183650102267 and parameters: {'kernel': 'sigmoid', 'C': 2.2357423356485917, 'epsilon': 0.08923188441212004, 'gamma': 'scale'}. Best is trial 1 with value: 0.15562798434914205.
[I 2025-07-11 17:24:16,355] Trial 3 finished with value: 0.3870222580927569 and parameters: {'kernel': 'rbf', 'C': 2.3198190596528594, 'epsilon': 0.020511463226066257, 'gamma': 'scale'}. Best is trial 3 with value: 0.3870222580927569.
[I 2025-07-11 17:24:16,424] Trial 4 finished with value: 0.5739648299789206 and parameters: {'kernel': 'rbf', 'C': 7.079648974375442, 'epsilon': 0.12082192280303952, 'gamma': 'scale'}. Best is trial 4 with value: 0.5739648299789206.

Fold 5
Running time: 0.1 sec
OOF RMSE: 14.33 | R2: -16.08
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.71 | R2: 0.39
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.26 | R2: 0.57
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 17:24:16,490] Trial 5 finished with value: 0.4513333273829848 and parameters: {'kernel': 'rbf', 'C': 4.098039138684656, 'epsilon': 0.1752210689747662, 'gamma': 'auto'}. Best is trial 4 with value: 0.5739648299789206.
[I 2025-07-11 17:24:16,584] Trial 6 finished with value: -0.24811675770016595 and parameters: {'kernel': 'sigmoid', 'C': 0.25681746518254134, 'epsilon': 0.062237057640462896, 'gamma': 'scale'}. Best is trial 4 with value: 0.5739648299789206.
[I 2025-07-11 17:24:16,653] Trial 7 finished with value: 0.5705036188817931 and parameters: {'kernel': 'rbf', 'C': 6.910950191255495, 'epsilon': 0.16740217812579924, 'gamma': 'scale'}. Best is trial 4 with value: 0.5739648299789206.

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.57 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.87 | R2: -0.25
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.27 | R2: 0.57
Fold 1
Fold 2

[I 2025-07-11 17:24:16,722] Trial 8 finished with value: 0.10997370853424815 and parameters: {'kernel': 'rbf', 'C': 0.13893539219663076, 'epsilon': 0.1598146245098142, 'gamma': 'scale'}. Best is trial 4 with value: 0.5739648299789206.
[I 2025-07-11 17:24:16,794] Trial 9 finished with value: 0.33144112838569495 and parameters: {'kernel': 'rbf', 'C': 1.5453833550796976, 'epsilon': 0.1307435722767675, 'gamma': 'scale'}. Best is trial 4 with value: 0.5739648299789206.
[I 2025-07-11 17:24:16,871] Trial 10 finished with value: -0.6982331319043207 and parameters: {'kernel': 'sigmoid', 'C': 0.6109685954745923, 'epsilon': 0.07256720040523743, 'gamma': 'auto'}. Best is trial 4 with value: 0.5739648299789206.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.27 | R2: 0.11
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.83 | R2: 0.33
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 4.52 | R2: -0.70
Fold 1

[I 2025-07-11 17:24:16,951] Trial 11 finished with value: 0.5959200444017888 and parameters: {'kernel': 'rbf', 'C': 8.885586086144363, 'epsilon': 0.14593160294540042, 'gamma': 'scale'}. Best is trial 11 with value: 0.5959200444017888.
[I 2025-07-11 17:24:17,026] Trial 12 finished with value: 0.5883949104564344 and parameters: {'kernel': 'rbf', 'C': 7.954154612654373, 'epsilon': 0.13825917044296057, 'gamma': 'scale'}. Best is trial 11 with value: 0.5959200444017888.
[I 2025-07-11 17:24:17,099] Trial 13 finished with value: 0.5988876884756753 and parameters: {'kernel': 'rbf', 'C': 9.368015046738579, 'epsilon': 0.14260568400950718, 'gamma': 'scale'}. Best is trial 13 with value: 0.5988876884756753.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.20 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.22 | R2: 0.59
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.20 | R2: 0.60

[I 2025-07-11 17:24:17,177] Trial 14 finished with value: -285.0264610368243 and parameters: {'kernel': 'sigmoid', 'C': 9.858396081352883, 'epsilon': 0.15169976812362213, 'gamma': 'scale'}. Best is trial 13 with value: 0.5988876884756753.
[I 2025-07-11 17:24:17,252] Trial 15 finished with value: 0.48129007235251176 and parameters: {'kernel': 'rbf', 'C': 3.836432688481547, 'epsilon': 0.10027131046266285, 'gamma': 'scale'}. Best is trial 13 with value: 0.5988876884756753.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 58.63 | R2: -285.03
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.50 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:24:17,321] Trial 16 finished with value: 0.24774718825998998 and parameters: {'kernel': 'rbf', 'C': 0.7425092067971584, 'epsilon': 0.19340921503702663, 'gamma': 'scale'}. Best is trial 13 with value: 0.5988876884756753.
[I 2025-07-11 17:24:17,394] Trial 17 finished with value: 0.47870618708936497 and parameters: {'kernel': 'rbf', 'C': 3.8589942222046725, 'epsilon': 0.14347222711694174, 'gamma': 'scale'}. Best is trial 13 with value: 0.5988876884756753.
[I 2025-07-11 17:24:17,469] Trial 18 finished with value: -36.56482273226032 and parameters: {'kernel': 'sigmoid', 'C': 5.035506391814398, 'epsilon': 0.045738380051309487, 'gamma': 'auto'}. Best is trial 13 with value: 0.5988876884756753.

Running time: 0.1 sec
OOF RMSE: 3.01 | R2: 0.25
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.50 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 21.25 | R2: -36.56
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 17:24:17,541] Trial 19 finished with value: 0.29844442563162765 and parameters: {'kernel': 'rbf', 'C': 1.1747345383792058, 'epsilon': 0.11040337550578329, 'gamma': 'scale'}. Best is trial 13 with value: 0.5988876884756753.
[I 2025-07-11 17:24:17,615] Trial 20 finished with value: 0.3881787034306503 and parameters: {'kernel': 'rbf', 'C': 2.3772067085928317, 'epsilon': 0.17772624821271676, 'gamma': 'scale'}. Best is trial 13 with value: 0.5988876884756753.
[I 2025-07-11 17:24:17,689] Trial 21 finished with value: 0.5975178374219555 and parameters: {'kernel': 'rbf', 'C': 9.09979259371576, 'epsilon': 0.13996453503831197, 'gamma': 'scale'}. Best is trial 13 with value: 0.5988876884756753.

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.90 | R2: 0.30
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.71 | R2: 0.39
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.20 | R2: 0.60
Fold 1
Fold 2
Fold 3

[I 2025-07-11 17:24:17,764] Trial 22 finished with value: 0.5435141183740603 and parameters: {'kernel': 'rbf', 'C': 5.715790371437153, 'epsilon': 0.1504430715214032, 'gamma': 'scale'}. Best is trial 13 with value: 0.5988876884756753.
[I 2025-07-11 17:24:17,843] Trial 23 finished with value: 0.5982999086740045 and parameters: {'kernel': 'rbf', 'C': 9.143434132014233, 'epsilon': 0.13074533377896766, 'gamma': 'scale'}. Best is trial 13 with value: 0.5988876884756753.
[I 2025-07-11 17:24:17,915] Trial 24 finished with value: 0.4525472991032621 and parameters: {'kernel': 'rbf', 'C': 3.3156793547807197, 'epsilon': 0.09617510257278017, 'gamma': 'scale'}. Best is trial 13 with value: 0.5988876884756753.
[I 2025-07-11 17:24:17,916] A new study created in memory with name: no-name-47c189b0-efbf-4de4-9ba2-cdd49731247e

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.34 | R2: 0.54
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.20 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.56 | R2: 0.45

✅ SVR - Mejor R2: 0.60
📋 Parámetros: {'kernel': 'rbf', 'C': 9.368015046738579, 'epsilon': 0.14260568400950718, 'gamma': 'scale'}

Buscando mejores hiperparámetros para KNN...
Fold 1
Fold 2

[I 2025-07-11 17:24:17,974] Trial 0 finished with value: 0.643960839388847 and parameters: {'n_neighbors': 4, 'weights': 'uniform', 'leaf_size': 10}. Best is trial 0 with value: 0.643960839388847.
[I 2025-07-11 17:24:18,035] Trial 1 finished with value: 0.508561339697688 and parameters: {'n_neighbors': 14, 'weights': 'uniform', 'leaf_size': 35}. Best is trial 0 with value: 0.643960839388847.
[I 2025-07-11 17:24:18,090] Trial 2 finished with value: 0.7092765392463615 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'leaf_size': 33}. Best is trial 2 with value: 0.7092765392463615.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.07 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.43 | R2: 0.51
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.87 | R2: 0.71
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:24:18,148] Trial 3 finished with value: 0.5053403410511421 and parameters: {'n_neighbors': 13, 'weights': 'uniform', 'leaf_size': 19}. Best is trial 2 with value: 0.7092765392463615.
[I 2025-07-11 17:24:18,205] Trial 4 finished with value: 0.6807873373061932 and parameters: {'n_neighbors': 5, 'weights': 'uniform', 'leaf_size': 29}. Best is trial 2 with value: 0.7092765392463615.
[I 2025-07-11 17:24:18,261] Trial 5 finished with value: 0.5637214194265695 and parameters: {'n_neighbors': 9, 'weights': 'uniform', 'leaf_size': 40}. Best is trial 2 with value: 0.7092765392463615.
[I 2025-07-11 17:24:18,315] Trial 6 finished with value: 0.5053403410511421 and parameters: {'n_neighbors': 13, 'weights': 'uniform', 'leaf_size': 23}. Best is trial 2 with value: 0.7092765392463615.

Running time: 0.1 sec
OOF RMSE: 2.44 | R2: 0.51
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.96 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.29 | R2: 0.56
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.44 | R2: 0.51
Fold 1
Fold 2
Fold 3

[I 2025-07-11 17:24:18,375] Trial 7 finished with value: 0.6909655797671655 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'leaf_size': 27}. Best is trial 2 with value: 0.7092765392463615.
[I 2025-07-11 17:24:18,437] Trial 8 finished with value: 0.5856430298280877 and parameters: {'n_neighbors': 8, 'weights': 'uniform', 'leaf_size': 10}. Best is trial 2 with value: 0.7092765392463615.
[I 2025-07-11 17:24:18,496] Trial 9 finished with value: 0.5241853402152139 and parameters: {'n_neighbors': 12, 'weights': 'uniform', 'leaf_size': 23}. Best is trial 2 with value: 0.7092765392463615.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.93 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.23 | R2: 0.59
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.39 | R2: 0.52
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:24:18,560] Trial 10 finished with value: 0.671802392621055 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'leaf_size': 37}. Best is trial 2 with value: 0.7092765392463615.
[I 2025-07-11 17:24:18,671] Trial 11 finished with value: 0.6909655797671655 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'leaf_size': 30}. Best is trial 2 with value: 0.7092765392463615.
[I 2025-07-11 17:24:18,737] Trial 12 finished with value: 0.6862984506632173 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 31}. Best is trial 2 with value: 0.7092765392463615.

Running time: 0.1 sec
OOF RMSE: 1.99 | R2: 0.67
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.93 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.94 | R2: 0.69
Fold 1
Fold 2

[I 2025-07-11 17:24:18,807] Trial 13 finished with value: 0.6042281971455308 and parameters: {'n_neighbors': 11, 'weights': 'distance', 'leaf_size': 18}. Best is trial 2 with value: 0.7092765392463615.
[I 2025-07-11 17:24:18,876] Trial 14 finished with value: 0.6909655797671655 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'leaf_size': 27}. Best is trial 2 with value: 0.7092765392463615.
[I 2025-07-11 17:24:18,943] Trial 15 finished with value: 0.6862984506632173 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 34}. Best is trial 2 with value: 0.7092765392463615.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.18 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.93 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.94 | R2: 0.69
Fold 1
Fold 2

[I 2025-07-11 17:24:19,012] Trial 16 finished with value: 0.6102801138655743 and parameters: {'n_neighbors': 10, 'weights': 'distance', 'leaf_size': 33}. Best is trial 2 with value: 0.7092765392463615.
[I 2025-07-11 17:24:19,081] Trial 17 finished with value: 0.7092765392463615 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'leaf_size': 25}. Best is trial 2 with value: 0.7092765392463615.
[I 2025-07-11 17:24:19,147] Trial 18 finished with value: 0.6459559352046467 and parameters: {'n_neighbors': 8, 'weights': 'distance', 'leaf_size': 18}. Best is trial 2 with value: 0.7092765392463615.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.16 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.87 | R2: 0.71
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.06 | R2: 0.65
Fold 1
Fold 2

[I 2025-07-11 17:24:19,212] Trial 19 finished with value: 0.6805222135056366 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'leaf_size': 23}. Best is trial 2 with value: 0.7092765392463615.
[I 2025-07-11 17:24:19,279] Trial 20 finished with value: 0.7092765392463615 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'leaf_size': 40}. Best is trial 2 with value: 0.7092765392463615.
[I 2025-07-11 17:24:19,345] Trial 21 finished with value: 0.7092765392463615 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'leaf_size': 39}. Best is trial 2 with value: 0.7092765392463615.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.96 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.87 | R2: 0.71
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.87 | R2: 0.71
Fold 1
Fold 2
Fold 3

[I 2025-07-11 17:24:19,412] Trial 22 finished with value: 0.7092765392463615 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'leaf_size': 37}. Best is trial 2 with value: 0.7092765392463615.
[I 2025-07-11 17:24:19,481] Trial 23 finished with value: 0.671802392621055 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'leaf_size': 32}. Best is trial 2 with value: 0.7092765392463615.
[I 2025-07-11 17:24:19,547] Trial 24 finished with value: 0.6862984506632173 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 37}. Best is trial 2 with value: 0.7092765392463615.
[I 2025-07-11 17:24:19,548] A new study created in memory with name: no-name-2e669fb7-fc4a-4c82-80b6-45a28667d3c6

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.87 | R2: 0.71
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.99 | R2: 0.67
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.94 | R2: 0.69

✅ KNN - Mejor R2: 0.71
📋 Parámetros: {'n_neighbors': 5, 'weights': 'distance', 'leaf_size': 33}

Buscando mejores hiperparámetros para LR...
Fold 1
Fold 2
Fold 3

[I 2025-07-11 17:24:19,636] Trial 0 finished with value: 0.4792604688472055 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 0 with value: 0.4792604688472055.
[I 2025-07-11 17:24:19,727] Trial 1 finished with value: 0.48281540786635824 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.48281540786635824.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.50 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.49 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:24:19,809] Trial 2 finished with value: 0.4792604688530032 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 1 with value: 0.48281540786635824.
[I 2025-07-11 17:24:19,941] Trial 3 finished with value: 0.4792604688530032 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 1 with value: 0.48281540786635824.

Running time: 0.1 sec
OOF RMSE: 2.50 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.50 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 17:24:20,049] Trial 4 finished with value: 0.4792604688472055 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 1 with value: 0.48281540786635824.
[I 2025-07-11 17:24:20,207] Trial 5 finished with value: 0.4792604688530032 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 1 with value: 0.48281540786635824.

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.50 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.50 | R2: 0.48
Fold 1

[I 2025-07-11 17:24:20,338] Trial 6 finished with value: 0.4792604688472055 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 1 with value: 0.48281540786635824.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.50 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:24:20,447] Trial 7 finished with value: 0.4792604688530032 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 1 with value: 0.48281540786635824.
[I 2025-07-11 17:24:20,551] Trial 8 finished with value: 0.4828154078663567 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 1 with value: 0.48281540786635824.
[I 2025-07-11 17:24:20,624] Trial 9 finished with value: 0.4792604688530032 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 1 with value: 0.48281540786635824.

Running time: 0.1 sec
OOF RMSE: 2.50 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.49 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.50 | R2: 0.48
Fold 1
Fold 2

[I 2025-07-11 17:24:20,700] Trial 10 finished with value: 0.48281540786635824 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.48281540786635824.
[I 2025-07-11 17:24:20,762] Trial 11 finished with value: 0.48281540786635824 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.48281540786635824.
[I 2025-07-11 17:24:20,819] Trial 12 finished with value: 0.48281540786635824 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.48281540786635824.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.49 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.49 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.49 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 17:24:20,878] Trial 13 finished with value: 0.48281540786635824 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.48281540786635824.
[I 2025-07-11 17:24:20,938] Trial 14 finished with value: 0.48281540786635824 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.48281540786635824.
[I 2025-07-11 17:24:20,996] Trial 15 finished with value: 0.48281540786635824 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.48281540786635824.
[I 2025-07-11 17:24:21,052] Trial 16 finished with value: 0.48281540786635824 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.48281540786635824.

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.49 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.49 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.49 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.49 | R2: 0.48
Fold 1

[I 2025-07-11 17:24:21,126] Trial 17 finished with value: 0.48281540786635824 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.48281540786635824.
[I 2025-07-11 17:24:21,189] Trial 18 finished with value: 0.4828154078663567 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 1 with value: 0.48281540786635824.
[I 2025-07-11 17:24:21,246] Trial 19 finished with value: 0.48281540786635824 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.48281540786635824.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.49 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.49 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.49 | R2: 0.48
Fold 1
Fold 2
Fold 3

[I 2025-07-11 17:24:21,305] Trial 20 finished with value: 0.48281540786635824 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.48281540786635824.
[I 2025-07-11 17:24:21,364] Trial 21 finished with value: 0.48281540786635824 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.48281540786635824.
[I 2025-07-11 17:24:21,421] Trial 22 finished with value: 0.48281540786635824 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.48281540786635824.
[I 2025-07-11 17:24:21,477] Trial 23 finished with value: 0.48281540786635824 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.48281540786635824.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.49 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.49 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.49 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.49 | R2: 0.48
Fold 1

[I 2025-07-11 17:24:21,536] Trial 24 finished with value: 0.48281540786635824 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.48281540786635824.
[I 2025-07-11 17:24:21,537] A new study created in memory with name: no-name-5a27938d-d2e7-40a0-b594-9b2008735389

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.49 | R2: 0.48

✅ LR - Mejor R2: 0.48
📋 Parámetros: {'fit_intercept': False, 'positive': True}

Buscando mejores hiperparámetros para RF...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:24:26,515] Trial 0 finished with value: 0.5811123845285883 and parameters: {'n_estimators': 300, 'max_depth': 9, 'min_samples_split': 8, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 0 with value: 0.5811123845285883.

Running time: 5.0 sec
OOF RMSE: 2.24 | R2: 0.58
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:24:27,975] Trial 1 finished with value: 0.5604991655467599 and parameters: {'n_estimators': 100, 'max_depth': 10, 'min_samples_split': 8, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 0 with value: 0.5811123845285883.

Running time: 1.5 sec
OOF RMSE: 2.30 | R2: 0.56
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:24:39,722] Trial 2 finished with value: 0.48757330514256536 and parameters: {'n_estimators': 500, 'max_depth': 13, 'min_samples_split': 2, 'min_samples_leaf': 5, 'bootstrap': False}. Best is trial 0 with value: 0.5811123845285883.

Running time: 11.7 sec
OOF RMSE: 2.48 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:24:41,175] Trial 3 finished with value: 0.56298332309127 and parameters: {'n_estimators': 100, 'max_depth': 13, 'min_samples_split': 6, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 0 with value: 0.5811123845285883.

Running time: 1.4 sec
OOF RMSE: 2.29 | R2: 0.56
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:24:43,748] Trial 4 finished with value: 0.3970530928220557 and parameters: {'n_estimators': 100, 'max_depth': 9, 'min_samples_split': 2, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 0 with value: 0.5811123845285883.

Running time: 2.6 sec
OOF RMSE: 2.69 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:24:55,935] Trial 5 finished with value: 0.4496925915175396 and parameters: {'n_estimators': 500, 'max_depth': 11, 'min_samples_split': 2, 'min_samples_leaf': 4, 'bootstrap': False}. Best is trial 0 with value: 0.5811123845285883.

Running time: 12.2 sec
OOF RMSE: 2.57 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:25:03,983] Trial 6 finished with value: 0.5868095324619076 and parameters: {'n_estimators': 500, 'max_depth': 10, 'min_samples_split': 8, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 6 with value: 0.5868095324619076.

Running time: 8.0 sec
OOF RMSE: 2.23 | R2: 0.59
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:25:10,186] Trial 7 finished with value: 0.4844039382846774 and parameters: {'n_estimators': 300, 'max_depth': 7, 'min_samples_split': 3, 'min_samples_leaf': 5, 'bootstrap': False}. Best is trial 6 with value: 0.5868095324619076.

Running time: 6.2 sec
OOF RMSE: 2.49 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:25:17,168] Trial 8 finished with value: 0.5853098559502581 and parameters: {'n_estimators': 500, 'max_depth': 6, 'min_samples_split': 2, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 6 with value: 0.5868095324619076.

Running time: 7.0 sec
OOF RMSE: 2.23 | R2: 0.59
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:25:18,581] Trial 9 finished with value: 0.5786830326151036 and parameters: {'n_estimators': 100, 'max_depth': 7, 'min_samples_split': 10, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 6 with value: 0.5868095324619076.

Running time: 1.4 sec
OOF RMSE: 2.25 | R2: 0.58
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:25:28,317] Trial 10 finished with value: 0.5980904288544606 and parameters: {'n_estimators': 500, 'max_depth': 15, 'min_samples_split': 5, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 10 with value: 0.5980904288544606.

Running time: 9.7 sec
OOF RMSE: 2.20 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:25:38,060] Trial 11 finished with value: 0.5980904288544606 and parameters: {'n_estimators': 500, 'max_depth': 15, 'min_samples_split': 5, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 10 with value: 0.5980904288544606.

Running time: 9.7 sec
OOF RMSE: 2.20 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:25:47,791] Trial 12 finished with value: 0.5980904288544606 and parameters: {'n_estimators': 500, 'max_depth': 15, 'min_samples_split': 5, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 10 with value: 0.5980904288544606.

Running time: 9.7 sec
OOF RMSE: 2.20 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:25:57,803] Trial 13 finished with value: 0.6005994746028613 and parameters: {'n_estimators': 500, 'max_depth': 15, 'min_samples_split': 4, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 13 with value: 0.6005994746028613.

Running time: 10.0 sec
OOF RMSE: 2.19 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:26:07,711] Trial 14 finished with value: 0.6015823824498082 and parameters: {'n_estimators': 500, 'max_depth': 13, 'min_samples_split': 4, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 14 with value: 0.6015823824498082.

Running time: 9.9 sec
OOF RMSE: 2.19 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:26:16,857] Trial 15 finished with value: 0.5808894029069047 and parameters: {'n_estimators': 500, 'max_depth': 13, 'min_samples_split': 4, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 14 with value: 0.6015823824498082.

Running time: 9.1 sec
OOF RMSE: 2.24 | R2: 0.58
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:26:22,772] Trial 16 finished with value: 0.5978113055191207 and parameters: {'n_estimators': 300, 'max_depth': 12, 'min_samples_split': 4, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 14 with value: 0.6015823824498082.

Running time: 5.9 sec
OOF RMSE: 2.20 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:26:31,999] Trial 17 finished with value: 0.5798954957513202 and parameters: {'n_estimators': 500, 'max_depth': 14, 'min_samples_split': 4, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 14 with value: 0.6015823824498082.

Running time: 9.2 sec
OOF RMSE: 2.25 | R2: 0.58
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:26:46,724] Trial 18 finished with value: 0.45095490328737864 and parameters: {'n_estimators': 500, 'max_depth': 12, 'min_samples_split': 6, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 14 with value: 0.6015823824498082.

Running time: 14.7 sec
OOF RMSE: 2.57 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:26:52,013] Trial 19 finished with value: 0.5821001883993071 and parameters: {'n_estimators': 300, 'max_depth': 14, 'min_samples_split': 7, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 14 with value: 0.6015823824498082.

Running time: 5.3 sec
OOF RMSE: 2.24 | R2: 0.58
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:27:00,260] Trial 20 finished with value: 0.5861205539722967 and parameters: {'n_estimators': 500, 'max_depth': 14, 'min_samples_split': 3, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 14 with value: 0.6015823824498082.

Running time: 8.2 sec
OOF RMSE: 2.23 | R2: 0.59
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:27:09,992] Trial 21 finished with value: 0.5980904288544606 and parameters: {'n_estimators': 500, 'max_depth': 15, 'min_samples_split': 5, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 14 with value: 0.6015823824498082.

Running time: 9.7 sec
OOF RMSE: 2.20 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:27:19,985] Trial 22 finished with value: 0.6005994746028613 and parameters: {'n_estimators': 500, 'max_depth': 15, 'min_samples_split': 4, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 14 with value: 0.6015823824498082.

Running time: 10.0 sec
OOF RMSE: 2.19 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:27:30,226] Trial 23 finished with value: 0.6015331375319636 and parameters: {'n_estimators': 500, 'max_depth': 14, 'min_samples_split': 3, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 14 with value: 0.6015823824498082.

Running time: 10.2 sec
OOF RMSE: 2.19 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:27:39,313] Trial 24 finished with value: 0.5806698979153934 and parameters: {'n_estimators': 500, 'max_depth': 12, 'min_samples_split': 3, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 14 with value: 0.6015823824498082.
[I 2025-07-11 17:27:39,315] A new study created in memory with name: no-name-6c12be41-678e-402e-979c-c2fd0af07a4c

Running time: 9.1 sec
OOF RMSE: 2.24 | R2: 0.58

✅ RF - Mejor R2: 0.60
📋 Parámetros: {'n_estimators': 500, 'max_depth': 13, 'min_samples_split': 4, 'min_samples_leaf': 1, 'bootstrap': True}

Buscando mejores hiperparámetros para CAT...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:32:29,458] Trial 0 finished with value: 0.6498802531612504 and parameters: {'iterations': 2000, 'learning_rate': 0.020027411170740934, 'depth': 10, 'l2_leaf_reg': 8.104730384496934}. Best is trial 0 with value: 0.6498802531612504.

Running time: 290.1 sec
OOF RMSE: 2.05 | R2: 0.65
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:37:31,026] Trial 1 finished with value: 0.6519709130517699 and parameters: {'iterations': 2000, 'learning_rate': 0.06729202797129841, 'depth': 10, 'l2_leaf_reg': 4.623888192212956}. Best is trial 1 with value: 0.6519709130517699.

Running time: 301.6 sec
OOF RMSE: 2.05 | R2: 0.65
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:38:13,574] Trial 2 finished with value: 0.6668137901970955 and parameters: {'iterations': 500, 'learning_rate': 0.013155008682611538, 'depth': 9, 'l2_leaf_reg': 1.076857263603094}. Best is trial 2 with value: 0.6668137901970955.
[I 2025-07-11 17:38:13,575] A new study created in memory with name: no-name-a7648ad2-acad-4899-b635-b825d046d843
[I 2025-07-11 17:38:13,671] Trial 0 finished with value: 0.5084282588690994 and parameters: {'alpha': 0.07512225264015909, 'l1_ratio': 0.311755022006191}. Best is trial 0 with value: 0.5084282588690994.
[I 2025-07-11 17:38:13,748] Trial 1 finished with value: 0.4354013380246571 and parameters: {'alpha': 0.526601277132134, 'l1_ratio': 0.7972735933448165}. Best is trial 0 with value: 0.5084282588690994.

Running time: 42.5 sec
OOF RMSE: 2.00 | R2: 0.67

✅ CAT - Mejor R2: 0.67
📋 Parámetros: {'iterations': 500, 'learning_rate': 0.013155008682611538, 'depth': 9, 'l2_leaf_reg': 1.076857263603094}

Buscando mejores hiperparámetros para EN...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.43 | R2: 0.51
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.60 | R2: 0.44
Fold 1
Fold 2

[I 2025-07-11 17:38:13,829] Trial 2 finished with value: 0.3977639749754327 and parameters: {'alpha': 1.80084315364255, 'l1_ratio': 0.09966867959399128}. Best is trial 0 with value: 0.5084282588690994.
[I 2025-07-11 17:38:13,908] Trial 3 finished with value: 0.3999368167240138 and parameters: {'alpha': 1.5056861113157602, 'l1_ratio': 0.14688671896238792}. Best is trial 0 with value: 0.5084282588690994.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.69 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.69 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:38:13,990] Trial 4 finished with value: 0.3238416135716652 and parameters: {'alpha': 1.4816595558620897, 'l1_ratio': 0.6069257370093383}. Best is trial 0 with value: 0.5084282588690994.
[I 2025-07-11 17:38:14,067] Trial 5 finished with value: -0.00027817151752640434 and parameters: {'alpha': 4.636149946163347, 'l1_ratio': 0.9193640798345744}. Best is trial 0 with value: 0.5084282588690994.
[I 2025-07-11 17:38:14,144] Trial 6 finished with value: 0.18478695913585186 and parameters: {'alpha': 2.1795488896996633, 'l1_ratio': 0.701332726990092}. Best is trial 0 with value: 0.5084282588690994.

Running time: 0.1 sec
OOF RMSE: 2.85 | R2: 0.32
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.47 | R2: -0.00
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.13 | R2: 0.18
Fold 1
Fold 2
Fold 3

[I 2025-07-11 17:38:14,227] Trial 7 finished with value: 0.5237475018739581 and parameters: {'alpha': 0.033081705613781674, 'l1_ratio': 0.8769728170517432}. Best is trial 7 with value: 0.5237475018739581.
[I 2025-07-11 17:38:14,309] Trial 8 finished with value: 0.3759763187681978 and parameters: {'alpha': 2.162430922528244, 'l1_ratio': 0.1643337679388952}. Best is trial 7 with value: 0.5237475018739581.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.39 | R2: 0.52
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.74 | R2: 0.38
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:38:14,406] Trial 9 finished with value: 0.47953612154626957 and parameters: {'alpha': 0.17182000415898402, 'l1_ratio': 0.9078183928119583}. Best is trial 7 with value: 0.5237475018739581.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.026e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.222e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.071e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.634e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.878e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 17:38:14,546] Trial 10 finished with value: 0.5015720003680458 and parameters: {'alpha': 0.0030367325111931606, 'l1_ratio': 0.4780403204679822}. Best is trial 7 with value: 0.5237475018739581.

Running time: 0.1 sec
OOF RMSE: 2.50 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.45 | R2: 0.50
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.222e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.600e+01, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.371e+01, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.609e+01, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.648e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 17:38:14,667] Trial 11 finished with value: 0.5128524897283534 and parameters: {'alpha': 0.012401019339468813, 'l1_ratio': 0.35698585600393123}. Best is trial 7 with value: 0.5237475018739581.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.886e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.536e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.631e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.647e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.147e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 17:38:14,787] Trial 12 finished with value: 0.5092716631341979 and parameters: {'alpha': 0.0063061825294485575, 'l1_ratio': 0.3894056747855135}. Best is trial 7 with value: 0.5237475018739581.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.631e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.42 | R2: 0.51
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.43 | R2: 0.51
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.315e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.133e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.307e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.428e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 17:38:14,955] Trial 13 finished with value: 0.46417727288167 and parameters: {'alpha': 0.00037679769595517235, 'l1_ratio': 0.5804282261837271}. Best is trial 7 with value: 0.5237475018739581.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.007e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 2.54 | R2: 0.46
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.653e+01, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.520e+01, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.460e+01, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.492e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 17:38:15,144] Trial 14 finished with value: 0.5158193194824083 and parameters: {'alpha': 0.019562858055234358, 'l1_ratio': 0.2802919607840347}. Best is trial 7 with value: 0.5237475018739581.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.138e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.754e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.642e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(

Fold 3
Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 2.41 | R2: 0.52
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.904e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.193e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 17:38:15,282] Trial 15 finished with value: 0.48705547565627993 and parameters: {'alpha': 0.0010432964555518506, 'l1_ratio': 0.01963549877477838}. Best is trial 7 with value: 0.5237475018739581.
[I 2025-07-11 17:38:15,416] Trial 16 finished with value: 0.526277535332456 and parameters: {'alpha': 0.048330942726490585, 'l1_ratio': 0.9989560212538449}. Best is trial 16 with value: 0.526277535332456.

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.48 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.39 | R2: 0.53
Fold 1
Fold 2

[I 2025-07-11 17:38:15,541] Trial 17 finished with value: 0.5142243038376646 and parameters: {'alpha': 0.08712887781278446, 'l1_ratio': 0.9959557843882478}. Best is trial 16 with value: 0.526277535332456.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.42 | R2: 0.51
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 17:38:15,715] Trial 18 finished with value: 0.46900823482737874 and parameters: {'alpha': 0.2254374676455729, 'l1_ratio': 0.7999915271182645}. Best is trial 16 with value: 0.526277535332456.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.768e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.436e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.290e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.428e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.681e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 17:38:15,866] Trial 19 finished with value: 0.4569584702622421 and parameters: {'alpha': 0.00010410245320590767, 'l1_ratio': 0.9938574634513921}. Best is trial 16 with value: 0.526277535332456.

Fold 5
Running time: 0.2 sec
OOF RMSE: 2.53 | R2: 0.47
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.55 | R2: 0.46
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.035e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.009e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.202e+01, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.172e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.683e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 17:38:16,002] Trial 20 finished with value: 0.48813281172317646 and parameters: {'alpha': 0.0025277952212771596, 'l1_ratio': 0.7885478398380759}. Best is trial 16 with value: 0.526277535332456.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.959e+01, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.381e+00, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.912e+01, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.955e+01, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.48 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.161e+01, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 17:38:16,127] Trial 21 finished with value: 0.5139508010768287 and parameters: {'alpha': 0.02667558107031406, 'l1_ratio': 0.2661421635933445}. Best is trial 16 with value: 0.526277535332456.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.098e+01, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.062e+00, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.223e-01, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.790e+00, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.074e+01, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 17:38:16,276] Trial 22 finished with value: 0.5168345547739102 and parameters: {'alpha': 0.021564633042974016, 'l1_ratio': 0.4606596702882634}. Best is trial 16 with value: 0.526277535332456.

Running time: 0.1 sec
OOF RMSE: 2.42 | R2: 0.51
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.41 | R2: 0.52
Fold 1
Fold 2
Fold 3

[I 2025-07-11 17:38:16,376] Trial 23 finished with value: 0.5174446046721406 and parameters: {'alpha': 0.05638020702024277, 'l1_ratio': 0.4989925544458395}. Best is trial 16 with value: 0.526277535332456.
[I 2025-07-11 17:38:16,477] Trial 24 finished with value: 0.5200510386999009 and parameters: {'alpha': 0.06597082643087906, 'l1_ratio': 0.67108519758568}. Best is trial 16 with value: 0.526277535332456.
[I 2025-07-11 17:38:16,478] A new study created in memory with name: no-name-70147325-9d72-47fd-9252-387c1b2114a0

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.41 | R2: 0.52
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.40 | R2: 0.52

✅ EN - Mejor R2: 0.53
📋 Parámetros: {'alpha': 0.048330942726490585, 'l1_ratio': 0.9989560212538449}

🔍 Optimizando en C2X-Complex_rhown_5x5_depth_lt_1...
Buscando mejores hiperparámetros para XGB...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:38:24,403] Trial 0 finished with value: 0.49020183447412713 and parameters: {'n_estimators': 2000, 'learning_rate': 0.07739255316298506, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.6446213896294838, 'colsample_bytree': 0.7183277494369676}. Best is trial 0 with value: 0.49020183447412713.

Running time: 7.9 sec
OOF RMSE: 2.48 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:38:32,226] Trial 1 finished with value: 0.5188924686278433 and parameters: {'n_estimators': 1000, 'learning_rate': 0.011427156780998985, 'max_depth': 8, 'min_child_weight': 3, 'subsample': 0.736293151917425, 'colsample_bytree': 0.8854419637481268}. Best is trial 1 with value: 0.5188924686278433.

Running time: 7.8 sec
OOF RMSE: 2.40 | R2: 0.52
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:38:38,308] Trial 2 finished with value: 0.5272741282543846 and parameters: {'n_estimators': 1000, 'learning_rate': 0.03622371120411466, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.8509405890180295, 'colsample_bytree': 0.7696936271577909}. Best is trial 2 with value: 0.5272741282543846.

Running time: 6.1 sec
OOF RMSE: 2.38 | R2: 0.53
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:38:44,139] Trial 3 finished with value: 0.5185819461568144 and parameters: {'n_estimators': 1000, 'learning_rate': 0.013459399227827155, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.720532971264973, 'colsample_bytree': 0.6557102507711225}. Best is trial 2 with value: 0.5272741282543846.

Running time: 5.8 sec
OOF RMSE: 2.41 | R2: 0.52
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:38:50,099] Trial 4 finished with value: 0.5813076474455618 and parameters: {'n_estimators': 500, 'learning_rate': 0.013473464861298417, 'max_depth': 8, 'min_child_weight': 1, 'subsample': 0.9265618318807921, 'colsample_bytree': 0.7340521906083576}. Best is trial 4 with value: 0.5813076474455618.

Running time: 6.0 sec
OOF RMSE: 2.24 | R2: 0.58
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:38:52,575] Trial 5 finished with value: 0.5249667154346669 and parameters: {'n_estimators': 500, 'learning_rate': 0.006917131259235871, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.9306870523651584, 'colsample_bytree': 0.7936383218805789}. Best is trial 4 with value: 0.5813076474455618.

Running time: 2.5 sec
OOF RMSE: 2.39 | R2: 0.52
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:38:59,237] Trial 6 finished with value: 0.5197894459419288 and parameters: {'n_estimators': 1000, 'learning_rate': 0.05483746380875893, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.7581040260367602, 'colsample_bytree': 0.8615598602423657}. Best is trial 4 with value: 0.5813076474455618.

Running time: 6.7 sec
OOF RMSE: 2.40 | R2: 0.52
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:39:07,830] Trial 7 finished with value: 0.5012887979257887 and parameters: {'n_estimators': 2000, 'learning_rate': 0.06969777295039048, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.7544433208799184, 'colsample_bytree': 0.8313732126370199}. Best is trial 4 with value: 0.5813076474455618.

Running time: 8.6 sec
OOF RMSE: 2.45 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:39:13,857] Trial 8 finished with value: 0.5030116048221352 and parameters: {'n_estimators': 1000, 'learning_rate': 0.006822771997068094, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.9817853483285933, 'colsample_bytree': 0.7853837263129241}. Best is trial 4 with value: 0.5813076474455618.

Running time: 6.0 sec
OOF RMSE: 2.44 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:39:22,544] Trial 9 finished with value: 0.4707412322651393 and parameters: {'n_estimators': 2000, 'learning_rate': 0.05538365132982758, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.7946253624360421, 'colsample_bytree': 0.8453257982387528}. Best is trial 4 with value: 0.5813076474455618.

Running time: 8.7 sec
OOF RMSE: 2.52 | R2: 0.47
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:39:29,188] Trial 10 finished with value: 0.5551488678138031 and parameters: {'n_estimators': 500, 'learning_rate': 0.019242292127022775, 'max_depth': 8, 'min_child_weight': 1, 'subsample': 0.8775366578665812, 'colsample_bytree': 0.9687499730705884}. Best is trial 4 with value: 0.5813076474455618.

Running time: 6.6 sec
OOF RMSE: 2.31 | R2: 0.56
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:39:36,035] Trial 11 finished with value: 0.5449705561840561 and parameters: {'n_estimators': 500, 'learning_rate': 0.022299006300486434, 'max_depth': 8, 'min_child_weight': 1, 'subsample': 0.8888943230731217, 'colsample_bytree': 0.9995817575925843}. Best is trial 4 with value: 0.5813076474455618.

Running time: 6.8 sec
OOF RMSE: 2.34 | R2: 0.54
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:39:43,699] Trial 12 finished with value: 0.5254604275813071 and parameters: {'n_estimators': 500, 'learning_rate': 0.019622091002476288, 'max_depth': 8, 'min_child_weight': 1, 'subsample': 0.9996108360181497, 'colsample_bytree': 0.9974221901066118}. Best is trial 4 with value: 0.5813076474455618.

Running time: 7.7 sec
OOF RMSE: 2.39 | R2: 0.53
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:39:49,841] Trial 13 finished with value: 0.5683569555179147 and parameters: {'n_estimators': 500, 'learning_rate': 0.012329227607207512, 'max_depth': 8, 'min_child_weight': 1, 'subsample': 0.8707732570022645, 'colsample_bytree': 0.9263149256579443}. Best is trial 4 with value: 0.5813076474455618.

Running time: 6.1 sec
OOF RMSE: 2.28 | R2: 0.57
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:39:52,751] Trial 14 finished with value: 0.5158486659253803 and parameters: {'n_estimators': 500, 'learning_rate': 0.010638912870239683, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.9314438379093417, 'colsample_bytree': 0.6179081853161686}. Best is trial 4 with value: 0.5813076474455618.

Running time: 2.9 sec
OOF RMSE: 2.41 | R2: 0.52
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:39:58,901] Trial 15 finished with value: 0.5600150767968985 and parameters: {'n_estimators': 500, 'learning_rate': 0.03138534216215727, 'max_depth': 8, 'min_child_weight': 1, 'subsample': 0.8215070083394629, 'colsample_bytree': 0.9212034421414378}. Best is trial 4 with value: 0.5813076474455618.

Running time: 6.1 sec
OOF RMSE: 2.30 | R2: 0.56
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:40:03,337] Trial 16 finished with value: 0.5176672167255905 and parameters: {'n_estimators': 500, 'learning_rate': 0.008627830987661497, 'max_depth': 8, 'min_child_weight': 2, 'subsample': 0.9207614101656494, 'colsample_bytree': 0.7240759953867006}. Best is trial 4 with value: 0.5813076474455618.

Running time: 4.4 sec
OOF RMSE: 2.41 | R2: 0.52
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:40:06,934] Trial 17 finished with value: 0.5678889391287216 and parameters: {'n_estimators': 500, 'learning_rate': 0.005046594936891365, 'max_depth': 6, 'min_child_weight': 1, 'subsample': 0.9621364540440696, 'colsample_bytree': 0.7239060854044739}. Best is trial 4 with value: 0.5813076474455618.

Running time: 3.6 sec
OOF RMSE: 2.28 | R2: 0.57
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:40:10,603] Trial 18 finished with value: 0.5858154777875118 and parameters: {'n_estimators': 500, 'learning_rate': 0.014369877210076695, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.8354155334511371, 'colsample_bytree': 0.6737079889012761}. Best is trial 18 with value: 0.5858154777875118.

Running time: 3.7 sec
OOF RMSE: 2.23 | R2: 0.59
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:40:13,656] Trial 19 finished with value: 0.5356386335423312 and parameters: {'n_estimators': 500, 'learning_rate': 0.015980403171779387, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.6114280009008637, 'colsample_bytree': 0.6744831661608334}. Best is trial 18 with value: 0.5858154777875118.

Running time: 3.0 sec
OOF RMSE: 2.36 | R2: 0.54
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:40:23,342] Trial 20 finished with value: 0.6113214754273599 and parameters: {'n_estimators': 2000, 'learning_rate': 0.030807798606597547, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.8196056231430358, 'colsample_bytree': 0.6083252426239475}. Best is trial 20 with value: 0.6113214754273599.

Running time: 9.7 sec
OOF RMSE: 2.16 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:40:32,949] Trial 21 finished with value: 0.5877260619575727 and parameters: {'n_estimators': 2000, 'learning_rate': 0.03009092765831257, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.8089701787598476, 'colsample_bytree': 0.6073606894513368}. Best is trial 20 with value: 0.6113214754273599.

Running time: 9.6 sec
OOF RMSE: 2.23 | R2: 0.59
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:40:42,594] Trial 22 finished with value: 0.5838516421671514 and parameters: {'n_estimators': 2000, 'learning_rate': 0.03131826550644176, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.8034556111375791, 'colsample_bytree': 0.6016712142768452}. Best is trial 20 with value: 0.6113214754273599.

Running time: 9.6 sec
OOF RMSE: 2.24 | R2: 0.58
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:40:51,236] Trial 23 finished with value: 0.5525981475889623 and parameters: {'n_estimators': 2000, 'learning_rate': 0.040583088965290295, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.6883922974852124, 'colsample_bytree': 0.6539128703937607}. Best is trial 20 with value: 0.6113214754273599.

Running time: 8.6 sec
OOF RMSE: 2.32 | R2: 0.55
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:41:02,083] Trial 24 finished with value: 0.6034802037094447 and parameters: {'n_estimators': 2000, 'learning_rate': 0.025525934792611032, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.8292863986986955, 'colsample_bytree': 0.6332874105434849}. Best is trial 20 with value: 0.6113214754273599.
[I 2025-07-11 17:41:02,084] A new study created in memory with name: no-name-989ebb6f-87e5-4cf8-ba75-788e42b6b2e9

Running time: 10.8 sec
OOF RMSE: 2.18 | R2: 0.60

✅ XGB - Mejor R2: 0.61
📋 Parámetros: {'n_estimators': 2000, 'learning_rate': 0.030807798606597547, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.8196056231430358, 'colsample_bytree': 0.6083252426239475}

Buscando mejores hiperparámetros para LBM...
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 17:41:03,072] Trial 0 finished with value: 0.5726722292163597 and parameters: {'learning_rate': 0.008770871336483476, 'num_leaves': 40, 'max_depth': 5, 'min_child_samples': 5, 'subsample': 0.7388025235307296, 'colsample_bytree': 0.6792946480385069, 'n_estimators': 2000}. Best is trial 0 with value: 0.5726722292163597.

Fold 5
Running time: 1.0 sec
OOF RMSE: 2.27 | R2: 0.57
Fold 1
Fold 2
Fold 3

[I 2025-07-11 17:41:03,431] Trial 1 finished with value: 0.5719558553405586 and parameters: {'learning_rate': 0.007522978870971748, 'num_leaves': 60, 'max_depth': 8, 'min_child_samples': 8, 'subsample': 0.9102756754459365, 'colsample_bytree': 0.6873908001677883, 'n_estimators': 500}. Best is trial 0 with value: 0.5726722292163597.

Fold 4
Fold 5
Running time: 0.4 sec
OOF RMSE: 2.27 | R2: 0.57
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 17:41:03,899] Trial 2 finished with value: 0.6462575188061508 and parameters: {'learning_rate': 0.011879181176237439, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 11, 'subsample': 0.7460901783257772, 'colsample_bytree': 0.7160772980839345, 'n_estimators': 1000}. Best is trial 2 with value: 0.6462575188061508.

Fold 5
Running time: 0.5 sec
OOF RMSE: 2.06 | R2: 0.65
Fold 1
Fold 2
Fold 3

[I 2025-07-11 17:41:04,172] Trial 3 finished with value: 0.5676126439165445 and parameters: {'learning_rate': 0.021951771112927815, 'num_leaves': 40, 'max_depth': 7, 'min_child_samples': 18, 'subsample': 0.8258496719820274, 'colsample_bytree': 0.7250589322838039, 'n_estimators': 500}. Best is trial 2 with value: 0.6462575188061508.

Fold 4
Fold 5
Running time: 0.3 sec
OOF RMSE: 2.28 | R2: 0.57
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:41:04,627] Trial 4 finished with value: 0.6202774051242511 and parameters: {'learning_rate': 0.023824825498638156, 'num_leaves': 60, 'max_depth': 6, 'min_child_samples': 13, 'subsample': 0.7255547087319533, 'colsample_bytree': 0.6262990799481506, 'n_estimators': 1000}. Best is trial 2 with value: 0.6462575188061508.

Running time: 0.4 sec
OOF RMSE: 2.14 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 17:41:05,477] Trial 5 finished with value: 0.5732843443874764 and parameters: {'learning_rate': 0.051002670553488, 'num_leaves': 80, 'max_depth': 7, 'min_child_samples': 25, 'subsample': 0.8786046295127854, 'colsample_bytree': 0.678044822935709, 'n_estimators': 2000}. Best is trial 2 with value: 0.6462575188061508.

Fold 5
Running time: 0.8 sec
OOF RMSE: 2.26 | R2: 0.57
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:41:05,768] Trial 6 finished with value: 0.6020530374871469 and parameters: {'learning_rate': 0.09935372676386292, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 9, 'subsample': 0.9260588203038338, 'colsample_bytree': 0.9471753930302435, 'n_estimators': 500}. Best is trial 2 with value: 0.6462575188061508.

Running time: 0.3 sec
OOF RMSE: 2.19 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:41:06,022] Trial 7 finished with value: 0.6087720713540588 and parameters: {'learning_rate': 0.07194374566883414, 'num_leaves': 40, 'max_depth': 5, 'min_child_samples': 8, 'subsample': 0.6775296173412203, 'colsample_bytree': 0.8316816884682718, 'n_estimators': 500}. Best is trial 2 with value: 0.6462575188061508.

Running time: 0.2 sec
OOF RMSE: 2.17 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:41:07,194] Trial 8 finished with value: 0.6091862483623603 and parameters: {'learning_rate': 0.005071234025889178, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 8, 'subsample': 0.9562664459366086, 'colsample_bytree': 0.8553123537324803, 'n_estimators': 2000}. Best is trial 2 with value: 0.6462575188061508.

Running time: 1.2 sec
OOF RMSE: 2.17 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:41:07,437] Trial 9 finished with value: 0.5775163220834953 and parameters: {'learning_rate': 0.019168701411084194, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 23, 'subsample': 0.6714471834638418, 'colsample_bytree': 0.6404779303208914, 'n_estimators': 500}. Best is trial 2 with value: 0.6462575188061508.

Running time: 0.2 sec
OOF RMSE: 2.25 | R2: 0.58
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 17:41:08,048] Trial 10 finished with value: 0.6198843557740161 and parameters: {'learning_rate': 0.015681207642466367, 'num_leaves': 80, 'max_depth': 8, 'min_child_samples': 15, 'subsample': 0.6256665313235714, 'colsample_bytree': 0.7725664053152477, 'n_estimators': 1000}. Best is trial 2 with value: 0.6462575188061508.

Fold 5
Running time: 0.6 sec
OOF RMSE: 2.14 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 17:41:08,512] Trial 11 finished with value: 0.6173715523682686 and parameters: {'learning_rate': 0.03697439327793942, 'num_leaves': 60, 'max_depth': 6, 'min_child_samples': 14, 'subsample': 0.7613997234953607, 'colsample_bytree': 0.6116833776149752, 'n_estimators': 1000}. Best is trial 2 with value: 0.6462575188061508.

Fold 5
Running time: 0.5 sec
OOF RMSE: 2.14 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 17:41:08,997] Trial 12 finished with value: 0.611533782488908 and parameters: {'learning_rate': 0.011913584836852774, 'num_leaves': 60, 'max_depth': 6, 'min_child_samples': 12, 'subsample': 0.8103367964648458, 'colsample_bytree': 0.760490263944981, 'n_estimators': 1000}. Best is trial 2 with value: 0.6462575188061508.

Fold 5
Running time: 0.5 sec
OOF RMSE: 2.16 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:41:09,389] Trial 13 finished with value: 0.5398119015729347 and parameters: {'learning_rate': 0.038055806617838896, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 19, 'subsample': 0.7235171363491474, 'colsample_bytree': 0.6267918455962145, 'n_estimators': 1000}. Best is trial 2 with value: 0.6462575188061508.

Running time: 0.4 sec
OOF RMSE: 2.35 | R2: 0.54
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:41:09,905] Trial 14 finished with value: 0.615211710782712 and parameters: {'learning_rate': 0.02887297443677434, 'num_leaves': 60, 'max_depth': 6, 'min_child_samples': 12, 'subsample': 0.6016115689493992, 'colsample_bytree': 0.8907374306040523, 'n_estimators': 1000}. Best is trial 2 with value: 0.6462575188061508.

Running time: 0.5 sec
OOF RMSE: 2.15 | R2: 0.62
Fold 1
Fold 2
Fold 3

[I 2025-07-11 17:41:10,355] Trial 15 finished with value: 0.5655841088763653 and parameters: {'learning_rate': 0.012513871225951186, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 18, 'subsample': 0.8455098705505025, 'colsample_bytree': 0.709979020690603, 'n_estimators': 1000}. Best is trial 2 with value: 0.6462575188061508.

Fold 4
Fold 5
Running time: 0.4 sec
OOF RMSE: 2.28 | R2: 0.57
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 17:41:10,790] Trial 16 finished with value: 0.6646608535074101 and parameters: {'learning_rate': 0.0277640752355835, 'num_leaves': 60, 'max_depth': 5, 'min_child_samples': 11, 'subsample': 0.7748305193166063, 'colsample_bytree': 0.7539637134525157, 'n_estimators': 1000}. Best is trial 16 with value: 0.6646608535074101.

Fold 5
Running time: 0.4 sec
OOF RMSE: 2.01 | R2: 0.66
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:41:11,301] Trial 17 finished with value: 0.5699195347158929 and parameters: {'learning_rate': 0.00903982503192719, 'num_leaves': 80, 'max_depth': 5, 'min_child_samples': 5, 'subsample': 0.787211271057109, 'colsample_bytree': 0.7965502872444171, 'n_estimators': 1000}. Best is trial 16 with value: 0.6646608535074101.

Running time: 0.5 sec
OOF RMSE: 2.27 | R2: 0.57
Fold 1
Fold 2
Fold 3

[I 2025-07-11 17:41:11,746] Trial 18 finished with value: 0.6509652560894144 and parameters: {'learning_rate': 0.013742894163122896, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 11, 'subsample': 0.997316208728388, 'colsample_bytree': 0.9945576737724467, 'n_estimators': 1000}. Best is trial 16 with value: 0.6646608535074101.

Fold 4
Fold 5
Running time: 0.4 sec
OOF RMSE: 2.05 | R2: 0.65
Fold 1
Fold 2
Fold 3

[I 2025-07-11 17:41:12,265] Trial 19 finished with value: 0.6099824453933289 and parameters: {'learning_rate': 0.03253991040053352, 'num_leaves': 60, 'max_depth': 5, 'min_child_samples': 10, 'subsample': 0.9895460117067701, 'colsample_bytree': 0.9943400514169508, 'n_estimators': 1000}. Best is trial 16 with value: 0.6646608535074101.

Fold 4
Fold 5
Running time: 0.5 sec
OOF RMSE: 2.16 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:41:13,119] Trial 20 finished with value: 0.5683721677118181 and parameters: {'learning_rate': 0.05199323723112104, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 17, 'subsample': 0.9994839929028251, 'colsample_bytree': 0.9425551805759858, 'n_estimators': 2000}. Best is trial 16 with value: 0.6646608535074101.

Running time: 0.8 sec
OOF RMSE: 2.28 | R2: 0.57
Fold 1
Fold 2
Fold 3

[I 2025-07-11 17:41:13,549] Trial 21 finished with value: 0.6556754691249365 and parameters: {'learning_rate': 0.014686182840526613, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 11, 'subsample': 0.8594268477801821, 'colsample_bytree': 0.7410210157517818, 'n_estimators': 1000}. Best is trial 16 with value: 0.6646608535074101.

Fold 4
Fold 5
Running time: 0.4 sec
OOF RMSE: 2.03 | R2: 0.66
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 17:41:13,963] Trial 22 finished with value: 0.6226212089023846 and parameters: {'learning_rate': 0.015541604495942806, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 15, 'subsample': 0.8512526836614807, 'colsample_bytree': 0.7593513393980067, 'n_estimators': 1000}. Best is trial 16 with value: 0.6646608535074101.

Fold 5
Running time: 0.4 sec
OOF RMSE: 2.13 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:41:14,408] Trial 23 finished with value: 0.6557318897352065 and parameters: {'learning_rate': 0.019787655442756538, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 11, 'subsample': 0.8862423100021639, 'colsample_bytree': 0.8303504941622366, 'n_estimators': 1000}. Best is trial 16 with value: 0.6646608535074101.

Running time: 0.4 sec
OOF RMSE: 2.03 | R2: 0.66
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:41:14,882] Trial 24 finished with value: 0.5326384236649724 and parameters: {'learning_rate': 0.018787940884847632, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 7, 'subsample': 0.8923442315814615, 'colsample_bytree': 0.8256509973229577, 'n_estimators': 1000}. Best is trial 16 with value: 0.6646608535074101.
[I 2025-07-11 17:41:14,883] A new study created in memory with name: no-name-c37576de-74ea-4df8-b109-230aa7d11726

Running time: 0.5 sec
OOF RMSE: 2.37 | R2: 0.53

✅ LBM - Mejor R2: 0.66
📋 Parámetros: {'learning_rate': 0.0277640752355835, 'num_leaves': 60, 'max_depth': 5, 'min_child_samples': 11, 'subsample': 0.7748305193166063, 'colsample_bytree': 0.7539637134525157, 'n_estimators': 1000}

Buscando mejores hiperparámetros para MLP...
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 17:41:16,036] Trial 0 finished with value: 0.44158189280830207 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.005956261265258564, 'learning_rate': 'constant', 'learning_rate_init': 0.0031217935205213954}. Best is trial 0 with value: 0.44158189280830207.

Fold 4
Fold 5
Running time: 1.1 sec
OOF RMSE: 2.59 | R2: 0.44
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:41:16,722] Trial 1 finished with value: 0.5402152572633654 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.017248451451935834, 'learning_rate': 'adaptive', 'learning_rate_init': 0.003996712044329806}. Best is trial 1 with value: 0.5402152572633654.

Running time: 0.7 sec
OOF RMSE: 2.35 | R2: 0.54
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 17:41:18,405] Trial 2 finished with value: 0.513266740987709 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.001259387403507673, 'learning_rate': 'constant', 'learning_rate_init': 0.00026428095728749817}. Best is trial 1 with value: 0.5402152572633654.

Running time: 1.7 sec
OOF RMSE: 2.42 | R2: 0.51
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:41:19,670] Trial 3 finished with value: 0.5098407050629097 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 8.489069761514533e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.003363993247391485}. Best is trial 1 with value: 0.5402152572633654.

Running time: 1.3 sec
OOF RMSE: 2.43 | R2: 0.51
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

[I 2025-07-11 17:41:20,719] Trial 4 finished with value: 0.5240875125582399 and parameters: {'hidden_layer_sizes': '50', 'activation': 'relu', 'solver': 'sgd', 'alpha': 1.76631737796544e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0017219149400380617}. Best is trial 1 with value: 0.5402152572633654.

Running time: 1.0 sec
OOF RMSE: 2.39 | R2: 0.52
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

[I 2025-07-11 17:41:21,859] Trial 5 finished with value: 0.49596061431616556 and parameters: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.0014257768488684021, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0002726493872091452}. Best is trial 1 with value: 0.5402152572633654.

Running time: 1.1 sec
OOF RMSE: 2.46 | R2: 0.50
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:41:23,344] Trial 6 finished with value: 0.4942816102708111 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'tanh', 'solver': 'adam', 'alpha': 9.926809668396021e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.0007795031768609365}. Best is trial 1 with value: 0.5402152572633654.

Running time: 1.5 sec
OOF RMSE: 2.47 | R2: 0.49
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 17:41:24,371] Trial 7 finished with value: 0.30268847462085335 and parameters: {'hidden_layer_sizes': '50', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 3.763353433880075e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.00011499571625149132}. Best is trial 1 with value: 0.5402152572633654.

Fold 4
Fold 5
Running time: 1.0 sec
OOF RMSE: 2.89 | R2: 0.30
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 17:41:25,290] Trial 8 finished with value: 0.535080925606257 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0549433119333216, 'learning_rate': 'constant', 'learning_rate_init': 0.0009247205674406577}. Best is trial 1 with value: 0.5402152572633654.

Running time: 0.9 sec
OOF RMSE: 2.36 | R2: 0.54
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 17:41:25,850] Trial 9 finished with value: 0.45617772469861273 and parameters: {'hidden_layer_sizes': '50', 'activation': 'relu', 'solver': 'adam', 'alpha': 3.326564470503657e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.001145643918752947}. Best is trial 1 with value: 0.5402152572633654.

Fold 5
Running time: 0.6 sec
OOF RMSE: 2.56 | R2: 0.46
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:41:26,475] Trial 10 finished with value: 0.5675148011557738 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.09184862291532142, 'learning_rate': 'adaptive', 'learning_rate_init': 0.009255841300880575}. Best is trial 10 with value: 0.5675148011557738.

Running time: 0.6 sec
OOF RMSE: 2.28 | R2: 0.57
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 17:41:27,106] Trial 11 finished with value: 0.5653557270736953 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.07916222190006608, 'learning_rate': 'adaptive', 'learning_rate_init': 0.009935708170814675}. Best is trial 10 with value: 0.5675148011557738.

Fold 5
Running time: 0.6 sec
OOF RMSE: 2.29 | R2: 0.57
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:41:27,730] Trial 12 finished with value: 0.5653323363044143 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.08979258550598337, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00993606713110148}. Best is trial 10 with value: 0.5675148011557738.

Running time: 0.6 sec
OOF RMSE: 2.29 | R2: 0.57
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 17:41:28,371] Trial 13 finished with value: 0.5655526799805588 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.015611663903217304, 'learning_rate': 'adaptive', 'learning_rate_init': 0.009640540341849258}. Best is trial 10 with value: 0.5675148011557738.

Fold 5
Running time: 0.6 sec
OOF RMSE: 2.28 | R2: 0.57
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:41:29,109] Trial 14 finished with value: 0.5719250211838274 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.01060542259141343, 'learning_rate': 'adaptive', 'learning_rate_init': 0.006074226483838979}. Best is trial 14 with value: 0.5719250211838274.

Running time: 0.7 sec
OOF RMSE: 2.27 | R2: 0.57
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:41:29,869] Trial 15 finished with value: 0.5776171044251062 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.005013078964353393, 'learning_rate': 'adaptive', 'learning_rate_init': 0.005476448530873517}. Best is trial 15 with value: 0.5776171044251062.

Running time: 0.8 sec
OOF RMSE: 2.25 | R2: 0.58
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:41:30,769] Trial 16 finished with value: 0.5753314532320274 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.004284723525131366, 'learning_rate': 'adaptive', 'learning_rate_init': 0.004847090440909935}. Best is trial 15 with value: 0.5776171044251062.

Running time: 0.9 sec
OOF RMSE: 2.26 | R2: 0.58
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:41:31,866] Trial 17 finished with value: 0.5041863438169059 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.00042452476972272866, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0020125447655080786}. Best is trial 15 with value: 0.5776171044251062.

Running time: 1.1 sec
OOF RMSE: 2.44 | R2: 0.50
Fold 1
Fold 2
Fold 3

[I 2025-07-11 17:41:32,541] Trial 18 finished with value: 0.5002154815823256 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.003864847574536815, 'learning_rate': 'adaptive', 'learning_rate_init': 0.005139464986376606}. Best is trial 15 with value: 0.5776171044251062.

Fold 4
Fold 5
Running time: 0.7 sec
OOF RMSE: 2.45 | R2: 0.50
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 17:41:33,579] Trial 19 finished with value: 0.5825340472639808 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0004450897201857254, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0020111300210804497}. Best is trial 19 with value: 0.5825340472639808.

Running time: 1.0 sec
OOF RMSE: 2.24 | R2: 0.58
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 17:41:34,717] Trial 20 finished with value: 0.5311598391396395 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0002953454047401883, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0005928057481208321}. Best is trial 19 with value: 0.5825340472639808.

Running time: 1.1 sec
OOF RMSE: 2.37 | R2: 0.53
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 17:41:35,750] Trial 21 finished with value: 0.5842995316444204 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.002580682582104384, 'learning_rate': 'adaptive', 'learning_rate_init': 0.002404013964548544}. Best is trial 21 with value: 0.5842995316444204.

Running time: 1.0 sec
OOF RMSE: 2.24 | R2: 0.58
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 17:41:36,877] Trial 22 finished with value: 0.5833607607287822 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0004914527559565791, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0021624197180569555}. Best is trial 21 with value: 0.5842995316444204.

Running time: 1.1 sec
OOF RMSE: 2.24 | R2: 0.58
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 17:41:37,921] Trial 23 finished with value: 0.5822620743450266 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.00041996384682583437, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0020559291379951133}. Best is trial 21 with value: 0.5842995316444204.

Running time: 1.0 sec
OOF RMSE: 2.24 | R2: 0.58
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 17:41:39,000] Trial 24 finished with value: 0.5744902030331727 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.00018497788740119293, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0014078930948540644}. Best is trial 21 with value: 0.5842995316444204.
[I 2025-07-11 17:41:39,001] A new study created in memory with name: no-name-a4e6a625-b02e-4e94-bd3f-b1307baa90c0
[I 2025-07-11 17:41:39,088] Trial 0 finished with value: 0.21200059902934754 and parameters: {'kernel': 'rbf', 'C': 0.3922460410821575, 'epsilon': 0.024565774288407824, 'gamma': 'auto'}. Best is trial 0 with value: 0.21200059902934754.
[I 2025-07-11 17:41:39,156] Trial 1 finished with value: -0.7177296379479092 and parameters: {'kernel': 'sigmoid', 'C': 0.7041150070018478, 'epsilon': 0.1122652989156419, 'gamma': 'auto'}. Best is trial 0 with value: 0.21200059902934754.

Running time: 1.1 sec
OOF RMSE: 2.26 | R2: 0.57

✅ MLP - Mejor R2: 0.58
📋 Parámetros: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.002580682582104384, 'learning_rate': 'adaptive', 'learning_rate_init': 0.002404013964548544}

Buscando mejores hiperparámetros para SVR...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.08 | R2: 0.21
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 4.54 | R2: -0.72
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 17:41:39,225] Trial 2 finished with value: 0.36640969943477253 and parameters: {'kernel': 'rbf', 'C': 2.4936536644997895, 'epsilon': 0.05337043428606564, 'gamma': 'scale'}. Best is trial 2 with value: 0.36640969943477253.
[I 2025-07-11 17:41:39,298] Trial 3 finished with value: 0.07879587690269185 and parameters: {'kernel': 'sigmoid', 'C': 0.1723380384397746, 'epsilon': 0.06528022595090437, 'gamma': 'scale'}. Best is trial 2 with value: 0.36640969943477253.
[I 2025-07-11 17:41:39,364] Trial 4 finished with value: -7.416114097510151 and parameters: {'kernel': 'sigmoid', 'C': 2.3163319228155728, 'epsilon': 0.18820055688466392, 'gamma': 'auto'}. Best is trial 2 with value: 0.36640969943477253.

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.76 | R2: 0.37
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.33 | R2: 0.08
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 10.06 | R2: -7.42
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 17:41:39,433] Trial 5 finished with value: 0.06086812980826961 and parameters: {'kernel': 'sigmoid', 'C': 0.19612830484080584, 'epsilon': 0.05423769404272868, 'gamma': 'scale'}. Best is trial 2 with value: 0.36640969943477253.
[I 2025-07-11 17:41:39,507] Trial 6 finished with value: 0.10418803598792115 and parameters: {'kernel': 'sigmoid', 'C': 0.1423225150807489, 'epsilon': 0.021975655295913048, 'gamma': 'auto'}. Best is trial 2 with value: 0.36640969943477253.
[I 2025-07-11 17:41:39,569] Trial 7 finished with value: 0.4007709778820655 and parameters: {'kernel': 'rbf', 'C': 3.5247605681209775, 'epsilon': 0.15858500542229456, 'gamma': 'auto'}. Best is trial 7 with value: 0.4007709778820655.

Fold 5
Running time: 0.1 sec
OOF RMSE: 3.36 | R2: 0.06
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.28 | R2: 0.10
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.68 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 17:41:39,634] Trial 8 finished with value: 0.38066498725125086 and parameters: {'kernel': 'rbf', 'C': 3.007695865824185, 'epsilon': 0.11929999439764571, 'gamma': 'auto'}. Best is trial 7 with value: 0.4007709778820655.
[I 2025-07-11 17:41:39,701] Trial 9 finished with value: 0.25978002542962364 and parameters: {'kernel': 'rbf', 'C': 0.756794726473274, 'epsilon': 0.15320963073530167, 'gamma': 'scale'}. Best is trial 7 with value: 0.4007709778820655.
[I 2025-07-11 17:41:39,772] Trial 10 finished with value: 0.4696163814995119 and parameters: {'kernel': 'rbf', 'C': 8.118660674504069, 'epsilon': 0.18647568122181557, 'gamma': 'auto'}. Best is trial 10 with value: 0.4696163814995119.

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.73 | R2: 0.38
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.98 | R2: 0.26
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.52 | R2: 0.47
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 17:41:39,846] Trial 11 finished with value: 0.4714753566273703 and parameters: {'kernel': 'rbf', 'C': 8.326611210817138, 'epsilon': 0.1925182100396907, 'gamma': 'auto'}. Best is trial 11 with value: 0.4714753566273703.
[I 2025-07-11 17:41:39,924] Trial 12 finished with value: 0.4826436121347806 and parameters: {'kernel': 'rbf', 'C': 9.3806591893409, 'epsilon': 0.19353836940315566, 'gamma': 'auto'}. Best is trial 12 with value: 0.4826436121347806.
[I 2025-07-11 17:41:39,995] Trial 13 finished with value: 0.48557690299789946 and parameters: {'kernel': 'rbf', 'C': 9.71924065984448, 'epsilon': 0.19926148210342245, 'gamma': 'auto'}. Best is trial 13 with value: 0.48557690299789946.

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.52 | R2: 0.47
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.49 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.49 | R2: 0.49
Fold 1
Fold 2
Fold 3

[I 2025-07-11 17:41:40,070] Trial 14 finished with value: 0.48577858430907706 and parameters: {'kernel': 'rbf', 'C': 9.866716830886464, 'epsilon': 0.15275735174891564, 'gamma': 'auto'}. Best is trial 14 with value: 0.48577858430907706.
[I 2025-07-11 17:41:40,146] Trial 15 finished with value: 0.4399269674580383 and parameters: {'kernel': 'rbf', 'C': 4.80208449468494, 'epsilon': 0.15296543857271078, 'gamma': 'auto'}. Best is trial 14 with value: 0.48577858430907706.
[I 2025-07-11 17:41:40,216] Trial 16 finished with value: 0.31348539020322896 and parameters: {'kernel': 'rbf', 'C': 1.3991455931761025, 'epsilon': 0.13357276665352186, 'gamma': 'auto'}. Best is trial 14 with value: 0.48577858430907706.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.49 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.59 | R2: 0.44
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.87 | R2: 0.31
Fold 1
Fold 2

[I 2025-07-11 17:41:40,296] Trial 17 finished with value: 0.4442854137074299 and parameters: {'kernel': 'rbf', 'C': 5.081058189944931, 'epsilon': 0.17365815192974135, 'gamma': 'auto'}. Best is trial 14 with value: 0.48577858430907706.
[I 2025-07-11 17:41:40,388] Trial 18 finished with value: 0.33200879142140205 and parameters: {'kernel': 'rbf', 'C': 1.7447259160673356, 'epsilon': 0.13572671811270878, 'gamma': 'scale'}. Best is trial 14 with value: 0.48577858430907706.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.58 | R2: 0.44
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.83 | R2: 0.33
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:41:40,463] Trial 19 finished with value: 0.44225038845560927 and parameters: {'kernel': 'rbf', 'C': 5.066815811119124, 'epsilon': 0.09323011511973019, 'gamma': 'auto'}. Best is trial 14 with value: 0.48577858430907706.
[I 2025-07-11 17:41:40,532] Trial 20 finished with value: 0.19880498938194258 and parameters: {'kernel': 'rbf', 'C': 0.34937215412001016, 'epsilon': 0.17096082722084646, 'gamma': 'auto'}. Best is trial 14 with value: 0.48577858430907706.
[I 2025-07-11 17:41:40,605] Trial 21 finished with value: 0.4854477625607936 and parameters: {'kernel': 'rbf', 'C': 9.703401511078477, 'epsilon': 0.1988412595566737, 'gamma': 'auto'}. Best is trial 14 with value: 0.48577858430907706.

Running time: 0.1 sec
OOF RMSE: 2.59 | R2: 0.44
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.10 | R2: 0.20
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.49 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 17:41:40,680] Trial 22 finished with value: 0.48721878830745835 and parameters: {'kernel': 'rbf', 'C': 9.933758770821122, 'epsilon': 0.19913769193990524, 'gamma': 'auto'}. Best is trial 22 with value: 0.48721878830745835.
[I 2025-07-11 17:41:40,761] Trial 23 finished with value: 0.45306719973891973 and parameters: {'kernel': 'rbf', 'C': 6.062183471730363, 'epsilon': 0.16902881037456904, 'gamma': 'auto'}. Best is trial 22 with value: 0.48721878830745835.
[I 2025-07-11 17:41:40,835] Trial 24 finished with value: 0.46162427848932064 and parameters: {'kernel': 'rbf', 'C': 6.818600565811772, 'epsilon': 0.13644713359493504, 'gamma': 'auto'}. Best is trial 22 with value: 0.48721878830745835.
[I 2025-07-11 17:41:40,836] A new study created in memory with name: no-name-31433a42-7d60-4a2e-9c3b-5246ad4445a4

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.48 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.56 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.54 | R2: 0.46

✅ SVR - Mejor R2: 0.49
📋 Parámetros: {'kernel': 'rbf', 'C': 9.933758770821122, 'epsilon': 0.19913769193990524, 'gamma': 'auto'}

Buscando mejores hiperparámetros para KNN...
Fold 1
Fold 2
Fold 3

[I 2025-07-11 17:41:40,894] Trial 0 finished with value: 0.648930729744892 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'leaf_size': 25}. Best is trial 0 with value: 0.648930729744892.
[I 2025-07-11 17:41:40,958] Trial 1 finished with value: 0.6052863502733863 and parameters: {'n_neighbors': 15, 'weights': 'distance', 'leaf_size': 35}. Best is trial 0 with value: 0.648930729744892.
[I 2025-07-11 17:41:41,014] Trial 2 finished with value: 0.648930729744892 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'leaf_size': 32}. Best is trial 0 with value: 0.648930729744892.
[I 2025-07-11 17:41:41,072] Trial 3 finished with value: 0.6496170706826871 and parameters: {'n_neighbors': 8, 'weights': 'distance', 'leaf_size': 35}. Best is trial 3 with value: 0.6496170706826871.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.05 | R2: 0.65
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.18 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.05 | R2: 0.65
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.05 | R2: 0.65

[I 2025-07-11 17:41:41,132] Trial 4 finished with value: 0.6385536173411752 and parameters: {'n_neighbors': 11, 'weights': 'distance', 'leaf_size': 17}. Best is trial 3 with value: 0.6496170706826871.
[I 2025-07-11 17:41:41,193] Trial 5 finished with value: 0.6391169899779572 and parameters: {'n_neighbors': 4, 'weights': 'uniform', 'leaf_size': 33}. Best is trial 3 with value: 0.6496170706826871.
[I 2025-07-11 17:41:41,249] Trial 6 finished with value: 0.6314159583467885 and parameters: {'n_neighbors': 9, 'weights': 'distance', 'leaf_size': 12}. Best is trial 3 with value: 0.6496170706826871.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.08 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.08 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.10 | R2: 0.63
Fold 1
Fold 2
Fold 3

[I 2025-07-11 17:41:41,305] Trial 7 finished with value: 0.6391169899779572 and parameters: {'n_neighbors': 4, 'weights': 'uniform', 'leaf_size': 34}. Best is trial 3 with value: 0.6496170706826871.
[I 2025-07-11 17:41:41,369] Trial 8 finished with value: 0.5970573518478851 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'leaf_size': 32}. Best is trial 3 with value: 0.6496170706826871.
[I 2025-07-11 17:41:41,425] Trial 9 finished with value: 0.6313268881412286 and parameters: {'n_neighbors': 6, 'weights': 'uniform', 'leaf_size': 16}. Best is trial 3 with value: 0.6496170706826871.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.08 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.20 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.10 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:41:41,488] Trial 10 finished with value: 0.6271443408719168 and parameters: {'n_neighbors': 12, 'weights': 'distance', 'leaf_size': 40}. Best is trial 3 with value: 0.6496170706826871.
[I 2025-07-11 17:41:41,554] Trial 11 finished with value: 0.6496170706826871 and parameters: {'n_neighbors': 8, 'weights': 'distance', 'leaf_size': 24}. Best is trial 3 with value: 0.6496170706826871.
[I 2025-07-11 17:41:41,617] Trial 12 finished with value: 0.6314159583467885 and parameters: {'n_neighbors': 9, 'weights': 'distance', 'leaf_size': 25}. Best is trial 3 with value: 0.6496170706826871.
[I 2025-07-11 17:41:41,679] Trial 13 finished with value: 0.6385536173411752 and parameters: {'n_neighbors': 11, 'weights': 'distance', 'leaf_size': 21}. Best is trial 3 with value: 0.6496170706826871.

Running time: 0.1 sec
OOF RMSE: 2.12 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.05 | R2: 0.65
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.10 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.08 | R2: 0.64

[I 2025-07-11 17:41:41,748] Trial 14 finished with value: 0.6640384052561312 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'leaf_size': 27}. Best is trial 14 with value: 0.6640384052561312.
[I 2025-07-11 17:41:41,817] Trial 15 finished with value: 0.6721698638838516 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'leaf_size': 29}. Best is trial 15 with value: 0.6721698638838516.
[I 2025-07-11 17:41:41,878] Trial 16 finished with value: 0.6640384052561312 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'leaf_size': 30}. Best is trial 15 with value: 0.6721698638838516.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.01 | R2: 0.66
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.98 | R2: 0.67
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.01 | R2: 0.66
Fold 1

[I 2025-07-11 17:41:41,969] Trial 17 finished with value: 0.6721698638838516 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'leaf_size': 28}. Best is trial 15 with value: 0.6721698638838516.
[I 2025-07-11 17:41:42,047] Trial 18 finished with value: 0.5970573518478851 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'leaf_size': 29}. Best is trial 15 with value: 0.6721698638838516.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.98 | R2: 0.67
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.20 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:41:42,111] Trial 19 finished with value: 0.6721698638838516 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'leaf_size': 39}. Best is trial 15 with value: 0.6721698638838516.
[I 2025-07-11 17:41:42,181] Trial 20 finished with value: 0.6721698638838516 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'leaf_size': 21}. Best is trial 15 with value: 0.6721698638838516.
[I 2025-07-11 17:41:42,245] Trial 21 finished with value: 0.6721698638838516 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'leaf_size': 40}. Best is trial 15 with value: 0.6721698638838516.
[I 2025-07-11 17:41:42,310] Trial 22 finished with value: 0.6547760098988968 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'leaf_size': 37}. Best is trial 15 with value: 0.6721698638838516.

Running time: 0.1 sec
OOF RMSE: 1.98 | R2: 0.67
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.98 | R2: 0.67
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.98 | R2: 0.67
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.04 | R2: 0.65

[I 2025-07-11 17:41:42,377] Trial 23 finished with value: 0.6721698638838516 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'leaf_size': 29}. Best is trial 15 with value: 0.6721698638838516.
[I 2025-07-11 17:41:42,444] Trial 24 finished with value: 0.6197041089126623 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 37}. Best is trial 15 with value: 0.6721698638838516.
[I 2025-07-11 17:41:42,445] A new study created in memory with name: no-name-b0fc5575-c5b4-4cce-87fa-7793d9a319c3
[I 2025-07-11 17:41:42,500] Trial 0 finished with value: -0.0033190266559897097 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: -0.0033190266559897097.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.98 | R2: 0.67
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.14 | R2: 0.62

✅ KNN - Mejor R2: 0.67
📋 Parámetros: {'n_neighbors': 5, 'weights': 'distance', 'leaf_size': 29}

Buscando mejores hiperparámetros para LR...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.47 | R2: -0.00
Fold 1
Fold 2

[I 2025-07-11 17:41:42,574] Trial 1 finished with value: -0.3881151836346195 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 0 with value: -0.0033190266559897097.
[I 2025-07-11 17:41:42,651] Trial 2 finished with value: -0.0033190266559897097 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: -0.0033190266559897097.
[I 2025-07-11 17:41:42,707] Trial 3 finished with value: -0.00444593223650247 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 0 with value: -0.0033190266559897097.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 4.08 | R2: -0.39
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.47 | R2: -0.00
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.47 | R2: -0.00
Fold 1
Fold 2
Fold 3

[I 2025-07-11 17:41:42,763] Trial 4 finished with value: -0.00444593223650247 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 0 with value: -0.0033190266559897097.
[I 2025-07-11 17:41:42,822] Trial 5 finished with value: -0.0033190266559897097 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: -0.0033190266559897097.
[I 2025-07-11 17:41:42,890] Trial 6 finished with value: -0.3881151836346195 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 0 with value: -0.0033190266559897097.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.47 | R2: -0.00
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.47 | R2: -0.00
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 4.08 | R2: -0.39
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 17:41:42,965] Trial 7 finished with value: -0.3881151836346195 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 0 with value: -0.0033190266559897097.
[I 2025-07-11 17:41:43,048] Trial 8 finished with value: -0.3881151836346195 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 0 with value: -0.0033190266559897097.

Fold 5
Running time: 0.1 sec
OOF RMSE: 4.08 | R2: -0.39
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 4.08 | R2: -0.39
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:41:43,221] Trial 9 finished with value: -0.3881151836346195 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 0 with value: -0.0033190266559897097.
[I 2025-07-11 17:41:43,302] Trial 10 finished with value: -0.0033190266559897097 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: -0.0033190266559897097.
[I 2025-07-11 17:41:43,360] Trial 11 finished with value: -0.0033190266559897097 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: -0.0033190266559897097.
[I 2025-07-11 17:41:43,416] Trial 12 finished with value: -0.0033190266559897097 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: -0.0033190266559897097.

Running time: 0.2 sec
OOF RMSE: 4.08 | R2: -0.39
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.47 | R2: -0.00
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.47 | R2: -0.00
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.47 | R2: -0.00

[I 2025-07-11 17:41:43,474] Trial 13 finished with value: -0.0033190266559897097 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: -0.0033190266559897097.
[I 2025-07-11 17:41:43,531] Trial 14 finished with value: -0.0033190266559897097 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: -0.0033190266559897097.
[I 2025-07-11 17:41:43,587] Trial 15 finished with value: -0.0033190266559897097 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: -0.0033190266559897097.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.47 | R2: -0.00
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.47 | R2: -0.00
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.47 | R2: -0.00
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 17:41:43,644] Trial 16 finished with value: -0.0033190266559897097 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: -0.0033190266559897097.
[I 2025-07-11 17:41:43,704] Trial 17 finished with value: -0.0033190266559897097 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: -0.0033190266559897097.
[I 2025-07-11 17:41:43,761] Trial 18 finished with value: -0.0033190266559897097 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: -0.0033190266559897097.
[I 2025-07-11 17:41:43,816] Trial 19 finished with value: -0.0033190266559897097 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: -0.0033190266559897097.

Fold 5
Running time: 0.1 sec
OOF RMSE: 3.47 | R2: -0.00
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.47 | R2: -0.00
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.47 | R2: -0.00
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.47 | R2: -0.00
Fold 1
Fold 2

[I 2025-07-11 17:41:43,875] Trial 20 finished with value: -0.0033190266559897097 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: -0.0033190266559897097.
[I 2025-07-11 17:41:43,935] Trial 21 finished with value: -0.0033190266559897097 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: -0.0033190266559897097.
[I 2025-07-11 17:41:43,991] Trial 22 finished with value: -0.0033190266559897097 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: -0.0033190266559897097.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.47 | R2: -0.00
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.47 | R2: -0.00
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.47 | R2: -0.00
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:41:44,047] Trial 23 finished with value: -0.0033190266559897097 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: -0.0033190266559897097.
[I 2025-07-11 17:41:44,104] Trial 24 finished with value: -0.0033190266559897097 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: -0.0033190266559897097.
[I 2025-07-11 17:41:44,104] A new study created in memory with name: no-name-af8c91d2-4ab0-4a83-b5b6-bfa3f4c5cc98

Running time: 0.1 sec
OOF RMSE: 3.47 | R2: -0.00
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.47 | R2: -0.00

✅ LR - Mejor R2: -0.00
📋 Parámetros: {'fit_intercept': True, 'positive': True}

Buscando mejores hiperparámetros para RF...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:41:45,584] Trial 0 finished with value: 0.4763469307876952 and parameters: {'n_estimators': 100, 'max_depth': 8, 'min_samples_split': 3, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 0 with value: 0.4763469307876952.

Running time: 1.5 sec
OOF RMSE: 2.51 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:41:46,992] Trial 1 finished with value: 0.4584662250823498 and parameters: {'n_estimators': 100, 'max_depth': 13, 'min_samples_split': 4, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 0 with value: 0.4763469307876952.

Running time: 1.4 sec
OOF RMSE: 2.55 | R2: 0.46
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:41:55,046] Trial 2 finished with value: 0.49572671288928005 and parameters: {'n_estimators': 500, 'max_depth': 14, 'min_samples_split': 6, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 2 with value: 0.49572671288928005.

Running time: 8.0 sec
OOF RMSE: 2.46 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:42:02,032] Trial 3 finished with value: 0.36212450582667555 and parameters: {'n_estimators': 300, 'max_depth': 9, 'min_samples_split': 9, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 2 with value: 0.49572671288928005.

Running time: 7.0 sec
OOF RMSE: 2.77 | R2: 0.36
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:42:09,954] Trial 4 finished with value: 0.5086269545579811 and parameters: {'n_estimators': 500, 'max_depth': 7, 'min_samples_split': 4, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 4 with value: 0.5086269545579811.

Running time: 7.9 sec
OOF RMSE: 2.43 | R2: 0.51
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:42:12,897] Trial 5 finished with value: 0.30234012198533056 and parameters: {'n_estimators': 100, 'max_depth': 14, 'min_samples_split': 3, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 4 with value: 0.5086269545579811.

Running time: 2.9 sec
OOF RMSE: 2.90 | R2: 0.30
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:42:23,359] Trial 6 finished with value: 0.32537486595206877 and parameters: {'n_estimators': 500, 'max_depth': 12, 'min_samples_split': 4, 'min_samples_leaf': 5, 'bootstrap': False}. Best is trial 4 with value: 0.5086269545579811.

Running time: 10.5 sec
OOF RMSE: 2.85 | R2: 0.33
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:42:28,541] Trial 7 finished with value: 0.49133435592908814 and parameters: {'n_estimators': 300, 'max_depth': 10, 'min_samples_split': 7, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 4 with value: 0.5086269545579811.

Running time: 5.2 sec
OOF RMSE: 2.47 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:42:35,639] Trial 8 finished with value: 0.29455248140093504 and parameters: {'n_estimators': 300, 'max_depth': 8, 'min_samples_split': 6, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 4 with value: 0.5086269545579811.

Running time: 7.1 sec
OOF RMSE: 2.91 | R2: 0.29
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:42:43,117] Trial 9 finished with value: 0.3299462602260427 and parameters: {'n_estimators': 300, 'max_depth': 14, 'min_samples_split': 7, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 4 with value: 0.5086269545579811.

Running time: 7.5 sec
OOF RMSE: 2.84 | R2: 0.33
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:42:49,391] Trial 10 finished with value: 0.49329898244104264 and parameters: {'n_estimators': 500, 'max_depth': 5, 'min_samples_split': 2, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 4 with value: 0.5086269545579811.

Running time: 6.3 sec
OOF RMSE: 2.47 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:42:55,617] Trial 11 finished with value: 0.49329898244104264 and parameters: {'n_estimators': 500, 'max_depth': 5, 'min_samples_split': 5, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 4 with value: 0.5086269545579811.

Running time: 6.2 sec
OOF RMSE: 2.47 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:43:03,053] Trial 12 finished with value: 0.5015520818833692 and parameters: {'n_estimators': 500, 'max_depth': 7, 'min_samples_split': 9, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 4 with value: 0.5086269545579811.

Running time: 7.4 sec
OOF RMSE: 2.45 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:43:10,411] Trial 13 finished with value: 0.5031438697080516 and parameters: {'n_estimators': 500, 'max_depth': 7, 'min_samples_split': 10, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 4 with value: 0.5086269545579811.

Running time: 7.4 sec
OOF RMSE: 2.44 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:43:17,244] Trial 14 finished with value: 0.501612494004033 and parameters: {'n_estimators': 500, 'max_depth': 6, 'min_samples_split': 10, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 4 with value: 0.5086269545579811.

Running time: 6.8 sec
OOF RMSE: 2.45 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:43:25,888] Trial 15 finished with value: 0.5029764180619611 and parameters: {'n_estimators': 500, 'max_depth': 11, 'min_samples_split': 8, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 4 with value: 0.5086269545579811.

Running time: 8.6 sec
OOF RMSE: 2.44 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:43:33,191] Trial 16 finished with value: 0.5031438697080516 and parameters: {'n_estimators': 500, 'max_depth': 7, 'min_samples_split': 10, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 4 with value: 0.5086269545579811.

Running time: 7.3 sec
OOF RMSE: 2.44 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:43:41,931] Trial 17 finished with value: 0.5012756266784544 and parameters: {'n_estimators': 500, 'max_depth': 9, 'min_samples_split': 5, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 4 with value: 0.5086269545579811.

Running time: 8.7 sec
OOF RMSE: 2.45 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:43:48,549] Trial 18 finished with value: 0.4804647199755443 and parameters: {'n_estimators': 500, 'max_depth': 6, 'min_samples_split': 2, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 4 with value: 0.5086269545579811.

Running time: 6.6 sec
OOF RMSE: 2.50 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:43:50,195] Trial 19 finished with value: 0.5015736106196739 and parameters: {'n_estimators': 100, 'max_depth': 10, 'min_samples_split': 8, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 4 with value: 0.5086269545579811.

Running time: 1.6 sec
OOF RMSE: 2.45 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:43:57,525] Trial 20 finished with value: 0.4948652558064921 and parameters: {'n_estimators': 500, 'max_depth': 7, 'min_samples_split': 5, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 4 with value: 0.5086269545579811.

Running time: 7.3 sec
OOF RMSE: 2.46 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:44:04,834] Trial 21 finished with value: 0.5031438697080516 and parameters: {'n_estimators': 500, 'max_depth': 7, 'min_samples_split': 10, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 4 with value: 0.5086269545579811.

Running time: 7.3 sec
OOF RMSE: 2.44 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:44:12,676] Trial 22 finished with value: 0.5027726072695037 and parameters: {'n_estimators': 500, 'max_depth': 8, 'min_samples_split': 10, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 4 with value: 0.5086269545579811.

Running time: 7.8 sec
OOF RMSE: 2.44 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:44:19,579] Trial 23 finished with value: 0.5005486950842482 and parameters: {'n_estimators': 500, 'max_depth': 6, 'min_samples_split': 9, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 4 with value: 0.5086269545579811.

Running time: 6.9 sec
OOF RMSE: 2.45 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:44:25,943] Trial 24 finished with value: 0.500778748116637 and parameters: {'n_estimators': 500, 'max_depth': 5, 'min_samples_split': 8, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 4 with value: 0.5086269545579811.
[I 2025-07-11 17:44:25,945] A new study created in memory with name: no-name-4df1ec89-7016-476f-ae2e-96f544e0c4d9

Running time: 6.4 sec
OOF RMSE: 2.45 | R2: 0.50

✅ RF - Mejor R2: 0.51
📋 Parámetros: {'n_estimators': 500, 'max_depth': 7, 'min_samples_split': 4, 'min_samples_leaf': 1, 'bootstrap': True}

Buscando mejores hiperparámetros para CAT...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:45:37,167] Trial 0 finished with value: 0.619895369861962 and parameters: {'iterations': 500, 'learning_rate': 0.040535494124929156, 'depth': 10, 'l2_leaf_reg': 9.811507647746636}. Best is trial 0 with value: 0.619895369861962.

Running time: 71.2 sec
OOF RMSE: 2.14 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:46:49,874] Trial 1 finished with value: 0.6341115928934002 and parameters: {'iterations': 2000, 'learning_rate': 0.09807063865420633, 'depth': 8, 'l2_leaf_reg': 8.327488367396}. Best is trial 1 with value: 0.6341115928934002.

Running time: 72.7 sec
OOF RMSE: 2.10 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:47:31,292] Trial 2 finished with value: 0.677082763664405 and parameters: {'iterations': 500, 'learning_rate': 0.053881702249112935, 'depth': 9, 'l2_leaf_reg': 3.923843354437382}. Best is trial 2 with value: 0.677082763664405.

Running time: 41.4 sec
OOF RMSE: 1.97 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:48:07,859] Trial 3 finished with value: 0.6396376616753603 and parameters: {'iterations': 1000, 'learning_rate': 0.05745570137641749, 'depth': 8, 'l2_leaf_reg': 8.235113204794054}. Best is trial 2 with value: 0.677082763664405.

Running time: 36.6 sec
OOF RMSE: 2.08 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:48:21,513] Trial 4 finished with value: 0.6435654053870852 and parameters: {'iterations': 1000, 'learning_rate': 0.016958327882358553, 'depth': 7, 'l2_leaf_reg': 8.94582341515127}. Best is trial 2 with value: 0.677082763664405.

Running time: 13.6 sec
OOF RMSE: 2.07 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:48:30,362] Trial 5 finished with value: 0.6579924163007074 and parameters: {'iterations': 2000, 'learning_rate': 0.06638771743347097, 'depth': 5, 'l2_leaf_reg': 6.507838606559967}. Best is trial 2 with value: 0.677082763664405.

Running time: 8.8 sec
OOF RMSE: 2.03 | R2: 0.66
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:48:34,562] Trial 6 finished with value: 0.6498253688390813 and parameters: {'iterations': 1000, 'learning_rate': 0.05924943303040634, 'depth': 5, 'l2_leaf_reg': 6.317191379327174}. Best is trial 2 with value: 0.677082763664405.

Running time: 4.2 sec
OOF RMSE: 2.05 | R2: 0.65
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:48:47,397] Trial 7 finished with value: 0.6745930406078671 and parameters: {'iterations': 2000, 'learning_rate': 0.01222833403553537, 'depth': 6, 'l2_leaf_reg': 5.167290502110568}. Best is trial 2 with value: 0.677082763664405.

Running time: 12.8 sec
OOF RMSE: 1.98 | R2: 0.67
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:49:00,435] Trial 8 finished with value: 0.616131181422818 and parameters: {'iterations': 2000, 'learning_rate': 0.06739750150758424, 'depth': 6, 'l2_leaf_reg': 8.610280835839973}. Best is trial 2 with value: 0.677082763664405.

Running time: 13.0 sec
OOF RMSE: 2.15 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:49:41,058] Trial 9 finished with value: 0.6556941950684636 and parameters: {'iterations': 500, 'learning_rate': 0.026985343742168065, 'depth': 9, 'l2_leaf_reg': 5.243906771594366}. Best is trial 2 with value: 0.677082763664405.

Running time: 40.6 sec
OOF RMSE: 2.03 | R2: 0.66
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:50:53,372] Trial 10 finished with value: 0.6594275580296529 and parameters: {'iterations': 500, 'learning_rate': 0.03082888713195156, 'depth': 10, 'l2_leaf_reg': 1.7967180689884095}. Best is trial 2 with value: 0.677082763664405.

Running time: 72.3 sec
OOF RMSE: 2.02 | R2: 0.66
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:50:54,908] Trial 11 finished with value: 0.6285446379314452 and parameters: {'iterations': 500, 'learning_rate': 0.010703363081551018, 'depth': 4, 'l2_leaf_reg': 3.5207268141294645}. Best is trial 2 with value: 0.677082763664405.

Running time: 1.5 sec
OOF RMSE: 2.11 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:51:21,884] Trial 12 finished with value: 0.6658937423174057 and parameters: {'iterations': 2000, 'learning_rate': 0.018877495113808217, 'depth': 7, 'l2_leaf_reg': 4.218665558911072}. Best is trial 2 with value: 0.677082763664405.

Running time: 27.0 sec
OOF RMSE: 2.00 | R2: 0.67
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:51:40,253] Trial 13 finished with value: 0.664252168194986 and parameters: {'iterations': 500, 'learning_rate': 0.01116976861586945, 'depth': 8, 'l2_leaf_reg': 2.528414887679702}. Best is trial 2 with value: 0.677082763664405.

Running time: 18.4 sec
OOF RMSE: 2.01 | R2: 0.66
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:51:53,751] Trial 14 finished with value: 0.6668267409580385 and parameters: {'iterations': 2000, 'learning_rate': 0.043806006694847216, 'depth': 6, 'l2_leaf_reg': 4.673990267652174}. Best is trial 2 with value: 0.677082763664405.

Running time: 13.5 sec
OOF RMSE: 2.00 | R2: 0.67
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:54:40,266] Trial 15 finished with value: 0.6671069378889692 and parameters: {'iterations': 2000, 'learning_rate': 0.020852362997177614, 'depth': 9, 'l2_leaf_reg': 3.209526617371626}. Best is trial 2 with value: 0.677082763664405.
[I 2025-07-11 17:54:40,267] A new study created in memory with name: no-name-02e4022f-0fff-4667-85be-2defd08e23d8
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.218e-01, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.009e+00, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.272e+00, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.539e-01, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.443e+00, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 17:54:40,372] Trial 0 finished with value: 0.4866185898146087 and parameters: {'alpha': 0.012048222747572826, 'l1_ratio': 0.7923276049847829}. Best is trial 0 with value: 0.4866185898146087.

Running time: 166.5 sec
OOF RMSE: 2.00 | R2: 0.67

✅ CAT - Mejor R2: 0.68
📋 Parámetros: {'iterations': 500, 'learning_rate': 0.053881702249112935, 'depth': 9, 'l2_leaf_reg': 3.923843354437382}

Buscando mejores hiperparámetros para EN...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.48 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.731e-01, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.486e+00, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 17:54:40,474] Trial 1 finished with value: 0.48542444347719005 and parameters: {'alpha': 0.018986238247341393, 'l1_ratio': 0.9647680705272078}. Best is trial 0 with value: 0.4866185898146087.
[I 2025-07-11 17:54:40,599] Trial 2 finished with value: 0.5130591413013901 and parameters: {'alpha': 0.05348860299000638, 'l1_ratio': 0.5201788752005865}. Best is trial 2 with value: 0.5130591413013901.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.388e+01, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.529e+01, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.510e+01, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(

Running time: 0.1 sec
OOF RMSE: 2.49 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.42 | R2: 0.51
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.060e+01, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.087e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 17:54:40,717] Trial 3 finished with value: 0.4450853441212309 and parameters: {'alpha': 0.0036482871548868625, 'l1_ratio': 0.5554313200636701}. Best is trial 2 with value: 0.5130591413013901.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.746e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.430e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.454e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.905e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.58 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.185e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 17:54:40,925] Trial 4 finished with value: 0.03984657598811736 and parameters: {'alpha': 0.0004604228832441145, 'l1_ratio': 0.8665438255430067}. Best is trial 2 with value: 0.5130591413013901.
[I 2025-07-11 17:54:41,071] Trial 5 finished with value: 0.48461439075708046 and parameters: {'alpha': 0.389500768875646, 'l1_ratio': 0.9480586575113231}. Best is trial 2 with value: 0.5130591413013901.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.511e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(

Running time: 0.2 sec
OOF RMSE: 3.40 | R2: 0.04
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.49 | R2: 0.48
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.022e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.177e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.687e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.686e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 17:54:41,258] Trial 6 finished with value: 0.15473269786814847 and parameters: {'alpha': 0.000725640576977084, 'l1_ratio': 0.5171637029112136}. Best is trial 2 with value: 0.5130591413013901.

Fold 3
Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 3.19 | R2: 0.15
Fold 1
Fold 2
Fold 3

[I 2025-07-11 17:54:41,386] Trial 7 finished with value: 0.44103284876938476 and parameters: {'alpha': 0.9978596970436505, 'l1_ratio': 0.4618007444649933}. Best is trial 2 with value: 0.5130591413013901.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.022e+00, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.269e+00, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.240e+01, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.076e+00, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.808e+01, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 17:54:41,520] Trial 8 finished with value: 0.5028851598588819 and parameters: {'alpha': 0.02267317415120494, 'l1_ratio': 0.24035035007558248}. Best is trial 2 with value: 0.5130591413013901.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.59 | R2: 0.44
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.44 | R2: 0.50
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.343e+01, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.550e+01, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.362e+01, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.863e+01, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.107e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 17:54:41,647] Trial 9 finished with value: 0.3919645213476869 and parameters: {'alpha': 0.0031570784466951056, 'l1_ratio': 0.7977610815357531}. Best is trial 2 with value: 0.5130591413013901.
[I 2025-07-11 17:54:41,753] Trial 10 finished with value: 0.3575121784425318 and parameters: {'alpha': 7.03396897325965, 'l1_ratio': 0.03302825657873776}. Best is trial 2 with value: 0.5130591413013901.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.70 | R2: 0.39
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.78 | R2: 0.36
Fold 1

[I 2025-07-11 17:54:41,871] Trial 11 finished with value: 0.5217386929275545 and parameters: {'alpha': 0.1116389377189639, 'l1_ratio': 0.22592906385613232}. Best is trial 11 with value: 0.5217386929275545.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.40 | R2: 0.52
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 17:54:42,036] Trial 12 finished with value: 0.519512678912134 and parameters: {'alpha': 0.18414211669552602, 'l1_ratio': 0.2596248999667341}. Best is trial 11 with value: 0.5217386929275545.
[I 2025-07-11 17:54:42,136] Trial 13 finished with value: 0.5187452899085108 and parameters: {'alpha': 0.20871597418449697, 'l1_ratio': 0.2194420733725841}. Best is trial 11 with value: 0.5217386929275545.

Fold 5
Running time: 0.2 sec
OOF RMSE: 2.40 | R2: 0.52
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.40 | R2: 0.52
Fold 1
Fold 2
Fold 3

[I 2025-07-11 17:54:42,234] Trial 14 finished with value: 0.4074941612475158 and parameters: {'alpha': 1.7664909996543732, 'l1_ratio': 0.27779516668263055}. Best is trial 11 with value: 0.5217386929275545.
[I 2025-07-11 17:54:42,370] Trial 15 finished with value: 0.5243340526797808 and parameters: {'alpha': 0.14014828482341338, 'l1_ratio': 0.02051772669299834}. Best is trial 15 with value: 0.5243340526797808.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.67 | R2: 0.41
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.39 | R2: 0.52
Fold 1

[I 2025-07-11 17:54:42,503] Trial 16 finished with value: 0.5220298522637212 and parameters: {'alpha': 0.09698686069982408, 'l1_ratio': 0.07385906647314011}. Best is trial 15 with value: 0.5243340526797808.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.538e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.382e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.40 | R2: 0.52
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.506e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.977e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.837e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 17:54:42,638] Trial 17 finished with value: 0.05034329869649068 and parameters: {'alpha': 0.0001404913793858825, 'l1_ratio': 0.012819185199467925}. Best is trial 15 with value: 0.5243340526797808.
[I 2025-07-11 17:54:42,727] Trial 18 finished with value: 0.4816190584775881 and parameters: {'alpha': 0.8954898156865565, 'l1_ratio': 0.11292673113059426}. Best is trial 15 with value: 0.5243340526797808.

Fold 5
Running time: 0.1 sec
OOF RMSE: 3.38 | R2: 0.05
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.50 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:54:42,832] Trial 19 finished with value: 0.5167206441532602 and parameters: {'alpha': 0.0636906515188305, 'l1_ratio': 0.38628329901516817}. Best is trial 15 with value: 0.5243340526797808.
[I 2025-07-11 17:54:42,926] Trial 20 finished with value: 0.3145060214052493 and parameters: {'alpha': 6.0220977439471355, 'l1_ratio': 0.09122035807925621}. Best is trial 15 with value: 0.5243340526797808.

Running time: 0.1 sec
OOF RMSE: 2.41 | R2: 0.52
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.87 | R2: 0.31
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.40 | R2: 0.52

[I 2025-07-11 17:54:43,032] Trial 21 finished with value: 0.5219685841701838 and parameters: {'alpha': 0.10064710988819732, 'l1_ratio': 0.14763581029635983}. Best is trial 15 with value: 0.5243340526797808.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.953e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.616e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.746e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.615e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.147e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 17:54:43,159] Trial 22 finished with value: 0.47902866608651673 and parameters: {'alpha': 0.007678560754460968, 'l1_ratio': 0.13734776471155052}. Best is trial 15 with value: 0.5243340526797808.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.50 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:54:43,250] Trial 23 finished with value: 0.5152369696879378 and parameters: {'alpha': 0.5439229547300544, 'l1_ratio': 0.004407924744420061}. Best is trial 15 with value: 0.5243340526797808.
[I 2025-07-11 17:54:43,352] Trial 24 finished with value: 0.5163407700383222 and parameters: {'alpha': 0.0616000295271695, 'l1_ratio': 0.34485248602557184}. Best is trial 15 with value: 0.5243340526797808.
[I 2025-07-11 17:54:43,354] A new study created in memory with name: no-name-679f1e3e-ba63-46cd-bcca-5a13a699dffb

Running time: 0.1 sec
OOF RMSE: 2.41 | R2: 0.52
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.41 | R2: 0.52

✅ EN - Mejor R2: 0.52
📋 Parámetros: {'alpha': 0.14014828482341338, 'l1_ratio': 0.02051772669299834}

🔍 Optimizando en C2X_rhown_9x9_depth_lt_1...
Buscando mejores hiperparámetros para XGB...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:54:53,503] Trial 0 finished with value: 0.41157307565438894 and parameters: {'n_estimators': 1000, 'learning_rate': 0.017247029641393734, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.7815878845392418, 'colsample_bytree': 0.9408736252494311}. Best is trial 0 with value: 0.41157307565438894.

Running time: 10.1 sec
OOF RMSE: 2.66 | R2: 0.41
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:55:00,595] Trial 1 finished with value: 0.3572193348993262 and parameters: {'n_estimators': 1000, 'learning_rate': 0.030139954637531358, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.8054053624449905, 'colsample_bytree': 0.7993710488680577}. Best is trial 0 with value: 0.41157307565438894.

Running time: 7.1 sec
OOF RMSE: 2.78 | R2: 0.36
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:55:16,439] Trial 2 finished with value: 0.39603042920979215 and parameters: {'n_estimators': 2000, 'learning_rate': 0.019616033602438365, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.8124281541638948, 'colsample_bytree': 0.9939578802851781}. Best is trial 0 with value: 0.41157307565438894.

Running time: 15.8 sec
OOF RMSE: 2.69 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:55:20,685] Trial 3 finished with value: 0.4349610397471553 and parameters: {'n_estimators': 1000, 'learning_rate': 0.017728202676264886, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.7667737960603765, 'colsample_bytree': 0.8375007726629176}. Best is trial 3 with value: 0.4349610397471553.

Running time: 4.2 sec
OOF RMSE: 2.61 | R2: 0.43
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:55:28,660] Trial 4 finished with value: 0.37161779716491583 and parameters: {'n_estimators': 1000, 'learning_rate': 0.03747286010098613, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.8132481771123847, 'colsample_bytree': 0.9619999959529725}. Best is trial 3 with value: 0.4349610397471553.

Running time: 8.0 sec
OOF RMSE: 2.75 | R2: 0.37
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:55:32,329] Trial 5 finished with value: 0.3914108529579374 and parameters: {'n_estimators': 500, 'learning_rate': 0.005001866676259352, 'max_depth': 8, 'min_child_weight': 3, 'subsample': 0.8103121181479862, 'colsample_bytree': 0.8422503087432671}. Best is trial 3 with value: 0.4349610397471553.

Running time: 3.7 sec
OOF RMSE: 2.70 | R2: 0.39
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:55:44,405] Trial 6 finished with value: 0.31914341692636106 and parameters: {'n_estimators': 2000, 'learning_rate': 0.017301516470040194, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.8918550999138035, 'colsample_bytree': 0.9228521015547531}. Best is trial 3 with value: 0.4349610397471553.

Running time: 12.1 sec
OOF RMSE: 2.86 | R2: 0.32
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:55:46,712] Trial 7 finished with value: 0.4237381556482066 and parameters: {'n_estimators': 500, 'learning_rate': 0.007958779092745285, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.7226339609892106, 'colsample_bytree': 0.8991765110323415}. Best is trial 3 with value: 0.4349610397471553.

Running time: 2.3 sec
OOF RMSE: 2.63 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:55:59,099] Trial 8 finished with value: 0.4244508039701491 and parameters: {'n_estimators': 2000, 'learning_rate': 0.05311074760552568, 'max_depth': 8, 'min_child_weight': 1, 'subsample': 0.6190786840735533, 'colsample_bytree': 0.8178857487281375}. Best is trial 3 with value: 0.4349610397471553.

Running time: 12.4 sec
OOF RMSE: 2.63 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:56:03,985] Trial 9 finished with value: 0.30317655964217805 and parameters: {'n_estimators': 1000, 'learning_rate': 0.008992313034843121, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.9110917372509816, 'colsample_bytree': 0.6631126704299947}. Best is trial 3 with value: 0.4349610397471553.

Running time: 4.9 sec
OOF RMSE: 2.89 | R2: 0.30
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:56:08,668] Trial 10 finished with value: 0.41715831586936347 and parameters: {'n_estimators': 1000, 'learning_rate': 0.07237905997515982, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.666309853194456, 'colsample_bytree': 0.735664895453543}. Best is trial 3 with value: 0.4349610397471553.

Running time: 4.7 sec
OOF RMSE: 2.65 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:56:19,211] Trial 11 finished with value: 0.3825063518281153 and parameters: {'n_estimators': 2000, 'learning_rate': 0.0812700952436181, 'max_depth': 8, 'min_child_weight': 4, 'subsample': 0.6088884861065692, 'colsample_bytree': 0.7910170324906766}. Best is trial 3 with value: 0.4349610397471553.

Running time: 10.5 sec
OOF RMSE: 2.72 | R2: 0.38
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:56:29,482] Trial 12 finished with value: 0.42790128072212463 and parameters: {'n_estimators': 2000, 'learning_rate': 0.04478243915954065, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.600466914153322, 'colsample_bytree': 0.850287065680132}. Best is trial 3 with value: 0.4349610397471553.

Running time: 10.3 sec
OOF RMSE: 2.62 | R2: 0.43
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:56:39,035] Trial 13 finished with value: 0.20601720853527183 and parameters: {'n_estimators': 2000, 'learning_rate': 0.035057745626569284, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.9838487560201581, 'colsample_bytree': 0.8654974804735113}. Best is trial 3 with value: 0.4349610397471553.

Running time: 9.5 sec
OOF RMSE: 3.09 | R2: 0.21
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:56:41,247] Trial 14 finished with value: 0.4497764324713798 and parameters: {'n_estimators': 500, 'learning_rate': 0.01232860580624704, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.7064114583540594, 'colsample_bytree': 0.7435181546451316}. Best is trial 14 with value: 0.4497764324713798.

Running time: 2.2 sec
OOF RMSE: 2.57 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:56:43,517] Trial 15 finished with value: 0.4464793030901867 and parameters: {'n_estimators': 500, 'learning_rate': 0.011342998249005103, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.7115969052191741, 'colsample_bytree': 0.7206617379629847}. Best is trial 14 with value: 0.4497764324713798.

Running time: 2.3 sec
OOF RMSE: 2.58 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:56:45,667] Trial 16 finished with value: 0.43562796192519737 and parameters: {'n_estimators': 500, 'learning_rate': 0.010452413086558247, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.7015585523226253, 'colsample_bytree': 0.6030306940386693}. Best is trial 14 with value: 0.4497764324713798.

Running time: 2.1 sec
OOF RMSE: 2.60 | R2: 0.44
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:56:47,941] Trial 17 finished with value: 0.4461541471722257 and parameters: {'n_estimators': 500, 'learning_rate': 0.011791641657814949, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.6864815082267269, 'colsample_bytree': 0.7251618582665939}. Best is trial 14 with value: 0.4497764324713798.

Running time: 2.3 sec
OOF RMSE: 2.58 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:56:50,749] Trial 18 finished with value: 0.41332646797044126 and parameters: {'n_estimators': 500, 'learning_rate': 0.0054732684720636094, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.7535710163276196, 'colsample_bytree': 0.7274012007479315}. Best is trial 14 with value: 0.4497764324713798.

Running time: 2.8 sec
OOF RMSE: 2.66 | R2: 0.41
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:56:52,845] Trial 19 finished with value: 0.43125986652930237 and parameters: {'n_estimators': 500, 'learning_rate': 0.013504052190282504, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.6666218252397915, 'colsample_bytree': 0.6719665164994505}. Best is trial 14 with value: 0.4497764324713798.

Running time: 2.1 sec
OOF RMSE: 2.61 | R2: 0.43
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:56:55,736] Trial 20 finished with value: 0.36844439555717445 and parameters: {'n_estimators': 500, 'learning_rate': 0.007110428129609381, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.8590207723303158, 'colsample_bytree': 0.7618237779292832}. Best is trial 14 with value: 0.4497764324713798.

Running time: 2.9 sec
OOF RMSE: 2.75 | R2: 0.37
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:56:57,922] Trial 21 finished with value: 0.44311613933389915 and parameters: {'n_estimators': 500, 'learning_rate': 0.012144801675257519, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.6786098911266881, 'colsample_bytree': 0.6949538223666457}. Best is trial 14 with value: 0.4497764324713798.

Running time: 2.2 sec
OOF RMSE: 2.59 | R2: 0.44
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:57:00,132] Trial 22 finished with value: 0.45553058176714345 and parameters: {'n_estimators': 500, 'learning_rate': 0.023699229508764526, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.7298039366397602, 'colsample_bytree': 0.6246729134472505}. Best is trial 22 with value: 0.45553058176714345.

Running time: 2.2 sec
OOF RMSE: 2.56 | R2: 0.46
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:57:02,262] Trial 23 finished with value: 0.45294599537659397 and parameters: {'n_estimators': 500, 'learning_rate': 0.024298963689704974, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.7272158419200851, 'colsample_bytree': 0.6346976392208891}. Best is trial 22 with value: 0.45553058176714345.

Running time: 2.1 sec
OOF RMSE: 2.56 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:57:04,346] Trial 24 finished with value: 0.453356579608156 and parameters: {'n_estimators': 500, 'learning_rate': 0.025026727622172742, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.7353103655870455, 'colsample_bytree': 0.6063177207020785}. Best is trial 22 with value: 0.45553058176714345.
[I 2025-07-11 17:57:04,347] A new study created in memory with name: no-name-7241446f-1e58-4af5-8942-48443ab0ca97

Running time: 2.1 sec
OOF RMSE: 2.56 | R2: 0.45

✅ XGB - Mejor R2: 0.46
📋 Parámetros: {'n_estimators': 500, 'learning_rate': 0.023699229508764526, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.7298039366397602, 'colsample_bytree': 0.6246729134472505}

Buscando mejores hiperparámetros para LBM...
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 17:57:05,334] Trial 0 finished with value: 0.49664999580541724 and parameters: {'learning_rate': 0.012816372686428329, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 14, 'subsample': 0.6083834497228939, 'colsample_bytree': 0.6766438711823742, 'n_estimators': 2000}. Best is trial 0 with value: 0.49664999580541724.

Fold 5
Running time: 1.0 sec
OOF RMSE: 2.46 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:57:06,215] Trial 1 finished with value: 0.48298430754003696 and parameters: {'learning_rate': 0.031059856813067735, 'num_leaves': 40, 'max_depth': 5, 'min_child_samples': 10, 'subsample': 0.7197229895136374, 'colsample_bytree': 0.9210575846034601, 'n_estimators': 2000}. Best is trial 0 with value: 0.49664999580541724.

Running time: 0.9 sec
OOF RMSE: 2.49 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 17:57:06,789] Trial 2 finished with value: 0.3988662223822166 and parameters: {'learning_rate': 0.025537483131528586, 'num_leaves': 80, 'max_depth': 8, 'min_child_samples': 18, 'subsample': 0.6222730780104302, 'colsample_bytree': 0.8258608692299584, 'n_estimators': 1000}. Best is trial 0 with value: 0.49664999580541724.

Fold 5
Running time: 0.6 sec
OOF RMSE: 2.69 | R2: 0.40
Fold 1
Fold 2

[I 2025-07-11 17:57:07,053] Trial 3 finished with value: 0.39321279931469455 and parameters: {'learning_rate': 0.009245052002608296, 'num_leaves': 60, 'max_depth': 6, 'min_child_samples': 11, 'subsample': 0.855245437416579, 'colsample_bytree': 0.7562810672902257, 'n_estimators': 500}. Best is trial 0 with value: 0.49664999580541724.

Fold 3
Fold 4
Fold 5
Running time: 0.3 sec
OOF RMSE: 2.70 | R2: 0.39
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:57:07,336] Trial 4 finished with value: 0.3548567415921422 and parameters: {'learning_rate': 0.01929739190814036, 'num_leaves': 80, 'max_depth': 7, 'min_child_samples': 18, 'subsample': 0.6735793154818136, 'colsample_bytree': 0.9369310900071643, 'n_estimators': 500}. Best is trial 0 with value: 0.49664999580541724.

Running time: 0.3 sec
OOF RMSE: 2.78 | R2: 0.35
Fold 1
Fold 2
Fold 3

[I 2025-07-11 17:57:07,803] Trial 5 finished with value: 0.37363501431476576 and parameters: {'learning_rate': 0.057561415976490456, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 19, 'subsample': 0.9896191183101829, 'colsample_bytree': 0.921709819661039, 'n_estimators': 1000}. Best is trial 0 with value: 0.49664999580541724.

Fold 4
Fold 5
Running time: 0.5 sec
OOF RMSE: 2.74 | R2: 0.37
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:57:08,362] Trial 6 finished with value: 0.4097009669136057 and parameters: {'learning_rate': 0.041923986676765994, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 6, 'subsample': 0.7302233334670172, 'colsample_bytree': 0.6485685346142129, 'n_estimators': 1000}. Best is trial 0 with value: 0.49664999580541724.

Running time: 0.6 sec
OOF RMSE: 2.66 | R2: 0.41
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 17:57:09,344] Trial 7 finished with value: 0.5187565998985002 and parameters: {'learning_rate': 0.009592169296099901, 'num_leaves': 80, 'max_depth': 6, 'min_child_samples': 10, 'subsample': 0.9124465110406608, 'colsample_bytree': 0.8195351278219585, 'n_estimators': 2000}. Best is trial 7 with value: 0.5187565998985002.

Fold 5
Running time: 1.0 sec
OOF RMSE: 2.40 | R2: 0.52
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:57:10,441] Trial 8 finished with value: 0.4398920946896595 and parameters: {'learning_rate': 0.005295336389520882, 'num_leaves': 60, 'max_depth': 7, 'min_child_samples': 9, 'subsample': 0.6475472570758988, 'colsample_bytree': 0.7443291673190001, 'n_estimators': 2000}. Best is trial 7 with value: 0.5187565998985002.

Running time: 1.1 sec
OOF RMSE: 2.59 | R2: 0.44
Fold 1
Fold 2
Fold 3

[I 2025-07-11 17:57:10,821] Trial 9 finished with value: 0.3438721303128325 and parameters: {'learning_rate': 0.01111659021246449, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 19, 'subsample': 0.6450146161146185, 'colsample_bytree': 0.6929921605329745, 'n_estimators': 1000}. Best is trial 7 with value: 0.5187565998985002.

Fold 4
Fold 5
Running time: 0.4 sec
OOF RMSE: 2.81 | R2: 0.34
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:57:11,749] Trial 10 finished with value: 0.38895709122032174 and parameters: {'learning_rate': 0.09353855434382231, 'num_leaves': 80, 'max_depth': 8, 'min_child_samples': 24, 'subsample': 0.8995034294692827, 'colsample_bytree': 0.8475447014014943, 'n_estimators': 2000}. Best is trial 7 with value: 0.5187565998985002.

Running time: 0.9 sec
OOF RMSE: 2.71 | R2: 0.39
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:57:12,732] Trial 11 finished with value: 0.5038861912326356 and parameters: {'learning_rate': 0.013130139517355898, 'num_leaves': 40, 'max_depth': 7, 'min_child_samples': 14, 'subsample': 0.9396411763175538, 'colsample_bytree': 0.6362215802865288, 'n_estimators': 2000}. Best is trial 7 with value: 0.5187565998985002.

Running time: 1.0 sec
OOF RMSE: 2.44 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 17:57:13,614] Trial 12 finished with value: 0.47616972672686386 and parameters: {'learning_rate': 0.006182941006948658, 'num_leaves': 40, 'max_depth': 6, 'min_child_samples': 14, 'subsample': 0.988709720005443, 'colsample_bytree': 0.615850195515903, 'n_estimators': 2000}. Best is trial 7 with value: 0.5187565998985002.

Fold 5
Running time: 0.9 sec
OOF RMSE: 2.51 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:57:15,098] Trial 13 finished with value: 0.34853669968955514 and parameters: {'learning_rate': 0.015622930294623362, 'num_leaves': 40, 'max_depth': 7, 'min_child_samples': 5, 'subsample': 0.9170033653912011, 'colsample_bytree': 0.9994542370626456, 'n_estimators': 2000}. Best is trial 7 with value: 0.5187565998985002.

Running time: 1.5 sec
OOF RMSE: 2.80 | R2: 0.35
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 17:57:15,910] Trial 14 finished with value: 0.46126626532192994 and parameters: {'learning_rate': 0.007833840571421094, 'num_leaves': 40, 'max_depth': 5, 'min_child_samples': 12, 'subsample': 0.8120712184912224, 'colsample_bytree': 0.7708168561391491, 'n_estimators': 2000}. Best is trial 7 with value: 0.5187565998985002.

Fold 5
Running time: 0.8 sec
OOF RMSE: 2.54 | R2: 0.46
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:57:17,251] Trial 15 finished with value: 0.5022246153417451 and parameters: {'learning_rate': 0.01928778267542831, 'num_leaves': 80, 'max_depth': 8, 'min_child_samples': 8, 'subsample': 0.9308643656210607, 'colsample_bytree': 0.872950338728826, 'n_estimators': 2000}. Best is trial 7 with value: 0.5187565998985002.

Running time: 1.3 sec
OOF RMSE: 2.45 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 17:57:17,552] Trial 16 finished with value: 0.39942144906408383 and parameters: {'learning_rate': 0.009181409272621417, 'num_leaves': 80, 'max_depth': 7, 'min_child_samples': 16, 'subsample': 0.8464594446274002, 'colsample_bytree': 0.706616549058875, 'n_estimators': 500}. Best is trial 7 with value: 0.5187565998985002.

Fold 5
Running time: 0.3 sec
OOF RMSE: 2.69 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:57:18,396] Trial 17 finished with value: 0.3889688294894452 and parameters: {'learning_rate': 0.013224080840987362, 'num_leaves': 40, 'max_depth': 6, 'min_child_samples': 23, 'subsample': 0.9640772134277087, 'colsample_bytree': 0.6025770559670226, 'n_estimators': 2000}. Best is trial 7 with value: 0.5187565998985002.

Running time: 0.8 sec
OOF RMSE: 2.71 | R2: 0.39
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:57:19,343] Trial 18 finished with value: 0.4327413078948489 and parameters: {'learning_rate': 0.006891124380103428, 'num_leaves': 60, 'max_depth': 6, 'min_child_samples': 13, 'subsample': 0.8534383960294291, 'colsample_bytree': 0.7996500990341213, 'n_estimators': 2000}. Best is trial 7 with value: 0.5187565998985002.

Running time: 0.9 sec
OOF RMSE: 2.61 | R2: 0.43
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 17:57:19,666] Trial 19 finished with value: 0.4339170381869365 and parameters: {'learning_rate': 0.02802790572453459, 'num_leaves': 80, 'max_depth': 7, 'min_child_samples': 7, 'subsample': 0.7860604666318834, 'colsample_bytree': 0.7275499446046404, 'n_estimators': 500}. Best is trial 7 with value: 0.5187565998985002.

Fold 5
Running time: 0.3 sec
OOF RMSE: 2.61 | R2: 0.43
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:57:20,485] Trial 20 finished with value: 0.4962062993758525 and parameters: {'learning_rate': 0.015309921728519214, 'num_leaves': 40, 'max_depth': 5, 'min_child_samples': 16, 'subsample': 0.8844592076463089, 'colsample_bytree': 0.7894184514366682, 'n_estimators': 2000}. Best is trial 7 with value: 0.5187565998985002.

Running time: 0.8 sec
OOF RMSE: 2.46 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:57:21,838] Trial 21 finished with value: 0.496521880391108 and parameters: {'learning_rate': 0.019955962631699638, 'num_leaves': 80, 'max_depth': 8, 'min_child_samples': 8, 'subsample': 0.9272933407188739, 'colsample_bytree': 0.8687864177346616, 'n_estimators': 2000}. Best is trial 7 with value: 0.5187565998985002.

Running time: 1.3 sec
OOF RMSE: 2.46 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:57:23,126] Trial 22 finished with value: 0.5145254302300011 and parameters: {'learning_rate': 0.010366022474639573, 'num_leaves': 80, 'max_depth': 8, 'min_child_samples': 10, 'subsample': 0.9448371020413298, 'colsample_bytree': 0.8822725507474576, 'n_estimators': 2000}. Best is trial 7 with value: 0.5187565998985002.

Running time: 1.3 sec
OOF RMSE: 2.42 | R2: 0.51
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:57:24,379] Trial 23 finished with value: 0.5115566646746608 and parameters: {'learning_rate': 0.010795756433922022, 'num_leaves': 80, 'max_depth': 8, 'min_child_samples': 10, 'subsample': 0.9578720575415092, 'colsample_bytree': 0.8910707418248479, 'n_estimators': 2000}. Best is trial 7 with value: 0.5187565998985002.

Running time: 1.2 sec
OOF RMSE: 2.42 | R2: 0.51
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:57:25,655] Trial 24 finished with value: 0.521486192372547 and parameters: {'learning_rate': 0.009287415114544437, 'num_leaves': 80, 'max_depth': 8, 'min_child_samples': 10, 'subsample': 0.9568085814792049, 'colsample_bytree': 0.8834108826852782, 'n_estimators': 2000}. Best is trial 24 with value: 0.521486192372547.
[I 2025-07-11 17:57:25,656] A new study created in memory with name: no-name-f45c8e36-6d00-4770-b240-32e308ffcd82

Running time: 1.3 sec
OOF RMSE: 2.40 | R2: 0.52

✅ LBM - Mejor R2: 0.52
📋 Parámetros: {'learning_rate': 0.009287415114544437, 'num_leaves': 80, 'max_depth': 8, 'min_child_samples': 10, 'subsample': 0.9568085814792049, 'colsample_bytree': 0.8834108826852782, 'n_estimators': 2000}

Buscando mejores hiperparámetros para MLP...
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 17:57:26,473] Trial 0 finished with value: 0.41957130958389033 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 1.5564708141991737e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.006897557882418587}. Best is trial 0 with value: 0.41957130958389033.

Fold 5
Running time: 0.8 sec
OOF RMSE: 2.64 | R2: 0.42
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

[I 2025-07-11 17:57:28,003] Trial 1 finished with value: 0.3707675514627842 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.061839834748804424, 'learning_rate': 'adaptive', 'learning_rate_init': 0.007305524846209587}. Best is trial 0 with value: 0.41957130958389033.

Running time: 1.5 sec
OOF RMSE: 2.75 | R2: 0.37
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 17:57:28,951] Trial 2 finished with value: 0.38378444767870934 and parameters: {'hidden_layer_sizes': '50', 'activation': 'relu', 'solver': 'adam', 'alpha': 1.946620947328902e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00014037008031291014}. Best is trial 0 with value: 0.41957130958389033.

Fold 5
Running time: 0.9 sec
OOF RMSE: 2.72 | R2: 0.38
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

[I 2025-07-11 17:57:30,415] Trial 3 finished with value: 0.3927219668504309 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.032826693465394935, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00017589377035054504}. Best is trial 0 with value: 0.41957130958389033.

Running time: 1.5 sec
OOF RMSE: 2.70 | R2: 0.39
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 17:57:31,876] Trial 4 finished with value: 0.3914705673658021 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 3.644626248522763e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.0006292982768674838}. Best is trial 0 with value: 0.41957130958389033.

Fold 5
Running time: 1.5 sec
OOF RMSE: 2.70 | R2: 0.39
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 17:57:34,032] Trial 5 finished with value: 0.3451875241089256 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.00017401892403159843, 'learning_rate': 'constant', 'learning_rate_init': 0.0001097428865444433}. Best is trial 0 with value: 0.41957130958389033.

Fold 5
Running time: 2.2 sec
OOF RMSE: 2.81 | R2: 0.35
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3
Fold 4

[I 2025-07-11 17:57:34,887] Trial 6 finished with value: 0.3726057529365132 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'relu', 'solver': 'sgd', 'alpha': 4.246560421003199e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.00025944542789521256}. Best is trial 0 with value: 0.41957130958389033.

Fold 5
Running time: 0.8 sec
OOF RMSE: 2.75 | R2: 0.37
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:57:36,108] Trial 7 finished with value: 0.4312229097642267 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0270302861227659, 'learning_rate': 'constant', 'learning_rate_init': 0.002544334209064755}. Best is trial 7 with value: 0.4312229097642267.

Running time: 1.2 sec
OOF RMSE: 2.61 | R2: 0.43
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

[I 2025-07-11 17:57:37,358] Trial 8 finished with value: 0.3469948726383335 and parameters: {'hidden_layer_sizes': '50', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.011247989931944589, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0037164567750195697}. Best is trial 7 with value: 0.4312229097642267.

Running time: 1.2 sec
OOF RMSE: 2.80 | R2: 0.35
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 17:57:38,545] Trial 9 finished with value: 0.4127175072333036 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.0001348951543215851, 'learning_rate': 'constant', 'learning_rate_init': 0.0004949971667203544}. Best is trial 7 with value: 0.4312229097642267.

Fold 5
Running time: 1.2 sec
OOF RMSE: 2.66 | R2: 0.41
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 17:57:39,826] Trial 10 finished with value: 0.43233933426519155 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0030423713746818063, 'learning_rate': 'constant', 'learning_rate_init': 0.0019293864534017412}. Best is trial 10 with value: 0.43233933426519155.

Fold 4
Fold 5
Running time: 1.3 sec
OOF RMSE: 2.61 | R2: 0.43
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

[I 2025-07-11 17:57:41,193] Trial 11 finished with value: 0.4289058276936707 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0032285432384344605, 'learning_rate': 'constant', 'learning_rate_init': 0.0021515869215024803}. Best is trial 10 with value: 0.43233933426519155.

Running time: 1.4 sec
OOF RMSE: 2.62 | R2: 0.43
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 17:57:42,435] Trial 12 finished with value: 0.4410383047147596 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0016136355640760255, 'learning_rate': 'constant', 'learning_rate_init': 0.0016046153765207495}. Best is trial 12 with value: 0.4410383047147596.

Fold 4
Fold 5
Running time: 1.2 sec
OOF RMSE: 2.59 | R2: 0.44
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

[I 2025-07-11 17:57:43,826] Trial 13 finished with value: 0.4182705321413971 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0014509891822258745, 'learning_rate': 'constant', 'learning_rate_init': 0.0010357555773338402}. Best is trial 12 with value: 0.4410383047147596.

Running time: 1.4 sec
OOF RMSE: 2.64 | R2: 0.42
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 17:57:45,234] Trial 14 finished with value: 0.44208590548762317 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.004912347384183444, 'learning_rate': 'constant', 'learning_rate_init': 0.0012868687694447295}. Best is trial 14 with value: 0.44208590548762317.

Fold 4
Fold 5
Running time: 1.4 sec
OOF RMSE: 2.59 | R2: 0.44
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 17:57:46,704] Trial 15 finished with value: 0.39390507782285833 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.00046966630102513406, 'learning_rate': 'constant', 'learning_rate_init': 0.0011126700916043737}. Best is trial 14 with value: 0.44208590548762317.

Running time: 1.5 sec
OOF RMSE: 2.70 | R2: 0.39
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

[I 2025-07-11 17:57:48,195] Trial 16 finished with value: 0.4103018986643657 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.007074795204956974, 'learning_rate': 'constant', 'learning_rate_init': 0.000671601929088008}. Best is trial 14 with value: 0.44208590548762317.

Running time: 1.5 sec
OOF RMSE: 2.66 | R2: 0.41
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 17:57:49,830] Trial 17 finished with value: 0.4321535769197089 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0006612940008337034, 'learning_rate': 'constant', 'learning_rate_init': 0.00037999539119730767}. Best is trial 14 with value: 0.44208590548762317.

Running time: 1.6 sec
OOF RMSE: 2.61 | R2: 0.43
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

[I 2025-07-11 17:57:51,279] Trial 18 finished with value: 0.4389167805686133 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.008730001195640817, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0014301369867103248}. Best is trial 14 with value: 0.44208590548762317.

Running time: 1.4 sec
OOF RMSE: 2.60 | R2: 0.44
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 17:57:51,958] Trial 19 finished with value: 0.3125206845656425 and parameters: {'hidden_layer_sizes': '50', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.001743761253473527, 'learning_rate': 'constant', 'learning_rate_init': 0.0031682202226392003}. Best is trial 14 with value: 0.44208590548762317.

Fold 4
Fold 5
Running time: 0.7 sec
OOF RMSE: 2.87 | R2: 0.31
Fold 1
Fold 2
Fold 3

[I 2025-07-11 17:57:52,935] Trial 20 finished with value: 0.42569089710187913 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.00025969424318721465, 'learning_rate': 'constant', 'learning_rate_init': 0.004567274839454736}. Best is trial 14 with value: 0.44208590548762317.

Fold 4
Fold 5
Running time: 1.0 sec
OOF RMSE: 2.63 | R2: 0.43
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 17:57:54,149] Trial 21 finished with value: 0.43884294427988335 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.00836556658928635, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0014275296673337025}. Best is trial 14 with value: 0.44208590548762317.

Fold 4
Fold 5
Running time: 1.2 sec
OOF RMSE: 2.60 | R2: 0.44
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 17:57:55,515] Trial 22 finished with value: 0.44149562258332653 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.003823378771040926, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0015759836591877953}. Best is trial 14 with value: 0.44208590548762317.

Fold 4
Fold 5
Running time: 1.4 sec
OOF RMSE: 2.59 | R2: 0.44
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

[I 2025-07-11 17:57:56,995] Trial 23 finished with value: 0.41440716780893294 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.003684185103927559, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0008222433581356259}. Best is trial 14 with value: 0.44208590548762317.

Running time: 1.5 sec
OOF RMSE: 2.65 | R2: 0.41
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 17:57:58,343] Trial 24 finished with value: 0.4387475960140752 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.020446080275119884, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0014255102169873448}. Best is trial 14 with value: 0.44208590548762317.
[I 2025-07-11 17:57:58,345] A new study created in memory with name: no-name-5c26ce0a-1f0c-4d3c-a8d7-ca977521be95
[I 2025-07-11 17:57:58,434] Trial 0 finished with value: -5.23449773176745 and parameters: {'kernel': 'sigmoid', 'C': 1.0957644140195473, 'epsilon': 0.19310604989627186, 'gamma': 'auto'}. Best is trial 0 with value: -5.23449773176745.

Fold 4
Fold 5
Running time: 1.3 sec
OOF RMSE: 2.60 | R2: 0.44

✅ MLP - Mejor R2: 0.44
📋 Parámetros: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.004912347384183444, 'learning_rate': 'constant', 'learning_rate_init': 0.0012868687694447295}

Buscando mejores hiperparámetros para SVR...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 8.66 | R2: -5.23
Fold 1

[I 2025-07-11 17:57:58,508] Trial 1 finished with value: -18.7867485462579 and parameters: {'kernel': 'sigmoid', 'C': 2.196234383362954, 'epsilon': 0.19365590372896296, 'gamma': 'auto'}. Best is trial 0 with value: -5.23449773176745.
[I 2025-07-11 17:57:58,579] Trial 2 finished with value: -2.0477320088535946 and parameters: {'kernel': 'sigmoid', 'C': 0.6709438080144625, 'epsilon': 0.13361713191311386, 'gamma': 'scale'}. Best is trial 2 with value: -2.0477320088535946.
[I 2025-07-11 17:57:58,644] Trial 3 finished with value: 0.2814391809681812 and parameters: {'kernel': 'rbf', 'C': 2.7618837060172594, 'epsilon': 0.10113758796847139, 'gamma': 'auto'}. Best is trial 3 with value: 0.2814391809681812.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 15.42 | R2: -18.79
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 6.05 | R2: -2.05
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.94 | R2: 0.28
Fold 1

[I 2025-07-11 17:57:58,715] Trial 4 finished with value: 0.04315652960593497 and parameters: {'kernel': 'rbf', 'C': 0.10085168775728152, 'epsilon': 0.08908925219536312, 'gamma': 'scale'}. Best is trial 3 with value: 0.2814391809681812.
[I 2025-07-11 17:57:58,787] Trial 5 finished with value: -25.200804412646214 and parameters: {'kernel': 'sigmoid', 'C': 2.521178972234761, 'epsilon': 0.13957704225512743, 'gamma': 'auto'}. Best is trial 3 with value: 0.2814391809681812.
[I 2025-07-11 17:57:58,853] Trial 6 finished with value: -1.900390860740457 and parameters: {'kernel': 'sigmoid', 'C': 0.622277447489051, 'epsilon': 0.1825490896279985, 'gamma': 'auto'}. Best is trial 3 with value: 0.2814391809681812.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.39 | R2: 0.04
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 17.74 | R2: -25.20
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 5.90 | R2: -1.90
Fold 1

[I 2025-07-11 17:57:58,927] Trial 7 finished with value: -336.8236633572077 and parameters: {'kernel': 'sigmoid', 'C': 9.600042692343164, 'epsilon': 0.11782832908656313, 'gamma': 'auto'}. Best is trial 3 with value: 0.2814391809681812.
[I 2025-07-11 17:57:59,012] Trial 8 finished with value: -5.559448513588158 and parameters: {'kernel': 'sigmoid', 'C': 1.1676613067491335, 'epsilon': 0.1388586126215652, 'gamma': 'scale'}. Best is trial 3 with value: 0.2814391809681812.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 63.72 | R2: -336.82
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 8.88 | R2: -5.56
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:57:59,079] Trial 9 finished with value: 0.10038383390919958 and parameters: {'kernel': 'rbf', 'C': 0.28970937073457254, 'epsilon': 0.13782340004672247, 'gamma': 'scale'}. Best is trial 3 with value: 0.2814391809681812.
[I 2025-07-11 17:57:59,163] Trial 10 finished with value: 0.35744461179779785 and parameters: {'kernel': 'rbf', 'C': 6.412256677786093, 'epsilon': 0.01656263173716549, 'gamma': 'auto'}. Best is trial 10 with value: 0.35744461179779785.
[I 2025-07-11 17:57:59,242] Trial 11 finished with value: 0.3954313640485626 and parameters: {'kernel': 'rbf', 'C': 8.734649131028176, 'epsilon': 0.015067985547545813, 'gamma': 'auto'}. Best is trial 11 with value: 0.3954313640485626.

Running time: 0.1 sec
OOF RMSE: 3.29 | R2: 0.10
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.78 | R2: 0.36
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.70 | R2: 0.40
Fold 1
Fold 2
Fold 3

[I 2025-07-11 17:57:59,323] Trial 12 finished with value: 0.39867390382905044 and parameters: {'kernel': 'rbf', 'C': 9.040243170264278, 'epsilon': 0.016488373566870648, 'gamma': 'auto'}. Best is trial 12 with value: 0.39867390382905044.
[I 2025-07-11 17:57:59,403] Trial 13 finished with value: 0.3208528484466904 and parameters: {'kernel': 'rbf', 'C': 5.019635469631912, 'epsilon': 0.015413864671025995, 'gamma': 'auto'}. Best is trial 12 with value: 0.39867390382905044.
[I 2025-07-11 17:57:59,477] Trial 14 finished with value: 0.31847288234217097 and parameters: {'kernel': 'rbf', 'C': 4.897171642417036, 'epsilon': 0.046622096313699964, 'gamma': 'auto'}. Best is trial 12 with value: 0.39867390382905044.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.69 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.86 | R2: 0.32
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.86 | R2: 0.32
Fold 1

[I 2025-07-11 17:57:59,559] Trial 15 finished with value: 0.40404377280610215 and parameters: {'kernel': 'rbf', 'C': 9.641702158623312, 'epsilon': 0.05120244645331237, 'gamma': 'auto'}. Best is trial 15 with value: 0.40404377280610215.
[I 2025-07-11 17:57:59,636] Trial 16 finished with value: 0.3041558938413387 and parameters: {'kernel': 'rbf', 'C': 4.236300889547976, 'epsilon': 0.06315954097821944, 'gamma': 'auto'}. Best is trial 15 with value: 0.40404377280610215.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.68 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.89 | R2: 0.30
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:57:59,708] Trial 17 finished with value: 0.2458552615448084 and parameters: {'kernel': 'rbf', 'C': 1.6905620971561692, 'epsilon': 0.051382360816326196, 'gamma': 'auto'}. Best is trial 15 with value: 0.40404377280610215.
[I 2025-07-11 17:57:59,789] Trial 18 finished with value: 0.4150093198780329 and parameters: {'kernel': 'rbf', 'C': 9.999876489435506, 'epsilon': 0.037814994820811736, 'gamma': 'scale'}. Best is trial 18 with value: 0.4150093198780329.
[I 2025-07-11 17:57:59,862] Trial 19 finished with value: 0.2971293763503564 and parameters: {'kernel': 'rbf', 'C': 3.442518297763435, 'epsilon': 0.07446456541385574, 'gamma': 'scale'}. Best is trial 18 with value: 0.4150093198780329.

Running time: 0.1 sec
OOF RMSE: 3.01 | R2: 0.25
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.65 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.91 | R2: 0.30
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 17:57:59,933] Trial 20 finished with value: 0.08957204239909367 and parameters: {'kernel': 'rbf', 'C': 0.2699194322584006, 'epsilon': 0.038999797710041945, 'gamma': 'scale'}. Best is trial 18 with value: 0.4150093198780329.
[I 2025-07-11 17:58:00,027] Trial 21 finished with value: 0.4128889493031326 and parameters: {'kernel': 'rbf', 'C': 9.77611511425337, 'epsilon': 0.03377196482785154, 'gamma': 'scale'}. Best is trial 18 with value: 0.4150093198780329.
[I 2025-07-11 17:58:00,102] Trial 22 finished with value: 0.364213901765159 and parameters: {'kernel': 'rbf', 'C': 6.643998550928389, 'epsilon': 0.07100362691604085, 'gamma': 'scale'}. Best is trial 18 with value: 0.4150093198780329.

Fold 5
Running time: 0.1 sec
OOF RMSE: 3.31 | R2: 0.09
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.66 | R2: 0.41
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.76 | R2: 0.36
Fold 1

[I 2025-07-11 17:58:00,183] Trial 23 finished with value: 0.3518219861671551 and parameters: {'kernel': 'rbf', 'C': 6.089722987151041, 'epsilon': 0.032245487263067536, 'gamma': 'scale'}. Best is trial 18 with value: 0.4150093198780329.
[I 2025-07-11 17:58:00,267] Trial 24 finished with value: 0.4141768548555952 and parameters: {'kernel': 'rbf', 'C': 9.891936803272563, 'epsilon': 0.0316020698870039, 'gamma': 'scale'}. Best is trial 18 with value: 0.4150093198780329.
[I 2025-07-11 17:58:00,268] A new study created in memory with name: no-name-f63d5e25-357f-475d-ab4f-d78025442880
[I 2025-07-11 17:58:00,326] Trial 0 finished with value: 0.45083685213815716 and parameters: {'n_neighbors': 11, 'weights': 'distance', 'leaf_size': 26}. Best is trial 0 with value: 0.45083685213815716.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.79 | R2: 0.35
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.65 | R2: 0.41

✅ SVR - Mejor R2: 0.42
📋 Parámetros: {'kernel': 'rbf', 'C': 9.999876489435506, 'epsilon': 0.037814994820811736, 'gamma': 'scale'}

Buscando mejores hiperparámetros para KNN...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.57 | R2: 0.45

[I 2025-07-11 17:58:00,386] Trial 1 finished with value: 0.45455343477768195 and parameters: {'n_neighbors': 15, 'weights': 'distance', 'leaf_size': 40}. Best is trial 1 with value: 0.45455343477768195.
[I 2025-07-11 17:58:00,447] Trial 2 finished with value: 0.45105807407993537 and parameters: {'n_neighbors': 5, 'weights': 'uniform', 'leaf_size': 27}. Best is trial 1 with value: 0.45455343477768195.
[I 2025-07-11 17:58:00,503] Trial 3 finished with value: 0.45935533826308406 and parameters: {'n_neighbors': 9, 'weights': 'distance', 'leaf_size': 18}. Best is trial 3 with value: 0.45935533826308406.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.56 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.57 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.55 | R2: 0.46
Fold 1
Fold 2
Fold 3

[I 2025-07-11 17:58:00,563] Trial 4 finished with value: 0.5058465768937079 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'leaf_size': 29}. Best is trial 4 with value: 0.5058465768937079.
[I 2025-07-11 17:58:00,627] Trial 5 finished with value: 0.42080446544340144 and parameters: {'n_neighbors': 8, 'weights': 'uniform', 'leaf_size': 24}. Best is trial 4 with value: 0.5058465768937079.
[I 2025-07-11 17:58:00,720] Trial 6 finished with value: 0.4229718957406364 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'leaf_size': 34}. Best is trial 4 with value: 0.5058465768937079.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.44 | R2: 0.51
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.64 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.63 | R2: 0.42
Fold 1
Fold 2

[I 2025-07-11 17:58:00,782] Trial 7 finished with value: 0.4517998889948215 and parameters: {'n_neighbors': 14, 'weights': 'distance', 'leaf_size': 11}. Best is trial 4 with value: 0.5058465768937079.
[I 2025-07-11 17:58:00,848] Trial 8 finished with value: 0.48072674190447395 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'leaf_size': 29}. Best is trial 4 with value: 0.5058465768937079.
[I 2025-07-11 17:58:00,905] Trial 9 finished with value: 0.43457320711486436 and parameters: {'n_neighbors': 7, 'weights': 'uniform', 'leaf_size': 12}. Best is trial 4 with value: 0.5058465768937079.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.57 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.50 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.61 | R2: 0.43
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 17:58:00,970] Trial 10 finished with value: 0.4644426141419692 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 35}. Best is trial 4 with value: 0.5058465768937079.
[I 2025-07-11 17:58:01,043] Trial 11 finished with value: 0.5036372346634452 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'leaf_size': 31}. Best is trial 4 with value: 0.5058465768937079.
[I 2025-07-11 17:58:01,109] Trial 12 finished with value: 0.494175248338375 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'leaf_size': 33}. Best is trial 4 with value: 0.5058465768937079.

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.54 | R2: 0.46
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.44 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.47 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 17:58:01,177] Trial 13 finished with value: 0.494175248338375 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'leaf_size': 20}. Best is trial 4 with value: 0.5058465768937079.
[I 2025-07-11 17:58:01,249] Trial 14 finished with value: 0.45083685213815716 and parameters: {'n_neighbors': 11, 'weights': 'distance', 'leaf_size': 31}. Best is trial 4 with value: 0.5058465768937079.
[I 2025-07-11 17:58:01,313] Trial 15 finished with value: 0.5036372346634452 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'leaf_size': 38}. Best is trial 4 with value: 0.5058465768937079.

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.47 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.57 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.44 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:58:01,379] Trial 16 finished with value: 0.4644426141419692 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 23}. Best is trial 4 with value: 0.5058465768937079.
[I 2025-07-11 17:58:01,461] Trial 17 finished with value: 0.44919541050254874 and parameters: {'n_neighbors': 10, 'weights': 'distance', 'leaf_size': 30}. Best is trial 4 with value: 0.5058465768937079.
[I 2025-07-11 17:58:01,544] Trial 18 finished with value: 0.4683167875891282 and parameters: {'n_neighbors': 4, 'weights': 'uniform', 'leaf_size': 17}. Best is trial 4 with value: 0.5058465768937079.

Running time: 0.1 sec
OOF RMSE: 2.54 | R2: 0.46
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.57 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.53 | R2: 0.47
Fold 1
Fold 2
Fold 3

[I 2025-07-11 17:58:01,610] Trial 19 finished with value: 0.48072674190447395 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'leaf_size': 37}. Best is trial 4 with value: 0.5058465768937079.
[I 2025-07-11 17:58:01,681] Trial 20 finished with value: 0.5036372346634452 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'leaf_size': 21}. Best is trial 4 with value: 0.5058465768937079.
[I 2025-07-11 17:58:01,746] Trial 21 finished with value: 0.5036372346634452 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'leaf_size': 39}. Best is trial 4 with value: 0.5058465768937079.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.50 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.44 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.44 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 17:58:01,812] Trial 22 finished with value: 0.5058465768937079 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'leaf_size': 36}. Best is trial 4 with value: 0.5058465768937079.
[I 2025-07-11 17:58:01,885] Trial 23 finished with value: 0.5058465768937079 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'leaf_size': 33}. Best is trial 4 with value: 0.5058465768937079.
[I 2025-07-11 17:58:01,947] Trial 24 finished with value: 0.5058465768937079 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'leaf_size': 36}. Best is trial 4 with value: 0.5058465768937079.
[I 2025-07-11 17:58:01,949] A new study created in memory with name: no-name-e38077c7-8d59-491e-a0d7-b80ddcb58c3a

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.44 | R2: 0.51
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.44 | R2: 0.51
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.44 | R2: 0.51

✅ KNN - Mejor R2: 0.51
📋 Parámetros: {'n_neighbors': 4, 'weights': 'distance', 'leaf_size': 29}

Buscando mejores hiperparámetros para LR...
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 17:58:02,026] Trial 0 finished with value: 0.25026773862731244 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 0 with value: 0.25026773862731244.
[I 2025-07-11 17:58:02,128] Trial 1 finished with value: 0.38269267121936235 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 1 with value: 0.38269267121936235.
[I 2025-07-11 17:58:02,210] Trial 2 finished with value: 0.2502677386263401 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 1 with value: 0.38269267121936235.

Fold 5
Running time: 0.1 sec
OOF RMSE: 3.00 | R2: 0.25
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.72 | R2: 0.38
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.00 | R2: 0.25

[I 2025-07-11 17:58:02,294] Trial 3 finished with value: 0.2502677386263401 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 1 with value: 0.38269267121936235.
[I 2025-07-11 17:58:02,386] Trial 4 finished with value: 0.2502677386263401 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 1 with value: 0.38269267121936235.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.00 | R2: 0.25
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.00 | R2: 0.25
Fold 1
Fold 2

[I 2025-07-11 17:58:02,468] Trial 5 finished with value: 0.3961773516018653 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 5 with value: 0.3961773516018653.
[I 2025-07-11 17:58:02,531] Trial 6 finished with value: 0.3961773516018653 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 5 with value: 0.3961773516018653.
[I 2025-07-11 17:58:02,601] Trial 7 finished with value: 0.25026773862731244 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 5 with value: 0.3961773516018653.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.69 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.69 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.00 | R2: 0.25
Fold 1
Fold 2

[I 2025-07-11 17:58:02,683] Trial 8 finished with value: 0.25026773862731244 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 5 with value: 0.3961773516018653.
[I 2025-07-11 17:58:02,777] Trial 9 finished with value: 0.25026773862731244 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 5 with value: 0.3961773516018653.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.00 | R2: 0.25
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.00 | R2: 0.25
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 17:58:02,859] Trial 10 finished with value: 0.3961773516018653 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 5 with value: 0.3961773516018653.
[I 2025-07-11 17:58:02,924] Trial 11 finished with value: 0.3961773516018653 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 5 with value: 0.3961773516018653.
[I 2025-07-11 17:58:03,000] Trial 12 finished with value: 0.3961773516018653 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 5 with value: 0.3961773516018653.

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.69 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.69 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.69 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:58:03,057] Trial 13 finished with value: 0.3961773516018653 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 5 with value: 0.3961773516018653.
[I 2025-07-11 17:58:03,122] Trial 14 finished with value: 0.3961773516018653 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 5 with value: 0.3961773516018653.
[I 2025-07-11 17:58:03,178] Trial 15 finished with value: 0.3961773516018653 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 5 with value: 0.3961773516018653.
[I 2025-07-11 17:58:03,235] Trial 16 finished with value: 0.3961773516018653 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 5 with value: 0.3961773516018653.

Running time: 0.1 sec
OOF RMSE: 2.69 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.69 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.69 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.69 | R2: 0.40
Fold 1
Fold 2

[I 2025-07-11 17:58:03,293] Trial 17 finished with value: 0.3961773516018653 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 5 with value: 0.3961773516018653.
[I 2025-07-11 17:58:03,353] Trial 18 finished with value: 0.3961773516018653 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 5 with value: 0.3961773516018653.
[I 2025-07-11 17:58:03,412] Trial 19 finished with value: 0.3961773516018653 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 5 with value: 0.3961773516018653.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.69 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.69 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.69 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:58:03,471] Trial 20 finished with value: 0.3961773516018653 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 5 with value: 0.3961773516018653.
[I 2025-07-11 17:58:03,531] Trial 21 finished with value: 0.3961773516018653 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 5 with value: 0.3961773516018653.
[I 2025-07-11 17:58:03,587] Trial 22 finished with value: 0.3961773516018653 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 5 with value: 0.3961773516018653.
[I 2025-07-11 17:58:03,642] Trial 23 finished with value: 0.3961773516018653 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 5 with value: 0.3961773516018653.

Running time: 0.1 sec
OOF RMSE: 2.69 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.69 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.69 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.69 | R2: 0.40
Fold 1
Fold 2
Fold 3

[I 2025-07-11 17:58:03,701] Trial 24 finished with value: 0.3961773516018653 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 5 with value: 0.3961773516018653.
[I 2025-07-11 17:58:03,702] A new study created in memory with name: no-name-f496fb7f-42f6-4eb1-9a99-032fad4568d1

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.69 | R2: 0.40

✅ LR - Mejor R2: 0.40
📋 Parámetros: {'fit_intercept': False, 'positive': True}

Buscando mejores hiperparámetros para RF...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:58:05,071] Trial 0 finished with value: 0.33960132324183434 and parameters: {'n_estimators': 100, 'max_depth': 7, 'min_samples_split': 3, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 0 with value: 0.33960132324183434.

Running time: 1.4 sec
OOF RMSE: 2.82 | R2: 0.34
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:58:15,741] Trial 1 finished with value: 0.05361510135868597 and parameters: {'n_estimators': 500, 'max_depth': 14, 'min_samples_split': 6, 'min_samples_leaf': 5, 'bootstrap': False}. Best is trial 0 with value: 0.33960132324183434.

Running time: 10.7 sec
OOF RMSE: 3.37 | R2: 0.05
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:58:23,253] Trial 2 finished with value: -0.032749658648968394 and parameters: {'n_estimators': 300, 'max_depth': 15, 'min_samples_split': 6, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 0 with value: 0.33960132324183434.

Running time: 7.5 sec
OOF RMSE: 3.52 | R2: -0.03
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:58:32,289] Trial 3 finished with value: 0.39480251878688866 and parameters: {'n_estimators': 500, 'max_depth': 13, 'min_samples_split': 8, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 3 with value: 0.39480251878688866.

Running time: 9.0 sec
OOF RMSE: 2.70 | R2: 0.39
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:58:34,493] Trial 4 finished with value: -0.056173657985033376 and parameters: {'n_estimators': 100, 'max_depth': 7, 'min_samples_split': 3, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 3 with value: 0.39480251878688866.

Running time: 2.2 sec
OOF RMSE: 3.56 | R2: -0.06
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:58:44,727] Trial 5 finished with value: 0.40570191808639067 and parameters: {'n_estimators': 500, 'max_depth': 14, 'min_samples_split': 3, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 5 with value: 0.40570191808639067.

Running time: 10.2 sec
OOF RMSE: 2.67 | R2: 0.41
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:58:46,522] Trial 6 finished with value: -0.00292294040781349 and parameters: {'n_estimators': 100, 'max_depth': 5, 'min_samples_split': 7, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 5 with value: 0.40570191808639067.

Running time: 1.8 sec
OOF RMSE: 3.47 | R2: -0.00
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:58:48,641] Trial 7 finished with value: -0.025135547194796937 and parameters: {'n_estimators': 100, 'max_depth': 7, 'min_samples_split': 2, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 5 with value: 0.40570191808639067.

Running time: 2.1 sec
OOF RMSE: 3.51 | R2: -0.03
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:59:01,015] Trial 8 finished with value: -0.029988067286396358 and parameters: {'n_estimators': 500, 'max_depth': 12, 'min_samples_split': 6, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 5 with value: 0.40570191808639067.

Running time: 12.4 sec
OOF RMSE: 3.52 | R2: -0.03
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:59:08,031] Trial 9 finished with value: 0.34059930015696505 and parameters: {'n_estimators': 500, 'max_depth': 8, 'min_samples_split': 8, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 5 with value: 0.40570191808639067.

Running time: 7.0 sec
OOF RMSE: 2.81 | R2: 0.34
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:59:13,350] Trial 10 finished with value: 0.3967525972892223 and parameters: {'n_estimators': 300, 'max_depth': 11, 'min_samples_split': 10, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 5 with value: 0.40570191808639067.

Running time: 5.3 sec
OOF RMSE: 2.69 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:59:18,597] Trial 11 finished with value: 0.3967525972892223 and parameters: {'n_estimators': 300, 'max_depth': 11, 'min_samples_split': 10, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 5 with value: 0.40570191808639067.

Running time: 5.2 sec
OOF RMSE: 2.69 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:59:23,613] Trial 12 finished with value: 0.3976104622368434 and parameters: {'n_estimators': 300, 'max_depth': 9, 'min_samples_split': 10, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 5 with value: 0.40570191808639067.

Running time: 5.0 sec
OOF RMSE: 2.69 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:59:28,693] Trial 13 finished with value: 0.3953826970492281 and parameters: {'n_estimators': 300, 'max_depth': 9, 'min_samples_split': 4, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 5 with value: 0.40570191808639067.

Running time: 5.1 sec
OOF RMSE: 2.70 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:59:37,427] Trial 14 finished with value: 0.38906128084815705 and parameters: {'n_estimators': 500, 'max_depth': 10, 'min_samples_split': 4, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 5 with value: 0.40570191808639067.

Running time: 8.7 sec
OOF RMSE: 2.71 | R2: 0.39
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:59:42,792] Trial 15 finished with value: 0.39658405405117303 and parameters: {'n_estimators': 300, 'max_depth': 15, 'min_samples_split': 9, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 5 with value: 0.40570191808639067.

Running time: 5.4 sec
OOF RMSE: 2.69 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:59:47,238] Trial 16 finished with value: 0.34471610997592805 and parameters: {'n_estimators': 300, 'max_depth': 13, 'min_samples_split': 5, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 5 with value: 0.40570191808639067.

Running time: 4.4 sec
OOF RMSE: 2.81 | R2: 0.34
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:59:53,630] Trial 17 finished with value: 0.38732044410106803 and parameters: {'n_estimators': 500, 'max_depth': 5, 'min_samples_split': 2, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 5 with value: 0.40570191808639067.

Running time: 6.4 sec
OOF RMSE: 2.71 | R2: 0.39
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 17:59:58,720] Trial 18 finished with value: 0.3985537687792847 and parameters: {'n_estimators': 300, 'max_depth': 9, 'min_samples_split': 8, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 5 with value: 0.40570191808639067.

Running time: 5.1 sec
OOF RMSE: 2.69 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:00:06,238] Trial 19 finished with value: 0.3459305955060744 and parameters: {'n_estimators': 500, 'max_depth': 11, 'min_samples_split': 8, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 5 with value: 0.40570191808639067.

Running time: 7.5 sec
OOF RMSE: 2.80 | R2: 0.35
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:00:11,390] Trial 20 finished with value: 0.3944261342911891 and parameters: {'n_estimators': 300, 'max_depth': 13, 'min_samples_split': 7, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 5 with value: 0.40570191808639067.

Running time: 5.1 sec
OOF RMSE: 2.70 | R2: 0.39
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:00:16,472] Trial 21 finished with value: 0.3985315653402093 and parameters: {'n_estimators': 300, 'max_depth': 10, 'min_samples_split': 9, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 5 with value: 0.40570191808639067.

Running time: 5.1 sec
OOF RMSE: 2.69 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:00:21,486] Trial 22 finished with value: 0.39706979917717156 and parameters: {'n_estimators': 300, 'max_depth': 9, 'min_samples_split': 9, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 5 with value: 0.40570191808639067.

Running time: 5.0 sec
OOF RMSE: 2.69 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:00:26,630] Trial 23 finished with value: 0.3985315653402093 and parameters: {'n_estimators': 300, 'max_depth': 10, 'min_samples_split': 9, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 5 with value: 0.40570191808639067.

Running time: 5.1 sec
OOF RMSE: 2.69 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:00:31,648] Trial 24 finished with value: 0.3913428116484484 and parameters: {'n_estimators': 300, 'max_depth': 10, 'min_samples_split': 7, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 5 with value: 0.40570191808639067.
[I 2025-07-11 18:00:31,649] A new study created in memory with name: no-name-f0f10231-ac8e-4a94-ae5a-eb041914f3d0

Running time: 5.0 sec
OOF RMSE: 2.70 | R2: 0.39

✅ RF - Mejor R2: 0.41
📋 Parámetros: {'n_estimators': 500, 'max_depth': 14, 'min_samples_split': 3, 'min_samples_leaf': 1, 'bootstrap': True}

Buscando mejores hiperparámetros para CAT...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:01:44,605] Trial 0 finished with value: 0.4750799203443693 and parameters: {'iterations': 2000, 'learning_rate': 0.05726875896273031, 'depth': 8, 'l2_leaf_reg': 3.8585805309268277}. Best is trial 0 with value: 0.4750799203443693.

Running time: 73.0 sec
OOF RMSE: 2.51 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:02:03,182] Trial 1 finished with value: 0.46981362648952696 and parameters: {'iterations': 500, 'learning_rate': 0.0350346863190602, 'depth': 8, 'l2_leaf_reg': 1.780100086149748}. Best is trial 0 with value: 0.4750799203443693.

Running time: 18.6 sec
OOF RMSE: 2.52 | R2: 0.47
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:02:10,489] Trial 2 finished with value: 0.49576723596030725 and parameters: {'iterations': 1000, 'learning_rate': 0.09743379926489598, 'depth': 6, 'l2_leaf_reg': 2.418641660338041}. Best is trial 2 with value: 0.49576723596030725.

Running time: 7.3 sec
OOF RMSE: 2.46 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:02:23,699] Trial 3 finished with value: 0.44966385233902084 and parameters: {'iterations': 2000, 'learning_rate': 0.02238573723927906, 'depth': 6, 'l2_leaf_reg': 9.821590451537432}. Best is trial 2 with value: 0.49576723596030725.

Running time: 13.2 sec
OOF RMSE: 2.57 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:05:12,225] Trial 4 finished with value: 0.4422704296095584 and parameters: {'iterations': 2000, 'learning_rate': 0.07655648810712748, 'depth': 9, 'l2_leaf_reg': 6.877182650111514}. Best is trial 2 with value: 0.49576723596030725.

Running time: 168.5 sec
OOF RMSE: 2.59 | R2: 0.44
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:05:20,905] Trial 5 finished with value: 0.4844281716653196 and parameters: {'iterations': 2000, 'learning_rate': 0.057971704934494, 'depth': 5, 'l2_leaf_reg': 2.149053764793136}. Best is trial 2 with value: 0.49576723596030725.

Running time: 8.7 sec
OOF RMSE: 2.49 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:07:45,630] Trial 6 finished with value: 0.4155675350385123 and parameters: {'iterations': 1000, 'learning_rate': 0.07349784298294486, 'depth': 10, 'l2_leaf_reg': 9.39378850098063}. Best is trial 2 with value: 0.49576723596030725.

Running time: 144.7 sec
OOF RMSE: 2.65 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:07:48,987] Trial 7 finished with value: 0.465843903710051 and parameters: {'iterations': 500, 'learning_rate': 0.011742941141720708, 'depth': 6, 'l2_leaf_reg': 7.207814803222055}. Best is trial 2 with value: 0.49576723596030725.

Running time: 3.4 sec
OOF RMSE: 2.53 | R2: 0.47
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:08:02,485] Trial 8 finished with value: 0.4900253206623034 and parameters: {'iterations': 1000, 'learning_rate': 0.016356353572226142, 'depth': 7, 'l2_leaf_reg': 2.4804507273215743}. Best is trial 2 with value: 0.49576723596030725.

Running time: 13.5 sec
OOF RMSE: 2.48 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:08:04,518] Trial 9 finished with value: 0.48439782503269146 and parameters: {'iterations': 500, 'learning_rate': 0.016208085364091164, 'depth': 5, 'l2_leaf_reg': 9.859454666293185}. Best is trial 2 with value: 0.49576723596030725.

Running time: 2.0 sec
OOF RMSE: 2.49 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:08:07,579] Trial 10 finished with value: 0.4925996074689549 and parameters: {'iterations': 1000, 'learning_rate': 0.03622901258214864, 'depth': 4, 'l2_leaf_reg': 4.559652062258676}. Best is trial 2 with value: 0.49576723596030725.

Running time: 3.1 sec
OOF RMSE: 2.47 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:08:10,960] Trial 11 finished with value: 0.4761541986644735 and parameters: {'iterations': 1000, 'learning_rate': 0.03244299027020878, 'depth': 4, 'l2_leaf_reg': 4.345364427805896}. Best is trial 2 with value: 0.49576723596030725.

Running time: 3.4 sec
OOF RMSE: 2.51 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:08:14,069] Trial 12 finished with value: 0.5009231647843806 and parameters: {'iterations': 1000, 'learning_rate': 0.04382877226566812, 'depth': 4, 'l2_leaf_reg': 3.9044856884811656}. Best is trial 12 with value: 0.5009231647843806.

Running time: 3.1 sec
OOF RMSE: 2.45 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:08:18,407] Trial 13 finished with value: 0.46902785405871705 and parameters: {'iterations': 1000, 'learning_rate': 0.09186491232060306, 'depth': 5, 'l2_leaf_reg': 3.361742657615515}. Best is trial 12 with value: 0.5009231647843806.

Running time: 4.3 sec
OOF RMSE: 2.53 | R2: 0.47
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:08:25,140] Trial 14 finished with value: 0.48019363151248984 and parameters: {'iterations': 1000, 'learning_rate': 0.04791727115001023, 'depth': 6, 'l2_leaf_reg': 5.75273425137288}. Best is trial 12 with value: 0.5009231647843806.

Running time: 6.7 sec
OOF RMSE: 2.50 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:08:28,153] Trial 15 finished with value: 0.48295368891708856 and parameters: {'iterations': 1000, 'learning_rate': 0.024588978966686107, 'depth': 4, 'l2_leaf_reg': 1.3802110241009036}. Best is trial 12 with value: 0.5009231647843806.

Running time: 3.0 sec
OOF RMSE: 2.49 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:08:41,956] Trial 16 finished with value: 0.4906212020163043 and parameters: {'iterations': 1000, 'learning_rate': 0.09410556306604613, 'depth': 7, 'l2_leaf_reg': 2.9930189634943973}. Best is trial 12 with value: 0.5009231647843806.

Running time: 13.8 sec
OOF RMSE: 2.47 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:08:45,952] Trial 17 finished with value: 0.43876135070843725 and parameters: {'iterations': 1000, 'learning_rate': 0.04785311383550247, 'depth': 5, 'l2_leaf_reg': 5.831174667425998}. Best is trial 12 with value: 0.5009231647843806.

Running time: 4.0 sec
OOF RMSE: 2.60 | R2: 0.44
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:09:00,028] Trial 18 finished with value: 0.48462508103978486 and parameters: {'iterations': 1000, 'learning_rate': 0.04708563239298304, 'depth': 7, 'l2_leaf_reg': 1.1319551113280193}. Best is trial 12 with value: 0.5009231647843806.

Running time: 14.1 sec
OOF RMSE: 2.49 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:09:01,703] Trial 19 finished with value: 0.5000352641206667 and parameters: {'iterations': 500, 'learning_rate': 0.025086882654644784, 'depth': 4, 'l2_leaf_reg': 4.886204762724905}. Best is trial 12 with value: 0.5009231647843806.

Running time: 1.7 sec
OOF RMSE: 2.45 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:09:03,165] Trial 20 finished with value: 0.5013888845964383 and parameters: {'iterations': 500, 'learning_rate': 0.02122490391796239, 'depth': 4, 'l2_leaf_reg': 4.8534022645050685}. Best is trial 20 with value: 0.5013888845964383.

Running time: 1.5 sec
OOF RMSE: 2.45 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:09:04,688] Trial 21 finished with value: 0.49485161514187315 and parameters: {'iterations': 500, 'learning_rate': 0.024521812576044417, 'depth': 4, 'l2_leaf_reg': 4.999381364662323}. Best is trial 20 with value: 0.5013888845964383.

Running time: 1.5 sec
OOF RMSE: 2.46 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:09:06,337] Trial 22 finished with value: 0.5015882606291253 and parameters: {'iterations': 500, 'learning_rate': 0.017987890187973567, 'depth': 4, 'l2_leaf_reg': 6.964986743821935}. Best is trial 22 with value: 0.5015882606291253.

Running time: 1.6 sec
OOF RMSE: 2.45 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:09:08,423] Trial 23 finished with value: 0.46816499916751686 and parameters: {'iterations': 500, 'learning_rate': 0.017806388901048898, 'depth': 5, 'l2_leaf_reg': 6.879570822740806}. Best is trial 22 with value: 0.5015882606291253.

Running time: 2.1 sec
OOF RMSE: 2.53 | R2: 0.47
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:09:10,137] Trial 24 finished with value: 0.47221669995051874 and parameters: {'iterations': 500, 'learning_rate': 0.011614115189751662, 'depth': 4, 'l2_leaf_reg': 8.22535657400462}. Best is trial 22 with value: 0.5015882606291253.
[I 2025-07-11 18:09:10,138] A new study created in memory with name: no-name-a3697473-1dc9-4882-894c-72a0fd26e64a
[I 2025-07-11 18:09:10,212] Trial 0 finished with value: 0.22964217947261023 and parameters: {'alpha': 4.10972522637664, 'l1_ratio': 0.41943430672876125}. Best is trial 0 with value: 0.22964217947261023.
[I 2025-07-11 18:09:10,300] Trial 1 finished with value: 0.4183049028143322 and parameters: {'alpha': 0.11002833272857705, 'l1_ratio': 0.2592333672920203}. Best is trial 1 with value: 0.4183049028143322.

Running time: 1.7 sec
OOF RMSE: 2.52 | R2: 0.47

✅ CAT - Mejor R2: 0.50
📋 Parámetros: {'iterations': 500, 'learning_rate': 0.017987890187973567, 'depth': 4, 'l2_leaf_reg': 6.964986743821935}

Buscando mejores hiperparámetros para EN...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.04 | R2: 0.23
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.64 | R2: 0.42
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.224e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.186e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.650e+01, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.433e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.715e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 18:09:10,417] Trial 2 finished with value: 0.39523613797666646 and parameters: {'alpha': 0.0016594506834647547, 'l1_ratio': 0.9581308110505613}. Best is trial 1 with value: 0.4183049028143322.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.218e+00, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 18:09:10,536] Trial 3 finished with value: 0.4212120479062471 and parameters: {'alpha': 0.05968422476504422, 'l1_ratio': 0.10974955467227976}. Best is trial 3 with value: 0.4212120479062471.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.70 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.64 | R2: 0.42
Fold 1

[I 2025-07-11 18:09:10,618] Trial 4 finished with value: 0.3753646948844971 and parameters: {'alpha': 1.3676432632184652, 'l1_ratio': 0.4749860488222082}. Best is trial 3 with value: 0.4212120479062471.
[I 2025-07-11 18:09:10,699] Trial 5 finished with value: 0.4054879978459276 and parameters: {'alpha': 0.44830328874887126, 'l1_ratio': 0.6710229085910813}. Best is trial 3 with value: 0.4212120479062471.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.947e+01, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.74 | R2: 0.38
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.67 | R2: 0.41
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.272e+01, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.892e+01, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.460e+01, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.940e+01, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 18:09:10,827] Trial 6 finished with value: 0.4225030499299628 and parameters: {'alpha': 0.014625074718472127, 'l1_ratio': 0.2963220530203752}. Best is trial 6 with value: 0.4225030499299628.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.319e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.685e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.979e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.005e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.390e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 18:09:10,951] Trial 7 finished with value: 0.38973715749947047 and parameters: {'alpha': 0.0003683828296007349, 'l1_ratio': 0.14146168918740865}. Best is trial 6 with value: 0.4225030499299628.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.63 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.71 | R2: 0.39
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.403e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.824e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.173e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.167e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.384e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 18:09:11,070] Trial 8 finished with value: 0.38342634832044575 and parameters: {'alpha': 0.00016426663315662838, 'l1_ratio': 0.001347920626371124}. Best is trial 6 with value: 0.4225030499299628.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.385e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.792e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.128e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.132e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.72 | R2: 0.38
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.392e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 18:09:11,204] Trial 9 finished with value: 0.385782554776141 and parameters: {'alpha': 0.00023207411156341804, 'l1_ratio': 0.06922662403849467}. Best is trial 6 with value: 0.4225030499299628.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.950e+00, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.604e+01, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.047e+01, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.953e+01, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.614e+01, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 18:09:11,340] Trial 10 finished with value: 0.40816214644878235 and parameters: {'alpha': 0.006391478078321336, 'l1_ratio': 0.711609946489665}. Best is trial 6 with value: 0.4225030499299628.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.216e+00, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.083e-01, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(

Running time: 0.1 sec
OOF RMSE: 2.72 | R2: 0.39
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.67 | R2: 0.41
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.409e+00, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.292e+01, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 18:09:11,466] Trial 11 finished with value: 0.4200682274429166 and parameters: {'alpha': 0.0232206816241363, 'l1_ratio': 0.3091335354505998}. Best is trial 6 with value: 0.4225030499299628.
[I 2025-07-11 18:09:11,581] Trial 12 finished with value: 0.4188431072133135 and parameters: {'alpha': 0.059013840759752814, 'l1_ratio': 0.21985768124123067}. Best is trial 6 with value: 0.4225030499299628.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.64 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.64 | R2: 0.42
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.437e+01, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.929e+01, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.446e+01, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.012e+01, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.814e+01, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 18:09:11,703] Trial 13 finished with value: 0.4209818230803394 and parameters: {'alpha': 0.008638421386649484, 'l1_ratio': 0.3912260509702228}. Best is trial 6 with value: 0.4225030499299628.
[I 2025-07-11 18:09:11,798] Trial 14 finished with value: 0.408056530877842 and parameters: {'alpha': 0.2107966773204246, 'l1_ratio': 0.5974738438579928}. Best is trial 6 with value: 0.4225030499299628.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.64 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.67 | R2: 0.41
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.802e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.610e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.010e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.089e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.411e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 18:09:11,930] Trial 15 finished with value: 0.41381345900700517 and parameters: {'alpha': 0.002432419529781272, 'l1_ratio': 0.184931120894309}. Best is trial 6 with value: 0.4225030499299628.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.104e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.984e+01, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.476e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.65 | R2: 0.41
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.567e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.271e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 18:09:12,074] Trial 16 finished with value: 0.42593835174859984 and parameters: {'alpha': 0.020651125092207196, 'l1_ratio': 0.10965931255409339}. Best is trial 16 with value: 0.42593835174859984.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.783e+01, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.547e+00, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.635e+00, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.526e+00, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.463e+01, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 18:09:12,233] Trial 17 finished with value: 0.42135979742853524 and parameters: {'alpha': 0.017699936345151164, 'l1_ratio': 0.32838938764885306}. Best is trial 16 with value: 0.42593835174859984.

Running time: 0.1 sec
OOF RMSE: 2.63 | R2: 0.43
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 2.64 | R2: 0.42
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.568e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.433e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.856e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.877e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.295e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 18:09:12,401] Trial 18 finished with value: 0.4030196263493617 and parameters: {'alpha': 0.0018641605387557762, 'l1_ratio': 0.56306118710418}. Best is trial 16 with value: 0.42593835174859984.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 2.68 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 18:09:12,516] Trial 19 finished with value: 0.4253622724762195 and parameters: {'alpha': 0.5961774242932104, 'l1_ratio': 0.007458121813094465}. Best is trial 16 with value: 0.42593835174859984.
[I 2025-07-11 18:09:12,649] Trial 20 finished with value: 0.3653887060321729 and parameters: {'alpha': 9.471846772430665, 'l1_ratio': 0.0032064430450388613}. Best is trial 16 with value: 0.42593835174859984.

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.63 | R2: 0.43
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.76 | R2: 0.37
Fold 1
Fold 2
Fold 3

[I 2025-07-11 18:09:12,764] Trial 21 finished with value: 0.42175780043330335 and parameters: {'alpha': 0.29696055968271756, 'l1_ratio': 0.11269362990864396}. Best is trial 16 with value: 0.42593835174859984.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.005e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.64 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.144e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.008e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.011e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.608e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 18:09:12,941] Trial 22 finished with value: 0.42303963921168 and parameters: {'alpha': 0.009092646404029561, 'l1_ratio': 0.21955487215131636}. Best is trial 16 with value: 0.42593835174859984.
[I 2025-07-11 18:09:13,045] Trial 23 finished with value: 0.4213700862532731 and parameters: {'alpha': 0.8534364927855146, 'l1_ratio': 0.043630888593685226}. Best is trial 16 with value: 0.42593835174859984.

Running time: 0.2 sec
OOF RMSE: 2.63 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.64 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.050e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.583e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.006e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.152e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.723e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 18:09:13,169] Trial 24 finished with value: 0.41863842576302057 and parameters: {'alpha': 0.0037371077408139552, 'l1_ratio': 0.17479519176854214}. Best is trial 16 with value: 0.42593835174859984.
[I 2025-07-11 18:09:13,171] A new study created in memory with name: no-name-1e963c7f-b7d3-43d9-aa28-5f6d0aa8a801

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.64 | R2: 0.42

✅ EN - Mejor R2: 0.43
📋 Parámetros: {'alpha': 0.020651125092207196, 'l1_ratio': 0.10965931255409339}

🔍 Optimizando en TOA_3x3_depth_lt_1...
Buscando mejores hiperparámetros para XGB...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:09:22,808] Trial 0 finished with value: 0.6298789555797859 and parameters: {'n_estimators': 2000, 'learning_rate': 0.040764965936880254, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.8337532149259632, 'colsample_bytree': 0.66027536566388}. Best is trial 0 with value: 0.6298789555797859.

Running time: 9.6 sec
OOF RMSE: 2.30 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:09:25,735] Trial 1 finished with value: 0.6628985948816115 and parameters: {'n_estimators': 500, 'learning_rate': 0.010440534550908199, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.9348648672927328, 'colsample_bytree': 0.7683801140067577}. Best is trial 1 with value: 0.6628985948816115.

Running time: 2.9 sec
OOF RMSE: 2.20 | R2: 0.66
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:09:29,981] Trial 2 finished with value: 0.6484640417810781 and parameters: {'n_estimators': 1000, 'learning_rate': 0.07383976846292258, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.8251873979317319, 'colsample_bytree': 0.9190164428539489}. Best is trial 1 with value: 0.6628985948816115.

Running time: 4.2 sec
OOF RMSE: 2.24 | R2: 0.65
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:09:37,609] Trial 3 finished with value: 0.6428047644958981 and parameters: {'n_estimators': 2000, 'learning_rate': 0.06753125212900356, 'max_depth': 8, 'min_child_weight': 2, 'subsample': 0.9005775436024309, 'colsample_bytree': 0.6962440747247588}. Best is trial 1 with value: 0.6628985948816115.

Running time: 7.6 sec
OOF RMSE: 2.26 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:09:40,677] Trial 4 finished with value: 0.6854549840127702 and parameters: {'n_estimators': 500, 'learning_rate': 0.008156230435441237, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.8001215529155075, 'colsample_bytree': 0.8857304548126212}. Best is trial 4 with value: 0.6854549840127702.

Running time: 3.1 sec
OOF RMSE: 2.12 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:09:43,644] Trial 5 finished with value: 0.6186333750286925 and parameters: {'n_estimators': 500, 'learning_rate': 0.035144039403802445, 'max_depth': 5, 'min_child_weight': 1, 'subsample': 0.8307077244263863, 'colsample_bytree': 0.870969667719134}. Best is trial 4 with value: 0.6854549840127702.

Running time: 3.0 sec
OOF RMSE: 2.34 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:09:54,426] Trial 6 finished with value: 0.6419558117396287 and parameters: {'n_estimators': 2000, 'learning_rate': 0.006304558599924568, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.9278047261644216, 'colsample_bytree': 0.7316103047989355}. Best is trial 4 with value: 0.6854549840127702.

Running time: 10.8 sec
OOF RMSE: 2.26 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:10:05,356] Trial 7 finished with value: 0.6763569061495907 and parameters: {'n_estimators': 2000, 'learning_rate': 0.0051913143415188824, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.9416625701810143, 'colsample_bytree': 0.7499466704533847}. Best is trial 4 with value: 0.6854549840127702.

Running time: 10.9 sec
OOF RMSE: 2.15 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:10:11,391] Trial 8 finished with value: 0.6826825804465562 and parameters: {'n_estimators': 1000, 'learning_rate': 0.03764039659710203, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.6880726531861103, 'colsample_bytree': 0.7739928662425671}. Best is trial 4 with value: 0.6854549840127702.

Running time: 6.0 sec
OOF RMSE: 2.13 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:10:26,306] Trial 9 finished with value: 0.6304180405219593 and parameters: {'n_estimators': 2000, 'learning_rate': 0.009174138788493534, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.6239885833003098, 'colsample_bytree': 0.6357005676448114}. Best is trial 4 with value: 0.6854549840127702.

Running time: 14.9 sec
OOF RMSE: 2.30 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:10:30,162] Trial 10 finished with value: 0.6439938109867069 and parameters: {'n_estimators': 500, 'learning_rate': 0.014564084687141588, 'max_depth': 8, 'min_child_weight': 3, 'subsample': 0.7303317393445422, 'colsample_bytree': 0.9897031013401022}. Best is trial 4 with value: 0.6854549840127702.

Running time: 3.8 sec
OOF RMSE: 2.26 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:10:36,710] Trial 11 finished with value: 0.6784859947055102 and parameters: {'n_estimators': 1000, 'learning_rate': 0.025482886495642423, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.7106820769107486, 'colsample_bytree': 0.8617685320580684}. Best is trial 4 with value: 0.6854549840127702.

Running time: 6.5 sec
OOF RMSE: 2.14 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:10:42,782] Trial 12 finished with value: 0.6754755164743724 and parameters: {'n_estimators': 1000, 'learning_rate': 0.018033414313568738, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.7307522377337348, 'colsample_bytree': 0.8250953924921216}. Best is trial 4 with value: 0.6854549840127702.

Running time: 6.1 sec
OOF RMSE: 2.15 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:10:49,948] Trial 13 finished with value: 0.6208694330844933 and parameters: {'n_estimators': 1000, 'learning_rate': 0.046819132682083826, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.6097433584409061, 'colsample_bytree': 0.9410368800541852}. Best is trial 4 with value: 0.6854549840127702.

Running time: 7.2 sec
OOF RMSE: 2.33 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:10:52,702] Trial 14 finished with value: 0.6835961220569109 and parameters: {'n_estimators': 500, 'learning_rate': 0.027922519047473886, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.681471042218269, 'colsample_bytree': 0.8120841270343607}. Best is trial 4 with value: 0.6854549840127702.

Running time: 2.7 sec
OOF RMSE: 2.13 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:10:56,109] Trial 15 finished with value: 0.6452953883441481 and parameters: {'n_estimators': 500, 'learning_rate': 0.024644201449108546, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.7724362052048527, 'colsample_bytree': 0.8279892157510388}. Best is trial 4 with value: 0.6854549840127702.

Running time: 3.4 sec
OOF RMSE: 2.25 | R2: 0.65
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:10:58,509] Trial 16 finished with value: 0.7011211337890131 and parameters: {'n_estimators': 500, 'learning_rate': 0.011065460930763691, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.6561434361923439, 'colsample_bytree': 0.8892521829814612}. Best is trial 16 with value: 0.7011211337890131.

Running time: 2.4 sec
OOF RMSE: 2.07 | R2: 0.70
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:11:00,989] Trial 17 finished with value: 0.6848895553992915 and parameters: {'n_estimators': 500, 'learning_rate': 0.009449263039333994, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.8723931364483525, 'colsample_bytree': 0.9086787943360184}. Best is trial 16 with value: 0.7011211337890131.

Running time: 2.5 sec
OOF RMSE: 2.12 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:11:03,456] Trial 18 finished with value: 0.6520462147092392 and parameters: {'n_estimators': 500, 'learning_rate': 0.013552949990306134, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.7718625613175627, 'colsample_bytree': 0.9883129875916266}. Best is trial 16 with value: 0.7011211337890131.

Running time: 2.5 sec
OOF RMSE: 2.23 | R2: 0.65
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:11:06,049] Trial 19 finished with value: 0.6823337443121883 and parameters: {'n_estimators': 500, 'learning_rate': 0.007406966418478121, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.9979105757755676, 'colsample_bytree': 0.8666496860601179}. Best is trial 16 with value: 0.7011211337890131.

Running time: 2.6 sec
OOF RMSE: 2.13 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:11:08,722] Trial 20 finished with value: 0.6621667191742915 and parameters: {'n_estimators': 500, 'learning_rate': 0.012919371124912676, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.6538252656711487, 'colsample_bytree': 0.9498184271539428}. Best is trial 16 with value: 0.7011211337890131.

Running time: 2.7 sec
OOF RMSE: 2.20 | R2: 0.66
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:11:11,584] Trial 21 finished with value: 0.6813056715190166 and parameters: {'n_estimators': 500, 'learning_rate': 0.008075930605136436, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.8916888041596589, 'colsample_bytree': 0.9017797743586272}. Best is trial 16 with value: 0.7011211337890131.

Running time: 2.9 sec
OOF RMSE: 2.13 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:11:14,139] Trial 22 finished with value: 0.687301634954975 and parameters: {'n_estimators': 500, 'learning_rate': 0.010410283404745828, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.866762870418856, 'colsample_bytree': 0.8991910415864159}. Best is trial 16 with value: 0.7011211337890131.

Running time: 2.5 sec
OOF RMSE: 2.11 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:11:16,929] Trial 23 finished with value: 0.681812864065547 and parameters: {'n_estimators': 500, 'learning_rate': 0.017803948280084053, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.7760487155441669, 'colsample_bytree': 0.8840076795130699}. Best is trial 16 with value: 0.7011211337890131.

Running time: 2.8 sec
OOF RMSE: 2.13 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:11:19,480] Trial 24 finished with value: 0.6759147719501546 and parameters: {'n_estimators': 500, 'learning_rate': 0.005014299749487007, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.8016924806972088, 'colsample_bytree': 0.9522802831541842}. Best is trial 16 with value: 0.7011211337890131.
[I 2025-07-11 18:11:19,481] A new study created in memory with name: no-name-461c9390-be51-4046-8a77-4aaeb09e8859

Running time: 2.5 sec
OOF RMSE: 2.15 | R2: 0.68

✅ XGB - Mejor R2: 0.70
📋 Parámetros: {'n_estimators': 500, 'learning_rate': 0.011065460930763691, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.6561434361923439, 'colsample_bytree': 0.8892521829814612}

Buscando mejores hiperparámetros para LBM...
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 18:11:19,741] Trial 0 finished with value: 0.6496333535627912 and parameters: {'learning_rate': 0.009916121684112099, 'num_leaves': 40, 'max_depth': 5, 'min_child_samples': 20, 'subsample': 0.9766214600656874, 'colsample_bytree': 0.8683075517216918, 'n_estimators': 500}. Best is trial 0 with value: 0.6496333535627912.

Fold 5
Running time: 0.3 sec
OOF RMSE: 2.24 | R2: 0.65
Fold 1
Fold 2
Fold 3

[I 2025-07-11 18:11:19,994] Trial 1 finished with value: 0.6695547146371995 and parameters: {'learning_rate': 0.017852836257579944, 'num_leaves': 40, 'max_depth': 6, 'min_child_samples': 23, 'subsample': 0.7716504089251448, 'colsample_bytree': 0.9434071467022684, 'n_estimators': 500}. Best is trial 1 with value: 0.6695547146371995.

Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 2.17 | R2: 0.67
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:11:20,464] Trial 2 finished with value: 0.6732498572875633 and parameters: {'learning_rate': 0.014607401209320815, 'num_leaves': 40, 'max_depth': 5, 'min_child_samples': 17, 'subsample': 0.9794984346516059, 'colsample_bytree': 0.8652522796374833, 'n_estimators': 1000}. Best is trial 2 with value: 0.6732498572875633.

Running time: 0.5 sec
OOF RMSE: 2.16 | R2: 0.67
Fold 1
Fold 2
Fold 3

[I 2025-07-11 18:11:20,894] Trial 3 finished with value: 0.7339651892367008 and parameters: {'learning_rate': 0.0711837204821817, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 16, 'subsample': 0.7600945796486985, 'colsample_bytree': 0.6547452492443382, 'n_estimators': 1000}. Best is trial 3 with value: 0.7339651892367008.

Fold 4
Fold 5
Running time: 0.4 sec
OOF RMSE: 1.95 | R2: 0.73
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:11:21,874] Trial 4 finished with value: 0.6762113668169287 and parameters: {'learning_rate': 0.005872965777643582, 'num_leaves': 40, 'max_depth': 5, 'min_child_samples': 6, 'subsample': 0.8404957746271038, 'colsample_bytree': 0.9279625238679949, 'n_estimators': 2000}. Best is trial 3 with value: 0.7339651892367008.

Running time: 1.0 sec
OOF RMSE: 2.15 | R2: 0.68
Fold 1
Fold 2
Fold 3

[I 2025-07-11 18:11:22,205] Trial 5 finished with value: 0.6708582553033693 and parameters: {'learning_rate': 0.022003865151688028, 'num_leaves': 40, 'max_depth': 8, 'min_child_samples': 17, 'subsample': 0.9898837057280567, 'colsample_bytree': 0.880088069347434, 'n_estimators': 500}. Best is trial 3 with value: 0.7339651892367008.

Fold 4
Fold 5
Running time: 0.3 sec
OOF RMSE: 2.17 | R2: 0.67
Fold 1
Fold 2

[I 2025-07-11 18:11:22,434] Trial 6 finished with value: 0.6122427063308422 and parameters: {'learning_rate': 0.009244438739419717, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 23, 'subsample': 0.8826463986302846, 'colsample_bytree': 0.7856728392624958, 'n_estimators': 500}. Best is trial 3 with value: 0.7339651892367008.

Fold 3
Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 2.35 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:11:23,713] Trial 7 finished with value: 0.6993627640823745 and parameters: {'learning_rate': 0.014359841106541761, 'num_leaves': 60, 'max_depth': 7, 'min_child_samples': 10, 'subsample': 0.9581316357894103, 'colsample_bytree': 0.9026767352631437, 'n_estimators': 2000}. Best is trial 3 with value: 0.7339651892367008.

Running time: 1.3 sec
OOF RMSE: 2.07 | R2: 0.70
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 18:11:24,433] Trial 8 finished with value: 0.6840517895441058 and parameters: {'learning_rate': 0.04359080001366885, 'num_leaves': 60, 'max_depth': 8, 'min_child_samples': 7, 'subsample': 0.8690722290950941, 'colsample_bytree': 0.6187107018199534, 'n_estimators': 1000}. Best is trial 3 with value: 0.7339651892367008.

Fold 5
Running time: 0.7 sec
OOF RMSE: 2.13 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:11:25,017] Trial 9 finished with value: 0.6841109335922579 and parameters: {'learning_rate': 0.03298332690164661, 'num_leaves': 80, 'max_depth': 6, 'min_child_samples': 7, 'subsample': 0.8994391381162399, 'colsample_bytree': 0.6192645461380968, 'n_estimators': 1000}. Best is trial 3 with value: 0.7339651892367008.

Running time: 0.6 sec
OOF RMSE: 2.13 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 18:11:25,639] Trial 10 finished with value: 0.7137241322004488 and parameters: {'learning_rate': 0.09719662548909766, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 13, 'subsample': 0.6384424625826814, 'colsample_bytree': 0.7241081132629037, 'n_estimators': 1000}. Best is trial 3 with value: 0.7339651892367008.

Fold 5
Running time: 0.6 sec
OOF RMSE: 2.02 | R2: 0.71
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:11:26,257] Trial 11 finished with value: 0.716819964688777 and parameters: {'learning_rate': 0.09176959151903666, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 13, 'subsample': 0.652614187503157, 'colsample_bytree': 0.7166034197369218, 'n_estimators': 1000}. Best is trial 3 with value: 0.7339651892367008.

Running time: 0.6 sec
OOF RMSE: 2.01 | R2: 0.72
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 18:11:26,871] Trial 12 finished with value: 0.7146682476682671 and parameters: {'learning_rate': 0.07852243796928468, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 12, 'subsample': 0.6980809423866088, 'colsample_bytree': 0.6970229290379978, 'n_estimators': 1000}. Best is trial 3 with value: 0.7339651892367008.

Fold 5
Running time: 0.6 sec
OOF RMSE: 2.02 | R2: 0.71
Fold 1
Fold 2
Fold 3

[I 2025-07-11 18:11:27,411] Trial 13 finished with value: 0.7361908657771258 and parameters: {'learning_rate': 0.058649190864794594, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 16, 'subsample': 0.7438143258380389, 'colsample_bytree': 0.6836802059586142, 'n_estimators': 1000}. Best is trial 13 with value: 0.7361908657771258.

Fold 4
Fold 5
Running time: 0.5 sec
OOF RMSE: 1.94 | R2: 0.74
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:11:27,913] Trial 14 finished with value: 0.7021765409417406 and parameters: {'learning_rate': 0.051016159330891965, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 17, 'subsample': 0.7576806876833708, 'colsample_bytree': 0.6673401069991676, 'n_estimators': 1000}. Best is trial 13 with value: 0.7361908657771258.

Running time: 0.5 sec
OOF RMSE: 2.06 | R2: 0.70
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:11:28,388] Trial 15 finished with value: 0.7145017733776826 and parameters: {'learning_rate': 0.06209175380754634, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 20, 'subsample': 0.7159345362959636, 'colsample_bytree': 0.7805241517070064, 'n_estimators': 1000}. Best is trial 13 with value: 0.7361908657771258.

Running time: 0.5 sec
OOF RMSE: 2.02 | R2: 0.71
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 18:11:29,226] Trial 16 finished with value: 0.7158301265543372 and parameters: {'learning_rate': 0.032140892968193696, 'num_leaves': 80, 'max_depth': 5, 'min_child_samples': 20, 'subsample': 0.804111783838075, 'colsample_bytree': 0.6606957049748828, 'n_estimators': 2000}. Best is trial 13 with value: 0.7361908657771258.

Fold 5
Running time: 0.8 sec
OOF RMSE: 2.02 | R2: 0.72
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 18:11:29,761] Trial 17 finished with value: 0.688179696380778 and parameters: {'learning_rate': 0.0361385862356808, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 15, 'subsample': 0.7168595223310944, 'colsample_bytree': 0.732955268447128, 'n_estimators': 1000}. Best is trial 13 with value: 0.7361908657771258.

Fold 5
Running time: 0.5 sec
OOF RMSE: 2.11 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 18:11:30,262] Trial 18 finished with value: 0.6935176441419105 and parameters: {'learning_rate': 0.07182824899203838, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 10, 'subsample': 0.6086420260731258, 'colsample_bytree': 0.818345780721195, 'n_estimators': 1000}. Best is trial 13 with value: 0.7361908657771258.

Fold 5
Running time: 0.5 sec
OOF RMSE: 2.09 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:11:31,262] Trial 19 finished with value: 0.6954767741944003 and parameters: {'learning_rate': 0.055542069025368436, 'num_leaves': 80, 'max_depth': 6, 'min_child_samples': 15, 'subsample': 0.8096212744856914, 'colsample_bytree': 0.6651326648310382, 'n_estimators': 2000}. Best is trial 13 with value: 0.7361908657771258.

Running time: 1.0 sec
OOF RMSE: 2.09 | R2: 0.70
Fold 1
Fold 2
Fold 3

[I 2025-07-11 18:11:31,674] Trial 20 finished with value: 0.6985224911173129 and parameters: {'learning_rate': 0.027262252871691418, 'num_leaves': 60, 'max_depth': 5, 'min_child_samples': 25, 'subsample': 0.7561066493528528, 'colsample_bytree': 0.6203618538118834, 'n_estimators': 1000}. Best is trial 13 with value: 0.7361908657771258.

Fold 4
Fold 5
Running time: 0.4 sec
OOF RMSE: 2.08 | R2: 0.70
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:11:32,289] Trial 21 finished with value: 0.7148294431518685 and parameters: {'learning_rate': 0.09478324258704282, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 13, 'subsample': 0.6502273883968903, 'colsample_bytree': 0.7313115202111038, 'n_estimators': 1000}. Best is trial 13 with value: 0.7361908657771258.

Running time: 0.6 sec
OOF RMSE: 2.02 | R2: 0.71
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 18:11:32,930] Trial 22 finished with value: 0.673253328000164 and parameters: {'learning_rate': 0.07414640844686782, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 11, 'subsample': 0.6744982637211954, 'colsample_bytree': 0.6930563643379662, 'n_estimators': 1000}. Best is trial 13 with value: 0.7361908657771258.

Fold 5
Running time: 0.6 sec
OOF RMSE: 2.16 | R2: 0.67
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:11:33,491] Trial 23 finished with value: 0.7040979614244802 and parameters: {'learning_rate': 0.044834754603693384, 'num_leaves': 20, 'max_depth': 8, 'min_child_samples': 18, 'subsample': 0.7301380558153264, 'colsample_bytree': 0.7620045292778831, 'n_estimators': 1000}. Best is trial 13 with value: 0.7361908657771258.

Running time: 0.6 sec
OOF RMSE: 2.06 | R2: 0.70
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 18:11:34,097] Trial 24 finished with value: 0.6742266009900719 and parameters: {'learning_rate': 0.09735875098837755, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 14, 'subsample': 0.6767825904914064, 'colsample_bytree': 0.6936014420813986, 'n_estimators': 1000}. Best is trial 13 with value: 0.7361908657771258.
[I 2025-07-11 18:11:34,098] A new study created in memory with name: no-name-8bf75430-0ccd-4261-acf2-c090791e72ab

Fold 5
Running time: 0.6 sec
OOF RMSE: 2.16 | R2: 0.67

✅ LBM - Mejor R2: 0.74
📋 Parámetros: {'learning_rate': 0.058649190864794594, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 16, 'subsample': 0.7438143258380389, 'colsample_bytree': 0.6836802059586142, 'n_estimators': 1000}

Buscando mejores hiperparámetros para MLP...
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 18:11:36,045] Trial 0 finished with value: 0.5321225779967327 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.0002729642589110575, 'learning_rate': 'constant', 'learning_rate_init': 0.0009355998260799562}. Best is trial 0 with value: 0.5321225779967327.

Running time: 1.9 sec
OOF RMSE: 2.59 | R2: 0.53
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 18:11:37,536] Trial 1 finished with value: 0.17580070018319793 and parameters: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'adam', 'alpha': 1.3971002297415424e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.0001274342859928617}. Best is trial 0 with value: 0.5321225779967327.

Running time: 1.5 sec
OOF RMSE: 3.43 | R2: 0.18
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 18:11:38,707] Trial 2 finished with value: 0.42323128791921927 and parameters: {'hidden_layer_sizes': '50', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.0018152576318630747, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0020472746303941964}. Best is trial 0 with value: 0.5321225779967327.

Running time: 1.2 sec
OOF RMSE: 2.87 | R2: 0.42
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:11:40,309] Trial 3 finished with value: 0.6336535009796354 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 2.6935967527067133e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.000702428540481157}. Best is trial 3 with value: 0.6336535009796354.

Running time: 1.6 sec
OOF RMSE: 2.29 | R2: 0.63
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 18:11:41,486] Trial 4 finished with value: 0.42836103325624675 and parameters: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.013396984848150575, 'learning_rate': 'constant', 'learning_rate_init': 0.002369335444521451}. Best is trial 3 with value: 0.6336535009796354.

Fold 5
Running time: 1.2 sec
OOF RMSE: 2.86 | R2: 0.43
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 18:11:43,394] Trial 5 finished with value: 0.1778616042418788 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0022259578774688213, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0001515706576798249}. Best is trial 3 with value: 0.6336535009796354.

Running time: 1.9 sec
OOF RMSE: 3.43 | R2: 0.18
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 18:11:44,575] Trial 6 finished with value: 0.3880343880958915 and parameters: {'hidden_layer_sizes': '50', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.0003390513006335006, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0005355818673794052}. Best is trial 3 with value: 0.6336535009796354.

Running time: 1.2 sec
OOF RMSE: 2.96 | R2: 0.39
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 18:11:45,300] Trial 7 finished with value: 0.5397086960718422 and parameters: {'hidden_layer_sizes': '50', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0502488028536491, 'learning_rate': 'adaptive', 'learning_rate_init': 0.004321277776941432}. Best is trial 3 with value: 0.6336535009796354.

Fold 5
Running time: 0.7 sec
OOF RMSE: 2.57 | R2: 0.54
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 18:11:46,033] Trial 8 finished with value: 0.6537048836229181 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 3.2952508241871195e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.004940160737060411}. Best is trial 8 with value: 0.6537048836229181.

Fold 5
Running time: 0.7 sec
OOF RMSE: 2.23 | R2: 0.65
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 18:11:48,599] Trial 9 finished with value: 0.56098874960671 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 1.1409113738581238e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.001065594227668045}. Best is trial 8 with value: 0.6537048836229181.

Running time: 2.6 sec
OOF RMSE: 2.51 | R2: 0.56
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:11:50,231] Trial 10 finished with value: 0.6100536508492979 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.00010194617990543117, 'learning_rate': 'constant', 'learning_rate_init': 0.0074082715582591665}. Best is trial 8 with value: 0.6537048836229181.

Running time: 1.6 sec
OOF RMSE: 2.36 | R2: 0.61
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 18:11:52,511] Trial 11 finished with value: 0.6133879371856599 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 5.5184573521184014e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.00027159842103323287}. Best is trial 8 with value: 0.6537048836229181.

Running time: 2.3 sec
OOF RMSE: 2.35 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 18:11:53,197] Trial 12 finished with value: 0.6909083039775499 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 4.455392323283756e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.009384872367481102}. Best is trial 12 with value: 0.6909083039775499.

Fold 5
Running time: 0.7 sec
OOF RMSE: 2.10 | R2: 0.69
Fold 1
Fold 2
Fold 3

[I 2025-07-11 18:11:54,027] Trial 13 finished with value: 0.7009025414574671 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0001233223774681869, 'learning_rate': 'constant', 'learning_rate_init': 0.009779044228126421}. Best is trial 13 with value: 0.7009025414574671.

Fold 4
Fold 5
Running time: 0.8 sec
OOF RMSE: 2.07 | R2: 0.70
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:11:54,771] Trial 14 finished with value: 0.6187126467042756 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0001622381986242867, 'learning_rate': 'constant', 'learning_rate_init': 0.009503721675406635}. Best is trial 13 with value: 0.7009025414574671.

Running time: 0.7 sec
OOF RMSE: 2.33 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:11:55,556] Trial 15 finished with value: 0.6161116926115385 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0008475392666617112, 'learning_rate': 'constant', 'learning_rate_init': 0.0029640293922476788}. Best is trial 13 with value: 0.7009025414574671.

Running time: 0.8 sec
OOF RMSE: 2.34 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:11:56,202] Trial 16 finished with value: 0.6960299938672775 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.000566783651095302, 'learning_rate': 'constant', 'learning_rate_init': 0.009668891804590447}. Best is trial 13 with value: 0.7009025414574671.

Running time: 0.6 sec
OOF RMSE: 2.08 | R2: 0.70
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:11:56,947] Trial 17 finished with value: 0.6652096760379385 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.000800135887157611, 'learning_rate': 'constant', 'learning_rate_init': 0.004481991279022707}. Best is trial 13 with value: 0.7009025414574671.

Running time: 0.7 sec
OOF RMSE: 2.19 | R2: 0.67
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:11:58,349] Trial 18 finished with value: 0.6109264945441908 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.005479936775581145, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0016214976976511824}. Best is trial 13 with value: 0.7009025414574671.

Running time: 1.4 sec
OOF RMSE: 2.36 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:11:59,162] Trial 19 finished with value: 0.6522917668610326 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0003767306403746447, 'learning_rate': 'constant', 'learning_rate_init': 0.0057092461955190535}. Best is trial 13 with value: 0.7009025414574671.

Running time: 0.8 sec
OOF RMSE: 2.23 | R2: 0.65
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:11:59,981] Trial 20 finished with value: 0.6204230763300336 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.008820051131572606, 'learning_rate': 'constant', 'learning_rate_init': 0.0034123390641667087}. Best is trial 13 with value: 0.7009025414574671.

Running time: 0.8 sec
OOF RMSE: 2.33 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:12:00,630] Trial 21 finished with value: 0.687705671891461 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.00010317337400183734, 'learning_rate': 'constant', 'learning_rate_init': 0.009250485146707321}. Best is trial 13 with value: 0.7009025414574671.

Running time: 0.6 sec
OOF RMSE: 2.11 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:12:01,253] Trial 22 finished with value: 0.6383204005243871 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 5.826349004981642e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.0074702398395800765}. Best is trial 13 with value: 0.7009025414574671.

Running time: 0.6 sec
OOF RMSE: 2.27 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:12:01,909] Trial 23 finished with value: 0.7014604430369968 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0005884657568808193, 'learning_rate': 'constant', 'learning_rate_init': 0.00977131119065175}. Best is trial 23 with value: 0.7014604430369968.

Running time: 0.7 sec
OOF RMSE: 2.07 | R2: 0.70
Fold 1
Fold 2
Fold 3

[I 2025-07-11 18:12:02,611] Trial 24 finished with value: 0.6604167296783879 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0022910412669831346, 'learning_rate': 'constant', 'learning_rate_init': 0.005928182278558872}. Best is trial 23 with value: 0.7014604430369968.
[I 2025-07-11 18:12:02,613] A new study created in memory with name: no-name-6b0209a5-256b-482e-9637-c7672fd0da5f

Fold 4
Fold 5
Running time: 0.7 sec
OOF RMSE: 2.20 | R2: 0.66

✅ MLP - Mejor R2: 0.70
📋 Parámetros: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0005884657568808193, 'learning_rate': 'constant', 'learning_rate_init': 0.00977131119065175}

Buscando mejores hiperparámetros para SVR...

[I 2025-07-11 18:12:02,714] Trial 0 finished with value: -1.6632279146316717 and parameters: {'kernel': 'sigmoid', 'C': 2.962964627244189, 'epsilon': 0.1628464586099716, 'gamma': 'auto'}. Best is trial 0 with value: -1.6632279146316717.
[I 2025-07-11 18:12:02,820] Trial 1 finished with value: 0.2896835891975209 and parameters: {'kernel': 'rbf', 'C': 4.376694047677955, 'epsilon': 0.011967662876146373, 'gamma': 'auto'}. Best is trial 1 with value: 0.2896835891975209.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 6.17 | R2: -1.66
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.19 | R2: 0.29

[I 2025-07-11 18:12:02,904] Trial 2 finished with value: -0.6516831486394243 and parameters: {'kernel': 'sigmoid', 'C': 0.738236139524013, 'epsilon': 0.06647522648473032, 'gamma': 'scale'}. Best is trial 1 with value: 0.2896835891975209.
[I 2025-07-11 18:12:02,983] Trial 3 finished with value: -1.437661473529002 and parameters: {'kernel': 'sigmoid', 'C': 2.774909756379545, 'epsilon': 0.09076391559528421, 'gamma': 'auto'}. Best is trial 1 with value: 0.2896835891975209.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 4.86 | R2: -0.65
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 5.90 | R2: -1.44
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 18:12:03,051] Trial 4 finished with value: -0.07109237737078256 and parameters: {'kernel': 'rbf', 'C': 0.10134461856232892, 'epsilon': 0.19727015213638338, 'gamma': 'auto'}. Best is trial 1 with value: 0.2896835891975209.
[I 2025-07-11 18:12:03,132] Trial 5 finished with value: -0.0746214238912477 and parameters: {'kernel': 'sigmoid', 'C': 0.15553986533031047, 'epsilon': 0.09205580933354728, 'gamma': 'auto'}. Best is trial 1 with value: 0.2896835891975209.
[I 2025-07-11 18:12:03,204] Trial 6 finished with value: 0.22187880386563852 and parameters: {'kernel': 'rbf', 'C': 1.8517753098525644, 'epsilon': 0.055309089069539234, 'gamma': 'scale'}. Best is trial 1 with value: 0.2896835891975209.

Fold 5
Running time: 0.1 sec
OOF RMSE: 3.91 | R2: -0.07
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.92 | R2: -0.07
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.34 | R2: 0.22
Fold 1
Fold 2
Fold 3

[I 2025-07-11 18:12:03,281] Trial 7 finished with value: -1.4058649321850463 and parameters: {'kernel': 'sigmoid', 'C': 2.747770879879397, 'epsilon': 0.02740165195685887, 'gamma': 'auto'}. Best is trial 1 with value: 0.2896835891975209.
[I 2025-07-11 18:12:03,358] Trial 8 finished with value: -0.05395012579748615 and parameters: {'kernel': 'sigmoid', 'C': 0.2556067342098344, 'epsilon': 0.055108518931049656, 'gamma': 'auto'}. Best is trial 1 with value: 0.2896835891975209.
[I 2025-07-11 18:12:03,427] Trial 9 finished with value: -0.059000904540237986 and parameters: {'kernel': 'sigmoid', 'C': 0.22394496943510883, 'epsilon': 0.1552259892435989, 'gamma': 'auto'}. Best is trial 1 with value: 0.2896835891975209.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 5.87 | R2: -1.41
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.88 | R2: -0.05
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.89 | R2: -0.06
Fold 1

[I 2025-07-11 18:12:03,515] Trial 10 finished with value: 0.5222781671451275 and parameters: {'kernel': 'rbf', 'C': 9.99146026649796, 'epsilon': 0.016757551201296503, 'gamma': 'scale'}. Best is trial 10 with value: 0.5222781671451275.
[I 2025-07-11 18:12:03,601] Trial 11 finished with value: 0.5222308572197069 and parameters: {'kernel': 'rbf', 'C': 9.978846064794206, 'epsilon': 0.012049826021785379, 'gamma': 'scale'}. Best is trial 10 with value: 0.5222781671451275.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.61 | R2: 0.52
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.61 | R2: 0.52
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 18:12:03,683] Trial 12 finished with value: 0.513077137626772 and parameters: {'kernel': 'rbf', 'C': 9.175175092969658, 'epsilon': 0.011526416914398735, 'gamma': 'scale'}. Best is trial 10 with value: 0.5222781671451275.
[I 2025-07-11 18:12:03,776] Trial 13 finished with value: 0.5098359129567609 and parameters: {'kernel': 'rbf', 'C': 8.784386404865783, 'epsilon': 0.03976699103470237, 'gamma': 'scale'}. Best is trial 10 with value: 0.5222781671451275.
[I 2025-07-11 18:12:03,851] Trial 14 finished with value: 0.09911924237860159 and parameters: {'kernel': 'rbf', 'C': 0.7541726209705981, 'epsilon': 0.12773360685930626, 'gamma': 'scale'}. Best is trial 10 with value: 0.5222781671451275.

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.64 | R2: 0.51
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.65 | R2: 0.51
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.59 | R2: 0.10
Fold 1

[I 2025-07-11 18:12:03,942] Trial 15 finished with value: 0.44639989264053304 and parameters: {'kernel': 'rbf', 'C': 5.703827465845936, 'epsilon': 0.0730729905481329, 'gamma': 'scale'}. Best is trial 10 with value: 0.5222781671451275.
[I 2025-07-11 18:12:04,022] Trial 16 finished with value: 0.18616230603055683 and parameters: {'kernel': 'rbf', 'C': 1.464885918524356, 'epsilon': 0.03491009221604677, 'gamma': 'scale'}. Best is trial 10 with value: 0.5222781671451275.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.81 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.41 | R2: 0.19
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 18:12:04,100] Trial 17 finished with value: 0.4444970860791938 and parameters: {'kernel': 'rbf', 'C': 5.452629664751844, 'epsilon': 0.11776757289257622, 'gamma': 'scale'}. Best is trial 10 with value: 0.5222781671451275.
[I 2025-07-11 18:12:04,182] Trial 18 finished with value: 0.051851513678635386 and parameters: {'kernel': 'rbf', 'C': 0.5245463088180982, 'epsilon': 0.030225683096843547, 'gamma': 'scale'}. Best is trial 10 with value: 0.5222781671451275.
[I 2025-07-11 18:12:04,263] Trial 19 finished with value: 0.5106769495419272 and parameters: {'kernel': 'rbf', 'C': 9.001823389844972, 'epsilon': 0.011606901439604578, 'gamma': 'scale'}. Best is trial 10 with value: 0.5222781671451275.

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.82 | R2: 0.44
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.68 | R2: 0.05
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.65 | R2: 0.51
Fold 1

[I 2025-07-11 18:12:04,346] Trial 20 finished with value: 0.4005419692911999 and parameters: {'kernel': 'rbf', 'C': 4.617327794414867, 'epsilon': 0.05097656365185139, 'gamma': 'scale'}. Best is trial 10 with value: 0.5222781671451275.
[I 2025-07-11 18:12:04,432] Trial 21 finished with value: 0.5149248071748405 and parameters: {'kernel': 'rbf', 'C': 9.314384460143586, 'epsilon': 0.010542074699291063, 'gamma': 'scale'}. Best is trial 10 with value: 0.5222781671451275.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.93 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.63 | R2: 0.51
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 18:12:04,512] Trial 22 finished with value: 0.4699256575140779 and parameters: {'kernel': 'rbf', 'C': 6.788916652840602, 'epsilon': 0.02459413769470553, 'gamma': 'scale'}. Best is trial 10 with value: 0.5222781671451275.
[I 2025-07-11 18:12:04,597] Trial 23 finished with value: 0.35605673357836587 and parameters: {'kernel': 'rbf', 'C': 3.7713834605268173, 'epsilon': 0.04365646046900792, 'gamma': 'scale'}. Best is trial 10 with value: 0.5222781671451275.
[I 2025-07-11 18:12:04,677] Trial 24 finished with value: 0.4926785573436645 and parameters: {'kernel': 'rbf', 'C': 7.583278341491164, 'epsilon': 0.07387136781850404, 'gamma': 'scale'}. Best is trial 10 with value: 0.5222781671451275.
[I 2025-07-11 18:12:04,678] A new study created in memory with name: no-name-314d9fe2-9201-4261-b1c5-83268e9c9f30

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.75 | R2: 0.47
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.03 | R2: 0.36
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.69 | R2: 0.49

✅ SVR - Mejor R2: 0.52
📋 Parámetros: {'kernel': 'rbf', 'C': 9.99146026649796, 'epsilon': 0.016757551201296503, 'gamma': 'scale'}

Buscando mejores hiperparámetros para KNN...
Fold 1
Fold 2

[I 2025-07-11 18:12:04,742] Trial 0 finished with value: 0.443854354909869 and parameters: {'n_neighbors': 12, 'weights': 'uniform', 'leaf_size': 32}. Best is trial 0 with value: 0.443854354909869.
[I 2025-07-11 18:12:04,831] Trial 1 finished with value: 0.6760258049085068 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'leaf_size': 25}. Best is trial 1 with value: 0.6760258049085068.
[I 2025-07-11 18:12:04,902] Trial 2 finished with value: 0.5620185321365514 and parameters: {'n_neighbors': 12, 'weights': 'distance', 'leaf_size': 14}. Best is trial 1 with value: 0.6760258049085068.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.82 | R2: 0.44
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.15 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.50 | R2: 0.56
Fold 1

[I 2025-07-11 18:12:04,973] Trial 3 finished with value: 0.5292554066206117 and parameters: {'n_neighbors': 8, 'weights': 'uniform', 'leaf_size': 29}. Best is trial 1 with value: 0.6760258049085068.
[I 2025-07-11 18:12:05,041] Trial 4 finished with value: 0.5292554066206117 and parameters: {'n_neighbors': 8, 'weights': 'uniform', 'leaf_size': 10}. Best is trial 1 with value: 0.6760258049085068.
[I 2025-07-11 18:12:05,103] Trial 5 finished with value: 0.38047095385176366 and parameters: {'n_neighbors': 15, 'weights': 'uniform', 'leaf_size': 24}. Best is trial 1 with value: 0.6760258049085068.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.59 | R2: 0.53
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.59 | R2: 0.53
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.98 | R2: 0.38
Fold 1
Fold 2

[I 2025-07-11 18:12:05,166] Trial 6 finished with value: 0.5313646395218761 and parameters: {'n_neighbors': 14, 'weights': 'distance', 'leaf_size': 36}. Best is trial 1 with value: 0.6760258049085068.
[I 2025-07-11 18:12:05,231] Trial 7 finished with value: 0.7299191310872667 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'leaf_size': 35}. Best is trial 7 with value: 0.7299191310872667.
[I 2025-07-11 18:12:05,295] Trial 8 finished with value: 0.5620185321365514 and parameters: {'n_neighbors': 12, 'weights': 'distance', 'leaf_size': 32}. Best is trial 7 with value: 0.7299191310872667.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.59 | R2: 0.53
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.97 | R2: 0.73
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.50 | R2: 0.56
Fold 1
Fold 2
Fold 3

[I 2025-07-11 18:12:05,357] Trial 9 finished with value: 0.5620185321365514 and parameters: {'n_neighbors': 12, 'weights': 'distance', 'leaf_size': 38}. Best is trial 7 with value: 0.7299191310872667.
[I 2025-07-11 18:12:05,441] Trial 10 finished with value: 0.7074043623477853 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 19}. Best is trial 7 with value: 0.7299191310872667.
[I 2025-07-11 18:12:05,509] Trial 11 finished with value: 0.7074043623477853 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 19}. Best is trial 7 with value: 0.7299191310872667.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.50 | R2: 0.56
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.05 | R2: 0.71
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.05 | R2: 0.71
Fold 1
Fold 2

[I 2025-07-11 18:12:05,581] Trial 12 finished with value: 0.6910047902971639 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'leaf_size': 20}. Best is trial 7 with value: 0.7299191310872667.
[I 2025-07-11 18:12:05,657] Trial 13 finished with value: 0.6624733899577742 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'leaf_size': 40}. Best is trial 7 with value: 0.7299191310872667.
[I 2025-07-11 18:12:05,723] Trial 14 finished with value: 0.6910047902971639 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'leaf_size': 19}. Best is trial 7 with value: 0.7299191310872667.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.10 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.20 | R2: 0.66
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.10 | R2: 0.69
Fold 1
Fold 2

[I 2025-07-11 18:12:05,792] Trial 15 finished with value: 0.6624733899577742 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'leaf_size': 29}. Best is trial 7 with value: 0.7299191310872667.
[I 2025-07-11 18:12:05,868] Trial 16 finished with value: 0.7074043623477853 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 15}. Best is trial 7 with value: 0.7299191310872667.
[I 2025-07-11 18:12:05,935] Trial 17 finished with value: 0.6910047902971639 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'leaf_size': 34}. Best is trial 7 with value: 0.7299191310872667.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.20 | R2: 0.66
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.05 | R2: 0.71
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.10 | R2: 0.69
Fold 1
Fold 2

[I 2025-07-11 18:12:06,006] Trial 18 finished with value: 0.6063449917263208 and parameters: {'n_neighbors': 9, 'weights': 'distance', 'leaf_size': 24}. Best is trial 7 with value: 0.7299191310872667.
[I 2025-07-11 18:12:06,110] Trial 19 finished with value: 0.7299191310872667 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'leaf_size': 27}. Best is trial 7 with value: 0.7299191310872667.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.37 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.97 | R2: 0.73
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 18:12:06,190] Trial 20 finished with value: 0.5858596325675174 and parameters: {'n_neighbors': 10, 'weights': 'distance', 'leaf_size': 29}. Best is trial 7 with value: 0.7299191310872667.
[I 2025-07-11 18:12:06,266] Trial 21 finished with value: 0.7299191310872667 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'leaf_size': 26}. Best is trial 7 with value: 0.7299191310872667.
[I 2025-07-11 18:12:06,337] Trial 22 finished with value: 0.7299191310872667 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'leaf_size': 28}. Best is trial 7 with value: 0.7299191310872667.

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.43 | R2: 0.59
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.97 | R2: 0.73
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.97 | R2: 0.73
Fold 1
Fold 2
Fold 3

[I 2025-07-11 18:12:06,408] Trial 23 finished with value: 0.6624733899577742 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'leaf_size': 26}. Best is trial 7 with value: 0.7299191310872667.
[I 2025-07-11 18:12:06,484] Trial 24 finished with value: 0.6330868939685446 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'leaf_size': 22}. Best is trial 7 with value: 0.7299191310872667.
[I 2025-07-11 18:12:06,485] A new study created in memory with name: no-name-27345aab-a33e-4fb7-926f-275de1c4dd9a
[I 2025-07-11 18:12:06,568] Trial 0 finished with value: -0.062416420566608455 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 0 with value: -0.062416420566608455.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.20 | R2: 0.66
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.29 | R2: 0.63

✅ KNN - Mejor R2: 0.73
📋 Parámetros: {'n_neighbors': 4, 'weights': 'distance', 'leaf_size': 35}

Buscando mejores hiperparámetros para LR...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.90 | R2: -0.06
Fold 1

[I 2025-07-11 18:12:06,671] Trial 1 finished with value: -0.062416420566608455 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 0 with value: -0.062416420566608455.
[I 2025-07-11 18:12:06,756] Trial 2 finished with value: 0.2608450371523062 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 2 with value: 0.2608450371523062.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.90 | R2: -0.06
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.25 | R2: 0.26
Fold 1
Fold 2
Fold 3

[I 2025-07-11 18:12:06,839] Trial 3 finished with value: -0.062416420566608455 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 2 with value: 0.2608450371523062.
[I 2025-07-11 18:12:06,920] Trial 4 finished with value: 0.2608450371523062 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 2 with value: 0.2608450371523062.
[I 2025-07-11 18:12:06,987] Trial 5 finished with value: 0.2608450371523062 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 2 with value: 0.2608450371523062.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.90 | R2: -0.06
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.25 | R2: 0.26
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.25 | R2: 0.26
Fold 1
Fold 2

[I 2025-07-11 18:12:07,051] Trial 6 finished with value: 0.2608450371523062 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 2 with value: 0.2608450371523062.
[I 2025-07-11 18:12:07,117] Trial 7 finished with value: 0.2606423971202708 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 2 with value: 0.2608450371523062.
[I 2025-07-11 18:12:07,177] Trial 8 finished with value: 0.2606423971202708 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 2 with value: 0.2608450371523062.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.25 | R2: 0.26
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.25 | R2: 0.26
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.25 | R2: 0.26
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 18:12:07,238] Trial 9 finished with value: 0.2606423971202708 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 2 with value: 0.2608450371523062.
[I 2025-07-11 18:12:07,322] Trial 10 finished with value: -0.062416420567529496 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 2 with value: 0.2608450371523062.
[I 2025-07-11 18:12:07,409] Trial 11 finished with value: 0.2608450371523062 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 2 with value: 0.2608450371523062.

Fold 5
Running time: 0.1 sec
OOF RMSE: 3.25 | R2: 0.26
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.90 | R2: -0.06
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.25 | R2: 0.26
Fold 1

[I 2025-07-11 18:12:07,484] Trial 12 finished with value: 0.2608450371523062 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 2 with value: 0.2608450371523062.
[I 2025-07-11 18:12:07,550] Trial 13 finished with value: 0.2608450371523062 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 2 with value: 0.2608450371523062.
[I 2025-07-11 18:12:07,609] Trial 14 finished with value: 0.2608450371523062 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 2 with value: 0.2608450371523062.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.25 | R2: 0.26
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.25 | R2: 0.26
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.25 | R2: 0.26
Fold 1
Fold 2

[I 2025-07-11 18:12:07,669] Trial 15 finished with value: 0.2608450371523062 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 2 with value: 0.2608450371523062.
[I 2025-07-11 18:12:07,734] Trial 16 finished with value: 0.2608450371523062 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 2 with value: 0.2608450371523062.
[I 2025-07-11 18:12:07,792] Trial 17 finished with value: 0.2608450371523062 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 2 with value: 0.2608450371523062.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.25 | R2: 0.26
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.25 | R2: 0.26
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.25 | R2: 0.26
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 18:12:07,891] Trial 18 finished with value: -0.062416420567529496 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 2 with value: 0.2608450371523062.
[I 2025-07-11 18:12:07,999] Trial 19 finished with value: 0.2608450371523062 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 2 with value: 0.2608450371523062.

Fold 5
Running time: 0.1 sec
OOF RMSE: 3.90 | R2: -0.06
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.25 | R2: 0.26
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec

[I 2025-07-11 18:12:08,059] Trial 20 finished with value: 0.2608450371523062 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 2 with value: 0.2608450371523062.
[I 2025-07-11 18:12:08,127] Trial 21 finished with value: 0.2608450371523062 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 2 with value: 0.2608450371523062.
[I 2025-07-11 18:12:08,190] Trial 22 finished with value: 0.2608450371523062 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 2 with value: 0.2608450371523062.
[I 2025-07-11 18:12:08,249] Trial 23 finished with value: 0.2608450371523062 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 2 with value: 0.2608450371523062.

OOF RMSE: 3.25 | R2: 0.26
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.25 | R2: 0.26
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.25 | R2: 0.26
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.25 | R2: 0.26
Fold 1

[I 2025-07-11 18:12:08,313] Trial 24 finished with value: 0.2608450371523062 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 2 with value: 0.2608450371523062.
[I 2025-07-11 18:12:08,314] A new study created in memory with name: no-name-13f66baf-fe1c-4c18-a3f5-fb4ba4d8c3c7

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.25 | R2: 0.26

✅ LR - Mejor R2: 0.26
📋 Parámetros: {'fit_intercept': False, 'positive': True}

Buscando mejores hiperparámetros para RF...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:12:17,218] Trial 0 finished with value: 0.5465972088474842 and parameters: {'n_estimators': 300, 'max_depth': 15, 'min_samples_split': 9, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 0 with value: 0.5465972088474842.

Running time: 8.9 sec
OOF RMSE: 2.55 | R2: 0.55
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:12:31,024] Trial 1 finished with value: 0.5575629323429174 and parameters: {'n_estimators': 500, 'max_depth': 9, 'min_samples_split': 10, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 1 with value: 0.5575629323429174.

Running time: 13.8 sec
OOF RMSE: 2.52 | R2: 0.56
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:12:36,757] Trial 2 finished with value: 0.6594901361403664 and parameters: {'n_estimators': 300, 'max_depth': 8, 'min_samples_split': 2, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 2 with value: 0.6594901361403664.

Running time: 5.7 sec
OOF RMSE: 2.21 | R2: 0.66
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:12:41,414] Trial 3 finished with value: 0.5930818680725294 and parameters: {'n_estimators': 300, 'max_depth': 8, 'min_samples_split': 8, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 2 with value: 0.6594901361403664.

Running time: 4.7 sec
OOF RMSE: 2.41 | R2: 0.59
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:12:44,475] Trial 4 finished with value: 0.5565788740060389 and parameters: {'n_estimators': 100, 'max_depth': 13, 'min_samples_split': 10, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 2 with value: 0.6594901361403664.

Running time: 3.1 sec
OOF RMSE: 2.52 | R2: 0.56
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:12:52,557] Trial 5 finished with value: 0.5957426981446419 and parameters: {'n_estimators': 500, 'max_depth': 9, 'min_samples_split': 3, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 2 with value: 0.6594901361403664.

Running time: 8.1 sec
OOF RMSE: 2.40 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:13:03,723] Trial 6 finished with value: 0.6273892425829533 and parameters: {'n_estimators': 500, 'max_depth': 7, 'min_samples_split': 2, 'min_samples_leaf': 5, 'bootstrap': False}. Best is trial 2 with value: 0.6594901361403664.

Running time: 11.2 sec
OOF RMSE: 2.31 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:13:06,301] Trial 7 finished with value: 0.624392954271214 and parameters: {'n_estimators': 100, 'max_depth': 10, 'min_samples_split': 8, 'min_samples_leaf': 5, 'bootstrap': False}. Best is trial 2 with value: 0.6594901361403664.

Running time: 2.6 sec
OOF RMSE: 2.32 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:13:12,411] Trial 8 finished with value: 0.6697550364205267 and parameters: {'n_estimators': 300, 'max_depth': 11, 'min_samples_split': 2, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 8 with value: 0.6697550364205267.

Running time: 6.1 sec
OOF RMSE: 2.17 | R2: 0.67
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:13:14,514] Trial 9 finished with value: 0.6105860186762907 and parameters: {'n_estimators': 100, 'max_depth': 6, 'min_samples_split': 5, 'min_samples_leaf': 4, 'bootstrap': False}. Best is trial 8 with value: 0.6697550364205267.

Running time: 2.1 sec
OOF RMSE: 2.36 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:13:20,675] Trial 10 finished with value: 0.6703807879905612 and parameters: {'n_estimators': 300, 'max_depth': 12, 'min_samples_split': 5, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 10 with value: 0.6703807879905612.

Running time: 6.2 sec
OOF RMSE: 2.17 | R2: 0.67
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:13:26,811] Trial 11 finished with value: 0.6703807879905612 and parameters: {'n_estimators': 300, 'max_depth': 12, 'min_samples_split': 5, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 10 with value: 0.6703807879905612.

Running time: 6.1 sec
OOF RMSE: 2.17 | R2: 0.67
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:13:32,966] Trial 12 finished with value: 0.6703807879905612 and parameters: {'n_estimators': 300, 'max_depth': 12, 'min_samples_split': 5, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 10 with value: 0.6703807879905612.

Running time: 6.1 sec
OOF RMSE: 2.17 | R2: 0.67
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:13:39,105] Trial 13 finished with value: 0.6723300124820809 and parameters: {'n_estimators': 300, 'max_depth': 14, 'min_samples_split': 6, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 13 with value: 0.6723300124820809.

Running time: 6.1 sec
OOF RMSE: 2.16 | R2: 0.67
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:13:44,784] Trial 14 finished with value: 0.6662461049231347 and parameters: {'n_estimators': 300, 'max_depth': 15, 'min_samples_split': 7, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 13 with value: 0.6723300124820809.

Running time: 5.7 sec
OOF RMSE: 2.18 | R2: 0.67
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:13:50,867] Trial 15 finished with value: 0.6723300124820809 and parameters: {'n_estimators': 300, 'max_depth': 14, 'min_samples_split': 6, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 13 with value: 0.6723300124820809.

Running time: 6.1 sec
OOF RMSE: 2.16 | R2: 0.67
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:13:56,625] Trial 16 finished with value: 0.665574565010804 and parameters: {'n_estimators': 300, 'max_depth': 14, 'min_samples_split': 6, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 13 with value: 0.6723300124820809.

Running time: 5.8 sec
OOF RMSE: 2.19 | R2: 0.67
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:14:01,875] Trial 17 finished with value: 0.6420621139977527 and parameters: {'n_estimators': 300, 'max_depth': 14, 'min_samples_split': 7, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 13 with value: 0.6723300124820809.

Running time: 5.2 sec
OOF RMSE: 2.26 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:14:03,958] Trial 18 finished with value: 0.6576340689273558 and parameters: {'n_estimators': 100, 'max_depth': 14, 'min_samples_split': 4, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 13 with value: 0.6723300124820809.

Running time: 2.1 sec
OOF RMSE: 2.21 | R2: 0.66
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:14:10,491] Trial 19 finished with value: 0.6386980566975691 and parameters: {'n_estimators': 500, 'max_depth': 5, 'min_samples_split': 6, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 13 with value: 0.6723300124820809.

Running time: 6.5 sec
OOF RMSE: 2.27 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:14:16,849] Trial 20 finished with value: 0.6678942218146101 and parameters: {'n_estimators': 300, 'max_depth': 13, 'min_samples_split': 7, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 13 with value: 0.6723300124820809.

Running time: 6.3 sec
OOF RMSE: 2.18 | R2: 0.67
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:14:23,055] Trial 21 finished with value: 0.6699844152874362 and parameters: {'n_estimators': 300, 'max_depth': 12, 'min_samples_split': 4, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 13 with value: 0.6723300124820809.

Running time: 6.2 sec
OOF RMSE: 2.17 | R2: 0.67
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:14:29,332] Trial 22 finished with value: 0.669989306631803 and parameters: {'n_estimators': 300, 'max_depth': 13, 'min_samples_split': 4, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 13 with value: 0.6723300124820809.

Running time: 6.3 sec
OOF RMSE: 2.17 | R2: 0.67
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:14:35,069] Trial 23 finished with value: 0.6656144139073574 and parameters: {'n_estimators': 300, 'max_depth': 15, 'min_samples_split': 6, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 13 with value: 0.6723300124820809.

Running time: 5.7 sec
OOF RMSE: 2.19 | R2: 0.67
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:14:41,043] Trial 24 finished with value: 0.6718215908009117 and parameters: {'n_estimators': 300, 'max_depth': 11, 'min_samples_split': 6, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 13 with value: 0.6723300124820809.
[I 2025-07-11 18:14:41,044] A new study created in memory with name: no-name-e1317cb9-abb7-4c62-84dc-8b5467f351e4

Running time: 6.0 sec
OOF RMSE: 2.17 | R2: 0.67

✅ RF - Mejor R2: 0.67
📋 Parámetros: {'n_estimators': 300, 'max_depth': 14, 'min_samples_split': 6, 'min_samples_leaf': 2, 'bootstrap': True}

Buscando mejores hiperparámetros para CAT...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:14:43,318] Trial 0 finished with value: 0.715107301045445 and parameters: {'iterations': 500, 'learning_rate': 0.0278553617433149, 'depth': 5, 'l2_leaf_reg': 2.762096469408685}. Best is trial 0 with value: 0.715107301045445.

Running time: 2.3 sec
OOF RMSE: 2.02 | R2: 0.72
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:14:45,584] Trial 1 finished with value: 0.723175704026497 and parameters: {'iterations': 500, 'learning_rate': 0.022501415026183098, 'depth': 5, 'l2_leaf_reg': 2.6297613519910987}. Best is trial 1 with value: 0.723175704026497.

Running time: 2.3 sec
OOF RMSE: 1.99 | R2: 0.72
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:14:54,925] Trial 2 finished with value: 0.7159803802292827 and parameters: {'iterations': 2000, 'learning_rate': 0.047998011596886034, 'depth': 5, 'l2_leaf_reg': 5.595116068436995}. Best is trial 1 with value: 0.723175704026497.

Running time: 9.3 sec
OOF RMSE: 2.02 | R2: 0.72
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:17:25,055] Trial 3 finished with value: 0.7265599446956033 and parameters: {'iterations': 1000, 'learning_rate': 0.07284750606764506, 'depth': 10, 'l2_leaf_reg': 8.435135568098113}. Best is trial 3 with value: 0.7265599446956033.

Running time: 150.1 sec
OOF RMSE: 1.98 | R2: 0.73
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:17:33,999] Trial 4 finished with value: 0.718754652880256 and parameters: {'iterations': 2000, 'learning_rate': 0.027319335387181936, 'depth': 5, 'l2_leaf_reg': 3.31433367813241}. Best is trial 3 with value: 0.7265599446956033.

Running time: 8.9 sec
OOF RMSE: 2.01 | R2: 0.72
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:17:42,658] Trial 5 finished with value: 0.7146051563317648 and parameters: {'iterations': 2000, 'learning_rate': 0.013066228956408039, 'depth': 5, 'l2_leaf_reg': 7.3154315780866215}. Best is trial 3 with value: 0.7265599446956033.

Running time: 8.7 sec
OOF RMSE: 2.02 | R2: 0.71
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:17:51,880] Trial 6 finished with value: 0.7005638489210539 and parameters: {'iterations': 2000, 'learning_rate': 0.08126018991226727, 'depth': 5, 'l2_leaf_reg': 6.556146389267002}. Best is trial 3 with value: 0.7265599446956033.

Running time: 9.2 sec
OOF RMSE: 2.07 | R2: 0.70
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:19:05,226] Trial 7 finished with value: 0.7126247999381314 and parameters: {'iterations': 2000, 'learning_rate': 0.012684500402912123, 'depth': 8, 'l2_leaf_reg': 4.923254162659982}. Best is trial 3 with value: 0.7265599446956033.

Running time: 73.3 sec
OOF RMSE: 2.03 | R2: 0.71
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:19:47,167] Trial 8 finished with value: 0.7143131686898851 and parameters: {'iterations': 500, 'learning_rate': 0.054527293413282406, 'depth': 9, 'l2_leaf_reg': 9.993590041102884}. Best is trial 3 with value: 0.7265599446956033.

Running time: 41.9 sec
OOF RMSE: 2.02 | R2: 0.71
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:19:48,608] Trial 9 finished with value: 0.695936133158096 and parameters: {'iterations': 500, 'learning_rate': 0.02169396180977743, 'depth': 4, 'l2_leaf_reg': 6.280687370885667}. Best is trial 3 with value: 0.7265599446956033.

Running time: 1.4 sec
OOF RMSE: 2.09 | R2: 0.70
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:22:18,274] Trial 10 finished with value: 0.7194640958615037 and parameters: {'iterations': 1000, 'learning_rate': 0.09630100297015952, 'depth': 10, 'l2_leaf_reg': 9.207536150970284}. Best is trial 3 with value: 0.7265599446956033.

Running time: 149.7 sec
OOF RMSE: 2.00 | R2: 0.72
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:22:32,504] Trial 11 finished with value: 0.7022200860609117 and parameters: {'iterations': 1000, 'learning_rate': 0.044855881786980176, 'depth': 7, 'l2_leaf_reg': 1.2267643284959577}. Best is trial 3 with value: 0.7265599446956033.

Running time: 14.2 sec
OOF RMSE: 2.06 | R2: 0.70
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:22:46,857] Trial 12 finished with value: 0.7132485232203494 and parameters: {'iterations': 1000, 'learning_rate': 0.021313635443590336, 'depth': 7, 'l2_leaf_reg': 8.426580673790522}. Best is trial 3 with value: 0.7265599446956033.

Running time: 14.3 sec
OOF RMSE: 2.02 | R2: 0.71
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:23:23,994] Trial 13 finished with value: 0.7148683793220877 and parameters: {'iterations': 1000, 'learning_rate': 0.061679942481104186, 'depth': 8, 'l2_leaf_reg': 4.127749797565716}. Best is trial 3 with value: 0.7265599446956033.

Running time: 37.1 sec
OOF RMSE: 2.02 | R2: 0.71
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:24:39,182] Trial 14 finished with value: 0.7258786466357809 and parameters: {'iterations': 500, 'learning_rate': 0.03583535058516177, 'depth': 10, 'l2_leaf_reg': 1.7616848277691328}. Best is trial 3 with value: 0.7265599446956033.

Running time: 75.2 sec
OOF RMSE: 1.98 | R2: 0.73
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:25:54,815] Trial 15 finished with value: 0.7137480341402086 and parameters: {'iterations': 500, 'learning_rate': 0.04128680771720379, 'depth': 10, 'l2_leaf_reg': 1.4906180555633133}. Best is trial 3 with value: 0.7265599446956033.
[I 2025-07-11 18:25:54,816] A new study created in memory with name: no-name-278da541-ed3f-4e5b-8c49-21c0211d6918
[I 2025-07-11 18:25:54,898] Trial 0 finished with value: -7.20156809632666e-05 and parameters: {'alpha': 3.083590029557236, 'l1_ratio': 0.5112005347587949}. Best is trial 0 with value: -7.20156809632666e-05.

Running time: 75.6 sec
OOF RMSE: 2.02 | R2: 0.71

✅ CAT - Mejor R2: 0.73
📋 Parámetros: {'iterations': 1000, 'learning_rate': 0.07284750606764506, 'depth': 10, 'l2_leaf_reg': 8.435135568098113}

Buscando mejores hiperparámetros para EN...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.78 | R2: -0.00
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.088e+02, tolerance: 3.043e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.436e+02, tolerance: 2.664e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.601e+02, tolerance: 2.195e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.099e+02, tolerance: 2.302e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.268e+02, tolerance: 2.844e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 18:25:55,028] Trial 1 finished with value: -0.007379510665964428 and parameters: {'alpha': 0.0011711838377967852, 'l1_ratio': 0.5478797219130557}. Best is trial 0 with value: -7.20156809632666e-05.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.993e+02, tolerance: 3.043e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.314e+02, tolerance: 2.664e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.590e+02, tolerance: 2.195e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.985e+02, tolerance: 2.302e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.213e+02, tolerance: 2.844e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 18:25:55,164] Trial 2 finished with value: -0.00962911133459654 and parameters: {'alpha': 0.001152133090253903, 'l1_ratio': 0.5794796071702429}. Best is trial 0 with value: -7.20156809632666e-05.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.070e+01, tolerance: 3.043e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.463e+00, tolerance: 2.664e-01
  model = cd_fast.enet_coordinate_descent(

Running time: 0.1 sec
OOF RMSE: 3.80 | R2: -0.01
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.80 | R2: -0.01
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.939e+00, tolerance: 2.195e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.514e+00, tolerance: 2.302e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.225e+00, tolerance: 2.844e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 18:25:55,313] Trial 3 finished with value: -0.003355288222317343 and parameters: {'alpha': 0.0090993350716778, 'l1_ratio': 0.8706872341932179}. Best is trial 0 with value: -7.20156809632666e-05.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.79 | R2: -0.00
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 18:25:55,473] Trial 4 finished with value: 0.004258768312589645 and parameters: {'alpha': 2.5034054727943276, 'l1_ratio': 0.5280892171798579}. Best is trial 4 with value: 0.004258768312589645.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.833e+02, tolerance: 3.043e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.559e+02, tolerance: 2.664e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.184e+02, tolerance: 2.195e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.504e+02, tolerance: 2.302e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.422e+02, tolerance: 2.844e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 18:25:55,609] Trial 5 finished with value: -0.011311231056129634 and parameters: {'alpha': 0.0005881040866702552, 'l1_ratio': 0.7774417936154274}. Best is trial 4 with value: 0.004258768312589645.

Fold 5
Running time: 0.1 sec
OOF RMSE: 3.77 | R2: 0.00
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.80 | R2: -0.01
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.449e+02, tolerance: 3.043e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.560e+02, tolerance: 2.664e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.507e+01, tolerance: 2.195e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.406e+01, tolerance: 2.302e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.211e+02, tolerance: 2.844e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 18:25:55,728] Trial 6 finished with value: 0.00025629009517080803 and parameters: {'alpha': 0.005400169792502619, 'l1_ratio': 0.536257786748674}. Best is trial 4 with value: 0.004258768312589645.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.344e+02, tolerance: 3.043e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.988e+02, tolerance: 2.664e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.181e+02, tolerance: 2.195e-01
  model = cd_fast.enet_coordinate_descent(

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.78 | R2: 0.00
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.057e+02, tolerance: 2.302e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.110e+02, tolerance: 2.844e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 18:25:55,868] Trial 7 finished with value: -0.004358889800962995 and parameters: {'alpha': 0.004078014730676352, 'l1_ratio': 0.11792440233429147}. Best is trial 4 with value: 0.004258768312589645.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.886e-01, tolerance: 3.043e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.036e+00, tolerance: 2.664e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 18:25:56,023] Trial 8 finished with value: 0.11006266291499478 and parameters: {'alpha': 0.0388558125911922, 'l1_ratio': 0.16986803839436182}. Best is trial 8 with value: 0.11006266291499478.

Running time: 0.1 sec
OOF RMSE: 3.79 | R2: -0.00
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.57 | R2: 0.11
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.703e+02, tolerance: 3.043e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.534e+02, tolerance: 2.664e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.902e+02, tolerance: 2.195e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.628e+02, tolerance: 2.302e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.366e+02, tolerance: 2.844e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 18:25:56,189] Trial 9 finished with value: -0.06373942414474354 and parameters: {'alpha': 0.00011397526575191846, 'l1_ratio': 0.4346352823464533}. Best is trial 8 with value: 0.11006266291499478.

Fold 3
Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 3.90 | R2: -0.06
Fold 1
Fold 2
Fold 3

[I 2025-07-11 18:25:56,389] Trial 10 finished with value: 0.1961476900587229 and parameters: {'alpha': 0.2835925621389237, 'l1_ratio': 0.004879585744342968}. Best is trial 10 with value: 0.1961476900587229.
[I 2025-07-11 18:25:56,513] Trial 11 finished with value: 0.18734991420811342 and parameters: {'alpha': 0.18425007408565233, 'l1_ratio': 0.050644027533963576}. Best is trial 10 with value: 0.1961476900587229.

Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 3.39 | R2: 0.20
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.41 | R2: 0.19

[I 2025-07-11 18:25:56,641] Trial 12 finished with value: 0.1873947630521694 and parameters: {'alpha': 0.21428635919116193, 'l1_ratio': 0.009235711103119902}. Best is trial 10 with value: 0.1961476900587229.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.41 | R2: 0.19
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 18:25:56,768] Trial 13 finished with value: 0.21800031811363108 and parameters: {'alpha': 0.25350408418250187, 'l1_ratio': 0.3037219690192088}. Best is trial 13 with value: 0.21800031811363108.
[I 2025-07-11 18:25:56,908] Trial 14 finished with value: 0.18263068170392538 and parameters: {'alpha': 0.5336189012246016, 'l1_ratio': 0.2880204110415104}. Best is trial 13 with value: 0.21800031811363108.

Fold 5
Running time: 0.1 sec
OOF RMSE: 3.34 | R2: 0.22
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.42 | R2: 0.18
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.229e+00, tolerance: 2.664e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 18:25:57,080] Trial 15 finished with value: 0.12465753030606552 and parameters: {'alpha': 0.04464450808523742, 'l1_ratio': 0.2801838439608374}. Best is trial 13 with value: 0.21800031811363108.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 3.54 | R2: 0.12
Fold 1
Fold 2
Fold 3

[I 2025-07-11 18:25:57,184] Trial 16 finished with value: 0.15797098618851813 and parameters: {'alpha': 0.6485195516487711, 'l1_ratio': 0.2980978292480438}. Best is trial 13 with value: 0.21800031811363108.
[I 2025-07-11 18:25:57,325] Trial 17 finished with value: 0.19771097902698598 and parameters: {'alpha': 0.11278431628128034, 'l1_ratio': 0.382894636636765}. Best is trial 13 with value: 0.21800031811363108.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.47 | R2: 0.16
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.39 | R2: 0.20
Fold 1

[I 2025-07-11 18:25:57,434] Trial 18 finished with value: -0.0003636740809507266 and parameters: {'alpha': 6.322914258234518, 'l1_ratio': 0.40656496503888595}. Best is trial 13 with value: 0.21800031811363108.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.78 | R2: -0.00
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:25:57,567] Trial 19 finished with value: 0.18181186741350008 and parameters: {'alpha': 0.0630470149610562, 'l1_ratio': 0.6879946736955306}. Best is trial 13 with value: 0.21800031811363108.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.921e+00, tolerance: 3.043e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.489e+01, tolerance: 2.664e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.802e-01, tolerance: 2.195e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.413e+00, tolerance: 2.302e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.730e+01, tolerance: 2.844e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 18:25:57,708] Trial 20 finished with value: 0.04114128324687383 and parameters: {'alpha': 0.01476073245715643, 'l1_ratio': 0.36852251891138427}. Best is trial 13 with value: 0.21800031811363108.

Running time: 0.1 sec
OOF RMSE: 3.42 | R2: 0.18
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.70 | R2: 0.04
Fold 1
Fold 2
Fold 3

[I 2025-07-11 18:25:57,816] Trial 21 finished with value: 0.19578261911698414 and parameters: {'alpha': 0.16453658349352784, 'l1_ratio': 0.16715247387706117}. Best is trial 13 with value: 0.21800031811363108.
[I 2025-07-11 18:25:57,934] Trial 22 finished with value: 0.12329416482549416 and parameters: {'alpha': 0.9835431406407601, 'l1_ratio': 0.23045039312417867}. Best is trial 13 with value: 0.21800031811363108.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.39 | R2: 0.20
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.54 | R2: 0.12
Fold 1

[I 2025-07-11 18:25:58,105] Trial 23 finished with value: 0.206140604378246 and parameters: {'alpha': 0.08490550359345113, 'l1_ratio': 0.6530389678837942}. Best is trial 13 with value: 0.21800031811363108.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 3.37 | R2: 0.21
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 18:25:58,226] Trial 24 finished with value: 0.22687812742962465 and parameters: {'alpha': 0.0875108209046544, 'l1_ratio': 0.9840610418292111}. Best is trial 24 with value: 0.22687812742962465.
[I 2025-07-11 18:25:58,227] A new study created in memory with name: no-name-dc502c41-0412-496b-b23b-d9020dcbf698

Fold 5
Running time: 0.1 sec
OOF RMSE: 3.32 | R2: 0.23

✅ EN - Mejor R2: 0.23
📋 Parámetros: {'alpha': 0.0875108209046544, 'l1_ratio': 0.9840610418292111}

🔍 Optimizando en C2X-Complex_rhown_9x9_depth_lt_1...
Buscando mejores hiperparámetros para XGB...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:26:01,512] Trial 0 finished with value: 0.6548582247199295 and parameters: {'n_estimators': 500, 'learning_rate': 0.014757731002669743, 'max_depth': 6, 'min_child_weight': 1, 'subsample': 0.9527172945239707, 'colsample_bytree': 0.6713173423001675}. Best is trial 0 with value: 0.6548582247199295.

Running time: 3.3 sec
OOF RMSE: 2.04 | R2: 0.65
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:26:08,852] Trial 1 finished with value: 0.6304058404928073 and parameters: {'n_estimators': 1000, 'learning_rate': 0.007444135716166664, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.8774516520006967, 'colsample_bytree': 0.9099961049673753}. Best is trial 0 with value: 0.6548582247199295.

Running time: 7.3 sec
OOF RMSE: 2.11 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:26:11,290] Trial 2 finished with value: 0.5897255723161181 and parameters: {'n_estimators': 500, 'learning_rate': 0.03802446546480885, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.7097405276557328, 'colsample_bytree': 0.7821423028603913}. Best is trial 0 with value: 0.6548582247199295.

Running time: 2.4 sec
OOF RMSE: 2.22 | R2: 0.59
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:26:13,864] Trial 3 finished with value: 0.6336599179460207 and parameters: {'n_estimators': 500, 'learning_rate': 0.006638444435884524, 'max_depth': 5, 'min_child_weight': 1, 'subsample': 0.8194004261178156, 'colsample_bytree': 0.6299150945538223}. Best is trial 0 with value: 0.6548582247199295.

Running time: 2.6 sec
OOF RMSE: 2.10 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:26:20,163] Trial 4 finished with value: 0.5841108384640195 and parameters: {'n_estimators': 1000, 'learning_rate': 0.02545481127489082, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.6272642517202732, 'colsample_bytree': 0.6700403131454242}. Best is trial 0 with value: 0.6548582247199295.

Running time: 6.3 sec
OOF RMSE: 2.24 | R2: 0.58
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:26:27,823] Trial 5 finished with value: 0.6646189001317588 and parameters: {'n_estimators': 1000, 'learning_rate': 0.012779167259174738, 'max_depth': 6, 'min_child_weight': 1, 'subsample': 0.8109604551437071, 'colsample_bytree': 0.7572789443439116}. Best is trial 5 with value: 0.6646189001317588.

Running time: 7.7 sec
OOF RMSE: 2.01 | R2: 0.66
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:26:35,445] Trial 6 finished with value: 0.5962835301869098 and parameters: {'n_estimators': 2000, 'learning_rate': 0.09501963310945916, 'max_depth': 8, 'min_child_weight': 2, 'subsample': 0.6466444983654479, 'colsample_bytree': 0.6213899152436705}. Best is trial 5 with value: 0.6646189001317588.

Running time: 7.6 sec
OOF RMSE: 2.20 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:26:41,145] Trial 7 finished with value: 0.6262202052997237 and parameters: {'n_estimators': 500, 'learning_rate': 0.01142533140204619, 'max_depth': 8, 'min_child_weight': 2, 'subsample': 0.930917529118167, 'colsample_bytree': 0.9298794290805417}. Best is trial 5 with value: 0.6646189001317588.

Running time: 5.7 sec
OOF RMSE: 2.12 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:26:47,146] Trial 8 finished with value: 0.6472966385589233 and parameters: {'n_estimators': 1000, 'learning_rate': 0.011297193700520262, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.8074370117191629, 'colsample_bytree': 0.8326650344462289}. Best is trial 5 with value: 0.6646189001317588.

Running time: 6.0 sec
OOF RMSE: 2.06 | R2: 0.65
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:26:51,617] Trial 9 finished with value: 0.6393284611377121 and parameters: {'n_estimators': 1000, 'learning_rate': 0.055182998568163825, 'max_depth': 6, 'min_child_weight': 1, 'subsample': 0.9961454074345596, 'colsample_bytree': 0.7010566723420546}. Best is trial 5 with value: 0.6646189001317588.

Running time: 4.5 sec
OOF RMSE: 2.08 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:27:04,961] Trial 10 finished with value: 0.5635596372871092 and parameters: {'n_estimators': 2000, 'learning_rate': 0.020681599305772957, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.7478011153867514, 'colsample_bytree': 0.998189033964478}. Best is trial 5 with value: 0.6646189001317588.

Running time: 13.3 sec
OOF RMSE: 2.29 | R2: 0.56
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:27:08,424] Trial 11 finished with value: 0.6533224987150938 and parameters: {'n_estimators': 500, 'learning_rate': 0.01612170752618939, 'max_depth': 6, 'min_child_weight': 1, 'subsample': 0.896334238114336, 'colsample_bytree': 0.7467593364882817}. Best is trial 5 with value: 0.6646189001317588.

Running time: 3.5 sec
OOF RMSE: 2.04 | R2: 0.65
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:27:16,164] Trial 12 finished with value: 0.6480843621228192 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01249425619415741, 'max_depth': 6, 'min_child_weight': 1, 'subsample': 0.9433343383775238, 'colsample_bytree': 0.7063835371100522}. Best is trial 5 with value: 0.6646189001317588.

Running time: 7.7 sec
OOF RMSE: 2.06 | R2: 0.65
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:27:21,348] Trial 13 finished with value: 0.6512204694853269 and parameters: {'n_estimators': 500, 'learning_rate': 0.02814813128235141, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.8562187501738185, 'colsample_bytree': 0.8252167865386643}. Best is trial 5 with value: 0.6646189001317588.

Running time: 5.2 sec
OOF RMSE: 2.05 | R2: 0.65
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:27:33,974] Trial 14 finished with value: 0.6319114660392633 and parameters: {'n_estimators': 2000, 'learning_rate': 0.0053332048216677645, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.7422123185360221, 'colsample_bytree': 0.7561279552987499}. Best is trial 5 with value: 0.6646189001317588.

Running time: 12.6 sec
OOF RMSE: 2.10 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:27:40,171] Trial 15 finished with value: 0.6403814466127166 and parameters: {'n_estimators': 1000, 'learning_rate': 0.009365888926284252, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.9913561257585431, 'colsample_bytree': 0.6804205245865496}. Best is trial 5 with value: 0.6646189001317588.

Running time: 6.2 sec
OOF RMSE: 2.08 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:27:43,025] Trial 16 finished with value: 0.6563224951634873 and parameters: {'n_estimators': 500, 'learning_rate': 0.01808829250605135, 'max_depth': 5, 'min_child_weight': 1, 'subsample': 0.683752448129704, 'colsample_bytree': 0.8656467500706123}. Best is trial 5 with value: 0.6646189001317588.

Running time: 2.8 sec
OOF RMSE: 2.03 | R2: 0.66
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:27:45,703] Trial 17 finished with value: 0.6025681252682338 and parameters: {'n_estimators': 500, 'learning_rate': 0.03959067419631842, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.6865012775469195, 'colsample_bytree': 0.8773942069306417}. Best is trial 5 with value: 0.6646189001317588.

Running time: 2.7 sec
OOF RMSE: 2.19 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:27:52,615] Trial 18 finished with value: 0.6479775847556404 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01809454304739192, 'max_depth': 5, 'min_child_weight': 1, 'subsample': 0.7558666301855749, 'colsample_bytree': 0.8630284063676092}. Best is trial 5 with value: 0.6646189001317588.

Running time: 6.9 sec
OOF RMSE: 2.06 | R2: 0.65
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:28:03,223] Trial 19 finished with value: 0.5833545330232826 and parameters: {'n_estimators': 2000, 'learning_rate': 0.03330405337537714, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.605342085441915, 'colsample_bytree': 0.9378046763035298}. Best is trial 5 with value: 0.6646189001317588.

Running time: 10.6 sec
OOF RMSE: 2.24 | R2: 0.58
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:28:06,204] Trial 20 finished with value: 0.5873020299622028 and parameters: {'n_estimators': 500, 'learning_rate': 0.05907501260339812, 'max_depth': 5, 'min_child_weight': 1, 'subsample': 0.6762620914308943, 'colsample_bytree': 0.7975809731261012}. Best is trial 5 with value: 0.6646189001317588.

Running time: 3.0 sec
OOF RMSE: 2.23 | R2: 0.59
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:28:09,680] Trial 21 finished with value: 0.6578065944212561 and parameters: {'n_estimators': 500, 'learning_rate': 0.015655293462486775, 'max_depth': 6, 'min_child_weight': 1, 'subsample': 0.832992133759893, 'colsample_bytree': 0.7413256716292063}. Best is trial 5 with value: 0.6646189001317588.

Running time: 3.5 sec
OOF RMSE: 2.03 | R2: 0.66
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:28:12,982] Trial 22 finished with value: 0.6514961982408958 and parameters: {'n_estimators': 500, 'learning_rate': 0.020496915424825637, 'max_depth': 6, 'min_child_weight': 1, 'subsample': 0.7847272499967093, 'colsample_bytree': 0.7395197951696447}. Best is trial 5 with value: 0.6646189001317588.

Running time: 3.3 sec
OOF RMSE: 2.05 | R2: 0.65
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:28:16,387] Trial 23 finished with value: 0.640155416939729 and parameters: {'n_estimators': 500, 'learning_rate': 0.008479631871392557, 'max_depth': 6, 'min_child_weight': 1, 'subsample': 0.8396078876541552, 'colsample_bytree': 0.8335141701223684}. Best is trial 5 with value: 0.6646189001317588.

Running time: 3.4 sec
OOF RMSE: 2.08 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:28:19,840] Trial 24 finished with value: 0.6415799863196628 and parameters: {'n_estimators': 500, 'learning_rate': 0.014320424733418503, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.7803344343550067, 'colsample_bytree': 0.7752041206470884}. Best is trial 5 with value: 0.6646189001317588.
[I 2025-07-11 18:28:19,844] A new study created in memory with name: no-name-ca300e5b-687e-49a0-be64-62af439d4886

Running time: 3.4 sec
OOF RMSE: 2.08 | R2: 0.64

✅ XGB - Mejor R2: 0.66
📋 Parámetros: {'n_estimators': 1000, 'learning_rate': 0.012779167259174738, 'max_depth': 6, 'min_child_weight': 1, 'subsample': 0.8109604551437071, 'colsample_bytree': 0.7572789443439116}

Buscando mejores hiperparámetros para LBM...
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 18:28:20,134] Trial 0 finished with value: 0.5889238206724818 and parameters: {'learning_rate': 0.016557222771377514, 'num_leaves': 80, 'max_depth': 7, 'min_child_samples': 12, 'subsample': 0.8383620646446097, 'colsample_bytree': 0.7036450775171037, 'n_estimators': 500}. Best is trial 0 with value: 0.5889238206724818.

Fold 5
Running time: 0.3 sec
OOF RMSE: 2.22 | R2: 0.59
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 18:28:20,646] Trial 1 finished with value: 0.5642053946493978 and parameters: {'learning_rate': 0.02640538810005711, 'num_leaves': 80, 'max_depth': 6, 'min_child_samples': 20, 'subsample': 0.8074744877520061, 'colsample_bytree': 0.6620896592918372, 'n_estimators': 1000}. Best is trial 0 with value: 0.5889238206724818.

Fold 5
Running time: 0.5 sec
OOF RMSE: 2.29 | R2: 0.56
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:28:21,583] Trial 2 finished with value: 0.5674952981380958 and parameters: {'learning_rate': 0.09605334016679387, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 14, 'subsample': 0.7108529609013868, 'colsample_bytree': 0.9572490981839223, 'n_estimators': 2000}. Best is trial 0 with value: 0.5889238206724818.

Running time: 0.9 sec
OOF RMSE: 2.28 | R2: 0.57
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 18:28:22,288] Trial 3 finished with value: 0.6195517511263349 and parameters: {'learning_rate': 0.02903744998694513, 'num_leaves': 60, 'max_depth': 7, 'min_child_samples': 5, 'subsample': 0.9208431361434186, 'colsample_bytree': 0.7722003696491838, 'n_estimators': 1000}. Best is trial 3 with value: 0.6195517511263349.

Fold 5
Running time: 0.7 sec
OOF RMSE: 2.14 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:28:22,584] Trial 4 finished with value: 0.5909352300800843 and parameters: {'learning_rate': 0.07382084328810588, 'num_leaves': 40, 'max_depth': 5, 'min_child_samples': 6, 'subsample': 0.9467587205685645, 'colsample_bytree': 0.8399003617218546, 'n_estimators': 500}. Best is trial 3 with value: 0.6195517511263349.

Running time: 0.3 sec
OOF RMSE: 2.22 | R2: 0.59
Fold 1
Fold 2
Fold 3

[I 2025-07-11 18:28:22,994] Trial 5 finished with value: 0.5410461822448447 and parameters: {'learning_rate': 0.016272918451118872, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 19, 'subsample': 0.6499818234257995, 'colsample_bytree': 0.8774345247778499, 'n_estimators': 1000}. Best is trial 3 with value: 0.6195517511263349.

Fold 4
Fold 5
Running time: 0.4 sec
OOF RMSE: 2.35 | R2: 0.54
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 18:28:23,521] Trial 6 finished with value: 0.5611263563864899 and parameters: {'learning_rate': 0.005663236235048319, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 18, 'subsample': 0.9321695684755189, 'colsample_bytree': 0.9581209130163755, 'n_estimators': 1000}. Best is trial 3 with value: 0.6195517511263349.

Fold 5
Running time: 0.5 sec
OOF RMSE: 2.30 | R2: 0.56
Fold 1
Fold 2

[I 2025-07-11 18:28:23,845] Trial 7 finished with value: 0.6190269250190934 and parameters: {'learning_rate': 0.04290233023499733, 'num_leaves': 40, 'max_depth': 8, 'min_child_samples': 11, 'subsample': 0.7323074192565762, 'colsample_bytree': 0.6434195062869645, 'n_estimators': 500}. Best is trial 3 with value: 0.6195517511263349.

Fold 3
Fold 4
Fold 5
Running time: 0.3 sec
OOF RMSE: 2.14 | R2: 0.62
Fold 1
Fold 2
Fold 3

[I 2025-07-11 18:28:24,251] Trial 8 finished with value: 0.5474631388651303 and parameters: {'learning_rate': 0.01795915145667585, 'num_leaves': 80, 'max_depth': 5, 'min_child_samples': 18, 'subsample': 0.7958308360060102, 'colsample_bytree': 0.7774474156935022, 'n_estimators': 1000}. Best is trial 3 with value: 0.6195517511263349.

Fold 4
Fold 5
Running time: 0.4 sec
OOF RMSE: 2.33 | R2: 0.55
Fold 1

[I 2025-07-11 18:28:24,507] Trial 9 finished with value: 0.5453673425473536 and parameters: {'learning_rate': 0.008581453534537004, 'num_leaves': 80, 'max_depth': 6, 'min_child_samples': 19, 'subsample': 0.6072391582031752, 'colsample_bytree': 0.8632510232404069, 'n_estimators': 500}. Best is trial 3 with value: 0.6195517511263349.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.3 sec
OOF RMSE: 2.34 | R2: 0.55
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 18:28:25,357] Trial 10 finished with value: 0.5922258486125044 and parameters: {'learning_rate': 0.04018510024514321, 'num_leaves': 60, 'max_depth': 8, 'min_child_samples': 25, 'subsample': 0.9994987130551409, 'colsample_bytree': 0.7665920174407246, 'n_estimators': 2000}. Best is trial 3 with value: 0.6195517511263349.

Fold 5
Running time: 0.8 sec
OOF RMSE: 2.21 | R2: 0.59
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 18:28:25,740] Trial 11 finished with value: 0.6393657759139486 and parameters: {'learning_rate': 0.03888035629897744, 'num_leaves': 40, 'max_depth': 8, 'min_child_samples': 5, 'subsample': 0.7309779883295796, 'colsample_bytree': 0.6039360780165048, 'n_estimators': 500}. Best is trial 11 with value: 0.6393657759139486.

Fold 5
Running time: 0.4 sec
OOF RMSE: 2.08 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:28:26,140] Trial 12 finished with value: 0.6459706944286683 and parameters: {'learning_rate': 0.04049635282595456, 'num_leaves': 60, 'max_depth': 8, 'min_child_samples': 5, 'subsample': 0.8860242605873505, 'colsample_bytree': 0.6133587240716104, 'n_estimators': 500}. Best is trial 12 with value: 0.6459706944286683.

Running time: 0.4 sec
OOF RMSE: 2.06 | R2: 0.65
Fold 1
Fold 2
Fold 3

[I 2025-07-11 18:28:26,491] Trial 13 finished with value: 0.5760744347495119 and parameters: {'learning_rate': 0.054132021686240914, 'num_leaves': 60, 'max_depth': 8, 'min_child_samples': 9, 'subsample': 0.8597380141091614, 'colsample_bytree': 0.6069113872364358, 'n_estimators': 500}. Best is trial 12 with value: 0.6459706944286683.

Fold 4
Fold 5
Running time: 0.3 sec
OOF RMSE: 2.26 | R2: 0.58
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:28:26,839] Trial 14 finished with value: 0.5798337102878764 and parameters: {'learning_rate': 0.05589074322016654, 'num_leaves': 40, 'max_depth': 8, 'min_child_samples': 8, 'subsample': 0.7272402622848966, 'colsample_bytree': 0.7053185556584733, 'n_estimators': 500}. Best is trial 12 with value: 0.6459706944286683.

Running time: 0.3 sec
OOF RMSE: 2.25 | R2: 0.58
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 18:28:27,160] Trial 15 finished with value: 0.6054558725147836 and parameters: {'learning_rate': 0.03253577239575113, 'num_leaves': 60, 'max_depth': 7, 'min_child_samples': 8, 'subsample': 0.8744668014531192, 'colsample_bytree': 0.6004151136696717, 'n_estimators': 500}. Best is trial 12 with value: 0.6459706944286683.

Fold 5
Running time: 0.3 sec
OOF RMSE: 2.18 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:28:27,596] Trial 16 finished with value: 0.5818535599153476 and parameters: {'learning_rate': 0.01013661855373209, 'num_leaves': 40, 'max_depth': 8, 'min_child_samples': 6, 'subsample': 0.7808531201836086, 'colsample_bytree': 0.6887787635555489, 'n_estimators': 500}. Best is trial 12 with value: 0.6459706944286683.

Running time: 0.4 sec
OOF RMSE: 2.24 | R2: 0.58
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:28:28,857] Trial 17 finished with value: 0.6101524567347033 and parameters: {'learning_rate': 0.06336125306652983, 'num_leaves': 60, 'max_depth': 8, 'min_child_samples': 11, 'subsample': 0.6785940962923704, 'colsample_bytree': 0.7346017621078482, 'n_estimators': 2000}. Best is trial 12 with value: 0.6459706944286683.

Running time: 1.3 sec
OOF RMSE: 2.16 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 18:28:29,130] Trial 18 finished with value: 0.6046457025052773 and parameters: {'learning_rate': 0.03876408569982821, 'num_leaves': 40, 'max_depth': 6, 'min_child_samples': 15, 'subsample': 0.7643842462727221, 'colsample_bytree': 0.6549161510033631, 'n_estimators': 500}. Best is trial 12 with value: 0.6459706944286683.

Fold 5
Running time: 0.3 sec
OOF RMSE: 2.18 | R2: 0.60
Fold 1
Fold 2

[I 2025-07-11 18:28:29,516] Trial 19 finished with value: 0.6377887371118689 and parameters: {'learning_rate': 0.02403250533940924, 'num_leaves': 60, 'max_depth': 7, 'min_child_samples': 5, 'subsample': 0.8933400791310698, 'colsample_bytree': 0.6289557406850491, 'n_estimators': 500}. Best is trial 12 with value: 0.6459706944286683.

Fold 3
Fold 4
Fold 5
Running time: 0.4 sec
OOF RMSE: 2.09 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:28:30,910] Trial 20 finished with value: 0.5441836429151323 and parameters: {'learning_rate': 0.09745490354298558, 'num_leaves': 40, 'max_depth': 8, 'min_child_samples': 9, 'subsample': 0.8313894785722292, 'colsample_bytree': 0.8157317716752417, 'n_estimators': 2000}. Best is trial 12 with value: 0.6459706944286683.

Running time: 1.4 sec
OOF RMSE: 2.34 | R2: 0.54
Fold 1
Fold 2
Fold 3

[I 2025-07-11 18:28:31,270] Trial 21 finished with value: 0.6334171051120632 and parameters: {'learning_rate': 0.019895796124467145, 'num_leaves': 60, 'max_depth': 7, 'min_child_samples': 5, 'subsample': 0.8924986935975597, 'colsample_bytree': 0.6342771308283641, 'n_estimators': 500}. Best is trial 12 with value: 0.6459706944286683.

Fold 4
Fold 5
Running time: 0.4 sec
OOF RMSE: 2.10 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:28:31,600] Trial 22 finished with value: 0.5740043969884965 and parameters: {'learning_rate': 0.024964083647145065, 'num_leaves': 60, 'max_depth': 7, 'min_child_samples': 7, 'subsample': 0.9758561693368858, 'colsample_bytree': 0.6048040855286515, 'n_estimators': 500}. Best is trial 12 with value: 0.6459706944286683.

Running time: 0.3 sec
OOF RMSE: 2.26 | R2: 0.57
Fold 1
Fold 2
Fold 3

[I 2025-07-11 18:28:32,022] Trial 23 finished with value: 0.6260805363825979 and parameters: {'learning_rate': 0.012174360190096272, 'num_leaves': 60, 'max_depth': 8, 'min_child_samples': 5, 'subsample': 0.9012476658680704, 'colsample_bytree': 0.6729852143366208, 'n_estimators': 500}. Best is trial 12 with value: 0.6459706944286683.

Fold 4
Fold 5
Running time: 0.4 sec
OOF RMSE: 2.12 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:28:32,332] Trial 24 finished with value: 0.5684979094714455 and parameters: {'learning_rate': 0.03305546729846497, 'num_leaves': 60, 'max_depth': 7, 'min_child_samples': 9, 'subsample': 0.8440062757788369, 'colsample_bytree': 0.6340639307325273, 'n_estimators': 500}. Best is trial 12 with value: 0.6459706944286683.
[I 2025-07-11 18:28:32,333] A new study created in memory with name: no-name-71c067c3-6da6-46aa-90ae-9bc583a9c716

Running time: 0.3 sec
OOF RMSE: 2.28 | R2: 0.57

✅ LBM - Mejor R2: 0.65
📋 Parámetros: {'learning_rate': 0.04049635282595456, 'num_leaves': 60, 'max_depth': 8, 'min_child_samples': 5, 'subsample': 0.8860242605873505, 'colsample_bytree': 0.6133587240716104, 'n_estimators': 500}

Buscando mejores hiperparámetros para MLP...
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

[I 2025-07-11 18:28:34,161] Trial 0 finished with value: 0.5642271854460823 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.009247225226913826, 'learning_rate': 'constant', 'learning_rate_init': 0.0008807746369329577}. Best is trial 0 with value: 0.5642271854460823.

Running time: 1.8 sec
OOF RMSE: 2.29 | R2: 0.56
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 18:28:35,743] Trial 1 finished with value: 0.5321959319417089 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'relu', 'solver': 'adam', 'alpha': 3.322016210211118e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.00042900424013498853}. Best is trial 0 with value: 0.5642271854460823.

Fold 4
Fold 5
Running time: 1.6 sec
OOF RMSE: 2.37 | R2: 0.53
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3
Fold 4

[I 2025-07-11 18:28:37,206] Trial 2 finished with value: 0.5709874672405806 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0005889488840897368, 'learning_rate': 'constant', 'learning_rate_init': 0.0004097733652710902}. Best is trial 2 with value: 0.5709874672405806.

Fold 5
Running time: 1.5 sec
OOF RMSE: 2.27 | R2: 0.57
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 18:28:37,904] Trial 3 finished with value: 0.45309712371194943 and parameters: {'hidden_layer_sizes': '50', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0025902776251080966, 'learning_rate': 'constant', 'learning_rate_init': 0.0009900024955407727}. Best is trial 2 with value: 0.5709874672405806.

Fold 4
Fold 5
Running time: 0.7 sec
OOF RMSE: 2.56 | R2: 0.45
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

[I 2025-07-11 18:28:40,966] Trial 4 finished with value: 0.44016228008017544 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.0011953641414335088, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0006562466146128985}. Best is trial 2 with value: 0.5709874672405806.

Running time: 3.1 sec
OOF RMSE: 2.59 | R2: 0.44
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 18:28:42,662] Trial 5 finished with value: 0.41953490630020795 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.0005626310890126765, 'learning_rate': 'constant', 'learning_rate_init': 0.0001691187676442752}. Best is trial 2 with value: 0.5709874672405806.

Running time: 1.7 sec
OOF RMSE: 2.64 | R2: 0.42
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

[I 2025-07-11 18:28:45,508] Trial 6 finished with value: 0.3271633979534505 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.0008122810859993299, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00013279167844035053}. Best is trial 2 with value: 0.5709874672405806.

Running time: 2.8 sec
OOF RMSE: 2.84 | R2: 0.33
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 18:28:46,300] Trial 7 finished with value: 0.6005190099438511 and parameters: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0010246053155767978, 'learning_rate': 'adaptive', 'learning_rate_init': 0.006218354426161081}. Best is trial 7 with value: 0.6005190099438511.

Running time: 0.8 sec
OOF RMSE: 2.19 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:28:47,425] Trial 8 finished with value: 0.6193838034446408 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'adam', 'alpha': 8.822164240930164e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.006139356885292696}. Best is trial 8 with value: 0.6193838034446408.

Running time: 1.1 sec
OOF RMSE: 2.14 | R2: 0.62
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

[I 2025-07-11 18:28:48,635] Trial 9 finished with value: 0.5394742519606122 and parameters: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.00012166352812297756, 'learning_rate': 'constant', 'learning_rate_init': 0.0005836765305047685}. Best is trial 8 with value: 0.6193838034446408.

Fold 4
Fold 5
Running time: 1.2 sec
OOF RMSE: 2.35 | R2: 0.54
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

[I 2025-07-11 18:28:50,127] Trial 10 finished with value: 0.41927802038966344 and parameters: {'hidden_layer_sizes': '50', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 1.4952955611632131e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.007620161931746055}. Best is trial 8 with value: 0.6193838034446408.

Running time: 1.5 sec
OOF RMSE: 2.64 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 18:28:50,899] Trial 11 finished with value: 0.5870369552838874 and parameters: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.05594014705013411, 'learning_rate': 'adaptive', 'learning_rate_init': 0.005349889490194722}. Best is trial 8 with value: 0.6193838034446408.

Running time: 0.8 sec
OOF RMSE: 2.23 | R2: 0.59
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:28:52,096] Trial 12 finished with value: 0.6806882450362322 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 8.838377531142477e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0031136415731477618}. Best is trial 12 with value: 0.6806882450362322.

Running time: 1.2 sec
OOF RMSE: 1.96 | R2: 0.68
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:28:53,718] Trial 13 finished with value: 0.6354328333157584 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'adam', 'alpha': 9.610127346836031e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.002602367525965633}. Best is trial 12 with value: 0.6806882450362322.

Running time: 1.6 sec
OOF RMSE: 2.09 | R2: 0.64
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:28:55,593] Trial 14 finished with value: 0.634467291877006 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.000105391316342388, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0024800429417531225}. Best is trial 12 with value: 0.6806882450362322.

Running time: 1.9 sec
OOF RMSE: 2.10 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:28:56,710] Trial 15 finished with value: 0.6332480311860604 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0001900121797383015, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0021396952842354542}. Best is trial 12 with value: 0.6806882450362322.

Running time: 1.1 sec
OOF RMSE: 2.10 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:28:57,811] Trial 16 finished with value: 0.6412548317848861 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 1.2416608356334141e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0022917516574699286}. Best is trial 12 with value: 0.6806882450362322.

Running time: 1.1 sec
OOF RMSE: 2.08 | R2: 0.64
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3
Fold 4
Fold 5
Running time: 1.4 sec
OOF RMSE: 2.18 | R2: 0.61

[I 2025-07-11 18:28:59,216] Trial 17 finished with value: 0.6056193325052265 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 1.185810136456069e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0019061575680193472}. Best is trial 12 with value: 0.6806882450362322.

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

[I 2025-07-11 18:29:00,379] Trial 18 finished with value: 0.5142099695272961 and parameters: {'hidden_layer_sizes': '50', 'activation': 'relu', 'solver': 'sgd', 'alpha': 3.359203827479439e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0034374716466820813}. Best is trial 12 with value: 0.6806882450362322.

Running time: 1.2 sec
OOF RMSE: 2.42 | R2: 0.51
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3
Fold 4

[I 2025-07-11 18:29:01,634] Trial 19 finished with value: 0.5846188991593608 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'relu', 'solver': 'adam', 'alpha': 3.258751383082392e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0013919230177932133}. Best is trial 12 with value: 0.6806882450362322.

Fold 5
Running time: 1.2 sec
OOF RMSE: 2.23 | R2: 0.58
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:29:02,756] Trial 20 finished with value: 0.7472115571966351 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 1.0688786363815157e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.004048909580686583}. Best is trial 20 with value: 0.7472115571966351.

Running time: 1.1 sec
OOF RMSE: 1.74 | R2: 0.75
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:29:03,919] Trial 21 finished with value: 0.7205507668406823 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 1.0845346608901425e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.003788099322504794}. Best is trial 20 with value: 0.7472115571966351.

Running time: 1.2 sec
OOF RMSE: 1.83 | R2: 0.72
Fold 1
Fold 2
Fold 3

[I 2025-07-11 18:29:05,099] Trial 22 finished with value: 0.732170822517288 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 3.2353640763718344e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.009862345315315069}. Best is trial 20 with value: 0.7472115571966351.

Fold 4
Fold 5
Running time: 1.2 sec
OOF RMSE: 1.79 | R2: 0.73
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:29:06,204] Trial 23 finished with value: 0.7396358374656309 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 2.7733656250553123e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.004314072179921939}. Best is trial 20 with value: 0.7472115571966351.

Running time: 1.1 sec
OOF RMSE: 1.77 | R2: 0.74
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 18:29:07,082] Trial 24 finished with value: 0.7503491551546929 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 3.18996430984702e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.009277103559033694}. Best is trial 24 with value: 0.7503491551546929.
[I 2025-07-11 18:29:07,083] A new study created in memory with name: no-name-961e972f-dc09-43c4-b042-f3ceba2df480
[I 2025-07-11 18:29:07,175] Trial 0 finished with value: -235.74758970581436 and parameters: {'kernel': 'sigmoid', 'C': 9.757877336937888, 'epsilon': 0.16018881015174213, 'gamma': 'scale'}. Best is trial 0 with value: -235.74758970581436.

Fold 5
Running time: 0.9 sec
OOF RMSE: 1.73 | R2: 0.75

✅ MLP - Mejor R2: 0.75
📋 Parámetros: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 3.18996430984702e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.009277103559033694}

Buscando mejores hiperparámetros para SVR...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 53.34 | R2: -235.75
Fold 1
Fold 2

[I 2025-07-11 18:29:07,243] Trial 1 finished with value: 0.15801831011049905 and parameters: {'kernel': 'rbf', 'C': 0.33257056758217723, 'epsilon': 0.10646467428735829, 'gamma': 'scale'}. Best is trial 1 with value: 0.15801831011049905.
[I 2025-07-11 18:29:07,320] Trial 2 finished with value: 0.5775084888070017 and parameters: {'kernel': 'rbf', 'C': 8.677830006533478, 'epsilon': 0.18622082090111314, 'gamma': 'scale'}. Best is trial 2 with value: 0.5775084888070017.
[I 2025-07-11 18:29:07,392] Trial 3 finished with value: 0.5380906366337252 and parameters: {'kernel': 'rbf', 'C': 9.335776068067407, 'epsilon': 0.11020087799579772, 'gamma': 'auto'}. Best is trial 2 with value: 0.5775084888070017.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.18 | R2: 0.16
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.25 | R2: 0.58
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.36 | R2: 0.54
Fold 1
Fold 2

[I 2025-07-11 18:29:07,460] Trial 4 finished with value: 0.36144286866703645 and parameters: {'kernel': 'rbf', 'C': 2.2555650736861685, 'epsilon': 0.15531173055512212, 'gamma': 'auto'}. Best is trial 2 with value: 0.5775084888070017.
[I 2025-07-11 18:29:07,527] Trial 5 finished with value: 0.11883036831390159 and parameters: {'kernel': 'rbf', 'C': 0.20701990177411997, 'epsilon': 0.13363540994434642, 'gamma': 'auto'}. Best is trial 2 with value: 0.5775084888070017.
[I 2025-07-11 18:29:07,594] Trial 6 finished with value: 0.02055479206224009 and parameters: {'kernel': 'sigmoid', 'C': 0.5281153618066443, 'epsilon': 0.14765658336099136, 'gamma': 'auto'}. Best is trial 2 with value: 0.5775084888070017.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.77 | R2: 0.36
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.25 | R2: 0.12
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.43 | R2: 0.02
Fold 1
Fold 2
Fold 3

[I 2025-07-11 18:29:07,662] Trial 7 finished with value: 0.0701951646578367 and parameters: {'kernel': 'rbf', 'C': 0.10378818116225633, 'epsilon': 0.18650936684552963, 'gamma': 'auto'}. Best is trial 2 with value: 0.5775084888070017.
[I 2025-07-11 18:29:07,752] Trial 8 finished with value: 0.09585317697058715 and parameters: {'kernel': 'rbf', 'C': 0.17736480000453925, 'epsilon': 0.11849591457139258, 'gamma': 'scale'}. Best is trial 2 with value: 0.5775084888070017.
[I 2025-07-11 18:29:07,827] Trial 9 finished with value: -2.250666688718038 and parameters: {'kernel': 'sigmoid', 'C': 1.60576912610483, 'epsilon': 0.1489307582177334, 'gamma': 'auto'}. Best is trial 2 with value: 0.5775084888070017.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.34 | R2: 0.07
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.30 | R2: 0.10
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 6.25 | R2: -2.25

[I 2025-07-11 18:29:07,908] Trial 10 finished with value: -34.47879218833938 and parameters: {'kernel': 'sigmoid', 'C': 3.559978481117139, 'epsilon': 0.05083885288407758, 'gamma': 'scale'}. Best is trial 2 with value: 0.5775084888070017.
[I 2025-07-11 18:29:07,992] Trial 11 finished with value: 0.585613093378681 and parameters: {'kernel': 'rbf', 'C': 9.707856822608347, 'epsilon': 0.06611906872387131, 'gamma': 'scale'}. Best is trial 11 with value: 0.585613093378681.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 20.65 | R2: -34.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.23 | R2: 0.59
Fold 1
Fold 2
Fold 3

[I 2025-07-11 18:29:08,069] Trial 12 finished with value: 0.4854936156151576 and parameters: {'kernel': 'rbf', 'C': 4.641477618943842, 'epsilon': 0.058483878079122975, 'gamma': 'scale'}. Best is trial 11 with value: 0.585613093378681.
[I 2025-07-11 18:29:08,159] Trial 13 finished with value: 0.4984699735702455 and parameters: {'kernel': 'rbf', 'C': 5.016825517876218, 'epsilon': 0.03442081401064913, 'gamma': 'scale'}. Best is trial 11 with value: 0.585613093378681.
[I 2025-07-11 18:29:08,234] Trial 14 finished with value: 0.27298933111370804 and parameters: {'kernel': 'rbf', 'C': 0.9231915822902246, 'epsilon': 0.07671273536240078, 'gamma': 'scale'}. Best is trial 11 with value: 0.585613093378681.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.49 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.45 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.96 | R2: 0.27
Fold 1

[I 2025-07-11 18:29:08,316] Trial 15 finished with value: 0.5275288888640941 and parameters: {'kernel': 'rbf', 'C': 5.925700748262925, 'epsilon': 0.010497923633958434, 'gamma': 'scale'}. Best is trial 11 with value: 0.585613093378681.
[I 2025-07-11 18:29:08,401] Trial 16 finished with value: 0.3751604379764787 and parameters: {'kernel': 'rbf', 'C': 2.334734022340272, 'epsilon': 0.08183031254800767, 'gamma': 'scale'}. Best is trial 11 with value: 0.585613093378681.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.38 | R2: 0.53
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.74 | R2: 0.38
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 18:29:08,479] Trial 17 finished with value: 0.2675346855995395 and parameters: {'kernel': 'rbf', 'C': 0.8750307811411495, 'epsilon': 0.19138560983605862, 'gamma': 'scale'}. Best is trial 11 with value: 0.585613093378681.
[I 2025-07-11 18:29:08,563] Trial 18 finished with value: -127.51266604487995 and parameters: {'kernel': 'sigmoid', 'C': 7.1219452015825935, 'epsilon': 0.07640551738283594, 'gamma': 'scale'}. Best is trial 11 with value: 0.585613093378681.
[I 2025-07-11 18:29:08,635] Trial 19 finished with value: 0.41110412253070694 and parameters: {'kernel': 'rbf', 'C': 2.9090004867780657, 'epsilon': 0.17430616845203853, 'gamma': 'scale'}. Best is trial 11 with value: 0.585613093378681.

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.97 | R2: 0.27
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 39.30 | R2: -127.51
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.66 | R2: 0.41
Fold 1
Fold 2

[I 2025-07-11 18:29:08,710] Trial 20 finished with value: 0.3331642839000212 and parameters: {'kernel': 'rbf', 'C': 1.610922378702581, 'epsilon': 0.09312494008872249, 'gamma': 'scale'}. Best is trial 11 with value: 0.585613093378681.
[I 2025-07-11 18:29:08,793] Trial 21 finished with value: 0.5250853743234773 and parameters: {'kernel': 'rbf', 'C': 7.966880289713503, 'epsilon': 0.11347226576785097, 'gamma': 'auto'}. Best is trial 11 with value: 0.585613093378681.
[I 2025-07-11 18:29:08,869] Trial 22 finished with value: 0.5408877149050582 and parameters: {'kernel': 'rbf', 'C': 9.659989458610989, 'epsilon': 0.051605955239723306, 'gamma': 'auto'}. Best is trial 11 with value: 0.585613093378681.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.83 | R2: 0.33
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.39 | R2: 0.53
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.35 | R2: 0.54

[I 2025-07-11 18:29:08,949] Trial 23 finished with value: 0.44689478261428117 and parameters: {'kernel': 'rbf', 'C': 4.267661806559581, 'epsilon': 0.04222822559434129, 'gamma': 'auto'}. Best is trial 11 with value: 0.585613093378681.
[I 2025-07-11 18:29:09,040] Trial 24 finished with value: 0.5102995798694919 and parameters: {'kernel': 'rbf', 'C': 6.649836830300007, 'epsilon': 0.019053582765798986, 'gamma': 'auto'}. Best is trial 11 with value: 0.585613093378681.
[I 2025-07-11 18:29:09,041] A new study created in memory with name: no-name-274487b7-16c2-443a-a8c1-633a07abee8b

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.58 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.43 | R2: 0.51

✅ SVR - Mejor R2: 0.59
📋 Parámetros: {'kernel': 'rbf', 'C': 9.707856822608347, 'epsilon': 0.06611906872387131, 'gamma': 'scale'}

Buscando mejores hiperparámetros para KNN...
Fold 1
Fold 2
Fold 3

[I 2025-07-11 18:29:09,109] Trial 0 finished with value: 0.6897029715606237 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'leaf_size': 23}. Best is trial 0 with value: 0.6897029715606237.
[I 2025-07-11 18:29:09,173] Trial 1 finished with value: 0.6302505414161335 and parameters: {'n_neighbors': 15, 'weights': 'distance', 'leaf_size': 25}. Best is trial 0 with value: 0.6897029715606237.
[I 2025-07-11 18:29:09,234] Trial 2 finished with value: 0.6302505414161335 and parameters: {'n_neighbors': 15, 'weights': 'distance', 'leaf_size': 30}. Best is trial 0 with value: 0.6897029715606237.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.93 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.11 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.11 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:29:09,294] Trial 3 finished with value: 0.6745888401085188 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'leaf_size': 16}. Best is trial 0 with value: 0.6897029715606237.
[I 2025-07-11 18:29:09,357] Trial 4 finished with value: 0.6466188476482639 and parameters: {'n_neighbors': 12, 'weights': 'distance', 'leaf_size': 39}. Best is trial 0 with value: 0.6897029715606237.
[I 2025-07-11 18:29:09,417] Trial 5 finished with value: 0.6897029715606237 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'leaf_size': 32}. Best is trial 0 with value: 0.6897029715606237.
[I 2025-07-11 18:29:09,473] Trial 6 finished with value: 0.6897029715606237 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'leaf_size': 11}. Best is trial 0 with value: 0.6897029715606237.

Running time: 0.1 sec
OOF RMSE: 1.98 | R2: 0.67
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.06 | R2: 0.65
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.93 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.93 | R2: 0.69
Fold 1
Fold 2

[I 2025-07-11 18:29:09,533] Trial 7 finished with value: 0.51880267229446 and parameters: {'n_neighbors': 15, 'weights': 'uniform', 'leaf_size': 23}. Best is trial 0 with value: 0.6897029715606237.
[I 2025-07-11 18:29:09,597] Trial 8 finished with value: 0.7196444956073751 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 35}. Best is trial 8 with value: 0.7196444956073751.
[I 2025-07-11 18:29:09,655] Trial 9 finished with value: 0.6567818749427776 and parameters: {'n_neighbors': 9, 'weights': 'distance', 'leaf_size': 22}. Best is trial 8 with value: 0.7196444956073751.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.40 | R2: 0.52
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.84 | R2: 0.72
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.03 | R2: 0.66
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 18:29:09,719] Trial 10 finished with value: 0.6758835073536573 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'leaf_size': 40}. Best is trial 8 with value: 0.7196444956073751.
[I 2025-07-11 18:29:09,795] Trial 11 finished with value: 0.6758835073536573 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'leaf_size': 32}. Best is trial 8 with value: 0.7196444956073751.
[I 2025-07-11 18:29:09,906] Trial 12 finished with value: 0.6901300964771395 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'leaf_size': 18}. Best is trial 8 with value: 0.7196444956073751.

Fold 5
Running time: 0.1 sec
OOF RMSE: 1.97 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.97 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.93 | R2: 0.69

[I 2025-07-11 18:29:09,982] Trial 13 finished with value: 0.6564151487269154 and parameters: {'n_neighbors': 8, 'weights': 'distance', 'leaf_size': 16}. Best is trial 8 with value: 0.7196444956073751.
[I 2025-07-11 18:29:10,051] Trial 14 finished with value: 0.5757313874387437 and parameters: {'n_neighbors': 6, 'weights': 'uniform', 'leaf_size': 16}. Best is trial 8 with value: 0.7196444956073751.
[I 2025-07-11 18:29:10,113] Trial 15 finished with value: 0.7196444956073751 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 36}. Best is trial 8 with value: 0.7196444956073751.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.03 | R2: 0.66
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.26 | R2: 0.58
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.84 | R2: 0.72

[I 2025-07-11 18:29:10,182] Trial 16 finished with value: 0.6353502193377383 and parameters: {'n_neighbors': 11, 'weights': 'distance', 'leaf_size': 37}. Best is trial 8 with value: 0.7196444956073751.
[I 2025-07-11 18:29:10,253] Trial 17 finished with value: 0.7196444956073751 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 35}. Best is trial 8 with value: 0.7196444956073751.
[I 2025-07-11 18:29:10,320] Trial 18 finished with value: 0.5078838039121569 and parameters: {'n_neighbors': 11, 'weights': 'uniform', 'leaf_size': 28}. Best is trial 8 with value: 0.7196444956073751.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.09 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.84 | R2: 0.72
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.43 | R2: 0.51

[I 2025-07-11 18:29:10,391] Trial 19 finished with value: 0.7093449676636573 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'leaf_size': 35}. Best is trial 8 with value: 0.7196444956073751.
[I 2025-07-11 18:29:10,460] Trial 20 finished with value: 0.6745888401085188 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'leaf_size': 27}. Best is trial 8 with value: 0.7196444956073751.
[I 2025-07-11 18:29:10,523] Trial 21 finished with value: 0.7196444956073751 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 35}. Best is trial 8 with value: 0.7196444956073751.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.87 | R2: 0.71
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.98 | R2: 0.67
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.84 | R2: 0.72
Fold 1

[I 2025-07-11 18:29:10,590] Trial 22 finished with value: 0.7093449676636573 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'leaf_size': 35}. Best is trial 8 with value: 0.7196444956073751.
[I 2025-07-11 18:29:10,692] Trial 23 finished with value: 0.7093449676636573 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'leaf_size': 32}. Best is trial 8 with value: 0.7196444956073751.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.87 | R2: 0.71
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.87 | R2: 0.71
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 18:29:10,763] Trial 24 finished with value: 0.7196444956073751 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 38}. Best is trial 8 with value: 0.7196444956073751.
[I 2025-07-11 18:29:10,764] A new study created in memory with name: no-name-85cbe6cf-16ba-4b37-af34-4d2efb1c747a
[I 2025-07-11 18:29:10,825] Trial 0 finished with value: 0.493575692432383 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 0 with value: 0.493575692432383.
[I 2025-07-11 18:29:10,919] Trial 1 finished with value: 0.42318765604448305 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 0 with value: 0.493575692432383.

Fold 5
Running time: 0.1 sec
OOF RMSE: 1.84 | R2: 0.72

✅ KNN - Mejor R2: 0.72
📋 Parámetros: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 35}

Buscando mejores hiperparámetros para LR...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.47 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.63 | R2: 0.42
Fold 1
Fold 2
Fold 3

[I 2025-07-11 18:29:10,993] Trial 2 finished with value: 0.49357569243238664 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 2 with value: 0.49357569243238664.
[I 2025-07-11 18:29:11,067] Trial 3 finished with value: 0.4231876560431088 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 2 with value: 0.49357569243238664.
[I 2025-07-11 18:29:11,142] Trial 4 finished with value: 0.493575692432383 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 2 with value: 0.49357569243238664.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.47 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.63 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.47 | R2: 0.49
Fold 1
Fold 2
Fold 3

[I 2025-07-11 18:29:11,201] Trial 5 finished with value: 0.49357569243238664 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 2 with value: 0.49357569243238664.
[I 2025-07-11 18:29:11,262] Trial 6 finished with value: 0.493575692432383 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 2 with value: 0.49357569243238664.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.47 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.47 | R2: 0.49
Fold 1
Fold 2
Fold 3

[I 2025-07-11 18:29:11,434] Trial 7 finished with value: 0.4231876560431088 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 2 with value: 0.49357569243238664.
[I 2025-07-11 18:29:11,513] Trial 8 finished with value: 0.493575692432383 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 2 with value: 0.49357569243238664.

Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 2.63 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.47 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.63 | R2: 0.42

[I 2025-07-11 18:29:11,588] Trial 9 finished with value: 0.4231876560431088 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 2 with value: 0.49357569243238664.
[I 2025-07-11 18:29:11,677] Trial 10 finished with value: 0.49357569243238664 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 2 with value: 0.49357569243238664.
[I 2025-07-11 18:29:11,735] Trial 11 finished with value: 0.49357569243238664 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 2 with value: 0.49357569243238664.
[I 2025-07-11 18:29:11,791] Trial 12 finished with value: 0.49357569243238664 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 2 with value: 0.49357569243238664.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.47 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.47 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.47 | R2: 0.49
Fold 1

[I 2025-07-11 18:29:11,852] Trial 13 finished with value: 0.49357569243238664 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 2 with value: 0.49357569243238664.
[I 2025-07-11 18:29:11,913] Trial 14 finished with value: 0.49357569243238664 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 2 with value: 0.49357569243238664.
[I 2025-07-11 18:29:11,970] Trial 15 finished with value: 0.49357569243238664 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 2 with value: 0.49357569243238664.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.47 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.47 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.47 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 18:29:12,028] Trial 16 finished with value: 0.49357569243238664 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 2 with value: 0.49357569243238664.
[I 2025-07-11 18:29:12,090] Trial 17 finished with value: 0.49357569243238664 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 2 with value: 0.49357569243238664.
[I 2025-07-11 18:29:12,166] Trial 18 finished with value: 0.42318765604448305 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 2 with value: 0.49357569243238664.

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.47 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.47 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.63 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 18:29:12,240] Trial 19 finished with value: 0.49357569243238664 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 2 with value: 0.49357569243238664.
[I 2025-07-11 18:29:12,301] Trial 20 finished with value: 0.49357569243238664 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 2 with value: 0.49357569243238664.
[I 2025-07-11 18:29:12,363] Trial 21 finished with value: 0.49357569243238664 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 2 with value: 0.49357569243238664.
[I 2025-07-11 18:29:12,419] Trial 22 finished with value: 0.49357569243238664 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 2 with value: 0.49357569243238664.

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.47 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.47 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.47 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.47 | R2: 0.49
Fold 1

[I 2025-07-11 18:29:12,489] Trial 23 finished with value: 0.49357569243238664 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 2 with value: 0.49357569243238664.
[I 2025-07-11 18:29:12,553] Trial 24 finished with value: 0.49357569243238664 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 2 with value: 0.49357569243238664.
[I 2025-07-11 18:29:12,554] A new study created in memory with name: no-name-c05311ca-5058-4ec7-9940-67ab1522885d

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.47 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.47 | R2: 0.49

✅ LR - Mejor R2: 0.49
📋 Parámetros: {'fit_intercept': True, 'positive': True}

Buscando mejores hiperparámetros para RF...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:29:18,929] Trial 0 finished with value: 0.4295695473678265 and parameters: {'n_estimators': 300, 'max_depth': 7, 'min_samples_split': 2, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 0 with value: 0.4295695473678265.

Running time: 6.4 sec
OOF RMSE: 2.62 | R2: 0.43
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:29:21,102] Trial 1 finished with value: 0.3277103916955202 and parameters: {'n_estimators': 100, 'max_depth': 8, 'min_samples_split': 4, 'min_samples_leaf': 4, 'bootstrap': False}. Best is trial 0 with value: 0.4295695473678265.

Running time: 2.2 sec
OOF RMSE: 2.84 | R2: 0.33
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:29:22,310] Trial 2 finished with value: 0.5082350172357222 and parameters: {'n_estimators': 100, 'max_depth': 5, 'min_samples_split': 3, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 2 with value: 0.5082350172357222.

Running time: 1.2 sec
OOF RMSE: 2.43 | R2: 0.51
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:29:33,047] Trial 3 finished with value: 0.3459985465330989 and parameters: {'n_estimators': 500, 'max_depth': 13, 'min_samples_split': 7, 'min_samples_leaf': 5, 'bootstrap': False}. Best is trial 2 with value: 0.5082350172357222.

Running time: 10.7 sec
OOF RMSE: 2.80 | R2: 0.35
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:29:35,451] Trial 4 finished with value: 0.4366957323485061 and parameters: {'n_estimators': 100, 'max_depth': 12, 'min_samples_split': 3, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 2 with value: 0.5082350172357222.

Running time: 2.4 sec
OOF RMSE: 2.60 | R2: 0.44
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:29:48,372] Trial 5 finished with value: 0.4346753406343027 and parameters: {'n_estimators': 500, 'max_depth': 11, 'min_samples_split': 3, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 2 with value: 0.5082350172357222.

Running time: 12.9 sec
OOF RMSE: 2.61 | R2: 0.43
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:29:49,792] Trial 6 finished with value: 0.5076150605521417 and parameters: {'n_estimators': 100, 'max_depth': 10, 'min_samples_split': 8, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 2 with value: 0.5082350172357222.

Running time: 1.4 sec
OOF RMSE: 2.43 | R2: 0.51
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:29:54,255] Trial 7 finished with value: 0.506789140586998 and parameters: {'n_estimators': 300, 'max_depth': 12, 'min_samples_split': 2, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 2 with value: 0.5082350172357222.

Running time: 4.5 sec
OOF RMSE: 2.43 | R2: 0.51
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:29:56,855] Trial 8 finished with value: 0.4452470611212538 and parameters: {'n_estimators': 100, 'max_depth': 14, 'min_samples_split': 5, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 2 with value: 0.5082350172357222.

Running time: 2.6 sec
OOF RMSE: 2.58 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:30:01,176] Trial 9 finished with value: 0.5053853888833194 and parameters: {'n_estimators': 300, 'max_depth': 9, 'min_samples_split': 10, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 2 with value: 0.5082350172357222.

Running time: 4.3 sec
OOF RMSE: 2.44 | R2: 0.51
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:30:02,499] Trial 10 finished with value: 0.5417576661883015 and parameters: {'n_estimators': 100, 'max_depth': 5, 'min_samples_split': 6, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 10 with value: 0.5417576661883015.

Running time: 1.3 sec
OOF RMSE: 2.35 | R2: 0.54
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:30:03,796] Trial 11 finished with value: 0.5417576661883015 and parameters: {'n_estimators': 100, 'max_depth': 5, 'min_samples_split': 6, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 10 with value: 0.5417576661883015.

Running time: 1.3 sec
OOF RMSE: 2.35 | R2: 0.54
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:30:05,242] Trial 12 finished with value: 0.5467426542070053 and parameters: {'n_estimators': 100, 'max_depth': 6, 'min_samples_split': 6, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 12 with value: 0.5467426542070053.

Running time: 1.4 sec
OOF RMSE: 2.33 | R2: 0.55
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:30:06,687] Trial 13 finished with value: 0.5378023128300584 and parameters: {'n_estimators': 100, 'max_depth': 6, 'min_samples_split': 8, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 12 with value: 0.5467426542070053.

Running time: 1.4 sec
OOF RMSE: 2.36 | R2: 0.54
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:30:08,273] Trial 14 finished with value: 0.5412338222734234 and parameters: {'n_estimators': 100, 'max_depth': 7, 'min_samples_split': 6, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 12 with value: 0.5467426542070053.

Running time: 1.6 sec
OOF RMSE: 2.35 | R2: 0.54
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:30:14,647] Trial 15 finished with value: 0.5476156557354492 and parameters: {'n_estimators': 500, 'max_depth': 5, 'min_samples_split': 5, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 15 with value: 0.5476156557354492.

Running time: 6.4 sec
OOF RMSE: 2.33 | R2: 0.55
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:30:22,276] Trial 16 finished with value: 0.5496167563357429 and parameters: {'n_estimators': 500, 'max_depth': 7, 'min_samples_split': 5, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 16 with value: 0.5496167563357429.

Running time: 7.6 sec
OOF RMSE: 2.33 | R2: 0.55
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:30:30,418] Trial 17 finished with value: 0.5523499034608568 and parameters: {'n_estimators': 500, 'max_depth': 8, 'min_samples_split': 4, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 17 with value: 0.5523499034608568.

Running time: 8.1 sec
OOF RMSE: 2.32 | R2: 0.55
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:30:38,849] Trial 18 finished with value: 0.5521316762246304 and parameters: {'n_estimators': 500, 'max_depth': 9, 'min_samples_split': 4, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 17 with value: 0.5523499034608568.

Running time: 8.4 sec
OOF RMSE: 2.32 | R2: 0.55
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:30:46,744] Trial 19 finished with value: 0.5283355627813461 and parameters: {'n_estimators': 500, 'max_depth': 9, 'min_samples_split': 4, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 17 with value: 0.5523499034608568.

Running time: 7.9 sec
OOF RMSE: 2.38 | R2: 0.53
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:30:54,735] Trial 20 finished with value: 0.5264255911939575 and parameters: {'n_estimators': 500, 'max_depth': 10, 'min_samples_split': 4, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 17 with value: 0.5523499034608568.

Running time: 8.0 sec
OOF RMSE: 2.39 | R2: 0.53
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:31:02,759] Trial 21 finished with value: 0.5514237492568312 and parameters: {'n_estimators': 500, 'max_depth': 8, 'min_samples_split': 5, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 17 with value: 0.5523499034608568.

Running time: 8.0 sec
OOF RMSE: 2.32 | R2: 0.55
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:31:11,203] Trial 22 finished with value: 0.5521316762246304 and parameters: {'n_estimators': 500, 'max_depth': 9, 'min_samples_split': 4, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 17 with value: 0.5523499034608568.

Running time: 8.4 sec
OOF RMSE: 2.32 | R2: 0.55
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:31:19,600] Trial 23 finished with value: 0.5521316762246304 and parameters: {'n_estimators': 500, 'max_depth': 9, 'min_samples_split': 4, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 17 with value: 0.5523499034608568.

Running time: 8.4 sec
OOF RMSE: 2.32 | R2: 0.55
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:31:28,343] Trial 24 finished with value: 0.5564891278266509 and parameters: {'n_estimators': 500, 'max_depth': 11, 'min_samples_split': 3, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 24 with value: 0.5564891278266509.
[I 2025-07-11 18:31:28,344] A new study created in memory with name: no-name-f7a8b12a-8b1e-4f64-a851-0a6d8afc7cc8

Running time: 8.7 sec
OOF RMSE: 2.31 | R2: 0.56

✅ RF - Mejor R2: 0.56
📋 Parámetros: {'n_estimators': 500, 'max_depth': 11, 'min_samples_split': 3, 'min_samples_leaf': 2, 'bootstrap': True}

Buscando mejores hiperparámetros para CAT...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:31:42,012] Trial 0 finished with value: 0.6888216645759251 and parameters: {'iterations': 1000, 'learning_rate': 0.030043589048351204, 'depth': 7, 'l2_leaf_reg': 2.3461040953541774}. Best is trial 0 with value: 0.6888216645759251.

Running time: 13.7 sec
OOF RMSE: 1.93 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:31:46,377] Trial 1 finished with value: 0.6564489395926969 and parameters: {'iterations': 1000, 'learning_rate': 0.07470718506860981, 'depth': 5, 'l2_leaf_reg': 8.850368992890171}. Best is trial 0 with value: 0.6888216645759251.

Running time: 4.4 sec
OOF RMSE: 2.03 | R2: 0.66
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:32:04,374] Trial 2 finished with value: 0.6682167647343089 and parameters: {'iterations': 500, 'learning_rate': 0.023490672266885743, 'depth': 8, 'l2_leaf_reg': 5.1187035426087455}. Best is trial 0 with value: 0.6888216645759251.

Running time: 18.0 sec
OOF RMSE: 2.00 | R2: 0.67
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:34:51,384] Trial 3 finished with value: 0.6916893825189164 and parameters: {'iterations': 2000, 'learning_rate': 0.03207314722798549, 'depth': 9, 'l2_leaf_reg': 1.7042105307530986}. Best is trial 3 with value: 0.6916893825189164.

Running time: 167.0 sec
OOF RMSE: 1.92 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:36:14,723] Trial 4 finished with value: 0.6815792301800416 and parameters: {'iterations': 1000, 'learning_rate': 0.09258171772035313, 'depth': 9, 'l2_leaf_reg': 5.127480227803666}. Best is trial 3 with value: 0.6916893825189164.

Running time: 83.3 sec
OOF RMSE: 1.96 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:36:17,991] Trial 5 finished with value: 0.693719799432472 and parameters: {'iterations': 500, 'learning_rate': 0.06327209998330206, 'depth': 6, 'l2_leaf_reg': 3.6397060388397873}. Best is trial 5 with value: 0.693719799432472.

Running time: 3.3 sec
OOF RMSE: 1.92 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:36:31,349] Trial 6 finished with value: 0.6473478032753722 and parameters: {'iterations': 2000, 'learning_rate': 0.09574967113185075, 'depth': 6, 'l2_leaf_reg': 8.668943452985104}. Best is trial 5 with value: 0.693719799432472.

Running time: 13.4 sec
OOF RMSE: 2.06 | R2: 0.65
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:36:37,966] Trial 7 finished with value: 0.6929439849253086 and parameters: {'iterations': 1000, 'learning_rate': 0.016872804102893126, 'depth': 6, 'l2_leaf_reg': 3.8013343163971456}. Best is trial 5 with value: 0.693719799432472.

Running time: 6.6 sec
OOF RMSE: 1.92 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:36:56,267] Trial 8 finished with value: 0.6676080927927085 and parameters: {'iterations': 500, 'learning_rate': 0.04289836819489309, 'depth': 8, 'l2_leaf_reg': 4.117636989829659}. Best is trial 5 with value: 0.693719799432472.

Running time: 18.3 sec
OOF RMSE: 2.00 | R2: 0.67
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:38:08,812] Trial 9 finished with value: 0.6992421066459573 and parameters: {'iterations': 500, 'learning_rate': 0.04326932428977199, 'depth': 10, 'l2_leaf_reg': 2.2210886683791333}. Best is trial 9 with value: 0.6992421066459573.

Running time: 72.5 sec
OOF RMSE: 1.90 | R2: 0.70
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:39:19,612] Trial 10 finished with value: 0.6139221403034176 and parameters: {'iterations': 500, 'learning_rate': 0.010274347781151908, 'depth': 10, 'l2_leaf_reg': 6.7357468944471}. Best is trial 9 with value: 0.6992421066459573.

Running time: 70.8 sec
OOF RMSE: 2.15 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:39:21,115] Trial 11 finished with value: 0.6597731842695367 and parameters: {'iterations': 500, 'learning_rate': 0.052565513813127795, 'depth': 4, 'l2_leaf_reg': 1.1079654767071792}. Best is trial 9 with value: 0.6992421066459573.

Running time: 1.5 sec
OOF RMSE: 2.02 | R2: 0.66
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:39:24,478] Trial 12 finished with value: 0.6915301011952386 and parameters: {'iterations': 500, 'learning_rate': 0.05602601007805964, 'depth': 6, 'l2_leaf_reg': 3.0232146615410094}. Best is trial 9 with value: 0.6992421066459573.

Running time: 3.4 sec
OOF RMSE: 1.93 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:40:35,964] Trial 13 finished with value: 0.6615082004365463 and parameters: {'iterations': 500, 'learning_rate': 0.058623564537712745, 'depth': 10, 'l2_leaf_reg': 6.404363702925107}. Best is trial 9 with value: 0.6992421066459573.

Running time: 71.5 sec
OOF RMSE: 2.02 | R2: 0.66
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:40:37,581] Trial 14 finished with value: 0.6899357237490452 and parameters: {'iterations': 500, 'learning_rate': 0.041420888804117484, 'depth': 4, 'l2_leaf_reg': 3.3854086357527446}. Best is trial 9 with value: 0.6992421066459573.

Running time: 1.6 sec
OOF RMSE: 1.93 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:40:44,857] Trial 15 finished with value: 0.7045022516720421 and parameters: {'iterations': 500, 'learning_rate': 0.07150965747913517, 'depth': 7, 'l2_leaf_reg': 2.379370305138668}. Best is trial 15 with value: 0.7045022516720421.

Running time: 7.3 sec
OOF RMSE: 1.88 | R2: 0.70
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:41:57,097] Trial 16 finished with value: 0.6868533133850947 and parameters: {'iterations': 2000, 'learning_rate': 0.04045142870646015, 'depth': 8, 'l2_leaf_reg': 2.1676322662422476}. Best is trial 15 with value: 0.7045022516720421.
[I 2025-07-11 18:41:57,098] A new study created in memory with name: no-name-974dbbe1-96d1-424e-9ad7-38fa3c446032
[I 2025-07-11 18:41:57,179] Trial 0 finished with value: 0.49092408839636636 and parameters: {'alpha': 0.28845319877717823, 'l1_ratio': 0.5993044970668177}. Best is trial 0 with value: 0.49092408839636636.

Running time: 72.2 sec
OOF RMSE: 1.94 | R2: 0.69

✅ CAT - Mejor R2: 0.70
📋 Parámetros: {'iterations': 500, 'learning_rate': 0.07150965747913517, 'depth': 7, 'l2_leaf_reg': 2.379370305138668}

Buscando mejores hiperparámetros para EN...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.47 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.765e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.369e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.511e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.896e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.262e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 18:41:57,299] Trial 1 finished with value: 0.5330370256387438 and parameters: {'alpha': 0.0011078857280934454, 'l1_ratio': 0.21498307555419094}. Best is trial 1 with value: 0.5330370256387438.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.422e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.166e+01, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.983e+01, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.117e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.316e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 18:41:57,415] Trial 2 finished with value: 0.5445438002348981 and parameters: {'alpha': 0.001968900211844185, 'l1_ratio': 0.49487351560594595}. Best is trial 2 with value: 0.5445438002348981.

Running time: 0.1 sec
OOF RMSE: 2.37 | R2: 0.53
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.34 | R2: 0.54
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.771e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.048e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.857e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.410e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.597e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 18:41:57,535] Trial 3 finished with value: 0.48630535623073745 and parameters: {'alpha': 0.0001919215301041575, 'l1_ratio': 0.9903404678203829}. Best is trial 2 with value: 0.5445438002348981.
[I 2025-07-11 18:41:57,620] Trial 4 finished with value: 0.3866470765598956 and parameters: {'alpha': 3.3671132813688027, 'l1_ratio': 0.07387733943632857}. Best is trial 2 with value: 0.5445438002348981.
[I 2025-07-11 18:41:57,711] Trial 5 finished with value: -0.00027817151752640434 and parameters: {'alpha': 7.786566637651128, 'l1_ratio': 0.3734989699046174}. Best is trial 2 with value: 0.5445438002348981.

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.48 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.71 | R2: 0.39
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.47 | R2: -0.00

[I 2025-07-11 18:41:57,793] Trial 6 finished with value: 0.369226079296624 and parameters: {'alpha': 1.4297690118494994, 'l1_ratio': 0.4594708440961265}. Best is trial 2 with value: 0.5445438002348981.
[I 2025-07-11 18:41:57,892] Trial 7 finished with value: 0.43036058524811094 and parameters: {'alpha': 0.8800395034358568, 'l1_ratio': 0.47537553604665705}. Best is trial 2 with value: 0.5445438002348981.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.75 | R2: 0.37
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.62 | R2: 0.43
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.237e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.368e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.301e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.819e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.095e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 18:41:58,032] Trial 8 finished with value: 0.4981300646040764 and parameters: {'alpha': 0.00022230318367047401, 'l1_ratio': 0.15703361655494885}. Best is trial 2 with value: 0.5445438002348981.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.930e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.938e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.950e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.46 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.425e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.865e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 18:41:58,166] Trial 9 finished with value: 0.5730722350148179 and parameters: {'alpha': 0.01732205816566096, 'l1_ratio': 0.0008665474901536907}. Best is trial 9 with value: 0.5730722350148179.

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.27 | R2: 0.57
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:41:58,348] Trial 10 finished with value: 0.5640217059892778 and parameters: {'alpha': 0.05154205932795767, 'l1_ratio': 0.7564821156324012}. Best is trial 9 with value: 0.5730722350148179.
[I 2025-07-11 18:41:58,476] Trial 11 finished with value: 0.5595301436693105 and parameters: {'alpha': 0.06330257946040689, 'l1_ratio': 0.754444472952492}. Best is trial 9 with value: 0.5730722350148179.

Running time: 0.2 sec
OOF RMSE: 2.29 | R2: 0.56
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.30 | R2: 0.56
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.488e-01, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.483e-01, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 18:41:58,636] Trial 12 finished with value: 0.5740799102262502 and parameters: {'alpha': 0.014068334189618923, 'l1_ratio': 0.8007157782085097}. Best is trial 12 with value: 0.5740799102262502.

Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 2.26 | R2: 0.57
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.641e-01, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.219e+00, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.848e+00, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.216e-01, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.062e+00, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 18:41:58,800] Trial 13 finished with value: 0.5654326332281987 and parameters: {'alpha': 0.00851074112626676, 'l1_ratio': 0.9852029090609293}. Best is trial 12 with value: 0.5740799102262502.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.017e+00, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.463e+00, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.344e+00, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.613e+00, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.695e+00, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 18:41:58,931] Trial 14 finished with value: 0.5705873350461033 and parameters: {'alpha': 0.009768266003591895, 'l1_ratio': 0.7445345413976788}. Best is trial 12 with value: 0.5740799102262502.

Running time: 0.1 sec
OOF RMSE: 2.29 | R2: 0.57
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.27 | R2: 0.57
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.683e+01, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.802e+01, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.960e+01, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.613e+01, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.035e+01, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 18:41:59,063] Trial 15 finished with value: 0.5727777818959487 and parameters: {'alpha': 0.012717323976342803, 'l1_ratio': 0.28734821420103007}. Best is trial 12 with value: 0.5740799102262502.
[I 2025-07-11 18:41:59,208] Trial 16 finished with value: 0.5442765513873635 and parameters: {'alpha': 0.18513510564322624, 'l1_ratio': 0.014786380390377796}. Best is trial 12 with value: 0.5740799102262502.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.27 | R2: 0.57
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.34 | R2: 0.54

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.165e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.990e+01, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.574e+01, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.855e+01, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.192e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 18:41:59,344] Trial 17 finished with value: 0.5395180417709081 and parameters: {'alpha': 0.0019453233785864683, 'l1_ratio': 0.6369162031128762}. Best is trial 12 with value: 0.5740799102262502.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.35 | R2: 0.54
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:41:59,451] Trial 18 finished with value: 0.516632448689096 and parameters: {'alpha': 0.14120382041821328, 'l1_ratio': 0.864039589388476}. Best is trial 12 with value: 0.5740799102262502.
[I 2025-07-11 18:41:59,585] Trial 19 finished with value: 0.5737754058057266 and parameters: {'alpha': 0.01912728966123489, 'l1_ratio': 0.6255497882340519}. Best is trial 12 with value: 0.5740799102262502.

Running time: 0.1 sec
OOF RMSE: 2.41 | R2: 0.52
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.26 | R2: 0.57
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.641e+01, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.404e+01, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.421e+01, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.141e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.624e+01, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 18:41:59,742] Trial 20 finished with value: 0.5516212926870253 and parameters: {'alpha': 0.0032069375431277853, 'l1_ratio': 0.633846250264803}. Best is trial 12 with value: 0.5740799102262502.
[I 2025-07-11 18:41:59,857] Trial 21 finished with value: 0.5709222011144601 and parameters: {'alpha': 0.024612981702658285, 'l1_ratio': 0.8605717162613108}. Best is trial 12 with value: 0.5740799102262502.

Fold 3
Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 2.32 | R2: 0.55
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.27 | R2: 0.57

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.215e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.697e+01, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.067e+01, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.888e+01, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.190e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 18:41:59,985] Trial 22 finished with value: 0.5660978649561288 and parameters: {'alpha': 0.005469705222692398, 'l1_ratio': 0.5922151154990001}. Best is trial 12 with value: 0.5740799102262502.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.624e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.424e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.28 | R2: 0.57
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.283e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.728e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.996e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 18:42:00,130] Trial 23 finished with value: 0.5124743060636567 and parameters: {'alpha': 0.0006209628737729691, 'l1_ratio': 0.3722869887941964}. Best is trial 12 with value: 0.5740799102262502.
[I 2025-07-11 18:42:00,259] Trial 24 finished with value: 0.5707795015132491 and parameters: {'alpha': 0.025273956111774083, 'l1_ratio': 0.8461476349265168}. Best is trial 12 with value: 0.5740799102262502.
[I 2025-07-11 18:42:00,261] A new study created in memory with name: no-name-7a191e0b-f3f8-47f5-af3b-071d9127d399

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.42 | R2: 0.51
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.27 | R2: 0.57

✅ EN - Mejor R2: 0.57
📋 Parámetros: {'alpha': 0.014068334189618923, 'l1_ratio': 0.8007157782085097}

🔍 Optimizando en C2X-Complex_rhow_3x3_depth_lt_1...
Buscando mejores hiperparámetros para XGB...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:42:06,391] Trial 0 finished with value: 0.5873077598548294 and parameters: {'n_estimators': 1000, 'learning_rate': 0.0613665427580701, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.786584787935183, 'colsample_bytree': 0.8520456768410578}. Best is trial 0 with value: 0.5873077598548294.

Running time: 6.1 sec
OOF RMSE: 2.23 | R2: 0.59
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:42:10,295] Trial 1 finished with value: 0.5791248242019656 and parameters: {'n_estimators': 500, 'learning_rate': 0.009012950740612582, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.9066999411049907, 'colsample_bytree': 0.918937366810987}. Best is trial 0 with value: 0.5873077598548294.

Running time: 3.9 sec
OOF RMSE: 2.25 | R2: 0.58
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:42:12,859] Trial 2 finished with value: 0.5770964013567038 and parameters: {'n_estimators': 500, 'learning_rate': 0.0513622102259913, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.6261763658780619, 'colsample_bytree': 0.6704274304616332}. Best is trial 0 with value: 0.5873077598548294.

Running time: 2.6 sec
OOF RMSE: 2.25 | R2: 0.58
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:42:23,753] Trial 3 finished with value: 0.5512057830973085 and parameters: {'n_estimators': 2000, 'learning_rate': 0.007687177113973548, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.7214516817631214, 'colsample_bytree': 0.7359685164635275}. Best is trial 0 with value: 0.5873077598548294.

Running time: 10.9 sec
OOF RMSE: 2.32 | R2: 0.55
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:42:29,971] Trial 4 finished with value: 0.559022657164034 and parameters: {'n_estimators': 1000, 'learning_rate': 0.005781832449522716, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.8510461616182565, 'colsample_bytree': 0.8327707430798029}. Best is trial 0 with value: 0.5873077598548294.

Running time: 6.2 sec
OOF RMSE: 2.30 | R2: 0.56
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:42:34,202] Trial 5 finished with value: 0.6078894918940263 and parameters: {'n_estimators': 500, 'learning_rate': 0.019473720504513944, 'max_depth': 8, 'min_child_weight': 2, 'subsample': 0.727662489143255, 'colsample_bytree': 0.716141072954056}. Best is trial 5 with value: 0.6078894918940263.

Running time: 4.2 sec
OOF RMSE: 2.17 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:42:47,411] Trial 6 finished with value: 0.6037895828264017 and parameters: {'n_estimators': 2000, 'learning_rate': 0.005640016180218966, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.843297518088387, 'colsample_bytree': 0.9172665771413563}. Best is trial 5 with value: 0.6078894918940263.

Running time: 13.2 sec
OOF RMSE: 2.18 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:42:58,849] Trial 7 finished with value: 0.5924521111835646 and parameters: {'n_estimators': 2000, 'learning_rate': 0.006131092783823588, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.7523406252419358, 'colsample_bytree': 0.6955629505110354}. Best is trial 5 with value: 0.6078894918940263.

Running time: 11.4 sec
OOF RMSE: 2.21 | R2: 0.59
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:43:02,767] Trial 8 finished with value: 0.5974716827737336 and parameters: {'n_estimators': 500, 'learning_rate': 0.01972859685513912, 'max_depth': 8, 'min_child_weight': 2, 'subsample': 0.9191393147579484, 'colsample_bytree': 0.6028917310170371}. Best is trial 5 with value: 0.6078894918940263.

Running time: 3.9 sec
OOF RMSE: 2.20 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:43:13,033] Trial 9 finished with value: 0.5983898629283614 and parameters: {'n_estimators': 2000, 'learning_rate': 0.03036707572663433, 'max_depth': 5, 'min_child_weight': 1, 'subsample': 0.7515153551031192, 'colsample_bytree': 0.687281603210782}. Best is trial 5 with value: 0.6078894918940263.

Running time: 10.3 sec
OOF RMSE: 2.20 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:43:16,759] Trial 10 finished with value: 0.5916546995028005 and parameters: {'n_estimators': 500, 'learning_rate': 0.014299143099606898, 'max_depth': 8, 'min_child_weight': 2, 'subsample': 0.6469247145216434, 'colsample_bytree': 0.7731300497508053}. Best is trial 5 with value: 0.6078894918940263.

Running time: 3.7 sec
OOF RMSE: 2.22 | R2: 0.59
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:43:31,926] Trial 11 finished with value: 0.6057162528910076 and parameters: {'n_estimators': 2000, 'learning_rate': 0.01392737127004205, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.9965965329552816, 'colsample_bytree': 0.9500320224773164}. Best is trial 5 with value: 0.6078894918940263.

Running time: 15.2 sec
OOF RMSE: 2.18 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:43:47,549] Trial 12 finished with value: 0.6125572836034192 and parameters: {'n_estimators': 2000, 'learning_rate': 0.014451254928984041, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.964633240932591, 'colsample_bytree': 0.9789732654216777}. Best is trial 12 with value: 0.6125572836034192.

Running time: 15.6 sec
OOF RMSE: 2.16 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:43:51,825] Trial 13 finished with value: 0.5962993878310979 and parameters: {'n_estimators': 500, 'learning_rate': 0.032139026535473916, 'max_depth': 8, 'min_child_weight': 2, 'subsample': 0.6887203928506962, 'colsample_bytree': 0.9977221307404116}. Best is trial 12 with value: 0.6125572836034192.

Running time: 4.3 sec
OOF RMSE: 2.20 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:43:59,550] Trial 14 finished with value: 0.6187064662960376 and parameters: {'n_estimators': 1000, 'learning_rate': 0.012905207201742857, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.9725155494556934, 'colsample_bytree': 0.794881996769778}. Best is trial 14 with value: 0.6187064662960376.

Running time: 7.7 sec
OOF RMSE: 2.14 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:44:07,385] Trial 15 finished with value: 0.6161964191096532 and parameters: {'n_estimators': 1000, 'learning_rate': 0.011100859611938135, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.9801489045016155, 'colsample_bytree': 0.8644928205338948}. Best is trial 14 with value: 0.6187064662960376.

Running time: 7.8 sec
OOF RMSE: 2.15 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:44:15,086] Trial 16 finished with value: 0.6079266930412554 and parameters: {'n_estimators': 1000, 'learning_rate': 0.010165078293750336, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.9334838570308938, 'colsample_bytree': 0.8653749716383902}. Best is trial 14 with value: 0.6187064662960376.

Running time: 7.7 sec
OOF RMSE: 2.17 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:44:19,645] Trial 17 finished with value: 0.572228283747878 and parameters: {'n_estimators': 1000, 'learning_rate': 0.011474078522592116, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.8656801173745923, 'colsample_bytree': 0.7929514926114969}. Best is trial 14 with value: 0.6187064662960376.

Running time: 4.6 sec
OOF RMSE: 2.27 | R2: 0.57
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:44:28,443] Trial 18 finished with value: 0.5966982075616617 and parameters: {'n_estimators': 1000, 'learning_rate': 0.0267856209992447, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.9901023833016884, 'colsample_bytree': 0.8876256153501182}. Best is trial 14 with value: 0.6187064662960376.

Running time: 8.8 sec
OOF RMSE: 2.20 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:44:35,249] Trial 19 finished with value: 0.581625181159756 and parameters: {'n_estimators': 1000, 'learning_rate': 0.018369295040702022, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.89177165774277, 'colsample_bytree': 0.8196846970742644}. Best is trial 14 with value: 0.6187064662960376.

Running time: 6.8 sec
OOF RMSE: 2.24 | R2: 0.58
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:44:39,251] Trial 20 finished with value: 0.6039577698156635 and parameters: {'n_estimators': 1000, 'learning_rate': 0.0992742245804185, 'max_depth': 8, 'min_child_weight': 3, 'subsample': 0.9512148283520485, 'colsample_bytree': 0.7680306146529078}. Best is trial 14 with value: 0.6187064662960376.

Running time: 4.0 sec
OOF RMSE: 2.18 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:44:47,698] Trial 21 finished with value: 0.6077215516928804 and parameters: {'n_estimators': 1000, 'learning_rate': 0.013305840644373417, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.9612936102076584, 'colsample_bytree': 0.9919434857382052}. Best is trial 14 with value: 0.6187064662960376.

Running time: 8.4 sec
OOF RMSE: 2.17 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:45:03,107] Trial 22 finished with value: 0.6070246586457865 and parameters: {'n_estimators': 2000, 'learning_rate': 0.007893228370430192, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.9680624062256639, 'colsample_bytree': 0.9490733311995856}. Best is trial 14 with value: 0.6187064662960376.

Running time: 15.4 sec
OOF RMSE: 2.17 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:45:11,565] Trial 23 finished with value: 0.6160587046563994 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01537983207966824, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.9963292596470549, 'colsample_bytree': 0.8885708349764517}. Best is trial 14 with value: 0.6187064662960376.

Running time: 8.5 sec
OOF RMSE: 2.15 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:45:21,125] Trial 24 finished with value: 0.547682021202971 and parameters: {'n_estimators': 1000, 'learning_rate': 0.023465123587354583, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.9952890853395858, 'colsample_bytree': 0.890132563532984}. Best is trial 14 with value: 0.6187064662960376.
[I 2025-07-11 18:45:21,126] A new study created in memory with name: no-name-2bf857a9-c894-4b4e-bd66-52ea38327c67

Running time: 9.6 sec
OOF RMSE: 2.33 | R2: 0.55

✅ XGB - Mejor R2: 0.62
📋 Parámetros: {'n_estimators': 1000, 'learning_rate': 0.012905207201742857, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.9725155494556934, 'colsample_bytree': 0.794881996769778}

Buscando mejores hiperparámetros para LBM...
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 18:45:21,375] Trial 0 finished with value: 0.5899597511062901 and parameters: {'learning_rate': 0.08440714917766223, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 21, 'subsample': 0.7213389603799424, 'colsample_bytree': 0.8441454374691357, 'n_estimators': 500}. Best is trial 0 with value: 0.5899597511062901.

Fold 5
Running time: 0.2 sec
OOF RMSE: 2.22 | R2: 0.59
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:45:22,503] Trial 1 finished with value: 0.6359566598803832 and parameters: {'learning_rate': 0.00959359632048751, 'num_leaves': 20, 'max_depth': 8, 'min_child_samples': 17, 'subsample': 0.6332143711669294, 'colsample_bytree': 0.731826563490885, 'n_estimators': 2000}. Best is trial 1 with value: 0.6359566598803832.

Running time: 1.1 sec
OOF RMSE: 2.09 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 18:45:23,052] Trial 2 finished with value: 0.484734994269471 and parameters: {'learning_rate': 0.010211517666301566, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 6, 'subsample': 0.7464664988815128, 'colsample_bytree': 0.6317063921898828, 'n_estimators': 1000}. Best is trial 1 with value: 0.6359566598803832.

Fold 5
Running time: 0.5 sec
OOF RMSE: 2.49 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 18:45:23,560] Trial 3 finished with value: 0.5714404827572335 and parameters: {'learning_rate': 0.008754106785240424, 'num_leaves': 40, 'max_depth': 6, 'min_child_samples': 15, 'subsample': 0.7372674180950471, 'colsample_bytree': 0.878549968062177, 'n_estimators': 1000}. Best is trial 1 with value: 0.6359566598803832.

Fold 5
Running time: 0.5 sec
OOF RMSE: 2.27 | R2: 0.57
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:45:24,494] Trial 4 finished with value: 0.5534553142772916 and parameters: {'learning_rate': 0.03625135246859152, 'num_leaves': 40, 'max_depth': 6, 'min_child_samples': 24, 'subsample': 0.8820309653099283, 'colsample_bytree': 0.8315187598199529, 'n_estimators': 2000}. Best is trial 1 with value: 0.6359566598803832.

Running time: 0.9 sec
OOF RMSE: 2.32 | R2: 0.55
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 18:45:25,097] Trial 5 finished with value: 0.5931125424310264 and parameters: {'learning_rate': 0.006719075206182836, 'num_leaves': 40, 'max_depth': 8, 'min_child_samples': 16, 'subsample': 0.9350191877297878, 'colsample_bytree': 0.7122829852077335, 'n_estimators': 1000}. Best is trial 1 with value: 0.6359566598803832.

Fold 5
Running time: 0.6 sec
OOF RMSE: 2.21 | R2: 0.59
Fold 1
Fold 2
Fold 3

[I 2025-07-11 18:45:25,618] Trial 6 finished with value: 0.5542266144672867 and parameters: {'learning_rate': 0.07782604720864875, 'num_leaves': 20, 'max_depth': 8, 'min_child_samples': 24, 'subsample': 0.9589810034994314, 'colsample_bytree': 0.707863733788524, 'n_estimators': 1000}. Best is trial 1 with value: 0.6359566598803832.

Fold 4
Fold 5
Running time: 0.5 sec
OOF RMSE: 2.31 | R2: 0.55
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:45:25,887] Trial 7 finished with value: 0.5958089026775426 and parameters: {'learning_rate': 0.01545802114269676, 'num_leaves': 40, 'max_depth': 6, 'min_child_samples': 17, 'subsample': 0.6310025626532103, 'colsample_bytree': 0.6331083505088496, 'n_estimators': 500}. Best is trial 1 with value: 0.6359566598803832.

Running time: 0.3 sec
OOF RMSE: 2.20 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 18:45:26,725] Trial 8 finished with value: 0.5682585321287817 and parameters: {'learning_rate': 0.006606587012187836, 'num_leaves': 80, 'max_depth': 5, 'min_child_samples': 13, 'subsample': 0.8801895947088447, 'colsample_bytree': 0.8060391535864262, 'n_estimators': 2000}. Best is trial 1 with value: 0.6359566598803832.

Fold 5
Running time: 0.8 sec
OOF RMSE: 2.28 | R2: 0.57
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:45:27,012] Trial 9 finished with value: 0.5251599826179076 and parameters: {'learning_rate': 0.00871740014660258, 'num_leaves': 20, 'max_depth': 8, 'min_child_samples': 22, 'subsample': 0.6748654926319012, 'colsample_bytree': 0.9261992193601862, 'n_estimators': 500}. Best is trial 1 with value: 0.6359566598803832.

Running time: 0.3 sec
OOF RMSE: 2.39 | R2: 0.53
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:45:28,194] Trial 10 finished with value: 0.5465898768971161 and parameters: {'learning_rate': 0.026126166387692377, 'num_leaves': 60, 'max_depth': 7, 'min_child_samples': 9, 'subsample': 0.6202425680474979, 'colsample_bytree': 0.7050941089998548, 'n_estimators': 2000}. Best is trial 1 with value: 0.6359566598803832.

Running time: 1.2 sec
OOF RMSE: 2.33 | R2: 0.55
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 18:45:28,500] Trial 11 finished with value: 0.5868341756425924 and parameters: {'learning_rate': 0.015868337043711486, 'num_leaves': 60, 'max_depth': 7, 'min_child_samples': 19, 'subsample': 0.6012709840719657, 'colsample_bytree': 0.604087279684113, 'n_estimators': 500}. Best is trial 1 with value: 0.6359566598803832.

Fold 5
Running time: 0.3 sec
OOF RMSE: 2.23 | R2: 0.59
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 18:45:29,581] Trial 12 finished with value: 0.6267364696013629 and parameters: {'learning_rate': 0.016014812622025972, 'num_leaves': 80, 'max_depth': 7, 'min_child_samples': 18, 'subsample': 0.6653004069128492, 'colsample_bytree': 0.7487216999634116, 'n_estimators': 2000}. Best is trial 1 with value: 0.6359566598803832.

Fold 5
Running time: 1.1 sec
OOF RMSE: 2.12 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:45:30,692] Trial 13 finished with value: 0.5381413198210225 and parameters: {'learning_rate': 0.015834597252757144, 'num_leaves': 80, 'max_depth': 7, 'min_child_samples': 11, 'subsample': 0.7960140354700828, 'colsample_bytree': 0.7563630826724314, 'n_estimators': 2000}. Best is trial 1 with value: 0.6359566598803832.

Running time: 1.1 sec
OOF RMSE: 2.36 | R2: 0.54
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:45:31,948] Trial 14 finished with value: 0.6207234145282331 and parameters: {'learning_rate': 0.040615253909951715, 'num_leaves': 80, 'max_depth': 8, 'min_child_samples': 18, 'subsample': 0.662446343827824, 'colsample_bytree': 0.987758655057604, 'n_estimators': 2000}. Best is trial 1 with value: 0.6359566598803832.

Running time: 1.2 sec
OOF RMSE: 2.13 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:45:33,042] Trial 15 finished with value: 0.5826758296462848 and parameters: {'learning_rate': 0.012419035484683325, 'num_leaves': 80, 'max_depth': 7, 'min_child_samples': 14, 'subsample': 0.6802350122845026, 'colsample_bytree': 0.7573892679474741, 'n_estimators': 2000}. Best is trial 1 with value: 0.6359566598803832.

Running time: 1.1 sec
OOF RMSE: 2.24 | R2: 0.58
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:45:34,144] Trial 16 finished with value: 0.6115129560146451 and parameters: {'learning_rate': 0.0053239980095735355, 'num_leaves': 80, 'max_depth': 8, 'min_child_samples': 20, 'subsample': 0.7932696730013997, 'colsample_bytree': 0.7607840860765246, 'n_estimators': 2000}. Best is trial 1 with value: 0.6359566598803832.

Running time: 1.1 sec
OOF RMSE: 2.16 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:45:35,262] Trial 17 finished with value: 0.5722006610227008 and parameters: {'learning_rate': 0.019361435337743132, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 12, 'subsample': 0.7073027899419365, 'colsample_bytree': 0.6791899616982152, 'n_estimators': 2000}. Best is trial 1 with value: 0.6359566598803832.

Running time: 1.1 sec
OOF RMSE: 2.27 | R2: 0.57
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:45:36,433] Trial 18 finished with value: 0.6396824037232156 and parameters: {'learning_rate': 0.026561605591333314, 'num_leaves': 60, 'max_depth': 8, 'min_child_samples': 17, 'subsample': 0.8418954721083158, 'colsample_bytree': 0.7779198169764334, 'n_estimators': 2000}. Best is trial 18 with value: 0.6396824037232156.

Running time: 1.2 sec
OOF RMSE: 2.08 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:45:37,800] Trial 19 finished with value: 0.5329837805985322 and parameters: {'learning_rate': 0.028322358953125296, 'num_leaves': 60, 'max_depth': 8, 'min_child_samples': 9, 'subsample': 0.8596058094886947, 'colsample_bytree': 0.8955459458337448, 'n_estimators': 2000}. Best is trial 18 with value: 0.6396824037232156.

Running time: 1.4 sec
OOF RMSE: 2.37 | R2: 0.53
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 18:45:38,822] Trial 20 finished with value: 0.5537887874901135 and parameters: {'learning_rate': 0.053888963027534736, 'num_leaves': 60, 'max_depth': 8, 'min_child_samples': 22, 'subsample': 0.8226778159790147, 'colsample_bytree': 0.810040149597265, 'n_estimators': 2000}. Best is trial 18 with value: 0.6396824037232156.

Fold 5
Running time: 1.0 sec
OOF RMSE: 2.32 | R2: 0.55
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 1.0 sec
OOF RMSE: 2.09 | R2: 0.64

[I 2025-07-11 18:45:39,873] Trial 21 finished with value: 0.6372501229392172 and parameters: {'learning_rate': 0.022398912472837224, 'num_leaves': 60, 'max_depth': 7, 'min_child_samples': 17, 'subsample': 0.8355582797674564, 'colsample_bytree': 0.7696206382620746, 'n_estimators': 2000}. Best is trial 18 with value: 0.6396824037232156.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:45:41,046] Trial 22 finished with value: 0.6484644605024845 and parameters: {'learning_rate': 0.02266040247346743, 'num_leaves': 60, 'max_depth': 8, 'min_child_samples': 16, 'subsample': 0.8315783594735167, 'colsample_bytree': 0.7884859666190508, 'n_estimators': 2000}. Best is trial 22 with value: 0.6484644605024845.

Running time: 1.2 sec
OOF RMSE: 2.06 | R2: 0.65
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:45:42,154] Trial 23 finished with value: 0.5528158749849948 and parameters: {'learning_rate': 0.02233639209648828, 'num_leaves': 60, 'max_depth': 7, 'min_child_samples': 15, 'subsample': 0.8390633374386753, 'colsample_bytree': 0.7872152703908234, 'n_estimators': 2000}. Best is trial 22 with value: 0.6484644605024845.

Running time: 1.1 sec
OOF RMSE: 2.32 | R2: 0.55
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:45:43,336] Trial 24 finished with value: 0.6183213256196849 and parameters: {'learning_rate': 0.03435615359585131, 'num_leaves': 60, 'max_depth': 8, 'min_child_samples': 19, 'subsample': 0.7740540379497551, 'colsample_bytree': 0.8543473948229279, 'n_estimators': 2000}. Best is trial 22 with value: 0.6484644605024845.
[I 2025-07-11 18:45:43,337] A new study created in memory with name: no-name-b8fd5c9d-22f1-4fa4-8491-7f0f5a48fcd8

Running time: 1.2 sec
OOF RMSE: 2.14 | R2: 0.62

✅ LBM - Mejor R2: 0.65
📋 Parámetros: {'learning_rate': 0.02266040247346743, 'num_leaves': 60, 'max_depth': 8, 'min_child_samples': 16, 'subsample': 0.8315783594735167, 'colsample_bytree': 0.7884859666190508, 'n_estimators': 2000}

Buscando mejores hiperparámetros para MLP...
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 18:45:44,946] Trial 0 finished with value: 0.4139372593223217 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 9.112792578770283e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.00013339310965046562}. Best is trial 0 with value: 0.4139372593223217.

Running time: 1.6 sec
OOF RMSE: 2.65 | R2: 0.41
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 18:45:47,022] Trial 1 finished with value: 0.5355158883307377 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.027992184954814894, 'learning_rate': 'adaptive', 'learning_rate_init': 0.000546305887102489}. Best is trial 1 with value: 0.5355158883307377.

Running time: 2.1 sec
OOF RMSE: 2.36 | R2: 0.54
Fold 1
Fold 2
Fold 3

[I 2025-07-11 18:45:47,776] Trial 2 finished with value: 0.45903307634911616 and parameters: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.013641276677854836, 'learning_rate': 'constant', 'learning_rate_init': 0.0038409832889187675}. Best is trial 1 with value: 0.5355158883307377.

Fold 4
Fold 5
Running time: 0.7 sec
OOF RMSE: 2.55 | R2: 0.46
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 18:45:50,191] Trial 3 finished with value: 0.3560450210952103 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 4.730371005258923e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.000392016847375823}. Best is trial 1 with value: 0.5355158883307377.

Running time: 2.4 sec
OOF RMSE: 2.78 | R2: 0.36
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 18:45:52,060] Trial 4 finished with value: 0.4108191429246657 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.01480591840545321, 'learning_rate': 'constant', 'learning_rate_init': 0.00010167550849164295}. Best is trial 1 with value: 0.5355158883307377.

Running time: 1.9 sec
OOF RMSE: 2.66 | R2: 0.41
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 18:45:53,977] Trial 5 finished with value: 0.5609748466486202 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.0456270202485248, 'learning_rate': 'adaptive', 'learning_rate_init': 0.005159955907982163}. Best is trial 5 with value: 0.5609748466486202.

Running time: 1.9 sec
OOF RMSE: 2.30 | R2: 0.56
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 18:45:55,013] Trial 6 finished with value: 0.45325243594322706 and parameters: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.013530549671776028, 'learning_rate': 'constant', 'learning_rate_init': 0.0001527925771172708}. Best is trial 5 with value: 0.5609748466486202.

Running time: 1.0 sec
OOF RMSE: 2.56 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 18:45:56,020] Trial 7 finished with value: 0.40400328310227274 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'sgd', 'alpha': 2.18230196765669e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.0007752366675222362}. Best is trial 5 with value: 0.5609748466486202.

Fold 5
Running time: 1.0 sec
OOF RMSE: 2.68 | R2: 0.40
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 18:45:57,630] Trial 8 finished with value: 0.6255921313925907 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 5.6634631922971965e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.0015095384374723241}. Best is trial 8 with value: 0.6255921313925907.

Running time: 1.6 sec
OOF RMSE: 2.12 | R2: 0.63
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 18:45:59,393] Trial 9 finished with value: 0.24298528828006638 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'relu', 'solver': 'sgd', 'alpha': 4.362963658075525e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0020899228976540107}. Best is trial 8 with value: 0.6255921313925907.

Running time: 1.8 sec
OOF RMSE: 3.02 | R2: 0.24
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 18:46:00,048] Trial 10 finished with value: 0.358816999815846 and parameters: {'hidden_layer_sizes': '50', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0005533757610326227, 'learning_rate': 'constant', 'learning_rate_init': 0.0020388275255878332}. Best is trial 8 with value: 0.6255921313925907.

Fold 4
Fold 5
Running time: 0.6 sec
OOF RMSE: 2.78 | R2: 0.36
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:46:00,953] Trial 11 finished with value: 0.6136120874949258 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0012697619667345053, 'learning_rate': 'adaptive', 'learning_rate_init': 0.008959939545070718}. Best is trial 8 with value: 0.6255921313925907.

Running time: 0.9 sec
OOF RMSE: 2.15 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 18:46:02,027] Trial 12 finished with value: 0.6170590242426479 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0008878263981579364, 'learning_rate': 'adaptive', 'learning_rate_init': 0.008406531099064024}. Best is trial 8 with value: 0.6255921313925907.

Fold 5
Running time: 1.1 sec
OOF RMSE: 2.15 | R2: 0.62
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 18:46:03,472] Trial 13 finished with value: 0.6273132089546503 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0006037197097259265, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0016219279636414882}. Best is trial 13 with value: 0.6273132089546503.

Running time: 1.4 sec
OOF RMSE: 2.12 | R2: 0.63
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 18:46:04,247] Trial 14 finished with value: 0.3445972384469447 and parameters: {'hidden_layer_sizes': '50', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0002177880841808394, 'learning_rate': 'constant', 'learning_rate_init': 0.0015137210194678668}. Best is trial 13 with value: 0.6273132089546503.

Fold 4
Fold 5
Running time: 0.8 sec
OOF RMSE: 2.81 | R2: 0.34
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 18:46:06,051] Trial 15 finished with value: 0.6045446061636857 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0035427036280135543, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0009416294627425609}. Best is trial 13 with value: 0.6273132089546503.

Running time: 1.8 sec
OOF RMSE: 2.18 | R2: 0.60
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 18:46:07,615] Trial 16 finished with value: 0.5065130458981686 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 1.3136420611767156e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.0002608405059939954}. Best is trial 13 with value: 0.6273132089546503.

Running time: 1.6 sec
OOF RMSE: 2.44 | R2: 0.51
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:46:08,808] Trial 17 finished with value: 0.616980736972144 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0002305765706547894, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0032066339285743766}. Best is trial 13 with value: 0.6273132089546503.

Running time: 1.2 sec
OOF RMSE: 2.15 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 18:46:10,402] Trial 18 finished with value: 0.6104409850233781 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.003239806859141561, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0016206414187957174}. Best is trial 13 with value: 0.6273132089546503.

Running time: 1.6 sec
OOF RMSE: 2.16 | R2: 0.61
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 18:46:11,082] Trial 19 finished with value: 0.33947555197820733 and parameters: {'hidden_layer_sizes': '50', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.00016506933459739504, 'learning_rate': 'constant', 'learning_rate_init': 0.0011918389618694287}. Best is trial 13 with value: 0.6273132089546503.

Fold 4
Fold 5
Running time: 0.7 sec
OOF RMSE: 2.82 | R2: 0.34
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 18:46:12,980] Trial 20 finished with value: 0.5750245865199801 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.00261692633300388, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0006604614138988335}. Best is trial 13 with value: 0.6273132089546503.

Running time: 1.9 sec
OOF RMSE: 2.26 | R2: 0.58
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:46:13,812] Trial 21 finished with value: 0.6120195334080114 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0008508689799010728, 'learning_rate': 'adaptive', 'learning_rate_init': 0.009360667616229702}. Best is trial 13 with value: 0.6273132089546503.

Running time: 0.8 sec
OOF RMSE: 2.16 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:46:14,851] Trial 22 finished with value: 0.6172451601484165 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0004675449648550413, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00558382381364975}. Best is trial 13 with value: 0.6273132089546503.

Running time: 1.0 sec
OOF RMSE: 2.14 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:46:16,044] Trial 23 finished with value: 0.6204275803179735 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.000391836213143719, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0029402734872109107}. Best is trial 13 with value: 0.6273132089546503.

Running time: 1.2 sec
OOF RMSE: 2.14 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:46:17,188] Trial 24 finished with value: 0.6200447752063427 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 8.125451748439876e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.002829528511522987}. Best is trial 13 with value: 0.6273132089546503.
[I 2025-07-11 18:46:17,190] A new study created in memory with name: no-name-6aaf21dc-ea09-4eca-b273-f6c1941424ab
[I 2025-07-11 18:46:17,278] Trial 0 finished with value: 0.09915369023130527 and parameters: {'kernel': 'sigmoid', 'C': 0.2634243487576688, 'epsilon': 0.17371602322626278, 'gamma': 'auto'}. Best is trial 0 with value: 0.09915369023130527.
[I 2025-07-11 18:46:17,353] Trial 1 finished with value: 0.40239215615508794 and parameters: {'kernel': 'rbf', 'C': 3.7030294231888865, 'epsilon': 0.07718767680980221, 'gamma': 'auto'}. Best is trial 1 with value: 0.40239215615508794.

Running time: 1.1 sec
OOF RMSE: 2.14 | R2: 0.62

✅ MLP - Mejor R2: 0.63
📋 Parámetros: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0006037197097259265, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0016219279636414882}

Buscando mejores hiperparámetros para SVR...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.29 | R2: 0.10
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.68 | R2: 0.40
Fold 1
Fold 2
Fold 3

[I 2025-07-11 18:46:17,425] Trial 2 finished with value: -29.8180371793831 and parameters: {'kernel': 'sigmoid', 'C': 3.2314572479782764, 'epsilon': 0.055922321173570225, 'gamma': 'scale'}. Best is trial 1 with value: 0.40239215615508794.
[I 2025-07-11 18:46:17,502] Trial 3 finished with value: -64.18505481065147 and parameters: {'kernel': 'sigmoid', 'C': 4.9326126018858885, 'epsilon': 0.0912423176375546, 'gamma': 'scale'}. Best is trial 1 with value: 0.40239215615508794.
[I 2025-07-11 18:46:17,569] Trial 4 finished with value: 0.030809737983915397 and parameters: {'kernel': 'rbf', 'C': 0.10279639982734204, 'epsilon': 0.02333520532450404, 'gamma': 'auto'}. Best is trial 1 with value: 0.40239215615508794.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 19.24 | R2: -29.82
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 27.99 | R2: -64.19
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.41 | R2: 0.03
Fold 1
Fold 2

[I 2025-07-11 18:46:17,640] Trial 5 finished with value: -44.28861962728015 and parameters: {'kernel': 'sigmoid', 'C': 3.9777352981064515, 'epsilon': 0.18923242700506612, 'gamma': 'scale'}. Best is trial 1 with value: 0.40239215615508794.
[I 2025-07-11 18:46:17,719] Trial 6 finished with value: 0.4931845986570531 and parameters: {'kernel': 'rbf', 'C': 7.605806452865518, 'epsilon': 0.08839256532146919, 'gamma': 'scale'}. Best is trial 6 with value: 0.4931845986570531.
[I 2025-07-11 18:46:17,785] Trial 7 finished with value: 0.1698416381008654 and parameters: {'kernel': 'rbf', 'C': 0.5065701080920145, 'epsilon': 0.19198120064262103, 'gamma': 'scale'}. Best is trial 6 with value: 0.4931845986570531.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 23.33 | R2: -44.29
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.47 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.16 | R2: 0.17
Fold 1

[I 2025-07-11 18:46:17,858] Trial 8 finished with value: 0.42973852437700955 and parameters: {'kernel': 'rbf', 'C': 4.515324158308795, 'epsilon': 0.025233357107054398, 'gamma': 'auto'}. Best is trial 6 with value: 0.4931845986570531.
[I 2025-07-11 18:46:17,950] Trial 9 finished with value: -0.5467901850019443 and parameters: {'kernel': 'sigmoid', 'C': 0.6655437425096662, 'epsilon': 0.1651429848589372, 'gamma': 'auto'}. Best is trial 6 with value: 0.4931845986570531.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.62 | R2: 0.43
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 4.31 | R2: -0.55
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 18:46:18,034] Trial 10 finished with value: 0.5148397397491912 and parameters: {'kernel': 'rbf', 'C': 9.749958503683633, 'epsilon': 0.12902461039791613, 'gamma': 'scale'}. Best is trial 10 with value: 0.5148397397491912.
[I 2025-07-11 18:46:18,120] Trial 11 finished with value: 0.5114036270550117 and parameters: {'kernel': 'rbf', 'C': 9.368486333027231, 'epsilon': 0.13196839458949244, 'gamma': 'scale'}. Best is trial 10 with value: 0.5148397397491912.
[I 2025-07-11 18:46:18,199] Trial 12 finished with value: 0.5168010405864566 and parameters: {'kernel': 'rbf', 'C': 9.930379673758079, 'epsilon': 0.13365054017947223, 'gamma': 'scale'}. Best is trial 12 with value: 0.5168010405864566.

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.41 | R2: 0.51
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.42 | R2: 0.51
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.41 | R2: 0.52
Fold 1

[I 2025-07-11 18:46:18,279] Trial 13 finished with value: 0.2980623061664214 and parameters: {'kernel': 'rbf', 'C': 1.6686109440363506, 'epsilon': 0.1305534508017676, 'gamma': 'scale'}. Best is trial 12 with value: 0.5168010405864566.
[I 2025-07-11 18:46:18,361] Trial 14 finished with value: 0.28845987488809144 and parameters: {'kernel': 'rbf', 'C': 1.5407721804651133, 'epsilon': 0.129949729113247, 'gamma': 'scale'}. Best is trial 12 with value: 0.5168010405864566.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.90 | R2: 0.30
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.92 | R2: 0.29
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 18:46:18,440] Trial 15 finished with value: 0.5128326819513069 and parameters: {'kernel': 'rbf', 'C': 9.417546760891922, 'epsilon': 0.1515094777836427, 'gamma': 'scale'}. Best is trial 12 with value: 0.5168010405864566.
[I 2025-07-11 18:46:18,519] Trial 16 finished with value: 0.3257140042118293 and parameters: {'kernel': 'rbf', 'C': 2.082283799519771, 'epsilon': 0.11331363321665339, 'gamma': 'scale'}. Best is trial 12 with value: 0.5168010405864566.
[I 2025-07-11 18:46:18,622] Trial 17 finished with value: 0.4756062615913741 and parameters: {'kernel': 'rbf', 'C': 6.310938326297665, 'epsilon': 0.15338648472864805, 'gamma': 'scale'}. Best is trial 12 with value: 0.5168010405864566.

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.42 | R2: 0.51
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.85 | R2: 0.33
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.51 | R2: 0.48

[I 2025-07-11 18:46:18,701] Trial 18 finished with value: 0.34666462177425683 and parameters: {'kernel': 'rbf', 'C': 2.439316818247866, 'epsilon': 0.10706728364220613, 'gamma': 'scale'}. Best is trial 12 with value: 0.5168010405864566.
[I 2025-07-11 18:46:18,778] Trial 19 finished with value: 0.22809536412138587 and parameters: {'kernel': 'rbf', 'C': 0.9150152733282941, 'epsilon': 0.06470056462714392, 'gamma': 'scale'}. Best is trial 12 with value: 0.5168010405864566.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.80 | R2: 0.35
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.05 | R2: 0.23
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 18:46:18,850] Trial 20 finished with value: 0.12141728027481935 and parameters: {'kernel': 'rbf', 'C': 0.32899008419421794, 'epsilon': 0.11803661902539492, 'gamma': 'scale'}. Best is trial 12 with value: 0.5168010405864566.
[I 2025-07-11 18:46:18,932] Trial 21 finished with value: 0.500707384240112 and parameters: {'kernel': 'rbf', 'C': 8.268169226660936, 'epsilon': 0.1470226365953512, 'gamma': 'scale'}. Best is trial 12 with value: 0.5168010405864566.
[I 2025-07-11 18:46:19,013] Trial 22 finished with value: 0.517408169425418 and parameters: {'kernel': 'rbf', 'C': 9.923337007863852, 'epsilon': 0.14620751167997123, 'gamma': 'scale'}. Best is trial 22 with value: 0.517408169425418.

Fold 5
Running time: 0.1 sec
OOF RMSE: 3.25 | R2: 0.12
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.45 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.41 | R2: 0.52
Fold 1
Fold 2

[I 2025-07-11 18:46:19,092] Trial 23 finished with value: 0.4807014373996433 and parameters: {'kernel': 'rbf', 'C': 6.688625479314756, 'epsilon': 0.17511399489460763, 'gamma': 'scale'}. Best is trial 22 with value: 0.517408169425418.
[I 2025-07-11 18:46:19,176] Trial 24 finished with value: 0.4635429158814772 and parameters: {'kernel': 'rbf', 'C': 5.634110743223042, 'epsilon': 0.1448169143736418, 'gamma': 'scale'}. Best is trial 22 with value: 0.517408169425418.
[I 2025-07-11 18:46:19,178] A new study created in memory with name: no-name-cfdcbb8a-bbe3-4cb7-a136-a149b7094d47
[I 2025-07-11 18:46:19,232] Trial 0 finished with value: 0.5759688374252304 and parameters: {'n_neighbors': 6, 'weights': 'uniform', 'leaf_size': 38}. Best is trial 0 with value: 0.5759688374252304.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.50 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.54 | R2: 0.46

✅ SVR - Mejor R2: 0.52
📋 Parámetros: {'kernel': 'rbf', 'C': 9.923337007863852, 'epsilon': 0.14620751167997123, 'gamma': 'scale'}

Buscando mejores hiperparámetros para KNN...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.26 | R2: 0.58
Fold 1
Fold 2

[I 2025-07-11 18:46:19,296] Trial 1 finished with value: 0.5524288643134794 and parameters: {'n_neighbors': 11, 'weights': 'uniform', 'leaf_size': 20}. Best is trial 0 with value: 0.5759688374252304.
[I 2025-07-11 18:46:19,361] Trial 2 finished with value: 0.5916207326159093 and parameters: {'n_neighbors': 15, 'weights': 'distance', 'leaf_size': 24}. Best is trial 2 with value: 0.5916207326159093.
[I 2025-07-11 18:46:19,418] Trial 3 finished with value: 0.6279356929931235 and parameters: {'n_neighbors': 12, 'weights': 'distance', 'leaf_size': 12}. Best is trial 3 with value: 0.6279356929931235.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.32 | R2: 0.55
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.22 | R2: 0.59
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.11 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 18:46:19,475] Trial 4 finished with value: 0.5201472020612046 and parameters: {'n_neighbors': 8, 'weights': 'uniform', 'leaf_size': 29}. Best is trial 3 with value: 0.6279356929931235.
[I 2025-07-11 18:46:19,537] Trial 5 finished with value: 0.5524288643134794 and parameters: {'n_neighbors': 11, 'weights': 'uniform', 'leaf_size': 10}. Best is trial 3 with value: 0.6279356929931235.
[I 2025-07-11 18:46:19,601] Trial 6 finished with value: 0.54879533552123 and parameters: {'n_neighbors': 13, 'weights': 'uniform', 'leaf_size': 13}. Best is trial 3 with value: 0.6279356929931235.
[I 2025-07-11 18:46:19,662] Trial 7 finished with value: 0.5542529896440821 and parameters: {'n_neighbors': 12, 'weights': 'uniform', 'leaf_size': 11}. Best is trial 3 with value: 0.6279356929931235.

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.40 | R2: 0.52
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.32 | R2: 0.55
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.33 | R2: 0.55
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.31 | R2: 0.55

[I 2025-07-11 18:46:19,728] Trial 8 finished with value: 0.6068919702931673 and parameters: {'n_neighbors': 10, 'weights': 'distance', 'leaf_size': 24}. Best is trial 3 with value: 0.6279356929931235.
[I 2025-07-11 18:46:19,819] Trial 9 finished with value: 0.622307802014919 and parameters: {'n_neighbors': 13, 'weights': 'distance', 'leaf_size': 32}. Best is trial 3 with value: 0.6279356929931235.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.17 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.13 | R2: 0.62
Fold 1
Fold 2
Fold 3

[I 2025-07-11 18:46:19,891] Trial 10 finished with value: 0.6585589988215383 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'leaf_size': 18}. Best is trial 10 with value: 0.6585589988215383.
[I 2025-07-11 18:46:19,963] Trial 11 finished with value: 0.6864964342969242 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 17}. Best is trial 11 with value: 0.6864964342969242.
[I 2025-07-11 18:46:20,031] Trial 12 finished with value: 0.6864964342969242 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 18}. Best is trial 11 with value: 0.6864964342969242.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.03 | R2: 0.66
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.94 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.94 | R2: 0.69
Fold 1
Fold 2
Fold 3

[I 2025-07-11 18:46:20,097] Trial 13 finished with value: 0.6864964342969242 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 17}. Best is trial 11 with value: 0.6864964342969242.
[I 2025-07-11 18:46:20,171] Trial 14 finished with value: 0.6386090049568667 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'leaf_size': 20}. Best is trial 11 with value: 0.6864964342969242.
[I 2025-07-11 18:46:20,242] Trial 15 finished with value: 0.630681928635954 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'leaf_size': 16}. Best is trial 11 with value: 0.6864964342969242.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.94 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.08 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.11 | R2: 0.63
Fold 1
Fold 2
Fold 3

[I 2025-07-11 18:46:20,310] Trial 16 finished with value: 0.6864964342969242 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 28}. Best is trial 11 with value: 0.6864964342969242.
[I 2025-07-11 18:46:20,382] Trial 17 finished with value: 0.6386090049568667 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'leaf_size': 22}. Best is trial 11 with value: 0.6864964342969242.
[I 2025-07-11 18:46:20,452] Trial 18 finished with value: 0.5989843643301974 and parameters: {'n_neighbors': 8, 'weights': 'distance', 'leaf_size': 14}. Best is trial 11 with value: 0.6864964342969242.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.94 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.08 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.20 | R2: 0.60
Fold 1
Fold 2
Fold 3

[I 2025-07-11 18:46:20,521] Trial 19 finished with value: 0.6386090049568667 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'leaf_size': 27}. Best is trial 11 with value: 0.6864964342969242.
[I 2025-07-11 18:46:20,592] Trial 20 finished with value: 0.6864964342969242 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 37}. Best is trial 11 with value: 0.6864964342969242.
[I 2025-07-11 18:46:20,661] Trial 21 finished with value: 0.6864964342969242 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 17}. Best is trial 11 with value: 0.6864964342969242.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.08 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.94 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.94 | R2: 0.69
Fold 1
Fold 2
Fold 3

[I 2025-07-11 18:46:20,730] Trial 22 finished with value: 0.6585589988215383 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'leaf_size': 15}. Best is trial 11 with value: 0.6864964342969242.
[I 2025-07-11 18:46:20,804] Trial 23 finished with value: 0.635044053375162 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'leaf_size': 19}. Best is trial 11 with value: 0.6864964342969242.
[I 2025-07-11 18:46:20,871] Trial 24 finished with value: 0.6585589988215383 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'leaf_size': 21}. Best is trial 11 with value: 0.6864964342969242.
[I 2025-07-11 18:46:20,872] A new study created in memory with name: no-name-e106c3df-4e30-4023-8b5b-e8165a823bc0

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.03 | R2: 0.66
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.09 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.03 | R2: 0.66

✅ KNN - Mejor R2: 0.69
📋 Parámetros: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 17}

Buscando mejores hiperparámetros para LR...
Fold 1
Fold 2
Fold 3

[I 2025-07-11 18:46:20,948] Trial 0 finished with value: -1.6803594234510673 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 0 with value: -1.6803594234510673.
[I 2025-07-11 18:46:21,035] Trial 1 finished with value: -1.6803594235162334 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 0 with value: -1.6803594234510673.
[I 2025-07-11 18:46:21,112] Trial 2 finished with value: -1.2272481422086603 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 2 with value: -1.2272481422086603.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 5.68 | R2: -1.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 5.68 | R2: -1.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 5.17 | R2: -1.23
Fold 1

[I 2025-07-11 18:46:21,309] Trial 3 finished with value: -1.6803594235162334 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 2 with value: -1.2272481422086603.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 5.68 | R2: -1.68
Fold 1

[I 2025-07-11 18:46:21,513] Trial 4 finished with value: -1.6803594235162334 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 2 with value: -1.2272481422086603.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 5.68 | R2: -1.68
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 18:46:21,621] Trial 5 finished with value: -1.6803594235162334 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 2 with value: -1.2272481422086603.
[I 2025-07-11 18:46:21,717] Trial 6 finished with value: -1.2272481422086883 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 2 with value: -1.2272481422086603.
[I 2025-07-11 18:46:21,797] Trial 7 finished with value: -1.6803594234510673 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 2 with value: -1.2272481422086603.

Fold 5
Running time: 0.1 sec
OOF RMSE: 5.68 | R2: -1.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 5.17 | R2: -1.23
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 5.68 | R2: -1.68
Fold 1

[I 2025-07-11 18:46:21,950] Trial 8 finished with value: -1.6803594235162334 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 2 with value: -1.2272481422086603.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 5.68 | R2: -1.68
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 18:46:22,065] Trial 9 finished with value: -1.6803594235162334 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 2 with value: -1.2272481422086603.
[I 2025-07-11 18:46:22,148] Trial 10 finished with value: -1.2272481422086603 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 2 with value: -1.2272481422086603.
[I 2025-07-11 18:46:22,226] Trial 11 finished with value: -1.2272481422086603 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 2 with value: -1.2272481422086603.

Fold 5
Running time: 0.1 sec
OOF RMSE: 5.68 | R2: -1.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 5.17 | R2: -1.23
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 5.17 | R2: -1.23
Fold 1
Fold 2

[I 2025-07-11 18:46:22,292] Trial 12 finished with value: -1.2272481422086603 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 2 with value: -1.2272481422086603.
[I 2025-07-11 18:46:22,357] Trial 13 finished with value: -1.2272481422086603 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 2 with value: -1.2272481422086603.
[I 2025-07-11 18:46:22,420] Trial 14 finished with value: -1.2272481422086603 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 2 with value: -1.2272481422086603.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 5.17 | R2: -1.23
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 5.17 | R2: -1.23
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 5.17 | R2: -1.23
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 18:46:22,480] Trial 15 finished with value: -1.2272481422086603 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 2 with value: -1.2272481422086603.
[I 2025-07-11 18:46:22,543] Trial 16 finished with value: -1.2272481422086603 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 2 with value: -1.2272481422086603.
[I 2025-07-11 18:46:22,604] Trial 17 finished with value: -1.2272481422086603 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 2 with value: -1.2272481422086603.
[I 2025-07-11 18:46:22,661] Trial 18 finished with value: -1.2272481422086603 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 2 with value: -1.2272481422086603.

Fold 5
Running time: 0.1 sec
OOF RMSE: 5.17 | R2: -1.23
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 5.17 | R2: -1.23
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 5.17 | R2: -1.23
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 5.17 | R2: -1.23
Fold 1

[I 2025-07-11 18:46:22,725] Trial 19 finished with value: -1.2272481422086603 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 2 with value: -1.2272481422086603.
[I 2025-07-11 18:46:22,787] Trial 20 finished with value: -1.2272481422086603 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 2 with value: -1.2272481422086603.
[I 2025-07-11 18:46:22,847] Trial 21 finished with value: -1.2272481422086603 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 2 with value: -1.2272481422086603.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 5.17 | R2: -1.23
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 5.17 | R2: -1.23
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 5.17 | R2: -1.23
Fold 1
Fold 2
Fold 3

[I 2025-07-11 18:46:22,905] Trial 22 finished with value: -1.2272481422086603 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 2 with value: -1.2272481422086603.
[I 2025-07-11 18:46:22,969] Trial 23 finished with value: -1.2272481422086603 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 2 with value: -1.2272481422086603.
[I 2025-07-11 18:46:23,031] Trial 24 finished with value: -1.2272481422086603 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 2 with value: -1.2272481422086603.
[I 2025-07-11 18:46:23,032] A new study created in memory with name: no-name-74e5c50d-a0dc-49d9-94fa-0b3457c13fb1

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 5.17 | R2: -1.23
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 5.17 | R2: -1.23
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 5.17 | R2: -1.23

✅ LR - Mejor R2: -1.23
📋 Parámetros: {'fit_intercept': True, 'positive': True}

Buscando mejores hiperparámetros para RF...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:46:31,682] Trial 0 finished with value: 0.37615561422244326 and parameters: {'n_estimators': 500, 'max_depth': 5, 'min_samples_split': 10, 'min_samples_leaf': 5, 'bootstrap': False}. Best is trial 0 with value: 0.37615561422244326.

Running time: 8.6 sec
OOF RMSE: 2.74 | R2: 0.38
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:46:36,065] Trial 1 finished with value: 0.5231120964214024 and parameters: {'n_estimators': 300, 'max_depth': 14, 'min_samples_split': 8, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 1 with value: 0.5231120964214024.

Running time: 4.4 sec
OOF RMSE: 2.39 | R2: 0.52
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:46:38,594] Trial 2 finished with value: 0.14533194469324717 and parameters: {'n_estimators': 100, 'max_depth': 12, 'min_samples_split': 3, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 1 with value: 0.5231120964214024.

Running time: 2.5 sec
OOF RMSE: 3.20 | R2: 0.15
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:46:45,663] Trial 3 finished with value: 0.14873164434971675 and parameters: {'n_estimators': 300, 'max_depth': 8, 'min_samples_split': 2, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 1 with value: 0.5231120964214024.

Running time: 7.1 sec
OOF RMSE: 3.20 | R2: 0.15
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:46:53,012] Trial 4 finished with value: 0.1464700128899531 and parameters: {'n_estimators': 300, 'max_depth': 9, 'min_samples_split': 6, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 1 with value: 0.5231120964214024.

Running time: 7.3 sec
OOF RMSE: 3.20 | R2: 0.15
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:46:54,558] Trial 5 finished with value: 0.5284724052237317 and parameters: {'n_estimators': 100, 'max_depth': 15, 'min_samples_split': 9, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 5 with value: 0.5284724052237317.

Running time: 1.5 sec
OOF RMSE: 2.38 | R2: 0.53
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:46:59,423] Trial 6 finished with value: 0.5356669250391253 and parameters: {'n_estimators': 300, 'max_depth': 15, 'min_samples_split': 8, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 6 with value: 0.5356669250391253.

Running time: 4.9 sec
OOF RMSE: 2.36 | R2: 0.54
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:47:01,188] Trial 7 finished with value: 0.5523285772129705 and parameters: {'n_estimators': 100, 'max_depth': 8, 'min_samples_split': 5, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 7 with value: 0.5523285772129705.

Running time: 1.8 sec
OOF RMSE: 2.32 | R2: 0.55
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:47:08,537] Trial 8 finished with value: 0.1464700128899531 and parameters: {'n_estimators': 300, 'max_depth': 9, 'min_samples_split': 3, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 7 with value: 0.5523285772129705.

Running time: 7.3 sec
OOF RMSE: 3.20 | R2: 0.15
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:47:10,221] Trial 9 finished with value: 0.5454775364085498 and parameters: {'n_estimators': 100, 'max_depth': 15, 'min_samples_split': 10, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 7 with value: 0.5523285772129705.

Running time: 1.7 sec
OOF RMSE: 2.34 | R2: 0.55
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:47:17,727] Trial 10 finished with value: 0.555793861600608 and parameters: {'n_estimators': 500, 'max_depth': 6, 'min_samples_split': 5, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 10 with value: 0.555793861600608.

Running time: 7.5 sec
OOF RMSE: 2.31 | R2: 0.56
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:47:25,233] Trial 11 finished with value: 0.555793861600608 and parameters: {'n_estimators': 500, 'max_depth': 6, 'min_samples_split': 5, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 10 with value: 0.555793861600608.

Running time: 7.5 sec
OOF RMSE: 2.31 | R2: 0.56
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:47:31,921] Trial 12 finished with value: 0.55561366366272 and parameters: {'n_estimators': 500, 'max_depth': 5, 'min_samples_split': 5, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 10 with value: 0.555793861600608.

Running time: 6.7 sec
OOF RMSE: 2.31 | R2: 0.56
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:47:39,403] Trial 13 finished with value: 0.555793861600608 and parameters: {'n_estimators': 500, 'max_depth': 6, 'min_samples_split': 5, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 10 with value: 0.555793861600608.

Running time: 7.5 sec
OOF RMSE: 2.31 | R2: 0.56
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:47:47,162] Trial 14 finished with value: 0.5491915193263932 and parameters: {'n_estimators': 500, 'max_depth': 7, 'min_samples_split': 7, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 10 with value: 0.555793861600608.

Running time: 7.8 sec
OOF RMSE: 2.33 | R2: 0.55
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:47:56,256] Trial 15 finished with value: 0.5562016754508818 and parameters: {'n_estimators': 500, 'max_depth': 11, 'min_samples_split': 4, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 15 with value: 0.5562016754508818.

Running time: 9.1 sec
OOF RMSE: 2.31 | R2: 0.56
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:48:05,388] Trial 16 finished with value: 0.5562016754508818 and parameters: {'n_estimators': 500, 'max_depth': 11, 'min_samples_split': 3, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 15 with value: 0.5562016754508818.

Running time: 9.1 sec
OOF RMSE: 2.31 | R2: 0.56
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:48:14,507] Trial 17 finished with value: 0.5562016754508818 and parameters: {'n_estimators': 500, 'max_depth': 11, 'min_samples_split': 3, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 15 with value: 0.5562016754508818.

Running time: 9.1 sec
OOF RMSE: 2.31 | R2: 0.56
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:48:23,662] Trial 18 finished with value: 0.5553431135641539 and parameters: {'n_estimators': 500, 'max_depth': 12, 'min_samples_split': 2, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 15 with value: 0.5562016754508818.

Running time: 9.1 sec
OOF RMSE: 2.31 | R2: 0.56
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:48:31,443] Trial 19 finished with value: 0.5363174787987255 and parameters: {'n_estimators': 500, 'max_depth': 13, 'min_samples_split': 4, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 15 with value: 0.5562016754508818.

Running time: 7.8 sec
OOF RMSE: 2.36 | R2: 0.54
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:48:40,459] Trial 20 finished with value: 0.5535119620256568 and parameters: {'n_estimators': 500, 'max_depth': 10, 'min_samples_split': 4, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 15 with value: 0.5562016754508818.

Running time: 9.0 sec
OOF RMSE: 2.32 | R2: 0.55
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:48:49,527] Trial 21 finished with value: 0.5562016754508818 and parameters: {'n_estimators': 500, 'max_depth': 11, 'min_samples_split': 3, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 15 with value: 0.5562016754508818.

Running time: 9.1 sec
OOF RMSE: 2.31 | R2: 0.56
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:48:58,612] Trial 22 finished with value: 0.5562016754508818 and parameters: {'n_estimators': 500, 'max_depth': 11, 'min_samples_split': 4, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 15 with value: 0.5562016754508818.

Running time: 9.1 sec
OOF RMSE: 2.31 | R2: 0.56
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:49:07,670] Trial 23 finished with value: 0.5562016754508818 and parameters: {'n_estimators': 500, 'max_depth': 11, 'min_samples_split': 2, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 15 with value: 0.5562016754508818.

Running time: 9.1 sec
OOF RMSE: 2.31 | R2: 0.56
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:49:15,477] Trial 24 finished with value: 0.5358427717926499 and parameters: {'n_estimators': 500, 'max_depth': 10, 'min_samples_split': 3, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 15 with value: 0.5562016754508818.
[I 2025-07-11 18:49:15,478] A new study created in memory with name: no-name-a99bd9cb-2d91-4077-be02-4f1b8beeb5a8

Running time: 7.8 sec
OOF RMSE: 2.36 | R2: 0.54

✅ RF - Mejor R2: 0.56
📋 Parámetros: {'n_estimators': 500, 'max_depth': 11, 'min_samples_split': 4, 'min_samples_leaf': 2, 'bootstrap': True}

Buscando mejores hiperparámetros para CAT...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:49:23,491] Trial 0 finished with value: 0.655412661507333 and parameters: {'iterations': 500, 'learning_rate': 0.013419755949651281, 'depth': 7, 'l2_leaf_reg': 1.345593360722721}. Best is trial 0 with value: 0.655412661507333.

Running time: 8.0 sec
OOF RMSE: 2.03 | R2: 0.66
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:49:54,428] Trial 1 finished with value: 0.6575464291624719 and parameters: {'iterations': 2000, 'learning_rate': 0.02707200961393809, 'depth': 7, 'l2_leaf_reg': 1.9097937179157793}. Best is trial 1 with value: 0.6575464291624719.

Running time: 30.9 sec
OOF RMSE: 2.03 | R2: 0.66
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:50:10,135] Trial 2 finished with value: 0.6649105608718473 and parameters: {'iterations': 1000, 'learning_rate': 0.07709804649567484, 'depth': 7, 'l2_leaf_reg': 6.227509985211535}. Best is trial 2 with value: 0.6649105608718473.

Running time: 15.7 sec
OOF RMSE: 2.01 | R2: 0.66
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:50:11,655] Trial 3 finished with value: 0.6104573649035379 and parameters: {'iterations': 500, 'learning_rate': 0.012215454134086813, 'depth': 4, 'l2_leaf_reg': 7.091508819915569}. Best is trial 2 with value: 0.6649105608718473.

Running time: 1.5 sec
OOF RMSE: 2.16 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:50:27,341] Trial 4 finished with value: 0.6533634381198914 and parameters: {'iterations': 1000, 'learning_rate': 0.031210679193199406, 'depth': 7, 'l2_leaf_reg': 9.095178499937498}. Best is trial 2 with value: 0.6649105608718473.

Running time: 15.7 sec
OOF RMSE: 2.04 | R2: 0.65
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:50:35,423] Trial 5 finished with value: 0.6477672182090284 and parameters: {'iterations': 500, 'learning_rate': 0.05690486275221815, 'depth': 7, 'l2_leaf_reg': 1.2546541481306746}. Best is trial 2 with value: 0.6649105608718473.

Running time: 8.1 sec
OOF RMSE: 2.06 | R2: 0.65
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:53:06,658] Trial 6 finished with value: 0.6746968953567665 and parameters: {'iterations': 1000, 'learning_rate': 0.010904729218569853, 'depth': 10, 'l2_leaf_reg': 2.3192707687798997}. Best is trial 6 with value: 0.6746968953567665.

Running time: 151.2 sec
OOF RMSE: 1.98 | R2: 0.67
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:53:26,987] Trial 7 finished with value: 0.6672199255692928 and parameters: {'iterations': 500, 'learning_rate': 0.06288879624560079, 'depth': 8, 'l2_leaf_reg': 3.2860008520673616}. Best is trial 6 with value: 0.6746968953567665.

Running time: 20.3 sec
OOF RMSE: 2.00 | R2: 0.67
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:53:35,083] Trial 8 finished with value: 0.6317946817166478 and parameters: {'iterations': 500, 'learning_rate': 0.016547566889552615, 'depth': 7, 'l2_leaf_reg': 7.045111014946463}. Best is trial 6 with value: 0.6746968953567665.

Running time: 8.1 sec
OOF RMSE: 2.10 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 18:58:42,972] Trial 9 finished with value: 0.6561715625529424 and parameters: {'iterations': 2000, 'learning_rate': 0.05187090360339874, 'depth': 10, 'l2_leaf_reg': 3.533988673831503}. Best is trial 6 with value: 0.6746968953567665.

Running time: 307.9 sec
OOF RMSE: 2.03 | R2: 0.66
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:01:15,344] Trial 10 finished with value: 0.6724593216714079 and parameters: {'iterations': 1000, 'learning_rate': 0.02021854515626271, 'depth': 10, 'l2_leaf_reg': 3.8264916555208996}. Best is trial 6 with value: 0.6746968953567665.
[I 2025-07-11 19:01:15,345] A new study created in memory with name: no-name-7dc0abbb-5da6-467a-b7e3-2088317ae780
[I 2025-07-11 19:01:15,497] Trial 0 finished with value: 0.4830702292916095 and parameters: {'alpha': 0.04188256656313815, 'l1_ratio': 0.9449887467368667}. Best is trial 0 with value: 0.4830702292916095.

Running time: 152.4 sec
OOF RMSE: 1.98 | R2: 0.67

✅ CAT - Mejor R2: 0.67
📋 Parámetros: {'iterations': 1000, 'learning_rate': 0.010904729218569853, 'depth': 10, 'l2_leaf_reg': 2.3192707687798997}

Buscando mejores hiperparámetros para EN...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.49 | R2: 0.48
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.951e+01, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.143e+01, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.184e+01, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.575e+00, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.612e+01, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 19:01:15,621] Trial 1 finished with value: 0.40829766022767244 and parameters: {'alpha': 0.004606649184076704, 'l1_ratio': 0.583455780138174}. Best is trial 0 with value: 0.4830702292916095.
[I 2025-07-11 19:01:15,706] Trial 2 finished with value: 0.08956735747169209 and parameters: {'alpha': 6.149576512887162, 'l1_ratio': 0.23400985587658918}. Best is trial 0 with value: 0.4830702292916095.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.67 | R2: 0.41
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.31 | R2: 0.09
Fold 1
Fold 2

[I 2025-07-11 19:01:15,829] Trial 3 finished with value: 0.46862026694504344 and parameters: {'alpha': 0.1038732727415615, 'l1_ratio': 0.09821732312127429}. Best is trial 0 with value: 0.4830702292916095.
[I 2025-07-11 19:01:15,933] Trial 4 finished with value: 0.4641078378005764 and parameters: {'alpha': 0.09214873655015904, 'l1_ratio': 0.9071942507825843}. Best is trial 0 with value: 0.4830702292916095.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.53 | R2: 0.47
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.54 | R2: 0.46
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.828e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.432e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.440e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.801e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.161e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 19:01:16,077] Trial 5 finished with value: 0.0013120801138408744 and parameters: {'alpha': 0.0006027133083066879, 'l1_ratio': 0.04794891479094432}. Best is trial 0 with value: 0.4830702292916095.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.46 | R2: 0.00
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:01:16,171] Trial 6 finished with value: -0.00027817151752640434 and parameters: {'alpha': 7.386146896480727, 'l1_ratio': 0.7181380257361668}. Best is trial 0 with value: 0.4830702292916095.
[I 2025-07-11 19:01:16,330] Trial 7 finished with value: 0.44824236078620794 and parameters: {'alpha': 0.5963668312612758, 'l1_ratio': 0.26488346280238084}. Best is trial 0 with value: 0.4830702292916095.

Running time: 0.1 sec
OOF RMSE: 3.47 | R2: -0.00
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 2.57 | R2: 0.45
Fold 1
Fold 2

[I 2025-07-11 19:01:16,435] Trial 8 finished with value: 0.4755007482486644 and parameters: {'alpha': 0.0547566690382512, 'l1_ratio': 0.9543563562441176}. Best is trial 0 with value: 0.4830702292916095.
[I 2025-07-11 19:01:16,533] Trial 9 finished with value: 0.43364210242066403 and parameters: {'alpha': 0.7969350140408643, 'l1_ratio': 0.3393219106515033}. Best is trial 0 with value: 0.4830702292916095.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.51 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.61 | R2: 0.43
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.667e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.272e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.269e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.608e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.688e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 19:01:16,686] Trial 10 finished with value: -0.3686269674082092 and parameters: {'alpha': 0.00011092163113234007, 'l1_ratio': 0.7548932592364335}. Best is trial 0 with value: 0.4830702292916095.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.156e+00, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.147e+00, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.282e+00, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 4.06 | R2: -0.37
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.131e+00, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.269e+00, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 19:01:16,822] Trial 11 finished with value: 0.49439277928262937 and parameters: {'alpha': 0.010066766130517523, 'l1_ratio': 0.9704186950519328}. Best is trial 11 with value: 0.49439277928262937.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.862e+00, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.501e+00, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.740e+00, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.197e+00, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.520e+01, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 19:01:16,945] Trial 12 finished with value: 0.3536145799803494 and parameters: {'alpha': 0.00621118196412871, 'l1_ratio': 0.9885365044654982}. Best is trial 11 with value: 0.49439277928262937.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.590e+00, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.46 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.79 | R2: 0.35
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.376e+00, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.857e+00, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.030e+00, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.664e+01, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 19:01:17,073] Trial 13 finished with value: 0.38553819263629097 and parameters: {'alpha': 0.005001548491225763, 'l1_ratio': 0.8119397454041556}. Best is trial 11 with value: 0.49439277928262937.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.945e+00, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.101e+00, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.726e+00, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.72 | R2: 0.39
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.634e-01, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 19:01:17,236] Trial 14 finished with value: 0.4807430426566126 and parameters: {'alpha': 0.01311106158204647, 'l1_ratio': 0.5936283815126551}. Best is trial 11 with value: 0.49439277928262937.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.251e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.870e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.759e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.026e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.020e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 19:01:17,369] Trial 15 finished with value: -0.12300505611455548 and parameters: {'alpha': 0.0011892133721613824, 'l1_ratio': 0.8313854840321188}. Best is trial 11 with value: 0.49439277928262937.

Fold 5
Running time: 0.2 sec
OOF RMSE: 2.50 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.67 | R2: -0.12
Fold 1
Fold 2

[I 2025-07-11 19:01:17,464] Trial 16 finished with value: 0.434782396319087 and parameters: {'alpha': 0.6839457324269751, 'l1_ratio': 0.4813667373968643}. Best is trial 11 with value: 0.49439277928262937.
[I 2025-07-11 19:01:17,618] Trial 17 finished with value: 0.47752771143682415 and parameters: {'alpha': 0.023570652048496277, 'l1_ratio': 0.6438390449471902}. Best is trial 11 with value: 0.49439277928262937.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.61 | R2: 0.43
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.51 | R2: 0.48

[I 2025-07-11 19:01:17,726] Trial 18 finished with value: 0.45654200197432093 and parameters: {'alpha': 0.23430532886179722, 'l1_ratio': 0.8763760196076602}. Best is trial 11 with value: 0.49439277928262937.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.860e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.503e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.544e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.56 | R2: 0.46
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.944e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.488e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 19:01:17,871] Trial 19 finished with value: -0.01621589052774075 and parameters: {'alpha': 0.0009057288855082484, 'l1_ratio': 0.4819066656430175}. Best is trial 11 with value: 0.49439277928262937.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.386e+00, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.213e-01, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 19:01:18,040] Trial 20 finished with value: 0.4807548852303807 and parameters: {'alpha': 0.016192887379165435, 'l1_ratio': 0.7200485642663915}. Best is trial 11 with value: 0.49439277928262937.

Fold 5
Running time: 0.1 sec
OOF RMSE: 3.49 | R2: -0.02
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 2.50 | R2: 0.48

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.421e-01, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.473e-01, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 19:01:18,206] Trial 21 finished with value: 0.4797270723689555 and parameters: {'alpha': 0.018241914195353752, 'l1_ratio': 0.7025845938969497}. Best is trial 11 with value: 0.49439277928262937.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 2.50 | R2: 0.48
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.266e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.280e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.264e+01, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.740e+01, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.500e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 19:01:18,351] Trial 22 finished with value: -0.14515905775516735 and parameters: {'alpha': 0.0018187698052505683, 'l1_ratio': 0.9982169578859307}. Best is trial 11 with value: 0.49439277928262937.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.71 | R2: -0.15
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 19:01:18,513] Trial 23 finished with value: 0.47844992150023735 and parameters: {'alpha': 0.03955734665687096, 'l1_ratio': 0.7975185613114654}. Best is trial 11 with value: 0.49439277928262937.
[I 2025-07-11 19:01:18,625] Trial 24 finished with value: 0.45749794015193224 and parameters: {'alpha': 0.19865958710763346, 'l1_ratio': 0.8936467659734082}. Best is trial 11 with value: 0.49439277928262937.
[I 2025-07-11 19:01:18,627] A new study created in memory with name: no-name-94e702fa-8f58-4025-97f2-21fea6caaf8e

Fold 5
Running time: 0.2 sec
OOF RMSE: 2.50 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.55 | R2: 0.46

✅ EN - Mejor R2: 0.49
📋 Parámetros: {'alpha': 0.010066766130517523, 'l1_ratio': 0.9704186950519328}

🔍 Optimizando en C2X_rhow_1x1_depth_lt_1...
Buscando mejores hiperparámetros para XGB...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:01:25,123] Trial 0 finished with value: 0.32246672130130494 and parameters: {'n_estimators': 1000, 'learning_rate': 0.013919934016142445, 'max_depth': 5, 'min_child_weight': 1, 'subsample': 0.7951984272161164, 'colsample_bytree': 0.743140715593741}. Best is trial 0 with value: 0.32246672130130494.

Running time: 6.5 sec
OOF RMSE: 2.85 | R2: 0.32
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:01:29,871] Trial 1 finished with value: 0.3158116595280911 and parameters: {'n_estimators': 500, 'learning_rate': 0.005806758746786633, 'max_depth': 8, 'min_child_weight': 4, 'subsample': 0.85902974193522, 'colsample_bytree': 0.7717756500432721}. Best is trial 0 with value: 0.32246672130130494.

Running time: 4.7 sec
OOF RMSE: 2.87 | R2: 0.32
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:01:37,213] Trial 2 finished with value: 0.28283702828592017 and parameters: {'n_estimators': 1000, 'learning_rate': 0.0075914789522460715, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.8570586013936214, 'colsample_bytree': 0.8838136176929088}. Best is trial 0 with value: 0.32246672130130494.

Running time: 7.3 sec
OOF RMSE: 2.94 | R2: 0.28
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:01:46,986] Trial 3 finished with value: 0.2587370957764562 and parameters: {'n_estimators': 2000, 'learning_rate': 0.008498981078437258, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.7029012675631887, 'colsample_bytree': 0.8057911020225134}. Best is trial 0 with value: 0.32246672130130494.

Running time: 9.8 sec
OOF RMSE: 2.98 | R2: 0.26
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:01:51,483] Trial 4 finished with value: 0.31589532161196876 and parameters: {'n_estimators': 500, 'learning_rate': 0.028148548719115395, 'max_depth': 8, 'min_child_weight': 2, 'subsample': 0.831288984811557, 'colsample_bytree': 0.83546316195691}. Best is trial 0 with value: 0.32246672130130494.

Running time: 4.5 sec
OOF RMSE: 2.87 | R2: 0.32
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:01:57,477] Trial 5 finished with value: 0.33555013400933553 and parameters: {'n_estimators': 500, 'learning_rate': 0.008787153371942635, 'max_depth': 8, 'min_child_weight': 1, 'subsample': 0.950657769262287, 'colsample_bytree': 0.6098251633150886}. Best is trial 5 with value: 0.33555013400933553.

Running time: 6.0 sec
OOF RMSE: 2.83 | R2: 0.34
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:02:02,312] Trial 6 finished with value: 0.26077852941505064 and parameters: {'n_estimators': 500, 'learning_rate': 0.06739438575398678, 'max_depth': 8, 'min_child_weight': 2, 'subsample': 0.9805745243895877, 'colsample_bytree': 0.9563923229727413}. Best is trial 5 with value: 0.33555013400933553.

Running time: 4.8 sec
OOF RMSE: 2.98 | R2: 0.26
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:02:14,125] Trial 7 finished with value: 0.3105448150948644 and parameters: {'n_estimators': 2000, 'learning_rate': 0.015280131826844725, 'max_depth': 5, 'min_child_weight': 1, 'subsample': 0.6771970346050272, 'colsample_bytree': 0.7217965360566251}. Best is trial 5 with value: 0.33555013400933553.

Running time: 11.8 sec
OOF RMSE: 2.88 | R2: 0.31
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:02:16,988] Trial 8 finished with value: 0.29340940140255367 and parameters: {'n_estimators': 500, 'learning_rate': 0.08791857942817562, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.8201841596407053, 'colsample_bytree': 0.6492748293991125}. Best is trial 5 with value: 0.33555013400933553.

Running time: 2.9 sec
OOF RMSE: 2.91 | R2: 0.29
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:02:21,559] Trial 9 finished with value: 0.2761328382286308 and parameters: {'n_estimators': 1000, 'learning_rate': 0.019910393063164743, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.7640515008106877, 'colsample_bytree': 0.6758256348207164}. Best is trial 5 with value: 0.33555013400933553.

Running time: 4.6 sec
OOF RMSE: 2.95 | R2: 0.28
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:02:25,759] Trial 10 finished with value: 0.30066991471520466 and parameters: {'n_estimators': 500, 'learning_rate': 0.03533013178480068, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.9664987089391277, 'colsample_bytree': 0.6016441863464764}. Best is trial 5 with value: 0.33555013400933553.

Running time: 4.2 sec
OOF RMSE: 2.90 | R2: 0.30
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:02:36,027] Trial 11 finished with value: 0.28800218759608 and parameters: {'n_estimators': 1000, 'learning_rate': 0.012208649713982452, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.9190347161002561, 'colsample_bytree': 0.7283276266574118}. Best is trial 5 with value: 0.33555013400933553.

Running time: 10.3 sec
OOF RMSE: 2.93 | R2: 0.29
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:02:42,483] Trial 12 finished with value: 0.3089337421856526 and parameters: {'n_estimators': 1000, 'learning_rate': 0.011409910390191989, 'max_depth': 6, 'min_child_weight': 1, 'subsample': 0.618375365926689, 'colsample_bytree': 0.6081362960063932}. Best is trial 5 with value: 0.33555013400933553.

Running time: 6.5 sec
OOF RMSE: 2.88 | R2: 0.31
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:02:49,997] Trial 13 finished with value: 0.29817064698732065 and parameters: {'n_estimators': 1000, 'learning_rate': 0.0055245929235625425, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.7708315743663581, 'colsample_bytree': 0.6974669104533476}. Best is trial 5 with value: 0.33555013400933553.

Running time: 7.5 sec
OOF RMSE: 2.90 | R2: 0.30
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:03:06,175] Trial 14 finished with value: 0.2947992006747646 and parameters: {'n_estimators': 2000, 'learning_rate': 0.01689858081340932, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.9164812934133509, 'colsample_bytree': 0.9973946059325837}. Best is trial 5 with value: 0.33555013400933553.

Running time: 16.2 sec
OOF RMSE: 2.91 | R2: 0.29
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:03:09,967] Trial 15 finished with value: 0.28268193881361303 and parameters: {'n_estimators': 500, 'learning_rate': 0.041950369711399364, 'max_depth': 6, 'min_child_weight': 1, 'subsample': 0.9067384424027469, 'colsample_bytree': 0.7582731430547871}. Best is trial 5 with value: 0.33555013400933553.

Running time: 3.8 sec
OOF RMSE: 2.94 | R2: 0.28
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:03:21,008] Trial 16 finished with value: 0.32173049782012875 and parameters: {'n_estimators': 1000, 'learning_rate': 0.009564159710612856, 'max_depth': 8, 'min_child_weight': 1, 'subsample': 0.7349020639136462, 'colsample_bytree': 0.8867364523099333}. Best is trial 5 with value: 0.33555013400933553.

Running time: 11.0 sec
OOF RMSE: 2.85 | R2: 0.32
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:03:23,435] Trial 17 finished with value: 0.2717537305926603 and parameters: {'n_estimators': 500, 'learning_rate': 0.02304334621455272, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.7925872231063972, 'colsample_bytree': 0.6636438028438678}. Best is trial 5 with value: 0.33555013400933553.

Running time: 2.4 sec
OOF RMSE: 2.96 | R2: 0.27
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:03:29,513] Trial 18 finished with value: 0.30543772129152713 and parameters: {'n_estimators': 1000, 'learning_rate': 0.015029499088960604, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.6421788308472682, 'colsample_bytree': 0.6404743486339288}. Best is trial 5 with value: 0.33555013400933553.

Running time: 6.1 sec
OOF RMSE: 2.89 | R2: 0.31
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:03:48,876] Trial 19 finished with value: 0.29549982489933047 and parameters: {'n_estimators': 2000, 'learning_rate': 0.00710727514825835, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.8887817350691937, 'colsample_bytree': 0.8477344512329015}. Best is trial 5 with value: 0.33555013400933553.

Running time: 19.4 sec
OOF RMSE: 2.91 | R2: 0.30
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:03:58,900] Trial 20 finished with value: 0.28397564906179185 and parameters: {'n_estimators': 1000, 'learning_rate': 0.010123231251264277, 'max_depth': 8, 'min_child_weight': 2, 'subsample': 0.9418740832236456, 'colsample_bytree': 0.7455960152544848}. Best is trial 5 with value: 0.33555013400933553.

Running time: 10.0 sec
OOF RMSE: 2.93 | R2: 0.28
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:04:10,310] Trial 21 finished with value: 0.31777493999749673 and parameters: {'n_estimators': 1000, 'learning_rate': 0.00988966032806836, 'max_depth': 8, 'min_child_weight': 1, 'subsample': 0.7354274681035123, 'colsample_bytree': 0.9240985027306546}. Best is trial 5 with value: 0.33555013400933553.

Running time: 11.4 sec
OOF RMSE: 2.86 | R2: 0.32
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:04:21,465] Trial 22 finished with value: 0.32037380816795646 and parameters: {'n_estimators': 1000, 'learning_rate': 0.0071002501707417365, 'max_depth': 8, 'min_child_weight': 1, 'subsample': 0.7246260630912664, 'colsample_bytree': 0.9004196079913918}. Best is trial 5 with value: 0.33555013400933553.

Running time: 11.1 sec
OOF RMSE: 2.86 | R2: 0.32
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:04:32,522] Trial 23 finished with value: 0.323482551148102 and parameters: {'n_estimators': 1000, 'learning_rate': 0.014423261601441925, 'max_depth': 8, 'min_child_weight': 1, 'subsample': 0.7553445175623471, 'colsample_bytree': 0.7999596448084431}. Best is trial 5 with value: 0.33555013400933553.

Running time: 11.1 sec
OOF RMSE: 2.85 | R2: 0.32
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:04:42,262] Trial 24 finished with value: 0.31657564343124633 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01386339028656475, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.7973331889535059, 'colsample_bytree': 0.800458840340939}. Best is trial 5 with value: 0.33555013400933553.
[I 2025-07-11 19:04:42,264] A new study created in memory with name: no-name-7f9a676a-2e47-4a7e-880c-b219f5a7dd7c

Running time: 9.7 sec
OOF RMSE: 2.87 | R2: 0.32

✅ XGB - Mejor R2: 0.34
📋 Parámetros: {'n_estimators': 500, 'learning_rate': 0.008787153371942635, 'max_depth': 8, 'min_child_weight': 1, 'subsample': 0.950657769262287, 'colsample_bytree': 0.6098251633150886}

Buscando mejores hiperparámetros para LBM...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:04:42,481] Trial 0 finished with value: 0.14194066702583852 and parameters: {'learning_rate': 0.08110302315395693, 'num_leaves': 60, 'max_depth': 5, 'min_child_samples': 20, 'subsample': 0.7311601395780456, 'colsample_bytree': 0.630326119487848, 'n_estimators': 500}. Best is trial 0 with value: 0.14194066702583852.

Running time: 0.2 sec
OOF RMSE: 3.21 | R2: 0.14
Fold 1
Fold 2
Fold 3

[I 2025-07-11 19:04:42,909] Trial 1 finished with value: 0.28113477144685295 and parameters: {'learning_rate': 0.006892210525544273, 'num_leaves': 40, 'max_depth': 5, 'min_child_samples': 19, 'subsample': 0.7099120608841594, 'colsample_bytree': 0.6892414817201115, 'n_estimators': 1000}. Best is trial 1 with value: 0.28113477144685295.

Fold 4
Fold 5
Running time: 0.4 sec
OOF RMSE: 2.94 | R2: 0.28
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:04:43,593] Trial 2 finished with value: 0.21511813180659267 and parameters: {'learning_rate': 0.020805192549603353, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 5, 'subsample': 0.7172007294457655, 'colsample_bytree': 0.6420598847810061, 'n_estimators': 1000}. Best is trial 1 with value: 0.28113477144685295.

Running time: 0.7 sec
OOF RMSE: 3.07 | R2: 0.22
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:04:43,824] Trial 3 finished with value: 0.221039309757593 and parameters: {'learning_rate': 0.021532419328468996, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 21, 'subsample': 0.617315580900796, 'colsample_bytree': 0.9126965608971325, 'n_estimators': 500}. Best is trial 1 with value: 0.28113477144685295.

Running time: 0.2 sec
OOF RMSE: 3.06 | R2: 0.22
Fold 1
Fold 2
Fold 3

[I 2025-07-11 19:04:44,195] Trial 4 finished with value: 0.24349560062984876 and parameters: {'learning_rate': 0.008840505577769548, 'num_leaves': 20, 'max_depth': 8, 'min_child_samples': 14, 'subsample': 0.8771956230232627, 'colsample_bytree': 0.9286650870012378, 'n_estimators': 500}. Best is trial 1 with value: 0.28113477144685295.

Fold 4
Fold 5
Running time: 0.4 sec
OOF RMSE: 3.02 | R2: 0.24
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 19:04:44,542] Trial 5 finished with value: 0.20437629536001312 and parameters: {'learning_rate': 0.07448641461359416, 'num_leaves': 60, 'max_depth': 7, 'min_child_samples': 7, 'subsample': 0.8106595081737461, 'colsample_bytree': 0.7398475216914823, 'n_estimators': 500}. Best is trial 1 with value: 0.28113477144685295.

Fold 5
Running time: 0.3 sec
OOF RMSE: 3.09 | R2: 0.20
Fold 1
Fold 2
Fold 3

[I 2025-07-11 19:04:44,810] Trial 6 finished with value: 0.11166654794357977 and parameters: {'learning_rate': 0.074097321522356, 'num_leaves': 40, 'max_depth': 7, 'min_child_samples': 25, 'subsample': 0.7061455550123705, 'colsample_bytree': 0.6410946238002037, 'n_estimators': 500}. Best is trial 1 with value: 0.28113477144685295.

Fold 4
Fold 5
Running time: 0.3 sec
OOF RMSE: 3.27 | R2: 0.11
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:04:45,411] Trial 7 finished with value: 0.20802724431173258 and parameters: {'learning_rate': 0.019444149470796968, 'num_leaves': 40, 'max_depth': 6, 'min_child_samples': 5, 'subsample': 0.8959239746820544, 'colsample_bytree': 0.7353319684925295, 'n_estimators': 1000}. Best is trial 1 with value: 0.28113477144685295.

Running time: 0.6 sec
OOF RMSE: 3.08 | R2: 0.21
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 19:04:46,228] Trial 8 finished with value: 0.14220848650577333 and parameters: {'learning_rate': 0.018453954509952193, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 23, 'subsample': 0.6003040941274166, 'colsample_bytree': 0.9071426102697243, 'n_estimators': 2000}. Best is trial 1 with value: 0.28113477144685295.

Fold 5
Running time: 0.8 sec
OOF RMSE: 3.21 | R2: 0.14
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:04:47,404] Trial 9 finished with value: 0.25386207479000944 and parameters: {'learning_rate': 0.02656618467993979, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 9, 'subsample': 0.8016345135700795, 'colsample_bytree': 0.8308595603851519, 'n_estimators': 2000}. Best is trial 1 with value: 0.28113477144685295.

Running time: 1.2 sec
OOF RMSE: 2.99 | R2: 0.25
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:04:47,898] Trial 10 finished with value: 0.2562676594691411 and parameters: {'learning_rate': 0.005570645802228059, 'num_leaves': 80, 'max_depth': 6, 'min_child_samples': 16, 'subsample': 0.9597464567664047, 'colsample_bytree': 0.7300437405385355, 'n_estimators': 1000}. Best is trial 1 with value: 0.28113477144685295.

Running time: 0.5 sec
OOF RMSE: 2.99 | R2: 0.26
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:04:48,404] Trial 11 finished with value: 0.25461158111186677 and parameters: {'learning_rate': 0.005672344624887283, 'num_leaves': 80, 'max_depth': 6, 'min_child_samples': 16, 'subsample': 0.9940186468824679, 'colsample_bytree': 0.730485287136426, 'n_estimators': 1000}. Best is trial 1 with value: 0.28113477144685295.

Running time: 0.5 sec
OOF RMSE: 2.99 | R2: 0.25
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:04:48,945] Trial 12 finished with value: 0.2618924855579472 and parameters: {'learning_rate': 0.00512136968604829, 'num_leaves': 80, 'max_depth': 6, 'min_child_samples': 16, 'subsample': 0.9783618051353608, 'colsample_bytree': 0.7989415896493831, 'n_estimators': 1000}. Best is trial 1 with value: 0.28113477144685295.

Running time: 0.5 sec
OOF RMSE: 2.98 | R2: 0.26
Fold 1
Fold 2
Fold 3

[I 2025-07-11 19:04:49,415] Trial 13 finished with value: 0.23390889173258267 and parameters: {'learning_rate': 0.010507810310444671, 'num_leaves': 80, 'max_depth': 5, 'min_child_samples': 12, 'subsample': 0.681199469752717, 'colsample_bytree': 0.8329730114395184, 'n_estimators': 1000}. Best is trial 1 with value: 0.28113477144685295.

Fold 4
Fold 5
Running time: 0.5 sec
OOF RMSE: 3.03 | R2: 0.23
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 19:04:49,936] Trial 14 finished with value: 0.2663394131797343 and parameters: {'learning_rate': 0.0089815083808552, 'num_leaves': 40, 'max_depth': 6, 'min_child_samples': 19, 'subsample': 0.8735189856886745, 'colsample_bytree': 0.997105219183352, 'n_estimators': 1000}. Best is trial 1 with value: 0.28113477144685295.

Fold 5
Running time: 0.5 sec
OOF RMSE: 2.97 | R2: 0.27
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 19:04:50,434] Trial 15 finished with value: 0.25834580576260757 and parameters: {'learning_rate': 0.01053862654640538, 'num_leaves': 40, 'max_depth': 5, 'min_child_samples': 19, 'subsample': 0.8646159754498445, 'colsample_bytree': 0.9759061134939342, 'n_estimators': 1000}. Best is trial 1 with value: 0.28113477144685295.

Fold 5
Running time: 0.5 sec
OOF RMSE: 2.99 | R2: 0.26
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:04:51,421] Trial 16 finished with value: 0.2224487186312979 and parameters: {'learning_rate': 0.008180691293349416, 'num_leaves': 40, 'max_depth': 6, 'min_child_samples': 18, 'subsample': 0.7477463377605335, 'colsample_bytree': 0.9978338881711863, 'n_estimators': 2000}. Best is trial 1 with value: 0.28113477144685295.

Running time: 1.0 sec
OOF RMSE: 3.06 | R2: 0.22
Fold 1
Fold 2
Fold 3

[I 2025-07-11 19:04:51,890] Trial 17 finished with value: 0.1975785009812242 and parameters: {'learning_rate': 0.013954081674684803, 'num_leaves': 40, 'max_depth': 8, 'min_child_samples': 23, 'subsample': 0.6545613689799737, 'colsample_bytree': 0.6848983086407918, 'n_estimators': 1000}. Best is trial 1 with value: 0.28113477144685295.

Fold 4
Fold 5
Running time: 0.5 sec
OOF RMSE: 3.11 | R2: 0.20
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 19:04:52,341] Trial 18 finished with value: 0.20984323415383355 and parameters: {'learning_rate': 0.03780896724968366, 'num_leaves': 40, 'max_depth': 5, 'min_child_samples': 12, 'subsample': 0.7697214593325475, 'colsample_bytree': 0.7892450740945797, 'n_estimators': 1000}. Best is trial 1 with value: 0.28113477144685295.

Fold 5
Running time: 0.4 sec
OOF RMSE: 3.08 | R2: 0.21
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 19:04:52,881] Trial 19 finished with value: 0.2706273597709635 and parameters: {'learning_rate': 0.0071738143164423685, 'num_leaves': 40, 'max_depth': 6, 'min_child_samples': 22, 'subsample': 0.9253845353709981, 'colsample_bytree': 0.8567304712966229, 'n_estimators': 1000}. Best is trial 1 with value: 0.28113477144685295.

Fold 5
Running time: 0.5 sec
OOF RMSE: 2.96 | R2: 0.27
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:04:53,757] Trial 20 finished with value: 0.07206904109434464 and parameters: {'learning_rate': 0.04076140937164957, 'num_leaves': 40, 'max_depth': 5, 'min_child_samples': 22, 'subsample': 0.9348274182557937, 'colsample_bytree': 0.8625630224527702, 'n_estimators': 2000}. Best is trial 1 with value: 0.28113477144685295.

Running time: 0.9 sec
OOF RMSE: 3.34 | R2: 0.07
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:04:54,254] Trial 21 finished with value: 0.2747230687622011 and parameters: {'learning_rate': 0.007342767417456125, 'num_leaves': 40, 'max_depth': 6, 'min_child_samples': 19, 'subsample': 0.8348706710084404, 'colsample_bytree': 0.9558389800075644, 'n_estimators': 1000}. Best is trial 1 with value: 0.28113477144685295.

Running time: 0.5 sec
OOF RMSE: 2.95 | R2: 0.27
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:04:54,720] Trial 22 finished with value: 0.262617569529052 and parameters: {'learning_rate': 0.006792461190417316, 'num_leaves': 40, 'max_depth': 6, 'min_child_samples': 25, 'subsample': 0.8303239709111422, 'colsample_bytree': 0.9559048612692844, 'n_estimators': 1000}. Best is trial 1 with value: 0.28113477144685295.

Running time: 0.5 sec
OOF RMSE: 2.98 | R2: 0.26
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 19:04:55,263] Trial 23 finished with value: 0.24219290748236733 and parameters: {'learning_rate': 0.012190884033394538, 'num_leaves': 40, 'max_depth': 6, 'min_child_samples': 18, 'subsample': 0.9315148060654501, 'colsample_bytree': 0.8941584604406364, 'n_estimators': 1000}. Best is trial 1 with value: 0.28113477144685295.

Fold 5
Running time: 0.5 sec
OOF RMSE: 3.02 | R2: 0.24
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 19:04:55,787] Trial 24 finished with value: 0.2582543823287391 and parameters: {'learning_rate': 0.0069662520011225205, 'num_leaves': 60, 'max_depth': 7, 'min_child_samples': 21, 'subsample': 0.8407183432059776, 'colsample_bytree': 0.8649592579988763, 'n_estimators': 1000}. Best is trial 1 with value: 0.28113477144685295.
[I 2025-07-11 19:04:55,788] A new study created in memory with name: no-name-e42fc3c7-1c6e-44ed-abfd-e88b639f84e8

Fold 5
Running time: 0.5 sec
OOF RMSE: 2.99 | R2: 0.26

✅ LBM - Mejor R2: 0.28
📋 Parámetros: {'learning_rate': 0.006892210525544273, 'num_leaves': 40, 'max_depth': 5, 'min_child_samples': 19, 'subsample': 0.7099120608841594, 'colsample_bytree': 0.6892414817201115, 'n_estimators': 1000}

Buscando mejores hiperparámetros para MLP...
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

[I 2025-07-11 19:04:57,160] Trial 0 finished with value: 0.28283631452397784 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.01810446702828245, 'learning_rate': 'constant', 'learning_rate_init': 0.0001013232335969991}. Best is trial 0 with value: 0.28283631452397784.

Running time: 1.4 sec
OOF RMSE: 2.94 | R2: 0.28
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 19:04:58,945] Trial 1 finished with value: 0.36565380797447533 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.0002159302728931628, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0006037303076886669}. Best is trial 1 with value: 0.36565380797447533.

Running time: 1.8 sec
OOF RMSE: 2.76 | R2: 0.37
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 19:04:59,665] Trial 2 finished with value: 0.1048091501313706 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'relu', 'solver': 'adam', 'alpha': 9.126480903571697e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.008720561901487213}. Best is trial 1 with value: 0.36565380797447533.

Fold 5
Running time: 0.7 sec
OOF RMSE: 3.28 | R2: 0.10
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3
Fold 4

[I 2025-07-11 19:05:00,615] Trial 3 finished with value: 0.2468071945167437 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0002751756328616631, 'learning_rate': 'constant', 'learning_rate_init': 0.0006711257871742915}. Best is trial 1 with value: 0.36565380797447533.

Fold 5
Running time: 0.9 sec
OOF RMSE: 3.01 | R2: 0.25
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:05:01,690] Trial 4 finished with value: 0.3850571293224623 and parameters: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.002092130370196257, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0003173723684838635}. Best is trial 4 with value: 0.3850571293224623.

Running time: 1.1 sec
OOF RMSE: 2.72 | R2: 0.39
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:05:03,638] Trial 5 finished with value: 0.37751976511492147 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.00019619219890842481, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0029228363287710983}. Best is trial 4 with value: 0.3850571293224623.

Running time: 1.9 sec
OOF RMSE: 2.74 | R2: 0.38
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:05:05,474] Trial 6 finished with value: 0.2559350830062197 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.01217038044756596, 'learning_rate': 'constant', 'learning_rate_init': 0.0021825867232449733}. Best is trial 4 with value: 0.3850571293224623.

Running time: 1.8 sec
OOF RMSE: 2.99 | R2: 0.26
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 19:05:06,497] Trial 7 finished with value: 0.19201021491963255 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0745659533424961, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00036411260556633865}. Best is trial 4 with value: 0.3850571293224623.

Running time: 1.0 sec
OOF RMSE: 3.12 | R2: 0.19
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:05:07,415] Trial 8 finished with value: 0.24203381122681267 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0010526201603304616, 'learning_rate': 'constant', 'learning_rate_init': 0.0007747002911953058}. Best is trial 4 with value: 0.3850571293224623.

Running time: 0.9 sec
OOF RMSE: 3.02 | R2: 0.24
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 19:05:08,124] Trial 9 finished with value: 0.2215988244128444 and parameters: {'hidden_layer_sizes': '50', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 5.367829409992605e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.0005712476427343856}. Best is trial 4 with value: 0.3850571293224623.

Fold 4
Fold 5
Running time: 0.7 sec
OOF RMSE: 3.06 | R2: 0.22
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

[I 2025-07-11 19:05:09,302] Trial 10 finished with value: 0.3858909074640543 and parameters: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'sgd', 'alpha': 1.3166464627164644e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00015837577682767894}. Best is trial 10 with value: 0.3858909074640543.

Running time: 1.2 sec
OOF RMSE: 2.72 | R2: 0.39
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

[I 2025-07-11 19:05:10,773] Trial 11 finished with value: 0.3860323717631451 and parameters: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'sgd', 'alpha': 1.250815504443339e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0001490868230368072}. Best is trial 11 with value: 0.3860323717631451.

Running time: 1.5 sec
OOF RMSE: 2.72 | R2: 0.39
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

[I 2025-07-11 19:05:11,898] Trial 12 finished with value: 0.3869268964844579 and parameters: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'sgd', 'alpha': 1.1523383260027413e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00010424777484592384}. Best is trial 12 with value: 0.3869268964844579.

Running time: 1.1 sec
OOF RMSE: 2.71 | R2: 0.39
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:05:13,045] Trial 13 finished with value: 0.3857690352169597 and parameters: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'sgd', 'alpha': 1.1249992689049275e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0001662382920029652}. Best is trial 12 with value: 0.3869268964844579.

Running time: 1.1 sec
OOF RMSE: 2.72 | R2: 0.39
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

[I 2025-07-11 19:05:14,278] Trial 14 finished with value: 0.3866143406254602 and parameters: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'sgd', 'alpha': 3.2924388927123504e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0001077356225487577}. Best is trial 12 with value: 0.3869268964844579.

Running time: 1.2 sec
OOF RMSE: 2.71 | R2: 0.39
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 19:05:15,518] Trial 15 finished with value: -0.13655102886638315 and parameters: {'hidden_layer_sizes': '50', 'activation': 'relu', 'solver': 'sgd', 'alpha': 4.4646904655203456e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00029741488135056064}. Best is trial 12 with value: 0.3869268964844579.

Fold 5
Running time: 1.2 sec
OOF RMSE: 3.70 | R2: -0.14
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:05:16,564] Trial 16 finished with value: 0.3825921523182133 and parameters: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'sgd', 'alpha': 3.564317271462515e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0016455943405207054}. Best is trial 12 with value: 0.3869268964844579.

Running time: 1.0 sec
OOF RMSE: 2.72 | R2: 0.38
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:05:17,776] Trial 17 finished with value: 0.38652209931040005 and parameters: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.00041299089050620536, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00011803404378498433}. Best is trial 12 with value: 0.3869268964844579.

Running time: 1.2 sec
OOF RMSE: 2.72 | R2: 0.39
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 19:05:19,461] Trial 18 finished with value: 0.3906187283641016 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.003393207856147233, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00021845709203661444}. Best is trial 18 with value: 0.3906187283641016.

Running time: 1.7 sec
OOF RMSE: 2.71 | R2: 0.39
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 19:05:20,582] Trial 19 finished with value: 0.2284915900886988 and parameters: {'hidden_layer_sizes': '50', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.004041854592562319, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0002241384149460658}. Best is trial 18 with value: 0.3906187283641016.

Fold 5
Running time: 1.1 sec
OOF RMSE: 3.04 | R2: 0.23
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:05:21,514] Trial 20 finished with value: 0.2764535592258812 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.007706484644161897, 'learning_rate': 'adaptive', 'learning_rate_init': 0.004734255883953598}. Best is trial 18 with value: 0.3906187283641016.

Running time: 0.9 sec
OOF RMSE: 2.95 | R2: 0.28
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 19:05:23,540] Trial 21 finished with value: 0.3589409127845483 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0008298483737054959, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00010167034947984809}. Best is trial 18 with value: 0.3906187283641016.

Running time: 2.0 sec
OOF RMSE: 2.78 | R2: 0.36
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 19:05:25,331] Trial 22 finished with value: 0.39071670531131875 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 2.7828802828129536e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00021912182016706574}. Best is trial 22 with value: 0.39071670531131875.

Running time: 1.8 sec
OOF RMSE: 2.71 | R2: 0.39
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 19:05:27,035] Trial 23 finished with value: 0.3920622511615264 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0427067431152606, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00022978677348610993}. Best is trial 23 with value: 0.3920622511615264.

Running time: 1.7 sec
OOF RMSE: 2.70 | R2: 0.39
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 19:05:28,610] Trial 24 finished with value: 0.40167915740890925 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.08738054757359731, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00042338382901349093}. Best is trial 24 with value: 0.40167915740890925.
[I 2025-07-11 19:05:28,612] A new study created in memory with name: no-name-3dba3332-0256-4921-a798-6aa05d973efa
[I 2025-07-11 19:05:28,709] Trial 0 finished with value: 0.22158693451559208 and parameters: {'kernel': 'rbf', 'C': 9.54066251582055, 'epsilon': 0.18664152362193945, 'gamma': 'auto'}. Best is trial 0 with value: 0.22158693451559208.
[I 2025-07-11 19:05:28,786] Trial 1 finished with value: -0.025113848742508216 and parameters: {'kernel': 'sigmoid', 'C': 0.18643942116470932, 'epsilon': 0.19704079206538716, 'gamma': 'auto'}. Best is trial 0 with value: 0.22158693451559208.

Running time: 1.6 sec
OOF RMSE: 2.68 | R2: 0.40

✅ MLP - Mejor R2: 0.40
📋 Parámetros: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.08738054757359731, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00042338382901349093}

Buscando mejores hiperparámetros para SVR...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.06 | R2: 0.22
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.51 | R2: -0.03
Fold 1
Fold 2

[I 2025-07-11 19:05:28,860] Trial 2 finished with value: -3.2893909377682506 and parameters: {'kernel': 'sigmoid', 'C': 1.594012722748147, 'epsilon': 0.19386419377546046, 'gamma': 'scale'}. Best is trial 0 with value: 0.22158693451559208.
[I 2025-07-11 19:05:28,954] Trial 3 finished with value: -2.2318213139184744 and parameters: {'kernel': 'sigmoid', 'C': 1.4023223164830687, 'epsilon': 0.11547845009752962, 'gamma': 'scale'}. Best is trial 0 with value: 0.22158693451559208.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 7.18 | R2: -3.29
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 6.23 | R2: -2.23
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:05:29,030] Trial 4 finished with value: 0.23209163447841596 and parameters: {'kernel': 'rbf', 'C': 2.8048150334081203, 'epsilon': 0.09898198594020163, 'gamma': 'scale'}. Best is trial 4 with value: 0.23209163447841596.
[I 2025-07-11 19:05:29,120] Trial 5 finished with value: -12.687944281133007 and parameters: {'kernel': 'sigmoid', 'C': 3.188812596751263, 'epsilon': 0.05852800805406134, 'gamma': 'scale'}. Best is trial 4 with value: 0.23209163447841596.
[I 2025-07-11 19:05:29,214] Trial 6 finished with value: -84.250297197908 and parameters: {'kernel': 'sigmoid', 'C': 4.714319415383589, 'epsilon': 0.1495347356435154, 'gamma': 'auto'}. Best is trial 4 with value: 0.23209163447841596.

Running time: 0.1 sec
OOF RMSE: 3.04 | R2: 0.23
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 12.83 | R2: -12.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 32.01 | R2: -84.25
Fold 1
Fold 2

[I 2025-07-11 19:05:29,282] Trial 7 finished with value: 0.15619641648543992 and parameters: {'kernel': 'rbf', 'C': 1.6547946166564607, 'epsilon': 0.1951819643081184, 'gamma': 'auto'}. Best is trial 4 with value: 0.23209163447841596.
[I 2025-07-11 19:05:29,363] Trial 8 finished with value: -123.42900641373015 and parameters: {'kernel': 'sigmoid', 'C': 9.148784445396538, 'epsilon': 0.1645651249544472, 'gamma': 'scale'}. Best is trial 4 with value: 0.23209163447841596.
[I 2025-07-11 19:05:29,435] Trial 9 finished with value: -6.2550726096497 and parameters: {'kernel': 'sigmoid', 'C': 2.1598493718767013, 'epsilon': 0.10793805806401216, 'gamma': 'scale'}. Best is trial 4 with value: 0.23209163447841596.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.18 | R2: 0.16
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 38.67 | R2: -123.43
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 9.34 | R2: -6.26

[I 2025-07-11 19:05:29,513] Trial 10 finished with value: 0.07354367433687492 and parameters: {'kernel': 'rbf', 'C': 0.44645310505853486, 'epsilon': 0.014694573988462675, 'gamma': 'scale'}. Best is trial 4 with value: 0.23209163447841596.
[I 2025-07-11 19:05:29,595] Trial 11 finished with value: 0.21731199277399305 and parameters: {'kernel': 'rbf', 'C': 8.06055907568584, 'epsilon': 0.07391703052657969, 'gamma': 'auto'}. Best is trial 4 with value: 0.23209163447841596.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.34 | R2: 0.07
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.07 | R2: 0.22
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 19:05:29,668] Trial 12 finished with value: 0.08161854737022745 and parameters: {'kernel': 'rbf', 'C': 0.5813748719527472, 'epsilon': 0.13286163302641674, 'gamma': 'auto'}. Best is trial 4 with value: 0.23209163447841596.
[I 2025-07-11 19:05:29,750] Trial 13 finished with value: 0.19939252331512347 and parameters: {'kernel': 'rbf', 'C': 4.567400119197475, 'epsilon': 0.06904835883416682, 'gamma': 'auto'}. Best is trial 4 with value: 0.23209163447841596.
[I 2025-07-11 19:05:29,830] Trial 14 finished with value: 0.26137096219233313 and parameters: {'kernel': 'rbf', 'C': 4.581306472349494, 'epsilon': 0.0919546832577662, 'gamma': 'scale'}. Best is trial 14 with value: 0.26137096219233313.

Fold 5
Running time: 0.1 sec
OOF RMSE: 3.32 | R2: 0.08
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.10 | R2: 0.20
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.98 | R2: 0.26
Fold 1
Fold 2

[I 2025-07-11 19:05:29,910] Trial 15 finished with value: 0.24389301337144165 and parameters: {'kernel': 'rbf', 'C': 3.404801579354797, 'epsilon': 0.08639482084170742, 'gamma': 'scale'}. Best is trial 14 with value: 0.26137096219233313.
[I 2025-07-11 19:05:30,017] Trial 16 finished with value: 0.1480911692126109 and parameters: {'kernel': 'rbf', 'C': 0.9940379482205328, 'epsilon': 0.037212414520842084, 'gamma': 'scale'}. Best is trial 14 with value: 0.26137096219233313.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.01 | R2: 0.24
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.20 | R2: 0.15
Fold 1
Fold 2
Fold 3

[I 2025-07-11 19:05:30,098] Trial 17 finished with value: 0.26473577207923593 and parameters: {'kernel': 'rbf', 'C': 4.9153255028534595, 'epsilon': 0.08875602317287999, 'gamma': 'scale'}. Best is trial 17 with value: 0.26473577207923593.
[I 2025-07-11 19:05:30,180] Trial 18 finished with value: 0.011066430270533778 and parameters: {'kernel': 'rbf', 'C': 0.14064732921994022, 'epsilon': 0.048688340756284, 'gamma': 'scale'}. Best is trial 17 with value: 0.26473577207923593.
[I 2025-07-11 19:05:30,265] Trial 19 finished with value: 0.2680528496131148 and parameters: {'kernel': 'rbf', 'C': 5.466613012578304, 'epsilon': 0.12555028421839518, 'gamma': 'scale'}. Best is trial 19 with value: 0.2680528496131148.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.97 | R2: 0.26
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.45 | R2: 0.01
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.97 | R2: 0.27

[I 2025-07-11 19:05:30,342] Trial 20 finished with value: 0.1323215141241233 and parameters: {'kernel': 'rbf', 'C': 0.7866325569547837, 'epsilon': 0.12575869399493295, 'gamma': 'scale'}. Best is trial 19 with value: 0.2680528496131148.
[I 2025-07-11 19:05:30,425] Trial 21 finished with value: 0.2682434263555906 and parameters: {'kernel': 'rbf', 'C': 5.53763902631098, 'epsilon': 0.09352166200975094, 'gamma': 'scale'}. Best is trial 21 with value: 0.2682434263555906.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.23 | R2: 0.13
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.97 | R2: 0.27
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 19:05:30,502] Trial 22 finished with value: 0.2699959441970263 and parameters: {'kernel': 'rbf', 'C': 5.949895723535186, 'epsilon': 0.14187731031175363, 'gamma': 'scale'}. Best is trial 22 with value: 0.2699959441970263.
[I 2025-07-11 19:05:30,585] Trial 23 finished with value: 0.27034196467704896 and parameters: {'kernel': 'rbf', 'C': 6.422502928128339, 'epsilon': 0.14508589676307573, 'gamma': 'scale'}. Best is trial 23 with value: 0.27034196467704896.
[I 2025-07-11 19:05:30,664] Trial 24 finished with value: 0.2702829335573578 and parameters: {'kernel': 'rbf', 'C': 5.944413412882829, 'epsilon': 0.1514297031328753, 'gamma': 'scale'}. Best is trial 23 with value: 0.27034196467704896.
[I 2025-07-11 19:05:30,665] A new study created in memory with name: no-name-fbffc4fa-a2ef-4e33-903e-992abb73b66a

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.96 | R2: 0.27
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.96 | R2: 0.27
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.96 | R2: 0.27

✅ SVR - Mejor R2: 0.27
📋 Parámetros: {'kernel': 'rbf', 'C': 6.422502928128339, 'epsilon': 0.14508589676307573, 'gamma': 'scale'}

Buscando mejores hiperparámetros para KNN...
Fold 1
Fold 2

[I 2025-07-11 19:05:30,727] Trial 0 finished with value: 0.37198538274985116 and parameters: {'n_neighbors': 15, 'weights': 'uniform', 'leaf_size': 21}. Best is trial 0 with value: 0.37198538274985116.
[I 2025-07-11 19:05:30,793] Trial 1 finished with value: 0.37198538274985116 and parameters: {'n_neighbors': 15, 'weights': 'uniform', 'leaf_size': 37}. Best is trial 0 with value: 0.37198538274985116.
[I 2025-07-11 19:05:30,855] Trial 2 finished with value: 0.39831590226843117 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'leaf_size': 32}. Best is trial 2 with value: 0.39831590226843117.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.75 | R2: 0.37
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.75 | R2: 0.37
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.69 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 19:05:30,913] Trial 3 finished with value: 0.4197459411864398 and parameters: {'n_neighbors': 6, 'weights': 'uniform', 'leaf_size': 39}. Best is trial 3 with value: 0.4197459411864398.
[I 2025-07-11 19:05:31,019] Trial 4 finished with value: 0.3751335350563484 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'leaf_size': 18}. Best is trial 3 with value: 0.4197459411864398.
[I 2025-07-11 19:05:31,089] Trial 5 finished with value: 0.39672582662084843 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'leaf_size': 19}. Best is trial 3 with value: 0.4197459411864398.

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.64 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.74 | R2: 0.38
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.69 | R2: 0.40
Fold 1

[I 2025-07-11 19:05:31,149] Trial 6 finished with value: 0.4197459411864398 and parameters: {'n_neighbors': 6, 'weights': 'uniform', 'leaf_size': 15}. Best is trial 3 with value: 0.4197459411864398.
[I 2025-07-11 19:05:31,212] Trial 7 finished with value: 0.4185582926348079 and parameters: {'n_neighbors': 7, 'weights': 'uniform', 'leaf_size': 15}. Best is trial 3 with value: 0.4197459411864398.
[I 2025-07-11 19:05:31,273] Trial 8 finished with value: 0.3894852204516984 and parameters: {'n_neighbors': 11, 'weights': 'distance', 'leaf_size': 37}. Best is trial 3 with value: 0.4197459411864398.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.64 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.64 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.71 | R2: 0.39
Fold 1
Fold 2
Fold 3

[I 2025-07-11 19:05:31,332] Trial 9 finished with value: 0.39920819214623804 and parameters: {'n_neighbors': 9, 'weights': 'distance', 'leaf_size': 14}. Best is trial 3 with value: 0.4197459411864398.
[I 2025-07-11 19:05:31,409] Trial 10 finished with value: 0.37649097794396924 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'leaf_size': 28}. Best is trial 3 with value: 0.4197459411864398.
[I 2025-07-11 19:05:31,482] Trial 11 finished with value: 0.41465246135569633 and parameters: {'n_neighbors': 5, 'weights': 'uniform', 'leaf_size': 25}. Best is trial 3 with value: 0.4197459411864398.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.69 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.74 | R2: 0.38
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.65 | R2: 0.41
Fold 1
Fold 2

[I 2025-07-11 19:05:31,549] Trial 12 finished with value: 0.40783792324810186 and parameters: {'n_neighbors': 9, 'weights': 'uniform', 'leaf_size': 10}. Best is trial 3 with value: 0.4197459411864398.
[I 2025-07-11 19:05:31,624] Trial 13 finished with value: 0.39071553700294137 and parameters: {'n_neighbors': 11, 'weights': 'uniform', 'leaf_size': 40}. Best is trial 3 with value: 0.4197459411864398.
[I 2025-07-11 19:05:31,693] Trial 14 finished with value: 0.4185582926348079 and parameters: {'n_neighbors': 7, 'weights': 'uniform', 'leaf_size': 25}. Best is trial 3 with value: 0.4197459411864398.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.67 | R2: 0.41
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.71 | R2: 0.39
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.64 | R2: 0.42
Fold 1
Fold 2

[I 2025-07-11 19:05:31,762] Trial 15 finished with value: 0.37649097794396924 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'leaf_size': 31}. Best is trial 3 with value: 0.4197459411864398.
[I 2025-07-11 19:05:31,844] Trial 16 finished with value: 0.41465246135569633 and parameters: {'n_neighbors': 5, 'weights': 'uniform', 'leaf_size': 10}. Best is trial 3 with value: 0.4197459411864398.
[I 2025-07-11 19:05:31,914] Trial 17 finished with value: 0.39071553700294137 and parameters: {'n_neighbors': 11, 'weights': 'uniform', 'leaf_size': 23}. Best is trial 3 with value: 0.4197459411864398.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.74 | R2: 0.38
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.65 | R2: 0.41
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.71 | R2: 0.39
Fold 1

[I 2025-07-11 19:05:31,983] Trial 18 finished with value: 0.40783792324810186 and parameters: {'n_neighbors': 9, 'weights': 'uniform', 'leaf_size': 31}. Best is trial 3 with value: 0.4197459411864398.
[I 2025-07-11 19:05:32,099] Trial 19 finished with value: 0.4015386663856393 and parameters: {'n_neighbors': 8, 'weights': 'uniform', 'leaf_size': 14}. Best is trial 3 with value: 0.4197459411864398.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.67 | R2: 0.41
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.68 | R2: 0.40
Fold 1
Fold 2
Fold 3

[I 2025-07-11 19:05:32,168] Trial 20 finished with value: 0.41465246135569633 and parameters: {'n_neighbors': 5, 'weights': 'uniform', 'leaf_size': 35}. Best is trial 3 with value: 0.4197459411864398.
[I 2025-07-11 19:05:32,241] Trial 21 finished with value: 0.4185582926348079 and parameters: {'n_neighbors': 7, 'weights': 'uniform', 'leaf_size': 15}. Best is trial 3 with value: 0.4197459411864398.
[I 2025-07-11 19:05:32,314] Trial 22 finished with value: 0.4197459411864398 and parameters: {'n_neighbors': 6, 'weights': 'uniform', 'leaf_size': 17}. Best is trial 3 with value: 0.4197459411864398.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.65 | R2: 0.41
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.64 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.64 | R2: 0.42
Fold 1
Fold 2

[I 2025-07-11 19:05:32,380] Trial 23 finished with value: 0.4197459411864398 and parameters: {'n_neighbors': 6, 'weights': 'uniform', 'leaf_size': 18}. Best is trial 3 with value: 0.4197459411864398.
[I 2025-07-11 19:05:32,451] Trial 24 finished with value: 0.4229103691269427 and parameters: {'n_neighbors': 4, 'weights': 'uniform', 'leaf_size': 12}. Best is trial 24 with value: 0.4229103691269427.
[I 2025-07-11 19:05:32,452] A new study created in memory with name: no-name-1e93f59c-f1d2-45b2-89fa-738c0893cb50
[I 2025-07-11 19:05:32,513] Trial 0 finished with value: 0.27320075499097507 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: 0.27320075499097507.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.64 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.63 | R2: 0.42

✅ KNN - Mejor R2: 0.42
📋 Parámetros: {'n_neighbors': 4, 'weights': 'uniform', 'leaf_size': 12}

Buscando mejores hiperparámetros para LR...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.96 | R2: 0.27
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 19:05:32,571] Trial 1 finished with value: 0.27320075499097507 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: 0.27320075499097507.
[I 2025-07-11 19:05:32,652] Trial 2 finished with value: -1.489875157569569 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 0 with value: 0.27320075499097507.

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.96 | R2: 0.27
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 5.47 | R2: -1.49
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 19:05:32,786] Trial 3 finished with value: -1.48987515770928 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 0 with value: 0.27320075499097507.
[I 2025-07-11 19:05:32,871] Trial 4 finished with value: -1.48987515770928 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 0 with value: 0.27320075499097507.

Fold 5
Running time: 0.1 sec
OOF RMSE: 5.47 | R2: -1.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 5.47 | R2: -1.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec

[I 2025-07-11 19:05:32,972] Trial 5 finished with value: -1.48987515770928 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 0 with value: 0.27320075499097507.
[I 2025-07-11 19:05:33,062] Trial 6 finished with value: -1.48987515770928 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 0 with value: 0.27320075499097507.
[I 2025-07-11 19:05:33,143] Trial 7 finished with value: 0.27320075499097507 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: 0.27320075499097507.

OOF RMSE: 5.47 | R2: -1.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 5.47 | R2: -1.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.96 | R2: 0.27
Fold 1
Fold 2

[I 2025-07-11 19:05:33,219] Trial 8 finished with value: -1.489875157569569 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 0 with value: 0.27320075499097507.
[I 2025-07-11 19:05:33,328] Trial 9 finished with value: 0.27320075499097507 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: 0.27320075499097507.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 5.47 | R2: -1.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.96 | R2: 0.27
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 19:05:33,394] Trial 10 finished with value: 0.27320075499097507 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: 0.27320075499097507.
[I 2025-07-11 19:05:33,457] Trial 11 finished with value: 0.27320075499097507 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: 0.27320075499097507.
[I 2025-07-11 19:05:33,522] Trial 12 finished with value: 0.27320075499097507 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: 0.27320075499097507.
[I 2025-07-11 19:05:33,579] Trial 13 finished with value: 0.27320075499097507 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: 0.27320075499097507.

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.96 | R2: 0.27
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.96 | R2: 0.27
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.96 | R2: 0.27
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.96 | R2: 0.27
Fold 1

[I 2025-07-11 19:05:33,642] Trial 14 finished with value: 0.27320075499097507 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: 0.27320075499097507.
[I 2025-07-11 19:05:33,705] Trial 15 finished with value: 0.27320075499097507 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: 0.27320075499097507.
[I 2025-07-11 19:05:33,765] Trial 16 finished with value: 0.27320075499097507 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: 0.27320075499097507.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.96 | R2: 0.27
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.96 | R2: 0.27
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.96 | R2: 0.27
Fold 1
Fold 2
Fold 3

[I 2025-07-11 19:05:33,824] Trial 17 finished with value: 0.27320075499097507 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: 0.27320075499097507.
[I 2025-07-11 19:05:33,889] Trial 18 finished with value: 0.2611578393390517 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 0 with value: 0.27320075499097507.
[I 2025-07-11 19:05:33,952] Trial 19 finished with value: 0.27320075499097507 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: 0.27320075499097507.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.96 | R2: 0.27
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.98 | R2: 0.26
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.96 | R2: 0.27
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:05:34,012] Trial 20 finished with value: 0.27320075499097507 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: 0.27320075499097507.
[I 2025-07-11 19:05:34,075] Trial 21 finished with value: 0.27320075499097507 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: 0.27320075499097507.
[I 2025-07-11 19:05:34,133] Trial 22 finished with value: 0.27320075499097507 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: 0.27320075499097507.
[I 2025-07-11 19:05:34,191] Trial 23 finished with value: 0.27320075499097507 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: 0.27320075499097507.

Running time: 0.1 sec
OOF RMSE: 2.96 | R2: 0.27
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.96 | R2: 0.27
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.96 | R2: 0.27
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.96 | R2: 0.27
Fold 1
Fold 2

[I 2025-07-11 19:05:34,252] Trial 24 finished with value: 0.27320075499097507 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: 0.27320075499097507.
[I 2025-07-11 19:05:34,253] A new study created in memory with name: no-name-bd389d18-09a2-40fb-bb4e-ff3e2b8bf9b6

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.96 | R2: 0.27

✅ LR - Mejor R2: 0.27
📋 Parámetros: {'fit_intercept': True, 'positive': True}

Buscando mejores hiperparámetros para RF...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:05:48,406] Trial 0 finished with value: 0.07424371832941423 and parameters: {'n_estimators': 500, 'max_depth': 13, 'min_samples_split': 4, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 0 with value: 0.07424371832941423.

Running time: 14.1 sec
OOF RMSE: 3.34 | R2: 0.07
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:05:54,157] Trial 1 finished with value: 0.15645031574936918 and parameters: {'n_estimators': 300, 'max_depth': 6, 'min_samples_split': 8, 'min_samples_leaf': 5, 'bootstrap': False}. Best is trial 1 with value: 0.15645031574936918.

Running time: 5.7 sec
OOF RMSE: 3.18 | R2: 0.16
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:06:02,591] Trial 2 finished with value: 0.3683843086586841 and parameters: {'n_estimators': 500, 'max_depth': 15, 'min_samples_split': 10, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 2 with value: 0.3683843086586841.

Running time: 8.4 sec
OOF RMSE: 2.76 | R2: 0.37
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:06:08,173] Trial 3 finished with value: 0.36049838936906475 and parameters: {'n_estimators': 300, 'max_depth': 12, 'min_samples_split': 3, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 2 with value: 0.3683843086586841.

Running time: 5.6 sec
OOF RMSE: 2.77 | R2: 0.36
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:06:14,545] Trial 4 finished with value: 0.1581458019954718 and parameters: {'n_estimators': 300, 'max_depth': 6, 'min_samples_split': 5, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 2 with value: 0.3683843086586841.

Running time: 6.4 sec
OOF RMSE: 3.18 | R2: 0.16
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:06:23,307] Trial 5 finished with value: 0.3577662097971962 and parameters: {'n_estimators': 500, 'max_depth': 8, 'min_samples_split': 4, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 2 with value: 0.3683843086586841.

Running time: 8.8 sec
OOF RMSE: 2.78 | R2: 0.36
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:06:25,596] Trial 6 finished with value: 0.18881642207280613 and parameters: {'n_estimators': 100, 'max_depth': 8, 'min_samples_split': 7, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 2 with value: 0.3683843086586841.

Running time: 2.3 sec
OOF RMSE: 3.12 | R2: 0.19
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:06:34,809] Trial 7 finished with value: 0.11274625497176016 and parameters: {'n_estimators': 500, 'max_depth': 5, 'min_samples_split': 2, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 2 with value: 0.3683843086586841.

Running time: 9.2 sec
OOF RMSE: 3.27 | R2: 0.11
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:06:47,623] Trial 8 finished with value: 0.1515025418646675 and parameters: {'n_estimators': 500, 'max_depth': 14, 'min_samples_split': 5, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 2 with value: 0.3683843086586841.

Running time: 12.8 sec
OOF RMSE: 3.19 | R2: 0.15
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:06:54,379] Trial 9 finished with value: 0.09998027431805567 and parameters: {'n_estimators': 300, 'max_depth': 9, 'min_samples_split': 10, 'min_samples_leaf': 4, 'bootstrap': False}. Best is trial 2 with value: 0.3683843086586841.

Running time: 6.7 sec
OOF RMSE: 3.29 | R2: 0.10
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:06:55,938] Trial 10 finished with value: 0.3328096388861511 and parameters: {'n_estimators': 100, 'max_depth': 15, 'min_samples_split': 10, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 2 with value: 0.3683843086586841.

Running time: 1.6 sec
OOF RMSE: 2.83 | R2: 0.33
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:07:01,446] Trial 11 finished with value: 0.35796838571945866 and parameters: {'n_estimators': 300, 'max_depth': 11, 'min_samples_split': 2, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 2 with value: 0.3683843086586841.

Running time: 5.5 sec
OOF RMSE: 2.78 | R2: 0.36
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:07:10,120] Trial 12 finished with value: 0.3672729712980076 and parameters: {'n_estimators': 500, 'max_depth': 12, 'min_samples_split': 8, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 2 with value: 0.3683843086586841.

Running time: 8.7 sec
OOF RMSE: 2.76 | R2: 0.37
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:07:19,358] Trial 13 finished with value: 0.3674018737449982 and parameters: {'n_estimators': 500, 'max_depth': 15, 'min_samples_split': 8, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 2 with value: 0.3683843086586841.

Running time: 9.2 sec
OOF RMSE: 2.76 | R2: 0.37
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:07:28,417] Trial 14 finished with value: 0.3709656460928962 and parameters: {'n_estimators': 500, 'max_depth': 15, 'min_samples_split': 9, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 14 with value: 0.3709656460928962.

Running time: 9.1 sec
OOF RMSE: 2.75 | R2: 0.37
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:07:37,426] Trial 15 finished with value: 0.3710408099436384 and parameters: {'n_estimators': 500, 'max_depth': 14, 'min_samples_split': 9, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 15 with value: 0.3710408099436384.

Running time: 9.0 sec
OOF RMSE: 2.75 | R2: 0.37
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:07:46,448] Trial 16 finished with value: 0.3721450337859482 and parameters: {'n_estimators': 500, 'max_depth': 13, 'min_samples_split': 9, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 16 with value: 0.3721450337859482.

Running time: 9.0 sec
OOF RMSE: 2.75 | R2: 0.37
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:07:48,332] Trial 17 finished with value: 0.33713779326291793 and parameters: {'n_estimators': 100, 'max_depth': 13, 'min_samples_split': 7, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 16 with value: 0.3721450337859482.

Running time: 1.9 sec
OOF RMSE: 2.82 | R2: 0.34
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:07:56,108] Trial 18 finished with value: 0.35182224153160235 and parameters: {'n_estimators': 500, 'max_depth': 10, 'min_samples_split': 9, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 16 with value: 0.3721450337859482.

Running time: 7.8 sec
OOF RMSE: 2.79 | R2: 0.35
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:08:04,433] Trial 19 finished with value: 0.3539633123359843 and parameters: {'n_estimators': 500, 'max_depth': 13, 'min_samples_split': 6, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 16 with value: 0.3721450337859482.

Running time: 8.3 sec
OOF RMSE: 2.79 | R2: 0.35
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:08:06,241] Trial 20 finished with value: 0.34889811802277915 and parameters: {'n_estimators': 100, 'max_depth': 11, 'min_samples_split': 9, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 16 with value: 0.3721450337859482.

Running time: 1.8 sec
OOF RMSE: 2.80 | R2: 0.35
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:08:15,308] Trial 21 finished with value: 0.3710408099436384 and parameters: {'n_estimators': 500, 'max_depth': 14, 'min_samples_split': 9, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 16 with value: 0.3721450337859482.

Running time: 9.1 sec
OOF RMSE: 2.75 | R2: 0.37
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:08:24,659] Trial 22 finished with value: 0.36572343091782267 and parameters: {'n_estimators': 500, 'max_depth': 14, 'min_samples_split': 7, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 16 with value: 0.3721450337859482.

Running time: 9.3 sec
OOF RMSE: 2.76 | R2: 0.37
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:08:33,700] Trial 23 finished with value: 0.3710408099436384 and parameters: {'n_estimators': 500, 'max_depth': 14, 'min_samples_split': 9, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 16 with value: 0.3721450337859482.

Running time: 9.0 sec
OOF RMSE: 2.75 | R2: 0.37
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:08:42,334] Trial 24 finished with value: 0.3672729712980076 and parameters: {'n_estimators': 500, 'max_depth': 12, 'min_samples_split': 8, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 16 with value: 0.3721450337859482.
[I 2025-07-11 19:08:42,335] A new study created in memory with name: no-name-f63621be-c5c5-4023-b6f8-fde7a1a824be

Running time: 8.6 sec
OOF RMSE: 2.76 | R2: 0.37

✅ RF - Mejor R2: 0.37
📋 Parámetros: {'n_estimators': 500, 'max_depth': 13, 'min_samples_split': 9, 'min_samples_leaf': 1, 'bootstrap': True}

Buscando mejores hiperparámetros para CAT...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:08:49,740] Trial 0 finished with value: 0.31897699021986714 and parameters: {'iterations': 1000, 'learning_rate': 0.052112402358740165, 'depth': 6, 'l2_leaf_reg': 2.5348765107494167}. Best is trial 0 with value: 0.31897699021986714.

Running time: 7.4 sec
OOF RMSE: 2.86 | R2: 0.32
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:09:33,814] Trial 1 finished with value: 0.34756955357169206 and parameters: {'iterations': 500, 'learning_rate': 0.02653937370310581, 'depth': 9, 'l2_leaf_reg': 8.170955875106767}. Best is trial 1 with value: 0.34756955357169206.

Running time: 44.1 sec
OOF RMSE: 2.80 | R2: 0.35
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:09:37,470] Trial 2 finished with value: 0.3462714726113377 and parameters: {'iterations': 500, 'learning_rate': 0.0320774445349761, 'depth': 6, 'l2_leaf_reg': 4.762021285444474}. Best is trial 1 with value: 0.34756955357169206.

Running time: 3.7 sec
OOF RMSE: 2.80 | R2: 0.35
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:12:40,147] Trial 3 finished with value: 0.3567237823059012 and parameters: {'iterations': 2000, 'learning_rate': 0.09301480867482831, 'depth': 9, 'l2_leaf_reg': 1.074842653687934}. Best is trial 3 with value: 0.3567237823059012.

Running time: 182.7 sec
OOF RMSE: 2.78 | R2: 0.36
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:12:41,758] Trial 4 finished with value: 0.3528043730183814 and parameters: {'iterations': 500, 'learning_rate': 0.014325141460022846, 'depth': 4, 'l2_leaf_reg': 3.9190529190397716}. Best is trial 3 with value: 0.3567237823059012.

Running time: 1.6 sec
OOF RMSE: 2.79 | R2: 0.35
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:13:12,464] Trial 5 finished with value: 0.332107573769472 and parameters: {'iterations': 2000, 'learning_rate': 0.02014397328594301, 'depth': 7, 'l2_leaf_reg': 3.2798895039215865}. Best is trial 3 with value: 0.3567237823059012.

Running time: 30.7 sec
OOF RMSE: 2.83 | R2: 0.33
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:14:27,099] Trial 6 finished with value: 0.34340070644867837 and parameters: {'iterations': 500, 'learning_rate': 0.02595933873869959, 'depth': 10, 'l2_leaf_reg': 4.614058915692695}. Best is trial 3 with value: 0.3567237823059012.

Running time: 74.6 sec
OOF RMSE: 2.81 | R2: 0.34
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:14:31,953] Trial 7 finished with value: 0.3414409934828663 and parameters: {'iterations': 1000, 'learning_rate': 0.0170364979000892, 'depth': 5, 'l2_leaf_reg': 7.93593894054184}. Best is trial 3 with value: 0.3567237823059012.

Running time: 4.8 sec
OOF RMSE: 2.81 | R2: 0.34
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:14:34,460] Trial 8 finished with value: 0.3020232777129708 and parameters: {'iterations': 500, 'learning_rate': 0.041525393673431145, 'depth': 5, 'l2_leaf_reg': 9.204631779841096}. Best is trial 3 with value: 0.3567237823059012.

Running time: 2.5 sec
OOF RMSE: 2.90 | R2: 0.30
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:14:40,965] Trial 9 finished with value: 0.3331840130839322 and parameters: {'iterations': 2000, 'learning_rate': 0.03428870130723815, 'depth': 4, 'l2_leaf_reg': 9.590295701728818}. Best is trial 3 with value: 0.3567237823059012.

Running time: 6.5 sec
OOF RMSE: 2.83 | R2: 0.33
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:17:43,966] Trial 10 finished with value: 0.34057079690497694 and parameters: {'iterations': 2000, 'learning_rate': 0.08148717931629856, 'depth': 9, 'l2_leaf_reg': 1.0183518473441493}. Best is trial 3 with value: 0.3567237823059012.

Running time: 183.0 sec
OOF RMSE: 2.82 | R2: 0.34
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:19:04,141] Trial 11 finished with value: 0.351061450858992 and parameters: {'iterations': 2000, 'learning_rate': 0.011006465502160709, 'depth': 8, 'l2_leaf_reg': 1.3062463405608655}. Best is trial 3 with value: 0.3567237823059012.
[I 2025-07-11 19:19:04,142] A new study created in memory with name: no-name-b4f8cc5d-471b-4bce-9949-ca78f0b86ed9
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.142e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.179e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.222e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.847e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.346e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 19:19:04,268] Trial 0 finished with value: 0.27795223905418676 and parameters: {'alpha': 0.00011522708865029567, 'l1_ratio': 0.8229250831283761}. Best is trial 0 with value: 0.27795223905418676.

Running time: 80.2 sec
OOF RMSE: 2.79 | R2: 0.35

✅ CAT - Mejor R2: 0.36
📋 Parámetros: {'iterations': 2000, 'learning_rate': 0.09301480867482831, 'depth': 9, 'l2_leaf_reg': 1.074842653687934}

Buscando mejores hiperparámetros para EN...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.95 | R2: 0.28
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:19:04,356] Trial 1 finished with value: 0.3573461229862297 and parameters: {'alpha': 0.23730217575782037, 'l1_ratio': 0.9131811050146191}. Best is trial 1 with value: 0.3573461229862297.
[I 2025-07-11 19:19:04,451] Trial 2 finished with value: 0.3647311767822874 and parameters: {'alpha': 0.6440735615760935, 'l1_ratio': 0.5655350934531589}. Best is trial 2 with value: 0.3647311767822874.

Running time: 0.1 sec
OOF RMSE: 2.78 | R2: 0.36
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.76 | R2: 0.36
Fold 1
Fold 2

[I 2025-07-11 19:19:04,727] Trial 3 finished with value: 0.3525749171187369 and parameters: {'alpha': 0.10485409928884451, 'l1_ratio': 0.017294502374255227}. Best is trial 2 with value: 0.3647311767822874.

Fold 3
Fold 4
Fold 5
Running time: 0.3 sec
OOF RMSE: 2.79 | R2: 0.35
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.858e+00, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.121e+01, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.153e+01, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.605e+01, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.289e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 19:19:04,875] Trial 4 finished with value: 0.3312031463177342 and parameters: {'alpha': 0.0042296409051852625, 'l1_ratio': 0.9981070376618155}. Best is trial 2 with value: 0.3647311767822874.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.146e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.060e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.83 | R2: 0.33
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.692e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.310e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.821e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 19:19:05,037] Trial 5 finished with value: 0.2986624416582653 and parameters: {'alpha': 0.0009319594661239928, 'l1_ratio': 0.731979890422158}. Best is trial 2 with value: 0.3647311767822874.
[I 2025-07-11 19:19:05,168] Trial 6 finished with value: 0.4291672822857987 and parameters: {'alpha': 0.029341247037709236, 'l1_ratio': 0.764010792925208}. Best is trial 6 with value: 0.4291672822857987.

Fold 5
Running time: 0.2 sec
OOF RMSE: 2.90 | R2: 0.30
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.62 | R2: 0.43
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.633e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.992e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.108e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.705e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.243e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 19:19:05,382] Trial 7 finished with value: 0.2816192974225077 and parameters: {'alpha': 0.0002874108628096355, 'l1_ratio': 0.7895124142080526}. Best is trial 6 with value: 0.4291672822857987.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 2.94 | R2: 0.28
Fold 1

[I 2025-07-11 19:19:05,510] Trial 8 finished with value: 0.3515618567444643 and parameters: {'alpha': 0.3311349587171213, 'l1_ratio': 0.6985375723808456}. Best is trial 6 with value: 0.4291672822857987.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.383e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.827e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.79 | R2: 0.35
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.007e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.594e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.123e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 19:19:05,662] Trial 9 finished with value: 0.2830445722031203 and parameters: {'alpha': 0.000404077688871333, 'l1_ratio': 0.8309023463074506}. Best is trial 6 with value: 0.4291672822857987.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.312e+00, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.352e+00, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.658e+01, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 19:19:05,796] Trial 10 finished with value: 0.4260022355957086 and parameters: {'alpha': 0.01506367312756872, 'l1_ratio': 0.31279782326431227}. Best is trial 6 with value: 0.4291672822857987.

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.94 | R2: 0.28
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.63 | R2: 0.43
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.540e+00, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.449e+01, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.105e+01, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.395e+00, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.933e+01, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 19:19:05,955] Trial 11 finished with value: 0.4261665025620809 and parameters: {'alpha': 0.009004026222765995, 'l1_ratio': 0.30555738917129055}. Best is trial 6 with value: 0.4291672822857987.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.309e-01, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.734e-01, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 2.63 | R2: 0.43
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.337e-01, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 19:19:06,091] Trial 12 finished with value: 0.42157843685164864 and parameters: {'alpha': 0.019268218765876918, 'l1_ratio': 0.3631170114859592}. Best is trial 6 with value: 0.4291672822857987.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.322e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.510e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.906e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.732e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.954e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 19:19:06,241] Trial 13 finished with value: 0.4001489610405723 and parameters: {'alpha': 0.00437234460399905, 'l1_ratio': 0.1291767373339997}. Best is trial 6 with value: 0.4291672822857987.

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.64 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.68 | R2: 0.40
Fold 1

[I 2025-07-11 19:19:06,345] Trial 14 finished with value: -0.00027817151752640434 and parameters: {'alpha': 8.5408958022015, 'l1_ratio': 0.5400902677486356}. Best is trial 6 with value: 0.4291672822857987.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.501e+01, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.144e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.47 | R2: -0.00
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.084e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.395e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.017e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 19:19:06,508] Trial 15 finished with value: 0.39610301233314316 and parameters: {'alpha': 0.0041145457581132795, 'l1_ratio': 0.3201430804376969}. Best is trial 6 with value: 0.4291672822857987.
[I 2025-07-11 19:19:06,628] Trial 16 finished with value: 0.39353686425756307 and parameters: {'alpha': 0.06996406860472042, 'l1_ratio': 0.4509953477296517}. Best is trial 6 with value: 0.4291672822857987.

Fold 5
Running time: 0.2 sec
OOF RMSE: 2.69 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.70 | R2: 0.39
Fold 1
Fold 2
Fold 3

[I 2025-07-11 19:19:06,736] Trial 17 finished with value: 0.34930437266641523 and parameters: {'alpha': 1.491099236544623, 'l1_ratio': 0.18931763114404213}. Best is trial 6 with value: 0.4291672822857987.
[I 2025-07-11 19:19:06,850] Trial 18 finished with value: 0.4240772979601505 and parameters: {'alpha': 0.034141758393393826, 'l1_ratio': 0.648266272345617}. Best is trial 6 with value: 0.4291672822857987.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.80 | R2: 0.35
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.63 | R2: 0.42
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.103e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.855e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.700e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.454e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.089e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 19:19:07,002] Trial 19 finished with value: 0.3610421767812486 and parameters: {'alpha': 0.0021382477102920862, 'l1_ratio': 0.21176115056514191}. Best is trial 6 with value: 0.4291672822857987.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.288e-01, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.740e+00, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.77 | R2: 0.36
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.935e+00, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.518e+01, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 19:19:07,168] Trial 20 finished with value: 0.4274021001031526 and parameters: {'alpha': 0.012501626622058221, 'l1_ratio': 0.42264469199950544}. Best is trial 6 with value: 0.4291672822857987.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.053e+00, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.256e+00, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.319e+01, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 19:19:07,334] Trial 21 finished with value: 0.42801579279942337 and parameters: {'alpha': 0.012783171419970004, 'l1_ratio': 0.49955903242735594}. Best is trial 6 with value: 0.4291672822857987.

Fold 5
Running time: 0.2 sec
OOF RMSE: 2.62 | R2: 0.43
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 2.62 | R2: 0.43

[I 2025-07-11 19:19:07,445] Trial 22 finished with value: 0.407491539292106 and parameters: {'alpha': 0.0512631694404022, 'l1_ratio': 0.45383215673664973}. Best is trial 6 with value: 0.4291672822857987.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.332e-01, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.155e+00, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.746e+00, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.67 | R2: 0.41
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.344e+00, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 19:19:07,579] Trial 23 finished with value: 0.4288224177973443 and parameters: {'alpha': 0.010530221063458776, 'l1_ratio': 0.636574110974242}. Best is trial 6 with value: 0.4291672822857987.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.746e+01, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.060e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.676e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.749e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.364e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 19:19:07,738] Trial 24 finished with value: 0.3267644200798223 and parameters: {'alpha': 0.0016887038399966026, 'l1_ratio': 0.614116690274277}. Best is trial 6 with value: 0.4291672822857987.
[I 2025-07-11 19:19:07,743] A new study created in memory with name: no-name-c6dfc8b2-b3da-4c58-be6e-51e37f13089a

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.62 | R2: 0.43
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 2.84 | R2: 0.33

✅ EN - Mejor R2: 0.43
📋 Parámetros: {'alpha': 0.029341247037709236, 'l1_ratio': 0.764010792925208}

🔍 Optimizando en C2RCC_rhown_1x1_depth_lt_1...
Buscando mejores hiperparámetros para XGB...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:19:15,577] Trial 0 finished with value: 0.6418892900738487 and parameters: {'n_estimators': 1000, 'learning_rate': 0.023707566143447444, 'max_depth': 8, 'min_child_weight': 4, 'subsample': 0.6176670947882931, 'colsample_bytree': 0.8748551934666176}. Best is trial 0 with value: 0.6418892900738487.

Running time: 7.8 sec
OOF RMSE: 2.07 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:19:18,184] Trial 1 finished with value: 0.5948923971428921 and parameters: {'n_estimators': 500, 'learning_rate': 0.06161351935492724, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.975098793489181, 'colsample_bytree': 0.6723704480933805}. Best is trial 0 with value: 0.6418892900738487.

Running time: 2.6 sec
OOF RMSE: 2.21 | R2: 0.59
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:19:21,968] Trial 2 finished with value: 0.5729222731110122 and parameters: {'n_estimators': 500, 'learning_rate': 0.0925732888830163, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.6430627475459693, 'colsample_bytree': 0.8390035531474545}. Best is trial 0 with value: 0.6418892900738487.

Running time: 3.8 sec
OOF RMSE: 2.27 | R2: 0.57
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:19:24,990] Trial 3 finished with value: 0.5589948185871748 and parameters: {'n_estimators': 500, 'learning_rate': 0.07961818070658686, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.8011982690599333, 'colsample_bytree': 0.7517852555759441}. Best is trial 0 with value: 0.6418892900738487.

Running time: 3.0 sec
OOF RMSE: 2.30 | R2: 0.56
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:19:28,141] Trial 4 finished with value: 0.6295232666798056 and parameters: {'n_estimators': 500, 'learning_rate': 0.00663708157102222, 'max_depth': 8, 'min_child_weight': 4, 'subsample': 0.8118032865724907, 'colsample_bytree': 0.6585017461580661}. Best is trial 0 with value: 0.6418892900738487.

Running time: 3.1 sec
OOF RMSE: 2.11 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:19:34,698] Trial 5 finished with value: 0.5355327817533171 and parameters: {'n_estimators': 1000, 'learning_rate': 0.05909928704445398, 'max_depth': 8, 'min_child_weight': 2, 'subsample': 0.7483229572262748, 'colsample_bytree': 0.7108000002212254}. Best is trial 0 with value: 0.6418892900738487.

Running time: 6.6 sec
OOF RMSE: 2.36 | R2: 0.54
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:19:41,352] Trial 6 finished with value: 0.5976880802415276 and parameters: {'n_estimators': 1000, 'learning_rate': 0.03287513338172295, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.909700540630971, 'colsample_bytree': 0.6710928286720306}. Best is trial 0 with value: 0.6418892900738487.

Running time: 6.6 sec
OOF RMSE: 2.20 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:19:48,779] Trial 7 finished with value: 0.5595754417445501 and parameters: {'n_estimators': 1000, 'learning_rate': 0.00820186805382883, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.9187968431997391, 'colsample_bytree': 0.647653094037926}. Best is trial 0 with value: 0.6418892900738487.

Running time: 7.4 sec
OOF RMSE: 2.30 | R2: 0.56
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:19:53,282] Trial 8 finished with value: 0.5678495395245315 and parameters: {'n_estimators': 500, 'learning_rate': 0.0065224451668022725, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.7616576499314283, 'colsample_bytree': 0.7116657014213238}. Best is trial 0 with value: 0.6418892900738487.

Running time: 4.5 sec
OOF RMSE: 2.28 | R2: 0.57
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:19:55,756] Trial 9 finished with value: 0.5733990505957138 and parameters: {'n_estimators': 500, 'learning_rate': 0.013992798942017715, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.8468796737275011, 'colsample_bytree': 0.740383052506814}. Best is trial 0 with value: 0.6418892900738487.

Running time: 2.5 sec
OOF RMSE: 2.26 | R2: 0.57
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:20:11,258] Trial 10 finished with value: 0.5998765756814055 and parameters: {'n_estimators': 2000, 'learning_rate': 0.024252929424220995, 'max_depth': 8, 'min_child_weight': 3, 'subsample': 0.6173041961542617, 'colsample_bytree': 0.9659457877704274}. Best is trial 0 with value: 0.6418892900738487.

Running time: 15.5 sec
OOF RMSE: 2.19 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:20:25,365] Trial 11 finished with value: 0.6184488104445104 and parameters: {'n_estimators': 2000, 'learning_rate': 0.013925630960780191, 'max_depth': 8, 'min_child_weight': 4, 'subsample': 0.6974965652565169, 'colsample_bytree': 0.8678454138623617}. Best is trial 0 with value: 0.6418892900738487.

Running time: 14.1 sec
OOF RMSE: 2.14 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:20:33,736] Trial 12 finished with value: 0.6307553976816263 and parameters: {'n_estimators': 1000, 'learning_rate': 0.012790178723980916, 'max_depth': 8, 'min_child_weight': 4, 'subsample': 0.6819752318884469, 'colsample_bytree': 0.9241068419454761}. Best is trial 0 with value: 0.6418892900738487.

Running time: 8.4 sec
OOF RMSE: 2.11 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:20:41,782] Trial 13 finished with value: 0.6275551211836633 and parameters: {'n_estimators': 1000, 'learning_rate': 0.014091506538864283, 'max_depth': 8, 'min_child_weight': 4, 'subsample': 0.683495875631142, 'colsample_bytree': 0.9492256547288542}. Best is trial 0 with value: 0.6418892900738487.

Running time: 8.0 sec
OOF RMSE: 2.12 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:20:46,138] Trial 14 finished with value: 0.6207435332828599 and parameters: {'n_estimators': 1000, 'learning_rate': 0.03738814374544568, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.6110264861896271, 'colsample_bytree': 0.9040314944257587}. Best is trial 0 with value: 0.6418892900738487.

Running time: 4.3 sec
OOF RMSE: 2.13 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:20:53,917] Trial 15 finished with value: 0.6209294274991997 and parameters: {'n_estimators': 1000, 'learning_rate': 0.018989032856374485, 'max_depth': 8, 'min_child_weight': 4, 'subsample': 0.6802980696771628, 'colsample_bytree': 0.8033424532092284}. Best is trial 0 with value: 0.6418892900738487.

Running time: 7.8 sec
OOF RMSE: 2.13 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:21:01,644] Trial 16 finished with value: 0.5597672651407664 and parameters: {'n_estimators': 1000, 'learning_rate': 0.010178457038448604, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.7293295569205837, 'colsample_bytree': 0.9117535064722977}. Best is trial 0 with value: 0.6418892900738487.

Running time: 7.7 sec
OOF RMSE: 2.30 | R2: 0.56
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:21:09,762] Trial 17 finished with value: 0.5894035728800788 and parameters: {'n_estimators': 1000, 'learning_rate': 0.02531447394658731, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.656652653281422, 'colsample_bytree': 0.9981813795628536}. Best is trial 0 with value: 0.6418892900738487.

Running time: 8.1 sec
OOF RMSE: 2.22 | R2: 0.59
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:21:21,306] Trial 18 finished with value: 0.6301893391236346 and parameters: {'n_estimators': 2000, 'learning_rate': 0.03969308900293742, 'max_depth': 8, 'min_child_weight': 4, 'subsample': 0.6026101617291049, 'colsample_bytree': 0.600788565944731}. Best is trial 0 with value: 0.6418892900738487.

Running time: 11.5 sec
OOF RMSE: 2.11 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:21:28,848] Trial 19 finished with value: 0.6003910977862031 and parameters: {'n_estimators': 1000, 'learning_rate': 0.00505525326972553, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.7216658372422655, 'colsample_bytree': 0.8494410894511185}. Best is trial 0 with value: 0.6418892900738487.

Running time: 7.5 sec
OOF RMSE: 2.19 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:21:36,473] Trial 20 finished with value: 0.6310108628809208 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01738436782330458, 'max_depth': 8, 'min_child_weight': 4, 'subsample': 0.6394232241987713, 'colsample_bytree': 0.9000896829098121}. Best is trial 0 with value: 0.6418892900738487.

Running time: 7.6 sec
OOF RMSE: 2.11 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:21:43,668] Trial 21 finished with value: 0.633204532110091 and parameters: {'n_estimators': 1000, 'learning_rate': 0.018205200307540578, 'max_depth': 8, 'min_child_weight': 4, 'subsample': 0.6467746824878817, 'colsample_bytree': 0.8922613849634484}. Best is trial 0 with value: 0.6418892900738487.

Running time: 7.2 sec
OOF RMSE: 2.10 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:21:51,753] Trial 22 finished with value: 0.6327214796679133 and parameters: {'n_estimators': 1000, 'learning_rate': 0.019237398364359864, 'max_depth': 8, 'min_child_weight': 4, 'subsample': 0.6416957655100303, 'colsample_bytree': 0.8808987404526746}. Best is trial 0 with value: 0.6418892900738487.

Running time: 8.1 sec
OOF RMSE: 2.10 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:21:59,433] Trial 23 finished with value: 0.6263293459535639 and parameters: {'n_estimators': 1000, 'learning_rate': 0.026116984924102412, 'max_depth': 8, 'min_child_weight': 4, 'subsample': 0.6495497198442004, 'colsample_bytree': 0.8117337092052923}. Best is trial 0 with value: 0.6418892900738487.

Running time: 7.7 sec
OOF RMSE: 2.12 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:22:07,127] Trial 24 finished with value: 0.5863429857667461 and parameters: {'n_estimators': 1000, 'learning_rate': 0.019110416706504145, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.7096761876602158, 'colsample_bytree': 0.8749064896046646}. Best is trial 0 with value: 0.6418892900738487.
[I 2025-07-11 19:22:07,128] A new study created in memory with name: no-name-65ea2288-d4b5-4d29-a380-a0be77c36659

Running time: 7.7 sec
OOF RMSE: 2.23 | R2: 0.59

✅ XGB - Mejor R2: 0.64
📋 Parámetros: {'n_estimators': 1000, 'learning_rate': 0.023707566143447444, 'max_depth': 8, 'min_child_weight': 4, 'subsample': 0.6176670947882931, 'colsample_bytree': 0.8748551934666176}

Buscando mejores hiperparámetros para LBM...
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 19:22:07,401] Trial 0 finished with value: 0.5436751676418959 and parameters: {'learning_rate': 0.05815422869144914, 'num_leaves': 80, 'max_depth': 6, 'min_child_samples': 19, 'subsample': 0.7305875804069586, 'colsample_bytree': 0.9940175248354866, 'n_estimators': 500}. Best is trial 0 with value: 0.5436751676418959.

Fold 5
Running time: 0.3 sec
OOF RMSE: 2.34 | R2: 0.54
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:22:07,898] Trial 1 finished with value: 0.4715259349222761 and parameters: {'learning_rate': 0.04105800089601696, 'num_leaves': 40, 'max_depth': 6, 'min_child_samples': 14, 'subsample': 0.9922343716871902, 'colsample_bytree': 0.9206876732891958, 'n_estimators': 1000}. Best is trial 0 with value: 0.5436751676418959.

Running time: 0.5 sec
OOF RMSE: 2.52 | R2: 0.47
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 19:22:08,420] Trial 2 finished with value: 0.5233142352084585 and parameters: {'learning_rate': 0.025185769493489284, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 12, 'subsample': 0.9996804912316778, 'colsample_bytree': 0.9959097068268757, 'n_estimators': 1000}. Best is trial 0 with value: 0.5436751676418959.

Fold 5
Running time: 0.5 sec
OOF RMSE: 2.39 | R2: 0.52
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:22:09,246] Trial 3 finished with value: 0.5765934216985216 and parameters: {'learning_rate': 0.008982594269937617, 'num_leaves': 40, 'max_depth': 7, 'min_child_samples': 25, 'subsample': 0.960781640440255, 'colsample_bytree': 0.6222891432497816, 'n_estimators': 2000}. Best is trial 3 with value: 0.5765934216985216.

Running time: 0.8 sec
OOF RMSE: 2.26 | R2: 0.58
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 19:22:10,077] Trial 4 finished with value: 0.5677291632483026 and parameters: {'learning_rate': 0.03412463221254879, 'num_leaves': 40, 'max_depth': 5, 'min_child_samples': 22, 'subsample': 0.6806005731160214, 'colsample_bytree': 0.9599238482254968, 'n_estimators': 2000}. Best is trial 3 with value: 0.5765934216985216.

Fold 5
Running time: 0.8 sec
OOF RMSE: 2.28 | R2: 0.57
Fold 1

[I 2025-07-11 19:22:10,302] Trial 5 finished with value: 0.4577167134159945 and parameters: {'learning_rate': 0.0061325047800776964, 'num_leaves': 40, 'max_depth': 5, 'min_child_samples': 25, 'subsample': 0.8229700740484897, 'colsample_bytree': 0.9512446176976725, 'n_estimators': 500}. Best is trial 3 with value: 0.5765934216985216.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 2.55 | R2: 0.46
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:22:11,254] Trial 6 finished with value: 0.5483478592674077 and parameters: {'learning_rate': 0.011951249719850954, 'num_leaves': 40, 'max_depth': 6, 'min_child_samples': 20, 'subsample': 0.811747182063956, 'colsample_bytree': 0.9036247670487996, 'n_estimators': 2000}. Best is trial 3 with value: 0.5765934216985216.

Running time: 0.9 sec
OOF RMSE: 2.33 | R2: 0.55
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:22:12,630] Trial 7 finished with value: 0.6182636301882485 and parameters: {'learning_rate': 0.04305237340159763, 'num_leaves': 80, 'max_depth': 7, 'min_child_samples': 6, 'subsample': 0.9453258860915392, 'colsample_bytree': 0.8629418922304548, 'n_estimators': 2000}. Best is trial 7 with value: 0.6182636301882485.

Running time: 1.4 sec
OOF RMSE: 2.14 | R2: 0.62
Fold 1
Fold 2
Fold 3

[I 2025-07-11 19:22:13,028] Trial 8 finished with value: 0.5330676927954974 and parameters: {'learning_rate': 0.027618612334447526, 'num_leaves': 20, 'max_depth': 8, 'min_child_samples': 5, 'subsample': 0.925291639428934, 'colsample_bytree': 0.7017777811334316, 'n_estimators': 500}. Best is trial 7 with value: 0.6182636301882485.

Fold 4
Fold 5
Running time: 0.4 sec
OOF RMSE: 2.37 | R2: 0.53
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:22:13,604] Trial 9 finished with value: 0.5807559489122016 and parameters: {'learning_rate': 0.09352758305192894, 'num_leaves': 20, 'max_depth': 8, 'min_child_samples': 18, 'subsample': 0.902095295798827, 'colsample_bytree': 0.7697569865142302, 'n_estimators': 1000}. Best is trial 7 with value: 0.6182636301882485.

Running time: 0.6 sec
OOF RMSE: 2.24 | R2: 0.58
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:22:14,957] Trial 10 finished with value: 0.5156319641464147 and parameters: {'learning_rate': 0.015410715368252344, 'num_leaves': 80, 'max_depth': 7, 'min_child_samples': 5, 'subsample': 0.6005213831458259, 'colsample_bytree': 0.8245436014101925, 'n_estimators': 2000}. Best is trial 7 with value: 0.6182636301882485.

Running time: 1.3 sec
OOF RMSE: 2.41 | R2: 0.52
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 19:22:15,629] Trial 11 finished with value: 0.5533311929024523 and parameters: {'learning_rate': 0.0997593031067838, 'num_leaves': 60, 'max_depth': 8, 'min_child_samples': 10, 'subsample': 0.901840677081682, 'colsample_bytree': 0.8031419057737803, 'n_estimators': 1000}. Best is trial 7 with value: 0.6182636301882485.

Fold 5
Running time: 0.7 sec
OOF RMSE: 2.32 | R2: 0.55
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:22:16,200] Trial 12 finished with value: 0.5575562880293222 and parameters: {'learning_rate': 0.09491382310555498, 'num_leaves': 20, 'max_depth': 8, 'min_child_samples': 17, 'subsample': 0.8765698968905414, 'colsample_bytree': 0.737524945028152, 'n_estimators': 1000}. Best is trial 7 with value: 0.6182636301882485.

Running time: 0.6 sec
OOF RMSE: 2.31 | R2: 0.56
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 19:22:16,811] Trial 13 finished with value: 0.5743178772657951 and parameters: {'learning_rate': 0.05666043182543071, 'num_leaves': 80, 'max_depth': 7, 'min_child_samples': 9, 'subsample': 0.8648136844318878, 'colsample_bytree': 0.8423246333735747, 'n_estimators': 1000}. Best is trial 7 with value: 0.6182636301882485.

Fold 5
Running time: 0.6 sec
OOF RMSE: 2.26 | R2: 0.57
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:22:17,992] Trial 14 finished with value: 0.5244153343200095 and parameters: {'learning_rate': 0.05952939248698766, 'num_leaves': 60, 'max_depth': 8, 'min_child_samples': 15, 'subsample': 0.9232714930451397, 'colsample_bytree': 0.7400310697680158, 'n_estimators': 2000}. Best is trial 7 with value: 0.6182636301882485.

Running time: 1.2 sec
OOF RMSE: 2.39 | R2: 0.52
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:22:19,273] Trial 15 finished with value: 0.6084139181970789 and parameters: {'learning_rate': 0.07170925457634052, 'num_leaves': 80, 'max_depth': 7, 'min_child_samples': 8, 'subsample': 0.7639289416937509, 'colsample_bytree': 0.8660168211496987, 'n_estimators': 2000}. Best is trial 7 with value: 0.6182636301882485.

Running time: 1.3 sec
OOF RMSE: 2.17 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:22:20,477] Trial 16 finished with value: 0.6146216004685674 and parameters: {'learning_rate': 0.018609343819324633, 'num_leaves': 80, 'max_depth': 7, 'min_child_samples': 8, 'subsample': 0.7539976258654806, 'colsample_bytree': 0.8692715743745897, 'n_estimators': 2000}. Best is trial 7 with value: 0.6182636301882485.

Running time: 1.2 sec
OOF RMSE: 2.15 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:22:21,702] Trial 17 finished with value: 0.6136767112160759 and parameters: {'learning_rate': 0.01725826798032224, 'num_leaves': 80, 'max_depth': 7, 'min_child_samples': 7, 'subsample': 0.6904486468253468, 'colsample_bytree': 0.8590748583618887, 'n_estimators': 2000}. Best is trial 7 with value: 0.6182636301882485.

Running time: 1.2 sec
OOF RMSE: 2.15 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:22:22,875] Trial 18 finished with value: 0.5622328428423478 and parameters: {'learning_rate': 0.0193758370062504, 'num_leaves': 80, 'max_depth': 7, 'min_child_samples': 11, 'subsample': 0.7563638668842323, 'colsample_bytree': 0.8857605989534773, 'n_estimators': 2000}. Best is trial 7 with value: 0.6182636301882485.

Running time: 1.2 sec
OOF RMSE: 2.29 | R2: 0.56
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:22:24,022] Trial 19 finished with value: 0.6158540451258891 and parameters: {'learning_rate': 0.04112589813257043, 'num_leaves': 80, 'max_depth': 6, 'min_child_samples': 7, 'subsample': 0.8353929223707433, 'colsample_bytree': 0.7793033132212484, 'n_estimators': 2000}. Best is trial 7 with value: 0.6182636301882485.

Running time: 1.1 sec
OOF RMSE: 2.15 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 19:22:24,839] Trial 20 finished with value: 0.5243698819723424 and parameters: {'learning_rate': 0.03874377173413793, 'num_leaves': 80, 'max_depth': 5, 'min_child_samples': 13, 'subsample': 0.847008131036731, 'colsample_bytree': 0.6469782738302765, 'n_estimators': 2000}. Best is trial 7 with value: 0.6182636301882485.

Fold 5
Running time: 0.8 sec
OOF RMSE: 2.39 | R2: 0.52
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:22:25,957] Trial 21 finished with value: 0.6102906547435281 and parameters: {'learning_rate': 0.031204236263763292, 'num_leaves': 80, 'max_depth': 6, 'min_child_samples': 7, 'subsample': 0.7802110919735885, 'colsample_bytree': 0.7802238022058844, 'n_estimators': 2000}. Best is trial 7 with value: 0.6182636301882485.

Running time: 1.1 sec
OOF RMSE: 2.16 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:22:27,594] Trial 22 finished with value: 0.5120244065559889 and parameters: {'learning_rate': 0.04294566946516146, 'num_leaves': 80, 'max_depth': 7, 'min_child_samples': 5, 'subsample': 0.7076571966251284, 'colsample_bytree': 0.8130048625584215, 'n_estimators': 2000}. Best is trial 7 with value: 0.6182636301882485.

Running time: 1.6 sec
OOF RMSE: 2.42 | R2: 0.51
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:22:28,629] Trial 23 finished with value: 0.6185207688374038 and parameters: {'learning_rate': 0.022336430019759105, 'num_leaves': 80, 'max_depth': 6, 'min_child_samples': 7, 'subsample': 0.6483167071869289, 'colsample_bytree': 0.6755878887231603, 'n_estimators': 2000}. Best is trial 23 with value: 0.6185207688374038.

Running time: 1.0 sec
OOF RMSE: 2.14 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:22:29,585] Trial 24 finished with value: 0.578495300527712 and parameters: {'learning_rate': 0.02448877120401576, 'num_leaves': 60, 'max_depth': 6, 'min_child_samples': 10, 'subsample': 0.6360496344125233, 'colsample_bytree': 0.6764844526311047, 'n_estimators': 2000}. Best is trial 23 with value: 0.6185207688374038.
[I 2025-07-11 19:22:29,586] A new study created in memory with name: no-name-0f2bb3b5-23b8-44af-a53b-c2556a441b09

Running time: 1.0 sec
OOF RMSE: 2.25 | R2: 0.58

✅ LBM - Mejor R2: 0.62
📋 Parámetros: {'learning_rate': 0.022336430019759105, 'num_leaves': 80, 'max_depth': 6, 'min_child_samples': 7, 'subsample': 0.6483167071869289, 'colsample_bytree': 0.6755878887231603, 'n_estimators': 2000}

Buscando mejores hiperparámetros para MLP...
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

[I 2025-07-11 19:22:32,578] Trial 0 finished with value: 0.33744904087466676 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 7.699554908528592e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00015942336368495808}. Best is trial 0 with value: 0.33744904087466676.

Running time: 3.0 sec
OOF RMSE: 2.82 | R2: 0.34
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:22:33,825] Trial 1 finished with value: 0.5527092840208384 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'adam', 'alpha': 6.898548202996747e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.0037885966281391223}. Best is trial 1 with value: 0.5527092840208384.

Running time: 1.2 sec
OOF RMSE: 2.32 | R2: 0.55
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 19:22:35,099] Trial 2 finished with value: 0.3476442670537113 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.00021655635839024334, 'learning_rate': 'adaptive', 'learning_rate_init': 0.001413584447052556}. Best is trial 1 with value: 0.5527092840208384.

Fold 4
Fold 5
Running time: 1.3 sec
OOF RMSE: 2.80 | R2: 0.35
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

[I 2025-07-11 19:22:37,049] Trial 3 finished with value: 0.42511314109258147 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.000663771815898524, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0002368293371809254}. Best is trial 1 with value: 0.5527092840208384.

Running time: 1.9 sec
OOF RMSE: 2.63 | R2: 0.43
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

[I 2025-07-11 19:22:38,453] Trial 4 finished with value: 0.3887329116656624 and parameters: {'hidden_layer_sizes': '50', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.01855382467693144, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00413271962448333}. Best is trial 1 with value: 0.5527092840208384.

Fold 5
Running time: 1.4 sec
OOF RMSE: 2.71 | R2: 0.39
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 19:22:39,300] Trial 5 finished with value: 0.42601973975974494 and parameters: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.004802786927429515, 'learning_rate': 'constant', 'learning_rate_init': 0.002468750224141294}. Best is trial 1 with value: 0.5527092840208384.

Running time: 0.8 sec
OOF RMSE: 2.63 | R2: 0.43
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 19:22:41,143] Trial 6 finished with value: 0.5803798553788246 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.00015418141431207437, 'learning_rate': 'constant', 'learning_rate_init': 0.00844693900265532}. Best is trial 6 with value: 0.5803798553788246.

Running time: 1.8 sec
OOF RMSE: 2.25 | R2: 0.58
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 19:22:41,873] Trial 7 finished with value: 0.25118504950892073 and parameters: {'hidden_layer_sizes': '50', 'activation': 'tanh', 'solver': 'adam', 'alpha': 6.586596710204789e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.002815958598797501}. Best is trial 6 with value: 0.5803798553788246.

Fold 4
Fold 5
Running time: 0.7 sec
OOF RMSE: 3.00 | R2: 0.25
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 19:22:42,783] Trial 8 finished with value: 0.4246537940454761 and parameters: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.002555258783722331, 'learning_rate': 'constant', 'learning_rate_init': 0.0026807241503310647}. Best is trial 6 with value: 0.5803798553788246.

Running time: 0.9 sec
OOF RMSE: 2.63 | R2: 0.42
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 19:22:43,641] Trial 9 finished with value: 0.3766472555764844 and parameters: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.00021954050815135812, 'learning_rate': 'constant', 'learning_rate_init': 0.000750955835750701}. Best is trial 6 with value: 0.5803798553788246.

Running time: 0.8 sec
OOF RMSE: 2.74 | R2: 0.38
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 19:22:44,597] Trial 10 finished with value: 0.5795214183488326 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'tanh', 'solver': 'adam', 'alpha': 1.7789337705744068e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.009768968963287413}. Best is trial 6 with value: 0.5803798553788246.

Fold 5
Running time: 0.9 sec
OOF RMSE: 2.25 | R2: 0.58
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:22:45,387] Trial 11 finished with value: 0.5785534590244257 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'tanh', 'solver': 'adam', 'alpha': 1.1278442848674756e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.009990554422764877}. Best is trial 6 with value: 0.5803798553788246.

Running time: 0.8 sec
OOF RMSE: 2.25 | R2: 0.58
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 19:22:46,189] Trial 12 finished with value: 0.5790639491626406 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'tanh', 'solver': 'adam', 'alpha': 1.0308229122234947e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.009905149751214986}. Best is trial 6 with value: 0.5803798553788246.

Fold 5
Running time: 0.8 sec
OOF RMSE: 2.25 | R2: 0.58
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:22:47,243] Trial 13 finished with value: 0.6173672480369005 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0727222153851554, 'learning_rate': 'constant', 'learning_rate_init': 0.0066462844312102105}. Best is trial 13 with value: 0.6173672480369005.

Running time: 1.0 sec
OOF RMSE: 2.14 | R2: 0.62
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 19:22:48,916] Trial 14 finished with value: 0.3418885984877641 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.057325736970332074, 'learning_rate': 'constant', 'learning_rate_init': 0.000599338404098923}. Best is trial 13 with value: 0.6173672480369005.

Fold 4
Fold 5
Running time: 1.7 sec
OOF RMSE: 2.81 | R2: 0.34
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:22:50,293] Trial 15 finished with value: 0.6234176337610275 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.08577417780953864, 'learning_rate': 'constant', 'learning_rate_init': 0.005198794514392527}. Best is trial 15 with value: 0.6234176337610275.

Running time: 1.4 sec
OOF RMSE: 2.13 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:22:51,264] Trial 16 finished with value: 0.5909004221618683 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.09654859246504094, 'learning_rate': 'constant', 'learning_rate_init': 0.0052368709964382264}. Best is trial 15 with value: 0.6234176337610275.

Running time: 1.0 sec
OOF RMSE: 2.22 | R2: 0.59
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 19:22:51,948] Trial 17 finished with value: 0.25903886218927186 and parameters: {'hidden_layer_sizes': '50', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.020417518210406826, 'learning_rate': 'constant', 'learning_rate_init': 0.0014097311530873863}. Best is trial 15 with value: 0.6234176337610275.

Fold 4
Fold 5
Running time: 0.7 sec
OOF RMSE: 2.98 | R2: 0.26
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 19:22:52,661] Trial 18 finished with value: 0.3188119779247296 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.015653518723037465, 'learning_rate': 'constant', 'learning_rate_init': 0.0004212281942464833}. Best is trial 15 with value: 0.6234176337610275.

Fold 4
Fold 5
Running time: 0.7 sec
OOF RMSE: 2.86 | R2: 0.32
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:22:53,713] Trial 19 finished with value: 0.5960220717127787 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.005843626070237739, 'learning_rate': 'constant', 'learning_rate_init': 0.0059196795577178786}. Best is trial 15 with value: 0.6234176337610275.

Running time: 1.0 sec
OOF RMSE: 2.20 | R2: 0.60
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 19:22:54,762] Trial 20 finished with value: 0.34906376535794237 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.037895186748551114, 'learning_rate': 'constant', 'learning_rate_init': 0.0014422458677151406}. Best is trial 15 with value: 0.6234176337610275.

Fold 4
Fold 5
Running time: 1.0 sec
OOF RMSE: 2.80 | R2: 0.35
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:22:55,803] Trial 21 finished with value: 0.5921059755538334 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.006394348047848324, 'learning_rate': 'constant', 'learning_rate_init': 0.005098649516837861}. Best is trial 15 with value: 0.6234176337610275.

Running time: 1.0 sec
OOF RMSE: 2.21 | R2: 0.59
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:22:56,743] Trial 22 finished with value: 0.5983613781131227 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0013250623484282514, 'learning_rate': 'constant', 'learning_rate_init': 0.005789236282971397}. Best is trial 15 with value: 0.6234176337610275.

Running time: 0.9 sec
OOF RMSE: 2.20 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:22:57,821] Trial 23 finished with value: 0.6163164141414873 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0010324691198356048, 'learning_rate': 'constant', 'learning_rate_init': 0.006562513136216919}. Best is trial 15 with value: 0.6234176337610275.

Running time: 1.1 sec
OOF RMSE: 2.15 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:22:59,261] Trial 24 finished with value: 0.5885299084771318 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.09625380416103205, 'learning_rate': 'constant', 'learning_rate_init': 0.002028372343879636}. Best is trial 15 with value: 0.6234176337610275.
[I 2025-07-11 19:22:59,262] A new study created in memory with name: no-name-930443a3-7b99-40ba-bfbd-75d986c278eb
[I 2025-07-11 19:22:59,349] Trial 0 finished with value: -73.92563527273707 and parameters: {'kernel': 'sigmoid', 'C': 3.7109983266291597, 'epsilon': 0.12842592715075812, 'gamma': 'scale'}. Best is trial 0 with value: -73.92563527273707.
[I 2025-07-11 19:22:59,420] Trial 1 finished with value: 0.0784499298526461 and parameters: {'kernel': 'rbf', 'C': 0.16021547380909004, 'epsilon': 0.19834052964957485, 'gamma': 'scale'}. Best is trial 1 with value: 0.0784499298526461.

Running time: 1.4 sec
OOF RMSE: 2.22 | R2: 0.59

✅ MLP - Mejor R2: 0.62
📋 Parámetros: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.08577417780953864, 'learning_rate': 'constant', 'learning_rate_init': 0.005198794514392527}

Buscando mejores hiperparámetros para SVR...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 30.01 | R2: -73.93
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.33 | R2: 0.08
Fold 1
Fold 2
Fold 3

[I 2025-07-11 19:22:59,489] Trial 2 finished with value: -10.320676542099658 and parameters: {'kernel': 'sigmoid', 'C': 1.3568612437174268, 'epsilon': 0.06876387261213047, 'gamma': 'scale'}. Best is trial 1 with value: 0.0784499298526461.
[I 2025-07-11 19:22:59,565] Trial 3 finished with value: 0.4206112024877594 and parameters: {'kernel': 'rbf', 'C': 6.084670575558031, 'epsilon': 0.07525874286014568, 'gamma': 'scale'}. Best is trial 3 with value: 0.4206112024877594.
[I 2025-07-11 19:22:59,635] Trial 4 finished with value: 0.07270427123745327 and parameters: {'kernel': 'rbf', 'C': 0.14812510199717088, 'epsilon': 0.1414832491630787, 'gamma': 'auto'}. Best is trial 3 with value: 0.4206112024877594.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 11.66 | R2: -10.32
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.64 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.34 | R2: 0.07
Fold 1
Fold 2
Fold 3

[I 2025-07-11 19:22:59,702] Trial 5 finished with value: 0.13657656400097706 and parameters: {'kernel': 'rbf', 'C': 0.43584711992227704, 'epsilon': 0.09187554559280744, 'gamma': 'auto'}. Best is trial 3 with value: 0.4206112024877594.
[I 2025-07-11 19:22:59,779] Trial 6 finished with value: 0.2742425520008921 and parameters: {'kernel': 'rbf', 'C': 2.125983694636438, 'epsilon': 0.02834382364663411, 'gamma': 'scale'}. Best is trial 3 with value: 0.4206112024877594.
[I 2025-07-11 19:22:59,865] Trial 7 finished with value: 0.10243475913459377 and parameters: {'kernel': 'rbf', 'C': 0.23339830657381455, 'epsilon': 0.1783907159595858, 'gamma': 'auto'}. Best is trial 3 with value: 0.4206112024877594.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.22 | R2: 0.14
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.95 | R2: 0.27
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.28 | R2: 0.10
Fold 1

[I 2025-07-11 19:22:59,936] Trial 8 finished with value: 0.29516360487095494 and parameters: {'kernel': 'rbf', 'C': 2.6934889790844974, 'epsilon': 0.08105529683159705, 'gamma': 'scale'}. Best is trial 3 with value: 0.4206112024877594.
[I 2025-07-11 19:23:00,020] Trial 9 finished with value: -403.0266008866401 and parameters: {'kernel': 'sigmoid', 'C': 8.632006679531854, 'epsilon': 0.12284925475390433, 'gamma': 'scale'}. Best is trial 3 with value: 0.4206112024877594.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.91 | R2: 0.30
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 69.68 | R2: -403.03
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:23:00,099] Trial 10 finished with value: -238.39531124231783 and parameters: {'kernel': 'sigmoid', 'C': 7.06638325931334, 'epsilon': 0.023703575393147228, 'gamma': 'auto'}. Best is trial 3 with value: 0.4206112024877594.
[I 2025-07-11 19:23:00,191] Trial 11 finished with value: 0.3267645008805802 and parameters: {'kernel': 'rbf', 'C': 3.465171682304881, 'epsilon': 0.0721116514683912, 'gamma': 'scale'}. Best is trial 3 with value: 0.4206112024877594.
[I 2025-07-11 19:23:00,273] Trial 12 finished with value: 0.35489873970866104 and parameters: {'kernel': 'rbf', 'C': 4.22546443134711, 'epsilon': 0.05228513719144726, 'gamma': 'scale'}. Best is trial 3 with value: 0.4206112024877594.

Running time: 0.1 sec
OOF RMSE: 53.64 | R2: -238.40
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.84 | R2: 0.33
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.78 | R2: 0.35
Fold 1
Fold 2

[I 2025-07-11 19:23:00,347] Trial 13 finished with value: 0.18603551265866014 and parameters: {'kernel': 'rbf', 'C': 0.7457624786126755, 'epsilon': 0.04501123833202042, 'gamma': 'scale'}. Best is trial 3 with value: 0.4206112024877594.
[I 2025-07-11 19:23:00,448] Trial 14 finished with value: 0.38889086204924594 and parameters: {'kernel': 'rbf', 'C': 5.183735207875762, 'epsilon': 0.050964290667035644, 'gamma': 'scale'}. Best is trial 3 with value: 0.4206112024877594.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.13 | R2: 0.19
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.71 | R2: 0.39
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 19:23:00,530] Trial 15 finished with value: 0.49550385941029185 and parameters: {'kernel': 'rbf', 'C': 9.679004405769282, 'epsilon': 0.10084709564467313, 'gamma': 'scale'}. Best is trial 15 with value: 0.49550385941029185.
[I 2025-07-11 19:23:00,612] Trial 16 finished with value: 0.48467537416951 and parameters: {'kernel': 'rbf', 'C': 8.962217175730382, 'epsilon': 0.09882771710733618, 'gamma': 'scale'}. Best is trial 15 with value: 0.49550385941029185.
[I 2025-07-11 19:23:00,688] Trial 17 finished with value: 0.22540115736408006 and parameters: {'kernel': 'rbf', 'C': 1.163292661417535, 'epsilon': 0.1076818302667755, 'gamma': 'scale'}. Best is trial 15 with value: 0.49550385941029185.

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.46 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.49 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.05 | R2: 0.23
Fold 1
Fold 2

[I 2025-07-11 19:23:00,766] Trial 18 finished with value: -445.3456716641591 and parameters: {'kernel': 'sigmoid', 'C': 9.647353006892597, 'epsilon': 0.10103204070294074, 'gamma': 'auto'}. Best is trial 15 with value: 0.49550385941029185.
[I 2025-07-11 19:23:00,844] Trial 19 finished with value: 0.2772618106759709 and parameters: {'kernel': 'rbf', 'C': 2.0951225597720478, 'epsilon': 0.15465739520143987, 'gamma': 'scale'}. Best is trial 15 with value: 0.49550385941029185.
[I 2025-07-11 19:23:00,915] Trial 20 finished with value: 0.16636969289958792 and parameters: {'kernel': 'rbf', 'C': 0.5611041413640688, 'epsilon': 0.1604489104173109, 'gamma': 'scale'}. Best is trial 15 with value: 0.49550385941029185.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 73.24 | R2: -445.35
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.95 | R2: 0.28
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.17 | R2: 0.17
Fold 1

[I 2025-07-11 19:23:00,993] Trial 21 finished with value: 0.41175032729277883 and parameters: {'kernel': 'rbf', 'C': 5.817187179133671, 'epsilon': 0.11443074722416922, 'gamma': 'scale'}. Best is trial 15 with value: 0.49550385941029185.
[I 2025-07-11 19:23:01,101] Trial 22 finished with value: 0.49514819404790067 and parameters: {'kernel': 'rbf', 'C': 9.690391477259888, 'epsilon': 0.08710841026818744, 'gamma': 'scale'}. Best is trial 15 with value: 0.49550385941029185.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.66 | R2: 0.41
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.46 | R2: 0.50
Fold 1
Fold 2
Fold 3

[I 2025-07-11 19:23:01,182] Trial 23 finished with value: 0.4930682088263545 and parameters: {'kernel': 'rbf', 'C': 9.51438401598188, 'epsilon': 0.09388010885959125, 'gamma': 'scale'}. Best is trial 15 with value: 0.49550385941029185.
[I 2025-07-11 19:23:01,267] Trial 24 finished with value: 0.4927723035499427 and parameters: {'kernel': 'rbf', 'C': 9.528435569083939, 'epsilon': 0.08702898853345693, 'gamma': 'scale'}. Best is trial 15 with value: 0.49550385941029185.
[I 2025-07-11 19:23:01,268] A new study created in memory with name: no-name-94f316be-59e3-4720-a07b-7d8329cc3627
[I 2025-07-11 19:23:01,327] Trial 0 finished with value: 0.5659290690317341 and parameters: {'n_neighbors': 10, 'weights': 'distance', 'leaf_size': 10}. Best is trial 0 with value: 0.5659290690317341.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.47 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.47 | R2: 0.49

✅ SVR - Mejor R2: 0.50
📋 Parámetros: {'kernel': 'rbf', 'C': 9.679004405769282, 'epsilon': 0.10084709564467313, 'gamma': 'scale'}

Buscando mejores hiperparámetros para KNN...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.28 | R2: 0.57
Fold 1
Fold 2
Fold 3

[I 2025-07-11 19:23:01,387] Trial 1 finished with value: 0.5364003993081803 and parameters: {'n_neighbors': 6, 'weights': 'uniform', 'leaf_size': 27}. Best is trial 0 with value: 0.5659290690317341.
[I 2025-07-11 19:23:01,450] Trial 2 finished with value: 0.5364003993081803 and parameters: {'n_neighbors': 6, 'weights': 'uniform', 'leaf_size': 32}. Best is trial 0 with value: 0.5659290690317341.
[I 2025-07-11 19:23:01,513] Trial 3 finished with value: 0.5046980793720063 and parameters: {'n_neighbors': 10, 'weights': 'uniform', 'leaf_size': 40}. Best is trial 0 with value: 0.5659290690317341.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.36 | R2: 0.54
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.36 | R2: 0.54
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.44 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:23:01,575] Trial 4 finished with value: 0.56888627599053 and parameters: {'n_neighbors': 8, 'weights': 'distance', 'leaf_size': 24}. Best is trial 4 with value: 0.56888627599053.
[I 2025-07-11 19:23:01,654] Trial 5 finished with value: 0.5434205036588793 and parameters: {'n_neighbors': 13, 'weights': 'distance', 'leaf_size': 32}. Best is trial 4 with value: 0.56888627599053.
[I 2025-07-11 19:23:01,734] Trial 6 finished with value: 0.5033616403503767 and parameters: {'n_neighbors': 8, 'weights': 'uniform', 'leaf_size': 36}. Best is trial 4 with value: 0.56888627599053.

Running time: 0.1 sec
OOF RMSE: 2.28 | R2: 0.57
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.34 | R2: 0.54
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.44 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 19:23:01,792] Trial 7 finished with value: 0.6310249092885778 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'leaf_size': 32}. Best is trial 7 with value: 0.6310249092885778.
[I 2025-07-11 19:23:01,855] Trial 8 finished with value: 0.5364003993081803 and parameters: {'n_neighbors': 6, 'weights': 'uniform', 'leaf_size': 17}. Best is trial 7 with value: 0.6310249092885778.
[I 2025-07-11 19:23:01,919] Trial 9 finished with value: 0.6195134079417843 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 10}. Best is trial 7 with value: 0.6310249092885778.
[I 2025-07-11 19:23:01,981] Trial 10 finished with value: 0.6195134079417843 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 23}. Best is trial 7 with value: 0.6310249092885778.

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.11 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.36 | R2: 0.54
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.14 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.14 | R2: 0.62

[I 2025-07-11 19:23:02,048] Trial 11 finished with value: 0.6195134079417843 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 10}. Best is trial 7 with value: 0.6310249092885778.
[I 2025-07-11 19:23:02,120] Trial 12 finished with value: 0.6195134079417843 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 17}. Best is trial 7 with value: 0.6310249092885778.
[I 2025-07-11 19:23:02,186] Trial 13 finished with value: 0.5291044649115955 and parameters: {'n_neighbors': 15, 'weights': 'distance', 'leaf_size': 29}. Best is trial 7 with value: 0.6310249092885778.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.14 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.14 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.38 | R2: 0.53
Fold 1

[I 2025-07-11 19:23:02,253] Trial 14 finished with value: 0.6278752895378754 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'leaf_size': 17}. Best is trial 7 with value: 0.6310249092885778.
[I 2025-07-11 19:23:02,361] Trial 15 finished with value: 0.6278752895378754 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'leaf_size': 18}. Best is trial 7 with value: 0.6310249092885778.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.11 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.11 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 19:23:02,431] Trial 16 finished with value: 0.6278752895378754 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'leaf_size': 21}. Best is trial 7 with value: 0.6310249092885778.
[I 2025-07-11 19:23:02,503] Trial 17 finished with value: 0.56888627599053 and parameters: {'n_neighbors': 8, 'weights': 'distance', 'leaf_size': 15}. Best is trial 7 with value: 0.6310249092885778.
[I 2025-07-11 19:23:02,574] Trial 18 finished with value: 0.6278752895378754 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'leaf_size': 35}. Best is trial 7 with value: 0.6310249092885778.

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.11 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.28 | R2: 0.57
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.11 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 19:23:02,641] Trial 19 finished with value: 0.5494836828706005 and parameters: {'n_neighbors': 12, 'weights': 'distance', 'leaf_size': 28}. Best is trial 7 with value: 0.6310249092885778.
[I 2025-07-11 19:23:02,712] Trial 20 finished with value: 0.5698181394062004 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'leaf_size': 40}. Best is trial 7 with value: 0.6310249092885778.
[I 2025-07-11 19:23:02,783] Trial 21 finished with value: 0.6278752895378754 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'leaf_size': 20}. Best is trial 7 with value: 0.6310249092885778.

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.33 | R2: 0.55
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.27 | R2: 0.57
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.11 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 19:23:02,849] Trial 22 finished with value: 0.6310249092885778 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'leaf_size': 14}. Best is trial 7 with value: 0.6310249092885778.
[I 2025-07-11 19:23:02,923] Trial 23 finished with value: 0.6310249092885778 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'leaf_size': 15}. Best is trial 7 with value: 0.6310249092885778.
[I 2025-07-11 19:23:02,996] Trial 24 finished with value: 0.6310249092885778 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'leaf_size': 13}. Best is trial 7 with value: 0.6310249092885778.
[I 2025-07-11 19:23:02,997] A new study created in memory with name: no-name-ce523d91-58be-4480-b74a-e3eb90080e8e

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.11 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.11 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.11 | R2: 0.63

✅ KNN - Mejor R2: 0.63
📋 Parámetros: {'n_neighbors': 4, 'weights': 'distance', 'leaf_size': 32}

Buscando mejores hiperparámetros para LR...
Fold 1
Fold 2
Fold 3

[I 2025-07-11 19:23:03,069] Trial 0 finished with value: -0.027636019996856165 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 0 with value: -0.027636019996856165.
[I 2025-07-11 19:23:03,145] Trial 1 finished with value: -0.027636019996856165 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 0 with value: -0.027636019996856165.
[I 2025-07-11 19:23:03,220] Trial 2 finished with value: 0.16837390835495925 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 2 with value: 0.16837390835495925.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.51 | R2: -0.03
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.51 | R2: -0.03
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.16 | R2: 0.17
Fold 1
Fold 2

[I 2025-07-11 19:23:03,285] Trial 3 finished with value: 0.16837390835495925 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 2 with value: 0.16837390835495925.
[I 2025-07-11 19:23:03,447] Trial 4 finished with value: -0.02763602000031895 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 2 with value: 0.16837390835495925.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.16 | R2: 0.17
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 3.51 | R2: -0.03

[I 2025-07-11 19:23:03,545] Trial 5 finished with value: 0.16837390835495925 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 2 with value: 0.16837390835495925.
[I 2025-07-11 19:23:03,604] Trial 6 finished with value: 0.1681790538552148 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 2 with value: 0.16837390835495925.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.16 | R2: 0.17
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.16 | R2: 0.17
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 19:23:03,687] Trial 7 finished with value: -0.027636019996856165 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 2 with value: 0.16837390835495925.
[I 2025-07-11 19:23:03,767] Trial 8 finished with value: 0.16837390835495925 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 2 with value: 0.16837390835495925.
[I 2025-07-11 19:23:03,848] Trial 9 finished with value: -0.027636019996856165 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 2 with value: 0.16837390835495925.

Fold 5
Running time: 0.1 sec
OOF RMSE: 3.51 | R2: -0.03
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.16 | R2: 0.17
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.51 | R2: -0.03
Fold 1
Fold 2

[I 2025-07-11 19:23:03,924] Trial 10 finished with value: 0.16837390835495925 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 2 with value: 0.16837390835495925.
[I 2025-07-11 19:23:03,986] Trial 11 finished with value: 0.16837390835495925 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 2 with value: 0.16837390835495925.
[I 2025-07-11 19:23:04,046] Trial 12 finished with value: 0.16837390835495925 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 2 with value: 0.16837390835495925.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.16 | R2: 0.17
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.16 | R2: 0.17
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.16 | R2: 0.17
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 19:23:04,106] Trial 13 finished with value: 0.16837390835495925 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 2 with value: 0.16837390835495925.
[I 2025-07-11 19:23:04,168] Trial 14 finished with value: 0.16837390835495925 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 2 with value: 0.16837390835495925.
[I 2025-07-11 19:23:04,242] Trial 15 finished with value: 0.16837390835495925 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 2 with value: 0.16837390835495925.

Fold 5
Running time: 0.1 sec
OOF RMSE: 3.16 | R2: 0.17
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.16 | R2: 0.17
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.16 | R2: 0.17
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:23:04,307] Trial 16 finished with value: 0.16837390835495925 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 2 with value: 0.16837390835495925.
[I 2025-07-11 19:23:04,367] Trial 17 finished with value: 0.16837390835495925 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 2 with value: 0.16837390835495925.
[I 2025-07-11 19:23:04,431] Trial 18 finished with value: 0.16837390835495925 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 2 with value: 0.16837390835495925.
[I 2025-07-11 19:23:04,488] Trial 19 finished with value: 0.16837390835495925 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 2 with value: 0.16837390835495925.

Running time: 0.1 sec
OOF RMSE: 3.16 | R2: 0.17
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.16 | R2: 0.17
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.16 | R2: 0.17
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.16 | R2: 0.17
Fold 1
Fold 2

[I 2025-07-11 19:23:04,547] Trial 20 finished with value: 0.16837390835495925 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 2 with value: 0.16837390835495925.
[I 2025-07-11 19:23:04,611] Trial 21 finished with value: 0.16837390835495925 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 2 with value: 0.16837390835495925.
[I 2025-07-11 19:23:04,672] Trial 22 finished with value: 0.16837390835495925 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 2 with value: 0.16837390835495925.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.16 | R2: 0.17
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.16 | R2: 0.17
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.16 | R2: 0.17
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:23:04,728] Trial 23 finished with value: 0.16837390835495925 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 2 with value: 0.16837390835495925.
[I 2025-07-11 19:23:04,789] Trial 24 finished with value: 0.16837390835495925 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 2 with value: 0.16837390835495925.
[I 2025-07-11 19:23:04,790] A new study created in memory with name: no-name-255121f7-c70e-4ab7-965a-38fc1eac4ff8

Running time: 0.1 sec
OOF RMSE: 3.16 | R2: 0.17
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.16 | R2: 0.17

✅ LR - Mejor R2: 0.17
📋 Parámetros: {'fit_intercept': True, 'positive': True}

Buscando mejores hiperparámetros para RF...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:23:13,586] Trial 0 finished with value: 0.571369469763719 and parameters: {'n_estimators': 500, 'max_depth': 14, 'min_samples_split': 6, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 0 with value: 0.571369469763719.

Running time: 8.8 sec
OOF RMSE: 2.27 | R2: 0.57
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:23:16,256] Trial 1 finished with value: 0.3711854121824978 and parameters: {'n_estimators': 100, 'max_depth': 12, 'min_samples_split': 8, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 0 with value: 0.571369469763719.

Running time: 2.7 sec
OOF RMSE: 2.75 | R2: 0.37
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:23:17,753] Trial 2 finished with value: 0.5585876499316529 and parameters: {'n_estimators': 100, 'max_depth': 14, 'min_samples_split': 3, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 0 with value: 0.571369469763719.

Running time: 1.5 sec
OOF RMSE: 2.30 | R2: 0.56
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:23:23,810] Trial 3 finished with value: 0.3774422726880231 and parameters: {'n_estimators': 300, 'max_depth': 7, 'min_samples_split': 3, 'min_samples_leaf': 5, 'bootstrap': False}. Best is trial 0 with value: 0.571369469763719.

Running time: 6.1 sec
OOF RMSE: 2.74 | R2: 0.38
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:23:25,408] Trial 4 finished with value: 0.5849573726826938 and parameters: {'n_estimators': 100, 'max_depth': 7, 'min_samples_split': 3, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 4 with value: 0.5849573726826938.

Running time: 1.6 sec
OOF RMSE: 2.23 | R2: 0.58
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:23:29,505] Trial 5 finished with value: 0.5469200841082462 and parameters: {'n_estimators': 300, 'max_depth': 7, 'min_samples_split': 2, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 4 with value: 0.5849573726826938.

Running time: 4.1 sec
OOF RMSE: 2.33 | R2: 0.55
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:23:36,043] Trial 6 finished with value: 0.3520896071624148 and parameters: {'n_estimators': 300, 'max_depth': 7, 'min_samples_split': 4, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 4 with value: 0.5849573726826938.

Running time: 6.5 sec
OOF RMSE: 2.79 | R2: 0.35
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:23:43,632] Trial 7 finished with value: 0.3524074065557995 and parameters: {'n_estimators': 300, 'max_depth': 9, 'min_samples_split': 2, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 4 with value: 0.5849573726826938.

Running time: 7.6 sec
OOF RMSE: 2.79 | R2: 0.35
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:23:47,747] Trial 8 finished with value: 0.5303288868020202 and parameters: {'n_estimators': 300, 'max_depth': 10, 'min_samples_split': 8, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 4 with value: 0.5849573726826938.

Running time: 4.1 sec
OOF RMSE: 2.38 | R2: 0.53
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:23:52,521] Trial 9 finished with value: 0.5685914702858573 and parameters: {'n_estimators': 300, 'max_depth': 15, 'min_samples_split': 7, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 4 with value: 0.5849573726826938.

Running time: 4.8 sec
OOF RMSE: 2.28 | R2: 0.57
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:23:53,781] Trial 10 finished with value: 0.567006878629849 and parameters: {'n_estimators': 100, 'max_depth': 5, 'min_samples_split': 10, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 4 with value: 0.5849573726826938.

Running time: 1.3 sec
OOF RMSE: 2.28 | R2: 0.57
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:24:03,281] Trial 11 finished with value: 0.5740956845469238 and parameters: {'n_estimators': 500, 'max_depth': 12, 'min_samples_split': 5, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 4 with value: 0.5849573726826938.

Running time: 9.5 sec
OOF RMSE: 2.26 | R2: 0.57
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:24:12,781] Trial 12 finished with value: 0.5740956845469238 and parameters: {'n_estimators': 500, 'max_depth': 12, 'min_samples_split': 5, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 4 with value: 0.5849573726826938.

Running time: 9.5 sec
OOF RMSE: 2.26 | R2: 0.57
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:24:22,128] Trial 13 finished with value: 0.573612372954599 and parameters: {'n_estimators': 500, 'max_depth': 11, 'min_samples_split': 5, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 4 with value: 0.5849573726826938.

Running time: 9.3 sec
OOF RMSE: 2.26 | R2: 0.57
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:24:30,970] Trial 14 finished with value: 0.5720611934642205 and parameters: {'n_estimators': 500, 'max_depth': 9, 'min_samples_split': 4, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 4 with value: 0.5849573726826938.

Running time: 8.8 sec
OOF RMSE: 2.27 | R2: 0.57
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:24:32,211] Trial 15 finished with value: 0.579037305971039 and parameters: {'n_estimators': 100, 'max_depth': 5, 'min_samples_split': 6, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 4 with value: 0.5849573726826938.

Running time: 1.2 sec
OOF RMSE: 2.25 | R2: 0.58
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:24:33,430] Trial 16 finished with value: 0.5637697376533315 and parameters: {'n_estimators': 100, 'max_depth': 5, 'min_samples_split': 10, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 4 with value: 0.5849573726826938.

Running time: 1.2 sec
OOF RMSE: 2.29 | R2: 0.56
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:24:34,746] Trial 17 finished with value: 0.5573821010721441 and parameters: {'n_estimators': 100, 'max_depth': 6, 'min_samples_split': 7, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 4 with value: 0.5849573726826938.

Running time: 1.3 sec
OOF RMSE: 2.31 | R2: 0.56
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:24:36,999] Trial 18 finished with value: 0.3765151099743427 and parameters: {'n_estimators': 100, 'max_depth': 8, 'min_samples_split': 9, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 4 with value: 0.5849573726826938.

Running time: 2.2 sec
OOF RMSE: 2.74 | R2: 0.38
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:24:38,219] Trial 19 finished with value: 0.5589408192486047 and parameters: {'n_estimators': 100, 'max_depth': 5, 'min_samples_split': 6, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 4 with value: 0.5849573726826938.

Running time: 1.2 sec
OOF RMSE: 2.30 | R2: 0.56
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:24:39,634] Trial 20 finished with value: 0.5955241321665423 and parameters: {'n_estimators': 100, 'max_depth': 6, 'min_samples_split': 3, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 20 with value: 0.5955241321665423.

Running time: 1.4 sec
OOF RMSE: 2.20 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:24:41,035] Trial 21 finished with value: 0.5955241321665423 and parameters: {'n_estimators': 100, 'max_depth': 6, 'min_samples_split': 3, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 20 with value: 0.5955241321665423.

Running time: 1.4 sec
OOF RMSE: 2.20 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:24:42,472] Trial 22 finished with value: 0.5955241321665423 and parameters: {'n_estimators': 100, 'max_depth': 6, 'min_samples_split': 3, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 20 with value: 0.5955241321665423.

Running time: 1.4 sec
OOF RMSE: 2.20 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:24:43,876] Trial 23 finished with value: 0.5955241321665423 and parameters: {'n_estimators': 100, 'max_depth': 6, 'min_samples_split': 2, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 20 with value: 0.5955241321665423.

Running time: 1.4 sec
OOF RMSE: 2.20 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:24:45,489] Trial 24 finished with value: 0.5924673701164942 and parameters: {'n_estimators': 100, 'max_depth': 8, 'min_samples_split': 4, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 20 with value: 0.5955241321665423.
[I 2025-07-11 19:24:45,490] A new study created in memory with name: no-name-26c390fc-f420-4383-928b-40982a0c318f

Running time: 1.6 sec
OOF RMSE: 2.21 | R2: 0.59

✅ RF - Mejor R2: 0.60
📋 Parámetros: {'n_estimators': 100, 'max_depth': 6, 'min_samples_split': 3, 'min_samples_leaf': 2, 'bootstrap': True}

Buscando mejores hiperparámetros para CAT...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:24:52,511] Trial 0 finished with value: 0.5949420922126786 and parameters: {'iterations': 1000, 'learning_rate': 0.014982504734203416, 'depth': 6, 'l2_leaf_reg': 6.7207701338043195}. Best is trial 0 with value: 0.5949420922126786.

Running time: 7.0 sec
OOF RMSE: 2.21 | R2: 0.59
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:24:54,098] Trial 1 finished with value: 0.5702894191520972 and parameters: {'iterations': 500, 'learning_rate': 0.051166482432749585, 'depth': 4, 'l2_leaf_reg': 1.1278941893508199}. Best is trial 0 with value: 0.5949420922126786.

Running time: 1.6 sec
OOF RMSE: 2.27 | R2: 0.57
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:25:01,225] Trial 2 finished with value: 0.6178134888221626 and parameters: {'iterations': 500, 'learning_rate': 0.028139345755353488, 'depth': 7, 'l2_leaf_reg': 2.324133576795928}. Best is trial 2 with value: 0.6178134888221626.

Running time: 7.1 sec
OOF RMSE: 2.14 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:25:02,749] Trial 3 finished with value: 0.5542809636635169 and parameters: {'iterations': 500, 'learning_rate': 0.01023691326147904, 'depth': 4, 'l2_leaf_reg': 7.065477972047898}. Best is trial 2 with value: 0.6178134888221626.

Running time: 1.5 sec
OOF RMSE: 2.31 | R2: 0.55
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:26:27,334] Trial 4 finished with value: 0.6217618531434143 and parameters: {'iterations': 1000, 'learning_rate': 0.08873076821740741, 'depth': 9, 'l2_leaf_reg': 2.360443825763334}. Best is trial 4 with value: 0.6217618531434143.

Running time: 84.6 sec
OOF RMSE: 2.13 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:27:40,486] Trial 5 finished with value: 0.6043956400361354 and parameters: {'iterations': 2000, 'learning_rate': 0.019147318022673856, 'depth': 8, 'l2_leaf_reg': 3.4251916144361285}. Best is trial 4 with value: 0.6217618531434143.

Running time: 73.1 sec
OOF RMSE: 2.18 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:28:21,401] Trial 6 finished with value: 0.6054974688178538 and parameters: {'iterations': 500, 'learning_rate': 0.026152366191017327, 'depth': 9, 'l2_leaf_reg': 7.729448241849784}. Best is trial 4 with value: 0.6217618531434143.

Running time: 40.9 sec
OOF RMSE: 2.18 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:28:24,777] Trial 7 finished with value: 0.570660466224406 and parameters: {'iterations': 1000, 'learning_rate': 0.043940101639593096, 'depth': 4, 'l2_leaf_reg': 1.1341504045381896}. Best is trial 4 with value: 0.6217618531434143.

Running time: 3.4 sec
OOF RMSE: 2.27 | R2: 0.57
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:29:00,911] Trial 8 finished with value: 0.6019759403144542 and parameters: {'iterations': 1000, 'learning_rate': 0.010585718109457885, 'depth': 8, 'l2_leaf_reg': 3.795228353677862}. Best is trial 4 with value: 0.6217618531434143.

Running time: 36.1 sec
OOF RMSE: 2.19 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:29:07,699] Trial 9 finished with value: 0.5910517932581525 and parameters: {'iterations': 1000, 'learning_rate': 0.016692004627304028, 'depth': 6, 'l2_leaf_reg': 8.201787007655696}. Best is trial 4 with value: 0.6217618531434143.

Running time: 6.8 sec
OOF RMSE: 2.22 | R2: 0.59
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:33:59,393] Trial 10 finished with value: 0.5944581760725713 and parameters: {'iterations': 2000, 'learning_rate': 0.09626552191286156, 'depth': 10, 'l2_leaf_reg': 4.941129678461227}. Best is trial 4 with value: 0.6217618531434143.

Running time: 291.7 sec
OOF RMSE: 2.21 | R2: 0.59
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:34:06,553] Trial 11 finished with value: 0.6001115322640236 and parameters: {'iterations': 500, 'learning_rate': 0.09093038707202482, 'depth': 7, 'l2_leaf_reg': 9.946365174031346}. Best is trial 4 with value: 0.6217618531434143.

Running time: 7.2 sec
OOF RMSE: 2.19 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:36:31,694] Trial 12 finished with value: 0.6024888160746449 and parameters: {'iterations': 1000, 'learning_rate': 0.04124336734056065, 'depth': 10, 'l2_leaf_reg': 2.7651133025154713}. Best is trial 4 with value: 0.6217618531434143.
[I 2025-07-11 19:36:31,695] A new study created in memory with name: no-name-bdef23fa-57bf-4596-a1f5-959d817e49b1
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.636e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.425e+01, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.164e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.106e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.634e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 19:36:31,815] Trial 0 finished with value: 0.412186854030378 and parameters: {'alpha': 0.002329483493247384, 'l1_ratio': 0.655042509169075}. Best is trial 0 with value: 0.412186854030378.

Running time: 145.1 sec
OOF RMSE: 2.19 | R2: 0.60

✅ CAT - Mejor R2: 0.62
📋 Parámetros: {'iterations': 1000, 'learning_rate': 0.08873076821740741, 'depth': 9, 'l2_leaf_reg': 2.360443825763334}

Buscando mejores hiperparámetros para EN...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.66 | R2: 0.41
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.487e+01, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.602e+00, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.916e+01, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.406e+01, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.790e+01, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 19:36:31,922] Trial 1 finished with value: 0.42702784901564084 and parameters: {'alpha': 0.006192995955829297, 'l1_ratio': 0.9257714899481345}. Best is trial 1 with value: 0.42702784901564084.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.682e+01, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.721e+00, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.139e+01, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.276e+01, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.62 | R2: 0.43
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.756e+01, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 19:36:32,109] Trial 2 finished with value: 0.4785332309935416 and parameters: {'alpha': 0.020037889228349214, 'l1_ratio': 0.3416457725008303}. Best is trial 2 with value: 0.4785332309935416.
[I 2025-07-11 19:36:32,275] Trial 3 finished with value: 0.4254938797425495 and parameters: {'alpha': 0.2009816350199614, 'l1_ratio': 0.5838633126743379}. Best is trial 2 with value: 0.4785332309935416.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.351e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(

Running time: 0.2 sec
OOF RMSE: 2.50 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 2.63 | R2: 0.43
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.854e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.091e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.852e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.227e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 19:36:32,479] Trial 4 finished with value: 0.34356054349049336 and parameters: {'alpha': 0.00019817660152475388, 'l1_ratio': 0.171450301466601}. Best is trial 2 with value: 0.4785332309935416.

Fold 3
Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 2.81 | R2: 0.34
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.651e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.330e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.623e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.713e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.604e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 19:36:32,708] Trial 5 finished with value: 0.3781557784086945 and parameters: {'alpha': 0.0019463420421885036, 'l1_ratio': 0.9749237072739679}. Best is trial 2 with value: 0.4785332309935416.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 2.73 | R2: 0.38
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 19:36:32,802] Trial 6 finished with value: 0.3937420176521367 and parameters: {'alpha': 0.5855373400497216, 'l1_ratio': 0.33263826536304164}. Best is trial 2 with value: 0.4785332309935416.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.129e-01, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.290e-01, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 19:36:32,982] Trial 7 finished with value: 0.4619570941749178 and parameters: {'alpha': 0.017406080422210885, 'l1_ratio': 0.8816982344489368}. Best is trial 2 with value: 0.4785332309935416.

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.70 | R2: 0.39
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 2.54 | R2: 0.46

[I 2025-07-11 19:36:33,081] Trial 8 finished with value: -0.00027817151752640434 and parameters: {'alpha': 9.374184489457011, 'l1_ratio': 0.9978070192520552}. Best is trial 2 with value: 0.4785332309935416.
[I 2025-07-11 19:36:33,170] Trial 9 finished with value: 0.39393679602306153 and parameters: {'alpha': 0.6655297772802723, 'l1_ratio': 0.22986105613087882}. Best is trial 2 with value: 0.4785332309935416.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.47 | R2: -0.00
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.70 | R2: 0.39
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.410e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.920e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.145e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.918e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.304e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 19:36:33,318] Trial 10 finished with value: 0.3448693165979613 and parameters: {'alpha': 0.00018747055737695676, 'l1_ratio': 0.013346161556451519}. Best is trial 2 with value: 0.4785332309935416.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.81 | R2: 0.34
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:36:33,445] Trial 11 finished with value: 0.4821162421564247 and parameters: {'alpha': 0.03260408196879752, 'l1_ratio': 0.7645274261904818}. Best is trial 11 with value: 0.4821162421564247.
[I 2025-07-11 19:36:33,553] Trial 12 finished with value: 0.4872063368824412 and parameters: {'alpha': 0.06800178999391457, 'l1_ratio': 0.7521336562638751}. Best is trial 12 with value: 0.4872063368824412.

Running time: 0.1 sec
OOF RMSE: 2.49 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.48 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:36:33,653] Trial 13 finished with value: 0.4653341683641701 and parameters: {'alpha': 0.09830830970145873, 'l1_ratio': 0.7688862713911476}. Best is trial 12 with value: 0.4872063368824412.
[I 2025-07-11 19:36:33,754] Trial 14 finished with value: 0.48227673232510737 and parameters: {'alpha': 0.07581128166539967, 'l1_ratio': 0.7775187165443909}. Best is trial 12 with value: 0.4872063368824412.

Running time: 0.1 sec
OOF RMSE: 2.53 | R2: 0.47
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.49 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:36:33,857] Trial 15 finished with value: -0.00027817151752640434 and parameters: {'alpha': 3.927997926426047, 'l1_ratio': 0.7303157256523349}. Best is trial 12 with value: 0.4872063368824412.
[I 2025-07-11 19:36:33,992] Trial 16 finished with value: 0.48147271921434887 and parameters: {'alpha': 0.08768461607508429, 'l1_ratio': 0.45619157341690075}. Best is trial 12 with value: 0.4872063368824412.

Running time: 0.1 sec
OOF RMSE: 3.47 | R2: -0.00
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.50 | R2: 0.48
Fold 1
Fold 2

[I 2025-07-11 19:36:34,163] Trial 17 finished with value: 0.3613191923880875 and parameters: {'alpha': 0.8253912485985494, 'l1_ratio': 0.5556019038388706}. Best is trial 12 with value: 0.4872063368824412.

Fold 3
Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 2.77 | R2: 0.36
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.418e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.831e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.191e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.816e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.138e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 19:36:34,380] Trial 18 finished with value: 0.3661723494781727 and parameters: {'alpha': 0.0008203251345256053, 'l1_ratio': 0.7838359514033215}. Best is trial 12 with value: 0.4872063368824412.

Fold 3
Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 2.76 | R2: 0.37
Fold 1
Fold 2
Fold 3

[I 2025-07-11 19:36:34,530] Trial 19 finished with value: 0.49018042429175857 and parameters: {'alpha': 0.05995132581939373, 'l1_ratio': 0.8725321610875301}. Best is trial 19 with value: 0.49018042429175857.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.037e+00, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.48 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.496e+01, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.500e+01, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.700e+01, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.331e+01, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 19:36:34,713] Trial 20 finished with value: 0.4367436871259195 and parameters: {'alpha': 0.007809890749713003, 'l1_ratio': 0.8496477083968746}. Best is trial 19 with value: 0.49018042429175857.
[I 2025-07-11 19:36:34,823] Trial 21 finished with value: 0.48492986865356036 and parameters: {'alpha': 0.07071013197350214, 'l1_ratio': 0.8471013708301671}. Best is trial 19 with value: 0.49018042429175857.

Running time: 0.2 sec
OOF RMSE: 2.60 | R2: 0.44
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.49 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:36:34,941] Trial 22 finished with value: 0.4105691689067069 and parameters: {'alpha': 0.25583683308504684, 'l1_ratio': 0.6573957443117345}. Best is trial 19 with value: 0.49018042429175857.
[I 2025-07-11 19:36:35,073] Trial 23 finished with value: 0.4870487874044145 and parameters: {'alpha': 0.04061229142796168, 'l1_ratio': 0.8652953774784028}. Best is trial 19 with value: 0.49018042429175857.

Running time: 0.1 sec
OOF RMSE: 2.66 | R2: 0.41
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.48 | R2: 0.49
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.940e+01, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.130e+01, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.473e+01, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.283e+01, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.254e+01, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 19:36:35,230] Trial 24 finished with value: 0.4472727259741591 and parameters: {'alpha': 0.008753181232541339, 'l1_ratio': 0.6762001616938398}. Best is trial 19 with value: 0.49018042429175857.
[I 2025-07-11 19:36:35,232] A new study created in memory with name: no-name-00ecdb2e-3803-4c0e-afac-d3562bbf4ce9

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.58 | R2: 0.45

✅ EN - Mejor R2: 0.49
📋 Parámetros: {'alpha': 0.05995132581939373, 'l1_ratio': 0.8725321610875301}

🔍 Optimizando en C2X_rhown_1x1_depth_lt_1...
Buscando mejores hiperparámetros para XGB...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:36:44,404] Trial 0 finished with value: 0.2730203159931571 and parameters: {'n_estimators': 1000, 'learning_rate': 0.024364375120859903, 'max_depth': 6, 'min_child_weight': 1, 'subsample': 0.8365185395389233, 'colsample_bytree': 0.9782543225186007}. Best is trial 0 with value: 0.2730203159931571.

Running time: 9.2 sec
OOF RMSE: 2.96 | R2: 0.27
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:36:51,233] Trial 1 finished with value: 0.312355512253388 and parameters: {'n_estimators': 1000, 'learning_rate': 0.03615154024852912, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.7663586868686805, 'colsample_bytree': 0.6705476937860156}. Best is trial 1 with value: 0.312355512253388.

Running time: 6.8 sec
OOF RMSE: 2.87 | R2: 0.31
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:37:02,202] Trial 2 finished with value: 0.29379385624486143 and parameters: {'n_estimators': 2000, 'learning_rate': 0.022579071526005398, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.8357773766021029, 'colsample_bytree': 0.7412290731859427}. Best is trial 1 with value: 0.312355512253388.

Running time: 11.0 sec
OOF RMSE: 2.91 | R2: 0.29
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:37:04,684] Trial 3 finished with value: 0.32193068333389463 and parameters: {'n_estimators': 500, 'learning_rate': 0.008093268644445166, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.6801790455458807, 'colsample_bytree': 0.7481960736859212}. Best is trial 3 with value: 0.32193068333389463.

Running time: 2.5 sec
OOF RMSE: 2.85 | R2: 0.32
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:37:07,650] Trial 4 finished with value: 0.22603635485295548 and parameters: {'n_estimators': 500, 'learning_rate': 0.05279466778727181, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.7455198859216273, 'colsample_bytree': 0.7545354287122862}. Best is trial 3 with value: 0.32193068333389463.

Running time: 3.0 sec
OOF RMSE: 3.05 | R2: 0.23
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:37:14,434] Trial 5 finished with value: 0.2635588153367151 and parameters: {'n_estimators': 1000, 'learning_rate': 0.018773782582029223, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.8783638579203077, 'colsample_bytree': 0.6362843512177442}. Best is trial 3 with value: 0.32193068333389463.

Running time: 6.8 sec
OOF RMSE: 2.97 | R2: 0.26
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:37:18,077] Trial 6 finished with value: 0.2532841270152544 and parameters: {'n_estimators': 500, 'learning_rate': 0.03980480315004945, 'max_depth': 6, 'min_child_weight': 1, 'subsample': 0.9786699055243022, 'colsample_bytree': 0.6920046836864865}. Best is trial 3 with value: 0.32193068333389463.

Running time: 3.6 sec
OOF RMSE: 3.00 | R2: 0.25
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:37:30,515] Trial 7 finished with value: 0.22534023372548584 and parameters: {'n_estimators': 2000, 'learning_rate': 0.04827197254167016, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.6792761741334241, 'colsample_bytree': 0.9632088684621732}. Best is trial 3 with value: 0.32193068333389463.

Running time: 12.4 sec
OOF RMSE: 3.05 | R2: 0.23
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:37:33,994] Trial 8 finished with value: 0.320012219192102 and parameters: {'n_estimators': 500, 'learning_rate': 0.00795376095199154, 'max_depth': 8, 'min_child_weight': 4, 'subsample': 0.6597717262136047, 'colsample_bytree': 0.9705168363002383}. Best is trial 3 with value: 0.32193068333389463.

Running time: 3.5 sec
OOF RMSE: 2.86 | R2: 0.32
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:37:45,295] Trial 9 finished with value: 0.3048956661681488 and parameters: {'n_estimators': 2000, 'learning_rate': 0.036987203735497666, 'max_depth': 8, 'min_child_weight': 2, 'subsample': 0.8881565052491911, 'colsample_bytree': 0.7875050880589421}. Best is trial 3 with value: 0.32193068333389463.

Running time: 11.3 sec
OOF RMSE: 2.89 | R2: 0.30
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:37:47,665] Trial 10 finished with value: 0.33401387931338666 and parameters: {'n_estimators': 500, 'learning_rate': 0.005135154382261033, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.6091447167295923, 'colsample_bytree': 0.8667203784838879}. Best is trial 10 with value: 0.33401387931338666.

Running time: 2.4 sec
OOF RMSE: 2.83 | R2: 0.33
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:37:50,209] Trial 11 finished with value: 0.3363184475909681 and parameters: {'n_estimators': 500, 'learning_rate': 0.005024292454962355, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.6109845658052584, 'colsample_bytree': 0.8600093965726303}. Best is trial 11 with value: 0.3363184475909681.

Running time: 2.5 sec
OOF RMSE: 2.82 | R2: 0.34
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:37:52,602] Trial 12 finished with value: 0.3373113744018261 and parameters: {'n_estimators': 500, 'learning_rate': 0.005643747057987874, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.6004411971311413, 'colsample_bytree': 0.8712113971241238}. Best is trial 12 with value: 0.3373113744018261.

Running time: 2.4 sec
OOF RMSE: 2.82 | R2: 0.34
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:37:55,089] Trial 13 finished with value: 0.3375517912116336 and parameters: {'n_estimators': 500, 'learning_rate': 0.005017672209676296, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.6068841748793381, 'colsample_bytree': 0.8778211786649988}. Best is trial 13 with value: 0.3375517912116336.

Running time: 2.5 sec
OOF RMSE: 2.82 | R2: 0.34
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:37:57,587] Trial 14 finished with value: 0.3105464129579374 and parameters: {'n_estimators': 500, 'learning_rate': 0.01086166606022039, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.7289046297135897, 'colsample_bytree': 0.8692250406359985}. Best is trial 13 with value: 0.3375517912116336.

Running time: 2.5 sec
OOF RMSE: 2.88 | R2: 0.31
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:38:00,015] Trial 15 finished with value: 0.18316713891622005 and parameters: {'n_estimators': 500, 'learning_rate': 0.09915079874610971, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.6001778308049694, 'colsample_bytree': 0.9048995025573856}. Best is trial 13 with value: 0.3375517912116336.

Running time: 2.4 sec
OOF RMSE: 3.13 | R2: 0.18
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:38:03,562] Trial 16 finished with value: 0.25545480949864174 and parameters: {'n_estimators': 500, 'learning_rate': 0.013173722422216967, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.6519577874179282, 'colsample_bytree': 0.912382066171483}. Best is trial 13 with value: 0.3375517912116336.

Running time: 3.5 sec
OOF RMSE: 2.99 | R2: 0.26
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:38:06,321] Trial 17 finished with value: 0.3324048694643321 and parameters: {'n_estimators': 500, 'learning_rate': 0.007856002109566477, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.7010724302514648, 'colsample_bytree': 0.8246842909173369}. Best is trial 13 with value: 0.3375517912116336.

Running time: 2.8 sec
OOF RMSE: 2.83 | R2: 0.33
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:38:12,547] Trial 18 finished with value: 0.27542968184987426 and parameters: {'n_estimators': 1000, 'learning_rate': 0.00650349951990703, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.7875261394021059, 'colsample_bytree': 0.9234671143857319}. Best is trial 13 with value: 0.3375517912116336.

Running time: 6.2 sec
OOF RMSE: 2.95 | R2: 0.28
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:38:23,655] Trial 19 finished with value: 0.24626657807983743 and parameters: {'n_estimators': 2000, 'learning_rate': 0.012219740461104826, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.6444874644974945, 'colsample_bytree': 0.8139522901011533}. Best is trial 13 with value: 0.3375517912116336.

Running time: 11.1 sec
OOF RMSE: 3.01 | R2: 0.25
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:38:26,303] Trial 20 finished with value: 0.31685768594951225 and parameters: {'n_estimators': 500, 'learning_rate': 0.006475942529051235, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.7130180875009526, 'colsample_bytree': 0.934955175680704}. Best is trial 13 with value: 0.3375517912116336.

Running time: 2.6 sec
OOF RMSE: 2.87 | R2: 0.32
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:38:28,696] Trial 21 finished with value: 0.34250132047837467 and parameters: {'n_estimators': 500, 'learning_rate': 0.005040531290685258, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.6168089280051787, 'colsample_bytree': 0.8361680651770701}. Best is trial 21 with value: 0.34250132047837467.

Running time: 2.4 sec
OOF RMSE: 2.81 | R2: 0.34
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:38:31,153] Trial 22 finished with value: 0.3341168126844969 and parameters: {'n_estimators': 500, 'learning_rate': 0.006163626234448411, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.643399958891238, 'colsample_bytree': 0.8470390321286339}. Best is trial 21 with value: 0.34250132047837467.

Running time: 2.5 sec
OOF RMSE: 2.83 | R2: 0.33
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:38:33,619] Trial 23 finished with value: 0.3239626847074566 and parameters: {'n_estimators': 500, 'learning_rate': 0.009504148728005821, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.6239115996575801, 'colsample_bytree': 0.7904107831472736}. Best is trial 21 with value: 0.34250132047837467.

Running time: 2.5 sec
OOF RMSE: 2.85 | R2: 0.32
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:38:36,370] Trial 24 finished with value: 0.2850340433487145 and parameters: {'n_estimators': 500, 'learning_rate': 0.015148982141087983, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.6859130922050035, 'colsample_bytree': 0.8854108212930732}. Best is trial 21 with value: 0.34250132047837467.
[I 2025-07-11 19:38:36,372] A new study created in memory with name: no-name-f4fcf38a-75f3-475d-a921-b04821959e53

Running time: 2.7 sec
OOF RMSE: 2.93 | R2: 0.29

✅ XGB - Mejor R2: 0.34
📋 Parámetros: {'n_estimators': 500, 'learning_rate': 0.005040531290685258, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.6168089280051787, 'colsample_bytree': 0.8361680651770701}

Buscando mejores hiperparámetros para LBM...
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 19:38:36,660] Trial 0 finished with value: 0.10376376426960077 and parameters: {'learning_rate': 0.04022020605661789, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 12, 'subsample': 0.7258771099436803, 'colsample_bytree': 0.9403096356006929, 'n_estimators': 500}. Best is trial 0 with value: 0.10376376426960077.

Fold 5
Running time: 0.3 sec
OOF RMSE: 3.28 | R2: 0.10
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:38:37,179] Trial 1 finished with value: 0.09973036514362565 and parameters: {'learning_rate': 0.07598326556644096, 'num_leaves': 60, 'max_depth': 6, 'min_child_samples': 18, 'subsample': 0.8121254948751989, 'colsample_bytree': 0.9797326499905863, 'n_estimators': 1000}. Best is trial 0 with value: 0.10376376426960077.

Running time: 0.5 sec
OOF RMSE: 3.29 | R2: 0.10
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 19:38:38,191] Trial 2 finished with value: 0.07175897839766021 and parameters: {'learning_rate': 0.05909235451160818, 'num_leaves': 60, 'max_depth': 6, 'min_child_samples': 14, 'subsample': 0.6517734222217907, 'colsample_bytree': 0.8745345794524687, 'n_estimators': 2000}. Best is trial 0 with value: 0.10376376426960077.

Fold 5
Running time: 1.0 sec
OOF RMSE: 3.34 | R2: 0.07
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 19:38:38,547] Trial 3 finished with value: 0.3271076519072874 and parameters: {'learning_rate': 0.005520385238541119, 'num_leaves': 60, 'max_depth': 8, 'min_child_samples': 10, 'subsample': 0.9192073081696037, 'colsample_bytree': 0.6999368229007302, 'n_estimators': 500}. Best is trial 3 with value: 0.3271076519072874.

Fold 5
Running time: 0.4 sec
OOF RMSE: 2.84 | R2: 0.33
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:38:40,156] Trial 4 finished with value: 0.2364722495295123 and parameters: {'learning_rate': 0.028514727894490926, 'num_leaves': 80, 'max_depth': 8, 'min_child_samples': 6, 'subsample': 0.8240208653980143, 'colsample_bytree': 0.8712122283859485, 'n_estimators': 2000}. Best is trial 3 with value: 0.3271076519072874.

Running time: 1.6 sec
OOF RMSE: 3.03 | R2: 0.24
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 19:38:40,420] Trial 5 finished with value: 0.27605748114760265 and parameters: {'learning_rate': 0.021280497987345184, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 6, 'subsample': 0.6883793718587167, 'colsample_bytree': 0.9435191055066383, 'n_estimators': 500}. Best is trial 3 with value: 0.3271076519072874.

Fold 5
Running time: 0.3 sec
OOF RMSE: 2.95 | R2: 0.28
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:38:41,367] Trial 6 finished with value: 0.07490772536351731 and parameters: {'learning_rate': 0.009932044310467195, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 13, 'subsample': 0.8658334188310186, 'colsample_bytree': 0.6383302687798196, 'n_estimators': 2000}. Best is trial 3 with value: 0.3271076519072874.

Running time: 0.9 sec
OOF RMSE: 3.33 | R2: 0.07
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 19:38:42,186] Trial 7 finished with value: 0.14016186474529158 and parameters: {'learning_rate': 0.01281775794838986, 'num_leaves': 60, 'max_depth': 5, 'min_child_samples': 21, 'subsample': 0.6244449558861812, 'colsample_bytree': 0.8704186915464134, 'n_estimators': 2000}. Best is trial 3 with value: 0.3271076519072874.

Fold 5
Running time: 0.8 sec
OOF RMSE: 3.21 | R2: 0.14
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:38:42,473] Trial 8 finished with value: 0.12750952575560648 and parameters: {'learning_rate': 0.07530294729216719, 'num_leaves': 20, 'max_depth': 8, 'min_child_samples': 18, 'subsample': 0.943273740398524, 'colsample_bytree': 0.6149000105994361, 'n_estimators': 500}. Best is trial 3 with value: 0.3271076519072874.

Running time: 0.3 sec
OOF RMSE: 3.24 | R2: 0.13
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 19:38:43,429] Trial 9 finished with value: 0.04952219847997208 and parameters: {'learning_rate': 0.08853109316421083, 'num_leaves': 80, 'max_depth': 6, 'min_child_samples': 14, 'subsample': 0.666954853212392, 'colsample_bytree': 0.6777435433843942, 'n_estimators': 2000}. Best is trial 3 with value: 0.3271076519072874.

Fold 5
Running time: 1.0 sec
OOF RMSE: 3.38 | R2: 0.05
Fold 1
Fold 2
Fold 3

[I 2025-07-11 19:38:43,896] Trial 10 finished with value: 0.24393199362933438 and parameters: {'learning_rate': 0.005965016922114054, 'num_leaves': 40, 'max_depth': 7, 'min_child_samples': 25, 'subsample': 0.989083290425344, 'colsample_bytree': 0.7252294640673576, 'n_estimators': 1000}. Best is trial 3 with value: 0.3271076519072874.

Fold 4
Fold 5
Running time: 0.5 sec
OOF RMSE: 3.01 | R2: 0.24
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:38:44,202] Trial 11 finished with value: 0.3884871253661627 and parameters: {'learning_rate': 0.005085051580842183, 'num_leaves': 40, 'max_depth': 5, 'min_child_samples': 6, 'subsample': 0.9036015866394526, 'colsample_bytree': 0.7681017427315883, 'n_estimators': 500}. Best is trial 11 with value: 0.3884871253661627.

Running time: 0.3 sec
OOF RMSE: 2.71 | R2: 0.39
Fold 1
Fold 2
Fold 3

[I 2025-07-11 19:38:44,552] Trial 12 finished with value: 0.34437827409484945 and parameters: {'learning_rate': 0.0051297873914356385, 'num_leaves': 40, 'max_depth': 7, 'min_child_samples': 9, 'subsample': 0.9018877329083258, 'colsample_bytree': 0.7587274683044802, 'n_estimators': 500}. Best is trial 11 with value: 0.3884871253661627.

Fold 4
Fold 5
Running time: 0.3 sec
OOF RMSE: 2.81 | R2: 0.34
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:38:44,896] Trial 13 finished with value: 0.28823552622766924 and parameters: {'learning_rate': 0.010311926538034507, 'num_leaves': 40, 'max_depth': 7, 'min_child_samples': 9, 'subsample': 0.8844162749964961, 'colsample_bytree': 0.7718631236275778, 'n_estimators': 500}. Best is trial 11 with value: 0.3884871253661627.

Running time: 0.3 sec
OOF RMSE: 2.92 | R2: 0.29
Fold 1
Fold 2
Fold 3

[I 2025-07-11 19:38:45,354] Trial 14 finished with value: 0.3537398515301522 and parameters: {'learning_rate': 0.005136833253607173, 'num_leaves': 40, 'max_depth': 7, 'min_child_samples': 5, 'subsample': 0.7664440268580547, 'colsample_bytree': 0.7904688814764664, 'n_estimators': 500}. Best is trial 11 with value: 0.3884871253661627.

Fold 4
Fold 5
Running time: 0.5 sec
OOF RMSE: 2.79 | R2: 0.35
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:38:45,644] Trial 15 finished with value: 0.3313281574542004 and parameters: {'learning_rate': 0.008991574759923435, 'num_leaves': 40, 'max_depth': 5, 'min_child_samples': 5, 'subsample': 0.753596167656646, 'colsample_bytree': 0.8248116555092077, 'n_estimators': 500}. Best is trial 11 with value: 0.3884871253661627.

Running time: 0.3 sec
OOF RMSE: 2.83 | R2: 0.33
Fold 1
Fold 2
Fold 3

[I 2025-07-11 19:38:45,988] Trial 16 finished with value: 0.26988069404761517 and parameters: {'learning_rate': 0.016366114205055043, 'num_leaves': 40, 'max_depth': 7, 'min_child_samples': 7, 'subsample': 0.7664822556808799, 'colsample_bytree': 0.8025111624905749, 'n_estimators': 500}. Best is trial 11 with value: 0.3884871253661627.

Fold 4
Fold 5
Running time: 0.3 sec
OOF RMSE: 2.96 | R2: 0.27
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 19:38:46,435] Trial 17 finished with value: 0.22048980067118584 and parameters: {'learning_rate': 0.007470007577408307, 'num_leaves': 40, 'max_depth': 5, 'min_child_samples': 11, 'subsample': 0.8350448681295928, 'colsample_bytree': 0.7408544115734631, 'n_estimators': 1000}. Best is trial 11 with value: 0.3884871253661627.

Fold 5
Running time: 0.4 sec
OOF RMSE: 3.06 | R2: 0.22
Fold 1
Fold 2

[I 2025-07-11 19:38:46,785] Trial 18 finished with value: 0.30037240390964526 and parameters: {'learning_rate': 0.00744159938142504, 'num_leaves': 40, 'max_depth': 7, 'min_child_samples': 8, 'subsample': 0.9851989731318382, 'colsample_bytree': 0.8328043937028001, 'n_estimators': 500}. Best is trial 11 with value: 0.3884871253661627.

Fold 3
Fold 4
Fold 5
Running time: 0.3 sec
OOF RMSE: 2.90 | R2: 0.30
Fold 1
Fold 2
Fold 3

[I 2025-07-11 19:38:47,177] Trial 19 finished with value: 0.2873713856395148 and parameters: {'learning_rate': 0.014735009021128924, 'num_leaves': 40, 'max_depth': 8, 'min_child_samples': 5, 'subsample': 0.7880434513468184, 'colsample_bytree': 0.6769469704363175, 'n_estimators': 500}. Best is trial 11 with value: 0.3884871253661627.

Fold 4
Fold 5
Running time: 0.4 sec
OOF RMSE: 2.93 | R2: 0.29
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 19:38:47,650] Trial 20 finished with value: 0.14890476383392326 and parameters: {'learning_rate': 0.021432066862574838, 'num_leaves': 80, 'max_depth': 5, 'min_child_samples': 17, 'subsample': 0.7092736240461295, 'colsample_bytree': 0.7733851722562685, 'n_estimators': 1000}. Best is trial 11 with value: 0.3884871253661627.

Fold 5
Running time: 0.5 sec
OOF RMSE: 3.20 | R2: 0.15
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:38:48,031] Trial 21 finished with value: 0.3258308858882839 and parameters: {'learning_rate': 0.005111687320662375, 'num_leaves': 40, 'max_depth': 7, 'min_child_samples': 8, 'subsample': 0.8873799097877835, 'colsample_bytree': 0.7573444681185749, 'n_estimators': 500}. Best is trial 11 with value: 0.3884871253661627.

Running time: 0.4 sec
OOF RMSE: 2.85 | R2: 0.33
Fold 1
Fold 2
Fold 3

[I 2025-07-11 19:38:48,380] Trial 22 finished with value: 0.3090273788580733 and parameters: {'learning_rate': 0.007131651976939437, 'num_leaves': 40, 'max_depth': 7, 'min_child_samples': 10, 'subsample': 0.9267299259848644, 'colsample_bytree': 0.7953409938661393, 'n_estimators': 500}. Best is trial 11 with value: 0.3884871253661627.

Fold 4
Fold 5
Running time: 0.3 sec
OOF RMSE: 2.88 | R2: 0.31
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 19:38:48,806] Trial 23 finished with value: 0.33516215610736744 and parameters: {'learning_rate': 0.005050677045023795, 'num_leaves': 40, 'max_depth': 7, 'min_child_samples': 7, 'subsample': 0.8648209775630274, 'colsample_bytree': 0.7186259423853637, 'n_estimators': 500}. Best is trial 11 with value: 0.3884871253661627.

Fold 5
Running time: 0.4 sec
OOF RMSE: 2.83 | R2: 0.34
Fold 1
Fold 2

[I 2025-07-11 19:38:49,164] Trial 24 finished with value: 0.3369665309482963 and parameters: {'learning_rate': 0.006830928151328351, 'num_leaves': 40, 'max_depth': 6, 'min_child_samples': 5, 'subsample': 0.9494223721096386, 'colsample_bytree': 0.8292656760563755, 'n_estimators': 500}. Best is trial 11 with value: 0.3884871253661627.
[I 2025-07-11 19:38:49,165] A new study created in memory with name: no-name-07c98431-2b5e-45fe-9262-d217f37b2d68

Fold 3
Fold 4
Fold 5
Running time: 0.4 sec
OOF RMSE: 2.82 | R2: 0.34

✅ LBM - Mejor R2: 0.39
📋 Parámetros: {'learning_rate': 0.005085051580842183, 'num_leaves': 40, 'max_depth': 5, 'min_child_samples': 6, 'subsample': 0.9036015866394526, 'colsample_bytree': 0.7681017427315883, 'n_estimators': 500}

Buscando mejores hiperparámetros para MLP...
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:38:50,649] Trial 0 finished with value: 0.3687534592726228 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 3.373218156008367e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0028231343375611593}. Best is trial 0 with value: 0.3687534592726228.

Running time: 1.5 sec
OOF RMSE: 2.75 | R2: 0.37
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 19:38:51,323] Trial 1 finished with value: 0.28589457165355325 and parameters: {'hidden_layer_sizes': '50', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.007769496838689184, 'learning_rate': 'constant', 'learning_rate_init': 0.0007985174697095436}. Best is trial 0 with value: 0.3687534592726228.

Fold 4
Fold 5
Running time: 0.7 sec
OOF RMSE: 2.93 | R2: 0.29
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

[I 2025-07-11 19:38:53,589] Trial 2 finished with value: 0.2935082341149128 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 1.270221038350468e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0003133533921414348}. Best is trial 0 with value: 0.3687534592726228.

Running time: 2.3 sec
OOF RMSE: 2.91 | R2: 0.29
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:38:54,715] Trial 3 finished with value: 0.33448892283279497 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 1.2718282477279595e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.007031687419916765}. Best is trial 0 with value: 0.3687534592726228.

Running time: 1.1 sec
OOF RMSE: 2.83 | R2: 0.33
Fold 1
Fold 2
Fold 3

[I 2025-07-11 19:38:55,526] Trial 4 finished with value: 0.28425898640369185 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.001258566123937548, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0005052674409741447}. Best is trial 0 with value: 0.3687534592726228.

Fold 4
Fold 5
Running time: 0.8 sec
OOF RMSE: 2.93 | R2: 0.28
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 19:38:55,948] Trial 5 finished with value: 0.31260098131450476 and parameters: {'hidden_layer_sizes': '50', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.0006327551225316941, 'learning_rate': 'constant', 'learning_rate_init': 0.0013087816339851293}. Best is trial 0 with value: 0.3687534592726228.

Fold 4
Fold 5
Running time: 0.4 sec
OOF RMSE: 2.87 | R2: 0.31
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

[I 2025-07-11 19:38:57,509] Trial 6 finished with value: 0.3040123576682645 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0009709180025293005, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00024281166734099678}. Best is trial 0 with value: 0.3687534592726228.

Running time: 1.6 sec
OOF RMSE: 2.89 | R2: 0.30
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 19:38:58,966] Trial 7 finished with value: 0.35549601312559864 and parameters: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0016904080708661172, 'learning_rate': 'constant', 'learning_rate_init': 0.00012669983837482597}. Best is trial 0 with value: 0.3687534592726228.

Running time: 1.5 sec
OOF RMSE: 2.78 | R2: 0.36
Fold 1
Fold 2
Fold 3

[I 2025-07-11 19:39:00,043] Trial 8 finished with value: 0.2449808069545204 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.03977577487125631, 'learning_rate': 'constant', 'learning_rate_init': 0.004076910656239612}. Best is trial 0 with value: 0.3687534592726228.

Fold 4
Fold 5
Running time: 1.1 sec
OOF RMSE: 3.01 | R2: 0.24
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

[I 2025-07-11 19:39:01,303] Trial 9 finished with value: 0.30673360014318374 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.00021544761452898105, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0004313225518523523}. Best is trial 0 with value: 0.3687534592726228.

Running time: 1.3 sec
OOF RMSE: 2.89 | R2: 0.31
Fold 1
Fold 2
Fold 3

[I 2025-07-11 19:39:02,182] Trial 10 finished with value: 0.4068733290536304 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 9.473422475999739e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.002378735830197345}. Best is trial 10 with value: 0.4068733290536304.

Fold 4
Fold 5
Running time: 0.9 sec
OOF RMSE: 2.67 | R2: 0.41
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 19:39:03,027] Trial 11 finished with value: 0.4117507932441924 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 8.315361525399918e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.002598747032975474}. Best is trial 11 with value: 0.4117507932441924.

Fold 5
Running time: 0.8 sec
OOF RMSE: 2.66 | R2: 0.41
Fold 1
Fold 2
Fold 3

[I 2025-07-11 19:39:03,903] Trial 12 finished with value: 0.4085441510420197 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.00010045548907942977, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0019284744634274307}. Best is trial 11 with value: 0.4117507932441924.

Fold 4
Fold 5
Running time: 0.9 sec
OOF RMSE: 2.67 | R2: 0.41
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:39:05,067] Trial 13 finished with value: 0.40880517475512235 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 7.374815919006159e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0014869065608626869}. Best is trial 11 with value: 0.4117507932441924.

Running time: 1.2 sec
OOF RMSE: 2.67 | R2: 0.41
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 19:39:05,763] Trial 14 finished with value: 0.3988329085667828 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.00023137949130250682, 'learning_rate': 'adaptive', 'learning_rate_init': 0.008662114001831546}. Best is trial 11 with value: 0.4117507932441924.

Fold 5
Running time: 0.7 sec
OOF RMSE: 2.69 | R2: 0.40
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:39:07,292] Trial 15 finished with value: 0.379817377555385 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 3.826670983357114e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0010102468384028751}. Best is trial 11 with value: 0.4117507932441924.

Running time: 1.5 sec
OOF RMSE: 2.73 | R2: 0.38
Fold 1
Fold 2
Fold 3

[I 2025-07-11 19:39:07,964] Trial 16 finished with value: 0.4056214857415099 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.004455622350595522, 'learning_rate': 'adaptive', 'learning_rate_init': 0.005460212556921586}. Best is trial 11 with value: 0.4117507932441924.

Fold 4
Fold 5
Running time: 0.7 sec
OOF RMSE: 2.67 | R2: 0.41
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 19:39:08,763] Trial 17 finished with value: 0.411254234712378 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0002905065462718991, 'learning_rate': 'adaptive', 'learning_rate_init': 0.003786024717345004}. Best is trial 11 with value: 0.4117507932441924.

Fold 5
Running time: 0.8 sec
OOF RMSE: 2.66 | R2: 0.41
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:39:09,459] Trial 18 finished with value: 0.017395565852743156 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0003486154209455482, 'learning_rate': 'adaptive', 'learning_rate_init': 0.003898458047533909}. Best is trial 11 with value: 0.4117507932441924.

Running time: 0.7 sec
OOF RMSE: 3.44 | R2: 0.02
Fold 1
Fold 2
Fold 3

[I 2025-07-11 19:39:10,090] Trial 19 finished with value: 0.2755046722751703 and parameters: {'hidden_layer_sizes': '50', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.004059993443784694, 'learning_rate': 'adaptive', 'learning_rate_init': 0.003464575665673176}. Best is trial 11 with value: 0.4117507932441924.

Fold 4
Fold 5
Running time: 0.6 sec
OOF RMSE: 2.95 | R2: 0.28
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 19:39:10,694] Trial 20 finished with value: 0.3964818787485197 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.07387644718624917, 'learning_rate': 'adaptive', 'learning_rate_init': 0.009874140682367536}. Best is trial 11 with value: 0.4117507932441924.

Fold 5
Running time: 0.6 sec
OOF RMSE: 2.69 | R2: 0.40
Fold 1
Fold 2
Fold 3

[I 2025-07-11 19:39:11,734] Trial 21 finished with value: 0.4084216364819202 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 6.067778481706462e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0017642991220388378}. Best is trial 11 with value: 0.4117507932441924.

Fold 4
Fold 5
Running time: 1.0 sec
OOF RMSE: 2.67 | R2: 0.41
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:39:12,836] Trial 22 finished with value: 0.4090704900360367 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.00014392496182382208, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0014533734532636792}. Best is trial 11 with value: 0.4117507932441924.

Running time: 1.1 sec
OOF RMSE: 2.66 | R2: 0.41
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 19:39:13,631] Trial 23 finished with value: 0.40666939632719024 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0004578700197860306, 'learning_rate': 'adaptive', 'learning_rate_init': 0.005565487589942479}. Best is trial 11 with value: 0.4117507932441924.

Fold 5
Running time: 0.8 sec
OOF RMSE: 2.67 | R2: 0.41
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:39:15,132] Trial 24 finished with value: 0.38026149015471156 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.00017848383013860115, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0007302523838354676}. Best is trial 11 with value: 0.4117507932441924.
[I 2025-07-11 19:39:15,134] A new study created in memory with name: no-name-1b407d01-ed7f-4077-976d-e2e8f3a43bf5
[I 2025-07-11 19:39:15,229] Trial 0 finished with value: -295.02427596423473 and parameters: {'kernel': 'sigmoid', 'C': 6.76476060710991, 'epsilon': 0.07791586565961026, 'gamma': 'auto'}. Best is trial 0 with value: -295.02427596423473.
[I 2025-07-11 19:39:15,298] Trial 1 finished with value: -0.2264293206593775 and parameters: {'kernel': 'sigmoid', 'C': 0.3778541548853667, 'epsilon': 0.10968587570431972, 'gamma': 'scale'}. Best is trial 1 with value: -0.2264293206593775.

Running time: 1.5 sec
OOF RMSE: 2.73 | R2: 0.38

✅ MLP - Mejor R2: 0.41
📋 Parámetros: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 8.315361525399918e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.002598747032975474}

Buscando mejores hiperparámetros para SVR...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 59.64 | R2: -295.02
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.84 | R2: -0.23
Fold 1
Fold 2
Fold 3

[I 2025-07-11 19:39:15,364] Trial 2 finished with value: 0.24842929929686108 and parameters: {'kernel': 'rbf', 'C': 3.080575272353378, 'epsilon': 0.16704793965084344, 'gamma': 'auto'}. Best is trial 2 with value: 0.24842929929686108.
[I 2025-07-11 19:39:15,435] Trial 3 finished with value: 0.22813622944985879 and parameters: {'kernel': 'rbf', 'C': 2.4281578559208947, 'epsilon': 0.1158773993473336, 'gamma': 'auto'}. Best is trial 2 with value: 0.24842929929686108.
[I 2025-07-11 19:39:15,506] Trial 4 finished with value: -2.8696879986967523 and parameters: {'kernel': 'sigmoid', 'C': 0.9624654760891863, 'epsilon': 0.029219345869954914, 'gamma': 'scale'}. Best is trial 2 with value: 0.24842929929686108.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.01 | R2: 0.25
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.05 | R2: 0.23
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 6.82 | R2: -2.87
Fold 1
Fold 2
Fold 3

[I 2025-07-11 19:39:15,573] Trial 5 finished with value: -0.03155559868638247 and parameters: {'kernel': 'sigmoid', 'C': 0.15904953942382702, 'epsilon': 0.05685551409780484, 'gamma': 'auto'}. Best is trial 2 with value: 0.24842929929686108.
[I 2025-07-11 19:39:15,646] Trial 6 finished with value: -99.20641979521531 and parameters: {'kernel': 'sigmoid', 'C': 6.083513451123545, 'epsilon': 0.12320629088091259, 'gamma': 'scale'}. Best is trial 2 with value: 0.24842929929686108.
[I 2025-07-11 19:39:15,717] Trial 7 finished with value: 0.28101158994698705 and parameters: {'kernel': 'rbf', 'C': 3.25584453695569, 'epsilon': 0.012015248904029753, 'gamma': 'scale'}. Best is trial 7 with value: 0.28101158994698705.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.52 | R2: -0.03
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 34.70 | R2: -99.21
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.94 | R2: 0.28
Fold 1
Fold 2
Fold 3

[I 2025-07-11 19:39:15,785] Trial 8 finished with value: -7.959770906770318 and parameters: {'kernel': 'sigmoid', 'C': 1.2213634887860552, 'epsilon': 0.18044152694141324, 'gamma': 'auto'}. Best is trial 7 with value: 0.28101158994698705.
[I 2025-07-11 19:39:15,861] Trial 9 finished with value: -13.262912844393659 and parameters: {'kernel': 'sigmoid', 'C': 1.5470924671617288, 'epsilon': 0.0276899517718626, 'gamma': 'auto'}. Best is trial 7 with value: 0.28101158994698705.
[I 2025-07-11 19:39:15,934] Trial 10 finished with value: 0.09009924583694795 and parameters: {'kernel': 'rbf', 'C': 0.5263587355383783, 'epsilon': 0.0157813052145167, 'gamma': 'scale'}. Best is trial 7 with value: 0.28101158994698705.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 10.38 | R2: -7.96
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 13.09 | R2: -13.26
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.31 | R2: 0.09
Fold 1
Fold 2

[I 2025-07-11 19:39:16,007] Trial 11 finished with value: 0.29323305340932393 and parameters: {'kernel': 'rbf', 'C': 3.6109084807405085, 'epsilon': 0.1636269711204194, 'gamma': 'scale'}. Best is trial 11 with value: 0.29323305340932393.
[I 2025-07-11 19:39:16,088] Trial 12 finished with value: 0.29717530784586565 and parameters: {'kernel': 'rbf', 'C': 3.724559019225909, 'epsilon': 0.15202382062422692, 'gamma': 'scale'}. Best is trial 12 with value: 0.29717530784586565.
[I 2025-07-11 19:39:16,164] Trial 13 finished with value: 0.3636799085001472 and parameters: {'kernel': 'rbf', 'C': 7.876806605983593, 'epsilon': 0.15164085808433925, 'gamma': 'scale'}. Best is trial 13 with value: 0.3636799085001472.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.91 | R2: 0.29
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.91 | R2: 0.30
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.77 | R2: 0.36

[I 2025-07-11 19:39:16,252] Trial 14 finished with value: 0.36441872220944316 and parameters: {'kernel': 'rbf', 'C': 8.009086298324947, 'epsilon': 0.14009361946428275, 'gamma': 'scale'}. Best is trial 14 with value: 0.36441872220944316.
[I 2025-07-11 19:39:16,334] Trial 15 finished with value: 0.37048100973745135 and parameters: {'kernel': 'rbf', 'C': 8.550871827422283, 'epsilon': 0.14529266602824675, 'gamma': 'scale'}. Best is trial 15 with value: 0.37048100973745135.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.76 | R2: 0.36
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.75 | R2: 0.37
Fold 1
Fold 2
Fold 3

[I 2025-07-11 19:39:16,414] Trial 16 finished with value: 0.36795819914200456 and parameters: {'kernel': 'rbf', 'C': 8.353397583004263, 'epsilon': 0.13349030912448137, 'gamma': 'scale'}. Best is trial 15 with value: 0.37048100973745135.
[I 2025-07-11 19:39:16,495] Trial 17 finished with value: 0.37740083761294285 and parameters: {'kernel': 'rbf', 'C': 9.00670307336654, 'epsilon': 0.19517906642916386, 'gamma': 'scale'}. Best is trial 17 with value: 0.37740083761294285.
[I 2025-07-11 19:39:16,564] Trial 18 finished with value: 0.0029937488352823616 and parameters: {'kernel': 'rbf', 'C': 0.10381575423788313, 'epsilon': 0.19551921502294833, 'gamma': 'scale'}. Best is trial 17 with value: 0.37740083761294285.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.76 | R2: 0.37
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.74 | R2: 0.38
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.46 | R2: 0.00
Fold 1

[I 2025-07-11 19:39:16,636] Trial 19 finished with value: 0.2220487968870657 and parameters: {'kernel': 'rbf', 'C': 1.8695101617212602, 'epsilon': 0.19956876580373328, 'gamma': 'scale'}. Best is trial 17 with value: 0.37740083761294285.
[I 2025-07-11 19:39:16,735] Trial 20 finished with value: 0.3234617306885844 and parameters: {'kernel': 'rbf', 'C': 4.818179868602793, 'epsilon': 0.18123973678917898, 'gamma': 'scale'}. Best is trial 17 with value: 0.37740083761294285.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.06 | R2: 0.22
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.85 | R2: 0.32
Fold 1
Fold 2
Fold 3

[I 2025-07-11 19:39:16,821] Trial 21 finished with value: 0.37810301411450953 and parameters: {'kernel': 'rbf', 'C': 9.861250089652614, 'epsilon': 0.09541024655704211, 'gamma': 'scale'}. Best is trial 21 with value: 0.37810301411450953.
[I 2025-07-11 19:39:16,904] Trial 22 finished with value: 0.37789238132404446 and parameters: {'kernel': 'rbf', 'C': 9.850039453058079, 'epsilon': 0.09277069483707344, 'gamma': 'scale'}. Best is trial 21 with value: 0.37810301411450953.
[I 2025-07-11 19:39:16,979] Trial 23 finished with value: 0.325501565376593 and parameters: {'kernel': 'rbf', 'C': 5.006032736396759, 'epsilon': 0.08894144881712847, 'gamma': 'scale'}. Best is trial 21 with value: 0.37810301411450953.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.73 | R2: 0.38
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.73 | R2: 0.38
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.85 | R2: 0.33
Fold 1

[I 2025-07-11 19:39:17,057] Trial 24 finished with value: 0.32658573079036246 and parameters: {'kernel': 'rbf', 'C': 5.099083280150034, 'epsilon': 0.08532552897399563, 'gamma': 'scale'}. Best is trial 21 with value: 0.37810301411450953.
[I 2025-07-11 19:39:17,058] A new study created in memory with name: no-name-d2a600d8-c3e3-4180-ba3b-ecdd63a622b2
[I 2025-07-11 19:39:17,118] Trial 0 finished with value: 0.36935429778219 and parameters: {'n_neighbors': 9, 'weights': 'uniform', 'leaf_size': 37}. Best is trial 0 with value: 0.36935429778219.
[I 2025-07-11 19:39:17,176] Trial 1 finished with value: 0.3495236529862402 and parameters: {'n_neighbors': 5, 'weights': 'uniform', 'leaf_size': 35}. Best is trial 0 with value: 0.36935429778219.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.84 | R2: 0.33

✅ SVR - Mejor R2: 0.38
📋 Parámetros: {'kernel': 'rbf', 'C': 9.861250089652614, 'epsilon': 0.09541024655704211, 'gamma': 'scale'}

Buscando mejores hiperparámetros para KNN...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.75 | R2: 0.37
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.80 | R2: 0.35
Fold 1
Fold 2
Fold 3

[I 2025-07-11 19:39:17,233] Trial 2 finished with value: 0.3527970761851099 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'leaf_size': 18}. Best is trial 0 with value: 0.36935429778219.
[I 2025-07-11 19:39:17,294] Trial 3 finished with value: 0.3569947708984099 and parameters: {'n_neighbors': 10, 'weights': 'uniform', 'leaf_size': 21}. Best is trial 0 with value: 0.36935429778219.
[I 2025-07-11 19:39:17,356] Trial 4 finished with value: 0.39713973226613075 and parameters: {'n_neighbors': 4, 'weights': 'uniform', 'leaf_size': 39}. Best is trial 4 with value: 0.39713973226613075.
[I 2025-07-11 19:39:17,410] Trial 5 finished with value: 0.40394970234347793 and parameters: {'n_neighbors': 8, 'weights': 'distance', 'leaf_size': 12}. Best is trial 5 with value: 0.40394970234347793.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.79 | R2: 0.35
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.78 | R2: 0.36
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.69 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.0 sec
OOF RMSE: 2.68 | R2: 0.40

[I 2025-07-11 19:39:17,468] Trial 6 finished with value: 0.3276866918944681 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 19}. Best is trial 5 with value: 0.40394970234347793.
[I 2025-07-11 19:39:17,530] Trial 7 finished with value: 0.3934895479659243 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'leaf_size': 30}. Best is trial 5 with value: 0.40394970234347793.
[I 2025-07-11 19:39:17,591] Trial 8 finished with value: 0.39713973226613075 and parameters: {'n_neighbors': 4, 'weights': 'uniform', 'leaf_size': 19}. Best is trial 5 with value: 0.40394970234347793.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.84 | R2: 0.33
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.70 | R2: 0.39
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.69 | R2: 0.40
Fold 1
Fold 2

[I 2025-07-11 19:39:17,673] Trial 9 finished with value: 0.3495236529862402 and parameters: {'n_neighbors': 5, 'weights': 'uniform', 'leaf_size': 35}. Best is trial 5 with value: 0.40394970234347793.
[I 2025-07-11 19:39:17,749] Trial 10 finished with value: 0.37787554244127974 and parameters: {'n_neighbors': 15, 'weights': 'distance', 'leaf_size': 11}. Best is trial 5 with value: 0.40394970234347793.
[I 2025-07-11 19:39:17,817] Trial 11 finished with value: 0.40394970234347793 and parameters: {'n_neighbors': 8, 'weights': 'distance', 'leaf_size': 10}. Best is trial 5 with value: 0.40394970234347793.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.80 | R2: 0.35
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.73 | R2: 0.38
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.68 | R2: 0.40
Fold 1

[I 2025-07-11 19:39:17,884] Trial 12 finished with value: 0.40394970234347793 and parameters: {'n_neighbors': 8, 'weights': 'distance', 'leaf_size': 10}. Best is trial 5 with value: 0.40394970234347793.
[I 2025-07-11 19:39:17,957] Trial 13 finished with value: 0.4050945182784029 and parameters: {'n_neighbors': 11, 'weights': 'distance', 'leaf_size': 13}. Best is trial 13 with value: 0.4050945182784029.
[I 2025-07-11 19:39:18,023] Trial 14 finished with value: 0.3920945557687231 and parameters: {'n_neighbors': 12, 'weights': 'distance', 'leaf_size': 15}. Best is trial 13 with value: 0.4050945182784029.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.68 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.67 | R2: 0.41
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.70 | R2: 0.39
Fold 1

[I 2025-07-11 19:39:18,086] Trial 15 finished with value: 0.4050945182784029 and parameters: {'n_neighbors': 11, 'weights': 'distance', 'leaf_size': 25}. Best is trial 13 with value: 0.4050945182784029.
[I 2025-07-11 19:39:18,161] Trial 16 finished with value: 0.3922220329455519 and parameters: {'n_neighbors': 13, 'weights': 'distance', 'leaf_size': 25}. Best is trial 13 with value: 0.4050945182784029.
[I 2025-07-11 19:39:18,227] Trial 17 finished with value: 0.4050945182784029 and parameters: {'n_neighbors': 11, 'weights': 'distance', 'leaf_size': 27}. Best is trial 13 with value: 0.4050945182784029.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.67 | R2: 0.41
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.70 | R2: 0.39
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.67 | R2: 0.41
Fold 1

[I 2025-07-11 19:39:18,293] Trial 18 finished with value: 0.37787554244127974 and parameters: {'n_neighbors': 15, 'weights': 'distance', 'leaf_size': 23}. Best is trial 13 with value: 0.4050945182784029.
[I 2025-07-11 19:39:18,365] Trial 19 finished with value: 0.3920945557687231 and parameters: {'n_neighbors': 12, 'weights': 'distance', 'leaf_size': 30}. Best is trial 13 with value: 0.4050945182784029.
[I 2025-07-11 19:39:18,430] Trial 20 finished with value: 0.3922220329455519 and parameters: {'n_neighbors': 13, 'weights': 'distance', 'leaf_size': 16}. Best is trial 13 with value: 0.4050945182784029.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.73 | R2: 0.38
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.70 | R2: 0.39
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.70 | R2: 0.39
Fold 1

[I 2025-07-11 19:39:18,496] Trial 21 finished with value: 0.40202035536442327 and parameters: {'n_neighbors': 10, 'weights': 'distance', 'leaf_size': 27}. Best is trial 13 with value: 0.4050945182784029.
[I 2025-07-11 19:39:18,601] Trial 22 finished with value: 0.4050945182784029 and parameters: {'n_neighbors': 11, 'weights': 'distance', 'leaf_size': 29}. Best is trial 13 with value: 0.4050945182784029.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.68 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.67 | R2: 0.41
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 19:39:18,675] Trial 23 finished with value: 0.4050945182784029 and parameters: {'n_neighbors': 11, 'weights': 'distance', 'leaf_size': 24}. Best is trial 13 with value: 0.4050945182784029.
[I 2025-07-11 19:39:18,750] Trial 24 finished with value: 0.3922220329455519 and parameters: {'n_neighbors': 13, 'weights': 'distance', 'leaf_size': 32}. Best is trial 13 with value: 0.4050945182784029.
[I 2025-07-11 19:39:18,751] A new study created in memory with name: no-name-662acc1c-b050-460f-9b96-8794d989e00b
[I 2025-07-11 19:39:18,813] Trial 0 finished with value: 0.25514493088834145 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 0 with value: 0.25514493088834145.

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.67 | R2: 0.41
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.70 | R2: 0.39

✅ KNN - Mejor R2: 0.41
📋 Parámetros: {'n_neighbors': 11, 'weights': 'distance', 'leaf_size': 13}

Buscando mejores hiperparámetros para LR...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.99 | R2: 0.26
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.0 sec
OOF RMSE: 2.99 | R2: 0.26

[I 2025-07-11 19:39:18,866] Trial 1 finished with value: 0.25514493088834145 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 0 with value: 0.25514493088834145.
[I 2025-07-11 19:39:18,943] Trial 2 finished with value: -0.9331766272698212 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 0 with value: 0.25514493088834145.
[I 2025-07-11 19:39:19,020] Trial 3 finished with value: -0.9331766272698212 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 0 with value: 0.25514493088834145.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 4.82 | R2: -0.93
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 4.82 | R2: -0.93
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 19:39:19,112] Trial 4 finished with value: -0.9331766272144641 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 0 with value: 0.25514493088834145.

Fold 5
Running time: 0.1 sec
OOF RMSE: 4.82 | R2: -0.93
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 4.82 | R2: -0.93

[I 2025-07-11 19:39:19,287] Trial 5 finished with value: -0.9331766272144641 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 0 with value: 0.25514493088834145.
[I 2025-07-11 19:39:19,479] Trial 6 finished with value: -0.9331766272698212 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 0 with value: 0.25514493088834145.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 4.82 | R2: -0.93
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:39:19,560] Trial 7 finished with value: 0.25514493088834145 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 0 with value: 0.25514493088834145.
[I 2025-07-11 19:39:19,638] Trial 8 finished with value: -0.9331766272698212 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 0 with value: 0.25514493088834145.
[I 2025-07-11 19:39:19,712] Trial 9 finished with value: 0.2553266208117232 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 9 with value: 0.2553266208117232.

Running time: 0.1 sec
OOF RMSE: 2.99 | R2: 0.26
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 4.82 | R2: -0.93
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.99 | R2: 0.26
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 19:39:19,773] Trial 10 finished with value: 0.2553266208117232 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 9 with value: 0.2553266208117232.
[I 2025-07-11 19:39:19,835] Trial 11 finished with value: 0.2553266208117232 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 9 with value: 0.2553266208117232.
[I 2025-07-11 19:39:19,903] Trial 12 finished with value: 0.2553266208117232 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 9 with value: 0.2553266208117232.
[I 2025-07-11 19:39:19,959] Trial 13 finished with value: 0.2553266208117232 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 9 with value: 0.2553266208117232.

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.99 | R2: 0.26
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.99 | R2: 0.26
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.99 | R2: 0.26
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.99 | R2: 0.26
Fold 1

[I 2025-07-11 19:39:20,018] Trial 14 finished with value: 0.2553266208117232 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 9 with value: 0.2553266208117232.
[I 2025-07-11 19:39:20,096] Trial 15 finished with value: 0.2553266208117232 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 9 with value: 0.2553266208117232.
[I 2025-07-11 19:39:20,163] Trial 16 finished with value: 0.2553266208117232 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 9 with value: 0.2553266208117232.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.99 | R2: 0.26
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.99 | R2: 0.26
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.99 | R2: 0.26
Fold 1

[I 2025-07-11 19:39:20,222] Trial 17 finished with value: 0.2553266208117232 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 9 with value: 0.2553266208117232.
[I 2025-07-11 19:39:20,283] Trial 18 finished with value: 0.2553266208117232 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 9 with value: 0.2553266208117232.
[I 2025-07-11 19:39:20,342] Trial 19 finished with value: 0.2553266208117232 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 9 with value: 0.2553266208117232.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.99 | R2: 0.26
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.99 | R2: 0.26
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.99 | R2: 0.26
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 19:39:20,400] Trial 20 finished with value: 0.2553266208117232 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 9 with value: 0.2553266208117232.
[I 2025-07-11 19:39:20,460] Trial 21 finished with value: 0.2553266208117232 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 9 with value: 0.2553266208117232.
[I 2025-07-11 19:39:20,523] Trial 22 finished with value: 0.2553266208117232 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 9 with value: 0.2553266208117232.
[I 2025-07-11 19:39:20,578] Trial 23 finished with value: 0.2553266208117232 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 9 with value: 0.2553266208117232.

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.99 | R2: 0.26
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.99 | R2: 0.26
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.99 | R2: 0.26
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.99 | R2: 0.26
Fold 1

[I 2025-07-11 19:39:20,637] Trial 24 finished with value: 0.2553266208117232 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 9 with value: 0.2553266208117232.
[I 2025-07-11 19:39:20,638] A new study created in memory with name: no-name-fa55c8ef-41f3-4590-a031-21ee87a76544

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.99 | R2: 0.26

✅ LR - Mejor R2: 0.26
📋 Parámetros: {'fit_intercept': True, 'positive': True}

Buscando mejores hiperparámetros para RF...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:39:22,879] Trial 0 finished with value: 0.014698533801950076 and parameters: {'n_estimators': 100, 'max_depth': 8, 'min_samples_split': 4, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 0 with value: 0.014698533801950076.

Running time: 2.2 sec
OOF RMSE: 3.44 | R2: 0.01
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:39:35,130] Trial 1 finished with value: -0.011991850483421551 and parameters: {'n_estimators': 500, 'max_depth': 12, 'min_samples_split': 10, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 0 with value: 0.014698533801950076.

Running time: 12.2 sec
OOF RMSE: 3.49 | R2: -0.01
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:39:42,507] Trial 2 finished with value: 0.3472478992195902 and parameters: {'n_estimators': 500, 'max_depth': 10, 'min_samples_split': 8, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 2 with value: 0.3472478992195902.

Running time: 7.4 sec
OOF RMSE: 2.80 | R2: 0.35
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:39:57,902] Trial 3 finished with value: -0.04901791785209242 and parameters: {'n_estimators': 500, 'max_depth': 13, 'min_samples_split': 2, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 2 with value: 0.3472478992195902.

Running time: 15.4 sec
OOF RMSE: 3.55 | R2: -0.05
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:40:08,503] Trial 4 finished with value: -0.07252112478128958 and parameters: {'n_estimators': 500, 'max_depth': 8, 'min_samples_split': 9, 'min_samples_leaf': 4, 'bootstrap': False}. Best is trial 2 with value: 0.3472478992195902.

Running time: 10.6 sec
OOF RMSE: 3.59 | R2: -0.07
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:40:12,871] Trial 5 finished with value: 0.3492482720859701 and parameters: {'n_estimators': 300, 'max_depth': 14, 'min_samples_split': 6, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 5 with value: 0.3492482720859701.

Running time: 4.4 sec
OOF RMSE: 2.80 | R2: 0.35
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:40:20,777] Trial 6 finished with value: 0.35491315459363915 and parameters: {'n_estimators': 500, 'max_depth': 14, 'min_samples_split': 7, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 6 with value: 0.35491315459363915.

Running time: 7.9 sec
OOF RMSE: 2.78 | R2: 0.35
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:40:22,167] Trial 7 finished with value: 0.33743582168320674 and parameters: {'n_estimators': 100, 'max_depth': 12, 'min_samples_split': 2, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 6 with value: 0.35491315459363915.

Running time: 1.4 sec
OOF RMSE: 2.82 | R2: 0.34
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:40:26,527] Trial 8 finished with value: 0.34924803121137526 and parameters: {'n_estimators': 300, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 6 with value: 0.35491315459363915.

Running time: 4.4 sec
OOF RMSE: 2.80 | R2: 0.35
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:40:31,833] Trial 9 finished with value: 0.369209782501691 and parameters: {'n_estimators': 300, 'max_depth': 14, 'min_samples_split': 3, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 9 with value: 0.369209782501691.

Running time: 5.3 sec
OOF RMSE: 2.75 | R2: 0.37
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:40:35,654] Trial 10 finished with value: 0.3722443126909851 and parameters: {'n_estimators': 300, 'max_depth': 5, 'min_samples_split': 5, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 10 with value: 0.3722443126909851.

Running time: 3.8 sec
OOF RMSE: 2.75 | R2: 0.37
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:40:39,478] Trial 11 finished with value: 0.3722443126909851 and parameters: {'n_estimators': 300, 'max_depth': 5, 'min_samples_split': 5, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 10 with value: 0.3722443126909851.

Running time: 3.8 sec
OOF RMSE: 2.75 | R2: 0.37
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:40:43,284] Trial 12 finished with value: 0.3722443126909851 and parameters: {'n_estimators': 300, 'max_depth': 5, 'min_samples_split': 5, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 10 with value: 0.3722443126909851.

Running time: 3.8 sec
OOF RMSE: 2.75 | R2: 0.37
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:40:47,122] Trial 13 finished with value: 0.3722443126909851 and parameters: {'n_estimators': 300, 'max_depth': 5, 'min_samples_split': 5, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 10 with value: 0.3722443126909851.

Running time: 3.8 sec
OOF RMSE: 2.75 | R2: 0.37
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:40:51,574] Trial 14 finished with value: 0.37160822571636876 and parameters: {'n_estimators': 300, 'max_depth': 7, 'min_samples_split': 6, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 10 with value: 0.3722443126909851.

Running time: 4.4 sec
OOF RMSE: 2.75 | R2: 0.37
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:40:55,876] Trial 15 finished with value: 0.3706355632804724 and parameters: {'n_estimators': 300, 'max_depth': 6, 'min_samples_split': 4, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 10 with value: 0.3722443126909851.

Running time: 4.3 sec
OOF RMSE: 2.75 | R2: 0.37
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:41:00,310] Trial 16 finished with value: 0.37127987837708687 and parameters: {'n_estimators': 300, 'max_depth': 7, 'min_samples_split': 7, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 10 with value: 0.3722443126909851.

Running time: 4.4 sec
OOF RMSE: 2.75 | R2: 0.37
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:41:02,151] Trial 17 finished with value: 0.3634810647823129 and parameters: {'n_estimators': 100, 'max_depth': 10, 'min_samples_split': 4, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 10 with value: 0.3722443126909851.

Running time: 1.8 sec
OOF RMSE: 2.77 | R2: 0.36
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:41:09,140] Trial 18 finished with value: 0.017890726895472775 and parameters: {'n_estimators': 300, 'max_depth': 9, 'min_samples_split': 5, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 10 with value: 0.3722443126909851.

Running time: 7.0 sec
OOF RMSE: 3.44 | R2: 0.02
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:41:13,240] Trial 19 finished with value: 0.3718093026150968 and parameters: {'n_estimators': 300, 'max_depth': 6, 'min_samples_split': 7, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 10 with value: 0.3722443126909851.

Running time: 4.1 sec
OOF RMSE: 2.75 | R2: 0.37
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:41:14,554] Trial 20 finished with value: 0.36575262317179646 and parameters: {'n_estimators': 100, 'max_depth': 5, 'min_samples_split': 3, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 10 with value: 0.3722443126909851.

Running time: 1.3 sec
OOF RMSE: 2.76 | R2: 0.37
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:41:18,350] Trial 21 finished with value: 0.3722443126909851 and parameters: {'n_estimators': 300, 'max_depth': 5, 'min_samples_split': 5, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 10 with value: 0.3722443126909851.

Running time: 3.8 sec
OOF RMSE: 2.75 | R2: 0.37
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:41:22,610] Trial 22 finished with value: 0.37131865593457036 and parameters: {'n_estimators': 300, 'max_depth': 6, 'min_samples_split': 5, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 10 with value: 0.3722443126909851.

Running time: 4.3 sec
OOF RMSE: 2.75 | R2: 0.37
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:41:27,037] Trial 23 finished with value: 0.37160822571636876 and parameters: {'n_estimators': 300, 'max_depth': 7, 'min_samples_split': 6, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 10 with value: 0.3722443126909851.

Running time: 4.4 sec
OOF RMSE: 2.75 | R2: 0.37
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:41:30,885] Trial 24 finished with value: 0.3717405167533445 and parameters: {'n_estimators': 300, 'max_depth': 5, 'min_samples_split': 4, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 10 with value: 0.3722443126909851.
[I 2025-07-11 19:41:30,886] A new study created in memory with name: no-name-857766f6-3f89-4dfc-afc1-3378e8cc054a

Running time: 3.8 sec
OOF RMSE: 2.75 | R2: 0.37

✅ RF - Mejor R2: 0.37
📋 Parámetros: {'n_estimators': 300, 'max_depth': 5, 'min_samples_split': 5, 'min_samples_leaf': 1, 'bootstrap': True}

Buscando mejores hiperparámetros para CAT...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:41:57,049] Trial 0 finished with value: 0.3203918417918087 and parameters: {'iterations': 2000, 'learning_rate': 0.012444397321033637, 'depth': 7, 'l2_leaf_reg': 5.310180748371367}. Best is trial 0 with value: 0.3203918417918087.

Running time: 26.2 sec
OOF RMSE: 2.86 | R2: 0.32
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:41:58,413] Trial 1 finished with value: 0.3135705872908483 and parameters: {'iterations': 500, 'learning_rate': 0.015126669327004292, 'depth': 4, 'l2_leaf_reg': 8.761642976678122}. Best is trial 0 with value: 0.3203918417918087.

Running time: 1.4 sec
OOF RMSE: 2.87 | R2: 0.31
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:42:00,509] Trial 2 finished with value: 0.34635062985630016 and parameters: {'iterations': 500, 'learning_rate': 0.06510683258223626, 'depth': 5, 'l2_leaf_reg': 1.6317048553953484}. Best is trial 2 with value: 0.34635062985630016.

Running time: 2.1 sec
OOF RMSE: 2.80 | R2: 0.35
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:42:41,257] Trial 3 finished with value: 0.3443194675223227 and parameters: {'iterations': 500, 'learning_rate': 0.024391617899732643, 'depth': 9, 'l2_leaf_reg': 8.714801621601406}. Best is trial 2 with value: 0.34635062985630016.

Running time: 40.7 sec
OOF RMSE: 2.81 | R2: 0.34
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:43:22,628] Trial 4 finished with value: 0.37116236933351365 and parameters: {'iterations': 500, 'learning_rate': 0.011619013743704725, 'depth': 9, 'l2_leaf_reg': 3.466644607427795}. Best is trial 4 with value: 0.37116236933351365.

Running time: 41.4 sec
OOF RMSE: 2.75 | R2: 0.37
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:43:26,944] Trial 5 finished with value: 0.3355020346895553 and parameters: {'iterations': 1000, 'learning_rate': 0.09360389961578303, 'depth': 5, 'l2_leaf_reg': 3.956291864412811}. Best is trial 4 with value: 0.37116236933351365.

Running time: 4.3 sec
OOF RMSE: 2.83 | R2: 0.34
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:43:33,834] Trial 6 finished with value: 0.3347132091974139 and parameters: {'iterations': 500, 'learning_rate': 0.019621741668233755, 'depth': 7, 'l2_leaf_reg': 6.8423501460133345}. Best is trial 4 with value: 0.37116236933351365.

Running time: 6.9 sec
OOF RMSE: 2.83 | R2: 0.33
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:45:53,091] Trial 7 finished with value: 0.3591226690910535 and parameters: {'iterations': 1000, 'learning_rate': 0.010328387120231968, 'depth': 10, 'l2_leaf_reg': 4.212510511062803}. Best is trial 4 with value: 0.37116236933351365.

Running time: 139.3 sec
OOF RMSE: 2.78 | R2: 0.36
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:47:16,091] Trial 8 finished with value: 0.3663996127490672 and parameters: {'iterations': 1000, 'learning_rate': 0.03431638575371759, 'depth': 9, 'l2_leaf_reg': 4.008826586985389}. Best is trial 4 with value: 0.37116236933351365.

Running time: 83.0 sec
OOF RMSE: 2.76 | R2: 0.37
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:47:18,156] Trial 9 finished with value: 0.28258439523293777 and parameters: {'iterations': 500, 'learning_rate': 0.04684739589792793, 'depth': 5, 'l2_leaf_reg': 5.038358423831876}. Best is trial 4 with value: 0.37116236933351365.

Running time: 2.1 sec
OOF RMSE: 2.94 | R2: 0.28
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:48:30,028] Trial 10 finished with value: 0.35724661513189837 and parameters: {'iterations': 2000, 'learning_rate': 0.030197634750741817, 'depth': 8, 'l2_leaf_reg': 1.5340061509092893}. Best is trial 4 with value: 0.37116236933351365.

Running time: 71.9 sec
OOF RMSE: 2.78 | R2: 0.36
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:50:52,116] Trial 11 finished with value: 0.37301482300955857 and parameters: {'iterations': 1000, 'learning_rate': 0.041087203039384124, 'depth': 10, 'l2_leaf_reg': 2.8269283711892514}. Best is trial 11 with value: 0.37301482300955857.

Running time: 142.1 sec
OOF RMSE: 2.74 | R2: 0.37
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:53:13,652] Trial 12 finished with value: 0.3782121770668738 and parameters: {'iterations': 1000, 'learning_rate': 0.04469542812736312, 'depth': 10, 'l2_leaf_reg': 2.8294316096298737}. Best is trial 12 with value: 0.3782121770668738.
[I 2025-07-11 19:53:13,653] A new study created in memory with name: no-name-c6b03668-0fc2-4c1a-ab83-0ed3e1864922
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.424e-01, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.137e+00, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.951e+00, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 19:53:13,775] Trial 0 finished with value: 0.4243695016586646 and parameters: {'alpha': 0.012802203799512513, 'l1_ratio': 0.6279334938967378}. Best is trial 0 with value: 0.4243695016586646.

Running time: 141.5 sec
OOF RMSE: 2.73 | R2: 0.38

✅ CAT - Mejor R2: 0.38
📋 Parámetros: {'iterations': 1000, 'learning_rate': 0.04469542812736312, 'depth': 10, 'l2_leaf_reg': 2.8294316096298737}

Buscando mejores hiperparámetros para EN...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.63 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.708e-01, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.232e+00, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.827e+00, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.609e+00, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 19:53:13,874] Trial 1 finished with value: 0.43226043484267074 and parameters: {'alpha': 0.014074796403248139, 'l1_ratio': 0.872062271222858}. Best is trial 1 with value: 0.43226043484267074.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.626e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.579e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.711e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.163e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.844e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 19:53:14,025] Trial 2 finished with value: 0.2157548664752693 and parameters: {'alpha': 0.0005538843527824488, 'l1_ratio': 0.05430670106207325}. Best is trial 1 with value: 0.43226043484267074.

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.61 | R2: 0.43
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.07 | R2: 0.22
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.035e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.078e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.849e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.877e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(

Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.505e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 19:53:14,295] Trial 3 finished with value: 0.26187367587312615 and parameters: {'alpha': 0.0014184638530695367, 'l1_ratio': 0.2013476125478969}. Best is trial 1 with value: 0.43226043484267074.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.290e+00, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.343e+00, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.352e+01, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.327e-01, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(

Running time: 0.3 sec
OOF RMSE: 2.98 | R2: 0.26
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.917e+00, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 19:53:14,538] Trial 4 finished with value: 0.4278219128794192 and parameters: {'alpha': 0.00961297120201595, 'l1_ratio': 0.6897492100947618}. Best is trial 1 with value: 0.43226043484267074.
[I 2025-07-11 19:53:14,658] Trial 5 finished with value: 0.3499273551291967 and parameters: {'alpha': 0.8599534955110583, 'l1_ratio': 0.6152662085093216}. Best is trial 1 with value: 0.43226043484267074.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.279e+01, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.012e+01, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.610e+01, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(

Running time: 0.2 sec
OOF RMSE: 2.62 | R2: 0.43
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.79 | R2: 0.35
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.167e+01, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.976e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 19:53:14,802] Trial 6 finished with value: 0.37999399728217553 and parameters: {'alpha': 0.00476646450129663, 'l1_ratio': 0.5811119545880595}. Best is trial 1 with value: 0.43226043484267074.
[I 2025-07-11 19:53:14,909] Trial 7 finished with value: 0.3727319474703251 and parameters: {'alpha': 0.05232292604296246, 'l1_ratio': 0.5930061210584927}. Best is trial 1 with value: 0.43226043484267074.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.742e+01, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.026e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.73 | R2: 0.38
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.75 | R2: 0.37
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.077e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.493e+01, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.495e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 19:53:15,051] Trial 8 finished with value: 0.3045623938720765 and parameters: {'alpha': 0.0025135315346809187, 'l1_ratio': 0.6894831262744546}. Best is trial 1 with value: 0.43226043484267074.
[I 2025-07-11 19:53:15,123] Trial 9 finished with value: 0.34699012108402094 and parameters: {'alpha': 1.2821572057119224, 'l1_ratio': 0.35782964304070275}. Best is trial 1 with value: 0.43226043484267074.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.301e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.311e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.236e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.89 | R2: 0.30
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.80 | R2: 0.35
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.715e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.392e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 19:53:15,247] Trial 10 finished with value: 0.18933966029057658 and parameters: {'alpha': 0.0001481183584105079, 'l1_ratio': 0.9283740457732734}. Best is trial 1 with value: 0.43226043484267074.
[I 2025-07-11 19:53:15,341] Trial 11 finished with value: 0.3233564046401666 and parameters: {'alpha': 0.08066157531209463, 'l1_ratio': 0.9108233733346034}. Best is trial 1 with value: 0.43226043484267074.

Fold 5
Running time: 0.1 sec
OOF RMSE: 3.12 | R2: 0.19
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.85 | R2: 0.32
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:53:15,430] Trial 12 finished with value: 0.3151234022635395 and parameters: {'alpha': 0.147403854839061, 'l1_ratio': 0.810989529538871}. Best is trial 1 with value: 0.43226043484267074.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.122e-01, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.132e+00, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.453e+00, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.248e+00, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 19:53:15,550] Trial 13 finished with value: 0.42942832656507623 and parameters: {'alpha': 0.0143485189258359, 'l1_ratio': 0.7866609882706853}. Best is trial 1 with value: 0.43226043484267074.

Running time: 0.1 sec
OOF RMSE: 2.87 | R2: 0.32
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.62 | R2: 0.43
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:53:15,640] Trial 14 finished with value: 0.3151435277647707 and parameters: {'alpha': 0.1489710244910607, 'l1_ratio': 0.8066882967748785}. Best is trial 1 with value: 0.43226043484267074.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.864e-01, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 19:53:15,769] Trial 15 finished with value: 0.4030862515027057 and parameters: {'alpha': 0.021602003845963672, 'l1_ratio': 0.42895511388447105}. Best is trial 1 with value: 0.43226043484267074.

Running time: 0.1 sec
OOF RMSE: 2.87 | R2: 0.32
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.68 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 19:53:15,866] Trial 16 finished with value: -0.00027817151752640434 and parameters: {'alpha': 6.780283836226953, 'l1_ratio': 0.9648004905012761}. Best is trial 1 with value: 0.43226043484267074.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.029e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.767e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(

Fold 5
Running time: 0.1 sec
OOF RMSE: 3.47 | R2: -0.00
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.2 sec

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.603e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.517e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.352e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 19:53:16,050] Trial 17 finished with value: 0.18647023742318503 and parameters: {'alpha': 0.0006377283824433776, 'l1_ratio': 0.8068444238687609}. Best is trial 1 with value: 0.43226043484267074.
[I 2025-07-11 19:53:16,171] Trial 18 finished with value: 0.40771850284550515 and parameters: {'alpha': 0.03088331188931046, 'l1_ratio': 0.8363270466504202}. Best is trial 1 with value: 0.43226043484267074.

OOF RMSE: 3.13 | R2: 0.19
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.67 | R2: 0.41
Fold 1
Fold 2
Fold 3

[I 2025-07-11 19:53:16,337] Trial 19 finished with value: 0.36339556343030266 and parameters: {'alpha': 0.3906055261179438, 'l1_ratio': 0.9986283340348369}. Best is trial 1 with value: 0.43226043484267074.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.196e+01, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.424e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.434e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.112e+01, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.673e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 19:53:16,460] Trial 20 finished with value: 0.3704765166459765 and parameters: {'alpha': 0.004605817146427996, 'l1_ratio': 0.44118545039347146}. Best is trial 1 with value: 0.43226043484267074.

Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 2.77 | R2: 0.36
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.75 | R2: 0.37
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.786e+00, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.159e+00, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.669e+00, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.520e+00, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 19:53:16,591] Trial 21 finished with value: 0.4296655046404875 and parameters: {'alpha': 0.011737037782240093, 'l1_ratio': 0.7221970580049707}. Best is trial 1 with value: 0.43226043484267074.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.392e+00, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.720e+00, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.129e+01, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.100e-01, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.62 | R2: 0.43
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.421e+00, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 19:53:16,703] Trial 22 finished with value: 0.4282677050867917 and parameters: {'alpha': 0.009846809686245512, 'l1_ratio': 0.7145799146824485}. Best is trial 1 with value: 0.43226043484267074.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.711e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.592e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.191e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.575e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.813e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 19:53:16,824] Trial 23 finished with value: 0.22057809958290198 and parameters: {'alpha': 0.001379693205023675, 'l1_ratio': 0.8746420409315239}. Best is trial 1 with value: 0.43226043484267074.

Running time: 0.1 sec
OOF RMSE: 2.62 | R2: 0.43
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.06 | R2: 0.22
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 19:53:16,940] Trial 24 finished with value: 0.4084037209590804 and parameters: {'alpha': 0.028379496948338225, 'l1_ratio': 0.736377082565437}. Best is trial 1 with value: 0.43226043484267074.
[I 2025-07-11 19:53:16,942] A new study created in memory with name: no-name-05b168f3-222c-44a9-8283-7bcaf9e0d77b

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.67 | R2: 0.41

✅ EN - Mejor R2: 0.43
📋 Parámetros: {'alpha': 0.014074796403248139, 'l1_ratio': 0.872062271222858}

🔍 Optimizando en C2RCC_rhown_9x9_depth_lt_1...
Buscando mejores hiperparámetros para XGB...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:53:24,998] Trial 0 finished with value: 0.6168180750266832 and parameters: {'n_estimators': 2000, 'learning_rate': 0.06889711823281991, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.6036575992149354, 'colsample_bytree': 0.7148513659417435}. Best is trial 0 with value: 0.6168180750266832.

Running time: 8.0 sec
OOF RMSE: 2.15 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:53:31,058] Trial 1 finished with value: 0.6270066507075752 and parameters: {'n_estimators': 1000, 'learning_rate': 0.04852859186700995, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.6130967299554658, 'colsample_bytree': 0.8098090912707832}. Best is trial 1 with value: 0.6270066507075752.

Running time: 6.1 sec
OOF RMSE: 2.12 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:53:33,510] Trial 2 finished with value: 0.6167232849111272 and parameters: {'n_estimators': 500, 'learning_rate': 0.08086853044741724, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.9140770020192693, 'colsample_bytree': 0.8305381566139778}. Best is trial 1 with value: 0.6270066507075752.

Running time: 2.4 sec
OOF RMSE: 2.15 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:53:36,992] Trial 3 finished with value: 0.6569254197739676 and parameters: {'n_estimators': 500, 'learning_rate': 0.0631582041675009, 'max_depth': 8, 'min_child_weight': 1, 'subsample': 0.6921610445591854, 'colsample_bytree': 0.6684470911873759}. Best is trial 3 with value: 0.6569254197739676.

Running time: 3.5 sec
OOF RMSE: 2.03 | R2: 0.66
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:53:44,166] Trial 4 finished with value: 0.5639174422607174 and parameters: {'n_estimators': 1000, 'learning_rate': 0.00961195698650269, 'max_depth': 8, 'min_child_weight': 4, 'subsample': 0.8283614891699675, 'colsample_bytree': 0.9879385173174315}. Best is trial 3 with value: 0.6569254197739676.

Running time: 7.2 sec
OOF RMSE: 2.29 | R2: 0.56
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:53:50,752] Trial 5 finished with value: 0.5330359863445613 and parameters: {'n_estimators': 1000, 'learning_rate': 0.04646939373171398, 'max_depth': 8, 'min_child_weight': 4, 'subsample': 0.6823914460792158, 'colsample_bytree': 0.7308630208502501}. Best is trial 3 with value: 0.6569254197739676.

Running time: 6.6 sec
OOF RMSE: 2.37 | R2: 0.53
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:54:01,046] Trial 6 finished with value: 0.5195393244573581 and parameters: {'n_estimators': 2000, 'learning_rate': 0.04775581838899043, 'max_depth': 8, 'min_child_weight': 4, 'subsample': 0.6567838278855374, 'colsample_bytree': 0.8957753127159769}. Best is trial 3 with value: 0.6569254197739676.

Running time: 10.3 sec
OOF RMSE: 2.40 | R2: 0.52
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:54:12,888] Trial 7 finished with value: 0.6205286994650436 and parameters: {'n_estimators': 2000, 'learning_rate': 0.01966102695055093, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.7890604062603591, 'colsample_bytree': 0.7897744077007182}. Best is trial 3 with value: 0.6569254197739676.

Running time: 11.8 sec
OOF RMSE: 2.14 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:54:22,473] Trial 8 finished with value: 0.5685570864383297 and parameters: {'n_estimators': 2000, 'learning_rate': 0.005507214532998318, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.9305079272116845, 'colsample_bytree': 0.9791116012303442}. Best is trial 3 with value: 0.6569254197739676.

Running time: 9.6 sec
OOF RMSE: 2.28 | R2: 0.57
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:54:32,137] Trial 9 finished with value: 0.5923856087921426 and parameters: {'n_estimators': 2000, 'learning_rate': 0.008433712479723436, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.9620480238952691, 'colsample_bytree': 0.7336319167355556}. Best is trial 3 with value: 0.6569254197739676.

Running time: 9.7 sec
OOF RMSE: 2.21 | R2: 0.59
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:54:35,090] Trial 10 finished with value: 0.6383909011588901 and parameters: {'n_estimators': 500, 'learning_rate': 0.02370628768389244, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.7473929774551168, 'colsample_bytree': 0.6022266498517466}. Best is trial 3 with value: 0.6569254197739676.

Running time: 2.9 sec
OOF RMSE: 2.08 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:54:38,197] Trial 11 finished with value: 0.6385281328894041 and parameters: {'n_estimators': 500, 'learning_rate': 0.021220173711749876, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.7430586360728721, 'colsample_bytree': 0.6000521191423114}. Best is trial 3 with value: 0.6569254197739676.

Running time: 3.1 sec
OOF RMSE: 2.08 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:54:40,906] Trial 12 finished with value: 0.6429882851409088 and parameters: {'n_estimators': 500, 'learning_rate': 0.024554392295406884, 'max_depth': 6, 'min_child_weight': 1, 'subsample': 0.7223747496436902, 'colsample_bytree': 0.622174633319938}. Best is trial 3 with value: 0.6569254197739676.

Running time: 2.7 sec
OOF RMSE: 2.07 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:54:43,724] Trial 13 finished with value: 0.6412930016418731 and parameters: {'n_estimators': 500, 'learning_rate': 0.031967622358039, 'max_depth': 6, 'min_child_weight': 1, 'subsample': 0.6981955088419267, 'colsample_bytree': 0.6669093566137417}. Best is trial 3 with value: 0.6569254197739676.

Running time: 2.8 sec
OOF RMSE: 2.08 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:54:46,486] Trial 14 finished with value: 0.6368483415227826 and parameters: {'n_estimators': 500, 'learning_rate': 0.012982493687970897, 'max_depth': 6, 'min_child_weight': 1, 'subsample': 0.8384254177450244, 'colsample_bytree': 0.6474546315660751}. Best is trial 3 with value: 0.6569254197739676.

Running time: 2.8 sec
OOF RMSE: 2.09 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:54:48,914] Trial 15 finished with value: 0.5872241122589212 and parameters: {'n_estimators': 500, 'learning_rate': 0.03220675791729201, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.7334547153641353, 'colsample_bytree': 0.6631244981270771}. Best is trial 3 with value: 0.6569254197739676.

Running time: 2.4 sec
OOF RMSE: 2.23 | R2: 0.59
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:54:51,665] Trial 16 finished with value: 0.6201428305454391 and parameters: {'n_estimators': 500, 'learning_rate': 0.09195367751401155, 'max_depth': 8, 'min_child_weight': 1, 'subsample': 0.7820286441516618, 'colsample_bytree': 0.6776998685456186}. Best is trial 3 with value: 0.6569254197739676.

Running time: 2.7 sec
OOF RMSE: 2.14 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:54:55,006] Trial 17 finished with value: 0.6455377643900369 and parameters: {'n_estimators': 500, 'learning_rate': 0.015841547012986627, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.6560654055244842, 'colsample_bytree': 0.7625505807373846}. Best is trial 3 with value: 0.6569254197739676.

Running time: 3.3 sec
OOF RMSE: 2.06 | R2: 0.65
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:54:58,011] Trial 18 finished with value: 0.5987774772063401 and parameters: {'n_estimators': 500, 'learning_rate': 0.013135474736090778, 'max_depth': 8, 'min_child_weight': 3, 'subsample': 0.6510122385360142, 'colsample_bytree': 0.7693465359841742}. Best is trial 3 with value: 0.6569254197739676.

Running time: 3.0 sec
OOF RMSE: 2.20 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:55:01,404] Trial 19 finished with value: 0.642411645314895 and parameters: {'n_estimators': 500, 'learning_rate': 0.01477065849550394, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.6486278272632741, 'colsample_bytree': 0.8669155146711237}. Best is trial 3 with value: 0.6569254197739676.

Running time: 3.4 sec
OOF RMSE: 2.07 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:55:08,333] Trial 20 finished with value: 0.6266650354885579 and parameters: {'n_estimators': 1000, 'learning_rate': 0.035069801270264066, 'max_depth': 8, 'min_child_weight': 1, 'subsample': 0.8742914566481051, 'colsample_bytree': 0.7013607101446583}. Best is trial 3 with value: 0.6569254197739676.

Running time: 6.9 sec
OOF RMSE: 2.12 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:55:11,160] Trial 21 finished with value: 0.6452738248300157 and parameters: {'n_estimators': 500, 'learning_rate': 0.017361747341985832, 'max_depth': 6, 'min_child_weight': 1, 'subsample': 0.7215793144466436, 'colsample_bytree': 0.6291871354865686}. Best is trial 3 with value: 0.6569254197739676.

Running time: 2.8 sec
OOF RMSE: 2.06 | R2: 0.65
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:55:14,392] Trial 22 finished with value: 0.6480302501479589 and parameters: {'n_estimators': 500, 'learning_rate': 0.01667753367819933, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.6899539026902431, 'colsample_bytree': 0.7635660245112721}. Best is trial 3 with value: 0.6569254197739676.

Running time: 3.2 sec
OOF RMSE: 2.06 | R2: 0.65
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:55:17,316] Trial 23 finished with value: 0.6364347021766301 and parameters: {'n_estimators': 500, 'learning_rate': 0.009697427978666861, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.6710454419137527, 'colsample_bytree': 0.7562746769141777}. Best is trial 3 with value: 0.6569254197739676.

Running time: 2.9 sec
OOF RMSE: 2.09 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:55:20,679] Trial 24 finished with value: 0.6554862678478428 and parameters: {'n_estimators': 500, 'learning_rate': 0.007235285983561124, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.6158207177660527, 'colsample_bytree': 0.8303037083673639}. Best is trial 3 with value: 0.6569254197739676.
[I 2025-07-11 19:55:20,682] A new study created in memory with name: no-name-61511736-a8aa-48a5-ada0-4408a751a27e

Running time: 3.4 sec
OOF RMSE: 2.03 | R2: 0.66

✅ XGB - Mejor R2: 0.66
📋 Parámetros: {'n_estimators': 500, 'learning_rate': 0.0631582041675009, 'max_depth': 8, 'min_child_weight': 1, 'subsample': 0.6921610445591854, 'colsample_bytree': 0.6684470911873759}

Buscando mejores hiperparámetros para LBM...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:55:20,895] Trial 0 finished with value: 0.5477424510383713 and parameters: {'learning_rate': 0.00699127413827243, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 19, 'subsample': 0.9960411261292116, 'colsample_bytree': 0.6952853921415884, 'n_estimators': 500}. Best is trial 0 with value: 0.5477424510383713.

Running time: 0.2 sec
OOF RMSE: 2.33 | R2: 0.55
Fold 1
Fold 2
Fold 3

[I 2025-07-11 19:55:21,262] Trial 1 finished with value: 0.5627818033529507 and parameters: {'learning_rate': 0.005972897389997448, 'num_leaves': 60, 'max_depth': 8, 'min_child_samples': 11, 'subsample': 0.6053045285185622, 'colsample_bytree': 0.7354778791131561, 'n_estimators': 500}. Best is trial 1 with value: 0.5627818033529507.

Fold 4
Fold 5
Running time: 0.4 sec
OOF RMSE: 2.29 | R2: 0.56
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:55:21,905] Trial 2 finished with value: 0.44203163237597864 and parameters: {'learning_rate': 0.011475001845782241, 'num_leaves': 40, 'max_depth': 7, 'min_child_samples': 7, 'subsample': 0.736007128280882, 'colsample_bytree': 0.9743253670691898, 'n_estimators': 1000}. Best is trial 1 with value: 0.5627818033529507.

Running time: 0.6 sec
OOF RMSE: 2.59 | R2: 0.44
Fold 1
Fold 2
Fold 3

[I 2025-07-11 19:55:22,355] Trial 3 finished with value: 0.5267898445176603 and parameters: {'learning_rate': 0.04280394556995481, 'num_leaves': 40, 'max_depth': 6, 'min_child_samples': 20, 'subsample': 0.8427990270637347, 'colsample_bytree': 0.74576314014822, 'n_estimators': 1000}. Best is trial 1 with value: 0.5627818033529507.

Fold 4
Fold 5
Running time: 0.4 sec
OOF RMSE: 2.38 | R2: 0.53
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:55:23,216] Trial 4 finished with value: 0.49454682259139215 and parameters: {'learning_rate': 0.019014202774793997, 'num_leaves': 60, 'max_depth': 5, 'min_child_samples': 9, 'subsample': 0.9031700968157195, 'colsample_bytree': 0.9799002835645636, 'n_estimators': 2000}. Best is trial 1 with value: 0.5627818033529507.

Running time: 0.9 sec
OOF RMSE: 2.46 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:55:23,772] Trial 5 finished with value: 0.5592784877171386 and parameters: {'learning_rate': 0.06016772298144221, 'num_leaves': 40, 'max_depth': 6, 'min_child_samples': 23, 'subsample': 0.8540050996546967, 'colsample_bytree': 0.9388055834434745, 'n_estimators': 1000}. Best is trial 1 with value: 0.5627818033529507.

Running time: 0.6 sec
OOF RMSE: 2.30 | R2: 0.56
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 19:55:24,674] Trial 6 finished with value: 0.5434638461923846 and parameters: {'learning_rate': 0.022502055292179485, 'num_leaves': 40, 'max_depth': 6, 'min_child_samples': 22, 'subsample': 0.6712031471650782, 'colsample_bytree': 0.9927118574685028, 'n_estimators': 2000}. Best is trial 1 with value: 0.5627818033529507.

Fold 5
Running time: 0.9 sec
OOF RMSE: 2.34 | R2: 0.54
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:55:24,982] Trial 7 finished with value: 0.5710536197215565 and parameters: {'learning_rate': 0.014176828322284184, 'num_leaves': 80, 'max_depth': 7, 'min_child_samples': 11, 'subsample': 0.881108272951912, 'colsample_bytree': 0.7772585725479899, 'n_estimators': 500}. Best is trial 7 with value: 0.5710536197215565.

Running time: 0.3 sec
OOF RMSE: 2.27 | R2: 0.57
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:55:25,206] Trial 8 finished with value: 0.5044579833610816 and parameters: {'learning_rate': 0.08959350805289819, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 17, 'subsample': 0.8464733373672648, 'colsample_bytree': 0.8305114024622638, 'n_estimators': 500}. Best is trial 7 with value: 0.5710536197215565.

Running time: 0.2 sec
OOF RMSE: 2.44 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 19:55:25,486] Trial 9 finished with value: 0.4491417250281198 and parameters: {'learning_rate': 0.08767647473946749, 'num_leaves': 40, 'max_depth': 7, 'min_child_samples': 16, 'subsample': 0.7295680828625531, 'colsample_bytree': 0.6325936379300021, 'n_estimators': 500}. Best is trial 7 with value: 0.5710536197215565.

Fold 5
Running time: 0.3 sec
OOF RMSE: 2.57 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:55:25,847] Trial 10 finished with value: 0.5551298005240911 and parameters: {'learning_rate': 0.025351605808886266, 'num_leaves': 80, 'max_depth': 8, 'min_child_samples': 12, 'subsample': 0.9632184985303613, 'colsample_bytree': 0.8578645129666373, 'n_estimators': 500}. Best is trial 7 with value: 0.5710536197215565.

Running time: 0.4 sec
OOF RMSE: 2.31 | R2: 0.56
Fold 1
Fold 2
Fold 3

[I 2025-07-11 19:55:26,223] Trial 11 finished with value: 0.5667410832462589 and parameters: {'learning_rate': 0.007020707605352962, 'num_leaves': 60, 'max_depth': 8, 'min_child_samples': 12, 'subsample': 0.605930173992936, 'colsample_bytree': 0.7536854833763457, 'n_estimators': 500}. Best is trial 7 with value: 0.5710536197215565.

Fold 4
Fold 5
Running time: 0.4 sec
OOF RMSE: 2.28 | R2: 0.57
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 19:55:26,662] Trial 12 finished with value: 0.4975890180748771 and parameters: {'learning_rate': 0.010518452962505484, 'num_leaves': 80, 'max_depth': 8, 'min_child_samples': 5, 'subsample': 0.7599101791716658, 'colsample_bytree': 0.7905985139690795, 'n_estimators': 500}. Best is trial 7 with value: 0.5710536197215565.

Fold 5
Running time: 0.4 sec
OOF RMSE: 2.46 | R2: 0.50
Fold 1
Fold 2

[I 2025-07-11 19:55:27,002] Trial 13 finished with value: 0.552191600499977 and parameters: {'learning_rate': 0.010338738653073115, 'num_leaves': 80, 'max_depth': 7, 'min_child_samples': 13, 'subsample': 0.6120825428261579, 'colsample_bytree': 0.876399446686464, 'n_estimators': 500}. Best is trial 7 with value: 0.5710536197215565.

Fold 3
Fold 4
Fold 5
Running time: 0.3 sec
OOF RMSE: 2.32 | R2: 0.55
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 19:55:27,328] Trial 14 finished with value: 0.5557769525575331 and parameters: {'learning_rate': 0.013628901247334204, 'num_leaves': 60, 'max_depth': 8, 'min_child_samples': 14, 'subsample': 0.9171250686997273, 'colsample_bytree': 0.6753796374370291, 'n_estimators': 500}. Best is trial 7 with value: 0.5710536197215565.

Fold 5
Running time: 0.3 sec
OOF RMSE: 2.31 | R2: 0.56
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:55:28,467] Trial 15 finished with value: 0.5656878563968419 and parameters: {'learning_rate': 0.005076517268312671, 'num_leaves': 80, 'max_depth': 7, 'min_child_samples': 10, 'subsample': 0.7960579443524367, 'colsample_bytree': 0.7780373378930261, 'n_estimators': 2000}. Best is trial 7 with value: 0.5710536197215565.

Running time: 1.1 sec
OOF RMSE: 2.28 | R2: 0.57
Fold 1
Fold 2
Fold 3

[I 2025-07-11 19:55:28,859] Trial 16 finished with value: 0.5348943666383162 and parameters: {'learning_rate': 0.007278089847421557, 'num_leaves': 60, 'max_depth': 8, 'min_child_samples': 8, 'subsample': 0.6665136187552065, 'colsample_bytree': 0.9020806182879437, 'n_estimators': 500}. Best is trial 7 with value: 0.5710536197215565.

Fold 4
Fold 5
Running time: 0.4 sec
OOF RMSE: 2.36 | R2: 0.53
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:55:29,170] Trial 17 finished with value: 0.5629579495645889 and parameters: {'learning_rate': 0.015427493049893883, 'num_leaves': 60, 'max_depth': 7, 'min_child_samples': 15, 'subsample': 0.8982018954536637, 'colsample_bytree': 0.6112448257165758, 'n_estimators': 500}. Best is trial 7 with value: 0.5710536197215565.

Running time: 0.3 sec
OOF RMSE: 2.29 | R2: 0.56
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:55:30,449] Trial 18 finished with value: 0.4362488496159155 and parameters: {'learning_rate': 0.03446426282900254, 'num_leaves': 80, 'max_depth': 8, 'min_child_samples': 7, 'subsample': 0.6623842546650821, 'colsample_bytree': 0.7221478761528124, 'n_estimators': 2000}. Best is trial 7 with value: 0.5710536197215565.

Running time: 1.3 sec
OOF RMSE: 2.60 | R2: 0.44
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 19:55:31,171] Trial 19 finished with value: 0.4840186005198537 and parameters: {'learning_rate': 0.008668792142260505, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 5, 'subsample': 0.804426127512076, 'colsample_bytree': 0.8233219045549864, 'n_estimators': 1000}. Best is trial 7 with value: 0.5710536197215565.

Fold 5
Running time: 0.7 sec
OOF RMSE: 2.49 | R2: 0.48
Fold 1
Fold 2

[I 2025-07-11 19:55:31,436] Trial 20 finished with value: 0.5991912119590304 and parameters: {'learning_rate': 0.017054386949525113, 'num_leaves': 60, 'max_depth': 6, 'min_child_samples': 18, 'subsample': 0.9340370764017192, 'colsample_bytree': 0.664330316009649, 'n_estimators': 500}. Best is trial 20 with value: 0.5991912119590304.

Fold 3
Fold 4
Fold 5
Running time: 0.3 sec
OOF RMSE: 2.19 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:55:31,750] Trial 21 finished with value: 0.6000869560338888 and parameters: {'learning_rate': 0.016882035886025205, 'num_leaves': 60, 'max_depth': 6, 'min_child_samples': 19, 'subsample': 0.9348314257301494, 'colsample_bytree': 0.6665201569505533, 'n_estimators': 500}. Best is trial 21 with value: 0.6000869560338888.

Running time: 0.3 sec
OOF RMSE: 2.19 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 19:55:32,004] Trial 22 finished with value: 0.5720163873406827 and parameters: {'learning_rate': 0.018017419677880134, 'num_leaves': 60, 'max_depth': 6, 'min_child_samples': 25, 'subsample': 0.9330394394002952, 'colsample_bytree': 0.6623485493965624, 'n_estimators': 500}. Best is trial 21 with value: 0.6000869560338888.

Fold 5
Running time: 0.2 sec
OOF RMSE: 2.27 | R2: 0.57
Fold 1
Fold 2
Fold 3

[I 2025-07-11 19:55:32,268] Trial 23 finished with value: 0.5795828970300423 and parameters: {'learning_rate': 0.030090536616311798, 'num_leaves': 60, 'max_depth': 6, 'min_child_samples': 25, 'subsample': 0.946739056855418, 'colsample_bytree': 0.6552769335852537, 'n_estimators': 500}. Best is trial 21 with value: 0.6000869560338888.

Fold 4
Fold 5
Running time: 0.3 sec
OOF RMSE: 2.25 | R2: 0.58
Fold 1
Fold 2

[I 2025-07-11 19:55:32,552] Trial 24 finished with value: 0.5786524660011609 and parameters: {'learning_rate': 0.03346522245475731, 'num_leaves': 60, 'max_depth': 6, 'min_child_samples': 18, 'subsample': 0.9582773814653102, 'colsample_bytree': 0.6524931802201597, 'n_estimators': 500}. Best is trial 21 with value: 0.6000869560338888.
[I 2025-07-11 19:55:32,554] A new study created in memory with name: no-name-e1dac17f-b257-4e92-895d-2bbb770e0711

Fold 3
Fold 4
Fold 5
Running time: 0.3 sec
OOF RMSE: 2.25 | R2: 0.58

✅ LBM - Mejor R2: 0.60
📋 Parámetros: {'learning_rate': 0.016882035886025205, 'num_leaves': 60, 'max_depth': 6, 'min_child_samples': 19, 'subsample': 0.9348314257301494, 'colsample_bytree': 0.6665201569505533, 'n_estimators': 500}

Buscando mejores hiperparámetros para MLP...
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

[I 2025-07-11 19:55:34,927] Trial 0 finished with value: 0.44241795518208304 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.03314828555738874, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0013588830624971068}. Best is trial 0 with value: 0.44241795518208304.

Running time: 2.4 sec
OOF RMSE: 2.59 | R2: 0.44
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

[I 2025-07-11 19:55:36,924] Trial 1 finished with value: 0.54678169287675 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'tanh', 'solver': 'adam', 'alpha': 4.8670781227011846e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.000725627949987135}. Best is trial 1 with value: 0.54678169287675.

Running time: 2.0 sec
OOF RMSE: 2.33 | R2: 0.55
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 19:55:38,307] Trial 2 finished with value: 0.41100395486682917 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.0003594278524901736, 'learning_rate': 'constant', 'learning_rate_init': 0.00018616843302560304}. Best is trial 1 with value: 0.54678169287675.

Fold 4
Fold 5
Running time: 1.4 sec
OOF RMSE: 2.66 | R2: 0.41
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 19:55:39,003] Trial 3 finished with value: 0.5006321575566308 and parameters: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0039948027353788745, 'learning_rate': 'adaptive', 'learning_rate_init': 0.004802698281798329}. Best is trial 1 with value: 0.54678169287675.

Fold 5
Running time: 0.7 sec
OOF RMSE: 2.45 | R2: 0.50
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 19:55:39,952] Trial 4 finished with value: 0.49489243325239185 and parameters: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'adam', 'alpha': 5.5653155082196065e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.0027434541018719082}. Best is trial 1 with value: 0.54678169287675.

Fold 4
Fold 5
Running time: 0.9 sec
OOF RMSE: 2.46 | R2: 0.49
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

[I 2025-07-11 19:55:41,085] Trial 5 finished with value: 0.3765219313165429 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0014728974335847323, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00017592690162669745}. Best is trial 1 with value: 0.54678169287675.

Running time: 1.1 sec
OOF RMSE: 2.74 | R2: 0.38
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 19:55:42,870] Trial 6 finished with value: 0.5540680059790726 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.003954542726784112, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0007045868498449528}. Best is trial 6 with value: 0.5540680059790726.

Running time: 1.8 sec
OOF RMSE: 2.31 | R2: 0.55
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 19:55:45,020] Trial 7 finished with value: 0.5714793842260176 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.001800082623402473, 'learning_rate': 'constant', 'learning_rate_init': 0.000979159479879744}. Best is trial 7 with value: 0.5714793842260176.

Fold 5
Running time: 2.1 sec
OOF RMSE: 2.27 | R2: 0.57
Fold 1
Fold 2
Fold 3

[I 2025-07-11 19:55:45,874] Trial 8 finished with value: 0.37566443505388003 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.009620945049238168, 'learning_rate': 'constant', 'learning_rate_init': 0.004498440735891664}. Best is trial 7 with value: 0.5714793842260176.

Fold 4
Fold 5
Running time: 0.8 sec
OOF RMSE: 2.74 | R2: 0.38
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 19:55:47,133] Trial 9 finished with value: 0.63774998536215 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'adam', 'alpha': 7.429221869351156e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0047841907282560854}. Best is trial 9 with value: 0.63774998536215.

Fold 5
Running time: 1.3 sec
OOF RMSE: 2.09 | R2: 0.64
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

[I 2025-07-11 19:55:48,658] Trial 10 finished with value: 0.3746384685704496 and parameters: {'hidden_layer_sizes': '50', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.0001866355286123119, 'learning_rate': 'adaptive', 'learning_rate_init': 0.008511200713742567}. Best is trial 9 with value: 0.63774998536215.

Running time: 1.5 sec
OOF RMSE: 2.74 | R2: 0.37
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3
Fold 4

[I 2025-07-11 19:55:50,683] Trial 11 finished with value: 0.5749207607690556 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'adam', 'alpha': 1.3876183293229914e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.0015132002370749817}. Best is trial 9 with value: 0.63774998536215.

Fold 5
Running time: 2.0 sec
OOF RMSE: 2.26 | R2: 0.57
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3
Fold 4

[I 2025-07-11 19:55:52,487] Trial 12 finished with value: 0.6299251220647347 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'adam', 'alpha': 1.3078489428575307e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.0020457632856513584}. Best is trial 9 with value: 0.63774998536215.

Fold 5
Running time: 1.8 sec
OOF RMSE: 2.11 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 19:55:54,090] Trial 13 finished with value: 0.6334420710926674 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'adam', 'alpha': 1.329986565294897e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.0028591338922319834}. Best is trial 9 with value: 0.63774998536215.

Fold 5
Running time: 1.6 sec
OOF RMSE: 2.10 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 19:55:55,193] Trial 14 finished with value: 0.6519301305355663 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'adam', 'alpha': 7.127663636261117e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00979462636171308}. Best is trial 14 with value: 0.6519301305355663.

Fold 5
Running time: 1.1 sec
OOF RMSE: 2.05 | R2: 0.65
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3
Fold 4

[I 2025-07-11 19:55:55,985] Trial 15 finished with value: 0.30369104945962166 and parameters: {'hidden_layer_sizes': '50', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.00021684864796636544, 'learning_rate': 'adaptive', 'learning_rate_init': 0.007328121129732734}. Best is trial 14 with value: 0.6519301305355663.

Fold 5
Running time: 0.8 sec
OOF RMSE: 2.89 | R2: 0.30
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 19:55:57,173] Trial 16 finished with value: 0.6164901996234577 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'adam', 'alpha': 6.6687805875351e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.009136764161979831}. Best is trial 14 with value: 0.6519301305355663.

Fold 5
Running time: 1.2 sec
OOF RMSE: 2.15 | R2: 0.62
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 19:55:59,821] Trial 17 finished with value: 0.5272489462103256 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0005422090439215295, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00040339788256645265}. Best is trial 14 with value: 0.6519301305355663.

Fold 5
Running time: 2.6 sec
OOF RMSE: 2.38 | R2: 0.53
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 19:56:02,503] Trial 18 finished with value: 0.606481906618963 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 9.452025092014201e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.004810478493700155}. Best is trial 14 with value: 0.6519301305355663.

Running time: 2.7 sec
OOF RMSE: 2.17 | R2: 0.61
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3
Fold 4

[I 2025-07-11 19:56:03,234] Trial 19 finished with value: 0.3538604062812414 and parameters: {'hidden_layer_sizes': '50', 'activation': 'tanh', 'solver': 'adam', 'alpha': 3.3570714510202244e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.005338991899449748}. Best is trial 14 with value: 0.6519301305355663.

Fold 5
Running time: 0.7 sec
OOF RMSE: 2.79 | R2: 0.35
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 19:56:04,842] Trial 20 finished with value: 0.6347548384173348 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.08176762160992544, 'learning_rate': 'adaptive', 'learning_rate_init': 0.003094356216264504}. Best is trial 14 with value: 0.6519301305355663.

Fold 5
Running time: 1.6 sec
OOF RMSE: 2.10 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 19:56:06,305] Trial 21 finished with value: 0.6317362841691239 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.07479904604111433, 'learning_rate': 'adaptive', 'learning_rate_init': 0.002775091761884246}. Best is trial 14 with value: 0.6519301305355663.

Fold 5
Running time: 1.5 sec
OOF RMSE: 2.10 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 19:56:07,854] Trial 22 finished with value: 0.6362511469453074 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.023491239304152946, 'learning_rate': 'adaptive', 'learning_rate_init': 0.003658004625098036}. Best is trial 14 with value: 0.6519301305355663.

Fold 5
Running time: 1.5 sec
OOF RMSE: 2.09 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 19:56:08,977] Trial 23 finished with value: 0.6321146636624169 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.018233362442115018, 'learning_rate': 'adaptive', 'learning_rate_init': 0.006566711312933449}. Best is trial 14 with value: 0.6519301305355663.

Fold 5
Running time: 1.1 sec
OOF RMSE: 2.10 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 19:56:10,230] Trial 24 finished with value: 0.6154238299463176 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0006903236266355287, 'learning_rate': 'adaptive', 'learning_rate_init': 0.009477315140324188}. Best is trial 14 with value: 0.6519301305355663.
[I 2025-07-11 19:56:10,231] A new study created in memory with name: no-name-d976fbc3-a19a-4106-838b-8b8594154254
[I 2025-07-11 19:56:10,321] Trial 0 finished with value: -43.95402332272048 and parameters: {'kernel': 'sigmoid', 'C': 3.9512967541883235, 'epsilon': 0.16322727615025365, 'gamma': 'scale'}. Best is trial 0 with value: -43.95402332272048.

Fold 5
Running time: 1.2 sec
OOF RMSE: 2.15 | R2: 0.62

✅ MLP - Mejor R2: 0.65
📋 Parámetros: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'adam', 'alpha': 7.127663636261117e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00979462636171308}

Buscando mejores hiperparámetros para SVR...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 23.24 | R2: -43.95
Fold 1
Fold 2
Fold 3

[I 2025-07-11 19:56:10,397] Trial 1 finished with value: 0.0691047226271545 and parameters: {'kernel': 'sigmoid', 'C': 0.10895300276646082, 'epsilon': 0.03694732429218185, 'gamma': 'scale'}. Best is trial 1 with value: 0.0691047226271545.
[I 2025-07-11 19:56:10,476] Trial 2 finished with value: 0.45378138107567734 and parameters: {'kernel': 'rbf', 'C': 4.228298719056419, 'epsilon': 0.032656397676967513, 'gamma': 'auto'}. Best is trial 2 with value: 0.45378138107567734.
[I 2025-07-11 19:56:10,546] Trial 3 finished with value: 0.08729232862367964 and parameters: {'kernel': 'sigmoid', 'C': 0.24382715898702778, 'epsilon': 0.08376500053486617, 'gamma': 'auto'}. Best is trial 2 with value: 0.45378138107567734.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.34 | R2: 0.07
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.56 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.31 | R2: 0.09
Fold 1
Fold 2

[I 2025-07-11 19:56:10,611] Trial 4 finished with value: 0.4680896581270326 and parameters: {'kernel': 'rbf', 'C': 3.824969342703164, 'epsilon': 0.1626075186834458, 'gamma': 'scale'}. Best is trial 4 with value: 0.4680896581270326.
[I 2025-07-11 19:56:10,701] Trial 5 finished with value: -1.6444063866822756 and parameters: {'kernel': 'sigmoid', 'C': 1.0179279768324108, 'epsilon': 0.10170275621672954, 'gamma': 'auto'}. Best is trial 4 with value: 0.4680896581270326.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.53 | R2: 0.47
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 5.64 | R2: -1.64
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:56:10,781] Trial 6 finished with value: -1.1208578224904158 and parameters: {'kernel': 'sigmoid', 'C': 0.5441796356208961, 'epsilon': 0.09103898490387627, 'gamma': 'scale'}. Best is trial 4 with value: 0.4680896581270326.
[I 2025-07-11 19:56:10,854] Trial 7 finished with value: 0.06644926786697203 and parameters: {'kernel': 'sigmoid', 'C': 0.13307904287363867, 'epsilon': 0.1133375933950701, 'gamma': 'scale'}. Best is trial 4 with value: 0.4680896581270326.
[I 2025-07-11 19:56:10,923] Trial 8 finished with value: 0.4968298666072124 and parameters: {'kernel': 'rbf', 'C': 4.4212309314136, 'epsilon': 0.04422429912844686, 'gamma': 'scale'}. Best is trial 8 with value: 0.4968298666072124.

Running time: 0.1 sec
OOF RMSE: 5.05 | R2: -1.12
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.35 | R2: 0.07
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.46 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:56:10,992] Trial 9 finished with value: -97.6088160397913 and parameters: {'kernel': 'sigmoid', 'C': 8.984979683251014, 'epsilon': 0.03312504066173698, 'gamma': 'auto'}. Best is trial 8 with value: 0.4968298666072124.
[I 2025-07-11 19:56:11,070] Trial 10 finished with value: 0.3189988208244422 and parameters: {'kernel': 'rbf', 'C': 1.391566640429005, 'epsilon': 0.06034359570202971, 'gamma': 'scale'}. Best is trial 8 with value: 0.4968298666072124.
[I 2025-07-11 19:56:11,139] Trial 11 finished with value: 0.4043276412707535 and parameters: {'kernel': 'rbf', 'C': 2.722226090600326, 'epsilon': 0.18161281375621635, 'gamma': 'scale'}. Best is trial 8 with value: 0.4968298666072124.

Running time: 0.1 sec
OOF RMSE: 34.42 | R2: -97.61
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.86 | R2: 0.32
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.68 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 19:56:11,211] Trial 12 finished with value: 0.5754605827769693 and parameters: {'kernel': 'rbf', 'C': 7.909746898279308, 'epsilon': 0.1433909053399454, 'gamma': 'scale'}. Best is trial 12 with value: 0.5754605827769693.
[I 2025-07-11 19:56:11,291] Trial 13 finished with value: 0.5951073508739912 and parameters: {'kernel': 'rbf', 'C': 9.982347917307658, 'epsilon': 0.12977990086010743, 'gamma': 'scale'}. Best is trial 13 with value: 0.5951073508739912.
[I 2025-07-11 19:56:11,367] Trial 14 finished with value: 0.5864868640519628 and parameters: {'kernel': 'rbf', 'C': 8.678462611103098, 'epsilon': 0.1287558587767084, 'gamma': 'scale'}. Best is trial 13 with value: 0.5951073508739912.

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.26 | R2: 0.58
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.21 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.23 | R2: 0.59
Fold 1
Fold 2

[I 2025-07-11 19:56:11,454] Trial 15 finished with value: 0.5922129438590789 and parameters: {'kernel': 'rbf', 'C': 9.41102057041863, 'epsilon': 0.1260690601114348, 'gamma': 'scale'}. Best is trial 13 with value: 0.5951073508739912.
[I 2025-07-11 19:56:11,548] Trial 16 finished with value: 0.3620942833795121 and parameters: {'kernel': 'rbf', 'C': 2.030488802604289, 'epsilon': 0.13387142022062118, 'gamma': 'scale'}. Best is trial 13 with value: 0.5951073508739912.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.21 | R2: 0.59
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.77 | R2: 0.36
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:56:11,624] Trial 17 finished with value: 0.23561805494005994 and parameters: {'kernel': 'rbf', 'C': 0.6237808016174458, 'epsilon': 0.07037192531597047, 'gamma': 'scale'}. Best is trial 13 with value: 0.5951073508739912.
[I 2025-07-11 19:56:11,701] Trial 18 finished with value: 0.5117407086569343 and parameters: {'kernel': 'rbf', 'C': 6.150703265203794, 'epsilon': 0.1878827261813463, 'gamma': 'auto'}. Best is trial 13 with value: 0.5951073508739912.
[I 2025-07-11 19:56:11,781] Trial 19 finished with value: 0.3603197435616843 and parameters: {'kernel': 'rbf', 'C': 1.9938407919060916, 'epsilon': 0.11661544062604122, 'gamma': 'scale'}. Best is trial 13 with value: 0.5951073508739912.

Running time: 0.1 sec
OOF RMSE: 3.03 | R2: 0.24
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.42 | R2: 0.51
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.77 | R2: 0.36
Fold 1
Fold 2
Fold 3

[I 2025-07-11 19:56:11,852] Trial 20 finished with value: 0.5918826137138392 and parameters: {'kernel': 'rbf', 'C': 9.7499014756613, 'epsilon': 0.16879947739697693, 'gamma': 'scale'}. Best is trial 13 with value: 0.5951073508739912.
[I 2025-07-11 19:56:11,933] Trial 21 finished with value: 0.5924967651393878 and parameters: {'kernel': 'rbf', 'C': 9.727067907153451, 'epsilon': 0.15568166873430775, 'gamma': 'scale'}. Best is trial 13 with value: 0.5951073508739912.
[I 2025-07-11 19:56:12,009] Trial 22 finished with value: 0.5393938745301823 and parameters: {'kernel': 'rbf', 'C': 5.8644173314708015, 'epsilon': 0.14809640811627062, 'gamma': 'scale'}. Best is trial 13 with value: 0.5951073508739912.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.21 | R2: 0.59
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.21 | R2: 0.59
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.35 | R2: 0.54
Fold 1

[I 2025-07-11 19:56:12,084] Trial 23 finished with value: 0.533553557592727 and parameters: {'kernel': 'rbf', 'C': 5.618488194468106, 'epsilon': 0.12605656963272568, 'gamma': 'scale'}. Best is trial 13 with value: 0.5951073508739912.
[I 2025-07-11 19:56:12,164] Trial 24 finished with value: 0.40933938042107887 and parameters: {'kernel': 'rbf', 'C': 2.8157564612978616, 'epsilon': 0.19943247435712003, 'gamma': 'scale'}. Best is trial 13 with value: 0.5951073508739912.
[I 2025-07-11 19:56:12,165] A new study created in memory with name: no-name-8d1b626e-8fab-4e73-b765-10e9dca82d87
[I 2025-07-11 19:56:12,223] Trial 0 finished with value: 0.616137841799786 and parameters: {'n_neighbors': 7, 'weights': 'uniform', 'leaf_size': 25}. Best is trial 0 with value: 0.616137841799786.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.37 | R2: 0.53
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.66 | R2: 0.41

✅ SVR - Mejor R2: 0.60
📋 Parámetros: {'kernel': 'rbf', 'C': 9.982347917307658, 'epsilon': 0.12977990086010743, 'gamma': 'scale'}

Buscando mejores hiperparámetros para KNN...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.15 | R2: 0.62
Fold 1

[I 2025-07-11 19:56:12,285] Trial 1 finished with value: 0.5364965409943574 and parameters: {'n_neighbors': 11, 'weights': 'uniform', 'leaf_size': 27}. Best is trial 0 with value: 0.616137841799786.
[I 2025-07-11 19:56:12,348] Trial 2 finished with value: 0.5482582989018208 and parameters: {'n_neighbors': 12, 'weights': 'uniform', 'leaf_size': 11}. Best is trial 0 with value: 0.616137841799786.
[I 2025-07-11 19:56:12,411] Trial 3 finished with value: 0.5482582989018208 and parameters: {'n_neighbors': 12, 'weights': 'uniform', 'leaf_size': 40}. Best is trial 0 with value: 0.616137841799786.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.36 | R2: 0.54
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.33 | R2: 0.55
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.33 | R2: 0.55
Fold 1
Fold 2
Fold 3

[I 2025-07-11 19:56:12,469] Trial 4 finished with value: 0.6831335980119155 and parameters: {'n_neighbors': 5, 'weights': 'uniform', 'leaf_size': 16}. Best is trial 4 with value: 0.6831335980119155.
[I 2025-07-11 19:56:12,533] Trial 5 finished with value: 0.5514689745490318 and parameters: {'n_neighbors': 10, 'weights': 'uniform', 'leaf_size': 24}. Best is trial 4 with value: 0.6831335980119155.
[I 2025-07-11 19:56:12,620] Trial 6 finished with value: 0.6620840675521971 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'leaf_size': 12}. Best is trial 4 with value: 0.6831335980119155.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.95 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.32 | R2: 0.55
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.02 | R2: 0.66
Fold 1
Fold 2

[I 2025-07-11 19:56:12,693] Trial 7 finished with value: 0.5088854120930328 and parameters: {'n_neighbors': 14, 'weights': 'uniform', 'leaf_size': 34}. Best is trial 4 with value: 0.6831335980119155.
[I 2025-07-11 19:56:12,756] Trial 8 finished with value: 0.6157917213403961 and parameters: {'n_neighbors': 10, 'weights': 'distance', 'leaf_size': 19}. Best is trial 4 with value: 0.6831335980119155.
[I 2025-07-11 19:56:12,818] Trial 9 finished with value: 0.5006295683437758 and parameters: {'n_neighbors': 15, 'weights': 'uniform', 'leaf_size': 38}. Best is trial 4 with value: 0.6831335980119155.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.43 | R2: 0.51
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.15 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.45 | R2: 0.50
Fold 1
Fold 2
Fold 3

[I 2025-07-11 19:56:12,882] Trial 10 finished with value: 0.6660135893234005 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 17}. Best is trial 4 with value: 0.6831335980119155.
[I 2025-07-11 19:56:12,949] Trial 11 finished with value: 0.6660135893234005 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 17}. Best is trial 4 with value: 0.6831335980119155.
[I 2025-07-11 19:56:13,018] Trial 12 finished with value: 0.6660135893234005 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 17}. Best is trial 4 with value: 0.6831335980119155.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.00 | R2: 0.67
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.00 | R2: 0.67
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.00 | R2: 0.67
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 19:56:13,082] Trial 13 finished with value: 0.7097624176110084 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'leaf_size': 20}. Best is trial 13 with value: 0.7097624176110084.
[I 2025-07-11 19:56:13,151] Trial 14 finished with value: 0.6796061345161262 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'leaf_size': 21}. Best is trial 13 with value: 0.7097624176110084.
[I 2025-07-11 19:56:13,221] Trial 15 finished with value: 0.7097624176110084 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'leaf_size': 29}. Best is trial 13 with value: 0.7097624176110084.

Fold 5
Running time: 0.1 sec
OOF RMSE: 1.87 | R2: 0.71
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.96 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.87 | R2: 0.71
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:56:13,285] Trial 16 finished with value: 0.7097624176110084 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'leaf_size': 30}. Best is trial 13 with value: 0.7097624176110084.
[I 2025-07-11 19:56:13,353] Trial 17 finished with value: 0.6477696015854666 and parameters: {'n_neighbors': 8, 'weights': 'distance', 'leaf_size': 30}. Best is trial 13 with value: 0.7097624176110084.
[I 2025-07-11 19:56:13,424] Trial 18 finished with value: 0.7097624176110084 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'leaf_size': 33}. Best is trial 13 with value: 0.7097624176110084.
[I 2025-07-11 19:56:13,486] Trial 19 finished with value: 0.6477696015854666 and parameters: {'n_neighbors': 8, 'weights': 'distance', 'leaf_size': 22}. Best is trial 13 with value: 0.7097624176110084.

Running time: 0.1 sec
OOF RMSE: 1.87 | R2: 0.71
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.06 | R2: 0.65
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.87 | R2: 0.71
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.06 | R2: 0.65

[I 2025-07-11 19:56:13,553] Trial 20 finished with value: 0.6635736677316018 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'leaf_size': 27}. Best is trial 13 with value: 0.7097624176110084.
[I 2025-07-11 19:56:13,627] Trial 21 finished with value: 0.7097624176110084 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'leaf_size': 31}. Best is trial 13 with value: 0.7097624176110084.
[I 2025-07-11 19:56:13,696] Trial 22 finished with value: 0.6796061345161262 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'leaf_size': 29}. Best is trial 13 with value: 0.7097624176110084.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.01 | R2: 0.66
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.87 | R2: 0.71
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.96 | R2: 0.68

[I 2025-07-11 19:56:13,765] Trial 23 finished with value: 0.6635736677316018 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'leaf_size': 35}. Best is trial 13 with value: 0.7097624176110084.
[I 2025-07-11 19:56:13,874] Trial 24 finished with value: 0.6796061345161262 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'leaf_size': 27}. Best is trial 13 with value: 0.7097624176110084.
[I 2025-07-11 19:56:13,875] A new study created in memory with name: no-name-e43b69d2-d9a9-4acb-836d-2c7b931171a8

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.01 | R2: 0.66
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.96 | R2: 0.68

✅ KNN - Mejor R2: 0.71
📋 Parámetros: {'n_neighbors': 5, 'weights': 'distance', 'leaf_size': 20}

Buscando mejores hiperparámetros para LR...
Fold 1
Fold 2
Fold 3

[I 2025-07-11 19:56:13,941] Trial 0 finished with value: 0.49636570904734356 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: 0.49636570904734356.
[I 2025-07-11 19:56:14,002] Trial 1 finished with value: 0.49636570904734356 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: 0.49636570904734356.
[I 2025-07-11 19:56:14,078] Trial 2 finished with value: 0.35758519205251815 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 0 with value: 0.49636570904734356.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.46 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.46 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.78 | R2: 0.36
Fold 1
Fold 2
Fold 3

[I 2025-07-11 19:56:14,158] Trial 3 finished with value: 0.35758519205251815 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 0 with value: 0.49636570904734356.
[I 2025-07-11 19:56:14,242] Trial 4 finished with value: 0.3575851920430171 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 0 with value: 0.49636570904734356.
[I 2025-07-11 19:56:14,322] Trial 5 finished with value: 0.3575851920430171 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 0 with value: 0.49636570904734356.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.78 | R2: 0.36
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.78 | R2: 0.36
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.78 | R2: 0.36
Fold 1

[I 2025-07-11 19:56:14,400] Trial 6 finished with value: 0.49636570904734356 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: 0.49636570904734356.
[I 2025-07-11 19:56:14,461] Trial 7 finished with value: 0.4965231448190166 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 7 with value: 0.4965231448190166.
[I 2025-07-11 19:56:14,519] Trial 8 finished with value: 0.49636570904734356 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 7 with value: 0.4965231448190166.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.46 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.46 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.46 | R2: 0.50
Fold 1
Fold 2

[I 2025-07-11 19:56:14,576] Trial 9 finished with value: 0.4965231448190166 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 7 with value: 0.4965231448190166.
[I 2025-07-11 19:56:14,638] Trial 10 finished with value: 0.4965231448190166 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 7 with value: 0.4965231448190166.
[I 2025-07-11 19:56:14,705] Trial 11 finished with value: 0.4965231448190166 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 7 with value: 0.4965231448190166.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.46 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.46 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.46 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 19:56:14,763] Trial 12 finished with value: 0.4965231448190166 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 7 with value: 0.4965231448190166.
[I 2025-07-11 19:56:14,822] Trial 13 finished with value: 0.4965231448190166 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 7 with value: 0.4965231448190166.
[I 2025-07-11 19:56:14,884] Trial 14 finished with value: 0.4965231448190166 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 7 with value: 0.4965231448190166.
[I 2025-07-11 19:56:14,941] Trial 15 finished with value: 0.4965231448190166 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 7 with value: 0.4965231448190166.

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.46 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.46 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.46 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.46 | R2: 0.50
Fold 1

[I 2025-07-11 19:56:14,998] Trial 16 finished with value: 0.4965231448190166 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 7 with value: 0.4965231448190166.
[I 2025-07-11 19:56:15,059] Trial 17 finished with value: 0.4965231448190166 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 7 with value: 0.4965231448190166.
[I 2025-07-11 19:56:15,144] Trial 18 finished with value: 0.35758519205251815 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 7 with value: 0.4965231448190166.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.46 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.46 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.78 | R2: 0.36
Fold 1

[I 2025-07-11 19:56:15,219] Trial 19 finished with value: 0.4965231448190166 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 7 with value: 0.4965231448190166.
[I 2025-07-11 19:56:15,280] Trial 20 finished with value: 0.4965231448190166 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 7 with value: 0.4965231448190166.
[I 2025-07-11 19:56:15,341] Trial 21 finished with value: 0.4965231448190166 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 7 with value: 0.4965231448190166.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.46 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.46 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.46 | R2: 0.50
Fold 1
Fold 2
Fold 3

[I 2025-07-11 19:56:15,398] Trial 22 finished with value: 0.4965231448190166 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 7 with value: 0.4965231448190166.
[I 2025-07-11 19:56:15,459] Trial 23 finished with value: 0.4965231448190166 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 7 with value: 0.4965231448190166.
[I 2025-07-11 19:56:15,519] Trial 24 finished with value: 0.4965231448190166 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 7 with value: 0.4965231448190166.
[I 2025-07-11 19:56:15,520] A new study created in memory with name: no-name-8ea96867-3c22-466e-9f75-3678422db18d

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.46 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.46 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.46 | R2: 0.50

✅ LR - Mejor R2: 0.50
📋 Parámetros: {'fit_intercept': False, 'positive': True}

Buscando mejores hiperparámetros para RF...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:56:17,780] Trial 0 finished with value: 0.38971434296165486 and parameters: {'n_estimators': 100, 'max_depth': 7, 'min_samples_split': 2, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 0 with value: 0.38971434296165486.

Running time: 2.3 sec
OOF RMSE: 2.71 | R2: 0.39
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:56:24,763] Trial 1 finished with value: 0.5029461900843168 and parameters: {'n_estimators': 300, 'max_depth': 15, 'min_samples_split': 10, 'min_samples_leaf': 5, 'bootstrap': False}. Best is trial 1 with value: 0.5029461900843168.

Running time: 7.0 sec
OOF RMSE: 2.44 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:56:26,404] Trial 2 finished with value: 0.6176688568112685 and parameters: {'n_estimators': 100, 'max_depth': 13, 'min_samples_split': 6, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 2 with value: 0.6176688568112685.

Running time: 1.6 sec
OOF RMSE: 2.14 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:56:28,848] Trial 3 finished with value: 0.5637134503327312 and parameters: {'n_estimators': 100, 'max_depth': 14, 'min_samples_split': 6, 'min_samples_leaf': 4, 'bootstrap': False}. Best is trial 2 with value: 0.6176688568112685.

Running time: 2.4 sec
OOF RMSE: 2.29 | R2: 0.56
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:56:33,221] Trial 4 finished with value: 0.6021521296825122 and parameters: {'n_estimators': 300, 'max_depth': 9, 'min_samples_split': 5, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 2 with value: 0.6176688568112685.

Running time: 4.4 sec
OOF RMSE: 2.19 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:56:34,625] Trial 5 finished with value: 0.5909769279657128 and parameters: {'n_estimators': 100, 'max_depth': 9, 'min_samples_split': 7, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 2 with value: 0.6176688568112685.

Running time: 1.4 sec
OOF RMSE: 2.22 | R2: 0.59
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:56:36,900] Trial 6 finished with value: 0.4693340468859669 and parameters: {'n_estimators': 100, 'max_depth': 8, 'min_samples_split': 6, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 2 with value: 0.6176688568112685.

Running time: 2.3 sec
OOF RMSE: 2.53 | R2: 0.47
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:56:38,414] Trial 7 finished with value: 0.6140942748837459 and parameters: {'n_estimators': 100, 'max_depth': 15, 'min_samples_split': 7, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 2 with value: 0.6176688568112685.

Running time: 1.5 sec
OOF RMSE: 2.15 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:56:50,241] Trial 8 finished with value: 0.565343757404544 and parameters: {'n_estimators': 500, 'max_depth': 10, 'min_samples_split': 2, 'min_samples_leaf': 4, 'bootstrap': False}. Best is trial 2 with value: 0.6176688568112685.

Running time: 11.8 sec
OOF RMSE: 2.29 | R2: 0.57
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:56:56,182] Trial 9 finished with value: 0.5978471322805679 and parameters: {'n_estimators': 500, 'max_depth': 5, 'min_samples_split': 10, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 2 with value: 0.6176688568112685.

Running time: 5.9 sec
OOF RMSE: 2.20 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:57:01,136] Trial 10 finished with value: 0.59998215713345 and parameters: {'n_estimators': 300, 'max_depth': 12, 'min_samples_split': 8, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 2 with value: 0.6176688568112685.

Running time: 4.9 sec
OOF RMSE: 2.19 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:57:02,799] Trial 11 finished with value: 0.6176688568112685 and parameters: {'n_estimators': 100, 'max_depth': 13, 'min_samples_split': 4, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 2 with value: 0.6176688568112685.

Running time: 1.7 sec
OOF RMSE: 2.14 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:57:04,588] Trial 12 finished with value: 0.6127984965662123 and parameters: {'n_estimators': 100, 'max_depth': 12, 'min_samples_split': 4, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 2 with value: 0.6176688568112685.

Running time: 1.8 sec
OOF RMSE: 2.16 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:57:06,234] Trial 13 finished with value: 0.6205322609090174 and parameters: {'n_estimators': 100, 'max_depth': 12, 'min_samples_split': 4, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 13 with value: 0.6205322609090174.

Running time: 1.6 sec
OOF RMSE: 2.14 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:57:15,077] Trial 14 finished with value: 0.6025661644845834 and parameters: {'n_estimators': 500, 'max_depth': 12, 'min_samples_split': 4, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 13 with value: 0.6205322609090174.

Running time: 8.8 sec
OOF RMSE: 2.19 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:57:16,703] Trial 15 finished with value: 0.6214040080764796 and parameters: {'n_estimators': 100, 'max_depth': 11, 'min_samples_split': 3, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 15 with value: 0.6214040080764796.

Running time: 1.6 sec
OOF RMSE: 2.13 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:57:18,663] Trial 16 finished with value: 0.627619994993919 and parameters: {'n_estimators': 100, 'max_depth': 11, 'min_samples_split': 3, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 16 with value: 0.627619994993919.

Running time: 2.0 sec
OOF RMSE: 2.12 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:57:20,540] Trial 17 finished with value: 0.6323932881793664 and parameters: {'n_estimators': 100, 'max_depth': 10, 'min_samples_split': 3, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 17 with value: 0.6323932881793664.

Running time: 1.9 sec
OOF RMSE: 2.10 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:57:24,783] Trial 18 finished with value: 0.6140069769813175 and parameters: {'n_estimators': 300, 'max_depth': 6, 'min_samples_split': 3, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 17 with value: 0.6323932881793664.

Running time: 4.2 sec
OOF RMSE: 2.15 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:57:34,316] Trial 19 finished with value: 0.6125759753755955 and parameters: {'n_estimators': 500, 'max_depth': 10, 'min_samples_split': 2, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 17 with value: 0.6323932881793664.

Running time: 9.5 sec
OOF RMSE: 2.16 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:57:36,010] Trial 20 finished with value: 0.6300950018267779 and parameters: {'n_estimators': 100, 'max_depth': 8, 'min_samples_split': 3, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 17 with value: 0.6323932881793664.

Running time: 1.7 sec
OOF RMSE: 2.11 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:57:37,719] Trial 21 finished with value: 0.6300950018267779 and parameters: {'n_estimators': 100, 'max_depth': 8, 'min_samples_split': 3, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 17 with value: 0.6323932881793664.

Running time: 1.7 sec
OOF RMSE: 2.11 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:57:39,335] Trial 22 finished with value: 0.6099578332546766 and parameters: {'n_estimators': 100, 'max_depth': 8, 'min_samples_split': 5, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 17 with value: 0.6323932881793664.

Running time: 1.6 sec
OOF RMSE: 2.16 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:57:40,904] Trial 23 finished with value: 0.631196766524827 and parameters: {'n_estimators': 100, 'max_depth': 7, 'min_samples_split': 3, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 17 with value: 0.6323932881793664.

Running time: 1.6 sec
OOF RMSE: 2.11 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:57:42,317] Trial 24 finished with value: 0.6102069003360093 and parameters: {'n_estimators': 100, 'max_depth': 6, 'min_samples_split': 5, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 17 with value: 0.6323932881793664.
[I 2025-07-11 19:57:42,318] A new study created in memory with name: no-name-c1e117ee-8a3b-4b12-8ab0-a111b332dbb5

Running time: 1.4 sec
OOF RMSE: 2.16 | R2: 0.61

✅ RF - Mejor R2: 0.63
📋 Parámetros: {'n_estimators': 100, 'max_depth': 10, 'min_samples_split': 3, 'min_samples_leaf': 1, 'bootstrap': True}

Buscando mejores hiperparámetros para CAT...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:57:48,936] Trial 0 finished with value: 0.6704221002670977 and parameters: {'iterations': 500, 'learning_rate': 0.02863437940531227, 'depth': 7, 'l2_leaf_reg': 2.0652026045061396}. Best is trial 0 with value: 0.6704221002670977.

Running time: 6.6 sec
OOF RMSE: 1.99 | R2: 0.67
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:58:01,859] Trial 1 finished with value: 0.662451910179238 and parameters: {'iterations': 1000, 'learning_rate': 0.05855362432858604, 'depth': 7, 'l2_leaf_reg': 2.754777801429079}. Best is trial 0 with value: 0.6704221002670977.

Running time: 12.9 sec
OOF RMSE: 2.01 | R2: 0.66
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 19:59:11,522] Trial 2 finished with value: 0.6675908457302624 and parameters: {'iterations': 500, 'learning_rate': 0.09024444679336112, 'depth': 10, 'l2_leaf_reg': 9.594392634389145}. Best is trial 0 with value: 0.6704221002670977.

Running time: 69.7 sec
OOF RMSE: 2.00 | R2: 0.67
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:00:21,235] Trial 3 finished with value: 0.6537878416099407 and parameters: {'iterations': 500, 'learning_rate': 0.09961869658312383, 'depth': 10, 'l2_leaf_reg': 2.86846470758411}. Best is trial 0 with value: 0.6704221002670977.

Running time: 69.7 sec
OOF RMSE: 2.04 | R2: 0.65
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:00:27,689] Trial 4 finished with value: 0.6459347728888647 and parameters: {'iterations': 1000, 'learning_rate': 0.06323759286590123, 'depth': 6, 'l2_leaf_reg': 8.881770460676051}. Best is trial 0 with value: 0.6704221002670977.

Running time: 6.4 sec
OOF RMSE: 2.06 | R2: 0.65
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:00:29,686] Trial 5 finished with value: 0.6475037320670021 and parameters: {'iterations': 500, 'learning_rate': 0.044285944995967344, 'depth': 5, 'l2_leaf_reg': 6.1518651502366115}. Best is trial 0 with value: 0.6704221002670977.

Running time: 2.0 sec
OOF RMSE: 2.06 | R2: 0.65
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:00:32,799] Trial 6 finished with value: 0.6551729867520517 and parameters: {'iterations': 500, 'learning_rate': 0.015013840627981376, 'depth': 6, 'l2_leaf_reg': 9.214048718184793}. Best is trial 0 with value: 0.6704221002670977.

Running time: 3.1 sec
OOF RMSE: 2.04 | R2: 0.66
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:02:49,854] Trial 7 finished with value: 0.67952344782925 and parameters: {'iterations': 1000, 'learning_rate': 0.022292200805198528, 'depth': 10, 'l2_leaf_reg': 2.112810297847323}. Best is trial 7 with value: 0.67952344782925.

Running time: 137.0 sec
OOF RMSE: 1.96 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:02:53,054] Trial 8 finished with value: 0.6429328857832033 and parameters: {'iterations': 500, 'learning_rate': 0.02856067807656738, 'depth': 6, 'l2_leaf_reg': 8.16341902806429}. Best is trial 7 with value: 0.67952344782925.

Running time: 3.2 sec
OOF RMSE: 2.07 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:03:58,247] Trial 9 finished with value: 0.6636376194927903 and parameters: {'iterations': 500, 'learning_rate': 0.017245190279275745, 'depth': 10, 'l2_leaf_reg': 3.9482338224135956}. Best is trial 7 with value: 0.67952344782925.

Running time: 65.2 sec
OOF RMSE: 2.01 | R2: 0.66
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:06:34,901] Trial 10 finished with value: 0.6589005249710833 and parameters: {'iterations': 2000, 'learning_rate': 0.01064941963297247, 'depth': 9, 'l2_leaf_reg': 5.588709876088201}. Best is trial 7 with value: 0.67952344782925.

Running time: 156.6 sec
OOF RMSE: 2.02 | R2: 0.66
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:07:09,953] Trial 11 finished with value: 0.6680967733082869 and parameters: {'iterations': 1000, 'learning_rate': 0.026880667882721115, 'depth': 8, 'l2_leaf_reg': 1.1420185067164828}. Best is trial 7 with value: 0.67952344782925.

Running time: 35.0 sec
OOF RMSE: 2.00 | R2: 0.67
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:08:19,235] Trial 12 finished with value: 0.6682048355606911 and parameters: {'iterations': 2000, 'learning_rate': 0.021232574764909952, 'depth': 8, 'l2_leaf_reg': 1.1422914759080474}. Best is trial 7 with value: 0.67952344782925.
[I 2025-07-11 20:08:19,236] A new study created in memory with name: no-name-c9655d53-f8f7-42f4-86bf-13ef81b2c2eb
[I 2025-07-11 20:08:19,321] Trial 0 finished with value: 0.5344212125729941 and parameters: {'alpha': 0.03605577284746663, 'l1_ratio': 0.8981232191121516}. Best is trial 0 with value: 0.5344212125729941.

Running time: 69.3 sec
OOF RMSE: 2.00 | R2: 0.67

✅ CAT - Mejor R2: 0.68
📋 Parámetros: {'iterations': 1000, 'learning_rate': 0.022292200805198528, 'depth': 10, 'l2_leaf_reg': 2.112810297847323}

Buscando mejores hiperparámetros para EN...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.37 | R2: 0.53
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.101e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.471e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.572e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.871e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.794e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 20:08:19,451] Trial 1 finished with value: 0.4895233690238069 and parameters: {'alpha': 0.0008806439712250589, 'l1_ratio': 0.6685433937024298}. Best is trial 0 with value: 0.5344212125729941.
[I 2025-07-11 20:08:19,532] Trial 2 finished with value: 0.2383978776984692 and parameters: {'alpha': 2.0671587893404593, 'l1_ratio': 0.5381486219100039}. Best is trial 0 with value: 0.5344212125729941.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.296e+01, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.039e+01, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.144e+01, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.973e+01, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.714e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(

Running time: 0.1 sec
OOF RMSE: 2.48 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.03 | R2: 0.24
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:08:19,652] Trial 3 finished with value: 0.5070508593717273 and parameters: {'alpha': 0.0031058604997865934, 'l1_ratio': 0.804694343758744}. Best is trial 0 with value: 0.5344212125729941.
[I 2025-07-11 20:08:19,731] Trial 4 finished with value: 0.05599064403499987 and parameters: {'alpha': 4.260534284885533, 'l1_ratio': 0.4132666041933496}. Best is trial 0 with value: 0.5344212125729941.
[I 2025-07-11 20:08:19,817] Trial 5 finished with value: 0.5054532274242666 and parameters: {'alpha': 0.10018620012432002, 'l1_ratio': 0.4759056930205411}. Best is trial 0 with value: 0.5344212125729941.

Running time: 0.1 sec
OOF RMSE: 2.43 | R2: 0.51
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.37 | R2: 0.06
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.44 | R2: 0.51
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.329e+01, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.879e+00, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.018e+01, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.334e+01, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.465e+01, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 20:08:19,950] Trial 6 finished with value: 0.52728343105967 and parameters: {'alpha': 0.020288006225702218, 'l1_ratio': 0.40460410724763407}. Best is trial 0 with value: 0.5344212125729941.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.635e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.169e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.912e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.287e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.38 | R2: 0.53
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.602e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 20:08:20,108] Trial 7 finished with value: 0.4815401815132264 and parameters: {'alpha': 0.0002403973415292109, 'l1_ratio': 0.6496499737406797}. Best is trial 0 with value: 0.5344212125729941.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.467e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.739e+01, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.289e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.039e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(

Running time: 0.2 sec
OOF RMSE: 2.50 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.229e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 20:08:20,317] Trial 8 finished with value: 0.5022155354181892 and parameters: {'alpha': 0.0021818829881085347, 'l1_ratio': 0.6962023274998341}. Best is trial 0 with value: 0.5344212125729941.
[I 2025-07-11 20:08:20,430] Trial 9 finished with value: 0.3862535058768982 and parameters: {'alpha': 1.4734053231392032, 'l1_ratio': 0.19825300256795553}. Best is trial 0 with value: 0.5344212125729941.

Running time: 0.2 sec
OOF RMSE: 2.45 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.72 | R2: 0.39
Fold 1
Fold 2
Fold 3

[I 2025-07-11 20:08:20,591] Trial 10 finished with value: 0.5324998260941938 and parameters: {'alpha': 0.0635214204750304, 'l1_ratio': 0.9756972498203298}. Best is trial 0 with value: 0.5344212125729941.
[I 2025-07-11 20:08:20,724] Trial 11 finished with value: 0.5081882111677289 and parameters: {'alpha': 0.10133062910759756, 'l1_ratio': 0.9663178717772908}. Best is trial 0 with value: 0.5344212125729941.

Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 2.37 | R2: 0.53
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.43 | R2: 0.51
Fold 1

[I 2025-07-11 20:08:20,880] Trial 12 finished with value: 0.5370022245903933 and parameters: {'alpha': 0.0218937340718044, 'l1_ratio': 0.9982770044716297}. Best is trial 12 with value: 0.5370022245903933.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.36 | R2: 0.54
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.190e-01, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.314e+00, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 20:08:21,037] Trial 13 finished with value: 0.5346371491262691 and parameters: {'alpha': 0.01495695870068688, 'l1_ratio': 0.8477571340011038}. Best is trial 12 with value: 0.5370022245903933.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.445e+01, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.182e+01, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.694e+01, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.811e+01, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.966e+01, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 20:08:21,157] Trial 14 finished with value: 0.5264233565785663 and parameters: {'alpha': 0.007433249831209145, 'l1_ratio': 0.8279754649475164}. Best is trial 12 with value: 0.5370022245903933.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.36 | R2: 0.53
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.39 | R2: 0.53
Fold 1
Fold 2

[I 2025-07-11 20:08:21,261] Trial 15 finished with value: 0.4496604541173379 and parameters: {'alpha': 0.4040022887671003, 'l1_ratio': 0.05625650692927253}. Best is trial 12 with value: 0.5370022245903933.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.113e+01, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.692e-01, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.629e-01, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.329e+01, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 20:08:21,392] Trial 16 finished with value: 0.5331434020377663 and parameters: {'alpha': 0.012983933201518338, 'l1_ratio': 0.8264065704700339}. Best is trial 12 with value: 0.5370022245903933.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.57 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.37 | R2: 0.53
Fold 1

[I 2025-07-11 20:08:21,487] Trial 17 finished with value: 0.44078230952182973 and parameters: {'alpha': 0.35341388158678616, 'l1_ratio': 0.7524589336050189}. Best is trial 12 with value: 0.5370022245903933.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.462e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.935e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.59 | R2: 0.44
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.732e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.141e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.359e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 20:08:21,627] Trial 18 finished with value: 0.48023316645703584 and parameters: {'alpha': 0.00026823577236683815, 'l1_ratio': 0.9809485817769117}. Best is trial 12 with value: 0.5370022245903933.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.704e+01, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.213e+01, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.381e+01, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.328e+01, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.392e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 20:08:21,762] Trial 19 finished with value: 0.5188587089149441 and parameters: {'alpha': 0.004806655572701103, 'l1_ratio': 0.5969083346529938}. Best is trial 12 with value: 0.5370022245903933.

Running time: 0.1 sec
OOF RMSE: 2.50 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.40 | R2: 0.52
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.165e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.059e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.913e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.194e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.523e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 20:08:21,938] Trial 20 finished with value: 0.49270195378841364 and parameters: {'alpha': 0.0007356030808078373, 'l1_ratio': 0.27017816848512394}. Best is trial 12 with value: 0.5370022245903933.

Fold 3
Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 2.47 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 20:08:22,086] Trial 21 finished with value: 0.5337609916715031 and parameters: {'alpha': 0.03305013372012786, 'l1_ratio': 0.885846981578367}. Best is trial 12 with value: 0.5370022245903933.
[I 2025-07-11 20:08:22,208] Trial 22 finished with value: 0.4490917864881293 and parameters: {'alpha': 0.3077743536623572, 'l1_ratio': 0.8557213751947971}. Best is trial 12 with value: 0.5370022245903933.

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.37 | R2: 0.53
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.57 | R2: 0.45
Fold 1
Fold 2
Fold 3

[I 2025-07-11 20:08:22,304] Trial 23 finished with value: 0.5341027068963085 and parameters: {'alpha': 0.033426742778849376, 'l1_ratio': 0.9078405161653026}. Best is trial 12 with value: 0.5370022245903933.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.400e+01, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.447e+00, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.180e+01, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.806e+00, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.294e+01, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 20:08:22,427] Trial 24 finished with value: 0.5299664274351026 and parameters: {'alpha': 0.010837502112362044, 'l1_ratio': 0.753141947666659}. Best is trial 12 with value: 0.5370022245903933.
[I 2025-07-11 20:08:22,428] A new study created in memory with name: no-name-f1b4efdc-343d-4c26-b771-7429aca23eb9

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.37 | R2: 0.53
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.38 | R2: 0.53

✅ EN - Mejor R2: 0.54
📋 Parámetros: {'alpha': 0.0218937340718044, 'l1_ratio': 0.9982770044716297}

🔍 Optimizando en C2X_rhow_5x5_depth_lt_1...
Buscando mejores hiperparámetros para XGB...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:08:27,550] Trial 0 finished with value: 0.4247159068806019 and parameters: {'n_estimators': 500, 'learning_rate': 0.01945209776518604, 'max_depth': 8, 'min_child_weight': 1, 'subsample': 0.7575744168915226, 'colsample_bytree': 0.9117235164116804}. Best is trial 0 with value: 0.4247159068806019.

Running time: 5.1 sec
OOF RMSE: 2.63 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:08:31,430] Trial 1 finished with value: 0.5107367209322211 and parameters: {'n_estimators': 1000, 'learning_rate': 0.021135081590622697, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.6606345129723122, 'colsample_bytree': 0.7217053297915935}. Best is trial 1 with value: 0.5107367209322211.

Running time: 3.9 sec
OOF RMSE: 2.42 | R2: 0.51
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:08:38,143] Trial 2 finished with value: 0.48400702554754826 and parameters: {'n_estimators': 1000, 'learning_rate': 0.005068922459562744, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.7410975080241837, 'colsample_bytree': 0.806007656710712}. Best is trial 1 with value: 0.5107367209322211.

Running time: 6.7 sec
OOF RMSE: 2.49 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:08:46,311] Trial 3 finished with value: 0.3997810972823659 and parameters: {'n_estimators': 1000, 'learning_rate': 0.028145359413673677, 'max_depth': 6, 'min_child_weight': 1, 'subsample': 0.8843621248934797, 'colsample_bytree': 0.9679467895251274}. Best is trial 1 with value: 0.5107367209322211.

Running time: 8.2 sec
OOF RMSE: 2.69 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:08:51,265] Trial 4 finished with value: 0.46523209566937096 and parameters: {'n_estimators': 1000, 'learning_rate': 0.010287416988156597, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.8536319309264571, 'colsample_bytree': 0.908789528197148}. Best is trial 1 with value: 0.5107367209322211.

Running time: 4.9 sec
OOF RMSE: 2.54 | R2: 0.47
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:08:57,740] Trial 5 finished with value: 0.3901451706872411 and parameters: {'n_estimators': 1000, 'learning_rate': 0.006217067685017807, 'max_depth': 6, 'min_child_weight': 1, 'subsample': 0.9008775226180245, 'colsample_bytree': 0.62315627194777}. Best is trial 1 with value: 0.5107367209322211.

Running time: 6.5 sec
OOF RMSE: 2.71 | R2: 0.39
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:09:08,501] Trial 6 finished with value: 0.4221040037770105 and parameters: {'n_estimators': 2000, 'learning_rate': 0.008340383362906878, 'max_depth': 5, 'min_child_weight': 1, 'subsample': 0.7972327410220228, 'colsample_bytree': 0.6894773532091588}. Best is trial 1 with value: 0.5107367209322211.

Running time: 10.8 sec
OOF RMSE: 2.64 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:09:11,689] Trial 7 finished with value: 0.41499887491877974 and parameters: {'n_estimators': 500, 'learning_rate': 0.08532723622334282, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.7733015329140291, 'colsample_bytree': 0.8169085807050417}. Best is trial 1 with value: 0.5107367209322211.

Running time: 3.2 sec
OOF RMSE: 2.65 | R2: 0.41
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:09:14,526] Trial 8 finished with value: 0.46533832209240766 and parameters: {'n_estimators': 500, 'learning_rate': 0.009579956490734906, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.8974919393894969, 'colsample_bytree': 0.7834370035835339}. Best is trial 1 with value: 0.5107367209322211.

Running time: 2.8 sec
OOF RMSE: 2.53 | R2: 0.47
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:09:21,513] Trial 9 finished with value: 0.4480855613853221 and parameters: {'n_estimators': 1000, 'learning_rate': 0.041776094510955784, 'max_depth': 6, 'min_child_weight': 1, 'subsample': 0.6727948692773977, 'colsample_bytree': 0.8277094667794457}. Best is trial 1 with value: 0.5107367209322211.

Running time: 7.0 sec
OOF RMSE: 2.58 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:09:30,339] Trial 10 finished with value: 0.48633351688788473 and parameters: {'n_estimators': 2000, 'learning_rate': 0.017547337810969975, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.6036907086536042, 'colsample_bytree': 0.7010345984373663}. Best is trial 1 with value: 0.5107367209322211.

Running time: 8.8 sec
OOF RMSE: 2.48 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:09:39,211] Trial 11 finished with value: 0.48144911068564156 and parameters: {'n_estimators': 2000, 'learning_rate': 0.017885345952089095, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.6013309586175803, 'colsample_bytree': 0.7083326329009707}. Best is trial 1 with value: 0.5107367209322211.

Running time: 8.9 sec
OOF RMSE: 2.50 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:09:47,746] Trial 12 finished with value: 0.40036582840180335 and parameters: {'n_estimators': 2000, 'learning_rate': 0.03460370884015768, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.9909351176701239, 'colsample_bytree': 0.7007316085324407}. Best is trial 1 with value: 0.5107367209322211.

Running time: 8.5 sec
OOF RMSE: 2.68 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:09:56,077] Trial 13 finished with value: 0.5121481919894806 and parameters: {'n_estimators': 2000, 'learning_rate': 0.016814615709677665, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.6003929153067326, 'colsample_bytree': 0.6003272719473953}. Best is trial 13 with value: 0.5121481919894806.

Running time: 8.3 sec
OOF RMSE: 2.42 | R2: 0.51
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:10:05,431] Trial 14 finished with value: 0.4687274346731217 and parameters: {'n_estimators': 2000, 'learning_rate': 0.06857074191067432, 'max_depth': 8, 'min_child_weight': 3, 'subsample': 0.6867321357083815, 'colsample_bytree': 0.6183932445251827}. Best is trial 13 with value: 0.5121481919894806.

Running time: 9.3 sec
OOF RMSE: 2.53 | R2: 0.47
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:10:10,177] Trial 15 finished with value: 0.48822379990804854 and parameters: {'n_estimators': 1000, 'learning_rate': 0.013611197598495349, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.662882264793658, 'colsample_bytree': 0.7544639626360115}. Best is trial 13 with value: 0.5121481919894806.

Running time: 4.7 sec
OOF RMSE: 2.48 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:10:20,200] Trial 16 finished with value: 0.47265135018092896 and parameters: {'n_estimators': 2000, 'learning_rate': 0.046471389854601385, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.6439646985921783, 'colsample_bytree': 0.600552340458517}. Best is trial 13 with value: 0.5121481919894806.

Running time: 10.0 sec
OOF RMSE: 2.52 | R2: 0.47
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:10:25,120] Trial 17 finished with value: 0.5001410153539674 and parameters: {'n_estimators': 1000, 'learning_rate': 0.023570708400562072, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.715419985341502, 'colsample_bytree': 0.663185550648107}. Best is trial 13 with value: 0.5121481919894806.

Running time: 4.9 sec
OOF RMSE: 2.45 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:10:34,728] Trial 18 finished with value: 0.48889063536801336 and parameters: {'n_estimators': 2000, 'learning_rate': 0.013332918978273468, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.6367918278080791, 'colsample_bytree': 0.7485275510368794}. Best is trial 13 with value: 0.5121481919894806.

Running time: 9.6 sec
OOF RMSE: 2.48 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:10:36,991] Trial 19 finished with value: 0.5256938481766997 and parameters: {'n_estimators': 500, 'learning_rate': 0.028615504628162317, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.7090299060564239, 'colsample_bytree': 0.6493736316287261}. Best is trial 19 with value: 0.5256938481766997.

Running time: 2.3 sec
OOF RMSE: 2.39 | R2: 0.53
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:10:39,425] Trial 20 finished with value: 0.5089805832295797 and parameters: {'n_estimators': 500, 'learning_rate': 0.030855879475458172, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.7128439546118317, 'colsample_bytree': 0.6473620708635024}. Best is trial 19 with value: 0.5256938481766997.

Running time: 2.4 sec
OOF RMSE: 2.43 | R2: 0.51
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:10:41,455] Trial 21 finished with value: 0.5072048069251047 and parameters: {'n_estimators': 500, 'learning_rate': 0.02467247175222432, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.6305597313583534, 'colsample_bytree': 0.658452063690256}. Best is trial 19 with value: 0.5256938481766997.

Running time: 2.0 sec
OOF RMSE: 2.43 | R2: 0.51
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:10:43,964] Trial 22 finished with value: 0.4785154528652633 and parameters: {'n_estimators': 500, 'learning_rate': 0.05200819569892158, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.6981178537528371, 'colsample_bytree': 0.7382572673016667}. Best is trial 19 with value: 0.5256938481766997.

Running time: 2.5 sec
OOF RMSE: 2.50 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:10:46,056] Trial 23 finished with value: 0.4956676556210251 and parameters: {'n_estimators': 500, 'learning_rate': 0.015259666198630832, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.7334078075375838, 'colsample_bytree': 0.6370517772026841}. Best is trial 19 with value: 0.5256938481766997.

Running time: 2.1 sec
OOF RMSE: 2.46 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:10:56,906] Trial 24 finished with value: 0.5078852641240377 and parameters: {'n_estimators': 2000, 'learning_rate': 0.037209159610206696, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.6611179546284806, 'colsample_bytree': 0.667787600474614}. Best is trial 19 with value: 0.5256938481766997.
[I 2025-07-11 20:10:56,908] A new study created in memory with name: no-name-021ae7e5-a2cd-422e-bd96-af7e566220e0

Running time: 10.8 sec
OOF RMSE: 2.43 | R2: 0.51

✅ XGB - Mejor R2: 0.53
📋 Parámetros: {'n_estimators': 500, 'learning_rate': 0.028615504628162317, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.7090299060564239, 'colsample_bytree': 0.6493736316287261}

Buscando mejores hiperparámetros para LBM...
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 20:10:57,816] Trial 0 finished with value: 0.36065871199938726 and parameters: {'learning_rate': 0.056213877084546754, 'num_leaves': 80, 'max_depth': 6, 'min_child_samples': 23, 'subsample': 0.9599687810955627, 'colsample_bytree': 0.788541278237112, 'n_estimators': 2000}. Best is trial 0 with value: 0.36065871199938726.

Fold 5
Running time: 0.9 sec
OOF RMSE: 2.77 | R2: 0.36
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:10:58,424] Trial 1 finished with value: 0.3722866020435843 and parameters: {'learning_rate': 0.019795207435252496, 'num_leaves': 80, 'max_depth': 7, 'min_child_samples': 12, 'subsample': 0.9913110659699064, 'colsample_bytree': 0.8459192028523281, 'n_estimators': 1000}. Best is trial 1 with value: 0.3722866020435843.

Running time: 0.6 sec
OOF RMSE: 2.75 | R2: 0.37
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 20:10:59,376] Trial 2 finished with value: 0.40219862492284597 and parameters: {'learning_rate': 0.035555102157434654, 'num_leaves': 60, 'max_depth': 7, 'min_child_samples': 22, 'subsample': 0.9816470270684283, 'colsample_bytree': 0.7083161902738424, 'n_estimators': 2000}. Best is trial 2 with value: 0.40219862492284597.

Fold 5
Running time: 0.9 sec
OOF RMSE: 2.68 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:11:00,199] Trial 3 finished with value: 0.4705048573988332 and parameters: {'learning_rate': 0.008599250618812004, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 22, 'subsample': 0.9248834043574791, 'colsample_bytree': 0.6045428202736426, 'n_estimators': 2000}. Best is trial 3 with value: 0.4705048573988332.

Running time: 0.8 sec
OOF RMSE: 2.52 | R2: 0.47
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 20:11:01,180] Trial 4 finished with value: 0.34966759515619217 and parameters: {'learning_rate': 0.027383523199748842, 'num_leaves': 40, 'max_depth': 7, 'min_child_samples': 16, 'subsample': 0.8975827740248188, 'colsample_bytree': 0.6409356398035138, 'n_estimators': 2000}. Best is trial 3 with value: 0.4705048573988332.

Fold 5
Running time: 1.0 sec
OOF RMSE: 2.80 | R2: 0.35
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 20:11:01,598] Trial 5 finished with value: 0.4541790231682993 and parameters: {'learning_rate': 0.027020703543611746, 'num_leaves': 20, 'max_depth': 8, 'min_child_samples': 25, 'subsample': 0.6098383264737469, 'colsample_bytree': 0.6405468795145299, 'n_estimators': 1000}. Best is trial 3 with value: 0.4705048573988332.

Fold 5
Running time: 0.4 sec
OOF RMSE: 2.56 | R2: 0.45
Fold 1
Fold 2

[I 2025-07-11 20:11:01,901] Trial 6 finished with value: 0.38929884889754995 and parameters: {'learning_rate': 0.05569487297448753, 'num_leaves': 60, 'max_depth': 7, 'min_child_samples': 16, 'subsample': 0.7977541257087839, 'colsample_bytree': 0.6696160505530521, 'n_estimators': 500}. Best is trial 3 with value: 0.4705048573988332.

Fold 3
Fold 4
Fold 5
Running time: 0.3 sec
OOF RMSE: 2.71 | R2: 0.39
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:11:02,179] Trial 7 finished with value: 0.4315664878271165 and parameters: {'learning_rate': 0.07482285766782652, 'num_leaves': 20, 'max_depth': 8, 'min_child_samples': 23, 'subsample': 0.9169986538448494, 'colsample_bytree': 0.6579528180077147, 'n_estimators': 500}. Best is trial 3 with value: 0.4705048573988332.

Running time: 0.3 sec
OOF RMSE: 2.61 | R2: 0.43
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:11:02,670] Trial 8 finished with value: 0.3745584623311434 and parameters: {'learning_rate': 0.08487453695787635, 'num_leaves': 40, 'max_depth': 6, 'min_child_samples': 23, 'subsample': 0.8734414794740335, 'colsample_bytree': 0.7314825503252216, 'n_estimators': 1000}. Best is trial 3 with value: 0.4705048573988332.

Running time: 0.5 sec
OOF RMSE: 2.74 | R2: 0.37
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 20:11:03,657] Trial 9 finished with value: 0.3959274468731896 and parameters: {'learning_rate': 0.007173111849005333, 'num_leaves': 80, 'max_depth': 5, 'min_child_samples': 5, 'subsample': 0.891676462985049, 'colsample_bytree': 0.7509609818602689, 'n_estimators': 2000}. Best is trial 3 with value: 0.4705048573988332.

Fold 5
Running time: 1.0 sec
OOF RMSE: 2.69 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 20:11:04,496] Trial 10 finished with value: 0.4518036230061371 and parameters: {'learning_rate': 0.005375586523581296, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 19, 'subsample': 0.7718413798261688, 'colsample_bytree': 0.9623518754934137, 'n_estimators': 2000}. Best is trial 3 with value: 0.4705048573988332.

Fold 5
Running time: 0.8 sec
OOF RMSE: 2.57 | R2: 0.45
Fold 1
Fold 2
Fold 3

[I 2025-07-11 20:11:04,994] Trial 11 finished with value: 0.46350607344272277 and parameters: {'learning_rate': 0.012896407846666746, 'num_leaves': 20, 'max_depth': 8, 'min_child_samples': 25, 'subsample': 0.6199959117123539, 'colsample_bytree': 0.6002460957570627, 'n_estimators': 1000}. Best is trial 3 with value: 0.4705048573988332.

Fold 4
Fold 5
Running time: 0.5 sec
OOF RMSE: 2.54 | R2: 0.46
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 20:11:05,466] Trial 12 finished with value: 0.45328162692113505 and parameters: {'learning_rate': 0.011426041456439554, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 19, 'subsample': 0.6096473403237471, 'colsample_bytree': 0.6014279534581944, 'n_estimators': 1000}. Best is trial 3 with value: 0.4705048573988332.

Fold 5
Running time: 0.5 sec
OOF RMSE: 2.56 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:11:06,163] Trial 13 finished with value: 0.371114443682109 and parameters: {'learning_rate': 0.013059550287013614, 'num_leaves': 20, 'max_depth': 8, 'min_child_samples': 12, 'subsample': 0.712511142031252, 'colsample_bytree': 0.8662089101146221, 'n_estimators': 1000}. Best is trial 3 with value: 0.4705048573988332.

Running time: 0.7 sec
OOF RMSE: 2.75 | R2: 0.37
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 20:11:06,416] Trial 14 finished with value: 0.45258514859483 and parameters: {'learning_rate': 0.010692918341440554, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 20, 'subsample': 0.7065217811679609, 'colsample_bytree': 0.6002897381523387, 'n_estimators': 500}. Best is trial 3 with value: 0.4705048573988332.

Fold 5
Running time: 0.2 sec
OOF RMSE: 2.56 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:11:07,253] Trial 15 finished with value: 0.4596549871811959 and parameters: {'learning_rate': 0.016850198769767868, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 25, 'subsample': 0.8419844336335116, 'colsample_bytree': 0.9789179932199908, 'n_estimators': 2000}. Best is trial 3 with value: 0.4705048573988332.

Running time: 0.8 sec
OOF RMSE: 2.55 | R2: 0.46
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 20:11:07,966] Trial 16 finished with value: 0.446790938126131 and parameters: {'learning_rate': 0.008350156954726894, 'num_leaves': 20, 'max_depth': 8, 'min_child_samples': 6, 'subsample': 0.6838285143696762, 'colsample_bytree': 0.6964361252178768, 'n_estimators': 1000}. Best is trial 3 with value: 0.4705048573988332.

Fold 5
Running time: 0.7 sec
OOF RMSE: 2.58 | R2: 0.45
Fold 1
Fold 2
Fold 3

[I 2025-07-11 20:11:08,510] Trial 17 finished with value: 0.4508199189660287 and parameters: {'learning_rate': 0.005401514450928312, 'num_leaves': 60, 'max_depth': 7, 'min_child_samples': 20, 'subsample': 0.7480081999154998, 'colsample_bytree': 0.8997593906117706, 'n_estimators': 1000}. Best is trial 3 with value: 0.4705048573988332.

Fold 4
Fold 5
Running time: 0.5 sec
OOF RMSE: 2.57 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 20:11:09,454] Trial 18 finished with value: 0.3497071061700012 and parameters: {'learning_rate': 0.01546466879763664, 'num_leaves': 40, 'max_depth': 6, 'min_child_samples': 12, 'subsample': 0.6627033496638025, 'colsample_bytree': 0.7650681172878613, 'n_estimators': 2000}. Best is trial 3 with value: 0.4705048573988332.

Fold 5
Running time: 0.9 sec
OOF RMSE: 2.80 | R2: 0.35
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 20:11:09,747] Trial 19 finished with value: 0.46548443858087174 and parameters: {'learning_rate': 0.008498214736857464, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 25, 'subsample': 0.8313391588108617, 'colsample_bytree': 0.8299255613695602, 'n_estimators': 500}. Best is trial 3 with value: 0.4705048573988332.

Fold 5
Running time: 0.3 sec
OOF RMSE: 2.53 | R2: 0.47
Fold 1
Fold 2
Fold 3

[I 2025-07-11 20:11:10,034] Trial 20 finished with value: 0.3823368046296166 and parameters: {'learning_rate': 0.008076541673413349, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 8, 'subsample': 0.8434811498434827, 'colsample_bytree': 0.8238528672370241, 'n_estimators': 500}. Best is trial 3 with value: 0.4705048573988332.

Fold 4
Fold 5
Running time: 0.3 sec
OOF RMSE: 2.72 | R2: 0.38
Fold 1
Fold 2

[I 2025-07-11 20:11:10,307] Trial 21 finished with value: 0.46693416316069003 and parameters: {'learning_rate': 0.009454775435261019, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 25, 'subsample': 0.9379698644079247, 'colsample_bytree': 0.9080158974948526, 'n_estimators': 500}. Best is trial 3 with value: 0.4705048573988332.

Fold 3
Fold 4
Fold 5
Running time: 0.3 sec
OOF RMSE: 2.53 | R2: 0.47
Fold 1

[I 2025-07-11 20:11:10,555] Trial 22 finished with value: 0.4580883884569923 and parameters: {'learning_rate': 0.008968772965524665, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 21, 'subsample': 0.9436182452015435, 'colsample_bytree': 0.9162978493124193, 'n_estimators': 500}. Best is trial 3 with value: 0.4705048573988332.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 2.55 | R2: 0.46
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:11:10,813] Trial 23 finished with value: 0.45166667940107685 and parameters: {'learning_rate': 0.006561064813824236, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 18, 'subsample': 0.8494547210507474, 'colsample_bytree': 0.9202166563025509, 'n_estimators': 500}. Best is trial 3 with value: 0.4705048573988332.

Running time: 0.3 sec
OOF RMSE: 2.57 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:11:11,056] Trial 24 finished with value: 0.46445731850808014 and parameters: {'learning_rate': 0.010111881358439455, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 24, 'subsample': 0.9495890718080549, 'colsample_bytree': 0.8655040091770867, 'n_estimators': 500}. Best is trial 3 with value: 0.4705048573988332.
[I 2025-07-11 20:11:11,057] A new study created in memory with name: no-name-9e81850e-6812-4de0-9eff-73dc8e8ccc9b

Running time: 0.2 sec
OOF RMSE: 2.54 | R2: 0.46

✅ LBM - Mejor R2: 0.47
📋 Parámetros: {'learning_rate': 0.008599250618812004, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 22, 'subsample': 0.9248834043574791, 'colsample_bytree': 0.6045428202736426, 'n_estimators': 2000}

Buscando mejores hiperparámetros para MLP...
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 20:11:12,972] Trial 0 finished with value: 0.3360854794031577 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.010999813160714455, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00032226119108915655}. Best is trial 0 with value: 0.3360854794031577.

Running time: 1.9 sec
OOF RMSE: 2.82 | R2: 0.34
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 20:11:14,456] Trial 1 finished with value: 0.2748716051657246 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.017135876902154252, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0005735748370376059}. Best is trial 0 with value: 0.3360854794031577.

Running time: 1.5 sec
OOF RMSE: 2.95 | R2: 0.27
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 20:11:16,017] Trial 2 finished with value: 0.38298874586883036 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 1.0029190420787105e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0009989636473471779}. Best is trial 2 with value: 0.38298874586883036.

Running time: 1.6 sec
OOF RMSE: 2.72 | R2: 0.38
Fold 1
Fold 2
Fold 3

[I 2025-07-11 20:11:16,804] Trial 3 finished with value: 0.32912079482986456 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.008674783667155767, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0010243304348625248}. Best is trial 2 with value: 0.38298874586883036.

Fold 4
Fold 5
Running time: 0.8 sec
OOF RMSE: 2.84 | R2: 0.33
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:11:17,520] Trial 4 finished with value: 0.31718098318538623 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.046121017197198154, 'learning_rate': 'constant', 'learning_rate_init': 0.000529403661555848}. Best is trial 2 with value: 0.38298874586883036.

Running time: 0.7 sec
OOF RMSE: 2.86 | R2: 0.32
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

[I 2025-07-11 20:11:18,998] Trial 5 finished with value: 0.35087267168786007 and parameters: {'hidden_layer_sizes': '50', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.0002271221708828358, 'learning_rate': 'adaptive', 'learning_rate_init': 0.007234799702184722}. Best is trial 2 with value: 0.38298874586883036.

Running time: 1.5 sec
OOF RMSE: 2.79 | R2: 0.35
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 20:11:21,479] Trial 6 finished with value: 0.3262862558328904 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.00026485404316104, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0009455780429175393}. Best is trial 2 with value: 0.38298874586883036.

Running time: 2.5 sec
OOF RMSE: 2.85 | R2: 0.33
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 20:11:24,124] Trial 7 finished with value: 0.3428034127098827 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.00983744732474591, 'learning_rate': 'adaptive', 'learning_rate_init': 0.005455561064723563}. Best is trial 2 with value: 0.38298874586883036.

Running time: 2.6 sec
OOF RMSE: 2.81 | R2: 0.34
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

[I 2025-07-11 20:11:25,857] Trial 8 finished with value: 0.3434407004929988 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.01599739575653653, 'learning_rate': 'adaptive', 'learning_rate_init': 0.004088162197297514}. Best is trial 2 with value: 0.38298874586883036.

Running time: 1.7 sec
OOF RMSE: 2.81 | R2: 0.34
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 20:11:28,404] Trial 9 finished with value: 0.29987278978985465 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 1.0456923816638465e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0001336352316752094}. Best is trial 2 with value: 0.38298874586883036.

Running time: 2.5 sec
OOF RMSE: 2.90 | R2: 0.30
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 20:11:29,385] Trial 10 finished with value: 0.358062306131826 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 2.363881573329255e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.002362360270778322}. Best is trial 2 with value: 0.38298874586883036.

Running time: 1.0 sec
OOF RMSE: 2.78 | R2: 0.36
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 20:11:30,095] Trial 11 finished with value: 0.3569163818651847 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 1.1753366316697742e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.0019856804812465796}. Best is trial 2 with value: 0.38298874586883036.

Running time: 0.7 sec
OOF RMSE: 2.78 | R2: 0.36
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 20:11:30,972] Trial 12 finished with value: 0.35870256975596726 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 5.518213349274655e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.0024354122301051945}. Best is trial 2 with value: 0.38298874586883036.

Running time: 0.9 sec
OOF RMSE: 2.78 | R2: 0.36
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 20:11:31,760] Trial 13 finished with value: 0.35841605270420596 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 6.870343491471192e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.00218938759668561}. Best is trial 2 with value: 0.38298874586883036.

Running time: 0.8 sec
OOF RMSE: 2.78 | R2: 0.36
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 20:11:32,976] Trial 14 finished with value: 0.37873996396301046 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 6.895958520865595e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.0010303648180961622}. Best is trial 2 with value: 0.38298874586883036.

Running time: 1.2 sec
OOF RMSE: 2.73 | R2: 0.38
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 20:11:34,381] Trial 15 finished with value: 0.3818932509006977 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.0013588857148619311, 'learning_rate': 'constant', 'learning_rate_init': 0.0002192877115033175}. Best is trial 2 with value: 0.38298874586883036.

Running time: 1.4 sec
OOF RMSE: 2.73 | R2: 0.38
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 20:11:36,551] Trial 16 finished with value: 0.35922685513231556 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.001771789427375893, 'learning_rate': 'constant', 'learning_rate_init': 0.00010418228462493079}. Best is trial 2 with value: 0.38298874586883036.

Running time: 2.2 sec
OOF RMSE: 2.77 | R2: 0.36
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 20:11:37,226] Trial 17 finished with value: 0.2970522202754319 and parameters: {'hidden_layer_sizes': '50', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.0011951549064045908, 'learning_rate': 'constant', 'learning_rate_init': 0.00021050167914195658}. Best is trial 2 with value: 0.38298874586883036.

Fold 4
Fold 5
Running time: 0.7 sec
OOF RMSE: 2.91 | R2: 0.30
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 20:11:38,474] Trial 18 finished with value: 0.4171571567444524 and parameters: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.0021888036951323623, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00025110377224401637}. Best is trial 18 with value: 0.4171571567444524.

Running time: 1.2 sec
OOF RMSE: 2.65 | R2: 0.42
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 20:11:39,759] Trial 19 finished with value: 0.40000193971656506 and parameters: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.0030960329106311454, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00045876114399107093}. Best is trial 18 with value: 0.4171571567444524.

Fold 5
Running time: 1.3 sec
OOF RMSE: 2.69 | R2: 0.40
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 20:11:41,008] Trial 20 finished with value: 0.4058014222103552 and parameters: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.003468353691208481, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00040004680336335586}. Best is trial 18 with value: 0.4171571567444524.

Running time: 1.2 sec
OOF RMSE: 2.67 | R2: 0.41
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 20:11:42,289] Trial 21 finished with value: 0.40537210613348673 and parameters: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.003270425726363511, 'learning_rate': 'adaptive', 'learning_rate_init': 0.000404984159729172}. Best is trial 18 with value: 0.4171571567444524.

Fold 5
Running time: 1.3 sec
OOF RMSE: 2.67 | R2: 0.41
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 20:11:43,496] Trial 22 finished with value: 0.4153677887851547 and parameters: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.003448315912030564, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0002863784601132589}. Best is trial 18 with value: 0.4171571567444524.

Running time: 1.2 sec
OOF RMSE: 2.65 | R2: 0.42
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 20:11:44,812] Trial 23 finished with value: 0.4183214404642186 and parameters: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.000603814085925738, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0002211444593441574}. Best is trial 23 with value: 0.4183214404642186.

Running time: 1.3 sec
OOF RMSE: 2.64 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:11:45,756] Trial 24 finished with value: 0.3654051965467878 and parameters: {'hidden_layer_sizes': '50', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.0004645456365810009, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00021803227846307866}. Best is trial 23 with value: 0.4183214404642186.
[I 2025-07-11 20:11:45,757] A new study created in memory with name: no-name-b9750d1f-0360-403d-9b2a-a7d610ca95cc
[I 2025-07-11 20:11:45,845] Trial 0 finished with value: -0.10610873458332493 and parameters: {'kernel': 'sigmoid', 'C': 0.22295998460711255, 'epsilon': 0.09366937566284335, 'gamma': 'scale'}. Best is trial 0 with value: -0.10610873458332493.
[I 2025-07-11 20:11:45,943] Trial 1 finished with value: -11.799666598922425 and parameters: {'kernel': 'sigmoid', 'C': 1.587456501804501, 'epsilon': 0.06928772971801936, 'gamma': 'auto'}. Best is trial 0 with value: -0.10610873458332493.

Running time: 0.9 sec
OOF RMSE: 2.76 | R2: 0.37

✅ MLP - Mejor R2: 0.42
📋 Parámetros: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.000603814085925738, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0002211444593441574}

Buscando mejores hiperparámetros para SVR...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.65 | R2: -0.11
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 12.40 | R2: -11.80
Fold 1

[I 2025-07-11 20:11:46,019] Trial 2 finished with value: -2.6915561710790676 and parameters: {'kernel': 'sigmoid', 'C': 0.862385961226261, 'epsilon': 0.13882998095229807, 'gamma': 'scale'}. Best is trial 0 with value: -0.10610873458332493.
[I 2025-07-11 20:11:46,099] Trial 3 finished with value: 0.36690551112311287 and parameters: {'kernel': 'rbf', 'C': 6.955950774800143, 'epsilon': 0.11362111183642196, 'gamma': 'auto'}. Best is trial 3 with value: 0.36690551112311287.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 6.66 | R2: -2.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.76 | R2: 0.37
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:11:46,175] Trial 4 finished with value: -76.72697995576902 and parameters: {'kernel': 'sigmoid', 'C': 4.123769964850733, 'epsilon': 0.1517656762442105, 'gamma': 'auto'}. Best is trial 3 with value: 0.36690551112311287.
[I 2025-07-11 20:11:46,250] Trial 5 finished with value: -75.23964254261801 and parameters: {'kernel': 'sigmoid', 'C': 4.083703825372802, 'epsilon': 0.19648749320525444, 'gamma': 'auto'}. Best is trial 3 with value: 0.36690551112311287.
[I 2025-07-11 20:11:46,321] Trial 6 finished with value: 0.16098418324774766 and parameters: {'kernel': 'rbf', 'C': 0.5597489212884867, 'epsilon': 0.1807965863848522, 'gamma': 'auto'}. Best is trial 3 with value: 0.36690551112311287.

Running time: 0.1 sec
OOF RMSE: 30.56 | R2: -76.73
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 30.27 | R2: -75.24
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.18 | R2: 0.16
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:11:46,387] Trial 7 finished with value: 0.18866421304533454 and parameters: {'kernel': 'rbf', 'C': 0.7853436212330922, 'epsilon': 0.020936547404961033, 'gamma': 'auto'}. Best is trial 3 with value: 0.36690551112311287.
[I 2025-07-11 20:11:46,466] Trial 8 finished with value: -125.98550612046147 and parameters: {'kernel': 'sigmoid', 'C': 6.546371188564796, 'epsilon': 0.06694138996203483, 'gamma': 'scale'}. Best is trial 3 with value: 0.36690551112311287.
[I 2025-07-11 20:11:46,542] Trial 9 finished with value: -23.930336432017494 and parameters: {'kernel': 'sigmoid', 'C': 2.7536712957201814, 'epsilon': 0.01289908448093023, 'gamma': 'scale'}. Best is trial 3 with value: 0.36690551112311287.

Running time: 0.1 sec
OOF RMSE: 3.12 | R2: 0.19
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 39.06 | R2: -125.99
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 17.31 | R2: -23.93
Fold 1
Fold 2
Fold 3

[I 2025-07-11 20:11:46,621] Trial 10 finished with value: 0.3799785744039669 and parameters: {'kernel': 'rbf', 'C': 8.830653644985947, 'epsilon': 0.12300183665177838, 'gamma': 'auto'}. Best is trial 10 with value: 0.3799785744039669.
[I 2025-07-11 20:11:46,706] Trial 11 finished with value: 0.3766235329407446 and parameters: {'kernel': 'rbf', 'C': 8.339523234873498, 'epsilon': 0.12348303215459398, 'gamma': 'auto'}. Best is trial 10 with value: 0.3799785744039669.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.73 | R2: 0.38
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.74 | R2: 0.38
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:11:46,799] Trial 12 finished with value: 0.3715846520793653 and parameters: {'kernel': 'rbf', 'C': 7.763247742369669, 'epsilon': 0.13213557234857667, 'gamma': 'auto'}. Best is trial 10 with value: 0.3799785744039669.
[I 2025-07-11 20:11:46,880] Trial 13 finished with value: 0.38679891178078607 and parameters: {'kernel': 'rbf', 'C': 9.670914854151954, 'epsilon': 0.16045825902682004, 'gamma': 'auto'}. Best is trial 13 with value: 0.38679891178078607.
[I 2025-07-11 20:11:46,952] Trial 14 finished with value: 0.028845710036943695 and parameters: {'kernel': 'rbf', 'C': 0.11910742615172129, 'epsilon': 0.15898333678392815, 'gamma': 'auto'}. Best is trial 13 with value: 0.38679891178078607.

Running time: 0.1 sec
OOF RMSE: 2.75 | R2: 0.37
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.71 | R2: 0.39
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.42 | R2: 0.03
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 20:11:47,024] Trial 15 finished with value: 0.2735257799642238 and parameters: {'kernel': 'rbf', 'C': 1.775075217606248, 'epsilon': 0.16954171029457613, 'gamma': 'auto'}. Best is trial 13 with value: 0.38679891178078607.
[I 2025-07-11 20:11:47,106] Trial 16 finished with value: 0.33394918490502046 and parameters: {'kernel': 'rbf', 'C': 3.4466127638966197, 'epsilon': 0.09494381989986812, 'gamma': 'auto'}. Best is trial 13 with value: 0.38679891178078607.
[I 2025-07-11 20:11:47,200] Trial 17 finished with value: 0.12863979998245367 and parameters: {'kernel': 'rbf', 'C': 0.39526817116598434, 'epsilon': 0.1962524981077837, 'gamma': 'auto'}. Best is trial 13 with value: 0.38679891178078607.

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.95 | R2: 0.27
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.83 | R2: 0.33
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.24 | R2: 0.13

[I 2025-07-11 20:11:47,283] Trial 18 finished with value: 0.27349729121549216 and parameters: {'kernel': 'rbf', 'C': 1.6670255752079093, 'epsilon': 0.06845334172209178, 'gamma': 'scale'}. Best is trial 13 with value: 0.38679891178078607.
[I 2025-07-11 20:11:47,368] Trial 19 finished with value: 0.38757310038797976 and parameters: {'kernel': 'rbf', 'C': 9.907394862754069, 'epsilon': 0.1424581913785938, 'gamma': 'auto'}. Best is trial 19 with value: 0.38757310038797976.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.95 | R2: 0.27
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.71 | R2: 0.39
Fold 1
Fold 2
Fold 3

[I 2025-07-11 20:11:47,443] Trial 20 finished with value: 0.30066580190164527 and parameters: {'kernel': 'rbf', 'C': 2.3336609331670277, 'epsilon': 0.16663051801311876, 'gamma': 'auto'}. Best is trial 19 with value: 0.38757310038797976.
[I 2025-07-11 20:11:47,528] Trial 21 finished with value: 0.38354766108630467 and parameters: {'kernel': 'rbf', 'C': 9.187450871431334, 'epsilon': 0.1455583905076953, 'gamma': 'auto'}. Best is trial 19 with value: 0.38757310038797976.
[I 2025-07-11 20:11:47,608] Trial 22 finished with value: 0.3478155120660359 and parameters: {'kernel': 'rbf', 'C': 5.050686729179963, 'epsilon': 0.1361135791812321, 'gamma': 'auto'}. Best is trial 19 with value: 0.38757310038797976.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.90 | R2: 0.30
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.72 | R2: 0.38
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.80 | R2: 0.35

[I 2025-07-11 20:11:47,690] Trial 23 finished with value: 0.38763997162651764 and parameters: {'kernel': 'rbf', 'C': 9.904770636445543, 'epsilon': 0.14646713014418933, 'gamma': 'auto'}. Best is trial 23 with value: 0.38763997162651764.
[I 2025-07-11 20:11:47,772] Trial 24 finished with value: 0.3511265533431214 and parameters: {'kernel': 'rbf', 'C': 5.101529953929584, 'epsilon': 0.17791813133463166, 'gamma': 'auto'}. Best is trial 23 with value: 0.38763997162651764.
[I 2025-07-11 20:11:47,773] A new study created in memory with name: no-name-1234e440-21f9-48be-ab1b-d4827b1126ef

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.71 | R2: 0.39
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.79 | R2: 0.35

✅ SVR - Mejor R2: 0.39
📋 Parámetros: {'kernel': 'rbf', 'C': 9.904770636445543, 'epsilon': 0.14646713014418933, 'gamma': 'auto'}

Buscando mejores hiperparámetros para KNN...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:11:47,832] Trial 0 finished with value: 0.47141218733201684 and parameters: {'n_neighbors': 9, 'weights': 'uniform', 'leaf_size': 16}. Best is trial 0 with value: 0.47141218733201684.
[I 2025-07-11 20:11:47,894] Trial 1 finished with value: 0.5152369349742637 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'leaf_size': 29}. Best is trial 1 with value: 0.5152369349742637.
[I 2025-07-11 20:11:47,960] Trial 2 finished with value: 0.4579965179190665 and parameters: {'n_neighbors': 12, 'weights': 'uniform', 'leaf_size': 38}. Best is trial 1 with value: 0.5152369349742637.
[I 2025-07-11 20:11:48,021] Trial 3 finished with value: 0.4242968434716812 and parameters: {'n_neighbors': 4, 'weights': 'uniform', 'leaf_size': 37}. Best is trial 1 with value: 0.5152369349742637.

Running time: 0.1 sec
OOF RMSE: 2.52 | R2: 0.47
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.41 | R2: 0.52
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.55 | R2: 0.46
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.63 | R2: 0.42
Fold 1

[I 2025-07-11 20:11:48,087] Trial 4 finished with value: 0.47793168391712193 and parameters: {'n_neighbors': 7, 'weights': 'uniform', 'leaf_size': 13}. Best is trial 1 with value: 0.5152369349742637.
[I 2025-07-11 20:11:48,152] Trial 5 finished with value: 0.39089336858242374 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 18}. Best is trial 1 with value: 0.5152369349742637.
[I 2025-07-11 20:11:48,218] Trial 6 finished with value: 0.4910675523665132 and parameters: {'n_neighbors': 6, 'weights': 'uniform', 'leaf_size': 12}. Best is trial 1 with value: 0.5152369349742637.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.50 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.71 | R2: 0.39
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.47 | R2: 0.49
Fold 1
Fold 2

[I 2025-07-11 20:11:48,279] Trial 7 finished with value: 0.5267051435336476 and parameters: {'n_neighbors': 8, 'weights': 'distance', 'leaf_size': 23}. Best is trial 7 with value: 0.5267051435336476.
[I 2025-07-11 20:11:48,348] Trial 8 finished with value: 0.39089336858242374 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 34}. Best is trial 7 with value: 0.5267051435336476.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.38 | R2: 0.53
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.71 | R2: 0.39
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 20:11:48,459] Trial 9 finished with value: 0.5060160073393988 and parameters: {'n_neighbors': 14, 'weights': 'distance', 'leaf_size': 39}. Best is trial 7 with value: 0.5267051435336476.
[I 2025-07-11 20:11:48,529] Trial 10 finished with value: 0.5163993139131284 and parameters: {'n_neighbors': 10, 'weights': 'distance', 'leaf_size': 24}. Best is trial 7 with value: 0.5267051435336476.
[I 2025-07-11 20:11:48,605] Trial 11 finished with value: 0.5163993139131284 and parameters: {'n_neighbors': 10, 'weights': 'distance', 'leaf_size': 23}. Best is trial 7 with value: 0.5267051435336476.

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.44 | R2: 0.51
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.41 | R2: 0.52
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.41 | R2: 0.52
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 20:11:48,670] Trial 12 finished with value: 0.5086362157214305 and parameters: {'n_neighbors': 9, 'weights': 'distance', 'leaf_size': 25}. Best is trial 7 with value: 0.5267051435336476.
[I 2025-07-11 20:11:48,741] Trial 13 finished with value: 0.508763273274615 and parameters: {'n_neighbors': 11, 'weights': 'distance', 'leaf_size': 21}. Best is trial 7 with value: 0.5267051435336476.
[I 2025-07-11 20:11:48,817] Trial 14 finished with value: 0.5142645711630542 and parameters: {'n_neighbors': 13, 'weights': 'distance', 'leaf_size': 29}. Best is trial 7 with value: 0.5267051435336476.

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.43 | R2: 0.51
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.43 | R2: 0.51
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.42 | R2: 0.51
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 20:11:48,882] Trial 15 finished with value: 0.5267051435336476 and parameters: {'n_neighbors': 8, 'weights': 'distance', 'leaf_size': 29}. Best is trial 7 with value: 0.5267051435336476.
[I 2025-07-11 20:11:48,955] Trial 16 finished with value: 0.5060186050196378 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'leaf_size': 29}. Best is trial 7 with value: 0.5267051435336476.
[I 2025-07-11 20:11:49,030] Trial 17 finished with value: 0.5267051435336476 and parameters: {'n_neighbors': 8, 'weights': 'distance', 'leaf_size': 32}. Best is trial 7 with value: 0.5267051435336476.

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.38 | R2: 0.53
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.44 | R2: 0.51
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.38 | R2: 0.53
Fold 1
Fold 2
Fold 3

[I 2025-07-11 20:11:49,094] Trial 18 finished with value: 0.5152342174662179 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'leaf_size': 20}. Best is trial 7 with value: 0.5267051435336476.
[I 2025-07-11 20:11:49,167] Trial 19 finished with value: 0.5267051435336476 and parameters: {'n_neighbors': 8, 'weights': 'distance', 'leaf_size': 32}. Best is trial 7 with value: 0.5267051435336476.
[I 2025-07-11 20:11:49,239] Trial 20 finished with value: 0.49338547215140405 and parameters: {'n_neighbors': 15, 'weights': 'distance', 'leaf_size': 28}. Best is trial 7 with value: 0.5267051435336476.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.41 | R2: 0.52
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.38 | R2: 0.53
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.47 | R2: 0.49
Fold 1
Fold 2
Fold 3

[I 2025-07-11 20:11:49,302] Trial 21 finished with value: 0.5267051435336476 and parameters: {'n_neighbors': 8, 'weights': 'distance', 'leaf_size': 34}. Best is trial 7 with value: 0.5267051435336476.
[I 2025-07-11 20:11:49,375] Trial 22 finished with value: 0.5267051435336476 and parameters: {'n_neighbors': 8, 'weights': 'distance', 'leaf_size': 32}. Best is trial 7 with value: 0.5267051435336476.
[I 2025-07-11 20:11:49,444] Trial 23 finished with value: 0.5163993139131284 and parameters: {'n_neighbors': 10, 'weights': 'distance', 'leaf_size': 27}. Best is trial 7 with value: 0.5267051435336476.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.38 | R2: 0.53
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.38 | R2: 0.53
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.41 | R2: 0.52
Fold 1
Fold 2

[I 2025-07-11 20:11:49,536] Trial 24 finished with value: 0.5152369349742637 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'leaf_size': 32}. Best is trial 7 with value: 0.5267051435336476.
[I 2025-07-11 20:11:49,537] A new study created in memory with name: no-name-68791204-5f03-44c7-9b7b-9565a656a8b6
[I 2025-07-11 20:11:49,628] Trial 0 finished with value: -0.7469406175900775 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 0 with value: -0.7469406175900775.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.41 | R2: 0.52

✅ KNN - Mejor R2: 0.53
📋 Parámetros: {'n_neighbors': 8, 'weights': 'distance', 'leaf_size': 23}

Buscando mejores hiperparámetros para LR...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 4.58 | R2: -0.75
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:11:49,707] Trial 1 finished with value: 0.23018305785573023 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.23018305785573023.
[I 2025-07-11 20:11:49,810] Trial 2 finished with value: -0.7469406175900775 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 1 with value: 0.23018305785573023.
[I 2025-07-11 20:11:49,902] Trial 3 finished with value: 0.19399351987433755 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 1 with value: 0.23018305785573023.

Running time: 0.1 sec
OOF RMSE: 3.04 | R2: 0.23
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 4.58 | R2: -0.75
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.11 | R2: 0.19
Fold 1

[I 2025-07-11 20:11:49,962] Trial 4 finished with value: 0.23018305785573023 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.23018305785573023.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.04 | R2: 0.23
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:11:50,155] Trial 5 finished with value: -0.7469406175900775 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 1 with value: 0.23018305785573023.
[I 2025-07-11 20:11:50,233] Trial 6 finished with value: 0.23018305785573023 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.23018305785573023.
[I 2025-07-11 20:11:50,300] Trial 7 finished with value: 0.19399351987433755 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 1 with value: 0.23018305785573023.

Running time: 0.2 sec
OOF RMSE: 4.58 | R2: -0.75
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.04 | R2: 0.23
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.11 | R2: 0.19
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec

[I 2025-07-11 20:11:50,356] Trial 8 finished with value: 0.19399351987433755 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 1 with value: 0.23018305785573023.
[I 2025-07-11 20:11:50,413] Trial 9 finished with value: 0.19399351987433755 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 1 with value: 0.23018305785573023.
[I 2025-07-11 20:11:50,497] Trial 10 finished with value: -0.7469406175435105 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 1 with value: 0.23018305785573023.

OOF RMSE: 3.11 | R2: 0.19
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.11 | R2: 0.19
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 4.58 | R2: -0.75
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 20:11:50,572] Trial 11 finished with value: 0.23018305785573023 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.23018305785573023.
[I 2025-07-11 20:11:50,633] Trial 12 finished with value: 0.23018305785573023 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.23018305785573023.
[I 2025-07-11 20:11:50,696] Trial 13 finished with value: 0.23018305785573023 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.23018305785573023.
[I 2025-07-11 20:11:50,756] Trial 14 finished with value: 0.23018305785573023 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.23018305785573023.

Fold 5
Running time: 0.1 sec
OOF RMSE: 3.04 | R2: 0.23
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.04 | R2: 0.23
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.04 | R2: 0.23
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.04 | R2: 0.23

[I 2025-07-11 20:11:50,814] Trial 15 finished with value: 0.23018305785573023 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.23018305785573023.
[I 2025-07-11 20:11:50,877] Trial 16 finished with value: 0.23018305785573023 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.23018305785573023.
[I 2025-07-11 20:11:50,938] Trial 17 finished with value: 0.23018305785573023 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.23018305785573023.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.04 | R2: 0.23
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.04 | R2: 0.23
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.04 | R2: 0.23
Fold 1
Fold 2

[I 2025-07-11 20:11:51,014] Trial 18 finished with value: -0.7469406175435105 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 1 with value: 0.23018305785573023.
[I 2025-07-11 20:11:51,118] Trial 19 finished with value: 0.23018305785573023 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.23018305785573023.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 4.58 | R2: -0.75
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.04 | R2: 0.23
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:11:51,184] Trial 20 finished with value: 0.23018305785573023 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.23018305785573023.
[I 2025-07-11 20:11:51,245] Trial 21 finished with value: 0.23018305785573023 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.23018305785573023.
[I 2025-07-11 20:11:51,308] Trial 22 finished with value: 0.23018305785573023 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.23018305785573023.
[I 2025-07-11 20:11:51,369] Trial 23 finished with value: 0.23018305785573023 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.23018305785573023.

Running time: 0.1 sec
OOF RMSE: 3.04 | R2: 0.23
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.04 | R2: 0.23
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.04 | R2: 0.23
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.04 | R2: 0.23
Fold 1
Fold 2

[I 2025-07-11 20:11:51,428] Trial 24 finished with value: 0.23018305785573023 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.23018305785573023.
[I 2025-07-11 20:11:51,428] A new study created in memory with name: no-name-4784542c-dfd0-455d-9c48-396e9b203e2a

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.04 | R2: 0.23

✅ LR - Mejor R2: 0.23
📋 Parámetros: {'fit_intercept': False, 'positive': True}

Buscando mejores hiperparámetros para RF...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:12:03,172] Trial 0 finished with value: 0.13128142554626798 and parameters: {'n_estimators': 500, 'max_depth': 9, 'min_samples_split': 4, 'min_samples_leaf': 5, 'bootstrap': False}. Best is trial 0 with value: 0.13128142554626798.

Running time: 11.7 sec
OOF RMSE: 3.23 | R2: 0.13
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:12:12,124] Trial 1 finished with value: 0.3912849100873087 and parameters: {'n_estimators': 300, 'max_depth': 15, 'min_samples_split': 6, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 1 with value: 0.3912849100873087.

Running time: 8.9 sec
OOF RMSE: 2.70 | R2: 0.39
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:12:13,508] Trial 2 finished with value: 0.36338746798883337 and parameters: {'n_estimators': 100, 'max_depth': 7, 'min_samples_split': 10, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 1 with value: 0.3912849100873087.

Running time: 1.4 sec
OOF RMSE: 2.77 | R2: 0.36
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:12:18,434] Trial 3 finished with value: 0.38566995045438934 and parameters: {'n_estimators': 300, 'max_depth': 10, 'min_samples_split': 4, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 1 with value: 0.3912849100873087.

Running time: 4.9 sec
OOF RMSE: 2.72 | R2: 0.39
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:12:19,948] Trial 4 finished with value: 0.3729431230067697 and parameters: {'n_estimators': 100, 'max_depth': 11, 'min_samples_split': 9, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 1 with value: 0.3912849100873087.

Running time: 1.5 sec
OOF RMSE: 2.75 | R2: 0.37
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:12:21,332] Trial 5 finished with value: 0.36338746798883337 and parameters: {'n_estimators': 100, 'max_depth': 7, 'min_samples_split': 6, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 1 with value: 0.3912849100873087.

Running time: 1.4 sec
OOF RMSE: 2.77 | R2: 0.36
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:12:23,951] Trial 6 finished with value: 0.32793564671506514 and parameters: {'n_estimators': 100, 'max_depth': 12, 'min_samples_split': 10, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 1 with value: 0.3912849100873087.

Running time: 2.6 sec
OOF RMSE: 2.84 | R2: 0.33
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:12:36,476] Trial 7 finished with value: 0.33915611619708763 and parameters: {'n_estimators': 500, 'max_depth': 13, 'min_samples_split': 10, 'min_samples_leaf': 4, 'bootstrap': False}. Best is trial 1 with value: 0.3912849100873087.

Running time: 12.5 sec
OOF RMSE: 2.82 | R2: 0.34
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:12:40,743] Trial 8 finished with value: 0.36743715101835295 and parameters: {'n_estimators': 300, 'max_depth': 14, 'min_samples_split': 7, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 1 with value: 0.3912849100873087.

Running time: 4.3 sec
OOF RMSE: 2.76 | R2: 0.37
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:12:52,008] Trial 9 finished with value: 0.2816475525907923 and parameters: {'n_estimators': 500, 'max_depth': 7, 'min_samples_split': 4, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 1 with value: 0.3912849100873087.

Running time: 11.3 sec
OOF RMSE: 2.94 | R2: 0.28
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:13:01,272] Trial 10 finished with value: 0.3161774993479758 and parameters: {'n_estimators': 300, 'max_depth': 15, 'min_samples_split': 7, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 1 with value: 0.3912849100873087.

Running time: 9.3 sec
OOF RMSE: 2.87 | R2: 0.32
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:13:06,498] Trial 11 finished with value: 0.4056757658875495 and parameters: {'n_estimators': 300, 'max_depth': 9, 'min_samples_split': 2, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 11 with value: 0.4056757658875495.

Running time: 5.2 sec
OOF RMSE: 2.67 | R2: 0.41
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:13:12,116] Trial 12 finished with value: 0.31365100455783046 and parameters: {'n_estimators': 300, 'max_depth': 5, 'min_samples_split': 3, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 11 with value: 0.4056757658875495.

Running time: 5.6 sec
OOF RMSE: 2.87 | R2: 0.31
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:13:17,354] Trial 13 finished with value: 0.4056757658875495 and parameters: {'n_estimators': 300, 'max_depth': 9, 'min_samples_split': 2, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 11 with value: 0.4056757658875495.

Running time: 5.2 sec
OOF RMSE: 2.67 | R2: 0.41
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:13:22,596] Trial 14 finished with value: 0.4056757658875495 and parameters: {'n_estimators': 300, 'max_depth': 9, 'min_samples_split': 2, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 11 with value: 0.4056757658875495.

Running time: 5.2 sec
OOF RMSE: 2.67 | R2: 0.41
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:13:27,813] Trial 15 finished with value: 0.4056757658875495 and parameters: {'n_estimators': 300, 'max_depth': 9, 'min_samples_split': 2, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 11 with value: 0.4056757658875495.

Running time: 5.2 sec
OOF RMSE: 2.67 | R2: 0.41
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:13:31,699] Trial 16 finished with value: 0.4002151634388179 and parameters: {'n_estimators': 300, 'max_depth': 5, 'min_samples_split': 3, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 11 with value: 0.4056757658875495.

Running time: 3.9 sec
OOF RMSE: 2.68 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:13:37,885] Trial 17 finished with value: 0.41003056967862694 and parameters: {'n_estimators': 300, 'max_depth': 11, 'min_samples_split': 2, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 17 with value: 0.41003056967862694.

Running time: 6.2 sec
OOF RMSE: 2.66 | R2: 0.41
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:13:43,694] Trial 18 finished with value: 0.4014317938508799 and parameters: {'n_estimators': 300, 'max_depth': 11, 'min_samples_split': 5, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 17 with value: 0.41003056967862694.

Running time: 5.8 sec
OOF RMSE: 2.68 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:13:53,857] Trial 19 finished with value: 0.4141804959652422 and parameters: {'n_estimators': 500, 'max_depth': 12, 'min_samples_split': 3, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 19 with value: 0.4141804959652422.

Running time: 10.2 sec
OOF RMSE: 2.65 | R2: 0.41
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:14:04,133] Trial 20 finished with value: 0.4101481526160726 and parameters: {'n_estimators': 500, 'max_depth': 13, 'min_samples_split': 3, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 19 with value: 0.4141804959652422.

Running time: 10.3 sec
OOF RMSE: 2.66 | R2: 0.41
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:14:14,418] Trial 21 finished with value: 0.4101481526160726 and parameters: {'n_estimators': 500, 'max_depth': 13, 'min_samples_split': 3, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 19 with value: 0.4141804959652422.

Running time: 10.3 sec
OOF RMSE: 2.66 | R2: 0.41
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:14:24,682] Trial 22 finished with value: 0.4101481526160726 and parameters: {'n_estimators': 500, 'max_depth': 13, 'min_samples_split': 3, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 19 with value: 0.4141804959652422.

Running time: 10.3 sec
OOF RMSE: 2.66 | R2: 0.41
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:14:34,404] Trial 23 finished with value: 0.4118006115219698 and parameters: {'n_estimators': 500, 'max_depth': 13, 'min_samples_split': 5, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 19 with value: 0.4141804959652422.

Running time: 9.7 sec
OOF RMSE: 2.66 | R2: 0.41
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:14:44,177] Trial 24 finished with value: 0.409991958201428 and parameters: {'n_estimators': 500, 'max_depth': 14, 'min_samples_split': 5, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 19 with value: 0.4141804959652422.
[I 2025-07-11 20:14:44,178] A new study created in memory with name: no-name-c12eafe9-923d-4b62-92c4-47ce1edf8579

Running time: 9.8 sec
OOF RMSE: 2.66 | R2: 0.41

✅ RF - Mejor R2: 0.41
📋 Parámetros: {'n_estimators': 500, 'max_depth': 12, 'min_samples_split': 3, 'min_samples_leaf': 1, 'bootstrap': True}

Buscando mejores hiperparámetros para CAT...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:15:22,741] Trial 0 finished with value: 0.5086841013917826 and parameters: {'iterations': 1000, 'learning_rate': 0.05632396084168866, 'depth': 8, 'l2_leaf_reg': 4.1591658487683025}. Best is trial 0 with value: 0.5086841013917826.

Running time: 38.6 sec
OOF RMSE: 2.43 | R2: 0.51
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:16:07,456] Trial 1 finished with value: 0.4802641838700895 and parameters: {'iterations': 500, 'learning_rate': 0.08374603922317754, 'depth': 9, 'l2_leaf_reg': 3.311748989692683}. Best is trial 0 with value: 0.5086841013917826.

Running time: 44.7 sec
OOF RMSE: 2.50 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:16:50,763] Trial 2 finished with value: 0.45168651846433183 and parameters: {'iterations': 500, 'learning_rate': 0.0276615661608578, 'depth': 9, 'l2_leaf_reg': 9.794512719689884}. Best is trial 0 with value: 0.5086841013917826.

Running time: 43.3 sec
OOF RMSE: 2.57 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:17:05,530] Trial 3 finished with value: 0.5133951465700313 and parameters: {'iterations': 1000, 'learning_rate': 0.08123535470320507, 'depth': 7, 'l2_leaf_reg': 5.71330103991811}. Best is trial 3 with value: 0.5133951465700313.

Running time: 14.8 sec
OOF RMSE: 2.42 | R2: 0.51
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:17:14,031] Trial 4 finished with value: 0.5383239743883467 and parameters: {'iterations': 2000, 'learning_rate': 0.0239996567562017, 'depth': 5, 'l2_leaf_reg': 2.085352338159665}. Best is trial 4 with value: 0.5383239743883467.

Running time: 8.5 sec
OOF RMSE: 2.36 | R2: 0.54
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:17:52,517] Trial 5 finished with value: 0.48705078215963915 and parameters: {'iterations': 1000, 'learning_rate': 0.044455716778403924, 'depth': 8, 'l2_leaf_reg': 4.868286629077813}. Best is trial 4 with value: 0.5383239743883467.

Running time: 38.5 sec
OOF RMSE: 2.48 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:20:20,992] Trial 6 finished with value: 0.4710698965637492 and parameters: {'iterations': 1000, 'learning_rate': 0.03942109805011334, 'depth': 10, 'l2_leaf_reg': 7.720326762106038}. Best is trial 4 with value: 0.5383239743883467.

Running time: 148.5 sec
OOF RMSE: 2.52 | R2: 0.47
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:20:59,571] Trial 7 finished with value: 0.4993880831167836 and parameters: {'iterations': 1000, 'learning_rate': 0.019357908191504763, 'depth': 8, 'l2_leaf_reg': 2.707131954317054}. Best is trial 4 with value: 0.5383239743883467.

Running time: 38.6 sec
OOF RMSE: 2.45 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:21:08,482] Trial 8 finished with value: 0.5294719067025289 and parameters: {'iterations': 2000, 'learning_rate': 0.06864802419401998, 'depth': 5, 'l2_leaf_reg': 7.4069189011068435}. Best is trial 4 with value: 0.5383239743883467.

Running time: 8.9 sec
OOF RMSE: 2.38 | R2: 0.53
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:21:16,083] Trial 9 finished with value: 0.44537970377917724 and parameters: {'iterations': 500, 'learning_rate': 0.011437101786590681, 'depth': 7, 'l2_leaf_reg': 6.831795903384276}. Best is trial 4 with value: 0.5383239743883467.

Running time: 7.6 sec
OOF RMSE: 2.58 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:21:22,236] Trial 10 finished with value: 0.5088227949690751 and parameters: {'iterations': 2000, 'learning_rate': 0.01689676815497181, 'depth': 4, 'l2_leaf_reg': 1.0054926055766185}. Best is trial 4 with value: 0.5383239743883467.

Running time: 6.1 sec
OOF RMSE: 2.43 | R2: 0.51
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:21:30,977] Trial 11 finished with value: 0.5209410369560196 and parameters: {'iterations': 2000, 'learning_rate': 0.024756431039335395, 'depth': 5, 'l2_leaf_reg': 8.372020716867459}. Best is trial 4 with value: 0.5383239743883467.

Running time: 8.7 sec
OOF RMSE: 2.40 | R2: 0.52
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:21:40,007] Trial 12 finished with value: 0.5326696761683497 and parameters: {'iterations': 2000, 'learning_rate': 0.05773190671364394, 'depth': 5, 'l2_leaf_reg': 1.057997499002612}. Best is trial 4 with value: 0.5383239743883467.

Running time: 9.0 sec
OOF RMSE: 2.37 | R2: 0.53
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:21:48,664] Trial 13 finished with value: 0.5484377481511908 and parameters: {'iterations': 2000, 'learning_rate': 0.03758006228280968, 'depth': 5, 'l2_leaf_reg': 1.1019188580461348}. Best is trial 13 with value: 0.5484377481511908.

Running time: 8.7 sec
OOF RMSE: 2.33 | R2: 0.55
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:22:02,146] Trial 14 finished with value: 0.505649554737101 and parameters: {'iterations': 2000, 'learning_rate': 0.03323395006542287, 'depth': 6, 'l2_leaf_reg': 2.1661458166478833}. Best is trial 13 with value: 0.5484377481511908.

Running time: 13.5 sec
OOF RMSE: 2.44 | R2: 0.51
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:22:08,547] Trial 15 finished with value: 0.5021788438245263 and parameters: {'iterations': 2000, 'learning_rate': 0.017761918051117587, 'depth': 4, 'l2_leaf_reg': 2.0705520762522127}. Best is trial 13 with value: 0.5484377481511908.

Running time: 6.4 sec
OOF RMSE: 2.45 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:22:21,686] Trial 16 finished with value: 0.5106002381736614 and parameters: {'iterations': 2000, 'learning_rate': 0.01035092688814694, 'depth': 6, 'l2_leaf_reg': 3.6075029864555535}. Best is trial 13 with value: 0.5484377481511908.

Running time: 13.1 sec
OOF RMSE: 2.43 | R2: 0.51
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:22:35,032] Trial 17 finished with value: 0.5011249181700532 and parameters: {'iterations': 2000, 'learning_rate': 0.022326358685131532, 'depth': 6, 'l2_leaf_reg': 1.8129564963947074}. Best is trial 13 with value: 0.5484377481511908.

Running time: 13.3 sec
OOF RMSE: 2.45 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:22:40,917] Trial 18 finished with value: 0.5142882664926078 and parameters: {'iterations': 2000, 'learning_rate': 0.013651642223700364, 'depth': 4, 'l2_leaf_reg': 5.605882144012532}. Best is trial 13 with value: 0.5484377481511908.

Running time: 5.9 sec
OOF RMSE: 2.42 | R2: 0.51
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:22:49,657] Trial 19 finished with value: 0.5272563923026026 and parameters: {'iterations': 2000, 'learning_rate': 0.034852529746403724, 'depth': 5, 'l2_leaf_reg': 2.8743752906621696}. Best is trial 13 with value: 0.5484377481511908.

Running time: 8.7 sec
OOF RMSE: 2.38 | R2: 0.53
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:22:52,922] Trial 20 finished with value: 0.497397961808579 and parameters: {'iterations': 500, 'learning_rate': 0.045926928716510156, 'depth': 6, 'l2_leaf_reg': 4.5566886093002745}. Best is trial 13 with value: 0.5484377481511908.

Running time: 3.3 sec
OOF RMSE: 2.46 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:23:02,275] Trial 21 finished with value: 0.5381291536191937 and parameters: {'iterations': 2000, 'learning_rate': 0.057367899577487336, 'depth': 5, 'l2_leaf_reg': 1.7485664488467703}. Best is trial 13 with value: 0.5484377481511908.

Running time: 9.3 sec
OOF RMSE: 2.36 | R2: 0.54
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:23:10,759] Trial 22 finished with value: 0.5445885638671897 and parameters: {'iterations': 2000, 'learning_rate': 0.09833254685678336, 'depth': 5, 'l2_leaf_reg': 1.6559389992608753}. Best is trial 13 with value: 0.5484377481511908.

Running time: 8.5 sec
OOF RMSE: 2.34 | R2: 0.54
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:23:17,176] Trial 23 finished with value: 0.5281529640856578 and parameters: {'iterations': 2000, 'learning_rate': 0.09878655956888692, 'depth': 4, 'l2_leaf_reg': 1.028644991066214}. Best is trial 13 with value: 0.5484377481511908.

Running time: 6.4 sec
OOF RMSE: 2.38 | R2: 0.53
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:23:30,585] Trial 24 finished with value: 0.5087859216792652 and parameters: {'iterations': 2000, 'learning_rate': 0.02812789438194364, 'depth': 6, 'l2_leaf_reg': 2.5254092390564886}. Best is trial 13 with value: 0.5484377481511908.
[I 2025-07-11 20:23:30,586] A new study created in memory with name: no-name-a83a1a6c-a9d8-4e4b-ac50-cc03128bc25a
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.117e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.414e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.357e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.880e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.178e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 20:23:30,710] Trial 0 finished with value: -0.8040893386775183 and parameters: {'alpha': 0.00022062185114997827, 'l1_ratio': 0.1558804709227949}. Best is trial 0 with value: -0.8040893386775183.

Running time: 13.4 sec
OOF RMSE: 2.43 | R2: 0.51

✅ CAT - Mejor R2: 0.55
📋 Parámetros: {'iterations': 2000, 'learning_rate': 0.03758006228280968, 'depth': 5, 'l2_leaf_reg': 1.1019188580461348}

Buscando mejores hiperparámetros para EN...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 4.66 | R2: -0.80
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:23:30,804] Trial 1 finished with value: 0.40430498318211405 and parameters: {'alpha': 3.959547403558004, 'l1_ratio': 0.08191320396214008}. Best is trial 1 with value: 0.40430498318211405.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.193e+01, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.672e+00, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.008e+01, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.266e+01, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.106e+01, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 20:23:30,924] Trial 2 finished with value: 0.20071910382904246 and parameters: {'alpha': 0.012677216257437854, 'l1_ratio': 0.35864238746899046}. Best is trial 1 with value: 0.40430498318211405.

Running time: 0.1 sec
OOF RMSE: 2.68 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.10 | R2: 0.20
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:23:31,011] Trial 3 finished with value: 0.0041159461809263664 and parameters: {'alpha': 6.267681614642128, 'l1_ratio': 0.7396228506948489}. Best is trial 1 with value: 0.40430498318211405.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.625e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.941e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.768e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.007e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.453e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 20:23:31,143] Trial 4 finished with value: -0.13594522153188993 and parameters: {'alpha': 0.0033946089864627547, 'l1_ratio': 0.2592840009691467}. Best is trial 1 with value: 0.40430498318211405.

Running time: 0.1 sec
OOF RMSE: 3.46 | R2: 0.00
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.69 | R2: -0.14
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 20:23:31,234] Trial 5 finished with value: -0.00027817151752640434 and parameters: {'alpha': 8.634122062847785, 'l1_ratio': 0.8761839045715613}. Best is trial 1 with value: 0.40430498318211405.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.773e+00, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.578e+00, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.965e+00, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.787e+00, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 20:23:31,356] Trial 6 finished with value: 0.2780713195930552 and parameters: {'alpha': 0.020411627693679636, 'l1_ratio': 0.4381254381432417}. Best is trial 1 with value: 0.40430498318211405.

Fold 5
Running time: 0.1 sec
OOF RMSE: 3.47 | R2: -0.00
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.95 | R2: 0.28
Fold 1
Fold 2
Fold 3

[I 2025-07-11 20:23:31,467] Trial 7 finished with value: 0.3933082055593309 and parameters: {'alpha': 0.04719938356121529, 'l1_ratio': 0.6490655856065504}. Best is trial 1 with value: 0.40430498318211405.
[I 2025-07-11 20:23:31,564] Trial 8 finished with value: 0.3636229283310596 and parameters: {'alpha': 1.8117867837651995, 'l1_ratio': 0.6740351995189984}. Best is trial 1 with value: 0.40430498318211405.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.70 | R2: 0.39
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.77 | R2: 0.36
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 20:23:31,649] Trial 9 finished with value: 0.32216200621621616 and parameters: {'alpha': 4.9517121264500705, 'l1_ratio': 0.26202729852183493}. Best is trial 1 with value: 0.40430498318211405.
[I 2025-07-11 20:23:31,751] Trial 10 finished with value: 0.4194273161830856 and parameters: {'alpha': 0.3917933030038935, 'l1_ratio': 0.08073757155932931}. Best is trial 10 with value: 0.4194273161830856.

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.85 | R2: 0.32
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.64 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 20:23:31,859] Trial 11 finished with value: 0.4109929323664471 and parameters: {'alpha': 0.3206684610251112, 'l1_ratio': 0.02028009705813838}. Best is trial 10 with value: 0.4194273161830856.
[I 2025-07-11 20:23:31,985] Trial 12 finished with value: 0.40524908298369766 and parameters: {'alpha': 0.2701573262920453, 'l1_ratio': 0.0043945766308833845}. Best is trial 10 with value: 0.4194273161830856.

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.66 | R2: 0.41
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.67 | R2: 0.41
Fold 1
Fold 2
Fold 3

[I 2025-07-11 20:23:32,079] Trial 13 finished with value: 0.42366397661704447 and parameters: {'alpha': 0.49526222161820754, 'l1_ratio': 0.1612019175465048}. Best is trial 13 with value: 0.42366397661704447.
[I 2025-07-11 20:23:32,185] Trial 14 finished with value: 0.4177756164990686 and parameters: {'alpha': 0.28101824851699886, 'l1_ratio': 0.2123922030637132}. Best is trial 13 with value: 0.42366397661704447.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.63 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.65 | R2: 0.42
Fold 1
Fold 2
Fold 3

[I 2025-07-11 20:23:32,314] Trial 15 finished with value: 0.4215556320883517 and parameters: {'alpha': 0.7547916373320953, 'l1_ratio': 0.4542393730755488}. Best is trial 13 with value: 0.42366397661704447.
[I 2025-07-11 20:23:32,416] Trial 16 finished with value: 0.4149992923474527 and parameters: {'alpha': 1.064412652592074, 'l1_ratio': 0.5055903202359041}. Best is trial 13 with value: 0.42366397661704447.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.64 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.65 | R2: 0.41
Fold 1
Fold 2

[I 2025-07-11 20:23:32,540] Trial 17 finished with value: 0.3980576599539193 and parameters: {'alpha': 0.06200075525223671, 'l1_ratio': 0.5331445431947976}. Best is trial 13 with value: 0.42366397661704447.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.253e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.066e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.989e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.214e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.999e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 20:23:32,678] Trial 18 finished with value: -0.6622394289910503 and parameters: {'alpha': 0.0020241292003137404, 'l1_ratio': 0.9698942046472245}. Best is trial 13 with value: 0.42366397661704447.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.69 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 4.47 | R2: -0.66
Fold 1

[I 2025-07-11 20:23:32,772] Trial 19 finished with value: 0.42117116560122636 and parameters: {'alpha': 0.9218815077354159, 'l1_ratio': 0.37115596859485345}. Best is trial 13 with value: 0.42366397661704447.
[I 2025-07-11 20:23:32,867] Trial 20 finished with value: 0.40641603433883566 and parameters: {'alpha': 0.13312294462192048, 'l1_ratio': 0.599123679577844}. Best is trial 13 with value: 0.42366397661704447.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.64 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.67 | R2: 0.41
Fold 1
Fold 2

[I 2025-07-11 20:23:32,962] Trial 21 finished with value: 0.4149582349689136 and parameters: {'alpha': 1.3443612738420052, 'l1_ratio': 0.3778437509329139}. Best is trial 13 with value: 0.42366397661704447.
[I 2025-07-11 20:23:33,054] Trial 22 finished with value: 0.4209584346547628 and parameters: {'alpha': 0.7053533856439336, 'l1_ratio': 0.37507488080070284}. Best is trial 13 with value: 0.42366397661704447.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.65 | R2: 0.41
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.64 | R2: 0.42
Fold 1
Fold 2
Fold 3

[I 2025-07-11 20:23:33,190] Trial 23 finished with value: 0.39769412386269487 and parameters: {'alpha': 0.1002124361444877, 'l1_ratio': 0.3036037150475362}. Best is trial 13 with value: 0.42366397661704447.
[I 2025-07-11 20:23:33,301] Trial 24 finished with value: 0.4165293469486021 and parameters: {'alpha': 1.9092160119165755, 'l1_ratio': 0.14799407068231585}. Best is trial 13 with value: 0.42366397661704447.
[I 2025-07-11 20:23:33,302] A new study created in memory with name: no-name-238bb6df-b011-4b4a-b54e-067c53676877

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.69 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.65 | R2: 0.42

✅ EN - Mejor R2: 0.42
📋 Parámetros: {'alpha': 0.49526222161820754, 'l1_ratio': 0.1612019175465048}

🔍 Optimizando en C2X_rhown_5x5_depth_lt_1...
Buscando mejores hiperparámetros para XGB...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:23:36,053] Trial 0 finished with value: 0.42669611662856466 and parameters: {'n_estimators': 500, 'learning_rate': 0.029862719209488627, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.8266380114249867, 'colsample_bytree': 0.8953413623697692}. Best is trial 0 with value: 0.42669611662856466.

Running time: 2.7 sec
OOF RMSE: 2.62 | R2: 0.43
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:23:46,205] Trial 1 finished with value: 0.44611350046123655 and parameters: {'n_estimators': 1000, 'learning_rate': 0.026423961337610852, 'max_depth': 8, 'min_child_weight': 1, 'subsample': 0.7134864085214043, 'colsample_bytree': 0.9448902274202169}. Best is trial 1 with value: 0.44611350046123655.

Running time: 10.1 sec
OOF RMSE: 2.58 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:23:49,416] Trial 2 finished with value: 0.47026156131187435 and parameters: {'n_estimators': 500, 'learning_rate': 0.006418354423958036, 'max_depth': 8, 'min_child_weight': 2, 'subsample': 0.6027384268434682, 'colsample_bytree': 0.6884702258872629}. Best is trial 2 with value: 0.47026156131187435.

Running time: 3.2 sec
OOF RMSE: 2.52 | R2: 0.47
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:23:52,268] Trial 3 finished with value: 0.4721401585949594 and parameters: {'n_estimators': 500, 'learning_rate': 0.013209624170102123, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.7332771776773226, 'colsample_bytree': 0.9643356670630877}. Best is trial 3 with value: 0.4721401585949594.

Running time: 2.8 sec
OOF RMSE: 2.52 | R2: 0.47
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:24:03,942] Trial 4 finished with value: 0.4485806307860498 and parameters: {'n_estimators': 2000, 'learning_rate': 0.03989287686427072, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.672116667493359, 'colsample_bytree': 0.8703856948250643}. Best is trial 3 with value: 0.4721401585949594.

Running time: 11.7 sec
OOF RMSE: 2.57 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:24:12,405] Trial 5 finished with value: 0.3887121692166232 and parameters: {'n_estimators': 1000, 'learning_rate': 0.006882337816849834, 'max_depth': 8, 'min_child_weight': 3, 'subsample': 0.9549112397808983, 'colsample_bytree': 0.9783975080448709}. Best is trial 3 with value: 0.4721401585949594.

Running time: 8.5 sec
OOF RMSE: 2.71 | R2: 0.39
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:24:16,306] Trial 6 finished with value: 0.4090370923684158 and parameters: {'n_estimators': 1000, 'learning_rate': 0.021392232936299643, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.7653361007904265, 'colsample_bytree': 0.7315550362680988}. Best is trial 3 with value: 0.4721401585949594.

Running time: 3.9 sec
OOF RMSE: 2.66 | R2: 0.41
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:24:21,463] Trial 7 finished with value: 0.45396779930841547 and parameters: {'n_estimators': 1000, 'learning_rate': 0.03144619702962856, 'max_depth': 5, 'min_child_weight': 1, 'subsample': 0.8628828692350221, 'colsample_bytree': 0.6060460779528796}. Best is trial 3 with value: 0.4721401585949594.

Running time: 5.2 sec
OOF RMSE: 2.56 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:24:32,610] Trial 8 finished with value: 0.5025626988378273 and parameters: {'n_estimators': 2000, 'learning_rate': 0.022021699798689048, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.6250165724276987, 'colsample_bytree': 0.8306135850428079}. Best is trial 8 with value: 0.5025626988378273.

Running time: 11.1 sec
OOF RMSE: 2.44 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:24:42,224] Trial 9 finished with value: 0.3964066165813138 and parameters: {'n_estimators': 2000, 'learning_rate': 0.01497789420545529, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.7528312739596299, 'colsample_bytree': 0.9597109674737285}. Best is trial 8 with value: 0.5025626988378273.

Running time: 9.6 sec
OOF RMSE: 2.69 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:24:53,236] Trial 10 finished with value: 0.4824517043832587 and parameters: {'n_estimators': 2000, 'learning_rate': 0.011545395513489813, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.6265771568566568, 'colsample_bytree': 0.8071405270339966}. Best is trial 8 with value: 0.5025626988378273.

Running time: 11.0 sec
OOF RMSE: 2.49 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:25:03,033] Trial 11 finished with value: 0.44518602595931644 and parameters: {'n_estimators': 2000, 'learning_rate': 0.09107886336789613, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.600185226261697, 'colsample_bytree': 0.8069357094659668}. Best is trial 8 with value: 0.5025626988378273.

Running time: 9.8 sec
OOF RMSE: 2.58 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:25:14,182] Trial 12 finished with value: 0.49461351672292153 and parameters: {'n_estimators': 2000, 'learning_rate': 0.012514410710155221, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.6563707702894985, 'colsample_bytree': 0.8100508964724995}. Best is trial 8 with value: 0.5025626988378273.

Running time: 11.1 sec
OOF RMSE: 2.46 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:25:24,637] Trial 13 finished with value: 0.45807572497881444 and parameters: {'n_estimators': 2000, 'learning_rate': 0.05207056358668714, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.6731002441919214, 'colsample_bytree': 0.7440262464790629}. Best is trial 8 with value: 0.5025626988378273.

Running time: 10.4 sec
OOF RMSE: 2.55 | R2: 0.46
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:25:37,463] Trial 14 finished with value: 0.5036614574282228 and parameters: {'n_estimators': 2000, 'learning_rate': 0.009503309824175112, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.6700280316320922, 'colsample_bytree': 0.8535538115131532}. Best is trial 14 with value: 0.5036614574282228.

Running time: 12.8 sec
OOF RMSE: 2.44 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:25:49,747] Trial 15 finished with value: 0.4291436770423841 and parameters: {'n_estimators': 2000, 'learning_rate': 0.008747999249497979, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.8860448629194663, 'colsample_bytree': 0.8724722494503773}. Best is trial 14 with value: 0.5036614574282228.

Running time: 12.3 sec
OOF RMSE: 2.62 | R2: 0.43
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:26:04,941] Trial 16 finished with value: 0.46394600447066925 and parameters: {'n_estimators': 2000, 'learning_rate': 0.016710418942419043, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.6973696236777389, 'colsample_bytree': 0.9074177931524193}. Best is trial 14 with value: 0.5036614574282228.

Running time: 15.2 sec
OOF RMSE: 2.54 | R2: 0.46
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:26:17,807] Trial 17 finished with value: 0.4717623261712951 and parameters: {'n_estimators': 2000, 'learning_rate': 0.0050895395158950495, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.802713011669909, 'colsample_bytree': 0.8505279541919974}. Best is trial 14 with value: 0.5036614574282228.

Running time: 12.9 sec
OOF RMSE: 2.52 | R2: 0.47
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:26:27,179] Trial 18 finished with value: 0.44424118224314224 and parameters: {'n_estimators': 2000, 'learning_rate': 0.056489471715373565, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.663153684976016, 'colsample_bytree': 0.7597702787366076}. Best is trial 14 with value: 0.5036614574282228.

Running time: 9.4 sec
OOF RMSE: 2.58 | R2: 0.44
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:26:30,194] Trial 19 finished with value: 0.4785051026570126 and parameters: {'n_estimators': 500, 'learning_rate': 0.009269749759372583, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.6360528752021642, 'colsample_bytree': 0.6683400869357571}. Best is trial 14 with value: 0.5036614574282228.

Running time: 3.0 sec
OOF RMSE: 2.50 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:26:40,986] Trial 20 finished with value: 0.3846521261529636 and parameters: {'n_estimators': 2000, 'learning_rate': 0.020954172044180628, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.9882993812025407, 'colsample_bytree': 0.8290537600956073}. Best is trial 14 with value: 0.5036614574282228.

Running time: 10.8 sec
OOF RMSE: 2.72 | R2: 0.38
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:26:51,964] Trial 21 finished with value: 0.4938411615212701 and parameters: {'n_estimators': 2000, 'learning_rate': 0.010344065198606207, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.6531378114691911, 'colsample_bytree': 0.786427495582005}. Best is trial 14 with value: 0.5036614574282228.

Running time: 11.0 sec
OOF RMSE: 2.47 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:27:04,059] Trial 22 finished with value: 0.4879223514388644 and parameters: {'n_estimators': 2000, 'learning_rate': 0.016444782573815674, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.6972260905607152, 'colsample_bytree': 0.9156790330882422}. Best is trial 14 with value: 0.5036614574282228.

Running time: 12.1 sec
OOF RMSE: 2.48 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:27:15,149] Trial 23 finished with value: 0.49515059407886886 and parameters: {'n_estimators': 2000, 'learning_rate': 0.007559755352233266, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.6250301530908005, 'colsample_bytree': 0.84889027873014}. Best is trial 14 with value: 0.5036614574282228.

Running time: 11.1 sec
OOF RMSE: 2.46 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:27:26,464] Trial 24 finished with value: 0.45287858375943624 and parameters: {'n_estimators': 2000, 'learning_rate': 0.007226662788402328, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.6174431819408592, 'colsample_bytree': 0.8446639642989687}. Best is trial 14 with value: 0.5036614574282228.
[I 2025-07-11 20:27:26,466] A new study created in memory with name: no-name-1108c3ce-dbab-40b6-9692-40471cbe070a

Running time: 11.3 sec
OOF RMSE: 2.56 | R2: 0.45

✅ XGB - Mejor R2: 0.50
📋 Parámetros: {'n_estimators': 2000, 'learning_rate': 0.009503309824175112, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.6700280316320922, 'colsample_bytree': 0.8535538115131532}

Buscando mejores hiperparámetros para LBM...
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 20:27:26,759] Trial 0 finished with value: 0.4908245130731901 and parameters: {'learning_rate': 0.006687187959242147, 'num_leaves': 80, 'max_depth': 8, 'min_child_samples': 20, 'subsample': 0.6874556886875797, 'colsample_bytree': 0.9825287695623381, 'n_estimators': 500}. Best is trial 0 with value: 0.4908245130731901.

Fold 5
Running time: 0.3 sec
OOF RMSE: 2.47 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:27:27,437] Trial 1 finished with value: 0.43769140512802085 and parameters: {'learning_rate': 0.0055127862052713975, 'num_leaves': 40, 'max_depth': 8, 'min_child_samples': 12, 'subsample': 0.8227992740267683, 'colsample_bytree': 0.8441184323280256, 'n_estimators': 1000}. Best is trial 0 with value: 0.4908245130731901.

Running time: 0.7 sec
OOF RMSE: 2.60 | R2: 0.44
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 20:27:27,715] Trial 2 finished with value: 0.44164804984797035 and parameters: {'learning_rate': 0.0143889036116567, 'num_leaves': 40, 'max_depth': 6, 'min_child_samples': 8, 'subsample': 0.8693429803973713, 'colsample_bytree': 0.9210292628286687, 'n_estimators': 500}. Best is trial 0 with value: 0.4908245130731901.

Fold 5
Running time: 0.3 sec
OOF RMSE: 2.59 | R2: 0.44
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:27:28,529] Trial 3 finished with value: 0.5047955106212454 and parameters: {'learning_rate': 0.021208541989412768, 'num_leaves': 60, 'max_depth': 5, 'min_child_samples': 24, 'subsample': 0.7729898373953558, 'colsample_bytree': 0.6594389848202712, 'n_estimators': 2000}. Best is trial 3 with value: 0.5047955106212454.

Running time: 0.8 sec
OOF RMSE: 2.44 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 20:27:29,152] Trial 4 finished with value: 0.440657125130404 and parameters: {'learning_rate': 0.005238656165073199, 'num_leaves': 80, 'max_depth': 8, 'min_child_samples': 12, 'subsample': 0.7515850553141841, 'colsample_bytree': 0.7220930249687527, 'n_estimators': 1000}. Best is trial 3 with value: 0.5047955106212454.

Fold 5
Running time: 0.6 sec
OOF RMSE: 2.59 | R2: 0.44
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:27:29,790] Trial 5 finished with value: 0.43778992021862473 and parameters: {'learning_rate': 0.009554924107544922, 'num_leaves': 40, 'max_depth': 7, 'min_child_samples': 8, 'subsample': 0.6750162241535758, 'colsample_bytree': 0.8264527310485433, 'n_estimators': 1000}. Best is trial 3 with value: 0.5047955106212454.

Running time: 0.6 sec
OOF RMSE: 2.60 | R2: 0.44
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:27:30,028] Trial 6 finished with value: 0.5420410296189494 and parameters: {'learning_rate': 0.0382089426806962, 'num_leaves': 80, 'max_depth': 8, 'min_child_samples': 24, 'subsample': 0.9423190624473281, 'colsample_bytree': 0.6511625366826868, 'n_estimators': 500}. Best is trial 6 with value: 0.5420410296189494.

Running time: 0.2 sec
OOF RMSE: 2.35 | R2: 0.54
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 20:27:30,298] Trial 7 finished with value: 0.4355363970230207 and parameters: {'learning_rate': 0.007906312658990972, 'num_leaves': 80, 'max_depth': 5, 'min_child_samples': 10, 'subsample': 0.9162521471204688, 'colsample_bytree': 0.7322824357967876, 'n_estimators': 500}. Best is trial 6 with value: 0.5420410296189494.

Fold 5
Running time: 0.3 sec
OOF RMSE: 2.60 | R2: 0.44
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:27:31,516] Trial 8 finished with value: 0.4168534111928166 and parameters: {'learning_rate': 0.0394002194221912, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 7, 'subsample': 0.7335874108371698, 'colsample_bytree': 0.9831350797535257, 'n_estimators': 2000}. Best is trial 6 with value: 0.5420410296189494.

Running time: 1.2 sec
OOF RMSE: 2.65 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:27:32,725] Trial 9 finished with value: 0.424942855382216 and parameters: {'learning_rate': 0.011164887122648563, 'num_leaves': 40, 'max_depth': 7, 'min_child_samples': 6, 'subsample': 0.915456859973161, 'colsample_bytree': 0.7941356916503278, 'n_estimators': 2000}. Best is trial 6 with value: 0.5420410296189494.

Running time: 1.2 sec
OOF RMSE: 2.63 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 20:27:32,997] Trial 10 finished with value: 0.45931680042667455 and parameters: {'learning_rate': 0.07932329655424068, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 19, 'subsample': 0.988128782450844, 'colsample_bytree': 0.6057561174703812, 'n_estimators': 500}. Best is trial 6 with value: 0.5420410296189494.

Fold 5
Running time: 0.3 sec
OOF RMSE: 2.55 | R2: 0.46
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:27:33,793] Trial 11 finished with value: 0.4983790022504758 and parameters: {'learning_rate': 0.026478110284167394, 'num_leaves': 60, 'max_depth': 5, 'min_child_samples': 25, 'subsample': 0.613910978228801, 'colsample_bytree': 0.6038845391277227, 'n_estimators': 2000}. Best is trial 6 with value: 0.5420410296189494.

Running time: 0.8 sec
OOF RMSE: 2.46 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 20:27:34,688] Trial 12 finished with value: 0.48199142215572466 and parameters: {'learning_rate': 0.052593810757260016, 'num_leaves': 60, 'max_depth': 6, 'min_child_samples': 24, 'subsample': 0.9968368594216249, 'colsample_bytree': 0.681699245891048, 'n_estimators': 2000}. Best is trial 6 with value: 0.5420410296189494.

Fold 5
Running time: 0.9 sec
OOF RMSE: 2.49 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:27:34,965] Trial 13 finished with value: 0.4951836094419729 and parameters: {'learning_rate': 0.020623621475192342, 'num_leaves': 60, 'max_depth': 5, 'min_child_samples': 21, 'subsample': 0.8155975441205127, 'colsample_bytree': 0.6722199141053004, 'n_estimators': 500}. Best is trial 6 with value: 0.5420410296189494.

Running time: 0.3 sec
OOF RMSE: 2.46 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 20:27:35,897] Trial 14 finished with value: 0.35655828858251903 and parameters: {'learning_rate': 0.029699787154979573, 'num_leaves': 80, 'max_depth': 6, 'min_child_samples': 17, 'subsample': 0.7623065810998089, 'colsample_bytree': 0.6582559886385465, 'n_estimators': 2000}. Best is trial 6 with value: 0.5420410296189494.

Fold 5
Running time: 0.9 sec
OOF RMSE: 2.78 | R2: 0.36
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:27:36,181] Trial 15 finished with value: 0.504007851354553 and parameters: {'learning_rate': 0.018694664355911342, 'num_leaves': 60, 'max_depth': 7, 'min_child_samples': 23, 'subsample': 0.8818874517017692, 'colsample_bytree': 0.7585874067339926, 'n_estimators': 500}. Best is trial 6 with value: 0.5420410296189494.

Running time: 0.3 sec
OOF RMSE: 2.44 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 20:27:37,009] Trial 16 finished with value: 0.33696035440648175 and parameters: {'learning_rate': 0.05322717280603447, 'num_leaves': 80, 'max_depth': 5, 'min_child_samples': 16, 'subsample': 0.8451196499398618, 'colsample_bytree': 0.646981667770861, 'n_estimators': 2000}. Best is trial 6 with value: 0.5420410296189494.

Fold 5
Running time: 0.8 sec
OOF RMSE: 2.82 | R2: 0.34
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:27:37,987] Trial 17 finished with value: 0.41074298083452543 and parameters: {'learning_rate': 0.08338296802527034, 'num_leaves': 60, 'max_depth': 8, 'min_child_samples': 22, 'subsample': 0.9520049358200581, 'colsample_bytree': 0.7112028280999051, 'n_estimators': 2000}. Best is trial 6 with value: 0.5420410296189494.

Running time: 1.0 sec
OOF RMSE: 2.66 | R2: 0.41
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 20:27:38,278] Trial 18 finished with value: 0.4666869744480743 and parameters: {'learning_rate': 0.03897334930911274, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 18, 'subsample': 0.7729001370597316, 'colsample_bytree': 0.7771551330348827, 'n_estimators': 500}. Best is trial 6 with value: 0.5420410296189494.

Fold 5
Running time: 0.3 sec
OOF RMSE: 2.53 | R2: 0.47
Fold 1
Fold 2
Fold 3

[I 2025-07-11 20:27:38,831] Trial 19 finished with value: 0.5344625682934933 and parameters: {'learning_rate': 0.014162505904092983, 'num_leaves': 80, 'max_depth': 7, 'min_child_samples': 25, 'subsample': 0.6841439293670203, 'colsample_bytree': 0.8733215589767211, 'n_estimators': 1000}. Best is trial 6 with value: 0.5420410296189494.

Fold 4
Fold 5
Running time: 0.5 sec
OOF RMSE: 2.37 | R2: 0.53
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:27:39,481] Trial 20 finished with value: 0.47304613452779354 and parameters: {'learning_rate': 0.01366866004788095, 'num_leaves': 80, 'max_depth': 8, 'min_child_samples': 14, 'subsample': 0.625008375912862, 'colsample_bytree': 0.9117304175488499, 'n_estimators': 1000}. Best is trial 6 with value: 0.5420410296189494.

Running time: 0.6 sec
OOF RMSE: 2.52 | R2: 0.47
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:27:39,974] Trial 21 finished with value: 0.5414042113670292 and parameters: {'learning_rate': 0.01784034916502372, 'num_leaves': 80, 'max_depth': 7, 'min_child_samples': 25, 'subsample': 0.6975973276175913, 'colsample_bytree': 0.8738974762670298, 'n_estimators': 1000}. Best is trial 6 with value: 0.5420410296189494.

Running time: 0.5 sec
OOF RMSE: 2.35 | R2: 0.54
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:27:40,483] Trial 22 finished with value: 0.5313062773237511 and parameters: {'learning_rate': 0.013985375976152353, 'num_leaves': 80, 'max_depth': 7, 'min_child_samples': 25, 'subsample': 0.6991632542823218, 'colsample_bytree': 0.8785392606459229, 'n_estimators': 1000}. Best is trial 6 with value: 0.5420410296189494.

Running time: 0.5 sec
OOF RMSE: 2.37 | R2: 0.53
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:27:41,051] Trial 23 finished with value: 0.48676526246720286 and parameters: {'learning_rate': 0.030093350884595672, 'num_leaves': 80, 'max_depth': 7, 'min_child_samples': 22, 'subsample': 0.6413752823702028, 'colsample_bytree': 0.8765100528898223, 'n_estimators': 1000}. Best is trial 6 with value: 0.5420410296189494.

Running time: 0.6 sec
OOF RMSE: 2.48 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 20:27:41,604] Trial 24 finished with value: 0.5050931288971103 and parameters: {'learning_rate': 0.01855393589933012, 'num_leaves': 80, 'max_depth': 8, 'min_child_samples': 21, 'subsample': 0.7127442699558705, 'colsample_bytree': 0.8341129856277565, 'n_estimators': 1000}. Best is trial 6 with value: 0.5420410296189494.
[I 2025-07-11 20:27:41,605] A new study created in memory with name: no-name-400a777c-5363-4cd2-ba5b-e1e67903fd32

Fold 5
Running time: 0.5 sec
OOF RMSE: 2.44 | R2: 0.51

✅ LBM - Mejor R2: 0.54
📋 Parámetros: {'learning_rate': 0.0382089426806962, 'num_leaves': 80, 'max_depth': 8, 'min_child_samples': 24, 'subsample': 0.9423190624473281, 'colsample_bytree': 0.6511625366826868, 'n_estimators': 500}

Buscando mejores hiperparámetros para MLP...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:27:42,476] Trial 0 finished with value: -0.1413993242246574 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.003016246991338261, 'learning_rate': 'adaptive', 'learning_rate_init': 0.009271181982578125}. Best is trial 0 with value: -0.1413993242246574.

Running time: 0.9 sec
OOF RMSE: 3.70 | R2: -0.14
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:27:43,289] Trial 1 finished with value: 0.45252458217871117 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.007220111671028815, 'learning_rate': 'constant', 'learning_rate_init': 0.0014920970651446873}. Best is trial 1 with value: 0.45252458217871117.

Running time: 0.8 sec
OOF RMSE: 2.56 | R2: 0.45
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 20:27:44,253] Trial 2 finished with value: 0.3180717572419193 and parameters: {'hidden_layer_sizes': '50', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.028376132275671515, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0013700230018424168}. Best is trial 1 with value: 0.45252458217871117.

Fold 4
Fold 5
Running time: 1.0 sec
OOF RMSE: 2.86 | R2: 0.32
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 20:27:45,535] Trial 3 finished with value: 0.3400708454247081 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.024079681833886785, 'learning_rate': 'constant', 'learning_rate_init': 0.0004738669732386548}. Best is trial 1 with value: 0.45252458217871117.

Running time: 1.3 sec
OOF RMSE: 2.82 | R2: 0.34
Fold 1
Fold 2
Fold 3

[I 2025-07-11 20:27:46,073] Trial 4 finished with value: 0.4112223408489698 and parameters: {'hidden_layer_sizes': '50', 'activation': 'relu', 'solver': 'adam', 'alpha': 3.449221071737085e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.005230911087790494}. Best is trial 1 with value: 0.45252458217871117.

Fold 4
Fold 5
Running time: 0.5 sec
OOF RMSE: 2.66 | R2: 0.41
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 20:27:46,717] Trial 5 finished with value: 0.32297482876318895 and parameters: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'sgd', 'alpha': 2.288635185185383e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.0018296257706875488}. Best is trial 1 with value: 0.45252458217871117.

Fold 4
Fold 5
Running time: 0.6 sec
OOF RMSE: 2.85 | R2: 0.32
Fold 1
Fold 2
Fold 3

[I 2025-07-11 20:27:47,851] Trial 6 finished with value: 0.430828686464341 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.07424988825547973, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0022958043669795776}. Best is trial 1 with value: 0.45252458217871117.

Fold 4
Fold 5
Running time: 1.1 sec
OOF RMSE: 2.62 | R2: 0.43
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 20:27:48,536] Trial 7 finished with value: 0.3676888782793283 and parameters: {'hidden_layer_sizes': '50', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 2.142947359938225e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.0024398941636601793}. Best is trial 1 with value: 0.45252458217871117.

Fold 4
Fold 5
Running time: 0.7 sec
OOF RMSE: 2.76 | R2: 0.37
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:27:49,482] Trial 8 finished with value: 0.560693656745402 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'tanh', 'solver': 'adam', 'alpha': 9.997221215790738e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.009289692119347494}. Best is trial 8 with value: 0.560693656745402.

Running time: 0.9 sec
OOF RMSE: 2.30 | R2: 0.56
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3
Fold 4

[I 2025-07-11 20:27:50,359] Trial 9 finished with value: 0.38607738249256907 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'relu', 'solver': 'sgd', 'alpha': 2.7474760068988246e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.0001726546626995759}. Best is trial 8 with value: 0.560693656745402.

Fold 5
Running time: 0.9 sec
OOF RMSE: 2.72 | R2: 0.39
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 20:27:51,842] Trial 10 finished with value: 0.40180885368885166 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0002929644365055633, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0004196385732900915}. Best is trial 8 with value: 0.560693656745402.

Running time: 1.5 sec
OOF RMSE: 2.68 | R2: 0.40
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

[I 2025-07-11 20:27:53,933] Trial 11 finished with value: 0.4524606816017681 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.0004170841634900568, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00520163594270721}. Best is trial 8 with value: 0.560693656745402.

Running time: 2.1 sec
OOF RMSE: 2.57 | R2: 0.45
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3
Fold 4

[I 2025-07-11 20:27:54,971] Trial 12 finished with value: 0.45119905823348727 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.003121910718099382, 'learning_rate': 'constant', 'learning_rate_init': 0.0006085140205971382}. Best is trial 8 with value: 0.560693656745402.

Fold 5
Running time: 1.0 sec
OOF RMSE: 2.57 | R2: 0.45
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 20:27:57,468] Trial 13 finished with value: 0.4052911764347641 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.00013329317684564545, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00012305198088050418}. Best is trial 8 with value: 0.560693656745402.

Fold 5
Running time: 2.5 sec
OOF RMSE: 2.67 | R2: 0.41
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3
Fold 4

[I 2025-07-11 20:27:58,319] Trial 14 finished with value: 0.48502321296713946 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.005607400633703329, 'learning_rate': 'constant', 'learning_rate_init': 0.00883491889079848}. Best is trial 8 with value: 0.560693656745402.

Fold 5
Running time: 0.8 sec
OOF RMSE: 2.49 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:27:59,320] Trial 15 finished with value: 0.5642827801907372 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0011257395702266796, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00913297115845993}. Best is trial 15 with value: 0.5642827801907372.

Running time: 1.0 sec
OOF RMSE: 2.29 | R2: 0.56
Fold 1
Fold 2
Fold 3

[I 2025-07-11 20:28:00,335] Trial 16 finished with value: 0.4544007710965703 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.00010596932025705352, 'learning_rate': 'adaptive', 'learning_rate_init': 0.004111748877255893}. Best is trial 15 with value: 0.5642827801907372.

Fold 4
Fold 5
Running time: 1.0 sec
OOF RMSE: 2.56 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:28:01,730] Trial 17 finished with value: 0.4138995271076811 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0008605806312438404, 'learning_rate': 'adaptive', 'learning_rate_init': 0.003706803740355756}. Best is trial 15 with value: 0.5642827801907372.

Running time: 1.4 sec
OOF RMSE: 2.65 | R2: 0.41
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 20:28:02,784] Trial 18 finished with value: 0.37367816404538967 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 8.156018625661035e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.008232026211593694}. Best is trial 15 with value: 0.5642827801907372.

Fold 5
Running time: 1.0 sec
OOF RMSE: 2.74 | R2: 0.37
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 20:28:04,030] Trial 19 finished with value: 0.41898091406353744 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0008234041937161925, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0008725288297656455}. Best is trial 15 with value: 0.5642827801907372.

Fold 4
Fold 5
Running time: 1.2 sec
OOF RMSE: 2.64 | R2: 0.42
Fold 1
Fold 2
Fold 3

[I 2025-07-11 20:28:04,967] Trial 20 finished with value: 0.43530208212076427 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'tanh', 'solver': 'adam', 'alpha': 1.0097952209988371e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.003166837636923758}. Best is trial 15 with value: 0.5642827801907372.

Fold 4
Fold 5
Running time: 0.9 sec
OOF RMSE: 2.60 | R2: 0.44
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3
Fold 4

[I 2025-07-11 20:28:05,900] Trial 21 finished with value: 0.5109575297502474 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.003173522427489333, 'learning_rate': 'constant', 'learning_rate_init': 0.00988020036652838}. Best is trial 15 with value: 0.5642827801907372.

Fold 5
Running time: 0.9 sec
OOF RMSE: 2.42 | R2: 0.51
Fold 1
Fold 2
Fold 3

[I 2025-07-11 20:28:06,669] Trial 22 finished with value: 0.4673541811227726 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0013420404920401656, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00605500688939607}. Best is trial 15 with value: 0.5642827801907372.

Fold 4
Fold 5
Running time: 0.8 sec
OOF RMSE: 2.53 | R2: 0.47
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

[I 2025-07-11 20:28:07,821] Trial 23 finished with value: 0.5046515589350998 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.00030325760672881907, 'learning_rate': 'constant', 'learning_rate_init': 0.009793902347711929}. Best is trial 15 with value: 0.5642827801907372.

Fold 4
Fold 5
Running time: 1.1 sec
OOF RMSE: 2.44 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 20:28:08,764] Trial 24 finished with value: 0.5808484823624944 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0018430995129781029, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0064682924707526075}. Best is trial 24 with value: 0.5808484823624944.
[I 2025-07-11 20:28:08,765] A new study created in memory with name: no-name-efc86f31-0587-4772-82d7-c56145186ad8
[I 2025-07-11 20:28:08,855] Trial 0 finished with value: 0.2464161113448703 and parameters: {'kernel': 'rbf', 'C': 0.9565325922366588, 'epsilon': 0.1041290988974354, 'gamma': 'auto'}. Best is trial 0 with value: 0.2464161113448703.

Fold 5
Running time: 0.9 sec
OOF RMSE: 2.24 | R2: 0.58

✅ MLP - Mejor R2: 0.58
📋 Parámetros: {'hidden_layer_sizes': '100_50', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0018430995129781029, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0064682924707526075}

Buscando mejores hiperparámetros para SVR...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.01 | R2: 0.25
Fold 1
Fold 2

[I 2025-07-11 20:28:08,929] Trial 1 finished with value: -2.4491507287132763 and parameters: {'kernel': 'sigmoid', 'C': 0.6016806142959912, 'epsilon': 0.11776983306722923, 'gamma': 'auto'}. Best is trial 0 with value: 0.2464161113448703.
[I 2025-07-11 20:28:09,002] Trial 2 finished with value: -11.719939832730512 and parameters: {'kernel': 'sigmoid', 'C': 1.4531741685830062, 'epsilon': 0.19365313281297986, 'gamma': 'auto'}. Best is trial 0 with value: 0.2464161113448703.
[I 2025-07-11 20:28:09,075] Trial 3 finished with value: -10.890130909809036 and parameters: {'kernel': 'sigmoid', 'C': 1.6639517333815972, 'epsilon': 0.18561742347914614, 'gamma': 'scale'}. Best is trial 0 with value: 0.2464161113448703.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 6.44 | R2: -2.45
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 12.36 | R2: -11.72
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 11.95 | R2: -10.89
Fold 1

[I 2025-07-11 20:28:09,140] Trial 4 finished with value: 0.05539499045626961 and parameters: {'kernel': 'rbf', 'C': 0.13131222298917689, 'epsilon': 0.18478859052124566, 'gamma': 'auto'}. Best is trial 0 with value: 0.2464161113448703.
[I 2025-07-11 20:28:09,213] Trial 5 finished with value: 0.19242688792320362 and parameters: {'kernel': 'rbf', 'C': 0.5638952292232543, 'epsilon': 0.1357419835086897, 'gamma': 'scale'}. Best is trial 0 with value: 0.2464161113448703.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.37 | R2: 0.06
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.12 | R2: 0.19
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:28:09,297] Trial 6 finished with value: -107.7616307569394 and parameters: {'kernel': 'sigmoid', 'C': 6.918939467270979, 'epsilon': 0.09270639194028382, 'gamma': 'scale'}. Best is trial 0 with value: 0.2464161113448703.
[I 2025-07-11 20:28:09,372] Trial 7 finished with value: 0.31678834295193303 and parameters: {'kernel': 'rbf', 'C': 2.1307254620905156, 'epsilon': 0.10001073216243567, 'gamma': 'auto'}. Best is trial 7 with value: 0.31678834295193303.
[I 2025-07-11 20:28:09,458] Trial 8 finished with value: 0.39616633236871235 and parameters: {'kernel': 'rbf', 'C': 4.695752143686603, 'epsilon': 0.022323601766179174, 'gamma': 'scale'}. Best is trial 8 with value: 0.39616633236871235.

Running time: 0.1 sec
OOF RMSE: 36.15 | R2: -107.76
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.87 | R2: 0.32
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.69 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 20:28:09,520] Trial 9 finished with value: 0.13174887554742498 and parameters: {'kernel': 'rbf', 'C': 0.3266958123971637, 'epsilon': 0.1224749460758078, 'gamma': 'auto'}. Best is trial 8 with value: 0.39616633236871235.
[I 2025-07-11 20:28:09,604] Trial 10 finished with value: 0.4153090029000679 and parameters: {'kernel': 'rbf', 'C': 6.73938366259557, 'epsilon': 0.016017992118853318, 'gamma': 'scale'}. Best is trial 10 with value: 0.4153090029000679.
[I 2025-07-11 20:28:09,691] Trial 11 finished with value: 0.4061275988376415 and parameters: {'kernel': 'rbf', 'C': 9.874036618187517, 'epsilon': 0.01054226699055347, 'gamma': 'scale'}. Best is trial 10 with value: 0.4153090029000679.

Fold 5
Running time: 0.1 sec
OOF RMSE: 3.23 | R2: 0.13
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.65 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.67 | R2: 0.41
Fold 1

[I 2025-07-11 20:28:09,776] Trial 12 finished with value: 0.4087761231880025 and parameters: {'kernel': 'rbf', 'C': 9.303237031094998, 'epsilon': 0.01051072906393417, 'gamma': 'scale'}. Best is trial 10 with value: 0.4153090029000679.
[I 2025-07-11 20:28:09,859] Trial 13 finished with value: 0.3747737454759309 and parameters: {'kernel': 'rbf', 'C': 3.806066402444752, 'epsilon': 0.055786180417379067, 'gamma': 'scale'}. Best is trial 10 with value: 0.4153090029000679.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.67 | R2: 0.41
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.74 | R2: 0.37
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 20:28:09,938] Trial 14 finished with value: 0.37222772430529927 and parameters: {'kernel': 'rbf', 'C': 3.701874615229108, 'epsilon': 0.0419548355035657, 'gamma': 'scale'}. Best is trial 10 with value: 0.4153090029000679.
[I 2025-07-11 20:28:10,021] Trial 15 finished with value: 0.40946920652693686 and parameters: {'kernel': 'rbf', 'C': 8.732119597910392, 'epsilon': 0.06519958161541892, 'gamma': 'scale'}. Best is trial 10 with value: 0.4153090029000679.
[I 2025-07-11 20:28:10,103] Trial 16 finished with value: 0.3457282928479035 and parameters: {'kernel': 'rbf', 'C': 2.955906225449862, 'epsilon': 0.06359089329657786, 'gamma': 'scale'}. Best is trial 10 with value: 0.4153090029000679.

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.75 | R2: 0.37
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.66 | R2: 0.41
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.80 | R2: 0.35
Fold 1

[I 2025-07-11 20:28:10,182] Trial 17 finished with value: 0.41102886442146214 and parameters: {'kernel': 'rbf', 'C': 6.309702723163438, 'epsilon': 0.07630744115679225, 'gamma': 'scale'}. Best is trial 10 with value: 0.4153090029000679.
[I 2025-07-11 20:28:10,263] Trial 18 finished with value: -88.26030973178933 and parameters: {'kernel': 'sigmoid', 'C': 5.121604788787275, 'epsilon': 0.16098251979353914, 'gamma': 'scale'}. Best is trial 10 with value: 0.4153090029000679.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.66 | R2: 0.41
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 32.75 | R2: -88.26
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:28:10,340] Trial 19 finished with value: 0.05163318030442987 and parameters: {'kernel': 'rbf', 'C': 0.1323151554407373, 'epsilon': 0.08427240911383434, 'gamma': 'scale'}. Best is trial 10 with value: 0.4153090029000679.
[I 2025-07-11 20:28:10,420] Trial 20 finished with value: 0.34307241035191727 and parameters: {'kernel': 'rbf', 'C': 2.8388174090477243, 'epsilon': 0.03739879491300427, 'gamma': 'scale'}. Best is trial 10 with value: 0.4153090029000679.
[I 2025-07-11 20:28:10,511] Trial 21 finished with value: 0.40554424754241347 and parameters: {'kernel': 'rbf', 'C': 5.53183802784661, 'epsilon': 0.07671870126289647, 'gamma': 'scale'}. Best is trial 10 with value: 0.4153090029000679.

Running time: 0.1 sec
OOF RMSE: 3.38 | R2: 0.05
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.81 | R2: 0.34
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.67 | R2: 0.41
Fold 1
Fold 2

[I 2025-07-11 20:28:10,591] Trial 22 finished with value: 0.41531190177092336 and parameters: {'kernel': 'rbf', 'C': 7.338251207738275, 'epsilon': 0.06680019822322752, 'gamma': 'scale'}. Best is trial 22 with value: 0.41531190177092336.
[I 2025-07-11 20:28:10,676] Trial 23 finished with value: 0.41213167471219425 and parameters: {'kernel': 'rbf', 'C': 6.358236482340002, 'epsilon': 0.04256463819748761, 'gamma': 'scale'}. Best is trial 22 with value: 0.41531190177092336.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.65 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.66 | R2: 0.41
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:28:10,754] Trial 24 finished with value: 0.3312760682666598 and parameters: {'kernel': 'rbf', 'C': 2.442372184276603, 'epsilon': 0.035726452604838685, 'gamma': 'scale'}. Best is trial 22 with value: 0.41531190177092336.
[I 2025-07-11 20:28:10,755] A new study created in memory with name: no-name-273d5490-2ab3-4105-914e-9ac04a16b731
[I 2025-07-11 20:28:10,813] Trial 0 finished with value: 0.5166890800465003 and parameters: {'n_neighbors': 9, 'weights': 'uniform', 'leaf_size': 40}. Best is trial 0 with value: 0.5166890800465003.
[I 2025-07-11 20:28:10,875] Trial 1 finished with value: 0.5657882614690097 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'leaf_size': 20}. Best is trial 1 with value: 0.5657882614690097.
[I 2025-07-11 20:28:10,928] Trial 2 finished with value: 0.4828583156035233 and parameters: {'n_neighbors': 5, 'weights': 'uniform', 'leaf_size': 22}. Best is trial 1 with value: 0.5657882614690097.

Running time: 0.1 sec
OOF RMSE: 2.83 | R2: 0.33

✅ SVR - Mejor R2: 0.42
📋 Parámetros: {'kernel': 'rbf', 'C': 7.338251207738275, 'epsilon': 0.06680019822322752, 'gamma': 'scale'}

Buscando mejores hiperparámetros para KNN...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.41 | R2: 0.52
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.28 | R2: 0.57
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.0 sec
OOF RMSE: 2.49 | R2: 0.48
Fold 1
Fold 2
Fold 3

[I 2025-07-11 20:28:10,987] Trial 3 finished with value: 0.4610747874407968 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'leaf_size': 26}. Best is trial 1 with value: 0.5657882614690097.
[I 2025-07-11 20:28:11,049] Trial 4 finished with value: 0.5118398553319365 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'leaf_size': 22}. Best is trial 1 with value: 0.5657882614690097.
[I 2025-07-11 20:28:11,111] Trial 5 finished with value: 0.48367050104966003 and parameters: {'n_neighbors': 12, 'weights': 'uniform', 'leaf_size': 28}. Best is trial 1 with value: 0.5657882614690097.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.54 | R2: 0.46
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.42 | R2: 0.51
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.49 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:28:11,175] Trial 6 finished with value: 0.5166890800465003 and parameters: {'n_neighbors': 9, 'weights': 'uniform', 'leaf_size': 40}. Best is trial 1 with value: 0.5657882614690097.
[I 2025-07-11 20:28:11,233] Trial 7 finished with value: 0.5579848341616995 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'leaf_size': 37}. Best is trial 1 with value: 0.5657882614690097.
[I 2025-07-11 20:28:11,322] Trial 8 finished with value: 0.48367050104966003 and parameters: {'n_neighbors': 12, 'weights': 'uniform', 'leaf_size': 21}. Best is trial 1 with value: 0.5657882614690097.

Running time: 0.1 sec
OOF RMSE: 2.41 | R2: 0.52
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.30 | R2: 0.56
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.49 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:28:11,383] Trial 9 finished with value: 0.5118398553319365 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'leaf_size': 37}. Best is trial 1 with value: 0.5657882614690097.
[I 2025-07-11 20:28:11,449] Trial 10 finished with value: 0.5201171273773715 and parameters: {'n_neighbors': 15, 'weights': 'distance', 'leaf_size': 12}. Best is trial 1 with value: 0.5657882614690097.
[I 2025-07-11 20:28:11,518] Trial 11 finished with value: 0.5579848341616995 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'leaf_size': 32}. Best is trial 1 with value: 0.5657882614690097.
[I 2025-07-11 20:28:11,579] Trial 12 finished with value: 0.5579848341616995 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'leaf_size': 14}. Best is trial 1 with value: 0.5657882614690097.

Running time: 0.1 sec
OOF RMSE: 2.42 | R2: 0.51
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.40 | R2: 0.52
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.30 | R2: 0.56
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.30 | R2: 0.56

[I 2025-07-11 20:28:11,650] Trial 13 finished with value: 0.5579848341616995 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'leaf_size': 17}. Best is trial 1 with value: 0.5657882614690097.
[I 2025-07-11 20:28:11,721] Trial 14 finished with value: 0.4908951485316668 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 31}. Best is trial 1 with value: 0.5657882614690097.
[I 2025-07-11 20:28:11,793] Trial 15 finished with value: 0.5583934329206188 and parameters: {'n_neighbors': 11, 'weights': 'distance', 'leaf_size': 18}. Best is trial 1 with value: 0.5657882614690097.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.30 | R2: 0.56
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.47 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.30 | R2: 0.56

[I 2025-07-11 20:28:11,861] Trial 16 finished with value: 0.5411136491947446 and parameters: {'n_neighbors': 12, 'weights': 'distance', 'leaf_size': 17}. Best is trial 1 with value: 0.5657882614690097.
[I 2025-07-11 20:28:11,936] Trial 17 finished with value: 0.5583934329206188 and parameters: {'n_neighbors': 11, 'weights': 'distance', 'leaf_size': 10}. Best is trial 1 with value: 0.5657882614690097.
[I 2025-07-11 20:28:12,005] Trial 18 finished with value: 0.5201171273773715 and parameters: {'n_neighbors': 15, 'weights': 'distance', 'leaf_size': 18}. Best is trial 1 with value: 0.5657882614690097.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.35 | R2: 0.54
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.30 | R2: 0.56
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.40 | R2: 0.52

[I 2025-07-11 20:28:12,072] Trial 19 finished with value: 0.5496781983931303 and parameters: {'n_neighbors': 10, 'weights': 'distance', 'leaf_size': 15}. Best is trial 1 with value: 0.5657882614690097.
[I 2025-07-11 20:28:12,148] Trial 20 finished with value: 0.5317322509280931 and parameters: {'n_neighbors': 13, 'weights': 'distance', 'leaf_size': 20}. Best is trial 1 with value: 0.5657882614690097.
[I 2025-07-11 20:28:12,216] Trial 21 finished with value: 0.5496781983931303 and parameters: {'n_neighbors': 10, 'weights': 'distance', 'leaf_size': 13}. Best is trial 1 with value: 0.5657882614690097.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.33 | R2: 0.55
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.37 | R2: 0.53
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.33 | R2: 0.55

[I 2025-07-11 20:28:12,286] Trial 22 finished with value: 0.5496781983931303 and parameters: {'n_neighbors': 10, 'weights': 'distance', 'leaf_size': 10}. Best is trial 1 with value: 0.5657882614690097.
[I 2025-07-11 20:28:12,360] Trial 23 finished with value: 0.5317322509280931 and parameters: {'n_neighbors': 13, 'weights': 'distance', 'leaf_size': 10}. Best is trial 1 with value: 0.5657882614690097.
[I 2025-07-11 20:28:12,429] Trial 24 finished with value: 0.5583934329206188 and parameters: {'n_neighbors': 11, 'weights': 'distance', 'leaf_size': 24}. Best is trial 1 with value: 0.5657882614690097.
[I 2025-07-11 20:28:12,430] A new study created in memory with name: no-name-db1bf698-a4c2-4757-8339-6d9a472cbe9e

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.33 | R2: 0.55
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.37 | R2: 0.53
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.30 | R2: 0.56

✅ KNN - Mejor R2: 0.57
📋 Parámetros: {'n_neighbors': 6, 'weights': 'distance', 'leaf_size': 20}

Buscando mejores hiperparámetros para LR...

[I 2025-07-11 20:28:12,493] Trial 0 finished with value: 0.20944446265145122 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: 0.20944446265145122.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.08 | R2: 0.21
Fold 1
Fold 2
Fold 3

[I 2025-07-11 20:28:12,694] Trial 1 finished with value: -1.274171143068724 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 0 with value: 0.20944446265145122.
[I 2025-07-11 20:28:12,777] Trial 2 finished with value: -1.274171143068724 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 0 with value: 0.20944446265145122.

Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 5.23 | R2: -1.27
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 5.23 | R2: -1.27
Fold 1
Fold 2
Fold 3

[I 2025-07-11 20:28:12,908] Trial 3 finished with value: -1.274171143105176 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 0 with value: 0.20944446265145122.
[I 2025-07-11 20:28:13,011] Trial 4 finished with value: 0.21091433610526655 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 4 with value: 0.21091433610526655.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 5.23 | R2: -1.27
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.08 | R2: 0.21
Fold 1
Fold 2

[I 2025-07-11 20:28:13,125] Trial 5 finished with value: -1.274171143068724 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 4 with value: 0.21091433610526655.
[I 2025-07-11 20:28:13,227] Trial 6 finished with value: -1.274171143068724 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 4 with value: 0.21091433610526655.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 5.23 | R2: -1.27
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 5.23 | R2: -1.27
Fold 1
Fold 2
Fold 3

[I 2025-07-11 20:28:13,306] Trial 7 finished with value: -1.274171143105176 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 4 with value: 0.21091433610526655.
[I 2025-07-11 20:28:13,380] Trial 8 finished with value: 0.21091433610526655 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 4 with value: 0.21091433610526655.
[I 2025-07-11 20:28:13,442] Trial 9 finished with value: 0.20944446265145122 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 4 with value: 0.21091433610526655.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 5.23 | R2: -1.27
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.08 | R2: 0.21
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.08 | R2: 0.21
Fold 1
Fold 2
Fold 3

[I 2025-07-11 20:28:13,505] Trial 10 finished with value: 0.21091433610526655 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 4 with value: 0.21091433610526655.
[I 2025-07-11 20:28:13,565] Trial 11 finished with value: 0.21091433610526655 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 4 with value: 0.21091433610526655.
[I 2025-07-11 20:28:13,624] Trial 12 finished with value: 0.21091433610526655 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 4 with value: 0.21091433610526655.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.08 | R2: 0.21
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.08 | R2: 0.21
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.08 | R2: 0.21
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 20:28:13,703] Trial 13 finished with value: 0.21091433610526655 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 4 with value: 0.21091433610526655.
[I 2025-07-11 20:28:13,764] Trial 14 finished with value: 0.21091433610526655 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 4 with value: 0.21091433610526655.
[I 2025-07-11 20:28:13,828] Trial 15 finished with value: 0.21091433610526655 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 4 with value: 0.21091433610526655.
[I 2025-07-11 20:28:13,891] Trial 16 finished with value: 0.21091433610526655 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 4 with value: 0.21091433610526655.

Fold 5
Running time: 0.1 sec
OOF RMSE: 3.08 | R2: 0.21
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.08 | R2: 0.21
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.08 | R2: 0.21
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.08 | R2: 0.21

[I 2025-07-11 20:28:13,953] Trial 17 finished with value: 0.21091433610526655 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 4 with value: 0.21091433610526655.
[I 2025-07-11 20:28:14,017] Trial 18 finished with value: 0.21091433610526655 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 4 with value: 0.21091433610526655.
[I 2025-07-11 20:28:14,080] Trial 19 finished with value: 0.21091433610526655 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 4 with value: 0.21091433610526655.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.08 | R2: 0.21
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.08 | R2: 0.21
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.08 | R2: 0.21
Fold 1
Fold 2

[I 2025-07-11 20:28:14,140] Trial 20 finished with value: 0.21091433610526655 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 4 with value: 0.21091433610526655.
[I 2025-07-11 20:28:14,200] Trial 21 finished with value: 0.21091433610526655 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 4 with value: 0.21091433610526655.
[I 2025-07-11 20:28:14,263] Trial 22 finished with value: 0.21091433610526655 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 4 with value: 0.21091433610526655.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.08 | R2: 0.21
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.08 | R2: 0.21
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.08 | R2: 0.21
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 20:28:14,325] Trial 23 finished with value: 0.21091433610526655 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 4 with value: 0.21091433610526655.
[I 2025-07-11 20:28:14,386] Trial 24 finished with value: 0.21091433610526655 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 4 with value: 0.21091433610526655.
[I 2025-07-11 20:28:14,387] A new study created in memory with name: no-name-61d4eea6-c7c0-4d10-bd44-7cc37893c5d4

Fold 5
Running time: 0.1 sec
OOF RMSE: 3.08 | R2: 0.21
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.08 | R2: 0.21

✅ LR - Mejor R2: 0.21
📋 Parámetros: {'fit_intercept': False, 'positive': True}

Buscando mejores hiperparámetros para RF...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:28:16,098] Trial 0 finished with value: 0.05494221870813987 and parameters: {'n_estimators': 100, 'max_depth': 5, 'min_samples_split': 5, 'min_samples_leaf': 4, 'bootstrap': False}. Best is trial 0 with value: 0.05494221870813987.

Running time: 1.7 sec
OOF RMSE: 3.37 | R2: 0.05
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:28:20,462] Trial 1 finished with value: 0.4062640885827373 and parameters: {'n_estimators': 300, 'max_depth': 11, 'min_samples_split': 6, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 1 with value: 0.4062640885827373.

Running time: 4.4 sec
OOF RMSE: 2.67 | R2: 0.41
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:28:27,343] Trial 2 finished with value: 0.05746478055765669 and parameters: {'n_estimators': 300, 'max_depth': 12, 'min_samples_split': 2, 'min_samples_leaf': 4, 'bootstrap': False}. Best is trial 1 with value: 0.4062640885827373.

Running time: 6.9 sec
OOF RMSE: 3.37 | R2: 0.06
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:28:29,911] Trial 3 finished with value: 0.11872389478202905 and parameters: {'n_estimators': 100, 'max_depth': 10, 'min_samples_split': 3, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 1 with value: 0.4062640885827373.

Running time: 2.6 sec
OOF RMSE: 3.25 | R2: 0.12
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:28:32,347] Trial 4 finished with value: 0.1174854273764282 and parameters: {'n_estimators': 100, 'max_depth': 14, 'min_samples_split': 6, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 1 with value: 0.4062640885827373.

Running time: 2.4 sec
OOF RMSE: 3.26 | R2: 0.12
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:28:36,955] Trial 5 finished with value: 0.41422663995433817 and parameters: {'n_estimators': 300, 'max_depth': 11, 'min_samples_split': 8, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 5 with value: 0.41422663995433817.

Running time: 4.6 sec
OOF RMSE: 2.65 | R2: 0.41
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:28:39,120] Trial 6 finished with value: 0.11470586255925297 and parameters: {'n_estimators': 100, 'max_depth': 14, 'min_samples_split': 7, 'min_samples_leaf': 5, 'bootstrap': False}. Best is trial 5 with value: 0.41422663995433817.

Running time: 2.2 sec
OOF RMSE: 3.26 | R2: 0.11
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:28:44,628] Trial 7 finished with value: 0.11699251717562342 and parameters: {'n_estimators': 300, 'max_depth': 6, 'min_samples_split': 7, 'min_samples_leaf': 5, 'bootstrap': False}. Best is trial 5 with value: 0.41422663995433817.

Running time: 5.5 sec
OOF RMSE: 3.26 | R2: 0.12
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:28:46,751] Trial 8 finished with value: 0.14700010994507628 and parameters: {'n_estimators': 100, 'max_depth': 7, 'min_samples_split': 9, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 5 with value: 0.41422663995433817.

Running time: 2.1 sec
OOF RMSE: 3.20 | R2: 0.15
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:28:49,341] Trial 9 finished with value: 0.11069380677270879 and parameters: {'n_estimators': 100, 'max_depth': 12, 'min_samples_split': 6, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 5 with value: 0.41422663995433817.

Running time: 2.6 sec
OOF RMSE: 3.27 | R2: 0.11
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:28:57,454] Trial 10 finished with value: 0.44754347300534625 and parameters: {'n_estimators': 500, 'max_depth': 9, 'min_samples_split': 10, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 10 with value: 0.44754347300534625.

Running time: 8.1 sec
OOF RMSE: 2.58 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:29:05,549] Trial 11 finished with value: 0.44754347300534625 and parameters: {'n_estimators': 500, 'max_depth': 9, 'min_samples_split': 10, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 10 with value: 0.44754347300534625.

Running time: 8.1 sec
OOF RMSE: 2.58 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:29:13,657] Trial 12 finished with value: 0.4474460161746885 and parameters: {'n_estimators': 500, 'max_depth': 8, 'min_samples_split': 10, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 10 with value: 0.44754347300534625.

Running time: 8.1 sec
OOF RMSE: 2.58 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:29:21,779] Trial 13 finished with value: 0.44754347300534625 and parameters: {'n_estimators': 500, 'max_depth': 9, 'min_samples_split': 10, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 10 with value: 0.44754347300534625.

Running time: 8.1 sec
OOF RMSE: 2.58 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:29:29,680] Trial 14 finished with value: 0.4480525927499929 and parameters: {'n_estimators': 500, 'max_depth': 8, 'min_samples_split': 9, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 14 with value: 0.4480525927499929.

Running time: 7.9 sec
OOF RMSE: 2.58 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:29:37,235] Trial 15 finished with value: 0.4566528778108697 and parameters: {'n_estimators': 500, 'max_depth': 7, 'min_samples_split': 8, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 15 with value: 0.4566528778108697.

Running time: 7.5 sec
OOF RMSE: 2.56 | R2: 0.46
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:29:44,573] Trial 16 finished with value: 0.4507660977126242 and parameters: {'n_estimators': 500, 'max_depth': 7, 'min_samples_split': 8, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 15 with value: 0.4566528778108697.

Running time: 7.3 sec
OOF RMSE: 2.57 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:29:50,830] Trial 17 finished with value: 0.4486333818340952 and parameters: {'n_estimators': 500, 'max_depth': 5, 'min_samples_split': 8, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 15 with value: 0.4566528778108697.

Running time: 6.3 sec
OOF RMSE: 2.57 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:29:58,420] Trial 18 finished with value: 0.4485231757123618 and parameters: {'n_estimators': 500, 'max_depth': 7, 'min_samples_split': 4, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 15 with value: 0.4566528778108697.

Running time: 7.6 sec
OOF RMSE: 2.57 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:30:05,121] Trial 19 finished with value: 0.4078863242740708 and parameters: {'n_estimators': 500, 'max_depth': 6, 'min_samples_split': 8, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 15 with value: 0.4566528778108697.

Running time: 6.7 sec
OOF RMSE: 2.67 | R2: 0.41
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:30:12,024] Trial 20 finished with value: 0.44976359011049694 and parameters: {'n_estimators': 500, 'max_depth': 6, 'min_samples_split': 7, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 15 with value: 0.4566528778108697.

Running time: 6.9 sec
OOF RMSE: 2.57 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:30:19,460] Trial 21 finished with value: 0.45136158243215996 and parameters: {'n_estimators': 500, 'max_depth': 7, 'min_samples_split': 7, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 15 with value: 0.4566528778108697.

Running time: 7.4 sec
OOF RMSE: 2.57 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:30:26,611] Trial 22 finished with value: 0.4129963362251853 and parameters: {'n_estimators': 500, 'max_depth': 7, 'min_samples_split': 8, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 15 with value: 0.4566528778108697.

Running time: 7.1 sec
OOF RMSE: 2.66 | R2: 0.41
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:30:34,504] Trial 23 finished with value: 0.4480525927499929 and parameters: {'n_estimators': 500, 'max_depth': 8, 'min_samples_split': 9, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 15 with value: 0.4566528778108697.

Running time: 7.9 sec
OOF RMSE: 2.58 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:30:40,765] Trial 24 finished with value: 0.446327787821893 and parameters: {'n_estimators': 500, 'max_depth': 5, 'min_samples_split': 7, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 15 with value: 0.4566528778108697.
[I 2025-07-11 20:30:40,767] A new study created in memory with name: no-name-156e23bd-1fce-481b-8130-bb31d76a0dc9

Running time: 6.3 sec
OOF RMSE: 2.58 | R2: 0.45

✅ RF - Mejor R2: 0.46
📋 Parámetros: {'n_estimators': 500, 'max_depth': 7, 'min_samples_split': 8, 'min_samples_leaf': 1, 'bootstrap': True}

Buscando mejores hiperparámetros para CAT...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:30:47,376] Trial 0 finished with value: 0.45551810903802337 and parameters: {'iterations': 1000, 'learning_rate': 0.03785563880094921, 'depth': 6, 'l2_leaf_reg': 9.274797776215715}. Best is trial 0 with value: 0.45551810903802337.

Running time: 6.6 sec
OOF RMSE: 2.56 | R2: 0.46
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:30:50,470] Trial 1 finished with value: 0.45670908294292134 and parameters: {'iterations': 500, 'learning_rate': 0.0709969869224648, 'depth': 6, 'l2_leaf_reg': 8.046790776508876}. Best is trial 1 with value: 0.45670908294292134.

Running time: 3.1 sec
OOF RMSE: 2.56 | R2: 0.46
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:32:12,422] Trial 2 finished with value: 0.44865013629958705 and parameters: {'iterations': 1000, 'learning_rate': 0.02021908584962389, 'depth': 9, 'l2_leaf_reg': 4.096437521178094}. Best is trial 1 with value: 0.45670908294292134.

Running time: 81.9 sec
OOF RMSE: 2.57 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:32:20,803] Trial 3 finished with value: 0.4834956752146531 and parameters: {'iterations': 2000, 'learning_rate': 0.058697186649957614, 'depth': 5, 'l2_leaf_reg': 8.657941772249352}. Best is trial 3 with value: 0.4834956752146531.

Running time: 8.4 sec
OOF RMSE: 2.49 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:32:24,637] Trial 4 finished with value: 0.501708035729969 and parameters: {'iterations': 1000, 'learning_rate': 0.03727874192525679, 'depth': 5, 'l2_leaf_reg': 7.0291684889440065}. Best is trial 4 with value: 0.501708035729969.

Running time: 3.8 sec
OOF RMSE: 2.45 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:32:42,702] Trial 5 finished with value: 0.4183454419900602 and parameters: {'iterations': 500, 'learning_rate': 0.0385917644470119, 'depth': 8, 'l2_leaf_reg': 9.28056373895006}. Best is trial 4 with value: 0.501708035729969.

Running time: 18.1 sec
OOF RMSE: 2.64 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:33:08,811] Trial 6 finished with value: 0.4783865923196684 and parameters: {'iterations': 2000, 'learning_rate': 0.012928279179226173, 'depth': 7, 'l2_leaf_reg': 5.2873378205892765}. Best is trial 4 with value: 0.501708035729969.

Running time: 26.1 sec
OOF RMSE: 2.50 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:33:14,764] Trial 7 finished with value: 0.5374116839590473 and parameters: {'iterations': 2000, 'learning_rate': 0.019554934973842024, 'depth': 4, 'l2_leaf_reg': 4.755951674701013}. Best is trial 7 with value: 0.5374116839590473.

Running time: 5.9 sec
OOF RMSE: 2.36 | R2: 0.54
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:33:27,317] Trial 8 finished with value: 0.45343313277449016 and parameters: {'iterations': 2000, 'learning_rate': 0.08146776306318768, 'depth': 6, 'l2_leaf_reg': 9.766298644467746}. Best is trial 7 with value: 0.5374116839590473.

Running time: 12.5 sec
OOF RMSE: 2.56 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:34:37,097] Trial 9 finished with value: 0.4543553209304677 and parameters: {'iterations': 2000, 'learning_rate': 0.013654279242926436, 'depth': 8, 'l2_leaf_reg': 7.912672770351889}. Best is trial 7 with value: 0.5374116839590473.

Running time: 69.8 sec
OOF RMSE: 2.56 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:34:42,961] Trial 10 finished with value: 0.5293529791144598 and parameters: {'iterations': 2000, 'learning_rate': 0.02361918669566936, 'depth': 4, 'l2_leaf_reg': 1.3347428628419076}. Best is trial 7 with value: 0.5374116839590473.

Running time: 5.9 sec
OOF RMSE: 2.38 | R2: 0.53
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:34:47,963] Trial 11 finished with value: 0.516896784870086 and parameters: {'iterations': 2000, 'learning_rate': 0.02130947336402567, 'depth': 4, 'l2_leaf_reg': 1.0659291445067285}. Best is trial 7 with value: 0.5374116839590473.

Running time: 5.0 sec
OOF RMSE: 2.41 | R2: 0.52
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:34:54,028] Trial 12 finished with value: 0.5193763477754214 and parameters: {'iterations': 2000, 'learning_rate': 0.021482145303616456, 'depth': 4, 'l2_leaf_reg': 1.5016298669394308}. Best is trial 7 with value: 0.5374116839590473.

Running time: 6.1 sec
OOF RMSE: 2.40 | R2: 0.52
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:35:00,074] Trial 13 finished with value: 0.5158703933269737 and parameters: {'iterations': 2000, 'learning_rate': 0.024918953658150476, 'depth': 4, 'l2_leaf_reg': 3.035994228397983}. Best is trial 7 with value: 0.5374116839590473.

Running time: 6.0 sec
OOF RMSE: 2.41 | R2: 0.52
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:39:41,398] Trial 14 finished with value: 0.47870712603493104 and parameters: {'iterations': 2000, 'learning_rate': 0.010085199910548737, 'depth': 10, 'l2_leaf_reg': 2.458085210761258}. Best is trial 7 with value: 0.5374116839590473.

Running time: 281.3 sec
OOF RMSE: 2.50 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:39:43,825] Trial 15 finished with value: 0.49370717440948264 and parameters: {'iterations': 500, 'learning_rate': 0.016052376740387047, 'depth': 5, 'l2_leaf_reg': 5.665956110940764}. Best is trial 7 with value: 0.5374116839590473.

Running time: 2.4 sec
OOF RMSE: 2.47 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:39:49,468] Trial 16 finished with value: 0.5215127852095947 and parameters: {'iterations': 2000, 'learning_rate': 0.029510117605425077, 'depth': 4, 'l2_leaf_reg': 4.301060333177784}. Best is trial 7 with value: 0.5374116839590473.

Running time: 5.6 sec
OOF RMSE: 2.40 | R2: 0.52
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:39:58,038] Trial 17 finished with value: 0.5029735056389701 and parameters: {'iterations': 2000, 'learning_rate': 0.05084822229620201, 'depth': 5, 'l2_leaf_reg': 6.514682193030167}. Best is trial 7 with value: 0.5374116839590473.

Running time: 8.6 sec
OOF RMSE: 2.44 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:40:04,736] Trial 18 finished with value: 0.49640848265184323 and parameters: {'iterations': 500, 'learning_rate': 0.017201068483422132, 'depth': 7, 'l2_leaf_reg': 2.6460581861942774}. Best is trial 7 with value: 0.5374116839590473.

Running time: 6.7 sec
OOF RMSE: 2.46 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:40:11,288] Trial 19 finished with value: 0.4903355920225865 and parameters: {'iterations': 1000, 'learning_rate': 0.027622008440835465, 'depth': 6, 'l2_leaf_reg': 3.7759172723212697}. Best is trial 7 with value: 0.5374116839590473.

Running time: 6.5 sec
OOF RMSE: 2.47 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:40:16,822] Trial 20 finished with value: 0.5114565609437518 and parameters: {'iterations': 2000, 'learning_rate': 0.010048911514099043, 'depth': 4, 'l2_leaf_reg': 1.8814626059119175}. Best is trial 7 with value: 0.5374116839590473.

Running time: 5.5 sec
OOF RMSE: 2.42 | R2: 0.51
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:40:22,897] Trial 21 finished with value: 0.5271158420132966 and parameters: {'iterations': 2000, 'learning_rate': 0.030030089573170094, 'depth': 4, 'l2_leaf_reg': 4.520964468873298}. Best is trial 7 with value: 0.5374116839590473.

Running time: 6.1 sec
OOF RMSE: 2.38 | R2: 0.53
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:40:31,122] Trial 22 finished with value: 0.5153823049335998 and parameters: {'iterations': 2000, 'learning_rate': 0.03327968881587571, 'depth': 5, 'l2_leaf_reg': 5.371629027737135}. Best is trial 7 with value: 0.5374116839590473.

Running time: 8.2 sec
OOF RMSE: 2.41 | R2: 0.52
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:40:36,555] Trial 23 finished with value: 0.5221933536077672 and parameters: {'iterations': 2000, 'learning_rate': 0.046420963240205566, 'depth': 4, 'l2_leaf_reg': 4.625912925924885}. Best is trial 7 with value: 0.5374116839590473.

Running time: 5.4 sec
OOF RMSE: 2.40 | R2: 0.52
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:40:44,818] Trial 24 finished with value: 0.5162189711946602 and parameters: {'iterations': 2000, 'learning_rate': 0.026794518135070434, 'depth': 5, 'l2_leaf_reg': 6.317686149272885}. Best is trial 7 with value: 0.5374116839590473.
[I 2025-07-11 20:40:44,820] A new study created in memory with name: no-name-e1f09d0b-44b2-485b-9d8d-907e01caad52
[I 2025-07-11 20:40:44,935] Trial 0 finished with value: 0.3808955206229805 and parameters: {'alpha': 0.03173034484794672, 'l1_ratio': 0.8027355247366729}. Best is trial 0 with value: 0.3808955206229805.
[I 2025-07-11 20:40:45,014] Trial 1 finished with value: 0.4214917172453514 and parameters: {'alpha': 1.5556514071893708, 'l1_ratio': 0.11748492868818072}. Best is trial 1 with value: 0.4214917172453514.

Running time: 8.3 sec
OOF RMSE: 2.41 | R2: 0.52

✅ CAT - Mejor R2: 0.54
📋 Parámetros: {'iterations': 2000, 'learning_rate': 0.019554934973842024, 'depth': 4, 'l2_leaf_reg': 4.755951674701013}

Buscando mejores hiperparámetros para EN...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.73 | R2: 0.38
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.64 | R2: 0.42

[I 2025-07-11 20:40:45,099] Trial 2 finished with value: 0.418628193754388 and parameters: {'alpha': 0.06684129081734923, 'l1_ratio': 0.6179339481152111}. Best is trial 1 with value: 0.4214917172453514.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.366e+01, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.165e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.719e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.595e+01, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.214e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 20:40:45,213] Trial 3 finished with value: -0.03378573799287854 and parameters: {'alpha': 0.0038373210304698613, 'l1_ratio': 0.6146037465299408}. Best is trial 1 with value: 0.4214917172453514.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.64 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.52 | R2: -0.03
Fold 1

[I 2025-07-11 20:40:45,297] Trial 4 finished with value: 0.429940741638164 and parameters: {'alpha': 1.0242092044364945, 'l1_ratio': 0.10253088968146462}. Best is trial 4 with value: 0.429940741638164.
[I 2025-07-11 20:40:45,375] Trial 5 finished with value: -0.00027817151752640434 and parameters: {'alpha': 8.174185230999242, 'l1_ratio': 0.6636111602511366}. Best is trial 4 with value: 0.429940741638164.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.62 | R2: 0.43
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.47 | R2: -0.00
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.890e+00, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.597e-01, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.935e-01, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.652e+00, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 20:40:45,492] Trial 6 finished with value: 0.24706035714471597 and parameters: {'alpha': 0.013665829053606533, 'l1_ratio': 0.825066721107669}. Best is trial 4 with value: 0.429940741638164.
[I 2025-07-11 20:40:45,577] Trial 7 finished with value: 0.4086984529310267 and parameters: {'alpha': 0.7545215549304112, 'l1_ratio': 0.7225189298586465}. Best is trial 4 with value: 0.429940741638164.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.01 | R2: 0.25
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.67 | R2: 0.41
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:40:45,660] Trial 8 finished with value: 0.415632483897576 and parameters: {'alpha': 0.08700575106533039, 'l1_ratio': 0.7578366247558135}. Best is trial 4 with value: 0.429940741638164.
[I 2025-07-11 20:40:45,743] Trial 9 finished with value: 0.41721460337292604 and parameters: {'alpha': 0.6163138528372941, 'l1_ratio': 0.5958759634506808}. Best is trial 4 with value: 0.429940741638164.

Running time: 0.1 sec
OOF RMSE: 2.65 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.65 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.276e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.739e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.806e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.327e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.472e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 20:40:45,872] Trial 10 finished with value: -0.6595367480572034 and parameters: {'alpha': 0.00013011896791361084, 'l1_ratio': 0.01685990719478997}. Best is trial 4 with value: 0.429940741638164.
[I 2025-07-11 20:40:45,963] Trial 11 finished with value: 0.2820630691706778 and parameters: {'alpha': 8.324435842284924, 'l1_ratio': 0.14462515951439903}. Best is trial 4 with value: 0.429940741638164.
[I 2025-07-11 20:40:46,048] Trial 12 finished with value: 0.4106259078261757 and parameters: {'alpha': 1.2604968013404938, 'l1_ratio': 0.3062337913845781}. Best is trial 4 with value: 0.429940741638164.

Running time: 0.1 sec
OOF RMSE: 4.47 | R2: -0.66
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.94 | R2: 0.28
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.66 | R2: 0.41
Fold 1

[I 2025-07-11 20:40:46,140] Trial 13 finished with value: 0.4264747318980293 and parameters: {'alpha': 0.29448100166391983, 'l1_ratio': 0.3370514591465695}. Best is trial 4 with value: 0.429940741638164.
[I 2025-07-11 20:40:46,240] Trial 14 finished with value: 0.4278513271841845 and parameters: {'alpha': 0.30140512225228755, 'l1_ratio': 0.30168237117099744}. Best is trial 4 with value: 0.429940741638164.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.63 | R2: 0.43
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.62 | R2: 0.43
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.830e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.120e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.796e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.895e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.888e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 20:40:46,446] Trial 15 finished with value: -0.24021206562065367 and parameters: {'alpha': 0.0019505701967014138, 'l1_ratio': 0.40322940477543767}. Best is trial 4 with value: 0.429940741638164.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 3.86 | R2: -0.24
Fold 1
Fold 2
Fold 3

[I 2025-07-11 20:40:46,589] Trial 16 finished with value: 0.4117146715569746 and parameters: {'alpha': 0.16393494151768667, 'l1_ratio': 0.954257386247162}. Best is trial 4 with value: 0.429940741638164.
[I 2025-07-11 20:40:46,700] Trial 17 finished with value: 0.38067851077316683 and parameters: {'alpha': 2.9190312308220037, 'l1_ratio': 0.21964647681866378}. Best is trial 4 with value: 0.429940741638164.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.66 | R2: 0.41
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.73 | R2: 0.38
Fold 1

[I 2025-07-11 20:40:46,908] Trial 18 finished with value: 0.42125755268480936 and parameters: {'alpha': 0.29693841143172334, 'l1_ratio': 0.48343162351780583}. Best is trial 4 with value: 0.429940741638164.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 2.64 | R2: 0.42
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.807e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.105e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.087e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.495e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.429e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 20:40:47,064] Trial 19 finished with value: 0.15360310021484425 and parameters: {'alpha': 0.0062554002753286535, 'l1_ratio': 0.2239892016406938}. Best is trial 4 with value: 0.429940741638164.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.330e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.862e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.19 | R2: 0.15
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.984e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.453e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.749e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 20:40:47,243] Trial 20 finished with value: -0.4559566896280316 and parameters: {'alpha': 0.0006811252463497214, 'l1_ratio': 0.007895988066696918}. Best is trial 4 with value: 0.429940741638164.
[I 2025-07-11 20:40:47,354] Trial 21 finished with value: 0.4249222919455602 and parameters: {'alpha': 0.2831737003954201, 'l1_ratio': 0.3785797333022116}. Best is trial 4 with value: 0.429940741638164.

Fold 5
Running time: 0.2 sec
OOF RMSE: 4.18 | R2: -0.46
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.63 | R2: 0.42
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.852e-01, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.566e+00, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 20:40:47,504] Trial 22 finished with value: 0.38335956417823713 and parameters: {'alpha': 0.03916181133197257, 'l1_ratio': 0.2563980347189468}. Best is trial 4 with value: 0.429940741638164.
[I 2025-07-11 20:40:47,608] Trial 23 finished with value: 0.42715474218739613 and parameters: {'alpha': 0.21282967785557586, 'l1_ratio': 0.34475775221434946}. Best is trial 4 with value: 0.429940741638164.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.72 | R2: 0.38
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.62 | R2: 0.43
Fold 1

[I 2025-07-11 20:40:47,720] Trial 24 finished with value: 0.40429782774059453 and parameters: {'alpha': 2.6519132475920673, 'l1_ratio': 0.12177172801483815}. Best is trial 4 with value: 0.429940741638164.
[I 2025-07-11 20:40:47,721] A new study created in memory with name: no-name-360c99d9-1bf9-422b-8f73-2d1d33e3d631

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.68 | R2: 0.40

✅ EN - Mejor R2: 0.43
📋 Parámetros: {'alpha': 1.0242092044364945, 'l1_ratio': 0.10253088968146462}

🔍 Optimizando en C2X_rhow_9x9_depth_lt_1...
Buscando mejores hiperparámetros para XGB...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:40:55,855] Trial 0 finished with value: 0.4334294991687069 and parameters: {'n_estimators': 1000, 'learning_rate': 0.03654678232953994, 'max_depth': 6, 'min_child_weight': 1, 'subsample': 0.8042245381530257, 'colsample_bytree': 0.9245185177336555}. Best is trial 0 with value: 0.4334294991687069.

Running time: 8.1 sec
OOF RMSE: 2.61 | R2: 0.43
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:40:58,121] Trial 1 finished with value: 0.4267313591453019 and parameters: {'n_estimators': 500, 'learning_rate': 0.018010159521842463, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.6269486442633737, 'colsample_bytree': 0.6607064899879208}. Best is trial 0 with value: 0.4334294991687069.

Running time: 2.3 sec
OOF RMSE: 2.62 | R2: 0.43
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:41:06,054] Trial 2 finished with value: 0.4195807215968541 and parameters: {'n_estimators': 1000, 'learning_rate': 0.008774547087576962, 'max_depth': 8, 'min_child_weight': 3, 'subsample': 0.8621768623780433, 'colsample_bytree': 0.8013840903480095}. Best is trial 0 with value: 0.4334294991687069.

Running time: 7.9 sec
OOF RMSE: 2.64 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:41:14,228] Trial 3 finished with value: 0.4220751419458544 and parameters: {'n_estimators': 1000, 'learning_rate': 0.024316874187503505, 'max_depth': 8, 'min_child_weight': 3, 'subsample': 0.7467955120520686, 'colsample_bytree': 0.9071378884632773}. Best is trial 0 with value: 0.4334294991687069.

Running time: 8.2 sec
OOF RMSE: 2.64 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:41:16,512] Trial 4 finished with value: 0.4138675255608103 and parameters: {'n_estimators': 500, 'learning_rate': 0.02043605259795371, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.9849325491764628, 'colsample_bytree': 0.6182825279568468}. Best is trial 0 with value: 0.4334294991687069.

Running time: 2.3 sec
OOF RMSE: 2.65 | R2: 0.41
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:41:19,708] Trial 5 finished with value: 0.4201090668080625 and parameters: {'n_estimators': 500, 'learning_rate': 0.03673209240936748, 'max_depth': 8, 'min_child_weight': 4, 'subsample': 0.8881175851571442, 'colsample_bytree': 0.7303632664834213}. Best is trial 0 with value: 0.4334294991687069.

Running time: 3.2 sec
OOF RMSE: 2.64 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:41:22,218] Trial 6 finished with value: 0.3955272599972872 and parameters: {'n_estimators': 500, 'learning_rate': 0.008343538692270846, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.793213622781682, 'colsample_bytree': 0.9185233379610673}. Best is trial 0 with value: 0.4334294991687069.

Running time: 2.5 sec
OOF RMSE: 2.70 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:41:28,745] Trial 7 finished with value: 0.4394438427353031 and parameters: {'n_estimators': 1000, 'learning_rate': 0.05915498881052614, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.6558058252926156, 'colsample_bytree': 0.7261569536187278}. Best is trial 7 with value: 0.4394438427353031.

Running time: 6.5 sec
OOF RMSE: 2.60 | R2: 0.44
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:41:39,012] Trial 8 finished with value: 0.41606584750485975 and parameters: {'n_estimators': 2000, 'learning_rate': 0.01965410677082512, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.9447204922462739, 'colsample_bytree': 0.6403921305229612}. Best is trial 7 with value: 0.4394438427353031.

Running time: 10.3 sec
OOF RMSE: 2.65 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:41:42,446] Trial 9 finished with value: 0.43364155492367773 and parameters: {'n_estimators': 500, 'learning_rate': 0.03701951554512196, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.6437285202788889, 'colsample_bytree': 0.9528869562944474}. Best is trial 7 with value: 0.4394438427353031.

Running time: 3.4 sec
OOF RMSE: 2.61 | R2: 0.43
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:41:52,992] Trial 10 finished with value: 0.4507847226144114 and parameters: {'n_estimators': 2000, 'learning_rate': 0.09432809674274524, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.703989010553551, 'colsample_bytree': 0.8091395583091203}. Best is trial 10 with value: 0.4507847226144114.

Running time: 10.5 sec
OOF RMSE: 2.57 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:42:03,637] Trial 11 finished with value: 0.4161106269344276 and parameters: {'n_estimators': 2000, 'learning_rate': 0.09969480515577314, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.6580871610181611, 'colsample_bytree': 0.7929725391603717}. Best is trial 10 with value: 0.4507847226144114.

Running time: 10.6 sec
OOF RMSE: 2.65 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:42:14,071] Trial 12 finished with value: 0.44784175091672307 and parameters: {'n_estimators': 2000, 'learning_rate': 0.09105345270067779, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.6968933341696572, 'colsample_bytree': 0.8125930847450256}. Best is trial 10 with value: 0.4507847226144114.

Running time: 10.4 sec
OOF RMSE: 2.58 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:42:24,531] Trial 13 finished with value: 0.4404961218456602 and parameters: {'n_estimators': 2000, 'learning_rate': 0.0919859579559443, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.7217438929862103, 'colsample_bytree': 0.8597708608984944}. Best is trial 10 with value: 0.4507847226144114.

Running time: 10.5 sec
OOF RMSE: 2.59 | R2: 0.44
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:42:34,947] Trial 14 finished with value: 0.4429289108399782 and parameters: {'n_estimators': 2000, 'learning_rate': 0.06354707132516527, 'max_depth': 6, 'min_child_weight': 1, 'subsample': 0.71793593830186, 'colsample_bytree': 0.8434161076316241}. Best is trial 10 with value: 0.4507847226144114.

Running time: 10.4 sec
OOF RMSE: 2.59 | R2: 0.44
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:42:47,329] Trial 15 finished with value: 0.46330865750529815 and parameters: {'n_estimators': 2000, 'learning_rate': 0.005199293845432892, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.6025661007443318, 'colsample_bytree': 0.7541083873001371}. Best is trial 15 with value: 0.46330865750529815.

Running time: 12.4 sec
OOF RMSE: 2.54 | R2: 0.46
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:42:58,421] Trial 16 finished with value: 0.4561743226543824 and parameters: {'n_estimators': 2000, 'learning_rate': 0.005189703767199189, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.6103256932329203, 'colsample_bytree': 0.7317196975817684}. Best is trial 15 with value: 0.46330865750529815.

Running time: 11.1 sec
OOF RMSE: 2.56 | R2: 0.46
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:43:09,455] Trial 17 finished with value: 0.45218605253475486 and parameters: {'n_estimators': 2000, 'learning_rate': 0.005105028259829657, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.6133504105481542, 'colsample_bytree': 0.7230144246085001}. Best is trial 15 with value: 0.46330865750529815.

Running time: 11.0 sec
OOF RMSE: 2.57 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:43:20,576] Trial 18 finished with value: 0.45761735163073103 and parameters: {'n_estimators': 2000, 'learning_rate': 0.005221369871237473, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.6018728765492556, 'colsample_bytree': 0.6849652498327617}. Best is trial 15 with value: 0.46330865750529815.

Running time: 11.1 sec
OOF RMSE: 2.55 | R2: 0.46
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:43:31,085] Trial 19 finished with value: 0.4092442950611228 and parameters: {'n_estimators': 2000, 'learning_rate': 0.010585880506752212, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.7653810389514114, 'colsample_bytree': 0.6730945883682918}. Best is trial 15 with value: 0.46330865750529815.

Running time: 10.5 sec
OOF RMSE: 2.66 | R2: 0.41
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:43:41,072] Trial 20 finished with value: 0.4467308547669281 and parameters: {'n_estimators': 2000, 'learning_rate': 0.012636073065722953, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.6705249013739013, 'colsample_bytree': 0.7635536251104892}. Best is trial 15 with value: 0.46330865750529815.

Running time: 10.0 sec
OOF RMSE: 2.58 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:43:51,902] Trial 21 finished with value: 0.4583339142339138 and parameters: {'n_estimators': 2000, 'learning_rate': 0.0050627235899188315, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.6057112987943014, 'colsample_bytree': 0.708860273743394}. Best is trial 15 with value: 0.46330865750529815.

Running time: 10.8 sec
OOF RMSE: 2.55 | R2: 0.46
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:44:02,772] Trial 22 finished with value: 0.4653614408291108 and parameters: {'n_estimators': 2000, 'learning_rate': 0.006618545905303849, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.6073846275021353, 'colsample_bytree': 0.6882824133242283}. Best is trial 22 with value: 0.4653614408291108.

Running time: 10.9 sec
OOF RMSE: 2.53 | R2: 0.47
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:44:13,777] Trial 23 finished with value: 0.4615029799946123 and parameters: {'n_estimators': 2000, 'learning_rate': 0.007051745846681361, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.678785694147827, 'colsample_bytree': 0.6961808972736596}. Best is trial 22 with value: 0.4653614408291108.

Running time: 11.0 sec
OOF RMSE: 2.54 | R2: 0.46
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:44:25,475] Trial 24 finished with value: 0.4499064943840483 and parameters: {'n_estimators': 2000, 'learning_rate': 0.007136241760124566, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.6762264169676725, 'colsample_bytree': 0.771868889774718}. Best is trial 22 with value: 0.4653614408291108.
[I 2025-07-11 20:44:25,476] A new study created in memory with name: no-name-92fba852-07cf-45c0-ac66-908d03e2a5ca

Running time: 11.7 sec
OOF RMSE: 2.57 | R2: 0.45

✅ XGB - Mejor R2: 0.47
📋 Parámetros: {'n_estimators': 2000, 'learning_rate': 0.006618545905303849, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.6073846275021353, 'colsample_bytree': 0.6882824133242283}

Buscando mejores hiperparámetros para LBM...
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 20:44:25,793] Trial 0 finished with value: 0.41491029886637043 and parameters: {'learning_rate': 0.014765004571065244, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 9, 'subsample': 0.9814004575480051, 'colsample_bytree': 0.8442466986237266, 'n_estimators': 500}. Best is trial 0 with value: 0.41491029886637043.

Fold 5
Running time: 0.3 sec
OOF RMSE: 2.65 | R2: 0.41
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 20:44:26,766] Trial 1 finished with value: 0.39284786962877294 and parameters: {'learning_rate': 0.007169165978828273, 'num_leaves': 40, 'max_depth': 7, 'min_child_samples': 22, 'subsample': 0.7046258592635839, 'colsample_bytree': 0.7479554447158927, 'n_estimators': 2000}. Best is trial 0 with value: 0.41491029886637043.

Fold 5
Running time: 1.0 sec
OOF RMSE: 2.70 | R2: 0.39
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:44:27,400] Trial 2 finished with value: 0.36692332810232364 and parameters: {'learning_rate': 0.0069545320080853954, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 7, 'subsample': 0.719887709538399, 'colsample_bytree': 0.728503993498281, 'n_estimators': 1000}. Best is trial 0 with value: 0.41491029886637043.

Running time: 0.6 sec
OOF RMSE: 2.76 | R2: 0.37
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 20:44:27,719] Trial 3 finished with value: 0.38334696978339133 and parameters: {'learning_rate': 0.0140988422387199, 'num_leaves': 20, 'max_depth': 8, 'min_child_samples': 20, 'subsample': 0.9682923723008114, 'colsample_bytree': 0.9601569258521798, 'n_estimators': 500}. Best is trial 0 with value: 0.41491029886637043.

Fold 5
Running time: 0.3 sec
OOF RMSE: 2.72 | R2: 0.38
Fold 1
Fold 2

[I 2025-07-11 20:44:28,019] Trial 4 finished with value: 0.39001942569419124 and parameters: {'learning_rate': 0.07754351710810996, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 23, 'subsample': 0.8174618938759979, 'colsample_bytree': 0.7907686961365803, 'n_estimators': 500}. Best is trial 0 with value: 0.41491029886637043.

Fold 3
Fold 4
Fold 5
Running time: 0.3 sec
OOF RMSE: 2.71 | R2: 0.39
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:44:28,569] Trial 5 finished with value: 0.371513072159101 and parameters: {'learning_rate': 0.008479105221820599, 'num_leaves': 60, 'max_depth': 7, 'min_child_samples': 17, 'subsample': 0.8913675287802174, 'colsample_bytree': 0.886256628181923, 'n_estimators': 1000}. Best is trial 0 with value: 0.41491029886637043.

Running time: 0.5 sec
OOF RMSE: 2.75 | R2: 0.37
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:44:29,067] Trial 6 finished with value: 0.37062696758484115 and parameters: {'learning_rate': 0.0812360939135175, 'num_leaves': 40, 'max_depth': 6, 'min_child_samples': 25, 'subsample': 0.708651978050153, 'colsample_bytree': 0.9091406833968803, 'n_estimators': 1000}. Best is trial 0 with value: 0.41491029886637043.

Running time: 0.5 sec
OOF RMSE: 2.75 | R2: 0.37
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 20:44:29,802] Trial 7 finished with value: 0.3754779600849183 and parameters: {'learning_rate': 0.038438073451698564, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 25, 'subsample': 0.7603055736599523, 'colsample_bytree': 0.6098741579662589, 'n_estimators': 2000}. Best is trial 0 with value: 0.41491029886637043.

Fold 5
Running time: 0.7 sec
OOF RMSE: 2.74 | R2: 0.38
Fold 1
Fold 2

[I 2025-07-11 20:44:30,059] Trial 8 finished with value: 0.32950400104066524 and parameters: {'learning_rate': 0.016618002306463226, 'num_leaves': 80, 'max_depth': 5, 'min_child_samples': 16, 'subsample': 0.7293085939461695, 'colsample_bytree': 0.7533899808499331, 'n_estimators': 500}. Best is trial 0 with value: 0.41491029886637043.

Fold 3
Fold 4
Fold 5
Running time: 0.3 sec
OOF RMSE: 2.84 | R2: 0.33
Fold 1
Fold 2
Fold 3

[I 2025-07-11 20:44:30,575] Trial 9 finished with value: 0.38413641805303655 and parameters: {'learning_rate': 0.016184502635622582, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 17, 'subsample': 0.8849435340403882, 'colsample_bytree': 0.6847765619794834, 'n_estimators': 1000}. Best is trial 0 with value: 0.41491029886637043.

Fold 4
Fold 5
Running time: 0.5 sec
OOF RMSE: 2.72 | R2: 0.38
Fold 1
Fold 2
Fold 3

[I 2025-07-11 20:44:30,935] Trial 10 finished with value: 0.36916109805107444 and parameters: {'learning_rate': 0.03478353658283638, 'num_leaves': 60, 'max_depth': 8, 'min_child_samples': 8, 'subsample': 0.9967983566828851, 'colsample_bytree': 0.8548708843417406, 'n_estimators': 500}. Best is trial 0 with value: 0.41491029886637043.

Fold 4
Fold 5
Running time: 0.4 sec
OOF RMSE: 2.75 | R2: 0.37
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:44:31,924] Trial 11 finished with value: 0.3950826784288287 and parameters: {'learning_rate': 0.005681518152340175, 'num_leaves': 40, 'max_depth': 6, 'min_child_samples': 11, 'subsample': 0.6314792660788945, 'colsample_bytree': 0.8247793804728664, 'n_estimators': 2000}. Best is trial 0 with value: 0.41491029886637043.

Running time: 1.0 sec
OOF RMSE: 2.70 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 20:44:32,930] Trial 12 finished with value: 0.38941490863197203 and parameters: {'learning_rate': 0.005606567346192313, 'num_leaves': 40, 'max_depth': 6, 'min_child_samples': 11, 'subsample': 0.6060290947524102, 'colsample_bytree': 0.8374316319021908, 'n_estimators': 2000}. Best is trial 0 with value: 0.41491029886637043.

Fold 5
Running time: 1.0 sec
OOF RMSE: 2.71 | R2: 0.39
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 20:44:33,959] Trial 13 finished with value: 0.39297000800610893 and parameters: {'learning_rate': 0.010741180213378807, 'num_leaves': 80, 'max_depth': 6, 'min_child_samples': 11, 'subsample': 0.6362744274883794, 'colsample_bytree': 0.9983952519723265, 'n_estimators': 2000}. Best is trial 0 with value: 0.41491029886637043.

Fold 5
Running time: 1.0 sec
OOF RMSE: 2.70 | R2: 0.39
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:44:34,946] Trial 14 finished with value: 0.35171973319702776 and parameters: {'learning_rate': 0.025721049424384863, 'num_leaves': 40, 'max_depth': 6, 'min_child_samples': 12, 'subsample': 0.871601225332508, 'colsample_bytree': 0.8160552744341366, 'n_estimators': 2000}. Best is trial 0 with value: 0.41491029886637043.

Running time: 1.0 sec
OOF RMSE: 2.79 | R2: 0.35
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 20:44:35,511] Trial 15 finished with value: 0.4387719854637361 and parameters: {'learning_rate': 0.005139185450780679, 'num_leaves': 40, 'max_depth': 8, 'min_child_samples': 5, 'subsample': 0.9320768812147596, 'colsample_bytree': 0.8930675994863468, 'n_estimators': 500}. Best is trial 15 with value: 0.4387719854637361.

Fold 5
Running time: 0.6 sec
OOF RMSE: 2.60 | R2: 0.44
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 20:44:35,988] Trial 16 finished with value: 0.46212919069327907 and parameters: {'learning_rate': 0.011008315969882157, 'num_leaves': 60, 'max_depth': 8, 'min_child_samples': 5, 'subsample': 0.9391830259538412, 'colsample_bytree': 0.9248852156294086, 'n_estimators': 500}. Best is trial 16 with value: 0.46212919069327907.

Fold 5
Running time: 0.5 sec
OOF RMSE: 2.54 | R2: 0.46
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 20:44:36,499] Trial 17 finished with value: 0.4585282756363016 and parameters: {'learning_rate': 0.009001322196220117, 'num_leaves': 60, 'max_depth': 8, 'min_child_samples': 5, 'subsample': 0.9317822247241575, 'colsample_bytree': 0.91904034309072, 'n_estimators': 500}. Best is trial 16 with value: 0.46212919069327907.

Fold 5
Running time: 0.5 sec
OOF RMSE: 2.55 | R2: 0.46
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:44:36,930] Trial 18 finished with value: 0.42581512112152564 and parameters: {'learning_rate': 0.010346502106733307, 'num_leaves': 60, 'max_depth': 8, 'min_child_samples': 6, 'subsample': 0.8294331149896315, 'colsample_bytree': 0.9482290559250192, 'n_estimators': 500}. Best is trial 16 with value: 0.46212919069327907.

Running time: 0.4 sec
OOF RMSE: 2.63 | R2: 0.43
Fold 1
Fold 2
Fold 3

[I 2025-07-11 20:44:37,305] Trial 19 finished with value: 0.3017334652972956 and parameters: {'learning_rate': 0.023409602156788403, 'num_leaves': 60, 'max_depth': 8, 'min_child_samples': 14, 'subsample': 0.9320478848298897, 'colsample_bytree': 0.9374752476433047, 'n_estimators': 500}. Best is trial 16 with value: 0.46212919069327907.

Fold 4
Fold 5
Running time: 0.4 sec
OOF RMSE: 2.90 | R2: 0.30
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 20:44:37,789] Trial 20 finished with value: 0.47342319609957517 and parameters: {'learning_rate': 0.011134896607881906, 'num_leaves': 60, 'max_depth': 8, 'min_child_samples': 5, 'subsample': 0.9333611710130115, 'colsample_bytree': 0.9961077153876287, 'n_estimators': 500}. Best is trial 20 with value: 0.47342319609957517.

Fold 5
Running time: 0.5 sec
OOF RMSE: 2.52 | R2: 0.47
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:44:38,258] Trial 21 finished with value: 0.4688948063442552 and parameters: {'learning_rate': 0.011085709360970369, 'num_leaves': 60, 'max_depth': 8, 'min_child_samples': 5, 'subsample': 0.9249410113209311, 'colsample_bytree': 0.9892448675286727, 'n_estimators': 500}. Best is trial 20 with value: 0.47342319609957517.

Running time: 0.5 sec
OOF RMSE: 2.53 | R2: 0.47
Fold 1
Fold 2
Fold 3

[I 2025-07-11 20:44:38,673] Trial 22 finished with value: 0.40564640407874186 and parameters: {'learning_rate': 0.012223889328979566, 'num_leaves': 60, 'max_depth': 8, 'min_child_samples': 9, 'subsample': 0.8537589328216654, 'colsample_bytree': 0.9945107354424702, 'n_estimators': 500}. Best is trial 20 with value: 0.47342319609957517.

Fold 4
Fold 5
Running time: 0.4 sec
OOF RMSE: 2.67 | R2: 0.41
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 20:44:39,079] Trial 23 finished with value: 0.3546041042539376 and parameters: {'learning_rate': 0.019084119227414705, 'num_leaves': 60, 'max_depth': 8, 'min_child_samples': 7, 'subsample': 0.9475743784085483, 'colsample_bytree': 0.9704086043964099, 'n_estimators': 500}. Best is trial 20 with value: 0.47342319609957517.

Fold 5
Running time: 0.4 sec
OOF RMSE: 2.78 | R2: 0.35
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:44:39,531] Trial 24 finished with value: 0.46588978031116235 and parameters: {'learning_rate': 0.011808386117187653, 'num_leaves': 60, 'max_depth': 7, 'min_child_samples': 5, 'subsample': 0.8965273648209245, 'colsample_bytree': 0.9796746210238588, 'n_estimators': 500}. Best is trial 20 with value: 0.47342319609957517.
[I 2025-07-11 20:44:39,532] A new study created in memory with name: no-name-b1b91450-d11a-4745-b42d-24e7694154ef

Running time: 0.4 sec
OOF RMSE: 2.53 | R2: 0.47

✅ LBM - Mejor R2: 0.47
📋 Parámetros: {'learning_rate': 0.011134896607881906, 'num_leaves': 60, 'max_depth': 8, 'min_child_samples': 5, 'subsample': 0.9333611710130115, 'colsample_bytree': 0.9961077153876287, 'n_estimators': 500}

Buscando mejores hiperparámetros para MLP...
Fold 1
Fold 2
Fold 3

[I 2025-07-11 20:44:40,155] Trial 0 finished with value: 0.3380056631820383 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.023687953540982347, 'learning_rate': 'constant', 'learning_rate_init': 0.004029909412257359}. Best is trial 0 with value: 0.3380056631820383.

Fold 4
Fold 5
Running time: 0.6 sec
OOF RMSE: 2.82 | R2: 0.34
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:44:40,808] Trial 1 finished with value: 0.3331993619808884 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.029902510244200552, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0004054411295177623}. Best is trial 0 with value: 0.3380056631820383.

Running time: 0.6 sec
OOF RMSE: 2.83 | R2: 0.33
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 20:44:42,162] Trial 2 finished with value: 0.3817416355063983 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.025010359628490783, 'learning_rate': 'constant', 'learning_rate_init': 0.0018522940078459797}. Best is trial 2 with value: 0.3817416355063983.

Running time: 1.3 sec
OOF RMSE: 2.73 | R2: 0.38
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 20:44:43,622] Trial 3 finished with value: 0.3742941144127312 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.00037554524837329374, 'learning_rate': 'constant', 'learning_rate_init': 0.00012615513732784257}. Best is trial 2 with value: 0.3817416355063983.

Running time: 1.5 sec
OOF RMSE: 2.74 | R2: 0.37
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 20:44:46,422] Trial 4 finished with value: 0.33436956760489756 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 4.202834837604312e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0009463560750873398}. Best is trial 2 with value: 0.3817416355063983.

Running time: 2.8 sec
OOF RMSE: 2.83 | R2: 0.33
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 20:44:47,041] Trial 5 finished with value: 0.35221562567839726 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0037834381188509257, 'learning_rate': 'constant', 'learning_rate_init': 0.0018910430569913676}. Best is trial 2 with value: 0.3817416355063983.

Fold 5
Running time: 0.6 sec
OOF RMSE: 2.79 | R2: 0.35
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

[I 2025-07-11 20:44:48,415] Trial 6 finished with value: 0.2836402351090982 and parameters: {'hidden_layer_sizes': '50', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.01765664736499057, 'learning_rate': 'adaptive', 'learning_rate_init': 0.001190448404139695}. Best is trial 2 with value: 0.3817416355063983.

Running time: 1.4 sec
OOF RMSE: 2.93 | R2: 0.28
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 20:44:50,958] Trial 7 finished with value: 0.3563354698038559 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.0192557667379937, 'learning_rate': 'adaptive', 'learning_rate_init': 0.007527818624473495}. Best is trial 2 with value: 0.3817416355063983.

Running time: 2.5 sec
OOF RMSE: 2.78 | R2: 0.36
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 20:44:51,743] Trial 8 finished with value: 0.20831264012292827 and parameters: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.012808883633193765, 'learning_rate': 'adaptive', 'learning_rate_init': 0.003171220988595414}. Best is trial 2 with value: 0.3817416355063983.

Fold 5
Running time: 0.8 sec
OOF RMSE: 3.08 | R2: 0.21
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:44:52,385] Trial 9 finished with value: 0.35974131242885254 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.040875551407536244, 'learning_rate': 'constant', 'learning_rate_init': 0.0026549384986366844}. Best is trial 2 with value: 0.3817416355063983.

Running time: 0.6 sec
OOF RMSE: 2.77 | R2: 0.36
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 20:44:53,780] Trial 10 finished with value: 0.38446105892185944 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.0008426661225113288, 'learning_rate': 'constant', 'learning_rate_init': 0.00040524220813810587}. Best is trial 10 with value: 0.38446105892185944.

Running time: 1.4 sec
OOF RMSE: 2.72 | R2: 0.38
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 20:44:55,334] Trial 11 finished with value: 0.3841157287005177 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.0004385085390624614, 'learning_rate': 'constant', 'learning_rate_init': 0.00039789168179056947}. Best is trial 10 with value: 0.38446105892185944.

Running time: 1.5 sec
OOF RMSE: 2.72 | R2: 0.38
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 20:44:56,973] Trial 12 finished with value: 0.37977067753000116 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.00029146181741805053, 'learning_rate': 'constant', 'learning_rate_init': 0.0003108383052775619}. Best is trial 10 with value: 0.38446105892185944.

Running time: 1.6 sec
OOF RMSE: 2.73 | R2: 0.38
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 20:44:58,479] Trial 13 finished with value: 0.384859008796849 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.0014563549610648009, 'learning_rate': 'constant', 'learning_rate_init': 0.0004096328378967801}. Best is trial 13 with value: 0.384859008796849.

Running time: 1.5 sec
OOF RMSE: 2.72 | R2: 0.38
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 20:44:59,411] Trial 14 finished with value: 0.2803816254449528 and parameters: {'hidden_layer_sizes': '50', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.0023457381159752437, 'learning_rate': 'constant', 'learning_rate_init': 0.00017320850102473784}. Best is trial 13 with value: 0.384859008796849.

Fold 4
Fold 5
Running time: 0.9 sec
OOF RMSE: 2.94 | R2: 0.28
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 20:45:00,838] Trial 15 finished with value: 0.3914318526227347 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 6.163548148420085e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.0008124553204028073}. Best is trial 15 with value: 0.3914318526227347.

Running time: 1.4 sec
OOF RMSE: 2.70 | R2: 0.39
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 20:45:02,205] Trial 16 finished with value: 0.39115290029360517 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 1.3928141913138172e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.0008049414036729055}. Best is trial 15 with value: 0.3914318526227347.

Running time: 1.4 sec
OOF RMSE: 2.70 | R2: 0.39
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 20:45:03,565] Trial 17 finished with value: 0.38958489556832643 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 1.447724364237636e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.0007417887738055229}. Best is trial 15 with value: 0.3914318526227347.

Running time: 1.4 sec
OOF RMSE: 2.71 | R2: 0.39
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 20:45:05,363] Trial 18 finished with value: 0.3605493657434422 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 7.439765583629596e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.0007946626549376744}. Best is trial 15 with value: 0.3914318526227347.

Running time: 1.8 sec
OOF RMSE: 2.77 | R2: 0.36
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 20:45:06,051] Trial 19 finished with value: 0.2833929641221824 and parameters: {'hidden_layer_sizes': '50', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 1.1726071902710952e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.0002130105159969111}. Best is trial 15 with value: 0.3914318526227347.

Fold 4
Fold 5
Running time: 0.7 sec
OOF RMSE: 2.93 | R2: 0.28
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 20:45:07,423] Trial 20 finished with value: 0.388984877344717 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 8.452193672238073e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.0006163326980137935}. Best is trial 15 with value: 0.3914318526227347.

Running time: 1.4 sec
OOF RMSE: 2.71 | R2: 0.39
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 20:45:08,743] Trial 21 finished with value: 0.3845269844133511 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 1.1211808372529534e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.0014094357890446837}. Best is trial 15 with value: 0.3914318526227347.

Running time: 1.3 sec
OOF RMSE: 2.72 | R2: 0.38
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 20:45:10,272] Trial 22 finished with value: 0.3913626486066015 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 2.096678902474493e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.0006880426832309817}. Best is trial 15 with value: 0.3914318526227347.

Running time: 1.5 sec
OOF RMSE: 2.70 | R2: 0.39
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 20:45:11,800] Trial 23 finished with value: 0.38825689113226614 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 3.5760138029190125e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.0005926415897378693}. Best is trial 15 with value: 0.3914318526227347.

Running time: 1.5 sec
OOF RMSE: 2.71 | R2: 0.39
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 20:45:13,190] Trial 24 finished with value: 0.3835879925359136 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.00013647783580685957, 'learning_rate': 'constant', 'learning_rate_init': 0.001310864644829079}. Best is trial 15 with value: 0.3914318526227347.
[I 2025-07-11 20:45:13,191] A new study created in memory with name: no-name-4ae3b9ca-48a6-431f-8e7a-8f16bfae4d84
[I 2025-07-11 20:45:13,280] Trial 0 finished with value: 0.21533275349087977 and parameters: {'kernel': 'rbf', 'C': 1.325027017454424, 'epsilon': 0.07031782288057371, 'gamma': 'scale'}. Best is trial 0 with value: 0.21533275349087977.
[I 2025-07-11 20:45:13,357] Trial 1 finished with value: -2.68920943222322 and parameters: {'kernel': 'sigmoid', 'C': 0.7966192147683219, 'epsilon': 0.19309839749894875, 'gamma': 'auto'}. Best is trial 0 with value: 0.21533275349087977.

Running time: 1.4 sec
OOF RMSE: 2.72 | R2: 0.38

✅ MLP - Mejor R2: 0.39
📋 Parámetros: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 6.163548148420085e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.0008124553204028073}

Buscando mejores hiperparámetros para SVR...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.07 | R2: 0.22
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 6.66 | R2: -2.69
Fold 1
Fold 2

[I 2025-07-11 20:45:13,434] Trial 2 finished with value: 0.2616146211842457 and parameters: {'kernel': 'rbf', 'C': 2.790529528576103, 'epsilon': 0.1381140018064716, 'gamma': 'scale'}. Best is trial 2 with value: 0.2616146211842457.
[I 2025-07-11 20:45:13,510] Trial 3 finished with value: -3.74515114466095 and parameters: {'kernel': 'sigmoid', 'C': 1.0315006713735466, 'epsilon': 0.11619229360313064, 'gamma': 'scale'}. Best is trial 2 with value: 0.2616146211842457.
[I 2025-07-11 20:45:13,593] Trial 4 finished with value: -3.367825729552391 and parameters: {'kernel': 'sigmoid', 'C': 0.9740596266498557, 'epsilon': 0.14404336757974162, 'gamma': 'scale'}. Best is trial 2 with value: 0.2616146211842457.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.98 | R2: 0.26
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 7.55 | R2: -3.75
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 7.24 | R2: -3.37

[I 2025-07-11 20:45:13,666] Trial 5 finished with value: -0.044266622881405704 and parameters: {'kernel': 'sigmoid', 'C': 0.2017855176731211, 'epsilon': 0.04369933084313482, 'gamma': 'scale'}. Best is trial 2 with value: 0.2616146211842457.
[I 2025-07-11 20:45:13,739] Trial 6 finished with value: 0.040234257399450746 and parameters: {'kernel': 'rbf', 'C': 0.1138039052159894, 'epsilon': 0.09480978060357535, 'gamma': 'scale'}. Best is trial 2 with value: 0.2616146211842457.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.54 | R2: -0.04
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.40 | R2: 0.04
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:45:13,813] Trial 7 finished with value: -43.32318288486835 and parameters: {'kernel': 'sigmoid', 'C': 3.5228366062640712, 'epsilon': 0.06166162680876538, 'gamma': 'auto'}. Best is trial 2 with value: 0.2616146211842457.
[I 2025-07-11 20:45:13,887] Trial 8 finished with value: -3.9259118245169526 and parameters: {'kernel': 'sigmoid', 'C': 0.9867401503882997, 'epsilon': 0.07384212059035578, 'gamma': 'auto'}. Best is trial 2 with value: 0.2616146211842457.
[I 2025-07-11 20:45:13,962] Trial 9 finished with value: -0.6043947625531823 and parameters: {'kernel': 'sigmoid', 'C': 0.3774484562753199, 'epsilon': 0.19531975857533335, 'gamma': 'auto'}. Best is trial 2 with value: 0.2616146211842457.

Running time: 0.1 sec
OOF RMSE: 23.08 | R2: -43.32
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 7.69 | R2: -3.93
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 4.39 | R2: -0.60
Fold 1
Fold 2

[I 2025-07-11 20:45:14,068] Trial 10 finished with value: 0.38271358711877246 and parameters: {'kernel': 'rbf', 'C': 9.833333728898696, 'epsilon': 0.14448909357960782, 'gamma': 'scale'}. Best is trial 10 with value: 0.38271358711877246.
[I 2025-07-11 20:45:14,154] Trial 11 finished with value: 0.383602134960913 and parameters: {'kernel': 'rbf', 'C': 9.992382982110051, 'epsilon': 0.14738520593876964, 'gamma': 'scale'}. Best is trial 11 with value: 0.383602134960913.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.72 | R2: 0.38
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.72 | R2: 0.38
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 20:45:14,238] Trial 12 finished with value: 0.38023259334614223 and parameters: {'kernel': 'rbf', 'C': 9.551563017683744, 'epsilon': 0.15869445514250627, 'gamma': 'scale'}. Best is trial 11 with value: 0.383602134960913.
[I 2025-07-11 20:45:14,320] Trial 13 finished with value: 0.3815741743978387 and parameters: {'kernel': 'rbf', 'C': 9.824337405140149, 'epsilon': 0.1674592952695715, 'gamma': 'scale'}. Best is trial 11 with value: 0.383602134960913.
[I 2025-07-11 20:45:14,406] Trial 14 finished with value: 0.2802322308432398 and parameters: {'kernel': 'rbf', 'C': 4.294280736651481, 'epsilon': 0.016693973111879964, 'gamma': 'scale'}. Best is trial 11 with value: 0.383602134960913.

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.73 | R2: 0.38
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.73 | R2: 0.38
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.94 | R2: 0.28
Fold 1

[I 2025-07-11 20:45:14,491] Trial 15 finished with value: 0.2978249178773157 and parameters: {'kernel': 'rbf', 'C': 5.054123536077245, 'epsilon': 0.11554019487096659, 'gamma': 'scale'}. Best is trial 11 with value: 0.383602134960913.
[I 2025-07-11 20:45:14,568] Trial 16 finished with value: 0.24229979551763736 and parameters: {'kernel': 'rbf', 'C': 2.201334691713396, 'epsilon': 0.17215374904791497, 'gamma': 'scale'}. Best is trial 11 with value: 0.383602134960913.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.90 | R2: 0.30
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.02 | R2: 0.24
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 20:45:14,651] Trial 17 finished with value: 0.34301640254947585 and parameters: {'kernel': 'rbf', 'C': 6.822740268044837, 'epsilon': 0.13417416793781284, 'gamma': 'scale'}. Best is trial 11 with value: 0.383602134960913.
[I 2025-07-11 20:45:14,728] Trial 18 finished with value: 0.23833252554953466 and parameters: {'kernel': 'rbf', 'C': 2.1806490359429636, 'epsilon': 0.0890120074608349, 'gamma': 'auto'}. Best is trial 11 with value: 0.383602134960913.
[I 2025-07-11 20:45:14,813] Trial 19 finished with value: 0.32199434631330803 and parameters: {'kernel': 'rbf', 'C': 6.0122686601752635, 'epsilon': 0.12340641187845658, 'gamma': 'scale'}. Best is trial 11 with value: 0.383602134960913.

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.81 | R2: 0.34
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.03 | R2: 0.24
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.85 | R2: 0.32
Fold 1

[I 2025-07-11 20:45:14,892] Trial 20 finished with value: 0.22572988642333902 and parameters: {'kernel': 'rbf', 'C': 1.6936107346766862, 'epsilon': 0.15222879302710302, 'gamma': 'scale'}. Best is trial 11 with value: 0.383602134960913.
[I 2025-07-11 20:45:14,975] Trial 21 finished with value: 0.38223401456366535 and parameters: {'kernel': 'rbf', 'C': 9.95838231742186, 'epsilon': 0.17272080965871422, 'gamma': 'scale'}. Best is trial 11 with value: 0.383602134960913.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.05 | R2: 0.23
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.72 | R2: 0.38
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:45:15,055] Trial 22 finished with value: 0.35337375104817603 and parameters: {'kernel': 'rbf', 'C': 7.285310716361751, 'epsilon': 0.17818088073106636, 'gamma': 'scale'}. Best is trial 11 with value: 0.383602134960913.
[I 2025-07-11 20:45:15,135] Trial 23 finished with value: 0.3808818413044418 and parameters: {'kernel': 'rbf', 'C': 9.776750988130214, 'epsilon': 0.17738022275245705, 'gamma': 'scale'}. Best is trial 11 with value: 0.383602134960913.
[I 2025-07-11 20:45:15,216] Trial 24 finished with value: 0.28121418047607905 and parameters: {'kernel': 'rbf', 'C': 4.105531841586406, 'epsilon': 0.1497708202877473, 'gamma': 'scale'}. Best is trial 11 with value: 0.383602134960913.
[I 2025-07-11 20:45:15,217] A new study created in memory with name: no-name-e21fc766-ec73-4bcc-bd9a-1687d334eeee

Running time: 0.1 sec
OOF RMSE: 2.79 | R2: 0.35
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.73 | R2: 0.38
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.94 | R2: 0.28

✅ SVR - Mejor R2: 0.38
📋 Parámetros: {'kernel': 'rbf', 'C': 9.992382982110051, 'epsilon': 0.14738520593876964, 'gamma': 'scale'}

Buscando mejores hiperparámetros para KNN...
Fold 1
Fold 2
Fold 3

[I 2025-07-11 20:45:15,282] Trial 0 finished with value: 0.5756585622556867 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'leaf_size': 27}. Best is trial 0 with value: 0.5756585622556867.
[I 2025-07-11 20:45:15,344] Trial 1 finished with value: 0.4325992277147289 and parameters: {'n_neighbors': 15, 'weights': 'uniform', 'leaf_size': 33}. Best is trial 0 with value: 0.5756585622556867.
[I 2025-07-11 20:45:15,405] Trial 2 finished with value: 0.5224301782870312 and parameters: {'n_neighbors': 4, 'weights': 'uniform', 'leaf_size': 29}. Best is trial 0 with value: 0.5756585622556867.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.26 | R2: 0.58
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.61 | R2: 0.43
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.40 | R2: 0.52
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:45:15,469] Trial 3 finished with value: 0.4700886788278772 and parameters: {'n_neighbors': 12, 'weights': 'distance', 'leaf_size': 16}. Best is trial 0 with value: 0.5756585622556867.
[I 2025-07-11 20:45:15,535] Trial 4 finished with value: 0.4325992277147289 and parameters: {'n_neighbors': 15, 'weights': 'uniform', 'leaf_size': 29}. Best is trial 0 with value: 0.5756585622556867.
[I 2025-07-11 20:45:15,597] Trial 5 finished with value: 0.46757387172243536 and parameters: {'n_neighbors': 10, 'weights': 'distance', 'leaf_size': 15}. Best is trial 0 with value: 0.5756585622556867.
[I 2025-07-11 20:45:15,653] Trial 6 finished with value: 0.4323503187297095 and parameters: {'n_neighbors': 9, 'weights': 'uniform', 'leaf_size': 27}. Best is trial 0 with value: 0.5756585622556867.

Running time: 0.1 sec
OOF RMSE: 2.52 | R2: 0.47
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.61 | R2: 0.43
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.53 | R2: 0.47
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.61 | R2: 0.43
Fold 1
Fold 2

[I 2025-07-11 20:45:15,713] Trial 7 finished with value: 0.5025137030531401 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'leaf_size': 22}. Best is trial 0 with value: 0.5756585622556867.
[I 2025-07-11 20:45:15,777] Trial 8 finished with value: 0.4714989741266552 and parameters: {'n_neighbors': 13, 'weights': 'distance', 'leaf_size': 33}. Best is trial 0 with value: 0.5756585622556867.
[I 2025-07-11 20:45:15,842] Trial 9 finished with value: 0.43680101075650635 and parameters: {'n_neighbors': 7, 'weights': 'uniform', 'leaf_size': 18}. Best is trial 0 with value: 0.5756585622556867.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.45 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.52 | R2: 0.47
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.60 | R2: 0.44
Fold 1
Fold 2
Fold 3

[I 2025-07-11 20:45:15,951] Trial 10 finished with value: 0.6318809653725268 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 40}. Best is trial 10 with value: 0.6318809653725268.
[I 2025-07-11 20:45:16,024] Trial 11 finished with value: 0.6318809653725268 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 39}. Best is trial 10 with value: 0.6318809653725268.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.10 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.10 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:45:16,100] Trial 12 finished with value: 0.6318809653725268 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 38}. Best is trial 10 with value: 0.6318809653725268.
[I 2025-07-11 20:45:16,173] Trial 13 finished with value: 0.5218619559852689 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'leaf_size': 39}. Best is trial 10 with value: 0.6318809653725268.
[I 2025-07-11 20:45:16,244] Trial 14 finished with value: 0.5588039608590836 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'leaf_size': 10}. Best is trial 10 with value: 0.6318809653725268.

Running time: 0.1 sec
OOF RMSE: 2.10 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.40 | R2: 0.52
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.30 | R2: 0.56
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:45:16,309] Trial 15 finished with value: 0.6318809653725268 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 40}. Best is trial 10 with value: 0.6318809653725268.
[I 2025-07-11 20:45:16,378] Trial 16 finished with value: 0.5218619559852689 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'leaf_size': 34}. Best is trial 10 with value: 0.6318809653725268.
[I 2025-07-11 20:45:16,449] Trial 17 finished with value: 0.4880917868448852 and parameters: {'n_neighbors': 9, 'weights': 'distance', 'leaf_size': 36}. Best is trial 10 with value: 0.6318809653725268.

Running time: 0.1 sec
OOF RMSE: 2.10 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.40 | R2: 0.52
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.48 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:45:16,514] Trial 18 finished with value: 0.6318809653725268 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 36}. Best is trial 10 with value: 0.6318809653725268.
[I 2025-07-11 20:45:16,583] Trial 19 finished with value: 0.5588039608590836 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'leaf_size': 23}. Best is trial 10 with value: 0.6318809653725268.
[I 2025-07-11 20:45:16,656] Trial 20 finished with value: 0.4933043947429039 and parameters: {'n_neighbors': 8, 'weights': 'distance', 'leaf_size': 31}. Best is trial 10 with value: 0.6318809653725268.

Running time: 0.1 sec
OOF RMSE: 2.10 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.30 | R2: 0.56
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.47 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:45:16,721] Trial 21 finished with value: 0.6318809653725268 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 38}. Best is trial 10 with value: 0.6318809653725268.
[I 2025-07-11 20:45:16,793] Trial 22 finished with value: 0.5756585622556867 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'leaf_size': 40}. Best is trial 10 with value: 0.6318809653725268.
[I 2025-07-11 20:45:16,863] Trial 23 finished with value: 0.5588039608590836 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'leaf_size': 36}. Best is trial 10 with value: 0.6318809653725268.

Running time: 0.1 sec
OOF RMSE: 2.10 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.26 | R2: 0.58
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.30 | R2: 0.56
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:45:16,926] Trial 24 finished with value: 0.6318809653725268 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 37}. Best is trial 10 with value: 0.6318809653725268.
[I 2025-07-11 20:45:16,927] A new study created in memory with name: no-name-4409d012-9562-44a0-b3d8-acb94ee55767
[I 2025-07-11 20:45:17,005] Trial 0 finished with value: -0.06968788456602959 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 0 with value: -0.06968788456602959.
[I 2025-07-11 20:45:17,105] Trial 1 finished with value: 0.2903151114057855 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.2903151114057855.

Running time: 0.1 sec
OOF RMSE: 2.10 | R2: 0.63

✅ KNN - Mejor R2: 0.63
📋 Parámetros: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 40}

Buscando mejores hiperparámetros para LR...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.59 | R2: -0.07
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.92 | R2: 0.29
Fold 1
Fold 2

[I 2025-07-11 20:45:17,162] Trial 2 finished with value: 0.2903151114057855 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.2903151114057855.
[I 2025-07-11 20:45:17,298] Trial 3 finished with value: -0.06968788456602959 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 1 with value: 0.2903151114057855.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.92 | R2: 0.29
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.59 | R2: -0.07
Fold 1
Fold 2

[I 2025-07-11 20:45:17,374] Trial 4 finished with value: 0.2903151114057855 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.2903151114057855.
[I 2025-07-11 20:45:17,435] Trial 5 finished with value: 0.2903151114057855 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.2903151114057855.
[I 2025-07-11 20:45:17,523] Trial 6 finished with value: -0.06968788456602959 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 1 with value: 0.2903151114057855.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.92 | R2: 0.29
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.92 | R2: 0.29
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.59 | R2: -0.07
Fold 1

[I 2025-07-11 20:45:17,604] Trial 7 finished with value: -0.06968788456602959 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 1 with value: 0.2903151114057855.
[I 2025-07-11 20:45:17,690] Trial 8 finished with value: -0.06968788456602959 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 1 with value: 0.2903151114057855.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.59 | R2: -0.07
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.59 | R2: -0.07
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 20:45:17,767] Trial 9 finished with value: 0.2903151114057855 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.2903151114057855.
[I 2025-07-11 20:45:17,831] Trial 10 finished with value: 0.2903151114057855 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.2903151114057855.
[I 2025-07-11 20:45:17,893] Trial 11 finished with value: 0.2903151114057855 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.2903151114057855.

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.92 | R2: 0.29
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.92 | R2: 0.29
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.92 | R2: 0.29
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:45:17,959] Trial 12 finished with value: 0.2903151114057855 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.2903151114057855.
[I 2025-07-11 20:45:18,021] Trial 13 finished with value: 0.2903151114057855 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.2903151114057855.
[I 2025-07-11 20:45:18,085] Trial 14 finished with value: 0.2903151114057855 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.2903151114057855.
[I 2025-07-11 20:45:18,142] Trial 15 finished with value: 0.2903151114057855 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.2903151114057855.

Running time: 0.1 sec
OOF RMSE: 2.92 | R2: 0.29
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.92 | R2: 0.29
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.92 | R2: 0.29
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.92 | R2: 0.29
Fold 1
Fold 2

[I 2025-07-11 20:45:18,203] Trial 16 finished with value: 0.2903151114057855 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.2903151114057855.
[I 2025-07-11 20:45:18,269] Trial 17 finished with value: 0.2903151114057855 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.2903151114057855.
[I 2025-07-11 20:45:18,332] Trial 18 finished with value: 0.2903151114057855 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.2903151114057855.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.92 | R2: 0.29
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.92 | R2: 0.29
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.92 | R2: 0.29
Fold 1
Fold 2
Fold 3

[I 2025-07-11 20:45:18,396] Trial 19 finished with value: 0.2903151114057855 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.2903151114057855.
[I 2025-07-11 20:45:18,458] Trial 20 finished with value: 0.2903151114057855 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.2903151114057855.
[I 2025-07-11 20:45:18,520] Trial 21 finished with value: 0.2903151114057855 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.2903151114057855.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.92 | R2: 0.29
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.92 | R2: 0.29
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.92 | R2: 0.29
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:45:18,584] Trial 22 finished with value: 0.2903151114057855 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.2903151114057855.
[I 2025-07-11 20:45:18,645] Trial 23 finished with value: 0.2903151114057855 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.2903151114057855.
[I 2025-07-11 20:45:18,711] Trial 24 finished with value: 0.2903151114057855 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.2903151114057855.
[I 2025-07-11 20:45:18,712] A new study created in memory with name: no-name-881d0600-d668-4b47-bbb1-8b6a4bca69eb

Running time: 0.1 sec
OOF RMSE: 2.92 | R2: 0.29
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.92 | R2: 0.29
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.92 | R2: 0.29

✅ LR - Mejor R2: 0.29
📋 Parámetros: {'fit_intercept': False, 'positive': True}

Buscando mejores hiperparámetros para RF...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:45:21,052] Trial 0 finished with value: 0.14985308629587502 and parameters: {'n_estimators': 100, 'max_depth': 13, 'min_samples_split': 10, 'min_samples_leaf': 5, 'bootstrap': False}. Best is trial 0 with value: 0.14985308629587502.

Running time: 2.3 sec
OOF RMSE: 3.20 | R2: 0.15
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:45:28,474] Trial 1 finished with value: 0.06306231264747786 and parameters: {'n_estimators': 300, 'max_depth': 8, 'min_samples_split': 5, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 0 with value: 0.14985308629587502.

Running time: 7.4 sec
OOF RMSE: 3.36 | R2: 0.06
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:45:31,069] Trial 2 finished with value: 0.13061651809863872 and parameters: {'n_estimators': 100, 'max_depth': 10, 'min_samples_split': 9, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 0 with value: 0.14985308629587502.

Running time: 2.6 sec
OOF RMSE: 3.23 | R2: 0.13
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:45:38,713] Trial 3 finished with value: 0.37892183701481164 and parameters: {'n_estimators': 500, 'max_depth': 9, 'min_samples_split': 6, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 3 with value: 0.37892183701481164.

Running time: 7.6 sec
OOF RMSE: 2.73 | R2: 0.38
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:45:46,437] Trial 4 finished with value: 0.15462976849593268 and parameters: {'n_estimators': 300, 'max_depth': 13, 'min_samples_split': 9, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 3 with value: 0.37892183701481164.

Running time: 7.7 sec
OOF RMSE: 3.19 | R2: 0.15
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:45:54,983] Trial 5 finished with value: 0.4104054170459709 and parameters: {'n_estimators': 500, 'max_depth': 15, 'min_samples_split': 9, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 5 with value: 0.4104054170459709.

Running time: 8.5 sec
OOF RMSE: 2.66 | R2: 0.41
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:46:06,535] Trial 6 finished with value: 0.14861925266731146 and parameters: {'n_estimators': 500, 'max_depth': 11, 'min_samples_split': 4, 'min_samples_leaf': 5, 'bootstrap': False}. Best is trial 5 with value: 0.4104054170459709.

Running time: 11.5 sec
OOF RMSE: 3.20 | R2: 0.15
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:46:08,068] Trial 7 finished with value: 0.3972749165105256 and parameters: {'n_estimators': 100, 'max_depth': 7, 'min_samples_split': 8, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 5 with value: 0.4104054170459709.

Running time: 1.5 sec
OOF RMSE: 2.69 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:46:09,346] Trial 8 finished with value: 0.37137424592492563 and parameters: {'n_estimators': 100, 'max_depth': 5, 'min_samples_split': 4, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 5 with value: 0.4104054170459709.

Running time: 1.3 sec
OOF RMSE: 2.75 | R2: 0.37
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:46:15,928] Trial 9 finished with value: 0.3702303111029348 and parameters: {'n_estimators': 500, 'max_depth': 6, 'min_samples_split': 9, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 5 with value: 0.4104054170459709.

Running time: 6.6 sec
OOF RMSE: 2.75 | R2: 0.37
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:46:26,694] Trial 10 finished with value: 0.42382314695850065 and parameters: {'n_estimators': 500, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 10 with value: 0.42382314695850065.

Running time: 10.8 sec
OOF RMSE: 2.63 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:46:37,493] Trial 11 finished with value: 0.42382314695850065 and parameters: {'n_estimators': 500, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 10 with value: 0.42382314695850065.

Running time: 10.8 sec
OOF RMSE: 2.63 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:46:48,329] Trial 12 finished with value: 0.42382314695850065 and parameters: {'n_estimators': 500, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 10 with value: 0.42382314695850065.

Running time: 10.8 sec
OOF RMSE: 2.63 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:46:58,967] Trial 13 finished with value: 0.4245139158711353 and parameters: {'n_estimators': 500, 'max_depth': 13, 'min_samples_split': 2, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 13 with value: 0.4245139158711353.

Running time: 10.6 sec
OOF RMSE: 2.63 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:47:09,347] Trial 14 finished with value: 0.4202408808957493 and parameters: {'n_estimators': 500, 'max_depth': 13, 'min_samples_split': 3, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 13 with value: 0.4245139158711353.

Running time: 10.4 sec
OOF RMSE: 2.64 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:47:19,543] Trial 15 finished with value: 0.4146262163539278 and parameters: {'n_estimators': 500, 'max_depth': 12, 'min_samples_split': 3, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 13 with value: 0.4245139158711353.

Running time: 10.2 sec
OOF RMSE: 2.65 | R2: 0.41
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:47:25,225] Trial 16 finished with value: 0.40964341558179906 and parameters: {'n_estimators': 300, 'max_depth': 14, 'min_samples_split': 7, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 13 with value: 0.4245139158711353.

Running time: 5.7 sec
OOF RMSE: 2.66 | R2: 0.41
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:47:32,884] Trial 17 finished with value: 0.379227715998525 and parameters: {'n_estimators': 500, 'max_depth': 11, 'min_samples_split': 2, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 13 with value: 0.4245139158711353.

Running time: 7.7 sec
OOF RMSE: 2.73 | R2: 0.38
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:47:41,247] Trial 18 finished with value: 0.3911871911237986 and parameters: {'n_estimators': 500, 'max_depth': 14, 'min_samples_split': 4, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 13 with value: 0.4245139158711353.

Running time: 8.4 sec
OOF RMSE: 2.70 | R2: 0.39
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:47:46,632] Trial 19 finished with value: 0.4018254967856011 and parameters: {'n_estimators': 300, 'max_depth': 12, 'min_samples_split': 6, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 13 with value: 0.4245139158711353.

Running time: 5.4 sec
OOF RMSE: 2.68 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:47:56,975] Trial 20 finished with value: 0.417106366802522 and parameters: {'n_estimators': 500, 'max_depth': 14, 'min_samples_split': 3, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 13 with value: 0.4245139158711353.

Running time: 10.3 sec
OOF RMSE: 2.65 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:48:07,737] Trial 21 finished with value: 0.42382314695850065 and parameters: {'n_estimators': 500, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 13 with value: 0.4245139158711353.

Running time: 10.8 sec
OOF RMSE: 2.63 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:48:18,465] Trial 22 finished with value: 0.42382314695850065 and parameters: {'n_estimators': 500, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 13 with value: 0.4245139158711353.

Running time: 10.7 sec
OOF RMSE: 2.63 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:48:27,696] Trial 23 finished with value: 0.40710404962104507 and parameters: {'n_estimators': 500, 'max_depth': 14, 'min_samples_split': 3, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 13 with value: 0.4245139158711353.

Running time: 9.2 sec
OOF RMSE: 2.67 | R2: 0.41
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:48:37,335] Trial 24 finished with value: 0.41419397661210733 and parameters: {'n_estimators': 500, 'max_depth': 12, 'min_samples_split': 5, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 13 with value: 0.4245139158711353.
[I 2025-07-11 20:48:37,336] A new study created in memory with name: no-name-4a83cf2f-d151-49b3-8478-cc69db498a7a

Running time: 9.6 sec
OOF RMSE: 2.65 | R2: 0.41

✅ RF - Mejor R2: 0.42
📋 Parámetros: {'n_estimators': 500, 'max_depth': 13, 'min_samples_split': 2, 'min_samples_leaf': 1, 'bootstrap': True}

Buscando mejores hiperparámetros para CAT...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:48:44,838] Trial 0 finished with value: 0.471478583103458 and parameters: {'iterations': 500, 'learning_rate': 0.01962057318203599, 'depth': 7, 'l2_leaf_reg': 9.957670068698741}. Best is trial 0 with value: 0.471478583103458.

Running time: 7.5 sec
OOF RMSE: 2.52 | R2: 0.47
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:48:47,652] Trial 1 finished with value: 0.47201686817065136 and parameters: {'iterations': 1000, 'learning_rate': 0.02101124125915683, 'depth': 4, 'l2_leaf_reg': 5.137761626405439}. Best is trial 1 with value: 0.47201686817065136.

Running time: 2.8 sec
OOF RMSE: 2.52 | R2: 0.47
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:53:47,801] Trial 2 finished with value: 0.4316595232636766 and parameters: {'iterations': 2000, 'learning_rate': 0.08459200511226185, 'depth': 10, 'l2_leaf_reg': 6.287877839769403}. Best is trial 1 with value: 0.47201686817065136.

Running time: 300.1 sec
OOF RMSE: 2.61 | R2: 0.43
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:55:13,490] Trial 3 finished with value: 0.49999428056798245 and parameters: {'iterations': 1000, 'learning_rate': 0.010359602485554016, 'depth': 9, 'l2_leaf_reg': 2.556163131717831}. Best is trial 3 with value: 0.49999428056798245.

Running time: 85.7 sec
OOF RMSE: 2.45 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:56:41,496] Trial 4 finished with value: 0.4797630012965707 and parameters: {'iterations': 1000, 'learning_rate': 0.09159851229476745, 'depth': 9, 'l2_leaf_reg': 6.980319482953737}. Best is trial 3 with value: 0.49999428056798245.

Running time: 88.0 sec
OOF RMSE: 2.50 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 20:56:43,085] Trial 5 finished with value: 0.4382548006421362 and parameters: {'iterations': 500, 'learning_rate': 0.042665094825283585, 'depth': 4, 'l2_leaf_reg': 7.992430866629139}. Best is trial 3 with value: 0.49999428056798245.

Running time: 1.6 sec
OOF RMSE: 2.60 | R2: 0.44
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:01:39,014] Trial 6 finished with value: 0.46614914510803884 and parameters: {'iterations': 2000, 'learning_rate': 0.017128257902922765, 'depth': 10, 'l2_leaf_reg': 6.528403615809237}. Best is trial 3 with value: 0.49999428056798245.
[I 2025-07-11 21:01:39,015] A new study created in memory with name: no-name-9391d0f2-2bb9-4959-a46f-5ed599be8f64
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.277e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.179e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.217e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.628e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.265e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 21:01:39,139] Trial 0 finished with value: 0.21543734082513732 and parameters: {'alpha': 0.00010260362908057558, 'l1_ratio': 0.6924580548668173}. Best is trial 0 with value: 0.21543734082513732.

Running time: 295.9 sec
OOF RMSE: 2.53 | R2: 0.47

✅ CAT - Mejor R2: 0.50
📋 Parámetros: {'iterations': 1000, 'learning_rate': 0.010359602485554016, 'depth': 9, 'l2_leaf_reg': 2.556163131717831}

Buscando mejores hiperparámetros para EN...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.07 | R2: 0.22
Fold 1
Fold 2
Fold 3

[I 2025-07-11 21:01:39,251] Trial 1 finished with value: 0.4195364924172734 and parameters: {'alpha': 0.4906870966234411, 'l1_ratio': 0.1281957482536077}. Best is trial 1 with value: 0.4195364924172734.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.64 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.213e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.170e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.094e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.629e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.214e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 21:01:39,488] Trial 2 finished with value: 0.22684624977229895 and parameters: {'alpha': 0.00033270143493289436, 'l1_ratio': 0.4059031248040126}. Best is trial 1 with value: 0.4195364924172734.
[I 2025-07-11 21:01:39,595] Trial 3 finished with value: 0.39630713289330766 and parameters: {'alpha': 0.028197786920047475, 'l1_ratio': 0.7991082383469978}. Best is trial 1 with value: 0.4195364924172734.

Fold 5
Running time: 0.2 sec
OOF RMSE: 3.05 | R2: 0.23
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.69 | R2: 0.40
Fold 1
Fold 2
Fold 3

[I 2025-07-11 21:01:39,698] Trial 4 finished with value: 0.40405413319862016 and parameters: {'alpha': 0.05306658125248114, 'l1_ratio': 0.2910507984173055}. Best is trial 1 with value: 0.4195364924172734.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.073e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.260e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.896e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.786e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.755e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 21:01:39,837] Trial 5 finished with value: 0.3536000608508557 and parameters: {'alpha': 0.004813586128947276, 'l1_ratio': 0.09807891901469701}. Best is trial 1 with value: 0.4195364924172734.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.68 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.79 | R2: 0.35
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.493e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.937e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.096e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.281e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.984e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 21:01:39,975] Trial 6 finished with value: 0.2499869016560442 and parameters: {'alpha': 0.0013545852556395715, 'l1_ratio': 0.707066868536043}. Best is trial 1 with value: 0.4195364924172734.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.516e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.985e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.964e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.00 | R2: 0.25
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.262e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.664e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 21:01:40,099] Trial 7 finished with value: 0.23824262602517488 and parameters: {'alpha': 0.001254104434677455, 'l1_ratio': 0.8844254651050448}. Best is trial 1 with value: 0.4195364924172734.
[I 2025-07-11 21:01:40,187] Trial 8 finished with value: 0.4216249337178678 and parameters: {'alpha': 0.6285630308232208, 'l1_ratio': 0.04777623734507519}. Best is trial 8 with value: 0.4216249337178678.
[I 2025-07-11 21:01:40,275] Trial 9 finished with value: -0.00027817151752640434 and parameters: {'alpha': 9.522473853747657, 'l1_ratio': 0.7323246421679567}. Best is trial 8 with value: 0.4216249337178678.

Fold 5
Running time: 0.1 sec
OOF RMSE: 3.03 | R2: 0.24
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.64 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.47 | R2: -0.00

[I 2025-07-11 21:01:40,393] Trial 10 finished with value: 0.4108550771610069 and parameters: {'alpha': 2.441171203513847, 'l1_ratio': 0.028477578656636804}. Best is trial 8 with value: 0.4216249337178678.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.66 | R2: 0.41
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:01:40,505] Trial 11 finished with value: 0.4182769271499732 and parameters: {'alpha': 0.4759331376272684, 'l1_ratio': 0.18895315465798523}. Best is trial 8 with value: 0.4216249337178678.
[I 2025-07-11 21:01:40,598] Trial 12 finished with value: 0.4157490924195695 and parameters: {'alpha': 0.21871544532612677, 'l1_ratio': 0.49502052095202187}. Best is trial 8 with value: 0.4216249337178678.

Running time: 0.1 sec
OOF RMSE: 2.64 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.65 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 21:01:40,744] Trial 13 finished with value: 0.4123024147055381 and parameters: {'alpha': 0.744305410042735, 'l1_ratio': 0.25353947934651855}. Best is trial 8 with value: 0.4216249337178678.

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.66 | R2: 0.41
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.527e+01, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.069e+00, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.513e+00, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.922e+00, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.328e+01, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 21:01:40,954] Trial 14 finished with value: 0.40604571973384596 and parameters: {'alpha': 0.08140236832618065, 'l1_ratio': 0.016099794120410654}. Best is trial 8 with value: 0.4216249337178678.
[I 2025-07-11 21:01:41,046] Trial 15 finished with value: 0.39476637030727757 and parameters: {'alpha': 2.276773358950576, 'l1_ratio': 0.15739554165382108}. Best is trial 8 with value: 0.4216249337178678.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.705e+00, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.204e-01, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.514e-01, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.875e-01, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(

Running time: 0.2 sec
OOF RMSE: 2.67 | R2: 0.41
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.70 | R2: 0.39
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.776e+01, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 21:01:41,164] Trial 16 finished with value: 0.38714176403451817 and parameters: {'alpha': 0.018867376781321932, 'l1_ratio': 0.359300334567582}. Best is trial 8 with value: 0.4216249337178678.
[I 2025-07-11 21:01:41,261] Trial 17 finished with value: 0.4151728513918862 and parameters: {'alpha': 0.1802471655601975, 'l1_ratio': 0.5623615847941278}. Best is trial 8 with value: 0.4216249337178678.
[I 2025-07-11 21:01:41,347] Trial 18 finished with value: 0.24222710394653102 and parameters: {'alpha': 9.684063879190774, 'l1_ratio': 0.12206667146993264}. Best is trial 8 with value: 0.4216249337178678.

Running time: 0.1 sec
OOF RMSE: 2.71 | R2: 0.39
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.65 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.02 | R2: 0.24
Fold 1

[I 2025-07-11 21:01:41,506] Trial 19 finished with value: 0.42036945472530185 and parameters: {'alpha': 1.4897685095176636, 'l1_ratio': 0.004671031237320836}. Best is trial 8 with value: 0.4216249337178678.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 2.64 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 21:01:41,615] Trial 20 finished with value: 0.4146934112719104 and parameters: {'alpha': 2.420589723343434, 'l1_ratio': 0.006636107314277662}. Best is trial 8 with value: 0.4216249337178678.
[I 2025-07-11 21:01:41,722] Trial 21 finished with value: 0.41360160484633246 and parameters: {'alpha': 0.7022744764215569, 'l1_ratio': 0.2240113474165994}. Best is trial 8 with value: 0.4216249337178678.

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.65 | R2: 0.41
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.65 | R2: 0.41
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 21:01:41,825] Trial 22 finished with value: 0.40991520078112464 and parameters: {'alpha': 1.6723933285627495, 'l1_ratio': 0.09675569788305172}. Best is trial 8 with value: 0.4216249337178678.
[I 2025-07-11 21:01:41,950] Trial 23 finished with value: 0.4065098175102495 and parameters: {'alpha': 0.21149057436841565, 'l1_ratio': 0.9952601999386561}. Best is trial 8 with value: 0.4216249337178678.

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.66 | R2: 0.41
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.67 | R2: 0.41
Fold 1
Fold 2
Fold 3

[I 2025-07-11 21:01:42,049] Trial 24 finished with value: 0.40910176527537623 and parameters: {'alpha': 0.8546649712081238, 'l1_ratio': 0.3393540849470657}. Best is trial 8 with value: 0.4216249337178678.
[I 2025-07-11 21:01:42,050] A new study created in memory with name: no-name-c4c59d41-6ae4-4061-93d8-a0b6d5713f8a

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.66 | R2: 0.41

✅ EN - Mejor R2: 0.42
📋 Parámetros: {'alpha': 0.6285630308232208, 'l1_ratio': 0.04777623734507519}

🔍 Optimizando en C2X_rhown_3x3_depth_lt_1...
Buscando mejores hiperparámetros para XGB...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:01:52,188] Trial 0 finished with value: 0.36198640228859247 and parameters: {'n_estimators': 2000, 'learning_rate': 0.03682722388552221, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.9609365884279788, 'colsample_bytree': 0.8708506321524065}. Best is trial 0 with value: 0.36198640228859247.

Running time: 10.1 sec
OOF RMSE: 2.77 | R2: 0.36
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:01:55,074] Trial 1 finished with value: 0.44481343873251555 and parameters: {'n_estimators': 500, 'learning_rate': 0.013222859538658765, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.7416342314880738, 'colsample_bytree': 0.626898071644842}. Best is trial 1 with value: 0.44481343873251555.

Running time: 2.9 sec
OOF RMSE: 2.58 | R2: 0.44
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:02:05,489] Trial 2 finished with value: 0.20682985487663552 and parameters: {'n_estimators': 2000, 'learning_rate': 0.024720666120720578, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.9861295774484372, 'colsample_bytree': 0.7836113819727804}. Best is trial 1 with value: 0.44481343873251555.

Running time: 10.4 sec
OOF RMSE: 3.09 | R2: 0.21
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:02:15,349] Trial 3 finished with value: 0.4261806720671356 and parameters: {'n_estimators': 2000, 'learning_rate': 0.0754967199554934, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.6824106054202637, 'colsample_bytree': 0.8223680816593013}. Best is trial 1 with value: 0.44481343873251555.

Running time: 9.9 sec
OOF RMSE: 2.63 | R2: 0.43
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:02:19,592] Trial 4 finished with value: 0.4046721233430658 and parameters: {'n_estimators': 500, 'learning_rate': 0.009381028753703826, 'max_depth': 8, 'min_child_weight': 3, 'subsample': 0.8942909829062418, 'colsample_bytree': 0.9633334007586118}. Best is trial 1 with value: 0.44481343873251555.

Running time: 4.2 sec
OOF RMSE: 2.67 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:02:22,661] Trial 5 finished with value: 0.4232116730654667 and parameters: {'n_estimators': 500, 'learning_rate': 0.02382126539482201, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.8389932232948, 'colsample_bytree': 0.9366246485219896}. Best is trial 1 with value: 0.44481343873251555.

Running time: 3.1 sec
OOF RMSE: 2.63 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:02:29,838] Trial 6 finished with value: 0.23498192093068304 and parameters: {'n_estimators': 1000, 'learning_rate': 0.03357600200829407, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.9714656781467433, 'colsample_bytree': 0.9074237113773482}. Best is trial 1 with value: 0.44481343873251555.

Running time: 7.2 sec
OOF RMSE: 3.03 | R2: 0.23
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:02:33,494] Trial 7 finished with value: 0.3884564733119553 and parameters: {'n_estimators': 1000, 'learning_rate': 0.013839689295960932, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.9425137654429965, 'colsample_bytree': 0.6339918373959871}. Best is trial 1 with value: 0.44481343873251555.

Running time: 3.7 sec
OOF RMSE: 2.71 | R2: 0.39
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:02:36,239] Trial 8 finished with value: 0.41825331724299597 and parameters: {'n_estimators': 500, 'learning_rate': 0.021766611913401214, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.7744432946802862, 'colsample_bytree': 0.7628281367200033}. Best is trial 1 with value: 0.44481343873251555.

Running time: 2.7 sec
OOF RMSE: 2.64 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:02:45,948] Trial 9 finished with value: 0.4228206009317055 and parameters: {'n_estimators': 2000, 'learning_rate': 0.07130165065537954, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.8287956709702842, 'colsample_bytree': 0.9275470528835905}. Best is trial 1 with value: 0.44481343873251555.

Running time: 9.7 sec
OOF RMSE: 2.63 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:02:49,487] Trial 10 finished with value: 0.4458183677147881 and parameters: {'n_estimators': 500, 'learning_rate': 0.005795378264103542, 'max_depth': 8, 'min_child_weight': 1, 'subsample': 0.6491202650452267, 'colsample_bytree': 0.6030411146905654}. Best is trial 10 with value: 0.4458183677147881.

Running time: 3.5 sec
OOF RMSE: 2.58 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:02:52,958] Trial 11 finished with value: 0.4447362850766008 and parameters: {'n_estimators': 500, 'learning_rate': 0.005380567007029554, 'max_depth': 8, 'min_child_weight': 1, 'subsample': 0.6290023092614642, 'colsample_bytree': 0.6014608256392802}. Best is trial 10 with value: 0.4458183677147881.

Running time: 3.5 sec
OOF RMSE: 2.58 | R2: 0.44
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:02:56,697] Trial 12 finished with value: 0.4379012647745306 and parameters: {'n_estimators': 500, 'learning_rate': 0.005299206173430888, 'max_depth': 8, 'min_child_weight': 1, 'subsample': 0.7182811960671917, 'colsample_bytree': 0.6814037830918959}. Best is trial 10 with value: 0.4458183677147881.

Running time: 3.7 sec
OOF RMSE: 2.60 | R2: 0.44
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:03:00,496] Trial 13 finished with value: 0.44169598025181955 and parameters: {'n_estimators': 500, 'learning_rate': 0.00953111740951128, 'max_depth': 8, 'min_child_weight': 1, 'subsample': 0.6064987063433913, 'colsample_bytree': 0.7122734205621044}. Best is trial 10 with value: 0.4458183677147881.

Running time: 3.8 sec
OOF RMSE: 2.59 | R2: 0.44
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:03:03,248] Trial 14 finished with value: 0.4657161371982982 and parameters: {'n_estimators': 500, 'learning_rate': 0.009751190845187654, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.7304986036877639, 'colsample_bytree': 0.6616040553358405}. Best is trial 14 with value: 0.4657161371982982.

Running time: 2.7 sec
OOF RMSE: 2.53 | R2: 0.47
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:03:06,345] Trial 15 finished with value: 0.45927587432031547 and parameters: {'n_estimators': 500, 'learning_rate': 0.00837139158306242, 'max_depth': 8, 'min_child_weight': 3, 'subsample': 0.6631149692679721, 'colsample_bytree': 0.6913385739838523}. Best is trial 14 with value: 0.4657161371982982.

Running time: 3.1 sec
OOF RMSE: 2.55 | R2: 0.46
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:03:12,724] Trial 16 finished with value: 0.4614334157566329 and parameters: {'n_estimators': 1000, 'learning_rate': 0.009006218241096355, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.6862240100787174, 'colsample_bytree': 0.6938507136149636}. Best is trial 14 with value: 0.4657161371982982.

Running time: 6.4 sec
OOF RMSE: 2.54 | R2: 0.46
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:03:16,686] Trial 17 finished with value: 0.4604397281564374 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01478106079401023, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.7184822111418687, 'colsample_bytree': 0.7322769851007019}. Best is trial 14 with value: 0.4657161371982982.

Running time: 4.0 sec
OOF RMSE: 2.55 | R2: 0.46
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:03:23,001] Trial 18 finished with value: 0.46068548558466216 and parameters: {'n_estimators': 1000, 'learning_rate': 0.007938432719657064, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.7570532836807241, 'colsample_bytree': 0.6681386702042129}. Best is trial 14 with value: 0.4657161371982982.

Running time: 6.3 sec
OOF RMSE: 2.55 | R2: 0.46
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:03:29,778] Trial 19 finished with value: 0.45264698644129864 and parameters: {'n_estimators': 1000, 'learning_rate': 0.011623586762252657, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.8016307874907742, 'colsample_bytree': 0.8374334873376704}. Best is trial 14 with value: 0.4657161371982982.

Running time: 6.8 sec
OOF RMSE: 2.56 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:03:35,964] Trial 20 finished with value: 0.45054410295802727 and parameters: {'n_estimators': 1000, 'learning_rate': 0.019312011004776537, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.6968809902784355, 'colsample_bytree': 0.7593318361065254}. Best is trial 14 with value: 0.4657161371982982.

Running time: 6.2 sec
OOF RMSE: 2.57 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:03:42,312] Trial 21 finished with value: 0.4619599093504527 and parameters: {'n_estimators': 1000, 'learning_rate': 0.007958159091791362, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.7545662679713991, 'colsample_bytree': 0.6635018019517764}. Best is trial 14 with value: 0.4657161371982982.

Running time: 6.3 sec
OOF RMSE: 2.54 | R2: 0.46
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:03:48,704] Trial 22 finished with value: 0.4581875766713063 and parameters: {'n_estimators': 1000, 'learning_rate': 0.006907939819143146, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.7886929232164014, 'colsample_bytree': 0.6542041475536378}. Best is trial 14 with value: 0.4657161371982982.

Running time: 6.4 sec
OOF RMSE: 2.55 | R2: 0.46
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:03:55,179] Trial 23 finished with value: 0.4581970433694974 and parameters: {'n_estimators': 1000, 'learning_rate': 0.010559335248016725, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.7294680498825284, 'colsample_bytree': 0.7228315502693614}. Best is trial 14 with value: 0.4657161371982982.

Running time: 6.5 sec
OOF RMSE: 2.55 | R2: 0.46
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:04:01,968] Trial 24 finished with value: 0.39533274357707093 and parameters: {'n_estimators': 1000, 'learning_rate': 0.017235533342500477, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.8596005091359513, 'colsample_bytree': 0.6493493671555968}. Best is trial 14 with value: 0.4657161371982982.
[I 2025-07-11 21:04:01,969] A new study created in memory with name: no-name-91de8ca1-5a34-44ec-8090-f052b64403a9

Running time: 6.8 sec
OOF RMSE: 2.70 | R2: 0.40

✅ XGB - Mejor R2: 0.47
📋 Parámetros: {'n_estimators': 500, 'learning_rate': 0.009751190845187654, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.7304986036877639, 'colsample_bytree': 0.6616040553358405}

Buscando mejores hiperparámetros para LBM...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:04:03,101] Trial 0 finished with value: 0.20307518596855878 and parameters: {'learning_rate': 0.035682694119893964, 'num_leaves': 60, 'max_depth': 7, 'min_child_samples': 16, 'subsample': 0.8418798762777782, 'colsample_bytree': 0.8769641314168248, 'n_estimators': 2000}. Best is trial 0 with value: 0.20307518596855878.

Running time: 1.1 sec
OOF RMSE: 3.09 | R2: 0.20
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 21:04:03,703] Trial 1 finished with value: 0.38952980869750586 and parameters: {'learning_rate': 0.011568293264558226, 'num_leaves': 80, 'max_depth': 7, 'min_child_samples': 8, 'subsample': 0.7957349691043666, 'colsample_bytree': 0.7976452477258766, 'n_estimators': 1000}. Best is trial 1 with value: 0.38952980869750586.

Fold 5
Running time: 0.6 sec
OOF RMSE: 2.71 | R2: 0.39
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:04:04,617] Trial 2 finished with value: 0.3388116601981649 and parameters: {'learning_rate': 0.016421004813537886, 'num_leaves': 40, 'max_depth': 7, 'min_child_samples': 21, 'subsample': 0.9947904162777192, 'colsample_bytree': 0.6151210541335597, 'n_estimators': 2000}. Best is trial 1 with value: 0.38952980869750586.

Running time: 0.9 sec
OOF RMSE: 2.82 | R2: 0.34
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 21:04:05,155] Trial 3 finished with value: 0.2633329781947963 and parameters: {'learning_rate': 0.0840385617707199, 'num_leaves': 40, 'max_depth': 7, 'min_child_samples': 22, 'subsample': 0.7704753923585763, 'colsample_bytree': 0.9970525992914201, 'n_estimators': 1000}. Best is trial 1 with value: 0.38952980869750586.

Fold 5
Running time: 0.5 sec
OOF RMSE: 2.98 | R2: 0.26
Fold 1
Fold 2
Fold 3

[I 2025-07-11 21:04:05,404] Trial 4 finished with value: 0.40919925239733324 and parameters: {'learning_rate': 0.008264854061189963, 'num_leaves': 80, 'max_depth': 5, 'min_child_samples': 21, 'subsample': 0.774745700462145, 'colsample_bytree': 0.7074207855894933, 'n_estimators': 500}. Best is trial 4 with value: 0.40919925239733324.

Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 2.66 | R2: 0.41
Fold 1
Fold 2

[I 2025-07-11 21:04:05,762] Trial 5 finished with value: 0.15155749267633 and parameters: {'learning_rate': 0.09600194737086423, 'num_leaves': 60, 'max_depth': 7, 'min_child_samples': 13, 'subsample': 0.7605092301722768, 'colsample_bytree': 0.8350419702270867, 'n_estimators': 500}. Best is trial 4 with value: 0.40919925239733324.

Fold 3
Fold 4
Fold 5
Running time: 0.4 sec
OOF RMSE: 3.19 | R2: 0.15
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:04:06,026] Trial 6 finished with value: 0.41378366213086715 and parameters: {'learning_rate': 0.03580981274083831, 'num_leaves': 80, 'max_depth': 8, 'min_child_samples': 23, 'subsample': 0.9237859982793204, 'colsample_bytree': 0.8470383112636346, 'n_estimators': 500}. Best is trial 6 with value: 0.41378366213086715.

Running time: 0.3 sec
OOF RMSE: 2.65 | R2: 0.41
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 21:04:06,616] Trial 7 finished with value: 0.31176204716486855 and parameters: {'learning_rate': 0.07329714976511517, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 9, 'subsample': 0.6003215897663797, 'colsample_bytree': 0.6383254426253182, 'n_estimators': 1000}. Best is trial 6 with value: 0.41378366213086715.

Fold 5
Running time: 0.6 sec
OOF RMSE: 2.88 | R2: 0.31
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:04:07,564] Trial 8 finished with value: 0.41392134562583704 and parameters: {'learning_rate': 0.025146334033413965, 'num_leaves': 80, 'max_depth': 5, 'min_child_samples': 7, 'subsample': 0.6784371912585565, 'colsample_bytree': 0.7909472626398094, 'n_estimators': 2000}. Best is trial 8 with value: 0.41392134562583704.

Running time: 0.9 sec
OOF RMSE: 2.65 | R2: 0.41
Fold 1
Fold 2
Fold 3

[I 2025-07-11 21:04:07,893] Trial 9 finished with value: 0.3534941027170291 and parameters: {'learning_rate': 0.020071064119994975, 'num_leaves': 60, 'max_depth': 8, 'min_child_samples': 17, 'subsample': 0.6883735289324582, 'colsample_bytree': 0.7905208266708537, 'n_estimators': 500}. Best is trial 8 with value: 0.41392134562583704.

Fold 4
Fold 5
Running time: 0.3 sec
OOF RMSE: 2.79 | R2: 0.35
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:04:08,840] Trial 10 finished with value: 0.5066497066027023 and parameters: {'learning_rate': 0.006147920682501303, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 6, 'subsample': 0.6166448052390412, 'colsample_bytree': 0.9497488445237675, 'n_estimators': 2000}. Best is trial 10 with value: 0.5066497066027023.

Running time: 0.9 sec
OOF RMSE: 2.43 | R2: 0.51
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:04:09,825] Trial 11 finished with value: 0.49488486776783347 and parameters: {'learning_rate': 0.005422260238706541, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 5, 'subsample': 0.6001697299073553, 'colsample_bytree': 0.9724115060226725, 'n_estimators': 2000}. Best is trial 10 with value: 0.5066497066027023.

Running time: 1.0 sec
OOF RMSE: 2.46 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:04:10,798] Trial 12 finished with value: 0.5042338464578503 and parameters: {'learning_rate': 0.006557297657695222, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 5, 'subsample': 0.6108101549939534, 'colsample_bytree': 0.9925525312111209, 'n_estimators': 2000}. Best is trial 10 with value: 0.5066497066027023.

Running time: 1.0 sec
OOF RMSE: 2.44 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 21:04:11,774] Trial 13 finished with value: 0.2778375864872178 and parameters: {'learning_rate': 0.005053803591480732, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 12, 'subsample': 0.6769888110299839, 'colsample_bytree': 0.9238122010264765, 'n_estimators': 2000}. Best is trial 10 with value: 0.5066497066027023.

Fold 5
Running time: 1.0 sec
OOF RMSE: 2.95 | R2: 0.28
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:04:12,932] Trial 14 finished with value: 0.49234979771454934 and parameters: {'learning_rate': 0.008533752527348983, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 5, 'subsample': 0.6503352925018913, 'colsample_bytree': 0.93431891198902, 'n_estimators': 2000}. Best is trial 10 with value: 0.5066497066027023.

Running time: 1.2 sec
OOF RMSE: 2.47 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 21:04:13,941] Trial 15 finished with value: 0.23479248121543805 and parameters: {'learning_rate': 0.007799544321682231, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 11, 'subsample': 0.7255028542230454, 'colsample_bytree': 0.9226424875734963, 'n_estimators': 2000}. Best is trial 10 with value: 0.5066497066027023.

Fold 5
Running time: 1.0 sec
OOF RMSE: 3.03 | R2: 0.23
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:04:14,970] Trial 16 finished with value: 0.4904332291441028 and parameters: {'learning_rate': 0.012528649717381641, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 5, 'subsample': 0.8507355271330956, 'colsample_bytree': 0.969564925651967, 'n_estimators': 2000}. Best is trial 10 with value: 0.5066497066027023.

Running time: 1.0 sec
OOF RMSE: 2.47 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 1.0 sec
OOF RMSE: 2.97 | R2: 0.27

[I 2025-07-11 21:04:15,961] Trial 17 finished with value: 0.2676105629894955 and parameters: {'learning_rate': 0.006596011544751566, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 10, 'subsample': 0.6467439755753599, 'colsample_bytree': 0.7310441054196001, 'n_estimators': 2000}. Best is trial 10 with value: 0.5066497066027023.

Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 21:04:16,794] Trial 18 finished with value: 0.2769649745983157 and parameters: {'learning_rate': 0.011302861990054308, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 14, 'subsample': 0.7220811315328814, 'colsample_bytree': 0.8884816961374253, 'n_estimators': 2000}. Best is trial 10 with value: 0.5066497066027023.

Fold 5
Running time: 0.8 sec
OOF RMSE: 2.95 | R2: 0.28
Fold 1
Fold 2
Fold 3

[I 2025-07-11 21:04:17,282] Trial 19 finished with value: 0.39628625316120614 and parameters: {'learning_rate': 0.014558739977321497, 'num_leaves': 40, 'max_depth': 5, 'min_child_samples': 18, 'subsample': 0.6336085460446195, 'colsample_bytree': 0.9937613861505096, 'n_estimators': 1000}. Best is trial 10 with value: 0.5066497066027023.

Fold 4
Fold 5
Running time: 0.5 sec
OOF RMSE: 2.69 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:04:18,198] Trial 20 finished with value: 0.3279697710440902 and parameters: {'learning_rate': 0.051951514910988913, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 25, 'subsample': 0.7203026449503643, 'colsample_bytree': 0.9456502346695893, 'n_estimators': 2000}. Best is trial 10 with value: 0.5066497066027023.

Running time: 0.9 sec
OOF RMSE: 2.84 | R2: 0.33
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:04:19,127] Trial 21 finished with value: 0.4529620792951048 and parameters: {'learning_rate': 0.005083100534590697, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 7, 'subsample': 0.6041053798062622, 'colsample_bytree': 0.9591306633037782, 'n_estimators': 2000}. Best is trial 10 with value: 0.5066497066027023.

Running time: 0.9 sec
OOF RMSE: 2.56 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 21:04:20,115] Trial 22 finished with value: 0.5039059688948122 and parameters: {'learning_rate': 0.006087160423914256, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 5, 'subsample': 0.6230123697004214, 'colsample_bytree': 0.9100157361432779, 'n_estimators': 2000}. Best is trial 10 with value: 0.5066497066027023.

Fold 5
Running time: 1.0 sec
OOF RMSE: 2.44 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:04:21,034] Trial 23 finished with value: 0.44898540705814527 and parameters: {'learning_rate': 0.006648050957984182, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 7, 'subsample': 0.6400515479898214, 'colsample_bytree': 0.8908123936877749, 'n_estimators': 2000}. Best is trial 10 with value: 0.5066497066027023.

Running time: 0.9 sec
OOF RMSE: 2.57 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:04:22,032] Trial 24 finished with value: 0.36346799294166365 and parameters: {'learning_rate': 0.008822176060344513, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 9, 'subsample': 0.692347448062183, 'colsample_bytree': 0.9132502397724772, 'n_estimators': 2000}. Best is trial 10 with value: 0.5066497066027023.
[I 2025-07-11 21:04:22,033] A new study created in memory with name: no-name-50eaa247-ea73-4e98-83c3-f3f773091193

Running time: 1.0 sec
OOF RMSE: 2.77 | R2: 0.36

✅ LBM - Mejor R2: 0.51
📋 Parámetros: {'learning_rate': 0.006147920682501303, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 6, 'subsample': 0.6166448052390412, 'colsample_bytree': 0.9497488445237675, 'n_estimators': 2000}

Buscando mejores hiperparámetros para MLP...
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

[I 2025-07-11 21:04:23,471] Trial 0 finished with value: 0.4052602970053977 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 5.074199252344198e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.0002698605050389302}. Best is trial 0 with value: 0.4052602970053977.

Running time: 1.4 sec
OOF RMSE: 2.67 | R2: 0.41
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

[I 2025-07-11 21:04:24,601] Trial 1 finished with value: 0.3616655962961146 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 6.8856686603565e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.0061755365859760825}. Best is trial 0 with value: 0.4052602970053977.

Running time: 1.1 sec
OOF RMSE: 2.77 | R2: 0.36
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:04:25,536] Trial 2 finished with value: 0.27962233293505534 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0003232697121780624, 'learning_rate': 'constant', 'learning_rate_init': 0.0006907531876311538}. Best is trial 0 with value: 0.4052602970053977.

Running time: 0.9 sec
OOF RMSE: 2.94 | R2: 0.28
Fold 1
Fold 2
Fold 3

[I 2025-07-11 21:04:26,183] Trial 3 finished with value: 0.41128154813322604 and parameters: {'hidden_layer_sizes': '50', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.08423907438222278, 'learning_rate': 'constant', 'learning_rate_init': 0.00015780052510987763}. Best is trial 3 with value: 0.41128154813322604.

Fold 4
Fold 5
Running time: 0.6 sec
OOF RMSE: 2.66 | R2: 0.41
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 21:04:26,792] Trial 4 finished with value: 0.4194715538239402 and parameters: {'hidden_layer_sizes': '50', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.08420094037703997, 'learning_rate': 'constant', 'learning_rate_init': 0.0025394479680122023}. Best is trial 4 with value: 0.4194715538239402.

Fold 4
Fold 5
Running time: 0.6 sec
OOF RMSE: 2.64 | R2: 0.42
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 21:04:27,566] Trial 5 finished with value: 0.38673279272735805 and parameters: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'sgd', 'alpha': 5.100713482685218e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.0002636492624718207}. Best is trial 4 with value: 0.4194715538239402.

Fold 3
Fold 4
Fold 5
Running time: 0.8 sec
OOF RMSE: 2.71 | R2: 0.39
Fold 1
Fold 2
Fold 3

[I 2025-07-11 21:04:28,170] Trial 6 finished with value: 0.4224794843465457 and parameters: {'hidden_layer_sizes': '50', 'activation': 'relu', 'solver': 'sgd', 'alpha': 9.949548958857351e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.0004723389215187457}. Best is trial 6 with value: 0.4224794843465457.

Fold 4
Fold 5
Running time: 0.6 sec
OOF RMSE: 2.63 | R2: 0.42
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3
Fold 4

[I 2025-07-11 21:04:29,628] Trial 7 finished with value: 0.36470986413786344 and parameters: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'sgd', 'alpha': 1.9970801908819703e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0008137972639547218}. Best is trial 6 with value: 0.4224794843465457.

Fold 5
Running time: 1.5 sec
OOF RMSE: 2.76 | R2: 0.36
Fold 1
Fold 2
Fold 3

[I 2025-07-11 21:04:30,206] Trial 8 finished with value: 0.3851617726376253 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.020355353479901913, 'learning_rate': 'constant', 'learning_rate_init': 0.0016950081628855109}. Best is trial 6 with value: 0.4224794843465457.

Fold 4
Fold 5
Running time: 0.6 sec
OOF RMSE: 2.72 | R2: 0.39
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

[I 2025-07-11 21:04:32,278] Trial 9 finished with value: 0.38222377698577437 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.04014866515093947, 'learning_rate': 'constant', 'learning_rate_init': 0.00013568223310786098}. Best is trial 6 with value: 0.4224794843465457.

Running time: 2.1 sec
OOF RMSE: 2.72 | R2: 0.38
Fold 1
Fold 2
Fold 3

[I 2025-07-11 21:04:32,845] Trial 10 finished with value: 0.306202824140245 and parameters: {'hidden_layer_sizes': '50', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0029716851137250875, 'learning_rate': 'adaptive', 'learning_rate_init': 0.008704753237572745}. Best is trial 6 with value: 0.4224794843465457.

Fold 4
Fold 5
Running time: 0.6 sec
OOF RMSE: 2.89 | R2: 0.31
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 21:04:33,829] Trial 11 finished with value: 0.3880963721902254 and parameters: {'hidden_layer_sizes': '50', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.0011154456686780783, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0020007222973741946}. Best is trial 6 with value: 0.4224794843465457.

Fold 5
Running time: 1.0 sec
OOF RMSE: 2.71 | R2: 0.39
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 21:04:34,270] Trial 12 finished with value: 0.4122588007258191 and parameters: {'hidden_layer_sizes': '50', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.007137481692809448, 'learning_rate': 'constant', 'learning_rate_init': 0.002994936360457535}. Best is trial 6 with value: 0.4224794843465457.

Fold 4
Fold 5
Running time: 0.4 sec
OOF RMSE: 2.66 | R2: 0.41
Fold 1
Fold 2
Fold 3

[I 2025-07-11 21:04:34,922] Trial 13 finished with value: 0.42402037328668885 and parameters: {'hidden_layer_sizes': '50', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.00018901849675329613, 'learning_rate': 'constant', 'learning_rate_init': 0.00047775977202615336}. Best is trial 13 with value: 0.42402037328668885.

Fold 4
Fold 5
Running time: 0.6 sec
OOF RMSE: 2.63 | R2: 0.42
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 21:04:36,598] Trial 14 finished with value: 0.37443237921615735 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.0003790259982280177, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0004303990086246019}. Best is trial 13 with value: 0.42402037328668885.

Running time: 1.7 sec
OOF RMSE: 2.74 | R2: 0.37
Fold 1
Fold 2
Fold 3

[I 2025-07-11 21:04:37,170] Trial 15 finished with value: 0.4230394409547735 and parameters: {'hidden_layer_sizes': '50', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.00023726401729265876, 'learning_rate': 'constant', 'learning_rate_init': 0.0005448279965217217}. Best is trial 13 with value: 0.42402037328668885.

Fold 4
Fold 5
Running time: 0.6 sec
OOF RMSE: 2.63 | R2: 0.42
Fold 1
Fold 2
Fold 3

[I 2025-07-11 21:04:37,665] Trial 16 finished with value: 0.4264253186318355 and parameters: {'hidden_layer_sizes': '50', 'activation': 'relu', 'solver': 'sgd', 'alpha': 1.0027359978673805e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.0010713124721328867}. Best is trial 16 with value: 0.4264253186318355.

Fold 4
Fold 5
Running time: 0.5 sec
OOF RMSE: 2.63 | R2: 0.43
Fold 1
Fold 2
Fold 3

[I 2025-07-11 21:04:38,195] Trial 17 finished with value: 0.4206459761173299 and parameters: {'hidden_layer_sizes': '50', 'activation': 'relu', 'solver': 'sgd', 'alpha': 1.0030993512639193e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.0011507923793591139}. Best is trial 16 with value: 0.4264253186318355.

Fold 4
Fold 5
Running time: 0.5 sec
OOF RMSE: 2.64 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:04:39,391] Trial 18 finished with value: 0.41809060350841243 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0010996881114774025, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0013432815140998371}. Best is trial 16 with value: 0.4264253186318355.

Running time: 1.2 sec
OOF RMSE: 2.64 | R2: 0.42
Fold 1
Fold 2
Fold 3

[I 2025-07-11 21:04:39,987] Trial 19 finished with value: 0.42153030685366777 and parameters: {'hidden_layer_sizes': '50', 'activation': 'relu', 'solver': 'sgd', 'alpha': 1.010166770389626e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.0003063512080788968}. Best is trial 16 with value: 0.4264253186318355.

Fold 4
Fold 5
Running time: 0.6 sec
OOF RMSE: 2.64 | R2: 0.42
Fold 1
Fold 2
Fold 3

[I 2025-07-11 21:04:40,415] Trial 20 finished with value: 0.424784991669652 and parameters: {'hidden_layer_sizes': '50', 'activation': 'relu', 'solver': 'sgd', 'alpha': 3.101599708721442e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.0009321150799991131}. Best is trial 16 with value: 0.4264253186318355.

Fold 4
Fold 5
Running time: 0.4 sec
OOF RMSE: 2.63 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:04:40,773] Trial 21 finished with value: 0.4183398649041009 and parameters: {'hidden_layer_sizes': '50', 'activation': 'relu', 'solver': 'sgd', 'alpha': 2.8105411170135404e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.0008804673906257387}. Best is trial 16 with value: 0.4264253186318355.

Running time: 0.4 sec
OOF RMSE: 2.64 | R2: 0.42
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 21:04:41,262] Trial 22 finished with value: 0.39396054420341675 and parameters: {'hidden_layer_sizes': '50', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.00014126119279533718, 'learning_rate': 'constant', 'learning_rate_init': 0.004093954488694564}. Best is trial 16 with value: 0.4264253186318355.

Fold 4
Fold 5
Running time: 0.5 sec
OOF RMSE: 2.70 | R2: 0.39
Fold 1
Fold 2
Fold 3

[I 2025-07-11 21:04:42,002] Trial 23 finished with value: 0.40818868847749645 and parameters: {'hidden_layer_sizes': '50', 'activation': 'relu', 'solver': 'sgd', 'alpha': 2.512300909239361e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.0013675973698259506}. Best is trial 16 with value: 0.4264253186318355.

Fold 4
Fold 5
Running time: 0.7 sec
OOF RMSE: 2.67 | R2: 0.41
Fold 1
Fold 2
Fold 3

[I 2025-07-11 21:04:42,570] Trial 24 finished with value: 0.41962448706571 and parameters: {'hidden_layer_sizes': '50', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.00015779050298161612, 'learning_rate': 'constant', 'learning_rate_init': 0.0006201952454974371}. Best is trial 16 with value: 0.4264253186318355.
[I 2025-07-11 21:04:42,571] A new study created in memory with name: no-name-df248647-5704-4e58-84b8-e2dde8aa2ece
[I 2025-07-11 21:04:42,661] Trial 0 finished with value: -0.7033531534651429 and parameters: {'kernel': 'sigmoid', 'C': 0.4514602961759049, 'epsilon': 0.06164048038976762, 'gamma': 'scale'}. Best is trial 0 with value: -0.7033531534651429.

Fold 4
Fold 5
Running time: 0.6 sec
OOF RMSE: 2.64 | R2: 0.42

✅ MLP - Mejor R2: 0.43
📋 Parámetros: {'hidden_layer_sizes': '50', 'activation': 'relu', 'solver': 'sgd', 'alpha': 1.0027359978673805e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.0010713124721328867}

Buscando mejores hiperparámetros para SVR...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 4.52 | R2: -0.70
Fold 1
Fold 2
Fold 3

[I 2025-07-11 21:04:42,732] Trial 1 finished with value: 0.29799964483284924 and parameters: {'kernel': 'rbf', 'C': 2.338626682761024, 'epsilon': 0.18293497412680967, 'gamma': 'scale'}. Best is trial 1 with value: 0.29799964483284924.
[I 2025-07-11 21:04:42,806] Trial 2 finished with value: -36.24966691380006 and parameters: {'kernel': 'sigmoid', 'C': 3.148981720032384, 'epsilon': 0.15553665048674595, 'gamma': 'scale'}. Best is trial 1 with value: 0.29799964483284924.
[I 2025-07-11 21:04:42,877] Trial 3 finished with value: 0.06721248277252367 and parameters: {'kernel': 'sigmoid', 'C': 0.10408423666379937, 'epsilon': 0.19956066575476625, 'gamma': 'auto'}. Best is trial 1 with value: 0.29799964483284924.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.90 | R2: 0.30
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 21.16 | R2: -36.25
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.35 | R2: 0.07
Fold 1
Fold 2

[I 2025-07-11 21:04:42,953] Trial 4 finished with value: 0.34057770091541684 and parameters: {'kernel': 'rbf', 'C': 3.8719717175926074, 'epsilon': 0.036734381596202, 'gamma': 'auto'}. Best is trial 4 with value: 0.34057770091541684.
[I 2025-07-11 21:04:43,025] Trial 5 finished with value: 0.31858073035259116 and parameters: {'kernel': 'rbf', 'C': 3.2112175401383474, 'epsilon': 0.11377430797368633, 'gamma': 'auto'}. Best is trial 4 with value: 0.34057770091541684.
[I 2025-07-11 21:04:43,100] Trial 6 finished with value: 0.364908991421407 and parameters: {'kernel': 'rbf', 'C': 4.686963878133994, 'epsilon': 0.15048984372586827, 'gamma': 'scale'}. Best is trial 6 with value: 0.364908991421407.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.82 | R2: 0.34
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.86 | R2: 0.32
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.76 | R2: 0.36
Fold 1

[I 2025-07-11 21:04:43,177] Trial 7 finished with value: 0.40124425691446264 and parameters: {'kernel': 'rbf', 'C': 9.750689440124036, 'epsilon': 0.14908971187935355, 'gamma': 'scale'}. Best is trial 7 with value: 0.40124425691446264.
[I 2025-07-11 21:04:43,257] Trial 8 finished with value: 0.40375400580816323 and parameters: {'kernel': 'rbf', 'C': 8.831320601586357, 'epsilon': 0.1047290029770141, 'gamma': 'scale'}. Best is trial 8 with value: 0.40375400580816323.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.68 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.68 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:04:43,331] Trial 9 finished with value: -0.40541493518767435 and parameters: {'kernel': 'sigmoid', 'C': 0.2928739212257227, 'epsilon': 0.05863734225168015, 'gamma': 'auto'}. Best is trial 8 with value: 0.40375400580816323.
[I 2025-07-11 21:04:43,407] Trial 10 finished with value: 0.20802581585182034 and parameters: {'kernel': 'rbf', 'C': 1.0566225499801687, 'epsilon': 0.0996561424013216, 'gamma': 'scale'}. Best is trial 8 with value: 0.40375400580816323.
[I 2025-07-11 21:04:43,505] Trial 11 finished with value: 0.40369493219083674 and parameters: {'kernel': 'rbf', 'C': 9.069423399677724, 'epsilon': 0.11398364778033943, 'gamma': 'scale'}. Best is trial 8 with value: 0.40375400580816323.

Running time: 0.1 sec
OOF RMSE: 4.11 | R2: -0.41
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.08 | R2: 0.21
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.68 | R2: 0.40
Fold 1
Fold 2

[I 2025-07-11 21:04:43,588] Trial 12 finished with value: 0.4032625355764161 and parameters: {'kernel': 'rbf', 'C': 9.689421312901565, 'epsilon': 0.09993433846628105, 'gamma': 'scale'}. Best is trial 8 with value: 0.40375400580816323.
[I 2025-07-11 21:04:43,670] Trial 13 finished with value: 0.224156715087251 and parameters: {'kernel': 'rbf', 'C': 1.2337857281843465, 'epsilon': 0.12285847299003495, 'gamma': 'scale'}. Best is trial 8 with value: 0.40375400580816323.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.68 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.05 | R2: 0.22
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:04:43,756] Trial 14 finished with value: 0.3949481625671506 and parameters: {'kernel': 'rbf', 'C': 6.474892386378593, 'epsilon': 0.07445008965350894, 'gamma': 'scale'}. Best is trial 8 with value: 0.40375400580816323.
[I 2025-07-11 21:04:43,834] Trial 15 finished with value: 0.2770292206849405 and parameters: {'kernel': 'rbf', 'C': 1.9291999673410298, 'epsilon': 0.012018557387600798, 'gamma': 'scale'}. Best is trial 8 with value: 0.40375400580816323.
[I 2025-07-11 21:04:43,911] Trial 16 finished with value: 0.14019830253472731 and parameters: {'kernel': 'rbf', 'C': 0.48232911148495894, 'epsilon': 0.1276729260286917, 'gamma': 'scale'}. Best is trial 8 with value: 0.40375400580816323.

Running time: 0.1 sec
OOF RMSE: 2.70 | R2: 0.39
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.95 | R2: 0.28
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.21 | R2: 0.14
Fold 1
Fold 2

[I 2025-07-11 21:04:43,999] Trial 17 finished with value: 0.39753989310675486 and parameters: {'kernel': 'rbf', 'C': 6.809178074646417, 'epsilon': 0.08834812079622867, 'gamma': 'scale'}. Best is trial 8 with value: 0.40375400580816323.
[I 2025-07-11 21:04:44,083] Trial 18 finished with value: -14.237371420277277 and parameters: {'kernel': 'sigmoid', 'C': 1.640001215954372, 'epsilon': 0.13477437121381852, 'gamma': 'auto'}. Best is trial 8 with value: 0.40375400580816323.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.69 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 13.53 | R2: -14.24
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:04:44,172] Trial 19 finished with value: 0.3931182933259061 and parameters: {'kernel': 'rbf', 'C': 6.338660315820466, 'epsilon': 0.08160637565953982, 'gamma': 'scale'}. Best is trial 8 with value: 0.40375400580816323.
[I 2025-07-11 21:04:44,246] Trial 20 finished with value: 0.17624777265691516 and parameters: {'kernel': 'rbf', 'C': 0.7586179555010104, 'epsilon': 0.17737865297248484, 'gamma': 'scale'}. Best is trial 8 with value: 0.40375400580816323.
[I 2025-07-11 21:04:44,337] Trial 21 finished with value: 0.4034057239822737 and parameters: {'kernel': 'rbf', 'C': 9.603125880714913, 'epsilon': 0.09997485157332035, 'gamma': 'scale'}. Best is trial 8 with value: 0.40375400580816323.

Running time: 0.1 sec
OOF RMSE: 2.70 | R2: 0.39
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.15 | R2: 0.18
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.68 | R2: 0.40
Fold 1

[I 2025-07-11 21:04:44,439] Trial 22 finished with value: 0.40346971053783476 and parameters: {'kernel': 'rbf', 'C': 9.57229384279779, 'epsilon': 0.09961608531826342, 'gamma': 'scale'}. Best is trial 8 with value: 0.40375400580816323.
[I 2025-07-11 21:04:44,530] Trial 23 finished with value: 0.37814679258732753 and parameters: {'kernel': 'rbf', 'C': 5.346903420626225, 'epsilon': 0.11275919351747582, 'gamma': 'scale'}. Best is trial 8 with value: 0.40375400580816323.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.68 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.73 | R2: 0.38
Fold 1
Fold 2
Fold 3

[I 2025-07-11 21:04:44,621] Trial 24 finished with value: 0.4015248435620996 and parameters: {'kernel': 'rbf', 'C': 7.109114305349425, 'epsilon': 0.06460700227643114, 'gamma': 'scale'}. Best is trial 8 with value: 0.40375400580816323.
[I 2025-07-11 21:04:44,622] A new study created in memory with name: no-name-6f2d52fa-9d67-4edf-922b-5040352b6e27
[I 2025-07-11 21:04:44,685] Trial 0 finished with value: 0.42891411291561565 and parameters: {'n_neighbors': 7, 'weights': 'uniform', 'leaf_size': 10}. Best is trial 0 with value: 0.42891411291561565.
[I 2025-07-11 21:04:44,748] Trial 1 finished with value: 0.4742389909626107 and parameters: {'n_neighbors': 8, 'weights': 'distance', 'leaf_size': 28}. Best is trial 1 with value: 0.4742389909626107.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.68 | R2: 0.40

✅ SVR - Mejor R2: 0.40
📋 Parámetros: {'kernel': 'rbf', 'C': 8.831320601586357, 'epsilon': 0.1047290029770141, 'gamma': 'scale'}

Buscando mejores hiperparámetros para KNN...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.62 | R2: 0.43
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.51 | R2: 0.47
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 21:04:44,813] Trial 2 finished with value: 0.46106246376658244 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'leaf_size': 38}. Best is trial 1 with value: 0.4742389909626107.
[I 2025-07-11 21:04:44,874] Trial 3 finished with value: 0.41669640068855485 and parameters: {'n_neighbors': 14, 'weights': 'uniform', 'leaf_size': 15}. Best is trial 1 with value: 0.4742389909626107.
[I 2025-07-11 21:04:44,939] Trial 4 finished with value: 0.45730120545791253 and parameters: {'n_neighbors': 10, 'weights': 'distance', 'leaf_size': 19}. Best is trial 1 with value: 0.4742389909626107.
[I 2025-07-11 21:04:45,001] Trial 5 finished with value: 0.41669640068855485 and parameters: {'n_neighbors': 14, 'weights': 'uniform', 'leaf_size': 34}. Best is trial 1 with value: 0.4742389909626107.

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.54 | R2: 0.46
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.65 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.55 | R2: 0.46
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.65 | R2: 0.42

[I 2025-07-11 21:04:45,064] Trial 6 finished with value: 0.44960788512329153 and parameters: {'n_neighbors': 11, 'weights': 'distance', 'leaf_size': 40}. Best is trial 1 with value: 0.4742389909626107.
[I 2025-07-11 21:04:45,126] Trial 7 finished with value: 0.41669640068855485 and parameters: {'n_neighbors': 14, 'weights': 'uniform', 'leaf_size': 40}. Best is trial 1 with value: 0.4742389909626107.
[I 2025-07-11 21:04:45,189] Trial 8 finished with value: 0.41775472124562263 and parameters: {'n_neighbors': 12, 'weights': 'uniform', 'leaf_size': 18}. Best is trial 1 with value: 0.4742389909626107.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.57 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.65 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.65 | R2: 0.42
Fold 1
Fold 2

[I 2025-07-11 21:04:45,253] Trial 9 finished with value: 0.3884785567435891 and parameters: {'n_neighbors': 4, 'weights': 'uniform', 'leaf_size': 25}. Best is trial 1 with value: 0.4742389909626107.
[I 2025-07-11 21:04:45,326] Trial 10 finished with value: 0.46490280776136794 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'leaf_size': 30}. Best is trial 1 with value: 0.4742389909626107.
[I 2025-07-11 21:04:45,396] Trial 11 finished with value: 0.46490280776136794 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'leaf_size': 29}. Best is trial 1 with value: 0.4742389909626107.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.71 | R2: 0.39
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.54 | R2: 0.46
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.54 | R2: 0.46
Fold 1

[I 2025-07-11 21:04:45,499] Trial 12 finished with value: 0.46490280776136794 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'leaf_size': 27}. Best is trial 1 with value: 0.4742389909626107.
[I 2025-07-11 21:04:45,580] Trial 13 finished with value: 0.45089559272635926 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'leaf_size': 31}. Best is trial 1 with value: 0.4742389909626107.
[I 2025-07-11 21:04:45,648] Trial 14 finished with value: 0.4816368006187881 and parameters: {'n_neighbors': 9, 'weights': 'distance', 'leaf_size': 23}. Best is trial 14 with value: 0.4816368006187881.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.54 | R2: 0.46
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.57 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.50 | R2: 0.48

[I 2025-07-11 21:04:45,719] Trial 15 finished with value: 0.4816368006187881 and parameters: {'n_neighbors': 9, 'weights': 'distance', 'leaf_size': 23}. Best is trial 14 with value: 0.4816368006187881.
[I 2025-07-11 21:04:45,789] Trial 16 finished with value: 0.4816368006187881 and parameters: {'n_neighbors': 9, 'weights': 'distance', 'leaf_size': 23}. Best is trial 14 with value: 0.4816368006187881.
[I 2025-07-11 21:04:45,861] Trial 17 finished with value: 0.44960788512329153 and parameters: {'n_neighbors': 11, 'weights': 'distance', 'leaf_size': 22}. Best is trial 14 with value: 0.4816368006187881.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.50 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.50 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.57 | R2: 0.45

[I 2025-07-11 21:04:45,933] Trial 18 finished with value: 0.4816368006187881 and parameters: {'n_neighbors': 9, 'weights': 'distance', 'leaf_size': 14}. Best is trial 14 with value: 0.4816368006187881.
[I 2025-07-11 21:04:46,004] Trial 19 finished with value: 0.45089559272635926 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'leaf_size': 20}. Best is trial 14 with value: 0.4816368006187881.
[I 2025-07-11 21:04:46,076] Trial 20 finished with value: 0.4540788118143899 and parameters: {'n_neighbors': 12, 'weights': 'distance', 'leaf_size': 33}. Best is trial 14 with value: 0.4816368006187881.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.50 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.57 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.56 | R2: 0.45

[I 2025-07-11 21:04:46,146] Trial 21 finished with value: 0.4816368006187881 and parameters: {'n_neighbors': 9, 'weights': 'distance', 'leaf_size': 25}. Best is trial 14 with value: 0.4816368006187881.
[I 2025-07-11 21:04:46,249] Trial 22 finished with value: 0.4816368006187881 and parameters: {'n_neighbors': 9, 'weights': 'distance', 'leaf_size': 23}. Best is trial 14 with value: 0.4816368006187881.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.50 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.50 | R2: 0.48
Fold 1
Fold 2
Fold 3

[I 2025-07-11 21:04:46,323] Trial 23 finished with value: 0.45730120545791253 and parameters: {'n_neighbors': 10, 'weights': 'distance', 'leaf_size': 22}. Best is trial 14 with value: 0.4816368006187881.
[I 2025-07-11 21:04:46,399] Trial 24 finished with value: 0.4742389909626107 and parameters: {'n_neighbors': 8, 'weights': 'distance', 'leaf_size': 16}. Best is trial 14 with value: 0.4816368006187881.
[I 2025-07-11 21:04:46,400] A new study created in memory with name: no-name-b7525ccc-f072-4352-945f-fb184ed782ec
[I 2025-07-11 21:04:46,464] Trial 0 finished with value: 0.3273096020698081 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 0 with value: 0.3273096020698081.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.55 | R2: 0.46
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.51 | R2: 0.47

✅ KNN - Mejor R2: 0.48
📋 Parámetros: {'n_neighbors': 9, 'weights': 'distance', 'leaf_size': 23}

Buscando mejores hiperparámetros para LR...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.84 | R2: 0.33
Fold 1
Fold 2
Fold 3

[I 2025-07-11 21:04:46,528] Trial 1 finished with value: 0.3273096020698081 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 0 with value: 0.3273096020698081.
[I 2025-07-11 21:04:46,602] Trial 2 finished with value: 0.15186884036489412 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 0 with value: 0.3273096020698081.
[I 2025-07-11 21:04:46,688] Trial 3 finished with value: 0.15186884036489412 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 0 with value: 0.3273096020698081.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.84 | R2: 0.33
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.19 | R2: 0.15
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.19 | R2: 0.15
Fold 1

[I 2025-07-11 21:04:46,771] Trial 4 finished with value: 0.15186884037550286 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 0 with value: 0.3273096020698081.
[I 2025-07-11 21:04:46,850] Trial 5 finished with value: 0.15186884037550286 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 0 with value: 0.3273096020698081.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.19 | R2: 0.15
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.19 | R2: 0.15
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 21:04:46,936] Trial 6 finished with value: 0.15186884037550286 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 0 with value: 0.3273096020698081.
[I 2025-07-11 21:04:47,009] Trial 7 finished with value: 0.32632271039862903 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: 0.3273096020698081.
[I 2025-07-11 21:04:47,070] Trial 8 finished with value: 0.3273096020698081 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 0 with value: 0.3273096020698081.

Fold 5
Running time: 0.1 sec
OOF RMSE: 3.19 | R2: 0.15
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.85 | R2: 0.33
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.84 | R2: 0.33
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 21:04:47,167] Trial 9 finished with value: 0.15186884037550286 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 0 with value: 0.3273096020698081.
[I 2025-07-11 21:04:47,273] Trial 10 finished with value: 0.3273096020698081 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 0 with value: 0.3273096020698081.
[I 2025-07-11 21:04:47,336] Trial 11 finished with value: 0.3273096020698081 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 0 with value: 0.3273096020698081.

Fold 5
Running time: 0.1 sec
OOF RMSE: 3.19 | R2: 0.15
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.84 | R2: 0.33
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.84 | R2: 0.33

[I 2025-07-11 21:04:47,398] Trial 12 finished with value: 0.3273096020698081 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 0 with value: 0.3273096020698081.
[I 2025-07-11 21:04:47,462] Trial 13 finished with value: 0.3273096020698081 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 0 with value: 0.3273096020698081.
[I 2025-07-11 21:04:47,528] Trial 14 finished with value: 0.3273096020698081 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 0 with value: 0.3273096020698081.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.84 | R2: 0.33
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.84 | R2: 0.33
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.84 | R2: 0.33
Fold 1
Fold 2

[I 2025-07-11 21:04:47,589] Trial 15 finished with value: 0.3273096020698081 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 0 with value: 0.3273096020698081.
[I 2025-07-11 21:04:47,650] Trial 16 finished with value: 0.3273096020698081 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 0 with value: 0.3273096020698081.
[I 2025-07-11 21:04:47,712] Trial 17 finished with value: 0.3273096020698081 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 0 with value: 0.3273096020698081.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.84 | R2: 0.33
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.84 | R2: 0.33
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.84 | R2: 0.33
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 21:04:47,773] Trial 18 finished with value: 0.3273096020698081 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 0 with value: 0.3273096020698081.
[I 2025-07-11 21:04:47,834] Trial 19 finished with value: 0.3273096020698081 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 0 with value: 0.3273096020698081.
[I 2025-07-11 21:04:47,897] Trial 20 finished with value: 0.3273096020698081 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 0 with value: 0.3273096020698081.
[I 2025-07-11 21:04:47,959] Trial 21 finished with value: 0.3273096020698081 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 0 with value: 0.3273096020698081.

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.84 | R2: 0.33
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.84 | R2: 0.33
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.84 | R2: 0.33
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.84 | R2: 0.33

[I 2025-07-11 21:04:48,021] Trial 22 finished with value: 0.3273096020698081 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 0 with value: 0.3273096020698081.
[I 2025-07-11 21:04:48,083] Trial 23 finished with value: 0.3273096020698081 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 0 with value: 0.3273096020698081.
[I 2025-07-11 21:04:48,143] Trial 24 finished with value: 0.3273096020698081 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 0 with value: 0.3273096020698081.
[I 2025-07-11 21:04:48,144] A new study created in memory with name: no-name-27d1cce3-be7e-46dc-a0ac-a9b28238aff4

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.84 | R2: 0.33
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.84 | R2: 0.33
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.84 | R2: 0.33

✅ LR - Mejor R2: 0.33
📋 Parámetros: {'fit_intercept': False, 'positive': True}

Buscando mejores hiperparámetros para RF...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:04:55,038] Trial 0 finished with value: 0.017405839954156344 and parameters: {'n_estimators': 300, 'max_depth': 7, 'min_samples_split': 3, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 0 with value: 0.017405839954156344.

Running time: 6.9 sec
OOF RMSE: 3.44 | R2: 0.02
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:05:08,033] Trial 1 finished with value: 0.19195576168046868 and parameters: {'n_estimators': 500, 'max_depth': 12, 'min_samples_split': 9, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 1 with value: 0.19195576168046868.

Running time: 13.0 sec
OOF RMSE: 3.12 | R2: 0.19
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:05:11,317] Trial 2 finished with value: 0.04948651302912621 and parameters: {'n_estimators': 100, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 1 with value: 0.19195576168046868.

Running time: 3.3 sec
OOF RMSE: 3.38 | R2: 0.05
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:05:13,773] Trial 3 finished with value: 0.2997913397709848 and parameters: {'n_estimators': 100, 'max_depth': 11, 'min_samples_split': 10, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 3 with value: 0.2997913397709848.

Running time: 2.5 sec
OOF RMSE: 2.90 | R2: 0.30
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:05:17,861] Trial 4 finished with value: 0.39976701081061683 and parameters: {'n_estimators': 300, 'max_depth': 8, 'min_samples_split': 8, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 4 with value: 0.39976701081061683.

Running time: 4.1 sec
OOF RMSE: 2.69 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:05:21,887] Trial 5 finished with value: 0.4200839495285982 and parameters: {'n_estimators': 300, 'max_depth': 6, 'min_samples_split': 5, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 5 with value: 0.4200839495285982.

Running time: 4.0 sec
OOF RMSE: 2.64 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:05:26,695] Trial 6 finished with value: 0.4124104038588431 and parameters: {'n_estimators': 300, 'max_depth': 10, 'min_samples_split': 9, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 5 with value: 0.4200839495285982.

Running time: 4.8 sec
OOF RMSE: 2.66 | R2: 0.41
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:05:28,940] Trial 7 finished with value: 0.22056297329503194 and parameters: {'n_estimators': 100, 'max_depth': 12, 'min_samples_split': 10, 'min_samples_leaf': 5, 'bootstrap': False}. Best is trial 5 with value: 0.4200839495285982.

Running time: 2.2 sec
OOF RMSE: 3.06 | R2: 0.22
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:05:33,127] Trial 8 finished with value: 0.41560012708546423 and parameters: {'n_estimators': 300, 'max_depth': 7, 'min_samples_split': 8, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 5 with value: 0.4200839495285982.

Running time: 4.2 sec
OOF RMSE: 2.65 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:05:40,909] Trial 9 finished with value: 0.20671096180511228 and parameters: {'n_estimators': 300, 'max_depth': 15, 'min_samples_split': 10, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 5 with value: 0.4200839495285982.

Running time: 7.8 sec
OOF RMSE: 3.09 | R2: 0.21
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:05:46,972] Trial 10 finished with value: 0.4091057161525238 and parameters: {'n_estimators': 500, 'max_depth': 5, 'min_samples_split': 5, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 5 with value: 0.4200839495285982.

Running time: 6.1 sec
OOF RMSE: 2.66 | R2: 0.41
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:05:50,568] Trial 11 finished with value: 0.41453868883910205 and parameters: {'n_estimators': 300, 'max_depth': 5, 'min_samples_split': 6, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 5 with value: 0.4200839495285982.

Running time: 3.6 sec
OOF RMSE: 2.65 | R2: 0.41
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:05:54,723] Trial 12 finished with value: 0.41560012708546423 and parameters: {'n_estimators': 300, 'max_depth': 7, 'min_samples_split': 7, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 5 with value: 0.4200839495285982.

Running time: 4.2 sec
OOF RMSE: 2.65 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:05:59,216] Trial 13 finished with value: 0.4217461352952201 and parameters: {'n_estimators': 300, 'max_depth': 8, 'min_samples_split': 5, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 13 with value: 0.4217461352952201.

Running time: 4.5 sec
OOF RMSE: 2.64 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:06:07,057] Trial 14 finished with value: 0.4173830436361117 and parameters: {'n_estimators': 500, 'max_depth': 9, 'min_samples_split': 4, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 13 with value: 0.4217461352952201.

Running time: 7.8 sec
OOF RMSE: 2.65 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:06:11,081] Trial 15 finished with value: 0.4200839495285982 and parameters: {'n_estimators': 300, 'max_depth': 6, 'min_samples_split': 5, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 13 with value: 0.4217461352952201.

Running time: 4.0 sec
OOF RMSE: 2.64 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:06:16,103] Trial 16 finished with value: 0.42266742413021285 and parameters: {'n_estimators': 300, 'max_depth': 9, 'min_samples_split': 4, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 16 with value: 0.42266742413021285.

Running time: 5.0 sec
OOF RMSE: 2.63 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:06:21,051] Trial 17 finished with value: 0.42266742413021285 and parameters: {'n_estimators': 300, 'max_depth': 9, 'min_samples_split': 3, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 16 with value: 0.42266742413021285.

Running time: 4.9 sec
OOF RMSE: 2.63 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:06:30,654] Trial 18 finished with value: 0.41100785158205844 and parameters: {'n_estimators': 500, 'max_depth': 10, 'min_samples_split': 2, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 16 with value: 0.42266742413021285.

Running time: 9.6 sec
OOF RMSE: 2.66 | R2: 0.41
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:06:32,421] Trial 19 finished with value: 0.41248486398440987 and parameters: {'n_estimators': 100, 'max_depth': 13, 'min_samples_split': 3, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 16 with value: 0.42266742413021285.

Running time: 1.8 sec
OOF RMSE: 2.66 | R2: 0.41
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:06:37,384] Trial 20 finished with value: 0.42266742413021285 and parameters: {'n_estimators': 300, 'max_depth': 9, 'min_samples_split': 3, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 16 with value: 0.42266742413021285.

Running time: 5.0 sec
OOF RMSE: 2.63 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:06:42,399] Trial 21 finished with value: 0.42266742413021285 and parameters: {'n_estimators': 300, 'max_depth': 9, 'min_samples_split': 3, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 16 with value: 0.42266742413021285.

Running time: 5.0 sec
OOF RMSE: 2.63 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:06:47,364] Trial 22 finished with value: 0.42266742413021285 and parameters: {'n_estimators': 300, 'max_depth': 9, 'min_samples_split': 4, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 16 with value: 0.42266742413021285.

Running time: 5.0 sec
OOF RMSE: 2.63 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:06:53,013] Trial 23 finished with value: 0.4069161006348766 and parameters: {'n_estimators': 300, 'max_depth': 11, 'min_samples_split': 4, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 16 with value: 0.42266742413021285.

Running time: 5.6 sec
OOF RMSE: 2.67 | R2: 0.41
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:06:57,751] Trial 24 finished with value: 0.42208399501409866 and parameters: {'n_estimators': 300, 'max_depth': 8, 'min_samples_split': 2, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 16 with value: 0.42266742413021285.
[I 2025-07-11 21:06:57,753] A new study created in memory with name: no-name-d2b4aa3f-0298-46c0-83e8-a1670aa0fb2d

Running time: 4.7 sec
OOF RMSE: 2.64 | R2: 0.42

✅ RF - Mejor R2: 0.42
📋 Parámetros: {'n_estimators': 300, 'max_depth': 9, 'min_samples_split': 4, 'min_samples_leaf': 2, 'bootstrap': True}

Buscando mejores hiperparámetros para CAT...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:11:39,555] Trial 0 finished with value: 0.482819667166582 and parameters: {'iterations': 2000, 'learning_rate': 0.020421522502179226, 'depth': 10, 'l2_leaf_reg': 5.260439116324897}. Best is trial 0 with value: 0.482819667166582.

Running time: 281.8 sec
OOF RMSE: 2.49 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:11:43,806] Trial 1 finished with value: 0.4389701486140467 and parameters: {'iterations': 1000, 'learning_rate': 0.011425494964450987, 'depth': 5, 'l2_leaf_reg': 9.75523168142507}. Best is trial 0 with value: 0.482819667166582.

Running time: 4.2 sec
OOF RMSE: 2.60 | R2: 0.44
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:11:50,377] Trial 2 finished with value: 0.501156315171599 and parameters: {'iterations': 1000, 'learning_rate': 0.03482784026260694, 'depth': 6, 'l2_leaf_reg': 4.849266226825792}. Best is trial 2 with value: 0.501156315171599.

Running time: 6.6 sec
OOF RMSE: 2.45 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:11:54,223] Trial 3 finished with value: 0.45771710774448826 and parameters: {'iterations': 1000, 'learning_rate': 0.02422887494465458, 'depth': 5, 'l2_leaf_reg': 9.554857593806792}. Best is trial 2 with value: 0.501156315171599.

Running time: 3.8 sec
OOF RMSE: 2.55 | R2: 0.46
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:11:59,785] Trial 4 finished with value: 0.4901882504302588 and parameters: {'iterations': 2000, 'learning_rate': 0.04977541360128558, 'depth': 4, 'l2_leaf_reg': 6.396634201031622}. Best is trial 2 with value: 0.501156315171599.

Running time: 5.6 sec
OOF RMSE: 2.48 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:16:43,266] Trial 5 finished with value: 0.4354480252270412 and parameters: {'iterations': 2000, 'learning_rate': 0.07895794880642368, 'depth': 10, 'l2_leaf_reg': 9.687431895540652}. Best is trial 2 with value: 0.501156315171599.

Running time: 283.5 sec
OOF RMSE: 2.60 | R2: 0.44
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:17:24,741] Trial 6 finished with value: 0.4574113167627496 and parameters: {'iterations': 500, 'learning_rate': 0.08907023513955752, 'depth': 9, 'l2_leaf_reg': 7.8752837716033}. Best is trial 2 with value: 0.501156315171599.
[I 2025-07-11 21:17:24,742] A new study created in memory with name: no-name-c894647b-e810-4284-a1dc-abc498d327ab
[I 2025-07-11 21:17:24,830] Trial 0 finished with value: 0.437381315894957 and parameters: {'alpha': 0.33455894740175385, 'l1_ratio': 0.286419034687712}. Best is trial 0 with value: 0.437381315894957.

Running time: 41.5 sec
OOF RMSE: 2.55 | R2: 0.46

✅ CAT - Mejor R2: 0.50
📋 Parámetros: {'iterations': 1000, 'learning_rate': 0.03482784026260694, 'depth': 6, 'l2_leaf_reg': 4.849266226825792}

Buscando mejores hiperparámetros para EN...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.60 | R2: 0.44
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.421e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.731e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.758e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.203e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.111e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 21:17:24,963] Trial 1 finished with value: 0.2075708638203837 and parameters: {'alpha': 0.0002412109846479207, 'l1_ratio': 0.4980793089671076}. Best is trial 0 with value: 0.437381315894957.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.535e+01, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.388e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.888e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.404e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.058e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 21:17:25,111] Trial 2 finished with value: 0.3792483747590035 and parameters: {'alpha': 0.006733376563562397, 'l1_ratio': 0.36231259548033323}. Best is trial 0 with value: 0.437381315894957.

Running time: 0.1 sec
OOF RMSE: 3.09 | R2: 0.21
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.73 | R2: 0.38
Fold 1
Fold 2

[I 2025-07-11 21:17:25,205] Trial 3 finished with value: 0.22714965546605426 and parameters: {'alpha': 7.850595836897416, 'l1_ratio': 0.24897354964577523}. Best is trial 0 with value: 0.437381315894957.
[I 2025-07-11 21:17:25,310] Trial 4 finished with value: 0.43025234535819146 and parameters: {'alpha': 0.3967913206164448, 'l1_ratio': 0.6864670739756833}. Best is trial 0 with value: 0.437381315894957.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.05 | R2: 0.23
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.62 | R2: 0.43
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.286e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.668e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.691e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.108e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.954e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 21:17:25,452] Trial 5 finished with value: 0.20620461222020414 and parameters: {'alpha': 0.00027725505743611913, 'l1_ratio': 0.6547216854250387}. Best is trial 0 with value: 0.437381315894957.
[I 2025-07-11 21:17:25,546] Trial 6 finished with value: 0.296078641757729 and parameters: {'alpha': 2.332385529389585, 'l1_ratio': 0.930257189164064}. Best is trial 0 with value: 0.437381315894957.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.09 | R2: 0.21
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.91 | R2: 0.30
Fold 1
Fold 2
Fold 3

[I 2025-07-11 21:17:25,630] Trial 7 finished with value: 0.43452571386480265 and parameters: {'alpha': 0.4620803029486947, 'l1_ratio': 0.29954317955072574}. Best is trial 0 with value: 0.437381315894957.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.545e-01, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.61 | R2: 0.43
Fold 1
Fold 2
Fold 3

[I 2025-07-11 21:17:25,880] Trial 8 finished with value: 0.4156449463821119 and parameters: {'alpha': 0.03320060974228398, 'l1_ratio': 0.5442567330129079}. Best is trial 0 with value: 0.437381315894957.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.217e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.575e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.762e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.967e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.301e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 21:17:26,024] Trial 9 finished with value: 0.3011087049095297 and parameters: {'alpha': 0.001446371509314507, 'l1_ratio': 0.06756466839868258}. Best is trial 0 with value: 0.437381315894957.

Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 2.65 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.90 | R2: 0.30

[I 2025-07-11 21:17:26,155] Trial 10 finished with value: 0.4341889003485492 and parameters: {'alpha': 0.15192153375623757, 'l1_ratio': 0.05138650516017518}. Best is trial 0 with value: 0.437381315894957.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.61 | R2: 0.43
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 21:17:26,274] Trial 11 finished with value: 0.436860041855878 and parameters: {'alpha': 0.40422617313261616, 'l1_ratio': 0.2729884749866687}. Best is trial 0 with value: 0.437381315894957.
[I 2025-07-11 21:17:26,412] Trial 12 finished with value: 0.42479725007513036 and parameters: {'alpha': 0.07823935248351914, 'l1_ratio': 0.20453685298804117}. Best is trial 0 with value: 0.437381315894957.

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.60 | R2: 0.44
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.63 | R2: 0.42
Fold 1
Fold 2

[I 2025-07-11 21:17:26,515] Trial 13 finished with value: 0.41087545045790685 and parameters: {'alpha': 1.3198630224574721, 'l1_ratio': 0.4225913402834887}. Best is trial 0 with value: 0.437381315894957.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.128e+01, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.078e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.609e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.214e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.664e+01, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 21:17:26,651] Trial 14 finished with value: 0.38551376119168446 and parameters: {'alpha': 0.013156806029801675, 'l1_ratio': 0.17694284651766023}. Best is trial 0 with value: 0.437381315894957.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.66 | R2: 0.41
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.72 | R2: 0.39
Fold 1

[I 2025-07-11 21:17:26,752] Trial 15 finished with value: 0.27429301230161995 and parameters: {'alpha': 9.912668888204825, 'l1_ratio': 0.12379821441213956}. Best is trial 0 with value: 0.437381315894957.
[I 2025-07-11 21:17:26,842] Trial 16 finished with value: 0.4353518551568304 and parameters: {'alpha': 0.27788038190707937, 'l1_ratio': 0.37563254171034843}. Best is trial 0 with value: 0.437381315894957.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.95 | R2: 0.27
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.60 | R2: 0.44
Fold 1
Fold 2

[I 2025-07-11 21:17:26,971] Trial 17 finished with value: 0.44724429854619374 and parameters: {'alpha': 1.1610046015227193, 'l1_ratio': 0.00021358542063354413}. Best is trial 17 with value: 0.44724429854619374.
[I 2025-07-11 21:17:27,058] Trial 18 finished with value: 0.35408763380362085 and parameters: {'alpha': 1.5466178325663789, 'l1_ratio': 0.9722863721744973}. Best is trial 17 with value: 0.44724429854619374.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.58 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.79 | R2: 0.35
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.693e+00, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.086e+00, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.283e+00, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.080e+01, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.889e+00, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 21:17:27,218] Trial 19 finished with value: 0.41593488899485764 and parameters: {'alpha': 0.05719211858637925, 'l1_ratio': 0.02635736141237362}. Best is trial 17 with value: 0.44724429854619374.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 2.65 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:17:27,314] Trial 20 finished with value: 0.28924866660822246 and parameters: {'alpha': 2.712613600357272, 'l1_ratio': 0.7620101740479075}. Best is trial 17 with value: 0.44724429854619374.
[I 2025-07-11 21:17:27,398] Trial 21 finished with value: 0.4301147100203868 and parameters: {'alpha': 0.7587202804571506, 'l1_ratio': 0.27190864761838}. Best is trial 17 with value: 0.44724429854619374.

Running time: 0.1 sec
OOF RMSE: 2.92 | R2: 0.29
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.62 | R2: 0.43
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:17:27,525] Trial 22 finished with value: 0.4320117309484214 and parameters: {'alpha': 0.12383650510989437, 'l1_ratio': 0.15446282143020468}. Best is trial 17 with value: 0.44724429854619374.
[I 2025-07-11 21:17:27,622] Trial 23 finished with value: 0.26429122533737714 and parameters: {'alpha': 4.369309894983191, 'l1_ratio': 0.4599041957911658}. Best is trial 17 with value: 0.44724429854619374.
[I 2025-07-11 21:17:27,721] Trial 24 finished with value: 0.42777886642416274 and parameters: {'alpha': 0.7090150224657706, 'l1_ratio': 0.3452833429233295}. Best is trial 17 with value: 0.44724429854619374.
[I 2025-07-11 21:17:27,722] A new study created in memory with name: no-name-8a494a66-9dd3-4d09-837e-5e54b11d7e14

Running time: 0.1 sec
OOF RMSE: 2.61 | R2: 0.43
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.97 | R2: 0.26
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.62 | R2: 0.43

✅ EN - Mejor R2: 0.45
📋 Parámetros: {'alpha': 1.1610046015227193, 'l1_ratio': 0.00021358542063354413}

🔍 Optimizando en C2RCC_rhown_5x5_depth_lt_1...
Buscando mejores hiperparámetros para XGB...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:17:30,491] Trial 0 finished with value: 0.6841537004555471 and parameters: {'n_estimators': 500, 'learning_rate': 0.006139327960467776, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.9096912975002868, 'colsample_bytree': 0.6925322923498378}. Best is trial 0 with value: 0.6841537004555471.

Running time: 2.8 sec
OOF RMSE: 1.95 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:17:37,368] Trial 1 finished with value: 0.7108700285969847 and parameters: {'n_estimators': 2000, 'learning_rate': 0.07917011134190674, 'max_depth': 8, 'min_child_weight': 2, 'subsample': 0.728491164688519, 'colsample_bytree': 0.66229060970914}. Best is trial 1 with value: 0.7108700285969847.

Running time: 6.9 sec
OOF RMSE: 1.86 | R2: 0.71
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:17:39,956] Trial 2 finished with value: 0.6836253749036554 and parameters: {'n_estimators': 500, 'learning_rate': 0.015021553801375853, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.9355794582325898, 'colsample_bytree': 0.6155253508971636}. Best is trial 1 with value: 0.7108700285969847.

Running time: 2.6 sec
OOF RMSE: 1.95 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:17:44,706] Trial 3 finished with value: 0.6807569360145187 and parameters: {'n_estimators': 500, 'learning_rate': 0.009954687030451373, 'max_depth': 8, 'min_child_weight': 1, 'subsample': 0.8248740719274786, 'colsample_bytree': 0.8838039362064745}. Best is trial 1 with value: 0.7108700285969847.

Running time: 4.7 sec
OOF RMSE: 1.96 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:17:56,284] Trial 4 finished with value: 0.6930060714726554 and parameters: {'n_estimators': 2000, 'learning_rate': 0.008347811045514941, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.6324734605990386, 'colsample_bytree': 0.7786248302826759}. Best is trial 1 with value: 0.7108700285969847.

Running time: 11.6 sec
OOF RMSE: 1.92 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:17:58,962] Trial 5 finished with value: 0.6856501436581663 and parameters: {'n_estimators': 500, 'learning_rate': 0.010196430863059016, 'max_depth': 5, 'min_child_weight': 1, 'subsample': 0.8392099978686776, 'colsample_bytree': 0.8632014268186893}. Best is trial 1 with value: 0.7108700285969847.

Running time: 2.7 sec
OOF RMSE: 1.94 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:18:05,725] Trial 6 finished with value: 0.6592284258193333 and parameters: {'n_estimators': 2000, 'learning_rate': 0.07924284354897868, 'max_depth': 6, 'min_child_weight': 1, 'subsample': 0.8602742853612237, 'colsample_bytree': 0.8127265892934961}. Best is trial 1 with value: 0.7108700285969847.

Running time: 6.8 sec
OOF RMSE: 2.02 | R2: 0.66
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:18:10,455] Trial 7 finished with value: 0.6908220178054546 and parameters: {'n_estimators': 1000, 'learning_rate': 0.019175107877425494, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.8126930909447041, 'colsample_bytree': 0.780793015214349}. Best is trial 1 with value: 0.7108700285969847.

Running time: 4.7 sec
OOF RMSE: 1.93 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:18:13,087] Trial 8 finished with value: 0.674584835445125 and parameters: {'n_estimators': 500, 'learning_rate': 0.013081112924114735, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.9046404575536213, 'colsample_bytree': 0.876247106579545}. Best is trial 1 with value: 0.7108700285969847.

Running time: 2.6 sec
OOF RMSE: 1.98 | R2: 0.67
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:18:18,613] Trial 9 finished with value: 0.6655067501846048 and parameters: {'n_estimators': 1000, 'learning_rate': 0.005854479042260232, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.8077568004448535, 'colsample_bytree': 0.9764979955703391}. Best is trial 1 with value: 0.7108700285969847.

Running time: 5.5 sec
OOF RMSE: 2.00 | R2: 0.67
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:18:26,475] Trial 10 finished with value: 0.6843521328788261 and parameters: {'n_estimators': 2000, 'learning_rate': 0.0677468142438597, 'max_depth': 8, 'min_child_weight': 2, 'subsample': 0.6916047662489362, 'colsample_bytree': 0.6018627952201646}. Best is trial 1 with value: 0.7108700285969847.

Running time: 7.9 sec
OOF RMSE: 1.95 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:18:36,470] Trial 11 finished with value: 0.6780001755413259 and parameters: {'n_estimators': 2000, 'learning_rate': 0.039209345845797196, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.6018633059481482, 'colsample_bytree': 0.7198359174436185}. Best is trial 1 with value: 0.7108700285969847.

Running time: 10.0 sec
OOF RMSE: 1.97 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:18:46,769] Trial 12 finished with value: 0.6722734837674857 and parameters: {'n_estimators': 2000, 'learning_rate': 0.037830940496396334, 'max_depth': 8, 'min_child_weight': 3, 'subsample': 0.7259852212634578, 'colsample_bytree': 0.6922495164593924}. Best is trial 1 with value: 0.7108700285969847.

Running time: 10.3 sec
OOF RMSE: 1.98 | R2: 0.67
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:18:58,002] Trial 13 finished with value: 0.680203128299157 and parameters: {'n_estimators': 2000, 'learning_rate': 0.02868470477707258, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.6383299319610888, 'colsample_bytree': 0.7568161020751777}. Best is trial 1 with value: 0.7108700285969847.

Running time: 11.2 sec
OOF RMSE: 1.96 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:19:06,526] Trial 14 finished with value: 0.6632678936160543 and parameters: {'n_estimators': 2000, 'learning_rate': 0.05223108706444651, 'max_depth': 8, 'min_child_weight': 3, 'subsample': 0.7349215469425653, 'colsample_bytree': 0.6468186669409876}. Best is trial 1 with value: 0.7108700285969847.

Running time: 8.5 sec
OOF RMSE: 2.01 | R2: 0.66
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:19:19,533] Trial 15 finished with value: 0.6693475082719271 and parameters: {'n_estimators': 2000, 'learning_rate': 0.023414775028545273, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.6839929301782367, 'colsample_bytree': 0.9781652519594376}. Best is trial 1 with value: 0.7108700285969847.

Running time: 13.0 sec
OOF RMSE: 1.99 | R2: 0.67
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:19:30,004] Trial 16 finished with value: 0.6809850715453639 and parameters: {'n_estimators': 2000, 'learning_rate': 0.008394054216738825, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.7546414884575686, 'colsample_bytree': 0.8294704424609828}. Best is trial 1 with value: 0.7108700285969847.

Running time: 10.5 sec
OOF RMSE: 1.96 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:19:34,382] Trial 17 finished with value: 0.6925168885057879 and parameters: {'n_estimators': 1000, 'learning_rate': 0.09870834804139915, 'max_depth': 8, 'min_child_weight': 2, 'subsample': 0.64877216415994, 'colsample_bytree': 0.7421390482410238}. Best is trial 1 with value: 0.7108700285969847.

Running time: 4.4 sec
OOF RMSE: 1.92 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:19:41,845] Trial 18 finished with value: 0.6764889344566378 and parameters: {'n_estimators': 2000, 'learning_rate': 0.047295134165368735, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.9892813115096982, 'colsample_bytree': 0.6564639697237681}. Best is trial 1 with value: 0.7108700285969847.

Running time: 7.5 sec
OOF RMSE: 1.97 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:19:53,669] Trial 19 finished with value: 0.6733526223021626 and parameters: {'n_estimators': 2000, 'learning_rate': 0.027917670372899193, 'max_depth': 8, 'min_child_weight': 2, 'subsample': 0.7731813045501168, 'colsample_bytree': 0.9144709871162192}. Best is trial 1 with value: 0.7108700285969847.

Running time: 11.8 sec
OOF RMSE: 1.98 | R2: 0.67
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:19:59,748] Trial 20 finished with value: 0.685657465874419 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01627179212712432, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.6842479006276804, 'colsample_bytree': 0.7806415671558715}. Best is trial 1 with value: 0.7108700285969847.

Running time: 6.1 sec
OOF RMSE: 1.94 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:20:04,088] Trial 21 finished with value: 0.6956678328125417 and parameters: {'n_estimators': 1000, 'learning_rate': 0.09901001692759266, 'max_depth': 8, 'min_child_weight': 2, 'subsample': 0.6344761875328552, 'colsample_bytree': 0.7176634960782732}. Best is trial 1 with value: 0.7108700285969847.

Running time: 4.3 sec
OOF RMSE: 1.91 | R2: 0.70
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:20:07,905] Trial 22 finished with value: 0.6838162715076963 and parameters: {'n_estimators': 1000, 'learning_rate': 0.09826781201499668, 'max_depth': 8, 'min_child_weight': 2, 'subsample': 0.6066510615229552, 'colsample_bytree': 0.6752594518664647}. Best is trial 1 with value: 0.7108700285969847.

Running time: 3.8 sec
OOF RMSE: 1.95 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:20:14,203] Trial 23 finished with value: 0.6694703797968049 and parameters: {'n_estimators': 1000, 'learning_rate': 0.06171171472616702, 'max_depth': 8, 'min_child_weight': 1, 'subsample': 0.6405345238885244, 'colsample_bytree': 0.7284425103396273}. Best is trial 1 with value: 0.7108700285969847.

Running time: 6.3 sec
OOF RMSE: 1.99 | R2: 0.67
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:20:19,307] Trial 24 finished with value: 0.689820197519018 and parameters: {'n_estimators': 1000, 'learning_rate': 0.07660359322615944, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.7161050553829347, 'colsample_bytree': 0.7090459631107648}. Best is trial 1 with value: 0.7108700285969847.
[I 2025-07-11 21:20:19,308] A new study created in memory with name: no-name-184181c0-9296-4fa2-9170-c60a3e9bd1a7

Running time: 5.1 sec
OOF RMSE: 1.93 | R2: 0.69

✅ XGB - Mejor R2: 0.71
📋 Parámetros: {'n_estimators': 2000, 'learning_rate': 0.07917011134190674, 'max_depth': 8, 'min_child_weight': 2, 'subsample': 0.728491164688519, 'colsample_bytree': 0.66229060970914}

Buscando mejores hiperparámetros para LBM...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:20:19,542] Trial 0 finished with value: 0.6826578165936155 and parameters: {'learning_rate': 0.06840355386266532, 'num_leaves': 60, 'max_depth': 5, 'min_child_samples': 10, 'subsample': 0.6965510927334336, 'colsample_bytree': 0.6194103812704387, 'n_estimators': 500}. Best is trial 0 with value: 0.6826578165936155.

Running time: 0.2 sec
OOF RMSE: 1.95 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:20:20,042] Trial 1 finished with value: 0.6038642073200238 and parameters: {'learning_rate': 0.07649003769740845, 'num_leaves': 60, 'max_depth': 7, 'min_child_samples': 25, 'subsample': 0.9056814633895371, 'colsample_bytree': 0.8786592082705975, 'n_estimators': 1000}. Best is trial 0 with value: 0.6826578165936155.

Running time: 0.5 sec
OOF RMSE: 2.18 | R2: 0.60
Fold 1
Fold 2
Fold 3

[I 2025-07-11 21:20:20,472] Trial 2 finished with value: 0.6128390772655337 and parameters: {'learning_rate': 0.011510729798052148, 'num_leaves': 40, 'max_depth': 5, 'min_child_samples': 21, 'subsample': 0.8682616170917579, 'colsample_bytree': 0.7594736268723794, 'n_estimators': 1000}. Best is trial 0 with value: 0.6826578165936155.

Fold 4
Fold 5
Running time: 0.4 sec
OOF RMSE: 2.16 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:20:20,747] Trial 3 finished with value: 0.6613925774194521 and parameters: {'learning_rate': 0.0326188220299418, 'num_leaves': 60, 'max_depth': 5, 'min_child_samples': 7, 'subsample': 0.9803727342994296, 'colsample_bytree': 0.7035516163515625, 'n_estimators': 500}. Best is trial 0 with value: 0.6826578165936155.

Running time: 0.3 sec
OOF RMSE: 2.02 | R2: 0.66
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 21:20:21,583] Trial 4 finished with value: 0.600977823731065 and parameters: {'learning_rate': 0.014475232823062694, 'num_leaves': 80, 'max_depth': 5, 'min_child_samples': 24, 'subsample': 0.9795144056668876, 'colsample_bytree': 0.9333725563006889, 'n_estimators': 2000}. Best is trial 0 with value: 0.6826578165936155.

Fold 5
Running time: 0.8 sec
OOF RMSE: 2.19 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:20:22,583] Trial 5 finished with value: 0.7030760801919292 and parameters: {'learning_rate': 0.021587981542743096, 'num_leaves': 60, 'max_depth': 6, 'min_child_samples': 14, 'subsample': 0.8356200747355901, 'colsample_bytree': 0.957541354070224, 'n_estimators': 2000}. Best is trial 5 with value: 0.7030760801919292.

Running time: 1.0 sec
OOF RMSE: 1.89 | R2: 0.70
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:20:23,653] Trial 6 finished with value: 0.6479204528079476 and parameters: {'learning_rate': 0.008019275867788932, 'num_leaves': 40, 'max_depth': 8, 'min_child_samples': 16, 'subsample': 0.8929177608330787, 'colsample_bytree': 0.6101520358026298, 'n_estimators': 2000}. Best is trial 5 with value: 0.7030760801919292.

Running time: 1.1 sec
OOF RMSE: 2.06 | R2: 0.65
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:20:24,735] Trial 7 finished with value: 0.6852540615673883 and parameters: {'learning_rate': 0.014493821072899083, 'num_leaves': 40, 'max_depth': 7, 'min_child_samples': 15, 'subsample': 0.9233265118048386, 'colsample_bytree': 0.9091847053630536, 'n_estimators': 2000}. Best is trial 5 with value: 0.7030760801919292.

Running time: 1.1 sec
OOF RMSE: 1.94 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:20:24,956] Trial 8 finished with value: 0.653575710310079 and parameters: {'learning_rate': 0.0857487138391576, 'num_leaves': 60, 'max_depth': 5, 'min_child_samples': 16, 'subsample': 0.9536474652294205, 'colsample_bytree': 0.6820150829301754, 'n_estimators': 500}. Best is trial 5 with value: 0.7030760801919292.

Running time: 0.2 sec
OOF RMSE: 2.04 | R2: 0.65
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:20:26,198] Trial 9 finished with value: 0.6935449193818115 and parameters: {'learning_rate': 0.019009054610825825, 'num_leaves': 80, 'max_depth': 8, 'min_child_samples': 13, 'subsample': 0.612349999663297, 'colsample_bytree': 0.8029851381565718, 'n_estimators': 2000}. Best is trial 5 with value: 0.7030760801919292.

Running time: 1.2 sec
OOF RMSE: 1.92 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:20:27,148] Trial 10 finished with value: 0.6417291275018173 and parameters: {'learning_rate': 0.03567025719736513, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 20, 'subsample': 0.7871115592846021, 'colsample_bytree': 0.9937489650373674, 'n_estimators': 2000}. Best is trial 5 with value: 0.7030760801919292.

Running time: 0.9 sec
OOF RMSE: 2.07 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:20:28,380] Trial 11 finished with value: 0.703491567151144 and parameters: {'learning_rate': 0.025286040013245803, 'num_leaves': 80, 'max_depth': 8, 'min_child_samples': 12, 'subsample': 0.610885216951345, 'colsample_bytree': 0.8189232424613758, 'n_estimators': 2000}. Best is trial 11 with value: 0.703491567151144.

Running time: 1.2 sec
OOF RMSE: 1.89 | R2: 0.70
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 21:20:29,390] Trial 12 finished with value: 0.6881063948631847 and parameters: {'learning_rate': 0.029763108573501392, 'num_leaves': 80, 'max_depth': 6, 'min_child_samples': 11, 'subsample': 0.7768061838002343, 'colsample_bytree': 0.8249093141446693, 'n_estimators': 2000}. Best is trial 11 with value: 0.703491567151144.

Fold 5
Running time: 1.0 sec
OOF RMSE: 1.94 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:20:30,831] Trial 13 finished with value: 0.6281986545340869 and parameters: {'learning_rate': 0.049733258153855625, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 6, 'subsample': 0.7157890934676637, 'colsample_bytree': 0.9810214682598745, 'n_estimators': 2000}. Best is trial 11 with value: 0.703491567151144.

Running time: 1.4 sec
OOF RMSE: 2.11 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:20:31,860] Trial 14 finished with value: 0.6282566056346264 and parameters: {'learning_rate': 0.005147169030824838, 'num_leaves': 80, 'max_depth': 6, 'min_child_samples': 9, 'subsample': 0.6150134051184657, 'colsample_bytree': 0.8535505187484136, 'n_estimators': 2000}. Best is trial 11 with value: 0.703491567151144.

Running time: 1.0 sec
OOF RMSE: 2.11 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 21:20:32,518] Trial 15 finished with value: 0.6943780204775132 and parameters: {'learning_rate': 0.021112868769142628, 'num_leaves': 60, 'max_depth': 8, 'min_child_samples': 13, 'subsample': 0.8301358864882807, 'colsample_bytree': 0.7530202120997334, 'n_estimators': 1000}. Best is trial 11 with value: 0.703491567151144.

Fold 5
Running time: 0.7 sec
OOF RMSE: 1.92 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:20:33,614] Trial 16 finished with value: 0.6667314138173297 and parameters: {'learning_rate': 0.0451562717158267, 'num_leaves': 80, 'max_depth': 7, 'min_child_samples': 19, 'subsample': 0.7131731259291204, 'colsample_bytree': 0.9205450684335635, 'n_estimators': 2000}. Best is trial 11 with value: 0.703491567151144.

Running time: 1.1 sec
OOF RMSE: 2.00 | R2: 0.67
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:20:34,571] Trial 17 finished with value: 0.7049041445682565 and parameters: {'learning_rate': 0.024094675577121107, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 14, 'subsample': 0.830549917599108, 'colsample_bytree': 0.9544792652786884, 'n_estimators': 2000}. Best is trial 17 with value: 0.7049041445682565.

Running time: 1.0 sec
OOF RMSE: 1.88 | R2: 0.70
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 21:20:35,154] Trial 18 finished with value: 0.6043431028579551 and parameters: {'learning_rate': 0.009960420793662786, 'num_leaves': 20, 'max_depth': 8, 'min_child_samples': 18, 'subsample': 0.6553260065133043, 'colsample_bytree': 0.8687238468473993, 'n_estimators': 1000}. Best is trial 17 with value: 0.7049041445682565.

Fold 5
Running time: 0.6 sec
OOF RMSE: 2.18 | R2: 0.60
Fold 1
Fold 2

[I 2025-07-11 21:20:35,485] Trial 19 finished with value: 0.6853799993115905 and parameters: {'learning_rate': 0.04867739031310048, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 11, 'subsample': 0.7523614705322722, 'colsample_bytree': 0.7597254261728639, 'n_estimators': 500}. Best is trial 17 with value: 0.7049041445682565.

Fold 3
Fold 4
Fold 5
Running time: 0.3 sec
OOF RMSE: 1.94 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:20:36,523] Trial 20 finished with value: 0.6603283535786374 and parameters: {'learning_rate': 0.026487236904769354, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 8, 'subsample': 0.8406095820833713, 'colsample_bytree': 0.8382674756766014, 'n_estimators': 2000}. Best is trial 17 with value: 0.7049041445682565.

Running time: 1.0 sec
OOF RMSE: 2.02 | R2: 0.66
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 21:20:37,530] Trial 21 finished with value: 0.6983575182463089 and parameters: {'learning_rate': 0.020423407449295054, 'num_leaves': 60, 'max_depth': 6, 'min_child_samples': 13, 'subsample': 0.8164350708361432, 'colsample_bytree': 0.948877163659694, 'n_estimators': 2000}. Best is trial 17 with value: 0.7049041445682565.

Fold 5
Running time: 1.0 sec
OOF RMSE: 1.90 | R2: 0.70
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 21:20:38,548] Trial 22 finished with value: 0.6987859084550708 and parameters: {'learning_rate': 0.015281744878449747, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 13, 'subsample': 0.856254276176065, 'colsample_bytree': 0.9671125719759504, 'n_estimators': 2000}. Best is trial 17 with value: 0.7049041445682565.

Fold 5
Running time: 1.0 sec
OOF RMSE: 1.90 | R2: 0.70
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:20:39,511] Trial 23 finished with value: 0.6860046704856613 and parameters: {'learning_rate': 0.025025574890311212, 'num_leaves': 80, 'max_depth': 6, 'min_child_samples': 15, 'subsample': 0.7611331642252179, 'colsample_bytree': 0.8931743211079447, 'n_estimators': 2000}. Best is trial 17 with value: 0.7049041445682565.

Running time: 1.0 sec
OOF RMSE: 1.94 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:20:40,627] Trial 24 finished with value: 0.6647028050495344 and parameters: {'learning_rate': 0.03861585181204191, 'num_leaves': 80, 'max_depth': 7, 'min_child_samples': 17, 'subsample': 0.8034315802247548, 'colsample_bytree': 0.9441933914056359, 'n_estimators': 2000}. Best is trial 17 with value: 0.7049041445682565.
[I 2025-07-11 21:20:40,628] A new study created in memory with name: no-name-32314057-e281-46bf-8c72-9ed5b1b9c6bd

Running time: 1.1 sec
OOF RMSE: 2.01 | R2: 0.66

✅ LBM - Mejor R2: 0.70
📋 Parámetros: {'learning_rate': 0.024094675577121107, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 14, 'subsample': 0.830549917599108, 'colsample_bytree': 0.9544792652786884, 'n_estimators': 2000}

Buscando mejores hiperparámetros para MLP...
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

[I 2025-07-11 21:20:41,727] Trial 0 finished with value: 0.29692841250360846 and parameters: {'hidden_layer_sizes': '50', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.00018677586974634222, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0003208952034103755}. Best is trial 0 with value: 0.29692841250360846.

Running time: 1.1 sec
OOF RMSE: 2.91 | R2: 0.30
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 21:20:43,247] Trial 1 finished with value: 0.5246398081530685 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.006749089702727603, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0006676312960721656}. Best is trial 1 with value: 0.5246398081530685.

Fold 4
Fold 5
Running time: 1.5 sec
OOF RMSE: 2.39 | R2: 0.52
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

[I 2025-07-11 21:20:46,201] Trial 2 finished with value: 0.5029721815516606 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.0005300857256362782, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0005753236876271104}. Best is trial 1 with value: 0.5246398081530685.

Running time: 2.9 sec
OOF RMSE: 2.44 | R2: 0.50
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 21:20:47,374] Trial 3 finished with value: 0.44884911503780833 and parameters: {'hidden_layer_sizes': '50', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0019856416121171432, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0018315338744184597}. Best is trial 1 with value: 0.5246398081530685.

Fold 4
Fold 5
Running time: 1.2 sec
OOF RMSE: 2.57 | R2: 0.45
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

[I 2025-07-11 21:20:49,835] Trial 4 finished with value: 0.5469569221295885 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.013164542404570075, 'learning_rate': 'constant', 'learning_rate_init': 0.00013206253518415102}. Best is trial 4 with value: 0.5469569221295885.

Running time: 2.5 sec
OOF RMSE: 2.33 | R2: 0.55
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

[I 2025-07-11 21:20:50,977] Trial 5 finished with value: 0.4840743476826067 and parameters: {'hidden_layer_sizes': '50', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.0004889511177294295, 'learning_rate': 'adaptive', 'learning_rate_init': 0.002022240070434148}. Best is trial 4 with value: 0.5469569221295885.

Running time: 1.1 sec
OOF RMSE: 2.49 | R2: 0.48
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 21:20:53,162] Trial 6 finished with value: 0.6056641458986318 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 3.64442589958767e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.00022381268640766182}. Best is trial 6 with value: 0.6056641458986318.

Fold 5
Running time: 2.2 sec
OOF RMSE: 2.18 | R2: 0.61
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 21:20:55,160] Trial 7 finished with value: 0.629800419883934 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.0036512859644736734, 'learning_rate': 'constant', 'learning_rate_init': 0.0012218382130985063}. Best is trial 7 with value: 0.629800419883934.

Running time: 2.0 sec
OOF RMSE: 2.11 | R2: 0.63
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

[I 2025-07-11 21:20:56,261] Trial 8 finished with value: 0.37307054144178065 and parameters: {'hidden_layer_sizes': '50', 'activation': 'relu', 'solver': 'adam', 'alpha': 5.9659700956209024e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.00021776581861275609}. Best is trial 7 with value: 0.629800419883934.

Fold 5
Running time: 1.1 sec
OOF RMSE: 2.74 | R2: 0.37
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 21:20:57,117] Trial 9 finished with value: 0.6260408340062731 and parameters: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.000258031124107846, 'learning_rate': 'adaptive', 'learning_rate_init': 0.003266809515719268}. Best is trial 7 with value: 0.629800419883934.

Running time: 0.8 sec
OOF RMSE: 2.12 | R2: 0.63
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3
Fold 4

[I 2025-07-11 21:20:58,664] Trial 10 finished with value: 0.7063164064185826 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.06482263467905276, 'learning_rate': 'constant', 'learning_rate_init': 0.009720301909593351}. Best is trial 10 with value: 0.7063164064185826.

Fold 5
Running time: 1.5 sec
OOF RMSE: 1.88 | R2: 0.71
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 21:21:00,203] Trial 11 finished with value: 0.7061868832900333 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.09090186967846596, 'learning_rate': 'constant', 'learning_rate_init': 0.009772088578961762}. Best is trial 10 with value: 0.7063164064185826.

Fold 5
Running time: 1.5 sec
OOF RMSE: 1.88 | R2: 0.71
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 21:21:01,703] Trial 12 finished with value: 0.7087368596703141 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.06607744775043728, 'learning_rate': 'constant', 'learning_rate_init': 0.009864687695645677}. Best is trial 12 with value: 0.7087368596703141.

Fold 5
Running time: 1.5 sec
OOF RMSE: 1.87 | R2: 0.71
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:21:02,732] Trial 13 finished with value: 0.6099275392779269 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.08539242575264219, 'learning_rate': 'constant', 'learning_rate_init': 0.009037393556502299}. Best is trial 12 with value: 0.7087368596703141.

Running time: 1.0 sec
OOF RMSE: 2.17 | R2: 0.61
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

[I 2025-07-11 21:21:03,975] Trial 14 finished with value: 0.5810834833661784 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.023458201398045317, 'learning_rate': 'constant', 'learning_rate_init': 0.004650474172850986}. Best is trial 12 with value: 0.7087368596703141.

Fold 4
Fold 5
Running time: 1.2 sec
OOF RMSE: 2.24 | R2: 0.58
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3
Fold 4

[I 2025-07-11 21:21:05,417] Trial 15 finished with value: 0.5827807327893022 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.027260326928841495, 'learning_rate': 'constant', 'learning_rate_init': 0.005477173035426907}. Best is trial 12 with value: 0.7087368596703141.

Fold 5
Running time: 1.4 sec
OOF RMSE: 2.24 | R2: 0.58
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

[I 2025-07-11 21:21:06,949] Trial 16 finished with value: 0.6064644582594279 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.04111893732213992, 'learning_rate': 'constant', 'learning_rate_init': 0.005414502783471598}. Best is trial 12 with value: 0.7087368596703141.

Fold 4
Fold 5
Running time: 1.5 sec
OOF RMSE: 2.17 | R2: 0.61
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

[I 2025-07-11 21:21:08,347] Trial 17 finished with value: 0.5756233631407905 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.008957462743755864, 'learning_rate': 'constant', 'learning_rate_init': 0.003122622042692836}. Best is trial 12 with value: 0.7087368596703141.

Fold 4
Fold 5
Running time: 1.4 sec
OOF RMSE: 2.26 | R2: 0.58
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 21:21:10,098] Trial 18 finished with value: 0.7144143480555103 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.0019997367482926564, 'learning_rate': 'constant', 'learning_rate_init': 0.007981278386049314}. Best is trial 18 with value: 0.7144143480555103.

Fold 5
Running time: 1.7 sec
OOF RMSE: 1.85 | R2: 0.71
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

[I 2025-07-11 21:21:12,009] Trial 19 finished with value: 0.5806169266111225 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.0015194556311128179, 'learning_rate': 'constant', 'learning_rate_init': 0.0028774728368925724}. Best is trial 18 with value: 0.7144143480555103.

Fold 4
Fold 5
Running time: 1.9 sec
OOF RMSE: 2.24 | R2: 0.58
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 21:21:13,134] Trial 20 finished with value: 0.6387086069688467 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.004732450544135071, 'learning_rate': 'constant', 'learning_rate_init': 0.0057675346902520755}. Best is trial 18 with value: 0.7144143480555103.

Running time: 1.1 sec
OOF RMSE: 2.08 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 21:21:14,529] Trial 21 finished with value: 0.7055575992605541 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.04712682928399909, 'learning_rate': 'constant', 'learning_rate_init': 0.009809187850783224}. Best is trial 18 with value: 0.7144143480555103.

Fold 5
Running time: 1.4 sec
OOF RMSE: 1.88 | R2: 0.71
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3
Fold 4

[I 2025-07-11 21:21:16,185] Trial 22 finished with value: 0.6075220700296793 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 1.3031177550901942e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.006745192732742195}. Best is trial 18 with value: 0.7144143480555103.

Fold 5
Running time: 1.7 sec
OOF RMSE: 2.17 | R2: 0.61
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:21:17,928] Trial 23 finished with value: 0.6003641351716276 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.014593714503538321, 'learning_rate': 'constant', 'learning_rate_init': 0.003837295258426299}. Best is trial 18 with value: 0.7144143480555103.

Running time: 1.7 sec
OOF RMSE: 2.19 | R2: 0.60
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

[I 2025-07-11 21:21:19,113] Trial 24 finished with value: 0.6192886890405123 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.09990333039955676, 'learning_rate': 'constant', 'learning_rate_init': 0.007281700060814075}. Best is trial 18 with value: 0.7144143480555103.
[I 2025-07-11 21:21:19,115] A new study created in memory with name: no-name-c25ba9dd-20ba-4af3-826b-d5b46c10c130

Fold 4
Fold 5
Running time: 1.2 sec
OOF RMSE: 2.14 | R2: 0.62

✅ MLP - Mejor R2: 0.71
📋 Parámetros: {'hidden_layer_sizes': '100_50', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.0019997367482926564, 'learning_rate': 'constant', 'learning_rate_init': 0.007981278386049314}

Buscando mejores hiperparámetros para SVR...
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 21:21:19,201] Trial 0 finished with value: 0.4607964199127824 and parameters: {'kernel': 'rbf', 'C': 4.4531750797095935, 'epsilon': 0.15988000594661142, 'gamma': 'auto'}. Best is trial 0 with value: 0.4607964199127824.
[I 2025-07-11 21:21:19,276] Trial 1 finished with value: 0.4594078016388984 and parameters: {'kernel': 'rbf', 'C': 4.397663598271278, 'epsilon': 0.015844029362547647, 'gamma': 'auto'}. Best is trial 0 with value: 0.4607964199127824.
[I 2025-07-11 21:21:19,347] Trial 2 finished with value: 0.14215212176766567 and parameters: {'kernel': 'rbf', 'C': 0.23514915945490245, 'epsilon': 0.15110218571447728, 'gamma': 'auto'}. Best is trial 0 with value: 0.4607964199127824.

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.55 | R2: 0.46
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.55 | R2: 0.46
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.21 | R2: 0.14
Fold 1
Fold 2
Fold 3

[I 2025-07-11 21:21:19,424] Trial 3 finished with value: -194.13815399929217 and parameters: {'kernel': 'sigmoid', 'C': 7.664008618394792, 'epsilon': 0.18331800037167217, 'gamma': 'scale'}. Best is trial 0 with value: 0.4607964199127824.
[I 2025-07-11 21:21:19,497] Trial 4 finished with value: 0.2694074765068686 and parameters: {'kernel': 'rbf', 'C': 0.8889304047932264, 'epsilon': 0.11100455459723743, 'gamma': 'scale'}. Best is trial 0 with value: 0.4607964199127824.
[I 2025-07-11 21:21:19,570] Trial 5 finished with value: 0.038240878977895076 and parameters: {'kernel': 'sigmoid', 'C': 0.2715085085474512, 'epsilon': 0.08341436871281872, 'gamma': 'auto'}. Best is trial 0 with value: 0.4607964199127824.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 48.42 | R2: -194.14
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.96 | R2: 0.27
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.40 | R2: 0.04
Fold 1
Fold 2
Fold 3

[I 2025-07-11 21:21:19,633] Trial 6 finished with value: 0.17415433017099147 and parameters: {'kernel': 'rbf', 'C': 0.3205885264957769, 'epsilon': 0.0671857929571345, 'gamma': 'scale'}. Best is trial 0 with value: 0.4607964199127824.
[I 2025-07-11 21:21:19,699] Trial 7 finished with value: 0.10192187661239194 and parameters: {'kernel': 'rbf', 'C': 0.1279761265845444, 'epsilon': 0.1634674300445735, 'gamma': 'scale'}. Best is trial 0 with value: 0.4607964199127824.
[I 2025-07-11 21:21:19,768] Trial 8 finished with value: 0.2532522609480733 and parameters: {'kernel': 'rbf', 'C': 0.7261015497739832, 'epsilon': 0.14456661577935467, 'gamma': 'scale'}. Best is trial 0 with value: 0.4607964199127824.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.15 | R2: 0.17
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.29 | R2: 0.10
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.00 | R2: 0.25
Fold 1
Fold 2
Fold 3

[I 2025-07-11 21:21:19,841] Trial 9 finished with value: 0.04843620248687952 and parameters: {'kernel': 'sigmoid', 'C': 0.25455634661411597, 'epsilon': 0.04178750766179994, 'gamma': 'auto'}. Best is trial 0 with value: 0.4607964199127824.
[I 2025-07-11 21:21:19,920] Trial 10 finished with value: -12.011340833338187 and parameters: {'kernel': 'sigmoid', 'C': 2.5180275178263942, 'epsilon': 0.1969863118375645, 'gamma': 'auto'}. Best is trial 0 with value: 0.4607964199127824.
[I 2025-07-11 21:21:20,006] Trial 11 finished with value: 0.491890535849561 and parameters: {'kernel': 'rbf', 'C': 5.588534555941301, 'epsilon': 0.02601567454712613, 'gamma': 'auto'}. Best is trial 11 with value: 0.491890535849561.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.38 | R2: 0.05
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 12.50 | R2: -12.01
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.47 | R2: 0.49

[I 2025-07-11 21:21:20,083] Trial 12 finished with value: 0.36727571570133966 and parameters: {'kernel': 'rbf', 'C': 2.3134456456376844, 'epsilon': 0.11813816673580033, 'gamma': 'auto'}. Best is trial 11 with value: 0.491890535849561.
[I 2025-07-11 21:21:20,171] Trial 13 finished with value: 0.561948072651048 and parameters: {'kernel': 'rbf', 'C': 9.696872393356152, 'epsilon': 0.011337921307558535, 'gamma': 'auto'}. Best is trial 13 with value: 0.561948072651048.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.76 | R2: 0.37
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.29 | R2: 0.56
Fold 1
Fold 2
Fold 3

[I 2025-07-11 21:21:20,278] Trial 14 finished with value: 0.5602272231844567 and parameters: {'kernel': 'rbf', 'C': 9.548004032757484, 'epsilon': 0.010286092298823693, 'gamma': 'auto'}. Best is trial 13 with value: 0.561948072651048.
[I 2025-07-11 21:21:20,369] Trial 15 finished with value: 0.5655021115068422 and parameters: {'kernel': 'rbf', 'C': 9.969242943480626, 'epsilon': 0.049875311621489865, 'gamma': 'auto'}. Best is trial 15 with value: 0.5655021115068422.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.30 | R2: 0.56
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.29 | R2: 0.57
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:21:20,447] Trial 16 finished with value: 0.3473315430657721 and parameters: {'kernel': 'rbf', 'C': 2.0545059404312673, 'epsilon': 0.0522509749914546, 'gamma': 'auto'}. Best is trial 15 with value: 0.5655021115068422.
[I 2025-07-11 21:21:20,526] Trial 17 finished with value: 0.30563435091306956 and parameters: {'kernel': 'rbf', 'C': 1.46834318764733, 'epsilon': 0.08262711923587167, 'gamma': 'auto'}. Best is trial 15 with value: 0.5655021115068422.
[I 2025-07-11 21:21:20,604] Trial 18 finished with value: -26.275048848975985 and parameters: {'kernel': 'sigmoid', 'C': 3.7699851201372163, 'epsilon': 0.03748313662841173, 'gamma': 'auto'}. Best is trial 15 with value: 0.5655021115068422.

Running time: 0.1 sec
OOF RMSE: 2.80 | R2: 0.35
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.89 | R2: 0.31
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 18.10 | R2: -26.28
Fold 1
Fold 2
Fold 3

[I 2025-07-11 21:21:20,681] Trial 19 finished with value: 0.5613887572405767 and parameters: {'kernel': 'rbf', 'C': 9.546236611505467, 'epsilon': 0.06424136400392384, 'gamma': 'auto'}. Best is trial 15 with value: 0.5655021115068422.
[I 2025-07-11 21:21:20,758] Trial 20 finished with value: 0.22012046463504764 and parameters: {'kernel': 'rbf', 'C': 0.5516253491397638, 'epsilon': 0.0901451960492771, 'gamma': 'auto'}. Best is trial 15 with value: 0.5655021115068422.
[I 2025-07-11 21:21:20,846] Trial 21 finished with value: 0.5572639052485184 and parameters: {'kernel': 'rbf', 'C': 9.180320976895896, 'epsilon': 0.06331546145103434, 'gamma': 'auto'}. Best is trial 15 with value: 0.5655021115068422.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.30 | R2: 0.56
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.06 | R2: 0.22
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.31 | R2: 0.56

[I 2025-07-11 21:21:20,933] Trial 22 finished with value: 0.508338462689951 and parameters: {'kernel': 'rbf', 'C': 6.423496115115042, 'epsilon': 0.03529035932416863, 'gamma': 'auto'}. Best is trial 15 with value: 0.5655021115068422.
[I 2025-07-11 21:21:21,019] Trial 23 finished with value: 0.5608440696057515 and parameters: {'kernel': 'rbf', 'C': 9.522231100156565, 'epsilon': 0.059512978083297224, 'gamma': 'auto'}. Best is trial 15 with value: 0.5655021115068422.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.43 | R2: 0.51
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.30 | R2: 0.56
Fold 1
Fold 2
Fold 3

[I 2025-07-11 21:21:21,100] Trial 24 finished with value: 0.4082545961367061 and parameters: {'kernel': 'rbf', 'C': 3.1334578658968013, 'epsilon': 0.022312165787351984, 'gamma': 'auto'}. Best is trial 15 with value: 0.5655021115068422.
[I 2025-07-11 21:21:21,101] A new study created in memory with name: no-name-a5dde13f-290f-4e16-aa72-4db79b12fa96
[I 2025-07-11 21:21:21,160] Trial 0 finished with value: 0.736861431963602 and parameters: {'n_neighbors': 4, 'weights': 'uniform', 'leaf_size': 16}. Best is trial 0 with value: 0.736861431963602.
[I 2025-07-11 21:21:21,223] Trial 1 finished with value: 0.6248108496301272 and parameters: {'n_neighbors': 9, 'weights': 'uniform', 'leaf_size': 38}. Best is trial 0 with value: 0.736861431963602.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.67 | R2: 0.41

✅ SVR - Mejor R2: 0.57
📋 Parámetros: {'kernel': 'rbf', 'C': 9.969242943480626, 'epsilon': 0.049875311621489865, 'gamma': 'auto'}

Buscando mejores hiperparámetros para KNN...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.78 | R2: 0.74
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.12 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:21:21,286] Trial 2 finished with value: 0.6259638310505578 and parameters: {'n_neighbors': 7, 'weights': 'uniform', 'leaf_size': 20}. Best is trial 0 with value: 0.736861431963602.
[I 2025-07-11 21:21:21,348] Trial 3 finished with value: 0.7812177705273289 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 25}. Best is trial 3 with value: 0.7812177705273289.
[I 2025-07-11 21:21:21,413] Trial 4 finished with value: 0.6407346577233703 and parameters: {'n_neighbors': 12, 'weights': 'distance', 'leaf_size': 21}. Best is trial 3 with value: 0.7812177705273289.
[I 2025-07-11 21:21:21,476] Trial 5 finished with value: 0.5929332439305854 and parameters: {'n_neighbors': 11, 'weights': 'uniform', 'leaf_size': 39}. Best is trial 3 with value: 0.7812177705273289.

Running time: 0.1 sec
OOF RMSE: 2.12 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.62 | R2: 0.78
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.08 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.21 | R2: 0.59
Fold 1

[I 2025-07-11 21:21:21,583] Trial 6 finished with value: 0.7812177705273289 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 35}. Best is trial 3 with value: 0.7812177705273289.
[I 2025-07-11 21:21:21,660] Trial 7 finished with value: 0.7268430820329521 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'leaf_size': 28}. Best is trial 3 with value: 0.7812177705273289.
[I 2025-07-11 21:21:21,723] Trial 8 finished with value: 0.5444775486547581 and parameters: {'n_neighbors': 15, 'weights': 'uniform', 'leaf_size': 17}. Best is trial 3 with value: 0.7812177705273289.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.62 | R2: 0.78
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.81 | R2: 0.73
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.34 | R2: 0.54
Fold 1

[I 2025-07-11 21:21:21,786] Trial 9 finished with value: 0.6686784003038193 and parameters: {'n_neighbors': 10, 'weights': 'distance', 'leaf_size': 40}. Best is trial 3 with value: 0.7812177705273289.
[I 2025-07-11 21:21:21,856] Trial 10 finished with value: 0.7268430820329521 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'leaf_size': 29}. Best is trial 3 with value: 0.7812177705273289.
[I 2025-07-11 21:21:21,926] Trial 11 finished with value: 0.7812177705273289 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 33}. Best is trial 3 with value: 0.7812177705273289.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.00 | R2: 0.67
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.81 | R2: 0.73
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.62 | R2: 0.78
Fold 1

[I 2025-07-11 21:21:21,997] Trial 12 finished with value: 0.7812177705273289 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 25}. Best is trial 3 with value: 0.7812177705273289.
[I 2025-07-11 21:21:22,068] Trial 13 finished with value: 0.7666985350398877 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'leaf_size': 11}. Best is trial 3 with value: 0.7812177705273289.
[I 2025-07-11 21:21:22,140] Trial 14 finished with value: 0.6758354995029823 and parameters: {'n_neighbors': 8, 'weights': 'distance', 'leaf_size': 33}. Best is trial 3 with value: 0.7812177705273289.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.62 | R2: 0.78
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.67 | R2: 0.77
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.97 | R2: 0.68

[I 2025-07-11 21:21:22,210] Trial 15 finished with value: 0.7812177705273289 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 34}. Best is trial 3 with value: 0.7812177705273289.
[I 2025-07-11 21:21:22,286] Trial 16 finished with value: 0.7666985350398877 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'leaf_size': 26}. Best is trial 3 with value: 0.7812177705273289.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.62 | R2: 0.78
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.67 | R2: 0.77
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:21:22,361] Trial 17 finished with value: 0.7666985350398877 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'leaf_size': 22}. Best is trial 3 with value: 0.7812177705273289.
[I 2025-07-11 21:21:22,432] Trial 18 finished with value: 0.6325516831396174 and parameters: {'n_neighbors': 13, 'weights': 'distance', 'leaf_size': 31}. Best is trial 3 with value: 0.7812177705273289.
[I 2025-07-11 21:21:22,546] Trial 19 finished with value: 0.6758354995029823 and parameters: {'n_neighbors': 8, 'weights': 'distance', 'leaf_size': 36}. Best is trial 3 with value: 0.7812177705273289.

Running time: 0.1 sec
OOF RMSE: 1.67 | R2: 0.77
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.10 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.97 | R2: 0.68
Fold 1

[I 2025-07-11 21:21:22,614] Trial 20 finished with value: 0.7674738731665292 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'leaf_size': 24}. Best is trial 3 with value: 0.7812177705273289.
[I 2025-07-11 21:21:22,686] Trial 21 finished with value: 0.7812177705273289 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 32}. Best is trial 3 with value: 0.7812177705273289.
[I 2025-07-11 21:21:22,762] Trial 22 finished with value: 0.7674738731665292 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'leaf_size': 36}. Best is trial 3 with value: 0.7812177705273289.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.67 | R2: 0.77
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.62 | R2: 0.78
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.67 | R2: 0.77

[I 2025-07-11 21:21:22,835] Trial 23 finished with value: 0.7812177705273289 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 30}. Best is trial 3 with value: 0.7812177705273289.
[I 2025-07-11 21:21:22,911] Trial 24 finished with value: 0.7268430820329521 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'leaf_size': 36}. Best is trial 3 with value: 0.7812177705273289.
[I 2025-07-11 21:21:22,912] A new study created in memory with name: no-name-74176dd4-ac0f-482c-8bdc-2065895145e4
[I 2025-07-11 21:21:22,971] Trial 0 finished with value: 0.3667508970728224 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: 0.3667508970728224.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.62 | R2: 0.78
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.81 | R2: 0.73

✅ KNN - Mejor R2: 0.78
📋 Parámetros: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 25}

Buscando mejores hiperparámetros para LR...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.76 | R2: 0.37
Fold 1

[I 2025-07-11 21:21:23,036] Trial 1 finished with value: 0.3667508970728224 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: 0.3667508970728224.
[I 2025-07-11 21:21:23,126] Trial 2 finished with value: 0.1603788569012522 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 0 with value: 0.3667508970728224.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.76 | R2: 0.37
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.18 | R2: 0.16
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:21:23,202] Trial 3 finished with value: 0.3670464690972546 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 3 with value: 0.3670464690972546.
[I 2025-07-11 21:21:23,281] Trial 4 finished with value: 0.1603788569012522 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 3 with value: 0.3670464690972546.
[I 2025-07-11 21:21:23,372] Trial 5 finished with value: 0.3670464690972546 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 3 with value: 0.3670464690972546.

Running time: 0.1 sec
OOF RMSE: 2.76 | R2: 0.37
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.18 | R2: 0.16
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.76 | R2: 0.37
Fold 1
Fold 2
Fold 3

[I 2025-07-11 21:21:23,461] Trial 6 finished with value: 0.1603788569012522 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 3 with value: 0.3670464690972546.
[I 2025-07-11 21:21:23,547] Trial 7 finished with value: 0.1603788569012522 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 3 with value: 0.3670464690972546.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.18 | R2: 0.16
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.18 | R2: 0.16
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:21:23,642] Trial 8 finished with value: 0.16037885689082143 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 3 with value: 0.3670464690972546.
[I 2025-07-11 21:21:23,718] Trial 9 finished with value: 0.3667508970728224 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 3 with value: 0.3670464690972546.
[I 2025-07-11 21:21:23,780] Trial 10 finished with value: 0.3670464690972546 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 3 with value: 0.3670464690972546.
[I 2025-07-11 21:21:23,840] Trial 11 finished with value: 0.3670464690972546 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 3 with value: 0.3670464690972546.

Running time: 0.1 sec
OOF RMSE: 3.18 | R2: 0.16
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.76 | R2: 0.37
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.76 | R2: 0.37
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.76 | R2: 0.37

[I 2025-07-11 21:21:23,905] Trial 12 finished with value: 0.3670464690972546 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 3 with value: 0.3670464690972546.
[I 2025-07-11 21:21:23,967] Trial 13 finished with value: 0.3670464690972546 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 3 with value: 0.3670464690972546.
[I 2025-07-11 21:21:24,029] Trial 14 finished with value: 0.3670464690972546 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 3 with value: 0.3670464690972546.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.76 | R2: 0.37
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.76 | R2: 0.37
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.76 | R2: 0.37
Fold 1
Fold 2

[I 2025-07-11 21:21:24,094] Trial 15 finished with value: 0.3670464690972546 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 3 with value: 0.3670464690972546.
[I 2025-07-11 21:21:24,154] Trial 16 finished with value: 0.3670464690972546 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 3 with value: 0.3670464690972546.
[I 2025-07-11 21:21:24,216] Trial 17 finished with value: 0.3670464690972546 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 3 with value: 0.3670464690972546.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.76 | R2: 0.37
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.76 | R2: 0.37
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.76 | R2: 0.37
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 21:21:24,296] Trial 18 finished with value: 0.3670464690972546 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 3 with value: 0.3670464690972546.
[I 2025-07-11 21:21:24,356] Trial 19 finished with value: 0.3670464690972546 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 3 with value: 0.3670464690972546.
[I 2025-07-11 21:21:24,421] Trial 20 finished with value: 0.3670464690972546 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 3 with value: 0.3670464690972546.

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.76 | R2: 0.37
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.76 | R2: 0.37
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.76 | R2: 0.37
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:21:24,483] Trial 21 finished with value: 0.3670464690972546 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 3 with value: 0.3670464690972546.
[I 2025-07-11 21:21:24,546] Trial 22 finished with value: 0.3670464690972546 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 3 with value: 0.3670464690972546.
[I 2025-07-11 21:21:24,607] Trial 23 finished with value: 0.3670464690972546 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 3 with value: 0.3670464690972546.
[I 2025-07-11 21:21:24,663] Trial 24 finished with value: 0.3670464690972546 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 3 with value: 0.3670464690972546.
[I 2025-07-11 21:21:24,664] A new study created in memory with name: no-name-427b8a2f-fce2-493b-8cd2-ab2af5e26354

Running time: 0.1 sec
OOF RMSE: 2.76 | R2: 0.37
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.76 | R2: 0.37
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.76 | R2: 0.37
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.76 | R2: 0.37

✅ LR - Mejor R2: 0.37
📋 Parámetros: {'fit_intercept': False, 'positive': True}

Buscando mejores hiperparámetros para RF...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:21:30,799] Trial 0 finished with value: 0.5570205594806295 and parameters: {'n_estimators': 300, 'max_depth': 8, 'min_samples_split': 8, 'min_samples_leaf': 5, 'bootstrap': False}. Best is trial 0 with value: 0.5570205594806295.

Running time: 6.1 sec
OOF RMSE: 2.31 | R2: 0.56
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:21:46,358] Trial 1 finished with value: 0.5146322304004167 and parameters: {'n_estimators': 500, 'max_depth': 13, 'min_samples_split': 2, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 0 with value: 0.5570205594806295.

Running time: 15.6 sec
OOF RMSE: 2.42 | R2: 0.51
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:21:53,231] Trial 2 finished with value: 0.6155948877163206 and parameters: {'n_estimators': 500, 'max_depth': 9, 'min_samples_split': 7, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 2 with value: 0.6155948877163206.

Running time: 6.9 sec
OOF RMSE: 2.15 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:21:59,158] Trial 3 finished with value: 0.5067491497708463 and parameters: {'n_estimators': 300, 'max_depth': 6, 'min_samples_split': 7, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 2 with value: 0.6155948877163206.

Running time: 5.9 sec
OOF RMSE: 2.43 | R2: 0.51
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:22:05,914] Trial 4 finished with value: 0.6254587897240564 and parameters: {'n_estimators': 300, 'max_depth': 13, 'min_samples_split': 5, 'min_samples_leaf': 4, 'bootstrap': False}. Best is trial 4 with value: 0.6254587897240564.

Running time: 6.8 sec
OOF RMSE: 2.12 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:22:15,890] Trial 5 finished with value: 0.5136377410917383 and parameters: {'n_estimators': 500, 'max_depth': 6, 'min_samples_split': 3, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 4 with value: 0.6254587897240564.

Running time: 10.0 sec
OOF RMSE: 2.42 | R2: 0.51
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:22:18,302] Trial 6 finished with value: 0.6534331738690037 and parameters: {'n_estimators': 100, 'max_depth': 11, 'min_samples_split': 5, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 6 with value: 0.6534331738690037.

Running time: 2.4 sec
OOF RMSE: 2.04 | R2: 0.65
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:22:22,800] Trial 7 finished with value: 0.6135189232135931 and parameters: {'n_estimators': 300, 'max_depth': 8, 'min_samples_split': 9, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 6 with value: 0.6534331738690037.

Running time: 4.5 sec
OOF RMSE: 2.16 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:22:26,570] Trial 8 finished with value: 0.6383153408288205 and parameters: {'n_estimators': 300, 'max_depth': 5, 'min_samples_split': 4, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 6 with value: 0.6534331738690037.

Running time: 3.8 sec
OOF RMSE: 2.08 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:22:32,767] Trial 9 finished with value: 0.6567402334434507 and parameters: {'n_estimators': 300, 'max_depth': 7, 'min_samples_split': 2, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 9 with value: 0.6567402334434507.

Running time: 6.2 sec
OOF RMSE: 2.03 | R2: 0.66
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:22:34,317] Trial 10 finished with value: 0.6193696928855542 and parameters: {'n_estimators': 100, 'max_depth': 15, 'min_samples_split': 10, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 9 with value: 0.6567402334434507.

Running time: 1.5 sec
OOF RMSE: 2.14 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:22:36,720] Trial 11 finished with value: 0.6534331738690037 and parameters: {'n_estimators': 100, 'max_depth': 11, 'min_samples_split': 2, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 9 with value: 0.6567402334434507.

Running time: 2.4 sec
OOF RMSE: 2.04 | R2: 0.65
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:22:38,960] Trial 12 finished with value: 0.6331160448838931 and parameters: {'n_estimators': 100, 'max_depth': 11, 'min_samples_split': 5, 'min_samples_leaf': 4, 'bootstrap': False}. Best is trial 9 with value: 0.6567402334434507.

Running time: 2.2 sec
OOF RMSE: 2.10 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:22:41,539] Trial 13 finished with value: 0.5952209573721607 and parameters: {'n_estimators': 100, 'max_depth': 10, 'min_samples_split': 4, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 9 with value: 0.6567402334434507.

Running time: 2.6 sec
OOF RMSE: 2.21 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:22:43,527] Trial 14 finished with value: 0.6312608739309231 and parameters: {'n_estimators': 100, 'max_depth': 7, 'min_samples_split': 6, 'min_samples_leaf': 4, 'bootstrap': False}. Best is trial 9 with value: 0.6567402334434507.

Running time: 2.0 sec
OOF RMSE: 2.11 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:22:51,540] Trial 15 finished with value: 0.5888447727543209 and parameters: {'n_estimators': 300, 'max_depth': 12, 'min_samples_split': 3, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 9 with value: 0.6567402334434507.

Running time: 8.0 sec
OOF RMSE: 2.22 | R2: 0.59
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:22:53,842] Trial 16 finished with value: 0.658357027684435 and parameters: {'n_estimators': 100, 'max_depth': 9, 'min_samples_split': 5, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 16 with value: 0.658357027684435.

Running time: 2.3 sec
OOF RMSE: 2.03 | R2: 0.66
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:23:00,400] Trial 17 finished with value: 0.6292356231819639 and parameters: {'n_estimators': 300, 'max_depth': 9, 'min_samples_split': 3, 'min_samples_leaf': 4, 'bootstrap': False}. Best is trial 16 with value: 0.658357027684435.

Running time: 6.6 sec
OOF RMSE: 2.11 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:23:01,871] Trial 18 finished with value: 0.6383845907248498 and parameters: {'n_estimators': 100, 'max_depth': 7, 'min_samples_split': 6, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 16 with value: 0.658357027684435.

Running time: 1.5 sec
OOF RMSE: 2.08 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:23:10,368] Trial 19 finished with value: 0.5960175713645544 and parameters: {'n_estimators': 500, 'max_depth': 5, 'min_samples_split': 2, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 16 with value: 0.658357027684435.

Running time: 8.5 sec
OOF RMSE: 2.20 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:23:17,351] Trial 20 finished with value: 0.6588466974401022 and parameters: {'n_estimators': 300, 'max_depth': 9, 'min_samples_split': 4, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 20 with value: 0.6588466974401022.

Running time: 7.0 sec
OOF RMSE: 2.02 | R2: 0.66
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:23:24,304] Trial 21 finished with value: 0.6588466974401022 and parameters: {'n_estimators': 300, 'max_depth': 9, 'min_samples_split': 4, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 20 with value: 0.6588466974401022.

Running time: 6.9 sec
OOF RMSE: 2.02 | R2: 0.66
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:23:31,270] Trial 22 finished with value: 0.6588466974401022 and parameters: {'n_estimators': 300, 'max_depth': 9, 'min_samples_split': 4, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 20 with value: 0.6588466974401022.

Running time: 7.0 sec
OOF RMSE: 2.02 | R2: 0.66
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:23:37,925] Trial 23 finished with value: 0.6300560366462313 and parameters: {'n_estimators': 300, 'max_depth': 10, 'min_samples_split': 4, 'min_samples_leaf': 4, 'bootstrap': False}. Best is trial 20 with value: 0.6588466974401022.

Running time: 6.6 sec
OOF RMSE: 2.11 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:23:45,609] Trial 24 finished with value: 0.5906100892228503 and parameters: {'n_estimators': 300, 'max_depth': 10, 'min_samples_split': 4, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 20 with value: 0.6588466974401022.
[I 2025-07-11 21:23:45,610] A new study created in memory with name: no-name-786db3c1-c316-49ef-bd11-12afe270f9b8

Running time: 7.7 sec
OOF RMSE: 2.22 | R2: 0.59

✅ RF - Mejor R2: 0.66
📋 Parámetros: {'n_estimators': 300, 'max_depth': 9, 'min_samples_split': 4, 'min_samples_leaf': 3, 'bootstrap': False}

Buscando mejores hiperparámetros para CAT...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:24:03,251] Trial 0 finished with value: 0.6989015481834993 and parameters: {'iterations': 500, 'learning_rate': 0.011943355775032232, 'depth': 8, 'l2_leaf_reg': 1.581867459266019}. Best is trial 0 with value: 0.6989015481834993.

Running time: 17.6 sec
OOF RMSE: 1.90 | R2: 0.70
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:24:05,212] Trial 1 finished with value: 0.6974169716727658 and parameters: {'iterations': 500, 'learning_rate': 0.016621090376226923, 'depth': 5, 'l2_leaf_reg': 2.9304653929950506}. Best is trial 0 with value: 0.6989015481834993.

Running time: 2.0 sec
OOF RMSE: 1.91 | R2: 0.70
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:25:14,750] Trial 2 finished with value: 0.705252490019535 and parameters: {'iterations': 2000, 'learning_rate': 0.01929131473081617, 'depth': 8, 'l2_leaf_reg': 7.498481416258496}. Best is trial 2 with value: 0.705252490019535.

Running time: 69.5 sec
OOF RMSE: 1.88 | R2: 0.71
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:25:49,369] Trial 3 finished with value: 0.7114352185063113 and parameters: {'iterations': 1000, 'learning_rate': 0.010974210736507546, 'depth': 8, 'l2_leaf_reg': 2.0603544341493816}. Best is trial 3 with value: 0.7114352185063113.

Running time: 34.6 sec
OOF RMSE: 1.86 | R2: 0.71
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:25:51,655] Trial 4 finished with value: 0.6685209652434823 and parameters: {'iterations': 500, 'learning_rate': 0.09634671111817446, 'depth': 5, 'l2_leaf_reg': 4.49307572831275}. Best is trial 3 with value: 0.7114352185063113.

Running time: 2.3 sec
OOF RMSE: 2.00 | R2: 0.67
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:25:53,689] Trial 5 finished with value: 0.6650629346573499 and parameters: {'iterations': 500, 'learning_rate': 0.014408102927219453, 'depth': 5, 'l2_leaf_reg': 7.947918541268093}. Best is trial 3 with value: 0.7114352185063113.

Running time: 2.0 sec
OOF RMSE: 2.01 | R2: 0.67
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:25:59,567] Trial 6 finished with value: 0.6779503273667227 and parameters: {'iterations': 2000, 'learning_rate': 0.059069091705878596, 'depth': 4, 'l2_leaf_reg': 7.883626455020181}. Best is trial 3 with value: 0.7114352185063113.

Running time: 5.9 sec
OOF RMSE: 1.97 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:27:20,828] Trial 7 finished with value: 0.7126687261867941 and parameters: {'iterations': 1000, 'learning_rate': 0.0849724732069319, 'depth': 9, 'l2_leaf_reg': 5.509932098839245}. Best is trial 7 with value: 0.7126687261867941.

Running time: 81.3 sec
OOF RMSE: 1.86 | R2: 0.71
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:27:22,807] Trial 8 finished with value: 0.6983528998963082 and parameters: {'iterations': 500, 'learning_rate': 0.022676414899577613, 'depth': 5, 'l2_leaf_reg': 3.324861606078373}. Best is trial 7 with value: 0.7126687261867941.

Running time: 2.0 sec
OOF RMSE: 1.90 | R2: 0.70
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:27:35,769] Trial 9 finished with value: 0.7133535685674626 and parameters: {'iterations': 2000, 'learning_rate': 0.01402408160083061, 'depth': 6, 'l2_leaf_reg': 3.1776231478967776}. Best is trial 9 with value: 0.7133535685674626.

Running time: 13.0 sec
OOF RMSE: 1.86 | R2: 0.71
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:32:17,671] Trial 10 finished with value: 0.714913801642519 and parameters: {'iterations': 2000, 'learning_rate': 0.034506394658675145, 'depth': 10, 'l2_leaf_reg': 5.816932621930025}. Best is trial 10 with value: 0.714913801642519.

Running time: 281.9 sec
OOF RMSE: 1.85 | R2: 0.71
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:36:59,251] Trial 11 finished with value: 0.710434653993474 and parameters: {'iterations': 2000, 'learning_rate': 0.037137336472330064, 'depth': 10, 'l2_leaf_reg': 5.881553150090488}. Best is trial 10 with value: 0.714913801642519.
[I 2025-07-11 21:36:59,252] A new study created in memory with name: no-name-e475ddf2-1f9c-4b77-bca5-6c3107cabe66
[I 2025-07-11 21:36:59,330] Trial 0 finished with value: 0.4770384795759176 and parameters: {'alpha': 0.2966613681399618, 'l1_ratio': 0.5583349142887089}. Best is trial 0 with value: 0.4770384795759176.

Running time: 281.6 sec
OOF RMSE: 1.87 | R2: 0.71

✅ CAT - Mejor R2: 0.71
📋 Parámetros: {'iterations': 2000, 'learning_rate': 0.034506394658675145, 'depth': 10, 'l2_leaf_reg': 5.816932621930025}

Buscando mejores hiperparámetros para EN...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.51 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.741e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.894e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.405e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.795e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.714e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 21:36:59,521] Trial 1 finished with value: 0.39429708336678015 and parameters: {'alpha': 0.0005942064582789372, 'l1_ratio': 0.47647812879719365}. Best is trial 0 with value: 0.4770384795759176.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.714e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.589e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.675e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(

Fold 5
Running time: 0.2 sec
OOF RMSE: 2.70 | R2: 0.39
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.922e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.779e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 21:36:59,765] Trial 2 finished with value: 0.3814423246889428 and parameters: {'alpha': 0.00017558857387290768, 'l1_ratio': 0.11616275094188011}. Best is trial 0 with value: 0.4770384795759176.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.550e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.476e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.462e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(

Fold 5
Running time: 0.2 sec
OOF RMSE: 2.73 | R2: 0.38
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.737e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.631e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 21:36:59,970] Trial 3 finished with value: 0.3954508671055391 and parameters: {'alpha': 0.0005004256812742442, 'l1_ratio': 0.12647786718679177}. Best is trial 0 with value: 0.4770384795759176.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.954e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.176e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.297e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(

Fold 5
Running time: 0.2 sec
OOF RMSE: 2.70 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.848e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.579e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 21:37:00,164] Trial 4 finished with value: 0.47814629404326325 and parameters: {'alpha': 0.009449271809285589, 'l1_ratio': 0.2495809726498427}. Best is trial 4 with value: 0.47814629404326325.
[I 2025-07-11 21:37:00,338] Trial 5 finished with value: 0.4492421462165349 and parameters: {'alpha': 0.567220915873413, 'l1_ratio': 0.7204741885520183}. Best is trial 4 with value: 0.47814629404326325.

Fold 5
Running time: 0.2 sec
OOF RMSE: 2.50 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 2.57 | R2: 0.45

[I 2025-07-11 21:37:00,457] Trial 6 finished with value: 0.5000727576184307 and parameters: {'alpha': 0.2585842017937936, 'l1_ratio': 0.08847459910149813}. Best is trial 6 with value: 0.5000727576184307.
[I 2025-07-11 21:37:00,540] Trial 7 finished with value: 0.45457967253448184 and parameters: {'alpha': 0.7483543822026499, 'l1_ratio': 0.0715284517683139}. Best is trial 6 with value: 0.5000727576184307.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.45 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.56 | R2: 0.45
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.602e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.947e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.485e+01, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.503e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.382e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 21:37:00,678] Trial 8 finished with value: 0.4266772213392087 and parameters: {'alpha': 0.0020992507962926065, 'l1_ratio': 0.39336091524880545}. Best is trial 6 with value: 0.5000727576184307.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.402e+01, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.494e+01, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.453e+01, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.62 | R2: 0.43
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.062e+00, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.758e+01, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 21:37:00,807] Trial 9 finished with value: 0.452978607181451 and parameters: {'alpha': 0.006985673698029828, 'l1_ratio': 0.8823585703935383}. Best is trial 6 with value: 0.5000727576184307.
[I 2025-07-11 21:37:00,897] Trial 10 finished with value: 0.01111879807813021 and parameters: {'alpha': 6.999723975217652, 'l1_ratio': 0.3167595946021789}. Best is trial 6 with value: 0.5000727576184307.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.887e+01, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.56 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.45 | R2: 0.01
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.511e+00, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.999e+01, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.944e+01, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.923e+01, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 21:37:01,057] Trial 11 finished with value: 0.5227316631339058 and parameters: {'alpha': 0.028286522640440296, 'l1_ratio': 0.24352880218478756}. Best is trial 11 with value: 0.5227316631339058.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.754e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.544e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.410e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.536e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(

Fold 3
Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 2.39 | R2: 0.52
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.484e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 21:37:01,216] Trial 12 finished with value: 0.5313995532148745 and parameters: {'alpha': 0.05592569117029843, 'l1_ratio': 0.021891483275802093}. Best is trial 12 with value: 0.5313995532148745.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.063e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.529e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.379e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.051e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.092e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 21:37:01,356] Trial 13 finished with value: 0.525270526399354 and parameters: {'alpha': 0.03778252280428007, 'l1_ratio': 0.011581301727495042}. Best is trial 12 with value: 0.5313995532148745.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.307e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(

Running time: 0.2 sec
OOF RMSE: 2.37 | R2: 0.53
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.39 | R2: 0.53
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.840e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.554e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.377e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.425e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 21:37:01,537] Trial 14 finished with value: 0.5291802092501645 and parameters: {'alpha': 0.048237255003449414, 'l1_ratio': 0.004409483482764471}. Best is trial 12 with value: 0.5313995532148745.

Fold 3
Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 2.38 | R2: 0.53
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:37:01,628] Trial 15 finished with value: 0.5380698418309826 and parameters: {'alpha': 0.08027720134703152, 'l1_ratio': 0.6438523161833076}. Best is trial 15 with value: 0.5380698418309826.
[I 2025-07-11 21:37:01,725] Trial 16 finished with value: 0.019875910530181784 and parameters: {'alpha': 3.3238888294493503, 'l1_ratio': 0.7011465671606195}. Best is trial 15 with value: 0.5380698418309826.
[I 2025-07-11 21:37:01,823] Trial 17 finished with value: 0.5280816220516521 and parameters: {'alpha': 0.09871112492598297, 'l1_ratio': 0.9235587054392158}. Best is trial 15 with value: 0.5380698418309826.

Running time: 0.1 sec
OOF RMSE: 2.36 | R2: 0.54
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.43 | R2: 0.02
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.38 | R2: 0.53

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.063e+01, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.056e+00, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.309e+00, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.030e+00, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.095e+01, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 21:37:01,953] Trial 18 finished with value: 0.49476633763035605 and parameters: {'alpha': 0.013027612923645614, 'l1_ratio': 0.6589272444198587}. Best is trial 15 with value: 0.5380698418309826.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.46 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:37:02,058] Trial 19 finished with value: 0.31587484581832037 and parameters: {'alpha': 1.4386887006640574, 'l1_ratio': 0.7910435292009326}. Best is trial 15 with value: 0.5380698418309826.
[I 2025-07-11 21:37:02,154] Trial 20 finished with value: 0.5146526413438459 and parameters: {'alpha': 0.1460518191716474, 'l1_ratio': 0.5719197801503644}. Best is trial 15 with value: 0.5380698418309826.

Running time: 0.1 sec
OOF RMSE: 2.87 | R2: 0.32
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.42 | R2: 0.51
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.771e+01, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.041e+01, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.397e+00, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.695e+01, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.379e+01, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 21:37:02,282] Trial 21 finished with value: 0.5266168654770542 and parameters: {'alpha': 0.03287036156894838, 'l1_ratio': 0.19987408821099115}. Best is trial 15 with value: 0.5380698418309826.
[I 2025-07-11 21:37:02,396] Trial 22 finished with value: 0.5375645330084586 and parameters: {'alpha': 0.07904769573592585, 'l1_ratio': 0.4183984127817473}. Best is trial 15 with value: 0.5380698418309826.

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.39 | R2: 0.53
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.36 | R2: 0.54
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 21:37:02,492] Trial 23 finished with value: 0.5333418515979287 and parameters: {'alpha': 0.09796988584314972, 'l1_ratio': 0.4273018878349172}. Best is trial 15 with value: 0.5380698418309826.
[I 2025-07-11 21:37:02,618] Trial 24 finished with value: 0.518197275998747 and parameters: {'alpha': 0.14271545616463147, 'l1_ratio': 0.41613323110770345}. Best is trial 15 with value: 0.5380698418309826.
[I 2025-07-11 21:37:02,620] A new study created in memory with name: no-name-66a0069c-8da1-46f2-b274-72b1b7893848

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.37 | R2: 0.53
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.41 | R2: 0.52

✅ EN - Mejor R2: 0.54
📋 Parámetros: {'alpha': 0.08027720134703152, 'l1_ratio': 0.6438523161833076}

🔍 Optimizando en TOA_1x1_depth_lt_1...
Buscando mejores hiperparámetros para XGB...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:37:08,353] Trial 0 finished with value: 0.6178814818895015 and parameters: {'n_estimators': 500, 'learning_rate': 0.028609229319060757, 'max_depth': 8, 'min_child_weight': 1, 'subsample': 0.9120415850237552, 'colsample_bytree': 0.822873791914071}. Best is trial 0 with value: 0.6178814818895015.

Running time: 5.7 sec
OOF RMSE: 2.34 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:37:13,813] Trial 1 finished with value: 0.6260893268381282 and parameters: {'n_estimators': 1000, 'learning_rate': 0.015923129997083757, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.8632136696687907, 'colsample_bytree': 0.6738357215305297}. Best is trial 1 with value: 0.6260893268381282.

Running time: 5.5 sec
OOF RMSE: 2.31 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:37:20,374] Trial 2 finished with value: 0.6328884117764457 and parameters: {'n_estimators': 1000, 'learning_rate': 0.005429258246024513, 'max_depth': 5, 'min_child_weight': 1, 'subsample': 0.7709770108878017, 'colsample_bytree': 0.930911074467368}. Best is trial 2 with value: 0.6328884117764457.

Running time: 6.6 sec
OOF RMSE: 2.29 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:37:25,335] Trial 3 finished with value: 0.618762392059065 and parameters: {'n_estimators': 1000, 'learning_rate': 0.014732873775486103, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.8933337808219923, 'colsample_bytree': 0.7586267527700373}. Best is trial 2 with value: 0.6328884117764457.

Running time: 5.0 sec
OOF RMSE: 2.33 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:37:28,935] Trial 4 finished with value: 0.664369728950269 and parameters: {'n_estimators': 500, 'learning_rate': 0.006704511294397888, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.7627739509918093, 'colsample_bytree': 0.7336778362408503}. Best is trial 4 with value: 0.664369728950269.

Running time: 3.6 sec
OOF RMSE: 2.19 | R2: 0.66
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:37:35,292] Trial 5 finished with value: 0.6327055904555801 and parameters: {'n_estimators': 1000, 'learning_rate': 0.0090107976908323, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.6254463963889774, 'colsample_bytree': 0.6227820048618838}. Best is trial 4 with value: 0.664369728950269.

Running time: 6.4 sec
OOF RMSE: 2.29 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:37:41,229] Trial 6 finished with value: 0.634375857995326 and parameters: {'n_estimators': 1000, 'learning_rate': 0.010159632372202064, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.7972334838410605, 'colsample_bytree': 0.7960385003164205}. Best is trial 4 with value: 0.664369728950269.

Running time: 5.9 sec
OOF RMSE: 2.29 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:37:51,019] Trial 7 finished with value: 0.629009061811239 and parameters: {'n_estimators': 2000, 'learning_rate': 0.03018734641292668, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.6145173401711737, 'colsample_bytree': 0.6316637249986516}. Best is trial 4 with value: 0.664369728950269.

Running time: 9.8 sec
OOF RMSE: 2.30 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:37:58,638] Trial 8 finished with value: 0.5832703729555512 and parameters: {'n_estimators': 1000, 'learning_rate': 0.02581649538049673, 'max_depth': 8, 'min_child_weight': 4, 'subsample': 0.8995926634692537, 'colsample_bytree': 0.9637807786649625}. Best is trial 4 with value: 0.664369728950269.

Running time: 7.6 sec
OOF RMSE: 2.44 | R2: 0.58
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:38:09,768] Trial 9 finished with value: 0.6008520311463672 and parameters: {'n_estimators': 2000, 'learning_rate': 0.009050947702431155, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.7316264476450136, 'colsample_bytree': 0.9340931796738227}. Best is trial 4 with value: 0.664369728950269.

Running time: 11.1 sec
OOF RMSE: 2.39 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:38:12,737] Trial 10 finished with value: 0.6229932863569192 and parameters: {'n_estimators': 500, 'learning_rate': 0.06759216952546789, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.9806431027519417, 'colsample_bytree': 0.713484180922304}. Best is trial 4 with value: 0.664369728950269.

Running time: 3.0 sec
OOF RMSE: 2.32 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:38:15,963] Trial 11 finished with value: 0.6352022042120462 and parameters: {'n_estimators': 500, 'learning_rate': 0.0053764787519510904, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.7019212170956225, 'colsample_bytree': 0.8334850758473503}. Best is trial 4 with value: 0.664369728950269.

Running time: 3.2 sec
OOF RMSE: 2.28 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:38:19,330] Trial 12 finished with value: 0.6311442966673582 and parameters: {'n_estimators': 500, 'learning_rate': 0.005035293393651281, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.6944756169814355, 'colsample_bytree': 0.853357645343219}. Best is trial 4 with value: 0.664369728950269.

Running time: 3.4 sec
OOF RMSE: 2.30 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:38:23,214] Trial 13 finished with value: 0.6204909379993261 and parameters: {'n_estimators': 500, 'learning_rate': 0.006576764432929578, 'max_depth': 8, 'min_child_weight': 2, 'subsample': 0.6925287914651684, 'colsample_bytree': 0.8724429001476617}. Best is trial 4 with value: 0.664369728950269.

Running time: 3.9 sec
OOF RMSE: 2.33 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:38:25,783] Trial 14 finished with value: 0.6299430538762213 and parameters: {'n_estimators': 500, 'learning_rate': 0.0608344014976086, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.6809860168517677, 'colsample_bytree': 0.740497706041786}. Best is trial 4 with value: 0.664369728950269.

Running time: 2.6 sec
OOF RMSE: 2.30 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:38:30,076] Trial 15 finished with value: 0.6333410007322009 and parameters: {'n_estimators': 500, 'learning_rate': 0.015545218273630824, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.8336761579234756, 'colsample_bytree': 0.7779061913142433}. Best is trial 4 with value: 0.664369728950269.

Running time: 4.3 sec
OOF RMSE: 2.29 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:38:32,654] Trial 16 finished with value: 0.6251967699245957 and parameters: {'n_estimators': 500, 'learning_rate': 0.09773701044272123, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.7491864050242772, 'colsample_bytree': 0.6980353580075428}. Best is trial 4 with value: 0.664369728950269.

Running time: 2.6 sec
OOF RMSE: 2.31 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:38:36,225] Trial 17 finished with value: 0.6237959312898778 and parameters: {'n_estimators': 500, 'learning_rate': 0.007350884210635414, 'max_depth': 8, 'min_child_weight': 3, 'subsample': 0.6550049042235181, 'colsample_bytree': 0.8853111473091695}. Best is trial 4 with value: 0.664369728950269.

Running time: 3.6 sec
OOF RMSE: 2.32 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:38:52,223] Trial 18 finished with value: 0.6295486236767154 and parameters: {'n_estimators': 2000, 'learning_rate': 0.01083890847152088, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.7305355846325466, 'colsample_bytree': 0.8362944398873902}. Best is trial 4 with value: 0.664369728950269.

Running time: 16.0 sec
OOF RMSE: 2.30 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:38:55,062] Trial 19 finished with value: 0.6283316376738424 and parameters: {'n_estimators': 500, 'learning_rate': 0.03725851198375585, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.8058035485387288, 'colsample_bytree': 0.7296726651952297}. Best is trial 4 with value: 0.664369728950269.

Running time: 2.8 sec
OOF RMSE: 2.31 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:38:58,646] Trial 20 finished with value: 0.647949473862472 and parameters: {'n_estimators': 500, 'learning_rate': 0.006825779529912217, 'max_depth': 8, 'min_child_weight': 3, 'subsample': 0.7771606041961516, 'colsample_bytree': 0.662990120978509}. Best is trial 4 with value: 0.664369728950269.

Running time: 3.6 sec
OOF RMSE: 2.24 | R2: 0.65
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:39:02,024] Trial 21 finished with value: 0.646839233285931 and parameters: {'n_estimators': 500, 'learning_rate': 0.0061894624801117435, 'max_depth': 8, 'min_child_weight': 3, 'subsample': 0.7714799332983149, 'colsample_bytree': 0.661197880851191}. Best is trial 4 with value: 0.664369728950269.

Running time: 3.4 sec
OOF RMSE: 2.25 | R2: 0.65
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:39:05,396] Trial 22 finished with value: 0.647593673006643 and parameters: {'n_estimators': 500, 'learning_rate': 0.007612282795730516, 'max_depth': 8, 'min_child_weight': 3, 'subsample': 0.7822636295133982, 'colsample_bytree': 0.6588956388563824}. Best is trial 4 with value: 0.664369728950269.

Running time: 3.4 sec
OOF RMSE: 2.24 | R2: 0.65
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:39:08,767] Trial 23 finished with value: 0.6489126698800441 and parameters: {'n_estimators': 500, 'learning_rate': 0.00769001681645395, 'max_depth': 8, 'min_child_weight': 3, 'subsample': 0.8369557503136243, 'colsample_bytree': 0.6665269626563688}. Best is trial 4 with value: 0.664369728950269.

Running time: 3.4 sec
OOF RMSE: 2.24 | R2: 0.65
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:39:12,972] Trial 24 finished with value: 0.6239385508443096 and parameters: {'n_estimators': 500, 'learning_rate': 0.012509322319544306, 'max_depth': 8, 'min_child_weight': 2, 'subsample': 0.849724081395889, 'colsample_bytree': 0.6851207385146043}. Best is trial 4 with value: 0.664369728950269.
[I 2025-07-11 21:39:12,973] A new study created in memory with name: no-name-4bb36ef3-55d5-477e-bff8-707970479f92

Running time: 4.2 sec
OOF RMSE: 2.32 | R2: 0.62

✅ XGB - Mejor R2: 0.66
📋 Parámetros: {'n_estimators': 500, 'learning_rate': 0.006704511294397888, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.7627739509918093, 'colsample_bytree': 0.7336778362408503}

Buscando mejores hiperparámetros para LBM...
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 21:39:13,792] Trial 0 finished with value: 0.6814269309395671 and parameters: {'learning_rate': 0.014227059277164925, 'num_leaves': 80, 'max_depth': 7, 'min_child_samples': 25, 'subsample': 0.9415436222600472, 'colsample_bytree': 0.6446175326309748, 'n_estimators': 2000}. Best is trial 0 with value: 0.6814269309395671.

Fold 5
Running time: 0.8 sec
OOF RMSE: 2.13 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 21:39:14,246] Trial 1 finished with value: 0.6430750613123645 and parameters: {'learning_rate': 0.01049912609678917, 'num_leaves': 80, 'max_depth': 7, 'min_child_samples': 25, 'subsample': 0.9721989724177635, 'colsample_bytree': 0.9955746196800807, 'n_estimators': 1000}. Best is trial 0 with value: 0.6814269309395671.

Fold 5
Running time: 0.4 sec
OOF RMSE: 2.26 | R2: 0.64
Fold 1
Fold 2
Fold 3

[I 2025-07-11 21:39:14,552] Trial 2 finished with value: 0.580244778250427 and parameters: {'learning_rate': 0.00914970474857403, 'num_leaves': 80, 'max_depth': 7, 'min_child_samples': 20, 'subsample': 0.8232692524460268, 'colsample_bytree': 0.8956261374764065, 'n_estimators': 500}. Best is trial 0 with value: 0.6814269309395671.

Fold 4
Fold 5
Running time: 0.3 sec
OOF RMSE: 2.45 | R2: 0.58
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:39:15,266] Trial 3 finished with value: 0.5981650642892522 and parameters: {'learning_rate': 0.015200924693246447, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 9, 'subsample': 0.7806943725245268, 'colsample_bytree': 0.958102732922865, 'n_estimators': 1000}. Best is trial 0 with value: 0.6814269309395671.

Running time: 0.7 sec
OOF RMSE: 2.40 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:39:16,454] Trial 4 finished with value: 0.5758249151654369 and parameters: {'learning_rate': 0.01938579293255535, 'num_leaves': 60, 'max_depth': 6, 'min_child_samples': 5, 'subsample': 0.7500064377209613, 'colsample_bytree': 0.6903827884090887, 'n_estimators': 2000}. Best is trial 0 with value: 0.6814269309395671.

Running time: 1.2 sec
OOF RMSE: 2.46 | R2: 0.58
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 21:39:16,750] Trial 5 finished with value: 0.6743888828204767 and parameters: {'learning_rate': 0.02673886565606622, 'num_leaves': 60, 'max_depth': 7, 'min_child_samples': 24, 'subsample': 0.9562384782204836, 'colsample_bytree': 0.9901701339154876, 'n_estimators': 500}. Best is trial 0 with value: 0.6814269309395671.

Fold 5
Running time: 0.3 sec
OOF RMSE: 2.16 | R2: 0.67
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:39:17,158] Trial 6 finished with value: 0.5374233341208601 and parameters: {'learning_rate': 0.060978464431395075, 'num_leaves': 40, 'max_depth': 7, 'min_child_samples': 7, 'subsample': 0.975354061596215, 'colsample_bytree': 0.9369500036467804, 'n_estimators': 500}. Best is trial 0 with value: 0.6814269309395671.

Running time: 0.4 sec
OOF RMSE: 2.57 | R2: 0.54
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 21:39:18,125] Trial 7 finished with value: 0.5971906200247545 and parameters: {'learning_rate': 0.00821959341118047, 'num_leaves': 80, 'max_depth': 5, 'min_child_samples': 6, 'subsample': 0.7208136238035217, 'colsample_bytree': 0.6972231436232128, 'n_estimators': 2000}. Best is trial 0 with value: 0.6814269309395671.

Fold 5
Running time: 1.0 sec
OOF RMSE: 2.40 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:39:18,935] Trial 8 finished with value: 0.6798957628964901 and parameters: {'learning_rate': 0.03280837937311116, 'num_leaves': 60, 'max_depth': 7, 'min_child_samples': 25, 'subsample': 0.7617427034467397, 'colsample_bytree': 0.6086231178242404, 'n_estimators': 2000}. Best is trial 0 with value: 0.6814269309395671.

Running time: 0.8 sec
OOF RMSE: 2.14 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 21:39:19,538] Trial 9 finished with value: 0.6156230119132167 and parameters: {'learning_rate': 0.009072307914408684, 'num_leaves': 40, 'max_depth': 8, 'min_child_samples': 19, 'subsample': 0.9794045292441376, 'colsample_bytree': 0.8559046362695886, 'n_estimators': 1000}. Best is trial 0 with value: 0.6814269309395671.

Fold 5
Running time: 0.6 sec
OOF RMSE: 2.34 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 21:39:20,513] Trial 10 finished with value: 0.6749321304473181 and parameters: {'learning_rate': 0.07975447152983203, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 13, 'subsample': 0.8755655717341914, 'colsample_bytree': 0.7736421610437223, 'n_estimators': 2000}. Best is trial 0 with value: 0.6814269309395671.

Fold 5
Running time: 1.0 sec
OOF RMSE: 2.16 | R2: 0.67
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:39:21,446] Trial 11 finished with value: 0.6908841348781577 and parameters: {'learning_rate': 0.03558374959466582, 'num_leaves': 60, 'max_depth': 8, 'min_child_samples': 21, 'subsample': 0.6449115562958018, 'colsample_bytree': 0.6305174224916954, 'n_estimators': 2000}. Best is trial 11 with value: 0.6908841348781577.

Running time: 0.9 sec
OOF RMSE: 2.10 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 21:39:22,466] Trial 12 finished with value: 0.6737872416847972 and parameters: {'learning_rate': 0.04248875221227254, 'num_leaves': 80, 'max_depth': 8, 'min_child_samples': 20, 'subsample': 0.6006846118026983, 'colsample_bytree': 0.6009852859015758, 'n_estimators': 2000}. Best is trial 11 with value: 0.6908841348781577.

Fold 5
Running time: 1.0 sec
OOF RMSE: 2.16 | R2: 0.67
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:39:23,678] Trial 13 finished with value: 0.6686805145152891 and parameters: {'learning_rate': 0.005903097683442425, 'num_leaves': 60, 'max_depth': 8, 'min_child_samples': 16, 'subsample': 0.6531856042322569, 'colsample_bytree': 0.6853420175194925, 'n_estimators': 2000}. Best is trial 11 with value: 0.6908841348781577.

Running time: 1.2 sec
OOF RMSE: 2.18 | R2: 0.67
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:39:24,590] Trial 14 finished with value: 0.6829248161673365 and parameters: {'learning_rate': 0.01598346469505684, 'num_leaves': 80, 'max_depth': 6, 'min_child_samples': 22, 'subsample': 0.865969699142603, 'colsample_bytree': 0.7786480776031864, 'n_estimators': 2000}. Best is trial 11 with value: 0.6908841348781577.

Running time: 0.9 sec
OOF RMSE: 2.13 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:39:25,536] Trial 15 finished with value: 0.6913620429195543 and parameters: {'learning_rate': 0.04351211697881444, 'num_leaves': 60, 'max_depth': 6, 'min_child_samples': 22, 'subsample': 0.8639833057090615, 'colsample_bytree': 0.7776911767283312, 'n_estimators': 2000}. Best is trial 15 with value: 0.6913620429195543.

Running time: 0.9 sec
OOF RMSE: 2.10 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:39:26,616] Trial 16 finished with value: 0.6807922513059393 and parameters: {'learning_rate': 0.04831163952294807, 'num_leaves': 60, 'max_depth': 6, 'min_child_samples': 16, 'subsample': 0.6849006190334724, 'colsample_bytree': 0.8364773561426604, 'n_estimators': 2000}. Best is trial 15 with value: 0.6913620429195543.

Running time: 1.1 sec
OOF RMSE: 2.14 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 1.1 sec
OOF RMSE: 2.21 | R2: 0.66

[I 2025-07-11 21:39:27,686] Trial 17 finished with value: 0.6578180853247946 and parameters: {'learning_rate': 0.08909109759863162, 'num_leaves': 60, 'max_depth': 6, 'min_child_samples': 14, 'subsample': 0.8896740570622932, 'colsample_bytree': 0.7422600165525356, 'n_estimators': 2000}. Best is trial 15 with value: 0.6913620429195543.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:39:28,193] Trial 18 finished with value: 0.6664506194405223 and parameters: {'learning_rate': 0.033782107324582665, 'num_leaves': 60, 'max_depth': 5, 'min_child_samples': 18, 'subsample': 0.8254651707757862, 'colsample_bytree': 0.8209288544497613, 'n_estimators': 1000}. Best is trial 15 with value: 0.6913620429195543.

Running time: 0.5 sec
OOF RMSE: 2.18 | R2: 0.67
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 21:39:28,477] Trial 19 finished with value: 0.6782214823814398 and parameters: {'learning_rate': 0.05946628983089462, 'num_leaves': 60, 'max_depth': 8, 'min_child_samples': 22, 'subsample': 0.64027729438438, 'colsample_bytree': 0.7356682043579134, 'n_estimators': 500}. Best is trial 15 with value: 0.6913620429195543.

Fold 5
Running time: 0.3 sec
OOF RMSE: 2.14 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:39:29,593] Trial 20 finished with value: 0.6147019997462293 and parameters: {'learning_rate': 0.023516892750620588, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 12, 'subsample': 0.9026886413999446, 'colsample_bytree': 0.8748055324684942, 'n_estimators': 2000}. Best is trial 15 with value: 0.6913620429195543.

Running time: 1.1 sec
OOF RMSE: 2.35 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 21:39:30,558] Trial 21 finished with value: 0.6835626762529499 and parameters: {'learning_rate': 0.018570656339652294, 'num_leaves': 40, 'max_depth': 6, 'min_child_samples': 22, 'subsample': 0.8466959726597914, 'colsample_bytree': 0.7880270465009912, 'n_estimators': 2000}. Best is trial 15 with value: 0.6913620429195543.

Fold 5
Running time: 1.0 sec
OOF RMSE: 2.13 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:39:31,485] Trial 22 finished with value: 0.6809417749411406 and parameters: {'learning_rate': 0.03212032572532296, 'num_leaves': 40, 'max_depth': 6, 'min_child_samples': 22, 'subsample': 0.8356699617296882, 'colsample_bytree': 0.7946908445195051, 'n_estimators': 2000}. Best is trial 15 with value: 0.6913620429195543.

Running time: 0.9 sec
OOF RMSE: 2.14 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 21:39:32,290] Trial 23 finished with value: 0.692289333402509 and parameters: {'learning_rate': 0.04420254492462428, 'num_leaves': 40, 'max_depth': 5, 'min_child_samples': 23, 'subsample': 0.7991575369762182, 'colsample_bytree': 0.6405026657041987, 'n_estimators': 2000}. Best is trial 23 with value: 0.692289333402509.

Fold 5
Running time: 0.8 sec
OOF RMSE: 2.10 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:39:33,152] Trial 24 finished with value: 0.6797340308707396 and parameters: {'learning_rate': 0.044939397033759036, 'num_leaves': 40, 'max_depth': 5, 'min_child_samples': 18, 'subsample': 0.7925896019863745, 'colsample_bytree': 0.6418003991231205, 'n_estimators': 2000}. Best is trial 23 with value: 0.692289333402509.
[I 2025-07-11 21:39:33,153] A new study created in memory with name: no-name-3f5ce07b-54e0-479e-ac22-8d709398dcc2

Running time: 0.9 sec
OOF RMSE: 2.14 | R2: 0.68

✅ LBM - Mejor R2: 0.69
📋 Parámetros: {'learning_rate': 0.04420254492462428, 'num_leaves': 40, 'max_depth': 5, 'min_child_samples': 23, 'subsample': 0.7991575369762182, 'colsample_bytree': 0.6405026657041987, 'n_estimators': 2000}

Buscando mejores hiperparámetros para MLP...
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 21:39:36,145] Trial 0 finished with value: 0.19667291471405957 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 3.146589764630243e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00015935299620866065}. Best is trial 0 with value: 0.19667291471405957.

Running time: 3.0 sec
OOF RMSE: 3.39 | R2: 0.20
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 21:39:38,785] Trial 1 finished with value: 0.5749819382661929 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'relu', 'solver': 'sgd', 'alpha': 3.587218676846054e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.002860858790713822}. Best is trial 1 with value: 0.5749819382661929.

Running time: 2.6 sec
OOF RMSE: 2.47 | R2: 0.57
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 21:39:39,563] Trial 2 finished with value: 0.5334771237430904 and parameters: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.0033357245797309555, 'learning_rate': 'constant', 'learning_rate_init': 0.009683268122154141}. Best is trial 1 with value: 0.5749819382661929.

Fold 5
Running time: 0.8 sec
OOF RMSE: 2.58 | R2: 0.53
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 21:39:42,690] Trial 3 finished with value: 0.6421171442728866 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.0003496825492993352, 'learning_rate': 'adaptive', 'learning_rate_init': 0.007938182927086238}. Best is trial 3 with value: 0.6421171442728866.

Running time: 3.1 sec
OOF RMSE: 2.26 | R2: 0.64
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 21:39:45,331] Trial 4 finished with value: 0.313470264673406 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0002625605624466176, 'learning_rate': 'constant', 'learning_rate_init': 0.0001282670547451791}. Best is trial 3 with value: 0.6421171442728866.

Running time: 2.6 sec
OOF RMSE: 3.13 | R2: 0.31
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 21:39:47,987] Trial 5 finished with value: 0.5982488437503152 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.011826445317941966, 'learning_rate': 'adaptive', 'learning_rate_init': 0.009243911109772216}. Best is trial 3 with value: 0.6421171442728866.

Running time: 2.6 sec
OOF RMSE: 2.40 | R2: 0.60
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 21:39:50,467] Trial 6 finished with value: 0.2530368420251685 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'sgd', 'alpha': 2.03101024471473e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00022627104248390355}. Best is trial 3 with value: 0.6421171442728866.

Running time: 2.5 sec
OOF RMSE: 3.27 | R2: 0.25
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 21:39:53,423] Trial 7 finished with value: 0.2546000604401698 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.00020638506580825518, 'learning_rate': 'constant', 'learning_rate_init': 0.0001425702350692868}. Best is trial 3 with value: 0.6421171442728866.

Running time: 3.0 sec
OOF RMSE: 3.26 | R2: 0.25
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:39:54,118] Trial 8 finished with value: 0.3600192606580481 and parameters: {'hidden_layer_sizes': '50', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.001256934512631947, 'learning_rate': 'adaptive', 'learning_rate_init': 0.003123493347021662}. Best is trial 3 with value: 0.6421171442728866.

Running time: 0.7 sec
OOF RMSE: 3.03 | R2: 0.36
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 21:39:56,537] Trial 9 finished with value: 0.5771641849624081 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'relu', 'solver': 'sgd', 'alpha': 4.22870093719767e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0026184845982489885}. Best is trial 3 with value: 0.6421171442728866.

Running time: 2.4 sec
OOF RMSE: 2.46 | R2: 0.58
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 21:39:59,327] Trial 10 finished with value: 0.6212696691375583 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.09225095415565042, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0006453622482072198}. Best is trial 3 with value: 0.6421171442728866.

Running time: 2.8 sec
OOF RMSE: 2.33 | R2: 0.62
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 21:40:02,265] Trial 11 finished with value: 0.6240182727097732 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.09515345278404183, 'learning_rate': 'adaptive', 'learning_rate_init': 0.000612830521276336}. Best is trial 3 with value: 0.6421171442728866.

Running time: 2.9 sec
OOF RMSE: 2.32 | R2: 0.62
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 21:40:05,215] Trial 12 finished with value: 0.6243320265987233 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.08693244513087771, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0005996965504993378}. Best is trial 3 with value: 0.6421171442728866.

Running time: 2.9 sec
OOF RMSE: 2.32 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 21:40:07,207] Trial 13 finished with value: 0.5977815522428636 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.01019528753121905, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0013090110784962751}. Best is trial 3 with value: 0.6421171442728866.

Running time: 2.0 sec
OOF RMSE: 2.40 | R2: 0.60
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 21:40:09,550] Trial 14 finished with value: 0.3301739255020111 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.00029302822675572577, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0003319872254032893}. Best is trial 3 with value: 0.6421171442728866.

Running time: 2.3 sec
OOF RMSE: 3.09 | R2: 0.33
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 21:40:11,479] Trial 15 finished with value: 0.5021941819857973 and parameters: {'hidden_layer_sizes': '50', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.019019813269476566, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0013180964493045364}. Best is trial 3 with value: 0.6421171442728866.

Running time: 1.9 sec
OOF RMSE: 2.67 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:40:12,958] Trial 16 finished with value: 0.5760775489893688 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0012076864566419026, 'learning_rate': 'adaptive', 'learning_rate_init': 0.004735994480915038}. Best is trial 3 with value: 0.6421171442728866.

Running time: 1.5 sec
OOF RMSE: 2.46 | R2: 0.58
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 21:40:16,193] Trial 17 finished with value: 0.44974238745896766 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.00010861360775751699, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00047206995960337266}. Best is trial 3 with value: 0.6421171442728866.

Running time: 3.2 sec
OOF RMSE: 2.80 | R2: 0.45
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 21:40:19,056] Trial 18 finished with value: 0.5423789758364903 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.0032287485590159525, 'learning_rate': 'constant', 'learning_rate_init': 0.0008612857152307765}. Best is trial 3 with value: 0.6421171442728866.

Running time: 2.9 sec
OOF RMSE: 2.56 | R2: 0.54
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 21:40:21,251] Trial 19 finished with value: 0.3046700465532123 and parameters: {'hidden_layer_sizes': '50', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.03088260865404806, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00027971430759168956}. Best is trial 3 with value: 0.6421171442728866.

Running time: 2.2 sec
OOF RMSE: 3.15 | R2: 0.30
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 21:40:23,259] Trial 20 finished with value: 0.4841867804298987 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.0005134897811431395, 'learning_rate': 'adaptive', 'learning_rate_init': 0.005143697988144038}. Best is trial 3 with value: 0.6421171442728866.

Running time: 2.0 sec
OOF RMSE: 2.72 | R2: 0.48
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 21:40:26,427] Trial 21 finished with value: 0.6243261506074295 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.08102746550240389, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0005487971868510073}. Best is trial 3 with value: 0.6421171442728866.

Running time: 3.2 sec
OOF RMSE: 2.32 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:40:28,200] Trial 22 finished with value: 0.5975610396130451 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.03416768485591063, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0017266150412779163}. Best is trial 3 with value: 0.6421171442728866.

Running time: 1.8 sec
OOF RMSE: 2.40 | R2: 0.60
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 21:40:31,312] Trial 23 finished with value: 0.6296343248767374 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0036479745405355443, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00041358009299571376}. Best is trial 3 with value: 0.6421171442728866.

Running time: 3.1 sec
OOF RMSE: 2.30 | R2: 0.63
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 21:40:34,816] Trial 24 finished with value: 0.6262346925235001 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.003535313326401156, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0003584376981669432}. Best is trial 3 with value: 0.6421171442728866.
[I 2025-07-11 21:40:34,817] A new study created in memory with name: no-name-6d1792a8-a32c-4aba-8d09-c989dac45694
[I 2025-07-11 21:40:34,905] Trial 0 finished with value: 0.19533102911611422 and parameters: {'kernel': 'rbf', 'C': 2.157250768946628, 'epsilon': 0.18659547158766393, 'gamma': 'auto'}. Best is trial 0 with value: 0.19533102911611422.
[I 2025-07-11 21:40:34,983] Trial 1 finished with value: -0.9378400405907912 and parameters: {'kernel': 'sigmoid', 'C': 0.8528891483656581, 'epsilon': 0.1877655719647129, 'gamma': 'scale'}. Best is trial 0 with value: 0.19533102911611422.

Running time: 3.5 sec
OOF RMSE: 2.31 | R2: 0.63

✅ MLP - Mejor R2: 0.64
📋 Parámetros: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.0003496825492993352, 'learning_rate': 'adaptive', 'learning_rate_init': 0.007938182927086238}

Buscando mejores hiperparámetros para SVR...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.39 | R2: 0.20
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 5.26 | R2: -0.94
Fold 1
Fold 2

[I 2025-07-11 21:40:35,060] Trial 2 finished with value: -56.79527844048495 and parameters: {'kernel': 'sigmoid', 'C': 6.258461050744733, 'epsilon': 0.13691746499114407, 'gamma': 'scale'}. Best is trial 0 with value: 0.19533102911611422.
[I 2025-07-11 21:40:35,139] Trial 3 finished with value: 0.26475645020682326 and parameters: {'kernel': 'rbf', 'C': 3.551199301872594, 'epsilon': 0.02177575633189771, 'gamma': 'auto'}. Best is trial 3 with value: 0.26475645020682326.
[I 2025-07-11 21:40:35,215] Trial 4 finished with value: 0.03473585782358124 and parameters: {'kernel': 'rbf', 'C': 0.47903651723256696, 'epsilon': 0.023964195747483062, 'gamma': 'scale'}. Best is trial 3 with value: 0.26475645020682326.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 28.75 | R2: -56.80
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.24 | R2: 0.26
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.72 | R2: 0.03
Fold 1

[I 2025-07-11 21:40:35,292] Trial 5 finished with value: 0.06786085639977246 and parameters: {'kernel': 'rbf', 'C': 0.6274231039282558, 'epsilon': 0.13426235097261593, 'gamma': 'scale'}. Best is trial 3 with value: 0.26475645020682326.
[I 2025-07-11 21:40:35,378] Trial 6 finished with value: -0.15268298907431888 and parameters: {'kernel': 'sigmoid', 'C': 1.131600740829512, 'epsilon': 0.09535417270161159, 'gamma': 'auto'}. Best is trial 3 with value: 0.26475645020682326.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.65 | R2: 0.07
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 4.06 | R2: -0.15
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 21:40:35,459] Trial 7 finished with value: -0.38423101545052485 and parameters: {'kernel': 'sigmoid', 'C': 1.5735103981996628, 'epsilon': 0.13376059577211533, 'gamma': 'auto'}. Best is trial 3 with value: 0.26475645020682326.
[I 2025-07-11 21:40:35,536] Trial 8 finished with value: -0.042338987926606064 and parameters: {'kernel': 'sigmoid', 'C': 0.7364562411690048, 'epsilon': 0.13169407983119774, 'gamma': 'auto'}. Best is trial 3 with value: 0.26475645020682326.
[I 2025-07-11 21:40:35,619] Trial 9 finished with value: -2.6516444517120448 and parameters: {'kernel': 'sigmoid', 'C': 3.7525252069635666, 'epsilon': 0.15754025630927665, 'gamma': 'auto'}. Best is trial 3 with value: 0.26475645020682326.

Fold 5
Running time: 0.1 sec
OOF RMSE: 4.45 | R2: -0.38
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.86 | R2: -0.04
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 7.23 | R2: -2.65
Fold 1
Fold 2

[I 2025-07-11 21:40:35,706] Trial 10 finished with value: -0.0665856409017791 and parameters: {'kernel': 'rbf', 'C': 0.1415514719062245, 'epsilon': 0.01093028539870272, 'gamma': 'auto'}. Best is trial 3 with value: 0.26475645020682326.
[I 2025-07-11 21:40:35,801] Trial 11 finished with value: 0.24887626439557076 and parameters: {'kernel': 'rbf', 'C': 3.2216397304046187, 'epsilon': 0.06739207524439561, 'gamma': 'auto'}. Best is trial 3 with value: 0.26475645020682326.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.91 | R2: -0.07
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.28 | R2: 0.25
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 21:40:35,890] Trial 12 finished with value: 0.4245179178592293 and parameters: {'kernel': 'rbf', 'C': 8.036436415077166, 'epsilon': 0.05878181206616154, 'gamma': 'auto'}. Best is trial 12 with value: 0.4245179178592293.
[I 2025-07-11 21:40:35,982] Trial 13 finished with value: 0.4458692682771179 and parameters: {'kernel': 'rbf', 'C': 9.160835552535229, 'epsilon': 0.051043187109908614, 'gamma': 'auto'}. Best is trial 13 with value: 0.4458692682771179.

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.87 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.81 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.78 | R2: 0.46

[I 2025-07-11 21:40:36,075] Trial 14 finished with value: 0.45769345823357155 and parameters: {'kernel': 'rbf', 'C': 9.900950449325649, 'epsilon': 0.060497205072349666, 'gamma': 'auto'}. Best is trial 14 with value: 0.45769345823357155.
[I 2025-07-11 21:40:36,168] Trial 15 finished with value: 0.4405416672372108 and parameters: {'kernel': 'rbf', 'C': 8.850831765939297, 'epsilon': 0.05657847553607598, 'gamma': 'auto'}. Best is trial 14 with value: 0.45769345823357155.
[I 2025-07-11 21:40:36,265] Trial 16 finished with value: -0.050075081637954044 and parameters: {'kernel': 'rbf', 'C': 0.20058315491372777, 'epsilon': 0.08639427430957944, 'gamma': 'auto'}. Best is trial 14 with value: 0.45769345823357155.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.83 | R2: 0.44
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.87 | R2: -0.05
Fold 1

[I 2025-07-11 21:40:36,348] Trial 17 finished with value: 0.3498384053345057 and parameters: {'kernel': 'rbf', 'C': 5.441421735489755, 'epsilon': 0.041186165804958215, 'gamma': 'auto'}. Best is trial 14 with value: 0.45769345823357155.
[I 2025-07-11 21:40:36,440] Trial 18 finished with value: -0.012096922116178632 and parameters: {'kernel': 'rbf', 'C': 0.29303105019609493, 'epsilon': 0.0778444757448667, 'gamma': 'scale'}. Best is trial 14 with value: 0.45769345823357155.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.05 | R2: 0.35
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.80 | R2: -0.01
Fold 1
Fold 2
Fold 3

[I 2025-07-11 21:40:36,527] Trial 19 finished with value: 0.18954062998528953 and parameters: {'kernel': 'rbf', 'C': 2.1376909244887012, 'epsilon': 0.11086956570465253, 'gamma': 'auto'}. Best is trial 14 with value: 0.45769345823357155.
[I 2025-07-11 21:40:36,617] Trial 20 finished with value: 0.4440620366893887 and parameters: {'kernel': 'rbf', 'C': 9.11821076353108, 'epsilon': 0.038536100661930084, 'gamma': 'auto'}. Best is trial 14 with value: 0.45769345823357155.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.40 | R2: 0.19
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.82 | R2: 0.44
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:40:36,708] Trial 21 finished with value: 0.44224610374446616 and parameters: {'kernel': 'rbf', 'C': 8.981871915387863, 'epsilon': 0.043086303872366734, 'gamma': 'auto'}. Best is trial 14 with value: 0.45769345823357155.
[I 2025-07-11 21:40:36,794] Trial 22 finished with value: 0.3547799470780043 and parameters: {'kernel': 'rbf', 'C': 5.575253555613142, 'epsilon': 0.03343635056846645, 'gamma': 'auto'}. Best is trial 14 with value: 0.45769345823357155.
[I 2025-07-11 21:40:36,876] Trial 23 finished with value: 0.32601904895378464 and parameters: {'kernel': 'rbf', 'C': 4.839090382812673, 'epsilon': 0.05229252164866423, 'gamma': 'auto'}. Best is trial 14 with value: 0.45769345823357155.

Running time: 0.1 sec
OOF RMSE: 2.82 | R2: 0.44
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.04 | R2: 0.35
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.10 | R2: 0.33
Fold 1
Fold 2

[I 2025-07-11 21:40:36,958] Trial 24 finished with value: 0.4492466501464917 and parameters: {'kernel': 'rbf', 'C': 9.36825486149696, 'epsilon': 0.07432111543722443, 'gamma': 'auto'}. Best is trial 14 with value: 0.45769345823357155.
[I 2025-07-11 21:40:36,959] A new study created in memory with name: no-name-f906773a-fb03-4855-b6c7-0494282650f1
[I 2025-07-11 21:40:37,025] Trial 0 finished with value: 0.47360922811290307 and parameters: {'n_neighbors': 9, 'weights': 'uniform', 'leaf_size': 11}. Best is trial 0 with value: 0.47360922811290307.
[I 2025-07-11 21:40:37,092] Trial 1 finished with value: 0.3405780864399972 and parameters: {'n_neighbors': 15, 'weights': 'uniform', 'leaf_size': 40}. Best is trial 0 with value: 0.47360922811290307.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.81 | R2: 0.45

✅ SVR - Mejor R2: 0.46
📋 Parámetros: {'kernel': 'rbf', 'C': 9.900950449325649, 'epsilon': 0.060497205072349666, 'gamma': 'auto'}

Buscando mejores hiperparámetros para KNN...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.74 | R2: 0.47
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.07 | R2: 0.34
Fold 1
Fold 2

[I 2025-07-11 21:40:37,212] Trial 2 finished with value: 0.4913731010729768 and parameters: {'n_neighbors': 12, 'weights': 'distance', 'leaf_size': 19}. Best is trial 2 with value: 0.4913731010729768.
[I 2025-07-11 21:40:37,282] Trial 3 finished with value: 0.6767775625401384 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 15}. Best is trial 3 with value: 0.6767775625401384.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.70 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.15 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:40:37,352] Trial 4 finished with value: 0.41753302774623524 and parameters: {'n_neighbors': 11, 'weights': 'uniform', 'leaf_size': 29}. Best is trial 3 with value: 0.6767775625401384.
[I 2025-07-11 21:40:37,425] Trial 5 finished with value: 0.4913731010729768 and parameters: {'n_neighbors': 12, 'weights': 'distance', 'leaf_size': 40}. Best is trial 3 with value: 0.6767775625401384.
[I 2025-07-11 21:40:37,493] Trial 6 finished with value: 0.41753302774623524 and parameters: {'n_neighbors': 11, 'weights': 'uniform', 'leaf_size': 40}. Best is trial 3 with value: 0.6767775625401384.

Running time: 0.1 sec
OOF RMSE: 2.89 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.70 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.89 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:40:37,559] Trial 7 finished with value: 0.5436573999061807 and parameters: {'n_neighbors': 10, 'weights': 'distance', 'leaf_size': 28}. Best is trial 3 with value: 0.6767775625401384.
[I 2025-07-11 21:40:37,623] Trial 8 finished with value: 0.5806139262215391 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'leaf_size': 35}. Best is trial 3 with value: 0.6767775625401384.
[I 2025-07-11 21:40:37,690] Trial 9 finished with value: 0.5436573999061807 and parameters: {'n_neighbors': 10, 'weights': 'distance', 'leaf_size': 12}. Best is trial 3 with value: 0.6767775625401384.
[I 2025-07-11 21:40:37,759] Trial 10 finished with value: 0.6767775625401384 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 20}. Best is trial 3 with value: 0.6767775625401384.

Running time: 0.1 sec
OOF RMSE: 2.55 | R2: 0.54
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.45 | R2: 0.58
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.55 | R2: 0.54
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.15 | R2: 0.68

[I 2025-07-11 21:40:37,833] Trial 11 finished with value: 0.6767775625401384 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 19}. Best is trial 3 with value: 0.6767775625401384.
[I 2025-07-11 21:40:37,912] Trial 12 finished with value: 0.6665115086497894 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'leaf_size': 19}. Best is trial 3 with value: 0.6767775625401384.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.15 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.18 | R2: 0.67
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 21:40:37,997] Trial 13 finished with value: 0.6426973339677362 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'leaf_size': 16}. Best is trial 3 with value: 0.6767775625401384.
[I 2025-07-11 21:40:38,074] Trial 14 finished with value: 0.606626976733458 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'leaf_size': 24}. Best is trial 3 with value: 0.6767775625401384.
[I 2025-07-11 21:40:38,152] Trial 15 finished with value: 0.6767775625401384 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 24}. Best is trial 3 with value: 0.6767775625401384.

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.26 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.37 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.15 | R2: 0.68
Fold 1
Fold 2

[I 2025-07-11 21:40:38,229] Trial 16 finished with value: 0.5806139262215391 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'leaf_size': 15}. Best is trial 3 with value: 0.6767775625401384.
[I 2025-07-11 21:40:38,303] Trial 17 finished with value: 0.6426973339677362 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'leaf_size': 22}. Best is trial 3 with value: 0.6767775625401384.
[I 2025-07-11 21:40:38,380] Trial 18 finished with value: 0.4926052059773014 and parameters: {'n_neighbors': 8, 'weights': 'uniform', 'leaf_size': 15}. Best is trial 3 with value: 0.6767775625401384.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.45 | R2: 0.58
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.26 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.69 | R2: 0.49
Fold 1

[I 2025-07-11 21:40:38,503] Trial 19 finished with value: 0.6767775625401384 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 10}. Best is trial 3 with value: 0.6767775625401384.
[I 2025-07-11 21:40:38,592] Trial 20 finished with value: 0.6426973339677362 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'leaf_size': 28}. Best is trial 3 with value: 0.6767775625401384.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.15 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.26 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 21:40:38,669] Trial 21 finished with value: 0.6767775625401384 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 19}. Best is trial 3 with value: 0.6767775625401384.
[I 2025-07-11 21:40:38,745] Trial 22 finished with value: 0.6665115086497894 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'leaf_size': 21}. Best is trial 3 with value: 0.6767775625401384.
[I 2025-07-11 21:40:38,826] Trial 23 finished with value: 0.6665115086497894 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'leaf_size': 17}. Best is trial 3 with value: 0.6767775625401384.

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.15 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.18 | R2: 0.67
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.18 | R2: 0.67
Fold 1
Fold 2

[I 2025-07-11 21:40:38,904] Trial 24 finished with value: 0.606626976733458 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'leaf_size': 13}. Best is trial 3 with value: 0.6767775625401384.
[I 2025-07-11 21:40:38,905] A new study created in memory with name: no-name-8a954b1d-5a5b-4eda-9ed6-52b71615f068
[I 2025-07-11 21:40:38,971] Trial 0 finished with value: 0.21637054280166712 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 0 with value: 0.21637054280166712.
[I 2025-07-11 21:40:39,062] Trial 1 finished with value: 0.3370149987052876 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 1 with value: 0.3370149987052876.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.37 | R2: 0.61

✅ KNN - Mejor R2: 0.68
📋 Parámetros: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 15}

Buscando mejores hiperparámetros para LR...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.35 | R2: 0.22
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.08 | R2: 0.34

[I 2025-07-11 21:40:39,157] Trial 2 finished with value: 0.3370149987052876 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 1 with value: 0.3370149987052876.
[I 2025-07-11 21:40:39,239] Trial 3 finished with value: 0.21637054280166368 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 1 with value: 0.3370149987052876.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.08 | R2: 0.34
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.35 | R2: 0.22
Fold 1
Fold 2

[I 2025-07-11 21:40:39,334] Trial 4 finished with value: 0.3370149987052876 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 1 with value: 0.3370149987052876.
[I 2025-07-11 21:40:39,411] Trial 5 finished with value: 0.21637054280166368 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 1 with value: 0.3370149987052876.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.08 | R2: 0.34
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.35 | R2: 0.22
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 21:40:39,513] Trial 6 finished with value: 0.3370149987056208 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 6 with value: 0.3370149987056208.
[I 2025-07-11 21:40:39,591] Trial 7 finished with value: 0.21637054280166712 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 6 with value: 0.3370149987056208.
[I 2025-07-11 21:40:39,677] Trial 8 finished with value: 0.3370149987056208 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 6 with value: 0.3370149987056208.

Fold 5
Running time: 0.1 sec
OOF RMSE: 3.08 | R2: 0.34
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.35 | R2: 0.22
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.08 | R2: 0.34
Fold 1

[I 2025-07-11 21:40:39,848] Trial 9 finished with value: 0.3370149987056208 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 6 with value: 0.3370149987056208.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 3.08 | R2: 0.34
Fold 1
Fold 2
Fold 3

[I 2025-07-11 21:40:39,954] Trial 10 finished with value: 0.3370149987056208 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 6 with value: 0.3370149987056208.
[I 2025-07-11 21:40:40,082] Trial 11 finished with value: 0.3370149987056208 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 6 with value: 0.3370149987056208.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.08 | R2: 0.34
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.08 | R2: 0.34
Fold 1
Fold 2

[I 2025-07-11 21:40:40,193] Trial 12 finished with value: 0.3370149987056208 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 6 with value: 0.3370149987056208.
[I 2025-07-11 21:40:40,303] Trial 13 finished with value: 0.3370149987056208 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 6 with value: 0.3370149987056208.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.08 | R2: 0.34
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.08 | R2: 0.34
Fold 1

[I 2025-07-11 21:40:40,440] Trial 14 finished with value: 0.3370149987056208 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 6 with value: 0.3370149987056208.
[I 2025-07-11 21:40:40,537] Trial 15 finished with value: 0.3370149987056208 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 6 with value: 0.3370149987056208.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.08 | R2: 0.34
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.08 | R2: 0.34
Fold 1
Fold 2

[I 2025-07-11 21:40:40,639] Trial 16 finished with value: 0.3370149987056208 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 6 with value: 0.3370149987056208.
[I 2025-07-11 21:40:40,729] Trial 17 finished with value: 0.3370149987056208 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 6 with value: 0.3370149987056208.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.08 | R2: 0.34
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.08 | R2: 0.34
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 21:40:40,813] Trial 18 finished with value: 0.21637054280166712 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 6 with value: 0.3370149987056208.
[I 2025-07-11 21:40:40,971] Trial 19 finished with value: 0.3370149987056208 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 6 with value: 0.3370149987056208.

Fold 5
Running time: 0.1 sec
OOF RMSE: 3.35 | R2: 0.22
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 3.08 | R2: 0.34
Fold 1

[I 2025-07-11 21:40:41,119] Trial 20 finished with value: 0.3370149987056208 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 6 with value: 0.3370149987056208.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.08 | R2: 0.34
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 21:40:41,303] Trial 21 finished with value: 0.3370149987056208 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 6 with value: 0.3370149987056208.
[I 2025-07-11 21:40:41,454] Trial 22 finished with value: 0.3370149987056208 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 6 with value: 0.3370149987056208.

Fold 5
Running time: 0.2 sec
OOF RMSE: 3.08 | R2: 0.34
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.08 | R2: 0.34
Fold 1

[I 2025-07-11 21:40:41,670] Trial 23 finished with value: 0.3370149987056208 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 6 with value: 0.3370149987056208.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 3.08 | R2: 0.34
Fold 1

[I 2025-07-11 21:40:41,812] Trial 24 finished with value: 0.3370149987056208 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 6 with value: 0.3370149987056208.
[I 2025-07-11 21:40:41,815] A new study created in memory with name: no-name-0dde8d86-931c-4c56-b403-737765b8935b

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.08 | R2: 0.34

✅ LR - Mejor R2: 0.34
📋 Parámetros: {'fit_intercept': False, 'positive': False}

Buscando mejores hiperparámetros para RF...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:40:48,122] Trial 0 finished with value: 0.6010874080245815 and parameters: {'n_estimators': 300, 'max_depth': 6, 'min_samples_split': 3, 'min_samples_leaf': 5, 'bootstrap': False}. Best is trial 0 with value: 0.6010874080245815.

Running time: 6.3 sec
OOF RMSE: 2.39 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:40:49,886] Trial 1 finished with value: 0.636772193834992 and parameters: {'n_estimators': 100, 'max_depth': 7, 'min_samples_split': 4, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 1 with value: 0.636772193834992.

Running time: 1.8 sec
OOF RMSE: 2.28 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:40:59,082] Trial 2 finished with value: 0.6121519273919813 and parameters: {'n_estimators': 300, 'max_depth': 13, 'min_samples_split': 10, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 1 with value: 0.636772193834992.

Running time: 9.2 sec
OOF RMSE: 2.35 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:41:10,966] Trial 3 finished with value: 0.5905776853496217 and parameters: {'n_estimators': 500, 'max_depth': 7, 'min_samples_split': 7, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 1 with value: 0.636772193834992.

Running time: 11.9 sec
OOF RMSE: 2.42 | R2: 0.59
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:41:25,171] Trial 4 finished with value: 0.6638727896406991 and parameters: {'n_estimators': 500, 'max_depth': 9, 'min_samples_split': 6, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 4 with value: 0.6638727896406991.

Running time: 14.2 sec
OOF RMSE: 2.19 | R2: 0.66
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:41:33,628] Trial 5 finished with value: 0.6104629596936152 and parameters: {'n_estimators': 300, 'max_depth': 14, 'min_samples_split': 7, 'min_samples_leaf': 4, 'bootstrap': False}. Best is trial 4 with value: 0.6638727896406991.

Running time: 8.5 sec
OOF RMSE: 2.36 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:41:35,284] Trial 6 finished with value: 0.6235165900641242 and parameters: {'n_estimators': 100, 'max_depth': 8, 'min_samples_split': 3, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 4 with value: 0.6638727896406991.

Running time: 1.7 sec
OOF RMSE: 2.32 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:41:44,128] Trial 7 finished with value: 0.6134075634611965 and parameters: {'n_estimators': 500, 'max_depth': 12, 'min_samples_split': 8, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 4 with value: 0.6638727896406991.

Running time: 8.8 sec
OOF RMSE: 2.35 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:41:54,367] Trial 8 finished with value: 0.600865814206559 and parameters: {'n_estimators': 500, 'max_depth': 6, 'min_samples_split': 6, 'min_samples_leaf': 5, 'bootstrap': False}. Best is trial 4 with value: 0.6638727896406991.

Running time: 10.2 sec
OOF RMSE: 2.39 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:42:08,286] Trial 9 finished with value: 0.607413683111103 and parameters: {'n_estimators': 500, 'max_depth': 11, 'min_samples_split': 10, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 4 with value: 0.6638727896406991.

Running time: 13.9 sec
OOF RMSE: 2.37 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:42:17,691] Trial 10 finished with value: 0.63025382708697 and parameters: {'n_estimators': 500, 'max_depth': 9, 'min_samples_split': 5, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 4 with value: 0.6638727896406991.

Running time: 9.4 sec
OOF RMSE: 2.30 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:42:19,758] Trial 11 finished with value: 0.6442654339159579 and parameters: {'n_estimators': 100, 'max_depth': 10, 'min_samples_split': 4, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 4 with value: 0.6638727896406991.

Running time: 2.1 sec
OOF RMSE: 2.26 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:42:21,934] Trial 12 finished with value: 0.6474695870193199 and parameters: {'n_estimators': 100, 'max_depth': 10, 'min_samples_split': 2, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 4 with value: 0.6638727896406991.

Running time: 2.2 sec
OOF RMSE: 2.25 | R2: 0.65
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:42:23,930] Trial 13 finished with value: 0.6446102384839014 and parameters: {'n_estimators': 100, 'max_depth': 10, 'min_samples_split': 2, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 4 with value: 0.6638727896406991.

Running time: 2.0 sec
OOF RMSE: 2.25 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:42:27,578] Trial 14 finished with value: 0.6521757301431299 and parameters: {'n_estimators': 100, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 4 with value: 0.6638727896406991.

Running time: 3.6 sec
OOF RMSE: 2.23 | R2: 0.65
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:42:42,506] Trial 15 finished with value: 0.6085776642844245 and parameters: {'n_estimators': 500, 'max_depth': 15, 'min_samples_split': 8, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 4 with value: 0.6638727896406991.

Running time: 14.9 sec
OOF RMSE: 2.37 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:42:45,419] Trial 16 finished with value: 0.6305745301230883 and parameters: {'n_estimators': 100, 'max_depth': 12, 'min_samples_split': 5, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 4 with value: 0.6638727896406991.

Running time: 2.9 sec
OOF RMSE: 2.30 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:42:48,516] Trial 17 finished with value: 0.6212765232263047 and parameters: {'n_estimators': 100, 'max_depth': 15, 'min_samples_split': 9, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 4 with value: 0.6638727896406991.

Running time: 3.1 sec
OOF RMSE: 2.33 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:43:01,401] Trial 18 finished with value: 0.6058657744271276 and parameters: {'n_estimators': 500, 'max_depth': 8, 'min_samples_split': 6, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 4 with value: 0.6638727896406991.

Running time: 12.9 sec
OOF RMSE: 2.37 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:43:10,184] Trial 19 finished with value: 0.631481415783991 and parameters: {'n_estimators': 300, 'max_depth': 12, 'min_samples_split': 4, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 4 with value: 0.6638727896406991.

Running time: 8.8 sec
OOF RMSE: 2.30 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:43:26,633] Trial 20 finished with value: 0.6488434469232832 and parameters: {'n_estimators': 500, 'max_depth': 14, 'min_samples_split': 5, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 4 with value: 0.6638727896406991.

Running time: 16.4 sec
OOF RMSE: 2.24 | R2: 0.65
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:43:43,065] Trial 21 finished with value: 0.6488434469232832 and parameters: {'n_estimators': 500, 'max_depth': 14, 'min_samples_split': 5, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 4 with value: 0.6638727896406991.

Running time: 16.4 sec
OOF RMSE: 2.24 | R2: 0.65
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:43:58,871] Trial 22 finished with value: 0.627471357259797 and parameters: {'n_estimators': 500, 'max_depth': 14, 'min_samples_split': 7, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 4 with value: 0.6638727896406991.

Running time: 15.8 sec
OOF RMSE: 2.31 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:44:14,701] Trial 23 finished with value: 0.6070514760703696 and parameters: {'n_estimators': 500, 'max_depth': 15, 'min_samples_split': 3, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 4 with value: 0.6638727896406991.

Running time: 15.8 sec
OOF RMSE: 2.37 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:44:30,710] Trial 24 finished with value: 0.6624280381287644 and parameters: {'n_estimators': 500, 'max_depth': 13, 'min_samples_split': 6, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 4 with value: 0.6638727896406991.
[I 2025-07-11 21:44:30,711] A new study created in memory with name: no-name-b6c2cc8b-84be-412b-b7c7-18401edb0074

Running time: 16.0 sec
OOF RMSE: 2.20 | R2: 0.66

✅ RF - Mejor R2: 0.66
📋 Parámetros: {'n_estimators': 500, 'max_depth': 9, 'min_samples_split': 6, 'min_samples_leaf': 1, 'bootstrap': False}

Buscando mejores hiperparámetros para CAT...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:45:43,775] Trial 0 finished with value: 0.7520295464068313 and parameters: {'iterations': 500, 'learning_rate': 0.010210083832698101, 'depth': 10, 'l2_leaf_reg': 1.1287401033538447}. Best is trial 0 with value: 0.7520295464068313.

Running time: 73.1 sec
OOF RMSE: 1.88 | R2: 0.75
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:48:28,831] Trial 1 finished with value: 0.7645014446030066 and parameters: {'iterations': 2000, 'learning_rate': 0.07165382678927044, 'depth': 9, 'l2_leaf_reg': 1.8160245893729459}. Best is trial 1 with value: 0.7645014446030066.

Running time: 165.0 sec
OOF RMSE: 1.84 | R2: 0.76
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:49:05,136] Trial 2 finished with value: 0.7569113600855704 and parameters: {'iterations': 1000, 'learning_rate': 0.08208740240556735, 'depth': 8, 'l2_leaf_reg': 4.12477946484737}. Best is trial 1 with value: 0.7645014446030066.

Running time: 36.3 sec
OOF RMSE: 1.86 | R2: 0.76
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:49:13,848] Trial 3 finished with value: 0.7686239911510273 and parameters: {'iterations': 2000, 'learning_rate': 0.01375366394545636, 'depth': 5, 'l2_leaf_reg': 1.2490482656711204}. Best is trial 3 with value: 0.7686239911510273.

Running time: 8.7 sec
OOF RMSE: 1.82 | R2: 0.77
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:49:19,666] Trial 4 finished with value: 0.7505225274363918 and parameters: {'iterations': 2000, 'learning_rate': 0.012884545142971743, 'depth': 4, 'l2_leaf_reg': 3.47761229806801}. Best is trial 3 with value: 0.7686239911510273.

Running time: 5.8 sec
OOF RMSE: 1.89 | R2: 0.75
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:49:26,638] Trial 5 finished with value: 0.776171884687112 and parameters: {'iterations': 500, 'learning_rate': 0.06281345861512878, 'depth': 7, 'l2_leaf_reg': 2.2486616599581906}. Best is trial 5 with value: 0.776171884687112.

Running time: 7.0 sec
OOF RMSE: 1.79 | R2: 0.78
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:49:33,544] Trial 6 finished with value: 0.7694173130589039 and parameters: {'iterations': 1000, 'learning_rate': 0.029715650077431, 'depth': 6, 'l2_leaf_reg': 6.29610543456714}. Best is trial 5 with value: 0.776171884687112.

Running time: 6.9 sec
OOF RMSE: 1.82 | R2: 0.77
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:49:37,681] Trial 7 finished with value: 0.7614499792032333 and parameters: {'iterations': 1000, 'learning_rate': 0.04869876631672678, 'depth': 5, 'l2_leaf_reg': 7.365084758538012}. Best is trial 5 with value: 0.776171884687112.

Running time: 4.1 sec
OOF RMSE: 1.85 | R2: 0.76
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:49:40,650] Trial 8 finished with value: 0.752155376463447 and parameters: {'iterations': 1000, 'learning_rate': 0.020091709610148768, 'depth': 4, 'l2_leaf_reg': 6.213475566939614}. Best is trial 5 with value: 0.776171884687112.

Running time: 3.0 sec
OOF RMSE: 1.88 | R2: 0.75
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:50:52,346] Trial 9 finished with value: 0.7725782844725769 and parameters: {'iterations': 2000, 'learning_rate': 0.021182749007572683, 'depth': 8, 'l2_leaf_reg': 8.10171830535303}. Best is trial 5 with value: 0.776171884687112.

Running time: 71.7 sec
OOF RMSE: 1.80 | R2: 0.77
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:50:59,423] Trial 10 finished with value: 0.7820099194886074 and parameters: {'iterations': 500, 'learning_rate': 0.04073200027341339, 'depth': 7, 'l2_leaf_reg': 3.8137510406675874}. Best is trial 10 with value: 0.7820099194886074.

Running time: 7.1 sec
OOF RMSE: 1.77 | R2: 0.78
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:51:06,670] Trial 11 finished with value: 0.775636655883916 and parameters: {'iterations': 500, 'learning_rate': 0.048761844556275455, 'depth': 7, 'l2_leaf_reg': 3.3932818871713155}. Best is trial 10 with value: 0.7820099194886074.

Running time: 7.2 sec
OOF RMSE: 1.79 | R2: 0.78
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:51:13,880] Trial 12 finished with value: 0.7735856701319852 and parameters: {'iterations': 500, 'learning_rate': 0.04947304217952762, 'depth': 7, 'l2_leaf_reg': 4.774912614146116}. Best is trial 10 with value: 0.7820099194886074.

Running time: 7.2 sec
OOF RMSE: 1.80 | R2: 0.77
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:51:17,273] Trial 13 finished with value: 0.7769400108173882 and parameters: {'iterations': 500, 'learning_rate': 0.035067043733249245, 'depth': 6, 'l2_leaf_reg': 2.588493691689691}. Best is trial 10 with value: 0.7820099194886074.

Running time: 3.4 sec
OOF RMSE: 1.79 | R2: 0.78
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:51:20,448] Trial 14 finished with value: 0.7693662230939712 and parameters: {'iterations': 500, 'learning_rate': 0.030141400365780974, 'depth': 6, 'l2_leaf_reg': 2.6933822037472464}. Best is trial 10 with value: 0.7820099194886074.

Running time: 3.2 sec
OOF RMSE: 1.82 | R2: 0.77
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:51:23,603] Trial 15 finished with value: 0.769518771309401 and parameters: {'iterations': 500, 'learning_rate': 0.03582883823178966, 'depth': 6, 'l2_leaf_reg': 5.078696849308283}. Best is trial 10 with value: 0.7820099194886074.

Running time: 3.1 sec
OOF RMSE: 1.82 | R2: 0.77
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:51:42,191] Trial 16 finished with value: 0.7675703283332362 and parameters: {'iterations': 500, 'learning_rate': 0.0385274679185647, 'depth': 8, 'l2_leaf_reg': 2.986665522185489}. Best is trial 10 with value: 0.7820099194886074.

Running time: 18.6 sec
OOF RMSE: 1.82 | R2: 0.77
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:51:44,243] Trial 17 finished with value: 0.7719631361340628 and parameters: {'iterations': 500, 'learning_rate': 0.02113923967527815, 'depth': 5, 'l2_leaf_reg': 4.165600954433085}. Best is trial 10 with value: 0.7820099194886074.

Running time: 2.0 sec
OOF RMSE: 1.81 | R2: 0.77
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:52:25,900] Trial 18 finished with value: 0.7653357207033799 and parameters: {'iterations': 500, 'learning_rate': 0.02713854626951683, 'depth': 9, 'l2_leaf_reg': 6.024475120591145}. Best is trial 10 with value: 0.7820099194886074.

Running time: 41.7 sec
OOF RMSE: 1.83 | R2: 0.77
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:52:29,208] Trial 19 finished with value: 0.7707810117913098 and parameters: {'iterations': 500, 'learning_rate': 0.09548401594500121, 'depth': 6, 'l2_leaf_reg': 9.51831694922372}. Best is trial 10 with value: 0.7820099194886074.

Running time: 3.3 sec
OOF RMSE: 1.81 | R2: 0.77
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:53:10,955] Trial 20 finished with value: 0.7712087657061085 and parameters: {'iterations': 500, 'learning_rate': 0.041000403842134596, 'depth': 9, 'l2_leaf_reg': 4.118088966027912}. Best is trial 10 with value: 0.7820099194886074.

Running time: 41.7 sec
OOF RMSE: 1.81 | R2: 0.77
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:53:17,943] Trial 21 finished with value: 0.7798104289299699 and parameters: {'iterations': 500, 'learning_rate': 0.06641013113756401, 'depth': 7, 'l2_leaf_reg': 1.891596088716129}. Best is trial 10 with value: 0.7820099194886074.

Running time: 7.0 sec
OOF RMSE: 1.77 | R2: 0.78
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:53:25,007] Trial 22 finished with value: 0.7705538294836891 and parameters: {'iterations': 500, 'learning_rate': 0.05964246940807435, 'depth': 7, 'l2_leaf_reg': 2.0583367900760403}. Best is trial 10 with value: 0.7820099194886074.

Running time: 7.1 sec
OOF RMSE: 1.81 | R2: 0.77
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:53:32,209] Trial 23 finished with value: 0.7625610342235308 and parameters: {'iterations': 500, 'learning_rate': 0.06042134215914813, 'depth': 7, 'l2_leaf_reg': 2.685478780668893}. Best is trial 10 with value: 0.7820099194886074.

Running time: 7.2 sec
OOF RMSE: 1.84 | R2: 0.76
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:53:50,645] Trial 24 finished with value: 0.7684803183788227 and parameters: {'iterations': 500, 'learning_rate': 0.02617559058512008, 'depth': 8, 'l2_leaf_reg': 1.6394760281997558}. Best is trial 10 with value: 0.7820099194886074.
[I 2025-07-11 21:53:50,646] A new study created in memory with name: no-name-91279b1c-0129-4d52-b109-cceabaf090d2
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.542e+00, tolerance: 3.043e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.726e+00, tolerance: 2.664e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.277e+00, tolerance: 2.195e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.892e-01, tolerance: 2.302e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.481e-01, tolerance: 2.844e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 21:53:50,771] Trial 0 finished with value: 0.1618730277315159 and parameters: {'alpha': 0.021957559325660337, 'l1_ratio': 0.407052858973052}. Best is trial 0 with value: 0.1618730277315159.

Running time: 18.4 sec
OOF RMSE: 1.82 | R2: 0.77

✅ CAT - Mejor R2: 0.78
📋 Parámetros: {'iterations': 500, 'learning_rate': 0.04073200027341339, 'depth': 7, 'l2_leaf_reg': 3.8137510406675874}

Buscando mejores hiperparámetros para EN...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.46 | R2: 0.16
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.589e+02, tolerance: 3.043e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.874e+02, tolerance: 2.664e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.759e+02, tolerance: 2.195e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.036e+02, tolerance: 2.302e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.743e+02, tolerance: 2.844e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 21:53:50,947] Trial 1 finished with value: 0.004304768396949488 and parameters: {'alpha': 0.0009211072258843221, 'l1_ratio': 0.9036268539806613}. Best is trial 0 with value: 0.1618730277315159.

Fold 3
Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 3.77 | R2: 0.00
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 21:53:51,136] Trial 2 finished with value: 0.1214532342848319 and parameters: {'alpha': 0.41420427640415114, 'l1_ratio': 0.6851116201536511}. Best is trial 0 with value: 0.1618730277315159.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.836e+02, tolerance: 3.043e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.682e+02, tolerance: 2.664e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.967e+02, tolerance: 2.195e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.854e+02, tolerance: 2.302e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.231e+02, tolerance: 2.844e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 21:53:51,286] Trial 3 finished with value: -0.05187308812934632 and parameters: {'alpha': 0.0001116402332757391, 'l1_ratio': 0.5296436264643102}. Best is trial 0 with value: 0.1618730277315159.

Fold 5
Running time: 0.2 sec
OOF RMSE: 3.54 | R2: 0.12
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.88 | R2: -0.05
Fold 1

[I 2025-07-11 21:53:51,449] Trial 4 finished with value: 0.16746697709689107 and parameters: {'alpha': 0.6537746778782485, 'l1_ratio': 0.24504260962180502}. Best is trial 4 with value: 0.16746697709689107.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 3.45 | R2: 0.17
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.076e+02, tolerance: 3.043e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.873e+02, tolerance: 2.664e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.124e+02, tolerance: 2.195e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.039e+02, tolerance: 2.302e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.424e+02, tolerance: 2.844e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 21:53:51,705] Trial 5 finished with value: -0.046782632866859686 and parameters: {'alpha': 0.0001275326517437495, 'l1_ratio': 0.08345417766983443}. Best is trial 4 with value: 0.16746697709689107.

Fold 3
Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 3.87 | R2: -0.05
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.677e+01, tolerance: 3.043e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.578e+01, tolerance: 2.664e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.537e+01, tolerance: 2.195e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.199e+01, tolerance: 2.302e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.841e+01, tolerance: 2.844e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 21:53:51,871] Trial 6 finished with value: 0.06996375677903421 and parameters: {'alpha': 0.004175582288126369, 'l1_ratio': 0.7710786060992287}. Best is trial 4 with value: 0.16746697709689107.
[I 2025-07-11 21:53:51,960] Trial 7 finished with value: 0.006752821518211327 and parameters: {'alpha': 2.04478687235423, 'l1_ratio': 0.40939335843518077}. Best is trial 4 with value: 0.16746697709689107.

Fold 3
Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 3.65 | R2: 0.07
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.77 | R2: 0.01
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.870e+02, tolerance: 3.043e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.228e+02, tolerance: 2.664e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.420e+02, tolerance: 2.195e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.291e+02, tolerance: 2.302e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.823e+02, tolerance: 2.844e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 21:53:52,109] Trial 8 finished with value: 0.011244674680872535 and parameters: {'alpha': 0.0008570601755294281, 'l1_ratio': 0.6844429479623853}. Best is trial 4 with value: 0.16746697709689107.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.180e+02, tolerance: 3.043e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.941e+02, tolerance: 2.664e-01
  model = cd_fast.enet_coordinate_descent(

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.76 | R2: 0.01
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.472e+02, tolerance: 2.195e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.789e+02, tolerance: 2.302e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.960e+02, tolerance: 2.844e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 21:53:52,372] Trial 9 finished with value: 0.07432468797386538 and parameters: {'alpha': 0.004495739211752642, 'l1_ratio': 0.03992969082228115}. Best is trial 4 with value: 0.16746697709689107.

Fold 4
Fold 5
Running time: 0.3 sec
OOF RMSE: 3.64 | R2: 0.07
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 21:53:52,490] Trial 10 finished with value: -0.0003636740809507266 and parameters: {'alpha': 9.286947031978139, 'l1_ratio': 0.254345837267821}. Best is trial 4 with value: 0.16746697709689107.
[I 2025-07-11 21:53:52,614] Trial 11 finished with value: 0.2359278630341739 and parameters: {'alpha': 0.11222335057093939, 'l1_ratio': 0.31092787623867874}. Best is trial 11 with value: 0.2359278630341739.

Fold 5
Running time: 0.1 sec
OOF RMSE: 3.78 | R2: -0.00
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.31 | R2: 0.24
Fold 1
Fold 2
Fold 3

[I 2025-07-11 21:53:52,716] Trial 12 finished with value: 0.24010737495509638 and parameters: {'alpha': 0.21338827741827626, 'l1_ratio': 0.2437523180243329}. Best is trial 12 with value: 0.24010737495509638.
[I 2025-07-11 21:53:52,846] Trial 13 finished with value: 0.22475365732865504 and parameters: {'alpha': 0.07768672397477554, 'l1_ratio': 0.2548478863306859}. Best is trial 12 with value: 0.24010737495509638.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.30 | R2: 0.24
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.33 | R2: 0.22
Fold 1

[I 2025-07-11 21:53:52,969] Trial 14 finished with value: 0.23015129510230337 and parameters: {'alpha': 0.10490553559851809, 'l1_ratio': 0.16174323123433054}. Best is trial 12 with value: 0.24010737495509638.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.875e-01, tolerance: 3.043e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.723e+00, tolerance: 2.664e-01
  model = cd_fast.enet_coordinate_descent(

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.32 | R2: 0.23
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.174e-01, tolerance: 2.195e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 21:53:53,092] Trial 15 finished with value: 0.18899306731000265 and parameters: {'alpha': 0.0341913063099248, 'l1_ratio': 0.46585291432302955}. Best is trial 12 with value: 0.24010737495509638.
[I 2025-07-11 21:53:53,229] Trial 16 finished with value: 0.23100259501373932 and parameters: {'alpha': 0.2967677562468533, 'l1_ratio': 0.2808395823703458}. Best is trial 12 with value: 0.24010737495509638.

Running time: 0.1 sec
OOF RMSE: 3.41 | R2: 0.19
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.32 | R2: 0.23
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 21:53:53,325] Trial 17 finished with value: 0.006743161903785433 and parameters: {'alpha': 1.7234625556196046, 'l1_ratio': 0.5683079024706963}. Best is trial 12 with value: 0.24010737495509638.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.000e+02, tolerance: 3.043e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.672e+02, tolerance: 2.664e-01
  model = cd_fast.enet_coordinate_descent(

Fold 5
Running time: 0.1 sec
OOF RMSE: 3.77 | R2: 0.01
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.703e+02, tolerance: 2.195e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.141e+01, tolerance: 2.302e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.257e+02, tolerance: 2.844e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 21:53:53,543] Trial 18 finished with value: 0.130582335497762 and parameters: {'alpha': 0.013750251336336401, 'l1_ratio': 0.12440952275769784}. Best is trial 12 with value: 0.24010737495509638.
[I 2025-07-11 21:53:53,715] Trial 19 finished with value: 0.24212389499606612 and parameters: {'alpha': 0.14809643318332405, 'l1_ratio': 0.3592767234841121}. Best is trial 19 with value: 0.24212389499606612.

Running time: 0.2 sec
OOF RMSE: 3.53 | R2: 0.13
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 3.29 | R2: 0.24
Fold 1

[I 2025-07-11 21:53:53,842] Trial 20 finished with value: -0.00031783975871735315 and parameters: {'alpha': 3.9360779181050773, 'l1_ratio': 0.40408402181545466}. Best is trial 19 with value: 0.24212389499606612.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.78 | R2: -0.00
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 21:53:53,997] Trial 21 finished with value: 0.23662848819322257 and parameters: {'alpha': 0.11429413318386095, 'l1_ratio': 0.32401397405808496}. Best is trial 19 with value: 0.24212389499606612.
[I 2025-07-11 21:53:54,130] Trial 22 finished with value: 0.2406867281620777 and parameters: {'alpha': 0.20231396596887743, 'l1_ratio': 0.33655155643192586}. Best is trial 19 with value: 0.24212389499606612.

Fold 5
Running time: 0.1 sec
OOF RMSE: 3.30 | R2: 0.24
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.29 | R2: 0.24
Fold 1
Fold 2

[I 2025-07-11 21:53:54,244] Trial 23 finished with value: 0.18151898135296352 and parameters: {'alpha': 0.7146877435973865, 'l1_ratio': 0.1740902054614792}. Best is trial 19 with value: 0.24212389499606612.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.42 | R2: 0.18
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:53:54,417] Trial 24 finished with value: 0.24259870573940934 and parameters: {'alpha': 0.15942821422511425, 'l1_ratio': 0.3605366068810148}. Best is trial 24 with value: 0.24259870573940934.
[I 2025-07-11 21:53:54,419] A new study created in memory with name: no-name-e62d7671-2feb-4083-ae85-6c2a8cb4e84c

Running time: 0.2 sec
OOF RMSE: 3.29 | R2: 0.24

✅ EN - Mejor R2: 0.24
📋 Parámetros: {'alpha': 0.15942821422511425, 'l1_ratio': 0.3605366068810148}

🔍 Optimizando en C2X-Complex_rhow_5x5_depth_lt_1...
Buscando mejores hiperparámetros para XGB...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:54:01,346] Trial 0 finished with value: 0.5206405138766008 and parameters: {'n_estimators': 500, 'learning_rate': 0.008807223382382965, 'max_depth': 8, 'min_child_weight': 2, 'subsample': 0.9338041904874441, 'colsample_bytree': 0.9721060410706956}. Best is trial 0 with value: 0.5206405138766008.

Running time: 6.9 sec
OOF RMSE: 2.40 | R2: 0.52
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:54:04,644] Trial 1 finished with value: 0.5805580625375577 and parameters: {'n_estimators': 500, 'learning_rate': 0.011012829650585742, 'max_depth': 8, 'min_child_weight': 2, 'subsample': 0.6820771296890723, 'colsample_bytree': 0.6531595378970182}. Best is trial 1 with value: 0.5805580625375577.

Running time: 3.3 sec
OOF RMSE: 2.25 | R2: 0.58
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:54:14,811] Trial 2 finished with value: 0.5548614783640407 and parameters: {'n_estimators': 1000, 'learning_rate': 0.007564757320046996, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.9510911497096285, 'colsample_bytree': 0.8693312167462399}. Best is trial 1 with value: 0.5805580625375577.

Running time: 10.2 sec
OOF RMSE: 2.31 | R2: 0.55
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:54:27,565] Trial 3 finished with value: 0.5839085213142026 and parameters: {'n_estimators': 2000, 'learning_rate': 0.015118922371233412, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.873659966407351, 'colsample_bytree': 0.7907384987021905}. Best is trial 3 with value: 0.5839085213142026.

Running time: 12.7 sec
OOF RMSE: 2.24 | R2: 0.58
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:54:41,082] Trial 4 finished with value: 0.5894676441589741 and parameters: {'n_estimators': 2000, 'learning_rate': 0.016892808875186474, 'max_depth': 8, 'min_child_weight': 3, 'subsample': 0.8381044674707269, 'colsample_bytree': 0.7268645557255137}. Best is trial 4 with value: 0.5894676441589741.

Running time: 13.5 sec
OOF RMSE: 2.22 | R2: 0.59
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:54:43,279] Trial 5 finished with value: 0.5945720813552323 and parameters: {'n_estimators': 500, 'learning_rate': 0.024320609215850563, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.781656006642426, 'colsample_bytree': 0.6033016797420071}. Best is trial 5 with value: 0.5945720813552323.

Running time: 2.2 sec
OOF RMSE: 2.21 | R2: 0.59
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:54:45,945] Trial 6 finished with value: 0.5155300748428097 and parameters: {'n_estimators': 500, 'learning_rate': 0.020889321676414073, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.967954329129884, 'colsample_bytree': 0.7161154115123445}. Best is trial 5 with value: 0.5945720813552323.

Running time: 2.7 sec
OOF RMSE: 2.41 | R2: 0.52
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:54:55,251] Trial 7 finished with value: 0.523788962706116 and parameters: {'n_estimators': 2000, 'learning_rate': 0.034583615314852274, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.9853249249863809, 'colsample_bytree': 0.768751773314823}. Best is trial 5 with value: 0.5945720813552323.

Running time: 9.3 sec
OOF RMSE: 2.39 | R2: 0.52
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:55:03,869] Trial 8 finished with value: 0.539652233525052 and parameters: {'n_estimators': 1000, 'learning_rate': 0.008280893122338184, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.8917801466571232, 'colsample_bytree': 0.937953964563092}. Best is trial 5 with value: 0.5945720813552323.

Running time: 8.6 sec
OOF RMSE: 2.35 | R2: 0.54
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:55:11,278] Trial 9 finished with value: 0.5642709355551627 and parameters: {'n_estimators': 1000, 'learning_rate': 0.02697479588948367, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.8568388872604255, 'colsample_bytree': 0.6363050929155963}. Best is trial 5 with value: 0.5945720813552323.

Running time: 7.4 sec
OOF RMSE: 2.29 | R2: 0.56
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:55:13,536] Trial 10 finished with value: 0.5886234832301402 and parameters: {'n_estimators': 500, 'learning_rate': 0.07873563259860072, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.7351927709609132, 'colsample_bytree': 0.6037642479947394}. Best is trial 5 with value: 0.5945720813552323.

Running time: 2.3 sec
OOF RMSE: 2.22 | R2: 0.59
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:55:22,627] Trial 11 finished with value: 0.5980702727186886 and parameters: {'n_estimators': 2000, 'learning_rate': 0.04500313274138926, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.7789449620654622, 'colsample_bytree': 0.7055255090494265}. Best is trial 11 with value: 0.5980702727186886.

Running time: 9.1 sec
OOF RMSE: 2.20 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:55:31,325] Trial 12 finished with value: 0.5966435972197887 and parameters: {'n_estimators': 2000, 'learning_rate': 0.05050931067163684, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.773370281050554, 'colsample_bytree': 0.68452549908167}. Best is trial 11 with value: 0.5980702727186886.

Running time: 8.7 sec
OOF RMSE: 2.20 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:55:40,686] Trial 13 finished with value: 0.5740634454683868 and parameters: {'n_estimators': 2000, 'learning_rate': 0.057037799511988604, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.6313214012703459, 'colsample_bytree': 0.69511347792306}. Best is trial 11 with value: 0.5980702727186886.

Running time: 9.4 sec
OOF RMSE: 2.26 | R2: 0.57
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:55:49,274] Trial 14 finished with value: 0.5723689389878537 and parameters: {'n_estimators': 2000, 'learning_rate': 0.04601786213342941, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.7604884720641474, 'colsample_bytree': 0.8206558746821615}. Best is trial 11 with value: 0.5980702727186886.

Running time: 8.6 sec
OOF RMSE: 2.27 | R2: 0.57
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:55:56,673] Trial 15 finished with value: 0.5430402508950603 and parameters: {'n_estimators': 2000, 'learning_rate': 0.09672831421187418, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.7177881329899625, 'colsample_bytree': 0.6800390396070336}. Best is trial 11 with value: 0.5980702727186886.

Running time: 7.4 sec
OOF RMSE: 2.34 | R2: 0.54
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:56:04,906] Trial 16 finished with value: 0.5700670091419507 and parameters: {'n_estimators': 2000, 'learning_rate': 0.05229946988804781, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.8150784333016732, 'colsample_bytree': 0.7606890936209433}. Best is trial 11 with value: 0.5980702727186886.

Running time: 8.2 sec
OOF RMSE: 2.27 | R2: 0.57
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:56:15,383] Trial 17 finished with value: 0.6029612331475087 and parameters: {'n_estimators': 2000, 'learning_rate': 0.03564592788391171, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.6695945205028145, 'colsample_bytree': 0.8540434512347715}. Best is trial 17 with value: 0.6029612331475087.

Running time: 10.5 sec
OOF RMSE: 2.18 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:56:25,229] Trial 18 finished with value: 0.5979285286469145 and parameters: {'n_estimators': 2000, 'learning_rate': 0.005098168198046409, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.6371631772517707, 'colsample_bytree': 0.8552465861166539}. Best is trial 17 with value: 0.6029612331475087.

Running time: 9.8 sec
OOF RMSE: 2.20 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:56:35,932] Trial 19 finished with value: 0.6069528376923993 and parameters: {'n_estimators': 2000, 'learning_rate': 0.035752020625470865, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.6791784716332401, 'colsample_bytree': 0.909274522422263}. Best is trial 19 with value: 0.6069528376923993.

Running time: 10.7 sec
OOF RMSE: 2.17 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:56:40,778] Trial 20 finished with value: 0.5810643404579092 and parameters: {'n_estimators': 1000, 'learning_rate': 0.03296180975896882, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.6016069553875656, 'colsample_bytree': 0.9192332942971291}. Best is trial 19 with value: 0.6069528376923993.

Running time: 4.8 sec
OOF RMSE: 2.24 | R2: 0.58
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:56:51,603] Trial 21 finished with value: 0.6026479054256689 and parameters: {'n_estimators': 2000, 'learning_rate': 0.033471704513714944, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.6873648872103431, 'colsample_bytree': 0.8768338061961956}. Best is trial 19 with value: 0.6069528376923993.

Running time: 10.8 sec
OOF RMSE: 2.19 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:57:02,158] Trial 22 finished with value: 0.5988620322519248 and parameters: {'n_estimators': 2000, 'learning_rate': 0.03598870537923301, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.6834491114128989, 'colsample_bytree': 0.8883885214296023}. Best is trial 19 with value: 0.6069528376923993.

Running time: 10.5 sec
OOF RMSE: 2.20 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:57:10,596] Trial 23 finished with value: 0.5681101909806603 and parameters: {'n_estimators': 2000, 'learning_rate': 0.06736078981698845, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.6787247284564607, 'colsample_bytree': 0.8357462338321325}. Best is trial 19 with value: 0.6069528376923993.

Running time: 8.4 sec
OOF RMSE: 2.28 | R2: 0.57
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:57:22,077] Trial 24 finished with value: 0.5881305182277597 and parameters: {'n_estimators': 2000, 'learning_rate': 0.028892886425217704, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.7215688332618015, 'colsample_bytree': 0.9962188136253614}. Best is trial 19 with value: 0.6069528376923993.
[I 2025-07-11 21:57:22,079] A new study created in memory with name: no-name-79912e90-c93e-45b0-9e90-ecf6c13c7162

Running time: 11.5 sec
OOF RMSE: 2.22 | R2: 0.59

✅ XGB - Mejor R2: 0.61
📋 Parámetros: {'n_estimators': 2000, 'learning_rate': 0.035752020625470865, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.6791784716332401, 'colsample_bytree': 0.909274522422263}

Buscando mejores hiperparámetros para LBM...
Fold 1
Fold 2
Fold 3

[I 2025-07-11 21:57:22,422] Trial 0 finished with value: 0.6395895618311335 and parameters: {'learning_rate': 0.008199932486200268, 'num_leaves': 60, 'max_depth': 5, 'min_child_samples': 5, 'subsample': 0.6782995047764365, 'colsample_bytree': 0.7802529124537346, 'n_estimators': 500}. Best is trial 0 with value: 0.6395895618311335.

Fold 4
Fold 5
Running time: 0.3 sec
OOF RMSE: 2.08 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 21:57:22,778] Trial 1 finished with value: 0.5342879435879212 and parameters: {'learning_rate': 0.009066115800590507, 'num_leaves': 80, 'max_depth': 7, 'min_child_samples': 13, 'subsample': 0.8956911748443697, 'colsample_bytree': 0.95895016282544, 'n_estimators': 500}. Best is trial 0 with value: 0.6395895618311335.

Fold 5
Running time: 0.4 sec
OOF RMSE: 2.37 | R2: 0.53
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:57:23,379] Trial 2 finished with value: 0.5400008739690768 and parameters: {'learning_rate': 0.005098047816912507, 'num_leaves': 20, 'max_depth': 8, 'min_child_samples': 16, 'subsample': 0.9438731944412491, 'colsample_bytree': 0.6210787371106329, 'n_estimators': 1000}. Best is trial 0 with value: 0.6395895618311335.

Running time: 0.6 sec
OOF RMSE: 2.35 | R2: 0.54
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:57:24,485] Trial 3 finished with value: 0.5776443144847789 and parameters: {'learning_rate': 0.007862015202870838, 'num_leaves': 40, 'max_depth': 7, 'min_child_samples': 17, 'subsample': 0.7731734935715808, 'colsample_bytree': 0.867752714151186, 'n_estimators': 2000}. Best is trial 0 with value: 0.6395895618311335.

Running time: 1.1 sec
OOF RMSE: 2.25 | R2: 0.58
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 21:57:25,156] Trial 4 finished with value: 0.5752493101175506 and parameters: {'learning_rate': 0.0877873688765647, 'num_leaves': 40, 'max_depth': 8, 'min_child_samples': 16, 'subsample': 0.7973283417355707, 'colsample_bytree': 0.9243285265092235, 'n_estimators': 1000}. Best is trial 0 with value: 0.6395895618311335.

Fold 5
Running time: 0.7 sec
OOF RMSE: 2.26 | R2: 0.58
Fold 1
Fold 2

[I 2025-07-11 21:57:25,387] Trial 5 finished with value: 0.5590442902198345 and parameters: {'learning_rate': 0.010790957587987595, 'num_leaves': 40, 'max_depth': 5, 'min_child_samples': 18, 'subsample': 0.8097402766781822, 'colsample_bytree': 0.6831517756237568, 'n_estimators': 500}. Best is trial 0 with value: 0.6395895618311335.

Fold 3
Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 2.30 | R2: 0.56
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:57:26,331] Trial 6 finished with value: 0.5554133321048188 and parameters: {'learning_rate': 0.08264199298961496, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 19, 'subsample': 0.7713614833717588, 'colsample_bytree': 0.6531057676726464, 'n_estimators': 2000}. Best is trial 0 with value: 0.6395895618311335.

Running time: 0.9 sec
OOF RMSE: 2.31 | R2: 0.56
Fold 1
Fold 2
Fold 3

[I 2025-07-11 21:57:26,811] Trial 7 finished with value: 0.636695355923165 and parameters: {'learning_rate': 0.09374053154826702, 'num_leaves': 20, 'max_depth': 8, 'min_child_samples': 25, 'subsample': 0.7151456888793936, 'colsample_bytree': 0.9569931800262027, 'n_estimators': 1000}. Best is trial 0 with value: 0.6395895618311335.

Fold 4
Fold 5
Running time: 0.5 sec
OOF RMSE: 2.09 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:57:27,395] Trial 8 finished with value: 0.5568821573618354 and parameters: {'learning_rate': 0.021681085419320074, 'num_leaves': 60, 'max_depth': 8, 'min_child_samples': 19, 'subsample': 0.7197165493091725, 'colsample_bytree': 0.7479528512386471, 'n_estimators': 1000}. Best is trial 0 with value: 0.6395895618311335.

Running time: 0.6 sec
OOF RMSE: 2.31 | R2: 0.56
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 21:57:28,160] Trial 9 finished with value: 0.613380354891914 and parameters: {'learning_rate': 0.03173333072738567, 'num_leaves': 80, 'max_depth': 7, 'min_child_samples': 5, 'subsample': 0.8560896405015126, 'colsample_bytree': 0.9722830376884027, 'n_estimators': 1000}. Best is trial 0 with value: 0.6395895618311335.

Fold 5
Running time: 0.8 sec
OOF RMSE: 2.16 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:57:28,474] Trial 10 finished with value: 0.6174445583942256 and parameters: {'learning_rate': 0.018454731135318238, 'num_leaves': 60, 'max_depth': 5, 'min_child_samples': 6, 'subsample': 0.6226997285543648, 'colsample_bytree': 0.7975008334456584, 'n_estimators': 500}. Best is trial 0 with value: 0.6395895618311335.

Running time: 0.3 sec
OOF RMSE: 2.14 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 21:57:28,758] Trial 11 finished with value: 0.6282426255404796 and parameters: {'learning_rate': 0.04522755457724627, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 25, 'subsample': 0.6589753963602847, 'colsample_bytree': 0.864263164271462, 'n_estimators': 500}. Best is trial 0 with value: 0.6395895618311335.

Fold 5
Running time: 0.3 sec
OOF RMSE: 2.11 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 21:57:29,319] Trial 12 finished with value: 0.49822397080593417 and parameters: {'learning_rate': 0.05473837107621617, 'num_leaves': 60, 'max_depth': 6, 'min_child_samples': 10, 'subsample': 0.6932587869374394, 'colsample_bytree': 0.7527066121832507, 'n_estimators': 1000}. Best is trial 0 with value: 0.6395895618311335.

Fold 5
Running time: 0.6 sec
OOF RMSE: 2.46 | R2: 0.50
Fold 1
Fold 2

[I 2025-07-11 21:57:29,572] Trial 13 finished with value: 0.5555342416711375 and parameters: {'learning_rate': 0.014334553990816162, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 23, 'subsample': 0.6035317137376551, 'colsample_bytree': 0.8736283712752234, 'n_estimators': 500}. Best is trial 0 with value: 0.6395895618311335.

Fold 3
Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 2.31 | R2: 0.56
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:57:30,740] Trial 14 finished with value: 0.5288696235220903 and parameters: {'learning_rate': 0.0053179942662898985, 'num_leaves': 60, 'max_depth': 7, 'min_child_samples': 10, 'subsample': 0.7087299701894586, 'colsample_bytree': 0.804395911188495, 'n_estimators': 2000}. Best is trial 0 with value: 0.6395895618311335.

Running time: 1.2 sec
OOF RMSE: 2.38 | R2: 0.53
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:57:31,213] Trial 15 finished with value: 0.6184289360173263 and parameters: {'learning_rate': 0.029490494021575057, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 22, 'subsample': 0.6626754936309961, 'colsample_bytree': 0.7241304889436234, 'n_estimators': 1000}. Best is trial 0 with value: 0.6395895618311335.

Running time: 0.5 sec
OOF RMSE: 2.14 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 21:57:31,500] Trial 16 finished with value: 0.5625850983991068 and parameters: {'learning_rate': 0.05405632158155818, 'num_leaves': 60, 'max_depth': 5, 'min_child_samples': 12, 'subsample': 0.9997967523187761, 'colsample_bytree': 0.8124972360549941, 'n_estimators': 500}. Best is trial 0 with value: 0.6395895618311335.

Fold 5
Running time: 0.3 sec
OOF RMSE: 2.29 | R2: 0.56
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:57:32,279] Trial 17 finished with value: 0.51492870959634 and parameters: {'learning_rate': 0.013778317626316827, 'num_leaves': 80, 'max_depth': 8, 'min_child_samples': 8, 'subsample': 0.7493507635456478, 'colsample_bytree': 0.9131347965168226, 'n_estimators': 1000}. Best is trial 0 with value: 0.6395895618311335.

Running time: 0.8 sec
OOF RMSE: 2.41 | R2: 0.51
Fold 1
Fold 2
Fold 3

[I 2025-07-11 21:57:32,608] Trial 18 finished with value: 0.5952223243374191 and parameters: {'learning_rate': 0.029219255232133187, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 14, 'subsample': 0.6628743479475586, 'colsample_bytree': 0.8368640831709786, 'n_estimators': 500}. Best is trial 0 with value: 0.6395895618311335.

Fold 4
Fold 5
Running time: 0.3 sec
OOF RMSE: 2.21 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:57:33,544] Trial 19 finished with value: 0.6058988931358491 and parameters: {'learning_rate': 0.007271155852466739, 'num_leaves': 60, 'max_depth': 6, 'min_child_samples': 21, 'subsample': 0.8339279926555383, 'colsample_bytree': 0.7026330376815869, 'n_estimators': 2000}. Best is trial 0 with value: 0.6395895618311335.

Running time: 0.9 sec
OOF RMSE: 2.18 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 21:57:33,798] Trial 20 finished with value: 0.6255196069337836 and parameters: {'learning_rate': 0.0426048556364298, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 25, 'subsample': 0.7177896326183516, 'colsample_bytree': 0.7682298832567999, 'n_estimators': 500}. Best is trial 0 with value: 0.6395895618311335.

Fold 5
Running time: 0.2 sec
OOF RMSE: 2.12 | R2: 0.63
Fold 1
Fold 2
Fold 3

[I 2025-07-11 21:57:34,133] Trial 21 finished with value: 0.628367376072023 and parameters: {'learning_rate': 0.06464578149276634, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 25, 'subsample': 0.6524431619525047, 'colsample_bytree': 0.893971124075627, 'n_estimators': 500}. Best is trial 0 with value: 0.6395895618311335.

Fold 4
Fold 5
Running time: 0.3 sec
OOF RMSE: 2.11 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:57:34,449] Trial 22 finished with value: 0.6314062211722793 and parameters: {'learning_rate': 0.09969365680902988, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 24, 'subsample': 0.635522523836463, 'colsample_bytree': 0.9911934227123081, 'n_estimators': 500}. Best is trial 0 with value: 0.6395895618311335.

Running time: 0.3 sec
OOF RMSE: 2.10 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 21:57:34,732] Trial 23 finished with value: 0.6278014180574363 and parameters: {'learning_rate': 0.07676899056955107, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 23, 'subsample': 0.6275210957217721, 'colsample_bytree': 0.9857851815343674, 'n_estimators': 500}. Best is trial 0 with value: 0.6395895618311335.

Fold 5
Running time: 0.3 sec
OOF RMSE: 2.11 | R2: 0.63
Fold 1
Fold 2
Fold 3

[I 2025-07-11 21:57:35,027] Trial 24 finished with value: 0.6044738440752573 and parameters: {'learning_rate': 0.08998822765431556, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 21, 'subsample': 0.6902017799524083, 'colsample_bytree': 0.948029704841835, 'n_estimators': 500}. Best is trial 0 with value: 0.6395895618311335.
[I 2025-07-11 21:57:35,028] A new study created in memory with name: no-name-d6c61169-7fbd-4634-9aae-73a55cab8fa5

Fold 4
Fold 5
Running time: 0.3 sec
OOF RMSE: 2.18 | R2: 0.60

✅ LBM - Mejor R2: 0.64
📋 Parámetros: {'learning_rate': 0.008199932486200268, 'num_leaves': 60, 'max_depth': 5, 'min_child_samples': 5, 'subsample': 0.6782995047764365, 'colsample_bytree': 0.7802529124537346, 'n_estimators': 500}

Buscando mejores hiperparámetros para MLP...
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 21:57:37,355] Trial 0 finished with value: 0.41230407209794284 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.008571012527399289, 'learning_rate': 'constant', 'learning_rate_init': 0.00012021876289637282}. Best is trial 0 with value: 0.41230407209794284.

Running time: 2.3 sec
OOF RMSE: 2.66 | R2: 0.41
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 21:57:39,373] Trial 1 finished with value: 0.5930703434457204 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.043114539284797755, 'learning_rate': 'constant', 'learning_rate_init': 0.0007496794440820198}. Best is trial 1 with value: 0.5930703434457204.

Running time: 2.0 sec
OOF RMSE: 2.21 | R2: 0.59
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 21:57:41,235] Trial 2 finished with value: 0.4909655845012588 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.017814168708146224, 'learning_rate': 'constant', 'learning_rate_init': 0.00016913080175288162}. Best is trial 1 with value: 0.5930703434457204.

Running time: 1.9 sec
OOF RMSE: 2.47 | R2: 0.49
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

[I 2025-07-11 21:57:42,631] Trial 3 finished with value: 0.27165282969826454 and parameters: {'hidden_layer_sizes': '50', 'activation': 'tanh', 'solver': 'adam', 'alpha': 2.3905633119442014e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.00016426763807271012}. Best is trial 1 with value: 0.5930703434457204.

Running time: 1.4 sec
OOF RMSE: 2.96 | R2: 0.27
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 21:57:45,905] Trial 4 finished with value: 0.38383747956541425 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.00012290926296987806, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0004165261484211723}. Best is trial 1 with value: 0.5930703434457204.

Running time: 3.3 sec
OOF RMSE: 2.72 | R2: 0.38
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 21:57:47,048] Trial 5 finished with value: 0.45186136761024487 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 9.079936696913043e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00035525495795095006}. Best is trial 1 with value: 0.5930703434457204.

Fold 5
Running time: 1.1 sec
OOF RMSE: 2.57 | R2: 0.45
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

[I 2025-07-11 21:57:49,972] Trial 6 finished with value: 0.4767350114833603 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.0006553271504098899, 'learning_rate': 'adaptive', 'learning_rate_init': 0.009945042894277223}. Best is trial 1 with value: 0.5930703434457204.

Running time: 2.9 sec
OOF RMSE: 2.51 | R2: 0.48
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

[I 2025-07-11 21:57:52,351] Trial 7 finished with value: 0.3927575114705405 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.08066720453606448, 'learning_rate': 'constant', 'learning_rate_init': 0.0001470051717184171}. Best is trial 1 with value: 0.5930703434457204.

Running time: 2.4 sec
OOF RMSE: 2.70 | R2: 0.39
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 21:57:53,028] Trial 8 finished with value: 0.3676675108872214 and parameters: {'hidden_layer_sizes': '50', 'activation': 'tanh', 'solver': 'adam', 'alpha': 1.1286093509124077e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.0036865635398669874}. Best is trial 1 with value: 0.5930703434457204.

Fold 4
Fold 5
Running time: 0.7 sec
OOF RMSE: 2.76 | R2: 0.37
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 21:57:53,769] Trial 9 finished with value: 0.3756319481534728 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.014079001138661142, 'learning_rate': 'constant', 'learning_rate_init': 0.0030191341709570013}. Best is trial 1 with value: 0.5930703434457204.

Fold 5
Running time: 0.7 sec
OOF RMSE: 2.74 | R2: 0.38
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 21:57:55,043] Trial 10 finished with value: 0.49687730026228816 and parameters: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.0018686276449975223, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0011702564044533455}. Best is trial 1 with value: 0.5930703434457204.

Running time: 1.3 sec
OOF RMSE: 2.46 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:57:56,184] Trial 11 finished with value: 0.494490784315213 and parameters: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.0012374463016177459, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0011038452607028508}. Best is trial 1 with value: 0.5930703434457204.

Running time: 1.1 sec
OOF RMSE: 2.46 | R2: 0.49
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

[I 2025-07-11 21:57:57,658] Trial 12 finished with value: 0.4917321051250897 and parameters: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.0019150617885882301, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0010128674396257709}. Best is trial 1 with value: 0.5930703434457204.

Running time: 1.5 sec
OOF RMSE: 2.47 | R2: 0.49
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:57:59,288] Trial 13 finished with value: 0.5041357412673992 and parameters: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.051726848958360175, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0019649926170074235}. Best is trial 1 with value: 0.5930703434457204.

Running time: 1.6 sec
OOF RMSE: 2.44 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 21:57:59,982] Trial 14 finished with value: 0.4896443805435552 and parameters: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.0959743687894373, 'learning_rate': 'constant', 'learning_rate_init': 0.002545391854003493}. Best is trial 1 with value: 0.5930703434457204.

Fold 5
Running time: 0.7 sec
OOF RMSE: 2.48 | R2: 0.49
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

[I 2025-07-11 21:58:01,427] Trial 15 finished with value: 0.49079821438208837 and parameters: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.03185181065626853, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0005724086958007219}. Best is trial 1 with value: 0.5930703434457204.

Running time: 1.4 sec
OOF RMSE: 2.47 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:58:02,221] Trial 16 finished with value: 0.4154403671945629 and parameters: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.005238259415770903, 'learning_rate': 'adaptive', 'learning_rate_init': 0.002351311159067654}. Best is trial 1 with value: 0.5930703434457204.

Running time: 0.8 sec
OOF RMSE: 2.65 | R2: 0.42
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 21:58:03,782] Trial 17 finished with value: 0.5750428585657883 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.037713115693071585, 'learning_rate': 'constant', 'learning_rate_init': 0.004964272637503516}. Best is trial 1 with value: 0.5930703434457204.

Running time: 1.6 sec
OOF RMSE: 2.26 | R2: 0.58
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:58:04,974] Trial 18 finished with value: 0.559126207825521 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.0046049131833603325, 'learning_rate': 'constant', 'learning_rate_init': 0.007849629087606282}. Best is trial 1 with value: 0.5930703434457204.

Running time: 1.2 sec
OOF RMSE: 2.30 | R2: 0.56
Fold 1
Fold 2
Fold 3

[I 2025-07-11 21:58:05,724] Trial 19 finished with value: 0.3777901882820379 and parameters: {'hidden_layer_sizes': '50', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.00030681522785092573, 'learning_rate': 'constant', 'learning_rate_init': 0.005761243345690812}. Best is trial 1 with value: 0.5930703434457204.

Fold 4
Fold 5
Running time: 0.7 sec
OOF RMSE: 2.73 | R2: 0.38
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 21:58:07,546] Trial 20 finished with value: 0.5924898715013931 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.027303993410814565, 'learning_rate': 'constant', 'learning_rate_init': 0.0015885729684341882}. Best is trial 1 with value: 0.5930703434457204.

Running time: 1.8 sec
OOF RMSE: 2.21 | R2: 0.59
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 21:58:09,405] Trial 21 finished with value: 0.5920142560689754 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.019752758366226406, 'learning_rate': 'constant', 'learning_rate_init': 0.001575161132047754}. Best is trial 1 with value: 0.5930703434457204.

Running time: 1.9 sec
OOF RMSE: 2.21 | R2: 0.59
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 21:58:11,047] Trial 22 finished with value: 0.5927154749559674 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.021900965923976907, 'learning_rate': 'constant', 'learning_rate_init': 0.00160507860530753}. Best is trial 1 with value: 0.5930703434457204.

Running time: 1.6 sec
OOF RMSE: 2.21 | R2: 0.59
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 21:58:13,079] Trial 23 finished with value: 0.583246110796162 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.004645954985713376, 'learning_rate': 'constant', 'learning_rate_init': 0.0006507549163017364}. Best is trial 1 with value: 0.5930703434457204.

Running time: 2.0 sec
OOF RMSE: 2.24 | R2: 0.58
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 21:58:15,249] Trial 24 finished with value: 0.5851836501413429 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.010692838733710618, 'learning_rate': 'constant', 'learning_rate_init': 0.0006717771268221678}. Best is trial 1 with value: 0.5930703434457204.
[I 2025-07-11 21:58:15,251] A new study created in memory with name: no-name-6c8e5d60-e48c-4033-b574-d6aea083e6ff
[I 2025-07-11 21:58:15,339] Trial 0 finished with value: 0.09698252370933835 and parameters: {'kernel': 'rbf', 'C': 0.1784544648922441, 'epsilon': 0.04669929379042263, 'gamma': 'auto'}. Best is trial 0 with value: 0.09698252370933835.
[I 2025-07-11 21:58:15,416] Trial 1 finished with value: -0.036743964692370845 and parameters: {'kernel': 'sigmoid', 'C': 0.3711614099312018, 'epsilon': 0.052628667520430904, 'gamma': 'auto'}. Best is trial 0 with value: 0.09698252370933835.

Running time: 2.2 sec
OOF RMSE: 2.23 | R2: 0.59

✅ MLP - Mejor R2: 0.59
📋 Parámetros: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.043114539284797755, 'learning_rate': 'constant', 'learning_rate_init': 0.0007496794440820198}

Buscando mejores hiperparámetros para SVR...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.29 | R2: 0.10
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.53 | R2: -0.04
Fold 1
Fold 2
Fold 3

[I 2025-07-11 21:58:15,486] Trial 2 finished with value: 0.34982877616034713 and parameters: {'kernel': 'rbf', 'C': 1.956848813297068, 'epsilon': 0.05647093561047896, 'gamma': 'scale'}. Best is trial 2 with value: 0.34982877616034713.
[I 2025-07-11 21:58:15,555] Trial 3 finished with value: 0.09345602919387519 and parameters: {'kernel': 'sigmoid', 'C': 0.1552715132402659, 'epsilon': 0.10197131871165313, 'gamma': 'auto'}. Best is trial 2 with value: 0.34982877616034713.
[I 2025-07-11 21:58:15,629] Trial 4 finished with value: 0.05243545378879566 and parameters: {'kernel': 'sigmoid', 'C': 0.19515802084266615, 'epsilon': 0.0515136545962831, 'gamma': 'scale'}. Best is trial 2 with value: 0.34982877616034713.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.80 | R2: 0.35
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.30 | R2: 0.09
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.37 | R2: 0.05
Fold 1
Fold 2
Fold 3

[I 2025-07-11 21:58:15,702] Trial 5 finished with value: 0.41868832439923176 and parameters: {'kernel': 'rbf', 'C': 3.175205053292737, 'epsilon': 0.1596247984007417, 'gamma': 'auto'}. Best is trial 5 with value: 0.41868832439923176.
[I 2025-07-11 21:58:15,777] Trial 6 finished with value: 0.2664914742365062 and parameters: {'kernel': 'rbf', 'C': 0.8445719502349923, 'epsilon': 0.11346918300688187, 'gamma': 'auto'}. Best is trial 5 with value: 0.41868832439923176.
[I 2025-07-11 21:58:15,849] Trial 7 finished with value: 0.09557690230782734 and parameters: {'kernel': 'sigmoid', 'C': 0.27165182570745394, 'epsilon': 0.17630821964907611, 'gamma': 'auto'}. Best is trial 5 with value: 0.41868832439923176.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.64 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.97 | R2: 0.27
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.30 | R2: 0.10
Fold 1
Fold 2

[I 2025-07-11 21:58:15,925] Trial 8 finished with value: -235.82992355516913 and parameters: {'kernel': 'sigmoid', 'C': 9.252666443872306, 'epsilon': 0.10145426175376426, 'gamma': 'scale'}. Best is trial 5 with value: 0.41868832439923176.
[I 2025-07-11 21:58:15,997] Trial 9 finished with value: 0.08561133017610412 and parameters: {'kernel': 'sigmoid', 'C': 0.12688305389982188, 'epsilon': 0.06452431727431077, 'gamma': 'auto'}. Best is trial 5 with value: 0.41868832439923176.
[I 2025-07-11 21:58:16,079] Trial 10 finished with value: 0.5409817699723798 and parameters: {'kernel': 'rbf', 'C': 5.801453312034185, 'epsilon': 0.19048635292645452, 'gamma': 'scale'}. Best is trial 10 with value: 0.5409817699723798.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 53.35 | R2: -235.83
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.31 | R2: 0.09
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.35 | R2: 0.54

[I 2025-07-11 21:58:16,162] Trial 11 finished with value: 0.5356409084363559 and parameters: {'kernel': 'rbf', 'C': 5.617000723955875, 'epsilon': 0.19775785860172967, 'gamma': 'scale'}. Best is trial 10 with value: 0.5409817699723798.
[I 2025-07-11 21:58:16,249] Trial 12 finished with value: 0.6097029819459256 and parameters: {'kernel': 'rbf', 'C': 9.00521497241115, 'epsilon': 0.19900631414722061, 'gamma': 'scale'}. Best is trial 12 with value: 0.6097029819459256.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.36 | R2: 0.54
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.17 | R2: 0.61
Fold 1
Fold 2
Fold 3

[I 2025-07-11 21:58:16,332] Trial 13 finished with value: 0.5666222228675087 and parameters: {'kernel': 'rbf', 'C': 6.737479875939576, 'epsilon': 0.1557472168913083, 'gamma': 'scale'}. Best is trial 12 with value: 0.6097029819459256.
[I 2025-07-11 21:58:16,413] Trial 14 finished with value: 0.3490679504836284 and parameters: {'kernel': 'rbf', 'C': 1.887913751257227, 'epsilon': 0.1534526160815647, 'gamma': 'scale'}. Best is trial 12 with value: 0.6097029819459256.
[I 2025-07-11 21:58:16,500] Trial 15 finished with value: 0.6213478358769532 and parameters: {'kernel': 'rbf', 'C': 9.786698910975767, 'epsilon': 0.13488366341421093, 'gamma': 'scale'}. Best is trial 15 with value: 0.6213478358769532.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.28 | R2: 0.57
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.80 | R2: 0.35
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.13 | R2: 0.62

[I 2025-07-11 21:58:16,602] Trial 16 finished with value: 0.4401705202720978 and parameters: {'kernel': 'rbf', 'C': 3.420511914092891, 'epsilon': 0.12802673833110279, 'gamma': 'scale'}. Best is trial 15 with value: 0.6213478358769532.
[I 2025-07-11 21:58:16,686] Trial 17 finished with value: 0.23443612576833406 and parameters: {'kernel': 'rbf', 'C': 0.67450206655704, 'epsilon': 0.1313770817724093, 'gamma': 'scale'}. Best is trial 15 with value: 0.6213478358769532.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.59 | R2: 0.44
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.03 | R2: 0.23
Fold 1
Fold 2

[I 2025-07-11 21:58:16,778] Trial 18 finished with value: 0.6015868212502333 and parameters: {'kernel': 'rbf', 'C': 8.873987188134013, 'epsilon': 0.023632062173095922, 'gamma': 'scale'}. Best is trial 15 with value: 0.6213478358769532.
[I 2025-07-11 21:58:16,865] Trial 19 finished with value: 0.45897827400322544 and parameters: {'kernel': 'rbf', 'C': 3.715853411737673, 'epsilon': 0.08742493953793867, 'gamma': 'scale'}. Best is trial 15 with value: 0.6213478358769532.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.19 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.55 | R2: 0.46
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:58:16,945] Trial 20 finished with value: 0.3219577670500273 and parameters: {'kernel': 'rbf', 'C': 1.51006934434427, 'epsilon': 0.17023706539350858, 'gamma': 'scale'}. Best is trial 15 with value: 0.6213478358769532.
[I 2025-07-11 21:58:17,040] Trial 21 finished with value: 0.6082012286518954 and parameters: {'kernel': 'rbf', 'C': 9.327773668549636, 'epsilon': 0.011836115263245078, 'gamma': 'scale'}. Best is trial 15 with value: 0.6213478358769532.
[I 2025-07-11 21:58:17,135] Trial 22 finished with value: 0.6158259558462579 and parameters: {'kernel': 'rbf', 'C': 9.892037345305374, 'epsilon': 0.012265961173814234, 'gamma': 'scale'}. Best is trial 15 with value: 0.6213478358769532.

Running time: 0.1 sec
OOF RMSE: 2.85 | R2: 0.32
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.17 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.15 | R2: 0.62

[I 2025-07-11 21:58:17,217] Trial 23 finished with value: 0.506630711243802 and parameters: {'kernel': 'rbf', 'C': 4.696662342432921, 'epsilon': 0.07598135745805538, 'gamma': 'scale'}. Best is trial 15 with value: 0.6213478358769532.
[I 2025-07-11 21:58:17,300] Trial 24 finished with value: 0.377100138653896 and parameters: {'kernel': 'rbf', 'C': 2.3961611473736784, 'epsilon': 0.13661357638843288, 'gamma': 'scale'}. Best is trial 15 with value: 0.6213478358769532.
[I 2025-07-11 21:58:17,301] A new study created in memory with name: no-name-0c0a32f1-1400-4640-914f-7887b8508ccc

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.43 | R2: 0.51
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.74 | R2: 0.38

✅ SVR - Mejor R2: 0.62
📋 Parámetros: {'kernel': 'rbf', 'C': 9.786698910975767, 'epsilon': 0.13488366341421093, 'gamma': 'scale'}

Buscando mejores hiperparámetros para KNN...
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 21:58:17,368] Trial 0 finished with value: 0.6277273353815896 and parameters: {'n_neighbors': 15, 'weights': 'distance', 'leaf_size': 29}. Best is trial 0 with value: 0.6277273353815896.
[I 2025-07-11 21:58:17,433] Trial 1 finished with value: 0.6896027027504293 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 33}. Best is trial 1 with value: 0.6896027027504293.
[I 2025-07-11 21:58:17,499] Trial 2 finished with value: 0.670822780902858 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'leaf_size': 32}. Best is trial 1 with value: 0.6896027027504293.

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.12 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.93 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.99 | R2: 0.67
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:58:17,566] Trial 3 finished with value: 0.6324190263213199 and parameters: {'n_neighbors': 12, 'weights': 'distance', 'leaf_size': 31}. Best is trial 1 with value: 0.6896027027504293.
[I 2025-07-11 21:58:17,635] Trial 4 finished with value: 0.6248674404847827 and parameters: {'n_neighbors': 13, 'weights': 'distance', 'leaf_size': 28}. Best is trial 1 with value: 0.6896027027504293.
[I 2025-07-11 21:58:17,700] Trial 5 finished with value: 0.6960814070224213 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'leaf_size': 23}. Best is trial 5 with value: 0.6960814070224213.
[I 2025-07-11 21:58:17,758] Trial 6 finished with value: 0.5351902854162292 and parameters: {'n_neighbors': 14, 'weights': 'uniform', 'leaf_size': 34}. Best is trial 5 with value: 0.6960814070224213.

Running time: 0.1 sec
OOF RMSE: 2.10 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.12 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.91 | R2: 0.70
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.36 | R2: 0.54
Fold 1

[I 2025-07-11 21:58:17,822] Trial 7 finished with value: 0.5351902854162292 and parameters: {'n_neighbors': 14, 'weights': 'uniform', 'leaf_size': 17}. Best is trial 5 with value: 0.6960814070224213.
[I 2025-07-11 21:58:17,887] Trial 8 finished with value: 0.6877674001088228 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'leaf_size': 10}. Best is trial 5 with value: 0.6960814070224213.
[I 2025-07-11 21:58:17,954] Trial 9 finished with value: 0.5745335578574695 and parameters: {'n_neighbors': 9, 'weights': 'uniform', 'leaf_size': 18}. Best is trial 5 with value: 0.6960814070224213.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.36 | R2: 0.54
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.94 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.26 | R2: 0.57
Fold 1

[I 2025-07-11 21:58:18,031] Trial 10 finished with value: 0.6960814070224213 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'leaf_size': 40}. Best is trial 5 with value: 0.6960814070224213.
[I 2025-07-11 21:58:18,109] Trial 11 finished with value: 0.6960814070224213 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'leaf_size': 40}. Best is trial 5 with value: 0.6960814070224213.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.91 | R2: 0.70
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.91 | R2: 0.70
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:58:18,184] Trial 12 finished with value: 0.6960814070224213 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'leaf_size': 22}. Best is trial 5 with value: 0.6960814070224213.
[I 2025-07-11 21:58:18,259] Trial 13 finished with value: 0.671629554604367 and parameters: {'n_neighbors': 8, 'weights': 'distance', 'leaf_size': 39}. Best is trial 5 with value: 0.6960814070224213.
[I 2025-07-11 21:58:18,333] Trial 14 finished with value: 0.6760434956603028 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'leaf_size': 23}. Best is trial 5 with value: 0.6960814070224213.

Running time: 0.1 sec
OOF RMSE: 1.91 | R2: 0.70
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.99 | R2: 0.67
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.97 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 21:58:18,404] Trial 15 finished with value: 0.6450512279610654 and parameters: {'n_neighbors': 11, 'weights': 'distance', 'leaf_size': 19}. Best is trial 5 with value: 0.6960814070224213.
[I 2025-07-11 21:58:18,473] Trial 16 finished with value: 0.6760434956603028 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'leaf_size': 13}. Best is trial 5 with value: 0.6960814070224213.
[I 2025-07-11 21:58:18,549] Trial 17 finished with value: 0.6507101967905125 and parameters: {'n_neighbors': 10, 'weights': 'distance', 'leaf_size': 26}. Best is trial 5 with value: 0.6960814070224213.

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.07 | R2: 0.65
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.97 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.05 | R2: 0.65
Fold 1
Fold 2
Fold 3

[I 2025-07-11 21:58:18,621] Trial 18 finished with value: 0.6057749816380644 and parameters: {'n_neighbors': 8, 'weights': 'uniform', 'leaf_size': 36}. Best is trial 5 with value: 0.6960814070224213.
[I 2025-07-11 21:58:18,694] Trial 19 finished with value: 0.661105280262333 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'leaf_size': 24}. Best is trial 5 with value: 0.6960814070224213.
[I 2025-07-11 21:58:18,768] Trial 20 finished with value: 0.6877674001088228 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'leaf_size': 21}. Best is trial 5 with value: 0.6960814070224213.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.18 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.02 | R2: 0.66
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.94 | R2: 0.69
Fold 1
Fold 2

[I 2025-07-11 21:58:18,842] Trial 21 finished with value: 0.6960814070224213 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'leaf_size': 40}. Best is trial 5 with value: 0.6960814070224213.
[I 2025-07-11 21:58:18,919] Trial 22 finished with value: 0.6760434956603028 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'leaf_size': 39}. Best is trial 5 with value: 0.6960814070224213.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.91 | R2: 0.70
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.97 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 21:58:19,025] Trial 23 finished with value: 0.6877674001088228 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'leaf_size': 37}. Best is trial 5 with value: 0.6960814070224213.
[I 2025-07-11 21:58:19,103] Trial 24 finished with value: 0.6545342154323839 and parameters: {'n_neighbors': 9, 'weights': 'distance', 'leaf_size': 36}. Best is trial 5 with value: 0.6960814070224213.
[I 2025-07-11 21:58:19,104] A new study created in memory with name: no-name-d20fb14e-6a18-431c-b8a3-b60d5fb5e34d
[I 2025-07-11 21:58:19,167] Trial 0 finished with value: -0.08997545706945709 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: -0.08997545706945709.

Fold 5
Running time: 0.1 sec
OOF RMSE: 1.94 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.04 | R2: 0.65

✅ KNN - Mejor R2: 0.70
📋 Parámetros: {'n_neighbors': 6, 'weights': 'distance', 'leaf_size': 23}

Buscando mejores hiperparámetros para LR...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.62 | R2: -0.09
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 21:58:19,253] Trial 1 finished with value: -0.29196803657192505 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 0 with value: -0.08997545706945709.
[I 2025-07-11 21:58:19,332] Trial 2 finished with value: -0.09002504507318165 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 0 with value: -0.08997545706945709.

Fold 5
Running time: 0.1 sec
OOF RMSE: 3.94 | R2: -0.29
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.62 | R2: -0.09
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:58:19,470] Trial 3 finished with value: -0.29196803657192505 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 0 with value: -0.08997545706945709.
[I 2025-07-11 21:58:19,559] Trial 4 finished with value: -0.29196803657183623 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 0 with value: -0.08997545706945709.
[I 2025-07-11 21:58:19,642] Trial 5 finished with value: -0.09002504507318165 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 0 with value: -0.08997545706945709.

Running time: 0.1 sec
OOF RMSE: 3.94 | R2: -0.29
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.94 | R2: -0.29
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.62 | R2: -0.09
Fold 1
Fold 2

[I 2025-07-11 21:58:19,707] Trial 6 finished with value: -0.09002504507318165 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 0 with value: -0.08997545706945709.
[I 2025-07-11 21:58:19,769] Trial 7 finished with value: -0.09002504507318165 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 0 with value: -0.08997545706945709.
[I 2025-07-11 21:58:19,833] Trial 8 finished with value: -0.09002504507318165 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 0 with value: -0.08997545706945709.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.62 | R2: -0.09
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.62 | R2: -0.09
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.62 | R2: -0.09
Fold 1
Fold 2
Fold 3

[I 2025-07-11 21:58:19,927] Trial 9 finished with value: -0.29196803657192505 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 0 with value: -0.08997545706945709.
[I 2025-07-11 21:58:20,010] Trial 10 finished with value: -0.08997545706945709 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: -0.08997545706945709.
[I 2025-07-11 21:58:20,074] Trial 11 finished with value: -0.08997545706945709 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: -0.08997545706945709.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.94 | R2: -0.29
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.62 | R2: -0.09
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.62 | R2: -0.09
Fold 1

[I 2025-07-11 21:58:20,139] Trial 12 finished with value: -0.08997545706945709 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: -0.08997545706945709.
[I 2025-07-11 21:58:20,203] Trial 13 finished with value: -0.08997545706945709 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: -0.08997545706945709.
[I 2025-07-11 21:58:20,265] Trial 14 finished with value: -0.08997545706945709 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: -0.08997545706945709.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.62 | R2: -0.09
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.62 | R2: -0.09
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.62 | R2: -0.09
Fold 1
Fold 2
Fold 3

[I 2025-07-11 21:58:20,331] Trial 15 finished with value: -0.08997545706945709 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: -0.08997545706945709.
[I 2025-07-11 21:58:20,408] Trial 16 finished with value: -0.08997545706945709 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: -0.08997545706945709.
[I 2025-07-11 21:58:20,476] Trial 17 finished with value: -0.08997545706945709 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: -0.08997545706945709.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.62 | R2: -0.09
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.62 | R2: -0.09
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.62 | R2: -0.09
Fold 1
Fold 2
Fold 3

[I 2025-07-11 21:58:20,574] Trial 18 finished with value: -0.29196803657183623 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 0 with value: -0.08997545706945709.
[I 2025-07-11 21:58:20,652] Trial 19 finished with value: -0.08997545706945709 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: -0.08997545706945709.
[I 2025-07-11 21:58:20,722] Trial 20 finished with value: -0.08997545706945709 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: -0.08997545706945709.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.94 | R2: -0.29
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.62 | R2: -0.09
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.62 | R2: -0.09

[I 2025-07-11 21:58:20,788] Trial 21 finished with value: -0.08997545706945709 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: -0.08997545706945709.
[I 2025-07-11 21:58:20,854] Trial 22 finished with value: -0.08997545706945709 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: -0.08997545706945709.
[I 2025-07-11 21:58:20,920] Trial 23 finished with value: -0.08997545706945709 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: -0.08997545706945709.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.62 | R2: -0.09
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.62 | R2: -0.09
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.62 | R2: -0.09
Fold 1

[I 2025-07-11 21:58:20,986] Trial 24 finished with value: -0.08997545706945709 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: -0.08997545706945709.
[I 2025-07-11 21:58:20,987] A new study created in memory with name: no-name-f3a3ac06-7824-49da-a7d8-58037cce5b88

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.62 | R2: -0.09

✅ LR - Mejor R2: -0.09
📋 Parámetros: {'fit_intercept': True, 'positive': True}

Buscando mejores hiperparámetros para RF...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:58:23,518] Trial 0 finished with value: 0.4205086507033122 and parameters: {'n_estimators': 100, 'max_depth': 10, 'min_samples_split': 4, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 0 with value: 0.4205086507033122.

Running time: 2.5 sec
OOF RMSE: 2.64 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:58:33,269] Trial 1 finished with value: 0.5338050147533437 and parameters: {'n_estimators': 500, 'max_depth': 11, 'min_samples_split': 4, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 1 with value: 0.5338050147533437.

Running time: 9.7 sec
OOF RMSE: 2.37 | R2: 0.53
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:58:37,618] Trial 2 finished with value: 0.4800327504188645 and parameters: {'n_estimators': 300, 'max_depth': 12, 'min_samples_split': 5, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 1 with value: 0.5338050147533437.

Running time: 4.3 sec
OOF RMSE: 2.50 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:58:48,336] Trial 3 finished with value: 0.368120394980732 and parameters: {'n_estimators': 500, 'max_depth': 6, 'min_samples_split': 2, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 1 with value: 0.5338050147533437.

Running time: 10.7 sec
OOF RMSE: 2.76 | R2: 0.37
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:58:55,383] Trial 4 finished with value: 0.38647323646635334 and parameters: {'n_estimators': 300, 'max_depth': 8, 'min_samples_split': 9, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 1 with value: 0.5338050147533437.

Running time: 7.0 sec
OOF RMSE: 2.72 | R2: 0.39
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:59:00,648] Trial 5 finished with value: 0.5705744332319435 and parameters: {'n_estimators': 300, 'max_depth': 5, 'min_samples_split': 5, 'min_samples_leaf': 4, 'bootstrap': False}. Best is trial 5 with value: 0.5705744332319435.

Running time: 5.3 sec
OOF RMSE: 2.27 | R2: 0.57
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:59:09,077] Trial 6 finished with value: 0.4081690862616092 and parameters: {'n_estimators': 300, 'max_depth': 12, 'min_samples_split': 7, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 5 with value: 0.5705744332319435.

Running time: 8.4 sec
OOF RMSE: 2.67 | R2: 0.41
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:59:11,973] Trial 7 finished with value: 0.4066312107444844 and parameters: {'n_estimators': 100, 'max_depth': 15, 'min_samples_split': 6, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 5 with value: 0.5705744332319435.

Running time: 2.9 sec
OOF RMSE: 2.67 | R2: 0.41
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:59:13,466] Trial 8 finished with value: 0.5024235876962402 and parameters: {'n_estimators': 100, 'max_depth': 6, 'min_samples_split': 3, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 5 with value: 0.5705744332319435.

Running time: 1.5 sec
OOF RMSE: 2.45 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:59:18,393] Trial 9 finished with value: 0.4993755756382521 and parameters: {'n_estimators': 300, 'max_depth': 11, 'min_samples_split': 3, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 5 with value: 0.5705744332319435.

Running time: 4.9 sec
OOF RMSE: 2.45 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:59:23,590] Trial 10 finished with value: 0.3981305288554071 and parameters: {'n_estimators': 300, 'max_depth': 5, 'min_samples_split': 10, 'min_samples_leaf': 5, 'bootstrap': False}. Best is trial 5 with value: 0.5705744332319435.

Running time: 5.2 sec
OOF RMSE: 2.69 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:59:31,251] Trial 11 finished with value: 0.4838594451860463 and parameters: {'n_estimators': 500, 'max_depth': 9, 'min_samples_split': 7, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 5 with value: 0.5705744332319435.

Running time: 7.7 sec
OOF RMSE: 2.49 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:59:39,010] Trial 12 finished with value: 0.48341846390060905 and parameters: {'n_estimators': 500, 'max_depth': 14, 'min_samples_split': 5, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 5 with value: 0.5705744332319435.

Running time: 7.8 sec
OOF RMSE: 2.49 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:59:46,527] Trial 13 finished with value: 0.4846391881197394 and parameters: {'n_estimators': 500, 'max_depth': 8, 'min_samples_split': 5, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 5 with value: 0.5705744332319435.

Running time: 7.5 sec
OOF RMSE: 2.49 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 21:59:59,887] Trial 14 finished with value: 0.4125920003790692 and parameters: {'n_estimators': 500, 'max_depth': 13, 'min_samples_split': 7, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 5 with value: 0.5705744332319435.

Running time: 13.4 sec
OOF RMSE: 2.66 | R2: 0.41
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:00:04,480] Trial 15 finished with value: 0.48454801572094564 and parameters: {'n_estimators': 300, 'max_depth': 10, 'min_samples_split': 2, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 5 with value: 0.5705744332319435.

Running time: 4.6 sec
OOF RMSE: 2.49 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:00:15,380] Trial 16 finished with value: 0.4252616048794876 and parameters: {'n_estimators': 500, 'max_depth': 7, 'min_samples_split': 4, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 5 with value: 0.5705744332319435.

Running time: 10.9 sec
OOF RMSE: 2.63 | R2: 0.43
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:00:24,170] Trial 17 finished with value: 0.5149692348065615 and parameters: {'n_estimators': 500, 'max_depth': 11, 'min_samples_split': 6, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 5 with value: 0.5705744332319435.

Running time: 8.8 sec
OOF RMSE: 2.41 | R2: 0.51
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:00:29,485] Trial 18 finished with value: 0.4212538885504855 and parameters: {'n_estimators': 300, 'max_depth': 5, 'min_samples_split': 4, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 5 with value: 0.5705744332319435.

Running time: 5.3 sec
OOF RMSE: 2.64 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:00:30,958] Trial 19 finished with value: 0.47454296372516436 and parameters: {'n_estimators': 100, 'max_depth': 9, 'min_samples_split': 8, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 5 with value: 0.5705744332319435.

Running time: 1.5 sec
OOF RMSE: 2.51 | R2: 0.47
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:00:38,750] Trial 20 finished with value: 0.4833977261090535 and parameters: {'n_estimators': 500, 'max_depth': 12, 'min_samples_split': 3, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 5 with value: 0.5705744332319435.

Running time: 7.8 sec
OOF RMSE: 2.49 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:00:47,410] Trial 21 finished with value: 0.5137290460164072 and parameters: {'n_estimators': 500, 'max_depth': 10, 'min_samples_split': 6, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 5 with value: 0.5705744332319435.

Running time: 8.7 sec
OOF RMSE: 2.42 | R2: 0.51
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:00:56,872] Trial 22 finished with value: 0.5255442049383614 and parameters: {'n_estimators': 500, 'max_depth': 11, 'min_samples_split': 5, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 5 with value: 0.5705744332319435.

Running time: 9.5 sec
OOF RMSE: 2.39 | R2: 0.53
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:01:06,502] Trial 23 finished with value: 0.5280423589263536 and parameters: {'n_estimators': 500, 'max_depth': 13, 'min_samples_split': 5, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 5 with value: 0.5705744332319435.

Running time: 9.6 sec
OOF RMSE: 2.38 | R2: 0.53
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:01:16,389] Trial 24 finished with value: 0.5322471617163882 and parameters: {'n_estimators': 500, 'max_depth': 14, 'min_samples_split': 4, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 5 with value: 0.5705744332319435.
[I 2025-07-11 22:01:16,390] A new study created in memory with name: no-name-2dc40b0b-7a0c-436d-b4e1-642b04148ac9

Running time: 9.9 sec
OOF RMSE: 2.37 | R2: 0.53

✅ RF - Mejor R2: 0.57
📋 Parámetros: {'n_estimators': 300, 'max_depth': 5, 'min_samples_split': 5, 'min_samples_leaf': 4, 'bootstrap': False}

Buscando mejores hiperparámetros para CAT...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:04:10,806] Trial 0 finished with value: 0.7063110368880988 and parameters: {'iterations': 2000, 'learning_rate': 0.0501505028007583, 'depth': 9, 'l2_leaf_reg': 5.225304076971158}. Best is trial 0 with value: 0.7063110368880988.

Running time: 174.4 sec
OOF RMSE: 1.88 | R2: 0.71
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:04:14,229] Trial 1 finished with value: 0.648794262530247 and parameters: {'iterations': 500, 'learning_rate': 0.01717444663924496, 'depth': 6, 'l2_leaf_reg': 7.344128071726823}. Best is trial 0 with value: 0.7063110368880988.

Running time: 3.4 sec
OOF RMSE: 2.05 | R2: 0.65
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:04:52,366] Trial 2 finished with value: 0.6691140388097108 and parameters: {'iterations': 1000, 'learning_rate': 0.08266271771263368, 'depth': 8, 'l2_leaf_reg': 7.514921764233125}. Best is trial 0 with value: 0.7063110368880988.

Running time: 38.1 sec
OOF RMSE: 1.99 | R2: 0.67
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:04:56,637] Trial 3 finished with value: 0.6899433345289274 and parameters: {'iterations': 1000, 'learning_rate': 0.014734111776015524, 'depth': 5, 'l2_leaf_reg': 2.3669828084367497}. Best is trial 0 with value: 0.7063110368880988.

Running time: 4.3 sec
OOF RMSE: 1.93 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:05:38,441] Trial 4 finished with value: 0.7000624818370025 and parameters: {'iterations': 500, 'learning_rate': 0.023898358176253916, 'depth': 9, 'l2_leaf_reg': 5.050303217032775}. Best is trial 0 with value: 0.7063110368880988.

Running time: 41.8 sec
OOF RMSE: 1.90 | R2: 0.70
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:05:51,771] Trial 5 finished with value: 0.6823214512241155 and parameters: {'iterations': 2000, 'learning_rate': 0.0687660592813478, 'depth': 6, 'l2_leaf_reg': 6.0412827432692735}. Best is trial 0 with value: 0.7063110368880988.

Running time: 13.3 sec
OOF RMSE: 1.95 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:05:59,219] Trial 6 finished with value: 0.6829049529464475 and parameters: {'iterations': 500, 'learning_rate': 0.05371335736499662, 'depth': 7, 'l2_leaf_reg': 7.528906389976387}. Best is trial 0 with value: 0.7063110368880988.

Running time: 7.4 sec
OOF RMSE: 1.95 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:06:00,770] Trial 7 finished with value: 0.6809094274931639 and parameters: {'iterations': 500, 'learning_rate': 0.01568438375041893, 'depth': 4, 'l2_leaf_reg': 2.228880070410047}. Best is trial 0 with value: 0.7063110368880988.

Running time: 1.5 sec
OOF RMSE: 1.96 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:07:28,058] Trial 8 finished with value: 0.6913241365450407 and parameters: {'iterations': 1000, 'learning_rate': 0.09193281071469238, 'depth': 9, 'l2_leaf_reg': 2.7253870011971086}. Best is trial 0 with value: 0.7063110368880988.

Running time: 87.3 sec
OOF RMSE: 1.93 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:07:29,617] Trial 9 finished with value: 0.6657986242840658 and parameters: {'iterations': 500, 'learning_rate': 0.03216386050559859, 'depth': 4, 'l2_leaf_reg': 6.642402675343168}. Best is trial 0 with value: 0.7063110368880988.

Running time: 1.6 sec
OOF RMSE: 2.00 | R2: 0.67
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:12:25,794] Trial 10 finished with value: 0.6691717343721477 and parameters: {'iterations': 2000, 'learning_rate': 0.040853350433015696, 'depth': 10, 'l2_leaf_reg': 9.820723381990751}. Best is trial 0 with value: 0.7063110368880988.
[I 2025-07-11 22:12:25,795] A new study created in memory with name: no-name-e9832fb9-899f-4b7b-8826-20c8f344bf14
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.179e+01, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.503e+01, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.752e+01, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.180e+01, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.636e+00, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 22:12:25,957] Trial 0 finished with value: 0.519087032041045 and parameters: {'alpha': 0.006494171925076222, 'l1_ratio': 0.5291387086270057}. Best is trial 0 with value: 0.519087032041045.

Running time: 296.2 sec
OOF RMSE: 1.99 | R2: 0.67

✅ CAT - Mejor R2: 0.71
📋 Parámetros: {'iterations': 2000, 'learning_rate': 0.0501505028007583, 'depth': 9, 'l2_leaf_reg': 5.225304076971158}

Buscando mejores hiperparámetros para EN...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 2.40 | R2: 0.52
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.053e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.498e+01, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.804e+01, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.446e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.015e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 22:12:26,141] Trial 1 finished with value: 0.2226500930377715 and parameters: {'alpha': 0.0016365359608718055, 'l1_ratio': 0.9467838242924485}. Best is trial 0 with value: 0.519087032041045.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.719e+01, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 3.06 | R2: 0.22
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.198e+01, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.964e+01, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.915e+01, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.446e+01, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 22:12:26,358] Trial 2 finished with value: 0.39295958054422353 and parameters: {'alpha': 0.00356532455198504, 'l1_ratio': 0.9836672245028779}. Best is trial 0 with value: 0.519087032041045.

Fold 3
Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 2.70 | R2: 0.39
Fold 1
Fold 2
Fold 3

[I 2025-07-11 22:12:26,537] Trial 3 finished with value: 0.5051558864159591 and parameters: {'alpha': 0.03775115024220522, 'l1_ratio': 0.5283867500072875}. Best is trial 0 with value: 0.519087032041045.

Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 2.44 | R2: 0.51
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 22:12:26,722] Trial 4 finished with value: 0.5120455724513746 and parameters: {'alpha': 0.1337642063059333, 'l1_ratio': 0.41797204927775744}. Best is trial 0 with value: 0.519087032041045.
[I 2025-07-11 22:12:26,812] Trial 5 finished with value: 0.5097392335705677 and parameters: {'alpha': 0.16661454599560654, 'l1_ratio': 0.542791693946832}. Best is trial 0 with value: 0.519087032041045.

Fold 5
Running time: 0.2 sec
OOF RMSE: 2.42 | R2: 0.51
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.43 | R2: 0.51
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 22:12:26,945] Trial 6 finished with value: 0.5166312375330622 and parameters: {'alpha': 0.18671819153999802, 'l1_ratio': 0.0033770278994245118}. Best is trial 0 with value: 0.519087032041045.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.726e+00, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.473e-01, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.823e+00, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.685e+00, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.619e+00, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 22:12:27,112] Trial 7 finished with value: 0.5032462585794693 and parameters: {'alpha': 0.019992092407004315, 'l1_ratio': 0.37077384702621363}. Best is trial 0 with value: 0.519087032041045.

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.41 | R2: 0.52
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 2.44 | R2: 0.50
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.068e+01, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.791e+01, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.962e+01, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.903e+01, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.237e+01, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 22:12:27,245] Trial 8 finished with value: 0.4045411174805392 and parameters: {'alpha': 0.0018900318454155222, 'l1_ratio': 0.5012656632962544}. Best is trial 0 with value: 0.519087032041045.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.67 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 22:12:27,376] Trial 9 finished with value: 0.5091762059745364 and parameters: {'alpha': 0.17717629742674293, 'l1_ratio': 0.4599938982568279}. Best is trial 0 with value: 0.519087032041045.
[I 2025-07-11 22:12:27,463] Trial 10 finished with value: -0.00027817151752640434 and parameters: {'alpha': 4.8769926318626, 'l1_ratio': 0.7642011578365628}. Best is trial 0 with value: 0.519087032041045.

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.43 | R2: 0.51
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.47 | R2: -0.00
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.472e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.036e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.274e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.599e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.061e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 22:12:27,671] Trial 11 finished with value: 0.080764803114307 and parameters: {'alpha': 0.00010404582777712664, 'l1_ratio': 0.04328338628714983}. Best is trial 0 with value: 0.519087032041045.

Fold 3
Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 3.32 | R2: 0.08
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:12:27,784] Trial 12 finished with value: 0.44584147894235016 and parameters: {'alpha': 2.9510587951556886, 'l1_ratio': 0.004055202229705877}. Best is trial 0 with value: 0.519087032041045.
[I 2025-07-11 22:12:27,892] Trial 13 finished with value: 0.47286625658045733 and parameters: {'alpha': 0.8109356809744723, 'l1_ratio': 0.2173779745920122}. Best is trial 0 with value: 0.519087032041045.

Running time: 0.1 sec
OOF RMSE: 2.58 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.52 | R2: 0.47
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.590e+00, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.968e-01, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.592e+00, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.860e-01, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.643e-01, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 22:12:28,018] Trial 14 finished with value: 0.5099841763379367 and parameters: {'alpha': 0.01229581632491089, 'l1_ratio': 0.7057312586445348}. Best is trial 0 with value: 0.519087032041045.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.402e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.967e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.233e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.556e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.081e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 22:12:28,160] Trial 15 finished with value: 0.14178127779116023 and parameters: {'alpha': 0.0002675853981466115, 'l1_ratio': 0.19978528535840234}. Best is trial 0 with value: 0.519087032041045.

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.43 | R2: 0.51
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.21 | R2: 0.14
Fold 1
Fold 2

[I 2025-07-11 22:12:28,264] Trial 16 finished with value: 0.4642619005849479 and parameters: {'alpha': 0.6866563884270823, 'l1_ratio': 0.667102412827488}. Best is trial 0 with value: 0.519087032041045.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.260e+01, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.101e+01, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.155e+01, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.990e+01, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.004e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 22:12:28,392] Trial 17 finished with value: 0.5133847030669008 and parameters: {'alpha': 0.006845503917652183, 'l1_ratio': 0.24738123403891488}. Best is trial 0 with value: 0.519087032041045.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.54 | R2: 0.46
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.42 | R2: 0.51
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.268e+00, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.802e-01, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.912e-01, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.232e-01, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.132e+00, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 22:12:28,532] Trial 18 finished with value: 0.5070209212331007 and parameters: {'alpha': 0.050857171323217945, 'l1_ratio': 0.11977772949918977}. Best is trial 0 with value: 0.519087032041045.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.469e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.392e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.657e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.43 | R2: 0.51
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.064e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.672e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 22:12:28,675] Trial 19 finished with value: 0.2957216917391958 and parameters: {'alpha': 0.0009392618573995213, 'l1_ratio': 0.3415671612340455}. Best is trial 0 with value: 0.519087032041045.
[I 2025-07-11 22:12:28,790] Trial 20 finished with value: 0.4104586830511081 and parameters: {'alpha': 0.9369408711667184, 'l1_ratio': 0.7849887201764253}. Best is trial 0 with value: 0.519087032041045.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.143e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.91 | R2: 0.30
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.66 | R2: 0.41
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.438e+01, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.245e+01, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.465e+01, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.478e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 22:12:28,949] Trial 21 finished with value: 0.5125721532243714 and parameters: {'alpha': 0.006701048102063542, 'l1_ratio': 0.21785604165487935}. Best is trial 0 with value: 0.519087032041045.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.583e+01, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.800e+01, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.260e+01, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(

Fold 3
Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 2.42 | R2: 0.51
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.190e+01, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.703e+01, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 22:12:29,116] Trial 22 finished with value: 0.5124165219011286 and parameters: {'alpha': 0.0076480811508591725, 'l1_ratio': 0.3024001420557376}. Best is trial 0 with value: 0.519087032041045.

Fold 5
Running time: 0.2 sec
OOF RMSE: 2.42 | R2: 0.51
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:12:29,297] Trial 23 finished with value: 0.5107730315329069 and parameters: {'alpha': 0.07951648783467469, 'l1_ratio': 0.12594794704577883}. Best is trial 0 with value: 0.519087032041045.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.950e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.416e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.865e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.106e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.700e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 22:12:29,430] Trial 24 finished with value: 0.1450015577500292 and parameters: {'alpha': 0.00048043926932955577, 'l1_ratio': 0.5919681107079084}. Best is trial 0 with value: 0.519087032041045.
[I 2025-07-11 22:12:29,432] A new study created in memory with name: no-name-a9ccce5e-72df-4d8c-80e4-c2f3009406ec

Running time: 0.2 sec
OOF RMSE: 2.42 | R2: 0.51
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.21 | R2: 0.15

✅ EN - Mejor R2: 0.52
📋 Parámetros: {'alpha': 0.006494171925076222, 'l1_ratio': 0.5291387086270057}

🔍 Optimizando en C2X-Complex_rhow_9x9_depth_lt_1...
Buscando mejores hiperparámetros para XGB...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:12:35,716] Trial 0 finished with value: 0.6321183684766986 and parameters: {'n_estimators': 1000, 'learning_rate': 0.028673848392531003, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.6255431232072456, 'colsample_bytree': 0.9606839470443793}. Best is trial 0 with value: 0.6321183684766986.

Running time: 6.3 sec
OOF RMSE: 2.10 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:12:39,053] Trial 1 finished with value: 0.6430927153215674 and parameters: {'n_estimators': 500, 'learning_rate': 0.010461011104628182, 'max_depth': 8, 'min_child_weight': 4, 'subsample': 0.9977996979396417, 'colsample_bytree': 0.7278772491322666}. Best is trial 1 with value: 0.6430927153215674.

Running time: 3.3 sec
OOF RMSE: 2.07 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:12:41,426] Trial 2 finished with value: 0.6871682774529111 and parameters: {'n_estimators': 500, 'learning_rate': 0.013670627053169848, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.8154528128814046, 'colsample_bytree': 0.6388942346164125}. Best is trial 2 with value: 0.6871682774529111.

Running time: 2.4 sec
OOF RMSE: 1.94 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:12:48,917] Trial 3 finished with value: 0.7024219747885774 and parameters: {'n_estimators': 2000, 'learning_rate': 0.08124354114251092, 'max_depth': 8, 'min_child_weight': 1, 'subsample': 0.8123759880940706, 'colsample_bytree': 0.6644609344442658}. Best is trial 3 with value: 0.7024219747885774.

Running time: 7.5 sec
OOF RMSE: 1.89 | R2: 0.70
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:12:53,805] Trial 4 finished with value: 0.6909568754944578 and parameters: {'n_estimators': 1000, 'learning_rate': 0.05626181125094612, 'max_depth': 5, 'min_child_weight': 1, 'subsample': 0.8480492700511139, 'colsample_bytree': 0.9435714631239184}. Best is trial 3 with value: 0.7024219747885774.

Running time: 4.9 sec
OOF RMSE: 1.93 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:13:00,416] Trial 5 finished with value: 0.5884881570413084 and parameters: {'n_estimators': 1000, 'learning_rate': 0.07176793260880389, 'max_depth': 8, 'min_child_weight': 3, 'subsample': 0.7108304319297235, 'colsample_bytree': 0.8957995115100621}. Best is trial 3 with value: 0.7024219747885774.

Running time: 6.6 sec
OOF RMSE: 2.22 | R2: 0.59
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:13:03,642] Trial 6 finished with value: 0.6312721148772638 and parameters: {'n_estimators': 500, 'learning_rate': 0.031440344988649054, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.8702747662656901, 'colsample_bytree': 0.9730477099972841}. Best is trial 3 with value: 0.7024219747885774.

Running time: 3.2 sec
OOF RMSE: 2.10 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:13:08,330] Trial 7 finished with value: 0.6884221773058641 and parameters: {'n_estimators': 500, 'learning_rate': 0.03347730196783021, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.927822037703239, 'colsample_bytree': 0.859331483213956}. Best is trial 3 with value: 0.7024219747885774.

Running time: 4.7 sec
OOF RMSE: 1.93 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:13:13,440] Trial 8 finished with value: 0.6726210424192167 and parameters: {'n_estimators': 500, 'learning_rate': 0.052025831927646926, 'max_depth': 8, 'min_child_weight': 1, 'subsample': 0.9269134788405071, 'colsample_bytree': 0.7447974289361357}. Best is trial 3 with value: 0.7024219747885774.

Running time: 5.1 sec
OOF RMSE: 1.98 | R2: 0.67
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:13:23,155] Trial 9 finished with value: 0.596677117019184 and parameters: {'n_estimators': 2000, 'learning_rate': 0.0542444977811171, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.6647050966726311, 'colsample_bytree': 0.7847880126003404}. Best is trial 3 with value: 0.7024219747885774.

Running time: 9.7 sec
OOF RMSE: 2.20 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:13:34,415] Trial 10 finished with value: 0.674049655082358 and parameters: {'n_estimators': 2000, 'learning_rate': 0.005306281419476085, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.7527303789839629, 'colsample_bytree': 0.6004198190502195}. Best is trial 3 with value: 0.7024219747885774.

Running time: 11.3 sec
OOF RMSE: 1.98 | R2: 0.67
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:13:37,711] Trial 11 finished with value: 0.7053851859040798 and parameters: {'n_estimators': 1000, 'learning_rate': 0.09720010251798367, 'max_depth': 5, 'min_child_weight': 1, 'subsample': 0.8256172673524305, 'colsample_bytree': 0.6807224451196582}. Best is trial 11 with value: 0.7053851859040798.

Running time: 3.3 sec
OOF RMSE: 1.88 | R2: 0.71
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:13:43,396] Trial 12 finished with value: 0.640829402208239 and parameters: {'n_estimators': 2000, 'learning_rate': 0.09921516106120495, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.7568754047270198, 'colsample_bytree': 0.6890573939685493}. Best is trial 11 with value: 0.7053851859040798.

Running time: 5.7 sec
OOF RMSE: 2.08 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:13:50,090] Trial 13 finished with value: 0.6758706061623045 and parameters: {'n_estimators': 2000, 'learning_rate': 0.09419854825363332, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.7810027415625882, 'colsample_bytree': 0.6646029629849567}. Best is trial 11 with value: 0.7053851859040798.

Running time: 6.7 sec
OOF RMSE: 1.97 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:13:56,566] Trial 14 finished with value: 0.6950762747309291 and parameters: {'n_estimators': 1000, 'learning_rate': 0.04294269730807846, 'max_depth': 6, 'min_child_weight': 1, 'subsample': 0.8725852346509018, 'colsample_bytree': 0.8127170307894679}. Best is trial 11 with value: 0.7053851859040798.

Running time: 6.5 sec
OOF RMSE: 1.91 | R2: 0.70
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:14:09,660] Trial 15 finished with value: 0.6719024465178529 and parameters: {'n_estimators': 2000, 'learning_rate': 0.01769487640979116, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.7143617623541332, 'colsample_bytree': 0.7123229308235363}. Best is trial 11 with value: 0.7053851859040798.

Running time: 13.1 sec
OOF RMSE: 1.99 | R2: 0.67
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:14:13,808] Trial 16 finished with value: 0.7120482423275537 and parameters: {'n_estimators': 1000, 'learning_rate': 0.08099127174553537, 'max_depth': 8, 'min_child_weight': 1, 'subsample': 0.8197401740188863, 'colsample_bytree': 0.6072082091050536}. Best is trial 16 with value: 0.7120482423275537.

Running time: 4.1 sec
OOF RMSE: 1.86 | R2: 0.71
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:14:17,271] Trial 17 finished with value: 0.6647341459468612 and parameters: {'n_estimators': 1000, 'learning_rate': 0.0671583220725575, 'max_depth': 5, 'min_child_weight': 1, 'subsample': 0.9240180920078013, 'colsample_bytree': 0.6030848412890911}. Best is trial 16 with value: 0.7120482423275537.

Running time: 3.5 sec
OOF RMSE: 2.01 | R2: 0.66
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:14:24,804] Trial 18 finished with value: 0.684694032855821 and parameters: {'n_estimators': 1000, 'learning_rate': 0.00837879550307143, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.8447145531892407, 'colsample_bytree': 0.6327893190344405}. Best is trial 16 with value: 0.7120482423275537.

Running time: 7.5 sec
OOF RMSE: 1.95 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:14:33,322] Trial 19 finished with value: 0.6983302126230588 and parameters: {'n_estimators': 1000, 'learning_rate': 0.02166307603169338, 'max_depth': 6, 'min_child_weight': 1, 'subsample': 0.9897793832431941, 'colsample_bytree': 0.7629300918828227}. Best is trial 16 with value: 0.7120482423275537.

Running time: 8.5 sec
OOF RMSE: 1.90 | R2: 0.70
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:14:40,571] Trial 20 finished with value: 0.653164627817461 and parameters: {'n_estimators': 1000, 'learning_rate': 0.04288168658609716, 'max_depth': 8, 'min_child_weight': 2, 'subsample': 0.7164167423771631, 'colsample_bytree': 0.6943545666762386}. Best is trial 16 with value: 0.7120482423275537.

Running time: 7.2 sec
OOF RMSE: 2.04 | R2: 0.65
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:14:47,716] Trial 21 finished with value: 0.6887104102142072 and parameters: {'n_estimators': 2000, 'learning_rate': 0.07803794353516329, 'max_depth': 8, 'min_child_weight': 1, 'subsample': 0.8082825235316973, 'colsample_bytree': 0.6444188246086511}. Best is trial 16 with value: 0.7120482423275537.

Running time: 7.1 sec
OOF RMSE: 1.93 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:14:51,411] Trial 22 finished with value: 0.6956758442544158 and parameters: {'n_estimators': 1000, 'learning_rate': 0.09999020524524907, 'max_depth': 8, 'min_child_weight': 1, 'subsample': 0.7967848358649755, 'colsample_bytree': 0.6739364242338701}. Best is trial 16 with value: 0.7120482423275537.

Running time: 3.7 sec
OOF RMSE: 1.91 | R2: 0.70
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:14:55,744] Trial 23 finished with value: 0.666477163167176 and parameters: {'n_estimators': 1000, 'learning_rate': 0.07305167317224577, 'max_depth': 8, 'min_child_weight': 1, 'subsample': 0.8992830888293828, 'colsample_bytree': 0.6299630169002408}. Best is trial 16 with value: 0.7120482423275537.

Running time: 4.3 sec
OOF RMSE: 2.00 | R2: 0.67
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:15:04,497] Trial 24 finished with value: 0.6870255376382364 and parameters: {'n_estimators': 2000, 'learning_rate': 0.044973553288625144, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.8307224619868271, 'colsample_bytree': 0.8247885910750421}. Best is trial 16 with value: 0.7120482423275537.
[I 2025-07-11 22:15:04,498] A new study created in memory with name: no-name-b33503e2-7c18-4c4c-9bf0-d452a6bbfdf5

Running time: 8.7 sec
OOF RMSE: 1.94 | R2: 0.69

✅ XGB - Mejor R2: 0.71
📋 Parámetros: {'n_estimators': 1000, 'learning_rate': 0.08099127174553537, 'max_depth': 8, 'min_child_weight': 1, 'subsample': 0.8197401740188863, 'colsample_bytree': 0.6072082091050536}

Buscando mejores hiperparámetros para LBM...
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 22:15:04,789] Trial 0 finished with value: 0.6457907222736925 and parameters: {'learning_rate': 0.008254727177117484, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 5, 'subsample': 0.8465113544450689, 'colsample_bytree': 0.8675432556158755, 'n_estimators': 500}. Best is trial 0 with value: 0.6457907222736925.

Fold 5
Running time: 0.3 sec
OOF RMSE: 2.06 | R2: 0.65
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:15:05,242] Trial 1 finished with value: 0.6621341042606397 and parameters: {'learning_rate': 0.011406592500662819, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 21, 'subsample': 0.6380100945869713, 'colsample_bytree': 0.8891407052571139, 'n_estimators': 1000}. Best is trial 1 with value: 0.6621341042606397.

Running time: 0.4 sec
OOF RMSE: 2.01 | R2: 0.66
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 22:15:05,908] Trial 2 finished with value: 0.6342653794610349 and parameters: {'learning_rate': 0.0070530853145937145, 'num_leaves': 40, 'max_depth': 6, 'min_child_samples': 5, 'subsample': 0.6160181722023937, 'colsample_bytree': 0.9834042594277024, 'n_estimators': 1000}. Best is trial 1 with value: 0.6621341042606397.

Fold 5
Running time: 0.7 sec
OOF RMSE: 2.10 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:15:06,818] Trial 3 finished with value: 0.7099378586307248 and parameters: {'learning_rate': 0.029448210789805966, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 24, 'subsample': 0.7870481536782934, 'colsample_bytree': 0.7422030954387295, 'n_estimators': 2000}. Best is trial 3 with value: 0.7099378586307248.

Running time: 0.9 sec
OOF RMSE: 1.87 | R2: 0.71
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:15:07,756] Trial 4 finished with value: 0.7090064788276367 and parameters: {'learning_rate': 0.07343653524777659, 'num_leaves': 40, 'max_depth': 7, 'min_child_samples': 22, 'subsample': 0.9149973232105053, 'colsample_bytree': 0.6375684479432713, 'n_estimators': 2000}. Best is trial 3 with value: 0.7099378586307248.

Running time: 0.9 sec
OOF RMSE: 1.87 | R2: 0.71
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 22:15:08,606] Trial 5 finished with value: 0.6701306781207373 and parameters: {'learning_rate': 0.005924690686401934, 'num_leaves': 80, 'max_depth': 5, 'min_child_samples': 22, 'subsample': 0.9127552941937364, 'colsample_bytree': 0.9343459947796388, 'n_estimators': 2000}. Best is trial 3 with value: 0.7099378586307248.

Fold 5
Running time: 0.8 sec
OOF RMSE: 1.99 | R2: 0.67
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 22:15:08,956] Trial 6 finished with value: 0.6421977210218976 and parameters: {'learning_rate': 0.06888809272053713, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 8, 'subsample': 0.6736480295261434, 'colsample_bytree': 0.8664326565838185, 'n_estimators': 500}. Best is trial 3 with value: 0.7099378586307248.

Fold 5
Running time: 0.3 sec
OOF RMSE: 2.07 | R2: 0.64
Fold 1
Fold 2
Fold 3

[I 2025-07-11 22:15:09,227] Trial 7 finished with value: 0.5498823991456552 and parameters: {'learning_rate': 0.04502418047299976, 'num_leaves': 80, 'max_depth': 6, 'min_child_samples': 10, 'subsample': 0.8104696338549903, 'colsample_bytree': 0.605425043648495, 'n_estimators': 500}. Best is trial 3 with value: 0.7099378586307248.

Fold 4
Fold 5
Running time: 0.3 sec
OOF RMSE: 2.33 | R2: 0.55
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:15:10,448] Trial 8 finished with value: 0.6026278087016026 and parameters: {'learning_rate': 0.007520999447690598, 'num_leaves': 80, 'max_depth': 8, 'min_child_samples': 9, 'subsample': 0.9607274809250391, 'colsample_bytree': 0.6143672195171418, 'n_estimators': 2000}. Best is trial 3 with value: 0.7099378586307248.

Running time: 1.2 sec
OOF RMSE: 2.19 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 22:15:11,364] Trial 9 finished with value: 0.6828607986584017 and parameters: {'learning_rate': 0.007278149291611011, 'num_leaves': 60, 'max_depth': 6, 'min_child_samples': 23, 'subsample': 0.9025625211215588, 'colsample_bytree': 0.7840049483386344, 'n_estimators': 2000}. Best is trial 3 with value: 0.7099378586307248.

Fold 5
Running time: 0.9 sec
OOF RMSE: 1.95 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:15:12,506] Trial 10 finished with value: 0.5651581584414287 and parameters: {'learning_rate': 0.023059226423911887, 'num_leaves': 60, 'max_depth': 8, 'min_child_samples': 17, 'subsample': 0.7585210210318731, 'colsample_bytree': 0.7326809643526704, 'n_estimators': 2000}. Best is trial 3 with value: 0.7099378586307248.

Running time: 1.1 sec
OOF RMSE: 2.29 | R2: 0.57
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:15:13,423] Trial 11 finished with value: 0.6958136838879745 and parameters: {'learning_rate': 0.03301219954079426, 'num_leaves': 40, 'max_depth': 7, 'min_child_samples': 25, 'subsample': 0.743680417840166, 'colsample_bytree': 0.7049704759567167, 'n_estimators': 2000}. Best is trial 3 with value: 0.7099378586307248.

Running time: 0.9 sec
OOF RMSE: 1.91 | R2: 0.70
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 22:15:14,505] Trial 12 finished with value: 0.6032849285644852 and parameters: {'learning_rate': 0.09617370068045954, 'num_leaves': 40, 'max_depth': 7, 'min_child_samples': 18, 'subsample': 0.8584513840915092, 'colsample_bytree': 0.6885202389567838, 'n_estimators': 2000}. Best is trial 3 with value: 0.7099378586307248.

Fold 5
Running time: 1.1 sec
OOF RMSE: 2.18 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:15:15,539] Trial 13 finished with value: 0.5395962049760414 and parameters: {'learning_rate': 0.016721863362213787, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 14, 'subsample': 0.9885639552900685, 'colsample_bytree': 0.6584620590687029, 'n_estimators': 2000}. Best is trial 3 with value: 0.7099378586307248.

Running time: 1.0 sec
OOF RMSE: 2.35 | R2: 0.54
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:15:16,679] Trial 14 finished with value: 0.6535994353992185 and parameters: {'learning_rate': 0.04594843498133386, 'num_leaves': 40, 'max_depth': 8, 'min_child_samples': 19, 'subsample': 0.7232089946123333, 'colsample_bytree': 0.7751089529090497, 'n_estimators': 2000}. Best is trial 3 with value: 0.7099378586307248.

Running time: 1.1 sec
OOF RMSE: 2.04 | R2: 0.65
Fold 1
Fold 2
Fold 3

[I 2025-07-11 22:15:17,138] Trial 15 finished with value: 0.693124702001833 and parameters: {'learning_rate': 0.02436313757788027, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 25, 'subsample': 0.798469812418081, 'colsample_bytree': 0.7425980771343808, 'n_estimators': 1000}. Best is trial 3 with value: 0.7099378586307248.

Fold 4
Fold 5
Running time: 0.5 sec
OOF RMSE: 1.92 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:15:18,068] Trial 16 finished with value: 0.5517454790939882 and parameters: {'learning_rate': 0.060968214379075986, 'num_leaves': 40, 'max_depth': 6, 'min_child_samples': 15, 'subsample': 0.9177983014048859, 'colsample_bytree': 0.6546750397558918, 'n_estimators': 2000}. Best is trial 3 with value: 0.7099378586307248.

Running time: 0.9 sec
OOF RMSE: 2.32 | R2: 0.55
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:15:19,144] Trial 17 finished with value: 0.7097592389234613 and parameters: {'learning_rate': 0.09838890457077999, 'num_leaves': 60, 'max_depth': 8, 'min_child_samples': 20, 'subsample': 0.698102199070893, 'colsample_bytree': 0.8083340649201293, 'n_estimators': 2000}. Best is trial 3 with value: 0.7099378586307248.

Running time: 1.1 sec
OOF RMSE: 1.87 | R2: 0.71
Fold 1
Fold 2
Fold 3

[I 2025-07-11 22:15:19,469] Trial 18 finished with value: 0.6569055551715632 and parameters: {'learning_rate': 0.01487038706169685, 'num_leaves': 60, 'max_depth': 8, 'min_child_samples': 20, 'subsample': 0.6946966357074209, 'colsample_bytree': 0.8302567226842528, 'n_estimators': 500}. Best is trial 3 with value: 0.7099378586307248.

Fold 4
Fold 5
Running time: 0.3 sec
OOF RMSE: 2.03 | R2: 0.66
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:15:20,150] Trial 19 finished with value: 0.5824085616245669 and parameters: {'learning_rate': 0.034549520178820244, 'num_leaves': 60, 'max_depth': 8, 'min_child_samples': 13, 'subsample': 0.7851318593615066, 'colsample_bytree': 0.8246745192573989, 'n_estimators': 1000}. Best is trial 3 with value: 0.7099378586307248.

Running time: 0.7 sec
OOF RMSE: 2.24 | R2: 0.58
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:15:21,325] Trial 20 finished with value: 0.5601657175740282 and parameters: {'learning_rate': 0.09459377791265125, 'num_leaves': 60, 'max_depth': 8, 'min_child_samples': 17, 'subsample': 0.6801858163460142, 'colsample_bytree': 0.7542418786640691, 'n_estimators': 2000}. Best is trial 3 with value: 0.7099378586307248.

Running time: 1.2 sec
OOF RMSE: 2.30 | R2: 0.56
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 22:15:22,307] Trial 21 finished with value: 0.6970996704979198 and parameters: {'learning_rate': 0.07233178122405638, 'num_leaves': 40, 'max_depth': 7, 'min_child_samples': 23, 'subsample': 0.8500791509652472, 'colsample_bytree': 0.7023981814524026, 'n_estimators': 2000}. Best is trial 3 with value: 0.7099378586307248.

Fold 5
Running time: 1.0 sec
OOF RMSE: 1.91 | R2: 0.70
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:15:23,263] Trial 22 finished with value: 0.7026127590128703 and parameters: {'learning_rate': 0.05097033764423076, 'num_leaves': 60, 'max_depth': 7, 'min_child_samples': 24, 'subsample': 0.7212957928596146, 'colsample_bytree': 0.813096613176982, 'n_estimators': 2000}. Best is trial 3 with value: 0.7099378586307248.

Running time: 1.0 sec
OOF RMSE: 1.89 | R2: 0.70
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:15:24,264] Trial 23 finished with value: 0.714135698411859 and parameters: {'learning_rate': 0.03297702117256764, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 20, 'subsample': 0.7714555033722502, 'colsample_bytree': 0.6549934685555461, 'n_estimators': 2000}. Best is trial 23 with value: 0.714135698411859.

Running time: 1.0 sec
OOF RMSE: 1.85 | R2: 0.71
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:15:25,272] Trial 24 finished with value: 0.7098730639999051 and parameters: {'learning_rate': 0.03243661183568076, 'num_leaves': 20, 'max_depth': 8, 'min_child_samples': 20, 'subsample': 0.7680412458730473, 'colsample_bytree': 0.6757984110319329, 'n_estimators': 2000}. Best is trial 23 with value: 0.714135698411859.
[I 2025-07-11 22:15:25,273] A new study created in memory with name: no-name-72cd08fe-59e6-46f2-bf96-b02986d0a233

Running time: 1.0 sec
OOF RMSE: 1.87 | R2: 0.71

✅ LBM - Mejor R2: 0.71
📋 Parámetros: {'learning_rate': 0.03297702117256764, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 20, 'subsample': 0.7714555033722502, 'colsample_bytree': 0.6549934685555461, 'n_estimators': 2000}

Buscando mejores hiperparámetros para MLP...
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 22:15:26,174] Trial 0 finished with value: 0.5212664031364644 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0004680653585730501, 'learning_rate': 'constant', 'learning_rate_init': 0.004244087737488244}. Best is trial 0 with value: 0.5212664031364644.

Fold 5
Running time: 0.9 sec
OOF RMSE: 2.40 | R2: 0.52
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 22:15:28,080] Trial 1 finished with value: 0.39711862931378994 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 1.199700575815955e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.000246194937196873}. Best is trial 0 with value: 0.5212664031364644.

Running time: 1.9 sec
OOF RMSE: 2.69 | R2: 0.40
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 22:15:30,525] Trial 2 finished with value: 0.4391205453898882 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.014596406805934721, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00019777981451526988}. Best is trial 0 with value: 0.5212664031364644.

Running time: 2.4 sec
OOF RMSE: 2.60 | R2: 0.44
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

[I 2025-07-11 22:15:32,097] Trial 3 finished with value: 0.3601798797751876 and parameters: {'hidden_layer_sizes': '50', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.004956870248579336, 'learning_rate': 'adaptive', 'learning_rate_init': 0.008032373817425258}. Best is trial 0 with value: 0.5212664031364644.

Running time: 1.6 sec
OOF RMSE: 2.77 | R2: 0.36
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

[I 2025-07-11 22:15:33,965] Trial 4 finished with value: 0.38174017998055554 and parameters: {'hidden_layer_sizes': '50', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.0008648416582494705, 'learning_rate': 'adaptive', 'learning_rate_init': 0.009726619483621225}. Best is trial 0 with value: 0.5212664031364644.

Running time: 1.9 sec
OOF RMSE: 2.73 | R2: 0.38
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 22:15:35,965] Trial 5 finished with value: 0.44777329255831255 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.00010617662044953263, 'learning_rate': 'constant', 'learning_rate_init': 0.0005273506048070313}. Best is trial 0 with value: 0.5212664031364644.

Running time: 2.0 sec
OOF RMSE: 2.58 | R2: 0.45
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

[I 2025-07-11 22:15:37,081] Trial 6 finished with value: 0.6966820971304561 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.08211894172239899, 'learning_rate': 'constant', 'learning_rate_init': 0.005248015229563677}. Best is trial 6 with value: 0.6966820971304561.

Running time: 1.1 sec
OOF RMSE: 1.91 | R2: 0.70
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 22:15:38,043] Trial 7 finished with value: 0.4046155488088393 and parameters: {'hidden_layer_sizes': '50', 'activation': 'relu', 'solver': 'adam', 'alpha': 1.7795904215356444e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.0003064945966038694}. Best is trial 6 with value: 0.6966820971304561.

Fold 5
Running time: 1.0 sec
OOF RMSE: 2.67 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 22:15:39,186] Trial 8 finished with value: 0.39606912769108893 and parameters: {'hidden_layer_sizes': '50', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.06286204117039113, 'learning_rate': 'constant', 'learning_rate_init': 0.0001984428676248637}. Best is trial 6 with value: 0.6966820971304561.

Fold 5
Running time: 1.1 sec
OOF RMSE: 2.69 | R2: 0.40
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 22:15:39,955] Trial 9 finished with value: 0.4060344312159745 and parameters: {'hidden_layer_sizes': '50', 'activation': 'tanh', 'solver': 'adam', 'alpha': 5.378333451136276e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0038305880182853817}. Best is trial 6 with value: 0.6966820971304561.

Fold 4
Fold 5
Running time: 0.8 sec
OOF RMSE: 2.67 | R2: 0.41
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 22:15:40,886] Trial 10 finished with value: 0.5768524897223275 and parameters: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.09927396977223059, 'learning_rate': 'constant', 'learning_rate_init': 0.0016606441392307625}. Best is trial 6 with value: 0.6966820971304561.

Fold 4
Fold 5
Running time: 0.9 sec
OOF RMSE: 2.25 | R2: 0.58
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

[I 2025-07-11 22:15:41,802] Trial 11 finished with value: 0.584281805758859 and parameters: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.07510996434481357, 'learning_rate': 'constant', 'learning_rate_init': 0.0014470634483343503}. Best is trial 6 with value: 0.6966820971304561.

Running time: 0.9 sec
OOF RMSE: 2.24 | R2: 0.58
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 22:15:42,889] Trial 12 finished with value: 0.5868986313816349 and parameters: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.008378374051319049, 'learning_rate': 'constant', 'learning_rate_init': 0.0013609330008695607}. Best is trial 6 with value: 0.6966820971304561.

Running time: 1.1 sec
OOF RMSE: 2.23 | R2: 0.59
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 22:15:43,925] Trial 13 finished with value: 0.5723468553929019 and parameters: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.008735987266146503, 'learning_rate': 'constant', 'learning_rate_init': 0.0007719702240258276}. Best is trial 6 with value: 0.6966820971304561.

Running time: 1.0 sec
OOF RMSE: 2.27 | R2: 0.57
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:15:45,017] Trial 14 finished with value: 0.5549312429388747 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.019417167601440077, 'learning_rate': 'constant', 'learning_rate_init': 0.0025897911376930993}. Best is trial 6 with value: 0.6966820971304561.

Running time: 1.1 sec
OOF RMSE: 2.31 | R2: 0.55
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:15:45,622] Trial 15 finished with value: 0.5008831132671151 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.00337015177171965, 'learning_rate': 'constant', 'learning_rate_init': 0.004736654892783291}. Best is trial 6 with value: 0.6966820971304561.

Running time: 0.6 sec
OOF RMSE: 2.45 | R2: 0.50
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

[I 2025-07-11 22:15:46,592] Trial 16 finished with value: 0.585251700526735 and parameters: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.00216153295102602, 'learning_rate': 'constant', 'learning_rate_init': 0.0019940221759365876}. Best is trial 6 with value: 0.6966820971304561.

Running time: 1.0 sec
OOF RMSE: 2.23 | R2: 0.59
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 22:15:48,486] Trial 17 finished with value: 0.5705045875400716 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.02963582477600482, 'learning_rate': 'constant', 'learning_rate_init': 0.0007071531320191858}. Best is trial 6 with value: 0.6966820971304561.

Running time: 1.9 sec
OOF RMSE: 2.27 | R2: 0.57
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 22:15:49,364] Trial 18 finished with value: 0.4707059990871606 and parameters: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.021280424728692893, 'learning_rate': 'constant', 'learning_rate_init': 0.0011028884726643057}. Best is trial 6 with value: 0.6966820971304561.

Fold 4
Fold 5
Running time: 0.9 sec
OOF RMSE: 2.52 | R2: 0.47
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 22:15:51,219] Trial 19 finished with value: 0.398732370542332 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0003725983623293137, 'learning_rate': 'constant', 'learning_rate_init': 0.0003952718688993463}. Best is trial 6 with value: 0.6966820971304561.

Fold 5
Running time: 1.8 sec
OOF RMSE: 2.69 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:15:52,613] Trial 20 finished with value: 0.5898932056482424 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.007426068922283992, 'learning_rate': 'constant', 'learning_rate_init': 0.0028542107935002354}. Best is trial 6 with value: 0.6966820971304561.

Running time: 1.4 sec
OOF RMSE: 2.22 | R2: 0.59
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 22:15:54,068] Trial 21 finished with value: 0.5927398610524744 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0017673828169818937, 'learning_rate': 'constant', 'learning_rate_init': 0.0027832542791720433}. Best is trial 6 with value: 0.6966820971304561.

Running time: 1.4 sec
OOF RMSE: 2.21 | R2: 0.59
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:15:55,098] Trial 22 finished with value: 0.6428050438747568 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0016629410839701945, 'learning_rate': 'constant', 'learning_rate_init': 0.006024063740523118}. Best is trial 6 with value: 0.6966820971304561.

Running time: 1.0 sec
OOF RMSE: 2.07 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:15:56,438] Trial 23 finished with value: 0.6886115295874135 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0017654051249585312, 'learning_rate': 'constant', 'learning_rate_init': 0.006205000922470752}. Best is trial 6 with value: 0.6966820971304561.

Running time: 1.3 sec
OOF RMSE: 1.93 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:15:57,540] Trial 24 finished with value: 0.6859296032421943 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.00022642585204176908, 'learning_rate': 'constant', 'learning_rate_init': 0.0066739589326785}. Best is trial 6 with value: 0.6966820971304561.
[I 2025-07-11 22:15:57,541] A new study created in memory with name: no-name-735a96cb-1ff9-4207-b84a-f3867c67cf3c
[I 2025-07-11 22:15:57,631] Trial 0 finished with value: 0.49440200705164816 and parameters: {'kernel': 'rbf', 'C': 4.193895464410173, 'epsilon': 0.15185153832534773, 'gamma': 'scale'}. Best is trial 0 with value: 0.49440200705164816.
[I 2025-07-11 22:15:57,713] Trial 1 finished with value: -7.304155463782498 and parameters: {'kernel': 'sigmoid', 'C': 1.5531549251061723, 'epsilon': 0.059889268576535114, 'gamma': 'scale'}. Best is trial 0 with value: 0.49440200705164816.

Running time: 1.1 sec
OOF RMSE: 1.94 | R2: 0.69

✅ MLP - Mejor R2: 0.70
📋 Parámetros: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.08211894172239899, 'learning_rate': 'constant', 'learning_rate_init': 0.005248015229563677}

Buscando mejores hiperparámetros para SVR...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.46 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 9.99 | R2: -7.30
Fold 1
Fold 2

[I 2025-07-11 22:15:57,786] Trial 2 finished with value: 0.5072492636782585 and parameters: {'kernel': 'rbf', 'C': 5.725618312262369, 'epsilon': 0.04897213831760466, 'gamma': 'auto'}. Best is trial 2 with value: 0.5072492636782585.
[I 2025-07-11 22:15:57,860] Trial 3 finished with value: 0.08314279236081024 and parameters: {'kernel': 'sigmoid', 'C': 0.133450626276245, 'epsilon': 0.18270653513027044, 'gamma': 'scale'}. Best is trial 2 with value: 0.5072492636782585.
[I 2025-07-11 22:15:57,936] Trial 4 finished with value: -9.970074468046775 and parameters: {'kernel': 'sigmoid', 'C': 1.8333674140161218, 'epsilon': 0.16376953082820447, 'gamma': 'scale'}. Best is trial 2 with value: 0.5072492636782585.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.43 | R2: 0.51
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.32 | R2: 0.08
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 11.48 | R2: -9.97
Fold 1

[I 2025-07-11 22:15:58,016] Trial 5 finished with value: -10.188569181927173 and parameters: {'kernel': 'sigmoid', 'C': 3.330228884070186, 'epsilon': 0.15754221966815443, 'gamma': 'auto'}. Best is trial 2 with value: 0.5072492636782585.
[I 2025-07-11 22:15:58,092] Trial 6 finished with value: 0.08142055684701843 and parameters: {'kernel': 'sigmoid', 'C': 0.12171954016495781, 'epsilon': 0.1740658095368358, 'gamma': 'scale'}. Best is trial 2 with value: 0.5072492636782585.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 11.60 | R2: -10.19
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.32 | R2: 0.08
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:15:58,165] Trial 7 finished with value: 0.15159912479456839 and parameters: {'kernel': 'rbf', 'C': 0.3242060251667217, 'epsilon': 0.16231859132365, 'gamma': 'scale'}. Best is trial 2 with value: 0.5072492636782585.
[I 2025-07-11 22:15:58,245] Trial 8 finished with value: 0.5598256567043219 and parameters: {'kernel': 'rbf', 'C': 5.709034671000622, 'epsilon': 0.1402535552300642, 'gamma': 'scale'}. Best is trial 8 with value: 0.5598256567043219.
[I 2025-07-11 22:15:58,323] Trial 9 finished with value: -40.27411665007792 and parameters: {'kernel': 'sigmoid', 'C': 6.827153072722921, 'epsilon': 0.028472471768571414, 'gamma': 'auto'}. Best is trial 8 with value: 0.5598256567043219.

Running time: 0.1 sec
OOF RMSE: 3.19 | R2: 0.15
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.30 | R2: 0.56
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 22.27 | R2: -40.27
Fold 1
Fold 2
Fold 3

[I 2025-07-11 22:15:58,395] Trial 10 finished with value: 0.238219087607489 and parameters: {'kernel': 'rbf', 'C': 0.642432683575363, 'epsilon': 0.10441629319243377, 'gamma': 'auto'}. Best is trial 8 with value: 0.5598256567043219.
[I 2025-07-11 22:15:58,479] Trial 11 finished with value: 0.5775036818323869 and parameters: {'kernel': 'rbf', 'C': 9.881958159789288, 'epsilon': 0.10502117729113379, 'gamma': 'auto'}. Best is trial 11 with value: 0.5775036818323869.
[I 2025-07-11 22:15:58,565] Trial 12 finished with value: 0.5740201214089082 and parameters: {'kernel': 'rbf', 'C': 9.438342648424198, 'epsilon': 0.11179156725501274, 'gamma': 'auto'}. Best is trial 11 with value: 0.5775036818323869.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.03 | R2: 0.24
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.25 | R2: 0.58
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.26 | R2: 0.57

[I 2025-07-11 22:15:58,671] Trial 13 finished with value: 0.5541528107451335 and parameters: {'kernel': 'rbf', 'C': 7.922444487500126, 'epsilon': 0.10729313524645198, 'gamma': 'auto'}. Best is trial 11 with value: 0.5775036818323869.
[I 2025-07-11 22:15:58,757] Trial 14 finished with value: 0.3900698438367993 and parameters: {'kernel': 'rbf', 'C': 2.5119770551934137, 'epsilon': 0.1045747932820403, 'gamma': 'auto'}. Best is trial 11 with value: 0.5775036818323869.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.31 | R2: 0.55
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.71 | R2: 0.39
Fold 1

[I 2025-07-11 22:15:58,841] Trial 15 finished with value: 0.2629209942105116 and parameters: {'kernel': 'rbf', 'C': 0.8305813629703209, 'epsilon': 0.07723382289713633, 'gamma': 'auto'}. Best is trial 11 with value: 0.5775036818323869.
[I 2025-07-11 22:15:58,930] Trial 16 finished with value: 0.5772581872148389 and parameters: {'kernel': 'rbf', 'C': 9.639170126413541, 'epsilon': 0.12870130482022507, 'gamma': 'auto'}. Best is trial 11 with value: 0.5775036818323869.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.98 | R2: 0.26
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.25 | R2: 0.58
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 22:15:59,011] Trial 17 finished with value: 0.19663248997027793 and parameters: {'kernel': 'rbf', 'C': 0.43463101477472876, 'epsilon': 0.13192727340245433, 'gamma': 'auto'}. Best is trial 11 with value: 0.5775036818323869.
[I 2025-07-11 22:15:59,103] Trial 18 finished with value: 0.5778171822086728 and parameters: {'kernel': 'rbf', 'C': 9.960529022869368, 'epsilon': 0.07911395726730236, 'gamma': 'auto'}. Best is trial 18 with value: 0.5778171822086728.
[I 2025-07-11 22:15:59,192] Trial 19 finished with value: 0.43074883914980244 and parameters: {'kernel': 'rbf', 'C': 3.3478804576237575, 'epsilon': 0.1994968278779536, 'gamma': 'auto'}. Best is trial 18 with value: 0.5778171822086728.

Fold 5
Running time: 0.1 sec
OOF RMSE: 3.11 | R2: 0.20
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.25 | R2: 0.58
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.62 | R2: 0.43

[I 2025-07-11 22:15:59,275] Trial 20 finished with value: 0.3350518955778249 and parameters: {'kernel': 'rbf', 'C': 1.555452805779577, 'epsilon': 0.07837171641726082, 'gamma': 'auto'}. Best is trial 18 with value: 0.5778171822086728.
[I 2025-07-11 22:15:59,366] Trial 21 finished with value: 0.5701610118458214 and parameters: {'kernel': 'rbf', 'C': 9.137750920384539, 'epsilon': 0.08656847026176713, 'gamma': 'auto'}. Best is trial 18 with value: 0.5778171822086728.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.83 | R2: 0.34
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.27 | R2: 0.57
Fold 1
Fold 2
Fold 3

[I 2025-07-11 22:15:59,453] Trial 22 finished with value: 0.48921643761115563 and parameters: {'kernel': 'rbf', 'C': 4.977561159228125, 'epsilon': 0.12492279258986705, 'gamma': 'auto'}. Best is trial 18 with value: 0.5778171822086728.
[I 2025-07-11 22:15:59,545] Trial 23 finished with value: 0.575618967295868 and parameters: {'kernel': 'rbf', 'C': 9.746344306908162, 'epsilon': 0.061041658706559775, 'gamma': 'auto'}. Best is trial 18 with value: 0.5778171822086728.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.48 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.26 | R2: 0.58
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:15:59,629] Trial 24 finished with value: 0.39255849417054367 and parameters: {'kernel': 'rbf', 'C': 2.592390707339247, 'epsilon': 0.01955642069535385, 'gamma': 'auto'}. Best is trial 18 with value: 0.5778171822086728.
[I 2025-07-11 22:15:59,631] A new study created in memory with name: no-name-1ebbff6c-04c7-408e-81ae-368741c45ace
[I 2025-07-11 22:15:59,699] Trial 0 finished with value: 0.649244791523355 and parameters: {'n_neighbors': 13, 'weights': 'distance', 'leaf_size': 11}. Best is trial 0 with value: 0.649244791523355.
[I 2025-07-11 22:15:59,764] Trial 1 finished with value: 0.5096495802562049 and parameters: {'n_neighbors': 11, 'weights': 'uniform', 'leaf_size': 29}. Best is trial 0 with value: 0.649244791523355.
[I 2025-07-11 22:15:59,827] Trial 2 finished with value: 0.7025765146759508 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'leaf_size': 39}. Best is trial 2 with value: 0.7025765146759508.

Running time: 0.1 sec
OOF RMSE: 2.70 | R2: 0.39

✅ SVR - Mejor R2: 0.58
📋 Parámetros: {'kernel': 'rbf', 'C': 9.960529022869368, 'epsilon': 0.07911395726730236, 'gamma': 'auto'}

Buscando mejores hiperparámetros para KNN...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.05 | R2: 0.65
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.43 | R2: 0.51
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.89 | R2: 0.70

[I 2025-07-11 22:15:59,895] Trial 3 finished with value: 0.5063312846151342 and parameters: {'n_neighbors': 15, 'weights': 'uniform', 'leaf_size': 37}. Best is trial 2 with value: 0.7025765146759508.
[I 2025-07-11 22:15:59,960] Trial 4 finished with value: 0.6504080512825579 and parameters: {'n_neighbors': 11, 'weights': 'distance', 'leaf_size': 14}. Best is trial 2 with value: 0.7025765146759508.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.44 | R2: 0.51
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.05 | R2: 0.65
Fold 1
Fold 2
Fold 3

[I 2025-07-11 22:16:00,066] Trial 5 finished with value: 0.6847983491274441 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 40}. Best is trial 2 with value: 0.7025765146759508.
[I 2025-07-11 22:16:00,137] Trial 6 finished with value: 0.6801128769445004 and parameters: {'n_neighbors': 8, 'weights': 'distance', 'leaf_size': 17}. Best is trial 2 with value: 0.7025765146759508.
[I 2025-07-11 22:16:00,202] Trial 7 finished with value: 0.6504080512825579 and parameters: {'n_neighbors': 11, 'weights': 'distance', 'leaf_size': 22}. Best is trial 2 with value: 0.7025765146759508.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.95 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.96 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.05 | R2: 0.65
Fold 1
Fold 2
Fold 3

[I 2025-07-11 22:16:00,269] Trial 8 finished with value: 0.6390899845499278 and parameters: {'n_neighbors': 14, 'weights': 'distance', 'leaf_size': 17}. Best is trial 2 with value: 0.7025765146759508.
[I 2025-07-11 22:16:00,335] Trial 9 finished with value: 0.6277694666274836 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'leaf_size': 10}. Best is trial 2 with value: 0.7025765146759508.
[I 2025-07-11 22:16:00,408] Trial 10 finished with value: 0.6090685835190557 and parameters: {'n_neighbors': 6, 'weights': 'uniform', 'leaf_size': 33}. Best is trial 2 with value: 0.7025765146759508.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.08 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.11 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.17 | R2: 0.61
Fold 1
Fold 2

[I 2025-07-11 22:16:00,483] Trial 11 finished with value: 0.6847983491274441 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 39}. Best is trial 2 with value: 0.7025765146759508.
[I 2025-07-11 22:16:00,558] Trial 12 finished with value: 0.7025765146759508 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'leaf_size': 40}. Best is trial 2 with value: 0.7025765146759508.
[I 2025-07-11 22:16:00,633] Trial 13 finished with value: 0.7149353661873685 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'leaf_size': 33}. Best is trial 13 with value: 0.7149353661873685.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.95 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.89 | R2: 0.70
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.85 | R2: 0.71
Fold 1

[I 2025-07-11 22:16:00,707] Trial 14 finished with value: 0.6917150264867501 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'leaf_size': 33}. Best is trial 13 with value: 0.7149353661873685.
[I 2025-07-11 22:16:00,781] Trial 15 finished with value: 0.7025765146759508 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'leaf_size': 27}. Best is trial 13 with value: 0.7149353661873685.
[I 2025-07-11 22:16:00,856] Trial 16 finished with value: 0.6764779788494 and parameters: {'n_neighbors': 9, 'weights': 'distance', 'leaf_size': 34}. Best is trial 13 with value: 0.7149353661873685.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.92 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.89 | R2: 0.70
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.97 | R2: 0.68

[I 2025-07-11 22:16:00,928] Trial 17 finished with value: 0.7025765146759508 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'leaf_size': 30}. Best is trial 13 with value: 0.7149353661873685.
[I 2025-07-11 22:16:01,049] Trial 18 finished with value: 0.5641761587453741 and parameters: {'n_neighbors': 7, 'weights': 'uniform', 'leaf_size': 24}. Best is trial 13 with value: 0.7149353661873685.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.89 | R2: 0.70
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.29 | R2: 0.56
Fold 1

[I 2025-07-11 22:16:01,132] Trial 19 finished with value: 0.6764779788494 and parameters: {'n_neighbors': 9, 'weights': 'distance', 'leaf_size': 35}. Best is trial 13 with value: 0.7149353661873685.
[I 2025-07-11 22:16:01,207] Trial 20 finished with value: 0.692311925507083 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'leaf_size': 30}. Best is trial 13 with value: 0.7149353661873685.
[I 2025-07-11 22:16:01,283] Trial 21 finished with value: 0.7025765146759508 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'leaf_size': 37}. Best is trial 13 with value: 0.7149353661873685.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.97 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.92 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.89 | R2: 0.70

[I 2025-07-11 22:16:01,370] Trial 22 finished with value: 0.7149353661873685 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'leaf_size': 40}. Best is trial 13 with value: 0.7149353661873685.
[I 2025-07-11 22:16:01,453] Trial 23 finished with value: 0.6917150264867501 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'leaf_size': 36}. Best is trial 13 with value: 0.7149353661873685.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.85 | R2: 0.71
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.92 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 22:16:01,523] Trial 24 finished with value: 0.7149353661873685 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'leaf_size': 38}. Best is trial 13 with value: 0.7149353661873685.
[I 2025-07-11 22:16:01,525] A new study created in memory with name: no-name-35cc944d-fa92-409f-b172-7273e1ed3e09
[I 2025-07-11 22:16:01,653] Trial 0 finished with value: 0.24666640850268773 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 0 with value: 0.24666640850268773.

Fold 5
Running time: 0.1 sec
OOF RMSE: 1.85 | R2: 0.71

✅ KNN - Mejor R2: 0.71
📋 Parámetros: {'n_neighbors': 6, 'weights': 'distance', 'leaf_size': 33}

Buscando mejores hiperparámetros para LR...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.01 | R2: 0.25
Fold 1
Fold 2
Fold 3

[I 2025-07-11 22:16:01,803] Trial 1 finished with value: 0.24666640850268773 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 0 with value: 0.24666640850268773.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.01 | R2: 0.25
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 22:16:01,979] Trial 2 finished with value: 0.24666640850642296 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 2 with value: 0.24666640850642296.
[I 2025-07-11 22:16:02,084] Trial 3 finished with value: 0.4881213296120218 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 3 with value: 0.4881213296120218.
[I 2025-07-11 22:16:02,148] Trial 4 finished with value: 0.4881213296120218 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 3 with value: 0.4881213296120218.

Fold 5
Running time: 0.2 sec
OOF RMSE: 3.01 | R2: 0.25
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.48 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.48 | R2: 0.49
Fold 1

[I 2025-07-11 22:16:02,212] Trial 5 finished with value: 0.48812132961202237 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 5 with value: 0.48812132961202237.
[I 2025-07-11 22:16:02,277] Trial 6 finished with value: 0.48812132961202237 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 5 with value: 0.48812132961202237.
[I 2025-07-11 22:16:02,366] Trial 7 finished with value: 0.24666640850268773 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 5 with value: 0.48812132961202237.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.48 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.48 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.01 | R2: 0.25

[I 2025-07-11 22:16:02,465] Trial 8 finished with value: 0.48812132961202237 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 5 with value: 0.48812132961202237.
[I 2025-07-11 22:16:02,555] Trial 9 finished with value: 0.24666640850642296 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 5 with value: 0.48812132961202237.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.48 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.01 | R2: 0.25
Fold 1
Fold 2

[I 2025-07-11 22:16:02,635] Trial 10 finished with value: 0.48812132961202237 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 5 with value: 0.48812132961202237.
[I 2025-07-11 22:16:02,698] Trial 11 finished with value: 0.48812132961202237 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 5 with value: 0.48812132961202237.
[I 2025-07-11 22:16:02,762] Trial 12 finished with value: 0.48812132961202237 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 5 with value: 0.48812132961202237.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.48 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.48 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.48 | R2: 0.49
Fold 1
Fold 2
Fold 3

[I 2025-07-11 22:16:02,827] Trial 13 finished with value: 0.48812132961202237 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 5 with value: 0.48812132961202237.
[I 2025-07-11 22:16:02,890] Trial 14 finished with value: 0.48812132961202237 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 5 with value: 0.48812132961202237.
[I 2025-07-11 22:16:02,956] Trial 15 finished with value: 0.48812132961202237 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 5 with value: 0.48812132961202237.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.48 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.48 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.48 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 22:16:03,021] Trial 16 finished with value: 0.48812132961202237 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 5 with value: 0.48812132961202237.
[I 2025-07-11 22:16:03,085] Trial 17 finished with value: 0.48812132961202237 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 5 with value: 0.48812132961202237.
[I 2025-07-11 22:16:03,150] Trial 18 finished with value: 0.4881213296120218 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 5 with value: 0.48812132961202237.

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.48 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.48 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.48 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:16:03,212] Trial 19 finished with value: 0.48812132961202237 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 5 with value: 0.48812132961202237.
[I 2025-07-11 22:16:03,277] Trial 20 finished with value: 0.48812132961202237 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 5 with value: 0.48812132961202237.
[I 2025-07-11 22:16:03,342] Trial 21 finished with value: 0.48812132961202237 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 5 with value: 0.48812132961202237.
[I 2025-07-11 22:16:03,404] Trial 22 finished with value: 0.48812132961202237 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 5 with value: 0.48812132961202237.

Running time: 0.1 sec
OOF RMSE: 2.48 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.48 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.48 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.48 | R2: 0.49
Fold 1

[I 2025-07-11 22:16:03,469] Trial 23 finished with value: 0.48812132961202237 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 5 with value: 0.48812132961202237.
[I 2025-07-11 22:16:03,532] Trial 24 finished with value: 0.48812132961202237 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 5 with value: 0.48812132961202237.
[I 2025-07-11 22:16:03,533] A new study created in memory with name: no-name-5c942467-3d4b-4e3c-bc83-ed826880bbc6

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.48 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.48 | R2: 0.49

✅ LR - Mejor R2: 0.49
📋 Parámetros: {'fit_intercept': True, 'positive': True}

Buscando mejores hiperparámetros para RF...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:16:05,821] Trial 0 finished with value: 0.5256777809502763 and parameters: {'n_estimators': 100, 'max_depth': 8, 'min_samples_split': 5, 'min_samples_leaf': 5, 'bootstrap': False}. Best is trial 0 with value: 0.5256777809502763.

Running time: 2.3 sec
OOF RMSE: 2.39 | R2: 0.53
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:16:18,893] Trial 1 finished with value: 0.5157227140791798 and parameters: {'n_estimators': 500, 'max_depth': 12, 'min_samples_split': 7, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 0 with value: 0.5256777809502763.

Running time: 13.1 sec
OOF RMSE: 2.41 | R2: 0.52
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:16:22,819] Trial 2 finished with value: 0.5524636296032144 and parameters: {'n_estimators': 300, 'max_depth': 6, 'min_samples_split': 8, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 2 with value: 0.5524636296032144.

Running time: 3.9 sec
OOF RMSE: 2.32 | R2: 0.55
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:16:34,437] Trial 3 finished with value: 0.5237236108832479 and parameters: {'n_estimators': 500, 'max_depth': 15, 'min_samples_split': 4, 'min_samples_leaf': 5, 'bootstrap': False}. Best is trial 2 with value: 0.5524636296032144.

Running time: 11.6 sec
OOF RMSE: 2.39 | R2: 0.52
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:16:45,451] Trial 4 finished with value: 0.5126738916233459 and parameters: {'n_estimators': 500, 'max_depth': 7, 'min_samples_split': 8, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 2 with value: 0.5524636296032144.

Running time: 11.0 sec
OOF RMSE: 2.42 | R2: 0.51
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:16:48,301] Trial 5 finished with value: 0.4710851413030962 and parameters: {'n_estimators': 100, 'max_depth': 12, 'min_samples_split': 7, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 2 with value: 0.5524636296032144.

Running time: 2.8 sec
OOF RMSE: 2.52 | R2: 0.47
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:17:00,587] Trial 6 finished with value: 0.5238221042730189 and parameters: {'n_estimators': 500, 'max_depth': 13, 'min_samples_split': 6, 'min_samples_leaf': 4, 'bootstrap': False}. Best is trial 2 with value: 0.5524636296032144.

Running time: 12.3 sec
OOF RMSE: 2.39 | R2: 0.52
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:17:03,157] Trial 7 finished with value: 0.539948010328003 and parameters: {'n_estimators': 100, 'max_depth': 10, 'min_samples_split': 2, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 2 with value: 0.5524636296032144.

Running time: 2.6 sec
OOF RMSE: 2.35 | R2: 0.54
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:17:09,532] Trial 8 finished with value: 0.5923555755231487 and parameters: {'n_estimators': 500, 'max_depth': 5, 'min_samples_split': 9, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 8 with value: 0.5923555755231487.

Running time: 6.4 sec
OOF RMSE: 2.21 | R2: 0.59
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:17:11,193] Trial 9 finished with value: 0.6073135340569321 and parameters: {'n_estimators': 100, 'max_depth': 8, 'min_samples_split': 7, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 9 with value: 0.6073135340569321.

Running time: 1.7 sec
OOF RMSE: 2.17 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:17:16,155] Trial 10 finished with value: 0.6109916998141594 and parameters: {'n_estimators': 300, 'max_depth': 9, 'min_samples_split': 10, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 10 with value: 0.6109916998141594.

Running time: 5.0 sec
OOF RMSE: 2.16 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:17:21,110] Trial 11 finished with value: 0.6109916998141594 and parameters: {'n_estimators': 300, 'max_depth': 9, 'min_samples_split': 10, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 10 with value: 0.6109916998141594.

Running time: 4.9 sec
OOF RMSE: 2.16 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:17:26,190] Trial 12 finished with value: 0.6132157671204962 and parameters: {'n_estimators': 300, 'max_depth': 10, 'min_samples_split': 10, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 12 with value: 0.6132157671204962.

Running time: 5.1 sec
OOF RMSE: 2.16 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:17:31,398] Trial 13 finished with value: 0.6139008045088827 and parameters: {'n_estimators': 300, 'max_depth': 11, 'min_samples_split': 10, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 13 with value: 0.6139008045088827.

Running time: 5.2 sec
OOF RMSE: 2.15 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:17:36,280] Trial 14 finished with value: 0.6077418756287865 and parameters: {'n_estimators': 300, 'max_depth': 11, 'min_samples_split': 10, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 13 with value: 0.6139008045088827.

Running time: 4.9 sec
OOF RMSE: 2.17 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:17:41,298] Trial 15 finished with value: 0.6083694190891302 and parameters: {'n_estimators': 300, 'max_depth': 14, 'min_samples_split': 9, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 13 with value: 0.6139008045088827.

Running time: 5.0 sec
OOF RMSE: 2.17 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:17:46,562] Trial 16 finished with value: 0.6167307223299945 and parameters: {'n_estimators': 300, 'max_depth': 11, 'min_samples_split': 9, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 16 with value: 0.6167307223299945.

Running time: 5.3 sec
OOF RMSE: 2.15 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:17:51,541] Trial 17 finished with value: 0.608422063434418 and parameters: {'n_estimators': 300, 'max_depth': 12, 'min_samples_split': 9, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 16 with value: 0.6167307223299945.

Running time: 5.0 sec
OOF RMSE: 2.17 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:17:56,873] Trial 18 finished with value: 0.6176793233947996 and parameters: {'n_estimators': 300, 'max_depth': 11, 'min_samples_split': 8, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 18 with value: 0.6176793233947996.

Running time: 5.3 sec
OOF RMSE: 2.14 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:18:02,011] Trial 19 finished with value: 0.6144362036215807 and parameters: {'n_estimators': 300, 'max_depth': 14, 'min_samples_split': 8, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 18 with value: 0.6176793233947996.

Running time: 5.1 sec
OOF RMSE: 2.15 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:18:06,565] Trial 20 finished with value: 0.5714053128113245 and parameters: {'n_estimators': 300, 'max_depth': 11, 'min_samples_split': 5, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 18 with value: 0.6176793233947996.

Running time: 4.5 sec
OOF RMSE: 2.27 | R2: 0.57
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:18:11,729] Trial 21 finished with value: 0.6143559403722223 and parameters: {'n_estimators': 300, 'max_depth': 15, 'min_samples_split': 8, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 18 with value: 0.6176793233947996.

Running time: 5.2 sec
OOF RMSE: 2.15 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:18:17,120] Trial 22 finished with value: 0.618106352704572 and parameters: {'n_estimators': 300, 'max_depth': 13, 'min_samples_split': 8, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 22 with value: 0.618106352704572.

Running time: 5.4 sec
OOF RMSE: 2.14 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:18:22,773] Trial 23 finished with value: 0.6243075963394364 and parameters: {'n_estimators': 300, 'max_depth': 13, 'min_samples_split': 6, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 23 with value: 0.6243075963394364.

Running time: 5.6 sec
OOF RMSE: 2.12 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:18:28,428] Trial 24 finished with value: 0.6243075963394364 and parameters: {'n_estimators': 300, 'max_depth': 13, 'min_samples_split': 6, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 23 with value: 0.6243075963394364.
[I 2025-07-11 22:18:28,429] A new study created in memory with name: no-name-37f5b860-e26e-41f3-b9bb-f99b3226c572

Running time: 5.6 sec
OOF RMSE: 2.12 | R2: 0.62

✅ RF - Mejor R2: 0.62
📋 Parámetros: {'n_estimators': 300, 'max_depth': 13, 'min_samples_split': 6, 'min_samples_leaf': 1, 'bootstrap': True}

Buscando mejores hiperparámetros para CAT...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:18:31,754] Trial 0 finished with value: 0.6966782757820276 and parameters: {'iterations': 500, 'learning_rate': 0.02163277563608426, 'depth': 6, 'l2_leaf_reg': 6.856613696243321}. Best is trial 0 with value: 0.6966782757820276.

Running time: 3.3 sec
OOF RMSE: 1.91 | R2: 0.70
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:19:55,724] Trial 1 finished with value: 0.6922162404432088 and parameters: {'iterations': 1000, 'learning_rate': 0.01174556112789569, 'depth': 9, 'l2_leaf_reg': 9.524735531367881}. Best is trial 0 with value: 0.6966782757820276.

Running time: 84.0 sec
OOF RMSE: 1.92 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:20:32,955] Trial 2 finished with value: 0.7198708185494418 and parameters: {'iterations': 1000, 'learning_rate': 0.01995935271857202, 'depth': 8, 'l2_leaf_reg': 6.100272755618042}. Best is trial 2 with value: 0.7198708185494418.

Running time: 37.2 sec
OOF RMSE: 1.83 | R2: 0.72
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:20:41,652] Trial 3 finished with value: 0.7027243545480184 and parameters: {'iterations': 2000, 'learning_rate': 0.03757087294652512, 'depth': 5, 'l2_leaf_reg': 5.876953387327062}. Best is trial 2 with value: 0.7198708185494418.

Running time: 8.7 sec
OOF RMSE: 1.89 | R2: 0.70
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:21:09,837] Trial 4 finished with value: 0.7287108380752045 and parameters: {'iterations': 2000, 'learning_rate': 0.014818185117332901, 'depth': 7, 'l2_leaf_reg': 3.7163342230393805}. Best is trial 4 with value: 0.7287108380752045.

Running time: 28.2 sec
OOF RMSE: 1.81 | R2: 0.73
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:26:05,646] Trial 5 finished with value: 0.7159103348039974 and parameters: {'iterations': 2000, 'learning_rate': 0.09003782327532167, 'depth': 10, 'l2_leaf_reg': 9.678432258579955}. Best is trial 4 with value: 0.7287108380752045.

Running time: 295.8 sec
OOF RMSE: 1.85 | R2: 0.72
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:26:19,178] Trial 6 finished with value: 0.7325853843469463 and parameters: {'iterations': 2000, 'learning_rate': 0.06890591113098513, 'depth': 6, 'l2_leaf_reg': 1.795693781101149}. Best is trial 6 with value: 0.7325853843469463.

Running time: 13.5 sec
OOF RMSE: 1.79 | R2: 0.73
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:26:20,740] Trial 7 finished with value: 0.6852792078900711 and parameters: {'iterations': 500, 'learning_rate': 0.018464549289020447, 'depth': 4, 'l2_leaf_reg': 5.453603071137209}. Best is trial 6 with value: 0.7325853843469463.

Running time: 1.6 sec
OOF RMSE: 1.94 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:26:49,030] Trial 8 finished with value: 0.740565999399811 and parameters: {'iterations': 2000, 'learning_rate': 0.02159545997852239, 'depth': 7, 'l2_leaf_reg': 2.2209927280980177}. Best is trial 8 with value: 0.740565999399811.

Running time: 28.3 sec
OOF RMSE: 1.77 | R2: 0.74
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:26:56,926] Trial 9 finished with value: 0.7104498960843528 and parameters: {'iterations': 500, 'learning_rate': 0.09447484936814374, 'depth': 7, 'l2_leaf_reg': 4.730151566769431}. Best is trial 8 with value: 0.740565999399811.

Running time: 7.9 sec
OOF RMSE: 1.87 | R2: 0.71
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:29:50,721] Trial 10 finished with value: 0.7482374765908766 and parameters: {'iterations': 2000, 'learning_rate': 0.03741078139881857, 'depth': 9, 'l2_leaf_reg': 1.4032955394531985}. Best is trial 10 with value: 0.7482374765908766.
[I 2025-07-11 22:29:50,723] A new study created in memory with name: no-name-c324a672-610c-44fa-99a5-6df86247371b
[I 2025-07-11 22:29:50,813] Trial 0 finished with value: -0.00027817151752640434 and parameters: {'alpha': 3.047940951233566, 'l1_ratio': 0.9440557036743287}. Best is trial 0 with value: -0.00027817151752640434.

Running time: 173.8 sec
OOF RMSE: 1.74 | R2: 0.75

✅ CAT - Mejor R2: 0.75
📋 Parámetros: {'iterations': 2000, 'learning_rate': 0.03741078139881857, 'depth': 9, 'l2_leaf_reg': 1.4032955394531985}

Buscando mejores hiperparámetros para EN...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.47 | R2: -0.00
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 22:29:50,954] Trial 1 finished with value: 0.5336010794674413 and parameters: {'alpha': 0.08410170469778162, 'l1_ratio': 0.5376261690798086}. Best is trial 1 with value: 0.5336010794674413.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.085e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.835e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.729e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.645e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.879e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 22:29:51,077] Trial 2 finished with value: 0.5555505565967757 and parameters: {'alpha': 0.005853056481825801, 'l1_ratio': 0.19006245704639368}. Best is trial 2 with value: 0.5555505565967757.

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.37 | R2: 0.53
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.31 | R2: 0.56
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.111e+01, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.070e+00, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.282e+00, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.261e+01, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.109e+01, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 22:29:51,197] Trial 3 finished with value: 0.5484117282814861 and parameters: {'alpha': 0.006143031397346157, 'l1_ratio': 0.6676095756492794}. Best is trial 2 with value: 0.5555505565967757.
[I 2025-07-11 22:29:51,287] Trial 4 finished with value: 0.06572281153064874 and parameters: {'alpha': 3.2725277550736744, 'l1_ratio': 0.5310493088517163}. Best is trial 2 with value: 0.5555505565967757.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.33 | R2: 0.55
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.35 | R2: 0.07
Fold 1
Fold 2
Fold 3

[I 2025-07-11 22:29:51,370] Trial 5 finished with value: 0.4064271521961369 and parameters: {'alpha': 1.8282643466664512, 'l1_ratio': 0.1373974267652055}. Best is trial 2 with value: 0.5555505565967757.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.383e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.415e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.386e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.67 | R2: 0.41
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.858e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.947e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 22:29:51,576] Trial 6 finished with value: 0.48552054278949097 and parameters: {'alpha': 0.0008776572731477401, 'l1_ratio': 0.04536929371979914}. Best is trial 2 with value: 0.5555505565967757.
[I 2025-07-11 22:29:51,695] Trial 7 finished with value: 0.4498357469455836 and parameters: {'alpha': 0.5934189045372303, 'l1_ratio': 0.6570719099075075}. Best is trial 2 with value: 0.5555505565967757.

Running time: 0.2 sec
OOF RMSE: 2.49 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.57 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 22:29:51,805] Trial 8 finished with value: 0.5199646338287498 and parameters: {'alpha': 0.15937823122136568, 'l1_ratio': 0.324002927334592}. Best is trial 2 with value: 0.5555505565967757.
[I 2025-07-11 22:29:51,900] Trial 9 finished with value: 0.5134478185511181 and parameters: {'alpha': 0.14598501098187372, 'l1_ratio': 0.5503689536327021}. Best is trial 2 with value: 0.5555505565967757.

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.40 | R2: 0.52
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.42 | R2: 0.51
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.339e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.367e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.378e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.802e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.651e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 22:29:52,066] Trial 10 finished with value: 0.4239868432098405 and parameters: {'alpha': 0.00015072730882520342, 'l1_ratio': 0.2461582583563006}. Best is trial 2 with value: 0.5555505565967757.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.153e+00, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.653e+00, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.159e+01, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.304e+00, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(

Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 2.63 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.34 | R2: 0.54

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.014e+00, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 22:29:52,213] Trial 11 finished with value: 0.5425743704246254 and parameters: {'alpha': 0.0063987223672948524, 'l1_ratio': 0.8035599862539616}. Best is trial 2 with value: 0.5555505565967757.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.834e+01, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.357e+01, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.529e+01, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.337e+01, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.051e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 22:29:52,361] Trial 12 finished with value: 0.5578438050337132 and parameters: {'alpha': 0.008208159924226516, 'l1_ratio': 0.3441387587683665}. Best is trial 12 with value: 0.5578438050337132.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.011e+01, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.31 | R2: 0.56
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.502e+01, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.922e+00, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.818e+01, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.107e+01, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 22:29:52,493] Trial 13 finished with value: 0.5589104641462681 and parameters: {'alpha': 0.011165270933831161, 'l1_ratio': 0.351341829029843}. Best is trial 13 with value: 0.5589104641462681.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.952e-01, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.817e-01, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.871e-01, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.473e+00, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 22:29:52,624] Trial 14 finished with value: 0.5553668954596351 and parameters: {'alpha': 0.02381397198152183, 'l1_ratio': 0.3683810311842875}. Best is trial 13 with value: 0.5589104641462681.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.30 | R2: 0.56
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.31 | R2: 0.56
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.445e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.870e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.717e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.366e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.517e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 22:29:52,771] Trial 15 finished with value: 0.4595349025597716 and parameters: {'alpha': 0.0006940348004314978, 'l1_ratio': 0.3823883696308937}. Best is trial 13 with value: 0.5589104641462681.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.486e-01, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.55 | R2: 0.46
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.346e+00, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 22:29:52,907] Trial 16 finished with value: 0.5553159458204681 and parameters: {'alpha': 0.02307263943893847, 'l1_ratio': 0.4110216047882573}. Best is trial 13 with value: 0.5589104641462681.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.337e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.383e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.337e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.823e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.929e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 22:29:53,038] Trial 17 finished with value: 0.4864296325121805 and parameters: {'alpha': 0.0008970211218765732, 'l1_ratio': 0.05284586324268703}. Best is trial 13 with value: 0.5589104641462681.

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.31 | R2: 0.56
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.48 | R2: 0.49
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.124e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.440e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.431e+01, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.153e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.291e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 22:29:53,176] Trial 18 finished with value: 0.5315650048126286 and parameters: {'alpha': 0.002436841456669119, 'l1_ratio': 0.2681784349005135}. Best is trial 13 with value: 0.5589104641462681.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.104e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.257e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.37 | R2: 0.53
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.247e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.708e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.597e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 22:29:53,355] Trial 19 finished with value: 0.42463639416130994 and parameters: {'alpha': 0.00019131699353069982, 'l1_ratio': 0.4407335456891019}. Best is trial 13 with value: 0.5589104641462681.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.973e-01, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.112e-01, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.768e-01, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(

Fold 5
Running time: 0.2 sec
OOF RMSE: 2.63 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.191e-01, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.799e+00, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 22:29:53,548] Trial 20 finished with value: 0.5557179669386356 and parameters: {'alpha': 0.012130188540454678, 'l1_ratio': 0.6653179435986392}. Best is trial 13 with value: 0.5589104641462681.
[I 2025-07-11 22:29:53,678] Trial 21 finished with value: 0.5452244541900857 and parameters: {'alpha': 0.048316570367486225, 'l1_ratio': 0.6607405190465532}. Best is trial 13 with value: 0.5589104641462681.

Running time: 0.2 sec
OOF RMSE: 2.31 | R2: 0.56
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.34 | R2: 0.55
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.435e-01, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.447e-01, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.989e-01, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 22:29:53,887] Trial 22 finished with value: 0.5538183509114027 and parameters: {'alpha': 0.012219837872194945, 'l1_ratio': 0.8090817070969375}. Best is trial 13 with value: 0.5589104641462681.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.504e+01, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(

Fold 3
Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 2.32 | R2: 0.55
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.549e+01, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.617e+01, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.565e+01, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.827e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 22:29:54,056] Trial 23 finished with value: 0.5262003945635836 and parameters: {'alpha': 0.0026937327334618268, 'l1_ratio': 0.47146591368814217}. Best is trial 13 with value: 0.5589104641462681.
[I 2025-07-11 22:29:54,158] Trial 24 finished with value: 0.4811274251909845 and parameters: {'alpha': 0.2910282401302988, 'l1_ratio': 0.7509687217519323}. Best is trial 13 with value: 0.5589104641462681.
[I 2025-07-11 22:29:54,160] A new study created in memory with name: no-name-556ea527-2d69-4eec-9526-b456da9f5a4c

Fold 3
Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 2.39 | R2: 0.53
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.50 | R2: 0.48

✅ EN - Mejor R2: 0.56
📋 Parámetros: {'alpha': 0.011165270933831161, 'l1_ratio': 0.351341829029843}

🔍 Optimizando en C2X-Complex_rhow_1x1_depth_lt_1...
Buscando mejores hiperparámetros para XGB...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:30:02,833] Trial 0 finished with value: 0.3219976193534547 and parameters: {'n_estimators': 2000, 'learning_rate': 0.0801491243678856, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.9740497281989171, 'colsample_bytree': 0.8461855173766172}. Best is trial 0 with value: 0.3219976193534547.

Running time: 8.7 sec
OOF RMSE: 2.85 | R2: 0.32
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:30:07,372] Trial 1 finished with value: 0.4234830739715263 and parameters: {'n_estimators': 1000, 'learning_rate': 0.04188364976141168, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.8718417017129734, 'colsample_bytree': 0.6131305575856439}. Best is trial 1 with value: 0.4234830739715263.

Running time: 4.5 sec
OOF RMSE: 2.63 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:30:10,533] Trial 2 finished with value: 0.4282839394293465 and parameters: {'n_estimators': 500, 'learning_rate': 0.061368710871117504, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.7847819422660591, 'colsample_bytree': 0.8192471650270031}. Best is trial 2 with value: 0.4282839394293465.

Running time: 3.2 sec
OOF RMSE: 2.62 | R2: 0.43
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:30:14,100] Trial 3 finished with value: 0.48486623847035826 and parameters: {'n_estimators': 500, 'learning_rate': 0.014416997200499252, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.6298406037487735, 'colsample_bytree': 0.6854705819958173}. Best is trial 3 with value: 0.48486623847035826.

Running time: 3.6 sec
OOF RMSE: 2.49 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:30:19,654] Trial 4 finished with value: 0.4570029097201579 and parameters: {'n_estimators': 1000, 'learning_rate': 0.05787399178608586, 'max_depth': 5, 'min_child_weight': 1, 'subsample': 0.6714754057370468, 'colsample_bytree': 0.9196614756512642}. Best is trial 3 with value: 0.48486623847035826.

Running time: 5.5 sec
OOF RMSE: 2.55 | R2: 0.46
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:30:22,961] Trial 5 finished with value: 0.4379617332233049 and parameters: {'n_estimators': 500, 'learning_rate': 0.02218757074989704, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.8697128298199781, 'colsample_bytree': 0.6626469134499475}. Best is trial 3 with value: 0.48486623847035826.

Running time: 3.3 sec
OOF RMSE: 2.60 | R2: 0.44
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:30:25,711] Trial 6 finished with value: 0.4291886920062389 and parameters: {'n_estimators': 500, 'learning_rate': 0.011523897615508724, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.8786822021268124, 'colsample_bytree': 0.9517570138692205}. Best is trial 3 with value: 0.48486623847035826.

Running time: 2.7 sec
OOF RMSE: 2.62 | R2: 0.43
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:30:32,170] Trial 7 finished with value: 0.42903380656716494 and parameters: {'n_estimators': 1000, 'learning_rate': 0.00840241471196906, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.7672632011344647, 'colsample_bytree': 0.8564234471883522}. Best is trial 3 with value: 0.48486623847035826.

Running time: 6.5 sec
OOF RMSE: 2.62 | R2: 0.43
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:30:34,801] Trial 8 finished with value: 0.44908141509780286 and parameters: {'n_estimators': 500, 'learning_rate': 0.013965588561956635, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.6138949483817168, 'colsample_bytree': 0.9399817555606422}. Best is trial 3 with value: 0.48486623847035826.

Running time: 2.6 sec
OOF RMSE: 2.57 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:30:40,095] Trial 9 finished with value: 0.4004875904521791 and parameters: {'n_estimators': 1000, 'learning_rate': 0.07470474165090363, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.8495045309406718, 'colsample_bytree': 0.7496307109178277}. Best is trial 3 with value: 0.48486623847035826.

Running time: 5.3 sec
OOF RMSE: 2.68 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:30:54,937] Trial 10 finished with value: 0.457914563629334 and parameters: {'n_estimators': 2000, 'learning_rate': 0.005701444437856871, 'max_depth': 8, 'min_child_weight': 2, 'subsample': 0.6999069173909075, 'colsample_bytree': 0.7229912476645178}. Best is trial 3 with value: 0.48486623847035826.

Running time: 14.8 sec
OOF RMSE: 2.55 | R2: 0.46
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:31:09,722] Trial 11 finished with value: 0.4629132460475176 and parameters: {'n_estimators': 2000, 'learning_rate': 0.005271548863593187, 'max_depth': 8, 'min_child_weight': 2, 'subsample': 0.6939906272508368, 'colsample_bytree': 0.7173470196439053}. Best is trial 3 with value: 0.48486623847035826.

Running time: 14.8 sec
OOF RMSE: 2.54 | R2: 0.46
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:31:23,525] Trial 12 finished with value: 0.47131703258663415 and parameters: {'n_estimators': 2000, 'learning_rate': 0.005179053597930256, 'max_depth': 8, 'min_child_weight': 2, 'subsample': 0.602413156921346, 'colsample_bytree': 0.7051513656659928}. Best is trial 3 with value: 0.48486623847035826.

Running time: 13.8 sec
OOF RMSE: 2.52 | R2: 0.47
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:31:36,693] Trial 13 finished with value: 0.49722414149953276 and parameters: {'n_estimators': 2000, 'learning_rate': 0.024400255985351765, 'max_depth': 8, 'min_child_weight': 1, 'subsample': 0.608137203613479, 'colsample_bytree': 0.6610967245634896}. Best is trial 13 with value: 0.49722414149953276.

Running time: 13.2 sec
OOF RMSE: 2.46 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:31:40,795] Trial 14 finished with value: 0.4865705415629481 and parameters: {'n_estimators': 500, 'learning_rate': 0.026169437565351332, 'max_depth': 8, 'min_child_weight': 1, 'subsample': 0.6580108275616294, 'colsample_bytree': 0.6153333799668353}. Best is trial 13 with value: 0.49722414149953276.

Running time: 4.1 sec
OOF RMSE: 2.48 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:31:51,970] Trial 15 finished with value: 0.4686106982025283 and parameters: {'n_estimators': 2000, 'learning_rate': 0.026624953526610547, 'max_depth': 8, 'min_child_weight': 1, 'subsample': 0.7157808979899082, 'colsample_bytree': 0.6016511672241308}. Best is trial 13 with value: 0.49722414149953276.

Running time: 11.2 sec
OOF RMSE: 2.53 | R2: 0.47
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:31:56,540] Trial 16 finished with value: 0.46814559919503895 and parameters: {'n_estimators': 500, 'learning_rate': 0.029088958028760863, 'max_depth': 8, 'min_child_weight': 1, 'subsample': 0.6543412860987868, 'colsample_bytree': 0.7708790193844963}. Best is trial 13 with value: 0.49722414149953276.

Running time: 4.6 sec
OOF RMSE: 2.53 | R2: 0.47
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:32:06,360] Trial 17 finished with value: 0.45989626191276767 and parameters: {'n_estimators': 2000, 'learning_rate': 0.03710345914329563, 'max_depth': 8, 'min_child_weight': 1, 'subsample': 0.7389702041533043, 'colsample_bytree': 0.6427153140577566}. Best is trial 13 with value: 0.49722414149953276.

Running time: 9.8 sec
OOF RMSE: 2.55 | R2: 0.46
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:32:09,199] Trial 18 finished with value: 0.4905522514126507 and parameters: {'n_estimators': 500, 'learning_rate': 0.019380047330368393, 'max_depth': 6, 'min_child_weight': 1, 'subsample': 0.657671771568407, 'colsample_bytree': 0.6392088243617587}. Best is trial 13 with value: 0.49722414149953276.

Running time: 2.8 sec
OOF RMSE: 2.47 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:32:21,490] Trial 19 finished with value: 0.4271782032800647 and parameters: {'n_estimators': 2000, 'learning_rate': 0.019327569791742716, 'max_depth': 6, 'min_child_weight': 1, 'subsample': 0.8291812554841613, 'colsample_bytree': 0.7826485412881692}. Best is trial 13 with value: 0.49722414149953276.

Running time: 12.3 sec
OOF RMSE: 2.62 | R2: 0.43
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:32:32,764] Trial 20 finished with value: 0.40606831763979967 and parameters: {'n_estimators': 2000, 'learning_rate': 0.017213462919694236, 'max_depth': 6, 'min_child_weight': 1, 'subsample': 0.9799511273149873, 'colsample_bytree': 0.6573066658908282}. Best is trial 13 with value: 0.49722414149953276.

Running time: 11.3 sec
OOF RMSE: 2.67 | R2: 0.41
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:32:36,169] Trial 21 finished with value: 0.4964291010452453 and parameters: {'n_estimators': 500, 'learning_rate': 0.04342874790946295, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.6502616324076819, 'colsample_bytree': 0.6313909867818288}. Best is trial 13 with value: 0.49722414149953276.

Running time: 3.4 sec
OOF RMSE: 2.46 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:32:40,639] Trial 22 finished with value: 0.49886333249528925 and parameters: {'n_estimators': 500, 'learning_rate': 0.038343998389647464, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.6399253488068783, 'colsample_bytree': 0.6771170914959754}. Best is trial 22 with value: 0.49886333249528925.

Running time: 4.5 sec
OOF RMSE: 2.45 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:32:44,631] Trial 23 finished with value: 0.48694615871234326 and parameters: {'n_estimators': 500, 'learning_rate': 0.04273263406356634, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.6301610144766383, 'colsample_bytree': 0.6818368743486755}. Best is trial 22 with value: 0.49886333249528925.

Running time: 4.0 sec
OOF RMSE: 2.48 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:32:48,492] Trial 24 finished with value: 0.4121154532909179 and parameters: {'n_estimators': 500, 'learning_rate': 0.03441845190462299, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.723748264166308, 'colsample_bytree': 0.9931237270329938}. Best is trial 22 with value: 0.49886333249528925.
[I 2025-07-11 22:32:48,493] A new study created in memory with name: no-name-c68fea28-4ded-431c-a72f-53bcf942c847

Running time: 3.9 sec
OOF RMSE: 2.66 | R2: 0.41

✅ XGB - Mejor R2: 0.50
📋 Parámetros: {'n_estimators': 500, 'learning_rate': 0.038343998389647464, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.6399253488068783, 'colsample_bytree': 0.6771170914959754}

Buscando mejores hiperparámetros para LBM...
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 22:32:49,074] Trial 0 finished with value: 0.4809122681104464 and parameters: {'learning_rate': 0.03701754294271261, 'num_leaves': 40, 'max_depth': 5, 'min_child_samples': 7, 'subsample': 0.7865906464740318, 'colsample_bytree': 0.877836238300584, 'n_estimators': 1000}. Best is trial 0 with value: 0.4809122681104464.

Fold 5
Running time: 0.6 sec
OOF RMSE: 2.50 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:32:50,152] Trial 1 finished with value: 0.371974581133075 and parameters: {'learning_rate': 0.035665957212370945, 'num_leaves': 40, 'max_depth': 8, 'min_child_samples': 18, 'subsample': 0.6576663666952813, 'colsample_bytree': 0.6212464217807271, 'n_estimators': 2000}. Best is trial 0 with value: 0.4809122681104464.

Running time: 1.1 sec
OOF RMSE: 2.75 | R2: 0.37
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:32:50,650] Trial 2 finished with value: 0.3628980323473363 and parameters: {'learning_rate': 0.06896580810370494, 'num_leaves': 40, 'max_depth': 5, 'min_child_samples': 11, 'subsample': 0.6474863485979975, 'colsample_bytree': 0.8613154968025687, 'n_estimators': 1000}. Best is trial 0 with value: 0.4809122681104464.

Running time: 0.5 sec
OOF RMSE: 2.77 | R2: 0.36
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:32:51,993] Trial 3 finished with value: 0.42280698329557087 and parameters: {'learning_rate': 0.008975113229318337, 'num_leaves': 40, 'max_depth': 8, 'min_child_samples': 9, 'subsample': 0.7315601611826155, 'colsample_bytree': 0.9164941793399948, 'n_estimators': 2000}. Best is trial 0 with value: 0.4809122681104464.

Running time: 1.3 sec
OOF RMSE: 2.63 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 22:32:52,275] Trial 4 finished with value: 0.4355633327412427 and parameters: {'learning_rate': 0.014110354380850513, 'num_leaves': 60, 'max_depth': 6, 'min_child_samples': 22, 'subsample': 0.9811912088788153, 'colsample_bytree': 0.6300288098668924, 'n_estimators': 500}. Best is trial 0 with value: 0.4809122681104464.

Fold 5
Running time: 0.3 sec
OOF RMSE: 2.60 | R2: 0.44
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 22:32:52,827] Trial 5 finished with value: 0.3810288946485181 and parameters: {'learning_rate': 0.0190592986274004, 'num_leaves': 80, 'max_depth': 6, 'min_child_samples': 12, 'subsample': 0.742187023657888, 'colsample_bytree': 0.9442650511034798, 'n_estimators': 1000}. Best is trial 0 with value: 0.4809122681104464.

Fold 5
Running time: 0.5 sec
OOF RMSE: 2.73 | R2: 0.38
Fold 1
Fold 2

[I 2025-07-11 22:32:53,130] Trial 6 finished with value: 0.4196235835769363 and parameters: {'learning_rate': 0.03717004809718294, 'num_leaves': 40, 'max_depth': 5, 'min_child_samples': 8, 'subsample': 0.8057498138752563, 'colsample_bytree': 0.893776977334666, 'n_estimators': 500}. Best is trial 0 with value: 0.4809122681104464.

Fold 3
Fold 4
Fold 5
Running time: 0.3 sec
OOF RMSE: 2.64 | R2: 0.42
Fold 1
Fold 2
Fold 3

[I 2025-07-11 22:32:53,622] Trial 7 finished with value: 0.43849892871537055 and parameters: {'learning_rate': 0.03667363595825876, 'num_leaves': 80, 'max_depth': 7, 'min_child_samples': 24, 'subsample': 0.7273548842268688, 'colsample_bytree': 0.6446859285372181, 'n_estimators': 1000}. Best is trial 0 with value: 0.4809122681104464.

Fold 4
Fold 5
Running time: 0.5 sec
OOF RMSE: 2.60 | R2: 0.44
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:32:54,301] Trial 8 finished with value: 0.3553113233504902 and parameters: {'learning_rate': 0.019985312592565006, 'num_leaves': 80, 'max_depth': 8, 'min_child_samples': 11, 'subsample': 0.7123787409357314, 'colsample_bytree': 0.7330531126395025, 'n_estimators': 1000}. Best is trial 0 with value: 0.4809122681104464.

Running time: 0.7 sec
OOF RMSE: 2.78 | R2: 0.36
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:32:54,558] Trial 9 finished with value: 0.4438673522510109 and parameters: {'learning_rate': 0.008799886315721756, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 24, 'subsample': 0.7558301505032836, 'colsample_bytree': 0.9165792288219906, 'n_estimators': 500}. Best is trial 0 with value: 0.4809122681104464.

Running time: 0.3 sec
OOF RMSE: 2.59 | R2: 0.44
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 22:32:55,382] Trial 10 finished with value: 0.4530537737725051 and parameters: {'learning_rate': 0.09413542239967879, 'num_leaves': 60, 'max_depth': 6, 'min_child_samples': 5, 'subsample': 0.8684945495292509, 'colsample_bytree': 0.8008920188683192, 'n_estimators': 1000}. Best is trial 0 with value: 0.4809122681104464.

Fold 5
Running time: 0.8 sec
OOF RMSE: 2.56 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:32:56,157] Trial 11 finished with value: 0.4605454207929851 and parameters: {'learning_rate': 0.07874289552262563, 'num_leaves': 60, 'max_depth': 6, 'min_child_samples': 5, 'subsample': 0.8610670111948597, 'colsample_bytree': 0.789842595325844, 'n_estimators': 1000}. Best is trial 0 with value: 0.4809122681104464.

Running time: 0.8 sec
OOF RMSE: 2.55 | R2: 0.46
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 22:32:57,028] Trial 12 finished with value: 0.4586773063943711 and parameters: {'learning_rate': 0.05681416870085012, 'num_leaves': 60, 'max_depth': 7, 'min_child_samples': 5, 'subsample': 0.8758686239368298, 'colsample_bytree': 0.8064146324932737, 'n_estimators': 1000}. Best is trial 0 with value: 0.4809122681104464.

Fold 5
Running time: 0.9 sec
OOF RMSE: 2.55 | R2: 0.46
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 22:32:57,491] Trial 13 finished with value: 0.4325842755796572 and parameters: {'learning_rate': 0.09877528553715852, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 16, 'subsample': 0.8543000145848723, 'colsample_bytree': 0.7386581593495042, 'n_estimators': 1000}. Best is trial 0 with value: 0.4809122681104464.

Fold 5
Running time: 0.5 sec
OOF RMSE: 2.61 | R2: 0.43
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:32:58,194] Trial 14 finished with value: 0.4495894716573101 and parameters: {'learning_rate': 0.05488490683189902, 'num_leaves': 60, 'max_depth': 6, 'min_child_samples': 7, 'subsample': 0.9190741689876466, 'colsample_bytree': 0.9864587354548222, 'n_estimators': 1000}. Best is trial 0 with value: 0.4809122681104464.

Running time: 0.7 sec
OOF RMSE: 2.57 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:32:59,696] Trial 15 finished with value: 0.4522976231094388 and parameters: {'learning_rate': 0.03366375271737532, 'num_leaves': 40, 'max_depth': 7, 'min_child_samples': 5, 'subsample': 0.8080330777308867, 'colsample_bytree': 0.7360648999683271, 'n_estimators': 2000}. Best is trial 0 with value: 0.4809122681104464.

Running time: 1.5 sec
OOF RMSE: 2.57 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 22:33:00,208] Trial 16 finished with value: 0.4343827364655488 and parameters: {'learning_rate': 0.005187899254013981, 'num_leaves': 60, 'max_depth': 5, 'min_child_samples': 14, 'subsample': 0.9448476936035457, 'colsample_bytree': 0.8603923223711385, 'n_estimators': 1000}. Best is trial 0 with value: 0.4809122681104464.

Fold 5
Running time: 0.5 sec
OOF RMSE: 2.61 | R2: 0.43
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:33:00,820] Trial 17 finished with value: 0.4201063042898626 and parameters: {'learning_rate': 0.05501982158592278, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 8, 'subsample': 0.8273018703369475, 'colsample_bytree': 0.828607565979812, 'n_estimators': 1000}. Best is trial 0 with value: 0.4809122681104464.

Running time: 0.6 sec
OOF RMSE: 2.64 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 22:33:01,676] Trial 18 finished with value: 0.44947375985789073 and parameters: {'learning_rate': 0.027484457419970097, 'num_leaves': 40, 'max_depth': 5, 'min_child_samples': 20, 'subsample': 0.9035381946482227, 'colsample_bytree': 0.7689830791373248, 'n_estimators': 2000}. Best is trial 0 with value: 0.4809122681104464.

Fold 5
Running time: 0.9 sec
OOF RMSE: 2.57 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 22:33:02,003] Trial 19 finished with value: 0.4574600364631527 and parameters: {'learning_rate': 0.06835094468684029, 'num_leaves': 60, 'max_depth': 6, 'min_child_samples': 15, 'subsample': 0.7769483342506711, 'colsample_bytree': 0.847081883876382, 'n_estimators': 500}. Best is trial 0 with value: 0.4809122681104464.

Fold 5
Running time: 0.3 sec
OOF RMSE: 2.55 | R2: 0.46
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:33:02,627] Trial 20 finished with value: 0.3443570957243731 and parameters: {'learning_rate': 0.04708636462278648, 'num_leaves': 60, 'max_depth': 7, 'min_child_samples': 10, 'subsample': 0.6022775544168006, 'colsample_bytree': 0.6852963314549455, 'n_estimators': 1000}. Best is trial 0 with value: 0.4809122681104464.

Running time: 0.6 sec
OOF RMSE: 2.81 | R2: 0.34
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:33:03,441] Trial 21 finished with value: 0.4506842831250567 and parameters: {'learning_rate': 0.07312805377548365, 'num_leaves': 60, 'max_depth': 7, 'min_child_samples': 6, 'subsample': 0.8691893452173044, 'colsample_bytree': 0.7986993086748488, 'n_estimators': 1000}. Best is trial 0 with value: 0.4809122681104464.

Running time: 0.8 sec
OOF RMSE: 2.57 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 22:33:04,234] Trial 22 finished with value: 0.45675236572285527 and parameters: {'learning_rate': 0.04557000863629465, 'num_leaves': 60, 'max_depth': 7, 'min_child_samples': 5, 'subsample': 0.8946946019190329, 'colsample_bytree': 0.800529210528454, 'n_estimators': 1000}. Best is trial 0 with value: 0.4809122681104464.

Fold 5
Running time: 0.8 sec
OOF RMSE: 2.56 | R2: 0.46
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:33:04,915] Trial 23 finished with value: 0.4460554650814844 and parameters: {'learning_rate': 0.028495971141412016, 'num_leaves': 60, 'max_depth': 7, 'min_child_samples': 7, 'subsample': 0.8416305906841738, 'colsample_bytree': 0.6890682983313838, 'n_estimators': 1000}. Best is trial 0 with value: 0.4809122681104464.

Running time: 0.7 sec
OOF RMSE: 2.58 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 22:33:05,488] Trial 24 finished with value: 0.40008933374095523 and parameters: {'learning_rate': 0.07698968065331024, 'num_leaves': 60, 'max_depth': 6, 'min_child_samples': 13, 'subsample': 0.9526096417822935, 'colsample_bytree': 0.8820299550114729, 'n_estimators': 1000}. Best is trial 0 with value: 0.4809122681104464.
[I 2025-07-11 22:33:05,489] A new study created in memory with name: no-name-721cc734-b23a-45be-ad54-c08255c9b1fc

Fold 5
Running time: 0.6 sec
OOF RMSE: 2.68 | R2: 0.40

✅ LBM - Mejor R2: 0.48
📋 Parámetros: {'learning_rate': 0.03701754294271261, 'num_leaves': 40, 'max_depth': 5, 'min_child_samples': 7, 'subsample': 0.7865906464740318, 'colsample_bytree': 0.877836238300584, 'n_estimators': 1000}

Buscando mejores hiperparámetros para MLP...
Fold 1
Fold 2
Fold 3

[I 2025-07-11 22:33:05,886] Trial 0 finished with value: 0.2294765218344359 and parameters: {'hidden_layer_sizes': '50', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.001966640333428694, 'learning_rate': 'constant', 'learning_rate_init': 0.007688263141006626}. Best is trial 0 with value: 0.2294765218344359.

Fold 4
Fold 5
Running time: 0.4 sec
OOF RMSE: 3.04 | R2: 0.23
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 22:33:07,713] Trial 1 finished with value: 0.5047713566631999 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0010556994151902804, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0008348386799865321}. Best is trial 1 with value: 0.5047713566631999.

Running time: 1.8 sec
OOF RMSE: 2.44 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 22:33:08,339] Trial 2 finished with value: 0.41809841310240603 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.09304810756653649, 'learning_rate': 'adaptive', 'learning_rate_init': 0.004605291983202622}. Best is trial 1 with value: 0.5047713566631999.

Fold 5
Running time: 0.6 sec
OOF RMSE: 2.64 | R2: 0.42
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 22:33:10,999] Trial 3 finished with value: 0.42390546881998437 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 1.349740669249776e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0006361255996173711}. Best is trial 1 with value: 0.5047713566631999.

Running time: 2.7 sec
OOF RMSE: 2.63 | R2: 0.42
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 22:33:13,655] Trial 4 finished with value: 0.3053692536670076 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 6.420394690083595e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.00010410623959846656}. Best is trial 1 with value: 0.5047713566631999.

Running time: 2.6 sec
OOF RMSE: 2.89 | R2: 0.31
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:33:14,738] Trial 5 finished with value: 0.46390195187526073 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0003535940042935226, 'learning_rate': 'constant', 'learning_rate_init': 0.0016825053515192563}. Best is trial 1 with value: 0.5047713566631999.

Running time: 1.1 sec
OOF RMSE: 2.54 | R2: 0.46
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:33:15,404] Trial 6 finished with value: 0.2761663462795957 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 1.3059084364339424e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.008443255819872781}. Best is trial 1 with value: 0.5047713566631999.

Running time: 0.7 sec
OOF RMSE: 2.95 | R2: 0.28
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 22:33:17,604] Trial 7 finished with value: 0.4443123488616021 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 2.0439120933727857e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.000158242669665783}. Best is trial 1 with value: 0.5047713566631999.

Running time: 2.2 sec
OOF RMSE: 2.58 | R2: 0.44
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 22:33:20,067] Trial 8 finished with value: 0.4392362670694058 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0002770293094387016, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0002813017773497651}. Best is trial 1 with value: 0.5047713566631999.

Running time: 2.5 sec
OOF RMSE: 2.60 | R2: 0.44
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 22:33:22,126] Trial 9 finished with value: 0.4317124143304665 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.019923917467746684, 'learning_rate': 'constant', 'learning_rate_init': 0.0011041654003925566}. Best is trial 1 with value: 0.5047713566631999.

Running time: 2.1 sec
OOF RMSE: 2.61 | R2: 0.43
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 22:33:23,593] Trial 10 finished with value: 0.4124077341693505 and parameters: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.006491731621750397, 'learning_rate': 'adaptive', 'learning_rate_init': 0.002682197000856433}. Best is trial 1 with value: 0.5047713566631999.

Running time: 1.5 sec
OOF RMSE: 2.66 | R2: 0.41
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 22:33:24,601] Trial 11 finished with value: 0.4376892903676092 and parameters: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.000411457846806511, 'learning_rate': 'constant', 'learning_rate_init': 0.0014133051062520565}. Best is trial 1 with value: 0.5047713566631999.

Running time: 1.0 sec
OOF RMSE: 2.60 | R2: 0.44
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

[I 2025-07-11 22:33:25,794] Trial 12 finished with value: 0.26434248658096227 and parameters: {'hidden_layer_sizes': '50', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0013455626242889348, 'learning_rate': 'constant', 'learning_rate_init': 0.0005298198412406701}. Best is trial 1 with value: 0.5047713566631999.

Running time: 1.2 sec
OOF RMSE: 2.97 | R2: 0.26
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 22:33:26,773] Trial 13 finished with value: 0.42944746539682754 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.00020297985306472576, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0021283250431578045}. Best is trial 1 with value: 0.5047713566631999.

Fold 5
Running time: 1.0 sec
OOF RMSE: 2.62 | R2: 0.43
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 22:33:28,539] Trial 14 finished with value: 0.500293404761641 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0042853356450007025, 'learning_rate': 'constant', 'learning_rate_init': 0.0005521708358253527}. Best is trial 1 with value: 0.5047713566631999.

Running time: 1.8 sec
OOF RMSE: 2.45 | R2: 0.50
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 22:33:30,121] Trial 15 finished with value: 0.500482525262856 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.004765974253229401, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0005567238343029981}. Best is trial 1 with value: 0.5047713566631999.

Running time: 1.6 sec
OOF RMSE: 2.45 | R2: 0.50
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 22:33:32,105] Trial 16 finished with value: 0.49043755060569716 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.014920441473514595, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00032152729896640946}. Best is trial 1 with value: 0.5047713566631999.

Running time: 2.0 sec
OOF RMSE: 2.47 | R2: 0.49
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 22:33:33,874] Trial 17 finished with value: 0.505002809459469 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.06341136672575416, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0008472157175144302}. Best is trial 17 with value: 0.505002809459469.

Running time: 1.8 sec
OOF RMSE: 2.44 | R2: 0.51
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 22:33:35,944] Trial 18 finished with value: 0.4615575820245541 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.07113883375896946, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0008584224873566756}. Best is trial 17 with value: 0.505002809459469.

Running time: 2.1 sec
OOF RMSE: 2.54 | R2: 0.46
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 22:33:37,993] Trial 19 finished with value: 0.4845035332249926 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.029452116665648273, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0002777355886463371}. Best is trial 17 with value: 0.505002809459469.

Running time: 2.0 sec
OOF RMSE: 2.49 | R2: 0.48
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 22:33:38,785] Trial 20 finished with value: 0.2458196653910839 and parameters: {'hidden_layer_sizes': '50', 'activation': 'tanh', 'solver': 'adam', 'alpha': 6.802134350293884e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0029928456137328207}. Best is trial 17 with value: 0.505002809459469.

Fold 4
Fold 5
Running time: 0.8 sec
OOF RMSE: 3.01 | R2: 0.25
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 22:33:40,735] Trial 21 finished with value: 0.4955202070114707 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0040778195999198194, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00041066246676477235}. Best is trial 17 with value: 0.505002809459469.

Running time: 1.9 sec
OOF RMSE: 2.46 | R2: 0.50
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 22:33:42,493] Trial 22 finished with value: 0.5046133390522463 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0009229381713266683, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0008822923431602585}. Best is trial 17 with value: 0.505002809459469.

Running time: 1.8 sec
OOF RMSE: 2.44 | R2: 0.50
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 22:33:44,183] Trial 23 finished with value: 0.5050942864971422 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0007558561979271034, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0009042654486051293}. Best is trial 23 with value: 0.5050942864971422.

Running time: 1.7 sec
OOF RMSE: 2.44 | R2: 0.51
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 22:33:45,484] Trial 24 finished with value: 0.49905330373482903 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.00010271403759428603, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0013185629637190639}. Best is trial 23 with value: 0.5050942864971422.
[I 2025-07-11 22:33:45,485] A new study created in memory with name: no-name-cf994a22-9c63-4837-856c-f9731881d938
[I 2025-07-11 22:33:45,578] Trial 0 finished with value: 0.4301140197471356 and parameters: {'kernel': 'rbf', 'C': 9.688457231821618, 'epsilon': 0.1598193809127412, 'gamma': 'scale'}. Best is trial 0 with value: 0.4301140197471356.
[I 2025-07-11 22:33:45,660] Trial 1 finished with value: -1.5042950617609114 and parameters: {'kernel': 'sigmoid', 'C': 0.7805289976660815, 'epsilon': 0.13564281728302308, 'gamma': 'scale'}. Best is trial 0 with value: 0.4301140197471356.

Running time: 1.3 sec
OOF RMSE: 2.45 | R2: 0.50

✅ MLP - Mejor R2: 0.51
📋 Parámetros: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0007558561979271034, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0009042654486051293}

Buscando mejores hiperparámetros para SVR...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.62 | R2: 0.43
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 5.49 | R2: -1.50
Fold 1
Fold 2

[I 2025-07-11 22:33:45,732] Trial 2 finished with value: -100.6097648025228 and parameters: {'kernel': 'sigmoid', 'C': 6.579148696766872, 'epsilon': 0.15687322428655465, 'gamma': 'auto'}. Best is trial 0 with value: 0.4301140197471356.
[I 2025-07-11 22:33:45,806] Trial 3 finished with value: -6.465514965750189 and parameters: {'kernel': 'sigmoid', 'C': 1.653081488798211, 'epsilon': 0.1924622308551163, 'gamma': 'scale'}. Best is trial 0 with value: 0.4301140197471356.
[I 2025-07-11 22:33:45,888] Trial 4 finished with value: 0.42451755217399967 and parameters: {'kernel': 'rbf', 'C': 9.098704700384086, 'epsilon': 0.08387932687497697, 'gamma': 'auto'}. Best is trial 0 with value: 0.4301140197471356.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 34.94 | R2: -100.61
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 9.47 | R2: -6.47
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.63 | R2: 0.42
Fold 1

[I 2025-07-11 22:33:45,966] Trial 5 finished with value: 0.30837489369250126 and parameters: {'kernel': 'rbf', 'C': 3.067336254579992, 'epsilon': 0.10932684853095118, 'gamma': 'auto'}. Best is trial 0 with value: 0.4301140197471356.
[I 2025-07-11 22:33:46,033] Trial 6 finished with value: 0.025670141691061632 and parameters: {'kernel': 'rbf', 'C': 0.1036310903319453, 'epsilon': 0.1454594426346285, 'gamma': 'scale'}. Best is trial 0 with value: 0.4301140197471356.
[I 2025-07-11 22:33:46,104] Trial 7 finished with value: 0.028229249703528247 and parameters: {'kernel': 'rbf', 'C': 0.11654999385547012, 'epsilon': 0.109499488010641, 'gamma': 'auto'}. Best is trial 0 with value: 0.4301140197471356.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.88 | R2: 0.31
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.42 | R2: 0.03
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.42 | R2: 0.03
Fold 1

[I 2025-07-11 22:33:46,179] Trial 8 finished with value: 0.05869380899404497 and parameters: {'kernel': 'rbf', 'C': 0.19488240985981278, 'epsilon': 0.03203679527093236, 'gamma': 'scale'}. Best is trial 0 with value: 0.4301140197471356.
[I 2025-07-11 22:33:46,265] Trial 9 finished with value: 0.31086723098403124 and parameters: {'kernel': 'rbf', 'C': 3.0523677047118594, 'epsilon': 0.12504535270360578, 'gamma': 'scale'}. Best is trial 0 with value: 0.4301140197471356.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.36 | R2: 0.06
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.88 | R2: 0.31
Fold 1
Fold 2
Fold 3

[I 2025-07-11 22:33:46,361] Trial 10 finished with value: -0.17444516538423138 and parameters: {'kernel': 'sigmoid', 'C': 0.4170657381499474, 'epsilon': 0.19997068458268702, 'gamma': 'scale'}. Best is trial 0 with value: 0.4301140197471356.
[I 2025-07-11 22:33:46,454] Trial 11 finished with value: 0.4290725983304199 and parameters: {'kernel': 'rbf', 'C': 9.787805948301502, 'epsilon': 0.06301984152756603, 'gamma': 'auto'}. Best is trial 0 with value: 0.4301140197471356.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.76 | R2: -0.17
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.62 | R2: 0.43
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:33:46,539] Trial 12 finished with value: 0.36700402584924763 and parameters: {'kernel': 'rbf', 'C': 4.603786095584652, 'epsilon': 0.06257011985185985, 'gamma': 'auto'}. Best is trial 0 with value: 0.4301140197471356.
[I 2025-07-11 22:33:46,627] Trial 13 finished with value: 0.4300339427788973 and parameters: {'kernel': 'rbf', 'C': 9.662032413970916, 'epsilon': 0.010306646706811369, 'gamma': 'auto'}. Best is trial 0 with value: 0.4301140197471356.
[I 2025-07-11 22:33:46,710] Trial 14 finished with value: 0.24330602949685676 and parameters: {'kernel': 'rbf', 'C': 1.6337717979767306, 'epsilon': 0.012661425146657773, 'gamma': 'auto'}. Best is trial 0 with value: 0.4301140197471356.

Running time: 0.1 sec
OOF RMSE: 2.76 | R2: 0.37
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.62 | R2: 0.43
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.02 | R2: 0.24
Fold 1
Fold 2

[I 2025-07-11 22:33:46,786] Trial 15 finished with value: 0.3643853966579671 and parameters: {'kernel': 'rbf', 'C': 4.604579328936265, 'epsilon': 0.1714544964485386, 'gamma': 'scale'}. Best is trial 0 with value: 0.4301140197471356.
[I 2025-07-11 22:33:46,866] Trial 16 finished with value: 0.27846113445411913 and parameters: {'kernel': 'rbf', 'C': 2.2432141368531777, 'epsilon': 0.07422550929584229, 'gamma': 'auto'}. Best is trial 0 with value: 0.4301140197471356.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.76 | R2: 0.36
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.94 | R2: 0.28
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:33:46,951] Trial 17 finished with value: 0.1758862881680857 and parameters: {'kernel': 'rbf', 'C': 0.7436783895228766, 'epsilon': 0.04367250460074472, 'gamma': 'scale'}. Best is trial 0 with value: 0.4301140197471356.
[I 2025-07-11 22:33:47,038] Trial 18 finished with value: -69.31097365586123 and parameters: {'kernel': 'sigmoid', 'C': 5.4861990734168335, 'epsilon': 0.169518524788829, 'gamma': 'auto'}. Best is trial 0 with value: 0.4301140197471356.
[I 2025-07-11 22:33:47,121] Trial 19 finished with value: 0.14283990788711898 and parameters: {'kernel': 'rbf', 'C': 0.5108489072940973, 'epsilon': 0.0878497515066975, 'gamma': 'scale'}. Best is trial 0 with value: 0.4301140197471356.

Running time: 0.1 sec
OOF RMSE: 3.15 | R2: 0.18
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 29.07 | R2: -69.31
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.21 | R2: 0.14
Fold 1
Fold 2

[I 2025-07-11 22:33:47,201] Trial 20 finished with value: 0.42310876766495664 and parameters: {'kernel': 'rbf', 'C': 7.304834294243508, 'epsilon': 0.031279968520883106, 'gamma': 'scale'}. Best is trial 0 with value: 0.4301140197471356.
[I 2025-07-11 22:33:47,297] Trial 21 finished with value: 0.4283112693033736 and parameters: {'kernel': 'rbf', 'C': 9.301761972205986, 'epsilon': 0.010371976406501737, 'gamma': 'auto'}. Best is trial 0 with value: 0.4301140197471356.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.63 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.62 | R2: 0.43
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 22:33:47,393] Trial 22 finished with value: 0.42657697404331985 and parameters: {'kernel': 'rbf', 'C': 9.340410868916587, 'epsilon': 0.05741534292223151, 'gamma': 'auto'}. Best is trial 0 with value: 0.4301140197471356.
[I 2025-07-11 22:33:47,485] Trial 23 finished with value: 0.33105387708022493 and parameters: {'kernel': 'rbf', 'C': 3.642368045131791, 'epsilon': 0.09260715000634788, 'gamma': 'auto'}. Best is trial 0 with value: 0.4301140197471356.
[I 2025-07-11 22:33:47,573] Trial 24 finished with value: 0.40431882201938973 and parameters: {'kernel': 'rbf', 'C': 6.128178732868468, 'epsilon': 0.048843742644390224, 'gamma': 'auto'}. Best is trial 0 with value: 0.4301140197471356.

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.63 | R2: 0.43
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.84 | R2: 0.33
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.68 | R2: 0.40

[I 2025-07-11 22:33:47,574] A new study created in memory with name: no-name-6f518aa2-66fd-42eb-8508-2a3510edb094
[I 2025-07-11 22:33:47,639] Trial 0 finished with value: 0.43872965288533705 and parameters: {'n_neighbors': 6, 'weights': 'uniform', 'leaf_size': 38}. Best is trial 0 with value: 0.43872965288533705.
[I 2025-07-11 22:33:47,706] Trial 1 finished with value: 0.5186367176834812 and parameters: {'n_neighbors': 15, 'weights': 'distance', 'leaf_size': 23}. Best is trial 1 with value: 0.5186367176834812.
[I 2025-07-11 22:33:47,770] Trial 2 finished with value: 0.5394857897133869 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 11}. Best is trial 2 with value: 0.5394857897133869.

✅ SVR - Mejor R2: 0.43
📋 Parámetros: {'kernel': 'rbf', 'C': 9.688457231821618, 'epsilon': 0.1598193809127412, 'gamma': 'scale'}

Buscando mejores hiperparámetros para KNN...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.60 | R2: 0.44
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.41 | R2: 0.52
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.35 | R2: 0.54
Fold 1

[I 2025-07-11 22:33:47,835] Trial 3 finished with value: 0.5488218822293138 and parameters: {'n_neighbors': 8, 'weights': 'distance', 'leaf_size': 10}. Best is trial 3 with value: 0.5488218822293138.
[I 2025-07-11 22:33:47,898] Trial 4 finished with value: 0.4689870211426306 and parameters: {'n_neighbors': 12, 'weights': 'uniform', 'leaf_size': 25}. Best is trial 3 with value: 0.5488218822293138.
[I 2025-07-11 22:33:47,966] Trial 5 finished with value: 0.5322198617477256 and parameters: {'n_neighbors': 12, 'weights': 'distance', 'leaf_size': 10}. Best is trial 3 with value: 0.5488218822293138.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.33 | R2: 0.55
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.53 | R2: 0.47
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.37 | R2: 0.53
Fold 1
Fold 2

[I 2025-07-11 22:33:48,033] Trial 6 finished with value: 0.530832872711426 and parameters: {'n_neighbors': 13, 'weights': 'distance', 'leaf_size': 18}. Best is trial 3 with value: 0.5488218822293138.
[I 2025-07-11 22:33:48,097] Trial 7 finished with value: 0.5114323437067447 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'leaf_size': 17}. Best is trial 3 with value: 0.5488218822293138.
[I 2025-07-11 22:33:48,161] Trial 8 finished with value: 0.49613245018303687 and parameters: {'n_neighbors': 8, 'weights': 'uniform', 'leaf_size': 18}. Best is trial 3 with value: 0.5488218822293138.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.37 | R2: 0.53
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.42 | R2: 0.51
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.46 | R2: 0.50
Fold 1
Fold 2
Fold 3

[I 2025-07-11 22:33:48,226] Trial 9 finished with value: 0.4689870211426306 and parameters: {'n_neighbors': 12, 'weights': 'uniform', 'leaf_size': 26}. Best is trial 3 with value: 0.5488218822293138.
[I 2025-07-11 22:33:48,300] Trial 10 finished with value: 0.568089742487507 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'leaf_size': 35}. Best is trial 10 with value: 0.568089742487507.
[I 2025-07-11 22:33:48,374] Trial 11 finished with value: 0.5394857897133869 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 37}. Best is trial 10 with value: 0.568089742487507.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.53 | R2: 0.47
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.28 | R2: 0.57
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.35 | R2: 0.54
Fold 1
Fold 2

[I 2025-07-11 22:33:48,443] Trial 12 finished with value: 0.533384262438025 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'leaf_size': 32}. Best is trial 10 with value: 0.568089742487507.
[I 2025-07-11 22:33:48,516] Trial 13 finished with value: 0.5529056718665524 and parameters: {'n_neighbors': 10, 'weights': 'distance', 'leaf_size': 31}. Best is trial 10 with value: 0.568089742487507.
[I 2025-07-11 22:33:48,594] Trial 14 finished with value: 0.5529056718665524 and parameters: {'n_neighbors': 10, 'weights': 'distance', 'leaf_size': 32}. Best is trial 10 with value: 0.568089742487507.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.37 | R2: 0.53
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.32 | R2: 0.55
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.32 | R2: 0.55
Fold 1

[I 2025-07-11 22:33:48,719] Trial 15 finished with value: 0.533384262438025 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'leaf_size': 32}. Best is trial 10 with value: 0.568089742487507.
[I 2025-07-11 22:33:48,794] Trial 16 finished with value: 0.5529056718665524 and parameters: {'n_neighbors': 10, 'weights': 'distance', 'leaf_size': 34}. Best is trial 10 with value: 0.568089742487507.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.37 | R2: 0.53
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.32 | R2: 0.55
Fold 1
Fold 2

[I 2025-07-11 22:33:48,870] Trial 17 finished with value: 0.5529056718665524 and parameters: {'n_neighbors': 10, 'weights': 'distance', 'leaf_size': 40}. Best is trial 10 with value: 0.568089742487507.
[I 2025-07-11 22:33:48,945] Trial 18 finished with value: 0.49728543124340363 and parameters: {'n_neighbors': 9, 'weights': 'uniform', 'leaf_size': 28}. Best is trial 10 with value: 0.568089742487507.
[I 2025-07-11 22:33:49,019] Trial 19 finished with value: 0.533384262438025 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'leaf_size': 28}. Best is trial 10 with value: 0.568089742487507.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.32 | R2: 0.55
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.46 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.37 | R2: 0.53
Fold 1

[I 2025-07-11 22:33:49,099] Trial 20 finished with value: 0.5186367176834812 and parameters: {'n_neighbors': 15, 'weights': 'distance', 'leaf_size': 35}. Best is trial 10 with value: 0.568089742487507.
[I 2025-07-11 22:33:49,175] Trial 21 finished with value: 0.5529056718665524 and parameters: {'n_neighbors': 10, 'weights': 'distance', 'leaf_size': 31}. Best is trial 10 with value: 0.568089742487507.
[I 2025-07-11 22:33:49,247] Trial 22 finished with value: 0.5352048425811411 and parameters: {'n_neighbors': 11, 'weights': 'distance', 'leaf_size': 30}. Best is trial 10 with value: 0.568089742487507.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.41 | R2: 0.52
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.32 | R2: 0.55
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.36 | R2: 0.54

[I 2025-07-11 22:33:49,324] Trial 23 finished with value: 0.5488218822293138 and parameters: {'n_neighbors': 8, 'weights': 'distance', 'leaf_size': 36}. Best is trial 10 with value: 0.568089742487507.
[I 2025-07-11 22:33:49,398] Trial 24 finished with value: 0.5509878793943392 and parameters: {'n_neighbors': 9, 'weights': 'distance', 'leaf_size': 40}. Best is trial 10 with value: 0.568089742487507.
[I 2025-07-11 22:33:49,399] A new study created in memory with name: no-name-5ff9c1a5-f570-45be-934e-769a81f71de3

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.33 | R2: 0.55
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.32 | R2: 0.55

✅ KNN - Mejor R2: 0.57
📋 Parámetros: {'n_neighbors': 4, 'weights': 'distance', 'leaf_size': 35}

Buscando mejores hiperparámetros para LR...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.79 | R2: -0.20

[I 2025-07-11 22:33:49,463] Trial 0 finished with value: -0.19647391926608337 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: -0.19647391926608337.
[I 2025-07-11 22:33:49,527] Trial 1 finished with value: -0.19647391926608337 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: -0.19647391926608337.
[I 2025-07-11 22:33:49,589] Trial 2 finished with value: -0.19647391926608337 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: -0.19647391926608337.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.79 | R2: -0.20
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.79 | R2: -0.20
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:33:49,686] Trial 3 finished with value: -0.33684288733371104 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 0 with value: -0.19647391926608337.
[I 2025-07-11 22:33:49,810] Trial 4 finished with value: -0.3368428873103504 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 0 with value: -0.19647391926608337.

Running time: 0.1 sec
OOF RMSE: 4.01 | R2: -0.34
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 4.01 | R2: -0.34
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:33:49,918] Trial 5 finished with value: -0.3368428873103504 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 0 with value: -0.19647391926608337.
[I 2025-07-11 22:33:49,994] Trial 6 finished with value: -0.19822626959822376 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 0 with value: -0.19647391926608337.
[I 2025-07-11 22:33:50,056] Trial 7 finished with value: -0.19647391926608337 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: -0.19647391926608337.

Running time: 0.1 sec
OOF RMSE: 4.01 | R2: -0.34
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.79 | R2: -0.20
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.79 | R2: -0.20
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 22:33:50,128] Trial 8 finished with value: -0.19647391926608337 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: -0.19647391926608337.
[I 2025-07-11 22:33:50,192] Trial 9 finished with value: -0.19822626959822376 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 0 with value: -0.19647391926608337.
[I 2025-07-11 22:33:50,272] Trial 10 finished with value: -0.33684288733371104 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 0 with value: -0.19647391926608337.

Fold 5
Running time: 0.1 sec
OOF RMSE: 3.79 | R2: -0.20
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.79 | R2: -0.20
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 4.01 | R2: -0.34
Fold 1
Fold 2
Fold 3

[I 2025-07-11 22:33:50,353] Trial 11 finished with value: -0.19647391926608337 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: -0.19647391926608337.
[I 2025-07-11 22:33:50,416] Trial 12 finished with value: -0.19647391926608337 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: -0.19647391926608337.
[I 2025-07-11 22:33:50,482] Trial 13 finished with value: -0.19647391926608337 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: -0.19647391926608337.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.79 | R2: -0.20
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.79 | R2: -0.20
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.79 | R2: -0.20
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 22:33:50,547] Trial 14 finished with value: -0.19647391926608337 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: -0.19647391926608337.
[I 2025-07-11 22:33:50,612] Trial 15 finished with value: -0.19647391926608337 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: -0.19647391926608337.
[I 2025-07-11 22:33:50,676] Trial 16 finished with value: -0.19647391926608337 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: -0.19647391926608337.

Fold 5
Running time: 0.1 sec
OOF RMSE: 3.79 | R2: -0.20
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.79 | R2: -0.20
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.79 | R2: -0.20
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:33:50,740] Trial 17 finished with value: -0.19647391926608337 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: -0.19647391926608337.
[I 2025-07-11 22:33:50,833] Trial 18 finished with value: -0.3368428873103504 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 0 with value: -0.19647391926608337.
[I 2025-07-11 22:33:50,910] Trial 19 finished with value: -0.19647391926608337 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: -0.19647391926608337.

Running time: 0.1 sec
OOF RMSE: 3.79 | R2: -0.20
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 4.01 | R2: -0.34
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.79 | R2: -0.20
Fold 1
Fold 2
Fold 3

[I 2025-07-11 22:33:50,977] Trial 20 finished with value: -0.19647391926608337 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: -0.19647391926608337.
[I 2025-07-11 22:33:51,044] Trial 21 finished with value: -0.19647391926608337 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: -0.19647391926608337.
[I 2025-07-11 22:33:51,110] Trial 22 finished with value: -0.19647391926608337 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: -0.19647391926608337.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.79 | R2: -0.20
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.79 | R2: -0.20
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.79 | R2: -0.20
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 22:33:51,176] Trial 23 finished with value: -0.19647391926608337 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: -0.19647391926608337.
[I 2025-07-11 22:33:51,243] Trial 24 finished with value: -0.19647391926608337 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: -0.19647391926608337.
[I 2025-07-11 22:33:51,244] A new study created in memory with name: no-name-23c9bc4c-a038-439a-bedb-edf34ea75957

Fold 5
Running time: 0.1 sec
OOF RMSE: 3.79 | R2: -0.20
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.79 | R2: -0.20

✅ LR - Mejor R2: -0.20
📋 Parámetros: {'fit_intercept': True, 'positive': True}

Buscando mejores hiperparámetros para RF...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:34:02,194] Trial 0 finished with value: 0.11937940740805042 and parameters: {'n_estimators': 500, 'max_depth': 8, 'min_samples_split': 6, 'min_samples_leaf': 5, 'bootstrap': False}. Best is trial 0 with value: 0.11937940740805042.

Running time: 10.9 sec
OOF RMSE: 3.25 | R2: 0.12
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:34:10,029] Trial 1 finished with value: 0.2872975362496648 and parameters: {'n_estimators': 300, 'max_depth': 14, 'min_samples_split': 5, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 1 with value: 0.2872975362496648.

Running time: 7.8 sec
OOF RMSE: 2.93 | R2: 0.29
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:34:13,952] Trial 2 finished with value: 0.4509139411474853 and parameters: {'n_estimators': 300, 'max_depth': 5, 'min_samples_split': 3, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 2 with value: 0.4509139411474853.

Running time: 3.9 sec
OOF RMSE: 2.57 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:34:26,445] Trial 3 finished with value: 0.30229799880854014 and parameters: {'n_estimators': 500, 'max_depth': 8, 'min_samples_split': 6, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 2 with value: 0.4509139411474853.

Running time: 12.5 sec
OOF RMSE: 2.90 | R2: 0.30
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:34:30,764] Trial 4 finished with value: 0.39285360473703534 and parameters: {'n_estimators': 300, 'max_depth': 14, 'min_samples_split': 10, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 2 with value: 0.4509139411474853.

Running time: 4.3 sec
OOF RMSE: 2.70 | R2: 0.39
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:34:40,692] Trial 5 finished with value: 0.35029265963224443 and parameters: {'n_estimators': 300, 'max_depth': 14, 'min_samples_split': 2, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 2 with value: 0.4509139411474853.

Running time: 9.9 sec
OOF RMSE: 2.79 | R2: 0.35
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:34:44,876] Trial 6 finished with value: 0.43184344146015474 and parameters: {'n_estimators': 300, 'max_depth': 6, 'min_samples_split': 6, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 2 with value: 0.4509139411474853.

Running time: 4.2 sec
OOF RMSE: 2.61 | R2: 0.43
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:34:54,106] Trial 7 finished with value: 0.46138585811090493 and parameters: {'n_estimators': 500, 'max_depth': 14, 'min_samples_split': 3, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 7 with value: 0.46138585811090493.

Running time: 9.2 sec
OOF RMSE: 2.54 | R2: 0.46
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:34:55,330] Trial 8 finished with value: 0.3825333924547115 and parameters: {'n_estimators': 100, 'max_depth': 5, 'min_samples_split': 5, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 7 with value: 0.46138585811090493.

Running time: 1.2 sec
OOF RMSE: 2.72 | R2: 0.38
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:35:07,175] Trial 9 finished with value: 0.2907269699312093 and parameters: {'n_estimators': 500, 'max_depth': 10, 'min_samples_split': 4, 'min_samples_leaf': 4, 'bootstrap': False}. Best is trial 7 with value: 0.46138585811090493.

Running time: 11.8 sec
OOF RMSE: 2.92 | R2: 0.29
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:35:08,896] Trial 10 finished with value: 0.40303285163243086 and parameters: {'n_estimators': 100, 'max_depth': 12, 'min_samples_split': 9, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 7 with value: 0.46138585811090493.

Running time: 1.7 sec
OOF RMSE: 2.68 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:35:18,000] Trial 11 finished with value: 0.4574551068324687 and parameters: {'n_estimators': 500, 'max_depth': 11, 'min_samples_split': 3, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 7 with value: 0.46138585811090493.

Running time: 9.1 sec
OOF RMSE: 2.55 | R2: 0.46
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:35:27,175] Trial 12 finished with value: 0.4574732661759594 and parameters: {'n_estimators': 500, 'max_depth': 12, 'min_samples_split': 2, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 7 with value: 0.46138585811090493.

Running time: 9.2 sec
OOF RMSE: 2.55 | R2: 0.46
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:35:36,345] Trial 13 finished with value: 0.4574732661759594 and parameters: {'n_estimators': 500, 'max_depth': 12, 'min_samples_split': 2, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 7 with value: 0.46138585811090493.

Running time: 9.2 sec
OOF RMSE: 2.55 | R2: 0.46
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:35:47,210] Trial 14 finished with value: 0.47624140604932097 and parameters: {'n_estimators': 500, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 14 with value: 0.47624140604932097.

Running time: 10.9 sec
OOF RMSE: 2.51 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:35:57,259] Trial 15 finished with value: 0.4667875607706762 and parameters: {'n_estimators': 500, 'max_depth': 15, 'min_samples_split': 4, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 14 with value: 0.47624140604932097.

Running time: 10.0 sec
OOF RMSE: 2.53 | R2: 0.47
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:35:59,116] Trial 16 finished with value: 0.4212068915328254 and parameters: {'n_estimators': 100, 'max_depth': 15, 'min_samples_split': 8, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 14 with value: 0.47624140604932097.

Running time: 1.9 sec
OOF RMSE: 2.64 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:36:09,254] Trial 17 finished with value: 0.4667875607706762 and parameters: {'n_estimators': 500, 'max_depth': 15, 'min_samples_split': 4, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 14 with value: 0.47624140604932097.

Running time: 10.1 sec
OOF RMSE: 2.53 | R2: 0.47
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:36:17,030] Trial 18 finished with value: 0.41519115677271023 and parameters: {'n_estimators': 500, 'max_depth': 13, 'min_samples_split': 4, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 14 with value: 0.47624140604932097.

Running time: 7.8 sec
OOF RMSE: 2.65 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:36:25,976] Trial 19 finished with value: 0.4259547928580132 and parameters: {'n_estimators': 500, 'max_depth': 10, 'min_samples_split': 8, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 14 with value: 0.47624140604932097.

Running time: 8.9 sec
OOF RMSE: 2.63 | R2: 0.43
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:36:27,658] Trial 20 finished with value: 0.4264134797251439 and parameters: {'n_estimators': 100, 'max_depth': 15, 'min_samples_split': 5, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 14 with value: 0.47624140604932097.

Running time: 1.7 sec
OOF RMSE: 2.63 | R2: 0.43
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:36:37,738] Trial 21 finished with value: 0.4667875607706762 and parameters: {'n_estimators': 500, 'max_depth': 15, 'min_samples_split': 4, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 14 with value: 0.47624140604932097.

Running time: 10.1 sec
OOF RMSE: 2.53 | R2: 0.47
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:36:48,023] Trial 22 finished with value: 0.46641301633643906 and parameters: {'n_estimators': 500, 'max_depth': 13, 'min_samples_split': 3, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 14 with value: 0.47624140604932097.

Running time: 10.3 sec
OOF RMSE: 2.53 | R2: 0.47
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:36:58,064] Trial 23 finished with value: 0.4667875607706762 and parameters: {'n_estimators': 500, 'max_depth': 15, 'min_samples_split': 4, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 14 with value: 0.47624140604932097.

Running time: 10.0 sec
OOF RMSE: 2.53 | R2: 0.47
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:37:07,397] Trial 24 finished with value: 0.43298186533858773 and parameters: {'n_estimators': 500, 'max_depth': 13, 'min_samples_split': 7, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 14 with value: 0.47624140604932097.
[I 2025-07-11 22:37:07,398] A new study created in memory with name: no-name-6b4a6021-1751-4587-8afc-5d16e76f2c54

Running time: 9.3 sec
OOF RMSE: 2.61 | R2: 0.43

✅ RF - Mejor R2: 0.48
📋 Parámetros: {'n_estimators': 500, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 1, 'bootstrap': True}

Buscando mejores hiperparámetros para CAT...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:37:27,096] Trial 0 finished with value: 0.6152016613616298 and parameters: {'iterations': 500, 'learning_rate': 0.08712562412816081, 'depth': 8, 'l2_leaf_reg': 5.716663878628392}. Best is trial 0 with value: 0.6152016613616298.

Running time: 19.7 sec
OOF RMSE: 2.15 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:37:33,292] Trial 1 finished with value: 0.5907356640428159 and parameters: {'iterations': 2000, 'learning_rate': 0.01589682681471822, 'depth': 4, 'l2_leaf_reg': 8.838266731198988}. Best is trial 0 with value: 0.6152016613616298.

Running time: 6.2 sec
OOF RMSE: 2.22 | R2: 0.59
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:37:48,188] Trial 2 finished with value: 0.6004433565831571 and parameters: {'iterations': 1000, 'learning_rate': 0.016948229402116325, 'depth': 7, 'l2_leaf_reg': 5.1926146653533}. Best is trial 0 with value: 0.6152016613616298.

Running time: 14.9 sec
OOF RMSE: 2.19 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:37:54,806] Trial 3 finished with value: 0.5835645677378724 and parameters: {'iterations': 1000, 'learning_rate': 0.010945262788347227, 'depth': 6, 'l2_leaf_reg': 8.77996325097413}. Best is trial 0 with value: 0.6152016613616298.

Running time: 6.6 sec
OOF RMSE: 2.24 | R2: 0.58
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:38:08,481] Trial 4 finished with value: 0.5833580326541277 and parameters: {'iterations': 2000, 'learning_rate': 0.04998352242123321, 'depth': 6, 'l2_leaf_reg': 2.3511245379587553}. Best is trial 0 with value: 0.6152016613616298.

Running time: 13.7 sec
OOF RMSE: 2.24 | R2: 0.58
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:38:11,562] Trial 5 finished with value: 0.5728228713758348 and parameters: {'iterations': 1000, 'learning_rate': 0.020268715330974907, 'depth': 4, 'l2_leaf_reg': 9.262738500376184}. Best is trial 0 with value: 0.6152016613616298.

Running time: 3.1 sec
OOF RMSE: 2.27 | R2: 0.57
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:41:08,734] Trial 6 finished with value: 0.6061065127869394 and parameters: {'iterations': 2000, 'learning_rate': 0.08517866193200677, 'depth': 9, 'l2_leaf_reg': 8.954262525341719}. Best is trial 0 with value: 0.6152016613616298.

Running time: 177.2 sec
OOF RMSE: 2.18 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:41:16,328] Trial 7 finished with value: 0.5648756622660223 and parameters: {'iterations': 500, 'learning_rate': 0.013514326074945066, 'depth': 7, 'l2_leaf_reg': 8.057689476210879}. Best is trial 0 with value: 0.6152016613616298.

Running time: 7.6 sec
OOF RMSE: 2.29 | R2: 0.56
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:44:12,112] Trial 8 finished with value: 0.6219060371950423 and parameters: {'iterations': 2000, 'learning_rate': 0.027814843365377966, 'depth': 9, 'l2_leaf_reg': 5.38723148802515}. Best is trial 8 with value: 0.6219060371950423.

Running time: 175.8 sec
OOF RMSE: 2.13 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:44:27,453] Trial 9 finished with value: 0.612398922567063 and parameters: {'iterations': 1000, 'learning_rate': 0.05682686476868888, 'depth': 7, 'l2_leaf_reg': 4.865568412322624}. Best is trial 8 with value: 0.6219060371950423.

Running time: 15.3 sec
OOF RMSE: 2.16 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:49:27,878] Trial 10 finished with value: 0.597464570588047 and parameters: {'iterations': 2000, 'learning_rate': 0.02925489091132434, 'depth': 10, 'l2_leaf_reg': 1.2532088671809554}. Best is trial 8 with value: 0.6219060371950423.
[I 2025-07-11 22:49:27,879] A new study created in memory with name: no-name-46aa56ba-2f37-40a8-9a23-cac1e20fc200
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.482e-01, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.089e+00, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.476e+00, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.434e+00, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.144e+00, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 22:49:27,985] Trial 0 finished with value: 0.5347935262115897 and parameters: {'alpha': 0.012733511253733861, 'l1_ratio': 0.9816153695462476}. Best is trial 0 with value: 0.5347935262115897.

Running time: 300.4 sec
OOF RMSE: 2.20 | R2: 0.60

✅ CAT - Mejor R2: 0.62
📋 Parámetros: {'iterations': 2000, 'learning_rate': 0.027814843365377966, 'depth': 9, 'l2_leaf_reg': 5.38723148802515}

Buscando mejores hiperparámetros para EN...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.36 | R2: 0.53
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.759e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.229e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.307e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.651e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.820e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 22:49:28,168] Trial 1 finished with value: 0.3321928644147246 and parameters: {'alpha': 0.0002515346038147347, 'l1_ratio': 0.16595918750491356}. Best is trial 0 with value: 0.5347935262115897.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.606e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.090e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.188e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.533e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(

Fold 3
Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 2.83 | R2: 0.33
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.674e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 22:49:28,314] Trial 2 finished with value: 0.3202808338099602 and parameters: {'alpha': 0.00011817962761991735, 'l1_ratio': 0.7982287938854661}. Best is trial 0 with value: 0.5347935262115897.
[I 2025-07-11 22:49:28,511] Trial 3 finished with value: 0.44389035134483434 and parameters: {'alpha': 0.04227740652738442, 'l1_ratio': 0.27902545084294206}. Best is trial 0 with value: 0.5347935262115897.

Running time: 0.1 sec
OOF RMSE: 2.86 | R2: 0.32
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 2.59 | R2: 0.44

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.132e+01, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.244e+01, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.897e+01, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.723e+01, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.715e+01, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 22:49:28,701] Trial 4 finished with value: 0.46885427874601726 and parameters: {'alpha': 0.0036602056751604936, 'l1_ratio': 0.7366298462806586}. Best is trial 0 with value: 0.5347935262115897.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 2.53 | R2: 0.47
Fold 1

[I 2025-07-11 22:49:28,858] Trial 5 finished with value: 0.40299291257193104 and parameters: {'alpha': 0.09040770065110755, 'l1_ratio': 0.6078095847385007}. Best is trial 0 with value: 0.5347935262115897.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 2.68 | R2: 0.40
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.655e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.993e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.949e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.536e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.050e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 22:49:28,996] Trial 6 finished with value: 0.4242438389193458 and parameters: {'alpha': 0.002116530445205447, 'l1_ratio': 0.030239799234742737}. Best is trial 0 with value: 0.5347935262115897.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.199e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.871e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.837e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.835e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.313e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 22:49:29,137] Trial 7 finished with value: 0.37878348733566325 and parameters: {'alpha': 0.0010504297150242337, 'l1_ratio': 0.39416758355202963}. Best is trial 0 with value: 0.5347935262115897.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.63 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.73 | R2: 0.38
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.104e+01, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.235e+01, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.814e+01, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.211e+01, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.262e+01, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 22:49:29,284] Trial 8 finished with value: 0.48203222254241174 and parameters: {'alpha': 0.00889499669212844, 'l1_ratio': 0.20368025751217989}. Best is trial 0 with value: 0.5347935262115897.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.49 | R2: 0.48
Fold 1
Fold 2
Fold 3

[I 2025-07-11 22:49:29,439] Trial 9 finished with value: 0.24529540816982998 and parameters: {'alpha': 0.7411491065118795, 'l1_ratio': 0.8472010551170928}. Best is trial 0 with value: 0.5347935262115897.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.01 | R2: 0.25
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 22:49:29,615] Trial 10 finished with value: -0.00027817151752640434 and parameters: {'alpha': 8.231849562733213, 'l1_ratio': 0.9597574869358918}. Best is trial 0 with value: 0.5347935262115897.

Fold 5
Running time: 0.2 sec
OOF RMSE: 3.47 | R2: -0.00
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.550e-01, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.079e+00, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.174e+00, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 22:49:29,901] Trial 11 finished with value: 0.5029699580568125 and parameters: {'alpha': 0.011014360371172878, 'l1_ratio': 0.5218334653485542}. Best is trial 0 with value: 0.5347935262115897.
[I 2025-07-11 22:49:30,008] Trial 12 finished with value: 0.35556881213874714 and parameters: {'alpha': 0.1774018565884723, 'l1_ratio': 0.5482361145385057}. Best is trial 0 with value: 0.5347935262115897.

Fold 4
Fold 5
Running time: 0.3 sec
OOF RMSE: 2.44 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.78 | R2: 0.36
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.710e-01, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.115e-01, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.121e-01, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.566e-01, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.885e-01, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 22:49:30,157] Trial 13 finished with value: 0.5134950923971214 and parameters: {'alpha': 0.01109393999677724, 'l1_ratio': 0.6484946758653347}. Best is trial 0 with value: 0.5347935262115897.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.42 | R2: 0.51
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:49:30,283] Trial 14 finished with value: 0.22856543717466604 and parameters: {'alpha': 0.33598639020885307, 'l1_ratio': 0.9983762923582766}. Best is trial 0 with value: 0.5347935262115897.
[I 2025-07-11 22:49:30,420] Trial 15 finished with value: 0.5044645196857882 and parameters: {'alpha': 0.02082957605334182, 'l1_ratio': 0.6796603745572893}. Best is trial 0 with value: 0.5347935262115897.

Running time: 0.1 sec
OOF RMSE: 3.04 | R2: 0.23
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.44 | R2: 0.50
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.614e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.184e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.255e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.914e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.217e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 22:49:30,555] Trial 16 finished with value: 0.3499767267289977 and parameters: {'alpha': 0.0005809886586289444, 'l1_ratio': 0.9181513021183803}. Best is trial 0 with value: 0.5347935262115897.
[I 2025-07-11 22:49:30,647] Trial 17 finished with value: 0.26533444355069913 and parameters: {'alpha': 1.4699984421046652, 'l1_ratio': 0.40437930239584535}. Best is trial 0 with value: 0.5347935262115897.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.441e+01, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.79 | R2: 0.35
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.97 | R2: 0.27
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.354e+01, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.304e+01, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.929e+01, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.358e+01, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 22:49:30,795] Trial 18 finished with value: 0.4849859067588437 and parameters: {'alpha': 0.004771530353217295, 'l1_ratio': 0.663866534180912}. Best is trial 0 with value: 0.5347935262115897.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.49 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 22:49:30,937] Trial 19 finished with value: 0.4833250944638855 and parameters: {'alpha': 0.03725753038404994, 'l1_ratio': 0.8428973846664402}. Best is trial 0 with value: 0.5347935262115897.
[I 2025-07-11 22:49:31,050] Trial 20 finished with value: 0.4203360280907228 and parameters: {'alpha': 0.07548407447632778, 'l1_ratio': 0.4191281796053754}. Best is trial 0 with value: 0.5347935262115897.

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.49 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.64 | R2: 0.42
Fold 1
Fold 2

[I 2025-07-11 22:49:31,226] Trial 21 finished with value: 0.518692051471596 and parameters: {'alpha': 0.016251465657444848, 'l1_ratio': 0.7479502160869976}. Best is trial 0 with value: 0.5347935262115897.

Fold 3
Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 2.40 | R2: 0.52
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.576e-01, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.670e-01, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.072e-01, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.241e-01, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.962e-01, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 22:49:31,416] Trial 22 finished with value: 0.5208262540917008 and parameters: {'alpha': 0.013319729235195343, 'l1_ratio': 0.7445868024529452}. Best is trial 0 with value: 0.5347935262115897.

Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 2.40 | R2: 0.52
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.423e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.098e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.283e+01, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.121e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.781e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 22:49:31,623] Trial 23 finished with value: 0.3883756585795054 and parameters: {'alpha': 0.0013530826758318363, 'l1_ratio': 0.7497876886039315}. Best is trial 0 with value: 0.5347935262115897.

Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 2.71 | R2: 0.39
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.177e-01, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.095e+00, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.931e+00, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 22:49:31,838] Trial 24 finished with value: 0.5258136124331056 and parameters: {'alpha': 0.017956834813938314, 'l1_ratio': 0.8890110506073345}. Best is trial 0 with value: 0.5347935262115897.
[I 2025-07-11 22:49:31,839] A new study created in memory with name: no-name-95058d43-5901-4227-bd80-bad7abb0fbd1

Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 2.39 | R2: 0.53

✅ EN - Mejor R2: 0.53
📋 Parámetros: {'alpha': 0.012733511253733861, 'l1_ratio': 0.9816153695462476}

🔍 Optimizando en C2X-Complex_rhown_1x1_depth_lt_1...
Buscando mejores hiperparámetros para XGB...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:49:39,034] Trial 0 finished with value: 0.43554527136616383 and parameters: {'n_estimators': 500, 'learning_rate': 0.005141410768155222, 'max_depth': 8, 'min_child_weight': 1, 'subsample': 0.9569095361956259, 'colsample_bytree': 0.7039922820260476}. Best is trial 0 with value: 0.43554527136616383.

Running time: 7.2 sec
OOF RMSE: 2.60 | R2: 0.44
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:49:46,696] Trial 1 finished with value: 0.39346841379971786 and parameters: {'n_estimators': 2000, 'learning_rate': 0.08253439336475527, 'max_depth': 8, 'min_child_weight': 3, 'subsample': 0.8031615948972016, 'colsample_bytree': 0.7384292901478073}. Best is trial 0 with value: 0.43554527136616383.

Running time: 7.7 sec
OOF RMSE: 2.70 | R2: 0.39
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:49:51,271] Trial 2 finished with value: 0.4280329202878641 and parameters: {'n_estimators': 1000, 'learning_rate': 0.060622092031594306, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.8146307620376171, 'colsample_bytree': 0.8438748765473719}. Best is trial 0 with value: 0.43554527136616383.

Running time: 4.6 sec
OOF RMSE: 2.62 | R2: 0.43
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:49:58,181] Trial 3 finished with value: 0.45510163243654256 and parameters: {'n_estimators': 2000, 'learning_rate': 0.08901232304726572, 'max_depth': 5, 'min_child_weight': 1, 'subsample': 0.7850098456905803, 'colsample_bytree': 0.9677891622899941}. Best is trial 3 with value: 0.45510163243654256.

Running time: 6.9 sec
OOF RMSE: 2.56 | R2: 0.46
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:50:06,919] Trial 4 finished with value: 0.4541470046702949 and parameters: {'n_estimators': 2000, 'learning_rate': 0.0507331012649109, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.659260976611514, 'colsample_bytree': 0.6817732454010305}. Best is trial 3 with value: 0.45510163243654256.

Running time: 8.7 sec
OOF RMSE: 2.56 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:50:16,893] Trial 5 finished with value: 0.4333482004247101 and parameters: {'n_estimators': 2000, 'learning_rate': 0.022187652899808175, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.8159148443733483, 'colsample_bytree': 0.6520665076637594}. Best is trial 3 with value: 0.45510163243654256.

Running time: 10.0 sec
OOF RMSE: 2.61 | R2: 0.43
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:50:27,046] Trial 6 finished with value: 0.4536502655890521 and parameters: {'n_estimators': 2000, 'learning_rate': 0.008278146184037726, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.649572698863987, 'colsample_bytree': 0.713312216437695}. Best is trial 3 with value: 0.45510163243654256.

Running time: 10.1 sec
OOF RMSE: 2.56 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:50:35,463] Trial 7 finished with value: 0.3570920433149011 and parameters: {'n_estimators': 2000, 'learning_rate': 0.04697421939765992, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.9114539034424272, 'colsample_bytree': 0.8801496397189947}. Best is trial 3 with value: 0.45510163243654256.

Running time: 8.4 sec
OOF RMSE: 2.78 | R2: 0.36
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:50:41,574] Trial 8 finished with value: 0.45343256593232584 and parameters: {'n_estimators': 1000, 'learning_rate': 0.04940445796108864, 'max_depth': 8, 'min_child_weight': 1, 'subsample': 0.7688452023595584, 'colsample_bytree': 0.616105725429389}. Best is trial 3 with value: 0.45510163243654256.

Running time: 6.1 sec
OOF RMSE: 2.56 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:50:46,997] Trial 9 finished with value: 0.4309232709431997 and parameters: {'n_estimators': 1000, 'learning_rate': 0.057384604773511795, 'max_depth': 5, 'min_child_weight': 1, 'subsample': 0.8028030421575143, 'colsample_bytree': 0.9430892337287666}. Best is trial 3 with value: 0.45510163243654256.

Running time: 5.4 sec
OOF RMSE: 2.62 | R2: 0.43
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:50:49,737] Trial 10 finished with value: 0.46873220972295904 and parameters: {'n_estimators': 500, 'learning_rate': 0.02278565662245695, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.7235384965229524, 'colsample_bytree': 0.9975972053836795}. Best is trial 10 with value: 0.46873220972295904.

Running time: 2.7 sec
OOF RMSE: 2.53 | R2: 0.47
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:50:52,607] Trial 11 finished with value: 0.45899582219453405 and parameters: {'n_estimators': 500, 'learning_rate': 0.020149739593076678, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.70122203731335, 'colsample_bytree': 0.9959323870513374}. Best is trial 10 with value: 0.46873220972295904.

Running time: 2.9 sec
OOF RMSE: 2.55 | R2: 0.46
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:50:55,312] Trial 12 finished with value: 0.46827890946176 and parameters: {'n_estimators': 500, 'learning_rate': 0.020123405296570206, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.7073212414569793, 'colsample_bytree': 0.9172907705421879}. Best is trial 10 with value: 0.46873220972295904.

Running time: 2.7 sec
OOF RMSE: 2.53 | R2: 0.47
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:50:57,891] Trial 13 finished with value: 0.4745728167385953 and parameters: {'n_estimators': 500, 'learning_rate': 0.0139084340492835, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.6032525770881089, 'colsample_bytree': 0.90677809806042}. Best is trial 13 with value: 0.4745728167385953.

Running time: 2.6 sec
OOF RMSE: 2.51 | R2: 0.47
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:51:00,826] Trial 14 finished with value: 0.4476833269444167 and parameters: {'n_estimators': 500, 'learning_rate': 0.012406439336886694, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.6095503794282328, 'colsample_bytree': 0.8546417740570585}. Best is trial 13 with value: 0.4745728167385953.

Running time: 2.9 sec
OOF RMSE: 2.58 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:51:03,643] Trial 15 finished with value: 0.472085556396322 and parameters: {'n_estimators': 500, 'learning_rate': 0.012987566379181057, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.6008435351860918, 'colsample_bytree': 0.7975824258910141}. Best is trial 13 with value: 0.4745728167385953.

Running time: 2.8 sec
OOF RMSE: 2.52 | R2: 0.47
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:51:06,508] Trial 16 finished with value: 0.45549578334252105 and parameters: {'n_estimators': 500, 'learning_rate': 0.012664448244832493, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.603358132875903, 'colsample_bytree': 0.7864367599116281}. Best is trial 13 with value: 0.4745728167385953.

Running time: 2.9 sec
OOF RMSE: 2.56 | R2: 0.46
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:51:09,434] Trial 17 finished with value: 0.46228770060860847 and parameters: {'n_estimators': 500, 'learning_rate': 0.011661589224575872, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.6556254358836865, 'colsample_bytree': 0.7861569862405873}. Best is trial 13 with value: 0.4745728167385953.

Running time: 2.9 sec
OOF RMSE: 2.54 | R2: 0.46
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:51:12,370] Trial 18 finished with value: 0.43628147740129763 and parameters: {'n_estimators': 500, 'learning_rate': 0.033516395614776213, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.8943408823646362, 'colsample_bytree': 0.8132505703599294}. Best is trial 13 with value: 0.4745728167385953.

Running time: 2.9 sec
OOF RMSE: 2.60 | R2: 0.44
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:51:15,217] Trial 19 finished with value: 0.44659689735401564 and parameters: {'n_estimators': 500, 'learning_rate': 0.007076089730431161, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.632146009487772, 'colsample_bytree': 0.9020646652629343}. Best is trial 13 with value: 0.4745728167385953.

Running time: 2.8 sec
OOF RMSE: 2.58 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:51:18,076] Trial 20 finished with value: 0.4781826062386273 and parameters: {'n_estimators': 500, 'learning_rate': 0.01432244930150747, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.741295681460159, 'colsample_bytree': 0.7555314856587327}. Best is trial 20 with value: 0.4781826062386273.

Running time: 2.9 sec
OOF RMSE: 2.50 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:51:21,035] Trial 21 finished with value: 0.4712068631277744 and parameters: {'n_estimators': 500, 'learning_rate': 0.01580954534906484, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.7331699926600123, 'colsample_bytree': 0.7640733110908288}. Best is trial 20 with value: 0.4781826062386273.

Running time: 3.0 sec
OOF RMSE: 2.52 | R2: 0.47
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:51:23,879] Trial 22 finished with value: 0.4771139990702681 and parameters: {'n_estimators': 500, 'learning_rate': 0.009228158033329534, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.6913038528597497, 'colsample_bytree': 0.8252596273646436}. Best is trial 20 with value: 0.4781826062386273.

Running time: 2.8 sec
OOF RMSE: 2.51 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:51:26,682] Trial 23 finished with value: 0.45703879124815583 and parameters: {'n_estimators': 500, 'learning_rate': 0.009009327522210954, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.6817080818016186, 'colsample_bytree': 0.850544702859113}. Best is trial 20 with value: 0.4781826062386273.

Running time: 2.8 sec
OOF RMSE: 2.55 | R2: 0.46
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:51:29,936] Trial 24 finished with value: 0.4590044545254903 and parameters: {'n_estimators': 500, 'learning_rate': 0.005817013022314106, 'max_depth': 8, 'min_child_weight': 4, 'subsample': 0.7620666112520968, 'colsample_bytree': 0.830610745269769}. Best is trial 20 with value: 0.4781826062386273.
[I 2025-07-11 22:51:29,938] A new study created in memory with name: no-name-2449b946-3983-407a-b0e8-31031e641857

Running time: 3.2 sec
OOF RMSE: 2.55 | R2: 0.46

✅ XGB - Mejor R2: 0.48
📋 Parámetros: {'n_estimators': 500, 'learning_rate': 0.01432244930150747, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.741295681460159, 'colsample_bytree': 0.7555314856587327}

Buscando mejores hiperparámetros para LBM...
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 22:51:30,865] Trial 0 finished with value: 0.4351891630492881 and parameters: {'learning_rate': 0.007485943152429608, 'num_leaves': 80, 'max_depth': 8, 'min_child_samples': 25, 'subsample': 0.7856669147987985, 'colsample_bytree': 0.6259954135325754, 'n_estimators': 2000}. Best is trial 0 with value: 0.4351891630492881.

Fold 5
Running time: 0.9 sec
OOF RMSE: 2.61 | R2: 0.44
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:51:31,153] Trial 1 finished with value: 0.38242343397312495 and parameters: {'learning_rate': 0.08370458860641891, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 19, 'subsample': 0.8878429353949611, 'colsample_bytree': 0.6434296467206235, 'n_estimators': 500}. Best is trial 0 with value: 0.4351891630492881.

Running time: 0.3 sec
OOF RMSE: 2.72 | R2: 0.38
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 22:51:31,460] Trial 2 finished with value: 0.3372634186062221 and parameters: {'learning_rate': 0.0775762626669312, 'num_leaves': 60, 'max_depth': 8, 'min_child_samples': 22, 'subsample': 0.9627826777220927, 'colsample_bytree': 0.874681447654744, 'n_estimators': 500}. Best is trial 0 with value: 0.4351891630492881.

Fold 5
Running time: 0.3 sec
OOF RMSE: 2.82 | R2: 0.34
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 22:51:31,947] Trial 3 finished with value: 0.4636041613881039 and parameters: {'learning_rate': 0.012581930241940016, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 16, 'subsample': 0.9836704297719847, 'colsample_bytree': 0.6987702154799919, 'n_estimators': 1000}. Best is trial 3 with value: 0.4636041613881039.

Fold 5
Running time: 0.5 sec
OOF RMSE: 2.54 | R2: 0.46
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:51:32,588] Trial 4 finished with value: 0.39719127511714536 and parameters: {'learning_rate': 0.03279420030448897, 'num_leaves': 60, 'max_depth': 8, 'min_child_samples': 16, 'subsample': 0.8034590254491292, 'colsample_bytree': 0.8633418565404343, 'n_estimators': 1000}. Best is trial 3 with value: 0.4636041613881039.

Running time: 0.6 sec
OOF RMSE: 2.69 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 22:51:33,118] Trial 5 finished with value: 0.4382129135327911 and parameters: {'learning_rate': 0.016079451520717228, 'num_leaves': 60, 'max_depth': 6, 'min_child_samples': 15, 'subsample': 0.7724924255666938, 'colsample_bytree': 0.7595356165806751, 'n_estimators': 1000}. Best is trial 3 with value: 0.4636041613881039.

Fold 5
Running time: 0.5 sec
OOF RMSE: 2.60 | R2: 0.44
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:51:34,278] Trial 6 finished with value: 0.32474880084535107 and parameters: {'learning_rate': 0.035010318549113045, 'num_leaves': 60, 'max_depth': 7, 'min_child_samples': 11, 'subsample': 0.7306839785954049, 'colsample_bytree': 0.9360468269304492, 'n_estimators': 2000}. Best is trial 3 with value: 0.4636041613881039.

Running time: 1.2 sec
OOF RMSE: 2.85 | R2: 0.32
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 22:51:35,166] Trial 7 finished with value: 0.406142239463696 and parameters: {'learning_rate': 0.005958342902120585, 'num_leaves': 60, 'max_depth': 5, 'min_child_samples': 22, 'subsample': 0.8153615593004672, 'colsample_bytree': 0.9948169652035554, 'n_estimators': 2000}. Best is trial 3 with value: 0.4636041613881039.

Fold 5
Running time: 0.9 sec
OOF RMSE: 2.67 | R2: 0.41
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:51:35,516] Trial 8 finished with value: 0.37764173348098284 and parameters: {'learning_rate': 0.014456587209574708, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 12, 'subsample': 0.7131453388163651, 'colsample_bytree': 0.9073100105509361, 'n_estimators': 500}. Best is trial 3 with value: 0.4636041613881039.

Running time: 0.3 sec
OOF RMSE: 2.73 | R2: 0.38
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 22:51:36,523] Trial 9 finished with value: 0.36245908539487504 and parameters: {'learning_rate': 0.07874958949738242, 'num_leaves': 80, 'max_depth': 6, 'min_child_samples': 12, 'subsample': 0.7481910576158002, 'colsample_bytree': 0.7039462400831431, 'n_estimators': 2000}. Best is trial 3 with value: 0.4636041613881039.

Fold 5
Running time: 1.0 sec
OOF RMSE: 2.77 | R2: 0.36
Fold 1
Fold 2
Fold 3

[I 2025-07-11 22:51:36,966] Trial 10 finished with value: 0.39315232048037396 and parameters: {'learning_rate': 0.010338461133120036, 'num_leaves': 40, 'max_depth': 5, 'min_child_samples': 9, 'subsample': 0.6038969044608822, 'colsample_bytree': 0.7822242740966042, 'n_estimators': 1000}. Best is trial 3 with value: 0.4636041613881039.

Fold 4
Fold 5
Running time: 0.4 sec
OOF RMSE: 2.70 | R2: 0.39
Fold 1
Fold 2
Fold 3

[I 2025-07-11 22:51:37,505] Trial 11 finished with value: 0.4321590547358056 and parameters: {'learning_rate': 0.016963061288464677, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 15, 'subsample': 0.9868289209446873, 'colsample_bytree': 0.7511236451528597, 'n_estimators': 1000}. Best is trial 3 with value: 0.4636041613881039.

Fold 4
Fold 5
Running time: 0.5 sec
OOF RMSE: 2.61 | R2: 0.43
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:51:38,102] Trial 12 finished with value: 0.3888835003711152 and parameters: {'learning_rate': 0.027171188622546392, 'num_leaves': 40, 'max_depth': 5, 'min_child_samples': 5, 'subsample': 0.8802429145804131, 'colsample_bytree': 0.7036066275753313, 'n_estimators': 1000}. Best is trial 3 with value: 0.4636041613881039.

Running time: 0.6 sec
OOF RMSE: 2.71 | R2: 0.39
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 22:51:38,620] Trial 13 finished with value: 0.4224253851156319 and parameters: {'learning_rate': 0.011728786562009132, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 18, 'subsample': 0.6786119234257738, 'colsample_bytree': 0.7127974529313567, 'n_estimators': 1000}. Best is trial 3 with value: 0.4636041613881039.

Fold 5
Running time: 0.5 sec
OOF RMSE: 2.63 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 22:51:39,089] Trial 14 finished with value: 0.4363296937809714 and parameters: {'learning_rate': 0.020540339942920857, 'num_leaves': 60, 'max_depth': 5, 'min_child_samples': 16, 'subsample': 0.8915911984167476, 'colsample_bytree': 0.8106079843167335, 'n_estimators': 1000}. Best is trial 3 with value: 0.4636041613881039.

Fold 5
Running time: 0.5 sec
OOF RMSE: 2.60 | R2: 0.44
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 22:51:39,627] Trial 15 finished with value: 0.45410116636901543 and parameters: {'learning_rate': 0.044918545562736355, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 14, 'subsample': 0.9377744113969995, 'colsample_bytree': 0.657103721343439, 'n_estimators': 1000}. Best is trial 3 with value: 0.4636041613881039.

Fold 5
Running time: 0.5 sec
OOF RMSE: 2.56 | R2: 0.45
Fold 1
Fold 2
Fold 3

[I 2025-07-11 22:51:40,127] Trial 16 finished with value: 0.4038063744513052 and parameters: {'learning_rate': 0.04824848195303589, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 7, 'subsample': 0.9484180667273581, 'colsample_bytree': 0.6001690786184155, 'n_estimators': 1000}. Best is trial 3 with value: 0.4636041613881039.

Fold 4
Fold 5
Running time: 0.5 sec
OOF RMSE: 2.68 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:51:40,661] Trial 17 finished with value: 0.38660299845797363 and parameters: {'learning_rate': 0.04532775076562696, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 19, 'subsample': 0.9297399905637601, 'colsample_bytree': 0.6699214160687351, 'n_estimators': 1000}. Best is trial 3 with value: 0.4636041613881039.

Running time: 0.5 sec
OOF RMSE: 2.71 | R2: 0.39
Fold 1
Fold 2
Fold 3

[I 2025-07-11 22:51:41,109] Trial 18 finished with value: 0.45328360526606815 and parameters: {'learning_rate': 0.059898126546617636, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 14, 'subsample': 0.9986518634142325, 'colsample_bytree': 0.6674489890389542, 'n_estimators': 1000}. Best is trial 3 with value: 0.4636041613881039.

Fold 4
Fold 5
Running time: 0.4 sec
OOF RMSE: 2.56 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 22:51:41,462] Trial 19 finished with value: 0.3689670310079919 and parameters: {'learning_rate': 0.0093764425526108, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 9, 'subsample': 0.9119159874724595, 'colsample_bytree': 0.734427361077141, 'n_estimators': 500}. Best is trial 3 with value: 0.4636041613881039.

Fold 5
Running time: 0.3 sec
OOF RMSE: 2.75 | R2: 0.37
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 22:51:41,995] Trial 20 finished with value: 0.3684890245464094 and parameters: {'learning_rate': 0.023043849872193805, 'num_leaves': 80, 'max_depth': 7, 'min_child_samples': 22, 'subsample': 0.8440465460027651, 'colsample_bytree': 0.8140154919148223, 'n_estimators': 1000}. Best is trial 3 with value: 0.4636041613881039.

Fold 5
Running time: 0.5 sec
OOF RMSE: 2.75 | R2: 0.37
Fold 1
Fold 2
Fold 3

[I 2025-07-11 22:51:42,483] Trial 21 finished with value: 0.43842628432947806 and parameters: {'learning_rate': 0.0487359742473113, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 13, 'subsample': 0.9865355227475097, 'colsample_bytree': 0.6723731741047645, 'n_estimators': 1000}. Best is trial 3 with value: 0.4636041613881039.

Fold 4
Fold 5
Running time: 0.5 sec
OOF RMSE: 2.60 | R2: 0.44
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 22:51:42,940] Trial 22 finished with value: 0.39313382307387723 and parameters: {'learning_rate': 0.06299589855747574, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 17, 'subsample': 0.9979573086740476, 'colsample_bytree': 0.67397454922081, 'n_estimators': 1000}. Best is trial 3 with value: 0.4636041613881039.

Fold 5
Running time: 0.5 sec
OOF RMSE: 2.70 | R2: 0.39
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:51:43,419] Trial 23 finished with value: 0.42605614915591516 and parameters: {'learning_rate': 0.06029041668148277, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 13, 'subsample': 0.9537071066052547, 'colsample_bytree': 0.601818374783139, 'n_estimators': 1000}. Best is trial 3 with value: 0.4636041613881039.

Running time: 0.5 sec
OOF RMSE: 2.63 | R2: 0.43
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:51:43,950] Trial 24 finished with value: 0.459930957790582 and parameters: {'learning_rate': 0.03013514324657338, 'num_leaves': 40, 'max_depth': 6, 'min_child_samples': 14, 'subsample': 0.8552160411870343, 'colsample_bytree': 0.6398324112912432, 'n_estimators': 1000}. Best is trial 3 with value: 0.4636041613881039.
[I 2025-07-11 22:51:43,951] A new study created in memory with name: no-name-206c7695-f844-4db8-a207-8bf13395a6b8

Running time: 0.5 sec
OOF RMSE: 2.55 | R2: 0.46

✅ LBM - Mejor R2: 0.46
📋 Parámetros: {'learning_rate': 0.012581930241940016, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 16, 'subsample': 0.9836704297719847, 'colsample_bytree': 0.6987702154799919, 'n_estimators': 1000}

Buscando mejores hiperparámetros para MLP...
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 22:51:44,649] Trial 0 finished with value: 0.5545484040924747 and parameters: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.00012522898757058283, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0046447383773033715}. Best is trial 0 with value: 0.5545484040924747.

Fold 5
Running time: 0.7 sec
OOF RMSE: 2.31 | R2: 0.55
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 22:51:45,909] Trial 1 finished with value: 0.4974106310048184 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.002099250442243355, 'learning_rate': 'constant', 'learning_rate_init': 0.002710907422476783}. Best is trial 0 with value: 0.5545484040924747.

Fold 5
Running time: 1.3 sec
OOF RMSE: 2.46 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 22:51:47,256] Trial 2 finished with value: 0.3984963166572084 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.00022700642909397338, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0005631182560012864}. Best is trial 0 with value: 0.5545484040924747.

Fold 5
Running time: 1.3 sec
OOF RMSE: 2.69 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 22:51:48,226] Trial 3 finished with value: 0.47879044887924216 and parameters: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.013984095790390559, 'learning_rate': 'constant', 'learning_rate_init': 0.0010513841164808732}. Best is trial 0 with value: 0.5545484040924747.

Fold 5
Running time: 1.0 sec
OOF RMSE: 2.50 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 22:51:49,579] Trial 4 finished with value: 0.4121373790555486 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 5.326186045482482e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.0010751438506989067}. Best is trial 0 with value: 0.5545484040924747.

Fold 5
Running time: 1.3 sec
OOF RMSE: 2.66 | R2: 0.41
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

[I 2025-07-11 22:51:52,559] Trial 5 finished with value: 0.3669140466895012 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'sgd', 'alpha': 1.6747886279390136e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0001294603872795843}. Best is trial 0 with value: 0.5545484040924747.

Running time: 3.0 sec
OOF RMSE: 2.76 | R2: 0.37
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

[I 2025-07-11 22:51:54,284] Trial 6 finished with value: 0.41635096478958167 and parameters: {'hidden_layer_sizes': '50', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.027147600363130454, 'learning_rate': 'adaptive', 'learning_rate_init': 0.006131999063327997}. Best is trial 0 with value: 0.5545484040924747.

Running time: 1.7 sec
OOF RMSE: 2.65 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 22:51:55,060] Trial 7 finished with value: 0.4152872398742249 and parameters: {'hidden_layer_sizes': '50', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.01236072397376251, 'learning_rate': 'constant', 'learning_rate_init': 0.008118186036935926}. Best is trial 0 with value: 0.5545484040924747.

Fold 5
Running time: 0.8 sec
OOF RMSE: 2.65 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 22:51:55,854] Trial 8 finished with value: 0.5322220112986283 and parameters: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.05182756560684678, 'learning_rate': 'constant', 'learning_rate_init': 0.0036811760347189235}. Best is trial 0 with value: 0.5545484040924747.

Fold 5
Running time: 0.8 sec
OOF RMSE: 2.37 | R2: 0.53
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 22:51:57,520] Trial 9 finished with value: 0.4311032555665568 and parameters: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.003070982649958652, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00023862742067999943}. Best is trial 0 with value: 0.5545484040924747.

Running time: 1.7 sec
OOF RMSE: 2.61 | R2: 0.43
Fold 1
Fold 2
Fold 3

[I 2025-07-11 22:51:58,237] Trial 10 finished with value: 0.4466113411090702 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.00028313151572567045, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0022225389242335586}. Best is trial 0 with value: 0.5545484040924747.

Fold 4
Fold 5
Running time: 0.7 sec
OOF RMSE: 2.58 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 22:51:59,029] Trial 11 finished with value: 0.531240646563232 and parameters: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.059112036259152116, 'learning_rate': 'constant', 'learning_rate_init': 0.003561973374733236}. Best is trial 0 with value: 0.5545484040924747.

Fold 5
Running time: 0.8 sec
OOF RMSE: 2.37 | R2: 0.53
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 22:51:59,677] Trial 12 finished with value: 0.49560533259664863 and parameters: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0002816529701252042, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00995737352682293}. Best is trial 0 with value: 0.5545484040924747.

Fold 5
Running time: 0.6 sec
OOF RMSE: 2.46 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 22:52:00,445] Trial 13 finished with value: 0.556698406524023 and parameters: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'adam', 'alpha': 1.036816551313713e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.004204678189048668}. Best is trial 13 with value: 0.556698406524023.

Fold 5
Running time: 0.8 sec
OOF RMSE: 2.31 | R2: 0.56
Fold 1
Fold 2
Fold 3

[I 2025-07-11 22:52:01,245] Trial 14 finished with value: 0.44879487554806274 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'relu', 'solver': 'adam', 'alpha': 1.100828823531969e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.0017641928715837472}. Best is trial 13 with value: 0.556698406524023.

Fold 4
Fold 5
Running time: 0.8 sec
OOF RMSE: 2.57 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 22:52:02,115] Trial 15 finished with value: 0.5636363980595728 and parameters: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'adam', 'alpha': 6.097608585774665e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0046041387585038585}. Best is trial 15 with value: 0.5636363980595728.

Fold 5
Running time: 0.9 sec
OOF RMSE: 2.29 | R2: 0.56
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 22:52:03,360] Trial 16 finished with value: 0.503348569995158 and parameters: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'adam', 'alpha': 3.084851231523889e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.0005489996726388472}. Best is trial 15 with value: 0.5636363980595728.

Running time: 1.2 sec
OOF RMSE: 2.44 | R2: 0.50
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 22:52:04,388] Trial 17 finished with value: 0.537191017331339 and parameters: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'adam', 'alpha': 6.0406331253471075e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.001623596744769699}. Best is trial 15 with value: 0.5636363980595728.

Fold 5
Running time: 1.0 sec
OOF RMSE: 2.36 | R2: 0.54
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:52:05,119] Trial 18 finished with value: 0.5357807472515563 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'relu', 'solver': 'adam', 'alpha': 2.4806786470478738e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.006005534171972257}. Best is trial 15 with value: 0.5636363980595728.

Running time: 0.7 sec
OOF RMSE: 2.36 | R2: 0.54
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 22:52:06,038] Trial 19 finished with value: 0.4186504406775893 and parameters: {'hidden_layer_sizes': '50', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0011905679855709903, 'learning_rate': 'constant', 'learning_rate_init': 0.0006041967441663743}. Best is trial 15 with value: 0.5636363980595728.

Fold 4
Fold 5
Running time: 0.9 sec
OOF RMSE: 2.64 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 22:52:06,822] Trial 20 finished with value: 0.5506220496714527 and parameters: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'adam', 'alpha': 9.333602191852528e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.0056192126982789175}. Best is trial 15 with value: 0.5636363980595728.

Fold 5
Running time: 0.8 sec
OOF RMSE: 2.32 | R2: 0.55
Fold 1
Fold 2
Fold 3

[I 2025-07-11 22:52:07,771] Trial 21 finished with value: 0.5466636609765345 and parameters: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.00012982682764329826, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00394053845609879}. Best is trial 15 with value: 0.5636363980595728.

Fold 4
Fold 5
Running time: 0.9 sec
OOF RMSE: 2.33 | R2: 0.55
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:52:08,549] Trial 22 finished with value: 0.5747064445290713 and parameters: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0005522912065996219, 'learning_rate': 'adaptive', 'learning_rate_init': 0.004290874088967187}. Best is trial 22 with value: 0.5747064445290713.

Running time: 0.8 sec
OOF RMSE: 2.26 | R2: 0.57
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 22:52:09,553] Trial 23 finished with value: 0.5266134066396821 and parameters: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0005356162790882632, 'learning_rate': 'adaptive', 'learning_rate_init': 0.002612570803323637}. Best is trial 22 with value: 0.5747064445290713.

Fold 5
Running time: 1.0 sec
OOF RMSE: 2.39 | R2: 0.53
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 22:52:10,719] Trial 24 finished with value: 0.5465520735670415 and parameters: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'adam', 'alpha': 3.579662943307959e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.001557932807754805}. Best is trial 22 with value: 0.5747064445290713.
[I 2025-07-11 22:52:10,720] A new study created in memory with name: no-name-1252837b-5200-4a99-88c0-c751bb2ddbef
[I 2025-07-11 22:52:10,805] Trial 0 finished with value: 0.0820266023342574 and parameters: {'kernel': 'sigmoid', 'C': 0.1270821592620765, 'epsilon': 0.041365215080430916, 'gamma': 'scale'}. Best is trial 0 with value: 0.0820266023342574.
[I 2025-07-11 22:52:10,877] Trial 1 finished with value: 0.24344862550855695 and parameters: {'kernel': 'rbf', 'C': 1.0018367750871195, 'epsilon': 0.08690689749959576, 'gamma': 'scale'}. Best is trial 1 with value: 0.24344862550855695.

Fold 5
Running time: 1.2 sec
OOF RMSE: 2.33 | R2: 0.55

✅ MLP - Mejor R2: 0.57
📋 Parámetros: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0005522912065996219, 'learning_rate': 'adaptive', 'learning_rate_init': 0.004290874088967187}

Buscando mejores hiperparámetros para SVR...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.32 | R2: 0.08
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.02 | R2: 0.24

[I 2025-07-11 22:52:10,958] Trial 2 finished with value: 0.43894430653041283 and parameters: {'kernel': 'rbf', 'C': 5.636319871519561, 'epsilon': 0.03212088119201273, 'gamma': 'scale'}. Best is trial 2 with value: 0.43894430653041283.
[I 2025-07-11 22:52:11,035] Trial 3 finished with value: -11.69832450417678 and parameters: {'kernel': 'sigmoid', 'C': 1.9178876537744496, 'epsilon': 0.07266923723130149, 'gamma': 'scale'}. Best is trial 2 with value: 0.43894430653041283.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.60 | R2: 0.44
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 12.35 | R2: -11.70
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 22:52:11,112] Trial 4 finished with value: -7.9439897589415605 and parameters: {'kernel': 'sigmoid', 'C': 1.730330692683646, 'epsilon': 0.10901690439338048, 'gamma': 'auto'}. Best is trial 2 with value: 0.43894430653041283.
[I 2025-07-11 22:52:11,185] Trial 5 finished with value: 0.07959664555102464 and parameters: {'kernel': 'sigmoid', 'C': 0.16183247853028476, 'epsilon': 0.18643222657725825, 'gamma': 'auto'}. Best is trial 2 with value: 0.43894430653041283.
[I 2025-07-11 22:52:11,259] Trial 6 finished with value: 0.3286393266516945 and parameters: {'kernel': 'rbf', 'C': 2.5030393875874215, 'epsilon': 0.1033486984668363, 'gamma': 'auto'}. Best is trial 2 with value: 0.43894430653041283.

Fold 5
Running time: 0.1 sec
OOF RMSE: 10.37 | R2: -7.94
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.33 | R2: 0.08
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.84 | R2: 0.33
Fold 1
Fold 2
Fold 3

[I 2025-07-11 22:52:11,332] Trial 7 finished with value: 0.1778492312687987 and parameters: {'kernel': 'rbf', 'C': 0.504028095414072, 'epsilon': 0.16190300541920913, 'gamma': 'auto'}. Best is trial 2 with value: 0.43894430653041283.
[I 2025-07-11 22:52:11,408] Trial 8 finished with value: -10.468889585444915 and parameters: {'kernel': 'sigmoid', 'C': 1.6336414667622878, 'epsilon': 0.1978427351658499, 'gamma': 'scale'}. Best is trial 2 with value: 0.43894430653041283.
[I 2025-07-11 22:52:11,491] Trial 9 finished with value: 0.12190677045609333 and parameters: {'kernel': 'rbf', 'C': 0.3324915596366685, 'epsilon': 0.04225649094691401, 'gamma': 'auto'}. Best is trial 2 with value: 0.43894430653041283.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.14 | R2: 0.18
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 11.74 | R2: -10.47
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.25 | R2: 0.12
Fold 1

[I 2025-07-11 22:52:11,583] Trial 10 finished with value: 0.464498371259389 and parameters: {'kernel': 'rbf', 'C': 9.694216967597729, 'epsilon': 0.02103672127699636, 'gamma': 'scale'}. Best is trial 10 with value: 0.464498371259389.
[I 2025-07-11 22:52:11,677] Trial 11 finished with value: 0.46375218108545946 and parameters: {'kernel': 'rbf', 'C': 9.532546494728459, 'epsilon': 0.010068385783941064, 'gamma': 'scale'}. Best is trial 10 with value: 0.464498371259389.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.54 | R2: 0.46
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.54 | R2: 0.46
Fold 1
Fold 2
Fold 3

[I 2025-07-11 22:52:11,766] Trial 12 finished with value: 0.4630297298963253 and parameters: {'kernel': 'rbf', 'C': 9.250815290718498, 'epsilon': 0.013934614207206444, 'gamma': 'scale'}. Best is trial 10 with value: 0.464498371259389.
[I 2025-07-11 22:52:11,857] Trial 13 finished with value: 0.42494481831909847 and parameters: {'kernel': 'rbf', 'C': 5.023392185641439, 'epsilon': 0.011768629346396718, 'gamma': 'scale'}. Best is trial 10 with value: 0.464498371259389.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.54 | R2: 0.46
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.63 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:52:11,942] Trial 14 finished with value: 0.45876014028270384 and parameters: {'kernel': 'rbf', 'C': 8.148321806448859, 'epsilon': 0.05914322918790173, 'gamma': 'scale'}. Best is trial 10 with value: 0.464498371259389.
[I 2025-07-11 22:52:12,022] Trial 15 finished with value: 0.3730991590599789 and parameters: {'kernel': 'rbf', 'C': 3.60077493481174, 'epsilon': 0.14958857433927852, 'gamma': 'scale'}. Best is trial 10 with value: 0.464498371259389.
[I 2025-07-11 22:52:12,108] Trial 16 finished with value: 0.4617454358990485 and parameters: {'kernel': 'rbf', 'C': 9.943768462968146, 'epsilon': 0.1290368563406605, 'gamma': 'scale'}. Best is trial 10 with value: 0.464498371259389.

Running time: 0.1 sec
OOF RMSE: 2.55 | R2: 0.46
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.74 | R2: 0.37
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.54 | R2: 0.46
Fold 1
Fold 2

[I 2025-07-11 22:52:12,188] Trial 17 finished with value: 0.37181426490602787 and parameters: {'kernel': 'rbf', 'C': 3.4851764946668933, 'epsilon': 0.0585159907862851, 'gamma': 'scale'}. Best is trial 10 with value: 0.464498371259389.
[I 2025-07-11 22:52:12,271] Trial 18 finished with value: 0.21907470803936224 and parameters: {'kernel': 'rbf', 'C': 0.8188300794425166, 'epsilon': 0.024770617712658996, 'gamma': 'scale'}. Best is trial 10 with value: 0.464498371259389.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.75 | R2: 0.37
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.06 | R2: 0.22
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:52:12,356] Trial 19 finished with value: 0.4422589839521205 and parameters: {'kernel': 'rbf', 'C': 5.873035015420354, 'epsilon': 0.05608808657563469, 'gamma': 'scale'}. Best is trial 10 with value: 0.464498371259389.
[I 2025-07-11 22:52:12,444] Trial 20 finished with value: 0.37048128962624827 and parameters: {'kernel': 'rbf', 'C': 3.4522061219972917, 'epsilon': 0.09327593080347, 'gamma': 'scale'}. Best is trial 10 with value: 0.464498371259389.
[I 2025-07-11 22:52:12,531] Trial 21 finished with value: 0.45793608079333015 and parameters: {'kernel': 'rbf', 'C': 7.955541251963781, 'epsilon': 0.01339155214200884, 'gamma': 'scale'}. Best is trial 10 with value: 0.464498371259389.

Running time: 0.1 sec
OOF RMSE: 2.59 | R2: 0.44
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.75 | R2: 0.37
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.55 | R2: 0.46
Fold 1

[I 2025-07-11 22:52:12,634] Trial 22 finished with value: 0.4455040759418768 and parameters: {'kernel': 'rbf', 'C': 6.257524262401835, 'epsilon': 0.010097205262511934, 'gamma': 'scale'}. Best is trial 10 with value: 0.464498371259389.
[I 2025-07-11 22:52:12,721] Trial 23 finished with value: 0.40157503471559886 and parameters: {'kernel': 'rbf', 'C': 4.297060115220316, 'epsilon': 0.030330048908052687, 'gamma': 'scale'}. Best is trial 10 with value: 0.464498371259389.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.58 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.68 | R2: 0.40
Fold 1
Fold 2

[I 2025-07-11 22:52:12,813] Trial 24 finished with value: 0.4639873210607711 and parameters: {'kernel': 'rbf', 'C': 9.427776821665788, 'epsilon': 0.04454472476076494, 'gamma': 'scale'}. Best is trial 10 with value: 0.464498371259389.
[I 2025-07-11 22:52:12,814] A new study created in memory with name: no-name-4f662567-1f20-499c-a2c1-16c7809946b8
[I 2025-07-11 22:52:12,878] Trial 0 finished with value: 0.5093066551814336 and parameters: {'n_neighbors': 12, 'weights': 'uniform', 'leaf_size': 20}. Best is trial 0 with value: 0.5093066551814336.
[I 2025-07-11 22:52:12,944] Trial 1 finished with value: 0.5680016295038939 and parameters: {'n_neighbors': 10, 'weights': 'distance', 'leaf_size': 14}. Best is trial 1 with value: 0.5680016295038939.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.54 | R2: 0.46

✅ SVR - Mejor R2: 0.46
📋 Parámetros: {'kernel': 'rbf', 'C': 9.694216967597729, 'epsilon': 0.02103672127699636, 'gamma': 'scale'}

Buscando mejores hiperparámetros para KNN...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.43 | R2: 0.51
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.28 | R2: 0.57
Fold 1
Fold 2

[I 2025-07-11 22:52:13,010] Trial 2 finished with value: 0.5502979662297396 and parameters: {'n_neighbors': 15, 'weights': 'distance', 'leaf_size': 23}. Best is trial 1 with value: 0.5680016295038939.
[I 2025-07-11 22:52:13,074] Trial 3 finished with value: 0.5943700810463782 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 25}. Best is trial 3 with value: 0.5943700810463782.
[I 2025-07-11 22:52:13,140] Trial 4 finished with value: 0.5580840634630375 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'leaf_size': 15}. Best is trial 3 with value: 0.5943700810463782.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.32 | R2: 0.55
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.21 | R2: 0.59
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.30 | R2: 0.56
Fold 1
Fold 2
Fold 3

[I 2025-07-11 22:52:13,205] Trial 5 finished with value: 0.5541756167594969 and parameters: {'n_neighbors': 9, 'weights': 'distance', 'leaf_size': 35}. Best is trial 3 with value: 0.5943700810463782.
[I 2025-07-11 22:52:13,274] Trial 6 finished with value: 0.5677794044102462 and parameters: {'n_neighbors': 11, 'weights': 'distance', 'leaf_size': 29}. Best is trial 3 with value: 0.5943700810463782.
[I 2025-07-11 22:52:13,339] Trial 7 finished with value: 0.5677794044102462 and parameters: {'n_neighbors': 11, 'weights': 'distance', 'leaf_size': 31}. Best is trial 3 with value: 0.5943700810463782.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.31 | R2: 0.55
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.28 | R2: 0.57
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.28 | R2: 0.57
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 22:52:13,404] Trial 8 finished with value: 0.5115854969222845 and parameters: {'n_neighbors': 8, 'weights': 'uniform', 'leaf_size': 17}. Best is trial 3 with value: 0.5943700810463782.
[I 2025-07-11 22:52:13,468] Trial 9 finished with value: 0.5975831210518429 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'leaf_size': 10}. Best is trial 9 with value: 0.5975831210518429.
[I 2025-07-11 22:52:13,542] Trial 10 finished with value: 0.565214590907738 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'leaf_size': 11}. Best is trial 9 with value: 0.5975831210518429.

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.42 | R2: 0.51
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.20 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.29 | R2: 0.57
Fold 1
Fold 2
Fold 3

[I 2025-07-11 22:52:13,621] Trial 11 finished with value: 0.5943700810463782 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 40}. Best is trial 9 with value: 0.5975831210518429.
[I 2025-07-11 22:52:13,695] Trial 12 finished with value: 0.576156314783348 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'leaf_size': 26}. Best is trial 9 with value: 0.5975831210518429.
[I 2025-07-11 22:52:13,766] Trial 13 finished with value: 0.576156314783348 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'leaf_size': 10}. Best is trial 9 with value: 0.5975831210518429.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.21 | R2: 0.59
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.26 | R2: 0.58
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.26 | R2: 0.58
Fold 1
Fold 2

[I 2025-07-11 22:52:13,840] Trial 14 finished with value: 0.4789983540621786 and parameters: {'n_neighbors': 7, 'weights': 'uniform', 'leaf_size': 20}. Best is trial 9 with value: 0.5975831210518429.
[I 2025-07-11 22:52:13,912] Trial 15 finished with value: 0.5943700810463782 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 34}. Best is trial 9 with value: 0.5975831210518429.
[I 2025-07-11 22:52:13,985] Trial 16 finished with value: 0.576156314783348 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'leaf_size': 24}. Best is trial 9 with value: 0.5975831210518429.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.50 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.21 | R2: 0.59
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.26 | R2: 0.58
Fold 1

[I 2025-07-11 22:52:14,059] Trial 17 finished with value: 0.5975831210518429 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'leaf_size': 40}. Best is trial 9 with value: 0.5975831210518429.
[I 2025-07-11 22:52:14,132] Trial 18 finished with value: 0.4789983540621786 and parameters: {'n_neighbors': 7, 'weights': 'uniform', 'leaf_size': 40}. Best is trial 9 with value: 0.5975831210518429.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.20 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.50 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 22:52:14,243] Trial 19 finished with value: 0.5611105188247868 and parameters: {'n_neighbors': 14, 'weights': 'distance', 'leaf_size': 37}. Best is trial 9 with value: 0.5975831210518429.
[I 2025-07-11 22:52:14,316] Trial 20 finished with value: 0.576156314783348 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'leaf_size': 29}. Best is trial 9 with value: 0.5975831210518429.
[I 2025-07-11 22:52:14,397] Trial 21 finished with value: 0.5975831210518429 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'leaf_size': 20}. Best is trial 9 with value: 0.5975831210518429.

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.30 | R2: 0.56
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.26 | R2: 0.58
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.20 | R2: 0.60
Fold 1
Fold 2

[I 2025-07-11 22:52:14,472] Trial 22 finished with value: 0.5975831210518429 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'leaf_size': 19}. Best is trial 9 with value: 0.5975831210518429.
[I 2025-07-11 22:52:14,559] Trial 23 finished with value: 0.5374148758598335 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'leaf_size': 12}. Best is trial 9 with value: 0.5975831210518429.
[I 2025-07-11 22:52:14,635] Trial 24 finished with value: 0.5975831210518429 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'leaf_size': 22}. Best is trial 9 with value: 0.5975831210518429.
[I 2025-07-11 22:52:14,636] A new study created in memory with name: no-name-cf0d17f0-b9de-4666-866a-96a6d1492e20

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.20 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.36 | R2: 0.54
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.20 | R2: 0.60

✅ KNN - Mejor R2: 0.60
📋 Parámetros: {'n_neighbors': 4, 'weights': 'distance', 'leaf_size': 10}

Buscando mejores hiperparámetros para LR...

[I 2025-07-11 22:52:14,700] Trial 0 finished with value: -0.02780913150713049 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: -0.02780913150713049.
[I 2025-07-11 22:52:14,761] Trial 1 finished with value: -0.02780913150713049 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: -0.02780913150713049.
[I 2025-07-11 22:52:14,837] Trial 2 finished with value: 0.14366362986987236 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 2 with value: 0.14366362986987236.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.51 | R2: -0.03
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.51 | R2: -0.03
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.21 | R2: 0.14

[I 2025-07-11 22:52:14,939] Trial 3 finished with value: -0.02784702972007458 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 2 with value: 0.14366362986987236.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.51 | R2: -0.03
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:52:15,080] Trial 4 finished with value: 0.14366362986325965 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 2 with value: 0.14366362986987236.
[I 2025-07-11 22:52:15,219] Trial 5 finished with value: 0.14366362986987236 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 2 with value: 0.14366362986987236.

Running time: 0.1 sec
OOF RMSE: 3.21 | R2: 0.14
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.21 | R2: 0.14
Fold 1
Fold 2

[I 2025-07-11 22:52:15,323] Trial 6 finished with value: -0.02780913150713049 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 2 with value: 0.14366362986987236.
[I 2025-07-11 22:52:15,385] Trial 7 finished with value: -0.02780913150713049 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 2 with value: 0.14366362986987236.
[I 2025-07-11 22:52:15,449] Trial 8 finished with value: -0.02784702972007458 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 2 with value: 0.14366362986987236.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.51 | R2: -0.03
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.51 | R2: -0.03
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.51 | R2: -0.03
Fold 1
Fold 2
Fold 3

[I 2025-07-11 22:52:15,525] Trial 9 finished with value: 0.14366362986325965 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 2 with value: 0.14366362986987236.
[I 2025-07-11 22:52:15,648] Trial 10 finished with value: 0.14366362986987236 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 2 with value: 0.14366362986987236.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.21 | R2: 0.14
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.21 | R2: 0.14
Fold 1
Fold 2

[I 2025-07-11 22:52:15,818] Trial 11 finished with value: 0.14366362986987236 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 2 with value: 0.14366362986987236.

Fold 3
Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 3.21 | R2: 0.14
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:52:15,932] Trial 12 finished with value: 0.14366362986987236 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 2 with value: 0.14366362986987236.
[I 2025-07-11 22:52:16,070] Trial 13 finished with value: 0.14366362986987236 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 2 with value: 0.14366362986987236.

Running time: 0.1 sec
OOF RMSE: 3.21 | R2: 0.14
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.21 | R2: 0.14
Fold 1
Fold 2
Fold 3

[I 2025-07-11 22:52:16,203] Trial 14 finished with value: 0.14366362986987236 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 2 with value: 0.14366362986987236.
[I 2025-07-11 22:52:16,346] Trial 15 finished with value: 0.14366362986987236 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 2 with value: 0.14366362986987236.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.21 | R2: 0.14
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.21 | R2: 0.14
Fold 1

[I 2025-07-11 22:52:16,445] Trial 16 finished with value: 0.14366362986987236 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 2 with value: 0.14366362986987236.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.21 | R2: 0.14
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:52:16,589] Trial 17 finished with value: 0.14366362986987236 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 2 with value: 0.14366362986987236.
[I 2025-07-11 22:52:16,690] Trial 18 finished with value: 0.14366362986987236 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 2 with value: 0.14366362986987236.
[I 2025-07-11 22:52:16,778] Trial 19 finished with value: 0.14366362986987236 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 2 with value: 0.14366362986987236.

Running time: 0.1 sec
OOF RMSE: 3.21 | R2: 0.14
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.21 | R2: 0.14
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.21 | R2: 0.14
Fold 1

[I 2025-07-11 22:52:16,865] Trial 20 finished with value: 0.14366362986987236 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 2 with value: 0.14366362986987236.
[I 2025-07-11 22:52:16,970] Trial 21 finished with value: 0.14366362986987236 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 2 with value: 0.14366362986987236.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.21 | R2: 0.14
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.21 | R2: 0.14
Fold 1
Fold 2

[I 2025-07-11 22:52:17,064] Trial 22 finished with value: 0.14366362986987236 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 2 with value: 0.14366362986987236.
[I 2025-07-11 22:52:17,189] Trial 23 finished with value: 0.14366362986987236 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 2 with value: 0.14366362986987236.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.21 | R2: 0.14
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.21 | R2: 0.14
Fold 1

[I 2025-07-11 22:52:17,344] Trial 24 finished with value: 0.14366362986987236 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 2 with value: 0.14366362986987236.
[I 2025-07-11 22:52:17,346] A new study created in memory with name: no-name-3bf2c2c8-c15d-451b-9048-f53faa8499f6

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.21 | R2: 0.14

✅ LR - Mejor R2: 0.14
📋 Parámetros: {'fit_intercept': False, 'positive': False}

Buscando mejores hiperparámetros para RF...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:52:19,012] Trial 0 finished with value: 0.39740245236931604 and parameters: {'n_estimators': 100, 'max_depth': 9, 'min_samples_split': 3, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 0 with value: 0.39740245236931604.

Running time: 1.7 sec
OOF RMSE: 2.69 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:52:26,607] Trial 1 finished with value: -0.18661176681915492 and parameters: {'n_estimators': 300, 'max_depth': 8, 'min_samples_split': 3, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 0 with value: 0.39740245236931604.

Running time: 7.6 sec
OOF RMSE: 3.78 | R2: -0.19
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:52:30,936] Trial 2 finished with value: 0.3955578514266007 and parameters: {'n_estimators': 300, 'max_depth': 8, 'min_samples_split': 8, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 0 with value: 0.39740245236931604.

Running time: 4.3 sec
OOF RMSE: 2.70 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:52:39,294] Trial 3 finished with value: 0.39647967053340016 and parameters: {'n_estimators': 500, 'max_depth': 11, 'min_samples_split': 8, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 0 with value: 0.39740245236931604.

Running time: 8.4 sec
OOF RMSE: 2.69 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:52:41,916] Trial 4 finished with value: -0.0943379226416372 and parameters: {'n_estimators': 100, 'max_depth': 14, 'min_samples_split': 9, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 0 with value: 0.39740245236931604.

Running time: 2.6 sec
OOF RMSE: 3.63 | R2: -0.09
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:52:49,299] Trial 5 finished with value: 0.3864919579727474 and parameters: {'n_estimators': 500, 'max_depth': 14, 'min_samples_split': 10, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 0 with value: 0.39740245236931604.

Running time: 7.4 sec
OOF RMSE: 2.72 | R2: 0.39
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:52:50,933] Trial 6 finished with value: 0.37668041382492334 and parameters: {'n_estimators': 100, 'max_depth': 14, 'min_samples_split': 10, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 0 with value: 0.39740245236931604.

Running time: 1.6 sec
OOF RMSE: 2.74 | R2: 0.38
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:52:57,945] Trial 7 finished with value: 0.3842255244991464 and parameters: {'n_estimators': 500, 'max_depth': 15, 'min_samples_split': 6, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 0 with value: 0.39740245236931604.

Running time: 7.0 sec
OOF RMSE: 2.72 | R2: 0.38
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:52:59,469] Trial 8 finished with value: 0.3916259238595018 and parameters: {'n_estimators': 100, 'max_depth': 11, 'min_samples_split': 4, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 0 with value: 0.39740245236931604.

Running time: 1.5 sec
OOF RMSE: 2.70 | R2: 0.39
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:53:01,812] Trial 9 finished with value: 0.17271291487297113 and parameters: {'n_estimators': 100, 'max_depth': 12, 'min_samples_split': 5, 'min_samples_leaf': 4, 'bootstrap': False}. Best is trial 0 with value: 0.39740245236931604.

Running time: 2.3 sec
OOF RMSE: 3.15 | R2: 0.17
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:53:03,569] Trial 10 finished with value: -0.01724107124895724 and parameters: {'n_estimators': 100, 'max_depth': 5, 'min_samples_split': 2, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 0 with value: 0.39740245236931604.

Running time: 1.8 sec
OOF RMSE: 3.50 | R2: -0.02
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:53:11,777] Trial 11 finished with value: 0.39788234449432425 and parameters: {'n_estimators': 500, 'max_depth': 9, 'min_samples_split': 7, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 11 with value: 0.39788234449432425.

Running time: 8.2 sec
OOF RMSE: 2.69 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:53:19,986] Trial 12 finished with value: 0.3826752081300895 and parameters: {'n_estimators': 500, 'max_depth': 8, 'min_samples_split': 7, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 11 with value: 0.39788234449432425.

Running time: 8.2 sec
OOF RMSE: 2.72 | R2: 0.38
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:53:26,825] Trial 13 finished with value: 0.40146417503602927 and parameters: {'n_estimators': 500, 'max_depth': 6, 'min_samples_split': 5, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 13 with value: 0.40146417503602927.

Running time: 6.8 sec
OOF RMSE: 2.68 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:53:33,810] Trial 14 finished with value: 0.4036419761142478 and parameters: {'n_estimators': 500, 'max_depth': 6, 'min_samples_split': 6, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 14 with value: 0.4036419761142478.

Running time: 7.0 sec
OOF RMSE: 2.68 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:53:40,031] Trial 15 finished with value: 0.40052853028411106 and parameters: {'n_estimators': 500, 'max_depth': 5, 'min_samples_split': 5, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 14 with value: 0.4036419761142478.

Running time: 6.2 sec
OOF RMSE: 2.68 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:53:47,217] Trial 16 finished with value: 0.4006262132535674 and parameters: {'n_estimators': 500, 'max_depth': 6, 'min_samples_split': 5, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 14 with value: 0.4036419761142478.

Running time: 7.2 sec
OOF RMSE: 2.68 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:53:53,620] Trial 17 finished with value: 0.38375768234419005 and parameters: {'n_estimators': 500, 'max_depth': 6, 'min_samples_split': 6, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 14 with value: 0.4036419761142478.

Running time: 6.4 sec
OOF RMSE: 2.72 | R2: 0.38
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:54:00,294] Trial 18 finished with value: -0.10861527567852858 and parameters: {'n_estimators': 300, 'max_depth': 7, 'min_samples_split': 4, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 14 with value: 0.4036419761142478.

Running time: 6.7 sec
OOF RMSE: 3.65 | R2: -0.11
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:54:07,072] Trial 19 finished with value: 0.3992748783295085 and parameters: {'n_estimators': 500, 'max_depth': 6, 'min_samples_split': 7, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 14 with value: 0.4036419761142478.

Running time: 6.8 sec
OOF RMSE: 2.69 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:54:14,380] Trial 20 finished with value: 0.3998389840262935 and parameters: {'n_estimators': 500, 'max_depth': 7, 'min_samples_split': 4, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 14 with value: 0.4036419761142478.

Running time: 7.3 sec
OOF RMSE: 2.69 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:54:21,583] Trial 21 finished with value: 0.4006262132535674 and parameters: {'n_estimators': 500, 'max_depth': 6, 'min_samples_split': 5, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 14 with value: 0.4036419761142478.

Running time: 7.2 sec
OOF RMSE: 2.68 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:54:28,026] Trial 22 finished with value: 0.3925848464038346 and parameters: {'n_estimators': 500, 'max_depth': 5, 'min_samples_split': 6, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 14 with value: 0.4036419761142478.

Running time: 6.4 sec
OOF RMSE: 2.70 | R2: 0.39
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:54:35,605] Trial 23 finished with value: 0.41039606254512495 and parameters: {'n_estimators': 500, 'max_depth': 7, 'min_samples_split': 5, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 23 with value: 0.41039606254512495.

Running time: 7.6 sec
OOF RMSE: 2.66 | R2: 0.41
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:54:43,253] Trial 24 finished with value: 0.41617027383005556 and parameters: {'n_estimators': 500, 'max_depth': 7, 'min_samples_split': 3, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 24 with value: 0.41617027383005556.
[I 2025-07-11 22:54:43,254] A new study created in memory with name: no-name-5146c898-f0f1-4501-a2f7-678c7974f782

Running time: 7.6 sec
OOF RMSE: 2.65 | R2: 0.42

✅ RF - Mejor R2: 0.42
📋 Parámetros: {'n_estimators': 500, 'max_depth': 7, 'min_samples_split': 3, 'min_samples_leaf': 2, 'bootstrap': True}

Buscando mejores hiperparámetros para CAT...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:55:53,865] Trial 0 finished with value: 0.5969769813253292 and parameters: {'iterations': 2000, 'learning_rate': 0.03995023831193371, 'depth': 8, 'l2_leaf_reg': 9.757841855920907}. Best is trial 0 with value: 0.5969769813253292.

Running time: 70.6 sec
OOF RMSE: 2.20 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:57:15,994] Trial 1 finished with value: 0.6057071674332546 and parameters: {'iterations': 1000, 'learning_rate': 0.07744300097517999, 'depth': 9, 'l2_leaf_reg': 7.349325236490775}. Best is trial 1 with value: 0.6057071674332546.

Running time: 82.1 sec
OOF RMSE: 2.18 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 22:57:19,016] Trial 2 finished with value: 0.5380568579030465 and parameters: {'iterations': 1000, 'learning_rate': 0.06394643257321408, 'depth': 4, 'l2_leaf_reg': 3.3362880708193723}. Best is trial 1 with value: 0.6057071674332546.

Running time: 3.0 sec
OOF RMSE: 2.36 | R2: 0.54
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:00:01,432] Trial 3 finished with value: 0.5852483839495146 and parameters: {'iterations': 2000, 'learning_rate': 0.023696619066986162, 'depth': 9, 'l2_leaf_reg': 7.294155458543361}. Best is trial 1 with value: 0.6057071674332546.

Running time: 162.4 sec
OOF RMSE: 2.23 | R2: 0.59
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:00:08,393] Trial 4 finished with value: 0.5691688582922446 and parameters: {'iterations': 500, 'learning_rate': 0.057457016614298674, 'depth': 7, 'l2_leaf_reg': 6.042299514998918}. Best is trial 1 with value: 0.6057071674332546.

Running time: 7.0 sec
OOF RMSE: 2.28 | R2: 0.57
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:01:18,770] Trial 5 finished with value: 0.5924680558828672 and parameters: {'iterations': 500, 'learning_rate': 0.043381935082974506, 'depth': 10, 'l2_leaf_reg': 3.883521789856247}. Best is trial 1 with value: 0.6057071674332546.

Running time: 70.4 sec
OOF RMSE: 2.21 | R2: 0.59
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:02:28,696] Trial 6 finished with value: 0.601620967347855 and parameters: {'iterations': 500, 'learning_rate': 0.014632714584679742, 'depth': 10, 'l2_leaf_reg': 2.406791129601096}. Best is trial 1 with value: 0.6057071674332546.

Running time: 69.9 sec
OOF RMSE: 2.19 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:04:50,602] Trial 7 finished with value: 0.5958416858760036 and parameters: {'iterations': 1000, 'learning_rate': 0.030573242734569597, 'depth': 10, 'l2_leaf_reg': 2.4081754096573786}. Best is trial 1 with value: 0.6057071674332546.
[I 2025-07-11 23:04:50,603] A new study created in memory with name: no-name-11be0ece-ac7c-4eed-b867-4b3acb2bae45
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.548e+01, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.854e+01, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.408e+01, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.752e+01, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.065e+01, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 23:04:50,704] Trial 0 finished with value: 0.4576449064065584 and parameters: {'alpha': 0.0039386695226489655, 'l1_ratio': 0.6340376634874344}. Best is trial 0 with value: 0.4576449064065584.

Running time: 141.9 sec
OOF RMSE: 2.20 | R2: 0.60

✅ CAT - Mejor R2: 0.61
📋 Parámetros: {'iterations': 1000, 'learning_rate': 0.07744300097517999, 'depth': 9, 'l2_leaf_reg': 7.349325236490775}

Buscando mejores hiperparámetros para EN...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.55 | R2: 0.46
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.838e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.908e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.608e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.945e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.704e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 23:04:50,824] Trial 1 finished with value: 0.38060610396413175 and parameters: {'alpha': 0.00048799616988655343, 'l1_ratio': 0.6114058085000714}. Best is trial 0 with value: 0.4576449064065584.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.235e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.156e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.964e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.204e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.460e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 23:04:50,938] Trial 2 finished with value: 0.38854129192990605 and parameters: {'alpha': 0.0005186826728208652, 'l1_ratio': 0.35505121406521145}. Best is trial 0 with value: 0.4576449064065584.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.730e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.990e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.370e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(

Running time: 0.1 sec
OOF RMSE: 2.73 | R2: 0.38
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.71 | R2: 0.39
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.609e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.103e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 23:04:51,056] Trial 3 finished with value: 0.3911973819368417 and parameters: {'alpha': 0.00047032528059602017, 'l1_ratio': 0.16854210329411623}. Best is trial 0 with value: 0.4576449064065584.
[I 2025-07-11 23:04:51,167] Trial 4 finished with value: 0.3892528763543017 and parameters: {'alpha': 0.2848978455406804, 'l1_ratio': 0.1345292957254226}. Best is trial 0 with value: 0.4576449064065584.

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.70 | R2: 0.39
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.71 | R2: 0.39
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.475e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.072e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.194e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.462e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.610e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 23:04:51,375] Trial 5 finished with value: 0.3696625108983189 and parameters: {'alpha': 0.0001827730826331086, 'l1_ratio': 0.7158692256384209}. Best is trial 0 with value: 0.4576449064065584.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 2.75 | R2: 0.37
Fold 1
Fold 2
Fold 3

[I 2025-07-11 23:04:51,531] Trial 6 finished with value: 0.027083874164009147 and parameters: {'alpha': 3.9525698330645525, 'l1_ratio': 0.4833986500252616}. Best is trial 0 with value: 0.4576449064065584.

Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 3.42 | R2: 0.03
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.152e+01, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.196e+01, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.760e+01, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.962e+01, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.860e+01, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 23:04:51,695] Trial 7 finished with value: 0.4755848419501464 and parameters: {'alpha': 0.009619027324977027, 'l1_ratio': 0.26586293804459993}. Best is trial 7 with value: 0.4755848419501464.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.458e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.007e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.168e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.449e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.590e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 23:04:51,824] Trial 8 finished with value: 0.37243747568782126 and parameters: {'alpha': 0.0002225782149409883, 'l1_ratio': 0.59937087558955}. Best is trial 7 with value: 0.4755848419501464.

Running time: 0.2 sec
OOF RMSE: 2.51 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.75 | R2: 0.37
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.314e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.692e+01, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.630e+01, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.671e+01, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.397e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 23:04:51,953] Trial 9 finished with value: 0.4514845469652009 and parameters: {'alpha': 0.021988010832291602, 'l1_ratio': 0.07056032460789308}. Best is trial 7 with value: 0.4755848419501464.
[I 2025-07-11 23:04:52,045] Trial 10 finished with value: 0.36858852513866036 and parameters: {'alpha': 0.13802570941358633, 'l1_ratio': 0.9323077619417293}. Best is trial 7 with value: 0.4755848419501464.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.57 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.75 | R2: 0.37
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.590e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.410e+01, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.091e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.356e+01, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.037e+01, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 23:04:52,190] Trial 11 finished with value: 0.47410170191514445 and parameters: {'alpha': 0.005285178925194771, 'l1_ratio': 0.32890226185725374}. Best is trial 7 with value: 0.4755848419501464.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.543e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.814e+01, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.598e+01, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.51 | R2: 0.47
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.281e+01, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.585e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 23:04:52,320] Trial 12 finished with value: 0.47698369036344257 and parameters: {'alpha': 0.0069236650677369175, 'l1_ratio': 0.32249707501130237}. Best is trial 12 with value: 0.47698369036344257.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.793e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.431e+01, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.193e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.190e+01, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.173e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 23:04:52,466] Trial 13 finished with value: 0.4761635297803237 and parameters: {'alpha': 0.005920148438002107, 'l1_ratio': 0.3020369794283603}. Best is trial 12 with value: 0.47698369036344257.

Running time: 0.1 sec
OOF RMSE: 2.51 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.51 | R2: 0.48
Fold 1
Fold 2
Fold 3

[I 2025-07-11 23:04:52,575] Trial 14 finished with value: 0.405094460025617 and parameters: {'alpha': 0.10769921585817374, 'l1_ratio': 0.4455190577853961}. Best is trial 12 with value: 0.47698369036344257.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.129e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.606e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.730e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.587e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.775e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 23:04:52,727] Trial 15 finished with value: 0.4378101048584677 and parameters: {'alpha': 0.0017440251067260967, 'l1_ratio': 0.015983407803658256}. Best is trial 12 with value: 0.47698369036344257.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.67 | R2: 0.41
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.60 | R2: 0.44

[I 2025-07-11 23:04:52,892] Trial 16 finished with value: 0.43228308845919794 and parameters: {'alpha': 0.03574066423933884, 'l1_ratio': 0.24424735972236808}. Best is trial 12 with value: 0.47698369036344257.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 2.61 | R2: 0.43
Fold 1
Fold 2

[I 2025-07-11 23:04:53,033] Trial 17 finished with value: 0.2878257707133559 and parameters: {'alpha': 0.875377172417081, 'l1_ratio': 0.8568517047643707}. Best is trial 12 with value: 0.47698369036344257.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.261e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.133e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.383e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.863e+01, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.073e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 23:04:53,169] Trial 18 finished with value: 0.4176860604655591 and parameters: {'alpha': 0.0014493237287183135, 'l1_ratio': 0.380120478409275}. Best is trial 12 with value: 0.47698369036344257.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.93 | R2: 0.29
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.65 | R2: 0.42

[I 2025-07-11 23:04:53,290] Trial 19 finished with value: 0.4324455328677259 and parameters: {'alpha': 0.03598972157378147, 'l1_ratio': 0.20224166621589504}. Best is trial 12 with value: 0.47698369036344257.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.61 | R2: 0.43
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.581e-01, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 23:04:53,424] Trial 20 finished with value: 0.4623091439071896 and parameters: {'alpha': 0.015519856459317903, 'l1_ratio': 0.49931076654720397}. Best is trial 12 with value: 0.47698369036344257.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.712e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.562e+01, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.276e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.815e+01, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.059e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 23:04:53,545] Trial 21 finished with value: 0.4753341345933174 and parameters: {'alpha': 0.005431757527899453, 'l1_ratio': 0.27943049687081334}. Best is trial 12 with value: 0.47698369036344257.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.063e+01, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(

Running time: 0.1 sec
OOF RMSE: 2.54 | R2: 0.46
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.51 | R2: 0.48
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.317e+00, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.041e+01, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.527e+00, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.960e+01, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 23:04:53,674] Trial 22 finished with value: 0.4749505480711438 and parameters: {'alpha': 0.009342548180430017, 'l1_ratio': 0.39172861460534125}. Best is trial 12 with value: 0.47698369036344257.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.419e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.515e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.869e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.51 | R2: 0.47
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.991e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.971e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 23:04:53,863] Trial 23 finished with value: 0.43581115509497304 and parameters: {'alpha': 0.0017675958626203686, 'l1_ratio': 0.11603497282321654}. Best is trial 12 with value: 0.47698369036344257.
[I 2025-07-11 23:04:53,971] Trial 24 finished with value: 0.4107603853727939 and parameters: {'alpha': 0.08017575195428786, 'l1_ratio': 0.29013107679494904}. Best is trial 12 with value: 0.47698369036344257.
[I 2025-07-11 23:04:53,972] A new study created in memory with name: no-name-72e715a2-2feb-4574-bb0a-96545997064e

Fold 5
Running time: 0.2 sec
OOF RMSE: 2.60 | R2: 0.44
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.66 | R2: 0.41

✅ EN - Mejor R2: 0.48
📋 Parámetros: {'alpha': 0.0069236650677369175, 'l1_ratio': 0.32249707501130237}

🔍 Optimizando en C2RCC_rhow_3x3_depth_lt_1...
Buscando mejores hiperparámetros para XGB...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:05:09,775] Trial 0 finished with value: 0.6931783648596941 and parameters: {'n_estimators': 2000, 'learning_rate': 0.0066297338697652135, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.61746504819819, 'colsample_bytree': 0.6770895324669373}. Best is trial 0 with value: 0.6931783648596941.

Running time: 15.8 sec
OOF RMSE: 1.92 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:05:16,788] Trial 1 finished with value: 0.7054363579659854 and parameters: {'n_estimators': 1000, 'learning_rate': 0.034683326025374495, 'max_depth': 8, 'min_child_weight': 2, 'subsample': 0.9495468701288149, 'colsample_bytree': 0.64287837419033}. Best is trial 1 with value: 0.7054363579659854.

Running time: 7.0 sec
OOF RMSE: 1.88 | R2: 0.71
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:05:20,090] Trial 2 finished with value: 0.6447809048704263 and parameters: {'n_estimators': 500, 'learning_rate': 0.04159408496200133, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.8581552264310389, 'colsample_bytree': 0.7226499994766776}. Best is trial 1 with value: 0.7054363579659854.

Running time: 3.3 sec
OOF RMSE: 2.07 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:05:25,730] Trial 3 finished with value: 0.6340960617181222 and parameters: {'n_estimators': 1000, 'learning_rate': 0.07191472600155163, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.9331700582462906, 'colsample_bytree': 0.9167252855067266}. Best is trial 1 with value: 0.7054363579659854.

Running time: 5.6 sec
OOF RMSE: 2.10 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:05:33,362] Trial 4 finished with value: 0.6650084516992251 and parameters: {'n_estimators': 1000, 'learning_rate': 0.005019937036180366, 'max_depth': 8, 'min_child_weight': 4, 'subsample': 0.8957458283946996, 'colsample_bytree': 0.761132517574841}. Best is trial 1 with value: 0.7054363579659854.

Running time: 7.6 sec
OOF RMSE: 2.01 | R2: 0.67
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:05:45,276] Trial 5 finished with value: 0.6624253271952271 and parameters: {'n_estimators': 2000, 'learning_rate': 0.019724070715868236, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.7031385819770019, 'colsample_bytree': 0.7238061406687227}. Best is trial 1 with value: 0.7054363579659854.

Running time: 11.9 sec
OOF RMSE: 2.01 | R2: 0.66
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:05:52,252] Trial 6 finished with value: 0.710465365467519 and parameters: {'n_estimators': 1000, 'learning_rate': 0.005048387417334193, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.7240795259765459, 'colsample_bytree': 0.8488969720425793}. Best is trial 6 with value: 0.710465365467519.

Running time: 7.0 sec
OOF RMSE: 1.87 | R2: 0.71
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:06:02,907] Trial 7 finished with value: 0.6487974107499739 and parameters: {'n_estimators': 2000, 'learning_rate': 0.042724035193912074, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.7044714070432387, 'colsample_bytree': 0.8966747084312867}. Best is trial 6 with value: 0.710465365467519.

Running time: 10.6 sec
OOF RMSE: 2.05 | R2: 0.65
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:06:06,257] Trial 8 finished with value: 0.6943523971150751 and parameters: {'n_estimators': 500, 'learning_rate': 0.01356621625467211, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.9744553440111893, 'colsample_bytree': 0.9024781080249767}. Best is trial 6 with value: 0.710465365467519.

Running time: 3.3 sec
OOF RMSE: 1.92 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:06:20,487] Trial 9 finished with value: 0.6943433646370851 and parameters: {'n_estimators': 2000, 'learning_rate': 0.020423328826435442, 'max_depth': 8, 'min_child_weight': 2, 'subsample': 0.7732339704228031, 'colsample_bytree': 0.8527799106954571}. Best is trial 6 with value: 0.710465365467519.

Running time: 14.2 sec
OOF RMSE: 1.92 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:06:27,174] Trial 10 finished with value: 0.706564042945651 and parameters: {'n_estimators': 1000, 'learning_rate': 0.00955522102724497, 'max_depth': 5, 'min_child_weight': 1, 'subsample': 0.7959097796267615, 'colsample_bytree': 0.9697454956242909}. Best is trial 6 with value: 0.710465365467519.

Running time: 6.7 sec
OOF RMSE: 1.88 | R2: 0.71
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:06:34,073] Trial 11 finished with value: 0.7081392968559698 and parameters: {'n_estimators': 1000, 'learning_rate': 0.0087849660869365, 'max_depth': 5, 'min_child_weight': 1, 'subsample': 0.7965480768614995, 'colsample_bytree': 0.9969527000611771}. Best is trial 6 with value: 0.710465365467519.

Running time: 6.9 sec
OOF RMSE: 1.87 | R2: 0.71
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:06:40,848] Trial 12 finished with value: 0.6990163565866258 and parameters: {'n_estimators': 1000, 'learning_rate': 0.009776312540509204, 'max_depth': 5, 'min_child_weight': 1, 'subsample': 0.7232573825104085, 'colsample_bytree': 0.9999219340835207}. Best is trial 6 with value: 0.710465365467519.

Running time: 6.8 sec
OOF RMSE: 1.90 | R2: 0.70
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:06:46,394] Trial 13 finished with value: 0.7110313556284973 and parameters: {'n_estimators': 1000, 'learning_rate': 0.0051001566840116, 'max_depth': 5, 'min_child_weight': 1, 'subsample': 0.6367882891759693, 'colsample_bytree': 0.8284267765412199}. Best is trial 13 with value: 0.7110313556284973.

Running time: 5.5 sec
OOF RMSE: 1.86 | R2: 0.71
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:06:53,131] Trial 14 finished with value: 0.7034486588547082 and parameters: {'n_estimators': 1000, 'learning_rate': 0.005098382224968676, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.6033460922024605, 'colsample_bytree': 0.824745760647431}. Best is trial 13 with value: 0.7110313556284973.

Running time: 6.7 sec
OOF RMSE: 1.89 | R2: 0.70
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:06:58,544] Trial 15 finished with value: 0.6613395104816827 and parameters: {'n_estimators': 1000, 'learning_rate': 0.012451819850153712, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.654004628899723, 'colsample_bytree': 0.783475960996181}. Best is trial 13 with value: 0.7110313556284973.

Running time: 5.4 sec
OOF RMSE: 2.02 | R2: 0.66
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:07:01,770] Trial 16 finished with value: 0.713916042268935 and parameters: {'n_estimators': 500, 'learning_rate': 0.006683548117656549, 'max_depth': 6, 'min_child_weight': 1, 'subsample': 0.6666897786815976, 'colsample_bytree': 0.8412098072277965}. Best is trial 16 with value: 0.713916042268935.

Running time: 3.2 sec
OOF RMSE: 1.85 | R2: 0.71
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:07:04,528] Trial 17 finished with value: 0.7141972782463275 and parameters: {'n_estimators': 500, 'learning_rate': 0.006975792217233777, 'max_depth': 5, 'min_child_weight': 1, 'subsample': 0.647116412695353, 'colsample_bytree': 0.8067159296688585}. Best is trial 17 with value: 0.7141972782463275.

Running time: 2.8 sec
OOF RMSE: 1.85 | R2: 0.71
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:07:07,466] Trial 18 finished with value: 0.7101636389174932 and parameters: {'n_estimators': 500, 'learning_rate': 0.01301424895604881, 'max_depth': 6, 'min_child_weight': 1, 'subsample': 0.6612508535269737, 'colsample_bytree': 0.7315814696479311}. Best is trial 17 with value: 0.7141972782463275.

Running time: 2.9 sec
OOF RMSE: 1.87 | R2: 0.71
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:07:10,377] Trial 19 finished with value: 0.7077782769102671 and parameters: {'n_estimators': 500, 'learning_rate': 0.02666848612804947, 'max_depth': 5, 'min_child_weight': 1, 'subsample': 0.846923049031005, 'colsample_bytree': 0.7854481037205836}. Best is trial 17 with value: 0.7141972782463275.

Running time: 2.9 sec
OOF RMSE: 1.87 | R2: 0.71
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:07:13,116] Trial 20 finished with value: 0.7044513671852981 and parameters: {'n_estimators': 500, 'learning_rate': 0.0074886682888935935, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.7594643532259062, 'colsample_bytree': 0.6066614374374456}. Best is trial 17 with value: 0.7141972782463275.

Running time: 2.7 sec
OOF RMSE: 1.88 | R2: 0.70
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:07:15,945] Trial 21 finished with value: 0.7134786392651016 and parameters: {'n_estimators': 500, 'learning_rate': 0.006273918261772348, 'max_depth': 5, 'min_child_weight': 1, 'subsample': 0.6490876050938591, 'colsample_bytree': 0.8328461310543057}. Best is trial 17 with value: 0.7141972782463275.

Running time: 2.8 sec
OOF RMSE: 1.86 | R2: 0.71
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:07:18,633] Trial 22 finished with value: 0.7144552629836822 and parameters: {'n_estimators': 500, 'learning_rate': 0.007017496597560787, 'max_depth': 5, 'min_child_weight': 1, 'subsample': 0.6791146700681028, 'colsample_bytree': 0.8737847252089066}. Best is trial 22 with value: 0.7144552629836822.

Running time: 2.7 sec
OOF RMSE: 1.85 | R2: 0.71
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:07:21,519] Trial 23 finished with value: 0.6972660103238215 and parameters: {'n_estimators': 500, 'learning_rate': 0.016708426231392324, 'max_depth': 5, 'min_child_weight': 1, 'subsample': 0.6821709530717244, 'colsample_bytree': 0.8816035124224634}. Best is trial 22 with value: 0.7144552629836822.

Running time: 2.9 sec
OOF RMSE: 1.91 | R2: 0.70
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:07:24,907] Trial 24 finished with value: 0.7142655167812826 and parameters: {'n_estimators': 500, 'learning_rate': 0.007954226260973007, 'max_depth': 6, 'min_child_weight': 1, 'subsample': 0.7488707102562765, 'colsample_bytree': 0.9245663128344206}. Best is trial 22 with value: 0.7144552629836822.
[I 2025-07-11 23:07:24,909] A new study created in memory with name: no-name-a97fac63-2f79-417a-bedc-fe5639c5626a

Running time: 3.4 sec
OOF RMSE: 1.85 | R2: 0.71

✅ XGB - Mejor R2: 0.71
📋 Parámetros: {'n_estimators': 500, 'learning_rate': 0.007017496597560787, 'max_depth': 5, 'min_child_weight': 1, 'subsample': 0.6791146700681028, 'colsample_bytree': 0.8737847252089066}

Buscando mejores hiperparámetros para LBM...
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 23:07:25,220] Trial 0 finished with value: 0.6049796872884365 and parameters: {'learning_rate': 0.08691217192173546, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 11, 'subsample': 0.8551119624388628, 'colsample_bytree': 0.6662372948851638, 'n_estimators': 500}. Best is trial 0 with value: 0.6049796872884365.

Fold 5
Running time: 0.3 sec
OOF RMSE: 2.18 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:07:25,876] Trial 1 finished with value: 0.5492730091296851 and parameters: {'learning_rate': 0.017098190310432027, 'num_leaves': 40, 'max_depth': 8, 'min_child_samples': 16, 'subsample': 0.7139610722339719, 'colsample_bytree': 0.8295920362226096, 'n_estimators': 1000}. Best is trial 0 with value: 0.6049796872884365.

Running time: 0.7 sec
OOF RMSE: 2.33 | R2: 0.55
Fold 1
Fold 2
Fold 3

[I 2025-07-11 23:07:26,349] Trial 2 finished with value: 0.5223193473900526 and parameters: {'learning_rate': 0.029791545392318538, 'num_leaves': 80, 'max_depth': 5, 'min_child_samples': 13, 'subsample': 0.6501022101748765, 'colsample_bytree': 0.7626326630317801, 'n_estimators': 1000}. Best is trial 0 with value: 0.6049796872884365.

Fold 4
Fold 5
Running time: 0.5 sec
OOF RMSE: 2.40 | R2: 0.52
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:07:26,677] Trial 3 finished with value: 0.588630882011455 and parameters: {'learning_rate': 0.07372340234825969, 'num_leaves': 80, 'max_depth': 6, 'min_child_samples': 9, 'subsample': 0.6226124107816117, 'colsample_bytree': 0.7753896202800592, 'n_estimators': 500}. Best is trial 0 with value: 0.6049796872884365.

Running time: 0.3 sec
OOF RMSE: 2.22 | R2: 0.59
Fold 1
Fold 2
Fold 3

[I 2025-07-11 23:07:27,190] Trial 4 finished with value: 0.5727968016584645 and parameters: {'learning_rate': 0.008450735314744254, 'num_leaves': 40, 'max_depth': 6, 'min_child_samples': 19, 'subsample': 0.9154039107383342, 'colsample_bytree': 0.6832218858835281, 'n_estimators': 1000}. Best is trial 0 with value: 0.6049796872884365.

Fold 4
Fold 5
Running time: 0.5 sec
OOF RMSE: 2.27 | R2: 0.57
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:07:27,666] Trial 5 finished with value: 0.5318254218762566 and parameters: {'learning_rate': 0.055428445689006706, 'num_leaves': 20, 'max_depth': 8, 'min_child_samples': 24, 'subsample': 0.8019085751625199, 'colsample_bytree': 0.8099710472316992, 'n_estimators': 1000}. Best is trial 0 with value: 0.6049796872884365.

Running time: 0.5 sec
OOF RMSE: 2.37 | R2: 0.53
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 23:07:27,988] Trial 6 finished with value: 0.5303834556622314 and parameters: {'learning_rate': 0.047816719914426785, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 16, 'subsample': 0.9633635499060373, 'colsample_bytree': 0.9969372559479137, 'n_estimators': 500}. Best is trial 0 with value: 0.6049796872884365.

Fold 5
Running time: 0.3 sec
OOF RMSE: 2.38 | R2: 0.53
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:07:29,408] Trial 7 finished with value: 0.6189320278061803 and parameters: {'learning_rate': 0.0396369498230244, 'num_leaves': 80, 'max_depth': 8, 'min_child_samples': 7, 'subsample': 0.8649631392096613, 'colsample_bytree': 0.7581581796376394, 'n_estimators': 2000}. Best is trial 7 with value: 0.6189320278061803.

Running time: 1.4 sec
OOF RMSE: 2.14 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 23:07:29,680] Trial 8 finished with value: 0.6117248849760726 and parameters: {'learning_rate': 0.01250020759335909, 'num_leaves': 40, 'max_depth': 5, 'min_child_samples': 8, 'subsample': 0.661727019174772, 'colsample_bytree': 0.9280581003831899, 'n_estimators': 500}. Best is trial 7 with value: 0.6189320278061803.

Fold 5
Running time: 0.3 sec
OOF RMSE: 2.16 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:07:30,057] Trial 9 finished with value: 0.5617281729784062 and parameters: {'learning_rate': 0.007612398823866696, 'num_leaves': 80, 'max_depth': 8, 'min_child_samples': 15, 'subsample': 0.9094233948567876, 'colsample_bytree': 0.9323237359328337, 'n_estimators': 500}. Best is trial 7 with value: 0.6189320278061803.

Running time: 0.4 sec
OOF RMSE: 2.29 | R2: 0.56
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:07:31,525] Trial 10 finished with value: 0.6637135135394577 and parameters: {'learning_rate': 0.03159295229081035, 'num_leaves': 60, 'max_depth': 7, 'min_child_samples': 5, 'subsample': 0.7668822837311821, 'colsample_bytree': 0.6203396866155765, 'n_estimators': 2000}. Best is trial 10 with value: 0.6637135135394577.

Running time: 1.5 sec
OOF RMSE: 2.01 | R2: 0.66
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:07:32,909] Trial 11 finished with value: 0.6697717207167224 and parameters: {'learning_rate': 0.03203644466427847, 'num_leaves': 60, 'max_depth': 7, 'min_child_samples': 5, 'subsample': 0.7478172632204634, 'colsample_bytree': 0.6041157065674472, 'n_estimators': 2000}. Best is trial 11 with value: 0.6697717207167224.

Running time: 1.4 sec
OOF RMSE: 1.99 | R2: 0.67
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:07:34,212] Trial 12 finished with value: 0.6774562857291209 and parameters: {'learning_rate': 0.02260203612175574, 'num_leaves': 60, 'max_depth': 7, 'min_child_samples': 5, 'subsample': 0.7439133799032975, 'colsample_bytree': 0.6128616447926193, 'n_estimators': 2000}. Best is trial 12 with value: 0.6774562857291209.

Running time: 1.3 sec
OOF RMSE: 1.97 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:07:35,393] Trial 13 finished with value: 0.6764769805638515 and parameters: {'learning_rate': 0.02006731427685943, 'num_leaves': 60, 'max_depth': 6, 'min_child_samples': 5, 'subsample': 0.7345604523564953, 'colsample_bytree': 0.6129884450770097, 'n_estimators': 2000}. Best is trial 12 with value: 0.6774562857291209.

Running time: 1.2 sec
OOF RMSE: 1.97 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:07:36,363] Trial 14 finished with value: 0.5791442405464646 and parameters: {'learning_rate': 0.019579067223513838, 'num_leaves': 60, 'max_depth': 6, 'min_child_samples': 10, 'subsample': 0.7021278000669527, 'colsample_bytree': 0.6921792607801671, 'n_estimators': 2000}. Best is trial 12 with value: 0.6774562857291209.

Running time: 1.0 sec
OOF RMSE: 2.25 | R2: 0.58
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:07:37,514] Trial 15 finished with value: 0.6751882487021512 and parameters: {'learning_rate': 0.005149648043110104, 'num_leaves': 60, 'max_depth': 6, 'min_child_samples': 5, 'subsample': 0.8066424646924905, 'colsample_bytree': 0.6470558185586635, 'n_estimators': 2000}. Best is trial 12 with value: 0.6774562857291209.

Running time: 1.1 sec
OOF RMSE: 1.98 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:07:38,359] Trial 16 finished with value: 0.5772863161127917 and parameters: {'learning_rate': 0.01390031161120928, 'num_leaves': 60, 'max_depth': 5, 'min_child_samples': 21, 'subsample': 0.7058339078307747, 'colsample_bytree': 0.7173691712140976, 'n_estimators': 2000}. Best is trial 12 with value: 0.6774562857291209.

Running time: 0.8 sec
OOF RMSE: 2.25 | R2: 0.58
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 23:07:39,395] Trial 17 finished with value: 0.5395515605564656 and parameters: {'learning_rate': 0.024359077186431176, 'num_leaves': 60, 'max_depth': 6, 'min_child_samples': 12, 'subsample': 0.7625860920140126, 'colsample_bytree': 0.8471267549163555, 'n_estimators': 2000}. Best is trial 12 with value: 0.6774562857291209.

Fold 5
Running time: 1.0 sec
OOF RMSE: 2.35 | R2: 0.54
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:07:40,551] Trial 18 finished with value: 0.5918201093619826 and parameters: {'learning_rate': 0.011562169571723239, 'num_leaves': 60, 'max_depth': 7, 'min_child_samples': 8, 'subsample': 0.8337290306206866, 'colsample_bytree': 0.7184502869508121, 'n_estimators': 2000}. Best is trial 12 with value: 0.6774562857291209.

Running time: 1.1 sec
OOF RMSE: 2.21 | R2: 0.59
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:07:41,641] Trial 19 finished with value: 0.6342363961834963 and parameters: {'learning_rate': 0.02251591531889307, 'num_leaves': 60, 'max_depth': 6, 'min_child_samples': 7, 'subsample': 0.6014492147892644, 'colsample_bytree': 0.6169050023340753, 'n_estimators': 2000}. Best is trial 12 with value: 0.6774562857291209.

Running time: 1.1 sec
OOF RMSE: 2.10 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:07:42,708] Trial 20 finished with value: 0.5151916250766567 and parameters: {'learning_rate': 0.01676525742224834, 'num_leaves': 60, 'max_depth': 7, 'min_child_samples': 14, 'subsample': 0.6732536073395126, 'colsample_bytree': 0.6462390116234855, 'n_estimators': 2000}. Best is trial 12 with value: 0.6774562857291209.

Running time: 1.1 sec
OOF RMSE: 2.41 | R2: 0.52
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:07:43,852] Trial 21 finished with value: 0.6738446697887303 and parameters: {'learning_rate': 0.005406154443067624, 'num_leaves': 60, 'max_depth': 6, 'min_child_samples': 5, 'subsample': 0.7948332690341436, 'colsample_bytree': 0.6493832413941896, 'n_estimators': 2000}. Best is trial 12 with value: 0.6774562857291209.

Running time: 1.1 sec
OOF RMSE: 1.98 | R2: 0.67
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:07:44,968] Trial 22 finished with value: 0.6620206907665868 and parameters: {'learning_rate': 0.005343666782739981, 'num_leaves': 60, 'max_depth': 6, 'min_child_samples': 6, 'subsample': 0.7336047817596715, 'colsample_bytree': 0.6022142884521132, 'n_estimators': 2000}. Best is trial 12 with value: 0.6774562857291209.

Running time: 1.1 sec
OOF RMSE: 2.02 | R2: 0.66
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 23:07:45,803] Trial 23 finished with value: 0.5944642451492984 and parameters: {'learning_rate': 0.009181757371411515, 'num_leaves': 60, 'max_depth': 5, 'min_child_samples': 10, 'subsample': 0.8023259805542317, 'colsample_bytree': 0.6444994236067991, 'n_estimators': 2000}. Best is trial 12 with value: 0.6774562857291209.

Fold 5
Running time: 0.8 sec
OOF RMSE: 2.21 | R2: 0.59
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 23:07:46,863] Trial 24 finished with value: 0.6265986458812485 and parameters: {'learning_rate': 0.006712379400630774, 'num_leaves': 60, 'max_depth': 6, 'min_child_samples': 7, 'subsample': 0.7824792721216111, 'colsample_bytree': 0.7040568565655396, 'n_estimators': 2000}. Best is trial 12 with value: 0.6774562857291209.
[I 2025-07-11 23:07:46,865] A new study created in memory with name: no-name-a7904280-4476-49f7-adbd-a8161abf38d5

Fold 5
Running time: 1.1 sec
OOF RMSE: 2.12 | R2: 0.63

✅ LBM - Mejor R2: 0.68
📋 Parámetros: {'learning_rate': 0.02260203612175574, 'num_leaves': 60, 'max_depth': 7, 'min_child_samples': 5, 'subsample': 0.7439133799032975, 'colsample_bytree': 0.6128616447926193, 'n_estimators': 2000}

Buscando mejores hiperparámetros para MLP...
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 23:07:47,675] Trial 0 finished with value: 0.3781937778816905 and parameters: {'hidden_layer_sizes': '50', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.07915135894899689, 'learning_rate': 'constant', 'learning_rate_init': 0.00024376844660580646}. Best is trial 0 with value: 0.3781937778816905.

Fold 4
Fold 5
Running time: 0.8 sec
OOF RMSE: 2.73 | R2: 0.38
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 23:07:49,177] Trial 1 finished with value: 0.5032107127681564 and parameters: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.00044151879489041457, 'learning_rate': 'constant', 'learning_rate_init': 0.0005266340169566514}. Best is trial 1 with value: 0.5032107127681564.

Fold 5
Running time: 1.5 sec
OOF RMSE: 2.44 | R2: 0.50
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

[I 2025-07-11 23:07:50,023] Trial 2 finished with value: 0.3254185594452994 and parameters: {'hidden_layer_sizes': '50', 'activation': 'tanh', 'solver': 'adam', 'alpha': 7.676571410081174e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.0013240175648774463}. Best is trial 1 with value: 0.5032107127681564.

Running time: 0.8 sec
OOF RMSE: 2.85 | R2: 0.33
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:07:51,443] Trial 3 finished with value: 0.5548636913611913 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.005963724463503469, 'learning_rate': 'constant', 'learning_rate_init': 0.0011062766563335032}. Best is trial 3 with value: 0.5548636913611913.

Running time: 1.4 sec
OOF RMSE: 2.31 | R2: 0.55
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 23:07:52,196] Trial 4 finished with value: 0.366127911849612 and parameters: {'hidden_layer_sizes': '50', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0005464222684191547, 'learning_rate': 'constant', 'learning_rate_init': 0.0016443735746204263}. Best is trial 3 with value: 0.5548636913611913.

Fold 5
Running time: 0.7 sec
OOF RMSE: 2.76 | R2: 0.37
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:07:53,342] Trial 5 finished with value: 0.5835622089680218 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 8.721435974182579e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.008306794875394121}. Best is trial 5 with value: 0.5835622089680218.

Running time: 1.1 sec
OOF RMSE: 2.24 | R2: 0.58
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:07:54,442] Trial 6 finished with value: 0.5922013385374822 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0019611058731203554, 'learning_rate': 'constant', 'learning_rate_init': 0.0011534536802952121}. Best is trial 6 with value: 0.5922013385374822.

Running time: 1.1 sec
OOF RMSE: 2.21 | R2: 0.59
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 23:07:56,848] Trial 7 finished with value: 0.5540206124360352 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.0008322932912931569, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0033058227165356532}. Best is trial 6 with value: 0.5922013385374822.

Running time: 2.4 sec
OOF RMSE: 2.32 | R2: 0.55
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 23:07:59,227] Trial 8 finished with value: 0.3447609070328246 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.0016974077257402116, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00014458266574610574}. Best is trial 6 with value: 0.5922013385374822.

Running time: 2.4 sec
OOF RMSE: 2.81 | R2: 0.34
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 23:08:01,231] Trial 9 finished with value: 0.4450973385029856 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.0003922340638533086, 'learning_rate': 'constant', 'learning_rate_init': 0.0007139719695332047}. Best is trial 6 with value: 0.5922013385374822.

Running time: 2.0 sec
OOF RMSE: 2.58 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 23:08:02,340] Trial 10 finished with value: 0.5899801680270083 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.02298863824368972, 'learning_rate': 'adaptive', 'learning_rate_init': 0.003921785995036745}. Best is trial 6 with value: 0.5922013385374822.

Fold 5
Running time: 1.1 sec
OOF RMSE: 2.22 | R2: 0.59
Fold 1
Fold 2
Fold 3

[I 2025-07-11 23:08:03,194] Trial 11 finished with value: 0.593134679069375 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.02889968837429535, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0038944887512488155}. Best is trial 11 with value: 0.593134679069375.

Fold 4
Fold 5
Running time: 0.8 sec
OOF RMSE: 2.21 | R2: 0.59
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.8 sec

[I 2025-07-11 23:08:04,009] Trial 12 finished with value: 0.5763173769482249 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'relu', 'solver': 'adam', 'alpha': 1.0364686478321395e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.002985279979936369}. Best is trial 11 with value: 0.593134679069375.

OOF RMSE: 2.26 | R2: 0.58
Fold 1
Fold 2
Fold 3

[I 2025-07-11 23:08:04,798] Trial 13 finished with value: 0.5719247077227692 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.01572399311364793, 'learning_rate': 'adaptive', 'learning_rate_init': 0.007923214273898886}. Best is trial 11 with value: 0.593134679069375.

Fold 4
Fold 5
Running time: 0.8 sec
OOF RMSE: 2.27 | R2: 0.57
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 23:08:06,778] Trial 14 finished with value: 0.5848403133356892 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0034675756498089394, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00040215580560158085}. Best is trial 11 with value: 0.593134679069375.

Running time: 2.0 sec
OOF RMSE: 2.23 | R2: 0.58
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:08:07,696] Trial 15 finished with value: 0.5865570441190178 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.049097452416273536, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0020384520187340265}. Best is trial 11 with value: 0.593134679069375.

Running time: 0.9 sec
OOF RMSE: 2.23 | R2: 0.59
Fold 1
Fold 2
Fold 3

[I 2025-07-11 23:08:08,552] Trial 16 finished with value: 0.5746904092637831 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.009959317298367416, 'learning_rate': 'constant', 'learning_rate_init': 0.004814602281464642}. Best is trial 11 with value: 0.593134679069375.

Fold 4
Fold 5
Running time: 0.9 sec
OOF RMSE: 2.26 | R2: 0.57
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 23:08:09,607] Trial 17 finished with value: 0.5811432106729668 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.031112244580190636, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0022434572959496115}. Best is trial 11 with value: 0.593134679069375.

Fold 5
Running time: 1.0 sec
OOF RMSE: 2.24 | R2: 0.58
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 23:08:12,293] Trial 18 finished with value: 0.5089134323896525 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.0026584000574002057, 'learning_rate': 'constant', 'learning_rate_init': 0.0008650586739545724}. Best is trial 11 with value: 0.593134679069375.

Running time: 2.7 sec
OOF RMSE: 2.43 | R2: 0.51
Fold 1
Fold 2
Fold 3

[I 2025-07-11 23:08:13,208] Trial 19 finished with value: 0.5736679171697103 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.00014151117077412163, 'learning_rate': 'adaptive', 'learning_rate_init': 0.005204982388869179}. Best is trial 11 with value: 0.593134679069375.

Fold 4
Fold 5
Running time: 0.9 sec
OOF RMSE: 2.26 | R2: 0.57
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 23:08:15,366] Trial 20 finished with value: 0.4572757990436944 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.00547705029962108, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00010555627469110685}. Best is trial 11 with value: 0.593134679069375.

Running time: 2.2 sec
OOF RMSE: 2.55 | R2: 0.46
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:08:16,199] Trial 21 finished with value: 0.5603918702968342 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.019430803465254876, 'learning_rate': 'adaptive', 'learning_rate_init': 0.004376880961346051}. Best is trial 11 with value: 0.593134679069375.

Running time: 0.8 sec
OOF RMSE: 2.30 | R2: 0.56
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:08:17,287] Trial 22 finished with value: 0.5737370573099996 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.08126362563146647, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0028512955904793614}. Best is trial 11 with value: 0.593134679069375.

Running time: 1.1 sec
OOF RMSE: 2.26 | R2: 0.57
Fold 1
Fold 2
Fold 3

[I 2025-07-11 23:08:18,062] Trial 23 finished with value: 0.5641673627028662 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.031298047284610685, 'learning_rate': 'adaptive', 'learning_rate_init': 0.009656898855111055}. Best is trial 11 with value: 0.593134679069375.

Fold 4
Fold 5
Running time: 0.8 sec
OOF RMSE: 2.29 | R2: 0.56
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:08:19,273] Trial 24 finished with value: 0.5756909298989241 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.008561677966454864, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0015240919681422061}. Best is trial 11 with value: 0.593134679069375.
[I 2025-07-11 23:08:19,274] A new study created in memory with name: no-name-f47b24b0-54de-4e49-8117-ea5caec0d3b9
[I 2025-07-11 23:08:19,365] Trial 0 finished with value: 0.35050325336764165 and parameters: {'kernel': 'rbf', 'C': 2.6733186486571, 'epsilon': 0.09289414660322416, 'gamma': 'auto'}. Best is trial 0 with value: 0.35050325336764165.
[I 2025-07-11 23:08:19,441] Trial 1 finished with value: -44.133541228119505 and parameters: {'kernel': 'sigmoid', 'C': 4.163574072076266, 'epsilon': 0.18952638177123954, 'gamma': 'auto'}. Best is trial 0 with value: 0.35050325336764165.

Running time: 1.2 sec
OOF RMSE: 2.26 | R2: 0.58

✅ MLP - Mejor R2: 0.59
📋 Parámetros: {'hidden_layer_sizes': '100_50', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.02889968837429535, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0038944887512488155}

Buscando mejores hiperparámetros para SVR...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.79 | R2: 0.35
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 23.29 | R2: -44.13
Fold 1
Fold 2

[I 2025-07-11 23:08:19,515] Trial 2 finished with value: 0.07841252968468337 and parameters: {'kernel': 'sigmoid', 'C': 0.10060793833943671, 'epsilon': 0.11466713449430602, 'gamma': 'auto'}. Best is trial 0 with value: 0.35050325336764165.
[I 2025-07-11 23:08:19,587] Trial 3 finished with value: 0.09278263408514065 and parameters: {'kernel': 'rbf', 'C': 0.12445436784018331, 'epsilon': 0.06276465103660492, 'gamma': 'auto'}. Best is trial 0 with value: 0.35050325336764165.
[I 2025-07-11 23:08:19,665] Trial 4 finished with value: 0.45530349448333096 and parameters: {'kernel': 'rbf', 'C': 4.263296004173715, 'epsilon': 0.14242608630059464, 'gamma': 'scale'}. Best is trial 4 with value: 0.45530349448333096.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.33 | R2: 0.08
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.30 | R2: 0.09
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.56 | R2: 0.46
Fold 1

[I 2025-07-11 23:08:19,743] Trial 5 finished with value: 0.3664530385169956 and parameters: {'kernel': 'rbf', 'C': 2.5582663107874213, 'epsilon': 0.12128865067912474, 'gamma': 'scale'}. Best is trial 4 with value: 0.45530349448333096.
[I 2025-07-11 23:08:19,817] Trial 6 finished with value: 0.23961836450253693 and parameters: {'kernel': 'rbf', 'C': 0.7484334682858534, 'epsilon': 0.054367475621703236, 'gamma': 'scale'}. Best is trial 4 with value: 0.45530349448333096.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.76 | R2: 0.37
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.02 | R2: 0.24
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:08:19,897] Trial 7 finished with value: -241.1098785570745 and parameters: {'kernel': 'sigmoid', 'C': 9.738426406632362, 'epsilon': 0.030479167081437372, 'gamma': 'auto'}. Best is trial 4 with value: 0.45530349448333096.
[I 2025-07-11 23:08:19,977] Trial 8 finished with value: 0.4989310236837792 and parameters: {'kernel': 'rbf', 'C': 5.608858626272599, 'epsilon': 0.0747477744861927, 'gamma': 'scale'}. Best is trial 8 with value: 0.4989310236837792.
[I 2025-07-11 23:08:20,055] Trial 9 finished with value: -52.627503649957546 and parameters: {'kernel': 'sigmoid', 'C': 3.534222814022903, 'epsilon': 0.07739433659739323, 'gamma': 'scale'}. Best is trial 8 with value: 0.4989310236837792.

Running time: 0.1 sec
OOF RMSE: 53.94 | R2: -241.11
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.45 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 25.39 | R2: -52.63
Fold 1
Fold 2
Fold 3

[I 2025-07-11 23:08:20,136] Trial 10 finished with value: 0.2543087032741028 and parameters: {'kernel': 'rbf', 'C': 0.8976943419539261, 'epsilon': 0.013143794907641462, 'gamma': 'scale'}. Best is trial 8 with value: 0.4989310236837792.
[I 2025-07-11 23:08:20,220] Trial 11 finished with value: 0.5647188588521901 and parameters: {'kernel': 'rbf', 'C': 8.781626458150953, 'epsilon': 0.15274856075968543, 'gamma': 'scale'}. Best is trial 11 with value: 0.5647188588521901.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.99 | R2: 0.25
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.29 | R2: 0.56
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:08:20,323] Trial 12 finished with value: 0.572729850462266 and parameters: {'kernel': 'rbf', 'C': 9.287025350240699, 'epsilon': 0.16541559746751497, 'gamma': 'scale'}. Best is trial 12 with value: 0.572729850462266.
[I 2025-07-11 23:08:20,408] Trial 13 finished with value: 0.5735218305527913 and parameters: {'kernel': 'rbf', 'C': 9.315235074685601, 'epsilon': 0.17138977721277437, 'gamma': 'scale'}. Best is trial 13 with value: 0.5735218305527913.
[I 2025-07-11 23:08:20,488] Trial 14 finished with value: 0.305405859471514 and parameters: {'kernel': 'rbf', 'C': 1.4974224938377327, 'epsilon': 0.1885956636178549, 'gamma': 'scale'}. Best is trial 13 with value: 0.5735218305527913.

Running time: 0.1 sec
OOF RMSE: 2.27 | R2: 0.57
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.26 | R2: 0.57
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.89 | R2: 0.31
Fold 1
Fold 2

[I 2025-07-11 23:08:20,568] Trial 15 finished with value: 0.16997201275076235 and parameters: {'kernel': 'rbf', 'C': 0.36230559873462176, 'epsilon': 0.16313486858931803, 'gamma': 'scale'}. Best is trial 13 with value: 0.5735218305527913.
[I 2025-07-11 23:08:20,652] Trial 16 finished with value: 0.5270958699813177 and parameters: {'kernel': 'rbf', 'C': 6.684701895562836, 'epsilon': 0.1687720786899875, 'gamma': 'scale'}. Best is trial 13 with value: 0.5735218305527913.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.16 | R2: 0.17
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.38 | R2: 0.53
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:08:20,735] Trial 17 finished with value: 0.33051645875048963 and parameters: {'kernel': 'rbf', 'C': 1.922064512402633, 'epsilon': 0.12902594325982175, 'gamma': 'scale'}. Best is trial 13 with value: 0.5735218305527913.
[I 2025-07-11 23:08:20,818] Trial 18 finished with value: -0.4927157160583422 and parameters: {'kernel': 'sigmoid', 'C': 0.33342477481805605, 'epsilon': 0.1956855668787102, 'gamma': 'scale'}. Best is trial 13 with value: 0.5735218305527913.
[I 2025-07-11 23:08:20,901] Trial 19 finished with value: 0.5188276311093494 and parameters: {'kernel': 'rbf', 'C': 6.3375383281988045, 'epsilon': 0.1781777398042027, 'gamma': 'scale'}. Best is trial 13 with value: 0.5735218305527913.

Running time: 0.1 sec
OOF RMSE: 2.84 | R2: 0.33
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 4.24 | R2: -0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.40 | R2: 0.52
Fold 1
Fold 2

[I 2025-07-11 23:08:20,977] Trial 20 finished with value: 0.31076249919832943 and parameters: {'kernel': 'rbf', 'C': 1.5781853875731977, 'epsilon': 0.14143002621592796, 'gamma': 'scale'}. Best is trial 13 with value: 0.5735218305527913.
[I 2025-07-11 23:08:21,065] Trial 21 finished with value: 0.5745659036457589 and parameters: {'kernel': 'rbf', 'C': 9.490620850830105, 'epsilon': 0.15053815923589725, 'gamma': 'scale'}. Best is trial 21 with value: 0.5745659036457589.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.88 | R2: 0.31
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.26 | R2: 0.57
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:08:21,148] Trial 22 finished with value: 0.5787567758774532 and parameters: {'kernel': 'rbf', 'C': 9.771071997103778, 'epsilon': 0.15987166542258283, 'gamma': 'scale'}. Best is trial 22 with value: 0.5787567758774532.
[I 2025-07-11 23:08:21,229] Trial 23 finished with value: 0.4968446023950367 and parameters: {'kernel': 'rbf', 'C': 5.551780741553715, 'epsilon': 0.14602986572204923, 'gamma': 'scale'}. Best is trial 22 with value: 0.5787567758774532.
[I 2025-07-11 23:08:21,315] Trial 24 finished with value: 0.5763364387695491 and parameters: {'kernel': 'rbf', 'C': 9.703724833081715, 'epsilon': 0.10192072946448666, 'gamma': 'scale'}. Best is trial 22 with value: 0.5787567758774532.
[I 2025-07-11 23:08:21,316] A new study created in memory with name: no-name-a9a6931e-f565-4c7a-b909-b1b7cc2187d2

Running time: 0.1 sec
OOF RMSE: 2.25 | R2: 0.58
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.46 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.26 | R2: 0.58

✅ SVR - Mejor R2: 0.58
📋 Parámetros: {'kernel': 'rbf', 'C': 9.771071997103778, 'epsilon': 0.15987166542258283, 'gamma': 'scale'}

Buscando mejores hiperparámetros para KNN...
Fold 1
Fold 2
Fold 3

[I 2025-07-11 23:08:21,375] Trial 0 finished with value: 0.642435757138353 and parameters: {'n_neighbors': 10, 'weights': 'distance', 'leaf_size': 25}. Best is trial 0 with value: 0.642435757138353.
[I 2025-07-11 23:08:21,437] Trial 1 finished with value: 0.5566712788075859 and parameters: {'n_neighbors': 14, 'weights': 'uniform', 'leaf_size': 15}. Best is trial 0 with value: 0.642435757138353.
[I 2025-07-11 23:08:21,502] Trial 2 finished with value: 0.7534078056617969 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'leaf_size': 24}. Best is trial 2 with value: 0.7534078056617969.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.07 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.31 | R2: 0.56
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.72 | R2: 0.75
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:08:21,568] Trial 3 finished with value: 0.664918704997145 and parameters: {'n_neighbors': 6, 'weights': 'uniform', 'leaf_size': 17}. Best is trial 2 with value: 0.7534078056617969.
[I 2025-07-11 23:08:21,661] Trial 4 finished with value: 0.5482056913270246 and parameters: {'n_neighbors': 13, 'weights': 'uniform', 'leaf_size': 20}. Best is trial 2 with value: 0.7534078056617969.
[I 2025-07-11 23:08:21,728] Trial 5 finished with value: 0.642435757138353 and parameters: {'n_neighbors': 10, 'weights': 'distance', 'leaf_size': 40}. Best is trial 2 with value: 0.7534078056617969.

Running time: 0.1 sec
OOF RMSE: 2.01 | R2: 0.66
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.33 | R2: 0.55
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.07 | R2: 0.64
Fold 1
Fold 2
Fold 3

[I 2025-07-11 23:08:21,812] Trial 6 finished with value: 0.7224753809702951 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'leaf_size': 16}. Best is trial 2 with value: 0.7534078056617969.
[I 2025-07-11 23:08:21,876] Trial 7 finished with value: 0.642435757138353 and parameters: {'n_neighbors': 10, 'weights': 'distance', 'leaf_size': 30}. Best is trial 2 with value: 0.7534078056617969.
[I 2025-07-11 23:08:21,941] Trial 8 finished with value: 0.7087014304749202 and parameters: {'n_neighbors': 5, 'weights': 'uniform', 'leaf_size': 30}. Best is trial 2 with value: 0.7534078056617969.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.83 | R2: 0.72
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.07 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.87 | R2: 0.71
Fold 1
Fold 2
Fold 3

[I 2025-07-11 23:08:22,011] Trial 9 finished with value: 0.7595830204383347 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'leaf_size': 15}. Best is trial 9 with value: 0.7595830204383347.
[I 2025-07-11 23:08:22,087] Trial 10 finished with value: 0.7978988238958789 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 10}. Best is trial 10 with value: 0.7978988238958789.
[I 2025-07-11 23:08:22,161] Trial 11 finished with value: 0.7978988238958789 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 10}. Best is trial 10 with value: 0.7978988238958789.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.70 | R2: 0.76
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.56 | R2: 0.80
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.56 | R2: 0.80
Fold 1
Fold 2

[I 2025-07-11 23:08:22,232] Trial 12 finished with value: 0.7978988238958789 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 12}. Best is trial 10 with value: 0.7978988238958789.
[I 2025-07-11 23:08:22,304] Trial 13 finished with value: 0.6595735884908903 and parameters: {'n_neighbors': 8, 'weights': 'distance', 'leaf_size': 10}. Best is trial 10 with value: 0.7978988238958789.
[I 2025-07-11 23:08:22,379] Trial 14 finished with value: 0.7978988238958789 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 10}. Best is trial 10 with value: 0.7978988238958789.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.56 | R2: 0.80
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.02 | R2: 0.66
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.56 | R2: 0.80
Fold 1

[I 2025-07-11 23:08:22,458] Trial 15 finished with value: 0.6595735884908903 and parameters: {'n_neighbors': 8, 'weights': 'distance', 'leaf_size': 19}. Best is trial 10 with value: 0.7978988238958789.
[I 2025-07-11 23:08:22,532] Trial 16 finished with value: 0.688795358598435 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'leaf_size': 39}. Best is trial 10 with value: 0.7978988238958789.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.02 | R2: 0.66
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.93 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:08:22,610] Trial 17 finished with value: 0.7978988238958789 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 13}. Best is trial 10 with value: 0.7978988238958789.
[I 2025-07-11 23:08:22,682] Trial 18 finished with value: 0.5451974882391918 and parameters: {'n_neighbors': 12, 'weights': 'uniform', 'leaf_size': 21}. Best is trial 10 with value: 0.7978988238958789.
[I 2025-07-11 23:08:22,755] Trial 19 finished with value: 0.7534078056617969 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'leaf_size': 29}. Best is trial 10 with value: 0.7978988238958789.

Running time: 0.1 sec
OOF RMSE: 1.56 | R2: 0.80
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.34 | R2: 0.55
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.72 | R2: 0.75
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 23:08:22,830] Trial 20 finished with value: 0.6197880484889321 and parameters: {'n_neighbors': 15, 'weights': 'distance', 'leaf_size': 35}. Best is trial 10 with value: 0.7978988238958789.
[I 2025-07-11 23:08:22,901] Trial 21 finished with value: 0.7978988238958789 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 11}. Best is trial 10 with value: 0.7978988238958789.

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.14 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.56 | R2: 0.80
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:08:23,026] Trial 22 finished with value: 0.7595830204383347 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'leaf_size': 12}. Best is trial 10 with value: 0.7978988238958789.
[I 2025-07-11 23:08:23,100] Trial 23 finished with value: 0.7595830204383347 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'leaf_size': 13}. Best is trial 10 with value: 0.7978988238958789.
[I 2025-07-11 23:08:23,173] Trial 24 finished with value: 0.7978988238958789 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 13}. Best is trial 10 with value: 0.7978988238958789.
[I 2025-07-11 23:08:23,175] A new study created in memory with name: no-name-8fd539be-dcd7-4223-ba82-d4ff5553bd82

Running time: 0.1 sec
OOF RMSE: 1.70 | R2: 0.76
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.70 | R2: 0.76
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.56 | R2: 0.80

✅ KNN - Mejor R2: 0.80
📋 Parámetros: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 10}

Buscando mejores hiperparámetros para LR...
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 23:08:23,290] Trial 0 finished with value: 0.022781471799743658 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 0 with value: 0.022781471799743658.
[I 2025-07-11 23:08:23,370] Trial 1 finished with value: 0.3338548601558131 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 1 with value: 0.3338548601558131.
[I 2025-07-11 23:08:23,466] Trial 2 finished with value: 0.022781471809709797 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 1 with value: 0.3338548601558131.

Fold 5
Running time: 0.1 sec
OOF RMSE: 3.43 | R2: 0.02
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.83 | R2: 0.33
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.43 | R2: 0.02
Fold 1

[I 2025-07-11 23:08:23,563] Trial 3 finished with value: 0.022781471799743658 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 1 with value: 0.3338548601558131.
[I 2025-07-11 23:08:23,654] Trial 4 finished with value: 0.022781471809709797 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 1 with value: 0.3338548601558131.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.43 | R2: 0.02
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.43 | R2: 0.02
Fold 1
Fold 2

[I 2025-07-11 23:08:23,746] Trial 5 finished with value: 0.022781471809709797 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 1 with value: 0.3338548601558131.
[I 2025-07-11 23:08:23,820] Trial 6 finished with value: 0.3338548601558131 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 1 with value: 0.3338548601558131.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.43 | R2: 0.02
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.83 | R2: 0.33
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:08:23,896] Trial 7 finished with value: 0.022781471809709797 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 1 with value: 0.3338548601558131.
[I 2025-07-11 23:08:23,973] Trial 8 finished with value: 0.33448262028090425 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 8 with value: 0.33448262028090425.
[I 2025-07-11 23:08:24,038] Trial 9 finished with value: 0.33448262028090425 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 8 with value: 0.33448262028090425.

Running time: 0.1 sec
OOF RMSE: 3.43 | R2: 0.02
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.83 | R2: 0.33
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.83 | R2: 0.33
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:08:24,102] Trial 10 finished with value: 0.33448262028090425 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 8 with value: 0.33448262028090425.
[I 2025-07-11 23:08:24,164] Trial 11 finished with value: 0.33448262028090425 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 8 with value: 0.33448262028090425.
[I 2025-07-11 23:08:24,227] Trial 12 finished with value: 0.33448262028090425 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 8 with value: 0.33448262028090425.
[I 2025-07-11 23:08:24,291] Trial 13 finished with value: 0.33448262028090425 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 8 with value: 0.33448262028090425.

Running time: 0.1 sec
OOF RMSE: 2.83 | R2: 0.33
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.83 | R2: 0.33
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.83 | R2: 0.33
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.83 | R2: 0.33
Fold 1

[I 2025-07-11 23:08:24,356] Trial 14 finished with value: 0.33448262028090425 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 8 with value: 0.33448262028090425.
[I 2025-07-11 23:08:24,419] Trial 15 finished with value: 0.33448262028090425 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 8 with value: 0.33448262028090425.
[I 2025-07-11 23:08:24,483] Trial 16 finished with value: 0.33448262028090425 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 8 with value: 0.33448262028090425.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.83 | R2: 0.33
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.83 | R2: 0.33
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.83 | R2: 0.33
Fold 1
Fold 2

[I 2025-07-11 23:08:24,546] Trial 17 finished with value: 0.33448262028090425 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 8 with value: 0.33448262028090425.
[I 2025-07-11 23:08:24,613] Trial 18 finished with value: 0.33448262028090425 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 8 with value: 0.33448262028090425.
[I 2025-07-11 23:08:24,676] Trial 19 finished with value: 0.33448262028090425 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 8 with value: 0.33448262028090425.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.83 | R2: 0.33
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.83 | R2: 0.33
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.83 | R2: 0.33
Fold 1
Fold 2
Fold 3

[I 2025-07-11 23:08:24,743] Trial 20 finished with value: 0.33448262028090425 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 8 with value: 0.33448262028090425.
[I 2025-07-11 23:08:24,806] Trial 21 finished with value: 0.33448262028090425 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 8 with value: 0.33448262028090425.
[I 2025-07-11 23:08:24,870] Trial 22 finished with value: 0.33448262028090425 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 8 with value: 0.33448262028090425.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.83 | R2: 0.33
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.83 | R2: 0.33
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.83 | R2: 0.33
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:08:24,936] Trial 23 finished with value: 0.33448262028090425 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 8 with value: 0.33448262028090425.
[I 2025-07-11 23:08:24,997] Trial 24 finished with value: 0.33448262028090425 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 8 with value: 0.33448262028090425.
[I 2025-07-11 23:08:24,998] A new study created in memory with name: no-name-3b2da0b4-9b28-4e56-882a-965b951fcd3f

Running time: 0.1 sec
OOF RMSE: 2.83 | R2: 0.33
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.83 | R2: 0.33

✅ LR - Mejor R2: 0.33
📋 Parámetros: {'fit_intercept': False, 'positive': True}

Buscando mejores hiperparámetros para RF...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:08:27,248] Trial 0 finished with value: 0.550472490026813 and parameters: {'n_estimators': 100, 'max_depth': 11, 'min_samples_split': 3, 'min_samples_leaf': 5, 'bootstrap': False}. Best is trial 0 with value: 0.550472490026813.

Running time: 2.2 sec
OOF RMSE: 2.32 | R2: 0.55
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:08:28,575] Trial 1 finished with value: 0.5871757075223953 and parameters: {'n_estimators': 100, 'max_depth': 6, 'min_samples_split': 2, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 1 with value: 0.5871757075223953.

Running time: 1.3 sec
OOF RMSE: 2.23 | R2: 0.59
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:08:30,469] Trial 2 finished with value: 0.4806166550430012 and parameters: {'n_estimators': 100, 'max_depth': 6, 'min_samples_split': 6, 'min_samples_leaf': 4, 'bootstrap': False}. Best is trial 1 with value: 0.5871757075223953.

Running time: 1.9 sec
OOF RMSE: 2.50 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:08:37,683] Trial 3 finished with value: 0.6366094073743037 and parameters: {'n_estimators': 500, 'max_depth': 6, 'min_samples_split': 2, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 3 with value: 0.6366094073743037.

Running time: 7.2 sec
OOF RMSE: 2.09 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:08:40,480] Trial 4 finished with value: 0.5277199739585627 and parameters: {'n_estimators': 100, 'max_depth': 11, 'min_samples_split': 5, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 3 with value: 0.6366094073743037.

Running time: 2.8 sec
OOF RMSE: 2.38 | R2: 0.53
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:08:49,466] Trial 5 finished with value: 0.638332628173329 and parameters: {'n_estimators': 500, 'max_depth': 12, 'min_samples_split': 8, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 5 with value: 0.638332628173329.

Running time: 9.0 sec
OOF RMSE: 2.08 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:08:51,991] Trial 6 finished with value: 0.5323884909199116 and parameters: {'n_estimators': 100, 'max_depth': 9, 'min_samples_split': 6, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 5 with value: 0.638332628173329.

Running time: 2.5 sec
OOF RMSE: 2.37 | R2: 0.53
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:08:54,624] Trial 7 finished with value: 0.5907825638662614 and parameters: {'n_estimators': 100, 'max_depth': 11, 'min_samples_split': 5, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 5 with value: 0.638332628173329.

Running time: 2.6 sec
OOF RMSE: 2.22 | R2: 0.59
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:09:07,263] Trial 8 finished with value: 0.5383456723419697 and parameters: {'n_estimators': 500, 'max_depth': 11, 'min_samples_split': 8, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 5 with value: 0.638332628173329.

Running time: 12.6 sec
OOF RMSE: 2.36 | R2: 0.54
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:09:18,380] Trial 9 finished with value: 0.5510793147936899 and parameters: {'n_estimators': 500, 'max_depth': 8, 'min_samples_split': 3, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 5 with value: 0.638332628173329.

Running time: 11.1 sec
OOF RMSE: 2.32 | R2: 0.55
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:09:23,023] Trial 10 finished with value: 0.608298239646859 and parameters: {'n_estimators': 300, 'max_depth': 15, 'min_samples_split': 10, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 5 with value: 0.638332628173329.

Running time: 4.6 sec
OOF RMSE: 2.17 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:09:31,559] Trial 11 finished with value: 0.6272281825655752 and parameters: {'n_estimators': 500, 'max_depth': 14, 'min_samples_split': 8, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 5 with value: 0.638332628173329.

Running time: 8.5 sec
OOF RMSE: 2.12 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:09:40,541] Trial 12 finished with value: 0.639421805398748 and parameters: {'n_estimators': 500, 'max_depth': 13, 'min_samples_split': 8, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 12 with value: 0.639421805398748.

Running time: 9.0 sec
OOF RMSE: 2.08 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:09:49,379] Trial 13 finished with value: 0.6291143384291658 and parameters: {'n_estimators': 500, 'max_depth': 13, 'min_samples_split': 9, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 12 with value: 0.639421805398748.

Running time: 8.8 sec
OOF RMSE: 2.11 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:09:54,784] Trial 14 finished with value: 0.6380681695014729 and parameters: {'n_estimators': 300, 'max_depth': 13, 'min_samples_split': 8, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 12 with value: 0.639421805398748.

Running time: 5.4 sec
OOF RMSE: 2.09 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:10:03,468] Trial 15 finished with value: 0.6198079674227104 and parameters: {'n_estimators': 500, 'max_depth': 13, 'min_samples_split': 10, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 12 with value: 0.639421805398748.

Running time: 8.7 sec
OOF RMSE: 2.14 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:10:11,036] Trial 16 finished with value: 0.6007488294472441 and parameters: {'n_estimators': 500, 'max_depth': 15, 'min_samples_split': 8, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 12 with value: 0.639421805398748.

Running time: 7.6 sec
OOF RMSE: 2.19 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:10:19,251] Trial 17 finished with value: 0.6325999829514152 and parameters: {'n_estimators': 500, 'max_depth': 9, 'min_samples_split': 7, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 12 with value: 0.639421805398748.

Running time: 8.2 sec
OOF RMSE: 2.10 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:10:23,919] Trial 18 finished with value: 0.6165153222675671 and parameters: {'n_estimators': 300, 'max_depth': 12, 'min_samples_split': 9, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 12 with value: 0.639421805398748.

Running time: 4.7 sec
OOF RMSE: 2.15 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:10:33,107] Trial 19 finished with value: 0.6469572920078377 and parameters: {'n_estimators': 500, 'max_depth': 14, 'min_samples_split': 7, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 19 with value: 0.6469572920078377.

Running time: 9.2 sec
OOF RMSE: 2.06 | R2: 0.65
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:10:41,321] Trial 20 finished with value: 0.6253731322573262 and parameters: {'n_estimators': 500, 'max_depth': 14, 'min_samples_split': 5, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 19 with value: 0.6469572920078377.

Running time: 8.2 sec
OOF RMSE: 2.12 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:10:50,414] Trial 21 finished with value: 0.6466974122749742 and parameters: {'n_estimators': 500, 'max_depth': 12, 'min_samples_split': 7, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 19 with value: 0.6469572920078377.

Running time: 9.1 sec
OOF RMSE: 2.06 | R2: 0.65
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:10:59,586] Trial 22 finished with value: 0.6469572920078377 and parameters: {'n_estimators': 500, 'max_depth': 14, 'min_samples_split': 7, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 19 with value: 0.6469572920078377.

Running time: 9.2 sec
OOF RMSE: 2.06 | R2: 0.65
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:11:08,202] Trial 23 finished with value: 0.6315656840883428 and parameters: {'n_estimators': 500, 'max_depth': 14, 'min_samples_split': 7, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 19 with value: 0.6469572920078377.

Running time: 8.6 sec
OOF RMSE: 2.10 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:11:17,398] Trial 24 finished with value: 0.6474317523517936 and parameters: {'n_estimators': 500, 'max_depth': 15, 'min_samples_split': 7, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 24 with value: 0.6474317523517936.
[I 2025-07-11 23:11:17,399] A new study created in memory with name: no-name-cbb16fd5-efa7-40f4-b56d-d2bed471926c

Running time: 9.2 sec
OOF RMSE: 2.06 | R2: 0.65

✅ RF - Mejor R2: 0.65
📋 Parámetros: {'n_estimators': 500, 'max_depth': 15, 'min_samples_split': 7, 'min_samples_leaf': 1, 'bootstrap': True}

Buscando mejores hiperparámetros para CAT...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:11:31,613] Trial 0 finished with value: 0.6873254137292919 and parameters: {'iterations': 1000, 'learning_rate': 0.011543419903124684, 'depth': 7, 'l2_leaf_reg': 6.606345397339421}. Best is trial 0 with value: 0.6873254137292919.

Running time: 14.2 sec
OOF RMSE: 1.94 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:12:00,137] Trial 1 finished with value: 0.7102478951694247 and parameters: {'iterations': 2000, 'learning_rate': 0.02362132946798511, 'depth': 7, 'l2_leaf_reg': 5.15651903784144}. Best is trial 1 with value: 0.7102478951694247.

Running time: 28.5 sec
OOF RMSE: 1.87 | R2: 0.71
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:12:01,614] Trial 2 finished with value: 0.6769850543529922 and parameters: {'iterations': 500, 'learning_rate': 0.09666451871593873, 'depth': 4, 'l2_leaf_reg': 5.304050202710957}. Best is trial 1 with value: 0.7102478951694247.

Running time: 1.5 sec
OOF RMSE: 1.97 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:12:09,879] Trial 3 finished with value: 0.6881083889266723 and parameters: {'iterations': 2000, 'learning_rate': 0.02023265080789348, 'depth': 5, 'l2_leaf_reg': 9.846084217061755}. Best is trial 1 with value: 0.7102478951694247.

Running time: 8.3 sec
OOF RMSE: 1.94 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:14:35,064] Trial 4 finished with value: 0.6933661427918992 and parameters: {'iterations': 1000, 'learning_rate': 0.020950975284004577, 'depth': 10, 'l2_leaf_reg': 5.38255152606406}. Best is trial 1 with value: 0.7102478951694247.

Running time: 145.2 sec
OOF RMSE: 1.92 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:14:44,339] Trial 5 finished with value: 0.6894938256351547 and parameters: {'iterations': 2000, 'learning_rate': 0.027700320291904973, 'depth': 5, 'l2_leaf_reg': 3.4067367763301255}. Best is trial 1 with value: 0.7102478951694247.

Running time: 9.3 sec
OOF RMSE: 1.93 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:17:35,971] Trial 6 finished with value: 0.7032477697638433 and parameters: {'iterations': 2000, 'learning_rate': 0.03484487895654677, 'depth': 9, 'l2_leaf_reg': 8.825306775472892}. Best is trial 1 with value: 0.7102478951694247.

Running time: 171.6 sec
OOF RMSE: 1.89 | R2: 0.70
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:18:50,867] Trial 7 finished with value: 0.7118255853240336 and parameters: {'iterations': 2000, 'learning_rate': 0.019084523026705158, 'depth': 8, 'l2_leaf_reg': 2.7477952562351993}. Best is trial 7 with value: 0.7118255853240336.

Running time: 74.9 sec
OOF RMSE: 1.86 | R2: 0.71
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:20:04,023] Trial 8 finished with value: 0.6785307921700725 and parameters: {'iterations': 500, 'learning_rate': 0.031015504119694906, 'depth': 10, 'l2_leaf_reg': 7.5923783584952425}. Best is trial 7 with value: 0.7118255853240336.

Running time: 73.2 sec
OOF RMSE: 1.97 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:20:06,400] Trial 9 finished with value: 0.685983914674423 and parameters: {'iterations': 500, 'learning_rate': 0.05066349453844599, 'depth': 5, 'l2_leaf_reg': 1.9628799368404815}. Best is trial 7 with value: 0.7118255853240336.

Running time: 2.4 sec
OOF RMSE: 1.94 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:21:21,453] Trial 10 finished with value: 0.7176161845518338 and parameters: {'iterations': 2000, 'learning_rate': 0.010780676246171898, 'depth': 8, 'l2_leaf_reg': 1.4665764798430505}. Best is trial 10 with value: 0.7176161845518338.
[I 2025-07-11 23:21:21,454] A new study created in memory with name: no-name-83042654-f374-491d-af8c-8d8a37eccc39
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.372e-01, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.066e-01, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 23:21:21,562] Trial 0 finished with value: 0.4855555461803053 and parameters: {'alpha': 0.06764292600308248, 'l1_ratio': 0.14247526284368373}. Best is trial 0 with value: 0.4855555461803053.

Running time: 75.0 sec
OOF RMSE: 1.84 | R2: 0.72

✅ CAT - Mejor R2: 0.72
📋 Parámetros: {'iterations': 2000, 'learning_rate': 0.010780676246171898, 'depth': 8, 'l2_leaf_reg': 1.4665764798430505}

Buscando mejores hiperparámetros para EN...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.49 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.523e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.443e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.387e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.042e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.491e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 23:21:21,683] Trial 1 finished with value: 0.14697288874912373 and parameters: {'alpha': 0.0004813442758505411, 'l1_ratio': 0.7214668772603757}. Best is trial 0 with value: 0.4855555461803053.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.058e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.908e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.985e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.755e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.099e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 23:21:21,804] Trial 2 finished with value: 0.17020449953073447 and parameters: {'alpha': 0.0005233978121361781, 'l1_ratio': 0.13478921770683816}. Best is trial 0 with value: 0.4855555461803053.

Fold 5
Running time: 0.1 sec
OOF RMSE: 3.20 | R2: 0.15
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.16 | R2: 0.17
Fold 1
Fold 2
Fold 3

[I 2025-07-11 23:21:21,911] Trial 3 finished with value: 0.2971318143153371 and parameters: {'alpha': 3.063320140716159, 'l1_ratio': 0.2890043452495923}. Best is trial 0 with value: 0.4855555461803053.
[I 2025-07-11 23:21:22,039] Trial 4 finished with value: 0.4361159460401677 and parameters: {'alpha': 0.905215692936587, 'l1_ratio': 0.27894099457610655}. Best is trial 0 with value: 0.4855555461803053.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.91 | R2: 0.30
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.60 | R2: 0.44
Fold 1

[I 2025-07-11 23:21:22,175] Trial 5 finished with value: 0.3886897697781101 and parameters: {'alpha': 0.014085353788028885, 'l1_ratio': 0.9837001491699107}. Best is trial 0 with value: 0.4855555461803053.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.71 | R2: 0.39
Fold 1
Fold 2
Fold 3

[I 2025-07-11 23:21:22,322] Trial 6 finished with value: -0.00027817151752640434 and parameters: {'alpha': 3.670832116674226, 'l1_ratio': 0.8377941338305795}. Best is trial 0 with value: 0.4855555461803053.
[I 2025-07-11 23:21:22,449] Trial 7 finished with value: 0.45189658681921396 and parameters: {'alpha': 0.5623193096170415, 'l1_ratio': 0.4310660763023393}. Best is trial 0 with value: 0.4855555461803053.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.47 | R2: -0.00
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.57 | R2: 0.45
Fold 1

[I 2025-07-11 23:21:22,586] Trial 8 finished with value: 0.48568248977031236 and parameters: {'alpha': 0.2085001740040576, 'l1_ratio': 0.26929941050981077}. Best is trial 8 with value: 0.48568248977031236.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.616e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.575e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.49 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.580e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.344e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.695e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 23:21:22,712] Trial 9 finished with value: 0.16706606313332173 and parameters: {'alpha': 0.0006008194638659172, 'l1_ratio': 0.39754173749642663}. Best is trial 8 with value: 0.48568248977031236.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.546e-01, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.542e-01, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.304e-01, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.955e+00, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 23:21:22,843] Trial 10 finished with value: 0.4142213040302347 and parameters: {'alpha': 0.01727978948024196, 'l1_ratio': 0.6121292641742028}. Best is trial 8 with value: 0.48568248977031236.

Running time: 0.1 sec
OOF RMSE: 3.16 | R2: 0.17
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.65 | R2: 0.41
Fold 1
Fold 2

[I 2025-07-11 23:21:22,986] Trial 11 finished with value: 0.4941155537654387 and parameters: {'alpha': 0.11952302072359938, 'l1_ratio': 0.08795169291598975}. Best is trial 11 with value: 0.4941155537654387.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.47 | R2: 0.49
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.936e+01, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.261e+00, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.834e+00, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.527e+01, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.293e+01, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 23:21:23,178] Trial 12 finished with value: 0.4926824752557767 and parameters: {'alpha': 0.1304683902049029, 'l1_ratio': 0.007661623224404002}. Best is trial 11 with value: 0.4941155537654387.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.893e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(

Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 2.47 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.413e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.252e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.503e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.364e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 23:21:23,368] Trial 13 finished with value: 0.4792284698885543 and parameters: {'alpha': 0.0610434720190391, 'l1_ratio': 0.024467298581660864}. Best is trial 11 with value: 0.4941155537654387.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.102e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.858e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.924e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.889e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.212e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 23:21:23,505] Trial 14 finished with value: 0.31143984831671956 and parameters: {'alpha': 0.0038412170466936286, 'l1_ratio': 0.026364510104303296}. Best is trial 11 with value: 0.4941155537654387.

Fold 5
Running time: 0.2 sec
OOF RMSE: 2.50 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.88 | R2: 0.31
Fold 1
Fold 2

[I 2025-07-11 23:21:23,607] Trial 15 finished with value: 0.4895344076458654 and parameters: {'alpha': 0.19160495532415836, 'l1_ratio': 0.14567510247599166}. Best is trial 11 with value: 0.4941155537654387.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.264e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.030e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.117e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.036e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.387e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 23:21:23,756] Trial 16 finished with value: 0.3136920074133779 and parameters: {'alpha': 0.003962166244292545, 'l1_ratio': 0.012435878495324498}. Best is trial 11 with value: 0.4941155537654387.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.48 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.87 | R2: 0.31

[I 2025-07-11 23:21:23,848] Trial 17 finished with value: 0.4600218624229243 and parameters: {'alpha': 0.4626270425450862, 'l1_ratio': 0.19161198080116237}. Best is trial 11 with value: 0.4941155537654387.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.728e+01, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.55 | R2: 0.46
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.001e+01, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.701e+01, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.445e+01, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.150e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 23:21:23,983] Trial 18 finished with value: 0.3519155319648172 and parameters: {'alpha': 0.008339883217537949, 'l1_ratio': 0.554417539488932}. Best is trial 11 with value: 0.4941155537654387.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.135e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.913e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.985e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.704e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.091e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 23:21:24,147] Trial 19 finished with value: 0.132298344010361 and parameters: {'alpha': 0.0001283608267088251, 'l1_ratio': 0.39801480067770456}. Best is trial 11 with value: 0.4941155537654387.

Running time: 0.1 sec
OOF RMSE: 2.79 | R2: 0.35
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 3.23 | R2: 0.13
Fold 1

[I 2025-07-11 23:21:24,270] Trial 20 finished with value: 0.27659973155502826 and parameters: {'alpha': 8.66750072093159, 'l1_ratio': 0.06867246123241694}. Best is trial 11 with value: 0.4941155537654387.
[I 2025-07-11 23:21:24,369] Trial 21 finished with value: 0.4949046429741678 and parameters: {'alpha': 0.13557024885542535, 'l1_ratio': 0.17699376276530177}. Best is trial 21 with value: 0.4949046429741678.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.95 | R2: 0.28
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.46 | R2: 0.49
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.316e+00, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.933e+00, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 23:21:24,497] Trial 22 finished with value: 0.4784057233391411 and parameters: {'alpha': 0.05223292208637233, 'l1_ratio': 0.2125932482146006}. Best is trial 21 with value: 0.4949046429741678.
[I 2025-07-11 23:21:24,602] Trial 23 finished with value: 0.4829841671244751 and parameters: {'alpha': 0.21676877928826768, 'l1_ratio': 0.3279276469122526}. Best is trial 21 with value: 0.4949046429741678.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.50 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.49 | R2: 0.48

[I 2025-07-11 23:21:24,723] Trial 24 finished with value: 0.4941747959648889 and parameters: {'alpha': 0.12364091183946468, 'l1_ratio': 0.08643519997971288}. Best is trial 21 with value: 0.4949046429741678.
[I 2025-07-11 23:21:24,724] A new study created in memory with name: no-name-9bcef0a3-4f53-48f6-a847-11e9ab4234e6

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.47 | R2: 0.49

✅ EN - Mejor R2: 0.49
📋 Parámetros: {'alpha': 0.13557024885542535, 'l1_ratio': 0.17699376276530177}

🔍 Optimizando en TOA_5x5_depth_lt_1...
Buscando mejores hiperparámetros para XGB...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:21:35,836] Trial 0 finished with value: 0.6792000159839725 and parameters: {'n_estimators': 2000, 'learning_rate': 0.011208147231334575, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.8553642983113656, 'colsample_bytree': 0.6201564100408333}. Best is trial 0 with value: 0.6792000159839725.

Running time: 11.1 sec
OOF RMSE: 2.14 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:21:40,643] Trial 1 finished with value: 0.663606702640098 and parameters: {'n_estimators': 1000, 'learning_rate': 0.08673289793870038, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.8187814297050234, 'colsample_bytree': 0.8609488835863677}. Best is trial 0 with value: 0.6792000159839725.

Running time: 4.8 sec
OOF RMSE: 2.19 | R2: 0.66
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:21:49,474] Trial 2 finished with value: 0.6468705800081955 and parameters: {'n_estimators': 2000, 'learning_rate': 0.07276805321252575, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.6811386254338796, 'colsample_bytree': 0.6225119412619508}. Best is trial 0 with value: 0.6792000159839725.

Running time: 8.8 sec
OOF RMSE: 2.25 | R2: 0.65
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:21:54,551] Trial 3 finished with value: 0.6585796842711622 and parameters: {'n_estimators': 1000, 'learning_rate': 0.02637253687609379, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.6712346908053339, 'colsample_bytree': 0.93106987103275}. Best is trial 0 with value: 0.6792000159839725.

Running time: 5.1 sec
OOF RMSE: 2.21 | R2: 0.66
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:22:05,858] Trial 4 finished with value: 0.6444334428291292 and parameters: {'n_estimators': 2000, 'learning_rate': 0.021380705868326362, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.9997730942314591, 'colsample_bytree': 0.6691980107332749}. Best is trial 0 with value: 0.6792000159839725.

Running time: 11.3 sec
OOF RMSE: 2.25 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:22:13,929] Trial 5 finished with value: 0.642573283439021 and parameters: {'n_estimators': 1000, 'learning_rate': 0.03865930417197165, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.8057446595811457, 'colsample_bytree': 0.9420667816433783}. Best is trial 0 with value: 0.6792000159839725.

Running time: 8.1 sec
OOF RMSE: 2.26 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:22:16,921] Trial 6 finished with value: 0.6554003095244745 and parameters: {'n_estimators': 500, 'learning_rate': 0.01708890523491804, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.9854278552014589, 'colsample_bytree': 0.7724048748446454}. Best is trial 0 with value: 0.6792000159839725.

Running time: 3.0 sec
OOF RMSE: 2.22 | R2: 0.66
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:22:22,380] Trial 7 finished with value: 0.647350358524728 and parameters: {'n_estimators': 1000, 'learning_rate': 0.05386804577305043, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.6132670840551107, 'colsample_bytree': 0.7302219522691769}. Best is trial 0 with value: 0.6792000159839725.

Running time: 5.5 sec
OOF RMSE: 2.25 | R2: 0.65
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:22:33,214] Trial 8 finished with value: 0.6659161753805976 and parameters: {'n_estimators': 2000, 'learning_rate': 0.03145368404713666, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.6389802457973273, 'colsample_bytree': 0.7078416599204429}. Best is trial 0 with value: 0.6792000159839725.

Running time: 10.8 sec
OOF RMSE: 2.19 | R2: 0.67
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:22:39,036] Trial 9 finished with value: 0.6297118319266191 and parameters: {'n_estimators': 1000, 'learning_rate': 0.05279241824586696, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.6084306216530552, 'colsample_bytree': 0.7769249759286094}. Best is trial 0 with value: 0.6792000159839725.

Running time: 5.8 sec
OOF RMSE: 2.30 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:22:43,735] Trial 10 finished with value: 0.6763274072016829 and parameters: {'n_estimators': 500, 'learning_rate': 0.006631086811191572, 'max_depth': 8, 'min_child_weight': 1, 'subsample': 0.9062425611433268, 'colsample_bytree': 0.6169349302390614}. Best is trial 0 with value: 0.6792000159839725.

Running time: 4.7 sec
OOF RMSE: 2.15 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:22:48,712] Trial 11 finished with value: 0.676999089361576 and parameters: {'n_estimators': 500, 'learning_rate': 0.006034726580663242, 'max_depth': 8, 'min_child_weight': 1, 'subsample': 0.9093792566661268, 'colsample_bytree': 0.6016096468348047}. Best is trial 0 with value: 0.6792000159839725.

Running time: 5.0 sec
OOF RMSE: 2.15 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:22:53,821] Trial 12 finished with value: 0.6771051423079276 and parameters: {'n_estimators': 500, 'learning_rate': 0.005655257866450312, 'max_depth': 8, 'min_child_weight': 1, 'subsample': 0.8975254260615346, 'colsample_bytree': 0.6077905680106852}. Best is trial 0 with value: 0.6792000159839725.

Running time: 5.1 sec
OOF RMSE: 2.15 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:22:57,611] Trial 13 finished with value: 0.6853618986347032 and parameters: {'n_estimators': 500, 'learning_rate': 0.011009137284924024, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.8821066458162379, 'colsample_bytree': 0.6663271648031495}. Best is trial 13 with value: 0.6853618986347032.

Running time: 3.8 sec
OOF RMSE: 2.12 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:23:12,217] Trial 14 finished with value: 0.6722901854446293 and parameters: {'n_estimators': 2000, 'learning_rate': 0.013088131777967067, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.745941960009442, 'colsample_bytree': 0.6734478996263221}. Best is trial 13 with value: 0.6853618986347032.

Running time: 14.6 sec
OOF RMSE: 2.16 | R2: 0.67
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:23:15,589] Trial 15 finished with value: 0.6719755186763494 and parameters: {'n_estimators': 500, 'learning_rate': 0.01000294922114597, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.8580672187884464, 'colsample_bytree': 0.8464433204669819}. Best is trial 13 with value: 0.6853618986347032.

Running time: 3.4 sec
OOF RMSE: 2.17 | R2: 0.67
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:23:30,354] Trial 16 finished with value: 0.6720199970337701 and parameters: {'n_estimators': 2000, 'learning_rate': 0.009919298104700516, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.7591255206596136, 'colsample_bytree': 0.6709548588549216}. Best is trial 13 with value: 0.6853618986347032.

Running time: 14.8 sec
OOF RMSE: 2.17 | R2: 0.67
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:23:33,470] Trial 17 finished with value: 0.6924155975812776 and parameters: {'n_estimators': 500, 'learning_rate': 0.008907371535392642, 'max_depth': 6, 'min_child_weight': 1, 'subsample': 0.8517122366675387, 'colsample_bytree': 0.7204468880571087}. Best is trial 17 with value: 0.6924155975812776.

Running time: 3.1 sec
OOF RMSE: 2.10 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:23:37,790] Trial 18 finished with value: 0.6871171918463121 and parameters: {'n_estimators': 500, 'learning_rate': 0.007925683331078428, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.9554192217048865, 'colsample_bytree': 0.7435556255723254}. Best is trial 17 with value: 0.6924155975812776.

Running time: 4.3 sec
OOF RMSE: 2.12 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:23:41,252] Trial 19 finished with value: 0.6838896227941209 and parameters: {'n_estimators': 500, 'learning_rate': 0.008166250606690876, 'max_depth': 6, 'min_child_weight': 1, 'subsample': 0.9520390975257741, 'colsample_bytree': 0.810519070717907}. Best is trial 17 with value: 0.6924155975812776.

Running time: 3.5 sec
OOF RMSE: 2.13 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:23:45,398] Trial 20 finished with value: 0.6744813216719773 and parameters: {'n_estimators': 500, 'learning_rate': 0.015349493091910516, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.7580286294747435, 'colsample_bytree': 0.7288658411417828}. Best is trial 17 with value: 0.6924155975812776.

Running time: 4.1 sec
OOF RMSE: 2.16 | R2: 0.67
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:23:49,598] Trial 21 finished with value: 0.6871204065358434 and parameters: {'n_estimators': 500, 'learning_rate': 0.007863837672788665, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.9419091161116045, 'colsample_bytree': 0.7131329351467218}. Best is trial 17 with value: 0.6924155975812776.

Running time: 4.2 sec
OOF RMSE: 2.12 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:23:54,863] Trial 22 finished with value: 0.6879643228118973 and parameters: {'n_estimators': 500, 'learning_rate': 0.007696369431568546, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.9460785642548089, 'colsample_bytree': 0.7525667998612806}. Best is trial 17 with value: 0.6924155975812776.

Running time: 5.3 sec
OOF RMSE: 2.11 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:23:58,345] Trial 23 finished with value: 0.6775651341993847 and parameters: {'n_estimators': 500, 'learning_rate': 0.005202283982365189, 'max_depth': 6, 'min_child_weight': 1, 'subsample': 0.9427434784416664, 'colsample_bytree': 0.8078128111887312}. Best is trial 17 with value: 0.6924155975812776.

Running time: 3.5 sec
OOF RMSE: 2.15 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:24:03,459] Trial 24 finished with value: 0.6636855787605298 and parameters: {'n_estimators': 500, 'learning_rate': 0.007492636105303076, 'max_depth': 8, 'min_child_weight': 2, 'subsample': 0.9324372694843985, 'colsample_bytree': 0.700546912680478}. Best is trial 17 with value: 0.6924155975812776.
[I 2025-07-11 23:24:03,461] A new study created in memory with name: no-name-93a93cff-6669-43d8-a245-dee7282a66ea

Running time: 5.1 sec
OOF RMSE: 2.19 | R2: 0.66

✅ XGB - Mejor R2: 0.69
📋 Parámetros: {'n_estimators': 500, 'learning_rate': 0.008907371535392642, 'max_depth': 6, 'min_child_weight': 1, 'subsample': 0.8517122366675387, 'colsample_bytree': 0.7204468880571087}

Buscando mejores hiperparámetros para LBM...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:24:04,368] Trial 0 finished with value: 0.7198535349685469 and parameters: {'learning_rate': 0.01496494086250747, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 23, 'subsample': 0.8033971167437775, 'colsample_bytree': 0.9564118104297373, 'n_estimators': 2000}. Best is trial 0 with value: 0.7198535349685469.

Running time: 0.9 sec
OOF RMSE: 2.00 | R2: 0.72
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 23:24:04,653] Trial 1 finished with value: 0.5978710317894076 and parameters: {'learning_rate': 0.008568870446481495, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 9, 'subsample': 0.7889744949818019, 'colsample_bytree': 0.7086191644437664, 'n_estimators': 500}. Best is trial 0 with value: 0.7198535349685469.

Fold 5
Running time: 0.3 sec
OOF RMSE: 2.40 | R2: 0.60
Fold 1
Fold 2
Fold 3

[I 2025-07-11 23:24:04,961] Trial 2 finished with value: 0.6991406400894492 and parameters: {'learning_rate': 0.018501309631223213, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 19, 'subsample': 0.6531124108132936, 'colsample_bytree': 0.9939944575898596, 'n_estimators': 500}. Best is trial 0 with value: 0.7198535349685469.

Fold 4
Fold 5
Running time: 0.3 sec
OOF RMSE: 2.07 | R2: 0.70
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:24:05,564] Trial 3 finished with value: 0.7133439584378704 and parameters: {'learning_rate': 0.026214382652714804, 'num_leaves': 80, 'max_depth': 6, 'min_child_samples': 15, 'subsample': 0.7612154684422434, 'colsample_bytree': 0.9650041907788433, 'n_estimators': 1000}. Best is trial 0 with value: 0.7198535349685469.

Running time: 0.6 sec
OOF RMSE: 2.02 | R2: 0.71
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 23:24:05,842] Trial 4 finished with value: 0.7087424496575798 and parameters: {'learning_rate': 0.03275566820139721, 'num_leaves': 60, 'max_depth': 6, 'min_child_samples': 23, 'subsample': 0.6289831376900091, 'colsample_bytree': 0.8773049708119713, 'n_estimators': 500}. Best is trial 0 with value: 0.7198535349685469.

Fold 5
Running time: 0.3 sec
OOF RMSE: 2.04 | R2: 0.71
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 23:24:06,405] Trial 5 finished with value: 0.6992560202605672 and parameters: {'learning_rate': 0.026906896848517547, 'num_leaves': 80, 'max_depth': 5, 'min_child_samples': 20, 'subsample': 0.7226130401982565, 'colsample_bytree': 0.9703404221413182, 'n_estimators': 1000}. Best is trial 0 with value: 0.7198535349685469.

Fold 5
Running time: 0.6 sec
OOF RMSE: 2.07 | R2: 0.70
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:24:07,253] Trial 6 finished with value: 0.6927838094273975 and parameters: {'learning_rate': 0.005405109483790391, 'num_leaves': 80, 'max_depth': 8, 'min_child_samples': 24, 'subsample': 0.973210160846551, 'colsample_bytree': 0.6390271836474413, 'n_estimators': 2000}. Best is trial 0 with value: 0.7198535349685469.

Running time: 0.8 sec
OOF RMSE: 2.10 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:24:08,538] Trial 7 finished with value: 0.7024212032998882 and parameters: {'learning_rate': 0.008147363778725786, 'num_leaves': 60, 'max_depth': 7, 'min_child_samples': 15, 'subsample': 0.7740251255334679, 'colsample_bytree': 0.9404578883266812, 'n_estimators': 2000}. Best is trial 0 with value: 0.7198535349685469.

Running time: 1.3 sec
OOF RMSE: 2.06 | R2: 0.70
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:24:09,701] Trial 8 finished with value: 0.6538735862104326 and parameters: {'learning_rate': 0.04304118786306139, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 7, 'subsample': 0.6635815713202585, 'colsample_bytree': 0.7673836307078397, 'n_estimators': 2000}. Best is trial 0 with value: 0.7198535349685469.

Running time: 1.2 sec
OOF RMSE: 2.22 | R2: 0.65
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 23:24:09,970] Trial 9 finished with value: 0.6765113052156996 and parameters: {'learning_rate': 0.02068344206192638, 'num_leaves': 80, 'max_depth': 5, 'min_child_samples': 20, 'subsample': 0.6835151954010734, 'colsample_bytree': 0.9520969699525239, 'n_estimators': 500}. Best is trial 0 with value: 0.7198535349685469.

Fold 5
Running time: 0.3 sec
OOF RMSE: 2.15 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 23:24:10,931] Trial 10 finished with value: 0.7213029084335902 and parameters: {'learning_rate': 0.07362645632060383, 'num_leaves': 40, 'max_depth': 7, 'min_child_samples': 25, 'subsample': 0.8847201202527167, 'colsample_bytree': 0.8741729968279447, 'n_estimators': 2000}. Best is trial 10 with value: 0.7213029084335902.

Fold 5
Running time: 1.0 sec
OOF RMSE: 2.00 | R2: 0.72
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:24:11,830] Trial 11 finished with value: 0.7120180061182125 and parameters: {'learning_rate': 0.05586832769091926, 'num_leaves': 40, 'max_depth': 7, 'min_child_samples': 25, 'subsample': 0.890097623741198, 'colsample_bytree': 0.8567647262232893, 'n_estimators': 2000}. Best is trial 10 with value: 0.7213029084335902.

Running time: 0.9 sec
OOF RMSE: 2.03 | R2: 0.71
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:24:13,256] Trial 12 finished with value: 0.6390389378642307 and parameters: {'learning_rate': 0.013502852244685124, 'num_leaves': 40, 'max_depth': 8, 'min_child_samples': 11, 'subsample': 0.8705283441258738, 'colsample_bytree': 0.8687052952173149, 'n_estimators': 2000}. Best is trial 10 with value: 0.7213029084335902.

Running time: 1.4 sec
OOF RMSE: 2.27 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 23:24:14,249] Trial 13 finished with value: 0.7142403393474486 and parameters: {'learning_rate': 0.08798918507425216, 'num_leaves': 40, 'max_depth': 7, 'min_child_samples': 22, 'subsample': 0.8600958058887475, 'colsample_bytree': 0.8041370158640929, 'n_estimators': 2000}. Best is trial 10 with value: 0.7213029084335902.

Fold 5
Running time: 1.0 sec
OOF RMSE: 2.02 | R2: 0.71
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:24:15,398] Trial 14 finished with value: 0.7168639428426042 and parameters: {'learning_rate': 0.09874061416504508, 'num_leaves': 40, 'max_depth': 7, 'min_child_samples': 17, 'subsample': 0.9453951619930238, 'colsample_bytree': 0.9095018459787024, 'n_estimators': 2000}. Best is trial 10 with value: 0.7213029084335902.

Running time: 1.1 sec
OOF RMSE: 2.01 | R2: 0.72
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:24:16,332] Trial 15 finished with value: 0.7175730984450013 and parameters: {'learning_rate': 0.013531155240945099, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 22, 'subsample': 0.8353566901525912, 'colsample_bytree': 0.8080648387898183, 'n_estimators': 2000}. Best is trial 10 with value: 0.7213029084335902.

Running time: 0.9 sec
OOF RMSE: 2.01 | R2: 0.72
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:24:16,831] Trial 16 finished with value: 0.7166672937491405 and parameters: {'learning_rate': 0.065919625232846, 'num_leaves': 20, 'max_depth': 8, 'min_child_samples': 25, 'subsample': 0.9321729027152855, 'colsample_bytree': 0.9114443438276812, 'n_estimators': 1000}. Best is trial 10 with value: 0.7213029084335902.

Running time: 0.5 sec
OOF RMSE: 2.01 | R2: 0.72
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:24:18,091] Trial 17 finished with value: 0.6717230890323493 and parameters: {'learning_rate': 0.013587626035380706, 'num_leaves': 40, 'max_depth': 7, 'min_child_samples': 12, 'subsample': 0.8215859234493416, 'colsample_bytree': 0.8410301172517778, 'n_estimators': 2000}. Best is trial 10 with value: 0.7213029084335902.

Running time: 1.3 sec
OOF RMSE: 2.17 | R2: 0.67
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 23:24:19,092] Trial 18 finished with value: 0.7264652032908214 and parameters: {'learning_rate': 0.03770587319568488, 'num_leaves': 60, 'max_depth': 6, 'min_child_samples': 18, 'subsample': 0.910944028016134, 'colsample_bytree': 0.7485067661016604, 'n_estimators': 2000}. Best is trial 18 with value: 0.7264652032908214.

Fold 5
Running time: 1.0 sec
OOF RMSE: 1.98 | R2: 0.73
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 23:24:19,682] Trial 19 finished with value: 0.7105134709434464 and parameters: {'learning_rate': 0.04011573795968778, 'num_leaves': 60, 'max_depth': 7, 'min_child_samples': 17, 'subsample': 0.9949153993150804, 'colsample_bytree': 0.735637996812172, 'n_estimators': 1000}. Best is trial 18 with value: 0.7264652032908214.

Fold 5
Running time: 0.6 sec
OOF RMSE: 2.03 | R2: 0.71
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:24:20,785] Trial 20 finished with value: 0.6748259709811337 and parameters: {'learning_rate': 0.06441198898788764, 'num_leaves': 60, 'max_depth': 6, 'min_child_samples': 12, 'subsample': 0.9108926945094129, 'colsample_bytree': 0.6582447911201423, 'n_estimators': 2000}. Best is trial 18 with value: 0.7264652032908214.

Running time: 1.1 sec
OOF RMSE: 2.16 | R2: 0.67
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:24:21,721] Trial 21 finished with value: 0.7146775677342636 and parameters: {'learning_rate': 0.045400832733459254, 'num_leaves': 60, 'max_depth': 6, 'min_child_samples': 21, 'subsample': 0.832657739655399, 'colsample_bytree': 0.7033234532916531, 'n_estimators': 2000}. Best is trial 18 with value: 0.7264652032908214.

Running time: 0.9 sec
OOF RMSE: 2.02 | R2: 0.71
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 23:24:22,769] Trial 22 finished with value: 0.7100267686962908 and parameters: {'learning_rate': 0.07310342705713785, 'num_leaves': 40, 'max_depth': 6, 'min_child_samples': 17, 'subsample': 0.9019702156172111, 'colsample_bytree': 0.7712988367228838, 'n_estimators': 2000}. Best is trial 18 with value: 0.7264652032908214.

Fold 5
Running time: 1.0 sec
OOF RMSE: 2.04 | R2: 0.71
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:24:23,729] Trial 23 finished with value: 0.7185881460620032 and parameters: {'learning_rate': 0.03304077453757693, 'num_leaves': 60, 'max_depth': 6, 'min_child_samples': 23, 'subsample': 0.7333085969640455, 'colsample_bytree': 0.9090778128219216, 'n_estimators': 2000}. Best is trial 18 with value: 0.7264652032908214.

Running time: 1.0 sec
OOF RMSE: 2.01 | R2: 0.72
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 1.1 sec
OOF RMSE: 1.93 | R2: 0.74

[I 2025-07-11 23:24:24,822] Trial 24 finished with value: 0.7385701173820522 and parameters: {'learning_rate': 0.016704714308945996, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 18, 'subsample': 0.9540897858559988, 'colsample_bytree': 0.8341988181963403, 'n_estimators': 2000}. Best is trial 24 with value: 0.7385701173820522.
[I 2025-07-11 23:24:24,823] A new study created in memory with name: no-name-34030859-a8dd-49b3-b71b-66b66b3886e4

✅ LBM - Mejor R2: 0.74
📋 Parámetros: {'learning_rate': 0.016704714308945996, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 18, 'subsample': 0.9540897858559988, 'colsample_bytree': 0.8341988181963403, 'n_estimators': 2000}

Buscando mejores hiperparámetros para MLP...
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 23:24:25,699] Trial 0 finished with value: 0.568965960589018 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.06869190709760367, 'learning_rate': 'constant', 'learning_rate_init': 0.0050262603499730074}. Best is trial 0 with value: 0.568965960589018.

Fold 5
Running time: 0.9 sec
OOF RMSE: 2.48 | R2: 0.57
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

[I 2025-07-11 23:24:26,864] Trial 1 finished with value: 0.7075546639121062 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.00010981494078919532, 'learning_rate': 'constant', 'learning_rate_init': 0.002020441396281085}. Best is trial 1 with value: 0.7075546639121062.

Running time: 1.2 sec
OOF RMSE: 2.04 | R2: 0.71
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:24:28,241] Trial 2 finished with value: 0.705966188441013 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.059992889696940575, 'learning_rate': 'constant', 'learning_rate_init': 0.0025518156996992545}. Best is trial 1 with value: 0.7075546639121062.

Running time: 1.4 sec
OOF RMSE: 2.05 | R2: 0.71
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 23:24:30,112] Trial 3 finished with value: 0.3964547347017725 and parameters: {'hidden_layer_sizes': '50', 'activation': 'tanh', 'solver': 'adam', 'alpha': 1.6694036751797026e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0004334529951851644}. Best is trial 1 with value: 0.7075546639121062.

Running time: 1.9 sec
OOF RMSE: 2.94 | R2: 0.40
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 23:24:31,883] Trial 4 finished with value: 0.27252005558429726 and parameters: {'hidden_layer_sizes': '50', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.07588014164148238, 'learning_rate': 'constant', 'learning_rate_init': 0.0003011351610027992}. Best is trial 1 with value: 0.7075546639121062.

Running time: 1.8 sec
OOF RMSE: 3.23 | R2: 0.27
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 23:24:32,810] Trial 5 finished with value: 0.36082388660890563 and parameters: {'hidden_layer_sizes': '50', 'activation': 'relu', 'solver': 'adam', 'alpha': 1.6409911965136933e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0009214127265055727}. Best is trial 1 with value: 0.7075546639121062.

Running time: 0.9 sec
OOF RMSE: 3.02 | R2: 0.36
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 23:24:35,598] Trial 6 finished with value: 0.7655604865497806 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0001533321880048486, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0005000583330622141}. Best is trial 6 with value: 0.7655604865497806.

Running time: 2.8 sec
OOF RMSE: 1.83 | R2: 0.77
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 23:24:38,446] Trial 7 finished with value: 0.6126123687396325 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0011462021092980433, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00033577696142886857}. Best is trial 6 with value: 0.7655604865497806.

Running time: 2.8 sec
OOF RMSE: 2.35 | R2: 0.61
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 23:24:41,299] Trial 8 finished with value: 0.5175209216926548 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'relu', 'solver': 'sgd', 'alpha': 4.500107590761819e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.000790934952721981}. Best is trial 6 with value: 0.7655604865497806.

Running time: 2.8 sec
OOF RMSE: 2.63 | R2: 0.52
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 23:24:42,537] Trial 9 finished with value: 0.7613727348164523 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'sgd', 'alpha': 1.5031597270329429e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.009487310458319242}. Best is trial 6 with value: 0.7655604865497806.

Fold 5
Running time: 1.2 sec
OOF RMSE: 1.85 | R2: 0.76
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 23:24:45,050] Trial 10 finished with value: 0.05951721898430151 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.0007951394167494698, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00010161078896335898}. Best is trial 6 with value: 0.7655604865497806.

Running time: 2.5 sec
OOF RMSE: 3.67 | R2: 0.06
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 23:24:46,157] Trial 11 finished with value: 0.7539819079878367 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.00018223713252922034, 'learning_rate': 'constant', 'learning_rate_init': 0.009404249516876574}. Best is trial 6 with value: 0.7655604865497806.

Fold 5
Running time: 1.1 sec
OOF RMSE: 1.88 | R2: 0.75
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 23:24:48,982] Trial 12 finished with value: 0.14474965111542792 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.0005769353669458647, 'learning_rate': 'constant', 'learning_rate_init': 0.0001343309028295501}. Best is trial 6 with value: 0.7655604865497806.

Running time: 2.8 sec
OOF RMSE: 3.50 | R2: 0.14
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 23:24:51,550] Trial 13 finished with value: 0.6759900186003702 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.0033604201675281457, 'learning_rate': 'adaptive', 'learning_rate_init': 0.001827509335867849}. Best is trial 6 with value: 0.7655604865497806.

Running time: 2.6 sec
OOF RMSE: 2.15 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 23:24:52,490] Trial 14 finished with value: 0.7318498982779058 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 8.838850643992824e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.009295867548929354}. Best is trial 6 with value: 0.7655604865497806.

Fold 5
Running time: 0.9 sec
OOF RMSE: 1.96 | R2: 0.73
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 23:24:54,320] Trial 15 finished with value: 0.19156982877097306 and parameters: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'sgd', 'alpha': 3.698876198359287e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0002067914869973913}. Best is trial 6 with value: 0.7655604865497806.

Running time: 1.8 sec
OOF RMSE: 3.40 | R2: 0.19
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 23:24:56,657] Trial 16 finished with value: 0.7733813678260739 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'sgd', 'alpha': 1.0318774925779709e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.004308070174117887}. Best is trial 16 with value: 0.7733813678260739.

Running time: 2.3 sec
OOF RMSE: 1.80 | R2: 0.77
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 23:24:57,810] Trial 17 finished with value: 0.731979077539282 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.00817131724289203, 'learning_rate': 'adaptive', 'learning_rate_init': 0.004034344012107327}. Best is trial 16 with value: 0.7733813678260739.

Fold 5
Running time: 1.1 sec
OOF RMSE: 1.96 | R2: 0.73
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 23:25:00,944] Trial 18 finished with value: 0.6971864996799846 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.00019816717480206552, 'learning_rate': 'constant', 'learning_rate_init': 0.0005890594744058673}. Best is trial 16 with value: 0.7733813678260739.

Running time: 3.1 sec
OOF RMSE: 2.08 | R2: 0.70
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 23:25:02,649] Trial 19 finished with value: 0.42492676902247295 and parameters: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.0003639391102215443, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0014237216730329369}. Best is trial 16 with value: 0.7733813678260739.

Fold 5
Running time: 1.7 sec
OOF RMSE: 2.87 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 23:25:03,587] Trial 20 finished with value: 0.7246392319624668 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.002069720960389373, 'learning_rate': 'constant', 'learning_rate_init': 0.004782501357570574}. Best is trial 16 with value: 0.7733813678260739.

Fold 5
Running time: 0.9 sec
OOF RMSE: 1.98 | R2: 0.72
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:25:05,083] Trial 21 finished with value: 0.7767505384546648 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'sgd', 'alpha': 1.017907367705406e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.006935425000823909}. Best is trial 21 with value: 0.7767505384546648.

Running time: 1.5 sec
OOF RMSE: 1.79 | R2: 0.78
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 23:25:07,342] Trial 22 finished with value: 0.7671208557691914 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'sgd', 'alpha': 1.0166037489950162e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.0035356118577302927}. Best is trial 21 with value: 0.7767505384546648.

Running time: 2.3 sec
OOF RMSE: 1.82 | R2: 0.77
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 23:25:10,188] Trial 23 finished with value: 0.7640445444101889 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'sgd', 'alpha': 1.1061136608088099e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.003183842205190768}. Best is trial 21 with value: 0.7767505384546648.

Running time: 2.8 sec
OOF RMSE: 1.84 | R2: 0.76
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

[I 2025-07-11 23:25:12,023] Trial 24 finished with value: 0.779565864858039 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'sgd', 'alpha': 3.340093429970117e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.005592039248332556}. Best is trial 24 with value: 0.779565864858039.
[I 2025-07-11 23:25:12,024] A new study created in memory with name: no-name-475c709a-4224-4af5-b478-ace6fe28a7fc
[I 2025-07-11 23:25:12,123] Trial 0 finished with value: 0.4043473194006503 and parameters: {'kernel': 'rbf', 'C': 4.268744484323459, 'epsilon': 0.013291526591769923, 'gamma': 'scale'}. Best is trial 0 with value: 0.4043473194006503.
[I 2025-07-11 23:25:12,204] Trial 1 finished with value: -11.222360406357236 and parameters: {'kernel': 'sigmoid', 'C': 6.036901302484564, 'epsilon': 0.08054737711523939, 'gamma': 'auto'}. Best is trial 0 with value: 0.4043473194006503.

Running time: 1.8 sec
OOF RMSE: 1.78 | R2: 0.78

✅ MLP - Mejor R2: 0.78
📋 Parámetros: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'sgd', 'alpha': 3.340093429970117e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.005592039248332556}

Buscando mejores hiperparámetros para SVR...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.92 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 13.22 | R2: -11.22
Fold 1

[I 2025-07-11 23:25:12,286] Trial 2 finished with value: -4.605044909692969 and parameters: {'kernel': 'sigmoid', 'C': 1.7165328526919197, 'epsilon': 0.1007485287493183, 'gamma': 'scale'}. Best is trial 0 with value: 0.4043473194006503.
[I 2025-07-11 23:25:12,370] Trial 3 finished with value: -0.03561102156538354 and parameters: {'kernel': 'sigmoid', 'C': 0.4597197337225007, 'epsilon': 0.14778973536451329, 'gamma': 'auto'}. Best is trial 0 with value: 0.4043473194006503.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 8.95 | R2: -4.61
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.85 | R2: -0.04
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 23:25:12,454] Trial 4 finished with value: 0.12325520213055918 and parameters: {'kernel': 'rbf', 'C': 1.340149936963751, 'epsilon': 0.048218746220588964, 'gamma': 'auto'}. Best is trial 0 with value: 0.4043473194006503.
[I 2025-07-11 23:25:12,532] Trial 5 finished with value: 0.2842017378102043 and parameters: {'kernel': 'rbf', 'C': 2.4282806699395527, 'epsilon': 0.08602661781302208, 'gamma': 'scale'}. Best is trial 0 with value: 0.4043473194006503.
[I 2025-07-11 23:25:12,608] Trial 6 finished with value: 0.03696050274701379 and parameters: {'kernel': 'rbf', 'C': 0.6403683260818049, 'epsilon': 0.045557846208967794, 'gamma': 'auto'}. Best is trial 0 with value: 0.4043473194006503.

Fold 5
Running time: 0.1 sec
OOF RMSE: 3.54 | R2: 0.12
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.20 | R2: 0.28
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.71 | R2: 0.04
Fold 1
Fold 2

[I 2025-07-11 23:25:12,698] Trial 7 finished with value: 0.15899048416934913 and parameters: {'kernel': 'rbf', 'C': 1.1412908949469909, 'epsilon': 0.19783461915681125, 'gamma': 'scale'}. Best is trial 0 with value: 0.4043473194006503.
[I 2025-07-11 23:25:12,786] Trial 8 finished with value: -0.04885522898638173 and parameters: {'kernel': 'sigmoid', 'C': 0.2539146945434558, 'epsilon': 0.10357365643206452, 'gamma': 'scale'}. Best is trial 0 with value: 0.4043473194006503.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.47 | R2: 0.16
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.87 | R2: -0.05
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 23:25:12,874] Trial 9 finished with value: -0.24102255391726857 and parameters: {'kernel': 'sigmoid', 'C': 0.49550904339292984, 'epsilon': 0.1459161786024389, 'gamma': 'scale'}. Best is trial 0 with value: 0.4043473194006503.
[I 2025-07-11 23:25:12,966] Trial 10 finished with value: 0.5428743255445513 and parameters: {'kernel': 'rbf', 'C': 8.991956159583417, 'epsilon': 0.020217895162197706, 'gamma': 'scale'}. Best is trial 10 with value: 0.5428743255445513.

Fold 5
Running time: 0.1 sec
OOF RMSE: 4.21 | R2: -0.24
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.56 | R2: 0.54
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.53 | R2: 0.55

[I 2025-07-11 23:25:13,062] Trial 11 finished with value: 0.5528825337729324 and parameters: {'kernel': 'rbf', 'C': 9.67189186658591, 'epsilon': 0.020530075568415514, 'gamma': 'scale'}. Best is trial 11 with value: 0.5528825337729324.
[I 2025-07-11 23:25:13,156] Trial 12 finished with value: 0.5482155024378459 and parameters: {'kernel': 'rbf', 'C': 9.367001432397302, 'epsilon': 0.011223056302679418, 'gamma': 'scale'}. Best is trial 11 with value: 0.5528825337729324.
[I 2025-07-11 23:25:13,247] Trial 13 finished with value: 0.5590869780991914 and parameters: {'kernel': 'rbf', 'C': 9.940935087802519, 'epsilon': 0.05284376616959884, 'gamma': 'scale'}. Best is trial 13 with value: 0.5590869780991914.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.54 | R2: 0.55
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.51 | R2: 0.56
Fold 1
Fold 2

[I 2025-07-11 23:25:13,337] Trial 14 finished with value: 0.358779852867089 and parameters: {'kernel': 'rbf', 'C': 3.431925710228574, 'epsilon': 0.04685047581911732, 'gamma': 'scale'}. Best is trial 13 with value: 0.5590869780991914.
[I 2025-07-11 23:25:13,419] Trial 15 finished with value: -0.05630008295391242 and parameters: {'kernel': 'rbf', 'C': 0.1423266517505007, 'epsilon': 0.06236951975325482, 'gamma': 'scale'}. Best is trial 13 with value: 0.5590869780991914.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.03 | R2: 0.36
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.89 | R2: -0.06
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 23:25:13,508] Trial 16 finished with value: 0.45456728221843723 and parameters: {'kernel': 'rbf', 'C': 5.102890822651198, 'epsilon': 0.12915940275321505, 'gamma': 'scale'}. Best is trial 13 with value: 0.5590869780991914.
[I 2025-07-11 23:25:13,609] Trial 17 finished with value: 0.3333947703103405 and parameters: {'kernel': 'rbf', 'C': 3.087339199944742, 'epsilon': 0.03453975469385963, 'gamma': 'scale'}. Best is trial 13 with value: 0.5590869780991914.

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.79 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.09 | R2: 0.33
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:25:13,700] Trial 18 finished with value: 0.4079326664435484 and parameters: {'kernel': 'rbf', 'C': 7.004332846249474, 'epsilon': 0.06836077810284313, 'gamma': 'auto'}. Best is trial 13 with value: 0.5590869780991914.
[I 2025-07-11 23:25:13,790] Trial 19 finished with value: 0.2540389852756588 and parameters: {'kernel': 'rbf', 'C': 2.1052354759265968, 'epsilon': 0.03276477229629261, 'gamma': 'scale'}. Best is trial 13 with value: 0.5590869780991914.
[I 2025-07-11 23:25:13,874] Trial 20 finished with value: 0.10406361893005212 and parameters: {'kernel': 'rbf', 'C': 0.8111910175067473, 'epsilon': 0.06458957484223335, 'gamma': 'scale'}. Best is trial 13 with value: 0.5590869780991914.

Running time: 0.1 sec
OOF RMSE: 2.91 | R2: 0.41
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.27 | R2: 0.25
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.58 | R2: 0.10
Fold 1

[I 2025-07-11 23:25:13,971] Trial 21 finished with value: 0.5557081325286932 and parameters: {'kernel': 'rbf', 'C': 9.883428670221367, 'epsilon': 0.015150935580508187, 'gamma': 'scale'}. Best is trial 13 with value: 0.5590869780991914.
[I 2025-07-11 23:25:14,066] Trial 22 finished with value: 0.5464544242115414 and parameters: {'kernel': 'rbf', 'C': 9.156430753989463, 'epsilon': 0.02944529520413109, 'gamma': 'scale'}. Best is trial 13 with value: 0.5590869780991914.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.52 | R2: 0.56
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.55 | R2: 0.55
Fold 1
Fold 2

[I 2025-07-11 23:25:14,157] Trial 23 finished with value: 0.46328539072865815 and parameters: {'kernel': 'rbf', 'C': 5.594107079947136, 'epsilon': 0.028116295271064483, 'gamma': 'scale'}. Best is trial 13 with value: 0.5590869780991914.
[I 2025-07-11 23:25:14,250] Trial 24 finished with value: 0.3764773074394966 and parameters: {'kernel': 'rbf', 'C': 3.716203812721906, 'epsilon': 0.05059523890334029, 'gamma': 'scale'}. Best is trial 13 with value: 0.5590869780991914.
[I 2025-07-11 23:25:14,251] A new study created in memory with name: no-name-75f4aa55-43c4-4b93-a278-e2ba38287f45

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.77 | R2: 0.46
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.99 | R2: 0.38

✅ SVR - Mejor R2: 0.56
📋 Parámetros: {'kernel': 'rbf', 'C': 9.940935087802519, 'epsilon': 0.05284376616959884, 'gamma': 'scale'}

Buscando mejores hiperparámetros para KNN...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:25:14,318] Trial 0 finished with value: 0.6640935428222943 and parameters: {'n_neighbors': 8, 'weights': 'distance', 'leaf_size': 33}. Best is trial 0 with value: 0.6640935428222943.
[I 2025-07-11 23:25:14,392] Trial 1 finished with value: 0.6640935428222943 and parameters: {'n_neighbors': 8, 'weights': 'distance', 'leaf_size': 11}. Best is trial 0 with value: 0.6640935428222943.
[I 2025-07-11 23:25:14,499] Trial 2 finished with value: 0.5313072543381201 and parameters: {'n_neighbors': 15, 'weights': 'distance', 'leaf_size': 40}. Best is trial 0 with value: 0.6640935428222943.

Running time: 0.1 sec
OOF RMSE: 2.19 | R2: 0.66
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.19 | R2: 0.66
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.59 | R2: 0.53
Fold 1
Fold 2

[I 2025-07-11 23:25:14,569] Trial 3 finished with value: 0.7123888470251898 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'leaf_size': 35}. Best is trial 3 with value: 0.7123888470251898.
[I 2025-07-11 23:25:14,644] Trial 4 finished with value: 0.40410406279113564 and parameters: {'n_neighbors': 14, 'weights': 'uniform', 'leaf_size': 19}. Best is trial 3 with value: 0.7123888470251898.
[I 2025-07-11 23:25:14,712] Trial 5 finished with value: 0.570056740868933 and parameters: {'n_neighbors': 7, 'weights': 'uniform', 'leaf_size': 16}. Best is trial 3 with value: 0.7123888470251898.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.03 | R2: 0.71
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.92 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.48 | R2: 0.57
Fold 1
Fold 2

[I 2025-07-11 23:25:14,782] Trial 6 finished with value: 0.40410406279113564 and parameters: {'n_neighbors': 14, 'weights': 'uniform', 'leaf_size': 15}. Best is trial 3 with value: 0.7123888470251898.
[I 2025-07-11 23:25:14,855] Trial 7 finished with value: 0.6314212924746987 and parameters: {'n_neighbors': 9, 'weights': 'distance', 'leaf_size': 40}. Best is trial 3 with value: 0.7123888470251898.
[I 2025-07-11 23:25:14,927] Trial 8 finished with value: 0.6060779960838049 and parameters: {'n_neighbors': 11, 'weights': 'distance', 'leaf_size': 37}. Best is trial 3 with value: 0.7123888470251898.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.92 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.30 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.37 | R2: 0.61
Fold 1
Fold 2

[I 2025-07-11 23:25:14,996] Trial 9 finished with value: 0.6754706006007152 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'leaf_size': 22}. Best is trial 3 with value: 0.7123888470251898.
[I 2025-07-11 23:25:15,075] Trial 10 finished with value: 0.7416048694663218 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'leaf_size': 29}. Best is trial 10 with value: 0.7416048694663218.
[I 2025-07-11 23:25:15,152] Trial 11 finished with value: 0.7416048694663218 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'leaf_size': 29}. Best is trial 10 with value: 0.7416048694663218.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.15 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.92 | R2: 0.74
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.92 | R2: 0.74

[I 2025-07-11 23:25:15,224] Trial 12 finished with value: 0.7416048694663218 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'leaf_size': 28}. Best is trial 10 with value: 0.7416048694663218.
[I 2025-07-11 23:25:15,302] Trial 13 finished with value: 0.7416048694663218 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'leaf_size': 28}. Best is trial 10 with value: 0.7416048694663218.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.92 | R2: 0.74
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.92 | R2: 0.74
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:25:15,381] Trial 14 finished with value: 0.6492159319478257 and parameters: {'n_neighbors': 5, 'weights': 'uniform', 'leaf_size': 30}. Best is trial 10 with value: 0.7416048694663218.
[I 2025-07-11 23:25:15,461] Trial 15 finished with value: 0.6492159319478257 and parameters: {'n_neighbors': 5, 'weights': 'uniform', 'leaf_size': 24}. Best is trial 10 with value: 0.7416048694663218.
[I 2025-07-11 23:25:15,537] Trial 16 finished with value: 0.46831837373669805 and parameters: {'n_neighbors': 11, 'weights': 'uniform', 'leaf_size': 31}. Best is trial 10 with value: 0.7416048694663218.

Running time: 0.1 sec
OOF RMSE: 2.24 | R2: 0.65
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.24 | R2: 0.65
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.76 | R2: 0.47
Fold 1
Fold 2
Fold 3

[I 2025-07-11 23:25:15,607] Trial 17 finished with value: 0.7416048694663218 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'leaf_size': 26}. Best is trial 10 with value: 0.7416048694663218.
[I 2025-07-11 23:25:15,680] Trial 18 finished with value: 0.6492159319478257 and parameters: {'n_neighbors': 5, 'weights': 'uniform', 'leaf_size': 21}. Best is trial 10 with value: 0.7416048694663218.
[I 2025-07-11 23:25:15,757] Trial 19 finished with value: 0.7206448811020261 and parameters: {'n_neighbors': 4, 'weights': 'uniform', 'leaf_size': 33}. Best is trial 10 with value: 0.7416048694663218.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.92 | R2: 0.74
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.24 | R2: 0.65
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.00 | R2: 0.72
Fold 1
Fold 2

[I 2025-07-11 23:25:15,835] Trial 20 finished with value: 0.46831837373669805 and parameters: {'n_neighbors': 11, 'weights': 'uniform', 'leaf_size': 25}. Best is trial 10 with value: 0.7416048694663218.
[I 2025-07-11 23:25:15,911] Trial 21 finished with value: 0.7416048694663218 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'leaf_size': 28}. Best is trial 10 with value: 0.7416048694663218.
[I 2025-07-11 23:25:15,987] Trial 22 finished with value: 0.7206448811020261 and parameters: {'n_neighbors': 4, 'weights': 'uniform', 'leaf_size': 29}. Best is trial 10 with value: 0.7416048694663218.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.76 | R2: 0.47
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.92 | R2: 0.74
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.00 | R2: 0.72

[I 2025-07-11 23:25:16,066] Trial 23 finished with value: 0.6177135449888577 and parameters: {'n_neighbors': 6, 'weights': 'uniform', 'leaf_size': 32}. Best is trial 10 with value: 0.7416048694663218.
[I 2025-07-11 23:25:16,142] Trial 24 finished with value: 0.7206448811020261 and parameters: {'n_neighbors': 4, 'weights': 'uniform', 'leaf_size': 27}. Best is trial 10 with value: 0.7416048694663218.
[I 2025-07-11 23:25:16,143] A new study created in memory with name: no-name-587e95dc-c6a6-4b1e-972c-e16c136d56e2

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.34 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.00 | R2: 0.72

✅ KNN - Mejor R2: 0.74
📋 Parámetros: {'n_neighbors': 3, 'weights': 'uniform', 'leaf_size': 29}

Buscando mejores hiperparámetros para LR...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:25:16,209] Trial 0 finished with value: 0.2496408237673653 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: 0.2496408237673653.
[I 2025-07-11 23:25:16,308] Trial 1 finished with value: 0.3292839286283965 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 1 with value: 0.3292839286283965.

Running time: 0.1 sec
OOF RMSE: 3.28 | R2: 0.25
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.10 | R2: 0.33
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 23:25:16,456] Trial 2 finished with value: 0.3292839286283965 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 1 with value: 0.3292839286283965.
[I 2025-07-11 23:25:16,560] Trial 3 finished with value: 0.2496408237673653 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 1 with value: 0.3292839286283965.

Fold 5
Running time: 0.1 sec
OOF RMSE: 3.10 | R2: 0.33
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.28 | R2: 0.25
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:25:16,627] Trial 4 finished with value: 0.24964082376736307 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.3292839286283965.
[I 2025-07-11 23:25:16,694] Trial 5 finished with value: 0.2496408237673653 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 1 with value: 0.3292839286283965.
[I 2025-07-11 23:25:16,760] Trial 6 finished with value: 0.24964082376736307 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.3292839286283965.

Running time: 0.1 sec
OOF RMSE: 3.28 | R2: 0.25
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.28 | R2: 0.25
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.28 | R2: 0.25
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:25:16,844] Trial 7 finished with value: 0.329283928628361 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 1 with value: 0.3292839286283965.
[I 2025-07-11 23:25:16,924] Trial 8 finished with value: 0.24964082376736307 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.3292839286283965.
[I 2025-07-11 23:25:17,019] Trial 9 finished with value: 0.3292839286283965 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 1 with value: 0.3292839286283965.

Running time: 0.1 sec
OOF RMSE: 3.10 | R2: 0.33
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.28 | R2: 0.25
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.10 | R2: 0.33
Fold 1
Fold 2

[I 2025-07-11 23:25:17,123] Trial 10 finished with value: 0.3292839286283965 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 1 with value: 0.3292839286283965.
[I 2025-07-11 23:25:17,262] Trial 11 finished with value: 0.3292839286283965 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 1 with value: 0.3292839286283965.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.10 | R2: 0.33
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.10 | R2: 0.33

[I 2025-07-11 23:25:17,371] Trial 12 finished with value: 0.3292839286283965 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 1 with value: 0.3292839286283965.
[I 2025-07-11 23:25:17,456] Trial 13 finished with value: 0.3292839286283965 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 1 with value: 0.3292839286283965.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.10 | R2: 0.33
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.10 | R2: 0.33
Fold 1
Fold 2

[I 2025-07-11 23:25:17,545] Trial 14 finished with value: 0.3292839286283965 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 1 with value: 0.3292839286283965.
[I 2025-07-11 23:25:17,641] Trial 15 finished with value: 0.3292839286283965 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 1 with value: 0.3292839286283965.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.10 | R2: 0.33
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.10 | R2: 0.33
Fold 1
Fold 2
Fold 3

[I 2025-07-11 23:25:17,733] Trial 16 finished with value: 0.3292839286283965 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 1 with value: 0.3292839286283965.
[I 2025-07-11 23:25:17,822] Trial 17 finished with value: 0.3292839286283965 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 1 with value: 0.3292839286283965.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.10 | R2: 0.33
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.10 | R2: 0.33
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 23:25:17,927] Trial 18 finished with value: 0.329283928628361 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 1 with value: 0.3292839286283965.
[I 2025-07-11 23:25:18,015] Trial 19 finished with value: 0.3292839286283965 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 1 with value: 0.3292839286283965.
[I 2025-07-11 23:25:18,102] Trial 20 finished with value: 0.3292839286283965 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 1 with value: 0.3292839286283965.

Fold 5
Running time: 0.1 sec
OOF RMSE: 3.10 | R2: 0.33
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.10 | R2: 0.33
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.10 | R2: 0.33

[I 2025-07-11 23:25:18,191] Trial 21 finished with value: 0.3292839286283965 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 1 with value: 0.3292839286283965.
[I 2025-07-11 23:25:18,292] Trial 22 finished with value: 0.3292839286283965 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 1 with value: 0.3292839286283965.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.10 | R2: 0.33
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.10 | R2: 0.33
Fold 1

[I 2025-07-11 23:25:18,456] Trial 23 finished with value: 0.3292839286283965 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 1 with value: 0.3292839286283965.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 3.10 | R2: 0.33
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 23:25:18,557] Trial 24 finished with value: 0.3292839286283965 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 1 with value: 0.3292839286283965.
[I 2025-07-11 23:25:18,559] A new study created in memory with name: no-name-85253e0d-1665-46c5-8ae6-472f9b9c3064

Fold 5
Running time: 0.1 sec
OOF RMSE: 3.10 | R2: 0.33

✅ LR - Mejor R2: 0.33
📋 Parámetros: {'fit_intercept': True, 'positive': False}

Buscando mejores hiperparámetros para RF...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:25:23,859] Trial 0 finished with value: 0.6056164859146194 and parameters: {'n_estimators': 300, 'max_depth': 10, 'min_samples_split': 2, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 0 with value: 0.6056164859146194.

Running time: 5.3 sec
OOF RMSE: 2.37 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:25:40,122] Trial 1 finished with value: 0.6836307564547466 and parameters: {'n_estimators': 500, 'max_depth': 12, 'min_samples_split': 6, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 1 with value: 0.6836307564547466.

Running time: 16.3 sec
OOF RMSE: 2.13 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:25:41,732] Trial 2 finished with value: 0.5540305921347839 and parameters: {'n_estimators': 100, 'max_depth': 8, 'min_samples_split': 9, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 1 with value: 0.6836307564547466.

Running time: 1.6 sec
OOF RMSE: 2.53 | R2: 0.55
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:25:51,322] Trial 3 finished with value: 0.6862629727158877 and parameters: {'n_estimators': 300, 'max_depth': 10, 'min_samples_split': 2, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 3 with value: 0.6862629727158877.

Running time: 9.6 sec
OOF RMSE: 2.12 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:25:58,410] Trial 4 finished with value: 0.6591137428422671 and parameters: {'n_estimators': 300, 'max_depth': 13, 'min_samples_split': 2, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 3 with value: 0.6862629727158877.

Running time: 7.1 sec
OOF RMSE: 2.21 | R2: 0.66
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:26:08,634] Trial 5 finished with value: 0.6602230244520866 and parameters: {'n_estimators': 500, 'max_depth': 15, 'min_samples_split': 5, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 3 with value: 0.6862629727158877.

Running time: 10.2 sec
OOF RMSE: 2.20 | R2: 0.66
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:26:17,452] Trial 6 finished with value: 0.6142014753880638 and parameters: {'n_estimators': 500, 'max_depth': 15, 'min_samples_split': 7, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 3 with value: 0.6862629727158877.

Running time: 8.8 sec
OOF RMSE: 2.35 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:26:22,737] Trial 7 finished with value: 0.6056477503891643 and parameters: {'n_estimators': 300, 'max_depth': 15, 'min_samples_split': 6, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 3 with value: 0.6862629727158877.

Running time: 5.3 sec
OOF RMSE: 2.37 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:26:25,597] Trial 8 finished with value: 0.678464344067665 and parameters: {'n_estimators': 100, 'max_depth': 11, 'min_samples_split': 6, 'min_samples_leaf': 4, 'bootstrap': False}. Best is trial 3 with value: 0.6862629727158877.

Running time: 2.9 sec
OOF RMSE: 2.14 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:26:27,731] Trial 9 finished with value: 0.6636596698351178 and parameters: {'n_estimators': 100, 'max_depth': 6, 'min_samples_split': 5, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 3 with value: 0.6862629727158877.

Running time: 2.1 sec
OOF RMSE: 2.19 | R2: 0.66
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:26:33,393] Trial 10 finished with value: 0.6449196235473094 and parameters: {'n_estimators': 300, 'max_depth': 5, 'min_samples_split': 3, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 3 with value: 0.6862629727158877.

Running time: 5.7 sec
OOF RMSE: 2.25 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:26:48,326] Trial 11 finished with value: 0.670718370694935 and parameters: {'n_estimators': 500, 'max_depth': 11, 'min_samples_split': 10, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 3 with value: 0.6862629727158877.

Running time: 14.9 sec
OOF RMSE: 2.17 | R2: 0.67
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:27:02,776] Trial 12 finished with value: 0.6882863610519904 and parameters: {'n_estimators': 500, 'max_depth': 9, 'min_samples_split': 4, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 12 with value: 0.6882863610519904.

Running time: 14.4 sec
OOF RMSE: 2.11 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:27:10,708] Trial 13 finished with value: 0.6448398343020049 and parameters: {'n_estimators': 300, 'max_depth': 8, 'min_samples_split': 4, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 12 with value: 0.6882863610519904.

Running time: 7.9 sec
OOF RMSE: 2.25 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:27:25,318] Trial 14 finished with value: 0.6847353844225327 and parameters: {'n_estimators': 500, 'max_depth': 9, 'min_samples_split': 3, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 12 with value: 0.6882863610519904.

Running time: 14.6 sec
OOF RMSE: 2.12 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:27:37,325] Trial 15 finished with value: 0.6387568220846325 and parameters: {'n_estimators': 500, 'max_depth': 7, 'min_samples_split': 4, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 12 with value: 0.6882863610519904.

Running time: 12.0 sec
OOF RMSE: 2.27 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:27:45,586] Trial 16 finished with value: 0.6706435275979925 and parameters: {'n_estimators': 300, 'max_depth': 9, 'min_samples_split': 3, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 12 with value: 0.6882863610519904.

Running time: 8.3 sec
OOF RMSE: 2.17 | R2: 0.67
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:27:56,437] Trial 17 finished with value: 0.6851444275529737 and parameters: {'n_estimators': 300, 'max_depth': 13, 'min_samples_split': 2, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 12 with value: 0.6882863610519904.

Running time: 10.8 sec
OOF RMSE: 2.12 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:28:10,498] Trial 18 finished with value: 0.6427239802663731 and parameters: {'n_estimators': 500, 'max_depth': 9, 'min_samples_split': 4, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 12 with value: 0.6882863610519904.

Running time: 14.1 sec
OOF RMSE: 2.26 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:28:13,442] Trial 19 finished with value: 0.6655952269263412 and parameters: {'n_estimators': 100, 'max_depth': 11, 'min_samples_split': 7, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 12 with value: 0.6882863610519904.

Running time: 2.9 sec
OOF RMSE: 2.19 | R2: 0.67
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:28:25,748] Trial 20 finished with value: 0.6798580449480621 and parameters: {'n_estimators': 500, 'max_depth': 7, 'min_samples_split': 3, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 12 with value: 0.6882863610519904.

Running time: 12.3 sec
OOF RMSE: 2.14 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:28:36,560] Trial 21 finished with value: 0.6851444275529737 and parameters: {'n_estimators': 300, 'max_depth': 13, 'min_samples_split': 2, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 12 with value: 0.6882863610519904.

Running time: 10.8 sec
OOF RMSE: 2.12 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:28:47,383] Trial 22 finished with value: 0.6851444275529737 and parameters: {'n_estimators': 300, 'max_depth': 13, 'min_samples_split': 2, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 12 with value: 0.6882863610519904.

Running time: 10.8 sec
OOF RMSE: 2.12 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:28:56,369] Trial 23 finished with value: 0.6470450031414395 and parameters: {'n_estimators': 300, 'max_depth': 10, 'min_samples_split': 4, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 12 with value: 0.6882863610519904.

Running time: 9.0 sec
OOF RMSE: 2.25 | R2: 0.65
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:29:06,562] Trial 24 finished with value: 0.6874929590504069 and parameters: {'n_estimators': 300, 'max_depth': 12, 'min_samples_split': 3, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 12 with value: 0.6882863610519904.
[I 2025-07-11 23:29:06,564] A new study created in memory with name: no-name-e4aa3fff-5f57-42d7-91aa-4d089c702050

Running time: 10.2 sec
OOF RMSE: 2.11 | R2: 0.69

✅ RF - Mejor R2: 0.69
📋 Parámetros: {'n_estimators': 500, 'max_depth': 9, 'min_samples_split': 4, 'min_samples_leaf': 1, 'bootstrap': False}

Buscando mejores hiperparámetros para CAT...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:29:12,056] Trial 0 finished with value: 0.7469030113113364 and parameters: {'iterations': 2000, 'learning_rate': 0.07954490945199243, 'depth': 4, 'l2_leaf_reg': 4.415043637799566}. Best is trial 0 with value: 0.7469030113113364.

Running time: 5.5 sec
OOF RMSE: 1.90 | R2: 0.75
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:29:13,602] Trial 1 finished with value: 0.7332191675024784 and parameters: {'iterations': 500, 'learning_rate': 0.0812652400324751, 'depth': 4, 'l2_leaf_reg': 1.628811689661997}. Best is trial 0 with value: 0.7469030113113364.

Running time: 1.5 sec
OOF RMSE: 1.95 | R2: 0.73
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:29:19,636] Trial 2 finished with value: 0.7449763820408146 and parameters: {'iterations': 2000, 'learning_rate': 0.06951369917797294, 'depth': 4, 'l2_leaf_reg': 6.757872194090419}. Best is trial 0 with value: 0.7469030113113364.

Running time: 6.0 sec
OOF RMSE: 1.91 | R2: 0.74
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:31:44,031] Trial 3 finished with value: 0.7850202389789146 and parameters: {'iterations': 1000, 'learning_rate': 0.04445864581501598, 'depth': 10, 'l2_leaf_reg': 7.208208790668715}. Best is trial 3 with value: 0.7850202389789146.

Running time: 144.4 sec
OOF RMSE: 1.75 | R2: 0.79
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:32:10,147] Trial 4 finished with value: 0.7848280748031726 and parameters: {'iterations': 2000, 'learning_rate': 0.03761436907526069, 'depth': 7, 'l2_leaf_reg': 2.0651376108800847}. Best is trial 3 with value: 0.7850202389789146.

Running time: 26.1 sec
OOF RMSE: 1.75 | R2: 0.78
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:32:13,551] Trial 5 finished with value: 0.7719245639020051 and parameters: {'iterations': 500, 'learning_rate': 0.030108102996432552, 'depth': 6, 'l2_leaf_reg': 5.7640385330741575}. Best is trial 3 with value: 0.7850202389789146.

Running time: 3.4 sec
OOF RMSE: 1.81 | R2: 0.77
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:34:56,159] Trial 6 finished with value: 0.7756054161221997 and parameters: {'iterations': 2000, 'learning_rate': 0.023389152271859667, 'depth': 9, 'l2_leaf_reg': 5.373960451132162}. Best is trial 3 with value: 0.7850202389789146.

Running time: 162.6 sec
OOF RMSE: 1.79 | R2: 0.78
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:37:38,111] Trial 7 finished with value: 0.7812010223509784 and parameters: {'iterations': 2000, 'learning_rate': 0.03579115662423977, 'depth': 9, 'l2_leaf_reg': 8.759085890547592}. Best is trial 3 with value: 0.7850202389789146.

Running time: 161.9 sec
OOF RMSE: 1.77 | R2: 0.78
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:37:43,754] Trial 8 finished with value: 0.7584748226799585 and parameters: {'iterations': 2000, 'learning_rate': 0.04569400300430306, 'depth': 4, 'l2_leaf_reg': 4.412065890736626}. Best is trial 3 with value: 0.7850202389789146.

Running time: 5.6 sec
OOF RMSE: 1.86 | R2: 0.76
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:37:56,810] Trial 9 finished with value: 0.7728533356468863 and parameters: {'iterations': 2000, 'learning_rate': 0.029228989530458556, 'depth': 6, 'l2_leaf_reg': 7.0102088567501095}. Best is trial 3 with value: 0.7850202389789146.

Running time: 13.0 sec
OOF RMSE: 1.80 | R2: 0.77
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:40:17,975] Trial 10 finished with value: 0.7492811769041556 and parameters: {'iterations': 1000, 'learning_rate': 0.010541352362865903, 'depth': 10, 'l2_leaf_reg': 8.680543268062994}. Best is trial 3 with value: 0.7850202389789146.
[I 2025-07-11 23:40:17,976] A new study created in memory with name: no-name-2100268c-ab2d-42f9-9cb1-a61dea351f58
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.886e+02, tolerance: 3.043e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.470e+02, tolerance: 2.664e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.871e+02, tolerance: 2.195e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.378e+02, tolerance: 2.302e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.205e+02, tolerance: 2.844e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 23:40:18,094] Trial 0 finished with value: -0.03978047551956809 and parameters: {'alpha': 0.0057186992600626345, 'l1_ratio': 0.3651405807398955}. Best is trial 0 with value: -0.03978047551956809.

Running time: 141.2 sec
OOF RMSE: 1.89 | R2: 0.75

✅ CAT - Mejor R2: 0.79
📋 Parámetros: {'iterations': 1000, 'learning_rate': 0.04445864581501598, 'depth': 10, 'l2_leaf_reg': 7.208208790668715}

Buscando mejores hiperparámetros para EN...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.86 | R2: -0.04
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.076e+02, tolerance: 3.043e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.304e+02, tolerance: 2.664e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.459e+02, tolerance: 2.195e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.068e+02, tolerance: 2.302e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.435e+02, tolerance: 2.844e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 23:40:18,230] Trial 1 finished with value: -0.032437158337566885 and parameters: {'alpha': 0.0011191378358933112, 'l1_ratio': 0.8725992433926896}. Best is trial 1 with value: -0.032437158337566885.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.315e+02, tolerance: 3.043e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.234e+02, tolerance: 2.664e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.704e+02, tolerance: 2.195e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.562e+02, tolerance: 2.302e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.140e+02, tolerance: 2.844e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 23:40:18,372] Trial 2 finished with value: -0.08025768549479229 and parameters: {'alpha': 0.00010484367608728353, 'l1_ratio': 0.6524121107172896}. Best is trial 1 with value: -0.032437158337566885.

Fold 5
Running time: 0.1 sec
OOF RMSE: 3.84 | R2: -0.03
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.93 | R2: -0.08
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.970e+02, tolerance: 3.043e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.542e+02, tolerance: 2.664e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.115e+02, tolerance: 2.195e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.089e+02, tolerance: 2.302e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.608e+02, tolerance: 2.844e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 23:40:18,515] Trial 3 finished with value: -0.03729235536686759 and parameters: {'alpha': 0.00036260194120415297, 'l1_ratio': 0.059052950908354274}. Best is trial 1 with value: -0.032437158337566885.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.127e+02, tolerance: 3.043e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.131e+02, tolerance: 2.664e-01
  model = cd_fast.enet_coordinate_descent(

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.85 | R2: -0.04
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.610e+02, tolerance: 2.195e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.480e+02, tolerance: 2.302e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.034e+02, tolerance: 2.844e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 23:40:18,698] Trial 4 finished with value: -0.06834580728351392 and parameters: {'alpha': 0.0001842052563282266, 'l1_ratio': 0.8751537377541659}. Best is trial 1 with value: -0.032437158337566885.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.287e+02, tolerance: 3.043e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.610e+02, tolerance: 2.664e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.321e+02, tolerance: 2.195e-01
  model = cd_fast.enet_coordinate_descent(

Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 3.91 | R2: -0.07
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.338e+02, tolerance: 2.302e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.824e+02, tolerance: 2.844e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 23:40:18,855] Trial 5 finished with value: -0.0065914331855640995 and parameters: {'alpha': 0.0008168758830108395, 'l1_ratio': 0.04499080026596425}. Best is trial 5 with value: -0.0065914331855640995.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.792e+02, tolerance: 3.043e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.937e+02, tolerance: 2.664e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.452e+02, tolerance: 2.195e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.380e+02, tolerance: 2.302e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.847e+02, tolerance: 2.844e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 23:40:18,999] Trial 6 finished with value: -0.036789800618163726 and parameters: {'alpha': 0.00039446313672463, 'l1_ratio': 0.8828922972644674}. Best is trial 5 with value: -0.0065914331855640995.

Fold 5
Running time: 0.1 sec
OOF RMSE: 3.79 | R2: -0.01
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.85 | R2: -0.04
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.402e+02, tolerance: 3.043e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.048e+02, tolerance: 2.664e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.734e+02, tolerance: 2.195e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.999e+02, tolerance: 2.302e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.921e+02, tolerance: 2.844e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 23:40:19,134] Trial 7 finished with value: -0.03263084077701439 and parameters: {'alpha': 0.0018344933440975256, 'l1_ratio': 0.6584405775038707}. Best is trial 5 with value: -0.0065914331855640995.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.483e+02, tolerance: 3.043e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.103e+02, tolerance: 2.664e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.768e+02, tolerance: 2.195e-01
  model = cd_fast.enet_coordinate_descent(

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.84 | R2: -0.03
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.601e+02, tolerance: 2.302e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.122e+02, tolerance: 2.844e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 23:40:19,271] Trial 8 finished with value: -0.029404676498315574 and parameters: {'alpha': 0.0004613427166205479, 'l1_ratio': 0.4649969128855205}. Best is trial 5 with value: -0.0065914331855640995.
[I 2025-07-11 23:40:19,357] Trial 9 finished with value: -0.0003636740809507266 and parameters: {'alpha': 2.6359543413208626, 'l1_ratio': 0.8582437114548029}. Best is trial 9 with value: -0.0003636740809507266.

Fold 5
Running time: 0.1 sec
OOF RMSE: 3.84 | R2: -0.03
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.78 | R2: -0.00
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 23:40:19,472] Trial 10 finished with value: -0.0003636740809507266 and parameters: {'alpha': 5.300445927649451, 'l1_ratio': 0.9996745107550551}. Best is trial 9 with value: -0.0003636740809507266.
[I 2025-07-11 23:40:19,581] Trial 11 finished with value: -0.0003636740809507266 and parameters: {'alpha': 4.745569263219318, 'l1_ratio': 0.9736940074902429}. Best is trial 9 with value: -0.0003636740809507266.

Fold 5
Running time: 0.1 sec
OOF RMSE: 3.78 | R2: -0.00
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.78 | R2: -0.00
Fold 1
Fold 2

[I 2025-07-11 23:40:19,711] Trial 12 finished with value: -0.0003636740809507266 and parameters: {'alpha': 5.070847935874419, 'l1_ratio': 0.6579080856673566}. Best is trial 9 with value: -0.0003636740809507266.
[I 2025-07-11 23:40:19,809] Trial 13 finished with value: 0.06551978137646852 and parameters: {'alpha': 0.47038981802484525, 'l1_ratio': 0.7927063424294172}. Best is trial 13 with value: 0.06551978137646852.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.78 | R2: -0.00
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.66 | R2: 0.07
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 23:40:19,909] Trial 14 finished with value: 0.1297471389954622 and parameters: {'alpha': 0.35430620547128056, 'l1_ratio': 0.7021767516495698}. Best is trial 14 with value: 0.1297471389954622.
[I 2025-07-11 23:40:20,016] Trial 15 finished with value: 0.1605508430986936 and parameters: {'alpha': 0.2923354286573993, 'l1_ratio': 0.7165574102740639}. Best is trial 15 with value: 0.1605508430986936.

Fold 5
Running time: 0.1 sec
OOF RMSE: 3.53 | R2: 0.13
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.46 | R2: 0.16
Fold 1
Fold 2
Fold 3

[I 2025-07-11 23:40:20,139] Trial 16 finished with value: 0.1692646587389095 and parameters: {'alpha': 0.10946086382169078, 'l1_ratio': 0.33455845710979193}. Best is trial 16 with value: 0.1692646587389095.
[I 2025-07-11 23:40:20,285] Trial 17 finished with value: 0.10035285145502826 and parameters: {'alpha': 0.04648387890029702, 'l1_ratio': 0.2696135007408206}. Best is trial 16 with value: 0.1692646587389095.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.45 | R2: 0.17
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.59 | R2: 0.10

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.099e-01, tolerance: 2.664e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 23:40:20,445] Trial 18 finished with value: 0.11077841256288679 and parameters: {'alpha': 0.05466121203302232, 'l1_ratio': 0.2084538211217266}. Best is trial 16 with value: 0.1692646587389095.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 3.57 | R2: 0.11
Fold 1
Fold 2
Fold 3

[I 2025-07-11 23:40:20,564] Trial 19 finished with value: 0.13580480753889423 and parameters: {'alpha': 0.44925591281329635, 'l1_ratio': 0.5041132319597514}. Best is trial 16 with value: 0.1692646587389095.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.52 | R2: 0.14
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.242e-01, tolerance: 3.043e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.445e+01, tolerance: 2.664e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 23:40:20,788] Trial 20 finished with value: -0.0018472428993090428 and parameters: {'alpha': 0.014605905707452823, 'l1_ratio': 0.5065169807684553}. Best is trial 16 with value: 0.1692646587389095.

Fold 5
Running time: 0.2 sec
OOF RMSE: 3.78 | R2: -0.00
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:40:20,954] Trial 21 finished with value: 0.20787659221893262 and parameters: {'alpha': 0.22102630864884604, 'l1_ratio': 0.5112113488406747}. Best is trial 21 with value: 0.20787659221893262.
[I 2025-07-11 23:40:21,134] Trial 22 finished with value: 0.18359836237199978 and parameters: {'alpha': 0.12332099029735223, 'l1_ratio': 0.396253135479301}. Best is trial 21 with value: 0.20787659221893262.

Running time: 0.2 sec
OOF RMSE: 3.37 | R2: 0.21
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 3.42 | R2: 0.18
Fold 1

[I 2025-07-11 23:40:21,267] Trial 23 finished with value: 0.1847353344336855 and parameters: {'alpha': 0.13312171099051312, 'l1_ratio': 0.36576180286198245}. Best is trial 21 with value: 0.20787659221893262.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.41 | R2: 0.18
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:40:21,382] Trial 24 finished with value: 0.020928964834107555 and parameters: {'alpha': 1.2620264217023571, 'l1_ratio': 0.4274224162258471}. Best is trial 21 with value: 0.20787659221893262.
[I 2025-07-11 23:40:21,383] A new study created in memory with name: no-name-2e76aea7-80b8-41e5-b4b7-c0b2ab4a4e1c

Running time: 0.1 sec
OOF RMSE: 3.74 | R2: 0.02

✅ EN - Mejor R2: 0.21
📋 Parámetros: {'alpha': 0.22102630864884604, 'l1_ratio': 0.5112113488406747}

🔍 Optimizando en C2RCC_rhown_3x3_depth_lt_1...
Buscando mejores hiperparámetros para XGB...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:40:28,261] Trial 0 finished with value: 0.6915545856833762 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01814158159076387, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.9279808157556414, 'colsample_bytree': 0.7171336024033921}. Best is trial 0 with value: 0.6915545856833762.

Running time: 6.9 sec
OOF RMSE: 1.93 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:40:31,028] Trial 1 finished with value: 0.681779865277018 and parameters: {'n_estimators': 500, 'learning_rate': 0.05388155883051022, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.6943002251798331, 'colsample_bytree': 0.6589809594735979}. Best is trial 0 with value: 0.6915545856833762.

Running time: 2.8 sec
OOF RMSE: 1.96 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:40:35,239] Trial 2 finished with value: 0.6910262984186533 and parameters: {'n_estimators': 500, 'learning_rate': 0.011982235765700424, 'max_depth': 8, 'min_child_weight': 2, 'subsample': 0.8598442301664131, 'colsample_bytree': 0.7944714658777421}. Best is trial 0 with value: 0.6915545856833762.

Running time: 4.2 sec
OOF RMSE: 1.93 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:40:38,840] Trial 3 finished with value: 0.6918369708556559 and parameters: {'n_estimators': 500, 'learning_rate': 0.00527066447024588, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.991473251824871, 'colsample_bytree': 0.7607123617337899}. Best is trial 3 with value: 0.6918369708556559.

Running time: 3.6 sec
OOF RMSE: 1.92 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:40:48,142] Trial 4 finished with value: 0.6734969014043076 and parameters: {'n_estimators': 1000, 'learning_rate': 0.03126971861702894, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.7859144315963303, 'colsample_bytree': 0.9511396098184386}. Best is trial 3 with value: 0.6918369708556559.

Running time: 9.3 sec
OOF RMSE: 1.98 | R2: 0.67
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:40:50,753] Trial 5 finished with value: 0.69175384509817 and parameters: {'n_estimators': 500, 'learning_rate': 0.0711991698664601, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.7478777748641383, 'colsample_bytree': 0.668430433784506}. Best is trial 3 with value: 0.6918369708556559.

Running time: 2.6 sec
OOF RMSE: 1.92 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:40:56,646] Trial 6 finished with value: 0.6811571901077855 and parameters: {'n_estimators': 2000, 'learning_rate': 0.09463501246804057, 'max_depth': 5, 'min_child_weight': 1, 'subsample': 0.6854997575114739, 'colsample_bytree': 0.8245474244808698}. Best is trial 3 with value: 0.6918369708556559.

Running time: 5.9 sec
OOF RMSE: 1.96 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:40:59,925] Trial 7 finished with value: 0.6745088493302516 and parameters: {'n_estimators': 500, 'learning_rate': 0.03403662889575966, 'max_depth': 8, 'min_child_weight': 3, 'subsample': 0.7671685236842434, 'colsample_bytree': 0.8043784854338684}. Best is trial 3 with value: 0.6918369708556559.

Running time: 3.3 sec
OOF RMSE: 1.98 | R2: 0.67
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:41:03,446] Trial 8 finished with value: 0.710708914561961 and parameters: {'n_estimators': 500, 'learning_rate': 0.009002363118067453, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.7766040470867547, 'colsample_bytree': 0.702903793330149}. Best is trial 8 with value: 0.710708914561961.

Running time: 3.5 sec
OOF RMSE: 1.86 | R2: 0.71
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:41:21,993] Trial 9 finished with value: 0.6856069584053188 and parameters: {'n_estimators': 2000, 'learning_rate': 0.01410229997184396, 'max_depth': 8, 'min_child_weight': 1, 'subsample': 0.7844495497897402, 'colsample_bytree': 0.9974538212544928}. Best is trial 8 with value: 0.710708914561961.

Running time: 18.5 sec
OOF RMSE: 1.94 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:41:27,922] Trial 10 finished with value: 0.6794554476075332 and parameters: {'n_estimators': 1000, 'learning_rate': 0.0071698835120576985, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.6014005795693937, 'colsample_bytree': 0.8796845209627687}. Best is trial 8 with value: 0.710708914561961.

Running time: 5.9 sec
OOF RMSE: 1.96 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:41:31,001] Trial 11 finished with value: 0.6890363560272861 and parameters: {'n_estimators': 500, 'learning_rate': 0.0058261515161279875, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.9659766831488966, 'colsample_bytree': 0.603939717938028}. Best is trial 8 with value: 0.710708914561961.

Running time: 3.1 sec
OOF RMSE: 1.93 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:41:34,047] Trial 12 finished with value: 0.6827929572103254 and parameters: {'n_estimators': 500, 'learning_rate': 0.009251565353876574, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.8715458344401874, 'colsample_bytree': 0.7390742452945289}. Best is trial 8 with value: 0.710708914561961.

Running time: 3.0 sec
OOF RMSE: 1.95 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:41:37,478] Trial 13 finished with value: 0.6995553902965355 and parameters: {'n_estimators': 500, 'learning_rate': 0.005584388609777809, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.8581797304892629, 'colsample_bytree': 0.7416235081629613}. Best is trial 8 with value: 0.710708914561961.

Running time: 3.4 sec
OOF RMSE: 1.90 | R2: 0.70
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:41:40,210] Trial 14 finished with value: 0.6925615604029264 and parameters: {'n_estimators': 500, 'learning_rate': 0.009280801063794822, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.8600516604991554, 'colsample_bytree': 0.6755479558733628}. Best is trial 8 with value: 0.710708914561961.

Running time: 2.7 sec
OOF RMSE: 1.92 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:41:51,359] Trial 15 finished with value: 0.674311281511395 and parameters: {'n_estimators': 2000, 'learning_rate': 0.008272348689076534, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.9044524929234036, 'colsample_bytree': 0.6168024331082548}. Best is trial 8 with value: 0.710708914561961.

Running time: 11.1 sec
OOF RMSE: 1.98 | R2: 0.67
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:41:54,830] Trial 16 finished with value: 0.7065909778495951 and parameters: {'n_estimators': 500, 'learning_rate': 0.005029497342860596, 'max_depth': 6, 'min_child_weight': 1, 'subsample': 0.8206939401937408, 'colsample_bytree': 0.8655228315784931}. Best is trial 8 with value: 0.710708914561961.

Running time: 3.5 sec
OOF RMSE: 1.88 | R2: 0.71
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:41:57,977] Trial 17 finished with value: 0.703113978402758 and parameters: {'n_estimators': 500, 'learning_rate': 0.013715746330038456, 'max_depth': 6, 'min_child_weight': 1, 'subsample': 0.7199264711946929, 'colsample_bytree': 0.8853672280683326}. Best is trial 8 with value: 0.710708914561961.

Running time: 3.1 sec
OOF RMSE: 1.89 | R2: 0.70
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:42:10,711] Trial 18 finished with value: 0.6878998290296882 and parameters: {'n_estimators': 2000, 'learning_rate': 0.020276583333246306, 'max_depth': 6, 'min_child_weight': 1, 'subsample': 0.8164793654877635, 'colsample_bytree': 0.8702162428808177}. Best is trial 8 with value: 0.710708914561961.

Running time: 12.7 sec
OOF RMSE: 1.94 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:42:18,362] Trial 19 finished with value: 0.6722362830229796 and parameters: {'n_estimators': 1000, 'learning_rate': 0.011454056641301308, 'max_depth': 6, 'min_child_weight': 1, 'subsample': 0.6336153951930819, 'colsample_bytree': 0.9209653351003115}. Best is trial 8 with value: 0.710708914561961.

Running time: 7.6 sec
OOF RMSE: 1.98 | R2: 0.67
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:42:21,148] Trial 20 finished with value: 0.7081018311237199 and parameters: {'n_estimators': 500, 'learning_rate': 0.006839978861573742, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.8254246129902707, 'colsample_bytree': 0.8351977651658907}. Best is trial 8 with value: 0.710708914561961.

Running time: 2.8 sec
OOF RMSE: 1.87 | R2: 0.71
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:42:23,951] Trial 21 finished with value: 0.7079035911929412 and parameters: {'n_estimators': 500, 'learning_rate': 0.006921351634063842, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.7964568430364392, 'colsample_bytree': 0.8488662496580189}. Best is trial 8 with value: 0.710708914561961.

Running time: 2.8 sec
OOF RMSE: 1.87 | R2: 0.71
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:42:26,524] Trial 22 finished with value: 0.7079931162844548 and parameters: {'n_estimators': 500, 'learning_rate': 0.00715038712639646, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.7431715493680303, 'colsample_bytree': 0.8196616439025883}. Best is trial 8 with value: 0.710708914561961.

Running time: 2.6 sec
OOF RMSE: 1.87 | R2: 0.71
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:42:29,131] Trial 23 finished with value: 0.7054470660955053 and parameters: {'n_estimators': 500, 'learning_rate': 0.007586624708697236, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.7295960457446677, 'colsample_bytree': 0.7745302561322212}. Best is trial 8 with value: 0.710708914561961.

Running time: 2.6 sec
OOF RMSE: 1.88 | R2: 0.71
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:42:31,723] Trial 24 finished with value: 0.696528670692111 and parameters: {'n_estimators': 500, 'learning_rate': 0.01022445284676943, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.6829920200996429, 'colsample_bytree': 0.7087881123405683}. Best is trial 8 with value: 0.710708914561961.
[I 2025-07-11 23:42:31,724] A new study created in memory with name: no-name-74ae91dc-9137-4ab6-8cdc-64ffd941db56

Running time: 2.6 sec
OOF RMSE: 1.91 | R2: 0.70

✅ XGB - Mejor R2: 0.71
📋 Parámetros: {'n_estimators': 500, 'learning_rate': 0.009002363118067453, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.7766040470867547, 'colsample_bytree': 0.702903793330149}

Buscando mejores hiperparámetros para LBM...
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 23:42:32,319] Trial 0 finished with value: 0.6620006665301708 and parameters: {'learning_rate': 0.012346694987851558, 'num_leaves': 60, 'max_depth': 6, 'min_child_samples': 6, 'subsample': 0.7141892394528124, 'colsample_bytree': 0.6607358730716422, 'n_estimators': 1000}. Best is trial 0 with value: 0.6620006665301708.

Fold 5
Running time: 0.6 sec
OOF RMSE: 2.02 | R2: 0.66
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:42:33,332] Trial 1 finished with value: 0.47110423645244515 and parameters: {'learning_rate': 0.030920428691939977, 'num_leaves': 40, 'max_depth': 6, 'min_child_samples': 16, 'subsample': 0.8981572483909188, 'colsample_bytree': 0.9691933495072458, 'n_estimators': 2000}. Best is trial 0 with value: 0.6620006665301708.

Running time: 1.0 sec
OOF RMSE: 2.52 | R2: 0.47
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 23:42:34,340] Trial 2 finished with value: 0.5251906075732201 and parameters: {'learning_rate': 0.020839704392940753, 'num_leaves': 20, 'max_depth': 8, 'min_child_samples': 22, 'subsample': 0.8728146146926065, 'colsample_bytree': 0.8887890370945741, 'n_estimators': 2000}. Best is trial 0 with value: 0.6620006665301708.

Fold 5
Running time: 1.0 sec
OOF RMSE: 2.39 | R2: 0.53
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:42:35,288] Trial 3 finished with value: 0.5768018713575738 and parameters: {'learning_rate': 0.006271186350465383, 'num_leaves': 40, 'max_depth': 5, 'min_child_samples': 9, 'subsample': 0.6142360836531717, 'colsample_bytree': 0.9515008981418978, 'n_estimators': 2000}. Best is trial 0 with value: 0.6620006665301708.

Running time: 0.9 sec
OOF RMSE: 2.26 | R2: 0.58
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 23:42:35,851] Trial 4 finished with value: 0.5560544435492558 and parameters: {'learning_rate': 0.07681331171920557, 'num_leaves': 40, 'max_depth': 6, 'min_child_samples': 10, 'subsample': 0.9063120180289554, 'colsample_bytree': 0.6686662676908298, 'n_estimators': 1000}. Best is trial 0 with value: 0.6620006665301708.

Fold 5
Running time: 0.6 sec
OOF RMSE: 2.31 | R2: 0.56
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:42:36,554] Trial 5 finished with value: 0.4678375060561504 and parameters: {'learning_rate': 0.07081903707382571, 'num_leaves': 80, 'max_depth': 8, 'min_child_samples': 11, 'subsample': 0.7912602412979161, 'colsample_bytree': 0.9607217732760116, 'n_estimators': 1000}. Best is trial 0 with value: 0.6620006665301708.

Running time: 0.7 sec
OOF RMSE: 2.53 | R2: 0.47
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 23:42:37,582] Trial 6 finished with value: 0.6100174924476793 and parameters: {'learning_rate': 0.006991981150760576, 'num_leaves': 80, 'max_depth': 5, 'min_child_samples': 5, 'subsample': 0.62095638896335, 'colsample_bytree': 0.9639895892852652, 'n_estimators': 2000}. Best is trial 0 with value: 0.6620006665301708.

Fold 5
Running time: 1.0 sec
OOF RMSE: 2.16 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 23:42:38,086] Trial 7 finished with value: 0.5389603172343924 and parameters: {'learning_rate': 0.015135808487710112, 'num_leaves': 60, 'max_depth': 5, 'min_child_samples': 17, 'subsample': 0.7086991692639232, 'colsample_bytree': 0.8774668695892147, 'n_estimators': 1000}. Best is trial 0 with value: 0.6620006665301708.

Fold 5
Running time: 0.5 sec
OOF RMSE: 2.35 | R2: 0.54
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:42:38,441] Trial 8 finished with value: 0.5304403296085355 and parameters: {'learning_rate': 0.07240927000539829, 'num_leaves': 20, 'max_depth': 8, 'min_child_samples': 18, 'subsample': 0.9505648841422951, 'colsample_bytree': 0.9676273723330664, 'n_estimators': 500}. Best is trial 0 with value: 0.6620006665301708.

Running time: 0.3 sec
OOF RMSE: 2.38 | R2: 0.53
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.9 sec
OOF RMSE: 2.47 | R2: 0.49

[I 2025-07-11 23:42:39,389] Trial 9 finished with value: 0.49111932575579054 and parameters: {'learning_rate': 0.020778579751800242, 'num_leaves': 60, 'max_depth': 5, 'min_child_samples': 16, 'subsample': 0.9131365185996801, 'colsample_bytree': 0.8834967491823176, 'n_estimators': 2000}. Best is trial 0 with value: 0.6620006665301708.

Fold 1
Fold 2
Fold 3

[I 2025-07-11 23:42:39,799] Trial 10 finished with value: 0.6378859015558491 and parameters: {'learning_rate': 0.010202202689183612, 'num_leaves': 60, 'max_depth': 7, 'min_child_samples': 5, 'subsample': 0.7347308386369057, 'colsample_bytree': 0.6016152151448553, 'n_estimators': 500}. Best is trial 0 with value: 0.6620006665301708.

Fold 4
Fold 5
Running time: 0.4 sec
OOF RMSE: 2.09 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 23:42:40,232] Trial 11 finished with value: 0.6409307874855613 and parameters: {'learning_rate': 0.01067017902625482, 'num_leaves': 60, 'max_depth': 7, 'min_child_samples': 5, 'subsample': 0.7337924686717537, 'colsample_bytree': 0.6062921885700949, 'n_estimators': 500}. Best is trial 0 with value: 0.6620006665301708.

Fold 5
Running time: 0.4 sec
OOF RMSE: 2.08 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.4 sec
OOF RMSE: 2.09 | R2: 0.64

[I 2025-07-11 23:42:40,592] Trial 12 finished with value: 0.6357627967137157 and parameters: {'learning_rate': 0.011344473575549916, 'num_leaves': 60, 'max_depth': 7, 'min_child_samples': 8, 'subsample': 0.7030225049999738, 'colsample_bytree': 0.7253184245060794, 'n_estimators': 500}. Best is trial 0 with value: 0.6620006665301708.

Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 23:42:40,890] Trial 13 finished with value: 0.5678037065863054 and parameters: {'learning_rate': 0.036026662062425746, 'num_leaves': 60, 'max_depth': 7, 'min_child_samples': 12, 'subsample': 0.7846800048755425, 'colsample_bytree': 0.603072800708416, 'n_estimators': 500}. Best is trial 0 with value: 0.6620006665301708.

Fold 5
Running time: 0.3 sec
OOF RMSE: 2.28 | R2: 0.57
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 23:42:41,511] Trial 14 finished with value: 0.6462764630229352 and parameters: {'learning_rate': 0.009548747770965059, 'num_leaves': 60, 'max_depth': 6, 'min_child_samples': 7, 'subsample': 0.6703900644246032, 'colsample_bytree': 0.7255691827794009, 'n_estimators': 1000}. Best is trial 0 with value: 0.6620006665301708.

Fold 5
Running time: 0.6 sec
OOF RMSE: 2.06 | R2: 0.65
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 23:42:41,990] Trial 15 finished with value: 0.536294799285713 and parameters: {'learning_rate': 0.005424093087168771, 'num_leaves': 60, 'max_depth': 6, 'min_child_samples': 24, 'subsample': 0.6622128781822966, 'colsample_bytree': 0.7573221035354978, 'n_estimators': 1000}. Best is trial 0 with value: 0.6620006665301708.

Fold 5
Running time: 0.5 sec
OOF RMSE: 2.36 | R2: 0.54
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:42:42,570] Trial 16 finished with value: 0.6491319042291124 and parameters: {'learning_rate': 0.008248786921711106, 'num_leaves': 60, 'max_depth': 6, 'min_child_samples': 7, 'subsample': 0.8305796470372844, 'colsample_bytree': 0.68423144472138, 'n_estimators': 1000}. Best is trial 0 with value: 0.6620006665301708.

Running time: 0.6 sec
OOF RMSE: 2.05 | R2: 0.65
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:42:43,104] Trial 17 finished with value: 0.5658670675242197 and parameters: {'learning_rate': 0.015179414758167125, 'num_leaves': 80, 'max_depth': 6, 'min_child_samples': 13, 'subsample': 0.8397858174511383, 'colsample_bytree': 0.6666293154365497, 'n_estimators': 1000}. Best is trial 0 with value: 0.6620006665301708.

Running time: 0.5 sec
OOF RMSE: 2.28 | R2: 0.57
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 23:42:43,653] Trial 18 finished with value: 0.568630680798405 and parameters: {'learning_rate': 0.007909729669563164, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 14, 'subsample': 0.9949614339674988, 'colsample_bytree': 0.7954993488225435, 'n_estimators': 1000}. Best is trial 0 with value: 0.6620006665301708.

Fold 5
Running time: 0.5 sec
OOF RMSE: 2.28 | R2: 0.57
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:42:44,278] Trial 19 finished with value: 0.6475174033801472 and parameters: {'learning_rate': 0.015422035772094974, 'num_leaves': 60, 'max_depth': 7, 'min_child_samples': 7, 'subsample': 0.8163535440999462, 'colsample_bytree': 0.6611890983540982, 'n_estimators': 1000}. Best is trial 0 with value: 0.6620006665301708.

Running time: 0.6 sec
OOF RMSE: 2.06 | R2: 0.65
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:42:44,793] Trial 20 finished with value: 0.5376640460363543 and parameters: {'learning_rate': 0.031603225530999715, 'num_leaves': 60, 'max_depth': 5, 'min_child_samples': 20, 'subsample': 0.8431299967530042, 'colsample_bytree': 0.716017201347793, 'n_estimators': 1000}. Best is trial 0 with value: 0.6620006665301708.

Running time: 0.5 sec
OOF RMSE: 2.36 | R2: 0.54
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 23:42:45,433] Trial 21 finished with value: 0.6459122627700316 and parameters: {'learning_rate': 0.014931776081327862, 'num_leaves': 60, 'max_depth': 7, 'min_child_samples': 7, 'subsample': 0.7652845804741334, 'colsample_bytree': 0.6610015986400078, 'n_estimators': 1000}. Best is trial 0 with value: 0.6620006665301708.

Fold 5
Running time: 0.6 sec
OOF RMSE: 2.06 | R2: 0.65
Fold 1
Fold 2
Fold 3

[I 2025-07-11 23:42:45,999] Trial 22 finished with value: 0.6466869393687624 and parameters: {'learning_rate': 0.014199481297807836, 'num_leaves': 60, 'max_depth': 6, 'min_child_samples': 7, 'subsample': 0.8240117072715554, 'colsample_bytree': 0.6437445056692794, 'n_estimators': 1000}. Best is trial 0 with value: 0.6620006665301708.

Fold 4
Fold 5
Running time: 0.6 sec
OOF RMSE: 2.06 | R2: 0.65
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 23:42:46,613] Trial 23 finished with value: 0.6037402151018312 and parameters: {'learning_rate': 0.008125507818863254, 'num_leaves': 60, 'max_depth': 7, 'min_child_samples': 9, 'subsample': 0.7666864533929303, 'colsample_bytree': 0.6882856537815839, 'n_estimators': 1000}. Best is trial 0 with value: 0.6620006665301708.

Fold 5
Running time: 0.6 sec
OOF RMSE: 2.18 | R2: 0.60
Fold 1
Fold 2
Fold 3

[I 2025-07-11 23:42:47,137] Trial 24 finished with value: 0.5209686579297403 and parameters: {'learning_rate': 0.024494816246276693, 'num_leaves': 60, 'max_depth': 6, 'min_child_samples': 11, 'subsample': 0.8149645611364691, 'colsample_bytree': 0.7857476008040413, 'n_estimators': 1000}. Best is trial 0 with value: 0.6620006665301708.
[I 2025-07-11 23:42:47,138] A new study created in memory with name: no-name-392f9289-09b5-458d-8140-f42ea5e6aa8c

Fold 4
Fold 5
Running time: 0.5 sec
OOF RMSE: 2.40 | R2: 0.52

✅ LBM - Mejor R2: 0.66
📋 Parámetros: {'learning_rate': 0.012346694987851558, 'num_leaves': 60, 'max_depth': 6, 'min_child_samples': 6, 'subsample': 0.7141892394528124, 'colsample_bytree': 0.6607358730716422, 'n_estimators': 1000}

Buscando mejores hiperparámetros para MLP...
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 23:42:48,120] Trial 0 finished with value: 0.5901985478620676 and parameters: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.04512891264408918, 'learning_rate': 'adaptive', 'learning_rate_init': 0.004590003646734352}. Best is trial 0 with value: 0.5901985478620676.

Fold 5
Running time: 1.0 sec
OOF RMSE: 2.22 | R2: 0.59
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 23:42:49,723] Trial 1 finished with value: 0.7331601196447333 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.08135814102667267, 'learning_rate': 'constant', 'learning_rate_init': 0.009468011158114064}. Best is trial 1 with value: 0.7331601196447333.

Fold 5
Running time: 1.6 sec
OOF RMSE: 1.79 | R2: 0.73
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 23:42:52,459] Trial 2 finished with value: 0.6248679612195593 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.002102697399773829, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0009832999917864125}. Best is trial 1 with value: 0.7331601196447333.

Running time: 2.7 sec
OOF RMSE: 2.12 | R2: 0.62
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

[I 2025-07-11 23:42:54,660] Trial 3 finished with value: 0.429611520215624 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'sgd', 'alpha': 1.7742776111765245e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00017354441124555882}. Best is trial 1 with value: 0.7331601196447333.

Running time: 2.2 sec
OOF RMSE: 2.62 | R2: 0.43
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 23:42:56,318] Trial 4 finished with value: 0.7031399371835134 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 2.9896365027189414e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0026699717349986185}. Best is trial 1 with value: 0.7331601196447333.

Fold 5
Running time: 1.7 sec
OOF RMSE: 1.89 | R2: 0.70
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 23:42:57,496] Trial 5 finished with value: 0.5970499478930928 and parameters: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.03048792756328684, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0044098310228232185}. Best is trial 1 with value: 0.7331601196447333.

Fold 5
Running time: 1.2 sec
OOF RMSE: 2.20 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 23:42:58,922] Trial 6 finished with value: 0.6208718239783515 and parameters: {'hidden_layer_sizes': '100', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.013632229493312617, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0053449880702833305}. Best is trial 1 with value: 0.7331601196447333.

Fold 5
Running time: 1.4 sec
OOF RMSE: 2.13 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 23:43:00,124] Trial 7 finished with value: 0.6167281501537891 and parameters: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'adam', 'alpha': 3.508157478955295e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.004844090483707724}. Best is trial 1 with value: 0.7331601196447333.

Fold 5
Running time: 1.2 sec
OOF RMSE: 2.15 | R2: 0.62
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 23:43:03,250] Trial 8 finished with value: 0.4733574705044601 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.0037012568565186537, 'learning_rate': 'constant', 'learning_rate_init': 0.0004984568133091254}. Best is trial 1 with value: 0.7331601196447333.

Fold 5
Running time: 3.1 sec
OOF RMSE: 2.52 | R2: 0.47
Fold 1
Fold 2
Fold 3

[I 2025-07-11 23:43:04,535] Trial 9 finished with value: 0.5553591170668487 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 4.164873450581158e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.005122826707474876}. Best is trial 1 with value: 0.7331601196447333.

Fold 4
Fold 5
Running time: 1.3 sec
OOF RMSE: 2.31 | R2: 0.56
Fold 1
Fold 2
Fold 3

[I 2025-07-11 23:43:05,346] Trial 10 finished with value: 0.5287313528404722 and parameters: {'hidden_layer_sizes': '50', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.00040353035426924093, 'learning_rate': 'constant', 'learning_rate_init': 0.009703389905424875}. Best is trial 1 with value: 0.7331601196447333.

Fold 4
Fold 5
Running time: 0.8 sec
OOF RMSE: 2.38 | R2: 0.53
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 23:43:06,645] Trial 11 finished with value: 0.7354740890964313 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.000345810166601407, 'learning_rate': 'constant', 'learning_rate_init': 0.001667148163859619}. Best is trial 11 with value: 0.7354740890964313.

Fold 5
Running time: 1.3 sec
OOF RMSE: 1.78 | R2: 0.74
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 23:43:08,911] Trial 12 finished with value: 0.6552928123531568 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.00023205776133613124, 'learning_rate': 'constant', 'learning_rate_init': 0.0014519507808363557}. Best is trial 11 with value: 0.7354740890964313.

Running time: 2.3 sec
OOF RMSE: 2.04 | R2: 0.66
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

[I 2025-07-11 23:43:10,864] Trial 13 finished with value: 0.5471887182070646 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.00022079902005052283, 'learning_rate': 'constant', 'learning_rate_init': 0.0003586189477849526}. Best is trial 11 with value: 0.7354740890964313.

Running time: 1.9 sec
OOF RMSE: 2.33 | R2: 0.55
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 23:43:11,671] Trial 14 finished with value: 0.44455756534445223 and parameters: {'hidden_layer_sizes': '50', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0868543942929179, 'learning_rate': 'constant', 'learning_rate_init': 0.0017573567332607146}. Best is trial 11 with value: 0.7354740890964313.

Fold 4
Fold 5
Running time: 0.8 sec
OOF RMSE: 2.58 | R2: 0.44
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 23:43:13,045] Trial 15 finished with value: 0.42119567994295803 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.006390926946439442, 'learning_rate': 'constant', 'learning_rate_init': 0.00010132806633428964}. Best is trial 11 with value: 0.7354740890964313.

Fold 5
Running time: 1.4 sec
OOF RMSE: 2.64 | R2: 0.42
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 23:43:15,237] Trial 16 finished with value: 0.7056699860208268 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0006840378667986401, 'learning_rate': 'constant', 'learning_rate_init': 0.0007735470058036271}. Best is trial 11 with value: 0.7354740890964313.

Fold 5
Running time: 2.2 sec
OOF RMSE: 1.88 | R2: 0.71
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 23:43:16,600] Trial 17 finished with value: 0.7330993368816161 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'sgd', 'alpha': 8.988165822571713e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.009997342942147918}. Best is trial 11 with value: 0.7354740890964313.

Fold 5
Running time: 1.4 sec
OOF RMSE: 1.79 | R2: 0.73
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 23:43:18,577] Trial 18 finished with value: 0.5406538909030587 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.001620641846379866, 'learning_rate': 'constant', 'learning_rate_init': 0.002354363299763017}. Best is trial 11 with value: 0.7354740890964313.

Fold 4
Fold 5
Running time: 2.0 sec
OOF RMSE: 2.35 | R2: 0.54
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 23:43:19,720] Trial 19 finished with value: 0.3807125531973231 and parameters: {'hidden_layer_sizes': '50', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0102011082684369, 'learning_rate': 'constant', 'learning_rate_init': 0.0003114749345755985}. Best is trial 11 with value: 0.7354740890964313.

Fold 4
Fold 5
Running time: 1.1 sec
OOF RMSE: 2.73 | R2: 0.38
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 23:43:20,979] Trial 20 finished with value: 0.7265879853975721 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.00010457317594771343, 'learning_rate': 'constant', 'learning_rate_init': 0.0028574463275455432}. Best is trial 11 with value: 0.7354740890964313.

Fold 5
Running time: 1.3 sec
OOF RMSE: 1.81 | R2: 0.73
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 23:43:22,517] Trial 21 finished with value: 0.7332635842470658 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.00011880507473691103, 'learning_rate': 'constant', 'learning_rate_init': 0.009538539200501975}. Best is trial 11 with value: 0.7354740890964313.

Fold 5
Running time: 1.5 sec
OOF RMSE: 1.79 | R2: 0.73
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 23:43:24,135] Trial 22 finished with value: 0.7223688826067604 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.0008692430692539131, 'learning_rate': 'constant', 'learning_rate_init': 0.00812854076662955}. Best is trial 11 with value: 0.7354740890964313.

Fold 5
Running time: 1.6 sec
OOF RMSE: 1.83 | R2: 0.72
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 23:43:25,609] Trial 23 finished with value: 0.7360651265186435 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'sgd', 'alpha': 9.734029787097429e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.007861948681722394}. Best is trial 23 with value: 0.7360651265186435.

Fold 5
Running time: 1.5 sec
OOF RMSE: 1.78 | R2: 0.74
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-11 23:43:27,600] Trial 24 finished with value: 0.7281362448294466 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.00011660327094343854, 'learning_rate': 'constant', 'learning_rate_init': 0.006657308949731417}. Best is trial 23 with value: 0.7360651265186435.
[I 2025-07-11 23:43:27,602] A new study created in memory with name: no-name-3be3e589-7eeb-436a-b862-de029384effc

Fold 5
Running time: 2.0 sec
OOF RMSE: 1.81 | R2: 0.73

✅ MLP - Mejor R2: 0.74
📋 Parámetros: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'sgd', 'alpha': 9.734029787097429e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.007861948681722394}

Buscando mejores hiperparámetros para SVR...
Fold 1
Fold 2
Fold 3

[I 2025-07-11 23:43:27,688] Trial 0 finished with value: -62.67928467133898 and parameters: {'kernel': 'sigmoid', 'C': 5.062017851546756, 'epsilon': 0.19250870709839485, 'gamma': 'auto'}. Best is trial 0 with value: -62.67928467133898.
[I 2025-07-11 23:43:27,755] Trial 1 finished with value: 0.11490699219632006 and parameters: {'kernel': 'rbf', 'C': 0.16902182968846258, 'epsilon': 0.18869166420619327, 'gamma': 'scale'}. Best is trial 1 with value: 0.11490699219632006.
[I 2025-07-11 23:43:27,830] Trial 2 finished with value: -4.0755432453211204 and parameters: {'kernel': 'sigmoid', 'C': 1.2574320024937844, 'epsilon': 0.07033222513713555, 'gamma': 'auto'}. Best is trial 1 with value: 0.11490699219632006.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 27.66 | R2: -62.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.26 | R2: 0.11
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 7.81 | R2: -4.08
Fold 1
Fold 2
Fold 3

[I 2025-07-11 23:43:27,897] Trial 3 finished with value: 0.15040095803400755 and parameters: {'kernel': 'rbf', 'C': 0.29394455360769245, 'epsilon': 0.15120008907021198, 'gamma': 'auto'}. Best is trial 3 with value: 0.15040095803400755.
[I 2025-07-11 23:43:27,969] Trial 4 finished with value: 0.24339820337448037 and parameters: {'kernel': 'rbf', 'C': 0.9233027293095717, 'epsilon': 0.10006476795192511, 'gamma': 'auto'}. Best is trial 4 with value: 0.24339820337448037.
[I 2025-07-11 23:43:28,044] Trial 5 finished with value: 0.35381148631127257 and parameters: {'kernel': 'rbf', 'C': 2.434625174224877, 'epsilon': 0.04696193697204508, 'gamma': 'scale'}. Best is trial 5 with value: 0.35381148631127257.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.20 | R2: 0.15
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.02 | R2: 0.24
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.79 | R2: 0.35
Fold 1
Fold 2

[I 2025-07-11 23:43:28,116] Trial 6 finished with value: 0.28509325334723257 and parameters: {'kernel': 'rbf', 'C': 1.2868317204614605, 'epsilon': 0.18469216025070093, 'gamma': 'scale'}. Best is trial 5 with value: 0.35381148631127257.
[I 2025-07-11 23:43:28,210] Trial 7 finished with value: -1.5825655544274841 and parameters: {'kernel': 'sigmoid', 'C': 0.7930083534524173, 'epsilon': 0.05067761526404458, 'gamma': 'auto'}. Best is trial 5 with value: 0.35381148631127257.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.93 | R2: 0.29
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 5.57 | R2: -1.58
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:43:28,283] Trial 8 finished with value: 0.011081756519322972 and parameters: {'kernel': 'sigmoid', 'C': 0.21569601639084168, 'epsilon': 0.10267997148709586, 'gamma': 'auto'}. Best is trial 5 with value: 0.35381148631127257.
[I 2025-07-11 23:43:28,366] Trial 9 finished with value: -2.738207786040584 and parameters: {'kernel': 'sigmoid', 'C': 1.0301515138242754, 'epsilon': 0.03569877163574171, 'gamma': 'auto'}. Best is trial 5 with value: 0.35381148631127257.
[I 2025-07-11 23:43:28,450] Trial 10 finished with value: 0.486475871674966 and parameters: {'kernel': 'rbf', 'C': 5.347187793698207, 'epsilon': 0.013169827168918652, 'gamma': 'scale'}. Best is trial 10 with value: 0.486475871674966.

Running time: 0.1 sec
OOF RMSE: 3.45 | R2: 0.01
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 6.70 | R2: -2.74
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.48 | R2: 0.49
Fold 1
Fold 2

[I 2025-07-11 23:43:28,536] Trial 11 finished with value: 0.5425797955707831 and parameters: {'kernel': 'rbf', 'C': 7.708995979791996, 'epsilon': 0.018764510549798167, 'gamma': 'scale'}. Best is trial 11 with value: 0.5425797955707831.
[I 2025-07-11 23:43:28,629] Trial 12 finished with value: 0.5769745313483734 and parameters: {'kernel': 'rbf', 'C': 9.891876048983287, 'epsilon': 0.01400338302967484, 'gamma': 'scale'}. Best is trial 12 with value: 0.5769745313483734.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.34 | R2: 0.54
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.25 | R2: 0.58
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 23:43:28,722] Trial 13 finished with value: 0.5724648419088841 and parameters: {'kernel': 'rbf', 'C': 9.509294301583122, 'epsilon': 0.010174078979628588, 'gamma': 'scale'}. Best is trial 12 with value: 0.5769745313483734.
[I 2025-07-11 23:43:28,805] Trial 14 finished with value: 0.5726377700654866 and parameters: {'kernel': 'rbf', 'C': 9.459265346154744, 'epsilon': 0.06705616900444233, 'gamma': 'scale'}. Best is trial 12 with value: 0.5769745313483734.
[I 2025-07-11 23:43:28,886] Trial 15 finished with value: 0.3881934121902797 and parameters: {'kernel': 'rbf', 'C': 3.0880354449295666, 'epsilon': 0.07635478751479172, 'gamma': 'scale'}. Best is trial 12 with value: 0.5769745313483734.

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.27 | R2: 0.57
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.27 | R2: 0.57
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.71 | R2: 0.39
Fold 1

[I 2025-07-11 23:43:28,961] Trial 16 finished with value: 0.38449241656309807 and parameters: {'kernel': 'rbf', 'C': 2.967460435193723, 'epsilon': 0.13797344116442933, 'gamma': 'scale'}. Best is trial 12 with value: 0.5769745313483734.
[I 2025-07-11 23:43:29,049] Trial 17 finished with value: 0.48251514338844936 and parameters: {'kernel': 'rbf', 'C': 5.280038320295404, 'epsilon': 0.07554613758197196, 'gamma': 'scale'}. Best is trial 12 with value: 0.5769745313483734.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.72 | R2: 0.38
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.49 | R2: 0.48
Fold 1
Fold 2
Fold 3

[I 2025-07-11 23:43:29,140] Trial 18 finished with value: 0.0784530272096603 and parameters: {'kernel': 'rbf', 'C': 0.10139986306394899, 'epsilon': 0.13576983136809295, 'gamma': 'scale'}. Best is trial 12 with value: 0.5769745313483734.
[I 2025-07-11 23:43:29,231] Trial 19 finished with value: 0.5745968083077737 and parameters: {'kernel': 'rbf', 'C': 9.66456549889072, 'epsilon': 0.03932882204868646, 'gamma': 'scale'}. Best is trial 12 with value: 0.5769745313483734.
[I 2025-07-11 23:43:29,310] Trial 20 finished with value: 0.19117743475448712 and parameters: {'kernel': 'rbf', 'C': 0.4699368513543891, 'epsilon': 0.034608434037170815, 'gamma': 'scale'}. Best is trial 12 with value: 0.5769745313483734.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.33 | R2: 0.08
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.26 | R2: 0.57
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.12 | R2: 0.19

[I 2025-07-11 23:43:29,399] Trial 21 finished with value: 0.5739442719155542 and parameters: {'kernel': 'rbf', 'C': 9.575986465890628, 'epsilon': 0.0576729672637935, 'gamma': 'scale'}. Best is trial 12 with value: 0.5769745313483734.
[I 2025-07-11 23:43:29,484] Trial 22 finished with value: 0.5098370927028095 and parameters: {'kernel': 'rbf', 'C': 6.242412114867911, 'epsilon': 0.03225689465012686, 'gamma': 'scale'}. Best is trial 12 with value: 0.5769745313483734.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.26 | R2: 0.57
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.43 | R2: 0.51
Fold 1
Fold 2

[I 2025-07-11 23:43:29,569] Trial 23 finished with value: 0.4238769138763474 and parameters: {'kernel': 'rbf', 'C': 3.7611761189180135, 'epsilon': 0.04643116519614735, 'gamma': 'scale'}. Best is trial 12 with value: 0.5769745313483734.
[I 2025-07-11 23:43:29,653] Trial 24 finished with value: 0.3206934313551333 and parameters: {'kernel': 'rbf', 'C': 1.8372549223202053, 'epsilon': 0.06092669683074013, 'gamma': 'scale'}. Best is trial 12 with value: 0.5769745313483734.
[I 2025-07-11 23:43:29,655] A new study created in memory with name: no-name-3381ee57-9cb3-463d-b2e9-35a44d1d291d
[I 2025-07-11 23:43:29,718] Trial 0 finished with value: 0.5320818314524178 and parameters: {'n_neighbors': 14, 'weights': 'uniform', 'leaf_size': 36}. Best is trial 0 with value: 0.5320818314524178.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.63 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.86 | R2: 0.32

✅ SVR - Mejor R2: 0.58
📋 Parámetros: {'kernel': 'rbf', 'C': 9.891876048983287, 'epsilon': 0.01400338302967484, 'gamma': 'scale'}

Buscando mejores hiperparámetros para KNN...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.37 | R2: 0.53
Fold 1

[I 2025-07-11 23:43:29,780] Trial 1 finished with value: 0.650043881788956 and parameters: {'n_neighbors': 9, 'weights': 'distance', 'leaf_size': 12}. Best is trial 1 with value: 0.650043881788956.
[I 2025-07-11 23:43:29,841] Trial 2 finished with value: 0.5493401605466779 and parameters: {'n_neighbors': 10, 'weights': 'uniform', 'leaf_size': 35}. Best is trial 1 with value: 0.650043881788956.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.05 | R2: 0.65
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.33 | R2: 0.55
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.85 | R2: 0.71

[I 2025-07-11 23:43:29,937] Trial 3 finished with value: 0.7146532659872163 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'leaf_size': 17}. Best is trial 3 with value: 0.7146532659872163.
[I 2025-07-11 23:43:30,002] Trial 4 finished with value: 0.685308622425659 and parameters: {'n_neighbors': 4, 'weights': 'uniform', 'leaf_size': 35}. Best is trial 3 with value: 0.7146532659872163.
[I 2025-07-11 23:43:30,073] Trial 5 finished with value: 0.650043881788956 and parameters: {'n_neighbors': 9, 'weights': 'distance', 'leaf_size': 20}. Best is trial 3 with value: 0.7146532659872163.
[I 2025-07-11 23:43:30,139] Trial 6 finished with value: 0.6697697572539011 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'leaf_size': 13}. Best is trial 3 with value: 0.7146532659872163.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.94 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.05 | R2: 0.65
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.99 | R2: 0.67
Fold 1

[I 2025-07-11 23:43:30,203] Trial 7 finished with value: 0.752584636286909 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'leaf_size': 25}. Best is trial 7 with value: 0.752584636286909.
[I 2025-07-11 23:43:30,268] Trial 8 finished with value: 0.7354814172293856 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'leaf_size': 19}. Best is trial 7 with value: 0.752584636286909.
[I 2025-07-11 23:43:30,332] Trial 9 finished with value: 0.6601540293208579 and parameters: {'n_neighbors': 8, 'weights': 'distance', 'leaf_size': 40}. Best is trial 7 with value: 0.752584636286909.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.72 | R2: 0.75
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.78 | R2: 0.74
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.02 | R2: 0.66
Fold 1

[I 2025-07-11 23:43:30,407] Trial 10 finished with value: 0.5440371497460825 and parameters: {'n_neighbors': 13, 'weights': 'uniform', 'leaf_size': 27}. Best is trial 7 with value: 0.752584636286909.
[I 2025-07-11 23:43:30,479] Trial 11 finished with value: 0.752584636286909 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'leaf_size': 26}. Best is trial 7 with value: 0.752584636286909.
[I 2025-07-11 23:43:30,551] Trial 12 finished with value: 0.752584636286909 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'leaf_size': 26}. Best is trial 7 with value: 0.752584636286909.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.34 | R2: 0.54
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.72 | R2: 0.75
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.72 | R2: 0.75

[I 2025-07-11 23:43:30,624] Trial 13 finished with value: 0.6464616969884462 and parameters: {'n_neighbors': 6, 'weights': 'uniform', 'leaf_size': 28}. Best is trial 7 with value: 0.752584636286909.
[I 2025-07-11 23:43:30,696] Trial 14 finished with value: 0.752584636286909 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'leaf_size': 23}. Best is trial 7 with value: 0.752584636286909.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.06 | R2: 0.65
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.72 | R2: 0.75
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:43:30,773] Trial 15 finished with value: 0.5598661809497549 and parameters: {'n_neighbors': 11, 'weights': 'uniform', 'leaf_size': 31}. Best is trial 7 with value: 0.752584636286909.
[I 2025-07-11 23:43:30,852] Trial 16 finished with value: 0.6464616969884462 and parameters: {'n_neighbors': 6, 'weights': 'uniform', 'leaf_size': 22}. Best is trial 7 with value: 0.752584636286909.
[I 2025-07-11 23:43:30,924] Trial 17 finished with value: 0.6498799261406728 and parameters: {'n_neighbors': 5, 'weights': 'uniform', 'leaf_size': 29}. Best is trial 7 with value: 0.752584636286909.

Running time: 0.1 sec
OOF RMSE: 2.30 | R2: 0.56
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.06 | R2: 0.65
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.05 | R2: 0.65
Fold 1
Fold 2
Fold 3

[I 2025-07-11 23:43:30,999] Trial 18 finished with value: 0.554114188629052 and parameters: {'n_neighbors': 12, 'weights': 'uniform', 'leaf_size': 16}. Best is trial 7 with value: 0.752584636286909.
[I 2025-07-11 23:43:31,073] Trial 19 finished with value: 0.752584636286909 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'leaf_size': 31}. Best is trial 7 with value: 0.752584636286909.
[I 2025-07-11 23:43:31,146] Trial 20 finished with value: 0.5294204409549118 and parameters: {'n_neighbors': 15, 'weights': 'uniform', 'leaf_size': 23}. Best is trial 7 with value: 0.752584636286909.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.31 | R2: 0.55
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.72 | R2: 0.75
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.38 | R2: 0.53
Fold 1
Fold 2

[I 2025-07-11 23:43:31,220] Trial 21 finished with value: 0.752584636286909 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'leaf_size': 26}. Best is trial 7 with value: 0.752584636286909.
[I 2025-07-11 23:43:31,295] Trial 22 finished with value: 0.6498799261406728 and parameters: {'n_neighbors': 5, 'weights': 'uniform', 'leaf_size': 25}. Best is trial 7 with value: 0.752584636286909.
[I 2025-07-11 23:43:31,370] Trial 23 finished with value: 0.685308622425659 and parameters: {'n_neighbors': 4, 'weights': 'uniform', 'leaf_size': 31}. Best is trial 7 with value: 0.752584636286909.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.72 | R2: 0.75
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.05 | R2: 0.65
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 1.94 | R2: 0.69
Fold 1

[I 2025-07-11 23:43:31,446] Trial 24 finished with value: 0.5947415920605266 and parameters: {'n_neighbors': 7, 'weights': 'uniform', 'leaf_size': 22}. Best is trial 7 with value: 0.752584636286909.
[I 2025-07-11 23:43:31,447] A new study created in memory with name: no-name-2c833bef-6a32-459c-b9b5-a792cb12b7ec
[I 2025-07-11 23:43:31,508] Trial 0 finished with value: 0.35941139868459604 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 0 with value: 0.35941139868459604.
[I 2025-07-11 23:43:31,570] Trial 1 finished with value: 0.35791043300747294 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: 0.35941139868459604.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.21 | R2: 0.59

✅ KNN - Mejor R2: 0.75
📋 Parámetros: {'n_neighbors': 3, 'weights': 'uniform', 'leaf_size': 25}

Buscando mejores hiperparámetros para LR...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.77 | R2: 0.36
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.78 | R2: 0.36
Fold 1
Fold 2
Fold 3

[I 2025-07-11 23:43:31,634] Trial 2 finished with value: 0.35941139868459604 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 0 with value: 0.35941139868459604.
[I 2025-07-11 23:43:31,720] Trial 3 finished with value: 0.10929896606607714 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 0 with value: 0.35941139868459604.
[I 2025-07-11 23:43:31,793] Trial 4 finished with value: 0.35941139868459604 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 0 with value: 0.35941139868459604.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.77 | R2: 0.36
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.27 | R2: 0.11
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.77 | R2: 0.36
Fold 1
Fold 2

[I 2025-07-11 23:43:31,858] Trial 5 finished with value: 0.35941139868459604 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 0 with value: 0.35941139868459604.
[I 2025-07-11 23:43:31,984] Trial 6 finished with value: 0.10929896606607714 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 0 with value: 0.35941139868459604.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.77 | R2: 0.36
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.27 | R2: 0.11
Fold 1
Fold 2
Fold 3

[I 2025-07-11 23:43:32,073] Trial 7 finished with value: 0.10929896606607714 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 0 with value: 0.35941139868459604.
[I 2025-07-11 23:43:32,177] Trial 8 finished with value: 0.10929896606607714 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 0 with value: 0.35941139868459604.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.27 | R2: 0.11
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.27 | R2: 0.11
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:43:32,255] Trial 9 finished with value: 0.35941139868459604 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 0 with value: 0.35941139868459604.
[I 2025-07-11 23:43:32,315] Trial 10 finished with value: 0.35941139868459604 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 0 with value: 0.35941139868459604.
[I 2025-07-11 23:43:32,378] Trial 11 finished with value: 0.35941139868459604 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 0 with value: 0.35941139868459604.
[I 2025-07-11 23:43:32,440] Trial 12 finished with value: 0.35941139868459604 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 0 with value: 0.35941139868459604.

Running time: 0.1 sec
OOF RMSE: 2.77 | R2: 0.36
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.77 | R2: 0.36
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.77 | R2: 0.36
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.77 | R2: 0.36
Fold 1

[I 2025-07-11 23:43:32,504] Trial 13 finished with value: 0.35941139868459604 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 0 with value: 0.35941139868459604.
[I 2025-07-11 23:43:32,565] Trial 14 finished with value: 0.35941139868459604 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 0 with value: 0.35941139868459604.
[I 2025-07-11 23:43:32,626] Trial 15 finished with value: 0.35941139868459604 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 0 with value: 0.35941139868459604.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.77 | R2: 0.36
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.77 | R2: 0.36
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.77 | R2: 0.36
Fold 1
Fold 2
Fold 3

[I 2025-07-11 23:43:32,688] Trial 16 finished with value: 0.35941139868459604 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 0 with value: 0.35941139868459604.
[I 2025-07-11 23:43:32,751] Trial 17 finished with value: 0.35941139868459604 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 0 with value: 0.35941139868459604.
[I 2025-07-11 23:43:32,834] Trial 18 finished with value: 0.109298966053197 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 0 with value: 0.35941139868459604.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.77 | R2: 0.36
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.77 | R2: 0.36
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.27 | R2: 0.11
Fold 1
Fold 2
Fold 3

[I 2025-07-11 23:43:32,914] Trial 19 finished with value: 0.35941139868459604 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 0 with value: 0.35941139868459604.
[I 2025-07-11 23:43:33,007] Trial 20 finished with value: 0.35941139868459604 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 0 with value: 0.35941139868459604.
[I 2025-07-11 23:43:33,072] Trial 21 finished with value: 0.35941139868459604 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 0 with value: 0.35941139868459604.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.77 | R2: 0.36
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.77 | R2: 0.36
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.77 | R2: 0.36
Fold 1

[I 2025-07-11 23:43:33,143] Trial 22 finished with value: 0.35941139868459604 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 0 with value: 0.35941139868459604.
[I 2025-07-11 23:43:33,207] Trial 23 finished with value: 0.35941139868459604 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 0 with value: 0.35941139868459604.
[I 2025-07-11 23:43:33,268] Trial 24 finished with value: 0.35941139868459604 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 0 with value: 0.35941139868459604.
[I 2025-07-11 23:43:33,269] A new study created in memory with name: no-name-7189da45-a1fa-419c-8f70-67ba46e5e9d7

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.77 | R2: 0.36
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.77 | R2: 0.36
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.77 | R2: 0.36

✅ LR - Mejor R2: 0.36
📋 Parámetros: {'fit_intercept': False, 'positive': True}

Buscando mejores hiperparámetros para RF...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:43:37,380] Trial 0 finished with value: 0.6162512005607842 and parameters: {'n_estimators': 300, 'max_depth': 6, 'min_samples_split': 10, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 0 with value: 0.6162512005607842.

Running time: 4.1 sec
OOF RMSE: 2.15 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:43:47,364] Trial 1 finished with value: 0.5496494261072165 and parameters: {'n_estimators': 500, 'max_depth': 6, 'min_samples_split': 3, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 0 with value: 0.6162512005607842.

Running time: 10.0 sec
OOF RMSE: 2.33 | R2: 0.55
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:43:58,665] Trial 2 finished with value: 0.6329289680000295 and parameters: {'n_estimators': 500, 'max_depth': 14, 'min_samples_split': 10, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 2 with value: 0.6329289680000295.

Running time: 11.3 sec
OOF RMSE: 2.10 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:44:01,067] Trial 3 finished with value: 0.6281901014129906 and parameters: {'n_estimators': 100, 'max_depth': 15, 'min_samples_split': 4, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 2 with value: 0.6329289680000295.

Running time: 2.4 sec
OOF RMSE: 2.11 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:44:07,733] Trial 4 finished with value: 0.5955488270691892 and parameters: {'n_estimators': 500, 'max_depth': 7, 'min_samples_split': 2, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 2 with value: 0.6329289680000295.

Running time: 6.7 sec
OOF RMSE: 2.20 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:44:12,010] Trial 5 finished with value: 0.6484398986736676 and parameters: {'n_estimators': 300, 'max_depth': 6, 'min_samples_split': 3, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 5 with value: 0.6484398986736676.

Running time: 4.3 sec
OOF RMSE: 2.06 | R2: 0.65
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:44:14,677] Trial 6 finished with value: 0.5574838063307648 and parameters: {'n_estimators': 100, 'max_depth': 14, 'min_samples_split': 2, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 5 with value: 0.6484398986736676.

Running time: 2.7 sec
OOF RMSE: 2.31 | R2: 0.56
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:44:18,604] Trial 7 finished with value: 0.5966176376440345 and parameters: {'n_estimators': 300, 'max_depth': 7, 'min_samples_split': 4, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 5 with value: 0.6484398986736676.

Running time: 3.9 sec
OOF RMSE: 2.20 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:44:25,848] Trial 8 finished with value: 0.6234233227188228 and parameters: {'n_estimators': 500, 'max_depth': 7, 'min_samples_split': 7, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 5 with value: 0.6484398986736676.

Running time: 7.2 sec
OOF RMSE: 2.13 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:44:34,460] Trial 9 finished with value: 0.5682353277123913 and parameters: {'n_estimators': 300, 'max_depth': 12, 'min_samples_split': 4, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 5 with value: 0.6484398986736676.

Running time: 8.6 sec
OOF RMSE: 2.28 | R2: 0.57
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:44:39,341] Trial 10 finished with value: 0.6284025878829715 and parameters: {'n_estimators': 300, 'max_depth': 10, 'min_samples_split': 7, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 5 with value: 0.6484398986736676.

Running time: 4.9 sec
OOF RMSE: 2.11 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:44:50,197] Trial 11 finished with value: 0.6061539143766679 and parameters: {'n_estimators': 500, 'max_depth': 10, 'min_samples_split': 10, 'min_samples_leaf': 4, 'bootstrap': False}. Best is trial 5 with value: 0.6484398986736676.

Running time: 10.9 sec
OOF RMSE: 2.18 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:44:58,471] Trial 12 finished with value: 0.6216628704645059 and parameters: {'n_estimators': 500, 'max_depth': 12, 'min_samples_split': 8, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 5 with value: 0.6484398986736676.

Running time: 8.3 sec
OOF RMSE: 2.13 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:45:05,043] Trial 13 finished with value: 0.6068432033103697 and parameters: {'n_estimators': 300, 'max_depth': 9, 'min_samples_split': 6, 'min_samples_leaf': 4, 'bootstrap': False}. Best is trial 5 with value: 0.6484398986736676.

Running time: 6.6 sec
OOF RMSE: 2.17 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:45:06,547] Trial 14 finished with value: 0.5964053841667297 and parameters: {'n_estimators': 100, 'max_depth': 13, 'min_samples_split': 9, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 5 with value: 0.6484398986736676.

Running time: 1.5 sec
OOF RMSE: 2.20 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:45:11,551] Trial 15 finished with value: 0.5390928597974081 and parameters: {'n_estimators': 300, 'max_depth': 5, 'min_samples_split': 6, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 5 with value: 0.6484398986736676.

Running time: 5.0 sec
OOF RMSE: 2.35 | R2: 0.54
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:45:22,881] Trial 16 finished with value: 0.631168248393087 and parameters: {'n_estimators': 500, 'max_depth': 9, 'min_samples_split': 5, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 5 with value: 0.6484398986736676.

Running time: 11.3 sec
OOF RMSE: 2.11 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:45:28,137] Trial 17 finished with value: 0.6339631953386817 and parameters: {'n_estimators': 300, 'max_depth': 12, 'min_samples_split': 8, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 5 with value: 0.6484398986736676.

Running time: 5.3 sec
OOF RMSE: 2.10 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:45:33,343] Trial 18 finished with value: 0.6351579104603977 and parameters: {'n_estimators': 300, 'max_depth': 11, 'min_samples_split': 8, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 5 with value: 0.6484398986736676.

Running time: 5.2 sec
OOF RMSE: 2.09 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:45:38,747] Trial 19 finished with value: 0.6447921612678289 and parameters: {'n_estimators': 300, 'max_depth': 10, 'min_samples_split': 5, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 5 with value: 0.6484398986736676.

Running time: 5.4 sec
OOF RMSE: 2.07 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:45:43,474] Trial 20 finished with value: 0.6366723608364444 and parameters: {'n_estimators': 300, 'max_depth': 8, 'min_samples_split': 3, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 5 with value: 0.6484398986736676.

Running time: 4.7 sec
OOF RMSE: 2.09 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:45:48,214] Trial 21 finished with value: 0.6366723608364444 and parameters: {'n_estimators': 300, 'max_depth': 8, 'min_samples_split': 3, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 5 with value: 0.6484398986736676.

Running time: 4.7 sec
OOF RMSE: 2.09 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:45:53,259] Trial 22 finished with value: 0.6498191441368857 and parameters: {'n_estimators': 300, 'max_depth': 8, 'min_samples_split': 3, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 22 with value: 0.6498191441368857.

Running time: 5.0 sec
OOF RMSE: 2.05 | R2: 0.65
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:45:58,467] Trial 23 finished with value: 0.6475177634096384 and parameters: {'n_estimators': 300, 'max_depth': 9, 'min_samples_split': 5, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 22 with value: 0.6498191441368857.

Running time: 5.2 sec
OOF RMSE: 2.06 | R2: 0.65
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:46:02,240] Trial 24 finished with value: 0.6467698145601571 and parameters: {'n_estimators': 300, 'max_depth': 5, 'min_samples_split': 5, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 22 with value: 0.6498191441368857.
[I 2025-07-11 23:46:02,241] A new study created in memory with name: no-name-6ae87677-d733-418f-9b52-4c202901e9ae

Running time: 3.8 sec
OOF RMSE: 2.06 | R2: 0.65

✅ RF - Mejor R2: 0.65
📋 Parámetros: {'n_estimators': 300, 'max_depth': 8, 'min_samples_split': 3, 'min_samples_leaf': 1, 'bootstrap': True}

Buscando mejores hiperparámetros para CAT...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:46:04,390] Trial 0 finished with value: 0.6645069342543775 and parameters: {'iterations': 500, 'learning_rate': 0.01938457405603316, 'depth': 5, 'l2_leaf_reg': 7.938528568932947}. Best is trial 0 with value: 0.6645069342543775.

Running time: 2.1 sec
OOF RMSE: 2.01 | R2: 0.66
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:46:08,171] Trial 1 finished with value: 0.6742347222023923 and parameters: {'iterations': 1000, 'learning_rate': 0.028268598279885176, 'depth': 5, 'l2_leaf_reg': 7.998110150245143}. Best is trial 1 with value: 0.6742347222023923.

Running time: 3.8 sec
OOF RMSE: 1.98 | R2: 0.67
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:46:49,107] Trial 2 finished with value: 0.6913225238097187 and parameters: {'iterations': 500, 'learning_rate': 0.08465098316960169, 'depth': 9, 'l2_leaf_reg': 2.9947933244173344}. Best is trial 2 with value: 0.6913225238097187.

Running time: 40.9 sec
OOF RMSE: 1.93 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:46:51,295] Trial 3 finished with value: 0.6659011555907907 and parameters: {'iterations': 500, 'learning_rate': 0.06126183657219991, 'depth': 5, 'l2_leaf_reg': 3.204536535625458}. Best is trial 2 with value: 0.6913225238097187.

Running time: 2.2 sec
OOF RMSE: 2.00 | R2: 0.67
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:46:53,286] Trial 4 finished with value: 0.6924228258740002 and parameters: {'iterations': 500, 'learning_rate': 0.06927302874744533, 'depth': 5, 'l2_leaf_reg': 1.3628213181521374}. Best is trial 4 with value: 0.6924228258740002.

Running time: 2.0 sec
OOF RMSE: 1.92 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:47:59,476] Trial 5 finished with value: 0.6865827401468613 and parameters: {'iterations': 500, 'learning_rate': 0.019036183517218044, 'depth': 10, 'l2_leaf_reg': 4.160456576617146}. Best is trial 4 with value: 0.6924228258740002.

Running time: 66.2 sec
OOF RMSE: 1.94 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:48:00,864] Trial 6 finished with value: 0.6260176492504268 and parameters: {'iterations': 500, 'learning_rate': 0.010486405170793224, 'depth': 4, 'l2_leaf_reg': 6.105704141919468}. Best is trial 4 with value: 0.6924228258740002.

Running time: 1.4 sec
OOF RMSE: 2.12 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:48:36,287] Trial 7 finished with value: 0.6905239115234028 and parameters: {'iterations': 1000, 'learning_rate': 0.04545443588887452, 'depth': 8, 'l2_leaf_reg': 4.826931928207121}. Best is trial 4 with value: 0.6924228258740002.

Running time: 35.4 sec
OOF RMSE: 1.93 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:48:37,902] Trial 8 finished with value: 0.6560738818167671 and parameters: {'iterations': 500, 'learning_rate': 0.02282781715759223, 'depth': 4, 'l2_leaf_reg': 4.332481351781505}. Best is trial 4 with value: 0.6924228258740002.

Running time: 1.6 sec
OOF RMSE: 2.03 | R2: 0.66
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:48:40,677] Trial 9 finished with value: 0.6938967929372137 and parameters: {'iterations': 1000, 'learning_rate': 0.05198448689870126, 'depth': 4, 'l2_leaf_reg': 2.096867227900898}. Best is trial 9 with value: 0.6938967929372137.

Running time: 2.8 sec
OOF RMSE: 1.92 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:49:06,747] Trial 10 finished with value: 0.7193508607147364 and parameters: {'iterations': 2000, 'learning_rate': 0.041037904354625496, 'depth': 7, 'l2_leaf_reg': 1.2453453187601524}. Best is trial 10 with value: 0.7193508607147364.

Running time: 26.1 sec
OOF RMSE: 1.84 | R2: 0.72
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:49:32,947] Trial 11 finished with value: 0.692573594930964 and parameters: {'iterations': 2000, 'learning_rate': 0.04279884047776963, 'depth': 7, 'l2_leaf_reg': 1.2854812388930217}. Best is trial 10 with value: 0.7193508607147364.

Running time: 26.2 sec
OOF RMSE: 1.92 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:49:58,809] Trial 12 finished with value: 0.6945050283521639 and parameters: {'iterations': 2000, 'learning_rate': 0.04205599113822838, 'depth': 7, 'l2_leaf_reg': 2.3377071698135072}. Best is trial 10 with value: 0.7193508607147364.

Running time: 25.9 sec
OOF RMSE: 1.92 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:50:24,441] Trial 13 finished with value: 0.6785214777989081 and parameters: {'iterations': 2000, 'learning_rate': 0.03372208948007753, 'depth': 7, 'l2_leaf_reg': 6.210589246970898}. Best is trial 10 with value: 0.7193508607147364.

Running time: 25.6 sec
OOF RMSE: 1.97 | R2: 0.68
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:51:35,099] Trial 14 finished with value: 0.6976652671916916 and parameters: {'iterations': 2000, 'learning_rate': 0.036191876814177563, 'depth': 8, 'l2_leaf_reg': 2.555985236043799}. Best is trial 10 with value: 0.7193508607147364.

Running time: 70.7 sec
OOF RMSE: 1.91 | R2: 0.70
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:52:45,593] Trial 15 finished with value: 0.692323727492679 and parameters: {'iterations': 2000, 'learning_rate': 0.028938535020736456, 'depth': 8, 'l2_leaf_reg': 9.546430114363709}. Best is trial 10 with value: 0.7193508607147364.

Running time: 70.5 sec
OOF RMSE: 1.92 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:53:56,123] Trial 16 finished with value: 0.7037876307451636 and parameters: {'iterations': 2000, 'learning_rate': 0.012498697943277735, 'depth': 8, 'l2_leaf_reg': 1.050234989152525}. Best is trial 10 with value: 0.7193508607147364.

Running time: 70.5 sec
OOF RMSE: 1.89 | R2: 0.70
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:54:09,160] Trial 17 finished with value: 0.7046726412253728 and parameters: {'iterations': 2000, 'learning_rate': 0.011803616860040386, 'depth': 6, 'l2_leaf_reg': 1.4960888374311048}. Best is trial 10 with value: 0.7193508607147364.

Running time: 13.0 sec
OOF RMSE: 1.88 | R2: 0.70
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:54:22,050] Trial 18 finished with value: 0.6873396548755343 and parameters: {'iterations': 2000, 'learning_rate': 0.014234859241146414, 'depth': 6, 'l2_leaf_reg': 3.567055641200159}. Best is trial 10 with value: 0.7193508607147364.

Running time: 12.9 sec
OOF RMSE: 1.94 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:54:34,854] Trial 19 finished with value: 0.6983940880367372 and parameters: {'iterations': 2000, 'learning_rate': 0.015970021290995177, 'depth': 6, 'l2_leaf_reg': 1.8484604432572067}. Best is trial 10 with value: 0.7193508607147364.

Running time: 12.8 sec
OOF RMSE: 1.90 | R2: 0.70
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:54:47,446] Trial 20 finished with value: 0.6895799062250823 and parameters: {'iterations': 2000, 'learning_rate': 0.023197935931936663, 'depth': 6, 'l2_leaf_reg': 7.3294569029325904}. Best is trial 10 with value: 0.7193508607147364.

Running time: 12.6 sec
OOF RMSE: 1.93 | R2: 0.69
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:57:30,620] Trial 21 finished with value: 0.7099322227936693 and parameters: {'iterations': 2000, 'learning_rate': 0.010165315241625832, 'depth': 9, 'l2_leaf_reg': 1.049947917640018}. Best is trial 10 with value: 0.7193508607147364.
[I 2025-07-11 23:57:30,621] A new study created in memory with name: no-name-bdad6fb2-cf92-43c5-a2bb-7b4d4b7a0d82
[I 2025-07-11 23:57:30,691] Trial 0 finished with value: 0.07677407761951038 and parameters: {'alpha': 9.473880310670008, 'l1_ratio': 0.15565934550095106}. Best is trial 0 with value: 0.07677407761951038.

Running time: 163.2 sec
OOF RMSE: 1.87 | R2: 0.71

✅ CAT - Mejor R2: 0.72
📋 Parámetros: {'iterations': 2000, 'learning_rate': 0.041037904354625496, 'depth': 7, 'l2_leaf_reg': 1.2453453187601524}

Buscando mejores hiperparámetros para EN...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.33 | R2: 0.08
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.748e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.890e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.568e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.974e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.894e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 23:57:30,864] Trial 1 finished with value: 0.24794436957526922 and parameters: {'alpha': 0.0009711112325685732, 'l1_ratio': 0.2870941536392855}. Best is trial 1 with value: 0.24794436957526922.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.547e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.229e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.524e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.555e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(

Fold 5
Running time: 0.2 sec
OOF RMSE: 3.01 | R2: 0.25
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.625e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 23:57:31,055] Trial 2 finished with value: 0.2292825825831225 and parameters: {'alpha': 0.0006131111282582125, 'l1_ratio': 0.21698706085980624}. Best is trial 1 with value: 0.24794436957526922.
[I 2025-07-11 23:57:31,172] Trial 3 finished with value: 0.3786689380102264 and parameters: {'alpha': 1.2107761315426673, 'l1_ratio': 0.5320763943689751}. Best is trial 3 with value: 0.3786689380102264.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.344e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.223e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(

Running time: 0.2 sec
OOF RMSE: 3.04 | R2: 0.23
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.73 | R2: 0.38
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.032e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.570e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.963e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 23:57:31,304] Trial 4 finished with value: 0.3216542235033186 and parameters: {'alpha': 0.003480636413546244, 'l1_ratio': 0.37608865250227674}. Best is trial 3 with value: 0.3786689380102264.
[I 2025-07-11 23:57:31,383] Trial 5 finished with value: -0.00027817151752640434 and parameters: {'alpha': 5.614314426902704, 'l1_ratio': 0.5134388307440009}. Best is trial 3 with value: 0.3786689380102264.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.949e+01, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.522e+01, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.86 | R2: 0.32
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.47 | R2: -0.00
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.949e+01, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.281e+01, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.029e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 23:57:31,511] Trial 6 finished with value: 0.3066861108719664 and parameters: {'alpha': 0.0037135265774741774, 'l1_ratio': 0.8299531130948229}. Best is trial 3 with value: 0.3786689380102264.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.542e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.270e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.570e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.498e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.535e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 23:57:31,625] Trial 7 finished with value: 0.21299825285406793 and parameters: {'alpha': 0.00043730318930848533, 'l1_ratio': 0.3744539567367847}. Best is trial 3 with value: 0.3786689380102264.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.474e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.89 | R2: 0.31
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.08 | R2: 0.21
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.902e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.645e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.655e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.348e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 23:57:31,752] Trial 8 finished with value: 0.23270387677630933 and parameters: {'alpha': 0.0008329617469555416, 'l1_ratio': 0.4993891104297147}. Best is trial 3 with value: 0.3786689380102264.
[I 2025-07-11 23:57:31,835] Trial 9 finished with value: 0.47947247575950824 and parameters: {'alpha': 0.19817676783082677, 'l1_ratio': 0.5922191722798141}. Best is trial 9 with value: 0.47947247575950824.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.04 | R2: 0.23
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.50 | R2: 0.48
Fold 1
Fold 2
Fold 3

[I 2025-07-11 23:57:31,932] Trial 10 finished with value: 0.5090468860299826 and parameters: {'alpha': 0.07023037496382047, 'l1_ratio': 0.8616330362775065}. Best is trial 10 with value: 0.5090468860299826.
[I 2025-07-11 23:57:32,044] Trial 11 finished with value: 0.5065416655698147 and parameters: {'alpha': 0.09723541785908763, 'l1_ratio': 0.9806907437544117}. Best is trial 10 with value: 0.5090468860299826.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.43 | R2: 0.51
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.44 | R2: 0.51
Fold 1
Fold 2

[I 2025-07-11 23:57:32,154] Trial 12 finished with value: 0.5090413396323121 and parameters: {'alpha': 0.06338514241881582, 'l1_ratio': 0.9852405994082687}. Best is trial 10 with value: 0.5090468860299826.
[I 2025-07-11 23:57:32,254] Trial 13 finished with value: 0.47020286148737755 and parameters: {'alpha': 0.02835782970413172, 'l1_ratio': 0.8106274607398921}. Best is trial 10 with value: 0.5090468860299826.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.43 | R2: 0.51
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.52 | R2: 0.47
Fold 1
Fold 2
Fold 3

[I 2025-07-11 23:57:32,358] Trial 14 finished with value: 0.4595301313735387 and parameters: {'alpha': 0.024195481580025335, 'l1_ratio': 0.9424585334276401}. Best is trial 10 with value: 0.5090468860299826.
[I 2025-07-11 23:57:32,450] Trial 15 finished with value: 0.4499944819795778 and parameters: {'alpha': 0.423222106816481, 'l1_ratio': 0.7238658989434812}. Best is trial 10 with value: 0.5090468860299826.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.55 | R2: 0.46
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.57 | R2: 0.45
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.792e+01, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.515e-01, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.365e+01, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.541e+00, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.341e+01, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 23:57:32,596] Trial 16 finished with value: 0.3796414656863556 and parameters: {'alpha': 0.009981132024012258, 'l1_ratio': 0.7354675691473704}. Best is trial 10 with value: 0.5090468860299826.
[I 2025-07-11 23:57:32,685] Trial 17 finished with value: 0.5067451275342374 and parameters: {'alpha': 0.09904602270998965, 'l1_ratio': 0.8914729874763543}. Best is trial 10 with value: 0.5090468860299826.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.73 | R2: 0.38
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.43 | R2: 0.51
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 23:57:32,779] Trial 18 finished with value: 0.3271472446298107 and parameters: {'alpha': 1.4052684214225721, 'l1_ratio': 0.6781514773343214}. Best is trial 10 with value: 0.5090468860299826.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.923e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.663e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.819e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.84 | R2: 0.33
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.647e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.927e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 23:57:32,965] Trial 19 finished with value: 0.1828110800198518 and parameters: {'alpha': 0.00010135616706600109, 'l1_ratio': 0.9975902409343769}. Best is trial 10 with value: 0.5090468860299826.
[I 2025-07-11 23:57:33,102] Trial 20 finished with value: 0.5084613580184343 and parameters: {'alpha': 0.06660731424991195, 'l1_ratio': 0.8524184476013841}. Best is trial 10 with value: 0.5090468860299826.

Running time: 0.2 sec
OOF RMSE: 3.13 | R2: 0.18
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.43 | R2: 0.51
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-11 23:57:33,197] Trial 21 finished with value: 0.5085972823395475 and parameters: {'alpha': 0.06787010011439326, 'l1_ratio': 0.8497900725615863}. Best is trial 10 with value: 0.5090468860299826.
[I 2025-07-11 23:57:33,288] Trial 22 finished with value: 0.4635718644996124 and parameters: {'alpha': 0.2846918203518881, 'l1_ratio': 0.7821082897241006}. Best is trial 10 with value: 0.5090468860299826.

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.43 | R2: 0.51
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.54 | R2: 0.46
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.383e+01, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.281e+01, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.814e+01, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.832e+01, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.837e+01, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-11 23:57:33,414] Trial 23 finished with value: 0.373071868708994 and parameters: {'alpha': 0.008851472329650688, 'l1_ratio': 0.6337654115945177}. Best is trial 10 with value: 0.5090468860299826.
[I 2025-07-11 23:57:33,545] Trial 24 finished with value: 0.4539855071545952 and parameters: {'alpha': 0.6286075992567227, 'l1_ratio': 0.02402565780565824}. Best is trial 10 with value: 0.5090468860299826.
[I 2025-07-11 23:57:33,546] A new study created in memory with name: no-name-a138c6bc-aebc-4264-a7c4-9e9de191365f

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.74 | R2: 0.37
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.56 | R2: 0.45

✅ EN - Mejor R2: 0.51
📋 Parámetros: {'alpha': 0.07023037496382047, 'l1_ratio': 0.8616330362775065}

🔍 Optimizando en C2RCC_rhow_1x1_depth_lt_1...
Buscando mejores hiperparámetros para XGB...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:57:37,596] Trial 0 finished with value: 0.524078811851276 and parameters: {'n_estimators': 500, 'learning_rate': 0.06985788793256364, 'max_depth': 8, 'min_child_weight': 2, 'subsample': 0.7964446997560825, 'colsample_bytree': 0.7234300869762775}. Best is trial 0 with value: 0.524078811851276.

Running time: 4.0 sec
OOF RMSE: 2.39 | R2: 0.52
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:57:46,592] Trial 1 finished with value: 0.5877031658192237 and parameters: {'n_estimators': 1000, 'learning_rate': 0.007138633990513745, 'max_depth': 6, 'min_child_weight': 1, 'subsample': 0.992530065642786, 'colsample_bytree': 0.9505086117888479}. Best is trial 1 with value: 0.5877031658192237.

Running time: 9.0 sec
OOF RMSE: 2.23 | R2: 0.59
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:58:01,146] Trial 2 finished with value: 0.5742320023010183 and parameters: {'n_estimators': 2000, 'learning_rate': 0.011970376977107587, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.7726646415018052, 'colsample_bytree': 0.8392985090041231}. Best is trial 1 with value: 0.5877031658192237.

Running time: 14.5 sec
OOF RMSE: 2.26 | R2: 0.57
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:58:03,908] Trial 3 finished with value: 0.5859523033928531 and parameters: {'n_estimators': 500, 'learning_rate': 0.0362135130561364, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.8046107034983163, 'colsample_bytree': 0.6210629195906865}. Best is trial 1 with value: 0.5877031658192237.

Running time: 2.8 sec
OOF RMSE: 2.23 | R2: 0.59
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:58:09,452] Trial 4 finished with value: 0.58958570484016 and parameters: {'n_estimators': 1000, 'learning_rate': 0.006300202111600782, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.9484933242939925, 'colsample_bytree': 0.8714845607673128}. Best is trial 4 with value: 0.58958570484016.

Running time: 5.5 sec
OOF RMSE: 2.22 | R2: 0.59
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:58:28,479] Trial 5 finished with value: 0.5590330475759719 and parameters: {'n_estimators': 2000, 'learning_rate': 0.006813777666294502, 'max_depth': 8, 'min_child_weight': 1, 'subsample': 0.8119136670149643, 'colsample_bytree': 0.852754852678508}. Best is trial 4 with value: 0.58958570484016.

Running time: 19.0 sec
OOF RMSE: 2.30 | R2: 0.56
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:58:34,321] Trial 6 finished with value: 0.581557135761936 and parameters: {'n_estimators': 1000, 'learning_rate': 0.013157455028427778, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.738232881363685, 'colsample_bytree': 0.8803971131839095}. Best is trial 4 with value: 0.58958570484016.

Running time: 5.8 sec
OOF RMSE: 2.24 | R2: 0.58
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:58:38,699] Trial 7 finished with value: 0.5809074279813193 and parameters: {'n_estimators': 500, 'learning_rate': 0.03955777438827077, 'max_depth': 8, 'min_child_weight': 2, 'subsample': 0.8577068443892956, 'colsample_bytree': 0.6905193381871494}. Best is trial 4 with value: 0.58958570484016.

Running time: 4.4 sec
OOF RMSE: 2.24 | R2: 0.58
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:58:46,739] Trial 8 finished with value: 0.5717191477695555 and parameters: {'n_estimators': 2000, 'learning_rate': 0.08627473690846785, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.8401814015851826, 'colsample_bytree': 0.8048371269792882}. Best is trial 4 with value: 0.58958570484016.

Running time: 8.0 sec
OOF RMSE: 2.27 | R2: 0.57
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:59:00,241] Trial 9 finished with value: 0.567052898765938 and parameters: {'n_estimators': 2000, 'learning_rate': 0.005472751113423451, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.733271299641005, 'colsample_bytree': 0.9752166987598684}. Best is trial 4 with value: 0.58958570484016.

Running time: 13.5 sec
OOF RMSE: 2.28 | R2: 0.57
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:59:04,836] Trial 10 finished with value: 0.6286916272119353 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01626161134619542, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.6114197967165038, 'colsample_bytree': 0.7450505343112996}. Best is trial 10 with value: 0.6286916272119353.

Running time: 4.6 sec
OOF RMSE: 2.11 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:59:09,407] Trial 11 finished with value: 0.6268076513008876 and parameters: {'n_estimators': 1000, 'learning_rate': 0.016053704022125463, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.6071378474717866, 'colsample_bytree': 0.742866029195161}. Best is trial 10 with value: 0.6286916272119353.

Running time: 4.6 sec
OOF RMSE: 2.12 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:59:14,019] Trial 12 finished with value: 0.6264221904491395 and parameters: {'n_estimators': 1000, 'learning_rate': 0.018955217420917398, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.6056372086831258, 'colsample_bytree': 0.7370507343776106}. Best is trial 10 with value: 0.6286916272119353.

Running time: 4.6 sec
OOF RMSE: 2.12 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:59:18,380] Trial 13 finished with value: 0.6188074554133838 and parameters: {'n_estimators': 1000, 'learning_rate': 0.023110080378023045, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.6041260625240699, 'colsample_bytree': 0.6534251360026367}. Best is trial 10 with value: 0.6286916272119353.

Running time: 4.4 sec
OOF RMSE: 2.14 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:59:23,190] Trial 14 finished with value: 0.5900322393044585 and parameters: {'n_estimators': 1000, 'learning_rate': 0.012431574276183218, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.6619500605915974, 'colsample_bytree': 0.756559806560582}. Best is trial 10 with value: 0.6286916272119353.

Running time: 4.8 sec
OOF RMSE: 2.22 | R2: 0.59
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:59:28,746] Trial 15 finished with value: 0.6104140147863792 and parameters: {'n_estimators': 1000, 'learning_rate': 0.02284430153678405, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.6699810649805505, 'colsample_bytree': 0.7831256606260668}. Best is trial 10 with value: 0.6286916272119353.

Running time: 5.5 sec
OOF RMSE: 2.16 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:59:33,806] Trial 16 finished with value: 0.6251090163347511 and parameters: {'n_estimators': 1000, 'learning_rate': 0.03938010858402513, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.6640264232519577, 'colsample_bytree': 0.6713461666427498}. Best is trial 10 with value: 0.6286916272119353.

Running time: 5.1 sec
OOF RMSE: 2.12 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:59:38,607] Trial 17 finished with value: 0.5798016118030936 and parameters: {'n_estimators': 1000, 'learning_rate': 0.009700567325130183, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.692284024027172, 'colsample_bytree': 0.7123867071889847}. Best is trial 10 with value: 0.6286916272119353.

Running time: 4.8 sec
OOF RMSE: 2.25 | R2: 0.58
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:59:45,631] Trial 18 finished with value: 0.6212447950319151 and parameters: {'n_estimators': 1000, 'learning_rate': 0.017633345315766175, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.6281184740686783, 'colsample_bytree': 0.7815110707014423}. Best is trial 10 with value: 0.6286916272119353.

Running time: 7.0 sec
OOF RMSE: 2.13 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:59:48,113] Trial 19 finished with value: 0.5664401316431564 and parameters: {'n_estimators': 500, 'learning_rate': 0.029029352958306272, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.7078353163170993, 'colsample_bytree': 0.6053773823140154}. Best is trial 10 with value: 0.6286916272119353.

Running time: 2.5 sec
OOF RMSE: 2.28 | R2: 0.57
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:59:53,655] Trial 20 finished with value: 0.6241938933295719 and parameters: {'n_estimators': 1000, 'learning_rate': 0.00876697394067421, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.6385965042202807, 'colsample_bytree': 0.9161665006730586}. Best is trial 10 with value: 0.6286916272119353.

Running time: 5.5 sec
OOF RMSE: 2.13 | R2: 0.62
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 23:59:58,291] Trial 21 finished with value: 0.6285155439535426 and parameters: {'n_estimators': 1000, 'learning_rate': 0.016671756845708336, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.6004647939899238, 'colsample_bytree': 0.7390732433458008}. Best is trial 10 with value: 0.6286916272119353.

Running time: 4.6 sec
OOF RMSE: 2.11 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-12 00:00:03,114] Trial 22 finished with value: 0.6330255959890827 and parameters: {'n_estimators': 1000, 'learning_rate': 0.016095735288348654, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.6011524367589229, 'colsample_bytree': 0.8122885062853744}. Best is trial 22 with value: 0.6330255959890827.

Running time: 4.8 sec
OOF RMSE: 2.10 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-12 00:00:08,853] Trial 23 finished with value: 0.5985730843311126 and parameters: {'n_estimators': 1000, 'learning_rate': 0.027290041375485286, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.6459227241820888, 'colsample_bytree': 0.8220602695756785}. Best is trial 22 with value: 0.6330255959890827.

Running time: 5.7 sec
OOF RMSE: 2.20 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-12 00:00:14,349] Trial 24 finished with value: 0.5836523252858312 and parameters: {'n_estimators': 1000, 'learning_rate': 0.014967961995095098, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.9035030716294965, 'colsample_bytree': 0.7727944084929915}. Best is trial 22 with value: 0.6330255959890827.
[I 2025-07-12 00:00:14,351] A new study created in memory with name: no-name-19d35418-8014-47f8-8d7f-badfdc79be26

Running time: 5.5 sec
OOF RMSE: 2.24 | R2: 0.58

✅ XGB - Mejor R2: 0.63
📋 Parámetros: {'n_estimators': 1000, 'learning_rate': 0.016095735288348654, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.6011524367589229, 'colsample_bytree': 0.8122885062853744}

Buscando mejores hiperparámetros para LBM...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-12 00:00:15,630] Trial 0 finished with value: 0.5565859786019549 and parameters: {'learning_rate': 0.040351333588215105, 'num_leaves': 60, 'max_depth': 7, 'min_child_samples': 8, 'subsample': 0.9623778096328554, 'colsample_bytree': 0.7795063927139135, 'n_estimators': 2000}. Best is trial 0 with value: 0.5565859786019549.

Running time: 1.3 sec
OOF RMSE: 2.31 | R2: 0.56
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-12 00:00:15,919] Trial 1 finished with value: 0.46775488773097695 and parameters: {'learning_rate': 0.06575345366637399, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 13, 'subsample': 0.7253946413229078, 'colsample_bytree': 0.9542466613459476, 'n_estimators': 500}. Best is trial 0 with value: 0.5565859786019549.

Fold 5
Running time: 0.3 sec
OOF RMSE: 2.53 | R2: 0.47
Fold 1
Fold 2
Fold 3

[I 2025-07-12 00:00:16,295] Trial 2 finished with value: 0.5567926241344607 and parameters: {'learning_rate': 0.017727897859432528, 'num_leaves': 40, 'max_depth': 7, 'min_child_samples': 12, 'subsample': 0.7569109380239507, 'colsample_bytree': 0.8364536192029534, 'n_estimators': 500}. Best is trial 2 with value: 0.5567926241344607.

Fold 4
Fold 5
Running time: 0.4 sec
OOF RMSE: 2.31 | R2: 0.56
Fold 1
Fold 2
Fold 3

[I 2025-07-12 00:00:16,783] Trial 3 finished with value: 0.56047439786948 and parameters: {'learning_rate': 0.009115984539428993, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 25, 'subsample': 0.6729672025581425, 'colsample_bytree': 0.7484626401800418, 'n_estimators': 1000}. Best is trial 3 with value: 0.56047439786948.

Fold 4
Fold 5
Running time: 0.5 sec
OOF RMSE: 2.30 | R2: 0.56
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-12 00:00:17,042] Trial 4 finished with value: 0.47234580457504227 and parameters: {'learning_rate': 0.0064243707806013175, 'num_leaves': 60, 'max_depth': 8, 'min_child_samples': 25, 'subsample': 0.6308816719058367, 'colsample_bytree': 0.6977767422225949, 'n_estimators': 500}. Best is trial 3 with value: 0.56047439786948.

Running time: 0.3 sec
OOF RMSE: 2.52 | R2: 0.47
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-12 00:00:18,202] Trial 5 finished with value: 0.5428930929406932 and parameters: {'learning_rate': 0.005865195213678847, 'num_leaves': 80, 'max_depth': 7, 'min_child_samples': 17, 'subsample': 0.7477503094027025, 'colsample_bytree': 0.7503362324776345, 'n_estimators': 2000}. Best is trial 3 with value: 0.56047439786948.

Fold 5
Running time: 1.2 sec
OOF RMSE: 2.34 | R2: 0.54
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-12 00:00:18,460] Trial 6 finished with value: 0.5772581719858698 and parameters: {'learning_rate': 0.031331072269248084, 'num_leaves': 60, 'max_depth': 7, 'min_child_samples': 24, 'subsample': 0.9225687104840656, 'colsample_bytree': 0.6593946943525972, 'n_estimators': 500}. Best is trial 6 with value: 0.5772581719858698.

Running time: 0.3 sec
OOF RMSE: 2.25 | R2: 0.58
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-12 00:00:19,329] Trial 7 finished with value: 0.5146841202291741 and parameters: {'learning_rate': 0.06786039015129311, 'num_leaves': 40, 'max_depth': 6, 'min_child_samples': 25, 'subsample': 0.9377753721245473, 'colsample_bytree': 0.6586498215399933, 'n_estimators': 2000}. Best is trial 6 with value: 0.5772581719858698.

Fold 5
Running time: 0.9 sec
OOF RMSE: 2.41 | R2: 0.51
Fold 1
Fold 2
Fold 3

[I 2025-07-12 00:00:19,842] Trial 8 finished with value: 0.572033933662995 and parameters: {'learning_rate': 0.007647768402487599, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 12, 'subsample': 0.613662548744142, 'colsample_bytree': 0.6776023826453772, 'n_estimators': 1000}. Best is trial 6 with value: 0.5772581719858698.

Fold 4
Fold 5
Running time: 0.5 sec
OOF RMSE: 2.27 | R2: 0.57
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-12 00:00:20,177] Trial 9 finished with value: 0.4973546937274953 and parameters: {'learning_rate': 0.03115645781382589, 'num_leaves': 40, 'max_depth': 7, 'min_child_samples': 15, 'subsample': 0.9808984381448866, 'colsample_bytree': 0.8237526676266822, 'n_estimators': 500}. Best is trial 6 with value: 0.5772581719858698.

Running time: 0.3 sec
OOF RMSE: 2.46 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-12 00:00:20,431] Trial 10 finished with value: 0.5476015646418713 and parameters: {'learning_rate': 0.017259674978930998, 'num_leaves': 60, 'max_depth': 5, 'min_child_samples': 20, 'subsample': 0.885182719660532, 'colsample_bytree': 0.6062697120346677, 'n_estimators': 500}. Best is trial 6 with value: 0.5772581719858698.

Fold 5
Running time: 0.2 sec
OOF RMSE: 2.33 | R2: 0.55
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-12 00:00:21,024] Trial 11 finished with value: 0.5896981851649293 and parameters: {'learning_rate': 0.011932503618933036, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 6, 'subsample': 0.8538957732054971, 'colsample_bytree': 0.6000808128174124, 'n_estimators': 1000}. Best is trial 11 with value: 0.5896981851649293.

Fold 5
Running time: 0.6 sec
OOF RMSE: 2.22 | R2: 0.59
Fold 1
Fold 2
Fold 3

[I 2025-07-12 00:00:21,598] Trial 12 finished with value: 0.6025429719530935 and parameters: {'learning_rate': 0.01474298474810751, 'num_leaves': 80, 'max_depth': 5, 'min_child_samples': 5, 'subsample': 0.8533114565344532, 'colsample_bytree': 0.6015970871864981, 'n_estimators': 1000}. Best is trial 12 with value: 0.6025429719530935.

Fold 4
Fold 5
Running time: 0.6 sec
OOF RMSE: 2.19 | R2: 0.60
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-12 00:00:22,103] Trial 13 finished with value: 0.6068679020971708 and parameters: {'learning_rate': 0.012180059733652663, 'num_leaves': 80, 'max_depth': 5, 'min_child_samples': 5, 'subsample': 0.8366799939698395, 'colsample_bytree': 0.6054562730928836, 'n_estimators': 1000}. Best is trial 13 with value: 0.6068679020971708.

Running time: 0.5 sec
OOF RMSE: 2.17 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-12 00:00:22,715] Trial 14 finished with value: 0.5872023719311981 and parameters: {'learning_rate': 0.012490304582553752, 'num_leaves': 80, 'max_depth': 5, 'min_child_samples': 5, 'subsample': 0.8316704003916627, 'colsample_bytree': 0.9130259319830384, 'n_estimators': 1000}. Best is trial 13 with value: 0.6068679020971708.

Fold 5
Running time: 0.6 sec
OOF RMSE: 2.23 | R2: 0.59
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-12 00:00:23,207] Trial 15 finished with value: 0.5324989530041134 and parameters: {'learning_rate': 0.020628479665811397, 'num_leaves': 80, 'max_depth': 5, 'min_child_samples': 9, 'subsample': 0.801091569526325, 'colsample_bytree': 0.6263120930168068, 'n_estimators': 1000}. Best is trial 13 with value: 0.6068679020971708.

Fold 5
Running time: 0.5 sec
OOF RMSE: 2.37 | R2: 0.53
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-12 00:00:23,705] Trial 16 finished with value: 0.5779033844113809 and parameters: {'learning_rate': 0.011957451736137659, 'num_leaves': 80, 'max_depth': 5, 'min_child_samples': 8, 'subsample': 0.8814342601946186, 'colsample_bytree': 0.7321088871595213, 'n_estimators': 1000}. Best is trial 13 with value: 0.6068679020971708.

Fold 5
Running time: 0.5 sec
OOF RMSE: 2.25 | R2: 0.58
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-12 00:00:24,671] Trial 17 finished with value: 0.57334029371476 and parameters: {'learning_rate': 0.09965234276329507, 'num_leaves': 80, 'max_depth': 8, 'min_child_samples': 5, 'subsample': 0.7818846694334065, 'colsample_bytree': 0.8692817790856902, 'n_estimators': 1000}. Best is trial 13 with value: 0.6068679020971708.

Fold 5
Running time: 1.0 sec
OOF RMSE: 2.26 | R2: 0.57
Fold 1
Fold 2
Fold 3

[I 2025-07-12 00:00:25,220] Trial 18 finished with value: 0.5493547467496577 and parameters: {'learning_rate': 0.027404490836602406, 'num_leaves': 80, 'max_depth': 5, 'min_child_samples': 10, 'subsample': 0.8216031917776653, 'colsample_bytree': 0.7043927224966279, 'n_estimators': 1000}. Best is trial 13 with value: 0.6068679020971708.

Fold 4
Fold 5
Running time: 0.5 sec
OOF RMSE: 2.33 | R2: 0.55
Fold 1
Fold 2
Fold 3

[I 2025-07-12 00:00:25,793] Trial 19 finished with value: 0.5483418666053523 and parameters: {'learning_rate': 0.01510732286808681, 'num_leaves': 80, 'max_depth': 6, 'min_child_samples': 7, 'subsample': 0.7007970909493088, 'colsample_bytree': 0.6444545315049857, 'n_estimators': 1000}. Best is trial 13 with value: 0.6068679020971708.

Fold 4
Fold 5
Running time: 0.6 sec
OOF RMSE: 2.33 | R2: 0.55
Fold 1
Fold 2
Fold 3

[I 2025-07-12 00:00:26,243] Trial 20 finished with value: 0.549123381927488 and parameters: {'learning_rate': 0.005176994485383049, 'num_leaves': 80, 'max_depth': 5, 'min_child_samples': 10, 'subsample': 0.8996571270623982, 'colsample_bytree': 0.6990398296002852, 'n_estimators': 1000}. Best is trial 13 with value: 0.6068679020971708.

Fold 4
Fold 5
Running time: 0.4 sec
OOF RMSE: 2.33 | R2: 0.55
Fold 1
Fold 2
Fold 3

[I 2025-07-12 00:00:26,759] Trial 21 finished with value: 0.6076496790236416 and parameters: {'learning_rate': 0.01015231557266531, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 5, 'subsample': 0.8486611598336831, 'colsample_bytree': 0.6028640324608862, 'n_estimators': 1000}. Best is trial 21 with value: 0.6076496790236416.

Fold 4
Fold 5
Running time: 0.5 sec
OOF RMSE: 2.17 | R2: 0.61
Fold 1
Fold 2
Fold 3

[I 2025-07-12 00:00:27,295] Trial 22 finished with value: 0.6085985836015166 and parameters: {'learning_rate': 0.008867488108075522, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 5, 'subsample': 0.8506476310106841, 'colsample_bytree': 0.6323146490623183, 'n_estimators': 1000}. Best is trial 22 with value: 0.6085985836015166.

Fold 4
Fold 5
Running time: 0.5 sec
OOF RMSE: 2.17 | R2: 0.61
Fold 1
Fold 2
Fold 3

[I 2025-07-12 00:00:27,873] Trial 23 finished with value: 0.5655383244859148 and parameters: {'learning_rate': 0.009285886391954004, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 7, 'subsample': 0.7931372903676954, 'colsample_bytree': 0.6423819026307828, 'n_estimators': 1000}. Best is trial 22 with value: 0.6085985836015166.

Fold 4
Fold 5
Running time: 0.6 sec
OOF RMSE: 2.28 | R2: 0.57
Fold 1
Fold 2
Fold 3

[I 2025-07-12 00:00:28,329] Trial 24 finished with value: 0.563993634271045 and parameters: {'learning_rate': 0.008577541444858503, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 10, 'subsample': 0.852620616304053, 'colsample_bytree': 0.6315873912879456, 'n_estimators': 1000}. Best is trial 22 with value: 0.6085985836015166.
[I 2025-07-12 00:00:28,331] A new study created in memory with name: no-name-77df1e44-a25e-4787-b36a-ab68a3a081b5

Fold 4
Fold 5
Running time: 0.5 sec
OOF RMSE: 2.29 | R2: 0.56

✅ LBM - Mejor R2: 0.61
📋 Parámetros: {'learning_rate': 0.008867488108075522, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 5, 'subsample': 0.8506476310106841, 'colsample_bytree': 0.6323146490623183, 'n_estimators': 1000}

Buscando mejores hiperparámetros para MLP...
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

[I 2025-07-12 00:00:29,250] Trial 0 finished with value: 0.2822383662479583 and parameters: {'hidden_layer_sizes': '50', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.01216523306344915, 'learning_rate': 'constant', 'learning_rate_init': 0.0018521702178009292}. Best is trial 0 with value: 0.2822383662479583.

Running time: 0.9 sec
OOF RMSE: 2.94 | R2: 0.28
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-12 00:00:32,370] Trial 1 finished with value: 0.42235065220026136 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.0180459485912913, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0038796783146411175}. Best is trial 1 with value: 0.42235065220026136.

Running time: 3.1 sec
OOF RMSE: 2.63 | R2: 0.42
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-12 00:00:34,799] Trial 2 finished with value: 0.4308561117422548 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.05140766970235253, 'learning_rate': 'constant', 'learning_rate_init': 0.0001207877743676606}. Best is trial 2 with value: 0.4308561117422548.

Running time: 2.4 sec
OOF RMSE: 2.62 | R2: 0.43
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-12 00:00:37,246] Trial 3 finished with value: 0.4042914152739404 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.0010320580273216954, 'learning_rate': 'constant', 'learning_rate_init': 0.0005794754950505393}. Best is trial 2 with value: 0.4308561117422548.

Running time: 2.4 sec
OOF RMSE: 2.68 | R2: 0.40
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

[I 2025-07-12 00:00:38,452] Trial 4 finished with value: 0.4373010731111281 and parameters: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'adam', 'alpha': 9.252142605364819e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.0004608299955455316}. Best is trial 4 with value: 0.4373010731111281.

Running time: 1.2 sec
OOF RMSE: 2.60 | R2: 0.44
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

[I 2025-07-12 00:00:41,126] Trial 5 finished with value: 0.3319108629927352 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.0003183535870972647, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00014215167001063142}. Best is trial 4 with value: 0.4373010731111281.

Running time: 2.7 sec
OOF RMSE: 2.83 | R2: 0.33
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-12 00:00:41,813] Trial 6 finished with value: 0.44710726215007324 and parameters: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.00010454509641968159, 'learning_rate': 'constant', 'learning_rate_init': 0.008495659363685881}. Best is trial 6 with value: 0.44710726215007324.

Running time: 0.7 sec
OOF RMSE: 2.58 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-12 00:00:43,332] Trial 7 finished with value: 0.4888263697343439 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'tanh', 'solver': 'adam', 'alpha': 8.834133808286119e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.0031819145655684286}. Best is trial 7 with value: 0.4888263697343439.

Running time: 1.5 sec
OOF RMSE: 2.48 | R2: 0.49
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-12 00:00:45,669] Trial 8 finished with value: 0.5488721407863028 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.014774616202901094, 'learning_rate': 'constant', 'learning_rate_init': 0.0007558099643269701}. Best is trial 8 with value: 0.5488721407863028.

Running time: 2.3 sec
OOF RMSE: 2.33 | R2: 0.55
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-12 00:00:46,443] Trial 9 finished with value: 0.45849257073116356 and parameters: {'hidden_layer_sizes': '100', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.00028085742121315385, 'learning_rate': 'constant', 'learning_rate_init': 0.007209956319677138}. Best is trial 8 with value: 0.5488721407863028.

Running time: 0.8 sec
OOF RMSE: 2.55 | R2: 0.46
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-12 00:00:49,069] Trial 10 finished with value: 0.4397186887157253 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.003612825015302069, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0008062565737305982}. Best is trial 8 with value: 0.5488721407863028.

Running time: 2.6 sec
OOF RMSE: 2.59 | R2: 0.44
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

[I 2025-07-12 00:00:50,707] Trial 11 finished with value: 0.48306517301699725 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'tanh', 'solver': 'adam', 'alpha': 1.066904996534364e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.0018464596691005883}. Best is trial 8 with value: 0.5488721407863028.

Running time: 1.6 sec
OOF RMSE: 2.49 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

[I 2025-07-12 00:00:52,644] Trial 12 finished with value: 0.48316873588049336 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'tanh', 'solver': 'adam', 'alpha': 1.045188100865095e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.0018021669493895817}. Best is trial 8 with value: 0.5488721407863028.

Running time: 1.9 sec
OOF RMSE: 2.49 | R2: 0.48
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-12 00:00:55,604] Trial 13 finished with value: 0.40981838301367346 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.09219046262108854, 'learning_rate': 'constant', 'learning_rate_init': 0.00027178279529887584}. Best is trial 8 with value: 0.5488721407863028.

Running time: 3.0 sec
OOF RMSE: 2.66 | R2: 0.41
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-12 00:00:55,921] Trial 14 finished with value: 0.3383805956276842 and parameters: {'hidden_layer_sizes': '50', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0028671605810150266, 'learning_rate': 'adaptive', 'learning_rate_init': 0.003517009460159228}. Best is trial 8 with value: 0.5488721407863028.

Fold 5
Running time: 0.3 sec
OOF RMSE: 2.82 | R2: 0.34
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-12 00:00:58,709] Trial 15 finished with value: 0.5000064129347274 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'tanh', 'solver': 'adam', 'alpha': 4.28492411714394e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.0010110451592217475}. Best is trial 8 with value: 0.5488721407863028.

Running time: 2.8 sec
OOF RMSE: 2.45 | R2: 0.50
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-12 00:01:01,257] Trial 16 finished with value: 0.43032690608626467 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'tanh', 'solver': 'adam', 'alpha': 3.20124448753885e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.00032406286823695067}. Best is trial 8 with value: 0.5488721407863028.

Running time: 2.5 sec
OOF RMSE: 2.62 | R2: 0.43
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-12 00:01:02,506] Trial 17 finished with value: 0.5504107547022172 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.00550741918180148, 'learning_rate': 'constant', 'learning_rate_init': 0.0010799825727407745}. Best is trial 17 with value: 0.5504107547022172.

Running time: 1.2 sec
OOF RMSE: 2.32 | R2: 0.55
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

[I 2025-07-12 00:01:03,817] Trial 18 finished with value: 0.38000940479770395 and parameters: {'hidden_layer_sizes': '50', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.008566497655201557, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0010940190782460133}. Best is trial 17 with value: 0.5504107547022172.

Running time: 1.3 sec
OOF RMSE: 2.73 | R2: 0.38
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-12 00:01:05,571] Trial 19 finished with value: 0.5038101910870786 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0016946673849269817, 'learning_rate': 'constant', 'learning_rate_init': 0.0002588116482453604}. Best is trial 17 with value: 0.5504107547022172.

Running time: 1.7 sec
OOF RMSE: 2.44 | R2: 0.50
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-12 00:01:07,727] Trial 20 finished with value: 0.5422973790418693 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.032461035149566365, 'learning_rate': 'constant', 'learning_rate_init': 0.0005684078553892068}. Best is trial 17 with value: 0.5504107547022172.

Running time: 2.2 sec
OOF RMSE: 2.35 | R2: 0.54
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-07-12 00:01:09,947] Trial 21 finished with value: 0.546723499353186 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.02949943931385231, 'learning_rate': 'constant', 'learning_rate_init': 0.0006352302429179895}. Best is trial 17 with value: 0.5504107547022172.

Running time: 2.2 sec
OOF RMSE: 2.33 | R2: 0.55
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

[I 2025-07-12 00:01:11,671] Trial 22 finished with value: 0.549015570208084 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.006546799418513086, 'learning_rate': 'constant', 'learning_rate_init': 0.0012822954517404115}. Best is trial 17 with value: 0.5504107547022172.

Running time: 1.7 sec
OOF RMSE: 2.33 | R2: 0.55
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

[I 2025-07-12 00:01:13,152] Trial 23 finished with value: 0.5465026842089431 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.006492453695683787, 'learning_rate': 'constant', 'learning_rate_init': 0.0011737187101825035}. Best is trial 17 with value: 0.5504107547022172.

Running time: 1.5 sec
OOF RMSE: 2.33 | R2: 0.55
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

[I 2025-07-12 00:01:14,436] Trial 24 finished with value: 0.5490063400696079 and parameters: {'hidden_layer_sizes': '100_50', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.003977985784196723, 'learning_rate': 'constant', 'learning_rate_init': 0.0014685325366454252}. Best is trial 17 with value: 0.5504107547022172.
[I 2025-07-12 00:01:14,437] A new study created in memory with name: no-name-747f3ff1-a8e3-42f6-af22-f89bcc09d5f3
[I 2025-07-12 00:01:14,525] Trial 0 finished with value: -4.750480776194466 and parameters: {'kernel': 'sigmoid', 'C': 0.8933925500050957, 'epsilon': 0.014221596848118308, 'gamma': 'scale'}. Best is trial 0 with value: -4.750480776194466.
[I 2025-07-12 00:01:14,604] Trial 1 finished with value: -0.2592509750819949 and parameters: {'kernel': 'sigmoid', 'C': 0.2563522227466809, 'epsilon': 0.02039083871942041, 'gamma': 'auto'}. Best is trial 1 with value: -0.2592509750819949.

Running time: 1.3 sec
OOF RMSE: 2.33 | R2: 0.55

✅ MLP - Mejor R2: 0.55
📋 Parámetros: {'hidden_layer_sizes': '100_50', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.00550741918180148, 'learning_rate': 'constant', 'learning_rate_init': 0.0010799825727407745}

Buscando mejores hiperparámetros para SVR...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 8.31 | R2: -4.75
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.89 | R2: -0.26
Fold 1
Fold 2

[I 2025-07-12 00:01:14,677] Trial 2 finished with value: 0.245045080103085 and parameters: {'kernel': 'rbf', 'C': 1.3846784193392832, 'epsilon': 0.08951386079164665, 'gamma': 'scale'}. Best is trial 2 with value: 0.245045080103085.
[I 2025-07-12 00:01:14,756] Trial 3 finished with value: 0.49193318701339894 and parameters: {'kernel': 'rbf', 'C': 8.595857896035039, 'epsilon': 0.11343364667021451, 'gamma': 'scale'}. Best is trial 3 with value: 0.49193318701339894.
[I 2025-07-12 00:01:14,827] Trial 4 finished with value: 0.2402523540047251 and parameters: {'kernel': 'rbf', 'C': 1.279409201200847, 'epsilon': 0.15643229779967635, 'gamma': 'scale'}. Best is trial 3 with value: 0.49193318701339894.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.01 | R2: 0.25
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.47 | R2: 0.49
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.02 | R2: 0.24
Fold 1

[I 2025-07-12 00:01:14,901] Trial 5 finished with value: -0.2809575197161087 and parameters: {'kernel': 'sigmoid', 'C': 0.2422766579830829, 'epsilon': 0.1001871252340998, 'gamma': 'scale'}. Best is trial 3 with value: 0.49193318701339894.
[I 2025-07-12 00:01:14,974] Trial 6 finished with value: 0.2260628082875884 and parameters: {'kernel': 'rbf', 'C': 1.1528035817091196, 'epsilon': 0.06715298090136518, 'gamma': 'scale'}. Best is trial 3 with value: 0.49193318701339894.
[I 2025-07-12 00:01:15,048] Trial 7 finished with value: 0.14358219968330066 and parameters: {'kernel': 'rbf', 'C': 0.4509533618323895, 'epsilon': 0.10948800934244544, 'gamma': 'scale'}. Best is trial 3 with value: 0.49193318701339894.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.92 | R2: -0.28
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.05 | R2: 0.23
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.21 | R2: 0.14

[I 2025-07-12 00:01:15,130] Trial 8 finished with value: 0.21916990192600916 and parameters: {'kernel': 'rbf', 'C': 1.146158065395679, 'epsilon': 0.02797333620807227, 'gamma': 'auto'}. Best is trial 3 with value: 0.49193318701339894.
[I 2025-07-12 00:01:15,221] Trial 9 finished with value: 0.052814167950544944 and parameters: {'kernel': 'sigmoid', 'C': 0.10490841107684364, 'epsilon': 0.1253797697252482, 'gamma': 'scale'}. Best is trial 3 with value: 0.49193318701339894.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.06 | R2: 0.22
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.37 | R2: 0.05
Fold 1
Fold 2

[I 2025-07-12 00:01:15,310] Trial 10 finished with value: 0.5001887534971063 and parameters: {'kernel': 'rbf', 'C': 9.825358412782949, 'epsilon': 0.19683731218208028, 'gamma': 'auto'}. Best is trial 10 with value: 0.5001887534971063.
[I 2025-07-12 00:01:15,394] Trial 11 finished with value: 0.5021390931221881 and parameters: {'kernel': 'rbf', 'C': 9.929439307242298, 'epsilon': 0.1849685814692066, 'gamma': 'auto'}. Best is trial 11 with value: 0.5021390931221881.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.45 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.45 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-12 00:01:15,476] Trial 12 finished with value: 0.4824310687543947 and parameters: {'kernel': 'rbf', 'C': 8.652580014757577, 'epsilon': 0.1954413730388579, 'gamma': 'auto'}. Best is trial 11 with value: 0.5021390931221881.
[I 2025-07-12 00:01:15,556] Trial 13 finished with value: 0.35422941862207125 and parameters: {'kernel': 'rbf', 'C': 3.8828108794497687, 'epsilon': 0.1965993886865833, 'gamma': 'auto'}. Best is trial 11 with value: 0.5021390931221881.
[I 2025-07-12 00:01:15,637] Trial 14 finished with value: 0.3455990149962993 and parameters: {'kernel': 'rbf', 'C': 3.7264775568212496, 'epsilon': 0.16324138179636405, 'gamma': 'auto'}. Best is trial 11 with value: 0.5021390931221881.

Running time: 0.1 sec
OOF RMSE: 2.49 | R2: 0.48
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.79 | R2: 0.35
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.80 | R2: 0.35
Fold 1
Fold 2
Fold 3

[I 2025-07-12 00:01:15,719] Trial 15 finished with value: 0.35955635677295794 and parameters: {'kernel': 'rbf', 'C': 4.113947989952233, 'epsilon': 0.16579076409705418, 'gamma': 'auto'}. Best is trial 11 with value: 0.5021390931221881.
[I 2025-07-12 00:01:15,802] Trial 16 finished with value: 0.41776974188632987 and parameters: {'kernel': 'rbf', 'C': 5.756213453929946, 'epsilon': 0.14419769296894064, 'gamma': 'auto'}. Best is trial 11 with value: 0.5021390931221881.
[I 2025-07-12 00:01:15,883] Trial 17 finished with value: 0.28578643509459456 and parameters: {'kernel': 'rbf', 'C': 2.2502418321156554, 'epsilon': 0.18137005071170875, 'gamma': 'auto'}. Best is trial 11 with value: 0.5021390931221881.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.77 | R2: 0.36
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.65 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.93 | R2: 0.29

[I 2025-07-12 00:01:15,966] Trial 18 finished with value: -444.584660358401 and parameters: {'kernel': 'sigmoid', 'C': 9.669810090458551, 'epsilon': 0.1402021826088987, 'gamma': 'auto'}. Best is trial 11 with value: 0.5021390931221881.
[I 2025-07-12 00:01:16,047] Trial 19 finished with value: 0.4349726507271928 and parameters: {'kernel': 'rbf', 'C': 6.239661908292755, 'epsilon': 0.18250928945713948, 'gamma': 'auto'}. Best is trial 11 with value: 0.5021390931221881.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 73.17 | R2: -444.58
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.61 | R2: 0.43
Fold 1
Fold 2
Fold 3

[I 2025-07-12 00:01:16,133] Trial 20 finished with value: 0.2947192862205159 and parameters: {'kernel': 'rbf', 'C': 2.4219713557068134, 'epsilon': 0.04776058663631513, 'gamma': 'auto'}. Best is trial 11 with value: 0.5021390931221881.
[I 2025-07-12 00:01:16,236] Trial 21 finished with value: 0.45336858535207847 and parameters: {'kernel': 'rbf', 'C': 6.788335660465497, 'epsilon': 0.07092084025605208, 'gamma': 'scale'}. Best is trial 11 with value: 0.5021390931221881.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.91 | R2: 0.29
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.56 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-12 00:01:16,327] Trial 22 finished with value: 0.49990468850939174 and parameters: {'kernel': 'rbf', 'C': 9.72143588421514, 'epsilon': 0.12336605893669703, 'gamma': 'auto'}. Best is trial 11 with value: 0.5021390931221881.
[I 2025-07-12 00:01:16,412] Trial 23 finished with value: 0.2892494694611336 and parameters: {'kernel': 'rbf', 'C': 2.355739737990342, 'epsilon': 0.17940527555986052, 'gamma': 'auto'}. Best is trial 11 with value: 0.5021390931221881.
[I 2025-07-12 00:01:16,493] Trial 24 finished with value: 0.3891006724504338 and parameters: {'kernel': 'rbf', 'C': 4.935609827846782, 'epsilon': 0.13483488020024875, 'gamma': 'auto'}. Best is trial 11 with value: 0.5021390931221881.
[I 2025-07-12 00:01:16,494] A new study created in memory with name: no-name-b58c92f6-9c7c-417d-a097-f73fe9b69e42

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.45 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.92 | R2: 0.29
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.71 | R2: 0.39

✅ SVR - Mejor R2: 0.50
📋 Parámetros: {'kernel': 'rbf', 'C': 9.929439307242298, 'epsilon': 0.1849685814692066, 'gamma': 'auto'}

Buscando mejores hiperparámetros para KNN...
Fold 1
Fold 2

[I 2025-07-12 00:01:16,563] Trial 0 finished with value: 0.4506184579511564 and parameters: {'n_neighbors': 15, 'weights': 'uniform', 'leaf_size': 12}. Best is trial 0 with value: 0.4506184579511564.
[I 2025-07-12 00:01:16,629] Trial 1 finished with value: 0.6501906160143576 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'leaf_size': 36}. Best is trial 1 with value: 0.6501906160143576.
[I 2025-07-12 00:01:16,697] Trial 2 finished with value: 0.47319667525473896 and parameters: {'n_neighbors': 14, 'weights': 'uniform', 'leaf_size': 11}. Best is trial 1 with value: 0.6501906160143576.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.57 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.05 | R2: 0.65
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.52 | R2: 0.47
Fold 1
Fold 2

[I 2025-07-12 00:01:16,766] Trial 3 finished with value: 0.6521770671808476 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 11}. Best is trial 3 with value: 0.6521770671808476.
[I 2025-07-12 00:01:16,834] Trial 4 finished with value: 0.5840878747113054 and parameters: {'n_neighbors': 10, 'weights': 'distance', 'leaf_size': 10}. Best is trial 3 with value: 0.6521770671808476.
[I 2025-07-12 00:01:16,899] Trial 5 finished with value: 0.5840878747113054 and parameters: {'n_neighbors': 10, 'weights': 'distance', 'leaf_size': 38}. Best is trial 3 with value: 0.6521770671808476.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.04 | R2: 0.65
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.24 | R2: 0.58
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.24 | R2: 0.58
Fold 1
Fold 2
Fold 3

[I 2025-07-12 00:01:16,967] Trial 6 finished with value: 0.5462404311902199 and parameters: {'n_neighbors': 14, 'weights': 'distance', 'leaf_size': 26}. Best is trial 3 with value: 0.6521770671808476.
[I 2025-07-12 00:01:17,038] Trial 7 finished with value: 0.5145198749731885 and parameters: {'n_neighbors': 8, 'weights': 'uniform', 'leaf_size': 26}. Best is trial 3 with value: 0.6521770671808476.
[I 2025-07-12 00:01:17,128] Trial 8 finished with value: 0.589970907733965 and parameters: {'n_neighbors': 5, 'weights': 'uniform', 'leaf_size': 18}. Best is trial 3 with value: 0.6521770671808476.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.34 | R2: 0.55
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.42 | R2: 0.51
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.22 | R2: 0.59
Fold 1

[I 2025-07-12 00:01:17,205] Trial 9 finished with value: 0.589970907733965 and parameters: {'n_neighbors': 5, 'weights': 'uniform', 'leaf_size': 10}. Best is trial 3 with value: 0.6521770671808476.
[I 2025-07-12 00:01:17,286] Trial 10 finished with value: 0.593235136095625 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'leaf_size': 20}. Best is trial 3 with value: 0.6521770671808476.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.22 | R2: 0.59
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.21 | R2: 0.59
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-12 00:01:17,358] Trial 11 finished with value: 0.6521770671808476 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 37}. Best is trial 3 with value: 0.6521770671808476.
[I 2025-07-12 00:01:17,431] Trial 12 finished with value: 0.6521770671808476 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 32}. Best is trial 3 with value: 0.6521770671808476.
[I 2025-07-12 00:01:17,503] Trial 13 finished with value: 0.6292069342222804 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'leaf_size': 31}. Best is trial 3 with value: 0.6521770671808476.

Running time: 0.1 sec
OOF RMSE: 2.04 | R2: 0.65
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.04 | R2: 0.65
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.11 | R2: 0.63
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-12 00:01:17,579] Trial 14 finished with value: 0.6521770671808476 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 18}. Best is trial 3 with value: 0.6521770671808476.
[I 2025-07-12 00:01:17,654] Trial 15 finished with value: 0.6136025896509423 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'leaf_size': 32}. Best is trial 3 with value: 0.6521770671808476.
[I 2025-07-12 00:01:17,728] Trial 16 finished with value: 0.5725869336167564 and parameters: {'n_neighbors': 11, 'weights': 'distance', 'leaf_size': 23}. Best is trial 3 with value: 0.6521770671808476.

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.04 | R2: 0.65
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.15 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.27 | R2: 0.57
Fold 1
Fold 2
Fold 3

[I 2025-07-12 00:01:17,806] Trial 17 finished with value: 0.6367746732116242 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'leaf_size': 40}. Best is trial 3 with value: 0.6521770671808476.
[I 2025-07-12 00:01:17,879] Trial 18 finished with value: 0.593235136095625 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'leaf_size': 14}. Best is trial 3 with value: 0.6521770671808476.
[I 2025-07-12 00:01:17,958] Trial 19 finished with value: 0.5671567196558591 and parameters: {'n_neighbors': 12, 'weights': 'distance', 'leaf_size': 29}. Best is trial 3 with value: 0.6521770671808476.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.09 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.21 | R2: 0.59
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.28 | R2: 0.57
Fold 1

[I 2025-07-12 00:01:18,030] Trial 20 finished with value: 0.593235136095625 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'leaf_size': 36}. Best is trial 3 with value: 0.6521770671808476.
[I 2025-07-12 00:01:18,104] Trial 21 finished with value: 0.6521770671808476 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 34}. Best is trial 3 with value: 0.6521770671808476.
[I 2025-07-12 00:01:18,179] Trial 22 finished with value: 0.6367746732116242 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'leaf_size': 29}. Best is trial 3 with value: 0.6521770671808476.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.21 | R2: 0.59
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.04 | R2: 0.65
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.09 | R2: 0.64

[I 2025-07-12 00:01:18,255] Trial 23 finished with value: 0.6367746732116242 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'leaf_size': 34}. Best is trial 3 with value: 0.6521770671808476.
[I 2025-07-12 00:01:18,330] Trial 24 finished with value: 0.6521770671808476 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 39}. Best is trial 3 with value: 0.6521770671808476.
[I 2025-07-12 00:01:18,331] A new study created in memory with name: no-name-09ee7bf2-650e-491a-94a0-d6c532bda369

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.09 | R2: 0.64
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.04 | R2: 0.65

✅ KNN - Mejor R2: 0.65
📋 Parámetros: {'n_neighbors': 3, 'weights': 'distance', 'leaf_size': 11}

Buscando mejores hiperparámetros para LR...
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-12 00:01:18,431] Trial 0 finished with value: -1.220475949352716 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 0 with value: -1.220475949352716.
[I 2025-07-12 00:01:18,514] Trial 1 finished with value: 0.24177183094951804 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.24177183094951804.
[I 2025-07-12 00:01:18,580] Trial 2 finished with value: 0.24177183094951527 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 1 with value: 0.24177183094951804.

Fold 5
Running time: 0.1 sec
OOF RMSE: 5.17 | R2: -1.22
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.02 | R2: 0.24
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.02 | R2: 0.24
Fold 1
Fold 2
Fold 3

[I 2025-07-12 00:01:18,644] Trial 3 finished with value: 0.24177183094951804 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.24177183094951804.
[I 2025-07-12 00:01:18,706] Trial 4 finished with value: 0.24177183094951527 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 1 with value: 0.24177183094951804.
[I 2025-07-12 00:01:18,774] Trial 5 finished with value: 0.24177183094951527 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 1 with value: 0.24177183094951804.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.02 | R2: 0.24
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.02 | R2: 0.24
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.02 | R2: 0.24
Fold 1
Fold 2
Fold 3

[I 2025-07-12 00:01:18,867] Trial 6 finished with value: -1.2204759494505701 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 1 with value: 0.24177183094951804.
[I 2025-07-12 00:01:18,952] Trial 7 finished with value: 0.24177183094951804 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.24177183094951804.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 5.17 | R2: -1.22
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.02 | R2: 0.24
Fold 1
Fold 2
Fold 3

[I 2025-07-12 00:01:19,089] Trial 8 finished with value: -1.2204759494505701 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 1 with value: 0.24177183094951804.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 5.17 | R2: -1.22
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-12 00:01:19,252] Trial 9 finished with value: -1.220475949352716 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 1 with value: 0.24177183094951804.
[I 2025-07-12 00:01:19,333] Trial 10 finished with value: 0.24177183094951804 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.24177183094951804.
[I 2025-07-12 00:01:19,398] Trial 11 finished with value: 0.24177183094951804 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.24177183094951804.

Running time: 0.2 sec
OOF RMSE: 5.17 | R2: -1.22
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.02 | R2: 0.24
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.02 | R2: 0.24
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-12 00:01:19,468] Trial 12 finished with value: 0.24177183094951804 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.24177183094951804.
[I 2025-07-12 00:01:19,540] Trial 13 finished with value: 0.24177183094951804 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.24177183094951804.
[I 2025-07-12 00:01:19,605] Trial 14 finished with value: 0.24177183094951804 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.24177183094951804.

Fold 5
Running time: 0.1 sec
OOF RMSE: 3.02 | R2: 0.24
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.02 | R2: 0.24
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.02 | R2: 0.24
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-12 00:01:19,666] Trial 15 finished with value: 0.24177183094951804 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.24177183094951804.
[I 2025-07-12 00:01:19,731] Trial 16 finished with value: 0.24177183094951804 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.24177183094951804.
[I 2025-07-12 00:01:19,794] Trial 17 finished with value: 0.24177183094951804 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.24177183094951804.

Running time: 0.1 sec
OOF RMSE: 3.02 | R2: 0.24
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.02 | R2: 0.24
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.02 | R2: 0.24
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-12 00:01:19,879] Trial 18 finished with value: -1.220475949352716 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 1 with value: 0.24177183094951804.
[I 2025-07-12 00:01:19,963] Trial 19 finished with value: 0.24177183094951804 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.24177183094951804.
[I 2025-07-12 00:01:20,028] Trial 20 finished with value: 0.24177183094951804 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.24177183094951804.

Running time: 0.1 sec
OOF RMSE: 5.17 | R2: -1.22
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.02 | R2: 0.24
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.02 | R2: 0.24
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-12 00:01:20,091] Trial 21 finished with value: 0.24177183094951804 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.24177183094951804.
[I 2025-07-12 00:01:20,174] Trial 22 finished with value: 0.24177183094951804 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.24177183094951804.
[I 2025-07-12 00:01:20,242] Trial 23 finished with value: 0.24177183094951804 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.24177183094951804.

Running time: 0.1 sec
OOF RMSE: 3.02 | R2: 0.24
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.02 | R2: 0.24
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.02 | R2: 0.24
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-12 00:01:20,304] Trial 24 finished with value: 0.24177183094951804 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.24177183094951804.
[I 2025-07-12 00:01:20,305] A new study created in memory with name: no-name-207b0be7-738c-4e6f-8f6a-ed92fbfceb6b

Running time: 0.1 sec
OOF RMSE: 3.02 | R2: 0.24

✅ LR - Mejor R2: 0.24
📋 Parámetros: {'fit_intercept': False, 'positive': True}

Buscando mejores hiperparámetros para RF...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-12 00:01:28,475] Trial 0 finished with value: 0.45446822141160514 and parameters: {'n_estimators': 300, 'max_depth': 13, 'min_samples_split': 9, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 0 with value: 0.45446822141160514.

Running time: 8.2 sec
OOF RMSE: 2.56 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-12 00:01:30,225] Trial 1 finished with value: 0.38249705510601306 and parameters: {'n_estimators': 100, 'max_depth': 5, 'min_samples_split': 2, 'min_samples_leaf': 4, 'bootstrap': False}. Best is trial 0 with value: 0.45446822141160514.

Running time: 1.7 sec
OOF RMSE: 2.72 | R2: 0.38
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-12 00:01:35,285] Trial 2 finished with value: 0.5379164598837376 and parameters: {'n_estimators': 300, 'max_depth': 14, 'min_samples_split': 2, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 2 with value: 0.5379164598837376.

Running time: 5.1 sec
OOF RMSE: 2.36 | R2: 0.54
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-12 00:01:46,134] Trial 3 finished with value: 0.37151746682686504 and parameters: {'n_estimators': 500, 'max_depth': 8, 'min_samples_split': 3, 'min_samples_leaf': 5, 'bootstrap': False}. Best is trial 2 with value: 0.5379164598837376.

Running time: 10.8 sec
OOF RMSE: 2.75 | R2: 0.37
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-12 00:01:51,195] Trial 4 finished with value: 0.5379164598837376 and parameters: {'n_estimators': 300, 'max_depth': 14, 'min_samples_split': 5, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 2 with value: 0.5379164598837376.

Running time: 5.1 sec
OOF RMSE: 2.36 | R2: 0.54
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-12 00:01:55,460] Trial 5 finished with value: 0.5009519594277212 and parameters: {'n_estimators': 300, 'max_depth': 13, 'min_samples_split': 10, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 2 with value: 0.5379164598837376.

Running time: 4.3 sec
OOF RMSE: 2.45 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-12 00:01:56,921] Trial 6 finished with value: 0.5081278608435934 and parameters: {'n_estimators': 100, 'max_depth': 14, 'min_samples_split': 9, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 2 with value: 0.5379164598837376.

Running time: 1.5 sec
OOF RMSE: 2.43 | R2: 0.51
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-12 00:01:58,384] Trial 7 finished with value: 0.5081278608435934 and parameters: {'n_estimators': 100, 'max_depth': 14, 'min_samples_split': 9, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 2 with value: 0.5379164598837376.

Running time: 1.5 sec
OOF RMSE: 2.43 | R2: 0.51
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-12 00:02:01,257] Trial 8 finished with value: 0.4022604191803679 and parameters: {'n_estimators': 100, 'max_depth': 10, 'min_samples_split': 3, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 2 with value: 0.5379164598837376.

Running time: 2.9 sec
OOF RMSE: 2.68 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-12 00:02:03,214] Trial 9 finished with value: 0.5446822567091334 and parameters: {'n_estimators': 100, 'max_depth': 12, 'min_samples_split': 6, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 9 with value: 0.5446822567091334.

Running time: 2.0 sec
OOF RMSE: 2.34 | R2: 0.54
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-12 00:02:12,718] Trial 10 finished with value: 0.5525360213950299 and parameters: {'n_estimators': 500, 'max_depth': 11, 'min_samples_split': 6, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 10 with value: 0.5525360213950299.

Running time: 9.5 sec
OOF RMSE: 2.32 | R2: 0.55
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-12 00:02:22,233] Trial 11 finished with value: 0.5525360213950299 and parameters: {'n_estimators': 500, 'max_depth': 11, 'min_samples_split': 6, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 10 with value: 0.5525360213950299.

Running time: 9.5 sec
OOF RMSE: 2.32 | R2: 0.55
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-12 00:02:30,899] Trial 12 finished with value: 0.5461316896130692 and parameters: {'n_estimators': 500, 'max_depth': 10, 'min_samples_split': 7, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 10 with value: 0.5525360213950299.

Running time: 8.7 sec
OOF RMSE: 2.34 | R2: 0.55
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-12 00:02:39,517] Trial 13 finished with value: 0.5579711493806554 and parameters: {'n_estimators': 500, 'max_depth': 8, 'min_samples_split': 5, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 13 with value: 0.5579711493806554.

Running time: 8.6 sec
OOF RMSE: 2.30 | R2: 0.56
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-12 00:02:47,743] Trial 14 finished with value: 0.5566520141362152 and parameters: {'n_estimators': 500, 'max_depth': 8, 'min_samples_split': 5, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 13 with value: 0.5579711493806554.

Running time: 8.2 sec
OOF RMSE: 2.31 | R2: 0.56
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-12 00:02:55,540] Trial 15 finished with value: 0.5563730058166337 and parameters: {'n_estimators': 500, 'max_depth': 7, 'min_samples_split': 4, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 13 with value: 0.5579711493806554.

Running time: 7.8 sec
OOF RMSE: 2.31 | R2: 0.56
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-12 00:03:03,876] Trial 16 finished with value: 0.5561394793785007 and parameters: {'n_estimators': 500, 'max_depth': 8, 'min_samples_split': 4, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 13 with value: 0.5579711493806554.

Running time: 8.3 sec
OOF RMSE: 2.31 | R2: 0.56
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-12 00:03:10,948] Trial 17 finished with value: 0.546052044999676 and parameters: {'n_estimators': 500, 'max_depth': 6, 'min_samples_split': 7, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 13 with value: 0.5579711493806554.

Running time: 7.1 sec
OOF RMSE: 2.34 | R2: 0.55
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-12 00:03:22,418] Trial 18 finished with value: 0.4297092897093845 and parameters: {'n_estimators': 500, 'max_depth': 8, 'min_samples_split': 5, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 13 with value: 0.5579711493806554.

Running time: 11.5 sec
OOF RMSE: 2.62 | R2: 0.43
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-12 00:03:29,975] Trial 19 finished with value: 0.5185281156128236 and parameters: {'n_estimators': 500, 'max_depth': 9, 'min_samples_split': 7, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 13 with value: 0.5579711493806554.

Running time: 7.6 sec
OOF RMSE: 2.41 | R2: 0.52
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-12 00:03:37,311] Trial 20 finished with value: 0.556954314206252 and parameters: {'n_estimators': 500, 'max_depth': 6, 'min_samples_split': 5, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 13 with value: 0.5579711493806554.

Running time: 7.3 sec
OOF RMSE: 2.31 | R2: 0.56
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-12 00:03:44,789] Trial 21 finished with value: 0.556954314206252 and parameters: {'n_estimators': 500, 'max_depth': 6, 'min_samples_split': 5, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 13 with value: 0.5579711493806554.

Running time: 7.5 sec
OOF RMSE: 2.31 | R2: 0.56
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-12 00:03:51,417] Trial 22 finished with value: 0.5562193352005207 and parameters: {'n_estimators': 500, 'max_depth': 5, 'min_samples_split': 4, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 13 with value: 0.5579711493806554.

Running time: 6.6 sec
OOF RMSE: 2.31 | R2: 0.56
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-12 00:03:58,876] Trial 23 finished with value: 0.556954314206252 and parameters: {'n_estimators': 500, 'max_depth': 6, 'min_samples_split': 5, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 13 with value: 0.5579711493806554.

Running time: 7.5 sec
OOF RMSE: 2.31 | R2: 0.56
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-12 00:04:06,261] Trial 24 finished with value: 0.5577479563345489 and parameters: {'n_estimators': 500, 'max_depth': 6, 'min_samples_split': 3, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 13 with value: 0.5579711493806554.
[I 2025-07-12 00:04:06,263] A new study created in memory with name: no-name-72431406-1e6b-4731-8079-1f4b1d6150c9

Running time: 7.4 sec
OOF RMSE: 2.31 | R2: 0.56

✅ RF - Mejor R2: 0.56
📋 Parámetros: {'n_estimators': 500, 'max_depth': 8, 'min_samples_split': 5, 'min_samples_leaf': 1, 'bootstrap': True}

Buscando mejores hiperparámetros para CAT...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-12 00:08:58,792] Trial 0 finished with value: 0.5867350725307436 and parameters: {'iterations': 2000, 'learning_rate': 0.019917025656983937, 'depth': 10, 'l2_leaf_reg': 8.10323497021735}. Best is trial 0 with value: 0.5867350725307436.

Running time: 292.5 sec
OOF RMSE: 2.23 | R2: 0.59
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-12 00:09:13,510] Trial 1 finished with value: 0.593944577659707 and parameters: {'iterations': 1000, 'learning_rate': 0.015135517997686686, 'depth': 7, 'l2_leaf_reg': 7.11788594763764}. Best is trial 1 with value: 0.593944577659707.

Running time: 14.7 sec
OOF RMSE: 2.21 | R2: 0.59
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-12 00:09:19,681] Trial 2 finished with value: 0.5762748144878975 and parameters: {'iterations': 2000, 'learning_rate': 0.010733199688349031, 'depth': 4, 'l2_leaf_reg': 3.820740510726783}. Best is trial 1 with value: 0.593944577659707.

Running time: 6.2 sec
OOF RMSE: 2.26 | R2: 0.58
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-12 00:09:28,731] Trial 3 finished with value: 0.5743088407698643 and parameters: {'iterations': 2000, 'learning_rate': 0.025702649093182005, 'depth': 5, 'l2_leaf_reg': 4.485683447949379}. Best is trial 1 with value: 0.593944577659707.

Running time: 9.0 sec
OOF RMSE: 2.26 | R2: 0.57
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-12 00:10:10,699] Trial 4 finished with value: 0.5678986843168765 and parameters: {'iterations': 500, 'learning_rate': 0.011154757459951072, 'depth': 9, 'l2_leaf_reg': 7.522831023770238}. Best is trial 1 with value: 0.593944577659707.

Running time: 42.0 sec
OOF RMSE: 2.28 | R2: 0.57
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-12 00:11:24,698] Trial 5 finished with value: 0.6059509453118133 and parameters: {'iterations': 500, 'learning_rate': 0.036510013721448895, 'depth': 10, 'l2_leaf_reg': 1.8159772760737423}. Best is trial 5 with value: 0.6059509453118133.

Running time: 74.0 sec
OOF RMSE: 2.18 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-12 00:12:38,802] Trial 6 finished with value: 0.6121380752035458 and parameters: {'iterations': 500, 'learning_rate': 0.0648143718040294, 'depth': 10, 'l2_leaf_reg': 2.9188928099974647}. Best is trial 6 with value: 0.6121380752035458.

Running time: 74.1 sec
OOF RMSE: 2.16 | R2: 0.61
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-12 00:15:30,697] Trial 7 finished with value: 0.5844672545192774 and parameters: {'iterations': 2000, 'learning_rate': 0.022325589060725716, 'depth': 9, 'l2_leaf_reg': 9.60303595381234}. Best is trial 6 with value: 0.6121380752035458.
[I 2025-07-12 00:15:30,698] A new study created in memory with name: no-name-54fd26d2-24b3-4136-a4cf-afddf103c721
[I 2025-07-12 00:15:30,777] Trial 0 finished with value: 0.07762104569566275 and parameters: {'alpha': 4.585619210527065, 'l1_ratio': 0.3554133600620284}. Best is trial 0 with value: 0.07762104569566275.

Running time: 171.9 sec
OOF RMSE: 2.23 | R2: 0.58

✅ CAT - Mejor R2: 0.61
📋 Parámetros: {'iterations': 500, 'learning_rate': 0.0648143718040294, 'depth': 10, 'l2_leaf_reg': 2.9188928099974647}

Buscando mejores hiperparámetros para EN...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.33 | R2: 0.08
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.147e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.689e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.886e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.558e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.000e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-12 00:15:30,946] Trial 1 finished with value: 0.23050086018400584 and parameters: {'alpha': 0.000465187450062331, 'l1_ratio': 0.2720008379835791}. Best is trial 1 with value: 0.23050086018400584.
[I 2025-07-12 00:15:31,055] Trial 2 finished with value: 0.4629125430985872 and parameters: {'alpha': 0.13989327404343094, 'l1_ratio': 0.4962711728770207}. Best is trial 2 with value: 0.4629125430985872.

Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 3.04 | R2: 0.23
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.54 | R2: 0.46
Fold 1
Fold 2

[I 2025-07-12 00:15:31,181] Trial 3 finished with value: 0.08767997810913031 and parameters: {'alpha': 2.8727774798264045, 'l1_ratio': 0.6086675148612222}. Best is trial 2 with value: 0.4629125430985872.
[I 2025-07-12 00:15:31,274] Trial 4 finished with value: 0.30513647157806933 and parameters: {'alpha': 7.824374990703551, 'l1_ratio': 0.03458918082363127}. Best is trial 2 with value: 0.4629125430985872.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 3.31 | R2: 0.09
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.89 | R2: 0.31
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.509e+01, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.830e+01, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.156e+01, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.318e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.695e+01, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-12 00:15:31,394] Trial 5 finished with value: 0.41996779120471295 and parameters: {'alpha': 0.006742361398659899, 'l1_ratio': 0.46841493244378074}. Best is trial 2 with value: 0.4629125430985872.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.090e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.714e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.902e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.64 | R2: 0.42
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.527e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.931e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-12 00:15:31,545] Trial 6 finished with value: 0.17596479947620858 and parameters: {'alpha': 0.00014223777229594264, 'l1_ratio': 0.675560320392686}. Best is trial 2 with value: 0.4629125430985872.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.423e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.176e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.176e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.431e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.441e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-12 00:15:31,672] Trial 7 finished with value: 0.4470051696989288 and parameters: {'alpha': 0.011343002647432847, 'l1_ratio': 0.07548497660410425}. Best is trial 2 with value: 0.4629125430985872.

Running time: 0.1 sec
OOF RMSE: 3.15 | R2: 0.18
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.58 | R2: 0.45
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-07-12 00:15:31,766] Trial 8 finished with value: 0.2831800730968064 and parameters: {'alpha': 3.3301131859221593, 'l1_ratio': 0.21761353054619215}. Best is trial 2 with value: 0.4629125430985872.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.390e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.967e+02, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.196e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.873e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.321e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-12 00:15:31,887] Trial 9 finished with value: 0.268258892895083 and parameters: {'alpha': 0.000699429625339174, 'l1_ratio': 0.020938593156143326}. Best is trial 2 with value: 0.4629125430985872.

Fold 5
Running time: 0.1 sec
OOF RMSE: 2.93 | R2: 0.28
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.97 | R2: 0.27
Fold 1
Fold 2
Fold 3

[I 2025-07-12 00:15:31,982] Trial 10 finished with value: 0.42524688418888557 and parameters: {'alpha': 0.26754191421292073, 'l1_ratio': 0.9145483955995946}. Best is trial 2 with value: 0.4629125430985872.
[I 2025-07-12 00:15:32,078] Trial 11 finished with value: 0.4983114556060523 and parameters: {'alpha': 0.054821303251896505, 'l1_ratio': 0.87496425156956}. Best is trial 11 with value: 0.4983114556060523.

Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.63 | R2: 0.43
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.46 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-12 00:15:32,189] Trial 12 finished with value: 0.46160368278076946 and parameters: {'alpha': 0.11829902780265024, 'l1_ratio': 0.997240113780162}. Best is trial 11 with value: 0.4983114556060523.
[I 2025-07-12 00:15:32,299] Trial 13 finished with value: 0.43752041891292315 and parameters: {'alpha': 0.19378994498669203, 'l1_ratio': 0.7903730690806923}. Best is trial 11 with value: 0.4983114556060523.

Running time: 0.1 sec
OOF RMSE: 2.54 | R2: 0.46
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.60 | R2: 0.44
Fold 1
Fold 2
Fold 3

[I 2025-07-12 00:15:32,474] Trial 14 finished with value: 0.4932322886108579 and parameters: {'alpha': 0.04474102511851476, 'l1_ratio': 0.4898763550441401}. Best is trial 11 with value: 0.4983114556060523.

Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 2.47 | R2: 0.49
Fold 1
Fold 2
Fold 3

[I 2025-07-12 00:15:32,671] Trial 15 finished with value: 0.4738457110225247 and parameters: {'alpha': 0.02215454293350301, 'l1_ratio': 0.7479970550899172}. Best is trial 11 with value: 0.4983114556060523.

Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 2.51 | R2: 0.47
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.243e+02, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.387e+01, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.559e+02, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.764e+02, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.103e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-12 00:15:32,871] Trial 16 finished with value: 0.35633329434393035 and parameters: {'alpha': 0.002997450063254026, 'l1_ratio': 0.5777577346509275}. Best is trial 11 with value: 0.4983114556060523.
[I 2025-07-12 00:15:32,989] Trial 17 finished with value: 0.3830364311373683 and parameters: {'alpha': 0.9742457405650541, 'l1_ratio': 0.38782999578459265}. Best is trial 11 with value: 0.4983114556060523.

Fold 5
Running time: 0.2 sec
OOF RMSE: 2.78 | R2: 0.36
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.72 | R2: 0.38
Fold 1
Fold 2

[I 2025-07-12 00:15:33,110] Trial 18 finished with value: 0.4971098192410165 and parameters: {'alpha': 0.05248122577434057, 'l1_ratio': 0.8014082390182126}. Best is trial 11 with value: 0.4983114556060523.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.46 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-12 00:15:33,265] Trial 19 finished with value: 0.40096497641808315 and parameters: {'alpha': 0.511607231316209, 'l1_ratio': 0.845137267742884}. Best is trial 11 with value: 0.4983114556060523.
[I 2025-07-12 00:15:33,432] Trial 20 finished with value: 0.4938018544541617 and parameters: {'alpha': 0.04098675874267865, 'l1_ratio': 0.9772965285090731}. Best is trial 11 with value: 0.4983114556060523.

Running time: 0.1 sec
OOF RMSE: 2.68 | R2: 0.40
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 2.47 | R2: 0.49
Fold 1

[I 2025-07-12 00:15:33,604] Trial 21 finished with value: 0.49550495641949965 and parameters: {'alpha': 0.04380262794751761, 'l1_ratio': 0.9800973104697819}. Best is trial 11 with value: 0.4983114556060523.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 2.46 | R2: 0.50
Fold 1
Fold 2
Fold 3

[I 2025-07-12 00:15:33,787] Trial 22 finished with value: 0.4987277084446985 and parameters: {'alpha': 0.05609674554093761, 'l1_ratio': 0.8826939390659186}. Best is trial 22 with value: 0.4987277084446985.

Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 2.45 | R2: 0.50
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.842e+01, tolerance: 2.084e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.758e+01, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.731e+01, tolerance: 2.029e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.940e+01, tolerance: 2.248e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.057e+02, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-12 00:15:33,980] Trial 23 finished with value: 0.3503865695136529 and parameters: {'alpha': 0.0034070013297747034, 'l1_ratio': 0.8156366683346599}. Best is trial 22 with value: 0.4987277084446985.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.788e-01, tolerance: 2.025e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.724e+00, tolerance: 2.730e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-07-12 00:15:34,120] Trial 24 finished with value: 0.46229566651466014 and parameters: {'alpha': 0.016167323878849213, 'l1_ratio': 0.701811448473339}. Best is trial 22 with value: 0.4987277084446985.

Fold 5
Running time: 0.2 sec
OOF RMSE: 2.79 | R2: 0.35
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.54 | R2: 0.46

✅ EN - Mejor R2: 0.50
📋 Parámetros: {'alpha': 0.05609674554093761, 'l1_ratio': 0.8826939390659186}

In [294]:
with open("global_results.pkl", "wb") as f:
    pickle.dump(global_results, f)

In [295]:
global_results

{('C2RCC_rhow_5x5_depth_lt_1',
  'XGB'): {'best_params': {'n_estimators': 1000,
   'learning_rate': 0.008490905014217147,
   'max_depth': 6,
   'min_child_weight': 3,
   'subsample': 0.9117231361249971,
   'colsample_bytree': 0.7381845712236873}, 'best_score': 0.6977084098853871, 'study': <optuna.study.study.Study at 0x769648cc2b80>},
 ('C2RCC_rhow_5x5_depth_lt_1',
  'LBM'): {'best_params': {'learning_rate': 0.02073824304970037,
   'num_leaves': 60,
   'max_depth': 8,
   'min_child_samples': 5,
   'subsample': 0.9938714541767556,
   'colsample_bytree': 0.7278831706716934,
   'n_estimators': 2000}, 'best_score': 0.667321133437436, 'study': <optuna.study.study.Study at 0x76963b8dd490>},
 ('C2RCC_rhow_5x5_depth_lt_1',
  'MLP'): {'best_params': {'hidden_layer_sizes': '128_64',
   'activation': 'tanh',
   'solver': 'adam',
   'alpha': 0.005677603912486301,
   'learning_rate': 'adaptive',
   'learning_rate_init': 0.004569000726524064}, 'best_score': 0.6988355877442272, 'study': <optuna.study.study.Study at 0x76963b712a60>},
 ('C2RCC_rhow_5x5_depth_lt_1',
  'SVR'): {'best_params': {'kernel': 'rbf',
   'C': 9.973087703929847,
   'epsilon': 0.06464202847072528,
   'gamma': 'scale'}, 'best_score': 0.585376445090346, 'study': <optuna.study.study.Study at 0x76963b8f11c0>},
 ('C2RCC_rhow_5x5_depth_lt_1',
  'KNN'): {'best_params': {'n_neighbors': 3,
   'weights': 'distance',
   'leaf_size': 40}, 'best_score': 0.7881537821929324, 'study': <optuna.study.study.Study at 0x76963b92e220>},
 ('C2RCC_rhow_5x5_depth_lt_1',
  'LR'): {'best_params': {'fit_intercept': True,
   'positive': True}, 'best_score': 0.34765539553365565, 'study': <optuna.study.study.Study at 0x76963b75cbe0>},
 ('C2RCC_rhow_5x5_depth_lt_1',
  'RF'): {'best_params': {'n_estimators': 100,
   'max_depth': 14,
   'min_samples_split': 10,
   'min_samples_leaf': 3,
   'bootstrap': False}, 'best_score': 0.6558410067121344, 'study': <optuna.study.study.Study at 0x76963b768f10>},
 ('C2RCC_rhow_5x5_depth_lt_1',
  'CAT'): {'best_params': {'iterations': 2000,
   'learning_rate': 0.05210869822845941,
   'depth': 7,
   'l2_leaf_reg': 4.122617409966653}, 'best_score': 0.7117095594085446, 'study': <optuna.study.study.Study at 0x76963b72cc10>},
 ('C2RCC_rhow_5x5_depth_lt_1',
  'EN'): {'best_params': {'alpha': 0.03976939481572569,
   'l1_ratio': 0.8424265339854451}, 'best_score': 0.5321671127533365, 'study': <optuna.study.study.Study at 0x76963b72fa00>},
 ('C2X-Complex_rhown_3x3_depth_lt_1',
  'XGB'): {'best_params': {'n_estimators': 2000,
   'learning_rate': 0.05883287671138505,
   'max_depth': 5,
   'min_child_weight': 2,
   'subsample': 0.8838687864977884,
   'colsample_bytree': 0.6032440232711282}, 'best_score': 0.6568430977739732, 'study': <optuna.study.study.Study at 0x76963b72d9a0>},
 ('C2X-Complex_rhown_3x3_depth_lt_1',
  'LBM'): {'best_params': {'learning_rate': 0.04162474407952709,
   'num_leaves': 40,
   'max_depth': 5,
   'min_child_samples': 5,
   'subsample': 0.9266985587468115,
   'colsample_bytree': 0.7248233128276992,
   'n_estimators': 2000}, 'best_score': 0.6574985310707853, 'study': <optuna.study.study.Study at 0x76963babea60>},
 ('C2X-Complex_rhown_3x3_depth_lt_1',
  'MLP'): {'best_params': {'hidden_layer_sizes': '100_50',
   'activation': 'tanh',
   'solver': 'adam',
   'alpha': 0.0007892560801364265,
   'learning_rate': 'constant',
   'learning_rate_init': 0.0030861230712521974}, 'best_score': 0.613640426476394, 'study': <optuna.study.study.Study at 0x76963b7c3970>},
 ('C2X-Complex_rhown_3x3_depth_lt_1',
  'SVR'): {'best_params': {'kernel': 'rbf',
   'C': 9.910598767358806,
   'epsilon': 0.19232584702065708,
   'gamma': 'auto'}, 'best_score': 0.4717009664080015, 'study': <optuna.study.study.Study at 0x76963b61e040>},
 ('C2X-Complex_rhown_3x3_depth_lt_1',
  'KNN'): {'best_params': {'n_neighbors': 3,
   'weights': 'distance',
   'leaf_size': 16}, 'best_score': 0.7012966245681302, 'study': <optuna.study.study.Study at 0x76963b54a760>},
 ('C2X-Complex_rhown_3x3_depth_lt_1',
  'LR'): {'best_params': {'fit_intercept': False,
   'positive': True}, 'best_score': -0.1495363584594449, 'study': <optuna.study.study.Study at 0x76963b7b51c0>},
 ('C2X-Complex_rhown_3x3_depth_lt_1',
  'RF'): {'best_params': {'n_estimators': 500,
   'max_depth': 10,
   'min_samples_split': 2,
   'min_samples_leaf': 1,
   'bootstrap': True}, 'best_score': 0.6046231595240374, 'study': <optuna.study.study.Study at 0x76963b837220>},
 ('C2X-Complex_rhown_3x3_depth_lt_1',
  'CAT'): {'best_params': {'iterations': 1000,
   'learning_rate': 0.022540257801375238,
   'depth': 9,
   'l2_leaf_reg': 1.133073971146791}, 'best_score': 0.708127026178391, 'study': <optuna.study.study.Study at 0x76963b7f0910>},
 ('C2X-Complex_rhown_3x3_depth_lt_1',
  'EN'): {'best_params': {'alpha': 0.09663056847398992,
   'l1_ratio': 0.1369199420011986}, 'best_score': 0.496557290116995, 'study': <optuna.study.study.Study at 0x76963b8f6070>},
 ('TOA_9x9_depth_lt_1',
  'XGB'): {'best_params': {'n_estimators': 500,
   'learning_rate': 0.03587187536212219,
   'max_depth': 8,
   'min_child_weight': 3,
   'subsample': 0.6414704974641332,
   'colsample_bytree': 0.6372324135122972}, 'best_score': 0.7510546854967972, 'study': <optuna.study.study.Study at 0x76963b87b730>},
 ('TOA_9x9_depth_lt_1',
  'LBM'): {'best_params': {'learning_rate': 0.04397213412834972,
   'num_leaves': 80,
   'max_depth': 6,
   'min_child_samples': 18,
   'subsample': 0.7359161631066482,
   'colsample_bytree': 0.7037071484276278,
   'n_estimators': 1000}, 'best_score': 0.7507228192950756, 'study': <optuna.study.study.Study at 0x76963bbf20d0>},
 ('TOA_9x9_depth_lt_1',
  'MLP'): {'best_params': {'hidden_layer_sizes': '128_64',
   'activation': 'relu',
   'solver': 'adam',
   'alpha': 4.942440869894174e-05,
   'learning_rate': 'adaptive',
   'learning_rate_init': 0.008991466183990703}, 'best_score': 0.753658164002937, 'study': <optuna.study.study.Study at 0x76963de26220>},
 ('TOA_9x9_depth_lt_1',
  'SVR'): {'best_params': {'kernel': 'rbf',
   'C': 9.972464370426488,
   'epsilon': 0.1390615243836335,
   'gamma': 'scale'}, 'best_score': 0.5776686845232404, 'study': <optuna.study.study.Study at 0x76963bb9d4f0>},
 ('TOA_9x9_depth_lt_1',
  'KNN'): {'best_params': {'n_neighbors': 3,
   'weights': 'distance',
   'leaf_size': 34}, 'best_score': 0.7889007264172183, 'study': <optuna.study.study.Study at 0x76963b805cd0>},
 ('TOA_9x9_depth_lt_1',
  'LR'): {'best_params': {'fit_intercept': False,
   'positive': True}, 'best_score': 0.21056516902481348, 'study': <optuna.study.study.Study at 0x76963b91dd60>},
 ('TOA_9x9_depth_lt_1',
  'RF'): {'best_params': {'n_estimators': 100,
   'max_depth': 10,
   'min_samples_split': 3,
   'min_samples_leaf': 1,
   'bootstrap': True}, 'best_score': 0.783606369853559, 'study': <optuna.study.study.Study at 0x76963dea84f0>},
 ('TOA_9x9_depth_lt_1',
  'CAT'): {'best_params': {'iterations': 500,
   'learning_rate': 0.05271300176975567,
   'depth': 8,
   'l2_leaf_reg': 1.17791064424655}, 'best_score': 0.8208954506904806, 'study': <optuna.study.study.Study at 0x76963e000430>},
 ('TOA_9x9_depth_lt_1',
  'EN'): {'best_params': {'alpha': 0.11724858580646791,
   'l1_ratio': 0.6392112277468219}, 'best_score': 0.19433741163378648, 'study': <optuna.study.study.Study at 0x76963e35bac0>},
 ('C2X_rhow_3x3_depth_lt_1',
  'XGB'): {'best_params': {'n_estimators': 2000,
   'learning_rate': 0.005073225186908113,
   'max_depth': 8,
   'min_child_weight': 4,
   'subsample': 0.6059690230568425,
   'colsample_bytree': 0.9542374874967058}, 'best_score': 0.4626729633693569, 'study': <optuna.study.study.Study at 0x76963e227ee0>},
 ('C2X_rhow_3x3_depth_lt_1',
  'LBM'): {'best_params': {'learning_rate': 0.005849380680569026,
   'num_leaves': 20,
   'max_depth': 7,
   'min_child_samples': 7,
   'subsample': 0.6122104334511537,
   'colsample_bytree': 0.7554534645600801,
   'n_estimators': 500}, 'best_score': 0.4841044867464147, 'study': <optuna.study.study.Study at 0x76963e22a0a0>},
 ('C2X_rhow_3x3_depth_lt_1',
  'MLP'): {'best_params': {'hidden_layer_sizes': '100',
   'activation': 'relu',
   'solver': 'adam',
   'alpha': 0.00013513916207160778,
   'learning_rate': 'adaptive',
   'learning_rate_init': 0.004133225692173275}, 'best_score': 0.44147982292583554, 'study': <optuna.study.study.Study at 0x76963e4b8be0>},
 ('C2X_rhow_3x3_depth_lt_1',
  'SVR'): {'best_params': {'kernel': 'rbf',
   'C': 7.926155854189685,
   'epsilon': 0.09039948325118322,
   'gamma': 'scale'}, 'best_score': 0.4048960366780281, 'study': <optuna.study.study.Study at 0x76963b624ac0>},
 ('C2X_rhow_3x3_depth_lt_1',
  'KNN'): {'best_params': {'n_neighbors': 11,
   'weights': 'distance',
   'leaf_size': 15}, 'best_score': 0.4860740106565894, 'study': <optuna.study.study.Study at 0x7696408bfe20>},
 ('C2X_rhow_3x3_depth_lt_1',
  'LR'): {'best_params': {'fit_intercept': False,
   'positive': True}, 'best_score': 0.30752474310345035, 'study': <optuna.study.study.Study at 0x76963b63c1c0>},
 ('C2X_rhow_3x3_depth_lt_1',
  'RF'): {'best_params': {'n_estimators': 300,
   'max_depth': 15,
   'min_samples_split': 4,
   'min_samples_leaf': 3,
   'bootstrap': True}, 'best_score': 0.39801167334890364, 'study': <optuna.study.study.Study at 0x76964335c040>},
 ('C2X_rhow_3x3_depth_lt_1',
  'CAT'): {'best_params': {'iterations': 2000,
   'learning_rate': 0.014055584655013302,
   'depth': 9,
   'l2_leaf_reg': 1.5655403361430114}, 'best_score': 0.5020901746821778, 'study': <optuna.study.study.Study at 0x76963b958fa0>},
 ('C2X_rhow_3x3_depth_lt_1',
  'EN'): {'best_params': {'alpha': 0.5852246372071594,
   'l1_ratio': 0.18267486333733565}, 'best_score': 0.42926146852697855, 'study': <optuna.study.study.Study at 0x76963b97fca0>},
 ('C2RCC_rhow_9x9_depth_lt_1',
  'XGB'): {'best_params': {'n_estimators': 500,
   'learning_rate': 0.030745077375263705,
   'max_depth': 7,
   'min_child_weight': 1,
   'subsample': 0.8042059735991965,
   'colsample_bytree': 0.7511243939675886}, 'best_score': 0.6444636050148718, 'study': <optuna.study.study.Study at 0x76963e00c670>},
 ('C2RCC_rhow_9x9_depth_lt_1',
  'LBM'): {'best_params': {'learning_rate': 0.04405372538922755,
   'num_leaves': 80,
   'max_depth': 7,
   'min_child_samples': 25,
   'subsample': 0.9482342769195646,
   'colsample_bytree': 0.6529119045727767,
   'n_estimators': 500}, 'best_score': 0.5500419427436437, 'study': <optuna.study.study.Study at 0x76963dea8a90>},
 ('C2RCC_rhow_9x9_depth_lt_1',
  'MLP'): {'best_params': {'hidden_layer_sizes': '128_64',
   'activation': 'relu',
   'solver': 'adam',
   'alpha': 0.00018774819440246876,
   'learning_rate': 'adaptive',
   'learning_rate_init': 0.009661697868037085}, 'best_score': 0.6490654760594676, 'study': <optuna.study.study.Study at 0x76963e003460>},
 ('C2RCC_rhow_9x9_depth_lt_1',
  'SVR'): {'best_params': {'kernel': 'rbf',
   'C': 9.368015046738579,
   'epsilon': 0.14260568400950718,
   'gamma': 'scale'}, 'best_score': 0.5988876884756753, 'study': <optuna.study.study.Study at 0x76963df14c70>},
 ('C2RCC_rhow_9x9_depth_lt_1',
  'KNN'): {'best_params': {'n_neighbors': 5,
   'weights': 'distance',
   'leaf_size': 33}, 'best_score': 0.7092765392463615, 'study': <optuna.study.study.Study at 0x769643350f40>},
 ('C2RCC_rhow_9x9_depth_lt_1',
  'LR'): {'best_params': {'fit_intercept': False,
   'positive': True}, 'best_score': 0.48281540786635824, 'study': <optuna.study.study.Study at 0x76963e034a60>},
 ('C2RCC_rhow_9x9_depth_lt_1',
  'RF'): {'best_params': {'n_estimators': 500,
   'max_depth': 13,
   'min_samples_split': 4,
   'min_samples_leaf': 1,
   'bootstrap': True}, 'best_score': 0.6015823824498082, 'study': <optuna.study.study.Study at 0x76963e4bc6d0>},
 ('C2RCC_rhow_9x9_depth_lt_1',
  'CAT'): {'best_params': {'iterations': 500,
   'learning_rate': 0.013155008682611538,
   'depth': 9,
   'l2_leaf_reg': 1.076857263603094}, 'best_score': 0.6668137901970955, 'study': <optuna.study.study.Study at 0x76963b611520>},
 ('C2RCC_rhow_9x9_depth_lt_1',
  'EN'): {'best_params': {'alpha': 0.048330942726490585,
   'l1_ratio': 0.9989560212538449}, 'best_score': 0.526277535332456, 'study': <optuna.study.study.Study at 0x76963e5dc730>},
 ('C2X-Complex_rhown_5x5_depth_lt_1',
  'XGB'): {'best_params': {'n_estimators': 2000,
   'learning_rate': 0.030807798606597547,
   'max_depth': 7,
   'min_child_weight': 1,
   'subsample': 0.8196056231430358,
   'colsample_bytree': 0.6083252426239475}, 'best_score': 0.6113214754273599, 'study': <optuna.study.study.Study at 0x76963e34c9a0>},
 ('C2X-Complex_rhown_5x5_depth_lt_1',
  'LBM'): {'best_params': {'learning_rate': 0.0277640752355835,
   'num_leaves': 60,
   'max_depth': 5,
   'min_child_samples': 11,
   'subsample': 0.7748305193166063,
   'colsample_bytree': 0.7539637134525157,
   'n_estimators': 1000}, 'best_score': 0.6646608535074101, 'study': <optuna.study.study.Study at 0x76963b7372b0>},
 ('C2X-Complex_rhown_5x5_depth_lt_1',
  'MLP'): {'best_params': {'hidden_layer_sizes': '100',
   'activation': 'tanh',
   'solver': 'adam',
   'alpha': 0.002580682582104384,
   'learning_rate': 'adaptive',
   'learning_rate_init': 0.002404013964548544}, 'best_score': 0.5842995316444204, 'study': <optuna.study.study.Study at 0x76963b8bf940>},
 ('C2X-Complex_rhown_5x5_depth_lt_1',
  'SVR'): {'best_params': {'kernel': 'rbf',
   'C': 9.933758770821122,
   'epsilon': 0.19913769193990524,
   'gamma': 'auto'}, 'best_score': 0.48721878830745835, 'study': <optuna.study.study.Study at 0x76963b6c5d00>},
 ('C2X-Complex_rhown_5x5_depth_lt_1',
  'KNN'): {'best_params': {'n_neighbors': 5,
   'weights': 'distance',
   'leaf_size': 29}, 'best_score': 0.6721698638838516, 'study': <optuna.study.study.Study at 0x76963b799a00>},
 ('C2X-Complex_rhown_5x5_depth_lt_1',
  'LR'): {'best_params': {'fit_intercept': True,
   'positive': True}, 'best_score': -0.0033190266559897097, 'study': <optuna.study.study.Study at 0x76963b720d30>},
 ('C2X-Complex_rhown_5x5_depth_lt_1',
  'RF'): {'best_params': {'n_estimators': 500,
   'max_depth': 7,
   'min_samples_split': 4,
   'min_samples_leaf': 1,
   'bootstrap': True}, 'best_score': 0.5086269545579811, 'study': <optuna.study.study.Study at 0x76963b7be400>},
 ('C2X-Complex_rhown_5x5_depth_lt_1',
  'CAT'): {'best_params': {'iterations': 500,
   'learning_rate': 0.053881702249112935,
   'depth': 9,
   'l2_leaf_reg': 3.923843354437382}, 'best_score': 0.677082763664405, 'study': <optuna.study.study.Study at 0x76963b770ac0>},
 ('C2X-Complex_rhown_5x5_depth_lt_1',
  'EN'): {'best_params': {'alpha': 0.14014828482341338,
   'l1_ratio': 0.02051772669299834}, 'best_score': 0.5243340526797808, 'study': <optuna.study.study.Study at 0x76963b743ac0>},
 ('C2X_rhown_9x9_depth_lt_1',
  'XGB'): {'best_params': {'n_estimators': 500,
   'learning_rate': 0.023699229508764526,
   'max_depth': 5,
   'min_child_weight': 4,
   'subsample': 0.7298039366397602,
   'colsample_bytree': 0.6246729134472505}, 'best_score': 0.45553058176714345, 'study': <optuna.study.study.Study at 0x76963b77c340>},
 ('C2X_rhown_9x9_depth_lt_1',
  'LBM'): {'best_params': {'learning_rate': 0.009287415114544437,
   'num_leaves': 80,
   'max_depth': 8,
   'min_child_samples': 10,
   'subsample': 0.9568085814792049,
   'colsample_bytree': 0.8834108826852782,
   'n_estimators': 2000}, 'best_score': 0.521486192372547, 'study': <optuna.study.study.Study at 0x76963dfaf430>},
 ('C2X_rhown_9x9_depth_lt_1',
  'MLP'): {'best_params': {'hidden_layer_sizes': '100',
   'activation': 'tanh',
   'solver': 'adam',
   'alpha': 0.004912347384183444,
   'learning_rate': 'constant',
   'learning_rate_init': 0.0012868687694447295}, 'best_score': 0.44208590548762317, 'study': <optuna.study.study.Study at 0x76963de36640>},
 ('C2X_rhown_9x9_depth_lt_1',
  'SVR'): {'best_params': {'kernel': 'rbf',
   'C': 9.999876489435506,
   'epsilon': 0.037814994820811736,
   'gamma': 'scale'}, 'best_score': 0.4150093198780329, 'study': <optuna.study.study.Study at 0x76963e2ede50>},
 ('C2X_rhown_9x9_depth_lt_1',
  'KNN'): {'best_params': {'n_neighbors': 4,
   'weights': 'distance',
   'leaf_size': 29}, 'best_score': 0.5058465768937079, 'study': <optuna.study.study.Study at 0x76963b6695e0>},
 ('C2X_rhown_9x9_depth_lt_1',
  'LR'): {'best_params': {'fit_intercept': False,
   'positive': True}, 'best_score': 0.3961773516018653, 'study': <optuna.study.study.Study at 0x76963e0589d0>},
 ('C2X_rhown_9x9_depth_lt_1',
  'RF'): {'best_params': {'n_estimators': 500,
   'max_depth': 14,
   'min_samples_split': 3,
   'min_samples_leaf': 1,
   'bootstrap': True}, 'best_score': 0.40570191808639067, 'study': <optuna.study.study.Study at 0x76963e2fad90>},
 ('C2X_rhown_9x9_depth_lt_1',
  'CAT'): {'best_params': {'iterations': 500,
   'learning_rate': 0.017987890187973567,
   'depth': 4,
   'l2_leaf_reg': 6.964986743821935}, 'best_score': 0.5015882606291253, 'study': <optuna.study.study.Study at 0x76963df53dc0>},
 ('C2X_rhown_9x9_depth_lt_1',
  'EN'): {'best_params': {'alpha': 0.020651125092207196,
   'l1_ratio': 0.10965931255409339}, 'best_score': 0.42593835174859984, 'study': <optuna.study.study.Study at 0x76963b5cffd0>},
 ('TOA_3x3_depth_lt_1',
  'XGB'): {'best_params': {'n_estimators': 500,
   'learning_rate': 0.011065460930763691,
   'max_depth': 5,
   'min_child_weight': 4,
   'subsample': 0.6561434361923439,
   'colsample_bytree': 0.8892521829814612}, 'best_score': 0.7011211337890131, 'study': <optuna.study.study.Study at 0x76963df631f0>},
 ('TOA_3x3_depth_lt_1',
  'LBM'): {'best_params': {'learning_rate': 0.058649190864794594,
   'num_leaves': 20,
   'max_depth': 6,
   'min_child_samples': 16,
   'subsample': 0.7438143258380389,
   'colsample_bytree': 0.6836802059586142,
   'n_estimators': 1000}, 'best_score': 0.7361908657771258, 'study': <optuna.study.study.Study at 0x76963e45e550>},
 ('TOA_3x3_depth_lt_1',
  'MLP'): {'best_params': {'hidden_layer_sizes': '128_64',
   'activation': 'relu',
   'solver': 'adam',
   'alpha': 0.0005884657568808193,
   'learning_rate': 'constant',
   'learning_rate_init': 0.00977131119065175}, 'best_score': 0.7014604430369968, 'study': <optuna.study.study.Study at 0x76963e45ec10>},
 ('TOA_3x3_depth_lt_1',
  'SVR'): {'best_params': {'kernel': 'rbf',
   'C': 9.99146026649796,
   'epsilon': 0.016757551201296503,
   'gamma': 'scale'}, 'best_score': 0.5222781671451275, 'study': <optuna.study.study.Study at 0x76963e24b0a0>},
 ('TOA_3x3_depth_lt_1',
  'KNN'): {'best_params': {'n_neighbors': 4,
   'weights': 'distance',
   'leaf_size': 35}, 'best_score': 0.7299191310872667, 'study': <optuna.study.study.Study at 0x76963dfb8dc0>},
 ('TOA_3x3_depth_lt_1',
  'LR'): {'best_params': {'fit_intercept': False,
   'positive': True}, 'best_score': 0.2608450371523062, 'study': <optuna.study.study.Study at 0x76963e3d6700>},
 ('TOA_3x3_depth_lt_1',
  'RF'): {'best_params': {'n_estimators': 300,
   'max_depth': 14,
   'min_samples_split': 6,
   'min_samples_leaf': 2,
   'bootstrap': True}, 'best_score': 0.6723300124820809, 'study': <optuna.study.study.Study at 0x76963b770fd0>},
 ('TOA_3x3_depth_lt_1',
  'CAT'): {'best_params': {'iterations': 1000,
   'learning_rate': 0.07284750606764506,
   'depth': 10,
   'l2_leaf_reg': 8.435135568098113}, 'best_score': 0.7265599446956033, 'study': <optuna.study.study.Study at 0x76963b6fe0d0>},
 ('TOA_3x3_depth_lt_1',
  'EN'): {'best_params': {'alpha': 0.0875108209046544,
   'l1_ratio': 0.9840610418292111}, 'best_score': 0.22687812742962465, 'study': <optuna.study.study.Study at 0x76963dece340>},
 ('C2X-Complex_rhown_9x9_depth_lt_1',
  'XGB'): {'best_params': {'n_estimators': 1000,
   'learning_rate': 0.012779167259174738,
   'max_depth': 6,
   'min_child_weight': 1,
   'subsample': 0.8109604551437071,
   'colsample_bytree': 0.7572789443439116}, 'best_score': 0.6646189001317588, 'study': <optuna.study.study.Study at 0x76963e3d30d0>},
 ('C2X-Complex_rhown_9x9_depth_lt_1',
  'LBM'): {'best_params': {'learning_rate': 0.04049635282595456,
   'num_leaves': 60,
   'max_depth': 8,
   'min_child_samples': 5,
   'subsample': 0.8860242605873505,

In [297]:
# Diccionario para agrupar parámetros por modelo
params_by_model = defaultdict(list)

# Agrupar best_params por modelo
for (df_name, model_name), result in global_results.items():
    best_params = result["best_params"]
    params_by_model[model_name].append(best_params)

# Crear DataFrames con medias y std por modelo
summary_stats = {}

for model_name, param_list in params_by_model.items():
    df_params = pd.DataFrame(param_list)

    # Filtramos solo columnas numéricas para calcular medias y std
    df_numeric = df_params.select_dtypes(include=[np.number])

    stats = pd.concat([df_numeric.mean().rename("mean"), df_numeric.std().rename("std")], axis=1)
    summary_stats[model_name] = stats

# Mostrar un ejemplo
summary_stats["XGB"]

                        mean         std
n_estimators      982.142857  630.727723
learning_rate       0.024349    0.022070
max_depth           6.607143    1.100144
min_child_weight    2.357143    1.282771
subsample           0.739660    0.107569
colsample_bytree    0.737681    0.104036

In [303]:
for model, stats_df in summary_stats.items():
    print(f"\n📊 {model}")
    print(stats_df.round(2))

📊 XGB
                    mean     std
n_estimators      982.14  630.73
learning_rate       0.02    0.02
max_depth           6.61    1.10
min_child_weight    2.36    1.28
subsample           0.74    0.11
colsample_bytree    0.74    0.10

📊 LBM
                      mean     std
learning_rate         0.02    0.02
num_leaves           47.14   22.58
max_depth             6.25    1.17
min_child_samples    12.32    7.07
subsample             0.83    0.12
colsample_bytree      0.74    0.11
n_estimators       1285.71  658.68

📊 MLP
                    mean   std
alpha               0.01  0.03
learning_rate_init  0.00  0.00

📊 SVR
         mean   std
C        9.54  0.88
epsilon  0.11  0.05

📊 KNN
              mean   std
n_neighbors   4.71  2.37
leaf_size    24.36  9.45

📊 LR
Empty DataFrame
Columns: [mean, std]
Index: []

📊 RF
                     mean     std
n_estimators       385.71  148.36
max_depth           10.43    3.13
min_samples_split    4.46    2.06
min_samples_leaf     1.54    0.84

📊 CAT
                  mean     std
iterations     1267.86  630.73
learning_rate     0.04    0.02
depth             8.29    1.78
l2_leaf_reg       3.45    2.23

📊 EN
          mean   std
alpha     0.19  0.31
l1_ratio  0.54  0.36

In [308]:
for model, param_list in params_by_model.items():
    print(f"\n🔤 Parámetros categóricos de {model}:")
    df = pd.DataFrame(param_list)
    df = df.drop(columns=["dataset", "model"])
    for col in df.select_dtypes(include='object').columns:
        print(f"{col}:\n{df[col].value_counts()}")

🔤 Parámetros categóricos de XGB:

🔤 Parámetros categóricos de LBM:

🔤 Parámetros categóricos de MLP:
hidden_layer_sizes:
hidden_layer_sizes
100       13
128_64     9
100_50     5
50         1
Name: count, dtype: int64
activation:
activation
tanh    16
relu    12
Name: count, dtype: int64
solver:
solver
adam    21
sgd      7
Name: count, dtype: int64
learning_rate:
learning_rate
adaptive    16
constant    12
Name: count, dtype: int64

🔤 Parámetros categóricos de SVR:
kernel:
kernel
rbf    28
Name: count, dtype: int64
gamma:
gamma
scale    21
auto      7
Name: count, dtype: int64

🔤 Parámetros categóricos de KNN:
weights:
weights
distance    25
uniform      3
Name: count, dtype: int64

🔤 Parámetros categóricos de LR:

🔤 Parámetros categóricos de RF:

🔤 Parámetros categóricos de CAT:

🔤 Parámetros categóricos de EN:

**Parámetros seleccionados** (Nos quedamos con los que dice Optuna en EN, KNN, SVR y XGB, y mantenemos los que pusimos por defecto en CAT, MLP, LBM y RF. Esto lo decidimos después de ver los resultados al entrenar todo con los que nos daba Optuna y comparar resultados modelo a modelo.)

In [9]:
model_params ={
    "XGB" : {
        'n_estimators': 1000,
        'learning_rate': 0.02,
        'max_depth': 7,
        'min_child_weight': 2,
        'subsample': 0.7,
        'colsample_bytree': 0.7,
        'device': 'cpu',
        'objective': 'reg:squarederror',
        'tree_method': 'hist',
        'enable_categorical': True,
        #'early_stopping_rounds': 50,
        'eval_metric': 'rmse'
        },

    "LBM" : {
        'learning_rate': 0.04,
        'num_leaves': 20,
        'max_depth': 7,
        'min_child_samples': 4,
        'subsample': 0.7,
        'colsample_bytree': 0.7,
        'n_estimators': 1000,
        'objective': 'regression',
        'metric': 'rmse',
        'boosting_type': 'gbdt',
        'device': 'cpu',  
        'verbosity': -1,
        #'early_stopping_rounds': 50
        },

    "MLP": {
        'hidden_layer_sizes': (100,),
        'activation': 'relu',
        'solver': 'adam',
        'alpha': 0.0001,
        'learning_rate': 'constant',
        'learning_rate_init': 0.001,
        'max_iter': 200,
        'shuffle': True,
        'random_state': None,
        'tol': 1e-4,
        'n_iter_no_change': 25,
        'verbose': False,
        'early_stopping': True,
        'validation_fraction': 0.2
        },

    "SVR": {
        'kernel': 'rbf',        
        'C': 9.5,               
        'epsilon': 0.1,           
        'gamma': 'scale',        
        'shrinking': True,
        'tol': 1e-3,
        'max_iter': -1,          
        'verbose': False,
    },

    "KNN": {
        'n_neighbors': 5,
        'weights': 'distance',      
        'algorithm': 'auto',      
        'leaf_size': 25,
        'p': 2,                    
        'metric': 'minkowski',
        'n_jobs': -1             
    },

    "RF": {
        'n_estimators': 100,         
        'criterion': 'squared_error',
        'max_depth': 10,         
        'min_samples_split': 2,
        'min_samples_leaf': 2,    
        'bootstrap': True,
        'random_state': 42,
        'verbose': 0
    },

    "CAT": {
        'iterations': 1000,
        'learning_rate': 0.03,
        'depth': 6,
        'l2_leaf_reg': 3.0,
        'loss_function': 'RMSE',
        'eval_metric': 'RMSE',
        'random_seed': 42,
        'allow_writing_files': False,
        'early_stopping_rounds': 50,
        'verbose': False
    },

    "EN": {
        'alpha': 0.2,             
        'l1_ratio': 0.5,           
        'fit_intercept': True,
        'max_iter': 1000,
        'tol': 1e-4,
        'selection': 'cyclic',
        'random_state': 42
    }

}


models = {
    "XGB": XGBRegressor(**model_params['XGB']),
    "LBM": LGBMRegressor(**model_params['LBM']),
    "MLP": MLPRegressor(**model_params['MLP']),
    "SVR": SVR(**model_params['SVR']),
    "KNN": KNeighborsRegressor(**model_params['KNN']),
    "LR": LinearRegression(),
    "RF": RandomForestRegressor(**model_params['RF']),
    "CAT": CatBoostRegressor(**model_params["CAT"]),
    "EN":  ElasticNet(**model_params["EN"])
}

**Entrenamiento con los parámetros seleccionados**

In [318]:
results = {}

for nombre_df, df in list(dfs.items()):
    #print(nombre_df)
    df = df.iloc[:,4:]

    # Para usar solamente bandas, sin combinaciones
    # if 'TOA' in nombre_df:
    #     # TOA solamente con las bandas, parece que las combinaciones solo meten ruido
    #     df = df.iloc[:,np.r_[0:14, 58:60]]
    # if 'rhow' in nombre_df and 'rhown' not in nombre_df:
    #     df = df.iloc[:,np.r_[0:9, 53:55]]
    # if 'rhown' in nombre_df:
    #     df = df.iloc[:,np.r_[0:7, 51:53]]

    train, test = train_test_split(df, test_size=0.2, random_state=42, stratify=df["High_Chl"]) # TEST 20% TRAIN 80%
    target = "Chl"

    train, val = train_test_split(train, test_size=0.25, random_state=42, stratify=train["High_Chl"]) # TRAIN 60% VAL 20% TEST%

    X_train = train.drop(columns=[target,"High_Chl"])
    X_val = val.drop(columns=[target, "High_Chl"])
    X_test = test.drop(columns=[target, "High_Chl"])
    y_train = train[target]
    y_val = val[target]
    y_test = test[target]

    
    scaler_X = RobustScaler()
    scaler_y = RobustScaler()
    X_train_scaled = scaler_X.fit_transform(X_train)
    X_val_scaled = scaler_X.transform(X_val)
    X_test_scaled = scaler_X.transform(X_test)
    y_train_scaled = scaler_y.fit_transform(y_train.values.reshape(-1, 1)).ravel()
    
    results[nombre_df] = {name: {'RMSE': None, 'R2': None} for name in models}
    val_preds = {}
    test_preds = {}

    for name, model in models.items():
        print(f"Fitting {name} for {nombre_df}")
        if name in ["MLP", "SVR", "KNN", "LR", "EN"]:
            model.fit(X_train_scaled, y_train_scaled)
            #test_pred = model.predict(X_test_scaled)
            val_pred = scaler_y.inverse_transform(model.predict(X_val_scaled).reshape(-1, 1)).ravel()
            test_pred = scaler_y.inverse_transform(model.predict(X_test_scaled).reshape(-1, 1)).ravel()
        else:
            model.fit(X_train, y_train)
            val_pred = model.predict(X_val)
            test_pred = model.predict(X_test)

        val_preds[name] = val_pred
        test_preds[name] = test_pred

        rmse = np.sqrt(mean_squared_error(y_test, test_pred))
        r2 = r2_score(y_test, test_pred)

        results[nombre_df][name]['RMSE'] = rmse.round(2)
        results[nombre_df][name]['R2'] = r2.round(2)

    # Meta-modelo
    meta_X = np.vstack([val_preds[model] for model in models]).T
    meta_y = y_val.values
    meta_model = Ridge().fit(meta_X, meta_y)

    # Predicción final ensemble
    test_meta_X = np.vstack([test_preds[model] for model in models]).T
    ensemble_pred = meta_model.predict(test_meta_X)

    rmse_ens = np.sqrt(mean_squared_error(y_test, ensemble_pred))
    r2_ens = r2_score(y_test, ensemble_pred)

    results[nombre_df]["Ensemble"] = {
        "RMSE": round(rmse_ens, 2),
        "R2": round(r2_ens, 2)
    }

Fitting XGB for C2RCC_rhow_5x5_depth_lt_1
Fitting LBM for C2RCC_rhow_5x5_depth_lt_1
Fitting MLP for C2RCC_rhow_5x5_depth_lt_1
Fitting SVR for C2RCC_rhow_5x5_depth_lt_1
Fitting KNN for C2RCC_rhow_5x5_depth_lt_1
Fitting LR for C2RCC_rhow_5x5_depth_lt_1
Fitting RF for C2RCC_rhow_5x5_depth_lt_1
Fitting CAT for C2RCC_rhow_5x5_depth_lt_1
Fitting EN for C2RCC_rhow_5x5_depth_lt_1
Fitting XGB for C2X-Complex_rhown_3x3_depth_lt_1
Fitting LBM for C2X-Complex_rhown_3x3_depth_lt_1
Fitting MLP for C2X-Complex_rhown_3x3_depth_lt_1
Fitting SVR for C2X-Complex_rhown_3x3_depth_lt_1
Fitting KNN for C2X-Complex_rhown_3x3_depth_lt_1
Fitting LR for C2X-Complex_rhown_3x3_depth_lt_1
Fitting RF for C2X-Complex_rhown_3x3_depth_lt_1
Fitting CAT for C2X-Complex_rhown_3x3_depth_lt_1
Fitting EN for C2X-Complex_rhown_3x3_depth_lt_1
Fitting XGB for TOA_9x9_depth_lt_1
Fitting LBM for TOA_9x9_depth_lt_1
Fitting MLP for TOA_9x9_depth_lt_1
Fitting SVR for TOA_9x9_depth_lt_1
Fitting KNN for TOA_9x9_depth_lt_1
Fitting LR for TOA_9x9_depth_lt_1
Fitting RF for TOA_9x9_depth_lt_1
Fitting CAT for TOA_9x9_depth_lt_1
Fitting EN for TOA_9x9_depth_lt_1
Fitting XGB for C2X_rhow_3x3_depth_lt_1
Fitting LBM for C2X_rhow_3x3_depth_lt_1
Fitting MLP for C2X_rhow_3x3_depth_lt_1
Fitting SVR for C2X_rhow_3x3_depth_lt_1
Fitting KNN for C2X_rhow_3x3_depth_lt_1
Fitting LR for C2X_rhow_3x3_depth_lt_1
Fitting RF for C2X_rhow_3x3_depth_lt_1
Fitting CAT for C2X_rhow_3x3_depth_lt_1
Fitting EN for C2X_rhow_3x3_depth_lt_1
Fitting XGB for C2RCC_rhow_9x9_depth_lt_1
Fitting LBM for C2RCC_rhow_9x9_depth_lt_1
Fitting MLP for C2RCC_rhow_9x9_depth_lt_1
Fitting SVR for C2RCC_rhow_9x9_depth_lt_1
Fitting KNN for C2RCC_rhow_9x9_depth_lt_1
Fitting LR for C2RCC_rhow_9x9_depth_lt_1
Fitting RF for C2RCC_rhow_9x9_depth_lt_1
Fitting CAT for C2RCC_rhow_9x9_depth_lt_1
Fitting EN for C2RCC_rhow_9x9_depth_lt_1
Fitting XGB for C2X-Complex_rhown_5x5_depth_lt_1
Fitting LBM for C2X-Complex_rhown_5x5_depth_lt_1
Fitting MLP for C2X-Complex_rhown_5x5_depth_lt_1
Fitting SVR for C2X-Complex_rhown_5x5_depth_lt_1
Fitting KNN for C2X-Complex_rhown_5x5_depth_lt_1
Fitting LR for C2X-Complex_rhown_5x5_depth_lt_1
Fitting RF for C2X-Complex_rhown_5x5_depth_lt_1
Fitting CAT for C2X-Complex_rhown_5x5_depth_lt_1
Fitting EN for C2X-Complex_rhown_5x5_depth_lt_1
Fitting XGB for C2X_rhown_9x9_depth_lt_1
Fitting LBM for C2X_rhown_9x9_depth_lt_1
Fitting MLP for C2X_rhown_9x9_depth_lt_1
Fitting SVR for C2X_rhown_9x9_depth_lt_1
Fitting KNN for C2X_rhown_9x9_depth_lt_1
Fitting LR for C2X_rhown_9x9_depth_lt_1
Fitting RF for C2X_rhown_9x9_depth_lt_1
Fitting CAT for C2X_rhown_9x9_depth_lt_1
Fitting EN for C2X_rhown_9x9_depth_lt_1
Fitting XGB for TOA_3x3_depth_lt_1
Fitting LBM for TOA_3x3_depth_lt_1
Fitting MLP for TOA_3x3_depth_lt_1
Fitting SVR for TOA_3x3_depth_lt_1
Fitting KNN for TOA_3x3_depth_lt_1
Fitting LR for TOA_3x3_depth_lt_1
Fitting RF for TOA_3x3_depth_lt_1
Fitting CAT for TOA_3x3_depth_lt_1
Fitting EN for TOA_3x3_depth_lt_1
Fitting XGB for C2X-Complex_rhown_9x9_depth_lt_1
Fitting LBM for C2X-Complex_rhown_9x9_depth_lt_1
Fitting MLP for C2X-Complex_rhown_9x9_depth_lt_1
Fitting SVR for C2X-Complex_rhown_9x9_depth_lt_1
Fitting KNN for C2X-Complex_rhown_9x9_depth_lt_1
Fitting LR for C2X-Complex_rhown_9x9_depth_lt_1
Fitting RF for C2X-Complex_rhown_9x9_depth_lt_1
Fitting CAT for C2X-Complex_rhown_9x9_depth_lt_1
Fitting EN for C2X-Complex_rhown_9x9_depth_lt_1
Fitting XGB for C2X-Complex_rhow_3x3_depth_lt_1
Fitting LBM for C2X-Complex_rhow_3x3_depth_lt_1
Fitting MLP for C2X-Complex_rhow_3x3_depth_lt_1
Fitting SVR for C2X-Complex_rhow_3x3_depth_lt_1
Fitting KNN for C2X-Complex_rhow_3x3_depth_lt_1
Fitting LR for C2X-Complex_rhow_3x3_depth_lt_1
Fitting RF for C2X-Complex_rhow_3x3_depth_lt_1
Fitting CAT for C2X-Complex_rhow_3x3_depth_lt_1
Fitting EN for C2X-Complex_rhow_3x3_depth_lt_1
Fitting XGB for C2X_rhow_1x1_depth_lt_1
Fitting LBM for C2X_rhow_1x1_depth_lt_1
Fitting MLP for C2X_rhow_1x1_depth_lt_1
Fitting SVR for C2X_rhow_1x1_depth_lt_1
Fitting KNN for C2X_rhow_1x1_depth_lt_1
Fitting LR for C2X_rhow_1x1_depth_lt_1
Fitting RF for C2X_rhow_1x1_depth_lt_1
Fitting CAT for C2X_rhow_1x1_depth_lt_1
Fitting EN for C2X_rhow_1x1_depth_lt_1
Fitting XGB for C2RCC_rhown_1x1_depth_lt_1
Fitting LBM for C2RCC_rhown_1x1_depth_lt_1
Fitting MLP for C2RCC_rhown_1x1_depth_lt_1
Fitting SVR for C2RCC_rhown_1x1_depth_lt_1
Fitting KNN for C2RCC_rhown_1x1_depth_lt_1
Fitting LR for C2RCC_rhown_1x1_depth_lt_1
Fitting RF for C2RCC_rhown_1x1_depth_lt_1
Fitting CAT for C2RCC_rhown_1x1_depth_lt_1
Fitting EN for C2RCC_rhown_1x1_depth_lt_1
Fitting XGB for C2X_rhown_1x1_depth_lt_1
Fitting LBM for C2X_rhown_1x1_depth_lt_1
Fitting MLP for C2X_rhown_1x1_depth_lt_1
Fitting SVR for C2X_rhown_1x1_depth_lt_1
Fitting KNN for C2X_rhown_1x1_depth_lt_1
Fitting LR for C2X_rhown_1x1_depth_lt_1
Fitting RF for C2X_rhown_1x1_depth_lt_1
Fitting CAT for C2X_rhown_1x1_depth_lt_1
Fitting EN for C2X_rhown_1x1_depth_lt_1
Fitting XGB for C2RCC_rhown_9x9_depth_lt_1
Fitting LBM for C2RCC_rhown_9x9_depth_lt_1
Fitting MLP for C2RCC_rhown_9x9_depth_lt_1
Fitting SVR for C2RCC_rhown_9x9_depth_lt_1
Fitting KNN for C2RCC_rhown_9x9_depth_lt_1
Fitting LR for C2RCC_rhown_9x9_depth_lt_1
Fitting RF for C2RCC_rhown_9x9_depth_lt_1
Fitting CAT for C2RCC_rhown_9x9_depth_lt_1
Fitting EN for C2RCC_rhown_9x9_depth_lt_1
Fitting XGB for C2X_rhow_5x5_depth_lt_1
Fitting LBM for C2X_rhow_5x5_depth_lt_1
Fitting MLP for C2X_rhow_5x5_depth_lt_1
Fitting SVR for C2X_rhow_5x5_depth_lt_1
Fitting KNN for C2X_rhow_5x5_depth_lt_1
Fitting LR for C2X_rhow_5x5_depth_lt_1
Fitting RF for C2X_rhow_5x5_depth_lt_1
Fitting CAT for C2X_rhow_5x5_depth_lt_1
Fitting EN for C2X_rhow_5x5_depth_lt_1
Fitting XGB for C2X_rhown_5x5_depth_lt_1
Fitting LBM for C2X_rhown_5x5_depth_lt_1
Fitting MLP for C2X_rhown_5x5_depth_lt_1
Fitting SVR for C2X_rhown_5x5_depth_lt_1
Fitting KNN for C2X_rhown_5x5_depth_lt_1
Fitting LR for C2X_rhown_5x5_depth_lt_1
Fitting RF for C2X_rhown_5x5_depth_lt_1
Fitting CAT for C2X_rhown_5x5_depth_lt_1
Fitting EN for C2X_rhown_5x5_depth_lt_1
Fitting XGB for C2X_rhow_9x9_depth_lt_1
Fitting LBM for C2X_rhow_9x9_depth_lt_1
Fitting MLP for C2X_rhow_9x9_depth_lt_1
Fitting SVR for C2X_rhow_9x9_depth_lt_1
Fitting KNN for C2X_rhow_9x9_depth_lt_1
Fitting LR for C2X_rhow_9x9_depth_lt_1
Fitting RF for C2X_rhow_9x9_depth_lt_1
Fitting CAT for C2X_rhow_9x9_depth_lt_1
Fitting EN for C2X_rhow_9x9_depth_lt_1
Fitting XGB for C2X_rhown_3x3_depth_lt_1
Fitting LBM for C2X_rhown_3x3_depth_lt_1
Fitting MLP for C2X_rhown_3x3_depth_lt_1
Fitting SVR for C2X_rhown_3x3_depth_lt_1
Fitting KNN for C2X_rhown_3x3_depth_lt_1
Fitting LR for C2X_rhown_3x3_depth_lt_1
Fitting RF for C2X_rhown_3x3_depth_lt_1
Fitting CAT for C2X_rhown_3x3_depth_lt_1
Fitting EN for C2X_rhown_3x3_depth_lt_1
Fitting XGB for C2RCC_rhown_5x5_depth_lt_1
Fitting LBM for C2RCC_rhown_5x5_depth_lt_1
Fitting MLP for C2RCC_rhown_5x5_depth_lt_1
Fitting SVR for C2RCC_rhown_5x5_depth_lt_1
Fitting KNN for C2RCC_rhown_5x5_depth_lt_1
Fitting LR for C2RCC_rhown_5x5_depth_lt_1
Fitting RF for C2RCC_rhown_5x5_depth_lt_1
Fitting CAT for C2RCC_rhown_5x5_depth_lt_1
Fitting EN for C2RCC_rhown_5x5_depth_lt_1
Fitting XGB for TOA_1x1_depth_lt_1
Fitting LBM for TOA_1x1_depth_lt_1
Fitting MLP for TOA_1x1_depth_lt_1
Fitting SVR for TOA_1x1_depth_lt_1
Fitting KNN for TOA_1x1_depth_lt_1
Fitting LR for TOA_1x1_depth_lt_1
Fitting RF for TOA_1x1_depth_lt_1
Fitting CAT for TOA_1x1_depth_lt_1
Fitting EN for TOA_1x1_depth_lt_1
Fitting XGB for C2X-Complex_rhow_5x5_depth_lt_1
Fitting LBM for C2X-Complex_rhow_5x5_depth_lt_1
Fitting MLP for C2X-Complex_rhow_5x5_depth_lt_1
Fitting SVR for C2X-Complex_rhow_5x5_depth_lt_1
Fitting KNN for C2X-Complex_rhow_5x5_depth_lt_1
Fitting LR for C2X-Complex_rhow_5x5_depth_lt_1
Fitting RF for C2X-Complex_rhow_5x5_depth_lt_1
Fitting CAT for C2X-Complex_rhow_5x5_depth_lt_1
Fitting EN for C2X-Complex_rhow_5x5_depth_lt_1
Fitting XGB for C2X-Complex_rhow_9x9_depth_lt_1
Fitting LBM for C2X-Complex_rhow_9x9_depth_lt_1
Fitting MLP for C2X-Complex_rhow_9x9_depth_lt_1
Fitting SVR for C2X-Complex_rhow_9x9_depth_lt_1
Fitting KNN for C2X-Complex_rhow_9x9_depth_lt_1
Fitting LR for C2X-Complex_rhow_9x9_depth_lt_1
Fitting RF for C2X-Complex_rhow_9x9_depth_lt_1
Fitting CAT for C2X-Complex_rhow_9x9_depth_lt_1
Fitting EN for C2X-Complex_rhow_9x9_depth_lt_1
Fitting XGB for C2X-Complex_rhow_1x1_depth_lt_1
Fitting LBM for C2X-Complex_rhow_1x1_depth_lt_1
Fitting MLP for C2X-Complex_rhow_1x1_depth_lt_1
Fitting SVR for C2X-Complex_rhow_1x1_depth_lt_1
Fitting KNN for C2X-Complex_rhow_1x1_depth_lt_1
Fitting LR for C2X-Complex_rhow_1x1_depth_lt_1
Fitting RF for C2X-Complex_rhow_1x1_depth_lt_1
Fitting CAT for C2X-Complex_rhow_1x1_depth_lt_1
Fitting EN for C2X-Complex_rhow_1x1_depth_lt_1
Fitting XGB for C2X-Complex_rhown_1x1_depth_lt_1
Fitting LBM for C2X-Complex_rhown_1x1_depth_lt_1
Fitting MLP for C2X-Complex_rhown_1x1_depth_lt_1
Fitting SVR for C2X-Complex_rhown_1x1_depth_lt_1
Fitting KNN for C2X-Complex_rhown_1x1_depth_lt_1
Fitting LR for C2X-Complex_rhown_1x1_depth_lt_1
Fitting RF for C2X-Complex_rhown_1x1_depth_lt_1
Fitting CAT for C2X-Complex_rhown_1x1_depth_lt_1
Fitting EN for C2X-Complex_rhown_1x1_depth_lt_1
Fitting XGB for C2RCC_rhow_3x3_depth_lt_1
Fitting LBM for C2RCC_rhow_3x3_depth_lt_1
Fitting MLP for C2RCC_rhow_3x3_depth_lt_1
Fitting SVR for C2RCC_rhow_3x3_depth_lt_1
Fitting KNN for C2RCC_rhow_3x3_depth_lt_1
Fitting LR for C2RCC_rhow_3x3_depth_lt_1
Fitting RF for C2RCC_rhow_3x3_depth_lt_1
Fitting CAT for C2RCC_rhow_3x3_depth_lt_1
Fitting EN for C2RCC_rhow_3x3_depth_lt_1
Fitting XGB for TOA_5x5_depth_lt_1
Fitting LBM for TOA_5x5_depth_lt_1
Fitting MLP for TOA_5x5_depth_lt_1
Fitting SVR for TOA_5x5_depth_lt_1
Fitting KNN for TOA_5x5_depth_lt_1
Fitting LR for TOA_5x5_depth_lt_1
Fitting RF for TOA_5x5_depth_lt_1
Fitting CAT for TOA_5x5_depth_lt_1
Fitting EN for TOA_5x5_depth_lt_1
Fitting XGB for C2RCC_rhown_3x3_depth_lt_1
Fitting LBM for C2RCC_rhown_3x3_depth_lt_1
Fitting MLP for C2RCC_rhown_3x3_depth_lt_1
Fitting SVR for C2RCC_rhown_3x3_depth_lt_1
Fitting KNN for C2RCC_rhown_3x3_depth_lt_1
Fitting LR for C2RCC_rhown_3x3_depth_lt_1
Fitting RF for C2RCC_rhown_3x3_depth_lt_1
Fitting CAT for C2RCC_rhown_3x3_depth_lt_1
Fitting EN for C2RCC_rhown_3x3_depth_lt_1
Fitting XGB for C2RCC_rhow_1x1_depth_lt_1
Fitting LBM for C2RCC_rhow_1x1_depth_lt_1
Fitting MLP for C2RCC_rhow_1x1_depth_lt_1
Fitting SVR for C2RCC_rhow_1x1_depth_lt_1
Fitting KNN for C2RCC_rhow_1x1_depth_lt_1
Fitting LR for C2RCC_rhow_1x1_depth_lt_1
Fitting RF for C2RCC_rhow_1x1_depth_lt_1
Fitting CAT for C2RCC_rhow_1x1_depth_lt_1
Fitting EN for C2RCC_rhow_1x1_depth_lt_1

In [329]:
rows = []

for df_name, model_scores in results.items():
    row = {}
    for model_name, metrics in model_scores.items():
        for metric_name, values in metrics.items():
            if isinstance(values, list):  # Solo para los que tienen listas (folds)
                mean_val = np.mean(values)
                std_val = np.std(values)
                row[(metric_name, model_name)] = f"{mean_val:.2f} ± {std_val:.2f}"
            else:
                # Para el ensemble que tiene un único valor
                row[(metric_name, model_name)] = f"{values:.2f}"
    rows.append((df_name, row))

df_results = pd.DataFrame.from_dict(dict(rows), orient="index")
df_results.columns = pd.MultiIndex.from_tuples(df_results.columns, names=["Metric", "Model"])
df_results = df_results.sort_index(axis=1, level=0)
df_results = df_results.sort_index(axis=0)

In [330]:
df_results

Metric                                     R2                         \
Model                                     CAT           EN  Ensemble
C2RCC_rhow_5x5_depth_lt_1         0.67 ± 0.13  0.48 ± 0.07      0.61
C2X-Complex_rhown_3x3_depth_lt_1  0.66 ± 0.12  0.50 ± 0.06  -6049.03
TOA_9x9_depth_lt_1                0.78 ± 0.12  0.19 ± 0.13      0.46

Metric                                                                    \
Model                                     KNN          LBM            LR
C2RCC_rhow_5x5_depth_lt_1         0.74 ± 0.10  0.61 ± 0.24   0.31 ± 0.52
C2X-Complex_rhown_3x3_depth_lt_1  0.59 ± 0.12  0.55 ± 0.17  -1.12 ± 3.18
TOA_9x9_depth_lt_1                0.76 ± 0.13  0.70 ± 0.09   0.18 ± 0.36

Metric                                                                   \
Model                                     MLP           RF          SVR
C2RCC_rhow_5x5_depth_lt_1         0.71 ± 0.12  0.63 ± 0.18  0.66 ± 0.15
C2X-Complex_rhown_3x3_depth_lt_1  0.45 ± 0.08  0.63 ± 0.11  0.53 ± 0.09
TOA_9x9_depth_lt_1                0.65 ± 0.14  0.70 ± 0.13  0.50 ± 0.04

Metric                                                RMSE               \
Model                                     XGB          CAT           EN
C2RCC_rhow_5x5_depth_lt_1         0.65 ± 0.19  2.04 ± 0.37  2.64 ± 0.20
C2X-Complex_rhown_3x3_depth_lt_1  0.61 ± 0.17  2.08 ± 0.17  2.63 ± 0.41
TOA_9x9_depth_lt_1                0.72 ± 0.12  1.80 ± 0.49  3.58 ± 0.15

Metric                                                               \
Model                            Ensemble          KNN          LBM
C2RCC_rhow_5x5_depth_lt_1            2.97  1.81 ± 0.21  2.16 ± 0.50
C2X-Complex_rhown_3x3_depth_lt_1   370.82  2.30 ± 0.17  2.41 ± 0.25
TOA_9x9_depth_lt_1                   2.59  1.87 ± 0.37  2.15 ± 0.32

Metric                                                                   \
Model                                      LR          MLP           RF
C2RCC_rhow_5x5_depth_lt_1         2.83 ± 0.72  1.93 ± 0.27  2.14 ± 0.35
C2X-Complex_rhown_3x3_depth_lt_1  4.08 ± 2.64  2.77 ± 0.44  2.21 ± 0.17
TOA_9x9_depth_lt_1                3.49 ± 0.48  2.31 ± 0.28  2.12 ± 0.39

Metric
Model                                     SVR          XGB
C2RCC_rhow_5x5_depth_lt_1         2.08 ± 0.31  2.08 ± 0.44
C2X-Complex_rhown_3x3_depth_lt_1  2.52 ± 0.31  2.21 ± 0.28
TOA_9x9_depth_lt_1                2.84 ± 0.26  2.05 ± 0.44

In [316]:
df_results

Metric                              R2                                         \
Model                              CAT    EN Ensemble   KNN   LBM    LR   MLP
C2RCC_rhow_1x1_depth_lt_1         0.56  0.45     0.64  0.66  0.62  0.64  0.09
C2RCC_rhow_3x3_depth_lt_1         0.59  0.40     0.71  0.65  0.54  0.47  0.64
C2RCC_rhow_5x5_depth_lt_1         0.62  0.49     0.75  0.68  0.68  0.64  0.71
C2RCC_rhow_9x9_depth_lt_1         0.77  0.48     0.64  0.65  0.78  0.49  0.67
C2RCC_rhown_1x1_depth_lt_1        0.51  0.42     0.68  0.69  0.56  0.44  0.16
C2RCC_rhown_3x3_depth_lt_1        0.56  0.39     0.72  0.64  0.53  0.48  0.65
C2RCC_rhown_5x5_depth_lt_1        0.63  0.47     0.74  0.70  0.73  0.62  0.71
C2RCC_rhown_9x9_depth_lt_1        0.82  0.47     0.55  0.65  0.80  0.55  0.65
C2X-Complex_rhow_1x1_depth_lt_1   0.70  0.50     0.60  0.69  0.59  0.15  0.51
C2X-Complex_rhow_3x3_depth_lt_1   0.73  0.39     0.54  0.61  0.60  0.10  0.67
C2X-Complex_rhow_5x5_depth_lt_1   0.72  0.37     0.63  0.60  0.65 -2.23  0.55
C2X-Complex_rhow_9x9_depth_lt_1   0.81  0.53     0.69  0.66  0.73  0.41  0.71
C2X-Complex_rhown_1x1_depth_lt_1  0.73  0.54     0.70  0.70  0.65  0.55  0.65
C2X-Complex_rhown_3x3_depth_lt_1  0.67  0.38     0.68  0.56  0.51  0.54  0.61
C2X-Complex_rhown_5x5_depth_lt_1  0.78  0.44     0.76  0.63  0.72  0.49  0.65
C2X-Complex_rhown_9x9_depth_lt_1  0.79  0.58     0.76  0.67  0.75  0.45  0.62
C2X_rhow_1x1_depth_lt_1           0.68  0.63     0.68  0.62  0.54  0.08  0.57
C2X_rhow_3x3_depth_lt_1           0.65  0.48     0.30  0.61  0.50 -0.88  0.56
C2X_rhow_5x5_depth_lt_1           0.54  0.57     0.68  0.56  0.36  0.54  0.58
C2X_rhow_9x9_depth_lt_1           0.68  0.72     0.74  0.74  0.60  0.37  0.58
C2X_rhown_1x1_depth_lt_1          0.59  0.58     0.58  0.52  0.49  0.33  0.47
C2X_rhown_3x3_depth_lt_1          0.62  0.33     0.63  0.51  0.49  0.03  0.58
C2X_rhown_5x5_depth_lt_1          0.51  0.40     0.42  0.46  0.35  0.72  0.53
C2X_rhown_9x9_depth_lt_1          0.68  0.66     0.66  0.58  0.50  0.47  0.65
TOA_1x1_depth_lt_1                0.37  0.08     0.40  0.43  0.59  0.27  0.64
TOA_3x3_depth_lt_1                0.58  0.15     0.48  0.47  0.65  0.45  0.57
TOA_5x5_depth_lt_1                0.56  0.22     0.48  0.50  0.60  0.38  0.55
TOA_9x9_depth_lt_1                0.60  0.21     0.43  0.51  0.58 -0.03  0.56

Metric                                              RMSE                       \
Model                               RF   SVR   XGB   CAT    EN Ensemble   KNN
C2RCC_rhow_1x1_depth_lt_1         0.65  0.64  0.50  3.17  3.55     2.86  2.76
C2RCC_rhow_3x3_depth_lt_1         0.62  0.63  0.57  3.04  3.71     2.57  2.82
C2RCC_rhow_5x5_depth_lt_1         0.67  0.68  0.73  2.94  3.42     2.40  2.68
C2RCC_rhow_9x9_depth_lt_1         0.72  0.62  0.79  2.27  3.44     2.88  2.81
C2RCC_rhown_1x1_depth_lt_1        0.61  0.62  0.52  3.34  3.62     2.69  2.64
C2RCC_rhown_3x3_depth_lt_1        0.59  0.64  0.67  3.17  3.71     2.50  2.87
C2RCC_rhown_5x5_depth_lt_1        0.67  0.67  0.72  2.88  3.46     2.45  2.62
C2RCC_rhown_9x9_depth_lt_1        0.73  0.63  0.80  2.02  3.47     3.20  2.81
C2X-Complex_rhow_1x1_depth_lt_1   0.62  0.58  0.62  2.61  3.36     3.03  2.66
C2X-Complex_rhow_3x3_depth_lt_1   0.61  0.71  0.62  2.47  3.74     3.24  2.98
C2X-Complex_rhow_5x5_depth_lt_1   0.59  0.73  0.62  2.51  3.77     2.91  3.02
C2X-Complex_rhow_9x9_depth_lt_1   0.70  0.66  0.67  2.08  3.25     2.66  2.79
C2X-Complex_rhown_1x1_depth_lt_1  0.59  0.62  0.64  2.49  3.22     2.62  2.59
C2X-Complex_rhown_3x3_depth_lt_1  0.57  0.72  0.66  2.72  3.77     2.68  3.16
C2X-Complex_rhown_5x5_depth_lt_1  0.65  0.71  0.69  2.24  3.57     2.33  2.89
C2X-Complex_rhown_9x9_depth_lt_1  0.68  0.74  0.70  2.20  3.10     2.35  2.73
C2X_rhow_1x1_depth_lt_1           0.62  0.68  0.66  2.71  2.90     2.68  2.94
C2X_rhow_3x3_depth_lt_1           0.60  0.62  0.56  2.83  3.45     3.98  2.97
C2X_rhow_5x5_depth_lt_1           0.51  0.65  0.43  3.25  3.14     2.69  3.15
C2X_rhow_9x9_depth_lt_1           0.67  0.75  0.64  2.70  2.50     2.42  2.42
C2X_rhown_1x1_depth_lt_1          0.54  0.53  0.55  3.05  3.10     3.08  3.32
C2X_rhown_3x3_depth_lt_1          0.53  0.57  0.40  2.95  3.89     2.88  3.34
C2X_rhown_5x5_depth_lt_1          0.43  0.58  0.39  3.34  3.68     3.62  3.52
C2X_rhown_9x9_depth_lt_1          0.61  0.67  0.60  2.70  2.78     2.78  3.09
TOA_1x1_depth_lt_1                0.14  0.37  0.22  2.81  3.39     2.73  2.67
TOA_3x3_depth_lt_1                0.40  0.38  0.37  2.29  3.26     2.56  2.57
TOA_5x5_depth_lt_1                0.46  0.39  0.39  2.33  3.13     2.56  2.51
TOA_9x9_depth_lt_1                0.39  0.43  0.37  2.25  3.14     2.67  2.48

Metric
Model                              LBM    LR   MLP    RF   SVR   XGB
C2RCC_rhow_1x1_depth_lt_1         2.93  2.88  4.55  2.82  2.85  3.37
C2RCC_rhow_3x3_depth_lt_1         3.25  3.45  2.88  2.93  2.89  3.11
C2RCC_rhow_5x5_depth_lt_1         2.68  2.85  2.57  2.75  2.70  2.47
C2RCC_rhow_9x9_depth_lt_1         2.26  3.41  2.74  2.50  2.96  2.17
C2RCC_rhown_1x1_depth_lt_1        3.18  3.57  4.37  2.97  2.93  3.32
C2RCC_rhown_3x3_depth_lt_1        3.25  3.42  2.83  3.06  2.88  2.72
C2RCC_rhown_5x5_depth_lt_1        2.50  2.92  2.55  2.73  2.73  2.52
C2RCC_rhown_9x9_depth_lt_1        2.14  3.20  2.81  2.49  2.91  2.12
C2X-Complex_rhow_1x1_depth_lt_1   3.06  4.39  3.35  2.96  3.10  2.95
C2X-Complex_rhow_3x3_depth_lt_1   3.00  4.52  2.73  2.97  2.55  2.95
C2X-Complex_rhow_5x5_depth_lt_1   2.82  8.57  3.19  3.07  2.46  2.95
C2X-Complex_rhow_9x9_depth_lt_1   2.46  3.68  2.57  2.60  2.77  2.75
C2X-Complex_rhown_1x1_depth_lt_1  2.83  3.19  2.81  3.04  2.95  2.87
C2X-Complex_rhown_3x3_depth_lt_1  3.33  3.24  2.99  3.13  2.53  2.79
C2X-Complex_rhown_5x5_depth_lt_1  2.51  3.42  2.83  2.83  2.58  2.64
C2X-Complex_rhown_9x9_depth_lt_1  2.40  3.53  2.95  2.71  2.44  2.63
C2X_rhow_1x1_depth_lt_1           3.25  4.56  3.13  2.96  2.68  2.80
C2X_rhow_3x3_depth_lt_1           3.37  6.54  3.17  3.00  2.94  3.15
C2X_rhow_5x5_depth_lt_1           3.82  3.22  3.10  3.33  2.81  3.61
C2X_rhow_9x9_depth_lt_1           3.02  3.77  3.09  2.72  2.40  2.86
C2X_rhown_1x1_depth_lt_1          3.40  3.92  3.47  3.24  3.27  3.18
C2X_rhown_3x3_depth_lt_1          3.39  4.70  3.08  3.26  3.13  3.68
C2X_rhown_5x5_depth_lt_1          3.85  2.54  3.28  3.59  3.08  3.72
C2X_rhown_9x9_depth_lt_1          3.38  3.46  2.82  2.97  2.75  3.03
TOA_1x1_depth_lt_1                2.27  3.01  2.13  3.28  2.82  3.12
TOA_3x3_depth_lt_1                2.10  2.61  2.33  2.74  2.78  2.81
TOA_5x5_depth_lt_1                2.23  2.79  2.38  2.61  2.77  2.77
TOA_9x9_depth_lt_1                2.29  3.59  2.35  2.76  2.67  2.82

### Entrenamiento con CV de todo

In [59]:
from itertools import islice

In [78]:
FOLDS = 5

results = {}

for nombre_df, df in list(dfs.items()):
#for nombre_df, df in islice(dfs.items(), 3):
    print(f"\n=== Procesando {nombre_df} ===")
    # Ignoramos las columnas de Date, Lat, Lon y Buoy
    df = df.iloc[:, 4:]

    # Separamos el conjunto de datos en train y test: Train 75% Test 25%
    train, test = train_test_split(df, test_size=0.25, random_state=42, stratify=df["High_Chl"])
    # Seleccionamos la columna que queremos predecir
    target = "Chl"

    # Quitamos esa columna y el indicador de clorofila alta
    X = train.drop(columns=[target, "High_Chl"])
    # Para y cogemos solamente Chl
    y = train[target]
    # Para poder hacer StratifiedKFold y tener el mismo número de valores de Chl alta en cada fold
    y_class = train["High_Chl"]

    # Definimos X e y para test
    X_test = test.drop(columns=[target, "High_Chl"])
    y_test = test[target]

    # Dicts para guardar las predicciones sobre los conjuntos de validación, las y's correspondientes y los índices que corresponden dentro del loop de folds para el ensemble
    val_preds = {name: np.zeros(len(train)) for name in models}
    y_vals = defaultdict(list)
    val_indices = {}
    # Dict para guardar las predicciones sobre test
    test_preds = {name: np.zeros(len(test)) for name in models}

    # scaler_X = RobustScaler()
    # scaler_y = RobustScaler()
    # X_scaled = scaler_X.fit_transform(X)
    # X_test_scaled = scaler_X.transform(X_test)
    # y_scaled = scaler_y.fit_transform(y.values.reshape(-1, 1)).ravel()

    # Stratified KFold de 5 folds
    skf = StratifiedKFold(n_splits=FOLDS, shuffle=True, random_state=42)

    # Dict para guardar resultados
    results[nombre_df] = {name: {'RMSE': [], 'R2': []} for name in models}

    # Loop para entrenar cada uno de los modelos
    for name, model in models.items():
        print(f"\n=== Training {name} ===")
        # Loop de folds, manteniendo la proporción de clases (Chl > 5) con y_class
        for fold, (train_idx, val_idx) in enumerate(skf.split(X, y_class)):
            print(f"Fold {fold+1}")
            X_train, X_val = X.iloc[train_idx], X.iloc[val_idx]
            y_train, y_val = y.iloc[train_idx], y.iloc[val_idx]

            # Para modelos basados en distancias escalamos los datos
            if name in ["MLP", "SVR", "KNN", "LR", "EN"]:
                # Escalado dentro del loop de folds para evitar data leakage entre folds
                scaler_X = RobustScaler()
                scaler_y = RobustScaler()
                X_train_scaled = scaler_X.fit_transform(X_train)
                X_val_scaled = scaler_X.transform(X_val)
                X_test_scaled = scaler_X.transform(X_test)
                y_train_scaled = scaler_y.fit_transform(y_train.values.reshape(-1, 1)).ravel()
                # Entrenamos modelo con datos escalados
                model.fit(X_train_scaled, y_train_scaled)
                # Predicción sobre val y test, haciendo la transformada inversa para devolver y a su escala
                val_pred = scaler_y.inverse_transform(model.predict(X_val_scaled).reshape(-1, 1)).ravel()
                test_pred = scaler_y.inverse_transform(model.predict(X_test_scaled).reshape(-1, 1)).ravel()
            # Para modelos basados en árboles no es necesario escalar
            else:
                # Entrenamos el modelo
                model.fit(X_train, y_train)
                # Predicción sobre val y test
                val_pred = model.predict(X_val)
                test_pred = model.predict(X_test)

            # Guardamos las predicciones sobre val, las y's que les corresponden y los índices
            val_preds[name][val_idx] = val_pred
            if name == list(models.keys())[0]:
                # Solo lo guardamos una vez
                y_vals[fold] = y_val
                val_indices[fold] = val_idx  # val_idx es un array de índices relativos a train

            # Guardamos la predicción de test, haciendo la media entre los folds
            test_preds[name] += test_pred / FOLDS

            # Calculamos y guardamos métricas
            rmse = np.sqrt(mean_squared_error(y_val, val_pred))
            r2 = r2_score(y_val, val_pred)
            results[nombre_df][name]['RMSE'].append(rmse)
            results[nombre_df][name]['R2'].append(r2)

    # Extendemos el dict de resultados con el ensemble
    results[nombre_df]["Ensemble"] = {'RMSE': [], 'R2': []}

    for fold in range(FOLDS):
        # Índices y valores del fold actual
        fold_val_idx = val_indices[fold]
        meta_X_val = np.vstack([val_preds[model][fold_val_idx] for model in models]).T
        meta_y_val = y_vals[fold]

        # Índices de entrenamiento: todos menos el fold actual
        train_folds = [i for i in range(FOLDS) if i != fold]
        train_idx = np.concatenate([val_indices[i] for i in train_folds])
        meta_X_train = np.vstack([val_preds[model][train_idx] for model in models]).T
        meta_y_train = y.iloc[train_idx]

        # Entrenamos el meta-modelo solo con los otros 4 folds
        meta_model = Ridge().fit(meta_X_train, meta_y_train)

        # Predicción en el fold actual (no visto)
        ensemble_pred = meta_model.predict(meta_X_val)

        rmse = np.sqrt(mean_squared_error(meta_y_val, ensemble_pred))
        r2 = r2_score(meta_y_val, ensemble_pred)
        results[nombre_df]["Ensemble"]['RMSE'].append(rmse)
        results[nombre_df]["Ensemble"]['R2'].append(r2)



# === Evaluación final sobre test ===
    for name in models:
        rmse_test = np.sqrt(mean_squared_error(y_test, test_preds[name]))
        r2_test = r2_score(y_test, test_preds[name])
        results[nombre_df][name]["RMSE test"] = rmse_test
        results[nombre_df][name]["R2 test"] = r2_test

    # Construcción del meta-modelo sobre todo el conjunto de validación
    final_meta_X = np.vstack([val_preds[model] for model in models]).T
    final_meta_y = y.values
    ensemble_model = Ridge().fit(final_meta_X, final_meta_y)

    # Predicción sobre test del ensemble
    meta_X_test = np.vstack([test_preds[model] for model in models]).T
    ensemble_test_pred = ensemble_model.predict(meta_X_test)
    # Evaluación del ensemble sobre test
    rmse_ens_test = np.sqrt(mean_squared_error(y_test, ensemble_test_pred))
    r2_ens_test = r2_score(y_test, ensemble_test_pred)
    results[nombre_df]["Ensemble"]["RMSE test"] = rmse_ens_test
    results[nombre_df]["Ensemble"]["R2 test"] = r2_ens_test

=== Procesando C2RCC_rhow_5x5_depth_lt_1 ===

=== Training XGB ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Training LBM ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Training MLP ===
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

=== Training KNN ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Training RF ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Training CAT ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Training EN ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_3x3_depth_lt_1 ===

=== Training XGB ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Training LBM ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Training MLP ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Training KNN ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Training RF ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Training CAT ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Training EN ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_9x9_depth_lt_1 ===

=== Training XGB ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Training LBM ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Training MLP ===
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

=== Training KNN ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Training RF ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Training CAT ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Training EN ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

In [26]:
with open(f"training_results/results_entrenamiento_CV_{depth}.pkl", "wb") as f:
    pickle.dump(results, f)

In [38]:
with open(f"training_results/results_entrenamiento_CV_{depth}.pkl", "rb") as f:
    results = pickle.load(f)

In [79]:
rows = []

for df_name, model_scores in results.items():
    row = {}
    for model_name, metrics in model_scores.items():
        for metric_name, values in metrics.items():
            if isinstance(values, list):  # Solo para los que tienen listas (folds)
                mean_val = np.mean(values)
                std_val = np.std(values)
                row[(metric_name, model_name)] = f"{mean_val:.2f} ± {std_val:.2f}"
            else:
                # Para el ensemble que tiene un único valor
                row[(metric_name, model_name)] = f"{values:.2f}"
    rows.append((df_name, row))

df_results = pd.DataFrame.from_dict(dict(rows), orient="index")
df_results.columns = pd.MultiIndex.from_tuples(df_results.columns, names=["Metric", "Model"])
df_results = df_results.sort_index(axis=1, level=0)
df_results = df_results.sort_index(axis=0)

In [80]:
df_results

Metric                                     R2                            \
Model                                     CAT           EN     Ensemble
C2RCC_rhow_5x5_depth_lt_1         0.69 ± 0.10  0.40 ± 0.05  0.58 ± 0.18
C2X-Complex_rhown_3x3_depth_lt_1  0.57 ± 0.23  0.37 ± 0.11  0.37 ± 0.30
TOA_9x9_depth_lt_1                0.77 ± 0.13  0.01 ± 0.01  0.66 ± 0.13

Metric                                                                   \
Model                                     KNN          LBM          MLP
C2RCC_rhow_5x5_depth_lt_1         0.67 ± 0.13  0.60 ± 0.20  0.53 ± 0.12
C2X-Complex_rhown_3x3_depth_lt_1  0.49 ± 0.24  0.42 ± 0.34  0.33 ± 0.17
TOA_9x9_depth_lt_1                0.72 ± 0.10  0.66 ± 0.12  0.48 ± 0.19

Metric                                                     R2 test        ...  \
Model                                      RF          XGB     CAT    EN  ...
C2RCC_rhow_5x5_depth_lt_1         0.64 ± 0.09  0.65 ± 0.09    0.76  0.37  ...
C2X-Complex_rhown_3x3_depth_lt_1  0.55 ± 0.24  0.52 ± 0.31    0.69  0.38  ...
TOA_9x9_depth_lt_1                0.69 ± 0.13  0.66 ± 0.20    0.70  0.09  ...

Metric                                   RMSE              RMSE test        \
Model                                      RF          XGB       CAT    EN
C2RCC_rhow_5x5_depth_lt_1         2.13 ± 0.11  2.10 ± 0.13      2.29  3.74
C2X-Complex_rhown_3x3_depth_lt_1  2.31 ± 0.46  2.37 ± 0.59      2.63  3.74
TOA_9x9_depth_lt_1                2.15 ± 0.54  2.20 ± 0.69      2.15  3.71

Metric
Model                            Ensemble   KNN   LBM   MLP    RF   XGB
C2RCC_rhow_5x5_depth_lt_1            2.29  2.47  2.45  2.66  2.52  2.32
C2X-Complex_rhown_3x3_depth_lt_1     2.79  2.93  2.88  3.51  2.95  2.79
TOA_9x9_depth_lt_1                   2.14  2.45  2.63  2.55  2.51  2.58

[3 rows x 32 columns]

In [83]:
# Asumiendo que tu DataFrame se llama df_results
df_sorted = df_results["R2 test"].copy()

# Añadir una columna auxiliar con el R2 máximo por fila
df_sorted["max_R2"] = df_sorted.max(axis=1)

# Ordenar por esa columna en orden descendente
df_sorted = df_sorted.sort_values("max_R2", ascending=False)

# Eliminar la columna auxiliar
df_sorted = df_sorted.drop(columns="max_R2")

In [82]:
df_sorted

Model,CAT,EN,Ensemble,KNN,LBM,MLP,RF,XGB
TOA_9x9_depth_lt_1,0.77 ± 0.13,0.01 ± 0.01,0.66 ± 0.13,0.72 ± 0.10,0.66 ± 0.12,0.48 ± 0.19,0.69 ± 0.13,0.66 ± 0.20
C2RCC_rhow_5x5_depth_lt_1,0.69 ± 0.10,0.40 ± 0.05,0.58 ± 0.18,0.67 ± 0.13,0.60 ± 0.20,0.53 ± 0.12,0.64 ± 0.09,0.65 ± 0.09
C2X-Complex_rhown_3x3_depth_lt_1,0.57 ± 0.23,0.37 ± 0.11,0.37 ± 0.30,0.49 ± 0.24,0.42 ± 0.34,0.33 ± 0.17,0.55 ± 0.24,0.52 ± 0.31

In [84]:
df_sorted

Model,CAT,EN,Ensemble,KNN,LBM,MLP,RF,XGB
C2RCC_rhow_5x5_depth_lt_1,0.76,0.37,0.77,0.73,0.73,0.68,0.72,0.76
TOA_9x9_depth_lt_1,0.70,0.09,0.70,0.60,0.54,0.57,0.58,0.56
C2X-Complex_rhown_3x3_depth_lt_1,0.69,0.38,0.65,0.62,0.63,0.45,0.61,0.65

In [40]:
df_results["R2 test"]

Model,CAT,EN,Ensemble,KNN,LBM,LR,MLP,RF,SVR,XGB
C2RCC_rhow_1x1_depth_lt_1,0.74,0.46,0.74,0.72,0.70,0.62,0.61,0.69,0.69,0.75
C2RCC_rhow_3x3_depth_lt_1,0.71,0.42,0.66,0.66,0.72,0.39,0.56,0.67,0.72,0.71
C2RCC_rhow_5x5_depth_lt_1,0.76,0.49,0.76,0.73,0.76,0.39,0.65,0.71,0.77,0.78
C2RCC_rhow_9x9_depth_lt_1,0.81,0.48,0.76,0.70,0.77,0.63,0.69,0.72,0.75,0.80
C2RCC_rhown_1x1_depth_lt_1,0.73,0.45,0.77,0.76,0.69,0.53,0.62,0.68,0.68,0.75
C2RCC_rhown_3x3_depth_lt_1,0.74,0.42,0.64,0.63,0.71,0.43,0.67,0.65,0.71,0.72
C2RCC_rhown_5x5_depth_lt_1,0.76,0.48,0.71,0.69,0.76,0.56,0.67,0.72,0.75,0.79
C2RCC_rhown_9x9_depth_lt_1,0.79,0.48,0.72,0.68,0.77,0.53,0.63,0.73,0.75,0.77
C2X-Complex_rhow_1x1_depth_lt_1,0.73,0.53,0.78,0.75,0.68,0.43,0.62,0.64,0.62,0.75
C2X-Complex_rhow_3x3_depth_lt_1,0.72,0.39,0.74,0.68,0.64,0.11,0.61,0.64,0.73,0.66
C2X-Complex_rhow_5x5_depth_lt_1,0.79,0.41,0.80,0.66,0.68,-0.31,0.59,0.68,0.78,0.73
C2X-Complex_rhow_9x9_depth_lt_1,0.86,0.55,0.82,0.74,0.86,0.48,0.63,0.79,0.74,0.83
C2X-Complex_rhown_1x1_depth_lt_1,0.74,0.57,0.79,0.76,0.64,0.57,0.63,0.60,0.67,0.71
C2X-Complex_rhown_3x3_depth_lt_1,0.69,0.39,0.72,0.64,0.57,0.59,0.51,0.61,0.73,0.65
C2X-Complex_rhown_5x5_depth_lt_1,0.77,0.46,0.80,0.67,0.72,0.52,0.56,0.68,0.75,0.73
C2X-Complex_rhown_9x9_depth_lt_1,0.82,0.57,0.80,0.77,0.78,0.68,0.69,0.74,0.76,0.77
C2X_rhow_1x1_depth_lt_1,0.58,0.64,0.71,0.69,0.50,0.40,0.58,0.59,0.68,0.62
C2X_rhow_3x3_depth_lt_1,0.60,0.40,0.54,0.63,0.55,0.59,0.47,0.56,0.63,0.63
C2X_rhow_5x5_depth_lt_1,0.56,0.50,0.62,0.58,0.54,0.67,0.63,0.60,0.67,0.48
C2X_rhow_9x9_depth_lt_1,0.63,0.67,0.71,0.75,0.65,0.69,0.53,0.69,0.73,0.64
C2X_rhown_1x1_depth_lt_1,0.56,0.58,0.62,0.58,0.59,0.47,0.56,0.60,0.61,0.58
C2X_rhown_3x3_depth_lt_1,0.59,0.25,0.56,0.56,0.52,0.57,0.38,0.52,0.62,0.56
C2X_rhown_5x5_depth_lt_1,0.49,0.36,0.48,0.55,0.43,-0.08,0.56,0.49,0.65,0.44
C2X_rhown_9x9_depth_lt_1,0.59,0.62,0.65,0.66,0.58,0.72,0.63,0.61,0.69,0.60
TOA_1x1_depth_lt_1,0.61,0.23,0.61,0.54,0.61,0.59,0.49,0.54,0.46,0.61
TOA_3x3_depth_lt_1,0.68,0.27,0.65,0.63,0.56,0.54,0.42,0.59,0.48,0.57
TOA_5x5_depth_lt_1,0.72,0.31,0.67,0.62,0.62,0.54,0.57,0.64,0.49,0.67
TOA_9x9_depth_lt_1,0.70,0.31,0.68,0.63,0.59,0.26,0.53,0.56,0.51,0.60

In [29]:
df_results["R2"]

Model,CAT,EN,Ensemble,KNN,LBM,LR,MLP,RF,SVR,XGB
C2RCC_rhow_1x1_depth_gt_3,0.39 ± 0.10,0.25 ± 0.06,0.55 ± 0.09,0.35 ± 0.12,0.38 ± 0.11,-0.54 ± 1.52,0.39 ± 0.08,0.35 ± 0.10,0.37 ± 0.11,0.37 ± 0.08
C2RCC_rhow_3x3_depth_gt_3,0.40 ± 0.13,0.27 ± 0.05,0.61 ± 0.07,0.39 ± 0.10,0.40 ± 0.10,0.24 ± 0.18,0.35 ± 0.08,0.42 ± 0.13,0.40 ± 0.10,0.38 ± 0.15
C2RCC_rhow_5x5_depth_gt_3,0.48 ± 0.13,0.29 ± 0.05,0.65 ± 0.10,0.46 ± 0.11,0.45 ± 0.13,0.08 ± 0.58,0.40 ± 0.05,0.46 ± 0.13,0.48 ± 0.09,0.47 ± 0.14
C2RCC_rhow_9x9_depth_gt_3,0.51 ± 0.08,0.29 ± 0.05,0.68 ± 0.09,0.42 ± 0.12,0.50 ± 0.09,0.30 ± 0.17,0.39 ± 0.05,0.48 ± 0.08,0.54 ± 0.06,0.49 ± 0.09
C2RCC_rhown_1x1_depth_gt_3,0.39 ± 0.09,0.25 ± 0.06,0.58 ± 0.08,0.35 ± 0.10,0.34 ± 0.11,0.23 ± 0.08,0.32 ± 0.08,0.38 ± 0.11,0.38 ± 0.11,0.42 ± 0.08
C2RCC_rhown_3x3_depth_gt_3,0.40 ± 0.11,0.27 ± 0.05,0.59 ± 0.12,0.40 ± 0.09,0.44 ± 0.13,0.22 ± 0.14,0.42 ± 0.09,0.43 ± 0.10,0.42 ± 0.10,0.39 ± 0.14
C2RCC_rhown_5x5_depth_gt_3,0.46 ± 0.11,0.29 ± 0.05,0.70 ± 0.06,0.50 ± 0.11,0.53 ± 0.09,0.20 ± 0.22,0.47 ± 0.05,0.49 ± 0.10,0.49 ± 0.09,0.50 ± 0.09
C2RCC_rhown_9x9_depth_gt_3,0.52 ± 0.10,0.29 ± 0.05,0.70 ± 0.06,0.45 ± 0.13,0.48 ± 0.12,0.05 ± 0.47,0.38 ± 0.07,0.51 ± 0.09,0.56 ± 0.06,0.50 ± 0.11
C2X-Complex_rhow_1x1_depth_gt_3,0.45 ± 0.08,0.19 ± 0.19,0.66 ± 0.04,0.34 ± 0.07,0.33 ± 0.13,-1.95 ± 3.97,0.36 ± 0.07,0.39 ± 0.10,0.41 ± 0.07,0.45 ± 0.08
C2X-Complex_rhow_3x3_depth_gt_3,0.48 ± 0.05,0.28 ± 0.02,0.71 ± 0.04,0.45 ± 0.07,0.34 ± 0.07,0.29 ± 0.16,0.47 ± 0.05,0.44 ± 0.08,0.46 ± 0.12,0.39 ± 0.12
C2X-Complex_rhow_5x5_depth_gt_3,0.47 ± 0.08,0.30 ± 0.04,0.69 ± 0.09,0.44 ± 0.10,0.39 ± 0.08,-0.79 ± 2.14,0.36 ± 0.11,0.45 ± 0.08,0.45 ± 0.08,0.41 ± 0.08
C2X-Complex_rhow_9x9_depth_gt_3,0.55 ± 0.07,0.31 ± 0.03,0.69 ± 0.04,0.51 ± 0.08,0.44 ± 0.08,0.16 ± 0.22,0.41 ± 0.09,0.46 ± 0.07,0.49 ± 0.03,0.46 ± 0.12
C2X-Complex_rhown_1x1_depth_gt_3,0.46 ± 0.09,0.22 ± 0.15,0.63 ± 0.06,0.36 ± 0.11,0.41 ± 0.10,-0.90 ± 1.39,0.24 ± 0.29,0.41 ± 0.09,0.42 ± 0.08,0.47 ± 0.06
C2X-Complex_rhown_3x3_depth_gt_3,0.46 ± 0.07,0.24 ± 0.09,0.70 ± 0.06,0.43 ± 0.11,0.40 ± 0.09,-0.67 ± 1.25,0.35 ± 0.09,0.45 ± 0.09,0.45 ± 0.13,0.44 ± 0.12
C2X-Complex_rhown_5x5_depth_gt_3,0.47 ± 0.06,0.27 ± 0.07,0.68 ± 0.05,0.45 ± 0.14,0.36 ± 0.10,-0.96 ± 2.46,0.33 ± 0.18,0.45 ± 0.09,0.45 ± 0.11,0.39 ± 0.14
C2X-Complex_rhown_9x9_depth_gt_3,0.54 ± 0.06,0.31 ± 0.04,0.64 ± 0.04,0.52 ± 0.08,0.46 ± 0.13,0.26 ± 0.16,0.43 ± 0.07,0.50 ± 0.04,0.49 ± 0.04,0.49 ± 0.06
C2X_rhow_1x1_depth_gt_3,0.40 ± 0.06,0.26 ± 0.10,0.57 ± 0.06,0.31 ± 0.11,0.36 ± 0.17,-5.54 ± 11.10,0.32 ± 0.05,0.42 ± 0.08,0.30 ± 0.08,0.42 ± 0.08
C2X_rhow_3x3_depth_gt_3,0.50 ± 0.06,0.27 ± 0.04,0.68 ± 0.05,0.39 ± 0.14,0.44 ± 0.10,0.01 ± 0.39,0.39 ± 0.06,0.46 ± 0.06,0.44 ± 0.11,0.47 ± 0.02
C2X_rhow_5x5_depth_gt_3,0.53 ± 0.08,0.29 ± 0.05,0.66 ± 0.08,0.42 ± 0.08,0.45 ± 0.15,0.05 ± 0.40,0.37 ± 0.07,0.49 ± 0.05,0.43 ± 0.10,0.46 ± 0.06
C2X_rhow_9x9_depth_gt_3,0.43 ± 0.19,0.29 ± 0.03,0.66 ± 0.09,0.41 ± 0.08,0.33 ± 0.32,-0.62 ± 1.11,0.29 ± 0.22,0.39 ± 0.19,0.47 ± 0.08,0.37 ± 0.28
C2X_rhown_1x1_depth_gt_3,0.40 ± 0.07,0.26 ± 0.10,0.54 ± 0.08,0.33 ± 0.09,0.36 ± 0.08,-0.74 ± 1.78,0.36 ± 0.08,0.39 ± 0.07,0.31 ± 0.09,0.43 ± 0.06
C2X_rhown_3x3_depth_gt_3,0.51 ± 0.03,0.27 ± 0.05,0.67 ± 0.07,0.39 ± 0.11,0.45 ± 0.10,0.07 ± 0.24,0.34 ± 0.17,0.46 ± 0.04,0.42 ± 0.10,0.49 ± 0.02
C2X_rhown_5x5_depth_gt_3,0.52 ± 0.06,0.29 ± 0.05,0.64 ± 0.09,0.46 ± 0.05,0.40 ± 0.07,-0.92 ± 1.56,0.39 ± 0.06,0.48 ± 0.06,0.45 ± 0.07,0.46 ± 0.04
C2X_rhown_9x9_depth_gt_3,0.48 ± 0.14,0.29 ± 0.03,0.65 ± 0.13,0.37 ± 0.11,0.41 ± 0.23,-0.10 ± 0.59,0.28 ± 0.09,0.43 ± 0.17,0.47 ± 0.09,0.43 ± 0.27
TOA_1x1_depth_gt_3,0.56 ± 0.07,0.07 ± 0.11,0.74 ± 0.05,0.55 ± 0.13,0.54 ± 0.08,0.31 ± 0.08,0.20 ± 0.26,0.46 ± 0.13,0.56 ± 0.17,0.52 ± 0.09
TOA_3x3_depth_gt_3,0.54 ± 0.06,0.08 ± 0.11,0.73 ± 0.07,0.57 ± 0.11,0.52 ± 0.08,0.23 ± 0.21,0.16 ± 0.17,0.47 ± 0.12,0.56 ± 0.13,0.50 ± 0.09
TOA_5x5_depth_gt_3,0.57 ± 0.07,0.09 ± 0.11,0.75 ± 0.06,0.57 ± 0.08,0.53 ± 0.12,0.31 ± 0.09,0.37 ± 0.25,0.48 ± 0.10,0.58 ± 0.13,0.54 ± 0.09
TOA_9x9_depth_gt_3,0.63 ± 0.08,0.07 ± 0.11,0.79 ± 0.06,0.65 ± 0.09,0.58 ± 0.09,0.16 ± 0.16,0.39 ± 0.22,0.51 ± 0.16,0.58 ± 0.12,0.56 ± 0.15