In [288]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import os
pd.options.mode.chained_assignment = None
import optuna
import time
from sklearn.metrics import r2_score, mean_squared_error
from sklearn.model_selection import cross_val_score, KFold, StratifiedKFold, train_test_split
from xgboost import XGBRegressor
from catboost import CatBoostRegressor
from lightgbm import LGBMRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression, Ridge, ElasticNet
from sklearn.neighbors import KNeighborsRegressor
from sklearn.neural_network import MLPRegressor
from sklearn.svm import SVR
from sklearn.preprocessing import StandardScaler, RobustScaler
import pickle

In [289]:
# Cargamos los csv de los tifs
path = "saved_files/dataset"
depth = "lt_1"
dfs = {}
all_datasets = False
for archivo in os.listdir(path):
    if all_datasets:
        if f"{depth}" in archivo:
            nombre_sin_extension = os.path.splitext(archivo)[0]  # sin .csv
            ruta_completa = os.path.join(path, archivo)
            dfs[nombre_sin_extension] = pd.read_csv(ruta_completa)
    else:
        if archivo.endswith(f"{depth}_features.csv"):
            nombre_sin_extension = os.path.splitext(archivo)[0]  # sin .csv
            ruta_completa = os.path.join(path, archivo)
            dfs[nombre_sin_extension[:-9]] = pd.read_csv(ruta_completa)

In [214]:
dfs.keys()

dict_keys(['C2RCC_rhow_5x5_depth_lt_1', 'C2X-Complex_rhown_3x3_depth_lt_1', 'TOA_9x9_depth_lt_1', 'C2X_rhow_3x3_depth_lt_1', 'C2RCC_rhow_9x9_depth_lt_1', 'C2X-Complex_rhown_5x5_depth_lt_1', 'C2X_rhown_9x9_depth_lt_1', 'TOA_3x3_depth_lt_1', 'C2X-Complex_rhown_9x9_depth_lt_1', 'C2X-Complex_rhow_3x3_depth_lt_1', 'C2X_rhow_1x1_depth_lt_1', 'C2RCC_rhown_1x1_depth_lt_1', 'C2X_rhown_1x1_depth_lt_1', 'C2RCC_rhown_9x9_depth_lt_1', 'C2X_rhow_5x5_depth_lt_1', 'C2X_rhown_5x5_depth_lt_1', 'C2X_rhow_9x9_depth_lt_1', 'C2X_rhown_3x3_depth_lt_1', 'C2RCC_rhown_5x5_depth_lt_1', 'TOA_1x1_depth_lt_1', 'C2X-Complex_rhow_5x5_depth_lt_1', 'C2X-Complex_rhow_9x9_depth_lt_1', 'C2X-Complex_rhow_1x1_depth_lt_1', 'C2X-Complex_rhown_1x1_depth_lt_1', 'C2RCC_rhow_3x3_depth_lt_1', 'TOA_5x5_depth_lt_1', 'C2RCC_rhown_3x3_depth_lt_1', 'C2RCC_rhow_1x1_depth_lt_1'])

In [194]:
dfs["C2RCC_rhow_1x1_depth_lt_1"]

,Date,Buoy,Latitude,Longitude,rhow_B1,rhow_B2,rhow_B3,rhow_B4,rhow_B5,rhow_B6,...,dif_rel_4bands_rhow_B2_B5_B3_B4,dif_rel_4bands_rhow_B2_B5_B4_B3,dif_rel_4bands_rhow_B3_B2_B4_B5,dif_rel_4bands_rhow_B3_B2_B5_B4,dif_rel_4bands_rhow_B3_B4_B5_B2,dif_rel_4bands_rhow_B3_B5_B4_B2,dif_rel_4bands_rhow_B4_B2_B5_B3,dif_rel_4bands_rhow_B4_B3_B5_B2,sum_norm_3bands_rhow_B2_B4_B3,sum_norm_3bands_rhow_B3_B5_B4
0,2016-08-09,CTD1,4187246,695025,0.010973,0.017248,0.033436,0.016780,0.012437,0.003690,...,-0.606,0.885,0.589,1.197,1.272,1.716,0.601,-0.219,0.671,0.914
1,2016-08-09,CTD2,4181518,693105,0.007180,0.010530,0.019375,0.011021,0.008281,0.002545,...,-0.486,0.703,0.509,1.089,0.972,1.293,0.619,-0.218,0.721,0.910
2,2016-08-09,CTD3,4181698,695238,0.007966,0.011565,0.020111,0.010630,0.007752,0.002311,...,-0.400,0.963,0.368,1.010,1.222,1.675,0.534,-0.142,0.701,0.906
3,2016-08-09,CTD4,4180266,698264,0.008062,0.010310,0.014764,0.008631,0.006252,0.001894,...,-0.062,1.064,0.052,0.708,1.104,1.524,0.414,-0.022,0.755,0.898
4,2016-08-09,CTD6,4176009,695829,0.008603,0.013129,0.023304,0.010864,0.007707,0.002229,...,-0.442,1.237,0.365,1.066,1.558,2.196,0.497,-0.121,0.659,0.908
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
446,2023-05-25,CTD8,4174178,693048,0.016512,0.029853,0.043600,0.007112,0.004319,0.001135,...,0.781,6.749,-0.186,0.853,5.986,9.856,0.139,0.018,0.503,0.945
447,2023-05-25,CTD9,4171106,693183,0.007081,0.012752,0.026582,0.009738,0.006888,0.001995,...,-0.879,1.485,0.671,1.377,2.190,3.095,0.505,-0.174,0.572,0.922
448,2023-05-25,CTD10,4170388,695646,0.007636,0.014290,0.026969,0.006672,0.004333,0.001186,...,-0.745,3.050,0.348,1.238,3.739,5.756,0.306,-0.056,0.508,0.930
449,2023-05-25,CTD11,4169609,700351,0.007547,0.014033,0.026831,0.007324,0.004826,0.001328,...,-0.756,2.635,0.394,1.253,3.320,5.038,0.342,-0.071,0.523,0.927
450,2023-05-25,CTD12,4173438,695414,0.010524,0.019697,0.033400,0.006790,0.004274,0.001145,...,-0.310,4.406,0.107,1.066,4.702,7.471,0.217,-0.014,0.499,0.937

In [29]:
# Para seleccionar manualmente qué dataframes nos quedamos
# Si leemos por profundidad ya no hace falta esto
dfs_to_keep = [
    "C2X_1x1_merge_depth_lt_1", "C2X_3x3_merge_depth_lt_1", "C2X_5x5_merge_depth_lt_1", 
    "C2X-Complex_1x1_merge_depth_lt_1", "C2X-Complex_3x3_merge_depth_lt_1", "C2X-Complex_5x5_merge_depth_lt_1",
    "C2RCC_1x1_merge_depth_lt_1", "C2RCC_3x3_merge_depth_lt_1", "C2RCC_5x5_merge_depth_lt_1",
    "TOA_1x1_merge_depth_lt_1", "TOA_3x3_merge_depth_lt_1", "TOA_5x5_merge_depth_lt_1",
]

#dfs = {k: dfs[k] for k in dfs_to_keep if k in dfs}

In [290]:

# Limpiamos valores nulos
for nombre_df, df in dfs.items():
    for band_set in ["rhow", "rhown","rtoa"]:
        dfs[nombre_df] = df.dropna()

In [216]:
def get_season(month):
    if month in [12, 1, 2]:
        return 'Invierno'
    elif month in [3, 4, 5]:
        return 'Primavera'
    elif month in [6, 7, 8]:
        return 'Verano'
    else:
        return 'Otoño'
    

def get_zone(buoy):
    if buoy in ["CTD1", "CTD2", "CTD3", "CTD4"]:
        return 'Zona-1'
    elif buoy in ["CTD6", "CTD8", "CTD9", "CTD10", "CTD12"]:
        return 'Zona-2'
    elif buoy in ["CTD7"]:
        return 'Zona-3'
    elif buoy in ["CTD11"]:
        return 'Zona-4'

In [291]:

for nombre_df, df in dfs.items():
    # Marcamos las columnas de CHl alta (equivalente a quantile(0.93))
    df["High_Chl"] = df["Chl"]>5
    # Sacamos la estación de cada fecha
    df['Date'] = pd.to_datetime(df['Date'])
    df['Season'] = df['Date'].dt.month.apply(get_season)
    
    # Etiquetamos la zona de la observación (comentado porque para aplicar el modelo habría que segmentar todo el Mar Menor - se puede hacer por px)
    # df['Zone'] = df['Buoy'].apply(get_zone)
    # Ponemos las columnas como categóricas, para Season y Zone
    for col in df.select_dtypes(include='object').columns:
        df[col] = df[col].astype('category')

    df = pd.concat([df.drop(columns=["Season"]),pd.get_dummies(df["Season"])], axis=1)
    dfs[nombre_df] = df

In [53]:
# Filtro para quitar columnas muy correlacionadas de cada dataset - de momento no lo usamos
def filtrar_columnas(df):

    # 1. Separar columnas numéricas y no numéricas
    df_numericas = df.select_dtypes(include='number')
    df_no_numericas = df.select_dtypes(exclude='number')

    # 2. Calcular la correlación con 'Chl' solo entre columnas numéricas
    correlaciones = df_numericas.corr()['Chl'].drop('Chl')

    # 3. Filtrar predictores numéricos con correlación significativa
    umbral_corr = 0.1
    columnas_utiles = correlaciones[correlaciones.abs() >= umbral_corr].index.tolist()

    # 4. Reconstruir el DataFrame con:
    # - Las columnas numéricas útiles
    # - La columna objetivo 'Chl'
    df_filtrado = pd.concat([df[columnas_utiles + ['Chl']]], axis=1)

    # Calcular la matriz de correlación entre predictores
    corr_matrix = df_filtrado.drop(columns='Chl').corr().abs()

    # Seleccionar columnas a eliminar (altamente correlacionadas entre sí)
    upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(bool))
    columnas_redundantes = [col for col in upper.columns if any(upper[col] > 0.98)]

    # Eliminar redundantes
    df_final = pd.concat([df_filtrado.drop(columns=columnas_redundantes), df_no_numericas], axis=1)
    df_final = df_final.drop(columns=["Date", "Buoy"])

    return df_final


for nombre_df, df in dfs.items():
    dfs[nombre_df] = filtrar_columnas(df)

In [218]:
model_params ={
    "XGB" : {
        'n_estimators': 1000,
        'learning_rate': 0.01,
        'max_depth': 7,
        'min_child_weight': 3,
        'subsample': 0.9,
        'colsample_bytree': 0.9,
        'device': 'cpu',
        'objective': 'reg:squarederror',
        'tree_method': 'hist',
        'enable_categorical': True,
        #'early_stopping_rounds': 50,
        'eval_metric': 'rmse'
        },

    "LBM" : {
        'learning_rate': 0.05,
        'num_leaves': 20,
        'max_depth': 7,
        'min_child_samples': 3,
        'subsample': 0.6,
        'colsample_bytree': 0.9,
        'n_estimators': 1000,
        'objective': 'regression',
        'metric': 'rmse',
        'boosting_type': 'gbdt',
        'device': 'cpu',  
        'verbosity': -1,
        #'early_stopping_rounds': 50
        },

    "MLP": {
        'hidden_layer_sizes': (100,),
        'activation': 'relu',
        'solver': 'adam',
        'alpha': 0.0001,
        'learning_rate': 'constant',
        'learning_rate_init': 0.001,
        'max_iter': 200,
        'shuffle': True,
        'random_state': None,
        'tol': 1e-4,
        'n_iter_no_change': 25,
        'verbose': False,
        'early_stopping': True,
        'validation_fraction': 0.2
        },

    "SVR": {
        'kernel': 'sigmoid',        
        'C': 1.0,               
        'epsilon': 0.1,           
        'gamma': 'scale',        
        'shrinking': True,
        'tol': 1e-3,
        'max_iter': -1,          
        'verbose': False,
    },

    "KNN": {
        'n_neighbors': 5,
        'weights': 'uniform',      
        'algorithm': 'auto',      
        'leaf_size': 30,
        'p': 2,                    
        'metric': 'minkowski',
        'n_jobs': -1             
    },

    "RF": {
        'n_estimators': 100,         
        'criterion': 'squared_error',
        'max_depth': 10,         
        'min_samples_split': 2,
        'min_samples_leaf': 1,    
        'bootstrap': True,
        'random_state': 42,
        'verbose': 0
    },

    "CAT": {
        'iterations': 1000,
        'learning_rate': 0.03,
        'depth': 6,
        'l2_leaf_reg': 3.0,
        'loss_function': 'RMSE',
        'eval_metric': 'RMSE',
        'random_seed': 42,
        'allow_writing_files': False,
        'early_stopping_rounds': 50,
        'verbose': False
    },

    "EN": {
        'alpha': 1.0,              # fuerza de regularización
        'l1_ratio': 0.5,           # mezcla entre L1 (lasso) y L2 (ridge)
        'fit_intercept': True,
        'max_iter': 1000,
        'tol': 1e-4,
        'selection': 'cyclic',
        'random_state': 42
    }

}


models = {
    "XGB": XGBRegressor(**model_params['XGB']),
    "LBM": LGBMRegressor(**model_params['LBM']),
    "MLP": MLPRegressor(**model_params['MLP']),
    #"SVR": SVR(**model_params['SVR']),
    "KNN": KNeighborsRegressor(**model_params['KNN']),
    #"LR": LinearRegression().
    "RF": RandomForestRegressor(**model_params['RF']),
    "CAT": CatBoostRegressor(**model_params["CAT"]),
    "EN":  ElasticNet(**model_params["EN"])
}

In [241]:
results = {}

for nombre_df, df in list(dfs.items()):
    #print(nombre_df)
    df = df.iloc[:,4:]

    # Para usar solamente bandas, sin combinaciones
    # if 'TOA' in nombre_df:
    #     # TOA solamente con las bandas, parece que las combinaciones solo meten ruido
    #     df = df.iloc[:,np.r_[0:14, 58:60]]
    # if 'rhow' in nombre_df and 'rhown' not in nombre_df:
    #     df = df.iloc[:,np.r_[0:9, 53:55]]
    # if 'rhown' in nombre_df:
    #     df = df.iloc[:,np.r_[0:7, 51:53]]

    train, test = train_test_split(df, test_size=0.2, random_state=42, stratify=df["High_Chl"]) # TEST 20% TRAIN 80%
    target = "Chl"

    train, val = train_test_split(train, test_size=0.25, random_state=42, stratify=train["High_Chl"]) # TRAIN 60% VAL 20% TEST%

    X_train = train.drop(columns=[target,"High_Chl"])
    X_val = val.drop(columns=[target, "High_Chl"])
    X_test = test.drop(columns=[target, "High_Chl"])
    y_train = train[target]
    y_val = val[target]
    y_test = test[target]

    
    scaler_X = RobustScaler()
    scaler_y = RobustScaler()
    X_train_scaled = scaler_X.fit_transform(X_train)
    X_val_scaled = scaler_X.transform(X_val)
    X_test_scaled = scaler_X.transform(X_test)
    y_train_scaled = scaler_y.fit_transform(y_train.values.reshape(-1, 1)).ravel()
    
    results[nombre_df] = {name: {'RMSE': None, 'R2': None} for name in models}
    val_preds = {}
    test_preds = {}

    for name, model in models.items():
        print(f"Fitting {name} for {nombre_df}")
        if name in ["MLP", "SVR", "KNN", "LR", "EN"]:
            model.fit(X_train_scaled, y_train_scaled)
            #test_pred = model.predict(X_test_scaled)
            val_pred = scaler_y.inverse_transform(model.predict(X_val_scaled).reshape(-1, 1)).ravel()
            test_pred = scaler_y.inverse_transform(model.predict(X_test_scaled).reshape(-1, 1)).ravel()
        else:
            model.fit(X_train, y_train)
            val_pred = model.predict(X_val)
            test_pred = model.predict(X_test)

        val_preds[name] = val_pred
        test_preds[name] = test_pred

        rmse = np.sqrt(mean_squared_error(y_test, test_pred))
        r2 = r2_score(y_test, test_pred)

        results[nombre_df][name]['RMSE'] = rmse.round(2)
        results[nombre_df][name]['R2'] = r2.round(2)

    # Meta-modelo
    meta_X = np.vstack([val_preds[model] for model in models]).T
    meta_y = y_val.values
    meta_model = Ridge().fit(meta_X, meta_y)

    # Predicción final ensemble
    test_meta_X = np.vstack([test_preds[model] for model in models]).T
    ensemble_pred = meta_model.predict(test_meta_X)

    rmse_ens = np.sqrt(mean_squared_error(y_test, ensemble_pred))
    r2_ens = r2_score(y_test, ensemble_pred)

    results[nombre_df]["Ensemble"] = {
        "RMSE": round(rmse_ens, 2),
        "R2": round(r2_ens, 2)
    }

Fitting XGB for C2RCC_rhow_5x5_depth_lt_1
Fitting LBM for C2RCC_rhow_5x5_depth_lt_1
Fitting MLP for C2RCC_rhow_5x5_depth_lt_1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fitting SVR for C2RCC_rhow_5x5_depth_lt_1
Fitting KNN for C2RCC_rhow_5x5_depth_lt_1
Fitting LR for C2RCC_rhow_5x5_depth_lt_1
Fitting RF for C2RCC_rhow_5x5_depth_lt_1
Fitting CAT for C2RCC_rhow_5x5_depth_lt_1
Learning rate set to 0.033272
0:	learn: 3.4129684	total: 2ms	remaining: 2s
1:	learn: 3.3568727	total: 3.27ms	remaining: 1.63s
2:	learn: 3.3074897	total: 4.42ms	remaining: 1.47s
3:	learn: 3.2558681	total: 5.56ms	remaining: 1.39s
4:	learn: 3.2071105	total: 6.7ms	remaining: 1.33s
5:	learn: 3.1585027	total: 8.52ms	remaining: 1.41s
6:	learn: 3.1054135	total: 10.4ms	remaining: 1.48s
7:	learn: 3.0560053	total: 12.1ms	remaining: 1.5s
8:	learn: 3.0141211	total: 13.4ms	remaining: 1.48s
9:	learn: 2.9590940	total: 14.6ms	remaining: 1.45s
10:	learn: 2.9136806	total: 15.9ms	remaining: 1.43s
11:	learn: 2.8789791	total: 17.2ms	remaining: 1.41s
12:	learn: 2.8313709	total: 18.4ms	remaining: 1.4s
13:	learn: 2.7964162	total: 19.6ms	remaining: 1.38s
14:	learn: 2.7483571	total: 20.9ms	remaining: 1.37s
15:	learn: 2.7036505	total: 22.6ms	remaining: 1.39s
16:	learn: 2.6640204	total: 23.9ms	remaining: 1.38s
17:	learn: 2.6232271	total: 25.5ms	remaining: 1.39s
18:	learn: 2.5785549	total: 26.9ms	remaining: 1.39s
19:	learn: 2.5397372	total: 28.7ms	remaining: 1.41s
20:	learn: 2.5058942	total: 30ms	remaining: 1.4s
21:	learn: 2.4743586	total: 31.3ms	remaining: 1.39s
22:	learn: 2.4329510	total: 32.7ms	remaining: 1.39s
23:	learn: 2.3942443	total: 33.9ms	remaining: 1.38s
24:	learn: 2.3627443	total: 35.2ms	remaining: 1.37s
25:	learn: 2.3286810	total: 36.4ms	remaining: 1.36s
26:	learn: 2.2908190	total: 37.6ms	remaining: 1.35s
27:	learn: 2.2597761	total: 38.9ms	remaining: 1.35s
28:	learn: 2.2252205	total: 40.3ms	remaining: 1.35s
29:	learn: 2.1886023	total: 41.6ms	remaining: 1.34s
30:	learn: 2.1558736	total: 42.9ms	remaining: 1.34s
31:	learn: 2.1238819	total: 44.1ms	remaining: 1.33s
32:	learn: 2.0989836	total: 45.2ms	remaining: 1.32s
33:	learn: 2.0752784	total: 46.4ms	remaining: 1.32s
34:	learn: 2.0462447	total: 47.9ms	remaining: 1.32s
35:	learn: 2.0199326	total: 49ms	remaining: 1.31s
36:	learn: 1.9939169	total: 50.2ms	remaining: 1.3s
37:	learn: 1.9628489	total: 51.3ms	remaining: 1.3s
38:	learn: 1.9382112	total: 52.5ms	remaining: 1.29s
39:	learn: 1.9124745	total: 53.7ms	remaining: 1.29s
40:	learn: 1.8859240	total: 55.2ms	remaining: 1.29s
41:	learn: 1.8630707	total: 56.8ms	remaining: 1.29s
42:	learn: 1.8419339	total: 58.2ms	remaining: 1.3s
43:	learn: 1.8195208	total: 59.5ms	remaining: 1.29s
44:	learn: 1.7981270	total: 61ms	remaining: 1.29s
45:	learn: 1.7775558	total: 62.3ms	remaining: 1.29s
46:	learn: 1.7571971	total: 63.7ms	remaining: 1.29s
47:	learn: 1.7412099	total: 65.1ms	remaining: 1.29s
48:	learn: 1.7193964	total: 66.4ms	remaining: 1.29s
49:	learn: 1.6994505	total: 67.7ms	remaining: 1.29s
50:	learn: 1.6850942	total: 71.7ms	remaining: 1.33s
51:	learn: 1.6670380	total: 73.4ms	remaining: 1.34s
52:	learn: 1.6505210	total: 74.7ms	remaining: 1.33s
53:	learn: 1.6290926	total: 76.4ms	remaining: 1.34s
54:	learn: 1.6060399	total: 77.7ms	remaining: 1.33s
55:	learn: 1.5894802	total: 79ms	remaining: 1.33s
56:	learn: 1.5662195	total: 80.2ms	remaining: 1.33s
57:	learn: 1.5504547	total: 81.5ms	remaining: 1.32s
58:	learn: 1.5309207	total: 83.2ms	remaining: 1.33s
59:	learn: 1.5156256	total: 84.7ms	remaining: 1.33s
60:	learn: 1.5006155	total: 86.1ms	remaining: 1.32s
61:	learn: 1.4831747	total: 87.8ms	remaining: 1.33s
62:	learn: 1.4709086	total: 89.1ms	remaining: 1.32s
63:	learn: 1.4560730	total: 90.6ms	remaining: 1.32s
64:	learn: 1.4422610	total: 92ms	remaining: 1.32s
65:	learn: 1.4249958	total: 93.4ms	remaining: 1.32s
66:	learn: 1.4100641	total: 94.9ms	remaining: 1.32s
67:	learn: 1.3935006	total: 96.3ms	remaining: 1.32s
68:	learn: 1.3766098	total: 97.9ms	remaining: 1.32s
69:	learn: 1.3627273	total: 99.2ms	remaining: 1.32s
70:	learn: 1.3510177	total: 101ms	remaining: 1.32s
71:	learn: 1.3340555	total: 103ms	remaining: 1.32s
72:	learn: 1.3226871	total: 104ms	remaining: 1.32s
73:	learn: 1.3126568	total: 105ms	remaining: 1.32s
74:	learn: 1.3034747	total: 107ms	remaining: 1.31s
75:	learn: 1.2907424	total: 108ms	remaining: 1.31s
76:	learn: 1.2820222	total: 109ms	remaining: 1.31s
77:	learn: 1.2700942	total: 111ms	remaining: 1.31s
78:	learn: 1.2591210	total: 112ms	remaining: 1.3s
79:	learn: 1.2484581	total: 113ms	remaining: 1.3s
80:	learn: 1.2386738	total: 115ms	remaining: 1.3s
81:	learn: 1.2310571	total: 116ms	remaining: 1.29s
82:	learn: 1.2240956	total: 117ms	remaining: 1.29s
83:	learn: 1.2099975	total: 118ms	remaining: 1.29s
84:	learn: 1.1970970	total: 120ms	remaining: 1.29s
85:	learn: 1.1920448	total: 121ms	remaining: 1.28s
86:	learn: 1.1831040	total: 122ms	remaining: 1.28s
87:	learn: 1.1731998	total: 123ms	remaining: 1.28s
88:	learn: 1.1601563	total: 125ms	remaining: 1.27s
89:	learn: 1.1529319	total: 126ms	remaining: 1.27s
90:	learn: 1.1422546	total: 127ms	remaining: 1.27s
91:	learn: 1.1393852	total: 128ms	remaining: 1.27s
92:	learn: 1.1347133	total: 130ms	remaining: 1.26s
93:	learn: 1.1254021	total: 131ms	remaining: 1.26s
94:	learn: 1.1202513	total: 132ms	remaining: 1.26s
95:	learn: 1.1133413	total: 133ms	remaining: 1.26s
96:	learn: 1.1062699	total: 135ms	remaining: 1.25s
97:	learn: 1.1023035	total: 136ms	remaining: 1.25s
98:	learn: 1.0951451	total: 137ms	remaining: 1.25s
99:	learn: 1.0872494	total: 138ms	remaining: 1.25s
100:	learn: 1.0818241	total: 140ms	remaining: 1.24s
101:	learn: 1.0759925	total: 141ms	remaining: 1.24s
102:	learn: 1.0701633	total: 142ms	remaining: 1.24s
103:	learn: 1.0646454	total: 143ms	remaining: 1.23s
104:	learn: 1.0557017	total: 145ms	remaining: 1.23s
105:	learn: 1.0525222	total: 146ms	remaining: 1.23s
106:	learn: 1.0469271	total: 147ms	remaining: 1.23s
107:	learn: 1.0437950	total: 148ms	remaining: 1.23s
108:	learn: 1.0397554	total: 150ms	remaining: 1.22s
109:	learn: 1.0347022	total: 151ms	remaining: 1.22s
110:	learn: 1.0314338	total: 152ms	remaining: 1.21s
111:	learn: 1.0265520	total: 153ms	remaining: 1.21s
112:	learn: 1.0228938	total: 155ms	remaining: 1.21s
113:	learn: 1.0172729	total: 156ms	remaining: 1.21s
114:	learn: 1.0131403	total: 157ms	remaining: 1.21s
115:	learn: 1.0079514	total: 158ms	remaining: 1.21s
116:	learn: 1.0023903	total: 160ms	remaining: 1.21s
117:	learn: 0.9997856	total: 161ms	remaining: 1.2s
118:	learn: 0.9950473	total: 162ms	remaining: 1.2s
119:	learn: 0.9910786	total: 164ms	remaining: 1.2s
120:	learn: 0.9848244	total: 165ms	remaining: 1.2s
121:	learn: 0.9812007	total: 166ms	remaining: 1.2s
122:	learn: 0.9745185	total: 169ms	remaining: 1.2s
123:	learn: 0.9715180	total: 170ms	remaining: 1.2s
124:	learn: 0.9649952	total: 172ms	remaining: 1.2s
125:	learn: 0.9618707	total: 173ms	remaining: 1.2s
126:	learn: 0.9580606	total: 175ms	remaining: 1.2s
127:	learn: 0.9514183	total: 176ms	remaining: 1.2s
128:	learn: 0.9445622	total: 177ms	remaining: 1.2s
129:	learn: 0.9423428	total: 179ms	remaining: 1.2s
130:	learn: 0.9397055	total: 180ms	remaining: 1.19s
131:	learn: 0.9353554	total: 181ms	remaining: 1.19s
132:	learn: 0.9321954	total: 183ms	remaining: 1.19s
133:	learn: 0.9260836	total: 185ms	remaining: 1.2s
134:	learn: 0.9218924	total: 187ms	remaining: 1.2s
135:	learn: 0.9199538	total: 188ms	remaining: 1.2s
136:	learn: 0.9155564	total: 192ms	remaining: 1.21s
137:	learn: 0.9127096	total: 194ms	remaining: 1.21s
138:	learn: 0.9092442	total: 197ms	remaining: 1.22s
139:	learn: 0.9049816	total: 199ms	remaining: 1.22s
140:	learn: 0.9028003	total: 202ms	remaining: 1.23s
141:	learn: 0.8978743	total: 205ms	remaining: 1.24s
142:	learn: 0.8929549	total: 208ms	remaining: 1.24s
143:	learn: 0.8876563	total: 209ms	remaining: 1.24s
144:	learn: 0.8819891	total: 210ms	remaining: 1.24s
145:	learn: 0.8779453	total: 211ms	remaining: 1.24s
146:	learn: 0.8734855	total: 213ms	remaining: 1.24s
147:	learn: 0.8704743	total: 217ms	remaining: 1.25s
148:	learn: 0.8674294	total: 221ms	remaining: 1.26s
149:	learn: 0.8655765	total: 223ms	remaining: 1.26s
150:	learn: 0.8618013	total: 227ms	remaining: 1.27s
151:	learn: 0.8567990	total: 228ms	remaining: 1.27s
152:	learn: 0.8523111	total: 230ms	remaining: 1.27s
153:	learn: 0.8508676	total: 233ms	remaining: 1.28s
154:	learn: 0.8488846	total: 237ms	remaining: 1.29s
155:	learn: 0.8452896	total: 240ms	remaining: 1.3s
156:	learn: 0.8419437	total: 242ms	remaining: 1.3s
157:	learn: 0.8400121	total: 244ms	remaining: 1.3s
158:	learn: 0.8389037	total: 245ms	remaining: 1.3s
159:	learn: 0.8384999	total: 246ms	remaining: 1.29s
160:	learn: 0.8344044	total: 248ms	remaining: 1.29s
161:	learn: 0.8311950	total: 250ms	remaining: 1.29s
162:	learn: 0.8302535	total: 251ms	remaining: 1.29s
163:	learn: 0.8272582	total: 252ms	remaining: 1.29s
164:	learn: 0.8244056	total: 254ms	remaining: 1.28s
165:	learn: 0.8201221	total: 255ms	remaining: 1.28s
166:	learn: 0.8161107	total: 256ms	remaining: 1.28s
167:	learn: 0.8136529	total: 258ms	remaining: 1.27s
168:	learn: 0.8096223	total: 259ms	remaining: 1.27s
169:	learn: 0.8064646	total: 261ms	remaining: 1.27s
170:	learn: 0.8037258	total: 262ms	remaining: 1.27s
171:	learn: 0.7998787	total: 264ms	remaining: 1.27s
172:	learn: 0.7958941	total: 265ms	remaining: 1.27s
173:	learn: 0.7919668	total: 266ms	remaining: 1.26s
174:	learn: 0.7894858	total: 268ms	remaining: 1.26s
175:	learn: 0.7878245	total: 269ms	remaining: 1.26s
176:	learn: 0.7861152	total: 270ms	remaining: 1.25s
177:	learn: 0.7834194	total: 272ms	remaining: 1.25s
178:	learn: 0.7801045	total: 273ms	remaining: 1.25s
179:	learn: 0.7774946	total: 274ms	remaining: 1.25s
180:	learn: 0.7737805	total: 276ms	remaining: 1.25s
181:	learn: 0.7716849	total: 277ms	remaining: 1.25s
182:	learn: 0.7700756	total: 278ms	remaining: 1.24s
183:	learn: 0.7664386	total: 280ms	remaining: 1.24s
184:	learn: 0.7631159	total: 281ms	remaining: 1.24s
185:	learn: 0.7620687	total: 282ms	remaining: 1.24s
186:	learn: 0.7586740	total: 284ms	remaining: 1.23s
187:	learn: 0.7562609	total: 285ms	remaining: 1.23s
188:	learn: 0.7520698	total: 286ms	remaining: 1.23s
189:	learn: 0.7484766	total: 288ms	remaining: 1.23s
190:	learn: 0.7464019	total: 289ms	remaining: 1.22s
191:	learn: 0.7440411	total: 293ms	remaining: 1.23s
192:	learn: 0.7421659	total: 296ms	remaining: 1.24s
193:	learn: 0.7391332	total: 299ms	remaining: 1.24s
194:	learn: 0.7380267	total: 301ms	remaining: 1.24s
195:	learn: 0.7359955	total: 303ms	remaining: 1.24s
196:	learn: 0.7343130	total: 306ms	remaining: 1.25s
197:	learn: 0.7320443	total: 308ms	remaining: 1.25s
198:	learn: 0.7293453	total: 311ms	remaining: 1.25s
199:	learn: 0.7267173	total: 313ms	remaining: 1.25s
200:	learn: 0.7236935	total: 316ms	remaining: 1.25s
201:	learn: 0.7227336	total: 318ms	remaining: 1.26s
202:	learn: 0.7221670	total: 321ms	remaining: 1.26s
203:	learn: 0.7195966	total: 323ms	remaining: 1.26s
204:	learn: 0.7189170	total: 326ms	remaining: 1.26s
205:	learn: 0.7159466	total: 329ms	remaining: 1.27s
206:	learn: 0.7133404	total: 331ms	remaining: 1.27s
207:	learn: 0.7100999	total: 332ms	remaining: 1.26s
208:	learn: 0.7091655	total: 333ms	remaining: 1.26s
209:	learn: 0.7071782	total: 334ms	remaining: 1.26s
210:	learn: 0.7057792	total: 336ms	remaining: 1.25s
211:	learn: 0.7018906	total: 337ms	remaining: 1.25s
212:	learn: 0.6997223	total: 339ms	remaining: 1.25s
213:	learn: 0.6973366	total: 341ms	remaining: 1.25s
214:	learn: 0.6956829	total: 343ms	remaining: 1.25s
215:	learn: 0.6940198	total: 345ms	remaining: 1.25s
216:	learn: 0.6906306	total: 346ms	remaining: 1.25s
217:	learn: 0.6879721	total: 347ms	remaining: 1.25s
218:	learn: 0.6855816	total: 349ms	remaining: 1.24s
219:	learn: 0.6833018	total: 350ms	remaining: 1.24s
220:	learn: 0.6808030	total: 351ms	remaining: 1.24s
221:	learn: 0.6793954	total: 352ms	remaining: 1.24s
222:	learn: 0.6767708	total: 355ms	remaining: 1.24s
223:	learn: 0.6742530	total: 357ms	remaining: 1.24s
224:	learn: 0.6712836	total: 358ms	remaining: 1.23s
225:	learn: 0.6694026	total: 359ms	remaining: 1.23s
226:	learn: 0.6670393	total: 360ms	remaining: 1.23s
227:	learn: 0.6650446	total: 362ms	remaining: 1.23s
228:	learn: 0.6616848	total: 365ms	remaining: 1.23s
229:	learn: 0.6608113	total: 366ms	remaining: 1.23s
230:	learn: 0.6585345	total: 368ms	remaining: 1.22s
231:	learn: 0.6552465	total: 370ms	remaining: 1.22s
232:	learn: 0.6515460	total: 371ms	remaining: 1.22s
233:	learn: 0.6487350	total: 373ms	remaining: 1.22s
234:	learn: 0.6458542	total: 375ms	remaining: 1.22s
235:	learn: 0.6435465	total: 378ms	remaining: 1.22s
236:	learn: 0.6406300	total: 381ms	remaining: 1.23s
237:	learn: 0.6369892	total: 384ms	remaining: 1.23s
238:	learn: 0.6338949	total: 387ms	remaining: 1.23s
239:	learn: 0.6308562	total: 390ms	remaining: 1.24s
240:	learn: 0.6283989	total: 393ms	remaining: 1.24s
241:	learn: 0.6260278	total: 396ms	remaining: 1.24s
242:	learn: 0.6250823	total: 399ms	remaining: 1.24s
243:	learn: 0.6220065	total: 402ms	remaining: 1.24s
244:	learn: 0.6202666	total: 405ms	remaining: 1.25s
245:	learn: 0.6196196	total: 408ms	remaining: 1.25s
246:	learn: 0.6172945	total: 411ms	remaining: 1.25s
247:	learn: 0.6150436	total: 413ms	remaining: 1.25s
248:	learn: 0.6127847	total: 415ms	remaining: 1.25s
249:	learn: 0.6117832	total: 419ms	remaining: 1.25s
250:	learn: 0.6100855	total: 421ms	remaining: 1.26s
251:	learn: 0.6075687	total: 424ms	remaining: 1.26s
252:	learn: 0.6056913	total: 426ms	remaining: 1.26s
253:	learn: 0.6044240	total: 429ms	remaining: 1.26s
254:	learn: 0.6014434	total: 431ms	remaining: 1.26s
255:	learn: 0.6005318	total: 434ms	remaining: 1.26s
256:	learn: 0.5985683	total: 436ms	remaining: 1.26s
257:	learn: 0.5960553	total: 437ms	remaining: 1.26s
258:	learn: 0.5945199	total: 438ms	remaining: 1.25s
259:	learn: 0.5910539	total: 440ms	remaining: 1.25s
260:	learn: 0.5887123	total: 441ms	remaining: 1.25s
261:	learn: 0.5862222	total: 443ms	remaining: 1.25s
262:	learn: 0.5846798	total: 444ms	remaining: 1.24s
263:	learn: 0.5830740	total: 445ms	remaining: 1.24s
264:	learn: 0.5801248	total: 446ms	remaining: 1.24s
265:	learn: 0.5776171	total: 448ms	remaining: 1.24s
266:	learn: 0.5762341	total: 449ms	remaining: 1.23s
267:	learn: 0.5745873	total: 451ms	remaining: 1.23s
268:	learn: 0.5732210	total: 452ms	remaining: 1.23s
269:	learn: 0.5703763	total: 454ms	remaining: 1.23s
270:	learn: 0.5693512	total: 455ms	remaining: 1.22s
271:	learn: 0.5667326	total: 457ms	remaining: 1.22s
272:	learn: 0.5655036	total: 458ms	remaining: 1.22s
273:	learn: 0.5633348	total: 459ms	remaining: 1.22s
274:	learn: 0.5617684	total: 461ms	remaining: 1.22s
275:	learn: 0.5587435	total: 462ms	remaining: 1.21s
276:	learn: 0.5583273	total: 464ms	remaining: 1.21s
277:	learn: 0.5578353	total: 465ms	remaining: 1.21s
278:	learn: 0.5548925	total: 467ms	remaining: 1.21s
279:	learn: 0.5536318	total: 468ms	remaining: 1.2s
280:	learn: 0.5523629	total: 470ms	remaining: 1.2s
281:	learn: 0.5490335	total: 471ms	remaining: 1.2s
282:	learn: 0.5471248	total: 473ms	remaining: 1.2s
283:	learn: 0.5457541	total: 474ms	remaining: 1.2s
284:	learn: 0.5436134	total: 476ms	remaining: 1.19s
285:	learn: 0.5432208	total: 477ms	remaining: 1.19s
286:	learn: 0.5409942	total: 479ms	remaining: 1.19s
287:	learn: 0.5391529	total: 480ms	remaining: 1.19s
288:	learn: 0.5363351	total: 482ms	remaining: 1.19s
289:	learn: 0.5340022	total: 483ms	remaining: 1.18s
290:	learn: 0.5325774	total: 485ms	remaining: 1.18s
291:	learn: 0.5308673	total: 486ms	remaining: 1.18s
292:	learn: 0.5269607	total: 487ms	remaining: 1.18s
293:	learn: 0.5257423	total: 489ms	remaining: 1.17s
294:	learn: 0.5241498	total: 490ms	remaining: 1.17s
295:	learn: 0.5232504	total: 492ms	remaining: 1.17s
296:	learn: 0.5198902	total: 493ms	remaining: 1.17s
297:	learn: 0.5182788	total: 494ms	remaining: 1.16s
298:	learn: 0.5174666	total: 496ms	remaining: 1.16s
299:	learn: 0.5157555	total: 497ms	remaining: 1.16s
300:	learn: 0.5150745	total: 499ms	remaining: 1.16s
301:	learn: 0.5134748	total: 500ms	remaining: 1.16s
302:	learn: 0.5104572	total: 502ms	remaining: 1.15s
303:	learn: 0.5078163	total: 503ms	remaining: 1.15s
304:	learn: 0.5061509	total: 504ms	remaining: 1.15s
305:	learn: 0.5043448	total: 506ms	remaining: 1.15s
306:	learn: 0.5009793	total: 507ms	remaining: 1.14s
307:	learn: 0.5002871	total: 508ms	remaining: 1.14s
308:	learn: 0.4980143	total: 510ms	remaining: 1.14s
309:	learn: 0.4962403	total: 511ms	remaining: 1.14s
310:	learn: 0.4954888	total: 513ms	remaining: 1.14s
311:	learn: 0.4929283	total: 514ms	remaining: 1.13s
312:	learn: 0.4916595	total: 516ms	remaining: 1.13s
313:	learn: 0.4893490	total: 517ms	remaining: 1.13s
314:	learn: 0.4875438	total: 518ms	remaining: 1.13s
315:	learn: 0.4868713	total: 520ms	remaining: 1.13s
316:	learn: 0.4855035	total: 521ms	remaining: 1.12s
317:	learn: 0.4851127	total: 523ms	remaining: 1.12s
318:	learn: 0.4836239	total: 524ms	remaining: 1.12s
319:	learn: 0.4830510	total: 525ms	remaining: 1.12s
320:	learn: 0.4821007	total: 527ms	remaining: 1.11s
321:	learn: 0.4818301	total: 528ms	remaining: 1.11s
322:	learn: 0.4808618	total: 530ms	remaining: 1.11s
323:	learn: 0.4784284	total: 531ms	remaining: 1.11s
324:	learn: 0.4751231	total: 533ms	remaining: 1.11s
325:	learn: 0.4725690	total: 535ms	remaining: 1.1s
326:	learn: 0.4720841	total: 536ms	remaining: 1.1s
327:	learn: 0.4716912	total: 538ms	remaining: 1.1s
328:	learn: 0.4704405	total: 539ms	remaining: 1.1s
329:	learn: 0.4694872	total: 541ms	remaining: 1.1s
330:	learn: 0.4681167	total: 542ms	remaining: 1.09s
331:	learn: 0.4658640	total: 544ms	remaining: 1.09s
332:	learn: 0.4647500	total: 547ms	remaining: 1.09s
333:	learn: 0.4644411	total: 551ms	remaining: 1.1s
334:	learn: 0.4626663	total: 553ms	remaining: 1.1s
335:	learn: 0.4617122	total: 556ms	remaining: 1.1s
336:	learn: 0.4606492	total: 559ms	remaining: 1.1s
337:	learn: 0.4601419	total: 562ms	remaining: 1.1s
338:	learn: 0.4578959	total: 565ms	remaining: 1.1s
339:	learn: 0.4553379	total: 567ms	remaining: 1.1s
340:	learn: 0.4530627	total: 570ms	remaining: 1.1s
341:	learn: 0.4518873	total: 573ms	remaining: 1.1s
342:	learn: 0.4497080	total: 576ms	remaining: 1.1s
343:	learn: 0.4481467	total: 578ms	remaining: 1.1s
344:	learn: 0.4478502	total: 582ms	remaining: 1.1s
345:	learn: 0.4466276	total: 585ms	remaining: 1.1s
346:	learn: 0.4448110	total: 587ms	remaining: 1.1s
347:	learn: 0.4440464	total: 590ms	remaining: 1.1s
348:	learn: 0.4428691	total: 594ms	remaining: 1.11s
349:	learn: 0.4404858	total: 596ms	remaining: 1.11s
350:	learn: 0.4397293	total: 599ms	remaining: 1.11s
351:	learn: 0.4385271	total: 600ms	remaining: 1.1s
352:	learn: 0.4360911	total: 602ms	remaining: 1.1s
353:	learn: 0.4329782	total: 603ms	remaining: 1.1s
354:	learn: 0.4324581	total: 605ms	remaining: 1.1s
355:	learn: 0.4308819	total: 606ms	remaining: 1.1s
356:	learn: 0.4279593	total: 608ms	remaining: 1.09s
357:	learn: 0.4263571	total: 609ms	remaining: 1.09s
358:	learn: 0.4247755	total: 611ms	remaining: 1.09s
359:	learn: 0.4228619	total: 612ms	remaining: 1.09s
360:	learn: 0.4209680	total: 614ms	remaining: 1.09s
361:	learn: 0.4196774	total: 615ms	remaining: 1.08s
362:	learn: 0.4180858	total: 617ms	remaining: 1.08s
363:	learn: 0.4175702	total: 618ms	remaining: 1.08s
364:	learn: 0.4164619	total: 620ms	remaining: 1.08s
365:	learn: 0.4152296	total: 621ms	remaining: 1.08s
366:	learn: 0.4130547	total: 623ms	remaining: 1.07s
367:	learn: 0.4124895	total: 624ms	remaining: 1.07s
368:	learn: 0.4109357	total: 626ms	remaining: 1.07s
369:	learn: 0.4086487	total: 627ms	remaining: 1.07s
370:	learn: 0.4076131	total: 628ms	remaining: 1.06s
371:	learn: 0.4065524	total: 630ms	remaining: 1.06s
372:	learn: 0.4050545	total: 633ms	remaining: 1.06s
373:	learn: 0.4046285	total: 636ms	remaining: 1.06s
374:	learn: 0.4038539	total: 638ms	remaining: 1.06s
375:	learn: 0.4023747	total: 640ms	remaining: 1.06s
376:	learn: 0.4018815	total: 642ms	remaining: 1.06s
377:	learn: 0.4006780	total: 643ms	remaining: 1.06s
378:	learn: 0.3992435	total: 644ms	remaining: 1.05s
379:	learn: 0.3970469	total: 646ms	remaining: 1.05s
380:	learn: 0.3947946	total: 647ms	remaining: 1.05s
381:	learn: 0.3943704	total: 649ms	remaining: 1.05s

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fitting SVR for C2X-Complex_rhown_3x3_depth_lt_1
Fitting KNN for C2X-Complex_rhown_3x3_depth_lt_1
Fitting LR for C2X-Complex_rhown_3x3_depth_lt_1
Fitting RF for C2X-Complex_rhown_3x3_depth_lt_1
Fitting CAT for C2X-Complex_rhown_3x3_depth_lt_1
Learning rate set to 0.033272
0:	learn: 3.4122952	total: 3.92ms	remaining: 3.92s
1:	learn: 3.3474127	total: 5.18ms	remaining: 2.59s
2:	learn: 3.2991138	total: 6.54ms	remaining: 2.17s
3:	learn: 3.2462580	total: 7.67ms	remaining: 1.91s
4:	learn: 3.1987774	total: 8.84ms	remaining: 1.76s
5:	learn: 3.1550942	total: 10ms	remaining: 1.66s
6:	learn: 3.1008370	total: 11.2ms	remaining: 1.58s
7:	learn: 3.0559803	total: 12.3ms	remaining: 1.52s
8:	learn: 3.0003857	total: 13.4ms	remaining: 1.48s
9:	learn: 2.9573906	total: 14.6ms	remaining: 1.44s
10:	learn: 2.9121269	total: 15.8ms	remaining: 1.42s
11:	learn: 2.8741344	total: 17ms	remaining: 1.4s
12:	learn: 2.8167912	total: 18.2ms	remaining: 1.38s
13:	learn: 2.7756944	total: 19.4ms	remaining: 1.37s
14:	learn: 2.7369197	total: 20.6ms	remaining: 1.35s
15:	learn: 2.6983670	total: 21.8ms	remaining: 1.34s
16:	learn: 2.6632162	total: 23.1ms	remaining: 1.34s
17:	learn: 2.6224717	total: 24.3ms	remaining: 1.32s
18:	learn: 2.5861249	total: 25.6ms	remaining: 1.32s
19:	learn: 2.5527934	total: 27ms	remaining: 1.32s
20:	learn: 2.5246702	total: 28.1ms	remaining: 1.31s
21:	learn: 2.4789618	total: 29.2ms	remaining: 1.3s
22:	learn: 2.4456195	total: 30.7ms	remaining: 1.3s
23:	learn: 2.4155696	total: 32.1ms	remaining: 1.3s
24:	learn: 2.3854267	total: 33.3ms	remaining: 1.3s
25:	learn: 2.3549271	total: 34.6ms	remaining: 1.3s
26:	learn: 2.3229688	total: 35.7ms	remaining: 1.28s
27:	learn: 2.2942065	total: 36.8ms	remaining: 1.28s
28:	learn: 2.2547556	total: 38ms	remaining: 1.27s
29:	learn: 2.2209657	total: 39.2ms	remaining: 1.27s
30:	learn: 2.1942426	total: 40.3ms	remaining: 1.26s
31:	learn: 2.1632090	total: 41.4ms	remaining: 1.25s
32:	learn: 2.1308964	total: 42.5ms	remaining: 1.25s
33:	learn: 2.1018368	total: 43.6ms	remaining: 1.24s
34:	learn: 2.0752360	total: 44.6ms	remaining: 1.23s
35:	learn: 2.0498084	total: 45.8ms	remaining: 1.23s
36:	learn: 2.0199956	total: 47.2ms	remaining: 1.23s
37:	learn: 1.9959869	total: 48.6ms	remaining: 1.23s
38:	learn: 1.9686561	total: 49.9ms	remaining: 1.23s
39:	learn: 1.9454934	total: 51.4ms	remaining: 1.23s
40:	learn: 1.9263304	total: 52.6ms	remaining: 1.23s
41:	learn: 1.9025041	total: 54ms	remaining: 1.23s
42:	learn: 1.8839819	total: 55.3ms	remaining: 1.23s
43:	learn: 1.8570459	total: 56.4ms	remaining: 1.23s
44:	learn: 1.8385115	total: 57.5ms	remaining: 1.22s
45:	learn: 1.8186255	total: 58.5ms	remaining: 1.21s
46:	learn: 1.7944491	total: 59.6ms	remaining: 1.21s
47:	learn: 1.7765591	total: 60.8ms	remaining: 1.21s
48:	learn: 1.7508331	total: 61.9ms	remaining: 1.2s
49:	learn: 1.7307157	total: 63.3ms	remaining: 1.2s
50:	learn: 1.7119860	total: 64.7ms	remaining: 1.2s
51:	learn: 1.6936916	total: 65.8ms	remaining: 1.2s
52:	learn: 1.6775222	total: 66.9ms	remaining: 1.2s
53:	learn: 1.6567859	total: 68.1ms	remaining: 1.19s
54:	learn: 1.6387348	total: 69.4ms	remaining: 1.19s
55:	learn: 1.6278971	total: 70.6ms	remaining: 1.19s
56:	learn: 1.6085217	total: 71.8ms	remaining: 1.19s
57:	learn: 1.5847783	total: 73.1ms	remaining: 1.19s
58:	learn: 1.5678105	total: 74.4ms	remaining: 1.19s
59:	learn: 1.5528968	total: 75.5ms	remaining: 1.18s
60:	learn: 1.5372224	total: 76.9ms	remaining: 1.18s
61:	learn: 1.5206797	total: 78.4ms	remaining: 1.19s
62:	learn: 1.5024355	total: 79.8ms	remaining: 1.19s
63:	learn: 1.4870541	total: 81ms	remaining: 1.18s
64:	learn: 1.4757375	total: 82.3ms	remaining: 1.18s
65:	learn: 1.4663567	total: 83.7ms	remaining: 1.18s
66:	learn: 1.4509259	total: 85ms	remaining: 1.18s
67:	learn: 1.4432441	total: 86.4ms	remaining: 1.18s
68:	learn: 1.4290621	total: 87.7ms	remaining: 1.18s
69:	learn: 1.4212186	total: 89ms	remaining: 1.18s
70:	learn: 1.4071068	total: 90.3ms	remaining: 1.18s
71:	learn: 1.3931328	total: 91.6ms	remaining: 1.18s
72:	learn: 1.3789301	total: 92.8ms	remaining: 1.18s
73:	learn: 1.3657122	total: 94.2ms	remaining: 1.18s
74:	learn: 1.3550537	total: 95.6ms	remaining: 1.18s
75:	learn: 1.3407241	total: 96.9ms	remaining: 1.18s
76:	learn: 1.3263234	total: 98.5ms	remaining: 1.18s
77:	learn: 1.3079392	total: 99.8ms	remaining: 1.18s
78:	learn: 1.3001507	total: 101ms	remaining: 1.18s
79:	learn: 1.2889780	total: 102ms	remaining: 1.18s
80:	learn: 1.2811764	total: 104ms	remaining: 1.18s
81:	learn: 1.2707549	total: 105ms	remaining: 1.18s
82:	learn: 1.2641990	total: 107ms	remaining: 1.18s
83:	learn: 1.2543775	total: 108ms	remaining: 1.18s
84:	learn: 1.2440703	total: 109ms	remaining: 1.18s
85:	learn: 1.2265079	total: 111ms	remaining: 1.18s
86:	learn: 1.2194086	total: 112ms	remaining: 1.18s
87:	learn: 1.2118404	total: 114ms	remaining: 1.18s
88:	learn: 1.2013208	total: 115ms	remaining: 1.18s
89:	learn: 1.1931270	total: 116ms	remaining: 1.18s
90:	learn: 1.1897699	total: 118ms	remaining: 1.18s
91:	learn: 1.1842005	total: 119ms	remaining: 1.17s
92:	learn: 1.1689922	total: 120ms	remaining: 1.17s
93:	learn: 1.1625082	total: 121ms	remaining: 1.17s
94:	learn: 1.1523280	total: 123ms	remaining: 1.17s
95:	learn: 1.1426788	total: 124ms	remaining: 1.17s
96:	learn: 1.1322314	total: 126ms	remaining: 1.17s
97:	learn: 1.1195115	total: 127ms	remaining: 1.17s
98:	learn: 1.1068867	total: 129ms	remaining: 1.17s
99:	learn: 1.0964695	total: 130ms	remaining: 1.17s
100:	learn: 1.0879848	total: 131ms	remaining: 1.17s
101:	learn: 1.0821557	total: 133ms	remaining: 1.17s
102:	learn: 1.0735846	total: 134ms	remaining: 1.17s
103:	learn: 1.0631590	total: 135ms	remaining: 1.17s
104:	learn: 1.0534736	total: 137ms	remaining: 1.17s
105:	learn: 1.0464819	total: 138ms	remaining: 1.17s
106:	learn: 1.0401163	total: 140ms	remaining: 1.17s
107:	learn: 1.0297973	total: 141ms	remaining: 1.16s
108:	learn: 1.0209631	total: 142ms	remaining: 1.16s
109:	learn: 1.0153815	total: 144ms	remaining: 1.16s
110:	learn: 1.0087861	total: 145ms	remaining: 1.16s
111:	learn: 1.0008542	total: 146ms	remaining: 1.16s
112:	learn: 0.9929485	total: 147ms	remaining: 1.16s
113:	learn: 0.9882880	total: 149ms	remaining: 1.16s
114:	learn: 0.9842695	total: 150ms	remaining: 1.15s
115:	learn: 0.9748940	total: 152ms	remaining: 1.15s
116:	learn: 0.9705710	total: 153ms	remaining: 1.15s
117:	learn: 0.9631627	total: 154ms	remaining: 1.15s
118:	learn: 0.9560033	total: 156ms	remaining: 1.15s
119:	learn: 0.9534367	total: 157ms	remaining: 1.15s
120:	learn: 0.9475804	total: 158ms	remaining: 1.15s
121:	learn: 0.9398108	total: 160ms	remaining: 1.15s
122:	learn: 0.9379028	total: 161ms	remaining: 1.15s
123:	learn: 0.9319724	total: 162ms	remaining: 1.15s
124:	learn: 0.9216772	total: 163ms	remaining: 1.14s
125:	learn: 0.9176442	total: 165ms	remaining: 1.14s
126:	learn: 0.9122627	total: 166ms	remaining: 1.14s
127:	learn: 0.9056834	total: 168ms	remaining: 1.14s
128:	learn: 0.8990453	total: 169ms	remaining: 1.14s
129:	learn: 0.8945561	total: 170ms	remaining: 1.14s
130:	learn: 0.8899731	total: 171ms	remaining: 1.14s
131:	learn: 0.8835086	total: 172ms	remaining: 1.13s
132:	learn: 0.8796253	total: 174ms	remaining: 1.13s
133:	learn: 0.8759688	total: 175ms	remaining: 1.13s
134:	learn: 0.8719225	total: 176ms	remaining: 1.13s
135:	learn: 0.8681499	total: 177ms	remaining: 1.12s
136:	learn: 0.8599945	total: 178ms	remaining: 1.12s
137:	learn: 0.8549692	total: 179ms	remaining: 1.12s
138:	learn: 0.8494832	total: 180ms	remaining: 1.12s
139:	learn: 0.8456423	total: 182ms	remaining: 1.12s
140:	learn: 0.8415902	total: 185ms	remaining: 1.13s
141:	learn: 0.8405113	total: 187ms	remaining: 1.13s
142:	learn: 0.8349451	total: 188ms	remaining: 1.13s
143:	learn: 0.8295160	total: 189ms	remaining: 1.12s
144:	learn: 0.8252064	total: 190ms	remaining: 1.12s
145:	learn: 0.8201400	total: 192ms	remaining: 1.12s
146:	learn: 0.8144657	total: 193ms	remaining: 1.12s
147:	learn: 0.8089798	total: 194ms	remaining: 1.12s
148:	learn: 0.8040702	total: 195ms	remaining: 1.12s
149:	learn: 0.7994783	total: 197ms	remaining: 1.11s
150:	learn: 0.7951878	total: 198ms	remaining: 1.11s
151:	learn: 0.7911638	total: 200ms	remaining: 1.11s
152:	learn: 0.7858165	total: 201ms	remaining: 1.11s
153:	learn: 0.7831679	total: 202ms	remaining: 1.11s
154:	learn: 0.7781086	total: 203ms	remaining: 1.11s
155:	learn: 0.7721614	total: 207ms	remaining: 1.12s
156:	learn: 0.7681205	total: 209ms	remaining: 1.12s
157:	learn: 0.7645979	total: 212ms	remaining: 1.13s
158:	learn: 0.7612642	total: 215ms	remaining: 1.14s
159:	learn: 0.7572815	total: 218ms	remaining: 1.15s
160:	learn: 0.7514698	total: 221ms	remaining: 1.15s
161:	learn: 0.7475138	total: 223ms	remaining: 1.15s
162:	learn: 0.7438598	total: 225ms	remaining: 1.16s
163:	learn: 0.7390147	total: 228ms	remaining: 1.16s
164:	learn: 0.7330570	total: 231ms	remaining: 1.17s
165:	learn: 0.7305155	total: 233ms	remaining: 1.17s
166:	learn: 0.7271467	total: 235ms	remaining: 1.17s
167:	learn: 0.7215079	total: 236ms	remaining: 1.17s
168:	learn: 0.7169126	total: 238ms	remaining: 1.17s
169:	learn: 0.7115211	total: 239ms	remaining: 1.17s
170:	learn: 0.7083381	total: 240ms	remaining: 1.16s
171:	learn: 0.7050875	total: 241ms	remaining: 1.16s
172:	learn: 0.7020589	total: 242ms	remaining: 1.16s
173:	learn: 0.6969552	total: 243ms	remaining: 1.15s
174:	learn: 0.6943133	total: 244ms	remaining: 1.15s
175:	learn: 0.6888850	total: 245ms	remaining: 1.15s
176:	learn: 0.6840305	total: 247ms	remaining: 1.15s
177:	learn: 0.6822984	total: 248ms	remaining: 1.14s
178:	learn: 0.6786240	total: 249ms	remaining: 1.14s
179:	learn: 0.6761047	total: 250ms	remaining: 1.14s
180:	learn: 0.6740698	total: 251ms	remaining: 1.14s
181:	learn: 0.6732702	total: 252ms	remaining: 1.13s
182:	learn: 0.6707573	total: 253ms	remaining: 1.13s
183:	learn: 0.6676977	total: 254ms	remaining: 1.13s
184:	learn: 0.6651069	total: 255ms	remaining: 1.12s
185:	learn: 0.6618076	total: 256ms	remaining: 1.12s
186:	learn: 0.6576674	total: 257ms	remaining: 1.12s
187:	learn: 0.6531660	total: 258ms	remaining: 1.11s
188:	learn: 0.6503339	total: 259ms	remaining: 1.11s
189:	learn: 0.6464953	total: 260ms	remaining: 1.11s
190:	learn: 0.6416795	total: 262ms	remaining: 1.11s
191:	learn: 0.6384319	total: 263ms	remaining: 1.11s
192:	learn: 0.6353147	total: 264ms	remaining: 1.1s
193:	learn: 0.6322246	total: 265ms	remaining: 1.1s
194:	learn: 0.6286689	total: 266ms	remaining: 1.1s
195:	learn: 0.6260017	total: 267ms	remaining: 1.1s
196:	learn: 0.6229155	total: 268ms	remaining: 1.09s
197:	learn: 0.6200632	total: 270ms	remaining: 1.09s
198:	learn: 0.6175373	total: 271ms	remaining: 1.09s
199:	learn: 0.6145415	total: 272ms	remaining: 1.09s
200:	learn: 0.6114709	total: 273ms	remaining: 1.08s
201:	learn: 0.6104858	total: 274ms	remaining: 1.08s
202:	learn: 0.6084029	total: 275ms	remaining: 1.08s
203:	learn: 0.6052043	total: 277ms	remaining: 1.08s
204:	learn: 0.6011444	total: 278ms	remaining: 1.08s
205:	learn: 0.5984267	total: 279ms	remaining: 1.08s
206:	learn: 0.5948129	total: 280ms	remaining: 1.07s
207:	learn: 0.5919509	total: 281ms	remaining: 1.07s
208:	learn: 0.5904649	total: 283ms	remaining: 1.07s
209:	learn: 0.5883600	total: 284ms	remaining: 1.07s
210:	learn: 0.5841040	total: 285ms	remaining: 1.06s
211:	learn: 0.5818787	total: 286ms	remaining: 1.06s
212:	learn: 0.5792048	total: 287ms	remaining: 1.06s
213:	learn: 0.5768827	total: 288ms	remaining: 1.06s
214:	learn: 0.5737905	total: 289ms	remaining: 1.05s
215:	learn: 0.5702218	total: 290ms	remaining: 1.05s
216:	learn: 0.5689234	total: 291ms	remaining: 1.05s
217:	learn: 0.5662829	total: 293ms	remaining: 1.05s
218:	learn: 0.5627183	total: 294ms	remaining: 1.05s
219:	learn: 0.5585819	total: 295ms	remaining: 1.05s
220:	learn: 0.5560411	total: 296ms	remaining: 1.04s
221:	learn: 0.5532265	total: 298ms	remaining: 1.04s
222:	learn: 0.5507568	total: 299ms	remaining: 1.04s
223:	learn: 0.5480230	total: 300ms	remaining: 1.04s
224:	learn: 0.5447986	total: 301ms	remaining: 1.04s
225:	learn: 0.5422698	total: 302ms	remaining: 1.03s
226:	learn: 0.5393413	total: 304ms	remaining: 1.03s
227:	learn: 0.5364739	total: 305ms	remaining: 1.03s
228:	learn: 0.5331117	total: 306ms	remaining: 1.03s
229:	learn: 0.5310259	total: 308ms	remaining: 1.03s
230:	learn: 0.5273534	total: 309ms	remaining: 1.03s
231:	learn: 0.5252045	total: 311ms	remaining: 1.03s
232:	learn: 0.5240779	total: 312ms	remaining: 1.03s
233:	learn: 0.5227297	total: 314ms	remaining: 1.03s
234:	learn: 0.5210393	total: 315ms	remaining: 1.02s
235:	learn: 0.5190981	total: 316ms	remaining: 1.02s
236:	learn: 0.5178419	total: 317ms	remaining: 1.02s
237:	learn: 0.5145484	total: 318ms	remaining: 1.02s
238:	learn: 0.5111282	total: 320ms	remaining: 1.02s
239:	learn: 0.5079434	total: 321ms	remaining: 1.01s
240:	learn: 0.5070829	total: 322ms	remaining: 1.01s
241:	learn: 0.5061967	total: 323ms	remaining: 1.01s
242:	learn: 0.5033750	total: 325ms	remaining: 1.01s
243:	learn: 0.5008293	total: 326ms	remaining: 1.01s
244:	learn: 0.4981411	total: 327ms	remaining: 1.01s
245:	learn: 0.4966595	total: 329ms	remaining: 1.01s
246:	learn: 0.4958701	total: 330ms	remaining: 1s
247:	learn: 0.4935489	total: 331ms	remaining: 1s
248:	learn: 0.4917238	total: 332ms	remaining: 1s
249:	learn: 0.4889225	total: 334ms	remaining: 1s
250:	learn: 0.4871074	total: 335ms	remaining: 1s
251:	learn: 0.4848435	total: 337ms	remaining: 1s
252:	learn: 0.4821328	total: 338ms	remaining: 999ms
253:	learn: 0.4796566	total: 340ms	remaining: 998ms
254:	learn: 0.4771988	total: 341ms	remaining: 997ms
255:	learn: 0.4769496	total: 343ms	remaining: 996ms
256:	learn: 0.4753798	total: 344ms	remaining: 994ms
257:	learn: 0.4735201	total: 345ms	remaining: 992ms
258:	learn: 0.4721344	total: 346ms	remaining: 991ms
259:	learn: 0.4708372	total: 348ms	remaining: 989ms
260:	learn: 0.4703713	total: 349ms	remaining: 988ms
261:	learn: 0.4688701	total: 350ms	remaining: 986ms
262:	learn: 0.4670552	total: 351ms	remaining: 984ms
263:	learn: 0.4660119	total: 353ms	remaining: 984ms
264:	learn: 0.4640611	total: 354ms	remaining: 983ms
265:	learn: 0.4624720	total: 356ms	remaining: 982ms
266:	learn: 0.4598534	total: 357ms	remaining: 980ms
267:	learn: 0.4578638	total: 358ms	remaining: 979ms
268:	learn: 0.4547594	total: 360ms	remaining: 977ms
269:	learn: 0.4531019	total: 361ms	remaining: 975ms
270:	learn: 0.4500028	total: 362ms	remaining: 973ms
271:	learn: 0.4486255	total: 363ms	remaining: 972ms
272:	learn: 0.4468400	total: 364ms	remaining: 970ms
273:	learn: 0.4443946	total: 366ms	remaining: 969ms
274:	learn: 0.4424136	total: 367ms	remaining: 969ms
275:	learn: 0.4411905	total: 370ms	remaining: 970ms
276:	learn: 0.4383281	total: 371ms	remaining: 968ms
277:	learn: 0.4357369	total: 372ms	remaining: 967ms
278:	learn: 0.4341310	total: 374ms	remaining: 966ms
279:	learn: 0.4327224	total: 375ms	remaining: 964ms
280:	learn: 0.4304747	total: 376ms	remaining: 962ms
281:	learn: 0.4293447	total: 377ms	remaining: 961ms
282:	learn: 0.4266338	total: 379ms	remaining: 960ms
283:	learn: 0.4251804	total: 380ms	remaining: 959ms
284:	learn: 0.4240168	total: 382ms	remaining: 958ms
285:	learn: 0.4224350	total: 383ms	remaining: 957ms
286:	learn: 0.4218381	total: 385ms	remaining: 955ms
287:	learn: 0.4196539	total: 386ms	remaining: 954ms
288:	learn: 0.4181846	total: 387ms	remaining: 953ms
289:	learn: 0.4160915	total: 389ms	remaining: 952ms
290:	learn: 0.4155520	total: 390ms	remaining: 951ms
291:	learn: 0.4143874	total: 391ms	remaining: 949ms
292:	learn: 0.4128989	total: 393ms	remaining: 948ms
293:	learn: 0.4122401	total: 394ms	remaining: 946ms
294:	learn: 0.4118670	total: 395ms	remaining: 945ms
295:	learn: 0.4101644	total: 397ms	remaining: 944ms
296:	learn: 0.4082754	total: 398ms	remaining: 942ms
297:	learn: 0.4054574	total: 400ms	remaining: 942ms
298:	learn: 0.4041878	total: 401ms	remaining: 940ms
299:	learn: 0.4025214	total: 403ms	remaining: 939ms
300:	learn: 0.4011107	total: 404ms	remaining: 938ms
301:	learn: 0.3992331	total: 405ms	remaining: 936ms
302:	learn: 0.3988240	total: 406ms	remaining: 934ms
303:	learn: 0.3975813	total: 407ms	remaining: 933ms
304:	learn: 0.3958284	total: 409ms	remaining: 931ms
305:	learn: 0.3939695	total: 410ms	remaining: 929ms
306:	learn: 0.3927605	total: 411ms	remaining: 928ms
307:	learn: 0.3910121	total: 412ms	remaining: 926ms
308:	learn: 0.3896846	total: 414ms	remaining: 925ms
309:	learn: 0.3872130	total: 415ms	remaining: 923ms
310:	learn: 0.3865717	total: 416ms	remaining: 922ms
311:	learn: 0.3849013	total: 417ms	remaining: 920ms
312:	learn: 0.3832889	total: 419ms	remaining: 919ms
313:	learn: 0.3816755	total: 420ms	remaining: 917ms
314:	learn: 0.3804611	total: 421ms	remaining: 915ms
315:	learn: 0.3798479	total: 422ms	remaining: 913ms
316:	learn: 0.3783474	total: 423ms	remaining: 912ms
317:	learn: 0.3759934	total: 424ms	remaining: 910ms
318:	learn: 0.3745113	total: 426ms	remaining: 908ms
319:	learn: 0.3725304	total: 427ms	remaining: 907ms
320:	learn: 0.3709085	total: 430ms	remaining: 910ms
321:	learn: 0.3695383	total: 433ms	remaining: 911ms
322:	learn: 0.3683934	total: 435ms	remaining: 911ms
323:	learn: 0.3661718	total: 437ms	remaining: 912ms
324:	learn: 0.3657559	total: 439ms	remaining: 913ms
325:	learn: 0.3654384	total: 442ms	remaining: 913ms
326:	learn: 0.3650060	total: 444ms	remaining: 914ms
327:	learn: 0.3636972	total: 446ms	remaining: 913ms
328:	learn: 0.3622955	total: 447ms	remaining: 912ms
329:	learn: 0.3612157	total: 448ms	remaining: 910ms
330:	learn: 0.3606782	total: 449ms	remaining: 908ms
331:	learn: 0.3602429	total: 450ms	remaining: 906ms
332:	learn: 0.3597303	total: 451ms	remaining: 904ms
333:	learn: 0.3589264	total: 452ms	remaining: 902ms
334:	learn: 0.3586617	total: 454ms	remaining: 900ms
335:	learn: 0.3575247	total: 455ms	remaining: 898ms
336:	learn: 0.3561817	total: 456ms	remaining: 897ms
337:	learn: 0.3543490	total: 457ms	remaining: 895ms
338:	learn: 0.3539016	total: 458ms	remaining: 893ms
339:	learn: 0.3525632	total: 460ms	remaining: 892ms
340:	learn: 0.3506883	total: 462ms	remaining: 893ms
341:	learn: 0.3495972	total: 463ms	remaining: 892ms
342:	learn: 0.3485873	total: 465ms	remaining: 890ms
343:	learn: 0.3470136	total: 466ms	remaining: 889ms
344:	learn: 0.3459060	total: 467ms	remaining: 887ms
345:	learn: 0.3445469	total: 468ms	remaining: 885ms
346:	learn: 0.3433607	total: 469ms	remaining: 883ms
347:	learn: 0.3424007	total: 470ms	remaining: 881ms
348:	learn: 0.3419724	total: 472ms	remaining: 880ms
349:	learn: 0.3416305	total: 473ms	remaining: 878ms
350:	learn: 0.3399134	total: 474ms	remaining: 876ms
351:	learn: 0.3386262	total: 476ms	remaining: 877ms
352:	learn: 0.3371261	total: 477ms	remaining: 875ms
353:	learn: 0.3362122	total: 479ms	remaining: 873ms
354:	learn: 0.3347139	total: 480ms	remaining: 871ms
355:	learn: 0.3337301	total: 481ms	remaining: 870ms
356:	learn: 0.3333906	total: 482ms	remaining: 868ms
357:	learn: 0.3325422	total: 483ms	remaining: 866ms
358:	learn: 0.3316373	total: 484ms	remaining: 865ms
359:	learn: 0.3304466	total: 485ms	remaining: 863ms
360:	learn: 0.3296548	total: 486ms	remaining: 861ms
361:	learn: 0.3286410	total: 488ms	remaining: 859ms
362:	learn: 0.3283236	total: 489ms	remaining: 858ms
363:	learn: 0.3280121	total: 490ms	remaining: 856ms
364:	learn: 0.3277444	total: 491ms	remaining: 854ms
365:	learn: 0.3264310	total: 492ms	remaining: 853ms
366:	learn: 0.3250421	total: 494ms	remaining: 851ms
367:	learn: 0.3236581	total: 495ms	remaining: 850ms
368:	learn: 0.3227992	total: 496ms	remaining: 848ms
369:	learn: 0.3209075	total: 497ms	remaining: 847ms
370:	learn: 0.3202588	total: 499ms	remaining: 845ms
371:	learn: 0.3194357	total: 500ms	remaining: 844ms
372:	learn: 0.3177419	total: 501ms	remaining: 842ms
373:	learn: 0.3166506	total: 502ms	remaining: 840ms
374:	learn: 0.3150626	total: 503ms	remaining: 839ms
375:	learn: 0.3136516	total: 505ms	remaining: 837ms
376:	learn: 0.3130702	total: 506ms	remaining: 836ms
377:	learn: 0.3114167	total: 507ms	remaining: 835ms
378:	learn: 0.3103424	total: 509ms	remaining: 833ms
379:	learn: 0.3090538	total: 510ms	remaining: 832ms

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fitting SVR for TOA_9x9_depth_lt_1
Fitting KNN for TOA_9x9_depth_lt_1
Fitting LR for TOA_9x9_depth_lt_1
Fitting RF for TOA_9x9_depth_lt_1
Fitting CAT for TOA_9x9_depth_lt_1
Learning rate set to 0.033292
0:	learn: 3.7210601	total: 2.54ms	remaining: 2.54s
1:	learn: 3.6793353	total: 4.09ms	remaining: 2.04s
2:	learn: 3.6099350	total: 5.44ms	remaining: 1.81s
3:	learn: 3.5434714	total: 6.62ms	remaining: 1.65s
4:	learn: 3.4836950	total: 7.74ms	remaining: 1.54s
5:	learn: 3.4219449	total: 8.91ms	remaining: 1.48s
6:	learn: 3.3630898	total: 10.2ms	remaining: 1.44s
7:	learn: 3.3294184	total: 11.2ms	remaining: 1.39s
8:	learn: 3.2846224	total: 12.4ms	remaining: 1.36s
9:	learn: 3.2334022	total: 13.5ms	remaining: 1.34s
10:	learn: 3.1747038	total: 14.6ms	remaining: 1.32s
11:	learn: 3.1122483	total: 15.7ms	remaining: 1.3s
12:	learn: 3.0804302	total: 17.7ms	remaining: 1.34s
13:	learn: 3.0267600	total: 19.4ms	remaining: 1.37s
14:	learn: 2.9712097	total: 20.8ms	remaining: 1.37s
15:	learn: 2.9131400	total: 22ms	remaining: 1.35s
16:	learn: 2.8659452	total: 23.2ms	remaining: 1.34s
17:	learn: 2.8328489	total: 24.3ms	remaining: 1.32s
18:	learn: 2.7993915	total: 25.6ms	remaining: 1.32s
19:	learn: 2.7776976	total: 26.9ms	remaining: 1.32s
20:	learn: 2.7230164	total: 28.1ms	remaining: 1.31s
21:	learn: 2.6742100	total: 29.2ms	remaining: 1.3s
22:	learn: 2.6458151	total: 30.3ms	remaining: 1.29s
23:	learn: 2.6069783	total: 31.8ms	remaining: 1.29s
24:	learn: 2.5672794	total: 33.5ms	remaining: 1.3s
25:	learn: 2.5339983	total: 34.7ms	remaining: 1.3s
26:	learn: 2.5157649	total: 35.9ms	remaining: 1.29s
27:	learn: 2.4755411	total: 37.2ms	remaining: 1.29s
28:	learn: 2.4388145	total: 38.5ms	remaining: 1.29s
29:	learn: 2.4022209	total: 39.7ms	remaining: 1.28s
30:	learn: 2.3643328	total: 40.9ms	remaining: 1.28s
31:	learn: 2.3323984	total: 42.1ms	remaining: 1.27s
32:	learn: 2.2957565	total: 43.2ms	remaining: 1.26s
33:	learn: 2.2639583	total: 44.2ms	remaining: 1.26s
34:	learn: 2.2282225	total: 45.4ms	remaining: 1.25s
35:	learn: 2.1950485	total: 46.5ms	remaining: 1.24s
36:	learn: 2.1709688	total: 47.9ms	remaining: 1.25s
37:	learn: 2.1341242	total: 49.3ms	remaining: 1.25s
38:	learn: 2.1101088	total: 50.7ms	remaining: 1.25s
39:	learn: 2.0803118	total: 52ms	remaining: 1.25s
40:	learn: 2.0524397	total: 53.2ms	remaining: 1.25s
41:	learn: 2.0323832	total: 54.3ms	remaining: 1.24s
42:	learn: 2.0101768	total: 55.5ms	remaining: 1.23s
43:	learn: 1.9992874	total: 56.7ms	remaining: 1.23s
44:	learn: 1.9763174	total: 57.8ms	remaining: 1.23s
45:	learn: 1.9461671	total: 59ms	remaining: 1.22s
46:	learn: 1.9194143	total: 60.1ms	remaining: 1.22s
47:	learn: 1.8996552	total: 61.1ms	remaining: 1.21s
48:	learn: 1.8737495	total: 62.2ms	remaining: 1.21s
49:	learn: 1.8514948	total: 63.5ms	remaining: 1.21s
50:	learn: 1.8362545	total: 64.9ms	remaining: 1.21s
51:	learn: 1.8077415	total: 66.6ms	remaining: 1.21s
52:	learn: 1.7822281	total: 68ms	remaining: 1.21s
53:	learn: 1.7607649	total: 69.2ms	remaining: 1.21s
54:	learn: 1.7349642	total: 70.4ms	remaining: 1.21s
55:	learn: 1.7169589	total: 71.7ms	remaining: 1.21s
56:	learn: 1.6941858	total: 73ms	remaining: 1.21s
57:	learn: 1.6709169	total: 74.3ms	remaining: 1.21s
58:	learn: 1.6522790	total: 75.6ms	remaining: 1.21s
59:	learn: 1.6415686	total: 77.1ms	remaining: 1.21s
60:	learn: 1.6215438	total: 78.6ms	remaining: 1.21s
61:	learn: 1.5984419	total: 79.8ms	remaining: 1.21s
62:	learn: 1.5831356	total: 81.3ms	remaining: 1.21s
63:	learn: 1.5637972	total: 82.6ms	remaining: 1.21s
64:	learn: 1.5520781	total: 84.1ms	remaining: 1.21s
65:	learn: 1.5415554	total: 85.4ms	remaining: 1.21s
66:	learn: 1.5231308	total: 86.6ms	remaining: 1.21s
67:	learn: 1.5065654	total: 87.8ms	remaining: 1.2s
68:	learn: 1.4970202	total: 88.9ms	remaining: 1.2s
69:	learn: 1.4843397	total: 90ms	remaining: 1.2s
70:	learn: 1.4730232	total: 91.3ms	remaining: 1.19s
71:	learn: 1.4589649	total: 92.5ms	remaining: 1.19s
72:	learn: 1.4422102	total: 93.8ms	remaining: 1.19s
73:	learn: 1.4348460	total: 95.3ms	remaining: 1.19s
74:	learn: 1.4194223	total: 96.7ms	remaining: 1.19s
75:	learn: 1.4049329	total: 98.1ms	remaining: 1.19s
76:	learn: 1.3886726	total: 99.3ms	remaining: 1.19s
77:	learn: 1.3764500	total: 101ms	remaining: 1.19s
78:	learn: 1.3609942	total: 102ms	remaining: 1.19s
79:	learn: 1.3510403	total: 104ms	remaining: 1.2s
80:	learn: 1.3454473	total: 106ms	remaining: 1.2s
81:	learn: 1.3303290	total: 107ms	remaining: 1.2s
82:	learn: 1.3194532	total: 108ms	remaining: 1.2s
83:	learn: 1.3090385	total: 110ms	remaining: 1.2s
84:	learn: 1.3056779	total: 111ms	remaining: 1.2s
85:	learn: 1.2993461	total: 112ms	remaining: 1.2s
86:	learn: 1.2877719	total: 114ms	remaining: 1.19s
87:	learn: 1.2834100	total: 115ms	remaining: 1.19s
88:	learn: 1.2748709	total: 116ms	remaining: 1.19s
89:	learn: 1.2639525	total: 118ms	remaining: 1.19s
90:	learn: 1.2506291	total: 119ms	remaining: 1.19s
91:	learn: 1.2397078	total: 121ms	remaining: 1.19s
92:	learn: 1.2361074	total: 121ms	remaining: 1.18s
93:	learn: 1.2314162	total: 123ms	remaining: 1.18s
94:	learn: 1.2245532	total: 124ms	remaining: 1.18s
95:	learn: 1.2211340	total: 125ms	remaining: 1.18s
96:	learn: 1.2114179	total: 127ms	remaining: 1.18s
97:	learn: 1.2077126	total: 128ms	remaining: 1.18s
98:	learn: 1.1977952	total: 129ms	remaining: 1.18s
99:	learn: 1.1923033	total: 131ms	remaining: 1.18s
100:	learn: 1.1860265	total: 132ms	remaining: 1.18s
101:	learn: 1.1774110	total: 133ms	remaining: 1.17s
102:	learn: 1.1699762	total: 135ms	remaining: 1.17s
103:	learn: 1.1605970	total: 136ms	remaining: 1.17s
104:	learn: 1.1538735	total: 139ms	remaining: 1.19s
105:	learn: 1.1448763	total: 142ms	remaining: 1.2s
106:	learn: 1.1413871	total: 144ms	remaining: 1.2s
107:	learn: 1.1337247	total: 147ms	remaining: 1.21s
108:	learn: 1.1293299	total: 149ms	remaining: 1.22s
109:	learn: 1.1187471	total: 151ms	remaining: 1.22s
110:	learn: 1.1123879	total: 152ms	remaining: 1.22s
111:	learn: 1.1073480	total: 153ms	remaining: 1.22s
112:	learn: 1.0988632	total: 155ms	remaining: 1.22s
113:	learn: 1.0959759	total: 157ms	remaining: 1.22s
114:	learn: 1.0884783	total: 158ms	remaining: 1.21s
115:	learn: 1.0802017	total: 159ms	remaining: 1.21s
116:	learn: 1.0737508	total: 160ms	remaining: 1.21s
117:	learn: 1.0728954	total: 161ms	remaining: 1.2s
118:	learn: 1.0635433	total: 162ms	remaining: 1.2s
119:	learn: 1.0584477	total: 163ms	remaining: 1.2s
120:	learn: 1.0540131	total: 164ms	remaining: 1.19s
121:	learn: 1.0517005	total: 165ms	remaining: 1.19s
122:	learn: 1.0464682	total: 166ms	remaining: 1.19s
123:	learn: 1.0391360	total: 168ms	remaining: 1.19s
124:	learn: 1.0346727	total: 169ms	remaining: 1.19s
125:	learn: 1.0329152	total: 172ms	remaining: 1.19s
126:	learn: 1.0277378	total: 174ms	remaining: 1.19s
127:	learn: 1.0190228	total: 175ms	remaining: 1.19s
128:	learn: 1.0154341	total: 178ms	remaining: 1.2s
129:	learn: 1.0096327	total: 180ms	remaining: 1.2s
130:	learn: 1.0036401	total: 183ms	remaining: 1.21s
131:	learn: 1.0002386	total: 185ms	remaining: 1.22s
132:	learn: 0.9942865	total: 188ms	remaining: 1.22s
133:	learn: 0.9921039	total: 190ms	remaining: 1.23s
134:	learn: 0.9860403	total: 193ms	remaining: 1.24s
135:	learn: 0.9830909	total: 195ms	remaining: 1.24s
136:	learn: 0.9798465	total: 198ms	remaining: 1.25s
137:	learn: 0.9767909	total: 200ms	remaining: 1.25s
138:	learn: 0.9740841	total: 203ms	remaining: 1.25s
139:	learn: 0.9657026	total: 205ms	remaining: 1.26s
140:	learn: 0.9598635	total: 208ms	remaining: 1.27s
141:	learn: 0.9548209	total: 211ms	remaining: 1.27s
142:	learn: 0.9525254	total: 214ms	remaining: 1.28s
143:	learn: 0.9489698	total: 217ms	remaining: 1.29s
144:	learn: 0.9431615	total: 220ms	remaining: 1.29s
145:	learn: 0.9376413	total: 222ms	remaining: 1.3s
146:	learn: 0.9303165	total: 225ms	remaining: 1.3s
147:	learn: 0.9273700	total: 227ms	remaining: 1.31s
148:	learn: 0.9254643	total: 230ms	remaining: 1.31s
149:	learn: 0.9226854	total: 232ms	remaining: 1.31s
150:	learn: 0.9180303	total: 235ms	remaining: 1.32s
151:	learn: 0.9125590	total: 237ms	remaining: 1.32s
152:	learn: 0.9106183	total: 240ms	remaining: 1.33s
153:	learn: 0.9094047	total: 242ms	remaining: 1.33s
154:	learn: 0.9026623	total: 244ms	remaining: 1.33s
155:	learn: 0.8981022	total: 247ms	remaining: 1.34s
156:	learn: 0.8945502	total: 249ms	remaining: 1.34s
157:	learn: 0.8883807	total: 252ms	remaining: 1.34s
158:	learn: 0.8863014	total: 253ms	remaining: 1.34s
159:	learn: 0.8819870	total: 255ms	remaining: 1.34s
160:	learn: 0.8755399	total: 256ms	remaining: 1.34s
161:	learn: 0.8740341	total: 258ms	remaining: 1.33s
162:	learn: 0.8692324	total: 259ms	remaining: 1.33s
163:	learn: 0.8648084	total: 260ms	remaining: 1.33s
164:	learn: 0.8609413	total: 263ms	remaining: 1.33s
165:	learn: 0.8589768	total: 265ms	remaining: 1.33s
166:	learn: 0.8540553	total: 267ms	remaining: 1.33s
167:	learn: 0.8477840	total: 268ms	remaining: 1.33s
168:	learn: 0.8436982	total: 270ms	remaining: 1.33s
169:	learn: 0.8379933	total: 271ms	remaining: 1.32s
170:	learn: 0.8336155	total: 272ms	remaining: 1.32s
171:	learn: 0.8305734	total: 274ms	remaining: 1.32s
172:	learn: 0.8244071	total: 275ms	remaining: 1.31s
173:	learn: 0.8185763	total: 277ms	remaining: 1.31s
174:	learn: 0.8150969	total: 278ms	remaining: 1.31s
175:	learn: 0.8125160	total: 280ms	remaining: 1.31s
176:	learn: 0.8107084	total: 281ms	remaining: 1.31s
177:	learn: 0.8056962	total: 283ms	remaining: 1.31s
178:	learn: 0.8038470	total: 284ms	remaining: 1.3s
179:	learn: 0.7985488	total: 286ms	remaining: 1.3s
180:	learn: 0.7925883	total: 287ms	remaining: 1.3s
181:	learn: 0.7871088	total: 289ms	remaining: 1.3s
182:	learn: 0.7829510	total: 291ms	remaining: 1.3s
183:	learn: 0.7803294	total: 292ms	remaining: 1.29s
184:	learn: 0.7756435	total: 294ms	remaining: 1.29s
185:	learn: 0.7710550	total: 296ms	remaining: 1.29s
186:	learn: 0.7652806	total: 297ms	remaining: 1.29s
187:	learn: 0.7593383	total: 299ms	remaining: 1.29s
188:	learn: 0.7538566	total: 300ms	remaining: 1.29s
189:	learn: 0.7481535	total: 302ms	remaining: 1.28s
190:	learn: 0.7450071	total: 303ms	remaining: 1.28s
191:	learn: 0.7413741	total: 304ms	remaining: 1.28s
192:	learn: 0.7355703	total: 306ms	remaining: 1.28s
193:	learn: 0.7341351	total: 308ms	remaining: 1.28s
194:	learn: 0.7319303	total: 309ms	remaining: 1.28s
195:	learn: 0.7303587	total: 313ms	remaining: 1.28s
196:	learn: 0.7258563	total: 314ms	remaining: 1.28s
197:	learn: 0.7214520	total: 316ms	remaining: 1.28s
198:	learn: 0.7187238	total: 317ms	remaining: 1.28s
199:	learn: 0.7139652	total: 319ms	remaining: 1.27s
200:	learn: 0.7118825	total: 321ms	remaining: 1.27s
201:	learn: 0.7095694	total: 322ms	remaining: 1.27s
202:	learn: 0.7058133	total: 323ms	remaining: 1.27s
203:	learn: 0.7032103	total: 325ms	remaining: 1.27s
204:	learn: 0.6997756	total: 327ms	remaining: 1.27s
205:	learn: 0.6956130	total: 329ms	remaining: 1.27s
206:	learn: 0.6919344	total: 330ms	remaining: 1.26s
207:	learn: 0.6891505	total: 331ms	remaining: 1.26s
208:	learn: 0.6871475	total: 334ms	remaining: 1.26s
209:	learn: 0.6838458	total: 335ms	remaining: 1.26s
210:	learn: 0.6819257	total: 336ms	remaining: 1.26s
211:	learn: 0.6779266	total: 337ms	remaining: 1.25s
212:	learn: 0.6738272	total: 338ms	remaining: 1.25s
213:	learn: 0.6700051	total: 340ms	remaining: 1.25s
214:	learn: 0.6678862	total: 343ms	remaining: 1.25s
215:	learn: 0.6673093	total: 344ms	remaining: 1.25s
216:	learn: 0.6640676	total: 345ms	remaining: 1.25s
217:	learn: 0.6628429	total: 346ms	remaining: 1.24s
218:	learn: 0.6605499	total: 348ms	remaining: 1.24s
219:	learn: 0.6594798	total: 349ms	remaining: 1.24s
220:	learn: 0.6584814	total: 350ms	remaining: 1.24s
221:	learn: 0.6567707	total: 352ms	remaining: 1.23s
222:	learn: 0.6557382	total: 353ms	remaining: 1.23s
223:	learn: 0.6531063	total: 354ms	remaining: 1.23s
224:	learn: 0.6493104	total: 357ms	remaining: 1.23s
225:	learn: 0.6486670	total: 358ms	remaining: 1.23s
226:	learn: 0.6466995	total: 359ms	remaining: 1.22s
227:	learn: 0.6443914	total: 361ms	remaining: 1.22s
228:	learn: 0.6408047	total: 362ms	remaining: 1.22s
229:	learn: 0.6386751	total: 364ms	remaining: 1.22s
230:	learn: 0.6333898	total: 366ms	remaining: 1.22s
231:	learn: 0.6311133	total: 369ms	remaining: 1.22s
232:	learn: 0.6274724	total: 371ms	remaining: 1.22s
233:	learn: 0.6253199	total: 374ms	remaining: 1.22s
234:	learn: 0.6240060	total: 376ms	remaining: 1.22s
235:	learn: 0.6216246	total: 377ms	remaining: 1.22s
236:	learn: 0.6182771	total: 379ms	remaining: 1.22s
237:	learn: 0.6170552	total: 380ms	remaining: 1.22s
238:	learn: 0.6147541	total: 382ms	remaining: 1.22s
239:	learn: 0.6107222	total: 383ms	remaining: 1.21s
240:	learn: 0.6086060	total: 385ms	remaining: 1.21s
241:	learn: 0.6081126	total: 386ms	remaining: 1.21s
242:	learn: 0.6063528	total: 388ms	remaining: 1.21s
243:	learn: 0.6057665	total: 390ms	remaining: 1.21s
244:	learn: 0.6034834	total: 391ms	remaining: 1.21s
245:	learn: 0.6029243	total: 393ms	remaining: 1.2s
246:	learn: 0.5992140	total: 394ms	remaining: 1.2s
247:	learn: 0.5973346	total: 396ms	remaining: 1.2s
248:	learn: 0.5946781	total: 397ms	remaining: 1.2s
249:	learn: 0.5925928	total: 398ms	remaining: 1.19s
250:	learn: 0.5920487	total: 400ms	remaining: 1.19s
251:	learn: 0.5905904	total: 401ms	remaining: 1.19s
252:	learn: 0.5873319	total: 403ms	remaining: 1.19s
253:	learn: 0.5862214	total: 405ms	remaining: 1.19s
254:	learn: 0.5849511	total: 407ms	remaining: 1.19s
255:	learn: 0.5829749	total: 408ms	remaining: 1.19s
256:	learn: 0.5824483	total: 409ms	remaining: 1.18s
257:	learn: 0.5803693	total: 411ms	remaining: 1.18s
258:	learn: 0.5786366	total: 412ms	remaining: 1.18s
259:	learn: 0.5759326	total: 413ms	remaining: 1.18s
260:	learn: 0.5718543	total: 415ms	remaining: 1.18s
261:	learn: 0.5714105	total: 417ms	remaining: 1.17s
262:	learn: 0.5676730	total: 419ms	remaining: 1.18s
263:	learn: 0.5672209	total: 421ms	remaining: 1.17s
264:	learn: 0.5650543	total: 424ms	remaining: 1.18s
265:	learn: 0.5630571	total: 426ms	remaining: 1.17s
266:	learn: 0.5626097	total: 427ms	remaining: 1.17s
267:	learn: 0.5605355	total: 429ms	remaining: 1.17s
268:	learn: 0.5572047	total: 432ms	remaining: 1.17s
269:	learn: 0.5551102	total: 435ms	remaining: 1.18s
270:	learn: 0.5545809	total: 437ms	remaining: 1.18s
271:	learn: 0.5536359	total: 439ms	remaining: 1.17s
272:	learn: 0.5513922	total: 440ms	remaining: 1.17s
273:	learn: 0.5493465	total: 442ms	remaining: 1.17s
274:	learn: 0.5474732	total: 444ms	remaining: 1.17s
275:	learn: 0.5470437	total: 445ms	remaining: 1.17s
276:	learn: 0.5435693	total: 447ms	remaining: 1.17s
277:	learn: 0.5417529	total: 450ms	remaining: 1.17s
278:	learn: 0.5414756	total: 452ms	remaining: 1.17s
279:	learn: 0.5372458	total: 455ms	remaining: 1.17s
280:	learn: 0.5332333	total: 462ms	remaining: 1.18s
281:	learn: 0.5316905	total: 468ms	remaining: 1.19s
282:	learn: 0.5313022	total: 472ms	remaining: 1.19s
283:	learn: 0.5307992	total: 476ms	remaining: 1.2s
284:	learn: 0.5281306	total: 479ms	remaining: 1.2s
285:	learn: 0.5267656	total: 485ms	remaining: 1.21s
286:	learn: 0.5263465	total: 490ms	remaining: 1.22s
287:	learn: 0.5231894	total: 494ms	remaining: 1.22s
288:	learn: 0.5206914	total: 498ms	remaining: 1.23s
289:	learn: 0.5191481	total: 501ms	remaining: 1.23s
290:	learn: 0.5175930	total: 502ms	remaining: 1.22s
291:	learn: 0.5156582	total: 503ms	remaining: 1.22s
292:	learn: 0.5132457	total: 505ms	remaining: 1.22s
293:	learn: 0.5115284	total: 506ms	remaining: 1.22s
294:	learn: 0.5097770	total: 508ms	remaining: 1.21s
295:	learn: 0.5070235	total: 509ms	remaining: 1.21s
296:	learn: 0.5052986	total: 511ms	remaining: 1.21s
297:	learn: 0.5031771	total: 512ms	remaining: 1.21s
298:	learn: 0.5016470	total: 514ms	remaining: 1.2s
299:	learn: 0.4997814	total: 518ms	remaining: 1.21s
300:	learn: 0.4986543	total: 522ms	remaining: 1.21s
301:	learn: 0.4970252	total: 526ms	remaining: 1.22s
302:	learn: 0.4945561	total: 529ms	remaining: 1.22s
303:	learn: 0.4920956	total: 533ms	remaining: 1.22s
304:	learn: 0.4917243	total: 535ms	remaining: 1.22s
305:	learn: 0.4902390	total: 538ms	remaining: 1.22s
306:	learn: 0.4884046	total: 541ms	remaining: 1.22s
307:	learn: 0.4848577	total: 544ms	remaining: 1.22s
308:	learn: 0.4819819	total: 545ms	remaining: 1.22s
309:	learn: 0.4805625	total: 546ms	remaining: 1.22s
310:	learn: 0.4791489	total: 548ms	remaining: 1.21s
311:	learn: 0.4778677	total: 549ms	remaining: 1.21s
312:	learn: 0.4760602	total: 550ms	remaining: 1.21s
313:	learn: 0.4740153	total: 552ms	remaining: 1.21s
314:	learn: 0.4713784	total: 553ms	remaining: 1.2s
315:	learn: 0.4683935	total: 554ms	remaining: 1.2s
316:	learn: 0.4673266	total: 555ms	remaining: 1.2s
317:	learn: 0.4648509	total: 557ms	remaining: 1.19s
318:	learn: 0.4625937	total: 558ms	remaining: 1.19s
319:	learn: 0.4615410	total: 559ms	remaining: 1.19s
320:	learn: 0.4602272	total: 560ms	remaining: 1.19s
321:	learn: 0.4587224	total: 562ms	remaining: 1.18s
322:	learn: 0.4569541	total: 563ms	remaining: 1.18s
323:	learn: 0.4565459	total: 564ms	remaining: 1.18s
324:	learn: 0.4561790	total: 565ms	remaining: 1.17s
325:	learn: 0.4550828	total: 567ms	remaining: 1.17s
326:	learn: 0.4526294	total: 568ms	remaining: 1.17s
327:	learn: 0.4500597	total: 570ms	remaining: 1.17s
328:	learn: 0.4478032	total: 571ms	remaining: 1.16s
329:	learn: 0.4467401	total: 572ms	remaining: 1.16s
330:	learn: 0.4447919	total: 573ms	remaining: 1.16s
331:	learn: 0.4437142	total: 575ms	remaining: 1.16s
332:	learn: 0.4429657	total: 576ms	remaining: 1.15s
333:	learn: 0.4412793	total: 577ms	remaining: 1.15s
334:	learn: 0.4400092	total: 579ms	remaining: 1.15s
335:	learn: 0.4390258	total: 580ms	remaining: 1.15s
336:	learn: 0.4387785	total: 581ms	remaining: 1.14s
337:	learn: 0.4368210	total: 582ms	remaining: 1.14s
338:	learn: 0.4352837	total: 583ms	remaining: 1.14s
339:	learn: 0.4350417	total: 585ms	remaining: 1.14s
340:	learn: 0.4339416	total: 587ms	remaining: 1.13s
341:	learn: 0.4335687	total: 588ms	remaining: 1.13s
342:	learn: 0.4320110	total: 590ms	remaining: 1.13s
343:	learn: 0.4307133	total: 591ms	remaining: 1.13s
344:	learn: 0.4290957	total: 592ms	remaining: 1.12s
345:	learn: 0.4263842	total: 593ms	remaining: 1.12s
346:	learn: 0.4241164	total: 594ms	remaining: 1.12s
347:	learn: 0.4227683	total: 595ms	remaining: 1.11s
348:	learn: 0.4225285	total: 596ms	remaining: 1.11s
349:	learn: 0.4210570	total: 597ms	remaining: 1.11s
350:	learn: 0.4198152	total: 599ms	remaining: 1.11s
351:	learn: 0.4195749	total: 602ms	remaining: 1.11s
352:	learn: 0.4185029	total: 604ms	remaining: 1.11s
353:	learn: 0.4162050	total: 606ms	remaining: 1.11s
354:	learn: 0.4152755	total: 609ms	remaining: 1.11s
355:	learn: 0.4140897	total: 611ms	remaining: 1.1s
356:	learn: 0.4122894	total: 614ms	remaining: 1.1s
357:	learn: 0.4120569	total: 616ms	remaining: 1.1s
358:	learn: 0.4118333	total: 618ms	remaining: 1.1s
359:	learn: 0.4115102	total: 621ms	remaining: 1.1s
360:	learn: 0.4092619	total: 624ms	remaining: 1.1s
361:	learn: 0.4085692	total: 626ms	remaining: 1.1s
362:	learn: 0.4072134	total: 628ms	remaining: 1.1s
363:	learn: 0.4054825	total: 631ms	remaining: 1.1s
364:	learn: 0.4038002	total: 633ms	remaining: 1.1s
365:	learn: 0.4022712	total: 636ms	remaining: 1.1s
366:	learn: 0.4011709	total: 637ms	remaining: 1.1s
367:	learn: 0.4003810	total: 638ms	remaining: 1.1s
368:	learn: 0.3992560	total: 640ms	remaining: 1.09s
369:	learn: 0.3991066	total: 641ms	remaining: 1.09s
370:	learn: 0.3981329	total: 642ms	remaining: 1.09s
371:	learn: 0.3979430	total: 643ms	remaining: 1.08s
372:	learn: 0.3967754	total: 644ms	remaining: 1.08s
373:	learn: 0.3957161	total: 646ms	remaining: 1.08s
374:	learn: 0.3932840	total: 647ms	remaining: 1.08s
375:	learn: 0.3918738	total: 648ms	remaining: 1.08s
376:	learn: 0.3910465	total: 651ms	remaining: 1.08s
377:	learn: 0.3892227	total: 653ms	remaining: 1.07s
378:	learn: 0.3881161	total: 654ms	remaining: 1.07s
379:	learn: 0.3865033	total: 655ms	remaining: 1.07s
380:	learn: 0.3850129	total: 657ms	remaining: 1.07s
381:	learn: 0.3833570	total: 658ms	remaining: 1.06s

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fitting SVR for C2X_rhow_3x3_depth_lt_1
Fitting KNN for C2X_rhow_3x3_depth_lt_1
Fitting LR for C2X_rhow_3x3_depth_lt_1
Fitting RF for C2X_rhow_3x3_depth_lt_1
Fitting CAT for C2X_rhow_3x3_depth_lt_1
Learning rate set to 0.033272
0:	learn: 3.4170961	total: 2.5ms	remaining: 2.5s
1:	learn: 3.3730500	total: 3.94ms	remaining: 1.97s
2:	learn: 3.3283392	total: 5.34ms	remaining: 1.77s
3:	learn: 3.2733346	total: 6.81ms	remaining: 1.7s
4:	learn: 3.2222519	total: 8.07ms	remaining: 1.61s
5:	learn: 3.1810080	total: 9.28ms	remaining: 1.54s
6:	learn: 3.1354723	total: 10.5ms	remaining: 1.49s
7:	learn: 3.0984250	total: 11.8ms	remaining: 1.47s
8:	learn: 3.0554954	total: 13.3ms	remaining: 1.46s
9:	learn: 3.0120236	total: 14.5ms	remaining: 1.44s
10:	learn: 2.9815164	total: 15.8ms	remaining: 1.42s
11:	learn: 2.9433821	total: 17.2ms	remaining: 1.41s
12:	learn: 2.9073967	total: 18.8ms	remaining: 1.43s
13:	learn: 2.8781994	total: 20.5ms	remaining: 1.44s
14:	learn: 2.8422505	total: 21.8ms	remaining: 1.43s
15:	learn: 2.8075492	total: 23.2ms	remaining: 1.43s
16:	learn: 2.7722880	total: 24.4ms	remaining: 1.41s
17:	learn: 2.7398766	total: 25.7ms	remaining: 1.4s
18:	learn: 2.7104411	total: 26.9ms	remaining: 1.39s
19:	learn: 2.6848206	total: 28.2ms	remaining: 1.38s
20:	learn: 2.6499332	total: 29.4ms	remaining: 1.37s
21:	learn: 2.6248252	total: 30.6ms	remaining: 1.36s
22:	learn: 2.5942177	total: 31.8ms	remaining: 1.35s
23:	learn: 2.5663871	total: 33.4ms	remaining: 1.36s
24:	learn: 2.5391930	total: 34.8ms	remaining: 1.36s
25:	learn: 2.5226886	total: 36.3ms	remaining: 1.36s
26:	learn: 2.5036796	total: 37.5ms	remaining: 1.35s
27:	learn: 2.4780652	total: 38.8ms	remaining: 1.35s
28:	learn: 2.4560094	total: 40.1ms	remaining: 1.34s
29:	learn: 2.4345962	total: 41.3ms	remaining: 1.33s
30:	learn: 2.4074702	total: 42.5ms	remaining: 1.33s
31:	learn: 2.3790570	total: 43.7ms	remaining: 1.32s
32:	learn: 2.3602114	total: 44.9ms	remaining: 1.32s
33:	learn: 2.3352621	total: 46.2ms	remaining: 1.31s
34:	learn: 2.3116310	total: 47.3ms	remaining: 1.3s
35:	learn: 2.2848904	total: 48.7ms	remaining: 1.3s
36:	learn: 2.2583857	total: 50.6ms	remaining: 1.32s
37:	learn: 2.2352833	total: 52ms	remaining: 1.32s
38:	learn: 2.2110061	total: 53.3ms	remaining: 1.31s
39:	learn: 2.1879630	total: 54.7ms	remaining: 1.31s
40:	learn: 2.1710603	total: 55.9ms	remaining: 1.31s
41:	learn: 2.1564420	total: 57ms	remaining: 1.3s
42:	learn: 2.1339920	total: 58.3ms	remaining: 1.3s
43:	learn: 2.1150276	total: 59.5ms	remaining: 1.29s
44:	learn: 2.0960046	total: 60.7ms	remaining: 1.29s
45:	learn: 2.0764572	total: 61.9ms	remaining: 1.28s
46:	learn: 2.0613159	total: 63.1ms	remaining: 1.28s
47:	learn: 2.0426047	total: 64.4ms	remaining: 1.28s
48:	learn: 2.0210631	total: 66.3ms	remaining: 1.29s
49:	learn: 2.0056199	total: 67.6ms	remaining: 1.28s
50:	learn: 1.9923581	total: 69.1ms	remaining: 1.29s
51:	learn: 1.9782681	total: 70.4ms	remaining: 1.28s
52:	learn: 1.9570850	total: 71.7ms	remaining: 1.28s
53:	learn: 1.9383511	total: 72.9ms	remaining: 1.28s
54:	learn: 1.9198196	total: 74.4ms	remaining: 1.28s
55:	learn: 1.9075668	total: 75.5ms	remaining: 1.27s
56:	learn: 1.8883574	total: 76.8ms	remaining: 1.27s
57:	learn: 1.8725706	total: 78ms	remaining: 1.27s
58:	learn: 1.8633198	total: 79.3ms	remaining: 1.26s
59:	learn: 1.8556833	total: 81.1ms	remaining: 1.27s
60:	learn: 1.8392664	total: 82.5ms	remaining: 1.27s
61:	learn: 1.8229940	total: 84.2ms	remaining: 1.27s
62:	learn: 1.8103505	total: 85.5ms	remaining: 1.27s
63:	learn: 1.8001138	total: 86.6ms	remaining: 1.27s
64:	learn: 1.7838892	total: 87.9ms	remaining: 1.26s
65:	learn: 1.7675806	total: 89.2ms	remaining: 1.26s
66:	learn: 1.7543641	total: 90.4ms	remaining: 1.26s
67:	learn: 1.7414432	total: 91.7ms	remaining: 1.26s
68:	learn: 1.7364680	total: 92.9ms	remaining: 1.25s
69:	learn: 1.7261491	total: 94.1ms	remaining: 1.25s
70:	learn: 1.7102851	total: 95.4ms	remaining: 1.25s
71:	learn: 1.6978532	total: 96.7ms	remaining: 1.25s
72:	learn: 1.6851957	total: 98.1ms	remaining: 1.25s
73:	learn: 1.6777958	total: 99.6ms	remaining: 1.25s
74:	learn: 1.6660360	total: 101ms	remaining: 1.25s
75:	learn: 1.6527963	total: 102ms	remaining: 1.24s
76:	learn: 1.6423744	total: 103ms	remaining: 1.24s
77:	learn: 1.6302515	total: 105ms	remaining: 1.24s
78:	learn: 1.6209589	total: 106ms	remaining: 1.23s
79:	learn: 1.6072181	total: 108ms	remaining: 1.24s
80:	learn: 1.5904930	total: 109ms	remaining: 1.24s
81:	learn: 1.5813720	total: 111ms	remaining: 1.24s
82:	learn: 1.5783022	total: 112ms	remaining: 1.24s
83:	learn: 1.5703544	total: 113ms	remaining: 1.24s
84:	learn: 1.5601385	total: 115ms	remaining: 1.24s
85:	learn: 1.5511340	total: 116ms	remaining: 1.24s
86:	learn: 1.5400463	total: 117ms	remaining: 1.23s
87:	learn: 1.5326171	total: 119ms	remaining: 1.23s
88:	learn: 1.5277487	total: 120ms	remaining: 1.23s
89:	learn: 1.5195839	total: 121ms	remaining: 1.22s
90:	learn: 1.5119943	total: 122ms	remaining: 1.22s
91:	learn: 1.5079903	total: 124ms	remaining: 1.22s
92:	learn: 1.4971179	total: 125ms	remaining: 1.22s
93:	learn: 1.4842967	total: 126ms	remaining: 1.21s
94:	learn: 1.4745519	total: 127ms	remaining: 1.21s
95:	learn: 1.4706639	total: 129ms	remaining: 1.21s
96:	learn: 1.4598441	total: 130ms	remaining: 1.21s
97:	learn: 1.4525869	total: 131ms	remaining: 1.21s
98:	learn: 1.4465567	total: 133ms	remaining: 1.21s
99:	learn: 1.4308384	total: 134ms	remaining: 1.2s
100:	learn: 1.4233670	total: 135ms	remaining: 1.2s
101:	learn: 1.4207336	total: 136ms	remaining: 1.2s
102:	learn: 1.4122362	total: 137ms	remaining: 1.19s
103:	learn: 1.4093142	total: 138ms	remaining: 1.19s
104:	learn: 1.4000080	total: 139ms	remaining: 1.19s
105:	learn: 1.3947451	total: 141ms	remaining: 1.19s
106:	learn: 1.3860122	total: 142ms	remaining: 1.18s
107:	learn: 1.3797896	total: 144ms	remaining: 1.19s
108:	learn: 1.3676356	total: 145ms	remaining: 1.18s
109:	learn: 1.3608005	total: 147ms	remaining: 1.19s
110:	learn: 1.3510621	total: 148ms	remaining: 1.18s
111:	learn: 1.3444907	total: 149ms	remaining: 1.18s
112:	learn: 1.3409883	total: 150ms	remaining: 1.18s
113:	learn: 1.3352636	total: 151ms	remaining: 1.18s
114:	learn: 1.3298059	total: 153ms	remaining: 1.17s
115:	learn: 1.3168999	total: 154ms	remaining: 1.17s
116:	learn: 1.3129256	total: 155ms	remaining: 1.17s
117:	learn: 1.3060112	total: 156ms	remaining: 1.17s
118:	learn: 1.3000257	total: 157ms	remaining: 1.16s
119:	learn: 1.2965863	total: 158ms	remaining: 1.16s
120:	learn: 1.2903914	total: 160ms	remaining: 1.16s
121:	learn: 1.2813416	total: 161ms	remaining: 1.16s
122:	learn: 1.2760047	total: 163ms	remaining: 1.16s
123:	learn: 1.2656896	total: 164ms	remaining: 1.16s
124:	learn: 1.2543429	total: 165ms	remaining: 1.16s
125:	learn: 1.2483950	total: 167ms	remaining: 1.16s
126:	learn: 1.2380057	total: 168ms	remaining: 1.16s
127:	learn: 1.2319350	total: 169ms	remaining: 1.15s
128:	learn: 1.2272940	total: 171ms	remaining: 1.15s
129:	learn: 1.2166880	total: 172ms	remaining: 1.15s
130:	learn: 1.2127313	total: 173ms	remaining: 1.15s
131:	learn: 1.2012643	total: 175ms	remaining: 1.15s
132:	learn: 1.1939658	total: 176ms	remaining: 1.15s
133:	learn: 1.1918084	total: 178ms	remaining: 1.15s
134:	learn: 1.1827446	total: 179ms	remaining: 1.15s
135:	learn: 1.1775501	total: 181ms	remaining: 1.15s
136:	learn: 1.1740267	total: 182ms	remaining: 1.15s
137:	learn: 1.1656526	total: 183ms	remaining: 1.14s
138:	learn: 1.1578731	total: 184ms	remaining: 1.14s
139:	learn: 1.1544120	total: 185ms	remaining: 1.14s
140:	learn: 1.1466031	total: 187ms	remaining: 1.14s
141:	learn: 1.1418156	total: 188ms	remaining: 1.14s
142:	learn: 1.1337316	total: 189ms	remaining: 1.13s
143:	learn: 1.1262592	total: 191ms	remaining: 1.13s
144:	learn: 1.1234400	total: 192ms	remaining: 1.13s
145:	learn: 1.1194218	total: 194ms	remaining: 1.13s
146:	learn: 1.1164191	total: 195ms	remaining: 1.13s
147:	learn: 1.1085726	total: 196ms	remaining: 1.13s
148:	learn: 1.1053253	total: 197ms	remaining: 1.13s
149:	learn: 1.1038322	total: 199ms	remaining: 1.13s
150:	learn: 1.0965570	total: 200ms	remaining: 1.12s
151:	learn: 1.0933907	total: 201ms	remaining: 1.12s
152:	learn: 1.0866135	total: 203ms	remaining: 1.12s
153:	learn: 1.0830570	total: 204ms	remaining: 1.12s
154:	learn: 1.0796259	total: 206ms	remaining: 1.12s
155:	learn: 1.0734184	total: 207ms	remaining: 1.12s
156:	learn: 1.0693687	total: 208ms	remaining: 1.12s
157:	learn: 1.0623462	total: 210ms	remaining: 1.12s
158:	learn: 1.0546991	total: 211ms	remaining: 1.12s
159:	learn: 1.0518491	total: 213ms	remaining: 1.12s
160:	learn: 1.0446936	total: 214ms	remaining: 1.11s
161:	learn: 1.0383606	total: 215ms	remaining: 1.11s
162:	learn: 1.0345973	total: 216ms	remaining: 1.11s
163:	learn: 1.0292167	total: 217ms	remaining: 1.11s
164:	learn: 1.0208340	total: 219ms	remaining: 1.11s
165:	learn: 1.0164399	total: 220ms	remaining: 1.11s
166:	learn: 1.0113343	total: 222ms	remaining: 1.11s
167:	learn: 1.0071172	total: 224ms	remaining: 1.11s
168:	learn: 1.0015798	total: 226ms	remaining: 1.11s
169:	learn: 0.9971271	total: 227ms	remaining: 1.11s
170:	learn: 0.9920152	total: 228ms	remaining: 1.1s
171:	learn: 0.9881373	total: 229ms	remaining: 1.1s
172:	learn: 0.9856107	total: 232ms	remaining: 1.11s
173:	learn: 0.9815758	total: 235ms	remaining: 1.11s
174:	learn: 0.9721184	total: 238ms	remaining: 1.12s
175:	learn: 0.9629196	total: 241ms	remaining: 1.13s
176:	learn: 0.9605727	total: 244ms	remaining: 1.13s
177:	learn: 0.9522157	total: 247ms	remaining: 1.14s
178:	learn: 0.9441721	total: 249ms	remaining: 1.14s
179:	learn: 0.9424003	total: 250ms	remaining: 1.14s
180:	learn: 0.9356660	total: 253ms	remaining: 1.15s
181:	learn: 0.9279192	total: 256ms	remaining: 1.15s
182:	learn: 0.9234821	total: 259ms	remaining: 1.16s
183:	learn: 0.9183850	total: 261ms	remaining: 1.16s
184:	learn: 0.9128526	total: 262ms	remaining: 1.15s
185:	learn: 0.9070001	total: 263ms	remaining: 1.15s
186:	learn: 0.9059189	total: 265ms	remaining: 1.15s
187:	learn: 0.8981542	total: 266ms	remaining: 1.15s
188:	learn: 0.8969579	total: 268ms	remaining: 1.15s
189:	learn: 0.8922053	total: 269ms	remaining: 1.15s
190:	learn: 0.8856433	total: 271ms	remaining: 1.15s
191:	learn: 0.8839147	total: 272ms	remaining: 1.14s
192:	learn: 0.8777884	total: 273ms	remaining: 1.14s
193:	learn: 0.8731530	total: 275ms	remaining: 1.14s
194:	learn: 0.8669676	total: 276ms	remaining: 1.14s
195:	learn: 0.8654199	total: 278ms	remaining: 1.14s
196:	learn: 0.8597315	total: 279ms	remaining: 1.14s
197:	learn: 0.8584800	total: 280ms	remaining: 1.14s
198:	learn: 0.8552456	total: 282ms	remaining: 1.13s
199:	learn: 0.8507425	total: 284ms	remaining: 1.14s
200:	learn: 0.8485134	total: 286ms	remaining: 1.14s
201:	learn: 0.8449910	total: 287ms	remaining: 1.13s
202:	learn: 0.8388681	total: 289ms	remaining: 1.13s
203:	learn: 0.8381814	total: 290ms	remaining: 1.13s
204:	learn: 0.8360785	total: 291ms	remaining: 1.13s
205:	learn: 0.8337065	total: 293ms	remaining: 1.13s
206:	learn: 0.8289561	total: 294ms	remaining: 1.13s
207:	learn: 0.8229421	total: 296ms	remaining: 1.13s
208:	learn: 0.8196330	total: 297ms	remaining: 1.13s
209:	learn: 0.8171226	total: 299ms	remaining: 1.12s
210:	learn: 0.8107719	total: 300ms	remaining: 1.12s
211:	learn: 0.8070715	total: 302ms	remaining: 1.12s
212:	learn: 0.8017804	total: 303ms	remaining: 1.12s
213:	learn: 0.7978809	total: 305ms	remaining: 1.12s
214:	learn: 0.7931602	total: 306ms	remaining: 1.12s
215:	learn: 0.7886917	total: 308ms	remaining: 1.12s
216:	learn: 0.7855738	total: 309ms	remaining: 1.11s
217:	learn: 0.7816861	total: 311ms	remaining: 1.11s
218:	learn: 0.7746422	total: 312ms	remaining: 1.11s
219:	learn: 0.7726115	total: 314ms	remaining: 1.11s
220:	learn: 0.7691069	total: 316ms	remaining: 1.11s
221:	learn: 0.7633692	total: 317ms	remaining: 1.11s
222:	learn: 0.7596491	total: 319ms	remaining: 1.11s
223:	learn: 0.7577867	total: 320ms	remaining: 1.11s
224:	learn: 0.7517038	total: 322ms	remaining: 1.11s
225:	learn: 0.7495827	total: 323ms	remaining: 1.11s
226:	learn: 0.7430426	total: 324ms	remaining: 1.1s
227:	learn: 0.7395852	total: 326ms	remaining: 1.1s
228:	learn: 0.7349582	total: 327ms	remaining: 1.1s
229:	learn: 0.7290565	total: 329ms	remaining: 1.1s
230:	learn: 0.7240718	total: 330ms	remaining: 1.1s
231:	learn: 0.7208386	total: 332ms	remaining: 1.1s
232:	learn: 0.7186422	total: 333ms	remaining: 1.1s
233:	learn: 0.7138500	total: 334ms	remaining: 1.09s
234:	learn: 0.7108082	total: 336ms	remaining: 1.09s
235:	learn: 0.7053989	total: 337ms	remaining: 1.09s
236:	learn: 0.7015430	total: 339ms	remaining: 1.09s
237:	learn: 0.6980487	total: 340ms	remaining: 1.09s
238:	learn: 0.6941220	total: 342ms	remaining: 1.09s
239:	learn: 0.6917520	total: 344ms	remaining: 1.09s
240:	learn: 0.6864916	total: 346ms	remaining: 1.09s
241:	learn: 0.6839224	total: 348ms	remaining: 1.09s
242:	learn: 0.6800907	total: 349ms	remaining: 1.09s
243:	learn: 0.6756411	total: 350ms	remaining: 1.08s
244:	learn: 0.6707188	total: 352ms	remaining: 1.08s
245:	learn: 0.6689210	total: 353ms	remaining: 1.08s
246:	learn: 0.6651134	total: 356ms	remaining: 1.08s
247:	learn: 0.6619963	total: 357ms	remaining: 1.08s
248:	learn: 0.6573740	total: 358ms	remaining: 1.08s
249:	learn: 0.6511108	total: 361ms	remaining: 1.08s
250:	learn: 0.6456846	total: 362ms	remaining: 1.08s
251:	learn: 0.6397237	total: 364ms	remaining: 1.08s
252:	learn: 0.6371363	total: 366ms	remaining: 1.08s
253:	learn: 0.6337689	total: 367ms	remaining: 1.08s
254:	learn: 0.6332192	total: 369ms	remaining: 1.08s
255:	learn: 0.6319715	total: 370ms	remaining: 1.07s
256:	learn: 0.6285203	total: 371ms	remaining: 1.07s
257:	learn: 0.6249493	total: 373ms	remaining: 1.07s
258:	learn: 0.6208451	total: 374ms	remaining: 1.07s
259:	learn: 0.6189333	total: 376ms	remaining: 1.07s
260:	learn: 0.6145189	total: 378ms	remaining: 1.07s
261:	learn: 0.6110293	total: 379ms	remaining: 1.07s
262:	learn: 0.6077862	total: 380ms	remaining: 1.06s
263:	learn: 0.6036324	total: 381ms	remaining: 1.06s
264:	learn: 0.6013249	total: 383ms	remaining: 1.06s
265:	learn: 0.6007950	total: 385ms	remaining: 1.06s
266:	learn: 0.5973738	total: 386ms	remaining: 1.06s
267:	learn: 0.5969254	total: 388ms	remaining: 1.06s
268:	learn: 0.5929210	total: 390ms	remaining: 1.06s
269:	learn: 0.5907892	total: 391ms	remaining: 1.06s
270:	learn: 0.5884993	total: 393ms	remaining: 1.06s
271:	learn: 0.5847687	total: 395ms	remaining: 1.06s
272:	learn: 0.5817612	total: 396ms	remaining: 1.05s
273:	learn: 0.5791208	total: 397ms	remaining: 1.05s
274:	learn: 0.5755441	total: 399ms	remaining: 1.05s
275:	learn: 0.5710538	total: 400ms	remaining: 1.05s
276:	learn: 0.5697690	total: 402ms	remaining: 1.05s
277:	learn: 0.5664962	total: 403ms	remaining: 1.05s
278:	learn: 0.5630570	total: 405ms	remaining: 1.04s
279:	learn: 0.5626330	total: 406ms	remaining: 1.04s
280:	learn: 0.5609451	total: 408ms	remaining: 1.04s
281:	learn: 0.5577568	total: 410ms	remaining: 1.04s
282:	learn: 0.5541952	total: 411ms	remaining: 1.04s
283:	learn: 0.5529496	total: 412ms	remaining: 1.04s
284:	learn: 0.5497643	total: 414ms	remaining: 1.04s
285:	learn: 0.5486272	total: 415ms	remaining: 1.04s
286:	learn: 0.5470399	total: 417ms	remaining: 1.03s
287:	learn: 0.5456461	total: 418ms	remaining: 1.03s
288:	learn: 0.5420710	total: 420ms	remaining: 1.03s
289:	learn: 0.5381667	total: 422ms	remaining: 1.03s
290:	learn: 0.5364521	total: 424ms	remaining: 1.03s
291:	learn: 0.5342320	total: 425ms	remaining: 1.03s
292:	learn: 0.5328056	total: 427ms	remaining: 1.03s
293:	learn: 0.5291107	total: 428ms	remaining: 1.03s
294:	learn: 0.5276919	total: 430ms	remaining: 1.03s
295:	learn: 0.5245532	total: 431ms	remaining: 1.02s
296:	learn: 0.5214249	total: 432ms	remaining: 1.02s
297:	learn: 0.5197123	total: 434ms	remaining: 1.02s
298:	learn: 0.5165975	total: 437ms	remaining: 1.02s
299:	learn: 0.5153710	total: 438ms	remaining: 1.02s
300:	learn: 0.5122518	total: 440ms	remaining: 1.02s
301:	learn: 0.5093319	total: 441ms	remaining: 1.02s
302:	learn: 0.5073924	total: 442ms	remaining: 1.02s
303:	learn: 0.5068396	total: 444ms	remaining: 1.02s
304:	learn: 0.5048092	total: 445ms	remaining: 1.01s
305:	learn: 0.5023707	total: 446ms	remaining: 1.01s
306:	learn: 0.4995304	total: 448ms	remaining: 1.01s
307:	learn: 0.4983848	total: 450ms	remaining: 1.01s
308:	learn: 0.4972531	total: 452ms	remaining: 1.01s
309:	learn: 0.4961236	total: 453ms	remaining: 1.01s
310:	learn: 0.4956271	total: 455ms	remaining: 1.01s
311:	learn: 0.4939459	total: 456ms	remaining: 1s
312:	learn: 0.4909982	total: 457ms	remaining: 1s
313:	learn: 0.4883229	total: 459ms	remaining: 1s
314:	learn: 0.4855995	total: 460ms	remaining: 1s
315:	learn: 0.4831815	total: 462ms	remaining: 999ms
316:	learn: 0.4804358	total: 463ms	remaining: 998ms
317:	learn: 0.4788334	total: 465ms	remaining: 997ms
318:	learn: 0.4771601	total: 468ms	remaining: 999ms
319:	learn: 0.4751639	total: 469ms	remaining: 997ms
320:	learn: 0.4735261	total: 471ms	remaining: 996ms
321:	learn: 0.4705618	total: 472ms	remaining: 994ms
322:	learn: 0.4688444	total: 474ms	remaining: 993ms
323:	learn: 0.4678810	total: 475ms	remaining: 991ms
324:	learn: 0.4655850	total: 477ms	remaining: 990ms
325:	learn: 0.4627931	total: 478ms	remaining: 989ms
326:	learn: 0.4612033	total: 482ms	remaining: 992ms
327:	learn: 0.4603057	total: 484ms	remaining: 991ms
328:	learn: 0.4596715	total: 485ms	remaining: 990ms
329:	learn: 0.4586859	total: 487ms	remaining: 988ms
330:	learn: 0.4566974	total: 488ms	remaining: 987ms
331:	learn: 0.4558625	total: 489ms	remaining: 985ms
332:	learn: 0.4550501	total: 491ms	remaining: 983ms
333:	learn: 0.4531843	total: 492ms	remaining: 982ms
334:	learn: 0.4523702	total: 494ms	remaining: 981ms
335:	learn: 0.4505739	total: 497ms	remaining: 981ms
336:	learn: 0.4499672	total: 498ms	remaining: 980ms
337:	learn: 0.4487500	total: 500ms	remaining: 979ms
338:	learn: 0.4479549	total: 501ms	remaining: 978ms
339:	learn: 0.4462508	total: 503ms	remaining: 976ms
340:	learn: 0.4455277	total: 504ms	remaining: 975ms
341:	learn: 0.4437386	total: 506ms	remaining: 973ms
342:	learn: 0.4413116	total: 507ms	remaining: 972ms
343:	learn: 0.4395991	total: 509ms	remaining: 971ms
344:	learn: 0.4378712	total: 511ms	remaining: 970ms
345:	learn: 0.4368315	total: 513ms	remaining: 969ms
346:	learn: 0.4344889	total: 514ms	remaining: 968ms
347:	learn: 0.4317816	total: 516ms	remaining: 967ms
348:	learn: 0.4292545	total: 517ms	remaining: 965ms
349:	learn: 0.4280206	total: 519ms	remaining: 964ms
350:	learn: 0.4271604	total: 520ms	remaining: 962ms
351:	learn: 0.4251759	total: 522ms	remaining: 960ms
352:	learn: 0.4242819	total: 523ms	remaining: 959ms
353:	learn: 0.4228754	total: 525ms	remaining: 958ms
354:	learn: 0.4212251	total: 527ms	remaining: 958ms
355:	learn: 0.4206076	total: 529ms	remaining: 956ms
356:	learn: 0.4192041	total: 530ms	remaining: 955ms
357:	learn: 0.4185399	total: 531ms	remaining: 953ms
358:	learn: 0.4180685	total: 533ms	remaining: 951ms
359:	learn: 0.4174650	total: 534ms	remaining: 950ms
360:	learn: 0.4158915	total: 536ms	remaining: 948ms
361:	learn: 0.4150282	total: 537ms	remaining: 947ms
362:	learn: 0.4131592	total: 539ms	remaining: 945ms
363:	learn: 0.4116315	total: 540ms	remaining: 944ms
364:	learn: 0.4095813	total: 542ms	remaining: 943ms
365:	learn: 0.4077468	total: 544ms	remaining: 942ms
366:	learn: 0.4064015	total: 545ms	remaining: 941ms
367:	learn: 0.4048057	total: 547ms	remaining: 939ms
368:	learn: 0.4042311	total: 549ms	remaining: 939ms
369:	learn: 0.4034415	total: 551ms	remaining: 938ms
370:	learn: 0.4019834	total: 552ms	remaining: 936ms
371:	learn: 0.4009089	total: 553ms	remaining: 934ms
372:	learn: 0.3997893	total: 555ms	remaining: 933ms
373:	learn: 0.3990878	total: 557ms	remaining: 932ms
374:	learn: 0.3984144	total: 559ms	remaining: 932ms
375:	learn: 0.3966763	total: 561ms	remaining: 930ms
376:	learn: 0.3954582	total: 562ms	remaining: 928ms
377:	learn: 0.3943272	total: 563ms	remaining: 927ms
378:	learn: 0.3933708	total: 565ms	remaining: 925ms
379:	learn: 0.3920303	total: 566ms	remaining: 924ms
380:	learn: 0.3913560	total: 568ms	remaining: 923ms

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fitting SVR for C2RCC_rhow_9x9_depth_lt_1
Fitting KNN for C2RCC_rhow_9x9_depth_lt_1
Fitting LR for C2RCC_rhow_9x9_depth_lt_1
Fitting RF for C2RCC_rhow_9x9_depth_lt_1
Fitting CAT for C2RCC_rhow_9x9_depth_lt_1
Learning rate set to 0.033272
0:	learn: 3.4057636	total: 3.83ms	remaining: 3.83s
1:	learn: 3.3552724	total: 5.01ms	remaining: 2.5s
2:	learn: 3.2983597	total: 6.11ms	remaining: 2.03s
3:	learn: 3.2398766	total: 7.29ms	remaining: 1.81s
4:	learn: 3.1895580	total: 8.46ms	remaining: 1.68s
5:	learn: 3.1312495	total: 10.3ms	remaining: 1.71s
6:	learn: 3.0767321	total: 11.6ms	remaining: 1.65s
7:	learn: 3.0344829	total: 12.8ms	remaining: 1.58s
8:	learn: 2.9866247	total: 13.9ms	remaining: 1.53s
9:	learn: 2.9382096	total: 15ms	remaining: 1.49s
10:	learn: 2.8956289	total: 16.1ms	remaining: 1.45s
11:	learn: 2.8447732	total: 17.2ms	remaining: 1.42s
12:	learn: 2.7976980	total: 18.4ms	remaining: 1.4s
13:	learn: 2.7583911	total: 19.5ms	remaining: 1.37s
14:	learn: 2.7021547	total: 20.6ms	remaining: 1.35s
15:	learn: 2.6658751	total: 21.7ms	remaining: 1.33s
16:	learn: 2.6281038	total: 22.8ms	remaining: 1.32s
17:	learn: 2.5956983	total: 24ms	remaining: 1.31s
18:	learn: 2.5576782	total: 26ms	remaining: 1.34s
19:	learn: 2.5144425	total: 27.4ms	remaining: 1.34s
20:	learn: 2.4773067	total: 28.5ms	remaining: 1.33s
21:	learn: 2.4377804	total: 29.7ms	remaining: 1.32s
22:	learn: 2.3976879	total: 30.9ms	remaining: 1.31s
23:	learn: 2.3609992	total: 32ms	remaining: 1.3s
24:	learn: 2.3330198	total: 33.1ms	remaining: 1.29s
25:	learn: 2.3009393	total: 34.3ms	remaining: 1.28s
26:	learn: 2.2638209	total: 35.4ms	remaining: 1.28s
27:	learn: 2.2310508	total: 36.5ms	remaining: 1.27s
28:	learn: 2.2000495	total: 37.7ms	remaining: 1.26s
29:	learn: 2.1692093	total: 38.9ms	remaining: 1.26s
30:	learn: 2.1434948	total: 40ms	remaining: 1.25s
31:	learn: 2.1097594	total: 43ms	remaining: 1.3s
32:	learn: 2.0868123	total: 44.2ms	remaining: 1.29s
33:	learn: 2.0549393	total: 45.4ms	remaining: 1.29s
34:	learn: 2.0310649	total: 46.5ms	remaining: 1.28s
35:	learn: 2.0056851	total: 47.7ms	remaining: 1.28s
36:	learn: 1.9742989	total: 48.8ms	remaining: 1.27s
37:	learn: 1.9507184	total: 49.9ms	remaining: 1.26s
38:	learn: 1.9246411	total: 51ms	remaining: 1.26s
39:	learn: 1.8987620	total: 52.2ms	remaining: 1.25s
40:	learn: 1.8748364	total: 53.3ms	remaining: 1.25s
41:	learn: 1.8550067	total: 54.5ms	remaining: 1.24s
42:	learn: 1.8351008	total: 55.6ms	remaining: 1.24s
43:	learn: 1.8143763	total: 57.2ms	remaining: 1.24s
44:	learn: 1.7954882	total: 58.5ms	remaining: 1.24s
45:	learn: 1.7745831	total: 59.8ms	remaining: 1.24s
46:	learn: 1.7567022	total: 60.9ms	remaining: 1.24s
47:	learn: 1.7348707	total: 62.1ms	remaining: 1.23s
48:	learn: 1.7147424	total: 63.2ms	remaining: 1.23s
49:	learn: 1.6950645	total: 64.4ms	remaining: 1.22s
50:	learn: 1.6773389	total: 65.5ms	remaining: 1.22s
51:	learn: 1.6592052	total: 66.7ms	remaining: 1.22s
52:	learn: 1.6435852	total: 67.8ms	remaining: 1.21s
53:	learn: 1.6261460	total: 68.9ms	remaining: 1.21s
54:	learn: 1.6106425	total: 70.1ms	remaining: 1.2s
55:	learn: 1.5913913	total: 71.2ms	remaining: 1.2s
56:	learn: 1.5770780	total: 72.4ms	remaining: 1.2s
57:	learn: 1.5630837	total: 73.9ms	remaining: 1.2s
58:	learn: 1.5464403	total: 75.2ms	remaining: 1.2s
59:	learn: 1.5329922	total: 76.5ms	remaining: 1.2s
60:	learn: 1.5178333	total: 77.7ms	remaining: 1.2s
61:	learn: 1.5034848	total: 78.9ms	remaining: 1.19s
62:	learn: 1.4895921	total: 80.1ms	remaining: 1.19s
63:	learn: 1.4778398	total: 81.2ms	remaining: 1.19s
64:	learn: 1.4628005	total: 82.3ms	remaining: 1.18s
65:	learn: 1.4505541	total: 83.5ms	remaining: 1.18s
66:	learn: 1.4370332	total: 84.7ms	remaining: 1.18s
67:	learn: 1.4238365	total: 85.8ms	remaining: 1.18s
68:	learn: 1.4162481	total: 87ms	remaining: 1.17s
69:	learn: 1.3977974	total: 88.2ms	remaining: 1.17s
70:	learn: 1.3879141	total: 89.5ms	remaining: 1.17s
71:	learn: 1.3695107	total: 90.8ms	remaining: 1.17s
72:	learn: 1.3544900	total: 92ms	remaining: 1.17s
73:	learn: 1.3438767	total: 93.2ms	remaining: 1.17s
74:	learn: 1.3349341	total: 94.4ms	remaining: 1.16s
75:	learn: 1.3228144	total: 95.6ms	remaining: 1.16s
76:	learn: 1.3126908	total: 97.1ms	remaining: 1.16s
77:	learn: 1.2982752	total: 98.3ms	remaining: 1.16s
78:	learn: 1.2883085	total: 99.6ms	remaining: 1.16s
79:	learn: 1.2783473	total: 101ms	remaining: 1.16s
80:	learn: 1.2685843	total: 102ms	remaining: 1.16s
81:	learn: 1.2581956	total: 103ms	remaining: 1.16s
82:	learn: 1.2542623	total: 105ms	remaining: 1.16s
83:	learn: 1.2462297	total: 106ms	remaining: 1.16s
84:	learn: 1.2348704	total: 108ms	remaining: 1.16s
85:	learn: 1.2295001	total: 109ms	remaining: 1.16s
86:	learn: 1.2278249	total: 110ms	remaining: 1.16s
87:	learn: 1.2189711	total: 112ms	remaining: 1.16s
88:	learn: 1.2144842	total: 113ms	remaining: 1.16s
89:	learn: 1.2123326	total: 115ms	remaining: 1.16s
90:	learn: 1.2077532	total: 116ms	remaining: 1.16s
91:	learn: 1.2044215	total: 117ms	remaining: 1.16s
92:	learn: 1.2005559	total: 119ms	remaining: 1.16s
93:	learn: 1.1921780	total: 120ms	remaining: 1.16s
94:	learn: 1.1864434	total: 122ms	remaining: 1.16s
95:	learn: 1.1847389	total: 123ms	remaining: 1.16s
96:	learn: 1.1806764	total: 125ms	remaining: 1.16s
97:	learn: 1.1744012	total: 126ms	remaining: 1.16s
98:	learn: 1.1687109	total: 127ms	remaining: 1.16s
99:	learn: 1.1609966	total: 129ms	remaining: 1.16s
100:	learn: 1.1567797	total: 130ms	remaining: 1.16s
101:	learn: 1.1557861	total: 130ms	remaining: 1.15s
102:	learn: 1.1479505	total: 132ms	remaining: 1.15s
103:	learn: 1.1453016	total: 133ms	remaining: 1.15s
104:	learn: 1.1419590	total: 135ms	remaining: 1.15s
105:	learn: 1.1396166	total: 136ms	remaining: 1.15s
106:	learn: 1.1337299	total: 138ms	remaining: 1.15s
107:	learn: 1.1265328	total: 139ms	remaining: 1.15s
108:	learn: 1.1219996	total: 140ms	remaining: 1.15s
109:	learn: 1.1194401	total: 142ms	remaining: 1.15s
110:	learn: 1.1149648	total: 143ms	remaining: 1.14s
111:	learn: 1.1132457	total: 144ms	remaining: 1.14s
112:	learn: 1.1105221	total: 145ms	remaining: 1.14s
113:	learn: 1.1076321	total: 146ms	remaining: 1.14s
114:	learn: 1.1011795	total: 147ms	remaining: 1.14s
115:	learn: 1.0999242	total: 149ms	remaining: 1.13s
116:	learn: 1.0971585	total: 150ms	remaining: 1.13s
117:	learn: 1.0943889	total: 151ms	remaining: 1.13s
118:	learn: 1.0915290	total: 152ms	remaining: 1.13s
119:	learn: 1.0900211	total: 154ms	remaining: 1.13s
120:	learn: 1.0878505	total: 155ms	remaining: 1.12s
121:	learn: 1.0832476	total: 156ms	remaining: 1.12s
122:	learn: 1.0767155	total: 157ms	remaining: 1.12s
123:	learn: 1.0752213	total: 158ms	remaining: 1.12s
124:	learn: 1.0692372	total: 160ms	remaining: 1.12s
125:	learn: 1.0684920	total: 160ms	remaining: 1.11s
126:	learn: 1.0604309	total: 161ms	remaining: 1.11s
127:	learn: 1.0541985	total: 163ms	remaining: 1.11s
128:	learn: 1.0491128	total: 164ms	remaining: 1.11s
129:	learn: 1.0435741	total: 165ms	remaining: 1.1s
130:	learn: 1.0419699	total: 166ms	remaining: 1.1s
131:	learn: 1.0360652	total: 168ms	remaining: 1.1s
132:	learn: 1.0334150	total: 169ms	remaining: 1.1s
133:	learn: 1.0280491	total: 170ms	remaining: 1.1s
134:	learn: 1.0235101	total: 172ms	remaining: 1.1s
135:	learn: 1.0191039	total: 173ms	remaining: 1.1s
136:	learn: 1.0144214	total: 174ms	remaining: 1.1s
137:	learn: 1.0119743	total: 176ms	remaining: 1.1s
138:	learn: 1.0039737	total: 177ms	remaining: 1.1s
139:	learn: 1.0014634	total: 178ms	remaining: 1.09s
140:	learn: 0.9997541	total: 180ms	remaining: 1.09s
141:	learn: 0.9977805	total: 182ms	remaining: 1.1s
142:	learn: 0.9943200	total: 184ms	remaining: 1.1s
143:	learn: 0.9902195	total: 186ms	remaining: 1.1s
144:	learn: 0.9880899	total: 187ms	remaining: 1.1s
145:	learn: 0.9851623	total: 189ms	remaining: 1.1s
146:	learn: 0.9837848	total: 190ms	remaining: 1.1s
147:	learn: 0.9790284	total: 192ms	remaining: 1.1s
148:	learn: 0.9750379	total: 193ms	remaining: 1.1s
149:	learn: 0.9734864	total: 194ms	remaining: 1.1s
150:	learn: 0.9714286	total: 196ms	remaining: 1.1s
151:	learn: 0.9695025	total: 197ms	remaining: 1.1s
152:	learn: 0.9648872	total: 199ms	remaining: 1.1s
153:	learn: 0.9630985	total: 200ms	remaining: 1.1s
154:	learn: 0.9608723	total: 201ms	remaining: 1.1s
155:	learn: 0.9593598	total: 203ms	remaining: 1.1s
156:	learn: 0.9571157	total: 205ms	remaining: 1.1s
157:	learn: 0.9564751	total: 207ms	remaining: 1.1s
158:	learn: 0.9546263	total: 209ms	remaining: 1.1s
159:	learn: 0.9520013	total: 210ms	remaining: 1.1s
160:	learn: 0.9501900	total: 211ms	remaining: 1.1s
161:	learn: 0.9484551	total: 213ms	remaining: 1.1s
162:	learn: 0.9441363	total: 214ms	remaining: 1.1s
163:	learn: 0.9421301	total: 215ms	remaining: 1.1s
164:	learn: 0.9387135	total: 216ms	remaining: 1.09s
165:	learn: 0.9336577	total: 218ms	remaining: 1.09s
166:	learn: 0.9323765	total: 219ms	remaining: 1.09s
167:	learn: 0.9283444	total: 220ms	remaining: 1.09s
168:	learn: 0.9261670	total: 222ms	remaining: 1.09s
169:	learn: 0.9245702	total: 223ms	remaining: 1.09s
170:	learn: 0.9211981	total: 224ms	remaining: 1.09s
171:	learn: 0.9200073	total: 225ms	remaining: 1.08s
172:	learn: 0.9186663	total: 226ms	remaining: 1.08s
173:	learn: 0.9173584	total: 228ms	remaining: 1.08s
174:	learn: 0.9133587	total: 229ms	remaining: 1.08s
175:	learn: 0.9114962	total: 230ms	remaining: 1.08s
176:	learn: 0.9083985	total: 232ms	remaining: 1.08s
177:	learn: 0.9065195	total: 233ms	remaining: 1.07s
178:	learn: 0.9051639	total: 234ms	remaining: 1.07s
179:	learn: 0.9037605	total: 235ms	remaining: 1.07s
180:	learn: 0.9020379	total: 237ms	remaining: 1.07s
181:	learn: 0.8974364	total: 238ms	remaining: 1.07s
182:	learn: 0.8964404	total: 239ms	remaining: 1.07s
183:	learn: 0.8931208	total: 240ms	remaining: 1.07s
184:	learn: 0.8917802	total: 242ms	remaining: 1.06s
185:	learn: 0.8904791	total: 243ms	remaining: 1.06s
186:	learn: 0.8886495	total: 245ms	remaining: 1.06s
187:	learn: 0.8874408	total: 246ms	remaining: 1.06s
188:	learn: 0.8862065	total: 248ms	remaining: 1.06s
189:	learn: 0.8790836	total: 249ms	remaining: 1.06s
190:	learn: 0.8776166	total: 250ms	remaining: 1.06s
191:	learn: 0.8764674	total: 252ms	remaining: 1.06s
192:	learn: 0.8746503	total: 253ms	remaining: 1.06s
193:	learn: 0.8728482	total: 254ms	remaining: 1.05s
194:	learn: 0.8660781	total: 255ms	remaining: 1.05s
195:	learn: 0.8648571	total: 256ms	remaining: 1.05s
196:	learn: 0.8599917	total: 258ms	remaining: 1.05s
197:	learn: 0.8589550	total: 259ms	remaining: 1.05s
198:	learn: 0.8577500	total: 260ms	remaining: 1.05s
199:	learn: 0.8567752	total: 261ms	remaining: 1.04s
200:	learn: 0.8558020	total: 263ms	remaining: 1.05s
201:	learn: 0.8546945	total: 264ms	remaining: 1.04s
202:	learn: 0.8535680	total: 265ms	remaining: 1.04s
203:	learn: 0.8474720	total: 266ms	remaining: 1.04s
204:	learn: 0.8465680	total: 268ms	remaining: 1.04s
205:	learn: 0.8415699	total: 269ms	remaining: 1.03s
206:	learn: 0.8376550	total: 269ms	remaining: 1.03s
207:	learn: 0.8367404	total: 270ms	remaining: 1.03s
208:	learn: 0.8339555	total: 272ms	remaining: 1.03s
209:	learn: 0.8331071	total: 273ms	remaining: 1.03s
210:	learn: 0.8315337	total: 274ms	remaining: 1.02s
211:	learn: 0.8306860	total: 276ms	remaining: 1.02s
212:	learn: 0.8294990	total: 279ms	remaining: 1.03s
213:	learn: 0.8287052	total: 280ms	remaining: 1.03s
214:	learn: 0.8231528	total: 281ms	remaining: 1.03s
215:	learn: 0.8214444	total: 283ms	remaining: 1.03s
216:	learn: 0.8186790	total: 284ms	remaining: 1.02s
217:	learn: 0.8175211	total: 285ms	remaining: 1.02s
218:	learn: 0.8161788	total: 286ms	remaining: 1.02s
219:	learn: 0.8146894	total: 287ms	remaining: 1.02s
220:	learn: 0.8118519	total: 288ms	remaining: 1.01s
221:	learn: 0.8103418	total: 290ms	remaining: 1.01s
222:	learn: 0.8089136	total: 292ms	remaining: 1.02s
223:	learn: 0.8077973	total: 295ms	remaining: 1.02s
224:	learn: 0.8020610	total: 296ms	remaining: 1.02s
225:	learn: 0.8013666	total: 297ms	remaining: 1.02s
226:	learn: 0.7966362	total: 298ms	remaining: 1.01s
227:	learn: 0.7958933	total: 299ms	remaining: 1.01s
228:	learn: 0.7908828	total: 300ms	remaining: 1.01s
229:	learn: 0.7892512	total: 301ms	remaining: 1.01s
230:	learn: 0.7885784	total: 302ms	remaining: 1s
231:	learn: 0.7876328	total: 303ms	remaining: 1s
232:	learn: 0.7859533	total: 304ms	remaining: 1s
233:	learn: 0.7810727	total: 306ms	remaining: 1s
234:	learn: 0.7772808	total: 307ms	remaining: 999ms
235:	learn: 0.7767205	total: 309ms	remaining: 1000ms
236:	learn: 0.7755585	total: 310ms	remaining: 1000ms
237:	learn: 0.7704549	total: 312ms	remaining: 999ms
238:	learn: 0.7691268	total: 313ms	remaining: 998ms
239:	learn: 0.7685586	total: 315ms	remaining: 996ms
240:	learn: 0.7679542	total: 316ms	remaining: 995ms
241:	learn: 0.7631711	total: 317ms	remaining: 994ms
242:	learn: 0.7587263	total: 319ms	remaining: 993ms
243:	learn: 0.7573571	total: 320ms	remaining: 992ms
244:	learn: 0.7545749	total: 321ms	remaining: 990ms
245:	learn: 0.7491310	total: 324ms	remaining: 992ms
246:	learn: 0.7480221	total: 325ms	remaining: 991ms
247:	learn: 0.7438299	total: 327ms	remaining: 990ms
248:	learn: 0.7427782	total: 328ms	remaining: 989ms
249:	learn: 0.7378665	total: 329ms	remaining: 987ms
250:	learn: 0.7327275	total: 330ms	remaining: 986ms
251:	learn: 0.7301462	total: 332ms	remaining: 985ms
252:	learn: 0.7272429	total: 333ms	remaining: 984ms
253:	learn: 0.7243183	total: 334ms	remaining: 982ms
254:	learn: 0.7202861	total: 336ms	remaining: 981ms
255:	learn: 0.7164336	total: 337ms	remaining: 980ms
256:	learn: 0.7135245	total: 338ms	remaining: 979ms
257:	learn: 0.7100992	total: 340ms	remaining: 978ms
258:	learn: 0.7095003	total: 341ms	remaining: 977ms
259:	learn: 0.7076811	total: 343ms	remaining: 975ms
260:	learn: 0.7050582	total: 344ms	remaining: 974ms
261:	learn: 0.7026119	total: 345ms	remaining: 973ms
262:	learn: 0.7020895	total: 347ms	remaining: 972ms
263:	learn: 0.6983596	total: 348ms	remaining: 970ms
264:	learn: 0.6947806	total: 349ms	remaining: 969ms
265:	learn: 0.6933424	total: 351ms	remaining: 968ms
266:	learn: 0.6891334	total: 352ms	remaining: 966ms
267:	learn: 0.6863557	total: 353ms	remaining: 965ms
268:	learn: 0.6833746	total: 355ms	remaining: 964ms
269:	learn: 0.6793881	total: 356ms	remaining: 964ms
270:	learn: 0.6787647	total: 358ms	remaining: 962ms
271:	learn: 0.6765960	total: 359ms	remaining: 961ms
272:	learn: 0.6723624	total: 360ms	remaining: 960ms
273:	learn: 0.6716665	total: 362ms	remaining: 959ms
274:	learn: 0.6687107	total: 363ms	remaining: 957ms
275:	learn: 0.6663001	total: 364ms	remaining: 956ms
276:	learn: 0.6630177	total: 366ms	remaining: 954ms
277:	learn: 0.6615472	total: 367ms	remaining: 953ms
278:	learn: 0.6595935	total: 368ms	remaining: 952ms
279:	learn: 0.6567483	total: 370ms	remaining: 951ms
280:	learn: 0.6565041	total: 371ms	remaining: 949ms
281:	learn: 0.6552352	total: 373ms	remaining: 951ms
282:	learn: 0.6500083	total: 376ms	remaining: 952ms
283:	learn: 0.6472677	total: 377ms	remaining: 951ms
284:	learn: 0.6450705	total: 378ms	remaining: 949ms
285:	learn: 0.6424066	total: 380ms	remaining: 948ms
286:	learn: 0.6408534	total: 381ms	remaining: 946ms
287:	learn: 0.6400846	total: 382ms	remaining: 945ms
288:	learn: 0.6370435	total: 384ms	remaining: 944ms
289:	learn: 0.6339401	total: 386ms	remaining: 944ms
290:	learn: 0.6313275	total: 387ms	remaining: 944ms
291:	learn: 0.6282087	total: 389ms	remaining: 943ms
292:	learn: 0.6259035	total: 390ms	remaining: 941ms
293:	learn: 0.6236845	total: 391ms	remaining: 940ms
294:	learn: 0.6223904	total: 393ms	remaining: 938ms
295:	learn: 0.6198555	total: 394ms	remaining: 937ms
296:	learn: 0.6193729	total: 395ms	remaining: 935ms
297:	learn: 0.6176372	total: 396ms	remaining: 933ms
298:	learn: 0.6171717	total: 397ms	remaining: 932ms
299:	learn: 0.6164596	total: 399ms	remaining: 930ms
300:	learn: 0.6137258	total: 400ms	remaining: 929ms
301:	learn: 0.6103146	total: 401ms	remaining: 928ms
302:	learn: 0.6096234	total: 403ms	remaining: 926ms
303:	learn: 0.6078736	total: 404ms	remaining: 925ms
304:	learn: 0.6053613	total: 405ms	remaining: 923ms
305:	learn: 0.6048537	total: 406ms	remaining: 922ms
306:	learn: 0.6027559	total: 408ms	remaining: 920ms
307:	learn: 0.5986593	total: 409ms	remaining: 919ms
308:	learn: 0.5961140	total: 410ms	remaining: 917ms
309:	learn: 0.5942039	total: 411ms	remaining: 916ms
310:	learn: 0.5922151	total: 412ms	remaining: 914ms
311:	learn: 0.5917369	total: 414ms	remaining: 912ms
312:	learn: 0.5901350	total: 415ms	remaining: 911ms
313:	learn: 0.5878235	total: 416ms	remaining: 910ms
314:	learn: 0.5841167	total: 418ms	remaining: 908ms
315:	learn: 0.5814741	total: 419ms	remaining: 907ms
316:	learn: 0.5792123	total: 420ms	remaining: 905ms
317:	learn: 0.5750843	total: 421ms	remaining: 903ms
318:	learn: 0.5728293	total: 422ms	remaining: 902ms
319:	learn: 0.5710931	total: 424ms	remaining: 900ms
320:	learn: 0.5687806	total: 425ms	remaining: 898ms
321:	learn: 0.5670631	total: 426ms	remaining: 897ms
322:	learn: 0.5648081	total: 427ms	remaining: 895ms
323:	learn: 0.5637221	total: 428ms	remaining: 893ms
324:	learn: 0.5630641	total: 429ms	remaining: 892ms
325:	learn: 0.5613476	total: 431ms	remaining: 891ms
326:	learn: 0.5589913	total: 432ms	remaining: 890ms
327:	learn: 0.5555342	total: 434ms	remaining: 889ms
328:	learn: 0.5534589	total: 435ms	remaining: 887ms
329:	learn: 0.5519789	total: 436ms	remaining: 885ms
330:	learn: 0.5502930	total: 437ms	remaining: 884ms
331:	learn: 0.5493992	total: 438ms	remaining: 882ms
332:	learn: 0.5472852	total: 439ms	remaining: 880ms
333:	learn: 0.5449602	total: 441ms	remaining: 879ms
334:	learn: 0.5435443	total: 442ms	remaining: 878ms
335:	learn: 0.5419371	total: 443ms	remaining: 876ms
336:	learn: 0.5383706	total: 444ms	remaining: 874ms
337:	learn: 0.5366147	total: 446ms	remaining: 873ms
338:	learn: 0.5341645	total: 447ms	remaining: 872ms
339:	learn: 0.5338750	total: 449ms	remaining: 871ms
340:	learn: 0.5322580	total: 450ms	remaining: 870ms
341:	learn: 0.5311722	total: 451ms	remaining: 868ms
342:	learn: 0.5297412	total: 452ms	remaining: 867ms
343:	learn: 0.5266487	total: 454ms	remaining: 865ms
344:	learn: 0.5251789	total: 455ms	remaining: 863ms
345:	learn: 0.5247672	total: 456ms	remaining: 862ms
346:	learn: 0.5228913	total: 457ms	remaining: 860ms
347:	learn: 0.5208932	total: 458ms	remaining: 859ms
348:	learn: 0.5189350	total: 460ms	remaining: 857ms
349:	learn: 0.5176039	total: 461ms	remaining: 856ms
350:	learn: 0.5167322	total: 462ms	remaining: 855ms
351:	learn: 0.5132442	total: 464ms	remaining: 854ms
352:	learn: 0.5106407	total: 465ms	remaining: 853ms
353:	learn: 0.5085615	total: 467ms	remaining: 852ms
354:	learn: 0.5064490	total: 468ms	remaining: 850ms
355:	learn: 0.5055822	total: 469ms	remaining: 849ms
356:	learn: 0.5044656	total: 470ms	remaining: 847ms
357:	learn: 0.5029426	total: 472ms	remaining: 846ms
358:	learn: 0.5017151	total: 473ms	remaining: 844ms
359:	learn: 0.4999504	total: 474ms	remaining: 843ms
360:	learn: 0.4980212	total: 475ms	remaining: 841ms
361:	learn: 0.4958560	total: 477ms	remaining: 840ms
362:	learn: 0.4946560	total: 479ms	remaining: 840ms
363:	learn: 0.4938001	total: 480ms	remaining: 839ms
364:	learn: 0.4908940	total: 482ms	remaining: 838ms
365:	learn: 0.4884531	total: 483ms	remaining: 836ms
366:	learn: 0.4877990	total: 484ms	remaining: 835ms
367:	learn: 0.4859710	total: 485ms	remaining: 833ms
368:	learn: 0.4842472	total: 486ms	remaining: 832ms
369:	learn: 0.4825613	total: 487ms	remaining: 830ms
370:	learn: 0.4808878	total: 489ms	remaining: 828ms
371:	learn: 0.4798156	total: 490ms	remaining: 827ms
372:	learn: 0.4793410	total: 491ms	remaining: 825ms
373:	learn: 0.4779628	total: 492ms	remaining: 824ms
374:	learn: 0.4768018	total: 495ms	remaining: 824ms
375:	learn: 0.4750215	total: 496ms	remaining: 824ms
376:	learn: 0.4736648	total: 498ms	remaining: 822ms
377:	learn: 0.4718472	total: 499ms	remaining: 821ms
378:	learn: 0.4707504	total: 500ms	remaining: 819ms
379:	learn: 0.4705495	total: 501ms	remaining: 818ms
380:	learn: 0.4695582	total: 502ms	remaining: 816ms
381:	learn: 0.4667744	total: 504ms	remaining: 815ms

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fitting SVR for C2X-Complex_rhown_5x5_depth_lt_1
Fitting KNN for C2X-Complex_rhown_5x5_depth_lt_1
Fitting LR for C2X-Complex_rhown_5x5_depth_lt_1
Fitting RF for C2X-Complex_rhown_5x5_depth_lt_1
Fitting CAT for C2X-Complex_rhown_5x5_depth_lt_1
Learning rate set to 0.033272
0:	learn: 3.4091918	total: 2.13ms	remaining: 2.12s
1:	learn: 3.3423821	total: 3.24ms	remaining: 1.61s
2:	learn: 3.2898448	total: 4.33ms	remaining: 1.44s
3:	learn: 3.2311525	total: 5.42ms	remaining: 1.35s
4:	learn: 3.1824363	total: 6.55ms	remaining: 1.3s
5:	learn: 3.1349529	total: 7.63ms	remaining: 1.26s
6:	learn: 3.0878222	total: 8.7ms	remaining: 1.23s
7:	learn: 3.0399445	total: 9.76ms	remaining: 1.21s
8:	learn: 2.9863857	total: 10.9ms	remaining: 1.2s
9:	learn: 2.9403053	total: 12ms	remaining: 1.18s
10:	learn: 2.8902229	total: 13.1ms	remaining: 1.17s
11:	learn: 2.8484656	total: 14.2ms	remaining: 1.17s
12:	learn: 2.7971668	total: 15.5ms	remaining: 1.17s
13:	learn: 2.7568069	total: 16.7ms	remaining: 1.18s
14:	learn: 2.7116452	total: 18ms	remaining: 1.18s
15:	learn: 2.6788639	total: 19.1ms	remaining: 1.18s
16:	learn: 2.6344592	total: 20.2ms	remaining: 1.17s
17:	learn: 2.5964805	total: 21.4ms	remaining: 1.17s
18:	learn: 2.5627825	total: 22.6ms	remaining: 1.16s
19:	learn: 2.5245352	total: 23.7ms	remaining: 1.16s
20:	learn: 2.4826846	total: 24.8ms	remaining: 1.16s
21:	learn: 2.4450862	total: 25.9ms	remaining: 1.15s
22:	learn: 2.4115619	total: 27ms	remaining: 1.15s
23:	learn: 2.3798207	total: 28.2ms	remaining: 1.15s
24:	learn: 2.3506951	total: 29.4ms	remaining: 1.15s
25:	learn: 2.3186379	total: 30.7ms	remaining: 1.15s
26:	learn: 2.2819798	total: 31.9ms	remaining: 1.15s
27:	learn: 2.2510975	total: 33ms	remaining: 1.15s
28:	learn: 2.2144618	total: 34.1ms	remaining: 1.14s
29:	learn: 2.1833956	total: 35.2ms	remaining: 1.14s
30:	learn: 2.1543107	total: 36.4ms	remaining: 1.14s
31:	learn: 2.1219071	total: 37.5ms	remaining: 1.13s
32:	learn: 2.0931737	total: 38.5ms	remaining: 1.13s
33:	learn: 2.0654223	total: 39.6ms	remaining: 1.13s
34:	learn: 2.0417275	total: 40.7ms	remaining: 1.12s
35:	learn: 2.0201453	total: 41.7ms	remaining: 1.12s
36:	learn: 1.9984695	total: 42.8ms	remaining: 1.11s
37:	learn: 1.9684655	total: 43.9ms	remaining: 1.11s
38:	learn: 1.9469067	total: 45.1ms	remaining: 1.11s
39:	learn: 1.9204711	total: 46.3ms	remaining: 1.11s
40:	learn: 1.8979917	total: 47.7ms	remaining: 1.12s
41:	learn: 1.8797685	total: 48.9ms	remaining: 1.11s
42:	learn: 1.8571858	total: 50ms	remaining: 1.11s
43:	learn: 1.8379170	total: 51.2ms	remaining: 1.11s
44:	learn: 1.8198076	total: 52.2ms	remaining: 1.11s
45:	learn: 1.7994680	total: 53.3ms	remaining: 1.1s
46:	learn: 1.7773221	total: 54.4ms	remaining: 1.1s
47:	learn: 1.7589456	total: 55.5ms	remaining: 1.1s
48:	learn: 1.7329443	total: 56.5ms	remaining: 1.1s
49:	learn: 1.7109929	total: 57.6ms	remaining: 1.09s
50:	learn: 1.6960417	total: 58.7ms	remaining: 1.09s
51:	learn: 1.6754108	total: 59.7ms	remaining: 1.09s
52:	learn: 1.6562764	total: 60.9ms	remaining: 1.09s
53:	learn: 1.6334292	total: 62.5ms	remaining: 1.09s
54:	learn: 1.6117087	total: 63.6ms	remaining: 1.09s
55:	learn: 1.5976104	total: 64.7ms	remaining: 1.09s
56:	learn: 1.5786778	total: 65.9ms	remaining: 1.09s
57:	learn: 1.5622324	total: 67ms	remaining: 1.09s
58:	learn: 1.5490933	total: 68ms	remaining: 1.08s
59:	learn: 1.5361518	total: 69.1ms	remaining: 1.08s
60:	learn: 1.5170896	total: 70.2ms	remaining: 1.08s
61:	learn: 1.5031082	total: 71.2ms	remaining: 1.08s
62:	learn: 1.4856232	total: 72.3ms	remaining: 1.07s
63:	learn: 1.4715030	total: 73.6ms	remaining: 1.08s
64:	learn: 1.4589451	total: 74.7ms	remaining: 1.07s
65:	learn: 1.4398486	total: 75.8ms	remaining: 1.07s
66:	learn: 1.4270659	total: 77.1ms	remaining: 1.07s
67:	learn: 1.4139350	total: 78.3ms	remaining: 1.07s
68:	learn: 1.4035470	total: 79.5ms	remaining: 1.07s
69:	learn: 1.3973861	total: 80.6ms	remaining: 1.07s
70:	learn: 1.3855167	total: 81.8ms	remaining: 1.07s
71:	learn: 1.3704390	total: 82.9ms	remaining: 1.07s
72:	learn: 1.3581698	total: 83.9ms	remaining: 1.06s
73:	learn: 1.3408232	total: 85ms	remaining: 1.06s
74:	learn: 1.3278302	total: 86ms	remaining: 1.06s
75:	learn: 1.3102634	total: 87.1ms	remaining: 1.06s
76:	learn: 1.2970477	total: 88.2ms	remaining: 1.06s
77:	learn: 1.2852055	total: 89.2ms	remaining: 1.05s
78:	learn: 1.2759905	total: 90.3ms	remaining: 1.05s
79:	learn: 1.2600928	total: 91.4ms	remaining: 1.05s
80:	learn: 1.2504328	total: 93.1ms	remaining: 1.06s
81:	learn: 1.2441644	total: 94.3ms	remaining: 1.05s
82:	learn: 1.2392181	total: 95.4ms	remaining: 1.05s
83:	learn: 1.2284098	total: 96.7ms	remaining: 1.05s
84:	learn: 1.2242322	total: 97.8ms	remaining: 1.05s
85:	learn: 1.2125660	total: 98.9ms	remaining: 1.05s
86:	learn: 1.2009676	total: 99.9ms	remaining: 1.05s
87:	learn: 1.1909499	total: 101ms	remaining: 1.05s
88:	learn: 1.1799804	total: 102ms	remaining: 1.04s
89:	learn: 1.1748095	total: 103ms	remaining: 1.04s
90:	learn: 1.1708239	total: 104ms	remaining: 1.04s
91:	learn: 1.1625168	total: 105ms	remaining: 1.04s
92:	learn: 1.1494870	total: 106ms	remaining: 1.04s
93:	learn: 1.1414763	total: 108ms	remaining: 1.04s
94:	learn: 1.1389661	total: 110ms	remaining: 1.04s
95:	learn: 1.1238998	total: 111ms	remaining: 1.04s
96:	learn: 1.1170660	total: 112ms	remaining: 1.04s
97:	learn: 1.1063266	total: 113ms	remaining: 1.04s
98:	learn: 1.1027837	total: 114ms	remaining: 1.04s
99:	learn: 1.0878946	total: 115ms	remaining: 1.04s
100:	learn: 1.0779735	total: 117ms	remaining: 1.04s
101:	learn: 1.0693252	total: 118ms	remaining: 1.04s
102:	learn: 1.0593512	total: 119ms	remaining: 1.03s
103:	learn: 1.0555377	total: 120ms	remaining: 1.03s
104:	learn: 1.0488824	total: 121ms	remaining: 1.03s
105:	learn: 1.0430715	total: 122ms	remaining: 1.03s
106:	learn: 1.0371770	total: 123ms	remaining: 1.03s
107:	learn: 1.0310448	total: 125ms	remaining: 1.03s
108:	learn: 1.0220651	total: 127ms	remaining: 1.03s
109:	learn: 1.0179115	total: 128ms	remaining: 1.03s
110:	learn: 1.0114803	total: 129ms	remaining: 1.03s
111:	learn: 1.0090062	total: 131ms	remaining: 1.03s
112:	learn: 0.9981298	total: 132ms	remaining: 1.03s
113:	learn: 0.9923348	total: 133ms	remaining: 1.03s
114:	learn: 0.9873228	total: 134ms	remaining: 1.03s
115:	learn: 0.9795333	total: 135ms	remaining: 1.03s
116:	learn: 0.9759566	total: 137ms	remaining: 1.03s
117:	learn: 0.9695594	total: 138ms	remaining: 1.03s
118:	learn: 0.9637575	total: 139ms	remaining: 1.03s
119:	learn: 0.9612184	total: 141ms	remaining: 1.03s
120:	learn: 0.9549972	total: 142ms	remaining: 1.03s
121:	learn: 0.9479860	total: 144ms	remaining: 1.03s
122:	learn: 0.9405155	total: 145ms	remaining: 1.03s
123:	learn: 0.9379516	total: 146ms	remaining: 1.03s
124:	learn: 0.9332114	total: 147ms	remaining: 1.03s
125:	learn: 0.9267831	total: 148ms	remaining: 1.03s
126:	learn: 0.9250227	total: 150ms	remaining: 1.03s
127:	learn: 0.9212846	total: 151ms	remaining: 1.03s
128:	learn: 0.9189697	total: 153ms	remaining: 1.03s
129:	learn: 0.9163510	total: 155ms	remaining: 1.04s
130:	learn: 0.9097691	total: 156ms	remaining: 1.04s
131:	learn: 0.9079396	total: 158ms	remaining: 1.04s
132:	learn: 0.9019959	total: 159ms	remaining: 1.04s
133:	learn: 0.9002041	total: 160ms	remaining: 1.03s
134:	learn: 0.8982239	total: 161ms	remaining: 1.03s
135:	learn: 0.8939122	total: 162ms	remaining: 1.03s
136:	learn: 0.8892289	total: 163ms	remaining: 1.03s
137:	learn: 0.8864105	total: 165ms	remaining: 1.03s
138:	learn: 0.8817004	total: 166ms	remaining: 1.02s
139:	learn: 0.8806769	total: 167ms	remaining: 1.02s
140:	learn: 0.8777151	total: 168ms	remaining: 1.02s
141:	learn: 0.8754331	total: 170ms	remaining: 1.02s
142:	learn: 0.8692063	total: 171ms	remaining: 1.02s
143:	learn: 0.8625761	total: 172ms	remaining: 1.02s
144:	learn: 0.8605852	total: 173ms	remaining: 1.02s
145:	learn: 0.8560790	total: 174ms	remaining: 1.02s
146:	learn: 0.8511888	total: 176ms	remaining: 1.02s
147:	learn: 0.8470727	total: 177ms	remaining: 1.02s
148:	learn: 0.8426724	total: 179ms	remaining: 1.02s
149:	learn: 0.8412343	total: 180ms	remaining: 1.02s
150:	learn: 0.8369316	total: 181ms	remaining: 1.02s
151:	learn: 0.8296063	total: 183ms	remaining: 1.02s
152:	learn: 0.8245718	total: 184ms	remaining: 1.02s
153:	learn: 0.8209067	total: 185ms	remaining: 1.02s
154:	learn: 0.8172084	total: 187ms	remaining: 1.02s
155:	learn: 0.8127251	total: 188ms	remaining: 1.02s
156:	learn: 0.8092885	total: 189ms	remaining: 1.01s
157:	learn: 0.8047576	total: 191ms	remaining: 1.01s
158:	learn: 0.8032656	total: 194ms	remaining: 1.02s
159:	learn: 0.8002235	total: 197ms	remaining: 1.03s
160:	learn: 0.7964036	total: 199ms	remaining: 1.04s
161:	learn: 0.7901561	total: 201ms	remaining: 1.04s
162:	learn: 0.7848009	total: 203ms	remaining: 1.04s
163:	learn: 0.7802364	total: 204ms	remaining: 1.04s
164:	learn: 0.7780069	total: 205ms	remaining: 1.04s
165:	learn: 0.7732801	total: 206ms	remaining: 1.04s
166:	learn: 0.7694216	total: 210ms	remaining: 1.04s
167:	learn: 0.7628441	total: 213ms	remaining: 1.05s
168:	learn: 0.7581501	total: 216ms	remaining: 1.06s
169:	learn: 0.7537282	total: 218ms	remaining: 1.06s
170:	learn: 0.7482471	total: 220ms	remaining: 1.06s
171:	learn: 0.7441953	total: 221ms	remaining: 1.06s
172:	learn: 0.7425815	total: 222ms	remaining: 1.06s
173:	learn: 0.7369031	total: 223ms	remaining: 1.06s
174:	learn: 0.7317544	total: 224ms	remaining: 1.06s
175:	learn: 0.7274210	total: 226ms	remaining: 1.06s
176:	learn: 0.7250036	total: 227ms	remaining: 1.05s
177:	learn: 0.7222253	total: 228ms	remaining: 1.05s
178:	learn: 0.7188439	total: 231ms	remaining: 1.06s
179:	learn: 0.7163686	total: 232ms	remaining: 1.06s
180:	learn: 0.7122438	total: 234ms	remaining: 1.06s
181:	learn: 0.7082620	total: 235ms	remaining: 1.06s
182:	learn: 0.7050293	total: 236ms	remaining: 1.05s
183:	learn: 0.7014040	total: 237ms	remaining: 1.05s
184:	learn: 0.6980046	total: 239ms	remaining: 1.05s
185:	learn: 0.6942712	total: 240ms	remaining: 1.05s
186:	learn: 0.6905099	total: 241ms	remaining: 1.05s
187:	learn: 0.6871663	total: 242ms	remaining: 1.05s
188:	learn: 0.6833942	total: 245ms	remaining: 1.05s
189:	learn: 0.6798293	total: 247ms	remaining: 1.05s
190:	learn: 0.6767360	total: 249ms	remaining: 1.05s
191:	learn: 0.6736548	total: 250ms	remaining: 1.05s
192:	learn: 0.6696721	total: 251ms	remaining: 1.05s
193:	learn: 0.6663627	total: 252ms	remaining: 1.05s
194:	learn: 0.6636168	total: 253ms	remaining: 1.04s
195:	learn: 0.6621828	total: 255ms	remaining: 1.04s
196:	learn: 0.6589035	total: 256ms	remaining: 1.04s
197:	learn: 0.6556363	total: 257ms	remaining: 1.04s
198:	learn: 0.6541678	total: 259ms	remaining: 1.04s
199:	learn: 0.6506645	total: 260ms	remaining: 1.04s
200:	learn: 0.6485775	total: 262ms	remaining: 1.04s
201:	learn: 0.6453620	total: 263ms	remaining: 1.04s
202:	learn: 0.6424281	total: 265ms	remaining: 1.04s
203:	learn: 0.6397191	total: 266ms	remaining: 1.04s
204:	learn: 0.6377016	total: 267ms	remaining: 1.03s
205:	learn: 0.6345564	total: 268ms	remaining: 1.03s
206:	learn: 0.6315884	total: 269ms	remaining: 1.03s
207:	learn: 0.6282360	total: 270ms	remaining: 1.03s
208:	learn: 0.6255455	total: 272ms	remaining: 1.03s
209:	learn: 0.6233133	total: 273ms	remaining: 1.03s
210:	learn: 0.6207719	total: 275ms	remaining: 1.03s
211:	learn: 0.6177162	total: 276ms	remaining: 1.02s
212:	learn: 0.6153457	total: 277ms	remaining: 1.02s
213:	learn: 0.6126549	total: 278ms	remaining: 1.02s
214:	learn: 0.6108441	total: 279ms	remaining: 1.02s
215:	learn: 0.6079938	total: 281ms	remaining: 1.02s
216:	learn: 0.6061267	total: 282ms	remaining: 1.02s
217:	learn: 0.6035774	total: 283ms	remaining: 1.01s
218:	learn: 0.6009645	total: 285ms	remaining: 1.01s
219:	learn: 0.5981137	total: 286ms	remaining: 1.01s
220:	learn: 0.5966207	total: 288ms	remaining: 1.01s
221:	learn: 0.5941404	total: 289ms	remaining: 1.01s
222:	learn: 0.5911426	total: 290ms	remaining: 1.01s
223:	learn: 0.5874597	total: 292ms	remaining: 1.01s
224:	learn: 0.5840279	total: 293ms	remaining: 1.01s
225:	learn: 0.5809868	total: 294ms	remaining: 1.01s
226:	learn: 0.5784223	total: 296ms	remaining: 1.01s
227:	learn: 0.5759421	total: 297ms	remaining: 1s
228:	learn: 0.5737083	total: 298ms	remaining: 1s
229:	learn: 0.5717173	total: 300ms	remaining: 1s
230:	learn: 0.5692714	total: 301ms	remaining: 1s
231:	learn: 0.5666783	total: 304ms	remaining: 1.01s
232:	learn: 0.5639380	total: 306ms	remaining: 1.01s
233:	learn: 0.5620223	total: 308ms	remaining: 1.01s
234:	learn: 0.5596412	total: 309ms	remaining: 1s
235:	learn: 0.5568937	total: 310ms	remaining: 1s
236:	learn: 0.5542837	total: 311ms	remaining: 1s
237:	learn: 0.5523386	total: 313ms	remaining: 1s
238:	learn: 0.5497879	total: 314ms	remaining: 999ms
239:	learn: 0.5478597	total: 315ms	remaining: 997ms
240:	learn: 0.5446705	total: 317ms	remaining: 998ms
241:	learn: 0.5432816	total: 318ms	remaining: 997ms
242:	learn: 0.5418332	total: 320ms	remaining: 996ms
243:	learn: 0.5406333	total: 321ms	remaining: 995ms
244:	learn: 0.5388992	total: 322ms	remaining: 993ms
245:	learn: 0.5374386	total: 324ms	remaining: 992ms
246:	learn: 0.5353400	total: 325ms	remaining: 990ms
247:	learn: 0.5334390	total: 326ms	remaining: 988ms
248:	learn: 0.5312268	total: 327ms	remaining: 987ms
249:	learn: 0.5289794	total: 328ms	remaining: 985ms
250:	learn: 0.5258862	total: 330ms	remaining: 983ms
251:	learn: 0.5239704	total: 331ms	remaining: 982ms
252:	learn: 0.5218589	total: 333ms	remaining: 983ms
253:	learn: 0.5196377	total: 334ms	remaining: 981ms
254:	learn: 0.5174842	total: 335ms	remaining: 980ms
255:	learn: 0.5156298	total: 337ms	remaining: 979ms
256:	learn: 0.5133520	total: 338ms	remaining: 977ms
257:	learn: 0.5111567	total: 339ms	remaining: 976ms
258:	learn: 0.5092560	total: 341ms	remaining: 974ms
259:	learn: 0.5073871	total: 342ms	remaining: 973ms
260:	learn: 0.5054296	total: 343ms	remaining: 971ms
261:	learn: 0.5029217	total: 344ms	remaining: 970ms
262:	learn: 0.5010324	total: 345ms	remaining: 968ms
263:	learn: 0.4983950	total: 347ms	remaining: 966ms
264:	learn: 0.4968334	total: 348ms	remaining: 965ms
265:	learn: 0.4955960	total: 349ms	remaining: 964ms
266:	learn: 0.4938339	total: 351ms	remaining: 963ms
267:	learn: 0.4919088	total: 352ms	remaining: 962ms
268:	learn: 0.4902174	total: 353ms	remaining: 960ms
269:	learn: 0.4873674	total: 355ms	remaining: 959ms
270:	learn: 0.4854851	total: 356ms	remaining: 957ms
271:	learn: 0.4831731	total: 357ms	remaining: 955ms
272:	learn: 0.4816369	total: 358ms	remaining: 954ms
273:	learn: 0.4807264	total: 360ms	remaining: 954ms
274:	learn: 0.4791384	total: 361ms	remaining: 953ms
275:	learn: 0.4785439	total: 363ms	remaining: 952ms
276:	learn: 0.4768304	total: 364ms	remaining: 951ms
277:	learn: 0.4758318	total: 365ms	remaining: 949ms
278:	learn: 0.4744333	total: 367ms	remaining: 948ms
279:	learn: 0.4733005	total: 368ms	remaining: 946ms
280:	learn: 0.4723897	total: 369ms	remaining: 945ms
281:	learn: 0.4698977	total: 371ms	remaining: 944ms
282:	learn: 0.4689690	total: 372ms	remaining: 943ms
283:	learn: 0.4674995	total: 374ms	remaining: 942ms
284:	learn: 0.4659227	total: 375ms	remaining: 941ms
285:	learn: 0.4648841	total: 376ms	remaining: 940ms
286:	learn: 0.4634125	total: 378ms	remaining: 939ms
287:	learn: 0.4614326	total: 379ms	remaining: 937ms
288:	learn: 0.4595322	total: 381ms	remaining: 936ms
289:	learn: 0.4581517	total: 382ms	remaining: 936ms
290:	learn: 0.4571905	total: 383ms	remaining: 934ms
291:	learn: 0.4561761	total: 385ms	remaining: 933ms
292:	learn: 0.4553720	total: 386ms	remaining: 931ms
293:	learn: 0.4535878	total: 387ms	remaining: 929ms
294:	learn: 0.4519541	total: 388ms	remaining: 928ms
295:	learn: 0.4509687	total: 390ms	remaining: 927ms
296:	learn: 0.4492729	total: 391ms	remaining: 926ms
297:	learn: 0.4468406	total: 393ms	remaining: 925ms
298:	learn: 0.4456677	total: 394ms	remaining: 924ms
299:	learn: 0.4447833	total: 395ms	remaining: 923ms
300:	learn: 0.4429093	total: 397ms	remaining: 921ms
301:	learn: 0.4415124	total: 398ms	remaining: 920ms
302:	learn: 0.4408552	total: 399ms	remaining: 919ms
303:	learn: 0.4396430	total: 401ms	remaining: 917ms
304:	learn: 0.4372156	total: 402ms	remaining: 916ms
305:	learn: 0.4364047	total: 403ms	remaining: 915ms
306:	learn: 0.4350784	total: 404ms	remaining: 913ms
307:	learn: 0.4331714	total: 406ms	remaining: 912ms
308:	learn: 0.4327535	total: 407ms	remaining: 910ms
309:	learn: 0.4316404	total: 408ms	remaining: 909ms
310:	learn: 0.4310171	total: 410ms	remaining: 907ms
311:	learn: 0.4295390	total: 411ms	remaining: 906ms
312:	learn: 0.4279715	total: 412ms	remaining: 905ms
313:	learn: 0.4262934	total: 413ms	remaining: 903ms
314:	learn: 0.4252065	total: 414ms	remaining: 901ms
315:	learn: 0.4229199	total: 416ms	remaining: 900ms
316:	learn: 0.4213821	total: 417ms	remaining: 898ms
317:	learn: 0.4191629	total: 418ms	remaining: 897ms
318:	learn: 0.4174819	total: 420ms	remaining: 897ms
319:	learn: 0.4162705	total: 422ms	remaining: 897ms
320:	learn: 0.4148111	total: 423ms	remaining: 896ms
321:	learn: 0.4130969	total: 425ms	remaining: 894ms
322:	learn: 0.4122379	total: 426ms	remaining: 892ms
323:	learn: 0.4115887	total: 427ms	remaining: 891ms
324:	learn: 0.4108550	total: 428ms	remaining: 889ms
325:	learn: 0.4099350	total: 429ms	remaining: 888ms
326:	learn: 0.4083810	total: 430ms	remaining: 886ms
327:	learn: 0.4072250	total: 432ms	remaining: 884ms
328:	learn: 0.4065525	total: 433ms	remaining: 883ms
329:	learn: 0.4056040	total: 435ms	remaining: 883ms
330:	learn: 0.4041988	total: 436ms	remaining: 882ms
331:	learn: 0.4037050	total: 438ms	remaining: 880ms
332:	learn: 0.4031037	total: 439ms	remaining: 879ms
333:	learn: 0.4019472	total: 440ms	remaining: 877ms
334:	learn: 0.4006115	total: 441ms	remaining: 875ms
335:	learn: 0.3990704	total: 442ms	remaining: 874ms
336:	learn: 0.3980327	total: 443ms	remaining: 872ms
337:	learn: 0.3974087	total: 445ms	remaining: 871ms
338:	learn: 0.3954937	total: 446ms	remaining: 869ms
339:	learn: 0.3940980	total: 447ms	remaining: 868ms
340:	learn: 0.3930802	total: 448ms	remaining: 866ms
341:	learn: 0.3918395	total: 450ms	remaining: 865ms
342:	learn: 0.3905061	total: 451ms	remaining: 864ms
343:	learn: 0.3887555	total: 452ms	remaining: 862ms
344:	learn: 0.3876113	total: 453ms	remaining: 861ms
345:	learn: 0.3868897	total: 455ms	remaining: 859ms
346:	learn: 0.3855344	total: 456ms	remaining: 858ms
347:	learn: 0.3841329	total: 457ms	remaining: 856ms
348:	learn: 0.3828113	total: 458ms	remaining: 855ms
349:	learn: 0.3816714	total: 460ms	remaining: 853ms
350:	learn: 0.3810629	total: 461ms	remaining: 852ms
351:	learn: 0.3801542	total: 462ms	remaining: 851ms
352:	learn: 0.3790105	total: 464ms	remaining: 850ms
353:	learn: 0.3772331	total: 465ms	remaining: 849ms
354:	learn: 0.3761019	total: 467ms	remaining: 848ms
355:	learn: 0.3750099	total: 468ms	remaining: 847ms
356:	learn: 0.3736165	total: 469ms	remaining: 845ms
357:	learn: 0.3725267	total: 471ms	remaining: 844ms
358:	learn: 0.3711992	total: 472ms	remaining: 842ms
359:	learn: 0.3703642	total: 473ms	remaining: 841ms
360:	learn: 0.3693381	total: 474ms	remaining: 839ms
361:	learn: 0.3679852	total: 476ms	remaining: 839ms
362:	learn: 0.3672217	total: 477ms	remaining: 838ms
363:	learn: 0.3661169	total: 479ms	remaining: 836ms
364:	learn: 0.3642686	total: 480ms	remaining: 835ms
365:	learn: 0.3625954	total: 482ms	remaining: 834ms
366:	learn: 0.3621805	total: 483ms	remaining: 833ms
367:	learn: 0.3610384	total: 484ms	remaining: 831ms
368:	learn: 0.3597067	total: 485ms	remaining: 830ms
369:	learn: 0.3587458	total: 486ms	remaining: 828ms
370:	learn: 0.3579070	total: 488ms	remaining: 827ms
371:	learn: 0.3569446	total: 489ms	remaining: 825ms
372:	learn: 0.3558702	total: 490ms	remaining: 824ms
373:	learn: 0.3548465	total: 491ms	remaining: 822ms
374:	learn: 0.3538775	total: 493ms	remaining: 822ms
375:	learn: 0.3532281	total: 494ms	remaining: 820ms
376:	learn: 0.3523168	total: 496ms	remaining: 819ms
377:	learn: 0.3507475	total: 497ms	remaining: 818ms
378:	learn: 0.3496712	total: 498ms	remaining: 816ms
379:	learn: 0.3487700	total: 499ms	remaining: 815ms

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fitting SVR for C2X_rhown_9x9_depth_lt_1
Fitting KNN for C2X_rhown_9x9_depth_lt_1
Fitting LR for C2X_rhown_9x9_depth_lt_1
Fitting RF for C2X_rhown_9x9_depth_lt_1
Fitting CAT for C2X_rhown_9x9_depth_lt_1
Learning rate set to 0.033272
0:	learn: 3.4267899	total: 1.5ms	remaining: 1.5s
1:	learn: 3.3784019	total: 2.61ms	remaining: 1.3s
2:	learn: 3.3313738	total: 3.68ms	remaining: 1.22s
3:	learn: 3.2897403	total: 4.76ms	remaining: 1.19s
4:	learn: 3.2417848	total: 5.86ms	remaining: 1.17s
5:	learn: 3.2036689	total: 6.97ms	remaining: 1.15s
6:	learn: 3.1636287	total: 8.05ms	remaining: 1.14s
7:	learn: 3.1184142	total: 9.15ms	remaining: 1.14s
8:	learn: 3.0754367	total: 10.3ms	remaining: 1.13s
9:	learn: 3.0354448	total: 11.5ms	remaining: 1.14s
10:	learn: 3.0037247	total: 12.7ms	remaining: 1.14s
11:	learn: 2.9718081	total: 13.8ms	remaining: 1.14s
12:	learn: 2.9366394	total: 15.2ms	remaining: 1.15s
13:	learn: 2.8995416	total: 16.3ms	remaining: 1.15s
14:	learn: 2.8637237	total: 17.3ms	remaining: 1.14s
15:	learn: 2.8269061	total: 18.4ms	remaining: 1.13s
16:	learn: 2.7964033	total: 19.5ms	remaining: 1.13s
17:	learn: 2.7642075	total: 20.6ms	remaining: 1.12s
18:	learn: 2.7423178	total: 21.6ms	remaining: 1.12s
19:	learn: 2.7134826	total: 22.7ms	remaining: 1.11s
20:	learn: 2.6826946	total: 23.7ms	remaining: 1.1s
21:	learn: 2.6523096	total: 24.8ms	remaining: 1.1s
22:	learn: 2.6175588	total: 26.3ms	remaining: 1.12s
23:	learn: 2.5952154	total: 28ms	remaining: 1.14s
24:	learn: 2.5707366	total: 29.2ms	remaining: 1.14s
25:	learn: 2.5423702	total: 30.3ms	remaining: 1.13s
26:	learn: 2.5096528	total: 31.5ms	remaining: 1.14s
27:	learn: 2.4849402	total: 32.6ms	remaining: 1.13s
28:	learn: 2.4649608	total: 33.6ms	remaining: 1.13s
29:	learn: 2.4348012	total: 34.7ms	remaining: 1.12s
30:	learn: 2.4106732	total: 35.8ms	remaining: 1.12s
31:	learn: 2.3747949	total: 36.8ms	remaining: 1.11s
32:	learn: 2.3506373	total: 37.9ms	remaining: 1.11s
33:	learn: 2.3295618	total: 39ms	remaining: 1.11s
34:	learn: 2.3007512	total: 40.1ms	remaining: 1.1s
35:	learn: 2.2781329	total: 41.2ms	remaining: 1.1s
36:	learn: 2.2571428	total: 42.9ms	remaining: 1.12s
37:	learn: 2.2375940	total: 44.2ms	remaining: 1.12s
38:	learn: 2.2131794	total: 45.3ms	remaining: 1.12s
39:	learn: 2.1880896	total: 46.4ms	remaining: 1.11s
40:	learn: 2.1690682	total: 47.5ms	remaining: 1.11s
41:	learn: 2.1408895	total: 48.6ms	remaining: 1.11s
42:	learn: 2.1250233	total: 49.8ms	remaining: 1.11s
43:	learn: 2.1064127	total: 50.9ms	remaining: 1.1s
44:	learn: 2.0891831	total: 51.9ms	remaining: 1.1s
45:	learn: 2.0696155	total: 53ms	remaining: 1.1s
46:	learn: 2.0474272	total: 54.2ms	remaining: 1.1s
47:	learn: 2.0245298	total: 55.3ms	remaining: 1.1s
48:	learn: 2.0071830	total: 56.5ms	remaining: 1.1s
49:	learn: 1.9801868	total: 57.7ms	remaining: 1.1s
50:	learn: 1.9636225	total: 59.2ms	remaining: 1.1s
51:	learn: 1.9492085	total: 60.4ms	remaining: 1.1s
52:	learn: 1.9328357	total: 61.8ms	remaining: 1.1s
53:	learn: 1.9226479	total: 63ms	remaining: 1.1s
54:	learn: 1.9086792	total: 64.2ms	remaining: 1.1s
55:	learn: 1.8940530	total: 65.3ms	remaining: 1.1s
56:	learn: 1.8799141	total: 66.4ms	remaining: 1.1s
57:	learn: 1.8667815	total: 67.6ms	remaining: 1.1s
58:	learn: 1.8489540	total: 68.6ms	remaining: 1.09s
59:	learn: 1.8363172	total: 69.7ms	remaining: 1.09s
60:	learn: 1.8162023	total: 71.1ms	remaining: 1.09s
61:	learn: 1.8045676	total: 72.8ms	remaining: 1.1s
62:	learn: 1.7907899	total: 74.1ms	remaining: 1.1s
63:	learn: 1.7780587	total: 75.4ms	remaining: 1.1s
64:	learn: 1.7674690	total: 76.6ms	remaining: 1.1s
65:	learn: 1.7478533	total: 77.9ms	remaining: 1.1s
66:	learn: 1.7378763	total: 80.4ms	remaining: 1.12s
67:	learn: 1.7315322	total: 81.5ms	remaining: 1.12s
68:	learn: 1.7199439	total: 82.7ms	remaining: 1.11s
69:	learn: 1.7073118	total: 83.9ms	remaining: 1.11s
70:	learn: 1.6982655	total: 85ms	remaining: 1.11s
71:	learn: 1.6875296	total: 86.2ms	remaining: 1.11s
72:	learn: 1.6785602	total: 87.8ms	remaining: 1.11s
73:	learn: 1.6662220	total: 89.2ms	remaining: 1.12s
74:	learn: 1.6566516	total: 90.6ms	remaining: 1.12s
75:	learn: 1.6469351	total: 91.9ms	remaining: 1.12s
76:	learn: 1.6372587	total: 93ms	remaining: 1.11s
77:	learn: 1.6278217	total: 94.3ms	remaining: 1.11s
78:	learn: 1.6167536	total: 95.6ms	remaining: 1.11s
79:	learn: 1.6030824	total: 96.9ms	remaining: 1.11s
80:	learn: 1.5954608	total: 98.2ms	remaining: 1.11s
81:	learn: 1.5894584	total: 99.5ms	remaining: 1.11s
82:	learn: 1.5835303	total: 101ms	remaining: 1.11s
83:	learn: 1.5697122	total: 102ms	remaining: 1.11s
84:	learn: 1.5625365	total: 103ms	remaining: 1.11s
85:	learn: 1.5544364	total: 105ms	remaining: 1.11s
86:	learn: 1.5475512	total: 106ms	remaining: 1.11s
87:	learn: 1.5403722	total: 107ms	remaining: 1.11s
88:	learn: 1.5280167	total: 108ms	remaining: 1.11s
89:	learn: 1.5204141	total: 110ms	remaining: 1.11s
90:	learn: 1.5090865	total: 111ms	remaining: 1.11s
91:	learn: 1.5040960	total: 112ms	remaining: 1.11s
92:	learn: 1.5002472	total: 113ms	remaining: 1.1s
93:	learn: 1.4980687	total: 114ms	remaining: 1.1s
94:	learn: 1.4921597	total: 116ms	remaining: 1.1s
95:	learn: 1.4852161	total: 117ms	remaining: 1.1s
96:	learn: 1.4756523	total: 118ms	remaining: 1.1s
97:	learn: 1.4715101	total: 120ms	remaining: 1.1s
98:	learn: 1.4637653	total: 121ms	remaining: 1.1s
99:	learn: 1.4567539	total: 122ms	remaining: 1.1s
100:	learn: 1.4482397	total: 123ms	remaining: 1.1s
101:	learn: 1.4450219	total: 124ms	remaining: 1.09s
102:	learn: 1.4394888	total: 125ms	remaining: 1.09s
103:	learn: 1.4340171	total: 127ms	remaining: 1.09s
104:	learn: 1.4324780	total: 128ms	remaining: 1.09s
105:	learn: 1.4242076	total: 129ms	remaining: 1.09s
106:	learn: 1.4178972	total: 131ms	remaining: 1.09s
107:	learn: 1.4163770	total: 132ms	remaining: 1.09s
108:	learn: 1.4086512	total: 134ms	remaining: 1.09s
109:	learn: 1.3992347	total: 135ms	remaining: 1.09s
110:	learn: 1.3896717	total: 136ms	remaining: 1.09s
111:	learn: 1.3846204	total: 138ms	remaining: 1.09s
112:	learn: 1.3727114	total: 139ms	remaining: 1.09s
113:	learn: 1.3659127	total: 140ms	remaining: 1.08s
114:	learn: 1.3613840	total: 141ms	remaining: 1.08s
115:	learn: 1.3501266	total: 142ms	remaining: 1.08s
116:	learn: 1.3480001	total: 143ms	remaining: 1.08s
117:	learn: 1.3440911	total: 144ms	remaining: 1.08s
118:	learn: 1.3361851	total: 145ms	remaining: 1.07s
119:	learn: 1.3258375	total: 146ms	remaining: 1.07s
120:	learn: 1.3191925	total: 148ms	remaining: 1.07s
121:	learn: 1.3040657	total: 149ms	remaining: 1.07s
122:	learn: 1.2959804	total: 150ms	remaining: 1.07s
123:	learn: 1.2877098	total: 152ms	remaining: 1.07s
124:	learn: 1.2829721	total: 153ms	remaining: 1.07s
125:	learn: 1.2802768	total: 154ms	remaining: 1.07s
126:	learn: 1.2721697	total: 155ms	remaining: 1.06s
127:	learn: 1.2689334	total: 156ms	remaining: 1.06s
128:	learn: 1.2627298	total: 158ms	remaining: 1.07s
129:	learn: 1.2560576	total: 159ms	remaining: 1.06s
130:	learn: 1.2409841	total: 160ms	remaining: 1.06s
131:	learn: 1.2381290	total: 161ms	remaining: 1.06s
132:	learn: 1.2329613	total: 163ms	remaining: 1.06s
133:	learn: 1.2265002	total: 164ms	remaining: 1.06s
134:	learn: 1.2226361	total: 165ms	remaining: 1.06s
135:	learn: 1.2134827	total: 166ms	remaining: 1.06s
136:	learn: 1.2056504	total: 167ms	remaining: 1.05s
137:	learn: 1.1932096	total: 169ms	remaining: 1.05s
138:	learn: 1.1849260	total: 170ms	remaining: 1.05s
139:	learn: 1.1805584	total: 171ms	remaining: 1.05s
140:	learn: 1.1766601	total: 172ms	remaining: 1.05s
141:	learn: 1.1700326	total: 173ms	remaining: 1.04s
142:	learn: 1.1610887	total: 174ms	remaining: 1.04s
143:	learn: 1.1525106	total: 176ms	remaining: 1.04s
144:	learn: 1.1421064	total: 177ms	remaining: 1.04s
145:	learn: 1.1339065	total: 179ms	remaining: 1.04s
146:	learn: 1.1255675	total: 180ms	remaining: 1.04s
147:	learn: 1.1205914	total: 181ms	remaining: 1.04s
148:	learn: 1.1150896	total: 183ms	remaining: 1.04s
149:	learn: 1.1061778	total: 184ms	remaining: 1.04s
150:	learn: 1.1023574	total: 185ms	remaining: 1.04s
151:	learn: 1.0978814	total: 187ms	remaining: 1.04s
152:	learn: 1.0968519	total: 188ms	remaining: 1.04s
153:	learn: 1.0915719	total: 189ms	remaining: 1.04s
154:	learn: 1.0880790	total: 191ms	remaining: 1.04s
155:	learn: 1.0819065	total: 192ms	remaining: 1.04s
156:	learn: 1.0788330	total: 193ms	remaining: 1.04s
157:	learn: 1.0729934	total: 195ms	remaining: 1.04s
158:	learn: 1.0678515	total: 196ms	remaining: 1.03s
159:	learn: 1.0610832	total: 197ms	remaining: 1.04s
160:	learn: 1.0575813	total: 199ms	remaining: 1.03s
161:	learn: 1.0564957	total: 199ms	remaining: 1.03s
162:	learn: 1.0529566	total: 201ms	remaining: 1.03s
163:	learn: 1.0507544	total: 202ms	remaining: 1.03s
164:	learn: 1.0457117	total: 203ms	remaining: 1.03s
165:	learn: 1.0437347	total: 205ms	remaining: 1.03s
166:	learn: 1.0379545	total: 206ms	remaining: 1.03s
167:	learn: 1.0311739	total: 208ms	remaining: 1.03s
168:	learn: 1.0244911	total: 210ms	remaining: 1.03s
169:	learn: 1.0193120	total: 211ms	remaining: 1.03s
170:	learn: 1.0158282	total: 213ms	remaining: 1.03s
171:	learn: 1.0124199	total: 214ms	remaining: 1.03s
172:	learn: 1.0086790	total: 215ms	remaining: 1.03s
173:	learn: 1.0018510	total: 217ms	remaining: 1.03s
174:	learn: 0.9983214	total: 218ms	remaining: 1.03s
175:	learn: 0.9929249	total: 220ms	remaining: 1.03s
176:	learn: 0.9861396	total: 222ms	remaining: 1.03s
177:	learn: 0.9825163	total: 224ms	remaining: 1.03s
178:	learn: 0.9771882	total: 225ms	remaining: 1.03s
179:	learn: 0.9707031	total: 226ms	remaining: 1.03s
180:	learn: 0.9682798	total: 227ms	remaining: 1.03s
181:	learn: 0.9646639	total: 229ms	remaining: 1.03s
182:	learn: 0.9579371	total: 230ms	remaining: 1.03s
183:	learn: 0.9535590	total: 231ms	remaining: 1.02s
184:	learn: 0.9496682	total: 232ms	remaining: 1.02s
185:	learn: 0.9454199	total: 234ms	remaining: 1.02s
186:	learn: 0.9399261	total: 235ms	remaining: 1.02s
187:	learn: 0.9335919	total: 237ms	remaining: 1.02s
188:	learn: 0.9324983	total: 238ms	remaining: 1.02s
189:	learn: 0.9273382	total: 239ms	remaining: 1.02s
190:	learn: 0.9262268	total: 241ms	remaining: 1.02s
191:	learn: 0.9243094	total: 242ms	remaining: 1.02s
192:	learn: 0.9156512	total: 243ms	remaining: 1.02s
193:	learn: 0.9132206	total: 244ms	remaining: 1.01s
194:	learn: 0.9121572	total: 246ms	remaining: 1.01s
195:	learn: 0.9060900	total: 247ms	remaining: 1.01s
196:	learn: 0.9033793	total: 248ms	remaining: 1.01s
197:	learn: 0.9005244	total: 250ms	remaining: 1.01s
198:	learn: 0.8980489	total: 251ms	remaining: 1.01s
199:	learn: 0.8939785	total: 253ms	remaining: 1.01s
200:	learn: 0.8895859	total: 254ms	remaining: 1.01s
201:	learn: 0.8832447	total: 256ms	remaining: 1.01s
202:	learn: 0.8783077	total: 257ms	remaining: 1.01s
203:	learn: 0.8731717	total: 258ms	remaining: 1.01s
204:	learn: 0.8709336	total: 259ms	remaining: 1.01s
205:	learn: 0.8652310	total: 261ms	remaining: 1s
206:	learn: 0.8598094	total: 262ms	remaining: 1s
207:	learn: 0.8549416	total: 264ms	remaining: 1s
208:	learn: 0.8502673	total: 266ms	remaining: 1s
209:	learn: 0.8452126	total: 267ms	remaining: 1s
210:	learn: 0.8404356	total: 269ms	remaining: 1s
211:	learn: 0.8400299	total: 269ms	remaining: 1s
212:	learn: 0.8353963	total: 270ms	remaining: 999ms
213:	learn: 0.8306007	total: 272ms	remaining: 997ms
214:	learn: 0.8240634	total: 273ms	remaining: 996ms
215:	learn: 0.8187857	total: 274ms	remaining: 994ms
216:	learn: 0.8147201	total: 275ms	remaining: 993ms
217:	learn: 0.8101800	total: 276ms	remaining: 992ms
218:	learn: 0.8069027	total: 278ms	remaining: 990ms
219:	learn: 0.8026521	total: 279ms	remaining: 989ms
220:	learn: 0.7998191	total: 281ms	remaining: 990ms
221:	learn: 0.7959108	total: 282ms	remaining: 989ms
222:	learn: 0.7929551	total: 283ms	remaining: 988ms
223:	learn: 0.7911973	total: 285ms	remaining: 986ms
224:	learn: 0.7878279	total: 286ms	remaining: 985ms
225:	learn: 0.7852225	total: 287ms	remaining: 983ms
226:	learn: 0.7792981	total: 288ms	remaining: 982ms
227:	learn: 0.7727224	total: 289ms	remaining: 980ms
228:	learn: 0.7713609	total: 291ms	remaining: 979ms
229:	learn: 0.7681657	total: 292ms	remaining: 977ms
230:	learn: 0.7645613	total: 293ms	remaining: 976ms
231:	learn: 0.7627565	total: 294ms	remaining: 975ms
232:	learn: 0.7591840	total: 296ms	remaining: 974ms
233:	learn: 0.7566672	total: 297ms	remaining: 974ms
234:	learn: 0.7529638	total: 299ms	remaining: 973ms
235:	learn: 0.7505988	total: 300ms	remaining: 971ms
236:	learn: 0.7468943	total: 301ms	remaining: 970ms
237:	learn: 0.7438076	total: 302ms	remaining: 966ms
238:	learn: 0.7394419	total: 303ms	remaining: 966ms
239:	learn: 0.7339330	total: 304ms	remaining: 964ms
240:	learn: 0.7312750	total: 305ms	remaining: 962ms
241:	learn: 0.7285255	total: 307ms	remaining: 961ms
242:	learn: 0.7246711	total: 308ms	remaining: 960ms
243:	learn: 0.7195222	total: 309ms	remaining: 959ms
244:	learn: 0.7165035	total: 311ms	remaining: 958ms
245:	learn: 0.7130274	total: 312ms	remaining: 956ms
246:	learn: 0.7102038	total: 313ms	remaining: 955ms
247:	learn: 0.7078141	total: 315ms	remaining: 954ms
248:	learn: 0.7057562	total: 316ms	remaining: 952ms
249:	learn: 0.7006423	total: 317ms	remaining: 950ms
250:	learn: 0.6973819	total: 318ms	remaining: 949ms
251:	learn: 0.6958872	total: 319ms	remaining: 948ms
252:	learn: 0.6942079	total: 320ms	remaining: 946ms
253:	learn: 0.6912294	total: 322ms	remaining: 945ms
254:	learn: 0.6881068	total: 324ms	remaining: 946ms
255:	learn: 0.6855695	total: 325ms	remaining: 943ms
256:	learn: 0.6811084	total: 326ms	remaining: 942ms
257:	learn: 0.6783331	total: 327ms	remaining: 941ms
258:	learn: 0.6751567	total: 328ms	remaining: 939ms
259:	learn: 0.6712809	total: 329ms	remaining: 938ms
260:	learn: 0.6686761	total: 331ms	remaining: 936ms
261:	learn: 0.6663912	total: 332ms	remaining: 934ms
262:	learn: 0.6634461	total: 333ms	remaining: 933ms
263:	learn: 0.6585166	total: 334ms	remaining: 931ms
264:	learn: 0.6557872	total: 335ms	remaining: 929ms
265:	learn: 0.6528568	total: 336ms	remaining: 928ms
266:	learn: 0.6508209	total: 337ms	remaining: 926ms
267:	learn: 0.6466434	total: 339ms	remaining: 925ms
268:	learn: 0.6426230	total: 340ms	remaining: 924ms
269:	learn: 0.6366829	total: 341ms	remaining: 923ms
270:	learn: 0.6339871	total: 343ms	remaining: 921ms
271:	learn: 0.6326020	total: 344ms	remaining: 920ms
272:	learn: 0.6273695	total: 345ms	remaining: 918ms
273:	learn: 0.6246305	total: 346ms	remaining: 917ms
274:	learn: 0.6214629	total: 347ms	remaining: 915ms
275:	learn: 0.6190354	total: 348ms	remaining: 914ms
276:	learn: 0.6158422	total: 350ms	remaining: 912ms
277:	learn: 0.6120362	total: 351ms	remaining: 912ms
278:	learn: 0.6067254	total: 355ms	remaining: 917ms
279:	learn: 0.6043431	total: 357ms	remaining: 919ms
280:	learn: 0.6026076	total: 359ms	remaining: 920ms
281:	learn: 0.6016639	total: 362ms	remaining: 921ms
282:	learn: 0.5974554	total: 365ms	remaining: 924ms
283:	learn: 0.5961763	total: 367ms	remaining: 926ms
284:	learn: 0.5941993	total: 370ms	remaining: 927ms
285:	learn: 0.5923052	total: 370ms	remaining: 925ms
286:	learn: 0.5889127	total: 372ms	remaining: 923ms
287:	learn: 0.5880906	total: 373ms	remaining: 922ms
288:	learn: 0.5850549	total: 374ms	remaining: 921ms
289:	learn: 0.5824924	total: 375ms	remaining: 919ms
290:	learn: 0.5781799	total: 377ms	remaining: 920ms
291:	learn: 0.5762878	total: 379ms	remaining: 918ms
292:	learn: 0.5730916	total: 380ms	remaining: 916ms
293:	learn: 0.5710642	total: 381ms	remaining: 915ms
294:	learn: 0.5685825	total: 382ms	remaining: 913ms
295:	learn: 0.5649277	total: 383ms	remaining: 911ms
296:	learn: 0.5609819	total: 385ms	remaining: 910ms
297:	learn: 0.5588848	total: 387ms	remaining: 912ms
298:	learn: 0.5558939	total: 389ms	remaining: 911ms
299:	learn: 0.5529886	total: 390ms	remaining: 910ms
300:	learn: 0.5508344	total: 391ms	remaining: 908ms
301:	learn: 0.5474880	total: 393ms	remaining: 908ms
302:	learn: 0.5459061	total: 394ms	remaining: 906ms
303:	learn: 0.5436652	total: 395ms	remaining: 905ms
304:	learn: 0.5408479	total: 397ms	remaining: 904ms
305:	learn: 0.5390466	total: 398ms	remaining: 903ms
306:	learn: 0.5379339	total: 399ms	remaining: 901ms
307:	learn: 0.5356695	total: 401ms	remaining: 900ms
308:	learn: 0.5348780	total: 402ms	remaining: 899ms
309:	learn: 0.5327937	total: 403ms	remaining: 898ms
310:	learn: 0.5306291	total: 405ms	remaining: 897ms
311:	learn: 0.5278857	total: 406ms	remaining: 895ms
312:	learn: 0.5254367	total: 407ms	remaining: 893ms
313:	learn: 0.5239565	total: 408ms	remaining: 892ms
314:	learn: 0.5222537	total: 410ms	remaining: 891ms
315:	learn: 0.5198127	total: 411ms	remaining: 889ms
316:	learn: 0.5180818	total: 412ms	remaining: 888ms
317:	learn: 0.5151299	total: 413ms	remaining: 886ms
318:	learn: 0.5123707	total: 414ms	remaining: 885ms
319:	learn: 0.5105840	total: 416ms	remaining: 884ms
320:	learn: 0.5081113	total: 417ms	remaining: 883ms
321:	learn: 0.5064766	total: 419ms	remaining: 882ms
322:	learn: 0.5047211	total: 420ms	remaining: 880ms
323:	learn: 0.5030604	total: 421ms	remaining: 879ms
324:	learn: 0.5014478	total: 422ms	remaining: 877ms
325:	learn: 0.4991777	total: 424ms	remaining: 876ms
326:	learn: 0.4973094	total: 425ms	remaining: 874ms
327:	learn: 0.4949968	total: 426ms	remaining: 873ms
328:	learn: 0.4936008	total: 427ms	remaining: 871ms
329:	learn: 0.4920498	total: 430ms	remaining: 873ms
330:	learn: 0.4909367	total: 432ms	remaining: 873ms
331:	learn: 0.4889172	total: 433ms	remaining: 872ms
332:	learn: 0.4879864	total: 435ms	remaining: 871ms
333:	learn: 0.4853948	total: 436ms	remaining: 869ms
334:	learn: 0.4848663	total: 437ms	remaining: 868ms
335:	learn: 0.4820368	total: 439ms	remaining: 867ms
336:	learn: 0.4790956	total: 440ms	remaining: 865ms
337:	learn: 0.4778573	total: 441ms	remaining: 864ms
338:	learn: 0.4770516	total: 442ms	remaining: 863ms
339:	learn: 0.4752700	total: 444ms	remaining: 862ms
340:	learn: 0.4735318	total: 446ms	remaining: 861ms
341:	learn: 0.4726297	total: 447ms	remaining: 860ms
342:	learn: 0.4701965	total: 448ms	remaining: 859ms
343:	learn: 0.4677543	total: 450ms	remaining: 858ms
344:	learn: 0.4669700	total: 451ms	remaining: 856ms
345:	learn: 0.4657441	total: 452ms	remaining: 855ms
346:	learn: 0.4630927	total: 454ms	remaining: 853ms
347:	learn: 0.4607854	total: 455ms	remaining: 852ms
348:	learn: 0.4583611	total: 456ms	remaining: 851ms
349:	learn: 0.4571705	total: 457ms	remaining: 849ms
350:	learn: 0.4555105	total: 459ms	remaining: 848ms
351:	learn: 0.4534190	total: 460ms	remaining: 847ms
352:	learn: 0.4521421	total: 461ms	remaining: 846ms
353:	learn: 0.4502129	total: 463ms	remaining: 844ms
354:	learn: 0.4474785	total: 464ms	remaining: 843ms
355:	learn: 0.4456150	total: 465ms	remaining: 842ms
356:	learn: 0.4435559	total: 467ms	remaining: 840ms
357:	learn: 0.4417126	total: 468ms	remaining: 839ms
358:	learn: 0.4393755	total: 469ms	remaining: 838ms
359:	learn: 0.4378553	total: 470ms	remaining: 836ms
360:	learn: 0.4366960	total: 472ms	remaining: 835ms
361:	learn: 0.4351706	total: 473ms	remaining: 833ms
362:	learn: 0.4343142	total: 476ms	remaining: 835ms
363:	learn: 0.4324555	total: 478ms	remaining: 836ms
364:	learn: 0.4304406	total: 479ms	remaining: 834ms
365:	learn: 0.4296049	total: 481ms	remaining: 833ms
366:	learn: 0.4284572	total: 482ms	remaining: 831ms
367:	learn: 0.4270236	total: 483ms	remaining: 829ms
368:	learn: 0.4261356	total: 484ms	remaining: 828ms
369:	learn: 0.4243854	total: 485ms	remaining: 826ms
370:	learn: 0.4225287	total: 486ms	remaining: 824ms
371:	learn: 0.4208097	total: 487ms	remaining: 823ms
372:	learn: 0.4197037	total: 489ms	remaining: 821ms
373:	learn: 0.4187710	total: 492ms	remaining: 823ms
374:	learn: 0.4176995	total: 493ms	remaining: 822ms
375:	learn: 0.4154131	total: 494ms	remaining: 820ms
376:	learn: 0.4131820	total: 495ms	remaining: 818ms
377:	learn: 0.4114511	total: 496ms	remaining: 817ms
378:	learn: 0.4093686	total: 497ms	remaining: 815ms
379:	learn: 0.4085766	total: 499ms	remaining: 813ms
380:	learn: 0.4072078	total: 500ms	remaining: 813ms
381:	learn: 0.4063405	total: 501ms	remaining: 811ms

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fitting SVR for TOA_3x3_depth_lt_1
Fitting KNN for TOA_3x3_depth_lt_1
Fitting LR for TOA_3x3_depth_lt_1
Fitting RF for TOA_3x3_depth_lt_1
Fitting CAT for TOA_3x3_depth_lt_1
Learning rate set to 0.033292
0:	learn: 3.7239298	total: 1.92ms	remaining: 1.92s
1:	learn: 3.6907880	total: 3.19ms	remaining: 1.59s
2:	learn: 3.6414286	total: 4.38ms	remaining: 1.45s
3:	learn: 3.5914090	total: 5.54ms	remaining: 1.38s
4:	learn: 3.5213895	total: 6.75ms	remaining: 1.34s
5:	learn: 3.4645834	total: 8.12ms	remaining: 1.34s
6:	learn: 3.4073872	total: 9.3ms	remaining: 1.32s
7:	learn: 3.3450512	total: 10.4ms	remaining: 1.29s
8:	learn: 3.2980817	total: 11.5ms	remaining: 1.27s
9:	learn: 3.2425596	total: 12.6ms	remaining: 1.25s
10:	learn: 3.1938200	total: 13.7ms	remaining: 1.23s
11:	learn: 3.1433359	total: 14.8ms	remaining: 1.22s
12:	learn: 3.1065841	total: 15.9ms	remaining: 1.21s
13:	learn: 3.0453510	total: 17ms	remaining: 1.19s
14:	learn: 3.0140269	total: 18.1ms	remaining: 1.19s
15:	learn: 2.9553802	total: 19.2ms	remaining: 1.18s
16:	learn: 2.9021470	total: 20.9ms	remaining: 1.21s
17:	learn: 2.8507002	total: 22.1ms	remaining: 1.21s
18:	learn: 2.8057253	total: 23.3ms	remaining: 1.2s
19:	learn: 2.7677941	total: 24.4ms	remaining: 1.2s
20:	learn: 2.7181402	total: 25.5ms	remaining: 1.19s
21:	learn: 2.6785160	total: 26.6ms	remaining: 1.18s
22:	learn: 2.6461171	total: 27.6ms	remaining: 1.17s
23:	learn: 2.6206069	total: 28.7ms	remaining: 1.17s
24:	learn: 2.5812649	total: 29.8ms	remaining: 1.16s
25:	learn: 2.5452309	total: 30.9ms	remaining: 1.16s
26:	learn: 2.5237619	total: 32ms	remaining: 1.15s
27:	learn: 2.4858263	total: 33.1ms	remaining: 1.15s
28:	learn: 2.4543241	total: 34.2ms	remaining: 1.14s
29:	learn: 2.4155221	total: 35.6ms	remaining: 1.15s
30:	learn: 2.3742008	total: 37.2ms	remaining: 1.16s
31:	learn: 2.3317778	total: 38.3ms	remaining: 1.16s
32:	learn: 2.2983263	total: 39.5ms	remaining: 1.16s
33:	learn: 2.2584412	total: 40.7ms	remaining: 1.16s
34:	learn: 2.2276882	total: 41.8ms	remaining: 1.15s
35:	learn: 2.1897082	total: 42.9ms	remaining: 1.15s
36:	learn: 2.1568847	total: 44ms	remaining: 1.15s
37:	learn: 2.1243601	total: 45.1ms	remaining: 1.14s
38:	learn: 2.0933397	total: 46.2ms	remaining: 1.14s
39:	learn: 2.0616417	total: 47.3ms	remaining: 1.13s
40:	learn: 2.0336882	total: 48.4ms	remaining: 1.13s
41:	learn: 2.0100758	total: 49.4ms	remaining: 1.13s
42:	learn: 1.9918330	total: 50.6ms	remaining: 1.13s
43:	learn: 1.9657099	total: 51.8ms	remaining: 1.13s
44:	learn: 1.9412862	total: 53.1ms	remaining: 1.13s
45:	learn: 1.9129953	total: 54.3ms	remaining: 1.13s
46:	learn: 1.8837758	total: 55.5ms	remaining: 1.13s
47:	learn: 1.8642346	total: 56.6ms	remaining: 1.12s
48:	learn: 1.8420053	total: 57.7ms	remaining: 1.12s
49:	learn: 1.8214747	total: 58.8ms	remaining: 1.12s
50:	learn: 1.7989003	total: 60ms	remaining: 1.11s
51:	learn: 1.7753174	total: 61.1ms	remaining: 1.11s
52:	learn: 1.7550068	total: 62.2ms	remaining: 1.11s
53:	learn: 1.7388372	total: 63.3ms	remaining: 1.11s
54:	learn: 1.7201538	total: 64.4ms	remaining: 1.11s
55:	learn: 1.7006903	total: 65.5ms	remaining: 1.1s
56:	learn: 1.6811255	total: 67ms	remaining: 1.11s
57:	learn: 1.6690412	total: 68.2ms	remaining: 1.11s
58:	learn: 1.6462281	total: 69.4ms	remaining: 1.11s
59:	learn: 1.6282534	total: 70.8ms	remaining: 1.11s
60:	learn: 1.6092481	total: 72ms	remaining: 1.11s
61:	learn: 1.5903655	total: 73.2ms	remaining: 1.11s
62:	learn: 1.5669519	total: 74.3ms	remaining: 1.1s
63:	learn: 1.5523669	total: 75.4ms	remaining: 1.1s
64:	learn: 1.5423350	total: 76.6ms	remaining: 1.1s
65:	learn: 1.5232781	total: 77.6ms	remaining: 1.1s
66:	learn: 1.5077560	total: 78.7ms	remaining: 1.09s
67:	learn: 1.4988943	total: 79.8ms	remaining: 1.09s
68:	learn: 1.4919117	total: 80.9ms	remaining: 1.09s
69:	learn: 1.4870757	total: 82ms	remaining: 1.09s
70:	learn: 1.4736710	total: 83.4ms	remaining: 1.09s
71:	learn: 1.4620260	total: 84.6ms	remaining: 1.09s
72:	learn: 1.4484630	total: 85.8ms	remaining: 1.09s
73:	learn: 1.4394847	total: 86.9ms	remaining: 1.09s
74:	learn: 1.4226282	total: 88ms	remaining: 1.08s
75:	learn: 1.4104157	total: 89.1ms	remaining: 1.08s
76:	learn: 1.4020448	total: 90.3ms	remaining: 1.08s
77:	learn: 1.3857205	total: 91.4ms	remaining: 1.08s
78:	learn: 1.3760477	total: 92.5ms	remaining: 1.08s
79:	learn: 1.3664097	total: 93.6ms	remaining: 1.08s
80:	learn: 1.3538448	total: 94.8ms	remaining: 1.07s
81:	learn: 1.3390630	total: 95.9ms	remaining: 1.07s
82:	learn: 1.3282008	total: 97.2ms	remaining: 1.07s
83:	learn: 1.3170086	total: 98.4ms	remaining: 1.07s
84:	learn: 1.3065816	total: 99.7ms	remaining: 1.07s
85:	learn: 1.3020909	total: 101ms	remaining: 1.07s
86:	learn: 1.2928822	total: 102ms	remaining: 1.07s
87:	learn: 1.2825310	total: 104ms	remaining: 1.07s
88:	learn: 1.2716885	total: 105ms	remaining: 1.07s
89:	learn: 1.2672355	total: 106ms	remaining: 1.07s
90:	learn: 1.2604825	total: 107ms	remaining: 1.07s
91:	learn: 1.2504536	total: 108ms	remaining: 1.07s
92:	learn: 1.2453223	total: 109ms	remaining: 1.07s
93:	learn: 1.2358292	total: 110ms	remaining: 1.06s
94:	learn: 1.2318838	total: 112ms	remaining: 1.07s
95:	learn: 1.2217543	total: 114ms	remaining: 1.07s
96:	learn: 1.2138983	total: 115ms	remaining: 1.07s
97:	learn: 1.2074372	total: 117ms	remaining: 1.07s
98:	learn: 1.1978797	total: 118ms	remaining: 1.08s
99:	learn: 1.1905064	total: 119ms	remaining: 1.07s
100:	learn: 1.1811344	total: 121ms	remaining: 1.07s
101:	learn: 1.1707083	total: 122ms	remaining: 1.07s
102:	learn: 1.1671340	total: 123ms	remaining: 1.07s
103:	learn: 1.1563293	total: 124ms	remaining: 1.07s
104:	learn: 1.1486157	total: 125ms	remaining: 1.07s
105:	learn: 1.1386452	total: 126ms	remaining: 1.06s
106:	learn: 1.1311732	total: 128ms	remaining: 1.06s
107:	learn: 1.1238064	total: 129ms	remaining: 1.06s
108:	learn: 1.1202207	total: 130ms	remaining: 1.06s
109:	learn: 1.1112563	total: 131ms	remaining: 1.06s
110:	learn: 1.1058865	total: 132ms	remaining: 1.06s
111:	learn: 1.0982133	total: 133ms	remaining: 1.06s
112:	learn: 1.0915139	total: 135ms	remaining: 1.06s
113:	learn: 1.0830224	total: 136ms	remaining: 1.05s
114:	learn: 1.0784703	total: 137ms	remaining: 1.05s
115:	learn: 1.0732397	total: 138ms	remaining: 1.05s
116:	learn: 1.0672248	total: 139ms	remaining: 1.05s
117:	learn: 1.0627307	total: 141ms	remaining: 1.05s
118:	learn: 1.0566010	total: 143ms	remaining: 1.05s
119:	learn: 1.0504734	total: 145ms	remaining: 1.06s
120:	learn: 1.0464824	total: 146ms	remaining: 1.06s
121:	learn: 1.0411734	total: 148ms	remaining: 1.06s
122:	learn: 1.0353746	total: 149ms	remaining: 1.06s
123:	learn: 1.0283565	total: 150ms	remaining: 1.06s
124:	learn: 1.0234916	total: 152ms	remaining: 1.06s
125:	learn: 1.0201932	total: 153ms	remaining: 1.06s
126:	learn: 1.0135618	total: 154ms	remaining: 1.06s
127:	learn: 1.0076381	total: 155ms	remaining: 1.06s
128:	learn: 1.0043384	total: 157ms	remaining: 1.06s
129:	learn: 0.9957484	total: 158ms	remaining: 1.06s
130:	learn: 0.9916412	total: 160ms	remaining: 1.06s
131:	learn: 0.9869810	total: 161ms	remaining: 1.06s
132:	learn: 0.9840368	total: 162ms	remaining: 1.06s
133:	learn: 0.9786724	total: 164ms	remaining: 1.06s
134:	learn: 0.9757734	total: 165ms	remaining: 1.06s
135:	learn: 0.9693425	total: 166ms	remaining: 1.05s
136:	learn: 0.9660274	total: 167ms	remaining: 1.05s
137:	learn: 0.9635282	total: 169ms	remaining: 1.05s
138:	learn: 0.9603041	total: 170ms	remaining: 1.05s
139:	learn: 0.9558199	total: 171ms	remaining: 1.05s
140:	learn: 0.9493518	total: 173ms	remaining: 1.05s
141:	learn: 0.9446365	total: 175ms	remaining: 1.05s
142:	learn: 0.9426003	total: 176ms	remaining: 1.05s
143:	learn: 0.9366219	total: 178ms	remaining: 1.06s
144:	learn: 0.9336896	total: 180ms	remaining: 1.06s
145:	learn: 0.9268016	total: 181ms	remaining: 1.06s
146:	learn: 0.9243852	total: 182ms	remaining: 1.06s
147:	learn: 0.9192318	total: 184ms	remaining: 1.06s
148:	learn: 0.9124965	total: 185ms	remaining: 1.05s
149:	learn: 0.9093660	total: 186ms	remaining: 1.05s
150:	learn: 0.9062633	total: 187ms	remaining: 1.05s
151:	learn: 0.9031517	total: 189ms	remaining: 1.05s
152:	learn: 0.8976724	total: 191ms	remaining: 1.05s
153:	learn: 0.8927851	total: 192ms	remaining: 1.05s
154:	learn: 0.8907996	total: 193ms	remaining: 1.05s
155:	learn: 0.8877925	total: 195ms	remaining: 1.05s
156:	learn: 0.8803407	total: 196ms	remaining: 1.05s
157:	learn: 0.8768797	total: 197ms	remaining: 1.05s
158:	learn: 0.8726102	total: 198ms	remaining: 1.05s
159:	learn: 0.8699380	total: 200ms	remaining: 1.05s
160:	learn: 0.8685981	total: 201ms	remaining: 1.05s
161:	learn: 0.8667056	total: 203ms	remaining: 1.05s
162:	learn: 0.8630535	total: 205ms	remaining: 1.05s
163:	learn: 0.8610295	total: 206ms	remaining: 1.05s
164:	learn: 0.8581180	total: 208ms	remaining: 1.05s
165:	learn: 0.8524746	total: 209ms	remaining: 1.05s
166:	learn: 0.8453175	total: 211ms	remaining: 1.05s
167:	learn: 0.8424726	total: 212ms	remaining: 1.05s
168:	learn: 0.8403573	total: 213ms	remaining: 1.05s
169:	learn: 0.8351361	total: 215ms	remaining: 1.05s
170:	learn: 0.8297833	total: 216ms	remaining: 1.05s
171:	learn: 0.8243214	total: 218ms	remaining: 1.05s
172:	learn: 0.8229110	total: 220ms	remaining: 1.05s
173:	learn: 0.8203126	total: 221ms	remaining: 1.05s
174:	learn: 0.8184289	total: 222ms	remaining: 1.05s
175:	learn: 0.8164230	total: 224ms	remaining: 1.05s
176:	learn: 0.8138023	total: 225ms	remaining: 1.05s
177:	learn: 0.8084970	total: 227ms	remaining: 1.05s
178:	learn: 0.8036689	total: 228ms	remaining: 1.05s
179:	learn: 0.7990828	total: 229ms	remaining: 1.04s
180:	learn: 0.7946047	total: 231ms	remaining: 1.04s
181:	learn: 0.7920442	total: 232ms	remaining: 1.04s
182:	learn: 0.7903334	total: 234ms	remaining: 1.04s
183:	learn: 0.7837195	total: 235ms	remaining: 1.04s
184:	learn: 0.7796404	total: 236ms	remaining: 1.04s
185:	learn: 0.7741229	total: 237ms	remaining: 1.04s
186:	learn: 0.7703463	total: 239ms	remaining: 1.04s
187:	learn: 0.7663063	total: 240ms	remaining: 1.04s
188:	learn: 0.7641458	total: 243ms	remaining: 1.04s
189:	learn: 0.7596999	total: 244ms	remaining: 1.04s
190:	learn: 0.7550751	total: 246ms	remaining: 1.04s
191:	learn: 0.7510950	total: 248ms	remaining: 1.04s
192:	learn: 0.7496811	total: 249ms	remaining: 1.04s
193:	learn: 0.7448886	total: 251ms	remaining: 1.04s
194:	learn: 0.7424685	total: 252ms	remaining: 1.04s
195:	learn: 0.7392055	total: 253ms	remaining: 1.04s
196:	learn: 0.7342675	total: 254ms	remaining: 1.04s
197:	learn: 0.7328904	total: 256ms	remaining: 1.04s
198:	learn: 0.7283350	total: 257ms	remaining: 1.03s
199:	learn: 0.7261349	total: 258ms	remaining: 1.03s
200:	learn: 0.7216068	total: 260ms	remaining: 1.03s
201:	learn: 0.7178606	total: 261ms	remaining: 1.03s
202:	learn: 0.7156242	total: 263ms	remaining: 1.03s
203:	learn: 0.7125362	total: 264ms	remaining: 1.03s
204:	learn: 0.7103981	total: 266ms	remaining: 1.03s
205:	learn: 0.7050072	total: 267ms	remaining: 1.03s
206:	learn: 0.7006182	total: 268ms	remaining: 1.03s
207:	learn: 0.6962190	total: 269ms	remaining: 1.02s
208:	learn: 0.6935055	total: 271ms	remaining: 1.02s
209:	learn: 0.6917607	total: 273ms	remaining: 1.02s
210:	learn: 0.6892845	total: 274ms	remaining: 1.02s
211:	learn: 0.6860491	total: 275ms	remaining: 1.02s
212:	learn: 0.6841634	total: 276ms	remaining: 1.02s
213:	learn: 0.6805847	total: 278ms	remaining: 1.02s
214:	learn: 0.6791146	total: 280ms	remaining: 1.02s
215:	learn: 0.6767675	total: 283ms	remaining: 1.03s
216:	learn: 0.6747091	total: 286ms	remaining: 1.03s
217:	learn: 0.6717751	total: 288ms	remaining: 1.03s
218:	learn: 0.6699625	total: 290ms	remaining: 1.03s
219:	learn: 0.6674939	total: 293ms	remaining: 1.04s
220:	learn: 0.6653178	total: 294ms	remaining: 1.04s
221:	learn: 0.6608525	total: 295ms	remaining: 1.03s
222:	learn: 0.6560606	total: 297ms	remaining: 1.03s
223:	learn: 0.6529105	total: 298ms	remaining: 1.03s
224:	learn: 0.6507609	total: 299ms	remaining: 1.03s
225:	learn: 0.6466431	total: 300ms	remaining: 1.03s
226:	learn: 0.6425908	total: 302ms	remaining: 1.03s
227:	learn: 0.6409403	total: 303ms	remaining: 1.02s
228:	learn: 0.6376657	total: 304ms	remaining: 1.02s
229:	learn: 0.6351832	total: 305ms	remaining: 1.02s
230:	learn: 0.6319796	total: 306ms	remaining: 1.02s
231:	learn: 0.6301996	total: 307ms	remaining: 1.02s
232:	learn: 0.6282395	total: 309ms	remaining: 1.01s
233:	learn: 0.6265221	total: 310ms	remaining: 1.01s
234:	learn: 0.6241946	total: 311ms	remaining: 1.01s
235:	learn: 0.6213312	total: 312ms	remaining: 1.01s
236:	learn: 0.6172172	total: 313ms	remaining: 1.01s
237:	learn: 0.6141833	total: 315ms	remaining: 1.01s
238:	learn: 0.6124142	total: 316ms	remaining: 1s
239:	learn: 0.6097503	total: 317ms	remaining: 1s
240:	learn: 0.6063050	total: 318ms	remaining: 1s
241:	learn: 0.6054061	total: 319ms	remaining: 1000ms
242:	learn: 0.6016108	total: 320ms	remaining: 998ms
243:	learn: 0.5983728	total: 322ms	remaining: 996ms
244:	learn: 0.5956903	total: 323ms	remaining: 994ms
245:	learn: 0.5932024	total: 324ms	remaining: 994ms
246:	learn: 0.5902967	total: 326ms	remaining: 995ms
247:	learn: 0.5867897	total: 328ms	remaining: 994ms
248:	learn: 0.5838610	total: 329ms	remaining: 992ms
249:	learn: 0.5802943	total: 330ms	remaining: 991ms
250:	learn: 0.5779157	total: 331ms	remaining: 989ms
251:	learn: 0.5763598	total: 333ms	remaining: 987ms
252:	learn: 0.5729405	total: 334ms	remaining: 985ms
253:	learn: 0.5703196	total: 335ms	remaining: 983ms
254:	learn: 0.5694717	total: 336ms	remaining: 982ms
255:	learn: 0.5679554	total: 337ms	remaining: 980ms
256:	learn: 0.5653437	total: 338ms	remaining: 978ms
257:	learn: 0.5617596	total: 339ms	remaining: 976ms
258:	learn: 0.5582836	total: 341ms	remaining: 975ms
259:	learn: 0.5559994	total: 342ms	remaining: 975ms
260:	learn: 0.5532580	total: 344ms	remaining: 973ms
261:	learn: 0.5516517	total: 345ms	remaining: 971ms
262:	learn: 0.5503485	total: 346ms	remaining: 970ms
263:	learn: 0.5488471	total: 347ms	remaining: 968ms
264:	learn: 0.5453642	total: 348ms	remaining: 966ms
265:	learn: 0.5433212	total: 349ms	remaining: 964ms
266:	learn: 0.5398104	total: 351ms	remaining: 962ms
267:	learn: 0.5386485	total: 352ms	remaining: 961ms
268:	learn: 0.5369512	total: 353ms	remaining: 959ms
269:	learn: 0.5337911	total: 354ms	remaining: 957ms
270:	learn: 0.5307815	total: 355ms	remaining: 956ms
271:	learn: 0.5286765	total: 357ms	remaining: 955ms
272:	learn: 0.5268589	total: 358ms	remaining: 954ms
273:	learn: 0.5251008	total: 359ms	remaining: 952ms
274:	learn: 0.5236420	total: 361ms	remaining: 951ms
275:	learn: 0.5204491	total: 363ms	remaining: 952ms
276:	learn: 0.5180043	total: 364ms	remaining: 951ms
277:	learn: 0.5159061	total: 365ms	remaining: 949ms
278:	learn: 0.5143046	total: 367ms	remaining: 947ms
279:	learn: 0.5117145	total: 368ms	remaining: 945ms
280:	learn: 0.5105122	total: 369ms	remaining: 943ms
281:	learn: 0.5074850	total: 370ms	remaining: 942ms
282:	learn: 0.5054408	total: 371ms	remaining: 941ms
283:	learn: 0.5032325	total: 374ms	remaining: 944ms
284:	learn: 0.5011231	total: 376ms	remaining: 943ms
285:	learn: 0.4994681	total: 377ms	remaining: 942ms
286:	learn: 0.4979696	total: 378ms	remaining: 940ms
287:	learn: 0.4966955	total: 380ms	remaining: 939ms
288:	learn: 0.4960452	total: 381ms	remaining: 937ms
289:	learn: 0.4942925	total: 382ms	remaining: 936ms
290:	learn: 0.4935357	total: 384ms	remaining: 935ms
291:	learn: 0.4920466	total: 385ms	remaining: 933ms
292:	learn: 0.4907340	total: 387ms	remaining: 933ms
293:	learn: 0.4901726	total: 388ms	remaining: 932ms
294:	learn: 0.4866081	total: 390ms	remaining: 932ms
295:	learn: 0.4857913	total: 392ms	remaining: 931ms
296:	learn: 0.4851771	total: 393ms	remaining: 930ms
297:	learn: 0.4836858	total: 394ms	remaining: 929ms
298:	learn: 0.4821381	total: 396ms	remaining: 928ms
299:	learn: 0.4790516	total: 397ms	remaining: 927ms
300:	learn: 0.4781009	total: 398ms	remaining: 925ms
301:	learn: 0.4769523	total: 400ms	remaining: 924ms
302:	learn: 0.4761236	total: 401ms	remaining: 923ms
303:	learn: 0.4749340	total: 402ms	remaining: 921ms
304:	learn: 0.4727170	total: 404ms	remaining: 921ms
305:	learn: 0.4719074	total: 405ms	remaining: 920ms
306:	learn: 0.4688600	total: 407ms	remaining: 918ms
307:	learn: 0.4672174	total: 408ms	remaining: 917ms
308:	learn: 0.4659923	total: 410ms	remaining: 916ms
309:	learn: 0.4652467	total: 411ms	remaining: 914ms
310:	learn: 0.4631759	total: 412ms	remaining: 913ms
311:	learn: 0.4620448	total: 413ms	remaining: 912ms
312:	learn: 0.4598903	total: 415ms	remaining: 910ms
313:	learn: 0.4580519	total: 416ms	remaining: 909ms
314:	learn: 0.4552342	total: 418ms	remaining: 909ms
315:	learn: 0.4531440	total: 419ms	remaining: 908ms
316:	learn: 0.4515934	total: 421ms	remaining: 907ms
317:	learn: 0.4505630	total: 422ms	remaining: 905ms
318:	learn: 0.4497958	total: 424ms	remaining: 904ms
319:	learn: 0.4476178	total: 425ms	remaining: 903ms
320:	learn: 0.4465258	total: 426ms	remaining: 901ms
321:	learn: 0.4445640	total: 427ms	remaining: 900ms
322:	learn: 0.4436457	total: 429ms	remaining: 898ms
323:	learn: 0.4425727	total: 430ms	remaining: 897ms
324:	learn: 0.4399840	total: 431ms	remaining: 896ms
325:	learn: 0.4382474	total: 433ms	remaining: 895ms
326:	learn: 0.4363087	total: 434ms	remaining: 894ms
327:	learn: 0.4338250	total: 436ms	remaining: 892ms
328:	learn: 0.4335872	total: 437ms	remaining: 891ms
329:	learn: 0.4311040	total: 438ms	remaining: 890ms
330:	learn: 0.4302894	total: 440ms	remaining: 888ms
331:	learn: 0.4300079	total: 441ms	remaining: 887ms
332:	learn: 0.4297589	total: 442ms	remaining: 886ms
333:	learn: 0.4284762	total: 443ms	remaining: 884ms
334:	learn: 0.4270419	total: 445ms	remaining: 883ms
335:	learn: 0.4261323	total: 446ms	remaining: 881ms
336:	learn: 0.4256815	total: 447ms	remaining: 880ms
337:	learn: 0.4246937	total: 449ms	remaining: 879ms
338:	learn: 0.4233347	total: 450ms	remaining: 878ms
339:	learn: 0.4231205	total: 452ms	remaining: 877ms
340:	learn: 0.4228623	total: 453ms	remaining: 876ms
341:	learn: 0.4215276	total: 454ms	remaining: 874ms
342:	learn: 0.4195823	total: 456ms	remaining: 873ms
343:	learn: 0.4180481	total: 457ms	remaining: 872ms
344:	learn: 0.4158465	total: 458ms	remaining: 870ms
345:	learn: 0.4137584	total: 460ms	remaining: 869ms
346:	learn: 0.4126615	total: 461ms	remaining: 868ms
347:	learn: 0.4110552	total: 463ms	remaining: 868ms
348:	learn: 0.4106370	total: 465ms	remaining: 867ms
349:	learn: 0.4099624	total: 466ms	remaining: 865ms
350:	learn: 0.4091150	total: 467ms	remaining: 864ms
351:	learn: 0.4080427	total: 469ms	remaining: 863ms
352:	learn: 0.4068668	total: 470ms	remaining: 861ms
353:	learn: 0.4058851	total: 471ms	remaining: 860ms
354:	learn: 0.4045936	total: 473ms	remaining: 859ms
355:	learn: 0.4043785	total: 474ms	remaining: 858ms
356:	learn: 0.4021726	total: 475ms	remaining: 856ms
357:	learn: 0.3993335	total: 477ms	remaining: 855ms
358:	learn: 0.3991351	total: 478ms	remaining: 854ms
359:	learn: 0.3989636	total: 480ms	remaining: 853ms
360:	learn: 0.3979384	total: 481ms	remaining: 851ms
361:	learn: 0.3974771	total: 482ms	remaining: 850ms
362:	learn: 0.3956247	total: 483ms	remaining: 848ms
363:	learn: 0.3939242	total: 485ms	remaining: 847ms
364:	learn: 0.3925980	total: 486ms	remaining: 845ms
365:	learn: 0.3915536	total: 487ms	remaining: 844ms
366:	learn: 0.3906278	total: 489ms	remaining: 843ms
367:	learn: 0.3901211	total: 490ms	remaining: 842ms
368:	learn: 0.3899413	total: 491ms	remaining: 840ms
369:	learn: 0.3888934	total: 493ms	remaining: 839ms
370:	learn: 0.3885913	total: 494ms	remaining: 838ms
371:	learn: 0.3875532	total: 495ms	remaining: 836ms
372:	learn: 0.3855674	total: 497ms	remaining: 835ms
373:	learn: 0.3840704	total: 498ms	remaining: 833ms
374:	learn: 0.3831719	total: 499ms	remaining: 832ms
375:	learn: 0.3822607	total: 500ms	remaining: 831ms
376:	learn: 0.3820986	total: 502ms	remaining: 829ms
377:	learn: 0.3810718	total: 503ms	remaining: 828ms
378:	learn: 0.3801885	total: 505ms	remaining: 827ms
379:	learn: 0.3800212	total: 506ms	remaining: 826ms
380:	learn: 0.3798639	total: 508ms	remaining: 825ms

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fitting SVR for C2X-Complex_rhown_9x9_depth_lt_1
Fitting KNN for C2X-Complex_rhown_9x9_depth_lt_1
Fitting LR for C2X-Complex_rhown_9x9_depth_lt_1
Fitting RF for C2X-Complex_rhown_9x9_depth_lt_1
Fitting CAT for C2X-Complex_rhown_9x9_depth_lt_1
Learning rate set to 0.033272
0:	learn: 3.4147038	total: 1.65ms	remaining: 1.65s
1:	learn: 3.3513479	total: 2.83ms	remaining: 1.41s
2:	learn: 3.3017629	total: 4.11ms	remaining: 1.37s
3:	learn: 3.2472665	total: 5.28ms	remaining: 1.31s
4:	learn: 3.1948099	total: 6.44ms	remaining: 1.28s
5:	learn: 3.1388001	total: 7.57ms	remaining: 1.25s
6:	learn: 3.1017901	total: 8.69ms	remaining: 1.23s
7:	learn: 3.0556607	total: 9.8ms	remaining: 1.22s
8:	learn: 3.0066351	total: 10.9ms	remaining: 1.2s
9:	learn: 2.9598407	total: 12ms	remaining: 1.19s
10:	learn: 2.9150341	total: 13.7ms	remaining: 1.23s
11:	learn: 2.8712367	total: 14.8ms	remaining: 1.22s
12:	learn: 2.8325079	total: 16ms	remaining: 1.21s
13:	learn: 2.7846930	total: 17.1ms	remaining: 1.21s
14:	learn: 2.7476766	total: 18.2ms	remaining: 1.2s
15:	learn: 2.7140110	total: 19.4ms	remaining: 1.19s
16:	learn: 2.6813607	total: 20.5ms	remaining: 1.19s
17:	learn: 2.6449358	total: 21.6ms	remaining: 1.18s
18:	learn: 2.6143297	total: 22.6ms	remaining: 1.17s
19:	learn: 2.5790752	total: 23.7ms	remaining: 1.16s
20:	learn: 2.5415505	total: 24.7ms	remaining: 1.15s
21:	learn: 2.5061322	total: 25.7ms	remaining: 1.14s
22:	learn: 2.4728359	total: 26.8ms	remaining: 1.14s
23:	learn: 2.4379705	total: 27.9ms	remaining: 1.13s
24:	learn: 2.4044157	total: 29.3ms	remaining: 1.14s
25:	learn: 2.3762427	total: 30.7ms	remaining: 1.15s
26:	learn: 2.3437304	total: 31.9ms	remaining: 1.15s
27:	learn: 2.3141505	total: 33.2ms	remaining: 1.15s
28:	learn: 2.2847737	total: 34.5ms	remaining: 1.15s
29:	learn: 2.2574568	total: 35.7ms	remaining: 1.15s
30:	learn: 2.2283719	total: 36.9ms	remaining: 1.15s
31:	learn: 2.1921185	total: 38.1ms	remaining: 1.15s
32:	learn: 2.1622250	total: 39.3ms	remaining: 1.15s
33:	learn: 2.1366793	total: 40.5ms	remaining: 1.15s
34:	learn: 2.1127300	total: 41.7ms	remaining: 1.15s
35:	learn: 2.0959151	total: 42.9ms	remaining: 1.15s
36:	learn: 2.0728460	total: 44.1ms	remaining: 1.15s
37:	learn: 2.0500526	total: 45.3ms	remaining: 1.15s
38:	learn: 2.0270867	total: 46.6ms	remaining: 1.15s
39:	learn: 2.0062470	total: 47.8ms	remaining: 1.15s
40:	learn: 1.9831223	total: 49ms	remaining: 1.15s
41:	learn: 1.9607520	total: 50.4ms	remaining: 1.15s
42:	learn: 1.9359517	total: 51.6ms	remaining: 1.15s
43:	learn: 1.9189002	total: 52.7ms	remaining: 1.14s
44:	learn: 1.9014839	total: 53.7ms	remaining: 1.14s
45:	learn: 1.8836722	total: 54.9ms	remaining: 1.14s
46:	learn: 1.8673358	total: 56.1ms	remaining: 1.14s
47:	learn: 1.8443795	total: 57.4ms	remaining: 1.14s
48:	learn: 1.8261973	total: 58.7ms	remaining: 1.14s
49:	learn: 1.8061180	total: 60.1ms	remaining: 1.14s
50:	learn: 1.7905468	total: 61.5ms	remaining: 1.14s
51:	learn: 1.7711643	total: 62.7ms	remaining: 1.14s
52:	learn: 1.7556331	total: 63.9ms	remaining: 1.14s
53:	learn: 1.7379587	total: 65.2ms	remaining: 1.14s
54:	learn: 1.7239819	total: 66.4ms	remaining: 1.14s
55:	learn: 1.7050693	total: 67.6ms	remaining: 1.14s
56:	learn: 1.6849940	total: 68.7ms	remaining: 1.14s
57:	learn: 1.6665233	total: 69.9ms	remaining: 1.13s
58:	learn: 1.6455069	total: 70.9ms	remaining: 1.13s
59:	learn: 1.6283674	total: 72.1ms	remaining: 1.13s
60:	learn: 1.6121912	total: 73.7ms	remaining: 1.13s
61:	learn: 1.5927832	total: 75ms	remaining: 1.14s
62:	learn: 1.5793562	total: 76.2ms	remaining: 1.13s
63:	learn: 1.5636954	total: 77.5ms	remaining: 1.13s
64:	learn: 1.5480671	total: 78.7ms	remaining: 1.13s
65:	learn: 1.5282281	total: 80ms	remaining: 1.13s
66:	learn: 1.5176552	total: 81.2ms	remaining: 1.13s
67:	learn: 1.5005737	total: 82.5ms	remaining: 1.13s
68:	learn: 1.4795049	total: 83.7ms	remaining: 1.13s
69:	learn: 1.4649482	total: 84.9ms	remaining: 1.13s
70:	learn: 1.4564648	total: 86.2ms	remaining: 1.13s
71:	learn: 1.4425834	total: 87.5ms	remaining: 1.13s
72:	learn: 1.4296203	total: 88.9ms	remaining: 1.13s
73:	learn: 1.4143484	total: 90.2ms	remaining: 1.13s
74:	learn: 1.3994139	total: 91.6ms	remaining: 1.13s
75:	learn: 1.3832322	total: 93ms	remaining: 1.13s
76:	learn: 1.3776975	total: 94.4ms	remaining: 1.13s
77:	learn: 1.3679178	total: 95.7ms	remaining: 1.13s
78:	learn: 1.3547311	total: 97.1ms	remaining: 1.13s
79:	learn: 1.3436235	total: 98.4ms	remaining: 1.13s
80:	learn: 1.3362894	total: 99.7ms	remaining: 1.13s
81:	learn: 1.3278654	total: 101ms	remaining: 1.13s
82:	learn: 1.3189821	total: 103ms	remaining: 1.13s
83:	learn: 1.3102395	total: 104ms	remaining: 1.14s
84:	learn: 1.3002892	total: 106ms	remaining: 1.14s
85:	learn: 1.2880760	total: 107ms	remaining: 1.14s
86:	learn: 1.2834930	total: 108ms	remaining: 1.14s
87:	learn: 1.2715870	total: 110ms	remaining: 1.14s
88:	learn: 1.2550169	total: 111ms	remaining: 1.13s
89:	learn: 1.2495859	total: 112ms	remaining: 1.13s
90:	learn: 1.2440198	total: 113ms	remaining: 1.13s
91:	learn: 1.2328423	total: 114ms	remaining: 1.13s
92:	learn: 1.2200920	total: 116ms	remaining: 1.13s
93:	learn: 1.2063832	total: 117ms	remaining: 1.13s
94:	learn: 1.2025931	total: 118ms	remaining: 1.12s
95:	learn: 1.1905275	total: 120ms	remaining: 1.13s
96:	learn: 1.1833457	total: 121ms	remaining: 1.13s
97:	learn: 1.1733407	total: 122ms	remaining: 1.12s
98:	learn: 1.1684947	total: 123ms	remaining: 1.12s
99:	learn: 1.1598850	total: 125ms	remaining: 1.12s
100:	learn: 1.1514849	total: 126ms	remaining: 1.12s
101:	learn: 1.1450798	total: 127ms	remaining: 1.12s
102:	learn: 1.1351759	total: 128ms	remaining: 1.12s
103:	learn: 1.1304759	total: 129ms	remaining: 1.11s
104:	learn: 1.1245404	total: 131ms	remaining: 1.11s
105:	learn: 1.1155195	total: 132ms	remaining: 1.12s
106:	learn: 1.1083271	total: 134ms	remaining: 1.11s
107:	learn: 1.1015177	total: 135ms	remaining: 1.11s
108:	learn: 1.0914318	total: 136ms	remaining: 1.11s
109:	learn: 1.0850934	total: 137ms	remaining: 1.11s
110:	learn: 1.0778543	total: 139ms	remaining: 1.11s
111:	learn: 1.0669075	total: 140ms	remaining: 1.11s
112:	learn: 1.0577071	total: 141ms	remaining: 1.11s
113:	learn: 1.0534217	total: 142ms	remaining: 1.1s
114:	learn: 1.0472082	total: 144ms	remaining: 1.1s
115:	learn: 1.0394540	total: 145ms	remaining: 1.1s
116:	learn: 1.0314535	total: 146ms	remaining: 1.1s
117:	learn: 1.0249411	total: 147ms	remaining: 1.1s
118:	learn: 1.0204188	total: 149ms	remaining: 1.1s
119:	learn: 1.0103584	total: 150ms	remaining: 1.1s
120:	learn: 1.0028378	total: 151ms	remaining: 1.1s
121:	learn: 0.9989531	total: 153ms	remaining: 1.1s
122:	learn: 0.9892557	total: 154ms	remaining: 1.1s
123:	learn: 0.9862233	total: 155ms	remaining: 1.09s
124:	learn: 0.9801308	total: 156ms	remaining: 1.09s
125:	learn: 0.9719504	total: 157ms	remaining: 1.09s
126:	learn: 0.9652660	total: 158ms	remaining: 1.09s
127:	learn: 0.9607356	total: 160ms	remaining: 1.09s
128:	learn: 0.9587072	total: 162ms	remaining: 1.09s
129:	learn: 0.9500794	total: 163ms	remaining: 1.09s
130:	learn: 0.9440173	total: 164ms	remaining: 1.09s
131:	learn: 0.9405571	total: 166ms	remaining: 1.09s
132:	learn: 0.9370616	total: 167ms	remaining: 1.09s
133:	learn: 0.9299081	total: 168ms	remaining: 1.08s
134:	learn: 0.9287746	total: 168ms	remaining: 1.08s
135:	learn: 0.9220443	total: 169ms	remaining: 1.08s
136:	learn: 0.9189752	total: 171ms	remaining: 1.07s
137:	learn: 0.9153877	total: 172ms	remaining: 1.07s
138:	learn: 0.9104995	total: 174ms	remaining: 1.07s
139:	learn: 0.9061604	total: 175ms	remaining: 1.07s
140:	learn: 0.8998720	total: 176ms	remaining: 1.07s
141:	learn: 0.8954553	total: 177ms	remaining: 1.07s
142:	learn: 0.8901772	total: 178ms	remaining: 1.07s
143:	learn: 0.8871088	total: 179ms	remaining: 1.07s
144:	learn: 0.8828020	total: 181ms	remaining: 1.06s
145:	learn: 0.8771755	total: 182ms	remaining: 1.06s
146:	learn: 0.8742539	total: 183ms	remaining: 1.06s
147:	learn: 0.8718955	total: 184ms	remaining: 1.06s
148:	learn: 0.8635839	total: 186ms	remaining: 1.06s
149:	learn: 0.8557242	total: 187ms	remaining: 1.06s
150:	learn: 0.8550572	total: 187ms	remaining: 1.05s
151:	learn: 0.8482833	total: 189ms	remaining: 1.05s
152:	learn: 0.8422061	total: 190ms	remaining: 1.05s
153:	learn: 0.8387453	total: 191ms	remaining: 1.05s
154:	learn: 0.8305376	total: 192ms	remaining: 1.05s
155:	learn: 0.8268420	total: 194ms	remaining: 1.05s
156:	learn: 0.8210684	total: 195ms	remaining: 1.05s
157:	learn: 0.8172518	total: 197ms	remaining: 1.05s
158:	learn: 0.8121838	total: 198ms	remaining: 1.05s
159:	learn: 0.8086145	total: 199ms	remaining: 1.04s
160:	learn: 0.8047397	total: 200ms	remaining: 1.04s
161:	learn: 0.7999467	total: 201ms	remaining: 1.04s
162:	learn: 0.7950346	total: 203ms	remaining: 1.04s
163:	learn: 0.7936716	total: 204ms	remaining: 1.04s
164:	learn: 0.7878523	total: 205ms	remaining: 1.04s
165:	learn: 0.7836826	total: 206ms	remaining: 1.03s
166:	learn: 0.7803385	total: 208ms	remaining: 1.04s
167:	learn: 0.7791021	total: 210ms	remaining: 1.04s
168:	learn: 0.7747117	total: 211ms	remaining: 1.04s
169:	learn: 0.7735371	total: 212ms	remaining: 1.04s
170:	learn: 0.7687680	total: 213ms	remaining: 1.03s
171:	learn: 0.7642602	total: 215ms	remaining: 1.03s
172:	learn: 0.7620902	total: 216ms	remaining: 1.03s
173:	learn: 0.7577493	total: 217ms	remaining: 1.03s
174:	learn: 0.7544895	total: 218ms	remaining: 1.03s
175:	learn: 0.7504206	total: 220ms	remaining: 1.03s
176:	learn: 0.7460966	total: 221ms	remaining: 1.03s
177:	learn: 0.7426323	total: 222ms	remaining: 1.02s
178:	learn: 0.7385185	total: 223ms	remaining: 1.02s
179:	learn: 0.7328680	total: 225ms	remaining: 1.02s
180:	learn: 0.7265378	total: 226ms	remaining: 1.02s
181:	learn: 0.7225767	total: 228ms	remaining: 1.02s
182:	learn: 0.7201082	total: 229ms	remaining: 1.02s
183:	learn: 0.7153859	total: 230ms	remaining: 1.02s
184:	learn: 0.7110798	total: 231ms	remaining: 1.02s
185:	learn: 0.7079914	total: 233ms	remaining: 1.02s
186:	learn: 0.7065700	total: 234ms	remaining: 1.02s
187:	learn: 0.7056023	total: 236ms	remaining: 1.02s
188:	learn: 0.7023023	total: 237ms	remaining: 1.01s
189:	learn: 0.6979051	total: 238ms	remaining: 1.01s
190:	learn: 0.6940563	total: 239ms	remaining: 1.01s
191:	learn: 0.6885903	total: 241ms	remaining: 1.01s
192:	learn: 0.6861212	total: 243ms	remaining: 1.02s
193:	learn: 0.6829193	total: 245ms	remaining: 1.02s
194:	learn: 0.6780760	total: 246ms	remaining: 1.01s
195:	learn: 0.6726966	total: 247ms	remaining: 1.01s
196:	learn: 0.6690235	total: 248ms	remaining: 1.01s
197:	learn: 0.6654001	total: 249ms	remaining: 1.01s
198:	learn: 0.6637323	total: 251ms	remaining: 1.01s
199:	learn: 0.6596493	total: 252ms	remaining: 1.01s
200:	learn: 0.6562455	total: 253ms	remaining: 1s
201:	learn: 0.6523433	total: 254ms	remaining: 1s
202:	learn: 0.6489157	total: 255ms	remaining: 1s
203:	learn: 0.6468431	total: 257ms	remaining: 1s
204:	learn: 0.6434151	total: 258ms	remaining: 1s
205:	learn: 0.6419881	total: 259ms	remaining: 998ms
206:	learn: 0.6394960	total: 260ms	remaining: 997ms
207:	learn: 0.6354922	total: 261ms	remaining: 995ms
208:	learn: 0.6315438	total: 262ms	remaining: 993ms
209:	learn: 0.6293505	total: 263ms	remaining: 991ms
210:	learn: 0.6255571	total: 264ms	remaining: 989ms
211:	learn: 0.6218571	total: 266ms	remaining: 987ms
212:	learn: 0.6181702	total: 267ms	remaining: 987ms
213:	learn: 0.6143012	total: 268ms	remaining: 985ms
214:	learn: 0.6107624	total: 269ms	remaining: 983ms
215:	learn: 0.6066478	total: 271ms	remaining: 982ms
216:	learn: 0.6020052	total: 272ms	remaining: 982ms
217:	learn: 0.5978376	total: 274ms	remaining: 982ms
218:	learn: 0.5949799	total: 275ms	remaining: 981ms
219:	learn: 0.5904705	total: 276ms	remaining: 979ms
220:	learn: 0.5869474	total: 278ms	remaining: 979ms
221:	learn: 0.5834415	total: 279ms	remaining: 977ms
222:	learn: 0.5791858	total: 280ms	remaining: 975ms
223:	learn: 0.5775886	total: 281ms	remaining: 974ms
224:	learn: 0.5755524	total: 282ms	remaining: 972ms
225:	learn: 0.5744456	total: 283ms	remaining: 970ms
226:	learn: 0.5699206	total: 285ms	remaining: 969ms
227:	learn: 0.5674371	total: 286ms	remaining: 968ms
228:	learn: 0.5650776	total: 287ms	remaining: 967ms
229:	learn: 0.5623161	total: 289ms	remaining: 966ms
230:	learn: 0.5596941	total: 290ms	remaining: 964ms
231:	learn: 0.5571602	total: 291ms	remaining: 963ms
232:	learn: 0.5556966	total: 292ms	remaining: 961ms
233:	learn: 0.5529494	total: 293ms	remaining: 960ms
234:	learn: 0.5503135	total: 294ms	remaining: 958ms
235:	learn: 0.5491461	total: 295ms	remaining: 956ms
236:	learn: 0.5471938	total: 296ms	remaining: 954ms
237:	learn: 0.5440379	total: 297ms	remaining: 952ms
238:	learn: 0.5419672	total: 298ms	remaining: 950ms
239:	learn: 0.5388126	total: 300ms	remaining: 948ms
240:	learn: 0.5359257	total: 301ms	remaining: 947ms
241:	learn: 0.5336952	total: 302ms	remaining: 945ms
242:	learn: 0.5326262	total: 304ms	remaining: 948ms
243:	learn: 0.5301509	total: 306ms	remaining: 947ms
244:	learn: 0.5268799	total: 307ms	remaining: 946ms
245:	learn: 0.5249486	total: 308ms	remaining: 945ms
246:	learn: 0.5230319	total: 309ms	remaining: 943ms
247:	learn: 0.5215866	total: 311ms	remaining: 942ms
248:	learn: 0.5179514	total: 312ms	remaining: 941ms
249:	learn: 0.5168806	total: 313ms	remaining: 939ms
250:	learn: 0.5149646	total: 314ms	remaining: 937ms
251:	learn: 0.5131354	total: 315ms	remaining: 936ms
252:	learn: 0.5101658	total: 317ms	remaining: 935ms
253:	learn: 0.5082496	total: 318ms	remaining: 934ms
254:	learn: 0.5062183	total: 319ms	remaining: 933ms
255:	learn: 0.5041831	total: 321ms	remaining: 932ms
256:	learn: 0.5006064	total: 322ms	remaining: 930ms
257:	learn: 0.4997387	total: 323ms	remaining: 929ms
258:	learn: 0.4980771	total: 324ms	remaining: 928ms
259:	learn: 0.4963872	total: 325ms	remaining: 926ms
260:	learn: 0.4947834	total: 327ms	remaining: 925ms
261:	learn: 0.4938499	total: 328ms	remaining: 924ms
262:	learn: 0.4922939	total: 329ms	remaining: 922ms
263:	learn: 0.4906835	total: 330ms	remaining: 921ms
264:	learn: 0.4898167	total: 332ms	remaining: 920ms
265:	learn: 0.4883397	total: 333ms	remaining: 918ms
266:	learn: 0.4853903	total: 334ms	remaining: 917ms
267:	learn: 0.4814322	total: 335ms	remaining: 916ms
268:	learn: 0.4793050	total: 337ms	remaining: 914ms
269:	learn: 0.4785693	total: 338ms	remaining: 913ms
270:	learn: 0.4776393	total: 339ms	remaining: 911ms
271:	learn: 0.4754581	total: 340ms	remaining: 910ms
272:	learn: 0.4733363	total: 341ms	remaining: 908ms
273:	learn: 0.4722786	total: 342ms	remaining: 907ms
274:	learn: 0.4694591	total: 344ms	remaining: 906ms
275:	learn: 0.4661003	total: 345ms	remaining: 904ms
276:	learn: 0.4652261	total: 347ms	remaining: 904ms
277:	learn: 0.4622510	total: 348ms	remaining: 903ms
278:	learn: 0.4594741	total: 349ms	remaining: 902ms
279:	learn: 0.4582480	total: 350ms	remaining: 901ms
280:	learn: 0.4576446	total: 351ms	remaining: 899ms
281:	learn: 0.4550290	total: 353ms	remaining: 898ms
282:	learn: 0.4541173	total: 354ms	remaining: 896ms
283:	learn: 0.4536394	total: 355ms	remaining: 895ms
284:	learn: 0.4528293	total: 356ms	remaining: 893ms
285:	learn: 0.4522636	total: 358ms	remaining: 894ms
286:	learn: 0.4518634	total: 361ms	remaining: 897ms
287:	learn: 0.4504423	total: 362ms	remaining: 896ms
288:	learn: 0.4500277	total: 364ms	remaining: 894ms
289:	learn: 0.4491853	total: 365ms	remaining: 893ms
290:	learn: 0.4488546	total: 366ms	remaining: 891ms
291:	learn: 0.4483367	total: 367ms	remaining: 890ms
292:	learn: 0.4474999	total: 368ms	remaining: 888ms
293:	learn: 0.4471950	total: 369ms	remaining: 887ms
294:	learn: 0.4466852	total: 371ms	remaining: 886ms
295:	learn: 0.4463263	total: 372ms	remaining: 885ms
296:	learn: 0.4437408	total: 373ms	remaining: 883ms
297:	learn: 0.4411668	total: 374ms	remaining: 882ms
298:	learn: 0.4390168	total: 376ms	remaining: 881ms
299:	learn: 0.4387035	total: 377ms	remaining: 879ms
300:	learn: 0.4383739	total: 378ms	remaining: 878ms
301:	learn: 0.4362955	total: 379ms	remaining: 877ms
302:	learn: 0.4337854	total: 381ms	remaining: 876ms
303:	learn: 0.4313103	total: 382ms	remaining: 875ms
304:	learn: 0.4289014	total: 384ms	remaining: 874ms
305:	learn: 0.4280262	total: 385ms	remaining: 873ms
306:	learn: 0.4262993	total: 386ms	remaining: 871ms
307:	learn: 0.4253784	total: 387ms	remaining: 870ms
308:	learn: 0.4230787	total: 388ms	remaining: 868ms
309:	learn: 0.4208578	total: 389ms	remaining: 867ms
310:	learn: 0.4191627	total: 391ms	remaining: 865ms
311:	learn: 0.4172735	total: 392ms	remaining: 864ms
312:	learn: 0.4169376	total: 394ms	remaining: 865ms
313:	learn: 0.4154026	total: 397ms	remaining: 867ms
314:	learn: 0.4150290	total: 398ms	remaining: 866ms
315:	learn: 0.4141843	total: 399ms	remaining: 865ms
316:	learn: 0.4127535	total: 401ms	remaining: 863ms
317:	learn: 0.4105212	total: 402ms	remaining: 862ms
318:	learn: 0.4082491	total: 403ms	remaining: 860ms
319:	learn: 0.4055313	total: 404ms	remaining: 859ms
320:	learn: 0.4052615	total: 405ms	remaining: 857ms
321:	learn: 0.4049463	total: 407ms	remaining: 856ms
322:	learn: 0.4046077	total: 409ms	remaining: 856ms
323:	learn: 0.4030459	total: 410ms	remaining: 856ms
324:	learn: 0.4027228	total: 411ms	remaining: 854ms
325:	learn: 0.4006801	total: 413ms	remaining: 853ms
326:	learn: 0.4004496	total: 414ms	remaining: 852ms
327:	learn: 0.3979064	total: 415ms	remaining: 850ms
328:	learn: 0.3958975	total: 416ms	remaining: 849ms
329:	learn: 0.3952437	total: 418ms	remaining: 848ms
330:	learn: 0.3929653	total: 419ms	remaining: 847ms
331:	learn: 0.3906904	total: 421ms	remaining: 847ms
332:	learn: 0.3896195	total: 424ms	remaining: 850ms
333:	learn: 0.3882092	total: 427ms	remaining: 851ms
334:	learn: 0.3879592	total: 429ms	remaining: 851ms
335:	learn: 0.3876032	total: 431ms	remaining: 852ms
336:	learn: 0.3861990	total: 433ms	remaining: 853ms
337:	learn: 0.3840583	total: 435ms	remaining: 853ms
338:	learn: 0.3835062	total: 437ms	remaining: 851ms
339:	learn: 0.3821214	total: 438ms	remaining: 850ms
340:	learn: 0.3811058	total: 441ms	remaining: 852ms
341:	learn: 0.3793098	total: 444ms	remaining: 854ms
342:	learn: 0.3779718	total: 446ms	remaining: 854ms
343:	learn: 0.3761904	total: 448ms	remaining: 854ms
344:	learn: 0.3743280	total: 450ms	remaining: 855ms
345:	learn: 0.3741580	total: 452ms	remaining: 855ms
346:	learn: 0.3739041	total: 455ms	remaining: 856ms
347:	learn: 0.3723552	total: 457ms	remaining: 857ms
348:	learn: 0.3707007	total: 459ms	remaining: 857ms
349:	learn: 0.3705828	total: 461ms	remaining: 856ms
350:	learn: 0.3685427	total: 462ms	remaining: 855ms
351:	learn: 0.3670407	total: 463ms	remaining: 853ms
352:	learn: 0.3657881	total: 465ms	remaining: 852ms
353:	learn: 0.3635988	total: 466ms	remaining: 850ms
354:	learn: 0.3633419	total: 467ms	remaining: 849ms
355:	learn: 0.3609794	total: 469ms	remaining: 849ms
356:	learn: 0.3597157	total: 472ms	remaining: 849ms
357:	learn: 0.3580137	total: 473ms	remaining: 848ms
358:	learn: 0.3564828	total: 474ms	remaining: 847ms
359:	learn: 0.3550908	total: 476ms	remaining: 846ms
360:	learn: 0.3548754	total: 477ms	remaining: 844ms
361:	learn: 0.3534150	total: 478ms	remaining: 843ms
362:	learn: 0.3531606	total: 479ms	remaining: 841ms
363:	learn: 0.3516035	total: 481ms	remaining: 840ms
364:	learn: 0.3501864	total: 482ms	remaining: 839ms
365:	learn: 0.3487459	total: 483ms	remaining: 837ms
366:	learn: 0.3473841	total: 485ms	remaining: 836ms
367:	learn: 0.3470587	total: 487ms	remaining: 836ms
368:	learn: 0.3452643	total: 488ms	remaining: 835ms
369:	learn: 0.3442620	total: 490ms	remaining: 834ms
370:	learn: 0.3427184	total: 491ms	remaining: 832ms
371:	learn: 0.3412851	total: 492ms	remaining: 831ms
372:	learn: 0.3410584	total: 493ms	remaining: 829ms
373:	learn: 0.3389820	total: 494ms	remaining: 828ms
374:	learn: 0.3376849	total: 496ms	remaining: 826ms
375:	learn: 0.3369814	total: 497ms	remaining: 824ms
376:	learn: 0.3351550	total: 498ms	remaining: 823ms
377:	learn: 0.3329653	total: 500ms	remaining: 822ms
378:	learn: 0.3325769	total: 501ms	remaining: 821ms
379:	learn: 0.3319145	total: 502ms	remaining: 820ms

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fitting SVR for C2X-Complex_rhow_3x3_depth_lt_1
Fitting KNN for C2X-Complex_rhow_3x3_depth_lt_1
Fitting LR for C2X-Complex_rhow_3x3_depth_lt_1
Fitting RF for C2X-Complex_rhow_3x3_depth_lt_1
Fitting CAT for C2X-Complex_rhow_3x3_depth_lt_1
Learning rate set to 0.033272
0:	learn: 3.4065491	total: 2.18ms	remaining: 2.18s
1:	learn: 3.3502020	total: 3.56ms	remaining: 1.78s
2:	learn: 3.2948016	total: 4.86ms	remaining: 1.61s
3:	learn: 3.2343777	total: 6.17ms	remaining: 1.53s
4:	learn: 3.1839413	total: 7.4ms	remaining: 1.47s
5:	learn: 3.1312251	total: 8.89ms	remaining: 1.47s
6:	learn: 3.0793130	total: 10.4ms	remaining: 1.48s
7:	learn: 3.0308274	total: 11.6ms	remaining: 1.44s
8:	learn: 2.9732503	total: 12.8ms	remaining: 1.41s
9:	learn: 2.9304526	total: 14ms	remaining: 1.38s
10:	learn: 2.8777961	total: 15.4ms	remaining: 1.38s
11:	learn: 2.8331921	total: 16.6ms	remaining: 1.37s
12:	learn: 2.7850686	total: 18ms	remaining: 1.37s
13:	learn: 2.7437934	total: 19.2ms	remaining: 1.35s
14:	learn: 2.6950698	total: 20.4ms	remaining: 1.34s
15:	learn: 2.6513477	total: 21.6ms	remaining: 1.33s
16:	learn: 2.6052685	total: 22.8ms	remaining: 1.31s
17:	learn: 2.5664835	total: 23.9ms	remaining: 1.3s
18:	learn: 2.5315462	total: 25.1ms	remaining: 1.29s
19:	learn: 2.4919429	total: 26.3ms	remaining: 1.29s
20:	learn: 2.4510310	total: 27.5ms	remaining: 1.28s
21:	learn: 2.4205340	total: 28.7ms	remaining: 1.27s
22:	learn: 2.3846289	total: 29.8ms	remaining: 1.27s
23:	learn: 2.3515872	total: 31.8ms	remaining: 1.29s
24:	learn: 2.3192517	total: 33.1ms	remaining: 1.29s
25:	learn: 2.2883335	total: 34.4ms	remaining: 1.29s
26:	learn: 2.2491414	total: 35.6ms	remaining: 1.28s
27:	learn: 2.2183041	total: 36.8ms	remaining: 1.28s
28:	learn: 2.1923480	total: 38ms	remaining: 1.27s
29:	learn: 2.1640816	total: 39.2ms	remaining: 1.27s
30:	learn: 2.1345587	total: 40.3ms	remaining: 1.26s
31:	learn: 2.1036299	total: 41.5ms	remaining: 1.25s
32:	learn: 2.0729590	total: 42.6ms	remaining: 1.25s
33:	learn: 2.0437453	total: 43.8ms	remaining: 1.24s
34:	learn: 2.0104530	total: 44.9ms	remaining: 1.24s
35:	learn: 1.9787112	total: 46.2ms	remaining: 1.24s
36:	learn: 1.9555256	total: 48.1ms	remaining: 1.25s
37:	learn: 1.9306007	total: 49.3ms	remaining: 1.25s
38:	learn: 1.8993259	total: 50.5ms	remaining: 1.24s
39:	learn: 1.8787770	total: 51.7ms	remaining: 1.24s
40:	learn: 1.8603693	total: 52.9ms	remaining: 1.24s
41:	learn: 1.8396216	total: 54.1ms	remaining: 1.23s
42:	learn: 1.8173718	total: 55.2ms	remaining: 1.23s
43:	learn: 1.7997196	total: 56.4ms	remaining: 1.22s
44:	learn: 1.7772407	total: 57.6ms	remaining: 1.22s
45:	learn: 1.7582950	total: 58.7ms	remaining: 1.22s
46:	learn: 1.7282232	total: 59.9ms	remaining: 1.21s
47:	learn: 1.7079071	total: 61ms	remaining: 1.21s
48:	learn: 1.6853921	total: 62.2ms	remaining: 1.21s
49:	learn: 1.6594966	total: 63.7ms	remaining: 1.21s
50:	learn: 1.6479304	total: 64.9ms	remaining: 1.21s
51:	learn: 1.6253158	total: 66.1ms	remaining: 1.21s
52:	learn: 1.6031309	total: 67.4ms	remaining: 1.2s
53:	learn: 1.5825225	total: 68.6ms	remaining: 1.2s
54:	learn: 1.5675698	total: 69.8ms	remaining: 1.2s
55:	learn: 1.5457074	total: 70.9ms	remaining: 1.2s
56:	learn: 1.5264306	total: 72.1ms	remaining: 1.19s
57:	learn: 1.5135569	total: 73.3ms	remaining: 1.19s
58:	learn: 1.4988320	total: 74.5ms	remaining: 1.19s
59:	learn: 1.4828741	total: 75.9ms	remaining: 1.19s
60:	learn: 1.4677587	total: 77.3ms	remaining: 1.19s
61:	learn: 1.4526948	total: 78.6ms	remaining: 1.19s
62:	learn: 1.4417305	total: 80.3ms	remaining: 1.19s
63:	learn: 1.4277907	total: 81.7ms	remaining: 1.2s
64:	learn: 1.4114027	total: 82.9ms	remaining: 1.19s
65:	learn: 1.3967742	total: 84.1ms	remaining: 1.19s
66:	learn: 1.3834588	total: 85.3ms	remaining: 1.19s
67:	learn: 1.3696983	total: 86.5ms	remaining: 1.19s
68:	learn: 1.3629916	total: 87.7ms	remaining: 1.18s
69:	learn: 1.3537415	total: 88.8ms	remaining: 1.18s
70:	learn: 1.3400733	total: 90ms	remaining: 1.18s
71:	learn: 1.3258643	total: 91.2ms	remaining: 1.18s
72:	learn: 1.3129704	total: 92.4ms	remaining: 1.17s
73:	learn: 1.3009028	total: 93.7ms	remaining: 1.17s
74:	learn: 1.2882140	total: 95.1ms	remaining: 1.17s
75:	learn: 1.2747006	total: 96.3ms	remaining: 1.17s
76:	learn: 1.2601801	total: 97.7ms	remaining: 1.17s
77:	learn: 1.2485911	total: 99.2ms	remaining: 1.17s
78:	learn: 1.2332393	total: 101ms	remaining: 1.18s
79:	learn: 1.2241369	total: 102ms	remaining: 1.18s
80:	learn: 1.2080116	total: 104ms	remaining: 1.18s
81:	learn: 1.1964923	total: 105ms	remaining: 1.18s
82:	learn: 1.1895498	total: 106ms	remaining: 1.18s
83:	learn: 1.1792168	total: 108ms	remaining: 1.17s
84:	learn: 1.1703731	total: 109ms	remaining: 1.18s
85:	learn: 1.1587818	total: 111ms	remaining: 1.18s
86:	learn: 1.1498629	total: 112ms	remaining: 1.18s
87:	learn: 1.1397187	total: 114ms	remaining: 1.18s
88:	learn: 1.1294214	total: 115ms	remaining: 1.18s
89:	learn: 1.1188709	total: 116ms	remaining: 1.18s
90:	learn: 1.1130310	total: 118ms	remaining: 1.17s
91:	learn: 1.1083425	total: 119ms	remaining: 1.17s
92:	learn: 1.0988382	total: 120ms	remaining: 1.17s
93:	learn: 1.0887928	total: 122ms	remaining: 1.17s
94:	learn: 1.0774473	total: 123ms	remaining: 1.17s
95:	learn: 1.0712012	total: 124ms	remaining: 1.17s
96:	learn: 1.0657192	total: 126ms	remaining: 1.17s
97:	learn: 1.0567226	total: 128ms	remaining: 1.17s
98:	learn: 1.0502689	total: 129ms	remaining: 1.17s
99:	learn: 1.0387744	total: 131ms	remaining: 1.17s
100:	learn: 1.0327848	total: 132ms	remaining: 1.17s
101:	learn: 1.0256703	total: 133ms	remaining: 1.17s
102:	learn: 1.0216383	total: 134ms	remaining: 1.17s
103:	learn: 1.0152402	total: 136ms	remaining: 1.17s
104:	learn: 1.0089161	total: 137ms	remaining: 1.17s
105:	learn: 0.9989774	total: 138ms	remaining: 1.17s
106:	learn: 0.9892532	total: 140ms	remaining: 1.17s
107:	learn: 0.9846074	total: 141ms	remaining: 1.17s
108:	learn: 0.9766356	total: 143ms	remaining: 1.17s
109:	learn: 0.9689044	total: 144ms	remaining: 1.17s
110:	learn: 0.9604184	total: 146ms	remaining: 1.17s
111:	learn: 0.9553706	total: 147ms	remaining: 1.16s
112:	learn: 0.9499614	total: 148ms	remaining: 1.16s
113:	learn: 0.9476555	total: 149ms	remaining: 1.16s
114:	learn: 0.9418323	total: 151ms	remaining: 1.16s
115:	learn: 0.9369051	total: 152ms	remaining: 1.16s
116:	learn: 0.9338699	total: 153ms	remaining: 1.16s
117:	learn: 0.9271323	total: 155ms	remaining: 1.16s
118:	learn: 0.9217206	total: 156ms	remaining: 1.16s
119:	learn: 0.9157051	total: 158ms	remaining: 1.16s
120:	learn: 0.9102045	total: 159ms	remaining: 1.16s
121:	learn: 0.9046960	total: 161ms	remaining: 1.16s
122:	learn: 0.8963983	total: 162ms	remaining: 1.16s
123:	learn: 0.8915199	total: 163ms	remaining: 1.15s
124:	learn: 0.8857605	total: 165ms	remaining: 1.15s
125:	learn: 0.8823772	total: 166ms	remaining: 1.15s
126:	learn: 0.8807193	total: 167ms	remaining: 1.15s
127:	learn: 0.8745768	total: 169ms	remaining: 1.15s
128:	learn: 0.8684936	total: 171ms	remaining: 1.16s
129:	learn: 0.8633241	total: 173ms	remaining: 1.16s
130:	learn: 0.8554965	total: 174ms	remaining: 1.16s
131:	learn: 0.8497642	total: 176ms	remaining: 1.15s
132:	learn: 0.8472259	total: 177ms	remaining: 1.16s
133:	learn: 0.8444438	total: 179ms	remaining: 1.16s
134:	learn: 0.8367737	total: 181ms	remaining: 1.16s
135:	learn: 0.8317438	total: 183ms	remaining: 1.16s
136:	learn: 0.8280115	total: 184ms	remaining: 1.16s
137:	learn: 0.8241893	total: 185ms	remaining: 1.16s
138:	learn: 0.8200616	total: 187ms	remaining: 1.16s
139:	learn: 0.8152445	total: 189ms	remaining: 1.16s
140:	learn: 0.8135069	total: 190ms	remaining: 1.16s
141:	learn: 0.8086783	total: 192ms	remaining: 1.16s
142:	learn: 0.8034600	total: 193ms	remaining: 1.16s
143:	learn: 0.7970087	total: 195ms	remaining: 1.16s
144:	learn: 0.7918373	total: 196ms	remaining: 1.16s
145:	learn: 0.7865133	total: 197ms	remaining: 1.15s
146:	learn: 0.7812931	total: 199ms	remaining: 1.15s
147:	learn: 0.7784875	total: 201ms	remaining: 1.16s
148:	learn: 0.7743518	total: 203ms	remaining: 1.16s
149:	learn: 0.7701458	total: 205ms	remaining: 1.16s
150:	learn: 0.7656488	total: 207ms	remaining: 1.17s
151:	learn: 0.7600597	total: 209ms	remaining: 1.17s
152:	learn: 0.7550636	total: 210ms	remaining: 1.16s
153:	learn: 0.7523805	total: 212ms	remaining: 1.16s
154:	learn: 0.7507993	total: 213ms	remaining: 1.16s
155:	learn: 0.7473771	total: 214ms	remaining: 1.16s
156:	learn: 0.7423372	total: 216ms	remaining: 1.16s
157:	learn: 0.7382132	total: 218ms	remaining: 1.16s
158:	learn: 0.7335255	total: 219ms	remaining: 1.16s
159:	learn: 0.7300015	total: 221ms	remaining: 1.16s
160:	learn: 0.7275217	total: 222ms	remaining: 1.16s
161:	learn: 0.7232387	total: 224ms	remaining: 1.16s
162:	learn: 0.7177003	total: 225ms	remaining: 1.16s
163:	learn: 0.7139814	total: 226ms	remaining: 1.15s
164:	learn: 0.7080007	total: 228ms	remaining: 1.16s
165:	learn: 0.7037100	total: 230ms	remaining: 1.16s
166:	learn: 0.6997076	total: 232ms	remaining: 1.16s
167:	learn: 0.6954932	total: 233ms	remaining: 1.15s
168:	learn: 0.6928163	total: 235ms	remaining: 1.15s
169:	learn: 0.6918189	total: 236ms	remaining: 1.15s
170:	learn: 0.6865028	total: 238ms	remaining: 1.15s
171:	learn: 0.6825422	total: 239ms	remaining: 1.15s
172:	learn: 0.6777746	total: 241ms	remaining: 1.15s
173:	learn: 0.6726014	total: 243ms	remaining: 1.15s
174:	learn: 0.6699001	total: 244ms	remaining: 1.15s
175:	learn: 0.6669142	total: 246ms	remaining: 1.15s
176:	learn: 0.6634254	total: 247ms	remaining: 1.15s
177:	learn: 0.6593145	total: 249ms	remaining: 1.15s
178:	learn: 0.6562073	total: 251ms	remaining: 1.15s
179:	learn: 0.6525881	total: 252ms	remaining: 1.15s
180:	learn: 0.6487427	total: 254ms	remaining: 1.15s
181:	learn: 0.6466700	total: 255ms	remaining: 1.15s
182:	learn: 0.6431063	total: 257ms	remaining: 1.15s
183:	learn: 0.6379792	total: 258ms	remaining: 1.14s
184:	learn: 0.6353802	total: 259ms	remaining: 1.14s
185:	learn: 0.6305485	total: 261ms	remaining: 1.14s
186:	learn: 0.6255339	total: 262ms	remaining: 1.14s
187:	learn: 0.6225810	total: 264ms	remaining: 1.14s
188:	learn: 0.6190507	total: 265ms	remaining: 1.14s
189:	learn: 0.6167278	total: 267ms	remaining: 1.14s
190:	learn: 0.6149499	total: 268ms	remaining: 1.14s
191:	learn: 0.6103629	total: 270ms	remaining: 1.14s
192:	learn: 0.6085416	total: 271ms	remaining: 1.13s
193:	learn: 0.6051440	total: 273ms	remaining: 1.13s
194:	learn: 0.6009013	total: 274ms	remaining: 1.13s
195:	learn: 0.5964940	total: 275ms	remaining: 1.13s
196:	learn: 0.5926634	total: 277ms	remaining: 1.13s
197:	learn: 0.5894508	total: 278ms	remaining: 1.13s
198:	learn: 0.5853675	total: 280ms	remaining: 1.13s
199:	learn: 0.5846331	total: 282ms	remaining: 1.13s
200:	learn: 0.5821448	total: 283ms	remaining: 1.13s
201:	learn: 0.5795484	total: 284ms	remaining: 1.12s
202:	learn: 0.5755612	total: 286ms	remaining: 1.12s
203:	learn: 0.5722865	total: 287ms	remaining: 1.12s
204:	learn: 0.5695636	total: 289ms	remaining: 1.12s
205:	learn: 0.5653154	total: 290ms	remaining: 1.12s
206:	learn: 0.5617800	total: 292ms	remaining: 1.12s
207:	learn: 0.5581547	total: 294ms	remaining: 1.12s
208:	learn: 0.5556977	total: 296ms	remaining: 1.12s
209:	learn: 0.5527143	total: 297ms	remaining: 1.12s
210:	learn: 0.5492333	total: 298ms	remaining: 1.11s
211:	learn: 0.5457149	total: 300ms	remaining: 1.11s
212:	learn: 0.5433437	total: 301ms	remaining: 1.11s
213:	learn: 0.5409837	total: 302ms	remaining: 1.11s
214:	learn: 0.5378050	total: 304ms	remaining: 1.11s
215:	learn: 0.5347347	total: 305ms	remaining: 1.11s
216:	learn: 0.5315213	total: 307ms	remaining: 1.11s
217:	learn: 0.5287675	total: 308ms	remaining: 1.11s
218:	learn: 0.5265263	total: 310ms	remaining: 1.1s
219:	learn: 0.5234320	total: 311ms	remaining: 1.1s
220:	learn: 0.5226204	total: 313ms	remaining: 1.1s
221:	learn: 0.5215684	total: 314ms	remaining: 1.1s
222:	learn: 0.5206083	total: 316ms	remaining: 1.1s
223:	learn: 0.5181190	total: 317ms	remaining: 1.1s
224:	learn: 0.5165092	total: 318ms	remaining: 1.1s
225:	learn: 0.5127043	total: 320ms	remaining: 1.09s
226:	learn: 0.5101201	total: 321ms	remaining: 1.09s
227:	learn: 0.5077844	total: 323ms	remaining: 1.09s
228:	learn: 0.5048949	total: 324ms	remaining: 1.09s
229:	learn: 0.5017655	total: 326ms	remaining: 1.09s
230:	learn: 0.4987457	total: 327ms	remaining: 1.09s
231:	learn: 0.4964951	total: 328ms	remaining: 1.09s
232:	learn: 0.4932156	total: 330ms	remaining: 1.08s
233:	learn: 0.4904292	total: 331ms	remaining: 1.08s
234:	learn: 0.4881301	total: 332ms	remaining: 1.08s
235:	learn: 0.4854211	total: 334ms	remaining: 1.08s
236:	learn: 0.4828877	total: 335ms	remaining: 1.08s
237:	learn: 0.4809818	total: 336ms	remaining: 1.08s
238:	learn: 0.4791533	total: 338ms	remaining: 1.08s
239:	learn: 0.4774274	total: 340ms	remaining: 1.07s
240:	learn: 0.4747958	total: 341ms	remaining: 1.07s
241:	learn: 0.4727783	total: 343ms	remaining: 1.07s
242:	learn: 0.4720397	total: 344ms	remaining: 1.07s
243:	learn: 0.4701541	total: 345ms	remaining: 1.07s
244:	learn: 0.4680343	total: 347ms	remaining: 1.07s
245:	learn: 0.4661655	total: 349ms	remaining: 1.07s
246:	learn: 0.4645662	total: 351ms	remaining: 1.07s
247:	learn: 0.4624148	total: 354ms	remaining: 1.07s
248:	learn: 0.4598714	total: 356ms	remaining: 1.07s
249:	learn: 0.4572074	total: 359ms	remaining: 1.08s
250:	learn: 0.4554619	total: 361ms	remaining: 1.08s
251:	learn: 0.4536236	total: 363ms	remaining: 1.08s
252:	learn: 0.4512761	total: 364ms	remaining: 1.07s
253:	learn: 0.4497680	total: 366ms	remaining: 1.08s
254:	learn: 0.4471505	total: 368ms	remaining: 1.07s
255:	learn: 0.4453208	total: 369ms	remaining: 1.07s
256:	learn: 0.4433079	total: 371ms	remaining: 1.07s
257:	learn: 0.4418664	total: 372ms	remaining: 1.07s
258:	learn: 0.4403601	total: 373ms	remaining: 1.07s
259:	learn: 0.4380755	total: 374ms	remaining: 1.06s
260:	learn: 0.4359412	total: 376ms	remaining: 1.06s
261:	learn: 0.4331180	total: 377ms	remaining: 1.06s
262:	learn: 0.4311307	total: 378ms	remaining: 1.06s
263:	learn: 0.4297511	total: 380ms	remaining: 1.06s
264:	learn: 0.4281235	total: 381ms	remaining: 1.06s
265:	learn: 0.4263088	total: 383ms	remaining: 1.05s
266:	learn: 0.4245051	total: 384ms	remaining: 1.05s
267:	learn: 0.4225518	total: 385ms	remaining: 1.05s
268:	learn: 0.4207746	total: 388ms	remaining: 1.05s
269:	learn: 0.4199339	total: 389ms	remaining: 1.05s
270:	learn: 0.4177651	total: 391ms	remaining: 1.05s
271:	learn: 0.4159557	total: 393ms	remaining: 1.05s
272:	learn: 0.4139420	total: 395ms	remaining: 1.05s
273:	learn: 0.4131263	total: 396ms	remaining: 1.05s
274:	learn: 0.4119908	total: 398ms	remaining: 1.05s
275:	learn: 0.4103238	total: 399ms	remaining: 1.05s
276:	learn: 0.4082683	total: 401ms	remaining: 1.05s
277:	learn: 0.4063048	total: 403ms	remaining: 1.05s
278:	learn: 0.4043170	total: 404ms	remaining: 1.04s
279:	learn: 0.4027531	total: 406ms	remaining: 1.04s
280:	learn: 0.4008450	total: 407ms	remaining: 1.04s
281:	learn: 0.3994965	total: 408ms	remaining: 1.04s
282:	learn: 0.3981998	total: 409ms	remaining: 1.04s
283:	learn: 0.3976476	total: 411ms	remaining: 1.03s
284:	learn: 0.3961481	total: 412ms	remaining: 1.03s
285:	learn: 0.3948486	total: 413ms	remaining: 1.03s
286:	learn: 0.3941345	total: 414ms	remaining: 1.03s
287:	learn: 0.3933274	total: 416ms	remaining: 1.03s
288:	learn: 0.3915324	total: 419ms	remaining: 1.03s
289:	learn: 0.3898453	total: 422ms	remaining: 1.03s
290:	learn: 0.3884576	total: 424ms	remaining: 1.03s
291:	learn: 0.3871076	total: 427ms	remaining: 1.03s
292:	learn: 0.3856411	total: 429ms	remaining: 1.03s
293:	learn: 0.3847473	total: 431ms	remaining: 1.04s
294:	learn: 0.3840432	total: 434ms	remaining: 1.04s
295:	learn: 0.3825079	total: 437ms	remaining: 1.04s
296:	learn: 0.3817294	total: 439ms	remaining: 1.04s
297:	learn: 0.3801311	total: 442ms	remaining: 1.04s
298:	learn: 0.3789575	total: 444ms	remaining: 1.04s
299:	learn: 0.3777488	total: 446ms	remaining: 1.04s
300:	learn: 0.3772844	total: 448ms	remaining: 1.04s
301:	learn: 0.3755093	total: 452ms	remaining: 1.04s
302:	learn: 0.3748637	total: 454ms	remaining: 1.04s
303:	learn: 0.3735973	total: 457ms	remaining: 1.04s
304:	learn: 0.3721201	total: 459ms	remaining: 1.05s
305:	learn: 0.3707496	total: 461ms	remaining: 1.05s
306:	learn: 0.3692739	total: 464ms	remaining: 1.05s
307:	learn: 0.3672370	total: 465ms	remaining: 1.04s
308:	learn: 0.3666815	total: 467ms	remaining: 1.04s
309:	learn: 0.3649714	total: 468ms	remaining: 1.04s
310:	learn: 0.3644080	total: 470ms	remaining: 1.04s
311:	learn: 0.3632096	total: 471ms	remaining: 1.04s
312:	learn: 0.3620589	total: 473ms	remaining: 1.04s
313:	learn: 0.3600634	total: 474ms	remaining: 1.03s
314:	learn: 0.3591201	total: 475ms	remaining: 1.03s
315:	learn: 0.3575544	total: 477ms	remaining: 1.03s
316:	learn: 0.3565875	total: 478ms	remaining: 1.03s
317:	learn: 0.3550201	total: 480ms	remaining: 1.03s
318:	learn: 0.3536749	total: 482ms	remaining: 1.03s
319:	learn: 0.3527514	total: 483ms	remaining: 1.03s
320:	learn: 0.3511092	total: 484ms	remaining: 1.02s
321:	learn: 0.3496690	total: 486ms	remaining: 1.02s
322:	learn: 0.3492868	total: 487ms	remaining: 1.02s
323:	learn: 0.3482699	total: 489ms	remaining: 1.02s
324:	learn: 0.3470676	total: 490ms	remaining: 1.02s
325:	learn: 0.3457526	total: 491ms	remaining: 1.01s
326:	learn: 0.3446403	total: 493ms	remaining: 1.01s
327:	learn: 0.3438176	total: 494ms	remaining: 1.01s
328:	learn: 0.3431285	total: 497ms	remaining: 1.01s
329:	learn: 0.3424486	total: 500ms	remaining: 1.01s
330:	learn: 0.3404263	total: 502ms	remaining: 1.01s
331:	learn: 0.3391331	total: 505ms	remaining: 1.01s
332:	learn: 0.3380790	total: 506ms	remaining: 1.01s
333:	learn: 0.3370438	total: 507ms	remaining: 1.01s
334:	learn: 0.3358410	total: 509ms	remaining: 1.01s
335:	learn: 0.3346587	total: 511ms	remaining: 1.01s
336:	learn: 0.3334445	total: 513ms	remaining: 1.01s
337:	learn: 0.3330448	total: 514ms	remaining: 1.01s
338:	learn: 0.3318070	total: 516ms	remaining: 1s
339:	learn: 0.3304700	total: 518ms	remaining: 1.01s
340:	learn: 0.3298052	total: 521ms	remaining: 1.01s
341:	learn: 0.3284142	total: 523ms	remaining: 1.01s
342:	learn: 0.3272921	total: 526ms	remaining: 1.01s
343:	learn: 0.3257085	total: 529ms	remaining: 1.01s
344:	learn: 0.3243167	total: 531ms	remaining: 1.01s
345:	learn: 0.3228642	total: 533ms	remaining: 1.01s
346:	learn: 0.3217792	total: 536ms	remaining: 1.01s
347:	learn: 0.3214246	total: 538ms	remaining: 1.01s
348:	learn: 0.3205540	total: 540ms	remaining: 1.01s
349:	learn: 0.3191426	total: 541ms	remaining: 1s
350:	learn: 0.3175042	total: 545ms	remaining: 1.01s
351:	learn: 0.3161150	total: 548ms	remaining: 1.01s
352:	learn: 0.3157310	total: 550ms	remaining: 1.01s
353:	learn: 0.3141155	total: 552ms	remaining: 1.01s
354:	learn: 0.3135288	total: 553ms	remaining: 1s
355:	learn: 0.3123570	total: 555ms	remaining: 1s
356:	learn: 0.3113693	total: 556ms	remaining: 1s
357:	learn: 0.3105214	total: 558ms	remaining: 1s
358:	learn: 0.3100902	total: 560ms	remaining: 1s
359:	learn: 0.3091450	total: 563ms	remaining: 1s
360:	learn: 0.3078824	total: 566ms	remaining: 1s
361:	learn: 0.3062873	total: 569ms	remaining: 1s
362:	learn: 0.3053441	total: 571ms	remaining: 1s
363:	learn: 0.3040832	total: 574ms	remaining: 1s
364:	learn: 0.3028232	total: 577ms	remaining: 1s
365:	learn: 0.3013470	total: 580ms	remaining: 1s
366:	learn: 0.3002523	total: 583ms	remaining: 1s
367:	learn: 0.2993797	total: 585ms	remaining: 1s
368:	learn: 0.2980929	total: 586ms	remaining: 1s
369:	learn: 0.2972033	total: 587ms	remaining: 1000ms
370:	learn: 0.2959825	total: 588ms	remaining: 997ms
371:	learn: 0.2948986	total: 589ms	remaining: 995ms
372:	learn: 0.2946519	total: 592ms	remaining: 996ms
373:	learn: 0.2932439	total: 596ms	remaining: 997ms
374:	learn: 0.2921682	total: 599ms	remaining: 998ms
375:	learn: 0.2918051	total: 601ms	remaining: 997ms
376:	learn: 0.2908039	total: 603ms	remaining: 997ms
377:	learn: 0.2898094	total: 606ms	remaining: 997ms
378:	learn: 0.2892498	total: 608ms	remaining: 996ms
379:	learn: 0.2884127	total: 609ms	remaining: 994ms
380:	learn: 0.2872664	total: 610ms	remaining: 991ms

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fitting SVR for C2X_rhow_1x1_depth_lt_1
Fitting KNN for C2X_rhow_1x1_depth_lt_1
Fitting LR for C2X_rhow_1x1_depth_lt_1
Fitting RF for C2X_rhow_1x1_depth_lt_1
Fitting CAT for C2X_rhow_1x1_depth_lt_1
Learning rate set to 0.033272
0:	learn: 3.4161073	total: 2.38ms	remaining: 2.38s
1:	learn: 3.3781223	total: 3.63ms	remaining: 1.81s
2:	learn: 3.3349871	total: 5.43ms	remaining: 1.81s
3:	learn: 3.2949011	total: 6.98ms	remaining: 1.74s
4:	learn: 3.2545730	total: 8.2ms	remaining: 1.63s
5:	learn: 3.2162110	total: 9.49ms	remaining: 1.57s
6:	learn: 3.1800680	total: 10.7ms	remaining: 1.52s
7:	learn: 3.1472316	total: 11.9ms	remaining: 1.48s
8:	learn: 3.1099177	total: 13.1ms	remaining: 1.45s
9:	learn: 3.0750741	total: 14.3ms	remaining: 1.42s
10:	learn: 3.0334016	total: 15.5ms	remaining: 1.4s
11:	learn: 3.0030193	total: 16.7ms	remaining: 1.37s
12:	learn: 2.9721512	total: 17.8ms	remaining: 1.35s
13:	learn: 2.9324632	total: 19.3ms	remaining: 1.36s
14:	learn: 2.8987700	total: 20.8ms	remaining: 1.37s
15:	learn: 2.8695612	total: 22.2ms	remaining: 1.36s
16:	learn: 2.8397519	total: 23.4ms	remaining: 1.35s
17:	learn: 2.8140546	total: 24.7ms	remaining: 1.35s
18:	learn: 2.7860044	total: 25.9ms	remaining: 1.34s
19:	learn: 2.7655382	total: 27.2ms	remaining: 1.33s
20:	learn: 2.7368416	total: 28.4ms	remaining: 1.32s
21:	learn: 2.7210213	total: 29.7ms	remaining: 1.32s
22:	learn: 2.6975171	total: 30.9ms	remaining: 1.31s
23:	learn: 2.6722141	total: 32.1ms	remaining: 1.3s
24:	learn: 2.6437832	total: 33.6ms	remaining: 1.31s
25:	learn: 2.6206724	total: 35.1ms	remaining: 1.31s
26:	learn: 2.5993030	total: 36.6ms	remaining: 1.32s
27:	learn: 2.5673915	total: 37.9ms	remaining: 1.31s
28:	learn: 2.5383755	total: 39.1ms	remaining: 1.31s
29:	learn: 2.5078916	total: 40.3ms	remaining: 1.3s
30:	learn: 2.4860784	total: 41.5ms	remaining: 1.3s
31:	learn: 2.4661106	total: 42.6ms	remaining: 1.29s
32:	learn: 2.4443505	total: 43.9ms	remaining: 1.28s
33:	learn: 2.4267856	total: 45ms	remaining: 1.28s
34:	learn: 2.4075135	total: 46.2ms	remaining: 1.27s
35:	learn: 2.3805066	total: 47.3ms	remaining: 1.27s
36:	learn: 2.3550326	total: 48.5ms	remaining: 1.26s
37:	learn: 2.3423419	total: 49.7ms	remaining: 1.26s
38:	learn: 2.3312923	total: 51.5ms	remaining: 1.27s
39:	learn: 2.3060946	total: 52.7ms	remaining: 1.26s
40:	learn: 2.2887501	total: 54ms	remaining: 1.26s
41:	learn: 2.2732964	total: 55.2ms	remaining: 1.26s
42:	learn: 2.2656212	total: 56ms	remaining: 1.25s
43:	learn: 2.2466974	total: 57.2ms	remaining: 1.24s
44:	learn: 2.2372521	total: 58.4ms	remaining: 1.24s
45:	learn: 2.2224344	total: 59.6ms	remaining: 1.24s
46:	learn: 2.2017711	total: 60.7ms	remaining: 1.23s
47:	learn: 2.1859483	total: 61.9ms	remaining: 1.23s
48:	learn: 2.1662022	total: 63ms	remaining: 1.22s
49:	learn: 2.1482528	total: 64.2ms	remaining: 1.22s
50:	learn: 2.1325317	total: 65.4ms	remaining: 1.22s
51:	learn: 2.1165654	total: 67.1ms	remaining: 1.22s
52:	learn: 2.0998118	total: 68.5ms	remaining: 1.22s
53:	learn: 2.0830622	total: 69.7ms	remaining: 1.22s
54:	learn: 2.0673899	total: 71ms	remaining: 1.22s
55:	learn: 2.0520695	total: 72.3ms	remaining: 1.22s
56:	learn: 2.0395557	total: 73.6ms	remaining: 1.22s
57:	learn: 2.0242518	total: 74.8ms	remaining: 1.22s
58:	learn: 2.0043288	total: 76ms	remaining: 1.21s
59:	learn: 1.9892721	total: 77.2ms	remaining: 1.21s
60:	learn: 1.9774638	total: 78.4ms	remaining: 1.21s
61:	learn: 1.9658872	total: 79.6ms	remaining: 1.2s
62:	learn: 1.9568433	total: 80.7ms	remaining: 1.2s
63:	learn: 1.9431956	total: 81.9ms	remaining: 1.2s
64:	learn: 1.9294656	total: 83.5ms	remaining: 1.2s
65:	learn: 1.9231434	total: 84.8ms	remaining: 1.2s
66:	learn: 1.9089688	total: 86.2ms	remaining: 1.2s
67:	learn: 1.8966726	total: 87.5ms	remaining: 1.2s
68:	learn: 1.8844941	total: 88.8ms	remaining: 1.2s
69:	learn: 1.8728186	total: 89.9ms	remaining: 1.19s
70:	learn: 1.8640945	total: 91.1ms	remaining: 1.19s
71:	learn: 1.8555472	total: 92.3ms	remaining: 1.19s
72:	learn: 1.8457169	total: 93.5ms	remaining: 1.19s
73:	learn: 1.8331134	total: 94.7ms	remaining: 1.18s
74:	learn: 1.8196769	total: 95.9ms	remaining: 1.18s
75:	learn: 1.8088559	total: 97.1ms	remaining: 1.18s
76:	learn: 1.8035642	total: 98.5ms	remaining: 1.18s
77:	learn: 1.7948227	total: 100ms	remaining: 1.19s
78:	learn: 1.7778369	total: 102ms	remaining: 1.18s
79:	learn: 1.7655344	total: 103ms	remaining: 1.18s
80:	learn: 1.7571470	total: 104ms	remaining: 1.18s
81:	learn: 1.7481536	total: 105ms	remaining: 1.18s
82:	learn: 1.7390652	total: 106ms	remaining: 1.18s
83:	learn: 1.7326948	total: 108ms	remaining: 1.17s
84:	learn: 1.7169226	total: 109ms	remaining: 1.17s
85:	learn: 1.7069671	total: 110ms	remaining: 1.17s
86:	learn: 1.6899165	total: 111ms	remaining: 1.17s
87:	learn: 1.6809971	total: 112ms	remaining: 1.16s
88:	learn: 1.6717229	total: 113ms	remaining: 1.16s
89:	learn: 1.6619606	total: 117ms	remaining: 1.18s
90:	learn: 1.6478390	total: 120ms	remaining: 1.2s
91:	learn: 1.6380916	total: 122ms	remaining: 1.21s
92:	learn: 1.6267611	total: 125ms	remaining: 1.22s
93:	learn: 1.6210739	total: 127ms	remaining: 1.23s
94:	learn: 1.6176385	total: 130ms	remaining: 1.24s
95:	learn: 1.6093604	total: 133ms	remaining: 1.25s
96:	learn: 1.6035028	total: 135ms	remaining: 1.26s
97:	learn: 1.5981249	total: 138ms	remaining: 1.27s
98:	learn: 1.5899192	total: 140ms	remaining: 1.27s
99:	learn: 1.5818103	total: 142ms	remaining: 1.28s
100:	learn: 1.5696662	total: 145ms	remaining: 1.29s
101:	learn: 1.5634015	total: 147ms	remaining: 1.29s
102:	learn: 1.5478957	total: 149ms	remaining: 1.3s
103:	learn: 1.5435224	total: 151ms	remaining: 1.3s
104:	learn: 1.5389716	total: 152ms	remaining: 1.29s
105:	learn: 1.5258636	total: 153ms	remaining: 1.29s
106:	learn: 1.5114600	total: 154ms	remaining: 1.29s
107:	learn: 1.5063711	total: 156ms	remaining: 1.29s
108:	learn: 1.4991586	total: 157ms	remaining: 1.28s
109:	learn: 1.4916026	total: 159ms	remaining: 1.28s
110:	learn: 1.4868895	total: 160ms	remaining: 1.28s
111:	learn: 1.4826378	total: 161ms	remaining: 1.28s
112:	learn: 1.4757247	total: 163ms	remaining: 1.28s
113:	learn: 1.4708045	total: 164ms	remaining: 1.28s
114:	learn: 1.4599961	total: 166ms	remaining: 1.27s
115:	learn: 1.4523559	total: 167ms	remaining: 1.27s
116:	learn: 1.4427004	total: 169ms	remaining: 1.27s
117:	learn: 1.4335635	total: 170ms	remaining: 1.27s
118:	learn: 1.4263211	total: 171ms	remaining: 1.27s
119:	learn: 1.4171451	total: 172ms	remaining: 1.26s
120:	learn: 1.4058092	total: 174ms	remaining: 1.26s
121:	learn: 1.3953667	total: 175ms	remaining: 1.26s
122:	learn: 1.3908637	total: 177ms	remaining: 1.26s
123:	learn: 1.3865169	total: 178ms	remaining: 1.26s
124:	learn: 1.3797598	total: 180ms	remaining: 1.26s
125:	learn: 1.3731703	total: 182ms	remaining: 1.26s
126:	learn: 1.3661724	total: 183ms	remaining: 1.26s
127:	learn: 1.3605941	total: 185ms	remaining: 1.26s
128:	learn: 1.3550837	total: 186ms	remaining: 1.25s
129:	learn: 1.3493015	total: 187ms	remaining: 1.25s
130:	learn: 1.3444766	total: 189ms	remaining: 1.25s
131:	learn: 1.3368480	total: 190ms	remaining: 1.25s
132:	learn: 1.3284984	total: 192ms	remaining: 1.25s
133:	learn: 1.3251838	total: 193ms	remaining: 1.25s
134:	learn: 1.3214468	total: 195ms	remaining: 1.25s
135:	learn: 1.3157785	total: 197ms	remaining: 1.25s
136:	learn: 1.3140441	total: 198ms	remaining: 1.25s
137:	learn: 1.3069784	total: 200ms	remaining: 1.25s
138:	learn: 1.3031551	total: 201ms	remaining: 1.25s
139:	learn: 1.2960100	total: 203ms	remaining: 1.25s
140:	learn: 1.2862271	total: 205ms	remaining: 1.25s
141:	learn: 1.2747113	total: 206ms	remaining: 1.25s
142:	learn: 1.2672697	total: 208ms	remaining: 1.24s
143:	learn: 1.2625493	total: 209ms	remaining: 1.24s
144:	learn: 1.2601284	total: 211ms	remaining: 1.24s
145:	learn: 1.2578883	total: 212ms	remaining: 1.24s
146:	learn: 1.2512691	total: 214ms	remaining: 1.24s
147:	learn: 1.2454854	total: 215ms	remaining: 1.24s
148:	learn: 1.2408380	total: 216ms	remaining: 1.24s
149:	learn: 1.2337752	total: 218ms	remaining: 1.23s
150:	learn: 1.2318044	total: 219ms	remaining: 1.23s
151:	learn: 1.2225776	total: 221ms	remaining: 1.23s
152:	learn: 1.2168933	total: 222ms	remaining: 1.23s
153:	learn: 1.2102128	total: 224ms	remaining: 1.23s
154:	learn: 1.2066811	total: 226ms	remaining: 1.23s
155:	learn: 1.2053155	total: 227ms	remaining: 1.23s
156:	learn: 1.1997258	total: 229ms	remaining: 1.23s
157:	learn: 1.1918717	total: 230ms	remaining: 1.23s
158:	learn: 1.1891842	total: 232ms	remaining: 1.23s
159:	learn: 1.1873236	total: 233ms	remaining: 1.23s
160:	learn: 1.1822190	total: 235ms	remaining: 1.22s
161:	learn: 1.1776043	total: 236ms	remaining: 1.22s
162:	learn: 1.1758837	total: 238ms	remaining: 1.22s
163:	learn: 1.1677901	total: 240ms	remaining: 1.22s
164:	learn: 1.1653212	total: 243ms	remaining: 1.23s
165:	learn: 1.1599150	total: 246ms	remaining: 1.24s
166:	learn: 1.1569844	total: 249ms	remaining: 1.24s
167:	learn: 1.1545775	total: 251ms	remaining: 1.24s
168:	learn: 1.1464679	total: 253ms	remaining: 1.24s
169:	learn: 1.1437057	total: 254ms	remaining: 1.24s
170:	learn: 1.1390412	total: 256ms	remaining: 1.24s
171:	learn: 1.1379950	total: 257ms	remaining: 1.24s
172:	learn: 1.1337027	total: 259ms	remaining: 1.24s
173:	learn: 1.1291781	total: 260ms	remaining: 1.23s
174:	learn: 1.1207138	total: 261ms	remaining: 1.23s
175:	learn: 1.1173727	total: 263ms	remaining: 1.23s
176:	learn: 1.1111306	total: 264ms	remaining: 1.23s
177:	learn: 1.1076824	total: 265ms	remaining: 1.23s
178:	learn: 1.1057545	total: 268ms	remaining: 1.23s
179:	learn: 1.1034308	total: 269ms	remaining: 1.23s
180:	learn: 1.0994152	total: 270ms	remaining: 1.22s
181:	learn: 1.0945556	total: 272ms	remaining: 1.22s
182:	learn: 1.0936845	total: 273ms	remaining: 1.22s
183:	learn: 1.0896538	total: 275ms	remaining: 1.22s
184:	learn: 1.0851905	total: 276ms	remaining: 1.22s
185:	learn: 1.0838295	total: 277ms	remaining: 1.21s
186:	learn: 1.0823911	total: 279ms	remaining: 1.21s
187:	learn: 1.0768648	total: 280ms	remaining: 1.21s
188:	learn: 1.0704658	total: 282ms	remaining: 1.21s
189:	learn: 1.0628054	total: 283ms	remaining: 1.21s
190:	learn: 1.0617700	total: 285ms	remaining: 1.21s
191:	learn: 1.0609999	total: 286ms	remaining: 1.2s
192:	learn: 1.0552044	total: 288ms	remaining: 1.2s
193:	learn: 1.0515930	total: 289ms	remaining: 1.2s
194:	learn: 1.0493964	total: 290ms	remaining: 1.2s
195:	learn: 1.0484080	total: 292ms	remaining: 1.2s
196:	learn: 1.0457068	total: 293ms	remaining: 1.19s
197:	learn: 1.0436352	total: 294ms	remaining: 1.19s
198:	learn: 1.0382105	total: 296ms	remaining: 1.19s
199:	learn: 1.0336919	total: 297ms	remaining: 1.19s
200:	learn: 1.0295930	total: 299ms	remaining: 1.19s
201:	learn: 1.0259428	total: 301ms	remaining: 1.19s
202:	learn: 1.0237337	total: 302ms	remaining: 1.19s
203:	learn: 1.0214353	total: 305ms	remaining: 1.19s
204:	learn: 1.0192902	total: 308ms	remaining: 1.2s
205:	learn: 1.0120406	total: 311ms	remaining: 1.2s
206:	learn: 1.0068400	total: 314ms	remaining: 1.2s
207:	learn: 1.0047026	total: 317ms	remaining: 1.21s
208:	learn: 1.0030293	total: 318ms	remaining: 1.2s
209:	learn: 1.0015219	total: 320ms	remaining: 1.2s
210:	learn: 0.9966466	total: 321ms	remaining: 1.2s
211:	learn: 0.9914299	total: 322ms	remaining: 1.2s
212:	learn: 0.9888891	total: 324ms	remaining: 1.2s
213:	learn: 0.9805035	total: 325ms	remaining: 1.19s
214:	learn: 0.9758377	total: 327ms	remaining: 1.19s
215:	learn: 0.9736533	total: 329ms	remaining: 1.19s
216:	learn: 0.9721335	total: 330ms	remaining: 1.19s
217:	learn: 0.9677231	total: 332ms	remaining: 1.19s
218:	learn: 0.9632991	total: 333ms	remaining: 1.19s
219:	learn: 0.9620661	total: 334ms	remaining: 1.19s
220:	learn: 0.9568250	total: 336ms	remaining: 1.18s
221:	learn: 0.9487736	total: 337ms	remaining: 1.18s
222:	learn: 0.9410209	total: 338ms	remaining: 1.18s
223:	learn: 0.9385388	total: 340ms	remaining: 1.18s
224:	learn: 0.9332528	total: 341ms	remaining: 1.17s
225:	learn: 0.9316184	total: 344ms	remaining: 1.18s
226:	learn: 0.9304745	total: 347ms	remaining: 1.18s
227:	learn: 0.9231046	total: 350ms	remaining: 1.18s
228:	learn: 0.9170036	total: 352ms	remaining: 1.19s
229:	learn: 0.9134561	total: 354ms	remaining: 1.19s
230:	learn: 0.9104612	total: 356ms	remaining: 1.18s
231:	learn: 0.9088965	total: 357ms	remaining: 1.18s
232:	learn: 0.9050638	total: 359ms	remaining: 1.18s
233:	learn: 0.8994055	total: 360ms	remaining: 1.18s
234:	learn: 0.8942928	total: 362ms	remaining: 1.18s
235:	learn: 0.8892296	total: 363ms	remaining: 1.18s
236:	learn: 0.8842788	total: 365ms	remaining: 1.17s
237:	learn: 0.8824162	total: 367ms	remaining: 1.17s
238:	learn: 0.8814174	total: 368ms	remaining: 1.17s
239:	learn: 0.8780766	total: 369ms	remaining: 1.17s
240:	learn: 0.8736022	total: 371ms	remaining: 1.17s
241:	learn: 0.8685723	total: 372ms	remaining: 1.17s
242:	learn: 0.8670291	total: 374ms	remaining: 1.16s
243:	learn: 0.8593386	total: 375ms	remaining: 1.16s
244:	learn: 0.8575172	total: 377ms	remaining: 1.16s
245:	learn: 0.8530737	total: 378ms	remaining: 1.16s
246:	learn: 0.8510426	total: 380ms	remaining: 1.16s
247:	learn: 0.8444155	total: 381ms	remaining: 1.16s
248:	learn: 0.8430470	total: 383ms	remaining: 1.15s
249:	learn: 0.8361183	total: 384ms	remaining: 1.15s
250:	learn: 0.8350121	total: 385ms	remaining: 1.15s
251:	learn: 0.8300681	total: 387ms	remaining: 1.15s
252:	learn: 0.8236901	total: 390ms	remaining: 1.15s
253:	learn: 0.8212559	total: 393ms	remaining: 1.16s
254:	learn: 0.8154034	total: 396ms	remaining: 1.16s
255:	learn: 0.8107027	total: 399ms	remaining: 1.16s
256:	learn: 0.8066128	total: 402ms	remaining: 1.16s
257:	learn: 0.8052243	total: 405ms	remaining: 1.16s
258:	learn: 0.8039730	total: 406ms	remaining: 1.16s
259:	learn: 0.8004303	total: 408ms	remaining: 1.16s
260:	learn: 0.7990559	total: 409ms	remaining: 1.16s
261:	learn: 0.7950213	total: 412ms	remaining: 1.16s
262:	learn: 0.7898539	total: 414ms	remaining: 1.16s
263:	learn: 0.7851348	total: 415ms	remaining: 1.16s
264:	learn: 0.7844053	total: 417ms	remaining: 1.16s
265:	learn: 0.7835761	total: 418ms	remaining: 1.15s
266:	learn: 0.7826521	total: 419ms	remaining: 1.15s
267:	learn: 0.7815198	total: 421ms	remaining: 1.15s
268:	learn: 0.7784531	total: 423ms	remaining: 1.15s
269:	learn: 0.7765574	total: 424ms	remaining: 1.15s
270:	learn: 0.7755679	total: 427ms	remaining: 1.15s
271:	learn: 0.7705395	total: 430ms	remaining: 1.15s
272:	learn: 0.7696610	total: 431ms	remaining: 1.15s
273:	learn: 0.7663239	total: 433ms	remaining: 1.15s
274:	learn: 0.7651820	total: 434ms	remaining: 1.14s
275:	learn: 0.7641088	total: 436ms	remaining: 1.14s
276:	learn: 0.7582143	total: 437ms	remaining: 1.14s
277:	learn: 0.7524896	total: 439ms	remaining: 1.14s
278:	learn: 0.7492543	total: 440ms	remaining: 1.14s
279:	learn: 0.7438378	total: 441ms	remaining: 1.13s
280:	learn: 0.7432886	total: 443ms	remaining: 1.13s
281:	learn: 0.7392978	total: 444ms	remaining: 1.13s
282:	learn: 0.7385660	total: 445ms	remaining: 1.13s
283:	learn: 0.7376310	total: 447ms	remaining: 1.13s
284:	learn: 0.7370340	total: 448ms	remaining: 1.12s
285:	learn: 0.7360344	total: 450ms	remaining: 1.12s
286:	learn: 0.7322715	total: 452ms	remaining: 1.12s
287:	learn: 0.7317795	total: 453ms	remaining: 1.12s
288:	learn: 0.7292506	total: 454ms	remaining: 1.12s
289:	learn: 0.7283539	total: 456ms	remaining: 1.11s
290:	learn: 0.7274389	total: 457ms	remaining: 1.11s
291:	learn: 0.7266876	total: 458ms	remaining: 1.11s
292:	learn: 0.7261840	total: 459ms	remaining: 1.11s
293:	learn: 0.7248204	total: 461ms	remaining: 1.11s
294:	learn: 0.7227550	total: 462ms	remaining: 1.1s
295:	learn: 0.7186255	total: 463ms	remaining: 1.1s
296:	learn: 0.7178581	total: 464ms	remaining: 1.1s
297:	learn: 0.7174778	total: 466ms	remaining: 1.1s
298:	learn: 0.7128299	total: 467ms	remaining: 1.09s
299:	learn: 0.7121328	total: 468ms	remaining: 1.09s
300:	learn: 0.7093386	total: 470ms	remaining: 1.09s
301:	learn: 0.7057926	total: 471ms	remaining: 1.09s
302:	learn: 0.7050163	total: 472ms	remaining: 1.09s
303:	learn: 0.7031206	total: 473ms	remaining: 1.08s
304:	learn: 0.7006817	total: 475ms	remaining: 1.08s
305:	learn: 0.6999351	total: 476ms	remaining: 1.08s
306:	learn: 0.6968140	total: 477ms	remaining: 1.08s
307:	learn: 0.6960864	total: 478ms	remaining: 1.07s
308:	learn: 0.6955514	total: 480ms	remaining: 1.07s
309:	learn: 0.6912521	total: 481ms	remaining: 1.07s
310:	learn: 0.6907649	total: 482ms	remaining: 1.07s
311:	learn: 0.6903128	total: 484ms	remaining: 1.07s
312:	learn: 0.6876476	total: 485ms	remaining: 1.06s
313:	learn: 0.6871777	total: 487ms	remaining: 1.06s
314:	learn: 0.6867967	total: 488ms	remaining: 1.06s
315:	learn: 0.6862151	total: 489ms	remaining: 1.06s
316:	learn: 0.6832455	total: 490ms	remaining: 1.06s
317:	learn: 0.6801954	total: 492ms	remaining: 1.05s
318:	learn: 0.6795445	total: 493ms	remaining: 1.05s
319:	learn: 0.6755423	total: 494ms	remaining: 1.05s
320:	learn: 0.6751423	total: 496ms	remaining: 1.05s
321:	learn: 0.6730467	total: 497ms	remaining: 1.05s
322:	learn: 0.6703731	total: 498ms	remaining: 1.04s
323:	learn: 0.6675353	total: 499ms	remaining: 1.04s
324:	learn: 0.6669184	total: 501ms	remaining: 1.04s
325:	learn: 0.6664803	total: 502ms	remaining: 1.04s
326:	learn: 0.6632867	total: 503ms	remaining: 1.04s
327:	learn: 0.6603098	total: 505ms	remaining: 1.03s
328:	learn: 0.6598808	total: 506ms	remaining: 1.03s
329:	learn: 0.6554197	total: 507ms	remaining: 1.03s
330:	learn: 0.6535863	total: 508ms	remaining: 1.03s
331:	learn: 0.6531662	total: 510ms	remaining: 1.02s
332:	learn: 0.6503569	total: 511ms	remaining: 1.02s
333:	learn: 0.6468982	total: 512ms	remaining: 1.02s
334:	learn: 0.6459283	total: 515ms	remaining: 1.02s
335:	learn: 0.6427651	total: 517ms	remaining: 1.02s
336:	learn: 0.6386112	total: 520ms	remaining: 1.02s
337:	learn: 0.6382383	total: 522ms	remaining: 1.02s
338:	learn: 0.6371312	total: 524ms	remaining: 1.02s
339:	learn: 0.6333542	total: 527ms	remaining: 1.02s
340:	learn: 0.6323370	total: 530ms	remaining: 1.02s
341:	learn: 0.6289091	total: 533ms	remaining: 1.03s
342:	learn: 0.6258993	total: 536ms	remaining: 1.03s
343:	learn: 0.6255236	total: 539ms	remaining: 1.03s
344:	learn: 0.6251550	total: 541ms	remaining: 1.03s
345:	learn: 0.6246399	total: 543ms	remaining: 1.03s
346:	learn: 0.6213976	total: 544ms	remaining: 1.02s
347:	learn: 0.6206621	total: 546ms	remaining: 1.02s
348:	learn: 0.6199813	total: 547ms	remaining: 1.02s
349:	learn: 0.6168930	total: 549ms	remaining: 1.02s
350:	learn: 0.6140598	total: 550ms	remaining: 1.02s
351:	learn: 0.6135995	total: 551ms	remaining: 1.01s
352:	learn: 0.6112232	total: 553ms	remaining: 1.01s
353:	learn: 0.6085109	total: 554ms	remaining: 1.01s
354:	learn: 0.6059883	total: 556ms	remaining: 1.01s
355:	learn: 0.6042482	total: 557ms	remaining: 1.01s
356:	learn: 0.6020261	total: 558ms	remaining: 1s
357:	learn: 0.6017305	total: 560ms	remaining: 1s
358:	learn: 0.5984974	total: 561ms	remaining: 1s
359:	learn: 0.5982329	total: 562ms	remaining: 1000ms
360:	learn: 0.5962836	total: 564ms	remaining: 998ms
361:	learn: 0.5952977	total: 565ms	remaining: 996ms
362:	learn: 0.5947028	total: 566ms	remaining: 994ms
363:	learn: 0.5920074	total: 568ms	remaining: 992ms
364:	learn: 0.5917566	total: 569ms	remaining: 990ms
365:	learn: 0.5890475	total: 571ms	remaining: 989ms
366:	learn: 0.5888061	total: 572ms	remaining: 987ms
367:	learn: 0.5859014	total: 573ms	remaining: 985ms
368:	learn: 0.5832167	total: 575ms	remaining: 983ms
369:	learn: 0.5829778	total: 576ms	remaining: 981ms
370:	learn: 0.5801510	total: 577ms	remaining: 979ms
371:	learn: 0.5781246	total: 579ms	remaining: 977ms
372:	learn: 0.5774446	total: 581ms	remaining: 976ms
373:	learn: 0.5770752	total: 582ms	remaining: 974ms
374:	learn: 0.5763165	total: 584ms	remaining: 973ms
375:	learn: 0.5742958	total: 585ms	remaining: 970ms
376:	learn: 0.5740680	total: 586ms	remaining: 968ms
377:	learn: 0.5734619	total: 587ms	remaining: 966ms
378:	learn: 0.5727218	total: 589ms	remaining: 964ms
379:	learn: 0.5703546	total: 590ms	remaining: 962ms
380:	learn: 0.5696664	total: 591ms	remaining: 960ms

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fitting SVR for C2RCC_rhown_1x1_depth_lt_1
Fitting KNN for C2RCC_rhown_1x1_depth_lt_1
Fitting LR for C2RCC_rhown_1x1_depth_lt_1
Fitting RF for C2RCC_rhown_1x1_depth_lt_1
Fitting CAT for C2RCC_rhown_1x1_depth_lt_1
Learning rate set to 0.033272
0:	learn: 3.4173329	total: 1.84ms	remaining: 1.84s
1:	learn: 3.3584685	total: 2.97ms	remaining: 1.48s
2:	learn: 3.3047272	total: 4.07ms	remaining: 1.35s
3:	learn: 3.2482346	total: 5.4ms	remaining: 1.34s
4:	learn: 3.2065859	total: 7.32ms	remaining: 1.46s
5:	learn: 3.1611349	total: 8.62ms	remaining: 1.43s
6:	learn: 3.1121775	total: 9.82ms	remaining: 1.39s
7:	learn: 3.0638868	total: 11ms	remaining: 1.37s
8:	learn: 3.0128440	total: 12.1ms	remaining: 1.33s
9:	learn: 2.9704482	total: 13.4ms	remaining: 1.32s
10:	learn: 2.9231078	total: 14.5ms	remaining: 1.3s
11:	learn: 2.8869384	total: 15.6ms	remaining: 1.28s
12:	learn: 2.8428495	total: 16.7ms	remaining: 1.26s
13:	learn: 2.7994628	total: 17.7ms	remaining: 1.25s
14:	learn: 2.7569590	total: 18.9ms	remaining: 1.24s
15:	learn: 2.7304397	total: 20.2ms	remaining: 1.24s
16:	learn: 2.6831412	total: 21.6ms	remaining: 1.25s
17:	learn: 2.6434102	total: 22.9ms	remaining: 1.25s
18:	learn: 2.5969400	total: 24ms	remaining: 1.24s
19:	learn: 2.5605560	total: 25.1ms	remaining: 1.23s
20:	learn: 2.5239183	total: 26.2ms	remaining: 1.22s
21:	learn: 2.4864391	total: 27.4ms	remaining: 1.22s
22:	learn: 2.4474813	total: 28.5ms	remaining: 1.21s
23:	learn: 2.4252299	total: 29.6ms	remaining: 1.2s
24:	learn: 2.3991988	total: 30.6ms	remaining: 1.19s
25:	learn: 2.3653061	total: 31.7ms	remaining: 1.19s
26:	learn: 2.3335827	total: 32.7ms	remaining: 1.18s
27:	learn: 2.3060625	total: 33.8ms	remaining: 1.17s
28:	learn: 2.2708765	total: 34.8ms	remaining: 1.17s
29:	learn: 2.2477605	total: 36.5ms	remaining: 1.18s
30:	learn: 2.2228908	total: 37.7ms	remaining: 1.18s
31:	learn: 2.1946963	total: 38.9ms	remaining: 1.18s
32:	learn: 2.1665892	total: 40.1ms	remaining: 1.18s
33:	learn: 2.1474961	total: 41.2ms	remaining: 1.17s
34:	learn: 2.1187415	total: 42.3ms	remaining: 1.17s
35:	learn: 2.0898724	total: 43.3ms	remaining: 1.16s
36:	learn: 2.0693861	total: 44.4ms	remaining: 1.16s
37:	learn: 2.0466588	total: 45.5ms	remaining: 1.15s
38:	learn: 2.0328937	total: 46.5ms	remaining: 1.15s
39:	learn: 2.0120630	total: 47.6ms	remaining: 1.14s
40:	learn: 1.9878504	total: 48.7ms	remaining: 1.14s
41:	learn: 1.9669092	total: 49.8ms	remaining: 1.14s
42:	learn: 1.9497950	total: 50.9ms	remaining: 1.13s
43:	learn: 1.9284395	total: 52.7ms	remaining: 1.14s
44:	learn: 1.9108130	total: 54ms	remaining: 1.15s
45:	learn: 1.8902624	total: 55.1ms	remaining: 1.14s
46:	learn: 1.8752020	total: 56.3ms	remaining: 1.14s
47:	learn: 1.8542508	total: 57.4ms	remaining: 1.14s
48:	learn: 1.8366430	total: 58.5ms	remaining: 1.13s
49:	learn: 1.8145755	total: 59.5ms	remaining: 1.13s
50:	learn: 1.7913743	total: 60.6ms	remaining: 1.13s
51:	learn: 1.7767499	total: 61.6ms	remaining: 1.12s
52:	learn: 1.7729448	total: 63ms	remaining: 1.13s
53:	learn: 1.7495235	total: 64.1ms	remaining: 1.12s
54:	learn: 1.7289229	total: 65.2ms	remaining: 1.12s
55:	learn: 1.7061882	total: 66.3ms	remaining: 1.12s
56:	learn: 1.6924653	total: 67.5ms	remaining: 1.11s
57:	learn: 1.6712920	total: 69.5ms	remaining: 1.13s
58:	learn: 1.6565111	total: 70.7ms	remaining: 1.13s
59:	learn: 1.6420568	total: 72.1ms	remaining: 1.13s
60:	learn: 1.6202576	total: 73.4ms	remaining: 1.13s
61:	learn: 1.6071892	total: 74.7ms	remaining: 1.13s
62:	learn: 1.5958600	total: 75.8ms	remaining: 1.13s
63:	learn: 1.5914082	total: 76.9ms	remaining: 1.12s
64:	learn: 1.5824756	total: 78ms	remaining: 1.12s
65:	learn: 1.5693790	total: 79ms	remaining: 1.12s
66:	learn: 1.5642481	total: 80.1ms	remaining: 1.11s
67:	learn: 1.5531880	total: 81.1ms	remaining: 1.11s
68:	learn: 1.5404067	total: 82.2ms	remaining: 1.11s
69:	learn: 1.5336328	total: 83.1ms	remaining: 1.1s
70:	learn: 1.5267555	total: 84.4ms	remaining: 1.1s
71:	learn: 1.5235828	total: 85.5ms	remaining: 1.1s
72:	learn: 1.5160824	total: 86.7ms	remaining: 1.1s
73:	learn: 1.5078752	total: 87.9ms	remaining: 1.1s
74:	learn: 1.4962203	total: 89ms	remaining: 1.1s
75:	learn: 1.4837427	total: 90.1ms	remaining: 1.09s
76:	learn: 1.4766906	total: 91.2ms	remaining: 1.09s
77:	learn: 1.4656492	total: 92.3ms	remaining: 1.09s
78:	learn: 1.4609532	total: 93.4ms	remaining: 1.09s
79:	learn: 1.4510210	total: 94.4ms	remaining: 1.08s
80:	learn: 1.4395267	total: 95.5ms	remaining: 1.08s
81:	learn: 1.4332633	total: 96.7ms	remaining: 1.08s
82:	learn: 1.4271003	total: 97.7ms	remaining: 1.08s
83:	learn: 1.4182785	total: 98.9ms	remaining: 1.08s
84:	learn: 1.4059185	total: 101ms	remaining: 1.08s
85:	learn: 1.3968867	total: 102ms	remaining: 1.08s
86:	learn: 1.3851657	total: 103ms	remaining: 1.08s
87:	learn: 1.3711035	total: 104ms	remaining: 1.08s
88:	learn: 1.3599475	total: 105ms	remaining: 1.08s
89:	learn: 1.3525248	total: 107ms	remaining: 1.08s
90:	learn: 1.3476593	total: 108ms	remaining: 1.07s
91:	learn: 1.3390830	total: 109ms	remaining: 1.07s
92:	learn: 1.3327139	total: 110ms	remaining: 1.07s
93:	learn: 1.3250789	total: 111ms	remaining: 1.07s
94:	learn: 1.3153992	total: 112ms	remaining: 1.07s
95:	learn: 1.3098005	total: 113ms	remaining: 1.07s
96:	learn: 1.3047556	total: 115ms	remaining: 1.07s
97:	learn: 1.2964343	total: 116ms	remaining: 1.07s
98:	learn: 1.2830771	total: 118ms	remaining: 1.07s
99:	learn: 1.2798067	total: 119ms	remaining: 1.07s
100:	learn: 1.2755083	total: 120ms	remaining: 1.07s
101:	learn: 1.2688053	total: 121ms	remaining: 1.06s
102:	learn: 1.2662834	total: 122ms	remaining: 1.06s
103:	learn: 1.2561348	total: 123ms	remaining: 1.06s
104:	learn: 1.2470008	total: 124ms	remaining: 1.06s
105:	learn: 1.2455268	total: 125ms	remaining: 1.06s
106:	learn: 1.2421505	total: 126ms	remaining: 1.05s
107:	learn: 1.2361105	total: 128ms	remaining: 1.05s
108:	learn: 1.2330717	total: 129ms	remaining: 1.05s
109:	learn: 1.2261792	total: 130ms	remaining: 1.05s
110:	learn: 1.2161210	total: 131ms	remaining: 1.05s
111:	learn: 1.2117099	total: 133ms	remaining: 1.05s
112:	learn: 1.2065864	total: 134ms	remaining: 1.05s
113:	learn: 1.1975422	total: 135ms	remaining: 1.05s
114:	learn: 1.1950547	total: 136ms	remaining: 1.05s
115:	learn: 1.1902467	total: 137ms	remaining: 1.05s
116:	learn: 1.1881432	total: 138ms	remaining: 1.04s
117:	learn: 1.1796105	total: 140ms	remaining: 1.04s
118:	learn: 1.1763763	total: 141ms	remaining: 1.04s
119:	learn: 1.1689559	total: 142ms	remaining: 1.04s
120:	learn: 1.1638218	total: 143ms	remaining: 1.04s
121:	learn: 1.1596672	total: 144ms	remaining: 1.03s
122:	learn: 1.1580264	total: 145ms	remaining: 1.03s
123:	learn: 1.1509325	total: 147ms	remaining: 1.03s
124:	learn: 1.1437333	total: 148ms	remaining: 1.03s
125:	learn: 1.1347993	total: 149ms	remaining: 1.03s
126:	learn: 1.1282532	total: 150ms	remaining: 1.03s
127:	learn: 1.1226324	total: 152ms	remaining: 1.03s
128:	learn: 1.1172073	total: 153ms	remaining: 1.03s
129:	learn: 1.1147405	total: 154ms	remaining: 1.03s
130:	learn: 1.1131521	total: 156ms	remaining: 1.03s
131:	learn: 1.1115574	total: 157ms	remaining: 1.03s
132:	learn: 1.1041033	total: 158ms	remaining: 1.03s
133:	learn: 1.1009161	total: 159ms	remaining: 1.03s
134:	learn: 1.0980005	total: 160ms	remaining: 1.02s
135:	learn: 1.0892843	total: 161ms	remaining: 1.02s
136:	learn: 1.0849958	total: 163ms	remaining: 1.02s
137:	learn: 1.0823108	total: 164ms	remaining: 1.02s
138:	learn: 1.0786921	total: 165ms	remaining: 1.02s
139:	learn: 1.0751279	total: 166ms	remaining: 1.02s
140:	learn: 1.0711720	total: 168ms	remaining: 1.02s
141:	learn: 1.0698597	total: 168ms	remaining: 1.01s
142:	learn: 1.0662838	total: 169ms	remaining: 1.01s
143:	learn: 1.0576508	total: 170ms	remaining: 1.01s
144:	learn: 1.0521576	total: 171ms	remaining: 1.01s
145:	learn: 1.0475702	total: 172ms	remaining: 1.01s
146:	learn: 1.0412501	total: 174ms	remaining: 1.01s
147:	learn: 1.0375011	total: 175ms	remaining: 1s
148:	learn: 1.0363668	total: 176ms	remaining: 1s
149:	learn: 1.0325470	total: 177ms	remaining: 1s
150:	learn: 1.0309836	total: 178ms	remaining: 1s
151:	learn: 1.0268183	total: 180ms	remaining: 1s
152:	learn: 1.0228738	total: 181ms	remaining: 1s
153:	learn: 1.0178346	total: 183ms	remaining: 1s
154:	learn: 1.0094159	total: 185ms	remaining: 1.01s
155:	learn: 1.0059657	total: 186ms	remaining: 1.01s
156:	learn: 1.0030493	total: 187ms	remaining: 1s
157:	learn: 0.9988845	total: 188ms	remaining: 1s
158:	learn: 0.9942371	total: 189ms	remaining: 1s
159:	learn: 0.9913656	total: 190ms	remaining: 1000ms
160:	learn: 0.9869211	total: 192ms	remaining: 998ms
161:	learn: 0.9835033	total: 193ms	remaining: 997ms
162:	learn: 0.9779518	total: 194ms	remaining: 996ms
163:	learn: 0.9756380	total: 196ms	remaining: 997ms
164:	learn: 0.9717053	total: 197ms	remaining: 999ms
165:	learn: 0.9677737	total: 199ms	remaining: 1000ms
166:	learn: 0.9629038	total: 200ms	remaining: 999ms
167:	learn: 0.9605201	total: 202ms	remaining: 998ms
168:	learn: 0.9578389	total: 203ms	remaining: 997ms
169:	learn: 0.9523977	total: 204ms	remaining: 995ms
170:	learn: 0.9477531	total: 205ms	remaining: 995ms
171:	learn: 0.9447184	total: 206ms	remaining: 994ms
172:	learn: 0.9417334	total: 208ms	remaining: 994ms
173:	learn: 0.9380108	total: 209ms	remaining: 994ms
174:	learn: 0.9362415	total: 211ms	remaining: 995ms
175:	learn: 0.9345924	total: 212ms	remaining: 994ms
176:	learn: 0.9305366	total: 214ms	remaining: 993ms
177:	learn: 0.9277537	total: 215ms	remaining: 992ms
178:	learn: 0.9245596	total: 216ms	remaining: 991ms
179:	learn: 0.9233224	total: 217ms	remaining: 989ms
180:	learn: 0.9206115	total: 218ms	remaining: 987ms
181:	learn: 0.9182023	total: 219ms	remaining: 986ms
182:	learn: 0.9154257	total: 220ms	remaining: 984ms
183:	learn: 0.9135125	total: 221ms	remaining: 982ms
184:	learn: 0.9097184	total: 223ms	remaining: 980ms
185:	learn: 0.9068532	total: 224ms	remaining: 979ms
186:	learn: 0.9010518	total: 225ms	remaining: 979ms
187:	learn: 0.8955706	total: 227ms	remaining: 979ms
188:	learn: 0.8905866	total: 228ms	remaining: 978ms
189:	learn: 0.8870012	total: 229ms	remaining: 978ms
190:	learn: 0.8843375	total: 231ms	remaining: 977ms
191:	learn: 0.8812637	total: 232ms	remaining: 975ms
192:	learn: 0.8769832	total: 233ms	remaining: 975ms
193:	learn: 0.8760144	total: 234ms	remaining: 974ms
194:	learn: 0.8730763	total: 236ms	remaining: 973ms
195:	learn: 0.8701028	total: 237ms	remaining: 973ms
196:	learn: 0.8688926	total: 238ms	remaining: 972ms
197:	learn: 0.8683956	total: 241ms	remaining: 977ms
198:	learn: 0.8626024	total: 244ms	remaining: 982ms
199:	learn: 0.8600873	total: 247ms	remaining: 986ms
200:	learn: 0.8592423	total: 249ms	remaining: 990ms
201:	learn: 0.8555569	total: 252ms	remaining: 994ms
202:	learn: 0.8517341	total: 255ms	remaining: 999ms
203:	learn: 0.8498208	total: 256ms	remaining: 999ms
204:	learn: 0.8453506	total: 258ms	remaining: 1s
205:	learn: 0.8441718	total: 260ms	remaining: 1s
206:	learn: 0.8431877	total: 261ms	remaining: 1s
207:	learn: 0.8413346	total: 262ms	remaining: 998ms
208:	learn: 0.8384594	total: 263ms	remaining: 997ms
209:	learn: 0.8366411	total: 264ms	remaining: 995ms
210:	learn: 0.8350456	total: 266ms	remaining: 993ms
211:	learn: 0.8306137	total: 267ms	remaining: 991ms
212:	learn: 0.8301185	total: 268ms	remaining: 989ms
213:	learn: 0.8277794	total: 269ms	remaining: 988ms
214:	learn: 0.8233120	total: 270ms	remaining: 986ms
215:	learn: 0.8216865	total: 271ms	remaining: 984ms
216:	learn: 0.8195319	total: 272ms	remaining: 983ms
217:	learn: 0.8174362	total: 274ms	remaining: 981ms
218:	learn: 0.8152343	total: 275ms	remaining: 981ms
219:	learn: 0.8122887	total: 276ms	remaining: 979ms
220:	learn: 0.8071078	total: 277ms	remaining: 978ms
221:	learn: 0.8030560	total: 278ms	remaining: 976ms
222:	learn: 0.8022306	total: 280ms	remaining: 974ms
223:	learn: 0.8002873	total: 281ms	remaining: 973ms
224:	learn: 0.7985565	total: 282ms	remaining: 971ms
225:	learn: 0.7969538	total: 283ms	remaining: 969ms
226:	learn: 0.7926548	total: 284ms	remaining: 967ms
227:	learn: 0.7872331	total: 285ms	remaining: 966ms
228:	learn: 0.7844160	total: 286ms	remaining: 964ms
229:	learn: 0.7838825	total: 288ms	remaining: 965ms
230:	learn: 0.7818808	total: 291ms	remaining: 969ms
231:	learn: 0.7782399	total: 294ms	remaining: 972ms
232:	learn: 0.7757788	total: 296ms	remaining: 975ms
233:	learn: 0.7703858	total: 298ms	remaining: 976ms
234:	learn: 0.7689787	total: 301ms	remaining: 979ms
235:	learn: 0.7672436	total: 303ms	remaining: 981ms
236:	learn: 0.7656413	total: 306ms	remaining: 984ms
237:	learn: 0.7627470	total: 308ms	remaining: 986ms
238:	learn: 0.7610436	total: 310ms	remaining: 988ms
239:	learn: 0.7602614	total: 313ms	remaining: 990ms
240:	learn: 0.7550986	total: 315ms	remaining: 992ms
241:	learn: 0.7521417	total: 316ms	remaining: 991ms
242:	learn: 0.7504859	total: 317ms	remaining: 989ms
243:	learn: 0.7477018	total: 319ms	remaining: 987ms
244:	learn: 0.7433426	total: 320ms	remaining: 985ms
245:	learn: 0.7386833	total: 322ms	remaining: 987ms
246:	learn: 0.7346752	total: 323ms	remaining: 986ms
247:	learn: 0.7325306	total: 325ms	remaining: 985ms
248:	learn: 0.7300143	total: 326ms	remaining: 983ms
249:	learn: 0.7264197	total: 327ms	remaining: 981ms
250:	learn: 0.7232810	total: 328ms	remaining: 979ms
251:	learn: 0.7193129	total: 329ms	remaining: 977ms
252:	learn: 0.7183013	total: 330ms	remaining: 975ms
253:	learn: 0.7174059	total: 331ms	remaining: 973ms
254:	learn: 0.7133656	total: 332ms	remaining: 971ms
255:	learn: 0.7105394	total: 334ms	remaining: 970ms
256:	learn: 0.7091774	total: 335ms	remaining: 968ms
257:	learn: 0.7055424	total: 337ms	remaining: 968ms
258:	learn: 0.7012911	total: 338ms	remaining: 967ms
259:	learn: 0.7003989	total: 339ms	remaining: 965ms
260:	learn: 0.6967633	total: 340ms	remaining: 964ms
261:	learn: 0.6944281	total: 342ms	remaining: 962ms
262:	learn: 0.6904621	total: 343ms	remaining: 960ms
263:	learn: 0.6873047	total: 344ms	remaining: 958ms
264:	learn: 0.6852735	total: 345ms	remaining: 957ms
265:	learn: 0.6818626	total: 346ms	remaining: 955ms
266:	learn: 0.6808161	total: 347ms	remaining: 953ms
267:	learn: 0.6789380	total: 348ms	remaining: 951ms
268:	learn: 0.6753481	total: 349ms	remaining: 949ms
269:	learn: 0.6731359	total: 350ms	remaining: 947ms
270:	learn: 0.6694046	total: 352ms	remaining: 946ms
271:	learn: 0.6674323	total: 354ms	remaining: 946ms
272:	learn: 0.6653269	total: 355ms	remaining: 945ms
273:	learn: 0.6642673	total: 356ms	remaining: 943ms
274:	learn: 0.6624526	total: 357ms	remaining: 941ms
275:	learn: 0.6586996	total: 358ms	remaining: 940ms
276:	learn: 0.6582731	total: 359ms	remaining: 938ms
277:	learn: 0.6572626	total: 360ms	remaining: 936ms
278:	learn: 0.6530092	total: 362ms	remaining: 934ms
279:	learn: 0.6501548	total: 363ms	remaining: 933ms
280:	learn: 0.6485586	total: 364ms	remaining: 931ms
281:	learn: 0.6440325	total: 365ms	remaining: 929ms
282:	learn: 0.6421870	total: 366ms	remaining: 927ms
283:	learn: 0.6411295	total: 368ms	remaining: 928ms
284:	learn: 0.6382244	total: 370ms	remaining: 929ms
285:	learn: 0.6372172	total: 371ms	remaining: 927ms
286:	learn: 0.6363432	total: 373ms	remaining: 925ms
287:	learn: 0.6348729	total: 374ms	remaining: 924ms
288:	learn: 0.6330227	total: 375ms	remaining: 924ms
289:	learn: 0.6321849	total: 377ms	remaining: 922ms
290:	learn: 0.6313798	total: 378ms	remaining: 920ms
291:	learn: 0.6273136	total: 379ms	remaining: 919ms
292:	learn: 0.6236178	total: 380ms	remaining: 917ms
293:	learn: 0.6219552	total: 381ms	remaining: 916ms
294:	learn: 0.6202971	total: 384ms	remaining: 917ms
295:	learn: 0.6194558	total: 385ms	remaining: 916ms
296:	learn: 0.6185221	total: 386ms	remaining: 915ms
297:	learn: 0.6165148	total: 388ms	remaining: 913ms
298:	learn: 0.6142647	total: 389ms	remaining: 912ms
299:	learn: 0.6139278	total: 390ms	remaining: 910ms
300:	learn: 0.6122891	total: 391ms	remaining: 908ms
301:	learn: 0.6105012	total: 392ms	remaining: 907ms
302:	learn: 0.6088154	total: 394ms	remaining: 906ms
303:	learn: 0.6080189	total: 395ms	remaining: 905ms
304:	learn: 0.6070931	total: 396ms	remaining: 903ms
305:	learn: 0.6061623	total: 398ms	remaining: 902ms
306:	learn: 0.6046903	total: 399ms	remaining: 901ms
307:	learn: 0.6019525	total: 401ms	remaining: 901ms
308:	learn: 0.5993851	total: 403ms	remaining: 901ms
309:	learn: 0.5965759	total: 404ms	remaining: 900ms
310:	learn: 0.5961875	total: 406ms	remaining: 899ms
311:	learn: 0.5929000	total: 407ms	remaining: 898ms
312:	learn: 0.5921992	total: 408ms	remaining: 896ms
313:	learn: 0.5896289	total: 410ms	remaining: 895ms
314:	learn: 0.5888569	total: 411ms	remaining: 894ms
315:	learn: 0.5877775	total: 413ms	remaining: 893ms
316:	learn: 0.5866778	total: 414ms	remaining: 892ms
317:	learn: 0.5859144	total: 415ms	remaining: 891ms
318:	learn: 0.5834396	total: 417ms	remaining: 889ms
319:	learn: 0.5825789	total: 418ms	remaining: 887ms
320:	learn: 0.5798478	total: 419ms	remaining: 886ms
321:	learn: 0.5792653	total: 420ms	remaining: 884ms
322:	learn: 0.5783317	total: 421ms	remaining: 883ms
323:	learn: 0.5776443	total: 422ms	remaining: 882ms
324:	learn: 0.5741688	total: 424ms	remaining: 880ms
325:	learn: 0.5712458	total: 425ms	remaining: 880ms
326:	learn: 0.5680481	total: 427ms	remaining: 879ms
327:	learn: 0.5665114	total: 429ms	remaining: 878ms
328:	learn: 0.5649844	total: 430ms	remaining: 877ms
329:	learn: 0.5635556	total: 431ms	remaining: 876ms
330:	learn: 0.5633009	total: 433ms	remaining: 875ms
331:	learn: 0.5626499	total: 434ms	remaining: 873ms
332:	learn: 0.5609192	total: 435ms	remaining: 872ms
333:	learn: 0.5581417	total: 436ms	remaining: 870ms
334:	learn: 0.5567554	total: 438ms	remaining: 869ms
335:	learn: 0.5556000	total: 439ms	remaining: 868ms
336:	learn: 0.5542089	total: 441ms	remaining: 867ms
337:	learn: 0.5513434	total: 442ms	remaining: 866ms
338:	learn: 0.5503511	total: 443ms	remaining: 864ms
339:	learn: 0.5490439	total: 445ms	remaining: 863ms
340:	learn: 0.5465083	total: 446ms	remaining: 861ms
341:	learn: 0.5441085	total: 447ms	remaining: 860ms
342:	learn: 0.5421763	total: 448ms	remaining: 858ms
343:	learn: 0.5404745	total: 449ms	remaining: 857ms
344:	learn: 0.5386068	total: 450ms	remaining: 855ms
345:	learn: 0.5383334	total: 451ms	remaining: 853ms
346:	learn: 0.5377298	total: 453ms	remaining: 852ms
347:	learn: 0.5370959	total: 454ms	remaining: 851ms
348:	learn: 0.5364159	total: 455ms	remaining: 850ms
349:	learn: 0.5356428	total: 457ms	remaining: 849ms
350:	learn: 0.5334742	total: 458ms	remaining: 847ms
351:	learn: 0.5329031	total: 459ms	remaining: 846ms
352:	learn: 0.5308083	total: 461ms	remaining: 845ms
353:	learn: 0.5305419	total: 462ms	remaining: 843ms
354:	learn: 0.5291509	total: 463ms	remaining: 842ms
355:	learn: 0.5285989	total: 465ms	remaining: 840ms
356:	learn: 0.5283282	total: 466ms	remaining: 839ms
357:	learn: 0.5268414	total: 467ms	remaining: 838ms
358:	learn: 0.5253749	total: 468ms	remaining: 836ms
359:	learn: 0.5248729	total: 470ms	remaining: 835ms
360:	learn: 0.5225434	total: 471ms	remaining: 835ms
361:	learn: 0.5219392	total: 473ms	remaining: 834ms
362:	learn: 0.5205073	total: 474ms	remaining: 832ms
363:	learn: 0.5200408	total: 476ms	remaining: 831ms
364:	learn: 0.5193346	total: 477ms	remaining: 830ms
365:	learn: 0.5190851	total: 479ms	remaining: 829ms
366:	learn: 0.5164891	total: 480ms	remaining: 828ms
367:	learn: 0.5143724	total: 481ms	remaining: 826ms
368:	learn: 0.5132252	total: 483ms	remaining: 826ms
369:	learn: 0.5111019	total: 484ms	remaining: 825ms
370:	learn: 0.5105934	total: 486ms	remaining: 823ms
371:	learn: 0.5080399	total: 487ms	remaining: 823ms
372:	learn: 0.5068654	total: 489ms	remaining: 822ms
373:	learn: 0.5059924	total: 490ms	remaining: 820ms
374:	learn: 0.5043715	total: 491ms	remaining: 819ms
375:	learn: 0.5041217	total: 493ms	remaining: 818ms
376:	learn: 0.5017893	total: 494ms	remaining: 817ms
377:	learn: 0.5006333	total: 495ms	remaining: 815ms
378:	learn: 0.4991722	total: 497ms	remaining: 814ms
379:	learn: 0.4980498	total: 498ms	remaining: 812ms
380:	learn: 0.4971194	total: 499ms	remaining: 811ms

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fitting SVR for C2X_rhown_1x1_depth_lt_1
Fitting KNN for C2X_rhown_1x1_depth_lt_1
Fitting LR for C2X_rhown_1x1_depth_lt_1
Fitting RF for C2X_rhown_1x1_depth_lt_1
Fitting CAT for C2X_rhown_1x1_depth_lt_1
Learning rate set to 0.033272
0:	learn: 3.4177674	total: 1.83ms	remaining: 1.83s
1:	learn: 3.3755629	total: 3.08ms	remaining: 1.53s
2:	learn: 3.3295933	total: 5.8ms	remaining: 1.93s
3:	learn: 3.2955505	total: 7.29ms	remaining: 1.82s
4:	learn: 3.2510415	total: 8.7ms	remaining: 1.73s
5:	learn: 3.2171839	total: 10.1ms	remaining: 1.67s
6:	learn: 3.1798974	total: 11.4ms	remaining: 1.62s
7:	learn: 3.1470174	total: 12.7ms	remaining: 1.57s
8:	learn: 3.1096663	total: 14ms	remaining: 1.54s
9:	learn: 3.0774744	total: 15.3ms	remaining: 1.51s
10:	learn: 3.0475845	total: 16.6ms	remaining: 1.49s
11:	learn: 3.0158400	total: 17.8ms	remaining: 1.47s
12:	learn: 2.9785053	total: 20.4ms	remaining: 1.55s
13:	learn: 2.9469195	total: 21.9ms	remaining: 1.54s
14:	learn: 2.9116233	total: 23.4ms	remaining: 1.53s
15:	learn: 2.8778512	total: 24.8ms	remaining: 1.53s
16:	learn: 2.8511874	total: 26.4ms	remaining: 1.53s
17:	learn: 2.8247287	total: 27.8ms	remaining: 1.52s
18:	learn: 2.8014318	total: 29.1ms	remaining: 1.5s
19:	learn: 2.7686733	total: 30.9ms	remaining: 1.51s
20:	learn: 2.7328903	total: 32.2ms	remaining: 1.5s
21:	learn: 2.6987661	total: 33.5ms	remaining: 1.49s
22:	learn: 2.6709409	total: 34.7ms	remaining: 1.47s
23:	learn: 2.6439489	total: 36ms	remaining: 1.47s
24:	learn: 2.6209701	total: 37.5ms	remaining: 1.46s
25:	learn: 2.5905246	total: 38.9ms	remaining: 1.46s
26:	learn: 2.5673484	total: 40.2ms	remaining: 1.45s
27:	learn: 2.5471513	total: 41.8ms	remaining: 1.45s
28:	learn: 2.5276890	total: 43.1ms	remaining: 1.44s
29:	learn: 2.5062126	total: 44.4ms	remaining: 1.44s
30:	learn: 2.4821821	total: 45.7ms	remaining: 1.43s
31:	learn: 2.4589322	total: 46.9ms	remaining: 1.42s
32:	learn: 2.4280395	total: 48.2ms	remaining: 1.41s
33:	learn: 2.4074845	total: 49.6ms	remaining: 1.41s
34:	learn: 2.3842603	total: 50.9ms	remaining: 1.4s
35:	learn: 2.3654821	total: 53ms	remaining: 1.42s
36:	learn: 2.3502605	total: 54.4ms	remaining: 1.42s
37:	learn: 2.3244961	total: 55.7ms	remaining: 1.41s
38:	learn: 2.3004685	total: 57ms	remaining: 1.4s
39:	learn: 2.2841124	total: 58.3ms	remaining: 1.4s
40:	learn: 2.2657323	total: 59.5ms	remaining: 1.39s
41:	learn: 2.2568902	total: 60.8ms	remaining: 1.39s
42:	learn: 2.2390600	total: 62.1ms	remaining: 1.38s
43:	learn: 2.2265540	total: 63.4ms	remaining: 1.38s
44:	learn: 2.2121527	total: 64.6ms	remaining: 1.37s
45:	learn: 2.2010673	total: 65.9ms	remaining: 1.37s
46:	learn: 2.1813864	total: 67.2ms	remaining: 1.36s
47:	learn: 2.1639307	total: 68.7ms	remaining: 1.36s
48:	learn: 2.1487490	total: 70.1ms	remaining: 1.36s
49:	learn: 2.1336734	total: 72.9ms	remaining: 1.39s
50:	learn: 2.1184593	total: 75.3ms	remaining: 1.4s
51:	learn: 2.0973221	total: 76.7ms	remaining: 1.4s
52:	learn: 2.0886000	total: 78.1ms	remaining: 1.4s
53:	learn: 2.0653180	total: 79.4ms	remaining: 1.39s
54:	learn: 2.0464303	total: 80.9ms	remaining: 1.39s
55:	learn: 2.0336663	total: 82.6ms	remaining: 1.39s
56:	learn: 2.0197937	total: 84.3ms	remaining: 1.4s
57:	learn: 2.0042422	total: 86ms	remaining: 1.4s
58:	learn: 1.9909392	total: 87.5ms	remaining: 1.4s
59:	learn: 1.9782377	total: 88.8ms	remaining: 1.39s
60:	learn: 1.9669834	total: 89.9ms	remaining: 1.38s
61:	learn: 1.9567871	total: 91.2ms	remaining: 1.38s
62:	learn: 1.9462386	total: 92.4ms	remaining: 1.37s
63:	learn: 1.9383653	total: 93.6ms	remaining: 1.37s
64:	learn: 1.9249939	total: 94.8ms	remaining: 1.36s
65:	learn: 1.9091811	total: 96.1ms	remaining: 1.36s
66:	learn: 1.8992354	total: 97.9ms	remaining: 1.36s
67:	learn: 1.8895788	total: 99.7ms	remaining: 1.37s
68:	learn: 1.8789257	total: 101ms	remaining: 1.37s
69:	learn: 1.8644388	total: 103ms	remaining: 1.36s
70:	learn: 1.8539064	total: 104ms	remaining: 1.36s
71:	learn: 1.8446326	total: 105ms	remaining: 1.36s
72:	learn: 1.8368363	total: 107ms	remaining: 1.36s
73:	learn: 1.8197063	total: 108ms	remaining: 1.36s
74:	learn: 1.8117657	total: 110ms	remaining: 1.35s
75:	learn: 1.7995366	total: 111ms	remaining: 1.35s
76:	learn: 1.7865832	total: 113ms	remaining: 1.35s
77:	learn: 1.7798577	total: 114ms	remaining: 1.35s
78:	learn: 1.7738078	total: 116ms	remaining: 1.35s
79:	learn: 1.7601962	total: 117ms	remaining: 1.34s
80:	learn: 1.7514701	total: 118ms	remaining: 1.34s
81:	learn: 1.7399525	total: 119ms	remaining: 1.33s
82:	learn: 1.7361105	total: 120ms	remaining: 1.33s
83:	learn: 1.7250272	total: 121ms	remaining: 1.32s
84:	learn: 1.7134030	total: 122ms	remaining: 1.32s
85:	learn: 1.7005519	total: 123ms	remaining: 1.31s
86:	learn: 1.6870178	total: 125ms	remaining: 1.31s
87:	learn: 1.6729315	total: 126ms	remaining: 1.3s
88:	learn: 1.6584319	total: 127ms	remaining: 1.3s
89:	learn: 1.6472959	total: 128ms	remaining: 1.3s
90:	learn: 1.6403679	total: 130ms	remaining: 1.3s
91:	learn: 1.6376694	total: 131ms	remaining: 1.29s
92:	learn: 1.6269097	total: 132ms	remaining: 1.29s
93:	learn: 1.6189288	total: 134ms	remaining: 1.29s
94:	learn: 1.6120316	total: 135ms	remaining: 1.29s
95:	learn: 1.6034181	total: 136ms	remaining: 1.28s
96:	learn: 1.5959812	total: 137ms	remaining: 1.28s
97:	learn: 1.5885098	total: 139ms	remaining: 1.28s
98:	learn: 1.5832117	total: 140ms	remaining: 1.27s
99:	learn: 1.5755955	total: 141ms	remaining: 1.27s
100:	learn: 1.5714926	total: 143ms	remaining: 1.27s
101:	learn: 1.5645206	total: 144ms	remaining: 1.27s
102:	learn: 1.5488514	total: 145ms	remaining: 1.26s
103:	learn: 1.5423611	total: 146ms	remaining: 1.26s
104:	learn: 1.5255031	total: 148ms	remaining: 1.26s
105:	learn: 1.5157908	total: 149ms	remaining: 1.26s
106:	learn: 1.5100008	total: 151ms	remaining: 1.26s
107:	learn: 1.5043633	total: 152ms	remaining: 1.25s
108:	learn: 1.4964439	total: 153ms	remaining: 1.25s
109:	learn: 1.4934694	total: 154ms	remaining: 1.25s
110:	learn: 1.4858738	total: 155ms	remaining: 1.24s
111:	learn: 1.4736584	total: 156ms	remaining: 1.24s
112:	learn: 1.4644295	total: 157ms	remaining: 1.24s
113:	learn: 1.4539724	total: 159ms	remaining: 1.23s
114:	learn: 1.4441787	total: 160ms	remaining: 1.23s
115:	learn: 1.4391893	total: 161ms	remaining: 1.23s
116:	learn: 1.4327661	total: 162ms	remaining: 1.22s
117:	learn: 1.4286807	total: 164ms	remaining: 1.22s
118:	learn: 1.4246895	total: 165ms	remaining: 1.22s
119:	learn: 1.4131618	total: 166ms	remaining: 1.22s
120:	learn: 1.4080695	total: 167ms	remaining: 1.21s
121:	learn: 1.3999204	total: 168ms	remaining: 1.21s
122:	learn: 1.3939268	total: 169ms	remaining: 1.21s
123:	learn: 1.3857983	total: 170ms	remaining: 1.2s
124:	learn: 1.3793472	total: 172ms	remaining: 1.2s
125:	learn: 1.3740059	total: 173ms	remaining: 1.2s
126:	learn: 1.3705664	total: 174ms	remaining: 1.19s
127:	learn: 1.3683115	total: 175ms	remaining: 1.19s
128:	learn: 1.3646239	total: 177ms	remaining: 1.2s
129:	learn: 1.3616274	total: 179ms	remaining: 1.2s
130:	learn: 1.3505152	total: 181ms	remaining: 1.2s
131:	learn: 1.3408596	total: 182ms	remaining: 1.2s
132:	learn: 1.3378275	total: 184ms	remaining: 1.2s
133:	learn: 1.3357368	total: 185ms	remaining: 1.19s
134:	learn: 1.3306551	total: 186ms	remaining: 1.19s
135:	learn: 1.3277254	total: 187ms	remaining: 1.19s
136:	learn: 1.3246115	total: 189ms	remaining: 1.19s
137:	learn: 1.3201340	total: 190ms	remaining: 1.19s
138:	learn: 1.3168859	total: 191ms	remaining: 1.19s
139:	learn: 1.3147010	total: 193ms	remaining: 1.19s
140:	learn: 1.3119816	total: 195ms	remaining: 1.19s
141:	learn: 1.3087156	total: 196ms	remaining: 1.19s
142:	learn: 1.3025504	total: 198ms	remaining: 1.19s
143:	learn: 1.2987918	total: 199ms	remaining: 1.18s
144:	learn: 1.2967608	total: 201ms	remaining: 1.18s
145:	learn: 1.2873089	total: 202ms	remaining: 1.18s
146:	learn: 1.2838482	total: 203ms	remaining: 1.18s
147:	learn: 1.2760776	total: 204ms	remaining: 1.18s
148:	learn: 1.2745647	total: 206ms	remaining: 1.18s
149:	learn: 1.2624571	total: 207ms	remaining: 1.17s
150:	learn: 1.2569253	total: 209ms	remaining: 1.17s
151:	learn: 1.2548094	total: 210ms	remaining: 1.17s
152:	learn: 1.2458957	total: 212ms	remaining: 1.17s
153:	learn: 1.2435441	total: 213ms	remaining: 1.17s
154:	learn: 1.2418573	total: 216ms	remaining: 1.18s
155:	learn: 1.2344634	total: 220ms	remaining: 1.19s
156:	learn: 1.2304654	total: 222ms	remaining: 1.19s
157:	learn: 1.2252497	total: 226ms	remaining: 1.2s
158:	learn: 1.2177475	total: 228ms	remaining: 1.21s
159:	learn: 1.2078387	total: 230ms	remaining: 1.21s
160:	learn: 1.2009597	total: 232ms	remaining: 1.21s
161:	learn: 1.1945684	total: 233ms	remaining: 1.2s
162:	learn: 1.1925760	total: 234ms	remaining: 1.2s
163:	learn: 1.1836010	total: 236ms	remaining: 1.2s
164:	learn: 1.1811882	total: 237ms	remaining: 1.2s
165:	learn: 1.1796343	total: 238ms	remaining: 1.2s
166:	learn: 1.1739965	total: 240ms	remaining: 1.2s
167:	learn: 1.1724849	total: 241ms	remaining: 1.19s
168:	learn: 1.1712333	total: 242ms	remaining: 1.19s
169:	learn: 1.1684849	total: 244ms	remaining: 1.19s
170:	learn: 1.1673381	total: 246ms	remaining: 1.19s
171:	learn: 1.1620320	total: 247ms	remaining: 1.19s
172:	learn: 1.1538502	total: 248ms	remaining: 1.19s
173:	learn: 1.1508054	total: 250ms	remaining: 1.18s
174:	learn: 1.1441563	total: 251ms	remaining: 1.18s
175:	learn: 1.1409469	total: 252ms	remaining: 1.18s
176:	learn: 1.1345190	total: 254ms	remaining: 1.18s
177:	learn: 1.1316410	total: 255ms	remaining: 1.18s
178:	learn: 1.1306011	total: 256ms	remaining: 1.18s
179:	learn: 1.1268337	total: 258ms	remaining: 1.17s
180:	learn: 1.1226178	total: 259ms	remaining: 1.17s
181:	learn: 1.1216314	total: 260ms	remaining: 1.17s
182:	learn: 1.1182895	total: 262ms	remaining: 1.17s
183:	learn: 1.1173109	total: 263ms	remaining: 1.17s
184:	learn: 1.1136985	total: 265ms	remaining: 1.17s
185:	learn: 1.1064947	total: 266ms	remaining: 1.17s
186:	learn: 1.1040527	total: 268ms	remaining: 1.17s
187:	learn: 1.1031379	total: 270ms	remaining: 1.16s
188:	learn: 1.1020919	total: 271ms	remaining: 1.16s
189:	learn: 1.0975001	total: 272ms	remaining: 1.16s
190:	learn: 1.0966601	total: 273ms	remaining: 1.16s
191:	learn: 1.0872517	total: 274ms	remaining: 1.15s
192:	learn: 1.0848562	total: 276ms	remaining: 1.15s
193:	learn: 1.0790317	total: 277ms	remaining: 1.15s
194:	learn: 1.0781943	total: 278ms	remaining: 1.15s
195:	learn: 1.0755395	total: 280ms	remaining: 1.15s
196:	learn: 1.0731131	total: 282ms	remaining: 1.15s
197:	learn: 1.0716798	total: 283ms	remaining: 1.15s
198:	learn: 1.0686812	total: 284ms	remaining: 1.14s
199:	learn: 1.0672829	total: 286ms	remaining: 1.14s
200:	learn: 1.0660937	total: 287ms	remaining: 1.14s
201:	learn: 1.0653425	total: 288ms	remaining: 1.14s
202:	learn: 1.0605788	total: 289ms	remaining: 1.14s
203:	learn: 1.0582852	total: 290ms	remaining: 1.13s
204:	learn: 1.0529165	total: 292ms	remaining: 1.13s
205:	learn: 1.0441819	total: 293ms	remaining: 1.13s
206:	learn: 1.0433599	total: 294ms	remaining: 1.13s
207:	learn: 1.0383066	total: 296ms	remaining: 1.13s
208:	learn: 1.0283110	total: 297ms	remaining: 1.12s
209:	learn: 1.0208466	total: 299ms	remaining: 1.12s
210:	learn: 1.0147362	total: 300ms	remaining: 1.12s
211:	learn: 1.0082881	total: 302ms	remaining: 1.12s
212:	learn: 1.0046140	total: 303ms	remaining: 1.12s
213:	learn: 1.0035285	total: 304ms	remaining: 1.12s
214:	learn: 0.9960557	total: 305ms	remaining: 1.11s
215:	learn: 0.9928455	total: 307ms	remaining: 1.11s
216:	learn: 0.9862333	total: 309ms	remaining: 1.11s
217:	learn: 0.9813888	total: 310ms	remaining: 1.11s
218:	learn: 0.9754397	total: 312ms	remaining: 1.11s
219:	learn: 0.9685550	total: 313ms	remaining: 1.11s
220:	learn: 0.9602534	total: 315ms	remaining: 1.11s
221:	learn: 0.9570156	total: 316ms	remaining: 1.11s
222:	learn: 0.9526582	total: 317ms	remaining: 1.1s
223:	learn: 0.9444066	total: 318ms	remaining: 1.1s
224:	learn: 0.9396084	total: 320ms	remaining: 1.1s
225:	learn: 0.9293585	total: 321ms	remaining: 1.1s
226:	learn: 0.9222574	total: 322ms	remaining: 1.1s
227:	learn: 0.9189407	total: 324ms	remaining: 1.1s
228:	learn: 0.9138068	total: 325ms	remaining: 1.09s
229:	learn: 0.9106315	total: 327ms	remaining: 1.09s
230:	learn: 0.9092574	total: 328ms	remaining: 1.09s
231:	learn: 0.9045836	total: 329ms	remaining: 1.09s
232:	learn: 0.8960693	total: 330ms	remaining: 1.09s
233:	learn: 0.8953378	total: 331ms	remaining: 1.08s
234:	learn: 0.8928105	total: 333ms	remaining: 1.08s
235:	learn: 0.8833037	total: 334ms	remaining: 1.08s
236:	learn: 0.8817760	total: 335ms	remaining: 1.08s
237:	learn: 0.8758085	total: 336ms	remaining: 1.08s
238:	learn: 0.8712861	total: 338ms	remaining: 1.07s
239:	learn: 0.8639001	total: 339ms	remaining: 1.07s
240:	learn: 0.8597572	total: 340ms	remaining: 1.07s
241:	learn: 0.8562215	total: 342ms	remaining: 1.07s
242:	learn: 0.8517875	total: 343ms	remaining: 1.07s
243:	learn: 0.8475949	total: 344ms	remaining: 1.07s
244:	learn: 0.8470531	total: 345ms	remaining: 1.06s
245:	learn: 0.8463115	total: 347ms	remaining: 1.06s
246:	learn: 0.8420729	total: 348ms	remaining: 1.06s
247:	learn: 0.8349019	total: 349ms	remaining: 1.06s
248:	learn: 0.8343324	total: 350ms	remaining: 1.06s
249:	learn: 0.8335502	total: 352ms	remaining: 1.05s
250:	learn: 0.8327143	total: 353ms	remaining: 1.05s
251:	learn: 0.8319804	total: 354ms	remaining: 1.05s
252:	learn: 0.8250517	total: 356ms	remaining: 1.05s
253:	learn: 0.8194656	total: 357ms	remaining: 1.05s
254:	learn: 0.8177920	total: 359ms	remaining: 1.05s
255:	learn: 0.8167924	total: 361ms	remaining: 1.05s
256:	learn: 0.8133551	total: 362ms	remaining: 1.05s
257:	learn: 0.8125138	total: 363ms	remaining: 1.04s
258:	learn: 0.8076036	total: 364ms	remaining: 1.04s
259:	learn: 0.8053719	total: 366ms	remaining: 1.04s
260:	learn: 0.7998167	total: 367ms	remaining: 1.04s
261:	learn: 0.7969569	total: 368ms	remaining: 1.04s
262:	learn: 0.7956038	total: 370ms	remaining: 1.04s
263:	learn: 0.7942947	total: 372ms	remaining: 1.04s
264:	learn: 0.7911058	total: 373ms	remaining: 1.03s
265:	learn: 0.7902236	total: 375ms	remaining: 1.03s
266:	learn: 0.7876391	total: 376ms	remaining: 1.03s
267:	learn: 0.7860753	total: 378ms	remaining: 1.03s
268:	learn: 0.7831980	total: 379ms	remaining: 1.03s
269:	learn: 0.7759005	total: 380ms	remaining: 1.03s
270:	learn: 0.7711668	total: 382ms	remaining: 1.03s
271:	learn: 0.7652893	total: 383ms	remaining: 1.02s
272:	learn: 0.7623783	total: 384ms	remaining: 1.02s
273:	learn: 0.7617806	total: 386ms	remaining: 1.02s
274:	learn: 0.7569491	total: 387ms	remaining: 1.02s
275:	learn: 0.7524075	total: 389ms	remaining: 1.02s
276:	learn: 0.7511624	total: 390ms	remaining: 1.02s
277:	learn: 0.7483907	total: 391ms	remaining: 1.02s
278:	learn: 0.7471504	total: 393ms	remaining: 1.01s
279:	learn: 0.7422395	total: 394ms	remaining: 1.01s
280:	learn: 0.7392331	total: 396ms	remaining: 1.01s
281:	learn: 0.7353601	total: 397ms	remaining: 1.01s
282:	learn: 0.7302224	total: 399ms	remaining: 1.01s
283:	learn: 0.7275361	total: 400ms	remaining: 1.01s
284:	learn: 0.7258541	total: 401ms	remaining: 1.01s
285:	learn: 0.7254785	total: 403ms	remaining: 1s
286:	learn: 0.7204340	total: 404ms	remaining: 1s
287:	learn: 0.7192181	total: 406ms	remaining: 1s
288:	learn: 0.7152833	total: 407ms	remaining: 1s
289:	learn: 0.7105348	total: 408ms	remaining: 999ms
290:	learn: 0.7096734	total: 409ms	remaining: 998ms
291:	learn: 0.7061573	total: 411ms	remaining: 996ms
292:	learn: 0.7050149	total: 412ms	remaining: 995ms
293:	learn: 0.7010699	total: 414ms	remaining: 994ms
294:	learn: 0.6986607	total: 415ms	remaining: 992ms
295:	learn: 0.6963906	total: 417ms	remaining: 991ms
296:	learn: 0.6956767	total: 418ms	remaining: 989ms
297:	learn: 0.6931481	total: 419ms	remaining: 987ms
298:	learn: 0.6914793	total: 420ms	remaining: 986ms
299:	learn: 0.6910357	total: 422ms	remaining: 984ms
300:	learn: 0.6907416	total: 423ms	remaining: 982ms
301:	learn: 0.6848146	total: 424ms	remaining: 981ms
302:	learn: 0.6791930	total: 426ms	remaining: 979ms
303:	learn: 0.6736691	total: 427ms	remaining: 978ms
304:	learn: 0.6707616	total: 429ms	remaining: 977ms
305:	learn: 0.6674331	total: 430ms	remaining: 975ms
306:	learn: 0.6665226	total: 431ms	remaining: 974ms
307:	learn: 0.6658962	total: 433ms	remaining: 972ms
308:	learn: 0.6649804	total: 434ms	remaining: 970ms
309:	learn: 0.6597687	total: 435ms	remaining: 968ms
310:	learn: 0.6562965	total: 436ms	remaining: 967ms
311:	learn: 0.6556548	total: 438ms	remaining: 965ms
312:	learn: 0.6553545	total: 439ms	remaining: 963ms
313:	learn: 0.6550340	total: 440ms	remaining: 961ms
314:	learn: 0.6547106	total: 441ms	remaining: 960ms
315:	learn: 0.6542182	total: 443ms	remaining: 958ms
316:	learn: 0.6521983	total: 444ms	remaining: 957ms
317:	learn: 0.6516973	total: 446ms	remaining: 956ms
318:	learn: 0.6469872	total: 447ms	remaining: 954ms
319:	learn: 0.6467027	total: 448ms	remaining: 952ms
320:	learn: 0.6462327	total: 449ms	remaining: 950ms
321:	learn: 0.6438678	total: 451ms	remaining: 949ms
322:	learn: 0.6434122	total: 452ms	remaining: 947ms
323:	learn: 0.6397556	total: 453ms	remaining: 945ms
324:	learn: 0.6371525	total: 454ms	remaining: 943ms
325:	learn: 0.6341830	total: 455ms	remaining: 941ms
326:	learn: 0.6334862	total: 457ms	remaining: 940ms
327:	learn: 0.6319739	total: 458ms	remaining: 939ms
328:	learn: 0.6316990	total: 460ms	remaining: 938ms
329:	learn: 0.6286001	total: 461ms	remaining: 936ms
330:	learn: 0.6283392	total: 462ms	remaining: 935ms
331:	learn: 0.6256192	total: 464ms	remaining: 933ms
332:	learn: 0.6252057	total: 465ms	remaining: 931ms
333:	learn: 0.6205026	total: 466ms	remaining: 930ms
334:	learn: 0.6160751	total: 467ms	remaining: 928ms
335:	learn: 0.6129547	total: 469ms	remaining: 926ms
336:	learn: 0.6125127	total: 470ms	remaining: 925ms
337:	learn: 0.6122338	total: 471ms	remaining: 923ms
338:	learn: 0.6119253	total: 473ms	remaining: 923ms
339:	learn: 0.6077537	total: 475ms	remaining: 922ms
340:	learn: 0.6043991	total: 476ms	remaining: 920ms
341:	learn: 0.6016803	total: 478ms	remaining: 919ms
342:	learn: 0.5989824	total: 479ms	remaining: 917ms
343:	learn: 0.5965454	total: 480ms	remaining: 916ms
344:	learn: 0.5932581	total: 482ms	remaining: 914ms
345:	learn: 0.5926157	total: 483ms	remaining: 913ms
346:	learn: 0.5922344	total: 485ms	remaining: 912ms
347:	learn: 0.5897146	total: 486ms	remaining: 911ms
348:	learn: 0.5894743	total: 488ms	remaining: 910ms
349:	learn: 0.5890759	total: 489ms	remaining: 909ms
350:	learn: 0.5888429	total: 491ms	remaining: 907ms
351:	learn: 0.5884827	total: 492ms	remaining: 906ms
352:	learn: 0.5869195	total: 493ms	remaining: 904ms
353:	learn: 0.5837056	total: 495ms	remaining: 903ms
354:	learn: 0.5831503	total: 496ms	remaining: 901ms
355:	learn: 0.5800954	total: 497ms	remaining: 900ms
356:	learn: 0.5784499	total: 499ms	remaining: 898ms
357:	learn: 0.5768336	total: 500ms	remaining: 897ms
358:	learn: 0.5764797	total: 501ms	remaining: 895ms
359:	learn: 0.5759529	total: 503ms	remaining: 895ms
360:	learn: 0.5738081	total: 505ms	remaining: 893ms
361:	learn: 0.5710629	total: 506ms	remaining: 892ms
362:	learn: 0.5699260	total: 507ms	remaining: 890ms
363:	learn: 0.5668534	total: 509ms	remaining: 889ms
364:	learn: 0.5659231	total: 510ms	remaining: 887ms
365:	learn: 0.5655836	total: 511ms	remaining: 886ms
366:	learn: 0.5652538	total: 513ms	remaining: 884ms
367:	learn: 0.5624838	total: 514ms	remaining: 882ms
368:	learn: 0.5602754	total: 515ms	remaining: 881ms
369:	learn: 0.5597749	total: 516ms	remaining: 879ms
370:	learn: 0.5578924	total: 518ms	remaining: 878ms
371:	learn: 0.5566301	total: 519ms	remaining: 877ms
372:	learn: 0.5539217	total: 521ms	remaining: 875ms
373:	learn: 0.5534912	total: 522ms	remaining: 874ms
374:	learn: 0.5504828	total: 524ms	remaining: 873ms
375:	learn: 0.5484904	total: 525ms	remaining: 871ms
376:	learn: 0.5470356	total: 526ms	remaining: 870ms
377:	learn: 0.5439964	total: 528ms	remaining: 868ms
378:	learn: 0.5432584	total: 529ms	remaining: 867ms
379:	learn: 0.5404244	total: 531ms	remaining: 866ms
380:	learn: 0.5394597	total: 533ms	remaining: 865ms
381:	learn: 0.5369888	total: 534ms	remaining: 864ms

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fitting SVR for C2RCC_rhown_9x9_depth_lt_1
Fitting KNN for C2RCC_rhown_9x9_depth_lt_1
Fitting LR for C2RCC_rhown_9x9_depth_lt_1
Fitting RF for C2RCC_rhown_9x9_depth_lt_1
Fitting CAT for C2RCC_rhown_9x9_depth_lt_1
Learning rate set to 0.033272
0:	learn: 3.4077335	total: 1.62ms	remaining: 1.62s
1:	learn: 3.3602182	total: 2.7ms	remaining: 1.35s
2:	learn: 3.3127479	total: 3.85ms	remaining: 1.28s
3:	learn: 3.2678320	total: 5.08ms	remaining: 1.26s
4:	learn: 3.2193709	total: 6.25ms	remaining: 1.24s
5:	learn: 3.1627098	total: 7.4ms	remaining: 1.23s
6:	learn: 3.1240892	total: 8.58ms	remaining: 1.22s
7:	learn: 3.0827965	total: 9.63ms	remaining: 1.19s
8:	learn: 3.0328200	total: 10.8ms	remaining: 1.18s
9:	learn: 2.9701785	total: 11.9ms	remaining: 1.17s
10:	learn: 2.9223436	total: 12.9ms	remaining: 1.16s
11:	learn: 2.8904881	total: 14ms	remaining: 1.15s
12:	learn: 2.8360117	total: 15.1ms	remaining: 1.15s
13:	learn: 2.7956010	total: 16.3ms	remaining: 1.14s
14:	learn: 2.7512028	total: 17.4ms	remaining: 1.14s
15:	learn: 2.7182360	total: 18.5ms	remaining: 1.14s
16:	learn: 2.6692602	total: 20.4ms	remaining: 1.18s
17:	learn: 2.6231604	total: 21.6ms	remaining: 1.18s
18:	learn: 2.5923118	total: 22.7ms	remaining: 1.17s
19:	learn: 2.5553084	total: 23.8ms	remaining: 1.17s
20:	learn: 2.5124142	total: 24.9ms	remaining: 1.16s
21:	learn: 2.4815810	total: 26.1ms	remaining: 1.16s
22:	learn: 2.4415850	total: 27.2ms	remaining: 1.15s
23:	learn: 2.4046826	total: 28.2ms	remaining: 1.15s
24:	learn: 2.3694390	total: 29.3ms	remaining: 1.14s
25:	learn: 2.3385219	total: 30.4ms	remaining: 1.14s
26:	learn: 2.3078414	total: 31.5ms	remaining: 1.13s
27:	learn: 2.2770872	total: 32.5ms	remaining: 1.13s
28:	learn: 2.2494899	total: 33.6ms	remaining: 1.12s
29:	learn: 2.2254047	total: 34.6ms	remaining: 1.12s
30:	learn: 2.1970761	total: 36.3ms	remaining: 1.14s
31:	learn: 2.1644211	total: 37.5ms	remaining: 1.13s
32:	learn: 2.1273589	total: 38.6ms	remaining: 1.13s
33:	learn: 2.1027018	total: 39.8ms	remaining: 1.13s
34:	learn: 2.0676096	total: 40.8ms	remaining: 1.13s
35:	learn: 2.0489835	total: 42ms	remaining: 1.12s
36:	learn: 2.0240260	total: 43.1ms	remaining: 1.12s
37:	learn: 1.9949671	total: 44.1ms	remaining: 1.12s
38:	learn: 1.9721415	total: 45.2ms	remaining: 1.11s
39:	learn: 1.9462647	total: 46.3ms	remaining: 1.11s
40:	learn: 1.9245029	total: 47.3ms	remaining: 1.11s
41:	learn: 1.9047529	total: 48.4ms	remaining: 1.1s
42:	learn: 1.8840295	total: 49.5ms	remaining: 1.1s
43:	learn: 1.8654642	total: 50.6ms	remaining: 1.1s
44:	learn: 1.8455083	total: 52.3ms	remaining: 1.11s
45:	learn: 1.8193007	total: 53.5ms	remaining: 1.11s
46:	learn: 1.8041495	total: 54.6ms	remaining: 1.11s
47:	learn: 1.7889725	total: 55.8ms	remaining: 1.11s
48:	learn: 1.7721915	total: 56.9ms	remaining: 1.1s
49:	learn: 1.7513851	total: 57.9ms	remaining: 1.1s
50:	learn: 1.7284559	total: 59ms	remaining: 1.1s
51:	learn: 1.7086720	total: 60.1ms	remaining: 1.09s
52:	learn: 1.6911873	total: 61.1ms	remaining: 1.09s
53:	learn: 1.6764319	total: 62.3ms	remaining: 1.09s
54:	learn: 1.6564770	total: 63.3ms	remaining: 1.09s
55:	learn: 1.6377491	total: 64.4ms	remaining: 1.08s
56:	learn: 1.6221738	total: 65.5ms	remaining: 1.08s
57:	learn: 1.6033613	total: 67.2ms	remaining: 1.09s
58:	learn: 1.5868535	total: 68.7ms	remaining: 1.09s
59:	learn: 1.5666784	total: 70.3ms	remaining: 1.1s
60:	learn: 1.5580304	total: 70.9ms	remaining: 1.09s
61:	learn: 1.5475726	total: 72.2ms	remaining: 1.09s
62:	learn: 1.5309815	total: 73.4ms	remaining: 1.09s
63:	learn: 1.5161647	total: 74.5ms	remaining: 1.09s
64:	learn: 1.5047037	total: 75.8ms	remaining: 1.09s
65:	learn: 1.4972284	total: 77ms	remaining: 1.09s
66:	learn: 1.4849810	total: 78ms	remaining: 1.09s
67:	learn: 1.4720416	total: 79.1ms	remaining: 1.08s
68:	learn: 1.4594053	total: 80.2ms	remaining: 1.08s
69:	learn: 1.4523525	total: 81.4ms	remaining: 1.08s
70:	learn: 1.4387848	total: 82.7ms	remaining: 1.08s
71:	learn: 1.4221812	total: 84.1ms	remaining: 1.08s
72:	learn: 1.4114128	total: 85.5ms	remaining: 1.08s
73:	learn: 1.4005656	total: 86.6ms	remaining: 1.08s
74:	learn: 1.3921060	total: 87.8ms	remaining: 1.08s
75:	learn: 1.3800262	total: 88.9ms	remaining: 1.08s
76:	learn: 1.3690696	total: 90ms	remaining: 1.08s
77:	learn: 1.3644792	total: 91.1ms	remaining: 1.08s
78:	learn: 1.3594730	total: 91.8ms	remaining: 1.07s
79:	learn: 1.3555272	total: 92.8ms	remaining: 1.07s
80:	learn: 1.3469353	total: 93.9ms	remaining: 1.06s
81:	learn: 1.3354809	total: 94.9ms	remaining: 1.06s
82:	learn: 1.3231396	total: 96ms	remaining: 1.06s
83:	learn: 1.3111242	total: 97.1ms	remaining: 1.06s
84:	learn: 1.3051715	total: 98.6ms	remaining: 1.06s
85:	learn: 1.3007567	total: 99.8ms	remaining: 1.06s
86:	learn: 1.2875178	total: 101ms	remaining: 1.06s
87:	learn: 1.2833242	total: 103ms	remaining: 1.06s
88:	learn: 1.2758709	total: 104ms	remaining: 1.06s
89:	learn: 1.2718910	total: 105ms	remaining: 1.06s
90:	learn: 1.2630221	total: 106ms	remaining: 1.06s
91:	learn: 1.2595059	total: 107ms	remaining: 1.05s
92:	learn: 1.2557650	total: 108ms	remaining: 1.05s
93:	learn: 1.2519857	total: 109ms	remaining: 1.05s
94:	learn: 1.2502540	total: 110ms	remaining: 1.05s
95:	learn: 1.2415356	total: 111ms	remaining: 1.05s
96:	learn: 1.2377533	total: 112ms	remaining: 1.04s
97:	learn: 1.2346491	total: 114ms	remaining: 1.04s
98:	learn: 1.2289033	total: 115ms	remaining: 1.04s
99:	learn: 1.2242208	total: 116ms	remaining: 1.04s
100:	learn: 1.2160337	total: 117ms	remaining: 1.04s
101:	learn: 1.2137699	total: 119ms	remaining: 1.04s
102:	learn: 1.2035089	total: 120ms	remaining: 1.04s
103:	learn: 1.1990522	total: 121ms	remaining: 1.04s
104:	learn: 1.1904359	total: 122ms	remaining: 1.04s
105:	learn: 1.1875560	total: 123ms	remaining: 1.04s
106:	learn: 1.1810741	total: 124ms	remaining: 1.03s
107:	learn: 1.1784132	total: 125ms	remaining: 1.03s
108:	learn: 1.1677435	total: 126ms	remaining: 1.03s
109:	learn: 1.1647779	total: 128ms	remaining: 1.03s
110:	learn: 1.1627798	total: 129ms	remaining: 1.03s
111:	learn: 1.1618752	total: 129ms	remaining: 1.02s
112:	learn: 1.1607256	total: 130ms	remaining: 1.02s
113:	learn: 1.1547212	total: 131ms	remaining: 1.02s
114:	learn: 1.1502691	total: 133ms	remaining: 1.03s
115:	learn: 1.1475326	total: 135ms	remaining: 1.02s
116:	learn: 1.1457393	total: 135ms	remaining: 1.02s
117:	learn: 1.1428623	total: 136ms	remaining: 1.02s
118:	learn: 1.1394714	total: 137ms	remaining: 1.02s
119:	learn: 1.1331253	total: 139ms	remaining: 1.02s
120:	learn: 1.1285689	total: 140ms	remaining: 1.01s
121:	learn: 1.1258485	total: 141ms	remaining: 1.01s
122:	learn: 1.1251414	total: 141ms	remaining: 1s
123:	learn: 1.1228993	total: 142ms	remaining: 1s
124:	learn: 1.1208501	total: 143ms	remaining: 1s
125:	learn: 1.1185909	total: 144ms	remaining: 1s
126:	learn: 1.1154374	total: 146ms	remaining: 1s
127:	learn: 1.1072088	total: 147ms	remaining: 1s
128:	learn: 1.1039107	total: 149ms	remaining: 1.01s
129:	learn: 1.1016888	total: 151ms	remaining: 1.01s
130:	learn: 1.0982482	total: 152ms	remaining: 1s
131:	learn: 1.0933801	total: 153ms	remaining: 1s
132:	learn: 1.0898687	total: 154ms	remaining: 1s
133:	learn: 1.0852056	total: 155ms	remaining: 1s
134:	learn: 1.0797904	total: 157ms	remaining: 1s
135:	learn: 1.0756799	total: 158ms	remaining: 1s
136:	learn: 1.0737658	total: 159ms	remaining: 1000ms
137:	learn: 1.0718431	total: 160ms	remaining: 1s
138:	learn: 1.0636087	total: 162ms	remaining: 1s
139:	learn: 1.0559538	total: 163ms	remaining: 1s
140:	learn: 1.0479732	total: 164ms	remaining: 1s
141:	learn: 1.0453922	total: 166ms	remaining: 1s
142:	learn: 1.0440948	total: 167ms	remaining: 1s
143:	learn: 1.0422695	total: 168ms	remaining: 996ms
144:	learn: 1.0396268	total: 169ms	remaining: 995ms
145:	learn: 1.0341064	total: 170ms	remaining: 995ms
146:	learn: 1.0309128	total: 171ms	remaining: 993ms
147:	learn: 1.0290020	total: 172ms	remaining: 992ms
148:	learn: 1.0264844	total: 174ms	remaining: 993ms
149:	learn: 1.0193681	total: 175ms	remaining: 993ms
150:	learn: 1.0140488	total: 177ms	remaining: 993ms
151:	learn: 1.0113945	total: 178ms	remaining: 992ms
152:	learn: 1.0095995	total: 179ms	remaining: 993ms
153:	learn: 1.0075245	total: 181ms	remaining: 992ms
154:	learn: 1.0070684	total: 181ms	remaining: 987ms
155:	learn: 1.0020641	total: 182ms	remaining: 986ms
156:	learn: 0.9993898	total: 183ms	remaining: 985ms
157:	learn: 0.9953997	total: 185ms	remaining: 984ms
158:	learn: 0.9913068	total: 186ms	remaining: 983ms
159:	learn: 0.9890009	total: 187ms	remaining: 983ms
160:	learn: 0.9835573	total: 188ms	remaining: 981ms
161:	learn: 0.9793398	total: 190ms	remaining: 984ms
162:	learn: 0.9729542	total: 192ms	remaining: 984ms
163:	learn: 0.9680017	total: 193ms	remaining: 984ms
164:	learn: 0.9623662	total: 195ms	remaining: 985ms
165:	learn: 0.9603140	total: 196ms	remaining: 985ms
166:	learn: 0.9579514	total: 197ms	remaining: 984ms
167:	learn: 0.9549554	total: 199ms	remaining: 984ms
168:	learn: 0.9515523	total: 200ms	remaining: 983ms
169:	learn: 0.9495113	total: 201ms	remaining: 983ms
170:	learn: 0.9469630	total: 204ms	remaining: 991ms
171:	learn: 0.9450239	total: 206ms	remaining: 993ms
172:	learn: 0.9392362	total: 208ms	remaining: 993ms
173:	learn: 0.9366184	total: 209ms	remaining: 993ms
174:	learn: 0.9352052	total: 211ms	remaining: 993ms
175:	learn: 0.9313468	total: 212ms	remaining: 992ms
176:	learn: 0.9298644	total: 213ms	remaining: 992ms
177:	learn: 0.9282366	total: 215ms	remaining: 991ms
178:	learn: 0.9245339	total: 216ms	remaining: 991ms
179:	learn: 0.9176830	total: 217ms	remaining: 990ms
180:	learn: 0.9139222	total: 219ms	remaining: 990ms
181:	learn: 0.9125501	total: 220ms	remaining: 990ms
182:	learn: 0.9107959	total: 222ms	remaining: 990ms
183:	learn: 0.9072206	total: 223ms	remaining: 989ms
184:	learn: 0.9051566	total: 224ms	remaining: 989ms
185:	learn: 0.8980314	total: 226ms	remaining: 988ms
186:	learn: 0.8963150	total: 228ms	remaining: 989ms
187:	learn: 0.8950627	total: 229ms	remaining: 989ms
188:	learn: 0.8939060	total: 231ms	remaining: 989ms
189:	learn: 0.8927613	total: 232ms	remaining: 989ms
190:	learn: 0.8917713	total: 233ms	remaining: 989ms
191:	learn: 0.8884585	total: 235ms	remaining: 988ms
192:	learn: 0.8872125	total: 236ms	remaining: 987ms
193:	learn: 0.8837618	total: 238ms	remaining: 987ms
194:	learn: 0.8792940	total: 239ms	remaining: 987ms
195:	learn: 0.8783155	total: 240ms	remaining: 984ms
196:	learn: 0.8773286	total: 241ms	remaining: 983ms
197:	learn: 0.8755356	total: 242ms	remaining: 982ms
198:	learn: 0.8743599	total: 244ms	remaining: 981ms
199:	learn: 0.8733684	total: 245ms	remaining: 980ms
200:	learn: 0.8717621	total: 246ms	remaining: 978ms
201:	learn: 0.8699208	total: 247ms	remaining: 975ms
202:	learn: 0.8685003	total: 248ms	remaining: 974ms
203:	learn: 0.8651124	total: 250ms	remaining: 977ms
204:	learn: 0.8640618	total: 253ms	remaining: 981ms
205:	learn: 0.8606948	total: 255ms	remaining: 981ms
206:	learn: 0.8595770	total: 256ms	remaining: 981ms
207:	learn: 0.8581444	total: 257ms	remaining: 980ms
208:	learn: 0.8569870	total: 259ms	remaining: 980ms
209:	learn: 0.8515998	total: 260ms	remaining: 979ms
210:	learn: 0.8485745	total: 261ms	remaining: 977ms
211:	learn: 0.8442917	total: 263ms	remaining: 976ms
212:	learn: 0.8415437	total: 264ms	remaining: 975ms
213:	learn: 0.8404023	total: 265ms	remaining: 975ms
214:	learn: 0.8339376	total: 267ms	remaining: 974ms
215:	learn: 0.8281211	total: 268ms	remaining: 973ms
216:	learn: 0.8271374	total: 270ms	remaining: 972ms
217:	learn: 0.8197295	total: 271ms	remaining: 972ms
218:	learn: 0.8188249	total: 272ms	remaining: 971ms
219:	learn: 0.8156426	total: 274ms	remaining: 970ms
220:	learn: 0.8095413	total: 275ms	remaining: 969ms
221:	learn: 0.8062176	total: 276ms	remaining: 967ms
222:	learn: 0.8051934	total: 277ms	remaining: 966ms
223:	learn: 0.8042803	total: 279ms	remaining: 966ms
224:	learn: 0.8035061	total: 280ms	remaining: 965ms
225:	learn: 0.8025689	total: 282ms	remaining: 964ms
226:	learn: 0.8017031	total: 283ms	remaining: 963ms
227:	learn: 0.7958286	total: 284ms	remaining: 962ms
228:	learn: 0.7948705	total: 285ms	remaining: 961ms
229:	learn: 0.7939643	total: 287ms	remaining: 960ms
230:	learn: 0.7913837	total: 288ms	remaining: 958ms
231:	learn: 0.7881361	total: 289ms	remaining: 958ms
232:	learn: 0.7839954	total: 291ms	remaining: 957ms
233:	learn: 0.7823800	total: 292ms	remaining: 956ms
234:	learn: 0.7807481	total: 293ms	remaining: 955ms
235:	learn: 0.7799069	total: 295ms	remaining: 956ms
236:	learn: 0.7734579	total: 297ms	remaining: 955ms
237:	learn: 0.7724430	total: 298ms	remaining: 954ms
238:	learn: 0.7681547	total: 299ms	remaining: 953ms
239:	learn: 0.7674802	total: 300ms	remaining: 951ms
240:	learn: 0.7659290	total: 302ms	remaining: 950ms
241:	learn: 0.7611747	total: 303ms	remaining: 949ms
242:	learn: 0.7604614	total: 304ms	remaining: 947ms
243:	learn: 0.7597760	total: 305ms	remaining: 946ms
244:	learn: 0.7561380	total: 306ms	remaining: 944ms
245:	learn: 0.7532587	total: 308ms	remaining: 943ms
246:	learn: 0.7525344	total: 309ms	remaining: 942ms
247:	learn: 0.7517649	total: 310ms	remaining: 942ms
248:	learn: 0.7511679	total: 312ms	remaining: 941ms
249:	learn: 0.7475835	total: 313ms	remaining: 940ms
250:	learn: 0.7431375	total: 315ms	remaining: 939ms
251:	learn: 0.7398229	total: 316ms	remaining: 937ms
252:	learn: 0.7337993	total: 317ms	remaining: 936ms
253:	learn: 0.7331216	total: 318ms	remaining: 934ms
254:	learn: 0.7324984	total: 319ms	remaining: 933ms
255:	learn: 0.7282855	total: 321ms	remaining: 931ms
256:	learn: 0.7277080	total: 322ms	remaining: 930ms
257:	learn: 0.7271020	total: 323ms	remaining: 929ms
258:	learn: 0.7264533	total: 325ms	remaining: 929ms
259:	learn: 0.7227731	total: 326ms	remaining: 928ms
260:	learn: 0.7221939	total: 327ms	remaining: 927ms
261:	learn: 0.7172174	total: 329ms	remaining: 926ms
262:	learn: 0.7166877	total: 330ms	remaining: 924ms
263:	learn: 0.7119928	total: 331ms	remaining: 923ms
264:	learn: 0.7073293	total: 332ms	remaining: 922ms
265:	learn: 0.7067685	total: 334ms	remaining: 920ms
266:	learn: 0.7022306	total: 335ms	remaining: 919ms
267:	learn: 0.7016606	total: 336ms	remaining: 918ms
268:	learn: 0.7011056	total: 337ms	remaining: 916ms
269:	learn: 0.6961264	total: 339ms	remaining: 916ms
270:	learn: 0.6922069	total: 341ms	remaining: 916ms
271:	learn: 0.6916100	total: 342ms	remaining: 916ms
272:	learn: 0.6866995	total: 343ms	remaining: 915ms
273:	learn: 0.6825127	total: 345ms	remaining: 914ms
274:	learn: 0.6804016	total: 346ms	remaining: 913ms
275:	learn: 0.6771867	total: 348ms	remaining: 912ms
276:	learn: 0.6765887	total: 349ms	remaining: 911ms
277:	learn: 0.6759728	total: 350ms	remaining: 909ms
278:	learn: 0.6715393	total: 351ms	remaining: 908ms
279:	learn: 0.6682778	total: 353ms	remaining: 907ms
280:	learn: 0.6662298	total: 356ms	remaining: 910ms
281:	learn: 0.6644141	total: 357ms	remaining: 909ms
282:	learn: 0.6608053	total: 359ms	remaining: 908ms
283:	learn: 0.6599672	total: 361ms	remaining: 910ms
284:	learn: 0.6579347	total: 364ms	remaining: 912ms
285:	learn: 0.6546490	total: 366ms	remaining: 914ms
286:	learn: 0.6514943	total: 368ms	remaining: 915ms
287:	learn: 0.6484505	total: 369ms	remaining: 913ms
288:	learn: 0.6468873	total: 371ms	remaining: 912ms
289:	learn: 0.6446664	total: 372ms	remaining: 911ms
290:	learn: 0.6403816	total: 373ms	remaining: 909ms
291:	learn: 0.6375318	total: 376ms	remaining: 911ms
292:	learn: 0.6353121	total: 377ms	remaining: 910ms
293:	learn: 0.6304077	total: 378ms	remaining: 908ms
294:	learn: 0.6273372	total: 380ms	remaining: 908ms
295:	learn: 0.6256133	total: 381ms	remaining: 907ms
296:	learn: 0.6239554	total: 382ms	remaining: 905ms
297:	learn: 0.6210102	total: 384ms	remaining: 904ms
298:	learn: 0.6177359	total: 385ms	remaining: 902ms
299:	learn: 0.6163631	total: 387ms	remaining: 902ms
300:	learn: 0.6130923	total: 388ms	remaining: 901ms
301:	learn: 0.6091597	total: 389ms	remaining: 899ms
302:	learn: 0.6086731	total: 390ms	remaining: 898ms
303:	learn: 0.6060425	total: 392ms	remaining: 897ms
304:	learn: 0.6030052	total: 393ms	remaining: 895ms
305:	learn: 0.6013179	total: 394ms	remaining: 893ms
306:	learn: 0.5983523	total: 395ms	remaining: 892ms
307:	learn: 0.5955016	total: 396ms	remaining: 890ms
308:	learn: 0.5941457	total: 397ms	remaining: 889ms
309:	learn: 0.5918568	total: 398ms	remaining: 887ms
310:	learn: 0.5884635	total: 399ms	remaining: 885ms
311:	learn: 0.5879220	total: 401ms	remaining: 885ms
312:	learn: 0.5873720	total: 404ms	remaining: 887ms
313:	learn: 0.5841020	total: 406ms	remaining: 888ms
314:	learn: 0.5826387	total: 409ms	remaining: 889ms
315:	learn: 0.5800904	total: 411ms	remaining: 890ms
316:	learn: 0.5789583	total: 413ms	remaining: 890ms
317:	learn: 0.5776092	total: 415ms	remaining: 891ms
318:	learn: 0.5761906	total: 418ms	remaining: 892ms
319:	learn: 0.5747953	total: 420ms	remaining: 893ms
320:	learn: 0.5728003	total: 422ms	remaining: 892ms
321:	learn: 0.5712952	total: 423ms	remaining: 890ms
322:	learn: 0.5699372	total: 424ms	remaining: 889ms
323:	learn: 0.5681956	total: 425ms	remaining: 887ms
324:	learn: 0.5668607	total: 426ms	remaining: 885ms
325:	learn: 0.5658108	total: 427ms	remaining: 883ms
326:	learn: 0.5615768	total: 428ms	remaining: 882ms
327:	learn: 0.5592288	total: 430ms	remaining: 880ms
328:	learn: 0.5585764	total: 431ms	remaining: 878ms
329:	learn: 0.5581960	total: 432ms	remaining: 876ms
330:	learn: 0.5575786	total: 433ms	remaining: 876ms
331:	learn: 0.5539621	total: 435ms	remaining: 875ms
332:	learn: 0.5525355	total: 436ms	remaining: 874ms
333:	learn: 0.5516628	total: 438ms	remaining: 872ms
334:	learn: 0.5494539	total: 439ms	remaining: 871ms
335:	learn: 0.5466869	total: 440ms	remaining: 869ms
336:	learn: 0.5435365	total: 441ms	remaining: 868ms
337:	learn: 0.5423258	total: 442ms	remaining: 866ms
338:	learn: 0.5401777	total: 444ms	remaining: 865ms
339:	learn: 0.5389947	total: 445ms	remaining: 863ms
340:	learn: 0.5354094	total: 446ms	remaining: 861ms
341:	learn: 0.5346578	total: 447ms	remaining: 860ms
342:	learn: 0.5312137	total: 449ms	remaining: 859ms
343:	learn: 0.5300369	total: 450ms	remaining: 858ms
344:	learn: 0.5268444	total: 452ms	remaining: 858ms
345:	learn: 0.5250175	total: 454ms	remaining: 858ms
346:	learn: 0.5233463	total: 455ms	remaining: 857ms
347:	learn: 0.5208515	total: 456ms	remaining: 855ms
348:	learn: 0.5185814	total: 458ms	remaining: 853ms
349:	learn: 0.5182418	total: 459ms	remaining: 852ms
350:	learn: 0.5178308	total: 460ms	remaining: 850ms
351:	learn: 0.5172978	total: 461ms	remaining: 848ms
352:	learn: 0.5141922	total: 462ms	remaining: 847ms
353:	learn: 0.5118567	total: 463ms	remaining: 845ms
354:	learn: 0.5112165	total: 464ms	remaining: 843ms
355:	learn: 0.5089271	total: 466ms	remaining: 843ms
356:	learn: 0.5067753	total: 467ms	remaining: 841ms
357:	learn: 0.5056886	total: 468ms	remaining: 840ms
358:	learn: 0.5042012	total: 469ms	remaining: 838ms
359:	learn: 0.5038765	total: 471ms	remaining: 837ms
360:	learn: 0.5007154	total: 472ms	remaining: 835ms
361:	learn: 0.4992780	total: 473ms	remaining: 833ms
362:	learn: 0.4956326	total: 474ms	remaining: 832ms
363:	learn: 0.4927880	total: 475ms	remaining: 830ms
364:	learn: 0.4910041	total: 476ms	remaining: 828ms
365:	learn: 0.4889716	total: 477ms	remaining: 827ms
366:	learn: 0.4883719	total: 478ms	remaining: 825ms
367:	learn: 0.4851126	total: 479ms	remaining: 823ms
368:	learn: 0.4845302	total: 481ms	remaining: 823ms
369:	learn: 0.4833349	total: 482ms	remaining: 821ms
370:	learn: 0.4810396	total: 483ms	remaining: 820ms
371:	learn: 0.4806318	total: 485ms	remaining: 819ms
372:	learn: 0.4799365	total: 486ms	remaining: 817ms
373:	learn: 0.4791371	total: 487ms	remaining: 815ms
374:	learn: 0.4770801	total: 488ms	remaining: 814ms
375:	learn: 0.4759247	total: 489ms	remaining: 812ms
376:	learn: 0.4732312	total: 491ms	remaining: 811ms
377:	learn: 0.4707195	total: 492ms	remaining: 809ms
378:	learn: 0.4694102	total: 493ms	remaining: 807ms
379:	learn: 0.4662038	total: 494ms	remaining: 806ms
380:	learn: 0.4653275	total: 495ms	remaining: 804ms

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fitting SVR for C2X_rhow_5x5_depth_lt_1
Fitting KNN for C2X_rhow_5x5_depth_lt_1
Fitting LR for C2X_rhow_5x5_depth_lt_1
Fitting RF for C2X_rhow_5x5_depth_lt_1
Fitting CAT for C2X_rhow_5x5_depth_lt_1
Learning rate set to 0.033272
0:	learn: 3.4143328	total: 1.86ms	remaining: 1.86s
1:	learn: 3.3610829	total: 3.15ms	remaining: 1.57s
2:	learn: 3.3115331	total: 4.37ms	remaining: 1.45s
3:	learn: 3.2655663	total: 5.58ms	remaining: 1.39s
4:	learn: 3.2161431	total: 6.75ms	remaining: 1.34s
5:	learn: 3.1738879	total: 7.92ms	remaining: 1.31s
6:	learn: 3.1313495	total: 9.18ms	remaining: 1.3s
7:	learn: 3.0834939	total: 10.3ms	remaining: 1.28s
8:	learn: 3.0459903	total: 11.5ms	remaining: 1.27s
9:	learn: 3.0038021	total: 12.7ms	remaining: 1.26s
10:	learn: 2.9630599	total: 13.9ms	remaining: 1.25s
11:	learn: 2.9267455	total: 15.3ms	remaining: 1.26s
12:	learn: 2.8880294	total: 16.5ms	remaining: 1.25s
13:	learn: 2.8578759	total: 17.7ms	remaining: 1.25s
14:	learn: 2.8235119	total: 19ms	remaining: 1.25s
15:	learn: 2.7801850	total: 20.2ms	remaining: 1.24s
16:	learn: 2.7508231	total: 21.3ms	remaining: 1.23s
17:	learn: 2.7117521	total: 22.5ms	remaining: 1.23s
18:	learn: 2.6824901	total: 23.6ms	remaining: 1.22s
19:	learn: 2.6510676	total: 24.9ms	remaining: 1.22s
20:	learn: 2.6198637	total: 26.1ms	remaining: 1.22s
21:	learn: 2.5919221	total: 27.2ms	remaining: 1.21s
22:	learn: 2.5607133	total: 28.4ms	remaining: 1.21s
23:	learn: 2.5300377	total: 29.5ms	remaining: 1.2s
24:	learn: 2.4996739	total: 31.4ms	remaining: 1.22s
25:	learn: 2.4739924	total: 33ms	remaining: 1.23s
26:	learn: 2.4429070	total: 34.2ms	remaining: 1.23s
27:	learn: 2.4129585	total: 35.5ms	remaining: 1.23s
28:	learn: 2.3870800	total: 36.7ms	remaining: 1.23s
29:	learn: 2.3624763	total: 37.8ms	remaining: 1.22s
30:	learn: 2.3305769	total: 39ms	remaining: 1.22s
31:	learn: 2.3083438	total: 40.4ms	remaining: 1.22s
32:	learn: 2.2818412	total: 41.6ms	remaining: 1.22s
33:	learn: 2.2575449	total: 42.8ms	remaining: 1.22s
34:	learn: 2.2363785	total: 43.9ms	remaining: 1.21s
35:	learn: 2.2059851	total: 45.7ms	remaining: 1.22s
36:	learn: 2.1827639	total: 47.1ms	remaining: 1.23s
37:	learn: 2.1642624	total: 48.7ms	remaining: 1.23s
38:	learn: 2.1348238	total: 50ms	remaining: 1.23s
39:	learn: 2.1143013	total: 51.3ms	remaining: 1.23s
40:	learn: 2.0942275	total: 52.4ms	remaining: 1.23s
41:	learn: 2.0758161	total: 53.6ms	remaining: 1.22s
42:	learn: 2.0602167	total: 54.7ms	remaining: 1.22s
43:	learn: 2.0404355	total: 56.2ms	remaining: 1.22s
44:	learn: 2.0192554	total: 57.4ms	remaining: 1.22s
45:	learn: 1.9922085	total: 58.6ms	remaining: 1.21s
46:	learn: 1.9762998	total: 59.8ms	remaining: 1.21s
47:	learn: 1.9501915	total: 61ms	remaining: 1.21s
48:	learn: 1.9306832	total: 62.3ms	remaining: 1.21s
49:	learn: 1.9110707	total: 63.8ms	remaining: 1.21s
50:	learn: 1.8909979	total: 65ms	remaining: 1.21s
51:	learn: 1.8715713	total: 66.3ms	remaining: 1.21s
52:	learn: 1.8536921	total: 67.6ms	remaining: 1.21s
53:	learn: 1.8445712	total: 68.8ms	remaining: 1.2s
54:	learn: 1.8254332	total: 70ms	remaining: 1.2s
55:	learn: 1.8095871	total: 71.5ms	remaining: 1.21s
56:	learn: 1.8010098	total: 72.9ms	remaining: 1.21s
57:	learn: 1.7802380	total: 74.1ms	remaining: 1.2s
58:	learn: 1.7622700	total: 75.6ms	remaining: 1.21s
59:	learn: 1.7455943	total: 76.9ms	remaining: 1.21s
60:	learn: 1.7311581	total: 78.3ms	remaining: 1.21s
61:	learn: 1.7159615	total: 79.6ms	remaining: 1.2s
62:	learn: 1.7004709	total: 81.4ms	remaining: 1.21s
63:	learn: 1.6887813	total: 82.8ms	remaining: 1.21s
64:	learn: 1.6755572	total: 84ms	remaining: 1.21s
65:	learn: 1.6576497	total: 85.2ms	remaining: 1.21s
66:	learn: 1.6408242	total: 86.4ms	remaining: 1.2s
67:	learn: 1.6338362	total: 88ms	remaining: 1.21s
68:	learn: 1.6288572	total: 89.1ms	remaining: 1.2s
69:	learn: 1.6158038	total: 90.3ms	remaining: 1.2s
70:	learn: 1.6057676	total: 91.5ms	remaining: 1.2s
71:	learn: 1.5927870	total: 92.8ms	remaining: 1.2s
72:	learn: 1.5813548	total: 94.6ms	remaining: 1.2s
73:	learn: 1.5667472	total: 96ms	remaining: 1.2s
74:	learn: 1.5527307	total: 97.2ms	remaining: 1.2s
75:	learn: 1.5347326	total: 98.5ms	remaining: 1.2s
76:	learn: 1.5235703	total: 99.7ms	remaining: 1.2s
77:	learn: 1.5078696	total: 101ms	remaining: 1.19s
78:	learn: 1.4957474	total: 102ms	remaining: 1.19s
79:	learn: 1.4817778	total: 103ms	remaining: 1.19s
80:	learn: 1.4672997	total: 104ms	remaining: 1.19s
81:	learn: 1.4528408	total: 106ms	remaining: 1.18s
82:	learn: 1.4357397	total: 107ms	remaining: 1.18s
83:	learn: 1.4268512	total: 108ms	remaining: 1.18s
84:	learn: 1.4165124	total: 110ms	remaining: 1.18s
85:	learn: 1.4053045	total: 111ms	remaining: 1.18s
86:	learn: 1.3991287	total: 113ms	remaining: 1.18s
87:	learn: 1.3887363	total: 114ms	remaining: 1.18s
88:	learn: 1.3793803	total: 115ms	remaining: 1.18s
89:	learn: 1.3746979	total: 116ms	remaining: 1.18s
90:	learn: 1.3639755	total: 118ms	remaining: 1.17s
91:	learn: 1.3578839	total: 119ms	remaining: 1.17s
92:	learn: 1.3492016	total: 120ms	remaining: 1.17s
93:	learn: 1.3348788	total: 121ms	remaining: 1.17s
94:	learn: 1.3260584	total: 122ms	remaining: 1.17s
95:	learn: 1.3210424	total: 124ms	remaining: 1.16s
96:	learn: 1.3094385	total: 125ms	remaining: 1.16s
97:	learn: 1.3008135	total: 126ms	remaining: 1.16s
98:	learn: 1.2969594	total: 128ms	remaining: 1.16s
99:	learn: 1.2837851	total: 129ms	remaining: 1.16s
100:	learn: 1.2734303	total: 130ms	remaining: 1.16s
101:	learn: 1.2614382	total: 131ms	remaining: 1.16s
102:	learn: 1.2564935	total: 133ms	remaining: 1.15s
103:	learn: 1.2485990	total: 134ms	remaining: 1.15s
104:	learn: 1.2398270	total: 135ms	remaining: 1.15s
105:	learn: 1.2349010	total: 136ms	remaining: 1.15s
106:	learn: 1.2274320	total: 137ms	remaining: 1.15s
107:	learn: 1.2194781	total: 139ms	remaining: 1.14s
108:	learn: 1.2122020	total: 140ms	remaining: 1.14s
109:	learn: 1.2071281	total: 142ms	remaining: 1.15s
110:	learn: 1.1967404	total: 143ms	remaining: 1.15s
111:	learn: 1.1913122	total: 144ms	remaining: 1.14s
112:	learn: 1.1815096	total: 146ms	remaining: 1.14s
113:	learn: 1.1792110	total: 147ms	remaining: 1.14s
114:	learn: 1.1722258	total: 148ms	remaining: 1.14s
115:	learn: 1.1628205	total: 150ms	remaining: 1.14s
116:	learn: 1.1538462	total: 151ms	remaining: 1.14s
117:	learn: 1.1471374	total: 152ms	remaining: 1.14s
118:	learn: 1.1403613	total: 153ms	remaining: 1.13s
119:	learn: 1.1356359	total: 154ms	remaining: 1.13s
120:	learn: 1.1323793	total: 155ms	remaining: 1.13s
121:	learn: 1.1227511	total: 156ms	remaining: 1.12s
122:	learn: 1.1194503	total: 158ms	remaining: 1.13s
123:	learn: 1.1085622	total: 160ms	remaining: 1.13s
124:	learn: 1.0972708	total: 161ms	remaining: 1.13s
125:	learn: 1.0920322	total: 162ms	remaining: 1.12s
126:	learn: 1.0850244	total: 163ms	remaining: 1.12s
127:	learn: 1.0803510	total: 165ms	remaining: 1.12s
128:	learn: 1.0742921	total: 166ms	remaining: 1.12s
129:	learn: 1.0662108	total: 167ms	remaining: 1.12s
130:	learn: 1.0619540	total: 168ms	remaining: 1.12s
131:	learn: 1.0542937	total: 169ms	remaining: 1.11s
132:	learn: 1.0469126	total: 171ms	remaining: 1.11s
133:	learn: 1.0414994	total: 173ms	remaining: 1.11s
134:	learn: 1.0368127	total: 175ms	remaining: 1.12s
135:	learn: 1.0353146	total: 176ms	remaining: 1.12s
136:	learn: 1.0298230	total: 177ms	remaining: 1.12s
137:	learn: 1.0228208	total: 178ms	remaining: 1.11s
138:	learn: 1.0170365	total: 180ms	remaining: 1.11s
139:	learn: 1.0133249	total: 181ms	remaining: 1.11s
140:	learn: 1.0069316	total: 182ms	remaining: 1.11s
141:	learn: 1.0046943	total: 184ms	remaining: 1.11s
142:	learn: 0.9974190	total: 185ms	remaining: 1.11s
143:	learn: 0.9911576	total: 186ms	remaining: 1.1s
144:	learn: 0.9862697	total: 187ms	remaining: 1.1s
145:	learn: 0.9812859	total: 189ms	remaining: 1.1s
146:	learn: 0.9765863	total: 190ms	remaining: 1.1s
147:	learn: 0.9729681	total: 191ms	remaining: 1.1s
148:	learn: 0.9661822	total: 192ms	remaining: 1.1s
149:	learn: 0.9640460	total: 194ms	remaining: 1.1s
150:	learn: 0.9618026	total: 195ms	remaining: 1.1s
151:	learn: 0.9530441	total: 197ms	remaining: 1.1s
152:	learn: 0.9504444	total: 199ms	remaining: 1.1s
153:	learn: 0.9445221	total: 200ms	remaining: 1.1s
154:	learn: 0.9400280	total: 201ms	remaining: 1.1s
155:	learn: 0.9353462	total: 203ms	remaining: 1.1s
156:	learn: 0.9338734	total: 204ms	remaining: 1.09s
157:	learn: 0.9274895	total: 205ms	remaining: 1.09s
158:	learn: 0.9239844	total: 207ms	remaining: 1.09s
159:	learn: 0.9155120	total: 208ms	remaining: 1.09s
160:	learn: 0.9077657	total: 209ms	remaining: 1.09s
161:	learn: 0.9063471	total: 211ms	remaining: 1.09s
162:	learn: 0.8980359	total: 212ms	remaining: 1.09s
163:	learn: 0.8916535	total: 214ms	remaining: 1.09s
164:	learn: 0.8863480	total: 215ms	remaining: 1.09s
165:	learn: 0.8794042	total: 216ms	remaining: 1.09s
166:	learn: 0.8738384	total: 218ms	remaining: 1.09s
167:	learn: 0.8665500	total: 219ms	remaining: 1.09s
168:	learn: 0.8610016	total: 221ms	remaining: 1.08s
169:	learn: 0.8587385	total: 222ms	remaining: 1.08s
170:	learn: 0.8547070	total: 224ms	remaining: 1.08s
171:	learn: 0.8478634	total: 225ms	remaining: 1.08s
172:	learn: 0.8421927	total: 226ms	remaining: 1.08s
173:	learn: 0.8385186	total: 228ms	remaining: 1.08s
174:	learn: 0.8340557	total: 229ms	remaining: 1.08s
175:	learn: 0.8293073	total: 230ms	remaining: 1.08s
176:	learn: 0.8267658	total: 231ms	remaining: 1.08s
177:	learn: 0.8202901	total: 233ms	remaining: 1.08s
178:	learn: 0.8180442	total: 235ms	remaining: 1.08s
179:	learn: 0.8117644	total: 237ms	remaining: 1.08s
180:	learn: 0.8106690	total: 238ms	remaining: 1.08s
181:	learn: 0.8057775	total: 240ms	remaining: 1.08s
182:	learn: 0.8038524	total: 241ms	remaining: 1.08s
183:	learn: 0.7984603	total: 243ms	remaining: 1.08s
184:	learn: 0.7922731	total: 244ms	remaining: 1.07s
185:	learn: 0.7889395	total: 245ms	remaining: 1.07s
186:	learn: 0.7829655	total: 247ms	remaining: 1.07s
187:	learn: 0.7771786	total: 248ms	remaining: 1.07s
188:	learn: 0.7752232	total: 250ms	remaining: 1.07s
189:	learn: 0.7716562	total: 251ms	remaining: 1.07s
190:	learn: 0.7689138	total: 252ms	remaining: 1.07s
191:	learn: 0.7660212	total: 254ms	remaining: 1.07s
192:	learn: 0.7631806	total: 255ms	remaining: 1.06s
193:	learn: 0.7579565	total: 256ms	remaining: 1.06s
194:	learn: 0.7549715	total: 257ms	remaining: 1.06s
195:	learn: 0.7495767	total: 259ms	remaining: 1.06s
196:	learn: 0.7482913	total: 262ms	remaining: 1.07s
197:	learn: 0.7430737	total: 263ms	remaining: 1.07s
198:	learn: 0.7378179	total: 265ms	remaining: 1.06s
199:	learn: 0.7343240	total: 267ms	remaining: 1.07s
200:	learn: 0.7318037	total: 269ms	remaining: 1.07s
201:	learn: 0.7281543	total: 271ms	remaining: 1.07s
202:	learn: 0.7240944	total: 272ms	remaining: 1.07s
203:	learn: 0.7199984	total: 273ms	remaining: 1.07s
204:	learn: 0.7165534	total: 275ms	remaining: 1.06s
205:	learn: 0.7115563	total: 276ms	remaining: 1.06s
206:	learn: 0.7076310	total: 278ms	remaining: 1.06s
207:	learn: 0.7052342	total: 279ms	remaining: 1.06s
208:	learn: 0.7029909	total: 280ms	remaining: 1.06s
209:	learn: 0.6999991	total: 282ms	remaining: 1.06s
210:	learn: 0.6968995	total: 284ms	remaining: 1.06s
211:	learn: 0.6919709	total: 286ms	remaining: 1.06s
212:	learn: 0.6879120	total: 287ms	remaining: 1.06s
213:	learn: 0.6850482	total: 289ms	remaining: 1.06s
214:	learn: 0.6820492	total: 290ms	remaining: 1.06s
215:	learn: 0.6790288	total: 291ms	remaining: 1.06s
216:	learn: 0.6764093	total: 293ms	remaining: 1.06s
217:	learn: 0.6742122	total: 294ms	remaining: 1.06s
218:	learn: 0.6706681	total: 296ms	remaining: 1.05s
219:	learn: 0.6662753	total: 297ms	remaining: 1.05s
220:	learn: 0.6642102	total: 299ms	remaining: 1.05s
221:	learn: 0.6610327	total: 300ms	remaining: 1.05s
222:	learn: 0.6582374	total: 302ms	remaining: 1.05s
223:	learn: 0.6548520	total: 303ms	remaining: 1.05s
224:	learn: 0.6518506	total: 304ms	remaining: 1.05s
225:	learn: 0.6496996	total: 306ms	remaining: 1.05s
226:	learn: 0.6468451	total: 307ms	remaining: 1.05s
227:	learn: 0.6444228	total: 309ms	remaining: 1.04s
228:	learn: 0.6424564	total: 310ms	remaining: 1.04s
229:	learn: 0.6394037	total: 311ms	remaining: 1.04s
230:	learn: 0.6359663	total: 313ms	remaining: 1.04s
231:	learn: 0.6315382	total: 315ms	remaining: 1.04s
232:	learn: 0.6292355	total: 316ms	remaining: 1.04s
233:	learn: 0.6259887	total: 318ms	remaining: 1.04s
234:	learn: 0.6231930	total: 319ms	remaining: 1.04s
235:	learn: 0.6196731	total: 321ms	remaining: 1.04s
236:	learn: 0.6169825	total: 322ms	remaining: 1.04s
237:	learn: 0.6128014	total: 323ms	remaining: 1.03s
238:	learn: 0.6095897	total: 325ms	remaining: 1.03s
239:	learn: 0.6068546	total: 326ms	remaining: 1.03s
240:	learn: 0.6053601	total: 328ms	remaining: 1.03s
241:	learn: 0.6049798	total: 329ms	remaining: 1.03s
242:	learn: 0.6030708	total: 331ms	remaining: 1.03s
243:	learn: 0.6002173	total: 332ms	remaining: 1.03s
244:	learn: 0.5973332	total: 334ms	remaining: 1.03s
245:	learn: 0.5948460	total: 335ms	remaining: 1.03s
246:	learn: 0.5927962	total: 337ms	remaining: 1.02s
247:	learn: 0.5900542	total: 338ms	remaining: 1.02s
248:	learn: 0.5882921	total: 340ms	remaining: 1.02s
249:	learn: 0.5854506	total: 341ms	remaining: 1.02s
250:	learn: 0.5835164	total: 342ms	remaining: 1.02s
251:	learn: 0.5817215	total: 344ms	remaining: 1.02s
252:	learn: 0.5802624	total: 346ms	remaining: 1.02s
253:	learn: 0.5782629	total: 347ms	remaining: 1.02s
254:	learn: 0.5756870	total: 349ms	remaining: 1.02s
255:	learn: 0.5743662	total: 350ms	remaining: 1.02s
256:	learn: 0.5725218	total: 351ms	remaining: 1.01s
257:	learn: 0.5705932	total: 353ms	remaining: 1.01s
258:	learn: 0.5688090	total: 354ms	remaining: 1.01s
259:	learn: 0.5664567	total: 356ms	remaining: 1.01s
260:	learn: 0.5627509	total: 358ms	remaining: 1.01s
261:	learn: 0.5609042	total: 360ms	remaining: 1.01s
262:	learn: 0.5582248	total: 362ms	remaining: 1.01s
263:	learn: 0.5567703	total: 363ms	remaining: 1.01s
264:	learn: 0.5549356	total: 364ms	remaining: 1.01s
265:	learn: 0.5529704	total: 366ms	remaining: 1.01s
266:	learn: 0.5513214	total: 367ms	remaining: 1.01s
267:	learn: 0.5496876	total: 368ms	remaining: 1s
268:	learn: 0.5474601	total: 370ms	remaining: 1.01s
269:	learn: 0.5451587	total: 372ms	remaining: 1s
270:	learn: 0.5428181	total: 374ms	remaining: 1.01s
271:	learn: 0.5408411	total: 376ms	remaining: 1s
272:	learn: 0.5386950	total: 377ms	remaining: 1s
273:	learn: 0.5369312	total: 379ms	remaining: 1s
274:	learn: 0.5355102	total: 380ms	remaining: 1s
275:	learn: 0.5330869	total: 382ms	remaining: 1s
276:	learn: 0.5306801	total: 384ms	remaining: 1s
277:	learn: 0.5278531	total: 385ms	remaining: 1s
278:	learn: 0.5252801	total: 387ms	remaining: 999ms
279:	learn: 0.5227690	total: 388ms	remaining: 998ms
280:	learn: 0.5213234	total: 389ms	remaining: 997ms
281:	learn: 0.5194048	total: 391ms	remaining: 995ms
282:	learn: 0.5175563	total: 393ms	remaining: 995ms
283:	learn: 0.5158607	total: 394ms	remaining: 994ms
284:	learn: 0.5133834	total: 396ms	remaining: 992ms
285:	learn: 0.5120370	total: 397ms	remaining: 991ms
286:	learn: 0.5101039	total: 398ms	remaining: 990ms
287:	learn: 0.5077028	total: 400ms	remaining: 988ms
288:	learn: 0.5063300	total: 401ms	remaining: 987ms
289:	learn: 0.5049952	total: 402ms	remaining: 985ms
290:	learn: 0.5036266	total: 404ms	remaining: 985ms
291:	learn: 0.5011667	total: 406ms	remaining: 984ms
292:	learn: 0.4988398	total: 407ms	remaining: 983ms
293:	learn: 0.4971012	total: 409ms	remaining: 982ms
294:	learn: 0.4940207	total: 410ms	remaining: 981ms
295:	learn: 0.4919460	total: 412ms	remaining: 979ms
296:	learn: 0.4903301	total: 413ms	remaining: 978ms
297:	learn: 0.4892851	total: 415ms	remaining: 977ms
298:	learn: 0.4867375	total: 416ms	remaining: 975ms
299:	learn: 0.4847354	total: 417ms	remaining: 973ms
300:	learn: 0.4823842	total: 419ms	remaining: 972ms
301:	learn: 0.4807231	total: 421ms	remaining: 973ms
302:	learn: 0.4794028	total: 422ms	remaining: 972ms
303:	learn: 0.4770130	total: 424ms	remaining: 970ms
304:	learn: 0.4757690	total: 425ms	remaining: 969ms
305:	learn: 0.4741591	total: 427ms	remaining: 967ms
306:	learn: 0.4733332	total: 428ms	remaining: 966ms
307:	learn: 0.4715958	total: 429ms	remaining: 965ms
308:	learn: 0.4696476	total: 431ms	remaining: 963ms
309:	learn: 0.4694770	total: 432ms	remaining: 962ms
310:	learn: 0.4681785	total: 435ms	remaining: 963ms
311:	learn: 0.4665223	total: 436ms	remaining: 962ms
312:	learn: 0.4663423	total: 438ms	remaining: 961ms
313:	learn: 0.4653180	total: 439ms	remaining: 959ms
314:	learn: 0.4633476	total: 440ms	remaining: 958ms
315:	learn: 0.4631906	total: 442ms	remaining: 957ms
316:	learn: 0.4620895	total: 443ms	remaining: 955ms
317:	learn: 0.4607618	total: 445ms	remaining: 954ms
318:	learn: 0.4593084	total: 446ms	remaining: 952ms
319:	learn: 0.4576094	total: 448ms	remaining: 951ms
320:	learn: 0.4574506	total: 450ms	remaining: 951ms
321:	learn: 0.4570435	total: 451ms	remaining: 950ms
322:	learn: 0.4568861	total: 453ms	remaining: 949ms
323:	learn: 0.4551357	total: 454ms	remaining: 947ms
324:	learn: 0.4549901	total: 455ms	remaining: 946ms
325:	learn: 0.4532520	total: 457ms	remaining: 945ms
326:	learn: 0.4513080	total: 458ms	remaining: 943ms
327:	learn: 0.4499012	total: 460ms	remaining: 942ms
328:	learn: 0.4485294	total: 461ms	remaining: 940ms
329:	learn: 0.4462762	total: 462ms	remaining: 939ms
330:	learn: 0.4436058	total: 464ms	remaining: 938ms
331:	learn: 0.4421362	total: 465ms	remaining: 936ms
332:	learn: 0.4395050	total: 467ms	remaining: 935ms
333:	learn: 0.4372378	total: 468ms	remaining: 934ms
334:	learn: 0.4360248	total: 470ms	remaining: 933ms
335:	learn: 0.4343760	total: 472ms	remaining: 932ms
336:	learn: 0.4332680	total: 473ms	remaining: 930ms
337:	learn: 0.4318981	total: 474ms	remaining: 929ms
338:	learn: 0.4301961	total: 476ms	remaining: 927ms
339:	learn: 0.4288866	total: 477ms	remaining: 926ms
340:	learn: 0.4275379	total: 478ms	remaining: 924ms
341:	learn: 0.4263933	total: 480ms	remaining: 923ms
342:	learn: 0.4261685	total: 481ms	remaining: 922ms
343:	learn: 0.4252646	total: 483ms	remaining: 921ms
344:	learn: 0.4239039	total: 484ms	remaining: 919ms
345:	learn: 0.4222017	total: 486ms	remaining: 918ms
346:	learn: 0.4205262	total: 487ms	remaining: 916ms
347:	learn: 0.4203819	total: 488ms	remaining: 915ms
348:	learn: 0.4196004	total: 490ms	remaining: 914ms
349:	learn: 0.4181891	total: 491ms	remaining: 912ms
350:	learn: 0.4165349	total: 493ms	remaining: 911ms
351:	learn: 0.4149505	total: 494ms	remaining: 909ms
352:	learn: 0.4124861	total: 496ms	remaining: 909ms
353:	learn: 0.4115531	total: 498ms	remaining: 908ms
354:	learn: 0.4107500	total: 499ms	remaining: 907ms
355:	learn: 0.4090384	total: 501ms	remaining: 906ms
356:	learn: 0.4063361	total: 502ms	remaining: 904ms
357:	learn: 0.4052568	total: 503ms	remaining: 903ms
358:	learn: 0.4041816	total: 505ms	remaining: 901ms
359:	learn: 0.4017120	total: 506ms	remaining: 900ms
360:	learn: 0.3999109	total: 508ms	remaining: 899ms
361:	learn: 0.3989667	total: 509ms	remaining: 897ms
362:	learn: 0.3983589	total: 511ms	remaining: 896ms
363:	learn: 0.3966922	total: 512ms	remaining: 895ms
364:	learn: 0.3963499	total: 514ms	remaining: 894ms
365:	learn: 0.3960637	total: 515ms	remaining: 892ms
366:	learn: 0.3949892	total: 517ms	remaining: 891ms
367:	learn: 0.3945112	total: 518ms	remaining: 889ms
368:	learn: 0.3930912	total: 519ms	remaining: 888ms
369:	learn: 0.3920214	total: 521ms	remaining: 887ms
370:	learn: 0.3907662	total: 522ms	remaining: 885ms
371:	learn: 0.3894279	total: 524ms	remaining: 884ms
372:	learn: 0.3888469	total: 525ms	remaining: 883ms
373:	learn: 0.3868532	total: 527ms	remaining: 882ms
374:	learn: 0.3855824	total: 529ms	remaining: 881ms
375:	learn: 0.3847864	total: 530ms	remaining: 880ms
376:	learn: 0.3846842	total: 532ms	remaining: 879ms
377:	learn: 0.3824662	total: 533ms	remaining: 877ms
378:	learn: 0.3804162	total: 535ms	remaining: 876ms
379:	learn: 0.3792112	total: 536ms	remaining: 875ms
380:	learn: 0.3780487	total: 538ms	remaining: 873ms
381:	learn: 0.3772410	total: 539ms	remaining: 872ms

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fitting SVR for C2X_rhown_5x5_depth_lt_1
Fitting KNN for C2X_rhown_5x5_depth_lt_1
Fitting LR for C2X_rhown_5x5_depth_lt_1
Fitting RF for C2X_rhown_5x5_depth_lt_1
Fitting CAT for C2X_rhown_5x5_depth_lt_1
Learning rate set to 0.033272
0:	learn: 3.4119599	total: 4.07ms	remaining: 4.07s
1:	learn: 3.3663652	total: 5.36ms	remaining: 2.67s
2:	learn: 3.3281277	total: 6.46ms	remaining: 2.15s
3:	learn: 3.2868857	total: 7.59ms	remaining: 1.89s
4:	learn: 3.2450587	total: 8.7ms	remaining: 1.73s
5:	learn: 3.2008909	total: 9.81ms	remaining: 1.62s
6:	learn: 3.1564132	total: 10.9ms	remaining: 1.55s
7:	learn: 3.1136855	total: 12ms	remaining: 1.49s
8:	learn: 3.0758213	total: 13.1ms	remaining: 1.44s
9:	learn: 3.0325314	total: 14.2ms	remaining: 1.4s
10:	learn: 2.9997663	total: 15.4ms	remaining: 1.38s
11:	learn: 2.9601642	total: 16.7ms	remaining: 1.37s
12:	learn: 2.9255534	total: 17.9ms	remaining: 1.36s
13:	learn: 2.8929778	total: 19.1ms	remaining: 1.35s
14:	learn: 2.8577978	total: 20.7ms	remaining: 1.36s
15:	learn: 2.8247035	total: 21.8ms	remaining: 1.34s
16:	learn: 2.7922601	total: 23ms	remaining: 1.33s
17:	learn: 2.7602367	total: 24.1ms	remaining: 1.31s
18:	learn: 2.7172672	total: 25.2ms	remaining: 1.3s
19:	learn: 2.6838528	total: 26.3ms	remaining: 1.29s
20:	learn: 2.6532646	total: 27.5ms	remaining: 1.28s
21:	learn: 2.6248449	total: 29ms	remaining: 1.29s
22:	learn: 2.5869102	total: 30.1ms	remaining: 1.28s
23:	learn: 2.5495786	total: 31.3ms	remaining: 1.27s
24:	learn: 2.5210379	total: 32.5ms	remaining: 1.27s
25:	learn: 2.4944808	total: 33.7ms	remaining: 1.26s
26:	learn: 2.4682545	total: 34.9ms	remaining: 1.26s
27:	learn: 2.4407328	total: 36.1ms	remaining: 1.25s
28:	learn: 2.4176973	total: 37.3ms	remaining: 1.25s
29:	learn: 2.3992000	total: 38.4ms	remaining: 1.24s
30:	learn: 2.3757232	total: 39.5ms	remaining: 1.23s
31:	learn: 2.3504530	total: 40.6ms	remaining: 1.23s
32:	learn: 2.3274490	total: 41.7ms	remaining: 1.22s
33:	learn: 2.3103865	total: 42.7ms	remaining: 1.21s
34:	learn: 2.2816091	total: 43.9ms	remaining: 1.21s
35:	learn: 2.2569412	total: 44.5ms	remaining: 1.19s
36:	learn: 2.2299578	total: 45.7ms	remaining: 1.19s
37:	learn: 2.2074802	total: 46.9ms	remaining: 1.19s
38:	learn: 2.1846182	total: 48.1ms	remaining: 1.19s
39:	learn: 2.1655248	total: 49.4ms	remaining: 1.19s
40:	learn: 2.1444665	total: 50.6ms	remaining: 1.18s
41:	learn: 2.1301478	total: 51.7ms	remaining: 1.18s
42:	learn: 2.1091336	total: 52.8ms	remaining: 1.17s
43:	learn: 2.0825384	total: 53.9ms	remaining: 1.17s
44:	learn: 2.0631161	total: 55ms	remaining: 1.17s
45:	learn: 2.0484978	total: 56.2ms	remaining: 1.16s
46:	learn: 2.0281199	total: 57.3ms	remaining: 1.16s
47:	learn: 2.0104576	total: 58.4ms	remaining: 1.16s
48:	learn: 1.9903913	total: 59.5ms	remaining: 1.15s
49:	learn: 1.9687025	total: 60.6ms	remaining: 1.15s
50:	learn: 1.9492833	total: 61.8ms	remaining: 1.15s
51:	learn: 1.9393116	total: 63.1ms	remaining: 1.15s
52:	learn: 1.9192811	total: 64.2ms	remaining: 1.15s
53:	learn: 1.9014465	total: 65.4ms	remaining: 1.15s
54:	learn: 1.8818491	total: 66.5ms	remaining: 1.14s
55:	learn: 1.8671194	total: 67.6ms	remaining: 1.14s
56:	learn: 1.8559055	total: 68.7ms	remaining: 1.14s
57:	learn: 1.8482901	total: 69.8ms	remaining: 1.13s
58:	learn: 1.8321080	total: 70.9ms	remaining: 1.13s
59:	learn: 1.8188327	total: 72.5ms	remaining: 1.14s
60:	learn: 1.8061375	total: 73.6ms	remaining: 1.13s
61:	learn: 1.7935171	total: 74.7ms	remaining: 1.13s
62:	learn: 1.7820147	total: 75.8ms	remaining: 1.13s
63:	learn: 1.7632879	total: 76.9ms	remaining: 1.12s
64:	learn: 1.7531110	total: 78.9ms	remaining: 1.14s
65:	learn: 1.7376531	total: 80.2ms	remaining: 1.13s
66:	learn: 1.7263755	total: 81.2ms	remaining: 1.13s
67:	learn: 1.7124181	total: 82.4ms	remaining: 1.13s
68:	learn: 1.6994303	total: 83.5ms	remaining: 1.13s
69:	learn: 1.6884894	total: 84.5ms	remaining: 1.12s
70:	learn: 1.6766223	total: 85.7ms	remaining: 1.12s
71:	learn: 1.6657856	total: 86.8ms	remaining: 1.12s
72:	learn: 1.6604206	total: 87.8ms	remaining: 1.11s
73:	learn: 1.6506130	total: 88.9ms	remaining: 1.11s
74:	learn: 1.6421000	total: 90ms	remaining: 1.11s
75:	learn: 1.6258862	total: 91.1ms	remaining: 1.11s
76:	learn: 1.6161934	total: 92.2ms	remaining: 1.1s
77:	learn: 1.6094280	total: 93.4ms	remaining: 1.1s
78:	learn: 1.6007830	total: 95.4ms	remaining: 1.11s
79:	learn: 1.5863755	total: 96.5ms	remaining: 1.11s
80:	learn: 1.5670673	total: 97.9ms	remaining: 1.11s
81:	learn: 1.5618162	total: 99ms	remaining: 1.11s
82:	learn: 1.5440942	total: 100ms	remaining: 1.1s
83:	learn: 1.5280886	total: 101ms	remaining: 1.1s
84:	learn: 1.5202795	total: 102ms	remaining: 1.1s
85:	learn: 1.5077733	total: 103ms	remaining: 1.1s
86:	learn: 1.5022876	total: 105ms	remaining: 1.1s
87:	learn: 1.4928361	total: 106ms	remaining: 1.09s
88:	learn: 1.4826806	total: 107ms	remaining: 1.09s
89:	learn: 1.4717613	total: 108ms	remaining: 1.09s
90:	learn: 1.4607778	total: 109ms	remaining: 1.09s
91:	learn: 1.4506775	total: 110ms	remaining: 1.09s
92:	learn: 1.4443194	total: 112ms	remaining: 1.09s
93:	learn: 1.4347309	total: 113ms	remaining: 1.09s
94:	learn: 1.4249891	total: 114ms	remaining: 1.08s
95:	learn: 1.4162621	total: 115ms	remaining: 1.08s
96:	learn: 1.4119259	total: 116ms	remaining: 1.08s
97:	learn: 1.3975734	total: 117ms	remaining: 1.08s
98:	learn: 1.3877463	total: 119ms	remaining: 1.08s
99:	learn: 1.3808550	total: 120ms	remaining: 1.08s
100:	learn: 1.3747099	total: 121ms	remaining: 1.08s
101:	learn: 1.3709623	total: 122ms	remaining: 1.08s
102:	learn: 1.3639716	total: 124ms	remaining: 1.08s
103:	learn: 1.3609133	total: 125ms	remaining: 1.08s
104:	learn: 1.3534464	total: 127ms	remaining: 1.08s
105:	learn: 1.3496109	total: 128ms	remaining: 1.08s
106:	learn: 1.3437029	total: 129ms	remaining: 1.08s
107:	learn: 1.3332859	total: 130ms	remaining: 1.08s
108:	learn: 1.3291516	total: 132ms	remaining: 1.07s
109:	learn: 1.3232431	total: 133ms	remaining: 1.07s
110:	learn: 1.3161282	total: 134ms	remaining: 1.07s
111:	learn: 1.3071095	total: 135ms	remaining: 1.07s
112:	learn: 1.2943674	total: 136ms	remaining: 1.07s
113:	learn: 1.2882967	total: 137ms	remaining: 1.07s
114:	learn: 1.2815876	total: 138ms	remaining: 1.06s
115:	learn: 1.2742099	total: 139ms	remaining: 1.06s
116:	learn: 1.2696221	total: 141ms	remaining: 1.06s
117:	learn: 1.2624033	total: 143ms	remaining: 1.06s
118:	learn: 1.2588424	total: 144ms	remaining: 1.06s
119:	learn: 1.2507020	total: 145ms	remaining: 1.06s
120:	learn: 1.2417755	total: 146ms	remaining: 1.06s
121:	learn: 1.2354280	total: 147ms	remaining: 1.06s
122:	learn: 1.2294092	total: 148ms	remaining: 1.06s
123:	learn: 1.2210124	total: 150ms	remaining: 1.06s
124:	learn: 1.2183427	total: 151ms	remaining: 1.05s
125:	learn: 1.2150210	total: 152ms	remaining: 1.05s
126:	learn: 1.2084082	total: 153ms	remaining: 1.05s
127:	learn: 1.2064439	total: 154ms	remaining: 1.05s
128:	learn: 1.2030822	total: 156ms	remaining: 1.05s
129:	learn: 1.1951256	total: 158ms	remaining: 1.05s
130:	learn: 1.1899206	total: 159ms	remaining: 1.05s
131:	learn: 1.1866860	total: 160ms	remaining: 1.05s
132:	learn: 1.1795116	total: 161ms	remaining: 1.05s
133:	learn: 1.1760319	total: 162ms	remaining: 1.05s
134:	learn: 1.1723057	total: 163ms	remaining: 1.05s
135:	learn: 1.1648243	total: 165ms	remaining: 1.04s
136:	learn: 1.1623387	total: 166ms	remaining: 1.04s
137:	learn: 1.1546311	total: 167ms	remaining: 1.04s
138:	learn: 1.1474632	total: 168ms	remaining: 1.04s
139:	learn: 1.1421344	total: 169ms	remaining: 1.04s
140:	learn: 1.1394251	total: 170ms	remaining: 1.04s
141:	learn: 1.1349689	total: 171ms	remaining: 1.03s
142:	learn: 1.1337814	total: 172ms	remaining: 1.03s
143:	learn: 1.1290065	total: 174ms	remaining: 1.03s
144:	learn: 1.1201395	total: 175ms	remaining: 1.03s
145:	learn: 1.1117735	total: 176ms	remaining: 1.03s
146:	learn: 1.1014989	total: 177ms	remaining: 1.03s
147:	learn: 1.0992735	total: 178ms	remaining: 1.03s
148:	learn: 1.0953813	total: 180ms	remaining: 1.02s
149:	learn: 1.0908149	total: 181ms	remaining: 1.02s
150:	learn: 1.0886870	total: 182ms	remaining: 1.02s
151:	learn: 1.0828347	total: 184ms	remaining: 1.02s
152:	learn: 1.0761539	total: 185ms	remaining: 1.02s
153:	learn: 1.0728368	total: 186ms	remaining: 1.02s
154:	learn: 1.0643978	total: 187ms	remaining: 1.02s
155:	learn: 1.0607790	total: 189ms	remaining: 1.02s
156:	learn: 1.0535441	total: 190ms	remaining: 1.02s
157:	learn: 1.0483530	total: 191ms	remaining: 1.02s
158:	learn: 1.0457555	total: 193ms	remaining: 1.02s
159:	learn: 1.0425757	total: 194ms	remaining: 1.02s
160:	learn: 1.0371879	total: 195ms	remaining: 1.02s
161:	learn: 1.0356761	total: 196ms	remaining: 1.01s
162:	learn: 1.0337453	total: 197ms	remaining: 1.01s
163:	learn: 1.0305798	total: 198ms	remaining: 1.01s
164:	learn: 1.0240344	total: 199ms	remaining: 1.01s
165:	learn: 1.0218907	total: 201ms	remaining: 1.01s
166:	learn: 1.0149920	total: 202ms	remaining: 1s
167:	learn: 1.0113321	total: 203ms	remaining: 1s
168:	learn: 1.0094845	total: 204ms	remaining: 1s
169:	learn: 1.0083543	total: 206ms	remaining: 1s
170:	learn: 1.0055091	total: 207ms	remaining: 1s
171:	learn: 0.9983745	total: 208ms	remaining: 1s
172:	learn: 0.9974960	total: 209ms	remaining: 998ms
173:	learn: 0.9928169	total: 210ms	remaining: 998ms
174:	learn: 0.9833963	total: 212ms	remaining: 1000ms
175:	learn: 0.9789272	total: 213ms	remaining: 998ms
176:	learn: 0.9758001	total: 214ms	remaining: 996ms
177:	learn: 0.9711618	total: 215ms	remaining: 995ms
178:	learn: 0.9659025	total: 217ms	remaining: 994ms
179:	learn: 0.9625513	total: 218ms	remaining: 994ms
180:	learn: 0.9582536	total: 219ms	remaining: 993ms
181:	learn: 0.9540786	total: 221ms	remaining: 992ms
182:	learn: 0.9480817	total: 222ms	remaining: 992ms
183:	learn: 0.9432731	total: 224ms	remaining: 991ms
184:	learn: 0.9371813	total: 225ms	remaining: 990ms
185:	learn: 0.9327369	total: 226ms	remaining: 989ms
186:	learn: 0.9305138	total: 227ms	remaining: 988ms
187:	learn: 0.9247557	total: 229ms	remaining: 987ms
188:	learn: 0.9237362	total: 230ms	remaining: 987ms
189:	learn: 0.9199995	total: 231ms	remaining: 987ms
190:	learn: 0.9166543	total: 233ms	remaining: 985ms
191:	learn: 0.9135777	total: 234ms	remaining: 985ms
192:	learn: 0.9105407	total: 235ms	remaining: 985ms
193:	learn: 0.9079517	total: 238ms	remaining: 987ms
194:	learn: 0.8986605	total: 241ms	remaining: 993ms
195:	learn: 0.8916077	total: 242ms	remaining: 993ms
196:	learn: 0.8858984	total: 243ms	remaining: 991ms
197:	learn: 0.8826194	total: 244ms	remaining: 989ms
198:	learn: 0.8792496	total: 245ms	remaining: 988ms
199:	learn: 0.8752132	total: 247ms	remaining: 986ms
200:	learn: 0.8713594	total: 248ms	remaining: 984ms
201:	learn: 0.8674256	total: 249ms	remaining: 983ms
202:	learn: 0.8636128	total: 250ms	remaining: 981ms
203:	learn: 0.8600573	total: 251ms	remaining: 980ms
204:	learn: 0.8568048	total: 252ms	remaining: 979ms
205:	learn: 0.8493542	total: 254ms	remaining: 980ms
206:	learn: 0.8426264	total: 256ms	remaining: 979ms
207:	learn: 0.8371323	total: 257ms	remaining: 978ms
208:	learn: 0.8328556	total: 258ms	remaining: 977ms
209:	learn: 0.8278404	total: 259ms	remaining: 975ms
210:	learn: 0.8244930	total: 260ms	remaining: 973ms
211:	learn: 0.8218891	total: 261ms	remaining: 971ms
212:	learn: 0.8174548	total: 262ms	remaining: 970ms
213:	learn: 0.8148770	total: 264ms	remaining: 968ms
214:	learn: 0.8083427	total: 265ms	remaining: 967ms
215:	learn: 0.8023211	total: 266ms	remaining: 965ms
216:	learn: 0.7982409	total: 269ms	remaining: 971ms
217:	learn: 0.7957003	total: 272ms	remaining: 974ms
218:	learn: 0.7902806	total: 274ms	remaining: 976ms
219:	learn: 0.7877466	total: 276ms	remaining: 978ms
220:	learn: 0.7810399	total: 278ms	remaining: 982ms
221:	learn: 0.7770733	total: 281ms	remaining: 984ms
222:	learn: 0.7715989	total: 282ms	remaining: 984ms
223:	learn: 0.7663033	total: 286ms	remaining: 990ms
224:	learn: 0.7627070	total: 288ms	remaining: 993ms
225:	learn: 0.7596320	total: 290ms	remaining: 992ms
226:	learn: 0.7542173	total: 291ms	remaining: 991ms
227:	learn: 0.7507592	total: 292ms	remaining: 989ms
228:	learn: 0.7468066	total: 293ms	remaining: 987ms
229:	learn: 0.7420999	total: 294ms	remaining: 986ms
230:	learn: 0.7374173	total: 295ms	remaining: 983ms
231:	learn: 0.7340065	total: 297ms	remaining: 982ms
232:	learn: 0.7304554	total: 298ms	remaining: 980ms
233:	learn: 0.7253008	total: 299ms	remaining: 979ms
234:	learn: 0.7203779	total: 300ms	remaining: 977ms
235:	learn: 0.7150397	total: 302ms	remaining: 976ms
236:	learn: 0.7127686	total: 303ms	remaining: 975ms
237:	learn: 0.7067761	total: 304ms	remaining: 973ms
238:	learn: 0.7025379	total: 305ms	remaining: 972ms
239:	learn: 0.6988680	total: 307ms	remaining: 971ms
240:	learn: 0.6972566	total: 308ms	remaining: 969ms
241:	learn: 0.6946666	total: 309ms	remaining: 968ms
242:	learn: 0.6902515	total: 310ms	remaining: 966ms
243:	learn: 0.6865853	total: 311ms	remaining: 965ms
244:	learn: 0.6844727	total: 313ms	remaining: 963ms
245:	learn: 0.6825780	total: 314ms	remaining: 962ms
246:	learn: 0.6782590	total: 315ms	remaining: 960ms
247:	learn: 0.6745907	total: 316ms	remaining: 959ms
248:	learn: 0.6724849	total: 318ms	remaining: 958ms
249:	learn: 0.6693950	total: 319ms	remaining: 956ms
250:	learn: 0.6662828	total: 320ms	remaining: 954ms
251:	learn: 0.6623933	total: 321ms	remaining: 953ms
252:	learn: 0.6593004	total: 322ms	remaining: 951ms
253:	learn: 0.6557274	total: 323ms	remaining: 949ms
254:	learn: 0.6544936	total: 324ms	remaining: 948ms
255:	learn: 0.6531677	total: 325ms	remaining: 946ms
256:	learn: 0.6514554	total: 327ms	remaining: 944ms
257:	learn: 0.6511145	total: 328ms	remaining: 942ms
258:	learn: 0.6475667	total: 329ms	remaining: 941ms
259:	learn: 0.6456817	total: 330ms	remaining: 940ms
260:	learn: 0.6426063	total: 332ms	remaining: 939ms
261:	learn: 0.6405176	total: 333ms	remaining: 938ms
262:	learn: 0.6385533	total: 334ms	remaining: 936ms
263:	learn: 0.6382296	total: 335ms	remaining: 934ms
264:	learn: 0.6335928	total: 336ms	remaining: 932ms
265:	learn: 0.6312144	total: 337ms	remaining: 931ms
266:	learn: 0.6287413	total: 339ms	remaining: 930ms
267:	learn: 0.6274831	total: 340ms	remaining: 928ms
268:	learn: 0.6243772	total: 341ms	remaining: 927ms
269:	learn: 0.6214849	total: 342ms	remaining: 925ms
270:	learn: 0.6196227	total: 343ms	remaining: 923ms
271:	learn: 0.6177567	total: 344ms	remaining: 921ms
272:	learn: 0.6158353	total: 346ms	remaining: 920ms
273:	learn: 0.6137002	total: 347ms	remaining: 919ms
274:	learn: 0.6096582	total: 349ms	remaining: 919ms
275:	learn: 0.6064527	total: 350ms	remaining: 917ms
276:	learn: 0.6032546	total: 351ms	remaining: 916ms
277:	learn: 0.5996315	total: 352ms	remaining: 914ms
278:	learn: 0.5975751	total: 353ms	remaining: 913ms
279:	learn: 0.5948304	total: 354ms	remaining: 911ms
280:	learn: 0.5941867	total: 355ms	remaining: 909ms
281:	learn: 0.5915636	total: 357ms	remaining: 908ms
282:	learn: 0.5900520	total: 358ms	remaining: 906ms
283:	learn: 0.5882470	total: 359ms	remaining: 904ms
284:	learn: 0.5866747	total: 360ms	remaining: 903ms
285:	learn: 0.5863831	total: 361ms	remaining: 901ms
286:	learn: 0.5844731	total: 363ms	remaining: 902ms
287:	learn: 0.5795786	total: 364ms	remaining: 901ms
288:	learn: 0.5783657	total: 365ms	remaining: 899ms
289:	learn: 0.5758838	total: 367ms	remaining: 898ms
290:	learn: 0.5727231	total: 368ms	remaining: 896ms
291:	learn: 0.5712840	total: 369ms	remaining: 895ms
292:	learn: 0.5688173	total: 370ms	remaining: 893ms
293:	learn: 0.5653889	total: 371ms	remaining: 891ms
294:	learn: 0.5633190	total: 372ms	remaining: 890ms
295:	learn: 0.5624923	total: 374ms	remaining: 890ms
296:	learn: 0.5622540	total: 375ms	remaining: 888ms
297:	learn: 0.5587551	total: 376ms	remaining: 887ms
298:	learn: 0.5575178	total: 378ms	remaining: 886ms
299:	learn: 0.5562848	total: 379ms	remaining: 884ms
300:	learn: 0.5527198	total: 380ms	remaining: 883ms
301:	learn: 0.5483328	total: 381ms	remaining: 882ms
302:	learn: 0.5438312	total: 383ms	remaining: 880ms
303:	learn: 0.5424271	total: 384ms	remaining: 878ms
304:	learn: 0.5381731	total: 385ms	remaining: 877ms
305:	learn: 0.5363448	total: 386ms	remaining: 876ms
306:	learn: 0.5319999	total: 388ms	remaining: 875ms
307:	learn: 0.5317592	total: 389ms	remaining: 874ms
308:	learn: 0.5280785	total: 390ms	remaining: 872ms
309:	learn: 0.5268991	total: 391ms	remaining: 871ms
310:	learn: 0.5260629	total: 393ms	remaining: 870ms
311:	learn: 0.5248599	total: 394ms	remaining: 868ms
312:	learn: 0.5220380	total: 395ms	remaining: 867ms
313:	learn: 0.5209379	total: 396ms	remaining: 866ms
314:	learn: 0.5199012	total: 398ms	remaining: 864ms
315:	learn: 0.5172018	total: 399ms	remaining: 863ms
316:	learn: 0.5162282	total: 400ms	remaining: 862ms
317:	learn: 0.5150596	total: 401ms	remaining: 861ms
318:	learn: 0.5142454	total: 403ms	remaining: 859ms
319:	learn: 0.5128425	total: 404ms	remaining: 858ms
320:	learn: 0.5100830	total: 405ms	remaining: 857ms
321:	learn: 0.5084914	total: 406ms	remaining: 855ms
322:	learn: 0.5075038	total: 407ms	remaining: 854ms
323:	learn: 0.5057790	total: 409ms	remaining: 853ms
324:	learn: 0.5033982	total: 410ms	remaining: 852ms
325:	learn: 0.5024449	total: 411ms	remaining: 851ms
326:	learn: 0.5015184	total: 413ms	remaining: 849ms
327:	learn: 0.4998088	total: 414ms	remaining: 848ms
328:	learn: 0.4989903	total: 415ms	remaining: 847ms
329:	learn: 0.4981381	total: 417ms	remaining: 846ms
330:	learn: 0.4962369	total: 418ms	remaining: 844ms
331:	learn: 0.4953567	total: 419ms	remaining: 843ms
332:	learn: 0.4940548	total: 420ms	remaining: 841ms
333:	learn: 0.4930601	total: 421ms	remaining: 840ms
334:	learn: 0.4922900	total: 422ms	remaining: 838ms
335:	learn: 0.4915226	total: 423ms	remaining: 837ms
336:	learn: 0.4892054	total: 425ms	remaining: 837ms
337:	learn: 0.4864569	total: 427ms	remaining: 836ms
338:	learn: 0.4839228	total: 428ms	remaining: 834ms
339:	learn: 0.4817386	total: 429ms	remaining: 833ms
340:	learn: 0.4796025	total: 430ms	remaining: 831ms
341:	learn: 0.4780023	total: 431ms	remaining: 830ms
342:	learn: 0.4756345	total: 433ms	remaining: 829ms
343:	learn: 0.4735393	total: 434ms	remaining: 827ms
344:	learn: 0.4729969	total: 435ms	remaining: 826ms
345:	learn: 0.4717548	total: 436ms	remaining: 824ms
346:	learn: 0.4709515	total: 437ms	remaining: 822ms
347:	learn: 0.4691152	total: 438ms	remaining: 821ms
348:	learn: 0.4682712	total: 439ms	remaining: 819ms
349:	learn: 0.4668549	total: 441ms	remaining: 819ms
350:	learn: 0.4662740	total: 442ms	remaining: 817ms
351:	learn: 0.4651358	total: 443ms	remaining: 816ms
352:	learn: 0.4629071	total: 444ms	remaining: 815ms
353:	learn: 0.4608355	total: 445ms	remaining: 813ms
354:	learn: 0.4592011	total: 447ms	remaining: 811ms
355:	learn: 0.4554909	total: 448ms	remaining: 810ms
356:	learn: 0.4534011	total: 449ms	remaining: 809ms
357:	learn: 0.4513230	total: 450ms	remaining: 807ms
358:	learn: 0.4506234	total: 451ms	remaining: 806ms
359:	learn: 0.4493134	total: 452ms	remaining: 804ms
360:	learn: 0.4475295	total: 453ms	remaining: 803ms
361:	learn: 0.4459968	total: 454ms	remaining: 801ms
362:	learn: 0.4442587	total: 456ms	remaining: 800ms
363:	learn: 0.4418948	total: 457ms	remaining: 799ms
364:	learn: 0.4403307	total: 458ms	remaining: 797ms
365:	learn: 0.4397184	total: 459ms	remaining: 796ms
366:	learn: 0.4372505	total: 461ms	remaining: 794ms
367:	learn: 0.4351656	total: 462ms	remaining: 793ms
368:	learn: 0.4335428	total: 463ms	remaining: 792ms
369:	learn: 0.4323830	total: 464ms	remaining: 790ms
370:	learn: 0.4313286	total: 465ms	remaining: 789ms
371:	learn: 0.4291882	total: 466ms	remaining: 787ms
372:	learn: 0.4272589	total: 467ms	remaining: 786ms
373:	learn: 0.4242863	total: 468ms	remaining: 784ms
374:	learn: 0.4224082	total: 470ms	remaining: 783ms
375:	learn: 0.4214512	total: 471ms	remaining: 781ms
376:	learn: 0.4206345	total: 472ms	remaining: 781ms
377:	learn: 0.4191885	total: 474ms	remaining: 779ms
378:	learn: 0.4170831	total: 475ms	remaining: 778ms
379:	learn: 0.4158571	total: 476ms	remaining: 777ms
380:	learn: 0.4148486	total: 477ms	remaining: 775ms

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fitting SVR for C2X_rhow_9x9_depth_lt_1
Fitting KNN for C2X_rhow_9x9_depth_lt_1
Fitting LR for C2X_rhow_9x9_depth_lt_1
Fitting RF for C2X_rhow_9x9_depth_lt_1
Fitting CAT for C2X_rhow_9x9_depth_lt_1
Learning rate set to 0.033272
0:	learn: 3.4183555	total: 2.89ms	remaining: 2.89s
1:	learn: 3.3733908	total: 4.15ms	remaining: 2.07s
2:	learn: 3.3311631	total: 5.33ms	remaining: 1.77s
3:	learn: 3.2851076	total: 6.68ms	remaining: 1.66s
4:	learn: 3.2407684	total: 7.95ms	remaining: 1.58s
5:	learn: 3.1895832	total: 9.46ms	remaining: 1.57s
6:	learn: 3.1497605	total: 11.1ms	remaining: 1.58s
7:	learn: 3.1144436	total: 12.5ms	remaining: 1.55s
8:	learn: 3.0736218	total: 13.8ms	remaining: 1.51s
9:	learn: 3.0345289	total: 15ms	remaining: 1.49s
10:	learn: 2.9967256	total: 16.3ms	remaining: 1.46s
11:	learn: 2.9616735	total: 17.6ms	remaining: 1.45s
12:	learn: 2.9258026	total: 18.8ms	remaining: 1.43s
13:	learn: 2.8961841	total: 20.2ms	remaining: 1.42s
14:	learn: 2.8611437	total: 21.5ms	remaining: 1.42s
15:	learn: 2.8325986	total: 22.9ms	remaining: 1.41s
16:	learn: 2.7961779	total: 24.9ms	remaining: 1.44s
17:	learn: 2.7605192	total: 26.3ms	remaining: 1.44s
18:	learn: 2.7235710	total: 27.6ms	remaining: 1.42s
19:	learn: 2.6869205	total: 29ms	remaining: 1.42s
20:	learn: 2.6575010	total: 30.3ms	remaining: 1.41s
21:	learn: 2.6332927	total: 31.6ms	remaining: 1.4s
22:	learn: 2.6064519	total: 33ms	remaining: 1.4s
23:	learn: 2.5817252	total: 34.3ms	remaining: 1.4s
24:	learn: 2.5557618	total: 35.7ms	remaining: 1.39s
25:	learn: 2.5275048	total: 37.1ms	remaining: 1.39s
26:	learn: 2.5014578	total: 38.6ms	remaining: 1.39s
27:	learn: 2.4738428	total: 40.2ms	remaining: 1.4s
28:	learn: 2.4481662	total: 42.1ms	remaining: 1.41s
29:	learn: 2.4268442	total: 43.5ms	remaining: 1.41s
30:	learn: 2.4065917	total: 45ms	remaining: 1.41s
31:	learn: 2.3784003	total: 46.4ms	remaining: 1.4s
32:	learn: 2.3522813	total: 47.7ms	remaining: 1.4s
33:	learn: 2.3305740	total: 49.1ms	remaining: 1.4s
34:	learn: 2.3089354	total: 50.5ms	remaining: 1.39s
35:	learn: 2.2855256	total: 51.9ms	remaining: 1.39s
36:	learn: 2.2554392	total: 53.3ms	remaining: 1.39s
37:	learn: 2.2405341	total: 54.8ms	remaining: 1.39s
38:	learn: 2.2120863	total: 56.5ms	remaining: 1.39s
39:	learn: 2.1851962	total: 57.9ms	remaining: 1.39s
40:	learn: 2.1591908	total: 59.3ms	remaining: 1.39s
41:	learn: 2.1377743	total: 60.7ms	remaining: 1.38s
42:	learn: 2.1239127	total: 62ms	remaining: 1.38s
43:	learn: 2.0999424	total: 63.4ms	remaining: 1.38s
44:	learn: 2.0776024	total: 64.6ms	remaining: 1.37s
45:	learn: 2.0602536	total: 65.9ms	remaining: 1.37s
46:	learn: 2.0501080	total: 67.3ms	remaining: 1.36s
47:	learn: 2.0272471	total: 68.6ms	remaining: 1.36s
48:	learn: 2.0099628	total: 70.1ms	remaining: 1.36s
49:	learn: 1.9914316	total: 71.7ms	remaining: 1.36s
50:	learn: 1.9775284	total: 73.2ms	remaining: 1.36s
51:	learn: 1.9630461	total: 74.4ms	remaining: 1.36s
52:	learn: 1.9424929	total: 75.9ms	remaining: 1.36s
53:	learn: 1.9293406	total: 77.4ms	remaining: 1.35s
54:	learn: 1.9133872	total: 78.7ms	remaining: 1.35s
55:	learn: 1.8937805	total: 80.1ms	remaining: 1.35s
56:	learn: 1.8810461	total: 81.5ms	remaining: 1.35s
57:	learn: 1.8722050	total: 82.9ms	remaining: 1.35s
58:	learn: 1.8599846	total: 84.5ms	remaining: 1.35s
59:	learn: 1.8441918	total: 86ms	remaining: 1.35s
60:	learn: 1.8292166	total: 87.5ms	remaining: 1.35s
61:	learn: 1.8178711	total: 89.1ms	remaining: 1.35s
62:	learn: 1.8084856	total: 90.6ms	remaining: 1.35s
63:	learn: 1.8003872	total: 92ms	remaining: 1.34s
64:	learn: 1.7807572	total: 93.4ms	remaining: 1.34s
65:	learn: 1.7588286	total: 94.8ms	remaining: 1.34s
66:	learn: 1.7451763	total: 96.1ms	remaining: 1.34s
67:	learn: 1.7350130	total: 97.5ms	remaining: 1.33s
68:	learn: 1.7259268	total: 98.8ms	remaining: 1.33s
69:	learn: 1.7065421	total: 100ms	remaining: 1.33s
70:	learn: 1.6961704	total: 102ms	remaining: 1.33s
71:	learn: 1.6829408	total: 104ms	remaining: 1.33s
72:	learn: 1.6768227	total: 105ms	remaining: 1.33s
73:	learn: 1.6633893	total: 106ms	remaining: 1.33s
74:	learn: 1.6531326	total: 108ms	remaining: 1.33s
75:	learn: 1.6420529	total: 109ms	remaining: 1.33s
76:	learn: 1.6344812	total: 110ms	remaining: 1.32s
77:	learn: 1.6166182	total: 112ms	remaining: 1.32s
78:	learn: 1.6047774	total: 113ms	remaining: 1.32s
79:	learn: 1.5944054	total: 114ms	remaining: 1.32s
80:	learn: 1.5831473	total: 116ms	remaining: 1.31s
81:	learn: 1.5732445	total: 118ms	remaining: 1.32s
82:	learn: 1.5675864	total: 119ms	remaining: 1.31s
83:	learn: 1.5553934	total: 120ms	remaining: 1.31s
84:	learn: 1.5482339	total: 122ms	remaining: 1.31s
85:	learn: 1.5389747	total: 123ms	remaining: 1.31s
86:	learn: 1.5254347	total: 124ms	remaining: 1.3s
87:	learn: 1.5145116	total: 126ms	remaining: 1.3s
88:	learn: 1.5036248	total: 127ms	remaining: 1.3s
89:	learn: 1.4897601	total: 129ms	remaining: 1.3s
90:	learn: 1.4734188	total: 130ms	remaining: 1.3s
91:	learn: 1.4679813	total: 131ms	remaining: 1.29s
92:	learn: 1.4619288	total: 133ms	remaining: 1.3s
93:	learn: 1.4497146	total: 134ms	remaining: 1.29s
94:	learn: 1.4449099	total: 136ms	remaining: 1.29s
95:	learn: 1.4325861	total: 137ms	remaining: 1.29s
96:	learn: 1.4253274	total: 139ms	remaining: 1.29s
97:	learn: 1.4157928	total: 140ms	remaining: 1.29s
98:	learn: 1.4091289	total: 141ms	remaining: 1.28s
99:	learn: 1.4000353	total: 143ms	remaining: 1.28s
100:	learn: 1.3904305	total: 144ms	remaining: 1.28s
101:	learn: 1.3827689	total: 145ms	remaining: 1.28s
102:	learn: 1.3745824	total: 147ms	remaining: 1.28s
103:	learn: 1.3653667	total: 149ms	remaining: 1.28s
104:	learn: 1.3571237	total: 150ms	remaining: 1.28s
105:	learn: 1.3479646	total: 152ms	remaining: 1.28s
106:	learn: 1.3390765	total: 153ms	remaining: 1.28s
107:	learn: 1.3288166	total: 154ms	remaining: 1.27s
108:	learn: 1.3251181	total: 156ms	remaining: 1.27s
109:	learn: 1.3196345	total: 157ms	remaining: 1.27s
110:	learn: 1.3109333	total: 159ms	remaining: 1.27s
111:	learn: 1.3020292	total: 160ms	remaining: 1.27s
112:	learn: 1.2991117	total: 162ms	remaining: 1.27s
113:	learn: 1.2912130	total: 163ms	remaining: 1.27s
114:	learn: 1.2817757	total: 165ms	remaining: 1.27s
115:	learn: 1.2693317	total: 166ms	remaining: 1.27s
116:	learn: 1.2618765	total: 168ms	remaining: 1.26s
117:	learn: 1.2517679	total: 169ms	remaining: 1.26s
118:	learn: 1.2482574	total: 170ms	remaining: 1.26s
119:	learn: 1.2449513	total: 172ms	remaining: 1.26s
120:	learn: 1.2405813	total: 173ms	remaining: 1.26s
121:	learn: 1.2346109	total: 175ms	remaining: 1.26s
122:	learn: 1.2254292	total: 177ms	remaining: 1.26s
123:	learn: 1.2153920	total: 179ms	remaining: 1.26s
124:	learn: 1.2052478	total: 180ms	remaining: 1.26s
125:	learn: 1.2026068	total: 182ms	remaining: 1.26s
126:	learn: 1.2009853	total: 183ms	remaining: 1.26s
127:	learn: 1.1911199	total: 184ms	remaining: 1.25s
128:	learn: 1.1850745	total: 186ms	remaining: 1.25s
129:	learn: 1.1839882	total: 187ms	remaining: 1.25s
130:	learn: 1.1788774	total: 189ms	remaining: 1.25s
131:	learn: 1.1735559	total: 190ms	remaining: 1.25s
132:	learn: 1.1665925	total: 192ms	remaining: 1.25s
133:	learn: 1.1606190	total: 193ms	remaining: 1.25s
134:	learn: 1.1545743	total: 195ms	remaining: 1.25s
135:	learn: 1.1471181	total: 196ms	remaining: 1.24s
136:	learn: 1.1401031	total: 198ms	remaining: 1.24s
137:	learn: 1.1306848	total: 199ms	remaining: 1.24s
138:	learn: 1.1238305	total: 201ms	remaining: 1.24s
139:	learn: 1.1153300	total: 202ms	remaining: 1.24s
140:	learn: 1.1104793	total: 204ms	remaining: 1.24s
141:	learn: 1.1079201	total: 205ms	remaining: 1.24s
142:	learn: 1.1005734	total: 207ms	remaining: 1.24s
143:	learn: 1.0978511	total: 208ms	remaining: 1.24s
144:	learn: 1.0965971	total: 210ms	remaining: 1.24s
145:	learn: 1.0913884	total: 212ms	remaining: 1.24s
146:	learn: 1.0845697	total: 213ms	remaining: 1.24s
147:	learn: 1.0739347	total: 215ms	remaining: 1.24s
148:	learn: 1.0664055	total: 216ms	remaining: 1.23s
149:	learn: 1.0636947	total: 218ms	remaining: 1.23s
150:	learn: 1.0583452	total: 219ms	remaining: 1.23s
151:	learn: 1.0524273	total: 221ms	remaining: 1.23s
152:	learn: 1.0466215	total: 222ms	remaining: 1.23s
153:	learn: 1.0405978	total: 224ms	remaining: 1.23s
154:	learn: 1.0340972	total: 225ms	remaining: 1.23s
155:	learn: 1.0275165	total: 227ms	remaining: 1.23s
156:	learn: 1.0176982	total: 228ms	remaining: 1.22s
157:	learn: 1.0130026	total: 229ms	remaining: 1.22s
158:	learn: 1.0073446	total: 231ms	remaining: 1.22s
159:	learn: 1.0040506	total: 233ms	remaining: 1.22s
160:	learn: 0.9972927	total: 234ms	remaining: 1.22s
161:	learn: 0.9911527	total: 236ms	remaining: 1.22s
162:	learn: 0.9840732	total: 238ms	remaining: 1.22s
163:	learn: 0.9776523	total: 239ms	remaining: 1.22s
164:	learn: 0.9714982	total: 241ms	remaining: 1.22s
165:	learn: 0.9666141	total: 242ms	remaining: 1.22s
166:	learn: 0.9604688	total: 244ms	remaining: 1.22s
167:	learn: 0.9519032	total: 245ms	remaining: 1.21s
168:	learn: 0.9468627	total: 246ms	remaining: 1.21s
169:	learn: 0.9442619	total: 248ms	remaining: 1.21s
170:	learn: 0.9395926	total: 249ms	remaining: 1.21s
171:	learn: 0.9381146	total: 251ms	remaining: 1.21s
172:	learn: 0.9326930	total: 252ms	remaining: 1.21s
173:	learn: 0.9263043	total: 254ms	remaining: 1.21s
174:	learn: 0.9210449	total: 255ms	remaining: 1.2s
175:	learn: 0.9191801	total: 257ms	remaining: 1.2s
176:	learn: 0.9149697	total: 258ms	remaining: 1.2s
177:	learn: 0.9108367	total: 260ms	remaining: 1.2s
178:	learn: 0.9076064	total: 261ms	remaining: 1.2s
179:	learn: 0.9010382	total: 263ms	remaining: 1.2s
180:	learn: 0.8957824	total: 264ms	remaining: 1.2s
181:	learn: 0.8941506	total: 266ms	remaining: 1.2s
182:	learn: 0.8869184	total: 268ms	remaining: 1.19s
183:	learn: 0.8828523	total: 269ms	remaining: 1.19s
184:	learn: 0.8813692	total: 270ms	remaining: 1.19s
185:	learn: 0.8767067	total: 272ms	remaining: 1.19s
186:	learn: 0.8722880	total: 273ms	remaining: 1.19s
187:	learn: 0.8663120	total: 274ms	remaining: 1.19s
188:	learn: 0.8614087	total: 276ms	remaining: 1.18s
189:	learn: 0.8599224	total: 277ms	remaining: 1.18s
190:	learn: 0.8556244	total: 279ms	remaining: 1.18s
191:	learn: 0.8523711	total: 280ms	remaining: 1.18s
192:	learn: 0.8502598	total: 282ms	remaining: 1.18s
193:	learn: 0.8495183	total: 283ms	remaining: 1.18s
194:	learn: 0.8456457	total: 285ms	remaining: 1.17s
195:	learn: 0.8382515	total: 286ms	remaining: 1.17s
196:	learn: 0.8330136	total: 287ms	remaining: 1.17s
197:	learn: 0.8292216	total: 289ms	remaining: 1.17s
198:	learn: 0.8257991	total: 290ms	remaining: 1.17s
199:	learn: 0.8210226	total: 291ms	remaining: 1.17s
200:	learn: 0.8171618	total: 293ms	remaining: 1.16s
201:	learn: 0.8125420	total: 294ms	remaining: 1.16s
202:	learn: 0.8078090	total: 296ms	remaining: 1.16s
203:	learn: 0.8019435	total: 298ms	remaining: 1.16s
204:	learn: 0.7995437	total: 299ms	remaining: 1.16s
205:	learn: 0.7962555	total: 301ms	remaining: 1.16s
206:	learn: 0.7933017	total: 302ms	remaining: 1.16s
207:	learn: 0.7895165	total: 303ms	remaining: 1.15s
208:	learn: 0.7863099	total: 305ms	remaining: 1.15s
209:	learn: 0.7828763	total: 306ms	remaining: 1.15s
210:	learn: 0.7783867	total: 307ms	remaining: 1.15s
211:	learn: 0.7751039	total: 309ms	remaining: 1.15s
212:	learn: 0.7696137	total: 311ms	remaining: 1.15s
213:	learn: 0.7645025	total: 312ms	remaining: 1.15s
214:	learn: 0.7614893	total: 314ms	remaining: 1.14s
215:	learn: 0.7585242	total: 315ms	remaining: 1.14s
216:	learn: 0.7552500	total: 316ms	remaining: 1.14s
217:	learn: 0.7519561	total: 318ms	remaining: 1.14s
218:	learn: 0.7476530	total: 319ms	remaining: 1.14s
219:	learn: 0.7446612	total: 321ms	remaining: 1.14s
220:	learn: 0.7397058	total: 322ms	remaining: 1.13s
221:	learn: 0.7358458	total: 323ms	remaining: 1.13s
222:	learn: 0.7303208	total: 325ms	remaining: 1.13s
223:	learn: 0.7250131	total: 327ms	remaining: 1.13s
224:	learn: 0.7221004	total: 328ms	remaining: 1.13s
225:	learn: 0.7194310	total: 329ms	remaining: 1.13s
226:	learn: 0.7162618	total: 331ms	remaining: 1.13s
227:	learn: 0.7117079	total: 332ms	remaining: 1.12s
228:	learn: 0.7070546	total: 333ms	remaining: 1.12s
229:	learn: 0.7025906	total: 335ms	remaining: 1.12s
230:	learn: 0.6999252	total: 336ms	remaining: 1.12s
231:	learn: 0.6963807	total: 338ms	remaining: 1.12s
232:	learn: 0.6928146	total: 339ms	remaining: 1.11s
233:	learn: 0.6898319	total: 341ms	remaining: 1.11s
234:	learn: 0.6853043	total: 342ms	remaining: 1.11s
235:	learn: 0.6827856	total: 344ms	remaining: 1.11s
236:	learn: 0.6799340	total: 345ms	remaining: 1.11s
237:	learn: 0.6775226	total: 347ms	remaining: 1.11s
238:	learn: 0.6731108	total: 349ms	remaining: 1.11s
239:	learn: 0.6702909	total: 350ms	remaining: 1.11s
240:	learn: 0.6674112	total: 352ms	remaining: 1.11s
241:	learn: 0.6643937	total: 353ms	remaining: 1.11s
242:	learn: 0.6620220	total: 355ms	remaining: 1.11s
243:	learn: 0.6588254	total: 358ms	remaining: 1.11s
244:	learn: 0.6541597	total: 360ms	remaining: 1.11s
245:	learn: 0.6496556	total: 361ms	remaining: 1.11s
246:	learn: 0.6472474	total: 362ms	remaining: 1.1s
247:	learn: 0.6441657	total: 364ms	remaining: 1.1s
248:	learn: 0.6402100	total: 365ms	remaining: 1.1s
249:	learn: 0.6361956	total: 367ms	remaining: 1.1s
250:	learn: 0.6321308	total: 368ms	remaining: 1.1s
251:	learn: 0.6297081	total: 370ms	remaining: 1.1s
252:	learn: 0.6257814	total: 372ms	remaining: 1.1s
253:	learn: 0.6231904	total: 374ms	remaining: 1.1s
254:	learn: 0.6195984	total: 376ms	remaining: 1.1s
255:	learn: 0.6165098	total: 377ms	remaining: 1.09s
256:	learn: 0.6143989	total: 378ms	remaining: 1.09s
257:	learn: 0.6117364	total: 380ms	remaining: 1.09s
258:	learn: 0.6081989	total: 381ms	remaining: 1.09s
259:	learn: 0.6056076	total: 382ms	remaining: 1.09s
260:	learn: 0.6019135	total: 384ms	remaining: 1.09s
261:	learn: 0.5988780	total: 385ms	remaining: 1.08s
262:	learn: 0.5961916	total: 387ms	remaining: 1.08s
263:	learn: 0.5930680	total: 389ms	remaining: 1.08s
264:	learn: 0.5905696	total: 390ms	remaining: 1.08s
265:	learn: 0.5873142	total: 392ms	remaining: 1.08s
266:	learn: 0.5861629	total: 393ms	remaining: 1.08s
267:	learn: 0.5838019	total: 394ms	remaining: 1.08s
268:	learn: 0.5803331	total: 396ms	remaining: 1.07s
269:	learn: 0.5773434	total: 397ms	remaining: 1.07s
270:	learn: 0.5743330	total: 400ms	remaining: 1.07s
271:	learn: 0.5711615	total: 401ms	remaining: 1.07s
272:	learn: 0.5693690	total: 402ms	remaining: 1.07s
273:	learn: 0.5678283	total: 404ms	remaining: 1.07s
274:	learn: 0.5656413	total: 405ms	remaining: 1.07s
275:	learn: 0.5638815	total: 407ms	remaining: 1.07s
276:	learn: 0.5626701	total: 408ms	remaining: 1.06s
277:	learn: 0.5612187	total: 409ms	remaining: 1.06s
278:	learn: 0.5583974	total: 411ms	remaining: 1.06s
279:	learn: 0.5564860	total: 412ms	remaining: 1.06s
280:	learn: 0.5548671	total: 413ms	remaining: 1.06s
281:	learn: 0.5525813	total: 415ms	remaining: 1.06s
282:	learn: 0.5499702	total: 416ms	remaining: 1.05s
283:	learn: 0.5482536	total: 418ms	remaining: 1.05s
284:	learn: 0.5457653	total: 419ms	remaining: 1.05s
285:	learn: 0.5428461	total: 421ms	remaining: 1.05s
286:	learn: 0.5416476	total: 422ms	remaining: 1.05s
287:	learn: 0.5395656	total: 423ms	remaining: 1.05s
288:	learn: 0.5376323	total: 425ms	remaining: 1.04s
289:	learn: 0.5352090	total: 426ms	remaining: 1.04s
290:	learn: 0.5340705	total: 428ms	remaining: 1.04s
291:	learn: 0.5327335	total: 429ms	remaining: 1.04s
292:	learn: 0.5299080	total: 431ms	remaining: 1.04s
293:	learn: 0.5280491	total: 435ms	remaining: 1.04s
294:	learn: 0.5268660	total: 438ms	remaining: 1.04s
295:	learn: 0.5259089	total: 440ms	remaining: 1.04s
296:	learn: 0.5245173	total: 443ms	remaining: 1.05s
297:	learn: 0.5239889	total: 445ms	remaining: 1.05s
298:	learn: 0.5219728	total: 447ms	remaining: 1.05s
299:	learn: 0.5184576	total: 449ms	remaining: 1.05s
300:	learn: 0.5167656	total: 450ms	remaining: 1.04s
301:	learn: 0.5162580	total: 451ms	remaining: 1.04s
302:	learn: 0.5138039	total: 453ms	remaining: 1.04s
303:	learn: 0.5115423	total: 454ms	remaining: 1.04s
304:	learn: 0.5098788	total: 455ms	remaining: 1.04s
305:	learn: 0.5082054	total: 456ms	remaining: 1.03s
306:	learn: 0.5068018	total: 457ms	remaining: 1.03s
307:	learn: 0.5043771	total: 459ms	remaining: 1.03s
308:	learn: 0.5032068	total: 460ms	remaining: 1.03s
309:	learn: 0.5004381	total: 462ms	remaining: 1.03s
310:	learn: 0.4996215	total: 464ms	remaining: 1.03s
311:	learn: 0.4978444	total: 465ms	remaining: 1.02s
312:	learn: 0.4968148	total: 467ms	remaining: 1.02s
313:	learn: 0.4945960	total: 468ms	remaining: 1.02s
314:	learn: 0.4938715	total: 469ms	remaining: 1.02s
315:	learn: 0.4930703	total: 471ms	remaining: 1.02s
316:	learn: 0.4914823	total: 472ms	remaining: 1.02s
317:	learn: 0.4883123	total: 474ms	remaining: 1.01s
318:	learn: 0.4875829	total: 475ms	remaining: 1.01s
319:	learn: 0.4861273	total: 476ms	remaining: 1.01s
320:	learn: 0.4846132	total: 478ms	remaining: 1.01s
321:	learn: 0.4826876	total: 480ms	remaining: 1.01s
322:	learn: 0.4808336	total: 481ms	remaining: 1.01s
323:	learn: 0.4795403	total: 483ms	remaining: 1.01s
324:	learn: 0.4767928	total: 484ms	remaining: 1s
325:	learn: 0.4739453	total: 485ms	remaining: 1s
326:	learn: 0.4725453	total: 487ms	remaining: 1s
327:	learn: 0.4714816	total: 488ms	remaining: 1s
328:	learn: 0.4694063	total: 490ms	remaining: 999ms
329:	learn: 0.4680344	total: 491ms	remaining: 997ms
330:	learn: 0.4662263	total: 493ms	remaining: 995ms
331:	learn: 0.4637454	total: 494ms	remaining: 994ms
332:	learn: 0.4616968	total: 496ms	remaining: 993ms
333:	learn: 0.4607684	total: 497ms	remaining: 991ms
334:	learn: 0.4588263	total: 498ms	remaining: 989ms
335:	learn: 0.4569298	total: 500ms	remaining: 988ms
336:	learn: 0.4548506	total: 501ms	remaining: 986ms
337:	learn: 0.4541572	total: 503ms	remaining: 984ms
338:	learn: 0.4534203	total: 504ms	remaining: 983ms
339:	learn: 0.4527782	total: 505ms	remaining: 981ms
340:	learn: 0.4518847	total: 507ms	remaining: 979ms
341:	learn: 0.4510773	total: 509ms	remaining: 979ms
342:	learn: 0.4489713	total: 510ms	remaining: 978ms
343:	learn: 0.4471917	total: 512ms	remaining: 976ms
344:	learn: 0.4453709	total: 513ms	remaining: 974ms
345:	learn: 0.4446449	total: 515ms	remaining: 973ms
346:	learn: 0.4421757	total: 516ms	remaining: 972ms
347:	learn: 0.4402631	total: 518ms	remaining: 970ms
348:	learn: 0.4396352	total: 519ms	remaining: 968ms
349:	learn: 0.4377134	total: 520ms	remaining: 966ms
350:	learn: 0.4371657	total: 522ms	remaining: 965ms
351:	learn: 0.4355259	total: 524ms	remaining: 964ms
352:	learn: 0.4338365	total: 525ms	remaining: 962ms
353:	learn: 0.4332510	total: 527ms	remaining: 961ms
354:	learn: 0.4314584	total: 528ms	remaining: 960ms
355:	learn: 0.4307004	total: 530ms	remaining: 959ms
356:	learn: 0.4291097	total: 531ms	remaining: 957ms
357:	learn: 0.4271067	total: 533ms	remaining: 956ms
358:	learn: 0.4266412	total: 534ms	remaining: 954ms
359:	learn: 0.4241418	total: 536ms	remaining: 953ms
360:	learn: 0.4217904	total: 537ms	remaining: 951ms
361:	learn: 0.4212133	total: 540ms	remaining: 951ms
362:	learn: 0.4188839	total: 542ms	remaining: 951ms
363:	learn: 0.4169053	total: 545ms	remaining: 953ms
364:	learn: 0.4161625	total: 548ms	remaining: 954ms
365:	learn: 0.4141509	total: 550ms	remaining: 953ms
366:	learn: 0.4133847	total: 554ms	remaining: 955ms
367:	learn: 0.4120459	total: 556ms	remaining: 956ms
368:	learn: 0.4106437	total: 560ms	remaining: 957ms
369:	learn: 0.4101681	total: 563ms	remaining: 958ms
370:	learn: 0.4089982	total: 566ms	remaining: 959ms
371:	learn: 0.4070608	total: 568ms	remaining: 959ms
372:	learn: 0.4064168	total: 569ms	remaining: 957ms
373:	learn: 0.4045733	total: 571ms	remaining: 955ms
374:	learn: 0.4038467	total: 572ms	remaining: 954ms
375:	learn: 0.4023123	total: 574ms	remaining: 953ms
376:	learn: 0.4009363	total: 576ms	remaining: 951ms
377:	learn: 0.4003565	total: 577ms	remaining: 950ms
378:	learn: 0.3995503	total: 579ms	remaining: 948ms
379:	learn: 0.3988927	total: 580ms	remaining: 946ms
380:	learn: 0.3976186	total: 581ms	remaining: 945ms
381:	learn: 0.3960350	total: 583ms	remaining: 943ms

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fitting SVR for C2X_rhown_3x3_depth_lt_1
Fitting KNN for C2X_rhown_3x3_depth_lt_1
Fitting LR for C2X_rhown_3x3_depth_lt_1
Fitting RF for C2X_rhown_3x3_depth_lt_1
Fitting CAT for C2X_rhown_3x3_depth_lt_1
Learning rate set to 0.033272
0:	learn: 3.4183317	total: 1.88ms	remaining: 1.87s
1:	learn: 3.3733791	total: 3.06ms	remaining: 1.53s
2:	learn: 3.3314875	total: 4.21ms	remaining: 1.4s
3:	learn: 3.2882448	total: 5.39ms	remaining: 1.34s
4:	learn: 3.2510917	total: 6.54ms	remaining: 1.3s
5:	learn: 3.2117558	total: 7.67ms	remaining: 1.27s
6:	learn: 3.1727492	total: 8.81ms	remaining: 1.25s
7:	learn: 3.1339979	total: 10ms	remaining: 1.24s
8:	learn: 3.0950692	total: 11.1ms	remaining: 1.22s
9:	learn: 3.0528943	total: 12.2ms	remaining: 1.2s
10:	learn: 3.0220057	total: 13.2ms	remaining: 1.19s
11:	learn: 2.9937352	total: 14.3ms	remaining: 1.18s
12:	learn: 2.9582569	total: 15.4ms	remaining: 1.17s
13:	learn: 2.9204912	total: 17.6ms	remaining: 1.24s
14:	learn: 2.8830970	total: 18.8ms	remaining: 1.24s
15:	learn: 2.8454770	total: 20ms	remaining: 1.23s
16:	learn: 2.8128815	total: 21.2ms	remaining: 1.23s
17:	learn: 2.7714206	total: 22.3ms	remaining: 1.22s
18:	learn: 2.7368402	total: 23.4ms	remaining: 1.21s
19:	learn: 2.7082761	total: 24.4ms	remaining: 1.2s
20:	learn: 2.6795302	total: 25.5ms	remaining: 1.19s
21:	learn: 2.6560607	total: 26.6ms	remaining: 1.18s
22:	learn: 2.6308501	total: 27.8ms	remaining: 1.18s
23:	learn: 2.6089951	total: 28.9ms	remaining: 1.17s
24:	learn: 2.5799432	total: 29.9ms	remaining: 1.17s
25:	learn: 2.5535736	total: 31ms	remaining: 1.16s
26:	learn: 2.5280495	total: 32ms	remaining: 1.15s
27:	learn: 2.5057842	total: 34.4ms	remaining: 1.19s
28:	learn: 2.4761204	total: 35.5ms	remaining: 1.19s
29:	learn: 2.4483998	total: 36.7ms	remaining: 1.19s
30:	learn: 2.4271574	total: 37.8ms	remaining: 1.18s
31:	learn: 2.4047255	total: 38.9ms	remaining: 1.18s
32:	learn: 2.3793562	total: 39.9ms	remaining: 1.17s
33:	learn: 2.3656864	total: 41ms	remaining: 1.17s
34:	learn: 2.3407016	total: 42.1ms	remaining: 1.16s
35:	learn: 2.3247268	total: 43.2ms	remaining: 1.16s
36:	learn: 2.3047151	total: 44.3ms	remaining: 1.15s
37:	learn: 2.2793717	total: 45.3ms	remaining: 1.15s
38:	learn: 2.2643618	total: 46.5ms	remaining: 1.15s
39:	learn: 2.2434874	total: 47.6ms	remaining: 1.14s
40:	learn: 2.2248916	total: 49.2ms	remaining: 1.15s
41:	learn: 2.2053125	total: 50.4ms	remaining: 1.15s
42:	learn: 2.1798812	total: 51.6ms	remaining: 1.15s
43:	learn: 2.1548247	total: 52.9ms	remaining: 1.15s
44:	learn: 2.1413947	total: 54ms	remaining: 1.15s
45:	learn: 2.1224093	total: 55.1ms	remaining: 1.14s
46:	learn: 2.1081566	total: 56.2ms	remaining: 1.14s
47:	learn: 2.0983178	total: 57.3ms	remaining: 1.14s
48:	learn: 2.0856881	total: 58.4ms	remaining: 1.13s
49:	learn: 2.0650833	total: 59.5ms	remaining: 1.13s
50:	learn: 2.0482589	total: 60.5ms	remaining: 1.13s
51:	learn: 2.0288693	total: 61.6ms	remaining: 1.12s
52:	learn: 2.0181288	total: 62.6ms	remaining: 1.12s
53:	learn: 1.9947115	total: 64.4ms	remaining: 1.13s
54:	learn: 1.9704282	total: 65.6ms	remaining: 1.13s
55:	learn: 1.9586719	total: 66.8ms	remaining: 1.13s
56:	learn: 1.9499765	total: 68ms	remaining: 1.12s
57:	learn: 1.9315374	total: 69.2ms	remaining: 1.12s
58:	learn: 1.9159782	total: 70.3ms	remaining: 1.12s
59:	learn: 1.8989080	total: 71.4ms	remaining: 1.12s
60:	learn: 1.8794798	total: 72.5ms	remaining: 1.11s
61:	learn: 1.8593075	total: 73.6ms	remaining: 1.11s
62:	learn: 1.8485652	total: 74.8ms	remaining: 1.11s
63:	learn: 1.8354822	total: 75.9ms	remaining: 1.11s
64:	learn: 1.8213089	total: 77ms	remaining: 1.11s
65:	learn: 1.8098658	total: 78.1ms	remaining: 1.1s
66:	learn: 1.7993141	total: 79.3ms	remaining: 1.1s
67:	learn: 1.7845162	total: 80.6ms	remaining: 1.1s
68:	learn: 1.7755089	total: 81.9ms	remaining: 1.1s
69:	learn: 1.7691973	total: 83.3ms	remaining: 1.11s
70:	learn: 1.7571771	total: 84.5ms	remaining: 1.1s
71:	learn: 1.7484299	total: 85.6ms	remaining: 1.1s
72:	learn: 1.7384327	total: 86.8ms	remaining: 1.1s
73:	learn: 1.7326235	total: 88ms	remaining: 1.1s
74:	learn: 1.7217841	total: 89.1ms	remaining: 1.1s
75:	learn: 1.7166289	total: 90.3ms	remaining: 1.1s
76:	learn: 1.7108991	total: 91.4ms	remaining: 1.09s
77:	learn: 1.7007900	total: 92.6ms	remaining: 1.09s
78:	learn: 1.6913767	total: 94.1ms	remaining: 1.1s
79:	learn: 1.6766640	total: 95.7ms	remaining: 1.1s
80:	learn: 1.6664278	total: 97.6ms	remaining: 1.11s
81:	learn: 1.6577982	total: 98.9ms	remaining: 1.11s
82:	learn: 1.6512079	total: 100ms	remaining: 1.1s
83:	learn: 1.6402436	total: 101ms	remaining: 1.1s
84:	learn: 1.6286318	total: 102ms	remaining: 1.1s
85:	learn: 1.6158790	total: 103ms	remaining: 1.1s
86:	learn: 1.6061037	total: 105ms	remaining: 1.1s
87:	learn: 1.5974004	total: 106ms	remaining: 1.09s
88:	learn: 1.5875187	total: 107ms	remaining: 1.09s
89:	learn: 1.5776382	total: 108ms	remaining: 1.09s
90:	learn: 1.5730148	total: 109ms	remaining: 1.09s
91:	learn: 1.5680059	total: 110ms	remaining: 1.08s
92:	learn: 1.5575439	total: 111ms	remaining: 1.08s
93:	learn: 1.5507818	total: 112ms	remaining: 1.08s
94:	learn: 1.5475324	total: 113ms	remaining: 1.08s
95:	learn: 1.5431983	total: 115ms	remaining: 1.08s
96:	learn: 1.5270213	total: 116ms	remaining: 1.08s
97:	learn: 1.5219073	total: 117ms	remaining: 1.08s
98:	learn: 1.5168000	total: 118ms	remaining: 1.07s
99:	learn: 1.5081809	total: 119ms	remaining: 1.07s
100:	learn: 1.5033193	total: 120ms	remaining: 1.07s
101:	learn: 1.4926402	total: 121ms	remaining: 1.06s
102:	learn: 1.4883160	total: 122ms	remaining: 1.06s
103:	learn: 1.4815388	total: 123ms	remaining: 1.06s
104:	learn: 1.4700763	total: 124ms	remaining: 1.06s
105:	learn: 1.4660584	total: 125ms	remaining: 1.06s
106:	learn: 1.4598510	total: 127ms	remaining: 1.06s
107:	learn: 1.4482787	total: 128ms	remaining: 1.06s
108:	learn: 1.4455231	total: 130ms	remaining: 1.06s
109:	learn: 1.4324137	total: 131ms	remaining: 1.06s
110:	learn: 1.4262584	total: 132ms	remaining: 1.06s
111:	learn: 1.4169528	total: 133ms	remaining: 1.05s
112:	learn: 1.4148647	total: 134ms	remaining: 1.05s
113:	learn: 1.4124751	total: 135ms	remaining: 1.05s
114:	learn: 1.4031491	total: 136ms	remaining: 1.05s
115:	learn: 1.3963147	total: 137ms	remaining: 1.04s
116:	learn: 1.3881719	total: 138ms	remaining: 1.04s
117:	learn: 1.3861543	total: 139ms	remaining: 1.04s
118:	learn: 1.3818270	total: 140ms	remaining: 1.04s
119:	learn: 1.3762266	total: 142ms	remaining: 1.04s
120:	learn: 1.3674156	total: 143ms	remaining: 1.04s
121:	learn: 1.3622555	total: 144ms	remaining: 1.04s
122:	learn: 1.3549035	total: 145ms	remaining: 1.03s
123:	learn: 1.3488204	total: 146ms	remaining: 1.03s
124:	learn: 1.3389938	total: 148ms	remaining: 1.03s
125:	learn: 1.3338730	total: 149ms	remaining: 1.03s
126:	learn: 1.3299461	total: 150ms	remaining: 1.03s
127:	learn: 1.3260318	total: 151ms	remaining: 1.03s
128:	learn: 1.3200949	total: 153ms	remaining: 1.03s
129:	learn: 1.3130796	total: 154ms	remaining: 1.03s
130:	learn: 1.3084352	total: 155ms	remaining: 1.03s
131:	learn: 1.3044748	total: 156ms	remaining: 1.02s
132:	learn: 1.2981427	total: 157ms	remaining: 1.02s
133:	learn: 1.2907955	total: 158ms	remaining: 1.02s
134:	learn: 1.2826525	total: 160ms	remaining: 1.02s
135:	learn: 1.2783000	total: 161ms	remaining: 1.02s
136:	learn: 1.2672654	total: 162ms	remaining: 1.02s
137:	learn: 1.2582333	total: 164ms	remaining: 1.02s
138:	learn: 1.2530414	total: 165ms	remaining: 1.02s
139:	learn: 1.2469116	total: 166ms	remaining: 1.02s
140:	learn: 1.2381756	total: 167ms	remaining: 1.02s
141:	learn: 1.2328437	total: 168ms	remaining: 1.01s
142:	learn: 1.2287205	total: 169ms	remaining: 1.01s
143:	learn: 1.2195773	total: 170ms	remaining: 1.01s
144:	learn: 1.2177566	total: 171ms	remaining: 1.01s
145:	learn: 1.2099978	total: 172ms	remaining: 1.01s
146:	learn: 1.2033574	total: 174ms	remaining: 1.01s
147:	learn: 1.1945083	total: 175ms	remaining: 1.01s
148:	learn: 1.1901657	total: 177ms	remaining: 1.01s
149:	learn: 1.1850291	total: 178ms	remaining: 1.01s
150:	learn: 1.1780672	total: 179ms	remaining: 1.01s
151:	learn: 1.1723626	total: 180ms	remaining: 1.01s
152:	learn: 1.1703641	total: 182ms	remaining: 1.01s
153:	learn: 1.1616345	total: 184ms	remaining: 1.01s
154:	learn: 1.1596945	total: 186ms	remaining: 1.01s
155:	learn: 1.1561848	total: 188ms	remaining: 1.02s
156:	learn: 1.1468742	total: 191ms	remaining: 1.02s
157:	learn: 1.1416321	total: 193ms	remaining: 1.03s
158:	learn: 1.1398882	total: 196ms	remaining: 1.03s
159:	learn: 1.1314961	total: 198ms	remaining: 1.04s
160:	learn: 1.1280393	total: 199ms	remaining: 1.04s
161:	learn: 1.1268918	total: 200ms	remaining: 1.03s
162:	learn: 1.1177817	total: 201ms	remaining: 1.03s
163:	learn: 1.1156643	total: 203ms	remaining: 1.03s
164:	learn: 1.1117543	total: 204ms	remaining: 1.03s
165:	learn: 1.1052848	total: 205ms	remaining: 1.03s
166:	learn: 1.0971442	total: 206ms	remaining: 1.03s
167:	learn: 1.0941685	total: 208ms	remaining: 1.03s
168:	learn: 1.0873255	total: 210ms	remaining: 1.03s
169:	learn: 1.0859625	total: 211ms	remaining: 1.03s
170:	learn: 1.0844604	total: 212ms	remaining: 1.03s
171:	learn: 1.0774337	total: 214ms	remaining: 1.03s
172:	learn: 1.0703584	total: 215ms	remaining: 1.03s
173:	learn: 1.0682077	total: 216ms	remaining: 1.02s
174:	learn: 1.0630609	total: 217ms	remaining: 1.02s
175:	learn: 1.0617824	total: 218ms	remaining: 1.02s
176:	learn: 1.0544105	total: 220ms	remaining: 1.02s
177:	learn: 1.0471557	total: 221ms	remaining: 1.02s
178:	learn: 1.0460786	total: 222ms	remaining: 1.02s
179:	learn: 1.0429356	total: 224ms	remaining: 1.02s
180:	learn: 1.0419216	total: 225ms	remaining: 1.02s
181:	learn: 1.0392075	total: 227ms	remaining: 1.02s
182:	learn: 1.0370425	total: 228ms	remaining: 1.02s
183:	learn: 1.0278996	total: 231ms	remaining: 1.02s
184:	learn: 1.0254689	total: 233ms	remaining: 1.03s
185:	learn: 1.0221466	total: 235ms	remaining: 1.03s
186:	learn: 1.0205675	total: 237ms	remaining: 1.03s
187:	learn: 1.0198298	total: 238ms	remaining: 1.03s
188:	learn: 1.0117543	total: 240ms	remaining: 1.03s
189:	learn: 1.0091469	total: 241ms	remaining: 1.03s
190:	learn: 1.0060039	total: 243ms	remaining: 1.03s
191:	learn: 1.0021365	total: 244ms	remaining: 1.03s
192:	learn: 1.0006741	total: 246ms	remaining: 1.03s
193:	learn: 0.9936685	total: 247ms	remaining: 1.02s
194:	learn: 0.9890471	total: 248ms	remaining: 1.02s
195:	learn: 0.9810611	total: 249ms	remaining: 1.02s
196:	learn: 0.9756366	total: 250ms	remaining: 1.02s
197:	learn: 0.9741431	total: 251ms	remaining: 1.02s
198:	learn: 0.9694797	total: 252ms	remaining: 1.01s
199:	learn: 0.9630226	total: 254ms	remaining: 1.01s
200:	learn: 0.9587813	total: 255ms	remaining: 1.01s
201:	learn: 0.9571942	total: 256ms	remaining: 1.01s
202:	learn: 0.9500333	total: 257ms	remaining: 1.01s
203:	learn: 0.9436741	total: 259ms	remaining: 1.01s
204:	learn: 0.9419537	total: 260ms	remaining: 1.01s
205:	learn: 0.9371685	total: 261ms	remaining: 1s
206:	learn: 0.9338382	total: 262ms	remaining: 1s
207:	learn: 0.9321304	total: 263ms	remaining: 1s
208:	learn: 0.9315505	total: 264ms	remaining: 999ms
209:	learn: 0.9272462	total: 265ms	remaining: 998ms
210:	learn: 0.9250390	total: 266ms	remaining: 996ms
211:	learn: 0.9207869	total: 268ms	remaining: 995ms
212:	learn: 0.9193846	total: 269ms	remaining: 994ms
213:	learn: 0.9183752	total: 270ms	remaining: 993ms
214:	learn: 0.9144449	total: 272ms	remaining: 992ms
215:	learn: 0.9133407	total: 273ms	remaining: 991ms
216:	learn: 0.9128364	total: 274ms	remaining: 990ms
217:	learn: 0.9089145	total: 275ms	remaining: 988ms
218:	learn: 0.9040145	total: 277ms	remaining: 987ms
219:	learn: 0.8963296	total: 278ms	remaining: 985ms
220:	learn: 0.8957400	total: 279ms	remaining: 984ms
221:	learn: 0.8950603	total: 280ms	remaining: 982ms
222:	learn: 0.8895287	total: 282ms	remaining: 981ms
223:	learn: 0.8887150	total: 283ms	remaining: 980ms
224:	learn: 0.8811200	total: 284ms	remaining: 980ms
225:	learn: 0.8790215	total: 286ms	remaining: 979ms
226:	learn: 0.8785312	total: 287ms	remaining: 976ms
227:	learn: 0.8746133	total: 288ms	remaining: 975ms
228:	learn: 0.8731031	total: 289ms	remaining: 973ms
229:	learn: 0.8679900	total: 290ms	remaining: 971ms
230:	learn: 0.8662507	total: 291ms	remaining: 969ms
231:	learn: 0.8611510	total: 292ms	remaining: 968ms
232:	learn: 0.8574756	total: 293ms	remaining: 966ms
233:	learn: 0.8548793	total: 295ms	remaining: 964ms
234:	learn: 0.8510429	total: 296ms	remaining: 962ms
235:	learn: 0.8505770	total: 297ms	remaining: 961ms
236:	learn: 0.8459030	total: 298ms	remaining: 959ms
237:	learn: 0.8416844	total: 299ms	remaining: 957ms
238:	learn: 0.8394538	total: 301ms	remaining: 960ms
239:	learn: 0.8351969	total: 303ms	remaining: 959ms
240:	learn: 0.8289032	total: 304ms	remaining: 958ms
241:	learn: 0.8242202	total: 305ms	remaining: 956ms
242:	learn: 0.8216303	total: 306ms	remaining: 955ms
243:	learn: 0.8165581	total: 308ms	remaining: 953ms
244:	learn: 0.8120620	total: 309ms	remaining: 951ms
245:	learn: 0.8105844	total: 310ms	remaining: 950ms
246:	learn: 0.8042902	total: 311ms	remaining: 948ms
247:	learn: 0.7967725	total: 312ms	remaining: 947ms
248:	learn: 0.7934272	total: 313ms	remaining: 945ms
249:	learn: 0.7874376	total: 314ms	remaining: 943ms
250:	learn: 0.7836656	total: 316ms	remaining: 944ms
251:	learn: 0.7810761	total: 318ms	remaining: 942ms
252:	learn: 0.7793049	total: 319ms	remaining: 941ms
253:	learn: 0.7724925	total: 320ms	remaining: 940ms
254:	learn: 0.7659528	total: 321ms	remaining: 939ms
255:	learn: 0.7642843	total: 323ms	remaining: 937ms
256:	learn: 0.7623021	total: 324ms	remaining: 936ms
257:	learn: 0.7584107	total: 325ms	remaining: 934ms
258:	learn: 0.7572505	total: 326ms	remaining: 933ms
259:	learn: 0.7544188	total: 327ms	remaining: 931ms
260:	learn: 0.7530771	total: 328ms	remaining: 929ms
261:	learn: 0.7504193	total: 329ms	remaining: 928ms
262:	learn: 0.7478856	total: 331ms	remaining: 926ms
263:	learn: 0.7409223	total: 332ms	remaining: 925ms
264:	learn: 0.7390057	total: 333ms	remaining: 924ms
265:	learn: 0.7333786	total: 334ms	remaining: 923ms
266:	learn: 0.7272352	total: 336ms	remaining: 921ms
267:	learn: 0.7239265	total: 337ms	remaining: 920ms
268:	learn: 0.7186282	total: 338ms	remaining: 918ms
269:	learn: 0.7156118	total: 339ms	remaining: 917ms
270:	learn: 0.7141633	total: 340ms	remaining: 915ms
271:	learn: 0.7103747	total: 341ms	remaining: 913ms
272:	learn: 0.7084035	total: 342ms	remaining: 912ms
273:	learn: 0.7061664	total: 344ms	remaining: 910ms
274:	learn: 0.7049087	total: 345ms	remaining: 909ms
275:	learn: 0.7007443	total: 346ms	remaining: 907ms
276:	learn: 0.6993781	total: 347ms	remaining: 906ms
277:	learn: 0.6952240	total: 348ms	remaining: 905ms
278:	learn: 0.6941334	total: 350ms	remaining: 905ms
279:	learn: 0.6908726	total: 351ms	remaining: 903ms
280:	learn: 0.6856942	total: 352ms	remaining: 902ms
281:	learn: 0.6834716	total: 354ms	remaining: 900ms
282:	learn: 0.6829896	total: 355ms	remaining: 899ms
283:	learn: 0.6786364	total: 356ms	remaining: 897ms
284:	learn: 0.6748324	total: 357ms	remaining: 895ms
285:	learn: 0.6737755	total: 358ms	remaining: 894ms
286:	learn: 0.6691586	total: 359ms	remaining: 892ms
287:	learn: 0.6642641	total: 360ms	remaining: 891ms
288:	learn: 0.6631089	total: 361ms	remaining: 889ms
289:	learn: 0.6600500	total: 363ms	remaining: 889ms
290:	learn: 0.6559548	total: 364ms	remaining: 888ms
291:	learn: 0.6526887	total: 366ms	remaining: 888ms
292:	learn: 0.6503067	total: 368ms	remaining: 887ms
293:	learn: 0.6484096	total: 369ms	remaining: 886ms
294:	learn: 0.6463523	total: 370ms	remaining: 885ms
295:	learn: 0.6410228	total: 371ms	remaining: 883ms
296:	learn: 0.6362374	total: 374ms	remaining: 885ms
297:	learn: 0.6342623	total: 375ms	remaining: 884ms
298:	learn: 0.6321543	total: 376ms	remaining: 882ms
299:	learn: 0.6274447	total: 378ms	remaining: 882ms
300:	learn: 0.6241165	total: 379ms	remaining: 881ms
301:	learn: 0.6219768	total: 381ms	remaining: 880ms
302:	learn: 0.6174333	total: 382ms	remaining: 879ms
303:	learn: 0.6125458	total: 384ms	remaining: 879ms
304:	learn: 0.6100188	total: 385ms	remaining: 878ms
305:	learn: 0.6061677	total: 389ms	remaining: 881ms
306:	learn: 0.6054850	total: 391ms	remaining: 883ms
307:	learn: 0.6016275	total: 393ms	remaining: 884ms
308:	learn: 0.5996754	total: 395ms	remaining: 883ms
309:	learn: 0.5980743	total: 397ms	remaining: 884ms
310:	learn: 0.5969910	total: 399ms	remaining: 883ms
311:	learn: 0.5932966	total: 400ms	remaining: 882ms
312:	learn: 0.5907483	total: 401ms	remaining: 880ms
313:	learn: 0.5889746	total: 402ms	remaining: 879ms
314:	learn: 0.5866061	total: 404ms	remaining: 878ms
315:	learn: 0.5829371	total: 405ms	remaining: 876ms
316:	learn: 0.5801409	total: 406ms	remaining: 875ms
317:	learn: 0.5768892	total: 407ms	remaining: 873ms
318:	learn: 0.5763042	total: 408ms	remaining: 871ms
319:	learn: 0.5753286	total: 409ms	remaining: 870ms
320:	learn: 0.5737786	total: 411ms	remaining: 870ms
321:	learn: 0.5722930	total: 413ms	remaining: 869ms
322:	learn: 0.5713440	total: 414ms	remaining: 868ms
323:	learn: 0.5685964	total: 415ms	remaining: 866ms
324:	learn: 0.5654361	total: 416ms	remaining: 865ms
325:	learn: 0.5614512	total: 418ms	remaining: 863ms
326:	learn: 0.5579213	total: 419ms	remaining: 862ms
327:	learn: 0.5563568	total: 420ms	remaining: 860ms
328:	learn: 0.5555244	total: 421ms	remaining: 859ms
329:	learn: 0.5527391	total: 422ms	remaining: 857ms
330:	learn: 0.5504409	total: 423ms	remaining: 855ms
331:	learn: 0.5484969	total: 424ms	remaining: 854ms
332:	learn: 0.5468829	total: 425ms	remaining: 852ms
333:	learn: 0.5445010	total: 428ms	remaining: 852ms
334:	learn: 0.5434527	total: 429ms	remaining: 851ms
335:	learn: 0.5418876	total: 430ms	remaining: 850ms
336:	learn: 0.5391295	total: 431ms	remaining: 848ms
337:	learn: 0.5382494	total: 432ms	remaining: 847ms
338:	learn: 0.5343053	total: 434ms	remaining: 845ms
339:	learn: 0.5326546	total: 435ms	remaining: 844ms
340:	learn: 0.5298463	total: 436ms	remaining: 842ms
341:	learn: 0.5281992	total: 437ms	remaining: 841ms
342:	learn: 0.5266642	total: 438ms	remaining: 839ms
343:	learn: 0.5240257	total: 439ms	remaining: 838ms
344:	learn: 0.5218082	total: 440ms	remaining: 836ms
345:	learn: 0.5202702	total: 442ms	remaining: 835ms
346:	learn: 0.5186799	total: 444ms	remaining: 835ms
347:	learn: 0.5158784	total: 445ms	remaining: 833ms
348:	learn: 0.5129808	total: 446ms	remaining: 832ms
349:	learn: 0.5097064	total: 447ms	remaining: 830ms
350:	learn: 0.5068184	total: 448ms	remaining: 829ms
351:	learn: 0.5052774	total: 449ms	remaining: 827ms
352:	learn: 0.5030441	total: 450ms	remaining: 826ms
353:	learn: 0.5007790	total: 452ms	remaining: 824ms
354:	learn: 0.4997334	total: 453ms	remaining: 823ms
355:	learn: 0.4982881	total: 454ms	remaining: 821ms
356:	learn: 0.4970326	total: 455ms	remaining: 820ms
357:	learn: 0.4946603	total: 456ms	remaining: 818ms
358:	learn: 0.4939855	total: 458ms	remaining: 818ms
359:	learn: 0.4930274	total: 460ms	remaining: 818ms
360:	learn: 0.4914869	total: 461ms	remaining: 817ms
361:	learn: 0.4894802	total: 463ms	remaining: 815ms
362:	learn: 0.4868665	total: 464ms	remaining: 814ms
363:	learn: 0.4861997	total: 465ms	remaining: 813ms
364:	learn: 0.4847863	total: 466ms	remaining: 811ms
365:	learn: 0.4843876	total: 468ms	remaining: 810ms
366:	learn: 0.4830050	total: 469ms	remaining: 808ms
367:	learn: 0.4816522	total: 470ms	remaining: 807ms
368:	learn: 0.4803308	total: 471ms	remaining: 806ms
369:	learn: 0.4790392	total: 473ms	remaining: 805ms
370:	learn: 0.4785071	total: 475ms	remaining: 805ms
371:	learn: 0.4765469	total: 476ms	remaining: 804ms
372:	learn: 0.4735974	total: 477ms	remaining: 803ms
373:	learn: 0.4718016	total: 479ms	remaining: 801ms
374:	learn: 0.4703276	total: 480ms	remaining: 800ms
375:	learn: 0.4687709	total: 481ms	remaining: 798ms
376:	learn: 0.4682594	total: 482ms	remaining: 797ms
377:	learn: 0.4670341	total: 483ms	remaining: 795ms
378:	learn: 0.4647744	total: 484ms	remaining: 793ms
379:	learn: 0.4621943	total: 485ms	remaining: 792ms
380:	learn: 0.4603826	total: 487ms	remaining: 790ms

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fitting SVR for C2RCC_rhown_5x5_depth_lt_1
Fitting KNN for C2RCC_rhown_5x5_depth_lt_1
Fitting LR for C2RCC_rhown_5x5_depth_lt_1
Fitting RF for C2RCC_rhown_5x5_depth_lt_1
Fitting CAT for C2RCC_rhown_5x5_depth_lt_1
Learning rate set to 0.033272
0:	learn: 3.4102290	total: 3.62ms	remaining: 3.62s
1:	learn: 3.3489584	total: 4.8ms	remaining: 2.39s
2:	learn: 3.3024044	total: 6.02ms	remaining: 2s
3:	learn: 3.2478446	total: 7.35ms	remaining: 1.83s
4:	learn: 3.1935477	total: 8.54ms	remaining: 1.7s
5:	learn: 3.1424942	total: 9.7ms	remaining: 1.61s
6:	learn: 3.0998253	total: 10.9ms	remaining: 1.54s
7:	learn: 3.0523310	total: 12ms	remaining: 1.49s
8:	learn: 3.0069367	total: 13.1ms	remaining: 1.44s
9:	learn: 2.9596102	total: 14.2ms	remaining: 1.41s
10:	learn: 2.9049123	total: 15.3ms	remaining: 1.38s
11:	learn: 2.8636497	total: 16.3ms	remaining: 1.34s
12:	learn: 2.8160664	total: 17.5ms	remaining: 1.32s
13:	learn: 2.7697070	total: 18.6ms	remaining: 1.31s
14:	learn: 2.7222871	total: 19.7ms	remaining: 1.29s
15:	learn: 2.6881859	total: 20.8ms	remaining: 1.28s
16:	learn: 2.6448491	total: 22.5ms	remaining: 1.3s
17:	learn: 2.6044200	total: 23.6ms	remaining: 1.29s
18:	learn: 2.5681104	total: 24.7ms	remaining: 1.28s
19:	learn: 2.5313652	total: 25.9ms	remaining: 1.27s
20:	learn: 2.4903084	total: 27ms	remaining: 1.26s
21:	learn: 2.4510526	total: 28.1ms	remaining: 1.25s
22:	learn: 2.4129632	total: 29.2ms	remaining: 1.24s
23:	learn: 2.3924846	total: 30.2ms	remaining: 1.23s
24:	learn: 2.3611878	total: 31.3ms	remaining: 1.22s
25:	learn: 2.3265177	total: 32.3ms	remaining: 1.21s
26:	learn: 2.2880326	total: 33.4ms	remaining: 1.2s
27:	learn: 2.2540066	total: 34.5ms	remaining: 1.2s
28:	learn: 2.2184788	total: 35.5ms	remaining: 1.19s
29:	learn: 2.1882344	total: 36.8ms	remaining: 1.19s
30:	learn: 2.1587282	total: 38.6ms	remaining: 1.21s
31:	learn: 2.1328241	total: 39.8ms	remaining: 1.2s
32:	learn: 2.0920883	total: 41.2ms	remaining: 1.21s
33:	learn: 2.0699763	total: 42.3ms	remaining: 1.2s
34:	learn: 2.0409345	total: 43.4ms	remaining: 1.2s
35:	learn: 2.0194171	total: 44.5ms	remaining: 1.19s
36:	learn: 1.9897989	total: 45.6ms	remaining: 1.19s
37:	learn: 1.9634044	total: 46.8ms	remaining: 1.18s
38:	learn: 1.9386084	total: 47.9ms	remaining: 1.18s
39:	learn: 1.9095695	total: 48.9ms	remaining: 1.17s
40:	learn: 1.8843303	total: 49.9ms	remaining: 1.17s
41:	learn: 1.8553334	total: 51ms	remaining: 1.16s
42:	learn: 1.8315540	total: 52.1ms	remaining: 1.16s
43:	learn: 1.8089336	total: 53.2ms	remaining: 1.16s
44:	learn: 1.7914613	total: 54.5ms	remaining: 1.16s
45:	learn: 1.7682276	total: 56.1ms	remaining: 1.16s
46:	learn: 1.7417910	total: 57.3ms	remaining: 1.16s
47:	learn: 1.7192349	total: 58.5ms	remaining: 1.16s
48:	learn: 1.6987762	total: 59.6ms	remaining: 1.16s
49:	learn: 1.6758191	total: 60.7ms	remaining: 1.15s
50:	learn: 1.6582532	total: 61.7ms	remaining: 1.15s
51:	learn: 1.6365500	total: 62.8ms	remaining: 1.14s
52:	learn: 1.6175652	total: 63.8ms	remaining: 1.14s
53:	learn: 1.5991190	total: 64.9ms	remaining: 1.14s
54:	learn: 1.5787979	total: 66ms	remaining: 1.13s
55:	learn: 1.5698904	total: 67.1ms	remaining: 1.13s
56:	learn: 1.5507342	total: 68.2ms	remaining: 1.13s
57:	learn: 1.5307101	total: 69.5ms	remaining: 1.13s
58:	learn: 1.5149677	total: 70.7ms	remaining: 1.13s
59:	learn: 1.4911445	total: 72ms	remaining: 1.13s
60:	learn: 1.4741678	total: 73.3ms	remaining: 1.13s
61:	learn: 1.4577258	total: 74.5ms	remaining: 1.13s
62:	learn: 1.4404620	total: 75.5ms	remaining: 1.12s
63:	learn: 1.4289965	total: 76.6ms	remaining: 1.12s
64:	learn: 1.4114524	total: 77.6ms	remaining: 1.12s
65:	learn: 1.3961684	total: 78.7ms	remaining: 1.11s
66:	learn: 1.3901881	total: 79.8ms	remaining: 1.11s
67:	learn: 1.3772643	total: 80.9ms	remaining: 1.11s
68:	learn: 1.3611045	total: 82ms	remaining: 1.11s
69:	learn: 1.3491966	total: 83.1ms	remaining: 1.1s
70:	learn: 1.3353142	total: 84.7ms	remaining: 1.11s
71:	learn: 1.3220336	total: 86.4ms	remaining: 1.11s
72:	learn: 1.3158179	total: 87.7ms	remaining: 1.11s
73:	learn: 1.3016895	total: 89ms	remaining: 1.11s
74:	learn: 1.2955860	total: 90.1ms	remaining: 1.11s
75:	learn: 1.2838953	total: 91.2ms	remaining: 1.11s
76:	learn: 1.2722914	total: 92.3ms	remaining: 1.11s
77:	learn: 1.2640623	total: 93.4ms	remaining: 1.1s
78:	learn: 1.2548450	total: 94.6ms	remaining: 1.1s
79:	learn: 1.2386765	total: 95.7ms	remaining: 1.1s
80:	learn: 1.2316703	total: 96.8ms	remaining: 1.1s
81:	learn: 1.2222258	total: 98.2ms	remaining: 1.1s
82:	learn: 1.2169633	total: 99.4ms	remaining: 1.1s
83:	learn: 1.2045513	total: 101ms	remaining: 1.1s
84:	learn: 1.1968341	total: 102ms	remaining: 1.1s
85:	learn: 1.1881936	total: 103ms	remaining: 1.1s
86:	learn: 1.1815483	total: 105ms	remaining: 1.1s
87:	learn: 1.1774158	total: 106ms	remaining: 1.09s
88:	learn: 1.1683099	total: 107ms	remaining: 1.09s
89:	learn: 1.1563269	total: 108ms	remaining: 1.09s
90:	learn: 1.1461895	total: 109ms	remaining: 1.09s
91:	learn: 1.1394379	total: 110ms	remaining: 1.09s
92:	learn: 1.1345418	total: 111ms	remaining: 1.08s
93:	learn: 1.1263016	total: 112ms	remaining: 1.08s
94:	learn: 1.1176061	total: 113ms	remaining: 1.08s
95:	learn: 1.1070823	total: 114ms	remaining: 1.08s
96:	learn: 1.0988344	total: 116ms	remaining: 1.08s
97:	learn: 1.0905263	total: 117ms	remaining: 1.07s
98:	learn: 1.0860680	total: 118ms	remaining: 1.07s
99:	learn: 1.0797277	total: 119ms	remaining: 1.07s
100:	learn: 1.0742953	total: 120ms	remaining: 1.07s
101:	learn: 1.0702637	total: 122ms	remaining: 1.07s
102:	learn: 1.0644810	total: 123ms	remaining: 1.07s
103:	learn: 1.0575801	total: 124ms	remaining: 1.06s
104:	learn: 1.0496526	total: 125ms	remaining: 1.06s
105:	learn: 1.0427873	total: 126ms	remaining: 1.06s
106:	learn: 1.0359479	total: 127ms	remaining: 1.06s
107:	learn: 1.0339669	total: 128ms	remaining: 1.06s
108:	learn: 1.0270711	total: 129ms	remaining: 1.05s
109:	learn: 1.0221764	total: 130ms	remaining: 1.05s
110:	learn: 1.0182722	total: 131ms	remaining: 1.05s
111:	learn: 1.0160767	total: 133ms	remaining: 1.05s
112:	learn: 1.0148293	total: 134ms	remaining: 1.05s
113:	learn: 1.0097641	total: 135ms	remaining: 1.05s
114:	learn: 1.0063695	total: 136ms	remaining: 1.05s
115:	learn: 1.0003937	total: 138ms	remaining: 1.05s
116:	learn: 0.9954063	total: 139ms	remaining: 1.05s
117:	learn: 0.9922097	total: 140ms	remaining: 1.04s
118:	learn: 0.9818894	total: 141ms	remaining: 1.04s
119:	learn: 0.9800930	total: 142ms	remaining: 1.04s
120:	learn: 0.9741923	total: 143ms	remaining: 1.04s
121:	learn: 0.9693506	total: 144ms	remaining: 1.04s
122:	learn: 0.9658171	total: 145ms	remaining: 1.03s
123:	learn: 0.9616428	total: 146ms	remaining: 1.03s
124:	learn: 0.9590853	total: 147ms	remaining: 1.03s
125:	learn: 0.9556090	total: 149ms	remaining: 1.03s
126:	learn: 0.9473704	total: 150ms	remaining: 1.03s
127:	learn: 0.9445109	total: 151ms	remaining: 1.03s
128:	learn: 0.9426440	total: 153ms	remaining: 1.03s
129:	learn: 0.9376699	total: 154ms	remaining: 1.03s
130:	learn: 0.9337945	total: 155ms	remaining: 1.03s
131:	learn: 0.9304088	total: 156ms	remaining: 1.03s
132:	learn: 0.9265794	total: 157ms	remaining: 1.02s
133:	learn: 0.9231851	total: 158ms	remaining: 1.02s
134:	learn: 0.9193580	total: 160ms	remaining: 1.02s
135:	learn: 0.9155792	total: 161ms	remaining: 1.02s
136:	learn: 0.9108446	total: 162ms	remaining: 1.02s
137:	learn: 0.9097306	total: 163ms	remaining: 1.02s
138:	learn: 0.9037465	total: 164ms	remaining: 1.02s
139:	learn: 0.8985954	total: 165ms	remaining: 1.02s
140:	learn: 0.8938337	total: 167ms	remaining: 1.01s
141:	learn: 0.8909403	total: 168ms	remaining: 1.01s
142:	learn: 0.8868626	total: 169ms	remaining: 1.01s
143:	learn: 0.8834848	total: 170ms	remaining: 1.01s
144:	learn: 0.8778039	total: 171ms	remaining: 1.01s
145:	learn: 0.8722093	total: 172ms	remaining: 1.01s
146:	learn: 0.8673758	total: 173ms	remaining: 1s
147:	learn: 0.8630872	total: 174ms	remaining: 1s
148:	learn: 0.8599710	total: 175ms	remaining: 1s
149:	learn: 0.8589037	total: 176ms	remaining: 1000ms
150:	learn: 0.8566955	total: 177ms	remaining: 998ms
151:	learn: 0.8543096	total: 179ms	remaining: 997ms
152:	learn: 0.8529205	total: 180ms	remaining: 998ms
153:	learn: 0.8506499	total: 182ms	remaining: 998ms
154:	learn: 0.8466259	total: 184ms	remaining: 1s
155:	learn: 0.8452324	total: 187ms	remaining: 1.01s
156:	learn: 0.8406679	total: 189ms	remaining: 1.01s
157:	learn: 0.8366401	total: 190ms	remaining: 1.01s
158:	learn: 0.8315405	total: 191ms	remaining: 1.01s
159:	learn: 0.8285736	total: 193ms	remaining: 1.01s
160:	learn: 0.8244620	total: 194ms	remaining: 1.01s
161:	learn: 0.8233889	total: 195ms	remaining: 1.01s
162:	learn: 0.8220707	total: 197ms	remaining: 1.01s
163:	learn: 0.8185265	total: 198ms	remaining: 1.01s
164:	learn: 0.8143346	total: 200ms	remaining: 1.01s
165:	learn: 0.8112288	total: 201ms	remaining: 1.01s
166:	learn: 0.8076505	total: 202ms	remaining: 1.01s
167:	learn: 0.8065976	total: 204ms	remaining: 1.01s
168:	learn: 0.8041331	total: 205ms	remaining: 1.01s
169:	learn: 0.8032475	total: 206ms	remaining: 1.01s
170:	learn: 0.8021125	total: 208ms	remaining: 1.01s
171:	learn: 0.7985216	total: 209ms	remaining: 1.01s
172:	learn: 0.7971966	total: 211ms	remaining: 1.01s
173:	learn: 0.7956780	total: 212ms	remaining: 1.01s
174:	learn: 0.7923724	total: 214ms	remaining: 1.01s
175:	learn: 0.7911200	total: 214ms	remaining: 1s
176:	learn: 0.7877109	total: 216ms	remaining: 1s
177:	learn: 0.7844963	total: 217ms	remaining: 1s
178:	learn: 0.7805595	total: 218ms	remaining: 1s
179:	learn: 0.7767433	total: 220ms	remaining: 1s
180:	learn: 0.7737907	total: 221ms	remaining: 1000ms
181:	learn: 0.7704945	total: 222ms	remaining: 999ms
182:	learn: 0.7661286	total: 224ms	remaining: 998ms
183:	learn: 0.7613487	total: 225ms	remaining: 999ms
184:	learn: 0.7578331	total: 227ms	remaining: 999ms
185:	learn: 0.7549679	total: 228ms	remaining: 999ms
186:	learn: 0.7524254	total: 230ms	remaining: 999ms
187:	learn: 0.7492662	total: 231ms	remaining: 998ms
188:	learn: 0.7471973	total: 233ms	remaining: 999ms
189:	learn: 0.7444341	total: 235ms	remaining: 1s
190:	learn: 0.7432458	total: 236ms	remaining: 1s
191:	learn: 0.7402886	total: 238ms	remaining: 1000ms
192:	learn: 0.7388272	total: 239ms	remaining: 1000ms
193:	learn: 0.7365103	total: 241ms	remaining: 1000ms
194:	learn: 0.7338043	total: 242ms	remaining: 999ms
195:	learn: 0.7330393	total: 244ms	remaining: 999ms
196:	learn: 0.7322891	total: 245ms	remaining: 998ms
197:	learn: 0.7299376	total: 247ms	remaining: 1s
198:	learn: 0.7280051	total: 249ms	remaining: 1s
199:	learn: 0.7270105	total: 250ms	remaining: 1s
200:	learn: 0.7257147	total: 251ms	remaining: 998ms
201:	learn: 0.7243324	total: 252ms	remaining: 997ms
202:	learn: 0.7215565	total: 254ms	remaining: 996ms
203:	learn: 0.7195794	total: 255ms	remaining: 995ms
204:	learn: 0.7157732	total: 257ms	remaining: 995ms
205:	learn: 0.7124844	total: 258ms	remaining: 994ms
206:	learn: 0.7098456	total: 259ms	remaining: 993ms
207:	learn: 0.7073125	total: 260ms	remaining: 991ms
208:	learn: 0.7052318	total: 262ms	remaining: 990ms
209:	learn: 0.7017213	total: 263ms	remaining: 988ms
210:	learn: 0.7009039	total: 264ms	remaining: 987ms
211:	learn: 0.6959542	total: 265ms	remaining: 985ms
212:	learn: 0.6939258	total: 266ms	remaining: 984ms
213:	learn: 0.6927073	total: 267ms	remaining: 982ms
214:	learn: 0.6910240	total: 269ms	remaining: 983ms
215:	learn: 0.6902187	total: 271ms	remaining: 983ms
216:	learn: 0.6880975	total: 272ms	remaining: 982ms
217:	learn: 0.6865722	total: 273ms	remaining: 981ms
218:	learn: 0.6840065	total: 275ms	remaining: 979ms
219:	learn: 0.6815185	total: 276ms	remaining: 978ms
220:	learn: 0.6792973	total: 277ms	remaining: 977ms
221:	learn: 0.6785689	total: 278ms	remaining: 976ms
222:	learn: 0.6756590	total: 280ms	remaining: 974ms
223:	learn: 0.6731322	total: 281ms	remaining: 974ms
224:	learn: 0.6702693	total: 282ms	remaining: 973ms
225:	learn: 0.6671006	total: 284ms	remaining: 974ms
226:	learn: 0.6631466	total: 286ms	remaining: 973ms
227:	learn: 0.6600818	total: 287ms	remaining: 972ms
228:	learn: 0.6584396	total: 288ms	remaining: 971ms
229:	learn: 0.6578769	total: 290ms	remaining: 970ms
230:	learn: 0.6548414	total: 291ms	remaining: 968ms
231:	learn: 0.6530993	total: 292ms	remaining: 966ms
232:	learn: 0.6490440	total: 293ms	remaining: 965ms
233:	learn: 0.6466156	total: 294ms	remaining: 964ms
234:	learn: 0.6428404	total: 296ms	remaining: 963ms
235:	learn: 0.6405111	total: 297ms	remaining: 962ms
236:	learn: 0.6363219	total: 299ms	remaining: 961ms
237:	learn: 0.6342293	total: 300ms	remaining: 960ms
238:	learn: 0.6316975	total: 301ms	remaining: 959ms
239:	learn: 0.6298450	total: 303ms	remaining: 959ms
240:	learn: 0.6265171	total: 304ms	remaining: 958ms
241:	learn: 0.6237966	total: 306ms	remaining: 957ms
242:	learn: 0.6203029	total: 307ms	remaining: 956ms
243:	learn: 0.6186998	total: 308ms	remaining: 954ms
244:	learn: 0.6181040	total: 309ms	remaining: 953ms
245:	learn: 0.6153817	total: 311ms	remaining: 952ms
246:	learn: 0.6110653	total: 312ms	remaining: 951ms
247:	learn: 0.6097894	total: 313ms	remaining: 950ms
248:	learn: 0.6071210	total: 315ms	remaining: 949ms
249:	learn: 0.6047254	total: 316ms	remaining: 948ms
250:	learn: 0.6030763	total: 317ms	remaining: 947ms
251:	learn: 0.6016383	total: 318ms	remaining: 945ms
252:	learn: 0.5971910	total: 320ms	remaining: 944ms
253:	learn: 0.5948981	total: 321ms	remaining: 942ms
254:	learn: 0.5940894	total: 322ms	remaining: 941ms
255:	learn: 0.5923927	total: 323ms	remaining: 940ms
256:	learn: 0.5902935	total: 325ms	remaining: 938ms
257:	learn: 0.5888096	total: 326ms	remaining: 937ms
258:	learn: 0.5861400	total: 327ms	remaining: 936ms
259:	learn: 0.5812735	total: 329ms	remaining: 936ms
260:	learn: 0.5800440	total: 330ms	remaining: 935ms
261:	learn: 0.5782328	total: 331ms	remaining: 934ms
262:	learn: 0.5764985	total: 333ms	remaining: 932ms
263:	learn: 0.5743280	total: 334ms	remaining: 931ms
264:	learn: 0.5727559	total: 335ms	remaining: 929ms
265:	learn: 0.5713315	total: 336ms	remaining: 928ms
266:	learn: 0.5700042	total: 338ms	remaining: 927ms
267:	learn: 0.5672384	total: 339ms	remaining: 926ms
268:	learn: 0.5658194	total: 340ms	remaining: 924ms
269:	learn: 0.5644396	total: 342ms	remaining: 924ms
270:	learn: 0.5629302	total: 343ms	remaining: 923ms
271:	learn: 0.5587024	total: 344ms	remaining: 922ms
272:	learn: 0.5569394	total: 346ms	remaining: 921ms
273:	learn: 0.5555784	total: 347ms	remaining: 919ms
274:	learn: 0.5531178	total: 348ms	remaining: 918ms
275:	learn: 0.5495204	total: 350ms	remaining: 917ms
276:	learn: 0.5474145	total: 351ms	remaining: 915ms
277:	learn: 0.5459847	total: 352ms	remaining: 913ms
278:	learn: 0.5424783	total: 353ms	remaining: 912ms
279:	learn: 0.5388240	total: 354ms	remaining: 911ms
280:	learn: 0.5377784	total: 355ms	remaining: 910ms
281:	learn: 0.5366306	total: 357ms	remaining: 910ms
282:	learn: 0.5357942	total: 359ms	remaining: 909ms
283:	learn: 0.5336375	total: 360ms	remaining: 908ms
284:	learn: 0.5306529	total: 361ms	remaining: 907ms
285:	learn: 0.5273456	total: 363ms	remaining: 905ms
286:	learn: 0.5261312	total: 365ms	remaining: 907ms
287:	learn: 0.5222059	total: 368ms	remaining: 909ms
288:	learn: 0.5208855	total: 370ms	remaining: 911ms
289:	learn: 0.5171991	total: 373ms	remaining: 913ms
290:	learn: 0.5162059	total: 374ms	remaining: 912ms
291:	learn: 0.5130868	total: 377ms	remaining: 914ms
292:	learn: 0.5119590	total: 379ms	remaining: 914ms
293:	learn: 0.5108507	total: 380ms	remaining: 913ms
294:	learn: 0.5069425	total: 381ms	remaining: 912ms
295:	learn: 0.5056152	total: 383ms	remaining: 910ms
296:	learn: 0.5044897	total: 384ms	remaining: 909ms
297:	learn: 0.5034315	total: 385ms	remaining: 907ms
298:	learn: 0.5006589	total: 387ms	remaining: 907ms
299:	learn: 0.4987528	total: 388ms	remaining: 906ms
300:	learn: 0.4976986	total: 390ms	remaining: 907ms
301:	learn: 0.4964699	total: 394ms	remaining: 911ms
302:	learn: 0.4948010	total: 396ms	remaining: 912ms
303:	learn: 0.4928853	total: 399ms	remaining: 913ms
304:	learn: 0.4900591	total: 401ms	remaining: 914ms
305:	learn: 0.4873803	total: 403ms	remaining: 915ms
306:	learn: 0.4863644	total: 406ms	remaining: 917ms
307:	learn: 0.4858621	total: 409ms	remaining: 918ms
308:	learn: 0.4851893	total: 411ms	remaining: 920ms
309:	learn: 0.4834790	total: 413ms	remaining: 919ms
310:	learn: 0.4824430	total: 416ms	remaining: 921ms
311:	learn: 0.4799543	total: 418ms	remaining: 922ms
312:	learn: 0.4778369	total: 421ms	remaining: 923ms
313:	learn: 0.4751712	total: 423ms	remaining: 924ms
314:	learn: 0.4734906	total: 425ms	remaining: 925ms
315:	learn: 0.4723553	total: 428ms	remaining: 926ms
316:	learn: 0.4702173	total: 430ms	remaining: 926ms
317:	learn: 0.4689694	total: 432ms	remaining: 927ms
318:	learn: 0.4661416	total: 435ms	remaining: 928ms
319:	learn: 0.4632449	total: 437ms	remaining: 928ms
320:	learn: 0.4612742	total: 439ms	remaining: 929ms
321:	learn: 0.4608813	total: 442ms	remaining: 930ms
322:	learn: 0.4580378	total: 444ms	remaining: 930ms
323:	learn: 0.4565260	total: 446ms	remaining: 930ms
324:	learn: 0.4556734	total: 448ms	remaining: 931ms
325:	learn: 0.4529049	total: 451ms	remaining: 932ms
326:	learn: 0.4498582	total: 453ms	remaining: 932ms
327:	learn: 0.4480185	total: 455ms	remaining: 932ms
328:	learn: 0.4462162	total: 458ms	remaining: 934ms
329:	learn: 0.4445078	total: 460ms	remaining: 935ms
330:	learn: 0.4414539	total: 463ms	remaining: 935ms
331:	learn: 0.4405499	total: 465ms	remaining: 935ms
332:	learn: 0.4395892	total: 466ms	remaining: 933ms
333:	learn: 0.4389919	total: 467ms	remaining: 931ms
334:	learn: 0.4381704	total: 468ms	remaining: 929ms
335:	learn: 0.4364561	total: 470ms	remaining: 928ms
336:	learn: 0.4354210	total: 471ms	remaining: 926ms
337:	learn: 0.4336047	total: 472ms	remaining: 924ms
338:	learn: 0.4328356	total: 473ms	remaining: 922ms
339:	learn: 0.4310027	total: 474ms	remaining: 920ms
340:	learn: 0.4286236	total: 475ms	remaining: 918ms
341:	learn: 0.4282226	total: 476ms	remaining: 917ms
342:	learn: 0.4274695	total: 477ms	remaining: 915ms
343:	learn: 0.4267863	total: 479ms	remaining: 913ms
344:	learn: 0.4253150	total: 480ms	remaining: 911ms
345:	learn: 0.4236518	total: 481ms	remaining: 909ms
346:	learn: 0.4228351	total: 482ms	remaining: 907ms
347:	learn: 0.4222170	total: 484ms	remaining: 907ms
348:	learn: 0.4209046	total: 487ms	remaining: 908ms
349:	learn: 0.4191299	total: 488ms	remaining: 906ms
350:	learn: 0.4178745	total: 489ms	remaining: 904ms
351:	learn: 0.4161653	total: 490ms	remaining: 902ms
352:	learn: 0.4149937	total: 491ms	remaining: 900ms
353:	learn: 0.4147629	total: 493ms	remaining: 899ms
354:	learn: 0.4139437	total: 494ms	remaining: 897ms
355:	learn: 0.4126694	total: 495ms	remaining: 895ms
356:	learn: 0.4114181	total: 496ms	remaining: 893ms
357:	learn: 0.4091829	total: 497ms	remaining: 891ms
358:	learn: 0.4088536	total: 500ms	remaining: 892ms
359:	learn: 0.4077226	total: 501ms	remaining: 892ms
360:	learn: 0.4063171	total: 503ms	remaining: 891ms
361:	learn: 0.4058285	total: 504ms	remaining: 889ms
362:	learn: 0.4048384	total: 505ms	remaining: 887ms
363:	learn: 0.4027976	total: 507ms	remaining: 885ms
364:	learn: 0.4004319	total: 508ms	remaining: 883ms
365:	learn: 0.3995803	total: 509ms	remaining: 881ms
366:	learn: 0.3981541	total: 510ms	remaining: 879ms
367:	learn: 0.3977682	total: 511ms	remaining: 877ms
368:	learn: 0.3956211	total: 512ms	remaining: 876ms
369:	learn: 0.3947760	total: 513ms	remaining: 874ms
370:	learn: 0.3936427	total: 516ms	remaining: 875ms
371:	learn: 0.3925232	total: 518ms	remaining: 874ms
372:	learn: 0.3918482	total: 519ms	remaining: 873ms
373:	learn: 0.3897546	total: 520ms	remaining: 871ms
374:	learn: 0.3894508	total: 521ms	remaining: 869ms
375:	learn: 0.3882420	total: 523ms	remaining: 867ms
376:	learn: 0.3869890	total: 524ms	remaining: 865ms
377:	learn: 0.3864648	total: 525ms	remaining: 863ms
378:	learn: 0.3858312	total: 526ms	remaining: 861ms
379:	learn: 0.3845080	total: 527ms	remaining: 860ms
380:	learn: 0.3842328	total: 528ms	remaining: 858ms

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fitting SVR for TOA_1x1_depth_lt_1
Fitting KNN for TOA_1x1_depth_lt_1
Fitting LR for TOA_1x1_depth_lt_1
Fitting RF for TOA_1x1_depth_lt_1
Fitting CAT for TOA_1x1_depth_lt_1
Learning rate set to 0.033292
0:	learn: 3.7161356	total: 2.37ms	remaining: 2.37s
1:	learn: 3.6553053	total: 3.51ms	remaining: 1.75s
2:	learn: 3.5977415	total: 4.62ms	remaining: 1.53s
3:	learn: 3.5506181	total: 5.72ms	remaining: 1.42s
4:	learn: 3.4849588	total: 6.88ms	remaining: 1.37s
5:	learn: 3.4214788	total: 8.15ms	remaining: 1.35s
6:	learn: 3.3650004	total: 9.41ms	remaining: 1.33s
7:	learn: 3.3315374	total: 10.7ms	remaining: 1.33s
8:	learn: 3.2846784	total: 11.9ms	remaining: 1.31s
9:	learn: 3.2415101	total: 13ms	remaining: 1.29s
10:	learn: 3.1829261	total: 14.1ms	remaining: 1.27s
11:	learn: 3.1356774	total: 15.2ms	remaining: 1.25s
12:	learn: 3.0871020	total: 16.4ms	remaining: 1.24s
13:	learn: 3.0460710	total: 17.4ms	remaining: 1.23s
14:	learn: 3.0110316	total: 18.5ms	remaining: 1.22s
15:	learn: 2.9535509	total: 19.6ms	remaining: 1.21s
16:	learn: 2.9273629	total: 20.7ms	remaining: 1.2s
17:	learn: 2.8746694	total: 21.9ms	remaining: 1.19s
18:	learn: 2.8402390	total: 23ms	remaining: 1.19s
19:	learn: 2.8090027	total: 24.3ms	remaining: 1.19s
20:	learn: 2.7661471	total: 25.5ms	remaining: 1.19s
21:	learn: 2.7145317	total: 26.7ms	remaining: 1.19s
22:	learn: 2.6660534	total: 27.9ms	remaining: 1.18s
23:	learn: 2.6396408	total: 29.1ms	remaining: 1.18s
24:	learn: 2.6062548	total: 30.4ms	remaining: 1.18s
25:	learn: 2.5672325	total: 31.7ms	remaining: 1.19s
26:	learn: 2.5266535	total: 32.9ms	remaining: 1.18s
27:	learn: 2.4871774	total: 34ms	remaining: 1.18s
28:	learn: 2.4564334	total: 35.1ms	remaining: 1.18s
29:	learn: 2.4276436	total: 36.4ms	remaining: 1.18s
30:	learn: 2.3874188	total: 37.8ms	remaining: 1.18s
31:	learn: 2.3530678	total: 39.2ms	remaining: 1.19s
32:	learn: 2.3218940	total: 40.4ms	remaining: 1.18s
33:	learn: 2.2887420	total: 41.6ms	remaining: 1.18s
34:	learn: 2.2570485	total: 42.8ms	remaining: 1.18s
35:	learn: 2.2227050	total: 44ms	remaining: 1.18s
36:	learn: 2.1934513	total: 45.1ms	remaining: 1.17s
37:	learn: 2.1578438	total: 46.3ms	remaining: 1.17s
38:	learn: 2.1342757	total: 47.4ms	remaining: 1.17s
39:	learn: 2.1055046	total: 48.6ms	remaining: 1.17s
40:	learn: 2.0752741	total: 49.7ms	remaining: 1.16s
41:	learn: 2.0616608	total: 50.8ms	remaining: 1.16s
42:	learn: 2.0317938	total: 51.9ms	remaining: 1.16s
43:	learn: 2.0124263	total: 53ms	remaining: 1.15s
44:	learn: 1.9880658	total: 54.6ms	remaining: 1.16s
45:	learn: 1.9592793	total: 55.9ms	remaining: 1.16s
46:	learn: 1.9331475	total: 57.1ms	remaining: 1.16s
47:	learn: 1.9206690	total: 58.3ms	remaining: 1.16s
48:	learn: 1.8992559	total: 59.4ms	remaining: 1.15s
49:	learn: 1.8721016	total: 60.6ms	remaining: 1.15s
50:	learn: 1.8519774	total: 61.7ms	remaining: 1.15s
51:	learn: 1.8347862	total: 62.8ms	remaining: 1.15s
52:	learn: 1.8154945	total: 64ms	remaining: 1.14s
53:	learn: 1.7969690	total: 65.1ms	remaining: 1.14s
54:	learn: 1.7882964	total: 66.2ms	remaining: 1.14s
55:	learn: 1.7719912	total: 67.2ms	remaining: 1.13s
56:	learn: 1.7480813	total: 68.4ms	remaining: 1.13s
57:	learn: 1.7342875	total: 69.5ms	remaining: 1.13s
58:	learn: 1.7181663	total: 70.7ms	remaining: 1.13s
59:	learn: 1.7031344	total: 71.9ms	remaining: 1.13s
60:	learn: 1.6785712	total: 73.2ms	remaining: 1.13s
61:	learn: 1.6635489	total: 74.4ms	remaining: 1.13s
62:	learn: 1.6459771	total: 75.7ms	remaining: 1.13s
63:	learn: 1.6279647	total: 76.8ms	remaining: 1.12s
64:	learn: 1.6096910	total: 78ms	remaining: 1.12s
65:	learn: 1.6026157	total: 79.1ms	remaining: 1.12s
66:	learn: 1.5842181	total: 80.3ms	remaining: 1.12s
67:	learn: 1.5653446	total: 81.4ms	remaining: 1.11s
68:	learn: 1.5508605	total: 82.6ms	remaining: 1.11s
69:	learn: 1.5391292	total: 83.7ms	remaining: 1.11s
70:	learn: 1.5227161	total: 84.8ms	remaining: 1.11s
71:	learn: 1.5132109	total: 87.1ms	remaining: 1.12s
72:	learn: 1.5046507	total: 89.5ms	remaining: 1.14s
73:	learn: 1.4907809	total: 91.9ms	remaining: 1.15s
74:	learn: 1.4765780	total: 94.2ms	remaining: 1.16s
75:	learn: 1.4612714	total: 96.1ms	remaining: 1.17s
76:	learn: 1.4474089	total: 97.2ms	remaining: 1.17s
77:	learn: 1.4322102	total: 98.4ms	remaining: 1.16s
78:	learn: 1.4204902	total: 99.5ms	remaining: 1.16s
79:	learn: 1.4115257	total: 101ms	remaining: 1.16s
80:	learn: 1.4033002	total: 102ms	remaining: 1.16s
81:	learn: 1.3976311	total: 103ms	remaining: 1.16s
82:	learn: 1.3812583	total: 105ms	remaining: 1.16s
83:	learn: 1.3703663	total: 106ms	remaining: 1.15s
84:	learn: 1.3589924	total: 107ms	remaining: 1.15s
85:	learn: 1.3542749	total: 108ms	remaining: 1.15s
86:	learn: 1.3400825	total: 109ms	remaining: 1.15s
87:	learn: 1.3329926	total: 110ms	remaining: 1.14s
88:	learn: 1.3257667	total: 112ms	remaining: 1.14s
89:	learn: 1.3180359	total: 113ms	remaining: 1.14s
90:	learn: 1.3096200	total: 114ms	remaining: 1.14s
91:	learn: 1.2983155	total: 115ms	remaining: 1.13s
92:	learn: 1.2942908	total: 116ms	remaining: 1.13s
93:	learn: 1.2877554	total: 117ms	remaining: 1.13s
94:	learn: 1.2840169	total: 119ms	remaining: 1.13s
95:	learn: 1.2715924	total: 120ms	remaining: 1.13s
96:	learn: 1.2622902	total: 122ms	remaining: 1.13s
97:	learn: 1.2572465	total: 123ms	remaining: 1.13s
98:	learn: 1.2458484	total: 124ms	remaining: 1.13s
99:	learn: 1.2371034	total: 125ms	remaining: 1.13s
100:	learn: 1.2299653	total: 127ms	remaining: 1.13s
101:	learn: 1.2232207	total: 128ms	remaining: 1.12s
102:	learn: 1.2209943	total: 129ms	remaining: 1.12s
103:	learn: 1.2110085	total: 130ms	remaining: 1.12s
104:	learn: 1.2040079	total: 131ms	remaining: 1.12s
105:	learn: 1.1979789	total: 133ms	remaining: 1.12s
106:	learn: 1.1875754	total: 134ms	remaining: 1.12s
107:	learn: 1.1836896	total: 135ms	remaining: 1.12s
108:	learn: 1.1745273	total: 137ms	remaining: 1.12s
109:	learn: 1.1723366	total: 138ms	remaining: 1.11s
110:	learn: 1.1644306	total: 139ms	remaining: 1.11s
111:	learn: 1.1514238	total: 140ms	remaining: 1.11s
112:	learn: 1.1476578	total: 141ms	remaining: 1.11s
113:	learn: 1.1444776	total: 142ms	remaining: 1.11s
114:	learn: 1.1389902	total: 143ms	remaining: 1.1s
115:	learn: 1.1353896	total: 145ms	remaining: 1.1s
116:	learn: 1.1258229	total: 146ms	remaining: 1.1s
117:	learn: 1.1179654	total: 147ms	remaining: 1.1s
118:	learn: 1.1117636	total: 148ms	remaining: 1.09s
119:	learn: 1.1013818	total: 149ms	remaining: 1.09s
120:	learn: 1.0929033	total: 151ms	remaining: 1.09s
121:	learn: 1.0860784	total: 152ms	remaining: 1.09s
122:	learn: 1.0789019	total: 153ms	remaining: 1.09s
123:	learn: 1.0716024	total: 154ms	remaining: 1.09s
124:	learn: 1.0647127	total: 155ms	remaining: 1.09s
125:	learn: 1.0634821	total: 157ms	remaining: 1.08s
126:	learn: 1.0581984	total: 158ms	remaining: 1.08s
127:	learn: 1.0493187	total: 159ms	remaining: 1.08s
128:	learn: 1.0421365	total: 160ms	remaining: 1.08s
129:	learn: 1.0383737	total: 161ms	remaining: 1.08s
130:	learn: 1.0352478	total: 162ms	remaining: 1.08s
131:	learn: 1.0326753	total: 163ms	remaining: 1.07s
132:	learn: 1.0273283	total: 164ms	remaining: 1.07s
133:	learn: 1.0184220	total: 166ms	remaining: 1.07s
134:	learn: 1.0134687	total: 167ms	remaining: 1.07s
135:	learn: 1.0086330	total: 169ms	remaining: 1.07s
136:	learn: 1.0066569	total: 170ms	remaining: 1.07s
137:	learn: 1.0028784	total: 171ms	remaining: 1.07s
138:	learn: 0.9972109	total: 172ms	remaining: 1.06s
139:	learn: 0.9938319	total: 173ms	remaining: 1.06s
140:	learn: 0.9884892	total: 174ms	remaining: 1.06s
141:	learn: 0.9854033	total: 175ms	remaining: 1.06s
142:	learn: 0.9796303	total: 176ms	remaining: 1.06s
143:	learn: 0.9720414	total: 178ms	remaining: 1.05s
144:	learn: 0.9668089	total: 179ms	remaining: 1.05s
145:	learn: 0.9629172	total: 180ms	remaining: 1.05s
146:	learn: 0.9582179	total: 181ms	remaining: 1.05s
147:	learn: 0.9540936	total: 184ms	remaining: 1.06s
148:	learn: 0.9495127	total: 187ms	remaining: 1.06s
149:	learn: 0.9445786	total: 189ms	remaining: 1.07s
150:	learn: 0.9395455	total: 191ms	remaining: 1.07s
151:	learn: 0.9344895	total: 193ms	remaining: 1.08s
152:	learn: 0.9290187	total: 195ms	remaining: 1.08s
153:	learn: 0.9269565	total: 198ms	remaining: 1.09s
154:	learn: 0.9208129	total: 201ms	remaining: 1.1s
155:	learn: 0.9174451	total: 204ms	remaining: 1.1s
156:	learn: 0.9103039	total: 206ms	remaining: 1.11s
157:	learn: 0.9052169	total: 209ms	remaining: 1.11s
158:	learn: 0.9035389	total: 210ms	remaining: 1.11s
159:	learn: 0.8987942	total: 211ms	remaining: 1.11s
160:	learn: 0.8944603	total: 213ms	remaining: 1.11s
161:	learn: 0.8923468	total: 214ms	remaining: 1.1s
162:	learn: 0.8887952	total: 215ms	remaining: 1.1s
163:	learn: 0.8877502	total: 216ms	remaining: 1.1s
164:	learn: 0.8839007	total: 217ms	remaining: 1.1s
165:	learn: 0.8819389	total: 219ms	remaining: 1.1s
166:	learn: 0.8748139	total: 220ms	remaining: 1.1s
167:	learn: 0.8678287	total: 221ms	remaining: 1.09s
168:	learn: 0.8635197	total: 222ms	remaining: 1.09s
169:	learn: 0.8582220	total: 224ms	remaining: 1.09s
170:	learn: 0.8530570	total: 225ms	remaining: 1.09s
171:	learn: 0.8478903	total: 226ms	remaining: 1.09s
172:	learn: 0.8442182	total: 227ms	remaining: 1.09s
173:	learn: 0.8403024	total: 229ms	remaining: 1.08s
174:	learn: 0.8366490	total: 230ms	remaining: 1.08s
175:	learn: 0.8324388	total: 231ms	remaining: 1.08s
176:	learn: 0.8271515	total: 232ms	remaining: 1.08s
177:	learn: 0.8239705	total: 233ms	remaining: 1.08s
178:	learn: 0.8222376	total: 235ms	remaining: 1.08s
179:	learn: 0.8187075	total: 236ms	remaining: 1.07s
180:	learn: 0.8138970	total: 238ms	remaining: 1.07s
181:	learn: 0.8083623	total: 239ms	remaining: 1.07s
182:	learn: 0.8047060	total: 241ms	remaining: 1.07s
183:	learn: 0.8013927	total: 242ms	remaining: 1.07s
184:	learn: 0.7981970	total: 243ms	remaining: 1.07s
185:	learn: 0.7946904	total: 244ms	remaining: 1.07s
186:	learn: 0.7915840	total: 246ms	remaining: 1.07s
187:	learn: 0.7877212	total: 247ms	remaining: 1.07s
188:	learn: 0.7847621	total: 248ms	remaining: 1.06s
189:	learn: 0.7820252	total: 249ms	remaining: 1.06s
190:	learn: 0.7774910	total: 251ms	remaining: 1.06s
191:	learn: 0.7732131	total: 252ms	remaining: 1.06s
192:	learn: 0.7699740	total: 253ms	remaining: 1.06s
193:	learn: 0.7658514	total: 255ms	remaining: 1.06s
194:	learn: 0.7614920	total: 256ms	remaining: 1.06s
195:	learn: 0.7592714	total: 257ms	remaining: 1.05s
196:	learn: 0.7553779	total: 258ms	remaining: 1.05s
197:	learn: 0.7510487	total: 259ms	remaining: 1.05s
198:	learn: 0.7479200	total: 261ms	remaining: 1.05s
199:	learn: 0.7449258	total: 262ms	remaining: 1.05s
200:	learn: 0.7433371	total: 264ms	remaining: 1.05s
201:	learn: 0.7398633	total: 265ms	remaining: 1.05s
202:	learn: 0.7362392	total: 267ms	remaining: 1.05s
203:	learn: 0.7337308	total: 268ms	remaining: 1.04s
204:	learn: 0.7287504	total: 269ms	remaining: 1.04s
205:	learn: 0.7271738	total: 270ms	remaining: 1.04s
206:	learn: 0.7254293	total: 271ms	remaining: 1.04s
207:	learn: 0.7236537	total: 272ms	remaining: 1.04s
208:	learn: 0.7202250	total: 273ms	remaining: 1.03s
209:	learn: 0.7192204	total: 274ms	remaining: 1.03s
210:	learn: 0.7150729	total: 276ms	remaining: 1.03s
211:	learn: 0.7138147	total: 279ms	remaining: 1.03s
212:	learn: 0.7095272	total: 281ms	remaining: 1.04s
213:	learn: 0.7054933	total: 284ms	remaining: 1.04s
214:	learn: 0.7014485	total: 286ms	remaining: 1.04s
215:	learn: 0.6977848	total: 289ms	remaining: 1.05s
216:	learn: 0.6936233	total: 291ms	remaining: 1.05s
217:	learn: 0.6915757	total: 293ms	remaining: 1.05s
218:	learn: 0.6874962	total: 296ms	remaining: 1.05s
219:	learn: 0.6852701	total: 298ms	remaining: 1.05s
220:	learn: 0.6824681	total: 299ms	remaining: 1.05s
221:	learn: 0.6791370	total: 300ms	remaining: 1.05s
222:	learn: 0.6757685	total: 301ms	remaining: 1.05s
223:	learn: 0.6739411	total: 303ms	remaining: 1.05s
224:	learn: 0.6705573	total: 304ms	remaining: 1.05s
225:	learn: 0.6683746	total: 305ms	remaining: 1.04s
226:	learn: 0.6668720	total: 306ms	remaining: 1.04s
227:	learn: 0.6632424	total: 307ms	remaining: 1.04s
228:	learn: 0.6604046	total: 310ms	remaining: 1.04s
229:	learn: 0.6589853	total: 313ms	remaining: 1.05s
230:	learn: 0.6548595	total: 316ms	remaining: 1.05s
231:	learn: 0.6537092	total: 318ms	remaining: 1.05s
232:	learn: 0.6498300	total: 321ms	remaining: 1.05s
233:	learn: 0.6474509	total: 323ms	remaining: 1.06s
234:	learn: 0.6467201	total: 325ms	remaining: 1.06s
235:	learn: 0.6440530	total: 328ms	remaining: 1.06s
236:	learn: 0.6427661	total: 329ms	remaining: 1.06s
237:	learn: 0.6404174	total: 331ms	remaining: 1.06s
238:	learn: 0.6383276	total: 332ms	remaining: 1.06s
239:	learn: 0.6355898	total: 333ms	remaining: 1.05s
240:	learn: 0.6325993	total: 334ms	remaining: 1.05s
241:	learn: 0.6310865	total: 335ms	remaining: 1.05s
242:	learn: 0.6291181	total: 336ms	remaining: 1.05s
243:	learn: 0.6261739	total: 337ms	remaining: 1.04s
244:	learn: 0.6253358	total: 338ms	remaining: 1.04s
245:	learn: 0.6227467	total: 340ms	remaining: 1.04s
246:	learn: 0.6212124	total: 341ms	remaining: 1.04s
247:	learn: 0.6168407	total: 342ms	remaining: 1.04s
248:	learn: 0.6157177	total: 345ms	remaining: 1.04s
249:	learn: 0.6122404	total: 346ms	remaining: 1.04s
250:	learn: 0.6095619	total: 347ms	remaining: 1.03s
251:	learn: 0.6075880	total: 348ms	remaining: 1.03s
252:	learn: 0.6054239	total: 349ms	remaining: 1.03s
253:	learn: 0.6034359	total: 350ms	remaining: 1.03s
254:	learn: 0.6010108	total: 352ms	remaining: 1.03s
255:	learn: 0.5985208	total: 353ms	remaining: 1.02s
256:	learn: 0.5964810	total: 354ms	remaining: 1.02s
257:	learn: 0.5947395	total: 355ms	remaining: 1.02s
258:	learn: 0.5917455	total: 356ms	remaining: 1.02s
259:	learn: 0.5885442	total: 358ms	remaining: 1.02s
260:	learn: 0.5882718	total: 360ms	remaining: 1.02s
261:	learn: 0.5863941	total: 361ms	remaining: 1.02s
262:	learn: 0.5844069	total: 363ms	remaining: 1.01s
263:	learn: 0.5805192	total: 364ms	remaining: 1.01s
264:	learn: 0.5782538	total: 365ms	remaining: 1.01s
265:	learn: 0.5755130	total: 366ms	remaining: 1.01s
266:	learn: 0.5730290	total: 367ms	remaining: 1.01s
267:	learn: 0.5696646	total: 368ms	remaining: 1s
268:	learn: 0.5693079	total: 369ms	remaining: 1s
269:	learn: 0.5670669	total: 371ms	remaining: 1s
270:	learn: 0.5668191	total: 372ms	remaining: 1s
271:	learn: 0.5642952	total: 374ms	remaining: 1s
272:	learn: 0.5600294	total: 376ms	remaining: 1s
273:	learn: 0.5557951	total: 378ms	remaining: 1s
274:	learn: 0.5532769	total: 379ms	remaining: 999ms
275:	learn: 0.5504936	total: 380ms	remaining: 997ms
276:	learn: 0.5489769	total: 381ms	remaining: 995ms
277:	learn: 0.5473958	total: 382ms	remaining: 993ms
278:	learn: 0.5442302	total: 383ms	remaining: 991ms
279:	learn: 0.5426719	total: 384ms	remaining: 989ms
280:	learn: 0.5402804	total: 386ms	remaining: 987ms
281:	learn: 0.5381777	total: 387ms	remaining: 985ms
282:	learn: 0.5366950	total: 389ms	remaining: 985ms
283:	learn: 0.5363828	total: 391ms	remaining: 986ms
284:	learn: 0.5334040	total: 393ms	remaining: 986ms
285:	learn: 0.5312125	total: 395ms	remaining: 985ms
286:	learn: 0.5296309	total: 396ms	remaining: 983ms
287:	learn: 0.5260605	total: 397ms	remaining: 981ms
288:	learn: 0.5229414	total: 398ms	remaining: 980ms
289:	learn: 0.5206502	total: 399ms	remaining: 978ms
290:	learn: 0.5186821	total: 401ms	remaining: 976ms
291:	learn: 0.5165687	total: 402ms	remaining: 974ms
292:	learn: 0.5135400	total: 403ms	remaining: 973ms
293:	learn: 0.5104355	total: 405ms	remaining: 973ms
294:	learn: 0.5091174	total: 407ms	remaining: 973ms
295:	learn: 0.5088368	total: 409ms	remaining: 972ms
296:	learn: 0.5065928	total: 410ms	remaining: 970ms
297:	learn: 0.5044122	total: 411ms	remaining: 969ms
298:	learn: 0.5029257	total: 413ms	remaining: 967ms
299:	learn: 0.5012370	total: 414ms	remaining: 965ms
300:	learn: 0.4993770	total: 415ms	remaining: 964ms
301:	learn: 0.4972507	total: 417ms	remaining: 963ms
302:	learn: 0.4958882	total: 418ms	remaining: 962ms
303:	learn: 0.4945440	total: 420ms	remaining: 962ms
304:	learn: 0.4938874	total: 422ms	remaining: 962ms
305:	learn: 0.4923959	total: 424ms	remaining: 961ms
306:	learn: 0.4907002	total: 425ms	remaining: 959ms
307:	learn: 0.4895825	total: 426ms	remaining: 957ms
308:	learn: 0.4884909	total: 427ms	remaining: 956ms
309:	learn: 0.4871935	total: 428ms	remaining: 954ms
310:	learn: 0.4853425	total: 430ms	remaining: 952ms
311:	learn: 0.4834330	total: 431ms	remaining: 950ms
312:	learn: 0.4821401	total: 432ms	remaining: 948ms
313:	learn: 0.4806138	total: 434ms	remaining: 947ms
314:	learn: 0.4775990	total: 435ms	remaining: 947ms
315:	learn: 0.4765458	total: 438ms	remaining: 948ms
316:	learn: 0.4752689	total: 439ms	remaining: 946ms
317:	learn: 0.4728301	total: 441ms	remaining: 945ms
318:	learn: 0.4705134	total: 442ms	remaining: 943ms
319:	learn: 0.4702151	total: 443ms	remaining: 941ms
320:	learn: 0.4691317	total: 444ms	remaining: 940ms
321:	learn: 0.4670888	total: 446ms	remaining: 938ms
322:	learn: 0.4657551	total: 447ms	remaining: 937ms
323:	learn: 0.4638756	total: 448ms	remaining: 935ms
324:	learn: 0.4621325	total: 450ms	remaining: 935ms
325:	learn: 0.4607088	total: 452ms	remaining: 935ms
326:	learn: 0.4590727	total: 454ms	remaining: 934ms
327:	learn: 0.4580747	total: 455ms	remaining: 933ms
328:	learn: 0.4565187	total: 457ms	remaining: 931ms
329:	learn: 0.4550505	total: 458ms	remaining: 930ms
330:	learn: 0.4527828	total: 459ms	remaining: 928ms
331:	learn: 0.4512775	total: 461ms	remaining: 927ms
332:	learn: 0.4510578	total: 462ms	remaining: 925ms
333:	learn: 0.4493637	total: 463ms	remaining: 923ms
334:	learn: 0.4478569	total: 465ms	remaining: 922ms
335:	learn: 0.4459813	total: 466ms	remaining: 921ms
336:	learn: 0.4447821	total: 469ms	remaining: 922ms
337:	learn: 0.4439603	total: 470ms	remaining: 920ms
338:	learn: 0.4421062	total: 471ms	remaining: 919ms
339:	learn: 0.4405917	total: 472ms	remaining: 917ms
340:	learn: 0.4390518	total: 474ms	remaining: 915ms
341:	learn: 0.4381360	total: 475ms	remaining: 914ms
342:	learn: 0.4359896	total: 476ms	remaining: 912ms
343:	learn: 0.4346344	total: 477ms	remaining: 910ms
344:	learn: 0.4344113	total: 478ms	remaining: 908ms
345:	learn: 0.4320237	total: 480ms	remaining: 908ms
346:	learn: 0.4317671	total: 482ms	remaining: 907ms
347:	learn: 0.4305857	total: 483ms	remaining: 906ms
348:	learn: 0.4304162	total: 485ms	remaining: 904ms
349:	learn: 0.4289404	total: 486ms	remaining: 903ms
350:	learn: 0.4273564	total: 487ms	remaining: 901ms
351:	learn: 0.4265580	total: 488ms	remaining: 899ms
352:	learn: 0.4257380	total: 489ms	remaining: 897ms
353:	learn: 0.4248396	total: 491ms	remaining: 895ms
354:	learn: 0.4235814	total: 492ms	remaining: 893ms
355:	learn: 0.4209138	total: 493ms	remaining: 892ms
356:	learn: 0.4201704	total: 494ms	remaining: 890ms
357:	learn: 0.4198602	total: 496ms	remaining: 890ms
358:	learn: 0.4185424	total: 499ms	remaining: 891ms
359:	learn: 0.4178395	total: 502ms	remaining: 892ms
360:	learn: 0.4170302	total: 504ms	remaining: 893ms
361:	learn: 0.4168354	total: 507ms	remaining: 893ms
362:	learn: 0.4161036	total: 509ms	remaining: 893ms
363:	learn: 0.4149992	total: 511ms	remaining: 893ms
364:	learn: 0.4122825	total: 514ms	remaining: 894ms
365:	learn: 0.4103265	total: 515ms	remaining: 892ms
366:	learn: 0.4098113	total: 516ms	remaining: 890ms
367:	learn: 0.4096495	total: 517ms	remaining: 889ms
368:	learn: 0.4082148	total: 519ms	remaining: 887ms
369:	learn: 0.4070898	total: 520ms	remaining: 885ms
370:	learn: 0.4060985	total: 521ms	remaining: 883ms
371:	learn: 0.4041304	total: 522ms	remaining: 881ms
372:	learn: 0.4030631	total: 523ms	remaining: 879ms
373:	learn: 0.4012959	total: 524ms	remaining: 877ms
374:	learn: 0.4004425	total: 525ms	remaining: 876ms
375:	learn: 0.3994435	total: 528ms	remaining: 876ms
376:	learn: 0.3978942	total: 531ms	remaining: 878ms
377:	learn: 0.3966316	total: 534ms	remaining: 878ms
378:	learn: 0.3944323	total: 536ms	remaining: 878ms
379:	learn: 0.3925389	total: 538ms	remaining: 878ms
380:	learn: 0.3913291	total: 541ms	remaining: 878ms
381:	learn: 0.3904277	total: 543ms	remaining: 878ms

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fitting SVR for C2X-Complex_rhow_5x5_depth_lt_1
Fitting KNN for C2X-Complex_rhow_5x5_depth_lt_1
Fitting LR for C2X-Complex_rhow_5x5_depth_lt_1
Fitting RF for C2X-Complex_rhow_5x5_depth_lt_1
Fitting CAT for C2X-Complex_rhow_5x5_depth_lt_1
Learning rate set to 0.033272
0:	learn: 3.4066301	total: 1.81ms	remaining: 1.81s
1:	learn: 3.3487528	total: 3.05ms	remaining: 1.52s
2:	learn: 3.2939454	total: 4.24ms	remaining: 1.41s
3:	learn: 3.2394650	total: 5.45ms	remaining: 1.36s
4:	learn: 3.1902399	total: 6.79ms	remaining: 1.35s
5:	learn: 3.1430165	total: 8.13ms	remaining: 1.35s
6:	learn: 3.0999795	total: 9.51ms	remaining: 1.35s
7:	learn: 3.0507580	total: 10.7ms	remaining: 1.33s
8:	learn: 2.9920305	total: 12ms	remaining: 1.32s
9:	learn: 2.9501619	total: 13.2ms	remaining: 1.3s
10:	learn: 2.9064063	total: 14.4ms	remaining: 1.29s
11:	learn: 2.8584655	total: 15.6ms	remaining: 1.28s
12:	learn: 2.8196922	total: 16.8ms	remaining: 1.27s
13:	learn: 2.7791491	total: 17.9ms	remaining: 1.26s
14:	learn: 2.7369484	total: 19ms	remaining: 1.25s
15:	learn: 2.6921672	total: 20.2ms	remaining: 1.24s
16:	learn: 2.6478091	total: 21.3ms	remaining: 1.23s
17:	learn: 2.6010791	total: 22.4ms	remaining: 1.22s
18:	learn: 2.5590494	total: 23.7ms	remaining: 1.22s
19:	learn: 2.5201368	total: 25.1ms	remaining: 1.23s
20:	learn: 2.4828395	total: 26.3ms	remaining: 1.23s
21:	learn: 2.4443263	total: 27.6ms	remaining: 1.23s
22:	learn: 2.4018681	total: 28.8ms	remaining: 1.22s
23:	learn: 2.3645510	total: 30ms	remaining: 1.22s
24:	learn: 2.3321426	total: 31.1ms	remaining: 1.21s
25:	learn: 2.3003813	total: 32.3ms	remaining: 1.21s
26:	learn: 2.2639446	total: 33.4ms	remaining: 1.2s
27:	learn: 2.2324719	total: 34.5ms	remaining: 1.2s
28:	learn: 2.2055399	total: 35.7ms	remaining: 1.19s
29:	learn: 2.1768199	total: 36.8ms	remaining: 1.19s
30:	learn: 2.1528672	total: 38.3ms	remaining: 1.2s
31:	learn: 2.1232886	total: 39.6ms	remaining: 1.2s
32:	learn: 2.0928185	total: 40.9ms	remaining: 1.2s
33:	learn: 2.0695270	total: 42.1ms	remaining: 1.2s
34:	learn: 2.0337185	total: 43.3ms	remaining: 1.19s
35:	learn: 2.0015068	total: 44.7ms	remaining: 1.2s
36:	learn: 1.9812508	total: 45.9ms	remaining: 1.19s
37:	learn: 1.9532523	total: 47ms	remaining: 1.19s
38:	learn: 1.9309229	total: 48.2ms	remaining: 1.19s
39:	learn: 1.9074408	total: 49.3ms	remaining: 1.18s
40:	learn: 1.8832533	total: 50.4ms	remaining: 1.18s
41:	learn: 1.8562455	total: 51.6ms	remaining: 1.18s
42:	learn: 1.8373107	total: 52.7ms	remaining: 1.17s
43:	learn: 1.8177649	total: 54ms	remaining: 1.17s
44:	learn: 1.7953870	total: 55.3ms	remaining: 1.17s
45:	learn: 1.7752770	total: 56.7ms	remaining: 1.18s
46:	learn: 1.7508476	total: 57.9ms	remaining: 1.17s
47:	learn: 1.7349349	total: 59.3ms	remaining: 1.18s
48:	learn: 1.7047387	total: 60.8ms	remaining: 1.18s
49:	learn: 1.6869880	total: 61.9ms	remaining: 1.18s
50:	learn: 1.6722406	total: 63.1ms	remaining: 1.18s
51:	learn: 1.6567429	total: 64.3ms	remaining: 1.17s
52:	learn: 1.6332201	total: 65.5ms	remaining: 1.17s
53:	learn: 1.6162760	total: 66.6ms	remaining: 1.17s
54:	learn: 1.5967899	total: 67.8ms	remaining: 1.17s
55:	learn: 1.5808800	total: 69ms	remaining: 1.16s
56:	learn: 1.5560290	total: 70.8ms	remaining: 1.17s
57:	learn: 1.5412450	total: 72ms	remaining: 1.17s
58:	learn: 1.5217926	total: 73.3ms	remaining: 1.17s
59:	learn: 1.5074236	total: 75ms	remaining: 1.17s
60:	learn: 1.4897245	total: 76.3ms	remaining: 1.17s
61:	learn: 1.4784602	total: 77.5ms	remaining: 1.17s
62:	learn: 1.4635620	total: 78.7ms	remaining: 1.17s
63:	learn: 1.4521577	total: 79.9ms	remaining: 1.17s
64:	learn: 1.4373008	total: 81.1ms	remaining: 1.17s
65:	learn: 1.4274324	total: 82.4ms	remaining: 1.17s
66:	learn: 1.4164956	total: 83.6ms	remaining: 1.16s
67:	learn: 1.4048548	total: 84.8ms	remaining: 1.16s
68:	learn: 1.3938045	total: 86.4ms	remaining: 1.17s
69:	learn: 1.3777827	total: 87.9ms	remaining: 1.17s
70:	learn: 1.3628867	total: 89.3ms	remaining: 1.17s
71:	learn: 1.3508386	total: 90.6ms	remaining: 1.17s
72:	learn: 1.3417602	total: 91.8ms	remaining: 1.17s
73:	learn: 1.3317954	total: 93ms	remaining: 1.16s
74:	learn: 1.3163690	total: 94.2ms	remaining: 1.16s
75:	learn: 1.2991144	total: 95.5ms	remaining: 1.16s
76:	learn: 1.2888320	total: 96.7ms	remaining: 1.16s
77:	learn: 1.2790750	total: 98.2ms	remaining: 1.16s
78:	learn: 1.2634077	total: 99.4ms	remaining: 1.16s
79:	learn: 1.2526872	total: 101ms	remaining: 1.16s
80:	learn: 1.2406469	total: 102ms	remaining: 1.16s
81:	learn: 1.2350706	total: 104ms	remaining: 1.16s
82:	learn: 1.2290314	total: 105ms	remaining: 1.16s
83:	learn: 1.2212158	total: 106ms	remaining: 1.16s
84:	learn: 1.2125086	total: 108ms	remaining: 1.16s
85:	learn: 1.2013299	total: 109ms	remaining: 1.16s
86:	learn: 1.1943923	total: 110ms	remaining: 1.15s
87:	learn: 1.1817216	total: 111ms	remaining: 1.15s
88:	learn: 1.1677199	total: 112ms	remaining: 1.15s
89:	learn: 1.1584172	total: 113ms	remaining: 1.15s
90:	learn: 1.1495281	total: 115ms	remaining: 1.15s
91:	learn: 1.1445831	total: 116ms	remaining: 1.14s
92:	learn: 1.1310985	total: 117ms	remaining: 1.14s
93:	learn: 1.1241356	total: 118ms	remaining: 1.14s
94:	learn: 1.1107866	total: 120ms	remaining: 1.14s
95:	learn: 1.1054798	total: 121ms	remaining: 1.14s
96:	learn: 1.0947291	total: 122ms	remaining: 1.14s
97:	learn: 1.0864279	total: 123ms	remaining: 1.14s
98:	learn: 1.0813715	total: 125ms	remaining: 1.13s
99:	learn: 1.0719924	total: 126ms	remaining: 1.13s
100:	learn: 1.0684515	total: 127ms	remaining: 1.13s
101:	learn: 1.0581610	total: 128ms	remaining: 1.13s
102:	learn: 1.0487697	total: 129ms	remaining: 1.12s
103:	learn: 1.0387642	total: 130ms	remaining: 1.12s
104:	learn: 1.0301036	total: 131ms	remaining: 1.12s
105:	learn: 1.0210247	total: 133ms	remaining: 1.12s
106:	learn: 1.0144745	total: 134ms	remaining: 1.12s
107:	learn: 1.0055116	total: 136ms	remaining: 1.12s
108:	learn: 0.9973455	total: 137ms	remaining: 1.12s
109:	learn: 0.9889947	total: 138ms	remaining: 1.12s
110:	learn: 0.9808391	total: 140ms	remaining: 1.12s
111:	learn: 0.9783956	total: 141ms	remaining: 1.11s
112:	learn: 0.9727303	total: 142ms	remaining: 1.11s
113:	learn: 0.9656562	total: 143ms	remaining: 1.11s
114:	learn: 0.9581863	total: 144ms	remaining: 1.11s
115:	learn: 0.9522980	total: 145ms	remaining: 1.11s
116:	learn: 0.9423529	total: 146ms	remaining: 1.1s
117:	learn: 0.9339776	total: 148ms	remaining: 1.11s
118:	learn: 0.9289824	total: 149ms	remaining: 1.1s
119:	learn: 0.9233379	total: 151ms	remaining: 1.11s
120:	learn: 0.9194120	total: 153ms	remaining: 1.11s
121:	learn: 0.9132909	total: 154ms	remaining: 1.11s
122:	learn: 0.9073919	total: 155ms	remaining: 1.11s
123:	learn: 0.8992351	total: 157ms	remaining: 1.11s
124:	learn: 0.8926520	total: 158ms	remaining: 1.1s
125:	learn: 0.8906339	total: 159ms	remaining: 1.1s
126:	learn: 0.8873128	total: 160ms	remaining: 1.1s
127:	learn: 0.8810209	total: 161ms	remaining: 1.1s
128:	learn: 0.8711536	total: 163ms	remaining: 1.1s
129:	learn: 0.8660903	total: 164ms	remaining: 1.1s
130:	learn: 0.8604390	total: 166ms	remaining: 1.1s
131:	learn: 0.8583723	total: 168ms	remaining: 1.1s
132:	learn: 0.8563509	total: 169ms	remaining: 1.1s
133:	learn: 0.8543491	total: 170ms	remaining: 1.1s
134:	learn: 0.8486032	total: 172ms	remaining: 1.1s
135:	learn: 0.8433871	total: 173ms	remaining: 1.1s
136:	learn: 0.8385377	total: 174ms	remaining: 1.09s
137:	learn: 0.8342386	total: 175ms	remaining: 1.09s
138:	learn: 0.8295495	total: 176ms	remaining: 1.09s
139:	learn: 0.8255456	total: 177ms	remaining: 1.09s
140:	learn: 0.8217658	total: 179ms	remaining: 1.09s
141:	learn: 0.8174015	total: 180ms	remaining: 1.09s
142:	learn: 0.8112257	total: 182ms	remaining: 1.09s
143:	learn: 0.8101079	total: 186ms	remaining: 1.1s
144:	learn: 0.8077504	total: 189ms	remaining: 1.11s
145:	learn: 0.8056847	total: 191ms	remaining: 1.12s
146:	learn: 0.8012332	total: 193ms	remaining: 1.12s
147:	learn: 0.7965031	total: 196ms	remaining: 1.13s
148:	learn: 0.7944721	total: 198ms	remaining: 1.13s
149:	learn: 0.7886432	total: 200ms	remaining: 1.14s
150:	learn: 0.7836645	total: 202ms	remaining: 1.14s
151:	learn: 0.7782371	total: 204ms	remaining: 1.14s
152:	learn: 0.7769681	total: 205ms	remaining: 1.13s
153:	learn: 0.7738752	total: 206ms	remaining: 1.13s
154:	learn: 0.7714148	total: 208ms	remaining: 1.13s
155:	learn: 0.7664489	total: 210ms	remaining: 1.13s
156:	learn: 0.7650360	total: 211ms	remaining: 1.13s
157:	learn: 0.7596223	total: 213ms	remaining: 1.13s
158:	learn: 0.7540952	total: 214ms	remaining: 1.13s
159:	learn: 0.7504813	total: 216ms	remaining: 1.13s
160:	learn: 0.7471307	total: 217ms	remaining: 1.13s
161:	learn: 0.7438181	total: 219ms	remaining: 1.13s
162:	learn: 0.7406393	total: 220ms	remaining: 1.13s
163:	learn: 0.7359913	total: 222ms	remaining: 1.13s
164:	learn: 0.7330904	total: 223ms	remaining: 1.13s
165:	learn: 0.7284825	total: 224ms	remaining: 1.13s
166:	learn: 0.7258662	total: 226ms	remaining: 1.13s
167:	learn: 0.7211203	total: 228ms	remaining: 1.13s
168:	learn: 0.7175761	total: 229ms	remaining: 1.13s
169:	learn: 0.7162954	total: 231ms	remaining: 1.13s
170:	learn: 0.7144576	total: 232ms	remaining: 1.13s
171:	learn: 0.7133702	total: 234ms	remaining: 1.13s
172:	learn: 0.7110018	total: 236ms	remaining: 1.13s
173:	learn: 0.7060487	total: 237ms	remaining: 1.13s
174:	learn: 0.7033020	total: 239ms	remaining: 1.12s
175:	learn: 0.6987877	total: 240ms	remaining: 1.12s
176:	learn: 0.6934099	total: 242ms	remaining: 1.12s
177:	learn: 0.6925244	total: 243ms	remaining: 1.12s
178:	learn: 0.6882387	total: 245ms	remaining: 1.12s
179:	learn: 0.6855178	total: 246ms	remaining: 1.12s
180:	learn: 0.6816586	total: 248ms	remaining: 1.12s
181:	learn: 0.6787153	total: 249ms	remaining: 1.12s
182:	learn: 0.6744106	total: 250ms	remaining: 1.12s
183:	learn: 0.6704395	total: 252ms	remaining: 1.12s
184:	learn: 0.6677915	total: 254ms	remaining: 1.12s
185:	learn: 0.6644107	total: 255ms	remaining: 1.12s
186:	learn: 0.6635906	total: 257ms	remaining: 1.11s
187:	learn: 0.6588818	total: 258ms	remaining: 1.12s
188:	learn: 0.6573274	total: 260ms	remaining: 1.11s
189:	learn: 0.6565413	total: 261ms	remaining: 1.11s
190:	learn: 0.6530328	total: 263ms	remaining: 1.11s
191:	learn: 0.6519573	total: 264ms	remaining: 1.11s
192:	learn: 0.6510167	total: 266ms	remaining: 1.11s
193:	learn: 0.6496162	total: 267ms	remaining: 1.11s
194:	learn: 0.6463189	total: 268ms	remaining: 1.11s
195:	learn: 0.6431916	total: 270ms	remaining: 1.11s
196:	learn: 0.6416874	total: 271ms	remaining: 1.1s
197:	learn: 0.6390724	total: 273ms	remaining: 1.1s
198:	learn: 0.6376081	total: 275ms	remaining: 1.11s
199:	learn: 0.6351905	total: 277ms	remaining: 1.11s
200:	learn: 0.6322562	total: 278ms	remaining: 1.1s
201:	learn: 0.6300653	total: 279ms	remaining: 1.1s
202:	learn: 0.6286062	total: 281ms	remaining: 1.1s
203:	learn: 0.6249747	total: 282ms	remaining: 1.1s
204:	learn: 0.6240644	total: 284ms	remaining: 1.1s
205:	learn: 0.6207394	total: 285ms	remaining: 1.1s
206:	learn: 0.6172183	total: 287ms	remaining: 1.1s
207:	learn: 0.6131318	total: 289ms	remaining: 1.1s
208:	learn: 0.6122875	total: 290ms	remaining: 1.1s
209:	learn: 0.6075769	total: 291ms	remaining: 1.1s
210:	learn: 0.6034988	total: 293ms	remaining: 1.09s
211:	learn: 0.6010812	total: 294ms	remaining: 1.09s
212:	learn: 0.5992611	total: 296ms	remaining: 1.09s
213:	learn: 0.5983050	total: 297ms	remaining: 1.09s
214:	learn: 0.5947299	total: 298ms	remaining: 1.09s
215:	learn: 0.5917559	total: 300ms	remaining: 1.09s
216:	learn: 0.5881262	total: 301ms	remaining: 1.08s
217:	learn: 0.5867071	total: 302ms	remaining: 1.08s
218:	learn: 0.5849016	total: 304ms	remaining: 1.08s
219:	learn: 0.5822663	total: 305ms	remaining: 1.08s
220:	learn: 0.5795310	total: 306ms	remaining: 1.08s
221:	learn: 0.5767465	total: 308ms	remaining: 1.08s
222:	learn: 0.5745453	total: 309ms	remaining: 1.08s
223:	learn: 0.5722180	total: 311ms	remaining: 1.07s
224:	learn: 0.5696149	total: 312ms	remaining: 1.07s
225:	learn: 0.5685717	total: 313ms	remaining: 1.07s
226:	learn: 0.5648909	total: 315ms	remaining: 1.07s
227:	learn: 0.5624734	total: 316ms	remaining: 1.07s
228:	learn: 0.5599465	total: 318ms	remaining: 1.07s
229:	learn: 0.5550876	total: 319ms	remaining: 1.07s
230:	learn: 0.5514323	total: 321ms	remaining: 1.07s
231:	learn: 0.5485387	total: 322ms	remaining: 1.07s
232:	learn: 0.5444400	total: 323ms	remaining: 1.06s
233:	learn: 0.5421502	total: 325ms	remaining: 1.06s
234:	learn: 0.5379487	total: 326ms	remaining: 1.06s
235:	learn: 0.5356345	total: 328ms	remaining: 1.06s
236:	learn: 0.5327207	total: 329ms	remaining: 1.06s
237:	learn: 0.5301103	total: 330ms	remaining: 1.06s
238:	learn: 0.5271063	total: 332ms	remaining: 1.06s
239:	learn: 0.5237712	total: 334ms	remaining: 1.06s
240:	learn: 0.5230423	total: 335ms	remaining: 1.05s
241:	learn: 0.5206829	total: 336ms	remaining: 1.05s
242:	learn: 0.5192510	total: 338ms	remaining: 1.05s
243:	learn: 0.5172877	total: 339ms	remaining: 1.05s
244:	learn: 0.5165006	total: 341ms	remaining: 1.05s
245:	learn: 0.5138360	total: 342ms	remaining: 1.05s
246:	learn: 0.5122977	total: 343ms	remaining: 1.05s
247:	learn: 0.5091948	total: 345ms	remaining: 1.04s
248:	learn: 0.5062796	total: 346ms	remaining: 1.04s
249:	learn: 0.5056751	total: 347ms	remaining: 1.04s
250:	learn: 0.5033616	total: 349ms	remaining: 1.04s
251:	learn: 0.5006447	total: 351ms	remaining: 1.04s
252:	learn: 0.4993473	total: 352ms	remaining: 1.04s
253:	learn: 0.4986602	total: 354ms	remaining: 1.04s
254:	learn: 0.4956146	total: 355ms	remaining: 1.04s
255:	learn: 0.4936444	total: 356ms	remaining: 1.03s
256:	learn: 0.4932181	total: 357ms	remaining: 1.03s
257:	learn: 0.4909863	total: 359ms	remaining: 1.03s
258:	learn: 0.4896292	total: 360ms	remaining: 1.03s
259:	learn: 0.4879762	total: 362ms	remaining: 1.03s
260:	learn: 0.4851932	total: 365ms	remaining: 1.03s
261:	learn: 0.4846075	total: 367ms	remaining: 1.03s
262:	learn: 0.4811521	total: 369ms	remaining: 1.03s
263:	learn: 0.4799580	total: 370ms	remaining: 1.03s
264:	learn: 0.4771201	total: 372ms	remaining: 1.03s
265:	learn: 0.4742626	total: 373ms	remaining: 1.03s
266:	learn: 0.4738397	total: 375ms	remaining: 1.03s
267:	learn: 0.4735042	total: 376ms	remaining: 1.03s
268:	learn: 0.4712625	total: 378ms	remaining: 1.03s
269:	learn: 0.4677283	total: 380ms	remaining: 1.03s
270:	learn: 0.4672635	total: 383ms	remaining: 1.03s
271:	learn: 0.4640488	total: 384ms	remaining: 1.03s
272:	learn: 0.4632560	total: 386ms	remaining: 1.03s
273:	learn: 0.4616043	total: 387ms	remaining: 1.03s
274:	learn: 0.4592695	total: 389ms	remaining: 1.02s
275:	learn: 0.4570652	total: 390ms	remaining: 1.02s
276:	learn: 0.4560974	total: 391ms	remaining: 1.02s
277:	learn: 0.4543446	total: 392ms	remaining: 1.02s
278:	learn: 0.4520601	total: 394ms	remaining: 1.02s
279:	learn: 0.4501920	total: 395ms	remaining: 1.02s
280:	learn: 0.4485303	total: 397ms	remaining: 1.01s
281:	learn: 0.4481168	total: 398ms	remaining: 1.01s
282:	learn: 0.4455802	total: 399ms	remaining: 1.01s
283:	learn: 0.4433242	total: 401ms	remaining: 1.01s
284:	learn: 0.4408145	total: 402ms	remaining: 1.01s
285:	learn: 0.4398356	total: 403ms	remaining: 1.01s
286:	learn: 0.4373564	total: 404ms	remaining: 1s
287:	learn: 0.4353068	total: 406ms	remaining: 1s
288:	learn: 0.4338878	total: 407ms	remaining: 1s
289:	learn: 0.4326196	total: 408ms	remaining: 999ms
290:	learn: 0.4322272	total: 410ms	remaining: 998ms
291:	learn: 0.4298768	total: 411ms	remaining: 996ms
292:	learn: 0.4278206	total: 412ms	remaining: 995ms
293:	learn: 0.4259155	total: 413ms	remaining: 993ms
294:	learn: 0.4246321	total: 415ms	remaining: 992ms
295:	learn: 0.4231734	total: 416ms	remaining: 990ms
296:	learn: 0.4221069	total: 418ms	remaining: 988ms
297:	learn: 0.4211320	total: 419ms	remaining: 987ms
298:	learn: 0.4184852	total: 420ms	remaining: 985ms
299:	learn: 0.4158874	total: 422ms	remaining: 984ms
300:	learn: 0.4155234	total: 423ms	remaining: 982ms
301:	learn: 0.4138969	total: 425ms	remaining: 983ms
302:	learn: 0.4126846	total: 427ms	remaining: 981ms
303:	learn: 0.4123246	total: 428ms	remaining: 980ms
304:	learn: 0.4097344	total: 429ms	remaining: 979ms
305:	learn: 0.4086384	total: 431ms	remaining: 977ms
306:	learn: 0.4065595	total: 432ms	remaining: 976ms
307:	learn: 0.4051795	total: 434ms	remaining: 975ms
308:	learn: 0.4032520	total: 435ms	remaining: 973ms
309:	learn: 0.4013824	total: 437ms	remaining: 972ms
310:	learn: 0.4010443	total: 438ms	remaining: 970ms
311:	learn: 0.3994877	total: 439ms	remaining: 969ms
312:	learn: 0.3969896	total: 441ms	remaining: 968ms
313:	learn: 0.3948833	total: 442ms	remaining: 966ms
314:	learn: 0.3935774	total: 444ms	remaining: 965ms
315:	learn: 0.3917069	total: 445ms	remaining: 963ms
316:	learn: 0.3897020	total: 446ms	remaining: 962ms
317:	learn: 0.3882652	total: 448ms	remaining: 960ms
318:	learn: 0.3870917	total: 449ms	remaining: 959ms
319:	learn: 0.3858902	total: 450ms	remaining: 957ms
320:	learn: 0.3842869	total: 452ms	remaining: 956ms
321:	learn: 0.3827640	total: 453ms	remaining: 954ms
322:	learn: 0.3809803	total: 455ms	remaining: 954ms
323:	learn: 0.3793601	total: 456ms	remaining: 952ms
324:	learn: 0.3778148	total: 458ms	remaining: 952ms
325:	learn: 0.3761988	total: 460ms	remaining: 951ms
326:	learn: 0.3742188	total: 461ms	remaining: 949ms
327:	learn: 0.3729167	total: 463ms	remaining: 948ms
328:	learn: 0.3715920	total: 464ms	remaining: 946ms
329:	learn: 0.3704502	total: 465ms	remaining: 945ms
330:	learn: 0.3688214	total: 467ms	remaining: 943ms
331:	learn: 0.3670826	total: 468ms	remaining: 942ms
332:	learn: 0.3651751	total: 470ms	remaining: 941ms
333:	learn: 0.3643203	total: 471ms	remaining: 940ms
334:	learn: 0.3625744	total: 473ms	remaining: 939ms
335:	learn: 0.3610255	total: 475ms	remaining: 938ms
336:	learn: 0.3597592	total: 476ms	remaining: 936ms
337:	learn: 0.3587753	total: 477ms	remaining: 935ms
338:	learn: 0.3570205	total: 479ms	remaining: 934ms
339:	learn: 0.3559571	total: 480ms	remaining: 932ms
340:	learn: 0.3548040	total: 481ms	remaining: 930ms
341:	learn: 0.3536380	total: 483ms	remaining: 929ms
342:	learn: 0.3517580	total: 484ms	remaining: 928ms
343:	learn: 0.3510980	total: 486ms	remaining: 927ms
344:	learn: 0.3492856	total: 487ms	remaining: 925ms
345:	learn: 0.3477430	total: 489ms	remaining: 924ms
346:	learn: 0.3460221	total: 490ms	remaining: 922ms
347:	learn: 0.3455253	total: 491ms	remaining: 921ms
348:	learn: 0.3440514	total: 493ms	remaining: 919ms
349:	learn: 0.3431435	total: 494ms	remaining: 917ms
350:	learn: 0.3419177	total: 495ms	remaining: 916ms
351:	learn: 0.3412848	total: 496ms	remaining: 914ms
352:	learn: 0.3399059	total: 498ms	remaining: 912ms
353:	learn: 0.3388217	total: 499ms	remaining: 911ms
354:	learn: 0.3376687	total: 501ms	remaining: 910ms
355:	learn: 0.3370440	total: 502ms	remaining: 909ms
356:	learn: 0.3352978	total: 504ms	remaining: 907ms
357:	learn: 0.3340508	total: 505ms	remaining: 906ms
358:	learn: 0.3329773	total: 506ms	remaining: 904ms
359:	learn: 0.3319803	total: 508ms	remaining: 902ms
360:	learn: 0.3312344	total: 509ms	remaining: 901ms
361:	learn: 0.3296701	total: 510ms	remaining: 899ms
362:	learn: 0.3282179	total: 512ms	remaining: 898ms
363:	learn: 0.3274201	total: 513ms	remaining: 896ms
364:	learn: 0.3263681	total: 515ms	remaining: 895ms
365:	learn: 0.3251196	total: 516ms	remaining: 894ms
366:	learn: 0.3245644	total: 518ms	remaining: 893ms
367:	learn: 0.3237975	total: 519ms	remaining: 891ms
368:	learn: 0.3231459	total: 520ms	remaining: 890ms
369:	learn: 0.3227860	total: 522ms	remaining: 888ms
370:	learn: 0.3212982	total: 523ms	remaining: 887ms
371:	learn: 0.3206341	total: 524ms	remaining: 885ms
372:	learn: 0.3198349	total: 526ms	remaining: 884ms
373:	learn: 0.3191417	total: 527ms	remaining: 882ms
374:	learn: 0.3183332	total: 529ms	remaining: 881ms
375:	learn: 0.3171901	total: 531ms	remaining: 881ms
376:	learn: 0.3160391	total: 532ms	remaining: 880ms
377:	learn: 0.3150448	total: 534ms	remaining: 878ms
378:	learn: 0.3139338	total: 535ms	remaining: 877ms
379:	learn: 0.3127610	total: 537ms	remaining: 876ms
380:	learn: 0.3117254	total: 538ms	remaining: 874ms

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fitting SVR for C2X-Complex_rhow_9x9_depth_lt_1
Fitting KNN for C2X-Complex_rhow_9x9_depth_lt_1
Fitting LR for C2X-Complex_rhow_9x9_depth_lt_1
Fitting RF for C2X-Complex_rhow_9x9_depth_lt_1
Fitting CAT for C2X-Complex_rhow_9x9_depth_lt_1
Learning rate set to 0.033272
0:	learn: 3.4155406	total: 1.94ms	remaining: 1.94s
1:	learn: 3.3639996	total: 3.32ms	remaining: 1.66s
2:	learn: 3.3055159	total: 5.01ms	remaining: 1.67s
3:	learn: 3.2588074	total: 6.27ms	remaining: 1.56s
4:	learn: 3.2070569	total: 7.47ms	remaining: 1.49s
5:	learn: 3.1644804	total: 8.76ms	remaining: 1.45s
6:	learn: 3.1182098	total: 10ms	remaining: 1.42s
7:	learn: 3.0691317	total: 11.3ms	remaining: 1.4s
8:	learn: 3.0243507	total: 12.6ms	remaining: 1.38s
9:	learn: 2.9777048	total: 13.7ms	remaining: 1.36s
10:	learn: 2.9265349	total: 15ms	remaining: 1.34s
11:	learn: 2.8889814	total: 16.1ms	remaining: 1.33s
12:	learn: 2.8395494	total: 17.4ms	remaining: 1.32s
13:	learn: 2.8010205	total: 19ms	remaining: 1.34s
14:	learn: 2.7620117	total: 20.5ms	remaining: 1.35s
15:	learn: 2.7207234	total: 21.8ms	remaining: 1.34s
16:	learn: 2.6844471	total: 23ms	remaining: 1.33s
17:	learn: 2.6431494	total: 24.2ms	remaining: 1.32s
18:	learn: 2.6108626	total: 25.3ms	remaining: 1.31s
19:	learn: 2.5718543	total: 26.5ms	remaining: 1.3s
20:	learn: 2.5333257	total: 27.6ms	remaining: 1.29s
21:	learn: 2.4935782	total: 28.8ms	remaining: 1.28s
22:	learn: 2.4625768	total: 30ms	remaining: 1.27s
23:	learn: 2.4270088	total: 31.2ms	remaining: 1.27s
24:	learn: 2.3970421	total: 32.5ms	remaining: 1.27s
25:	learn: 2.3655045	total: 33.8ms	remaining: 1.26s
26:	learn: 2.3334442	total: 35.7ms	remaining: 1.28s
27:	learn: 2.3023834	total: 37.2ms	remaining: 1.29s
28:	learn: 2.2675081	total: 38.6ms	remaining: 1.29s
29:	learn: 2.2355928	total: 40ms	remaining: 1.29s
30:	learn: 2.2085914	total: 41.3ms	remaining: 1.29s
31:	learn: 2.1690613	total: 42.5ms	remaining: 1.29s
32:	learn: 2.1414877	total: 43.9ms	remaining: 1.28s
33:	learn: 2.1112899	total: 45.2ms	remaining: 1.28s
34:	learn: 2.0872897	total: 46.5ms	remaining: 1.28s
35:	learn: 2.0687406	total: 47.9ms	remaining: 1.28s
36:	learn: 2.0461166	total: 49.1ms	remaining: 1.28s
37:	learn: 2.0187843	total: 50.6ms	remaining: 1.28s
38:	learn: 1.9930825	total: 51.9ms	remaining: 1.28s
39:	learn: 1.9602337	total: 53.2ms	remaining: 1.28s
40:	learn: 1.9323231	total: 54.6ms	remaining: 1.28s
41:	learn: 1.9079243	total: 55.9ms	remaining: 1.27s
42:	learn: 1.8881060	total: 57.3ms	remaining: 1.27s
43:	learn: 1.8715151	total: 58.6ms	remaining: 1.27s
44:	learn: 1.8484477	total: 60ms	remaining: 1.27s
45:	learn: 1.8299865	total: 61.3ms	remaining: 1.27s
46:	learn: 1.8115184	total: 62.7ms	remaining: 1.27s
47:	learn: 1.7877780	total: 64ms	remaining: 1.27s
48:	learn: 1.7711785	total: 65.5ms	remaining: 1.27s
49:	learn: 1.7546101	total: 67.1ms	remaining: 1.27s
50:	learn: 1.7411771	total: 68.5ms	remaining: 1.27s
51:	learn: 1.7245607	total: 69.7ms	remaining: 1.27s
52:	learn: 1.7050662	total: 71.5ms	remaining: 1.28s
53:	learn: 1.6843154	total: 72.7ms	remaining: 1.27s
54:	learn: 1.6657770	total: 73.9ms	remaining: 1.27s
55:	learn: 1.6461440	total: 75.2ms	remaining: 1.27s
56:	learn: 1.6234201	total: 76.6ms	remaining: 1.27s
57:	learn: 1.6051566	total: 77.9ms	remaining: 1.26s
58:	learn: 1.5919059	total: 79.3ms	remaining: 1.26s
59:	learn: 1.5787327	total: 80.8ms	remaining: 1.26s
60:	learn: 1.5580147	total: 82.4ms	remaining: 1.27s
61:	learn: 1.5420189	total: 83.8ms	remaining: 1.27s
62:	learn: 1.5285512	total: 85.2ms	remaining: 1.27s
63:	learn: 1.5178191	total: 86.5ms	remaining: 1.26s
64:	learn: 1.5008527	total: 87.9ms	remaining: 1.26s
65:	learn: 1.4924304	total: 89.2ms	remaining: 1.26s
66:	learn: 1.4836007	total: 90.6ms	remaining: 1.26s
67:	learn: 1.4659322	total: 92ms	remaining: 1.26s
68:	learn: 1.4577590	total: 93.3ms	remaining: 1.26s
69:	learn: 1.4375144	total: 94.8ms	remaining: 1.26s
70:	learn: 1.4262402	total: 96.3ms	remaining: 1.26s
71:	learn: 1.4118143	total: 97.9ms	remaining: 1.26s
72:	learn: 1.3976148	total: 99.4ms	remaining: 1.26s
73:	learn: 1.3865806	total: 101ms	remaining: 1.26s
74:	learn: 1.3732701	total: 102ms	remaining: 1.26s
75:	learn: 1.3599505	total: 103ms	remaining: 1.26s
76:	learn: 1.3505505	total: 105ms	remaining: 1.26s
77:	learn: 1.3385103	total: 106ms	remaining: 1.25s
78:	learn: 1.3308977	total: 107ms	remaining: 1.25s
79:	learn: 1.3226567	total: 109ms	remaining: 1.25s
80:	learn: 1.3088549	total: 110ms	remaining: 1.25s
81:	learn: 1.3036853	total: 112ms	remaining: 1.25s
82:	learn: 1.2924732	total: 113ms	remaining: 1.25s
83:	learn: 1.2800816	total: 115ms	remaining: 1.25s
84:	learn: 1.2750966	total: 116ms	remaining: 1.25s
85:	learn: 1.2657079	total: 117ms	remaining: 1.24s
86:	learn: 1.2608054	total: 118ms	remaining: 1.24s
87:	learn: 1.2485685	total: 119ms	remaining: 1.24s
88:	learn: 1.2332801	total: 121ms	remaining: 1.23s
89:	learn: 1.2284270	total: 122ms	remaining: 1.23s
90:	learn: 1.2191421	total: 123ms	remaining: 1.23s
91:	learn: 1.2143983	total: 124ms	remaining: 1.23s
92:	learn: 1.2059867	total: 126ms	remaining: 1.22s
93:	learn: 1.1951851	total: 127ms	remaining: 1.22s
94:	learn: 1.1815476	total: 128ms	remaining: 1.22s
95:	learn: 1.1779378	total: 129ms	remaining: 1.22s
96:	learn: 1.1653161	total: 131ms	remaining: 1.22s
97:	learn: 1.1598878	total: 132ms	remaining: 1.21s
98:	learn: 1.1517603	total: 133ms	remaining: 1.21s
99:	learn: 1.1429423	total: 134ms	remaining: 1.21s
100:	learn: 1.1366818	total: 135ms	remaining: 1.2s
101:	learn: 1.1315814	total: 137ms	remaining: 1.2s
102:	learn: 1.1265208	total: 138ms	remaining: 1.2s
103:	learn: 1.1186234	total: 139ms	remaining: 1.2s
104:	learn: 1.1143081	total: 140ms	remaining: 1.19s
105:	learn: 1.1050331	total: 141ms	remaining: 1.19s
106:	learn: 1.0956882	total: 143ms	remaining: 1.19s
107:	learn: 1.0846336	total: 144ms	remaining: 1.19s
108:	learn: 1.0753907	total: 145ms	remaining: 1.19s
109:	learn: 1.0733600	total: 147ms	remaining: 1.19s
110:	learn: 1.0673065	total: 148ms	remaining: 1.18s
111:	learn: 1.0623697	total: 149ms	remaining: 1.18s
112:	learn: 1.0514257	total: 150ms	remaining: 1.18s
113:	learn: 1.0461929	total: 151ms	remaining: 1.18s
114:	learn: 1.0424283	total: 153ms	remaining: 1.17s
115:	learn: 1.0396730	total: 154ms	remaining: 1.17s
116:	learn: 1.0344278	total: 155ms	remaining: 1.17s
117:	learn: 1.0288869	total: 156ms	remaining: 1.17s
118:	learn: 1.0271034	total: 157ms	remaining: 1.16s
119:	learn: 1.0227551	total: 159ms	remaining: 1.16s
120:	learn: 1.0185474	total: 160ms	remaining: 1.16s
121:	learn: 1.0107259	total: 161ms	remaining: 1.16s
122:	learn: 1.0001757	total: 163ms	remaining: 1.16s
123:	learn: 0.9900068	total: 164ms	remaining: 1.16s
124:	learn: 0.9874717	total: 165ms	remaining: 1.16s
125:	learn: 0.9815272	total: 166ms	remaining: 1.15s
126:	learn: 0.9765368	total: 167ms	remaining: 1.15s
127:	learn: 0.9720597	total: 169ms	remaining: 1.15s
128:	learn: 0.9615992	total: 171ms	remaining: 1.15s
129:	learn: 0.9578637	total: 172ms	remaining: 1.15s
130:	learn: 0.9512767	total: 173ms	remaining: 1.15s
131:	learn: 0.9492827	total: 174ms	remaining: 1.15s
132:	learn: 0.9394890	total: 176ms	remaining: 1.15s
133:	learn: 0.9365483	total: 177ms	remaining: 1.14s
134:	learn: 0.9322429	total: 178ms	remaining: 1.14s
135:	learn: 0.9274479	total: 180ms	remaining: 1.14s
136:	learn: 0.9200320	total: 182ms	remaining: 1.14s
137:	learn: 0.9189276	total: 183ms	remaining: 1.14s
138:	learn: 0.9174868	total: 184ms	remaining: 1.14s
139:	learn: 0.9116602	total: 185ms	remaining: 1.14s
140:	learn: 0.9104323	total: 187ms	remaining: 1.14s
141:	learn: 0.9031287	total: 188ms	remaining: 1.14s
142:	learn: 0.9015564	total: 190ms	remaining: 1.14s
143:	learn: 0.8966114	total: 192ms	remaining: 1.14s
144:	learn: 0.8953844	total: 193ms	remaining: 1.14s
145:	learn: 0.8886206	total: 194ms	remaining: 1.14s
146:	learn: 0.8824887	total: 195ms	remaining: 1.13s
147:	learn: 0.8809756	total: 197ms	remaining: 1.13s
148:	learn: 0.8796092	total: 198ms	remaining: 1.13s
149:	learn: 0.8786460	total: 199ms	remaining: 1.13s
150:	learn: 0.8704354	total: 200ms	remaining: 1.13s
151:	learn: 0.8652702	total: 201ms	remaining: 1.12s
152:	learn: 0.8600441	total: 203ms	remaining: 1.12s
153:	learn: 0.8555510	total: 204ms	remaining: 1.12s
154:	learn: 0.8495054	total: 206ms	remaining: 1.12s
155:	learn: 0.8436702	total: 207ms	remaining: 1.12s
156:	learn: 0.8377349	total: 209ms	remaining: 1.12s
157:	learn: 0.8358415	total: 210ms	remaining: 1.12s
158:	learn: 0.8275950	total: 211ms	remaining: 1.12s
159:	learn: 0.8207799	total: 213ms	remaining: 1.12s
160:	learn: 0.8158430	total: 214ms	remaining: 1.11s
161:	learn: 0.8130736	total: 215ms	remaining: 1.11s
162:	learn: 0.8074515	total: 216ms	remaining: 1.11s
163:	learn: 0.8051605	total: 218ms	remaining: 1.11s
164:	learn: 0.8027416	total: 219ms	remaining: 1.11s
165:	learn: 0.8011159	total: 221ms	remaining: 1.11s
166:	learn: 0.8002303	total: 222ms	remaining: 1.11s
167:	learn: 0.7963805	total: 223ms	remaining: 1.11s
168:	learn: 0.7950177	total: 225ms	remaining: 1.11s
169:	learn: 0.7923905	total: 226ms	remaining: 1.1s
170:	learn: 0.7865388	total: 230ms	remaining: 1.11s
171:	learn: 0.7830236	total: 233ms	remaining: 1.12s
172:	learn: 0.7777007	total: 236ms	remaining: 1.13s
173:	learn: 0.7729960	total: 239ms	remaining: 1.13s
174:	learn: 0.7663773	total: 241ms	remaining: 1.14s
175:	learn: 0.7610334	total: 244ms	remaining: 1.14s
176:	learn: 0.7578851	total: 246ms	remaining: 1.14s
177:	learn: 0.7545015	total: 249ms	remaining: 1.15s
178:	learn: 0.7489440	total: 252ms	remaining: 1.15s
179:	learn: 0.7453362	total: 255ms	remaining: 1.16s
180:	learn: 0.7401162	total: 257ms	remaining: 1.16s
181:	learn: 0.7358554	total: 260ms	remaining: 1.17s
182:	learn: 0.7316768	total: 262ms	remaining: 1.17s
183:	learn: 0.7290755	total: 265ms	remaining: 1.17s
184:	learn: 0.7256890	total: 267ms	remaining: 1.18s
185:	learn: 0.7238698	total: 270ms	remaining: 1.18s
186:	learn: 0.7202362	total: 272ms	remaining: 1.18s
187:	learn: 0.7169415	total: 273ms	remaining: 1.18s
188:	learn: 0.7121430	total: 274ms	remaining: 1.18s
189:	learn: 0.7093138	total: 275ms	remaining: 1.17s
190:	learn: 0.7070459	total: 276ms	remaining: 1.17s
191:	learn: 0.7036997	total: 278ms	remaining: 1.17s
192:	learn: 0.6984974	total: 279ms	remaining: 1.17s
193:	learn: 0.6949607	total: 280ms	remaining: 1.16s
194:	learn: 0.6934914	total: 282ms	remaining: 1.16s
195:	learn: 0.6903448	total: 283ms	remaining: 1.16s
196:	learn: 0.6849896	total: 286ms	remaining: 1.17s
197:	learn: 0.6802359	total: 288ms	remaining: 1.17s
198:	learn: 0.6795874	total: 289ms	remaining: 1.16s
199:	learn: 0.6767224	total: 291ms	remaining: 1.16s
200:	learn: 0.6760412	total: 292ms	remaining: 1.16s
201:	learn: 0.6720930	total: 293ms	remaining: 1.16s
202:	learn: 0.6691132	total: 295ms	remaining: 1.16s
203:	learn: 0.6651438	total: 296ms	remaining: 1.16s
204:	learn: 0.6615500	total: 297ms	remaining: 1.15s
205:	learn: 0.6581207	total: 300ms	remaining: 1.16s
206:	learn: 0.6575162	total: 301ms	remaining: 1.15s
207:	learn: 0.6547594	total: 302ms	remaining: 1.15s
208:	learn: 0.6516547	total: 304ms	remaining: 1.15s
209:	learn: 0.6482618	total: 305ms	remaining: 1.15s
210:	learn: 0.6454724	total: 306ms	remaining: 1.14s
211:	learn: 0.6427036	total: 308ms	remaining: 1.14s
212:	learn: 0.6407342	total: 309ms	remaining: 1.14s
213:	learn: 0.6399421	total: 310ms	remaining: 1.14s
214:	learn: 0.6385158	total: 312ms	remaining: 1.14s
215:	learn: 0.6359966	total: 313ms	remaining: 1.14s
216:	learn: 0.6314759	total: 314ms	remaining: 1.13s
217:	learn: 0.6283767	total: 315ms	remaining: 1.13s
218:	learn: 0.6237586	total: 317ms	remaining: 1.13s
219:	learn: 0.6201027	total: 318ms	remaining: 1.13s
220:	learn: 0.6174044	total: 320ms	remaining: 1.13s
221:	learn: 0.6166324	total: 321ms	remaining: 1.13s
222:	learn: 0.6129801	total: 322ms	remaining: 1.12s
223:	learn: 0.6123423	total: 324ms	remaining: 1.12s
224:	learn: 0.6119156	total: 325ms	remaining: 1.12s
225:	learn: 0.6098324	total: 327ms	remaining: 1.12s
226:	learn: 0.6093253	total: 328ms	remaining: 1.12s
227:	learn: 0.6055581	total: 329ms	remaining: 1.11s
228:	learn: 0.6043106	total: 332ms	remaining: 1.12s
229:	learn: 0.6024398	total: 335ms	remaining: 1.12s
230:	learn: 0.5987409	total: 338ms	remaining: 1.12s
231:	learn: 0.5961047	total: 340ms	remaining: 1.13s
232:	learn: 0.5930626	total: 343ms	remaining: 1.13s
233:	learn: 0.5891837	total: 345ms	remaining: 1.13s
234:	learn: 0.5869227	total: 347ms	remaining: 1.13s
235:	learn: 0.5846658	total: 350ms	remaining: 1.13s
236:	learn: 0.5818852	total: 352ms	remaining: 1.13s
237:	learn: 0.5800396	total: 355ms	remaining: 1.14s
238:	learn: 0.5761417	total: 356ms	remaining: 1.13s
239:	learn: 0.5734090	total: 358ms	remaining: 1.13s
240:	learn: 0.5701637	total: 359ms	remaining: 1.13s
241:	learn: 0.5696554	total: 360ms	remaining: 1.13s
242:	learn: 0.5670259	total: 362ms	remaining: 1.13s
243:	learn: 0.5654357	total: 363ms	remaining: 1.12s
244:	learn: 0.5634621	total: 365ms	remaining: 1.12s
245:	learn: 0.5600258	total: 366ms	remaining: 1.12s
246:	learn: 0.5576026	total: 367ms	remaining: 1.12s
247:	learn: 0.5544753	total: 369ms	remaining: 1.12s
248:	learn: 0.5508527	total: 371ms	remaining: 1.12s
249:	learn: 0.5489923	total: 373ms	remaining: 1.12s
250:	learn: 0.5455484	total: 376ms	remaining: 1.12s
251:	learn: 0.5450094	total: 378ms	remaining: 1.12s
252:	learn: 0.5445796	total: 381ms	remaining: 1.13s
253:	learn: 0.5421954	total: 384ms	remaining: 1.13s
254:	learn: 0.5388673	total: 387ms	remaining: 1.13s
255:	learn: 0.5356034	total: 389ms	remaining: 1.13s
256:	learn: 0.5332977	total: 392ms	remaining: 1.13s
257:	learn: 0.5299651	total: 397ms	remaining: 1.14s
258:	learn: 0.5263151	total: 400ms	remaining: 1.14s
259:	learn: 0.5231643	total: 402ms	remaining: 1.15s
260:	learn: 0.5199740	total: 405ms	remaining: 1.15s
261:	learn: 0.5173182	total: 406ms	remaining: 1.14s
262:	learn: 0.5143395	total: 407ms	remaining: 1.14s
263:	learn: 0.5113319	total: 409ms	remaining: 1.14s
264:	learn: 0.5079857	total: 412ms	remaining: 1.14s
265:	learn: 0.5049814	total: 414ms	remaining: 1.14s
266:	learn: 0.5045773	total: 416ms	remaining: 1.14s
267:	learn: 0.5042925	total: 419ms	remaining: 1.14s
268:	learn: 0.5028442	total: 421ms	remaining: 1.14s
269:	learn: 0.5004816	total: 423ms	remaining: 1.14s
270:	learn: 0.4987112	total: 426ms	remaining: 1.15s
271:	learn: 0.4957391	total: 429ms	remaining: 1.15s
272:	learn: 0.4937853	total: 431ms	remaining: 1.15s
273:	learn: 0.4922091	total: 433ms	remaining: 1.15s
274:	learn: 0.4909320	total: 436ms	remaining: 1.15s
275:	learn: 0.4883933	total: 437ms	remaining: 1.15s
276:	learn: 0.4861566	total: 438ms	remaining: 1.14s
277:	learn: 0.4842562	total: 439ms	remaining: 1.14s
278:	learn: 0.4816653	total: 441ms	remaining: 1.14s
279:	learn: 0.4800911	total: 443ms	remaining: 1.14s
280:	learn: 0.4776740	total: 444ms	remaining: 1.14s
281:	learn: 0.4766239	total: 446ms	remaining: 1.14s
282:	learn: 0.4744452	total: 447ms	remaining: 1.13s
283:	learn: 0.4730832	total: 448ms	remaining: 1.13s
284:	learn: 0.4710147	total: 449ms	remaining: 1.13s
285:	learn: 0.4689793	total: 451ms	remaining: 1.12s
286:	learn: 0.4665811	total: 452ms	remaining: 1.12s
287:	learn: 0.4642013	total: 453ms	remaining: 1.12s
288:	learn: 0.4634422	total: 454ms	remaining: 1.12s
289:	learn: 0.4619680	total: 455ms	remaining: 1.11s
290:	learn: 0.4597562	total: 457ms	remaining: 1.11s
291:	learn: 0.4566904	total: 459ms	remaining: 1.11s
292:	learn: 0.4553901	total: 461ms	remaining: 1.11s
293:	learn: 0.4543692	total: 462ms	remaining: 1.11s
294:	learn: 0.4532020	total: 463ms	remaining: 1.11s
295:	learn: 0.4511501	total: 465ms	remaining: 1.1s
296:	learn: 0.4497066	total: 466ms	remaining: 1.1s
297:	learn: 0.4485386	total: 467ms	remaining: 1.1s
298:	learn: 0.4476694	total: 469ms	remaining: 1.1s
299:	learn: 0.4462691	total: 472ms	remaining: 1.1s
300:	learn: 0.4451852	total: 474ms	remaining: 1.1s
301:	learn: 0.4440601	total: 477ms	remaining: 1.1s
302:	learn: 0.4425914	total: 480ms	remaining: 1.1s
303:	learn: 0.4411582	total: 482ms	remaining: 1.1s
304:	learn: 0.4384785	total: 485ms	remaining: 1.1s
305:	learn: 0.4365234	total: 488ms	remaining: 1.1s
306:	learn: 0.4361931	total: 490ms	remaining: 1.11s
307:	learn: 0.4344055	total: 493ms	remaining: 1.11s
308:	learn: 0.4321055	total: 495ms	remaining: 1.11s
309:	learn: 0.4311523	total: 498ms	remaining: 1.11s
310:	learn: 0.4287625	total: 500ms	remaining: 1.11s
311:	learn: 0.4266737	total: 501ms	remaining: 1.1s
312:	learn: 0.4250066	total: 502ms	remaining: 1.1s
313:	learn: 0.4237377	total: 503ms	remaining: 1.1s
314:	learn: 0.4212141	total: 505ms	remaining: 1.1s
315:	learn: 0.4200598	total: 508ms	remaining: 1.1s
316:	learn: 0.4182886	total: 510ms	remaining: 1.1s
317:	learn: 0.4160242	total: 511ms	remaining: 1.1s
318:	learn: 0.4133419	total: 513ms	remaining: 1.09s
319:	learn: 0.4122377	total: 514ms	remaining: 1.09s
320:	learn: 0.4095783	total: 515ms	remaining: 1.09s
321:	learn: 0.4084503	total: 516ms	remaining: 1.09s
322:	learn: 0.4073839	total: 517ms	remaining: 1.08s
323:	learn: 0.4054515	total: 518ms	remaining: 1.08s
324:	learn: 0.4050593	total: 520ms	remaining: 1.08s
325:	learn: 0.4037805	total: 521ms	remaining: 1.08s
326:	learn: 0.4022818	total: 524ms	remaining: 1.08s
327:	learn: 0.3999448	total: 525ms	remaining: 1.07s
328:	learn: 0.3984717	total: 526ms	remaining: 1.07s
329:	learn: 0.3974217	total: 527ms	remaining: 1.07s
330:	learn: 0.3957269	total: 529ms	remaining: 1.07s
331:	learn: 0.3952053	total: 530ms	remaining: 1.06s
332:	learn: 0.3935378	total: 531ms	remaining: 1.06s
333:	learn: 0.3922680	total: 532ms	remaining: 1.06s
334:	learn: 0.3910405	total: 533ms	remaining: 1.06s
335:	learn: 0.3887188	total: 534ms	remaining: 1.06s
336:	learn: 0.3863157	total: 536ms	remaining: 1.05s
337:	learn: 0.3860240	total: 537ms	remaining: 1.05s
338:	learn: 0.3843976	total: 539ms	remaining: 1.05s
339:	learn: 0.3827001	total: 541ms	remaining: 1.05s
340:	learn: 0.3816693	total: 542ms	remaining: 1.05s
341:	learn: 0.3805003	total: 543ms	remaining: 1.04s
342:	learn: 0.3791084	total: 545ms	remaining: 1.04s
343:	learn: 0.3773194	total: 546ms	remaining: 1.04s
344:	learn: 0.3760570	total: 547ms	remaining: 1.04s
345:	learn: 0.3747242	total: 549ms	remaining: 1.04s
346:	learn: 0.3745977	total: 550ms	remaining: 1.03s
347:	learn: 0.3741437	total: 551ms	remaining: 1.03s
348:	learn: 0.3732393	total: 553ms	remaining: 1.03s
349:	learn: 0.3716832	total: 554ms	remaining: 1.03s
350:	learn: 0.3697597	total: 555ms	remaining: 1.03s
351:	learn: 0.3688920	total: 557ms	remaining: 1.02s
352:	learn: 0.3677712	total: 558ms	remaining: 1.02s
353:	learn: 0.3660429	total: 559ms	remaining: 1.02s
354:	learn: 0.3641822	total: 561ms	remaining: 1.02s
355:	learn: 0.3626292	total: 562ms	remaining: 1.02s
356:	learn: 0.3616420	total: 564ms	remaining: 1.01s
357:	learn: 0.3604614	total: 566ms	remaining: 1.01s
358:	learn: 0.3593612	total: 567ms	remaining: 1.01s
359:	learn: 0.3588765	total: 569ms	remaining: 1.01s
360:	learn: 0.3584328	total: 571ms	remaining: 1.01s
361:	learn: 0.3570423	total: 575ms	remaining: 1.01s
362:	learn: 0.3559295	total: 577ms	remaining: 1.01s
363:	learn: 0.3548134	total: 580ms	remaining: 1.01s
364:	learn: 0.3534753	total: 582ms	remaining: 1.01s
365:	learn: 0.3532283	total: 584ms	remaining: 1.01s
366:	learn: 0.3512853	total: 587ms	remaining: 1.01s
367:	learn: 0.3494689	total: 589ms	remaining: 1.01s
368:	learn: 0.3469761	total: 593ms	remaining: 1.01s
369:	learn: 0.3461590	total: 596ms	remaining: 1.01s
370:	learn: 0.3441344	total: 597ms	remaining: 1.01s
371:	learn: 0.3424447	total: 599ms	remaining: 1.01s
372:	learn: 0.3416655	total: 600ms	remaining: 1.01s
373:	learn: 0.3398238	total: 603ms	remaining: 1.01s
374:	learn: 0.3380918	total: 606ms	remaining: 1.01s
375:	learn: 0.3367181	total: 608ms	remaining: 1.01s
376:	learn: 0.3356312	total: 610ms	remaining: 1.01s
377:	learn: 0.3346477	total: 613ms	remaining: 1.01s
378:	learn: 0.3337602	total: 616ms	remaining: 1.01s
379:	learn: 0.3319668	total: 618ms	remaining: 1.01s
380:	learn: 0.3307323	total: 621ms	remaining: 1.01s

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fitting SVR for C2X-Complex_rhow_1x1_depth_lt_1
Fitting KNN for C2X-Complex_rhow_1x1_depth_lt_1
Fitting LR for C2X-Complex_rhow_1x1_depth_lt_1
Fitting RF for C2X-Complex_rhow_1x1_depth_lt_1
Fitting CAT for C2X-Complex_rhow_1x1_depth_lt_1
Learning rate set to 0.033272
0:	learn: 3.4153861	total: 2.85ms	remaining: 2.85s
1:	learn: 3.3576977	total: 4.19ms	remaining: 2.09s
2:	learn: 3.3065378	total: 5.38ms	remaining: 1.79s
3:	learn: 3.2547090	total: 6.62ms	remaining: 1.65s
4:	learn: 3.2012616	total: 7.81ms	remaining: 1.55s
5:	learn: 3.1529368	total: 9.27ms	remaining: 1.53s
6:	learn: 3.1102941	total: 10.5ms	remaining: 1.49s
7:	learn: 3.0637648	total: 11.7ms	remaining: 1.45s
8:	learn: 3.0216873	total: 12.8ms	remaining: 1.41s
9:	learn: 2.9815956	total: 14.1ms	remaining: 1.39s
10:	learn: 2.9436595	total: 15.3ms	remaining: 1.37s
11:	learn: 2.9017267	total: 16.9ms	remaining: 1.39s
12:	learn: 2.8582517	total: 18.2ms	remaining: 1.38s
13:	learn: 2.8284193	total: 19.4ms	remaining: 1.36s
14:	learn: 2.7899403	total: 20.6ms	remaining: 1.35s
15:	learn: 2.7521389	total: 21.8ms	remaining: 1.34s
16:	learn: 2.7228933	total: 22.9ms	remaining: 1.33s
17:	learn: 2.6911412	total: 24.1ms	remaining: 1.32s
18:	learn: 2.6594661	total: 25.3ms	remaining: 1.31s
19:	learn: 2.6260094	total: 26.5ms	remaining: 1.3s
20:	learn: 2.5977876	total: 27.7ms	remaining: 1.29s
21:	learn: 2.5688157	total: 28.9ms	remaining: 1.28s
22:	learn: 2.5393408	total: 30.1ms	remaining: 1.28s
23:	learn: 2.5077124	total: 31.2ms	remaining: 1.27s
24:	learn: 2.4766694	total: 33ms	remaining: 1.29s
25:	learn: 2.4455534	total: 34.3ms	remaining: 1.28s
26:	learn: 2.4171183	total: 35.5ms	remaining: 1.28s
27:	learn: 2.3970463	total: 36.8ms	remaining: 1.27s
28:	learn: 2.3694272	total: 38ms	remaining: 1.27s
29:	learn: 2.3406619	total: 39.2ms	remaining: 1.27s
30:	learn: 2.3087908	total: 40.4ms	remaining: 1.26s
31:	learn: 2.2843456	total: 41.5ms	remaining: 1.26s
32:	learn: 2.2597270	total: 42.7ms	remaining: 1.25s
33:	learn: 2.2346501	total: 43.9ms	remaining: 1.25s
34:	learn: 2.2176243	total: 45.2ms	remaining: 1.25s
35:	learn: 2.1889898	total: 46.4ms	remaining: 1.24s
36:	learn: 2.1639249	total: 47.6ms	remaining: 1.24s
37:	learn: 2.1356803	total: 49.2ms	remaining: 1.25s
38:	learn: 2.1050989	total: 50.8ms	remaining: 1.25s
39:	learn: 2.0892638	total: 52.3ms	remaining: 1.25s
40:	learn: 2.0612409	total: 53.7ms	remaining: 1.26s
41:	learn: 2.0359178	total: 55.2ms	remaining: 1.26s
42:	learn: 2.0168123	total: 56.7ms	remaining: 1.26s
43:	learn: 1.9994765	total: 58.2ms	remaining: 1.26s
44:	learn: 1.9779389	total: 59.5ms	remaining: 1.26s
45:	learn: 1.9651874	total: 60.9ms	remaining: 1.26s
46:	learn: 1.9417336	total: 62.3ms	remaining: 1.26s
47:	learn: 1.9209656	total: 64.5ms	remaining: 1.28s
48:	learn: 1.8993603	total: 66ms	remaining: 1.28s
49:	learn: 1.8811202	total: 67.6ms	remaining: 1.28s
50:	learn: 1.8638146	total: 69ms	remaining: 1.28s
51:	learn: 1.8480746	total: 70.4ms	remaining: 1.28s
52:	learn: 1.8307980	total: 71.9ms	remaining: 1.28s
53:	learn: 1.8121721	total: 73.3ms	remaining: 1.28s
54:	learn: 1.7890091	total: 74.7ms	remaining: 1.28s
55:	learn: 1.7778702	total: 77.8ms	remaining: 1.31s
56:	learn: 1.7622530	total: 79.1ms	remaining: 1.31s
57:	learn: 1.7395925	total: 80.5ms	remaining: 1.31s
58:	learn: 1.7240792	total: 81.8ms	remaining: 1.3s
59:	learn: 1.7075542	total: 83.1ms	remaining: 1.3s
60:	learn: 1.6911693	total: 84.4ms	remaining: 1.3s
61:	learn: 1.6742885	total: 85.5ms	remaining: 1.29s
62:	learn: 1.6582399	total: 86.8ms	remaining: 1.29s
63:	learn: 1.6401924	total: 87.9ms	remaining: 1.29s
64:	learn: 1.6288466	total: 89.1ms	remaining: 1.28s
65:	learn: 1.6196041	total: 90.3ms	remaining: 1.28s
66:	learn: 1.6041323	total: 91.5ms	remaining: 1.27s
67:	learn: 1.5928315	total: 92.7ms	remaining: 1.27s
68:	learn: 1.5790132	total: 93.9ms	remaining: 1.27s
69:	learn: 1.5586698	total: 95.8ms	remaining: 1.27s
70:	learn: 1.5402722	total: 97ms	remaining: 1.27s
71:	learn: 1.5267617	total: 98.3ms	remaining: 1.27s
72:	learn: 1.5135826	total: 99.5ms	remaining: 1.26s
73:	learn: 1.5030468	total: 101ms	remaining: 1.26s
74:	learn: 1.4908199	total: 102ms	remaining: 1.26s
75:	learn: 1.4802040	total: 103ms	remaining: 1.26s
76:	learn: 1.4669169	total: 105ms	remaining: 1.25s
77:	learn: 1.4589430	total: 106ms	remaining: 1.25s
78:	learn: 1.4484324	total: 107ms	remaining: 1.25s
79:	learn: 1.4380531	total: 108ms	remaining: 1.24s
80:	learn: 1.4237071	total: 109ms	remaining: 1.24s
81:	learn: 1.4178668	total: 111ms	remaining: 1.24s
82:	learn: 1.4042502	total: 112ms	remaining: 1.24s
83:	learn: 1.3985009	total: 114ms	remaining: 1.24s
84:	learn: 1.3914892	total: 115ms	remaining: 1.24s
85:	learn: 1.3794563	total: 116ms	remaining: 1.23s
86:	learn: 1.3763264	total: 117ms	remaining: 1.23s
87:	learn: 1.3675769	total: 119ms	remaining: 1.23s
88:	learn: 1.3567438	total: 120ms	remaining: 1.23s
89:	learn: 1.3511370	total: 121ms	remaining: 1.22s
90:	learn: 1.3419972	total: 122ms	remaining: 1.22s
91:	learn: 1.3349987	total: 123ms	remaining: 1.22s
92:	learn: 1.3299918	total: 124ms	remaining: 1.21s
93:	learn: 1.3205480	total: 126ms	remaining: 1.22s
94:	learn: 1.3151027	total: 128ms	remaining: 1.22s
95:	learn: 1.3057614	total: 129ms	remaining: 1.22s
96:	learn: 1.3011683	total: 130ms	remaining: 1.21s
97:	learn: 1.2905646	total: 132ms	remaining: 1.21s
98:	learn: 1.2831343	total: 133ms	remaining: 1.21s
99:	learn: 1.2737669	total: 134ms	remaining: 1.21s
100:	learn: 1.2694008	total: 135ms	remaining: 1.2s
101:	learn: 1.2593631	total: 136ms	remaining: 1.2s
102:	learn: 1.2549445	total: 138ms	remaining: 1.2s
103:	learn: 1.2438222	total: 139ms	remaining: 1.2s
104:	learn: 1.2364376	total: 140ms	remaining: 1.19s
105:	learn: 1.2325648	total: 141ms	remaining: 1.19s
106:	learn: 1.2253628	total: 143ms	remaining: 1.19s
107:	learn: 1.2183649	total: 144ms	remaining: 1.19s
108:	learn: 1.2084992	total: 145ms	remaining: 1.19s
109:	learn: 1.2018053	total: 147ms	remaining: 1.19s
110:	learn: 1.1914792	total: 148ms	remaining: 1.19s
111:	learn: 1.1884931	total: 150ms	remaining: 1.19s
112:	learn: 1.1782864	total: 151ms	remaining: 1.18s
113:	learn: 1.1702871	total: 152ms	remaining: 1.18s
114:	learn: 1.1604327	total: 153ms	remaining: 1.18s
115:	learn: 1.1516297	total: 155ms	remaining: 1.18s
116:	learn: 1.1492857	total: 156ms	remaining: 1.18s
117:	learn: 1.1442447	total: 158ms	remaining: 1.18s
118:	learn: 1.1420640	total: 159ms	remaining: 1.18s
119:	learn: 1.1331682	total: 161ms	remaining: 1.18s
120:	learn: 1.1235435	total: 162ms	remaining: 1.18s
121:	learn: 1.1187314	total: 163ms	remaining: 1.17s
122:	learn: 1.1108535	total: 164ms	remaining: 1.17s
123:	learn: 1.0990932	total: 166ms	remaining: 1.17s
124:	learn: 1.0971977	total: 167ms	remaining: 1.17s
125:	learn: 1.0877594	total: 168ms	remaining: 1.17s
126:	learn: 1.0778782	total: 169ms	remaining: 1.16s
127:	learn: 1.0713407	total: 170ms	remaining: 1.16s
128:	learn: 1.0632451	total: 172ms	remaining: 1.16s
129:	learn: 1.0612361	total: 173ms	remaining: 1.16s
130:	learn: 1.0539303	total: 175ms	remaining: 1.16s
131:	learn: 1.0487304	total: 176ms	remaining: 1.16s
132:	learn: 1.0418279	total: 177ms	remaining: 1.16s
133:	learn: 1.0343508	total: 179ms	remaining: 1.15s
134:	learn: 1.0283397	total: 180ms	remaining: 1.15s
135:	learn: 1.0253847	total: 182ms	remaining: 1.15s
136:	learn: 1.0194550	total: 183ms	remaining: 1.15s
137:	learn: 1.0174394	total: 184ms	remaining: 1.15s
138:	learn: 1.0162265	total: 186ms	remaining: 1.15s
139:	learn: 1.0113512	total: 187ms	remaining: 1.15s
140:	learn: 1.0089061	total: 188ms	remaining: 1.15s
141:	learn: 1.0064479	total: 190ms	remaining: 1.15s
142:	learn: 1.0021125	total: 191ms	remaining: 1.14s
143:	learn: 0.9977137	total: 192ms	remaining: 1.14s
144:	learn: 0.9940645	total: 193ms	remaining: 1.14s
145:	learn: 0.9864269	total: 196ms	remaining: 1.14s
146:	learn: 0.9811758	total: 197ms	remaining: 1.15s
147:	learn: 0.9733909	total: 199ms	remaining: 1.14s
148:	learn: 0.9652613	total: 200ms	remaining: 1.14s
149:	learn: 0.9602955	total: 201ms	remaining: 1.14s
150:	learn: 0.9542383	total: 202ms	remaining: 1.14s
151:	learn: 0.9470132	total: 204ms	remaining: 1.14s
152:	learn: 0.9414053	total: 206ms	remaining: 1.14s
153:	learn: 0.9354993	total: 207ms	remaining: 1.14s
154:	learn: 0.9287983	total: 208ms	remaining: 1.14s
155:	learn: 0.9278102	total: 211ms	remaining: 1.14s
156:	learn: 0.9240163	total: 212ms	remaining: 1.14s
157:	learn: 0.9158505	total: 213ms	remaining: 1.14s
158:	learn: 0.9114728	total: 214ms	remaining: 1.13s
159:	learn: 0.9064893	total: 216ms	remaining: 1.13s
160:	learn: 0.9004182	total: 217ms	remaining: 1.13s
161:	learn: 0.8975373	total: 218ms	remaining: 1.13s
162:	learn: 0.8939014	total: 219ms	remaining: 1.13s
163:	learn: 0.8895433	total: 220ms	remaining: 1.12s
164:	learn: 0.8845258	total: 224ms	remaining: 1.13s
165:	learn: 0.8773129	total: 227ms	remaining: 1.14s
166:	learn: 0.8765472	total: 230ms	remaining: 1.15s
167:	learn: 0.8704621	total: 232ms	remaining: 1.15s
168:	learn: 0.8654637	total: 235ms	remaining: 1.16s
169:	learn: 0.8638476	total: 238ms	remaining: 1.16s
170:	learn: 0.8616251	total: 241ms	remaining: 1.17s
171:	learn: 0.8597736	total: 244ms	remaining: 1.17s
172:	learn: 0.8586409	total: 246ms	remaining: 1.18s
173:	learn: 0.8557033	total: 250ms	remaining: 1.19s
174:	learn: 0.8507444	total: 253ms	remaining: 1.19s
175:	learn: 0.8456715	total: 255ms	remaining: 1.2s
176:	learn: 0.8411716	total: 258ms	remaining: 1.2s
177:	learn: 0.8349944	total: 261ms	remaining: 1.21s
178:	learn: 0.8283225	total: 263ms	remaining: 1.21s
179:	learn: 0.8241018	total: 264ms	remaining: 1.2s
180:	learn: 0.8187198	total: 266ms	remaining: 1.2s
181:	learn: 0.8152231	total: 267ms	remaining: 1.2s
182:	learn: 0.8116676	total: 269ms	remaining: 1.2s
183:	learn: 0.8074526	total: 270ms	remaining: 1.2s
184:	learn: 0.8035108	total: 271ms	remaining: 1.2s
185:	learn: 0.8011006	total: 273ms	remaining: 1.19s
186:	learn: 0.7968022	total: 274ms	remaining: 1.19s
187:	learn: 0.7931461	total: 275ms	remaining: 1.19s
188:	learn: 0.7873195	total: 276ms	remaining: 1.19s
189:	learn: 0.7817969	total: 278ms	remaining: 1.18s
190:	learn: 0.7793708	total: 279ms	remaining: 1.18s
191:	learn: 0.7729806	total: 280ms	remaining: 1.18s
192:	learn: 0.7679602	total: 281ms	remaining: 1.18s
193:	learn: 0.7647982	total: 282ms	remaining: 1.17s
194:	learn: 0.7632883	total: 284ms	remaining: 1.17s
195:	learn: 0.7591463	total: 285ms	remaining: 1.17s
196:	learn: 0.7572676	total: 287ms	remaining: 1.17s
197:	learn: 0.7565155	total: 288ms	remaining: 1.17s
198:	learn: 0.7543028	total: 289ms	remaining: 1.16s
199:	learn: 0.7522333	total: 291ms	remaining: 1.16s
200:	learn: 0.7494261	total: 292ms	remaining: 1.16s
201:	learn: 0.7475203	total: 293ms	remaining: 1.16s
202:	learn: 0.7430215	total: 294ms	remaining: 1.16s
203:	learn: 0.7400733	total: 295ms	remaining: 1.15s
204:	learn: 0.7353954	total: 297ms	remaining: 1.15s
205:	learn: 0.7343023	total: 298ms	remaining: 1.15s
206:	learn: 0.7306124	total: 299ms	remaining: 1.15s
207:	learn: 0.7277151	total: 301ms	remaining: 1.14s
208:	learn: 0.7264791	total: 302ms	remaining: 1.14s
209:	learn: 0.7234662	total: 303ms	remaining: 1.14s
210:	learn: 0.7191733	total: 304ms	remaining: 1.14s
211:	learn: 0.7154184	total: 306ms	remaining: 1.14s
212:	learn: 0.7121357	total: 307ms	remaining: 1.13s
213:	learn: 0.7090390	total: 308ms	remaining: 1.13s
214:	learn: 0.7053894	total: 309ms	remaining: 1.13s
215:	learn: 0.7037659	total: 311ms	remaining: 1.13s
216:	learn: 0.7011556	total: 312ms	remaining: 1.13s
217:	learn: 0.6960617	total: 313ms	remaining: 1.12s
218:	learn: 0.6935359	total: 315ms	remaining: 1.12s
219:	learn: 0.6894212	total: 317ms	remaining: 1.12s
220:	learn: 0.6863729	total: 318ms	remaining: 1.12s
221:	learn: 0.6842379	total: 320ms	remaining: 1.12s
222:	learn: 0.6815660	total: 321ms	remaining: 1.12s
223:	learn: 0.6802385	total: 322ms	remaining: 1.12s
224:	learn: 0.6758309	total: 324ms	remaining: 1.11s
225:	learn: 0.6740887	total: 325ms	remaining: 1.11s
226:	learn: 0.6702713	total: 327ms	remaining: 1.11s
227:	learn: 0.6672447	total: 328ms	remaining: 1.11s
228:	learn: 0.6661543	total: 329ms	remaining: 1.11s
229:	learn: 0.6642894	total: 331ms	remaining: 1.11s
230:	learn: 0.6600236	total: 333ms	remaining: 1.11s
231:	learn: 0.6557915	total: 334ms	remaining: 1.11s
232:	learn: 0.6511533	total: 336ms	remaining: 1.1s
233:	learn: 0.6503831	total: 337ms	remaining: 1.1s
234:	learn: 0.6487846	total: 338ms	remaining: 1.1s
235:	learn: 0.6453040	total: 340ms	remaining: 1.1s
236:	learn: 0.6416743	total: 341ms	remaining: 1.1s
237:	learn: 0.6388361	total: 343ms	remaining: 1.1s
238:	learn: 0.6346947	total: 344ms	remaining: 1.09s
239:	learn: 0.6336467	total: 345ms	remaining: 1.09s
240:	learn: 0.6326973	total: 346ms	remaining: 1.09s
241:	learn: 0.6294821	total: 349ms	remaining: 1.09s
242:	learn: 0.6242656	total: 353ms	remaining: 1.1s
243:	learn: 0.6236016	total: 356ms	remaining: 1.1s
244:	learn: 0.6209777	total: 358ms	remaining: 1.1s
245:	learn: 0.6202646	total: 359ms	remaining: 1.1s
246:	learn: 0.6199697	total: 360ms	remaining: 1.1s
247:	learn: 0.6185381	total: 363ms	remaining: 1.1s
248:	learn: 0.6146587	total: 364ms	remaining: 1.1s
249:	learn: 0.6108464	total: 366ms	remaining: 1.1s
250:	learn: 0.6066162	total: 367ms	remaining: 1.09s
251:	learn: 0.6051513	total: 368ms	remaining: 1.09s
252:	learn: 0.6005922	total: 370ms	remaining: 1.09s
253:	learn: 0.5987311	total: 371ms	remaining: 1.09s
254:	learn: 0.5974199	total: 372ms	remaining: 1.09s
255:	learn: 0.5932434	total: 374ms	remaining: 1.09s
256:	learn: 0.5902915	total: 375ms	remaining: 1.08s
257:	learn: 0.5889446	total: 376ms	remaining: 1.08s
258:	learn: 0.5865175	total: 379ms	remaining: 1.08s
259:	learn: 0.5816421	total: 380ms	remaining: 1.08s
260:	learn: 0.5805775	total: 381ms	remaining: 1.08s
261:	learn: 0.5785528	total: 383ms	remaining: 1.08s
262:	learn: 0.5776863	total: 384ms	remaining: 1.08s
263:	learn: 0.5766641	total: 386ms	remaining: 1.08s
264:	learn: 0.5764279	total: 388ms	remaining: 1.07s
265:	learn: 0.5749961	total: 389ms	remaining: 1.07s
266:	learn: 0.5720914	total: 390ms	remaining: 1.07s
267:	learn: 0.5711620	total: 392ms	remaining: 1.07s
268:	learn: 0.5699040	total: 393ms	remaining: 1.07s
269:	learn: 0.5664001	total: 394ms	remaining: 1.07s
270:	learn: 0.5652096	total: 396ms	remaining: 1.06s
271:	learn: 0.5613071	total: 397ms	remaining: 1.06s
272:	learn: 0.5568220	total: 399ms	remaining: 1.06s
273:	learn: 0.5526507	total: 400ms	remaining: 1.06s
274:	learn: 0.5498506	total: 402ms	remaining: 1.06s
275:	learn: 0.5479059	total: 403ms	remaining: 1.06s
276:	learn: 0.5470181	total: 404ms	remaining: 1.05s
277:	learn: 0.5452555	total: 405ms	remaining: 1.05s
278:	learn: 0.5412556	total: 407ms	remaining: 1.05s
279:	learn: 0.5402474	total: 408ms	remaining: 1.05s
280:	learn: 0.5365384	total: 409ms	remaining: 1.05s
281:	learn: 0.5328685	total: 411ms	remaining: 1.04s
282:	learn: 0.5322391	total: 412ms	remaining: 1.04s
283:	learn: 0.5314560	total: 413ms	remaining: 1.04s
284:	learn: 0.5287915	total: 414ms	remaining: 1.04s
285:	learn: 0.5260627	total: 416ms	remaining: 1.04s
286:	learn: 0.5224690	total: 417ms	remaining: 1.03s
287:	learn: 0.5191291	total: 418ms	remaining: 1.03s
288:	learn: 0.5155825	total: 419ms	remaining: 1.03s
289:	learn: 0.5148278	total: 421ms	remaining: 1.03s
290:	learn: 0.5111621	total: 422ms	remaining: 1.03s
291:	learn: 0.5088933	total: 423ms	remaining: 1.02s
292:	learn: 0.5081916	total: 424ms	remaining: 1.02s
293:	learn: 0.5066315	total: 425ms	remaining: 1.02s
294:	learn: 0.5058700	total: 428ms	remaining: 1.02s
295:	learn: 0.5030484	total: 429ms	remaining: 1.02s
296:	learn: 0.5002497	total: 430ms	remaining: 1.02s
297:	learn: 0.4998912	total: 431ms	remaining: 1.02s
298:	learn: 0.4967262	total: 433ms	remaining: 1.01s
299:	learn: 0.4950536	total: 434ms	remaining: 1.01s
300:	learn: 0.4942672	total: 435ms	remaining: 1.01s
301:	learn: 0.4914855	total: 437ms	remaining: 1.01s
302:	learn: 0.4901122	total: 438ms	remaining: 1.01s
303:	learn: 0.4869445	total: 439ms	remaining: 1s
304:	learn: 0.4833432	total: 440ms	remaining: 1s
305:	learn: 0.4827842	total: 442ms	remaining: 1s
306:	learn: 0.4817813	total: 444ms	remaining: 1s
307:	learn: 0.4802976	total: 445ms	remaining: 1s
308:	learn: 0.4797352	total: 446ms	remaining: 998ms
309:	learn: 0.4790121	total: 448ms	remaining: 996ms
310:	learn: 0.4785815	total: 449ms	remaining: 995ms
311:	learn: 0.4774241	total: 450ms	remaining: 993ms
312:	learn: 0.4758867	total: 452ms	remaining: 991ms
313:	learn: 0.4736016	total: 453ms	remaining: 989ms
314:	learn: 0.4731904	total: 454ms	remaining: 987ms
315:	learn: 0.4706686	total: 456ms	remaining: 987ms
316:	learn: 0.4692718	total: 457ms	remaining: 985ms
317:	learn: 0.4684518	total: 459ms	remaining: 985ms
318:	learn: 0.4668397	total: 461ms	remaining: 984ms
319:	learn: 0.4648245	total: 462ms	remaining: 982ms
320:	learn: 0.4638612	total: 463ms	remaining: 980ms
321:	learn: 0.4609617	total: 465ms	remaining: 978ms
322:	learn: 0.4596487	total: 466ms	remaining: 976ms
323:	learn: 0.4570387	total: 467ms	remaining: 974ms
324:	learn: 0.4541731	total: 468ms	remaining: 972ms
325:	learn: 0.4535965	total: 469ms	remaining: 970ms
326:	learn: 0.4512737	total: 471ms	remaining: 968ms
327:	learn: 0.4496525	total: 472ms	remaining: 966ms
328:	learn: 0.4470034	total: 473ms	remaining: 966ms
329:	learn: 0.4456485	total: 475ms	remaining: 964ms
330:	learn: 0.4431646	total: 476ms	remaining: 963ms
331:	learn: 0.4420770	total: 478ms	remaining: 961ms
332:	learn: 0.4395114	total: 479ms	remaining: 959ms
333:	learn: 0.4391628	total: 480ms	remaining: 957ms
334:	learn: 0.4387390	total: 481ms	remaining: 955ms
335:	learn: 0.4370833	total: 483ms	remaining: 954ms
336:	learn: 0.4362149	total: 484ms	remaining: 952ms
337:	learn: 0.4345264	total: 485ms	remaining: 950ms
338:	learn: 0.4342009	total: 486ms	remaining: 948ms
339:	learn: 0.4324223	total: 487ms	remaining: 946ms
340:	learn: 0.4297365	total: 489ms	remaining: 945ms
341:	learn: 0.4274405	total: 490ms	remaining: 944ms
342:	learn: 0.4263975	total: 492ms	remaining: 942ms
343:	learn: 0.4242764	total: 493ms	remaining: 940ms
344:	learn: 0.4229288	total: 494ms	remaining: 938ms
345:	learn: 0.4219797	total: 495ms	remaining: 937ms
346:	learn: 0.4204305	total: 497ms	remaining: 935ms
347:	learn: 0.4179691	total: 498ms	remaining: 933ms
348:	learn: 0.4164329	total: 499ms	remaining: 931ms
349:	learn: 0.4137077	total: 500ms	remaining: 929ms
350:	learn: 0.4125430	total: 501ms	remaining: 927ms
351:	learn: 0.4118229	total: 503ms	remaining: 925ms
352:	learn: 0.4105822	total: 504ms	remaining: 923ms
353:	learn: 0.4093256	total: 506ms	remaining: 923ms
354:	learn: 0.4080001	total: 507ms	remaining: 921ms
355:	learn: 0.4076102	total: 508ms	remaining: 919ms
356:	learn: 0.4066099	total: 509ms	remaining: 918ms
357:	learn: 0.4062934	total: 511ms	remaining: 916ms
358:	learn: 0.4043176	total: 512ms	remaining: 914ms
359:	learn: 0.4040824	total: 513ms	remaining: 912ms
360:	learn: 0.4037249	total: 514ms	remaining: 910ms
361:	learn: 0.4025680	total: 516ms	remaining: 909ms
362:	learn: 0.4021614	total: 517ms	remaining: 907ms
363:	learn: 0.4017212	total: 518ms	remaining: 905ms
364:	learn: 0.4001038	total: 519ms	remaining: 903ms
365:	learn: 0.3998362	total: 520ms	remaining: 901ms
366:	learn: 0.3983458	total: 522ms	remaining: 900ms
367:	learn: 0.3973931	total: 523ms	remaining: 899ms
368:	learn: 0.3969791	total: 525ms	remaining: 897ms
369:	learn: 0.3966061	total: 526ms	remaining: 895ms
370:	learn: 0.3944664	total: 527ms	remaining: 894ms
371:	learn: 0.3924411	total: 528ms	remaining: 892ms
372:	learn: 0.3908620	total: 530ms	remaining: 890ms
373:	learn: 0.3897290	total: 531ms	remaining: 889ms
374:	learn: 0.3890739	total: 532ms	remaining: 887ms
375:	learn: 0.3866529	total: 533ms	remaining: 885ms
376:	learn: 0.3857311	total: 535ms	remaining: 883ms
377:	learn: 0.3853949	total: 536ms	remaining: 882ms
378:	learn: 0.3838933	total: 538ms	remaining: 882ms
379:	learn: 0.3822250	total: 539ms	remaining: 880ms
380:	learn: 0.3816487	total: 541ms	remaining: 878ms

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fitting SVR for C2X-Complex_rhown_1x1_depth_lt_1
Fitting KNN for C2X-Complex_rhown_1x1_depth_lt_1
Fitting LR for C2X-Complex_rhown_1x1_depth_lt_1
Fitting RF for C2X-Complex_rhown_1x1_depth_lt_1
Fitting CAT for C2X-Complex_rhown_1x1_depth_lt_1
Learning rate set to 0.033272
0:	learn: 3.4215448	total: 4.16ms	remaining: 4.15s
1:	learn: 3.3716334	total: 5.36ms	remaining: 2.67s
2:	learn: 3.3160012	total: 6.52ms	remaining: 2.17s
3:	learn: 3.2682688	total: 7.69ms	remaining: 1.91s
4:	learn: 3.2207984	total: 8.87ms	remaining: 1.76s
5:	learn: 3.1710136	total: 10.5ms	remaining: 1.73s
6:	learn: 3.1275776	total: 11.8ms	remaining: 1.68s
7:	learn: 3.0808336	total: 13ms	remaining: 1.61s
8:	learn: 3.0371486	total: 14.2ms	remaining: 1.57s
9:	learn: 2.9944682	total: 15.5ms	remaining: 1.54s
10:	learn: 2.9479102	total: 16.7ms	remaining: 1.5s
11:	learn: 2.9100279	total: 17.8ms	remaining: 1.47s
12:	learn: 2.8635522	total: 19ms	remaining: 1.44s
13:	learn: 2.8304730	total: 20.1ms	remaining: 1.42s
14:	learn: 2.7923043	total: 21.3ms	remaining: 1.4s
15:	learn: 2.7502420	total: 22.5ms	remaining: 1.38s
16:	learn: 2.7146382	total: 23.7ms	remaining: 1.37s
17:	learn: 2.6663844	total: 25.3ms	remaining: 1.38s
18:	learn: 2.6319615	total: 26.7ms	remaining: 1.38s
19:	learn: 2.5960945	total: 27.9ms	remaining: 1.37s
20:	learn: 2.5629471	total: 29.4ms	remaining: 1.37s
21:	learn: 2.5349118	total: 30.6ms	remaining: 1.36s
22:	learn: 2.5003429	total: 32ms	remaining: 1.36s
23:	learn: 2.4719504	total: 33.1ms	remaining: 1.35s
24:	learn: 2.4414756	total: 34.3ms	remaining: 1.34s
25:	learn: 2.4151981	total: 35.5ms	remaining: 1.33s
26:	learn: 2.3878007	total: 36.7ms	remaining: 1.32s
27:	learn: 2.3582058	total: 37.8ms	remaining: 1.31s
28:	learn: 2.3247925	total: 39ms	remaining: 1.31s
29:	learn: 2.2922180	total: 40.7ms	remaining: 1.31s
30:	learn: 2.2702538	total: 42ms	remaining: 1.31s
31:	learn: 2.2381541	total: 43.4ms	remaining: 1.31s
32:	learn: 2.2051647	total: 44.6ms	remaining: 1.31s
33:	learn: 2.1810538	total: 45.8ms	remaining: 1.3s
34:	learn: 2.1549609	total: 47.1ms	remaining: 1.3s
35:	learn: 2.1297723	total: 48.3ms	remaining: 1.29s
36:	learn: 2.1133945	total: 49.5ms	remaining: 1.29s
37:	learn: 2.0896194	total: 50.7ms	remaining: 1.28s
38:	learn: 2.0657548	total: 51.9ms	remaining: 1.28s
39:	learn: 2.0459517	total: 53ms	remaining: 1.27s
40:	learn: 2.0245306	total: 54.4ms	remaining: 1.27s
41:	learn: 2.0030414	total: 55.7ms	remaining: 1.27s
42:	learn: 1.9888839	total: 57.1ms	remaining: 1.27s
43:	learn: 1.9649073	total: 58.5ms	remaining: 1.27s
44:	learn: 1.9420731	total: 59.7ms	remaining: 1.27s
45:	learn: 1.9223787	total: 60.9ms	remaining: 1.26s
46:	learn: 1.9097366	total: 62.1ms	remaining: 1.26s
47:	learn: 1.8915772	total: 63.5ms	remaining: 1.26s
48:	learn: 1.8690535	total: 64.7ms	remaining: 1.25s
49:	learn: 1.8470241	total: 65.8ms	remaining: 1.25s
50:	learn: 1.8206210	total: 66.9ms	remaining: 1.24s
51:	learn: 1.8035474	total: 68ms	remaining: 1.24s
52:	learn: 1.7870965	total: 69.1ms	remaining: 1.24s
53:	learn: 1.7727085	total: 70.3ms	remaining: 1.23s
54:	learn: 1.7554988	total: 71.4ms	remaining: 1.23s
55:	learn: 1.7343189	total: 73.4ms	remaining: 1.24s
56:	learn: 1.7183774	total: 75ms	remaining: 1.24s
57:	learn: 1.7040780	total: 76.5ms	remaining: 1.24s
58:	learn: 1.6839556	total: 77.9ms	remaining: 1.24s
59:	learn: 1.6621154	total: 79.4ms	remaining: 1.24s
60:	learn: 1.6514488	total: 80.7ms	remaining: 1.24s
61:	learn: 1.6464102	total: 82.1ms	remaining: 1.24s
62:	learn: 1.6352480	total: 83.3ms	remaining: 1.24s
63:	learn: 1.6249101	total: 84.4ms	remaining: 1.23s
64:	learn: 1.6113458	total: 85.6ms	remaining: 1.23s
65:	learn: 1.5988213	total: 86.7ms	remaining: 1.23s
66:	learn: 1.5895474	total: 88ms	remaining: 1.23s
67:	learn: 1.5717723	total: 89.4ms	remaining: 1.22s
68:	learn: 1.5557520	total: 90.7ms	remaining: 1.22s
69:	learn: 1.5378136	total: 92.1ms	remaining: 1.22s
70:	learn: 1.5234634	total: 93.4ms	remaining: 1.22s
71:	learn: 1.5111358	total: 94.9ms	remaining: 1.22s
72:	learn: 1.4976949	total: 96.1ms	remaining: 1.22s
73:	learn: 1.4852641	total: 97.3ms	remaining: 1.22s
74:	learn: 1.4801988	total: 98.6ms	remaining: 1.22s
75:	learn: 1.4627704	total: 99.9ms	remaining: 1.21s
76:	learn: 1.4595099	total: 101ms	remaining: 1.21s
77:	learn: 1.4504332	total: 102ms	remaining: 1.21s
78:	learn: 1.4438361	total: 104ms	remaining: 1.21s
79:	learn: 1.4319739	total: 105ms	remaining: 1.21s
80:	learn: 1.4195985	total: 106ms	remaining: 1.21s
81:	learn: 1.4069400	total: 108ms	remaining: 1.21s
82:	learn: 1.3983750	total: 109ms	remaining: 1.2s
83:	learn: 1.3859575	total: 110ms	remaining: 1.2s
84:	learn: 1.3814827	total: 111ms	remaining: 1.2s
85:	learn: 1.3758896	total: 113ms	remaining: 1.2s
86:	learn: 1.3632887	total: 114ms	remaining: 1.2s
87:	learn: 1.3556328	total: 115ms	remaining: 1.19s
88:	learn: 1.3444704	total: 117ms	remaining: 1.19s
89:	learn: 1.3370971	total: 118ms	remaining: 1.19s
90:	learn: 1.3311192	total: 119ms	remaining: 1.19s
91:	learn: 1.3213152	total: 121ms	remaining: 1.19s
92:	learn: 1.3156768	total: 122ms	remaining: 1.19s
93:	learn: 1.3101115	total: 123ms	remaining: 1.19s
94:	learn: 1.3021572	total: 124ms	remaining: 1.19s
95:	learn: 1.2920429	total: 126ms	remaining: 1.18s
96:	learn: 1.2807472	total: 127ms	remaining: 1.18s
97:	learn: 1.2733638	total: 128ms	remaining: 1.18s
98:	learn: 1.2642374	total: 129ms	remaining: 1.18s
99:	learn: 1.2555218	total: 131ms	remaining: 1.18s
100:	learn: 1.2503884	total: 132ms	remaining: 1.17s
101:	learn: 1.2387691	total: 133ms	remaining: 1.17s
102:	learn: 1.2350732	total: 135ms	remaining: 1.17s
103:	learn: 1.2256927	total: 136ms	remaining: 1.17s
104:	learn: 1.2148325	total: 137ms	remaining: 1.17s
105:	learn: 1.2096905	total: 139ms	remaining: 1.17s
106:	learn: 1.2031849	total: 140ms	remaining: 1.17s
107:	learn: 1.1973662	total: 141ms	remaining: 1.17s
108:	learn: 1.1910034	total: 142ms	remaining: 1.16s
109:	learn: 1.1805343	total: 144ms	remaining: 1.16s
110:	learn: 1.1710098	total: 146ms	remaining: 1.17s
111:	learn: 1.1641337	total: 147ms	remaining: 1.17s
112:	learn: 1.1525170	total: 149ms	remaining: 1.17s
113:	learn: 1.1447278	total: 150ms	remaining: 1.17s
114:	learn: 1.1375513	total: 152ms	remaining: 1.17s
115:	learn: 1.1333039	total: 152ms	remaining: 1.16s
116:	learn: 1.1260302	total: 154ms	remaining: 1.16s
117:	learn: 1.1163956	total: 155ms	remaining: 1.16s
118:	learn: 1.1125473	total: 156ms	remaining: 1.16s
119:	learn: 1.1092224	total: 158ms	remaining: 1.16s
120:	learn: 1.1020390	total: 159ms	remaining: 1.16s
121:	learn: 1.0940422	total: 160ms	remaining: 1.15s
122:	learn: 1.0854675	total: 162ms	remaining: 1.15s
123:	learn: 1.0770395	total: 163ms	remaining: 1.15s
124:	learn: 1.0698524	total: 165ms	remaining: 1.15s
125:	learn: 1.0671557	total: 166ms	remaining: 1.15s
126:	learn: 1.0625275	total: 167ms	remaining: 1.15s
127:	learn: 1.0531163	total: 168ms	remaining: 1.15s
128:	learn: 1.0462529	total: 171ms	remaining: 1.15s
129:	learn: 1.0419402	total: 172ms	remaining: 1.15s
130:	learn: 1.0402324	total: 173ms	remaining: 1.15s
131:	learn: 1.0328497	total: 174ms	remaining: 1.15s
132:	learn: 1.0307797	total: 176ms	remaining: 1.14s
133:	learn: 1.0232804	total: 178ms	remaining: 1.15s
134:	learn: 1.0139662	total: 180ms	remaining: 1.15s
135:	learn: 1.0102024	total: 181ms	remaining: 1.15s
136:	learn: 1.0044035	total: 183ms	remaining: 1.15s
137:	learn: 0.9959391	total: 184ms	remaining: 1.15s
138:	learn: 0.9931264	total: 185ms	remaining: 1.15s
139:	learn: 0.9879650	total: 187ms	remaining: 1.15s
140:	learn: 0.9809949	total: 188ms	remaining: 1.15s
141:	learn: 0.9778585	total: 189ms	remaining: 1.14s
142:	learn: 0.9699369	total: 191ms	remaining: 1.14s
143:	learn: 0.9640643	total: 192ms	remaining: 1.14s
144:	learn: 0.9617024	total: 194ms	remaining: 1.14s
145:	learn: 0.9556601	total: 195ms	remaining: 1.14s
146:	learn: 0.9468892	total: 196ms	remaining: 1.14s
147:	learn: 0.9451488	total: 198ms	remaining: 1.14s
148:	learn: 0.9420642	total: 200ms	remaining: 1.14s
149:	learn: 0.9370022	total: 201ms	remaining: 1.14s
150:	learn: 0.9309814	total: 202ms	remaining: 1.14s
151:	learn: 0.9259158	total: 204ms	remaining: 1.14s
152:	learn: 0.9215378	total: 205ms	remaining: 1.13s
153:	learn: 0.9198165	total: 206ms	remaining: 1.13s
154:	learn: 0.9146459	total: 208ms	remaining: 1.13s
155:	learn: 0.9121311	total: 209ms	remaining: 1.13s
156:	learn: 0.9061713	total: 211ms	remaining: 1.13s
157:	learn: 0.9031601	total: 213ms	remaining: 1.13s
158:	learn: 0.8992845	total: 215ms	remaining: 1.14s
159:	learn: 0.8978415	total: 216ms	remaining: 1.14s
160:	learn: 0.8953079	total: 218ms	remaining: 1.13s
161:	learn: 0.8877776	total: 219ms	remaining: 1.13s
162:	learn: 0.8837376	total: 220ms	remaining: 1.13s
163:	learn: 0.8821665	total: 222ms	remaining: 1.13s
164:	learn: 0.8788674	total: 223ms	remaining: 1.13s
165:	learn: 0.8721239	total: 225ms	remaining: 1.13s
166:	learn: 0.8639896	total: 226ms	remaining: 1.13s
167:	learn: 0.8603924	total: 228ms	remaining: 1.13s
168:	learn: 0.8551165	total: 229ms	remaining: 1.13s
169:	learn: 0.8532882	total: 230ms	remaining: 1.12s
170:	learn: 0.8492214	total: 231ms	remaining: 1.12s
171:	learn: 0.8433249	total: 234ms	remaining: 1.13s
172:	learn: 0.8372653	total: 237ms	remaining: 1.13s
173:	learn: 0.8305672	total: 240ms	remaining: 1.14s
174:	learn: 0.8248550	total: 242ms	remaining: 1.14s
175:	learn: 0.8228974	total: 244ms	remaining: 1.14s
176:	learn: 0.8203400	total: 248ms	remaining: 1.15s
177:	learn: 0.8118894	total: 250ms	remaining: 1.15s
178:	learn: 0.8091313	total: 252ms	remaining: 1.16s
179:	learn: 0.8061893	total: 255ms	remaining: 1.16s
180:	learn: 0.8034533	total: 257ms	remaining: 1.16s
181:	learn: 0.7981772	total: 258ms	remaining: 1.16s
182:	learn: 0.7934301	total: 260ms	remaining: 1.16s
183:	learn: 0.7892601	total: 261ms	remaining: 1.16s
184:	learn: 0.7869616	total: 262ms	remaining: 1.15s
185:	learn: 0.7823611	total: 263ms	remaining: 1.15s
186:	learn: 0.7775642	total: 264ms	remaining: 1.15s
187:	learn: 0.7751158	total: 265ms	remaining: 1.15s
188:	learn: 0.7691573	total: 266ms	remaining: 1.14s
189:	learn: 0.7634359	total: 267ms	remaining: 1.14s
190:	learn: 0.7616186	total: 270ms	remaining: 1.14s
191:	learn: 0.7586964	total: 271ms	remaining: 1.14s
192:	learn: 0.7546957	total: 273ms	remaining: 1.14s
193:	learn: 0.7535137	total: 274ms	remaining: 1.14s
194:	learn: 0.7489712	total: 275ms	remaining: 1.13s
195:	learn: 0.7466622	total: 276ms	remaining: 1.13s
196:	learn: 0.7428585	total: 277ms	remaining: 1.13s
197:	learn: 0.7390994	total: 279ms	remaining: 1.13s
198:	learn: 0.7356752	total: 280ms	remaining: 1.13s
199:	learn: 0.7302331	total: 281ms	remaining: 1.12s
200:	learn: 0.7267641	total: 282ms	remaining: 1.12s
201:	learn: 0.7243544	total: 283ms	remaining: 1.12s
202:	learn: 0.7216742	total: 285ms	remaining: 1.12s
203:	learn: 0.7185255	total: 288ms	remaining: 1.12s
204:	learn: 0.7170168	total: 289ms	remaining: 1.12s
205:	learn: 0.7156227	total: 291ms	remaining: 1.12s
206:	learn: 0.7126931	total: 292ms	remaining: 1.12s
207:	learn: 0.7089376	total: 293ms	remaining: 1.11s
208:	learn: 0.7055269	total: 294ms	remaining: 1.11s
209:	learn: 0.6997462	total: 295ms	remaining: 1.11s
210:	learn: 0.6958726	total: 296ms	remaining: 1.11s
211:	learn: 0.6935039	total: 297ms	remaining: 1.1s
212:	learn: 0.6922360	total: 298ms	remaining: 1.1s
213:	learn: 0.6884259	total: 300ms	remaining: 1.1s
214:	learn: 0.6836373	total: 301ms	remaining: 1.1s
215:	learn: 0.6803729	total: 304ms	remaining: 1.1s
216:	learn: 0.6787625	total: 305ms	remaining: 1.1s
217:	learn: 0.6759237	total: 307ms	remaining: 1.1s
218:	learn: 0.6726963	total: 308ms	remaining: 1.1s
219:	learn: 0.6707552	total: 309ms	remaining: 1.1s
220:	learn: 0.6678214	total: 311ms	remaining: 1.09s
221:	learn: 0.6658664	total: 312ms	remaining: 1.09s
222:	learn: 0.6644054	total: 313ms	remaining: 1.09s
223:	learn: 0.6600506	total: 315ms	remaining: 1.09s
224:	learn: 0.6575122	total: 316ms	remaining: 1.09s
225:	learn: 0.6525010	total: 318ms	remaining: 1.09s
226:	learn: 0.6496201	total: 319ms	remaining: 1.08s
227:	learn: 0.6452067	total: 320ms	remaining: 1.08s
228:	learn: 0.6428608	total: 321ms	remaining: 1.08s
229:	learn: 0.6408957	total: 323ms	remaining: 1.08s
230:	learn: 0.6389220	total: 324ms	remaining: 1.08s
231:	learn: 0.6359137	total: 325ms	remaining: 1.08s
232:	learn: 0.6316018	total: 326ms	remaining: 1.07s
233:	learn: 0.6285631	total: 328ms	remaining: 1.07s
234:	learn: 0.6275591	total: 329ms	remaining: 1.07s
235:	learn: 0.6249386	total: 330ms	remaining: 1.07s
236:	learn: 0.6236265	total: 333ms	remaining: 1.07s
237:	learn: 0.6193424	total: 334ms	remaining: 1.07s
238:	learn: 0.6181754	total: 336ms	remaining: 1.07s
239:	learn: 0.6150485	total: 337ms	remaining: 1.07s
240:	learn: 0.6136541	total: 338ms	remaining: 1.06s
241:	learn: 0.6102668	total: 339ms	remaining: 1.06s
242:	learn: 0.6071647	total: 340ms	remaining: 1.06s
243:	learn: 0.6040594	total: 341ms	remaining: 1.06s
244:	learn: 0.6013853	total: 343ms	remaining: 1.05s
245:	learn: 0.6000484	total: 344ms	remaining: 1.05s
246:	learn: 0.5981877	total: 346ms	remaining: 1.05s
247:	learn: 0.5956794	total: 347ms	remaining: 1.05s
248:	learn: 0.5937680	total: 348ms	remaining: 1.05s
249:	learn: 0.5906839	total: 350ms	remaining: 1.05s
250:	learn: 0.5877195	total: 351ms	remaining: 1.05s
251:	learn: 0.5846846	total: 352ms	remaining: 1.04s
252:	learn: 0.5827756	total: 353ms	remaining: 1.04s
253:	learn: 0.5800006	total: 355ms	remaining: 1.04s
254:	learn: 0.5790350	total: 356ms	remaining: 1.04s
255:	learn: 0.5761797	total: 357ms	remaining: 1.04s
256:	learn: 0.5749904	total: 358ms	remaining: 1.03s
257:	learn: 0.5721573	total: 360ms	remaining: 1.04s
258:	learn: 0.5697869	total: 363ms	remaining: 1.04s
259:	learn: 0.5672035	total: 365ms	remaining: 1.04s
260:	learn: 0.5648943	total: 366ms	remaining: 1.04s
261:	learn: 0.5619413	total: 367ms	remaining: 1.03s
262:	learn: 0.5602451	total: 369ms	remaining: 1.03s
263:	learn: 0.5575608	total: 370ms	remaining: 1.03s
264:	learn: 0.5546219	total: 372ms	remaining: 1.03s
265:	learn: 0.5524006	total: 373ms	remaining: 1.03s
266:	learn: 0.5493666	total: 377ms	remaining: 1.03s
267:	learn: 0.5468149	total: 378ms	remaining: 1.03s
268:	learn: 0.5457436	total: 380ms	remaining: 1.03s
269:	learn: 0.5434040	total: 381ms	remaining: 1.03s
270:	learn: 0.5411200	total: 382ms	remaining: 1.03s
271:	learn: 0.5390251	total: 384ms	remaining: 1.03s
272:	learn: 0.5381579	total: 385ms	remaining: 1.02s
273:	learn: 0.5356528	total: 386ms	remaining: 1.02s
274:	learn: 0.5323292	total: 387ms	remaining: 1.02s
275:	learn: 0.5301367	total: 389ms	remaining: 1.02s
276:	learn: 0.5292459	total: 390ms	remaining: 1.02s
277:	learn: 0.5284293	total: 392ms	remaining: 1.02s
278:	learn: 0.5275861	total: 393ms	remaining: 1.02s
279:	learn: 0.5258413	total: 395ms	remaining: 1.01s
280:	learn: 0.5242890	total: 396ms	remaining: 1.01s
281:	learn: 0.5229458	total: 397ms	remaining: 1.01s
282:	learn: 0.5214574	total: 399ms	remaining: 1.01s
283:	learn: 0.5207126	total: 400ms	remaining: 1.01s
284:	learn: 0.5185315	total: 401ms	remaining: 1s
285:	learn: 0.5178088	total: 402ms	remaining: 1s
286:	learn: 0.5157458	total: 404ms	remaining: 1s
287:	learn: 0.5142547	total: 405ms	remaining: 1s
288:	learn: 0.5120121	total: 407ms	remaining: 1s
289:	learn: 0.5113486	total: 408ms	remaining: 999ms
290:	learn: 0.5101235	total: 409ms	remaining: 997ms
291:	learn: 0.5073167	total: 411ms	remaining: 996ms
292:	learn: 0.5063408	total: 412ms	remaining: 994ms
293:	learn: 0.5056758	total: 413ms	remaining: 992ms
294:	learn: 0.5034564	total: 414ms	remaining: 990ms
295:	learn: 0.5003229	total: 415ms	remaining: 988ms
296:	learn: 0.4998767	total: 417ms	remaining: 986ms
297:	learn: 0.4978906	total: 419ms	remaining: 988ms
298:	learn: 0.4969985	total: 420ms	remaining: 986ms
299:	learn: 0.4941551	total: 422ms	remaining: 984ms
300:	learn: 0.4927852	total: 423ms	remaining: 982ms
301:	learn: 0.4910501	total: 424ms	remaining: 981ms
302:	learn: 0.4890857	total: 425ms	remaining: 979ms
303:	learn: 0.4873147	total: 427ms	remaining: 977ms
304:	learn: 0.4859669	total: 428ms	remaining: 974ms
305:	learn: 0.4839842	total: 429ms	remaining: 972ms
306:	learn: 0.4826325	total: 430ms	remaining: 970ms
307:	learn: 0.4820139	total: 431ms	remaining: 968ms
308:	learn: 0.4797136	total: 432ms	remaining: 966ms
309:	learn: 0.4769930	total: 434ms	remaining: 965ms
310:	learn: 0.4746903	total: 436ms	remaining: 966ms
311:	learn: 0.4729011	total: 438ms	remaining: 965ms
312:	learn: 0.4712338	total: 439ms	remaining: 963ms
313:	learn: 0.4687145	total: 440ms	remaining: 962ms
314:	learn: 0.4673633	total: 441ms	remaining: 960ms
315:	learn: 0.4653884	total: 442ms	remaining: 958ms
316:	learn: 0.4631895	total: 444ms	remaining: 956ms
317:	learn: 0.4626642	total: 445ms	remaining: 954ms
318:	learn: 0.4610565	total: 446ms	remaining: 952ms
319:	learn: 0.4594175	total: 447ms	remaining: 950ms
320:	learn: 0.4576101	total: 448ms	remaining: 948ms
321:	learn: 0.4571560	total: 450ms	remaining: 948ms
322:	learn: 0.4553478	total: 452ms	remaining: 947ms
323:	learn: 0.4535050	total: 453ms	remaining: 945ms
324:	learn: 0.4512397	total: 454ms	remaining: 943ms
325:	learn: 0.4489594	total: 455ms	remaining: 941ms
326:	learn: 0.4484916	total: 457ms	remaining: 940ms
327:	learn: 0.4462813	total: 458ms	remaining: 938ms
328:	learn: 0.4453855	total: 459ms	remaining: 936ms
329:	learn: 0.4438427	total: 460ms	remaining: 934ms
330:	learn: 0.4434513	total: 461ms	remaining: 932ms
331:	learn: 0.4422824	total: 462ms	remaining: 930ms
332:	learn: 0.4418473	total: 464ms	remaining: 928ms
333:	learn: 0.4413018	total: 465ms	remaining: 927ms
334:	learn: 0.4407709	total: 467ms	remaining: 927ms
335:	learn: 0.4386814	total: 469ms	remaining: 926ms
336:	learn: 0.4377462	total: 470ms	remaining: 925ms
337:	learn: 0.4364382	total: 471ms	remaining: 923ms
338:	learn: 0.4346147	total: 473ms	remaining: 921ms
339:	learn: 0.4324120	total: 474ms	remaining: 920ms
340:	learn: 0.4300626	total: 475ms	remaining: 918ms
341:	learn: 0.4295473	total: 476ms	remaining: 916ms
342:	learn: 0.4290732	total: 477ms	remaining: 914ms
343:	learn: 0.4287259	total: 478ms	remaining: 912ms
344:	learn: 0.4269354	total: 479ms	remaining: 910ms
345:	learn: 0.4264523	total: 480ms	remaining: 908ms
346:	learn: 0.4252315	total: 482ms	remaining: 908ms
347:	learn: 0.4235495	total: 484ms	remaining: 906ms
348:	learn: 0.4218926	total: 485ms	remaining: 904ms
349:	learn: 0.4214432	total: 486ms	remaining: 903ms
350:	learn: 0.4198377	total: 487ms	remaining: 901ms
351:	learn: 0.4184369	total: 488ms	remaining: 899ms
352:	learn: 0.4164956	total: 489ms	remaining: 897ms
353:	learn: 0.4144481	total: 491ms	remaining: 895ms
354:	learn: 0.4135262	total: 492ms	remaining: 893ms
355:	learn: 0.4120325	total: 493ms	remaining: 891ms
356:	learn: 0.4103053	total: 494ms	remaining: 889ms
357:	learn: 0.4088491	total: 495ms	remaining: 888ms
358:	learn: 0.4084312	total: 496ms	remaining: 886ms
359:	learn: 0.4079499	total: 498ms	remaining: 885ms
360:	learn: 0.4074353	total: 499ms	remaining: 884ms
361:	learn: 0.4071016	total: 500ms	remaining: 882ms
362:	learn: 0.4067578	total: 502ms	remaining: 880ms
363:	learn: 0.4060576	total: 503ms	remaining: 879ms
364:	learn: 0.4041816	total: 504ms	remaining: 877ms
365:	learn: 0.4034656	total: 505ms	remaining: 875ms
366:	learn: 0.4031608	total: 506ms	remaining: 873ms
367:	learn: 0.4030068	total: 507ms	remaining: 871ms
368:	learn: 0.4012657	total: 508ms	remaining: 869ms
369:	learn: 0.3994923	total: 510ms	remaining: 868ms
370:	learn: 0.3988299	total: 511ms	remaining: 866ms
371:	learn: 0.3966745	total: 512ms	remaining: 864ms
372:	learn: 0.3961220	total: 514ms	remaining: 864ms
373:	learn: 0.3948901	total: 515ms	remaining: 863ms
374:	learn: 0.3936136	total: 517ms	remaining: 861ms
375:	learn: 0.3921204	total: 518ms	remaining: 860ms
376:	learn: 0.3917167	total: 519ms	remaining: 858ms
377:	learn: 0.3901631	total: 520ms	remaining: 856ms
378:	learn: 0.3889584	total: 522ms	remaining: 855ms
379:	learn: 0.3885179	total: 523ms	remaining: 853ms
380:	learn: 0.3882368	total: 524ms	remaining: 851ms

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fitting SVR for C2RCC_rhow_3x3_depth_lt_1
Fitting KNN for C2RCC_rhow_3x3_depth_lt_1
Fitting LR for C2RCC_rhow_3x3_depth_lt_1
Fitting RF for C2RCC_rhow_3x3_depth_lt_1
Fitting CAT for C2RCC_rhow_3x3_depth_lt_1
Learning rate set to 0.033272
0:	learn: 3.4095254	total: 2.1ms	remaining: 2.1s
1:	learn: 3.3529602	total: 3.31ms	remaining: 1.65s
2:	learn: 3.2825294	total: 4.54ms	remaining: 1.51s
3:	learn: 3.2301713	total: 5.75ms	remaining: 1.43s
4:	learn: 3.1780429	total: 6.93ms	remaining: 1.38s
5:	learn: 3.1276365	total: 8.15ms	remaining: 1.35s
6:	learn: 3.0740426	total: 9.4ms	remaining: 1.33s
7:	learn: 3.0334143	total: 10.6ms	remaining: 1.31s
8:	learn: 2.9851218	total: 11.7ms	remaining: 1.29s
9:	learn: 2.9396686	total: 13.4ms	remaining: 1.33s
10:	learn: 2.8956050	total: 14.7ms	remaining: 1.32s
11:	learn: 2.8605329	total: 15.9ms	remaining: 1.31s
12:	learn: 2.8084468	total: 17.2ms	remaining: 1.3s
13:	learn: 2.7772949	total: 18.3ms	remaining: 1.29s
14:	learn: 2.7330837	total: 19.5ms	remaining: 1.28s
15:	learn: 2.6945430	total: 20.7ms	remaining: 1.27s
16:	learn: 2.6637524	total: 21.8ms	remaining: 1.26s
17:	learn: 2.6143669	total: 23.1ms	remaining: 1.26s
18:	learn: 2.5745262	total: 24.3ms	remaining: 1.25s
19:	learn: 2.5374736	total: 25.5ms	remaining: 1.25s
20:	learn: 2.4926015	total: 26.7ms	remaining: 1.24s
21:	learn: 2.4448256	total: 28.7ms	remaining: 1.27s
22:	learn: 2.4057598	total: 29.9ms	remaining: 1.27s
23:	learn: 2.3751315	total: 31.1ms	remaining: 1.27s
24:	learn: 2.3454044	total: 32.4ms	remaining: 1.26s
25:	learn: 2.3023148	total: 33.6ms	remaining: 1.26s
26:	learn: 2.2665857	total: 34.8ms	remaining: 1.25s
27:	learn: 2.2322042	total: 35.9ms	remaining: 1.25s
28:	learn: 2.1932532	total: 37.1ms	remaining: 1.24s
29:	learn: 2.1635111	total: 38.3ms	remaining: 1.24s
30:	learn: 2.1275872	total: 39.4ms	remaining: 1.23s
31:	learn: 2.0973575	total: 40.5ms	remaining: 1.23s
32:	learn: 2.0688696	total: 41.7ms	remaining: 1.22s
33:	learn: 2.0416838	total: 42.9ms	remaining: 1.22s
34:	learn: 2.0205765	total: 44.7ms	remaining: 1.23s
35:	learn: 1.9965338	total: 45.9ms	remaining: 1.23s
36:	learn: 1.9705625	total: 47.1ms	remaining: 1.23s
37:	learn: 1.9480485	total: 48.4ms	remaining: 1.23s
38:	learn: 1.9146526	total: 49.6ms	remaining: 1.22s
39:	learn: 1.8868697	total: 50.7ms	remaining: 1.22s
40:	learn: 1.8575372	total: 51.9ms	remaining: 1.21s
41:	learn: 1.8420720	total: 53.1ms	remaining: 1.21s
42:	learn: 1.8183227	total: 54.2ms	remaining: 1.21s
43:	learn: 1.7902943	total: 55.4ms	remaining: 1.2s
44:	learn: 1.7698067	total: 56.6ms	remaining: 1.2s
45:	learn: 1.7394501	total: 57.8ms	remaining: 1.2s
46:	learn: 1.7210678	total: 59ms	remaining: 1.2s
47:	learn: 1.7016045	total: 60.9ms	remaining: 1.21s
48:	learn: 1.6798907	total: 62.2ms	remaining: 1.21s
49:	learn: 1.6636306	total: 63.5ms	remaining: 1.21s
50:	learn: 1.6486716	total: 64.7ms	remaining: 1.2s
51:	learn: 1.6320019	total: 65.9ms	remaining: 1.2s
52:	learn: 1.6143993	total: 67.1ms	remaining: 1.2s
53:	learn: 1.5981643	total: 68.2ms	remaining: 1.19s
54:	learn: 1.5814316	total: 69.4ms	remaining: 1.19s
55:	learn: 1.5706866	total: 70.5ms	remaining: 1.19s
56:	learn: 1.5552834	total: 71.7ms	remaining: 1.19s
57:	learn: 1.5321352	total: 73.1ms	remaining: 1.19s
58:	learn: 1.5148111	total: 74.2ms	remaining: 1.18s
59:	learn: 1.4977751	total: 76.1ms	remaining: 1.19s
60:	learn: 1.4806358	total: 77.6ms	remaining: 1.19s
61:	learn: 1.4695078	total: 78.9ms	remaining: 1.19s
62:	learn: 1.4560323	total: 80.2ms	remaining: 1.19s
63:	learn: 1.4364721	total: 81.5ms	remaining: 1.19s
64:	learn: 1.4295344	total: 82.9ms	remaining: 1.19s
65:	learn: 1.4229278	total: 84.2ms	remaining: 1.19s
66:	learn: 1.4124584	total: 85.5ms	remaining: 1.19s
67:	learn: 1.3986263	total: 87.1ms	remaining: 1.19s
68:	learn: 1.3812764	total: 88.5ms	remaining: 1.19s
69:	learn: 1.3673172	total: 89.9ms	remaining: 1.19s
70:	learn: 1.3525306	total: 91.7ms	remaining: 1.2s
71:	learn: 1.3454593	total: 93.3ms	remaining: 1.2s
72:	learn: 1.3334272	total: 94.9ms	remaining: 1.2s
73:	learn: 1.3198433	total: 96.3ms	remaining: 1.21s
74:	learn: 1.3032824	total: 97.7ms	remaining: 1.2s
75:	learn: 1.2950052	total: 99.2ms	remaining: 1.21s
76:	learn: 1.2847132	total: 101ms	remaining: 1.21s
77:	learn: 1.2820528	total: 102ms	remaining: 1.2s
78:	learn: 1.2740287	total: 103ms	remaining: 1.2s
79:	learn: 1.2637144	total: 105ms	remaining: 1.2s
80:	learn: 1.2525064	total: 106ms	remaining: 1.21s
81:	learn: 1.2413385	total: 108ms	remaining: 1.21s
82:	learn: 1.2309499	total: 110ms	remaining: 1.21s
83:	learn: 1.2164133	total: 111ms	remaining: 1.21s
84:	learn: 1.2003863	total: 113ms	remaining: 1.21s
85:	learn: 1.1958317	total: 114ms	remaining: 1.21s
86:	learn: 1.1844965	total: 115ms	remaining: 1.21s
87:	learn: 1.1700476	total: 117ms	remaining: 1.21s
88:	learn: 1.1626930	total: 118ms	remaining: 1.21s
89:	learn: 1.1599767	total: 119ms	remaining: 1.21s
90:	learn: 1.1517525	total: 121ms	remaining: 1.21s
91:	learn: 1.1487976	total: 122ms	remaining: 1.21s
92:	learn: 1.1342486	total: 124ms	remaining: 1.21s
93:	learn: 1.1235551	total: 125ms	remaining: 1.21s
94:	learn: 1.1148206	total: 127ms	remaining: 1.21s
95:	learn: 1.1059544	total: 128ms	remaining: 1.21s
96:	learn: 1.1019626	total: 129ms	remaining: 1.21s
97:	learn: 1.0985428	total: 131ms	remaining: 1.2s
98:	learn: 1.0885240	total: 132ms	remaining: 1.2s
99:	learn: 1.0802115	total: 134ms	remaining: 1.2s
100:	learn: 1.0756594	total: 135ms	remaining: 1.2s
101:	learn: 1.0722232	total: 136ms	remaining: 1.2s
102:	learn: 1.0667924	total: 139ms	remaining: 1.21s
103:	learn: 1.0598639	total: 140ms	remaining: 1.21s
104:	learn: 1.0501698	total: 141ms	remaining: 1.21s
105:	learn: 1.0452731	total: 143ms	remaining: 1.2s
106:	learn: 1.0378524	total: 144ms	remaining: 1.2s
107:	learn: 1.0358099	total: 146ms	remaining: 1.2s
108:	learn: 1.0341731	total: 147ms	remaining: 1.2s
109:	learn: 1.0276991	total: 148ms	remaining: 1.2s
110:	learn: 1.0179626	total: 150ms	remaining: 1.2s
111:	learn: 1.0116281	total: 151ms	remaining: 1.2s
112:	learn: 1.0054262	total: 153ms	remaining: 1.2s
113:	learn: 0.9995506	total: 154ms	remaining: 1.2s
114:	learn: 0.9969463	total: 156ms	remaining: 1.2s
115:	learn: 0.9892002	total: 157ms	remaining: 1.2s
116:	learn: 0.9827715	total: 159ms	remaining: 1.2s
117:	learn: 0.9756167	total: 160ms	remaining: 1.2s
118:	learn: 0.9711220	total: 162ms	remaining: 1.2s
119:	learn: 0.9671096	total: 163ms	remaining: 1.2s
120:	learn: 0.9614519	total: 164ms	remaining: 1.19s
121:	learn: 0.9554446	total: 166ms	remaining: 1.19s
122:	learn: 0.9485406	total: 167ms	remaining: 1.19s
123:	learn: 0.9465524	total: 169ms	remaining: 1.19s
124:	learn: 0.9401303	total: 170ms	remaining: 1.19s
125:	learn: 0.9369092	total: 172ms	remaining: 1.19s
126:	learn: 0.9332332	total: 173ms	remaining: 1.19s
127:	learn: 0.9252605	total: 174ms	remaining: 1.19s
128:	learn: 0.9199660	total: 177ms	remaining: 1.19s
129:	learn: 0.9183302	total: 178ms	remaining: 1.19s
130:	learn: 0.9128500	total: 179ms	remaining: 1.19s
131:	learn: 0.9094584	total: 181ms	remaining: 1.19s
132:	learn: 0.9052792	total: 183ms	remaining: 1.19s
133:	learn: 0.9016545	total: 185ms	remaining: 1.2s
134:	learn: 0.8987975	total: 187ms	remaining: 1.2s
135:	learn: 0.8975729	total: 188ms	remaining: 1.2s
136:	learn: 0.8922342	total: 190ms	remaining: 1.19s
137:	learn: 0.8867976	total: 192ms	remaining: 1.2s
138:	learn: 0.8850402	total: 193ms	remaining: 1.2s
139:	learn: 0.8815143	total: 195ms	remaining: 1.2s
140:	learn: 0.8759290	total: 196ms	remaining: 1.19s
141:	learn: 0.8732717	total: 198ms	remaining: 1.19s
142:	learn: 0.8712455	total: 199ms	remaining: 1.19s
143:	learn: 0.8671054	total: 201ms	remaining: 1.2s
144:	learn: 0.8659587	total: 204ms	remaining: 1.2s
145:	learn: 0.8611348	total: 205ms	remaining: 1.2s
146:	learn: 0.8549163	total: 207ms	remaining: 1.2s
147:	learn: 0.8512100	total: 208ms	remaining: 1.2s
148:	learn: 0.8476342	total: 209ms	remaining: 1.19s
149:	learn: 0.8466181	total: 210ms	remaining: 1.19s
150:	learn: 0.8442014	total: 212ms	remaining: 1.19s
151:	learn: 0.8412861	total: 213ms	remaining: 1.19s
152:	learn: 0.8387145	total: 215ms	remaining: 1.19s
153:	learn: 0.8344886	total: 217ms	remaining: 1.19s
154:	learn: 0.8284140	total: 219ms	remaining: 1.19s
155:	learn: 0.8277990	total: 220ms	remaining: 1.19s
156:	learn: 0.8267893	total: 222ms	remaining: 1.19s
157:	learn: 0.8252205	total: 223ms	remaining: 1.19s
158:	learn: 0.8226146	total: 224ms	remaining: 1.19s
159:	learn: 0.8212365	total: 226ms	remaining: 1.19s
160:	learn: 0.8198870	total: 227ms	remaining: 1.18s
161:	learn: 0.8175292	total: 229ms	remaining: 1.18s
162:	learn: 0.8135256	total: 230ms	remaining: 1.18s
163:	learn: 0.8098983	total: 232ms	remaining: 1.18s
164:	learn: 0.8077429	total: 233ms	remaining: 1.18s
165:	learn: 0.8037477	total: 235ms	remaining: 1.18s
166:	learn: 0.8008961	total: 236ms	remaining: 1.18s
167:	learn: 0.7981782	total: 238ms	remaining: 1.18s
168:	learn: 0.7927624	total: 240ms	remaining: 1.18s
169:	learn: 0.7915612	total: 241ms	remaining: 1.18s
170:	learn: 0.7898635	total: 243ms	remaining: 1.18s
171:	learn: 0.7871236	total: 244ms	remaining: 1.18s
172:	learn: 0.7828985	total: 246ms	remaining: 1.18s
173:	learn: 0.7801605	total: 248ms	remaining: 1.18s
174:	learn: 0.7784418	total: 250ms	remaining: 1.18s
175:	learn: 0.7756288	total: 251ms	remaining: 1.18s
176:	learn: 0.7730750	total: 253ms	remaining: 1.18s
177:	learn: 0.7716819	total: 255ms	remaining: 1.18s
178:	learn: 0.7709062	total: 256ms	remaining: 1.18s
179:	learn: 0.7697992	total: 258ms	remaining: 1.17s
180:	learn: 0.7645787	total: 259ms	remaining: 1.17s
181:	learn: 0.7624894	total: 261ms	remaining: 1.17s
182:	learn: 0.7610719	total: 263ms	remaining: 1.17s
183:	learn: 0.7564671	total: 264ms	remaining: 1.17s
184:	learn: 0.7555616	total: 266ms	remaining: 1.17s
185:	learn: 0.7518350	total: 267ms	remaining: 1.17s
186:	learn: 0.7505409	total: 269ms	remaining: 1.17s
187:	learn: 0.7484562	total: 270ms	remaining: 1.17s
188:	learn: 0.7479133	total: 271ms	remaining: 1.16s
189:	learn: 0.7441653	total: 272ms	remaining: 1.16s
190:	learn: 0.7420614	total: 274ms	remaining: 1.16s
191:	learn: 0.7390629	total: 275ms	remaining: 1.16s
192:	learn: 0.7358721	total: 276ms	remaining: 1.16s
193:	learn: 0.7348688	total: 280ms	remaining: 1.16s
194:	learn: 0.7342086	total: 283ms	remaining: 1.17s
195:	learn: 0.7321748	total: 286ms	remaining: 1.17s
196:	learn: 0.7300729	total: 288ms	remaining: 1.18s
197:	learn: 0.7291082	total: 292ms	remaining: 1.18s
198:	learn: 0.7252885	total: 294ms	remaining: 1.19s
199:	learn: 0.7234862	total: 296ms	remaining: 1.18s
200:	learn: 0.7200476	total: 297ms	remaining: 1.18s
201:	learn: 0.7194749	total: 298ms	remaining: 1.18s
202:	learn: 0.7178228	total: 300ms	remaining: 1.18s
203:	learn: 0.7169245	total: 301ms	remaining: 1.17s
204:	learn: 0.7155280	total: 302ms	remaining: 1.17s
205:	learn: 0.7140517	total: 303ms	remaining: 1.17s
206:	learn: 0.7117806	total: 304ms	remaining: 1.17s
207:	learn: 0.7068629	total: 306ms	remaining: 1.16s
208:	learn: 0.7052345	total: 307ms	remaining: 1.16s
209:	learn: 0.7035324	total: 309ms	remaining: 1.16s
210:	learn: 0.7029127	total: 310ms	remaining: 1.16s
211:	learn: 0.7015587	total: 312ms	remaining: 1.16s
212:	learn: 0.6991623	total: 313ms	remaining: 1.16s
213:	learn: 0.6975723	total: 314ms	remaining: 1.15s
214:	learn: 0.6959424	total: 315ms	remaining: 1.15s
215:	learn: 0.6947980	total: 316ms	remaining: 1.15s
216:	learn: 0.6919602	total: 318ms	remaining: 1.15s
217:	learn: 0.6896598	total: 319ms	remaining: 1.14s
218:	learn: 0.6875416	total: 320ms	remaining: 1.14s
219:	learn: 0.6846922	total: 321ms	remaining: 1.14s
220:	learn: 0.6824867	total: 322ms	remaining: 1.14s
221:	learn: 0.6819753	total: 324ms	remaining: 1.13s
222:	learn: 0.6812959	total: 325ms	remaining: 1.13s
223:	learn: 0.6788847	total: 326ms	remaining: 1.13s
224:	learn: 0.6776420	total: 328ms	remaining: 1.13s
225:	learn: 0.6760248	total: 329ms	remaining: 1.13s
226:	learn: 0.6745760	total: 330ms	remaining: 1.12s
227:	learn: 0.6740482	total: 331ms	remaining: 1.12s
228:	learn: 0.6723818	total: 332ms	remaining: 1.12s
229:	learn: 0.6713730	total: 334ms	remaining: 1.12s
230:	learn: 0.6698399	total: 335ms	remaining: 1.11s
231:	learn: 0.6691565	total: 336ms	remaining: 1.11s
232:	learn: 0.6685055	total: 337ms	remaining: 1.11s
233:	learn: 0.6670357	total: 338ms	remaining: 1.11s
234:	learn: 0.6634492	total: 340ms	remaining: 1.11s
235:	learn: 0.6618401	total: 342ms	remaining: 1.11s
236:	learn: 0.6612509	total: 343ms	remaining: 1.1s
237:	learn: 0.6594302	total: 344ms	remaining: 1.1s
238:	learn: 0.6589783	total: 345ms	remaining: 1.1s
239:	learn: 0.6574881	total: 347ms	remaining: 1.1s
240:	learn: 0.6553599	total: 348ms	remaining: 1.09s
241:	learn: 0.6542094	total: 349ms	remaining: 1.09s
242:	learn: 0.6499920	total: 350ms	remaining: 1.09s
243:	learn: 0.6487189	total: 351ms	remaining: 1.09s
244:	learn: 0.6475182	total: 352ms	remaining: 1.09s
245:	learn: 0.6459767	total: 354ms	remaining: 1.08s
246:	learn: 0.6449966	total: 355ms	remaining: 1.08s
247:	learn: 0.6426741	total: 357ms	remaining: 1.08s
248:	learn: 0.6404962	total: 359ms	remaining: 1.08s
249:	learn: 0.6371348	total: 360ms	remaining: 1.08s
250:	learn: 0.6349368	total: 361ms	remaining: 1.08s
251:	learn: 0.6330636	total: 362ms	remaining: 1.07s
252:	learn: 0.6301563	total: 363ms	remaining: 1.07s
253:	learn: 0.6290998	total: 365ms	remaining: 1.07s
254:	learn: 0.6280191	total: 366ms	remaining: 1.07s
255:	learn: 0.6261159	total: 367ms	remaining: 1.07s
256:	learn: 0.6256065	total: 369ms	remaining: 1.06s
257:	learn: 0.6252722	total: 371ms	remaining: 1.06s
258:	learn: 0.6220249	total: 374ms	remaining: 1.07s
259:	learn: 0.6209613	total: 377ms	remaining: 1.07s
260:	learn: 0.6206331	total: 380ms	remaining: 1.08s
261:	learn: 0.6194662	total: 384ms	remaining: 1.08s
262:	learn: 0.6164909	total: 386ms	remaining: 1.08s
263:	learn: 0.6128772	total: 389ms	remaining: 1.08s
264:	learn: 0.6118180	total: 392ms	remaining: 1.09s
265:	learn: 0.6101650	total: 395ms	remaining: 1.09s
266:	learn: 0.6073430	total: 397ms	remaining: 1.09s
267:	learn: 0.6040780	total: 400ms	remaining: 1.09s
268:	learn: 0.6028876	total: 402ms	remaining: 1.09s
269:	learn: 0.6019690	total: 405ms	remaining: 1.09s
270:	learn: 0.6006874	total: 408ms	remaining: 1.1s
271:	learn: 0.5994615	total: 410ms	remaining: 1.1s
272:	learn: 0.5967280	total: 413ms	remaining: 1.1s
273:	learn: 0.5946807	total: 415ms	remaining: 1.1s
274:	learn: 0.5936918	total: 418ms	remaining: 1.1s
275:	learn: 0.5906216	total: 420ms	remaining: 1.1s
276:	learn: 0.5874177	total: 423ms	remaining: 1.1s
277:	learn: 0.5847041	total: 424ms	remaining: 1.1s
278:	learn: 0.5838617	total: 425ms	remaining: 1.1s
279:	learn: 0.5809738	total: 426ms	remaining: 1.1s
280:	learn: 0.5784826	total: 428ms	remaining: 1.09s
281:	learn: 0.5756921	total: 429ms	remaining: 1.09s
282:	learn: 0.5727406	total: 430ms	remaining: 1.09s
283:	learn: 0.5707143	total: 431ms	remaining: 1.09s
284:	learn: 0.5686478	total: 432ms	remaining: 1.08s
285:	learn: 0.5655428	total: 434ms	remaining: 1.08s
286:	learn: 0.5634720	total: 435ms	remaining: 1.08s
287:	learn: 0.5625614	total: 436ms	remaining: 1.08s
288:	learn: 0.5617214	total: 439ms	remaining: 1.08s
289:	learn: 0.5591745	total: 440ms	remaining: 1.08s
290:	learn: 0.5565598	total: 442ms	remaining: 1.07s
291:	learn: 0.5562611	total: 443ms	remaining: 1.07s
292:	learn: 0.5549526	total: 444ms	remaining: 1.07s
293:	learn: 0.5517905	total: 445ms	remaining: 1.07s
294:	learn: 0.5506937	total: 446ms	remaining: 1.07s
295:	learn: 0.5497528	total: 448ms	remaining: 1.06s
296:	learn: 0.5488436	total: 449ms	remaining: 1.06s
297:	learn: 0.5460092	total: 450ms	remaining: 1.06s
298:	learn: 0.5442426	total: 452ms	remaining: 1.06s
299:	learn: 0.5429864	total: 453ms	remaining: 1.06s
300:	learn: 0.5421922	total: 455ms	remaining: 1.06s
301:	learn: 0.5393889	total: 457ms	remaining: 1.05s
302:	learn: 0.5374360	total: 458ms	remaining: 1.05s
303:	learn: 0.5353391	total: 459ms	remaining: 1.05s
304:	learn: 0.5347146	total: 460ms	remaining: 1.05s
305:	learn: 0.5322286	total: 461ms	remaining: 1.05s
306:	learn: 0.5289799	total: 463ms	remaining: 1.04s
307:	learn: 0.5281686	total: 465ms	remaining: 1.04s
308:	learn: 0.5271752	total: 466ms	remaining: 1.04s
309:	learn: 0.5264795	total: 467ms	remaining: 1.04s
310:	learn: 0.5262388	total: 470ms	remaining: 1.04s
311:	learn: 0.5254641	total: 471ms	remaining: 1.04s
312:	learn: 0.5229636	total: 473ms	remaining: 1.04s
313:	learn: 0.5222371	total: 474ms	remaining: 1.04s
314:	learn: 0.5194713	total: 476ms	remaining: 1.03s
315:	learn: 0.5168604	total: 477ms	remaining: 1.03s
316:	learn: 0.5141922	total: 478ms	remaining: 1.03s
317:	learn: 0.5136764	total: 479ms	remaining: 1.03s
318:	learn: 0.5111861	total: 481ms	remaining: 1.03s
319:	learn: 0.5090459	total: 482ms	remaining: 1.02s
320:	learn: 0.5085188	total: 485ms	remaining: 1.02s
321:	learn: 0.5067921	total: 487ms	remaining: 1.02s
322:	learn: 0.5060960	total: 488ms	remaining: 1.02s
323:	learn: 0.5052148	total: 489ms	remaining: 1.02s
324:	learn: 0.5044812	total: 491ms	remaining: 1.02s
325:	learn: 0.5016502	total: 492ms	remaining: 1.02s
326:	learn: 0.4994182	total: 493ms	remaining: 1.01s
327:	learn: 0.4977585	total: 494ms	remaining: 1.01s
328:	learn: 0.4962194	total: 495ms	remaining: 1.01s
329:	learn: 0.4934005	total: 496ms	remaining: 1.01s
330:	learn: 0.4926043	total: 498ms	remaining: 1.01s
331:	learn: 0.4906442	total: 500ms	remaining: 1s
332:	learn: 0.4876359	total: 502ms	remaining: 1s
333:	learn: 0.4864639	total: 503ms	remaining: 1s
334:	learn: 0.4849195	total: 504ms	remaining: 1s
335:	learn: 0.4826435	total: 505ms	remaining: 999ms
336:	learn: 0.4804930	total: 507ms	remaining: 997ms
337:	learn: 0.4794774	total: 508ms	remaining: 994ms
338:	learn: 0.4780926	total: 509ms	remaining: 992ms
339:	learn: 0.4768965	total: 510ms	remaining: 990ms
340:	learn: 0.4746816	total: 511ms	remaining: 988ms
341:	learn: 0.4730473	total: 512ms	remaining: 986ms
342:	learn: 0.4705727	total: 514ms	remaining: 985ms
343:	learn: 0.4703572	total: 516ms	remaining: 984ms
344:	learn: 0.4691985	total: 518ms	remaining: 983ms
345:	learn: 0.4684513	total: 519ms	remaining: 981ms
346:	learn: 0.4670402	total: 520ms	remaining: 979ms
347:	learn: 0.4664639	total: 522ms	remaining: 978ms
348:	learn: 0.4650853	total: 523ms	remaining: 975ms
349:	learn: 0.4627784	total: 524ms	remaining: 974ms
350:	learn: 0.4600803	total: 525ms	remaining: 971ms
351:	learn: 0.4591364	total: 527ms	remaining: 969ms
352:	learn: 0.4568428	total: 528ms	remaining: 967ms
353:	learn: 0.4544526	total: 530ms	remaining: 966ms
354:	learn: 0.4538863	total: 531ms	remaining: 965ms
355:	learn: 0.4531444	total: 533ms	remaining: 965ms
356:	learn: 0.4510164	total: 535ms	remaining: 963ms
357:	learn: 0.4503507	total: 536ms	remaining: 961ms
358:	learn: 0.4495582	total: 537ms	remaining: 959ms
359:	learn: 0.4469930	total: 539ms	remaining: 958ms
360:	learn: 0.4460061	total: 540ms	remaining: 956ms
361:	learn: 0.4438943	total: 541ms	remaining: 954ms
362:	learn: 0.4429166	total: 542ms	remaining: 952ms
363:	learn: 0.4410031	total: 544ms	remaining: 950ms
364:	learn: 0.4403626	total: 546ms	remaining: 949ms
365:	learn: 0.4387491	total: 548ms	remaining: 949ms
366:	learn: 0.4372198	total: 550ms	remaining: 948ms
367:	learn: 0.4354326	total: 551ms	remaining: 947ms
368:	learn: 0.4337545	total: 552ms	remaining: 945ms
369:	learn: 0.4315007	total: 554ms	remaining: 943ms
370:	learn: 0.4297620	total: 555ms	remaining: 941ms
371:	learn: 0.4285416	total: 556ms	remaining: 939ms
372:	learn: 0.4283517	total: 557ms	remaining: 937ms
373:	learn: 0.4269172	total: 559ms	remaining: 935ms
374:	learn: 0.4257961	total: 560ms	remaining: 933ms
375:	learn: 0.4251073	total: 561ms	remaining: 932ms
376:	learn: 0.4234674	total: 563ms	remaining: 931ms
377:	learn: 0.4226140	total: 566ms	remaining: 931ms
378:	learn: 0.4212409	total: 569ms	remaining: 932ms
379:	learn: 0.4196772	total: 571ms	remaining: 932ms
380:	learn: 0.4183057	total: 574ms	remaining: 932ms
381:	learn: 0.4160018	total: 576ms	remaining: 932ms

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fitting SVR for TOA_5x5_depth_lt_1
Fitting KNN for TOA_5x5_depth_lt_1
Fitting LR for TOA_5x5_depth_lt_1
Fitting RF for TOA_5x5_depth_lt_1
Fitting CAT for TOA_5x5_depth_lt_1
Learning rate set to 0.033292
0:	learn: 3.7139214	total: 1.74ms	remaining: 1.74s
1:	learn: 3.6643628	total: 2.85ms	remaining: 1.42s
2:	learn: 3.6006528	total: 3.91ms	remaining: 1.3s
3:	learn: 3.5499114	total: 4.98ms	remaining: 1.24s
4:	learn: 3.4839437	total: 6.08ms	remaining: 1.21s
5:	learn: 3.4257150	total: 7.21ms	remaining: 1.19s
6:	learn: 3.3671876	total: 8.49ms	remaining: 1.2s
7:	learn: 3.3213571	total: 9.72ms	remaining: 1.21s
8:	learn: 3.2791244	total: 10.9ms	remaining: 1.2s
9:	learn: 3.2256604	total: 12ms	remaining: 1.19s
10:	learn: 3.1805125	total: 13.2ms	remaining: 1.19s
11:	learn: 3.1274639	total: 14.3ms	remaining: 1.18s
12:	learn: 3.0864180	total: 15.4ms	remaining: 1.17s
13:	learn: 3.0291593	total: 16.5ms	remaining: 1.16s
14:	learn: 2.9875266	total: 17.6ms	remaining: 1.16s
15:	learn: 2.9318790	total: 18.6ms	remaining: 1.15s
16:	learn: 2.8857557	total: 19.8ms	remaining: 1.14s
17:	learn: 2.8341173	total: 20.9ms	remaining: 1.14s
18:	learn: 2.7884470	total: 22ms	remaining: 1.14s
19:	learn: 2.7536227	total: 23.6ms	remaining: 1.15s
20:	learn: 2.7082622	total: 24.8ms	remaining: 1.16s
21:	learn: 2.6585559	total: 26.1ms	remaining: 1.16s
22:	learn: 2.6173828	total: 27.3ms	remaining: 1.16s
23:	learn: 2.5722483	total: 28.4ms	remaining: 1.16s
24:	learn: 2.5353164	total: 29.5ms	remaining: 1.15s
25:	learn: 2.5009306	total: 30.6ms	remaining: 1.15s
26:	learn: 2.4789229	total: 31.7ms	remaining: 1.14s
27:	learn: 2.4427175	total: 32.8ms	remaining: 1.14s
28:	learn: 2.4070203	total: 33.9ms	remaining: 1.13s
29:	learn: 2.3699436	total: 34.9ms	remaining: 1.13s
30:	learn: 2.3293590	total: 36ms	remaining: 1.13s
31:	learn: 2.2909553	total: 37.1ms	remaining: 1.12s
32:	learn: 2.2638922	total: 38.2ms	remaining: 1.12s
33:	learn: 2.2240501	total: 39.9ms	remaining: 1.13s
34:	learn: 2.1988482	total: 41.2ms	remaining: 1.14s
35:	learn: 2.1744124	total: 42.4ms	remaining: 1.13s
36:	learn: 2.1409184	total: 43.7ms	remaining: 1.14s
37:	learn: 2.1061051	total: 44.9ms	remaining: 1.14s
38:	learn: 2.0831641	total: 46.1ms	remaining: 1.14s
39:	learn: 2.0510894	total: 47.4ms	remaining: 1.14s
40:	learn: 2.0215564	total: 48.7ms	remaining: 1.14s
41:	learn: 1.9948196	total: 50ms	remaining: 1.14s
42:	learn: 1.9667131	total: 51.2ms	remaining: 1.14s
43:	learn: 1.9426324	total: 52.5ms	remaining: 1.14s
44:	learn: 1.9185946	total: 53.8ms	remaining: 1.14s
45:	learn: 1.8948609	total: 55.3ms	remaining: 1.15s
46:	learn: 1.8702585	total: 56.7ms	remaining: 1.15s
47:	learn: 1.8514120	total: 57.8ms	remaining: 1.15s
48:	learn: 1.8309582	total: 59ms	remaining: 1.14s
49:	learn: 1.8137825	total: 60.2ms	remaining: 1.14s
50:	learn: 1.7965657	total: 61.4ms	remaining: 1.14s
51:	learn: 1.7778361	total: 62.6ms	remaining: 1.14s
52:	learn: 1.7545136	total: 63.9ms	remaining: 1.14s
53:	learn: 1.7355640	total: 65ms	remaining: 1.14s
54:	learn: 1.7112190	total: 66.2ms	remaining: 1.14s
55:	learn: 1.6877442	total: 67.5ms	remaining: 1.14s
56:	learn: 1.6720073	total: 68.6ms	remaining: 1.13s
57:	learn: 1.6521567	total: 70.5ms	remaining: 1.15s
58:	learn: 1.6350050	total: 72ms	remaining: 1.15s
59:	learn: 1.6175261	total: 73.3ms	remaining: 1.15s
60:	learn: 1.5990926	total: 74.5ms	remaining: 1.15s
61:	learn: 1.5793479	total: 75.7ms	remaining: 1.15s
62:	learn: 1.5631723	total: 77.1ms	remaining: 1.15s
63:	learn: 1.5507386	total: 78.4ms	remaining: 1.15s
64:	learn: 1.5384731	total: 79.6ms	remaining: 1.14s
65:	learn: 1.5251134	total: 80.8ms	remaining: 1.14s
66:	learn: 1.5048860	total: 81.9ms	remaining: 1.14s
67:	learn: 1.4887413	total: 83.2ms	remaining: 1.14s
68:	learn: 1.4755019	total: 84.8ms	remaining: 1.14s
69:	learn: 1.4709286	total: 86.3ms	remaining: 1.15s
70:	learn: 1.4596226	total: 87.6ms	remaining: 1.15s
71:	learn: 1.4432289	total: 88.9ms	remaining: 1.15s
72:	learn: 1.4328420	total: 90.2ms	remaining: 1.14s
73:	learn: 1.4225770	total: 91.3ms	remaining: 1.14s
74:	learn: 1.4085321	total: 92.6ms	remaining: 1.14s
75:	learn: 1.3939063	total: 93.9ms	remaining: 1.14s
76:	learn: 1.3810903	total: 95.2ms	remaining: 1.14s
77:	learn: 1.3722737	total: 96.4ms	remaining: 1.14s
78:	learn: 1.3609951	total: 97.6ms	remaining: 1.14s
79:	learn: 1.3468532	total: 98.8ms	remaining: 1.14s
80:	learn: 1.3342632	total: 100ms	remaining: 1.14s
81:	learn: 1.3170134	total: 102ms	remaining: 1.14s
82:	learn: 1.3053332	total: 103ms	remaining: 1.14s
83:	learn: 1.2917013	total: 104ms	remaining: 1.14s
84:	learn: 1.2805279	total: 106ms	remaining: 1.14s
85:	learn: 1.2753519	total: 108ms	remaining: 1.14s
86:	learn: 1.2613495	total: 109ms	remaining: 1.14s
87:	learn: 1.2526558	total: 110ms	remaining: 1.14s
88:	learn: 1.2482706	total: 111ms	remaining: 1.14s
89:	learn: 1.2452974	total: 113ms	remaining: 1.14s
90:	learn: 1.2386063	total: 114ms	remaining: 1.14s
91:	learn: 1.2333764	total: 116ms	remaining: 1.14s
92:	learn: 1.2232535	total: 117ms	remaining: 1.14s
93:	learn: 1.2134670	total: 118ms	remaining: 1.14s
94:	learn: 1.2094880	total: 120ms	remaining: 1.14s
95:	learn: 1.2022414	total: 121ms	remaining: 1.14s
96:	learn: 1.1925552	total: 122ms	remaining: 1.14s
97:	learn: 1.1881640	total: 123ms	remaining: 1.14s
98:	learn: 1.1791457	total: 125ms	remaining: 1.14s
99:	learn: 1.1673783	total: 126ms	remaining: 1.14s
100:	learn: 1.1636113	total: 127ms	remaining: 1.13s
101:	learn: 1.1519502	total: 128ms	remaining: 1.13s
102:	learn: 1.1447622	total: 130ms	remaining: 1.13s
103:	learn: 1.1362620	total: 131ms	remaining: 1.13s
104:	learn: 1.1299836	total: 133ms	remaining: 1.13s
105:	learn: 1.1222032	total: 134ms	remaining: 1.13s
106:	learn: 1.1178119	total: 135ms	remaining: 1.13s
107:	learn: 1.1096648	total: 137ms	remaining: 1.13s
108:	learn: 1.1052511	total: 138ms	remaining: 1.13s
109:	learn: 1.0947816	total: 139ms	remaining: 1.13s
110:	learn: 1.0890400	total: 140ms	remaining: 1.12s
111:	learn: 1.0834580	total: 142ms	remaining: 1.12s
112:	learn: 1.0740554	total: 143ms	remaining: 1.12s
113:	learn: 1.0663919	total: 145ms	remaining: 1.13s
114:	learn: 1.0591858	total: 146ms	remaining: 1.13s
115:	learn: 1.0542273	total: 148ms	remaining: 1.12s
116:	learn: 1.0479692	total: 149ms	remaining: 1.12s
117:	learn: 1.0401755	total: 150ms	remaining: 1.12s
118:	learn: 1.0378990	total: 151ms	remaining: 1.12s
119:	learn: 1.0309655	total: 153ms	remaining: 1.12s
120:	learn: 1.0270218	total: 154ms	remaining: 1.12s
121:	learn: 1.0181855	total: 155ms	remaining: 1.11s
122:	learn: 1.0140215	total: 156ms	remaining: 1.11s
123:	learn: 1.0096080	total: 157ms	remaining: 1.11s
124:	learn: 1.0032153	total: 159ms	remaining: 1.11s
125:	learn: 0.9971888	total: 160ms	remaining: 1.11s
126:	learn: 0.9906164	total: 161ms	remaining: 1.11s
127:	learn: 0.9834352	total: 163ms	remaining: 1.11s
128:	learn: 0.9788448	total: 165ms	remaining: 1.11s
129:	learn: 0.9736019	total: 166ms	remaining: 1.11s
130:	learn: 0.9716184	total: 167ms	remaining: 1.11s
131:	learn: 0.9645294	total: 168ms	remaining: 1.1s
132:	learn: 0.9611183	total: 169ms	remaining: 1.1s
133:	learn: 0.9549950	total: 170ms	remaining: 1.1s
134:	learn: 0.9523510	total: 171ms	remaining: 1.1s
135:	learn: 0.9480521	total: 173ms	remaining: 1.1s
136:	learn: 0.9433575	total: 175ms	remaining: 1.1s
137:	learn: 0.9344588	total: 177ms	remaining: 1.11s
138:	learn: 0.9270343	total: 178ms	remaining: 1.1s
139:	learn: 0.9246068	total: 180ms	remaining: 1.1s
140:	learn: 0.9195453	total: 181ms	remaining: 1.1s
141:	learn: 0.9176341	total: 182ms	remaining: 1.1s
142:	learn: 0.9127266	total: 183ms	remaining: 1.1s
143:	learn: 0.9080308	total: 184ms	remaining: 1.09s
144:	learn: 0.9034173	total: 185ms	remaining: 1.09s
145:	learn: 0.8981788	total: 186ms	remaining: 1.09s
146:	learn: 0.8935229	total: 187ms	remaining: 1.09s
147:	learn: 0.8912130	total: 189ms	remaining: 1.09s
148:	learn: 0.8873354	total: 192ms	remaining: 1.09s
149:	learn: 0.8851168	total: 193ms	remaining: 1.1s
150:	learn: 0.8795861	total: 195ms	remaining: 1.09s
151:	learn: 0.8734749	total: 196ms	remaining: 1.09s
152:	learn: 0.8677465	total: 197ms	remaining: 1.09s
153:	learn: 0.8617534	total: 198ms	remaining: 1.09s
154:	learn: 0.8577950	total: 200ms	remaining: 1.09s
155:	learn: 0.8518839	total: 201ms	remaining: 1.09s
156:	learn: 0.8458892	total: 203ms	remaining: 1.09s
157:	learn: 0.8389917	total: 204ms	remaining: 1.09s
158:	learn: 0.8369195	total: 205ms	remaining: 1.09s
159:	learn: 0.8318443	total: 208ms	remaining: 1.09s
160:	learn: 0.8273784	total: 209ms	remaining: 1.09s
161:	learn: 0.8234980	total: 211ms	remaining: 1.09s
162:	learn: 0.8188818	total: 212ms	remaining: 1.09s
163:	learn: 0.8149210	total: 213ms	remaining: 1.08s
164:	learn: 0.8127829	total: 214ms	remaining: 1.08s
165:	learn: 0.8087339	total: 215ms	remaining: 1.08s
166:	learn: 0.8033860	total: 217ms	remaining: 1.08s
167:	learn: 0.7989757	total: 218ms	remaining: 1.08s
168:	learn: 0.7969947	total: 219ms	remaining: 1.07s
169:	learn: 0.7908915	total: 220ms	remaining: 1.07s
170:	learn: 0.7874121	total: 222ms	remaining: 1.07s
171:	learn: 0.7826624	total: 224ms	remaining: 1.08s
172:	learn: 0.7787872	total: 226ms	remaining: 1.08s
173:	learn: 0.7748325	total: 227ms	remaining: 1.08s
174:	learn: 0.7730273	total: 228ms	remaining: 1.07s
175:	learn: 0.7687145	total: 229ms	remaining: 1.07s
176:	learn: 0.7655454	total: 230ms	remaining: 1.07s
177:	learn: 0.7612877	total: 232ms	remaining: 1.07s
178:	learn: 0.7577690	total: 233ms	remaining: 1.07s
179:	learn: 0.7516500	total: 234ms	remaining: 1.06s
180:	learn: 0.7481540	total: 235ms	remaining: 1.06s
181:	learn: 0.7440184	total: 239ms	remaining: 1.07s
182:	learn: 0.7399011	total: 241ms	remaining: 1.08s
183:	learn: 0.7379104	total: 244ms	remaining: 1.08s
184:	learn: 0.7360000	total: 246ms	remaining: 1.08s
185:	learn: 0.7336573	total: 249ms	remaining: 1.09s
186:	learn: 0.7288704	total: 252ms	remaining: 1.09s
187:	learn: 0.7235928	total: 254ms	remaining: 1.1s
188:	learn: 0.7216551	total: 256ms	remaining: 1.1s
189:	learn: 0.7176206	total: 257ms	remaining: 1.1s
190:	learn: 0.7134624	total: 258ms	remaining: 1.09s
191:	learn: 0.7096819	total: 260ms	remaining: 1.09s
192:	learn: 0.7062610	total: 261ms	remaining: 1.09s
193:	learn: 0.7039092	total: 262ms	remaining: 1.09s
194:	learn: 0.7022349	total: 263ms	remaining: 1.08s
195:	learn: 0.6968246	total: 264ms	remaining: 1.08s
196:	learn: 0.6942768	total: 265ms	remaining: 1.08s
197:	learn: 0.6896971	total: 266ms	remaining: 1.08s
198:	learn: 0.6851464	total: 269ms	remaining: 1.08s
199:	learn: 0.6824991	total: 270ms	remaining: 1.08s
200:	learn: 0.6806362	total: 272ms	remaining: 1.08s
201:	learn: 0.6778841	total: 273ms	remaining: 1.08s
202:	learn: 0.6730417	total: 274ms	remaining: 1.08s
203:	learn: 0.6689714	total: 275ms	remaining: 1.07s
204:	learn: 0.6661105	total: 276ms	remaining: 1.07s
205:	learn: 0.6612653	total: 278ms	remaining: 1.07s
206:	learn: 0.6568578	total: 279ms	remaining: 1.07s
207:	learn: 0.6542285	total: 280ms	remaining: 1.06s
208:	learn: 0.6516979	total: 282ms	remaining: 1.06s
209:	learn: 0.6497055	total: 284ms	remaining: 1.07s
210:	learn: 0.6464807	total: 286ms	remaining: 1.07s
211:	learn: 0.6429388	total: 288ms	remaining: 1.07s
212:	learn: 0.6384918	total: 289ms	remaining: 1.07s
213:	learn: 0.6359741	total: 290ms	remaining: 1.06s
214:	learn: 0.6337185	total: 291ms	remaining: 1.06s
215:	learn: 0.6305831	total: 292ms	remaining: 1.06s
216:	learn: 0.6288806	total: 293ms	remaining: 1.06s
217:	learn: 0.6243914	total: 295ms	remaining: 1.06s
218:	learn: 0.6205815	total: 296ms	remaining: 1.05s
219:	learn: 0.6181910	total: 297ms	remaining: 1.05s
220:	learn: 0.6136871	total: 298ms	remaining: 1.05s
221:	learn: 0.6116921	total: 300ms	remaining: 1.05s
222:	learn: 0.6097310	total: 302ms	remaining: 1.05s
223:	learn: 0.6054022	total: 303ms	remaining: 1.05s
224:	learn: 0.6032463	total: 304ms	remaining: 1.05s
225:	learn: 0.6007105	total: 305ms	remaining: 1.05s
226:	learn: 0.5978779	total: 307ms	remaining: 1.04s
227:	learn: 0.5942599	total: 308ms	remaining: 1.04s
228:	learn: 0.5905437	total: 309ms	remaining: 1.04s
229:	learn: 0.5892600	total: 310ms	remaining: 1.04s
230:	learn: 0.5861387	total: 311ms	remaining: 1.04s
231:	learn: 0.5844497	total: 312ms	remaining: 1.03s
232:	learn: 0.5823761	total: 313ms	remaining: 1.03s
233:	learn: 0.5787664	total: 316ms	remaining: 1.03s
234:	learn: 0.5771600	total: 317ms	remaining: 1.03s
235:	learn: 0.5764778	total: 319ms	remaining: 1.03s
236:	learn: 0.5732245	total: 320ms	remaining: 1.03s
237:	learn: 0.5716676	total: 321ms	remaining: 1.03s
238:	learn: 0.5679807	total: 322ms	remaining: 1.02s
239:	learn: 0.5654913	total: 323ms	remaining: 1.02s
240:	learn: 0.5644225	total: 324ms	remaining: 1.02s
241:	learn: 0.5611907	total: 325ms	remaining: 1.02s
242:	learn: 0.5578056	total: 327ms	remaining: 1.02s
243:	learn: 0.5534069	total: 328ms	remaining: 1.01s
244:	learn: 0.5526746	total: 329ms	remaining: 1.01s
245:	learn: 0.5519534	total: 331ms	remaining: 1.01s
246:	learn: 0.5492837	total: 333ms	remaining: 1.01s
247:	learn: 0.5487105	total: 334ms	remaining: 1.01s
248:	learn: 0.5458125	total: 335ms	remaining: 1.01s
249:	learn: 0.5436311	total: 336ms	remaining: 1.01s
250:	learn: 0.5413376	total: 338ms	remaining: 1.01s
251:	learn: 0.5381732	total: 339ms	remaining: 1s
252:	learn: 0.5354121	total: 340ms	remaining: 1s
253:	learn: 0.5346439	total: 341ms	remaining: 1s
254:	learn: 0.5337711	total: 342ms	remaining: 999ms
255:	learn: 0.5328145	total: 343ms	remaining: 997ms
256:	learn: 0.5308936	total: 344ms	remaining: 995ms
257:	learn: 0.5270901	total: 345ms	remaining: 994ms
258:	learn: 0.5255260	total: 348ms	remaining: 995ms
259:	learn: 0.5221736	total: 349ms	remaining: 993ms
260:	learn: 0.5206577	total: 350ms	remaining: 992ms
261:	learn: 0.5179833	total: 351ms	remaining: 990ms
262:	learn: 0.5159614	total: 353ms	remaining: 988ms
263:	learn: 0.5145231	total: 354ms	remaining: 986ms
264:	learn: 0.5133509	total: 355ms	remaining: 984ms
265:	learn: 0.5101866	total: 356ms	remaining: 982ms
266:	learn: 0.5086840	total: 357ms	remaining: 980ms
267:	learn: 0.5056410	total: 358ms	remaining: 978ms
268:	learn: 0.5043181	total: 359ms	remaining: 977ms
269:	learn: 0.5015773	total: 361ms	remaining: 975ms
270:	learn: 0.5008089	total: 362ms	remaining: 973ms
271:	learn: 0.4986156	total: 366ms	remaining: 979ms
272:	learn: 0.4973697	total: 367ms	remaining: 978ms
273:	learn: 0.4960090	total: 368ms	remaining: 976ms
274:	learn: 0.4948443	total: 370ms	remaining: 974ms
275:	learn: 0.4935485	total: 371ms	remaining: 973ms
276:	learn: 0.4917351	total: 372ms	remaining: 971ms
277:	learn: 0.4891312	total: 373ms	remaining: 970ms
278:	learn: 0.4876679	total: 375ms	remaining: 968ms
279:	learn: 0.4853081	total: 376ms	remaining: 967ms
280:	learn: 0.4834181	total: 378ms	remaining: 968ms
281:	learn: 0.4812838	total: 380ms	remaining: 968ms
282:	learn: 0.4789440	total: 382ms	remaining: 967ms
283:	learn: 0.4782247	total: 383ms	remaining: 966ms
284:	learn: 0.4752399	total: 384ms	remaining: 964ms
285:	learn: 0.4743998	total: 386ms	remaining: 963ms
286:	learn: 0.4730701	total: 387ms	remaining: 961ms
287:	learn: 0.4710204	total: 388ms	remaining: 959ms
288:	learn: 0.4706172	total: 389ms	remaining: 957ms
289:	learn: 0.4682375	total: 390ms	remaining: 955ms
290:	learn: 0.4669432	total: 391ms	remaining: 954ms
291:	learn: 0.4660416	total: 393ms	remaining: 952ms
292:	learn: 0.4640127	total: 395ms	remaining: 953ms
293:	learn: 0.4625912	total: 398ms	remaining: 955ms
294:	learn: 0.4623261	total: 399ms	remaining: 953ms
295:	learn: 0.4610764	total: 400ms	remaining: 951ms
296:	learn: 0.4594815	total: 401ms	remaining: 950ms
297:	learn: 0.4582744	total: 402ms	remaining: 948ms
298:	learn: 0.4575918	total: 404ms	remaining: 946ms
299:	learn: 0.4559465	total: 405ms	remaining: 944ms
300:	learn: 0.4550582	total: 406ms	remaining: 943ms
301:	learn: 0.4526522	total: 407ms	remaining: 941ms
302:	learn: 0.4514783	total: 409ms	remaining: 941ms
303:	learn: 0.4491830	total: 412ms	remaining: 942ms
304:	learn: 0.4467478	total: 413ms	remaining: 940ms
305:	learn: 0.4454929	total: 414ms	remaining: 939ms
306:	learn: 0.4445482	total: 415ms	remaining: 938ms
307:	learn: 0.4431525	total: 417ms	remaining: 936ms
308:	learn: 0.4421330	total: 418ms	remaining: 934ms
309:	learn: 0.4409536	total: 419ms	remaining: 932ms
310:	learn: 0.4391975	total: 420ms	remaining: 931ms
311:	learn: 0.4384724	total: 421ms	remaining: 929ms
312:	learn: 0.4377379	total: 422ms	remaining: 927ms
313:	learn: 0.4351210	total: 423ms	remaining: 925ms
314:	learn: 0.4335472	total: 425ms	remaining: 923ms
315:	learn: 0.4333264	total: 427ms	remaining: 925ms
316:	learn: 0.4315238	total: 429ms	remaining: 923ms
317:	learn: 0.4309877	total: 430ms	remaining: 922ms
318:	learn: 0.4304025	total: 431ms	remaining: 920ms
319:	learn: 0.4288778	total: 432ms	remaining: 918ms
320:	learn: 0.4266767	total: 433ms	remaining: 916ms
321:	learn: 0.4254997	total: 434ms	remaining: 915ms
322:	learn: 0.4242732	total: 436ms	remaining: 913ms
323:	learn: 0.4225348	total: 437ms	remaining: 911ms
324:	learn: 0.4222805	total: 438ms	remaining: 909ms
325:	learn: 0.4207181	total: 439ms	remaining: 908ms
326:	learn: 0.4196226	total: 440ms	remaining: 906ms
327:	learn: 0.4175398	total: 443ms	remaining: 907ms
328:	learn: 0.4156613	total: 444ms	remaining: 906ms
329:	learn: 0.4139994	total: 446ms	remaining: 905ms
330:	learn: 0.4129606	total: 447ms	remaining: 903ms
331:	learn: 0.4117511	total: 448ms	remaining: 901ms
332:	learn: 0.4098168	total: 449ms	remaining: 900ms
333:	learn: 0.4087722	total: 451ms	remaining: 899ms
334:	learn: 0.4077408	total: 452ms	remaining: 897ms
335:	learn: 0.4065055	total: 453ms	remaining: 895ms
336:	learn: 0.4061027	total: 454ms	remaining: 893ms
337:	learn: 0.4054875	total: 455ms	remaining: 891ms
338:	learn: 0.4045017	total: 457ms	remaining: 890ms
339:	learn: 0.4042922	total: 459ms	remaining: 891ms
340:	learn: 0.4040867	total: 460ms	remaining: 889ms
341:	learn: 0.4026605	total: 461ms	remaining: 887ms
342:	learn: 0.4024662	total: 462ms	remaining: 886ms
343:	learn: 0.4009485	total: 463ms	remaining: 884ms
344:	learn: 0.3993003	total: 465ms	remaining: 882ms
345:	learn: 0.3991167	total: 466ms	remaining: 881ms
346:	learn: 0.3983712	total: 467ms	remaining: 879ms
347:	learn: 0.3972188	total: 468ms	remaining: 877ms
348:	learn: 0.3963360	total: 469ms	remaining: 875ms
349:	learn: 0.3956310	total: 470ms	remaining: 874ms
350:	learn: 0.3954528	total: 472ms	remaining: 872ms
351:	learn: 0.3944449	total: 474ms	remaining: 872ms
352:	learn: 0.3932955	total: 475ms	remaining: 871ms
353:	learn: 0.3925353	total: 476ms	remaining: 869ms
354:	learn: 0.3919401	total: 478ms	remaining: 868ms
355:	learn: 0.3900898	total: 479ms	remaining: 866ms
356:	learn: 0.3888601	total: 480ms	remaining: 865ms
357:	learn: 0.3869068	total: 481ms	remaining: 863ms
358:	learn: 0.3860353	total: 482ms	remaining: 861ms
359:	learn: 0.3857326	total: 484ms	remaining: 860ms
360:	learn: 0.3834165	total: 485ms	remaining: 858ms
361:	learn: 0.3820498	total: 486ms	remaining: 857ms
362:	learn: 0.3808059	total: 487ms	remaining: 855ms
363:	learn: 0.3794248	total: 490ms	remaining: 856ms
364:	learn: 0.3780927	total: 491ms	remaining: 854ms
365:	learn: 0.3779393	total: 492ms	remaining: 853ms
366:	learn: 0.3768063	total: 494ms	remaining: 851ms
367:	learn: 0.3751139	total: 495ms	remaining: 850ms
368:	learn: 0.3749538	total: 496ms	remaining: 848ms
369:	learn: 0.3744027	total: 497ms	remaining: 846ms
370:	learn: 0.3731621	total: 498ms	remaining: 845ms
371:	learn: 0.3717093	total: 499ms	remaining: 843ms
372:	learn: 0.3710413	total: 500ms	remaining: 841ms
373:	learn: 0.3700201	total: 502ms	remaining: 839ms
374:	learn: 0.3688259	total: 503ms	remaining: 838ms
375:	learn: 0.3667917	total: 504ms	remaining: 836ms
376:	learn: 0.3666400	total: 506ms	remaining: 836ms
377:	learn: 0.3647319	total: 507ms	remaining: 834ms
378:	learn: 0.3640921	total: 508ms	remaining: 833ms
379:	learn: 0.3627208	total: 510ms	remaining: 831ms
380:	learn: 0.3616774	total: 511ms	remaining: 830ms
381:	learn: 0.3609064	total: 512ms	remaining: 828ms

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fitting SVR for C2RCC_rhown_3x3_depth_lt_1
Fitting KNN for C2RCC_rhown_3x3_depth_lt_1
Fitting LR for C2RCC_rhown_3x3_depth_lt_1
Fitting RF for C2RCC_rhown_3x3_depth_lt_1
Fitting CAT for C2RCC_rhown_3x3_depth_lt_1
Learning rate set to 0.033272
0:	learn: 3.4097600	total: 3.54ms	remaining: 3.54s
1:	learn: 3.3466748	total: 4.68ms	remaining: 2.34s
2:	learn: 3.2995671	total: 5.78ms	remaining: 1.92s
3:	learn: 3.2520073	total: 6.86ms	remaining: 1.71s
4:	learn: 3.1905901	total: 7.93ms	remaining: 1.58s
5:	learn: 3.1424228	total: 9.03ms	remaining: 1.5s
6:	learn: 3.0965614	total: 10.1ms	remaining: 1.44s
7:	learn: 3.0487338	total: 11.2ms	remaining: 1.39s
8:	learn: 2.9968750	total: 12.3ms	remaining: 1.36s
9:	learn: 2.9459715	total: 14.3ms	remaining: 1.41s
10:	learn: 2.8971853	total: 15.8ms	remaining: 1.42s
11:	learn: 2.8647712	total: 16.9ms	remaining: 1.4s
12:	learn: 2.8182326	total: 18.1ms	remaining: 1.38s
13:	learn: 2.7796133	total: 19.3ms	remaining: 1.36s
14:	learn: 2.7328070	total: 20.5ms	remaining: 1.34s
15:	learn: 2.6973056	total: 21.7ms	remaining: 1.33s
16:	learn: 2.6592643	total: 22.9ms	remaining: 1.32s
17:	learn: 2.6182831	total: 23.9ms	remaining: 1.3s
18:	learn: 2.5767864	total: 25ms	remaining: 1.29s
19:	learn: 2.5434884	total: 26.3ms	remaining: 1.29s
20:	learn: 2.5077115	total: 27.5ms	remaining: 1.28s
21:	learn: 2.4776521	total: 28.9ms	remaining: 1.28s
22:	learn: 2.4425542	total: 30.1ms	remaining: 1.28s
23:	learn: 2.4096115	total: 31.3ms	remaining: 1.27s
24:	learn: 2.3712942	total: 32.4ms	remaining: 1.26s
25:	learn: 2.3403015	total: 33.7ms	remaining: 1.26s
26:	learn: 2.3064498	total: 34.8ms	remaining: 1.25s
27:	learn: 2.2689138	total: 35.9ms	remaining: 1.25s
28:	learn: 2.2381233	total: 37ms	remaining: 1.24s
29:	learn: 2.2098487	total: 38.1ms	remaining: 1.23s
30:	learn: 2.1813743	total: 39.2ms	remaining: 1.22s
31:	learn: 2.1458541	total: 40.3ms	remaining: 1.22s
32:	learn: 2.1075553	total: 41.3ms	remaining: 1.21s
33:	learn: 2.0776858	total: 42.4ms	remaining: 1.2s
34:	learn: 2.0463897	total: 43.7ms	remaining: 1.2s
35:	learn: 2.0223767	total: 45ms	remaining: 1.21s
36:	learn: 1.9946256	total: 46.2ms	remaining: 1.2s
37:	learn: 1.9668073	total: 47.3ms	remaining: 1.2s
38:	learn: 1.9385163	total: 48.4ms	remaining: 1.19s
39:	learn: 1.9154135	total: 49.5ms	remaining: 1.19s
40:	learn: 1.8851269	total: 50.5ms	remaining: 1.18s
41:	learn: 1.8621712	total: 51.6ms	remaining: 1.18s
42:	learn: 1.8463865	total: 52.7ms	remaining: 1.17s
43:	learn: 1.8232476	total: 53.8ms	remaining: 1.17s
44:	learn: 1.8073955	total: 54.9ms	remaining: 1.17s
45:	learn: 1.7960430	total: 56.1ms	remaining: 1.16s
46:	learn: 1.7710395	total: 57.2ms	remaining: 1.16s
47:	learn: 1.7495485	total: 58.3ms	remaining: 1.16s
48:	learn: 1.7283148	total: 59.3ms	remaining: 1.15s
49:	learn: 1.7132922	total: 61ms	remaining: 1.16s
50:	learn: 1.6857779	total: 62.2ms	remaining: 1.16s
51:	learn: 1.6680243	total: 63.3ms	remaining: 1.15s
52:	learn: 1.6530515	total: 64.5ms	remaining: 1.15s
53:	learn: 1.6312668	total: 65.7ms	remaining: 1.15s
54:	learn: 1.6163048	total: 66.7ms	remaining: 1.15s
55:	learn: 1.5939503	total: 67.8ms	remaining: 1.14s
56:	learn: 1.5707229	total: 68.9ms	remaining: 1.14s
57:	learn: 1.5603913	total: 70ms	remaining: 1.14s
58:	learn: 1.5426258	total: 71.1ms	remaining: 1.13s
59:	learn: 1.5218961	total: 73.5ms	remaining: 1.15s
60:	learn: 1.5087957	total: 74.9ms	remaining: 1.15s
61:	learn: 1.4931808	total: 76.3ms	remaining: 1.16s
62:	learn: 1.4771600	total: 77.7ms	remaining: 1.16s
63:	learn: 1.4622845	total: 79.1ms	remaining: 1.16s
64:	learn: 1.4460912	total: 80.5ms	remaining: 1.16s
65:	learn: 1.4322842	total: 81.8ms	remaining: 1.16s
66:	learn: 1.4239414	total: 83.1ms	remaining: 1.16s
67:	learn: 1.4109562	total: 84.3ms	remaining: 1.16s
68:	learn: 1.3906343	total: 85.4ms	remaining: 1.15s
69:	learn: 1.3839449	total: 86.6ms	remaining: 1.15s
70:	learn: 1.3714715	total: 87.7ms	remaining: 1.15s
71:	learn: 1.3563951	total: 88.8ms	remaining: 1.14s
72:	learn: 1.3425589	total: 89.9ms	remaining: 1.14s
73:	learn: 1.3393622	total: 91ms	remaining: 1.14s
74:	learn: 1.3276737	total: 92.2ms	remaining: 1.14s
75:	learn: 1.3149661	total: 93.6ms	remaining: 1.14s
76:	learn: 1.3035319	total: 95ms	remaining: 1.14s
77:	learn: 1.2967499	total: 96.2ms	remaining: 1.14s
78:	learn: 1.2910026	total: 97.4ms	remaining: 1.14s
79:	learn: 1.2798021	total: 98.5ms	remaining: 1.13s
80:	learn: 1.2741360	total: 99.7ms	remaining: 1.13s
81:	learn: 1.2655689	total: 101ms	remaining: 1.13s
82:	learn: 1.2613566	total: 102ms	remaining: 1.13s
83:	learn: 1.2525351	total: 103ms	remaining: 1.12s
84:	learn: 1.2420305	total: 104ms	remaining: 1.12s
85:	learn: 1.2331655	total: 105ms	remaining: 1.12s
86:	learn: 1.2303326	total: 106ms	remaining: 1.12s
87:	learn: 1.2236515	total: 108ms	remaining: 1.11s
88:	learn: 1.2171436	total: 109ms	remaining: 1.11s
89:	learn: 1.2005185	total: 110ms	remaining: 1.11s
90:	learn: 1.1894291	total: 111ms	remaining: 1.11s
91:	learn: 1.1776180	total: 113ms	remaining: 1.11s
92:	learn: 1.1721895	total: 114ms	remaining: 1.11s
93:	learn: 1.1599386	total: 115ms	remaining: 1.11s
94:	learn: 1.1500331	total: 117ms	remaining: 1.11s
95:	learn: 1.1390753	total: 118ms	remaining: 1.11s
96:	learn: 1.1303325	total: 119ms	remaining: 1.11s
97:	learn: 1.1259319	total: 121ms	remaining: 1.11s
98:	learn: 1.1233335	total: 123ms	remaining: 1.11s
99:	learn: 1.1170334	total: 124ms	remaining: 1.12s
100:	learn: 1.1119218	total: 126ms	remaining: 1.12s
101:	learn: 1.1021770	total: 127ms	remaining: 1.12s
102:	learn: 1.0951796	total: 128ms	remaining: 1.12s
103:	learn: 1.0879204	total: 129ms	remaining: 1.11s
104:	learn: 1.0818147	total: 130ms	remaining: 1.11s
105:	learn: 1.0735963	total: 132ms	remaining: 1.11s
106:	learn: 1.0651126	total: 133ms	remaining: 1.11s
107:	learn: 1.0611526	total: 134ms	remaining: 1.11s
108:	learn: 1.0534921	total: 135ms	remaining: 1.1s
109:	learn: 1.0495048	total: 136ms	remaining: 1.1s
110:	learn: 1.0436365	total: 138ms	remaining: 1.1s
111:	learn: 1.0359952	total: 139ms	remaining: 1.1s
112:	learn: 1.0281821	total: 141ms	remaining: 1.1s
113:	learn: 1.0253956	total: 142ms	remaining: 1.1s
114:	learn: 1.0210838	total: 143ms	remaining: 1.1s
115:	learn: 1.0154390	total: 144ms	remaining: 1.1s
116:	learn: 1.0092970	total: 146ms	remaining: 1.1s
117:	learn: 1.0045223	total: 147ms	remaining: 1.1s
118:	learn: 0.9975269	total: 148ms	remaining: 1.09s
119:	learn: 0.9923367	total: 149ms	remaining: 1.09s
120:	learn: 0.9908926	total: 150ms	remaining: 1.09s
121:	learn: 0.9881686	total: 151ms	remaining: 1.08s
122:	learn: 0.9823384	total: 152ms	remaining: 1.08s
123:	learn: 0.9775324	total: 154ms	remaining: 1.08s
124:	learn: 0.9715651	total: 155ms	remaining: 1.08s
125:	learn: 0.9654492	total: 156ms	remaining: 1.08s
126:	learn: 0.9601348	total: 157ms	remaining: 1.08s
127:	learn: 0.9582866	total: 159ms	remaining: 1.08s
128:	learn: 0.9523086	total: 161ms	remaining: 1.08s
129:	learn: 0.9426810	total: 162ms	remaining: 1.08s
130:	learn: 0.9390432	total: 163ms	remaining: 1.08s
131:	learn: 0.9326449	total: 164ms	remaining: 1.08s
132:	learn: 0.9258446	total: 165ms	remaining: 1.08s
133:	learn: 0.9213604	total: 167ms	remaining: 1.08s
134:	learn: 0.9175308	total: 168ms	remaining: 1.08s
135:	learn: 0.9140803	total: 169ms	remaining: 1.07s
136:	learn: 0.9101717	total: 171ms	remaining: 1.07s
137:	learn: 0.9042936	total: 172ms	remaining: 1.07s
138:	learn: 0.8994925	total: 173ms	remaining: 1.07s
139:	learn: 0.8977961	total: 174ms	remaining: 1.07s
140:	learn: 0.8933140	total: 176ms	remaining: 1.07s
141:	learn: 0.8904198	total: 177ms	remaining: 1.07s
142:	learn: 0.8880579	total: 179ms	remaining: 1.07s
143:	learn: 0.8856660	total: 180ms	remaining: 1.07s
144:	learn: 0.8833515	total: 181ms	remaining: 1.07s
145:	learn: 0.8813045	total: 183ms	remaining: 1.07s
146:	learn: 0.8800437	total: 184ms	remaining: 1.07s
147:	learn: 0.8777206	total: 185ms	remaining: 1.07s
148:	learn: 0.8739884	total: 187ms	remaining: 1.07s
149:	learn: 0.8695010	total: 188ms	remaining: 1.06s
150:	learn: 0.8656055	total: 190ms	remaining: 1.07s
151:	learn: 0.8635803	total: 191ms	remaining: 1.06s
152:	learn: 0.8584758	total: 193ms	remaining: 1.07s
153:	learn: 0.8547188	total: 194ms	remaining: 1.06s
154:	learn: 0.8525745	total: 195ms	remaining: 1.06s
155:	learn: 0.8501185	total: 197ms	remaining: 1.06s
156:	learn: 0.8445438	total: 198ms	remaining: 1.06s
157:	learn: 0.8404878	total: 199ms	remaining: 1.06s
158:	learn: 0.8377075	total: 201ms	remaining: 1.06s
159:	learn: 0.8347333	total: 202ms	remaining: 1.06s
160:	learn: 0.8318785	total: 203ms	remaining: 1.06s
161:	learn: 0.8286469	total: 205ms	remaining: 1.06s
162:	learn: 0.8246837	total: 206ms	remaining: 1.06s
163:	learn: 0.8191971	total: 207ms	remaining: 1.06s
164:	learn: 0.8171715	total: 209ms	remaining: 1.05s
165:	learn: 0.8144115	total: 210ms	remaining: 1.05s
166:	learn: 0.8096608	total: 211ms	remaining: 1.05s
167:	learn: 0.8076134	total: 213ms	remaining: 1.05s
168:	learn: 0.8067773	total: 214ms	remaining: 1.05s
169:	learn: 0.8023793	total: 215ms	remaining: 1.05s
170:	learn: 0.8005009	total: 217ms	remaining: 1.05s
171:	learn: 0.7986580	total: 218ms	remaining: 1.05s
172:	learn: 0.7971696	total: 219ms	remaining: 1.05s
173:	learn: 0.7943307	total: 221ms	remaining: 1.05s
174:	learn: 0.7932070	total: 222ms	remaining: 1.05s
175:	learn: 0.7916274	total: 223ms	remaining: 1.04s
176:	learn: 0.7868088	total: 225ms	remaining: 1.04s
177:	learn: 0.7854577	total: 226ms	remaining: 1.04s
178:	learn: 0.7843534	total: 228ms	remaining: 1.04s
179:	learn: 0.7827297	total: 230ms	remaining: 1.05s
180:	learn: 0.7765228	total: 231ms	remaining: 1.04s
181:	learn: 0.7746275	total: 233ms	remaining: 1.04s
182:	learn: 0.7739477	total: 234ms	remaining: 1.04s
183:	learn: 0.7717551	total: 235ms	remaining: 1.04s
184:	learn: 0.7702173	total: 237ms	remaining: 1.04s
185:	learn: 0.7655863	total: 238ms	remaining: 1.04s
186:	learn: 0.7639628	total: 239ms	remaining: 1.04s
187:	learn: 0.7597710	total: 241ms	remaining: 1.04s
188:	learn: 0.7572401	total: 242ms	remaining: 1.04s
189:	learn: 0.7555885	total: 244ms	remaining: 1.04s
190:	learn: 0.7515206	total: 245ms	remaining: 1.04s
191:	learn: 0.7467297	total: 246ms	remaining: 1.04s
192:	learn: 0.7437344	total: 248ms	remaining: 1.04s
193:	learn: 0.7429082	total: 249ms	remaining: 1.03s
194:	learn: 0.7420777	total: 251ms	remaining: 1.04s
195:	learn: 0.7377685	total: 252ms	remaining: 1.03s
196:	learn: 0.7363954	total: 254ms	remaining: 1.03s
197:	learn: 0.7329445	total: 256ms	remaining: 1.04s
198:	learn: 0.7305062	total: 257ms	remaining: 1.03s
199:	learn: 0.7281516	total: 258ms	remaining: 1.03s
200:	learn: 0.7263381	total: 260ms	remaining: 1.03s
201:	learn: 0.7230247	total: 261ms	remaining: 1.03s
202:	learn: 0.7219095	total: 262ms	remaining: 1.03s
203:	learn: 0.7162065	total: 263ms	remaining: 1.02s
204:	learn: 0.7146207	total: 264ms	remaining: 1.02s
205:	learn: 0.7125720	total: 265ms	remaining: 1.02s
206:	learn: 0.7082547	total: 266ms	remaining: 1.02s
207:	learn: 0.7061576	total: 267ms	remaining: 1.02s
208:	learn: 0.7052828	total: 268ms	remaining: 1.01s
209:	learn: 0.7039597	total: 269ms	remaining: 1.01s
210:	learn: 0.7028596	total: 271ms	remaining: 1.01s
211:	learn: 0.7013647	total: 273ms	remaining: 1.01s
212:	learn: 0.6991349	total: 274ms	remaining: 1.01s
213:	learn: 0.6976087	total: 275ms	remaining: 1.01s
214:	learn: 0.6968939	total: 276ms	remaining: 1.01s
215:	learn: 0.6957662	total: 277ms	remaining: 1s
216:	learn: 0.6942728	total: 278ms	remaining: 1s
217:	learn: 0.6925660	total: 279ms	remaining: 1s
218:	learn: 0.6905005	total: 280ms	remaining: 1s
219:	learn: 0.6882990	total: 282ms	remaining: 998ms
220:	learn: 0.6868413	total: 283ms	remaining: 996ms
221:	learn: 0.6855453	total: 284ms	remaining: 996ms
222:	learn: 0.6837581	total: 285ms	remaining: 995ms
223:	learn: 0.6816374	total: 287ms	remaining: 994ms
224:	learn: 0.6807585	total: 289ms	remaining: 994ms
225:	learn: 0.6792141	total: 290ms	remaining: 993ms
226:	learn: 0.6773188	total: 291ms	remaining: 992ms
227:	learn: 0.6754389	total: 293ms	remaining: 991ms
228:	learn: 0.6728050	total: 294ms	remaining: 990ms
229:	learn: 0.6711959	total: 295ms	remaining: 989ms
230:	learn: 0.6677062	total: 297ms	remaining: 988ms
231:	learn: 0.6662104	total: 298ms	remaining: 986ms
232:	learn: 0.6651604	total: 300ms	remaining: 987ms
233:	learn: 0.6626038	total: 302ms	remaining: 987ms
234:	learn: 0.6609923	total: 303ms	remaining: 986ms
235:	learn: 0.6596022	total: 304ms	remaining: 985ms
236:	learn: 0.6585223	total: 306ms	remaining: 985ms
237:	learn: 0.6575288	total: 307ms	remaining: 983ms
238:	learn: 0.6544799	total: 309ms	remaining: 983ms
239:	learn: 0.6531817	total: 310ms	remaining: 981ms
240:	learn: 0.6502578	total: 311ms	remaining: 980ms
241:	learn: 0.6493312	total: 312ms	remaining: 979ms
242:	learn: 0.6453697	total: 314ms	remaining: 977ms
243:	learn: 0.6441118	total: 315ms	remaining: 976ms
244:	learn: 0.6425573	total: 316ms	remaining: 975ms
245:	learn: 0.6411692	total: 318ms	remaining: 975ms
246:	learn: 0.6391056	total: 319ms	remaining: 974ms
247:	learn: 0.6367525	total: 321ms	remaining: 972ms
248:	learn: 0.6349729	total: 322ms	remaining: 971ms
249:	learn: 0.6321055	total: 323ms	remaining: 970ms
250:	learn: 0.6307168	total: 324ms	remaining: 968ms
251:	learn: 0.6294262	total: 325ms	remaining: 966ms
252:	learn: 0.6260602	total: 327ms	remaining: 964ms
253:	learn: 0.6235489	total: 328ms	remaining: 962ms
254:	learn: 0.6202231	total: 329ms	remaining: 961ms
255:	learn: 0.6160399	total: 330ms	remaining: 959ms
256:	learn: 0.6147600	total: 332ms	remaining: 960ms
257:	learn: 0.6118658	total: 333ms	remaining: 958ms
258:	learn: 0.6082672	total: 334ms	remaining: 957ms
259:	learn: 0.6061640	total: 336ms	remaining: 956ms
260:	learn: 0.6043029	total: 337ms	remaining: 954ms
261:	learn: 0.6026627	total: 338ms	remaining: 953ms
262:	learn: 0.6000244	total: 339ms	remaining: 951ms
263:	learn: 0.5988163	total: 341ms	remaining: 950ms
264:	learn: 0.5951639	total: 342ms	remaining: 948ms
265:	learn: 0.5940876	total: 343ms	remaining: 946ms
266:	learn: 0.5915394	total: 344ms	remaining: 945ms
267:	learn: 0.5898415	total: 346ms	remaining: 945ms
268:	learn: 0.5886682	total: 347ms	remaining: 944ms
269:	learn: 0.5861281	total: 349ms	remaining: 942ms
270:	learn: 0.5841099	total: 350ms	remaining: 941ms
271:	learn: 0.5816611	total: 351ms	remaining: 940ms
272:	learn: 0.5803306	total: 352ms	remaining: 937ms
273:	learn: 0.5779715	total: 353ms	remaining: 936ms
274:	learn: 0.5746502	total: 354ms	remaining: 935ms
275:	learn: 0.5724283	total: 356ms	remaining: 933ms
276:	learn: 0.5705333	total: 357ms	remaining: 931ms
277:	learn: 0.5673703	total: 358ms	remaining: 930ms
278:	learn: 0.5648669	total: 361ms	remaining: 933ms
279:	learn: 0.5637717	total: 363ms	remaining: 932ms
280:	learn: 0.5613426	total: 364ms	remaining: 931ms
281:	learn: 0.5590423	total: 365ms	remaining: 930ms
282:	learn: 0.5577618	total: 367ms	remaining: 929ms
283:	learn: 0.5570668	total: 368ms	remaining: 927ms
284:	learn: 0.5548351	total: 369ms	remaining: 926ms
285:	learn: 0.5537523	total: 373ms	remaining: 932ms
286:	learn: 0.5525488	total: 375ms	remaining: 931ms
287:	learn: 0.5514851	total: 376ms	remaining: 931ms
288:	learn: 0.5507975	total: 378ms	remaining: 929ms
289:	learn: 0.5502049	total: 379ms	remaining: 928ms
290:	learn: 0.5483076	total: 381ms	remaining: 928ms
291:	learn: 0.5463010	total: 382ms	remaining: 927ms
292:	learn: 0.5447456	total: 383ms	remaining: 925ms
293:	learn: 0.5435605	total: 385ms	remaining: 924ms
294:	learn: 0.5410035	total: 386ms	remaining: 922ms
295:	learn: 0.5403992	total: 387ms	remaining: 921ms
296:	learn: 0.5382966	total: 388ms	remaining: 919ms
297:	learn: 0.5362017	total: 390ms	remaining: 918ms
298:	learn: 0.5345852	total: 391ms	remaining: 917ms
299:	learn: 0.5335833	total: 392ms	remaining: 915ms
300:	learn: 0.5329702	total: 394ms	remaining: 915ms
301:	learn: 0.5312913	total: 395ms	remaining: 913ms
302:	learn: 0.5307384	total: 397ms	remaining: 912ms
303:	learn: 0.5288507	total: 398ms	remaining: 911ms
304:	learn: 0.5269223	total: 399ms	remaining: 909ms
305:	learn: 0.5247373	total: 400ms	remaining: 907ms
306:	learn: 0.5238658	total: 401ms	remaining: 906ms
307:	learn: 0.5214434	total: 403ms	remaining: 904ms
308:	learn: 0.5204260	total: 404ms	remaining: 903ms
309:	learn: 0.5193704	total: 405ms	remaining: 901ms
310:	learn: 0.5166436	total: 407ms	remaining: 901ms
311:	learn: 0.5157586	total: 408ms	remaining: 900ms
312:	learn: 0.5144446	total: 409ms	remaining: 898ms
313:	learn: 0.5125322	total: 411ms	remaining: 897ms
314:	learn: 0.5115284	total: 412ms	remaining: 895ms
315:	learn: 0.5095415	total: 413ms	remaining: 894ms
316:	learn: 0.5081116	total: 414ms	remaining: 892ms
317:	learn: 0.5057796	total: 415ms	remaining: 891ms
318:	learn: 0.5033808	total: 417ms	remaining: 890ms
319:	learn: 0.5026990	total: 418ms	remaining: 888ms
320:	learn: 0.5005787	total: 419ms	remaining: 886ms
321:	learn: 0.4986777	total: 420ms	remaining: 885ms
322:	learn: 0.4962195	total: 422ms	remaining: 884ms
323:	learn: 0.4942207	total: 423ms	remaining: 883ms
324:	learn: 0.4934375	total: 424ms	remaining: 882ms
325:	learn: 0.4914943	total: 426ms	remaining: 880ms
326:	learn: 0.4910140	total: 427ms	remaining: 879ms
327:	learn: 0.4905781	total: 428ms	remaining: 878ms
328:	learn: 0.4903127	total: 430ms	remaining: 876ms
329:	learn: 0.4897320	total: 431ms	remaining: 875ms
330:	learn: 0.4875516	total: 432ms	remaining: 873ms
331:	learn: 0.4859340	total: 433ms	remaining: 872ms
332:	learn: 0.4847016	total: 435ms	remaining: 871ms
333:	learn: 0.4839038	total: 436ms	remaining: 870ms
334:	learn: 0.4834206	total: 438ms	remaining: 869ms
335:	learn: 0.4816682	total: 439ms	remaining: 868ms
336:	learn: 0.4802478	total: 440ms	remaining: 866ms
337:	learn: 0.4784454	total: 441ms	remaining: 865ms
338:	learn: 0.4759965	total: 443ms	remaining: 863ms
339:	learn: 0.4741162	total: 444ms	remaining: 862ms
340:	learn: 0.4720938	total: 445ms	remaining: 860ms
341:	learn: 0.4703984	total: 446ms	remaining: 859ms
342:	learn: 0.4687815	total: 448ms	remaining: 857ms
343:	learn: 0.4682776	total: 449ms	remaining: 855ms
344:	learn: 0.4676262	total: 450ms	remaining: 854ms
345:	learn: 0.4653437	total: 451ms	remaining: 853ms
346:	learn: 0.4629527	total: 453ms	remaining: 852ms
347:	learn: 0.4606709	total: 454ms	remaining: 851ms
348:	learn: 0.4586716	total: 455ms	remaining: 849ms
349:	learn: 0.4569869	total: 457ms	remaining: 848ms
350:	learn: 0.4553881	total: 458ms	remaining: 847ms
351:	learn: 0.4549691	total: 459ms	remaining: 845ms
352:	learn: 0.4526285	total: 460ms	remaining: 844ms
353:	learn: 0.4522108	total: 462ms	remaining: 842ms
354:	learn: 0.4514517	total: 463ms	remaining: 841ms
355:	learn: 0.4506717	total: 464ms	remaining: 840ms
356:	learn: 0.4488653	total: 466ms	remaining: 838ms
357:	learn: 0.4462163	total: 467ms	remaining: 838ms
358:	learn: 0.4448848	total: 469ms	remaining: 837ms
359:	learn: 0.4440867	total: 470ms	remaining: 835ms
360:	learn: 0.4431865	total: 471ms	remaining: 834ms
361:	learn: 0.4428268	total: 473ms	remaining: 833ms
362:	learn: 0.4424104	total: 474ms	remaining: 832ms
363:	learn: 0.4420899	total: 475ms	remaining: 830ms
364:	learn: 0.4403619	total: 477ms	remaining: 829ms
365:	learn: 0.4397896	total: 478ms	remaining: 828ms
366:	learn: 0.4381191	total: 479ms	remaining: 827ms
367:	learn: 0.4377120	total: 481ms	remaining: 827ms
368:	learn: 0.4353379	total: 483ms	remaining: 826ms
369:	learn: 0.4338963	total: 484ms	remaining: 824ms
370:	learn: 0.4322062	total: 485ms	remaining: 823ms
371:	learn: 0.4302334	total: 487ms	remaining: 822ms
372:	learn: 0.4288106	total: 488ms	remaining: 820ms
373:	learn: 0.4285898	total: 489ms	remaining: 819ms
374:	learn: 0.4277729	total: 491ms	remaining: 818ms
375:	learn: 0.4271544	total: 492ms	remaining: 816ms
376:	learn: 0.4260725	total: 493ms	remaining: 815ms
377:	learn: 0.4236751	total: 495ms	remaining: 814ms
378:	learn: 0.4233607	total: 496ms	remaining: 813ms
379:	learn: 0.4225691	total: 497ms	remaining: 811ms
380:	learn: 0.4219676	total: 499ms	remaining: 810ms

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fitting SVR for C2RCC_rhow_1x1_depth_lt_1
Fitting KNN for C2RCC_rhow_1x1_depth_lt_1
Fitting LR for C2RCC_rhow_1x1_depth_lt_1
Fitting RF for C2RCC_rhow_1x1_depth_lt_1
Fitting CAT for C2RCC_rhow_1x1_depth_lt_1
Learning rate set to 0.033272
0:	learn: 3.4073191	total: 3.12ms	remaining: 3.12s
1:	learn: 3.3490540	total: 4.36ms	remaining: 2.17s
2:	learn: 3.3029165	total: 5.53ms	remaining: 1.84s
3:	learn: 3.2483306	total: 6.72ms	remaining: 1.67s
4:	learn: 3.2034362	total: 8ms	remaining: 1.59s
5:	learn: 3.1537909	total: 9.87ms	remaining: 1.63s
6:	learn: 3.1054676	total: 11.2ms	remaining: 1.59s
7:	learn: 3.0517937	total: 12.4ms	remaining: 1.53s
8:	learn: 2.9973583	total: 13.6ms	remaining: 1.5s
9:	learn: 2.9458330	total: 14.8ms	remaining: 1.46s
10:	learn: 2.9123639	total: 16ms	remaining: 1.44s
11:	learn: 2.8800820	total: 17.1ms	remaining: 1.41s
12:	learn: 2.8407615	total: 18.3ms	remaining: 1.39s
13:	learn: 2.8112349	total: 19.4ms	remaining: 1.37s
14:	learn: 2.7611414	total: 20.6ms	remaining: 1.35s
15:	learn: 2.7209199	total: 21.7ms	remaining: 1.34s
16:	learn: 2.6895394	total: 22.9ms	remaining: 1.32s
17:	learn: 2.6458578	total: 24.6ms	remaining: 1.34s
18:	learn: 2.6060294	total: 26ms	remaining: 1.34s
19:	learn: 2.5742021	total: 27.3ms	remaining: 1.33s
20:	learn: 2.5368178	total: 28.7ms	remaining: 1.34s
21:	learn: 2.5074187	total: 30ms	remaining: 1.33s
22:	learn: 2.4727110	total: 31.1ms	remaining: 1.32s
23:	learn: 2.4318644	total: 32.2ms	remaining: 1.31s
24:	learn: 2.3970756	total: 33.4ms	remaining: 1.3s
25:	learn: 2.3645329	total: 34.6ms	remaining: 1.29s
26:	learn: 2.3333787	total: 35.9ms	remaining: 1.29s
27:	learn: 2.3094187	total: 37.2ms	remaining: 1.29s
28:	learn: 2.2769455	total: 38.3ms	remaining: 1.28s
29:	learn: 2.2525794	total: 39.9ms	remaining: 1.29s
30:	learn: 2.2273039	total: 41.1ms	remaining: 1.28s
31:	learn: 2.1992531	total: 42.5ms	remaining: 1.28s
32:	learn: 2.1747795	total: 43.9ms	remaining: 1.28s
33:	learn: 2.1551578	total: 45.1ms	remaining: 1.28s
34:	learn: 2.1373657	total: 46.3ms	remaining: 1.27s
35:	learn: 2.1049946	total: 47.5ms	remaining: 1.27s
36:	learn: 2.0848570	total: 48.7ms	remaining: 1.27s
37:	learn: 2.0587498	total: 49.9ms	remaining: 1.26s
38:	learn: 2.0337588	total: 51.1ms	remaining: 1.26s
39:	learn: 2.0136236	total: 52.3ms	remaining: 1.25s
40:	learn: 1.9853789	total: 53.4ms	remaining: 1.25s
41:	learn: 1.9651467	total: 54.6ms	remaining: 1.25s
42:	learn: 1.9442275	total: 56.6ms	remaining: 1.26s
43:	learn: 1.9278375	total: 58ms	remaining: 1.26s
44:	learn: 1.9111811	total: 59.4ms	remaining: 1.26s
45:	learn: 1.8869418	total: 60.6ms	remaining: 1.26s
46:	learn: 1.8678302	total: 61.8ms	remaining: 1.25s
47:	learn: 1.8487423	total: 63.1ms	remaining: 1.25s
48:	learn: 1.8292692	total: 64.4ms	remaining: 1.25s
49:	learn: 1.8147146	total: 65.7ms	remaining: 1.25s
50:	learn: 1.7944664	total: 66.9ms	remaining: 1.24s
51:	learn: 1.7775124	total: 68ms	remaining: 1.24s
52:	learn: 1.7647814	total: 69.2ms	remaining: 1.24s
53:	learn: 1.7514063	total: 70.5ms	remaining: 1.23s
54:	learn: 1.7342690	total: 72.2ms	remaining: 1.24s
55:	learn: 1.7152021	total: 74.2ms	remaining: 1.25s
56:	learn: 1.7026429	total: 75.8ms	remaining: 1.25s
57:	learn: 1.6840758	total: 77.1ms	remaining: 1.25s
58:	learn: 1.6623522	total: 78.4ms	remaining: 1.25s
59:	learn: 1.6401159	total: 79.7ms	remaining: 1.25s
60:	learn: 1.6228306	total: 80.9ms	remaining: 1.25s
61:	learn: 1.6050953	total: 82.3ms	remaining: 1.25s
62:	learn: 1.5931031	total: 83.7ms	remaining: 1.25s
63:	learn: 1.5807688	total: 85ms	remaining: 1.24s
64:	learn: 1.5685548	total: 86.5ms	remaining: 1.24s
65:	learn: 1.5542328	total: 88.1ms	remaining: 1.25s
66:	learn: 1.5411630	total: 89.5ms	remaining: 1.25s
67:	learn: 1.5317578	total: 90.9ms	remaining: 1.25s
68:	learn: 1.5196238	total: 92.3ms	remaining: 1.25s
69:	learn: 1.5136351	total: 93.6ms	remaining: 1.24s
70:	learn: 1.4968965	total: 95ms	remaining: 1.24s
71:	learn: 1.4850837	total: 96.3ms	remaining: 1.24s
72:	learn: 1.4791274	total: 97.7ms	remaining: 1.24s
73:	learn: 1.4687649	total: 99ms	remaining: 1.24s
74:	learn: 1.4556947	total: 100ms	remaining: 1.24s
75:	learn: 1.4414235	total: 102ms	remaining: 1.23s
76:	learn: 1.4332540	total: 103ms	remaining: 1.24s
77:	learn: 1.4270299	total: 105ms	remaining: 1.24s
78:	learn: 1.4172911	total: 106ms	remaining: 1.23s
79:	learn: 1.4084885	total: 107ms	remaining: 1.23s
80:	learn: 1.3964377	total: 109ms	remaining: 1.23s
81:	learn: 1.3850583	total: 110ms	remaining: 1.23s
82:	learn: 1.3687411	total: 111ms	remaining: 1.23s
83:	learn: 1.3599756	total: 113ms	remaining: 1.23s
84:	learn: 1.3487401	total: 114ms	remaining: 1.23s
85:	learn: 1.3421786	total: 115ms	remaining: 1.23s
86:	learn: 1.3355545	total: 117ms	remaining: 1.23s
87:	learn: 1.3269188	total: 119ms	remaining: 1.23s
88:	learn: 1.3156089	total: 120ms	remaining: 1.23s
89:	learn: 1.3077888	total: 122ms	remaining: 1.23s
90:	learn: 1.3013974	total: 123ms	remaining: 1.23s
91:	learn: 1.2978508	total: 124ms	remaining: 1.23s
92:	learn: 1.2919357	total: 126ms	remaining: 1.23s
93:	learn: 1.2836741	total: 127ms	remaining: 1.22s
94:	learn: 1.2758811	total: 128ms	remaining: 1.22s
95:	learn: 1.2727569	total: 129ms	remaining: 1.22s
96:	learn: 1.2648937	total: 131ms	remaining: 1.22s
97:	learn: 1.2557603	total: 133ms	remaining: 1.22s
98:	learn: 1.2482118	total: 135ms	remaining: 1.23s
99:	learn: 1.2424244	total: 136ms	remaining: 1.23s
100:	learn: 1.2348996	total: 138ms	remaining: 1.23s
101:	learn: 1.2298760	total: 139ms	remaining: 1.22s
102:	learn: 1.2185332	total: 140ms	remaining: 1.22s
103:	learn: 1.2153885	total: 142ms	remaining: 1.22s
104:	learn: 1.2049258	total: 143ms	remaining: 1.22s
105:	learn: 1.1986262	total: 145ms	remaining: 1.22s
106:	learn: 1.1944307	total: 146ms	remaining: 1.22s
107:	learn: 1.1908519	total: 148ms	remaining: 1.22s
108:	learn: 1.1834401	total: 149ms	remaining: 1.22s
109:	learn: 1.1798232	total: 151ms	remaining: 1.22s
110:	learn: 1.1692781	total: 152ms	remaining: 1.22s
111:	learn: 1.1633060	total: 154ms	remaining: 1.22s
112:	learn: 1.1606946	total: 155ms	remaining: 1.22s
113:	learn: 1.1595448	total: 156ms	remaining: 1.21s
114:	learn: 1.1517675	total: 158ms	remaining: 1.21s
115:	learn: 1.1468161	total: 159ms	remaining: 1.21s
116:	learn: 1.1408814	total: 161ms	remaining: 1.21s
117:	learn: 1.1371335	total: 162ms	remaining: 1.21s
118:	learn: 1.1334200	total: 164ms	remaining: 1.21s
119:	learn: 1.1315189	total: 166ms	remaining: 1.22s
120:	learn: 1.1252393	total: 167ms	remaining: 1.21s
121:	learn: 1.1183305	total: 169ms	remaining: 1.21s
122:	learn: 1.1149194	total: 170ms	remaining: 1.21s
123:	learn: 1.1057533	total: 171ms	remaining: 1.21s
124:	learn: 1.1044781	total: 173ms	remaining: 1.21s
125:	learn: 1.1004984	total: 174ms	remaining: 1.21s
126:	learn: 1.0976585	total: 176ms	remaining: 1.21s
127:	learn: 1.0903484	total: 177ms	remaining: 1.21s
128:	learn: 1.0888116	total: 178ms	remaining: 1.2s
129:	learn: 1.0868735	total: 181ms	remaining: 1.21s
130:	learn: 1.0791837	total: 183ms	remaining: 1.22s
131:	learn: 1.0757566	total: 185ms	remaining: 1.21s
132:	learn: 1.0708423	total: 186ms	remaining: 1.21s
133:	learn: 1.0641383	total: 187ms	remaining: 1.21s
134:	learn: 1.0581427	total: 189ms	remaining: 1.21s
135:	learn: 1.0563828	total: 190ms	remaining: 1.21s
136:	learn: 1.0558507	total: 191ms	remaining: 1.2s
137:	learn: 1.0518215	total: 192ms	remaining: 1.2s
138:	learn: 1.0469213	total: 195ms	remaining: 1.21s
139:	learn: 1.0449613	total: 196ms	remaining: 1.2s
140:	learn: 1.0403706	total: 197ms	remaining: 1.2s
141:	learn: 1.0370364	total: 199ms	remaining: 1.2s
142:	learn: 1.0316589	total: 200ms	remaining: 1.2s
143:	learn: 1.0268863	total: 201ms	remaining: 1.2s
144:	learn: 1.0250206	total: 203ms	remaining: 1.2s
145:	learn: 1.0201183	total: 204ms	remaining: 1.19s
146:	learn: 1.0175479	total: 205ms	remaining: 1.19s
147:	learn: 1.0121098	total: 207ms	remaining: 1.19s
148:	learn: 1.0081268	total: 208ms	remaining: 1.19s
149:	learn: 1.0052384	total: 209ms	remaining: 1.19s
150:	learn: 0.9996632	total: 210ms	remaining: 1.18s
151:	learn: 0.9984691	total: 212ms	remaining: 1.18s
152:	learn: 0.9918589	total: 213ms	remaining: 1.18s
153:	learn: 0.9872082	total: 214ms	remaining: 1.18s
154:	learn: 0.9827596	total: 216ms	remaining: 1.18s
155:	learn: 0.9774448	total: 217ms	remaining: 1.17s
156:	learn: 0.9747672	total: 218ms	remaining: 1.17s
157:	learn: 0.9685687	total: 220ms	remaining: 1.17s
158:	learn: 0.9679223	total: 221ms	remaining: 1.17s
159:	learn: 0.9658415	total: 223ms	remaining: 1.17s
160:	learn: 0.9615722	total: 224ms	remaining: 1.17s
161:	learn: 0.9571940	total: 226ms	remaining: 1.17s
162:	learn: 0.9530941	total: 227ms	remaining: 1.17s
163:	learn: 0.9473354	total: 229ms	remaining: 1.17s
164:	learn: 0.9425402	total: 231ms	remaining: 1.17s
165:	learn: 0.9392605	total: 232ms	remaining: 1.17s
166:	learn: 0.9378624	total: 233ms	remaining: 1.16s
167:	learn: 0.9358261	total: 236ms	remaining: 1.17s
168:	learn: 0.9344168	total: 238ms	remaining: 1.17s
169:	learn: 0.9313869	total: 241ms	remaining: 1.18s
170:	learn: 0.9283831	total: 244ms	remaining: 1.18s
171:	learn: 0.9262290	total: 247ms	remaining: 1.19s
172:	learn: 0.9223907	total: 250ms	remaining: 1.19s
173:	learn: 0.9179490	total: 252ms	remaining: 1.2s
174:	learn: 0.9142140	total: 255ms	remaining: 1.2s
175:	learn: 0.9128902	total: 258ms	remaining: 1.21s
176:	learn: 0.9104818	total: 260ms	remaining: 1.21s
177:	learn: 0.9072150	total: 263ms	remaining: 1.21s
178:	learn: 0.9038096	total: 265ms	remaining: 1.22s
179:	learn: 0.9027526	total: 268ms	remaining: 1.22s
180:	learn: 0.8984100	total: 270ms	remaining: 1.22s
181:	learn: 0.8963157	total: 271ms	remaining: 1.22s
182:	learn: 0.8923729	total: 273ms	remaining: 1.22s
183:	learn: 0.8895403	total: 275ms	remaining: 1.22s
184:	learn: 0.8873005	total: 277ms	remaining: 1.22s
185:	learn: 0.8846224	total: 278ms	remaining: 1.22s
186:	learn: 0.8826843	total: 279ms	remaining: 1.21s
187:	learn: 0.8776159	total: 281ms	remaining: 1.21s
188:	learn: 0.8758516	total: 282ms	remaining: 1.21s
189:	learn: 0.8722847	total: 283ms	remaining: 1.21s
190:	learn: 0.8699195	total: 285ms	remaining: 1.21s
191:	learn: 0.8676899	total: 286ms	remaining: 1.2s
192:	learn: 0.8665553	total: 287ms	remaining: 1.2s
193:	learn: 0.8659352	total: 289ms	remaining: 1.2s
194:	learn: 0.8635934	total: 290ms	remaining: 1.2s
195:	learn: 0.8582984	total: 291ms	remaining: 1.2s
196:	learn: 0.8551913	total: 293ms	remaining: 1.19s
197:	learn: 0.8539531	total: 294ms	remaining: 1.19s
198:	learn: 0.8511689	total: 295ms	remaining: 1.19s
199:	learn: 0.8488146	total: 297ms	remaining: 1.19s
200:	learn: 0.8475894	total: 298ms	remaining: 1.18s
201:	learn: 0.8424169	total: 299ms	remaining: 1.18s
202:	learn: 0.8406266	total: 301ms	remaining: 1.18s
203:	learn: 0.8384211	total: 303ms	remaining: 1.18s
204:	learn: 0.8363202	total: 304ms	remaining: 1.18s
205:	learn: 0.8322028	total: 306ms	remaining: 1.18s
206:	learn: 0.8290592	total: 307ms	remaining: 1.18s
207:	learn: 0.8255941	total: 308ms	remaining: 1.17s
208:	learn: 0.8220767	total: 310ms	remaining: 1.17s
209:	learn: 0.8197758	total: 311ms	remaining: 1.17s
210:	learn: 0.8181725	total: 312ms	remaining: 1.17s
211:	learn: 0.8135485	total: 314ms	remaining: 1.17s
212:	learn: 0.8129955	total: 315ms	remaining: 1.16s
213:	learn: 0.8121049	total: 316ms	remaining: 1.16s
214:	learn: 0.8101686	total: 318ms	remaining: 1.16s
215:	learn: 0.8080565	total: 319ms	remaining: 1.16s
216:	learn: 0.8068776	total: 320ms	remaining: 1.16s
217:	learn: 0.8051281	total: 322ms	remaining: 1.15s
218:	learn: 0.8033846	total: 323ms	remaining: 1.15s
219:	learn: 0.8004208	total: 324ms	remaining: 1.15s
220:	learn: 0.7960140	total: 325ms	remaining: 1.15s
221:	learn: 0.7940910	total: 326ms	remaining: 1.14s
222:	learn: 0.7914411	total: 328ms	remaining: 1.14s
223:	learn: 0.7868860	total: 329ms	remaining: 1.14s
224:	learn: 0.7853585	total: 330ms	remaining: 1.14s
225:	learn: 0.7837376	total: 331ms	remaining: 1.13s
226:	learn: 0.7823087	total: 333ms	remaining: 1.13s
227:	learn: 0.7814464	total: 334ms	remaining: 1.13s
228:	learn: 0.7791539	total: 335ms	remaining: 1.13s
229:	learn: 0.7758259	total: 337ms	remaining: 1.13s
230:	learn: 0.7717586	total: 338ms	remaining: 1.13s
231:	learn: 0.7693157	total: 339ms	remaining: 1.12s
232:	learn: 0.7663765	total: 341ms	remaining: 1.12s
233:	learn: 0.7647555	total: 342ms	remaining: 1.12s
234:	learn: 0.7613874	total: 343ms	remaining: 1.12s
235:	learn: 0.7585456	total: 344ms	remaining: 1.11s
236:	learn: 0.7557379	total: 345ms	remaining: 1.11s
237:	learn: 0.7539971	total: 347ms	remaining: 1.11s
238:	learn: 0.7521983	total: 349ms	remaining: 1.11s
239:	learn: 0.7514558	total: 351ms	remaining: 1.11s
240:	learn: 0.7483509	total: 355ms	remaining: 1.12s
241:	learn: 0.7473297	total: 357ms	remaining: 1.12s
242:	learn: 0.7464259	total: 360ms	remaining: 1.12s
243:	learn: 0.7446506	total: 362ms	remaining: 1.12s
244:	learn: 0.7425978	total: 365ms	remaining: 1.13s
245:	learn: 0.7409718	total: 367ms	remaining: 1.13s
246:	learn: 0.7392076	total: 369ms	remaining: 1.12s
247:	learn: 0.7354301	total: 370ms	remaining: 1.12s
248:	learn: 0.7339262	total: 371ms	remaining: 1.12s
249:	learn: 0.7332000	total: 373ms	remaining: 1.12s
250:	learn: 0.7314864	total: 374ms	remaining: 1.11s
251:	learn: 0.7281025	total: 375ms	remaining: 1.11s
252:	learn: 0.7246455	total: 376ms	remaining: 1.11s
253:	learn: 0.7224369	total: 377ms	remaining: 1.11s
254:	learn: 0.7185783	total: 379ms	remaining: 1.11s
255:	learn: 0.7155926	total: 382ms	remaining: 1.11s
256:	learn: 0.7137716	total: 384ms	remaining: 1.11s
257:	learn: 0.7101335	total: 385ms	remaining: 1.11s
258:	learn: 0.7070437	total: 386ms	remaining: 1.1s
259:	learn: 0.7046758	total: 388ms	remaining: 1.1s
260:	learn: 0.7025735	total: 389ms	remaining: 1.1s
261:	learn: 0.6989873	total: 390ms	remaining: 1.1s
262:	learn: 0.6953705	total: 391ms	remaining: 1.1s
263:	learn: 0.6932435	total: 393ms	remaining: 1.09s
264:	learn: 0.6928365	total: 394ms	remaining: 1.09s
265:	learn: 0.6901816	total: 396ms	remaining: 1.09s
266:	learn: 0.6873702	total: 398ms	remaining: 1.09s
267:	learn: 0.6857252	total: 399ms	remaining: 1.09s
268:	learn: 0.6840856	total: 401ms	remaining: 1.09s
269:	learn: 0.6805046	total: 402ms	remaining: 1.09s
270:	learn: 0.6780168	total: 403ms	remaining: 1.08s
271:	learn: 0.6755580	total: 404ms	remaining: 1.08s
272:	learn: 0.6743461	total: 406ms	remaining: 1.08s
273:	learn: 0.6715164	total: 407ms	remaining: 1.08s
274:	learn: 0.6709323	total: 408ms	remaining: 1.07s
275:	learn: 0.6694431	total: 409ms	remaining: 1.07s
276:	learn: 0.6669394	total: 411ms	remaining: 1.07s
277:	learn: 0.6643121	total: 412ms	remaining: 1.07s
278:	learn: 0.6628978	total: 414ms	remaining: 1.07s
279:	learn: 0.6608894	total: 415ms	remaining: 1.07s
280:	learn: 0.6579954	total: 416ms	remaining: 1.06s
281:	learn: 0.6556836	total: 417ms	remaining: 1.06s
282:	learn: 0.6533307	total: 419ms	remaining: 1.06s
283:	learn: 0.6507785	total: 420ms	remaining: 1.06s
284:	learn: 0.6491065	total: 421ms	remaining: 1.06s
285:	learn: 0.6457706	total: 422ms	remaining: 1.05s
286:	learn: 0.6430680	total: 423ms	remaining: 1.05s
287:	learn: 0.6414249	total: 425ms	remaining: 1.05s
288:	learn: 0.6383492	total: 426ms	remaining: 1.05s
289:	learn: 0.6368651	total: 427ms	remaining: 1.04s
290:	learn: 0.6347508	total: 429ms	remaining: 1.04s
291:	learn: 0.6329451	total: 430ms	remaining: 1.04s
292:	learn: 0.6300321	total: 432ms	remaining: 1.04s
293:	learn: 0.6279395	total: 433ms	remaining: 1.04s
294:	learn: 0.6257527	total: 434ms	remaining: 1.04s
295:	learn: 0.6240001	total: 435ms	remaining: 1.03s
296:	learn: 0.6231176	total: 436ms	remaining: 1.03s
297:	learn: 0.6202820	total: 438ms	remaining: 1.03s
298:	learn: 0.6195318	total: 439ms	remaining: 1.03s
299:	learn: 0.6170432	total: 440ms	remaining: 1.03s
300:	learn: 0.6149103	total: 441ms	remaining: 1.02s
301:	learn: 0.6125815	total: 443ms	remaining: 1.02s
302:	learn: 0.6101356	total: 444ms	remaining: 1.02s
303:	learn: 0.6089891	total: 446ms	remaining: 1.02s
304:	learn: 0.6070255	total: 448ms	remaining: 1.02s
305:	learn: 0.6045031	total: 449ms	remaining: 1.02s
306:	learn: 0.6026257	total: 451ms	remaining: 1.02s
307:	learn: 0.6001874	total: 452ms	remaining: 1.01s
308:	learn: 0.5984904	total: 453ms	remaining: 1.01s
309:	learn: 0.5958338	total: 455ms	remaining: 1.01s
310:	learn: 0.5940879	total: 456ms	remaining: 1.01s
311:	learn: 0.5921103	total: 457ms	remaining: 1.01s
312:	learn: 0.5915902	total: 459ms	remaining: 1.01s
313:	learn: 0.5893063	total: 460ms	remaining: 1s
314:	learn: 0.5870255	total: 462ms	remaining: 1s
315:	learn: 0.5857690	total: 463ms	remaining: 1s
316:	learn: 0.5838474	total: 464ms	remaining: 1s
317:	learn: 0.5819130	total: 465ms	remaining: 998ms
318:	learn: 0.5795869	total: 467ms	remaining: 996ms
319:	learn: 0.5767724	total: 468ms	remaining: 994ms
320:	learn: 0.5741302	total: 469ms	remaining: 992ms
321:	learn: 0.5720223	total: 470ms	remaining: 990ms
322:	learn: 0.5697934	total: 471ms	remaining: 988ms
323:	learn: 0.5690261	total: 473ms	remaining: 986ms
324:	learn: 0.5662440	total: 474ms	remaining: 984ms
325:	learn: 0.5643214	total: 475ms	remaining: 983ms
326:	learn: 0.5622789	total: 477ms	remaining: 981ms
327:	learn: 0.5605888	total: 478ms	remaining: 979ms
328:	learn: 0.5600637	total: 479ms	remaining: 978ms
329:	learn: 0.5580261	total: 481ms	remaining: 976ms
330:	learn: 0.5565598	total: 482ms	remaining: 974ms
331:	learn: 0.5549394	total: 483ms	remaining: 972ms
332:	learn: 0.5531565	total: 485ms	remaining: 971ms
333:	learn: 0.5520596	total: 486ms	remaining: 969ms
334:	learn: 0.5500189	total: 487ms	remaining: 968ms
335:	learn: 0.5480646	total: 489ms	remaining: 965ms
336:	learn: 0.5475652	total: 490ms	remaining: 964ms
337:	learn: 0.5450296	total: 492ms	remaining: 964ms
338:	learn: 0.5421444	total: 493ms	remaining: 962ms
339:	learn: 0.5410374	total: 495ms	remaining: 960ms
340:	learn: 0.5398161	total: 496ms	remaining: 958ms
341:	learn: 0.5387133	total: 497ms	remaining: 956ms
342:	learn: 0.5375452	total: 498ms	remaining: 954ms
343:	learn: 0.5368540	total: 499ms	remaining: 952ms
344:	learn: 0.5362051	total: 501ms	remaining: 951ms
345:	learn: 0.5354206	total: 502ms	remaining: 949ms
346:	learn: 0.5345097	total: 503ms	remaining: 947ms
347:	learn: 0.5334123	total: 504ms	remaining: 945ms
348:	learn: 0.5327438	total: 506ms	remaining: 943ms
349:	learn: 0.5310118	total: 507ms	remaining: 942ms
350:	learn: 0.5297587	total: 509ms	remaining: 941ms
351:	learn: 0.5287031	total: 510ms	remaining: 940ms
352:	learn: 0.5274835	total: 512ms	remaining: 938ms
353:	learn: 0.5254176	total: 513ms	remaining: 936ms
354:	learn: 0.5247605	total: 514ms	remaining: 934ms
355:	learn: 0.5237650	total: 515ms	remaining: 932ms
356:	learn: 0.5231115	total: 517ms	remaining: 931ms
357:	learn: 0.5220915	total: 518ms	remaining: 929ms
358:	learn: 0.5206978	total: 519ms	remaining: 927ms
359:	learn: 0.5190463	total: 521ms	remaining: 925ms
360:	learn: 0.5160681	total: 523ms	remaining: 926ms
361:	learn: 0.5143837	total: 524ms	remaining: 924ms
362:	learn: 0.5134279	total: 526ms	remaining: 923ms
363:	learn: 0.5123654	total: 527ms	remaining: 921ms
364:	learn: 0.5108392	total: 529ms	remaining: 920ms
365:	learn: 0.5085388	total: 530ms	remaining: 918ms
366:	learn: 0.5072245	total: 531ms	remaining: 916ms
367:	learn: 0.5044728	total: 532ms	remaining: 914ms
368:	learn: 0.5035205	total: 533ms	remaining: 912ms
369:	learn: 0.5021009	total: 535ms	remaining: 910ms
370:	learn: 0.5002455	total: 536ms	remaining: 908ms
371:	learn: 0.4982384	total: 537ms	remaining: 907ms
372:	learn: 0.4975234	total: 539ms	remaining: 907ms
373:	learn: 0.4964720	total: 541ms	remaining: 905ms
374:	learn: 0.4946879	total: 542ms	remaining: 904ms
375:	learn: 0.4933065	total: 544ms	remaining: 902ms
376:	learn: 0.4914778	total: 545ms	remaining: 900ms
377:	learn: 0.4903813	total: 546ms	remaining: 899ms
378:	learn: 0.4894840	total: 547ms	remaining: 897ms
379:	learn: 0.4879237	total: 549ms	remaining: 895ms
380:	learn: 0.4868249	total: 550ms	remaining: 894ms

In [242]:
# Para hacer un dataframe con multiindex en el que se vea todo

rows = []

for df_name, model_scores in results.items():
    row = {}
    for model_name, metrics in model_scores.items():
        for metric_name, value in metrics.items():
            # Clave: (métrica, modelo) → orden correcto para columnas
            row[(metric_name, model_name)] = value
    rows.append((df_name, row))

df_results = pd.DataFrame.from_dict(dict(rows), orient="index")
df_results.columns = pd.MultiIndex.from_tuples(df_results.columns, names=["Metric", "Model"])
df_results = df_results.sort_index(axis=1, level=0)
df_results = df_results.sort_index(axis=0)

In [243]:
df_results

Metric                              R2                                         \
Model                              CAT    EN Ensemble   KNN   LBM    LR   MLP
C2RCC_rhow_1x1_depth_lt_1         0.60  0.32     0.77  0.65  0.62  0.64  0.78
C2RCC_rhow_3x3_depth_lt_1         0.62  0.33     0.79  0.63  0.63  0.47  0.78
C2RCC_rhow_5x5_depth_lt_1         0.67  0.37     0.78  0.64  0.65  0.64  0.80
C2RCC_rhow_9x9_depth_lt_1         0.78  0.37     0.69  0.62  0.70  0.49  0.77
C2RCC_rhown_1x1_depth_lt_1        0.51  0.30     0.72  0.68  0.62  0.44  0.77
C2RCC_rhown_3x3_depth_lt_1        0.62  0.31     0.78  0.61  0.62  0.48  0.76
C2RCC_rhown_5x5_depth_lt_1        0.64  0.36     0.69  0.67  0.64  0.62  0.81
C2RCC_rhown_9x9_depth_lt_1        0.81  0.36     0.74  0.62  0.70  0.55  0.77
C2X-Complex_rhow_1x1_depth_lt_1   0.68  0.36     0.43  0.64  0.70  0.15  0.72
C2X-Complex_rhow_3x3_depth_lt_1   0.71  0.37     0.51  0.60  0.56  0.10  0.72
C2X-Complex_rhow_5x5_depth_lt_1   0.71  0.41     0.63  0.58  0.67 -2.23  0.73
C2X-Complex_rhow_9x9_depth_lt_1   0.80  0.50     0.74  0.64  0.81  0.41  0.77
C2X-Complex_rhown_1x1_depth_lt_1  0.73  0.40     0.77  0.69  0.68  0.55  0.72
C2X-Complex_rhown_3x3_depth_lt_1  0.67  0.37     0.53  0.56  0.60  0.54  0.72
C2X-Complex_rhown_5x5_depth_lt_1  0.71  0.44     0.78  0.62  0.65  0.49  0.72
C2X-Complex_rhown_9x9_depth_lt_1  0.79  0.50     0.79  0.67  0.74  0.45  0.80
C2X_rhow_1x1_depth_lt_1           0.68  0.62     0.74  0.60  0.59  0.08  0.55
C2X_rhow_3x3_depth_lt_1           0.62  0.47     0.52  0.62  0.59 -0.88  0.65
C2X_rhow_5x5_depth_lt_1           0.48  0.54     0.69  0.57  0.50  0.54  0.76
C2X_rhow_9x9_depth_lt_1           0.68  0.65     0.70  0.70  0.67  0.37  0.79
C2X_rhown_1x1_depth_lt_1          0.61  0.53     0.59  0.50  0.52  0.33  0.53
C2X_rhown_3x3_depth_lt_1          0.61  0.32     0.69  0.51  0.60  0.03  0.66
C2X_rhown_5x5_depth_lt_1          0.50  0.43     0.60  0.45  0.43  0.72  0.71
C2X_rhown_9x9_depth_lt_1          0.68  0.60     0.76  0.55  0.59  0.47  0.77
TOA_1x1_depth_lt_1                0.36  0.01     0.24  0.37  0.45  0.27  0.41
TOA_3x3_depth_lt_1                0.63  0.02     0.45  0.42  0.51  0.45  0.50
TOA_5x5_depth_lt_1                0.60  0.04     0.49  0.46  0.42  0.38  0.57
TOA_9x9_depth_lt_1                0.60  0.04     0.42  0.46  0.54 -0.03  0.68

Metric                                              RMSE                       \
Model                               RF   SVR   XGB   CAT    EN Ensemble   KNN
C2RCC_rhow_1x1_depth_lt_1         0.62  0.30  0.39  3.00  3.93     2.28  2.82
C2RCC_rhow_3x3_depth_lt_1         0.61  0.33  0.58  2.94  3.92     2.20  2.90
C2RCC_rhow_5x5_depth_lt_1         0.70  0.35  0.78  2.72  3.79     2.23  2.86
C2RCC_rhow_9x9_depth_lt_1         0.71  0.33  0.65  2.26  3.80     2.66  2.96
C2RCC_rhown_1x1_depth_lt_1        0.56  0.30  0.58  3.33  3.99     2.54  2.70
C2RCC_rhown_3x3_depth_lt_1        0.59  0.32  0.76  2.94  3.96     2.25  2.96
C2RCC_rhown_5x5_depth_lt_1        0.71  0.35  0.77  2.85  3.82     2.65  2.74
C2RCC_rhown_9x9_depth_lt_1        0.76  0.33  0.82  2.07  3.82     2.43  2.93
C2X-Complex_rhow_1x1_depth_lt_1   0.60  0.23  0.66  2.71  3.81     3.59  2.87
C2X-Complex_rhow_3x3_depth_lt_1   0.62  0.28  0.59  2.57  3.79     3.33  3.03
C2X-Complex_rhow_5x5_depth_lt_1   0.58  0.29  0.59  2.56  3.65     2.90  3.09
C2X-Complex_rhow_9x9_depth_lt_1   0.68  0.22  0.53  2.14  3.38     2.43  2.84
C2X-Complex_rhown_1x1_depth_lt_1  0.59  0.33  0.61  2.49  3.69     2.27  2.65
C2X-Complex_rhown_3x3_depth_lt_1  0.53  0.36  0.64  2.75  3.77     3.27  3.18
C2X-Complex_rhown_5x5_depth_lt_1  0.65  0.32  0.73  2.55  3.58     2.23  2.94
C2X-Complex_rhown_9x9_depth_lt_1  0.69  0.29  0.53  2.17  3.38     2.17  2.74
C2X_rhow_1x1_depth_lt_1           0.62  0.23  0.60  2.68  2.94     2.45  3.01
C2X_rhow_3x3_depth_lt_1           0.57  0.27  0.48  2.95  3.48     3.29  2.96
C2X_rhow_5x5_depth_lt_1           0.47  0.24  0.51  3.42  3.23     2.64  3.11
C2X_rhow_9x9_depth_lt_1           0.68  0.21  0.74  2.69  2.82     2.63  2.60
C2X_rhown_1x1_depth_lt_1          0.53  0.23  0.48  2.96  3.27     3.05  3.37
C2X_rhown_3x3_depth_lt_1          0.50  0.27  0.46  2.98  3.92     2.66  3.35
C2X_rhown_5x5_depth_lt_1          0.39  0.24  0.44  3.37  3.61     3.01  3.53
C2X_rhown_9x9_depth_lt_1          0.60  0.21  0.54  2.68  3.03     2.36  3.20
TOA_1x1_depth_lt_1                0.16  0.12  0.16  2.82  3.51     3.08  2.82
TOA_3x3_depth_lt_1                0.46  0.13  0.39  2.15  3.50     2.61  2.70
TOA_5x5_depth_lt_1                0.51  0.13  0.32  2.24  3.47     2.53  2.60
TOA_9x9_depth_lt_1                0.42  0.14  0.36  2.23  3.47     2.70  2.59

Metric
Model                              LBM    LR   MLP    RF   SVR   XGB
C2RCC_rhow_1x1_depth_lt_1         2.95  2.88  2.22  2.94  3.98  3.72
C2RCC_rhow_3x3_depth_lt_1         2.91  3.45  2.23  2.96  3.91  3.10
C2RCC_rhow_5x5_depth_lt_1         2.83  2.85  2.12  2.59  3.84  2.23
C2RCC_rhow_9x9_depth_lt_1         2.63  3.41  2.29  2.56  3.90  2.82
C2RCC_rhown_1x1_depth_lt_1        2.94  3.57  2.28  3.15  4.00  3.09
C2RCC_rhown_3x3_depth_lt_1        2.93  3.42  2.34  3.04  3.93  2.35
C2RCC_rhown_5x5_depth_lt_1        2.84  2.92  2.10  2.56  3.85  2.29
C2RCC_rhown_9x9_depth_lt_1        2.59  3.20  2.30  2.35  3.90  2.00
C2X-Complex_rhow_1x1_depth_lt_1   2.61  4.39  2.53  3.02  4.17  2.80
C2X-Complex_rhow_3x3_depth_lt_1   3.16  4.52  2.52  2.95  4.05  3.04
C2X-Complex_rhow_5x5_depth_lt_1   2.76  8.57  2.47  3.11  4.01  3.05
C2X-Complex_rhow_9x9_depth_lt_1   2.10  3.68  2.27  2.68  4.20  3.26
C2X-Complex_rhown_1x1_depth_lt_1  2.68  3.19  2.54  3.06  3.91  2.98
C2X-Complex_rhown_3x3_depth_lt_1  3.01  3.24  2.53  3.25  3.82  2.85
C2X-Complex_rhown_5x5_depth_lt_1  2.84  3.42  2.54  2.81  3.92  2.49
C2X-Complex_rhown_9x9_depth_lt_1  2.43  3.53  2.14  2.63  4.00  3.27
C2X_rhow_1x1_depth_lt_1           3.04  4.56  3.20  2.94  4.19  3.03
C2X_rhow_3x3_depth_lt_1           3.07  6.54  2.84  3.12  4.07  3.44
C2X_rhow_5x5_depth_lt_1           3.36  3.22  2.35  3.48  4.16  3.33
C2X_rhow_9x9_depth_lt_1           2.72  3.77  2.17  2.70  4.25  2.44
C2X_rhown_1x1_depth_lt_1          3.29  3.92  3.27  3.26  4.18  3.43
C2X_rhown_3x3_depth_lt_1          3.01  4.70  2.80  3.36  4.08  3.50
C2X_rhown_5x5_depth_lt_1          3.59  2.54  2.55  3.71  4.15  3.57
C2X_rhown_9x9_depth_lt_1          3.06  3.46  2.26  3.00  4.24  3.22
TOA_1x1_depth_lt_1                2.63  3.01  2.73  3.24  3.32  3.25
TOA_3x3_depth_lt_1                2.47  2.61  2.50  2.60  3.29  2.77
TOA_5x5_depth_lt_1                2.70  2.79  2.32  2.46  3.30  2.92
TOA_9x9_depth_lt_1                2.39  3.59  2.00  2.69  3.28  2.83

In [114]:
df_results

metric                              r2              rmse
model                              LBM   MLP   XGB   LBM   MLP   XGB
C2RCC_rhow_5x5_depth_lt_1         0.51  0.67  0.72  2.59  2.12  1.95
C2X-Complex_rhown_3x3_depth_lt_1  0.52  0.63  0.70  2.57  2.25  2.03
TOA_9x9_depth_lt_1                0.50  0.48  0.61  2.61  2.65  2.29
C2X_rhow_3x3_depth_lt_1           0.54  0.64  0.64  2.50  2.23  2.24
C2RCC_rhow_9x9_depth_lt_1         0.63  0.75  0.57  2.25  1.87  2.44
C2X-Complex_rhown_5x5_depth_lt_1  0.63  0.55  0.73  2.25  2.48  1.92
C2X_rhown_9x9_depth_lt_1          0.49  0.67  0.44  2.66  2.13  2.77
TOA_3x3_depth_lt_1                0.56  0.47  0.57  2.44  2.69  2.41
C2X-Complex_rhown_9x9_depth_lt_1  0.58  0.71  0.64  2.39  2.01  2.22
C2X-Complex_rhow_3x3_depth_lt_1   0.66  0.24  0.68  2.15  3.24  2.10
C2X_rhow_1x1_depth_lt_1           0.27  0.52  0.45  3.16  2.58  2.74
C2RCC_rhown_1x1_depth_lt_1        0.41  0.58  0.68  2.85  2.41  2.11
C2X_rhown_1x1_depth_lt_1          0.20  0.35  0.16  3.31  2.99  3.40
C2RCC_rhown_9x9_depth_lt_1        0.45  0.67  0.54  2.74  2.13  2.53
C2X_rhow_5x5_depth_lt_1           0.52  0.65  0.68  2.56  2.19  2.09
C2X_rhown_5x5_depth_lt_1          0.51  0.38  0.59  2.58  2.91  2.36
C2X_rhow_9x9_depth_lt_1           0.60  0.69  0.67  2.34  2.07  2.14
C2X_rhown_3x3_depth_lt_1          0.10  0.57  0.58  3.51  2.43  2.40
C2RCC_rhown_5x5_depth_lt_1        0.68  0.64  0.79  2.10  2.22  1.70
TOA_1x1_depth_lt_1                0.66  0.47  0.61  2.13  2.68  2.29
C2X-Complex_rhow_5x5_depth_lt_1   0.88  0.03  0.88  1.29  3.65  1.27
C2X-Complex_rhow_9x9_depth_lt_1   0.61  0.13  0.68  2.30  3.46  2.10
C2X-Complex_rhow_1x1_depth_lt_1   0.66  0.57  0.67  2.18  2.42  2.14
C2X-Complex_rhown_1x1_depth_lt_1  0.43  0.68  0.51  2.80  2.11  2.59
C2RCC_rhow_3x3_depth_lt_1         0.64  0.63  0.56  2.24  2.26  2.47
TOA_5x5_depth_lt_1                0.52  0.48  0.55  2.54  2.66  2.48
C2RCC_rhown_3x3_depth_lt_1        0.70  0.65  0.64  2.03  2.19  2.22
C2RCC_rhow_1x1_depth_lt_1         0.23  0.55  0.64  3.25  2.50  2.22

In [292]:
def objective(trial, df, target, model_name):
    df = df.iloc[:,4:]
    # Mismos splits que para el entrenamiento
    train, test = train_test_split(df, test_size=0.2, random_state=42, stratify=df["High_Chl"]) # TEST 20% TRAIN 80%
    target = "Chl"
    train, val = train_test_split(train, test_size=0.25, random_state=42, stratify=train["High_Chl"])

    X = train.drop(columns=[target, 'High_Chl'])
    y = train[target]
    y_class = train["High_Chl"]

    # Definimos los folds
    skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
    
    oof_preds = np.zeros(len(train))  # Almacenar las predicciones OOF

    start = time.time()
    
    if model_name == "LBM":
        params = {
            'objective': 'regression',
            'metric': 'rmse',
            'boosting_type': 'gbdt',
            'device': 'cpu',  # usa CPU/GPU
            'verbosity': -1,
            'learning_rate': trial.suggest_float('learning_rate', 0.005, 0.1, log=True),
            'num_leaves': trial.suggest_categorical('num_leaves', [20, 40, 60, 80]),
            'max_depth': trial.suggest_int('max_depth', 5, 8),
            'min_child_samples': trial.suggest_int('min_child_samples', 5, 25),
            'subsample': trial.suggest_float('subsample', 0.6, 1.0),
            'colsample_bytree': trial.suggest_float('colsample_bytree', 0.6, 1.0),
            'n_estimators': trial.suggest_categorical('n_estimators', [500, 1000, 2000])
        }

    if model_name == "XGB":
        params = {
            'n_estimators': trial.suggest_categorical('n_estimators', [500, 1000, 2000]),
            'learning_rate': trial.suggest_float('learning_rate', 0.005, 0.1, log=True),
            'max_depth': trial.suggest_int('max_depth', 5, 8),
            'min_child_weight': trial.suggest_int('min_child_weight', 1, 4),
            'subsample': trial.suggest_float('subsample', 0.6, 1.0),
            'colsample_bytree': trial.suggest_float('colsample_bytree', 0.6, 1.0),
            'device': 'cpu',
            'objective': 'reg:squarederror',
            'tree_method': 'hist',
            'enable_categorical': True,
            'eval_metric': 'rmse'
        }
    
    if model_name == "MLP":
        # Así para evitar warning de definir como tuple
        hidden_options = {
            '50': (50,),
            '100': (100,),
            '100_50': (100, 50),
            '128_64': (128, 64)
        }
        key = trial.suggest_categorical('hidden_layer_sizes', list(hidden_options.keys()))
        params = {
            'hidden_layer_sizes': hidden_options[key],
            #'hidden_layer_sizes': trial.suggest_categorical('hidden_layer_sizes', [(50,), (100,), (100, 50), (128, 64)]),
            'activation': trial.suggest_categorical('activation', ['relu', 'tanh']),
            'solver': trial.suggest_categorical('solver', ['adam', 'sgd']),
            'alpha': trial.suggest_float('alpha', 1e-5, 1e-1, log=True),
            'learning_rate': trial.suggest_categorical('learning_rate', ['constant', 'adaptive']),
            'learning_rate_init': trial.suggest_float('learning_rate_init', 1e-4, 1e-2, log=True),
            'max_iter': 200,
            'n_iter_no_change': 25,
            'early_stopping': True,
            'validation_fraction': 0.2,
            'random_state': 42,
            'verbose': False
        }

    if model_name == "SVR":
        params = {
            'kernel': trial.suggest_categorical('kernel', ['rbf', 'sigmoid']),
            'C': trial.suggest_float('C', 0.1, 10.0, log=True),
            'epsilon': trial.suggest_float('epsilon', 0.01, 0.2),
            'gamma': trial.suggest_categorical('gamma', ['scale', 'auto']),
            'shrinking': True,
            'tol': 1e-3,
            'max_iter': -1,
            'verbose': False
        }

    if model_name == "KNN":
        params = {
            'n_neighbors': trial.suggest_int('n_neighbors', 3, 15),
            'weights': trial.suggest_categorical('weights', ['uniform', 'distance']),
            'algorithm': 'auto',
            'leaf_size': trial.suggest_int('leaf_size', 10, 40),
            'p': 2,  # 1 = manhattan, 2 = euclídea
            'metric': 'minkowski',
            'n_jobs': -1
        }

    if model_name == "LR":
        # No sirve de mucho, pero por completitud
        params = {
            'fit_intercept': trial.suggest_categorical('fit_intercept', [True, False]),
            'positive': trial.suggest_categorical('positive', [True, False]),
        }

    if model_name == "RF":
        params = {
            'n_estimators': trial.suggest_categorical('n_estimators', [100, 300, 500]),
            'max_depth': trial.suggest_int('max_depth', 5, 15),
            'min_samples_split': trial.suggest_int('min_samples_split', 2, 10),
            'min_samples_leaf': trial.suggest_int('min_samples_leaf', 1, 5),
            'bootstrap': trial.suggest_categorical('bootstrap', [True, False]),
            'random_state': 42,
            'verbose': 0
        }

    if model_name == "CAT":
        params = {
            'iterations': trial.suggest_categorical('iterations', [500, 1000, 2000]),
            'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.1, log=True),
            'depth': trial.suggest_int('depth', 4, 10),
            'l2_leaf_reg': trial.suggest_float('l2_leaf_reg', 1.0, 10.0),
            'loss_function': 'RMSE',
            'eval_metric': 'RMSE',
            'random_seed': 42,
            'early_stopping_rounds': 50,
            'verbose': False,
        }

    if model_name == "EN":
        params = {
            'alpha': trial.suggest_float('alpha', 1e-4, 10.0, log=True),
            'l1_ratio': trial.suggest_float('l1_ratio', 0.0, 1.0),
            'fit_intercept': True,
            'max_iter': 1000,
            'tol': 1e-4,
            'selection': 'cyclic',
            'random_state': 42
        }

    # Cargamos el modelo correspondiente
    model = models[model_name](**params)

    
    for fold, (train_idx, val_idx) in enumerate(skf.split(X, y_class)):
        print(f"Fold {fold+1}")
        
        X_train, X_val = X.iloc[train_idx], X.iloc[val_idx]
        y_train, y_val = y.iloc[train_idx], y.iloc[val_idx]

        if model_name in ["MLP", "SVR", "KNN", "LR", "EN"]:
            scaler_X = RobustScaler()
            scaler_y = RobustScaler()
            X_train_scaled = scaler_X.fit_transform(X_train)
            X_val_scaled = scaler_X.transform(X_val)
            y_train_scaled = scaler_y.fit_transform(y_train.values.reshape(-1, 1)).ravel()
            model.fit(X_train_scaled, y_train_scaled)
            y_pred = scaler_y.inverse_transform(model.predict(X_val_scaled).reshape(-1, 1)).ravel()
        else:
            model.fit(X_train, y_train)
            y_pred = model.predict(X_val)
        
        oof_preds[val_idx] = y_pred


    print(f"Running time: {time.time() - start:.1f} sec")
    # Calculamos el RMSE OOF
    rmse_score = np.sqrt(mean_squared_error(y, oof_preds))
    r2 = r2_score(y, oof_preds)
    print(f"OOF RMSE: {rmse_score:.2f} | R2: {r2:.2f}")
    
    return r2

In [293]:
models = {
    "XGB": XGBRegressor,
    "LBM": LGBMRegressor,
    "MLP": MLPRegressor,
    "SVR": SVR,
    "KNN": KNeighborsRegressor,
    "LR": LinearRegression,
    "RF": RandomForestRegressor,
    "CAT": CatBoostRegressor,
    "EN":  ElasticNet
}

def run_optuna(df, target, n_trials, model_name):
    results = {}

    print(f"Buscando mejores hiperparámetros para {model_name}...")
    study = optuna.create_study(direction='maximize')
    study.optimize(lambda trial: objective(trial, df, target, model_name), n_trials=n_trials, timeout= 600)
    
    print(f"\n✅ {model_name} - Mejor R2: {study.best_value:.2f}")
    print(f"📋 Parámetros: {study.best_params}\n")
    
    results[model_name] = {
        'best_params': study.best_params,
        'best_score': study.best_value,
        'study': study
    }
    return results

#df = dfs["C2X_rhown_3x3_depth_lt_1"]

# all_results = {}
n_trials = 25
# for model_name in models.keys():
#     all_results[model_name] = run_optuna(df, "Chl", n_trials, model_name)
global_results = {}

for df_name, df in dfs.items():
    print(f"🔍 Optimizando en {df_name}...")
    for model_name in models.keys():
        key = (df_name, model_name)
        result = run_optuna(df, "Chl", n_trials, model_name)
        global_results[key] = result[model_name]

[I 2025-07-11 16:08:52,346] A new study created in memory with name: no-name-b643c892-28af-4ffa-a3d5-07df1c04bcc9

🔍 Optimizando en C2RCC_rhow_5x5_depth_lt_1...
Buscando mejores hiperparámetros para XGB...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-07-11 16:09:01,324] Trial 0 finished with value: 0.6786606658483075 and parameters: {'n_estimators': 1000, 'learning_rate': 0.03363059712784438, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.7354620669213784, 'colsample_bytree': 0.926760985439751}. Best is trial 0 with value: 0.6786606658483075.

Running time: 9.0 sec
OOF RMSE: 1.97 | R2: 0.68
Fold 1

In [ ]:

with open("global_results.pkl", "wb") as f:
    pickle.dump(global_results, f)

In [286]:
global_results

{('C2RCC_rhow_5x5_depth_lt_1',
  'RF'): {'best_params': {'n_estimators': 500,
   'max_depth': 15,
   'min_samples_split': 4,
   'min_samples_leaf': 3,
   'bootstrap': False}, 'best_score': 0.6353231990874344, 'study': <optuna.study.study.Study at 0x76963bb04760>},
 ('C2RCC_rhow_5x5_depth_lt_1',
  'EN'): {'best_params': {'alpha': 2.0185768774268875,
   'l1_ratio': 0.17644243451557984}, 'best_score': 0.4064433021731192, 'study': <optuna.study.study.Study at 0x76963ba5db50>},
 ('C2X-Complex_rhown_3x3_depth_lt_1',
  'RF'): {'best_params': {'n_estimators': 500,
   'max_depth': 7,
   'min_samples_split': 6,
   'min_samples_leaf': 2,
   'bootstrap': False}, 'best_score': 0.4824625378062575, 'study': <optuna.study.study.Study at 0x76963b9c29a0>},
 ('C2X-Complex_rhown_3x3_depth_lt_1',
  'EN'): {'best_params': {'alpha': 0.4923404321333851,
   'l1_ratio': 0.0721806154716893}, 'best_score': 0.49010994246426043, 'study': <optuna.study.study.Study at 0x76963ba2e5e0>},
 ('TOA_9x9_depth_lt_1',
  'RF'): {'best_params': {'n_estimators': 500,
   'max_depth': 5,
   'min_samples_split': 2,
   'min_samples_leaf': 3,
   'bootstrap': True}, 'best_score': 0.7134186379035719, 'study': <optuna.study.study.Study at 0x76963ba326a0>},
 ('TOA_9x9_depth_lt_1',
  'EN'): {'best_params': {'alpha': 0.09719390872978613,
   'l1_ratio': 0.2421774388424941}, 'best_score': 0.15664538223733782, 'study': <optuna.study.study.Study at 0x76963ba3a460>},
 ('C2X_rhow_3x3_depth_lt_1',
  'RF'): {'best_params': {'n_estimators': 300,
   'max_depth': 5,
   'min_samples_split': 6,
   'min_samples_leaf': 3,
   'bootstrap': True}, 'best_score': 0.39653527621046913, 'study': <optuna.study.study.Study at 0x76963ba3a1f0>},
 ('C2X_rhow_3x3_depth_lt_1',
  'EN'): {'best_params': {'alpha': 0.007315543540605456,
   'l1_ratio': 0.11862006027331229}, 'best_score': 0.3935448726087031, 'study': <optuna.study.study.Study at 0x76963b9d78e0>},
 ('C2RCC_rhow_9x9_depth_lt_1',
  'RF'): {'best_params': {'n_estimators': 300,
   'max_depth': 9,
   'min_samples_split': 5,
   'min_samples_leaf': 4,
   'bootstrap': True}, 'best_score': 0.5812622288709142, 'study': <optuna.study.study.Study at 0x76963b9d7490>},
 ('C2RCC_rhow_9x9_depth_lt_1',
  'EN'): {'best_params': {'alpha': 0.00018026850420126874,
   'l1_ratio': 0.9002673084159815}, 'best_score': 0.4581437717848439, 'study': <optuna.study.study.Study at 0x76963b9c7610>},
 ('C2X-Complex_rhown_5x5_depth_lt_1',
  'RF'): {'best_params': {'n_estimators': 500,
   'max_depth': 5,
   'min_samples_split': 2,
   'min_samples_leaf': 4,
   'bootstrap': False}, 'best_score': 0.4334443143586768, 'study': <optuna.study.study.Study at 0x76963ba38f70>},
 ('C2X-Complex_rhown_5x5_depth_lt_1',
  'EN'): {'best_params': {'alpha': 0.9052815340776024,
   'l1_ratio': 0.6727056364136254}, 'best_score': 0.42859799107247143, 'study': <optuna.study.study.Study at 0x76963ba32b80>},
 ('C2X_rhown_9x9_depth_lt_1',
  'RF'): {'best_params': {'n_estimators': 500,
   'max_depth': 6,
   'min_samples_split': 2,
   'min_samples_leaf': 3,
   'bootstrap': False}, 'best_score': -0.005353542662442257, 'study': <optuna.study.study.Study at 0x76963ba32dc0>},
 ('C2X_rhown_9x9_depth_lt_1',
  'EN'): {'best_params': {'alpha': 0.2878611278651547,
   'l1_ratio': 0.8299698670695076}, 'best_score': 0.40741420077488755, 'study': <optuna.study.study.Study at 0x76963ba3ad60>},
 ('TOA_3x3_depth_lt_1',
  'RF'): {'best_params': {'n_estimators': 500,
   'max_depth': 13,
   'min_samples_split': 5,
   'min_samples_leaf': 4,
   'bootstrap': False}, 'best_score': 0.6091168663253357, 'study': <optuna.study.study.Study at 0x76963ba3aa60>},
 ('TOA_3x3_depth_lt_1',
  'EN'): {'best_params': {'alpha': 1.5213392223135067,
   'l1_ratio': 0.002378695190274893}, 'best_score': 0.1866712048415745, 'study': <optuna.study.study.Study at 0x76963ba2e940>},
 ('C2X-Complex_rhown_9x9_depth_lt_1',
  'RF'): {'best_params': {'n_estimators': 500,
   'max_depth': 12,
   'min_samples_split': 2,
   'min_samples_leaf': 2,
   'bootstrap': True}, 'best_score': 0.556745305382218, 'study': <optuna.study.study.Study at 0x76963ba2e4f0>},
 ('C2X-Complex_rhown_9x9_depth_lt_1',
  'EN'): {'best_params': {'alpha': 0.011502927832452067,
   'l1_ratio': 0.03735735386718064}, 'best_score': 0.5731093658033833, 'study': <optuna.study.study.Study at 0x76963b9d95b0>},
 ('C2X-Complex_rhow_3x3_depth_lt_1',
  'RF'): {'best_params': {'n_estimators': 500,
   'max_depth': 5,
   'min_samples_split': 4,
   'min_samples_leaf': 2,
   'bootstrap': True}, 'best_score': 0.5557084861361615, 'study': <optuna.study.study.Study at 0x76963b9d91f0>},
 ('C2X-Complex_rhow_3x3_depth_lt_1',
  'EN'): {'best_params': {'alpha': 0.030834792148540947,
   'l1_ratio': 0.896879917908149}, 'best_score': 0.4852886454514451, 'study': <optuna.study.study.Study at 0x76963b9ff5b0>},
 ('C2X_rhow_1x1_depth_lt_1',
  'RF'): {'best_params': {'n_estimators': 300,
   'max_depth': 14,
   'min_samples_split': 3,
   'min_samples_leaf': 5,
   'bootstrap': True}, 'best_score': 0.3578280904657377, 'study': <optuna.study.study.Study at 0x76963b9ffa90>},
 ('C2X_rhow_1x1_depth_lt_1',
  'EN'): {'best_params': {'alpha': 0.3405957141564692,
   'l1_ratio': 0.7426687850113083}, 'best_score': 0.35586459730020914, 'study': <optuna.study.study.Study at 0x76963b9ff5e0>},
 ('C2RCC_rhown_1x1_depth_lt_1',
  'RF'): {'best_params': {'n_estimators': 500,
   'max_depth': 14,
   'min_samples_split': 9,
   'min_samples_leaf': 3,
   'bootstrap': True}, 'best_score': 0.5542133199790913, 'study': <optuna.study.study.Study at 0x76963b9ff820>},
 ('C2RCC_rhown_1x1_depth_lt_1',
  'EN'): {'best_params': {'alpha': 0.0018436941970599184,
   'l1_ratio': 0.5828475585918957}, 'best_score': 0.4073223137803337, 'study': <optuna.study.study.Study at 0x76963b9e07f0>},
 ('C2X_rhown_1x1_depth_lt_1',
  'RF'): {'best_params': {'n_estimators': 300,
   'max_depth': 15,
   'min_samples_split': 8,
   'min_samples_leaf': 1,
   'bootstrap': True}, 'best_score': 0.36850564205031877, 'study': <optuna.study.study.Study at 0x76963b9c9a60>},
 ('C2X_rhown_1x1_depth_lt_1',
  'EN'): {'best_params': {'alpha': 0.05636312494603324,
   'l1_ratio': 0.027085433564309702}, 'best_score': 0.3589463447435043, 'study': <optuna.study.study.Study at 0x76963b9fff70>},
 ('C2RCC_rhown_9x9_depth_lt_1',
  'RF'): {'best_params': {'n_estimators': 500,
   'max_depth': 8,
   'min_samples_split': 4,
   'min_samples_leaf': 3,
   'bootstrap': True}, 'best_score': 0.6121893872150144, 'study': <optuna.study.study.Study at 0x76963b9e0dc0>},
 ('C2RCC_rhown_9x9_depth_lt_1',
  'EN'): {'best_params': {'alpha': 0.00017916653997696546,
   'l1_ratio': 0.13334744180135272}, 'best_score': 0.4823826352800551, 'study': <optuna.study.study.Study at 0x76963b989370>},
 ('C2X_rhow_5x5_depth_lt_1',
  'RF'): {'best_params': {'n_estimators': 500,
   'max_depth': 9,
   'min_samples_split': 2,
   'min_samples_leaf': 1,
   'bootstrap': True}, 'best_score': 0.4195107766348578, 'study': <optuna.study.study.Study at 0x76963b9c1100>},
 ('C2X_rhow_5x5_depth_lt_1',
  'EN'): {'best_params': {'alpha': 0.1806183924209037,
   'l1_ratio': 0.023718775438775874}, 'best_score': 0.3946904744294879, 'study': <optuna.study.study.Study at 0x76963b99ae80>},
 ('C2X_rhown_5x5_depth_lt_1',
  'RF'): {'best_params': {'n_estimators': 100,
   'max_depth': 9,
   'min_samples_split': 10,
   'min_samples_leaf': 2,
   'bootstrap': True}, 'best_score': 0.43646166703747913, 'study': <optuna.study.study.Study at 0x76963b9c2ca0>},
 ('C2X_rhown_5x5_depth_lt_1',
  'EN'): {'best_params': {'alpha': 0.03753164173907478,
   'l1_ratio': 0.43898491861968203}, 'best_score': 0.3875949977290861, 'study': <optuna.study.study.Study at 0x76963b9a8e20>},
 ('C2X_rhow_9x9_depth_lt_1',
  'RF'): {'best_params': {'n_estimators': 500,
   'max_depth': 13,
   'min_samples_split': 4,
   'min_samples_leaf': 1,
   'bootstrap': True}, 'best_score': 0.423800038923585, 'study': <optuna.study.study.Study at 0x76963ba10160>},
 ('C2X_rhow_9x9_depth_lt_1',
  'EN'): {'best_params': {'alpha': 0.00010710351239414114,
   'l1_ratio': 0.1401539421461495}, 'best_score': 0.2183432902218052, 'study': <optuna.study.study.Study at 0x76963b9ea850>},
 ('C2X_rhown_3x3_depth_lt_1',
  'RF'): {'best_params': {'n_estimators': 500,
   'max_depth': 7,
   'min_samples_split': 9,
   'min_samples_leaf': 3,
   'bootstrap': True}, 'best_score': 0.41389768689573836, 'study': <optuna.study.study.Study at 0x76963b9c9eb0>},
 ('C2X_rhown_3x3_depth_lt_1',
  'EN'): {'best_params': {'alpha': 0.024435965023411704,
   'l1_ratio': 0.45079524670779914}, 'best_score': 0.4005957179816009, 'study': <optuna.study.study.Study at 0x76963b9c1d60>},
 ('C2RCC_rhown_5x5_depth_lt_1',
  'RF'): {'best_params': {'n_estimators': 100,
   'max_depth': 11,
   'min_samples_split': 8,
   'min_samples_leaf': 1,
   'bootstrap': True}, 'best_score': 0.6328761912214957, 'study': <optuna.study.study.Study at 0x76963b9eafd0>},
 ('C2RCC_rhown_5x5_depth_lt_1',
  'EN'): {'best_params': {'alpha': 0.19795464985206312,
   'l1_ratio': 0.5760881284254676}, 'best_score': 0.5001870385029592, 'study': <optuna.study.study.Study at 0x76963b982700>},
 ('TOA_1x1_depth_lt_1',
  'RF'): {'best_params': {'n_estimators': 300,
   'max_depth': 5,
   'min_samples_split': 10,
   'min_samples_leaf': 3,
   'bootstrap': True}, 'best_score': 0.6134343928793133, 'study': <optuna.study.study.Study at 0x76963b982430>},
 ('TOA_1x1_depth_lt_1',
  'EN'): {'best_params': {'alpha': 0.0005401520280959581,
   'l1_ratio': 0.9102846686200694}, 'best_score': 0.005611499553546895, 'study': <optuna.study.study.Study at 0x76963b982250>},
 ('C2X-Complex_rhow_5x5_depth_lt_1',
  'RF'): {'best_params': {'n_estimators': 500,
   'max_depth': 13,
   'min_samples_split': 7,
   'min_samples_leaf': 2,
   'bootstrap': True}, 'best_score': 0.5110714610582543, 'study': <optuna.study.study.Study at 0x76963b9a37c0>},
 ('C2X-Complex_rhow_5x5_depth_lt_1',
  'EN'): {'best_params': {'alpha': 1.9060493790486415,
   'l1_ratio': 0.04718718383645659}, 'best_score': 0.4556306396143318, 'study': <optuna.study.study.Study at 0x76963b9a32e0>},
 ('C2X-Complex_rhow_9x9_depth_lt_1',
  'RF'): {'best_params': {'n_estimators': 100,
   'max_depth': 6,
   'min_samples_split': 2,
   'min_samples_leaf': 4,
   'bootstrap': True}, 'best_score': 0.5688085259205904, 'study': <optuna.study.study.Study at 0x76963b9a30a0>},
 ('C2X-Complex_rhow_9x9_depth_lt_1',
  'EN'): {'best_params': {'alpha': 0.0036815406547214993,
   'l1_ratio': 0.7457449371404596}, 'best_score': 0.524159077637046, 'study': <optuna.study.study.Study at 0x76963b98a040>},
 ('C2X-Complex_rhow_1x1_depth_lt_1',
  'RF'): {'best_params': {'n_estimators': 500,
   'max_depth': 10,
   'min_samples_split': 10,
   'min_samples_leaf': 2,
   'bootstrap': False}, 'best_score': 0.22294089117384652, 'study': <optuna.study.study.Study at 0x76963b9a8490>},
 ('C2X-Complex_rhow_1x1_depth_lt_1',
  'EN'): {'best_params': {'alpha': 0.3538449492823126,
   'l1_ratio': 0.2795848962499574}, 'best_score': 0.35045712689989184, 'study': <optuna.study.study.Study at 0x76963b9a1400>},
 ('C2X-Complex_rhown_1x1_depth_lt_1',
  'RF'): {'best_params': {'n_estimators': 300,
   'max_depth': 15,
   'min_samples_split': 6,
   'min_samples_leaf': 3,
   'bootstrap': False}, 'best_score': -0.03343486756213432, 'study': <optuna.study.study.Study at 0x76963b9a1040>},
 ('C2X-Complex_rhown_1x1_depth_lt_1',
  'EN'): {'best_params': {'alpha': 0.0041019071451971045,
   'l1_ratio': 0.4083037350405967}, 'best_score': 0.4644962649504307, 'study': <optuna.study.study.Study at 0x76963b989c10>},
 ('C2RCC_rhow_3x3_depth_lt_1',
  'RF'): {'best_params': {'n_estimators': 100,
   'max_depth': 9,
   'min_samples_split': 5,
   'min_samples_leaf': 4,
   'bootstrap': True}, 'best_score': 0.6027230291679768, 'study': <optuna.study.study.Study at 0x76963b98ad90>},
 ('C2RCC_rhow_3x3_depth_lt_1',
  'EN'): {'best_params': {'alpha': 1.098188505689708,
   'l1_ratio': 0.31878701776814256}, 'best_score': 0.42483014408490505, 'study': <optuna.study.study.Study at 0x76963b943640>},
 ('TOA_5x5_depth_lt_1',
  'RF'): {'best_params': {'n_estimators': 300,
   'max_depth': 9,
   'min_samples_split': 5,
   'min_samples_leaf': 3,
   'bootstrap': True}, 'best_score': 0.6468333072432157, 'study': <optuna.study.study.Study at 0x76963b9439a0>},
 ('TOA_5x5_depth_lt_1',
  'EN'): {'best_params': {'alpha': 0.02900497993386982,
   'l1_ratio': 0.8452327215888115}, 'best_score': 0.061485214553012923, 'study': <optuna.study.study.Study at 0x76963b9bc7c0>},
 ('C2RCC_rhown_3x3_depth_lt_1',
  'RF'): {'best_params': {'n_estimators': 100,
   'max_depth': 14,
   'min_samples_split': 3,
   'min_samples_leaf': 3,
   'bootstrap': True}, 'best_score': 0.61832577091425, 'study': <optuna.study.study.Study at 0x76963b9bcc10>},
 ('C2RCC_rhown_3x3_depth_lt_1',
  'EN'): {'best_params': {'alpha': 0.00044112777670774487,
   'l1_ratio': 0.5603345920388918}, 'best_score': 0.20783985377282477, 'study': <optuna.study.study.Study at 0x76963b9a34c0>},
 ('C2RCC_rhow_1x1_depth_lt_1',
  'RF'): {'best_params': {'n_estimators': 300,
   'max_depth': 15,
   'min_samples_split': 7,
   'min_samples_leaf': 3,
   'bootstrap': True}, 'best_score': 0.5400907432563182, 'study': <optuna.study.study.Study at 0x76963b943d60>},
 ('C2RCC_rhow_1x1_depth_lt_1',
  'EN'): {'best_params': {'alpha': 0.05995285032187487,
   'l1_ratio': 0.07444013803210037}, 'best_score': 0.4907918030289331, 'study': <optuna.study.study.Study at 0x76963b9af1c0>}}

In [287]:
from collections import defaultdict
import pandas as pd

# Recolectar todos los mejores parámetros por modelo
param_values = defaultdict(list)

for (df_name, model_name), result in global_results.items():
    param_values[model_name].append(result['best_params'])

# Convertir cada grupo de parámetros en DataFrame
avg_params = {}

for model_name, param_list in param_values.items():
    df_params = pd.DataFrame(param_list)
    # Calcular media solo de los parámetros numéricos
    df_mean = df_params.select_dtypes(include='number').mean().to_dict()
    
    # Para categóricos: tomamos la moda (más frecuente)
    df_cat = df_params.select_dtypes(exclude='number').mode().iloc[0].to_dict()
    
    # Juntamos ambos
    avg_params[model_name] = {**df_mean, **df_cat}

IndexError: single positional indexer is out-of-bounds

In [55]:
model_names = ["XGB", "LBM"]
n_trials = 20
results = run_optuna(train, "Chl", n_trials, model_names)

[I 2025-06-24 12:22:47,253] A new study created in memory with name: no-name-fa720214-6f8c-4099-99f4-edf6841d7c5d

Buscando mejores hiperparámetros para XGB...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-06-24 12:22:49,621] Trial 0 finished with value: 2.6402744486891083 and parameters: {'n_estimators': 1000, 'learning_rate': 0.010250582517387313, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.6149501746489763, 'colsample_bytree': 0.612993571753984}. Best is trial 0 with value: 2.6402744486891083.

Running time: 2.4 sec
OOF RMSE: 2.6403
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-06-24 12:22:54,496] Trial 1 finished with value: 2.6551140502554027 and parameters: {'n_estimators': 1000, 'learning_rate': 0.006437532229785393, 'max_depth': 8, 'min_child_weight': 3, 'subsample': 0.9780500815920048, 'colsample_bytree': 0.7647705570506433}. Best is trial 0 with value: 2.6402744486891083.

Running time: 4.9 sec
OOF RMSE: 2.6551
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-06-24 12:22:56,555] Trial 2 finished with value: 2.6821809959946346 and parameters: {'n_estimators': 500, 'learning_rate': 0.036295417660052856, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.8997804333162291, 'colsample_bytree': 0.8183208314687155}. Best is trial 0 with value: 2.6402744486891083.

Running time: 2.1 sec
OOF RMSE: 2.6822
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-06-24 12:22:58,449] Trial 3 finished with value: 2.6261139770665527 and parameters: {'n_estimators': 1000, 'learning_rate': 0.07567669726198281, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.8569616490502185, 'colsample_bytree': 0.8655529356133367}. Best is trial 3 with value: 2.6261139770665527.

Fold 5
Running time: 1.9 sec
OOF RMSE: 2.6261
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-06-24 12:22:59,787] Trial 4 finished with value: 2.713462049979826 and parameters: {'n_estimators': 2000, 'learning_rate': 0.028874591978922722, 'max_depth': 8, 'min_child_weight': 4, 'subsample': 0.7972433167859954, 'colsample_bytree': 0.7991186915448727}. Best is trial 3 with value: 2.6261139770665527.

Fold 5
Running time: 1.3 sec
OOF RMSE: 2.7135
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-06-24 12:23:03,935] Trial 5 finished with value: 2.615317857131312 and parameters: {'n_estimators': 500, 'learning_rate': 0.014547838246409157, 'max_depth': 8, 'min_child_weight': 1, 'subsample': 0.7602676884959991, 'colsample_bytree': 0.7782678563025162}. Best is trial 5 with value: 2.615317857131312.

Running time: 4.1 sec
OOF RMSE: 2.6153
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-06-24 12:23:07,407] Trial 6 finished with value: 2.6127332105798087 and parameters: {'n_estimators': 2000, 'learning_rate': 0.01127604719707619, 'max_depth': 8, 'min_child_weight': 3, 'subsample': 0.9485263327519621, 'colsample_bytree': 0.6483401568533559}. Best is trial 6 with value: 2.6127332105798087.

Running time: 3.5 sec
OOF RMSE: 2.6127
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-06-24 12:23:15,193] Trial 7 finished with value: 2.613372092967531 and parameters: {'n_estimators': 2000, 'learning_rate': 0.005811292316513637, 'max_depth': 8, 'min_child_weight': 1, 'subsample': 0.9239669782633102, 'colsample_bytree': 0.8200968385800755}. Best is trial 6 with value: 2.6127332105798087.

Running time: 7.8 sec
OOF RMSE: 2.6134
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-06-24 12:23:16,448] Trial 8 finished with value: 2.728750756259754 and parameters: {'n_estimators': 1000, 'learning_rate': 0.09829942571767503, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.9307910948388916, 'colsample_bytree': 0.6029347129451597}. Best is trial 6 with value: 2.6127332105798087.

Fold 5
Running time: 1.3 sec
OOF RMSE: 2.7288
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-06-24 12:23:18,460] Trial 9 finished with value: 2.620851442686234 and parameters: {'n_estimators': 2000, 'learning_rate': 0.014792261786147442, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.7380178684577196, 'colsample_bytree': 0.9766215000521102}. Best is trial 6 with value: 2.6127332105798087.

Fold 5
Running time: 2.0 sec
OOF RMSE: 2.6209
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-06-24 12:23:19,755] Trial 10 finished with value: 2.6676792302783943 and parameters: {'n_estimators': 2000, 'learning_rate': 0.04867288549271965, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.9952194426325786, 'colsample_bytree': 0.6883061174280276}. Best is trial 6 with value: 2.6127332105798087.

Fold 5
Running time: 1.3 sec
OOF RMSE: 2.6677
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-06-24 12:23:32,479] Trial 11 finished with value: 2.5861375238851174 and parameters: {'n_estimators': 2000, 'learning_rate': 0.005038520390145823, 'max_depth': 8, 'min_child_weight': 1, 'subsample': 0.8658250277664441, 'colsample_bytree': 0.907105544104575}. Best is trial 11 with value: 2.5861375238851174.

Running time: 12.7 sec
OOF RMSE: 2.5861
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-06-24 12:23:35,979] Trial 12 finished with value: 2.691656350102549 and parameters: {'n_estimators': 2000, 'learning_rate': 0.00902245863996426, 'max_depth': 8, 'min_child_weight': 3, 'subsample': 0.8419278580781034, 'colsample_bytree': 0.9542017429525549}. Best is trial 11 with value: 2.5861375238851174.

Running time: 3.5 sec
OOF RMSE: 2.6917
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-06-24 12:23:39,326] Trial 13 finished with value: 2.608288291740057 and parameters: {'n_estimators': 2000, 'learning_rate': 0.018071374063423424, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.863600806369081, 'colsample_bytree': 0.9059095420633456}. Best is trial 11 with value: 2.5861375238851174.

Running time: 3.3 sec
OOF RMSE: 2.6083
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-06-24 12:23:41,769] Trial 14 finished with value: 2.610572586464634 and parameters: {'n_estimators': 2000, 'learning_rate': 0.02338911427759606, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.8603565263431331, 'colsample_bytree': 0.9168857472658908}. Best is trial 11 with value: 2.5861375238851174.

Fold 5
Running time: 2.4 sec
OOF RMSE: 2.6106
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-06-24 12:23:47,935] Trial 15 finished with value: 2.6050801971068847 and parameters: {'n_estimators': 2000, 'learning_rate': 0.005080702701572969, 'max_depth': 6, 'min_child_weight': 1, 'subsample': 0.691602783480446, 'colsample_bytree': 0.887144630886142}. Best is trial 11 with value: 2.5861375238851174.

Running time: 6.2 sec
OOF RMSE: 2.6051
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-06-24 12:23:50,408] Trial 16 finished with value: 2.6995719442425403 and parameters: {'n_estimators': 500, 'learning_rate': 0.00523603071250709, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.6693696317143784, 'colsample_bytree': 0.8740991969015772}. Best is trial 11 with value: 2.5861375238851174.

Running time: 2.5 sec
OOF RMSE: 2.6996
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-06-24 12:23:56,333] Trial 17 finished with value: 2.594997505583282 and parameters: {'n_estimators': 2000, 'learning_rate': 0.00734065986694599, 'max_depth': 6, 'min_child_weight': 1, 'subsample': 0.6996198953925541, 'colsample_bytree': 0.9912777671401467}. Best is trial 11 with value: 2.5861375238851174.

Running time: 5.9 sec
OOF RMSE: 2.5950
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-06-24 12:24:01,086] Trial 18 finished with value: 2.6012067864248785 and parameters: {'n_estimators': 2000, 'learning_rate': 0.008165684951555343, 'max_depth': 6, 'min_child_weight': 1, 'subsample': 0.7047533675215372, 'colsample_bytree': 0.9931934564966513}. Best is trial 11 with value: 2.5861375238851174.

Running time: 4.8 sec
OOF RMSE: 2.6012
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-06-24 12:24:05,364] Trial 19 finished with value: 2.6731102193968486 and parameters: {'n_estimators': 500, 'learning_rate': 0.007418912442318321, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.6013521516321941, 'colsample_bytree': 0.9431805205817451}. Best is trial 11 with value: 2.5861375238851174.
[I 2025-06-24 12:24:05,366] A new study created in memory with name: no-name-7f35e8ca-83c5-4a38-b84d-90630a32ffa5
[I 2025-06-24 12:24:05,513] Trial 0 finished with value: 2.9435736995853055 and parameters: {'learning_rate': 0.05288946352740371, 'num_leaves': 60, 'max_depth': 7, 'min_child_samples': 7, 'subsample': 0.7572063973783191, 'colsample_bytree': 0.6455858740832475, 'n_estimators': 2000}. Best is trial 0 with value: 2.9435736995853055.

Running time: 4.3 sec
OOF RMSE: 2.6731

✅ XGB - Mejor RMSLE: 2.5861
📋 Parámetros: {'n_estimators': 2000, 'learning_rate': 0.005038520390145823, 'max_depth': 8, 'min_child_weight': 1, 'subsample': 0.8658250277664441, 'colsample_bytree': 0.907105544104575}

Buscando mejores hiperparámetros para LBM...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.9436
Fold 1
Fold 2

[I 2025-06-24 12:24:05,756] Trial 1 finished with value: 2.887572864162134 and parameters: {'learning_rate': 0.009604754272633844, 'num_leaves': 80, 'max_depth': 6, 'min_child_samples': 8, 'subsample': 0.8710544073618645, 'colsample_bytree': 0.7055438621790793, 'n_estimators': 500}. Best is trial 1 with value: 2.887572864162134.

Fold 3
Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 2.8876
Fold 1
Fold 2

[I 2025-06-24 12:24:05,860] Trial 2 finished with value: 2.8184225340727114 and parameters: {'learning_rate': 0.07574871844118981, 'num_leaves': 40, 'max_depth': 8, 'min_child_samples': 12, 'subsample': 0.6069396225400716, 'colsample_bytree': 0.7061043972712124, 'n_estimators': 500}. Best is trial 2 with value: 2.8184225340727114.

Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.8184
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-06-24 12:24:06,039] Trial 3 finished with value: 2.7061905004636415 and parameters: {'learning_rate': 0.02150052608370486, 'num_leaves': 100, 'max_depth': 5, 'min_child_samples': 30, 'subsample': 0.7745410029575505, 'colsample_bytree': 0.7448381049433551, 'n_estimators': 500}. Best is trial 3 with value: 2.7061905004636415.

Fold 5
Running time: 0.2 sec
OOF RMSE: 2.7062
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-06-24 12:24:06,319] Trial 4 finished with value: 2.84590632079738 and parameters: {'learning_rate': 0.007257439910812682, 'num_leaves': 100, 'max_depth': 8, 'min_child_samples': 11, 'subsample': 0.9376678973618735, 'colsample_bytree': 0.9330056687208195, 'n_estimators': 2000}. Best is trial 3 with value: 2.7061905004636415.

Fold 5
Running time: 0.3 sec
OOF RMSE: 2.8459
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-06-24 12:24:06,625] Trial 5 finished with value: 2.6874185962418538 and parameters: {'learning_rate': 0.03069069018267327, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 24, 'subsample': 0.756559578718071, 'colsample_bytree': 0.981254288289675, 'n_estimators': 2000}. Best is trial 5 with value: 2.6874185962418538.
[I 2025-06-24 12:24:06,797] Trial 6 finished with value: 2.70597549610142 and parameters: {'learning_rate': 0.03507752042499887, 'num_leaves': 60, 'max_depth': 5, 'min_child_samples': 23, 'subsample': 0.7051922505123183, 'colsample_bytree': 0.7938721655585548, 'n_estimators': 500}. Best is trial 5 with value: 2.6874185962418538.

Fold 5
Running time: 0.3 sec
OOF RMSE: 2.6874
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 2.7060
Fold 1

[I 2025-06-24 12:24:06,980] Trial 7 finished with value: 2.7266569650203865 and parameters: {'learning_rate': 0.02114330801978341, 'num_leaves': 40, 'max_depth': 7, 'min_child_samples': 6, 'subsample': 0.7343304199643446, 'colsample_bytree': 0.7499822347492404, 'n_estimators': 2000}. Best is trial 5 with value: 2.6874185962418538.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 2.7267
Fold 1
Fold 2
Fold 3

[I 2025-06-24 12:24:07,142] Trial 8 finished with value: 2.7056442062856987 and parameters: {'learning_rate': 0.07024014438061067, 'num_leaves': 100, 'max_depth': 8, 'min_child_samples': 26, 'subsample': 0.6305435833071508, 'colsample_bytree': 0.8805261154113829, 'n_estimators': 500}. Best is trial 5 with value: 2.6874185962418538.
[I 2025-06-24 12:24:07,236] Trial 9 finished with value: 2.8586153376040553 and parameters: {'learning_rate': 0.05323324539959722, 'num_leaves': 60, 'max_depth': 5, 'min_child_samples': 11, 'subsample': 0.6947703471006734, 'colsample_bytree': 0.8314920857744387, 'n_estimators': 1000}. Best is trial 5 with value: 2.6874185962418538.

Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 2.7056
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.8586
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-06-24 12:24:07,574] Trial 10 finished with value: 2.73652380179127 and parameters: {'learning_rate': 0.011207670907665654, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 19, 'subsample': 0.8365318751653104, 'colsample_bytree': 0.9928797491931961, 'n_estimators': 1000}. Best is trial 5 with value: 2.6874185962418538.
[I 2025-06-24 12:24:07,719] Trial 11 finished with value: 2.6523885863923535 and parameters: {'learning_rate': 0.08933589129532095, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 27, 'subsample': 0.6011289390155303, 'colsample_bytree': 0.8961713183846663, 'n_estimators': 2000}. Best is trial 11 with value: 2.6523885863923535.

Fold 5
Running time: 0.3 sec
OOF RMSE: 2.7365
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.6524
Fold 1

[I 2025-06-24 12:24:07,865] Trial 12 finished with value: 2.688014576770715 and parameters: {'learning_rate': 0.09518824530735312, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 23, 'subsample': 0.9562032780060272, 'colsample_bytree': 0.986584300780503, 'n_estimators': 2000}. Best is trial 11 with value: 2.6523885863923535.

Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.1 sec
OOF RMSE: 2.6880
Fold 1
Fold 2
Fold 3

[I 2025-06-24 12:24:08,025] Trial 13 finished with value: 2.714132381915793 and parameters: {'learning_rate': 0.033719202589652504, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 30, 'subsample': 0.665436861730937, 'colsample_bytree': 0.9017093732608532, 'n_estimators': 2000}. Best is trial 11 with value: 2.6523885863923535.

Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 2.7141
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-06-24 12:24:08,269] Trial 14 finished with value: 2.7302843004132713 and parameters: {'learning_rate': 0.014799284888684074, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 18, 'subsample': 0.8188358102797795, 'colsample_bytree': 0.9405840021737804, 'n_estimators': 2000}. Best is trial 11 with value: 2.6523885863923535.

Fold 5
Running time: 0.2 sec
OOF RMSE: 2.7303
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-06-24 12:24:08,500] Trial 15 finished with value: 2.7050927396705644 and parameters: {'learning_rate': 0.03392854732333659, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 26, 'subsample': 0.913400176709108, 'colsample_bytree': 0.8666019149873319, 'n_estimators': 2000}. Best is trial 11 with value: 2.6523885863923535.
[I 2025-06-24 12:24:08,652] Trial 16 finished with value: 2.7210139010946017 and parameters: {'learning_rate': 0.044515843480382795, 'num_leaves': 80, 'max_depth': 7, 'min_child_samples': 22, 'subsample': 0.6525867431728067, 'colsample_bytree': 0.9529687725260358, 'n_estimators': 2000}. Best is trial 11 with value: 2.6523885863923535.

Fold 5
Running time: 0.2 sec
OOF RMSE: 2.7051
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Running time: 0.2 sec
OOF RMSE: 2.7210
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-06-24 12:24:08,989] Trial 17 finished with value: 2.678404424299871 and parameters: {'learning_rate': 0.015335494988185795, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 27, 'subsample': 0.8785621019206835, 'colsample_bytree': 0.8281419678660219, 'n_estimators': 1000}. Best is trial 11 with value: 2.6523885863923535.

Fold 5
Running time: 0.3 sec
OOF RMSE: 2.6784
Fold 1
Fold 2
Fold 3

[I 2025-06-24 12:24:09,456] Trial 18 finished with value: 2.7875795003296453 and parameters: {'learning_rate': 0.005596380240543389, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 15, 'subsample': 0.9879610090915855, 'colsample_bytree': 0.8125020591488976, 'n_estimators': 1000}. Best is trial 11 with value: 2.6523885863923535.

Fold 4
Fold 5
Running time: 0.5 sec
OOF RMSE: 2.7876
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-06-24 12:24:09,798] Trial 19 finished with value: 2.6784534814223617 and parameters: {'learning_rate': 0.015045130475019163, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 27, 'subsample': 0.8784043880020499, 'colsample_bytree': 0.855483063357705, 'n_estimators': 1000}. Best is trial 11 with value: 2.6523885863923535.

Fold 5
Running time: 0.3 sec
OOF RMSE: 2.6785

✅ LBM - Mejor RMSLE: 2.6524
📋 Parámetros: {'learning_rate': 0.08933589129532095, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 27, 'subsample': 0.6011289390155303, 'colsample_bytree': 0.8961713183846663, 'n_estimators': 2000}

In [56]:
results

{'XGB': {'best_params': {'n_estimators': 2000,
   'learning_rate': 0.005038520390145823,
   'max_depth': 8,
   'min_child_weight': 1,
   'subsample': 0.8658250277664441,
   'colsample_bytree': 0.907105544104575},
  'best_score': 2.5861375238851174,
  'study': <optuna.study.study.Study at 0x705cdee95c70>},
 'LBM': {'best_params': {'learning_rate': 0.08933589129532095,
   'num_leaves': 20,
   'max_depth': 7,
   'min_child_samples': 27,
   'subsample': 0.6011289390155303,
   'colsample_bytree': 0.8961713183846663,
   'n_estimators': 2000},
  'best_score': 2.6523885863923535,
  'study': <optuna.study.study.Study at 0x705cdeddeb50>}}

In [30]:
#best_params = {'n_estimators': 2000, 'learning_rate': 0.04814113153747816, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.9437728415677074, 'colsample_bytree': 0.909668290806239}
# {'n_estimators': 1000, 'learning_rate': 0.010767242978932143, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.8684177755167737, 'colsample_bytree': 0.7303912217157997}
# {'n_estimators': 1000, 'learning_rate': 0.014410895948871282, 'max_depth': 8, 'min_child_weight': 1, 'subsample': 0.9990473761909979, 'colsample_bytree': 0.86335191588344}

#{'learning_rate': 0.08933589129532095, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 27, 'subsample': 0.6011289390155303, 'colsample_bytree': 0.8961713183846663, 'n_estimators': 2000}
best_params_xgb = {'n_estimators': 1000, 'learning_rate': 0.012, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.95, 'colsample_bytree': 0.85}
best_params_lbm = {'learning_rate': 0.089, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 27, 'subsample': 0.60, 'colsample_bytree': 0.89, 'n_estimators': 2000}

In [18]:
params_xgb= {
    'n_estimators': 1000,
    'learning_rate': 0.012,
    'max_depth': 7,
    'min_child_weight': 1,
    'subsample': 0.95,
    'colsample_bytree': 0.85,
    'device': 'cpu',
    'objective': 'reg:squarederror',
    'tree_method': 'hist',
    'enable_categorical': True,
    'early_stopping_rounds': 50,
    'eval_metric': 'rmse'}

params_lbm = {
    'learning_rate': 0.089,
    'num_leaves': 20,
    'max_depth': 7,
    'min_child_samples': 27,
    'subsample': 0.6,
    'colsample_bytree': 0.89,
    'n_estimators': 2000,
    'objective': 'regression',
    'metric': 'rmse',
    'boosting_type': 'gbdt',
    'device': 'cpu',  
    'verbosity': -1,
    'early_stopping_rounds': 50}

### Entrenamiento XGB y LBM

In [41]:
save_folder = "training_results"
FOLDS = 5
kf = KFold(n_splits=FOLDS, shuffle=True, random_state=42)

models = {
    'LightGBM': LGBMRegressor(**params_lbm),
    'XGBoost': XGBRegressor(**params_xgb)
}
models_storage = {name: [] for name in models}

results = {name: {'oof': np.zeros(len(train)), 'pred': np.zeros(len(test)), 'rmse': [], 'r2': [], 'r2_tfg' : []} for name in models}

target = "Chl"
X = train.drop(columns=[target, 'High_Chl'])
X_test = test.drop(columns=[target, 'High_Chl'])
y = train[target]
y_class = train["High_Chl"]

    
# Definimos los folds
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

for name, model in models.items():
    print(f"\n=== Training {name} ===")
    for i, (train_idx, valid_idx) in enumerate(skf.split(X, y_class)):
        print(f"\nFold {i+1}")
        x_train, y_train = X.iloc[train_idx], y[train_idx]
        x_valid, y_valid = X.iloc[valid_idx], y[valid_idx]
        
        start = time.time()
        
        if name == 'XGBoost':
            model.fit(x_train, y_train, eval_set=[(x_valid, y_valid)], verbose=500)
        elif name == 'LightGBM':
            model.fit(x_train, y_train, eval_set=[(x_valid, y_valid)])

        models_storage[name].append(model)
        oof_pred = model.predict(x_valid)
        test_pred = model.predict(X_test)
        
        results[name]['oof'][valid_idx] = oof_pred
        results[name]['pred'] += test_pred / FOLDS
        
        rmse = np.sqrt(mean_squared_error(y_valid, oof_pred))
        r2 = r2_score(y_valid, oof_pred)

        results[name]['rmse'].append(rmse)
        results[name]['r2'].append(r2)

        
        print(f"Fold {i+1} RMSE: {rmse:.2f} | R2: {r2:.2f} | R2_TFG {r2_corr:.2f}")
        print(f"Training time: {time.time() - start:.1f} sec")
    


print("\n=== Model Comparison ===")
for name in models:
    mean_rmse = np.mean(results[name]['rmse'])
    std_rmse = np.std(results[name]['rmse'])
    print(f"{name} - Mean RMSE: {mean_rmse:.2f} ± {std_rmse:.2f}")
    mean_r2 = np.mean(results[name]['r2'])
    std_r2 = np.std(results[name]['r2'])
    print(f"{name} - Mean R2: {mean_r2:.2f} ± {std_r2:.2f}")

=== Training LightGBM ===

Fold 1
Fold 1 RMSE: 2.99 | R2: 0.48 | R2_TFG 0.53
Training time: 0.0 sec

Fold 2
Fold 2 RMSE: 2.44 | R2: 0.35 | R2_TFG 0.37
Training time: 0.0 sec

Fold 3
Fold 3 RMSE: 2.89 | R2: 0.50 | R2_TFG 0.58
Training time: 0.0 sec

Fold 4
Fold 4 RMSE: 2.41 | R2: 0.57 | R2_TFG 0.58
Training time: 0.1 sec

Fold 5
Fold 5 RMSE: 2.58 | R2: 0.35 | R2_TFG 0.36
Training time: 0.0 sec

=== Training XGBoost ===

Fold 1
[0]	validation_0-rmse:4.14220
[427]	validation_0-rmse:3.18872
Fold 1 RMSE: 3.19 | R2: 0.41 | R2_TFG 0.42
Training time: 3.7 sec

Fold 2
[0]	validation_0-rmse:3.04737
[123]	validation_0-rmse:2.57395
Fold 2 RMSE: 2.53 | R2: 0.31 | R2_TFG 0.31
Training time: 1.3 sec

Fold 3
[0]	validation_0-rmse:4.08089
[500]	validation_0-rmse:2.66474
[999]	validation_0-rmse:2.65590
Fold 3 RMSE: 2.66 | R2: 0.58 | R2_TFG 0.65
Training time: 8.5 sec

Fold 4
[0]	validation_0-rmse:3.65318
[500]	validation_0-rmse:1.98663
[999]	validation_0-rmse:1.97681
Fold 4 RMSE: 1.98 | R2: 0.71 | R2_TFG 0.71
Training time: 8.6 sec

Fold 5
[0]	validation_0-rmse:3.18402
[124]	validation_0-rmse:2.81527
Fold 5 RMSE: 2.69 | R2: 0.29 | R2_TFG 0.29
Training time: 0.8 sec

=== Model Comparison ===
LightGBM - Mean RMSE: 2.66 ± 0.24
LightGBM - Mean R2: 0.45 ± 0.09
LightGBM - Mean R2: 0.48 ± 0.10
XGBoost - Mean RMSE: 2.61 ± 0.39
XGBoost - Mean R2: 0.46 ± 0.16
XGBoost - Mean R2: 0.48 ± 0.17

In [60]:
xgb_preds = np.load("training_results/XGBoost_pred.npy")
y_test = test[target]

rmse = np.sqrt(mean_squared_error(y_test, xgb_preds))
r2 = r2_score(y_test, xgb_preds)

print(f"XGB - Test RMSE: {rmse:.2f} | Test R2: {r2:.2f}")

lbm_preds = np.load("training_results/LightGBM_pred.npy")
y_test = test[target]

rmse = np.sqrt(mean_squared_error(y_test, lbm_preds))
r2 = r2_score(y_test, lbm_preds)

print(f"LBM - Test RMSE: {rmse:.2f} | Test R2: {r2:.2f}")

XGB - Test RMSE: 3.20 | Test R2: 0.54
LBM - Test RMSE: 3.48 | Test R2: 0.46

In [61]:
oof_xgb = np.load("training_results/XGBoost_oof.npy")
oof_lbm = np.load("training_results/LightGBM_oof.npy")
#oof_nn = np.load("NN_oof.npy")
pred_xgb = np.load("training_results/XGBoost_pred.npy")
pred_lbm = np.load("training_results/LightGBM_pred.npy")
#pred_nn = np.load("NN_pred.npy")

In [62]:
results = {
    'XGB': {'oof': oof_xgb, 'pred': pred_xgb},
    'LBM': {'oof': oof_lbm, 'pred': pred_lbm},   
    #'MLP': {'oof': oof_nn, 'pred': pred_nn},
}

In [64]:
oof_preds = {name: results[name]['oof'] for name in results}
test_preds = {name: results[name]['pred'] for name in results}
y_true = y

In [65]:
meta_X = np.vstack([oof_preds["XGB"], oof_preds["LBM"]]).T
meta_y = y_true  # target original

# Luego entrenar un meta-modelo
from sklearn.linear_model import Ridge
meta_model = Ridge().fit(meta_X, meta_y)
rmse = np.sqrt(mean_squared_error(meta_y, meta_model.predict(meta_X)))
r2 = r2_score(meta_y, meta_model.predict(meta_X))
print(f"RMSE: {rmse:.2f} | R2: {r2:.2f}")

RMSE: 2.55 | R2: 0.52

In [66]:
meta_X_test = np.vstack([test_preds["XGB"], test_preds["LBM"]]).T
test_pred = meta_model.predict(meta_X_test)
rmse = np.sqrt(mean_squared_error(y_test, test_pred))
r2 = r2_score(y_test, test_pred)
print(f"RMSE: {rmse:.2f} | R2: {r2:.2f}")

RMSE: 3.22 | R2: 0.54

### TabPFN

In [1]:
from tabpfn import TabPFNRegressor

ImportError: cannot import name 'TabPFNRegressor' from 'tabpfn' (/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/tabpfn/__init__.py)

In [69]:
X_train = train.drop(columns=[target, 'High_Chl'])
X_test = test.drop(columns=[target, 'High_Chl'])
y = train[target]
y_test = test[target]

,rhow_B1,rhow_B2,rhow_B4,rhow_B5,Band_15,dif_norm_rhow_B2_B3,dif_inv_rhow_B2_B3,dif_norm_rhow_B2_B4,dif_inv_rhow_B2_B4,dif_norm_rhow_B3_B4,...,dif_rel_4bands_rhow_B3_B4_B5_B2,sum_norm_3bands_rhow_B2_B4_B3,sum_norm_3bands_rhow_B3_B5_B4,dall_gitelson_rhown_B3_B4_B5,dif_norm_4_bands_rhown_B4_B5_B2_B3,sum_norm_3bands_rhown_B3_B5_B4,Chl,High_Chl,Season,Zone
0,0.020469,0.031289,0.011193,0.007345,0.147099,-0.079,4.681,0.473,-57.385,0.532,...,3.040,0.625,0.920,-0.466,0.054,0.923,0.4995,False,Verano,Zona-4
1,0.009607,0.021231,0.010398,0.007248,0.115210,-0.313,22.437,0.342,-49.068,0.592,...,3.558,0.512,0.938,-0.527,0.049,0.940,1.6950,False,Primavera,Zona-3
2,0.009486,0.020363,0.015713,0.011596,0.166120,-0.352,25.583,0.129,-14.534,0.460,...,2.136,0.574,0.929,-0.478,0.061,0.934,2.9870,False,Primavera,Zona-3
3,0.004488,0.011016,0.008279,0.006037,0.088587,-0.372,49.260,0.142,-30.012,0.488,...,2.361,0.550,0.931,-0.483,0.062,0.932,2.4695,False,Primavera,Zona-1
4,0.001168,0.003506,0.001086,0.000560,0.000027,-0.323,139.403,0.527,-635.927,0.727,...,6.156,0.443,0.934,-0.484,0.042,0.944,0.6580,False,Otoño,Zona-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
331,0.006617,0.012153,0.002676,0.001761,0.035969,-0.001,0.211,0.639,-291.347,0.640,...,4.408,0.609,0.938,-0.556,0.031,0.948,0.5110,False,Primavera,Zona-2
332,0.010938,0.015758,0.009683,0.007627,0.216871,-0.166,18.093,0.239,-39.821,0.390,...,1.793,0.673,0.935,-0.445,0.053,0.937,0.4490,False,Otoño,Zona-2
333,0.001308,0.004138,0.001208,0.000618,0.000027,-0.327,119.011,0.548,-585.858,0.742,...,6.597,0.435,0.937,-0.488,0.039,0.948,0.3030,False,Primavera,Zona-1
334,0.003544,0.010456,0.027829,0.024688,0.332638,-0.555,68.239,-0.454,59.704,0.135,...,-1.050,0.815,0.951,-0.257,0.060,0.955,4.3660,False,Otoño,Zona-2
335,0.017259,0.025501,0.012045,0.009055,0.245757,-0.169,11.340,0.358,-43.810,0.497,...,2.623,0.612,0.938,-0.500,0.049,0.937,0.8570,False,Invierno,Zona-2

In [ ]:
# Initialize the regressor
regressor = TabPFNRegressor()  
regressor.fit(X_train, y_train)

# Predict on the test set
predictions = regressor.predict(X_test)

# Evaluate the model

rmse = np.sqrt(mean_squared_error(y_test, predictions))
r2 = r2_score(y_test, predictions)

print("RMSE):", rmse)
print("R² Score:", r2)