In [21]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import os
pd.options.mode.chained_assignment = None
import optuna
import time
from sklearn.metrics import r2_score, mean_squared_error
from sklearn.model_selection import cross_val_score, KFold, StratifiedKFold, train_test_split
from xgboost import XGBRegressor
from catboost import CatBoostRegressor
from lightgbm import LGBMRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression, Ridge, ElasticNet
from sklearn.neighbors import KNeighborsRegressor
from sklearn.neural_network import MLPRegressor
from sklearn.svm import SVR
from sklearn.preprocessing import StandardScaler, RobustScaler
import pickle
from collections import defaultdict

In [34]:
depths = ["in_3_4"] #"in_1_2", "in_2_3", "in_3_4"]
for depth in depths: 
    # Cargamos los csv de los tifs
    path = "saved_files/dataset"
    dfs = {}
    for archivo in os.listdir(path):
        if archivo.endswith(f"{depth}_features.csv"):
            nombre_sin_extension = os.path.splitext(archivo)[0]  # sin .csv
            ruta_completa = os.path.join(path, archivo)
            dfs[nombre_sin_extension[:-9]] = pd.read_csv(ruta_completa)



    # Limpiamos valores nulos
    for nombre_df, df in dfs.items():
        for band_set in ["rhow", "rhown","rtoa"]:
            dfs[nombre_df] = df.dropna()

    dfs_to_keep = [
		'C2X-Complex_rhow_9x9_depth_in_0_1', 
		'TOA_15x15_depth_in_0_1',
		'C2X-Complex_rhown_9x9_depth_in_0_1',
		'C2X-Complex_rhow_5x5_depth_in_0_1',
		'C2RCC_rhow_5x5_depth_in_0_1',
		'C2RCC_rhow_15x15_depth_in_0_1', 
		'C2X-Complex_rhown_15x15_depth_in_0_1',
		'C2RCC_rhown_5x5_depth_in_0_1', 
		'C2X-Complex_rhow_15x15_depth_in_0_1',
		'C2RCC_rhow_9x9_depth_in_0_1',
		'C2X-Complex_rhow_5x5_depth_in_1_2', 
		'C2X_rhow_3x3_depth_in_1_2',
		'C2X-Complex_rhown_5x5_depth_in_1_2',
		'C2X-Complex_rhow_9x9_depth_in_1_2',
		'C2X-Complex_rhow_3x3_depth_in_1_2',
		'C2X-Complex_rhown_3x3_depth_in_1_2',
		'C2RCC_rhown_3x3_depth_in_1_2',
		'C2X-Complex_rhown_9x9_depth_in_1_2',
		'C2X-Complex_rhow_15x15_depth_in_1_2', 
		'C2X_rhow_5x5_depth_in_1_2',
        'TOA_15x15_depth_in_2_3',
		'TOA_9x9_depth_in_2_3',
		'TOA_5x5_depth_in_2_3', 
		'C2X-Complex_rhow_5x5_depth_in_2_3',
		'C2RCC_rhown_5x5_depth_in_2_3', 
		'TOA_3x3_depth_in_2_3',
		'C2X-Complex_rhown_5x5_depth_in_2_3', 
		'C2RCC_rhow_3x3_depth_in_2_3',
		'C2X-Complex_rhown_9x9_depth_in_2_3', 
		'C2X_rhow_9x9_depth_in_2_3',
        'TOA_9x9_depth_in_3_4',
		'TOA_3x3_depth_in_3_4',
		'TOA_5x5_depth_in_3_4',
		'C2X-Complex_rhow_5x5_depth_in_3_4', 
		'TOA_1x1_depth_in_3_4',
		'TOA_15x15_depth_in_3_4',
		'C2X-Complex_rhown_5x5_depth_in_3_4',
		'C2X-Complex_rhow_9x9_depth_in_3_4',
		'C2X-Complex_rhow_15x15_depth_in_3_4',
		'C2X-Complex_rhown_9x9_depth_in_3_4'
        ]

    dfs = {k: dfs[k] for k in dfs_to_keep if k in dfs}


    for nombre_df, df in dfs.items():
        # Marcamos las columnas de CHl alta (equivalente a quantile(0.93))
        df["High_Chl"] = df["Chl"]>5
        # Sacamos la estación de cada fecha
        df['Date'] = pd.to_datetime(df['Date'])
        def get_season(month):
            if month in [12, 1, 2]:
                return 'Invierno'
            elif month in [3, 4, 5]:
                return 'Primavera'
            elif month in [6, 7, 8]:
                return 'Verano'
            else:
                return 'Otoño'
        df['Season'] = df['Date'].dt.month.apply(get_season)
        for col in df.select_dtypes(include='object').columns:
            df[col] = df[col].astype('category')
        df = pd.concat([df.drop(columns=["Season"]),pd.get_dummies(df["Season"])], axis=1)
        dfs[nombre_df] = df

    #results = cross_validation_training(dfs, depth)
    # Run optuna

### Optimización de hiperparámetros

In [64]:
def objective(trial, df, nombre_df, target, model_name):
    # Mismo proceso que para validación cruzada, pero haciendo preds solamente sobre test
    FOLDS = 5
    # Para hacer clip a las predicciones y forzar > 0
    correct = True
    results = {}

    df = df.iloc[:, 4:]

    # Separamos el conjunto de datos en train y test: Train 75% Test 25%
    train, test = train_test_split(df, test_size=0.25, random_state=42, stratify=df["High_Chl"])
    # Seleccionamos la columna que queremos predecir
    target = "Chl"

    # Quitamos esa columna y el indicador de clorofila alta
    X = train.drop(columns=[target, "High_Chl", "Turbidez"])
    # Para y cogemos solamente Chl
    y = train[target]
    # Para poder hacer StratifiedKFold y tener el mismo número de valores de Chl alta en cada fold
    y_class = train["High_Chl"]

    # Definimos X e y para test
    #X_test = test.drop(columns=[target, "High_Chl", "Turbidez"])
    #y_test = test[target]

    # Dicts para guardar las predicciones sobre los conjuntos de validación, las y's correspondientes y los índices que corresponden dentro del loop de folds para el ensemble
    val_preds = {name: np.zeros(len(train)) for name in models}
    y_vals = defaultdict(list)
    val_indices = {}
    # Dict para guardar las predicciones sobre test
    #test_preds = {name: np.zeros(len(test)) for name in models}
    
    # Dict para guardar resultados
    results[nombre_df] = {name: {'RMSE': [], 'R2': []} for name in models}
    skf = StratifiedKFold(n_splits=FOLDS, shuffle=True, random_state=42)

    if model_name == "LBM":
        params = {
            'objective': 'regression',
            'metric': 'rmse',
            'boosting_type': 'gbdt',
            'device': 'cpu',  # usa CPU/GPU
            'verbosity': -1,
            'learning_rate': trial.suggest_float('learning_rate', 0.005, 0.05, log=True),
            'num_leaves': trial.suggest_categorical('num_leaves', [10, 20, 30]),
            'max_depth': trial.suggest_int('max_depth', 3, 6),
            'min_child_samples': trial.suggest_int('min_child_samples', 4, 8),
            'subsample': trial.suggest_float('subsample', 0.6, 1.0),
            'colsample_bytree': trial.suggest_float('colsample_bytree', 0.6, 1.0),
            'n_estimators': trial.suggest_categorical('n_estimators', [200, 400, 800]),
            'reg_alpha': trial.suggest_float('reg_alpha', 1e-3, 10.0, log=True),
            'reg_lambda': trial.suggest_float('reg_lambda', 1e-3, 10.0, log=True),
            'min_split_gain': trial.suggest_categorical('min_split_gain', [0.0, 0.1, 0.2, 0.5, 1.0])
        }

    if model_name == "XGB":
        params = {
            'n_estimators': trial.suggest_categorical('n_estimators', [200, 400, 800]),
            'learning_rate': trial.suggest_float('learning_rate', 0.005, 0.05, log=True),
            'max_depth': trial.suggest_int('max_depth', 3, 6),
            'min_child_weight': trial.suggest_int('min_child_weight', 2, 4),
            'subsample': trial.suggest_float('subsample', 0.6, 1.0),
            'colsample_bytree': trial.suggest_float('colsample_bytree', 0.6, 1.0),
            'reg_alpha': trial.suggest_float('reg_alpha', 1e-3, 10.0, log=True),
            'reg_lambda': trial.suggest_float('reg_lambda', 1e-3, 10.0, log=True),
            'device': 'cpu',
            'objective': 'reg:squarederror',
            'tree_method': 'hist',
            'enable_categorical': True,
            'eval_metric': 'rmse'
        }
    
    if model_name == "MLP":
        # Así para evitar warning de definir como tuple
        hidden_options = {
            '32': (32,),
            '64': (64,),
            '128': (128,),
            '32_16': (32, 16)
        }
        hidden_layer_sizes = trial.suggest_categorical('hidden_layer_sizes', list(hidden_options.values()))
        params = {
            'hidden_layer_sizes': hidden_layer_sizes,
            #'hidden_layer_sizes': trial.suggest_categorical('hidden_layer_sizes', [(50,), (100,), (100, 50), (128, 64)]),
            'activation': trial.suggest_categorical('activation', ['relu', 'tanh']),
            'solver': trial.suggest_categorical('solver', ['adam', 'sgd']),
            'alpha': trial.suggest_float('alpha', 1e-4, 1, log=True),
            'learning_rate': trial.suggest_categorical('learning_rate', ['constant', 'adaptive']),
            'learning_rate_init': trial.suggest_float('learning_rate_init', 1e-4, 1e-2, log=True),
            'max_iter': 200,
            'n_iter_no_change': 25,
            'early_stopping': True,
            'validation_fraction': 0.2,
            'random_state': 42,
            'verbose': False
        }

    if model_name == "SVR":
        params = {
            'kernel': 'rbf',
            'C': trial.suggest_float('C', 0.1, 5.0, log=True),
            'epsilon': trial.suggest_float('epsilon', 0.01, 0.2),
            'gamma': 'scale',
            'shrinking': True,
            'tol': 1e-3,
            'max_iter': -1,
            'verbose': False
        }

    if model_name == "KNN":
        params = {
            'n_neighbors': trial.suggest_int('n_neighbors', 5, 15),
            'weights': 'distance',
            'algorithm': 'auto',
            'leaf_size': trial.suggest_int('leaf_size', 10, 40),
            'p': 2,  # 1 = manhattan, 2 = euclídea
            'metric': 'minkowski',
            'n_jobs': -1
        }

    if model_name == "LR":
        # No sirve de mucho, pero por completitud
        params = {
            'fit_intercept': trial.suggest_categorical('fit_intercept', [True, False]),
            'positive': trial.suggest_categorical('positive', [True, False]),
        }

    if model_name == "RF":
        params = {
            'n_estimators': trial.suggest_categorical('n_estimators', [200, 400, 800]),
            'max_depth': trial.suggest_int('max_depth', 3, 6),
            'min_samples_split': trial.suggest_int('min_samples_split', 4, 10),
            'min_samples_leaf': trial.suggest_int('min_samples_leaf', 2, 8),
            'bootstrap': trial.suggest_categorical('bootstrap', [True, False]),
            'random_state': 42,
            'verbose': 0
        }

    if model_name == "CAT":
        params = {
            'iterations': trial.suggest_categorical('iterations', [500, 750, 100]),
            'learning_rate': trial.suggest_float('learning_rate', 0.02, 0.08, log=True),
            'depth': trial.suggest_int('depth', 4, 8),
            'l2_leaf_reg': trial.suggest_float('l2_leaf_reg', 1.0, 5.0),
            'loss_function': 'RMSE',
            'eval_metric': 'RMSE',
            'random_seed': 42,
            'early_stopping_rounds': 50,
            'verbose': False
        }

    if model_name == "ELN":
        params = {
            'alpha': trial.suggest_float('alpha', 1e-4, 1.0, log=True),
            'l1_ratio': trial.suggest_float('l1_ratio', 0.1, 0.9),
            'fit_intercept': True,
            'max_iter': 1000,
            'tol': 1e-4,
            'selection': 'cyclic',
            'random_state': 42
        }

    # Cargamos el modelo correspondiente
    model = models[model_name](**params)

    for fold, (train_idx, val_idx) in enumerate(skf.split(X, y_class)):
        print(f"Fold {fold+1}")
        X_train, X_val = X.iloc[train_idx], X.iloc[val_idx]
        y_train, y_val = y.iloc[train_idx], y.iloc[val_idx]

        if model_name in ["MLP", "SVR", "KNN", "LR", "ELN"]:
            scaler_X = RobustScaler()
            scaler_y = RobustScaler()
            X_train_scaled = scaler_X.fit_transform(X_train)
            X_val_scaled = scaler_X.transform(X_val)
            #X_test_scaled = scaler_X.transform(X_test)
            y_train_scaled = scaler_y.fit_transform(y_train.values.reshape(-1, 1)).ravel()
            model.fit(X_train_scaled, y_train_scaled)
            val_pred = scaler_y.inverse_transform(model.predict(X_val_scaled).reshape(-1, 1)).ravel()
            #test_pred = scaler_y.inverse_transform(model.predict(X_test_scaled).reshape(-1, 1)).ravel()

        else:
            model.fit(X_train, y_train)
            val_pred = model.predict(X_val)
            #test_pred = model.predict(X_test)

        if correct:
            val_pred = np.clip(val_pred, 0.2, None)
            #test_pred = np.clip(test_pred, 0.2, None)

        val_preds[model_name][val_idx] = val_pred
        if model_name == list(models.keys())[0]:
            # Solo lo guardamos una vez
            y_vals[fold] = y_val
            val_indices[fold] = val_idx

        rmse = np.sqrt(mean_squared_error(y_val, val_pred))
        r2 = r2_score(y_val, val_pred)
        results[nombre_df][model_name]['RMSE'].append(rmse)
        results[nombre_df][model_name]['R2'].append(r2)
        #test_preds[model_name] += test_pred / FOLDS

    #rmse_test = np.sqrt(mean_squared_error(y_test, test_preds[model_name]))
    r2 = np.mean(results[nombre_df][model_name]["R2"])

    return r2

In [67]:

models = {
    "XGB": XGBRegressor,
    "LBM": LGBMRegressor,
    "MLP": MLPRegressor,
    "SVR": SVR,
    "KNN": KNeighborsRegressor,
    "LR": LinearRegression,
    "RF": RandomForestRegressor,
    "CAT": CatBoostRegressor,
    "ELN":  ElasticNet
}

def run_optuna(df, nombre_df, target, n_trials, model_name):
    results = {}

    print(f"Buscando mejores hiperparámetros para {model_name} con {nombre_df}...")
    study = optuna.create_study(direction='maximize')
    study.optimize(lambda trial: objective(trial, df, nombre_df, target, model_name), n_trials=n_trials, timeout= 1500)
    
    print(f"\n✅ {model_name} con {nombre_df} - Mejor R2: {study.best_value:.2f}")
    print(f"📋 Parámetros: {study.best_params}\n")
    
    results[model_name] = {
        'best_params': study.best_params,
        'best_score': np.round(study.best_value, 3)
    }
    return results

In [68]:


depths = ["in_0_1", "in_1_2", "in_2_3", "in_3_4"]
for depth in depths: 
    # Cargamos los csv de los tifs
    path = "saved_files/dataset"
    dfs = {}
    for archivo in os.listdir(path):
        if archivo.endswith(f"{depth}_features.csv"):
            nombre_sin_extension = os.path.splitext(archivo)[0]  # sin .csv
            ruta_completa = os.path.join(path, archivo)
            dfs[nombre_sin_extension[:-9]] = pd.read_csv(ruta_completa)


    # Limpiamos valores nulos
    for nombre_df, df in dfs.items():
        for band_set in ["rhow", "rhown","rtoa"]:
            dfs[nombre_df] = df.dropna()

    dfs_to_keep = [
		'C2X-Complex_rhow_9x9_depth_in_0_1', 
		'TOA_15x15_depth_in_0_1',
		'C2X-Complex_rhown_9x9_depth_in_0_1',
		'C2X-Complex_rhow_5x5_depth_in_0_1',
		'C2RCC_rhow_5x5_depth_in_0_1',
		'C2RCC_rhow_15x15_depth_in_0_1', 
		'C2X-Complex_rhown_15x15_depth_in_0_1',
		'C2RCC_rhown_5x5_depth_in_0_1', 
		'C2X-Complex_rhow_15x15_depth_in_0_1',
		'C2RCC_rhow_9x9_depth_in_0_1',
		'C2X-Complex_rhow_5x5_depth_in_1_2', 
		'C2X_rhow_3x3_depth_in_1_2',
		'C2X-Complex_rhown_5x5_depth_in_1_2',
		'C2X-Complex_rhow_9x9_depth_in_1_2',
		'C2X-Complex_rhow_3x3_depth_in_1_2',
		'C2X-Complex_rhown_3x3_depth_in_1_2',
		'C2RCC_rhown_3x3_depth_in_1_2',
		'C2X-Complex_rhown_9x9_depth_in_1_2',
		'C2X-Complex_rhow_15x15_depth_in_1_2', 
		'C2X_rhow_5x5_depth_in_1_2',
        'TOA_15x15_depth_in_2_3',
		'TOA_9x9_depth_in_2_3',
		'TOA_5x5_depth_in_2_3', 
		'C2X-Complex_rhow_5x5_depth_in_2_3',
		'C2RCC_rhown_5x5_depth_in_2_3', 
		'TOA_3x3_depth_in_2_3',
		'C2X-Complex_rhown_5x5_depth_in_2_3', 
		'C2RCC_rhow_3x3_depth_in_2_3',
		'C2X-Complex_rhown_9x9_depth_in_2_3', 
		'C2X_rhow_9x9_depth_in_2_3',
        'TOA_9x9_depth_in_3_4',
		'TOA_3x3_depth_in_3_4',
		'TOA_5x5_depth_in_3_4',
		'C2X-Complex_rhow_5x5_depth_in_3_4', 
		'TOA_1x1_depth_in_3_4',
		'TOA_15x15_depth_in_3_4',
		'C2X-Complex_rhown_5x5_depth_in_3_4',
		'C2X-Complex_rhow_9x9_depth_in_3_4',
		'C2X-Complex_rhow_15x15_depth_in_3_4',
		'C2X-Complex_rhown_9x9_depth_in_3_4'
        ]

    dfs = {k: dfs[k] for k in dfs_to_keep if k in dfs}


    for nombre_df, df in dfs.items():
        # Marcamos las columnas de CHl alta (equivalente a quantile(0.93))
        df["High_Chl"] = df["Chl"]>5
        # Sacamos la estación de cada fecha
        df['Date'] = pd.to_datetime(df['Date'])
        def get_season(month):
            if month in [12, 1, 2]:
                return 'Invierno'
            elif month in [3, 4, 5]:
                return 'Primavera'
            elif month in [6, 7, 8]:
                return 'Verano'
            else:
                return 'Otoño'
        df['Season'] = df['Date'].dt.month.apply(get_season)
        for col in df.select_dtypes(include='object').columns:
            df[col] = df[col].astype('category')
        df = pd.concat([df.drop(columns=["Season"]),pd.get_dummies(df["Season"])], axis=1)
        dfs[nombre_df] = df

In [69]:

n_trials = 25
global_results = {}
for nombre_df, df in list(dfs.items()):
    for model_name in models.keys():
        key = (nombre_df, model_name)
        result = run_optuna(df, nombre_df, "Chl", n_trials, model_name)
        global_results[key] = result[model_name]

with open(f"training_results/selection_results_{depth}.pkl", "wb") as f:
    pickle.dump(global_results, f)

[I 2025-09-05 14:49:50,815] A new study created in memory with name: no-name-8142d234-8603-4dac-b86e-4ed65e07e36a

Buscando mejores hiperparámetros para XGB con TOA_9x9_depth_in_3_4...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-05 14:49:51,808] Trial 0 finished with value: 0.22143256544043424 and parameters: {'n_estimators': 100, 'learning_rate': 0.006331295848463554, 'max_depth': 4, 'min_child_weight': 3, 'subsample': 0.6189068374012878, 'colsample_bytree': 0.7915675776355535, 'reg_alpha': 0.22188080496423374, 'reg_lambda': 1.8096118618515222}. Best is trial 0 with value: 0.22143256544043424.

Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-05 14:49:52,781] Trial 1 finished with value: 0.43358086437467663 and parameters: {'n_estimators': 100, 'learning_rate': 0.018566020456359925, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.7020190781416005, 'colsample_bytree': 0.9639207366879835, 'reg_alpha': 0.18435296612342958, 'reg_lambda': 0.028697927595108117}. Best is trial 1 with value: 0.43358086437467663.

Fold 5
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-05 14:49:54,580] Trial 2 finished with value: 0.4827752130612758 and parameters: {'n_estimators': 250, 'learning_rate': 0.02795012502224411, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.9185459792503402, 'colsample_bytree': 0.7684243710784034, 'reg_alpha': 0.009564699398834588, 'reg_lambda': 0.9296573228478843}. Best is trial 2 with value: 0.4827752130612758.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-05 14:49:56,283] Trial 3 finished with value: 0.45916699090456986 and parameters: {'n_estimators': 250, 'learning_rate': 0.01709436842285325, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.886080793560043, 'colsample_bytree': 0.9189738669911536, 'reg_alpha': 6.045652870350894, 'reg_lambda': 0.28649672599957915}. Best is trial 2 with value: 0.4827752130612758.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-05 14:49:57,415] Trial 4 finished with value: 0.3640269513056861 and parameters: {'n_estimators': 100, 'learning_rate': 0.013725635710861363, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.8121482944741432, 'colsample_bytree': 0.7183645865849799, 'reg_alpha': 0.07945981153589007, 'reg_lambda': 3.135349596395583}. Best is trial 2 with value: 0.4827752130612758.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-05 14:49:59,590] Trial 5 finished with value: 0.5125743973706995 and parameters: {'n_estimators': 250, 'learning_rate': 0.030810039218678947, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.7128274437092043, 'colsample_bytree': 0.9119800435375578, 'reg_alpha': 2.6092130895982417, 'reg_lambda': 0.18722457638554055}. Best is trial 5 with value: 0.5125743973706995.

Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-05 14:50:00,364] Trial 6 finished with value: 0.44462179605002145 and parameters: {'n_estimators': 100, 'learning_rate': 0.02188787759941391, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.6397047036283628, 'colsample_bytree': 0.7040499989492004, 'reg_alpha': 1.7103985445426804, 'reg_lambda': 0.015685296424866015}. Best is trial 5 with value: 0.5125743973706995.

Fold 5
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-05 14:50:01,946] Trial 7 finished with value: 0.4155808914332237 and parameters: {'n_estimators': 250, 'learning_rate': 0.009815708334950523, 'max_depth': 4, 'min_child_weight': 3, 'subsample': 0.7154040982219264, 'colsample_bytree': 0.721300133717714, 'reg_alpha': 1.1849458885684063, 'reg_lambda': 2.0583580779194577}. Best is trial 5 with value: 0.5125743973706995.
[I 2025-09-05 14:50:02,143] Trial 8 finished with value: -0.36651985360730255 and parameters: {'n_estimators': 0, 'learning_rate': 0.04180015831438819, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.6567452973998668, 'colsample_bytree': 0.6716884419547297, 'reg_alpha': 0.014911984527693422, 'reg_lambda': 0.4186551698106543}. Best is trial 5 with value: 0.5125743973706995.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Fold 1

[I 2025-09-05 14:50:02,419] Trial 9 finished with value: -0.36651985360730255 and parameters: {'n_estimators': 0, 'learning_rate': 0.009551569853639088, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.8097343033824773, 'colsample_bytree': 0.8983880052676714, 'reg_alpha': 0.30959933298037434, 'reg_lambda': 1.1064516308696355}. Best is trial 5 with value: 0.5125743973706995.

Fold 2
Fold 3
Fold 4
Fold 5
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-05 14:50:03,643] Trial 10 finished with value: 0.44120754745386714 and parameters: {'n_estimators': 250, 'learning_rate': 0.04985914069802329, 'max_depth': 3, 'min_child_weight': 2, 'subsample': 0.9992213071007443, 'colsample_bytree': 0.8674314137323766, 'reg_alpha': 0.0010313080654836893, 'reg_lambda': 0.0010170112477502163}. Best is trial 5 with value: 0.5125743973706995.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-05 14:50:05,684] Trial 11 finished with value: 0.4657220936804456 and parameters: {'n_estimators': 250, 'learning_rate': 0.02831562570381573, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.9264200722483312, 'colsample_bytree': 0.8262669104266832, 'reg_alpha': 0.01079507676522526, 'reg_lambda': 0.07418718023561358}. Best is trial 5 with value: 0.5125743973706995.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-05 14:50:07,619] Trial 12 finished with value: 0.49805255347652044 and parameters: {'n_estimators': 250, 'learning_rate': 0.031405542588804125, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.736172740119508, 'colsample_bytree': 0.6126614800165628, 'reg_alpha': 0.00791792671977994, 'reg_lambda': 7.775802831818779}. Best is trial 5 with value: 0.5125743973706995.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-05 14:50:09,432] Trial 13 finished with value: 0.49712534877738507 and parameters: {'n_estimators': 250, 'learning_rate': 0.033733380436372015, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.7452700217691967, 'colsample_bytree': 0.6213781574941203, 'reg_alpha': 0.0013601204725866897, 'reg_lambda': 0.004039223279847733}. Best is trial 5 with value: 0.5125743973706995.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-05 14:50:11,594] Trial 14 finished with value: 0.49064622664568114 and parameters: {'n_estimators': 250, 'learning_rate': 0.03347553317484236, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.7672111560649845, 'colsample_bytree': 0.9913747862774418, 'reg_alpha': 0.035848840538575955, 'reg_lambda': 7.100522545727513}. Best is trial 5 with value: 0.5125743973706995.

Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-05 14:50:12,713] Trial 15 finished with value: 0.4577138057783827 and parameters: {'n_estimators': 250, 'learning_rate': 0.023350617164926205, 'max_depth': 3, 'min_child_weight': 2, 'subsample': 0.679607684548927, 'colsample_bytree': 0.6027652601142746, 'reg_alpha': 8.94388421673454, 'reg_lambda': 9.488729263878863}. Best is trial 5 with value: 0.5125743973706995.

Fold 5
Fold 1
Fold 2
Fold 3

[I 2025-09-05 14:50:13,043] Trial 16 finished with value: -0.36651985360730255 and parameters: {'n_estimators': 0, 'learning_rate': 0.03612385212005762, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.8534088100169067, 'colsample_bytree': 0.8437096575490026, 'reg_alpha': 0.0037599414419034237, 'reg_lambda': 0.18335725201681805}. Best is trial 5 with value: 0.5125743973706995.

Fold 4
Fold 5
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-05 14:50:14,920] Trial 17 finished with value: 0.4702363529224147 and parameters: {'n_estimators': 250, 'learning_rate': 0.0487638361209935, 'max_depth': 4, 'min_child_weight': 2, 'subsample': 0.7592083261103489, 'colsample_bytree': 0.9416912176911121, 'reg_alpha': 0.8232357006606098, 'reg_lambda': 0.07443759357305178}. Best is trial 5 with value: 0.5125743973706995.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-05 14:50:17,146] Trial 18 finished with value: 0.4857359102852617 and parameters: {'n_estimators': 250, 'learning_rate': 0.013447243788312167, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.6091811292063881, 'colsample_bytree': 0.8802644470390701, 'reg_alpha': 0.05795068623295358, 'reg_lambda': 0.012503136046685683}. Best is trial 5 with value: 0.5125743973706995.

Fold 1
Fold 2

[I 2025-09-05 14:50:17,511] Trial 19 finished with value: -0.36651985360730255 and parameters: {'n_estimators': 0, 'learning_rate': 0.025428985705263182, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.7254520229065511, 'colsample_bytree': 0.661374801988599, 'reg_alpha': 3.8947873836290405, 'reg_lambda': 0.605105302769044}. Best is trial 5 with value: 0.5125743973706995.

Fold 3
Fold 4
Fold 5
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-05 14:50:21,013] Trial 20 finished with value: 0.4144929091134387 and parameters: {'n_estimators': 250, 'learning_rate': 0.005038724398296978, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.7886587408511885, 'colsample_bytree': 0.7629067420730727, 'reg_alpha': 0.0033511875311078598, 'reg_lambda': 0.12697271815455408}. Best is trial 5 with value: 0.5125743973706995.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-05 14:50:22,829] Trial 21 finished with value: 0.4901020920999697 and parameters: {'n_estimators': 250, 'learning_rate': 0.034750175232452746, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.7465946021990989, 'colsample_bytree': 0.6209760216261682, 'reg_alpha': 0.00202718531246351, 'reg_lambda': 0.0018355258680344492}. Best is trial 5 with value: 0.5125743973706995.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-05 14:50:24,720] Trial 22 finished with value: 0.48808091950638044 and parameters: {'n_estimators': 250, 'learning_rate': 0.03202971843748229, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.7032365138493647, 'colsample_bytree': 0.6440049346424365, 'reg_alpha': 0.001359337311775884, 'reg_lambda': 0.004164827124131545}. Best is trial 5 with value: 0.5125743973706995.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-05 14:50:26,824] Trial 23 finished with value: 0.4706841972406293 and parameters: {'n_estimators': 250, 'learning_rate': 0.04135760140830118, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.6702605701601214, 'colsample_bytree': 0.6834966407830088, 'reg_alpha': 0.004568405317234048, 'reg_lambda': 0.005479233437683356}. Best is trial 5 with value: 0.5125743973706995.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-05 14:50:28,191] Trial 24 finished with value: 0.48260006165536085 and parameters: {'n_estimators': 250, 'learning_rate': 0.01914598427519645, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.8486639656358443, 'colsample_bytree': 0.629320271568023, 'reg_alpha': 0.026793608575089944, 'reg_lambda': 0.024783507069333924}. Best is trial 5 with value: 0.5125743973706995.
[I 2025-09-05 14:50:28,192] A new study created in memory with name: no-name-0ca844e5-ae11-4228-aa3d-4f315066f08b
[I 2025-09-05 14:50:28,295] Trial 0 finished with value: 0.3232949903896335 and parameters: {'learning_rate': 0.00991402511690901, 'num_leaves': 10, 'max_depth': 6, 'min_child_samples': 5, 'subsample': 0.8844074383435272, 'colsample_bytree': 0.744162916941872, 'n_estimators': 100, 'reg_alpha': 0.07098813148191915, 'reg_lambda': 1.5556851067963862, 'min_split_gain': 0.5}. Best is trial 0 with value: 0.3232949903896335.
[I 2025-09-05 14:50:28,357] Trial 1 finished with value: 0.18473374439840354 and parameters: {'learning_rate': 0.0057174211279210655, 'num_leaves': 10, 'max_depth': 3, 'min_child_samples': 7, 'subsample': 0.7393184400783556, 'colsample_bytree': 0.7321164025388115, 'n_estimators': 100, 'reg_alpha': 0.2734102881163963, 'reg_lambda': 0.4370950973262398, 'min_split_gain': 0.0}. Best is trial 0 with value: 0.3232949903896335.

✅ XGB con TOA_9x9_depth_in_3_4 - Mejor R2: 0.51
📋 Parámetros: {'n_estimators': 250, 'learning_rate': 0.030810039218678947, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.7128274437092043, 'colsample_bytree': 0.9119800435375578, 'reg_alpha': 2.6092130895982417, 'reg_lambda': 0.18722457638554055}

Buscando mejores hiperparámetros para LBM con TOA_9x9_depth_in_3_4...
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Fold 1
Fold 2

[I 2025-09-05 14:50:28,525] Trial 2 finished with value: 0.4711315544281856 and parameters: {'learning_rate': 0.01879839873251892, 'num_leaves': 20, 'max_depth': 4, 'min_child_samples': 7, 'subsample': 0.8404225520937488, 'colsample_bytree': 0.8350147021456217, 'n_estimators': 250, 'reg_alpha': 0.40141406266583907, 'reg_lambda': 2.2030432294272675, 'min_split_gain': 1.0}. Best is trial 2 with value: 0.4711315544281856.

Fold 3
Fold 4
Fold 5
Fold 1
Fold 2
Fold 3

[I 2025-09-05 14:50:28,733] Trial 3 finished with value: 0.4840529311962099 and parameters: {'learning_rate': 0.013462017703483582, 'num_leaves': 10, 'max_depth': 6, 'min_child_samples': 6, 'subsample': 0.7225982946891283, 'colsample_bytree': 0.8411607592222461, 'n_estimators': 250, 'reg_alpha': 0.001507253319167222, 'reg_lambda': 0.13287983090034894, 'min_split_gain': 0.5}. Best is trial 3 with value: 0.4840529311962099.

Fold 4
Fold 5
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-05 14:50:28,931] Trial 4 finished with value: 0.4442636653652 and parameters: {'learning_rate': 0.008581711739324442, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 7, 'subsample': 0.8852741687322495, 'colsample_bytree': 0.6274975106176789, 'n_estimators': 250, 'reg_alpha': 3.680259057330848, 'reg_lambda': 0.0027123261914066637, 'min_split_gain': 0.2}. Best is trial 3 with value: 0.4840529311962099.

Fold 5
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-05 14:50:29,382] Trial 5 finished with value: 0.4895440055866249 and parameters: {'learning_rate': 0.006821910389519423, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 7, 'subsample': 0.7726130480675089, 'colsample_bytree': 0.9502863528350852, 'n_estimators': 500, 'reg_alpha': 2.048590384661351, 'reg_lambda': 0.18466162360426308, 'min_split_gain': 0.0}. Best is trial 5 with value: 0.4895440055866249.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-05 14:50:29,595] Trial 6 finished with value: 0.44711369008982843 and parameters: {'learning_rate': 0.008414593844032644, 'num_leaves': 10, 'max_depth': 6, 'min_child_samples': 7, 'subsample': 0.7132818019993464, 'colsample_bytree': 0.7985106477111791, 'n_estimators': 250, 'reg_alpha': 0.02302701798400648, 'reg_lambda': 0.09591707270213706, 'min_split_gain': 0.0}. Best is trial 5 with value: 0.4895440055866249.
[I 2025-09-05 14:50:29,756] Trial 7 finished with value: 0.4483114829897848 and parameters: {'learning_rate': 0.0317983405641704, 'num_leaves': 20, 'max_depth': 3, 'min_child_samples': 8, 'subsample': 0.9475089763023717, 'colsample_bytree': 0.6942742081720632, 'n_estimators': 500, 'reg_alpha': 1.3542425759811159, 'reg_lambda': 1.86479901567072, 'min_split_gain': 1.0}. Best is trial 5 with value: 0.4895440055866249.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Fold 1
Fold 2
Fold 3

[I 2025-09-05 14:50:29,848] Trial 8 finished with value: 0.4768800951140304 and parameters: {'learning_rate': 0.04486071757905673, 'num_leaves': 10, 'max_depth': 4, 'min_child_samples': 8, 'subsample': 0.8910500330701803, 'colsample_bytree': 0.7829500692448672, 'n_estimators': 100, 'reg_alpha': 0.23312996621241996, 'reg_lambda': 0.002069833472204654, 'min_split_gain': 0.0}. Best is trial 5 with value: 0.4895440055866249.
[I 2025-09-05 14:50:29,951] Trial 9 finished with value: 0.2531844213866427 and parameters: {'learning_rate': 0.005004780896195691, 'num_leaves': 30, 'max_depth': 5, 'min_child_samples': 5, 'subsample': 0.8784143321008052, 'colsample_bytree': 0.8624474713212872, 'n_estimators': 100, 'reg_alpha': 0.0028675671633022126, 'reg_lambda': 0.01007978324832079, 'min_split_gain': 0.5}. Best is trial 5 with value: 0.4895440055866249.

Fold 4
Fold 5
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-05 14:50:30,241] Trial 10 finished with value: 0.4488652214421787 and parameters: {'learning_rate': 0.01978909030789417, 'num_leaves': 30, 'max_depth': 5, 'min_child_samples': 4, 'subsample': 0.6069876893592165, 'colsample_bytree': 0.9896571149031501, 'n_estimators': 500, 'reg_alpha': 6.711534015669249, 'reg_lambda': 0.0314794016502834, 'min_split_gain': 0.1}. Best is trial 5 with value: 0.4895440055866249.

Fold 1
Fold 2
Fold 3

[I 2025-09-05 14:50:30,687] Trial 11 finished with value: 0.4740357602417261 and parameters: {'learning_rate': 0.013253682544896214, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 6, 'subsample': 0.7604704763324615, 'colsample_bytree': 0.9258944578511777, 'n_estimators': 500, 'reg_alpha': 0.0010696846268378416, 'reg_lambda': 0.1814311701383837, 'min_split_gain': 0.5}. Best is trial 5 with value: 0.4895440055866249.

Fold 4
Fold 5
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-05 14:50:31,118] Trial 12 finished with value: 0.5065725969013972 and parameters: {'learning_rate': 0.012317178854309406, 'num_leaves': 10, 'max_depth': 6, 'min_child_samples': 6, 'subsample': 0.659826327540429, 'colsample_bytree': 0.9131115917933522, 'n_estimators': 500, 'reg_alpha': 0.011451521225213777, 'reg_lambda': 0.04050682592713659, 'min_split_gain': 0.2}. Best is trial 12 with value: 0.5065725969013972.

Fold 5
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-05 14:50:31,551] Trial 13 finished with value: 0.46671724681108095 and parameters: {'learning_rate': 0.006789430744636398, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 5, 'subsample': 0.6356471815443817, 'colsample_bytree': 0.933418261763165, 'n_estimators': 500, 'reg_alpha': 0.012771896511218878, 'reg_lambda': 0.017909509939358085, 'min_split_gain': 0.2}. Best is trial 12 with value: 0.5065725969013972.

Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-05 14:50:31,906] Trial 14 finished with value: 0.4912687739518685 and parameters: {'learning_rate': 0.01131995370708326, 'num_leaves': 30, 'max_depth': 4, 'min_child_samples': 6, 'subsample': 0.6652321985920329, 'colsample_bytree': 0.9929318782745911, 'n_estimators': 500, 'reg_alpha': 0.009979022422564262, 'reg_lambda': 8.051026552155804, 'min_split_gain': 0.2}. Best is trial 12 with value: 0.5065725969013972.

Fold 5
Fold 1
Fold 2

[I 2025-09-05 14:50:32,250] Trial 15 finished with value: 0.5075484496142304 and parameters: {'learning_rate': 0.02298083521873911, 'num_leaves': 30, 'max_depth': 4, 'min_child_samples': 6, 'subsample': 0.6736390955503158, 'colsample_bytree': 0.994869929592234, 'n_estimators': 500, 'reg_alpha': 0.007301198046242098, 'reg_lambda': 8.110050496453574, 'min_split_gain': 0.2}. Best is trial 15 with value: 0.5075484496142304.

Fold 3
Fold 4
Fold 5
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-05 14:50:32,594] Trial 16 finished with value: 0.49302774942179883 and parameters: {'learning_rate': 0.025485554835631623, 'num_leaves': 30, 'max_depth': 4, 'min_child_samples': 4, 'subsample': 0.67270951806031, 'colsample_bytree': 0.8849970883266287, 'n_estimators': 500, 'reg_alpha': 0.005153999390331625, 'reg_lambda': 6.187513617059242, 'min_split_gain': 0.2}. Best is trial 15 with value: 0.5075484496142304.

Fold 5
Fold 1
Fold 2
Fold 3

[I 2025-09-05 14:50:32,856] Trial 17 finished with value: 0.45206207694453243 and parameters: {'learning_rate': 0.0272565311232707, 'num_leaves': 30, 'max_depth': 3, 'min_child_samples': 5, 'subsample': 0.6754525968230602, 'colsample_bytree': 0.9147998711272602, 'n_estimators': 500, 'reg_alpha': 0.05215754337098998, 'reg_lambda': 0.03605027484720929, 'min_split_gain': 0.2}. Best is trial 15 with value: 0.5075484496142304.

Fold 4
Fold 5
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-05 14:50:33,260] Trial 18 finished with value: 0.4686590587162569 and parameters: {'learning_rate': 0.018340456798872116, 'num_leaves': 30, 'max_depth': 4, 'min_child_samples': 6, 'subsample': 0.8171844428173524, 'colsample_bytree': 0.967296278042182, 'n_estimators': 500, 'reg_alpha': 0.025288738339562467, 'reg_lambda': 0.006389372367134697, 'min_split_gain': 0.1}. Best is trial 15 with value: 0.5075484496142304.
[I 2025-09-05 14:50:33,488] Trial 19 finished with value: 0.49544370381800446 and parameters: {'learning_rate': 0.04685738619784909, 'num_leaves': 10, 'max_depth': 3, 'min_child_samples': 6, 'subsample': 0.9903343937575864, 'colsample_bytree': 0.8938905080920576, 'n_estimators': 500, 'reg_alpha': 0.004711097978889859, 'reg_lambda': 0.697559787951642, 'min_split_gain': 0.2}. Best is trial 15 with value: 0.5075484496142304.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-05 14:50:33,810] Trial 20 finished with value: 0.4346333045742584 and parameters: {'learning_rate': 0.035966952454138654, 'num_leaves': 30, 'max_depth': 6, 'min_child_samples': 5, 'subsample': 0.6030984285955937, 'colsample_bytree': 0.9932876627271376, 'n_estimators': 500, 'reg_alpha': 0.03778015133052872, 'reg_lambda': 0.04920520352157606, 'min_split_gain': 0.2}. Best is trial 15 with value: 0.5075484496142304.

Fold 5
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-05 14:50:34,041] Trial 21 finished with value: 0.4940871390047664 and parameters: {'learning_rate': 0.046125508392173886, 'num_leaves': 10, 'max_depth': 3, 'min_child_samples': 6, 'subsample': 0.9938822560060532, 'colsample_bytree': 0.8891994307398646, 'n_estimators': 500, 'reg_alpha': 0.0036016400007961107, 'reg_lambda': 0.5032888711628128, 'min_split_gain': 0.2}. Best is trial 15 with value: 0.5075484496142304.

Fold 5
Fold 1
Fold 2
Fold 3

[I 2025-09-05 14:50:34,307] Trial 22 finished with value: 0.49895512709639733 and parameters: {'learning_rate': 0.02294528214774629, 'num_leaves': 10, 'max_depth': 3, 'min_child_samples': 6, 'subsample': 0.6968970842141051, 'colsample_bytree': 0.8846638466127823, 'n_estimators': 500, 'reg_alpha': 0.009351123893265608, 'reg_lambda': 0.6765994355288113, 'min_split_gain': 0.2}. Best is trial 15 with value: 0.5075484496142304.

Fold 4
Fold 5
Fold 1
Fold 2

[I 2025-09-05 14:50:34,632] Trial 23 finished with value: 0.5094898761861233 and parameters: {'learning_rate': 0.022836872481335296, 'num_leaves': 10, 'max_depth': 4, 'min_child_samples': 6, 'subsample': 0.6969178974711557, 'colsample_bytree': 0.957837367218261, 'n_estimators': 500, 'reg_alpha': 0.010958930915002094, 'reg_lambda': 4.097488526702455, 'min_split_gain': 0.2}. Best is trial 23 with value: 0.5094898761861233.

Fold 3
Fold 4
Fold 5
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-05 14:50:34,981] Trial 24 finished with value: 0.49429323680551657 and parameters: {'learning_rate': 0.014842604171387224, 'num_leaves': 10, 'max_depth': 4, 'min_child_samples': 7, 'subsample': 0.6408962704668233, 'colsample_bytree': 0.9587100029081839, 'n_estimators': 500, 'reg_alpha': 0.13226610422411567, 'reg_lambda': 3.8601786864056904, 'min_split_gain': 0.2}. Best is trial 23 with value: 0.5094898761861233.
[I 2025-09-05 14:50:34,983] A new study created in memory with name: no-name-edd62a28-f769-436e-af78-c5df8086dee9

Fold 5

✅ LBM con TOA_9x9_depth_in_3_4 - Mejor R2: 0.51
📋 Parámetros: {'learning_rate': 0.022836872481335296, 'num_leaves': 10, 'max_depth': 4, 'min_child_samples': 6, 'subsample': 0.6969178974711557, 'colsample_bytree': 0.957837367218261, 'n_estimators': 500, 'reg_alpha': 0.010958930915002094, 'reg_lambda': 4.097488526702455, 'min_split_gain': 0.2}

Buscando mejores hiperparámetros para MLP con TOA_9x9_depth_in_3_4...
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32, 16) which is of type tuple.
  warnings.warn(message)

Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-05 14:50:35,930] Trial 0 finished with value: 0.3705306206442942 and parameters: {'hidden_layer_sizes': (32,), 'activation': 'relu', 'solver': 'adam', 'alpha': 0.04425954204807753, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0012939496421008306}. Best is trial 0 with value: 0.3705306206442942.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-05 14:50:37,867] Trial 1 finished with value: 0.30201486514993714 and parameters: {'hidden_layer_sizes': (32, 16), 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.10541958984627346, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0006356338075991651}. Best is trial 0 with value: 0.3705306206442942.

In [47]:
global_results

{('TOA_9x9_depth_in_3_4',
  'XGB'): {'best_params': {'n_estimators': 2000,
   'learning_rate': 0.047600594240155655,
   'max_depth': 5,
   'min_child_weight': 4,
   'subsample': 0.6049475476360661,
   'colsample_bytree': 0.8631912096943319}, 'best_score': 0.615, 'study': <optuna.study.study.Study at 0x7800b0502610>},
 ('TOA_9x9_depth_in_3_4',
  'LBM'): {'best_params': {'learning_rate': 0.01713416804277511,
   'num_leaves': 80,
   'max_depth': 8,
   'min_child_samples': 11,
   'subsample': 0.7883599431510695,
   'colsample_bytree': 0.8460115625974576,
   'n_estimators': 500}, 'best_score': 0.628, 'study': <optuna.study.study.Study at 0x7800b0502c10>},
 ('TOA_9x9_depth_in_3_4',
  'MLP'): {'best_params': {'hidden_layer_sizes': '256_128',
   'activation': 'relu',
   'solver': 'sgd',
   'alpha': 0.015492411781384838,
   'learning_rate': 'adaptive',
   'learning_rate_init': 0.0019024503727906594}, 'best_score': 0.71, 'study': <optuna.study.study.Study at 0x7800b014d100>},
 ('TOA_9x9_depth_in_3_4',
  'SVR'): {'best_params': {'C': 1.9860741741743726,
   'epsilon': 0.023712171259654913}, 'best_score': 0.504, 'study': <optuna.study.study.Study at 0x7800d80a13a0>},
 ('TOA_9x9_depth_in_3_4',
  'KNN'): {'best_params': {'n_neighbors': 10,
   'leaf_size': 40}, 'best_score': 0.65, 'study': <optuna.study.study.Study at 0x7800b03d04c0>},
 ('TOA_9x9_depth_in_3_4',
  'LR'): {'best_params': {'fit_intercept': False,
   'positive': False}, 'best_score': 0.378, 'study': <optuna.study.study.Study at 0x7800b04c3eb0>},
 ('TOA_9x9_depth_in_3_4',
  'RF'): {'best_params': {'n_estimators': 100,
   'max_depth': 14,
   'min_samples_split': 10,
   'min_samples_leaf': 2,
   'bootstrap': True}, 'best_score': 0.624, 'study': <optuna.study.study.Study at 0x7800b029aa60>},
 ('TOA_9x9_depth_in_3_4',
  'CAT'): {'best_params': {'iterations': 1000,
   'learning_rate': 0.0678180379236064,
   'depth': 8,
   'l2_leaf_reg': 2.511488464786048}, 'best_score': 0.621, 'study': <optuna.study.study.Study at 0x7800b0609370>},
 ('TOA_9x9_depth_in_3_4',
  'ELN'): {'best_params': {'alpha': 0.00010094145044864732,
   'l1_ratio': 0.5266509861480015}, 'best_score': 0.461, 'study': <optuna.study.study.Study at 0x7800d917cd00>},
 ('TOA_3x3_depth_in_3_4',
  'XGB'): {'best_params': {'n_estimators': 500,
   'learning_rate': 0.009576598127245279,
   'max_depth': 7,
   'min_child_weight': 4,
   'subsample': 0.7615794445091003,
   'colsample_bytree': 0.6930474458735117}, 'best_score': 0.627, 'study': <optuna.study.study.Study at 0x7800d930ac70>},
 ('TOA_3x3_depth_in_3_4',
  'LBM'): {'best_params': {'learning_rate': 0.01474336254464019,
   'num_leaves': 40,
   'max_depth': 6,
   'min_child_samples': 6,
   'subsample': 0.9964816945465981,
   'colsample_bytree': 0.8686133786839119,
   'n_estimators': 500}, 'best_score': 0.661, 'study': <optuna.study.study.Study at 0x7800b0557190>},
 ('TOA_3x3_depth_in_3_4',
  'MLP'): {'best_params': {'hidden_layer_sizes': '128_64',
   'activation': 'relu',
   'solver': 'adam',
   'alpha': 1.8399498662330756e-05,
   'learning_rate': 'constant',
   'learning_rate_init': 0.0005319925846193705}, 'best_score': 0.676, 'study': <optuna.study.study.Study at 0x7800a9f7a3a0>},
 ('TOA_3x3_depth_in_3_4',
  'SVR'): {'best_params': {'C': 2.4279016303695427,
   'epsilon': 0.08368239687667561}, 'best_score': 0.488, 'study': <optuna.study.study.Study at 0x7800b044be80>},
 ('TOA_3x3_depth_in_3_4',
  'KNN'): {'best_params': {'n_neighbors': 6,
   'leaf_size': 40}, 'best_score': 0.617, 'study': <optuna.study.study.Study at 0x7800b06f57f0>},
 ('TOA_3x3_depth_in_3_4',
  'LR'): {'best_params': {'fit_intercept': True,
   'positive': False}, 'best_score': 0.4, 'study': <optuna.study.study.Study at 0x7800b0187610>},
 ('TOA_3x3_depth_in_3_4',
  'RF'): {'best_params': {'n_estimators': 300,
   'max_depth': 12,
   'min_samples_split': 6,
   'min_samples_leaf': 3,
   'bootstrap': False}, 'best_score': 0.681, 'study': <optuna.study.study.Study at 0x7800b0354d30>},
 ('TOA_3x3_depth_in_3_4',
  'CAT'): {'best_params': {'iterations': 500,
   'learning_rate': 0.05232742477450515,
   'depth': 9,
   'l2_leaf_reg': 1.0235346499052462}, 'best_score': 0.63, 'study': <optuna.study.study.Study at 0x7800b02f4610>},
 ('TOA_3x3_depth_in_3_4',
  'ELN'): {'best_params': {'alpha': 0.00018219071583212146,
   'l1_ratio': 0.9794021781112037}, 'best_score': 0.467, 'study': <optuna.study.study.Study at 0x7800a9ffc9d0>},
 ('TOA_5x5_depth_in_3_4',
  'XGB'): {'best_params': {'n_estimators': 500,
   'learning_rate': 0.04876113896916153,
   'max_depth': 5,
   'min_child_weight': 4,
   'subsample': 0.7176461215093223,
   'colsample_bytree': 0.6759132844855982}, 'best_score': 0.627, 'study': <optuna.study.study.Study at 0x7800d919b280>},
 ('TOA_5x5_depth_in_3_4',
  'LBM'): {'best_params': {'learning_rate': 0.01955671466854787,
   'num_leaves': 60,
   'max_depth': 6,
   'min_child_samples': 4,
   'subsample': 0.9583671783514893,
   'colsample_bytree': 0.9991128614038579,
   'n_estimators': 500}, 'best_score': 0.678, 'study': <optuna.study.study.Study at 0x7800b02c6e20>},
 ('TOA_5x5_depth_in_3_4',
  'MLP'): {'best_params': {'hidden_layer_sizes': '128_64',
   'activation': 'relu',
   'solver': 'adam',
   'alpha': 0.00024472909052337217,
   'learning_rate': 'adaptive',
   'learning_rate_init': 0.0005084699170246252}, 'best_score': 0.697, 'study': <optuna.study.study.Study at 0x7800b004c0a0>},
 ('TOA_5x5_depth_in_3_4',
  'SVR'): {'best_params': {'C': 2.063097300418171,
   'epsilon': 0.0789893324667928}, 'best_score': 0.483, 'study': <optuna.study.study.Study at 0x7800b01fdb20>},
 ('TOA_5x5_depth_in_3_4',
  'KNN'): {'best_params': {'n_neighbors': 10,
   'leaf_size': 18}, 'best_score': 0.638, 'study': <optuna.study.study.Study at 0x7800b03aa640>},
 ('TOA_5x5_depth_in_3_4',
  'LR'): {'best_params': {'fit_intercept': True,
   'positive': False}, 'best_score': 0.448, 'study': <optuna.study.study.Study at 0x7800b029bd00>},
 ('TOA_5x5_depth_in_3_4',
  'RF'): {'best_params': {'n_estimators': 100,
   'max_depth': 15,
   'min_samples_split': 4,
   'min_samples_leaf': 3,
   'bootstrap': True}, 'best_score': 0.63, 'study': <optuna.study.study.Study at 0x7800b00a2ca0>},
 ('TOA_5x5_depth_in_3_4',
  'CAT'): {'best_params': {'iterations': 2000,
   'learning_rate': 0.01027011523144864,
   'depth': 7,
   'l2_leaf_reg': 1.0526076927639805}, 'best_score': 0.593, 'study': <optuna.study.study.Study at 0x7800b04bdaf0>},
 ('TOA_5x5_depth_in_3_4',
  'ELN'): {'best_params': {'alpha': 0.014403901229536019,
   'l1_ratio': 0.9023438654300626}, 'best_score': 0.474, 'study': <optuna.study.study.Study at 0x7800a9f6d8e0>},
 ('C2X-Complex_rhow_5x5_depth_in_3_4',
  'XGB'): {'best_params': {'n_estimators': 500,
   'learning_rate': 0.007889846245071235,
   'max_depth': 7,
   'min_child_weight': 4,
   'subsample': 0.6478799909895996,
   'colsample_bytree': 0.9184042139949454}, 'best_score': 0.652, 'study': <optuna.study.study.Study at 0x7800a9f5eb80>},
 ('C2X-Complex_rhow_5x5_depth_in_3_4',
  'LBM'): {'best_params': {'learning_rate': 0.006617912473095984,
   'num_leaves': 40,
   'max_depth': 8,
   'min_child_samples': 8,
   'subsample': 0.9303188839872626,
   'colsample_bytree': 0.7448045774739271,
   'n_estimators': 500}, 'best_score': 0.636, 'study': <optuna.study.study.Study at 0x7800b06a8d60>},
 ('C2X-Complex_rhow_5x5_depth_in_3_4',
  'MLP'): {'best_params': {'hidden_layer_sizes': '256_128',
   'activation': 'relu',
   'solver': 'adam',
   'alpha': 0.00010236429010965995,
   'learning_rate': 'adaptive',
   'learning_rate_init': 0.0003651197409167566}, 'best_score': 0.657, 'study': <optuna.study.study.Study at 0x7800b057dfa0>},
 ('C2X-Complex_rhow_5x5_depth_in_3_4',
  'SVR'): {'best_params': {'C': 9.555509499241047,
   'epsilon': 0.13134472658792118}, 'best_score': 0.537, 'study': <optuna.study.study.Study at 0x7800b0079520>},
 ('C2X-Complex_rhow_5x5_depth_in_3_4',
  'KNN'): {'best_params': {'n_neighbors': 10,
   'leaf_size': 40}, 'best_score': 0.588, 'study': <optuna.study.study.Study at 0x7800a9f3d160>},
 ('C2X-Complex_rhow_5x5_depth_in_3_4',
  'LR'): {'best_params': {'fit_intercept': False,
   'positive': True}, 'best_score': 0.548, 'study': <optuna.study.study.Study at 0x7800b06798b0>},
 ('C2X-Complex_rhow_5x5_depth_in_3_4',
  'RF'): {'best_params': {'n_estimators': 500,
   'max_depth': 12,
   'min_samples_split': 2,
   'min_samples_leaf': 2,
   'bootstrap': True}, 'best_score': 0.651, 'study': <optuna.study.study.Study at 0x7800b057f7f0>},
 ('C2X-Complex_rhow_5x5_depth_in_3_4',
  'CAT'): {'best_params': {'iterations': 500,
   'learning_rate': 0.014143036661619373,
   'depth': 4,
   'l2_leaf_reg': 2.864319547628134}, 'best_score': 0.63, 'study': <optuna.study.study.Study at 0x7800b06be1c0>},
 ('C2X-Complex_rhow_5x5_depth_in_3_4',
  'ELN'): {'best_params': {'alpha': 0.0025285029727796925,
   'l1_ratio': 0.5792628939321688}, 'best_score': 0.584, 'study': <optuna.study.study.Study at 0x7800d9079fa0>},
 ('TOA_1x1_depth_in_3_4',
  'XGB'): {'best_params': {'n_estimators': 500,
   'learning_rate': 0.005903889352876245,
   'max_depth': 8,
   'min_child_weight': 2,
   'subsample': 0.781917998902364,
   'colsample_bytree': 0.722278807877633}, 'best_score': 0.519, 'study': <optuna.study.study.Study at 0x7800b07592e0>},
 ('TOA_1x1_depth_in_3_4',
  'LBM'): {'best_params': {'learning_rate': 0.007130386687415869,
   'num_leaves': 20,
   'max_depth': 7,
   'min_child_samples': 10,
   'subsample': 0.8922959456502495,
   'colsample_bytree': 0.9294737227298466,
   'n_estimators': 500}, 'best_score': 0.618, 'study': <optuna.study.study.Study at 0x7800b0085820>},
 ('TOA_1x1_depth_in_3_4',
  'MLP'): {'best_params': {'hidden_layer_sizes': '256',
   'activation': 'relu',
   'solver': 'adam',
   'alpha': 4.763485358217016e-05,
   'learning_rate': 'adaptive',
   'learning_rate_init': 0.0004348441303622641}, 'best_score': 0.688, 'study': <optuna.study.study.Study at 0x7800b029aac0>},
 ('TOA_1x1_depth_in_3_4',
  'SVR'): {'best_params': {'C': 2.2111333817672927,
   'epsilon': 0.07253326854109794}, 'best_score': 0.461, 'study': <optuna.study.study.Study at 0x7800b025f2b0>},
 ('TOA_1x1_depth_in_3_4',
  'KNN'): {'best_params': {'n_neighbors': 6,
   'leaf_size': 33}, 'best_score': 0.611, 'study': <optuna.study.study.Study at 0x7800b01d88e0>},
 ('TOA_1x1_depth_in_3_4',
  'LR'): {'best_params': {'fit_intercept': False,
   'positive': True}, 'best_score': 0.328, 'study': <optuna.study.study.Study at 0x7800b021e070>},
 ('TOA_1x1_depth_in_3_4',
  'RF'): {'best_params': {'n_estimators': 500,
   'max_depth': 11,
   'min_samples_split': 6,
   'min_samples_leaf': 3,
   'bootstrap': True}, 'best_score': 0.557, 'study': <optuna.study.study.Study at 0x7800d8343670>},
 ('TOA_1x1_depth_in_3_4',
  'CAT'): {'best_params': {'iterations': 1000,
   'learning_rate': 0.033260444981323356,
   'depth': 8,
   'l2_leaf_reg': 1.12206076072196}, 'best_score': 0.569, 'study': <optuna.study.study.Study at 0x7800dcb5f460>},
 ('TOA_1x1_depth_in_3_4',
  'ELN'): {'best_params': {'alpha': 0.028283841413022752,
   'l1_ratio': 0.9109286287993379}, 'best_score': 0.452, 'study': <optuna.study.study.Study at 0x7800d92a9b50>},
 ('TOA_15x15_depth_in_3_4',
  'XGB'): {'best_params': {'n_estimators': 500,
   'learning_rate': 0.013566967402918429,
   'max_depth': 5,
   'min_child_weight': 4,
   'subsample': 0.6807531615273382,
   'colsample_bytree': 0.607434439562925}, 'best_score': 0.607, 'study': <optuna.study.study.Study at 0x7800b03f2220>},
 ('TOA_15x15_depth_in_3_4',
  'LBM'): {'best_params': {'learning_rate': 0.00909468587481228,
   'num_leaves': 60,
   'max_depth': 7,
   'min_child_samples': 13,
   'subsample': 0.6536720142119191,
   'colsample_bytree': 0.8953446248078664,
   'n_estimators': 1000}, 'best_score': 0.632, 'study': <optuna.study.study.Study at 0x7800a9661100>},
 ('TOA_15x15_depth_in_3_4',
  'MLP'): {'best_params': {'hidden_layer_sizes': '256',
   'activation': 'relu',
   'solver': 'adam',
   'alpha': 0.0034242834875374936,
   'learning_rate': 'constant',
   'learning_rate_init': 0.0012220669807227185}, 'best_score': 0.708, 'study': <optuna.study.study.Study at 0x7800a8debf10>},
 ('TOA_15x15_depth_in_3_4',
  'SVR'): {'best_params': {'C': 2.15684226903379,
   'epsilon': 0.12775727625293434}, 'best_score': 0.494, 'study': <optuna.study.study.Study at 0x7800a8dacc40>},
 ('TOA_15x15_depth_in_3_4',
  'KNN'): {'best_params': {'n_neighbors': 7,
   'leaf_size': 31}, 'best_score': 0.649, 'study': <optuna.study.study.Study at 0x7800a9eb7c70>},
 ('TOA_15x15_depth_in_3_4',
  'LR'): {'best_params': {'fit_intercept': False,
   'positive': False}, 'best_score': 0.38, 'study': <optuna.study.study.Study at 0x7800a9f4b820>},
 ('TOA_15x15_depth_in_3_4',
  'RF'): {'best_params': {'n_estimators': 100,
   'max_depth': 10,
   'min_samples_split': 2,
   'min_samples_leaf': 2,
   'bootstrap': True}, 'best_score': 0.617, 'study': <optuna.study.study.Study at 0x7800a8dff730>},
 ('TOA_15x15_depth_in_3_4',
  'CAT'): {'best_params': {'iterations': 2000,
   'learning_rate': 0.05314326154992145,
   'depth': 9,
   'l2_leaf_reg': 1.0213152871705147}, 'best_score': 0.681, 'study': <optuna.study.study.Study at 0x7800a8d816a0>},
 ('TOA_15x15_depth_in_3_4',
  'ELN'): {'best_params': {'alpha': 0.00011287578590294489,
   'l1_ratio': 0.9941527400112994}, 'best_score': 0.505, 'study': <optuna.study.study.Study at 0x7800a8dab1c0>},
 ('C2X-Complex_rhown_5x5_depth_in_3_4',
  'XGB'): {'best_params': {'n_estimators': 2000,
   'learning_rate': 0.045720937679426726,
   'max_depth': 7,
   'min_child_weight': 2,
   'subsample': 0.8049551995941774,
   'colsample_bytree': 0.9077296398951732}, 'best_score': 0.637, 'study': <optuna.study.study.Study at 0x7800a8d94d30>},
 ('C2X-Complex_rhown_5x5_depth_in_3_4',
  'LBM'): {'best_params': {'learning_rate': 0.021490317734639115,
   'num_leaves': 60,
   'max_depth': 7,
   'min_child_samples': 4,
   'subsample': 0.9171600598982209,
   'colsample_bytree': 0.9060991657287198,
   'n_estimators': 500}, 'best_score': 0.623, 'study': <optuna.study.study.Study at 0x7800e4412a90>},
 ('C2X-Complex_rhown_5x5_depth_in_3_4',
  'MLP'): {'best_params': {'hidden_layer_sizes': '256_128',
   'activation': 'relu',
   'solver': 'sgd',
   'alpha': 0.0028311644287798946,
   'learning_rate': 'constant',
   'learning_rate_init': 0.005228148188640056}, 'best_score': 0.618, 'study': <optuna.study.study.Study at 0x7800b018e790>},
 ('C2X-Complex_rhown_5x5_depth_in_3_4',
  'SVR'): {'best_params': {'C': 3.645085787366226,
   'epsilon': 0.18516646571349163}, 'best_score': 0.509, 'study': <optuna.study.study.Study at 0x7800a9673850>},
 ('C2X-Complex_rhown_5x5_depth_in_3_4',
  'KNN'): {'best_params': {'n_neighbors': 10,
   'leaf_size': 34}, 'best_score': 0.571, 'study': <optuna.study.study.Study at 0x7800b00b8e50>},
 ('C2X-Complex_rhown_5x5_depth_in_3_4',
  'LR'): {'best_params': {'fit_intercept': False,
   'positive': True}, 'best_score': 0.537, 'study': <optuna.study.study.Study at 0x7800b04e9340>},
 ('C2X-Complex_rhown_5x5_depth_in_3_4',
  'RF'): {'best_params': {'n_estimators': 500,
   'max_depth': 11,
   'min_samples_split': 4,
   'min_samples_leaf': 2,
   'bootstrap': True}, 'best_score': 0.641, 'study': <optuna.study.study.Study at 0x7800b06798e0>},
 ('C2X-Complex_rhown_5x5_depth_in_3_4',
  'CAT'): {'best_params': {'iterations': 500,
   'learning_rate': 0.025340947072845177,
   'depth': 6,
   'l2_leaf_reg': 5.927927435982809}, 'best_score': 0.603, 'study': <optuna.study.study.Study at 0x7800a9f92b50>},
 ('C2X-Complex_rhown_5x5_depth_in_3_4',
  'ELN'): {'best_params': {'alpha': 0.029440640009221405,
   'l1_ratio': 0.9952562878940697}, 'best_score': 0.573, 'study': <optuna.study.study.Study at 0x7800a9f92fa0>},
 ('C2X-Complex_rhow_9x9_depth_in_3_4',
  'XGB'): {'best_params': {'n_estimators': 500,
   'learning_rate': 0.007784242501186818,
   'max_depth': 6,
   'min_child_weight': 1,
   'subsample': 0.6045990140239461,
   'colsample_bytree': 0.9996062608334324}, 'best_score': 0.616, 'study': <optuna.study.study.Study at 0x7800a8d96a00>},
 ('C2X-Complex_rhow_9x9_depth_in_3_4',
  'LBM'): {'best_params': {'learning_rate': 0.006387333436517826,
   'num_leaves': 80,
   'max_depth': 8,
   'min_child_samples': 13,
   'subsample': 0.6384425602632136,
   'colsample_bytree': 0.6626794560644892,
   'n_estimators': 500}, 'best_score': 0.624, 'study': <optuna.study.study.Study at 0x7800d911cc10>},
 ('C2X-Complex_rhow_9x9_depth_in_3_4',
  'MLP'): {'best_params': {'hidden_layer_sizes': '256_128',
   'activation': 'relu',
   'solver': 'adam',
   'alpha': 0.0014611726954603002,
   'learning_rate': 'constant',
   'learning_rate_init': 0.0006912854086058073}, 'best_score': 0.649, 'study': <optuna.study.study.Study at 0x7800a8dd2790>},
 ('C2X-Complex_rhow_9x9_depth_in_3_4',
  'SVR'): {'best_params': {'C': 9.93157967401947,
   'epsilon': 0.1963107857538181}, 'best_score': 0.598, 'study': <optuna.study.study.Study at 0x7800b036ba60>},
 ('C2X-Complex_rhow_9x9_depth_in_3_4',
  'KNN'): {'best_params': {'n_neighbors': 9,
   'leaf_size': 27}, 'best_score': 0.579, 'study': <optuna.study.study.Study at 0x7800a9eb3460>},
 ('C2X-Complex_rhow_9x9_depth_in_3_4',
  'LR'): {'best_params': {'fit_intercept': False,
   'positive': True}, 'best_score': 0.569, 'study': <optuna.study.study.Study at 0x7800d8f87d90>},
 ('C2X-Complex_rhow_9x9_depth_in_3_4',
  'RF'): {'best_params': {'n_estimators': 100,
   'max_depth': 14,
   'min_samples_split': 3,
   'min_samples_leaf': 1,
   'bootstrap': True}, 'best_score': 0.63, 'study': <optuna.study.study.Study at 0x7800a8e23940>},
 ('C2X-Complex_rhow_9x9_depth_in_3_4',
  'CAT'): {'best_params': {'iterations': 1000,
   'learning_rate': 0.07521844621271666,
   'depth': 5,
   'l2_leaf_reg': 4.739858256733454}, 'best_score': 0.617, 'study': <optuna.study.study.Study at 0x7800b01b6430>},
 ('C2X-Complex_rhow_9x9_depth_in_3_4',
  'ELN'): {'best_params': {'alpha': 0.015126276739043923,
   'l1_ratio': 0.3433210919466816}, 'best_score': 0.589, 'study': <optuna.study.study.Study at 0x7800a9ecdbe0>},
 ('C2X-Complex_rhow_15x15_depth_in_3_4',
  'XGB'): {'best_params': {'n_estimators': 1000,
   'learning_rate': 0.010148550064538592,
   'max_depth': 7,
   'min_child_weight': 1,
   'subsample': 0.7092554975366574,
   'colsample_bytree': 0.9589996114894445}, 'best_score': 0.548, 'study': <optuna.study.study.Study at 0x7800a9f0bc70>},
 ('C2X-Complex_rhow_15x15_depth_in_3_4',
  'LBM'): {'best_params': {'learning_rate': 0.005034271791889273,
   'num_leaves': 60,
   'max_depth': 6,
   'min_child_samples': 11,
   'subsample': 0.9704198407257476,
   'colsample_bytree': 0.8302542907662975,
   'n_estimators': 500}, 'best_score': 0.555, 'study': <optuna.study.study.Study at 0x7800a8e6bf40>},
 ('C2X-Complex_rhow_15x15_depth_in_3_4',
  'MLP'): {'best_params': {'hidden_layer_sizes': '256',
   'activation': 'relu',
   'solver': 'adam',
   'alpha': 0.03673448429184167,
   'learning_rate': 'adaptive',
   'learning_rate_init': 0.005512541724045937}, 'best_score': 0.638, 'study': <optuna.study.study.Study at 0x7800a9f6f5b0>},
 ('C2X-Complex_rhow_15x15_depth_in_3_4',
  'SVR'): {'best_params': {'C': 3.2413369664629386,
   'epsilon': 0.1982961712911414}, 'best_score': 0.584, 'study': <optuna.study.study.Study at 0x7800d8fe5ee0>},
 ('C2X-Complex_rhow_15x15_depth_in_3_4',
  'KNN'): {'best_params': {'n_neighbors': 10,
   'leaf_size': 19}, 'best_score': 0.484, 'study': <optuna.study.study.Study at 0x7800a8e0ebb0>},
 ('C2X-Complex_rhow_15x15_depth_in_3_4',
  'LR'): {'best_params': {'fit_intercept': True,
   'positive': True}, 'best_score': 0.537, 'study': <optuna.study.study.Study at 0x7800a8e796a0>},
 ('C2X-Complex_rhow_15x15_depth_in_3_4',
  'RF'): {'best_params': {'n_estimators': 100,
   'max_depth': 8,
   'min_samples_split': 3,
   'min_samples_leaf': 4,
   'bootstrap': True}, 'best_score': 0.572, 'study': <optuna.study.study.Study at 0x7800a9ec8d30>},
 ('C2X-Complex_rhow_15x15_depth_in_3_4',
  'CAT'): {'best_params': {'iterations': 500,
   'learning_rate': 0.010126948003726963,

In [14]:
with open(f"training_results/selection_results_{depth}.pkl", "wb") as f:
    pickle.dump(global_results, f)

In [39]:
# Diccionario para agrupar parámetros por modelo
params_by_model = defaultdict(list)

# Agrupar best_params por modelo
for (df_name, model_name), result in global_results.items():
    best_params = result["best_params"]
    params_by_model[model_name].append(best_params)

# Crear DataFrames con medias y std por modelo
summary_stats = {}

for model_name, param_list in params_by_model.items():
    df_params = pd.DataFrame(param_list)

    # Filtramos solo columnas numéricas para calcular medias y std
    df_numeric = df_params.select_dtypes(include=[np.number])

    stats = pd.concat([df_numeric.mean().rename("mean"), df_numeric.std().rename("std")], axis=1)
    summary_stats[model_name] = stats

# Mostrar un ejemplo
summary_stats["LBM"]

                         mean         std
learning_rate        0.011264    0.006322
num_leaves          52.000000   21.499354
max_depth            6.800000    1.032796
min_child_samples    9.000000    3.366502
subsample            0.846105    0.135599
colsample_bytree     0.853437    0.094603
n_estimators       550.000000  158.113883

In [37]:
global_results

{('TOA_9x9_depth_in_3_4',
  'XGB'): {'best_params': {'n_estimators': 2000,
   'learning_rate': 0.047600594240155655,
   'max_depth': 5,
   'min_child_weight': 4,
   'subsample': 0.6049475476360661,
   'colsample_bytree': 0.8631912096943319}, 'best_score': 0.615, 'study': <optuna.study.study.Study at 0x7800b0502610>},
 ('TOA_9x9_depth_in_3_4',
  'LBM'): {'best_params': {'learning_rate': 0.01713416804277511,
   'num_leaves': 80,
   'max_depth': 8,
   'min_child_samples': 11,
   'subsample': 0.7883599431510695,
   'colsample_bytree': 0.8460115625974576,
   'n_estimators': 500}, 'best_score': 0.628, 'study': <optuna.study.study.Study at 0x7800b0502c10>},
 ('TOA_9x9_depth_in_3_4',
  'MLP'): {'best_params': {'hidden_layer_sizes': '256_128',
   'activation': 'relu',
   'solver': 'sgd',
   'alpha': 0.015492411781384838,
   'learning_rate': 'adaptive',
   'learning_rate_init': 0.0019024503727906594}, 'best_score': 0.71, 'study': <optuna.study.study.Study at 0x7800b014d100>},
 ('TOA_9x9_depth_in_3_4',
  'SVR'): {'best_params': {'C': 1.9860741741743726,
   'epsilon': 0.023712171259654913}, 'best_score': 0.504, 'study': <optuna.study.study.Study at 0x7800d80a13a0>},
 ('TOA_9x9_depth_in_3_4',
  'KNN'): {'best_params': {'n_neighbors': 10,
   'leaf_size': 40}, 'best_score': 0.65, 'study': <optuna.study.study.Study at 0x7800b03d04c0>},
 ('TOA_9x9_depth_in_3_4',
  'LR'): {'best_params': {'fit_intercept': False,
   'positive': False}, 'best_score': 0.378, 'study': <optuna.study.study.Study at 0x7800b04c3eb0>},
 ('TOA_9x9_depth_in_3_4',
  'RF'): {'best_params': {'n_estimators': 100,
   'max_depth': 14,
   'min_samples_split': 10,
   'min_samples_leaf': 2,
   'bootstrap': True}, 'best_score': 0.624, 'study': <optuna.study.study.Study at 0x7800b029aa60>},
 ('TOA_9x9_depth_in_3_4',
  'CAT'): {'best_params': {'iterations': 1000,
   'learning_rate': 0.0678180379236064,
   'depth': 8,
   'l2_leaf_reg': 2.511488464786048}, 'best_score': 0.621, 'study': <optuna.study.study.Study at 0x7800b0609370>},
 ('TOA_9x9_depth_in_3_4',
  'ELN'): {'best_params': {'alpha': 0.00010094145044864732,
   'l1_ratio': 0.5266509861480015}, 'best_score': 0.461, 'study': <optuna.study.study.Study at 0x7800d917cd00>},
 ('TOA_3x3_depth_in_3_4',
  'XGB'): {'best_params': {'n_estimators': 500,
   'learning_rate': 0.009576598127245279,
   'max_depth': 7,
   'min_child_weight': 4,
   'subsample': 0.7615794445091003,
   'colsample_bytree': 0.6930474458735117}, 'best_score': 0.627, 'study': <optuna.study.study.Study at 0x7800d930ac70>},
 ('TOA_3x3_depth_in_3_4',
  'LBM'): {'best_params': {'learning_rate': 0.01474336254464019,
   'num_leaves': 40,
   'max_depth': 6,
   'min_child_samples': 6,
   'subsample': 0.9964816945465981,
   'colsample_bytree': 0.8686133786839119,
   'n_estimators': 500}, 'best_score': 0.661, 'study': <optuna.study.study.Study at 0x7800b0557190>},
 ('TOA_3x3_depth_in_3_4',
  'MLP'): {'best_params': {'hidden_layer_sizes': '128_64',
   'activation': 'relu',
   'solver': 'adam',
   'alpha': 1.8399498662330756e-05,
   'learning_rate': 'constant',
   'learning_rate_init': 0.0005319925846193705}, 'best_score': 0.676, 'study': <optuna.study.study.Study at 0x7800a9f7a3a0>},
 ('TOA_3x3_depth_in_3_4',
  'SVR'): {'best_params': {'C': 2.4279016303695427,
   'epsilon': 0.08368239687667561}, 'best_score': 0.488, 'study': <optuna.study.study.Study at 0x7800b044be80>},
 ('TOA_3x3_depth_in_3_4',
  'KNN'): {'best_params': {'n_neighbors': 6,
   'leaf_size': 40}, 'best_score': 0.617, 'study': <optuna.study.study.Study at 0x7800b06f57f0>},
 ('TOA_3x3_depth_in_3_4',
  'LR'): {'best_params': {'fit_intercept': True,
   'positive': False}, 'best_score': 0.4, 'study': <optuna.study.study.Study at 0x7800b0187610>},
 ('TOA_3x3_depth_in_3_4',
  'RF'): {'best_params': {'n_estimators': 300,
   'max_depth': 12,
   'min_samples_split': 6,
   'min_samples_leaf': 3,
   'bootstrap': False}, 'best_score': 0.681, 'study': <optuna.study.study.Study at 0x7800b0354d30>},
 ('TOA_3x3_depth_in_3_4',
  'CAT'): {'best_params': {'iterations': 500,
   'learning_rate': 0.05232742477450515,
   'depth': 9,
   'l2_leaf_reg': 1.0235346499052462}, 'best_score': 0.63, 'study': <optuna.study.study.Study at 0x7800b02f4610>},
 ('TOA_3x3_depth_in_3_4',
  'ELN'): {'best_params': {'alpha': 0.00018219071583212146,
   'l1_ratio': 0.9794021781112037}, 'best_score': 0.467, 'study': <optuna.study.study.Study at 0x7800a9ffc9d0>},
 ('TOA_5x5_depth_in_3_4',
  'XGB'): {'best_params': {'n_estimators': 500,
   'learning_rate': 0.04876113896916153,
   'max_depth': 5,
   'min_child_weight': 4,
   'subsample': 0.7176461215093223,
   'colsample_bytree': 0.6759132844855982}, 'best_score': 0.627, 'study': <optuna.study.study.Study at 0x7800d919b280>},
 ('TOA_5x5_depth_in_3_4',
  'LBM'): {'best_params': {'learning_rate': 0.01955671466854787,
   'num_leaves': 60,
   'max_depth': 6,
   'min_child_samples': 4,
   'subsample': 0.9583671783514893,
   'colsample_bytree': 0.9991128614038579,
   'n_estimators': 500}, 'best_score': 0.678, 'study': <optuna.study.study.Study at 0x7800b02c6e20>},
 ('TOA_5x5_depth_in_3_4',
  'MLP'): {'best_params': {'hidden_layer_sizes': '128_64',
   'activation': 'relu',
   'solver': 'adam',
   'alpha': 0.00024472909052337217,
   'learning_rate': 'adaptive',
   'learning_rate_init': 0.0005084699170246252}, 'best_score': 0.697, 'study': <optuna.study.study.Study at 0x7800b004c0a0>},
 ('TOA_5x5_depth_in_3_4',
  'SVR'): {'best_params': {'C': 2.063097300418171,
   'epsilon': 0.0789893324667928}, 'best_score': 0.483, 'study': <optuna.study.study.Study at 0x7800b01fdb20>},
 ('TOA_5x5_depth_in_3_4',
  'KNN'): {'best_params': {'n_neighbors': 10,
   'leaf_size': 18}, 'best_score': 0.638, 'study': <optuna.study.study.Study at 0x7800b03aa640>},
 ('TOA_5x5_depth_in_3_4',
  'LR'): {'best_params': {'fit_intercept': True,
   'positive': False}, 'best_score': 0.448, 'study': <optuna.study.study.Study at 0x7800b029bd00>},
 ('TOA_5x5_depth_in_3_4',
  'RF'): {'best_params': {'n_estimators': 100,
   'max_depth': 15,
   'min_samples_split': 4,
   'min_samples_leaf': 3,
   'bootstrap': True}, 'best_score': 0.63, 'study': <optuna.study.study.Study at 0x7800b00a2ca0>},
 ('TOA_5x5_depth_in_3_4',
  'CAT'): {'best_params': {'iterations': 2000,
   'learning_rate': 0.01027011523144864,
   'depth': 7,
   'l2_leaf_reg': 1.0526076927639805}, 'best_score': 0.593, 'study': <optuna.study.study.Study at 0x7800b04bdaf0>},
 ('TOA_5x5_depth_in_3_4',
  'ELN'): {'best_params': {'alpha': 0.014403901229536019,
   'l1_ratio': 0.9023438654300626}, 'best_score': 0.474, 'study': <optuna.study.study.Study at 0x7800a9f6d8e0>},
 ('C2X-Complex_rhow_5x5_depth_in_3_4',
  'XGB'): {'best_params': {'n_estimators': 500,
   'learning_rate': 0.007889846245071235,
   'max_depth': 7,
   'min_child_weight': 4,
   'subsample': 0.6478799909895996,
   'colsample_bytree': 0.9184042139949454}, 'best_score': 0.652, 'study': <optuna.study.study.Study at 0x7800a9f5eb80>},
 ('C2X-Complex_rhow_5x5_depth_in_3_4',
  'LBM'): {'best_params': {'learning_rate': 0.006617912473095984,
   'num_leaves': 40,
   'max_depth': 8,
   'min_child_samples': 8,
   'subsample': 0.9303188839872626,
   'colsample_bytree': 0.7448045774739271,
   'n_estimators': 500}, 'best_score': 0.636, 'study': <optuna.study.study.Study at 0x7800b06a8d60>},
 ('C2X-Complex_rhow_5x5_depth_in_3_4',
  'MLP'): {'best_params': {'hidden_layer_sizes': '256_128',
   'activation': 'relu',
   'solver': 'adam',
   'alpha': 0.00010236429010965995,
   'learning_rate': 'adaptive',
   'learning_rate_init': 0.0003651197409167566}, 'best_score': 0.657, 'study': <optuna.study.study.Study at 0x7800b057dfa0>},
 ('C2X-Complex_rhow_5x5_depth_in_3_4',
  'SVR'): {'best_params': {'C': 9.555509499241047,
   'epsilon': 0.13134472658792118}, 'best_score': 0.537, 'study': <optuna.study.study.Study at 0x7800b0079520>},
 ('C2X-Complex_rhow_5x5_depth_in_3_4',
  'KNN'): {'best_params': {'n_neighbors': 10,
   'leaf_size': 40}, 'best_score': 0.588, 'study': <optuna.study.study.Study at 0x7800a9f3d160>},
 ('C2X-Complex_rhow_5x5_depth_in_3_4',
  'LR'): {'best_params': {'fit_intercept': False,
   'positive': True}, 'best_score': 0.548, 'study': <optuna.study.study.Study at 0x7800b06798b0>},
 ('C2X-Complex_rhow_5x5_depth_in_3_4',
  'RF'): {'best_params': {'n_estimators': 500,
   'max_depth': 12,
   'min_samples_split': 2,
   'min_samples_leaf': 2,
   'bootstrap': True}, 'best_score': 0.651, 'study': <optuna.study.study.Study at 0x7800b057f7f0>},
 ('C2X-Complex_rhow_5x5_depth_in_3_4',
  'CAT'): {'best_params': {'iterations': 500,
   'learning_rate': 0.014143036661619373,
   'depth': 4,
   'l2_leaf_reg': 2.864319547628134}, 'best_score': 0.63, 'study': <optuna.study.study.Study at 0x7800b06be1c0>},
 ('C2X-Complex_rhow_5x5_depth_in_3_4',
  'ELN'): {'best_params': {'alpha': 0.0025285029727796925,
   'l1_ratio': 0.5792628939321688}, 'best_score': 0.584, 'study': <optuna.study.study.Study at 0x7800d9079fa0>},
 ('TOA_1x1_depth_in_3_4',
  'XGB'): {'best_params': {'n_estimators': 500,
   'learning_rate': 0.005903889352876245,
   'max_depth': 8,
   'min_child_weight': 2,
   'subsample': 0.781917998902364,
   'colsample_bytree': 0.722278807877633}, 'best_score': 0.519, 'study': <optuna.study.study.Study at 0x7800b07592e0>},
 ('TOA_1x1_depth_in_3_4',
  'LBM'): {'best_params': {'learning_rate': 0.007130386687415869,
   'num_leaves': 20,
   'max_depth': 7,
   'min_child_samples': 10,
   'subsample': 0.8922959456502495,
   'colsample_bytree': 0.9294737227298466,
   'n_estimators': 500}, 'best_score': 0.618, 'study': <optuna.study.study.Study at 0x7800b0085820>},
 ('TOA_1x1_depth_in_3_4',
  'MLP'): {'best_params': {'hidden_layer_sizes': '256',
   'activation': 'relu',
   'solver': 'adam',
   'alpha': 4.763485358217016e-05,
   'learning_rate': 'adaptive',
   'learning_rate_init': 0.0004348441303622641}, 'best_score': 0.688, 'study': <optuna.study.study.Study at 0x7800b029aac0>},
 ('TOA_1x1_depth_in_3_4',
  'SVR'): {'best_params': {'C': 2.2111333817672927,
   'epsilon': 0.07253326854109794}, 'best_score': 0.461, 'study': <optuna.study.study.Study at 0x7800b025f2b0>},
 ('TOA_1x1_depth_in_3_4',
  'KNN'): {'best_params': {'n_neighbors': 6,
   'leaf_size': 33}, 'best_score': 0.611, 'study': <optuna.study.study.Study at 0x7800b01d88e0>},
 ('TOA_1x1_depth_in_3_4',
  'LR'): {'best_params': {'fit_intercept': False,
   'positive': True}, 'best_score': 0.328, 'study': <optuna.study.study.Study at 0x7800b021e070>},
 ('TOA_1x1_depth_in_3_4',
  'RF'): {'best_params': {'n_estimators': 500,
   'max_depth': 11,
   'min_samples_split': 6,
   'min_samples_leaf': 3,
   'bootstrap': True}, 'best_score': 0.557, 'study': <optuna.study.study.Study at 0x7800d8343670>},
 ('TOA_1x1_depth_in_3_4',
  'CAT'): {'best_params': {'iterations': 1000,
   'learning_rate': 0.033260444981323356,
   'depth': 8,
   'l2_leaf_reg': 1.12206076072196}, 'best_score': 0.569, 'study': <optuna.study.study.Study at 0x7800dcb5f460>},
 ('TOA_1x1_depth_in_3_4',
  'ELN'): {'best_params': {'alpha': 0.028283841413022752,
   'l1_ratio': 0.9109286287993379}, 'best_score': 0.452, 'study': <optuna.study.study.Study at 0x7800d92a9b50>},
 ('TOA_15x15_depth_in_3_4',
  'XGB'): {'best_params': {'n_estimators': 500,
   'learning_rate': 0.013566967402918429,
   'max_depth': 5,
   'min_child_weight': 4,
   'subsample': 0.6807531615273382,
   'colsample_bytree': 0.607434439562925}, 'best_score': 0.607, 'study': <optuna.study.study.Study at 0x7800b03f2220>},
 ('TOA_15x15_depth_in_3_4',
  'LBM'): {'best_params': {'learning_rate': 0.00909468587481228,
   'num_leaves': 60,
   'max_depth': 7,
   'min_child_samples': 13,
   'subsample': 0.6536720142119191,
   'colsample_bytree': 0.8953446248078664,
   'n_estimators': 1000}, 'best_score': 0.632, 'study': <optuna.study.study.Study at 0x7800a9661100>},
 ('TOA_15x15_depth_in_3_4',
  'MLP'): {'best_params': {'hidden_layer_sizes': '256',
   'activation': 'relu',
   'solver': 'adam',
   'alpha': 0.0034242834875374936,
   'learning_rate': 'constant',
   'learning_rate_init': 0.0012220669807227185}, 'best_score': 0.708, 'study': <optuna.study.study.Study at 0x7800a8debf10>},
 ('TOA_15x15_depth_in_3_4',
  'SVR'): {'best_params': {'C': 2.15684226903379,
   'epsilon': 0.12775727625293434}, 'best_score': 0.494, 'study': <optuna.study.study.Study at 0x7800a8dacc40>},
 ('TOA_15x15_depth_in_3_4',
  'KNN'): {'best_params': {'n_neighbors': 7,
   'leaf_size': 31}, 'best_score': 0.649, 'study': <optuna.study.study.Study at 0x7800a9eb7c70>},
 ('TOA_15x15_depth_in_3_4',
  'LR'): {'best_params': {'fit_intercept': False,
   'positive': False}, 'best_score': 0.38, 'study': <optuna.study.study.Study at 0x7800a9f4b820>},
 ('TOA_15x15_depth_in_3_4',
  'RF'): {'best_params': {'n_estimators': 100,
   'max_depth': 10,
   'min_samples_split': 2,
   'min_samples_leaf': 2,
   'bootstrap': True}, 'best_score': 0.617, 'study': <optuna.study.study.Study at 0x7800a8dff730>},
 ('TOA_15x15_depth_in_3_4',
  'CAT'): {'best_params': {'iterations': 2000,
   'learning_rate': 0.05314326154992145,
   'depth': 9,
   'l2_leaf_reg': 1.0213152871705147}, 'best_score': 0.681, 'study': <optuna.study.study.Study at 0x7800a8d816a0>},
 ('TOA_15x15_depth_in_3_4',
  'ELN'): {'best_params': {'alpha': 0.00011287578590294489,
   'l1_ratio': 0.9941527400112994}, 'best_score': 0.505, 'study': <optuna.study.study.Study at 0x7800a8dab1c0>},
 ('C2X-Complex_rhown_5x5_depth_in_3_4',
  'XGB'): {'best_params': {'n_estimators': 2000,
   'learning_rate': 0.045720937679426726,
   'max_depth': 7,
   'min_child_weight': 2,
   'subsample': 0.8049551995941774,
   'colsample_bytree': 0.9077296398951732}, 'best_score': 0.637, 'study': <optuna.study.study.Study at 0x7800a8d94d30>},
 ('C2X-Complex_rhown_5x5_depth_in_3_4',
  'LBM'): {'best_params': {'learning_rate': 0.021490317734639115,
   'num_leaves': 60,
   'max_depth': 7,
   'min_child_samples': 4,
   'subsample': 0.9171600598982209,
   'colsample_bytree': 0.9060991657287198,
   'n_estimators': 500}, 'best_score': 0.623, 'study': <optuna.study.study.Study at 0x7800e4412a90>},
 ('C2X-Complex_rhown_5x5_depth_in_3_4',
  'MLP'): {'best_params': {'hidden_layer_sizes': '256_128',
   'activation': 'relu',
   'solver': 'sgd',
   'alpha': 0.0028311644287798946,
   'learning_rate': 'constant',
   'learning_rate_init': 0.005228148188640056}, 'best_score': 0.618, 'study': <optuna.study.study.Study at 0x7800b018e790>},
 ('C2X-Complex_rhown_5x5_depth_in_3_4',
  'SVR'): {'best_params': {'C': 3.645085787366226,
   'epsilon': 0.18516646571349163}, 'best_score': 0.509, 'study': <optuna.study.study.Study at 0x7800a9673850>},
 ('C2X-Complex_rhown_5x5_depth_in_3_4',
  'KNN'): {'best_params': {'n_neighbors': 10,
   'leaf_size': 34}, 'best_score': 0.571, 'study': <optuna.study.study.Study at 0x7800b00b8e50>},
 ('C2X-Complex_rhown_5x5_depth_in_3_4',
  'LR'): {'best_params': {'fit_intercept': False,
   'positive': True}, 'best_score': 0.537, 'study': <optuna.study.study.Study at 0x7800b04e9340>},
 ('C2X-Complex_rhown_5x5_depth_in_3_4',
  'RF'): {'best_params': {'n_estimators': 500,
   'max_depth': 11,
   'min_samples_split': 4,
   'min_samples_leaf': 2,
   'bootstrap': True}, 'best_score': 0.641, 'study': <optuna.study.study.Study at 0x7800b06798e0>},
 ('C2X-Complex_rhown_5x5_depth_in_3_4',
  'CAT'): {'best_params': {'iterations': 500,
   'learning_rate': 0.025340947072845177,
   'depth': 6,
   'l2_leaf_reg': 5.927927435982809}, 'best_score': 0.603, 'study': <optuna.study.study.Study at 0x7800a9f92b50>},
 ('C2X-Complex_rhown_5x5_depth_in_3_4',
  'ELN'): {'best_params': {'alpha': 0.029440640009221405,
   'l1_ratio': 0.9952562878940697}, 'best_score': 0.573, 'study': <optuna.study.study.Study at 0x7800a9f92fa0>},
 ('C2X-Complex_rhow_9x9_depth_in_3_4',
  'XGB'): {'best_params': {'n_estimators': 500,
   'learning_rate': 0.007784242501186818,
   'max_depth': 6,
   'min_child_weight': 1,
   'subsample': 0.6045990140239461,
   'colsample_bytree': 0.9996062608334324}, 'best_score': 0.616, 'study': <optuna.study.study.Study at 0x7800a8d96a00>},
 ('C2X-Complex_rhow_9x9_depth_in_3_4',
  'LBM'): {'best_params': {'learning_rate': 0.006387333436517826,
   'num_leaves': 80,
   'max_depth': 8,
   'min_child_samples': 13,
   'subsample': 0.6384425602632136,
   'colsample_bytree': 0.6626794560644892,
   'n_estimators': 500}, 'best_score': 0.624, 'study': <optuna.study.study.Study at 0x7800d911cc10>},
 ('C2X-Complex_rhow_9x9_depth_in_3_4',
  'MLP'): {'best_params': {'hidden_layer_sizes': '256_128',
   'activation': 'relu',
   'solver': 'adam',
   'alpha': 0.0014611726954603002,
   'learning_rate': 'constant',
   'learning_rate_init': 0.0006912854086058073}, 'best_score': 0.649, 'study': <optuna.study.study.Study at 0x7800a8dd2790>},
 ('C2X-Complex_rhow_9x9_depth_in_3_4',
  'SVR'): {'best_params': {'C': 9.93157967401947,
   'epsilon': 0.1963107857538181}, 'best_score': 0.598, 'study': <optuna.study.study.Study at 0x7800b036ba60>},
 ('C2X-Complex_rhow_9x9_depth_in_3_4',
  'KNN'): {'best_params': {'n_neighbors': 9,
   'leaf_size': 27}, 'best_score': 0.579, 'study': <optuna.study.study.Study at 0x7800a9eb3460>},
 ('C2X-Complex_rhow_9x9_depth_in_3_4',
  'LR'): {'best_params': {'fit_intercept': False,
   'positive': True}, 'best_score': 0.569, 'study': <optuna.study.study.Study at 0x7800d8f87d90>},
 ('C2X-Complex_rhow_9x9_depth_in_3_4',
  'RF'): {'best_params': {'n_estimators': 100,
   'max_depth': 14,
   'min_samples_split': 3,
   'min_samples_leaf': 1,
   'bootstrap': True}, 'best_score': 0.63, 'study': <optuna.study.study.Study at 0x7800a8e23940>},
 ('C2X-Complex_rhow_9x9_depth_in_3_4',
  'CAT'): {'best_params': {'iterations': 1000,
   'learning_rate': 0.07521844621271666,
   'depth': 5,
   'l2_leaf_reg': 4.739858256733454}, 'best_score': 0.617, 'study': <optuna.study.study.Study at 0x7800b01b6430>},
 ('C2X-Complex_rhow_9x9_depth_in_3_4',
  'ELN'): {'best_params': {'alpha': 0.015126276739043923,
   'l1_ratio': 0.3433210919466816}, 'best_score': 0.589, 'study': <optuna.study.study.Study at 0x7800a9ecdbe0>},
 ('C2X-Complex_rhow_15x15_depth_in_3_4',
  'XGB'): {'best_params': {'n_estimators': 1000,
   'learning_rate': 0.010148550064538592,
   'max_depth': 7,
   'min_child_weight': 1,
   'subsample': 0.7092554975366574,
   'colsample_bytree': 0.9589996114894445}, 'best_score': 0.548, 'study': <optuna.study.study.Study at 0x7800a9f0bc70>},
 ('C2X-Complex_rhow_15x15_depth_in_3_4',
  'LBM'): {'best_params': {'learning_rate': 0.005034271791889273,
   'num_leaves': 60,
   'max_depth': 6,
   'min_child_samples': 11,
   'subsample': 0.9704198407257476,
   'colsample_bytree': 0.8302542907662975,
   'n_estimators': 500}, 'best_score': 0.555, 'study': <optuna.study.study.Study at 0x7800a8e6bf40>},
 ('C2X-Complex_rhow_15x15_depth_in_3_4',
  'MLP'): {'best_params': {'hidden_layer_sizes': '256',
   'activation': 'relu',
   'solver': 'adam',
   'alpha': 0.03673448429184167,
   'learning_rate': 'adaptive',
   'learning_rate_init': 0.005512541724045937}, 'best_score': 0.638, 'study': <optuna.study.study.Study at 0x7800a9f6f5b0>},
 ('C2X-Complex_rhow_15x15_depth_in_3_4',
  'SVR'): {'best_params': {'C': 3.2413369664629386,
   'epsilon': 0.1982961712911414}, 'best_score': 0.584, 'study': <optuna.study.study.Study at 0x7800d8fe5ee0>},
 ('C2X-Complex_rhow_15x15_depth_in_3_4',
  'KNN'): {'best_params': {'n_neighbors': 10,
   'leaf_size': 19}, 'best_score': 0.484, 'study': <optuna.study.study.Study at 0x7800a8e0ebb0>},
 ('C2X-Complex_rhow_15x15_depth_in_3_4',
  'LR'): {'best_params': {'fit_intercept': True,
   'positive': True}, 'best_score': 0.537, 'study': <optuna.study.study.Study at 0x7800a8e796a0>},
 ('C2X-Complex_rhow_15x15_depth_in_3_4',
  'RF'): {'best_params': {'n_estimators': 100,
   'max_depth': 8,
   'min_samples_split': 3,
   'min_samples_leaf': 4,
   'bootstrap': True}, 'best_score': 0.572, 'study': <optuna.study.study.Study at 0x7800a9ec8d30>},
 ('C2X-Complex_rhow_15x15_depth_in_3_4',
  'CAT'): {'best_params': {'iterations': 500,
   'learning_rate': 0.010126948003726963,

**Entrenamiento con los parámetros seleccionados**

In [318]:
results = {}

for nombre_df, df in list(dfs.items()):
    #print(nombre_df)
    df = df.iloc[:,4:]

    # Para usar solamente bandas, sin combinaciones
    # if 'TOA' in nombre_df:
    #     # TOA solamente con las bandas, parece que las combinaciones solo meten ruido
    #     df = df.iloc[:,np.r_[0:14, 58:60]]
    # if 'rhow' in nombre_df and 'rhown' not in nombre_df:
    #     df = df.iloc[:,np.r_[0:9, 53:55]]
    # if 'rhown' in nombre_df:
    #     df = df.iloc[:,np.r_[0:7, 51:53]]

    train, test = train_test_split(df, test_size=0.2, random_state=42, stratify=df["High_Chl"]) # TEST 20% TRAIN 80%
    target = "Chl"

    train, val = train_test_split(train, test_size=0.25, random_state=42, stratify=train["High_Chl"]) # TRAIN 60% VAL 20% TEST%

    X_train = train.drop(columns=[target,"High_Chl"])
    X_val = val.drop(columns=[target, "High_Chl"])
    X_test = test.drop(columns=[target, "High_Chl"])
    y_train = train[target]
    y_val = val[target]
    y_test = test[target]

    
    scaler_X = RobustScaler()
    scaler_y = RobustScaler()
    X_train_scaled = scaler_X.fit_transform(X_train)
    X_val_scaled = scaler_X.transform(X_val)
    X_test_scaled = scaler_X.transform(X_test)
    y_train_scaled = scaler_y.fit_transform(y_train.values.reshape(-1, 1)).ravel()
    
    results[nombre_df] = {name: {'RMSE': None, 'R2': None} for name in models}
    val_preds = {}
    test_preds = {}

    for name, model in models.items():
        print(f"Fitting {name} for {nombre_df}")
        if name in ["MLP", "SVR", "KNN", "LR", "EN"]:
            model.fit(X_train_scaled, y_train_scaled)
            #test_pred = model.predict(X_test_scaled)
            val_pred = scaler_y.inverse_transform(model.predict(X_val_scaled).reshape(-1, 1)).ravel()
            test_pred = scaler_y.inverse_transform(model.predict(X_test_scaled).reshape(-1, 1)).ravel()
        else:
            model.fit(X_train, y_train)
            val_pred = model.predict(X_val)
            test_pred = model.predict(X_test)

        val_preds[name] = val_pred
        test_preds[name] = test_pred

        rmse = np.sqrt(mean_squared_error(y_test, test_pred))
        r2 = r2_score(y_test, test_pred)

        results[nombre_df][name]['RMSE'] = rmse.round(2)
        results[nombre_df][name]['R2'] = r2.round(2)

    # Meta-modelo
    meta_X = np.vstack([val_preds[model] for model in models]).T
    meta_y = y_val.values
    meta_model = Ridge().fit(meta_X, meta_y)

    # Predicción final ensemble
    test_meta_X = np.vstack([test_preds[model] for model in models]).T
    ensemble_pred = meta_model.predict(test_meta_X)

    rmse_ens = np.sqrt(mean_squared_error(y_test, ensemble_pred))
    r2_ens = r2_score(y_test, ensemble_pred)

    results[nombre_df]["Ensemble"] = {
        "RMSE": round(rmse_ens, 2),
        "R2": round(r2_ens, 2)
    }

Fitting XGB for C2RCC_rhow_5x5_depth_lt_1
Fitting LBM for C2RCC_rhow_5x5_depth_lt_1
Fitting MLP for C2RCC_rhow_5x5_depth_lt_1
Fitting SVR for C2RCC_rhow_5x5_depth_lt_1
Fitting KNN for C2RCC_rhow_5x5_depth_lt_1
Fitting LR for C2RCC_rhow_5x5_depth_lt_1
Fitting RF for C2RCC_rhow_5x5_depth_lt_1
Fitting CAT for C2RCC_rhow_5x5_depth_lt_1
Fitting EN for C2RCC_rhow_5x5_depth_lt_1
Fitting XGB for C2X-Complex_rhown_3x3_depth_lt_1
Fitting LBM for C2X-Complex_rhown_3x3_depth_lt_1
Fitting MLP for C2X-Complex_rhown_3x3_depth_lt_1
Fitting SVR for C2X-Complex_rhown_3x3_depth_lt_1
Fitting KNN for C2X-Complex_rhown_3x3_depth_lt_1
Fitting LR for C2X-Complex_rhown_3x3_depth_lt_1
Fitting RF for C2X-Complex_rhown_3x3_depth_lt_1
Fitting CAT for C2X-Complex_rhown_3x3_depth_lt_1
Fitting EN for C2X-Complex_rhown_3x3_depth_lt_1
Fitting XGB for TOA_9x9_depth_lt_1
Fitting LBM for TOA_9x9_depth_lt_1
Fitting MLP for TOA_9x9_depth_lt_1
Fitting SVR for TOA_9x9_depth_lt_1
Fitting KNN for TOA_9x9_depth_lt_1
Fitting LR for TOA_9x9_depth_lt_1
Fitting RF for TOA_9x9_depth_lt_1
Fitting CAT for TOA_9x9_depth_lt_1
Fitting EN for TOA_9x9_depth_lt_1
Fitting XGB for C2X_rhow_3x3_depth_lt_1
Fitting LBM for C2X_rhow_3x3_depth_lt_1
Fitting MLP for C2X_rhow_3x3_depth_lt_1
Fitting SVR for C2X_rhow_3x3_depth_lt_1
Fitting KNN for C2X_rhow_3x3_depth_lt_1
Fitting LR for C2X_rhow_3x3_depth_lt_1
Fitting RF for C2X_rhow_3x3_depth_lt_1
Fitting CAT for C2X_rhow_3x3_depth_lt_1
Fitting EN for C2X_rhow_3x3_depth_lt_1
Fitting XGB for C2RCC_rhow_9x9_depth_lt_1
Fitting LBM for C2RCC_rhow_9x9_depth_lt_1
Fitting MLP for C2RCC_rhow_9x9_depth_lt_1
Fitting SVR for C2RCC_rhow_9x9_depth_lt_1
Fitting KNN for C2RCC_rhow_9x9_depth_lt_1
Fitting LR for C2RCC_rhow_9x9_depth_lt_1
Fitting RF for C2RCC_rhow_9x9_depth_lt_1
Fitting CAT for C2RCC_rhow_9x9_depth_lt_1
Fitting EN for C2RCC_rhow_9x9_depth_lt_1
Fitting XGB for C2X-Complex_rhown_5x5_depth_lt_1
Fitting LBM for C2X-Complex_rhown_5x5_depth_lt_1
Fitting MLP for C2X-Complex_rhown_5x5_depth_lt_1
Fitting SVR for C2X-Complex_rhown_5x5_depth_lt_1
Fitting KNN for C2X-Complex_rhown_5x5_depth_lt_1
Fitting LR for C2X-Complex_rhown_5x5_depth_lt_1
Fitting RF for C2X-Complex_rhown_5x5_depth_lt_1
Fitting CAT for C2X-Complex_rhown_5x5_depth_lt_1
Fitting EN for C2X-Complex_rhown_5x5_depth_lt_1
Fitting XGB for C2X_rhown_9x9_depth_lt_1
Fitting LBM for C2X_rhown_9x9_depth_lt_1
Fitting MLP for C2X_rhown_9x9_depth_lt_1
Fitting SVR for C2X_rhown_9x9_depth_lt_1
Fitting KNN for C2X_rhown_9x9_depth_lt_1
Fitting LR for C2X_rhown_9x9_depth_lt_1
Fitting RF for C2X_rhown_9x9_depth_lt_1
Fitting CAT for C2X_rhown_9x9_depth_lt_1
Fitting EN for C2X_rhown_9x9_depth_lt_1
Fitting XGB for TOA_3x3_depth_lt_1
Fitting LBM for TOA_3x3_depth_lt_1
Fitting MLP for TOA_3x3_depth_lt_1
Fitting SVR for TOA_3x3_depth_lt_1
Fitting KNN for TOA_3x3_depth_lt_1
Fitting LR for TOA_3x3_depth_lt_1
Fitting RF for TOA_3x3_depth_lt_1
Fitting CAT for TOA_3x3_depth_lt_1
Fitting EN for TOA_3x3_depth_lt_1
Fitting XGB for C2X-Complex_rhown_9x9_depth_lt_1
Fitting LBM for C2X-Complex_rhown_9x9_depth_lt_1
Fitting MLP for C2X-Complex_rhown_9x9_depth_lt_1
Fitting SVR for C2X-Complex_rhown_9x9_depth_lt_1
Fitting KNN for C2X-Complex_rhown_9x9_depth_lt_1
Fitting LR for C2X-Complex_rhown_9x9_depth_lt_1
Fitting RF for C2X-Complex_rhown_9x9_depth_lt_1
Fitting CAT for C2X-Complex_rhown_9x9_depth_lt_1
Fitting EN for C2X-Complex_rhown_9x9_depth_lt_1
Fitting XGB for C2X-Complex_rhow_3x3_depth_lt_1
Fitting LBM for C2X-Complex_rhow_3x3_depth_lt_1
Fitting MLP for C2X-Complex_rhow_3x3_depth_lt_1
Fitting SVR for C2X-Complex_rhow_3x3_depth_lt_1
Fitting KNN for C2X-Complex_rhow_3x3_depth_lt_1
Fitting LR for C2X-Complex_rhow_3x3_depth_lt_1
Fitting RF for C2X-Complex_rhow_3x3_depth_lt_1
Fitting CAT for C2X-Complex_rhow_3x3_depth_lt_1
Fitting EN for C2X-Complex_rhow_3x3_depth_lt_1
Fitting XGB for C2X_rhow_1x1_depth_lt_1
Fitting LBM for C2X_rhow_1x1_depth_lt_1
Fitting MLP for C2X_rhow_1x1_depth_lt_1
Fitting SVR for C2X_rhow_1x1_depth_lt_1
Fitting KNN for C2X_rhow_1x1_depth_lt_1
Fitting LR for C2X_rhow_1x1_depth_lt_1
Fitting RF for C2X_rhow_1x1_depth_lt_1
Fitting CAT for C2X_rhow_1x1_depth_lt_1
Fitting EN for C2X_rhow_1x1_depth_lt_1
Fitting XGB for C2RCC_rhown_1x1_depth_lt_1
Fitting LBM for C2RCC_rhown_1x1_depth_lt_1
Fitting MLP for C2RCC_rhown_1x1_depth_lt_1
Fitting SVR for C2RCC_rhown_1x1_depth_lt_1
Fitting KNN for C2RCC_rhown_1x1_depth_lt_1
Fitting LR for C2RCC_rhown_1x1_depth_lt_1
Fitting RF for C2RCC_rhown_1x1_depth_lt_1
Fitting CAT for C2RCC_rhown_1x1_depth_lt_1
Fitting EN for C2RCC_rhown_1x1_depth_lt_1
Fitting XGB for C2X_rhown_1x1_depth_lt_1
Fitting LBM for C2X_rhown_1x1_depth_lt_1
Fitting MLP for C2X_rhown_1x1_depth_lt_1
Fitting SVR for C2X_rhown_1x1_depth_lt_1
Fitting KNN for C2X_rhown_1x1_depth_lt_1
Fitting LR for C2X_rhown_1x1_depth_lt_1
Fitting RF for C2X_rhown_1x1_depth_lt_1
Fitting CAT for C2X_rhown_1x1_depth_lt_1
Fitting EN for C2X_rhown_1x1_depth_lt_1
Fitting XGB for C2RCC_rhown_9x9_depth_lt_1
Fitting LBM for C2RCC_rhown_9x9_depth_lt_1
Fitting MLP for C2RCC_rhown_9x9_depth_lt_1
Fitting SVR for C2RCC_rhown_9x9_depth_lt_1
Fitting KNN for C2RCC_rhown_9x9_depth_lt_1
Fitting LR for C2RCC_rhown_9x9_depth_lt_1
Fitting RF for C2RCC_rhown_9x9_depth_lt_1
Fitting CAT for C2RCC_rhown_9x9_depth_lt_1
Fitting EN for C2RCC_rhown_9x9_depth_lt_1
Fitting XGB for C2X_rhow_5x5_depth_lt_1
Fitting LBM for C2X_rhow_5x5_depth_lt_1
Fitting MLP for C2X_rhow_5x5_depth_lt_1
Fitting SVR for C2X_rhow_5x5_depth_lt_1
Fitting KNN for C2X_rhow_5x5_depth_lt_1
Fitting LR for C2X_rhow_5x5_depth_lt_1
Fitting RF for C2X_rhow_5x5_depth_lt_1
Fitting CAT for C2X_rhow_5x5_depth_lt_1
Fitting EN for C2X_rhow_5x5_depth_lt_1
Fitting XGB for C2X_rhown_5x5_depth_lt_1
Fitting LBM for C2X_rhown_5x5_depth_lt_1
Fitting MLP for C2X_rhown_5x5_depth_lt_1
Fitting SVR for C2X_rhown_5x5_depth_lt_1
Fitting KNN for C2X_rhown_5x5_depth_lt_1
Fitting LR for C2X_rhown_5x5_depth_lt_1
Fitting RF for C2X_rhown_5x5_depth_lt_1
Fitting CAT for C2X_rhown_5x5_depth_lt_1
Fitting EN for C2X_rhown_5x5_depth_lt_1
Fitting XGB for C2X_rhow_9x9_depth_lt_1
Fitting LBM for C2X_rhow_9x9_depth_lt_1
Fitting MLP for C2X_rhow_9x9_depth_lt_1
Fitting SVR for C2X_rhow_9x9_depth_lt_1
Fitting KNN for C2X_rhow_9x9_depth_lt_1
Fitting LR for C2X_rhow_9x9_depth_lt_1
Fitting RF for C2X_rhow_9x9_depth_lt_1
Fitting CAT for C2X_rhow_9x9_depth_lt_1
Fitting EN for C2X_rhow_9x9_depth_lt_1
Fitting XGB for C2X_rhown_3x3_depth_lt_1
Fitting LBM for C2X_rhown_3x3_depth_lt_1
Fitting MLP for C2X_rhown_3x3_depth_lt_1
Fitting SVR for C2X_rhown_3x3_depth_lt_1
Fitting KNN for C2X_rhown_3x3_depth_lt_1
Fitting LR for C2X_rhown_3x3_depth_lt_1
Fitting RF for C2X_rhown_3x3_depth_lt_1
Fitting CAT for C2X_rhown_3x3_depth_lt_1
Fitting EN for C2X_rhown_3x3_depth_lt_1
Fitting XGB for C2RCC_rhown_5x5_depth_lt_1
Fitting LBM for C2RCC_rhown_5x5_depth_lt_1
Fitting MLP for C2RCC_rhown_5x5_depth_lt_1
Fitting SVR for C2RCC_rhown_5x5_depth_lt_1
Fitting KNN for C2RCC_rhown_5x5_depth_lt_1
Fitting LR for C2RCC_rhown_5x5_depth_lt_1
Fitting RF for C2RCC_rhown_5x5_depth_lt_1
Fitting CAT for C2RCC_rhown_5x5_depth_lt_1
Fitting EN for C2RCC_rhown_5x5_depth_lt_1
Fitting XGB for TOA_1x1_depth_lt_1
Fitting LBM for TOA_1x1_depth_lt_1
Fitting MLP for TOA_1x1_depth_lt_1
Fitting SVR for TOA_1x1_depth_lt_1
Fitting KNN for TOA_1x1_depth_lt_1
Fitting LR for TOA_1x1_depth_lt_1
Fitting RF for TOA_1x1_depth_lt_1
Fitting CAT for TOA_1x1_depth_lt_1
Fitting EN for TOA_1x1_depth_lt_1
Fitting XGB for C2X-Complex_rhow_5x5_depth_lt_1
Fitting LBM for C2X-Complex_rhow_5x5_depth_lt_1
Fitting MLP for C2X-Complex_rhow_5x5_depth_lt_1
Fitting SVR for C2X-Complex_rhow_5x5_depth_lt_1
Fitting KNN for C2X-Complex_rhow_5x5_depth_lt_1
Fitting LR for C2X-Complex_rhow_5x5_depth_lt_1
Fitting RF for C2X-Complex_rhow_5x5_depth_lt_1
Fitting CAT for C2X-Complex_rhow_5x5_depth_lt_1
Fitting EN for C2X-Complex_rhow_5x5_depth_lt_1
Fitting XGB for C2X-Complex_rhow_9x9_depth_lt_1
Fitting LBM for C2X-Complex_rhow_9x9_depth_lt_1
Fitting MLP for C2X-Complex_rhow_9x9_depth_lt_1
Fitting SVR for C2X-Complex_rhow_9x9_depth_lt_1
Fitting KNN for C2X-Complex_rhow_9x9_depth_lt_1
Fitting LR for C2X-Complex_rhow_9x9_depth_lt_1
Fitting RF for C2X-Complex_rhow_9x9_depth_lt_1
Fitting CAT for C2X-Complex_rhow_9x9_depth_lt_1
Fitting EN for C2X-Complex_rhow_9x9_depth_lt_1
Fitting XGB for C2X-Complex_rhow_1x1_depth_lt_1
Fitting LBM for C2X-Complex_rhow_1x1_depth_lt_1
Fitting MLP for C2X-Complex_rhow_1x1_depth_lt_1
Fitting SVR for C2X-Complex_rhow_1x1_depth_lt_1
Fitting KNN for C2X-Complex_rhow_1x1_depth_lt_1
Fitting LR for C2X-Complex_rhow_1x1_depth_lt_1
Fitting RF for C2X-Complex_rhow_1x1_depth_lt_1
Fitting CAT for C2X-Complex_rhow_1x1_depth_lt_1
Fitting EN for C2X-Complex_rhow_1x1_depth_lt_1
Fitting XGB for C2X-Complex_rhown_1x1_depth_lt_1
Fitting LBM for C2X-Complex_rhown_1x1_depth_lt_1
Fitting MLP for C2X-Complex_rhown_1x1_depth_lt_1
Fitting SVR for C2X-Complex_rhown_1x1_depth_lt_1
Fitting KNN for C2X-Complex_rhown_1x1_depth_lt_1
Fitting LR for C2X-Complex_rhown_1x1_depth_lt_1
Fitting RF for C2X-Complex_rhown_1x1_depth_lt_1
Fitting CAT for C2X-Complex_rhown_1x1_depth_lt_1
Fitting EN for C2X-Complex_rhown_1x1_depth_lt_1
Fitting XGB for C2RCC_rhow_3x3_depth_lt_1
Fitting LBM for C2RCC_rhow_3x3_depth_lt_1
Fitting MLP for C2RCC_rhow_3x3_depth_lt_1
Fitting SVR for C2RCC_rhow_3x3_depth_lt_1
Fitting KNN for C2RCC_rhow_3x3_depth_lt_1
Fitting LR for C2RCC_rhow_3x3_depth_lt_1
Fitting RF for C2RCC_rhow_3x3_depth_lt_1
Fitting CAT for C2RCC_rhow_3x3_depth_lt_1
Fitting EN for C2RCC_rhow_3x3_depth_lt_1
Fitting XGB for TOA_5x5_depth_lt_1
Fitting LBM for TOA_5x5_depth_lt_1
Fitting MLP for TOA_5x5_depth_lt_1
Fitting SVR for TOA_5x5_depth_lt_1
Fitting KNN for TOA_5x5_depth_lt_1
Fitting LR for TOA_5x5_depth_lt_1
Fitting RF for TOA_5x5_depth_lt_1
Fitting CAT for TOA_5x5_depth_lt_1
Fitting EN for TOA_5x5_depth_lt_1
Fitting XGB for C2RCC_rhown_3x3_depth_lt_1
Fitting LBM for C2RCC_rhown_3x3_depth_lt_1
Fitting MLP for C2RCC_rhown_3x3_depth_lt_1
Fitting SVR for C2RCC_rhown_3x3_depth_lt_1
Fitting KNN for C2RCC_rhown_3x3_depth_lt_1
Fitting LR for C2RCC_rhown_3x3_depth_lt_1
Fitting RF for C2RCC_rhown_3x3_depth_lt_1
Fitting CAT for C2RCC_rhown_3x3_depth_lt_1
Fitting EN for C2RCC_rhown_3x3_depth_lt_1
Fitting XGB for C2RCC_rhow_1x1_depth_lt_1
Fitting LBM for C2RCC_rhow_1x1_depth_lt_1
Fitting MLP for C2RCC_rhow_1x1_depth_lt_1
Fitting SVR for C2RCC_rhow_1x1_depth_lt_1
Fitting KNN for C2RCC_rhow_1x1_depth_lt_1
Fitting LR for C2RCC_rhow_1x1_depth_lt_1
Fitting RF for C2RCC_rhow_1x1_depth_lt_1
Fitting CAT for C2RCC_rhow_1x1_depth_lt_1
Fitting EN for C2RCC_rhow_1x1_depth_lt_1

In [329]:
rows = []

for df_name, model_scores in results.items():
    row = {}
    for model_name, metrics in model_scores.items():
        for metric_name, values in metrics.items():
            if isinstance(values, list):  # Solo para los que tienen listas (folds)
                mean_val = np.mean(values)
                std_val = np.std(values)
                row[(metric_name, model_name)] = f"{mean_val:.2f} ± {std_val:.2f}"
            else:
                # Para el ensemble que tiene un único valor
                row[(metric_name, model_name)] = f"{values:.2f}"
    rows.append((df_name, row))

df_results = pd.DataFrame.from_dict(dict(rows), orient="index")
df_results.columns = pd.MultiIndex.from_tuples(df_results.columns, names=["Metric", "Model"])
df_results = df_results.sort_index(axis=1, level=0)
df_results = df_results.sort_index(axis=0)

In [330]:
df_results

Metric                                     R2                         \
Model                                     CAT           EN  Ensemble
C2RCC_rhow_5x5_depth_lt_1         0.67 ± 0.13  0.48 ± 0.07      0.61
C2X-Complex_rhown_3x3_depth_lt_1  0.66 ± 0.12  0.50 ± 0.06  -6049.03
TOA_9x9_depth_lt_1                0.78 ± 0.12  0.19 ± 0.13      0.46

Metric                                                                    \
Model                                     KNN          LBM            LR
C2RCC_rhow_5x5_depth_lt_1         0.74 ± 0.10  0.61 ± 0.24   0.31 ± 0.52
C2X-Complex_rhown_3x3_depth_lt_1  0.59 ± 0.12  0.55 ± 0.17  -1.12 ± 3.18
TOA_9x9_depth_lt_1                0.76 ± 0.13  0.70 ± 0.09   0.18 ± 0.36

Metric                                                                   \
Model                                     MLP           RF          SVR
C2RCC_rhow_5x5_depth_lt_1         0.71 ± 0.12  0.63 ± 0.18  0.66 ± 0.15
C2X-Complex_rhown_3x3_depth_lt_1  0.45 ± 0.08  0.63 ± 0.11  0.53 ± 0.09
TOA_9x9_depth_lt_1                0.65 ± 0.14  0.70 ± 0.13  0.50 ± 0.04

Metric                                                RMSE               \
Model                                     XGB          CAT           EN
C2RCC_rhow_5x5_depth_lt_1         0.65 ± 0.19  2.04 ± 0.37  2.64 ± 0.20
C2X-Complex_rhown_3x3_depth_lt_1  0.61 ± 0.17  2.08 ± 0.17  2.63 ± 0.41
TOA_9x9_depth_lt_1                0.72 ± 0.12  1.80 ± 0.49  3.58 ± 0.15

Metric                                                               \
Model                            Ensemble          KNN          LBM
C2RCC_rhow_5x5_depth_lt_1            2.97  1.81 ± 0.21  2.16 ± 0.50
C2X-Complex_rhown_3x3_depth_lt_1   370.82  2.30 ± 0.17  2.41 ± 0.25
TOA_9x9_depth_lt_1                   2.59  1.87 ± 0.37  2.15 ± 0.32

Metric                                                                   \
Model                                      LR          MLP           RF
C2RCC_rhow_5x5_depth_lt_1         2.83 ± 0.72  1.93 ± 0.27  2.14 ± 0.35
C2X-Complex_rhown_3x3_depth_lt_1  4.08 ± 2.64  2.77 ± 0.44  2.21 ± 0.17
TOA_9x9_depth_lt_1                3.49 ± 0.48  2.31 ± 0.28  2.12 ± 0.39

Metric
Model                                     SVR          XGB
C2RCC_rhow_5x5_depth_lt_1         2.08 ± 0.31  2.08 ± 0.44
C2X-Complex_rhown_3x3_depth_lt_1  2.52 ± 0.31  2.21 ± 0.28
TOA_9x9_depth_lt_1                2.84 ± 0.26  2.05 ± 0.44