In [70]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import os
pd.options.mode.chained_assignment = None
import optuna
import time
from sklearn.metrics import r2_score, mean_squared_error
from sklearn.model_selection import cross_val_score, KFold, StratifiedKFold, train_test_split
from xgboost import XGBRegressor
from catboost import CatBoostRegressor
from lightgbm import LGBMRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression, Ridge, ElasticNet
from sklearn.neighbors import KNeighborsRegressor
from sklearn.neural_network import MLPRegressor
from sklearn.svm import SVR
from sklearn.preprocessing import StandardScaler, RobustScaler
import pickle
from collections import defaultdict

In [71]:
depths = ["in_0_1"] #"in_1_2", "in_2_3", "in_3_4"]
for depth in depths: 
    # Cargamos los csv de los tifs
    path = "saved_files/dataset"
    dfs = {}
    for archivo in os.listdir(path):
        if archivo.endswith(f"{depth}_features.csv"):
            nombre_sin_extension = os.path.splitext(archivo)[0]  # sin .csv
            ruta_completa = os.path.join(path, archivo)
            dfs[nombre_sin_extension[:-9]] = pd.read_csv(ruta_completa)



    # Limpiamos valores nulos
    for nombre_df, df in dfs.items():
        for band_set in ["rhow", "rhown","rtoa"]:
            dfs[nombre_df] = df.dropna()

    dfs_to_keep = [
		'C2X-Complex_rhow_9x9_depth_in_0_1', 
		'TOA_15x15_depth_in_0_1',
		'C2X-Complex_rhown_9x9_depth_in_0_1',
		# 'C2X-Complex_rhow_5x5_depth_in_0_1',
		# 'C2RCC_rhow_5x5_depth_in_0_1',
		# 'C2RCC_rhow_15x15_depth_in_0_1', 
		# 'C2X-Complex_rhown_15x15_depth_in_0_1',
		# 'C2RCC_rhown_5x5_depth_in_0_1', 
		# 'C2X-Complex_rhow_15x15_depth_in_0_1',
		# 'C2RCC_rhow_9x9_depth_in_0_1',
		# 'C2X-Complex_rhow_5x5_depth_in_1_2', 
		# 'C2X_rhow_3x3_depth_in_1_2',
		# 'C2X-Complex_rhown_5x5_depth_in_1_2',
		# 'C2X-Complex_rhow_9x9_depth_in_1_2',
		# 'C2X-Complex_rhow_3x3_depth_in_1_2',
		# 'C2X-Complex_rhown_3x3_depth_in_1_2',
		# 'C2RCC_rhown_3x3_depth_in_1_2',
		# 'C2X-Complex_rhown_9x9_depth_in_1_2',
		# 'C2X-Complex_rhow_15x15_depth_in_1_2', 
		# 'C2X_rhow_5x5_depth_in_1_2',
        # 'TOA_15x15_depth_in_2_3',
		# 'TOA_9x9_depth_in_2_3',
		# 'TOA_5x5_depth_in_2_3', 
		# 'C2X-Complex_rhow_5x5_depth_in_2_3',
		# 'C2RCC_rhown_5x5_depth_in_2_3', 
		# 'TOA_3x3_depth_in_2_3',
		# 'C2X-Complex_rhown_5x5_depth_in_2_3', 
		# 'C2RCC_rhow_3x3_depth_in_2_3',
		# 'C2X-Complex_rhown_9x9_depth_in_2_3', 
		# 'C2X_rhow_9x9_depth_in_2_3',
        # 'TOA_9x9_depth_in_3_4',
		# 'TOA_3x3_depth_in_3_4',
		# 'TOA_5x5_depth_in_3_4',
		# 'C2X-Complex_rhow_5x5_depth_in_3_4', 
		# 'TOA_1x1_depth_in_3_4',
		# 'TOA_15x15_depth_in_3_4',
		# 'C2X-Complex_rhown_5x5_depth_in_3_4',
		# 'C2X-Complex_rhow_9x9_depth_in_3_4',
		# 'C2X-Complex_rhow_15x15_depth_in_3_4',
		# 'C2X-Complex_rhown_9x9_depth_in_3_4'
        ]

    dfs = {k: dfs[k] for k in dfs_to_keep if k in dfs}


    for nombre_df, df in dfs.items():
        # Marcamos las columnas de CHl alta (equivalente a quantile(0.93))
        df["High_Chl"] = df["Chl"]>5
        # Sacamos la estación de cada fecha
        df['Date'] = pd.to_datetime(df['Date'])
        def get_season(month):
            if month in [12, 1, 2]:
                return 'Invierno'
            elif month in [3, 4, 5]:
                return 'Primavera'
            elif month in [6, 7, 8]:
                return 'Verano'
            else:
                return 'Otoño'
        df['Season'] = df['Date'].dt.month.apply(get_season)
        for col in df.select_dtypes(include='object').columns:
            df[col] = df[col].astype('category')
        df = pd.concat([df.drop(columns=["Season"]),pd.get_dummies(df["Season"])], axis=1)
        dfs[nombre_df] = df

### Optimización de hiperparámetros

In [80]:
def objective(trial, df, nombre_df, target, model_name):
    # Mismo proceso que para validación cruzada, pero haciendo preds solamente sobre test
    FOLDS = 3
    # Para hacer clip a las predicciones y forzar > 0
    correct = True
    results = {}

    df = df.iloc[:, 4:]

    # Separamos el conjunto de datos en train y test: Train 75% Test 25%
    train, test = train_test_split(df, test_size=0.25, random_state=42, stratify=df["High_Chl"])
    # Seleccionamos la columna que queremos predecir
    target = "Chl"

    # Quitamos esa columna y el indicador de clorofila alta
    X = train.drop(columns=[target, "High_Chl", "Turbidez"])
    # Para y cogemos solamente Chl
    y = train[target]
    # Para poder hacer StratifiedKFold y tener el mismo número de valores de Chl alta en cada fold
    y_class = train["High_Chl"]

    # Definimos X e y para test
    #X_test = test.drop(columns=[target, "High_Chl", "Turbidez"])
    #y_test = test[target]

    # Dicts para guardar las predicciones sobre los conjuntos de validación, las y's correspondientes y los índices que corresponden dentro del loop de folds para el ensemble
    val_preds = {name: np.zeros(len(train)) for name in models}
    y_vals = defaultdict(list)
    val_indices = {}
    # Dict para guardar las predicciones sobre test
    #test_preds = {name: np.zeros(len(test)) for name in models}
    
    # Dict para guardar resultados
    results[nombre_df] = {name: {'RMSE': [], 'R2': []} for name in models}
    skf = StratifiedKFold(n_splits=FOLDS, shuffle=True, random_state=42)

    if model_name == "LBM":
        params = {
            'objective': 'regression',
            'metric': 'rmse',
            'boosting_type': 'gbdt',
            'device': 'cpu',  # usa CPU/GPU
            'verbosity': -1,
            'learning_rate': trial.suggest_categorical('learning_rate', [0.02, 0.03, 0.04, 0.05]),
            'num_leaves': trial.suggest_categorical('num_leaves', [10, 20, 30]),
            'max_depth': trial.suggest_int('max_depth', 5, 8),
            'min_child_samples': trial.suggest_int('min_child_samples', 4, 8),
            'subsample': trial.suggest_float('subsample', 0.6, 0.8),
            'colsample_bytree': trial.suggest_float('colsample_bytree', 0.6, 0.8),
            'n_estimators': trial.suggest_categorical('n_estimators', [750, 1000, 1250]),
            # 'reg_alpha': trial.suggest_float('reg_alpha', 1e-3, 10.0, log=True),
            # 'reg_lambda': trial.suggest_float('reg_lambda', 1e-3, 10.0, log=True),
            'min_split_gain': trial.suggest_categorical('min_split_gain', [0.0, 0.1, 0.2, 0.5, 1.0])
        }

    if model_name == "XGB":
        params = {
            # 'n_estimators': trial.suggest_categorical('n_estimators', [750, 1000, 1250]),
            # 'learning_rate': trial.suggest_categorical('learning_rate', [0.01, 0.02, 0.03]),
            # 'max_depth': trial.suggest_int('max_depth', 5, 8),
            # 'min_child_weight': trial.suggest_int('min_child_weight', 2, 4),
            # 'subsample': trial.suggest_float('subsample', 0.6, 0.8),
            #'colsample_bytree': trial.suggest_float('colsample_bytree', 0.6, 0.8),
            'n_estimators': 1000,
            'learning_rate': 0.02,
            'max_depth': trial.suggest_int('max_depth', 6, 7),
            'min_child_weight': 2,
            'subsample': 0.7,
            'colsample_bytree': 0.7,
            # 'reg_alpha': trial.suggest_float('reg_alpha', 1e-3, 10.0, log=True),
            # 'reg_lambda': trial.suggest_float('reg_lambda', 1e-3, 10.0, log=True),
            'device': 'cpu',
            'objective': 'reg:squarederror',
            'tree_method': 'hist',
            'enable_categorical': True,
            'eval_metric': 'rmse'
        }
    
    if model_name == "MLP":
        # Así para evitar warning de definir como tuple
        hidden_options = {
            '32': (32,),
            '64': (64,),
            '128': (128,),
            '64_16': (64, 16)
        }
        hidden_layer_sizes = trial.suggest_categorical('hidden_layer_sizes', list(hidden_options.values()))
        params = {
            'hidden_layer_sizes': hidden_layer_sizes,
            #'hidden_layer_sizes': trial.suggest_categorical('hidden_layer_sizes', [(50,), (100,), (100, 50), (128, 64)]),
            'activation': trial.suggest_categorical('activation', ['relu', 'tanh']),
            'solver': trial.suggest_categorical('solver', ['adam', 'sgd']),
            'alpha': trial.suggest_float('alpha', 1e-5, 0.1, log=True),
            'learning_rate': trial.suggest_categorical('learning_rate', ['constant', 'adaptive']),
            'learning_rate_init': trial.suggest_float('learning_rate_init', 1e-4, 1e-2, log=True),
            'max_iter': 200,
            'n_iter_no_change': 25,
            'early_stopping': True,
            'validation_fraction': 0.2,
            'random_state': 42,
            'verbose': False
        }

    if model_name == "SVR":
        params = {
            'kernel': 'rbf',
            'C': trial.suggest_float('C', 0.1, 10.0, log=True),
            'epsilon': trial.suggest_float('epsilon', 0.01, 0.2),
            'gamma': 'scale',
            'shrinking': True,
            'tol': 1e-3,
            'max_iter': -1,
            'verbose': False
        }

    if model_name == "KNN":
        params = {
            'n_neighbors': trial.suggest_int('n_neighbors', 3, 12),
            'weights': 'distance',
            'algorithm': 'auto',
            'leaf_size': trial.suggest_int('leaf_size', 10, 40),
            'p': 2,  # 1 = manhattan, 2 = euclídea
            'metric': 'minkowski',
            'n_jobs': -1
        }

    if model_name == "LR":
        # No sirve de mucho, pero por completitud
        params = {
            'fit_intercept': trial.suggest_categorical('fit_intercept', [True, False]),
            'positive': trial.suggest_categorical('positive', [True, False]),
        }

    if model_name == "RF":
        params = {
            'n_estimators': trial.suggest_categorical('n_estimators', [100, 200, 400]),
            'max_depth': trial.suggest_int('max_depth', 5, 12),
            'min_samples_split': trial.suggest_int('min_samples_split', 2, 8),
            'min_samples_leaf': trial.suggest_int('min_samples_leaf', 2, 8),
            'bootstrap': trial.suggest_categorical('bootstrap', [True, False]),
            'random_state': 42,
            'verbose': 0
        }

    if model_name == "CAT":
        params = {
            'iterations': trial.suggest_categorical('iterations', [500, 750, 1000]),
            'learning_rate': trial.suggest_categorical('learning_rate', [0.02, 0.03, 0.04, 0.05]),
            'depth': trial.suggest_int('depth', 4, 8),
            'l2_leaf_reg': trial.suggest_float('l2_leaf_reg', 1.0, 5.0),
            'loss_function': 'RMSE',
            'eval_metric': 'RMSE',
            'random_seed': 42,
            'early_stopping_rounds': 50,
            'verbose': False
        }

    if model_name == "ELN":
        params = {
            'alpha': trial.suggest_float('alpha', 1e-4, 1.0, log=True),
            'l1_ratio': trial.suggest_float('l1_ratio', 0.1, 0.9),
            'fit_intercept': True,
            'max_iter': 1000,
            'tol': 1e-4,
            'selection': 'cyclic',
            'random_state': 42
        }

    # Cargamos el modelo correspondiente
    model = models[model_name](**params)

    for fold, (train_idx, val_idx) in enumerate(skf.split(X, y_class)):
        print(f"Fold {fold+1}")
        X_train, X_val = X.iloc[train_idx], X.iloc[val_idx]
        y_train, y_val = y.iloc[train_idx], y.iloc[val_idx]

        if model_name in ["MLP", "SVR", "KNN", "LR", "ELN"]:
            scaler_X = RobustScaler()
            scaler_y = RobustScaler()
            X_train_scaled = scaler_X.fit_transform(X_train)
            X_val_scaled = scaler_X.transform(X_val)
            #X_test_scaled = scaler_X.transform(X_test)
            y_train_scaled = scaler_y.fit_transform(y_train.values.reshape(-1, 1)).ravel()
            model.fit(X_train_scaled, y_train_scaled)
            val_pred = scaler_y.inverse_transform(model.predict(X_val_scaled).reshape(-1, 1)).ravel()
            #test_pred = scaler_y.inverse_transform(model.predict(X_test_scaled).reshape(-1, 1)).ravel()

        else:
            model.fit(X_train, y_train)
            val_pred = model.predict(X_val)
            #test_pred = model.predict(X_test)

        if correct:
            val_pred = np.clip(val_pred, 0.2, None)
            #test_pred = np.clip(test_pred, 0.2, None)

        val_preds[model_name][val_idx] = val_pred
        if model_name == list(models.keys())[0]:
            # Solo lo guardamos una vez
            y_vals[fold] = y_val
            val_indices[fold] = val_idx

        rmse = np.sqrt(mean_squared_error(y_val, val_pred))
        r2 = r2_score(y_val, val_pred)
        results[nombre_df][model_name]['RMSE'].append(rmse)
        results[nombre_df][model_name]['R2'].append(r2)
        #test_preds[model_name] += test_pred / FOLDS

    #rmse_test = np.sqrt(mean_squared_error(y_test, test_preds[model_name]))
    r2 = np.mean(results[nombre_df][model_name]["R2"])

    return r2

In [81]:

models = {
    "XGB": XGBRegressor,
    "LBM": LGBMRegressor,
    "MLP": MLPRegressor,
    "SVR": SVR,
    "KNN": KNeighborsRegressor,
    "LR": LinearRegression,
    "RF": RandomForestRegressor,
    "CAT": CatBoostRegressor,
    "ELN":  ElasticNet
}

def run_optuna(df, nombre_df, target, n_trials, model_name):
    results = {}

    print(f"Buscando mejores hiperparámetros para {model_name} con {nombre_df}...")
    study = optuna.create_study(direction='maximize')
    study.optimize(lambda trial: objective(trial, df, nombre_df, target, model_name), n_trials=n_trials, timeout= 1500)
    
    print(f"\n✅ {model_name} con {nombre_df} - Mejor R2: {study.best_value:.2f}")
    print(f"📋 Parámetros: {study.best_params}\n")
    
    results[model_name] = {
        'best_params': study.best_params,
        'best_score': np.round(study.best_value, 3)
    }
    return results

In [82]:


depths = ["in_0_1"]#, "in_1_2", "in_2_3", "in_3_4"]
for depth in depths: 
    # Cargamos los csv de los tifs
    path = "saved_files/dataset"
    dfs = {}
    for archivo in os.listdir(path):
        if archivo.endswith(f"{depth}_features.csv"):
            nombre_sin_extension = os.path.splitext(archivo)[0]  # sin .csv
            ruta_completa = os.path.join(path, archivo)
            dfs[nombre_sin_extension[:-9]] = pd.read_csv(ruta_completa)


    # Limpiamos valores nulos
    for nombre_df, df in dfs.items():
        for band_set in ["rhow", "rhown","rtoa"]:
            dfs[nombre_df] = df.dropna()

    dfs_to_keep = [
		'C2X-Complex_rhow_9x9_depth_in_0_1', 
		'TOA_15x15_depth_in_0_1',
		'C2X-Complex_rhown_9x9_depth_in_0_1',
		'C2X-Complex_rhow_5x5_depth_in_0_1',
		'C2RCC_rhow_5x5_depth_in_0_1',
		'C2RCC_rhow_15x15_depth_in_0_1', 
		'C2X-Complex_rhown_15x15_depth_in_0_1',
		'C2RCC_rhown_5x5_depth_in_0_1', 
		'C2X-Complex_rhow_15x15_depth_in_0_1',
		'C2RCC_rhow_9x9_depth_in_0_1',
		# 'C2X-Complex_rhow_5x5_depth_in_1_2', 
		# 'C2X_rhow_3x3_depth_in_1_2',
		# 'C2X-Complex_rhown_5x5_depth_in_1_2',
		# 'C2X-Complex_rhow_9x9_depth_in_1_2',
		# 'C2X-Complex_rhow_3x3_depth_in_1_2',
		# 'C2X-Complex_rhown_3x3_depth_in_1_2',
		# 'C2RCC_rhown_3x3_depth_in_1_2',
		# 'C2X-Complex_rhown_9x9_depth_in_1_2',
		# 'C2X-Complex_rhow_15x15_depth_in_1_2', 
		# 'C2X_rhow_5x5_depth_in_1_2',
        # 'TOA_15x15_depth_in_2_3',
		# 'TOA_9x9_depth_in_2_3',
		# 'TOA_5x5_depth_in_2_3', 
		# 'C2X-Complex_rhow_5x5_depth_in_2_3',
		# 'C2RCC_rhown_5x5_depth_in_2_3', 
		# 'TOA_3x3_depth_in_2_3',
		# 'C2X-Complex_rhown_5x5_depth_in_2_3', 
		# 'C2RCC_rhow_3x3_depth_in_2_3',
		# 'C2X-Complex_rhown_9x9_depth_in_2_3', 
		# 'C2X_rhow_9x9_depth_in_2_3',
        # 'TOA_9x9_depth_in_3_4',
		# 'TOA_3x3_depth_in_3_4',
		# 'TOA_5x5_depth_in_3_4',
		# 'C2X-Complex_rhow_5x5_depth_in_3_4', 
		# 'TOA_1x1_depth_in_3_4',
		# 'TOA_15x15_depth_in_3_4',
		# 'C2X-Complex_rhown_5x5_depth_in_3_4',
		# 'C2X-Complex_rhow_9x9_depth_in_3_4',
		# 'C2X-Complex_rhow_15x15_depth_in_3_4',
		# 'C2X-Complex_rhown_9x9_depth_in_3_4'
        ]

    dfs = {k: dfs[k] for k in dfs_to_keep if k in dfs}


    for nombre_df, df in dfs.items():
        # Marcamos las columnas de CHl alta (equivalente a quantile(0.93))
        df["High_Chl"] = df["Chl"]>5
        # Sacamos la estación de cada fecha
        df['Date'] = pd.to_datetime(df['Date'])
        def get_season(month):
            if month in [12, 1, 2]:
                return 'Invierno'
            elif month in [3, 4, 5]:
                return 'Primavera'
            elif month in [6, 7, 8]:
                return 'Verano'
            else:
                return 'Otoño'
        df['Season'] = df['Date'].dt.month.apply(get_season)
        for col in df.select_dtypes(include='object').columns:
            df[col] = df[col].astype('category')
        df = pd.concat([df.drop(columns=["Season"]),pd.get_dummies(df["Season"])], axis=1)
        dfs[nombre_df] = df

In [83]:

n_trials = 30
global_results = {}
for nombre_df, df in list(dfs.items()):
    for model_name in models.keys():
        key = (nombre_df, model_name)
        result = run_optuna(df, nombre_df, "Chl", n_trials, model_name)
        global_results[key] = result[model_name]

with open(f"training_results/selection_results_{depth}.pkl", "wb") as f:
    pickle.dump(global_results, f)

[I 2025-09-08 13:24:21,741] A new study created in memory with name: no-name-1732c2eb-27c3-4105-835f-487a1ceef329

Buscando mejores hiperparámetros para XGB con C2X-Complex_rhow_9x9_depth_in_0_1...
Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:24:29,279] Trial 0 finished with value: 0.6030748460338842 and parameters: {'n_estimators': 1250, 'learning_rate': 0.01, 'max_depth': 8, 'min_child_weight': 2, 'subsample': 0.7392049054441077, 'colsample_bytree': 0.7744599140950612}. Best is trial 0 with value: 0.6030748460338842.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:24:31,703] Trial 1 finished with value: 0.6414428239853286 and parameters: {'n_estimators': 750, 'learning_rate': 0.02, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.6473570761617794, 'colsample_bytree': 0.7591524448975372}. Best is trial 1 with value: 0.6414428239853286.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:24:36,306] Trial 2 finished with value: 0.6172154031022724 and parameters: {'n_estimators': 750, 'learning_rate': 0.02, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.7848313874154655, 'colsample_bytree': 0.6770212871754104}. Best is trial 1 with value: 0.6414428239853286.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:24:39,737] Trial 3 finished with value: 0.6439058429711523 and parameters: {'n_estimators': 1000, 'learning_rate': 0.02, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.6316347803907552, 'colsample_bytree': 0.7631933898770786}. Best is trial 3 with value: 0.6439058429711523.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:24:45,127] Trial 4 finished with value: 0.6117168988057434 and parameters: {'n_estimators': 1250, 'learning_rate': 0.03, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.7625675078003316, 'colsample_bytree': 0.7126178645298611}. Best is trial 3 with value: 0.6439058429711523.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:24:49,627] Trial 5 finished with value: 0.615274054207316 and parameters: {'n_estimators': 1250, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.7430189796046753, 'colsample_bytree': 0.7209129067863018}. Best is trial 3 with value: 0.6439058429711523.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:24:54,365] Trial 6 finished with value: 0.6318882044328117 and parameters: {'n_estimators': 1250, 'learning_rate': 0.02, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.7665753307249026, 'colsample_bytree': 0.6550066906700343}. Best is trial 3 with value: 0.6439058429711523.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:24:59,901] Trial 7 finished with value: 0.6285984657891234 and parameters: {'n_estimators': 1000, 'learning_rate': 0.02, 'max_depth': 8, 'min_child_weight': 2, 'subsample': 0.6581624142064815, 'colsample_bytree': 0.7949153208464632}. Best is trial 3 with value: 0.6439058429711523.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:25:05,441] Trial 8 finished with value: 0.60213081443912 and parameters: {'n_estimators': 1250, 'learning_rate': 0.02, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.7421205046674721, 'colsample_bytree': 0.7774617745106861}. Best is trial 3 with value: 0.6439058429711523.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:25:08,227] Trial 9 finished with value: 0.6283984986702061 and parameters: {'n_estimators': 750, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.7169604562677948, 'colsample_bytree': 0.6500697167246878}. Best is trial 3 with value: 0.6439058429711523.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:25:12,076] Trial 10 finished with value: 0.6556418238073364 and parameters: {'n_estimators': 1000, 'learning_rate': 0.03, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.6016293047849552, 'colsample_bytree': 0.6187862830762235}. Best is trial 10 with value: 0.6556418238073364.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:25:16,089] Trial 11 finished with value: 0.6577230500902366 and parameters: {'n_estimators': 1000, 'learning_rate': 0.03, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.6046027494752703, 'colsample_bytree': 0.6053587688897054}. Best is trial 11 with value: 0.6577230500902366.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:25:19,537] Trial 12 finished with value: 0.6627426606183683 and parameters: {'n_estimators': 1000, 'learning_rate': 0.03, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.6110891121680128, 'colsample_bytree': 0.602586920149331}. Best is trial 12 with value: 0.6627426606183683.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:25:23,604] Trial 13 finished with value: 0.6655818712479834 and parameters: {'n_estimators': 1000, 'learning_rate': 0.03, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.6001013071833111, 'colsample_bytree': 0.602524118946164}. Best is trial 13 with value: 0.6655818712479834.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:25:27,533] Trial 14 finished with value: 0.6469860712547356 and parameters: {'n_estimators': 1000, 'learning_rate': 0.03, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.6831750650843448, 'colsample_bytree': 0.6292765762350561}. Best is trial 13 with value: 0.6655818712479834.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:25:32,203] Trial 15 finished with value: 0.6420505932778645 and parameters: {'n_estimators': 1000, 'learning_rate': 0.03, 'max_depth': 8, 'min_child_weight': 4, 'subsample': 0.6278620877156669, 'colsample_bytree': 0.6037652909390244}. Best is trial 13 with value: 0.6655818712479834.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:25:36,251] Trial 16 finished with value: 0.6470822964856954 and parameters: {'n_estimators': 1000, 'learning_rate': 0.03, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.6792124930082147, 'colsample_bytree': 0.6381996382622872}. Best is trial 13 with value: 0.6655818712479834.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:25:39,787] Trial 17 finished with value: 0.6461646908310151 and parameters: {'n_estimators': 1000, 'learning_rate': 0.03, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.6205452140904126, 'colsample_bytree': 0.6891356882273005}. Best is trial 13 with value: 0.6655818712479834.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:25:44,376] Trial 18 finished with value: 0.6424925337813346 and parameters: {'n_estimators': 1000, 'learning_rate': 0.03, 'max_depth': 8, 'min_child_weight': 3, 'subsample': 0.6605022795761165, 'colsample_bytree': 0.6674174000486967}. Best is trial 13 with value: 0.6655818712479834.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:25:48,002] Trial 19 finished with value: 0.631963385569177 and parameters: {'n_estimators': 1000, 'learning_rate': 0.03, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.7033364088933525, 'colsample_bytree': 0.6008530997367202}. Best is trial 13 with value: 0.6655818712479834.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:25:50,493] Trial 20 finished with value: 0.6317305602445608 and parameters: {'n_estimators': 750, 'learning_rate': 0.03, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.6195889803223953, 'colsample_bytree': 0.6239192893845072}. Best is trial 13 with value: 0.6655818712479834.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:25:53,886] Trial 21 finished with value: 0.6581336604285094 and parameters: {'n_estimators': 1000, 'learning_rate': 0.03, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.6010325556856975, 'colsample_bytree': 0.6105944643093438}. Best is trial 13 with value: 0.6655818712479834.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:25:57,871] Trial 22 finished with value: 0.6582752171086798 and parameters: {'n_estimators': 1000, 'learning_rate': 0.03, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.601043273661567, 'colsample_bytree': 0.6173160562504785}. Best is trial 13 with value: 0.6655818712479834.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:26:01,845] Trial 23 finished with value: 0.6453033185523053 and parameters: {'n_estimators': 1000, 'learning_rate': 0.03, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.62997556208487, 'colsample_bytree': 0.6404213739551745}. Best is trial 13 with value: 0.6655818712479834.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:26:07,045] Trial 24 finished with value: 0.643548561838092 and parameters: {'n_estimators': 1000, 'learning_rate': 0.03, 'max_depth': 8, 'min_child_weight': 4, 'subsample': 0.6504078321390477, 'colsample_bytree': 0.6256206620786022}. Best is trial 13 with value: 0.6655818712479834.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:26:10,955] Trial 25 finished with value: 0.6471719969031137 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.6144555519909589, 'colsample_bytree': 0.734243983447891}. Best is trial 13 with value: 0.6655818712479834.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:26:13,984] Trial 26 finished with value: 0.6487162461515603 and parameters: {'n_estimators': 1000, 'learning_rate': 0.03, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.6358521923889987, 'colsample_bytree': 0.6527737849482043}. Best is trial 13 with value: 0.6655818712479834.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:26:18,122] Trial 27 finished with value: 0.6537446394606832 and parameters: {'n_estimators': 1000, 'learning_rate': 0.03, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.6665354654077937, 'colsample_bytree': 0.6170339097517629}. Best is trial 13 with value: 0.6655818712479834.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:26:24,395] Trial 28 finished with value: 0.6570240919918178 and parameters: {'n_estimators': 1000, 'learning_rate': 0.03, 'max_depth': 8, 'min_child_weight': 3, 'subsample': 0.6425556677086102, 'colsample_bytree': 0.6365284491331404}. Best is trial 13 with value: 0.6655818712479834.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:26:28,188] Trial 29 finished with value: 0.6524097618835974 and parameters: {'n_estimators': 750, 'learning_rate': 0.01, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.6118663991507747, 'colsample_bytree': 0.6723080378024096}. Best is trial 13 with value: 0.6655818712479834.
[I 2025-09-08 13:26:28,190] A new study created in memory with name: no-name-7ac6cfb0-f9e4-4468-988f-1bbadc59d9f4

✅ XGB con C2X-Complex_rhow_9x9_depth_in_0_1 - Mejor R2: 0.67
📋 Parámetros: {'n_estimators': 1000, 'learning_rate': 0.03, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.6001013071833111, 'colsample_bytree': 0.602524118946164}

Buscando mejores hiperparámetros para LBM con C2X-Complex_rhow_9x9_depth_in_0_1...
Fold 1
Fold 2

[I 2025-09-08 13:26:28,645] Trial 0 finished with value: 0.5780899018303542 and parameters: {'learning_rate': 0.02, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 7, 'subsample': 0.6264538811839797, 'colsample_bytree': 0.7774868140991811, 'n_estimators': 1250, 'min_split_gain': 0.0}. Best is trial 0 with value: 0.5780899018303542.

Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:26:28,999] Trial 1 finished with value: 0.5450226133114415 and parameters: {'learning_rate': 0.02, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 4, 'subsample': 0.7327043978713452, 'colsample_bytree': 0.7791168535494625, 'n_estimators': 750, 'min_split_gain': 0.0}. Best is trial 0 with value: 0.5780899018303542.
[I 2025-09-08 13:26:29,149] Trial 2 finished with value: 0.6229082989824056 and parameters: {'learning_rate': 0.02, 'num_leaves': 10, 'max_depth': 7, 'min_child_samples': 8, 'subsample': 0.6570562060555647, 'colsample_bytree': 0.709543590742873, 'n_estimators': 750, 'min_split_gain': 0.5}. Best is trial 2 with value: 0.6229082989824056.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 13:26:29,292] Trial 3 finished with value: 0.567122533593682 and parameters: {'learning_rate': 0.04, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 7, 'subsample': 0.7650327758713465, 'colsample_bytree': 0.7122363266803113, 'n_estimators': 1000, 'min_split_gain': 0.1}. Best is trial 2 with value: 0.6229082989824056.
[I 2025-09-08 13:26:29,422] Trial 4 finished with value: 0.6339415183798776 and parameters: {'learning_rate': 0.04, 'num_leaves': 10, 'max_depth': 8, 'min_child_samples': 8, 'subsample': 0.7288572592305556, 'colsample_bytree': 0.7010228875835481, 'n_estimators': 1250, 'min_split_gain': 0.5}. Best is trial 4 with value: 0.6339415183798776.

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 13:26:29,564] Trial 5 finished with value: 0.5313074330068032 and parameters: {'learning_rate': 0.04, 'num_leaves': 10, 'max_depth': 7, 'min_child_samples': 6, 'subsample': 0.7093882297659233, 'colsample_bytree': 0.683506946619669, 'n_estimators': 1250, 'min_split_gain': 0.1}. Best is trial 4 with value: 0.6339415183798776.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:26:29,721] Trial 6 finished with value: 0.5274827087262057 and parameters: {'learning_rate': 0.03, 'num_leaves': 10, 'max_depth': 7, 'min_child_samples': 5, 'subsample': 0.7488014022119085, 'colsample_bytree': 0.7908536770744312, 'n_estimators': 1250, 'min_split_gain': 0.1}. Best is trial 4 with value: 0.6339415183798776.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:26:30,325] Trial 7 finished with value: 0.5195984550534535 and parameters: {'learning_rate': 0.05, 'num_leaves': 20, 'max_depth': 8, 'min_child_samples': 4, 'subsample': 0.7856715787761308, 'colsample_bytree': 0.7096013549870688, 'n_estimators': 1000, 'min_split_gain': 0.0}. Best is trial 4 with value: 0.6339415183798776.
[I 2025-09-08 13:26:30,434] Trial 8 finished with value: 0.572834905213174 and parameters: {'learning_rate': 0.04, 'num_leaves': 30, 'max_depth': 7, 'min_child_samples': 4, 'subsample': 0.7424088714588652, 'colsample_bytree': 0.7766826800570443, 'n_estimators': 1000, 'min_split_gain': 1.0}. Best is trial 4 with value: 0.6339415183798776.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:26:30,556] Trial 9 finished with value: 0.5393538026875684 and parameters: {'learning_rate': 0.04, 'num_leaves': 10, 'max_depth': 6, 'min_child_samples': 6, 'subsample': 0.6460876417466829, 'colsample_bytree': 0.7045619883699583, 'n_estimators': 1250, 'min_split_gain': 1.0}. Best is trial 4 with value: 0.6339415183798776.
[I 2025-09-08 13:26:30,718] Trial 10 finished with value: 0.6172137502581472 and parameters: {'learning_rate': 0.03, 'num_leaves': 30, 'max_depth': 8, 'min_child_samples': 8, 'subsample': 0.686582849801366, 'colsample_bytree': 0.6209521306824024, 'n_estimators': 1250, 'min_split_gain': 0.5}. Best is trial 4 with value: 0.6339415183798776.

Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 13:26:30,881] Trial 11 finished with value: 0.6298098812809959 and parameters: {'learning_rate': 0.02, 'num_leaves': 10, 'max_depth': 8, 'min_child_samples': 8, 'subsample': 0.6640192252526049, 'colsample_bytree': 0.6616351098954478, 'n_estimators': 750, 'min_split_gain': 0.5}. Best is trial 4 with value: 0.6339415183798776.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:26:31,001] Trial 12 finished with value: 0.6224691272179524 and parameters: {'learning_rate': 0.05, 'num_leaves': 10, 'max_depth': 8, 'min_child_samples': 8, 'subsample': 0.6894981158070321, 'colsample_bytree': 0.6519462928152009, 'n_estimators': 750, 'min_split_gain': 0.2}. Best is trial 4 with value: 0.6339415183798776.
[I 2025-09-08 13:26:31,151] Trial 13 finished with value: 0.5892630963702196 and parameters: {'learning_rate': 0.02, 'num_leaves': 10, 'max_depth': 5, 'min_child_samples': 7, 'subsample': 0.665359038762475, 'colsample_bytree': 0.6603764082564327, 'n_estimators': 750, 'min_split_gain': 0.5}. Best is trial 4 with value: 0.6339415183798776.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 13:26:31,286] Trial 14 finished with value: 0.6221424595903001 and parameters: {'learning_rate': 0.04, 'num_leaves': 10, 'max_depth': 8, 'min_child_samples': 8, 'subsample': 0.607613084464671, 'colsample_bytree': 0.748904600447105, 'n_estimators': 750, 'min_split_gain': 0.5}. Best is trial 4 with value: 0.6339415183798776.

Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:26:31,465] Trial 15 finished with value: 0.5940938527773433 and parameters: {'learning_rate': 0.02, 'num_leaves': 10, 'max_depth': 8, 'min_child_samples': 7, 'subsample': 0.7126116690727058, 'colsample_bytree': 0.6043180964236616, 'n_estimators': 1250, 'min_split_gain': 0.5}. Best is trial 4 with value: 0.6339415183798776.
[I 2025-09-08 13:26:31,602] Trial 16 finished with value: 0.6147472148933161 and parameters: {'learning_rate': 0.05, 'num_leaves': 30, 'max_depth': 8, 'min_child_samples': 8, 'subsample': 0.6764888819768821, 'colsample_bytree': 0.738883770926287, 'n_estimators': 750, 'min_split_gain': 0.2}. Best is trial 4 with value: 0.6339415183798776.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 13:26:31,744] Trial 17 finished with value: 0.5500462977645567 and parameters: {'learning_rate': 0.03, 'num_leaves': 10, 'max_depth': 5, 'min_child_samples': 5, 'subsample': 0.7138828624628424, 'colsample_bytree': 0.6644935989944192, 'n_estimators': 1250, 'min_split_gain': 0.5}. Best is trial 4 with value: 0.6339415183798776.
[I 2025-09-08 13:26:31,887] Trial 18 finished with value: 0.5695925280219497 and parameters: {'learning_rate': 0.02, 'num_leaves': 10, 'max_depth': 7, 'min_child_samples': 6, 'subsample': 0.7949809299316721, 'colsample_bytree': 0.6368325399093331, 'n_estimators': 750, 'min_split_gain': 0.5}. Best is trial 4 with value: 0.6339415183798776.

Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:26:32,018] Trial 19 finished with value: 0.580359054489831 and parameters: {'learning_rate': 0.04, 'num_leaves': 30, 'max_depth': 8, 'min_child_samples': 7, 'subsample': 0.6421692557831314, 'colsample_bytree': 0.6865326400924896, 'n_estimators': 1000, 'min_split_gain': 0.5}. Best is trial 4 with value: 0.6339415183798776.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:26:32,144] Trial 20 finished with value: 0.62664506678819 and parameters: {'learning_rate': 0.04, 'num_leaves': 10, 'max_depth': 7, 'min_child_samples': 8, 'subsample': 0.6036238648665007, 'colsample_bytree': 0.6706957244527006, 'n_estimators': 1250, 'min_split_gain': 1.0}. Best is trial 4 with value: 0.6339415183798776.
[I 2025-09-08 13:26:32,283] Trial 21 finished with value: 0.62664506678819 and parameters: {'learning_rate': 0.04, 'num_leaves': 10, 'max_depth': 7, 'min_child_samples': 8, 'subsample': 0.6041915058531839, 'colsample_bytree': 0.6844951294231344, 'n_estimators': 1250, 'min_split_gain': 1.0}. Best is trial 4 with value: 0.6339415183798776.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 13:26:32,413] Trial 22 finished with value: 0.6279961575179928 and parameters: {'learning_rate': 0.04, 'num_leaves': 10, 'max_depth': 8, 'min_child_samples': 8, 'subsample': 0.6266898885182102, 'colsample_bytree': 0.635478999439104, 'n_estimators': 1250, 'min_split_gain': 1.0}. Best is trial 4 with value: 0.6339415183798776.
[I 2025-09-08 13:26:32,539] Trial 23 finished with value: 0.5855692821407241 and parameters: {'learning_rate': 0.04, 'num_leaves': 10, 'max_depth': 8, 'min_child_samples': 7, 'subsample': 0.6285815995578974, 'colsample_bytree': 0.6402155843918444, 'n_estimators': 1250, 'min_split_gain': 1.0}. Best is trial 4 with value: 0.6339415183798776.

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 13:26:32,698] Trial 24 finished with value: 0.6338678524270321 and parameters: {'learning_rate': 0.04, 'num_leaves': 10, 'max_depth': 8, 'min_child_samples': 8, 'subsample': 0.6283209845256045, 'colsample_bytree': 0.6233548469371823, 'n_estimators': 1250, 'min_split_gain': 0.2}. Best is trial 4 with value: 0.6339415183798776.

Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 13:26:32,899] Trial 25 finished with value: 0.5938741598292804 and parameters: {'learning_rate': 0.02, 'num_leaves': 10, 'max_depth': 8, 'min_child_samples': 7, 'subsample': 0.6714864936212401, 'colsample_bytree': 0.6013159945614633, 'n_estimators': 750, 'min_split_gain': 0.2}. Best is trial 4 with value: 0.6339415183798776.

Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:26:33,080] Trial 26 finished with value: 0.6245053079503036 and parameters: {'learning_rate': 0.03, 'num_leaves': 10, 'max_depth': 8, 'min_child_samples': 8, 'subsample': 0.7300892755081694, 'colsample_bytree': 0.7277746285191347, 'n_estimators': 1250, 'min_split_gain': 0.2}. Best is trial 4 with value: 0.6339415183798776.
[I 2025-09-08 13:26:33,219] Trial 27 finished with value: 0.5246881287012045 and parameters: {'learning_rate': 0.05, 'num_leaves': 10, 'max_depth': 7, 'min_child_samples': 5, 'subsample': 0.645928972754899, 'colsample_bytree': 0.6195702836118475, 'n_estimators': 1250, 'min_split_gain': 0.2}. Best is trial 4 with value: 0.6339415183798776.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 13:26:33,372] Trial 28 finished with value: 0.5696308865184329 and parameters: {'learning_rate': 0.04, 'num_leaves': 20, 'max_depth': 8, 'min_child_samples': 7, 'subsample': 0.7013728348402625, 'colsample_bytree': 0.649313586494805, 'n_estimators': 1000, 'min_split_gain': 0.2}. Best is trial 4 with value: 0.6339415183798776.

Fold 3
Fold 1
Fold 2

[I 2025-09-08 13:26:33,702] Trial 29 finished with value: 0.5891459894125423 and parameters: {'learning_rate': 0.02, 'num_leaves': 30, 'max_depth': 8, 'min_child_samples': 7, 'subsample': 0.618108753754791, 'colsample_bytree': 0.6195602321157077, 'n_estimators': 750, 'min_split_gain': 0.0}. Best is trial 4 with value: 0.6339415183798776.
[I 2025-09-08 13:26:33,704] A new study created in memory with name: no-name-209b1d57-91d9-4173-abdc-7111caeb093c

Fold 3

✅ LBM con C2X-Complex_rhow_9x9_depth_in_0_1 - Mejor R2: 0.63
📋 Parámetros: {'learning_rate': 0.04, 'num_leaves': 10, 'max_depth': 8, 'min_child_samples': 8, 'subsample': 0.7288572592305556, 'colsample_bytree': 0.7010228875835481, 'n_estimators': 1250, 'min_split_gain': 0.5}

Buscando mejores hiperparámetros para MLP con C2X-Complex_rhow_9x9_depth_in_0_1...
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 13:26:34,436] Trial 0 finished with value: 0.506469236835796 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.0004004263523545614, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0006140582178551252}. Best is trial 0 with value: 0.506469236835796.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 13:26:36,275] Trial 1 finished with value: 0.3545492834366115 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'adam', 'alpha': 5.374218233832777e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.00028838787450400635}. Best is trial 0 with value: 0.506469236835796.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 13:26:36,907] Trial 2 finished with value: 0.5561643169716358 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'relu', 'solver': 'adam', 'alpha': 0.00020056076160730813, 'learning_rate': 'constant', 'learning_rate_init': 0.0007288311878618631}. Best is trial 2 with value: 0.5561643169716358.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 3
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 13:26:37,457] Trial 3 finished with value: 0.44332874571829817 and parameters: {'hidden_layer_sizes': (64,), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.003063459912123847, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0018906862758415212}. Best is trial 2 with value: 0.5561643169716358.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 13:26:38,328] Trial 4 finished with value: 0.3600038200502724 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.04273146229764933, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0003064064020593945}. Best is trial 2 with value: 0.5561643169716358.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 13:26:39,020] Trial 5 finished with value: 0.5087049589081819 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'relu', 'solver': 'adam', 'alpha': 0.04362406366152356, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00019943886351869136}. Best is trial 2 with value: 0.5561643169716358.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 13:26:39,467] Trial 6 finished with value: 0.555041000482539 and parameters: {'hidden_layer_sizes': (32,), 'activation': 'tanh', 'solver': 'sgd', 'alpha': 2.01382198647347e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.005019882869409529}. Best is trial 2 with value: 0.5561643169716358.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 3
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 13:26:40,188] Trial 7 finished with value: 0.5119299833995657 and parameters: {'hidden_layer_sizes': (128,), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.00010055310511395927, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0005515095079389006}. Best is trial 2 with value: 0.5561643169716358.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 13:26:40,966] Trial 8 finished with value: 0.5463468184326764 and parameters: {'hidden_layer_sizes': (128,), 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.00018524386607366924, 'learning_rate': 'constant', 'learning_rate_init': 0.0010297238456811904}. Best is trial 2 with value: 0.5561643169716358.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 13:26:41,524] Trial 9 finished with value: 0.46474663857488446 and parameters: {'hidden_layer_sizes': (32,), 'activation': 'tanh', 'solver': 'adam', 'alpha': 3.565032265814208e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0005510819501999181}. Best is trial 2 with value: 0.5561643169716358.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 13:26:41,964] Trial 10 finished with value: 0.345544388652334 and parameters: {'hidden_layer_sizes': (64,), 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.002512516374851615, 'learning_rate': 'constant', 'learning_rate_init': 0.00010222502171627307}. Best is trial 2 with value: 0.5561643169716358.

Fold 3
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 13:26:42,217] Trial 11 finished with value: 0.4605497425450043 and parameters: {'hidden_layer_sizes': (32,), 'activation': 'relu', 'solver': 'sgd', 'alpha': 1.1856039888587587e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.00899004056546609}. Best is trial 2 with value: 0.5561643169716358.

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 13:26:42,479] Trial 12 finished with value: 0.46260586461349096 and parameters: {'hidden_layer_sizes': (32,), 'activation': 'relu', 'solver': 'sgd', 'alpha': 1.108259312553515e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.003919887602920531}. Best is trial 2 with value: 0.5561643169716358.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:26:42,778] Trial 13 finished with value: 0.48715499648092964 and parameters: {'hidden_layer_sizes': (32,), 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.0005121826679460864, 'learning_rate': 'constant', 'learning_rate_init': 0.002142083316449048}. Best is trial 2 with value: 0.5561643169716358.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

[I 2025-09-08 13:26:43,338] Trial 14 finished with value: 0.5182520027590333 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.001860762858412532, 'learning_rate': 'constant', 'learning_rate_init': 0.006954785874928618}. Best is trial 2 with value: 0.5561643169716358.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 13:26:43,646] Trial 15 finished with value: 0.47194761950140246 and parameters: {'hidden_layer_sizes': (32,), 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.0087677096750371, 'learning_rate': 'constant', 'learning_rate_init': 0.0016261336938162396}. Best is trial 2 with value: 0.5561643169716358.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 3
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 13:26:44,442] Trial 16 finished with value: 0.5711947408512217 and parameters: {'hidden_layer_sizes': (128,), 'activation': 'tanh', 'solver': 'sgd', 'alpha': 3.6418657548485065e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.003995488929601639}. Best is trial 16 with value: 0.5711947408512217.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2

[I 2025-09-08 13:26:44,887] Trial 17 finished with value: 0.5612547970781667 and parameters: {'hidden_layer_sizes': (128,), 'activation': 'relu', 'solver': 'adam', 'alpha': 0.00015495441796945146, 'learning_rate': 'constant', 'learning_rate_init': 0.003253398605128535}. Best is trial 16 with value: 0.5711947408512217.

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 13:26:45,656] Trial 18 finished with value: 0.5686181613961331 and parameters: {'hidden_layer_sizes': (128,), 'activation': 'tanh', 'solver': 'sgd', 'alpha': 7.233157247126315e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.003322442109016689}. Best is trial 16 with value: 0.5711947408512217.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 13:26:46,424] Trial 19 finished with value: 0.5675217372784319 and parameters: {'hidden_layer_sizes': (128,), 'activation': 'tanh', 'solver': 'sgd', 'alpha': 5.718071322371172e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.0030800204252953624}. Best is trial 16 with value: 0.5711947408512217.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 13:26:47,329] Trial 20 finished with value: 0.6137890398567326 and parameters: {'hidden_layer_sizes': (128,), 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.000940531570749994, 'learning_rate': 'constant', 'learning_rate_init': 0.005851832652109401}. Best is trial 20 with value: 0.6137890398567326.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 13:26:48,244] Trial 21 finished with value: 0.6133118388837494 and parameters: {'hidden_layer_sizes': (128,), 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.008873362601358105, 'learning_rate': 'constant', 'learning_rate_init': 0.006071445630124063}. Best is trial 20 with value: 0.6137890398567326.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 13:26:49,168] Trial 22 finished with value: 0.6133242223239754 and parameters: {'hidden_layer_sizes': (128,), 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.01378988779475145, 'learning_rate': 'constant', 'learning_rate_init': 0.006062301476863412}. Best is trial 20 with value: 0.6137890398567326.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 13:26:50,097] Trial 23 finished with value: 0.612960507742541 and parameters: {'hidden_layer_sizes': (128,), 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.012895036476874145, 'learning_rate': 'constant', 'learning_rate_init': 0.006215702592519391}. Best is trial 20 with value: 0.6137890398567326.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 13:26:51,135] Trial 24 finished with value: 0.6069912071440705 and parameters: {'hidden_layer_sizes': (128,), 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.009703371041547943, 'learning_rate': 'constant', 'learning_rate_init': 0.008729591746498361}. Best is trial 20 with value: 0.6137890398567326.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 13:26:52,325] Trial 25 finished with value: 0.6146335142325978 and parameters: {'hidden_layer_sizes': (128,), 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.09004038407315856, 'learning_rate': 'constant', 'learning_rate_init': 0.005278118700349368}. Best is trial 25 with value: 0.6146335142325978.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 13:26:53,057] Trial 26 finished with value: 0.5429436314893678 and parameters: {'hidden_layer_sizes': (128,), 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.07040222301554937, 'learning_rate': 'constant', 'learning_rate_init': 0.001266413696818977}. Best is trial 25 with value: 0.6146335142325978.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 13:26:53,768] Trial 27 finished with value: 0.6046317477742239 and parameters: {'hidden_layer_sizes': (128,), 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.022998431067844518, 'learning_rate': 'constant', 'learning_rate_init': 0.009893601555654871}. Best is trial 25 with value: 0.6146335142325978.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 13:26:54,286] Trial 28 finished with value: 0.40386435858482167 and parameters: {'hidden_layer_sizes': (64,), 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.0009662384407472198, 'learning_rate': 'constant', 'learning_rate_init': 0.0025758848898095434}. Best is trial 25 with value: 0.6146335142325978.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 13:26:55,516] Trial 29 finished with value: 0.6146388773911298 and parameters: {'hidden_layer_sizes': (128,), 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.06954238794081256, 'learning_rate': 'adaptive', 'learning_rate_init': 0.005206399765786056}. Best is trial 29 with value: 0.6146388773911298.
[I 2025-09-08 13:26:55,518] A new study created in memory with name: no-name-c70338e1-d453-4547-bf4d-ef76191aa98d
[I 2025-09-08 13:26:55,602] Trial 0 finished with value: 0.5970585989631556 and parameters: {'C': 4.331927542356141, 'epsilon': 0.08403080199940828}. Best is trial 0 with value: 0.5970585989631556.
[I 2025-09-08 13:26:55,655] Trial 1 finished with value: 0.35723827329584257 and parameters: {'C': 1.2640820758196405, 'epsilon': 0.047108593735335734}. Best is trial 0 with value: 0.5970585989631556.
[I 2025-09-08 13:26:55,705] Trial 2 finished with value: 0.3299714721154781 and parameters: {'C': 1.0794860656433145, 'epsilon': 0.06471168111943819}. Best is trial 0 with value: 0.5970585989631556.

✅ MLP con C2X-Complex_rhow_9x9_depth_in_0_1 - Mejor R2: 0.61
📋 Parámetros: {'hidden_layer_sizes': (128,), 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.06954238794081256, 'learning_rate': 'adaptive', 'learning_rate_init': 0.005206399765786056}

Buscando mejores hiperparámetros para SVR con C2X-Complex_rhow_9x9_depth_in_0_1...
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 13:26:55,754] Trial 3 finished with value: 0.25447479038735776 and parameters: {'C': 0.654706873444473, 'epsilon': 0.13225021827310254}. Best is trial 0 with value: 0.5970585989631556.
[I 2025-09-08 13:26:55,805] Trial 4 finished with value: 0.1985489481605005 and parameters: {'C': 0.4568193259805227, 'epsilon': 0.03316571645850287}. Best is trial 0 with value: 0.5970585989631556.
[I 2025-09-08 13:26:55,856] Trial 5 finished with value: 0.13264278689750594 and parameters: {'C': 0.25056477804648075, 'epsilon': 0.05374655829228535}. Best is trial 0 with value: 0.5970585989631556.
[I 2025-09-08 13:26:55,905] Trial 6 finished with value: 0.25771267007019977 and parameters: {'C': 0.7088344173255926, 'epsilon': 0.01443876649979925}. Best is trial 0 with value: 0.5970585989631556.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 13:26:55,956] Trial 7 finished with value: 0.08040584730930563 and parameters: {'C': 0.1335179239279906, 'epsilon': 0.13674195603901926}. Best is trial 0 with value: 0.5970585989631556.
[I 2025-09-08 13:26:56,005] Trial 8 finished with value: 0.6525429156930751 and parameters: {'C': 7.342339285712259, 'epsilon': 0.19208315854143954}. Best is trial 8 with value: 0.6525429156930751.
[I 2025-09-08 13:26:56,056] Trial 9 finished with value: 0.6366548267551065 and parameters: {'C': 6.275294052356989, 'epsilon': 0.15392051164675402}. Best is trial 8 with value: 0.6525429156930751.
[I 2025-09-08 13:26:56,109] Trial 10 finished with value: 0.503326407440393 and parameters: {'C': 2.6021932419510025, 'epsilon': 0.18295793216376474}. Best is trial 8 with value: 0.6525429156930751.

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 13:26:56,168] Trial 11 finished with value: 0.6749253795476574 and parameters: {'C': 9.605158702958787, 'epsilon': 0.19975577035836573}. Best is trial 11 with value: 0.6749253795476574.
[I 2025-09-08 13:26:56,228] Trial 12 finished with value: 0.676028878521088 and parameters: {'C': 9.76165705897909, 'epsilon': 0.19941521956153346}. Best is trial 12 with value: 0.676028878521088.
[I 2025-09-08 13:26:56,287] Trial 13 finished with value: 0.6748035441520465 and parameters: {'C': 9.77505644519266, 'epsilon': 0.16721306831656585}. Best is trial 12 with value: 0.676028878521088.
[I 2025-09-08 13:26:56,343] Trial 14 finished with value: 0.4894761882712471 and parameters: {'C': 2.443924796520024, 'epsilon': 0.19537169740867028}. Best is trial 12 with value: 0.676028878521088.

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 13:26:56,401] Trial 15 finished with value: 0.5198868033887217 and parameters: {'C': 2.8854975675093226, 'epsilon': 0.10892445413087928}. Best is trial 12 with value: 0.676028878521088.
[I 2025-09-08 13:26:56,459] Trial 16 finished with value: 0.6055256284421877 and parameters: {'C': 4.441486362216952, 'epsilon': 0.16753684920773826}. Best is trial 12 with value: 0.676028878521088.
[I 2025-09-08 13:26:56,514] Trial 17 finished with value: 0.439492251530823 and parameters: {'C': 1.9779836612327628, 'epsilon': 0.1115588513607653}. Best is trial 12 with value: 0.676028878521088.
[I 2025-09-08 13:26:56,571] Trial 18 finished with value: 0.6730954736412366 and parameters: {'C': 9.677092814499094, 'epsilon': 0.14281173768617547}. Best is trial 12 with value: 0.676028878521088.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:26:56,626] Trial 19 finished with value: 0.6122815431921594 and parameters: {'C': 4.864672944542034, 'epsilon': 0.17546147137285606}. Best is trial 12 with value: 0.676028878521088.
[I 2025-09-08 13:26:56,680] Trial 20 finished with value: 0.42479722962229083 and parameters: {'C': 1.8404799403279248, 'epsilon': 0.19900394943341873}. Best is trial 12 with value: 0.676028878521088.
[I 2025-09-08 13:26:56,737] Trial 21 finished with value: 0.6755489203056347 and parameters: {'C': 9.922544172038915, 'epsilon': 0.16392403855134163}. Best is trial 12 with value: 0.676028878521088.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:26:56,793] Trial 22 finished with value: 0.6418455584152083 and parameters: {'C': 6.539499717293973, 'epsilon': 0.15616026382787754}. Best is trial 12 with value: 0.676028878521088.
[I 2025-09-08 13:26:56,849] Trial 23 finished with value: 0.6762080718160816 and parameters: {'C': 9.86126615602416, 'epsilon': 0.18375599037748358}. Best is trial 23 with value: 0.6762080718160816.
[I 2025-09-08 13:26:56,901] Trial 24 finished with value: 0.5560008653565505 and parameters: {'C': 3.4003298123647263, 'epsilon': 0.1793254094380281}. Best is trial 23 with value: 0.6762080718160816.
[I 2025-09-08 13:26:56,956] Trial 25 finished with value: 0.627965733379789 and parameters: {'C': 5.848962867291627, 'epsilon': 0.1558241100274344}. Best is trial 23 with value: 0.6762080718160816.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:26:57,010] Trial 26 finished with value: 0.5662533304630596 and parameters: {'C': 3.638275638533322, 'epsilon': 0.1227707638199158}. Best is trial 23 with value: 0.6762080718160816.
[I 2025-09-08 13:26:57,069] Trial 27 finished with value: 0.649719459606653 and parameters: {'C': 7.544642105610206, 'epsilon': 0.08209185095245118}. Best is trial 23 with value: 0.6762080718160816.
[I 2025-09-08 13:26:57,120] Trial 28 finished with value: 0.38216416678500015 and parameters: {'C': 1.4842175482254887, 'epsilon': 0.1846037069906015}. Best is trial 23 with value: 0.6762080718160816.
[I 2025-09-08 13:26:57,175] Trial 29 finished with value: 0.6063142074590183 and parameters: {'C': 4.663117109010248, 'epsilon': 0.09197368979704472}. Best is trial 23 with value: 0.6762080718160816.
[I 2025-09-08 13:26:57,176] A new study created in memory with name: no-name-3d85e0b5-2532-42c7-bcde-6d1e5b01ded7
[I 2025-09-08 13:26:57,216] Trial 0 finished with value: 0.5945109645187574 and parameters: {'n_neighbors': 12, 'leaf_size': 22}. Best is trial 0 with value: 0.5945109645187574.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

✅ SVR con C2X-Complex_rhow_9x9_depth_in_0_1 - Mejor R2: 0.68
📋 Parámetros: {'C': 9.86126615602416, 'epsilon': 0.18375599037748358}

Buscando mejores hiperparámetros para KNN con C2X-Complex_rhow_9x9_depth_in_0_1...
Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 13:26:57,257] Trial 1 finished with value: 0.5893133792479817 and parameters: {'n_neighbors': 9, 'leaf_size': 39}. Best is trial 0 with value: 0.5945109645187574.
[I 2025-09-08 13:26:57,299] Trial 2 finished with value: 0.5945109645187574 and parameters: {'n_neighbors': 12, 'leaf_size': 29}. Best is trial 0 with value: 0.5945109645187574.
[I 2025-09-08 13:26:57,339] Trial 3 finished with value: 0.5926456713405899 and parameters: {'n_neighbors': 6, 'leaf_size': 22}. Best is trial 0 with value: 0.5945109645187574.
[I 2025-09-08 13:26:57,381] Trial 4 finished with value: 0.5014581030724793 and parameters: {'n_neighbors': 3, 'leaf_size': 24}. Best is trial 0 with value: 0.5945109645187574.
[I 2025-09-08 13:26:57,421] Trial 5 finished with value: 0.5839785073442166 and parameters: {'n_neighbors': 10, 'leaf_size': 15}. Best is trial 0 with value: 0.5945109645187574.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 13:26:57,464] Trial 6 finished with value: 0.5900820114223775 and parameters: {'n_neighbors': 7, 'leaf_size': 13}. Best is trial 0 with value: 0.5945109645187574.
[I 2025-09-08 13:26:57,504] Trial 7 finished with value: 0.5863144248763094 and parameters: {'n_neighbors': 8, 'leaf_size': 15}. Best is trial 0 with value: 0.5945109645187574.
[I 2025-09-08 13:26:57,546] Trial 8 finished with value: 0.5839785073442166 and parameters: {'n_neighbors': 10, 'leaf_size': 34}. Best is trial 0 with value: 0.5945109645187574.
[I 2025-09-08 13:26:57,589] Trial 9 finished with value: 0.5429292949154164 and parameters: {'n_neighbors': 4, 'leaf_size': 27}. Best is trial 0 with value: 0.5945109645187574.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:26:57,644] Trial 10 finished with value: 0.5945109645187574 and parameters: {'n_neighbors': 12, 'leaf_size': 20}. Best is trial 0 with value: 0.5945109645187574.
[I 2025-09-08 13:26:57,728] Trial 11 finished with value: 0.5945109645187574 and parameters: {'n_neighbors': 12, 'leaf_size': 30}. Best is trial 0 with value: 0.5945109645187574.
[I 2025-09-08 13:26:57,787] Trial 12 finished with value: 0.5945109645187574 and parameters: {'n_neighbors': 12, 'leaf_size': 31}. Best is trial 0 with value: 0.5945109645187574.
[I 2025-09-08 13:26:57,835] Trial 13 finished with value: 0.5839785073442166 and parameters: {'n_neighbors': 10, 'leaf_size': 20}. Best is trial 0 with value: 0.5945109645187574.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 13:26:57,890] Trial 14 finished with value: 0.596572840931929 and parameters: {'n_neighbors': 11, 'leaf_size': 38}. Best is trial 14 with value: 0.596572840931929.
[I 2025-09-08 13:26:57,978] Trial 15 finished with value: 0.596572840931929 and parameters: {'n_neighbors': 11, 'leaf_size': 37}. Best is trial 14 with value: 0.596572840931929.
[I 2025-09-08 13:26:58,025] Trial 16 finished with value: 0.5893133792479817 and parameters: {'n_neighbors': 9, 'leaf_size': 40}. Best is trial 14 with value: 0.596572840931929.

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:26:58,074] Trial 17 finished with value: 0.5926456713405899 and parameters: {'n_neighbors': 6, 'leaf_size': 36}. Best is trial 14 with value: 0.596572840931929.
[I 2025-09-08 13:26:58,124] Trial 18 finished with value: 0.596572840931929 and parameters: {'n_neighbors': 11, 'leaf_size': 35}. Best is trial 14 with value: 0.596572840931929.
[I 2025-09-08 13:26:58,175] Trial 19 finished with value: 0.5863144248763094 and parameters: {'n_neighbors': 8, 'leaf_size': 37}. Best is trial 14 with value: 0.596572840931929.
[I 2025-09-08 13:26:58,225] Trial 20 finished with value: 0.596572840931929 and parameters: {'n_neighbors': 11, 'leaf_size': 33}. Best is trial 14 with value: 0.596572840931929.
[I 2025-09-08 13:26:58,274] Trial 21 finished with value: 0.596572840931929 and parameters: {'n_neighbors': 11, 'leaf_size': 36}. Best is trial 14 with value: 0.596572840931929.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 13:26:58,323] Trial 22 finished with value: 0.596572840931929 and parameters: {'n_neighbors': 11, 'leaf_size': 40}. Best is trial 14 with value: 0.596572840931929.
[I 2025-09-08 13:26:58,373] Trial 23 finished with value: 0.5893133792479817 and parameters: {'n_neighbors': 9, 'leaf_size': 33}. Best is trial 14 with value: 0.596572840931929.
[I 2025-09-08 13:26:58,424] Trial 24 finished with value: 0.5839785073442166 and parameters: {'n_neighbors': 10, 'leaf_size': 37}. Best is trial 14 with value: 0.596572840931929.
[I 2025-09-08 13:26:58,473] Trial 25 finished with value: 0.596572840931929 and parameters: {'n_neighbors': 11, 'leaf_size': 34}. Best is trial 14 with value: 0.596572840931929.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 13:26:58,527] Trial 26 finished with value: 0.596572840931929 and parameters: {'n_neighbors': 11, 'leaf_size': 38}. Best is trial 14 with value: 0.596572840931929.
[I 2025-09-08 13:26:58,580] Trial 27 finished with value: 0.5893133792479817 and parameters: {'n_neighbors': 9, 'leaf_size': 27}. Best is trial 14 with value: 0.596572840931929.
[I 2025-09-08 13:26:58,631] Trial 28 finished with value: 0.5839785073442166 and parameters: {'n_neighbors': 10, 'leaf_size': 32}. Best is trial 14 with value: 0.596572840931929.
[I 2025-09-08 13:26:58,682] Trial 29 finished with value: 0.5900820114223775 and parameters: {'n_neighbors': 7, 'leaf_size': 28}. Best is trial 14 with value: 0.596572840931929.
[I 2025-09-08 13:26:58,683] A new study created in memory with name: no-name-47041141-01c7-4bdb-bd0d-ac66bef2b30a

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

✅ KNN con C2X-Complex_rhow_9x9_depth_in_0_1 - Mejor R2: 0.60
📋 Parámetros: {'n_neighbors': 11, 'leaf_size': 38}

Buscando mejores hiperparámetros para LR con C2X-Complex_rhow_9x9_depth_in_0_1...
Fold 1
Fold 2

[I 2025-09-08 13:26:58,738] Trial 0 finished with value: 0.20132728950144888 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 0 with value: 0.20132728950144888.
[I 2025-09-08 13:26:58,803] Trial 1 finished with value: 0.20132728950144888 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 0 with value: 0.20132728950144888.
[I 2025-09-08 13:26:58,856] Trial 2 finished with value: 0.20132728950144888 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 0 with value: 0.20132728950144888.
[I 2025-09-08 13:26:58,909] Trial 3 finished with value: 0.3314023566411913 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 3 with value: 0.3314023566411913.

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 13:26:58,968] Trial 4 finished with value: 0.20132728950144888 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 3 with value: 0.3314023566411913.
[I 2025-09-08 13:26:59,037] Trial 5 finished with value: 0.33140235664119083 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 3 with value: 0.3314023566411913.
[I 2025-09-08 13:26:59,079] Trial 6 finished with value: 0.33140235664119083 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 3 with value: 0.3314023566411913.
[I 2025-09-08 13:26:59,118] Trial 7 finished with value: 0.3314023566411913 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 3 with value: 0.3314023566411913.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 13:26:59,168] Trial 8 finished with value: 0.20132728950144888 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 3 with value: 0.3314023566411913.
[I 2025-09-08 13:26:59,224] Trial 9 finished with value: 0.33140235664119083 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 3 with value: 0.3314023566411913.
[I 2025-09-08 13:26:59,266] Trial 10 finished with value: 0.3314023566411913 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 3 with value: 0.3314023566411913.
[I 2025-09-08 13:26:59,308] Trial 11 finished with value: 0.3314023566411913 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 3 with value: 0.3314023566411913.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:26:59,352] Trial 12 finished with value: 0.3314023566411913 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 3 with value: 0.3314023566411913.
[I 2025-09-08 13:26:59,400] Trial 13 finished with value: 0.3314023566411913 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 3 with value: 0.3314023566411913.
[I 2025-09-08 13:26:59,444] Trial 14 finished with value: 0.3314023566411913 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 3 with value: 0.3314023566411913.
[I 2025-09-08 13:26:59,489] Trial 15 finished with value: 0.3314023566411913 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 3 with value: 0.3314023566411913.
[I 2025-09-08 13:26:59,534] Trial 16 finished with value: 0.3314023566411913 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 3 with value: 0.3314023566411913.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 13:26:59,582] Trial 17 finished with value: 0.3314023566411913 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 3 with value: 0.3314023566411913.
[I 2025-09-08 13:26:59,644] Trial 18 finished with value: 0.3314023566411913 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 3 with value: 0.3314023566411913.
[I 2025-09-08 13:26:59,705] Trial 19 finished with value: 0.3314023566411913 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 3 with value: 0.3314023566411913.
[I 2025-09-08 13:26:59,746] Trial 20 finished with value: 0.3314023566411913 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 3 with value: 0.3314023566411913.

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 13:26:59,788] Trial 21 finished with value: 0.3314023566411913 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 3 with value: 0.3314023566411913.
[I 2025-09-08 13:26:59,830] Trial 22 finished with value: 0.3314023566411913 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 3 with value: 0.3314023566411913.
[I 2025-09-08 13:26:59,873] Trial 23 finished with value: 0.3314023566411913 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 3 with value: 0.3314023566411913.
[I 2025-09-08 13:26:59,915] Trial 24 finished with value: 0.3314023566411913 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 3 with value: 0.3314023566411913.
[I 2025-09-08 13:26:59,957] Trial 25 finished with value: 0.3314023566411913 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 3 with value: 0.3314023566411913.

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 13:27:00,013] Trial 26 finished with value: 0.20132728949688974 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 3 with value: 0.3314023566411913.
[I 2025-09-08 13:27:00,067] Trial 27 finished with value: 0.3314023566411913 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 3 with value: 0.3314023566411913.
[I 2025-09-08 13:27:00,111] Trial 28 finished with value: 0.3314023566411913 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 3 with value: 0.3314023566411913.
[I 2025-09-08 13:27:00,163] Trial 29 finished with value: 0.20132728949688974 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 3 with value: 0.3314023566411913.
[I 2025-09-08 13:27:00,165] A new study created in memory with name: no-name-c887858c-430d-4cab-834b-3dd45e89b772

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

✅ LR con C2X-Complex_rhow_9x9_depth_in_0_1 - Mejor R2: 0.33
📋 Parámetros: {'fit_intercept': False, 'positive': True}

Buscando mejores hiperparámetros para RF con C2X-Complex_rhow_9x9_depth_in_0_1...
Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:27:02,095] Trial 0 finished with value: 0.528111138519071 and parameters: {'n_estimators': 200, 'max_depth': 7, 'min_samples_split': 3, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 0 with value: 0.528111138519071.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:27:04,309] Trial 1 finished with value: 0.5756752900045515 and parameters: {'n_estimators': 200, 'max_depth': 7, 'min_samples_split': 5, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 1 with value: 0.5756752900045515.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:27:05,600] Trial 2 finished with value: 0.3322919280522874 and parameters: {'n_estimators': 100, 'max_depth': 5, 'min_samples_split': 4, 'min_samples_leaf': 6, 'bootstrap': False}. Best is trial 1 with value: 0.5756752900045515.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:27:12,856] Trial 3 finished with value: 0.3538422186058943 and parameters: {'n_estimators': 400, 'max_depth': 12, 'min_samples_split': 2, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 1 with value: 0.5756752900045515.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:27:18,734] Trial 4 finished with value: 0.30977105897536034 and parameters: {'n_estimators': 400, 'max_depth': 12, 'min_samples_split': 3, 'min_samples_leaf': 7, 'bootstrap': False}. Best is trial 1 with value: 0.5756752900045515.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:27:20,830] Trial 5 finished with value: 0.5621873979020758 and parameters: {'n_estimators': 200, 'max_depth': 9, 'min_samples_split': 7, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 1 with value: 0.5756752900045515.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:27:24,230] Trial 6 finished with value: 0.5558596971447906 and parameters: {'n_estimators': 400, 'max_depth': 5, 'min_samples_split': 7, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 1 with value: 0.5756752900045515.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:27:25,383] Trial 7 finished with value: 0.5935510887082862 and parameters: {'n_estimators': 100, 'max_depth': 9, 'min_samples_split': 4, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 7 with value: 0.5935510887082862.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:27:26,293] Trial 8 finished with value: 0.4998783993640095 and parameters: {'n_estimators': 100, 'max_depth': 7, 'min_samples_split': 4, 'min_samples_leaf': 6, 'bootstrap': True}. Best is trial 7 with value: 0.5935510887082862.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:27:32,757] Trial 9 finished with value: 0.34657875963635537 and parameters: {'n_estimators': 400, 'max_depth': 10, 'min_samples_split': 7, 'min_samples_leaf': 5, 'bootstrap': False}. Best is trial 7 with value: 0.5935510887082862.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:27:33,984] Trial 10 finished with value: 0.5870135852795132 and parameters: {'n_estimators': 100, 'max_depth': 10, 'min_samples_split': 5, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 7 with value: 0.5935510887082862.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:27:35,191] Trial 11 finished with value: 0.5870135852795132 and parameters: {'n_estimators': 100, 'max_depth': 10, 'min_samples_split': 5, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 7 with value: 0.5935510887082862.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:27:36,379] Trial 12 finished with value: 0.5761388334194287 and parameters: {'n_estimators': 100, 'max_depth': 10, 'min_samples_split': 6, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 7 with value: 0.5935510887082862.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:27:37,598] Trial 13 finished with value: 0.5853997978174236 and parameters: {'n_estimators': 100, 'max_depth': 9, 'min_samples_split': 4, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 7 with value: 0.5935510887082862.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:27:38,746] Trial 14 finished with value: 0.5867998305705323 and parameters: {'n_estimators': 100, 'max_depth': 11, 'min_samples_split': 6, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 7 with value: 0.5935510887082862.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:27:39,655] Trial 15 finished with value: 0.4349976841721605 and parameters: {'n_estimators': 100, 'max_depth': 8, 'min_samples_split': 8, 'min_samples_leaf': 8, 'bootstrap': True}. Best is trial 7 with value: 0.5935510887082862.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:27:40,715] Trial 16 finished with value: 0.57043893274503 and parameters: {'n_estimators': 100, 'max_depth': 8, 'min_samples_split': 2, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 7 with value: 0.5935510887082862.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:27:41,895] Trial 17 finished with value: 0.5867998305705323 and parameters: {'n_estimators': 100, 'max_depth': 11, 'min_samples_split': 3, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 7 with value: 0.5935510887082862.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:27:43,934] Trial 18 finished with value: 0.40076363933938014 and parameters: {'n_estimators': 100, 'max_depth': 11, 'min_samples_split': 5, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 7 with value: 0.5935510887082862.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:27:46,378] Trial 19 finished with value: 0.5621873979020758 and parameters: {'n_estimators': 200, 'max_depth': 9, 'min_samples_split': 6, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 7 with value: 0.5935510887082862.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:27:47,545] Trial 20 finished with value: 0.5879191826046136 and parameters: {'n_estimators': 100, 'max_depth': 6, 'min_samples_split': 4, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 7 with value: 0.5935510887082862.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:27:48,690] Trial 21 finished with value: 0.5879191826046136 and parameters: {'n_estimators': 100, 'max_depth': 6, 'min_samples_split': 4, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 7 with value: 0.5935510887082862.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:27:49,786] Trial 22 finished with value: 0.5879191826046136 and parameters: {'n_estimators': 100, 'max_depth': 6, 'min_samples_split': 4, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 7 with value: 0.5935510887082862.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:27:50,779] Trial 23 finished with value: 0.5716130304196961 and parameters: {'n_estimators': 100, 'max_depth': 6, 'min_samples_split': 3, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 7 with value: 0.5935510887082862.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:27:51,763] Trial 24 finished with value: 0.5879191826046136 and parameters: {'n_estimators': 100, 'max_depth': 6, 'min_samples_split': 4, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 7 with value: 0.5935510887082862.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:27:52,767] Trial 25 finished with value: 0.5384708799715724 and parameters: {'n_estimators': 100, 'max_depth': 8, 'min_samples_split': 3, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 7 with value: 0.5935510887082862.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:27:54,089] Trial 26 finished with value: 0.27725843255019983 and parameters: {'n_estimators': 100, 'max_depth': 5, 'min_samples_split': 5, 'min_samples_leaf': 4, 'bootstrap': False}. Best is trial 7 with value: 0.5935510887082862.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:27:55,207] Trial 27 finished with value: 0.5879191826046136 and parameters: {'n_estimators': 100, 'max_depth': 6, 'min_samples_split': 4, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 7 with value: 0.5935510887082862.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:27:59,474] Trial 28 finished with value: 0.48762903531401464 and parameters: {'n_estimators': 400, 'max_depth': 7, 'min_samples_split': 2, 'min_samples_leaf': 6, 'bootstrap': True}. Best is trial 7 with value: 0.5935510887082862.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:28:01,635] Trial 29 finished with value: 0.5275994122927107 and parameters: {'n_estimators': 200, 'max_depth': 8, 'min_samples_split': 3, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 7 with value: 0.5935510887082862.
[I 2025-09-08 13:28:01,637] A new study created in memory with name: no-name-3004f006-3d41-4344-b5b7-de0dc8609300

✅ RF con C2X-Complex_rhow_9x9_depth_in_0_1 - Mejor R2: 0.59
📋 Parámetros: {'n_estimators': 100, 'max_depth': 9, 'min_samples_split': 4, 'min_samples_leaf': 3, 'bootstrap': True}

Buscando mejores hiperparámetros para CAT con C2X-Complex_rhow_9x9_depth_in_0_1...
Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:28:10,276] Trial 0 finished with value: 0.6622279147887871 and parameters: {'iterations': 750, 'learning_rate': 0.03, 'depth': 7, 'l2_leaf_reg': 2.1248088526085773}. Best is trial 0 with value: 0.6622279147887871.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:28:11,423] Trial 1 finished with value: 0.618365519407622 and parameters: {'iterations': 500, 'learning_rate': 0.05, 'depth': 4, 'l2_leaf_reg': 1.0794356140561518}. Best is trial 0 with value: 0.6622279147887871.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:28:13,500] Trial 2 finished with value: 0.6319928714705699 and parameters: {'iterations': 750, 'learning_rate': 0.03, 'depth': 4, 'l2_leaf_reg': 3.255539508806421}. Best is trial 0 with value: 0.6622279147887871.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:28:25,744] Trial 3 finished with value: 0.6524655601418335 and parameters: {'iterations': 1000, 'learning_rate': 0.03, 'depth': 7, 'l2_leaf_reg': 4.401308101995252}. Best is trial 0 with value: 0.6622279147887871.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:28:28,813] Trial 4 finished with value: 0.6492855146197801 and parameters: {'iterations': 1000, 'learning_rate': 0.02, 'depth': 5, 'l2_leaf_reg': 1.9649484466724587}. Best is trial 0 with value: 0.6622279147887871.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:28:32,341] Trial 5 finished with value: 0.6494318821483266 and parameters: {'iterations': 750, 'learning_rate': 0.04, 'depth': 6, 'l2_leaf_reg': 1.8155590831744264}. Best is trial 0 with value: 0.6622279147887871.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:28:33,363] Trial 6 finished with value: 0.64793858803133 and parameters: {'iterations': 500, 'learning_rate': 0.02, 'depth': 4, 'l2_leaf_reg': 2.898016125718441}. Best is trial 0 with value: 0.6622279147887871.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:29:04,535] Trial 7 finished with value: 0.6601886974848216 and parameters: {'iterations': 1000, 'learning_rate': 0.04, 'depth': 8, 'l2_leaf_reg': 2.3326116941962054}. Best is trial 0 with value: 0.6622279147887871.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:29:19,673] Trial 8 finished with value: 0.6479126437066642 and parameters: {'iterations': 500, 'learning_rate': 0.05, 'depth': 8, 'l2_leaf_reg': 3.740037574817948}. Best is trial 0 with value: 0.6622279147887871.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:29:22,615] Trial 9 finished with value: 0.6345291601313919 and parameters: {'iterations': 1000, 'learning_rate': 0.04, 'depth': 5, 'l2_leaf_reg': 1.9568788127848857}. Best is trial 0 with value: 0.6622279147887871.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:29:31,469] Trial 10 finished with value: 0.6686572972528113 and parameters: {'iterations': 750, 'learning_rate': 0.03, 'depth': 7, 'l2_leaf_reg': 4.586486710178384}. Best is trial 10 with value: 0.6686572972528113.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:29:40,010] Trial 11 finished with value: 0.6609653322359277 and parameters: {'iterations': 750, 'learning_rate': 0.03, 'depth': 7, 'l2_leaf_reg': 4.98056322342231}. Best is trial 10 with value: 0.6686572972528113.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:29:48,714] Trial 12 finished with value: 0.676380191680023 and parameters: {'iterations': 750, 'learning_rate': 0.03, 'depth': 7, 'l2_leaf_reg': 3.9726791284986285}. Best is trial 12 with value: 0.676380191680023.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:29:52,156] Trial 13 finished with value: 0.6334836770023572 and parameters: {'iterations': 750, 'learning_rate': 0.03, 'depth': 6, 'l2_leaf_reg': 4.107476941359198}. Best is trial 12 with value: 0.676380191680023.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:30:01,984] Trial 14 finished with value: 0.6701044780754751 and parameters: {'iterations': 750, 'learning_rate': 0.03, 'depth': 7, 'l2_leaf_reg': 4.7529155641416825}. Best is trial 12 with value: 0.676380191680023.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:30:25,126] Trial 15 finished with value: 0.6549762228915116 and parameters: {'iterations': 750, 'learning_rate': 0.03, 'depth': 8, 'l2_leaf_reg': 3.6654240800437687}. Best is trial 12 with value: 0.676380191680023.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:30:28,840] Trial 16 finished with value: 0.6499876740093615 and parameters: {'iterations': 750, 'learning_rate': 0.03, 'depth': 6, 'l2_leaf_reg': 4.853961506149393}. Best is trial 12 with value: 0.676380191680023.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:30:38,285] Trial 17 finished with value: 0.6747280378443911 and parameters: {'iterations': 750, 'learning_rate': 0.02, 'depth': 7, 'l2_leaf_reg': 4.014639918764459}. Best is trial 12 with value: 0.676380191680023.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:30:40,421] Trial 18 finished with value: 0.6650031720360705 and parameters: {'iterations': 750, 'learning_rate': 0.02, 'depth': 5, 'l2_leaf_reg': 4.018194255823847}. Best is trial 12 with value: 0.676380191680023.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:30:55,374] Trial 19 finished with value: 0.6539552860871675 and parameters: {'iterations': 500, 'learning_rate': 0.02, 'depth': 8, 'l2_leaf_reg': 3.138935373616995}. Best is trial 12 with value: 0.676380191680023.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:30:59,072] Trial 20 finished with value: 0.6561773699396937 and parameters: {'iterations': 750, 'learning_rate': 0.02, 'depth': 6, 'l2_leaf_reg': 3.582116908807074}. Best is trial 12 with value: 0.676380191680023.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:31:08,217] Trial 21 finished with value: 0.6733445228348054 and parameters: {'iterations': 750, 'learning_rate': 0.05, 'depth': 7, 'l2_leaf_reg': 4.3284790321325355}. Best is trial 12 with value: 0.676380191680023.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:31:17,442] Trial 22 finished with value: 0.667664589864495 and parameters: {'iterations': 750, 'learning_rate': 0.05, 'depth': 7, 'l2_leaf_reg': 4.233615216140864}. Best is trial 12 with value: 0.676380191680023.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:31:27,685] Trial 23 finished with value: 0.6667739433463892 and parameters: {'iterations': 750, 'learning_rate': 0.05, 'depth': 7, 'l2_leaf_reg': 3.871451270865699}. Best is trial 12 with value: 0.676380191680023.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:31:52,167] Trial 24 finished with value: 0.6631795181072985 and parameters: {'iterations': 750, 'learning_rate': 0.05, 'depth': 8, 'l2_leaf_reg': 3.4318150217346393}. Best is trial 12 with value: 0.676380191680023.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:32:03,004] Trial 25 finished with value: 0.6715976481310135 and parameters: {'iterations': 750, 'learning_rate': 0.05, 'depth': 7, 'l2_leaf_reg': 4.34034442619689}. Best is trial 12 with value: 0.676380191680023.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:32:07,378] Trial 26 finished with value: 0.6607539609915457 and parameters: {'iterations': 750, 'learning_rate': 0.02, 'depth': 6, 'l2_leaf_reg': 2.8157214504822896}. Best is trial 12 with value: 0.676380191680023.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:32:11,636] Trial 27 finished with value: 0.6500845607592969 and parameters: {'iterations': 750, 'learning_rate': 0.05, 'depth': 6, 'l2_leaf_reg': 4.575755455039211}. Best is trial 12 with value: 0.676380191680023.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:32:18,431] Trial 28 finished with value: 0.6732503691676758 and parameters: {'iterations': 500, 'learning_rate': 0.02, 'depth': 7, 'l2_leaf_reg': 2.635636212462293}. Best is trial 12 with value: 0.676380191680023.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:32:28,729] Trial 29 finished with value: 0.6561007839789154 and parameters: {'iterations': 750, 'learning_rate': 0.04, 'depth': 7, 'l2_leaf_reg': 3.9625627762530877}. Best is trial 12 with value: 0.676380191680023.
[I 2025-09-08 13:32:28,730] A new study created in memory with name: no-name-02186798-5570-40c2-96c1-ed20704e1eb1
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.693e+02, tolerance: 3.241e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.081e+02, tolerance: 2.440e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.065e+02, tolerance: 2.507e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 13:32:28,810] Trial 0 finished with value: 0.4761960412283363 and parameters: {'alpha': 0.004410105127982306, 'l1_ratio': 0.32501560931051676}. Best is trial 0 with value: 0.4761960412283363.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.917e+00, tolerance: 3.241e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.055e-01, tolerance: 2.440e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.594e+01, tolerance: 2.507e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 13:32:28,906] Trial 1 finished with value: 0.4835713159330734 and parameters: {'alpha': 0.015983937746454572, 'l1_ratio': 0.3567471681555142}. Best is trial 1 with value: 0.4835713159330734.

✅ CAT con C2X-Complex_rhow_9x9_depth_in_0_1 - Mejor R2: 0.68
📋 Parámetros: {'iterations': 750, 'learning_rate': 0.03, 'depth': 7, 'l2_leaf_reg': 3.9726791284986285}

Buscando mejores hiperparámetros para ELN con C2X-Complex_rhow_9x9_depth_in_0_1...
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 13:32:28,981] Trial 2 finished with value: 0.4910698411342058 and parameters: {'alpha': 0.04123536257549618, 'l1_ratio': 0.5960250973908362}. Best is trial 2 with value: 0.4910698411342058.
[I 2025-09-08 13:32:29,054] Trial 3 finished with value: 0.484005030257418 and parameters: {'alpha': 0.0656040861488963, 'l1_ratio': 0.7826996119130104}. Best is trial 2 with value: 0.4910698411342058.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.520e+02, tolerance: 3.241e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.094e+02, tolerance: 2.440e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.718e+02, tolerance: 2.507e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 13:32:29,138] Trial 4 finished with value: 0.46246321200550894 and parameters: {'alpha': 0.0008651185528819705, 'l1_ratio': 0.5114056521122546}. Best is trial 2 with value: 0.4910698411342058.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:32:29,202] Trial 5 finished with value: 0.4391443345736093 and parameters: {'alpha': 0.36716582567780176, 'l1_ratio': 0.8038509989363}. Best is trial 2 with value: 0.4910698411342058.
[I 2025-09-08 13:32:29,274] Trial 6 finished with value: 0.4898085643212977 and parameters: {'alpha': 0.04681818284933885, 'l1_ratio': 0.6564518335772414}. Best is trial 2 with value: 0.4910698411342058.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.932e+00, tolerance: 2.507e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 13:32:29,382] Trial 7 finished with value: 0.4821614240949991 and parameters: {'alpha': 0.03087797850006635, 'l1_ratio': 0.2338482190669252}. Best is trial 2 with value: 0.4910698411342058.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.294e+02, tolerance: 3.241e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.412e+02, tolerance: 2.440e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.569e+02, tolerance: 2.507e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 13:32:29,553] Trial 8 finished with value: 0.47503641536966473 and parameters: {'alpha': 0.004691342413418929, 'l1_ratio': 0.10789423860183388}. Best is trial 2 with value: 0.4910698411342058.

Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:32:29,645] Trial 9 finished with value: 0.4692132788046039 and parameters: {'alpha': 0.14408909743962472, 'l1_ratio': 0.8056716505282522}. Best is trial 2 with value: 0.4910698411342058.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.136e+02, tolerance: 3.241e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.302e+02, tolerance: 2.440e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.555e+02, tolerance: 2.507e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 13:32:29,756] Trial 10 finished with value: 0.4560634089173252 and parameters: {'alpha': 0.0005738796977112507, 'l1_ratio': 0.518485784460598}. Best is trial 2 with value: 0.4910698411342058.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:32:29,853] Trial 11 finished with value: 0.4138859898254748 and parameters: {'alpha': 0.6571986564835558, 'l1_ratio': 0.6433603997866736}. Best is trial 2 with value: 0.4910698411342058.
[I 2025-09-08 13:32:29,953] Trial 12 finished with value: 0.4817206295456637 and parameters: {'alpha': 0.0774806453681867, 'l1_ratio': 0.6478476704277598}. Best is trial 2 with value: 0.4910698411342058.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.877e+02, tolerance: 3.241e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.495e+02, tolerance: 2.440e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.171e+02, tolerance: 2.507e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 13:32:30,105] Trial 13 finished with value: 0.4511396634958267 and parameters: {'alpha': 0.00010667826866347043, 'l1_ratio': 0.6436017292906171}. Best is trial 2 with value: 0.4910698411342058.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.223e+01, tolerance: 3.241e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.249e+01, tolerance: 2.440e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.071e+01, tolerance: 2.507e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 13:32:30,234] Trial 14 finished with value: 0.4888010766188529 and parameters: {'alpha': 0.008509934838908455, 'l1_ratio': 0.6884883622623681}. Best is trial 2 with value: 0.4910698411342058.
[I 2025-09-08 13:32:30,334] Trial 15 finished with value: 0.47159342229010964 and parameters: {'alpha': 0.1468385311972508, 'l1_ratio': 0.4340893599937331}. Best is trial 2 with value: 0.4910698411342058.

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 13:32:30,475] Trial 16 finished with value: 0.4893093002475489 and parameters: {'alpha': 0.02480856371370237, 'l1_ratio': 0.5468526367261082}. Best is trial 2 with value: 0.4910698411342058.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.374e+02, tolerance: 3.241e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.909e+02, tolerance: 2.440e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.847e+02, tolerance: 2.507e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 13:32:30,610] Trial 17 finished with value: 0.4681540693830497 and parameters: {'alpha': 0.0015817994611887819, 'l1_ratio': 0.8959625898949359}. Best is trial 2 with value: 0.4910698411342058.

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 13:32:30,702] Trial 18 finished with value: 0.44983171237829644 and parameters: {'alpha': 0.2929620233325528, 'l1_ratio': 0.5803771129402074}. Best is trial 2 with value: 0.4910698411342058.
[I 2025-09-08 13:32:30,797] Trial 19 finished with value: 0.48689043258841486 and parameters: {'alpha': 0.04872615108250837, 'l1_ratio': 0.42553513490382155}. Best is trial 2 with value: 0.4910698411342058.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.643e+00, tolerance: 3.241e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.522e+00, tolerance: 2.440e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.752e+00, tolerance: 2.507e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 13:32:30,907] Trial 20 finished with value: 0.4901968033093234 and parameters: {'alpha': 0.010744446806614629, 'l1_ratio': 0.7342414704486939}. Best is trial 2 with value: 0.4910698411342058.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.981e+00, tolerance: 3.241e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.684e+00, tolerance: 2.440e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.568e+00, tolerance: 2.507e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 13:32:31,031] Trial 21 finished with value: 0.49013992770275966 and parameters: {'alpha': 0.012021819099824485, 'l1_ratio': 0.7277076775295205}. Best is trial 2 with value: 0.4910698411342058.

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.758e+01, tolerance: 3.241e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.272e+01, tolerance: 2.440e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.013e+01, tolerance: 2.507e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 13:32:31,149] Trial 22 finished with value: 0.4901351321077369 and parameters: {'alpha': 0.008278292139463147, 'l1_ratio': 0.7375129653968236}. Best is trial 2 with value: 0.4910698411342058.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.144e+02, tolerance: 3.241e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.200e+01, tolerance: 2.440e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.387e+02, tolerance: 2.507e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 13:32:31,267] Trial 23 finished with value: 0.47125486131072575 and parameters: {'alpha': 0.0024589510317562812, 'l1_ratio': 0.8988408464519033}. Best is trial 2 with value: 0.4910698411342058.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.768e+00, tolerance: 3.241e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.860e-01, tolerance: 2.507e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 13:32:31,375] Trial 24 finished with value: 0.48948092913296404 and parameters: {'alpha': 0.015423155048963494, 'l1_ratio': 0.7218780670560434}. Best is trial 2 with value: 0.4910698411342058.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.359e+02, tolerance: 3.241e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.595e+01, tolerance: 2.440e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.059e+02, tolerance: 2.507e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 13:32:31,483] Trial 25 finished with value: 0.4833952932394295 and parameters: {'alpha': 0.004577738936949875, 'l1_ratio': 0.5764198543987875}. Best is trial 2 with value: 0.4910698411342058.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.486e-01, tolerance: 3.241e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.101e+00, tolerance: 2.507e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 13:32:31,575] Trial 26 finished with value: 0.48739683172049153 and parameters: {'alpha': 0.018102774336097943, 'l1_ratio': 0.8437963996569704}. Best is trial 2 with value: 0.4910698411342058.
[I 2025-09-08 13:32:31,665] Trial 27 finished with value: 0.47369546117559286 and parameters: {'alpha': 0.11776347040944031, 'l1_ratio': 0.7292602343788602}. Best is trial 2 with value: 0.4910698411342058.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.403e+02, tolerance: 3.241e-01
  model = cd_fast.enet_coordinate_descent(

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.357e+02, tolerance: 2.440e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.792e+02, tolerance: 2.507e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 13:32:31,789] Trial 28 finished with value: 0.45381538905402713 and parameters: {'alpha': 0.0004033554887774947, 'l1_ratio': 0.6008698674084717}. Best is trial 2 with value: 0.4910698411342058.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.379e+02, tolerance: 3.241e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.666e+01, tolerance: 2.440e-01
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.516e+01, tolerance: 2.507e-01
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 13:32:31,907] Trial 29 finished with value: 0.47974052011333956 and parameters: {'alpha': 0.008151376452653857, 'l1_ratio': 0.44725992777018286}. Best is trial 2 with value: 0.4910698411342058.
[I 2025-09-08 13:32:31,909] A new study created in memory with name: no-name-49555074-2924-4bf4-9f41-4168d4a02a42

Fold 3
Fold 1
Fold 2
Fold 3

✅ ELN con C2X-Complex_rhow_9x9_depth_in_0_1 - Mejor R2: 0.49
📋 Parámetros: {'alpha': 0.04123536257549618, 'l1_ratio': 0.5960250973908362}

Buscando mejores hiperparámetros para XGB con TOA_15x15_depth_in_0_1...
Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:32:42,676] Trial 0 finished with value: 0.5929799908771519 and parameters: {'n_estimators': 1250, 'learning_rate': 0.02, 'max_depth': 8, 'min_child_weight': 3, 'subsample': 0.7318316273239569, 'colsample_bytree': 0.7057248078043556}. Best is trial 0 with value: 0.5929799908771519.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:32:48,723] Trial 1 finished with value: 0.6228690849656923 and parameters: {'n_estimators': 1250, 'learning_rate': 0.02, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.6021080151098912, 'colsample_bytree': 0.710202184489963}. Best is trial 1 with value: 0.6228690849656923.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:32:54,951] Trial 2 finished with value: 0.6003203125211205 and parameters: {'n_estimators': 1250, 'learning_rate': 0.03, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.6826857050152854, 'colsample_bytree': 0.706575406831904}. Best is trial 1 with value: 0.6228690849656923.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:33:04,746] Trial 3 finished with value: 0.5790343077555994 and parameters: {'n_estimators': 1250, 'learning_rate': 0.02, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.7768612051413486, 'colsample_bytree': 0.6971231772150231}. Best is trial 1 with value: 0.6228690849656923.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:33:08,376] Trial 4 finished with value: 0.6255081774554799 and parameters: {'n_estimators': 750, 'learning_rate': 0.03, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.6544483259098335, 'colsample_bytree': 0.6051464017068795}. Best is trial 4 with value: 0.6255081774554799.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:33:15,104] Trial 5 finished with value: 0.611211553457996 and parameters: {'n_estimators': 1250, 'learning_rate': 0.03, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.7588317316993044, 'colsample_bytree': 0.6046329111605292}. Best is trial 4 with value: 0.6255081774554799.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:33:20,758] Trial 6 finished with value: 0.5888431574431982 and parameters: {'n_estimators': 1250, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.6239872523857267, 'colsample_bytree': 0.6781942678746138}. Best is trial 4 with value: 0.6255081774554799.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:33:25,918] Trial 7 finished with value: 0.622322663261558 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.6093134723707248, 'colsample_bytree': 0.6091738998706112}. Best is trial 4 with value: 0.6255081774554799.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:33:32,688] Trial 8 finished with value: 0.6248986181330481 and parameters: {'n_estimators': 1000, 'learning_rate': 0.02, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.6305215748104964, 'colsample_bytree': 0.6125339784963343}. Best is trial 4 with value: 0.6255081774554799.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:33:38,788] Trial 9 finished with value: 0.6009934160071903 and parameters: {'n_estimators': 750, 'learning_rate': 0.02, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.6227390032001643, 'colsample_bytree': 0.6217457968602829}. Best is trial 4 with value: 0.6255081774554799.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:33:44,500] Trial 10 finished with value: 0.6086621597669938 and parameters: {'n_estimators': 750, 'learning_rate': 0.03, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.6817324630856856, 'colsample_bytree': 0.7879423230100748}. Best is trial 4 with value: 0.6255081774554799.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:33:54,167] Trial 11 finished with value: 0.6175935951346166 and parameters: {'n_estimators': 1000, 'learning_rate': 0.03, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.6521023506628787, 'colsample_bytree': 0.6524522823380916}. Best is trial 4 with value: 0.6255081774554799.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:34:02,774] Trial 12 finished with value: 0.6241516589503328 and parameters: {'n_estimators': 1000, 'learning_rate': 0.02, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.6579075305150021, 'colsample_bytree': 0.6441260993718174}. Best is trial 4 with value: 0.6255081774554799.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:34:10,012] Trial 13 finished with value: 0.6138104641457134 and parameters: {'n_estimators': 750, 'learning_rate': 0.03, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.7133421884800705, 'colsample_bytree': 0.7544189150925875}. Best is trial 4 with value: 0.6255081774554799.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:34:16,049] Trial 14 finished with value: 0.6225755180375252 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.6464024501802181, 'colsample_bytree': 0.6405254742448054}. Best is trial 4 with value: 0.6255081774554799.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:34:21,834] Trial 15 finished with value: 0.5902141369990234 and parameters: {'n_estimators': 750, 'learning_rate': 0.02, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.6744858677921615, 'colsample_bytree': 0.6666757247546434}. Best is trial 4 with value: 0.6255081774554799.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:34:29,766] Trial 16 finished with value: 0.606397744953615 and parameters: {'n_estimators': 750, 'learning_rate': 0.03, 'max_depth': 8, 'min_child_weight': 4, 'subsample': 0.6372341274251258, 'colsample_bytree': 0.6270412714163329}. Best is trial 4 with value: 0.6255081774554799.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:34:38,336] Trial 17 finished with value: 0.5814134666496058 and parameters: {'n_estimators': 1000, 'learning_rate': 0.02, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.7049269622098064, 'colsample_bytree': 0.7341529162444149}. Best is trial 4 with value: 0.6255081774554799.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:34:44,396] Trial 18 finished with value: 0.5888465006164325 and parameters: {'n_estimators': 750, 'learning_rate': 0.03, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.6648649185755411, 'colsample_bytree': 0.6012002077641733}. Best is trial 4 with value: 0.6255081774554799.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:34:53,833] Trial 19 finished with value: 0.6257230529335557 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.6343131797343551, 'colsample_bytree': 0.6709479444665711}. Best is trial 19 with value: 0.6257230529335557.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:35:00,468] Trial 20 finished with value: 0.577943117053194 and parameters: {'n_estimators': 750, 'learning_rate': 0.01, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.6934694448735005, 'colsample_bytree': 0.6728393859000757}. Best is trial 19 with value: 0.6257230529335557.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:35:08,447] Trial 21 finished with value: 0.6254386887614484 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.6324526241126115, 'colsample_bytree': 0.6279634772254382}. Best is trial 19 with value: 0.6257230529335557.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:35:18,230] Trial 22 finished with value: 0.6257572305972947 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 8, 'min_child_weight': 4, 'subsample': 0.6423160439473994, 'colsample_bytree': 0.6290933213570498}. Best is trial 22 with value: 0.6257572305972947.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:35:28,908] Trial 23 finished with value: 0.6230857067022464 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 8, 'min_child_weight': 4, 'subsample': 0.655424162278962, 'colsample_bytree': 0.6581753491932066}. Best is trial 22 with value: 0.6257572305972947.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:35:39,807] Trial 24 finished with value: 0.6222756616163451 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 8, 'min_child_weight': 4, 'subsample': 0.6153606931692926, 'colsample_bytree': 0.6316682870318073}. Best is trial 22 with value: 0.6257572305972947.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:35:49,292] Trial 25 finished with value: 0.6214754228323404 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 8, 'min_child_weight': 4, 'subsample': 0.7243455057121619, 'colsample_bytree': 0.6875017459974658}. Best is trial 22 with value: 0.6257572305972947.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 13:35:58,735] Trial 26 finished with value: 0.6240923525569496 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.6420773547890284, 'colsample_bytree': 0.6468960070498417}. Best is trial 22 with value: 0.6257572305972947.

Fold 1
Fold 2

[W 2025-09-08 13:36:03,921] Trial 27 failed with parameters: {'n_estimators': 750, 'learning_rate': 0.01, 'max_depth': 8, 'min_child_weight': 3, 'subsample': 0.6694396039712016, 'colsample_bytree': 0.7301243298789246} because of the following error: KeyboardInterrupt().
Traceback (most recent call last):
  File "/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/study/_optimize.py", line 201, in _run_trial
    value_or_values = func(trial)
  File "/tmp/ipykernel_10242/2927183585.py", line 18, in <lambda>
    study.optimize(lambda trial: objective(trial, df, nombre_df, target, model_name), n_trials=n_trials, timeout= 1500)
  File "/tmp/ipykernel_10242/164190014.py", line 183, in objective
    model.fit(X_train, y_train)
  File "/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/xgboost/core.py", line 738, in inner_f
    return func(**kwargs)
  File "/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/xgboost/sklearn.py", line 1108, in fit
    self._Booster = train(
  File "/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/xgboost/core.py", line 738, in inner_f
    return func(**kwargs)
  File "/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/xgboost/training.py", line 181, in train
    bst.update(dtrain, iteration=i, fobj=obj)
  File "/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/xgboost/core.py", line 2113, in update
    _LIB.XGBoosterUpdateOneIter(
KeyboardInterrupt
[W 2025-09-08 13:36:03,929] Trial 27 failed with value None.

KeyboardInterrupt:

In [47]:
global_results

{('TOA_9x9_depth_in_3_4',
  'XGB'): {'best_params': {'n_estimators': 2000,
   'learning_rate': 0.047600594240155655,
   'max_depth': 5,
   'min_child_weight': 4,
   'subsample': 0.6049475476360661,
   'colsample_bytree': 0.8631912096943319}, 'best_score': 0.615, 'study': <optuna.study.study.Study at 0x7800b0502610>},
 ('TOA_9x9_depth_in_3_4',
  'LBM'): {'best_params': {'learning_rate': 0.01713416804277511,
   'num_leaves': 80,
   'max_depth': 8,
   'min_child_samples': 11,
   'subsample': 0.7883599431510695,
   'colsample_bytree': 0.8460115625974576,
   'n_estimators': 500}, 'best_score': 0.628, 'study': <optuna.study.study.Study at 0x7800b0502c10>},
 ('TOA_9x9_depth_in_3_4',
  'MLP'): {'best_params': {'hidden_layer_sizes': '256_128',
   'activation': 'relu',
   'solver': 'sgd',
   'alpha': 0.015492411781384838,
   'learning_rate': 'adaptive',
   'learning_rate_init': 0.0019024503727906594}, 'best_score': 0.71, 'study': <optuna.study.study.Study at 0x7800b014d100>},
 ('TOA_9x9_depth_in_3_4',
  'SVR'): {'best_params': {'C': 1.9860741741743726,
   'epsilon': 0.023712171259654913}, 'best_score': 0.504, 'study': <optuna.study.study.Study at 0x7800d80a13a0>},
 ('TOA_9x9_depth_in_3_4',
  'KNN'): {'best_params': {'n_neighbors': 10,
   'leaf_size': 40}, 'best_score': 0.65, 'study': <optuna.study.study.Study at 0x7800b03d04c0>},
 ('TOA_9x9_depth_in_3_4',
  'LR'): {'best_params': {'fit_intercept': False,
   'positive': False}, 'best_score': 0.378, 'study': <optuna.study.study.Study at 0x7800b04c3eb0>},
 ('TOA_9x9_depth_in_3_4',
  'RF'): {'best_params': {'n_estimators': 100,
   'max_depth': 14,
   'min_samples_split': 10,
   'min_samples_leaf': 2,
   'bootstrap': True}, 'best_score': 0.624, 'study': <optuna.study.study.Study at 0x7800b029aa60>},
 ('TOA_9x9_depth_in_3_4',
  'CAT'): {'best_params': {'iterations': 1000,
   'learning_rate': 0.0678180379236064,
   'depth': 8,
   'l2_leaf_reg': 2.511488464786048}, 'best_score': 0.621, 'study': <optuna.study.study.Study at 0x7800b0609370>},
 ('TOA_9x9_depth_in_3_4',
  'ELN'): {'best_params': {'alpha': 0.00010094145044864732,
   'l1_ratio': 0.5266509861480015}, 'best_score': 0.461, 'study': <optuna.study.study.Study at 0x7800d917cd00>},
 ('TOA_3x3_depth_in_3_4',
  'XGB'): {'best_params': {'n_estimators': 500,
   'learning_rate': 0.009576598127245279,
   'max_depth': 7,
   'min_child_weight': 4,
   'subsample': 0.7615794445091003,
   'colsample_bytree': 0.6930474458735117}, 'best_score': 0.627, 'study': <optuna.study.study.Study at 0x7800d930ac70>},
 ('TOA_3x3_depth_in_3_4',
  'LBM'): {'best_params': {'learning_rate': 0.01474336254464019,
   'num_leaves': 40,
   'max_depth': 6,
   'min_child_samples': 6,
   'subsample': 0.9964816945465981,
   'colsample_bytree': 0.8686133786839119,
   'n_estimators': 500}, 'best_score': 0.661, 'study': <optuna.study.study.Study at 0x7800b0557190>},
 ('TOA_3x3_depth_in_3_4',
  'MLP'): {'best_params': {'hidden_layer_sizes': '128_64',
   'activation': 'relu',
   'solver': 'adam',
   'alpha': 1.8399498662330756e-05,
   'learning_rate': 'constant',
   'learning_rate_init': 0.0005319925846193705}, 'best_score': 0.676, 'study': <optuna.study.study.Study at 0x7800a9f7a3a0>},
 ('TOA_3x3_depth_in_3_4',
  'SVR'): {'best_params': {'C': 2.4279016303695427,
   'epsilon': 0.08368239687667561}, 'best_score': 0.488, 'study': <optuna.study.study.Study at 0x7800b044be80>},
 ('TOA_3x3_depth_in_3_4',
  'KNN'): {'best_params': {'n_neighbors': 6,
   'leaf_size': 40}, 'best_score': 0.617, 'study': <optuna.study.study.Study at 0x7800b06f57f0>},
 ('TOA_3x3_depth_in_3_4',
  'LR'): {'best_params': {'fit_intercept': True,
   'positive': False}, 'best_score': 0.4, 'study': <optuna.study.study.Study at 0x7800b0187610>},
 ('TOA_3x3_depth_in_3_4',
  'RF'): {'best_params': {'n_estimators': 300,
   'max_depth': 12,
   'min_samples_split': 6,
   'min_samples_leaf': 3,
   'bootstrap': False}, 'best_score': 0.681, 'study': <optuna.study.study.Study at 0x7800b0354d30>},
 ('TOA_3x3_depth_in_3_4',
  'CAT'): {'best_params': {'iterations': 500,
   'learning_rate': 0.05232742477450515,
   'depth': 9,
   'l2_leaf_reg': 1.0235346499052462}, 'best_score': 0.63, 'study': <optuna.study.study.Study at 0x7800b02f4610>},
 ('TOA_3x3_depth_in_3_4',
  'ELN'): {'best_params': {'alpha': 0.00018219071583212146,
   'l1_ratio': 0.9794021781112037}, 'best_score': 0.467, 'study': <optuna.study.study.Study at 0x7800a9ffc9d0>},
 ('TOA_5x5_depth_in_3_4',
  'XGB'): {'best_params': {'n_estimators': 500,
   'learning_rate': 0.04876113896916153,
   'max_depth': 5,
   'min_child_weight': 4,
   'subsample': 0.7176461215093223,
   'colsample_bytree': 0.6759132844855982}, 'best_score': 0.627, 'study': <optuna.study.study.Study at 0x7800d919b280>},
 ('TOA_5x5_depth_in_3_4',
  'LBM'): {'best_params': {'learning_rate': 0.01955671466854787,
   'num_leaves': 60,
   'max_depth': 6,
   'min_child_samples': 4,
   'subsample': 0.9583671783514893,
   'colsample_bytree': 0.9991128614038579,
   'n_estimators': 500}, 'best_score': 0.678, 'study': <optuna.study.study.Study at 0x7800b02c6e20>},
 ('TOA_5x5_depth_in_3_4',
  'MLP'): {'best_params': {'hidden_layer_sizes': '128_64',
   'activation': 'relu',
   'solver': 'adam',
   'alpha': 0.00024472909052337217,
   'learning_rate': 'adaptive',
   'learning_rate_init': 0.0005084699170246252}, 'best_score': 0.697, 'study': <optuna.study.study.Study at 0x7800b004c0a0>},
 ('TOA_5x5_depth_in_3_4',
  'SVR'): {'best_params': {'C': 2.063097300418171,
   'epsilon': 0.0789893324667928}, 'best_score': 0.483, 'study': <optuna.study.study.Study at 0x7800b01fdb20>},
 ('TOA_5x5_depth_in_3_4',
  'KNN'): {'best_params': {'n_neighbors': 10,
   'leaf_size': 18}, 'best_score': 0.638, 'study': <optuna.study.study.Study at 0x7800b03aa640>},
 ('TOA_5x5_depth_in_3_4',
  'LR'): {'best_params': {'fit_intercept': True,
   'positive': False}, 'best_score': 0.448, 'study': <optuna.study.study.Study at 0x7800b029bd00>},
 ('TOA_5x5_depth_in_3_4',
  'RF'): {'best_params': {'n_estimators': 100,
   'max_depth': 15,
   'min_samples_split': 4,
   'min_samples_leaf': 3,
   'bootstrap': True}, 'best_score': 0.63, 'study': <optuna.study.study.Study at 0x7800b00a2ca0>},
 ('TOA_5x5_depth_in_3_4',
  'CAT'): {'best_params': {'iterations': 2000,
   'learning_rate': 0.01027011523144864,
   'depth': 7,
   'l2_leaf_reg': 1.0526076927639805}, 'best_score': 0.593, 'study': <optuna.study.study.Study at 0x7800b04bdaf0>},
 ('TOA_5x5_depth_in_3_4',
  'ELN'): {'best_params': {'alpha': 0.014403901229536019,
   'l1_ratio': 0.9023438654300626}, 'best_score': 0.474, 'study': <optuna.study.study.Study at 0x7800a9f6d8e0>},
 ('C2X-Complex_rhow_5x5_depth_in_3_4',
  'XGB'): {'best_params': {'n_estimators': 500,
   'learning_rate': 0.007889846245071235,
   'max_depth': 7,
   'min_child_weight': 4,
   'subsample': 0.6478799909895996,
   'colsample_bytree': 0.9184042139949454}, 'best_score': 0.652, 'study': <optuna.study.study.Study at 0x7800a9f5eb80>},
 ('C2X-Complex_rhow_5x5_depth_in_3_4',
  'LBM'): {'best_params': {'learning_rate': 0.006617912473095984,
   'num_leaves': 40,
   'max_depth': 8,
   'min_child_samples': 8,
   'subsample': 0.9303188839872626,
   'colsample_bytree': 0.7448045774739271,
   'n_estimators': 500}, 'best_score': 0.636, 'study': <optuna.study.study.Study at 0x7800b06a8d60>},
 ('C2X-Complex_rhow_5x5_depth_in_3_4',
  'MLP'): {'best_params': {'hidden_layer_sizes': '256_128',
   'activation': 'relu',
   'solver': 'adam',
   'alpha': 0.00010236429010965995,
   'learning_rate': 'adaptive',
   'learning_rate_init': 0.0003651197409167566}, 'best_score': 0.657, 'study': <optuna.study.study.Study at 0x7800b057dfa0>},
 ('C2X-Complex_rhow_5x5_depth_in_3_4',
  'SVR'): {'best_params': {'C': 9.555509499241047,
   'epsilon': 0.13134472658792118}, 'best_score': 0.537, 'study': <optuna.study.study.Study at 0x7800b0079520>},
 ('C2X-Complex_rhow_5x5_depth_in_3_4',
  'KNN'): {'best_params': {'n_neighbors': 10,
   'leaf_size': 40}, 'best_score': 0.588, 'study': <optuna.study.study.Study at 0x7800a9f3d160>},
 ('C2X-Complex_rhow_5x5_depth_in_3_4',
  'LR'): {'best_params': {'fit_intercept': False,
   'positive': True}, 'best_score': 0.548, 'study': <optuna.study.study.Study at 0x7800b06798b0>},
 ('C2X-Complex_rhow_5x5_depth_in_3_4',
  'RF'): {'best_params': {'n_estimators': 500,
   'max_depth': 12,
   'min_samples_split': 2,
   'min_samples_leaf': 2,
   'bootstrap': True}, 'best_score': 0.651, 'study': <optuna.study.study.Study at 0x7800b057f7f0>},
 ('C2X-Complex_rhow_5x5_depth_in_3_4',
  'CAT'): {'best_params': {'iterations': 500,
   'learning_rate': 0.014143036661619373,
   'depth': 4,
   'l2_leaf_reg': 2.864319547628134}, 'best_score': 0.63, 'study': <optuna.study.study.Study at 0x7800b06be1c0>},
 ('C2X-Complex_rhow_5x5_depth_in_3_4',
  'ELN'): {'best_params': {'alpha': 0.0025285029727796925,
   'l1_ratio': 0.5792628939321688}, 'best_score': 0.584, 'study': <optuna.study.study.Study at 0x7800d9079fa0>},
 ('TOA_1x1_depth_in_3_4',
  'XGB'): {'best_params': {'n_estimators': 500,
   'learning_rate': 0.005903889352876245,
   'max_depth': 8,
   'min_child_weight': 2,
   'subsample': 0.781917998902364,
   'colsample_bytree': 0.722278807877633}, 'best_score': 0.519, 'study': <optuna.study.study.Study at 0x7800b07592e0>},
 ('TOA_1x1_depth_in_3_4',
  'LBM'): {'best_params': {'learning_rate': 0.007130386687415869,
   'num_leaves': 20,
   'max_depth': 7,
   'min_child_samples': 10,
   'subsample': 0.8922959456502495,
   'colsample_bytree': 0.9294737227298466,
   'n_estimators': 500}, 'best_score': 0.618, 'study': <optuna.study.study.Study at 0x7800b0085820>},
 ('TOA_1x1_depth_in_3_4',
  'MLP'): {'best_params': {'hidden_layer_sizes': '256',
   'activation': 'relu',
   'solver': 'adam',
   'alpha': 4.763485358217016e-05,
   'learning_rate': 'adaptive',
   'learning_rate_init': 0.0004348441303622641}, 'best_score': 0.688, 'study': <optuna.study.study.Study at 0x7800b029aac0>},
 ('TOA_1x1_depth_in_3_4',
  'SVR'): {'best_params': {'C': 2.2111333817672927,
   'epsilon': 0.07253326854109794}, 'best_score': 0.461, 'study': <optuna.study.study.Study at 0x7800b025f2b0>},
 ('TOA_1x1_depth_in_3_4',
  'KNN'): {'best_params': {'n_neighbors': 6,
   'leaf_size': 33}, 'best_score': 0.611, 'study': <optuna.study.study.Study at 0x7800b01d88e0>},
 ('TOA_1x1_depth_in_3_4',
  'LR'): {'best_params': {'fit_intercept': False,
   'positive': True}, 'best_score': 0.328, 'study': <optuna.study.study.Study at 0x7800b021e070>},
 ('TOA_1x1_depth_in_3_4',
  'RF'): {'best_params': {'n_estimators': 500,
   'max_depth': 11,
   'min_samples_split': 6,
   'min_samples_leaf': 3,
   'bootstrap': True}, 'best_score': 0.557, 'study': <optuna.study.study.Study at 0x7800d8343670>},
 ('TOA_1x1_depth_in_3_4',
  'CAT'): {'best_params': {'iterations': 1000,
   'learning_rate': 0.033260444981323356,
   'depth': 8,
   'l2_leaf_reg': 1.12206076072196}, 'best_score': 0.569, 'study': <optuna.study.study.Study at 0x7800dcb5f460>},
 ('TOA_1x1_depth_in_3_4',
  'ELN'): {'best_params': {'alpha': 0.028283841413022752,
   'l1_ratio': 0.9109286287993379}, 'best_score': 0.452, 'study': <optuna.study.study.Study at 0x7800d92a9b50>},
 ('TOA_15x15_depth_in_3_4',
  'XGB'): {'best_params': {'n_estimators': 500,
   'learning_rate': 0.013566967402918429,
   'max_depth': 5,
   'min_child_weight': 4,
   'subsample': 0.6807531615273382,
   'colsample_bytree': 0.607434439562925}, 'best_score': 0.607, 'study': <optuna.study.study.Study at 0x7800b03f2220>},
 ('TOA_15x15_depth_in_3_4',
  'LBM'): {'best_params': {'learning_rate': 0.00909468587481228,
   'num_leaves': 60,
   'max_depth': 7,
   'min_child_samples': 13,
   'subsample': 0.6536720142119191,
   'colsample_bytree': 0.8953446248078664,
   'n_estimators': 1000}, 'best_score': 0.632, 'study': <optuna.study.study.Study at 0x7800a9661100>},
 ('TOA_15x15_depth_in_3_4',
  'MLP'): {'best_params': {'hidden_layer_sizes': '256',
   'activation': 'relu',
   'solver': 'adam',
   'alpha': 0.0034242834875374936,
   'learning_rate': 'constant',
   'learning_rate_init': 0.0012220669807227185}, 'best_score': 0.708, 'study': <optuna.study.study.Study at 0x7800a8debf10>},
 ('TOA_15x15_depth_in_3_4',
  'SVR'): {'best_params': {'C': 2.15684226903379,
   'epsilon': 0.12775727625293434}, 'best_score': 0.494, 'study': <optuna.study.study.Study at 0x7800a8dacc40>},
 ('TOA_15x15_depth_in_3_4',
  'KNN'): {'best_params': {'n_neighbors': 7,
   'leaf_size': 31}, 'best_score': 0.649, 'study': <optuna.study.study.Study at 0x7800a9eb7c70>},
 ('TOA_15x15_depth_in_3_4',
  'LR'): {'best_params': {'fit_intercept': False,
   'positive': False}, 'best_score': 0.38, 'study': <optuna.study.study.Study at 0x7800a9f4b820>},
 ('TOA_15x15_depth_in_3_4',
  'RF'): {'best_params': {'n_estimators': 100,
   'max_depth': 10,
   'min_samples_split': 2,
   'min_samples_leaf': 2,
   'bootstrap': True}, 'best_score': 0.617, 'study': <optuna.study.study.Study at 0x7800a8dff730>},
 ('TOA_15x15_depth_in_3_4',
  'CAT'): {'best_params': {'iterations': 2000,
   'learning_rate': 0.05314326154992145,
   'depth': 9,
   'l2_leaf_reg': 1.0213152871705147}, 'best_score': 0.681, 'study': <optuna.study.study.Study at 0x7800a8d816a0>},
 ('TOA_15x15_depth_in_3_4',
  'ELN'): {'best_params': {'alpha': 0.00011287578590294489,
   'l1_ratio': 0.9941527400112994}, 'best_score': 0.505, 'study': <optuna.study.study.Study at 0x7800a8dab1c0>},
 ('C2X-Complex_rhown_5x5_depth_in_3_4',
  'XGB'): {'best_params': {'n_estimators': 2000,
   'learning_rate': 0.045720937679426726,
   'max_depth': 7,
   'min_child_weight': 2,
   'subsample': 0.8049551995941774,
   'colsample_bytree': 0.9077296398951732}, 'best_score': 0.637, 'study': <optuna.study.study.Study at 0x7800a8d94d30>},
 ('C2X-Complex_rhown_5x5_depth_in_3_4',
  'LBM'): {'best_params': {'learning_rate': 0.021490317734639115,
   'num_leaves': 60,
   'max_depth': 7,
   'min_child_samples': 4,
   'subsample': 0.9171600598982209,
   'colsample_bytree': 0.9060991657287198,
   'n_estimators': 500}, 'best_score': 0.623, 'study': <optuna.study.study.Study at 0x7800e4412a90>},
 ('C2X-Complex_rhown_5x5_depth_in_3_4',
  'MLP'): {'best_params': {'hidden_layer_sizes': '256_128',
   'activation': 'relu',
   'solver': 'sgd',
   'alpha': 0.0028311644287798946,
   'learning_rate': 'constant',
   'learning_rate_init': 0.005228148188640056}, 'best_score': 0.618, 'study': <optuna.study.study.Study at 0x7800b018e790>},
 ('C2X-Complex_rhown_5x5_depth_in_3_4',
  'SVR'): {'best_params': {'C': 3.645085787366226,
   'epsilon': 0.18516646571349163}, 'best_score': 0.509, 'study': <optuna.study.study.Study at 0x7800a9673850>},
 ('C2X-Complex_rhown_5x5_depth_in_3_4',
  'KNN'): {'best_params': {'n_neighbors': 10,
   'leaf_size': 34}, 'best_score': 0.571, 'study': <optuna.study.study.Study at 0x7800b00b8e50>},
 ('C2X-Complex_rhown_5x5_depth_in_3_4',
  'LR'): {'best_params': {'fit_intercept': False,
   'positive': True}, 'best_score': 0.537, 'study': <optuna.study.study.Study at 0x7800b04e9340>},
 ('C2X-Complex_rhown_5x5_depth_in_3_4',
  'RF'): {'best_params': {'n_estimators': 500,
   'max_depth': 11,
   'min_samples_split': 4,
   'min_samples_leaf': 2,
   'bootstrap': True}, 'best_score': 0.641, 'study': <optuna.study.study.Study at 0x7800b06798e0>},
 ('C2X-Complex_rhown_5x5_depth_in_3_4',
  'CAT'): {'best_params': {'iterations': 500,
   'learning_rate': 0.025340947072845177,
   'depth': 6,
   'l2_leaf_reg': 5.927927435982809}, 'best_score': 0.603, 'study': <optuna.study.study.Study at 0x7800a9f92b50>},
 ('C2X-Complex_rhown_5x5_depth_in_3_4',
  'ELN'): {'best_params': {'alpha': 0.029440640009221405,
   'l1_ratio': 0.9952562878940697}, 'best_score': 0.573, 'study': <optuna.study.study.Study at 0x7800a9f92fa0>},
 ('C2X-Complex_rhow_9x9_depth_in_3_4',
  'XGB'): {'best_params': {'n_estimators': 500,
   'learning_rate': 0.007784242501186818,
   'max_depth': 6,
   'min_child_weight': 1,
   'subsample': 0.6045990140239461,
   'colsample_bytree': 0.9996062608334324}, 'best_score': 0.616, 'study': <optuna.study.study.Study at 0x7800a8d96a00>},
 ('C2X-Complex_rhow_9x9_depth_in_3_4',
  'LBM'): {'best_params': {'learning_rate': 0.006387333436517826,
   'num_leaves': 80,
   'max_depth': 8,
   'min_child_samples': 13,
   'subsample': 0.6384425602632136,
   'colsample_bytree': 0.6626794560644892,
   'n_estimators': 500}, 'best_score': 0.624, 'study': <optuna.study.study.Study at 0x7800d911cc10>},
 ('C2X-Complex_rhow_9x9_depth_in_3_4',
  'MLP'): {'best_params': {'hidden_layer_sizes': '256_128',
   'activation': 'relu',
   'solver': 'adam',
   'alpha': 0.0014611726954603002,
   'learning_rate': 'constant',
   'learning_rate_init': 0.0006912854086058073}, 'best_score': 0.649, 'study': <optuna.study.study.Study at 0x7800a8dd2790>},
 ('C2X-Complex_rhow_9x9_depth_in_3_4',
  'SVR'): {'best_params': {'C': 9.93157967401947,
   'epsilon': 0.1963107857538181}, 'best_score': 0.598, 'study': <optuna.study.study.Study at 0x7800b036ba60>},
 ('C2X-Complex_rhow_9x9_depth_in_3_4',
  'KNN'): {'best_params': {'n_neighbors': 9,
   'leaf_size': 27}, 'best_score': 0.579, 'study': <optuna.study.study.Study at 0x7800a9eb3460>},
 ('C2X-Complex_rhow_9x9_depth_in_3_4',
  'LR'): {'best_params': {'fit_intercept': False,
   'positive': True}, 'best_score': 0.569, 'study': <optuna.study.study.Study at 0x7800d8f87d90>},
 ('C2X-Complex_rhow_9x9_depth_in_3_4',
  'RF'): {'best_params': {'n_estimators': 100,
   'max_depth': 14,
   'min_samples_split': 3,
   'min_samples_leaf': 1,
   'bootstrap': True}, 'best_score': 0.63, 'study': <optuna.study.study.Study at 0x7800a8e23940>},
 ('C2X-Complex_rhow_9x9_depth_in_3_4',
  'CAT'): {'best_params': {'iterations': 1000,
   'learning_rate': 0.07521844621271666,
   'depth': 5,
   'l2_leaf_reg': 4.739858256733454}, 'best_score': 0.617, 'study': <optuna.study.study.Study at 0x7800b01b6430>},
 ('C2X-Complex_rhow_9x9_depth_in_3_4',
  'ELN'): {'best_params': {'alpha': 0.015126276739043923,
   'l1_ratio': 0.3433210919466816}, 'best_score': 0.589, 'study': <optuna.study.study.Study at 0x7800a9ecdbe0>},
 ('C2X-Complex_rhow_15x15_depth_in_3_4',
  'XGB'): {'best_params': {'n_estimators': 1000,
   'learning_rate': 0.010148550064538592,
   'max_depth': 7,
   'min_child_weight': 1,
   'subsample': 0.7092554975366574,
   'colsample_bytree': 0.9589996114894445}, 'best_score': 0.548, 'study': <optuna.study.study.Study at 0x7800a9f0bc70>},
 ('C2X-Complex_rhow_15x15_depth_in_3_4',
  'LBM'): {'best_params': {'learning_rate': 0.005034271791889273,
   'num_leaves': 60,
   'max_depth': 6,
   'min_child_samples': 11,
   'subsample': 0.9704198407257476,
   'colsample_bytree': 0.8302542907662975,
   'n_estimators': 500}, 'best_score': 0.555, 'study': <optuna.study.study.Study at 0x7800a8e6bf40>},
 ('C2X-Complex_rhow_15x15_depth_in_3_4',
  'MLP'): {'best_params': {'hidden_layer_sizes': '256',
   'activation': 'relu',
   'solver': 'adam',
   'alpha': 0.03673448429184167,
   'learning_rate': 'adaptive',
   'learning_rate_init': 0.005512541724045937}, 'best_score': 0.638, 'study': <optuna.study.study.Study at 0x7800a9f6f5b0>},
 ('C2X-Complex_rhow_15x15_depth_in_3_4',
  'SVR'): {'best_params': {'C': 3.2413369664629386,
   'epsilon': 0.1982961712911414}, 'best_score': 0.584, 'study': <optuna.study.study.Study at 0x7800d8fe5ee0>},
 ('C2X-Complex_rhow_15x15_depth_in_3_4',
  'KNN'): {'best_params': {'n_neighbors': 10,
   'leaf_size': 19}, 'best_score': 0.484, 'study': <optuna.study.study.Study at 0x7800a8e0ebb0>},
 ('C2X-Complex_rhow_15x15_depth_in_3_4',
  'LR'): {'best_params': {'fit_intercept': True,
   'positive': True}, 'best_score': 0.537, 'study': <optuna.study.study.Study at 0x7800a8e796a0>},
 ('C2X-Complex_rhow_15x15_depth_in_3_4',
  'RF'): {'best_params': {'n_estimators': 100,
   'max_depth': 8,
   'min_samples_split': 3,
   'min_samples_leaf': 4,
   'bootstrap': True}, 'best_score': 0.572, 'study': <optuna.study.study.Study at 0x7800a9ec8d30>},
 ('C2X-Complex_rhow_15x15_depth_in_3_4',
  'CAT'): {'best_params': {'iterations': 500,
   'learning_rate': 0.010126948003726963,

In [76]:
with open(f"training_results/selection_results_{depth}.pkl", "wb") as f:
    pickle.dump(global_results, f)

In [39]:
# Diccionario para agrupar parámetros por modelo
params_by_model = defaultdict(list)

# Agrupar best_params por modelo
for (df_name, model_name), result in global_results.items():
    best_params = result["best_params"]
    params_by_model[model_name].append(best_params)

# Crear DataFrames con medias y std por modelo
summary_stats = {}

for model_name, param_list in params_by_model.items():
    df_params = pd.DataFrame(param_list)

    # Filtramos solo columnas numéricas para calcular medias y std
    df_numeric = df_params.select_dtypes(include=[np.number])

    stats = pd.concat([df_numeric.mean().rename("mean"), df_numeric.std().rename("std")], axis=1)
    summary_stats[model_name] = stats

# Mostrar un ejemplo
summary_stats["LBM"]

                         mean         std
learning_rate        0.011264    0.006322
num_leaves          52.000000   21.499354
max_depth            6.800000    1.032796
min_child_samples    9.000000    3.366502
subsample            0.846105    0.135599
colsample_bytree     0.853437    0.094603
n_estimators       550.000000  158.113883

In [77]:
global_results

{('C2X-Complex_rhow_9x9_depth_in_0_1',
  'XGB'): {'best_params': {'n_estimators': 400,
   'learning_rate': 0.010130819207976474,
   'max_depth': 3,
   'min_child_weight': 4,
   'subsample': 0.6466932179565845,
   'colsample_bytree': 0.863252176802725,
   'reg_alpha': 4.690598830858826,
   'reg_lambda': 2.45182006997585}, 'best_score': 0.647},
 ('C2X-Complex_rhow_9x9_depth_in_0_1',
  'LBM'): {'best_params': {'learning_rate': 0.0180173396623031,
   'num_leaves': 10,
   'max_depth': 4,
   'min_child_samples': 7,
   'subsample': 0.9691353325596449,
   'colsample_bytree': 0.8647429278156027,
   'n_estimators': 400,
   'reg_alpha': 0.002205137562138462,
   'reg_lambda': 3.8972417461043776,
   'min_split_gain': 0.0}, 'best_score': 0.65},
 ('C2X-Complex_rhow_9x9_depth_in_0_1',
  'MLP'): {'best_params': {'hidden_layer_sizes': (128,),
   'activation': 'tanh',
   'solver': 'adam',
   'alpha': 0.0011908618164157352,
   'learning_rate': 'constant',
   'learning_rate_init': 0.0017720053047611522}, 'best_score': 0.61},
 ('C2X-Complex_rhow_9x9_depth_in_0_1',
  'SVR'): {'best_params': {'C': 3.9386384240176913,
   'epsilon': 0.13356302312909252}, 'best_score': 0.583},
 ('C2X-Complex_rhow_9x9_depth_in_0_1',
  'KNN'): {'best_params': {'n_neighbors': 11,
   'leaf_size': 31}, 'best_score': 0.597},
 ('C2X-Complex_rhow_9x9_depth_in_0_1',
  'LR'): {'best_params': {'fit_intercept': False,
   'positive': True}, 'best_score': 0.331},
 ('C2X-Complex_rhow_9x9_depth_in_0_1',
  'RF'): {'best_params': {'n_estimators': 1000,
   'max_depth': 5,
   'min_samples_split': 4,
   'min_samples_leaf': 2,
   'bootstrap': True}, 'best_score': 0.583},
 ('C2X-Complex_rhow_9x9_depth_in_0_1',
  'CAT'): {'best_params': {'iterations': 250,
   'learning_rate': 0.0756380808532654,
   'depth': 7,
   'l2_leaf_reg': 2.5411091406930897}, 'best_score': 0.675},
 ('C2X-Complex_rhow_9x9_depth_in_0_1',
  'ELN'): {'best_params': {'alpha': 0.011909689277147112,
   'l1_ratio': 0.6705067016233937}, 'best_score': 0.491},
 ('TOA_15x15_depth_in_0_1',
  'XGB'): {'best_params': {'n_estimators': 200,
   'learning_rate': 0.024471415345560892,
   'max_depth': 5,
   'min_child_weight': 4,
   'subsample': 0.7265771487440407,
   'colsample_bytree': 0.7775278664043689,
   'reg_alpha': 0.5613433496336138,
   'reg_lambda': 0.002550744579989708}, 'best_score': 0.627},
 ('TOA_15x15_depth_in_0_1',
  'LBM'): {'best_params': {'learning_rate': 0.02145535516045795,
   'num_leaves': 20,
   'max_depth': 3,
   'min_child_samples': 4,
   'subsample': 0.694504550531154,
   'colsample_bytree': 0.7080350560291987,
   'n_estimators': 400,
   'reg_alpha': 0.04488177599212278,
   'reg_lambda': 4.088104008042177,
   'min_split_gain': 1.0}, 'best_score': 0.708},
 ('TOA_15x15_depth_in_0_1',
  'MLP'): {'best_params': {'hidden_layer_sizes': (32,),
   'activation': 'tanh',
   'solver': 'adam',
   'alpha': 0.00015456085838171134,
   'learning_rate': 'adaptive',
   'learning_rate_init': 0.004321905618989237}, 'best_score': 0.573},
 ('TOA_15x15_depth_in_0_1',
  'SVR'): {'best_params': {'C': 3.1895539854205484,
   'epsilon': 0.18977910716291796}, 'best_score': 0.16},
 ('TOA_15x15_depth_in_0_1',
  'KNN'): {'best_params': {'n_neighbors': 6,
   'leaf_size': 17}, 'best_score': 0.685},
 ('TOA_15x15_depth_in_0_1',
  'LR'): {'best_params': {'fit_intercept': False,
   'positive': False}, 'best_score': 0.268},
 ('TOA_15x15_depth_in_0_1',
  'RF'): {'best_params': {'n_estimators': 250,
   'max_depth': 4,
   'min_samples_split': 4,
   'min_samples_leaf': 4,
   'bootstrap': False}, 'best_score': 0.676},
 ('TOA_15x15_depth_in_0_1',
  'CAT'): {'best_params': {'iterations': 500,
   'learning_rate': 0.0489561833218288,
   'depth': 7,
   'l2_leaf_reg': 4.107360431179985}, 'best_score': 0.748},
 ('TOA_15x15_depth_in_0_1',
  'ELN'): {'best_params': {'alpha': 0.0006904285328981824,
   'l1_ratio': 0.5643108754372316}, 'best_score': 0.477},
 ('C2X-Complex_rhown_9x9_depth_in_0_1',
  'XGB'): {'best_params': {'n_estimators': 800,
   'learning_rate': 0.01770672414044032,
   'max_depth': 4,
   'min_child_weight': 4,
   'subsample': 0.6601809216151284,
   'colsample_bytree': 0.8391852713063789,
   'reg_alpha': 7.564600608481072,
   'reg_lambda': 5.202422425136457}, 'best_score': 0.668},
 ('C2X-Complex_rhown_9x9_depth_in_0_1',
  'LBM'): {'best_params': {'learning_rate': 0.020544903012824623,
   'num_leaves': 30,
   'max_depth': 4,
   'min_child_samples': 4,
   'subsample': 0.8766068394586368,
   'colsample_bytree': 0.7785675443310818,
   'n_estimators': 200,
   'reg_alpha': 0.1949801950057403,
   'reg_lambda': 1.0757420053093538,
   'min_split_gain': 0.1}, 'best_score': 0.661},
 ('C2X-Complex_rhown_9x9_depth_in_0_1',
  'MLP'): {'best_params': {'hidden_layer_sizes': (64,),
   'activation': 'tanh',
   'solver': 'adam',
   'alpha': 0.049060660674847996,
   'learning_rate': 'constant',
   'learning_rate_init': 0.003087876915473385}, 'best_score': 0.647},
 ('C2X-Complex_rhown_9x9_depth_in_0_1',
  'SVR'): {'best_params': {'C': 4.7599704979394915,
   'epsilon': 0.09506214370520978}, 'best_score': 0.611},
 ('C2X-Complex_rhown_9x9_depth_in_0_1',
  'KNN'): {'best_params': {'n_neighbors': 11,
   'leaf_size': 17}, 'best_score': 0.6},
 ('C2X-Complex_rhown_9x9_depth_in_0_1',
  'LR'): {'best_params': {'fit_intercept': False,
   'positive': True}, 'best_score': 0.37},
 ('C2X-Complex_rhown_9x9_depth_in_0_1',
  'RF'): {'best_params': {'n_estimators': 500,
   'max_depth': 4,
   'min_samples_split': 4,
   'min_samples_leaf': 2,
   'bootstrap': True}, 'best_score': 0.575},
 ('C2X-Complex_rhown_9x9_depth_in_0_1',
  'CAT'): {'best_params': {'iterations': 250,
   'learning_rate': 0.042443431081201584,
   'depth': 7,
   'l2_leaf_reg': 4.644143785341621}, 'best_score': 0.646},
 ('C2X-Complex_rhown_9x9_depth_in_0_1',
  'ELN'): {'best_params': {'alpha': 0.010375237343643838,
   'l1_ratio': 0.7025948455573761}, 'best_score': 0.535}}

**Entrenamiento con los parámetros seleccionados**

In [78]:
results = {}

for nombre_df, df in list(dfs.items()):
    #print(nombre_df)
    df = df.iloc[:,4:]

    # Para usar solamente bandas, sin combinaciones
    # if 'TOA' in nombre_df:
    #     # TOA solamente con las bandas, parece que las combinaciones solo meten ruido
    #     df = df.iloc[:,np.r_[0:14, 58:60]]
    # if 'rhow' in nombre_df and 'rhown' not in nombre_df:
    #     df = df.iloc[:,np.r_[0:9, 53:55]]
    # if 'rhown' in nombre_df:
    #     df = df.iloc[:,np.r_[0:7, 51:53]]

    train, test = train_test_split(df, test_size=0.2, random_state=42, stratify=df["High_Chl"]) # TEST 20% TRAIN 80%
    target = "Chl"

    train, val = train_test_split(train, test_size=0.25, random_state=42, stratify=train["High_Chl"]) # TRAIN 60% VAL 20% TEST%

    X_train = train.drop(columns=[target,"High_Chl"])
    X_val = val.drop(columns=[target, "High_Chl"])
    X_test = test.drop(columns=[target, "High_Chl"])
    y_train = train[target]
    y_val = val[target]
    y_test = test[target]

    
    scaler_X = RobustScaler()
    scaler_y = RobustScaler()
    X_train_scaled = scaler_X.fit_transform(X_train)
    X_val_scaled = scaler_X.transform(X_val)
    X_test_scaled = scaler_X.transform(X_test)
    y_train_scaled = scaler_y.fit_transform(y_train.values.reshape(-1, 1)).ravel()
    
    results[nombre_df] = {name: {'RMSE': None, 'R2': None} for name in models}
    val_preds = {}
    test_preds = {}

    for name, model in models.items():
        print(f"Fitting {name} for {nombre_df}")
        if name in ["MLP", "SVR", "KNN", "LR", "EN"]:
            model.fit(X_train_scaled, y_train_scaled)
            #test_pred = model.predict(X_test_scaled)
            val_pred = scaler_y.inverse_transform(model.predict(X_val_scaled).reshape(-1, 1)).ravel()
            test_pred = scaler_y.inverse_transform(model.predict(X_test_scaled).reshape(-1, 1)).ravel()
        else:
            model.fit(X_train, y_train)
            val_pred = model.predict(X_val)
            test_pred = model.predict(X_test)

        val_preds[name] = val_pred
        test_preds[name] = test_pred

        rmse = np.sqrt(mean_squared_error(y_test, test_pred))
        r2 = r2_score(y_test, test_pred)

        results[nombre_df][name]['RMSE'] = rmse.round(2)
        results[nombre_df][name]['R2'] = r2.round(2)

    # Meta-modelo
    meta_X = np.vstack([val_preds[model] for model in models]).T
    meta_y = y_val.values
    meta_model = Ridge().fit(meta_X, meta_y)

    # Predicción final ensemble
    test_meta_X = np.vstack([test_preds[model] for model in models]).T
    ensemble_pred = meta_model.predict(test_meta_X)

    rmse_ens = np.sqrt(mean_squared_error(y_test, ensemble_pred))
    r2_ens = r2_score(y_test, ensemble_pred)

    results[nombre_df]["Ensemble"] = {
        "RMSE": round(rmse_ens, 2),
        "R2": round(r2_ens, 2)
    }

Fitting XGB for C2X-Complex_rhow_9x9_depth_in_0_1

TypeError: fit() missing 1 required positional argument: 'y'

In [329]:
rows = []

for df_name, model_scores in results.items():
    row = {}
    for model_name, metrics in model_scores.items():
        for metric_name, values in metrics.items():
            if isinstance(values, list):  # Solo para los que tienen listas (folds)
                mean_val = np.mean(values)
                std_val = np.std(values)
                row[(metric_name, model_name)] = f"{mean_val:.2f} ± {std_val:.2f}"
            else:
                # Para el ensemble que tiene un único valor
                row[(metric_name, model_name)] = f"{values:.2f}"
    rows.append((df_name, row))

df_results = pd.DataFrame.from_dict(dict(rows), orient="index")
df_results.columns = pd.MultiIndex.from_tuples(df_results.columns, names=["Metric", "Model"])
df_results = df_results.sort_index(axis=1, level=0)
df_results = df_results.sort_index(axis=0)

In [330]:
df_results

Metric                                     R2                         \
Model                                     CAT           EN  Ensemble
C2RCC_rhow_5x5_depth_lt_1         0.67 ± 0.13  0.48 ± 0.07      0.61
C2X-Complex_rhown_3x3_depth_lt_1  0.66 ± 0.12  0.50 ± 0.06  -6049.03
TOA_9x9_depth_lt_1                0.78 ± 0.12  0.19 ± 0.13      0.46

Metric                                                                    \
Model                                     KNN          LBM            LR
C2RCC_rhow_5x5_depth_lt_1         0.74 ± 0.10  0.61 ± 0.24   0.31 ± 0.52
C2X-Complex_rhown_3x3_depth_lt_1  0.59 ± 0.12  0.55 ± 0.17  -1.12 ± 3.18
TOA_9x9_depth_lt_1                0.76 ± 0.13  0.70 ± 0.09   0.18 ± 0.36

Metric                                                                   \
Model                                     MLP           RF          SVR
C2RCC_rhow_5x5_depth_lt_1         0.71 ± 0.12  0.63 ± 0.18  0.66 ± 0.15
C2X-Complex_rhown_3x3_depth_lt_1  0.45 ± 0.08  0.63 ± 0.11  0.53 ± 0.09
TOA_9x9_depth_lt_1                0.65 ± 0.14  0.70 ± 0.13  0.50 ± 0.04

Metric                                                RMSE               \
Model                                     XGB          CAT           EN
C2RCC_rhow_5x5_depth_lt_1         0.65 ± 0.19  2.04 ± 0.37  2.64 ± 0.20
C2X-Complex_rhown_3x3_depth_lt_1  0.61 ± 0.17  2.08 ± 0.17  2.63 ± 0.41
TOA_9x9_depth_lt_1                0.72 ± 0.12  1.80 ± 0.49  3.58 ± 0.15

Metric                                                               \
Model                            Ensemble          KNN          LBM
C2RCC_rhow_5x5_depth_lt_1            2.97  1.81 ± 0.21  2.16 ± 0.50
C2X-Complex_rhown_3x3_depth_lt_1   370.82  2.30 ± 0.17  2.41 ± 0.25
TOA_9x9_depth_lt_1                   2.59  1.87 ± 0.37  2.15 ± 0.32

Metric                                                                   \
Model                                      LR          MLP           RF
C2RCC_rhow_5x5_depth_lt_1         2.83 ± 0.72  1.93 ± 0.27  2.14 ± 0.35
C2X-Complex_rhown_3x3_depth_lt_1  4.08 ± 2.64  2.77 ± 0.44  2.21 ± 0.17
TOA_9x9_depth_lt_1                3.49 ± 0.48  2.31 ± 0.28  2.12 ± 0.39

Metric
Model                                     SVR          XGB
C2RCC_rhow_5x5_depth_lt_1         2.08 ± 0.31  2.08 ± 0.44
C2X-Complex_rhown_3x3_depth_lt_1  2.52 ± 0.31  2.21 ± 0.28
TOA_9x9_depth_lt_1                2.84 ± 0.26  2.05 ± 0.44