In [88]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import os
pd.options.mode.chained_assignment = None
import optuna
import time
from sklearn.metrics import r2_score, mean_squared_error
from sklearn.model_selection import cross_val_score, KFold, StratifiedKFold, train_test_split
from xgboost import XGBRegressor
from catboost import CatBoostRegressor
from lightgbm import LGBMRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression, Ridge, ElasticNet
from sklearn.neighbors import KNeighborsRegressor
from sklearn.neural_network import MLPRegressor
from sklearn.svm import SVR
from sklearn.preprocessing import StandardScaler, RobustScaler
import pickle
from collections import defaultdict

In [89]:
depths = ["in_0_1"] #"in_1_2", "in_2_3", "in_3_4"]
for depth in depths: 
    # Cargamos los csv de los tifs
    path = "saved_files/dataset"
    dfs = {}
    for archivo in os.listdir(path):
        if archivo.endswith(f"{depth}_features.csv"):
            nombre_sin_extension = os.path.splitext(archivo)[0]  # sin .csv
            ruta_completa = os.path.join(path, archivo)
            dfs[nombre_sin_extension[:-9]] = pd.read_csv(ruta_completa)



    # Limpiamos valores nulos
    for nombre_df, df in dfs.items():
        for band_set in ["rhow", "rhown","rtoa"]:
            dfs[nombre_df] = df.dropna()

    dfs_to_keep = [
		'C2X-Complex_rhow_9x9_depth_in_0_1', 
		'TOA_15x15_depth_in_0_1',
		'C2X-Complex_rhown_9x9_depth_in_0_1',
		# 'C2X-Complex_rhow_5x5_depth_in_0_1',
		# 'C2RCC_rhow_5x5_depth_in_0_1',
		# 'C2RCC_rhow_15x15_depth_in_0_1', 
		# 'C2X-Complex_rhown_15x15_depth_in_0_1',
		# 'C2RCC_rhown_5x5_depth_in_0_1', 
		# 'C2X-Complex_rhow_15x15_depth_in_0_1',
		# 'C2RCC_rhow_9x9_depth_in_0_1',
		# 'C2X-Complex_rhow_5x5_depth_in_1_2', 
		# 'C2X_rhow_3x3_depth_in_1_2',
		# 'C2X-Complex_rhown_5x5_depth_in_1_2',
		# 'C2X-Complex_rhow_9x9_depth_in_1_2',
		# 'C2X-Complex_rhow_3x3_depth_in_1_2',
		# 'C2X-Complex_rhown_3x3_depth_in_1_2',
		# 'C2RCC_rhown_3x3_depth_in_1_2',
		# 'C2X-Complex_rhown_9x9_depth_in_1_2',
		# 'C2X-Complex_rhow_15x15_depth_in_1_2', 
		# 'C2X_rhow_5x5_depth_in_1_2',
        # 'TOA_15x15_depth_in_2_3',
		# 'TOA_9x9_depth_in_2_3',
		# 'TOA_5x5_depth_in_2_3', 
		# 'C2X-Complex_rhow_5x5_depth_in_2_3',
		# 'C2RCC_rhown_5x5_depth_in_2_3', 
		# 'TOA_3x3_depth_in_2_3',
		# 'C2X-Complex_rhown_5x5_depth_in_2_3', 
		# 'C2RCC_rhow_3x3_depth_in_2_3',
		# 'C2X-Complex_rhown_9x9_depth_in_2_3', 
		# 'C2X_rhow_9x9_depth_in_2_3',
        # 'TOA_9x9_depth_in_3_4',
		# 'TOA_3x3_depth_in_3_4',
		# 'TOA_5x5_depth_in_3_4',
		# 'C2X-Complex_rhow_5x5_depth_in_3_4', 
		# 'TOA_1x1_depth_in_3_4',
		# 'TOA_15x15_depth_in_3_4',
		# 'C2X-Complex_rhown_5x5_depth_in_3_4',
		# 'C2X-Complex_rhow_9x9_depth_in_3_4',
		# 'C2X-Complex_rhow_15x15_depth_in_3_4',
		# 'C2X-Complex_rhown_9x9_depth_in_3_4'
        ]

    dfs = {k: dfs[k] for k in dfs_to_keep if k in dfs}


    for nombre_df, df in dfs.items():
        # Marcamos las columnas de CHl alta (equivalente a quantile(0.93))
        df["High_Chl"] = df["Chl"]>5
        # Sacamos la estación de cada fecha
        df['Date'] = pd.to_datetime(df['Date'])
        def get_season(month):
            if month in [12, 1, 2]:
                return 'Invierno'
            elif month in [3, 4, 5]:
                return 'Primavera'
            elif month in [6, 7, 8]:
                return 'Verano'
            else:
                return 'Otoño'
        df['Season'] = df['Date'].dt.month.apply(get_season)
        for col in df.select_dtypes(include='object').columns:
            df[col] = df[col].astype('category')
        df = pd.concat([df.drop(columns=["Season"]),pd.get_dummies(df["Season"])], axis=1)
        dfs[nombre_df] = df

### Optimización de hiperparámetros

In [95]:
def objective(trial, df, nombre_df, target, model_name):
    # Mismo proceso que para validación cruzada, pero haciendo preds solamente sobre test
    FOLDS = 3
    # Para hacer clip a las predicciones y forzar > 0
    correct = True
    results = {}

    df = df.iloc[:, 4:]

    # Separamos el conjunto de datos en train y test: Train 75% Test 25%
    train, test = train_test_split(df, test_size=0.25, random_state=42, stratify=df["High_Chl"])
    # Seleccionamos la columna que queremos predecir
    target = "Chl"

    # Quitamos esa columna y el indicador de clorofila alta
    X = train.drop(columns=[target, "High_Chl", "Turbidez"])
    # Para y cogemos solamente Chl
    y = train[target]
    # Para poder hacer StratifiedKFold y tener el mismo número de valores de Chl alta en cada fold
    y_class = train["High_Chl"]

    # Definimos X e y para test
    #X_test = test.drop(columns=[target, "High_Chl", "Turbidez"])
    #y_test = test[target]

    # Dicts para guardar las predicciones sobre los conjuntos de validación, las y's correspondientes y los índices que corresponden dentro del loop de folds para el ensemble
    val_preds = {name: np.zeros(len(train)) for name in models}
    y_vals = defaultdict(list)
    val_indices = {}
    # Dict para guardar las predicciones sobre test
    #test_preds = {name: np.zeros(len(test)) for name in models}
    
    # Dict para guardar resultados
    results[nombre_df] = {name: {'RMSE': [], 'R2': []} for name in models}
    skf = StratifiedKFold(n_splits=FOLDS, shuffle=True, random_state=42)

    if model_name == "LBM":
        params = {
            'objective': 'regression',
            'metric': 'rmse',
            'boosting_type': 'gbdt',
            'device': 'cpu',  # usa CPU/GPU
            'verbosity': -1,
            'learning_rate': trial.suggest_categorical('learning_rate', [0.02, 0.03, 0.04, 0.05]),
            'num_leaves': trial.suggest_categorical('num_leaves', [10, 20, 30]),
            'max_depth': trial.suggest_int('max_depth', 5, 8),
            'min_child_samples': trial.suggest_int('min_child_samples', 4, 8),
            'subsample': trial.suggest_float('subsample', 0.6, 0.8),
            'colsample_bytree': trial.suggest_float('colsample_bytree', 0.6, 0.8),
            'n_estimators': trial.suggest_categorical('n_estimators', [750, 1000, 1250]),
            # 'reg_alpha': trial.suggest_float('reg_alpha', 1e-3, 10.0, log=True),
            # 'reg_lambda': trial.suggest_float('reg_lambda', 1e-3, 10.0, log=True),
            'min_split_gain': trial.suggest_categorical('min_split_gain', [0.0, 0.1, 0.2, 0.5, 1.0])
        }

    if model_name == "XGB":
        params = {
            'n_estimators': trial.suggest_categorical('n_estimators', [750, 1000, 1250]),
            'learning_rate': trial.suggest_categorical('learning_rate', [0.01, 0.02, 0.03]),
            'max_depth': trial.suggest_int('max_depth', 5, 8),
            'min_child_weight': trial.suggest_int('min_child_weight', 2, 4),
            'subsample': trial.suggest_float('subsample', 0.6, 0.8),
            'colsample_bytree': trial.suggest_float('colsample_bytree', 0.6, 0.8),
            # 'n_estimators': 1000,
            # 'learning_rate': 0.02,
            # 'max_depth': trial.suggest_int('max_depth', 6, 7),
            # 'min_child_weight': 2,
            # 'subsample': 0.7,
            # 'colsample_bytree': 0.7,
            # 'reg_alpha': trial.suggest_float('reg_alpha', 1e-3, 10.0, log=True),
            # 'reg_lambda': trial.suggest_float('reg_lambda', 1e-3, 10.0, log=True),
            'device': 'cpu',
            'objective': 'reg:squarederror',
            'tree_method': 'hist',
            'enable_categorical': True,
            'eval_metric': 'rmse'
        }
    
    if model_name == "MLP":
        # Así para evitar warning de definir como tuple
        hidden_options = {
            '32': (32,),
            '64': (64,),
            '128': (128,),
            '64_16': (64, 16)
        }
        hidden_layer_sizes = trial.suggest_categorical('hidden_layer_sizes', list(hidden_options.values()))
        params = {
            'hidden_layer_sizes': hidden_layer_sizes,
            #'hidden_layer_sizes': trial.suggest_categorical('hidden_layer_sizes', [(50,), (100,), (100, 50), (128, 64)]),
            'activation': trial.suggest_categorical('activation', ['relu', 'tanh']),
            'solver': trial.suggest_categorical('solver', ['adam', 'sgd']),
            'alpha': trial.suggest_float('alpha', 1e-5, 0.1, log=True),
            'learning_rate': trial.suggest_categorical('learning_rate', ['constant', 'adaptive']),
            'learning_rate_init': trial.suggest_float('learning_rate_init', 1e-4, 1e-2, log=True),
            'max_iter': 200,
            'n_iter_no_change': 25,
            'early_stopping': True,
            'validation_fraction': 0.2,
            'random_state': 42,
            'verbose': False
        }

    if model_name == "SVR":
        params = {
            'kernel': 'rbf',
            'C': trial.suggest_float('C', 0.1, 10.0, log=True),
            'epsilon': trial.suggest_float('epsilon', 0.01, 0.2),
            'gamma': 'scale',
            'shrinking': True,
            'tol': 1e-3,
            'max_iter': -1,
            'verbose': False
        }

    if model_name == "KNN":
        params = {
            'n_neighbors': trial.suggest_int('n_neighbors', 3, 12),
            'weights': 'distance',
            'algorithm': 'auto',
            'leaf_size': trial.suggest_int('leaf_size', 10, 40),
            'p': 2,  # 1 = manhattan, 2 = euclídea
            'metric': 'minkowski',
            'n_jobs': -1
        }

    if model_name == "LR":
        # No sirve de mucho, pero por completitud
        params = {
            'fit_intercept': trial.suggest_categorical('fit_intercept', [True, False]),
            'positive': trial.suggest_categorical('positive', [True, False]),
        }

    if model_name == "RF":
        params = {
            'n_estimators': trial.suggest_categorical('n_estimators', [100, 200, 400]),
            'max_depth': trial.suggest_int('max_depth', 5, 12),
            'min_samples_split': trial.suggest_int('min_samples_split', 2, 8),
            'min_samples_leaf': trial.suggest_int('min_samples_leaf', 2, 8),
            'bootstrap': trial.suggest_categorical('bootstrap', [True, False]),
            'random_state': 42,
            'verbose': 0
        }

    if model_name == "CAT":
        params = {
            'iterations': trial.suggest_categorical('iterations', [500, 750, 1000]),
            'learning_rate': trial.suggest_categorical('learning_rate', [0.02, 0.03, 0.04, 0.05]),
            'depth': trial.suggest_int('depth', 4, 8),
            'l2_leaf_reg': trial.suggest_float('l2_leaf_reg', 1.0, 5.0),
            'loss_function': 'RMSE',
            'eval_metric': 'RMSE',
            'random_seed': 42,
            'early_stopping_rounds': 50,
            'verbose': False
        }

    if model_name == "ELN":
        params = {
            'alpha': trial.suggest_float('alpha', 1e-4, 1.0, log=True),
            'l1_ratio': trial.suggest_float('l1_ratio', 0.1, 0.9),
            'fit_intercept': True,
            'max_iter': 1000,
            'tol': 1e-4,
            'selection': 'cyclic',
            'random_state': 42
        }

    # Cargamos el modelo correspondiente
    model = models[model_name](**params)

    for fold, (train_idx, val_idx) in enumerate(skf.split(X, y_class)):
        print(f"Fold {fold+1}")
        X_train, X_val = X.iloc[train_idx], X.iloc[val_idx]
        y_train, y_val = y.iloc[train_idx], y.iloc[val_idx]

        if model_name in ["MLP", "SVR", "KNN", "LR", "ELN"]:
            scaler_X = RobustScaler()
            scaler_y = RobustScaler()
            X_train_scaled = scaler_X.fit_transform(X_train)
            X_val_scaled = scaler_X.transform(X_val)
            #X_test_scaled = scaler_X.transform(X_test)
            y_train_scaled = scaler_y.fit_transform(y_train.values.reshape(-1, 1)).ravel()
            model.fit(X_train_scaled, y_train_scaled)
            val_pred = scaler_y.inverse_transform(model.predict(X_val_scaled).reshape(-1, 1)).ravel()
            #test_pred = scaler_y.inverse_transform(model.predict(X_test_scaled).reshape(-1, 1)).ravel()

        else:
            model.fit(X_train, y_train)
            val_pred = model.predict(X_val)
            #test_pred = model.predict(X_test)

        if correct:
            val_pred = np.clip(val_pred, 0.2, None)
            #test_pred = np.clip(test_pred, 0.2, None)

        val_preds[model_name][val_idx] = val_pred
        if model_name == list(models.keys())[0]:
            # Solo lo guardamos una vez
            y_vals[fold] = y_val
            val_indices[fold] = val_idx

        rmse = np.sqrt(mean_squared_error(y_val, val_pred))
        r2 = r2_score(y_val, val_pred)
        results[nombre_df][model_name]['RMSE'].append(rmse)
        results[nombre_df][model_name]['R2'].append(r2)
        #test_preds[model_name] += test_pred / FOLDS

    #rmse_test = np.sqrt(mean_squared_error(y_test, test_preds[model_name]))
    r2 = np.mean(results[nombre_df][model_name]["R2"])

    return r2

In [96]:

models = {
    "XGB": XGBRegressor,
    "LBM": LGBMRegressor,
    "MLP": MLPRegressor,
    "SVR": SVR,
    "KNN": KNeighborsRegressor,
    "LR": LinearRegression,
    "RF": RandomForestRegressor,
    "CAT": CatBoostRegressor,
    "ELN":  ElasticNet
}

def run_optuna(df, nombre_df, target, n_trials, model_name):
    results = {}

    print(f"Buscando mejores hiperparámetros para {model_name} con {nombre_df}...")
    study = optuna.create_study(direction='maximize')
    study.optimize(lambda trial: objective(trial, df, nombre_df, target, model_name), n_trials=n_trials, timeout= 1500)
    
    print(f"\n✅ {model_name} con {nombre_df} - Mejor R2: {study.best_value:.2f}")
    print(f"📋 Parámetros: {study.best_params}\n")
    
    results[model_name] = {
        'best_params': study.best_params,
        'best_score': np.round(study.best_value, 3)
    }
    return results

In [102]:


depths = ["in_3_4"]#, "in_1_2", "in_2_3", "in_3_4"]
for depth in depths: 
    # Cargamos los csv de los tifs
    path = "saved_files/dataset"
    dfs = {}
    for archivo in os.listdir(path):
        if archivo.endswith(f"{depth}_features.csv"):
            nombre_sin_extension = os.path.splitext(archivo)[0]  # sin .csv
            ruta_completa = os.path.join(path, archivo)
            dfs[nombre_sin_extension[:-9]] = pd.read_csv(ruta_completa)


    # Limpiamos valores nulos
    for nombre_df, df in dfs.items():
        for band_set in ["rhow", "rhown","rtoa"]:
            dfs[nombre_df] = df.dropna()

    dfs_to_keep = [
		'C2X-Complex_rhow_9x9_depth_in_0_1', 
		'TOA_15x15_depth_in_0_1',
		'C2X-Complex_rhown_9x9_depth_in_0_1',
		'C2X-Complex_rhow_5x5_depth_in_0_1',
		'C2RCC_rhow_5x5_depth_in_0_1',
		'C2RCC_rhow_15x15_depth_in_0_1', 
		'C2X-Complex_rhown_15x15_depth_in_0_1',
		'C2RCC_rhown_5x5_depth_in_0_1', 
		'C2X-Complex_rhow_15x15_depth_in_0_1',
		'C2RCC_rhow_9x9_depth_in_0_1',
		'C2X-Complex_rhow_5x5_depth_in_1_2', 
		'C2X_rhow_3x3_depth_in_1_2',
		'C2X-Complex_rhown_5x5_depth_in_1_2',
		'C2X-Complex_rhow_9x9_depth_in_1_2',
		'C2X-Complex_rhow_3x3_depth_in_1_2',
		'C2X-Complex_rhown_3x3_depth_in_1_2',
		'C2RCC_rhown_3x3_depth_in_1_2',
		'C2X-Complex_rhown_9x9_depth_in_1_2',
		'C2X-Complex_rhow_15x15_depth_in_1_2', 
		'C2X_rhow_5x5_depth_in_1_2',
        'TOA_15x15_depth_in_2_3',
		'TOA_9x9_depth_in_2_3',
		'TOA_5x5_depth_in_2_3', 
		'C2X-Complex_rhow_5x5_depth_in_2_3',
		'C2RCC_rhown_5x5_depth_in_2_3', 
		'TOA_3x3_depth_in_2_3',
		'C2X-Complex_rhown_5x5_depth_in_2_3', 
		'C2RCC_rhow_3x3_depth_in_2_3',
		'C2X-Complex_rhown_9x9_depth_in_2_3', 
		'C2X_rhow_9x9_depth_in_2_3',
        'TOA_9x9_depth_in_3_4',
		'TOA_3x3_depth_in_3_4',
		'TOA_5x5_depth_in_3_4',
		'C2X-Complex_rhow_5x5_depth_in_3_4', 
		'TOA_1x1_depth_in_3_4',
		'TOA_15x15_depth_in_3_4',
		'C2X-Complex_rhown_5x5_depth_in_3_4',
		'C2X-Complex_rhow_9x9_depth_in_3_4',
		'C2X-Complex_rhow_15x15_depth_in_3_4',
		'C2X-Complex_rhown_9x9_depth_in_3_4'
        ]

    dfs = {k: dfs[k] for k in dfs_to_keep if k in dfs}


    for nombre_df, df in dfs.items():
        # Marcamos las columnas de CHl alta (equivalente a quantile(0.93))
        df["High_Chl"] = df["Chl"]>5
        # Sacamos la estación de cada fecha
        df['Date'] = pd.to_datetime(df['Date'])
        def get_season(month):
            if month in [12, 1, 2]:
                return 'Invierno'
            elif month in [3, 4, 5]:
                return 'Primavera'
            elif month in [6, 7, 8]:
                return 'Verano'
            else:
                return 'Otoño'
        df['Season'] = df['Date'].dt.month.apply(get_season)
        for col in df.select_dtypes(include='object').columns:
            df[col] = df[col].astype('category')
        df = pd.concat([df.drop(columns=["Season"]),pd.get_dummies(df["Season"])], axis=1)
        dfs[nombre_df] = df

In [103]:

n_trials = 30
global_results = {}
for nombre_df, df in list(dfs.items()):
    for model_name in models.keys():
        key = (nombre_df, model_name)
        result = run_optuna(df, nombre_df, "Chl", n_trials, model_name)
        global_results[key] = result[model_name]

with open(f"training_results/selection_results_{depth}.pkl", "wb") as f:
    pickle.dump(global_results, f)

[I 2025-09-08 20:26:39,083] A new study created in memory with name: no-name-94dd381f-b854-4af2-bf69-ea4ddfacab52

Buscando mejores hiperparámetros para XGB con TOA_9x9_depth_in_3_4...
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:26:45,818] Trial 0 finished with value: 0.43989581670767525 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 8, 'min_child_weight': 2, 'subsample': 0.6928063449113847, 'colsample_bytree': 0.7829297111031831}. Best is trial 0 with value: 0.43989581670767525.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:26:49,440] Trial 1 finished with value: 0.4080765295845629 and parameters: {'n_estimators': 1000, 'learning_rate': 0.02, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.6680370209331662, 'colsample_bytree': 0.6157861727806752}. Best is trial 0 with value: 0.43989581670767525.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:26:54,422] Trial 2 finished with value: 0.3490016805891292 and parameters: {'n_estimators': 1250, 'learning_rate': 0.03, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.6569271112448599, 'colsample_bytree': 0.7484821866220847}. Best is trial 0 with value: 0.43989581670767525.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:26:57,738] Trial 3 finished with value: 0.41233421498470085 and parameters: {'n_estimators': 750, 'learning_rate': 0.03, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.6420025465839956, 'colsample_bytree': 0.6592190862152684}. Best is trial 0 with value: 0.43989581670767525.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:27:01,068] Trial 4 finished with value: 0.4431033716080677 and parameters: {'n_estimators': 750, 'learning_rate': 0.01, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.7543587602722412, 'colsample_bytree': 0.7001086089588694}. Best is trial 4 with value: 0.4431033716080677.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:27:03,874] Trial 5 finished with value: 0.39728777967657486 and parameters: {'n_estimators': 750, 'learning_rate': 0.03, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.7163345520371088, 'colsample_bytree': 0.7699129398970043}. Best is trial 4 with value: 0.4431033716080677.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:27:09,042] Trial 6 finished with value: 0.4201383969790329 and parameters: {'n_estimators': 1000, 'learning_rate': 0.03, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.7535237380044131, 'colsample_bytree': 0.7540667973773828}. Best is trial 4 with value: 0.4431033716080677.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:27:13,802] Trial 7 finished with value: 0.4080305378217473 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.7420954160133906, 'colsample_bytree': 0.7092633945932797}. Best is trial 4 with value: 0.4431033716080677.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:27:18,961] Trial 8 finished with value: 0.394904766851163 and parameters: {'n_estimators': 1250, 'learning_rate': 0.02, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.7483889316441186, 'colsample_bytree': 0.769796966440573}. Best is trial 4 with value: 0.4431033716080677.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:27:24,856] Trial 9 finished with value: 0.4110065320174801 and parameters: {'n_estimators': 1250, 'learning_rate': 0.01, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.6634253845476381, 'colsample_bytree': 0.7439388840820018}. Best is trial 4 with value: 0.4431033716080677.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:27:29,704] Trial 10 finished with value: 0.4432730869689358 and parameters: {'n_estimators': 750, 'learning_rate': 0.01, 'max_depth': 8, 'min_child_weight': 2, 'subsample': 0.7953652884081289, 'colsample_bytree': 0.6856024137622808}. Best is trial 10 with value: 0.4432730869689358.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:27:34,560] Trial 11 finished with value: 0.4391472619952285 and parameters: {'n_estimators': 750, 'learning_rate': 0.01, 'max_depth': 8, 'min_child_weight': 2, 'subsample': 0.789532616533058, 'colsample_bytree': 0.6806990437396625}. Best is trial 10 with value: 0.4432730869689358.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:27:39,600] Trial 12 finished with value: 0.4364908582650629 and parameters: {'n_estimators': 750, 'learning_rate': 0.01, 'max_depth': 8, 'min_child_weight': 2, 'subsample': 0.7976435800545455, 'colsample_bytree': 0.6973653962842339}. Best is trial 10 with value: 0.4432730869689358.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:27:43,026] Trial 13 finished with value: 0.4500919924166665 and parameters: {'n_estimators': 750, 'learning_rate': 0.01, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.7726313745425268, 'colsample_bytree': 0.6493358021181809}. Best is trial 13 with value: 0.4500919924166665.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:27:46,937] Trial 14 finished with value: 0.46559953429239664 and parameters: {'n_estimators': 750, 'learning_rate': 0.01, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.6087799996015169, 'colsample_bytree': 0.6186468481380722}. Best is trial 14 with value: 0.46559953429239664.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:27:50,927] Trial 15 finished with value: 0.44374573575468973 and parameters: {'n_estimators': 750, 'learning_rate': 0.01, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.6003851274451827, 'colsample_bytree': 0.6054002021778767}. Best is trial 14 with value: 0.46559953429239664.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:27:53,784] Trial 16 finished with value: 0.46027839095448636 and parameters: {'n_estimators': 750, 'learning_rate': 0.02, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.6033213027503617, 'colsample_bytree': 0.6360545636923884}. Best is trial 14 with value: 0.46559953429239664.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:27:56,388] Trial 17 finished with value: 0.4416176252817842 and parameters: {'n_estimators': 750, 'learning_rate': 0.02, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.6000960371033687, 'colsample_bytree': 0.6315473406681389}. Best is trial 14 with value: 0.46559953429239664.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:27:59,139] Trial 18 finished with value: 0.4587949436326076 and parameters: {'n_estimators': 750, 'learning_rate': 0.02, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.6255308043722211, 'colsample_bytree': 0.6370597273120047}. Best is trial 14 with value: 0.46559953429239664.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:28:04,533] Trial 19 finished with value: 0.39781480445096457 and parameters: {'n_estimators': 1250, 'learning_rate': 0.02, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.6222149604150959, 'colsample_bytree': 0.6000342705809742}. Best is trial 14 with value: 0.46559953429239664.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:28:07,210] Trial 20 finished with value: 0.43902977684111955 and parameters: {'n_estimators': 750, 'learning_rate': 0.02, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.6897301831273458, 'colsample_bytree': 0.6604833473672864}. Best is trial 14 with value: 0.46559953429239664.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:28:10,118] Trial 21 finished with value: 0.4599575484121672 and parameters: {'n_estimators': 750, 'learning_rate': 0.02, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.6259984809414786, 'colsample_bytree': 0.6255575889973289}. Best is trial 14 with value: 0.46559953429239664.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:28:12,828] Trial 22 finished with value: 0.45529360648532863 and parameters: {'n_estimators': 750, 'learning_rate': 0.02, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.6200719031266337, 'colsample_bytree': 0.6225468689428649}. Best is trial 14 with value: 0.46559953429239664.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:28:16,089] Trial 23 finished with value: 0.44788719198886956 and parameters: {'n_estimators': 750, 'learning_rate': 0.02, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.6395408898454382, 'colsample_bytree': 0.6445199541771625}. Best is trial 14 with value: 0.46559953429239664.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:28:18,708] Trial 24 finished with value: 0.4578339803457492 and parameters: {'n_estimators': 750, 'learning_rate': 0.02, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.6133594518369538, 'colsample_bytree': 0.6161413249969416}. Best is trial 14 with value: 0.46559953429239664.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:28:21,776] Trial 25 finished with value: 0.42278823620176104 and parameters: {'n_estimators': 750, 'learning_rate': 0.02, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.6390937431590904, 'colsample_bytree': 0.6710696172314765}. Best is trial 14 with value: 0.46559953429239664.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:28:25,618] Trial 26 finished with value: 0.4439659770489736 and parameters: {'n_estimators': 750, 'learning_rate': 0.02, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.6793244622668139, 'colsample_bytree': 0.6293016683234961}. Best is trial 14 with value: 0.46559953429239664.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:28:28,448] Trial 27 finished with value: 0.4280903548262347 and parameters: {'n_estimators': 750, 'learning_rate': 0.02, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.7164825896407202, 'colsample_bytree': 0.7230622300225997}. Best is trial 14 with value: 0.46559953429239664.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:28:32,538] Trial 28 finished with value: 0.42502086632159014 and parameters: {'n_estimators': 1000, 'learning_rate': 0.03, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.649491241603734, 'colsample_bytree': 0.6527330964441982}. Best is trial 14 with value: 0.46559953429239664.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:28:39,651] Trial 29 finished with value: 0.4519136526587609 and parameters: {'n_estimators': 1250, 'learning_rate': 0.02, 'max_depth': 8, 'min_child_weight': 2, 'subsample': 0.6145052810158369, 'colsample_bytree': 0.6087563427986401}. Best is trial 14 with value: 0.46559953429239664.
[I 2025-09-08 20:28:39,653] A new study created in memory with name: no-name-a8d93d20-694a-4e43-afa4-c1b8f4475c36
[I 2025-09-08 20:28:39,755] Trial 0 finished with value: 0.4886283958453996 and parameters: {'learning_rate': 0.05, 'num_leaves': 10, 'max_depth': 5, 'min_child_samples': 4, 'subsample': 0.7522617350306261, 'colsample_bytree': 0.6399666050051604, 'n_estimators': 1000, 'min_split_gain': 1.0}. Best is trial 0 with value: 0.4886283958453996.

✅ XGB con TOA_9x9_depth_in_3_4 - Mejor R2: 0.47
📋 Parámetros: {'n_estimators': 750, 'learning_rate': 0.01, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.6087799996015169, 'colsample_bytree': 0.6186468481380722}

Buscando mejores hiperparámetros para LBM con TOA_9x9_depth_in_3_4...
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:28:39,871] Trial 1 finished with value: 0.4593750828106027 and parameters: {'learning_rate': 0.03, 'num_leaves': 10, 'max_depth': 7, 'min_child_samples': 5, 'subsample': 0.7947137032289542, 'colsample_bytree': 0.7655496632366189, 'n_estimators': 750, 'min_split_gain': 1.0}. Best is trial 0 with value: 0.4886283958453996.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:28:40,080] Trial 2 finished with value: 0.4322633803303795 and parameters: {'learning_rate': 0.03, 'num_leaves': 30, 'max_depth': 7, 'min_child_samples': 5, 'subsample': 0.688686621634429, 'colsample_bytree': 0.620900406446943, 'n_estimators': 750, 'min_split_gain': 0.1}. Best is trial 0 with value: 0.4886283958453996.
[I 2025-09-08 20:28:40,254] Trial 3 finished with value: 0.4502489894514798 and parameters: {'learning_rate': 0.02, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 6, 'subsample': 0.7821353512863591, 'colsample_bytree': 0.7204194404354529, 'n_estimators': 1000, 'min_split_gain': 1.0}. Best is trial 0 with value: 0.4886283958453996.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:28:40,613] Trial 4 finished with value: 0.5418882238757567 and parameters: {'learning_rate': 0.02, 'num_leaves': 20, 'max_depth': 8, 'min_child_samples': 7, 'subsample': 0.6744276219759505, 'colsample_bytree': 0.7353851999565469, 'n_estimators': 1250, 'min_split_gain': 0.1}. Best is trial 4 with value: 0.5418882238757567.
[I 2025-09-08 20:28:40,770] Trial 5 finished with value: 0.43192923171455583 and parameters: {'learning_rate': 0.03, 'num_leaves': 20, 'max_depth': 8, 'min_child_samples': 6, 'subsample': 0.627894449382284, 'colsample_bytree': 0.7597613396887772, 'n_estimators': 750, 'min_split_gain': 0.5}. Best is trial 4 with value: 0.5418882238757567.

Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 20:28:40,936] Trial 6 finished with value: 0.4957855326890412 and parameters: {'learning_rate': 0.02, 'num_leaves': 10, 'max_depth': 7, 'min_child_samples': 8, 'subsample': 0.6142313928620293, 'colsample_bytree': 0.7000581914859466, 'n_estimators': 1000, 'min_split_gain': 1.0}. Best is trial 4 with value: 0.5418882238757567.

Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 20:28:41,094] Trial 7 finished with value: 0.3974640352904486 and parameters: {'learning_rate': 0.04, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 5, 'subsample': 0.6794836218640653, 'colsample_bytree': 0.7431000832848282, 'n_estimators': 750, 'min_split_gain': 0.2}. Best is trial 4 with value: 0.5418882238757567.
[I 2025-09-08 20:28:41,221] Trial 8 finished with value: 0.4956182153554436 and parameters: {'learning_rate': 0.05, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 8, 'subsample': 0.7215064877650174, 'colsample_bytree': 0.7132546923935044, 'n_estimators': 1000, 'min_split_gain': 0.5}. Best is trial 4 with value: 0.5418882238757567.

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 20:28:41,498] Trial 9 finished with value: 0.41254132659027176 and parameters: {'learning_rate': 0.02, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 5, 'subsample': 0.6806078408399078, 'colsample_bytree': 0.7994650642841519, 'n_estimators': 1250, 'min_split_gain': 0.2}. Best is trial 4 with value: 0.5418882238757567.

Fold 2
Fold 3
Fold 1

[I 2025-09-08 20:28:41,730] Trial 10 finished with value: 0.5299984177967505 and parameters: {'learning_rate': 0.04, 'num_leaves': 30, 'max_depth': 8, 'min_child_samples': 7, 'subsample': 0.6486870060331982, 'colsample_bytree': 0.6622286765444343, 'n_estimators': 1250, 'min_split_gain': 0.1}. Best is trial 4 with value: 0.5418882238757567.

Fold 2
Fold 3
Fold 1

[I 2025-09-08 20:28:41,959] Trial 11 finished with value: 0.5299984177967505 and parameters: {'learning_rate': 0.04, 'num_leaves': 30, 'max_depth': 8, 'min_child_samples': 7, 'subsample': 0.6454052686229953, 'colsample_bytree': 0.655827966681786, 'n_estimators': 1250, 'min_split_gain': 0.1}. Best is trial 4 with value: 0.5418882238757567.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:28:42,688] Trial 12 finished with value: 0.517813516046565 and parameters: {'learning_rate': 0.04, 'num_leaves': 30, 'max_depth': 8, 'min_child_samples': 7, 'subsample': 0.6531226603870139, 'colsample_bytree': 0.6774524634749347, 'n_estimators': 1250, 'min_split_gain': 0.0}. Best is trial 4 with value: 0.5418882238757567.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:28:42,920] Trial 13 finished with value: 0.5255134491007439 and parameters: {'learning_rate': 0.04, 'num_leaves': 30, 'max_depth': 8, 'min_child_samples': 7, 'subsample': 0.7196127306660682, 'colsample_bytree': 0.6763920203078363, 'n_estimators': 1250, 'min_split_gain': 0.1}. Best is trial 4 with value: 0.5418882238757567.

Fold 1
Fold 2

[I 2025-09-08 20:28:43,252] Trial 14 finished with value: 0.5467262824332201 and parameters: {'learning_rate': 0.02, 'num_leaves': 30, 'max_depth': 6, 'min_child_samples': 7, 'subsample': 0.601399686306191, 'colsample_bytree': 0.603088411447886, 'n_estimators': 1250, 'min_split_gain': 0.1}. Best is trial 14 with value: 0.5467262824332201.

Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:28:43,590] Trial 15 finished with value: 0.5081502500715033 and parameters: {'learning_rate': 0.02, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 8, 'subsample': 0.6050870891962519, 'colsample_bytree': 0.6001995097487776, 'n_estimators': 1250, 'min_split_gain': 0.1}. Best is trial 14 with value: 0.5467262824332201.

Fold 1
Fold 2

[I 2025-09-08 20:28:44,015] Trial 16 finished with value: 0.4834734405082499 and parameters: {'learning_rate': 0.02, 'num_leaves': 30, 'max_depth': 5, 'min_child_samples': 6, 'subsample': 0.7241778721210103, 'colsample_bytree': 0.7348201765197375, 'n_estimators': 1250, 'min_split_gain': 0.0}. Best is trial 14 with value: 0.5467262824332201.

Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:28:44,362] Trial 17 finished with value: 0.5507638526727415 and parameters: {'learning_rate': 0.02, 'num_leaves': 30, 'max_depth': 6, 'min_child_samples': 7, 'subsample': 0.663853941982004, 'colsample_bytree': 0.7917965480302354, 'n_estimators': 1250, 'min_split_gain': 0.1}. Best is trial 17 with value: 0.5507638526727415.

Fold 1
Fold 2

[I 2025-09-08 20:28:44,705] Trial 18 finished with value: 0.450978154839717 and parameters: {'learning_rate': 0.02, 'num_leaves': 30, 'max_depth': 6, 'min_child_samples': 6, 'subsample': 0.6216751432979382, 'colsample_bytree': 0.7962889117928529, 'n_estimators': 1250, 'min_split_gain': 0.1}. Best is trial 17 with value: 0.5507638526727415.

Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:28:45,056] Trial 19 finished with value: 0.492894123932331 and parameters: {'learning_rate': 0.02, 'num_leaves': 30, 'max_depth': 6, 'min_child_samples': 8, 'subsample': 0.6592104016062418, 'colsample_bytree': 0.7733209631781709, 'n_estimators': 1250, 'min_split_gain': 0.1}. Best is trial 17 with value: 0.5507638526727415.
[I 2025-09-08 20:28:45,198] Trial 20 finished with value: 0.5375386145505948 and parameters: {'learning_rate': 0.05, 'num_leaves': 30, 'max_depth': 5, 'min_child_samples': 7, 'subsample': 0.6003605168106162, 'colsample_bytree': 0.6247840516250643, 'n_estimators': 1250, 'min_split_gain': 0.5}. Best is trial 17 with value: 0.5507638526727415.

Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 20:28:45,534] Trial 21 finished with value: 0.5507638526727415 and parameters: {'learning_rate': 0.02, 'num_leaves': 30, 'max_depth': 6, 'min_child_samples': 7, 'subsample': 0.7037772170895752, 'colsample_bytree': 0.7833644086529988, 'n_estimators': 1250, 'min_split_gain': 0.1}. Best is trial 17 with value: 0.5507638526727415.

Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 20:28:45,879] Trial 22 finished with value: 0.5507638526727415 and parameters: {'learning_rate': 0.02, 'num_leaves': 30, 'max_depth': 6, 'min_child_samples': 7, 'subsample': 0.7032926078337183, 'colsample_bytree': 0.7807955371150377, 'n_estimators': 1250, 'min_split_gain': 0.1}. Best is trial 17 with value: 0.5507638526727415.

Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:28:46,229] Trial 23 finished with value: 0.4457353525744776 and parameters: {'learning_rate': 0.02, 'num_leaves': 30, 'max_depth': 6, 'min_child_samples': 6, 'subsample': 0.70501543375377, 'colsample_bytree': 0.7852035981612434, 'n_estimators': 1250, 'min_split_gain': 0.1}. Best is trial 17 with value: 0.5507638526727415.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:28:46,511] Trial 24 finished with value: 0.5109690742034828 and parameters: {'learning_rate': 0.02, 'num_leaves': 30, 'max_depth': 5, 'min_child_samples': 8, 'subsample': 0.7538016645812293, 'colsample_bytree': 0.7798427806768368, 'n_estimators': 1250, 'min_split_gain': 0.2}. Best is trial 17 with value: 0.5507638526727415.

Fold 1
Fold 2

[I 2025-09-08 20:28:47,027] Trial 25 finished with value: 0.5528257444378237 and parameters: {'learning_rate': 0.02, 'num_leaves': 30, 'max_depth': 6, 'min_child_samples': 7, 'subsample': 0.6994334947062816, 'colsample_bytree': 0.7549046735992467, 'n_estimators': 1250, 'min_split_gain': 0.0}. Best is trial 25 with value: 0.5528257444378237.

Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:28:47,465] Trial 26 finished with value: 0.48164521427901813 and parameters: {'learning_rate': 0.02, 'num_leaves': 10, 'max_depth': 6, 'min_child_samples': 6, 'subsample': 0.7413069386779376, 'colsample_bytree': 0.7541748183176917, 'n_estimators': 1250, 'min_split_gain': 0.0}. Best is trial 25 with value: 0.5528257444378237.

Fold 1
Fold 2

[I 2025-09-08 20:28:47,897] Trial 27 finished with value: 0.5619833158977411 and parameters: {'learning_rate': 0.02, 'num_leaves': 30, 'max_depth': 5, 'min_child_samples': 7, 'subsample': 0.6938791931438405, 'colsample_bytree': 0.7473628521478555, 'n_estimators': 1250, 'min_split_gain': 0.0}. Best is trial 27 with value: 0.5619833158977411.

Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:28:48,252] Trial 28 finished with value: 0.5382938405026256 and parameters: {'learning_rate': 0.05, 'num_leaves': 30, 'max_depth': 5, 'min_child_samples': 8, 'subsample': 0.6669724825564265, 'colsample_bytree': 0.7483943899850338, 'n_estimators': 1000, 'min_split_gain': 0.0}. Best is trial 27 with value: 0.5619833158977411.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:28:48,500] Trial 29 finished with value: 0.4857169477518258 and parameters: {'learning_rate': 0.03, 'num_leaves': 10, 'max_depth': 5, 'min_child_samples': 6, 'subsample': 0.6911614604229387, 'colsample_bytree': 0.7261725845603768, 'n_estimators': 750, 'min_split_gain': 0.0}. Best is trial 27 with value: 0.5619833158977411.
[I 2025-09-08 20:28:48,501] A new study created in memory with name: no-name-4cc30011-9b0a-401c-9e75-a6e0cb6510c6
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

✅ LBM con TOA_9x9_depth_in_3_4 - Mejor R2: 0.56
📋 Parámetros: {'learning_rate': 0.02, 'num_leaves': 30, 'max_depth': 5, 'min_child_samples': 7, 'subsample': 0.6938791931438405, 'colsample_bytree': 0.7473628521478555, 'n_estimators': 1250, 'min_split_gain': 0.0}

Buscando mejores hiperparámetros para MLP con TOA_9x9_depth_in_3_4...
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 20:28:49,070] Trial 0 finished with value: -0.036478553555963265 and parameters: {'hidden_layer_sizes': (64,), 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.0006533789576091106, 'learning_rate': 'constant', 'learning_rate_init': 0.0007078299265022322}. Best is trial 0 with value: -0.036478553555963265.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

[I 2025-09-08 20:28:49,878] Trial 1 finished with value: 0.28109230070379887 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.0024568715821796866, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0025998903026360136}. Best is trial 1 with value: 0.28109230070379887.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 20:28:50,728] Trial 2 finished with value: 0.3454732256211667 and parameters: {'hidden_layer_sizes': (128,), 'activation': 'relu', 'solver': 'adam', 'alpha': 0.00013396082588050672, 'learning_rate': 'constant', 'learning_rate_init': 0.00017438633330576445}. Best is trial 2 with value: 0.3454732256211667.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 20:28:51,334] Trial 3 finished with value: -0.29397562232253405 and parameters: {'hidden_layer_sizes': (64,), 'activation': 'relu', 'solver': 'sgd', 'alpha': 1.158619993591092e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.00010770671428533944}. Best is trial 2 with value: 0.3454732256211667.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 20:28:51,864] Trial 4 finished with value: 0.340824061596547 and parameters: {'hidden_layer_sizes': (128,), 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0002631167789774259, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0008074024461643323}. Best is trial 2 with value: 0.3454732256211667.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2

[I 2025-09-08 20:28:52,201] Trial 5 finished with value: 0.40627057563927343 and parameters: {'hidden_layer_sizes': (32,), 'activation': 'relu', 'solver': 'adam', 'alpha': 2.2754375482164583e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.006628201853439261}. Best is trial 5 with value: 0.40627057563927343.

Fold 3
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 20:28:52,954] Trial 6 finished with value: 0.1257568419037575 and parameters: {'hidden_layer_sizes': (32,), 'activation': 'relu', 'solver': 'adam', 'alpha': 8.125040344018466e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00031025910617667966}. Best is trial 5 with value: 0.40627057563927343.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 20:28:54,203] Trial 7 finished with value: 0.3167288813517396 and parameters: {'hidden_layer_sizes': (128,), 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.0005375122340260077, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0033377805204063034}. Best is trial 5 with value: 0.40627057563927343.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 20:28:55,313] Trial 8 finished with value: 0.23369337812449556 and parameters: {'hidden_layer_sizes': (64,), 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.050414041044206305, 'learning_rate': 'constant', 'learning_rate_init': 0.0005971384870874839}. Best is trial 5 with value: 0.40627057563927343.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

[I 2025-09-08 20:28:56,271] Trial 9 finished with value: 0.4004406860402387 and parameters: {'hidden_layer_sizes': (64,), 'activation': 'tanh', 'solver': 'adam', 'alpha': 2.3709457662889753e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.0004789053268657314}. Best is trial 5 with value: 0.40627057563927343.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

[I 2025-09-08 20:28:56,855] Trial 10 finished with value: 0.5216289223832198 and parameters: {'hidden_layer_sizes': (32,), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.005392120541621005, 'learning_rate': 'constant', 'learning_rate_init': 0.009219036545462151}. Best is trial 10 with value: 0.5216289223832198.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2

[I 2025-09-08 20:28:57,359] Trial 11 finished with value: 0.499781684924546 and parameters: {'hidden_layer_sizes': (32,), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.010323090199839962, 'learning_rate': 'constant', 'learning_rate_init': 0.008873429061675509}. Best is trial 10 with value: 0.5216289223832198.

Fold 3
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 2
Fold 3

[I 2025-09-08 20:28:57,838] Trial 12 finished with value: 0.4999075565631404 and parameters: {'hidden_layer_sizes': (32,), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.009499382430102201, 'learning_rate': 'constant', 'learning_rate_init': 0.008887286099996694}. Best is trial 10 with value: 0.5216289223832198.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

[I 2025-09-08 20:28:58,632] Trial 13 finished with value: 0.47722583097362586 and parameters: {'hidden_layer_sizes': (32,), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0060309504153764504, 'learning_rate': 'constant', 'learning_rate_init': 0.002182958580590323}. Best is trial 10 with value: 0.5216289223832198.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

[I 2025-09-08 20:28:59,223] Trial 14 finished with value: 0.5130544814637009 and parameters: {'hidden_layer_sizes': (32,), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.04827011510311736, 'learning_rate': 'constant', 'learning_rate_init': 0.005024164613602253}. Best is trial 10 with value: 0.5216289223832198.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 20:29:00,124] Trial 15 finished with value: 0.5059698457544713 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.09807788107423718, 'learning_rate': 'constant', 'learning_rate_init': 0.0042729507074225495}. Best is trial 10 with value: 0.5216289223832198.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 20:29:00,958] Trial 16 finished with value: 0.4510157949906735 and parameters: {'hidden_layer_sizes': (32,), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.025525790190460473, 'learning_rate': 'constant', 'learning_rate_init': 0.0013436889509070076}. Best is trial 10 with value: 0.5216289223832198.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

[I 2025-09-08 20:29:01,600] Trial 17 finished with value: 0.5180318415867474 and parameters: {'hidden_layer_sizes': (32,), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.002121165045808423, 'learning_rate': 'constant', 'learning_rate_init': 0.004720943044750175}. Best is trial 10 with value: 0.5216289223832198.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 20:29:02,402] Trial 18 finished with value: 0.45898642981757387 and parameters: {'hidden_layer_sizes': (32,), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0018532553684624572, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0015355964841888507}. Best is trial 10 with value: 0.5216289223832198.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 20:29:03,266] Trial 19 finished with value: 0.5114243778287485 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0025251414865289567, 'learning_rate': 'constant', 'learning_rate_init': 0.004892155290248355}. Best is trial 10 with value: 0.5216289223832198.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 20:29:04,087] Trial 20 finished with value: 0.4695555677399303 and parameters: {'hidden_layer_sizes': (32,), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.005079517360257184, 'learning_rate': 'constant', 'learning_rate_init': 0.001895155000186681}. Best is trial 10 with value: 0.5216289223832198.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

[I 2025-09-08 20:29:04,695] Trial 21 finished with value: 0.5116729157079276 and parameters: {'hidden_layer_sizes': (32,), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.020501237237314826, 'learning_rate': 'constant', 'learning_rate_init': 0.005842419118834692}. Best is trial 10 with value: 0.5216289223832198.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 20:29:05,207] Trial 22 finished with value: 0.5007582896320844 and parameters: {'hidden_layer_sizes': (32,), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.02331613786735208, 'learning_rate': 'constant', 'learning_rate_init': 0.009940925175821739}. Best is trial 10 with value: 0.5216289223832198.

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

[I 2025-09-08 20:29:05,899] Trial 23 finished with value: 0.49983586602116326 and parameters: {'hidden_layer_sizes': (32,), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0014010503015363125, 'learning_rate': 'constant', 'learning_rate_init': 0.003178110382428264}. Best is trial 10 with value: 0.5216289223832198.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

[I 2025-09-08 20:29:06,645] Trial 24 finished with value: 0.508492543089814 and parameters: {'hidden_layer_sizes': (32,), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.06507262394711218, 'learning_rate': 'constant', 'learning_rate_init': 0.004112323147073513}. Best is trial 10 with value: 0.5216289223832198.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

[I 2025-09-08 20:29:07,257] Trial 25 finished with value: 0.5116641186514603 and parameters: {'hidden_layer_sizes': (32,), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.004676348404396646, 'learning_rate': 'constant', 'learning_rate_init': 0.006949137105725636}. Best is trial 10 with value: 0.5216289223832198.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 20:29:08,008] Trial 26 finished with value: 0.23622271690467275 and parameters: {'hidden_layer_sizes': (32,), 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.0008201989673313332, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0012472946462756657}. Best is trial 10 with value: 0.5216289223832198.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 20:29:08,686] Trial 27 finished with value: 0.39753657659873004 and parameters: {'hidden_layer_sizes': (128,), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.013334551205831428, 'learning_rate': 'constant', 'learning_rate_init': 0.005669473673406585}. Best is trial 10 with value: 0.5216289223832198.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

[I 2025-09-08 20:29:09,644] Trial 28 finished with value: 0.5033265132400039 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.00031523418209144263, 'learning_rate': 'constant', 'learning_rate_init': 0.00301429609798761}. Best is trial 10 with value: 0.5216289223832198.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 20:29:10,439] Trial 29 finished with value: 0.38262378032569994 and parameters: {'hidden_layer_sizes': (64,), 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.04761346325307552, 'learning_rate': 'constant', 'learning_rate_init': 0.0040301486256554934}. Best is trial 10 with value: 0.5216289223832198.
[I 2025-09-08 20:29:10,441] A new study created in memory with name: no-name-a199e5e8-f010-41f6-bdb0-0f3fb9829953
[I 2025-09-08 20:29:10,514] Trial 0 finished with value: 0.05539414532317988 and parameters: {'C': 0.2055641635251816, 'epsilon': 0.019644792313282068}. Best is trial 0 with value: 0.05539414532317988.

Fold 3

✅ MLP con TOA_9x9_depth_in_3_4 - Mejor R2: 0.52
📋 Parámetros: {'hidden_layer_sizes': (32,), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.005392120541621005, 'learning_rate': 'constant', 'learning_rate_init': 0.009219036545462151}

Buscando mejores hiperparámetros para SVR con TOA_9x9_depth_in_3_4...
Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 20:29:10,568] Trial 1 finished with value: 0.3144739676233698 and parameters: {'C': 1.4031534351646608, 'epsilon': 0.0992284975638783}. Best is trial 1 with value: 0.3144739676233698.
[I 2025-09-08 20:29:10,622] Trial 2 finished with value: 0.45147120684757763 and parameters: {'C': 4.1803454167908995, 'epsilon': 0.17040530992287964}. Best is trial 2 with value: 0.45147120684757763.
[I 2025-09-08 20:29:10,672] Trial 3 finished with value: 0.13024732490350233 and parameters: {'C': 0.3645551083353404, 'epsilon': 0.138117134843161}. Best is trial 2 with value: 0.45147120684757763.
[I 2025-09-08 20:29:10,728] Trial 4 finished with value: 0.4458368777340858 and parameters: {'C': 4.341747471195374, 'epsilon': 0.07425459572126693}. Best is trial 2 with value: 0.45147120684757763.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 20:29:10,783] Trial 5 finished with value: 0.18923731940357066 and parameters: {'C': 0.6508863125976341, 'epsilon': 0.039099770165193885}. Best is trial 2 with value: 0.45147120684757763.
[I 2025-09-08 20:29:10,838] Trial 6 finished with value: 0.43892903365887603 and parameters: {'C': 3.7765540527090797, 'epsilon': 0.1599835805090071}. Best is trial 2 with value: 0.45147120684757763.
[I 2025-09-08 20:29:10,890] Trial 7 finished with value: 0.5224639400485732 and parameters: {'C': 7.671578478099503, 'epsilon': 0.1344526599734623}. Best is trial 7 with value: 0.5224639400485732.
[I 2025-09-08 20:29:10,941] Trial 8 finished with value: 0.08672889979449594 and parameters: {'C': 0.24399211290275022, 'epsilon': 0.11875304715684859}. Best is trial 7 with value: 0.5224639400485732.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 20:29:10,992] Trial 9 finished with value: 0.20244072644317812 and parameters: {'C': 0.6981016832353923, 'epsilon': 0.05266601069772992}. Best is trial 7 with value: 0.5224639400485732.
[I 2025-09-08 20:29:11,050] Trial 10 finished with value: 0.35297052952500035 and parameters: {'C': 1.8439589518540584, 'epsilon': 0.19380601213412546}. Best is trial 7 with value: 0.5224639400485732.
[I 2025-09-08 20:29:11,106] Trial 11 finished with value: 0.5318729870111357 and parameters: {'C': 8.86723689597209, 'epsilon': 0.17279127636842656}. Best is trial 11 with value: 0.5318729870111357.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:29:11,164] Trial 12 finished with value: 0.5186800058057205 and parameters: {'C': 7.860425712365531, 'epsilon': 0.19355338302948039}. Best is trial 11 with value: 0.5318729870111357.
[I 2025-09-08 20:29:11,223] Trial 13 finished with value: 0.5308037733108871 and parameters: {'C': 8.396665294782004, 'epsilon': 0.14792666053314524}. Best is trial 11 with value: 0.5318729870111357.
[I 2025-09-08 20:29:11,281] Trial 14 finished with value: 0.5372485998125087 and parameters: {'C': 9.319300846067396, 'epsilon': 0.16125433566343228}. Best is trial 14 with value: 0.5372485998125087.
[I 2025-09-08 20:29:11,338] Trial 15 finished with value: 0.39985856417407706 and parameters: {'C': 2.4892674939755524, 'epsilon': 0.17514925393306982}. Best is trial 14 with value: 0.5372485998125087.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 20:29:11,400] Trial 16 finished with value: 0.5367272031936547 and parameters: {'C': 9.614665442210974, 'epsilon': 0.10139149083093245}. Best is trial 14 with value: 0.5372485998125087.
[I 2025-09-08 20:29:11,461] Trial 17 finished with value: 0.4140475647851143 and parameters: {'C': 3.0366462640699936, 'epsilon': 0.09737402158950476}. Best is trial 14 with value: 0.5372485998125087.
[I 2025-09-08 20:29:11,524] Trial 18 finished with value: 0.47741260981492517 and parameters: {'C': 5.5857219179766275, 'epsilon': 0.07256143826936692}. Best is trial 14 with value: 0.5372485998125087.
[I 2025-09-08 20:29:11,581] Trial 19 finished with value: 0.29735689804669474 and parameters: {'C': 1.2441835380879194, 'epsilon': 0.11928027120663245}. Best is trial 14 with value: 0.5372485998125087.

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:29:11,639] Trial 20 finished with value: -0.0005733208757995693 and parameters: {'C': 0.12156900861576396, 'epsilon': 0.0798131820687358}. Best is trial 14 with value: 0.5372485998125087.
[I 2025-09-08 20:29:11,699] Trial 21 finished with value: 0.5385789442837989 and parameters: {'C': 9.96334681405889, 'epsilon': 0.17660925574481576}. Best is trial 21 with value: 0.5385789442837989.
[I 2025-09-08 20:29:11,758] Trial 22 finished with value: 0.4861653960708224 and parameters: {'C': 5.557420524975388, 'epsilon': 0.19996001310420333}. Best is trial 21 with value: 0.5385789442837989.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 20:29:11,822] Trial 23 finished with value: 0.5395753961698574 and parameters: {'C': 9.542438571239611, 'epsilon': 0.12262113543912687}. Best is trial 23 with value: 0.5395753961698574.
[I 2025-09-08 20:29:11,879] Trial 24 finished with value: 0.49243036067223517 and parameters: {'C': 5.770665621303706, 'epsilon': 0.15287099138820223}. Best is trial 23 with value: 0.5395753961698574.
[I 2025-09-08 20:29:11,938] Trial 25 finished with value: 0.38151533143454186 and parameters: {'C': 2.18617468383648, 'epsilon': 0.12383215388460073}. Best is trial 23 with value: 0.5395753961698574.
[I 2025-09-08 20:29:11,996] Trial 26 finished with value: 0.4959414490876661 and parameters: {'C': 6.196478007251739, 'epsilon': 0.1828259866374163}. Best is trial 23 with value: 0.5395753961698574.

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:29:12,056] Trial 27 finished with value: 0.4265081100809916 and parameters: {'C': 3.3183241121033524, 'epsilon': 0.15764456326955825}. Best is trial 23 with value: 0.5395753961698574.
[I 2025-09-08 20:29:12,115] Trial 28 finished with value: 0.46409155336933994 and parameters: {'C': 4.622610878681966, 'epsilon': 0.13996095313885065}. Best is trial 23 with value: 0.5395753961698574.
[I 2025-09-08 20:29:12,174] Trial 29 finished with value: 0.2158556182938389 and parameters: {'C': 0.8059403603938462, 'epsilon': 0.02061433236103541}. Best is trial 23 with value: 0.5395753961698574.
[I 2025-09-08 20:29:12,175] A new study created in memory with name: no-name-75497829-c76b-4be4-801b-402a4941665b

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

✅ SVR con TOA_9x9_depth_in_3_4 - Mejor R2: 0.54
📋 Parámetros: {'C': 9.542438571239611, 'epsilon': 0.12262113543912687}

Buscando mejores hiperparámetros para KNN con TOA_9x9_depth_in_3_4...
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:29:12,220] Trial 0 finished with value: 0.5061286767761044 and parameters: {'n_neighbors': 3, 'leaf_size': 22}. Best is trial 0 with value: 0.5061286767761044.
[I 2025-09-08 20:29:12,265] Trial 1 finished with value: 0.5302919301318615 and parameters: {'n_neighbors': 4, 'leaf_size': 20}. Best is trial 1 with value: 0.5302919301318615.
[I 2025-09-08 20:29:12,311] Trial 2 finished with value: 0.5028328459882289 and parameters: {'n_neighbors': 6, 'leaf_size': 30}. Best is trial 1 with value: 0.5302919301318615.
[I 2025-09-08 20:29:12,356] Trial 3 finished with value: 0.442312380584096 and parameters: {'n_neighbors': 10, 'leaf_size': 20}. Best is trial 1 with value: 0.5302919301318615.
[I 2025-09-08 20:29:12,398] Trial 4 finished with value: 0.4680585301366782 and parameters: {'n_neighbors': 8, 'leaf_size': 22}. Best is trial 1 with value: 0.5302919301318615.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 20:29:12,447] Trial 5 finished with value: 0.442312380584096 and parameters: {'n_neighbors': 10, 'leaf_size': 29}. Best is trial 1 with value: 0.5302919301318615.
[I 2025-09-08 20:29:12,490] Trial 6 finished with value: 0.5193125112732361 and parameters: {'n_neighbors': 5, 'leaf_size': 38}. Best is trial 1 with value: 0.5302919301318615.
[I 2025-09-08 20:29:12,535] Trial 7 finished with value: 0.4158322730085599 and parameters: {'n_neighbors': 12, 'leaf_size': 24}. Best is trial 1 with value: 0.5302919301318615.
[I 2025-09-08 20:29:12,579] Trial 8 finished with value: 0.442312380584096 and parameters: {'n_neighbors': 10, 'leaf_size': 24}. Best is trial 1 with value: 0.5302919301318615.
[I 2025-09-08 20:29:12,623] Trial 9 finished with value: 0.5302919301318615 and parameters: {'n_neighbors': 4, 'leaf_size': 33}. Best is trial 1 with value: 0.5302919301318615.

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:29:12,678] Trial 10 finished with value: 0.48748101692037205 and parameters: {'n_neighbors': 7, 'leaf_size': 13}. Best is trial 1 with value: 0.5302919301318615.
[I 2025-09-08 20:29:12,732] Trial 11 finished with value: 0.5061286767761044 and parameters: {'n_neighbors': 3, 'leaf_size': 38}. Best is trial 1 with value: 0.5302919301318615.
[I 2025-09-08 20:29:12,784] Trial 12 finished with value: 0.5302919301318615 and parameters: {'n_neighbors': 4, 'leaf_size': 15}. Best is trial 1 with value: 0.5302919301318615.
[I 2025-09-08 20:29:12,835] Trial 13 finished with value: 0.5193125112732361 and parameters: {'n_neighbors': 5, 'leaf_size': 33}. Best is trial 1 with value: 0.5302919301318615.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:29:12,888] Trial 14 finished with value: 0.5193125112732361 and parameters: {'n_neighbors': 5, 'leaf_size': 17}. Best is trial 1 with value: 0.5302919301318615.
[I 2025-09-08 20:29:12,943] Trial 15 finished with value: 0.48748101692037205 and parameters: {'n_neighbors': 7, 'leaf_size': 29}. Best is trial 1 with value: 0.5302919301318615.
[I 2025-09-08 20:29:12,992] Trial 16 finished with value: 0.5061286767761044 and parameters: {'n_neighbors': 3, 'leaf_size': 10}. Best is trial 1 with value: 0.5302919301318615.
[I 2025-09-08 20:29:13,044] Trial 17 finished with value: 0.5302919301318615 and parameters: {'n_neighbors': 4, 'leaf_size': 34}. Best is trial 1 with value: 0.5302919301318615.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:29:13,100] Trial 18 finished with value: 0.4680585301366782 and parameters: {'n_neighbors': 8, 'leaf_size': 34}. Best is trial 1 with value: 0.5302919301318615.
[I 2025-09-08 20:29:13,153] Trial 19 finished with value: 0.5028328459882289 and parameters: {'n_neighbors': 6, 'leaf_size': 18}. Best is trial 1 with value: 0.5302919301318615.
[I 2025-09-08 20:29:13,204] Trial 20 finished with value: 0.5302919301318615 and parameters: {'n_neighbors': 4, 'leaf_size': 27}. Best is trial 1 with value: 0.5302919301318615.
[I 2025-09-08 20:29:13,257] Trial 21 finished with value: 0.5302919301318615 and parameters: {'n_neighbors': 4, 'leaf_size': 13}. Best is trial 1 with value: 0.5302919301318615.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:29:13,310] Trial 22 finished with value: 0.5028328459882289 and parameters: {'n_neighbors': 6, 'leaf_size': 16}. Best is trial 1 with value: 0.5302919301318615.
[I 2025-09-08 20:29:13,366] Trial 23 finished with value: 0.5302919301318615 and parameters: {'n_neighbors': 4, 'leaf_size': 15}. Best is trial 1 with value: 0.5302919301318615.
[I 2025-09-08 20:29:13,420] Trial 24 finished with value: 0.5193125112732361 and parameters: {'n_neighbors': 5, 'leaf_size': 21}. Best is trial 1 with value: 0.5302919301318615.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:29:13,473] Trial 25 finished with value: 0.5061286767761044 and parameters: {'n_neighbors': 3, 'leaf_size': 10}. Best is trial 1 with value: 0.5302919301318615.
[I 2025-09-08 20:29:13,528] Trial 26 finished with value: 0.5302919301318615 and parameters: {'n_neighbors': 4, 'leaf_size': 19}. Best is trial 1 with value: 0.5302919301318615.
[I 2025-09-08 20:29:13,582] Trial 27 finished with value: 0.5028328459882289 and parameters: {'n_neighbors': 6, 'leaf_size': 26}. Best is trial 1 with value: 0.5302919301318615.
[I 2025-09-08 20:29:13,639] Trial 28 finished with value: 0.4552059373202864 and parameters: {'n_neighbors': 9, 'leaf_size': 14}. Best is trial 1 with value: 0.5302919301318615.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:29:13,692] Trial 29 finished with value: 0.5061286767761044 and parameters: {'n_neighbors': 3, 'leaf_size': 22}. Best is trial 1 with value: 0.5302919301318615.
[I 2025-09-08 20:29:13,693] A new study created in memory with name: no-name-da29d822-f55a-4a83-b086-bb128b92bd81
[I 2025-09-08 20:29:13,756] Trial 0 finished with value: 0.116689431027775 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: 0.116689431027775.
[I 2025-09-08 20:29:13,808] Trial 1 finished with value: 0.116689431027775 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: 0.116689431027775.
[I 2025-09-08 20:29:13,864] Trial 2 finished with value: 0.36667076421971556 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 2 with value: 0.36667076421971556.

✅ KNN con TOA_9x9_depth_in_3_4 - Mejor R2: 0.53
📋 Parámetros: {'n_neighbors': 4, 'leaf_size': 20}

Buscando mejores hiperparámetros para LR con TOA_9x9_depth_in_3_4...
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 20:29:13,934] Trial 3 finished with value: 0.36667076421971556 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 2 with value: 0.36667076421971556.
[I 2025-09-08 20:29:13,999] Trial 4 finished with value: 0.36667076421971556 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 2 with value: 0.36667076421971556.
[I 2025-09-08 20:29:14,058] Trial 5 finished with value: 0.36667076421971556 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 2 with value: 0.36667076421971556.

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:29:14,117] Trial 6 finished with value: 0.116689431027775 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 2 with value: 0.36667076421971556.
[I 2025-09-08 20:29:14,161] Trial 7 finished with value: 0.11668943102777178 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 2 with value: 0.36667076421971556.
[I 2025-09-08 20:29:14,215] Trial 8 finished with value: 0.36667076421971556 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 2 with value: 0.36667076421971556.
[I 2025-09-08 20:29:14,277] Trial 9 finished with value: 0.36667076421991673 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 9 with value: 0.36667076421991673.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:29:14,335] Trial 10 finished with value: 0.36667076421991673 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 9 with value: 0.36667076421991673.
[I 2025-09-08 20:29:14,399] Trial 11 finished with value: 0.36667076421991673 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 9 with value: 0.36667076421991673.
[I 2025-09-08 20:29:14,459] Trial 12 finished with value: 0.36667076421991673 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 9 with value: 0.36667076421991673.
[I 2025-09-08 20:29:14,519] Trial 13 finished with value: 0.36667076421991673 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 9 with value: 0.36667076421991673.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 20:29:14,590] Trial 14 finished with value: 0.36667076421991673 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 9 with value: 0.36667076421991673.
[I 2025-09-08 20:29:14,669] Trial 15 finished with value: 0.36667076421991673 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 9 with value: 0.36667076421991673.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:29:14,749] Trial 16 finished with value: 0.36667076421991673 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 9 with value: 0.36667076421991673.
[I 2025-09-08 20:29:14,829] Trial 17 finished with value: 0.36667076421991673 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 9 with value: 0.36667076421991673.
[I 2025-09-08 20:29:14,902] Trial 18 finished with value: 0.11668943102777178 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 9 with value: 0.36667076421991673.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:29:14,962] Trial 19 finished with value: 0.36667076421991673 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 9 with value: 0.36667076421991673.
[I 2025-09-08 20:29:15,035] Trial 20 finished with value: 0.36667076421991673 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 9 with value: 0.36667076421991673.
[I 2025-09-08 20:29:15,098] Trial 21 finished with value: 0.36667076421991673 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 9 with value: 0.36667076421991673.
[I 2025-09-08 20:29:15,164] Trial 22 finished with value: 0.36667076421991673 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 9 with value: 0.36667076421991673.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:29:15,224] Trial 23 finished with value: 0.36667076421991673 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 9 with value: 0.36667076421991673.
[I 2025-09-08 20:29:15,291] Trial 24 finished with value: 0.36667076421991673 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 9 with value: 0.36667076421991673.
[I 2025-09-08 20:29:15,352] Trial 25 finished with value: 0.36667076421991673 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 9 with value: 0.36667076421991673.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 20:29:15,412] Trial 26 finished with value: 0.11668943102777178 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 9 with value: 0.36667076421991673.
[I 2025-09-08 20:29:15,463] Trial 27 finished with value: 0.36667076421991673 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 9 with value: 0.36667076421991673.
[I 2025-09-08 20:29:15,526] Trial 28 finished with value: 0.36667076421991673 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 9 with value: 0.36667076421991673.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:29:15,595] Trial 29 finished with value: 0.11668943102777178 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 9 with value: 0.36667076421991673.
[I 2025-09-08 20:29:15,598] A new study created in memory with name: no-name-3cc63219-08f3-4321-9b67-aa95a87c08a7

✅ LR con TOA_9x9_depth_in_3_4 - Mejor R2: 0.37
📋 Parámetros: {'fit_intercept': False, 'positive': False}

Buscando mejores hiperparámetros para RF con TOA_9x9_depth_in_3_4...
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:29:17,676] Trial 0 finished with value: 0.0936036972662128 and parameters: {'n_estimators': 100, 'max_depth': 12, 'min_samples_split': 5, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 0 with value: 0.0936036972662128.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:29:18,529] Trial 1 finished with value: 0.31057519390129845 and parameters: {'n_estimators': 100, 'max_depth': 12, 'min_samples_split': 6, 'min_samples_leaf': 8, 'bootstrap': True}. Best is trial 1 with value: 0.31057519390129845.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:29:20,868] Trial 2 finished with value: 0.24434024665651025 and parameters: {'n_estimators': 200, 'max_depth': 5, 'min_samples_split': 2, 'min_samples_leaf': 6, 'bootstrap': False}. Best is trial 1 with value: 0.31057519390129845.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:29:24,342] Trial 3 finished with value: 0.3271554770749832 and parameters: {'n_estimators': 400, 'max_depth': 7, 'min_samples_split': 5, 'min_samples_leaf': 7, 'bootstrap': True}. Best is trial 3 with value: 0.3271554770749832.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:29:27,501] Trial 4 finished with value: 0.20914770860656814 and parameters: {'n_estimators': 200, 'max_depth': 8, 'min_samples_split': 8, 'min_samples_leaf': 5, 'bootstrap': False}. Best is trial 3 with value: 0.3271554770749832.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:29:34,080] Trial 5 finished with value: 0.28440061251577015 and parameters: {'n_estimators': 400, 'max_depth': 11, 'min_samples_split': 8, 'min_samples_leaf': 6, 'bootstrap': False}. Best is trial 3 with value: 0.3271554770749832.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:29:36,468] Trial 6 finished with value: 0.40472911042476484 and parameters: {'n_estimators': 200, 'max_depth': 9, 'min_samples_split': 6, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 6 with value: 0.40472911042476484.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:29:38,640] Trial 7 finished with value: 0.38316071264476115 and parameters: {'n_estimators': 200, 'max_depth': 10, 'min_samples_split': 6, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 6 with value: 0.40472911042476484.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:29:42,460] Trial 8 finished with value: 0.360675379456124 and parameters: {'n_estimators': 400, 'max_depth': 7, 'min_samples_split': 7, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 6 with value: 0.40472911042476484.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:29:46,988] Trial 9 finished with value: 0.22800267403763622 and parameters: {'n_estimators': 400, 'max_depth': 5, 'min_samples_split': 3, 'min_samples_leaf': 7, 'bootstrap': False}. Best is trial 6 with value: 0.40472911042476484.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:29:49,430] Trial 10 finished with value: 0.40971682027490247 and parameters: {'n_estimators': 200, 'max_depth': 9, 'min_samples_split': 4, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 10 with value: 0.40971682027490247.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:29:51,991] Trial 11 finished with value: 0.40971682027490247 and parameters: {'n_estimators': 200, 'max_depth': 9, 'min_samples_split': 4, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 10 with value: 0.40971682027490247.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:29:54,308] Trial 12 finished with value: 0.39874267618261544 and parameters: {'n_estimators': 200, 'max_depth': 9, 'min_samples_split': 4, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 10 with value: 0.40971682027490247.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:29:56,745] Trial 13 finished with value: 0.4005177693115957 and parameters: {'n_estimators': 200, 'max_depth': 10, 'min_samples_split': 3, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 10 with value: 0.40971682027490247.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:29:58,939] Trial 14 finished with value: 0.39655509251901483 and parameters: {'n_estimators': 200, 'max_depth': 8, 'min_samples_split': 4, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 10 with value: 0.40971682027490247.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:30:01,520] Trial 15 finished with value: 0.4135903512088536 and parameters: {'n_estimators': 200, 'max_depth': 10, 'min_samples_split': 4, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 15 with value: 0.4135903512088536.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:30:02,671] Trial 16 finished with value: 0.3855245968273506 and parameters: {'n_estimators': 100, 'max_depth': 10, 'min_samples_split': 2, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 15 with value: 0.4135903512088536.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:30:04,942] Trial 17 finished with value: 0.38337052048481945 and parameters: {'n_estimators': 200, 'max_depth': 11, 'min_samples_split': 3, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 15 with value: 0.4135903512088536.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:30:07,172] Trial 18 finished with value: 0.4002486355427238 and parameters: {'n_estimators': 200, 'max_depth': 7, 'min_samples_split': 5, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 15 with value: 0.4135903512088536.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:30:08,422] Trial 19 finished with value: 0.3983790652239132 and parameters: {'n_estimators': 100, 'max_depth': 11, 'min_samples_split': 4, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 15 with value: 0.4135903512088536.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:30:10,600] Trial 20 finished with value: 0.38234166713144474 and parameters: {'n_estimators': 200, 'max_depth': 8, 'min_samples_split': 3, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 15 with value: 0.4135903512088536.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:30:13,179] Trial 21 finished with value: 0.40971682027490247 and parameters: {'n_estimators': 200, 'max_depth': 9, 'min_samples_split': 4, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 15 with value: 0.4135903512088536.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:30:15,823] Trial 22 finished with value: 0.4135903512088536 and parameters: {'n_estimators': 200, 'max_depth': 10, 'min_samples_split': 4, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 15 with value: 0.4135903512088536.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:30:18,171] Trial 23 finished with value: 0.4005177693115957 and parameters: {'n_estimators': 200, 'max_depth': 10, 'min_samples_split': 5, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 15 with value: 0.4135903512088536.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:30:20,756] Trial 24 finished with value: 0.41206097168267247 and parameters: {'n_estimators': 200, 'max_depth': 11, 'min_samples_split': 3, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 15 with value: 0.4135903512088536.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:30:23,129] Trial 25 finished with value: 0.4002026503718185 and parameters: {'n_estimators': 200, 'max_depth': 11, 'min_samples_split': 2, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 15 with value: 0.4135903512088536.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:30:27,302] Trial 26 finished with value: 0.10502326131045192 and parameters: {'n_estimators': 200, 'max_depth': 12, 'min_samples_split': 3, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 15 with value: 0.4135903512088536.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:30:29,686] Trial 27 finished with value: 0.4002026503718185 and parameters: {'n_estimators': 200, 'max_depth': 11, 'min_samples_split': 3, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 15 with value: 0.4135903512088536.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:30:34,705] Trial 28 finished with value: 0.40935516179139847 and parameters: {'n_estimators': 400, 'max_depth': 10, 'min_samples_split': 2, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 15 with value: 0.4135903512088536.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:30:36,784] Trial 29 finished with value: 0.0936036972662128 and parameters: {'n_estimators': 100, 'max_depth': 12, 'min_samples_split': 5, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 15 with value: 0.4135903512088536.
[I 2025-09-08 20:30:36,786] A new study created in memory with name: no-name-39d7f47a-f207-425a-83c0-a839044f198a

✅ RF con TOA_9x9_depth_in_3_4 - Mejor R2: 0.41
📋 Parámetros: {'n_estimators': 200, 'max_depth': 10, 'min_samples_split': 4, 'min_samples_leaf': 2, 'bootstrap': True}

Buscando mejores hiperparámetros para CAT con TOA_9x9_depth_in_3_4...
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:30:41,494] Trial 0 finished with value: 0.5584946482299221 and parameters: {'iterations': 1000, 'learning_rate': 0.05, 'depth': 6, 'l2_leaf_reg': 1.9714040222133362}. Best is trial 0 with value: 0.5584946482299221.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:30:54,182] Trial 1 finished with value: 0.5652153444114726 and parameters: {'iterations': 500, 'learning_rate': 0.04, 'depth': 8, 'l2_leaf_reg': 2.537570075127598}. Best is trial 1 with value: 0.5652153444114726.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:31:06,823] Trial 2 finished with value: 0.5410163058208346 and parameters: {'iterations': 500, 'learning_rate': 0.05, 'depth': 8, 'l2_leaf_reg': 2.766262874590044}. Best is trial 1 with value: 0.5652153444114726.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:31:19,457] Trial 3 finished with value: 0.5450973435728605 and parameters: {'iterations': 500, 'learning_rate': 0.04, 'depth': 8, 'l2_leaf_reg': 1.9385436367109667}. Best is trial 1 with value: 0.5652153444114726.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:31:21,834] Trial 4 finished with value: 0.5170584452256918 and parameters: {'iterations': 500, 'learning_rate': 0.04, 'depth': 6, 'l2_leaf_reg': 4.021078968633033}. Best is trial 1 with value: 0.5652153444114726.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:31:29,457] Trial 5 finished with value: 0.5459289218408089 and parameters: {'iterations': 750, 'learning_rate': 0.05, 'depth': 7, 'l2_leaf_reg': 2.69171254527874}. Best is trial 1 with value: 0.5652153444114726.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:31:30,488] Trial 6 finished with value: 0.49475639065438887 and parameters: {'iterations': 500, 'learning_rate': 0.05, 'depth': 4, 'l2_leaf_reg': 2.3351086265779424}. Best is trial 1 with value: 0.5652153444114726.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:31:32,502] Trial 7 finished with value: 0.4965909049613639 and parameters: {'iterations': 1000, 'learning_rate': 0.05, 'depth': 4, 'l2_leaf_reg': 2.9275316670433975}. Best is trial 1 with value: 0.5652153444114726.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:31:37,605] Trial 8 finished with value: 0.5428993647340203 and parameters: {'iterations': 500, 'learning_rate': 0.03, 'depth': 7, 'l2_leaf_reg': 2.412750577878168}. Best is trial 1 with value: 0.5652153444114726.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:31:40,981] Trial 9 finished with value: 0.5160181578345965 and parameters: {'iterations': 750, 'learning_rate': 0.03, 'depth': 6, 'l2_leaf_reg': 4.5872979874494995}. Best is trial 1 with value: 0.5652153444114726.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:31:43,316] Trial 10 finished with value: 0.5316863065202416 and parameters: {'iterations': 750, 'learning_rate': 0.02, 'depth': 5, 'l2_leaf_reg': 1.0687698940237573}. Best is trial 1 with value: 0.5652153444114726.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:31:53,562] Trial 11 finished with value: 0.5409420460080426 and parameters: {'iterations': 1000, 'learning_rate': 0.04, 'depth': 7, 'l2_leaf_reg': 3.7962880549067}. Best is trial 1 with value: 0.5652153444114726.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:31:56,596] Trial 12 finished with value: 0.5382676500277714 and parameters: {'iterations': 1000, 'learning_rate': 0.02, 'depth': 5, 'l2_leaf_reg': 1.5215844843588968}. Best is trial 1 with value: 0.5652153444114726.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:31:59,532] Trial 13 finished with value: 0.5301640046987965 and parameters: {'iterations': 1000, 'learning_rate': 0.04, 'depth': 5, 'l2_leaf_reg': 3.37400600150018}. Best is trial 1 with value: 0.5652153444114726.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:32:09,478] Trial 14 finished with value: 0.5519288229982812 and parameters: {'iterations': 1000, 'learning_rate': 0.05, 'depth': 7, 'l2_leaf_reg': 1.819303139416122}. Best is trial 1 with value: 0.5652153444114726.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:32:22,157] Trial 15 finished with value: 0.5348343033971098 and parameters: {'iterations': 500, 'learning_rate': 0.04, 'depth': 8, 'l2_leaf_reg': 1.2700029423656471}. Best is trial 1 with value: 0.5652153444114726.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:32:26,698] Trial 16 finished with value: 0.5616253870115605 and parameters: {'iterations': 1000, 'learning_rate': 0.03, 'depth': 6, 'l2_leaf_reg': 2.017813207362977}. Best is trial 1 with value: 0.5652153444114726.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:32:29,787] Trial 17 finished with value: 0.521241845526608 and parameters: {'iterations': 1000, 'learning_rate': 0.03, 'depth': 5, 'l2_leaf_reg': 3.3859198222854543}. Best is trial 1 with value: 0.5652153444114726.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:32:34,808] Trial 18 finished with value: 0.5417981016765706 and parameters: {'iterations': 500, 'learning_rate': 0.03, 'depth': 7, 'l2_leaf_reg': 2.2973610183620696}. Best is trial 1 with value: 0.5652153444114726.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:32:38,391] Trial 19 finished with value: 0.5347655261484849 and parameters: {'iterations': 750, 'learning_rate': 0.03, 'depth': 6, 'l2_leaf_reg': 3.286298064512991}. Best is trial 1 with value: 0.5652153444114726.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:33:03,645] Trial 20 finished with value: 0.5576995837341855 and parameters: {'iterations': 1000, 'learning_rate': 0.02, 'depth': 8, 'l2_leaf_reg': 1.6295533873669976}. Best is trial 1 with value: 0.5652153444114726.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:33:08,347] Trial 21 finished with value: 0.5435684755143125 and parameters: {'iterations': 1000, 'learning_rate': 0.03, 'depth': 6, 'l2_leaf_reg': 2.056359534558503}. Best is trial 1 with value: 0.5652153444114726.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:33:12,925] Trial 22 finished with value: 0.5354217085426605 and parameters: {'iterations': 1000, 'learning_rate': 0.04, 'depth': 6, 'l2_leaf_reg': 2.487347889786546}. Best is trial 1 with value: 0.5652153444114726.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:33:17,667] Trial 23 finished with value: 0.550020676729809 and parameters: {'iterations': 1000, 'learning_rate': 0.05, 'depth': 6, 'l2_leaf_reg': 2.0561587703668986}. Best is trial 1 with value: 0.5652153444114726.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:33:20,836] Trial 24 finished with value: 0.5411856408376096 and parameters: {'iterations': 1000, 'learning_rate': 0.03, 'depth': 5, 'l2_leaf_reg': 1.4078363168704473}. Best is trial 1 with value: 0.5652153444114726.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:33:25,919] Trial 25 finished with value: 0.5554697261071985 and parameters: {'iterations': 500, 'learning_rate': 0.05, 'depth': 7, 'l2_leaf_reg': 3.0563451091636593}. Best is trial 1 with value: 0.5652153444114726.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:33:30,555] Trial 26 finished with value: 0.544582917391208 and parameters: {'iterations': 1000, 'learning_rate': 0.04, 'depth': 6, 'l2_leaf_reg': 1.7707313058375092}. Best is trial 1 with value: 0.5652153444114726.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:33:40,596] Trial 27 finished with value: 0.5525884667130686 and parameters: {'iterations': 1000, 'learning_rate': 0.02, 'depth': 7, 'l2_leaf_reg': 2.1560380106952497}. Best is trial 1 with value: 0.5652153444114726.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:33:42,766] Trial 28 finished with value: 0.5380525450293746 and parameters: {'iterations': 750, 'learning_rate': 0.05, 'depth': 5, 'l2_leaf_reg': 2.6222523250897676}. Best is trial 1 with value: 0.5652153444114726.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:33:55,354] Trial 29 finished with value: 0.5370538041790577 and parameters: {'iterations': 500, 'learning_rate': 0.03, 'depth': 8, 'l2_leaf_reg': 2.9510244968102577}. Best is trial 1 with value: 0.5652153444114726.
[I 2025-09-08 20:33:55,355] A new study created in memory with name: no-name-23080eb5-027a-4bd0-a51a-b0ed21849a2c
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.419e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.055e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.509e+01, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 20:33:55,469] Trial 0 finished with value: 0.391422687680303 and parameters: {'alpha': 0.0016560295054450687, 'l1_ratio': 0.8924716607469375}. Best is trial 0 with value: 0.391422687680303.
[I 2025-09-08 20:33:55,556] Trial 1 finished with value: 0.33618605100049964 and parameters: {'alpha': 0.009267576475645533, 'l1_ratio': 0.857311308683949}. Best is trial 0 with value: 0.391422687680303.

✅ CAT con TOA_9x9_depth_in_3_4 - Mejor R2: 0.57
📋 Parámetros: {'iterations': 500, 'learning_rate': 0.04, 'depth': 8, 'l2_leaf_reg': 2.537570075127598}

Buscando mejores hiperparámetros para ELN con TOA_9x9_depth_in_3_4...
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.161e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.082e+00, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.992e+01, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 20:33:55,676] Trial 2 finished with value: 0.37856077520020043 and parameters: {'alpha': 0.004304983884358842, 'l1_ratio': 0.2568279953219812}. Best is trial 0 with value: 0.391422687680303.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:33:55,779] Trial 3 finished with value: 0.25652231843582135 and parameters: {'alpha': 0.02501647698669705, 'l1_ratio': 0.6580278035863563}. Best is trial 0 with value: 0.391422687680303.
[I 2025-09-08 20:33:55,883] Trial 4 finished with value: 0.26852503403281097 and parameters: {'alpha': 0.018989768364116057, 'l1_ratio': 0.8326158818520826}. Best is trial 0 with value: 0.391422687680303.
[I 2025-09-08 20:33:55,946] Trial 5 finished with value: 0.13692951545842694 and parameters: {'alpha': 0.0791494716796674, 'l1_ratio': 0.640491503008952}. Best is trial 0 with value: 0.391422687680303.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 20:33:56,029] Trial 6 finished with value: 0.010576593538206133 and parameters: {'alpha': 0.6955673666018194, 'l1_ratio': 0.8818510623891992}. Best is trial 0 with value: 0.391422687680303.
[I 2025-09-08 20:33:56,111] Trial 7 finished with value: 0.030301597650655543 and parameters: {'alpha': 0.4466314527563927, 'l1_ratio': 0.4262742277714334}. Best is trial 0 with value: 0.391422687680303.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.391e+00, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.450e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.055e+01, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 20:33:56,205] Trial 8 finished with value: 0.38423374834704865 and parameters: {'alpha': 0.002644746604387958, 'l1_ratio': 0.6268618215679891}. Best is trial 0 with value: 0.391422687680303.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.898e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.409e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.278e+01, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 20:33:56,316] Trial 9 finished with value: 0.3872623020552364 and parameters: {'alpha': 0.00292685820370209, 'l1_ratio': 0.1957592773320882}. Best is trial 0 with value: 0.391422687680303.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.338e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.778e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.073e+02, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 20:33:56,419] Trial 10 finished with value: 0.428199200199553 and parameters: {'alpha': 0.00016418848142119678, 'l1_ratio': 0.3567614317636959}. Best is trial 10 with value: 0.428199200199553.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.316e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.886e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.082e+02, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 20:33:56,520] Trial 11 finished with value: 0.4297699193013898 and parameters: {'alpha': 0.00011608350604563636, 'l1_ratio': 0.392385986376475}. Best is trial 11 with value: 0.4297699193013898.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.320e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.938e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.087e+02, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 20:33:56,625] Trial 12 finished with value: 0.4301585381511141 and parameters: {'alpha': 0.00010243720236289113, 'l1_ratio': 0.3887769460729168}. Best is trial 12 with value: 0.4301585381511141.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.633e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.304e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.133e+02, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 20:33:56,734] Trial 13 finished with value: 0.42849398617515266 and parameters: {'alpha': 0.00013374470826942, 'l1_ratio': 0.10334170518276142}. Best is trial 12 with value: 0.4301585381511141.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.748e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.464e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.402e+01, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 20:33:56,853] Trial 14 finished with value: 0.424248001293736 and parameters: {'alpha': 0.0003087561209514826, 'l1_ratio': 0.5016111453261598}. Best is trial 12 with value: 0.4301585381511141.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.033e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.692e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.975e+01, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 20:33:56,978] Trial 15 finished with value: 0.41438076154165326 and parameters: {'alpha': 0.0006444081881826212, 'l1_ratio': 0.4893265741850635}. Best is trial 12 with value: 0.4301585381511141.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.660e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.575e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.082e+01, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 20:33:57,090] Trial 16 finished with value: 0.4133633708127382 and parameters: {'alpha': 0.0006711128573538062, 'l1_ratio': 0.329002166380051}. Best is trial 12 with value: 0.4301585381511141.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.207e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.753e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.063e+02, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 20:33:57,212] Trial 17 finished with value: 0.430009244164747 and parameters: {'alpha': 0.00011636801886951968, 'l1_ratio': 0.5092403777634045}. Best is trial 12 with value: 0.4301585381511141.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.982e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.506e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.782e+01, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 20:33:57,310] Trial 18 finished with value: 0.41715482422762823 and parameters: {'alpha': 0.0005513888269803338, 'l1_ratio': 0.5478442791731157}. Best is trial 12 with value: 0.4301585381511141.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 20:33:57,386] Trial 19 finished with value: 0.1076397769665846 and parameters: {'alpha': 0.08893707581298638, 'l1_ratio': 0.7386683047524705}. Best is trial 12 with value: 0.4301585381511141.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.499e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.446e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.361e+01, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 20:33:57,492] Trial 20 finished with value: 0.4039688181651962 and parameters: {'alpha': 0.0012077338770470642, 'l1_ratio': 0.2716819794484401}. Best is trial 12 with value: 0.4301585381511141.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.277e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.724e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.066e+02, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 20:33:57,611] Trial 21 finished with value: 0.42871529737318 and parameters: {'alpha': 0.00015281357740971194, 'l1_ratio': 0.40915161432130737}. Best is trial 12 with value: 0.4301585381511141.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.789e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.499e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.367e+01, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 20:33:57,721] Trial 22 finished with value: 0.4226927445477376 and parameters: {'alpha': 0.0003468658224764808, 'l1_ratio': 0.43305984267571157}. Best is trial 12 with value: 0.4301585381511141.

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.154e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.625e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.049e+02, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 20:33:57,836] Trial 23 finished with value: 0.429577481627515 and parameters: {'alpha': 0.00013456161030451453, 'l1_ratio': 0.5380412091702831}. Best is trial 12 with value: 0.4301585381511141.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.352e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.975e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.093e+02, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 20:33:58,014] Trial 24 finished with value: 0.43005568831938673 and parameters: {'alpha': 0.00010356082959078544, 'l1_ratio': 0.3505483390647986}. Best is trial 12 with value: 0.4301585381511141.

Fold 3
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.310e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.348e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.040e+02, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 20:33:58,126] Trial 25 finished with value: 0.42399529841508454 and parameters: {'alpha': 0.0002886506226251779, 'l1_ratio': 0.2921054616273064}. Best is trial 12 with value: 0.4301585381511141.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.570e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.773e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.084e+02, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 20:33:58,238] Trial 26 finished with value: 0.42332972061507124 and parameters: {'alpha': 0.00029662923394031907, 'l1_ratio': 0.1902912909123693}. Best is trial 12 with value: 0.4301585381511141.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.921e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.414e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.221e+01, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 20:33:58,342] Trial 27 finished with value: 0.40472383927086675 and parameters: {'alpha': 0.001086678222542939, 'l1_ratio': 0.472159356337458}. Best is trial 12 with value: 0.4301585381511141.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.088e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.523e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.856e+01, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 20:33:58,445] Trial 28 finished with value: 0.41926658909832976 and parameters: {'alpha': 0.00047750811768599026, 'l1_ratio': 0.5672830893523226}. Best is trial 12 with value: 0.4301585381511141.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.013e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.040e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.802e+01, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 20:33:58,549] Trial 29 finished with value: 0.3968765407499661 and parameters: {'alpha': 0.0016593921394467417, 'l1_ratio': 0.36584692369886984}. Best is trial 12 with value: 0.4301585381511141.
[I 2025-09-08 20:33:58,552] A new study created in memory with name: no-name-875687e3-07d6-4a28-8183-8b25efdb4e62

Fold 1
Fold 2
Fold 3

✅ ELN con TOA_9x9_depth_in_3_4 - Mejor R2: 0.43
📋 Parámetros: {'alpha': 0.00010243720236289113, 'l1_ratio': 0.3887769460729168}

Buscando mejores hiperparámetros para XGB con TOA_3x3_depth_in_3_4...
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:34:02,908] Trial 0 finished with value: 0.4467892120395362 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.769690120650753, 'colsample_bytree': 0.7794816033099694}. Best is trial 0 with value: 0.4467892120395362.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:34:07,495] Trial 1 finished with value: 0.45002477968883303 and parameters: {'n_estimators': 1250, 'learning_rate': 0.03, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.6431135438036506, 'colsample_bytree': 0.6106700183621515}. Best is trial 1 with value: 0.45002477968883303.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:34:14,162] Trial 2 finished with value: 0.45718212565668476 and parameters: {'n_estimators': 1250, 'learning_rate': 0.01, 'max_depth': 8, 'min_child_weight': 4, 'subsample': 0.6021761421580955, 'colsample_bytree': 0.7245878467667474}. Best is trial 2 with value: 0.45718212565668476.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:34:21,071] Trial 3 finished with value: 0.43243586459179556 and parameters: {'n_estimators': 1250, 'learning_rate': 0.03, 'max_depth': 8, 'min_child_weight': 2, 'subsample': 0.6043247321863312, 'colsample_bytree': 0.6722355096270266}. Best is trial 2 with value: 0.45718212565668476.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:34:23,863] Trial 4 finished with value: 0.45338948159649145 and parameters: {'n_estimators': 750, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.7308277447164031, 'colsample_bytree': 0.727531131543219}. Best is trial 2 with value: 0.45718212565668476.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:34:27,798] Trial 5 finished with value: 0.43476079439093196 and parameters: {'n_estimators': 750, 'learning_rate': 0.03, 'max_depth': 8, 'min_child_weight': 4, 'subsample': 0.6489081167316685, 'colsample_bytree': 0.7637520619353944}. Best is trial 2 with value: 0.45718212565668476.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:34:31,901] Trial 6 finished with value: 0.42985544050553753 and parameters: {'n_estimators': 750, 'learning_rate': 0.03, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.7915194903764738, 'colsample_bytree': 0.7414465622785058}. Best is trial 2 with value: 0.45718212565668476.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:34:38,386] Trial 7 finished with value: 0.4477674789901453 and parameters: {'n_estimators': 1250, 'learning_rate': 0.02, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.6712346357640436, 'colsample_bytree': 0.7496939419678336}. Best is trial 2 with value: 0.45718212565668476.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:34:41,935] Trial 8 finished with value: 0.4621299258197345 and parameters: {'n_estimators': 750, 'learning_rate': 0.01, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.6658113244825449, 'colsample_bytree': 0.7610975976327279}. Best is trial 8 with value: 0.4621299258197345.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:34:49,172] Trial 9 finished with value: 0.4452047539800317 and parameters: {'n_estimators': 1250, 'learning_rate': 0.02, 'max_depth': 8, 'min_child_weight': 2, 'subsample': 0.6180737593423558, 'colsample_bytree': 0.6368882589063531}. Best is trial 8 with value: 0.4621299258197345.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:34:53,359] Trial 10 finished with value: 0.45929921374382704 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.7011758831075103, 'colsample_bytree': 0.6809293129453855}. Best is trial 8 with value: 0.4621299258197345.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:34:57,815] Trial 11 finished with value: 0.4559033645948101 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.6908196642719414, 'colsample_bytree': 0.6842978082899879}. Best is trial 8 with value: 0.4621299258197345.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:35:01,996] Trial 12 finished with value: 0.4614037424347583 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.721860448768819, 'colsample_bytree': 0.6573471300324369}. Best is trial 8 with value: 0.4621299258197345.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:35:06,267] Trial 13 finished with value: 0.45345892451837716 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.7292814259142881, 'colsample_bytree': 0.7963416751419394}. Best is trial 8 with value: 0.4621299258197345.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:35:09,024] Trial 14 finished with value: 0.4583479992197712 and parameters: {'n_estimators': 750, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.7318408089265145, 'colsample_bytree': 0.6451544091661156}. Best is trial 8 with value: 0.4621299258197345.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:35:14,720] Trial 15 finished with value: 0.45766338425156555 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.7002429354424295, 'colsample_bytree': 0.7076361838116284}. Best is trial 8 with value: 0.4621299258197345.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:35:17,774] Trial 16 finished with value: 0.4526459229953243 and parameters: {'n_estimators': 750, 'learning_rate': 0.02, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.6645356442006712, 'colsample_bytree': 0.6473943194545683}. Best is trial 8 with value: 0.4621299258197345.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:35:22,705] Trial 17 finished with value: 0.4503661974492961 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.7521426945542836, 'colsample_bytree': 0.6071332306230548}. Best is trial 8 with value: 0.4621299258197345.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:35:25,462] Trial 18 finished with value: 0.45119639968836484 and parameters: {'n_estimators': 750, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.6810351921764964, 'colsample_bytree': 0.7018986571679535}. Best is trial 8 with value: 0.4621299258197345.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:35:29,097] Trial 19 finished with value: 0.43544570867218385 and parameters: {'n_estimators': 750, 'learning_rate': 0.02, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.7122937460213307, 'colsample_bytree': 0.6618141179596607}. Best is trial 8 with value: 0.4621299258197345.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:35:34,090] Trial 20 finished with value: 0.45083273078433095 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.6341128574932795, 'colsample_bytree': 0.7992197118416423}. Best is trial 8 with value: 0.4621299258197345.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:35:38,303] Trial 21 finished with value: 0.458772816842506 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.709455961843497, 'colsample_bytree': 0.6861236065834075}. Best is trial 8 with value: 0.4621299258197345.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:35:42,801] Trial 22 finished with value: 0.45017180969259146 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.6650481765253848, 'colsample_bytree': 0.6657974614095181}. Best is trial 8 with value: 0.4621299258197345.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:35:46,888] Trial 23 finished with value: 0.4562708586395048 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.7529827635751373, 'colsample_bytree': 0.7134148686145231}. Best is trial 8 with value: 0.4621299258197345.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:35:50,440] Trial 24 finished with value: 0.44954813733547977 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.6877998655193855, 'colsample_bytree': 0.6223330477129974}. Best is trial 8 with value: 0.4621299258197345.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:35:55,097] Trial 25 finished with value: 0.44616787817186926 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.7107427683296116, 'colsample_bytree': 0.6869149725013887}. Best is trial 8 with value: 0.4621299258197345.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:35:58,894] Trial 26 finished with value: 0.4519809662991426 and parameters: {'n_estimators': 750, 'learning_rate': 0.01, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.74763751003377, 'colsample_bytree': 0.6347052443009153}. Best is trial 8 with value: 0.4621299258197345.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:36:02,996] Trial 27 finished with value: 0.4636444888589916 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.7208182203127074, 'colsample_bytree': 0.6519621765412179}. Best is trial 27 with value: 0.4636444888589916.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:36:06,623] Trial 28 finished with value: 0.45383081780488865 and parameters: {'n_estimators': 1000, 'learning_rate': 0.02, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.7220536001275879, 'colsample_bytree': 0.6543264520904087}. Best is trial 27 with value: 0.4636444888589916.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:36:09,633] Trial 29 finished with value: 0.4371934349971938 and parameters: {'n_estimators': 750, 'learning_rate': 0.03, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.7731056067624911, 'colsample_bytree': 0.7604849643759882}. Best is trial 27 with value: 0.4636444888589916.
[I 2025-09-08 20:36:09,636] A new study created in memory with name: no-name-f7713475-ac97-465a-b7d1-ad7c90b0cff4

✅ XGB con TOA_3x3_depth_in_3_4 - Mejor R2: 0.46
📋 Parámetros: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.7208182203127074, 'colsample_bytree': 0.6519621765412179}

Buscando mejores hiperparámetros para LBM con TOA_3x3_depth_in_3_4...
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:36:09,912] Trial 0 finished with value: 0.41588405111548415 and parameters: {'learning_rate': 0.05, 'num_leaves': 10, 'max_depth': 7, 'min_child_samples': 6, 'subsample': 0.6958010168233016, 'colsample_bytree': 0.7097863153124432, 'n_estimators': 750, 'min_split_gain': 0.0}. Best is trial 0 with value: 0.41588405111548415.
[I 2025-09-08 20:36:10,068] Trial 1 finished with value: 0.4396332340057807 and parameters: {'learning_rate': 0.03, 'num_leaves': 30, 'max_depth': 6, 'min_child_samples': 8, 'subsample': 0.6906599463555492, 'colsample_bytree': 0.6098493243397708, 'n_estimators': 1000, 'min_split_gain': 0.5}. Best is trial 1 with value: 0.4396332340057807.

Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 20:36:10,260] Trial 2 finished with value: 0.4235498387486228 and parameters: {'learning_rate': 0.02, 'num_leaves': 30, 'max_depth': 6, 'min_child_samples': 4, 'subsample': 0.6666911804961029, 'colsample_bytree': 0.6391879331389309, 'n_estimators': 1250, 'min_split_gain': 0.5}. Best is trial 1 with value: 0.4396332340057807.

Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 20:36:10,418] Trial 3 finished with value: 0.42588342322407313 and parameters: {'learning_rate': 0.05, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 7, 'subsample': 0.6049845142963433, 'colsample_bytree': 0.6819619502699079, 'n_estimators': 1000, 'min_split_gain': 0.1}. Best is trial 1 with value: 0.4396332340057807.
[I 2025-09-08 20:36:10,523] Trial 4 finished with value: 0.4429626530834392 and parameters: {'learning_rate': 0.05, 'num_leaves': 10, 'max_depth': 5, 'min_child_samples': 8, 'subsample': 0.7755615332465949, 'colsample_bytree': 0.7626036163951393, 'n_estimators': 1000, 'min_split_gain': 1.0}. Best is trial 4 with value: 0.4429626530834392.

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 20:36:10,642] Trial 5 finished with value: 0.4563832318725694 and parameters: {'learning_rate': 0.05, 'num_leaves': 30, 'max_depth': 8, 'min_child_samples': 7, 'subsample': 0.6043781518503527, 'colsample_bytree': 0.6345238989393786, 'n_estimators': 750, 'min_split_gain': 0.5}. Best is trial 5 with value: 0.4563832318725694.
[I 2025-09-08 20:36:10,794] Trial 6 finished with value: 0.44515650130975537 and parameters: {'learning_rate': 0.03, 'num_leaves': 10, 'max_depth': 8, 'min_child_samples': 8, 'subsample': 0.7888041519977731, 'colsample_bytree': 0.616102098084212, 'n_estimators': 1000, 'min_split_gain': 0.5}. Best is trial 5 with value: 0.4563832318725694.

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 20:36:10,966] Trial 7 finished with value: 0.4513588389595588 and parameters: {'learning_rate': 0.04, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 8, 'subsample': 0.7284822399193525, 'colsample_bytree': 0.6222759737347321, 'n_estimators': 1000, 'min_split_gain': 0.2}. Best is trial 5 with value: 0.4563832318725694.

Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 20:36:11,165] Trial 8 finished with value: 0.4073186673340081 and parameters: {'learning_rate': 0.03, 'num_leaves': 30, 'max_depth': 6, 'min_child_samples': 6, 'subsample': 0.634028318385564, 'colsample_bytree': 0.7227917692508593, 'n_estimators': 1250, 'min_split_gain': 0.2}. Best is trial 5 with value: 0.4563832318725694.

Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:36:11,324] Trial 9 finished with value: 0.4012256775590113 and parameters: {'learning_rate': 0.02, 'num_leaves': 30, 'max_depth': 6, 'min_child_samples': 6, 'subsample': 0.6662657852468772, 'colsample_bytree': 0.7381673340851047, 'n_estimators': 1000, 'min_split_gain': 1.0}. Best is trial 5 with value: 0.4563832318725694.
[I 2025-09-08 20:36:11,514] Trial 10 finished with value: 0.4093578075702135 and parameters: {'learning_rate': 0.04, 'num_leaves': 30, 'max_depth': 8, 'min_child_samples': 4, 'subsample': 0.6036173383060609, 'colsample_bytree': 0.6670952480064141, 'n_estimators': 750, 'min_split_gain': 0.1}. Best is trial 5 with value: 0.4563832318725694.

Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 20:36:11,690] Trial 11 finished with value: 0.4422813459006092 and parameters: {'learning_rate': 0.04, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 7, 'subsample': 0.7347542052069431, 'colsample_bytree': 0.6511350099288349, 'n_estimators': 750, 'min_split_gain': 0.2}. Best is trial 5 with value: 0.4563832318725694.

Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 20:36:11,865] Trial 12 finished with value: 0.45193609036306537 and parameters: {'learning_rate': 0.04, 'num_leaves': 20, 'max_depth': 8, 'min_child_samples': 7, 'subsample': 0.7384482256042795, 'colsample_bytree': 0.6058765684420393, 'n_estimators': 750, 'min_split_gain': 0.2}. Best is trial 5 with value: 0.4563832318725694.

Fold 3
Fold 1
Fold 2

[I 2025-09-08 20:36:12,272] Trial 13 finished with value: 0.4451628121831745 and parameters: {'learning_rate': 0.05, 'num_leaves': 20, 'max_depth': 8, 'min_child_samples': 7, 'subsample': 0.7469970672733258, 'colsample_bytree': 0.6021571745235116, 'n_estimators': 750, 'min_split_gain': 0.0}. Best is trial 5 with value: 0.4563832318725694.

Fold 3
Fold 1

[I 2025-09-08 20:36:12,450] Trial 14 finished with value: 0.386982592991948 and parameters: {'learning_rate': 0.04, 'num_leaves': 20, 'max_depth': 8, 'min_child_samples': 5, 'subsample': 0.7500284730173432, 'colsample_bytree': 0.7871748695751581, 'n_estimators': 750, 'min_split_gain': 0.2}. Best is trial 5 with value: 0.4563832318725694.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:36:12,584] Trial 15 finished with value: 0.4563832318725694 and parameters: {'learning_rate': 0.05, 'num_leaves': 30, 'max_depth': 8, 'min_child_samples': 7, 'subsample': 0.7164147829288685, 'colsample_bytree': 0.6431272497263736, 'n_estimators': 750, 'min_split_gain': 0.5}. Best is trial 5 with value: 0.4563832318725694.
[I 2025-09-08 20:36:12,709] Trial 16 finished with value: 0.39930987112216565 and parameters: {'learning_rate': 0.05, 'num_leaves': 30, 'max_depth': 7, 'min_child_samples': 5, 'subsample': 0.6426892363835598, 'colsample_bytree': 0.6845480647629097, 'n_estimators': 750, 'min_split_gain': 0.5}. Best is trial 5 with value: 0.4563832318725694.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 20:36:12,868] Trial 17 finished with value: 0.448806584013639 and parameters: {'learning_rate': 0.05, 'num_leaves': 30, 'max_depth': 8, 'min_child_samples': 7, 'subsample': 0.7074170028198586, 'colsample_bytree': 0.6476991074334458, 'n_estimators': 1250, 'min_split_gain': 0.5}. Best is trial 5 with value: 0.4563832318725694.
[I 2025-09-08 20:36:12,997] Trial 18 finished with value: 0.4073832570618463 and parameters: {'learning_rate': 0.05, 'num_leaves': 30, 'max_depth': 7, 'min_child_samples': 5, 'subsample': 0.6665537122849069, 'colsample_bytree': 0.6340673154731857, 'n_estimators': 750, 'min_split_gain': 0.5}. Best is trial 5 with value: 0.4563832318725694.

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 20:36:13,131] Trial 19 finished with value: 0.4307959451037722 and parameters: {'learning_rate': 0.05, 'num_leaves': 30, 'max_depth': 8, 'min_child_samples': 7, 'subsample': 0.7160974408156827, 'colsample_bytree': 0.664450643827849, 'n_estimators': 750, 'min_split_gain': 0.5}. Best is trial 5 with value: 0.4563832318725694.

Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 20:36:13,350] Trial 20 finished with value: 0.3998994877939026 and parameters: {'learning_rate': 0.02, 'num_leaves': 30, 'max_depth': 7, 'min_child_samples': 6, 'subsample': 0.628656919692154, 'colsample_bytree': 0.6851222825202068, 'n_estimators': 750, 'min_split_gain': 0.5}. Best is trial 5 with value: 0.4563832318725694.

Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:36:13,529] Trial 21 finished with value: 0.45009247592836193 and parameters: {'learning_rate': 0.04, 'num_leaves': 20, 'max_depth': 8, 'min_child_samples': 7, 'subsample': 0.7649124502169425, 'colsample_bytree': 0.6267599799718743, 'n_estimators': 750, 'min_split_gain': 0.2}. Best is trial 5 with value: 0.4563832318725694.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:36:13,769] Trial 22 finished with value: 0.4541002925260729 and parameters: {'learning_rate': 0.04, 'num_leaves': 20, 'max_depth': 8, 'min_child_samples': 7, 'subsample': 0.6819103964747685, 'colsample_bytree': 0.6612883990930977, 'n_estimators': 750, 'min_split_gain': 0.1}. Best is trial 5 with value: 0.4563832318725694.
[I 2025-09-08 20:36:13,923] Trial 23 finished with value: 0.40349239546718874 and parameters: {'learning_rate': 0.05, 'num_leaves': 10, 'max_depth': 8, 'min_child_samples': 6, 'subsample': 0.6825468405493041, 'colsample_bytree': 0.6624459586155009, 'n_estimators': 750, 'min_split_gain': 0.1}. Best is trial 5 with value: 0.4563832318725694.

Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 20:36:14,107] Trial 24 finished with value: 0.4523150479842421 and parameters: {'learning_rate': 0.05, 'num_leaves': 30, 'max_depth': 8, 'min_child_samples': 8, 'subsample': 0.653434333965746, 'colsample_bytree': 0.65120798249657, 'n_estimators': 750, 'min_split_gain': 0.1}. Best is trial 5 with value: 0.4563832318725694.

Fold 2
Fold 3
Fold 1

[I 2025-09-08 20:36:14,340] Trial 25 finished with value: 0.45059824125342085 and parameters: {'learning_rate': 0.04, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 7, 'subsample': 0.6166892681050986, 'colsample_bytree': 0.7039345266526656, 'n_estimators': 1250, 'min_split_gain': 0.1}. Best is trial 5 with value: 0.4563832318725694.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:36:14,806] Trial 26 finished with value: 0.41517030027506435 and parameters: {'learning_rate': 0.02, 'num_leaves': 30, 'max_depth': 8, 'min_child_samples': 6, 'subsample': 0.7131680330079045, 'colsample_bytree': 0.6738690498130094, 'n_estimators': 750, 'min_split_gain': 0.0}. Best is trial 5 with value: 0.4563832318725694.
[I 2025-09-08 20:36:14,949] Trial 27 finished with value: 0.4334763865713495 and parameters: {'learning_rate': 0.03, 'num_leaves': 30, 'max_depth': 7, 'min_child_samples': 7, 'subsample': 0.6792268433613785, 'colsample_bytree': 0.6322007963619016, 'n_estimators': 750, 'min_split_gain': 1.0}. Best is trial 5 with value: 0.4563832318725694.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 20:36:15,117] Trial 28 finished with value: 0.4400582151986215 and parameters: {'learning_rate': 0.05, 'num_leaves': 10, 'max_depth': 8, 'min_child_samples': 8, 'subsample': 0.6447146645506452, 'colsample_bytree': 0.648631430869986, 'n_estimators': 750, 'min_split_gain': 0.1}. Best is trial 5 with value: 0.4563832318725694.

Fold 3
Fold 1
Fold 2

[I 2025-09-08 20:36:15,487] Trial 29 finished with value: 0.4160620588452269 and parameters: {'learning_rate': 0.05, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 6, 'subsample': 0.6976770453906267, 'colsample_bytree': 0.6966619478206495, 'n_estimators': 750, 'min_split_gain': 0.0}. Best is trial 5 with value: 0.4563832318725694.
[I 2025-09-08 20:36:15,489] A new study created in memory with name: no-name-702645b0-7907-4a51-874a-34960aa7a425

Fold 3

✅ LBM con TOA_3x3_depth_in_3_4 - Mejor R2: 0.46
📋 Parámetros: {'learning_rate': 0.05, 'num_leaves': 30, 'max_depth': 8, 'min_child_samples': 7, 'subsample': 0.6043781518503527, 'colsample_bytree': 0.6345238989393786, 'n_estimators': 750, 'min_split_gain': 0.5}

Buscando mejores hiperparámetros para MLP con TOA_3x3_depth_in_3_4...
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 20:36:16,493] Trial 0 finished with value: 0.06918228050106923 and parameters: {'hidden_layer_sizes': (128,), 'activation': 'relu', 'solver': 'sgd', 'alpha': 5.006938333612558e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00025724150386908406}. Best is trial 0 with value: 0.06918228050106923.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 20:36:17,265] Trial 1 finished with value: -0.07775176461921389 and parameters: {'hidden_layer_sizes': (32,), 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0002543169869654584, 'learning_rate': 'constant', 'learning_rate_init': 0.00016792600192566939}. Best is trial 0 with value: 0.06918228050106923.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 20:36:17,861] Trial 2 finished with value: 0.2624656722141558 and parameters: {'hidden_layer_sizes': (32,), 'activation': 'relu', 'solver': 'adam', 'alpha': 1.5285333932847357e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.0008950818626994932}. Best is trial 2 with value: 0.2624656722141558.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 20:36:18,864] Trial 3 finished with value: 0.14995531334535842 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'relu', 'solver': 'sgd', 'alpha': 4.717554166886539e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0004768867002077231}. Best is trial 2 with value: 0.2624656722141558.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:36:19,157] Trial 4 finished with value: 0.09871893032386862 and parameters: {'hidden_layer_sizes': (128,), 'activation': 'relu', 'solver': 'adam', 'alpha': 0.027597690956111597, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0008906776597055014}. Best is trial 2 with value: 0.2624656722141558.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 20:36:19,881] Trial 5 finished with value: 0.35716043529269365 and parameters: {'hidden_layer_sizes': (128,), 'activation': 'tanh', 'solver': 'adam', 'alpha': 7.428736001913222e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0012484767118200219}. Best is trial 5 with value: 0.35716043529269365.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2

[I 2025-09-08 20:36:20,398] Trial 6 finished with value: 0.45187071032539133 and parameters: {'hidden_layer_sizes': (32,), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.008579121589882036, 'learning_rate': 'adaptive', 'learning_rate_init': 0.005327377124204867}. Best is trial 6 with value: 0.45187071032539133.

Fold 3
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 2
Fold 3

[I 2025-09-08 20:36:21,017] Trial 7 finished with value: 0.31789583786950765 and parameters: {'hidden_layer_sizes': (128,), 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.03496519192175116, 'learning_rate': 'constant', 'learning_rate_init': 0.003953427041346968}. Best is trial 6 with value: 0.45187071032539133.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 20:36:21,815] Trial 8 finished with value: 0.19906692852975735 and parameters: {'hidden_layer_sizes': (32,), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.04860720240702506, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00026411961400463234}. Best is trial 6 with value: 0.45187071032539133.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 20:36:22,546] Trial 9 finished with value: -0.2783698784710806 and parameters: {'hidden_layer_sizes': (64,), 'activation': 'relu', 'solver': 'sgd', 'alpha': 1.2298447029289875e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00012457647673728677}. Best is trial 6 with value: 0.45187071032539133.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:36:23,322] Trial 10 finished with value: 0.4841098524612904 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0034940126564838997, 'learning_rate': 'constant', 'learning_rate_init': 0.00878762192225214}. Best is trial 10 with value: 0.4841098524612904.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:36:23,935] Trial 11 finished with value: 0.43441346964848365 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.003750583074817048, 'learning_rate': 'constant', 'learning_rate_init': 0.009651640785107472}. Best is trial 10 with value: 0.4841098524612904.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:36:24,728] Trial 12 finished with value: 0.4752248508358507 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0034443594614515342, 'learning_rate': 'constant', 'learning_rate_init': 0.008611217723104922}. Best is trial 10 with value: 0.4841098524612904.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 20:36:25,508] Trial 13 finished with value: 0.46271488439699987 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0013259138275066849, 'learning_rate': 'constant', 'learning_rate_init': 0.00284014719601991}. Best is trial 10 with value: 0.4841098524612904.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:36:26,309] Trial 14 finished with value: 0.5068519873946112 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.000872940140769533, 'learning_rate': 'constant', 'learning_rate_init': 0.00937175921831572}. Best is trial 14 with value: 0.5068519873946112.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 20:36:27,172] Trial 15 finished with value: 0.4628348743894665 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0004126496031168675, 'learning_rate': 'constant', 'learning_rate_init': 0.002381154805861848}. Best is trial 14 with value: 0.5068519873946112.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 20:36:27,799] Trial 16 finished with value: 0.432824229819942 and parameters: {'hidden_layer_sizes': (64,), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.001005122534776586, 'learning_rate': 'constant', 'learning_rate_init': 0.005686934156357611}. Best is trial 14 with value: 0.5068519873946112.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 3
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 20:36:28,829] Trial 17 finished with value: 0.49329730026200874 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.01032500233851789, 'learning_rate': 'constant', 'learning_rate_init': 0.0019453724583061956}. Best is trial 14 with value: 0.5068519873946112.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 20:36:29,733] Trial 18 finished with value: 0.377586351666809 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.09960409538562186, 'learning_rate': 'constant', 'learning_rate_init': 0.00165994384408712}. Best is trial 14 with value: 0.5068519873946112.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 3
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 20:36:30,906] Trial 19 finished with value: 0.4754637214592801 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.008409557797631969, 'learning_rate': 'constant', 'learning_rate_init': 0.0005621035246181266}. Best is trial 14 with value: 0.5068519873946112.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 20:36:31,603] Trial 20 finished with value: 0.45355078915176056 and parameters: {'hidden_layer_sizes': (64,), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.00024993889534711156, 'learning_rate': 'constant', 'learning_rate_init': 0.0021254281079477813}. Best is trial 14 with value: 0.5068519873946112.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:36:32,468] Trial 21 finished with value: 0.4902969275861196 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0032370219611958717, 'learning_rate': 'constant', 'learning_rate_init': 0.006269025434504567}. Best is trial 14 with value: 0.5068519873946112.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 20:36:33,274] Trial 22 finished with value: 0.4637576964954225 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.011819242951346752, 'learning_rate': 'constant', 'learning_rate_init': 0.004214730423676784}. Best is trial 14 with value: 0.5068519873946112.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:36:33,990] Trial 23 finished with value: 0.49033946952191343 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.001420641102418813, 'learning_rate': 'constant', 'learning_rate_init': 0.006266729491800314}. Best is trial 14 with value: 0.5068519873946112.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 20:36:34,770] Trial 24 finished with value: 0.4606944043920649 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0006472667903950969, 'learning_rate': 'constant', 'learning_rate_init': 0.0033139767729656456}. Best is trial 14 with value: 0.5068519873946112.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:36:35,520] Trial 25 finished with value: 0.4901312155242663 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.001906114060442951, 'learning_rate': 'constant', 'learning_rate_init': 0.0062991871293027295}. Best is trial 14 with value: 0.5068519873946112.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 20:36:36,423] Trial 26 finished with value: 0.3777281142679529 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.0001751101547738174, 'learning_rate': 'constant', 'learning_rate_init': 0.001530493941811245}. Best is trial 14 with value: 0.5068519873946112.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 3
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 20:36:37,211] Trial 27 finished with value: 0.46468233210058557 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.012062013098743439, 'learning_rate': 'constant', 'learning_rate_init': 0.0043151491296654874}. Best is trial 14 with value: 0.5068519873946112.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 20:36:37,844] Trial 28 finished with value: 0.434577356582905 and parameters: {'hidden_layer_sizes': (64,), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0005816503440745407, 'learning_rate': 'constant', 'learning_rate_init': 0.006910875561387757}. Best is trial 14 with value: 0.5068519873946112.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 3
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

[I 2025-09-08 20:36:38,754] Trial 29 finished with value: 0.1909478550957637 and parameters: {'hidden_layer_sizes': (128,), 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.00010179665098370563, 'learning_rate': 'constant', 'learning_rate_init': 0.0006527347331074637}. Best is trial 14 with value: 0.5068519873946112.
[I 2025-09-08 20:36:38,756] A new study created in memory with name: no-name-96972330-4b4e-4070-85b8-8c9cd9eae4c1
[I 2025-09-08 20:36:38,836] Trial 0 finished with value: 0.3739378248387779 and parameters: {'C': 2.0565812285607956, 'epsilon': 0.13800296362341613}. Best is trial 0 with value: 0.3739378248387779.
[I 2025-09-08 20:36:38,888] Trial 1 finished with value: 0.44553226004708185 and parameters: {'C': 4.626430525523203, 'epsilon': 0.19604600002988615}. Best is trial 1 with value: 0.44553226004708185.
[I 2025-09-08 20:36:38,940] Trial 2 finished with value: 0.04267592308965573 and parameters: {'C': 0.17156830630260061, 'epsilon': 0.09388875755741083}. Best is trial 1 with value: 0.44553226004708185.

✅ MLP con TOA_3x3_depth_in_3_4 - Mejor R2: 0.51
📋 Parámetros: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.000872940140769533, 'learning_rate': 'constant', 'learning_rate_init': 0.00937175921831572}

Buscando mejores hiperparámetros para SVR con TOA_3x3_depth_in_3_4...
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 20:36:38,991] Trial 3 finished with value: 0.19606088041557668 and parameters: {'C': 0.5291955676228675, 'epsilon': 0.16939232862998846}. Best is trial 1 with value: 0.44553226004708185.
[I 2025-09-08 20:36:39,047] Trial 4 finished with value: 0.4430446893086886 and parameters: {'C': 4.971722463796003, 'epsilon': 0.08153735698090187}. Best is trial 1 with value: 0.44553226004708185.
[I 2025-09-08 20:36:39,097] Trial 5 finished with value: 0.11569436540517415 and parameters: {'C': 0.30155291858082905, 'epsilon': 0.1835414506438229}. Best is trial 1 with value: 0.44553226004708185.
[I 2025-09-08 20:36:39,149] Trial 6 finished with value: 0.344067524981101 and parameters: {'C': 1.719737828182292, 'epsilon': 0.025411755016677796}. Best is trial 1 with value: 0.44553226004708185.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 20:36:39,205] Trial 7 finished with value: 0.07370558791024251 and parameters: {'C': 0.24440045913135577, 'epsilon': 0.018902439127546862}. Best is trial 1 with value: 0.44553226004708185.
[I 2025-09-08 20:36:39,258] Trial 8 finished with value: 0.16995567770481101 and parameters: {'C': 0.48912059739259295, 'epsilon': 0.11697482538267558}. Best is trial 1 with value: 0.44553226004708185.
[I 2025-09-08 20:36:39,306] Trial 9 finished with value: 0.09775800509441608 and parameters: {'C': 0.2630631836049226, 'epsilon': 0.1715733569208732}. Best is trial 1 with value: 0.44553226004708185.
[I 2025-09-08 20:36:39,366] Trial 10 finished with value: 0.501690479283069 and parameters: {'C': 9.069677890226378, 'epsilon': 0.197825904448714}. Best is trial 10 with value: 0.501690479283069.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:36:39,430] Trial 11 finished with value: 0.5069522063447043 and parameters: {'C': 9.851842394028774, 'epsilon': 0.18652628326291426}. Best is trial 11 with value: 0.5069522063447043.
[I 2025-09-08 20:36:39,494] Trial 12 finished with value: 0.5071515532200502 and parameters: {'C': 9.751518354981506, 'epsilon': 0.1472428070652645}. Best is trial 12 with value: 0.5071515532200502.
[I 2025-09-08 20:36:39,554] Trial 13 finished with value: 0.4916662471119742 and parameters: {'C': 7.708426395662592, 'epsilon': 0.14344045124000637}. Best is trial 12 with value: 0.5071515532200502.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 20:36:39,616] Trial 14 finished with value: 0.40388870035504904 and parameters: {'C': 2.8446324221342962, 'epsilon': 0.1491947774094398}. Best is trial 12 with value: 0.5071515532200502.
[I 2025-09-08 20:36:39,677] Trial 15 finished with value: 0.28528025472774726 and parameters: {'C': 1.1380744698455263, 'epsilon': 0.06635042231283539}. Best is trial 12 with value: 0.5071515532200502.
[I 2025-09-08 20:36:39,736] Trial 16 finished with value: 0.4357010376893096 and parameters: {'C': 4.380073135487509, 'epsilon': 0.127682858697525}. Best is trial 12 with value: 0.5071515532200502.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:36:39,792] Trial 17 finished with value: -0.0004314017435402828 and parameters: {'C': 0.10429349013735727, 'epsilon': 0.15822835167152102}. Best is trial 12 with value: 0.5071515532200502.
[I 2025-09-08 20:36:39,853] Trial 18 finished with value: 0.5092640241692025 and parameters: {'C': 9.821267059819277, 'epsilon': 0.10498901641112071}. Best is trial 18 with value: 0.5092640241692025.
[I 2025-09-08 20:36:39,911] Trial 19 finished with value: 0.4023375990567846 and parameters: {'C': 2.9652827276884715, 'epsilon': 0.05363581479571603}. Best is trial 18 with value: 0.5092640241692025.
[I 2025-09-08 20:36:39,971] Trial 20 finished with value: 0.46115436038974417 and parameters: {'C': 5.710698385242585, 'epsilon': 0.11119773996182658}. Best is trial 18 with value: 0.5092640241692025.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 20:36:40,035] Trial 21 finished with value: 0.508584896403936 and parameters: {'C': 9.957578782073883, 'epsilon': 0.12695604433896365}. Best is trial 18 with value: 0.5092640241692025.
[I 2025-09-08 20:36:40,098] Trial 22 finished with value: 0.4730945712971668 and parameters: {'C': 6.5760676684940025, 'epsilon': 0.09542245520529002}. Best is trial 18 with value: 0.5092640241692025.
[I 2025-09-08 20:36:40,159] Trial 23 finished with value: 0.4172900787508607 and parameters: {'C': 3.455276730805983, 'epsilon': 0.12538855014259712}. Best is trial 18 with value: 0.5092640241692025.

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:36:40,219] Trial 24 finished with value: 0.5096098419414844 and parameters: {'C': 9.879423718522935, 'epsilon': 0.09910316141795063}. Best is trial 24 with value: 0.5096098419414844.
[I 2025-09-08 20:36:40,285] Trial 25 finished with value: 0.46727999632945255 and parameters: {'C': 6.478882078553211, 'epsilon': 0.07324477294235295}. Best is trial 24 with value: 0.5096098419414844.
[I 2025-09-08 20:36:40,346] Trial 26 finished with value: 0.3608244765815824 and parameters: {'C': 1.8808779763201657, 'epsilon': 0.04562498679422881}. Best is trial 24 with value: 0.5096098419414844.
[I 2025-09-08 20:36:40,403] Trial 27 finished with value: 0.26185618414021355 and parameters: {'C': 0.968232413468853, 'epsilon': 0.0951677595984241}. Best is trial 24 with value: 0.5096098419414844.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 20:36:40,467] Trial 28 finished with value: 0.427248750920119 and parameters: {'C': 3.9289621417839045, 'epsilon': 0.10131700122364398}. Best is trial 24 with value: 0.5096098419414844.
[I 2025-09-08 20:36:40,529] Trial 29 finished with value: 0.39831097051611836 and parameters: {'C': 2.5766708586126215, 'epsilon': 0.1311290994571098}. Best is trial 24 with value: 0.5096098419414844.
[I 2025-09-08 20:36:40,530] A new study created in memory with name: no-name-99921d13-4c27-47a7-a2da-83cc9d7efa14
[I 2025-09-08 20:36:40,574] Trial 0 finished with value: 0.39234509423016806 and parameters: {'n_neighbors': 9, 'leaf_size': 12}. Best is trial 0 with value: 0.39234509423016806.
[I 2025-09-08 20:36:40,618] Trial 1 finished with value: 0.39234509423016806 and parameters: {'n_neighbors': 9, 'leaf_size': 21}. Best is trial 0 with value: 0.39234509423016806.

Fold 3
Fold 1
Fold 2
Fold 3

✅ SVR con TOA_3x3_depth_in_3_4 - Mejor R2: 0.51
📋 Parámetros: {'C': 9.879423718522935, 'epsilon': 0.09910316141795063}

Buscando mejores hiperparámetros para KNN con TOA_3x3_depth_in_3_4...
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:36:40,663] Trial 2 finished with value: 0.3811591452562495 and parameters: {'n_neighbors': 10, 'leaf_size': 27}. Best is trial 0 with value: 0.39234509423016806.
[I 2025-09-08 20:36:40,752] Trial 3 finished with value: 0.41489602400543557 and parameters: {'n_neighbors': 6, 'leaf_size': 12}. Best is trial 3 with value: 0.41489602400543557.
[I 2025-09-08 20:36:40,801] Trial 4 finished with value: 0.40444441328102493 and parameters: {'n_neighbors': 8, 'leaf_size': 12}. Best is trial 3 with value: 0.41489602400543557.
[I 2025-09-08 20:36:40,846] Trial 5 finished with value: 0.3800332027466178 and parameters: {'n_neighbors': 11, 'leaf_size': 10}. Best is trial 3 with value: 0.41489602400543557.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 20:36:40,894] Trial 6 finished with value: 0.3811591452562495 and parameters: {'n_neighbors': 10, 'leaf_size': 36}. Best is trial 3 with value: 0.41489602400543557.
[I 2025-09-08 20:36:40,942] Trial 7 finished with value: 0.3811591452562495 and parameters: {'n_neighbors': 10, 'leaf_size': 16}. Best is trial 3 with value: 0.41489602400543557.
[I 2025-09-08 20:36:40,987] Trial 8 finished with value: 0.3811591452562495 and parameters: {'n_neighbors': 10, 'leaf_size': 32}. Best is trial 3 with value: 0.41489602400543557.
[I 2025-09-08 20:36:41,030] Trial 9 finished with value: 0.3800332027466178 and parameters: {'n_neighbors': 11, 'leaf_size': 13}. Best is trial 3 with value: 0.41489602400543557.

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:36:41,083] Trial 10 finished with value: 0.4153869058004327 and parameters: {'n_neighbors': 4, 'leaf_size': 23}. Best is trial 10 with value: 0.4153869058004327.
[I 2025-09-08 20:36:41,136] Trial 11 finished with value: 0.4153869058004327 and parameters: {'n_neighbors': 4, 'leaf_size': 23}. Best is trial 10 with value: 0.4153869058004327.
[I 2025-09-08 20:36:41,188] Trial 12 finished with value: 0.37102037030198604 and parameters: {'n_neighbors': 3, 'leaf_size': 23}. Best is trial 10 with value: 0.4153869058004327.
[I 2025-09-08 20:36:41,241] Trial 13 finished with value: 0.4153869058004327 and parameters: {'n_neighbors': 4, 'leaf_size': 28}. Best is trial 10 with value: 0.4153869058004327.
[I 2025-09-08 20:36:41,292] Trial 14 finished with value: 0.399331895845938 and parameters: {'n_neighbors': 5, 'leaf_size': 19}. Best is trial 10 with value: 0.4153869058004327.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:36:41,344] Trial 15 finished with value: 0.41489602400543557 and parameters: {'n_neighbors': 6, 'leaf_size': 31}. Best is trial 10 with value: 0.4153869058004327.
[I 2025-09-08 20:36:41,397] Trial 16 finished with value: 0.37102037030198604 and parameters: {'n_neighbors': 3, 'leaf_size': 18}. Best is trial 10 with value: 0.4153869058004327.
[I 2025-09-08 20:36:41,449] Trial 17 finished with value: 0.399331895845938 and parameters: {'n_neighbors': 5, 'leaf_size': 24}. Best is trial 10 with value: 0.4153869058004327.
[I 2025-09-08 20:36:41,500] Trial 18 finished with value: 0.4189245629773947 and parameters: {'n_neighbors': 7, 'leaf_size': 27}. Best is trial 18 with value: 0.4189245629773947.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:36:41,557] Trial 19 finished with value: 0.4189245629773947 and parameters: {'n_neighbors': 7, 'leaf_size': 38}. Best is trial 18 with value: 0.4189245629773947.
[I 2025-09-08 20:36:41,610] Trial 20 finished with value: 0.4189245629773947 and parameters: {'n_neighbors': 7, 'leaf_size': 40}. Best is trial 18 with value: 0.4189245629773947.
[I 2025-09-08 20:36:41,661] Trial 21 finished with value: 0.4189245629773947 and parameters: {'n_neighbors': 7, 'leaf_size': 40}. Best is trial 18 with value: 0.4189245629773947.
[I 2025-09-08 20:36:41,713] Trial 22 finished with value: 0.4189245629773947 and parameters: {'n_neighbors': 7, 'leaf_size': 40}. Best is trial 18 with value: 0.4189245629773947.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:36:41,768] Trial 23 finished with value: 0.40444441328102493 and parameters: {'n_neighbors': 8, 'leaf_size': 36}. Best is trial 18 with value: 0.4189245629773947.
[I 2025-09-08 20:36:41,821] Trial 24 finished with value: 0.41489602400543557 and parameters: {'n_neighbors': 6, 'leaf_size': 37}. Best is trial 18 with value: 0.4189245629773947.
[I 2025-09-08 20:36:41,871] Trial 25 finished with value: 0.4189245629773947 and parameters: {'n_neighbors': 7, 'leaf_size': 33}. Best is trial 18 with value: 0.4189245629773947.
[I 2025-09-08 20:36:41,921] Trial 26 finished with value: 0.40444441328102493 and parameters: {'n_neighbors': 8, 'leaf_size': 38}. Best is trial 18 with value: 0.4189245629773947.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:36:41,977] Trial 27 finished with value: 0.41489602400543557 and parameters: {'n_neighbors': 6, 'leaf_size': 34}. Best is trial 18 with value: 0.4189245629773947.
[I 2025-09-08 20:36:42,031] Trial 28 finished with value: 0.37415442198681986 and parameters: {'n_neighbors': 12, 'leaf_size': 29}. Best is trial 18 with value: 0.4189245629773947.
[I 2025-09-08 20:36:42,085] Trial 29 finished with value: 0.39234509423016806 and parameters: {'n_neighbors': 9, 'leaf_size': 30}. Best is trial 18 with value: 0.4189245629773947.
[I 2025-09-08 20:36:42,086] A new study created in memory with name: no-name-196f2474-5fd3-48ac-8807-a54b767526f9
[I 2025-09-08 20:36:42,128] Trial 0 finished with value: 0.1331145933344262 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: 0.1331145933344262.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

✅ KNN con TOA_3x3_depth_in_3_4 - Mejor R2: 0.42
📋 Parámetros: {'n_neighbors': 7, 'leaf_size': 27}

Buscando mejores hiperparámetros para LR con TOA_3x3_depth_in_3_4...
Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 20:36:42,184] Trial 1 finished with value: 0.3712890320434652 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 1 with value: 0.3712890320434652.
[I 2025-09-08 20:36:42,243] Trial 2 finished with value: 0.3712890320434652 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 1 with value: 0.3712890320434652.
[I 2025-09-08 20:36:42,302] Trial 3 finished with value: 0.37128903204347524 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 3 with value: 0.37128903204347524.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:36:42,361] Trial 4 finished with value: 0.37128903204347524 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 3 with value: 0.37128903204347524.
[I 2025-09-08 20:36:42,441] Trial 5 finished with value: 0.3712890320434652 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 3 with value: 0.37128903204347524.
[I 2025-09-08 20:36:42,507] Trial 6 finished with value: 0.37128903204347524 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 3 with value: 0.37128903204347524.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:36:42,574] Trial 7 finished with value: 0.1331145933344262 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 3 with value: 0.37128903204347524.
[I 2025-09-08 20:36:42,623] Trial 8 finished with value: 0.1331145933344262 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 3 with value: 0.37128903204347524.
[I 2025-09-08 20:36:42,668] Trial 9 finished with value: 0.1331145933344262 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 3 with value: 0.37128903204347524.
[I 2025-09-08 20:36:42,717] Trial 10 finished with value: 0.3712890320434652 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 3 with value: 0.37128903204347524.
[I 2025-09-08 20:36:42,776] Trial 11 finished with value: 0.37128903204347524 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 3 with value: 0.37128903204347524.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:36:42,841] Trial 12 finished with value: 0.37128903204347524 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 3 with value: 0.37128903204347524.
[I 2025-09-08 20:36:42,910] Trial 13 finished with value: 0.37128903204347524 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 3 with value: 0.37128903204347524.
[I 2025-09-08 20:36:42,971] Trial 14 finished with value: 0.37128903204347524 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 3 with value: 0.37128903204347524.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 20:36:43,043] Trial 15 finished with value: 0.37128903204347524 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 3 with value: 0.37128903204347524.
[I 2025-09-08 20:36:43,107] Trial 16 finished with value: 0.37128903204347524 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 3 with value: 0.37128903204347524.
[I 2025-09-08 20:36:43,169] Trial 17 finished with value: 0.37128903204347524 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 3 with value: 0.37128903204347524.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 20:36:43,231] Trial 18 finished with value: 0.13375489004103527 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 3 with value: 0.37128903204347524.
[I 2025-09-08 20:36:43,296] Trial 19 finished with value: 0.37128903204347524 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 3 with value: 0.37128903204347524.
[I 2025-09-08 20:36:43,363] Trial 20 finished with value: 0.37128903204347524 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 3 with value: 0.37128903204347524.

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:36:43,430] Trial 21 finished with value: 0.37128903204347524 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 3 with value: 0.37128903204347524.
[I 2025-09-08 20:36:43,508] Trial 22 finished with value: 0.37128903204347524 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 3 with value: 0.37128903204347524.
[I 2025-09-08 20:36:43,573] Trial 23 finished with value: 0.37128903204347524 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 3 with value: 0.37128903204347524.
[I 2025-09-08 20:36:43,639] Trial 24 finished with value: 0.37128903204347524 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 3 with value: 0.37128903204347524.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:36:43,709] Trial 25 finished with value: 0.37128903204347524 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 3 with value: 0.37128903204347524.
[I 2025-09-08 20:36:43,776] Trial 26 finished with value: 0.13375489004103527 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 3 with value: 0.37128903204347524.
[I 2025-09-08 20:36:43,834] Trial 27 finished with value: 0.37128903204347524 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 3 with value: 0.37128903204347524.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 20:36:43,940] Trial 28 finished with value: 0.37128903204347524 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 3 with value: 0.37128903204347524.
[I 2025-09-08 20:36:44,015] Trial 29 finished with value: 0.1331145933344262 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 3 with value: 0.37128903204347524.
[I 2025-09-08 20:36:44,016] A new study created in memory with name: no-name-272e8f3d-6c4b-4e34-be6e-dfb5bc4dff90

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

✅ LR con TOA_3x3_depth_in_3_4 - Mejor R2: 0.37
📋 Parámetros: {'fit_intercept': True, 'positive': False}

Buscando mejores hiperparámetros para RF con TOA_3x3_depth_in_3_4...
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:36:45,827] Trial 0 finished with value: 0.1096433826722139 and parameters: {'n_estimators': 100, 'max_depth': 9, 'min_samples_split': 7, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 0 with value: 0.1096433826722139.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:36:49,884] Trial 1 finished with value: 0.3405076454307922 and parameters: {'n_estimators': 400, 'max_depth': 8, 'min_samples_split': 6, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 1 with value: 0.3405076454307922.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:36:53,987] Trial 2 finished with value: 0.34871377695395966 and parameters: {'n_estimators': 400, 'max_depth': 7, 'min_samples_split': 7, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 2 with value: 0.34871377695395966.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:36:54,943] Trial 3 finished with value: 0.3156086979242661 and parameters: {'n_estimators': 100, 'max_depth': 12, 'min_samples_split': 5, 'min_samples_leaf': 7, 'bootstrap': True}. Best is trial 2 with value: 0.34871377695395966.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:37:01,615] Trial 4 finished with value: 0.1462331359192093 and parameters: {'n_estimators': 400, 'max_depth': 8, 'min_samples_split': 8, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 2 with value: 0.34871377695395966.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:37:04,303] Trial 5 finished with value: 0.1386476955615098 and parameters: {'n_estimators': 200, 'max_depth': 6, 'min_samples_split': 6, 'min_samples_leaf': 5, 'bootstrap': False}. Best is trial 2 with value: 0.34871377695395966.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:37:07,840] Trial 6 finished with value: 0.10877750842574248 and parameters: {'n_estimators': 200, 'max_depth': 9, 'min_samples_split': 7, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 2 with value: 0.34871377695395966.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:37:09,253] Trial 7 finished with value: 0.17165519474124058 and parameters: {'n_estimators': 100, 'max_depth': 7, 'min_samples_split': 4, 'min_samples_leaf': 7, 'bootstrap': False}. Best is trial 2 with value: 0.34871377695395966.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:37:15,704] Trial 8 finished with value: 0.11872607956600956 and parameters: {'n_estimators': 400, 'max_depth': 9, 'min_samples_split': 3, 'min_samples_leaf': 6, 'bootstrap': False}. Best is trial 2 with value: 0.34871377695395966.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:37:16,855] Trial 9 finished with value: 0.3686943241346674 and parameters: {'n_estimators': 100, 'max_depth': 8, 'min_samples_split': 4, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 9 with value: 0.3686943241346674.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:37:18,219] Trial 10 finished with value: 0.39218578960542677 and parameters: {'n_estimators': 100, 'max_depth': 11, 'min_samples_split': 2, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 10 with value: 0.39218578960542677.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:37:19,648] Trial 11 finished with value: 0.39218578960542677 and parameters: {'n_estimators': 100, 'max_depth': 11, 'min_samples_split': 2, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 10 with value: 0.39218578960542677.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:37:21,083] Trial 12 finished with value: 0.39149280643758555 and parameters: {'n_estimators': 100, 'max_depth': 12, 'min_samples_split': 2, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 10 with value: 0.39218578960542677.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:37:22,493] Trial 13 finished with value: 0.39218578960542677 and parameters: {'n_estimators': 100, 'max_depth': 11, 'min_samples_split': 2, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 10 with value: 0.39218578960542677.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:37:23,850] Trial 14 finished with value: 0.39218578960542677 and parameters: {'n_estimators': 100, 'max_depth': 11, 'min_samples_split': 3, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 10 with value: 0.39218578960542677.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:37:25,025] Trial 15 finished with value: 0.35829049400317986 and parameters: {'n_estimators': 100, 'max_depth': 10, 'min_samples_split': 2, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 10 with value: 0.39218578960542677.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:37:26,778] Trial 16 finished with value: 0.32188544603192526 and parameters: {'n_estimators': 200, 'max_depth': 11, 'min_samples_split': 3, 'min_samples_leaf': 8, 'bootstrap': True}. Best is trial 10 with value: 0.39218578960542677.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:37:27,924] Trial 17 finished with value: 0.35829049400317986 and parameters: {'n_estimators': 100, 'max_depth': 10, 'min_samples_split': 4, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 10 with value: 0.39218578960542677.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:37:28,872] Trial 18 finished with value: 0.34857805159512906 and parameters: {'n_estimators': 100, 'max_depth': 5, 'min_samples_split': 2, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 10 with value: 0.39218578960542677.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:37:31,127] Trial 19 finished with value: 0.3602798096789825 and parameters: {'n_estimators': 200, 'max_depth': 10, 'min_samples_split': 3, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 10 with value: 0.39218578960542677.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:37:32,473] Trial 20 finished with value: 0.3855974284000738 and parameters: {'n_estimators': 100, 'max_depth': 12, 'min_samples_split': 5, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 10 with value: 0.39218578960542677.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:37:33,896] Trial 21 finished with value: 0.39218578960542677 and parameters: {'n_estimators': 100, 'max_depth': 11, 'min_samples_split': 2, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 10 with value: 0.39218578960542677.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:37:35,223] Trial 22 finished with value: 0.3691670954783281 and parameters: {'n_estimators': 100, 'max_depth': 11, 'min_samples_split': 2, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 10 with value: 0.39218578960542677.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:37:36,552] Trial 23 finished with value: 0.39329183806433843 and parameters: {'n_estimators': 100, 'max_depth': 10, 'min_samples_split': 3, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 23 with value: 0.39329183806433843.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:37:37,774] Trial 24 finished with value: 0.37012997019104965 and parameters: {'n_estimators': 100, 'max_depth': 10, 'min_samples_split': 3, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 23 with value: 0.39329183806433843.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:37:39,099] Trial 25 finished with value: 0.39329183806433843 and parameters: {'n_estimators': 100, 'max_depth': 10, 'min_samples_split': 4, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 23 with value: 0.39329183806433843.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:37:40,322] Trial 26 finished with value: 0.37012997019104965 and parameters: {'n_estimators': 100, 'max_depth': 10, 'min_samples_split': 4, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 23 with value: 0.39329183806433843.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:37:41,449] Trial 27 finished with value: 0.35713911327741465 and parameters: {'n_estimators': 100, 'max_depth': 9, 'min_samples_split': 5, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 23 with value: 0.39329183806433843.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:37:45,406] Trial 28 finished with value: 0.33078161910531784 and parameters: {'n_estimators': 400, 'max_depth': 10, 'min_samples_split': 3, 'min_samples_leaf': 6, 'bootstrap': True}. Best is trial 23 with value: 0.39329183806433843.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:37:48,991] Trial 29 finished with value: 0.07663300717369619 and parameters: {'n_estimators': 200, 'max_depth': 9, 'min_samples_split': 4, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 23 with value: 0.39329183806433843.
[I 2025-09-08 20:37:48,992] A new study created in memory with name: no-name-a6d49337-21f0-4abd-ab91-93541c7d7368

✅ RF con TOA_3x3_depth_in_3_4 - Mejor R2: 0.39
📋 Parámetros: {'n_estimators': 100, 'max_depth': 10, 'min_samples_split': 3, 'min_samples_leaf': 2, 'bootstrap': True}

Buscando mejores hiperparámetros para CAT con TOA_3x3_depth_in_3_4...
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:37:52,512] Trial 0 finished with value: 0.4940373068163943 and parameters: {'iterations': 750, 'learning_rate': 0.05, 'depth': 6, 'l2_leaf_reg': 1.8323984384353755}. Best is trial 0 with value: 0.4940373068163943.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:37:54,059] Trial 1 finished with value: 0.4991999795296677 and parameters: {'iterations': 500, 'learning_rate': 0.04, 'depth': 5, 'l2_leaf_reg': 1.9196425343248533}. Best is trial 1 with value: 0.4991999795296677.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:37:55,923] Trial 2 finished with value: 0.4612633259288403 and parameters: {'iterations': 1000, 'learning_rate': 0.02, 'depth': 4, 'l2_leaf_reg': 1.425451469001581}. Best is trial 1 with value: 0.4991999795296677.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:38:21,340] Trial 3 finished with value: 0.5095861021672747 and parameters: {'iterations': 1000, 'learning_rate': 0.03, 'depth': 8, 'l2_leaf_reg': 1.7072268231933556}. Best is trial 3 with value: 0.5095861021672747.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:38:34,081] Trial 4 finished with value: 0.500125234508109 and parameters: {'iterations': 500, 'learning_rate': 0.05, 'depth': 8, 'l2_leaf_reg': 4.391188893440118}. Best is trial 3 with value: 0.5095861021672747.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:38:39,066] Trial 5 finished with value: 0.47385628422030696 and parameters: {'iterations': 500, 'learning_rate': 0.04, 'depth': 7, 'l2_leaf_reg': 4.883962609401156}. Best is trial 3 with value: 0.5095861021672747.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:38:41,374] Trial 6 finished with value: 0.4906113591795324 and parameters: {'iterations': 750, 'learning_rate': 0.03, 'depth': 5, 'l2_leaf_reg': 2.5081773737064297}. Best is trial 3 with value: 0.5095861021672747.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:38:44,522] Trial 7 finished with value: 0.4927560464831069 and parameters: {'iterations': 1000, 'learning_rate': 0.03, 'depth': 5, 'l2_leaf_reg': 1.5442032456987218}. Best is trial 3 with value: 0.5095861021672747.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:38:47,524] Trial 8 finished with value: 0.4848309216782965 and parameters: {'iterations': 1000, 'learning_rate': 0.03, 'depth': 5, 'l2_leaf_reg': 4.599950965503668}. Best is trial 3 with value: 0.5095861021672747.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:38:49,793] Trial 9 finished with value: 0.5172813649293747 and parameters: {'iterations': 500, 'learning_rate': 0.03, 'depth': 6, 'l2_leaf_reg': 1.750840500053684}. Best is trial 9 with value: 0.5172813649293747.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:38:54,875] Trial 10 finished with value: 0.4748520393200602 and parameters: {'iterations': 500, 'learning_rate': 0.02, 'depth': 7, 'l2_leaf_reg': 3.4049716999049604}. Best is trial 9 with value: 0.5172813649293747.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:39:20,223] Trial 11 finished with value: 0.4945881225721925 and parameters: {'iterations': 1000, 'learning_rate': 0.03, 'depth': 8, 'l2_leaf_reg': 1.0754977931286747}. Best is trial 9 with value: 0.5172813649293747.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:39:25,395] Trial 12 finished with value: 0.495490483021422 and parameters: {'iterations': 500, 'learning_rate': 0.03, 'depth': 7, 'l2_leaf_reg': 2.791814799131868}. Best is trial 9 with value: 0.5172813649293747.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:39:30,150] Trial 13 finished with value: 0.4965905266241754 and parameters: {'iterations': 1000, 'learning_rate': 0.03, 'depth': 6, 'l2_leaf_reg': 3.4472501705984087}. Best is trial 9 with value: 0.5172813649293747.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:39:37,781] Trial 14 finished with value: 0.5080130492015111 and parameters: {'iterations': 750, 'learning_rate': 0.03, 'depth': 7, 'l2_leaf_reg': 2.2693412214124935}. Best is trial 9 with value: 0.5172813649293747.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:39:50,512] Trial 15 finished with value: 0.4886830638298319 and parameters: {'iterations': 500, 'learning_rate': 0.03, 'depth': 8, 'l2_leaf_reg': 1.1117070200823909}. Best is trial 9 with value: 0.5172813649293747.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:39:55,207] Trial 16 finished with value: 0.4935304600576904 and parameters: {'iterations': 1000, 'learning_rate': 0.05, 'depth': 6, 'l2_leaf_reg': 2.1570944990759564}. Best is trial 9 with value: 0.5172813649293747.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:39:56,273] Trial 17 finished with value: 0.4297788746936238 and parameters: {'iterations': 500, 'learning_rate': 0.02, 'depth': 4, 'l2_leaf_reg': 3.3399840657757998}. Best is trial 9 with value: 0.5172813649293747.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:40:06,293] Trial 18 finished with value: 0.5028613694574897 and parameters: {'iterations': 1000, 'learning_rate': 0.04, 'depth': 7, 'l2_leaf_reg': 2.843242864713243}. Best is trial 9 with value: 0.5172813649293747.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:40:09,818] Trial 19 finished with value: 0.4911151198207106 and parameters: {'iterations': 750, 'learning_rate': 0.03, 'depth': 6, 'l2_leaf_reg': 3.9886202645623907}. Best is trial 9 with value: 0.5172813649293747.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:40:35,175] Trial 20 finished with value: 0.497575205565522 and parameters: {'iterations': 1000, 'learning_rate': 0.03, 'depth': 8, 'l2_leaf_reg': 1.5900918504684067}. Best is trial 9 with value: 0.5172813649293747.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:40:42,773] Trial 21 finished with value: 0.4970501523227216 and parameters: {'iterations': 750, 'learning_rate': 0.03, 'depth': 7, 'l2_leaf_reg': 2.229180804174101}. Best is trial 9 with value: 0.5172813649293747.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:40:50,444] Trial 22 finished with value: 0.50095720727779 and parameters: {'iterations': 750, 'learning_rate': 0.03, 'depth': 7, 'l2_leaf_reg': 2.416453082037454}. Best is trial 9 with value: 0.5172813649293747.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:41:09,467] Trial 23 finished with value: 0.4963695209846919 and parameters: {'iterations': 750, 'learning_rate': 0.03, 'depth': 8, 'l2_leaf_reg': 1.9676724034114552}. Best is trial 9 with value: 0.5172813649293747.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:41:16,943] Trial 24 finished with value: 0.5029558194021011 and parameters: {'iterations': 750, 'learning_rate': 0.03, 'depth': 7, 'l2_leaf_reg': 2.578461300428079}. Best is trial 9 with value: 0.5172813649293747.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:41:36,034] Trial 25 finished with value: 0.49496020900365484 and parameters: {'iterations': 750, 'learning_rate': 0.03, 'depth': 8, 'l2_leaf_reg': 1.3641155056396785}. Best is trial 9 with value: 0.5172813649293747.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:41:38,396] Trial 26 finished with value: 0.4932125061805084 and parameters: {'iterations': 500, 'learning_rate': 0.05, 'depth': 6, 'l2_leaf_reg': 1.8215467678470745}. Best is trial 9 with value: 0.5172813649293747.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:41:43,491] Trial 27 finished with value: 0.49303882770197777 and parameters: {'iterations': 500, 'learning_rate': 0.02, 'depth': 7, 'l2_leaf_reg': 2.1711918294174484}. Best is trial 9 with value: 0.5172813649293747.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:42:02,489] Trial 28 finished with value: 0.4872013031155517 and parameters: {'iterations': 750, 'learning_rate': 0.04, 'depth': 8, 'l2_leaf_reg': 3.1432710594977706}. Best is trial 9 with value: 0.5172813649293747.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:42:06,896] Trial 29 finished with value: 0.49283428888355285 and parameters: {'iterations': 1000, 'learning_rate': 0.05, 'depth': 6, 'l2_leaf_reg': 1.748906902269777}. Best is trial 9 with value: 0.5172813649293747.
[I 2025-09-08 20:42:06,897] A new study created in memory with name: no-name-1602d20c-7d26-4b8b-a746-c47422b057f6
[I 2025-09-08 20:42:06,960] Trial 0 finished with value: 0.24963672963770633 and parameters: {'alpha': 0.07015759743157389, 'l1_ratio': 0.27243704934306123}. Best is trial 0 with value: 0.24963672963770633.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.145e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.644e+00, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.031e+01, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 20:42:07,036] Trial 1 finished with value: 0.42754296041497936 and parameters: {'alpha': 0.004206961839982112, 'l1_ratio': 0.35139023625465193}. Best is trial 1 with value: 0.42754296041497936.
[I 2025-09-08 20:42:07,090] Trial 2 finished with value: 0.030550695047243098 and parameters: {'alpha': 0.621159414289676, 'l1_ratio': 0.6700205280989863}. Best is trial 1 with value: 0.42754296041497936.

✅ CAT con TOA_3x3_depth_in_3_4 - Mejor R2: 0.52
📋 Parámetros: {'iterations': 500, 'learning_rate': 0.03, 'depth': 6, 'l2_leaf_reg': 1.750840500053684}

Buscando mejores hiperparámetros para ELN con TOA_3x3_depth_in_3_4...
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.828e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.471e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.896e+01, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 20:42:07,180] Trial 3 finished with value: 0.4548129922734155 and parameters: {'alpha': 0.0006439418693841499, 'l1_ratio': 0.4661561243502582}. Best is trial 3 with value: 0.4548129922734155.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.079e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.366e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.958e+01, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 20:42:07,265] Trial 4 finished with value: 0.45287457439766915 and parameters: {'alpha': 0.0009697883197937345, 'l1_ratio': 0.6338638842150537}. Best is trial 3 with value: 0.4548129922734155.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:42:07,328] Trial 5 finished with value: 0.23754031967833775 and parameters: {'alpha': 0.08081447376581735, 'l1_ratio': 0.266872254328095}. Best is trial 3 with value: 0.4548129922734155.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.368e-02, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.579e-01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.909e-01, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 20:42:07,433] Trial 6 finished with value: 0.40761946414380645 and parameters: {'alpha': 0.006487743910192069, 'l1_ratio': 0.7699081488539268}. Best is trial 3 with value: 0.4548129922734155.
[I 2025-09-08 20:42:07,504] Trial 7 finished with value: 0.32430450186187854 and parameters: {'alpha': 0.01987543401795103, 'l1_ratio': 0.5844394978029805}. Best is trial 3 with value: 0.4548129922734155.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 20:42:07,610] Trial 8 finished with value: 0.3044074746254824 and parameters: {'alpha': 0.024077041742283783, 'l1_ratio': 0.5649272318046545}. Best is trial 3 with value: 0.4548129922734155.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.727e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.199e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.526e+01, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 20:42:07,713] Trial 9 finished with value: 0.45770020862957445 and parameters: {'alpha': 0.000257252533799908, 'l1_ratio': 0.5523119979340555}. Best is trial 9 with value: 0.45770020862957445.

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.263e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.799e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.058e+02, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 20:42:07,843] Trial 10 finished with value: 0.45810862392688056 and parameters: {'alpha': 0.00011043047347057365, 'l1_ratio': 0.10149070898223761}. Best is trial 10 with value: 0.45810862392688056.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.171e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.672e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.053e+02, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 20:42:07,966] Trial 11 finished with value: 0.458114318120367 and parameters: {'alpha': 0.00013134522758396385, 'l1_ratio': 0.1547223900375098}. Best is trial 11 with value: 0.458114318120367.

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.245e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.745e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.062e+02, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 20:42:08,088] Trial 12 finished with value: 0.45814016944845 and parameters: {'alpha': 0.00017237046413033072, 'l1_ratio': 0.1158867654037039}. Best is trial 12 with value: 0.45814016944845.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.808e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.524e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.890e+01, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 20:42:08,208] Trial 13 finished with value: 0.4494799269777967 and parameters: {'alpha': 0.0012253495610796239, 'l1_ratio': 0.10022466899868457}. Best is trial 12 with value: 0.45814016944845.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.870e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.300e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.036e+02, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 20:42:08,316] Trial 14 finished with value: 0.4576913845342199 and parameters: {'alpha': 0.00028351982143192154, 'l1_ratio': 0.20637274575247044}. Best is trial 12 with value: 0.45814016944845.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.795e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.184e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.022e+02, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 20:42:08,415] Trial 15 finished with value: 0.457940970722633 and parameters: {'alpha': 0.0001108295178381039, 'l1_ratio': 0.42725084633406607}. Best is trial 12 with value: 0.45814016944845.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.406e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.130e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.784e+01, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 20:42:08,520] Trial 16 finished with value: 0.43913782304634524 and parameters: {'alpha': 0.0027615849168056076, 'l1_ratio': 0.1805002637733688}. Best is trial 12 with value: 0.45814016944845.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.853e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.252e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.276e+01, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 20:42:08,617] Trial 17 finished with value: 0.45721032699882436 and parameters: {'alpha': 0.0003931835935072521, 'l1_ratio': 0.39776739224466195}. Best is trial 12 with value: 0.45814016944845.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:42:08,697] Trial 18 finished with value: 0.008441762592437155 and parameters: {'alpha': 0.8971689074010906, 'l1_ratio': 0.890355620803426}. Best is trial 12 with value: 0.45814016944845.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.971e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.996e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.131e+01, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 20:42:08,811] Trial 19 finished with value: 0.4460248992544713 and parameters: {'alpha': 0.0017798272497144094, 'l1_ratio': 0.3188679699497853}. Best is trial 12 with value: 0.45814016944845.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.166e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.680e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.051e+02, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 20:42:08,922] Trial 20 finished with value: 0.4580742018174225 and parameters: {'alpha': 0.00010751024038657019, 'l1_ratio': 0.16285812870013144}. Best is trial 12 with value: 0.45814016944845.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.218e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.749e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.053e+02, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 20:42:09,041] Trial 21 finished with value: 0.45807490631963893 and parameters: {'alpha': 0.00010041165635843547, 'l1_ratio': 0.12923517642526997}. Best is trial 12 with value: 0.45814016944845.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.762e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.208e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.030e+02, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 20:42:09,152] Trial 22 finished with value: 0.45773156705863394 and parameters: {'alpha': 0.00027419532624747026, 'l1_ratio': 0.23304242140591097}. Best is trial 12 with value: 0.45814016944845.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.324e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.653e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.039e+02, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 20:42:09,269] Trial 23 finished with value: 0.45563003752768055 and parameters: {'alpha': 0.0005698589636289106, 'l1_ratio': 0.10167515196056705}. Best is trial 12 with value: 0.45814016944845.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.038e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.513e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.049e+02, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 20:42:09,375] Trial 24 finished with value: 0.4580744641948151 and parameters: {'alpha': 0.0001865171513010392, 'l1_ratio': 0.1889885766558132}. Best is trial 12 with value: 0.45814016944845.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.137e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.449e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.073e+01, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 20:42:09,474] Trial 25 finished with value: 0.4561864445103397 and parameters: {'alpha': 0.0005435731188767138, 'l1_ratio': 0.29842398429848804}. Best is trial 12 with value: 0.45814016944845.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.139e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.624e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.056e+02, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 20:42:09,578] Trial 26 finished with value: 0.45810083945847735 and parameters: {'alpha': 0.00018282480670996272, 'l1_ratio': 0.15365256613578576}. Best is trial 12 with value: 0.45814016944845.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.596e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.546e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.257e+01, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 20:42:09,679] Trial 27 finished with value: 0.4440131047958296 and parameters: {'alpha': 0.001970527902296787, 'l1_ratio': 0.23813535160731752}. Best is trial 12 with value: 0.45814016944845.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.069e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.895e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.904e+01, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 20:42:09,773] Trial 28 finished with value: 0.4537076999843827 and parameters: {'alpha': 0.0008203546191131363, 'l1_ratio': 0.328781812910094}. Best is trial 12 with value: 0.45814016944845.
[I 2025-09-08 20:42:09,859] Trial 29 finished with value: 0.1891166402121689 and parameters: {'alpha': 0.13400738433945092, 'l1_ratio': 0.25702951419716424}. Best is trial 12 with value: 0.45814016944845.
[I 2025-09-08 20:42:09,861] A new study created in memory with name: no-name-805680cf-2ada-44ff-ac31-5ce106022d48

Fold 1
Fold 2
Fold 3

✅ ELN con TOA_3x3_depth_in_3_4 - Mejor R2: 0.46
📋 Parámetros: {'alpha': 0.00017237046413033072, 'l1_ratio': 0.1158867654037039}

Buscando mejores hiperparámetros para XGB con TOA_5x5_depth_in_3_4...
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:42:15,312] Trial 0 finished with value: 0.43593152843950467 and parameters: {'n_estimators': 1000, 'learning_rate': 0.02, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.7401301341098883, 'colsample_bytree': 0.6963621281916561}. Best is trial 0 with value: 0.43593152843950467.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:42:22,880] Trial 1 finished with value: 0.43031295627999516 and parameters: {'n_estimators': 1250, 'learning_rate': 0.03, 'max_depth': 8, 'min_child_weight': 2, 'subsample': 0.7459098566788445, 'colsample_bytree': 0.7298777106451049}. Best is trial 0 with value: 0.43593152843950467.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:42:29,490] Trial 2 finished with value: 0.41414200189613437 and parameters: {'n_estimators': 1250, 'learning_rate': 0.03, 'max_depth': 8, 'min_child_weight': 3, 'subsample': 0.7304921848533363, 'colsample_bytree': 0.7058351225989931}. Best is trial 0 with value: 0.43593152843950467.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:42:33,233] Trial 3 finished with value: 0.43905653952455026 and parameters: {'n_estimators': 750, 'learning_rate': 0.02, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.7646413645544305, 'colsample_bytree': 0.6618278066993036}. Best is trial 3 with value: 0.43905653952455026.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:42:37,341] Trial 4 finished with value: 0.42883340691741045 and parameters: {'n_estimators': 750, 'learning_rate': 0.02, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.7988485772762468, 'colsample_bytree': 0.6511986421267623}. Best is trial 3 with value: 0.43905653952455026.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:42:42,409] Trial 5 finished with value: 0.45001761548973124 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.7840973947575369, 'colsample_bytree': 0.7924535978368692}. Best is trial 5 with value: 0.45001761548973124.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:42:48,477] Trial 6 finished with value: 0.44989118486517743 and parameters: {'n_estimators': 1250, 'learning_rate': 0.01, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.755155816293291, 'colsample_bytree': 0.6081336860472085}. Best is trial 5 with value: 0.45001761548973124.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:42:52,677] Trial 7 finished with value: 0.43266139410947096 and parameters: {'n_estimators': 1000, 'learning_rate': 0.02, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.633702751132205, 'colsample_bytree': 0.6752256634592241}. Best is trial 5 with value: 0.45001761548973124.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:42:57,050] Trial 8 finished with value: 0.42464164509396607 and parameters: {'n_estimators': 1000, 'learning_rate': 0.03, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.7742402088898988, 'colsample_bytree': 0.6817376691643051}. Best is trial 5 with value: 0.45001761548973124.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:43:02,723] Trial 9 finished with value: 0.43545967465126184 and parameters: {'n_estimators': 1250, 'learning_rate': 0.03, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.6441677797231038, 'colsample_bytree': 0.6670057903462261}. Best is trial 5 with value: 0.45001761548973124.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:43:06,514] Trial 10 finished with value: 0.440154853466799 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.6898850711304207, 'colsample_bytree': 0.7957582159721378}. Best is trial 5 with value: 0.45001761548973124.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:43:12,603] Trial 11 finished with value: 0.44800406556564437 and parameters: {'n_estimators': 1250, 'learning_rate': 0.01, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.7076392310335785, 'colsample_bytree': 0.6093101454302107}. Best is trial 5 with value: 0.45001761548973124.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:43:19,828] Trial 12 finished with value: 0.4092667257093107 and parameters: {'n_estimators': 1250, 'learning_rate': 0.01, 'max_depth': 8, 'min_child_weight': 3, 'subsample': 0.7987696227303563, 'colsample_bytree': 0.7995031169770531}. Best is trial 5 with value: 0.45001761548973124.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:43:23,642] Trial 13 finished with value: 0.4374773989062298 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.6793629468433431, 'colsample_bytree': 0.7490050284179623}. Best is trial 5 with value: 0.45001761548973124.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:43:27,026] Trial 14 finished with value: 0.44961648160767154 and parameters: {'n_estimators': 750, 'learning_rate': 0.01, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.7685151383518389, 'colsample_bytree': 0.6004663023071766}. Best is trial 5 with value: 0.45001761548973124.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:43:31,813] Trial 15 finished with value: 0.44856798359263844 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.7136792309282476, 'colsample_bytree': 0.7655356940333147}. Best is trial 5 with value: 0.45001761548973124.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:43:38,590] Trial 16 finished with value: 0.44314457371404875 and parameters: {'n_estimators': 1250, 'learning_rate': 0.01, 'max_depth': 8, 'min_child_weight': 4, 'subsample': 0.7742576591693616, 'colsample_bytree': 0.6278874315690648}. Best is trial 5 with value: 0.45001761548973124.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:43:44,987] Trial 17 finished with value: 0.44815583128771275 and parameters: {'n_estimators': 1250, 'learning_rate': 0.01, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.6664509533778813, 'colsample_bytree': 0.7169879601864997}. Best is trial 5 with value: 0.45001761548973124.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:43:49,356] Trial 18 finished with value: 0.4573187953098823 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.6109235000701465, 'colsample_bytree': 0.6352537032113388}. Best is trial 18 with value: 0.4573187953098823.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:43:52,872] Trial 19 finished with value: 0.45587181823904305 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.6154099439627392, 'colsample_bytree': 0.6426146675443839}. Best is trial 18 with value: 0.4573187953098823.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:43:56,661] Trial 20 finished with value: 0.448143482585309 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.6054850049313784, 'colsample_bytree': 0.6396424681300918}. Best is trial 18 with value: 0.4573187953098823.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:44:00,213] Trial 21 finished with value: 0.45023721283623735 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.6027137913392961, 'colsample_bytree': 0.625968368119938}. Best is trial 18 with value: 0.4573187953098823.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:44:03,910] Trial 22 finished with value: 0.45445779211993126 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.6061109192937338, 'colsample_bytree': 0.6311239810370921}. Best is trial 18 with value: 0.4573187953098823.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:44:07,449] Trial 23 finished with value: 0.4560245913426694 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.626700906655835, 'colsample_bytree': 0.6423555017449665}. Best is trial 18 with value: 0.4573187953098823.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:44:11,151] Trial 24 finished with value: 0.457294763050154 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.6272650225918305, 'colsample_bytree': 0.6488241988801049}. Best is trial 18 with value: 0.4573187953098823.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:44:15,384] Trial 25 finished with value: 0.4487338742629903 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.6414334570987448, 'colsample_bytree': 0.6550518438918823}. Best is trial 18 with value: 0.4573187953098823.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:44:19,180] Trial 26 finished with value: 0.4560239184847405 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.6237839316823103, 'colsample_bytree': 0.6867405507222509}. Best is trial 18 with value: 0.4573187953098823.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:44:22,247] Trial 27 finished with value: 0.4434372210814395 and parameters: {'n_estimators': 750, 'learning_rate': 0.01, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.659610426082517, 'colsample_bytree': 0.6269473384978358}. Best is trial 18 with value: 0.4573187953098823.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:44:25,812] Trial 28 finished with value: 0.448472269651202 and parameters: {'n_estimators': 1000, 'learning_rate': 0.02, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.6605436986938649, 'colsample_bytree': 0.6449065686231331}. Best is trial 18 with value: 0.4573187953098823.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:44:30,193] Trial 29 finished with value: 0.4013079023607096 and parameters: {'n_estimators': 1000, 'learning_rate': 0.03, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.6215029300753491, 'colsample_bytree': 0.6949299945710071}. Best is trial 18 with value: 0.4573187953098823.
[I 2025-09-08 20:44:30,195] A new study created in memory with name: no-name-ca5b64d6-bc86-4f92-a782-e09cd212c606
[I 2025-09-08 20:44:30,341] Trial 0 finished with value: 0.4158931427054971 and parameters: {'learning_rate': 0.04, 'num_leaves': 30, 'max_depth': 5, 'min_child_samples': 6, 'subsample': 0.7794067362052111, 'colsample_bytree': 0.7189859842412559, 'n_estimators': 1250, 'min_split_gain': 0.5}. Best is trial 0 with value: 0.4158931427054971.

✅ XGB con TOA_5x5_depth_in_3_4 - Mejor R2: 0.46
📋 Parámetros: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.6109235000701465, 'colsample_bytree': 0.6352537032113388}

Buscando mejores hiperparámetros para LBM con TOA_5x5_depth_in_3_4...
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:44:30,982] Trial 1 finished with value: 0.3884947779396845 and parameters: {'learning_rate': 0.03, 'num_leaves': 30, 'max_depth': 8, 'min_child_samples': 6, 'subsample': 0.7731168526887883, 'colsample_bytree': 0.6371611174815188, 'n_estimators': 1250, 'min_split_gain': 0.0}. Best is trial 0 with value: 0.4158931427054971.

Fold 1
Fold 2

[I 2025-09-08 20:44:31,441] Trial 2 finished with value: 0.38116538043528986 and parameters: {'learning_rate': 0.03, 'num_leaves': 10, 'max_depth': 8, 'min_child_samples': 4, 'subsample': 0.7686436760814056, 'colsample_bytree': 0.7061627846272055, 'n_estimators': 1250, 'min_split_gain': 0.0}. Best is trial 0 with value: 0.4158931427054971.

Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:44:31,995] Trial 3 finished with value: 0.39567285976272765 and parameters: {'learning_rate': 0.02, 'num_leaves': 30, 'max_depth': 8, 'min_child_samples': 6, 'subsample': 0.686436451883546, 'colsample_bytree': 0.6472029573958454, 'n_estimators': 1000, 'min_split_gain': 0.0}. Best is trial 0 with value: 0.4158931427054971.
[I 2025-09-08 20:44:32,196] Trial 4 finished with value: 0.3404390195053176 and parameters: {'learning_rate': 0.03, 'num_leaves': 30, 'max_depth': 6, 'min_child_samples': 4, 'subsample': 0.6933491858173977, 'colsample_bytree': 0.7715025982578373, 'n_estimators': 1000, 'min_split_gain': 0.1}. Best is trial 0 with value: 0.4158931427054971.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:44:32,567] Trial 5 finished with value: 0.35486437042055047 and parameters: {'learning_rate': 0.03, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 4, 'subsample': 0.6503018269640978, 'colsample_bytree': 0.7728335997664393, 'n_estimators': 1000, 'min_split_gain': 0.0}. Best is trial 0 with value: 0.4158931427054971.
[I 2025-09-08 20:44:32,745] Trial 6 finished with value: 0.41904679979107257 and parameters: {'learning_rate': 0.03, 'num_leaves': 30, 'max_depth': 5, 'min_child_samples': 6, 'subsample': 0.7652289538046495, 'colsample_bytree': 0.6887884455863388, 'n_estimators': 1000, 'min_split_gain': 0.2}. Best is trial 6 with value: 0.41904679979107257.

Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 20:44:32,989] Trial 7 finished with value: 0.4371617591141294 and parameters: {'learning_rate': 0.02, 'num_leaves': 10, 'max_depth': 7, 'min_child_samples': 7, 'subsample': 0.670832590041, 'colsample_bytree': 0.662813892447312, 'n_estimators': 750, 'min_split_gain': 0.1}. Best is trial 7 with value: 0.4371617591141294.

Fold 2
Fold 3
Fold 1

[I 2025-09-08 20:44:33,176] Trial 8 finished with value: 0.4523404110330534 and parameters: {'learning_rate': 0.02, 'num_leaves': 20, 'max_depth': 8, 'min_child_samples': 8, 'subsample': 0.6292894134880107, 'colsample_bytree': 0.6526272612258303, 'n_estimators': 1250, 'min_split_gain': 1.0}. Best is trial 8 with value: 0.4523404110330534.

Fold 2
Fold 3
Fold 1

[I 2025-09-08 20:44:33,430] Trial 9 finished with value: 0.3760273459077832 and parameters: {'learning_rate': 0.02, 'num_leaves': 30, 'max_depth': 5, 'min_child_samples': 5, 'subsample': 0.6558003197878778, 'colsample_bytree': 0.669826826974282, 'n_estimators': 1000, 'min_split_gain': 0.1}. Best is trial 8 with value: 0.4523404110330534.

Fold 2
Fold 3
Fold 1

[I 2025-09-08 20:44:33,557] Trial 10 finished with value: 0.4689682548073379 and parameters: {'learning_rate': 0.05, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 8, 'subsample': 0.6003679646730424, 'colsample_bytree': 0.6057673613202854, 'n_estimators': 750, 'min_split_gain': 1.0}. Best is trial 10 with value: 0.4689682548073379.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:44:33,724] Trial 11 finished with value: 0.4689682548073379 and parameters: {'learning_rate': 0.05, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 8, 'subsample': 0.6170466494407482, 'colsample_bytree': 0.602043698138936, 'n_estimators': 750, 'min_split_gain': 1.0}. Best is trial 10 with value: 0.4689682548073379.
[I 2025-09-08 20:44:33,838] Trial 12 finished with value: 0.4689682548073379 and parameters: {'learning_rate': 0.05, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 8, 'subsample': 0.6071693392407919, 'colsample_bytree': 0.6047022436811721, 'n_estimators': 750, 'min_split_gain': 1.0}. Best is trial 10 with value: 0.4689682548073379.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:44:33,949] Trial 13 finished with value: 0.4689682548073379 and parameters: {'learning_rate': 0.05, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 8, 'subsample': 0.606973137767437, 'colsample_bytree': 0.610129269713575, 'n_estimators': 750, 'min_split_gain': 1.0}. Best is trial 10 with value: 0.4689682548073379.
[I 2025-09-08 20:44:34,061] Trial 14 finished with value: 0.4344144216812094 and parameters: {'learning_rate': 0.05, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 7, 'subsample': 0.729655015613172, 'colsample_bytree': 0.6258189620019067, 'n_estimators': 750, 'min_split_gain': 1.0}. Best is trial 10 with value: 0.4689682548073379.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:44:34,175] Trial 15 finished with value: 0.4311536832211155 and parameters: {'learning_rate': 0.05, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 7, 'subsample': 0.6309541494210662, 'colsample_bytree': 0.7344645206465297, 'n_estimators': 750, 'min_split_gain': 1.0}. Best is trial 10 with value: 0.4689682548073379.
[I 2025-09-08 20:44:34,325] Trial 16 finished with value: 0.46140503227257196 and parameters: {'learning_rate': 0.05, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 8, 'subsample': 0.7198315416755038, 'colsample_bytree': 0.6009199723662522, 'n_estimators': 750, 'min_split_gain': 0.2}. Best is trial 10 with value: 0.4689682548073379.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 20:44:34,482] Trial 17 finished with value: 0.4251704783976453 and parameters: {'learning_rate': 0.04, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 7, 'subsample': 0.6002278221969446, 'colsample_bytree': 0.7961207881091292, 'n_estimators': 750, 'min_split_gain': 0.5}. Best is trial 10 with value: 0.4689682548073379.
[I 2025-09-08 20:44:34,590] Trial 18 finished with value: 0.46027357326609253 and parameters: {'learning_rate': 0.05, 'num_leaves': 10, 'max_depth': 6, 'min_child_samples': 8, 'subsample': 0.6313746747077071, 'colsample_bytree': 0.6222779123851562, 'n_estimators': 750, 'min_split_gain': 1.0}. Best is trial 10 with value: 0.4689682548073379.

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 20:44:34,707] Trial 19 finished with value: 0.435402138918313 and parameters: {'learning_rate': 0.05, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 7, 'subsample': 0.6464125223796021, 'colsample_bytree': 0.6797475654935238, 'n_estimators': 750, 'min_split_gain': 1.0}. Best is trial 10 with value: 0.4689682548073379.
[I 2025-09-08 20:44:34,825] Trial 20 finished with value: 0.3704506046074078 and parameters: {'learning_rate': 0.05, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 5, 'subsample': 0.720005646455456, 'colsample_bytree': 0.6296797488277073, 'n_estimators': 750, 'min_split_gain': 1.0}. Best is trial 10 with value: 0.4689682548073379.

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 20:44:34,946] Trial 21 finished with value: 0.4689682548073379 and parameters: {'learning_rate': 0.05, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 8, 'subsample': 0.6134392289882112, 'colsample_bytree': 0.6038231817245335, 'n_estimators': 750, 'min_split_gain': 1.0}. Best is trial 10 with value: 0.4689682548073379.
[I 2025-09-08 20:44:35,066] Trial 22 finished with value: 0.4689682548073379 and parameters: {'learning_rate': 0.05, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 8, 'subsample': 0.6253898859803139, 'colsample_bytree': 0.6126438528738616, 'n_estimators': 750, 'min_split_gain': 1.0}. Best is trial 10 with value: 0.4689682548073379.

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 20:44:35,182] Trial 23 finished with value: 0.46076529206582206 and parameters: {'learning_rate': 0.05, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 8, 'subsample': 0.6150370648051033, 'colsample_bytree': 0.6401308609608339, 'n_estimators': 750, 'min_split_gain': 1.0}. Best is trial 10 with value: 0.4689682548073379.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:44:35,324] Trial 24 finished with value: 0.4512470208297101 and parameters: {'learning_rate': 0.04, 'num_leaves': 20, 'max_depth': 8, 'min_child_samples': 7, 'subsample': 0.6679406944642237, 'colsample_bytree': 0.6203240054021114, 'n_estimators': 750, 'min_split_gain': 0.5}. Best is trial 10 with value: 0.4689682548073379.
[I 2025-09-08 20:44:35,471] Trial 25 finished with value: 0.4464563802158585 and parameters: {'learning_rate': 0.05, 'num_leaves': 10, 'max_depth': 7, 'min_child_samples': 8, 'subsample': 0.6017313726471265, 'colsample_bytree': 0.6558981891200634, 'n_estimators': 750, 'min_split_gain': 0.2}. Best is trial 10 with value: 0.4689682548073379.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 20:44:35,587] Trial 26 finished with value: 0.4190488514819754 and parameters: {'learning_rate': 0.05, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 7, 'subsample': 0.7991842686184071, 'colsample_bytree': 0.6032994653250832, 'n_estimators': 750, 'min_split_gain': 1.0}. Best is trial 10 with value: 0.4689682548073379.
[I 2025-09-08 20:44:35,706] Trial 27 finished with value: 0.46076529206582206 and parameters: {'learning_rate': 0.05, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 8, 'subsample': 0.6398651783347188, 'colsample_bytree': 0.6348534718071908, 'n_estimators': 750, 'min_split_gain': 1.0}. Best is trial 10 with value: 0.4689682548073379.

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 20:44:35,830] Trial 28 finished with value: 0.4512346360534884 and parameters: {'learning_rate': 0.05, 'num_leaves': 20, 'max_depth': 8, 'min_child_samples': 8, 'subsample': 0.6178925171348875, 'colsample_bytree': 0.6161067819829258, 'n_estimators': 750, 'min_split_gain': 1.0}. Best is trial 10 with value: 0.4689682548073379.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:44:35,985] Trial 29 finished with value: 0.37531324136439004 and parameters: {'learning_rate': 0.04, 'num_leaves': 10, 'max_depth': 7, 'min_child_samples': 5, 'subsample': 0.6739368085250629, 'colsample_bytree': 0.7422808413314743, 'n_estimators': 1250, 'min_split_gain': 0.5}. Best is trial 10 with value: 0.4689682548073379.
[I 2025-09-08 20:44:35,987] A new study created in memory with name: no-name-7a410300-33d4-4dc8-8bfd-c7e46b4e5ae1
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

✅ LBM con TOA_5x5_depth_in_3_4 - Mejor R2: 0.47
📋 Parámetros: {'learning_rate': 0.05, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 8, 'subsample': 0.6003679646730424, 'colsample_bytree': 0.6057673613202854, 'n_estimators': 750, 'min_split_gain': 1.0}

Buscando mejores hiperparámetros para MLP con TOA_5x5_depth_in_3_4...
Fold 1
Fold 2

[I 2025-09-08 20:44:36,442] Trial 0 finished with value: 0.2708893196175344 and parameters: {'hidden_layer_sizes': (128,), 'activation': 'relu', 'solver': 'adam', 'alpha': 6.465427588764295e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0003716763233221732}. Best is trial 0 with value: 0.2708893196175344.

Fold 3
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 20:44:37,466] Trial 1 finished with value: 0.3075355451494993 and parameters: {'hidden_layer_sizes': (64,), 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.001439011647211839, 'learning_rate': 'constant', 'learning_rate_init': 0.0009313009670524931}. Best is trial 1 with value: 0.3075355451494993.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

[I 2025-09-08 20:44:37,937] Trial 2 finished with value: 0.4342186138282352 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'relu', 'solver': 'adam', 'alpha': 0.006728484518464565, 'learning_rate': 'constant', 'learning_rate_init': 0.0017943903100070446}. Best is trial 2 with value: 0.4342186138282352.

Fold 2
Fold 3
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 2

[I 2025-09-08 20:44:38,346] Trial 3 finished with value: 0.2334041377188256 and parameters: {'hidden_layer_sizes': (32,), 'activation': 'relu', 'solver': 'adam', 'alpha': 0.012790953627614619, 'learning_rate': 'constant', 'learning_rate_init': 0.006706623361412244}. Best is trial 2 with value: 0.4342186138282352.

Fold 3
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 20:44:39,163] Trial 4 finished with value: 0.2717244831752968 and parameters: {'hidden_layer_sizes': (32,), 'activation': 'relu', 'solver': 'adam', 'alpha': 0.001988207888670123, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0007787064022061616}. Best is trial 2 with value: 0.4342186138282352.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:44:39,680] Trial 5 finished with value: 0.15548638080698243 and parameters: {'hidden_layer_sizes': (128,), 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0011240423588510658, 'learning_rate': 'constant', 'learning_rate_init': 0.005279114941020746}. Best is trial 2 with value: 0.4342186138282352.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 20:44:40,746] Trial 6 finished with value: 0.14782603620810156 and parameters: {'hidden_layer_sizes': (64,), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.05335079138002441, 'learning_rate': 'constant', 'learning_rate_init': 0.00012776627360567758}. Best is trial 2 with value: 0.4342186138282352.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 20:44:41,574] Trial 7 finished with value: 0.29936303325112895 and parameters: {'hidden_layer_sizes': (32,), 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.006427252460474303, 'learning_rate': 'constant', 'learning_rate_init': 0.0016644259531105072}. Best is trial 2 with value: 0.4342186138282352.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 20:44:42,339] Trial 8 finished with value: -0.25159537168893337 and parameters: {'hidden_layer_sizes': (64,), 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.0015626253066321069, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00017866744490971834}. Best is trial 2 with value: 0.4342186138282352.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 20:44:43,500] Trial 9 finished with value: 0.36718853782715727 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.0013167781391683958, 'learning_rate': 'constant', 'learning_rate_init': 0.0007920161037258475}. Best is trial 2 with value: 0.4342186138282352.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

[I 2025-09-08 20:44:44,029] Trial 10 finished with value: 0.4648118078053933 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'relu', 'solver': 'adam', 'alpha': 8.036137037351823e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.002576099270693168}. Best is trial 10 with value: 0.4648118078053933.

Fold 2
Fold 3
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)
[I 2025-09-08 20:44:44,572] Trial 11 finished with value: 0.46702793461787406 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'relu', 'solver': 'adam', 'alpha': 7.084844521488146e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0028032941515024373}. Best is trial 11 with value: 0.46702793461787406.

Fold 2
Fold 3
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 20:44:45,180] Trial 12 finished with value: 0.4122636445457097 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'relu', 'solver': 'adam', 'alpha': 5.311287089916622e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.003158162124741806}. Best is trial 11 with value: 0.46702793461787406.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:44:45,935] Trial 13 finished with value: 0.42534931287125427 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'relu', 'solver': 'adam', 'alpha': 1.2843025572106863e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0031965912481362164}. Best is trial 11 with value: 0.46702793461787406.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2

[I 2025-09-08 20:44:46,339] Trial 14 finished with value: 0.4470104106681581 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'relu', 'solver': 'adam', 'alpha': 0.000194443438327746, 'learning_rate': 'adaptive', 'learning_rate_init': 0.008890389997967185}. Best is trial 11 with value: 0.46702793461787406.

Fold 3
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)
[I 2025-09-08 20:44:46,837] Trial 15 finished with value: 0.456302241332714 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0002240949545367108, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0022357496574149072}. Best is trial 11 with value: 0.46702793461787406.

Fold 2
Fold 3
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 2
Fold 3

[I 2025-09-08 20:44:47,392] Trial 16 finished with value: 0.4212370208857874 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'relu', 'solver': 'adam', 'alpha': 1.1731496185799362e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.003989561784812136}. Best is trial 11 with value: 0.46702793461787406.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 20:44:48,222] Trial 17 finished with value: 0.387158797397342 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'relu', 'solver': 'adam', 'alpha': 0.00026978352562224246, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0004407187760793014}. Best is trial 11 with value: 0.46702793461787406.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 3
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 20:44:49,617] Trial 18 finished with value: 0.3610708330527424 and parameters: {'hidden_layer_sizes': (128,), 'activation': 'tanh', 'solver': 'sgd', 'alpha': 6.167970938729293e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.001224948538134235}. Best is trial 11 with value: 0.46702793461787406.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

[I 2025-09-08 20:44:50,114] Trial 19 finished with value: 0.45306375920418657 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'relu', 'solver': 'adam', 'alpha': 3.159350006953164e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.002585940265156749}. Best is trial 11 with value: 0.46702793461787406.

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2

[I 2025-09-08 20:44:50,571] Trial 20 finished with value: 0.4511142894367288 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0004772364017402805, 'learning_rate': 'adaptive', 'learning_rate_init': 0.005335454408734467}. Best is trial 11 with value: 0.46702793461787406.

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

[I 2025-09-08 20:44:51,079] Trial 21 finished with value: 0.4533490360634393 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0001453874747496579, 'learning_rate': 'adaptive', 'learning_rate_init': 0.002082138299019761}. Best is trial 11 with value: 0.46702793461787406.

Fold 2
Fold 3
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 2
Fold 3

[I 2025-09-08 20:44:51,840] Trial 22 finished with value: 0.4368339868782978 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'relu', 'solver': 'adam', 'alpha': 0.00037918876964977466, 'learning_rate': 'adaptive', 'learning_rate_init': 0.001392484482346751}. Best is trial 11 with value: 0.46702793461787406.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2

[I 2025-09-08 20:44:52,350] Trial 23 finished with value: 0.4354815467324425 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'relu', 'solver': 'adam', 'alpha': 0.00012374688991877736, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0042062770084177435}. Best is trial 11 with value: 0.46702793461787406.

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

[I 2025-09-08 20:44:52,879] Trial 24 finished with value: 0.45867122602071647 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'relu', 'solver': 'adam', 'alpha': 2.9195748267007543e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0023897930234933903}. Best is trial 11 with value: 0.46702793461787406.

Fold 2
Fold 3
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 2
Fold 3

[I 2025-09-08 20:44:53,459] Trial 25 finished with value: 0.43705034671629245 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'relu', 'solver': 'adam', 'alpha': 2.551299962059521e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00800621083814789}. Best is trial 11 with value: 0.46702793461787406.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 20:44:54,742] Trial 26 finished with value: 0.3669048727985498 and parameters: {'hidden_layer_sizes': (128,), 'activation': 'tanh', 'solver': 'sgd', 'alpha': 2.2462852463608403e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0028571012869983295}. Best is trial 11 with value: 0.46702793461787406.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 20:44:55,435] Trial 27 finished with value: 0.22831341060283275 and parameters: {'hidden_layer_sizes': (64,), 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0005800804833311114, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0006029973591000066}. Best is trial 11 with value: 0.46702793461787406.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 20:44:55,894] Trial 28 finished with value: 0.23114488263243604 and parameters: {'hidden_layer_sizes': (32,), 'activation': 'relu', 'solver': 'adam', 'alpha': 9.014155786494e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.004264587793806154}. Best is trial 11 with value: 0.46702793461787406.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 3
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 20:44:56,445] Trial 29 finished with value: 0.24555424576843243 and parameters: {'hidden_layer_sizes': (128,), 'activation': 'relu', 'solver': 'adam', 'alpha': 5.65604987171475e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.001144770355886339}. Best is trial 11 with value: 0.46702793461787406.
[I 2025-09-08 20:44:56,449] A new study created in memory with name: no-name-99dca3b3-944d-4a7b-8d52-ac2c051bd960
[I 2025-09-08 20:44:56,544] Trial 0 finished with value: 0.5004364461954945 and parameters: {'C': 7.291821901513826, 'epsilon': 0.021201857582754467}. Best is trial 0 with value: 0.5004364461954945.
[I 2025-09-08 20:44:56,599] Trial 1 finished with value: 0.23526091769486726 and parameters: {'C': 0.9255449343434017, 'epsilon': 0.033348652316856964}. Best is trial 0 with value: 0.5004364461954945.

✅ MLP con TOA_5x5_depth_in_3_4 - Mejor R2: 0.47
📋 Parámetros: {'hidden_layer_sizes': (64, 16), 'activation': 'relu', 'solver': 'adam', 'alpha': 7.084844521488146e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0028032941515024373}

Buscando mejores hiperparámetros para SVR con TOA_5x5_depth_in_3_4...
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:44:56,649] Trial 2 finished with value: 0.09538475765977583 and parameters: {'C': 0.24240062014471098, 'epsilon': 0.1867283570683194}. Best is trial 0 with value: 0.5004364461954945.
[I 2025-09-08 20:44:56,710] Trial 3 finished with value: 0.5342087663287618 and parameters: {'C': 9.669601818814435, 'epsilon': 0.05413701488172285}. Best is trial 3 with value: 0.5342087663287618.
[I 2025-09-08 20:44:56,760] Trial 4 finished with value: 0.33508859310288397 and parameters: {'C': 1.528576836794701, 'epsilon': 0.15130049100299353}. Best is trial 3 with value: 0.5342087663287618.
[I 2025-09-08 20:44:56,811] Trial 5 finished with value: 0.1538299114230238 and parameters: {'C': 0.4915697053918197, 'epsilon': 0.10252545858835341}. Best is trial 3 with value: 0.5342087663287618.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:44:56,864] Trial 6 finished with value: 0.02095143643329315 and parameters: {'C': 0.17497339777759213, 'epsilon': 0.03072049232164946}. Best is trial 3 with value: 0.5342087663287618.
[I 2025-09-08 20:44:56,940] Trial 7 finished with value: 0.39682001904728326 and parameters: {'C': 2.441689206024051, 'epsilon': 0.05566637496487991}. Best is trial 3 with value: 0.5342087663287618.
[I 2025-09-08 20:44:56,999] Trial 8 finished with value: 0.037379416638775455 and parameters: {'C': 0.1493288071414002, 'epsilon': 0.18529352308934896}. Best is trial 3 with value: 0.5342087663287618.
[I 2025-09-08 20:44:57,052] Trial 9 finished with value: 0.445897246711132 and parameters: {'C': 4.081408524754711, 'epsilon': 0.15366556365533246}. Best is trial 3 with value: 0.5342087663287618.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 20:44:57,120] Trial 10 finished with value: 0.5265467747413176 and parameters: {'C': 8.5407775800686, 'epsilon': 0.08278903867095184}. Best is trial 3 with value: 0.5342087663287618.
[I 2025-09-08 20:44:57,186] Trial 11 finished with value: 0.5356270033022975 and parameters: {'C': 9.450154123987506, 'epsilon': 0.0801619012895185}. Best is trial 11 with value: 0.5356270033022975.
[I 2025-09-08 20:44:57,248] Trial 12 finished with value: 0.4444042724184289 and parameters: {'C': 4.039347470837841, 'epsilon': 0.06954682623886776}. Best is trial 11 with value: 0.5356270033022975.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 20:44:57,311] Trial 13 finished with value: 0.5348877460522652 and parameters: {'C': 9.33076387082021, 'epsilon': 0.11327931702944127}. Best is trial 11 with value: 0.5356270033022975.
[I 2025-09-08 20:44:57,376] Trial 14 finished with value: 0.45546691952077945 and parameters: {'C': 4.429623283411375, 'epsilon': 0.11353034246200179}. Best is trial 11 with value: 0.5356270033022975.
[I 2025-09-08 20:44:57,434] Trial 15 finished with value: 0.35979379060161465 and parameters: {'C': 1.7991092358950957, 'epsilon': 0.12913513731749157}. Best is trial 11 with value: 0.5356270033022975.
[I 2025-09-08 20:44:57,492] Trial 16 finished with value: 0.2012710245278296 and parameters: {'C': 0.6656949016779806, 'epsilon': 0.09206861222882097}. Best is trial 11 with value: 0.5356270033022975.

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:44:57,555] Trial 17 finished with value: 0.47553973039149544 and parameters: {'C': 5.327079889364573, 'epsilon': 0.1263090590926895}. Best is trial 11 with value: 0.5356270033022975.
[I 2025-09-08 20:44:57,616] Trial 18 finished with value: 0.4001978705222194 and parameters: {'C': 2.5944360717622477, 'epsilon': 0.1478611605936319}. Best is trial 11 with value: 0.5356270033022975.
[I 2025-09-08 20:44:57,678] Trial 19 finished with value: 0.4877907529361571 and parameters: {'C': 6.068131230971522, 'epsilon': 0.0823887111114606}. Best is trial 11 with value: 0.5356270033022975.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 20:44:57,741] Trial 20 finished with value: 0.40779688724249064 and parameters: {'C': 2.770547044510071, 'epsilon': 0.05404484515809414}. Best is trial 11 with value: 0.5356270033022975.
[I 2025-09-08 20:44:57,808] Trial 21 finished with value: 0.5232224662886712 and parameters: {'C': 8.601923432315921, 'epsilon': 0.05316130426391761}. Best is trial 11 with value: 0.5356270033022975.
[I 2025-09-08 20:44:57,871] Trial 22 finished with value: 0.538956023564992 and parameters: {'C': 9.938381984680884, 'epsilon': 0.07161097431454402}. Best is trial 22 with value: 0.538956023564992.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 20:44:57,934] Trial 23 finished with value: 0.4803103071492811 and parameters: {'C': 5.5771894021882895, 'epsilon': 0.10747918723272291}. Best is trial 22 with value: 0.538956023564992.
[I 2025-09-08 20:44:58,000] Trial 24 finished with value: 0.4359937987484425 and parameters: {'C': 3.6528900556485357, 'epsilon': 0.07393326337697018}. Best is trial 22 with value: 0.538956023564992.
[I 2025-09-08 20:44:58,061] Trial 25 finished with value: 0.5365148172369473 and parameters: {'C': 9.648378880787162, 'epsilon': 0.12250981195971236}. Best is trial 22 with value: 0.538956023564992.

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:44:58,120] Trial 26 finished with value: 0.12711597322229598 and parameters: {'C': 0.375717221698747, 'epsilon': 0.13303080228429584}. Best is trial 22 with value: 0.538956023564992.
[I 2025-09-08 20:44:58,181] Trial 27 finished with value: 0.3272546746542902 and parameters: {'C': 1.4678545123857918, 'epsilon': 0.17094992743638612}. Best is trial 22 with value: 0.538956023564992.
[I 2025-09-08 20:44:58,242] Trial 28 finished with value: 0.4997264829114862 and parameters: {'C': 6.5195100631571075, 'epsilon': 0.09550490348680156}. Best is trial 22 with value: 0.538956023564992.
[I 2025-09-08 20:44:58,304] Trial 29 finished with value: 0.4962078365971376 and parameters: {'C': 6.5953010660427935, 'epsilon': 0.07407271488931205}. Best is trial 22 with value: 0.538956023564992.
[I 2025-09-08 20:44:58,305] A new study created in memory with name: no-name-a1d1f041-1dd5-4a9d-9db8-79bb928101d6

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

✅ SVR con TOA_5x5_depth_in_3_4 - Mejor R2: 0.54
📋 Parámetros: {'C': 9.938381984680884, 'epsilon': 0.07161097431454402}

Buscando mejores hiperparámetros para KNN con TOA_5x5_depth_in_3_4...
Fold 1
Fold 2

[I 2025-09-08 20:44:58,351] Trial 0 finished with value: 0.4409592514807994 and parameters: {'n_neighbors': 3, 'leaf_size': 32}. Best is trial 0 with value: 0.4409592514807994.
[I 2025-09-08 20:44:58,399] Trial 1 finished with value: 0.4241994188212463 and parameters: {'n_neighbors': 7, 'leaf_size': 13}. Best is trial 0 with value: 0.4409592514807994.
[I 2025-09-08 20:44:58,443] Trial 2 finished with value: 0.4241994188212463 and parameters: {'n_neighbors': 7, 'leaf_size': 11}. Best is trial 0 with value: 0.4409592514807994.
[I 2025-09-08 20:44:58,487] Trial 3 finished with value: 0.4069282840750162 and parameters: {'n_neighbors': 8, 'leaf_size': 34}. Best is trial 0 with value: 0.4409592514807994.
[I 2025-09-08 20:44:58,530] Trial 4 finished with value: 0.39720612645984793 and parameters: {'n_neighbors': 9, 'leaf_size': 17}. Best is trial 0 with value: 0.4409592514807994.

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 20:44:58,605] Trial 5 finished with value: 0.4241994188212463 and parameters: {'n_neighbors': 7, 'leaf_size': 24}. Best is trial 0 with value: 0.4409592514807994.
[I 2025-09-08 20:44:58,670] Trial 6 finished with value: 0.3748251713684718 and parameters: {'n_neighbors': 11, 'leaf_size': 40}. Best is trial 0 with value: 0.4409592514807994.
[I 2025-09-08 20:44:58,714] Trial 7 finished with value: 0.4409592514807994 and parameters: {'n_neighbors': 3, 'leaf_size': 33}. Best is trial 0 with value: 0.4409592514807994.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:44:58,761] Trial 8 finished with value: 0.4335445707173031 and parameters: {'n_neighbors': 5, 'leaf_size': 27}. Best is trial 0 with value: 0.4409592514807994.
[I 2025-09-08 20:44:58,811] Trial 9 finished with value: 0.3625755211050756 and parameters: {'n_neighbors': 12, 'leaf_size': 37}. Best is trial 0 with value: 0.4409592514807994.
[I 2025-09-08 20:44:58,863] Trial 10 finished with value: 0.4451636487560163 and parameters: {'n_neighbors': 4, 'leaf_size': 27}. Best is trial 10 with value: 0.4451636487560163.
[I 2025-09-08 20:44:58,915] Trial 11 finished with value: 0.4409592514807994 and parameters: {'n_neighbors': 3, 'leaf_size': 27}. Best is trial 10 with value: 0.4451636487560163.
[I 2025-09-08 20:44:58,967] Trial 12 finished with value: 0.4335445707173031 and parameters: {'n_neighbors': 5, 'leaf_size': 22}. Best is trial 10 with value: 0.4451636487560163.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:44:59,023] Trial 13 finished with value: 0.4335445707173031 and parameters: {'n_neighbors': 5, 'leaf_size': 30}. Best is trial 10 with value: 0.4451636487560163.
[I 2025-09-08 20:44:59,074] Trial 14 finished with value: 0.4451636487560163 and parameters: {'n_neighbors': 4, 'leaf_size': 20}. Best is trial 10 with value: 0.4451636487560163.
[I 2025-09-08 20:44:59,126] Trial 15 finished with value: 0.4335445707173031 and parameters: {'n_neighbors': 5, 'leaf_size': 19}. Best is trial 10 with value: 0.4451636487560163.
[I 2025-09-08 20:44:59,178] Trial 16 finished with value: 0.4451636487560163 and parameters: {'n_neighbors': 4, 'leaf_size': 19}. Best is trial 10 with value: 0.4451636487560163.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:44:59,234] Trial 17 finished with value: 0.4318430624744578 and parameters: {'n_neighbors': 6, 'leaf_size': 16}. Best is trial 10 with value: 0.4451636487560163.
[I 2025-09-08 20:44:59,285] Trial 18 finished with value: 0.39200767063491887 and parameters: {'n_neighbors': 10, 'leaf_size': 22}. Best is trial 10 with value: 0.4451636487560163.
[I 2025-09-08 20:44:59,339] Trial 19 finished with value: 0.4451636487560163 and parameters: {'n_neighbors': 4, 'leaf_size': 28}. Best is trial 10 with value: 0.4451636487560163.
[I 2025-09-08 20:44:59,389] Trial 20 finished with value: 0.4318430624744578 and parameters: {'n_neighbors': 6, 'leaf_size': 24}. Best is trial 10 with value: 0.4451636487560163.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:44:59,443] Trial 21 finished with value: 0.4451636487560163 and parameters: {'n_neighbors': 4, 'leaf_size': 19}. Best is trial 10 with value: 0.4451636487560163.
[I 2025-09-08 20:44:59,498] Trial 22 finished with value: 0.4451636487560163 and parameters: {'n_neighbors': 4, 'leaf_size': 20}. Best is trial 10 with value: 0.4451636487560163.
[I 2025-09-08 20:44:59,549] Trial 23 finished with value: 0.4451636487560163 and parameters: {'n_neighbors': 4, 'leaf_size': 15}. Best is trial 10 with value: 0.4451636487560163.
[I 2025-09-08 20:44:59,601] Trial 24 finished with value: 0.4318430624744578 and parameters: {'n_neighbors': 6, 'leaf_size': 22}. Best is trial 10 with value: 0.4451636487560163.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:44:59,655] Trial 25 finished with value: 0.4409592514807994 and parameters: {'n_neighbors': 3, 'leaf_size': 25}. Best is trial 10 with value: 0.4451636487560163.
[I 2025-09-08 20:44:59,708] Trial 26 finished with value: 0.4451636487560163 and parameters: {'n_neighbors': 4, 'leaf_size': 10}. Best is trial 10 with value: 0.4451636487560163.
[I 2025-09-08 20:44:59,759] Trial 27 finished with value: 0.4318430624744578 and parameters: {'n_neighbors': 6, 'leaf_size': 18}. Best is trial 10 with value: 0.4451636487560163.
[I 2025-09-08 20:44:59,810] Trial 28 finished with value: 0.4069282840750162 and parameters: {'n_neighbors': 8, 'leaf_size': 29}. Best is trial 10 with value: 0.4451636487560163.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:44:59,864] Trial 29 finished with value: 0.4409592514807994 and parameters: {'n_neighbors': 3, 'leaf_size': 14}. Best is trial 10 with value: 0.4451636487560163.
[I 2025-09-08 20:44:59,865] A new study created in memory with name: no-name-eeabc02a-2b56-4684-8b66-359741e33a45
[I 2025-09-08 20:44:59,922] Trial 0 finished with value: 0.37987142006221547 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 0 with value: 0.37987142006221547.
[I 2025-09-08 20:44:59,980] Trial 1 finished with value: 0.37987142006221547 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 0 with value: 0.37987142006221547.

Fold 1
Fold 2
Fold 3

✅ KNN con TOA_5x5_depth_in_3_4 - Mejor R2: 0.45
📋 Parámetros: {'n_neighbors': 4, 'leaf_size': 27}

Buscando mejores hiperparámetros para LR con TOA_5x5_depth_in_3_4...
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:45:00,036] Trial 2 finished with value: 0.13925598276448806 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: 0.37987142006221547.
[I 2025-09-08 20:45:00,088] Trial 3 finished with value: 0.13925598276449555 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 0 with value: 0.37987142006221547.
[I 2025-09-08 20:45:00,187] Trial 4 finished with value: 0.37987142006221547 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 0 with value: 0.37987142006221547.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:45:00,243] Trial 5 finished with value: 0.13925598276448806 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: 0.37987142006221547.
[I 2025-09-08 20:45:00,305] Trial 6 finished with value: 0.37987142006221547 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 0 with value: 0.37987142006221547.
[I 2025-09-08 20:45:00,362] Trial 7 finished with value: 0.37987142006221547 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 0 with value: 0.37987142006221547.
[I 2025-09-08 20:45:00,416] Trial 8 finished with value: 0.13925598276449555 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 0 with value: 0.37987142006221547.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 20:45:00,463] Trial 9 finished with value: 0.13925598276449555 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 0 with value: 0.37987142006221547.
[I 2025-09-08 20:45:00,527] Trial 10 finished with value: 0.37987142006235647 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 10 with value: 0.37987142006235647.
[I 2025-09-08 20:45:00,587] Trial 11 finished with value: 0.37987142006235647 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 10 with value: 0.37987142006235647.
[I 2025-09-08 20:45:00,647] Trial 12 finished with value: 0.37987142006235647 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 10 with value: 0.37987142006235647.

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:45:00,721] Trial 13 finished with value: 0.37987142006235647 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 10 with value: 0.37987142006235647.
[I 2025-09-08 20:45:00,793] Trial 14 finished with value: 0.37987142006235647 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 10 with value: 0.37987142006235647.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:45:00,855] Trial 15 finished with value: 0.37987142006235647 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 10 with value: 0.37987142006235647.
[I 2025-09-08 20:45:00,924] Trial 16 finished with value: 0.37987142006235647 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 10 with value: 0.37987142006235647.
[I 2025-09-08 20:45:00,983] Trial 17 finished with value: 0.37987142006235647 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 10 with value: 0.37987142006235647.
[I 2025-09-08 20:45:01,046] Trial 18 finished with value: 0.37987142006235647 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 10 with value: 0.37987142006235647.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 20:45:01,113] Trial 19 finished with value: 0.37987142006235647 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 10 with value: 0.37987142006235647.
[I 2025-09-08 20:45:01,183] Trial 20 finished with value: 0.37987142006235647 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 10 with value: 0.37987142006235647.
[I 2025-09-08 20:45:01,245] Trial 21 finished with value: 0.37987142006235647 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 10 with value: 0.37987142006235647.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 20:45:01,307] Trial 22 finished with value: 0.37987142006235647 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 10 with value: 0.37987142006235647.
[I 2025-09-08 20:45:01,377] Trial 23 finished with value: 0.37987142006235647 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 10 with value: 0.37987142006235647.
[I 2025-09-08 20:45:01,444] Trial 24 finished with value: 0.37987142006235647 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 10 with value: 0.37987142006235647.

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:45:01,513] Trial 25 finished with value: 0.37987142006235647 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 10 with value: 0.37987142006235647.
[I 2025-09-08 20:45:01,575] Trial 26 finished with value: 0.13925598276449555 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 10 with value: 0.37987142006235647.
[I 2025-09-08 20:45:01,631] Trial 27 finished with value: 0.37987142006235647 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 10 with value: 0.37987142006235647.
[I 2025-09-08 20:45:01,687] Trial 28 finished with value: 0.37987142006235647 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 10 with value: 0.37987142006235647.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 20:45:01,759] Trial 29 finished with value: 0.37987142006235647 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 10 with value: 0.37987142006235647.
[I 2025-09-08 20:45:01,761] A new study created in memory with name: no-name-b9747594-9241-4f52-994e-66cdab8db2b3

Fold 3

✅ LR con TOA_5x5_depth_in_3_4 - Mejor R2: 0.38
📋 Parámetros: {'fit_intercept': False, 'positive': False}

Buscando mejores hiperparámetros para RF con TOA_5x5_depth_in_3_4...
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:45:02,923] Trial 0 finished with value: 0.3577423644709121 and parameters: {'n_estimators': 100, 'max_depth': 12, 'min_samples_split': 6, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 0 with value: 0.3577423644709121.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:45:06,263] Trial 1 finished with value: 0.22906114088985743 and parameters: {'n_estimators': 200, 'max_depth': 8, 'min_samples_split': 7, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 0 with value: 0.3577423644709121.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:45:08,035] Trial 2 finished with value: 0.23455245662161486 and parameters: {'n_estimators': 100, 'max_depth': 9, 'min_samples_split': 6, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 0 with value: 0.3577423644709121.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:45:12,851] Trial 3 finished with value: 0.38967489795384697 and parameters: {'n_estimators': 400, 'max_depth': 9, 'min_samples_split': 6, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 3 with value: 0.38967489795384697.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:45:14,363] Trial 4 finished with value: 0.20350563744729142 and parameters: {'n_estimators': 100, 'max_depth': 9, 'min_samples_split': 4, 'min_samples_leaf': 8, 'bootstrap': False}. Best is trial 3 with value: 0.38967489795384697.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:45:15,790] Trial 5 finished with value: 0.21138961003034215 and parameters: {'n_estimators': 100, 'max_depth': 6, 'min_samples_split': 8, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 3 with value: 0.38967489795384697.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:45:18,181] Trial 6 finished with value: 0.19678862123244636 and parameters: {'n_estimators': 200, 'max_depth': 5, 'min_samples_split': 4, 'min_samples_leaf': 4, 'bootstrap': False}. Best is trial 3 with value: 0.38967489795384697.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:45:19,240] Trial 7 finished with value: 0.3710538460125414 and parameters: {'n_estimators': 100, 'max_depth': 7, 'min_samples_split': 6, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 3 with value: 0.38967489795384697.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:45:24,016] Trial 8 finished with value: 0.19720795618995354 and parameters: {'n_estimators': 400, 'max_depth': 5, 'min_samples_split': 4, 'min_samples_leaf': 4, 'bootstrap': False}. Best is trial 3 with value: 0.38967489795384697.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:45:26,076] Trial 9 finished with value: 0.35389441319077264 and parameters: {'n_estimators': 200, 'max_depth': 11, 'min_samples_split': 6, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 3 with value: 0.38967489795384697.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:45:29,735] Trial 10 finished with value: 0.3360822742492838 and parameters: {'n_estimators': 400, 'max_depth': 10, 'min_samples_split': 2, 'min_samples_leaf': 7, 'bootstrap': True}. Best is trial 3 with value: 0.38967489795384697.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:45:34,302] Trial 11 finished with value: 0.3635511891634972 and parameters: {'n_estimators': 400, 'max_depth': 8, 'min_samples_split': 8, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 3 with value: 0.38967489795384697.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:45:38,648] Trial 12 finished with value: 0.39099916901922355 and parameters: {'n_estimators': 400, 'max_depth': 7, 'min_samples_split': 5, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 12 with value: 0.39099916901922355.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:45:42,373] Trial 13 finished with value: 0.3383488021449666 and parameters: {'n_estimators': 400, 'max_depth': 7, 'min_samples_split': 5, 'min_samples_leaf': 6, 'bootstrap': True}. Best is trial 12 with value: 0.39099916901922355.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:45:47,491] Trial 14 finished with value: 0.4059044802419604 and parameters: {'n_estimators': 400, 'max_depth': 10, 'min_samples_split': 2, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 14 with value: 0.4059044802419604.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:45:51,626] Trial 15 finished with value: 0.3496724885374882 and parameters: {'n_estimators': 400, 'max_depth': 11, 'min_samples_split': 2, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 14 with value: 0.4059044802419604.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:45:55,982] Trial 16 finished with value: 0.39415487784887215 and parameters: {'n_estimators': 400, 'max_depth': 7, 'min_samples_split': 3, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 14 with value: 0.4059044802419604.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:46:00,721] Trial 17 finished with value: 0.38462284908608196 and parameters: {'n_estimators': 400, 'max_depth': 10, 'min_samples_split': 3, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 14 with value: 0.4059044802419604.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:46:04,237] Trial 18 finished with value: 0.33323745660360143 and parameters: {'n_estimators': 400, 'max_depth': 6, 'min_samples_split': 3, 'min_samples_leaf': 6, 'bootstrap': True}. Best is trial 14 with value: 0.4059044802419604.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:46:08,659] Trial 19 finished with value: 0.35938977775657904 and parameters: {'n_estimators': 400, 'max_depth': 10, 'min_samples_split': 3, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 14 with value: 0.4059044802419604.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:46:11,302] Trial 20 finished with value: 0.4136798399419109 and parameters: {'n_estimators': 200, 'max_depth': 12, 'min_samples_split': 2, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 20 with value: 0.4136798399419109.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:46:13,932] Trial 21 finished with value: 0.4136798399419109 and parameters: {'n_estimators': 200, 'max_depth': 12, 'min_samples_split': 2, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 20 with value: 0.4136798399419109.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:46:16,325] Trial 22 finished with value: 0.3844971034153251 and parameters: {'n_estimators': 200, 'max_depth': 12, 'min_samples_split': 2, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 20 with value: 0.4136798399419109.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:46:18,922] Trial 23 finished with value: 0.41560321920707005 and parameters: {'n_estimators': 200, 'max_depth': 11, 'min_samples_split': 2, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 23 with value: 0.41560321920707005.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:46:21,335] Trial 24 finished with value: 0.3844971034153251 and parameters: {'n_estimators': 200, 'max_depth': 12, 'min_samples_split': 2, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 23 with value: 0.41560321920707005.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:46:23,932] Trial 25 finished with value: 0.41560321920707005 and parameters: {'n_estimators': 200, 'max_depth': 11, 'min_samples_split': 3, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 23 with value: 0.41560321920707005.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:46:26,309] Trial 26 finished with value: 0.38635874694622624 and parameters: {'n_estimators': 200, 'max_depth': 11, 'min_samples_split': 3, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 23 with value: 0.41560321920707005.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:46:28,936] Trial 27 finished with value: 0.41560321920707005 and parameters: {'n_estimators': 200, 'max_depth': 11, 'min_samples_split': 4, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 23 with value: 0.41560321920707005.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:46:31,142] Trial 28 finished with value: 0.36459338265091673 and parameters: {'n_estimators': 200, 'max_depth': 11, 'min_samples_split': 4, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 23 with value: 0.41560321920707005.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:46:33,077] Trial 29 finished with value: 0.34006229442937297 and parameters: {'n_estimators': 200, 'max_depth': 11, 'min_samples_split': 5, 'min_samples_leaf': 6, 'bootstrap': True}. Best is trial 23 with value: 0.41560321920707005.
[I 2025-09-08 20:46:33,079] A new study created in memory with name: no-name-04418fa3-1328-43d3-ad10-ac52c6acfab4

✅ RF con TOA_5x5_depth_in_3_4 - Mejor R2: 0.42
📋 Parámetros: {'n_estimators': 200, 'max_depth': 11, 'min_samples_split': 2, 'min_samples_leaf': 2, 'bootstrap': True}

Buscando mejores hiperparámetros para CAT con TOA_5x5_depth_in_3_4...
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:46:36,561] Trial 0 finished with value: 0.5127123518098088 and parameters: {'iterations': 750, 'learning_rate': 0.02, 'depth': 6, 'l2_leaf_reg': 2.7913072884794623}. Best is trial 0 with value: 0.5127123518098088.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:46:44,156] Trial 1 finished with value: 0.5357961937239747 and parameters: {'iterations': 750, 'learning_rate': 0.02, 'depth': 7, 'l2_leaf_reg': 1.9596252484385346}. Best is trial 1 with value: 0.5357961937239747.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:47:03,136] Trial 2 finished with value: 0.5291582934102733 and parameters: {'iterations': 750, 'learning_rate': 0.04, 'depth': 8, 'l2_leaf_reg': 2.7311411288445293}. Best is trial 1 with value: 0.5357961937239747.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:47:04,114] Trial 3 finished with value: 0.5092514637833016 and parameters: {'iterations': 500, 'learning_rate': 0.04, 'depth': 4, 'l2_leaf_reg': 1.0178430165128791}. Best is trial 1 with value: 0.5357961937239747.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:47:08,776] Trial 4 finished with value: 0.50932601596605 and parameters: {'iterations': 1000, 'learning_rate': 0.05, 'depth': 6, 'l2_leaf_reg': 2.8781769687110836}. Best is trial 1 with value: 0.5357961937239747.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:47:16,345] Trial 5 finished with value: 0.5132256984898409 and parameters: {'iterations': 750, 'learning_rate': 0.05, 'depth': 7, 'l2_leaf_reg': 4.080127939724686}. Best is trial 1 with value: 0.5357961937239747.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:47:41,870] Trial 6 finished with value: 0.5298996212644204 and parameters: {'iterations': 1000, 'learning_rate': 0.03, 'depth': 8, 'l2_leaf_reg': 1.4242457208699126}. Best is trial 1 with value: 0.5357961937239747.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:47:43,496] Trial 7 finished with value: 0.48685560987921844 and parameters: {'iterations': 750, 'learning_rate': 0.05, 'depth': 4, 'l2_leaf_reg': 3.2124226870790773}. Best is trial 1 with value: 0.5357961937239747.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:47:44,664] Trial 8 finished with value: 0.4748681315369982 and parameters: {'iterations': 500, 'learning_rate': 0.05, 'depth': 4, 'l2_leaf_reg': 3.329754968423144}. Best is trial 1 with value: 0.5357961937239747.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:47:49,486] Trial 9 finished with value: 0.509568798541817 and parameters: {'iterations': 1000, 'learning_rate': 0.02, 'depth': 6, 'l2_leaf_reg': 4.030788711359003}. Best is trial 1 with value: 0.5357961937239747.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:47:57,048] Trial 10 finished with value: 0.5320586264314702 and parameters: {'iterations': 750, 'learning_rate': 0.02, 'depth': 7, 'l2_leaf_reg': 1.788663548156866}. Best is trial 1 with value: 0.5357961937239747.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:48:04,787] Trial 11 finished with value: 0.5373079911947092 and parameters: {'iterations': 750, 'learning_rate': 0.02, 'depth': 7, 'l2_leaf_reg': 1.9185513747174787}. Best is trial 11 with value: 0.5373079911947092.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:48:12,425] Trial 12 finished with value: 0.5343306729920574 and parameters: {'iterations': 750, 'learning_rate': 0.02, 'depth': 7, 'l2_leaf_reg': 2.0392559145819553}. Best is trial 11 with value: 0.5373079911947092.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:48:14,852] Trial 13 finished with value: 0.5026897229678113 and parameters: {'iterations': 750, 'learning_rate': 0.02, 'depth': 5, 'l2_leaf_reg': 2.2379719035356866}. Best is trial 11 with value: 0.5373079911947092.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:48:22,436] Trial 14 finished with value: 0.5155797440503318 and parameters: {'iterations': 750, 'learning_rate': 0.03, 'depth': 7, 'l2_leaf_reg': 4.765785565597804}. Best is trial 11 with value: 0.5373079911947092.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:48:34,997] Trial 15 finished with value: 0.5228227399420531 and parameters: {'iterations': 500, 'learning_rate': 0.02, 'depth': 8, 'l2_leaf_reg': 1.3888400128167937}. Best is trial 11 with value: 0.5373079911947092.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:48:37,256] Trial 16 finished with value: 0.5076413429407146 and parameters: {'iterations': 750, 'learning_rate': 0.02, 'depth': 5, 'l2_leaf_reg': 2.1108421528858954}. Best is trial 11 with value: 0.5373079911947092.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:48:45,071] Trial 17 finished with value: 0.5246761763595821 and parameters: {'iterations': 750, 'learning_rate': 0.02, 'depth': 7, 'l2_leaf_reg': 2.3921204779882714}. Best is trial 11 with value: 0.5373079911947092.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:48:48,017] Trial 18 finished with value: 0.5309145979757474 and parameters: {'iterations': 1000, 'learning_rate': 0.04, 'depth': 5, 'l2_leaf_reg': 1.7675755717073494}. Best is trial 11 with value: 0.5373079911947092.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:49:00,782] Trial 19 finished with value: 0.5319483845744486 and parameters: {'iterations': 500, 'learning_rate': 0.03, 'depth': 8, 'l2_leaf_reg': 1.0101175958207367}. Best is trial 11 with value: 0.5373079911947092.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:49:04,387] Trial 20 finished with value: 0.522143231574893 and parameters: {'iterations': 750, 'learning_rate': 0.02, 'depth': 6, 'l2_leaf_reg': 2.4649384773236367}. Best is trial 11 with value: 0.5373079911947092.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:49:11,995] Trial 21 finished with value: 0.5312347054238638 and parameters: {'iterations': 750, 'learning_rate': 0.02, 'depth': 7, 'l2_leaf_reg': 1.8327292908483055}. Best is trial 11 with value: 0.5373079911947092.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:49:19,632] Trial 22 finished with value: 0.5355941397240201 and parameters: {'iterations': 750, 'learning_rate': 0.02, 'depth': 7, 'l2_leaf_reg': 1.4179989862888318}. Best is trial 11 with value: 0.5373079911947092.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:49:27,273] Trial 23 finished with value: 0.5335809741968225 and parameters: {'iterations': 750, 'learning_rate': 0.02, 'depth': 7, 'l2_leaf_reg': 1.2829964105767802}. Best is trial 11 with value: 0.5373079911947092.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:49:30,767] Trial 24 finished with value: 0.5313667326487969 and parameters: {'iterations': 750, 'learning_rate': 0.02, 'depth': 6, 'l2_leaf_reg': 1.5804972484172959}. Best is trial 11 with value: 0.5373079911947092.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:49:49,888] Trial 25 finished with value: 0.5286688761584194 and parameters: {'iterations': 750, 'learning_rate': 0.02, 'depth': 8, 'l2_leaf_reg': 1.9939548180560878}. Best is trial 11 with value: 0.5373079911947092.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:49:57,613] Trial 26 finished with value: 0.5357782050921922 and parameters: {'iterations': 750, 'learning_rate': 0.02, 'depth': 7, 'l2_leaf_reg': 1.5751503510340887}. Best is trial 11 with value: 0.5373079911947092.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:50:01,212] Trial 27 finished with value: 0.5190058571977025 and parameters: {'iterations': 750, 'learning_rate': 0.03, 'depth': 6, 'l2_leaf_reg': 2.5474854389195163}. Best is trial 11 with value: 0.5373079911947092.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:50:11,342] Trial 28 finished with value: 0.5268125904062098 and parameters: {'iterations': 1000, 'learning_rate': 0.04, 'depth': 7, 'l2_leaf_reg': 3.352516260054234}. Best is trial 11 with value: 0.5373079911947092.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:50:23,985] Trial 29 finished with value: 0.5073367883636329 and parameters: {'iterations': 500, 'learning_rate': 0.02, 'depth': 8, 'l2_leaf_reg': 2.688866546142883}. Best is trial 11 with value: 0.5373079911947092.
[I 2025-09-08 20:50:23,986] A new study created in memory with name: no-name-52183b09-4a50-4b83-a0f4-d892d942dfbf
[I 2025-09-08 20:50:24,041] Trial 0 finished with value: 0.29652903663410696 and parameters: {'alpha': 0.027880103043655523, 'l1_ratio': 0.41882118613590424}. Best is trial 0 with value: 0.29652903663410696.
[I 2025-09-08 20:50:24,108] Trial 1 finished with value: 0.3241429687051722 and parameters: {'alpha': 0.016071585312209858, 'l1_ratio': 0.7868935669972551}. Best is trial 1 with value: 0.3241429687051722.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.561e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.942e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(

✅ CAT con TOA_5x5_depth_in_3_4 - Mejor R2: 0.54
📋 Parámetros: {'iterations': 750, 'learning_rate': 0.02, 'depth': 7, 'l2_leaf_reg': 1.9185513747174787}

Buscando mejores hiperparámetros para ELN con TOA_5x5_depth_in_3_4...
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.031e+02, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 20:50:24,192] Trial 2 finished with value: 0.46915842707723615 and parameters: {'alpha': 0.00012100470695601038, 'l1_ratio': 0.6189821000350977}. Best is trial 2 with value: 0.46915842707723615.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.402e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.270e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.179e+01, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 20:50:24,282] Trial 3 finished with value: 0.42662126839176245 and parameters: {'alpha': 0.0033743159155191003, 'l1_ratio': 0.2977255640888804}. Best is trial 2 with value: 0.46915842707723615.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.271e-01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 20:50:24,365] Trial 4 finished with value: 0.3295701992400764 and parameters: {'alpha': 0.02497921550742014, 'l1_ratio': 0.24916271739317813}. Best is trial 2 with value: 0.46915842707723615.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.399e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.934e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.374e+01, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 20:50:24,453] Trial 5 finished with value: 0.45357981903745026 and parameters: {'alpha': 0.0014652269132109086, 'l1_ratio': 0.8735797314173669}. Best is trial 2 with value: 0.46915842707723615.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.206e+00, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.202e+00, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.955e+00, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 20:50:24,539] Trial 6 finished with value: 0.3743861367133496 and parameters: {'alpha': 0.012519935058863646, 'l1_ratio': 0.2312773944921303}. Best is trial 2 with value: 0.46915842707723615.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.873e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.812e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.484e+01, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 20:50:24,624] Trial 7 finished with value: 0.46081511524989655 and parameters: {'alpha': 0.0007371491415328287, 'l1_ratio': 0.893637770422669}. Best is trial 2 with value: 0.46915842707723615.

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.882e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.823e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.509e+01, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 20:50:24,716] Trial 8 finished with value: 0.4610808780412789 and parameters: {'alpha': 0.0007205475991959297, 'l1_ratio': 0.8953470334145738}. Best is trial 2 with value: 0.46915842707723615.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.987e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.976e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.473e+01, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 20:50:24,806] Trial 9 finished with value: 0.44580898285535947 and parameters: {'alpha': 0.0014644368599975677, 'l1_ratio': 0.38249231735006894}. Best is trial 2 with value: 0.46915842707723615.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.612e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.980e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.034e+02, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 20:50:24,946] Trial 10 finished with value: 0.46929750633855455 and parameters: {'alpha': 0.00011124020954553836, 'l1_ratio': 0.6186793396311554}. Best is trial 10 with value: 0.46929750633855455.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.564e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.948e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.032e+02, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 20:50:25,067] Trial 11 finished with value: 0.46906140991832884 and parameters: {'alpha': 0.00012563148903809064, 'l1_ratio': 0.5996046554395904}. Best is trial 10 with value: 0.46929750633855455.
[I 2025-09-08 20:50:25,197] Trial 12 finished with value: 0.011321272217779232 and parameters: {'alpha': 0.8970080528776228, 'l1_ratio': 0.6137615905934553}. Best is trial 10 with value: 0.46929750633855455.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.637e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.998e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.035e+02, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 20:50:25,301] Trial 13 finished with value: 0.4694265344738458 and parameters: {'alpha': 0.00010205026076068682, 'l1_ratio': 0.635667342179087}. Best is trial 13 with value: 0.4694265344738458.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.850e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.531e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.826e+01, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 20:50:25,432] Trial 14 finished with value: 0.4677034363795505 and parameters: {'alpha': 0.00021249701129746277, 'l1_ratio': 0.6803996598143321}. Best is trial 13 with value: 0.4694265344738458.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:50:25,539] Trial 15 finished with value: 0.10757974693709227 and parameters: {'alpha': 0.13972186844918963, 'l1_ratio': 0.4844633954415078}. Best is trial 13 with value: 0.4694265344738458.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.696e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.940e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.675e+01, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 20:50:25,665] Trial 16 finished with value: 0.46471148859586214 and parameters: {'alpha': 0.00037315805050802214, 'l1_ratio': 0.7144686104893906}. Best is trial 13 with value: 0.4694265344738458.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.476e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.700e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.180e+01, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 20:50:25,765] Trial 17 finished with value: 0.42020272378448226 and parameters: {'alpha': 0.004624646482264277, 'l1_ratio': 0.1051497090521949}. Best is trial 13 with value: 0.4694265344738458.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.429e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.376e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.359e+01, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 20:50:25,883] Trial 18 finished with value: 0.46445527631033584 and parameters: {'alpha': 0.00037301876262394904, 'l1_ratio': 0.5159147435665916}. Best is trial 13 with value: 0.4694265344738458.
[I 2025-09-08 20:50:25,975] Trial 19 finished with value: 0.11281866019493854 and parameters: {'alpha': 0.10201162450517376, 'l1_ratio': 0.7577987226717889}. Best is trial 13 with value: 0.4694265344738458.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.559e+00, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.692e+00, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.498e+00, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 20:50:26,104] Trial 20 finished with value: 0.4189208465314311 and parameters: {'alpha': 0.003906842039306688, 'l1_ratio': 0.5304443067616114}. Best is trial 13 with value: 0.4694265344738458.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.545e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.921e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.028e+02, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 20:50:26,230] Trial 21 finished with value: 0.4692514022494992 and parameters: {'alpha': 0.00011660255665121189, 'l1_ratio': 0.6512661458876401}. Best is trial 13 with value: 0.4694265344738458.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.600e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.963e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.031e+02, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 20:50:26,347] Trial 22 finished with value: 0.46942430732295803 and parameters: {'alpha': 0.00010360600346531927, 'l1_ratio': 0.6625741861135056}. Best is trial 13 with value: 0.4694265344738458.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.446e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.800e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.441e+01, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 20:50:26,454] Trial 23 finished with value: 0.46503238152070364 and parameters: {'alpha': 0.00036496709359402083, 'l1_ratio': 0.804881707195259}. Best is trial 13 with value: 0.4694265344738458.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.901e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.625e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.919e+01, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 20:50:26,596] Trial 24 finished with value: 0.46695240869725496 and parameters: {'alpha': 0.0002444865645161714, 'l1_ratio': 0.5681590593662327}. Best is trial 13 with value: 0.4694265344738458.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.034e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.779e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.584e+01, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 20:50:26,804] Trial 25 finished with value: 0.45567360520430994 and parameters: {'alpha': 0.00079072331827801, 'l1_ratio': 0.4396256250036469}. Best is trial 13 with value: 0.4694265344738458.

Fold 3
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.540e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.905e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.025e+02, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 20:50:26,943] Trial 26 finished with value: 0.46948198518568623 and parameters: {'alpha': 0.00010195997442902021, 'l1_ratio': 0.725926746425225}. Best is trial 26 with value: 0.46948198518568623.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.547e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.382e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.596e+01, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 20:50:27,059] Trial 27 finished with value: 0.46719826637864287 and parameters: {'alpha': 0.0002388967314779598, 'l1_ratio': 0.7137101840299527}. Best is trial 26 with value: 0.46948198518568623.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.705e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.463e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.795e+01, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 20:50:27,148] Trial 28 finished with value: 0.45472782723692323 and parameters: {'alpha': 0.0012835519055085737, 'l1_ratio': 0.8285536701379084}. Best is trial 26 with value: 0.46948198518568623.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:50:27,229] Trial 29 finished with value: 0.16892043962354522 and parameters: {'alpha': 0.06122031786209828, 'l1_ratio': 0.736741926323812}. Best is trial 26 with value: 0.46948198518568623.
[I 2025-09-08 20:50:27,231] A new study created in memory with name: no-name-6c00e745-9c4c-4d13-a1b9-d73c05cf6abe

Fold 1
Fold 2
Fold 3

✅ ELN con TOA_5x5_depth_in_3_4 - Mejor R2: 0.47
📋 Parámetros: {'alpha': 0.00010195997442902021, 'l1_ratio': 0.725926746425225}

Buscando mejores hiperparámetros para XGB con C2X-Complex_rhow_5x5_depth_in_3_4...
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:50:31,073] Trial 0 finished with value: 0.3883729482058515 and parameters: {'n_estimators': 1000, 'learning_rate': 0.03, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.6599669024924719, 'colsample_bytree': 0.6575453974163075}. Best is trial 0 with value: 0.3883729482058515.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:50:36,524] Trial 1 finished with value: 0.4243193854658947 and parameters: {'n_estimators': 1250, 'learning_rate': 0.02, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.7962530274326373, 'colsample_bytree': 0.601756491115214}. Best is trial 1 with value: 0.4243193854658947.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:50:42,366] Trial 2 finished with value: 0.41153782230257113 and parameters: {'n_estimators': 1000, 'learning_rate': 0.02, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.6921048359455668, 'colsample_bytree': 0.712452164895749}. Best is trial 1 with value: 0.4243193854658947.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:50:49,106] Trial 3 finished with value: 0.42663852883912695 and parameters: {'n_estimators': 1250, 'learning_rate': 0.01, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.6531908174881197, 'colsample_bytree': 0.6218625088700507}. Best is trial 3 with value: 0.42663852883912695.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:50:53,016] Trial 4 finished with value: 0.40236699665056314 and parameters: {'n_estimators': 1000, 'learning_rate': 0.02, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.6576704335005329, 'colsample_bytree': 0.6452763701098443}. Best is trial 3 with value: 0.42663852883912695.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:50:56,371] Trial 5 finished with value: 0.42801662366994564 and parameters: {'n_estimators': 750, 'learning_rate': 0.01, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.6783740163869652, 'colsample_bytree': 0.6426167584883035}. Best is trial 5 with value: 0.42801662366994564.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:51:02,081] Trial 6 finished with value: 0.41683282291214874 and parameters: {'n_estimators': 1250, 'learning_rate': 0.03, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.6401997238778159, 'colsample_bytree': 0.622021699740146}. Best is trial 5 with value: 0.42801662366994564.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:51:06,236] Trial 7 finished with value: 0.43795311999199704 and parameters: {'n_estimators': 750, 'learning_rate': 0.03, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.7424655197056466, 'colsample_bytree': 0.7699617394011313}. Best is trial 7 with value: 0.43795311999199704.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:51:09,000] Trial 8 finished with value: 0.43858580342726555 and parameters: {'n_estimators': 750, 'learning_rate': 0.03, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.7445746494271623, 'colsample_bytree': 0.7266784217732185}. Best is trial 8 with value: 0.43858580342726555.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:51:15,502] Trial 9 finished with value: 0.43369416291380025 and parameters: {'n_estimators': 1250, 'learning_rate': 0.03, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.7532304068959211, 'colsample_bytree': 0.7262846068111997}. Best is trial 8 with value: 0.43858580342726555.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:51:18,304] Trial 10 finished with value: 0.43814903975377284 and parameters: {'n_estimators': 750, 'learning_rate': 0.03, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.7303788695476298, 'colsample_bytree': 0.7879785985707932}. Best is trial 8 with value: 0.43858580342726555.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:51:21,114] Trial 11 finished with value: 0.43935748886135295 and parameters: {'n_estimators': 750, 'learning_rate': 0.03, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.7304145113582423, 'colsample_bytree': 0.7910846717757103}. Best is trial 11 with value: 0.43935748886135295.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:51:24,508] Trial 12 finished with value: 0.42570092473839694 and parameters: {'n_estimators': 750, 'learning_rate': 0.03, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.7776615821530815, 'colsample_bytree': 0.7460112225434814}. Best is trial 11 with value: 0.43935748886135295.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:51:27,141] Trial 13 finished with value: 0.38759738844788183 and parameters: {'n_estimators': 750, 'learning_rate': 0.03, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.6036279195229085, 'colsample_bytree': 0.7505399214655251}. Best is trial 11 with value: 0.43935748886135295.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:51:31,096] Trial 14 finished with value: 0.40968190490556705 and parameters: {'n_estimators': 750, 'learning_rate': 0.03, 'max_depth': 8, 'min_child_weight': 4, 'subsample': 0.7154716984016424, 'colsample_bytree': 0.6855777131708127}. Best is trial 11 with value: 0.43935748886135295.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:51:34,392] Trial 15 finished with value: 0.45197223679738113 and parameters: {'n_estimators': 750, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.7608551337282232, 'colsample_bytree': 0.7940075085416106}. Best is trial 15 with value: 0.45197223679738113.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:51:37,345] Trial 16 finished with value: 0.44436774183330047 and parameters: {'n_estimators': 750, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.7687101851821673, 'colsample_bytree': 0.7969371016167923}. Best is trial 15 with value: 0.45197223679738113.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:51:42,373] Trial 17 finished with value: 0.44829000575738975 and parameters: {'n_estimators': 750, 'learning_rate': 0.01, 'max_depth': 8, 'min_child_weight': 3, 'subsample': 0.7743958973382176, 'colsample_bytree': 0.7962542113100866}. Best is trial 15 with value: 0.45197223679738113.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:51:47,231] Trial 18 finished with value: 0.447197159996334 and parameters: {'n_estimators': 750, 'learning_rate': 0.01, 'max_depth': 8, 'min_child_weight': 3, 'subsample': 0.7898194003735894, 'colsample_bytree': 0.7657147512119495}. Best is trial 15 with value: 0.45197223679738113.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:51:53,437] Trial 19 finished with value: 0.43670638408480905 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 8, 'min_child_weight': 3, 'subsample': 0.7641146616024193, 'colsample_bytree': 0.6873563843891776}. Best is trial 15 with value: 0.45197223679738113.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:51:58,261] Trial 20 finished with value: 0.4470503231735708 and parameters: {'n_estimators': 750, 'learning_rate': 0.01, 'max_depth': 8, 'min_child_weight': 3, 'subsample': 0.7006391177305054, 'colsample_bytree': 0.7696022639701974}. Best is trial 15 with value: 0.45197223679738113.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:52:03,257] Trial 21 finished with value: 0.45335185811315154 and parameters: {'n_estimators': 750, 'learning_rate': 0.01, 'max_depth': 8, 'min_child_weight': 3, 'subsample': 0.7997412885839525, 'colsample_bytree': 0.7711838422623002}. Best is trial 21 with value: 0.45335185811315154.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:52:08,137] Trial 22 finished with value: 0.4475403014225283 and parameters: {'n_estimators': 750, 'learning_rate': 0.01, 'max_depth': 8, 'min_child_weight': 3, 'subsample': 0.7834026090599288, 'colsample_bytree': 0.7813526412655334}. Best is trial 21 with value: 0.45335185811315154.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:52:12,371] Trial 23 finished with value: 0.4526109502242452 and parameters: {'n_estimators': 750, 'learning_rate': 0.01, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.798977215432707, 'colsample_bytree': 0.7988293479212178}. Best is trial 21 with value: 0.45335185811315154.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:52:16,760] Trial 24 finished with value: 0.44765746784627886 and parameters: {'n_estimators': 750, 'learning_rate': 0.01, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.7921300841384736, 'colsample_bytree': 0.7623952733864926}. Best is trial 21 with value: 0.45335185811315154.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:52:21,805] Trial 25 finished with value: 0.455297810248491 and parameters: {'n_estimators': 750, 'learning_rate': 0.01, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.7983608440866793, 'colsample_bytree': 0.7417627791029254}. Best is trial 25 with value: 0.455297810248491.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:52:26,704] Trial 26 finished with value: 0.45247984434122795 and parameters: {'n_estimators': 750, 'learning_rate': 0.01, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.7972613408779472, 'colsample_bytree': 0.7408461600114071}. Best is trial 25 with value: 0.455297810248491.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:52:31,682] Trial 27 finished with value: 0.4562455211712515 and parameters: {'n_estimators': 750, 'learning_rate': 0.01, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.7986527867691257, 'colsample_bytree': 0.7355712952557141}. Best is trial 27 with value: 0.4562455211712515.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:52:37,702] Trial 28 finished with value: 0.4289760616361578 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.7757843307827023, 'colsample_bytree': 0.7125888143886925}. Best is trial 27 with value: 0.4562455211712515.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:52:46,450] Trial 29 finished with value: 0.43153195117808957 and parameters: {'n_estimators': 1250, 'learning_rate': 0.02, 'max_depth': 8, 'min_child_weight': 2, 'subsample': 0.7563007463652502, 'colsample_bytree': 0.7330346495324719}. Best is trial 27 with value: 0.4562455211712515.
[I 2025-09-08 20:52:46,452] A new study created in memory with name: no-name-8270d38b-8267-4f74-b916-cd7c513565f3
[I 2025-09-08 20:52:46,632] Trial 0 finished with value: 0.37973151712343317 and parameters: {'learning_rate': 0.04, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 6, 'subsample': 0.7422261370386586, 'colsample_bytree': 0.7965652943180408, 'n_estimators': 1250, 'min_split_gain': 0.1}. Best is trial 0 with value: 0.37973151712343317.

✅ XGB con C2X-Complex_rhow_5x5_depth_in_3_4 - Mejor R2: 0.46
📋 Parámetros: {'n_estimators': 750, 'learning_rate': 0.01, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.7986527867691257, 'colsample_bytree': 0.7355712952557141}

Buscando mejores hiperparámetros para LBM con C2X-Complex_rhow_5x5_depth_in_3_4...
Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 20:52:46,823] Trial 1 finished with value: 0.3904459180553197 and parameters: {'learning_rate': 0.03, 'num_leaves': 30, 'max_depth': 6, 'min_child_samples': 7, 'subsample': 0.7758585265136272, 'colsample_bytree': 0.7378045991243384, 'n_estimators': 1000, 'min_split_gain': 0.2}. Best is trial 1 with value: 0.3904459180553197.

Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 20:52:47,017] Trial 2 finished with value: 0.37293237135282414 and parameters: {'learning_rate': 0.03, 'num_leaves': 20, 'max_depth': 8, 'min_child_samples': 5, 'subsample': 0.7838125076027175, 'colsample_bytree': 0.7230276642361604, 'n_estimators': 750, 'min_split_gain': 0.1}. Best is trial 1 with value: 0.3904459180553197.
[I 2025-09-08 20:52:47,154] Trial 3 finished with value: 0.40724039384884425 and parameters: {'learning_rate': 0.02, 'num_leaves': 10, 'max_depth': 7, 'min_child_samples': 6, 'subsample': 0.6550935968883399, 'colsample_bytree': 0.6639559566058518, 'n_estimators': 750, 'min_split_gain': 1.0}. Best is trial 3 with value: 0.40724039384884425.

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 20:52:47,378] Trial 4 finished with value: 0.3835475351568487 and parameters: {'learning_rate': 0.02, 'num_leaves': 30, 'max_depth': 7, 'min_child_samples': 7, 'subsample': 0.6780386718924363, 'colsample_bytree': 0.6507223955054968, 'n_estimators': 750, 'min_split_gain': 0.2}. Best is trial 3 with value: 0.40724039384884425.

Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 20:52:47,513] Trial 5 finished with value: 0.38832906921287 and parameters: {'learning_rate': 0.05, 'num_leaves': 30, 'max_depth': 7, 'min_child_samples': 5, 'subsample': 0.7318643655544916, 'colsample_bytree': 0.6102637480491359, 'n_estimators': 1000, 'min_split_gain': 0.5}. Best is trial 3 with value: 0.40724039384884425.

Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:52:48,170] Trial 6 finished with value: 0.40661364136635836 and parameters: {'learning_rate': 0.05, 'num_leaves': 30, 'max_depth': 7, 'min_child_samples': 4, 'subsample': 0.7030757827639678, 'colsample_bytree': 0.6211268198838767, 'n_estimators': 1250, 'min_split_gain': 0.0}. Best is trial 3 with value: 0.40724039384884425.
[I 2025-09-08 20:52:48,311] Trial 7 finished with value: 0.37555477401280496 and parameters: {'learning_rate': 0.05, 'num_leaves': 30, 'max_depth': 6, 'min_child_samples': 5, 'subsample': 0.6119990013856241, 'colsample_bytree': 0.6639744736883616, 'n_estimators': 1000, 'min_split_gain': 0.2}. Best is trial 3 with value: 0.40724039384884425.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:52:48,406] Trial 8 finished with value: 0.38059387668832256 and parameters: {'learning_rate': 0.05, 'num_leaves': 30, 'max_depth': 7, 'min_child_samples': 7, 'subsample': 0.6407183602924094, 'colsample_bytree': 0.771894156108385, 'n_estimators': 750, 'min_split_gain': 1.0}. Best is trial 3 with value: 0.40724039384884425.
[I 2025-09-08 20:52:48,504] Trial 9 finished with value: 0.3694880133286353 and parameters: {'learning_rate': 0.05, 'num_leaves': 20, 'max_depth': 8, 'min_child_samples': 8, 'subsample': 0.6027408868725364, 'colsample_bytree': 0.7299225401581277, 'n_estimators': 750, 'min_split_gain': 1.0}. Best is trial 3 with value: 0.40724039384884425.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:52:48,652] Trial 10 finished with value: 0.40944573642737053 and parameters: {'learning_rate': 0.02, 'num_leaves': 10, 'max_depth': 5, 'min_child_samples': 6, 'subsample': 0.6629127780922128, 'colsample_bytree': 0.6849276384853668, 'n_estimators': 750, 'min_split_gain': 1.0}. Best is trial 10 with value: 0.40944573642737053.
[I 2025-09-08 20:52:48,796] Trial 11 finished with value: 0.40944573642737053 and parameters: {'learning_rate': 0.02, 'num_leaves': 10, 'max_depth': 5, 'min_child_samples': 6, 'subsample': 0.6694000999658355, 'colsample_bytree': 0.6782993577597582, 'n_estimators': 750, 'min_split_gain': 1.0}. Best is trial 10 with value: 0.40944573642737053.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 20:52:48,949] Trial 12 finished with value: 0.4069500269281264 and parameters: {'learning_rate': 0.02, 'num_leaves': 10, 'max_depth': 5, 'min_child_samples': 6, 'subsample': 0.6859176538057344, 'colsample_bytree': 0.6957945270614667, 'n_estimators': 750, 'min_split_gain': 1.0}. Best is trial 10 with value: 0.40944573642737053.
[I 2025-09-08 20:52:49,101] Trial 13 finished with value: 0.38427366745372193 and parameters: {'learning_rate': 0.02, 'num_leaves': 10, 'max_depth': 5, 'min_child_samples': 8, 'subsample': 0.6461029848405301, 'colsample_bytree': 0.6920991974736088, 'n_estimators': 750, 'min_split_gain': 1.0}. Best is trial 10 with value: 0.40944573642737053.

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:52:49,377] Trial 14 finished with value: 0.4091803867275428 and parameters: {'learning_rate': 0.02, 'num_leaves': 10, 'max_depth': 6, 'min_child_samples': 4, 'subsample': 0.7242329424847472, 'colsample_bytree': 0.6420649541625281, 'n_estimators': 750, 'min_split_gain': 0.0}. Best is trial 10 with value: 0.40944573642737053.
[I 2025-09-08 20:52:49,531] Trial 15 finished with value: 0.41617055754460736 and parameters: {'learning_rate': 0.04, 'num_leaves': 10, 'max_depth': 5, 'min_child_samples': 7, 'subsample': 0.6688927897779221, 'colsample_bytree': 0.6796369568857092, 'n_estimators': 1250, 'min_split_gain': 0.5}. Best is trial 15 with value: 0.41617055754460736.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 20:52:49,683] Trial 16 finished with value: 0.39867687375749955 and parameters: {'learning_rate': 0.04, 'num_leaves': 10, 'max_depth': 5, 'min_child_samples': 7, 'subsample': 0.6314097396520125, 'colsample_bytree': 0.7139252376091108, 'n_estimators': 1250, 'min_split_gain': 0.5}. Best is trial 15 with value: 0.41617055754460736.
[I 2025-09-08 20:52:49,842] Trial 17 finished with value: 0.3911550050349155 and parameters: {'learning_rate': 0.04, 'num_leaves': 10, 'max_depth': 6, 'min_child_samples': 8, 'subsample': 0.698102526950598, 'colsample_bytree': 0.7522505697193963, 'n_estimators': 1250, 'min_split_gain': 0.5}. Best is trial 15 with value: 0.41617055754460736.

Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:52:49,995] Trial 18 finished with value: 0.417723992727808 and parameters: {'learning_rate': 0.04, 'num_leaves': 10, 'max_depth': 5, 'min_child_samples': 7, 'subsample': 0.6638132948800934, 'colsample_bytree': 0.6400995153737677, 'n_estimators': 1250, 'min_split_gain': 0.5}. Best is trial 18 with value: 0.417723992727808.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 20:52:50,145] Trial 19 finished with value: 0.41675408851119117 and parameters: {'learning_rate': 0.04, 'num_leaves': 10, 'max_depth': 6, 'min_child_samples': 7, 'subsample': 0.7083867995817359, 'colsample_bytree': 0.62004825439233, 'n_estimators': 1250, 'min_split_gain': 0.5}. Best is trial 18 with value: 0.417723992727808.

Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:52:50,342] Trial 20 finished with value: 0.41282565456302883 and parameters: {'learning_rate': 0.04, 'num_leaves': 10, 'max_depth': 6, 'min_child_samples': 8, 'subsample': 0.755746595649173, 'colsample_bytree': 0.623358025622529, 'n_estimators': 1250, 'min_split_gain': 0.5}. Best is trial 18 with value: 0.417723992727808.
[I 2025-09-08 20:52:50,495] Trial 21 finished with value: 0.4153989274663634 and parameters: {'learning_rate': 0.04, 'num_leaves': 10, 'max_depth': 5, 'min_child_samples': 7, 'subsample': 0.7113764669455065, 'colsample_bytree': 0.60224646955823, 'n_estimators': 1250, 'min_split_gain': 0.5}. Best is trial 18 with value: 0.417723992727808.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 20:52:50,648] Trial 22 finished with value: 0.41675408851119117 and parameters: {'learning_rate': 0.04, 'num_leaves': 10, 'max_depth': 6, 'min_child_samples': 7, 'subsample': 0.6859222093115285, 'colsample_bytree': 0.6331114246905024, 'n_estimators': 1250, 'min_split_gain': 0.5}. Best is trial 18 with value: 0.417723992727808.
[I 2025-09-08 20:52:50,797] Trial 23 finished with value: 0.41771841599359827 and parameters: {'learning_rate': 0.04, 'num_leaves': 10, 'max_depth': 6, 'min_child_samples': 7, 'subsample': 0.6844574787280078, 'colsample_bytree': 0.6356716635385381, 'n_estimators': 1250, 'min_split_gain': 0.5}. Best is trial 18 with value: 0.417723992727808.

Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:52:50,952] Trial 24 finished with value: 0.3939854805039403 and parameters: {'learning_rate': 0.04, 'num_leaves': 10, 'max_depth': 6, 'min_child_samples': 8, 'subsample': 0.7166161020151465, 'colsample_bytree': 0.6536304145736168, 'n_estimators': 1250, 'min_split_gain': 0.5}. Best is trial 18 with value: 0.417723992727808.

Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 20:52:51,111] Trial 25 finished with value: 0.41526673160633387 and parameters: {'learning_rate': 0.04, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 7, 'subsample': 0.6946673667384663, 'colsample_bytree': 0.6307318360337575, 'n_estimators': 1250, 'min_split_gain': 0.5}. Best is trial 18 with value: 0.417723992727808.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:52:51,265] Trial 26 finished with value: 0.4078559865603946 and parameters: {'learning_rate': 0.04, 'num_leaves': 10, 'max_depth': 6, 'min_child_samples': 7, 'subsample': 0.7460300302992057, 'colsample_bytree': 0.6139072062495055, 'n_estimators': 1250, 'min_split_gain': 0.5}. Best is trial 18 with value: 0.417723992727808.
[I 2025-09-08 20:52:51,439] Trial 27 finished with value: 0.40272423968538895 and parameters: {'learning_rate': 0.03, 'num_leaves': 10, 'max_depth': 6, 'min_child_samples': 8, 'subsample': 0.625650598426091, 'colsample_bytree': 0.6408311918824608, 'n_estimators': 1250, 'min_split_gain': 0.5}. Best is trial 18 with value: 0.417723992727808.

Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 20:52:51,638] Trial 28 finished with value: 0.3812922317157379 and parameters: {'learning_rate': 0.04, 'num_leaves': 10, 'max_depth': 7, 'min_child_samples': 6, 'subsample': 0.6539232749305877, 'colsample_bytree': 0.6628187619797882, 'n_estimators': 1250, 'min_split_gain': 0.1}. Best is trial 18 with value: 0.417723992727808.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:52:52,072] Trial 29 finished with value: 0.3775887638472735 and parameters: {'learning_rate': 0.04, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 6, 'subsample': 0.7630687351645216, 'colsample_bytree': 0.6038296993825709, 'n_estimators': 1250, 'min_split_gain': 0.0}. Best is trial 18 with value: 0.417723992727808.
[I 2025-09-08 20:52:52,074] A new study created in memory with name: no-name-ceb0487c-a42a-4135-84de-1997d49aa2d1
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

✅ LBM con C2X-Complex_rhow_5x5_depth_in_3_4 - Mejor R2: 0.42
📋 Parámetros: {'learning_rate': 0.04, 'num_leaves': 10, 'max_depth': 5, 'min_child_samples': 7, 'subsample': 0.6638132948800934, 'colsample_bytree': 0.6400995153737677, 'n_estimators': 1250, 'min_split_gain': 0.5}

Buscando mejores hiperparámetros para MLP con C2X-Complex_rhow_5x5_depth_in_3_4...
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 20:52:53,235] Trial 0 finished with value: 0.4878808311723332 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.0005826886131636542, 'learning_rate': 'constant', 'learning_rate_init': 0.004051165669468146}. Best is trial 0 with value: 0.4878808311723332.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 20:52:54,444] Trial 1 finished with value: 0.2698046830116416 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.0066861009391620835, 'learning_rate': 'constant', 'learning_rate_init': 0.00014390256465386515}. Best is trial 0 with value: 0.4878808311723332.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 20:52:55,739] Trial 2 finished with value: 0.3125003512937557 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.07724921452323906, 'learning_rate': 'constant', 'learning_rate_init': 0.0002460179460780228}. Best is trial 0 with value: 0.4878808311723332.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 20:52:56,797] Trial 3 finished with value: 0.39913761820267274 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'relu', 'solver': 'sgd', 'alpha': 6.440792320846318e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00026077265559373467}. Best is trial 0 with value: 0.4878808311723332.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 20:52:57,884] Trial 4 finished with value: 0.4293174288399671 and parameters: {'hidden_layer_sizes': (64,), 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.0010237196838004663, 'learning_rate': 'adaptive', 'learning_rate_init': 0.008679890901062698}. Best is trial 0 with value: 0.4878808311723332.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 20:52:59,271] Trial 5 finished with value: 0.45583208176320955 and parameters: {'hidden_layer_sizes': (128,), 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.05588081267188967, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0025082829199195313}. Best is trial 0 with value: 0.4878808311723332.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 20:53:00,377] Trial 6 finished with value: 0.47393358852821904 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'relu', 'solver': 'adam', 'alpha': 3.952608035277288e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.00026341934748453955}. Best is trial 0 with value: 0.4878808311723332.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:53:01,310] Trial 7 finished with value: 0.48140712138317737 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.07430464073130454, 'learning_rate': 'constant', 'learning_rate_init': 0.002803668681517515}. Best is trial 0 with value: 0.4878808311723332.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 20:53:02,056] Trial 8 finished with value: 0.4509135985172092 and parameters: {'hidden_layer_sizes': (32,), 'activation': 'relu', 'solver': 'sgd', 'alpha': 2.5986303240933643e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.001728910012063158}. Best is trial 0 with value: 0.4878808311723332.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 20:53:02,857] Trial 9 finished with value: 0.40917627080971447 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.001501109023920349, 'learning_rate': 'constant', 'learning_rate_init': 0.0033732734299529027}. Best is trial 0 with value: 0.4878808311723332.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 20:53:03,512] Trial 10 finished with value: 0.4485138879247086 and parameters: {'hidden_layer_sizes': (64,), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.00020095569947243074, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0007275516669597401}. Best is trial 0 with value: 0.4878808311723332.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:53:03,852] Trial 11 finished with value: 0.39422230151381427 and parameters: {'hidden_layer_sizes': (32,), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.009630641461224991, 'learning_rate': 'constant', 'learning_rate_init': 0.008600948108025995}. Best is trial 0 with value: 0.4878808311723332.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:53:04,524] Trial 12 finished with value: 0.4540828849516563 and parameters: {'hidden_layer_sizes': (128,), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0003206632394250302, 'learning_rate': 'constant', 'learning_rate_init': 0.004263002003410829}. Best is trial 0 with value: 0.4878808311723332.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 20:53:05,698] Trial 13 finished with value: 0.49453521255755456 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.007673127874972007, 'learning_rate': 'constant', 'learning_rate_init': 0.0008247917312249387}. Best is trial 13 with value: 0.49453521255755456.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 20:53:06,849] Trial 14 finished with value: 0.4948730998431922 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.005209328969532822, 'learning_rate': 'constant', 'learning_rate_init': 0.000813859455063722}. Best is trial 14 with value: 0.4948730998431922.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 20:53:08,191] Trial 15 finished with value: 0.49492032603209934 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.004797572240505437, 'learning_rate': 'constant', 'learning_rate_init': 0.0008126221093375269}. Best is trial 15 with value: 0.49492032603209934.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 20:53:08,913] Trial 16 finished with value: 0.45314787908948656 and parameters: {'hidden_layer_sizes': (32,), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0028251612891423573, 'learning_rate': 'constant', 'learning_rate_init': 0.00046459836266444853}. Best is trial 15 with value: 0.49492032603209934.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

[I 2025-09-08 20:53:09,699] Trial 17 finished with value: 0.4771075818486743 and parameters: {'hidden_layer_sizes': (128,), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.017400852687915417, 'learning_rate': 'constant', 'learning_rate_init': 0.001371341129916423}. Best is trial 15 with value: 0.49492032603209934.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 20:53:10,265] Trial 18 finished with value: 0.43498324433694907 and parameters: {'hidden_layer_sizes': (64,), 'activation': 'relu', 'solver': 'adam', 'alpha': 0.003097214133955348, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00048128438379656024}. Best is trial 15 with value: 0.49492032603209934.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 20:53:11,296] Trial 19 finished with value: 0.48596741514231195 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.015523271379292552, 'learning_rate': 'constant', 'learning_rate_init': 0.001261094534302066}. Best is trial 15 with value: 0.49492032603209934.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 20:53:12,553] Trial 20 finished with value: 0.4948102550586982 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'adam', 'alpha': 1.1772593876786091e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.0004928662603265042}. Best is trial 15 with value: 0.49492032603209934.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 20:53:13,781] Trial 21 finished with value: 0.4945281352734556 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'adam', 'alpha': 1.255796339305403e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.000484272526857668}. Best is trial 15 with value: 0.49492032603209934.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 20:53:15,100] Trial 22 finished with value: 0.49412369466091216 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.00011775507262642588, 'learning_rate': 'constant', 'learning_rate_init': 0.0008401095813312725}. Best is trial 15 with value: 0.49492032603209934.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 20:53:16,371] Trial 23 finished with value: 0.4970931608685809 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0032901148512814366, 'learning_rate': 'constant', 'learning_rate_init': 0.0006192096957491424}. Best is trial 23 with value: 0.4970931608685809.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

[I 2025-09-08 20:53:17,401] Trial 24 finished with value: 0.46844634229670085 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0022124286650359905, 'learning_rate': 'constant', 'learning_rate_init': 0.001939057150094957}. Best is trial 23 with value: 0.4970931608685809.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 20:53:18,792] Trial 25 finished with value: 0.496839781990061 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.030325991820025766, 'learning_rate': 'constant', 'learning_rate_init': 0.0006736301385377436}. Best is trial 23 with value: 0.4970931608685809.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:53:19,502] Trial 26 finished with value: 0.3548410608109274 and parameters: {'hidden_layer_sizes': (128,), 'activation': 'relu', 'solver': 'adam', 'alpha': 0.02933147719168945, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0003624529741250549}. Best is trial 23 with value: 0.4970931608685809.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 20:53:20,495] Trial 27 finished with value: 0.34581631729881196 and parameters: {'hidden_layer_sizes': (32,), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.03692591552365257, 'learning_rate': 'constant', 'learning_rate_init': 0.00011489459199692239}. Best is trial 23 with value: 0.4970931608685809.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 20:53:21,111] Trial 28 finished with value: 0.4392020864662152 and parameters: {'hidden_layer_sizes': (64,), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.017348969593762927, 'learning_rate': 'constant', 'learning_rate_init': 0.0011353560294461256}. Best is trial 23 with value: 0.4970931608685809.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 20:53:22,514] Trial 29 finished with value: 0.4971071104602863 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0005124311256864591, 'learning_rate': 'constant', 'learning_rate_init': 0.0006525381519635442}. Best is trial 29 with value: 0.4971071104602863.
[I 2025-09-08 20:53:22,516] A new study created in memory with name: no-name-75876a7e-95b7-45dc-8965-d8d1d6e9d01a
[I 2025-09-08 20:53:22,593] Trial 0 finished with value: 0.49496109186601284 and parameters: {'C': 3.37802498287359, 'epsilon': 0.032146841999084734}. Best is trial 0 with value: 0.49496109186601284.
[I 2025-09-08 20:53:22,646] Trial 1 finished with value: 0.414364998882065 and parameters: {'C': 0.7066595666727746, 'epsilon': 0.03351134383991614}. Best is trial 0 with value: 0.49496109186601284.
[I 2025-09-08 20:53:22,697] Trial 2 finished with value: 0.385854930696029 and parameters: {'C': 0.5068380953716035, 'epsilon': 0.08959313009671285}. Best is trial 0 with value: 0.49496109186601284.

✅ MLP con C2X-Complex_rhow_5x5_depth_in_3_4 - Mejor R2: 0.50
📋 Parámetros: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0005124311256864591, 'learning_rate': 'constant', 'learning_rate_init': 0.0006525381519635442}

Buscando mejores hiperparámetros para SVR con C2X-Complex_rhow_5x5_depth_in_3_4...
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 20:53:22,748] Trial 3 finished with value: 0.4506546461441676 and parameters: {'C': 0.8825098489380081, 'epsilon': 0.19676309205072595}. Best is trial 0 with value: 0.49496109186601284.
[I 2025-09-08 20:53:22,801] Trial 4 finished with value: 0.3301756590953456 and parameters: {'C': 0.3310780396291193, 'epsilon': 0.03681196531022327}. Best is trial 0 with value: 0.49496109186601284.
[I 2025-09-08 20:53:22,856] Trial 5 finished with value: 0.48117337539468297 and parameters: {'C': 5.097157771654792, 'epsilon': 0.03144422461282599}. Best is trial 0 with value: 0.49496109186601284.
[I 2025-09-08 20:53:22,903] Trial 6 finished with value: 0.502652176700208 and parameters: {'C': 3.303008355989999, 'epsilon': 0.11585516755849977}. Best is trial 6 with value: 0.502652176700208.

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 20:53:22,950] Trial 7 finished with value: 0.39079945217905254 and parameters: {'C': 0.5190196507329453, 'epsilon': 0.1814896285501833}. Best is trial 6 with value: 0.502652176700208.
[I 2025-09-08 20:53:23,009] Trial 8 finished with value: 0.4867596773581098 and parameters: {'C': 2.595653914342478, 'epsilon': 0.029947925339204116}. Best is trial 6 with value: 0.502652176700208.
[I 2025-09-08 20:53:23,059] Trial 9 finished with value: 0.3527292658678036 and parameters: {'C': 0.37829027686215194, 'epsilon': 0.10338227189632235}. Best is trial 6 with value: 0.502652176700208.
[I 2025-09-08 20:53:23,114] Trial 10 finished with value: 0.43854364214256786 and parameters: {'C': 8.205002352776752, 'epsilon': 0.15223912110570087}. Best is trial 6 with value: 0.502652176700208.

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 20:53:23,175] Trial 11 finished with value: 0.19141798968503435 and parameters: {'C': 0.10427098466842841, 'epsilon': 0.07303962529537836}. Best is trial 6 with value: 0.502652176700208.
[I 2025-09-08 20:53:23,235] Trial 12 finished with value: 0.49198332688252516 and parameters: {'C': 2.179019721507826, 'epsilon': 0.14024048557213395}. Best is trial 6 with value: 0.502652176700208.
[I 2025-09-08 20:53:23,292] Trial 13 finished with value: 0.48667439841122623 and parameters: {'C': 2.286656454709896, 'epsilon': 0.06642612656610025}. Best is trial 6 with value: 0.502652176700208.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:53:23,347] Trial 14 finished with value: 0.4951524348472258 and parameters: {'C': 4.398764393165777, 'epsilon': 0.12219095856065923}. Best is trial 6 with value: 0.502652176700208.
[I 2025-09-08 20:53:23,408] Trial 15 finished with value: 0.4662821730885205 and parameters: {'C': 6.782603213168789, 'epsilon': 0.12798182926132073}. Best is trial 6 with value: 0.502652176700208.
[I 2025-09-08 20:53:23,464] Trial 16 finished with value: 0.4684440406254213 and parameters: {'C': 1.3196902539273159, 'epsilon': 0.1165364891272115}. Best is trial 6 with value: 0.502652176700208.
[I 2025-09-08 20:53:23,519] Trial 17 finished with value: 0.4990334537632429 and parameters: {'C': 4.096094334504829, 'epsilon': 0.1627114528211856}. Best is trial 6 with value: 0.502652176700208.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:53:23,575] Trial 18 finished with value: 0.47487926492472154 and parameters: {'C': 1.5920140861858345, 'epsilon': 0.16017947281274675}. Best is trial 6 with value: 0.502652176700208.
[I 2025-09-08 20:53:23,641] Trial 19 finished with value: 0.4147631459976649 and parameters: {'C': 9.692858246957675, 'epsilon': 0.16972487439353778}. Best is trial 6 with value: 0.502652176700208.
[I 2025-09-08 20:53:23,698] Trial 20 finished with value: 0.4983153940963609 and parameters: {'C': 4.094871135381652, 'epsilon': 0.1407333789916861}. Best is trial 6 with value: 0.502652176700208.
[I 2025-09-08 20:53:23,755] Trial 21 finished with value: 0.4929451502524153 and parameters: {'C': 4.657898943926635, 'epsilon': 0.14834192547108582}. Best is trial 6 with value: 0.502652176700208.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 20:53:23,817] Trial 22 finished with value: 0.4822922296017376 and parameters: {'C': 5.769333629885463, 'epsilon': 0.1390832904240196}. Best is trial 6 with value: 0.502652176700208.
[I 2025-09-08 20:53:23,903] Trial 23 finished with value: 0.5040013573887754 and parameters: {'C': 3.6020615325367475, 'epsilon': 0.17755767069963907}. Best is trial 23 with value: 0.5040013573887754.
[I 2025-09-08 20:53:23,963] Trial 24 finished with value: 0.47711867467173935 and parameters: {'C': 1.5696635769805223, 'epsilon': 0.19987606244266665}. Best is trial 23 with value: 0.5040013573887754.

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:53:24,016] Trial 25 finished with value: 0.5069494563463731 and parameters: {'C': 3.0157422699977454, 'epsilon': 0.1747413893663285}. Best is trial 25 with value: 0.5069494563463731.
[I 2025-09-08 20:53:24,080] Trial 26 finished with value: 0.5011159721485682 and parameters: {'C': 2.602546740294757, 'epsilon': 0.18407337332245105}. Best is trial 25 with value: 0.5069494563463731.
[I 2025-09-08 20:53:24,135] Trial 27 finished with value: 0.4680884562168027 and parameters: {'C': 1.2012667871735445, 'epsilon': 0.1749230241587563}. Best is trial 25 with value: 0.5069494563463731.
[I 2025-09-08 20:53:24,193] Trial 28 finished with value: 0.49671403199352643 and parameters: {'C': 3.1809024098197103, 'epsilon': 0.054152782610960855}. Best is trial 25 with value: 0.5069494563463731.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 20:53:24,251] Trial 29 finished with value: 0.48696440637015437 and parameters: {'C': 2.0011411004834816, 'epsilon': 0.09862232532814115}. Best is trial 25 with value: 0.5069494563463731.
[I 2025-09-08 20:53:24,253] A new study created in memory with name: no-name-e1b718f7-7036-43a4-a1f1-f8b7c24cfd7d
[I 2025-09-08 20:53:24,300] Trial 0 finished with value: 0.4360318685995425 and parameters: {'n_neighbors': 5, 'leaf_size': 20}. Best is trial 0 with value: 0.4360318685995425.
[I 2025-09-08 20:53:24,345] Trial 1 finished with value: 0.4538590780845732 and parameters: {'n_neighbors': 8, 'leaf_size': 30}. Best is trial 1 with value: 0.4538590780845732.
[I 2025-09-08 20:53:24,389] Trial 2 finished with value: 0.44602793573939775 and parameters: {'n_neighbors': 10, 'leaf_size': 16}. Best is trial 1 with value: 0.4538590780845732.
[I 2025-09-08 20:53:24,432] Trial 3 finished with value: 0.44602793573939775 and parameters: {'n_neighbors': 10, 'leaf_size': 35}. Best is trial 1 with value: 0.4538590780845732.

Fold 3

✅ SVR con C2X-Complex_rhow_5x5_depth_in_3_4 - Mejor R2: 0.51
📋 Parámetros: {'C': 3.0157422699977454, 'epsilon': 0.1747413893663285}

Buscando mejores hiperparámetros para KNN con C2X-Complex_rhow_5x5_depth_in_3_4...
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 20:53:24,478] Trial 4 finished with value: 0.35549783702188215 and parameters: {'n_neighbors': 4, 'leaf_size': 36}. Best is trial 1 with value: 0.4538590780845732.
[I 2025-09-08 20:53:24,526] Trial 5 finished with value: 0.4538590780845732 and parameters: {'n_neighbors': 8, 'leaf_size': 36}. Best is trial 1 with value: 0.4538590780845732.
[I 2025-09-08 20:53:24,567] Trial 6 finished with value: 0.4538590780845732 and parameters: {'n_neighbors': 8, 'leaf_size': 40}. Best is trial 1 with value: 0.4538590780845732.
[I 2025-09-08 20:53:24,611] Trial 7 finished with value: 0.3620579996961079 and parameters: {'n_neighbors': 3, 'leaf_size': 24}. Best is trial 1 with value: 0.4538590780845732.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:53:24,654] Trial 8 finished with value: 0.4550574897959467 and parameters: {'n_neighbors': 12, 'leaf_size': 26}. Best is trial 8 with value: 0.4550574897959467.
[I 2025-09-08 20:53:24,704] Trial 9 finished with value: 0.44602793573939775 and parameters: {'n_neighbors': 10, 'leaf_size': 19}. Best is trial 8 with value: 0.4550574897959467.
[I 2025-09-08 20:53:24,754] Trial 10 finished with value: 0.4550574897959467 and parameters: {'n_neighbors': 12, 'leaf_size': 10}. Best is trial 8 with value: 0.4550574897959467.
[I 2025-09-08 20:53:24,803] Trial 11 finished with value: 0.4550574897959467 and parameters: {'n_neighbors': 12, 'leaf_size': 10}. Best is trial 8 with value: 0.4550574897959467.
[I 2025-09-08 20:53:24,852] Trial 12 finished with value: 0.4550574897959467 and parameters: {'n_neighbors': 12, 'leaf_size': 26}. Best is trial 8 with value: 0.4550574897959467.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:53:24,908] Trial 13 finished with value: 0.4550574897959467 and parameters: {'n_neighbors': 12, 'leaf_size': 10}. Best is trial 8 with value: 0.4550574897959467.
[I 2025-09-08 20:53:24,958] Trial 14 finished with value: 0.4344629289018876 and parameters: {'n_neighbors': 6, 'leaf_size': 28}. Best is trial 8 with value: 0.4550574897959467.
[I 2025-09-08 20:53:25,010] Trial 15 finished with value: 0.4521687720645014 and parameters: {'n_neighbors': 11, 'leaf_size': 15}. Best is trial 8 with value: 0.4550574897959467.
[I 2025-09-08 20:53:25,061] Trial 16 finished with value: 0.4503902817530647 and parameters: {'n_neighbors': 9, 'leaf_size': 22}. Best is trial 8 with value: 0.4550574897959467.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:53:25,117] Trial 17 finished with value: 0.4344629289018876 and parameters: {'n_neighbors': 6, 'leaf_size': 30}. Best is trial 8 with value: 0.4550574897959467.
[I 2025-09-08 20:53:25,222] Trial 18 finished with value: 0.4521687720645014 and parameters: {'n_neighbors': 11, 'leaf_size': 15}. Best is trial 8 with value: 0.4550574897959467.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:53:25,282] Trial 19 finished with value: 0.4521687720645014 and parameters: {'n_neighbors': 11, 'leaf_size': 32}. Best is trial 8 with value: 0.4550574897959467.
[I 2025-09-08 20:53:25,335] Trial 20 finished with value: 0.4503902817530647 and parameters: {'n_neighbors': 9, 'leaf_size': 25}. Best is trial 8 with value: 0.4550574897959467.
[I 2025-09-08 20:53:25,384] Trial 21 finished with value: 0.4550574897959467 and parameters: {'n_neighbors': 12, 'leaf_size': 10}. Best is trial 8 with value: 0.4550574897959467.
[I 2025-09-08 20:53:25,435] Trial 22 finished with value: 0.4550574897959467 and parameters: {'n_neighbors': 12, 'leaf_size': 14}. Best is trial 8 with value: 0.4550574897959467.
[I 2025-09-08 20:53:25,486] Trial 23 finished with value: 0.4521687720645014 and parameters: {'n_neighbors': 11, 'leaf_size': 12}. Best is trial 8 with value: 0.4550574897959467.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:53:25,541] Trial 24 finished with value: 0.4550574897959467 and parameters: {'n_neighbors': 12, 'leaf_size': 18}. Best is trial 8 with value: 0.4550574897959467.
[I 2025-09-08 20:53:25,595] Trial 25 finished with value: 0.44602793573939775 and parameters: {'n_neighbors': 10, 'leaf_size': 12}. Best is trial 8 with value: 0.4550574897959467.
[I 2025-09-08 20:53:25,651] Trial 26 finished with value: 0.4521687720645014 and parameters: {'n_neighbors': 11, 'leaf_size': 22}. Best is trial 8 with value: 0.4550574897959467.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:53:25,698] Trial 27 finished with value: 0.4503902817530647 and parameters: {'n_neighbors': 9, 'leaf_size': 17}. Best is trial 8 with value: 0.4550574897959467.
[I 2025-09-08 20:53:25,753] Trial 28 finished with value: 0.4622716251837414 and parameters: {'n_neighbors': 7, 'leaf_size': 12}. Best is trial 28 with value: 0.4622716251837414.
[I 2025-09-08 20:53:25,805] Trial 29 finished with value: 0.4344629289018876 and parameters: {'n_neighbors': 6, 'leaf_size': 22}. Best is trial 28 with value: 0.4622716251837414.
[I 2025-09-08 20:53:25,806] A new study created in memory with name: no-name-15fac9c0-0c5f-46ad-ae17-3469f9b57863
[I 2025-09-08 20:53:25,857] Trial 0 finished with value: 0.30337247541807155 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 0 with value: 0.30337247541807155.
[I 2025-09-08 20:53:25,912] Trial 1 finished with value: 0.30337247541807155 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 0 with value: 0.30337247541807155.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

✅ KNN con C2X-Complex_rhow_5x5_depth_in_3_4 - Mejor R2: 0.46
📋 Parámetros: {'n_neighbors': 7, 'leaf_size': 12}

Buscando mejores hiperparámetros para LR con C2X-Complex_rhow_5x5_depth_in_3_4...
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 20:53:25,970] Trial 2 finished with value: 0.35230978136154506 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 2 with value: 0.35230978136154506.
[I 2025-09-08 20:53:26,037] Trial 3 finished with value: 0.30337247541807155 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 2 with value: 0.35230978136154506.
[I 2025-09-08 20:53:26,095] Trial 4 finished with value: 0.3033724754264015 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 2 with value: 0.35230978136154506.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:53:26,152] Trial 5 finished with value: 0.35230978136154506 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 2 with value: 0.35230978136154506.
[I 2025-09-08 20:53:26,200] Trial 6 finished with value: 0.35230978136154506 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 2 with value: 0.35230978136154506.
[I 2025-09-08 20:53:26,250] Trial 7 finished with value: 0.30337247541807155 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 2 with value: 0.35230978136154506.
[I 2025-09-08 20:53:26,302] Trial 8 finished with value: 0.30337247541807155 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 2 with value: 0.35230978136154506.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:53:26,360] Trial 9 finished with value: 0.35230978136154506 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 2 with value: 0.35230978136154506.
[I 2025-09-08 20:53:26,414] Trial 10 finished with value: 0.35205452984677343 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 2 with value: 0.35230978136154506.
[I 2025-09-08 20:53:26,456] Trial 11 finished with value: 0.35205452984677343 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 2 with value: 0.35230978136154506.
[I 2025-09-08 20:53:26,496] Trial 12 finished with value: 0.35230978136154506 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 2 with value: 0.35230978136154506.
[I 2025-09-08 20:53:26,539] Trial 13 finished with value: 0.35230978136154506 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 2 with value: 0.35230978136154506.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:53:26,582] Trial 14 finished with value: 0.35205452984677343 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 2 with value: 0.35230978136154506.
[I 2025-09-08 20:53:26,628] Trial 15 finished with value: 0.35230978136154506 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 2 with value: 0.35230978136154506.
[I 2025-09-08 20:53:26,672] Trial 16 finished with value: 0.35230978136154506 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 2 with value: 0.35230978136154506.
[I 2025-09-08 20:53:26,713] Trial 17 finished with value: 0.35230978136154506 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 2 with value: 0.35230978136154506.
[I 2025-09-08 20:53:26,754] Trial 18 finished with value: 0.35205452984677343 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 2 with value: 0.35230978136154506.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:53:26,795] Trial 19 finished with value: 0.35230978136154506 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 2 with value: 0.35230978136154506.
[I 2025-09-08 20:53:26,852] Trial 20 finished with value: 0.35230978136154506 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 2 with value: 0.35230978136154506.
[I 2025-09-08 20:53:26,912] Trial 21 finished with value: 0.35230978136154506 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 2 with value: 0.35230978136154506.
[I 2025-09-08 20:53:26,957] Trial 22 finished with value: 0.35230978136154506 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 2 with value: 0.35230978136154506.
[I 2025-09-08 20:53:26,998] Trial 23 finished with value: 0.35230978136154506 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 2 with value: 0.35230978136154506.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:53:27,046] Trial 24 finished with value: 0.35230978136154506 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 2 with value: 0.35230978136154506.
[I 2025-09-08 20:53:27,095] Trial 25 finished with value: 0.35230978136154506 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 2 with value: 0.35230978136154506.
[I 2025-09-08 20:53:27,136] Trial 26 finished with value: 0.35205452984677343 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 2 with value: 0.35230978136154506.
[I 2025-09-08 20:53:27,178] Trial 27 finished with value: 0.35230978136154506 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 2 with value: 0.35230978136154506.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 20:53:27,221] Trial 28 finished with value: 0.35230978136154506 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 2 with value: 0.35230978136154506.
[I 2025-09-08 20:53:27,289] Trial 29 finished with value: 0.30337247541807155 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 2 with value: 0.35230978136154506.
[I 2025-09-08 20:53:27,293] A new study created in memory with name: no-name-9ae63b0d-b6fb-4af3-9353-9740ff540700

Fold 3
Fold 1
Fold 2
Fold 3

✅ LR con C2X-Complex_rhow_5x5_depth_in_3_4 - Mejor R2: 0.35
📋 Parámetros: {'fit_intercept': True, 'positive': True}

Buscando mejores hiperparámetros para RF con C2X-Complex_rhow_5x5_depth_in_3_4...
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:53:29,017] Trial 0 finished with value: 0.4400251410979847 and parameters: {'n_estimators': 200, 'max_depth': 11, 'min_samples_split': 5, 'min_samples_leaf': 6, 'bootstrap': True}. Best is trial 0 with value: 0.4400251410979847.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:53:30,459] Trial 1 finished with value: 0.04021043307557515 and parameters: {'n_estimators': 100, 'max_depth': 12, 'min_samples_split': 4, 'min_samples_leaf': 4, 'bootstrap': False}. Best is trial 0 with value: 0.4400251410979847.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:53:34,200] Trial 2 finished with value: 0.44404193704575073 and parameters: {'n_estimators': 400, 'max_depth': 12, 'min_samples_split': 5, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 2 with value: 0.44404193704575073.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:53:37,776] Trial 3 finished with value: 0.4468659712840401 and parameters: {'n_estimators': 400, 'max_depth': 6, 'min_samples_split': 4, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 3 with value: 0.4468659712840401.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:53:42,700] Trial 4 finished with value: 0.14049696692379518 and parameters: {'n_estimators': 400, 'max_depth': 8, 'min_samples_split': 3, 'min_samples_leaf': 6, 'bootstrap': False}. Best is trial 3 with value: 0.4468659712840401.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:53:43,722] Trial 5 finished with value: 0.44558457984071403 and parameters: {'n_estimators': 100, 'max_depth': 7, 'min_samples_split': 4, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 3 with value: 0.4468659712840401.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:53:47,050] Trial 6 finished with value: 0.43761668617264293 and parameters: {'n_estimators': 400, 'max_depth': 8, 'min_samples_split': 6, 'min_samples_leaf': 6, 'bootstrap': True}. Best is trial 3 with value: 0.4468659712840401.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:53:47,981] Trial 7 finished with value: 0.4434696706140164 and parameters: {'n_estimators': 100, 'max_depth': 6, 'min_samples_split': 6, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 3 with value: 0.4468659712840401.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:53:48,959] Trial 8 finished with value: 0.44268408923883196 and parameters: {'n_estimators': 100, 'max_depth': 7, 'min_samples_split': 6, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 3 with value: 0.4468659712840401.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:53:50,073] Trial 9 finished with value: 0.023097906445410803 and parameters: {'n_estimators': 100, 'max_depth': 5, 'min_samples_split': 5, 'min_samples_leaf': 5, 'bootstrap': False}. Best is trial 3 with value: 0.4468659712840401.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:53:52,330] Trial 10 finished with value: 0.11525583758219016 and parameters: {'n_estimators': 200, 'max_depth': 10, 'min_samples_split': 2, 'min_samples_leaf': 8, 'bootstrap': False}. Best is trial 3 with value: 0.4468659712840401.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:53:55,628] Trial 11 finished with value: 0.4418101480381916 and parameters: {'n_estimators': 400, 'max_depth': 5, 'min_samples_split': 8, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 3 with value: 0.4468659712840401.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:53:56,598] Trial 12 finished with value: 0.44268408923883196 and parameters: {'n_estimators': 100, 'max_depth': 7, 'min_samples_split': 3, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 3 with value: 0.4468659712840401.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:54:00,955] Trial 13 finished with value: 0.4501852566056572 and parameters: {'n_estimators': 400, 'max_depth': 9, 'min_samples_split': 3, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 13 with value: 0.4501852566056572.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:54:04,924] Trial 14 finished with value: 0.4475262810773228 and parameters: {'n_estimators': 400, 'max_depth': 9, 'min_samples_split': 2, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 13 with value: 0.4501852566056572.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:54:08,654] Trial 15 finished with value: 0.4441491165083596 and parameters: {'n_estimators': 400, 'max_depth': 10, 'min_samples_split': 2, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 13 with value: 0.4501852566056572.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:54:12,640] Trial 16 finished with value: 0.4475262810773228 and parameters: {'n_estimators': 400, 'max_depth': 9, 'min_samples_split': 2, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 13 with value: 0.4501852566056572.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:54:15,767] Trial 17 finished with value: 0.42897382968590597 and parameters: {'n_estimators': 400, 'max_depth': 9, 'min_samples_split': 3, 'min_samples_leaf': 8, 'bootstrap': True}. Best is trial 13 with value: 0.4501852566056572.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:54:19,072] Trial 18 finished with value: -0.04088972783106226 and parameters: {'n_estimators': 200, 'max_depth': 10, 'min_samples_split': 3, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 13 with value: 0.4501852566056572.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:54:22,584] Trial 19 finished with value: 0.4416645246346191 and parameters: {'n_estimators': 400, 'max_depth': 9, 'min_samples_split': 8, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 13 with value: 0.4501852566056572.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:54:26,608] Trial 20 finished with value: 0.4487356384377179 and parameters: {'n_estimators': 400, 'max_depth': 11, 'min_samples_split': 2, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 13 with value: 0.4501852566056572.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:54:30,661] Trial 21 finished with value: 0.4487356384377179 and parameters: {'n_estimators': 400, 'max_depth': 11, 'min_samples_split': 2, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 13 with value: 0.4501852566056572.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:54:35,078] Trial 22 finished with value: 0.45255810350542397 and parameters: {'n_estimators': 400, 'max_depth': 11, 'min_samples_split': 2, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 22 with value: 0.45255810350542397.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:54:39,486] Trial 23 finished with value: 0.45255810350542397 and parameters: {'n_estimators': 400, 'max_depth': 11, 'min_samples_split': 3, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 22 with value: 0.45255810350542397.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:54:43,928] Trial 24 finished with value: 0.45117845475430657 and parameters: {'n_estimators': 400, 'max_depth': 12, 'min_samples_split': 3, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 22 with value: 0.45255810350542397.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:54:46,177] Trial 25 finished with value: 0.45070193663056796 and parameters: {'n_estimators': 200, 'max_depth': 12, 'min_samples_split': 4, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 22 with value: 0.45255810350542397.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:54:51,932] Trial 26 finished with value: 0.04074924928185061 and parameters: {'n_estimators': 400, 'max_depth': 11, 'min_samples_split': 3, 'min_samples_leaf': 4, 'bootstrap': False}. Best is trial 22 with value: 0.45255810350542397.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:54:56,348] Trial 27 finished with value: 0.45117845475430657 and parameters: {'n_estimators': 400, 'max_depth': 12, 'min_samples_split': 4, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 22 with value: 0.45255810350542397.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:54:59,560] Trial 28 finished with value: 0.4351693250020318 and parameters: {'n_estimators': 400, 'max_depth': 11, 'min_samples_split': 3, 'min_samples_leaf': 7, 'bootstrap': True}. Best is trial 22 with value: 0.45255810350542397.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:55:01,321] Trial 29 finished with value: 0.4441963030270098 and parameters: {'n_estimators': 200, 'max_depth': 10, 'min_samples_split': 2, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 22 with value: 0.45255810350542397.
[I 2025-09-08 20:55:01,322] A new study created in memory with name: no-name-70b12f5b-86d7-43ce-b7af-6add14b808ad

✅ RF con C2X-Complex_rhow_5x5_depth_in_3_4 - Mejor R2: 0.45
📋 Parámetros: {'n_estimators': 400, 'max_depth': 11, 'min_samples_split': 2, 'min_samples_leaf': 2, 'bootstrap': True}

Buscando mejores hiperparámetros para CAT con C2X-Complex_rhow_5x5_depth_in_3_4...
Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:55:28,673] Trial 0 finished with value: 0.4998877077610791 and parameters: {'iterations': 1000, 'learning_rate': 0.05, 'depth': 8, 'l2_leaf_reg': 2.560208090323835}. Best is trial 0 with value: 0.4998877077610791.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:55:29,847] Trial 1 finished with value: 0.43253977866042953 and parameters: {'iterations': 500, 'learning_rate': 0.02, 'depth': 4, 'l2_leaf_reg': 1.3538909217835022}. Best is trial 0 with value: 0.4998877077610791.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:55:32,201] Trial 2 finished with value: 0.44420639983561405 and parameters: {'iterations': 750, 'learning_rate': 0.02, 'depth': 5, 'l2_leaf_reg': 3.453057420136513}. Best is trial 0 with value: 0.4998877077610791.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:55:33,891] Trial 3 finished with value: 0.4387838565910471 and parameters: {'iterations': 750, 'learning_rate': 0.03, 'depth': 4, 'l2_leaf_reg': 4.484206801814157}. Best is trial 0 with value: 0.4998877077610791.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:55:37,074] Trial 4 finished with value: 0.4359671195725318 and parameters: {'iterations': 1000, 'learning_rate': 0.02, 'depth': 5, 'l2_leaf_reg': 2.630385473648349}. Best is trial 0 with value: 0.4998877077610791.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:55:57,052] Trial 5 finished with value: 0.48853335945056253 and parameters: {'iterations': 750, 'learning_rate': 0.03, 'depth': 8, 'l2_leaf_reg': 4.906202229218257}. Best is trial 0 with value: 0.4998877077610791.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:56:10,703] Trial 6 finished with value: 0.5005600944551801 and parameters: {'iterations': 500, 'learning_rate': 0.05, 'depth': 8, 'l2_leaf_reg': 2.1715631802694055}. Best is trial 6 with value: 0.5005600944551801.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:56:12,215] Trial 7 finished with value: 0.42905241473169436 and parameters: {'iterations': 750, 'learning_rate': 0.03, 'depth': 4, 'l2_leaf_reg': 3.4588924751363392}. Best is trial 6 with value: 0.5005600944551801.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:56:13,808] Trial 8 finished with value: 0.4657060680968774 and parameters: {'iterations': 500, 'learning_rate': 0.02, 'depth': 5, 'l2_leaf_reg': 4.648079488233426}. Best is trial 6 with value: 0.5005600944551801.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:56:40,397] Trial 9 finished with value: 0.4889662051570975 and parameters: {'iterations': 1000, 'learning_rate': 0.03, 'depth': 8, 'l2_leaf_reg': 4.58960718086696}. Best is trial 6 with value: 0.5005600944551801.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:56:46,183] Trial 10 finished with value: 0.4672218586639381 and parameters: {'iterations': 500, 'learning_rate': 0.05, 'depth': 7, 'l2_leaf_reg': 1.101785867608722}. Best is trial 6 with value: 0.5005600944551801.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:56:57,259] Trial 11 finished with value: 0.4724295024714049 and parameters: {'iterations': 1000, 'learning_rate': 0.05, 'depth': 7, 'l2_leaf_reg': 2.1966541551198104}. Best is trial 6 with value: 0.5005600944551801.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:57:08,360] Trial 12 finished with value: 0.4621275376877758 and parameters: {'iterations': 1000, 'learning_rate': 0.04, 'depth': 7, 'l2_leaf_reg': 1.9966493073031337}. Best is trial 6 with value: 0.5005600944551801.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:57:21,949] Trial 13 finished with value: 0.4915839424048505 and parameters: {'iterations': 500, 'learning_rate': 0.05, 'depth': 8, 'l2_leaf_reg': 3.0897020500237744}. Best is trial 6 with value: 0.5005600944551801.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:57:27,055] Trial 14 finished with value: 0.4680174741790539 and parameters: {'iterations': 1000, 'learning_rate': 0.05, 'depth': 6, 'l2_leaf_reg': 1.8231319259590473}. Best is trial 6 with value: 0.5005600944551801.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:57:32,918] Trial 15 finished with value: 0.4591367819095029 and parameters: {'iterations': 500, 'learning_rate': 0.05, 'depth': 7, 'l2_leaf_reg': 2.543642827353586}. Best is trial 6 with value: 0.5005600944551801.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:58:00,224] Trial 16 finished with value: 0.49006263570793585 and parameters: {'iterations': 1000, 'learning_rate': 0.04, 'depth': 8, 'l2_leaf_reg': 1.6009292450335626}. Best is trial 6 with value: 0.5005600944551801.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:58:03,000] Trial 17 finished with value: 0.463705713947149 and parameters: {'iterations': 500, 'learning_rate': 0.05, 'depth': 6, 'l2_leaf_reg': 3.7614385260961365}. Best is trial 6 with value: 0.5005600944551801.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:58:30,220] Trial 18 finished with value: 0.5045593650747909 and parameters: {'iterations': 1000, 'learning_rate': 0.05, 'depth': 8, 'l2_leaf_reg': 2.470463049060001}. Best is trial 18 with value: 0.5045593650747909.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:58:35,873] Trial 19 finished with value: 0.4698922757059473 and parameters: {'iterations': 500, 'learning_rate': 0.05, 'depth': 7, 'l2_leaf_reg': 2.941616250200516}. Best is trial 18 with value: 0.5045593650747909.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:59:02,737] Trial 20 finished with value: 0.4957181903362445 and parameters: {'iterations': 1000, 'learning_rate': 0.04, 'depth': 8, 'l2_leaf_reg': 3.955129457812463}. Best is trial 18 with value: 0.5045593650747909.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:59:30,008] Trial 21 finished with value: 0.49733472782730787 and parameters: {'iterations': 1000, 'learning_rate': 0.05, 'depth': 8, 'l2_leaf_reg': 2.447037115169342}. Best is trial 18 with value: 0.5045593650747909.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 20:59:57,192] Trial 22 finished with value: 0.4782699820750575 and parameters: {'iterations': 1000, 'learning_rate': 0.05, 'depth': 8, 'l2_leaf_reg': 2.8763002603076018}. Best is trial 18 with value: 0.5045593650747909.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:00:08,363] Trial 23 finished with value: 0.4857374276202278 and parameters: {'iterations': 1000, 'learning_rate': 0.05, 'depth': 7, 'l2_leaf_reg': 2.0408367761304187}. Best is trial 18 with value: 0.5045593650747909.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:00:35,568] Trial 24 finished with value: 0.5042395393217367 and parameters: {'iterations': 1000, 'learning_rate': 0.05, 'depth': 8, 'l2_leaf_reg': 2.286467618138785}. Best is trial 18 with value: 0.5045593650747909.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:00:41,296] Trial 25 finished with value: 0.47011754980081677 and parameters: {'iterations': 500, 'learning_rate': 0.05, 'depth': 7, 'l2_leaf_reg': 2.28199912482078}. Best is trial 18 with value: 0.5045593650747909.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:00:46,213] Trial 26 finished with value: 0.45666683734978175 and parameters: {'iterations': 1000, 'learning_rate': 0.05, 'depth': 6, 'l2_leaf_reg': 1.6860737485602404}. Best is trial 18 with value: 0.5045593650747909.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:01:13,464] Trial 27 finished with value: 0.4818570980567438 and parameters: {'iterations': 1000, 'learning_rate': 0.05, 'depth': 8, 'l2_leaf_reg': 1.3190665170508211}. Best is trial 18 with value: 0.5045593650747909.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:01:21,842] Trial 28 finished with value: 0.479067519107444 and parameters: {'iterations': 750, 'learning_rate': 0.04, 'depth': 7, 'l2_leaf_reg': 3.2098831413420736}. Best is trial 18 with value: 0.5045593650747909.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:01:35,432] Trial 29 finished with value: 0.4772330356802 and parameters: {'iterations': 500, 'learning_rate': 0.05, 'depth': 8, 'l2_leaf_reg': 2.7513677696864063}. Best is trial 18 with value: 0.5045593650747909.
[I 2025-09-08 21:01:35,433] A new study created in memory with name: no-name-fddd8d05-8a0f-4764-801e-d9c91cd87ec6
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.600e-01, tolerance: 4.779e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.802e-01, tolerance: 4.223e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.969e-01, tolerance: 3.136e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:01:35,506] Trial 0 finished with value: 0.39731021605738404 and parameters: {'alpha': 0.0042529560588886635, 'l1_ratio': 0.5569612844363226}. Best is trial 0 with value: 0.39731021605738404.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.065e+02, tolerance: 4.779e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.433e+01, tolerance: 4.223e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.333e+01, tolerance: 3.136e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:01:35,586] Trial 1 finished with value: 0.4143283715174741 and parameters: {'alpha': 0.00011320748218287912, 'l1_ratio': 0.3390667572113455}. Best is trial 1 with value: 0.4143283715174741.

✅ CAT con C2X-Complex_rhow_5x5_depth_in_3_4 - Mejor R2: 0.50
📋 Parámetros: {'iterations': 1000, 'learning_rate': 0.05, 'depth': 8, 'l2_leaf_reg': 2.470463049060001}

Buscando mejores hiperparámetros para ELN con C2X-Complex_rhow_5x5_depth_in_3_4...
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:01:35,644] Trial 2 finished with value: 0.3380213066025504 and parameters: {'alpha': 0.08340868991177935, 'l1_ratio': 0.6703951310105237}. Best is trial 1 with value: 0.4143283715174741.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.615e-01, tolerance: 4.779e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.520e+00, tolerance: 4.223e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.055e+00, tolerance: 3.136e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:01:35,724] Trial 3 finished with value: 0.3982128106057458 and parameters: {'alpha': 0.0032391626196622584, 'l1_ratio': 0.5434900634728447}. Best is trial 1 with value: 0.4143283715174741.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.920e+00, tolerance: 4.779e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.709e+00, tolerance: 4.223e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.470e+00, tolerance: 3.136e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:01:35,796] Trial 4 finished with value: 0.3981072376172727 and parameters: {'alpha': 0.004177796501868059, 'l1_ratio': 0.31608650299460683}. Best is trial 1 with value: 0.4143283715174741.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.250e+01, tolerance: 4.779e-02
  model = cd_fast.enet_coordinate_descent(

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.388e+01, tolerance: 4.223e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.387e+01, tolerance: 3.136e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:01:35,872] Trial 5 finished with value: 0.4037607949352687 and parameters: {'alpha': 0.001260327848883922, 'l1_ratio': 0.6723136417393101}. Best is trial 1 with value: 0.4143283715174741.
[I 2025-09-08 21:01:35,932] Trial 6 finished with value: 0.23776492373293842 and parameters: {'alpha': 0.6162331049589239, 'l1_ratio': 0.5702277281240499}. Best is trial 1 with value: 0.4143283715174741.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.305e+01, tolerance: 4.779e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.959e+01, tolerance: 4.223e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.330e+01, tolerance: 3.136e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:01:36,019] Trial 7 finished with value: 0.4081258763066556 and parameters: {'alpha': 0.0009528760139437254, 'l1_ratio': 0.5184868650796851}. Best is trial 1 with value: 0.4143283715174741.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.097e+02, tolerance: 4.779e-02
  model = cd_fast.enet_coordinate_descent(

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.626e+01, tolerance: 4.223e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.483e+01, tolerance: 3.136e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:01:36,104] Trial 8 finished with value: 0.4148379551756085 and parameters: {'alpha': 0.00018280204070574645, 'l1_ratio': 0.13568570719418435}. Best is trial 8 with value: 0.4148379551756085.
[I 2025-09-08 21:01:36,186] Trial 9 finished with value: 0.38519745294911933 and parameters: {'alpha': 0.0106887111853122, 'l1_ratio': 0.8546557226228514}. Best is trial 8 with value: 0.4148379551756085.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.086e+02, tolerance: 4.779e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.563e+01, tolerance: 4.223e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.449e+01, tolerance: 3.136e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:01:36,284] Trial 10 finished with value: 0.41495548124135845 and parameters: {'alpha': 0.0002558413136016056, 'l1_ratio': 0.11853541179406196}. Best is trial 10 with value: 0.41495548124135845.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.124e+02, tolerance: 4.779e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.750e+01, tolerance: 4.223e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.561e+01, tolerance: 3.136e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:01:36,378] Trial 11 finished with value: 0.4145620228452455 and parameters: {'alpha': 0.00010052982877750717, 'l1_ratio': 0.12720479076792754}. Best is trial 10 with value: 0.41495548124135845.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.009e+02, tolerance: 4.779e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.084e+01, tolerance: 4.223e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.247e+01, tolerance: 3.136e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:01:36,475] Trial 12 finished with value: 0.41457523031682686 and parameters: {'alpha': 0.0005097992953776824, 'l1_ratio': 0.11180358042330835}. Best is trial 10 with value: 0.41495548124135845.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.896e+01, tolerance: 4.779e-02
  model = cd_fast.enet_coordinate_descent(

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.482e+01, tolerance: 4.223e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.761e+01, tolerance: 3.136e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:01:36,567] Trial 13 finished with value: 0.41430030703887644 and parameters: {'alpha': 0.00038695922837325356, 'l1_ratio': 0.26983048421277495}. Best is trial 10 with value: 0.41495548124135845.
[I 2025-09-08 21:01:36,671] Trial 14 finished with value: 0.3818861549706844 and parameters: {'alpha': 0.026792761450324897, 'l1_ratio': 0.18922036260462724}. Best is trial 10 with value: 0.41495548124135845.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.954e+01, tolerance: 4.779e-02
  model = cd_fast.enet_coordinate_descent(

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.600e+01, tolerance: 4.223e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.736e+01, tolerance: 3.136e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:01:36,778] Trial 15 finished with value: 0.4140644480153344 and parameters: {'alpha': 0.0002581330436843739, 'l1_ratio': 0.4010403616524021}. Best is trial 10 with value: 0.41495548124135845.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.811e+01, tolerance: 4.779e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.520e+01, tolerance: 4.223e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.561e+01, tolerance: 3.136e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:01:36,878] Trial 16 finished with value: 0.4088024935195202 and parameters: {'alpha': 0.00134708907531362, 'l1_ratio': 0.2115972363803806}. Best is trial 10 with value: 0.41495548124135845.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.320e+01, tolerance: 4.779e-02
  model = cd_fast.enet_coordinate_descent(

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.808e+01, tolerance: 4.223e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.897e+01, tolerance: 3.136e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:01:36,977] Trial 17 finished with value: 0.4141262699923109 and parameters: {'alpha': 0.0002052584276962461, 'l1_ratio': 0.4315221042433953}. Best is trial 10 with value: 0.41495548124135845.
[I 2025-09-08 21:01:37,099] Trial 18 finished with value: 0.3584233407858155 and parameters: {'alpha': 0.11587551001633045, 'l1_ratio': 0.23120891727356563}. Best is trial 10 with value: 0.41495548124135845.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.508e+01, tolerance: 4.779e-02
  model = cd_fast.enet_coordinate_descent(

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.745e+01, tolerance: 4.223e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.117e+01, tolerance: 3.136e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:01:37,212] Trial 19 finished with value: 0.4138979262130443 and parameters: {'alpha': 0.0006803882852991055, 'l1_ratio': 0.11002054090854332}. Best is trial 10 with value: 0.41495548124135845.
[I 2025-09-08 21:01:37,302] Trial 20 finished with value: 0.37807388168046857 and parameters: {'alpha': 0.015945304244940953, 'l1_ratio': 0.8813792443354698}. Best is trial 10 with value: 0.41495548124135845.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.053e+02, tolerance: 4.779e-02
  model = cd_fast.enet_coordinate_descent(

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.370e+01, tolerance: 4.223e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.341e+01, tolerance: 3.136e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:01:37,400] Trial 21 finished with value: 0.41484847290417 and parameters: {'alpha': 0.0003707688827519967, 'l1_ratio': 0.1159124578499674}. Best is trial 10 with value: 0.41495548124135845.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.078e+02, tolerance: 4.779e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.529e+01, tolerance: 4.223e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.413e+01, tolerance: 3.136e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:01:37,506] Trial 22 finished with value: 0.4147606380413313 and parameters: {'alpha': 0.00018463541407302313, 'l1_ratio': 0.17446811671426182}. Best is trial 10 with value: 0.41495548124135845.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.100e+01, tolerance: 4.779e-02
  model = cd_fast.enet_coordinate_descent(

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.317e+01, tolerance: 4.223e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.602e+01, tolerance: 3.136e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:01:37,610] Trial 23 finished with value: 0.40650677050086675 and parameters: {'alpha': 0.0015919190821951567, 'l1_ratio': 0.28438365965124224}. Best is trial 10 with value: 0.41495548124135845.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.014e+02, tolerance: 4.779e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.158e+01, tolerance: 4.223e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.189e+01, tolerance: 3.136e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:01:37,758] Trial 24 finished with value: 0.4146771960625613 and parameters: {'alpha': 0.0003533312815179147, 'l1_ratio': 0.1633945253920464}. Best is trial 10 with value: 0.41495548124135845.

Fold 3
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.057e+02, tolerance: 4.779e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.386e+01, tolerance: 4.223e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.299e+01, tolerance: 3.136e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:01:37,897] Trial 25 finished with value: 0.41426018376805107 and parameters: {'alpha': 0.0001102204071588524, 'l1_ratio': 0.38258977740957417}. Best is trial 10 with value: 0.41495548124135845.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.671e+01, tolerance: 4.779e-02
  model = cd_fast.enet_coordinate_descent(

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.613e+01, tolerance: 4.223e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.409e+01, tolerance: 3.136e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:01:38,004] Trial 26 finished with value: 0.40563858929892227 and parameters: {'alpha': 0.0019173349735517424, 'l1_ratio': 0.24377860083716196}. Best is trial 10 with value: 0.41495548124135845.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.904e+01, tolerance: 4.779e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.959e+01, tolerance: 4.223e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.209e+01, tolerance: 3.136e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:01:38,121] Trial 27 finished with value: 0.41437140327934996 and parameters: {'alpha': 0.0005714697715619048, 'l1_ratio': 0.10807970849079263}. Best is trial 10 with value: 0.41495548124135845.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.049e+02, tolerance: 4.779e-02
  model = cd_fast.enet_coordinate_descent(

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.357e+01, tolerance: 4.223e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.303e+01, tolerance: 3.136e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:01:38,224] Trial 28 finished with value: 0.4147927534733662 and parameters: {'alpha': 0.00025535233793479276, 'l1_ratio': 0.17677700261131465}. Best is trial 10 with value: 0.41495548124135845.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.389e+00, tolerance: 4.779e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.112e+00, tolerance: 4.223e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.331e+00, tolerance: 3.136e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:01:38,330] Trial 29 finished with value: 0.39921986614206345 and parameters: {'alpha': 0.00293925959006417, 'l1_ratio': 0.4492541221301446}. Best is trial 10 with value: 0.41495548124135845.
[I 2025-09-08 21:01:38,332] A new study created in memory with name: no-name-863f62de-dbe7-48fc-b590-aaf900062be1

Fold 1
Fold 2
Fold 3

✅ ELN con C2X-Complex_rhow_5x5_depth_in_3_4 - Mejor R2: 0.41
📋 Parámetros: {'alpha': 0.0002558413136016056, 'l1_ratio': 0.11853541179406196}

Buscando mejores hiperparámetros para XGB con TOA_1x1_depth_in_3_4...
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:01:42,799] Trial 0 finished with value: 0.4162626990473181 and parameters: {'n_estimators': 750, 'learning_rate': 0.03, 'max_depth': 8, 'min_child_weight': 4, 'subsample': 0.6821606779533995, 'colsample_bytree': 0.6540772088222734}. Best is trial 0 with value: 0.4162626990473181.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:01:45,694] Trial 1 finished with value: 0.40513436245595047 and parameters: {'n_estimators': 750, 'learning_rate': 0.03, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.749873343697727, 'colsample_bytree': 0.6780223790661325}. Best is trial 0 with value: 0.4162626990473181.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:01:50,515] Trial 2 finished with value: 0.4323116520725278 and parameters: {'n_estimators': 1000, 'learning_rate': 0.03, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.756063797167149, 'colsample_bytree': 0.6570901236058173}. Best is trial 2 with value: 0.4323116520725278.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:01:54,757] Trial 3 finished with value: 0.4052927198341316 and parameters: {'n_estimators': 750, 'learning_rate': 0.03, 'max_depth': 8, 'min_child_weight': 4, 'subsample': 0.6934177002177732, 'colsample_bytree': 0.6937179645854874}. Best is trial 2 with value: 0.4323116520725278.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:02:00,674] Trial 4 finished with value: 0.43392302734652133 and parameters: {'n_estimators': 1000, 'learning_rate': 0.03, 'max_depth': 8, 'min_child_weight': 3, 'subsample': 0.632684014999616, 'colsample_bytree': 0.6180172353174345}. Best is trial 4 with value: 0.43392302734652133.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:02:05,546] Trial 5 finished with value: 0.4439328721197829 and parameters: {'n_estimators': 1250, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.7220005476843646, 'colsample_bytree': 0.6320881102280983}. Best is trial 5 with value: 0.4439328721197829.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:02:11,113] Trial 6 finished with value: 0.4273441582912036 and parameters: {'n_estimators': 1250, 'learning_rate': 0.01, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.7925662941863383, 'colsample_bytree': 0.7515715158065929}. Best is trial 5 with value: 0.4439328721197829.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:02:17,059] Trial 7 finished with value: 0.44925165341879797 and parameters: {'n_estimators': 1250, 'learning_rate': 0.02, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.6495546857823644, 'colsample_bytree': 0.6386017988292518}. Best is trial 7 with value: 0.44925165341879797.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:02:19,604] Trial 8 finished with value: 0.4437358046189724 and parameters: {'n_estimators': 750, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.7052302699112213, 'colsample_bytree': 0.6022316304220389}. Best is trial 7 with value: 0.44925165341879797.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:02:26,705] Trial 9 finished with value: 0.4005299705441767 and parameters: {'n_estimators': 1250, 'learning_rate': 0.03, 'max_depth': 8, 'min_child_weight': 3, 'subsample': 0.6509809125126541, 'colsample_bytree': 0.772782694793712}. Best is trial 7 with value: 0.44925165341879797.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:02:33,522] Trial 10 finished with value: 0.4317436700225527 and parameters: {'n_estimators': 1250, 'learning_rate': 0.02, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.6167444016106463, 'colsample_bytree': 0.7257571444045098}. Best is trial 7 with value: 0.44925165341879797.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:02:39,642] Trial 11 finished with value: 0.4196714575165825 and parameters: {'n_estimators': 1250, 'learning_rate': 0.02, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.7237360581468282, 'colsample_bytree': 0.6306572780043376}. Best is trial 7 with value: 0.44925165341879797.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:02:45,637] Trial 12 finished with value: 0.44393121807470787 and parameters: {'n_estimators': 1250, 'learning_rate': 0.02, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.6579728281108237, 'colsample_bytree': 0.6454174391823709}. Best is trial 7 with value: 0.44925165341879797.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:02:52,170] Trial 13 finished with value: 0.4608030470156934 and parameters: {'n_estimators': 1250, 'learning_rate': 0.01, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.6037953802483496, 'colsample_bytree': 0.7135799601857096}. Best is trial 13 with value: 0.4608030470156934.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:02:58,679] Trial 14 finished with value: 0.4538813395972728 and parameters: {'n_estimators': 1250, 'learning_rate': 0.01, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.6110204197178019, 'colsample_bytree': 0.7271510006902562}. Best is trial 13 with value: 0.4608030470156934.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:03:05,270] Trial 15 finished with value: 0.4554045039060948 and parameters: {'n_estimators': 1250, 'learning_rate': 0.01, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.606751496966553, 'colsample_bytree': 0.7235964505456448}. Best is trial 13 with value: 0.4608030470156934.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:03:10,628] Trial 16 finished with value: 0.4648416288154418 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.6036478218450342, 'colsample_bytree': 0.7198862484516634}. Best is trial 16 with value: 0.4648416288154418.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:03:15,874] Trial 17 finished with value: 0.45407696988534557 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.6313826596786805, 'colsample_bytree': 0.7926686167179781}. Best is trial 16 with value: 0.4648416288154418.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:03:21,272] Trial 18 finished with value: 0.45571543465891967 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.6000406348367245, 'colsample_bytree': 0.7020043228272936}. Best is trial 16 with value: 0.4648416288154418.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:03:26,541] Trial 19 finished with value: 0.45167108106637377 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.6624866476975901, 'colsample_bytree': 0.7493520485504432}. Best is trial 16 with value: 0.4648416288154418.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:03:31,176] Trial 20 finished with value: 0.45707571406551334 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.6303568140575507, 'colsample_bytree': 0.6849161765247165}. Best is trial 16 with value: 0.4648416288154418.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:03:35,783] Trial 21 finished with value: 0.46085144357541025 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.6288000871085293, 'colsample_bytree': 0.6796159257765678}. Best is trial 16 with value: 0.4648416288154418.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:03:41,273] Trial 22 finished with value: 0.4578108462695248 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.6297092170231786, 'colsample_bytree': 0.706248830635253}. Best is trial 16 with value: 0.4648416288154418.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:03:45,793] Trial 23 finished with value: 0.4667636749872111 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.6003150578900983, 'colsample_bytree': 0.6722968232084591}. Best is trial 23 with value: 0.4667636749872111.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:03:50,485] Trial 24 finished with value: 0.4575992399366616 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.6744831785332676, 'colsample_bytree': 0.66956772942169}. Best is trial 23 with value: 0.4667636749872111.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:03:55,080] Trial 25 finished with value: 0.4619719301340657 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.6208279704937236, 'colsample_bytree': 0.670183577697399}. Best is trial 23 with value: 0.4667636749872111.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:03:59,519] Trial 26 finished with value: 0.46670619558740595 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.6194552515258307, 'colsample_bytree': 0.6655073547621787}. Best is trial 23 with value: 0.4667636749872111.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:04:04,013] Trial 27 finished with value: 0.4566345977365138 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.6454296816918199, 'colsample_bytree': 0.7457637668547159}. Best is trial 23 with value: 0.4667636749872111.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:04:07,973] Trial 28 finished with value: 0.4579356478980004 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.6176701093418406, 'colsample_bytree': 0.6922323464604823}. Best is trial 23 with value: 0.4667636749872111.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:04:13,655] Trial 29 finished with value: 0.43393997958560665 and parameters: {'n_estimators': 1000, 'learning_rate': 0.02, 'max_depth': 8, 'min_child_weight': 4, 'subsample': 0.6731438131407511, 'colsample_bytree': 0.6546834708751531}. Best is trial 23 with value: 0.4667636749872111.
[I 2025-09-08 21:04:13,657] A new study created in memory with name: no-name-180203ac-e24c-44d0-a559-dae046557dd3
[I 2025-09-08 21:04:13,784] Trial 0 finished with value: 0.47299228944318994 and parameters: {'learning_rate': 0.05, 'num_leaves': 30, 'max_depth': 7, 'min_child_samples': 4, 'subsample': 0.7110038914431904, 'colsample_bytree': 0.7106838495586849, 'n_estimators': 750, 'min_split_gain': 0.5}. Best is trial 0 with value: 0.47299228944318994.

✅ XGB con TOA_1x1_depth_in_3_4 - Mejor R2: 0.47
📋 Parámetros: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.6003150578900983, 'colsample_bytree': 0.6722968232084591}

Buscando mejores hiperparámetros para LBM con TOA_1x1_depth_in_3_4...
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 21:04:13,909] Trial 1 finished with value: 0.47188767182380453 and parameters: {'learning_rate': 0.04, 'num_leaves': 30, 'max_depth': 5, 'min_child_samples': 5, 'subsample': 0.7661674278854924, 'colsample_bytree': 0.7977857254187355, 'n_estimators': 1000, 'min_split_gain': 1.0}. Best is trial 0 with value: 0.47299228944318994.

Fold 3
Fold 1
Fold 2

[I 2025-09-08 21:04:14,169] Trial 2 finished with value: 0.4752606427759196 and parameters: {'learning_rate': 0.02, 'num_leaves': 30, 'max_depth': 5, 'min_child_samples': 5, 'subsample': 0.7066538869207213, 'colsample_bytree': 0.6038868940443085, 'n_estimators': 750, 'min_split_gain': 0.0}. Best is trial 2 with value: 0.4752606427759196.

Fold 3
Fold 1

[I 2025-09-08 21:04:14,474] Trial 3 finished with value: 0.4573700983760925 and parameters: {'learning_rate': 0.03, 'num_leaves': 10, 'max_depth': 8, 'min_child_samples': 6, 'subsample': 0.7401192351707251, 'colsample_bytree': 0.7551210680793288, 'n_estimators': 750, 'min_split_gain': 0.0}. Best is trial 2 with value: 0.4752606427759196.

Fold 2
Fold 3
Fold 1

[I 2025-09-08 21:04:14,630] Trial 4 finished with value: 0.46840773500813687 and parameters: {'learning_rate': 0.03, 'num_leaves': 10, 'max_depth': 7, 'min_child_samples': 4, 'subsample': 0.7586105251487798, 'colsample_bytree': 0.6242758065870565, 'n_estimators': 1250, 'min_split_gain': 0.5}. Best is trial 2 with value: 0.4752606427759196.

Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 21:04:14,814] Trial 5 finished with value: 0.4697895423737191 and parameters: {'learning_rate': 0.03, 'num_leaves': 30, 'max_depth': 7, 'min_child_samples': 4, 'subsample': 0.6540963015319415, 'colsample_bytree': 0.6838979169464126, 'n_estimators': 750, 'min_split_gain': 0.2}. Best is trial 2 with value: 0.4752606427759196.

Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:04:15,264] Trial 6 finished with value: 0.4497196748657996 and parameters: {'learning_rate': 0.05, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 5, 'subsample': 0.7785699319924748, 'colsample_bytree': 0.6620004605877027, 'n_estimators': 1250, 'min_split_gain': 0.0}. Best is trial 2 with value: 0.4752606427759196.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:04:15,512] Trial 7 finished with value: 0.4311383938493627 and parameters: {'learning_rate': 0.03, 'num_leaves': 30, 'max_depth': 7, 'min_child_samples': 6, 'subsample': 0.6561479812636526, 'colsample_bytree': 0.7664579199089734, 'n_estimators': 1000, 'min_split_gain': 0.1}. Best is trial 2 with value: 0.4752606427759196.
[I 2025-09-08 21:04:15,665] Trial 8 finished with value: 0.44143247271164915 and parameters: {'learning_rate': 0.05, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 7, 'subsample': 0.7358678753482035, 'colsample_bytree': 0.6960282428588068, 'n_estimators': 1250, 'min_split_gain': 0.5}. Best is trial 2 with value: 0.4752606427759196.

Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 21:04:15,834] Trial 9 finished with value: 0.4706216283711508 and parameters: {'learning_rate': 0.03, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 6, 'subsample': 0.6896760528600212, 'colsample_bytree': 0.7652373334081792, 'n_estimators': 1250, 'min_split_gain': 0.5}. Best is trial 2 with value: 0.4752606427759196.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:04:16,152] Trial 10 finished with value: 0.47456610600340693 and parameters: {'learning_rate': 0.02, 'num_leaves': 30, 'max_depth': 6, 'min_child_samples': 8, 'subsample': 0.6220437179754014, 'colsample_bytree': 0.6018765307051652, 'n_estimators': 750, 'min_split_gain': 0.0}. Best is trial 2 with value: 0.4752606427759196.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:04:16,472] Trial 11 finished with value: 0.47456610600340693 and parameters: {'learning_rate': 0.02, 'num_leaves': 30, 'max_depth': 6, 'min_child_samples': 8, 'subsample': 0.6009450946901009, 'colsample_bytree': 0.6020338218569092, 'n_estimators': 750, 'min_split_gain': 0.0}. Best is trial 2 with value: 0.4752606427759196.

Fold 1
Fold 2

[I 2025-09-08 21:04:16,829] Trial 12 finished with value: 0.4696006407212317 and parameters: {'learning_rate': 0.02, 'num_leaves': 30, 'max_depth': 6, 'min_child_samples': 8, 'subsample': 0.6066248774495184, 'colsample_bytree': 0.6385783179332963, 'n_estimators': 750, 'min_split_gain': 0.0}. Best is trial 2 with value: 0.4752606427759196.

Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:04:17,153] Trial 13 finished with value: 0.4510174549132766 and parameters: {'learning_rate': 0.02, 'num_leaves': 30, 'max_depth': 6, 'min_child_samples': 7, 'subsample': 0.6666730058888485, 'colsample_bytree': 0.6004556811560698, 'n_estimators': 750, 'min_split_gain': 0.0}. Best is trial 2 with value: 0.4752606427759196.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:04:17,396] Trial 14 finished with value: 0.4712111663468555 and parameters: {'learning_rate': 0.02, 'num_leaves': 30, 'max_depth': 5, 'min_child_samples': 5, 'subsample': 0.6997140217806603, 'colsample_bytree': 0.6320979602040976, 'n_estimators': 750, 'min_split_gain': 0.1}. Best is trial 2 with value: 0.4752606427759196.
[I 2025-09-08 21:04:17,563] Trial 15 finished with value: 0.470312409563643 and parameters: {'learning_rate': 0.02, 'num_leaves': 10, 'max_depth': 6, 'min_child_samples': 7, 'subsample': 0.6278578758839797, 'colsample_bytree': 0.6611149259273682, 'n_estimators': 750, 'min_split_gain': 1.0}. Best is trial 2 with value: 0.4752606427759196.

Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 21:04:17,737] Trial 16 finished with value: 0.46417496290409876 and parameters: {'learning_rate': 0.04, 'num_leaves': 30, 'max_depth': 5, 'min_child_samples': 8, 'subsample': 0.6781464332015844, 'colsample_bytree': 0.7235329891596989, 'n_estimators': 1000, 'min_split_gain': 0.2}. Best is trial 2 with value: 0.4752606427759196.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:04:18,071] Trial 17 finished with value: 0.4690071610825896 and parameters: {'learning_rate': 0.02, 'num_leaves': 30, 'max_depth': 6, 'min_child_samples': 5, 'subsample': 0.7960292819290986, 'colsample_bytree': 0.6556654917779994, 'n_estimators': 750, 'min_split_gain': 0.0}. Best is trial 2 with value: 0.4752606427759196.

Fold 1
Fold 2

[I 2025-09-08 21:04:18,516] Trial 18 finished with value: 0.4489608294189016 and parameters: {'learning_rate': 0.02, 'num_leaves': 20, 'max_depth': 8, 'min_child_samples': 7, 'subsample': 0.7137382112046646, 'colsample_bytree': 0.616746175609549, 'n_estimators': 750, 'min_split_gain': 0.0}. Best is trial 2 with value: 0.4752606427759196.

Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:04:18,846] Trial 19 finished with value: 0.48866407501151965 and parameters: {'learning_rate': 0.02, 'num_leaves': 10, 'max_depth': 5, 'min_child_samples': 5, 'subsample': 0.6261243462939043, 'colsample_bytree': 0.6448393863322003, 'n_estimators': 1000, 'min_split_gain': 0.0}. Best is trial 19 with value: 0.48866407501151965.
[I 2025-09-08 21:04:19,026] Trial 20 finished with value: 0.4702216601811264 and parameters: {'learning_rate': 0.04, 'num_leaves': 10, 'max_depth': 5, 'min_child_samples': 5, 'subsample': 0.6393415482988415, 'colsample_bytree': 0.6767482244491317, 'n_estimators': 1000, 'min_split_gain': 0.1}. Best is trial 19 with value: 0.48866407501151965.

Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 21:04:19,347] Trial 21 finished with value: 0.46733845433360816 and parameters: {'learning_rate': 0.02, 'num_leaves': 10, 'max_depth': 5, 'min_child_samples': 6, 'subsample': 0.6288044413346112, 'colsample_bytree': 0.6435324181458445, 'n_estimators': 1000, 'min_split_gain': 0.0}. Best is trial 19 with value: 0.48866407501151965.

Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 21:04:19,698] Trial 22 finished with value: 0.47322566779873565 and parameters: {'learning_rate': 0.02, 'num_leaves': 10, 'max_depth': 6, 'min_child_samples': 5, 'subsample': 0.6218031859908089, 'colsample_bytree': 0.616315009362592, 'n_estimators': 1000, 'min_split_gain': 0.0}. Best is trial 19 with value: 0.48866407501151965.

Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:04:20,102] Trial 23 finished with value: 0.4822114442506127 and parameters: {'learning_rate': 0.02, 'num_leaves': 10, 'max_depth': 5, 'min_child_samples': 4, 'subsample': 0.6474241943897693, 'colsample_bytree': 0.6020541094045122, 'n_estimators': 1000, 'min_split_gain': 0.0}. Best is trial 19 with value: 0.48866407501151965.

Fold 1
Fold 2

[I 2025-09-08 21:04:20,443] Trial 24 finished with value: 0.48343000136713843 and parameters: {'learning_rate': 0.02, 'num_leaves': 10, 'max_depth': 5, 'min_child_samples': 4, 'subsample': 0.6772585620908398, 'colsample_bytree': 0.6185731269982868, 'n_estimators': 1000, 'min_split_gain': 0.0}. Best is trial 19 with value: 0.48866407501151965.

Fold 3
Fold 1
Fold 2

[I 2025-09-08 21:04:20,662] Trial 25 finished with value: 0.4894281893491841 and parameters: {'learning_rate': 0.02, 'num_leaves': 10, 'max_depth': 5, 'min_child_samples': 4, 'subsample': 0.651334630057386, 'colsample_bytree': 0.6443291978265231, 'n_estimators': 1000, 'min_split_gain': 0.2}. Best is trial 25 with value: 0.4894281893491841.

Fold 3
Fold 1
Fold 2

[I 2025-09-08 21:04:20,887] Trial 26 finished with value: 0.4764973763444355 and parameters: {'learning_rate': 0.02, 'num_leaves': 10, 'max_depth': 5, 'min_child_samples': 4, 'subsample': 0.6752090488887624, 'colsample_bytree': 0.6496912764115299, 'n_estimators': 1000, 'min_split_gain': 0.2}. Best is trial 25 with value: 0.4894281893491841.

Fold 3
Fold 1
Fold 2

[I 2025-09-08 21:04:21,109] Trial 27 finished with value: 0.48039483164976526 and parameters: {'learning_rate': 0.02, 'num_leaves': 10, 'max_depth': 5, 'min_child_samples': 4, 'subsample': 0.6666678806821791, 'colsample_bytree': 0.6708446289050067, 'n_estimators': 1000, 'min_split_gain': 0.2}. Best is trial 25 with value: 0.4894281893491841.

Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:04:21,273] Trial 28 finished with value: 0.4786021079020612 and parameters: {'learning_rate': 0.04, 'num_leaves': 10, 'max_depth': 6, 'min_child_samples': 4, 'subsample': 0.6880856730047344, 'colsample_bytree': 0.6293606143786771, 'n_estimators': 1000, 'min_split_gain': 0.2}. Best is trial 25 with value: 0.4894281893491841.
[I 2025-09-08 21:04:21,401] Trial 29 finished with value: 0.46258730504002293 and parameters: {'learning_rate': 0.05, 'num_leaves': 10, 'max_depth': 5, 'min_child_samples': 4, 'subsample': 0.6396889752222285, 'colsample_bytree': 0.7031159466984266, 'n_estimators': 1000, 'min_split_gain': 1.0}. Best is trial 25 with value: 0.4894281893491841.
[I 2025-09-08 21:04:21,403] A new study created in memory with name: no-name-35799c2c-44fb-4070-95fc-f7a4bd715a54
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

✅ LBM con TOA_1x1_depth_in_3_4 - Mejor R2: 0.49
📋 Parámetros: {'learning_rate': 0.02, 'num_leaves': 10, 'max_depth': 5, 'min_child_samples': 4, 'subsample': 0.651334630057386, 'colsample_bytree': 0.6443291978265231, 'n_estimators': 1000, 'min_split_gain': 0.2}

Buscando mejores hiperparámetros para MLP con TOA_1x1_depth_in_3_4...
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 21:04:22,362] Trial 0 finished with value: 0.3615220881321724 and parameters: {'hidden_layer_sizes': (32,), 'activation': 'tanh', 'solver': 'adam', 'alpha': 3.5883921645979074e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.000543390215672742}. Best is trial 0 with value: 0.3615220881321724.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 21:04:23,223] Trial 1 finished with value: -0.07096336741393887 and parameters: {'hidden_layer_sizes': (64,), 'activation': 'relu', 'solver': 'adam', 'alpha': 0.000400582665501137, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0001609991598797513}. Best is trial 0 with value: 0.3615220881321724.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 21:04:24,023] Trial 2 finished with value: -0.12841178968212907 and parameters: {'hidden_layer_sizes': (32,), 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.00021124052276146204, 'learning_rate': 'adaptive', 'learning_rate_init': 0.000334833627332295}. Best is trial 0 with value: 0.3615220881321724.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 21:04:24,976] Trial 3 finished with value: 0.3055494839033056 and parameters: {'hidden_layer_sizes': (32,), 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.034561610134837294, 'learning_rate': 'adaptive', 'learning_rate_init': 0.001718660548944922}. Best is trial 0 with value: 0.3615220881321724.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 21:04:25,748] Trial 4 finished with value: 0.16037559018177883 and parameters: {'hidden_layer_sizes': (64,), 'activation': 'relu', 'solver': 'adam', 'alpha': 0.095175888412401, 'learning_rate': 'constant', 'learning_rate_init': 0.0004382003149935319}. Best is trial 0 with value: 0.3615220881321724.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 21:04:27,204] Trial 5 finished with value: 0.143513318645771 and parameters: {'hidden_layer_sizes': (128,), 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.0004481885985757747, 'learning_rate': 'constant', 'learning_rate_init': 0.0001366818130843964}. Best is trial 0 with value: 0.3615220881321724.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 21:04:28,201] Trial 6 finished with value: 0.3681527091676811 and parameters: {'hidden_layer_sizes': (32,), 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.0446205663889446, 'learning_rate': 'constant', 'learning_rate_init': 0.0032372472634263918}. Best is trial 6 with value: 0.3681527091676811.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 21:04:29,279] Trial 7 finished with value: 0.450933921498041 and parameters: {'hidden_layer_sizes': (32,), 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.0026197698966148823, 'learning_rate': 'adaptive', 'learning_rate_init': 0.008498929158762573}. Best is trial 7 with value: 0.450933921498041.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 21:04:29,853] Trial 8 finished with value: -0.13234272702809502 and parameters: {'hidden_layer_sizes': (32,), 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.00015437146457414797, 'learning_rate': 'constant', 'learning_rate_init': 0.00026015025552280274}. Best is trial 7 with value: 0.450933921498041.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 3
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 21:04:30,799] Trial 9 finished with value: 0.3381986799923095 and parameters: {'hidden_layer_sizes': (32,), 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.017318874306978215, 'learning_rate': 'constant', 'learning_rate_init': 0.002316795308360718}. Best is trial 7 with value: 0.450933921498041.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:04:31,893] Trial 10 finished with value: 0.49638601332727994 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.003108822176492307, 'learning_rate': 'adaptive', 'learning_rate_init': 0.009391205517669258}. Best is trial 10 with value: 0.49638601332727994.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:04:32,764] Trial 11 finished with value: 0.4952806212937819 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0036914490305656146, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00991604200235566}. Best is trial 10 with value: 0.49638601332727994.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 21:04:33,780] Trial 12 finished with value: 0.49201626311014196 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0032611258007805752, 'learning_rate': 'adaptive', 'learning_rate_init': 0.009344395397660498}. Best is trial 10 with value: 0.49638601332727994.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:04:34,648] Trial 13 finished with value: 0.527617060955751 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.007133747502647248, 'learning_rate': 'adaptive', 'learning_rate_init': 0.004664468554668095}. Best is trial 13 with value: 0.527617060955751.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:04:35,530] Trial 14 finished with value: 0.5273338390220763 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.010824814331210344, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0046128508623070694}. Best is trial 13 with value: 0.527617060955751.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:04:36,538] Trial 15 finished with value: 0.5275788164333982 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.011162136797113207, 'learning_rate': 'adaptive', 'learning_rate_init': 0.004662878007076277}. Best is trial 13 with value: 0.527617060955751.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 21:04:37,655] Trial 16 finished with value: 0.5205499942542108 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.011017626299941357, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0011360878101945384}. Best is trial 13 with value: 0.527617060955751.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 21:04:38,428] Trial 17 finished with value: 0.39618063550825083 and parameters: {'hidden_layer_sizes': (128,), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0008853528658032748, 'learning_rate': 'adaptive', 'learning_rate_init': 0.004223284262740997}. Best is trial 13 with value: 0.527617060955751.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

[I 2025-09-08 21:04:39,284] Trial 18 finished with value: 0.32000929437332876 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'relu', 'solver': 'adam', 'alpha': 0.00703461176916046, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0008470552521827676}. Best is trial 13 with value: 0.527617060955751.

Fold 3
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 2
Fold 3

[I 2025-09-08 21:04:40,342] Trial 19 finished with value: 0.5279810631083971 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'adam', 'alpha': 2.2451819062285724e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.004563295561385222}. Best is trial 19 with value: 0.5279810631083971.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 21:04:41,528] Trial 20 finished with value: 0.5253201287653241 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'adam', 'alpha': 1.0010347967640869e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00168744788628792}. Best is trial 19 with value: 0.5279810631083971.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:04:42,320] Trial 21 finished with value: 0.5268006423097237 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'adam', 'alpha': 6.598609840219324e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0053069868279958824}. Best is trial 19 with value: 0.5279810631083971.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:04:43,326] Trial 22 finished with value: 0.534833105671152 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0013800359843491696, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0029346290185890338}. Best is trial 22 with value: 0.534833105671152.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:04:44,197] Trial 23 finished with value: 0.5380079189310215 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0013385832287232742, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0026964964276903185}. Best is trial 23 with value: 0.5380079189310215.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 21:04:44,957] Trial 24 finished with value: 0.3406371384845581 and parameters: {'hidden_layer_sizes': (128,), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0010609007037838051, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0026032147559975384}. Best is trial 23 with value: 0.5380079189310215.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 21:04:45,846] Trial 25 finished with value: 0.43619538622682813 and parameters: {'hidden_layer_sizes': (64,), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0013607540712349464, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0014090602165198409}. Best is trial 23 with value: 0.5380079189310215.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2

[I 2025-09-08 21:04:46,539] Trial 26 finished with value: 0.344092206574262 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'relu', 'solver': 'adam', 'alpha': 1.0071465296578464e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0027104008749546187}. Best is trial 23 with value: 0.5380079189310215.

Fold 3
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 2
Fold 3

[I 2025-09-08 21:04:47,537] Trial 27 finished with value: 0.5300038162690398 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'adam', 'alpha': 4.051285792772917e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.006756161684980621}. Best is trial 23 with value: 0.5380079189310215.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:04:48,328] Trial 28 finished with value: 0.5309638480043054 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.00011401325406731372, 'learning_rate': 'adaptive', 'learning_rate_init': 0.006987453269890898}. Best is trial 23 with value: 0.5380079189310215.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 21:04:49,688] Trial 29 finished with value: 0.5086744041666178 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0001182637282694895, 'learning_rate': 'constant', 'learning_rate_init': 0.0007650396851577077}. Best is trial 23 with value: 0.5380079189310215.
[I 2025-09-08 21:04:49,691] A new study created in memory with name: no-name-fba5b22e-fe85-4dd7-8aae-7fbf578b7808
[I 2025-09-08 21:04:49,778] Trial 0 finished with value: 0.1448046633441511 and parameters: {'C': 0.4502454885322972, 'epsilon': 0.11468457003928645}. Best is trial 0 with value: 0.1448046633441511.
[I 2025-09-08 21:04:49,832] Trial 1 finished with value: 0.16007180171536317 and parameters: {'C': 0.5430116268348149, 'epsilon': 0.012857409085683507}. Best is trial 1 with value: 0.16007180171536317.
[I 2025-09-08 21:04:49,888] Trial 2 finished with value: 0.3918725598184471 and parameters: {'C': 3.0457689183644394, 'epsilon': 0.04373069375643859}. Best is trial 2 with value: 0.3918725598184471.

✅ MLP con TOA_1x1_depth_in_3_4 - Mejor R2: 0.54
📋 Parámetros: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0013385832287232742, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0026964964276903185}

Buscando mejores hiperparámetros para SVR con TOA_1x1_depth_in_3_4...
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 21:04:49,959] Trial 3 finished with value: -0.01567784416520579 and parameters: {'C': 0.12009945912122309, 'epsilon': 0.012832350102345923}. Best is trial 2 with value: 0.3918725598184471.
[I 2025-09-08 21:04:50,027] Trial 4 finished with value: -0.024114209566181193 and parameters: {'C': 0.10424520484594986, 'epsilon': 0.0772972017985754}. Best is trial 2 with value: 0.3918725598184471.
[I 2025-09-08 21:04:50,082] Trial 5 finished with value: 0.07960160256087205 and parameters: {'C': 0.2438692584520997, 'epsilon': 0.1935348482751557}. Best is trial 2 with value: 0.3918725598184471.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 21:04:50,141] Trial 6 finished with value: 0.3938678350749775 and parameters: {'C': 3.1214558945157984, 'epsilon': 0.05806833002752285}. Best is trial 6 with value: 0.3938678350749775.
[I 2025-09-08 21:04:50,198] Trial 7 finished with value: 0.131475020729201 and parameters: {'C': 0.38744094895521075, 'epsilon': 0.15208108449550733}. Best is trial 6 with value: 0.3938678350749775.
[I 2025-09-08 21:04:50,249] Trial 8 finished with value: 0.10926534982165921 and parameters: {'C': 0.35037750660550504, 'epsilon': 0.0644246864389605}. Best is trial 6 with value: 0.3938678350749775.
[I 2025-09-08 21:04:50,300] Trial 9 finished with value: 0.4360927471634848 and parameters: {'C': 4.777239895854169, 'epsilon': 0.16374237664570865}. Best is trial 9 with value: 0.4360927471634848.

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 21:04:50,362] Trial 10 finished with value: 0.5009230931455805 and parameters: {'C': 9.76163714745112, 'epsilon': 0.19931693282510068}. Best is trial 10 with value: 0.5009230931455805.
[I 2025-09-08 21:04:50,424] Trial 11 finished with value: 0.5004149130612762 and parameters: {'C': 9.571290639328216, 'epsilon': 0.19780414169784788}. Best is trial 10 with value: 0.5009230931455805.
[I 2025-09-08 21:04:50,481] Trial 12 finished with value: 0.49568099473138344 and parameters: {'C': 8.251363099410746, 'epsilon': 0.19966280303624256}. Best is trial 10 with value: 0.5009230931455805.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:04:50,538] Trial 13 finished with value: 0.3013132639619953 and parameters: {'C': 1.3348498284511103, 'epsilon': 0.15985534399213272}. Best is trial 10 with value: 0.5009230931455805.
[I 2025-09-08 21:04:50,601] Trial 14 finished with value: 0.5014550032657091 and parameters: {'C': 9.088899743688453, 'epsilon': 0.12433015609383098}. Best is trial 14 with value: 0.5014550032657091.
[I 2025-09-08 21:04:50,659] Trial 15 finished with value: 0.30149753734372303 and parameters: {'C': 1.3747187671434038, 'epsilon': 0.11630020097284685}. Best is trial 14 with value: 0.5014550032657091.
[I 2025-09-08 21:04:50,720] Trial 16 finished with value: 0.43965885025822765 and parameters: {'C': 4.918544341565706, 'epsilon': 0.09363388556732613}. Best is trial 14 with value: 0.5014550032657091.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 21:04:50,783] Trial 17 finished with value: 0.3740910859699043 and parameters: {'C': 2.494430210916729, 'epsilon': 0.1374960289647689}. Best is trial 14 with value: 0.5014550032657091.
[I 2025-09-08 21:04:50,849] Trial 18 finished with value: 0.4515880447754858 and parameters: {'C': 5.428219745489875, 'epsilon': 0.173622598181147}. Best is trial 14 with value: 0.5014550032657091.
[I 2025-09-08 21:04:50,907] Trial 19 finished with value: 0.23678430329306602 and parameters: {'C': 0.8434292435432771, 'epsilon': 0.13060966977745442}. Best is trial 14 with value: 0.5014550032657091.

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:04:50,969] Trial 20 finished with value: 0.35706258798134977 and parameters: {'C': 2.1830873304355967, 'epsilon': 0.09725356181218486}. Best is trial 14 with value: 0.5014550032657091.
[I 2025-09-08 21:04:51,035] Trial 21 finished with value: 0.5016399925282473 and parameters: {'C': 9.54466161452434, 'epsilon': 0.17825407572792584}. Best is trial 21 with value: 0.5016399925282473.
[I 2025-09-08 21:04:51,096] Trial 22 finished with value: 0.4781620023609327 and parameters: {'C': 6.887224635647937, 'epsilon': 0.1768856975164952}. Best is trial 21 with value: 0.5016399925282473.
[I 2025-09-08 21:04:51,157] Trial 23 finished with value: 0.49750735729261386 and parameters: {'C': 8.634357870301468, 'epsilon': 0.14451200764657074}. Best is trial 21 with value: 0.5016399925282473.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 21:04:51,221] Trial 24 finished with value: 0.42238052442412605 and parameters: {'C': 3.916902688308183, 'epsilon': 0.1806919514837771}. Best is trial 21 with value: 0.5016399925282473.
[I 2025-09-08 21:04:51,300] Trial 25 finished with value: 0.4722587167513372 and parameters: {'C': 6.440765104382779, 'epsilon': 0.18098453023825262}. Best is trial 21 with value: 0.5016399925282473.
[I 2025-09-08 21:04:51,374] Trial 26 finished with value: 0.33210246176116875 and parameters: {'C': 1.693699274059495, 'epsilon': 0.12981377820698187}. Best is trial 21 with value: 0.5016399925282473.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 21:04:51,444] Trial 27 finished with value: 0.5029685377449596 and parameters: {'C': 9.860960918627077, 'epsilon': 0.16456627405161972}. Best is trial 27 with value: 0.5029685377449596.
[I 2025-09-08 21:04:51,508] Trial 28 finished with value: 0.4162135374499652 and parameters: {'C': 3.6766249417525483, 'epsilon': 0.1618785046575335}. Best is trial 27 with value: 0.5029685377449596.
[I 2025-09-08 21:04:51,567] Trial 29 finished with value: 0.47474242010557194 and parameters: {'C': 6.744758992201873, 'epsilon': 0.11721757779477185}. Best is trial 27 with value: 0.5029685377449596.
[I 2025-09-08 21:04:51,569] A new study created in memory with name: no-name-af8cb03c-fedd-4df7-bb2c-d93bdc8436e8

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

✅ SVR con TOA_1x1_depth_in_3_4 - Mejor R2: 0.50
📋 Parámetros: {'C': 9.860960918627077, 'epsilon': 0.16456627405161972}

Buscando mejores hiperparámetros para KNN con TOA_1x1_depth_in_3_4...
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:04:51,613] Trial 0 finished with value: 0.37783971165572366 and parameters: {'n_neighbors': 3, 'leaf_size': 14}. Best is trial 0 with value: 0.37783971165572366.
[I 2025-09-08 21:04:51,664] Trial 1 finished with value: 0.38443090283400166 and parameters: {'n_neighbors': 9, 'leaf_size': 32}. Best is trial 1 with value: 0.38443090283400166.
[I 2025-09-08 21:04:51,709] Trial 2 finished with value: 0.3673979247345007 and parameters: {'n_neighbors': 11, 'leaf_size': 23}. Best is trial 1 with value: 0.38443090283400166.
[I 2025-09-08 21:04:51,752] Trial 3 finished with value: 0.38961382145916335 and parameters: {'n_neighbors': 6, 'leaf_size': 40}. Best is trial 3 with value: 0.38961382145916335.
[I 2025-09-08 21:04:51,798] Trial 4 finished with value: 0.400245895221455 and parameters: {'n_neighbors': 5, 'leaf_size': 23}. Best is trial 4 with value: 0.400245895221455.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 21:04:51,843] Trial 5 finished with value: 0.35516739816140097 and parameters: {'n_neighbors': 12, 'leaf_size': 37}. Best is trial 4 with value: 0.400245895221455.
[I 2025-09-08 21:04:51,894] Trial 6 finished with value: 0.37783971165572366 and parameters: {'n_neighbors': 3, 'leaf_size': 10}. Best is trial 4 with value: 0.400245895221455.
[I 2025-09-08 21:04:51,939] Trial 7 finished with value: 0.37578705492953657 and parameters: {'n_neighbors': 10, 'leaf_size': 18}. Best is trial 4 with value: 0.400245895221455.
[I 2025-09-08 21:04:51,982] Trial 8 finished with value: 0.37783971165572366 and parameters: {'n_neighbors': 3, 'leaf_size': 33}. Best is trial 4 with value: 0.400245895221455.
[I 2025-09-08 21:04:52,026] Trial 9 finished with value: 0.38443090283400166 and parameters: {'n_neighbors': 9, 'leaf_size': 15}. Best is trial 4 with value: 0.400245895221455.

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:04:52,087] Trial 10 finished with value: 0.38961382145916335 and parameters: {'n_neighbors': 6, 'leaf_size': 25}. Best is trial 4 with value: 0.400245895221455.
[I 2025-09-08 21:04:52,141] Trial 11 finished with value: 0.38961382145916335 and parameters: {'n_neighbors': 6, 'leaf_size': 40}. Best is trial 4 with value: 0.400245895221455.
[I 2025-09-08 21:04:52,196] Trial 12 finished with value: 0.38961382145916335 and parameters: {'n_neighbors': 6, 'leaf_size': 30}. Best is trial 4 with value: 0.400245895221455.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:04:52,245] Trial 13 finished with value: 0.400245895221455 and parameters: {'n_neighbors': 5, 'leaf_size': 21}. Best is trial 4 with value: 0.400245895221455.
[I 2025-09-08 21:04:52,360] Trial 14 finished with value: 0.400245895221455 and parameters: {'n_neighbors': 5, 'leaf_size': 20}. Best is trial 4 with value: 0.400245895221455.
[I 2025-09-08 21:04:52,418] Trial 15 finished with value: 0.38584284520702194 and parameters: {'n_neighbors': 4, 'leaf_size': 28}. Best is trial 4 with value: 0.400245895221455.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:04:52,469] Trial 16 finished with value: 0.3936162958902985 and parameters: {'n_neighbors': 8, 'leaf_size': 21}. Best is trial 4 with value: 0.400245895221455.
[I 2025-09-08 21:04:52,526] Trial 17 finished with value: 0.400245895221455 and parameters: {'n_neighbors': 5, 'leaf_size': 27}. Best is trial 4 with value: 0.400245895221455.
[I 2025-09-08 21:04:52,578] Trial 18 finished with value: 0.3896077215506751 and parameters: {'n_neighbors': 7, 'leaf_size': 17}. Best is trial 4 with value: 0.400245895221455.
[I 2025-09-08 21:04:52,633] Trial 19 finished with value: 0.38584284520702194 and parameters: {'n_neighbors': 4, 'leaf_size': 24}. Best is trial 4 with value: 0.400245895221455.
[I 2025-09-08 21:04:52,683] Trial 20 finished with value: 0.3896077215506751 and parameters: {'n_neighbors': 7, 'leaf_size': 10}. Best is trial 4 with value: 0.400245895221455.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:04:52,739] Trial 21 finished with value: 0.400245895221455 and parameters: {'n_neighbors': 5, 'leaf_size': 21}. Best is trial 4 with value: 0.400245895221455.
[I 2025-09-08 21:04:52,795] Trial 22 finished with value: 0.400245895221455 and parameters: {'n_neighbors': 5, 'leaf_size': 20}. Best is trial 4 with value: 0.400245895221455.
[I 2025-09-08 21:04:52,848] Trial 23 finished with value: 0.38584284520702194 and parameters: {'n_neighbors': 4, 'leaf_size': 18}. Best is trial 4 with value: 0.400245895221455.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:04:52,900] Trial 24 finished with value: 0.400245895221455 and parameters: {'n_neighbors': 5, 'leaf_size': 23}. Best is trial 4 with value: 0.400245895221455.
[I 2025-09-08 21:04:52,963] Trial 25 finished with value: 0.3936162958902985 and parameters: {'n_neighbors': 8, 'leaf_size': 26}. Best is trial 4 with value: 0.400245895221455.
[I 2025-09-08 21:04:53,015] Trial 26 finished with value: 0.38584284520702194 and parameters: {'n_neighbors': 4, 'leaf_size': 14}. Best is trial 4 with value: 0.400245895221455.
[I 2025-09-08 21:04:53,068] Trial 27 finished with value: 0.3896077215506751 and parameters: {'n_neighbors': 7, 'leaf_size': 20}. Best is trial 4 with value: 0.400245895221455.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:04:53,119] Trial 28 finished with value: 0.400245895221455 and parameters: {'n_neighbors': 5, 'leaf_size': 16}. Best is trial 4 with value: 0.400245895221455.
[I 2025-09-08 21:04:53,177] Trial 29 finished with value: 0.37783971165572366 and parameters: {'n_neighbors': 3, 'leaf_size': 12}. Best is trial 4 with value: 0.400245895221455.
[I 2025-09-08 21:04:53,178] A new study created in memory with name: no-name-9bffe975-1d86-46ba-8474-9c5deebf046e
[I 2025-09-08 21:04:53,222] Trial 0 finished with value: 0.11931689783295152 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 0 with value: 0.11931689783295152.
[I 2025-09-08 21:04:53,279] Trial 1 finished with value: 0.4472331796618876 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 1 with value: 0.4472331796618876.

Fold 1
Fold 2
Fold 3

✅ KNN con TOA_1x1_depth_in_3_4 - Mejor R2: 0.40
📋 Parámetros: {'n_neighbors': 5, 'leaf_size': 23}

Buscando mejores hiperparámetros para LR con TOA_1x1_depth_in_3_4...
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:04:53,341] Trial 2 finished with value: 0.4472331796618736 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 1 with value: 0.4472331796618876.
[I 2025-09-08 21:04:53,401] Trial 3 finished with value: 0.11931689783295152 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.4472331796618876.
[I 2025-09-08 21:04:53,464] Trial 4 finished with value: 0.4472331796618876 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 1 with value: 0.4472331796618876.
[I 2025-09-08 21:04:53,529] Trial 5 finished with value: 0.11931689783295152 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.4472331796618876.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 21:04:53,576] Trial 6 finished with value: 0.11931689783293035 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 1 with value: 0.4472331796618876.
[I 2025-09-08 21:04:53,624] Trial 7 finished with value: 0.11931689783295152 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.4472331796618876.
[I 2025-09-08 21:04:53,670] Trial 8 finished with value: 0.11931689783295152 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.4472331796618876.
[I 2025-09-08 21:04:53,713] Trial 9 finished with value: 0.11931689783293035 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 1 with value: 0.4472331796618876.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 21:04:53,773] Trial 10 finished with value: 0.4472331796618736 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 1 with value: 0.4472331796618876.
[I 2025-09-08 21:04:53,901] Trial 11 finished with value: 0.4472331796618876 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 1 with value: 0.4472331796618876.

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 21:04:54,087] Trial 12 finished with value: 0.4472331796618876 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 1 with value: 0.4472331796618876.
[I 2025-09-08 21:04:54,179] Trial 13 finished with value: 0.4472331796618876 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 1 with value: 0.4472331796618876.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 21:04:54,292] Trial 14 finished with value: 0.4472331796618876 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 1 with value: 0.4472331796618876.
[I 2025-09-08 21:04:54,374] Trial 15 finished with value: 0.4472331796618876 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 1 with value: 0.4472331796618876.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:04:54,468] Trial 16 finished with value: 0.4472331796618876 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 1 with value: 0.4472331796618876.
[I 2025-09-08 21:04:54,553] Trial 17 finished with value: 0.4472331796618876 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 1 with value: 0.4472331796618876.
[I 2025-09-08 21:04:54,655] Trial 18 finished with value: 0.4472331796618736 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 1 with value: 0.4472331796618876.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 21:04:54,739] Trial 19 finished with value: 0.4472331796618876 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 1 with value: 0.4472331796618876.
[I 2025-09-08 21:04:54,818] Trial 20 finished with value: 0.4472331796618876 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 1 with value: 0.4472331796618876.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:04:54,889] Trial 21 finished with value: 0.4472331796618876 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 1 with value: 0.4472331796618876.
[I 2025-09-08 21:04:54,958] Trial 22 finished with value: 0.4472331796618876 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 1 with value: 0.4472331796618876.
[I 2025-09-08 21:04:55,023] Trial 23 finished with value: 0.4472331796618876 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 1 with value: 0.4472331796618876.
[I 2025-09-08 21:04:55,087] Trial 24 finished with value: 0.4472331796618876 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 1 with value: 0.4472331796618876.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 21:04:55,187] Trial 25 finished with value: 0.4472331796618876 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 1 with value: 0.4472331796618876.
[I 2025-09-08 21:04:55,281] Trial 26 finished with value: 0.4472331796618736 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 1 with value: 0.4472331796618876.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 21:04:55,510] Trial 27 finished with value: 0.4472331796618876 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 1 with value: 0.4472331796618876.
[I 2025-09-08 21:04:55,583] Trial 28 finished with value: 0.4472331796618876 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 1 with value: 0.4472331796618876.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 21:04:55,674] Trial 29 finished with value: 0.4472331796618876 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 1 with value: 0.4472331796618876.
[I 2025-09-08 21:04:55,677] A new study created in memory with name: no-name-5f15116f-078a-465b-8573-cb4b5d942c35

Fold 3

✅ LR con TOA_1x1_depth_in_3_4 - Mejor R2: 0.45
📋 Parámetros: {'fit_intercept': False, 'positive': False}

Buscando mejores hiperparámetros para RF con TOA_1x1_depth_in_3_4...
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:04:58,368] Trial 0 finished with value: 0.20136975065907556 and parameters: {'n_estimators': 200, 'max_depth': 6, 'min_samples_split': 6, 'min_samples_leaf': 7, 'bootstrap': False}. Best is trial 0 with value: 0.20136975065907556.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:05:00,129] Trial 1 finished with value: 0.19430889565519685 and parameters: {'n_estimators': 100, 'max_depth': 11, 'min_samples_split': 4, 'min_samples_leaf': 5, 'bootstrap': False}. Best is trial 0 with value: 0.20136975065907556.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:05:06,601] Trial 2 finished with value: 0.20332441584780192 and parameters: {'n_estimators': 400, 'max_depth': 8, 'min_samples_split': 3, 'min_samples_leaf': 5, 'bootstrap': False}. Best is trial 2 with value: 0.20332441584780192.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:05:12,582] Trial 3 finished with value: 0.2212427609332229 and parameters: {'n_estimators': 400, 'max_depth': 9, 'min_samples_split': 6, 'min_samples_leaf': 8, 'bootstrap': False}. Best is trial 3 with value: 0.2212427609332229.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:05:15,537] Trial 4 finished with value: 0.19282930667250273 and parameters: {'n_estimators': 200, 'max_depth': 7, 'min_samples_split': 5, 'min_samples_leaf': 6, 'bootstrap': False}. Best is trial 3 with value: 0.2212427609332229.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:05:17,081] Trial 5 finished with value: 0.17483973892373936 and parameters: {'n_estimators': 100, 'max_depth': 7, 'min_samples_split': 7, 'min_samples_leaf': 4, 'bootstrap': False}. Best is trial 3 with value: 0.2212427609332229.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:05:20,845] Trial 6 finished with value: 0.12103263165601608 and parameters: {'n_estimators': 200, 'max_depth': 10, 'min_samples_split': 2, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 3 with value: 0.2212427609332229.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:05:24,815] Trial 7 finished with value: 0.3400168472771686 and parameters: {'n_estimators': 400, 'max_depth': 9, 'min_samples_split': 8, 'min_samples_leaf': 6, 'bootstrap': True}. Best is trial 7 with value: 0.3400168472771686.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:05:30,694] Trial 8 finished with value: 0.19338552434500833 and parameters: {'n_estimators': 400, 'max_depth': 7, 'min_samples_split': 4, 'min_samples_leaf': 6, 'bootstrap': False}. Best is trial 7 with value: 0.3400168472771686.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:05:32,371] Trial 9 finished with value: 0.31603391655838936 and parameters: {'n_estimators': 200, 'max_depth': 5, 'min_samples_split': 3, 'min_samples_leaf': 6, 'bootstrap': True}. Best is trial 7 with value: 0.3400168472771686.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:05:37,253] Trial 10 finished with value: 0.3830952646612524 and parameters: {'n_estimators': 400, 'max_depth': 12, 'min_samples_split': 8, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 10 with value: 0.3830952646612524.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:05:42,422] Trial 11 finished with value: 0.38409883013238444 and parameters: {'n_estimators': 400, 'max_depth': 12, 'min_samples_split': 8, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 11 with value: 0.38409883013238444.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:05:47,594] Trial 12 finished with value: 0.38409883013238444 and parameters: {'n_estimators': 400, 'max_depth': 12, 'min_samples_split': 8, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 11 with value: 0.38409883013238444.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:05:52,888] Trial 13 finished with value: 0.39097147891432166 and parameters: {'n_estimators': 400, 'max_depth': 12, 'min_samples_split': 7, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 13 with value: 0.39097147891432166.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:05:58,064] Trial 14 finished with value: 0.39021669489978367 and parameters: {'n_estimators': 400, 'max_depth': 11, 'min_samples_split': 7, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 13 with value: 0.39097147891432166.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:06:02,922] Trial 15 finished with value: 0.3947108654274493 and parameters: {'n_estimators': 400, 'max_depth': 10, 'min_samples_split': 6, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 15 with value: 0.3947108654274493.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:06:04,163] Trial 16 finished with value: 0.38803825404604936 and parameters: {'n_estimators': 100, 'max_depth': 10, 'min_samples_split': 6, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 15 with value: 0.3947108654274493.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:06:08,790] Trial 17 finished with value: 0.3754143508097452 and parameters: {'n_estimators': 400, 'max_depth': 11, 'min_samples_split': 7, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 15 with value: 0.3947108654274493.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:06:13,350] Trial 18 finished with value: 0.37517697057609006 and parameters: {'n_estimators': 400, 'max_depth': 10, 'min_samples_split': 5, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 15 with value: 0.3947108654274493.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:06:14,597] Trial 19 finished with value: 0.38882437558552807 and parameters: {'n_estimators': 100, 'max_depth': 11, 'min_samples_split': 5, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 15 with value: 0.3947108654274493.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:06:19,533] Trial 20 finished with value: 0.38766458736449966 and parameters: {'n_estimators': 400, 'max_depth': 9, 'min_samples_split': 7, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 15 with value: 0.3947108654274493.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:06:24,710] Trial 21 finished with value: 0.39021669489978367 and parameters: {'n_estimators': 400, 'max_depth': 11, 'min_samples_split': 7, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 15 with value: 0.3947108654274493.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:06:30,050] Trial 22 finished with value: 0.39668235894426607 and parameters: {'n_estimators': 400, 'max_depth': 12, 'min_samples_split': 6, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 22 with value: 0.39668235894426607.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:06:34,976] Trial 23 finished with value: 0.3958968124399904 and parameters: {'n_estimators': 400, 'max_depth': 12, 'min_samples_split': 6, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 22 with value: 0.39668235894426607.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:06:39,519] Trial 24 finished with value: 0.37517697057609006 and parameters: {'n_estimators': 400, 'max_depth': 10, 'min_samples_split': 6, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 22 with value: 0.39668235894426607.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:06:44,542] Trial 25 finished with value: 0.3958968124399904 and parameters: {'n_estimators': 400, 'max_depth': 12, 'min_samples_split': 6, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 22 with value: 0.39668235894426607.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:06:49,527] Trial 26 finished with value: 0.3958968124399904 and parameters: {'n_estimators': 400, 'max_depth': 12, 'min_samples_split': 4, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 22 with value: 0.39668235894426607.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:06:54,134] Trial 27 finished with value: 0.3753854886402747 and parameters: {'n_estimators': 400, 'max_depth': 12, 'min_samples_split': 5, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 22 with value: 0.39668235894426607.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:06:56,648] Trial 28 finished with value: 0.393750945857964 and parameters: {'n_estimators': 200, 'max_depth': 11, 'min_samples_split': 6, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 22 with value: 0.39668235894426607.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:06:57,450] Trial 29 finished with value: 0.296712996101672 and parameters: {'n_estimators': 100, 'max_depth': 5, 'min_samples_split': 6, 'min_samples_leaf': 8, 'bootstrap': True}. Best is trial 22 with value: 0.39668235894426607.
[I 2025-09-08 21:06:57,451] A new study created in memory with name: no-name-23c0bc79-d777-487c-aff9-49a7e6187992

✅ RF con TOA_1x1_depth_in_3_4 - Mejor R2: 0.40
📋 Parámetros: {'n_estimators': 400, 'max_depth': 12, 'min_samples_split': 6, 'min_samples_leaf': 2, 'bootstrap': True}

Buscando mejores hiperparámetros para CAT con TOA_1x1_depth_in_3_4...
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:06:59,734] Trial 0 finished with value: 0.4897488799234633 and parameters: {'iterations': 500, 'learning_rate': 0.02, 'depth': 6, 'l2_leaf_reg': 3.1108860704647516}. Best is trial 0 with value: 0.4897488799234633.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:07:25,407] Trial 1 finished with value: 0.491718957411775 and parameters: {'iterations': 1000, 'learning_rate': 0.02, 'depth': 8, 'l2_leaf_reg': 4.368067040408748}. Best is trial 1 with value: 0.491718957411775.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:07:27,586] Trial 2 finished with value: 0.5068695669275203 and parameters: {'iterations': 750, 'learning_rate': 0.02, 'depth': 5, 'l2_leaf_reg': 1.114656920727446}. Best is trial 2 with value: 0.5068695669275203.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:07:29,025] Trial 3 finished with value: 0.4829121652854866 and parameters: {'iterations': 750, 'learning_rate': 0.05, 'depth': 4, 'l2_leaf_reg': 2.131579576731415}. Best is trial 2 with value: 0.5068695669275203.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:07:30,141] Trial 4 finished with value: 0.49250850364131066 and parameters: {'iterations': 500, 'learning_rate': 0.04, 'depth': 4, 'l2_leaf_reg': 1.6896132257771725}. Best is trial 2 with value: 0.5068695669275203.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:07:35,539] Trial 5 finished with value: 0.5117962033960078 and parameters: {'iterations': 500, 'learning_rate': 0.04, 'depth': 7, 'l2_leaf_reg': 2.7529495823871755}. Best is trial 5 with value: 0.5117962033960078.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:07:37,074] Trial 6 finished with value: 0.49388704889841156 and parameters: {'iterations': 500, 'learning_rate': 0.02, 'depth': 5, 'l2_leaf_reg': 1.721026579879093}. Best is trial 5 with value: 0.5117962033960078.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:08:02,949] Trial 7 finished with value: 0.5108930310342611 and parameters: {'iterations': 1000, 'learning_rate': 0.03, 'depth': 8, 'l2_leaf_reg': 2.9682121722118855}. Best is trial 5 with value: 0.5117962033960078.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:08:28,727] Trial 8 finished with value: 0.4927973172744185 and parameters: {'iterations': 1000, 'learning_rate': 0.04, 'depth': 8, 'l2_leaf_reg': 4.102389343360631}. Best is trial 5 with value: 0.5117962033960078.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:08:30,736] Trial 9 finished with value: 0.48001038139022684 and parameters: {'iterations': 1000, 'learning_rate': 0.05, 'depth': 4, 'l2_leaf_reg': 4.6200423457345}. Best is trial 5 with value: 0.5117962033960078.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:08:36,008] Trial 10 finished with value: 0.5164359603735377 and parameters: {'iterations': 500, 'learning_rate': 0.04, 'depth': 7, 'l2_leaf_reg': 3.331635761198955}. Best is trial 10 with value: 0.5164359603735377.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:08:41,295] Trial 11 finished with value: 0.5019420717274944 and parameters: {'iterations': 500, 'learning_rate': 0.04, 'depth': 7, 'l2_leaf_reg': 3.260666107495944}. Best is trial 10 with value: 0.5164359603735377.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:08:46,683] Trial 12 finished with value: 0.5040382754886962 and parameters: {'iterations': 500, 'learning_rate': 0.04, 'depth': 7, 'l2_leaf_reg': 3.7937266349696257}. Best is trial 10 with value: 0.5164359603735377.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:08:52,031] Trial 13 finished with value: 0.5082078117994541 and parameters: {'iterations': 500, 'learning_rate': 0.04, 'depth': 7, 'l2_leaf_reg': 2.465351808233919}. Best is trial 10 with value: 0.5164359603735377.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:08:54,378] Trial 14 finished with value: 0.4928500055582892 and parameters: {'iterations': 500, 'learning_rate': 0.03, 'depth': 6, 'l2_leaf_reg': 3.6711537924832114}. Best is trial 10 with value: 0.5164359603735377.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:08:59,739] Trial 15 finished with value: 0.5092635061588058 and parameters: {'iterations': 500, 'learning_rate': 0.04, 'depth': 7, 'l2_leaf_reg': 2.690657232912075}. Best is trial 10 with value: 0.5164359603735377.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:09:03,411] Trial 16 finished with value: 0.4948557385745496 and parameters: {'iterations': 750, 'learning_rate': 0.04, 'depth': 6, 'l2_leaf_reg': 4.957799297704959}. Best is trial 10 with value: 0.5164359603735377.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:09:08,727] Trial 17 finished with value: 0.500569773885445 and parameters: {'iterations': 500, 'learning_rate': 0.04, 'depth': 7, 'l2_leaf_reg': 3.504598627199538}. Best is trial 10 with value: 0.5164359603735377.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:09:10,139] Trial 18 finished with value: 0.5078588975344595 and parameters: {'iterations': 500, 'learning_rate': 0.03, 'depth': 5, 'l2_leaf_reg': 2.3158804764037995}. Best is trial 10 with value: 0.5164359603735377.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:09:29,479] Trial 19 finished with value: 0.5116942163597029 and parameters: {'iterations': 750, 'learning_rate': 0.05, 'depth': 8, 'l2_leaf_reg': 2.776382249448318}. Best is trial 10 with value: 0.5164359603735377.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:09:34,928] Trial 20 finished with value: 0.5166344624808102 and parameters: {'iterations': 500, 'learning_rate': 0.04, 'depth': 7, 'l2_leaf_reg': 1.9519631134428785}. Best is trial 20 with value: 0.5166344624808102.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:09:40,140] Trial 21 finished with value: 0.5090170405592621 and parameters: {'iterations': 500, 'learning_rate': 0.04, 'depth': 7, 'l2_leaf_reg': 1.9251377885082395}. Best is trial 20 with value: 0.5166344624808102.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:09:42,543] Trial 22 finished with value: 0.49403479538024603 and parameters: {'iterations': 500, 'learning_rate': 0.04, 'depth': 6, 'l2_leaf_reg': 1.3431436708828635}. Best is trial 20 with value: 0.5166344624808102.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:09:47,859] Trial 23 finished with value: 0.514277122942686 and parameters: {'iterations': 500, 'learning_rate': 0.04, 'depth': 7, 'l2_leaf_reg': 2.5170004063094504}. Best is trial 20 with value: 0.5166344624808102.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:10:00,760] Trial 24 finished with value: 0.5129288442614767 and parameters: {'iterations': 500, 'learning_rate': 0.04, 'depth': 8, 'l2_leaf_reg': 2.3995895507151226}. Best is trial 20 with value: 0.5166344624808102.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:10:06,077] Trial 25 finished with value: 0.5117606205351145 and parameters: {'iterations': 500, 'learning_rate': 0.04, 'depth': 7, 'l2_leaf_reg': 1.54629586629734}. Best is trial 20 with value: 0.5166344624808102.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:10:08,567] Trial 26 finished with value: 0.5037213072114461 and parameters: {'iterations': 500, 'learning_rate': 0.04, 'depth': 6, 'l2_leaf_reg': 2.0046894399390216}. Best is trial 20 with value: 0.5166344624808102.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:10:13,888] Trial 27 finished with value: 0.49506392005137373 and parameters: {'iterations': 500, 'learning_rate': 0.03, 'depth': 7, 'l2_leaf_reg': 3.292508516141091}. Best is trial 20 with value: 0.5166344624808102.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:10:39,736] Trial 28 finished with value: 0.5126526604148925 and parameters: {'iterations': 1000, 'learning_rate': 0.05, 'depth': 8, 'l2_leaf_reg': 1.024809771561743}. Best is trial 20 with value: 0.5166344624808102.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:10:43,410] Trial 29 finished with value: 0.5033289761245667 and parameters: {'iterations': 750, 'learning_rate': 0.02, 'depth': 6, 'l2_leaf_reg': 3.0545675960203167}. Best is trial 20 with value: 0.5166344624808102.
[I 2025-09-08 21:10:43,412] A new study created in memory with name: no-name-22263754-6450-4a2a-aeb2-e347947ee54d
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.826e-01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.224e-01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.282e-02, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:10:43,506] Trial 0 finished with value: 0.3132408172004005 and parameters: {'alpha': 0.03923827820300082, 'l1_ratio': 0.121869619934865}. Best is trial 0 with value: 0.3132408172004005.
[I 2025-09-08 21:10:43,567] Trial 1 finished with value: 0.032274680061872285 and parameters: {'alpha': 0.46305194017065393, 'l1_ratio': 0.49998688136750036}. Best is trial 0 with value: 0.3132408172004005.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.956e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(

✅ CAT con TOA_1x1_depth_in_3_4 - Mejor R2: 0.52
📋 Parámetros: {'iterations': 500, 'learning_rate': 0.04, 'depth': 7, 'l2_leaf_reg': 1.9519631134428785}

Buscando mejores hiperparámetros para ELN con TOA_1x1_depth_in_3_4...
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.987e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.042e+02, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:10:43,659] Trial 2 finished with value: 0.44612684989574847 and parameters: {'alpha': 0.0002524090842424618, 'l1_ratio': 0.2916229549720397}. Best is trial 2 with value: 0.44612684989574847.
[I 2025-09-08 21:10:43,766] Trial 3 finished with value: 0.027917580768509326 and parameters: {'alpha': 0.20739594934990901, 'l1_ratio': 0.7674130495459436}. Best is trial 2 with value: 0.44612684989574847.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.051e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.295e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.136e+01, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:10:43,907] Trial 4 finished with value: 0.44444398612388625 and parameters: {'alpha': 0.0003869323634187381, 'l1_ratio': 0.6235961645995329}. Best is trial 2 with value: 0.44612684989574847.
[I 2025-09-08 21:10:44,029] Trial 5 finished with value: 0.30682649094862113 and parameters: {'alpha': 0.01793968880696631, 'l1_ratio': 0.7466191035945701}. Best is trial 2 with value: 0.44612684989574847.

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.095e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.196e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.055e+02, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:10:44,166] Trial 6 finished with value: 0.4467862621557061 and parameters: {'alpha': 0.0001910062142219051, 'l1_ratio': 0.31027505061672}. Best is trial 6 with value: 0.4467862621557061.
[I 2025-09-08 21:10:44,260] Trial 7 finished with value: 0.03958105216858254 and parameters: {'alpha': 0.18858887767760169, 'l1_ratio': 0.6819944260819828}. Best is trial 6 with value: 0.4467862621557061.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.934e+00, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.749e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.189e+01, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:10:44,371] Trial 8 finished with value: 0.42088973885712216 and parameters: {'alpha': 0.001900832854590338, 'l1_ratio': 0.8856439565389234}. Best is trial 6 with value: 0.4467862621557061.
[I 2025-09-08 21:10:44,505] Trial 9 finished with value: 0.047916422692379425 and parameters: {'alpha': 0.42099616204151025, 'l1_ratio': 0.2483773510288943}. Best is trial 6 with value: 0.4467862621557061.

Fold 3
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.325e+00, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.496e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.480e+01, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:10:44,690] Trial 10 finished with value: 0.4228541353812707 and parameters: {'alpha': 0.0023733980161297335, 'l1_ratio': 0.44358517224548916}. Best is trial 6 with value: 0.4467862621557061.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.247e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.369e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.064e+02, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:10:44,832] Trial 11 finished with value: 0.44728233392252364 and parameters: {'alpha': 0.0001388929718875052, 'l1_ratio': 0.3218637003005127}. Best is trial 11 with value: 0.44728233392252364.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.286e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.433e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.067e+02, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:10:44,969] Trial 12 finished with value: 0.4474162500052632 and parameters: {'alpha': 0.00010648968394027482, 'l1_ratio': 0.34856221307081736}. Best is trial 12 with value: 0.4474162500052632.

Fold 3
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.229e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.373e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.060e+02, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:10:45,083] Trial 13 finished with value: 0.4474278257487021 and parameters: {'alpha': 0.00010464334389147273, 'l1_ratio': 0.40221380088256337}. Best is trial 13 with value: 0.4474278257487021.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.251e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.704e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.084e+01, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:10:45,199] Trial 14 finished with value: 0.42737195468450967 and parameters: {'alpha': 0.001671486173344574, 'l1_ratio': 0.42759797232578817}. Best is trial 13 with value: 0.4474278257487021.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.058e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.807e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.852e+01, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:10:45,313] Trial 15 finished with value: 0.4402118462416717 and parameters: {'alpha': 0.0006476644906158769, 'l1_ratio': 0.1647791358321175}. Best is trial 13 with value: 0.4474278257487021.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.299e-01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.899e+00, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.242e-02, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:10:45,435] Trial 16 finished with value: 0.3933041015532517 and parameters: {'alpha': 0.006533535829154325, 'l1_ratio': 0.5728816936483857}. Best is trial 13 with value: 0.4474278257487021.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.834e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.308e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.693e+01, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:10:45,556] Trial 17 finished with value: 0.4403976603688153 and parameters: {'alpha': 0.0006441428246319273, 'l1_ratio': 0.39439118127138506}. Best is trial 13 with value: 0.4474278257487021.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.019e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.306e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.594e+01, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:10:45,676] Trial 18 finished with value: 0.43614569531964165 and parameters: {'alpha': 0.0008889354415839266, 'l1_ratio': 0.21759451101052135}. Best is trial 13 with value: 0.4474278257487021.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.705e+00, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.733e+00, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.579e+00, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:10:45,797] Trial 19 finished with value: 0.39898931092732726 and parameters: {'alpha': 0.0061412360694407175, 'l1_ratio': 0.36452504234799216}. Best is trial 13 with value: 0.4474278257487021.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.001e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.125e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.036e+02, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:10:45,909] Trial 20 finished with value: 0.44736490627404774 and parameters: {'alpha': 0.00012398154551175443, 'l1_ratio': 0.5230060252001447}. Best is trial 13 with value: 0.4474278257487021.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.950e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.063e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.030e+02, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:10:46,037] Trial 21 finished with value: 0.4473748608268869 and parameters: {'alpha': 0.00013322271085378922, 'l1_ratio': 0.528505741454602}. Best is trial 13 with value: 0.4474278257487021.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.106e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.242e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.047e+02, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:10:46,160] Trial 22 finished with value: 0.44743145873553375 and parameters: {'alpha': 0.00010998242942100706, 'l1_ratio': 0.4900955079492201}. Best is trial 22 with value: 0.44743145873553375.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.622e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.694e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.853e+01, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:10:46,276] Trial 23 finished with value: 0.4439698373547027 and parameters: {'alpha': 0.0004110682117016835, 'l1_ratio': 0.4584989009821009}. Best is trial 22 with value: 0.44743145873553375.

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.683e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.611e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.010e+02, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:10:46,388] Trial 24 finished with value: 0.44576633699027407 and parameters: {'alpha': 0.00028004403204044546, 'l1_ratio': 0.3484088579687585}. Best is trial 22 with value: 0.44743145873553375.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.970e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.110e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.031e+02, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:10:46,524] Trial 25 finished with value: 0.44742374390359113 and parameters: {'alpha': 0.00010776509335862226, 'l1_ratio': 0.608617687804773}. Best is trial 22 with value: 0.44743145873553375.

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.733e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.287e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.413e+01, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:10:46,644] Trial 26 finished with value: 0.43082005807650336 and parameters: {'alpha': 0.0012462631439127167, 'l1_ratio': 0.6081965519572183}. Best is trial 22 with value: 0.44743145873553375.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.772e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.151e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.665e+01, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:10:46,747] Trial 27 finished with value: 0.4442385743770467 and parameters: {'alpha': 0.00039313458776802973, 'l1_ratio': 0.6877668869817161}. Best is trial 22 with value: 0.44743145873553375.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.149e+00, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.466e+00, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.986e+00, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:10:46,861] Trial 28 finished with value: 0.4101069728390292 and parameters: {'alpha': 0.003549565075612698, 'l1_ratio': 0.5724486084161327}. Best is trial 22 with value: 0.44743145873553375.
[I 2025-09-08 21:10:46,954] Trial 29 finished with value: 0.20672677603482906 and parameters: {'alpha': 0.03314384329238902, 'l1_ratio': 0.8612682140096255}. Best is trial 22 with value: 0.44743145873553375.
[I 2025-09-08 21:10:46,956] A new study created in memory with name: no-name-6e3023ff-4b84-46b1-a195-9a9d00bdbea1

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

✅ ELN con TOA_1x1_depth_in_3_4 - Mejor R2: 0.45
📋 Parámetros: {'alpha': 0.00010998242942100706, 'l1_ratio': 0.4900955079492201}

Buscando mejores hiperparámetros para XGB con TOA_15x15_depth_in_3_4...
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:10:51,318] Trial 0 finished with value: 0.360588636773842 and parameters: {'n_estimators': 1000, 'learning_rate': 0.03, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.6729865957834541, 'colsample_bytree': 0.6645814146792806}. Best is trial 0 with value: 0.360588636773842.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:10:58,905] Trial 1 finished with value: 0.4091874821834365 and parameters: {'n_estimators': 1250, 'learning_rate': 0.01, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.6202853401003425, 'colsample_bytree': 0.7573757063343988}. Best is trial 1 with value: 0.4091874821834365.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:11:01,814] Trial 2 finished with value: 0.3765115677465977 and parameters: {'n_estimators': 750, 'learning_rate': 0.03, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.6822437933721102, 'colsample_bytree': 0.7227494382355246}. Best is trial 1 with value: 0.4091874821834365.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:11:09,169] Trial 3 finished with value: 0.33891620048759874 and parameters: {'n_estimators': 1250, 'learning_rate': 0.03, 'max_depth': 8, 'min_child_weight': 4, 'subsample': 0.6485414932389205, 'colsample_bytree': 0.6332224994020947}. Best is trial 1 with value: 0.4091874821834365.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:11:13,586] Trial 4 finished with value: 0.40639903847592995 and parameters: {'n_estimators': 1000, 'learning_rate': 0.03, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.6181555751148252, 'colsample_bytree': 0.7198781525431381}. Best is trial 1 with value: 0.4091874821834365.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:11:19,437] Trial 5 finished with value: 0.35253453874596324 and parameters: {'n_estimators': 1250, 'learning_rate': 0.03, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.7077633274690429, 'colsample_bytree': 0.70092987747187}. Best is trial 1 with value: 0.4091874821834365.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:11:23,610] Trial 6 finished with value: 0.3853318974479502 and parameters: {'n_estimators': 1000, 'learning_rate': 0.02, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.7265977448504947, 'colsample_bytree': 0.7368220909720988}. Best is trial 1 with value: 0.4091874821834365.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:11:28,057] Trial 7 finished with value: 0.37999508025253875 and parameters: {'n_estimators': 750, 'learning_rate': 0.02, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.7219646950111381, 'colsample_bytree': 0.7322758719003577}. Best is trial 1 with value: 0.4091874821834365.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:11:32,843] Trial 8 finished with value: 0.43751178722992196 and parameters: {'n_estimators': 750, 'learning_rate': 0.01, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.6222990042184315, 'colsample_bytree': 0.7734189792209094}. Best is trial 8 with value: 0.43751178722992196.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:11:39,877] Trial 9 finished with value: 0.43611970434406394 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 8, 'min_child_weight': 2, 'subsample': 0.7572041547387327, 'colsample_bytree': 0.6705557029074175}. Best is trial 8 with value: 0.43751178722992196.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:11:43,992] Trial 10 finished with value: 0.444264816871003 and parameters: {'n_estimators': 750, 'learning_rate': 0.01, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.7778936464138879, 'colsample_bytree': 0.7999001640537932}. Best is trial 10 with value: 0.444264816871003.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:11:48,311] Trial 11 finished with value: 0.4395099375285523 and parameters: {'n_estimators': 750, 'learning_rate': 0.01, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.7959633805700466, 'colsample_bytree': 0.7990293922150647}. Best is trial 10 with value: 0.444264816871003.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:11:52,565] Trial 12 finished with value: 0.43953814426537835 and parameters: {'n_estimators': 750, 'learning_rate': 0.01, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.7895217818772698, 'colsample_bytree': 0.7997104134952224}. Best is trial 10 with value: 0.444264816871003.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:11:56,483] Trial 13 finished with value: 0.438394720015903 and parameters: {'n_estimators': 750, 'learning_rate': 0.01, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.7981243190040876, 'colsample_bytree': 0.7948294733870672}. Best is trial 10 with value: 0.444264816871003.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:12:00,190] Trial 14 finished with value: 0.41619326291517905 and parameters: {'n_estimators': 750, 'learning_rate': 0.01, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.7607453418524651, 'colsample_bytree': 0.7648493935308078}. Best is trial 10 with value: 0.444264816871003.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:12:04,551] Trial 15 finished with value: 0.4441272744460943 and parameters: {'n_estimators': 750, 'learning_rate': 0.01, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.7649592476452152, 'colsample_bytree': 0.7806277956144325}. Best is trial 10 with value: 0.444264816871003.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:12:09,675] Trial 16 finished with value: 0.44060418355035874 and parameters: {'n_estimators': 750, 'learning_rate': 0.01, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.7626212628526837, 'colsample_bytree': 0.7716051825000929}. Best is trial 10 with value: 0.444264816871003.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:12:14,080] Trial 17 finished with value: 0.4367678189282129 and parameters: {'n_estimators': 750, 'learning_rate': 0.02, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.7409877962519886, 'colsample_bytree': 0.7543299771051346}. Best is trial 10 with value: 0.444264816871003.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:12:18,147] Trial 18 finished with value: 0.4238741333911982 and parameters: {'n_estimators': 750, 'learning_rate': 0.01, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.7744079408197146, 'colsample_bytree': 0.6097133182927934}. Best is trial 10 with value: 0.444264816871003.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:12:23,820] Trial 19 finished with value: 0.4423743793609325 and parameters: {'n_estimators': 1250, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.7389986625593501, 'colsample_bytree': 0.781013141648978}. Best is trial 10 with value: 0.444264816871003.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:12:27,707] Trial 20 finished with value: 0.44126415402295743 and parameters: {'n_estimators': 750, 'learning_rate': 0.02, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.7775404862215468, 'colsample_bytree': 0.6713776641675441}. Best is trial 10 with value: 0.444264816871003.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:12:33,180] Trial 21 finished with value: 0.4432998287693776 and parameters: {'n_estimators': 1250, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.741964658009775, 'colsample_bytree': 0.7873457920192306}. Best is trial 10 with value: 0.444264816871003.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:12:38,505] Trial 22 finished with value: 0.43985403871118134 and parameters: {'n_estimators': 1250, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.7465972521486254, 'colsample_bytree': 0.7464186285405695}. Best is trial 10 with value: 0.444264816871003.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:12:45,225] Trial 23 finished with value: 0.43593537421588574 and parameters: {'n_estimators': 1250, 'learning_rate': 0.01, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.7771998006611124, 'colsample_bytree': 0.7877422883263014}. Best is trial 10 with value: 0.444264816871003.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:12:50,793] Trial 24 finished with value: 0.42900446691666466 and parameters: {'n_estimators': 1250, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.7102326070652127, 'colsample_bytree': 0.7773423908871108}. Best is trial 10 with value: 0.444264816871003.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:12:56,832] Trial 25 finished with value: 0.4096328726836654 and parameters: {'n_estimators': 1250, 'learning_rate': 0.01, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.6915099317781, 'colsample_bytree': 0.6988221010106141}. Best is trial 10 with value: 0.444264816871003.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:13:00,248] Trial 26 finished with value: 0.43636859564452507 and parameters: {'n_estimators': 750, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.722954652119171, 'colsample_bytree': 0.7823776151825681}. Best is trial 10 with value: 0.444264816871003.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:13:04,202] Trial 27 finished with value: 0.44299132092979354 and parameters: {'n_estimators': 750, 'learning_rate': 0.01, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.7529907920537233, 'colsample_bytree': 0.747960125682269}. Best is trial 10 with value: 0.444264816871003.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:13:09,827] Trial 28 finished with value: 0.3548616134771961 and parameters: {'n_estimators': 1000, 'learning_rate': 0.02, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.7692959967923588, 'colsample_bytree': 0.7642228790777834}. Best is trial 10 with value: 0.444264816871003.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:13:14,871] Trial 29 finished with value: 0.41571931491618236 and parameters: {'n_estimators': 1250, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.6638683512237448, 'colsample_bytree': 0.6982411939554002}. Best is trial 10 with value: 0.444264816871003.
[I 2025-09-08 21:13:14,873] A new study created in memory with name: no-name-845324f0-08e0-47e3-8076-f1b4318233b4

✅ XGB con TOA_15x15_depth_in_3_4 - Mejor R2: 0.44
📋 Parámetros: {'n_estimators': 750, 'learning_rate': 0.01, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.7778936464138879, 'colsample_bytree': 0.7999001640537932}

Buscando mejores hiperparámetros para LBM con TOA_15x15_depth_in_3_4...
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:13:15,142] Trial 0 finished with value: 0.4629608676022355 and parameters: {'learning_rate': 0.02, 'num_leaves': 30, 'max_depth': 7, 'min_child_samples': 4, 'subsample': 0.7316281799724239, 'colsample_bytree': 0.7071810411073743, 'n_estimators': 1250, 'min_split_gain': 0.2}. Best is trial 0 with value: 0.4629608676022355.
[I 2025-09-08 21:13:15,262] Trial 1 finished with value: 0.4549578495158997 and parameters: {'learning_rate': 0.03, 'num_leaves': 10, 'max_depth': 6, 'min_child_samples': 5, 'subsample': 0.7986552266901571, 'colsample_bytree': 0.7476782747917754, 'n_estimators': 750, 'min_split_gain': 1.0}. Best is trial 0 with value: 0.4629608676022355.

Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 21:13:15,520] Trial 2 finished with value: 0.4372951877209701 and parameters: {'learning_rate': 0.02, 'num_leaves': 20, 'max_depth': 8, 'min_child_samples': 6, 'subsample': 0.7412778224755504, 'colsample_bytree': 0.7477737503973794, 'n_estimators': 750, 'min_split_gain': 0.2}. Best is trial 0 with value: 0.4629608676022355.

Fold 2
Fold 3
Fold 1

[I 2025-09-08 21:13:15,690] Trial 3 finished with value: 0.5113361850068673 and parameters: {'learning_rate': 0.05, 'num_leaves': 10, 'max_depth': 7, 'min_child_samples': 8, 'subsample': 0.6203260455423879, 'colsample_bytree': 0.7617015787730134, 'n_estimators': 1250, 'min_split_gain': 0.2}. Best is trial 3 with value: 0.5113361850068673.

Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 21:13:15,917] Trial 4 finished with value: 0.45733294908675387 and parameters: {'learning_rate': 0.02, 'num_leaves': 10, 'max_depth': 6, 'min_child_samples': 6, 'subsample': 0.7773573006437839, 'colsample_bytree': 0.7928274288786393, 'n_estimators': 750, 'min_split_gain': 0.2}. Best is trial 3 with value: 0.5113361850068673.

Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:13:16,077] Trial 5 finished with value: 0.5233690298655516 and parameters: {'learning_rate': 0.04, 'num_leaves': 10, 'max_depth': 5, 'min_child_samples': 8, 'subsample': 0.765486490042486, 'colsample_bytree': 0.6881072836377381, 'n_estimators': 750, 'min_split_gain': 0.1}. Best is trial 5 with value: 0.5233690298655516.
[I 2025-09-08 21:13:16,245] Trial 6 finished with value: 0.47105501338478833 and parameters: {'learning_rate': 0.04, 'num_leaves': 10, 'max_depth': 6, 'min_child_samples': 5, 'subsample': 0.7359069639079004, 'colsample_bytree': 0.7388176857680947, 'n_estimators': 1000, 'min_split_gain': 0.1}. Best is trial 5 with value: 0.5233690298655516.

Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 21:13:16,516] Trial 7 finished with value: 0.49835295591643236 and parameters: {'learning_rate': 0.02, 'num_leaves': 20, 'max_depth': 8, 'min_child_samples': 7, 'subsample': 0.7856536857847749, 'colsample_bytree': 0.6300712468099922, 'n_estimators': 1250, 'min_split_gain': 0.2}. Best is trial 5 with value: 0.5233690298655516.

Fold 2
Fold 3
Fold 1

[I 2025-09-08 21:13:16,640] Trial 8 finished with value: 0.4704755818248558 and parameters: {'learning_rate': 0.04, 'num_leaves': 30, 'max_depth': 7, 'min_child_samples': 7, 'subsample': 0.7942960194724804, 'colsample_bytree': 0.793841196227316, 'n_estimators': 750, 'min_split_gain': 1.0}. Best is trial 5 with value: 0.5233690298655516.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:13:17,086] Trial 9 finished with value: 0.4909372205389288 and parameters: {'learning_rate': 0.04, 'num_leaves': 30, 'max_depth': 8, 'min_child_samples': 8, 'subsample': 0.6791281987985834, 'colsample_bytree': 0.667583588321964, 'n_estimators': 750, 'min_split_gain': 0.0}. Best is trial 5 with value: 0.5233690298655516.
[I 2025-09-08 21:13:17,251] Trial 10 finished with value: 0.49556098964810463 and parameters: {'learning_rate': 0.05, 'num_leaves': 10, 'max_depth': 5, 'min_child_samples': 7, 'subsample': 0.6916244858910399, 'colsample_bytree': 0.6001448932103162, 'n_estimators': 1000, 'min_split_gain': 0.1}. Best is trial 5 with value: 0.5233690298655516.

Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 21:13:17,393] Trial 11 finished with value: 0.5178050659735002 and parameters: {'learning_rate': 0.05, 'num_leaves': 10, 'max_depth': 5, 'min_child_samples': 8, 'subsample': 0.6071422400282832, 'colsample_bytree': 0.6858955596075493, 'n_estimators': 1250, 'min_split_gain': 0.5}. Best is trial 5 with value: 0.5233690298655516.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:13:17,540] Trial 12 finished with value: 0.5138798732581776 and parameters: {'learning_rate': 0.05, 'num_leaves': 10, 'max_depth': 5, 'min_child_samples': 8, 'subsample': 0.6133118354145138, 'colsample_bytree': 0.6803025362547463, 'n_estimators': 1250, 'min_split_gain': 0.5}. Best is trial 5 with value: 0.5233690298655516.
[I 2025-09-08 21:13:17,714] Trial 13 finished with value: 0.5159245325963479 and parameters: {'learning_rate': 0.03, 'num_leaves': 10, 'max_depth': 5, 'min_child_samples': 8, 'subsample': 0.6544681793229215, 'colsample_bytree': 0.7116657284799386, 'n_estimators': 1250, 'min_split_gain': 0.5}. Best is trial 5 with value: 0.5233690298655516.

Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 21:13:17,864] Trial 14 finished with value: 0.49673557136113905 and parameters: {'learning_rate': 0.04, 'num_leaves': 10, 'max_depth': 5, 'min_child_samples': 7, 'subsample': 0.651607460842249, 'colsample_bytree': 0.6608339826126468, 'n_estimators': 1000, 'min_split_gain': 0.5}. Best is trial 5 with value: 0.5233690298655516.

Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 21:13:18,039] Trial 15 finished with value: 0.49975341289595293 and parameters: {'learning_rate': 0.05, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 8, 'subsample': 0.7154359730477091, 'colsample_bytree': 0.6407189560986902, 'n_estimators': 750, 'min_split_gain': 0.1}. Best is trial 5 with value: 0.5233690298655516.

Fold 3
Fold 1
Fold 2

[I 2025-09-08 21:13:18,453] Trial 16 finished with value: 0.4859166142617111 and parameters: {'learning_rate': 0.05, 'num_leaves': 10, 'max_depth': 5, 'min_child_samples': 7, 'subsample': 0.7585935175822013, 'colsample_bytree': 0.6904733817617649, 'n_estimators': 1250, 'min_split_gain': 0.0}. Best is trial 5 with value: 0.5233690298655516.

Fold 3
Fold 1
Fold 2

[I 2025-09-08 21:13:18,613] Trial 17 finished with value: 0.47860616904745806 and parameters: {'learning_rate': 0.04, 'num_leaves': 10, 'max_depth': 5, 'min_child_samples': 6, 'subsample': 0.6399064273679661, 'colsample_bytree': 0.7221092581569786, 'n_estimators': 1250, 'min_split_gain': 0.5}. Best is trial 5 with value: 0.5233690298655516.

Fold 3
Fold 1
Fold 2

[I 2025-09-08 21:13:18,849] Trial 18 finished with value: 0.5011551120297123 and parameters: {'learning_rate': 0.03, 'num_leaves': 30, 'max_depth': 6, 'min_child_samples': 8, 'subsample': 0.6735915161377607, 'colsample_bytree': 0.6473880365333124, 'n_estimators': 750, 'min_split_gain': 0.1}. Best is trial 5 with value: 0.5233690298655516.

Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:13:19,015] Trial 19 finished with value: 0.46959256725049014 and parameters: {'learning_rate': 0.05, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 4, 'subsample': 0.6022292969498604, 'colsample_bytree': 0.618804604726333, 'n_estimators': 1000, 'min_split_gain': 0.5}. Best is trial 5 with value: 0.5233690298655516.
[I 2025-09-08 21:13:19,210] Trial 20 finished with value: 0.45436648202698365 and parameters: {'learning_rate': 0.04, 'num_leaves': 10, 'max_depth': 6, 'min_child_samples': 6, 'subsample': 0.7177087781918212, 'colsample_bytree': 0.6871560098393431, 'n_estimators': 1250, 'min_split_gain': 0.1}. Best is trial 5 with value: 0.5233690298655516.

Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 21:13:19,382] Trial 21 finished with value: 0.5159245325963479 and parameters: {'learning_rate': 0.03, 'num_leaves': 10, 'max_depth': 5, 'min_child_samples': 8, 'subsample': 0.6482477939680873, 'colsample_bytree': 0.7082813178534586, 'n_estimators': 1250, 'min_split_gain': 0.5}. Best is trial 5 with value: 0.5233690298655516.

Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 21:13:19,568] Trial 22 finished with value: 0.5160856856979917 and parameters: {'learning_rate': 0.03, 'num_leaves': 10, 'max_depth': 5, 'min_child_samples': 8, 'subsample': 0.6266553617604245, 'colsample_bytree': 0.7216294023778075, 'n_estimators': 1250, 'min_split_gain': 0.5}. Best is trial 5 with value: 0.5233690298655516.

Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:13:19,733] Trial 23 finished with value: 0.5002371455330686 and parameters: {'learning_rate': 0.03, 'num_leaves': 10, 'max_depth': 5, 'min_child_samples': 7, 'subsample': 0.6309230563271427, 'colsample_bytree': 0.6695376235618005, 'n_estimators': 1250, 'min_split_gain': 0.5}. Best is trial 5 with value: 0.5233690298655516.
[I 2025-09-08 21:13:19,915] Trial 24 finished with value: 0.5160856856979917 and parameters: {'learning_rate': 0.03, 'num_leaves': 10, 'max_depth': 5, 'min_child_samples': 8, 'subsample': 0.6002834174524396, 'colsample_bytree': 0.7260550818605205, 'n_estimators': 1250, 'min_split_gain': 0.5}. Best is trial 5 with value: 0.5233690298655516.

Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 21:13:20,196] Trial 25 finished with value: 0.48513822141851676 and parameters: {'learning_rate': 0.03, 'num_leaves': 10, 'max_depth': 6, 'min_child_samples': 7, 'subsample': 0.6696014149217997, 'colsample_bytree': 0.695799860172059, 'n_estimators': 750, 'min_split_gain': 0.0}. Best is trial 5 with value: 0.5233690298655516.

Fold 2
Fold 3
Fold 1

[I 2025-09-08 21:13:20,347] Trial 26 finished with value: 0.5066576669369319 and parameters: {'learning_rate': 0.04, 'num_leaves': 10, 'max_depth': 5, 'min_child_samples': 8, 'subsample': 0.6221010521234244, 'colsample_bytree': 0.767774389378167, 'n_estimators': 1250, 'min_split_gain': 1.0}. Best is trial 5 with value: 0.5233690298655516.

Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 21:13:20,542] Trial 27 finished with value: 0.5014426220637679 and parameters: {'learning_rate': 0.05, 'num_leaves': 10, 'max_depth': 6, 'min_child_samples': 8, 'subsample': 0.7624849142262669, 'colsample_bytree': 0.7258584786301426, 'n_estimators': 1250, 'min_split_gain': 0.1}. Best is trial 5 with value: 0.5233690298655516.

Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:13:20,745] Trial 28 finished with value: 0.5065207918868313 and parameters: {'learning_rate': 0.03, 'num_leaves': 30, 'max_depth': 5, 'min_child_samples': 7, 'subsample': 0.7036346750619475, 'colsample_bytree': 0.6753287033062876, 'n_estimators': 1000, 'min_split_gain': 0.5}. Best is trial 5 with value: 0.5233690298655516.
[I 2025-09-08 21:13:20,952] Trial 29 finished with value: 0.4683305768048869 and parameters: {'learning_rate': 0.02, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 4, 'subsample': 0.6353593087151719, 'colsample_bytree': 0.7039243360357121, 'n_estimators': 750, 'min_split_gain': 0.5}. Best is trial 5 with value: 0.5233690298655516.
[I 2025-09-08 21:13:20,953] A new study created in memory with name: no-name-598529fe-97c9-41f8-a571-4a1a11e273f8

Fold 1
Fold 2
Fold 3

✅ LBM con TOA_15x15_depth_in_3_4 - Mejor R2: 0.52
📋 Parámetros: {'learning_rate': 0.04, 'num_leaves': 10, 'max_depth': 5, 'min_child_samples': 8, 'subsample': 0.765486490042486, 'colsample_bytree': 0.6881072836377381, 'n_estimators': 750, 'min_split_gain': 0.1}

Buscando mejores hiperparámetros para MLP con TOA_15x15_depth_in_3_4...
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 21:13:22,311] Trial 0 finished with value: 0.4339496487662046 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.005124631830678554, 'learning_rate': 'constant', 'learning_rate_init': 0.0002981191660864221}. Best is trial 0 with value: 0.4339496487662046.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 21:13:23,401] Trial 1 finished with value: 0.4561031145127769 and parameters: {'hidden_layer_sizes': (64,), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0015743530689486037, 'learning_rate': 'constant', 'learning_rate_init': 0.0012380880958235147}. Best is trial 1 with value: 0.4561031145127769.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 3
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 21:13:24,457] Trial 2 finished with value: 0.4491267338221556 and parameters: {'hidden_layer_sizes': (32,), 'activation': 'tanh', 'solver': 'sgd', 'alpha': 4.756586377959258e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.007428419012379046}. Best is trial 1 with value: 0.4561031145127769.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

[I 2025-09-08 21:13:25,211] Trial 3 finished with value: 0.09097561230291736 and parameters: {'hidden_layer_sizes': (64,), 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.00972314764510401, 'learning_rate': 'constant', 'learning_rate_init': 0.0013756964935781695}. Best is trial 1 with value: 0.4561031145127769.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

[I 2025-09-08 21:13:26,169] Trial 4 finished with value: -0.04257613477345187 and parameters: {'hidden_layer_sizes': (32,), 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.014369829834903038, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0007586639256384935}. Best is trial 1 with value: 0.4561031145127769.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 21:13:27,379] Trial 5 finished with value: 0.2913151437772124 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.003325758662562494, 'learning_rate': 'constant', 'learning_rate_init': 0.0009984612180513872}. Best is trial 1 with value: 0.4561031145127769.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:13:27,894] Trial 6 finished with value: 0.2620208106712445 and parameters: {'hidden_layer_sizes': (128,), 'activation': 'relu', 'solver': 'adam', 'alpha': 1.0311336074972097e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.007967392505040374}. Best is trial 1 with value: 0.4561031145127769.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 21:13:28,621] Trial 7 finished with value: -0.10302385242328749 and parameters: {'hidden_layer_sizes': (64,), 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.06668099543944808, 'learning_rate': 'constant', 'learning_rate_init': 0.0005151051233167828}. Best is trial 1 with value: 0.4561031145127769.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 21:13:29,466] Trial 8 finished with value: -0.11272171954867187 and parameters: {'hidden_layer_sizes': (64,), 'activation': 'relu', 'solver': 'adam', 'alpha': 1.1742493670039356e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.00011273353650116102}. Best is trial 1 with value: 0.4561031145127769.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

[I 2025-09-08 21:13:30,692] Trial 9 finished with value: 0.48851285493493846 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'adam', 'alpha': 7.116754586428669e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.0025027320638411985}. Best is trial 9 with value: 0.48851285493493846.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:13:31,628] Trial 10 finished with value: 0.5005115988994968 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0001875612148925029, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00315517849198427}. Best is trial 10 with value: 0.5005115988994968.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:13:32,727] Trial 11 finished with value: 0.49989766988069223 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0002182692291699824, 'learning_rate': 'adaptive', 'learning_rate_init': 0.003049501210596972}. Best is trial 10 with value: 0.5005115988994968.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:13:33,897] Trial 12 finished with value: 0.4999572349746892 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0002942059484053988, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0028253762874498284}. Best is trial 10 with value: 0.5005115988994968.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:13:34,927] Trial 13 finished with value: 0.500504283591554 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0003615199281312021, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0031333008565686245}. Best is trial 10 with value: 0.5005115988994968.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 21:13:35,672] Trial 14 finished with value: 0.3841042477874878 and parameters: {'hidden_layer_sizes': (128,), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0004598160170335711, 'learning_rate': 'adaptive', 'learning_rate_init': 0.004622260298763644}. Best is trial 10 with value: 0.5005115988994968.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:13:36,501] Trial 15 finished with value: 0.5238699181797728 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'adam', 'alpha': 7.433113437676689e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.004767135345295976}. Best is trial 15 with value: 0.5238699181797728.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:13:37,490] Trial 16 finished with value: 0.527943884039618 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'adam', 'alpha': 5.5225079369370465e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00510594349310219}. Best is trial 16 with value: 0.527943884039618.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:13:38,274] Trial 17 finished with value: 0.5280595983308992 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'adam', 'alpha': 4.5719082540518624e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.005663404957348032}. Best is trial 17 with value: 0.5280595983308992.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2

[I 2025-09-08 21:13:38,820] Trial 18 finished with value: 0.4815792292619993 and parameters: {'hidden_layer_sizes': (32,), 'activation': 'tanh', 'solver': 'adam', 'alpha': 2.8855513564858596e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.008372931147255038}. Best is trial 17 with value: 0.5280595983308992.

Fold 3
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 21:13:39,747] Trial 19 finished with value: 0.34327739595268314 and parameters: {'hidden_layer_sizes': (128,), 'activation': 'tanh', 'solver': 'adam', 'alpha': 2.5689685053258882e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0018651155717087484}. Best is trial 17 with value: 0.5280595983308992.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:13:40,611] Trial 20 finished with value: 0.5279773665683349 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0007960964776049064, 'learning_rate': 'adaptive', 'learning_rate_init': 0.005717449526596722}. Best is trial 17 with value: 0.5280595983308992.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:13:41,466] Trial 21 finished with value: 0.5295472443504524 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0010601776554131407, 'learning_rate': 'adaptive', 'learning_rate_init': 0.005177574217753322}. Best is trial 21 with value: 0.5295472443504524.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:13:42,390] Trial 22 finished with value: 0.500358272843847 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0009911642855368376, 'learning_rate': 'adaptive', 'learning_rate_init': 0.009597074315006528}. Best is trial 21 with value: 0.5295472443504524.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:13:43,248] Trial 23 finished with value: 0.5259157862030057 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0008800463557062182, 'learning_rate': 'adaptive', 'learning_rate_init': 0.005361391830260973}. Best is trial 21 with value: 0.5295472443504524.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 21:13:44,597] Trial 24 finished with value: 0.47929525667556466 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0023061490274686133, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0019269904444857242}. Best is trial 21 with value: 0.5295472443504524.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:13:45,507] Trial 25 finished with value: 0.5354761887931138 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0001348648883586536, 'learning_rate': 'adaptive', 'learning_rate_init': 0.006504170861988247}. Best is trial 25 with value: 0.5354761887931138.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 21:13:46,763] Trial 26 finished with value: 0.4638253972788376 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.00014370845147835024, 'learning_rate': 'adaptive', 'learning_rate_init': 0.003810963292838943}. Best is trial 25 with value: 0.5354761887931138.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 21:13:47,658] Trial 27 finished with value: 0.32386129442743466 and parameters: {'hidden_layer_sizes': (128,), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.00012363621909002362, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0019796225857254606}. Best is trial 25 with value: 0.5354761887931138.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:13:48,306] Trial 28 finished with value: 0.48758308550851326 and parameters: {'hidden_layer_sizes': (32,), 'activation': 'tanh', 'solver': 'adam', 'alpha': 2.203271564287486e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.006588859912068258}. Best is trial 25 with value: 0.5354761887931138.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 21:13:49,641] Trial 29 finished with value: 0.4203925708338267 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0005048083543985216, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00026063733262245815}. Best is trial 25 with value: 0.5354761887931138.
[I 2025-09-08 21:13:49,643] A new study created in memory with name: no-name-f2875437-ca15-42ba-92d3-ac80677538a1
[I 2025-09-08 21:13:49,721] Trial 0 finished with value: 0.44038456980895146 and parameters: {'C': 4.767512009153394, 'epsilon': 0.1244315853272698}. Best is trial 0 with value: 0.44038456980895146.
[I 2025-09-08 21:13:49,773] Trial 1 finished with value: -0.0038732248591327734 and parameters: {'C': 0.12731198197540008, 'epsilon': 0.04441686186790172}. Best is trial 0 with value: 0.44038456980895146.
[I 2025-09-08 21:13:49,830] Trial 2 finished with value: 0.353862355252385 and parameters: {'C': 2.3146439484047225, 'epsilon': 0.04888854000553304}. Best is trial 0 with value: 0.44038456980895146.

✅ MLP con TOA_15x15_depth_in_3_4 - Mejor R2: 0.54
📋 Parámetros: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0001348648883586536, 'learning_rate': 'adaptive', 'learning_rate_init': 0.006504170861988247}

Buscando mejores hiperparámetros para SVR con TOA_15x15_depth_in_3_4...
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 21:13:49,887] Trial 3 finished with value: 0.007705379453692133 and parameters: {'C': 0.11650787448262406, 'epsilon': 0.14931565288724863}. Best is trial 0 with value: 0.44038456980895146.
[I 2025-09-08 21:13:49,953] Trial 4 finished with value: 0.28352250140483554 and parameters: {'C': 1.408901327508385, 'epsilon': 0.08181559221131578}. Best is trial 0 with value: 0.44038456980895146.
[I 2025-09-08 21:13:50,026] Trial 5 finished with value: 0.025311364224472777 and parameters: {'C': 0.12268213196339924, 'epsilon': 0.18876896197940518}. Best is trial 0 with value: 0.44038456980895146.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 21:13:50,078] Trial 6 finished with value: 0.2686056753634397 and parameters: {'C': 1.1986479300061827, 'epsilon': 0.18363452578163436}. Best is trial 0 with value: 0.44038456980895146.
[I 2025-09-08 21:13:50,142] Trial 7 finished with value: 0.4350781304540446 and parameters: {'C': 4.536814220885443, 'epsilon': 0.10012735923279549}. Best is trial 0 with value: 0.44038456980895146.
[I 2025-09-08 21:13:50,193] Trial 8 finished with value: 0.010763331201794476 and parameters: {'C': 0.1211344631603584, 'epsilon': 0.1451932061746439}. Best is trial 0 with value: 0.44038456980895146.
[I 2025-09-08 21:13:50,246] Trial 9 finished with value: 0.10870283881221003 and parameters: {'C': 0.3886223043897176, 'epsilon': 0.036378345192741586}. Best is trial 0 with value: 0.44038456980895146.

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 21:13:50,312] Trial 10 finished with value: 0.5067930432830218 and parameters: {'C': 9.713692404036728, 'epsilon': 0.13454247627044935}. Best is trial 10 with value: 0.5067930432830218.
[I 2025-09-08 21:13:50,381] Trial 11 finished with value: 0.5055088537970958 and parameters: {'C': 9.621012944297657, 'epsilon': 0.13113104850183613}. Best is trial 10 with value: 0.5067930432830218.
[I 2025-09-08 21:13:50,442] Trial 12 finished with value: 0.5023686692409535 and parameters: {'C': 9.155378179473097, 'epsilon': 0.15075505382894883}. Best is trial 10 with value: 0.5067930432830218.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 21:13:50,508] Trial 13 finished with value: 0.5008355915170571 and parameters: {'C': 9.56529201806198, 'epsilon': 0.08617691630888644}. Best is trial 10 with value: 0.5067930432830218.
[I 2025-09-08 21:13:50,577] Trial 14 finished with value: 0.4217623482651886 and parameters: {'C': 4.062445058246534, 'epsilon': 0.12432077389704586}. Best is trial 10 with value: 0.5067930432830218.
[I 2025-09-08 21:13:50,634] Trial 15 finished with value: 0.17082069646417797 and parameters: {'C': 0.5348268926420774, 'epsilon': 0.17090937643916465}. Best is trial 10 with value: 0.5067930432830218.

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:13:50,697] Trial 16 finished with value: 0.38302539939895225 and parameters: {'C': 2.762738954229503, 'epsilon': 0.12228872645199806}. Best is trial 10 with value: 0.5067930432830218.
[I 2025-09-08 21:13:50,766] Trial 17 finished with value: 0.4725316149021519 and parameters: {'C': 6.967011814322843, 'epsilon': 0.07822077158105739}. Best is trial 10 with value: 0.5067930432830218.
[I 2025-09-08 21:13:50,828] Trial 18 finished with value: 0.1601398654179728 and parameters: {'C': 0.637446647886466, 'epsilon': 0.010900960835855844}. Best is trial 10 with value: 0.5067930432830218.
[I 2025-09-08 21:13:50,888] Trial 19 finished with value: 0.35542487619675106 and parameters: {'C': 2.2145950423065384, 'epsilon': 0.1687140492842431}. Best is trial 10 with value: 0.5067930432830218.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 21:13:50,951] Trial 20 finished with value: 0.08141968566171535 and parameters: {'C': 0.2710744209010096, 'epsilon': 0.10513219541682864}. Best is trial 10 with value: 0.5067930432830218.
[I 2025-09-08 21:13:51,032] Trial 21 finished with value: 0.5091003543073971 and parameters: {'C': 9.900038623195563, 'epsilon': 0.14889477339702906}. Best is trial 21 with value: 0.5091003543073971.
[I 2025-09-08 21:13:51,108] Trial 22 finished with value: 0.47655265809869674 and parameters: {'C': 6.800215967445897, 'epsilon': 0.13620334868740913}. Best is trial 21 with value: 0.5091003543073971.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 21:13:51,169] Trial 23 finished with value: 0.46376499352629 and parameters: {'C': 6.113709554705421, 'epsilon': 0.16402619937076682}. Best is trial 21 with value: 0.5091003543073971.
[I 2025-09-08 21:13:51,233] Trial 24 finished with value: 0.4022689982111068 and parameters: {'C': 3.3345755158027344, 'epsilon': 0.11000722901773792}. Best is trial 21 with value: 0.5091003543073971.
[I 2025-09-08 21:13:51,296] Trial 25 finished with value: 0.5035333997895893 and parameters: {'C': 9.851318821730441, 'epsilon': 0.19938665199709038}. Best is trial 21 with value: 0.5091003543073971.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 21:13:51,355] Trial 26 finished with value: 0.3039663141888018 and parameters: {'C': 1.6011107029782854, 'epsilon': 0.13544011209396065}. Best is trial 21 with value: 0.5091003543073971.
[I 2025-09-08 21:13:51,422] Trial 27 finished with value: 0.45092080909838533 and parameters: {'C': 5.304516224769033, 'epsilon': 0.1589443646329669}. Best is trial 21 with value: 0.5091003543073971.
[I 2025-09-08 21:13:51,484] Trial 28 finished with value: 0.48187160936491197 and parameters: {'C': 7.364604326796903, 'epsilon': 0.11575815258343723}. Best is trial 21 with value: 0.5091003543073971.

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:13:51,542] Trial 29 finished with value: 0.4112564245061287 and parameters: {'C': 3.717819639174212, 'epsilon': 0.1346448818217632}. Best is trial 21 with value: 0.5091003543073971.
[I 2025-09-08 21:13:51,543] A new study created in memory with name: no-name-e0595682-f119-4ece-8199-34b7e025f4c7
[I 2025-09-08 21:13:51,595] Trial 0 finished with value: 0.46607435516989915 and parameters: {'n_neighbors': 7, 'leaf_size': 20}. Best is trial 0 with value: 0.46607435516989915.
[I 2025-09-08 21:13:51,648] Trial 1 finished with value: 0.5401995913391523 and parameters: {'n_neighbors': 4, 'leaf_size': 24}. Best is trial 1 with value: 0.5401995913391523.
[I 2025-09-08 21:13:51,696] Trial 2 finished with value: 0.4433064191174998 and parameters: {'n_neighbors': 9, 'leaf_size': 16}. Best is trial 1 with value: 0.5401995913391523.
[I 2025-09-08 21:13:51,740] Trial 3 finished with value: 0.420274650778169 and parameters: {'n_neighbors': 11, 'leaf_size': 38}. Best is trial 1 with value: 0.5401995913391523.

✅ SVR con TOA_15x15_depth_in_3_4 - Mejor R2: 0.51
📋 Parámetros: {'C': 9.900038623195563, 'epsilon': 0.14889477339702906}

Buscando mejores hiperparámetros para KNN con TOA_15x15_depth_in_3_4...
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 21:13:51,788] Trial 4 finished with value: 0.4433064191174998 and parameters: {'n_neighbors': 9, 'leaf_size': 33}. Best is trial 1 with value: 0.5401995913391523.
[I 2025-09-08 21:13:51,837] Trial 5 finished with value: 0.42723729604569566 and parameters: {'n_neighbors': 10, 'leaf_size': 38}. Best is trial 1 with value: 0.5401995913391523.
[I 2025-09-08 21:13:51,884] Trial 6 finished with value: 0.5401995913391523 and parameters: {'n_neighbors': 4, 'leaf_size': 26}. Best is trial 1 with value: 0.5401995913391523.
[I 2025-09-08 21:13:51,926] Trial 7 finished with value: 0.4104065897469645 and parameters: {'n_neighbors': 12, 'leaf_size': 39}. Best is trial 1 with value: 0.5401995913391523.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:13:51,972] Trial 8 finished with value: 0.5165493007728906 and parameters: {'n_neighbors': 5, 'leaf_size': 36}. Best is trial 1 with value: 0.5401995913391523.
[I 2025-09-08 21:13:52,019] Trial 9 finished with value: 0.48481480973947844 and parameters: {'n_neighbors': 6, 'leaf_size': 34}. Best is trial 1 with value: 0.5401995913391523.
[I 2025-09-08 21:13:52,132] Trial 10 finished with value: 0.5393852131670256 and parameters: {'n_neighbors': 3, 'leaf_size': 26}. Best is trial 1 with value: 0.5401995913391523.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:13:52,187] Trial 11 finished with value: 0.5393852131670256 and parameters: {'n_neighbors': 3, 'leaf_size': 26}. Best is trial 1 with value: 0.5401995913391523.
[I 2025-09-08 21:13:52,245] Trial 12 finished with value: 0.5165493007728906 and parameters: {'n_neighbors': 5, 'leaf_size': 10}. Best is trial 1 with value: 0.5401995913391523.
[I 2025-09-08 21:13:52,297] Trial 13 finished with value: 0.5401995913391523 and parameters: {'n_neighbors': 4, 'leaf_size': 29}. Best is trial 1 with value: 0.5401995913391523.
[I 2025-09-08 21:13:52,345] Trial 14 finished with value: 0.46607435516989915 and parameters: {'n_neighbors': 7, 'leaf_size': 20}. Best is trial 1 with value: 0.5401995913391523.
[I 2025-09-08 21:13:52,398] Trial 15 finished with value: 0.5165493007728906 and parameters: {'n_neighbors': 5, 'leaf_size': 22}. Best is trial 1 with value: 0.5401995913391523.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:13:52,454] Trial 16 finished with value: 0.5401995913391523 and parameters: {'n_neighbors': 4, 'leaf_size': 30}. Best is trial 1 with value: 0.5401995913391523.
[I 2025-09-08 21:13:52,513] Trial 17 finished with value: 0.48481480973947844 and parameters: {'n_neighbors': 6, 'leaf_size': 15}. Best is trial 1 with value: 0.5401995913391523.
[I 2025-09-08 21:13:52,566] Trial 18 finished with value: 0.5393852131670256 and parameters: {'n_neighbors': 3, 'leaf_size': 24}. Best is trial 1 with value: 0.5401995913391523.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:13:52,617] Trial 19 finished with value: 0.5401995913391523 and parameters: {'n_neighbors': 4, 'leaf_size': 29}. Best is trial 1 with value: 0.5401995913391523.
[I 2025-09-08 21:13:52,675] Trial 20 finished with value: 0.45430235535234 and parameters: {'n_neighbors': 8, 'leaf_size': 16}. Best is trial 1 with value: 0.5401995913391523.
[I 2025-09-08 21:13:52,725] Trial 21 finished with value: 0.5401995913391523 and parameters: {'n_neighbors': 4, 'leaf_size': 29}. Best is trial 1 with value: 0.5401995913391523.
[I 2025-09-08 21:13:52,777] Trial 22 finished with value: 0.48481480973947844 and parameters: {'n_neighbors': 6, 'leaf_size': 31}. Best is trial 1 with value: 0.5401995913391523.
[I 2025-09-08 21:13:52,829] Trial 23 finished with value: 0.5401995913391523 and parameters: {'n_neighbors': 4, 'leaf_size': 27}. Best is trial 1 with value: 0.5401995913391523.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:13:52,889] Trial 24 finished with value: 0.5165493007728906 and parameters: {'n_neighbors': 5, 'leaf_size': 23}. Best is trial 1 with value: 0.5401995913391523.
[I 2025-09-08 21:13:52,952] Trial 25 finished with value: 0.5393852131670256 and parameters: {'n_neighbors': 3, 'leaf_size': 21}. Best is trial 1 with value: 0.5401995913391523.
[I 2025-09-08 21:13:53,005] Trial 26 finished with value: 0.5401995913391523 and parameters: {'n_neighbors': 4, 'leaf_size': 32}. Best is trial 1 with value: 0.5401995913391523.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:13:53,057] Trial 27 finished with value: 0.48481480973947844 and parameters: {'n_neighbors': 6, 'leaf_size': 27}. Best is trial 1 with value: 0.5401995913391523.
[I 2025-09-08 21:13:53,122] Trial 28 finished with value: 0.5165493007728906 and parameters: {'n_neighbors': 5, 'leaf_size': 18}. Best is trial 1 with value: 0.5401995913391523.
[I 2025-09-08 21:13:53,225] Trial 29 finished with value: 0.46607435516989915 and parameters: {'n_neighbors': 7, 'leaf_size': 25}. Best is trial 1 with value: 0.5401995913391523.
[I 2025-09-08 21:13:53,227] A new study created in memory with name: no-name-84364124-e579-49a6-892e-bea9daeb26b8
[I 2025-09-08 21:13:53,272] Trial 0 finished with value: 0.13768423818375597 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 0 with value: 0.13768423818375597.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

✅ KNN con TOA_15x15_depth_in_3_4 - Mejor R2: 0.54
📋 Parámetros: {'n_neighbors': 4, 'leaf_size': 24}

Buscando mejores hiperparámetros para LR con TOA_15x15_depth_in_3_4...
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:13:53,333] Trial 1 finished with value: 0.34320136791340716 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 1 with value: 0.34320136791340716.
[I 2025-09-08 21:13:53,397] Trial 2 finished with value: 0.3432013679127614 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 1 with value: 0.34320136791340716.
[I 2025-09-08 21:13:53,465] Trial 3 finished with value: 0.3432013679127614 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 1 with value: 0.34320136791340716.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 21:13:53,533] Trial 4 finished with value: 0.34320136791340716 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 1 with value: 0.34320136791340716.
[I 2025-09-08 21:13:53,594] Trial 5 finished with value: 0.13768423818375597 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.34320136791340716.
[I 2025-09-08 21:13:53,644] Trial 6 finished with value: 0.1376842381837584 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 1 with value: 0.34320136791340716.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:13:53,708] Trial 7 finished with value: 0.34320136791340716 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 1 with value: 0.34320136791340716.
[I 2025-09-08 21:13:53,809] Trial 8 finished with value: 0.34320136791340716 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 1 with value: 0.34320136791340716.
[I 2025-09-08 21:13:53,899] Trial 9 finished with value: 0.1376842381837584 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 1 with value: 0.34320136791340716.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 21:13:53,958] Trial 10 finished with value: 0.34320136791340716 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 1 with value: 0.34320136791340716.
[I 2025-09-08 21:13:54,028] Trial 11 finished with value: 0.34320136791340716 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 1 with value: 0.34320136791340716.

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:13:54,180] Trial 12 finished with value: 0.34320136791340716 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 1 with value: 0.34320136791340716.
[I 2025-09-08 21:13:54,330] Trial 13 finished with value: 0.34320136791340716 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 1 with value: 0.34320136791340716.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:13:54,400] Trial 14 finished with value: 0.34320136791340716 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 1 with value: 0.34320136791340716.
[I 2025-09-08 21:13:54,485] Trial 15 finished with value: 0.34320136791340716 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 1 with value: 0.34320136791340716.
[I 2025-09-08 21:13:54,546] Trial 16 finished with value: 0.34320136791340716 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 1 with value: 0.34320136791340716.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:13:54,609] Trial 17 finished with value: 0.34320136791340716 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 1 with value: 0.34320136791340716.
[I 2025-09-08 21:13:54,669] Trial 18 finished with value: 0.13768423818375597 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.34320136791340716.
[I 2025-09-08 21:13:54,737] Trial 19 finished with value: 0.34320136791340716 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 1 with value: 0.34320136791340716.
[I 2025-09-08 21:13:54,807] Trial 20 finished with value: 0.34320136791340716 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 1 with value: 0.34320136791340716.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 21:13:54,887] Trial 21 finished with value: 0.34320136791340716 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 1 with value: 0.34320136791340716.
[I 2025-09-08 21:13:54,959] Trial 22 finished with value: 0.34320136791340716 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 1 with value: 0.34320136791340716.
[I 2025-09-08 21:13:55,034] Trial 23 finished with value: 0.34320136791340716 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 1 with value: 0.34320136791340716.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:13:55,104] Trial 24 finished with value: 0.34320136791340716 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 1 with value: 0.34320136791340716.
[I 2025-09-08 21:13:55,176] Trial 25 finished with value: 0.34320136791340716 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 1 with value: 0.34320136791340716.
[I 2025-09-08 21:13:55,239] Trial 26 finished with value: 0.13768423818375597 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.34320136791340716.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:13:55,313] Trial 27 finished with value: 0.34320136791340716 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 1 with value: 0.34320136791340716.
[I 2025-09-08 21:13:55,400] Trial 28 finished with value: 0.34320136791340716 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 1 with value: 0.34320136791340716.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:13:55,463] Trial 29 finished with value: 0.13768423818375597 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.34320136791340716.
[I 2025-09-08 21:13:55,465] A new study created in memory with name: no-name-02295f6e-ec41-41a1-bba1-edebfd22c5d4

✅ LR con TOA_15x15_depth_in_3_4 - Mejor R2: 0.34
📋 Parámetros: {'fit_intercept': True, 'positive': False}

Buscando mejores hiperparámetros para RF con TOA_15x15_depth_in_3_4...
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:13:59,401] Trial 0 finished with value: 0.3619597741067809 and parameters: {'n_estimators': 400, 'max_depth': 11, 'min_samples_split': 4, 'min_samples_leaf': 6, 'bootstrap': True}. Best is trial 0 with value: 0.3619597741067809.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:14:03,267] Trial 1 finished with value: 0.37476827288402664 and parameters: {'n_estimators': 400, 'max_depth': 7, 'min_samples_split': 5, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 1 with value: 0.37476827288402664.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:14:06,125] Trial 2 finished with value: 0.24903531417330882 and parameters: {'n_estimators': 200, 'max_depth': 6, 'min_samples_split': 4, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 1 with value: 0.37476827288402664.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:14:07,021] Trial 3 finished with value: 0.3743882039724428 and parameters: {'n_estimators': 100, 'max_depth': 5, 'min_samples_split': 3, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 1 with value: 0.37476827288402664.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:14:10,908] Trial 4 finished with value: 0.36195096304651536 and parameters: {'n_estimators': 400, 'max_depth': 12, 'min_samples_split': 8, 'min_samples_leaf': 6, 'bootstrap': True}. Best is trial 1 with value: 0.37476827288402664.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:14:13,033] Trial 5 finished with value: 0.39771113697810695 and parameters: {'n_estimators': 200, 'max_depth': 8, 'min_samples_split': 5, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 5 with value: 0.39771113697810695.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:14:17,721] Trial 6 finished with value: 0.22291853338720624 and parameters: {'n_estimators': 400, 'max_depth': 5, 'min_samples_split': 2, 'min_samples_leaf': 6, 'bootstrap': False}. Best is trial 5 with value: 0.39771113697810695.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:14:18,755] Trial 7 finished with value: 0.3711920582145159 and parameters: {'n_estimators': 100, 'max_depth': 12, 'min_samples_split': 8, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 5 with value: 0.39771113697810695.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:14:20,875] Trial 8 finished with value: 0.416870462724314 and parameters: {'n_estimators': 200, 'max_depth': 7, 'min_samples_split': 4, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 8 with value: 0.416870462724314.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:14:22,874] Trial 9 finished with value: 0.393962883451098 and parameters: {'n_estimators': 200, 'max_depth': 7, 'min_samples_split': 2, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 8 with value: 0.416870462724314.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:14:25,896] Trial 10 finished with value: 0.233860210250213 and parameters: {'n_estimators': 200, 'max_depth': 10, 'min_samples_split': 7, 'min_samples_leaf': 8, 'bootstrap': False}. Best is trial 8 with value: 0.416870462724314.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:14:28,185] Trial 11 finished with value: 0.4250761189998548 and parameters: {'n_estimators': 200, 'max_depth': 9, 'min_samples_split': 6, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 11 with value: 0.4250761189998548.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:14:30,464] Trial 12 finished with value: 0.4250761189998548 and parameters: {'n_estimators': 200, 'max_depth': 9, 'min_samples_split': 6, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 11 with value: 0.4250761189998548.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:14:32,732] Trial 13 finished with value: 0.4250761189998548 and parameters: {'n_estimators': 200, 'max_depth': 9, 'min_samples_split': 6, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 11 with value: 0.4250761189998548.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:14:36,273] Trial 14 finished with value: 0.30840128475268636 and parameters: {'n_estimators': 200, 'max_depth': 9, 'min_samples_split': 6, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 11 with value: 0.4250761189998548.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:14:38,470] Trial 15 finished with value: 0.3997075055802499 and parameters: {'n_estimators': 200, 'max_depth': 10, 'min_samples_split': 6, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 11 with value: 0.4250761189998548.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:14:39,708] Trial 16 finished with value: 0.40530876142447836 and parameters: {'n_estimators': 100, 'max_depth': 10, 'min_samples_split': 7, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 11 with value: 0.4250761189998548.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:14:41,405] Trial 17 finished with value: 0.32203497361208006 and parameters: {'n_estimators': 200, 'max_depth': 8, 'min_samples_split': 7, 'min_samples_leaf': 8, 'bootstrap': True}. Best is trial 11 with value: 0.4250761189998548.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:14:44,936] Trial 18 finished with value: 0.30840128475268636 and parameters: {'n_estimators': 200, 'max_depth': 9, 'min_samples_split': 6, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 11 with value: 0.4250761189998548.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:14:46,074] Trial 19 finished with value: 0.4013066113948771 and parameters: {'n_estimators': 100, 'max_depth': 11, 'min_samples_split': 5, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 11 with value: 0.4250761189998548.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:14:47,857] Trial 20 finished with value: 0.3408050707535952 and parameters: {'n_estimators': 200, 'max_depth': 8, 'min_samples_split': 7, 'min_samples_leaf': 7, 'bootstrap': True}. Best is trial 11 with value: 0.4250761189998548.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:14:50,139] Trial 21 finished with value: 0.4250761189998548 and parameters: {'n_estimators': 200, 'max_depth': 9, 'min_samples_split': 6, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 11 with value: 0.4250761189998548.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:14:52,439] Trial 22 finished with value: 0.4250761189998548 and parameters: {'n_estimators': 200, 'max_depth': 9, 'min_samples_split': 6, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 11 with value: 0.4250761189998548.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:14:54,926] Trial 23 finished with value: 0.4201502602549134 and parameters: {'n_estimators': 200, 'max_depth': 10, 'min_samples_split': 5, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 11 with value: 0.4250761189998548.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:14:57,098] Trial 24 finished with value: 0.40000867290274583 and parameters: {'n_estimators': 200, 'max_depth': 11, 'min_samples_split': 7, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 11 with value: 0.4250761189998548.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:14:59,310] Trial 25 finished with value: 0.42153919912572496 and parameters: {'n_estimators': 200, 'max_depth': 8, 'min_samples_split': 5, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 11 with value: 0.4250761189998548.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:15:02,951] Trial 26 finished with value: 0.27048477266816895 and parameters: {'n_estimators': 200, 'max_depth': 9, 'min_samples_split': 6, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 11 with value: 0.4250761189998548.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:15:05,011] Trial 27 finished with value: 0.37379651814661763 and parameters: {'n_estimators': 200, 'max_depth': 10, 'min_samples_split': 8, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 11 with value: 0.4250761189998548.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:15:09,224] Trial 28 finished with value: 0.3956968665147526 and parameters: {'n_estimators': 400, 'max_depth': 8, 'min_samples_split': 6, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 11 with value: 0.4250761189998548.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:15:10,253] Trial 29 finished with value: 0.37151858967376805 and parameters: {'n_estimators': 100, 'max_depth': 11, 'min_samples_split': 4, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 11 with value: 0.4250761189998548.
[I 2025-09-08 21:15:10,255] A new study created in memory with name: no-name-0f32565e-d95f-4818-b85e-7f1dd7161602

✅ RF con TOA_15x15_depth_in_3_4 - Mejor R2: 0.43
📋 Parámetros: {'n_estimators': 200, 'max_depth': 9, 'min_samples_split': 6, 'min_samples_leaf': 3, 'bootstrap': True}

Buscando mejores hiperparámetros para CAT con TOA_15x15_depth_in_3_4...
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:15:35,852] Trial 0 finished with value: 0.5397700019946859 and parameters: {'iterations': 1000, 'learning_rate': 0.03, 'depth': 8, 'l2_leaf_reg': 3.5539196496861187}. Best is trial 0 with value: 0.5397700019946859.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:15:39,415] Trial 1 finished with value: 0.5065954167169526 and parameters: {'iterations': 750, 'learning_rate': 0.02, 'depth': 6, 'l2_leaf_reg': 4.638186273652194}. Best is trial 0 with value: 0.5397700019946859.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:15:49,603] Trial 2 finished with value: 0.5276224756425248 and parameters: {'iterations': 1000, 'learning_rate': 0.04, 'depth': 7, 'l2_leaf_reg': 4.307242766651303}. Best is trial 0 with value: 0.5397700019946859.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:16:08,777] Trial 3 finished with value: 0.5400468247694293 and parameters: {'iterations': 750, 'learning_rate': 0.05, 'depth': 8, 'l2_leaf_reg': 2.364513420137956}. Best is trial 3 with value: 0.5400468247694293.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:16:09,955] Trial 4 finished with value: 0.4977270139397019 and parameters: {'iterations': 500, 'learning_rate': 0.04, 'depth': 4, 'l2_leaf_reg': 1.4010850286740397}. Best is trial 3 with value: 0.5400468247694293.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:16:11,121] Trial 5 finished with value: 0.47119300138896275 and parameters: {'iterations': 500, 'learning_rate': 0.04, 'depth': 4, 'l2_leaf_reg': 2.271244298537041}. Best is trial 3 with value: 0.5400468247694293.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:16:12,647] Trial 6 finished with value: 0.48524666938060146 and parameters: {'iterations': 750, 'learning_rate': 0.05, 'depth': 4, 'l2_leaf_reg': 4.04243248283991}. Best is trial 3 with value: 0.5400468247694293.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:16:17,900] Trial 7 finished with value: 0.5482295239914838 and parameters: {'iterations': 500, 'learning_rate': 0.03, 'depth': 7, 'l2_leaf_reg': 1.933981457121793}. Best is trial 7 with value: 0.5482295239914838.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:16:20,359] Trial 8 finished with value: 0.5064749155073949 and parameters: {'iterations': 750, 'learning_rate': 0.03, 'depth': 5, 'l2_leaf_reg': 2.9080393854470183}. Best is trial 7 with value: 0.5482295239914838.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:16:22,750] Trial 9 finished with value: 0.5267199583330872 and parameters: {'iterations': 500, 'learning_rate': 0.05, 'depth': 6, 'l2_leaf_reg': 3.4530331184392464}. Best is trial 7 with value: 0.5482295239914838.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:16:27,972] Trial 10 finished with value: 0.560167178700576 and parameters: {'iterations': 500, 'learning_rate': 0.03, 'depth': 7, 'l2_leaf_reg': 1.0025790178512624}. Best is trial 10 with value: 0.560167178700576.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:16:33,303] Trial 11 finished with value: 0.5505018090206703 and parameters: {'iterations': 500, 'learning_rate': 0.03, 'depth': 7, 'l2_leaf_reg': 1.0695907573447627}. Best is trial 10 with value: 0.560167178700576.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:16:38,507] Trial 12 finished with value: 0.5517775516930882 and parameters: {'iterations': 500, 'learning_rate': 0.03, 'depth': 7, 'l2_leaf_reg': 1.1072007027071278}. Best is trial 10 with value: 0.560167178700576.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:16:43,820] Trial 13 finished with value: 0.5527405750755165 and parameters: {'iterations': 500, 'learning_rate': 0.03, 'depth': 7, 'l2_leaf_reg': 1.591306591891689}. Best is trial 10 with value: 0.560167178700576.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:16:56,589] Trial 14 finished with value: 0.5350920227525852 and parameters: {'iterations': 500, 'learning_rate': 0.02, 'depth': 8, 'l2_leaf_reg': 1.706018782988674}. Best is trial 10 with value: 0.560167178700576.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:16:59,034] Trial 15 finished with value: 0.5077838825715908 and parameters: {'iterations': 500, 'learning_rate': 0.03, 'depth': 6, 'l2_leaf_reg': 2.6913967874188507}. Best is trial 10 with value: 0.560167178700576.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:17:02,343] Trial 16 finished with value: 0.5152898346455994 and parameters: {'iterations': 1000, 'learning_rate': 0.03, 'depth': 5, 'l2_leaf_reg': 1.675628918120725}. Best is trial 10 with value: 0.560167178700576.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:17:07,876] Trial 17 finished with value: 0.5499288623200347 and parameters: {'iterations': 500, 'learning_rate': 0.03, 'depth': 7, 'l2_leaf_reg': 1.0284758184228462}. Best is trial 10 with value: 0.560167178700576.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:17:10,275] Trial 18 finished with value: 0.5159512234779854 and parameters: {'iterations': 500, 'learning_rate': 0.02, 'depth': 6, 'l2_leaf_reg': 2.136944874491288}. Best is trial 10 with value: 0.560167178700576.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:17:35,932] Trial 19 finished with value: 0.5518760155696829 and parameters: {'iterations': 1000, 'learning_rate': 0.03, 'depth': 8, 'l2_leaf_reg': 1.5550803090048337}. Best is trial 10 with value: 0.560167178700576.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:17:37,383] Trial 20 finished with value: 0.5063611292963263 and parameters: {'iterations': 500, 'learning_rate': 0.03, 'depth': 5, 'l2_leaf_reg': 3.450916316496405}. Best is trial 10 with value: 0.560167178700576.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:18:03,534] Trial 21 finished with value: 0.5432480687872593 and parameters: {'iterations': 1000, 'learning_rate': 0.03, 'depth': 8, 'l2_leaf_reg': 1.4845467489196342}. Best is trial 10 with value: 0.560167178700576.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:18:29,614] Trial 22 finished with value: 0.5541548917361284 and parameters: {'iterations': 1000, 'learning_rate': 0.03, 'depth': 8, 'l2_leaf_reg': 1.3764012608559328}. Best is trial 10 with value: 0.560167178700576.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:18:39,914] Trial 23 finished with value: 0.5641761794912997 and parameters: {'iterations': 1000, 'learning_rate': 0.03, 'depth': 7, 'l2_leaf_reg': 1.372553105720123}. Best is trial 23 with value: 0.5641761794912997.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:18:50,111] Trial 24 finished with value: 0.5553500541246498 and parameters: {'iterations': 1000, 'learning_rate': 0.03, 'depth': 7, 'l2_leaf_reg': 1.2905384625397809}. Best is trial 23 with value: 0.5641761794912997.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:19:00,223] Trial 25 finished with value: 0.5456359892330112 and parameters: {'iterations': 1000, 'learning_rate': 0.03, 'depth': 7, 'l2_leaf_reg': 1.9522362617373243}. Best is trial 23 with value: 0.5641761794912997.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:19:10,210] Trial 26 finished with value: 0.5395168196379757 and parameters: {'iterations': 1000, 'learning_rate': 0.04, 'depth': 7, 'l2_leaf_reg': 2.5504747190587542}. Best is trial 23 with value: 0.5641761794912997.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:19:14,846] Trial 27 finished with value: 0.5421184660425177 and parameters: {'iterations': 1000, 'learning_rate': 0.02, 'depth': 6, 'l2_leaf_reg': 1.3073352815760897}. Best is trial 23 with value: 0.5641761794912997.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:19:24,601] Trial 28 finished with value: 0.545844132442238 and parameters: {'iterations': 1000, 'learning_rate': 0.05, 'depth': 7, 'l2_leaf_reg': 1.8543778763151901}. Best is trial 23 with value: 0.5641761794912997.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:19:29,274] Trial 29 finished with value: 0.5382462970884875 and parameters: {'iterations': 1000, 'learning_rate': 0.03, 'depth': 6, 'l2_leaf_reg': 1.0611732927641837}. Best is trial 23 with value: 0.5641761794912997.
[I 2025-09-08 21:19:29,276] A new study created in memory with name: no-name-535b383b-a832-4e9b-997b-3f4328df9873
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.830e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.142e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.089e+02, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:19:29,368] Trial 0 finished with value: 0.42372983841474904 and parameters: {'alpha': 0.00012273916983293736, 'l1_ratio': 0.1503426723470833}. Best is trial 0 with value: 0.42372983841474904.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.671e-01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.499e-02, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:19:29,467] Trial 1 finished with value: 0.30273380990893306 and parameters: {'alpha': 0.04601355235065955, 'l1_ratio': 0.18186161371246368}. Best is trial 0 with value: 0.42372983841474904.

✅ CAT con TOA_15x15_depth_in_3_4 - Mejor R2: 0.56
📋 Parámetros: {'iterations': 1000, 'learning_rate': 0.03, 'depth': 7, 'l2_leaf_reg': 1.372553105720123}

Buscando mejores hiperparámetros para ELN con TOA_15x15_depth_in_3_4...
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 21:19:29,571] Trial 2 finished with value: 0.06637866710246221 and parameters: {'alpha': 0.16454582961125513, 'l1_ratio': 0.6415721760523768}. Best is trial 0 with value: 0.42372983841474904.
[I 2025-09-08 21:19:29,634] Trial 3 finished with value: 0.050289949929318976 and parameters: {'alpha': 0.1595393917151961, 'l1_ratio': 0.8022504431109073}. Best is trial 0 with value: 0.42372983841474904.
[I 2025-09-08 21:19:29,707] Trial 4 finished with value: 0.02683505091582124 and parameters: {'alpha': 0.28391558271058115, 'l1_ratio': 0.6810552180454785}. Best is trial 0 with value: 0.42372983841474904.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:19:29,785] Trial 5 finished with value: 0.23727775315834232 and parameters: {'alpha': 0.05640575819883956, 'l1_ratio': 0.42266079876169216}. Best is trial 0 with value: 0.42372983841474904.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.060e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.312e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.012e+02, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:19:29,926] Trial 6 finished with value: 0.42530718280597896 and parameters: {'alpha': 0.0001311822286370697, 'l1_ratio': 0.647837115444159}. Best is trial 6 with value: 0.42530718280597896.
[I 2025-09-08 21:19:30,023] Trial 7 finished with value: 0.12771760020099052 and parameters: {'alpha': 0.2688160496960592, 'l1_ratio': 0.1771530643945358}. Best is trial 6 with value: 0.42530718280597896.
[I 2025-09-08 21:19:30,125] Trial 8 finished with value: 0.2326380218813957 and parameters: {'alpha': 0.03569632925424705, 'l1_ratio': 0.7447312506834712}. Best is trial 6 with value: 0.42530718280597896.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.107e+00, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.997e+00, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.094e+00, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:19:30,234] Trial 9 finished with value: 0.3600844994425452 and parameters: {'alpha': 0.007244057833666656, 'l1_ratio': 0.4627346018069086}. Best is trial 6 with value: 0.42530718280597896.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.940e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.230e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.914e+01, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:19:30,373] Trial 10 finished with value: 0.42642802719864026 and parameters: {'alpha': 0.00011050358458123106, 'l1_ratio': 0.8845168226843667}. Best is trial 10 with value: 0.42642802719864026.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.617e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.922e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.667e+01, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:19:30,520] Trial 11 finished with value: 0.4260376505069299 and parameters: {'alpha': 0.0001429277835819054, 'l1_ratio': 0.8968216812349378}. Best is trial 10 with value: 0.42642802719864026.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.685e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.754e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.003e+01, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:19:30,638] Trial 12 finished with value: 0.4105363969578546 and parameters: {'alpha': 0.0009157620391283335, 'l1_ratio': 0.878850987470196}. Best is trial 10 with value: 0.42642802719864026.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.669e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.894e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.246e+01, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:19:30,783] Trial 13 finished with value: 0.4109867325070142 and parameters: {'alpha': 0.0008804720393494825, 'l1_ratio': 0.8710061913684672}. Best is trial 10 with value: 0.42642802719864026.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.789e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.626e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.505e+01, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:19:30,947] Trial 14 finished with value: 0.41083060157175605 and parameters: {'alpha': 0.0006168919139777279, 'l1_ratio': 0.37994406858079055}. Best is trial 10 with value: 0.42642802719864026.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.151e-01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.650e+00, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.986e+00, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:19:31,054] Trial 15 finished with value: 0.372861336506258 and parameters: {'alpha': 0.004444753803802577, 'l1_ratio': 0.5947371185819933}. Best is trial 10 with value: 0.42642802719864026.

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.039e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.869e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.069e+01, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:19:31,151] Trial 16 finished with value: 0.42013324590319145 and parameters: {'alpha': 0.0003867297152981126, 'l1_ratio': 0.7741457312254958}. Best is trial 10 with value: 0.42642802719864026.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.036e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.251e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.597e+01, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:19:31,257] Trial 17 finished with value: 0.38814688650156554 and parameters: {'alpha': 0.0023855566805407393, 'l1_ratio': 0.5419074077838444}. Best is trial 10 with value: 0.42642802719864026.

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.158e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.401e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.050e+02, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:19:31,383] Trial 18 finished with value: 0.4208826034220315 and parameters: {'alpha': 0.00022758910839684447, 'l1_ratio': 0.2931160058882213}. Best is trial 10 with value: 0.42642802719864026.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.604e+00, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.000e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.663e+01, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:19:31,498] Trial 19 finished with value: 0.38942657598854485 and parameters: {'alpha': 0.002017239329536046, 'l1_ratio': 0.8904347666429075}. Best is trial 10 with value: 0.42642802719864026.

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.782e-02, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.404e-01, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:19:31,610] Trial 20 finished with value: 0.31970825686970233 and parameters: {'alpha': 0.014391411568364482, 'l1_ratio': 0.7231562600750139}. Best is trial 10 with value: 0.42642802719864026.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.070e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.352e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.004e+02, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:19:31,721] Trial 21 finished with value: 0.4263775418694092 and parameters: {'alpha': 0.00010335226105041431, 'l1_ratio': 0.8204830964748868}. Best is trial 10 with value: 0.42642802719864026.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 21:19:31,797] Trial 22 finished with value: 0.009070990185643687 and parameters: {'alpha': 0.9762914330394723, 'l1_ratio': 0.824115587539032}. Best is trial 10 with value: 0.42642802719864026.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.580e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.626e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.830e+01, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:19:31,898] Trial 23 finished with value: 0.42320148842083194 and parameters: {'alpha': 0.00027826638186674634, 'l1_ratio': 0.8015182488164068}. Best is trial 10 with value: 0.42642802719864026.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.052e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.336e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.002e+02, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:19:32,066] Trial 24 finished with value: 0.42642036158007973 and parameters: {'alpha': 0.00010338619533242604, 'l1_ratio': 0.8373811410831642}. Best is trial 10 with value: 0.42642802719864026.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.056e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.002e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.110e+01, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:19:32,184] Trial 25 finished with value: 0.41947289899464835 and parameters: {'alpha': 0.0003951434222031422, 'l1_ratio': 0.7093017835004859}. Best is trial 10 with value: 0.42642802719864026.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.808e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.644e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.814e+01, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:19:32,291] Trial 26 finished with value: 0.3986390844292089 and parameters: {'alpha': 0.0014966774882515042, 'l1_ratio': 0.8385412324864201}. Best is trial 10 with value: 0.42642802719864026.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.296e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.554e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.032e+02, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:19:32,418] Trial 27 finished with value: 0.42549623242296625 and parameters: {'alpha': 0.00011077673155996855, 'l1_ratio': 0.5742718328479509}. Best is trial 10 with value: 0.42642802719864026.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.858e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.124e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.255e+01, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:19:32,545] Trial 28 finished with value: 0.42378218657923333 and parameters: {'alpha': 0.00023618516102317995, 'l1_ratio': 0.759455642708195}. Best is trial 10 with value: 0.42642802719864026.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.706e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.721e+01, tolerance: 3.336e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.153e+01, tolerance: 4.300e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:19:32,646] Trial 29 finished with value: 0.4156820873806879 and parameters: {'alpha': 0.0005859872891702842, 'l1_ratio': 0.8316464080404752}. Best is trial 10 with value: 0.42642802719864026.
[I 2025-09-08 21:19:32,648] A new study created in memory with name: no-name-ffa4b7af-56b8-4825-83be-1bb0817ba923

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

✅ ELN con TOA_15x15_depth_in_3_4 - Mejor R2: 0.43
📋 Parámetros: {'alpha': 0.00011050358458123106, 'l1_ratio': 0.8845168226843667}

Buscando mejores hiperparámetros para XGB con C2X-Complex_rhown_5x5_depth_in_3_4...
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:19:35,984] Trial 0 finished with value: 0.3561950980493595 and parameters: {'n_estimators': 750, 'learning_rate': 0.01, 'max_depth': 8, 'min_child_weight': 4, 'subsample': 0.6553181342618327, 'colsample_bytree': 0.6028089721736766}. Best is trial 0 with value: 0.3561950980493595.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:19:41,511] Trial 1 finished with value: 0.3074275236036403 and parameters: {'n_estimators': 1000, 'learning_rate': 0.02, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.6836034013714322, 'colsample_bytree': 0.7611223557156367}. Best is trial 0 with value: 0.3561950980493595.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:19:45,269] Trial 2 finished with value: 0.3260750001307533 and parameters: {'n_estimators': 750, 'learning_rate': 0.02, 'max_depth': 8, 'min_child_weight': 4, 'subsample': 0.6147500880611307, 'colsample_bytree': 0.7265985439108162}. Best is trial 0 with value: 0.3561950980493595.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:19:50,756] Trial 3 finished with value: 0.29225758229099286 and parameters: {'n_estimators': 1000, 'learning_rate': 0.03, 'max_depth': 8, 'min_child_weight': 4, 'subsample': 0.7995218663982286, 'colsample_bytree': 0.7352283989784567}. Best is trial 0 with value: 0.3561950980493595.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:19:54,987] Trial 4 finished with value: 0.31930479420442465 and parameters: {'n_estimators': 1250, 'learning_rate': 0.02, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.6231880588778459, 'colsample_bytree': 0.6310797762503875}. Best is trial 0 with value: 0.3561950980493595.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:19:58,803] Trial 5 finished with value: 0.30834450831688753 and parameters: {'n_estimators': 750, 'learning_rate': 0.03, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.7014880055265577, 'colsample_bytree': 0.7414542957774841}. Best is trial 0 with value: 0.3561950980493595.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:20:01,217] Trial 6 finished with value: 0.3000540286607929 and parameters: {'n_estimators': 750, 'learning_rate': 0.03, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.6596647602330414, 'colsample_bytree': 0.623989791774949}. Best is trial 0 with value: 0.3561950980493595.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:20:04,763] Trial 7 finished with value: 0.34905150678771046 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.7250582607971089, 'colsample_bytree': 0.60015179374779}. Best is trial 0 with value: 0.3561950980493595.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:20:09,362] Trial 8 finished with value: 0.3440378328630765 and parameters: {'n_estimators': 1250, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.7020170104402683, 'colsample_bytree': 0.6002520901107519}. Best is trial 0 with value: 0.3561950980493595.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:20:12,944] Trial 9 finished with value: 0.3475392101570131 and parameters: {'n_estimators': 750, 'learning_rate': 0.01, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.7596607475240417, 'colsample_bytree': 0.7133150162000976}. Best is trial 0 with value: 0.3561950980493595.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:20:15,757] Trial 10 finished with value: 0.361356730095209 and parameters: {'n_estimators': 750, 'learning_rate': 0.01, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.6513352880077945, 'colsample_bytree': 0.6764997325968356}. Best is trial 10 with value: 0.361356730095209.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:20:18,384] Trial 11 finished with value: 0.3563583990603367 and parameters: {'n_estimators': 750, 'learning_rate': 0.01, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.6563076929349949, 'colsample_bytree': 0.6724649458356228}. Best is trial 10 with value: 0.361356730095209.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:20:21,091] Trial 12 finished with value: 0.36465642480962784 and parameters: {'n_estimators': 750, 'learning_rate': 0.01, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.6531183551344321, 'colsample_bytree': 0.6779081844202318}. Best is trial 12 with value: 0.36465642480962784.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:20:23,960] Trial 13 finished with value: 0.35924549526910726 and parameters: {'n_estimators': 750, 'learning_rate': 0.01, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.6336858567184495, 'colsample_bytree': 0.6755817419391366}. Best is trial 12 with value: 0.36465642480962784.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:20:28,479] Trial 14 finished with value: 0.3381101228934795 and parameters: {'n_estimators': 1250, 'learning_rate': 0.01, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.6756554865769984, 'colsample_bytree': 0.6792102057358926}. Best is trial 12 with value: 0.36465642480962784.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:20:31,531] Trial 15 finished with value: 0.34444865537113145 and parameters: {'n_estimators': 750, 'learning_rate': 0.01, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.6399704197820804, 'colsample_bytree': 0.793536011907402}. Best is trial 12 with value: 0.36465642480962784.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:20:33,932] Trial 16 finished with value: 0.3696566863441488 and parameters: {'n_estimators': 750, 'learning_rate': 0.01, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.6035709044473411, 'colsample_bytree': 0.6474841281311986}. Best is trial 16 with value: 0.3696566863441488.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:20:37,545] Trial 17 finished with value: 0.3492340979400936 and parameters: {'n_estimators': 750, 'learning_rate': 0.01, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.6018298094765805, 'colsample_bytree': 0.6525360752471941}. Best is trial 16 with value: 0.3696566863441488.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:20:42,889] Trial 18 finished with value: 0.29952124885701464 and parameters: {'n_estimators': 1250, 'learning_rate': 0.03, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.6017535751430694, 'colsample_bytree': 0.7001622498679055}. Best is trial 16 with value: 0.3696566863441488.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:20:46,961] Trial 19 finished with value: 0.3215044172587244 and parameters: {'n_estimators': 1000, 'learning_rate': 0.02, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.7312604745164041, 'colsample_bytree': 0.6468803385812882}. Best is trial 16 with value: 0.3696566863441488.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:20:49,188] Trial 20 finished with value: 0.3700574575132669 and parameters: {'n_estimators': 750, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.625779949227601, 'colsample_bytree': 0.6525948120517908}. Best is trial 20 with value: 0.3700574575132669.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:20:51,571] Trial 21 finished with value: 0.37256428086150667 and parameters: {'n_estimators': 750, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.6217244242963522, 'colsample_bytree': 0.6523782484973186}. Best is trial 21 with value: 0.37256428086150667.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:20:53,791] Trial 22 finished with value: 0.3700574575132669 and parameters: {'n_estimators': 750, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.6257742292645484, 'colsample_bytree': 0.6502172333566307}. Best is trial 21 with value: 0.37256428086150667.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:20:56,017] Trial 23 finished with value: 0.3692752121812051 and parameters: {'n_estimators': 750, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.6245964665900127, 'colsample_bytree': 0.6270988898738672}. Best is trial 21 with value: 0.37256428086150667.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:20:58,253] Trial 24 finished with value: 0.362849412281615 and parameters: {'n_estimators': 750, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.6774012931306932, 'colsample_bytree': 0.6589752930727901}. Best is trial 21 with value: 0.37256428086150667.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:21:00,916] Trial 25 finished with value: 0.3615164172369633 and parameters: {'n_estimators': 750, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.6368990206835715, 'colsample_bytree': 0.6949882664913785}. Best is trial 21 with value: 0.37256428086150667.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:21:03,157] Trial 26 finished with value: 0.37562793560578117 and parameters: {'n_estimators': 750, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.6166618031001413, 'colsample_bytree': 0.6351163826019478}. Best is trial 26 with value: 0.37562793560578117.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:21:05,359] Trial 27 finished with value: 0.3786007655990189 and parameters: {'n_estimators': 750, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.6167125513109382, 'colsample_bytree': 0.618695331209452}. Best is trial 27 with value: 0.3786007655990189.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:21:09,346] Trial 28 finished with value: 0.3214586949068887 and parameters: {'n_estimators': 1250, 'learning_rate': 0.02, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.6432115379688311, 'colsample_bytree': 0.6168204954409883}. Best is trial 27 with value: 0.3786007655990189.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:21:12,739] Trial 29 finished with value: 0.29498413681738006 and parameters: {'n_estimators': 1000, 'learning_rate': 0.03, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.666372384933962, 'colsample_bytree': 0.6176501370018435}. Best is trial 27 with value: 0.3786007655990189.
[I 2025-09-08 21:21:12,742] A new study created in memory with name: no-name-44a14aef-94cd-493e-be4e-760417575e25

✅ XGB con C2X-Complex_rhown_5x5_depth_in_3_4 - Mejor R2: 0.38
📋 Parámetros: {'n_estimators': 750, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.6167125513109382, 'colsample_bytree': 0.618695331209452}

Buscando mejores hiperparámetros para LBM con C2X-Complex_rhown_5x5_depth_in_3_4...
Fold 1
Fold 2

[I 2025-09-08 21:21:13,253] Trial 0 finished with value: 0.32223038451729524 and parameters: {'learning_rate': 0.04, 'num_leaves': 10, 'max_depth': 8, 'min_child_samples': 5, 'subsample': 0.7761863793542471, 'colsample_bytree': 0.7803014094744105, 'n_estimators': 1250, 'min_split_gain': 0.0}. Best is trial 0 with value: 0.32223038451729524.

Fold 3
Fold 1

[I 2025-09-08 21:21:13,412] Trial 1 finished with value: 0.41247279489009764 and parameters: {'learning_rate': 0.02, 'num_leaves': 30, 'max_depth': 5, 'min_child_samples': 7, 'subsample': 0.6810195910436888, 'colsample_bytree': 0.771771738809041, 'n_estimators': 1000, 'min_split_gain': 1.0}. Best is trial 1 with value: 0.41247279489009764.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:21:13,551] Trial 2 finished with value: 0.3864595487788316 and parameters: {'learning_rate': 0.04, 'num_leaves': 30, 'max_depth': 5, 'min_child_samples': 5, 'subsample': 0.6210157896827804, 'colsample_bytree': 0.7036477222161746, 'n_estimators': 1250, 'min_split_gain': 1.0}. Best is trial 1 with value: 0.41247279489009764.
[I 2025-09-08 21:21:13,672] Trial 3 finished with value: 0.3289920509037231 and parameters: {'learning_rate': 0.05, 'num_leaves': 30, 'max_depth': 5, 'min_child_samples': 6, 'subsample': 0.7882256072094436, 'colsample_bytree': 0.6141378313116586, 'n_estimators': 1000, 'min_split_gain': 0.5}. Best is trial 1 with value: 0.41247279489009764.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:21:13,790] Trial 4 finished with value: 0.362374873565061 and parameters: {'learning_rate': 0.04, 'num_leaves': 10, 'max_depth': 6, 'min_child_samples': 6, 'subsample': 0.6881387583278518, 'colsample_bytree': 0.6148354429598315, 'n_estimators': 1000, 'min_split_gain': 0.5}. Best is trial 1 with value: 0.41247279489009764.
[I 2025-09-08 21:21:13,967] Trial 5 finished with value: 0.37565869383688194 and parameters: {'learning_rate': 0.03, 'num_leaves': 30, 'max_depth': 8, 'min_child_samples': 4, 'subsample': 0.7829094182195668, 'colsample_bytree': 0.7506423299824785, 'n_estimators': 1250, 'min_split_gain': 0.5}. Best is trial 1 with value: 0.41247279489009764.

Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 21:21:14,201] Trial 6 finished with value: 0.35117647866477425 and parameters: {'learning_rate': 0.02, 'num_leaves': 30, 'max_depth': 8, 'min_child_samples': 5, 'subsample': 0.7333729765998545, 'colsample_bytree': 0.7271553966390205, 'n_estimators': 1000, 'min_split_gain': 0.2}. Best is trial 1 with value: 0.41247279489009764.

Fold 2
Fold 3
Fold 1

[I 2025-09-08 21:21:14,483] Trial 7 finished with value: 0.34838842745589105 and parameters: {'learning_rate': 0.02, 'num_leaves': 10, 'max_depth': 5, 'min_child_samples': 8, 'subsample': 0.7206297149345764, 'colsample_bytree': 0.6187950600352363, 'n_estimators': 1000, 'min_split_gain': 0.0}. Best is trial 1 with value: 0.41247279489009764.

Fold 2
Fold 3
Fold 1

[I 2025-09-08 21:21:14,644] Trial 8 finished with value: 0.3473064726702521 and parameters: {'learning_rate': 0.04, 'num_leaves': 30, 'max_depth': 6, 'min_child_samples': 5, 'subsample': 0.790799311569572, 'colsample_bytree': 0.6829080499055986, 'n_estimators': 1250, 'min_split_gain': 0.2}. Best is trial 1 with value: 0.41247279489009764.

Fold 2
Fold 3
Fold 1

[I 2025-09-08 21:21:14,912] Trial 9 finished with value: 0.31773444104965837 and parameters: {'learning_rate': 0.03, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 8, 'subsample': 0.7049818361889145, 'colsample_bytree': 0.7485440404463415, 'n_estimators': 1000, 'min_split_gain': 0.1}. Best is trial 1 with value: 0.41247279489009764.

Fold 2
Fold 3
Fold 1

[I 2025-09-08 21:21:15,084] Trial 10 finished with value: 0.40651299157815707 and parameters: {'learning_rate': 0.02, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 7, 'subsample': 0.6402971382019693, 'colsample_bytree': 0.7961901475753248, 'n_estimators': 750, 'min_split_gain': 1.0}. Best is trial 1 with value: 0.41247279489009764.

Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 21:21:15,261] Trial 11 finished with value: 0.40651299157815707 and parameters: {'learning_rate': 0.02, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 7, 'subsample': 0.634677202668733, 'colsample_bytree': 0.7970685237044015, 'n_estimators': 750, 'min_split_gain': 1.0}. Best is trial 1 with value: 0.41247279489009764.

Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:21:15,430] Trial 12 finished with value: 0.3907393874327301 and parameters: {'learning_rate': 0.02, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 7, 'subsample': 0.6565634584465112, 'colsample_bytree': 0.7719296614315858, 'n_estimators': 750, 'min_split_gain': 1.0}. Best is trial 1 with value: 0.41247279489009764.
[I 2025-09-08 21:21:15,602] Trial 13 finished with value: 0.40651299157815707 and parameters: {'learning_rate': 0.02, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 7, 'subsample': 0.6636496858638177, 'colsample_bytree': 0.7997258722341559, 'n_estimators': 750, 'min_split_gain': 1.0}. Best is trial 1 with value: 0.41247279489009764.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 21:21:15,714] Trial 14 finished with value: 0.3821659040675122 and parameters: {'learning_rate': 0.05, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 7, 'subsample': 0.6053322287344656, 'colsample_bytree': 0.6784433525188184, 'n_estimators': 750, 'min_split_gain': 1.0}. Best is trial 1 with value: 0.41247279489009764.

Fold 3
Fold 1
Fold 2

[I 2025-09-08 21:21:15,994] Trial 15 finished with value: 0.3319245876812123 and parameters: {'learning_rate': 0.02, 'num_leaves': 30, 'max_depth': 7, 'min_child_samples': 8, 'subsample': 0.6678271183566268, 'colsample_bytree': 0.7587671587518305, 'n_estimators': 750, 'min_split_gain': 0.1}. Best is trial 1 with value: 0.41247279489009764.

Fold 3
Fold 1
Fold 2

[I 2025-09-08 21:21:16,176] Trial 16 finished with value: 0.3801249151489527 and parameters: {'learning_rate': 0.02, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 6, 'subsample': 0.6413241843853486, 'colsample_bytree': 0.720935361678593, 'n_estimators': 1000, 'min_split_gain': 1.0}. Best is trial 1 with value: 0.41247279489009764.

Fold 3
Fold 1
Fold 2

[I 2025-09-08 21:21:16,401] Trial 17 finished with value: 0.3985930420931139 and parameters: {'learning_rate': 0.02, 'num_leaves': 30, 'max_depth': 6, 'min_child_samples': 7, 'subsample': 0.7496784368951677, 'colsample_bytree': 0.6511925383847647, 'n_estimators': 750, 'min_split_gain': 1.0}. Best is trial 1 with value: 0.41247279489009764.
[I 2025-09-08 21:21:16,512] Trial 18 finished with value: 0.3581576158324955 and parameters: {'learning_rate': 0.05, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 6, 'subsample': 0.6836409646174207, 'colsample_bytree': 0.7783414466040156, 'n_estimators': 750, 'min_split_gain': 1.0}. Best is trial 1 with value: 0.41247279489009764.

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 21:21:16,749] Trial 19 finished with value: 0.3449087835883737 and parameters: {'learning_rate': 0.03, 'num_leaves': 10, 'max_depth': 8, 'min_child_samples': 8, 'subsample': 0.6338017169277267, 'colsample_bytree': 0.7305210525207272, 'n_estimators': 1000, 'min_split_gain': 0.1}. Best is trial 1 with value: 0.41247279489009764.

Fold 2
Fold 3
Fold 1

[I 2025-09-08 21:21:16,996] Trial 20 finished with value: 0.3601522208035101 and parameters: {'learning_rate': 0.02, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 7, 'subsample': 0.6072995782148665, 'colsample_bytree': 0.7719019137582225, 'n_estimators': 1000, 'min_split_gain': 0.2}. Best is trial 1 with value: 0.41247279489009764.

Fold 2
Fold 3
Fold 1

[I 2025-09-08 21:21:17,162] Trial 21 finished with value: 0.40651299157815707 and parameters: {'learning_rate': 0.02, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 7, 'subsample': 0.6476415754858155, 'colsample_bytree': 0.7999181635399838, 'n_estimators': 750, 'min_split_gain': 1.0}. Best is trial 1 with value: 0.41247279489009764.

Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 21:21:17,362] Trial 22 finished with value: 0.40651299157815707 and parameters: {'learning_rate': 0.02, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 7, 'subsample': 0.6267267552944017, 'colsample_bytree': 0.7993384207374779, 'n_estimators': 750, 'min_split_gain': 1.0}. Best is trial 1 with value: 0.41247279489009764.

Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:21:17,529] Trial 23 finished with value: 0.34980831175610255 and parameters: {'learning_rate': 0.02, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 6, 'subsample': 0.6834909977554602, 'colsample_bytree': 0.7855069071703157, 'n_estimators': 750, 'min_split_gain': 1.0}. Best is trial 1 with value: 0.41247279489009764.
[I 2025-09-08 21:21:17,692] Trial 24 finished with value: 0.3840044194065229 and parameters: {'learning_rate': 0.02, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 8, 'subsample': 0.6658911668233959, 'colsample_bytree': 0.7642397342718896, 'n_estimators': 750, 'min_split_gain': 1.0}. Best is trial 1 with value: 0.41247279489009764.

Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 21:21:18,020] Trial 25 finished with value: 0.3569618555592606 and parameters: {'learning_rate': 0.02, 'num_leaves': 30, 'max_depth': 7, 'min_child_samples': 7, 'subsample': 0.618519876779057, 'colsample_bytree': 0.7421642048424194, 'n_estimators': 750, 'min_split_gain': 0.0}. Best is trial 1 with value: 0.41247279489009764.

Fold 2
Fold 3

[I 2025-09-08 21:21:18,181] Trial 26 finished with value: 0.3599274277121169 and parameters: {'learning_rate': 0.02, 'num_leaves': 20, 'max_depth': 8, 'min_child_samples': 6, 'subsample': 0.6495063592480476, 'colsample_bytree': 0.7863421367730975, 'n_estimators': 750, 'min_split_gain': 1.0}. Best is trial 1 with value: 0.41247279489009764.

Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 21:21:18,326] Trial 27 finished with value: 0.39673984092069753 and parameters: {'learning_rate': 0.03, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 7, 'subsample': 0.6986286392106907, 'colsample_bytree': 0.7078306935532295, 'n_estimators': 750, 'min_split_gain': 1.0}. Best is trial 1 with value: 0.41247279489009764.

Fold 2
Fold 3
Fold 1

[I 2025-09-08 21:21:18,547] Trial 28 finished with value: 0.3770426018796538 and parameters: {'learning_rate': 0.05, 'num_leaves': 30, 'max_depth': 7, 'min_child_samples': 8, 'subsample': 0.6763842915249971, 'colsample_bytree': 0.7649646880121794, 'n_estimators': 1250, 'min_split_gain': 1.0}. Best is trial 1 with value: 0.41247279489009764.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:21:18,948] Trial 29 finished with value: 0.2695631792356295 and parameters: {'learning_rate': 0.04, 'num_leaves': 10, 'max_depth': 8, 'min_child_samples': 6, 'subsample': 0.638381833445959, 'colsample_bytree': 0.7804232083012551, 'n_estimators': 1000, 'min_split_gain': 0.0}. Best is trial 1 with value: 0.41247279489009764.
[I 2025-09-08 21:21:18,951] A new study created in memory with name: no-name-26e49f4c-2fe5-4ba6-92b0-1d5dc6136d5a
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

✅ LBM con C2X-Complex_rhown_5x5_depth_in_3_4 - Mejor R2: 0.41
📋 Parámetros: {'learning_rate': 0.02, 'num_leaves': 30, 'max_depth': 5, 'min_child_samples': 7, 'subsample': 0.6810195910436888, 'colsample_bytree': 0.771771738809041, 'n_estimators': 1000, 'min_split_gain': 1.0}

Buscando mejores hiperparámetros para MLP con C2X-Complex_rhown_5x5_depth_in_3_4...
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:21:19,309] Trial 0 finished with value: 0.38365456742675574 and parameters: {'hidden_layer_sizes': (128,), 'activation': 'relu', 'solver': 'adam', 'alpha': 4.837934884566034e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.008785818275249019}. Best is trial 0 with value: 0.38365456742675574.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 21:21:20,756] Trial 1 finished with value: 0.4445699448139941 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.003841892304309113, 'learning_rate': 'constant', 'learning_rate_init': 0.0006736132434403384}. Best is trial 1 with value: 0.4445699448139941.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:21:21,247] Trial 2 finished with value: 0.43007143675451226 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'relu', 'solver': 'adam', 'alpha': 7.285385357052363e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.002786357429230474}. Best is trial 1 with value: 0.4445699448139941.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 21:21:22,171] Trial 3 finished with value: 0.19799296985154424 and parameters: {'hidden_layer_sizes': (64,), 'activation': 'relu', 'solver': 'sgd', 'alpha': 1.1772967033082564e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.00018841117618405268}. Best is trial 1 with value: 0.4445699448139941.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 21:21:22,730] Trial 4 finished with value: 0.41889971872979853 and parameters: {'hidden_layer_sizes': (32,), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.009549979143668029, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00040460488828786566}. Best is trial 1 with value: 0.4445699448139941.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 21:21:23,310] Trial 5 finished with value: 0.3739579023263618 and parameters: {'hidden_layer_sizes': (128,), 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0027747437259528674, 'learning_rate': 'constant', 'learning_rate_init': 0.0018494723058986803}. Best is trial 1 with value: 0.4445699448139941.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 21:21:24,424] Trial 6 finished with value: 0.3282583720512314 and parameters: {'hidden_layer_sizes': (64,), 'activation': 'relu', 'solver': 'adam', 'alpha': 1.8401894526197817e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00017143387831450717}. Best is trial 1 with value: 0.4445699448139941.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 21:21:25,394] Trial 7 finished with value: 0.3275784322844044 and parameters: {'hidden_layer_sizes': (128,), 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.0014936633234808561, 'learning_rate': 'constant', 'learning_rate_init': 0.000430128571921504}. Best is trial 1 with value: 0.4445699448139941.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 21:21:26,630] Trial 8 finished with value: 0.4667206573045298 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.019746577031392744, 'learning_rate': 'constant', 'learning_rate_init': 0.0003288180706169165}. Best is trial 8 with value: 0.4667206573045298.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

[I 2025-09-08 21:21:27,043] Trial 9 finished with value: 0.2887251686598119 and parameters: {'hidden_layer_sizes': (32,), 'activation': 'relu', 'solver': 'adam', 'alpha': 0.018787113545575804, 'learning_rate': 'constant', 'learning_rate_init': 0.007396324637315977}. Best is trial 8 with value: 0.4667206573045298.

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 21:21:28,428] Trial 10 finished with value: 0.33500463215305104 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.08817733789267237, 'learning_rate': 'constant', 'learning_rate_init': 0.0001057192964852092}. Best is trial 8 with value: 0.4667206573045298.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 21:21:29,666] Trial 11 finished with value: 0.44850287423879687 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.01653175057308487, 'learning_rate': 'constant', 'learning_rate_init': 0.0007279311472098551}. Best is trial 8 with value: 0.4667206573045298.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 21:21:31,001] Trial 12 finished with value: 0.4657508707932778 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.046517973841952505, 'learning_rate': 'constant', 'learning_rate_init': 0.0011494347482275988}. Best is trial 8 with value: 0.4667206573045298.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 21:21:32,036] Trial 13 finished with value: 0.47340673360374197 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.09858882509565808, 'learning_rate': 'constant', 'learning_rate_init': 0.0017842511788359818}. Best is trial 13 with value: 0.47340673360374197.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:21:32,549] Trial 14 finished with value: 0.48442673313465784 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0004446736671055645, 'learning_rate': 'constant', 'learning_rate_init': 0.0038350535527577763}. Best is trial 14 with value: 0.48442673313465784.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 21:21:33,686] Trial 15 finished with value: 0.47451181304400336 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.00033788131339758273, 'learning_rate': 'constant', 'learning_rate_init': 0.004064973169940874}. Best is trial 14 with value: 0.48442673313465784.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:21:34,255] Trial 16 finished with value: 0.48521851798765975 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.00032009888390899824, 'learning_rate': 'constant', 'learning_rate_init': 0.0039908853613671745}. Best is trial 16 with value: 0.48521851798765975.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2

[I 2025-09-08 21:21:34,771] Trial 17 finished with value: 0.41178022739903947 and parameters: {'hidden_layer_sizes': (32,), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.00029014190504408595, 'learning_rate': 'constant', 'learning_rate_init': 0.0042307315941237525}. Best is trial 16 with value: 0.48521851798765975.

Fold 3
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 2
Fold 3

[I 2025-09-08 21:21:35,556] Trial 18 finished with value: 0.4460341962395453 and parameters: {'hidden_layer_sizes': (64,), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.00042812281826177167, 'learning_rate': 'adaptive', 'learning_rate_init': 0.005661754965688448}. Best is trial 16 with value: 0.48521851798765975.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:21:36,192] Trial 19 finished with value: 0.48539451180957 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.00011799308934315778, 'learning_rate': 'constant', 'learning_rate_init': 0.0021608187105178703}. Best is trial 19 with value: 0.48539451180957.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:21:36,855] Trial 20 finished with value: 0.4860609826862878 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.00011605853738486838, 'learning_rate': 'constant', 'learning_rate_init': 0.0019512908785049307}. Best is trial 20 with value: 0.4860609826862878.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:21:37,587] Trial 21 finished with value: 0.48531662146776045 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.00011430611840888799, 'learning_rate': 'constant', 'learning_rate_init': 0.002100010206256106}. Best is trial 20 with value: 0.4860609826862878.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:21:38,408] Trial 22 finished with value: 0.4854719356818656 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'adam', 'alpha': 7.958570532807908e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.0017403338706969067}. Best is trial 20 with value: 0.4860609826862878.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:21:39,281] Trial 23 finished with value: 0.47946352397554226 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'adam', 'alpha': 3.4080999673782575e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.0012468869335646704}. Best is trial 20 with value: 0.4860609826862878.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2

[I 2025-09-08 21:21:39,867] Trial 24 finished with value: 0.4851792269021617 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.00013184643458151614, 'learning_rate': 'constant', 'learning_rate_init': 0.002647171007174997}. Best is trial 20 with value: 0.4860609826862878.

Fold 3
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 2
Fold 3

[I 2025-09-08 21:21:40,825] Trial 25 finished with value: 0.48258264884779395 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.00011446279668658509, 'learning_rate': 'constant', 'learning_rate_init': 0.0014039407047127717}. Best is trial 20 with value: 0.4860609826862878.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 21:21:41,537] Trial 26 finished with value: 0.45509991787540444 and parameters: {'hidden_layer_sizes': (64,), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.001169158451340536, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0008528084047241746}. Best is trial 20 with value: 0.4860609826862878.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:21:42,141] Trial 27 finished with value: 0.41359508745315204 and parameters: {'hidden_layer_sizes': (32,), 'activation': 'tanh', 'solver': 'adam', 'alpha': 3.10667089783262e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.0023524835091037226}. Best is trial 20 with value: 0.4860609826862878.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 21:21:43,008] Trial 28 finished with value: 0.40263932135533514 and parameters: {'hidden_layer_sizes': (128,), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0001970075265979172, 'learning_rate': 'constant', 'learning_rate_init': 0.0015377825192227589}. Best is trial 20 with value: 0.4860609826862878.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 21:21:43,817] Trial 29 finished with value: 0.39493975534680126 and parameters: {'hidden_layer_sizes': (128,), 'activation': 'relu', 'solver': 'adam', 'alpha': 6.14057643574123e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0009061981760124494}. Best is trial 20 with value: 0.4860609826862878.
[I 2025-09-08 21:21:43,819] A new study created in memory with name: no-name-73685030-7670-415f-a1f6-e65623f5ec56
[I 2025-09-08 21:21:43,890] Trial 0 finished with value: 0.43169382896086117 and parameters: {'C': 5.139984506750667, 'epsilon': 0.10154483327283602}. Best is trial 0 with value: 0.43169382896086117.
[I 2025-09-08 21:21:43,942] Trial 1 finished with value: 0.30304576276761497 and parameters: {'C': 0.20644724829229147, 'epsilon': 0.10478748198493575}. Best is trial 0 with value: 0.43169382896086117.
[I 2025-09-08 21:21:43,991] Trial 2 finished with value: 0.36974668718380826 and parameters: {'C': 0.4045522998084499, 'epsilon': 0.028564799704968558}. Best is trial 0 with value: 0.43169382896086117.

✅ MLP con C2X-Complex_rhown_5x5_depth_in_3_4 - Mejor R2: 0.49
📋 Parámetros: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.00011605853738486838, 'learning_rate': 'constant', 'learning_rate_init': 0.0019512908785049307}

Buscando mejores hiperparámetros para SVR con C2X-Complex_rhown_5x5_depth_in_3_4...
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 21:21:44,039] Trial 3 finished with value: 0.39849481390171854 and parameters: {'C': 0.528665345745202, 'epsilon': 0.09152956640005498}. Best is trial 0 with value: 0.43169382896086117.
[I 2025-09-08 21:21:44,095] Trial 4 finished with value: 0.3739295392404618 and parameters: {'C': 8.271405919668041, 'epsilon': 0.1466086294574799}. Best is trial 0 with value: 0.43169382896086117.
[I 2025-09-08 21:21:44,145] Trial 5 finished with value: 0.28392217610783865 and parameters: {'C': 0.17288643567600492, 'epsilon': 0.16302815085543815}. Best is trial 0 with value: 0.43169382896086117.
[I 2025-09-08 21:21:44,193] Trial 6 finished with value: 0.2458807553422825 and parameters: {'C': 0.13371927224989472, 'epsilon': 0.0714987884180124}. Best is trial 0 with value: 0.43169382896086117.

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:21:44,239] Trial 7 finished with value: 0.3989325511807367 and parameters: {'C': 0.5215457176874824, 'epsilon': 0.12464391235789397}. Best is trial 0 with value: 0.43169382896086117.
[I 2025-09-08 21:21:44,296] Trial 8 finished with value: 0.47399394916327386 and parameters: {'C': 1.7396967414675988, 'epsilon': 0.18163389874284772}. Best is trial 8 with value: 0.47399394916327386.
[I 2025-09-08 21:21:44,346] Trial 9 finished with value: 0.47231831558828025 and parameters: {'C': 1.657949835200915, 'epsilon': 0.12819241932441758}. Best is trial 8 with value: 0.47399394916327386.
[I 2025-09-08 21:21:44,397] Trial 10 finished with value: 0.479828674768948 and parameters: {'C': 2.2016208512651825, 'epsilon': 0.19360651448939928}. Best is trial 10 with value: 0.479828674768948.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:21:44,451] Trial 11 finished with value: 0.47926141972456654 and parameters: {'C': 2.1476132764741016, 'epsilon': 0.19658029692359355}. Best is trial 10 with value: 0.479828674768948.
[I 2025-09-08 21:21:44,509] Trial 12 finished with value: 0.48221303782620994 and parameters: {'C': 2.912388122647311, 'epsilon': 0.1956408432654206}. Best is trial 12 with value: 0.48221303782620994.
[I 2025-09-08 21:21:44,563] Trial 13 finished with value: 0.4708889094751283 and parameters: {'C': 3.622872509233198, 'epsilon': 0.19994581322918623}. Best is trial 12 with value: 0.48221303782620994.
[I 2025-09-08 21:21:44,613] Trial 14 finished with value: 0.4598321094158715 and parameters: {'C': 1.0230323095528568, 'epsilon': 0.16439247605830692}. Best is trial 12 with value: 0.48221303782620994.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:21:44,668] Trial 15 finished with value: 0.47174895221739604 and parameters: {'C': 3.5378676369778344, 'epsilon': 0.17014242251928421}. Best is trial 12 with value: 0.48221303782620994.
[I 2025-09-08 21:21:44,739] Trial 16 finished with value: 0.3531040019068589 and parameters: {'C': 9.629886955203585, 'epsilon': 0.015144934791475953}. Best is trial 12 with value: 0.48221303782620994.
[I 2025-09-08 21:21:44,821] Trial 17 finished with value: 0.44760996711106854 and parameters: {'C': 0.8579225921724252, 'epsilon': 0.1400529456667403}. Best is trial 12 with value: 0.48221303782620994.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:21:44,887] Trial 18 finished with value: 0.47790848009407255 and parameters: {'C': 2.9899004667376112, 'epsilon': 0.07557607375953715}. Best is trial 12 with value: 0.48221303782620994.
[I 2025-09-08 21:21:44,946] Trial 19 finished with value: 0.46292369616801254 and parameters: {'C': 1.0796772525641043, 'epsilon': 0.18411236560842645}. Best is trial 12 with value: 0.48221303782620994.
[I 2025-09-08 21:21:45,006] Trial 20 finished with value: 0.40876290758225303 and parameters: {'C': 6.004598709233854, 'epsilon': 0.05314115016402319}. Best is trial 12 with value: 0.48221303782620994.
[I 2025-09-08 21:21:45,059] Trial 21 finished with value: 0.47877964698518644 and parameters: {'C': 2.1156693192929, 'epsilon': 0.19444910318375408}. Best is trial 12 with value: 0.48221303782620994.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:21:45,114] Trial 22 finished with value: 0.4828566473857698 and parameters: {'C': 2.7148025546689913, 'epsilon': 0.19941219755965625}. Best is trial 22 with value: 0.4828566473857698.
[I 2025-09-08 21:21:45,179] Trial 23 finished with value: 0.4417614216119241 and parameters: {'C': 4.854227632689277, 'epsilon': 0.17635104484668168}. Best is trial 22 with value: 0.4828566473857698.
[I 2025-09-08 21:21:45,236] Trial 24 finished with value: 0.48015017226727147 and parameters: {'C': 2.7565463233802747, 'epsilon': 0.15107336539979774}. Best is trial 22 with value: 0.4828566473857698.
[I 2025-09-08 21:21:45,290] Trial 25 finished with value: 0.47955596053887534 and parameters: {'C': 2.872177573439217, 'epsilon': 0.1530253485088361}. Best is trial 22 with value: 0.4828566473857698.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 21:21:45,345] Trial 26 finished with value: 0.4696557060964082 and parameters: {'C': 1.4025598515357272, 'epsilon': 0.12448051947044751}. Best is trial 22 with value: 0.4828566473857698.
[I 2025-09-08 21:21:45,410] Trial 27 finished with value: 0.46097025155083954 and parameters: {'C': 3.992084222314294, 'epsilon': 0.15134267766916573}. Best is trial 22 with value: 0.4828566473857698.
[I 2025-09-08 21:21:45,464] Trial 28 finished with value: 0.4819847950686628 and parameters: {'C': 2.69320005444868, 'epsilon': 0.1798344291982802}. Best is trial 22 with value: 0.4828566473857698.
[I 2025-09-08 21:21:45,518] Trial 29 finished with value: 0.39924295259978776 and parameters: {'C': 6.566445690157138, 'epsilon': 0.18345911796335074}. Best is trial 22 with value: 0.4828566473857698.
[I 2025-09-08 21:21:45,519] A new study created in memory with name: no-name-0962b55b-2028-4282-b838-6285e7d6fc47

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

✅ SVR con C2X-Complex_rhown_5x5_depth_in_3_4 - Mejor R2: 0.48
📋 Parámetros: {'C': 2.7148025546689913, 'epsilon': 0.19941219755965625}

Buscando mejores hiperparámetros para KNN con C2X-Complex_rhown_5x5_depth_in_3_4...
Fold 1

[I 2025-09-08 21:21:45,563] Trial 0 finished with value: 0.41954855189614654 and parameters: {'n_neighbors': 7, 'leaf_size': 15}. Best is trial 0 with value: 0.41954855189614654.
[I 2025-09-08 21:21:45,612] Trial 1 finished with value: 0.4316348124076225 and parameters: {'n_neighbors': 12, 'leaf_size': 32}. Best is trial 1 with value: 0.4316348124076225.
[I 2025-09-08 21:21:45,707] Trial 2 finished with value: 0.4316348124076225 and parameters: {'n_neighbors': 12, 'leaf_size': 20}. Best is trial 1 with value: 0.4316348124076225.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 21:21:45,759] Trial 3 finished with value: 0.4382385383435925 and parameters: {'n_neighbors': 10, 'leaf_size': 23}. Best is trial 3 with value: 0.4382385383435925.
[I 2025-09-08 21:21:45,804] Trial 4 finished with value: 0.4346669265196539 and parameters: {'n_neighbors': 9, 'leaf_size': 31}. Best is trial 3 with value: 0.4382385383435925.
[I 2025-09-08 21:21:45,848] Trial 5 finished with value: 0.4352934636725663 and parameters: {'n_neighbors': 8, 'leaf_size': 31}. Best is trial 3 with value: 0.4382385383435925.
[I 2025-09-08 21:21:45,889] Trial 6 finished with value: 0.4346669265196539 and parameters: {'n_neighbors': 9, 'leaf_size': 26}. Best is trial 3 with value: 0.4382385383435925.
[I 2025-09-08 21:21:45,928] Trial 7 finished with value: 0.41954855189614654 and parameters: {'n_neighbors': 7, 'leaf_size': 36}. Best is trial 3 with value: 0.4382385383435925.

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 21:21:45,971] Trial 8 finished with value: 0.41954855189614654 and parameters: {'n_neighbors': 7, 'leaf_size': 20}. Best is trial 3 with value: 0.4382385383435925.
[I 2025-09-08 21:21:46,017] Trial 9 finished with value: 0.4184230159461915 and parameters: {'n_neighbors': 6, 'leaf_size': 29}. Best is trial 3 with value: 0.4382385383435925.
[I 2025-09-08 21:21:46,068] Trial 10 finished with value: 0.3487747644150773 and parameters: {'n_neighbors': 3, 'leaf_size': 10}. Best is trial 3 with value: 0.4382385383435925.
[I 2025-09-08 21:21:46,115] Trial 11 finished with value: 0.4382385383435925 and parameters: {'n_neighbors': 10, 'leaf_size': 40}. Best is trial 3 with value: 0.4382385383435925.

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:21:46,164] Trial 12 finished with value: 0.4382385383435925 and parameters: {'n_neighbors': 10, 'leaf_size': 40}. Best is trial 3 with value: 0.4382385383435925.
[I 2025-09-08 21:21:46,214] Trial 13 finished with value: 0.4346280233463406 and parameters: {'n_neighbors': 11, 'leaf_size': 21}. Best is trial 3 with value: 0.4382385383435925.
[I 2025-09-08 21:21:46,265] Trial 14 finished with value: 0.4382385383435925 and parameters: {'n_neighbors': 10, 'leaf_size': 24}. Best is trial 3 with value: 0.4382385383435925.
[I 2025-09-08 21:21:46,312] Trial 15 finished with value: 0.4070786247153537 and parameters: {'n_neighbors': 5, 'leaf_size': 39}. Best is trial 3 with value: 0.4382385383435925.
[I 2025-09-08 21:21:46,362] Trial 16 finished with value: 0.4382385383435925 and parameters: {'n_neighbors': 10, 'leaf_size': 16}. Best is trial 3 with value: 0.4382385383435925.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 21:21:46,411] Trial 17 finished with value: 0.4346280233463406 and parameters: {'n_neighbors': 11, 'leaf_size': 35}. Best is trial 3 with value: 0.4382385383435925.
[I 2025-09-08 21:21:46,466] Trial 18 finished with value: 0.4346669265196539 and parameters: {'n_neighbors': 9, 'leaf_size': 25}. Best is trial 3 with value: 0.4382385383435925.
[I 2025-09-08 21:21:46,519] Trial 19 finished with value: 0.4346280233463406 and parameters: {'n_neighbors': 11, 'leaf_size': 28}. Best is trial 3 with value: 0.4382385383435925.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 21:21:46,616] Trial 20 finished with value: 0.4352934636725663 and parameters: {'n_neighbors': 8, 'leaf_size': 17}. Best is trial 3 with value: 0.4382385383435925.
[I 2025-09-08 21:21:46,675] Trial 21 finished with value: 0.4382385383435925 and parameters: {'n_neighbors': 10, 'leaf_size': 40}. Best is trial 3 with value: 0.4382385383435925.
[I 2025-09-08 21:21:46,730] Trial 22 finished with value: 0.4382385383435925 and parameters: {'n_neighbors': 10, 'leaf_size': 36}. Best is trial 3 with value: 0.4382385383435925.
[I 2025-09-08 21:21:46,778] Trial 23 finished with value: 0.4346669265196539 and parameters: {'n_neighbors': 9, 'leaf_size': 38}. Best is trial 3 with value: 0.4382385383435925.

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 21:21:46,827] Trial 24 finished with value: 0.4316348124076225 and parameters: {'n_neighbors': 12, 'leaf_size': 34}. Best is trial 3 with value: 0.4382385383435925.
[I 2025-09-08 21:21:46,879] Trial 25 finished with value: 0.4346280233463406 and parameters: {'n_neighbors': 11, 'leaf_size': 40}. Best is trial 3 with value: 0.4382385383435925.
[I 2025-09-08 21:21:46,937] Trial 26 finished with value: 0.4352934636725663 and parameters: {'n_neighbors': 8, 'leaf_size': 22}. Best is trial 3 with value: 0.4382385383435925.
[I 2025-09-08 21:21:46,985] Trial 27 finished with value: 0.4382385383435925 and parameters: {'n_neighbors': 10, 'leaf_size': 37}. Best is trial 3 with value: 0.4382385383435925.

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 21:21:47,034] Trial 28 finished with value: 0.4070786247153537 and parameters: {'n_neighbors': 5, 'leaf_size': 33}. Best is trial 3 with value: 0.4382385383435925.
[I 2025-09-08 21:21:47,086] Trial 29 finished with value: 0.4346669265196539 and parameters: {'n_neighbors': 9, 'leaf_size': 28}. Best is trial 3 with value: 0.4382385383435925.
[I 2025-09-08 21:21:47,088] A new study created in memory with name: no-name-263947f4-2bb3-4349-98ce-6fd7e3a861c2
[I 2025-09-08 21:21:47,143] Trial 0 finished with value: 0.28027004992415133 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 0 with value: 0.28027004992415133.
[I 2025-09-08 21:21:47,196] Trial 1 finished with value: 0.2802700499286684 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 1 with value: 0.2802700499286684.

Fold 3
Fold 1
Fold 2
Fold 3

✅ KNN con C2X-Complex_rhown_5x5_depth_in_3_4 - Mejor R2: 0.44
📋 Parámetros: {'n_neighbors': 10, 'leaf_size': 23}

Buscando mejores hiperparámetros para LR con C2X-Complex_rhown_5x5_depth_in_3_4...
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 21:21:47,249] Trial 2 finished with value: 0.3134768744097976 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 2 with value: 0.3134768744097976.
[I 2025-09-08 21:21:47,318] Trial 3 finished with value: 0.2802700499286684 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 2 with value: 0.3134768744097976.
[I 2025-09-08 21:21:47,380] Trial 4 finished with value: 0.28027004992415133 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 2 with value: 0.3134768744097976.

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:21:47,441] Trial 5 finished with value: 0.3134768744097976 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 2 with value: 0.3134768744097976.
[I 2025-09-08 21:21:47,546] Trial 6 finished with value: 0.2802700499286684 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 2 with value: 0.3134768744097976.
[I 2025-09-08 21:21:47,630] Trial 7 finished with value: 0.28027004992415133 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 2 with value: 0.3134768744097976.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 21:21:47,690] Trial 8 finished with value: 0.2802700499286684 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 2 with value: 0.3134768744097976.
[I 2025-09-08 21:21:47,759] Trial 9 finished with value: 0.28027004992415133 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 2 with value: 0.3134768744097976.
[I 2025-09-08 21:21:47,823] Trial 10 finished with value: 0.3134768744097976 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 2 with value: 0.3134768744097976.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:21:47,870] Trial 11 finished with value: 0.3134768744097976 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 2 with value: 0.3134768744097976.
[I 2025-09-08 21:21:47,916] Trial 12 finished with value: 0.3134768744097976 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 2 with value: 0.3134768744097976.
[I 2025-09-08 21:21:47,962] Trial 13 finished with value: 0.3134768744097976 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 2 with value: 0.3134768744097976.
[I 2025-09-08 21:21:48,003] Trial 14 finished with value: 0.3134768744097976 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 2 with value: 0.3134768744097976.
[I 2025-09-08 21:21:48,043] Trial 15 finished with value: 0.3134768744097976 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 2 with value: 0.3134768744097976.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:21:48,084] Trial 16 finished with value: 0.3134768744097976 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 2 with value: 0.3134768744097976.
[I 2025-09-08 21:21:48,129] Trial 17 finished with value: 0.3134768744097976 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 2 with value: 0.3134768744097976.
[I 2025-09-08 21:21:48,170] Trial 18 finished with value: 0.3136415581997169 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 18 with value: 0.3136415581997169.
[I 2025-09-08 21:21:48,209] Trial 19 finished with value: 0.3136415581997169 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 18 with value: 0.3136415581997169.
[I 2025-09-08 21:21:48,248] Trial 20 finished with value: 0.3136415581997169 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 18 with value: 0.3136415581997169.
[I 2025-09-08 21:21:48,289] Trial 21 finished with value: 0.3136415581997169 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 18 with value: 0.3136415581997169.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:21:48,329] Trial 22 finished with value: 0.3136415581997169 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 18 with value: 0.3136415581997169.
[I 2025-09-08 21:21:48,374] Trial 23 finished with value: 0.3136415581997169 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 18 with value: 0.3136415581997169.
[I 2025-09-08 21:21:48,434] Trial 24 finished with value: 0.3136415581997169 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 18 with value: 0.3136415581997169.
[I 2025-09-08 21:21:48,488] Trial 25 finished with value: 0.3136415581997169 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 18 with value: 0.3136415581997169.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 21:21:48,533] Trial 26 finished with value: 0.3136415581997169 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 18 with value: 0.3136415581997169.
[I 2025-09-08 21:21:48,579] Trial 27 finished with value: 0.3136415581997169 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 18 with value: 0.3136415581997169.
[I 2025-09-08 21:21:48,624] Trial 28 finished with value: 0.3136415581997169 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 18 with value: 0.3136415581997169.
[I 2025-09-08 21:21:48,662] Trial 29 finished with value: 0.3136415581997169 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 18 with value: 0.3136415581997169.
[I 2025-09-08 21:21:48,664] A new study created in memory with name: no-name-263a614f-6911-4dda-af03-5369b1b25169

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

✅ LR con C2X-Complex_rhown_5x5_depth_in_3_4 - Mejor R2: 0.31
📋 Parámetros: {'fit_intercept': True, 'positive': True}

Buscando mejores hiperparámetros para RF con C2X-Complex_rhown_5x5_depth_in_3_4...
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:21:50,334] Trial 0 finished with value: 0.4454617006657921 and parameters: {'n_estimators': 200, 'max_depth': 9, 'min_samples_split': 2, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 0 with value: 0.4454617006657921.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:21:52,234] Trial 1 finished with value: 0.4485843690489626 and parameters: {'n_estimators': 200, 'max_depth': 11, 'min_samples_split': 5, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 1 with value: 0.4485843690489626.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:21:56,764] Trial 2 finished with value: 0.2871098908910265 and parameters: {'n_estimators': 400, 'max_depth': 6, 'min_samples_split': 6, 'min_samples_leaf': 6, 'bootstrap': False}. Best is trial 1 with value: 0.4485843690489626.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:22:00,070] Trial 3 finished with value: 0.4476976563019462 and parameters: {'n_estimators': 400, 'max_depth': 6, 'min_samples_split': 8, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 1 with value: 0.4485843690489626.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:22:02,921] Trial 4 finished with value: 0.11607138220108133 and parameters: {'n_estimators': 200, 'max_depth': 9, 'min_samples_split': 3, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 1 with value: 0.4485843690489626.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:22:05,155] Trial 5 finished with value: 0.08831006725177688 and parameters: {'n_estimators': 200, 'max_depth': 5, 'min_samples_split': 4, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 1 with value: 0.4485843690489626.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:22:08,357] Trial 6 finished with value: 0.4358763062391356 and parameters: {'n_estimators': 400, 'max_depth': 11, 'min_samples_split': 3, 'min_samples_leaf': 6, 'bootstrap': True}. Best is trial 1 with value: 0.4485843690489626.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:22:09,513] Trial 7 finished with value: 0.2879142584075289 and parameters: {'n_estimators': 100, 'max_depth': 8, 'min_samples_split': 6, 'min_samples_leaf': 8, 'bootstrap': False}. Best is trial 1 with value: 0.4485843690489626.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:22:10,961] Trial 8 finished with value: 0.43847098185628347 and parameters: {'n_estimators': 200, 'max_depth': 5, 'min_samples_split': 6, 'min_samples_leaf': 7, 'bootstrap': True}. Best is trial 1 with value: 0.4485843690489626.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:22:11,958] Trial 9 finished with value: 0.4379229286456677 and parameters: {'n_estimators': 100, 'max_depth': 11, 'min_samples_split': 8, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 1 with value: 0.4485843690489626.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:22:13,763] Trial 10 finished with value: 0.4531513425475371 and parameters: {'n_estimators': 200, 'max_depth': 12, 'min_samples_split': 5, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 10 with value: 0.4531513425475371.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:22:15,540] Trial 11 finished with value: 0.4531513425475371 and parameters: {'n_estimators': 200, 'max_depth': 12, 'min_samples_split': 5, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 10 with value: 0.4531513425475371.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:22:17,322] Trial 12 finished with value: 0.4531513425475371 and parameters: {'n_estimators': 200, 'max_depth': 12, 'min_samples_split': 5, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 10 with value: 0.4531513425475371.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:22:19,099] Trial 13 finished with value: 0.4531513425475371 and parameters: {'n_estimators': 200, 'max_depth': 12, 'min_samples_split': 4, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 10 with value: 0.4531513425475371.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:22:20,814] Trial 14 finished with value: 0.4449718278910559 and parameters: {'n_estimators': 200, 'max_depth': 10, 'min_samples_split': 7, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 10 with value: 0.4531513425475371.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:22:21,809] Trial 15 finished with value: 0.44866838712461893 and parameters: {'n_estimators': 100, 'max_depth': 12, 'min_samples_split': 4, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 10 with value: 0.4531513425475371.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:22:23,413] Trial 16 finished with value: 0.4393590987763362 and parameters: {'n_estimators': 200, 'max_depth': 10, 'min_samples_split': 5, 'min_samples_leaf': 6, 'bootstrap': True}. Best is trial 10 with value: 0.4531513425475371.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:22:25,199] Trial 17 finished with value: 0.4533320255789275 and parameters: {'n_estimators': 200, 'max_depth': 8, 'min_samples_split': 7, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 17 with value: 0.4533320255789275.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:22:30,207] Trial 18 finished with value: 0.27873291222541285 and parameters: {'n_estimators': 400, 'max_depth': 8, 'min_samples_split': 7, 'min_samples_leaf': 5, 'bootstrap': False}. Best is trial 17 with value: 0.4533320255789275.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:22:31,141] Trial 19 finished with value: 0.4539407512864469 and parameters: {'n_estimators': 100, 'max_depth': 7, 'min_samples_split': 8, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 19 with value: 0.4539407512864469.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:22:32,091] Trial 20 finished with value: 0.4383161246021154 and parameters: {'n_estimators': 100, 'max_depth': 7, 'min_samples_split': 7, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 19 with value: 0.4539407512864469.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:22:33,007] Trial 21 finished with value: 0.4539407512864469 and parameters: {'n_estimators': 100, 'max_depth': 7, 'min_samples_split': 8, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 19 with value: 0.4539407512864469.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:22:33,943] Trial 22 finished with value: 0.4539407512864469 and parameters: {'n_estimators': 100, 'max_depth': 7, 'min_samples_split': 8, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 19 with value: 0.4539407512864469.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:22:34,856] Trial 23 finished with value: 0.4539407512864469 and parameters: {'n_estimators': 100, 'max_depth': 7, 'min_samples_split': 8, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 19 with value: 0.4539407512864469.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:22:35,763] Trial 24 finished with value: 0.4539407512864469 and parameters: {'n_estimators': 100, 'max_depth': 7, 'min_samples_split': 8, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 19 with value: 0.4539407512864469.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:22:36,668] Trial 25 finished with value: 0.4416996413527083 and parameters: {'n_estimators': 100, 'max_depth': 6, 'min_samples_split': 8, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 19 with value: 0.4539407512864469.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:22:37,989] Trial 26 finished with value: 0.1252923033820794 and parameters: {'n_estimators': 100, 'max_depth': 7, 'min_samples_split': 7, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 19 with value: 0.4539407512864469.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:22:38,875] Trial 27 finished with value: 0.4416996413527083 and parameters: {'n_estimators': 100, 'max_depth': 6, 'min_samples_split': 8, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 19 with value: 0.4539407512864469.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:22:39,842] Trial 28 finished with value: 0.44703204144233255 and parameters: {'n_estimators': 100, 'max_depth': 8, 'min_samples_split': 6, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 19 with value: 0.4539407512864469.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:22:40,731] Trial 29 finished with value: 0.4417757033663496 and parameters: {'n_estimators': 100, 'max_depth': 9, 'min_samples_split': 7, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 19 with value: 0.4539407512864469.
[I 2025-09-08 21:22:40,733] A new study created in memory with name: no-name-39229302-6370-4a03-86d4-72abd401747d

✅ RF con C2X-Complex_rhown_5x5_depth_in_3_4 - Mejor R2: 0.45
📋 Parámetros: {'n_estimators': 100, 'max_depth': 7, 'min_samples_split': 8, 'min_samples_leaf': 3, 'bootstrap': True}

Buscando mejores hiperparámetros para CAT con C2X-Complex_rhown_5x5_depth_in_3_4...
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:22:45,409] Trial 0 finished with value: 0.374159887430684 and parameters: {'iterations': 1000, 'learning_rate': 0.03, 'depth': 6, 'l2_leaf_reg': 4.991355755473656}. Best is trial 0 with value: 0.374159887430684.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:22:47,784] Trial 1 finished with value: 0.3908109924623437 and parameters: {'iterations': 500, 'learning_rate': 0.03, 'depth': 6, 'l2_leaf_reg': 3.272894562460989}. Best is trial 1 with value: 0.3908109924623437.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:22:49,400] Trial 2 finished with value: 0.3371391908466954 and parameters: {'iterations': 750, 'learning_rate': 0.02, 'depth': 4, 'l2_leaf_reg': 4.97202101342975}. Best is trial 1 with value: 0.3908109924623437.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:23:08,216] Trial 3 finished with value: 0.37942493134578176 and parameters: {'iterations': 750, 'learning_rate': 0.02, 'depth': 8, 'l2_leaf_reg': 1.8543960041529122}. Best is trial 1 with value: 0.3908109924623437.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:23:09,225] Trial 4 finished with value: 0.3100786224641355 and parameters: {'iterations': 500, 'learning_rate': 0.04, 'depth': 4, 'l2_leaf_reg': 3.326878784487258}. Best is trial 1 with value: 0.3908109924623437.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:23:21,546] Trial 5 finished with value: 0.41152318083705564 and parameters: {'iterations': 500, 'learning_rate': 0.02, 'depth': 8, 'l2_leaf_reg': 2.6656040691571183}. Best is trial 5 with value: 0.41152318083705564.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:23:40,167] Trial 6 finished with value: 0.3769249951254842 and parameters: {'iterations': 750, 'learning_rate': 0.05, 'depth': 8, 'l2_leaf_reg': 4.962148417259967}. Best is trial 5 with value: 0.41152318083705564.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:23:45,211] Trial 7 finished with value: 0.3866155161743028 and parameters: {'iterations': 500, 'learning_rate': 0.03, 'depth': 7, 'l2_leaf_reg': 3.166172600545722}. Best is trial 5 with value: 0.41152318083705564.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:23:49,680] Trial 8 finished with value: 0.38016036700750605 and parameters: {'iterations': 1000, 'learning_rate': 0.02, 'depth': 6, 'l2_leaf_reg': 1.294157233962399}. Best is trial 5 with value: 0.41152318083705564.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:23:51,861] Trial 9 finished with value: 0.33244803522184546 and parameters: {'iterations': 750, 'learning_rate': 0.04, 'depth': 5, 'l2_leaf_reg': 3.744326806070546}. Best is trial 5 with value: 0.41152318083705564.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:23:56,962] Trial 10 finished with value: 0.3537967950620668 and parameters: {'iterations': 500, 'learning_rate': 0.05, 'depth': 7, 'l2_leaf_reg': 2.4025259387692697}. Best is trial 5 with value: 0.41152318083705564.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:24:01,844] Trial 11 finished with value: 0.3749511915211108 and parameters: {'iterations': 500, 'learning_rate': 0.03, 'depth': 7, 'l2_leaf_reg': 2.584085587078868}. Best is trial 5 with value: 0.41152318083705564.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:24:03,415] Trial 12 finished with value: 0.36002461727732765 and parameters: {'iterations': 500, 'learning_rate': 0.03, 'depth': 5, 'l2_leaf_reg': 3.939586560620758}. Best is trial 5 with value: 0.41152318083705564.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:24:04,963] Trial 13 finished with value: 0.33520579230927244 and parameters: {'iterations': 500, 'learning_rate': 0.02, 'depth': 5, 'l2_leaf_reg': 2.4124515744344355}. Best is trial 5 with value: 0.41152318083705564.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:24:09,953] Trial 14 finished with value: 0.4216350340377757 and parameters: {'iterations': 500, 'learning_rate': 0.02, 'depth': 7, 'l2_leaf_reg': 4.051822705140918}. Best is trial 14 with value: 0.4216350340377757.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:24:21,992] Trial 15 finished with value: 0.4364959964521164 and parameters: {'iterations': 500, 'learning_rate': 0.02, 'depth': 8, 'l2_leaf_reg': 4.201416204739036}. Best is trial 15 with value: 0.4364959964521164.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:24:31,738] Trial 16 finished with value: 0.3967640534966998 and parameters: {'iterations': 1000, 'learning_rate': 0.02, 'depth': 7, 'l2_leaf_reg': 4.312852882009317}. Best is trial 15 with value: 0.4364959964521164.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:24:43,601] Trial 17 finished with value: 0.4413740316617929 and parameters: {'iterations': 500, 'learning_rate': 0.02, 'depth': 8, 'l2_leaf_reg': 4.321335658821983}. Best is trial 17 with value: 0.4413740316617929.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:24:55,419] Trial 18 finished with value: 0.4318508048983161 and parameters: {'iterations': 500, 'learning_rate': 0.02, 'depth': 8, 'l2_leaf_reg': 4.446031842614889}. Best is trial 17 with value: 0.4413740316617929.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:25:19,949] Trial 19 finished with value: 0.3894473955764976 and parameters: {'iterations': 1000, 'learning_rate': 0.05, 'depth': 8, 'l2_leaf_reg': 4.593571629693583}. Best is trial 17 with value: 0.4413740316617929.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:25:32,334] Trial 20 finished with value: 0.40155400920427126 and parameters: {'iterations': 500, 'learning_rate': 0.04, 'depth': 8, 'l2_leaf_reg': 3.616222177475855}. Best is trial 17 with value: 0.4413740316617929.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:25:44,308] Trial 21 finished with value: 0.42247353100863155 and parameters: {'iterations': 500, 'learning_rate': 0.02, 'depth': 8, 'l2_leaf_reg': 4.4392620173232595}. Best is trial 17 with value: 0.4413740316617929.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:25:56,323] Trial 22 finished with value: 0.43322024713055046 and parameters: {'iterations': 500, 'learning_rate': 0.02, 'depth': 8, 'l2_leaf_reg': 4.203279482808967}. Best is trial 17 with value: 0.4413740316617929.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:26:01,207] Trial 23 finished with value: 0.42549121029358944 and parameters: {'iterations': 500, 'learning_rate': 0.02, 'depth': 7, 'l2_leaf_reg': 4.15522909140698}. Best is trial 17 with value: 0.4413740316617929.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:26:13,238] Trial 24 finished with value: 0.4176804196748571 and parameters: {'iterations': 500, 'learning_rate': 0.02, 'depth': 8, 'l2_leaf_reg': 3.6360179744668204}. Best is trial 17 with value: 0.4413740316617929.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:26:18,030] Trial 25 finished with value: 0.427056100758705 and parameters: {'iterations': 500, 'learning_rate': 0.02, 'depth': 7, 'l2_leaf_reg': 4.688228035612014}. Best is trial 17 with value: 0.4413740316617929.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:26:30,048] Trial 26 finished with value: 0.42886049466668186 and parameters: {'iterations': 500, 'learning_rate': 0.02, 'depth': 8, 'l2_leaf_reg': 3.813016460403477}. Best is trial 17 with value: 0.4413740316617929.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:26:32,252] Trial 27 finished with value: 0.42807753775720103 and parameters: {'iterations': 500, 'learning_rate': 0.02, 'depth': 6, 'l2_leaf_reg': 4.147487844628618}. Best is trial 17 with value: 0.4413740316617929.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:26:50,745] Trial 28 finished with value: 0.39660655866994016 and parameters: {'iterations': 750, 'learning_rate': 0.04, 'depth': 8, 'l2_leaf_reg': 4.665996681398902}. Best is trial 17 with value: 0.4413740316617929.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:26:55,420] Trial 29 finished with value: 0.3599723659647924 and parameters: {'iterations': 1000, 'learning_rate': 0.05, 'depth': 6, 'l2_leaf_reg': 3.512678201957417}. Best is trial 17 with value: 0.4413740316617929.
[I 2025-09-08 21:26:55,421] A new study created in memory with name: no-name-9ac01884-921d-4361-bca1-c241e72168de
[I 2025-09-08 21:26:55,476] Trial 0 finished with value: 0.3346501776059411 and parameters: {'alpha': 0.11898620703465713, 'l1_ratio': 0.7431707506731803}. Best is trial 0 with value: 0.3346501776059411.
[I 2025-09-08 21:26:55,564] Trial 1 finished with value: 0.3307606210356004 and parameters: {'alpha': 0.13115926782311133, 'l1_ratio': 0.8024811635195099}. Best is trial 0 with value: 0.3346501776059411.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.245e-02, tolerance: 4.223e-02
  model = cd_fast.enet_coordinate_descent(

✅ CAT con C2X-Complex_rhown_5x5_depth_in_3_4 - Mejor R2: 0.44
📋 Parámetros: {'iterations': 500, 'learning_rate': 0.02, 'depth': 8, 'l2_leaf_reg': 4.321335658821983}

Buscando mejores hiperparámetros para ELN con C2X-Complex_rhown_5x5_depth_in_3_4...
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:26:55,634] Trial 2 finished with value: 0.39131020602069394 and parameters: {'alpha': 0.008623704927370716, 'l1_ratio': 0.8226224411813655}. Best is trial 2 with value: 0.39131020602069394.
[I 2025-09-08 21:26:55,719] Trial 3 finished with value: 0.24455170801643808 and parameters: {'alpha': 0.9475389851395267, 'l1_ratio': 0.37364101326327004}. Best is trial 2 with value: 0.39131020602069394.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.097e+00, tolerance: 4.779e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.048e+01, tolerance: 4.223e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.044e+00, tolerance: 3.136e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:26:55,832] Trial 4 finished with value: 0.3818390494325725 and parameters: {'alpha': 0.0008462264605484229, 'l1_ratio': 0.8826920405537677}. Best is trial 2 with value: 0.39131020602069394.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.939e+01, tolerance: 4.779e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.715e+01, tolerance: 4.223e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.808e+01, tolerance: 3.136e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:26:55,947] Trial 5 finished with value: 0.3729565301086584 and parameters: {'alpha': 0.00014422011616520048, 'l1_ratio': 0.5827328890277165}. Best is trial 2 with value: 0.39131020602069394.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.408e+01, tolerance: 4.779e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.034e+01, tolerance: 4.223e-02
  model = cd_fast.enet_coordinate_descent(

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.760e+01, tolerance: 3.136e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:26:56,095] Trial 6 finished with value: 0.38269600966883494 and parameters: {'alpha': 0.001129450296239876, 'l1_ratio': 0.16130249859185436}. Best is trial 2 with value: 0.39131020602069394.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.197e+01, tolerance: 4.779e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.953e+01, tolerance: 4.223e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.206e+01, tolerance: 3.136e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:26:56,247] Trial 7 finished with value: 0.3855430953595087 and parameters: {'alpha': 0.0018459137280047052, 'l1_ratio': 0.20317574045228623}. Best is trial 2 with value: 0.39131020602069394.
[I 2025-09-08 21:26:56,303] Trial 8 finished with value: 0.32216449688293475 and parameters: {'alpha': 0.3011412468446515, 'l1_ratio': 0.5007118638265586}. Best is trial 2 with value: 0.39131020602069394.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.733e+01, tolerance: 4.779e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.077e+01, tolerance: 4.223e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.358e+01, tolerance: 3.136e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:26:56,401] Trial 9 finished with value: 0.37697616859464206 and parameters: {'alpha': 0.00040534289094907233, 'l1_ratio': 0.5205622042089052}. Best is trial 2 with value: 0.39131020602069394.
[I 2025-09-08 21:26:56,484] Trial 10 finished with value: 0.3901109528853068 and parameters: {'alpha': 0.010287037927079683, 'l1_ratio': 0.6757373270289914}. Best is trial 2 with value: 0.39131020602069394.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 21:26:56,560] Trial 11 finished with value: 0.3839125672418587 and parameters: {'alpha': 0.016237625357233425, 'l1_ratio': 0.6813222116827875}. Best is trial 2 with value: 0.39131020602069394.
[I 2025-09-08 21:26:56,636] Trial 12 finished with value: 0.38753411831138146 and parameters: {'alpha': 0.012061847814974507, 'l1_ratio': 0.6866722098310014}. Best is trial 2 with value: 0.39131020602069394.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.076e-01, tolerance: 4.223e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.066e-02, tolerance: 3.136e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:26:56,744] Trial 13 finished with value: 0.39532022846644316 and parameters: {'alpha': 0.006246719678179008, 'l1_ratio': 0.8775636082563202}. Best is trial 13 with value: 0.39532022846644316.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.319e-02, tolerance: 4.779e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.494e-01, tolerance: 4.223e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.493e-01, tolerance: 3.136e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:26:56,882] Trial 14 finished with value: 0.3978383833439077 and parameters: {'alpha': 0.0036384222644170066, 'l1_ratio': 0.8916741518672807}. Best is trial 14 with value: 0.3978383833439077.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.125e-02, tolerance: 4.779e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.680e-01, tolerance: 4.223e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.284e-01, tolerance: 3.136e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:26:56,998] Trial 15 finished with value: 0.3977322701918425 and parameters: {'alpha': 0.003569322639840338, 'l1_ratio': 0.8791939121945329}. Best is trial 14 with value: 0.3978383833439077.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.086e+01, tolerance: 4.779e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.965e+00, tolerance: 4.223e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.792e+00, tolerance: 3.136e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:26:57,093] Trial 16 finished with value: 0.39087619173298993 and parameters: {'alpha': 0.0032142286470085353, 'l1_ratio': 0.37536956668194865}. Best is trial 14 with value: 0.3978383833439077.
[I 2025-09-08 21:26:57,172] Trial 17 finished with value: 0.364292056524598 and parameters: {'alpha': 0.033795637960635484, 'l1_ratio': 0.7833011113638129}. Best is trial 14 with value: 0.3978383833439077.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.557e+01, tolerance: 4.779e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.209e+01, tolerance: 4.223e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.124e+01, tolerance: 3.136e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:26:57,260] Trial 18 finished with value: 0.37659987711523996 and parameters: {'alpha': 0.000382647258365819, 'l1_ratio': 0.8977641145238792}. Best is trial 14 with value: 0.3978383833439077.
[I 2025-09-08 21:26:57,338] Trial 19 finished with value: 0.3531352440797562 and parameters: {'alpha': 0.05169814496813426, 'l1_ratio': 0.5930061902613263}. Best is trial 14 with value: 0.3978383833439077.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.151e+01, tolerance: 4.779e-02
  model = cd_fast.enet_coordinate_descent(

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.823e+00, tolerance: 4.223e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.688e+00, tolerance: 3.136e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:26:57,460] Trial 20 finished with value: 0.3908535412272857 and parameters: {'alpha': 0.0030995223716160612, 'l1_ratio': 0.3865450123523465}. Best is trial 14 with value: 0.3978383833439077.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.247e-02, tolerance: 4.779e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.475e-01, tolerance: 4.223e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.542e-01, tolerance: 3.136e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:26:57,613] Trial 21 finished with value: 0.3978776747905419 and parameters: {'alpha': 0.0036337700258973885, 'l1_ratio': 0.8962670389431517}. Best is trial 21 with value: 0.3978776747905419.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.956e-01, tolerance: 4.779e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.170e-01, tolerance: 4.223e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.956e-01, tolerance: 3.136e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:26:57,718] Trial 22 finished with value: 0.39647512432574716 and parameters: {'alpha': 0.0033469590974780825, 'l1_ratio': 0.7457384788343385}. Best is trial 21 with value: 0.3978776747905419.
[I 2025-09-08 21:26:57,790] Trial 23 finished with value: 0.37074000310064276 and parameters: {'alpha': 0.02695028444586601, 'l1_ratio': 0.8364241336700018}. Best is trial 21 with value: 0.3978776747905419.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.352e+01, tolerance: 4.779e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.582e+01, tolerance: 4.223e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.086e+01, tolerance: 3.136e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:26:57,883] Trial 24 finished with value: 0.38079723159414725 and parameters: {'alpha': 0.0006948837368184419, 'l1_ratio': 0.7455584702158387}. Best is trial 21 with value: 0.3978776747905419.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.188e-02, tolerance: 4.779e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.964e-01, tolerance: 4.223e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.935e-02, tolerance: 3.136e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:26:57,962] Trial 25 finished with value: 0.39705183669747424 and parameters: {'alpha': 0.004858266049643477, 'l1_ratio': 0.8441426010426516}. Best is trial 21 with value: 0.3978776747905419.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.096e+01, tolerance: 4.779e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.260e+01, tolerance: 4.223e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.530e+01, tolerance: 3.136e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:26:58,055] Trial 26 finished with value: 0.3856326046887066 and parameters: {'alpha': 0.001503729352387855, 'l1_ratio': 0.2921622237362584}. Best is trial 21 with value: 0.3978776747905419.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.020e+02, tolerance: 4.779e-02
  model = cd_fast.enet_coordinate_descent(

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.921e+01, tolerance: 4.223e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.209e+01, tolerance: 3.136e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:26:58,153] Trial 27 finished with value: 0.37254458099530696 and parameters: {'alpha': 0.00011790070967743145, 'l1_ratio': 0.6053719444928614}. Best is trial 21 with value: 0.3978776747905419.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.677e+00, tolerance: 4.779e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.481e+00, tolerance: 4.223e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.169e+00, tolerance: 3.136e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:26:58,247] Trial 28 finished with value: 0.39395705945586573 and parameters: {'alpha': 0.0020729986063589847, 'l1_ratio': 0.8973033345506061}. Best is trial 21 with value: 0.3978776747905419.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.802e+01, tolerance: 4.779e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.375e+01, tolerance: 4.223e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.342e+01, tolerance: 3.136e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:26:58,342] Trial 29 finished with value: 0.37544806033741374 and parameters: {'alpha': 0.0003103388095293661, 'l1_ratio': 0.7586004331469653}. Best is trial 21 with value: 0.3978776747905419.
[I 2025-09-08 21:26:58,344] A new study created in memory with name: no-name-71f7fcbf-ac04-4489-bbe0-265e016f975c

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

✅ ELN con C2X-Complex_rhown_5x5_depth_in_3_4 - Mejor R2: 0.40
📋 Parámetros: {'alpha': 0.0036337700258973885, 'l1_ratio': 0.8962670389431517}

Buscando mejores hiperparámetros para XGB con C2X-Complex_rhow_9x9_depth_in_3_4...
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:27:04,593] Trial 0 finished with value: 0.3647575972225723 and parameters: {'n_estimators': 1250, 'learning_rate': 0.01, 'max_depth': 8, 'min_child_weight': 3, 'subsample': 0.6098349447525068, 'colsample_bytree': 0.6218086300133492}. Best is trial 0 with value: 0.3647575972225723.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:27:11,134] Trial 1 finished with value: 0.3782159868039631 and parameters: {'n_estimators': 1250, 'learning_rate': 0.01, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.7904734189735461, 'colsample_bytree': 0.6339057824611566}. Best is trial 1 with value: 0.3782159868039631.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:27:16,775] Trial 2 finished with value: 0.3814069785983705 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.6688227684864544, 'colsample_bytree': 0.6834938700917916}. Best is trial 2 with value: 0.3814069785983705.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:27:20,668] Trial 3 finished with value: 0.3675207885063221 and parameters: {'n_estimators': 750, 'learning_rate': 0.02, 'max_depth': 8, 'min_child_weight': 3, 'subsample': 0.6277507080501427, 'colsample_bytree': 0.6252563739354419}. Best is trial 2 with value: 0.3814069785983705.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:27:25,189] Trial 4 finished with value: 0.3622948053984765 and parameters: {'n_estimators': 1250, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.6895203276481063, 'colsample_bytree': 0.7113020752030009}. Best is trial 2 with value: 0.3814069785983705.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:27:28,495] Trial 5 finished with value: 0.39227998990400126 and parameters: {'n_estimators': 750, 'learning_rate': 0.01, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.6160409096022628, 'colsample_bytree': 0.7511474385210647}. Best is trial 5 with value: 0.39227998990400126.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:27:34,163] Trial 6 finished with value: 0.325497811586218 and parameters: {'n_estimators': 1250, 'learning_rate': 0.03, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.6614059914321289, 'colsample_bytree': 0.6496099023158537}. Best is trial 5 with value: 0.39227998990400126.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:27:37,466] Trial 7 finished with value: 0.38445486533548623 and parameters: {'n_estimators': 750, 'learning_rate': 0.02, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.6537740017304658, 'colsample_bytree': 0.7980239801997121}. Best is trial 5 with value: 0.39227998990400126.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:27:40,843] Trial 8 finished with value: 0.3930847859010201 and parameters: {'n_estimators': 750, 'learning_rate': 0.02, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.7976056226752914, 'colsample_bytree': 0.6491029623668473}. Best is trial 8 with value: 0.3930847859010201.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:27:44,461] Trial 9 finished with value: 0.3565036088387786 and parameters: {'n_estimators': 750, 'learning_rate': 0.02, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.7098737476330443, 'colsample_bytree': 0.7050656681485452}. Best is trial 8 with value: 0.3930847859010201.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:27:48,810] Trial 10 finished with value: 0.3777972776373919 and parameters: {'n_estimators': 1000, 'learning_rate': 0.03, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.7995927047738431, 'colsample_bytree': 0.6003300330815392}. Best is trial 8 with value: 0.3930847859010201.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:27:53,324] Trial 11 finished with value: 0.3784981445550449 and parameters: {'n_estimators': 750, 'learning_rate': 0.02, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.7393193652356735, 'colsample_bytree': 0.7669140086269438}. Best is trial 8 with value: 0.3930847859010201.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:27:56,276] Trial 12 finished with value: 0.3731308626888035 and parameters: {'n_estimators': 750, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.7515807958600299, 'colsample_bytree': 0.744454296877603}. Best is trial 8 with value: 0.3930847859010201.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:28:00,417] Trial 13 finished with value: 0.385794243498832 and parameters: {'n_estimators': 750, 'learning_rate': 0.02, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.7579850293446975, 'colsample_bytree': 0.6683816014596929}. Best is trial 8 with value: 0.3930847859010201.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:28:04,635] Trial 14 finished with value: 0.34076015853097125 and parameters: {'n_estimators': 750, 'learning_rate': 0.03, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.7154498672429918, 'colsample_bytree': 0.7351649634413687}. Best is trial 8 with value: 0.3930847859010201.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:28:08,267] Trial 15 finished with value: 0.4015387611647993 and parameters: {'n_estimators': 750, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.6305649504490933, 'colsample_bytree': 0.7803072001724782}. Best is trial 15 with value: 0.4015387611647993.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:28:12,725] Trial 16 finished with value: 0.36599191608782444 and parameters: {'n_estimators': 1000, 'learning_rate': 0.02, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.6367684886202697, 'colsample_bytree': 0.7938830717682479}. Best is trial 15 with value: 0.4015387611647993.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:28:16,164] Trial 17 finished with value: 0.4062762786627381 and parameters: {'n_estimators': 750, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.6879255351403103, 'colsample_bytree': 0.6759766195040465}. Best is trial 17 with value: 0.4062762786627381.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:28:19,693] Trial 18 finished with value: 0.4087373470452156 and parameters: {'n_estimators': 750, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.685407635161434, 'colsample_bytree': 0.7185930219360637}. Best is trial 18 with value: 0.4087373470452156.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:28:25,189] Trial 19 finished with value: 0.38932502336187697 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.6797230240698438, 'colsample_bytree': 0.726676878509604}. Best is trial 18 with value: 0.4087373470452156.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:28:28,808] Trial 20 finished with value: 0.3916550957835521 and parameters: {'n_estimators': 750, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.7255407589561671, 'colsample_bytree': 0.6878969696410491}. Best is trial 18 with value: 0.4087373470452156.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:28:32,480] Trial 21 finished with value: 0.39621078064051635 and parameters: {'n_estimators': 750, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.644888128794014, 'colsample_bytree': 0.7743693194552397}. Best is trial 18 with value: 0.4087373470452156.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:28:36,016] Trial 22 finished with value: 0.403332531139573 and parameters: {'n_estimators': 750, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.6932769643321028, 'colsample_bytree': 0.671228333607063}. Best is trial 18 with value: 0.4087373470452156.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:28:39,436] Trial 23 finished with value: 0.4110507732047723 and parameters: {'n_estimators': 750, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.6962491772863236, 'colsample_bytree': 0.6752889414503019}. Best is trial 23 with value: 0.4110507732047723.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:28:44,160] Trial 24 finished with value: 0.4054630936421823 and parameters: {'n_estimators': 750, 'learning_rate': 0.01, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.678605964360315, 'colsample_bytree': 0.7172999715697654}. Best is trial 23 with value: 0.4110507732047723.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:28:47,728] Trial 25 finished with value: 0.3998882679980331 and parameters: {'n_estimators': 750, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.7046209403430554, 'colsample_bytree': 0.6877589204145947}. Best is trial 23 with value: 0.4110507732047723.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:28:51,579] Trial 26 finished with value: 0.361438465967921 and parameters: {'n_estimators': 750, 'learning_rate': 0.03, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.7263874952226489, 'colsample_bytree': 0.6604645450838215}. Best is trial 23 with value: 0.4110507732047723.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:28:55,072] Trial 27 finished with value: 0.4097562941947703 and parameters: {'n_estimators': 750, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.6823508432391012, 'colsample_bytree': 0.698163125567496}. Best is trial 23 with value: 0.4110507732047723.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:29:01,208] Trial 28 finished with value: 0.3879454110764093 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.6709731250773973, 'colsample_bytree': 0.6974423909599532}. Best is trial 23 with value: 0.4110507732047723.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:29:09,859] Trial 29 finished with value: 0.3700659401631645 and parameters: {'n_estimators': 1250, 'learning_rate': 0.01, 'max_depth': 8, 'min_child_weight': 2, 'subsample': 0.6532191173626087, 'colsample_bytree': 0.7188047885970469}. Best is trial 23 with value: 0.4110507732047723.
[I 2025-09-08 21:29:09,861] A new study created in memory with name: no-name-477ffe53-56f3-4309-8b46-a1e6eab2a978
[I 2025-09-08 21:29:09,994] Trial 0 finished with value: 0.41148061220312665 and parameters: {'learning_rate': 0.03, 'num_leaves': 10, 'max_depth': 8, 'min_child_samples': 5, 'subsample': 0.7761961293034247, 'colsample_bytree': 0.6021224275026358, 'n_estimators': 1000, 'min_split_gain': 1.0}. Best is trial 0 with value: 0.41148061220312665.

✅ XGB con C2X-Complex_rhow_9x9_depth_in_3_4 - Mejor R2: 0.41
📋 Parámetros: {'n_estimators': 750, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.6962491772863236, 'colsample_bytree': 0.6752889414503019}

Buscando mejores hiperparámetros para LBM con C2X-Complex_rhow_9x9_depth_in_3_4...
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 21:29:10,149] Trial 1 finished with value: 0.3913998644093512 and parameters: {'learning_rate': 0.02, 'num_leaves': 30, 'max_depth': 6, 'min_child_samples': 7, 'subsample': 0.6093806779849633, 'colsample_bytree': 0.7721810562898944, 'n_estimators': 750, 'min_split_gain': 1.0}. Best is trial 0 with value: 0.41148061220312665.

Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:29:10,324] Trial 2 finished with value: 0.3923865649133944 and parameters: {'learning_rate': 0.02, 'num_leaves': 10, 'max_depth': 6, 'min_child_samples': 6, 'subsample': 0.7531209616954075, 'colsample_bytree': 0.6050873053058204, 'n_estimators': 750, 'min_split_gain': 0.5}. Best is trial 0 with value: 0.41148061220312665.

Fold 1
Fold 2

[I 2025-09-08 21:29:10,815] Trial 3 finished with value: 0.30252073452305667 and parameters: {'learning_rate': 0.03, 'num_leaves': 30, 'max_depth': 6, 'min_child_samples': 8, 'subsample': 0.7072578314056389, 'colsample_bytree': 0.7345504162967423, 'n_estimators': 1250, 'min_split_gain': 0.0}. Best is trial 0 with value: 0.41148061220312665.

Fold 3
Fold 1

[I 2025-09-08 21:29:10,968] Trial 4 finished with value: 0.33407805523897327 and parameters: {'learning_rate': 0.04, 'num_leaves': 10, 'max_depth': 6, 'min_child_samples': 8, 'subsample': 0.7995802677656919, 'colsample_bytree': 0.65012584501851, 'n_estimators': 750, 'min_split_gain': 0.2}. Best is trial 0 with value: 0.41148061220312665.

Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 21:29:11,154] Trial 5 finished with value: 0.4063993877674184 and parameters: {'learning_rate': 0.04, 'num_leaves': 10, 'max_depth': 7, 'min_child_samples': 4, 'subsample': 0.6011600636215026, 'colsample_bytree': 0.6887302690180149, 'n_estimators': 1250, 'min_split_gain': 0.1}. Best is trial 0 with value: 0.41148061220312665.
[I 2025-09-08 21:29:11,263] Trial 6 finished with value: 0.3697865935588351 and parameters: {'learning_rate': 0.04, 'num_leaves': 30, 'max_depth': 8, 'min_child_samples': 7, 'subsample': 0.7959941212063206, 'colsample_bytree': 0.6377142139217717, 'n_estimators': 750, 'min_split_gain': 1.0}. Best is trial 0 with value: 0.41148061220312665.

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 21:29:11,401] Trial 7 finished with value: 0.39205236301660173 and parameters: {'learning_rate': 0.04, 'num_leaves': 30, 'max_depth': 5, 'min_child_samples': 6, 'subsample': 0.7207218988116808, 'colsample_bytree': 0.7013328157561198, 'n_estimators': 1000, 'min_split_gain': 0.5}. Best is trial 0 with value: 0.41148061220312665.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:29:11,554] Trial 8 finished with value: 0.3790448285269277 and parameters: {'learning_rate': 0.03, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 7, 'subsample': 0.6605931974790115, 'colsample_bytree': 0.7391962047975387, 'n_estimators': 1000, 'min_split_gain': 1.0}. Best is trial 0 with value: 0.41148061220312665.
[I 2025-09-08 21:29:11,712] Trial 9 finished with value: 0.3869173525175758 and parameters: {'learning_rate': 0.04, 'num_leaves': 10, 'max_depth': 6, 'min_child_samples': 5, 'subsample': 0.6191504895897212, 'colsample_bytree': 0.7015809973903586, 'n_estimators': 750, 'min_split_gain': 0.1}. Best is trial 0 with value: 0.41148061220312665.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:29:12,240] Trial 10 finished with value: 0.39573808341418704 and parameters: {'learning_rate': 0.05, 'num_leaves': 20, 'max_depth': 8, 'min_child_samples': 4, 'subsample': 0.7508103379402735, 'colsample_bytree': 0.6166762742474694, 'n_estimators': 1000, 'min_split_gain': 0.0}. Best is trial 0 with value: 0.41148061220312665.
[I 2025-09-08 21:29:12,445] Trial 11 finished with value: 0.40373311947204077 and parameters: {'learning_rate': 0.03, 'num_leaves': 10, 'max_depth': 7, 'min_child_samples': 4, 'subsample': 0.6614927348115714, 'colsample_bytree': 0.6683954235763734, 'n_estimators': 1250, 'min_split_gain': 0.1}. Best is trial 0 with value: 0.41148061220312665.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:29:12,622] Trial 12 finished with value: 0.3779995843180369 and parameters: {'learning_rate': 0.05, 'num_leaves': 10, 'max_depth': 8, 'min_child_samples': 5, 'subsample': 0.6595549290382596, 'colsample_bytree': 0.7938057756119667, 'n_estimators': 1250, 'min_split_gain': 0.1}. Best is trial 0 with value: 0.41148061220312665.

Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 21:29:12,890] Trial 13 finished with value: 0.3837400756268667 and parameters: {'learning_rate': 0.03, 'num_leaves': 10, 'max_depth': 7, 'min_child_samples': 5, 'subsample': 0.7563173795407766, 'colsample_bytree': 0.6773395118363271, 'n_estimators': 1250, 'min_split_gain': 0.2}. Best is trial 0 with value: 0.41148061220312665.

Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 21:29:13,068] Trial 14 finished with value: 0.41172515861865217 and parameters: {'learning_rate': 0.04, 'num_leaves': 10, 'max_depth': 8, 'min_child_samples': 4, 'subsample': 0.6834537829969792, 'colsample_bytree': 0.7372437309309379, 'n_estimators': 1000, 'min_split_gain': 0.1}. Best is trial 14 with value: 0.41172515861865217.

Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:29:13,229] Trial 15 finished with value: 0.39429569799304015 and parameters: {'learning_rate': 0.03, 'num_leaves': 10, 'max_depth': 8, 'min_child_samples': 5, 'subsample': 0.6746240066730229, 'colsample_bytree': 0.735133358891836, 'n_estimators': 1000, 'min_split_gain': 1.0}. Best is trial 14 with value: 0.41172515861865217.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:29:13,511] Trial 16 finished with value: 0.3988035459588451 and parameters: {'learning_rate': 0.02, 'num_leaves': 20, 'max_depth': 8, 'min_child_samples': 4, 'subsample': 0.6888201553028133, 'colsample_bytree': 0.7703215194955402, 'n_estimators': 1000, 'min_split_gain': 0.1}. Best is trial 14 with value: 0.41172515861865217.
[I 2025-09-08 21:29:13,634] Trial 17 finished with value: 0.39734635152160475 and parameters: {'learning_rate': 0.05, 'num_leaves': 10, 'max_depth': 5, 'min_child_samples': 5, 'subsample': 0.7271174520320222, 'colsample_bytree': 0.7188938604669028, 'n_estimators': 1000, 'min_split_gain': 1.0}. Best is trial 14 with value: 0.41172515861865217.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:29:14,057] Trial 18 finished with value: 0.4089725340805043 and parameters: {'learning_rate': 0.03, 'num_leaves': 10, 'max_depth': 8, 'min_child_samples': 4, 'subsample': 0.6391117010882643, 'colsample_bytree': 0.7614173454775228, 'n_estimators': 1000, 'min_split_gain': 0.0}. Best is trial 14 with value: 0.41172515861865217.
[I 2025-09-08 21:29:14,214] Trial 19 finished with value: 0.3870103317229301 and parameters: {'learning_rate': 0.04, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 6, 'subsample': 0.7801400835098484, 'colsample_bytree': 0.6346128603804109, 'n_estimators': 1000, 'min_split_gain': 0.5}. Best is trial 14 with value: 0.41172515861865217.

Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 21:29:14,373] Trial 20 finished with value: 0.3909724264663515 and parameters: {'learning_rate': 0.04, 'num_leaves': 10, 'max_depth': 8, 'min_child_samples': 5, 'subsample': 0.6925609324701536, 'colsample_bytree': 0.6585394368154724, 'n_estimators': 1000, 'min_split_gain': 0.2}. Best is trial 14 with value: 0.41172515861865217.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:29:14,779] Trial 21 finished with value: 0.4089725340805043 and parameters: {'learning_rate': 0.03, 'num_leaves': 10, 'max_depth': 8, 'min_child_samples': 4, 'subsample': 0.6351103956883176, 'colsample_bytree': 0.7631887192945179, 'n_estimators': 1000, 'min_split_gain': 0.0}. Best is trial 14 with value: 0.41172515861865217.

Fold 1
Fold 2

[I 2025-09-08 21:29:15,255] Trial 22 finished with value: 0.3985021915912075 and parameters: {'learning_rate': 0.03, 'num_leaves': 10, 'max_depth': 8, 'min_child_samples': 4, 'subsample': 0.6459025032392182, 'colsample_bytree': 0.7520828905671092, 'n_estimators': 1000, 'min_split_gain': 0.0}. Best is trial 14 with value: 0.41172515861865217.

Fold 3
Fold 1
Fold 2

[I 2025-09-08 21:29:15,669] Trial 23 finished with value: 0.3976485754772134 and parameters: {'learning_rate': 0.03, 'num_leaves': 10, 'max_depth': 7, 'min_child_samples': 4, 'subsample': 0.632361318784631, 'colsample_bytree': 0.7989303340100032, 'n_estimators': 1000, 'min_split_gain': 0.0}. Best is trial 14 with value: 0.41172515861865217.

Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:29:16,085] Trial 24 finished with value: 0.3679305387736518 and parameters: {'learning_rate': 0.03, 'num_leaves': 10, 'max_depth': 8, 'min_child_samples': 5, 'subsample': 0.730018497927759, 'colsample_bytree': 0.7204484090281454, 'n_estimators': 1000, 'min_split_gain': 0.0}. Best is trial 14 with value: 0.41172515861865217.
[I 2025-09-08 21:29:16,227] Trial 25 finished with value: 0.42164436141841133 and parameters: {'learning_rate': 0.03, 'num_leaves': 10, 'max_depth': 8, 'min_child_samples': 4, 'subsample': 0.7055518170129985, 'colsample_bytree': 0.718362592089808, 'n_estimators': 1000, 'min_split_gain': 1.0}. Best is trial 25 with value: 0.42164436141841133.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 21:29:16,419] Trial 26 finished with value: 0.39685557043268394 and parameters: {'learning_rate': 0.02, 'num_leaves': 10, 'max_depth': 7, 'min_child_samples': 6, 'subsample': 0.7710432290576738, 'colsample_bytree': 0.7193110692341624, 'n_estimators': 1000, 'min_split_gain': 1.0}. Best is trial 25 with value: 0.42164436141841133.

Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:29:16,562] Trial 27 finished with value: 0.4073061210834356 and parameters: {'learning_rate': 0.05, 'num_leaves': 10, 'max_depth': 8, 'min_child_samples': 5, 'subsample': 0.7141424017913893, 'colsample_bytree': 0.6836080896495321, 'n_estimators': 1000, 'min_split_gain': 1.0}. Best is trial 25 with value: 0.42164436141841133.
[I 2025-09-08 21:29:16,712] Trial 28 finished with value: 0.42600317951409766 and parameters: {'learning_rate': 0.03, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 4, 'subsample': 0.6814939637533514, 'colsample_bytree': 0.7067336054321028, 'n_estimators': 1000, 'min_split_gain': 1.0}. Best is trial 28 with value: 0.42600317951409766.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 21:29:16,869] Trial 29 finished with value: 0.42600317951409766 and parameters: {'learning_rate': 0.03, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 4, 'subsample': 0.6800482312339733, 'colsample_bytree': 0.7064780900419296, 'n_estimators': 1000, 'min_split_gain': 1.0}. Best is trial 28 with value: 0.42600317951409766.
[I 2025-09-08 21:29:16,870] A new study created in memory with name: no-name-b421f604-6cb2-413f-bec9-50d7cb9b4e38
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 3

✅ LBM con C2X-Complex_rhow_9x9_depth_in_3_4 - Mejor R2: 0.43
📋 Parámetros: {'learning_rate': 0.03, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 4, 'subsample': 0.6814939637533514, 'colsample_bytree': 0.7067336054321028, 'n_estimators': 1000, 'min_split_gain': 1.0}

Buscando mejores hiperparámetros para MLP con C2X-Complex_rhow_9x9_depth_in_3_4...
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

[I 2025-09-08 21:29:18,223] Trial 0 finished with value: 0.4426880379487559 and parameters: {'hidden_layer_sizes': (128,), 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.0028807922547748744, 'learning_rate': 'constant', 'learning_rate_init': 0.001325858422423691}. Best is trial 0 with value: 0.4426880379487559.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

[I 2025-09-08 21:29:18,806] Trial 1 finished with value: 0.40564531751434146 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'relu', 'solver': 'adam', 'alpha': 0.015387543985226373, 'learning_rate': 'constant', 'learning_rate_init': 0.003078289387242535}. Best is trial 0 with value: 0.4426880379487559.

Fold 2
Fold 3
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 21:29:20,318] Trial 2 finished with value: 0.2975752562828935 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'sgd', 'alpha': 4.384548903830225e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00018432355830328432}. Best is trial 0 with value: 0.4426880379487559.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 21:29:20,993] Trial 3 finished with value: 0.37494236329188446 and parameters: {'hidden_layer_sizes': (64,), 'activation': 'relu', 'solver': 'adam', 'alpha': 0.04991144245395568, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0003446030374323778}. Best is trial 0 with value: 0.4426880379487559.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:29:21,817] Trial 4 finished with value: 0.41643649540445876 and parameters: {'hidden_layer_sizes': (64,), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.00019134900803641615, 'learning_rate': 'constant', 'learning_rate_init': 0.0021276364503781367}. Best is trial 0 with value: 0.4426880379487559.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:29:22,342] Trial 5 finished with value: 0.4520803773683333 and parameters: {'hidden_layer_sizes': (64,), 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.01961815259657439, 'learning_rate': 'constant', 'learning_rate_init': 0.005575274486021745}. Best is trial 5 with value: 0.4520803773683333.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 21:29:23,537] Trial 6 finished with value: 0.33337498160223794 and parameters: {'hidden_layer_sizes': (32,), 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.017324352839480608, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00017477845294713658}. Best is trial 5 with value: 0.4520803773683333.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

[I 2025-09-08 21:29:24,259] Trial 7 finished with value: 0.40416042209966996 and parameters: {'hidden_layer_sizes': (128,), 'activation': 'relu', 'solver': 'adam', 'alpha': 1.4100042099134876e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0014021153590732585}. Best is trial 5 with value: 0.4520803773683333.

Fold 2
Fold 3
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

[I 2025-09-08 21:29:25,139] Trial 8 finished with value: 0.3148368080382147 and parameters: {'hidden_layer_sizes': (128,), 'activation': 'tanh', 'solver': 'adam', 'alpha': 8.740077112448428e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.0030261373663621016}. Best is trial 5 with value: 0.4520803773683333.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

[I 2025-09-08 21:29:25,618] Trial 9 finished with value: 0.3892139724968982 and parameters: {'hidden_layer_sizes': (128,), 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0024916369078849584, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0035526770931803534}. Best is trial 5 with value: 0.4520803773683333.

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:29:26,246] Trial 10 finished with value: 0.4475055995268133 and parameters: {'hidden_layer_sizes': (64,), 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.0005397532553596845, 'learning_rate': 'constant', 'learning_rate_init': 0.007447801579054388}. Best is trial 5 with value: 0.4520803773683333.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2

[I 2025-09-08 21:29:26,807] Trial 11 finished with value: 0.456388993965869 and parameters: {'hidden_layer_sizes': (64,), 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.0005528459156882064, 'learning_rate': 'constant', 'learning_rate_init': 0.008235673572447743}. Best is trial 11 with value: 0.456388993965869.

Fold 3
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 2
Fold 3

[I 2025-09-08 21:29:27,339] Trial 12 finished with value: 0.447441789452351 and parameters: {'hidden_layer_sizes': (64,), 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.0010045433609001144, 'learning_rate': 'constant', 'learning_rate_init': 0.007443394945177073}. Best is trial 11 with value: 0.456388993965869.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:29:27,917] Trial 13 finished with value: 0.4573014920320084 and parameters: {'hidden_layer_sizes': (64,), 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.006988594292529506, 'learning_rate': 'constant', 'learning_rate_init': 0.009133451712786705}. Best is trial 13 with value: 0.4573014920320084.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 21:29:28,773] Trial 14 finished with value: 0.3827799318535008 and parameters: {'hidden_layer_sizes': (32,), 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.00438294867902544, 'learning_rate': 'constant', 'learning_rate_init': 0.0005461749605521}. Best is trial 13 with value: 0.4573014920320084.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:29:29,302] Trial 15 finished with value: 0.45758618637158216 and parameters: {'hidden_layer_sizes': (64,), 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.0004105122272363123, 'learning_rate': 'constant', 'learning_rate_init': 0.00840456035322438}. Best is trial 15 with value: 0.45758618637158216.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 21:29:30,539] Trial 16 finished with value: 0.4220669362433796 and parameters: {'hidden_layer_sizes': (64,), 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.00018415505610497936, 'learning_rate': 'constant', 'learning_rate_init': 0.0006193878635115515}. Best is trial 15 with value: 0.45758618637158216.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:29:31,151] Trial 17 finished with value: 0.45073046701887093 and parameters: {'hidden_layer_sizes': (64,), 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.00702809692624262, 'learning_rate': 'constant', 'learning_rate_init': 0.004650697358452872}. Best is trial 15 with value: 0.45758618637158216.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 21:29:32,585] Trial 18 finished with value: 0.33330568551816203 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.06738929043201934, 'learning_rate': 'constant', 'learning_rate_init': 0.00010235798427191988}. Best is trial 15 with value: 0.45758618637158216.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2

[I 2025-09-08 21:29:32,994] Trial 19 finished with value: 0.43219807774490676 and parameters: {'hidden_layer_sizes': (32,), 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.0009498531439010309, 'learning_rate': 'constant', 'learning_rate_init': 0.009737308209417981}. Best is trial 15 with value: 0.45758618637158216.

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 21:29:33,956] Trial 20 finished with value: 0.43704143768118686 and parameters: {'hidden_layer_sizes': (64,), 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.0015019487091363331, 'learning_rate': 'constant', 'learning_rate_init': 0.0021525391448638303}. Best is trial 15 with value: 0.45758618637158216.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:29:34,468] Trial 21 finished with value: 0.457169361548123 and parameters: {'hidden_layer_sizes': (64,), 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.00039106591053492855, 'learning_rate': 'constant', 'learning_rate_init': 0.008746458975969724}. Best is trial 15 with value: 0.45758618637158216.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:29:35,008] Trial 22 finished with value: 0.45293184816442267 and parameters: {'hidden_layer_sizes': (64,), 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.00032319455316006957, 'learning_rate': 'constant', 'learning_rate_init': 0.0053975661794000195}. Best is trial 15 with value: 0.45758618637158216.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:29:35,528] Trial 23 finished with value: 0.4577784242753456 and parameters: {'hidden_layer_sizes': (64,), 'activation': 'relu', 'solver': 'sgd', 'alpha': 9.353815923306378e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.009405252120074026}. Best is trial 23 with value: 0.4577784242753456.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:29:36,255] Trial 24 finished with value: 0.4507150128711346 and parameters: {'hidden_layer_sizes': (64,), 'activation': 'relu', 'solver': 'sgd', 'alpha': 4.477652319861394e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.00495733429259206}. Best is trial 23 with value: 0.4577784242753456.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:29:36,902] Trial 25 finished with value: 0.44575938408275756 and parameters: {'hidden_layer_sizes': (64,), 'activation': 'relu', 'solver': 'sgd', 'alpha': 1.769663764705437e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.0038625557447988304}. Best is trial 23 with value: 0.4577784242753456.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 21:29:38,149] Trial 26 finished with value: 0.40021660164188155 and parameters: {'hidden_layer_sizes': (64,), 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.00013194658012240335, 'learning_rate': 'adaptive', 'learning_rate_init': 0.009999994905682087}. Best is trial 23 with value: 0.4577784242753456.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:29:38,638] Trial 27 finished with value: 0.4307567253273225 and parameters: {'hidden_layer_sizes': (32,), 'activation': 'relu', 'solver': 'sgd', 'alpha': 4.9750712843512926e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.006201895528111717}. Best is trial 23 with value: 0.4577784242753456.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

[I 2025-09-08 21:29:39,519] Trial 28 finished with value: 0.3951689285490095 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'relu', 'solver': 'sgd', 'alpha': 7.458406224924152e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.002381125758710397}. Best is trial 23 with value: 0.4577784242753456.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

[I 2025-09-08 21:29:40,999] Trial 29 finished with value: 0.4427749271753883 and parameters: {'hidden_layer_sizes': (128,), 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.002207746830179731, 'learning_rate': 'constant', 'learning_rate_init': 0.0014285900932544022}. Best is trial 23 with value: 0.4577784242753456.
[I 2025-09-08 21:29:41,001] A new study created in memory with name: no-name-dc2e83d3-b43d-4635-9cb5-13bbc57a758b

Fold 3

✅ MLP con C2X-Complex_rhow_9x9_depth_in_3_4 - Mejor R2: 0.46
📋 Parámetros: {'hidden_layer_sizes': (64,), 'activation': 'relu', 'solver': 'sgd', 'alpha': 9.353815923306378e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.009405252120074026}

Buscando mejores hiperparámetros para SVR con C2X-Complex_rhow_9x9_depth_in_3_4...
Fold 1

[I 2025-09-08 21:29:41,084] Trial 0 finished with value: 0.5095668077058405 and parameters: {'C': 6.436228976299725, 'epsilon': 0.025057491331582474}. Best is trial 0 with value: 0.5095668077058405.
[I 2025-09-08 21:29:41,142] Trial 1 finished with value: 0.5155714229028731 and parameters: {'C': 4.005918096958267, 'epsilon': 0.10884959351928648}. Best is trial 1 with value: 0.5155714229028731.
[I 2025-09-08 21:29:41,203] Trial 2 finished with value: 0.4616664675294331 and parameters: {'C': 9.582691329742602, 'epsilon': 0.15549124964993857}. Best is trial 1 with value: 0.5155714229028731.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:29:41,253] Trial 3 finished with value: 0.492015105248737 and parameters: {'C': 1.3698323549558231, 'epsilon': 0.17374364283896646}. Best is trial 1 with value: 0.5155714229028731.
[I 2025-09-08 21:29:41,307] Trial 4 finished with value: 0.3520999068600115 and parameters: {'C': 0.3666619919205542, 'epsilon': 0.14436558682259218}. Best is trial 1 with value: 0.5155714229028731.
[I 2025-09-08 21:29:41,370] Trial 5 finished with value: 0.25291088183365956 and parameters: {'C': 0.13776114754906357, 'epsilon': 0.18217067646624868}. Best is trial 1 with value: 0.5155714229028731.
[I 2025-09-08 21:29:41,435] Trial 6 finished with value: 0.5037131127656823 and parameters: {'C': 1.8478507366654315, 'epsilon': 0.18637469759103636}. Best is trial 1 with value: 0.5155714229028731.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 21:29:41,488] Trial 7 finished with value: 0.23289321584134406 and parameters: {'C': 0.12407754448275862, 'epsilon': 0.058600985279135605}. Best is trial 1 with value: 0.5155714229028731.
[I 2025-09-08 21:29:41,554] Trial 8 finished with value: 0.5191864426819414 and parameters: {'C': 4.189596608050861, 'epsilon': 0.04718535967595182}. Best is trial 8 with value: 0.5191864426819414.
[I 2025-09-08 21:29:41,608] Trial 9 finished with value: 0.2704918210635353 and parameters: {'C': 0.17665387535294894, 'epsilon': 0.019417937545410026}. Best is trial 8 with value: 0.5191864426819414.
[I 2025-09-08 21:29:41,663] Trial 10 finished with value: 0.4066310331350704 and parameters: {'C': 0.5850660110756025, 'epsilon': 0.07615027948581962}. Best is trial 8 with value: 0.5191864426819414.

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 21:29:41,723] Trial 11 finished with value: 0.5136435272429057 and parameters: {'C': 3.3902228480674736, 'epsilon': 0.11228719243085292}. Best is trial 8 with value: 0.5191864426819414.
[I 2025-09-08 21:29:41,791] Trial 12 finished with value: 0.51488714428488 and parameters: {'C': 3.5386015673283384, 'epsilon': 0.10618120034268232}. Best is trial 8 with value: 0.5191864426819414.
[I 2025-09-08 21:29:41,853] Trial 13 finished with value: 0.5172723835455678 and parameters: {'C': 3.3395589129178562, 'epsilon': 0.06928642073774269}. Best is trial 8 with value: 0.5191864426819414.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 21:29:41,912] Trial 14 finished with value: 0.5029621820016935 and parameters: {'C': 1.8520093535075899, 'epsilon': 0.061879022713080774}. Best is trial 8 with value: 0.5191864426819414.
[I 2025-09-08 21:29:41,978] Trial 15 finished with value: 0.42457514921137035 and parameters: {'C': 0.7340855067911056, 'epsilon': 0.04336510879357552}. Best is trial 8 with value: 0.5191864426819414.
[I 2025-09-08 21:29:42,066] Trial 16 finished with value: 0.5090490144639706 and parameters: {'C': 5.6068814562198215, 'epsilon': 0.08637336957349112}. Best is trial 8 with value: 0.5191864426819414.

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 21:29:42,135] Trial 17 finished with value: 0.5138425332000045 and parameters: {'C': 2.4597574562894553, 'epsilon': 0.04061798556838418}. Best is trial 8 with value: 0.5191864426819414.
[I 2025-09-08 21:29:42,220] Trial 18 finished with value: 0.4738061754155593 and parameters: {'C': 9.596844320761631, 'epsilon': 0.010053452087006094}. Best is trial 8 with value: 0.5191864426819414.
[I 2025-09-08 21:29:42,276] Trial 19 finished with value: 0.4653181348885327 and parameters: {'C': 1.0857001343394104, 'epsilon': 0.08903271510919814}. Best is trial 8 with value: 0.5191864426819414.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 21:29:42,339] Trial 20 finished with value: 0.5046687133514786 and parameters: {'C': 5.657890061723024, 'epsilon': 0.12414705663380718}. Best is trial 8 with value: 0.5191864426819414.
[I 2025-09-08 21:29:42,412] Trial 21 finished with value: 0.5174968035295276 and parameters: {'C': 3.542537063867257, 'epsilon': 0.06610299108108429}. Best is trial 8 with value: 0.5191864426819414.
[I 2025-09-08 21:29:42,481] Trial 22 finished with value: 0.516159586464056 and parameters: {'C': 2.534566968402245, 'epsilon': 0.06383562768432234}. Best is trial 8 with value: 0.5191864426819414.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 21:29:42,542] Trial 23 finished with value: 0.5187680460212828 and parameters: {'C': 4.120100868967512, 'epsilon': 0.0418776175919836}. Best is trial 8 with value: 0.5191864426819414.
[I 2025-09-08 21:29:42,613] Trial 24 finished with value: 0.517690018843607 and parameters: {'C': 5.256812727935746, 'epsilon': 0.03585627953557263}. Best is trial 8 with value: 0.5191864426819414.
[I 2025-09-08 21:29:42,703] Trial 25 finished with value: 0.5051417359392735 and parameters: {'C': 6.668036621082233, 'epsilon': 0.04399012457232561}. Best is trial 8 with value: 0.5191864426819414.

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 21:29:42,775] Trial 26 finished with value: 0.5197429137919033 and parameters: {'C': 4.5277396709733395, 'epsilon': 0.0324926674251931}. Best is trial 26 with value: 0.5197429137919033.
[I 2025-09-08 21:29:42,846] Trial 27 finished with value: 0.5058671188270368 and parameters: {'C': 2.1194791646372604, 'epsilon': 0.02994074281916643}. Best is trial 26 with value: 0.5197429137919033.
[I 2025-09-08 21:29:42,903] Trial 28 finished with value: 0.3216754184635422 and parameters: {'C': 0.2874259108258448, 'epsilon': 0.010232245868216444}. Best is trial 26 with value: 0.5197429137919033.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 21:29:42,962] Trial 29 finished with value: 0.48610085598853847 and parameters: {'C': 1.4095639999879768, 'epsilon': 0.051776546393593637}. Best is trial 26 with value: 0.5197429137919033.
[I 2025-09-08 21:29:42,964] A new study created in memory with name: no-name-c935b6e0-2bb2-4d00-aeae-989095679233
[I 2025-09-08 21:29:43,016] Trial 0 finished with value: 0.38840243575526395 and parameters: {'n_neighbors': 4, 'leaf_size': 29}. Best is trial 0 with value: 0.38840243575526395.
[I 2025-09-08 21:29:43,065] Trial 1 finished with value: 0.39582891749046495 and parameters: {'n_neighbors': 5, 'leaf_size': 16}. Best is trial 1 with value: 0.39582891749046495.
[I 2025-09-08 21:29:43,110] Trial 2 finished with value: 0.42277673908293273 and parameters: {'n_neighbors': 7, 'leaf_size': 20}. Best is trial 2 with value: 0.42277673908293273.

Fold 3

✅ SVR con C2X-Complex_rhow_9x9_depth_in_3_4 - Mejor R2: 0.52
📋 Parámetros: {'C': 4.5277396709733395, 'epsilon': 0.0324926674251931}

Buscando mejores hiperparámetros para KNN con C2X-Complex_rhow_9x9_depth_in_3_4...
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:29:43,153] Trial 3 finished with value: 0.38840243575526395 and parameters: {'n_neighbors': 4, 'leaf_size': 15}. Best is trial 2 with value: 0.42277673908293273.
[I 2025-09-08 21:29:43,203] Trial 4 finished with value: 0.4153449960905485 and parameters: {'n_neighbors': 12, 'leaf_size': 30}. Best is trial 2 with value: 0.42277673908293273.
[I 2025-09-08 21:29:43,248] Trial 5 finished with value: 0.4153449960905485 and parameters: {'n_neighbors': 12, 'leaf_size': 26}. Best is trial 2 with value: 0.42277673908293273.
[I 2025-09-08 21:29:43,290] Trial 6 finished with value: 0.4076251508584523 and parameters: {'n_neighbors': 10, 'leaf_size': 13}. Best is trial 2 with value: 0.42277673908293273.
[I 2025-09-08 21:29:43,333] Trial 7 finished with value: 0.4092851294463912 and parameters: {'n_neighbors': 8, 'leaf_size': 29}. Best is trial 2 with value: 0.42277673908293273.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:29:43,374] Trial 8 finished with value: 0.39582891749046495 and parameters: {'n_neighbors': 5, 'leaf_size': 14}. Best is trial 2 with value: 0.42277673908293273.
[I 2025-09-08 21:29:43,421] Trial 9 finished with value: 0.4153449960905485 and parameters: {'n_neighbors': 12, 'leaf_size': 31}. Best is trial 2 with value: 0.42277673908293273.
[I 2025-09-08 21:29:43,502] Trial 10 finished with value: 0.42277673908293273 and parameters: {'n_neighbors': 7, 'leaf_size': 40}. Best is trial 2 with value: 0.42277673908293273.
[I 2025-09-08 21:29:43,573] Trial 11 finished with value: 0.42277673908293273 and parameters: {'n_neighbors': 7, 'leaf_size': 40}. Best is trial 2 with value: 0.42277673908293273.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 21:29:43,633] Trial 12 finished with value: 0.42277673908293273 and parameters: {'n_neighbors': 7, 'leaf_size': 20}. Best is trial 2 with value: 0.42277673908293273.
[I 2025-09-08 21:29:43,690] Trial 13 finished with value: 0.398280037575238 and parameters: {'n_neighbors': 9, 'leaf_size': 38}. Best is trial 2 with value: 0.42277673908293273.
[I 2025-09-08 21:29:43,747] Trial 14 finished with value: 0.415284246243212 and parameters: {'n_neighbors': 6, 'leaf_size': 19}. Best is trial 2 with value: 0.42277673908293273.
[I 2025-09-08 21:29:43,796] Trial 15 finished with value: 0.398280037575238 and parameters: {'n_neighbors': 9, 'leaf_size': 35}. Best is trial 2 with value: 0.42277673908293273.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:29:43,851] Trial 16 finished with value: 0.3516582542144437 and parameters: {'n_neighbors': 3, 'leaf_size': 22}. Best is trial 2 with value: 0.42277673908293273.
[I 2025-09-08 21:29:43,909] Trial 17 finished with value: 0.415284246243212 and parameters: {'n_neighbors': 6, 'leaf_size': 23}. Best is trial 2 with value: 0.42277673908293273.
[I 2025-09-08 21:29:43,965] Trial 18 finished with value: 0.4076251508584523 and parameters: {'n_neighbors': 10, 'leaf_size': 10}. Best is trial 2 with value: 0.42277673908293273.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:29:44,016] Trial 19 finished with value: 0.4092851294463912 and parameters: {'n_neighbors': 8, 'leaf_size': 34}. Best is trial 2 with value: 0.42277673908293273.
[I 2025-09-08 21:29:44,073] Trial 20 finished with value: 0.415284246243212 and parameters: {'n_neighbors': 6, 'leaf_size': 25}. Best is trial 2 with value: 0.42277673908293273.
[I 2025-09-08 21:29:44,125] Trial 21 finished with value: 0.42277673908293273 and parameters: {'n_neighbors': 7, 'leaf_size': 40}. Best is trial 2 with value: 0.42277673908293273.
[I 2025-09-08 21:29:44,173] Trial 22 finished with value: 0.42277673908293273 and parameters: {'n_neighbors': 7, 'leaf_size': 36}. Best is trial 2 with value: 0.42277673908293273.
[I 2025-09-08 21:29:44,225] Trial 23 finished with value: 0.398280037575238 and parameters: {'n_neighbors': 9, 'leaf_size': 39}. Best is trial 2 with value: 0.42277673908293273.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:29:44,282] Trial 24 finished with value: 0.4092851294463912 and parameters: {'n_neighbors': 8, 'leaf_size': 33}. Best is trial 2 with value: 0.42277673908293273.
[I 2025-09-08 21:29:44,340] Trial 25 finished with value: 0.415284246243212 and parameters: {'n_neighbors': 6, 'leaf_size': 37}. Best is trial 2 with value: 0.42277673908293273.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:29:44,440] Trial 26 finished with value: 0.39582891749046495 and parameters: {'n_neighbors': 5, 'leaf_size': 18}. Best is trial 2 with value: 0.42277673908293273.
[I 2025-09-08 21:29:44,496] Trial 27 finished with value: 0.42277673908293273 and parameters: {'n_neighbors': 7, 'leaf_size': 40}. Best is trial 2 with value: 0.42277673908293273.
[I 2025-09-08 21:29:44,551] Trial 28 finished with value: 0.4076251508584523 and parameters: {'n_neighbors': 10, 'leaf_size': 33}. Best is trial 2 with value: 0.42277673908293273.
[I 2025-09-08 21:29:44,606] Trial 29 finished with value: 0.38840243575526395 and parameters: {'n_neighbors': 4, 'leaf_size': 27}. Best is trial 2 with value: 0.42277673908293273.
[I 2025-09-08 21:29:44,607] A new study created in memory with name: no-name-ceaaf046-22ba-429d-a903-2bf277fcede9

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

✅ KNN con C2X-Complex_rhow_9x9_depth_in_3_4 - Mejor R2: 0.42
📋 Parámetros: {'n_neighbors': 7, 'leaf_size': 20}

Buscando mejores hiperparámetros para LR con C2X-Complex_rhow_9x9_depth_in_3_4...
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:29:44,663] Trial 0 finished with value: 0.2945522760213509 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 0 with value: 0.2945522760213509.
[I 2025-09-08 21:29:44,744] Trial 1 finished with value: 0.4010891673461538 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 1 with value: 0.4010891673461538.
[I 2025-09-08 21:29:44,801] Trial 2 finished with value: 0.2945522760213509 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 1 with value: 0.4010891673461538.
[I 2025-09-08 21:29:44,859] Trial 3 finished with value: 0.2945522760213509 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 1 with value: 0.4010891673461538.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 21:29:44,944] Trial 4 finished with value: 0.4010891673461538 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 1 with value: 0.4010891673461538.
[I 2025-09-08 21:29:44,994] Trial 5 finished with value: 0.4010891673461538 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 1 with value: 0.4010891673461538.
[I 2025-09-08 21:29:45,051] Trial 6 finished with value: 0.2945522760213509 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 1 with value: 0.4010891673461538.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:29:45,111] Trial 7 finished with value: 0.2945522760213509 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 1 with value: 0.4010891673461538.
[I 2025-09-08 21:29:45,171] Trial 8 finished with value: 0.2945522760213509 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 1 with value: 0.4010891673461538.
[I 2025-09-08 21:29:45,229] Trial 9 finished with value: 0.4010891673461538 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 1 with value: 0.4010891673461538.
[I 2025-09-08 21:29:45,282] Trial 10 finished with value: 0.4010891673461538 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 1 with value: 0.4010891673461538.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 21:29:45,349] Trial 11 finished with value: 0.4010891673461538 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 1 with value: 0.4010891673461538.
[I 2025-09-08 21:29:45,399] Trial 12 finished with value: 0.4010891673461538 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 1 with value: 0.4010891673461538.
[I 2025-09-08 21:29:45,450] Trial 13 finished with value: 0.4010891673461538 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 1 with value: 0.4010891673461538.
[I 2025-09-08 21:29:45,501] Trial 14 finished with value: 0.4010891673461538 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 1 with value: 0.4010891673461538.

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:29:45,543] Trial 15 finished with value: 0.4010891673461538 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 1 with value: 0.4010891673461538.
[I 2025-09-08 21:29:45,591] Trial 16 finished with value: 0.4010891673461538 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 1 with value: 0.4010891673461538.
[I 2025-09-08 21:29:45,644] Trial 17 finished with value: 0.4010891673461538 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 1 with value: 0.4010891673461538.
[I 2025-09-08 21:29:45,689] Trial 18 finished with value: 0.4010891673461538 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 1 with value: 0.4010891673461538.
[I 2025-09-08 21:29:45,732] Trial 19 finished with value: 0.4010891673461538 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 1 with value: 0.4010891673461538.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 21:29:45,775] Trial 20 finished with value: 0.4010891673461538 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 1 with value: 0.4010891673461538.
[I 2025-09-08 21:29:45,826] Trial 21 finished with value: 0.4010891673461538 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 1 with value: 0.4010891673461538.
[I 2025-09-08 21:29:45,876] Trial 22 finished with value: 0.4010891673461538 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 1 with value: 0.4010891673461538.
[I 2025-09-08 21:29:45,920] Trial 23 finished with value: 0.4010891673461538 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 1 with value: 0.4010891673461538.
[I 2025-09-08 21:29:45,962] Trial 24 finished with value: 0.4010891673461538 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 1 with value: 0.4010891673461538.

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:29:46,004] Trial 25 finished with value: 0.4010891673461538 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 1 with value: 0.4010891673461538.
[I 2025-09-08 21:29:46,052] Trial 26 finished with value: 0.4010891673461538 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 1 with value: 0.4010891673461538.
[I 2025-09-08 21:29:46,101] Trial 27 finished with value: 0.4010891673461538 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 1 with value: 0.4010891673461538.
[I 2025-09-08 21:29:46,143] Trial 28 finished with value: 0.4010891673461538 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 1 with value: 0.4010891673461538.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 21:29:46,196] Trial 29 finished with value: 0.2945522760213509 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 1 with value: 0.4010891673461538.
[I 2025-09-08 21:29:46,198] A new study created in memory with name: no-name-bcdfdb04-688c-4101-8c55-d66c6377481f

Fold 3

✅ LR con C2X-Complex_rhow_9x9_depth_in_3_4 - Mejor R2: 0.40
📋 Parámetros: {'fit_intercept': True, 'positive': True}

Buscando mejores hiperparámetros para RF con C2X-Complex_rhow_9x9_depth_in_3_4...
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:29:49,608] Trial 0 finished with value: 0.4502489425916176 and parameters: {'n_estimators': 400, 'max_depth': 8, 'min_samples_split': 3, 'min_samples_leaf': 6, 'bootstrap': True}. Best is trial 0 with value: 0.4502489425916176.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:29:53,578] Trial 1 finished with value: 0.4537128158808235 and parameters: {'n_estimators': 400, 'max_depth': 8, 'min_samples_split': 5, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 1 with value: 0.4537128158808235.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:29:55,192] Trial 2 finished with value: 0.44279118638455506 and parameters: {'n_estimators': 200, 'max_depth': 12, 'min_samples_split': 8, 'min_samples_leaf': 7, 'bootstrap': True}. Best is trial 1 with value: 0.4537128158808235.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:29:58,706] Trial 3 finished with value: 0.45124282885128925 and parameters: {'n_estimators': 400, 'max_depth': 10, 'min_samples_split': 2, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 1 with value: 0.4537128158808235.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:29:59,932] Trial 4 finished with value: 0.2972473226655334 and parameters: {'n_estimators': 100, 'max_depth': 6, 'min_samples_split': 5, 'min_samples_leaf': 5, 'bootstrap': False}. Best is trial 1 with value: 0.4537128158808235.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:30:02,957] Trial 5 finished with value: 0.4496436942358786 and parameters: {'n_estimators': 400, 'max_depth': 5, 'min_samples_split': 4, 'min_samples_leaf': 6, 'bootstrap': True}. Best is trial 1 with value: 0.4537128158808235.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:30:05,206] Trial 6 finished with value: 0.3498168150003256 and parameters: {'n_estimators': 200, 'max_depth': 5, 'min_samples_split': 2, 'min_samples_leaf': 4, 'bootstrap': False}. Best is trial 1 with value: 0.4537128158808235.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:30:09,259] Trial 7 finished with value: 0.45657393383960104 and parameters: {'n_estimators': 400, 'max_depth': 12, 'min_samples_split': 2, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 7 with value: 0.45657393383960104.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:30:11,551] Trial 8 finished with value: 0.3398241254732526 and parameters: {'n_estimators': 200, 'max_depth': 8, 'min_samples_split': 2, 'min_samples_leaf': 8, 'bootstrap': False}. Best is trial 7 with value: 0.45657393383960104.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:30:12,374] Trial 9 finished with value: 0.44141404677445917 and parameters: {'n_estimators': 100, 'max_depth': 12, 'min_samples_split': 6, 'min_samples_leaf': 7, 'bootstrap': True}. Best is trial 7 with value: 0.45657393383960104.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:30:18,912] Trial 10 finished with value: 0.27118050250976317 and parameters: {'n_estimators': 400, 'max_depth': 10, 'min_samples_split': 7, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 7 with value: 0.45657393383960104.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:30:23,408] Trial 11 finished with value: 0.4486214281749823 and parameters: {'n_estimators': 400, 'max_depth': 10, 'min_samples_split': 4, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 7 with value: 0.45657393383960104.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:30:27,210] Trial 12 finished with value: 0.45409821386556376 and parameters: {'n_estimators': 400, 'max_depth': 7, 'min_samples_split': 5, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 7 with value: 0.45657393383960104.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:30:31,095] Trial 13 finished with value: 0.45409821386556376 and parameters: {'n_estimators': 400, 'max_depth': 7, 'min_samples_split': 6, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 7 with value: 0.45657393383960104.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:30:35,151] Trial 14 finished with value: 0.4560694757658503 and parameters: {'n_estimators': 400, 'max_depth': 11, 'min_samples_split': 4, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 7 with value: 0.45657393383960104.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:30:36,144] Trial 15 finished with value: 0.4500814331884559 and parameters: {'n_estimators': 100, 'max_depth': 11, 'min_samples_split': 3, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 7 with value: 0.45657393383960104.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:30:39,852] Trial 16 finished with value: 0.45378441436930794 and parameters: {'n_estimators': 400, 'max_depth': 11, 'min_samples_split': 3, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 7 with value: 0.45657393383960104.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:30:44,354] Trial 17 finished with value: 0.4471483653220341 and parameters: {'n_estimators': 400, 'max_depth': 11, 'min_samples_split': 4, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 7 with value: 0.45657393383960104.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:30:47,537] Trial 18 finished with value: 0.08384582481093705 and parameters: {'n_estimators': 200, 'max_depth': 12, 'min_samples_split': 3, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 7 with value: 0.45657393383960104.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:30:48,507] Trial 19 finished with value: 0.4508005811751128 and parameters: {'n_estimators': 100, 'max_depth': 9, 'min_samples_split': 2, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 7 with value: 0.45657393383960104.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:30:53,013] Trial 20 finished with value: 0.4471483653220341 and parameters: {'n_estimators': 400, 'max_depth': 11, 'min_samples_split': 4, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 7 with value: 0.45657393383960104.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:30:56,631] Trial 21 finished with value: 0.45370975843389605 and parameters: {'n_estimators': 400, 'max_depth': 6, 'min_samples_split': 6, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 7 with value: 0.45657393383960104.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:31:00,453] Trial 22 finished with value: 0.45409821386556376 and parameters: {'n_estimators': 400, 'max_depth': 7, 'min_samples_split': 5, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 7 with value: 0.45657393383960104.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:31:04,228] Trial 23 finished with value: 0.454006273407282 and parameters: {'n_estimators': 400, 'max_depth': 9, 'min_samples_split': 7, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 7 with value: 0.45657393383960104.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:31:08,066] Trial 24 finished with value: 0.45409821386556376 and parameters: {'n_estimators': 400, 'max_depth': 7, 'min_samples_split': 4, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 7 with value: 0.45657393383960104.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:31:12,535] Trial 25 finished with value: 0.45018589633667094 and parameters: {'n_estimators': 400, 'max_depth': 12, 'min_samples_split': 5, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 7 with value: 0.45657393383960104.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:31:17,956] Trial 26 finished with value: 0.27997292618210595 and parameters: {'n_estimators': 400, 'max_depth': 9, 'min_samples_split': 3, 'min_samples_leaf': 5, 'bootstrap': False}. Best is trial 7 with value: 0.45657393383960104.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:31:21,433] Trial 27 finished with value: 0.45234751510374344 and parameters: {'n_estimators': 400, 'max_depth': 6, 'min_samples_split': 6, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 7 with value: 0.45657393383960104.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:31:23,452] Trial 28 finished with value: 0.4552560893322912 and parameters: {'n_estimators': 200, 'max_depth': 10, 'min_samples_split': 5, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 7 with value: 0.45657393383960104.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:31:25,213] Trial 29 finished with value: 0.44919911699628073 and parameters: {'n_estimators': 200, 'max_depth': 10, 'min_samples_split': 7, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 7 with value: 0.45657393383960104.
[I 2025-09-08 21:31:25,215] A new study created in memory with name: no-name-9f7fd802-c742-4cfc-a2e6-e636bf906bc5

✅ RF con C2X-Complex_rhow_9x9_depth_in_3_4 - Mejor R2: 0.46
📋 Parámetros: {'n_estimators': 400, 'max_depth': 12, 'min_samples_split': 2, 'min_samples_leaf': 3, 'bootstrap': True}

Buscando mejores hiperparámetros para CAT con C2X-Complex_rhow_9x9_depth_in_3_4...
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:31:36,423] Trial 0 finished with value: 0.40326675091847397 and parameters: {'iterations': 1000, 'learning_rate': 0.05, 'depth': 7, 'l2_leaf_reg': 4.223911834349941}. Best is trial 0 with value: 0.40326675091847397.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:31:38,649] Trial 1 finished with value: 0.3546572057350434 and parameters: {'iterations': 1000, 'learning_rate': 0.02, 'depth': 4, 'l2_leaf_reg': 1.9312847600730843}. Best is trial 0 with value: 0.40326675091847397.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:31:41,952] Trial 2 finished with value: 0.37249650282555136 and parameters: {'iterations': 1000, 'learning_rate': 0.04, 'depth': 5, 'l2_leaf_reg': 3.2037613838706918}. Best is trial 0 with value: 0.40326675091847397.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:31:43,601] Trial 3 finished with value: 0.4002037570251306 and parameters: {'iterations': 500, 'learning_rate': 0.05, 'depth': 5, 'l2_leaf_reg': 4.853119304727514}. Best is trial 0 with value: 0.40326675091847397.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:31:45,928] Trial 4 finished with value: 0.3664167406556185 and parameters: {'iterations': 750, 'learning_rate': 0.05, 'depth': 5, 'l2_leaf_reg': 2.9390079673060625}. Best is trial 0 with value: 0.40326675091847397.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:31:48,285] Trial 5 finished with value: 0.37932532626446985 and parameters: {'iterations': 750, 'learning_rate': 0.05, 'depth': 5, 'l2_leaf_reg': 2.3353026227331783}. Best is trial 0 with value: 0.40326675091847397.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:31:53,418] Trial 6 finished with value: 0.38041318393745716 and parameters: {'iterations': 1000, 'learning_rate': 0.02, 'depth': 6, 'l2_leaf_reg': 2.5339097839426623}. Best is trial 0 with value: 0.40326675091847397.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:32:01,895] Trial 7 finished with value: 0.41581317887691177 and parameters: {'iterations': 750, 'learning_rate': 0.02, 'depth': 7, 'l2_leaf_reg': 3.0249478357094843}. Best is trial 7 with value: 0.41581317887691177.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:32:02,899] Trial 8 finished with value: 0.35463122562428806 and parameters: {'iterations': 500, 'learning_rate': 0.05, 'depth': 4, 'l2_leaf_reg': 3.385578802432797}. Best is trial 7 with value: 0.41581317887691177.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:32:22,831] Trial 9 finished with value: 0.4266199914720407 and parameters: {'iterations': 750, 'learning_rate': 0.03, 'depth': 8, 'l2_leaf_reg': 4.058746897996231}. Best is trial 9 with value: 0.4266199914720407.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:32:43,480] Trial 10 finished with value: 0.4341979559418218 and parameters: {'iterations': 750, 'learning_rate': 0.03, 'depth': 8, 'l2_leaf_reg': 1.3872204583620107}. Best is trial 10 with value: 0.4341979559418218.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:33:03,939] Trial 11 finished with value: 0.4373474756431119 and parameters: {'iterations': 750, 'learning_rate': 0.03, 'depth': 8, 'l2_leaf_reg': 1.3260584426051756}. Best is trial 11 with value: 0.4373474756431119.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:33:24,485] Trial 12 finished with value: 0.44297416297510095 and parameters: {'iterations': 750, 'learning_rate': 0.03, 'depth': 8, 'l2_leaf_reg': 1.0255588829481326}. Best is trial 12 with value: 0.44297416297510095.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:33:32,959] Trial 13 finished with value: 0.41060462350904886 and parameters: {'iterations': 750, 'learning_rate': 0.03, 'depth': 7, 'l2_leaf_reg': 1.1415180176141513}. Best is trial 12 with value: 0.44297416297510095.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:33:53,321] Trial 14 finished with value: 0.41687608260465553 and parameters: {'iterations': 750, 'learning_rate': 0.03, 'depth': 8, 'l2_leaf_reg': 1.7312307322688494}. Best is trial 12 with value: 0.44297416297510095.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:34:01,891] Trial 15 finished with value: 0.42400988031032627 and parameters: {'iterations': 750, 'learning_rate': 0.03, 'depth': 7, 'l2_leaf_reg': 1.1904126381295836}. Best is trial 12 with value: 0.44297416297510095.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:34:15,640] Trial 16 finished with value: 0.4303927325399351 and parameters: {'iterations': 500, 'learning_rate': 0.04, 'depth': 8, 'l2_leaf_reg': 1.6822194739756124}. Best is trial 12 with value: 0.44297416297510095.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:34:19,393] Trial 17 finished with value: 0.384608072116668 and parameters: {'iterations': 750, 'learning_rate': 0.03, 'depth': 6, 'l2_leaf_reg': 2.1020431443800294}. Best is trial 12 with value: 0.44297416297510095.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:34:23,195] Trial 18 finished with value: 0.40194711047301385 and parameters: {'iterations': 750, 'learning_rate': 0.03, 'depth': 6, 'l2_leaf_reg': 1.0157329781258182}. Best is trial 12 with value: 0.44297416297510095.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:34:36,789] Trial 19 finished with value: 0.42968263316688127 and parameters: {'iterations': 500, 'learning_rate': 0.03, 'depth': 8, 'l2_leaf_reg': 1.5288108591547331}. Best is trial 12 with value: 0.44297416297510095.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:34:45,286] Trial 20 finished with value: 0.4273088457869128 and parameters: {'iterations': 750, 'learning_rate': 0.04, 'depth': 7, 'l2_leaf_reg': 2.518887473450193}. Best is trial 12 with value: 0.44297416297510095.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:35:05,616] Trial 21 finished with value: 0.41357963942797554 and parameters: {'iterations': 750, 'learning_rate': 0.03, 'depth': 8, 'l2_leaf_reg': 1.372789477367094}. Best is trial 12 with value: 0.44297416297510095.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:35:26,055] Trial 22 finished with value: 0.43577882277958285 and parameters: {'iterations': 750, 'learning_rate': 0.03, 'depth': 8, 'l2_leaf_reg': 1.0067719338584746}. Best is trial 12 with value: 0.44297416297510095.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:35:46,527] Trial 23 finished with value: 0.4331017105457587 and parameters: {'iterations': 750, 'learning_rate': 0.03, 'depth': 8, 'l2_leaf_reg': 1.043336213660669}. Best is trial 12 with value: 0.44297416297510095.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:35:55,101] Trial 24 finished with value: 0.4125674695116997 and parameters: {'iterations': 750, 'learning_rate': 0.03, 'depth': 7, 'l2_leaf_reg': 1.9000032421203223}. Best is trial 12 with value: 0.44297416297510095.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:36:15,462] Trial 25 finished with value: 0.4241720318773552 and parameters: {'iterations': 750, 'learning_rate': 0.03, 'depth': 8, 'l2_leaf_reg': 1.4107271458594415}. Best is trial 12 with value: 0.44297416297510095.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:36:23,958] Trial 26 finished with value: 0.4071847291644915 and parameters: {'iterations': 750, 'learning_rate': 0.03, 'depth': 7, 'l2_leaf_reg': 1.5935983918026695}. Best is trial 12 with value: 0.44297416297510095.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:36:44,257] Trial 27 finished with value: 0.4214463586369696 and parameters: {'iterations': 750, 'learning_rate': 0.03, 'depth': 8, 'l2_leaf_reg': 1.9654652579182446}. Best is trial 12 with value: 0.44297416297510095.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:36:49,983] Trial 28 finished with value: 0.4168754587570744 and parameters: {'iterations': 500, 'learning_rate': 0.02, 'depth': 7, 'l2_leaf_reg': 2.2330643008127877}. Best is trial 12 with value: 0.44297416297510095.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:37:01,392] Trial 29 finished with value: 0.4012501862942446 and parameters: {'iterations': 1000, 'learning_rate': 0.04, 'depth': 7, 'l2_leaf_reg': 3.7338426117367156}. Best is trial 12 with value: 0.44297416297510095.
[I 2025-09-08 21:37:01,394] A new study created in memory with name: no-name-c9c9ae82-ad36-424c-84d8-e9ea659f15fb
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.449e+01, tolerance: 4.779e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.590e+01, tolerance: 4.223e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.950e+01, tolerance: 3.136e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:37:01,466] Trial 0 finished with value: 0.4267588615082328 and parameters: {'alpha': 0.0020263952940592065, 'l1_ratio': 0.39241152574618043}. Best is trial 0 with value: 0.4267588615082328.
[I 2025-09-08 21:37:01,554] Trial 1 finished with value: 0.4209716642000445 and parameters: {'alpha': 0.008428849956508474, 'l1_ratio': 0.4861130935432447}. Best is trial 0 with value: 0.4267588615082328.

✅ CAT con C2X-Complex_rhow_9x9_depth_in_3_4 - Mejor R2: 0.44
📋 Parámetros: {'iterations': 750, 'learning_rate': 0.03, 'depth': 8, 'l2_leaf_reg': 1.0255588829481326}

Buscando mejores hiperparámetros para ELN con C2X-Complex_rhow_9x9_depth_in_3_4...
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:37:01,613] Trial 2 finished with value: 0.36604689371260674 and parameters: {'alpha': 0.16879834566371532, 'l1_ratio': 0.7910168954995511}. Best is trial 0 with value: 0.4267588615082328.
[I 2025-09-08 21:37:01,674] Trial 3 finished with value: 0.37965117335693926 and parameters: {'alpha': 0.08483368173614726, 'l1_ratio': 0.8951741149454949}. Best is trial 0 with value: 0.4267588615082328.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.824e+01, tolerance: 4.779e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.411e+01, tolerance: 4.223e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.651e+01, tolerance: 3.136e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:37:01,753] Trial 4 finished with value: 0.42875212091357984 and parameters: {'alpha': 0.0017457384262861409, 'l1_ratio': 0.36192057254495524}. Best is trial 4 with value: 0.42875212091357984.
[I 2025-09-08 21:37:01,815] Trial 5 finished with value: 0.4105437597847405 and parameters: {'alpha': 0.023887105604748767, 'l1_ratio': 0.5135010146994149}. Best is trial 4 with value: 0.42875212091357984.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 21:37:01,882] Trial 6 finished with value: 0.4018015675507283 and parameters: {'alpha': 0.09681655067904041, 'l1_ratio': 0.19536484778134922}. Best is trial 4 with value: 0.42875212091357984.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.352e+01, tolerance: 4.779e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.361e+01, tolerance: 4.223e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.304e+01, tolerance: 3.136e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:37:01,962] Trial 7 finished with value: 0.4340524921592818 and parameters: {'alpha': 0.000250224656764823, 'l1_ratio': 0.5769747633789072}. Best is trial 7 with value: 0.4340524921592818.
[I 2025-09-08 21:37:02,025] Trial 8 finished with value: 0.21961700061573683 and parameters: {'alpha': 0.6512301414780978, 'l1_ratio': 0.7545965506564302}. Best is trial 7 with value: 0.4340524921592818.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 21:37:02,146] Trial 9 finished with value: 0.4087308947848416 and parameters: {'alpha': 0.04968372127053054, 'l1_ratio': 0.21807612143629554}. Best is trial 7 with value: 0.4340524921592818.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.031e+02, tolerance: 4.779e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.001e+01, tolerance: 4.223e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.863e+01, tolerance: 3.136e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:37:02,273] Trial 10 finished with value: 0.4340983730624371 and parameters: {'alpha': 0.000130207786508063, 'l1_ratio': 0.6294208258193146}. Best is trial 10 with value: 0.4340983730624371.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.031e+02, tolerance: 4.779e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.003e+01, tolerance: 4.223e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.866e+01, tolerance: 3.136e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:37:02,407] Trial 11 finished with value: 0.43408955449773895 and parameters: {'alpha': 0.00012906947387123464, 'l1_ratio': 0.6326351149134138}. Best is trial 10 with value: 0.4340983730624371.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.716e+01, tolerance: 4.779e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.575e+01, tolerance: 4.223e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.491e+01, tolerance: 3.136e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:37:02,523] Trial 12 finished with value: 0.4337057177283022 and parameters: {'alpha': 0.00018427377064885334, 'l1_ratio': 0.6758126298474584}. Best is trial 10 with value: 0.4340983730624371.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.058e+02, tolerance: 4.779e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.192e+01, tolerance: 4.223e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.036e+01, tolerance: 3.136e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:37:02,688] Trial 13 finished with value: 0.4341753354472872 and parameters: {'alpha': 0.00010018272227032154, 'l1_ratio': 0.6292794104903512}. Best is trial 13 with value: 0.4341753354472872.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.666e+01, tolerance: 4.779e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.165e+01, tolerance: 4.223e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.808e+01, tolerance: 3.136e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:37:02,827] Trial 14 finished with value: 0.4280827746249872 and parameters: {'alpha': 0.0007399900279498512, 'l1_ratio': 0.7105467146203424}. Best is trial 13 with value: 0.4341753354472872.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.592e+01, tolerance: 4.779e-02
  model = cd_fast.enet_coordinate_descent(

Fold 3
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.895e+01, tolerance: 4.223e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.916e+01, tolerance: 3.136e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:37:03,021] Trial 15 finished with value: 0.4261214494284949 and parameters: {'alpha': 0.0006426771524636271, 'l1_ratio': 0.8608992683777906}. Best is trial 13 with value: 0.4341753354472872.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.515e-01, tolerance: 4.779e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.548e-01, tolerance: 4.223e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.122e-02, tolerance: 3.136e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:37:03,145] Trial 16 finished with value: 0.4222705424526703 and parameters: {'alpha': 0.005203830623129798, 'l1_ratio': 0.5812841950464551}. Best is trial 13 with value: 0.4341753354472872.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.689e+01, tolerance: 4.779e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.957e+01, tolerance: 4.223e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.766e+01, tolerance: 3.136e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:37:03,243] Trial 17 finished with value: 0.43388699397858205 and parameters: {'alpha': 0.0004647993851362882, 'l1_ratio': 0.4430839715190597}. Best is trial 13 with value: 0.4341753354472872.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.099e+02, tolerance: 4.779e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.543e+01, tolerance: 4.223e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.325e+01, tolerance: 3.136e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:37:03,339] Trial 18 finished with value: 0.4351254799814018 and parameters: {'alpha': 0.00011461676043717124, 'l1_ratio': 0.3003141232321186}. Best is trial 18 with value: 0.4351254799814018.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.105e+01, tolerance: 4.779e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.208e+01, tolerance: 4.223e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.645e+01, tolerance: 3.136e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:37:03,432] Trial 19 finished with value: 0.4346639240120059 and parameters: {'alpha': 0.0020623022841637344, 'l1_ratio': 0.12058275555741993}. Best is trial 18 with value: 0.4351254799814018.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.636e+01, tolerance: 4.779e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.966e+01, tolerance: 4.223e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.216e+01, tolerance: 3.136e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:37:03,535] Trial 20 finished with value: 0.4331113412541421 and parameters: {'alpha': 0.002735666506095798, 'l1_ratio': 0.10966823851517571}. Best is trial 18 with value: 0.4351254799814018.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.588e+01, tolerance: 4.779e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.618e+01, tolerance: 4.223e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.358e+01, tolerance: 3.136e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:37:03,647] Trial 21 finished with value: 0.43575693016032285 and parameters: {'alpha': 0.0004115113393030161, 'l1_ratio': 0.3192525414333508}. Best is trial 21 with value: 0.43575693016032285.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.341e+01, tolerance: 4.779e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.840e+01, tolerance: 4.223e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.575e+01, tolerance: 3.136e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:37:03,750] Trial 22 finished with value: 0.4363220449851923 and parameters: {'alpha': 0.0003850351953426253, 'l1_ratio': 0.2827466640478364}. Best is trial 22 with value: 0.4363220449851923.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.484e+01, tolerance: 4.779e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.848e+01, tolerance: 4.223e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.610e+01, tolerance: 3.136e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:37:03,874] Trial 23 finished with value: 0.4361622010531508 and parameters: {'alpha': 0.00035830329114950005, 'l1_ratio': 0.29927070594744115}. Best is trial 22 with value: 0.4363220449851923.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.832e+01, tolerance: 4.779e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.759e+01, tolerance: 4.223e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.941e+01, tolerance: 3.136e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:37:03,999] Trial 24 finished with value: 0.4351153838767304 and parameters: {'alpha': 0.0008558903337434821, 'l1_ratio': 0.2890716913921769}. Best is trial 22 with value: 0.4363220449851923.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.296e+01, tolerance: 4.779e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.855e+01, tolerance: 4.223e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.574e+01, tolerance: 3.136e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:37:04,121] Trial 25 finished with value: 0.43644607616196396 and parameters: {'alpha': 0.00039949200470504586, 'l1_ratio': 0.27051324735442944}. Best is trial 25 with value: 0.43644607616196396.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.036e+02, tolerance: 4.779e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.322e+01, tolerance: 4.223e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.035e+01, tolerance: 3.136e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:37:04,247] Trial 26 finished with value: 0.43664360429782206 and parameters: {'alpha': 0.0003007578938360893, 'l1_ratio': 0.2069928159482579}. Best is trial 26 with value: 0.43664360429782206.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.015e+01, tolerance: 4.779e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.756e+01, tolerance: 4.223e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.553e+01, tolerance: 3.136e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:37:04,343] Trial 27 finished with value: 0.4360722164633802 and parameters: {'alpha': 0.0011433052717487416, 'l1_ratio': 0.20169974621489373}. Best is trial 26 with value: 0.43664360429782206.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.285e+01, tolerance: 4.779e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.335e+01, tolerance: 4.223e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.749e+01, tolerance: 3.136e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:37:04,472] Trial 28 finished with value: 0.42970179892167454 and parameters: {'alpha': 0.0038080385511706236, 'l1_ratio': 0.2281263987045733}. Best is trial 26 with value: 0.43664360429782206.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 21:37:04,648] Trial 29 finished with value: 0.41497460569619465 and parameters: {'alpha': 0.020311508258433822, 'l1_ratio': 0.3979689681452317}. Best is trial 26 with value: 0.43664360429782206.
[I 2025-09-08 21:37:04,650] A new study created in memory with name: no-name-29cc4202-1fae-4285-b642-2cb313c547bb

Fold 3

✅ ELN con C2X-Complex_rhow_9x9_depth_in_3_4 - Mejor R2: 0.44
📋 Parámetros: {'alpha': 0.0003007578938360893, 'l1_ratio': 0.2069928159482579}

Buscando mejores hiperparámetros para XGB con C2X-Complex_rhow_15x15_depth_in_3_4...
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:37:10,278] Trial 0 finished with value: 0.44656668972023317 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.6150111463818903, 'colsample_bytree': 0.6840058914065439}. Best is trial 0 with value: 0.44656668972023317.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:37:14,428] Trial 1 finished with value: 0.44097718348852416 and parameters: {'n_estimators': 750, 'learning_rate': 0.01, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.7720459790530778, 'colsample_bytree': 0.7404682182703881}. Best is trial 0 with value: 0.44656668972023317.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:37:20,431] Trial 2 finished with value: 0.4066819028272158 and parameters: {'n_estimators': 1250, 'learning_rate': 0.02, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.7450979717374794, 'colsample_bytree': 0.7535202225141452}. Best is trial 0 with value: 0.44656668972023317.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:37:25,010] Trial 3 finished with value: 0.416904876563539 and parameters: {'n_estimators': 1000, 'learning_rate': 0.03, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.7847210432868565, 'colsample_bytree': 0.7164835998693816}. Best is trial 0 with value: 0.44656668972023317.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:37:32,368] Trial 4 finished with value: 0.4171017440373981 and parameters: {'n_estimators': 1250, 'learning_rate': 0.02, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.7948509077722649, 'colsample_bytree': 0.6727643055473741}. Best is trial 0 with value: 0.44656668972023317.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:37:37,852] Trial 5 finished with value: 0.3994718483201085 and parameters: {'n_estimators': 1250, 'learning_rate': 0.01, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.7430005031610267, 'colsample_bytree': 0.6365242420339233}. Best is trial 0 with value: 0.44656668972023317.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:37:42,658] Trial 6 finished with value: 0.4520322256433313 and parameters: {'n_estimators': 1000, 'learning_rate': 0.03, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.7533472868027209, 'colsample_bytree': 0.6724550238369584}. Best is trial 6 with value: 0.4520322256433313.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:37:46,433] Trial 7 finished with value: 0.3554960549900749 and parameters: {'n_estimators': 750, 'learning_rate': 0.03, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.6260048998743563, 'colsample_bytree': 0.6352933286924383}. Best is trial 6 with value: 0.4520322256433313.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:37:54,231] Trial 8 finished with value: 0.4381873577967403 and parameters: {'n_estimators': 1250, 'learning_rate': 0.03, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.6174485736235344, 'colsample_bytree': 0.7539018222565357}. Best is trial 6 with value: 0.4520322256433313.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:37:59,194] Trial 9 finished with value: 0.4481142901736846 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.6817448931621376, 'colsample_bytree': 0.6419857870144691}. Best is trial 6 with value: 0.4520322256433313.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:38:06,701] Trial 10 finished with value: 0.4312561898978726 and parameters: {'n_estimators': 1000, 'learning_rate': 0.03, 'max_depth': 8, 'min_child_weight': 2, 'subsample': 0.6947279961507101, 'colsample_bytree': 0.7985077809601889}. Best is trial 6 with value: 0.4520322256433313.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:38:11,017] Trial 11 finished with value: 0.45475388692224455 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.6821385201336727, 'colsample_bytree': 0.6027539313982617}. Best is trial 11 with value: 0.45475388692224455.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:38:15,620] Trial 12 finished with value: 0.4431439654991481 and parameters: {'n_estimators': 1000, 'learning_rate': 0.03, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.6621722947399342, 'colsample_bytree': 0.6034875602714912}. Best is trial 11 with value: 0.45475388692224455.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:38:20,034] Trial 13 finished with value: 0.4503928899299896 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.7399482121896817, 'colsample_bytree': 0.6113225007871306}. Best is trial 11 with value: 0.45475388692224455.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:38:25,004] Trial 14 finished with value: 0.4523424997602618 and parameters: {'n_estimators': 1000, 'learning_rate': 0.02, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.6597929956840688, 'colsample_bytree': 0.6649574756377917}. Best is trial 11 with value: 0.45475388692224455.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:38:29,107] Trial 15 finished with value: 0.42620122211883044 and parameters: {'n_estimators': 1000, 'learning_rate': 0.02, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.6607650591241719, 'colsample_bytree': 0.6534043356737876}. Best is trial 11 with value: 0.45475388692224455.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:38:34,870] Trial 16 finished with value: 0.4328924369616797 and parameters: {'n_estimators': 750, 'learning_rate': 0.02, 'max_depth': 8, 'min_child_weight': 2, 'subsample': 0.6489752236693388, 'colsample_bytree': 0.711847214361619}. Best is trial 11 with value: 0.45475388692224455.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:38:38,636] Trial 17 finished with value: 0.3899504192426848 and parameters: {'n_estimators': 1000, 'learning_rate': 0.02, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.7118423805105215, 'colsample_bytree': 0.61950520214571}. Best is trial 11 with value: 0.45475388692224455.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:38:43,180] Trial 18 finished with value: 0.4470183124158425 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.6378313602594116, 'colsample_bytree': 0.6585435057952667}. Best is trial 11 with value: 0.45475388692224455.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:38:46,962] Trial 19 finished with value: 0.4236989154739505 and parameters: {'n_estimators': 750, 'learning_rate': 0.02, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.7156656646272513, 'colsample_bytree': 0.6911883024475518}. Best is trial 11 with value: 0.45475388692224455.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:38:51,526] Trial 20 finished with value: 0.45702488180582784 and parameters: {'n_estimators': 1000, 'learning_rate': 0.02, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.6772862339754507, 'colsample_bytree': 0.6252048263540031}. Best is trial 20 with value: 0.45702488180582784.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:38:56,043] Trial 21 finished with value: 0.45923450626073076 and parameters: {'n_estimators': 1000, 'learning_rate': 0.02, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.6790743343341125, 'colsample_bytree': 0.6230537358111669}. Best is trial 21 with value: 0.45923450626073076.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:39:00,715] Trial 22 finished with value: 0.46179721465945534 and parameters: {'n_estimators': 1000, 'learning_rate': 0.02, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.6787613169148017, 'colsample_bytree': 0.6225837064437524}. Best is trial 22 with value: 0.46179721465945534.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:39:04,873] Trial 23 finished with value: 0.4473743149681983 and parameters: {'n_estimators': 1000, 'learning_rate': 0.02, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.6791712359813767, 'colsample_bytree': 0.6258290395437086}. Best is trial 22 with value: 0.46179721465945534.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:39:10,209] Trial 24 finished with value: 0.449258611037002 and parameters: {'n_estimators': 1000, 'learning_rate': 0.02, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.7118910773666783, 'colsample_bytree': 0.6468850265015443}. Best is trial 22 with value: 0.46179721465945534.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:39:14,296] Trial 25 finished with value: 0.4187351446835397 and parameters: {'n_estimators': 1000, 'learning_rate': 0.02, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.6947604414608017, 'colsample_bytree': 0.6240291707765931}. Best is trial 22 with value: 0.46179721465945534.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:39:19,467] Trial 26 finished with value: 0.4616087513549226 and parameters: {'n_estimators': 1000, 'learning_rate': 0.02, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.6399097407895042, 'colsample_bytree': 0.6227935492527134}. Best is trial 22 with value: 0.46179721465945534.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:39:25,364] Trial 27 finished with value: 0.43995803999408684 and parameters: {'n_estimators': 1000, 'learning_rate': 0.02, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.6012216280259352, 'colsample_bytree': 0.6019103880190326}. Best is trial 22 with value: 0.46179721465945534.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:39:28,821] Trial 28 finished with value: 0.4142145423042547 and parameters: {'n_estimators': 750, 'learning_rate': 0.02, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.6370497322432399, 'colsample_bytree': 0.6478126513849018}. Best is trial 22 with value: 0.46179721465945534.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:39:35,520] Trial 29 finished with value: 0.4339490365082653 and parameters: {'n_estimators': 1250, 'learning_rate': 0.02, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.6432661669136394, 'colsample_bytree': 0.6856829337241832}. Best is trial 22 with value: 0.46179721465945534.
[I 2025-09-08 21:39:35,522] A new study created in memory with name: no-name-c57c7c94-0a74-4fe7-93cb-55b771017002

✅ XGB con C2X-Complex_rhow_15x15_depth_in_3_4 - Mejor R2: 0.46
📋 Parámetros: {'n_estimators': 1000, 'learning_rate': 0.02, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.6787613169148017, 'colsample_bytree': 0.6225837064437524}

Buscando mejores hiperparámetros para LBM con C2X-Complex_rhow_15x15_depth_in_3_4...
Fold 1
Fold 2

[I 2025-09-08 21:39:35,909] Trial 0 finished with value: 0.42910840585262644 and parameters: {'learning_rate': 0.03, 'num_leaves': 30, 'max_depth': 7, 'min_child_samples': 4, 'subsample': 0.6586671401156625, 'colsample_bytree': 0.7423650198961539, 'n_estimators': 750, 'min_split_gain': 0.0}. Best is trial 0 with value: 0.42910840585262644.

Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:39:36,442] Trial 1 finished with value: 0.3022437413255306 and parameters: {'learning_rate': 0.04, 'num_leaves': 20, 'max_depth': 8, 'min_child_samples': 7, 'subsample': 0.7778032415944575, 'colsample_bytree': 0.6034299249584812, 'n_estimators': 1250, 'min_split_gain': 0.0}. Best is trial 0 with value: 0.42910840585262644.
[I 2025-09-08 21:39:36,607] Trial 2 finished with value: 0.3928042855853399 and parameters: {'learning_rate': 0.02, 'num_leaves': 10, 'max_depth': 5, 'min_child_samples': 7, 'subsample': 0.6469381737014874, 'colsample_bytree': 0.7588746562159231, 'n_estimators': 1000, 'min_split_gain': 1.0}. Best is trial 0 with value: 0.42910840585262644.

Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 21:39:36,752] Trial 3 finished with value: 0.4003964947949005 and parameters: {'learning_rate': 0.04, 'num_leaves': 10, 'max_depth': 5, 'min_child_samples': 7, 'subsample': 0.6317770840308888, 'colsample_bytree': 0.694874513479577, 'n_estimators': 1000, 'min_split_gain': 0.5}. Best is trial 0 with value: 0.42910840585262644.

Fold 2
Fold 3
Fold 1

[I 2025-09-08 21:39:36,987] Trial 4 finished with value: 0.3752920594141327 and parameters: {'learning_rate': 0.04, 'num_leaves': 30, 'max_depth': 7, 'min_child_samples': 6, 'subsample': 0.7985907268266427, 'colsample_bytree': 0.6215749000444111, 'n_estimators': 1000, 'min_split_gain': 0.2}. Best is trial 0 with value: 0.42910840585262644.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:39:37,359] Trial 5 finished with value: 0.43142829582855247 and parameters: {'learning_rate': 0.05, 'num_leaves': 10, 'max_depth': 6, 'min_child_samples': 4, 'subsample': 0.6139946024740897, 'colsample_bytree': 0.6898488740307751, 'n_estimators': 1000, 'min_split_gain': 0.0}. Best is trial 5 with value: 0.43142829582855247.
[I 2025-09-08 21:39:37,504] Trial 6 finished with value: 0.4258735721040705 and parameters: {'learning_rate': 0.04, 'num_leaves': 10, 'max_depth': 8, 'min_child_samples': 5, 'subsample': 0.665711808568405, 'colsample_bytree': 0.7388961334208631, 'n_estimators': 1250, 'min_split_gain': 1.0}. Best is trial 5 with value: 0.43142829582855247.

Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 21:39:37,738] Trial 7 finished with value: 0.40905743796901534 and parameters: {'learning_rate': 0.03, 'num_leaves': 10, 'max_depth': 5, 'min_child_samples': 8, 'subsample': 0.6197028184787939, 'colsample_bytree': 0.6607549345769651, 'n_estimators': 750, 'min_split_gain': 0.0}. Best is trial 5 with value: 0.43142829582855247.

Fold 2
Fold 3
Fold 1

[I 2025-09-08 21:39:37,981] Trial 8 finished with value: 0.39971105135797275 and parameters: {'learning_rate': 0.02, 'num_leaves': 10, 'max_depth': 8, 'min_child_samples': 5, 'subsample': 0.6794798706467036, 'colsample_bytree': 0.7019908494434453, 'n_estimators': 1000, 'min_split_gain': 0.1}. Best is trial 5 with value: 0.43142829582855247.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:39:38,378] Trial 9 finished with value: 0.42462427562269117 and parameters: {'learning_rate': 0.05, 'num_leaves': 10, 'max_depth': 7, 'min_child_samples': 4, 'subsample': 0.7185525270120908, 'colsample_bytree': 0.784391594744215, 'n_estimators': 1000, 'min_split_gain': 0.0}. Best is trial 5 with value: 0.43142829582855247.
[I 2025-09-08 21:39:38,525] Trial 10 finished with value: 0.41788443612764276 and parameters: {'learning_rate': 0.05, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 5, 'subsample': 0.7157713223565868, 'colsample_bytree': 0.661942679727312, 'n_estimators': 750, 'min_split_gain': 0.1}. Best is trial 5 with value: 0.43142829582855247.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:39:38,906] Trial 11 finished with value: 0.4209750625881254 and parameters: {'learning_rate': 0.03, 'num_leaves': 30, 'max_depth': 6, 'min_child_samples': 4, 'subsample': 0.6055481685113487, 'colsample_bytree': 0.719327118219891, 'n_estimators': 750, 'min_split_gain': 0.0}. Best is trial 5 with value: 0.43142829582855247.

Fold 1
Fold 2

[I 2025-09-08 21:39:39,329] Trial 12 finished with value: 0.4130277353555553 and parameters: {'learning_rate': 0.03, 'num_leaves': 30, 'max_depth': 7, 'min_child_samples': 4, 'subsample': 0.6814419233528235, 'colsample_bytree': 0.7955160570035003, 'n_estimators': 750, 'min_split_gain': 0.0}. Best is trial 5 with value: 0.43142829582855247.

Fold 3
Fold 1
Fold 2

[I 2025-09-08 21:39:39,460] Trial 13 finished with value: 0.4011392377978304 and parameters: {'learning_rate': 0.05, 'num_leaves': 30, 'max_depth': 6, 'min_child_samples': 4, 'subsample': 0.6406869487217696, 'colsample_bytree': 0.6615801417029359, 'n_estimators': 750, 'min_split_gain': 0.5}. Best is trial 5 with value: 0.43142829582855247.

Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:39:39,665] Trial 14 finished with value: 0.4057351766593367 and parameters: {'learning_rate': 0.03, 'num_leaves': 30, 'max_depth': 6, 'min_child_samples': 5, 'subsample': 0.6017430943650098, 'colsample_bytree': 0.7535862704570373, 'n_estimators': 1250, 'min_split_gain': 0.2}. Best is trial 5 with value: 0.43142829582855247.

Fold 1
Fold 2

[I 2025-09-08 21:39:40,153] Trial 15 finished with value: 0.36904403216679577 and parameters: {'learning_rate': 0.05, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 6, 'subsample': 0.6595231113854922, 'colsample_bytree': 0.6926121985676645, 'n_estimators': 1000, 'min_split_gain': 0.0}. Best is trial 5 with value: 0.43142829582855247.

Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:39:40,567] Trial 16 finished with value: 0.42336674602646274 and parameters: {'learning_rate': 0.03, 'num_leaves': 30, 'max_depth': 7, 'min_child_samples': 4, 'subsample': 0.7467922864781527, 'colsample_bytree': 0.7239703233539091, 'n_estimators': 750, 'min_split_gain': 0.0}. Best is trial 5 with value: 0.43142829582855247.

Fold 1
Fold 2

[I 2025-09-08 21:39:40,954] Trial 17 finished with value: 0.3982115816086538 and parameters: {'learning_rate': 0.05, 'num_leaves': 10, 'max_depth': 6, 'min_child_samples': 5, 'subsample': 0.6941562650050754, 'colsample_bytree': 0.7694184112386451, 'n_estimators': 1000, 'min_split_gain': 0.0}. Best is trial 5 with value: 0.43142829582855247.

Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:39:41,259] Trial 18 finished with value: 0.38958644562108274 and parameters: {'learning_rate': 0.02, 'num_leaves': 30, 'max_depth': 6, 'min_child_samples': 6, 'subsample': 0.6327992835187778, 'colsample_bytree': 0.6746070347231773, 'n_estimators': 750, 'min_split_gain': 0.1}. Best is trial 5 with value: 0.43142829582855247.
[I 2025-09-08 21:39:41,408] Trial 19 finished with value: 0.4125758410650658 and parameters: {'learning_rate': 0.05, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 4, 'subsample': 0.6182670083861939, 'colsample_bytree': 0.6338074066733316, 'n_estimators': 1250, 'min_split_gain': 0.5}. Best is trial 5 with value: 0.43142829582855247.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 21:39:41,604] Trial 20 finished with value: 0.38735264941576464 and parameters: {'learning_rate': 0.03, 'num_leaves': 30, 'max_depth': 5, 'min_child_samples': 6, 'subsample': 0.6581963677408624, 'colsample_bytree': 0.7289941166074563, 'n_estimators': 1000, 'min_split_gain': 0.2}. Best is trial 5 with value: 0.43142829582855247.
[I 2025-09-08 21:39:41,748] Trial 21 finished with value: 0.4258735721040705 and parameters: {'learning_rate': 0.04, 'num_leaves': 10, 'max_depth': 8, 'min_child_samples': 5, 'subsample': 0.6701675626723645, 'colsample_bytree': 0.7395458582428033, 'n_estimators': 1250, 'min_split_gain': 1.0}. Best is trial 5 with value: 0.43142829582855247.

Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:39:41,898] Trial 22 finished with value: 0.43131998379933095 and parameters: {'learning_rate': 0.04, 'num_leaves': 10, 'max_depth': 8, 'min_child_samples': 5, 'subsample': 0.6968812113539428, 'colsample_bytree': 0.7428022469007307, 'n_estimators': 1250, 'min_split_gain': 1.0}. Best is trial 5 with value: 0.43142829582855247.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 21:39:42,083] Trial 23 finished with value: 0.44198025348792847 and parameters: {'learning_rate': 0.04, 'num_leaves': 10, 'max_depth': 8, 'min_child_samples': 4, 'subsample': 0.7161148105781019, 'colsample_bytree': 0.7094964257149129, 'n_estimators': 1250, 'min_split_gain': 1.0}. Best is trial 23 with value: 0.44198025348792847.

Fold 3
Fold 1
Fold 2

[I 2025-09-08 21:39:42,261] Trial 24 finished with value: 0.4316779289790949 and parameters: {'learning_rate': 0.04, 'num_leaves': 10, 'max_depth': 8, 'min_child_samples': 5, 'subsample': 0.7438117439921702, 'colsample_bytree': 0.706070261415492, 'n_estimators': 1250, 'min_split_gain': 1.0}. Best is trial 23 with value: 0.44198025348792847.
[I 2025-09-08 21:39:42,413] Trial 25 finished with value: 0.44198025348792847 and parameters: {'learning_rate': 0.04, 'num_leaves': 10, 'max_depth': 8, 'min_child_samples': 4, 'subsample': 0.744545274847118, 'colsample_bytree': 0.7101503609986796, 'n_estimators': 1250, 'min_split_gain': 1.0}. Best is trial 23 with value: 0.44198025348792847.

Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:39:42,557] Trial 26 finished with value: 0.4316779289790949 and parameters: {'learning_rate': 0.04, 'num_leaves': 10, 'max_depth': 8, 'min_child_samples': 5, 'subsample': 0.7487742265130518, 'colsample_bytree': 0.710670756168164, 'n_estimators': 1250, 'min_split_gain': 1.0}. Best is trial 23 with value: 0.44198025348792847.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 21:39:42,706] Trial 27 finished with value: 0.44198025348792847 and parameters: {'learning_rate': 0.04, 'num_leaves': 10, 'max_depth': 8, 'min_child_samples': 4, 'subsample': 0.7417106635447567, 'colsample_bytree': 0.7077187927481547, 'n_estimators': 1250, 'min_split_gain': 1.0}. Best is trial 23 with value: 0.44198025348792847.
[I 2025-09-08 21:39:42,858] Trial 28 finished with value: 0.441969642619166 and parameters: {'learning_rate': 0.04, 'num_leaves': 10, 'max_depth': 8, 'min_child_samples': 4, 'subsample': 0.7281194022779137, 'colsample_bytree': 0.6886028577106598, 'n_estimators': 1250, 'min_split_gain': 1.0}. Best is trial 23 with value: 0.44198025348792847.

Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:39:43,002] Trial 29 finished with value: 0.44471870693271215 and parameters: {'learning_rate': 0.04, 'num_leaves': 10, 'max_depth': 8, 'min_child_samples': 4, 'subsample': 0.7601466359380711, 'colsample_bytree': 0.676322608638828, 'n_estimators': 1250, 'min_split_gain': 1.0}. Best is trial 29 with value: 0.44471870693271215.
[I 2025-09-08 21:39:43,004] A new study created in memory with name: no-name-b3cf867b-efa2-47c1-ae31-592cfc911d6d
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

✅ LBM con C2X-Complex_rhow_15x15_depth_in_3_4 - Mejor R2: 0.44
📋 Parámetros: {'learning_rate': 0.04, 'num_leaves': 10, 'max_depth': 8, 'min_child_samples': 4, 'subsample': 0.7601466359380711, 'colsample_bytree': 0.676322608638828, 'n_estimators': 1250, 'min_split_gain': 1.0}

Buscando mejores hiperparámetros para MLP con C2X-Complex_rhow_15x15_depth_in_3_4...
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 21:39:44,561] Trial 0 finished with value: 0.40417004746715923 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'sgd', 'alpha': 1.9534647633073085e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.0008816404390272951}. Best is trial 0 with value: 0.40417004746715923.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 21:39:45,867] Trial 1 finished with value: 0.453752119118197 and parameters: {'hidden_layer_sizes': (128,), 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.00034527159729126806, 'learning_rate': 'constant', 'learning_rate_init': 0.002737253517739048}. Best is trial 1 with value: 0.453752119118197.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2

[I 2025-09-08 21:39:46,585] Trial 2 finished with value: 0.40927872872196575 and parameters: {'hidden_layer_sizes': (64,), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0010767533066885129, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0017616505106684754}. Best is trial 1 with value: 0.453752119118197.

Fold 3
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 21:39:47,941] Trial 3 finished with value: 0.3678690388822696 and parameters: {'hidden_layer_sizes': (64,), 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.0006064357977385883, 'learning_rate': 'constant', 'learning_rate_init': 0.00038285019239117055}. Best is trial 1 with value: 0.453752119118197.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 21:39:49,002] Trial 4 finished with value: 0.2823397525054903 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.03679396847604369, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00011111751954123072}. Best is trial 1 with value: 0.453752119118197.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 21:39:49,795] Trial 5 finished with value: 0.41682321607675865 and parameters: {'hidden_layer_sizes': (32,), 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.0005430327600098185, 'learning_rate': 'constant', 'learning_rate_init': 0.003711427526490003}. Best is trial 1 with value: 0.453752119118197.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 3
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 21:39:50,861] Trial 6 finished with value: 0.49895356862220397 and parameters: {'hidden_layer_sizes': (128,), 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0011134883614907273, 'learning_rate': 'constant', 'learning_rate_init': 0.002901275919308721}. Best is trial 6 with value: 0.49895356862220397.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 21:39:51,808] Trial 7 finished with value: 0.40915523418979055 and parameters: {'hidden_layer_sizes': (32,), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.014163541063203614, 'learning_rate': 'constant', 'learning_rate_init': 0.00042187148268940064}. Best is trial 6 with value: 0.49895356862220397.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2

[I 2025-09-08 21:39:52,309] Trial 8 finished with value: 0.4065444425056704 and parameters: {'hidden_layer_sizes': (64,), 'activation': 'tanh', 'solver': 'adam', 'alpha': 1.7639946598644092e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00351969327802434}. Best is trial 6 with value: 0.49895356862220397.

Fold 3
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

[I 2025-09-08 21:39:53,459] Trial 9 finished with value: 0.4102886475353678 and parameters: {'hidden_layer_sizes': (64,), 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.00028244304128273776, 'learning_rate': 'constant', 'learning_rate_init': 0.0020144327356717393}. Best is trial 6 with value: 0.49895356862220397.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:39:54,283] Trial 10 finished with value: 0.5255603098708539 and parameters: {'hidden_layer_sizes': (128,), 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0038022555774314113, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00680278123816466}. Best is trial 10 with value: 0.5255603098708539.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:39:55,099] Trial 11 finished with value: 0.5350904823225032 and parameters: {'hidden_layer_sizes': (128,), 'activation': 'relu', 'solver': 'adam', 'alpha': 0.004235390097738461, 'learning_rate': 'adaptive', 'learning_rate_init': 0.007038924308627167}. Best is trial 11 with value: 0.5350904823225032.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:39:55,821] Trial 12 finished with value: 0.49560157852506376 and parameters: {'hidden_layer_sizes': (128,), 'activation': 'relu', 'solver': 'adam', 'alpha': 0.006138803076031521, 'learning_rate': 'adaptive', 'learning_rate_init': 0.009200873792909296}. Best is trial 11 with value: 0.5350904823225032.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:39:56,753] Trial 13 finished with value: 0.4933609353436312 and parameters: {'hidden_layer_sizes': (128,), 'activation': 'relu', 'solver': 'adam', 'alpha': 0.004434304067366242, 'learning_rate': 'adaptive', 'learning_rate_init': 0.008758951975695432}. Best is trial 11 with value: 0.5350904823225032.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:39:57,517] Trial 14 finished with value: 0.5210107853436687 and parameters: {'hidden_layer_sizes': (128,), 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0716850914407771, 'learning_rate': 'adaptive', 'learning_rate_init': 0.006457574529807749}. Best is trial 11 with value: 0.5350904823225032.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:39:58,407] Trial 15 finished with value: 0.5179773072399821 and parameters: {'hidden_layer_sizes': (128,), 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0039151553950442855, 'learning_rate': 'adaptive', 'learning_rate_init': 0.004836666582021817}. Best is trial 11 with value: 0.5350904823225032.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 21:39:59,563] Trial 16 finished with value: 0.5174848052255036 and parameters: {'hidden_layer_sizes': (128,), 'activation': 'relu', 'solver': 'adam', 'alpha': 8.012940755499646e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0010347195189510446}. Best is trial 11 with value: 0.5350904823225032.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:40:00,287] Trial 17 finished with value: 0.5223545505847441 and parameters: {'hidden_layer_sizes': (128,), 'activation': 'relu', 'solver': 'adam', 'alpha': 0.018053885197309532, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0056176778453188615}. Best is trial 11 with value: 0.5350904823225032.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2

[I 2025-09-08 21:40:00,936] Trial 18 finished with value: 0.4111879680783208 and parameters: {'hidden_layer_sizes': (32,), 'activation': 'relu', 'solver': 'adam', 'alpha': 0.002007623648814597, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0011416631202981835}. Best is trial 11 with value: 0.5350904823225032.

Fold 3
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 21:40:02,166] Trial 19 finished with value: 0.42320132397339244 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'relu', 'solver': 'adam', 'alpha': 0.011078607593984924, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0004856215421428858}. Best is trial 11 with value: 0.5350904823225032.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 21:40:03,479] Trial 20 finished with value: 0.4365775838436321 and parameters: {'hidden_layer_sizes': (128,), 'activation': 'relu', 'solver': 'adam', 'alpha': 9.59796566978059e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00013623188072823443}. Best is trial 11 with value: 0.5350904823225032.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:40:04,300] Trial 21 finished with value: 0.5349329677250686 and parameters: {'hidden_layer_sizes': (128,), 'activation': 'relu', 'solver': 'adam', 'alpha': 0.02182735564756428, 'learning_rate': 'adaptive', 'learning_rate_init': 0.005956958891291296}. Best is trial 11 with value: 0.5350904823225032.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:40:05,239] Trial 22 finished with value: 0.5170709843627027 and parameters: {'hidden_layer_sizes': (128,), 'activation': 'relu', 'solver': 'adam', 'alpha': 0.03347659935143988, 'learning_rate': 'adaptive', 'learning_rate_init': 0.006423971766817025}. Best is trial 11 with value: 0.5350904823225032.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:40:06,013] Trial 23 finished with value: 0.4876235741917487 and parameters: {'hidden_layer_sizes': (128,), 'activation': 'relu', 'solver': 'adam', 'alpha': 0.002806121263228147, 'learning_rate': 'adaptive', 'learning_rate_init': 0.009264913671419137}. Best is trial 11 with value: 0.5350904823225032.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

[I 2025-09-08 21:40:06,980] Trial 24 finished with value: 0.5162703908429661 and parameters: {'hidden_layer_sizes': (128,), 'activation': 'relu', 'solver': 'adam', 'alpha': 0.00923715565550471, 'learning_rate': 'adaptive', 'learning_rate_init': 0.004497239900021721}. Best is trial 11 with value: 0.5350904823225032.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 21:40:08,088] Trial 25 finished with value: 0.5102881917280412 and parameters: {'hidden_layer_sizes': (128,), 'activation': 'relu', 'solver': 'adam', 'alpha': 0.08029403253351851, 'learning_rate': 'adaptive', 'learning_rate_init': 0.001876805295874978}. Best is trial 11 with value: 0.5350904823225032.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:40:08,831] Trial 26 finished with value: 0.5191909542069464 and parameters: {'hidden_layer_sizes': (128,), 'activation': 'relu', 'solver': 'adam', 'alpha': 0.03153352666242927, 'learning_rate': 'adaptive', 'learning_rate_init': 0.006992455187763378}. Best is trial 11 with value: 0.5350904823225032.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2

[I 2025-09-08 21:40:09,339] Trial 27 finished with value: 0.4357336090431067 and parameters: {'hidden_layer_sizes': (32,), 'activation': 'relu', 'solver': 'adam', 'alpha': 0.001999258052360745, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00421259933522784}. Best is trial 11 with value: 0.5350904823225032.

Fold 3
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 21:40:10,529] Trial 28 finished with value: 0.4329113426208567 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'relu', 'solver': 'adam', 'alpha': 0.007024267298508625, 'learning_rate': 'adaptive', 'learning_rate_init': 0.002745706142992152}. Best is trial 11 with value: 0.5350904823225032.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 21:40:11,786] Trial 29 finished with value: 0.4165532736199767 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.020457702953434333, 'learning_rate': 'adaptive', 'learning_rate_init': 0.001349801986486479}. Best is trial 11 with value: 0.5350904823225032.
[I 2025-09-08 21:40:11,788] A new study created in memory with name: no-name-22448b51-b673-439e-a8c4-c419ededa489
[I 2025-09-08 21:40:11,857] Trial 0 finished with value: 0.37359372354905934 and parameters: {'C': 0.45574598943296846, 'epsilon': 0.16892115739499416}. Best is trial 0 with value: 0.37359372354905934.
[I 2025-09-08 21:40:11,915] Trial 1 finished with value: 0.5132734734522598 and parameters: {'C': 8.216919343827403, 'epsilon': 0.15004040266284246}. Best is trial 1 with value: 0.5132734734522598.
[I 2025-09-08 21:40:11,965] Trial 2 finished with value: 0.43475072668217735 and parameters: {'C': 1.0805548439822104, 'epsilon': 0.11885777604819776}. Best is trial 1 with value: 0.5132734734522598.

✅ MLP con C2X-Complex_rhow_15x15_depth_in_3_4 - Mejor R2: 0.54
📋 Parámetros: {'hidden_layer_sizes': (128,), 'activation': 'relu', 'solver': 'adam', 'alpha': 0.004235390097738461, 'learning_rate': 'adaptive', 'learning_rate_init': 0.007038924308627167}

Buscando mejores hiperparámetros para SVR con C2X-Complex_rhow_15x15_depth_in_3_4...
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 21:40:12,014] Trial 3 finished with value: 0.3584686955764001 and parameters: {'C': 0.3796495255264597, 'epsilon': 0.17594928167788434}. Best is trial 1 with value: 0.5132734734522598.
[I 2025-09-08 21:40:12,069] Trial 4 finished with value: 0.34802092335527113 and parameters: {'C': 0.27956477848574046, 'epsilon': 0.04366889501378317}. Best is trial 1 with value: 0.5132734734522598.
[I 2025-09-08 21:40:12,128] Trial 5 finished with value: 0.448189897103793 and parameters: {'C': 1.6825203799526294, 'epsilon': 0.038092009983592294}. Best is trial 1 with value: 0.5132734734522598.
[I 2025-09-08 21:40:12,177] Trial 6 finished with value: 0.4492262914784883 and parameters: {'C': 1.5828362518575632, 'epsilon': 0.08622205682850731}. Best is trial 1 with value: 0.5132734734522598.

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 21:40:12,228] Trial 7 finished with value: 0.41048814919661264 and parameters: {'C': 0.7541338877256288, 'epsilon': 0.18914910415751465}. Best is trial 1 with value: 0.5132734734522598.
[I 2025-09-08 21:40:12,280] Trial 8 finished with value: 0.35924126204710305 and parameters: {'C': 0.35333548295012723, 'epsilon': 0.1217298081493816}. Best is trial 1 with value: 0.5132734734522598.
[I 2025-09-08 21:40:12,344] Trial 9 finished with value: 0.3467106711053522 and parameters: {'C': 0.2833322195015588, 'epsilon': 0.13128163132202675}. Best is trial 1 with value: 0.5132734734522598.

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:40:12,428] Trial 10 finished with value: 0.5132124427748307 and parameters: {'C': 8.152764822491717, 'epsilon': 0.07938014055392295}. Best is trial 1 with value: 0.5132734734522598.
[I 2025-09-08 21:40:12,499] Trial 11 finished with value: 0.5152323611581394 and parameters: {'C': 9.060291906665672, 'epsilon': 0.07977499768461056}. Best is trial 11 with value: 0.5152323611581394.
[I 2025-09-08 21:40:12,564] Trial 12 finished with value: 0.5136356843723069 and parameters: {'C': 8.501875283808566, 'epsilon': 0.14993467440635744}. Best is trial 11 with value: 0.5152323611581394.
[I 2025-09-08 21:40:12,624] Trial 13 finished with value: 0.49008697236505644 and parameters: {'C': 4.331073864005014, 'epsilon': 0.07854284778661674}. Best is trial 11 with value: 0.5152323611581394.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 21:40:12,685] Trial 14 finished with value: 0.2490488798034286 and parameters: {'C': 0.10919400645785836, 'epsilon': 0.01260431462333736}. Best is trial 11 with value: 0.5152323611581394.
[I 2025-09-08 21:40:12,749] Trial 15 finished with value: 0.48965108287917175 and parameters: {'C': 4.060412541256, 'epsilon': 0.10190167474969568}. Best is trial 11 with value: 0.5152323611581394.
[I 2025-09-08 21:40:12,810] Trial 16 finished with value: 0.49418008845482225 and parameters: {'C': 4.082961367811499, 'epsilon': 0.15014522477587944}. Best is trial 11 with value: 0.5152323611581394.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:40:12,873] Trial 17 finished with value: 0.5163133338225094 and parameters: {'C': 9.740076562335307, 'epsilon': 0.04684900615162051}. Best is trial 17 with value: 0.5163133338225094.
[I 2025-09-08 21:40:12,940] Trial 18 finished with value: 0.46952268709614237 and parameters: {'C': 2.5379150415685423, 'epsilon': 0.0557578381871709}. Best is trial 17 with value: 0.5163133338225094.
[I 2025-09-08 21:40:13,028] Trial 19 finished with value: 0.4952547233259754 and parameters: {'C': 5.50473119892222, 'epsilon': 0.016092795525000547}. Best is trial 17 with value: 0.5163133338225094.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:40:13,095] Trial 20 finished with value: 0.4727753079048518 and parameters: {'C': 2.9203016912673205, 'epsilon': 0.06317372239878224}. Best is trial 17 with value: 0.5163133338225094.
[I 2025-09-08 21:40:13,162] Trial 21 finished with value: 0.5152967806577634 and parameters: {'C': 9.265002947472844, 'epsilon': 0.09921663444738942}. Best is trial 17 with value: 0.5163133338225094.
[I 2025-09-08 21:40:13,224] Trial 22 finished with value: 0.515222168827207 and parameters: {'C': 9.562716557034705, 'epsilon': 0.10478315612463715}. Best is trial 17 with value: 0.5163133338225094.
[I 2025-09-08 21:40:13,285] Trial 23 finished with value: 0.5022549517954665 and parameters: {'C': 6.223436599630086, 'epsilon': 0.06469351905171111}. Best is trial 17 with value: 0.5163133338225094.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 21:40:13,351] Trial 24 finished with value: 0.49777950957228834 and parameters: {'C': 5.6786505588815555, 'epsilon': 0.03587286805754504}. Best is trial 17 with value: 0.5163133338225094.
[I 2025-09-08 21:40:13,423] Trial 25 finished with value: 0.4744504671363606 and parameters: {'C': 2.7909121078900543, 'epsilon': 0.08773938883392915}. Best is trial 17 with value: 0.5163133338225094.
[I 2025-09-08 21:40:13,485] Trial 26 finished with value: 0.49956543440616974 and parameters: {'C': 5.7774676312749405, 'epsilon': 0.05274240346112124}. Best is trial 17 with value: 0.5163133338225094.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 21:40:13,546] Trial 27 finished with value: 0.4531115819224731 and parameters: {'C': 1.8914565932117038, 'epsilon': 0.02877752380322731}. Best is trial 17 with value: 0.5163133338225094.
[I 2025-09-08 21:40:13,622] Trial 28 finished with value: 0.5152707895999024 and parameters: {'C': 9.988261754153909, 'epsilon': 0.09704306801892609}. Best is trial 17 with value: 0.5163133338225094.
[I 2025-09-08 21:40:13,680] Trial 29 finished with value: 0.2544790479082259 and parameters: {'C': 0.10902838971464102, 'epsilon': 0.1330541003827952}. Best is trial 17 with value: 0.5163133338225094.
[I 2025-09-08 21:40:13,681] A new study created in memory with name: no-name-7d4d43d7-4216-4dad-88e1-b66ec3aa146a
[I 2025-09-08 21:40:13,723] Trial 0 finished with value: 0.5050210457706227 and parameters: {'n_neighbors': 8, 'leaf_size': 37}. Best is trial 0 with value: 0.5050210457706227.

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

✅ SVR con C2X-Complex_rhow_15x15_depth_in_3_4 - Mejor R2: 0.52
📋 Parámetros: {'C': 9.740076562335307, 'epsilon': 0.04684900615162051}

Buscando mejores hiperparámetros para KNN con C2X-Complex_rhow_15x15_depth_in_3_4...
Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 21:40:13,772] Trial 1 finished with value: 0.5035306752601006 and parameters: {'n_neighbors': 3, 'leaf_size': 38}. Best is trial 0 with value: 0.5050210457706227.
[I 2025-09-08 21:40:13,875] Trial 2 finished with value: 0.49571919428019795 and parameters: {'n_neighbors': 12, 'leaf_size': 25}. Best is trial 0 with value: 0.5050210457706227.
[I 2025-09-08 21:40:13,928] Trial 3 finished with value: 0.548947530694237 and parameters: {'n_neighbors': 4, 'leaf_size': 39}. Best is trial 3 with value: 0.548947530694237.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 21:40:13,976] Trial 4 finished with value: 0.5199238336431903 and parameters: {'n_neighbors': 6, 'leaf_size': 23}. Best is trial 3 with value: 0.548947530694237.
[I 2025-09-08 21:40:14,024] Trial 5 finished with value: 0.5020555740652849 and parameters: {'n_neighbors': 9, 'leaf_size': 37}. Best is trial 3 with value: 0.548947530694237.
[I 2025-09-08 21:40:14,073] Trial 6 finished with value: 0.5020555740652849 and parameters: {'n_neighbors': 9, 'leaf_size': 10}. Best is trial 3 with value: 0.548947530694237.
[I 2025-09-08 21:40:14,115] Trial 7 finished with value: 0.5061122910997146 and parameters: {'n_neighbors': 7, 'leaf_size': 20}. Best is trial 3 with value: 0.548947530694237.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:40:14,159] Trial 8 finished with value: 0.5003308614730204 and parameters: {'n_neighbors': 11, 'leaf_size': 12}. Best is trial 3 with value: 0.548947530694237.
[I 2025-09-08 21:40:14,209] Trial 9 finished with value: 0.5003308614730204 and parameters: {'n_neighbors': 11, 'leaf_size': 18}. Best is trial 3 with value: 0.548947530694237.
[I 2025-09-08 21:40:14,269] Trial 10 finished with value: 0.5035306752601006 and parameters: {'n_neighbors': 3, 'leaf_size': 31}. Best is trial 3 with value: 0.548947530694237.
[I 2025-09-08 21:40:14,322] Trial 11 finished with value: 0.5199667853235161 and parameters: {'n_neighbors': 5, 'leaf_size': 30}. Best is trial 3 with value: 0.548947530694237.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:40:14,374] Trial 12 finished with value: 0.5199667853235161 and parameters: {'n_neighbors': 5, 'leaf_size': 28}. Best is trial 3 with value: 0.548947530694237.
[I 2025-09-08 21:40:14,430] Trial 13 finished with value: 0.5199667853235161 and parameters: {'n_neighbors': 5, 'leaf_size': 33}. Best is trial 3 with value: 0.548947530694237.
[I 2025-09-08 21:40:14,480] Trial 14 finished with value: 0.548947530694237 and parameters: {'n_neighbors': 4, 'leaf_size': 40}. Best is trial 3 with value: 0.548947530694237.
[I 2025-09-08 21:40:14,585] Trial 15 finished with value: 0.548947530694237 and parameters: {'n_neighbors': 4, 'leaf_size': 40}. Best is trial 3 with value: 0.548947530694237.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 21:40:14,640] Trial 16 finished with value: 0.5035306752601006 and parameters: {'n_neighbors': 3, 'leaf_size': 34}. Best is trial 3 with value: 0.548947530694237.
[I 2025-09-08 21:40:14,694] Trial 17 finished with value: 0.5199238336431903 and parameters: {'n_neighbors': 6, 'leaf_size': 40}. Best is trial 3 with value: 0.548947530694237.
[I 2025-09-08 21:40:14,753] Trial 18 finished with value: 0.548947530694237 and parameters: {'n_neighbors': 4, 'leaf_size': 35}. Best is trial 3 with value: 0.548947530694237.
[I 2025-09-08 21:40:14,803] Trial 19 finished with value: 0.5061122910997146 and parameters: {'n_neighbors': 7, 'leaf_size': 28}. Best is trial 3 with value: 0.548947530694237.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:40:14,857] Trial 20 finished with value: 0.548947530694237 and parameters: {'n_neighbors': 4, 'leaf_size': 16}. Best is trial 3 with value: 0.548947530694237.
[I 2025-09-08 21:40:14,911] Trial 21 finished with value: 0.548947530694237 and parameters: {'n_neighbors': 4, 'leaf_size': 40}. Best is trial 3 with value: 0.548947530694237.
[I 2025-09-08 21:40:14,968] Trial 22 finished with value: 0.5199238336431903 and parameters: {'n_neighbors': 6, 'leaf_size': 39}. Best is trial 3 with value: 0.548947530694237.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:40:15,017] Trial 23 finished with value: 0.548947530694237 and parameters: {'n_neighbors': 4, 'leaf_size': 36}. Best is trial 3 with value: 0.548947530694237.
[I 2025-09-08 21:40:15,070] Trial 24 finished with value: 0.5199667853235161 and parameters: {'n_neighbors': 5, 'leaf_size': 33}. Best is trial 3 with value: 0.548947530694237.
[I 2025-09-08 21:40:15,171] Trial 25 finished with value: 0.5035306752601006 and parameters: {'n_neighbors': 3, 'leaf_size': 40}. Best is trial 3 with value: 0.548947530694237.
[I 2025-09-08 21:40:15,221] Trial 26 finished with value: 0.548947530694237 and parameters: {'n_neighbors': 4, 'leaf_size': 35}. Best is trial 3 with value: 0.548947530694237.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:40:15,279] Trial 27 finished with value: 0.5199238336431903 and parameters: {'n_neighbors': 6, 'leaf_size': 31}. Best is trial 3 with value: 0.548947530694237.
[I 2025-09-08 21:40:15,339] Trial 28 finished with value: 0.5050210457706227 and parameters: {'n_neighbors': 8, 'leaf_size': 38}. Best is trial 3 with value: 0.548947530694237.
[I 2025-09-08 21:40:15,394] Trial 29 finished with value: 0.5199667853235161 and parameters: {'n_neighbors': 5, 'leaf_size': 37}. Best is trial 3 with value: 0.548947530694237.
[I 2025-09-08 21:40:15,396] A new study created in memory with name: no-name-7b358876-4ea7-4b47-a2d8-7f9e209261eb

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

✅ KNN con C2X-Complex_rhow_15x15_depth_in_3_4 - Mejor R2: 0.55
📋 Parámetros: {'n_neighbors': 4, 'leaf_size': 39}

Buscando mejores hiperparámetros para LR con C2X-Complex_rhow_15x15_depth_in_3_4...
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:40:15,454] Trial 0 finished with value: 0.2549108876889937 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 0 with value: 0.2549108876889937.
[I 2025-09-08 21:40:15,561] Trial 1 finished with value: 0.2549108876912806 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 1 with value: 0.2549108876912806.
[I 2025-09-08 21:40:15,628] Trial 2 finished with value: 0.3494026477097864 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 2 with value: 0.3494026477097864.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:40:15,671] Trial 3 finished with value: 0.3494026477097783 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 2 with value: 0.3494026477097864.
[I 2025-09-08 21:40:15,728] Trial 4 finished with value: 0.2549108876912806 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 2 with value: 0.3494026477097864.
[I 2025-09-08 21:40:15,796] Trial 5 finished with value: 0.3494026477097783 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 2 with value: 0.3494026477097864.
[I 2025-09-08 21:40:15,848] Trial 6 finished with value: 0.2549108876912806 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 2 with value: 0.3494026477097864.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 21:40:15,903] Trial 7 finished with value: 0.3494026477097864 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 2 with value: 0.3494026477097864.
[I 2025-09-08 21:40:15,966] Trial 8 finished with value: 0.2549108876889937 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 2 with value: 0.3494026477097864.
[I 2025-09-08 21:40:16,034] Trial 9 finished with value: 0.3494026477097864 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 2 with value: 0.3494026477097864.

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:40:16,105] Trial 10 finished with value: 0.3494026477097864 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 2 with value: 0.3494026477097864.
[I 2025-09-08 21:40:16,155] Trial 11 finished with value: 0.3494026477097864 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 2 with value: 0.3494026477097864.
[I 2025-09-08 21:40:16,207] Trial 12 finished with value: 0.3494026477097864 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 2 with value: 0.3494026477097864.
[I 2025-09-08 21:40:16,259] Trial 13 finished with value: 0.3494026477097864 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 2 with value: 0.3494026477097864.
[I 2025-09-08 21:40:16,306] Trial 14 finished with value: 0.3494026477097864 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 2 with value: 0.3494026477097864.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 21:40:16,350] Trial 15 finished with value: 0.3494026477097864 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 2 with value: 0.3494026477097864.
[I 2025-09-08 21:40:16,399] Trial 16 finished with value: 0.3494026477097864 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 2 with value: 0.3494026477097864.
[I 2025-09-08 21:40:16,448] Trial 17 finished with value: 0.3494026477097864 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 2 with value: 0.3494026477097864.
[I 2025-09-08 21:40:16,492] Trial 18 finished with value: 0.3494026477097864 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 2 with value: 0.3494026477097864.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:40:16,536] Trial 19 finished with value: 0.3494026477097864 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 2 with value: 0.3494026477097864.
[I 2025-09-08 21:40:16,581] Trial 20 finished with value: 0.3494026477097864 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 2 with value: 0.3494026477097864.
[I 2025-09-08 21:40:16,633] Trial 21 finished with value: 0.3494026477097864 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 2 with value: 0.3494026477097864.
[I 2025-09-08 21:40:16,679] Trial 22 finished with value: 0.3494026477097864 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 2 with value: 0.3494026477097864.
[I 2025-09-08 21:40:16,722] Trial 23 finished with value: 0.3494026477097864 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 2 with value: 0.3494026477097864.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 21:40:16,767] Trial 24 finished with value: 0.3494026477097864 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 2 with value: 0.3494026477097864.
[I 2025-09-08 21:40:16,817] Trial 25 finished with value: 0.3494026477097864 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 2 with value: 0.3494026477097864.
[I 2025-09-08 21:40:16,931] Trial 26 finished with value: 0.2549108876912806 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 2 with value: 0.3494026477097864.

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 21:40:16,996] Trial 27 finished with value: 0.3494026477097864 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 2 with value: 0.3494026477097864.
[I 2025-09-08 21:40:17,044] Trial 28 finished with value: 0.3494026477097864 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 2 with value: 0.3494026477097864.
[I 2025-09-08 21:40:17,108] Trial 29 finished with value: 0.2549108876889937 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 2 with value: 0.3494026477097864.
[I 2025-09-08 21:40:17,110] A new study created in memory with name: no-name-3415dd50-8ecb-48b1-a442-53be489c45f6

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

✅ LR con C2X-Complex_rhow_15x15_depth_in_3_4 - Mejor R2: 0.35
📋 Parámetros: {'fit_intercept': False, 'positive': True}

Buscando mejores hiperparámetros para RF con C2X-Complex_rhow_15x15_depth_in_3_4...
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:40:20,232] Trial 0 finished with value: 0.15857318217027672 and parameters: {'n_estimators': 200, 'max_depth': 8, 'min_samples_split': 5, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 0 with value: 0.15857318217027672.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:40:22,855] Trial 1 finished with value: 0.17286644767542625 and parameters: {'n_estimators': 200, 'max_depth': 6, 'min_samples_split': 5, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 1 with value: 0.17286644767542625.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:40:28,852] Trial 2 finished with value: 0.24459238274694603 and parameters: {'n_estimators': 400, 'max_depth': 9, 'min_samples_split': 7, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 2 with value: 0.24459238274694603.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:40:32,013] Trial 3 finished with value: 0.40220163223073185 and parameters: {'n_estimators': 400, 'max_depth': 11, 'min_samples_split': 3, 'min_samples_leaf': 7, 'bootstrap': True}. Best is trial 3 with value: 0.40220163223073185.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:40:32,930] Trial 4 finished with value: 0.4045728604567633 and parameters: {'n_estimators': 100, 'max_depth': 10, 'min_samples_split': 4, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 4 with value: 0.4045728604567633.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:40:34,234] Trial 5 finished with value: 0.18190076440387437 and parameters: {'n_estimators': 100, 'max_depth': 10, 'min_samples_split': 6, 'min_samples_leaf': 6, 'bootstrap': False}. Best is trial 4 with value: 0.4045728604567633.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:40:35,165] Trial 6 finished with value: 0.41621163549301904 and parameters: {'n_estimators': 100, 'max_depth': 6, 'min_samples_split': 7, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 6 with value: 0.41621163549301904.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:40:36,817] Trial 7 finished with value: 0.39765731601634274 and parameters: {'n_estimators': 200, 'max_depth': 12, 'min_samples_split': 5, 'min_samples_leaf': 6, 'bootstrap': True}. Best is trial 6 with value: 0.41621163549301904.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:40:39,299] Trial 8 finished with value: 0.18401805744826186 and parameters: {'n_estimators': 200, 'max_depth': 7, 'min_samples_split': 8, 'min_samples_leaf': 6, 'bootstrap': False}. Best is trial 6 with value: 0.41621163549301904.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:40:41,061] Trial 9 finished with value: 0.4012390867997073 and parameters: {'n_estimators': 200, 'max_depth': 10, 'min_samples_split': 6, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 6 with value: 0.41621163549301904.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:40:41,890] Trial 10 finished with value: 0.4001065460855672 and parameters: {'n_estimators': 100, 'max_depth': 5, 'min_samples_split': 2, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 6 with value: 0.41621163549301904.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:40:42,863] Trial 11 finished with value: 0.4010375001645039 and parameters: {'n_estimators': 100, 'max_depth': 8, 'min_samples_split': 3, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 6 with value: 0.41621163549301904.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:40:43,607] Trial 12 finished with value: 0.4081242020923525 and parameters: {'n_estimators': 100, 'max_depth': 5, 'min_samples_split': 4, 'min_samples_leaf': 8, 'bootstrap': True}. Best is trial 6 with value: 0.41621163549301904.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:40:44,351] Trial 13 finished with value: 0.4081242020923525 and parameters: {'n_estimators': 100, 'max_depth': 5, 'min_samples_split': 8, 'min_samples_leaf': 8, 'bootstrap': True}. Best is trial 6 with value: 0.41621163549301904.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:40:45,153] Trial 14 finished with value: 0.40732632057344403 and parameters: {'n_estimators': 100, 'max_depth': 6, 'min_samples_split': 7, 'min_samples_leaf': 8, 'bootstrap': True}. Best is trial 6 with value: 0.41621163549301904.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:40:46,079] Trial 15 finished with value: 0.41348314113719464 and parameters: {'n_estimators': 100, 'max_depth': 6, 'min_samples_split': 4, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 6 with value: 0.41621163549301904.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:40:47,063] Trial 16 finished with value: 0.412905502750269 and parameters: {'n_estimators': 100, 'max_depth': 7, 'min_samples_split': 6, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 6 with value: 0.41621163549301904.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:40:50,840] Trial 17 finished with value: 0.4250515635692112 and parameters: {'n_estimators': 400, 'max_depth': 7, 'min_samples_split': 4, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 17 with value: 0.4250515635692112.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:40:54,465] Trial 18 finished with value: 0.40783679048671106 and parameters: {'n_estimators': 400, 'max_depth': 7, 'min_samples_split': 7, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 17 with value: 0.4250515635692112.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:40:58,686] Trial 19 finished with value: 0.43886664499406985 and parameters: {'n_estimators': 400, 'max_depth': 8, 'min_samples_split': 2, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 19 with value: 0.43886664499406985.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:41:03,046] Trial 20 finished with value: 0.43701465464303396 and parameters: {'n_estimators': 400, 'max_depth': 9, 'min_samples_split': 2, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 19 with value: 0.43886664499406985.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:41:07,403] Trial 21 finished with value: 0.43701465464303396 and parameters: {'n_estimators': 400, 'max_depth': 9, 'min_samples_split': 2, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 19 with value: 0.43886664499406985.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:41:11,739] Trial 22 finished with value: 0.43701465464303396 and parameters: {'n_estimators': 400, 'max_depth': 9, 'min_samples_split': 2, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 19 with value: 0.43886664499406985.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:41:16,080] Trial 23 finished with value: 0.43701465464303396 and parameters: {'n_estimators': 400, 'max_depth': 9, 'min_samples_split': 2, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 19 with value: 0.43886664499406985.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:41:20,326] Trial 24 finished with value: 0.43886664499406985 and parameters: {'n_estimators': 400, 'max_depth': 8, 'min_samples_split': 3, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 19 with value: 0.43886664499406985.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:41:24,534] Trial 25 finished with value: 0.43886664499406985 and parameters: {'n_estimators': 400, 'max_depth': 8, 'min_samples_split': 3, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 19 with value: 0.43886664499406985.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:41:30,162] Trial 26 finished with value: 0.24929981880916655 and parameters: {'n_estimators': 400, 'max_depth': 8, 'min_samples_split': 3, 'min_samples_leaf': 4, 'bootstrap': False}. Best is trial 19 with value: 0.43886664499406985.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:41:34,088] Trial 27 finished with value: 0.42746834306397696 and parameters: {'n_estimators': 400, 'max_depth': 8, 'min_samples_split': 3, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 19 with value: 0.43886664499406985.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:41:38,321] Trial 28 finished with value: 0.43886664499406985 and parameters: {'n_estimators': 400, 'max_depth': 8, 'min_samples_split': 3, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 19 with value: 0.43886664499406985.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:41:44,543] Trial 29 finished with value: 0.07178113585501844 and parameters: {'n_estimators': 400, 'max_depth': 8, 'min_samples_split': 3, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 19 with value: 0.43886664499406985.
[I 2025-09-08 21:41:44,544] A new study created in memory with name: no-name-f56e7ec6-370b-4b83-8030-a814f318332b

✅ RF con C2X-Complex_rhow_15x15_depth_in_3_4 - Mejor R2: 0.44
📋 Parámetros: {'n_estimators': 400, 'max_depth': 8, 'min_samples_split': 2, 'min_samples_leaf': 2, 'bootstrap': True}

Buscando mejores hiperparámetros para CAT con C2X-Complex_rhow_15x15_depth_in_3_4...
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:41:46,702] Trial 0 finished with value: 0.45266387312574846 and parameters: {'iterations': 1000, 'learning_rate': 0.02, 'depth': 4, 'l2_leaf_reg': 4.035443205395055}. Best is trial 0 with value: 0.45266387312574846.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:41:48,413] Trial 1 finished with value: 0.4484449800931878 and parameters: {'iterations': 750, 'learning_rate': 0.05, 'depth': 4, 'l2_leaf_reg': 4.576703790922457}. Best is trial 0 with value: 0.45266387312574846.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:41:51,069] Trial 2 finished with value: 0.49850523566497756 and parameters: {'iterations': 500, 'learning_rate': 0.05, 'depth': 6, 'l2_leaf_reg': 1.0326673029472841}. Best is trial 2 with value: 0.49850523566497756.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:42:04,848] Trial 3 finished with value: 0.47349829032059426 and parameters: {'iterations': 500, 'learning_rate': 0.04, 'depth': 8, 'l2_leaf_reg': 1.1181999120140014}. Best is trial 2 with value: 0.49850523566497756.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:42:25,000] Trial 4 finished with value: 0.4836624451805036 and parameters: {'iterations': 750, 'learning_rate': 0.02, 'depth': 8, 'l2_leaf_reg': 2.818191728247699}. Best is trial 2 with value: 0.49850523566497756.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:42:26,544] Trial 5 finished with value: 0.4617084035788331 and parameters: {'iterations': 500, 'learning_rate': 0.03, 'depth': 5, 'l2_leaf_reg': 2.262344357003762}. Best is trial 2 with value: 0.49850523566497756.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:42:28,769] Trial 6 finished with value: 0.4518467982243149 and parameters: {'iterations': 1000, 'learning_rate': 0.04, 'depth': 4, 'l2_leaf_reg': 2.668316432442682}. Best is trial 2 with value: 0.49850523566497756.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:42:32,524] Trial 7 finished with value: 0.49564826297576525 and parameters: {'iterations': 750, 'learning_rate': 0.05, 'depth': 6, 'l2_leaf_reg': 4.631752381138675}. Best is trial 2 with value: 0.49850523566497756.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:42:33,620] Trial 8 finished with value: 0.4447959815068563 and parameters: {'iterations': 500, 'learning_rate': 0.05, 'depth': 4, 'l2_leaf_reg': 3.7262643341242128}. Best is trial 2 with value: 0.49850523566497756.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:42:59,972] Trial 9 finished with value: 0.4885975077956564 and parameters: {'iterations': 1000, 'learning_rate': 0.02, 'depth': 8, 'l2_leaf_reg': 4.267686349444839}. Best is trial 2 with value: 0.49850523566497756.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:43:02,304] Trial 10 finished with value: 0.48495090405320473 and parameters: {'iterations': 500, 'learning_rate': 0.03, 'depth': 6, 'l2_leaf_reg': 1.3887750254942646}. Best is trial 2 with value: 0.49850523566497756.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:43:06,215] Trial 11 finished with value: 0.4785171530847137 and parameters: {'iterations': 750, 'learning_rate': 0.05, 'depth': 6, 'l2_leaf_reg': 1.9038561503831675}. Best is trial 2 with value: 0.49850523566497756.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:43:14,724] Trial 12 finished with value: 0.4816590360124482 and parameters: {'iterations': 750, 'learning_rate': 0.05, 'depth': 7, 'l2_leaf_reg': 4.980447244403299}. Best is trial 2 with value: 0.49850523566497756.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:43:20,658] Trial 13 finished with value: 0.48824674236371973 and parameters: {'iterations': 500, 'learning_rate': 0.05, 'depth': 7, 'l2_leaf_reg': 3.2128767609973994}. Best is trial 2 with value: 0.49850523566497756.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:43:22,916] Trial 14 finished with value: 0.49321097005918196 and parameters: {'iterations': 750, 'learning_rate': 0.05, 'depth': 5, 'l2_leaf_reg': 3.4390575992308}. Best is trial 2 with value: 0.49850523566497756.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:43:28,882] Trial 15 finished with value: 0.4923662296594151 and parameters: {'iterations': 500, 'learning_rate': 0.05, 'depth': 7, 'l2_leaf_reg': 1.7582029903627832}. Best is trial 2 with value: 0.49850523566497756.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:43:31,231] Trial 16 finished with value: 0.48875742252040394 and parameters: {'iterations': 750, 'learning_rate': 0.05, 'depth': 5, 'l2_leaf_reg': 2.586690653526202}. Best is trial 2 with value: 0.49850523566497756.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:43:35,195] Trial 17 finished with value: 0.4755132625009056 and parameters: {'iterations': 750, 'learning_rate': 0.03, 'depth': 6, 'l2_leaf_reg': 3.6946855607123275}. Best is trial 2 with value: 0.49850523566497756.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:43:41,132] Trial 18 finished with value: 0.47860153026343477 and parameters: {'iterations': 500, 'learning_rate': 0.04, 'depth': 7, 'l2_leaf_reg': 4.8511461972475285}. Best is trial 2 with value: 0.49850523566497756.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:43:44,292] Trial 19 finished with value: 0.48276897586209583 and parameters: {'iterations': 1000, 'learning_rate': 0.05, 'depth': 5, 'l2_leaf_reg': 2.2451506756092465}. Best is trial 2 with value: 0.49850523566497756.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:43:48,209] Trial 20 finished with value: 0.4908165942744061 and parameters: {'iterations': 750, 'learning_rate': 0.05, 'depth': 6, 'l2_leaf_reg': 4.338257226796927}. Best is trial 2 with value: 0.49850523566497756.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:43:50,602] Trial 21 finished with value: 0.4935278288973044 and parameters: {'iterations': 750, 'learning_rate': 0.05, 'depth': 5, 'l2_leaf_reg': 3.132889603247381}. Best is trial 2 with value: 0.49850523566497756.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:43:53,011] Trial 22 finished with value: 0.49916646303744777 and parameters: {'iterations': 750, 'learning_rate': 0.05, 'depth': 5, 'l2_leaf_reg': 3.0629598009592023}. Best is trial 22 with value: 0.49916646303744777.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:43:56,776] Trial 23 finished with value: 0.4933847078905846 and parameters: {'iterations': 750, 'learning_rate': 0.05, 'depth': 6, 'l2_leaf_reg': 1.5332483882875196}. Best is trial 22 with value: 0.49916646303744777.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:44:00,545] Trial 24 finished with value: 0.487183610078715 and parameters: {'iterations': 750, 'learning_rate': 0.05, 'depth': 6, 'l2_leaf_reg': 1.0083998426620526}. Best is trial 22 with value: 0.49916646303744777.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:44:02,135] Trial 25 finished with value: 0.49048870934855177 and parameters: {'iterations': 500, 'learning_rate': 0.05, 'depth': 5, 'l2_leaf_reg': 2.3134511163802456}. Best is trial 22 with value: 0.49916646303744777.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:44:06,070] Trial 26 finished with value: 0.47646973905154194 and parameters: {'iterations': 750, 'learning_rate': 0.02, 'depth': 6, 'l2_leaf_reg': 3.8814939586724884}. Best is trial 22 with value: 0.49916646303744777.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:44:14,748] Trial 27 finished with value: 0.4726344079540381 and parameters: {'iterations': 750, 'learning_rate': 0.03, 'depth': 7, 'l2_leaf_reg': 3.3321797379432248}. Best is trial 22 with value: 0.49916646303744777.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:44:18,089] Trial 28 finished with value: 0.48272847728045437 and parameters: {'iterations': 1000, 'learning_rate': 0.04, 'depth': 5, 'l2_leaf_reg': 2.9845159566433326}. Best is trial 22 with value: 0.49916646303744777.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:44:20,578] Trial 29 finished with value: 0.4570805317237821 and parameters: {'iterations': 500, 'learning_rate': 0.02, 'depth': 6, 'l2_leaf_reg': 4.112336663331435}. Best is trial 22 with value: 0.49916646303744777.
[I 2025-09-08 21:44:20,580] A new study created in memory with name: no-name-cdabc8a3-ed7f-4b55-8377-8f8bbab94044
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.707e-02, tolerance: 3.578e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.129e-02, tolerance: 4.678e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:44:20,649] Trial 0 finished with value: 0.3984856635455216 and parameters: {'alpha': 0.004498103839774165, 'l1_ratio': 0.8744703506222645}. Best is trial 0 with value: 0.3984856635455216.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.364e+01, tolerance: 3.578e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.735e+01, tolerance: 3.999e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.781e+01, tolerance: 4.678e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:44:20,736] Trial 1 finished with value: 0.3907701421370909 and parameters: {'alpha': 0.0010044949097921013, 'l1_ratio': 0.252717704525915}. Best is trial 0 with value: 0.3984856635455216.

✅ CAT con C2X-Complex_rhow_15x15_depth_in_3_4 - Mejor R2: 0.50
📋 Parámetros: {'iterations': 750, 'learning_rate': 0.05, 'depth': 5, 'l2_leaf_reg': 3.0629598009592023}

Buscando mejores hiperparámetros para ELN con C2X-Complex_rhow_15x15_depth_in_3_4...
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 21:44:20,807] Trial 2 finished with value: 0.39628202373365456 and parameters: {'alpha': 0.01488263311940335, 'l1_ratio': 0.8480909079781486}. Best is trial 0 with value: 0.3984856635455216.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.991e+01, tolerance: 3.578e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.533e+01, tolerance: 3.999e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.190e+01, tolerance: 4.678e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:44:20,896] Trial 3 finished with value: 0.39346258746195434 and parameters: {'alpha': 0.0013307219415586006, 'l1_ratio': 0.27704451517381995}. Best is trial 0 with value: 0.3984856635455216.

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.555e-02, tolerance: 3.578e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:44:21,013] Trial 4 finished with value: 0.39710140513528785 and parameters: {'alpha': 0.010869320705516066, 'l1_ratio': 0.35841944828539185}. Best is trial 0 with value: 0.3984856635455216.
[I 2025-09-08 21:44:21,101] Trial 5 finished with value: 0.3925748299786085 and parameters: {'alpha': 0.02488249518339584, 'l1_ratio': 0.6067425843914602}. Best is trial 0 with value: 0.3984856635455216.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.402e+00, tolerance: 3.578e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.282e+00, tolerance: 3.999e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.359e+01, tolerance: 4.678e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:44:21,204] Trial 6 finished with value: 0.39507616181854605 and parameters: {'alpha': 0.007710163931093649, 'l1_ratio': 0.20209692249568623}. Best is trial 0 with value: 0.3984856635455216.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.887e+01, tolerance: 3.578e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.424e+01, tolerance: 3.999e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.002e+02, tolerance: 4.678e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:44:21,318] Trial 7 finished with value: 0.38077540079831645 and parameters: {'alpha': 0.00013657245107210708, 'l1_ratio': 0.6383515664781585}. Best is trial 0 with value: 0.3984856635455216.
[I 2025-09-08 21:44:21,431] Trial 8 finished with value: 0.39495043664267254 and parameters: {'alpha': 0.027116624069819496, 'l1_ratio': 0.30579958311444005}. Best is trial 0 with value: 0.3984856635455216.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.016e+01, tolerance: 3.578e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.225e+01, tolerance: 3.999e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.002e+02, tolerance: 4.678e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:44:21,553] Trial 9 finished with value: 0.38537069495020965 and parameters: {'alpha': 0.00042862720360744514, 'l1_ratio': 0.2168158852711141}. Best is trial 0 with value: 0.3984856635455216.
[I 2025-09-08 21:44:21,641] Trial 10 finished with value: 0.2841376626732764 and parameters: {'alpha': 0.3510261181348782, 'l1_ratio': 0.8557984734903262}. Best is trial 0 with value: 0.3984856635455216.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 21:44:21,747] Trial 11 finished with value: 0.358445683351398 and parameters: {'alpha': 0.14103356350591809, 'l1_ratio': 0.47098606430522166}. Best is trial 0 with value: 0.3984856635455216.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.044e+00, tolerance: 3.578e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.972e+00, tolerance: 3.999e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.093e+01, tolerance: 4.678e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:44:21,893] Trial 12 finished with value: 0.3959438033862046 and parameters: {'alpha': 0.003959278863084947, 'l1_ratio': 0.43629087650436715}. Best is trial 0 with value: 0.3984856635455216.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:44:21,988] Trial 13 finished with value: 0.3607673781582459 and parameters: {'alpha': 0.08815446601015357, 'l1_ratio': 0.6731121551626355}. Best is trial 0 with value: 0.3984856635455216.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.776e+01, tolerance: 3.578e-02
  model = cd_fast.enet_coordinate_descent(

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.516e+01, tolerance: 3.999e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.425e+01, tolerance: 4.678e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:44:22,122] Trial 14 finished with value: 0.39803159260349147 and parameters: {'alpha': 0.003162746653037838, 'l1_ratio': 0.11606506097005231}. Best is trial 0 with value: 0.3984856635455216.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.800e+01, tolerance: 3.578e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.416e+01, tolerance: 3.999e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.480e+01, tolerance: 4.678e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:44:22,286] Trial 15 finished with value: 0.39806824323855167 and parameters: {'alpha': 0.0029416597085727475, 'l1_ratio': 0.10976726273166883}. Best is trial 0 with value: 0.3984856635455216.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.646e+01, tolerance: 3.578e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.015e+01, tolerance: 3.999e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.276e+01, tolerance: 4.678e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:44:22,380] Trial 16 finished with value: 0.38449586303496924 and parameters: {'alpha': 0.00045638650439678533, 'l1_ratio': 0.7324460287569537}. Best is trial 0 with value: 0.3984856635455216.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.816e+00, tolerance: 3.578e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.415e+00, tolerance: 3.999e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.775e+01, tolerance: 4.678e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:44:22,480] Trial 17 finished with value: 0.39574870981411286 and parameters: {'alpha': 0.00364774643595346, 'l1_ratio': 0.5454316258035361}. Best is trial 0 with value: 0.3984856635455216.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 21:44:22,674] Trial 18 finished with value: 0.3912322769692513 and parameters: {'alpha': 0.06786640063369724, 'l1_ratio': 0.10625416308913738}. Best is trial 0 with value: 0.3984856635455216.

Fold 3
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.988e+01, tolerance: 3.578e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.564e+01, tolerance: 3.999e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.003e+02, tolerance: 4.678e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:44:22,804] Trial 19 finished with value: 0.3802128684244517 and parameters: {'alpha': 0.00010558606215832955, 'l1_ratio': 0.7738891181686799}. Best is trial 0 with value: 0.3984856635455216.
[I 2025-09-08 21:44:22,879] Trial 20 finished with value: 0.27021554679624293 and parameters: {'alpha': 0.6822238406073017, 'l1_ratio': 0.41801562709911483}. Best is trial 0 with value: 0.3984856635455216.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.225e+01, tolerance: 3.578e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.787e+01, tolerance: 3.999e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.340e+01, tolerance: 4.678e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:44:22,999] Trial 21 finished with value: 0.39726807626006816 and parameters: {'alpha': 0.0021530715311906573, 'l1_ratio': 0.11013084935324216}. Best is trial 0 with value: 0.3984856635455216.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.917e+01, tolerance: 3.578e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.811e+01, tolerance: 3.999e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.956e+01, tolerance: 4.678e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:44:23,102] Trial 22 finished with value: 0.39590932760797476 and parameters: {'alpha': 0.005518997346943766, 'l1_ratio': 0.1489971025883631}. Best is trial 0 with value: 0.3984856635455216.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.488e+01, tolerance: 3.578e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.152e+01, tolerance: 3.999e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.832e+01, tolerance: 4.678e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:44:23,198] Trial 23 finished with value: 0.386860509278182 and parameters: {'alpha': 0.0006566263223602363, 'l1_ratio': 0.5407633140001098}. Best is trial 0 with value: 0.3984856635455216.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.209e+00, tolerance: 3.578e-02
  model = cd_fast.enet_coordinate_descent(

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.283e+01, tolerance: 3.999e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.206e+01, tolerance: 4.678e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:44:23,307] Trial 24 finished with value: 0.3961765601266441 and parameters: {'alpha': 0.0032653211985525293, 'l1_ratio': 0.35210079813919837}. Best is trial 0 with value: 0.3984856635455216.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.370e+01, tolerance: 3.578e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.833e+01, tolerance: 3.999e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.619e+01, tolerance: 4.678e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:44:23,410] Trial 25 finished with value: 0.39577997654855684 and parameters: {'alpha': 0.0016629659741852268, 'l1_ratio': 0.15299372488744262}. Best is trial 0 with value: 0.3984856635455216.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.255e+01, tolerance: 3.578e-02
  model = cd_fast.enet_coordinate_descent(

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.176e+01, tolerance: 3.999e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.037e+02, tolerance: 4.678e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:44:23,526] Trial 26 finished with value: 0.3821549920762884 and parameters: {'alpha': 0.00022546601914785874, 'l1_ratio': 0.19181749328309533}. Best is trial 0 with value: 0.3984856635455216.
[I 2025-09-08 21:44:23,676] Trial 27 finished with value: 0.38734004632738905 and parameters: {'alpha': 0.03138034286261639, 'l1_ratio': 0.765500884615276}. Best is trial 0 with value: 0.3984856635455216.

Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:44:23,796] Trial 28 finished with value: 0.39863027468531786 and parameters: {'alpha': 0.010400228287710573, 'l1_ratio': 0.8885580738178107}. Best is trial 28 with value: 0.39863027468531786.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.078e-02, tolerance: 3.578e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:44:23,903] Trial 29 finished with value: 0.3972091607188555 and parameters: {'alpha': 0.013663750086182654, 'l1_ratio': 0.882289011966953}. Best is trial 28 with value: 0.39863027468531786.
[I 2025-09-08 21:44:23,905] A new study created in memory with name: no-name-4da6d6c4-803c-4396-97eb-695ee3609593

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

✅ ELN con C2X-Complex_rhow_15x15_depth_in_3_4 - Mejor R2: 0.40
📋 Parámetros: {'alpha': 0.010400228287710573, 'l1_ratio': 0.8885580738178107}

Buscando mejores hiperparámetros para XGB con C2X-Complex_rhown_9x9_depth_in_3_4...
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:44:28,950] Trial 0 finished with value: 0.22775914056168522 and parameters: {'n_estimators': 750, 'learning_rate': 0.03, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.6054012835160973, 'colsample_bytree': 0.7552833498796255}. Best is trial 0 with value: 0.22775914056168522.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:44:34,279] Trial 1 finished with value: 0.31483704756068515 and parameters: {'n_estimators': 1250, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.7930360376315084, 'colsample_bytree': 0.7219966498244917}. Best is trial 1 with value: 0.31483704756068515.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:44:39,957] Trial 2 finished with value: 0.2477885188465917 and parameters: {'n_estimators': 750, 'learning_rate': 0.02, 'max_depth': 8, 'min_child_weight': 2, 'subsample': 0.6836404402296126, 'colsample_bytree': 0.7454436401687258}. Best is trial 1 with value: 0.31483704756068515.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:44:45,360] Trial 3 finished with value: 0.2685596772300233 and parameters: {'n_estimators': 1250, 'learning_rate': 0.02, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.6785866256082514, 'colsample_bytree': 0.6751438931162581}. Best is trial 1 with value: 0.31483704756068515.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:44:51,460] Trial 4 finished with value: 0.2771724663535032 and parameters: {'n_estimators': 1000, 'learning_rate': 0.02, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.7484331791392105, 'colsample_bytree': 0.6336149883017906}. Best is trial 1 with value: 0.31483704756068515.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:44:55,547] Trial 5 finished with value: 0.2728959317540838 and parameters: {'n_estimators': 750, 'learning_rate': 0.03, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.6051428044283108, 'colsample_bytree': 0.7673729376527744}. Best is trial 1 with value: 0.31483704756068515.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:45:01,460] Trial 6 finished with value: 0.27288494669585034 and parameters: {'n_estimators': 1250, 'learning_rate': 0.02, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.7805319202973504, 'colsample_bytree': 0.7020968453647053}. Best is trial 1 with value: 0.31483704756068515.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:45:09,180] Trial 7 finished with value: 0.2531286314715135 and parameters: {'n_estimators': 1250, 'learning_rate': 0.03, 'max_depth': 8, 'min_child_weight': 3, 'subsample': 0.7464969746160988, 'colsample_bytree': 0.6913575644062591}. Best is trial 1 with value: 0.31483704756068515.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:45:14,644] Trial 8 finished with value: 0.2610002825145319 and parameters: {'n_estimators': 1000, 'learning_rate': 0.03, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.6277776204848395, 'colsample_bytree': 0.7642880095297718}. Best is trial 1 with value: 0.31483704756068515.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:45:19,118] Trial 9 finished with value: 0.2693401994502803 and parameters: {'n_estimators': 750, 'learning_rate': 0.03, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.7329268540811553, 'colsample_bytree': 0.6688791036660574}. Best is trial 1 with value: 0.31483704756068515.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:45:24,546] Trial 10 finished with value: 0.30561895938507977 and parameters: {'n_estimators': 1250, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.7935568049258424, 'colsample_bytree': 0.7974550003244909}. Best is trial 1 with value: 0.31483704756068515.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:45:30,063] Trial 11 finished with value: 0.3103065159015586 and parameters: {'n_estimators': 1250, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.7943162341366581, 'colsample_bytree': 0.7980548368544573}. Best is trial 1 with value: 0.31483704756068515.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:45:35,387] Trial 12 finished with value: 0.3210641939728817 and parameters: {'n_estimators': 1250, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.7953837023214747, 'colsample_bytree': 0.7207843737049596}. Best is trial 12 with value: 0.3210641939728817.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:45:40,628] Trial 13 finished with value: 0.3184113486551262 and parameters: {'n_estimators': 1250, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.7218428243487178, 'colsample_bytree': 0.7314659042032452}. Best is trial 12 with value: 0.3210641939728817.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:45:45,874] Trial 14 finished with value: 0.3222745701691628 and parameters: {'n_estimators': 1250, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.7134467820023552, 'colsample_bytree': 0.7221852379051668}. Best is trial 14 with value: 0.3222745701691628.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:45:50,866] Trial 15 finished with value: 0.32057317201898966 and parameters: {'n_estimators': 1250, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.6453694735431008, 'colsample_bytree': 0.61355703736168}. Best is trial 14 with value: 0.3222745701691628.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:45:55,643] Trial 16 finished with value: 0.326166677291102 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.7646525194581018, 'colsample_bytree': 0.7102961356105443}. Best is trial 16 with value: 0.326166677291102.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:46:01,093] Trial 17 finished with value: 0.3211826073764661 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.7054631959848406, 'colsample_bytree': 0.656800748009434}. Best is trial 16 with value: 0.326166677291102.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:46:05,350] Trial 18 finished with value: 0.32249562962688927 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.7634716061577141, 'colsample_bytree': 0.6992200321189233}. Best is trial 16 with value: 0.326166677291102.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:46:10,726] Trial 19 finished with value: 0.32589729109230775 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.7644400400445809, 'colsample_bytree': 0.6959437300672902}. Best is trial 16 with value: 0.326166677291102.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:46:15,321] Trial 20 finished with value: 0.3247722103432519 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.7654076622171363, 'colsample_bytree': 0.6445837007151438}. Best is trial 16 with value: 0.326166677291102.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:46:20,321] Trial 21 finished with value: 0.3298148685201366 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.7664423076856999, 'colsample_bytree': 0.6027722236467548}. Best is trial 21 with value: 0.3298148685201366.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:46:25,824] Trial 22 finished with value: 0.31909019038856345 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.7660131667590147, 'colsample_bytree': 0.6193342652247864}. Best is trial 21 with value: 0.3298148685201366.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:46:30,745] Trial 23 finished with value: 0.3281218316960884 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.7431840346425217, 'colsample_bytree': 0.6772780693068094}. Best is trial 21 with value: 0.3298148685201366.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:46:35,431] Trial 24 finished with value: 0.32515890965199984 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.7401878920188834, 'colsample_bytree': 0.6078278411540465}. Best is trial 21 with value: 0.3298148685201366.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:46:40,831] Trial 25 finished with value: 0.3288510351170664 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.7259598045953478, 'colsample_bytree': 0.6775609039686776}. Best is trial 21 with value: 0.3298148685201366.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:46:46,340] Trial 26 finished with value: 0.32594398944545866 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.6924259766424463, 'colsample_bytree': 0.677679606987913}. Best is trial 21 with value: 0.3298148685201366.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:46:53,284] Trial 27 finished with value: 0.2986734570478633 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 8, 'min_child_weight': 2, 'subsample': 0.7255017508571596, 'colsample_bytree': 0.6459913203523844}. Best is trial 21 with value: 0.3298148685201366.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:46:58,644] Trial 28 finished with value: 0.2814564262819546 and parameters: {'n_estimators': 1000, 'learning_rate': 0.02, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.7508032255190947, 'colsample_bytree': 0.6003273713693206}. Best is trial 21 with value: 0.3298148685201366.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:47:04,453] Trial 29 finished with value: 0.2964404061635637 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.6615306214291139, 'colsample_bytree': 0.6255284014106901}. Best is trial 21 with value: 0.3298148685201366.
[I 2025-09-08 21:47:04,455] A new study created in memory with name: no-name-99d78fd3-f2fa-47e9-a2bf-296a23329a53
[I 2025-09-08 21:47:04,618] Trial 0 finished with value: 0.3003300873229632 and parameters: {'learning_rate': 0.04, 'num_leaves': 10, 'max_depth': 8, 'min_child_samples': 6, 'subsample': 0.7820355740644713, 'colsample_bytree': 0.7952051875016718, 'n_estimators': 1000, 'min_split_gain': 0.2}. Best is trial 0 with value: 0.3003300873229632.

✅ XGB con C2X-Complex_rhown_9x9_depth_in_3_4 - Mejor R2: 0.33
📋 Parámetros: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.7664423076856999, 'colsample_bytree': 0.6027722236467548}

Buscando mejores hiperparámetros para LBM con C2X-Complex_rhown_9x9_depth_in_3_4...
Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 21:47:04,782] Trial 1 finished with value: 0.38667008315931534 and parameters: {'learning_rate': 0.04, 'num_leaves': 10, 'max_depth': 6, 'min_child_samples': 4, 'subsample': 0.6482563799005192, 'colsample_bytree': 0.793228312663879, 'n_estimators': 750, 'min_split_gain': 0.1}. Best is trial 1 with value: 0.38667008315931534.

Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 21:47:04,934] Trial 2 finished with value: 0.3445549079218921 and parameters: {'learning_rate': 0.05, 'num_leaves': 30, 'max_depth': 7, 'min_child_samples': 5, 'subsample': 0.7895975542005025, 'colsample_bytree': 0.7523356283693493, 'n_estimators': 750, 'min_split_gain': 0.2}. Best is trial 1 with value: 0.38667008315931534.

Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:47:05,128] Trial 3 finished with value: 0.28098322623605815 and parameters: {'learning_rate': 0.05, 'num_leaves': 20, 'max_depth': 8, 'min_child_samples': 7, 'subsample': 0.7692775681546182, 'colsample_bytree': 0.7394884554060119, 'n_estimators': 750, 'min_split_gain': 0.1}. Best is trial 1 with value: 0.38667008315931534.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:47:05,397] Trial 4 finished with value: 0.30811568743813444 and parameters: {'learning_rate': 0.02, 'num_leaves': 10, 'max_depth': 8, 'min_child_samples': 7, 'subsample': 0.753082119950746, 'colsample_bytree': 0.73222592039683, 'n_estimators': 1000, 'min_split_gain': 0.2}. Best is trial 1 with value: 0.38667008315931534.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:47:05,628] Trial 5 finished with value: 0.3495465814209578 and parameters: {'learning_rate': 0.02, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 8, 'subsample': 0.7769762642618322, 'colsample_bytree': 0.7748001464394918, 'n_estimators': 750, 'min_split_gain': 0.2}. Best is trial 1 with value: 0.38667008315931534.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:47:05,841] Trial 6 finished with value: 0.30555690443136563 and parameters: {'learning_rate': 0.05, 'num_leaves': 30, 'max_depth': 6, 'min_child_samples': 7, 'subsample': 0.7578909386301349, 'colsample_bytree': 0.6795904303463327, 'n_estimators': 1000, 'min_split_gain': 0.1}. Best is trial 1 with value: 0.38667008315931534.
[I 2025-09-08 21:47:06,016] Trial 7 finished with value: 0.288023826201449 and parameters: {'learning_rate': 0.05, 'num_leaves': 30, 'max_depth': 7, 'min_child_samples': 7, 'subsample': 0.6162334296003176, 'colsample_bytree': 0.7377318125673858, 'n_estimators': 1250, 'min_split_gain': 0.2}. Best is trial 1 with value: 0.38667008315931534.

Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 21:47:06,162] Trial 8 finished with value: 0.32293957206103724 and parameters: {'learning_rate': 0.04, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 7, 'subsample': 0.6804369099121821, 'colsample_bytree': 0.7621079384974956, 'n_estimators': 1000, 'min_split_gain': 0.5}. Best is trial 1 with value: 0.38667008315931534.

Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 21:47:06,326] Trial 9 finished with value: 0.34743884622442245 and parameters: {'learning_rate': 0.02, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 6, 'subsample': 0.7555416343250192, 'colsample_bytree': 0.6603186976490187, 'n_estimators': 1000, 'min_split_gain': 1.0}. Best is trial 1 with value: 0.38667008315931534.

Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:47:06,804] Trial 10 finished with value: 0.3874589160986159 and parameters: {'learning_rate': 0.03, 'num_leaves': 10, 'max_depth': 6, 'min_child_samples': 4, 'subsample': 0.6281553640898427, 'colsample_bytree': 0.6059101133839331, 'n_estimators': 1250, 'min_split_gain': 0.0}. Best is trial 10 with value: 0.3874589160986159.

Fold 1
Fold 2

[I 2025-09-08 21:47:07,251] Trial 11 finished with value: 0.3874589160986159 and parameters: {'learning_rate': 0.03, 'num_leaves': 10, 'max_depth': 6, 'min_child_samples': 4, 'subsample': 0.6291143816065536, 'colsample_bytree': 0.6082936155138831, 'n_estimators': 1250, 'min_split_gain': 0.0}. Best is trial 10 with value: 0.3874589160986159.

Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:47:07,698] Trial 12 finished with value: 0.3874589160986159 and parameters: {'learning_rate': 0.03, 'num_leaves': 10, 'max_depth': 6, 'min_child_samples': 4, 'subsample': 0.6004487667685937, 'colsample_bytree': 0.6068625768545342, 'n_estimators': 1250, 'min_split_gain': 0.0}. Best is trial 10 with value: 0.3874589160986159.

Fold 1
Fold 2

[I 2025-09-08 21:47:08,138] Trial 13 finished with value: 0.3271478377116556 and parameters: {'learning_rate': 0.03, 'num_leaves': 10, 'max_depth': 5, 'min_child_samples': 5, 'subsample': 0.6468295901355077, 'colsample_bytree': 0.6058752854212595, 'n_estimators': 1250, 'min_split_gain': 0.0}. Best is trial 10 with value: 0.3874589160986159.

Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:47:08,613] Trial 14 finished with value: 0.38454028709783356 and parameters: {'learning_rate': 0.03, 'num_leaves': 10, 'max_depth': 7, 'min_child_samples': 4, 'subsample': 0.714857645353256, 'colsample_bytree': 0.6396800918987156, 'n_estimators': 1250, 'min_split_gain': 0.0}. Best is trial 10 with value: 0.3874589160986159.

Fold 1
Fold 2

[I 2025-09-08 21:47:09,094] Trial 15 finished with value: 0.3272659960875239 and parameters: {'learning_rate': 0.03, 'num_leaves': 10, 'max_depth': 6, 'min_child_samples': 5, 'subsample': 0.6391803623975661, 'colsample_bytree': 0.6351171657153711, 'n_estimators': 1250, 'min_split_gain': 0.0}. Best is trial 10 with value: 0.3874589160986159.

Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:47:09,574] Trial 16 finished with value: 0.3836162757681833 and parameters: {'learning_rate': 0.03, 'num_leaves': 10, 'max_depth': 7, 'min_child_samples': 4, 'subsample': 0.6849712620798795, 'colsample_bytree': 0.699917093126499, 'n_estimators': 1250, 'min_split_gain': 0.0}. Best is trial 10 with value: 0.3874589160986159.
[I 2025-09-08 21:47:09,720] Trial 17 finished with value: 0.36246173523274905 and parameters: {'learning_rate': 0.03, 'num_leaves': 10, 'max_depth': 5, 'min_child_samples': 5, 'subsample': 0.6256267121493098, 'colsample_bytree': 0.6270362504898659, 'n_estimators': 1250, 'min_split_gain': 1.0}. Best is trial 10 with value: 0.3874589160986159.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 21:47:09,885] Trial 18 finished with value: 0.3142285204521749 and parameters: {'learning_rate': 0.03, 'num_leaves': 10, 'max_depth': 6, 'min_child_samples': 6, 'subsample': 0.6645922852525955, 'colsample_bytree': 0.6627219768365447, 'n_estimators': 1250, 'min_split_gain': 0.5}. Best is trial 10 with value: 0.3874589160986159.

Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:47:10,475] Trial 19 finished with value: 0.37076827044126043 and parameters: {'learning_rate': 0.03, 'num_leaves': 30, 'max_depth': 7, 'min_child_samples': 4, 'subsample': 0.7153154125766107, 'colsample_bytree': 0.6013003199770192, 'n_estimators': 1250, 'min_split_gain': 0.0}. Best is trial 10 with value: 0.3874589160986159.

Fold 1
Fold 2

[I 2025-09-08 21:47:10,897] Trial 20 finished with value: 0.3141980519688961 and parameters: {'learning_rate': 0.03, 'num_leaves': 10, 'max_depth': 5, 'min_child_samples': 5, 'subsample': 0.6012745017989124, 'colsample_bytree': 0.707123820330268, 'n_estimators': 1250, 'min_split_gain': 0.0}. Best is trial 10 with value: 0.3874589160986159.

Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:47:11,410] Trial 21 finished with value: 0.3874589160986159 and parameters: {'learning_rate': 0.03, 'num_leaves': 10, 'max_depth': 6, 'min_child_samples': 4, 'subsample': 0.6023848335249593, 'colsample_bytree': 0.6182875648964444, 'n_estimators': 1250, 'min_split_gain': 0.0}. Best is trial 10 with value: 0.3874589160986159.

Fold 1
Fold 2

[I 2025-09-08 21:47:11,872] Trial 22 finished with value: 0.3920812585846694 and parameters: {'learning_rate': 0.03, 'num_leaves': 10, 'max_depth': 6, 'min_child_samples': 4, 'subsample': 0.6249841748544112, 'colsample_bytree': 0.6506784009297264, 'n_estimators': 1250, 'min_split_gain': 0.0}. Best is trial 22 with value: 0.3920812585846694.

Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:47:12,320] Trial 23 finished with value: 0.3920812585846694 and parameters: {'learning_rate': 0.03, 'num_leaves': 10, 'max_depth': 6, 'min_child_samples': 4, 'subsample': 0.6323102613778924, 'colsample_bytree': 0.6501528181958575, 'n_estimators': 1250, 'min_split_gain': 0.0}. Best is trial 22 with value: 0.3920812585846694.

Fold 1
Fold 2

[I 2025-09-08 21:47:12,773] Trial 24 finished with value: 0.3466738115761319 and parameters: {'learning_rate': 0.03, 'num_leaves': 10, 'max_depth': 6, 'min_child_samples': 5, 'subsample': 0.6604494065214783, 'colsample_bytree': 0.655834150531478, 'n_estimators': 1250, 'min_split_gain': 0.0}. Best is trial 22 with value: 0.3920812585846694.

Fold 3
Fold 1

[I 2025-09-08 21:47:12,946] Trial 25 finished with value: 0.4026974067876619 and parameters: {'learning_rate': 0.03, 'num_leaves': 10, 'max_depth': 7, 'min_child_samples': 4, 'subsample': 0.6229830936949696, 'colsample_bytree': 0.683999239984165, 'n_estimators': 1250, 'min_split_gain': 0.5}. Best is trial 25 with value: 0.4026974067876619.

Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 21:47:13,141] Trial 26 finished with value: 0.37081497167418814 and parameters: {'learning_rate': 0.03, 'num_leaves': 10, 'max_depth': 7, 'min_child_samples': 5, 'subsample': 0.6622264287702319, 'colsample_bytree': 0.6832308765623166, 'n_estimators': 1250, 'min_split_gain': 0.5}. Best is trial 25 with value: 0.4026974067876619.

Fold 3
Fold 1
Fold 2

[I 2025-09-08 21:47:13,341] Trial 27 finished with value: 0.41742332746196426 and parameters: {'learning_rate': 0.04, 'num_leaves': 10, 'max_depth': 7, 'min_child_samples': 4, 'subsample': 0.6131611884477942, 'colsample_bytree': 0.6470763076923975, 'n_estimators': 1250, 'min_split_gain': 0.5}. Best is trial 27 with value: 0.41742332746196426.

Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:47:13,532] Trial 28 finished with value: 0.33120333428500576 and parameters: {'learning_rate': 0.04, 'num_leaves': 30, 'max_depth': 7, 'min_child_samples': 8, 'subsample': 0.6166269574772733, 'colsample_bytree': 0.6777884415006356, 'n_estimators': 1250, 'min_split_gain': 0.5}. Best is trial 27 with value: 0.41742332746196426.
[I 2025-09-08 21:47:13,687] Trial 29 finished with value: 0.3336888359144412 and parameters: {'learning_rate': 0.04, 'num_leaves': 20, 'max_depth': 8, 'min_child_samples': 6, 'subsample': 0.6958882449526691, 'colsample_bytree': 0.7129473218229216, 'n_estimators': 750, 'min_split_gain': 0.5}. Best is trial 27 with value: 0.41742332746196426.
[I 2025-09-08 21:47:13,689] A new study created in memory with name: no-name-54071982-3c9d-4130-93ec-3d2c3d7f6579
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

✅ LBM con C2X-Complex_rhown_9x9_depth_in_3_4 - Mejor R2: 0.42
📋 Parámetros: {'learning_rate': 0.04, 'num_leaves': 10, 'max_depth': 7, 'min_child_samples': 4, 'subsample': 0.6131611884477942, 'colsample_bytree': 0.6470763076923975, 'n_estimators': 1250, 'min_split_gain': 0.5}

Buscando mejores hiperparámetros para MLP con C2X-Complex_rhown_9x9_depth_in_3_4...
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 21:47:15,167] Trial 0 finished with value: 0.25461353482433574 and parameters: {'hidden_layer_sizes': (128,), 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.005347008192286331, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00012646049359934847}. Best is trial 0 with value: 0.25461353482433574.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 21:47:16,616] Trial 1 finished with value: 0.46428646223975883 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.005901805746773447, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0016773507148959744}. Best is trial 1 with value: 0.46428646223975883.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 21:47:17,769] Trial 2 finished with value: 0.4451305120030556 and parameters: {'hidden_layer_sizes': (128,), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.019156774136261136, 'learning_rate': 'constant', 'learning_rate_init': 0.0006709456402458118}. Best is trial 1 with value: 0.46428646223975883.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 21:47:18,357] Trial 3 finished with value: 0.37915737602279703 and parameters: {'hidden_layer_sizes': (32,), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.02288528860392056, 'learning_rate': 'adaptive', 'learning_rate_init': 0.000863651011292243}. Best is trial 1 with value: 0.46428646223975883.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:47:19,250] Trial 4 finished with value: 0.445294758257803 and parameters: {'hidden_layer_sizes': (128,), 'activation': 'tanh', 'solver': 'adam', 'alpha': 5.3128108996164135e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.006657332902983413}. Best is trial 1 with value: 0.46428646223975883.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:47:19,767] Trial 5 finished with value: 0.4221939580983314 and parameters: {'hidden_layer_sizes': (32,), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0001915546648965714, 'learning_rate': 'adaptive', 'learning_rate_init': 0.005892685420016288}. Best is trial 1 with value: 0.46428646223975883.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 21:47:21,106] Trial 6 finished with value: 0.3728667904981063 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.00022390222165199239, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0002971556514540153}. Best is trial 1 with value: 0.46428646223975883.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:47:21,863] Trial 7 finished with value: 0.3906314777153466 and parameters: {'hidden_layer_sizes': (64,), 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.0007307659851547286, 'learning_rate': 'constant', 'learning_rate_init': 0.00702442255777853}. Best is trial 1 with value: 0.46428646223975883.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 21:47:23,383] Trial 8 finished with value: 0.3199737890093089 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.00011441296917287615, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00010217272745011944}. Best is trial 1 with value: 0.46428646223975883.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 21:47:24,795] Trial 9 finished with value: 0.4017164448003456 and parameters: {'hidden_layer_sizes': (64,), 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.026361136230303957, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0018771643224504916}. Best is trial 1 with value: 0.46428646223975883.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 21:47:25,924] Trial 10 finished with value: 0.44615865279937833 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.0025758041180862154, 'learning_rate': 'constant', 'learning_rate_init': 0.0021778043100077354}. Best is trial 1 with value: 0.46428646223975883.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 21:47:27,229] Trial 11 finished with value: 0.43987518477653814 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.002222941049269001, 'learning_rate': 'constant', 'learning_rate_init': 0.0018347947775697016}. Best is trial 1 with value: 0.46428646223975883.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 21:47:28,316] Trial 12 finished with value: 0.4458851031379045 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.0044181930411459035, 'learning_rate': 'constant', 'learning_rate_init': 0.0025510548603950977}. Best is trial 1 with value: 0.46428646223975883.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 21:47:29,314] Trial 13 finished with value: 0.4375281679052903 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.09240342630488445, 'learning_rate': 'constant', 'learning_rate_init': 0.0033882768843497293}. Best is trial 1 with value: 0.46428646223975883.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 21:47:30,871] Trial 14 finished with value: 0.41562206063709944 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'sgd', 'alpha': 1.4042065917825803e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.0005987003495454309}. Best is trial 1 with value: 0.46428646223975883.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 21:47:32,138] Trial 15 finished with value: 0.43302726974910105 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.0011511025263039798, 'learning_rate': 'constant', 'learning_rate_init': 0.0013148494894493947}. Best is trial 1 with value: 0.46428646223975883.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 21:47:33,800] Trial 16 finished with value: 0.4664829197354428 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.0072762484813276625, 'learning_rate': 'adaptive', 'learning_rate_init': 0.003808276538031299}. Best is trial 16 with value: 0.4664829197354428.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 21:47:35,110] Trial 17 finished with value: 0.4282603200774051 and parameters: {'hidden_layer_sizes': (64,), 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.008779667301418857, 'learning_rate': 'adaptive', 'learning_rate_init': 0.004563909256014514}. Best is trial 16 with value: 0.4664829197354428.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:47:35,621] Trial 18 finished with value: 0.3999745494207607 and parameters: {'hidden_layer_sizes': (32,), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.09080394574204996, 'learning_rate': 'adaptive', 'learning_rate_init': 0.009581748353781448}. Best is trial 16 with value: 0.4664829197354428.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 21:47:37,314] Trial 19 finished with value: 0.4551758811570752 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.0005017412750042533, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0012450480987199685}. Best is trial 16 with value: 0.4664829197354428.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 21:47:38,975] Trial 20 finished with value: 0.38097964089925546 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.015610305960228357, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0003449559627772489}. Best is trial 16 with value: 0.4664829197354428.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 21:47:40,628] Trial 21 finished with value: 0.44951612610666397 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.000695794471921217, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0010897996246730993}. Best is trial 16 with value: 0.4664829197354428.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 21:47:42,272] Trial 22 finished with value: 0.4631256045895669 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.0015776545956093927, 'learning_rate': 'adaptive', 'learning_rate_init': 0.001597833249742911}. Best is trial 16 with value: 0.4664829197354428.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 21:47:43,957] Trial 23 finished with value: 0.4684994499656798 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.001574034904994127, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0033321988037929486}. Best is trial 23 with value: 0.4684994499656798.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 21:47:45,367] Trial 24 finished with value: 0.46880740571105567 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.008470702703954933, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0032379114477279823}. Best is trial 24 with value: 0.46880740571105567.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 21:47:46,880] Trial 25 finished with value: 0.4690278297034482 and parameters: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.009624616811702286, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0031558267239436767}. Best is trial 25 with value: 0.4690278297034482.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:47:47,819] Trial 26 finished with value: 0.4514121914887362 and parameters: {'hidden_layer_sizes': (128,), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0387870198757773, 'learning_rate': 'adaptive', 'learning_rate_init': 0.002967709212446879}. Best is trial 25 with value: 0.4690278297034482.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 21:47:49,116] Trial 27 finished with value: 0.4308078909200946 and parameters: {'hidden_layer_sizes': (64,), 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.0031315621855827493, 'learning_rate': 'adaptive', 'learning_rate_init': 0.004449308360978282}. Best is trial 25 with value: 0.4690278297034482.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 21:47:50,131] Trial 28 finished with value: 0.3375846762793089 and parameters: {'hidden_layer_sizes': (32,), 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.0116420663712657, 'learning_rate': 'adaptive', 'learning_rate_init': 0.009308914533356479}. Best is trial 25 with value: 0.4690278297034482.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (32,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (128,) which is of type tuple.
  warnings.warn(message)
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/optuna/distributions.py:518: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (64, 16) which is of type tuple.
  warnings.warn(message)

Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-08 21:47:51,616] Trial 29 finished with value: 0.43593901538691293 and parameters: {'hidden_layer_sizes': (128,), 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.03967293515966501, 'learning_rate': 'adaptive', 'learning_rate_init': 0.002624412195540775}. Best is trial 25 with value: 0.4690278297034482.
[I 2025-09-08 21:47:51,618] A new study created in memory with name: no-name-c9a9ab76-6b4b-4d95-ba1b-4aa8781ed3c1
[I 2025-09-08 21:47:51,685] Trial 0 finished with value: 0.434579096888905 and parameters: {'C': 0.7875908937621762, 'epsilon': 0.18856963372054655}. Best is trial 0 with value: 0.434579096888905.
[I 2025-09-08 21:47:51,746] Trial 1 finished with value: 0.4952198363675688 and parameters: {'C': 4.819321164987268, 'epsilon': 0.026465135422288795}. Best is trial 1 with value: 0.4952198363675688.
[I 2025-09-08 21:47:51,803] Trial 2 finished with value: 0.49292782699576776 and parameters: {'C': 5.133169085692021, 'epsilon': 0.06235233351354361}. Best is trial 1 with value: 0.4952198363675688.

✅ MLP con C2X-Complex_rhown_9x9_depth_in_3_4 - Mejor R2: 0.47
📋 Parámetros: {'hidden_layer_sizes': (64, 16), 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.009624616811702286, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0031558267239436767}

Buscando mejores hiperparámetros para SVR con C2X-Complex_rhown_9x9_depth_in_3_4...
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 21:47:51,851] Trial 3 finished with value: 0.2502327325514811 and parameters: {'C': 0.13443267204313844, 'epsilon': 0.16783926111475342}. Best is trial 1 with value: 0.4952198363675688.
[I 2025-09-08 21:47:51,905] Trial 4 finished with value: 0.3288543610750902 and parameters: {'C': 0.2815918246115618, 'epsilon': 0.11239282971932467}. Best is trial 1 with value: 0.4952198363675688.
[I 2025-09-08 21:47:51,973] Trial 5 finished with value: 0.33979852120316306 and parameters: {'C': 0.31578380769672154, 'epsilon': 0.029044603413577848}. Best is trial 1 with value: 0.4952198363675688.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 21:47:52,049] Trial 6 finished with value: 0.4959653326454205 and parameters: {'C': 4.131643252745697, 'epsilon': 0.07609859643296543}. Best is trial 6 with value: 0.4959653326454205.
[I 2025-09-08 21:47:52,109] Trial 7 finished with value: 0.4892031298206689 and parameters: {'C': 5.716846864503603, 'epsilon': 0.023190897359315954}. Best is trial 6 with value: 0.4959653326454205.
[I 2025-09-08 21:47:52,166] Trial 8 finished with value: 0.49274198635244426 and parameters: {'C': 4.319575888057592, 'epsilon': 0.139381609677004}. Best is trial 6 with value: 0.4959653326454205.
[I 2025-09-08 21:47:52,216] Trial 9 finished with value: 0.40969471684719555 and parameters: {'C': 0.5689821869302394, 'epsilon': 0.09902435827269755}. Best is trial 6 with value: 0.4959653326454205.

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 21:47:52,276] Trial 10 finished with value: 0.48915445828937393 and parameters: {'C': 1.8486035169715307, 'epsilon': 0.08299912381896116}. Best is trial 6 with value: 0.4959653326454205.
[I 2025-09-08 21:47:52,348] Trial 11 finished with value: 0.48772579613313355 and parameters: {'C': 2.0613570521398032, 'epsilon': 0.04689656924302392}. Best is trial 6 with value: 0.4959653326454205.
[I 2025-09-08 21:47:52,428] Trial 12 finished with value: 0.4562600308503913 and parameters: {'C': 9.22479870608467, 'epsilon': 0.01088273858570015}. Best is trial 6 with value: 0.4959653326454205.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 21:47:52,492] Trial 13 finished with value: 0.49456039730331086 and parameters: {'C': 2.2966169235978917, 'epsilon': 0.06377700635386528}. Best is trial 6 with value: 0.4959653326454205.
[I 2025-09-08 21:47:52,566] Trial 14 finished with value: 0.4588617756759061 and parameters: {'C': 8.954127323575602, 'epsilon': 0.04274130420971436}. Best is trial 6 with value: 0.4959653326454205.
[I 2025-09-08 21:47:52,624] Trial 15 finished with value: 0.5026056497132885 and parameters: {'C': 2.9754002881137316, 'epsilon': 0.12759858235761026}. Best is trial 15 with value: 0.5026056497132885.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 21:47:52,681] Trial 16 finished with value: 0.48243733131321936 and parameters: {'C': 1.3354166338485245, 'epsilon': 0.13947046461570287}. Best is trial 15 with value: 0.5026056497132885.
[I 2025-09-08 21:47:52,745] Trial 17 finished with value: 0.502915261404742 and parameters: {'C': 2.6702985848490384, 'epsilon': 0.1288925295789405}. Best is trial 17 with value: 0.502915261404742.
[I 2025-09-08 21:47:52,816] Trial 18 finished with value: 0.5024778877014565 and parameters: {'C': 2.887699015267493, 'epsilon': 0.13543683432395967}. Best is trial 17 with value: 0.502915261404742.

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:47:52,874] Trial 19 finished with value: 0.4695849880381318 and parameters: {'C': 1.1286997855846017, 'epsilon': 0.11227580685116544}. Best is trial 17 with value: 0.502915261404742.
[I 2025-09-08 21:47:52,933] Trial 20 finished with value: 0.4202946815963653 and parameters: {'C': 0.6271168844904005, 'epsilon': 0.16812368046552015}. Best is trial 17 with value: 0.502915261404742.
[I 2025-09-08 21:47:53,018] Trial 21 finished with value: 0.5027756859362297 and parameters: {'C': 2.6916527025284585, 'epsilon': 0.1372734237527474}. Best is trial 17 with value: 0.502915261404742.
[I 2025-09-08 21:47:53,079] Trial 22 finished with value: 0.502849343065759 and parameters: {'C': 2.8938319003952984, 'epsilon': 0.12581630307230054}. Best is trial 17 with value: 0.502915261404742.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:47:53,140] Trial 23 finished with value: 0.48771478918065786 and parameters: {'C': 1.486555491094591, 'epsilon': 0.15830001298436994}. Best is trial 17 with value: 0.502915261404742.
[I 2025-09-08 21:47:53,204] Trial 24 finished with value: 0.5015814074896359 and parameters: {'C': 3.015944412797657, 'epsilon': 0.152239741192086}. Best is trial 17 with value: 0.502915261404742.
[I 2025-09-08 21:47:53,267] Trial 25 finished with value: 0.4731296326985966 and parameters: {'C': 7.245344275960195, 'epsilon': 0.09779449679346573}. Best is trial 17 with value: 0.502915261404742.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 21:47:53,325] Trial 26 finished with value: 0.44746181839769084 and parameters: {'C': 0.8951438517332851, 'epsilon': 0.12090500598658344}. Best is trial 17 with value: 0.502915261404742.
[I 2025-09-08 21:47:53,391] Trial 27 finished with value: 0.4923486658206588 and parameters: {'C': 3.4298124053927146, 'epsilon': 0.19348177255499788}. Best is trial 17 with value: 0.502915261404742.
[I 2025-09-08 21:47:53,455] Trial 28 finished with value: 0.4926729041927677 and parameters: {'C': 1.745644953317379, 'epsilon': 0.15026677270140992}. Best is trial 17 with value: 0.502915261404742.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 21:47:53,514] Trial 29 finished with value: 0.49878383772346896 and parameters: {'C': 2.408403295802129, 'epsilon': 0.17890739360919167}. Best is trial 17 with value: 0.502915261404742.
[I 2025-09-08 21:47:53,515] A new study created in memory with name: no-name-9511b4a6-254c-4b46-a5d9-e85c484364ac
[I 2025-09-08 21:47:53,560] Trial 0 finished with value: 0.2895221314388748 and parameters: {'n_neighbors': 4, 'leaf_size': 34}. Best is trial 0 with value: 0.2895221314388748.
[I 2025-09-08 21:47:53,609] Trial 1 finished with value: 0.28193232736231016 and parameters: {'n_neighbors': 3, 'leaf_size': 16}. Best is trial 0 with value: 0.2895221314388748.
[I 2025-09-08 21:47:53,657] Trial 2 finished with value: 0.4108025286502049 and parameters: {'n_neighbors': 10, 'leaf_size': 37}. Best is trial 2 with value: 0.4108025286502049.

Fold 3

✅ SVR con C2X-Complex_rhown_9x9_depth_in_3_4 - Mejor R2: 0.50
📋 Parámetros: {'C': 2.6702985848490384, 'epsilon': 0.1288925295789405}

Buscando mejores hiperparámetros para KNN con C2X-Complex_rhown_9x9_depth_in_3_4...
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:47:53,701] Trial 3 finished with value: 0.2895221314388748 and parameters: {'n_neighbors': 4, 'leaf_size': 37}. Best is trial 2 with value: 0.4108025286502049.
[I 2025-09-08 21:47:53,745] Trial 4 finished with value: 0.3836867978105021 and parameters: {'n_neighbors': 6, 'leaf_size': 16}. Best is trial 2 with value: 0.4108025286502049.
[I 2025-09-08 21:47:53,793] Trial 5 finished with value: 0.41314169426441044 and parameters: {'n_neighbors': 8, 'leaf_size': 13}. Best is trial 5 with value: 0.41314169426441044.
[I 2025-09-08 21:47:53,836] Trial 6 finished with value: 0.41314169426441044 and parameters: {'n_neighbors': 8, 'leaf_size': 19}. Best is trial 5 with value: 0.41314169426441044.
[I 2025-09-08 21:47:53,878] Trial 7 finished with value: 0.2895221314388748 and parameters: {'n_neighbors': 4, 'leaf_size': 35}. Best is trial 5 with value: 0.41314169426441044.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:47:53,921] Trial 8 finished with value: 0.358502994888832 and parameters: {'n_neighbors': 5, 'leaf_size': 10}. Best is trial 5 with value: 0.41314169426441044.
[I 2025-09-08 21:47:53,969] Trial 9 finished with value: 0.4046864936449714 and parameters: {'n_neighbors': 9, 'leaf_size': 15}. Best is trial 5 with value: 0.41314169426441044.
[I 2025-09-08 21:47:54,029] Trial 10 finished with value: 0.40234045093938353 and parameters: {'n_neighbors': 12, 'leaf_size': 27}. Best is trial 5 with value: 0.41314169426441044.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 21:47:54,146] Trial 11 finished with value: 0.41314169426441044 and parameters: {'n_neighbors': 8, 'leaf_size': 23}. Best is trial 5 with value: 0.41314169426441044.
[I 2025-09-08 21:47:54,204] Trial 12 finished with value: 0.4108737022148497 and parameters: {'n_neighbors': 7, 'leaf_size': 22}. Best is trial 5 with value: 0.41314169426441044.
[I 2025-09-08 21:47:54,265] Trial 13 finished with value: 0.4108025286502049 and parameters: {'n_neighbors': 10, 'leaf_size': 11}. Best is trial 5 with value: 0.41314169426441044.
[I 2025-09-08 21:47:54,317] Trial 14 finished with value: 0.4108737022148497 and parameters: {'n_neighbors': 7, 'leaf_size': 20}. Best is trial 5 with value: 0.41314169426441044.

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 21:47:54,369] Trial 15 finished with value: 0.4046864936449714 and parameters: {'n_neighbors': 9, 'leaf_size': 29}. Best is trial 5 with value: 0.41314169426441044.
[I 2025-09-08 21:47:54,426] Trial 16 finished with value: 0.41026575069328697 and parameters: {'n_neighbors': 11, 'leaf_size': 18}. Best is trial 5 with value: 0.41314169426441044.
[I 2025-09-08 21:47:54,481] Trial 17 finished with value: 0.41314169426441044 and parameters: {'n_neighbors': 8, 'leaf_size': 13}. Best is trial 5 with value: 0.41314169426441044.
[I 2025-09-08 21:47:54,531] Trial 18 finished with value: 0.4046864936449714 and parameters: {'n_neighbors': 9, 'leaf_size': 19}. Best is trial 5 with value: 0.41314169426441044.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 21:47:54,582] Trial 19 finished with value: 0.3836867978105021 and parameters: {'n_neighbors': 6, 'leaf_size': 30}. Best is trial 5 with value: 0.41314169426441044.
[I 2025-09-08 21:47:54,711] Trial 20 finished with value: 0.3836867978105021 and parameters: {'n_neighbors': 6, 'leaf_size': 24}. Best is trial 5 with value: 0.41314169426441044.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 21:47:54,781] Trial 21 finished with value: 0.41314169426441044 and parameters: {'n_neighbors': 8, 'leaf_size': 23}. Best is trial 5 with value: 0.41314169426441044.
[I 2025-09-08 21:47:54,841] Trial 22 finished with value: 0.41314169426441044 and parameters: {'n_neighbors': 8, 'leaf_size': 21}. Best is trial 5 with value: 0.41314169426441044.
[I 2025-09-08 21:47:54,901] Trial 23 finished with value: 0.4108737022148497 and parameters: {'n_neighbors': 7, 'leaf_size': 13}. Best is trial 5 with value: 0.41314169426441044.
[I 2025-09-08 21:47:54,956] Trial 24 finished with value: 0.4108025286502049 and parameters: {'n_neighbors': 10, 'leaf_size': 26}. Best is trial 5 with value: 0.41314169426441044.

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:47:55,011] Trial 25 finished with value: 0.4046864936449714 and parameters: {'n_neighbors': 9, 'leaf_size': 18}. Best is trial 5 with value: 0.41314169426441044.
[I 2025-09-08 21:47:55,065] Trial 26 finished with value: 0.41314169426441044 and parameters: {'n_neighbors': 8, 'leaf_size': 13}. Best is trial 5 with value: 0.41314169426441044.
[I 2025-09-08 21:47:55,124] Trial 27 finished with value: 0.41026575069328697 and parameters: {'n_neighbors': 11, 'leaf_size': 17}. Best is trial 5 with value: 0.41314169426441044.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:47:55,176] Trial 28 finished with value: 0.4108737022148497 and parameters: {'n_neighbors': 7, 'leaf_size': 25}. Best is trial 5 with value: 0.41314169426441044.
[I 2025-09-08 21:47:55,228] Trial 29 finished with value: 0.358502994888832 and parameters: {'n_neighbors': 5, 'leaf_size': 30}. Best is trial 5 with value: 0.41314169426441044.
[I 2025-09-08 21:47:55,229] A new study created in memory with name: no-name-1afc911a-acd5-487e-b964-ae16bed44d21
[I 2025-09-08 21:47:55,358] Trial 0 finished with value: 0.3725799562927563 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 0 with value: 0.3725799562927563.

Fold 1
Fold 2
Fold 3

✅ KNN con C2X-Complex_rhown_9x9_depth_in_3_4 - Mejor R2: 0.41
📋 Parámetros: {'n_neighbors': 8, 'leaf_size': 13}

Buscando mejores hiperparámetros para LR con C2X-Complex_rhown_9x9_depth_in_3_4...
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 21:47:55,448] Trial 1 finished with value: 0.3725799562927563 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 0 with value: 0.3725799562927563.
[I 2025-09-08 21:47:55,525] Trial 2 finished with value: 0.3725799562927563 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 0 with value: 0.3725799562927563.
[I 2025-09-08 21:47:55,589] Trial 3 finished with value: 0.37257995629547214 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 3 with value: 0.37257995629547214.

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 21:47:55,662] Trial 4 finished with value: 0.3725799562927563 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 3 with value: 0.37257995629547214.
[I 2025-09-08 21:47:55,728] Trial 5 finished with value: 0.3712160079690565 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 3 with value: 0.37257995629547214.
[I 2025-09-08 21:47:55,775] Trial 6 finished with value: 0.3712160079690648 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 3 with value: 0.37257995629547214.
[I 2025-09-08 21:47:55,825] Trial 7 finished with value: 0.37257995629547214 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 3 with value: 0.37257995629547214.

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 21:47:55,880] Trial 8 finished with value: 0.3712160079690648 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 3 with value: 0.37257995629547214.
[I 2025-09-08 21:47:55,925] Trial 9 finished with value: 0.3712160079690565 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 3 with value: 0.37257995629547214.
[I 2025-09-08 21:47:55,992] Trial 10 finished with value: 0.37257995629547214 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 3 with value: 0.37257995629547214.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 21:47:56,141] Trial 11 finished with value: 0.37257995629547214 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 3 with value: 0.37257995629547214.
[I 2025-09-08 21:47:56,247] Trial 12 finished with value: 0.37257995629547214 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 3 with value: 0.37257995629547214.

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 21:47:56,341] Trial 13 finished with value: 0.37257995629547214 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 3 with value: 0.37257995629547214.
[I 2025-09-08 21:47:56,431] Trial 14 finished with value: 0.37257995629547214 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 3 with value: 0.37257995629547214.

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:47:56,557] Trial 15 finished with value: 0.37257995629547214 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 3 with value: 0.37257995629547214.
[I 2025-09-08 21:47:56,634] Trial 16 finished with value: 0.37257995629547214 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 3 with value: 0.37257995629547214.
[I 2025-09-08 21:47:56,697] Trial 17 finished with value: 0.37257995629547214 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 3 with value: 0.37257995629547214.
[I 2025-09-08 21:47:56,751] Trial 18 finished with value: 0.3712160079690565 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 3 with value: 0.37257995629547214.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 21:47:56,809] Trial 19 finished with value: 0.37257995629547214 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 3 with value: 0.37257995629547214.
[I 2025-09-08 21:47:56,867] Trial 20 finished with value: 0.37257995629547214 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 3 with value: 0.37257995629547214.
[I 2025-09-08 21:47:56,934] Trial 21 finished with value: 0.37257995629547214 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 3 with value: 0.37257995629547214.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:47:57,005] Trial 22 finished with value: 0.37257995629547214 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 3 with value: 0.37257995629547214.
[I 2025-09-08 21:47:57,156] Trial 23 finished with value: 0.37257995629547214 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 3 with value: 0.37257995629547214.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:47:57,230] Trial 24 finished with value: 0.37257995629547214 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 3 with value: 0.37257995629547214.
[I 2025-09-08 21:47:57,334] Trial 25 finished with value: 0.37257995629547214 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 3 with value: 0.37257995629547214.
[I 2025-09-08 21:47:57,423] Trial 26 finished with value: 0.3712160079690565 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 3 with value: 0.37257995629547214.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 21:47:57,483] Trial 27 finished with value: 0.37257995629547214 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 3 with value: 0.37257995629547214.
[I 2025-09-08 21:47:57,547] Trial 28 finished with value: 0.37257995629547214 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 3 with value: 0.37257995629547214.
[I 2025-09-08 21:47:57,621] Trial 29 finished with value: 0.3725799562927563 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 3 with value: 0.37257995629547214.
[I 2025-09-08 21:47:57,622] A new study created in memory with name: no-name-570a7afa-74c3-4b55-af68-10de5e42acc2

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

✅ LR con C2X-Complex_rhown_9x9_depth_in_3_4 - Mejor R2: 0.37
📋 Parámetros: {'fit_intercept': False, 'positive': False}

Buscando mejores hiperparámetros para RF con C2X-Complex_rhown_9x9_depth_in_3_4...
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:48:00,102] Trial 0 finished with value: 0.173711070645424 and parameters: {'n_estimators': 200, 'max_depth': 6, 'min_samples_split': 3, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 0 with value: 0.173711070645424.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:48:01,017] Trial 1 finished with value: 0.4146791079646564 and parameters: {'n_estimators': 100, 'max_depth': 9, 'min_samples_split': 5, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 1 with value: 0.4146791079646564.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:48:04,851] Trial 2 finished with value: 0.4129551349558256 and parameters: {'n_estimators': 400, 'max_depth': 9, 'min_samples_split': 4, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 1 with value: 0.4146791079646564.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:48:09,658] Trial 3 finished with value: 0.07861471496286976 and parameters: {'n_estimators': 400, 'max_depth': 8, 'min_samples_split': 7, 'min_samples_leaf': 6, 'bootstrap': False}. Best is trial 1 with value: 0.4146791079646564.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:48:12,348] Trial 4 finished with value: 0.06612965738461891 and parameters: {'n_estimators': 200, 'max_depth': 11, 'min_samples_split': 7, 'min_samples_leaf': 4, 'bootstrap': False}. Best is trial 1 with value: 0.4146791079646564.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:48:13,415] Trial 5 finished with value: 0.08029550549952069 and parameters: {'n_estimators': 100, 'max_depth': 5, 'min_samples_split': 6, 'min_samples_leaf': 6, 'bootstrap': False}. Best is trial 1 with value: 0.4146791079646564.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:48:14,323] Trial 6 finished with value: 0.41812817904282146 and parameters: {'n_estimators': 100, 'max_depth': 8, 'min_samples_split': 4, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 6 with value: 0.41812817904282146.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:48:15,919] Trial 7 finished with value: 0.410636717473486 and parameters: {'n_estimators': 200, 'max_depth': 12, 'min_samples_split': 3, 'min_samples_leaf': 6, 'bootstrap': True}. Best is trial 6 with value: 0.41812817904282146.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:48:16,694] Trial 8 finished with value: 0.414117386834502 and parameters: {'n_estimators': 100, 'max_depth': 7, 'min_samples_split': 4, 'min_samples_leaf': 8, 'bootstrap': True}. Best is trial 6 with value: 0.41812817904282146.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:48:20,950] Trial 9 finished with value: 0.08408081737404009 and parameters: {'n_estimators': 400, 'max_depth': 5, 'min_samples_split': 8, 'min_samples_leaf': 5, 'bootstrap': False}. Best is trial 6 with value: 0.41812817904282146.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:48:22,032] Trial 10 finished with value: 0.4095191981297453 and parameters: {'n_estimators': 100, 'max_depth': 10, 'min_samples_split': 2, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 6 with value: 0.41812817904282146.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:48:22,957] Trial 11 finished with value: 0.4146791079646564 and parameters: {'n_estimators': 100, 'max_depth': 9, 'min_samples_split': 5, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 6 with value: 0.41812817904282146.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:48:23,882] Trial 12 finished with value: 0.41812817904282146 and parameters: {'n_estimators': 100, 'max_depth': 8, 'min_samples_split': 5, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 6 with value: 0.41812817904282146.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:48:24,886] Trial 13 finished with value: 0.4141434231547829 and parameters: {'n_estimators': 100, 'max_depth': 7, 'min_samples_split': 4, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 6 with value: 0.41812817904282146.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:48:25,756] Trial 14 finished with value: 0.4135161973999702 and parameters: {'n_estimators': 100, 'max_depth': 7, 'min_samples_split': 6, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 6 with value: 0.41812817904282146.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:48:26,517] Trial 15 finished with value: 0.41426161091316516 and parameters: {'n_estimators': 100, 'max_depth': 8, 'min_samples_split': 2, 'min_samples_leaf': 8, 'bootstrap': True}. Best is trial 6 with value: 0.41812817904282146.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:48:27,512] Trial 16 finished with value: 0.40617761968522165 and parameters: {'n_estimators': 100, 'max_depth': 10, 'min_samples_split': 6, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 6 with value: 0.41812817904282146.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:48:28,315] Trial 17 finished with value: 0.41932344619979633 and parameters: {'n_estimators': 100, 'max_depth': 6, 'min_samples_split': 3, 'min_samples_leaf': 7, 'bootstrap': True}. Best is trial 17 with value: 0.41932344619979633.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:48:31,263] Trial 18 finished with value: 0.41836845100517744 and parameters: {'n_estimators': 400, 'max_depth': 6, 'min_samples_split': 3, 'min_samples_leaf': 7, 'bootstrap': True}. Best is trial 17 with value: 0.41932344619979633.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:48:34,256] Trial 19 finished with value: 0.41836845100517744 and parameters: {'n_estimators': 400, 'max_depth': 6, 'min_samples_split': 3, 'min_samples_leaf': 7, 'bootstrap': True}. Best is trial 17 with value: 0.41932344619979633.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:48:37,206] Trial 20 finished with value: 0.41836845100517744 and parameters: {'n_estimators': 400, 'max_depth': 6, 'min_samples_split': 2, 'min_samples_leaf': 7, 'bootstrap': True}. Best is trial 17 with value: 0.41932344619979633.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:48:40,146] Trial 21 finished with value: 0.41836845100517744 and parameters: {'n_estimators': 400, 'max_depth': 6, 'min_samples_split': 3, 'min_samples_leaf': 7, 'bootstrap': True}. Best is trial 17 with value: 0.41932344619979633.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:48:42,965] Trial 22 finished with value: 0.4171068377263126 and parameters: {'n_estimators': 400, 'max_depth': 5, 'min_samples_split': 3, 'min_samples_leaf': 7, 'bootstrap': True}. Best is trial 17 with value: 0.41932344619979633.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:48:45,840] Trial 23 finished with value: 0.41709273631090626 and parameters: {'n_estimators': 400, 'max_depth': 6, 'min_samples_split': 3, 'min_samples_leaf': 8, 'bootstrap': True}. Best is trial 17 with value: 0.41932344619979633.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:48:48,862] Trial 24 finished with value: 0.4189000750031074 and parameters: {'n_estimators': 400, 'max_depth': 7, 'min_samples_split': 2, 'min_samples_leaf': 7, 'bootstrap': True}. Best is trial 17 with value: 0.41932344619979633.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:48:52,014] Trial 25 finished with value: 0.41584270836370624 and parameters: {'n_estimators': 400, 'max_depth': 7, 'min_samples_split': 2, 'min_samples_leaf': 6, 'bootstrap': True}. Best is trial 17 with value: 0.41932344619979633.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:48:56,568] Trial 26 finished with value: 0.15294224861798147 and parameters: {'n_estimators': 400, 'max_depth': 7, 'min_samples_split': 2, 'min_samples_leaf': 7, 'bootstrap': False}. Best is trial 17 with value: 0.41932344619979633.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:48:57,990] Trial 27 finished with value: 0.41507618440884037 and parameters: {'n_estimators': 200, 'max_depth': 5, 'min_samples_split': 4, 'min_samples_leaf': 8, 'bootstrap': True}. Best is trial 17 with value: 0.41932344619979633.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:49:01,174] Trial 28 finished with value: 0.4120152958814831 and parameters: {'n_estimators': 400, 'max_depth': 6, 'min_samples_split': 2, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 17 with value: 0.41932344619979633.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:49:03,450] Trial 29 finished with value: 0.15300039126645795 and parameters: {'n_estimators': 200, 'max_depth': 7, 'min_samples_split': 3, 'min_samples_leaf': 7, 'bootstrap': False}. Best is trial 17 with value: 0.41932344619979633.
[I 2025-09-08 21:49:03,451] A new study created in memory with name: no-name-972ba9e5-cf55-456c-9ef3-15a9a2ff0b13

✅ RF con C2X-Complex_rhown_9x9_depth_in_3_4 - Mejor R2: 0.42
📋 Parámetros: {'n_estimators': 100, 'max_depth': 6, 'min_samples_split': 3, 'min_samples_leaf': 7, 'bootstrap': True}

Buscando mejores hiperparámetros para CAT con C2X-Complex_rhown_9x9_depth_in_3_4...
Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:49:28,773] Trial 0 finished with value: 0.3516563333778082 and parameters: {'iterations': 1000, 'learning_rate': 0.05, 'depth': 8, 'l2_leaf_reg': 2.796111613819799}. Best is trial 0 with value: 0.3516563333778082.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:49:47,972] Trial 1 finished with value: 0.38169592589802165 and parameters: {'iterations': 750, 'learning_rate': 0.04, 'depth': 8, 'l2_leaf_reg': 1.7742334191844265}. Best is trial 1 with value: 0.38169592589802165.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:49:58,293] Trial 2 finished with value: 0.3675753219808244 and parameters: {'iterations': 1000, 'learning_rate': 0.04, 'depth': 7, 'l2_leaf_reg': 1.8024395448635873}. Best is trial 1 with value: 0.38169592589802165.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:50:03,121] Trial 3 finished with value: 0.3267920097811575 and parameters: {'iterations': 1000, 'learning_rate': 0.04, 'depth': 6, 'l2_leaf_reg': 1.969879807191104}. Best is trial 1 with value: 0.38169592589802165.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:50:05,368] Trial 4 finished with value: 0.3006483948204788 and parameters: {'iterations': 750, 'learning_rate': 0.05, 'depth': 5, 'l2_leaf_reg': 1.8520086063613297}. Best is trial 1 with value: 0.38169592589802165.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:50:10,611] Trial 5 finished with value: 0.37838276724168846 and parameters: {'iterations': 500, 'learning_rate': 0.05, 'depth': 7, 'l2_leaf_reg': 2.837236307016007}. Best is trial 1 with value: 0.38169592589802165.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:50:12,746] Trial 6 finished with value: 0.2875470338500195 and parameters: {'iterations': 1000, 'learning_rate': 0.02, 'depth': 4, 'l2_leaf_reg': 1.702078086947815}. Best is trial 1 with value: 0.38169592589802165.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:50:25,131] Trial 7 finished with value: 0.3970790834264542 and parameters: {'iterations': 500, 'learning_rate': 0.04, 'depth': 8, 'l2_leaf_reg': 4.598607323487992}. Best is trial 7 with value: 0.3970790834264542.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:50:27,089] Trial 8 finished with value: 0.2994657763383775 and parameters: {'iterations': 1000, 'learning_rate': 0.03, 'depth': 4, 'l2_leaf_reg': 4.119917977377466}. Best is trial 7 with value: 0.3970790834264542.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:50:32,372] Trial 9 finished with value: 0.38387804050748553 and parameters: {'iterations': 500, 'learning_rate': 0.02, 'depth': 7, 'l2_leaf_reg': 2.5856440618137095}. Best is trial 7 with value: 0.3970790834264542.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:50:34,635] Trial 10 finished with value: 0.38584983413216856 and parameters: {'iterations': 500, 'learning_rate': 0.03, 'depth': 6, 'l2_leaf_reg': 4.9820789170385495}. Best is trial 7 with value: 0.3970790834264542.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:50:36,892] Trial 11 finished with value: 0.38010296835311386 and parameters: {'iterations': 500, 'learning_rate': 0.03, 'depth': 6, 'l2_leaf_reg': 4.940817138645028}. Best is trial 7 with value: 0.3970790834264542.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:50:38,479] Trial 12 finished with value: 0.3499881059922578 and parameters: {'iterations': 500, 'learning_rate': 0.03, 'depth': 5, 'l2_leaf_reg': 4.957196902351476}. Best is trial 7 with value: 0.3970790834264542.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:50:40,099] Trial 13 finished with value: 0.3119555416847591 and parameters: {'iterations': 500, 'learning_rate': 0.04, 'depth': 5, 'l2_leaf_reg': 4.305060331765888}. Best is trial 7 with value: 0.3970790834264542.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:50:45,340] Trial 14 finished with value: 0.3870173515868876 and parameters: {'iterations': 500, 'learning_rate': 0.03, 'depth': 7, 'l2_leaf_reg': 3.8252811677197935}. Best is trial 7 with value: 0.3970790834264542.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:50:57,436] Trial 15 finished with value: 0.37784315719275385 and parameters: {'iterations': 500, 'learning_rate': 0.03, 'depth': 8, 'l2_leaf_reg': 3.620874677519268}. Best is trial 7 with value: 0.3970790834264542.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:51:02,698] Trial 16 finished with value: 0.3810865837549155 and parameters: {'iterations': 500, 'learning_rate': 0.04, 'depth': 7, 'l2_leaf_reg': 3.622736758687242}. Best is trial 7 with value: 0.3970790834264542.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:51:21,108] Trial 17 finished with value: 0.39032136928371397 and parameters: {'iterations': 750, 'learning_rate': 0.02, 'depth': 8, 'l2_leaf_reg': 4.218930389547981}. Best is trial 7 with value: 0.3970790834264542.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:51:39,369] Trial 18 finished with value: 0.3916703728187307 and parameters: {'iterations': 750, 'learning_rate': 0.02, 'depth': 8, 'l2_leaf_reg': 4.455612002906544}. Best is trial 7 with value: 0.3970790834264542.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:51:57,825] Trial 19 finished with value: 0.3907694490253834 and parameters: {'iterations': 750, 'learning_rate': 0.02, 'depth': 8, 'l2_leaf_reg': 3.3150528992908717}. Best is trial 7 with value: 0.3970790834264542.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:52:16,857] Trial 20 finished with value: 0.3875499523629135 and parameters: {'iterations': 750, 'learning_rate': 0.02, 'depth': 8, 'l2_leaf_reg': 1.2120649910884418}. Best is trial 7 with value: 0.3970790834264542.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:52:35,245] Trial 21 finished with value: 0.3881581521460799 and parameters: {'iterations': 750, 'learning_rate': 0.02, 'depth': 8, 'l2_leaf_reg': 3.240059614744805}. Best is trial 7 with value: 0.3970790834264542.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:52:53,429] Trial 22 finished with value: 0.39423592328187596 and parameters: {'iterations': 750, 'learning_rate': 0.02, 'depth': 8, 'l2_leaf_reg': 4.461274572686802}. Best is trial 7 with value: 0.3970790834264542.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:53:00,809] Trial 23 finished with value: 0.38536908694847766 and parameters: {'iterations': 750, 'learning_rate': 0.02, 'depth': 7, 'l2_leaf_reg': 4.588105405515336}. Best is trial 7 with value: 0.3970790834264542.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:53:18,865] Trial 24 finished with value: 0.3859188162783434 and parameters: {'iterations': 750, 'learning_rate': 0.02, 'depth': 8, 'l2_leaf_reg': 4.535918852204642}. Best is trial 7 with value: 0.3970790834264542.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:53:26,565] Trial 25 finished with value: 0.3755702884298136 and parameters: {'iterations': 750, 'learning_rate': 0.04, 'depth': 7, 'l2_leaf_reg': 4.580338230729587}. Best is trial 7 with value: 0.3970790834264542.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:53:44,741] Trial 26 finished with value: 0.39658924323159184 and parameters: {'iterations': 750, 'learning_rate': 0.02, 'depth': 8, 'l2_leaf_reg': 4.035351417326998}. Best is trial 7 with value: 0.3970790834264542.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:53:48,375] Trial 27 finished with value: 0.3516169919267966 and parameters: {'iterations': 750, 'learning_rate': 0.02, 'depth': 6, 'l2_leaf_reg': 3.8131054772412174}. Best is trial 7 with value: 0.3970790834264542.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:54:07,001] Trial 28 finished with value: 0.3889252038932978 and parameters: {'iterations': 750, 'learning_rate': 0.04, 'depth': 8, 'l2_leaf_reg': 4.000697672122689}. Best is trial 7 with value: 0.3970790834264542.

Fold 1
Fold 2
Fold 3

[I 2025-09-08 21:54:14,742] Trial 29 finished with value: 0.3593124015771398 and parameters: {'iterations': 750, 'learning_rate': 0.05, 'depth': 7, 'l2_leaf_reg': 2.4977773260909295}. Best is trial 7 with value: 0.3970790834264542.
[I 2025-09-08 21:54:14,744] A new study created in memory with name: no-name-d80429a3-d1ed-4ce6-b116-c085f07b7a64
[I 2025-09-08 21:54:14,808] Trial 0 finished with value: 0.39243686939186473 and parameters: {'alpha': 0.03422708043803173, 'l1_ratio': 0.6922923105601329}. Best is trial 0 with value: 0.39243686939186473.
[I 2025-09-08 21:54:14,883] Trial 1 finished with value: 0.38684220487640414 and parameters: {'alpha': 0.10452220541759713, 'l1_ratio': 0.22558751997590482}. Best is trial 0 with value: 0.39243686939186473.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.088e+02, tolerance: 4.779e-02
  model = cd_fast.enet_coordinate_descent(

✅ CAT con C2X-Complex_rhown_9x9_depth_in_3_4 - Mejor R2: 0.40
📋 Parámetros: {'iterations': 500, 'learning_rate': 0.04, 'depth': 8, 'l2_leaf_reg': 4.598607323487992}

Buscando mejores hiperparámetros para ELN con C2X-Complex_rhown_9x9_depth_in_3_4...
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.783e+01, tolerance: 4.223e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.580e+01, tolerance: 3.136e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:54:15,002] Trial 2 finished with value: 0.4021914370744209 and parameters: {'alpha': 0.00022295940701543045, 'l1_ratio': 0.29482167476731824}. Best is trial 2 with value: 0.4021914370744209.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.670e+01, tolerance: 4.779e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.155e+01, tolerance: 4.223e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.549e+01, tolerance: 3.136e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:54:15,107] Trial 3 finished with value: 0.4003330091542736 and parameters: {'alpha': 0.0002873309380606896, 'l1_ratio': 0.8300696759420053}. Best is trial 2 with value: 0.4021914370744209.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.753e+01, tolerance: 4.779e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.776e+00, tolerance: 4.223e-02
  model = cd_fast.enet_coordinate_descent(

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.935e+01, tolerance: 3.136e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:54:15,196] Trial 4 finished with value: 0.3953802035322835 and parameters: {'alpha': 0.0012793954324101509, 'l1_ratio': 0.6682883940148526}. Best is trial 2 with value: 0.4021914370744209.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.875e-02, tolerance: 4.223e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:54:15,322] Trial 5 finished with value: 0.40138701918323116 and parameters: {'alpha': 0.010230222720776198, 'l1_ratio': 0.4110149112663698}. Best is trial 2 with value: 0.4021914370744209.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.737e+01, tolerance: 4.779e-02
  model = cd_fast.enet_coordinate_descent(

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.509e+00, tolerance: 4.223e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.908e+01, tolerance: 3.136e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:54:15,463] Trial 6 finished with value: 0.39524954595967965 and parameters: {'alpha': 0.0012812392917114675, 'l1_ratio': 0.6794761030712043}. Best is trial 2 with value: 0.4021914370744209.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.641e-01, tolerance: 3.136e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:54:15,591] Trial 7 finished with value: 0.39792325613914853 and parameters: {'alpha': 0.006481364914097041, 'l1_ratio': 0.7915659637494202}. Best is trial 2 with value: 0.4021914370744209.

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 21:54:15,707] Trial 8 finished with value: 0.2452288594771063 and parameters: {'alpha': 0.8708217756780205, 'l1_ratio': 0.4939846946775094}. Best is trial 2 with value: 0.4021914370744209.
[I 2025-09-08 21:54:15,827] Trial 9 finished with value: 0.3740521452411231 and parameters: {'alpha': 0.11563179965039577, 'l1_ratio': 0.4060794567042022}. Best is trial 2 with value: 0.4021914370744209.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.166e+02, tolerance: 4.779e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.332e+01, tolerance: 4.223e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.486e+01, tolerance: 3.136e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:54:15,971] Trial 10 finished with value: 0.4027723914109318 and parameters: {'alpha': 0.00016056282793201377, 'l1_ratio': 0.10265906242732448}. Best is trial 10 with value: 0.4027723914109318.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.163e+02, tolerance: 4.779e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.311e+01, tolerance: 4.223e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.423e+01, tolerance: 3.136e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:54:16,130] Trial 11 finished with value: 0.4027519496801791 and parameters: {'alpha': 0.0001582371876240497, 'l1_ratio': 0.11583013415364674}. Best is trial 10 with value: 0.4027723914109318.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.165e+02, tolerance: 4.779e-02
  model = cd_fast.enet_coordinate_descent(

Fold 3
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.315e+01, tolerance: 4.223e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.527e+01, tolerance: 3.136e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:54:16,315] Trial 12 finished with value: 0.4027243490849322 and parameters: {'alpha': 0.000110972495276223, 'l1_ratio': 0.14096781160398647}. Best is trial 10 with value: 0.4027723914109318.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.991e+01, tolerance: 4.779e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.592e+01, tolerance: 4.223e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.505e+01, tolerance: 3.136e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:54:16,441] Trial 13 finished with value: 0.4023822960395808 and parameters: {'alpha': 0.0007883733357270822, 'l1_ratio': 0.10855635168755842}. Best is trial 10 with value: 0.4027723914109318.

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.118e+01, tolerance: 4.779e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.986e+01, tolerance: 4.223e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.378e+01, tolerance: 3.136e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:54:16,594] Trial 14 finished with value: 0.4015112071211357 and parameters: {'alpha': 0.000570736986435307, 'l1_ratio': 0.25076869825414316}. Best is trial 10 with value: 0.4027723914109318.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.127e+01, tolerance: 4.779e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.297e+01, tolerance: 4.223e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.956e+01, tolerance: 3.136e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:54:16,720] Trial 15 finished with value: 0.4009114367621078 and parameters: {'alpha': 0.0024091896796393213, 'l1_ratio': 0.18161873945248613}. Best is trial 10 with value: 0.4027723914109318.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.241e+00, tolerance: 4.779e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.298e+00, tolerance: 4.223e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.494e+01, tolerance: 3.136e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:54:16,864] Trial 16 finished with value: 0.4023395698983327 and parameters: {'alpha': 0.004079730287184008, 'l1_ratio': 0.34601227426066294}. Best is trial 10 with value: 0.4027723914109318.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.172e+02, tolerance: 4.779e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.361e+01, tolerance: 4.223e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.683e+01, tolerance: 3.136e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:54:17,010] Trial 17 finished with value: 0.4027564357097824 and parameters: {'alpha': 0.00010595856682005831, 'l1_ratio': 0.10374538568317027}. Best is trial 10 with value: 0.4027723914109318.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.314e+01, tolerance: 4.779e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.760e+01, tolerance: 4.223e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.287e+01, tolerance: 3.136e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:54:17,168] Trial 18 finished with value: 0.4006213267321425 and parameters: {'alpha': 0.00042534354065441524, 'l1_ratio': 0.5451055818194277}. Best is trial 10 with value: 0.4027723914109318.

Fold 3
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.135e+02, tolerance: 4.779e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.113e+01, tolerance: 4.223e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.890e+01, tolerance: 3.136e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:54:17,267] Trial 19 finished with value: 0.40255530498757564 and parameters: {'alpha': 0.00011078495468797137, 'l1_ratio': 0.31906873936387914}. Best is trial 10 with value: 0.4027723914109318.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.370e-01, tolerance: 4.779e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.470e-01, tolerance: 4.223e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.613e-01, tolerance: 3.136e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:54:17,365] Trial 20 finished with value: 0.404017837264983 and parameters: {'alpha': 0.014121604263515133, 'l1_ratio': 0.21101591762738398}. Best is trial 20 with value: 0.404017837264983.

Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.607e-02, tolerance: 4.779e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.166e-01, tolerance: 4.223e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.151e-02, tolerance: 3.136e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:54:17,560] Trial 21 finished with value: 0.40385682524555727 and parameters: {'alpha': 0.019412713829136022, 'l1_ratio': 0.19790161277613777}. Best is trial 20 with value: 0.404017837264983.

Fold 2
Fold 3
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.507e-01, tolerance: 4.779e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.138e-01, tolerance: 4.223e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.869e-02, tolerance: 3.136e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:54:17,676] Trial 22 finished with value: 0.4038600191198965 and parameters: {'alpha': 0.017039139152437894, 'l1_ratio': 0.21677026109583059}. Best is trial 20 with value: 0.404017837264983.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.778e-02, tolerance: 4.779e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.138e-01, tolerance: 4.223e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.750e-02, tolerance: 3.136e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:54:17,792] Trial 23 finished with value: 0.4037695174827678 and parameters: {'alpha': 0.018967955949889904, 'l1_ratio': 0.21262593588980155}. Best is trial 20 with value: 0.404017837264983.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 21:54:17,867] Trial 24 finished with value: 0.39440865228507205 and parameters: {'alpha': 0.05270152003026899, 'l1_ratio': 0.373478035170802}. Best is trial 20 with value: 0.404017837264983.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.378e-01, tolerance: 4.779e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.631e-02, tolerance: 3.136e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-08 21:54:17,977] Trial 25 finished with value: 0.4033805856384188 and parameters: {'alpha': 0.017624368693479858, 'l1_ratio': 0.26615811833233494}. Best is trial 20 with value: 0.404017837264983.

Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2

[I 2025-09-08 21:54:18,055] Trial 26 finished with value: 0.36845456809233684 and parameters: {'alpha': 0.18744144590199352, 'l1_ratio': 0.45226095150006834}. Best is trial 20 with value: 0.404017837264983.
[I 2025-09-08 21:54:18,140] Trial 27 finished with value: 0.40413355338744994 and parameters: {'alpha': 0.03453451436006177, 'l1_ratio': 0.18176328613460752}. Best is trial 27 with value: 0.40413355338744994.
[I 2025-09-08 21:54:18,218] Trial 28 finished with value: 0.3471287754341286 and parameters: {'alpha': 0.2903248123277917, 'l1_ratio': 0.5947684788554036}. Best is trial 27 with value: 0.40413355338744994.

Fold 3
Fold 1
Fold 2
Fold 3
Fold 1
Fold 2
Fold 3
Fold 1

[I 2025-09-08 21:54:18,324] Trial 29 finished with value: 0.4042913943139886 and parameters: {'alpha': 0.032098193805296736, 'l1_ratio': 0.1837190983843505}. Best is trial 29 with value: 0.4042913943139886.

Fold 2
Fold 3

✅ ELN con C2X-Complex_rhown_9x9_depth_in_3_4 - Mejor R2: 0.40
📋 Parámetros: {'alpha': 0.032098193805296736, 'l1_ratio': 0.1837190983843505}

In [94]:
global_results

{('C2X-Complex_rhow_9x9_depth_in_0_1',
  'XGB'): {'best_params': {'n_estimators': 750,
   'learning_rate': 0.02,
   'max_depth': 6,
   'min_child_weight': 4,
   'subsample': 0.6334861078851525,
   'colsample_bytree': 0.6000710318679877}, 'best_score': 0.662},
 ('C2X-Complex_rhow_9x9_depth_in_0_1',
  'LBM'): {'best_params': {'learning_rate': 0.05,
   'num_leaves': 10,
   'max_depth': 5,
   'min_child_samples': 8,
   'subsample': 0.7259907325916005,
   'colsample_bytree': 0.633176440623437,
   'n_estimators': 1250,
   'min_split_gain': 0.5}, 'best_score': 0.635},
 ('C2X-Complex_rhow_9x9_depth_in_0_1',
  'MLP'): {'best_params': {'hidden_layer_sizes': (64, 16),
   'activation': 'tanh',
   'solver': 'sgd',
   'alpha': 0.0001622339998571086,
   'learning_rate': 'adaptive',
   'learning_rate_init': 0.0022028189935992017}, 'best_score': 0.573},
 ('C2X-Complex_rhow_9x9_depth_in_0_1',
  'SVR'): {'best_params': {'C': 9.78208231963643,
   'epsilon': 0.08246384108501315}, 'best_score': 0.671},
 ('C2X-Complex_rhow_9x9_depth_in_0_1',
  'KNN'): {'best_params': {'n_neighbors': 11,
   'leaf_size': 37}, 'best_score': 0.597},
 ('C2X-Complex_rhow_9x9_depth_in_0_1',
  'LR'): {'best_params': {'fit_intercept': False,
   'positive': True}, 'best_score': 0.331},
 ('C2X-Complex_rhow_9x9_depth_in_0_1',
  'RF'): {'best_params': {'n_estimators': 100,
   'max_depth': 9,
   'min_samples_split': 5,
   'min_samples_leaf': 3,
   'bootstrap': True}, 'best_score': 0.594},
 ('C2X-Complex_rhow_9x9_depth_in_0_1',
  'CAT'): {'best_params': {'iterations': 500,
   'learning_rate': 0.02,
   'depth': 7,
   'l2_leaf_reg': 3.5964392231010223}, 'best_score': 0.676},
 ('C2X-Complex_rhow_9x9_depth_in_0_1',
  'ELN'): {'best_params': {'alpha': 0.03518157122089253,
   'l1_ratio': 0.7470948791846247}, 'best_score': 0.493},
 ('TOA_15x15_depth_in_0_1',
  'XGB'): {'best_params': {'n_estimators': 1250,
   'learning_rate': 0.02,
   'max_depth': 8,
   'min_child_weight': 4,
   'subsample': 0.790084319824438,
   'colsample_bytree': 0.6527647392264622}, 'best_score': 0.639},
 ('TOA_15x15_depth_in_0_1',
  'LBM'): {'best_params': {'learning_rate': 0.03,
   'num_leaves': 30,
   'max_depth': 5,
   'min_child_samples': 4,
   'subsample': 0.7384720618088759,
   'colsample_bytree': 0.6346737332463599,
   'n_estimators': 1250,
   'min_split_gain': 0.2}, 'best_score': 0.717},
 ('TOA_15x15_depth_in_0_1',
  'MLP'): {'best_params': {'hidden_layer_sizes': (64,),
   'activation': 'tanh',
   'solver': 'adam',
   'alpha': 2.268523901902573e-05,
   'learning_rate': 'adaptive',
   'learning_rate_init': 0.0064466547378883785}, 'best_score': 0.709},
 ('TOA_15x15_depth_in_0_1',
  'SVR'): {'best_params': {'C': 9.942430237500371,
   'epsilon': 0.19667119801787789}, 'best_score': 0.317},
 ('TOA_15x15_depth_in_0_1',
  'KNN'): {'best_params': {'n_neighbors': 3,
   'leaf_size': 24}, 'best_score': 0.723},
 ('TOA_15x15_depth_in_0_1',
  'LR'): {'best_params': {'fit_intercept': False,
   'positive': False}, 'best_score': 0.268},
 ('TOA_15x15_depth_in_0_1',
  'RF'): {'best_params': {'n_estimators': 400,
   'max_depth': 6,
   'min_samples_split': 5,
   'min_samples_leaf': 6,
   'bootstrap': False}, 'best_score': 0.701},
 ('TOA_15x15_depth_in_0_1',
  'CAT'): {'best_params': {'iterations': 750,
   'learning_rate': 0.04,
   'depth': 7,
   'l2_leaf_reg': 2.1220488084336058}, 'best_score': 0.751},
 ('TOA_15x15_depth_in_0_1',
  'ELN'): {'best_params': {'alpha': 0.0001032226579017661,
   'l1_ratio': 0.4226718006683823}, 'best_score': 0.481},
 ('C2X-Complex_rhown_9x9_depth_in_0_1',
  'XGB'): {'best_params': {'n_estimators': 750,
   'learning_rate': 0.01,
   'max_depth': 6,
   'min_child_weight': 3,
   'subsample': 0.7790147015003476,
   'colsample_bytree': 0.690555218802008}, 'best_score': 0.624},
 ('C2X-Complex_rhown_9x9_depth_in_0_1',
  'LBM'): {'best_params': {'learning_rate': 0.02,
   'num_leaves': 10,
   'max_depth': 6,
   'min_child_samples': 7,
   'subsample': 0.617309342651074,
   'colsample_bytree': 0.7565036261875273,
   'n_estimators': 750,
   'min_split_gain': 0.2}, 'best_score': 0.634},
 ('C2X-Complex_rhown_9x9_depth_in_0_1',
  'MLP'): {'best_params': {'hidden_layer_sizes': (64,),
   'activation': 'tanh',
   'solver': 'adam',
   'alpha': 0.016261522896903958,
   'learning_rate': 'constant',
   'learning_rate_init': 0.009911545325337816}, 'best_score': 0.653},
 ('C2X-Complex_rhown_9x9_depth_in_0_1',
  'SVR'): {'best_params': {'C': 9.795469538168005,
   'epsilon': 0.15605458842314468}, 'best_score': 0.666},
 ('C2X-Complex_rhown_9x9_depth_in_0_1',
  'KNN'): {'best_params': {'n_neighbors': 10,
   'leaf_size': 30}, 'best_score': 0.605},
 ('C2X-Complex_rhown_9x9_depth_in_0_1',
  'LR'): {'best_params': {'fit_intercept': False,
   'positive': True}, 'best_score': 0.37},
 ('C2X-Complex_rhown_9x9_depth_in_0_1',
  'RF'): {'best_params': {'n_estimators': 400,
   'max_depth': 6,
   'min_samples_split': 5,
   'min_samples_leaf': 2,
   'bootstrap': True}, 'best_score': 0.578},
 ('C2X-Complex_rhown_9x9_depth_in_0_1',
  'CAT'): {'best_params': {'iterations': 500,
   'learning_rate': 0.03,
   'depth': 8,
   'l2_leaf_reg': 1.9647128702130359}, 'best_score': 0.65},
 ('C2X-Complex_rhown_9x9_depth_in_0_1',
  'ELN'): {'best_params': {'alpha': 0.011573102037621203,
   'l1_ratio': 0.4672375332372809}, 'best_score': 0.536},
 ('C2X-Complex_rhow_5x5_depth_in_0_1',
  'XGB'): {'best_params': {'n_estimators': 750,
   'learning_rate': 0.02,
   'max_depth': 7,
   'min_child_weight': 2,
   'subsample': 0.6027404644951201,
   'colsample_bytree': 0.6015786622193016}, 'best_score': 0.457},
 ('C2X-Complex_rhow_5x5_depth_in_0_1',
  'LBM'): {'best_params': {'learning_rate': 0.03,
   'num_leaves': 10,
   'max_depth': 7,
   'min_child_samples': 8,
   'subsample': 0.6335124270397844,
   'colsample_bytree': 0.6197372828743114,
   'n_estimators': 750,
   'min_split_gain': 0.5}, 'best_score': 0.538},
 ('C2X-Complex_rhow_5x5_depth_in_0_1',
  'MLP'): {'best_params': {'hidden_layer_sizes': (64, 16),
   'activation': 'tanh',
   'solver': 'adam',
   'alpha': 8.543562608013794e-05,
   'learning_rate': 'adaptive',
   'learning_rate_init': 0.0020164253666941343}, 'best_score': 0.562},
 ('C2X-Complex_rhow_5x5_depth_in_0_1',
  'SVR'): {'best_params': {'C': 9.880206563670095,
   'epsilon': 0.152552721395346}, 'best_score': 0.664},
 ('C2X-Complex_rhow_5x5_depth_in_0_1',
  'KNN'): {'best_params': {'n_neighbors': 12,
   'leaf_size': 39}, 'best_score': 0.64},
 ('C2X-Complex_rhow_5x5_depth_in_0_1',
  'LR'): {'best_params': {'fit_intercept': True,
   'positive': True}, 'best_score': 0.39},
 ('C2X-Complex_rhow_5x5_depth_in_0_1',
  'RF'): {'best_params': {'n_estimators': 400,
   'max_depth': 10,
   'min_samples_split': 2,
   'min_samples_leaf': 2,
   'bootstrap': True}, 'best_score': 0.475},
 ('C2X-Complex_rhow_5x5_depth_in_0_1',
  'CAT'): {'best_params': {'iterations': 500,
   'learning_rate': 0.05,
   'depth': 8,
   'l2_leaf_reg': 2.7792625209450668}, 'best_score': 0.628},
 ('C2X-Complex_rhow_5x5_depth_in_0_1',
  'ELN'): {'best_params': {'alpha': 0.0013451928757631797,
   'l1_ratio': 0.8616384894558748}, 'best_score': 0.491},
 ('C2RCC_rhow_5x5_depth_in_0_1',
  'XGB'): {'best_params': {'n_estimators': 750,
   'learning_rate': 0.01,
   'max_depth': 5,
   'min_child_weight': 4,
   'subsample': 0.6178589201946612,
   'colsample_bytree': 0.6190888742563266}, 'best_score': 0.685},
 ('C2RCC_rhow_5x5_depth_in_0_1',
  'LBM'): {'best_params': {'learning_rate': 0.05,
   'num_leaves': 30,
   'max_depth': 6,
   'min_child_samples': 8,
   'subsample': 0.7535275735884176,
   'colsample_bytree': 0.6159216457154343,
   'n_estimators': 1000,
   'min_split_gain': 0.5}, 'best_score': 0.634},
 ('C2RCC_rhow_5x5_depth_in_0_1',
  'MLP'): {'best_params': {'hidden_layer_sizes': (64,),
   'activation': 'tanh',
   'solver': 'adam',
   'alpha': 0.09210129371566216,
   'learning_rate': 'constant',
   'learning_rate_init': 0.0099307176842141}, 'best_score': 0.719},
 ('C2RCC_rhow_5x5_depth_in_0_1',
  'SVR'): {'best_params': {'C': 9.912167069518391,
   'epsilon': 0.11177152401996852}, 'best_score': 0.698},
 ('C2RCC_rhow_5x5_depth_in_0_1',
  'KNN'): {'best_params': {'n_neighbors': 5,
   'leaf_size': 23}, 'best_score': 0.736},
 ('C2RCC_rhow_5x5_depth_in_0_1',
  'LR'): {'best_params': {'fit_intercept': True,
   'positive': False}, 'best_score': 0.474},
 ('C2RCC_rhow_5x5_depth_in_0_1',
  'RF'): {'best_params': {'n_estimators': 200,
   'max_depth': 5,
   'min_samples_split': 4,
   'min_samples_leaf': 3,
   'bootstrap': True}, 'best_score': 0.592},
 ('C2RCC_rhow_5x5_depth_in_0_1',
  'CAT'): {'best_params': {'iterations': 500,
   'learning_rate': 0.02,
   'depth': 8,
   'l2_leaf_reg': 2.2630596294284766}, 'best_score': 0.718},
 ('C2RCC_rhow_5x5_depth_in_0_1',
  'ELN'): {'best_params': {'alpha': 0.0009469354922941979,
   'l1_ratio': 0.35616314548110306}, 'best_score': 0.587},
 ('C2RCC_rhow_15x15_depth_in_0_1',
  'XGB'): {'best_params': {'n_estimators': 750,
   'learning_rate': 0.03,
   'max_depth': 6,
   'min_child_weight': 2,
   'subsample': 0.7816969089720872,
   'colsample_bytree': 0.7307805247383148}, 'best_score': 0.609},
 ('C2RCC_rhow_15x15_depth_in_0_1',
  'LBM'): {'best_params': {'learning_rate': 0.02,
   'num_leaves': 30,
   'max_depth': 6,
   'min_child_samples': 8,
   'subsample': 0.7099963188356267,
   'colsample_bytree': 0.679053255292279,
   'n_estimators': 1000,
   'min_split_gain': 0.5}, 'best_score': 0.587},
 ('C2RCC_rhow_15x15_depth_in_0_1',
  'MLP'): {'best_params': {'hidden_layer_sizes': (64, 16),
   'activation': 'relu',
   'solver': 'sgd',
   'alpha': 0.00019298335958285577,
   'learning_rate': 'adaptive',
   'learning_rate_init': 0.0024479575255152665}, 'best_score': 0.714},
 ('C2RCC_rhow_15x15_depth_in_0_1',
  'SVR'): {'best_params': {'C': 9.781358736437241,
   'epsilon': 0.12142420568214786}, 'best_score': 0.683},
 ('C2RCC_rhow_15x15_depth_in_0_1',
  'KNN'): {'best_params': {'n_neighbors': 4,
   'leaf_size': 30}, 'best_score': 0.715},
 ('C2RCC_rhow_15x15_depth_in_0_1',
  'LR'): {'best_params': {'fit_intercept': True,
   'positive': True}, 'best_score': -0.276},
 ('C2RCC_rhow_15x15_depth_in_0_1',
  'RF'): {'best_params': {'n_estimators': 400,
   'max_depth': 6,
   'min_samples_split': 5,
   'min_samples_leaf': 2,
   'bootstrap': True}, 'best_score': 0.537},
 ('C2RCC_rhow_15x15_depth_in_0_1',
  'CAT'): {'best_params': {'iterations': 750,
   'learning_rate': 0.05,
   'depth': 7,
   'l2_leaf_reg': 4.763102068203935}, 'best_score': 0.724},
 ('C2RCC_rhow_15x15_depth_in_0_1',
  'ELN'): {'best_params': {'alpha': 0.05540895560432349,
   'l1_ratio': 0.3729671525667103}, 'best_score': 0.493},
 ('C2X-Complex_rhown_15x15_depth_in_0_1',
  'XGB'): {'best_params': {'n_estimators': 1250,
   'learning_rate': 0.01,
   'max_depth': 7,
   'min_child_weight': 3,
   'subsample': 0.6164625817053201,
   'colsample_bytree': 0.6902992196449772}, 'best_score': 0.645},
 ('C2X-Complex_rhown_15x15_depth_in_0_1',
  'LBM'): {'best_params': {'learning_rate': 0.02,
   'num_leaves': 10,
   'max_depth': 8,
   'min_child_samples': 5,
   'subsample': 0.672243697884544,
   'colsample_bytree': 0.6375905588548606,
   'n_estimators': 1000,
   'min_split_gain': 0.2}, 'best_score': 0.656},
 ('C2X-Complex_rhown_15x15_depth_in_0_1',
  'MLP'): {'best_params': {'hidden_layer_sizes': (64, 16),
   'activation': 'relu',
   'solver': 'adam',
   'alpha': 6.21252528637522e-05,
   'learning_rate': 'constant',
   'learning_rate_init': 0.0011006207938633779}, 'best_score': 0.675},
 ('C2X-Complex_rhown_15x15_depth_in_0_1',
  'SVR'): {'best_params': {'C': 9.627069403738384,
   'epsilon': 0.010087236846022106}, 'best_score': 0.652},
 ('C2X-Complex_rhown_15x15_depth_in_0_1',
  'KNN'): {'best_params': {'n_neighbors': 3,
   'leaf_size': 35}, 'best_score': 0.746},
 ('C2X-Complex_rhown_15x15_depth_in_0_1',
  'LR'): {'best_params': {'fit_intercept': False,
   'positive': False}, 'best_score': 0.486},
 ('C2X-Complex_rhown_15x15_depth_in_0_1',
  'RF'): {'best_params': {'n_estimators': 100,
   'max_depth': 8,
   'min_samples_split': 4,
   'min_samples_leaf': 2,
   'bootstrap': True}, 'best_score': 0.587},
 ('C2X-Complex_rhown_15x15_depth_in_0_1',
  'CAT'): {'best_params': {'iterations': 750,
   'learning_rate': 0.03,
   'depth': 8,
   'l2_leaf_reg': 2.200977496232614}, 'best_score': 0.741},
 ('C2X-Complex_rhown_15x15_depth_in_0_1',
  'ELN'): {'best_params': {'alpha': 0.007966652969906986,
   'l1_ratio': 0.11046822473163945}, 'best_score': 0.565},
 ('C2RCC_rhown_5x5_depth_in_0_1',
  'XGB'): {'best_params': {'n_estimators': 750,
   'learning_rate': 0.01,
   'max_depth': 6,
   'min_child_weight': 3,
   'subsample': 0.6216370162715222,
   'colsample_bytree': 0.7792799161816585}, 'best_score': 0.713},
 ('C2RCC_rhown_5x5_depth_in_0_1',
  'LBM'): {'best_params': {'learning_rate': 0.02,
   'num_leaves': 20,
   'max_depth': 6,
   'min_child_samples': 7,
   'subsample': 0.761686864173508,
   'colsample_bytree': 0.6000895682252526,
   'n_estimators': 750,
   'min_split_gain': 0.0}, 'best_score': 0.697},
 ('C2RCC_rhown_5x5_depth_in_0_1',
  'MLP'): {'best_params': {'hidden_layer_sizes': (128,),
   'activation': 'relu',
   'solver': 'adam',
   'alpha': 0.0013166149028004104,
   'learning_rate': 'adaptive',
   'learning_rate_init': 0.009794501621781264}, 'best_score': 0.73},
 ('C2RCC_rhown_5x5_depth_in_0_1',
  'SVR'): {'best_params': {'C': 9.998729287630322,
   'epsilon': 0.12692976724644883}, 'best_score': 0.688},
 ('C2RCC_rhown_5x5_depth_in_0_1',
  'KNN'): {'best_params': {'n_neighbors': 6,
   'leaf_size': 25}, 'best_score': 0.719},
 ('C2RCC_rhown_5x5_depth_in_0_1',
  'LR'): {'best_params': {'fit_intercept': True,
   'positive': False}, 'best_score': 0.502},
 ('C2RCC_rhown_5x5_depth_in_0_1',
  'RF'): {'best_params': {'n_estimators': 100,
   'max_depth': 12,
   'min_samples_split': 3,
   'min_samples_leaf': 3,
   'bootstrap': True}, 'best_score': 0.634},
 ('C2RCC_rhown_5x5_depth_in_0_1',
  'CAT'): {'best_params': {'iterations': 1000,
   'learning_rate': 0.04,
   'depth': 7,
   'l2_leaf_reg': 4.560703028307181}, 'best_score': 0.722},
 ('C2RCC_rhown_5x5_depth_in_0_1',
  'ELN'): {'best_params': {'alpha': 0.0011356160371922882,
   'l1_ratio': 0.8248731233022716}, 'best_score': 0.588},
 ('C2X-Complex_rhow_15x15_depth_in_0_1',
  'XGB'): {'best_params': {'n_estimators': 750,
   'learning_rate': 0.01,
   'max_depth': 5,
   'min_child_weight': 3,
   'subsample': 0.6995853143595189,
   'colsample_bytree': 0.646363342514155}, 'best_score': 0.636},
 ('C2X-Complex_rhow_15x15_depth_in_0_1',
  'LBM'): {'best_params': {'learning_rate': 0.05,
   'num_leaves': 10,
   'max_depth': 6,
   'min_child_samples': 8,
   'subsample': 0.7348952583662651,
   'colsample_bytree': 0.7043033481121315,
   'n_estimators': 1250,
   'min_split_gain': 0.2}, 'best_score': 0.706},
 ('C2X-Complex_rhow_15x15_depth_in_0_1',
  'MLP'): {'best_params': {'hidden_layer_sizes': (64, 16),
   'activation': 'tanh',
   'solver': 'adam',
   'alpha': 0.00039038964368111323,
   'learning_rate': 'constant',
   'learning_rate_init': 0.008881325155552915}, 'best_score': 0.746},
 ('C2X-Complex_rhow_15x15_depth_in_0_1',
  'SVR'): {'best_params': {'C': 9.965216355595086,
   'epsilon': 0.09499823981142935}, 'best_score': 0.656},
 ('C2X-Complex_rhow_15x15_depth_in_0_1',
  'KNN'): {'best_params': {'n_neighbors': 4,
   'leaf_size': 22}, 'best_score': 0.695},
 ('C2X-Complex_rhow_15x15_depth_in_0_1',
  'LR'): {'best_params': {'fit_intercept': False,
   'positive': True}, 'best_score': 0.126},
 ('C2X-Complex_rhow_15x15_depth_in_0_1',
  'RF'): {'best_params': {'n_estimators': 400,
   'max_depth': 12,
   'min_samples_split': 4,
   'min_samples_leaf': 2,
   'bootstrap': True}, 'best_score': 0.591},
 ('C2X-Complex_rhow_15x15_depth_in_0_1',
  'CAT'): {'best_params': {'iterations': 500,
   'learning_rate': 0.02,
   'depth': 8,
   'l2_leaf_reg': 2.578872261607816}, 'best_score': 0.734},
 ('C2X-Complex_rhow_15x15_depth_in_0_1',
  'ELN'): {'best_params': {'alpha': 0.0031848139544228865,
   'l1_ratio': 0.7514439142517285}, 'best_score': 0.485},
 ('C2RCC_rhow_9x9_depth_in_0_1',
  'XGB'): {'best_params': {'n_estimators': 1000,
   'learning_rate': 0.03,
   'max_depth': 6,
   'min_child_weight': 2,
   'subsample': 0.740902848198941,
   'colsample_bytree': 0.6676605035450245}, 'best_score': 0.711},
 ('C2RCC_rhow_9x9_depth_in_0_1',
  'LBM'): {'best_params': {'learning_rate': 0.03,
   'num_leaves': 10,
   'max_depth': 5,
   'min_child_samples': 4,
   'subsample': 0.6548027366024081,
   'colsample_bytree': 0.6482497261377679,
   'n_estimators': 1250,
   'min_split_gain': 0.0}, 'best_score': 0.686},
 ('C2RCC_rhow_9x9_depth_in_0_1',
  'MLP'): {'best_params': {'hidden_layer_sizes': (64, 16),
   'activation': 'relu',
   'solver': 'adam',
   'alpha': 4.368298634962287e-05,
   'learning_rate': 'adaptive',
   'learning_rate_init': 0.003267617395494424}, 'best_score': 0.699},
 ('C2RCC_rhow_9x9_depth_in_0_1',
  'SVR'): {'best_params': {'C': 9.901011689105662,
   'epsilon': 0.13086701333039777}, 'best_score': 0.675},
 ('C2RCC_rhow_9x9_depth_in_0_1',
  'KNN'): {'best_params': {'n_neighbors': 3,
   'leaf_size': 38}, 'best_score': 0.763},
 ('C2RCC_rhow_9x9_depth_in_0_1',
  'LR'): {'best_params': {'fit_intercept': False,
   'positive': False}, 'best_score': 0.577},
 ('C2RCC_rhow_9x9_depth_in_0_1',
  'RF'): {'best_params': {'n_estimators': 100,
   'max_depth': 6,
   'min_samples_split': 4,
   'min_samples_leaf': 2,
   'bootstrap': True}, 'best_score': 0.615},
 ('C2RCC_rhow_9x9_depth_in_0_1',
  'CAT'): {'best_params': {'iterations': 750,
   'learning_rate': 0.05,
   'depth': 8,
   'l2_leaf_reg': 4.759935263347128}, 'best_score': 0.743},
 ('C2RCC_rhow_9x9_depth_in_0_1',
  'ELN'): {'best_params': {'alpha': 0.0009323650679869702,
   'l1_ratio': 0.22259088930153997}, 'best_score': 0.58}}

In [76]:
with open(f"training_results/selection_results_{depth}.pkl", "wb") as f:
    pickle.dump(global_results, f)

In [39]:
# Diccionario para agrupar parámetros por modelo
params_by_model = defaultdict(list)

# Agrupar best_params por modelo
for (df_name, model_name), result in global_results.items():
    best_params = result["best_params"]
    params_by_model[model_name].append(best_params)

# Crear DataFrames con medias y std por modelo
summary_stats = {}

for model_name, param_list in params_by_model.items():
    df_params = pd.DataFrame(param_list)

    # Filtramos solo columnas numéricas para calcular medias y std
    df_numeric = df_params.select_dtypes(include=[np.number])

    stats = pd.concat([df_numeric.mean().rename("mean"), df_numeric.std().rename("std")], axis=1)
    summary_stats[model_name] = stats

# Mostrar un ejemplo
summary_stats["LBM"]

                         mean         std
learning_rate        0.011264    0.006322
num_leaves          52.000000   21.499354
max_depth            6.800000    1.032796
min_child_samples    9.000000    3.366502
subsample            0.846105    0.135599
colsample_bytree     0.853437    0.094603
n_estimators       550.000000  158.113883

In [77]:
global_results

{('C2X-Complex_rhow_9x9_depth_in_0_1',
  'XGB'): {'best_params': {'n_estimators': 400,
   'learning_rate': 0.010130819207976474,
   'max_depth': 3,
   'min_child_weight': 4,
   'subsample': 0.6466932179565845,
   'colsample_bytree': 0.863252176802725,
   'reg_alpha': 4.690598830858826,
   'reg_lambda': 2.45182006997585}, 'best_score': 0.647},
 ('C2X-Complex_rhow_9x9_depth_in_0_1',
  'LBM'): {'best_params': {'learning_rate': 0.0180173396623031,
   'num_leaves': 10,
   'max_depth': 4,
   'min_child_samples': 7,
   'subsample': 0.9691353325596449,
   'colsample_bytree': 0.8647429278156027,
   'n_estimators': 400,
   'reg_alpha': 0.002205137562138462,
   'reg_lambda': 3.8972417461043776,
   'min_split_gain': 0.0}, 'best_score': 0.65},
 ('C2X-Complex_rhow_9x9_depth_in_0_1',
  'MLP'): {'best_params': {'hidden_layer_sizes': (128,),
   'activation': 'tanh',
   'solver': 'adam',
   'alpha': 0.0011908618164157352,
   'learning_rate': 'constant',
   'learning_rate_init': 0.0017720053047611522}, 'best_score': 0.61},
 ('C2X-Complex_rhow_9x9_depth_in_0_1',
  'SVR'): {'best_params': {'C': 3.9386384240176913,
   'epsilon': 0.13356302312909252}, 'best_score': 0.583},
 ('C2X-Complex_rhow_9x9_depth_in_0_1',
  'KNN'): {'best_params': {'n_neighbors': 11,
   'leaf_size': 31}, 'best_score': 0.597},
 ('C2X-Complex_rhow_9x9_depth_in_0_1',
  'LR'): {'best_params': {'fit_intercept': False,
   'positive': True}, 'best_score': 0.331},
 ('C2X-Complex_rhow_9x9_depth_in_0_1',
  'RF'): {'best_params': {'n_estimators': 1000,
   'max_depth': 5,
   'min_samples_split': 4,
   'min_samples_leaf': 2,
   'bootstrap': True}, 'best_score': 0.583},
 ('C2X-Complex_rhow_9x9_depth_in_0_1',
  'CAT'): {'best_params': {'iterations': 250,
   'learning_rate': 0.0756380808532654,
   'depth': 7,
   'l2_leaf_reg': 2.5411091406930897}, 'best_score': 0.675},
 ('C2X-Complex_rhow_9x9_depth_in_0_1',
  'ELN'): {'best_params': {'alpha': 0.011909689277147112,
   'l1_ratio': 0.6705067016233937}, 'best_score': 0.491},
 ('TOA_15x15_depth_in_0_1',
  'XGB'): {'best_params': {'n_estimators': 200,
   'learning_rate': 0.024471415345560892,
   'max_depth': 5,
   'min_child_weight': 4,
   'subsample': 0.7265771487440407,
   'colsample_bytree': 0.7775278664043689,
   'reg_alpha': 0.5613433496336138,
   'reg_lambda': 0.002550744579989708}, 'best_score': 0.627},
 ('TOA_15x15_depth_in_0_1',
  'LBM'): {'best_params': {'learning_rate': 0.02145535516045795,
   'num_leaves': 20,
   'max_depth': 3,
   'min_child_samples': 4,
   'subsample': 0.694504550531154,
   'colsample_bytree': 0.7080350560291987,
   'n_estimators': 400,
   'reg_alpha': 0.04488177599212278,
   'reg_lambda': 4.088104008042177,
   'min_split_gain': 1.0}, 'best_score': 0.708},
 ('TOA_15x15_depth_in_0_1',
  'MLP'): {'best_params': {'hidden_layer_sizes': (32,),
   'activation': 'tanh',
   'solver': 'adam',
   'alpha': 0.00015456085838171134,
   'learning_rate': 'adaptive',
   'learning_rate_init': 0.004321905618989237}, 'best_score': 0.573},
 ('TOA_15x15_depth_in_0_1',
  'SVR'): {'best_params': {'C': 3.1895539854205484,
   'epsilon': 0.18977910716291796}, 'best_score': 0.16},
 ('TOA_15x15_depth_in_0_1',
  'KNN'): {'best_params': {'n_neighbors': 6,
   'leaf_size': 17}, 'best_score': 0.685},
 ('TOA_15x15_depth_in_0_1',
  'LR'): {'best_params': {'fit_intercept': False,
   'positive': False}, 'best_score': 0.268},
 ('TOA_15x15_depth_in_0_1',
  'RF'): {'best_params': {'n_estimators': 250,
   'max_depth': 4,
   'min_samples_split': 4,
   'min_samples_leaf': 4,
   'bootstrap': False}, 'best_score': 0.676},
 ('TOA_15x15_depth_in_0_1',
  'CAT'): {'best_params': {'iterations': 500,
   'learning_rate': 0.0489561833218288,
   'depth': 7,
   'l2_leaf_reg': 4.107360431179985}, 'best_score': 0.748},
 ('TOA_15x15_depth_in_0_1',
  'ELN'): {'best_params': {'alpha': 0.0006904285328981824,
   'l1_ratio': 0.5643108754372316}, 'best_score': 0.477},
 ('C2X-Complex_rhown_9x9_depth_in_0_1',
  'XGB'): {'best_params': {'n_estimators': 800,
   'learning_rate': 0.01770672414044032,
   'max_depth': 4,
   'min_child_weight': 4,
   'subsample': 0.6601809216151284,
   'colsample_bytree': 0.8391852713063789,
   'reg_alpha': 7.564600608481072,
   'reg_lambda': 5.202422425136457}, 'best_score': 0.668},
 ('C2X-Complex_rhown_9x9_depth_in_0_1',
  'LBM'): {'best_params': {'learning_rate': 0.020544903012824623,
   'num_leaves': 30,
   'max_depth': 4,
   'min_child_samples': 4,
   'subsample': 0.8766068394586368,
   'colsample_bytree': 0.7785675443310818,
   'n_estimators': 200,
   'reg_alpha': 0.1949801950057403,
   'reg_lambda': 1.0757420053093538,
   'min_split_gain': 0.1}, 'best_score': 0.661},
 ('C2X-Complex_rhown_9x9_depth_in_0_1',
  'MLP'): {'best_params': {'hidden_layer_sizes': (64,),
   'activation': 'tanh',
   'solver': 'adam',
   'alpha': 0.049060660674847996,
   'learning_rate': 'constant',
   'learning_rate_init': 0.003087876915473385}, 'best_score': 0.647},
 ('C2X-Complex_rhown_9x9_depth_in_0_1',
  'SVR'): {'best_params': {'C': 4.7599704979394915,
   'epsilon': 0.09506214370520978}, 'best_score': 0.611},
 ('C2X-Complex_rhown_9x9_depth_in_0_1',
  'KNN'): {'best_params': {'n_neighbors': 11,
   'leaf_size': 17}, 'best_score': 0.6},
 ('C2X-Complex_rhown_9x9_depth_in_0_1',
  'LR'): {'best_params': {'fit_intercept': False,
   'positive': True}, 'best_score': 0.37},
 ('C2X-Complex_rhown_9x9_depth_in_0_1',
  'RF'): {'best_params': {'n_estimators': 500,
   'max_depth': 4,
   'min_samples_split': 4,
   'min_samples_leaf': 2,
   'bootstrap': True}, 'best_score': 0.575},
 ('C2X-Complex_rhown_9x9_depth_in_0_1',
  'CAT'): {'best_params': {'iterations': 250,
   'learning_rate': 0.042443431081201584,
   'depth': 7,
   'l2_leaf_reg': 4.644143785341621}, 'best_score': 0.646},
 ('C2X-Complex_rhown_9x9_depth_in_0_1',
  'ELN'): {'best_params': {'alpha': 0.010375237343643838,
   'l1_ratio': 0.7025948455573761}, 'best_score': 0.535}}

**Entrenamiento con los parámetros seleccionados**

In [78]:
results = {}

for nombre_df, df in list(dfs.items()):
    #print(nombre_df)
    df = df.iloc[:,4:]

    # Para usar solamente bandas, sin combinaciones
    # if 'TOA' in nombre_df:
    #     # TOA solamente con las bandas, parece que las combinaciones solo meten ruido
    #     df = df.iloc[:,np.r_[0:14, 58:60]]
    # if 'rhow' in nombre_df and 'rhown' not in nombre_df:
    #     df = df.iloc[:,np.r_[0:9, 53:55]]
    # if 'rhown' in nombre_df:
    #     df = df.iloc[:,np.r_[0:7, 51:53]]

    train, test = train_test_split(df, test_size=0.2, random_state=42, stratify=df["High_Chl"]) # TEST 20% TRAIN 80%
    target = "Chl"

    train, val = train_test_split(train, test_size=0.25, random_state=42, stratify=train["High_Chl"]) # TRAIN 60% VAL 20% TEST%

    X_train = train.drop(columns=[target,"High_Chl"])
    X_val = val.drop(columns=[target, "High_Chl"])
    X_test = test.drop(columns=[target, "High_Chl"])
    y_train = train[target]
    y_val = val[target]
    y_test = test[target]

    
    scaler_X = RobustScaler()
    scaler_y = RobustScaler()
    X_train_scaled = scaler_X.fit_transform(X_train)
    X_val_scaled = scaler_X.transform(X_val)
    X_test_scaled = scaler_X.transform(X_test)
    y_train_scaled = scaler_y.fit_transform(y_train.values.reshape(-1, 1)).ravel()
    
    results[nombre_df] = {name: {'RMSE': None, 'R2': None} for name in models}
    val_preds = {}
    test_preds = {}

    for name, model in models.items():
        print(f"Fitting {name} for {nombre_df}")
        if name in ["MLP", "SVR", "KNN", "LR", "EN"]:
            model.fit(X_train_scaled, y_train_scaled)
            #test_pred = model.predict(X_test_scaled)
            val_pred = scaler_y.inverse_transform(model.predict(X_val_scaled).reshape(-1, 1)).ravel()
            test_pred = scaler_y.inverse_transform(model.predict(X_test_scaled).reshape(-1, 1)).ravel()
        else:
            model.fit(X_train, y_train)
            val_pred = model.predict(X_val)
            test_pred = model.predict(X_test)

        val_preds[name] = val_pred
        test_preds[name] = test_pred

        rmse = np.sqrt(mean_squared_error(y_test, test_pred))
        r2 = r2_score(y_test, test_pred)

        results[nombre_df][name]['RMSE'] = rmse.round(2)
        results[nombre_df][name]['R2'] = r2.round(2)

    # Meta-modelo
    meta_X = np.vstack([val_preds[model] for model in models]).T
    meta_y = y_val.values
    meta_model = Ridge().fit(meta_X, meta_y)

    # Predicción final ensemble
    test_meta_X = np.vstack([test_preds[model] for model in models]).T
    ensemble_pred = meta_model.predict(test_meta_X)

    rmse_ens = np.sqrt(mean_squared_error(y_test, ensemble_pred))
    r2_ens = r2_score(y_test, ensemble_pred)

    results[nombre_df]["Ensemble"] = {
        "RMSE": round(rmse_ens, 2),
        "R2": round(r2_ens, 2)
    }

Fitting XGB for C2X-Complex_rhow_9x9_depth_in_0_1

TypeError: fit() missing 1 required positional argument: 'y'

In [329]:
rows = []

for df_name, model_scores in results.items():
    row = {}
    for model_name, metrics in model_scores.items():
        for metric_name, values in metrics.items():
            if isinstance(values, list):  # Solo para los que tienen listas (folds)
                mean_val = np.mean(values)
                std_val = np.std(values)
                row[(metric_name, model_name)] = f"{mean_val:.2f} ± {std_val:.2f}"
            else:
                # Para el ensemble que tiene un único valor
                row[(metric_name, model_name)] = f"{values:.2f}"
    rows.append((df_name, row))

df_results = pd.DataFrame.from_dict(dict(rows), orient="index")
df_results.columns = pd.MultiIndex.from_tuples(df_results.columns, names=["Metric", "Model"])
df_results = df_results.sort_index(axis=1, level=0)
df_results = df_results.sort_index(axis=0)

In [330]:
df_results

Metric                                     R2                         \
Model                                     CAT           EN  Ensemble
C2RCC_rhow_5x5_depth_lt_1         0.67 ± 0.13  0.48 ± 0.07      0.61
C2X-Complex_rhown_3x3_depth_lt_1  0.66 ± 0.12  0.50 ± 0.06  -6049.03
TOA_9x9_depth_lt_1                0.78 ± 0.12  0.19 ± 0.13      0.46

Metric                                                                    \
Model                                     KNN          LBM            LR
C2RCC_rhow_5x5_depth_lt_1         0.74 ± 0.10  0.61 ± 0.24   0.31 ± 0.52
C2X-Complex_rhown_3x3_depth_lt_1  0.59 ± 0.12  0.55 ± 0.17  -1.12 ± 3.18
TOA_9x9_depth_lt_1                0.76 ± 0.13  0.70 ± 0.09   0.18 ± 0.36

Metric                                                                   \
Model                                     MLP           RF          SVR
C2RCC_rhow_5x5_depth_lt_1         0.71 ± 0.12  0.63 ± 0.18  0.66 ± 0.15
C2X-Complex_rhown_3x3_depth_lt_1  0.45 ± 0.08  0.63 ± 0.11  0.53 ± 0.09
TOA_9x9_depth_lt_1                0.65 ± 0.14  0.70 ± 0.13  0.50 ± 0.04

Metric                                                RMSE               \
Model                                     XGB          CAT           EN
C2RCC_rhow_5x5_depth_lt_1         0.65 ± 0.19  2.04 ± 0.37  2.64 ± 0.20
C2X-Complex_rhown_3x3_depth_lt_1  0.61 ± 0.17  2.08 ± 0.17  2.63 ± 0.41
TOA_9x9_depth_lt_1                0.72 ± 0.12  1.80 ± 0.49  3.58 ± 0.15

Metric                                                               \
Model                            Ensemble          KNN          LBM
C2RCC_rhow_5x5_depth_lt_1            2.97  1.81 ± 0.21  2.16 ± 0.50
C2X-Complex_rhown_3x3_depth_lt_1   370.82  2.30 ± 0.17  2.41 ± 0.25
TOA_9x9_depth_lt_1                   2.59  1.87 ± 0.37  2.15 ± 0.32

Metric                                                                   \
Model                                      LR          MLP           RF
C2RCC_rhow_5x5_depth_lt_1         2.83 ± 0.72  1.93 ± 0.27  2.14 ± 0.35
C2X-Complex_rhown_3x3_depth_lt_1  4.08 ± 2.64  2.77 ± 0.44  2.21 ± 0.17
TOA_9x9_depth_lt_1                3.49 ± 0.48  2.31 ± 0.28  2.12 ± 0.39

Metric
Model                                     SVR          XGB
C2RCC_rhow_5x5_depth_lt_1         2.08 ± 0.31  2.08 ± 0.44
C2X-Complex_rhown_3x3_depth_lt_1  2.52 ± 0.31  2.21 ± 0.28
TOA_9x9_depth_lt_1                2.84 ± 0.26  2.05 ± 0.44