In [21]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import os
pd.options.mode.chained_assignment = None
import optuna
import time
from sklearn.metrics import r2_score, mean_squared_error
from sklearn.model_selection import cross_val_score, KFold, StratifiedKFold, train_test_split
from xgboost import XGBRegressor
from catboost import CatBoostRegressor
from lightgbm import LGBMRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression, Ridge, ElasticNet
from sklearn.neighbors import KNeighborsRegressor
from sklearn.neural_network import MLPRegressor
from sklearn.svm import SVR
from sklearn.preprocessing import StandardScaler, RobustScaler
import pickle
from collections import defaultdict

In [34]:
depths = ["in_3_4"] #"in_1_2", "in_2_3", "in_3_4"]
for depth in depths: 
    # Cargamos los csv de los tifs
    path = "saved_files/dataset"
    dfs = {}
    for archivo in os.listdir(path):
        if archivo.endswith(f"{depth}_features.csv"):
            nombre_sin_extension = os.path.splitext(archivo)[0]  # sin .csv
            ruta_completa = os.path.join(path, archivo)
            dfs[nombre_sin_extension[:-9]] = pd.read_csv(ruta_completa)



    # Limpiamos valores nulos
    for nombre_df, df in dfs.items():
        for band_set in ["rhow", "rhown","rtoa"]:
            dfs[nombre_df] = df.dropna()

    dfs_to_keep = [
		'C2X-Complex_rhow_9x9_depth_in_0_1', 
		'TOA_15x15_depth_in_0_1',
		'C2X-Complex_rhown_9x9_depth_in_0_1',
		'C2X-Complex_rhow_5x5_depth_in_0_1',
		'C2RCC_rhow_5x5_depth_in_0_1',
		'C2RCC_rhow_15x15_depth_in_0_1', 
		'C2X-Complex_rhown_15x15_depth_in_0_1',
		'C2RCC_rhown_5x5_depth_in_0_1', 
		'C2X-Complex_rhow_15x15_depth_in_0_1',
		'C2RCC_rhow_9x9_depth_in_0_1',
		'C2X-Complex_rhow_5x5_depth_in_1_2', 
		'C2X_rhow_3x3_depth_in_1_2',
		'C2X-Complex_rhown_5x5_depth_in_1_2',
		'C2X-Complex_rhow_9x9_depth_in_1_2',
		'C2X-Complex_rhow_3x3_depth_in_1_2',
		'C2X-Complex_rhown_3x3_depth_in_1_2',
		'C2RCC_rhown_3x3_depth_in_1_2',
		'C2X-Complex_rhown_9x9_depth_in_1_2',
		'C2X-Complex_rhow_15x15_depth_in_1_2', 
		'C2X_rhow_5x5_depth_in_1_2',
        'TOA_15x15_depth_in_2_3',
		'TOA_9x9_depth_in_2_3',
		'TOA_5x5_depth_in_2_3', 
		'C2X-Complex_rhow_5x5_depth_in_2_3',
		'C2RCC_rhown_5x5_depth_in_2_3', 
		'TOA_3x3_depth_in_2_3',
		'C2X-Complex_rhown_5x5_depth_in_2_3', 
		'C2RCC_rhow_3x3_depth_in_2_3',
		'C2X-Complex_rhown_9x9_depth_in_2_3', 
		'C2X_rhow_9x9_depth_in_2_3',
        'TOA_9x9_depth_in_3_4',
		'TOA_3x3_depth_in_3_4',
		'TOA_5x5_depth_in_3_4',
		'C2X-Complex_rhow_5x5_depth_in_3_4', 
		'TOA_1x1_depth_in_3_4',
		'TOA_15x15_depth_in_3_4',
		'C2X-Complex_rhown_5x5_depth_in_3_4',
		'C2X-Complex_rhow_9x9_depth_in_3_4',
		'C2X-Complex_rhow_15x15_depth_in_3_4',
		'C2X-Complex_rhown_9x9_depth_in_3_4'
        ]

    dfs = {k: dfs[k] for k in dfs_to_keep if k in dfs}


    for nombre_df, df in dfs.items():
        # Marcamos las columnas de CHl alta (equivalente a quantile(0.93))
        df["High_Chl"] = df["Chl"]>5
        # Sacamos la estación de cada fecha
        df['Date'] = pd.to_datetime(df['Date'])
        def get_season(month):
            if month in [12, 1, 2]:
                return 'Invierno'
            elif month in [3, 4, 5]:
                return 'Primavera'
            elif month in [6, 7, 8]:
                return 'Verano'
            else:
                return 'Otoño'
        df['Season'] = df['Date'].dt.month.apply(get_season)
        for col in df.select_dtypes(include='object').columns:
            df[col] = df[col].astype('category')
        df = pd.concat([df.drop(columns=["Season"]),pd.get_dummies(df["Season"])], axis=1)
        dfs[nombre_df] = df

    #results = cross_validation_training(dfs, depth)
    # Run optuna

### Optimización de hiperparámetros

In [46]:
def objective(trial, df, nombre_df, target, model_name):
    # Mismo proceso que para validación cruzada, pero haciendo preds solamente sobre test
    FOLDS = 5
    # Para hacer clip a las predicciones y forzar > 0
    correct = True
    #results = {}

    df = df.iloc[:, 4:]

    # Separamos el conjunto de datos en train y test: Train 75% Test 25%
    train, test = train_test_split(df, test_size=0.25, random_state=42, stratify=df["High_Chl"])
    target = "Chl"

    X = train.drop(columns=[target, "High_Chl", "Turbidez"])
    y = train[target]
    y_class = train["High_Chl"]

    # Definimos X e y para test
    X_test = test.drop(columns=[target, "High_Chl", "Turbidez"])
    y_test = test[target]

    #test_preds = {name: np.zeros(len(test)) for name in models}
    test_preds = np.zeros(len(test))

    #results[nombre_df] = {name: {'RMSE': [], 'R2': []} for name in models}
    # Stratified KFold de 5 folds
    skf = StratifiedKFold(n_splits=FOLDS, shuffle=True, random_state=42)

    if model_name == "LBM":
        params = {
            'objective': 'regression',
            'metric': 'rmse',
            'boosting_type': 'gbdt',
            'device': 'cpu',  # usa CPU/GPU
            'verbosity': -1,
            'learning_rate': trial.suggest_float('learning_rate', 0.005, 0.05, log=True),
            'num_leaves': trial.suggest_categorical('num_leaves', [10, 20, 30]),
            'max_depth': trial.suggest_int('max_depth', 3, 6),
            'min_child_samples': trial.suggest_int('min_child_samples', 4, 8),
            'subsample': trial.suggest_float('subsample', 0.6, 1.0),
            'colsample_bytree': trial.suggest_float('colsample_bytree', 0.6, 1.0),
            'n_estimators': trial.suggest_categorical('n_estimators', [100, 250, 500]),
            'reg_alpha': trial.suggest_float('reg_alpha', 1e-3, 10.0, log=True),
            'reg_lambda': trial.suggest_float('reg_lambda', 1e-3, 10.0, log=True),
            'min_split_gain': trial.suggest_categorical('min_split_gain', [0.0, 0.1, 0.2, 0.5, 1.0])
        }

    if model_name == "XGB":
        params = {
            'n_estimators': trial.suggest_categorical('n_estimators', [100, 250, 00]),
            'learning_rate': trial.suggest_float('learning_rate', 0.005, 0.05, log=True),
            'max_depth': trial.suggest_int('max_depth', 3, 6),
            'min_child_weight': trial.suggest_int('min_child_weight', 2, 4),
            'subsample': trial.suggest_float('subsample', 0.6, 1.0),
            'colsample_bytree': trial.suggest_float('colsample_bytree', 0.6, 1.0),
            'reg_alpha': trial.suggest_float('reg_alpha', 1e-3, 10.0, log=True),
            'reg_lambda': trial.suggest_float('reg_lambda', 1e-3, 10.0, log=True),
            'device': 'cpu',
            'objective': 'reg:squarederror',
            'tree_method': 'hist',
            'enable_categorical': True,
            'eval_metric': 'rmse'
        }
    
    if model_name == "MLP":
        # Así para evitar warning de definir como tuple
        hidden_options = {
            '32': (32,),
            '64': (64,),
            '32_16': (32, 16)
        }
        hidden_layer_sizes = trial.suggest_categorical('hidden_layer_sizes', list(hidden_options.values()))
        params = {
            'hidden_layer_sizes': hidden_layer_sizes,
            #'hidden_layer_sizes': trial.suggest_categorical('hidden_layer_sizes', [(50,), (100,), (100, 50), (128, 64)]),
            'activation': trial.suggest_categorical('activation', ['relu', 'tanh']),
            'solver': trial.suggest_categorical('solver', ['adam', 'sgd']),
            'alpha': trial.suggest_float('alpha', 1e-4, 1, log=True),
            'learning_rate': trial.suggest_categorical('learning_rate', ['constant', 'adaptive']),
            'learning_rate_init': trial.suggest_float('learning_rate_init', 1e-4, 1e-2, log=True),
            'max_iter': 200,
            'n_iter_no_change': 25,
            'early_stopping': True,
            'validation_fraction': 0.2,
            'random_state': 42,
            'verbose': False
        }

    if model_name == "SVR":
        params = {
            'kernel': 'rbf',
            'C': trial.suggest_float('C', 0.1, 5.0, log=True),
            'epsilon': trial.suggest_float('epsilon', 0.01, 0.2),
            'gamma': 'scale',
            'shrinking': True,
            'tol': 1e-3,
            'max_iter': -1,
            'verbose': False
        }

    if model_name == "KNN":
        params = {
            'n_neighbors': trial.suggest_int('n_neighbors', 5, 15),
            'weights': 'distance',
            'algorithm': 'auto',
            'leaf_size': trial.suggest_int('leaf_size', 10, 40),
            'p': 2,  # 1 = manhattan, 2 = euclídea
            'metric': 'minkowski',
            'n_jobs': -1
        }

    if model_name == "LR":
        # No sirve de mucho, pero por completitud
        params = {
            'fit_intercept': trial.suggest_categorical('fit_intercept', [True, False]),
            'positive': trial.suggest_categorical('positive', [True, False]),
        }

    if model_name == "RF":
        params = {
            'n_estimators': trial.suggest_categorical('n_estimators', [100, 300, 500]),
            'max_depth': trial.suggest_int('max_depth', 3, 6),
            'min_samples_split': trial.suggest_int('min_samples_split', 4, 10),
            'min_samples_leaf': trial.suggest_int('min_samples_leaf', 2, 8),
            'bootstrap': trial.suggest_categorical('bootstrap', [True, False]),
            'random_state': 42,
            'verbose': 0
        }

    if model_name == "CAT":
        params = {
            'iterations': trial.suggest_categorical('iterations', [500, 750, 100]),
            'learning_rate': trial.suggest_float('learning_rate', 0.02, 0.08, log=True),
            'depth': trial.suggest_int('depth', 4, 8),
            'l2_leaf_reg': trial.suggest_float('l2_leaf_reg', 2.0, 1.0),
            'loss_function': 'RMSE',
            'eval_metric': 'RMSE',
            'random_seed': 42,
            'early_stopping_rounds': 50,
            'verbose': False,
            'random_strength': trial.suggest_float('random_strength', 0.0, 1.0),
            'bagging_temperature': trial.suggest_float('bagging_temperature', 0.0, 1.0),
        }

    if model_name == "ELN":
        params = {
            'alpha': trial.suggest_float('alpha', 1e-4, 1.0, log=True),
            'l1_ratio': trial.suggest_float('l1_ratio', 0.1, 0.9),
            'fit_intercept': True,
            'max_iter': 1000,
            'tol': 1e-4,
            'selection': 'cyclic',
            'random_state': 42
        }

    # Cargamos el modelo correspondiente
    model = models[model_name](**params)

    for fold, (train_idx, val_idx) in enumerate(skf.split(X, y_class)):
        print(f"Fold {fold+1}")
        X_train, X_val = X.iloc[train_idx], X.iloc[val_idx]
        y_train, y_val = y.iloc[train_idx], y.iloc[val_idx]

        if model_name in ["MLP", "SVR", "KNN", "LR", "ELN"]:
            scaler_X = RobustScaler()
            scaler_y = RobustScaler()
            X_train_scaled = scaler_X.fit_transform(X_train)
            X_val_scaled = scaler_X.transform(X_val)
            X_test_scaled = scaler_X.transform(X_test)
            y_train_scaled = scaler_y.fit_transform(y_train.values.reshape(-1, 1)).ravel()
            model.fit(X_train_scaled, y_train_scaled)
            test_pred = scaler_y.inverse_transform(model.predict(X_test_scaled).reshape(-1, 1)).ravel()

        else:
            model.fit(X_train, y_train)
            test_pred = model.predict(X_test)

        if correct:
            test_pred = np.clip(test_pred, 0.2, None)

        test_preds[model_name] += test_pred / FOLDS

    #rmse_test = np.sqrt(mean_squared_error(y_test, test_preds[model_name]))
    r2_test = r2_score(y_test, test_preds[model_name])

    return r2_test

In [36]:

models = {
    "XGB": XGBRegressor,
    "LBM": LGBMRegressor,
    "MLP": MLPRegressor,
    "SVR": SVR,
    "KNN": KNeighborsRegressor,
    "LR": LinearRegression,
    "RF": RandomForestRegressor,
    "CAT": CatBoostRegressor,
    "ELN":  ElasticNet
}

def run_optuna(df, nombre_df, target, n_trials, model_name):
    results = {}

    print(f"Buscando mejores hiperparámetros para {model_name} con {nombre_df}...")
    study = optuna.create_study(direction='maximize')
    study.optimize(lambda trial: objective(trial, df, nombre_df, target, model_name), n_trials=n_trials, timeout= 1500)
    
    print(f"\n✅ {model_name} con {nombre_df} - Mejor R2: {study.best_value:.2f}")
    print(f"📋 Parámetros: {study.best_params}\n")
    
    results[model_name] = {
        'best_params': study.best_params,
        'best_score': np.round(study.best_value, 3),
        'study': study
    }
    return results

n_trials = 20
global_results = {}


depths = ["in_0_1", "in_1_2", "in_2_3", "in_3_4"]
for depth in depths: 
    # Cargamos los csv de los tifs
    path = "saved_files/dataset"
    dfs = {}
    for archivo in os.listdir(path):
        if archivo.endswith(f"{depth}_features.csv"):
            nombre_sin_extension = os.path.splitext(archivo)[0]  # sin .csv
            ruta_completa = os.path.join(path, archivo)
            dfs[nombre_sin_extension[:-9]] = pd.read_csv(ruta_completa)


    # Limpiamos valores nulos
    for nombre_df, df in dfs.items():
        for band_set in ["rhow", "rhown","rtoa"]:
            dfs[nombre_df] = df.dropna()

    dfs_to_keep = [
		'C2X-Complex_rhow_9x9_depth_in_0_1', 
		'TOA_15x15_depth_in_0_1',
		'C2X-Complex_rhown_9x9_depth_in_0_1',
		'C2X-Complex_rhow_5x5_depth_in_0_1',
		'C2RCC_rhow_5x5_depth_in_0_1',
		'C2RCC_rhow_15x15_depth_in_0_1', 
		'C2X-Complex_rhown_15x15_depth_in_0_1',
		'C2RCC_rhown_5x5_depth_in_0_1', 
		'C2X-Complex_rhow_15x15_depth_in_0_1',
		'C2RCC_rhow_9x9_depth_in_0_1',
		'C2X-Complex_rhow_5x5_depth_in_1_2', 
		'C2X_rhow_3x3_depth_in_1_2',
		'C2X-Complex_rhown_5x5_depth_in_1_2',
		'C2X-Complex_rhow_9x9_depth_in_1_2',
		'C2X-Complex_rhow_3x3_depth_in_1_2',
		'C2X-Complex_rhown_3x3_depth_in_1_2',
		'C2RCC_rhown_3x3_depth_in_1_2',
		'C2X-Complex_rhown_9x9_depth_in_1_2',
		'C2X-Complex_rhow_15x15_depth_in_1_2', 
		'C2X_rhow_5x5_depth_in_1_2',
        'TOA_15x15_depth_in_2_3',
		'TOA_9x9_depth_in_2_3',
		'TOA_5x5_depth_in_2_3', 
		'C2X-Complex_rhow_5x5_depth_in_2_3',
		'C2RCC_rhown_5x5_depth_in_2_3', 
		'TOA_3x3_depth_in_2_3',
		'C2X-Complex_rhown_5x5_depth_in_2_3', 
		'C2RCC_rhow_3x3_depth_in_2_3',
		'C2X-Complex_rhown_9x9_depth_in_2_3', 
		'C2X_rhow_9x9_depth_in_2_3',
        'TOA_9x9_depth_in_3_4',
		'TOA_3x3_depth_in_3_4',
		'TOA_5x5_depth_in_3_4',
		'C2X-Complex_rhow_5x5_depth_in_3_4', 
		'TOA_1x1_depth_in_3_4',
		'TOA_15x15_depth_in_3_4',
		'C2X-Complex_rhown_5x5_depth_in_3_4',
		'C2X-Complex_rhow_9x9_depth_in_3_4',
		'C2X-Complex_rhow_15x15_depth_in_3_4',
		'C2X-Complex_rhown_9x9_depth_in_3_4'
        ]

    dfs = {k: dfs[k] for k in dfs_to_keep if k in dfs}


    for nombre_df, df in dfs.items():
        # Marcamos las columnas de CHl alta (equivalente a quantile(0.93))
        df["High_Chl"] = df["Chl"]>5
        # Sacamos la estación de cada fecha
        df['Date'] = pd.to_datetime(df['Date'])
        def get_season(month):
            if month in [12, 1, 2]:
                return 'Invierno'
            elif month in [3, 4, 5]:
                return 'Primavera'
            elif month in [6, 7, 8]:
                return 'Verano'
            else:
                return 'Otoño'
        df['Season'] = df['Date'].dt.month.apply(get_season)
        for col in df.select_dtypes(include='object').columns:
            df[col] = df[col].astype('category')
        df = pd.concat([df.drop(columns=["Season"]),pd.get_dummies(df["Season"])], axis=1)
        dfs[nombre_df] = df

    for nombre_df, df in list(dfs.items()):
        for model_name in models.keys():
            key = (nombre_df, model_name)
            result = run_optuna(df, nombre_df, "Chl", n_trials, model_name)
            global_results[key] = result[model_name]

    with open(f"training_results/selection_results_{depth}.pkl", "wb") as f:
        pickle.dump(global_results, f)

[I 2025-09-04 14:19:12,167] A new study created in memory with name: no-name-3ec5fe63-a087-4177-87eb-4b637483cb3c

Buscando mejores hiperparámetros para XGB con TOA_9x9_depth_in_3_4...

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:19:15,176] Trial 0 finished with value: 0.5200771062651086 and parameters: {'n_estimators': 500, 'learning_rate': 0.010154558822693555, 'max_depth': 5, 'min_child_weight': 1, 'subsample': 0.8202811812149784, 'colsample_bytree': 0.6729905646697188}. Best is trial 0 with value: 0.5200771062651086.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:19:23,159] Trial 1 finished with value: 0.47749786193414134 and parameters: {'n_estimators': 1000, 'learning_rate': 0.014900629764633438, 'max_depth': 6, 'min_child_weight': 1, 'subsample': 0.9926663347183362, 'colsample_bytree': 0.7326210265974088}. Best is trial 0 with value: 0.5200771062651086.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:19:36,606] Trial 2 finished with value: 0.5355096642605808 and parameters: {'n_estimators': 2000, 'learning_rate': 0.022336178717114283, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.7562582639160361, 'colsample_bytree': 0.9851539969098063}. Best is trial 2 with value: 0.5355096642605808.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:19:40,980] Trial 3 finished with value: 0.503785912986729 and parameters: {'n_estimators': 500, 'learning_rate': 0.028211290487955804, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.6633066250641342, 'colsample_bytree': 0.7006260601991892}. Best is trial 2 with value: 0.5355096642605808.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:19:59,986] Trial 4 finished with value: 0.536740187662972 and parameters: {'n_estimators': 2000, 'learning_rate': 0.017703177718082625, 'max_depth': 8, 'min_child_weight': 2, 'subsample': 0.669246569585045, 'colsample_bytree': 0.8517921505841703}. Best is trial 4 with value: 0.536740187662972.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:20:09,848] Trial 5 finished with value: 0.5563627658375494 and parameters: {'n_estimators': 1000, 'learning_rate': 0.0060590472324995185, 'max_depth': 8, 'min_child_weight': 2, 'subsample': 0.7351640986902455, 'colsample_bytree': 0.944970286729723}. Best is trial 5 with value: 0.5563627658375494.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:20:17,310] Trial 6 finished with value: 0.5720053872247997 and parameters: {'n_estimators': 1000, 'learning_rate': 0.008198497936611737, 'max_depth': 8, 'min_child_weight': 3, 'subsample': 0.7212531244969402, 'colsample_bytree': 0.6752045806299354}. Best is trial 6 with value: 0.5720053872247997.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:20:20,220] Trial 7 finished with value: 0.5850567841035694 and parameters: {'n_estimators': 500, 'learning_rate': 0.009349062341632887, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.7352370364469053, 'colsample_bytree': 0.7098194060876609}. Best is trial 7 with value: 0.5850567841035694.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:20:24,065] Trial 8 finished with value: 0.583660984523628 and parameters: {'n_estimators': 500, 'learning_rate': 0.006404043596364241, 'max_depth': 8, 'min_child_weight': 4, 'subsample': 0.75302251931311, 'colsample_bytree': 0.7486438767643471}. Best is trial 7 with value: 0.5850567841035694.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:20:36,728] Trial 9 finished with value: 0.593785045097491 and parameters: {'n_estimators': 2000, 'learning_rate': 0.008995118177840267, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.6284816197581397, 'colsample_bytree': 0.6884804437602281}. Best is trial 9 with value: 0.593785045097491.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:20:49,606] Trial 10 finished with value: 0.5655818928672611 and parameters: {'n_estimators': 2000, 'learning_rate': 0.013109602877266003, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.86722524888727, 'colsample_bytree': 0.6038878924485898}. Best is trial 9 with value: 0.593785045097491.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:20:51,849] Trial 11 finished with value: 0.5996603277656202 and parameters: {'n_estimators': 500, 'learning_rate': 0.010322994749904472, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.6060099832858249, 'colsample_bytree': 0.8343972821589686}. Best is trial 11 with value: 0.5996603277656202.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:20:59,261] Trial 12 finished with value: 0.6150915813276077 and parameters: {'n_estimators': 2000, 'learning_rate': 0.047600594240155655, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.6049475476360661, 'colsample_bytree': 0.8631912096943319}. Best is trial 12 with value: 0.6150915813276077.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:21:06,708] Trial 13 finished with value: 0.5874084961533513 and parameters: {'n_estimators': 2000, 'learning_rate': 0.048776389080873846, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.6127410483663734, 'colsample_bytree': 0.8527494180128398}. Best is trial 12 with value: 0.6150915813276077.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:21:08,676] Trial 14 finished with value: 0.6092538976167923 and parameters: {'n_estimators': 500, 'learning_rate': 0.04354400734326646, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.6634146603810124, 'colsample_bytree': 0.8638104130182864}. Best is trial 12 with value: 0.6150915813276077.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:21:10,671] Trial 15 finished with value: 0.5863545310731173 and parameters: {'n_estimators': 500, 'learning_rate': 0.049547834229388375, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.6717442422092413, 'colsample_bytree': 0.9147027231444478}. Best is trial 12 with value: 0.6150915813276077.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:21:18,567] Trial 16 finished with value: 0.5486077721655949 and parameters: {'n_estimators': 2000, 'learning_rate': 0.033558425775537165, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.9095095904977806, 'colsample_bytree': 0.7961642622198205}. Best is trial 12 with value: 0.6150915813276077.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:21:20,603] Trial 17 finished with value: 0.5956039951618781 and parameters: {'n_estimators': 500, 'learning_rate': 0.036642278605777075, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.687283657600201, 'colsample_bytree': 0.8981698677602784}. Best is trial 12 with value: 0.6150915813276077.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:21:27,564] Trial 18 finished with value: 0.5482726739847361 and parameters: {'n_estimators': 2000, 'learning_rate': 0.03917389979300245, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.7979100049828401, 'colsample_bytree': 0.7991122236797561}. Best is trial 12 with value: 0.6150915813276077.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:21:31,901] Trial 19 finished with value: 0.5832495163509529 and parameters: {'n_estimators': 1000, 'learning_rate': 0.024601069676549875, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.6276395497483841, 'colsample_bytree': 0.8864583542912743}. Best is trial 12 with value: 0.6150915813276077.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:21:40,209] Trial 20 finished with value: 0.5661436043589898 and parameters: {'n_estimators': 2000, 'learning_rate': 0.01935891430131137, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.7027976393361547, 'colsample_bytree': 0.9813209378211312}. Best is trial 12 with value: 0.6150915813276077.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:21:42,324] Trial 21 finished with value: 0.5990176044818906 and parameters: {'n_estimators': 500, 'learning_rate': 0.012090247549032406, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.6014226858784391, 'colsample_bytree': 0.8406368582439021}. Best is trial 12 with value: 0.6150915813276077.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:21:44,230] Trial 22 finished with value: 0.6085262159960401 and parameters: {'n_estimators': 500, 'learning_rate': 0.030194354270501777, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.6404127854879855, 'colsample_bytree': 0.770310038240577}. Best is trial 12 with value: 0.6150915813276077.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:21:46,407] Trial 23 finished with value: 0.5943164266424623 and parameters: {'n_estimators': 500, 'learning_rate': 0.030572520768796654, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.648584765902839, 'colsample_bytree': 0.7824121244256853}. Best is trial 12 with value: 0.6150915813276077.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:21:48,294] Trial 24 finished with value: 0.60655855152784 and parameters: {'n_estimators': 500, 'learning_rate': 0.04062257525018666, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.6412340104038969, 'colsample_bytree': 0.759021233584904}. Best is trial 12 with value: 0.6150915813276077.
[I 2025-09-04 14:21:48,295] A new study created in memory with name: no-name-cbc108ae-2d12-4188-84d1-ad2c5723ec2d

✅ XGB con TOA_9x9_depth_in_3_4 - Mejor R2: 0.62
📋 Parámetros: {'n_estimators': 2000, 'learning_rate': 0.047600594240155655, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.6049475476360661, 'colsample_bytree': 0.8631912096943319}

Buscando mejores hiperparámetros para LBM con TOA_9x9_depth_in_3_4...

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 14:21:49,062] Trial 0 finished with value: 0.534654693894187 and parameters: {'learning_rate': 0.027539146652518394, 'num_leaves': 40, 'max_depth': 7, 'min_child_samples': 6, 'subsample': 0.8204583024041748, 'colsample_bytree': 0.9732835621940499, 'n_estimators': 1000}. Best is trial 0 with value: 0.534654693894187.

Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:21:50,611] Trial 1 finished with value: 0.5207251179617358 and parameters: {'learning_rate': 0.03650206676746847, 'num_leaves': 80, 'max_depth': 7, 'min_child_samples': 6, 'subsample': 0.632893860382608, 'colsample_bytree': 0.9906589596932562, 'n_estimators': 2000}. Best is trial 0 with value: 0.534654693894187.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 14:21:51,390] Trial 2 finished with value: 0.6011937067425999 and parameters: {'learning_rate': 0.009129621713885207, 'num_leaves': 80, 'max_depth': 7, 'min_child_samples': 8, 'subsample': 0.6656405200015706, 'colsample_bytree': 0.6115164375868924, 'n_estimators': 1000}. Best is trial 2 with value: 0.6011937067425999.

Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:21:52,559] Trial 3 finished with value: 0.48637777921417613 and parameters: {'learning_rate': 0.01159356379329682, 'num_leaves': 60, 'max_depth': 5, 'min_child_samples': 5, 'subsample': 0.6404283182155567, 'colsample_bytree': 0.9267572616946411, 'n_estimators': 2000}. Best is trial 2 with value: 0.6011937067425999.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 14:21:52,855] Trial 4 finished with value: 0.6041292983702677 and parameters: {'learning_rate': 0.008431740548258132, 'num_leaves': 40, 'max_depth': 5, 'min_child_samples': 7, 'subsample': 0.8186442169173899, 'colsample_bytree': 0.6381384820030342, 'n_estimators': 500}. Best is trial 4 with value: 0.6041292983702677.

Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 14:21:53,461] Trial 5 finished with value: 0.5922777183201695 and parameters: {'learning_rate': 0.02144107094379694, 'num_leaves': 40, 'max_depth': 6, 'min_child_samples': 12, 'subsample': 0.9381817873391213, 'colsample_bytree': 0.6617729575543781, 'n_estimators': 1000}. Best is trial 4 with value: 0.6041292983702677.

Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:21:54,530] Trial 6 finished with value: 0.5584163225060389 and parameters: {'learning_rate': 0.009010775731654617, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 8, 'subsample': 0.7474618088333066, 'colsample_bytree': 0.9382546177287059, 'n_estimators': 2000}. Best is trial 4 with value: 0.6041292983702677.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 14:21:55,121] Trial 7 finished with value: 0.5687842134310348 and parameters: {'learning_rate': 0.00803702791396181, 'num_leaves': 60, 'max_depth': 5, 'min_child_samples': 8, 'subsample': 0.9774807727910517, 'colsample_bytree': 0.9923193620397855, 'n_estimators': 1000}. Best is trial 4 with value: 0.6041292983702677.

Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:21:56,176] Trial 8 finished with value: 0.5619950610818067 and parameters: {'learning_rate': 0.017375439958543498, 'num_leaves': 80, 'max_depth': 5, 'min_child_samples': 12, 'subsample': 0.8411919841349217, 'colsample_bytree': 0.879287739138112, 'n_estimators': 2000}. Best is trial 4 with value: 0.6041292983702677.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:21:57,201] Trial 9 finished with value: 0.589853473392972 and parameters: {'learning_rate': 0.034276318281087126, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 7, 'subsample': 0.9071407845235837, 'colsample_bytree': 0.6326095217083242, 'n_estimators': 2000}. Best is trial 4 with value: 0.6041292983702677.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 14:21:57,580] Trial 10 finished with value: 0.562455499380189 and parameters: {'learning_rate': 0.005832714085520332, 'num_leaves': 40, 'max_depth': 8, 'min_child_samples': 16, 'subsample': 0.7414793325495395, 'colsample_bytree': 0.7385229499144168, 'n_estimators': 500}. Best is trial 4 with value: 0.6041292983702677.

Fold 4
Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 14:21:57,956] Trial 11 finished with value: 0.6003248644770667 and parameters: {'learning_rate': 0.005271310709503149, 'num_leaves': 80, 'max_depth': 6, 'min_child_samples': 10, 'subsample': 0.710546288389221, 'colsample_bytree': 0.6016678219731194, 'n_estimators': 500}. Best is trial 4 with value: 0.6041292983702677.

Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:21:58,430] Trial 12 finished with value: 0.6236206962413595 and parameters: {'learning_rate': 0.012461514819676877, 'num_leaves': 80, 'max_depth': 8, 'min_child_samples': 10, 'subsample': 0.8744590800732992, 'colsample_bytree': 0.7238409594170279, 'n_estimators': 500}. Best is trial 12 with value: 0.6236206962413595.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 14:21:58,882] Trial 13 finished with value: 0.6273302452030582 and parameters: {'learning_rate': 0.013134941831635164, 'num_leaves': 40, 'max_depth': 8, 'min_child_samples': 11, 'subsample': 0.8841707418743817, 'colsample_bytree': 0.7230835234175526, 'n_estimators': 500}. Best is trial 13 with value: 0.6273302452030582.

Fold 4
Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 14:21:59,325] Trial 14 finished with value: 0.6235651741781084 and parameters: {'learning_rate': 0.015196542644299597, 'num_leaves': 80, 'max_depth': 8, 'min_child_samples': 12, 'subsample': 0.8845574381897251, 'colsample_bytree': 0.7577876661337564, 'n_estimators': 500}. Best is trial 13 with value: 0.6273302452030582.

Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:21:59,731] Trial 15 finished with value: 0.6044510786571617 and parameters: {'learning_rate': 0.013580425539909307, 'num_leaves': 40, 'max_depth': 8, 'min_child_samples': 14, 'subsample': 0.8667435990350284, 'colsample_bytree': 0.8198597085719468, 'n_estimators': 500}. Best is trial 13 with value: 0.6273302452030582.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 14:22:00,181] Trial 16 finished with value: 0.6159750948537257 and parameters: {'learning_rate': 0.020220514791660257, 'num_leaves': 20, 'max_depth': 8, 'min_child_samples': 10, 'subsample': 0.9490108781161157, 'colsample_bytree': 0.6977526417968396, 'n_estimators': 500}. Best is trial 13 with value: 0.6273302452030582.

Fold 4
Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 14:22:00,563] Trial 17 finished with value: 0.6069636749886982 and parameters: {'learning_rate': 0.012108381795519804, 'num_leaves': 60, 'max_depth': 7, 'min_child_samples': 14, 'subsample': 0.9990626134576743, 'colsample_bytree': 0.80803758569248, 'n_estimators': 500}. Best is trial 13 with value: 0.6273302452030582.

Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:22:00,997] Trial 18 finished with value: 0.596208877540764 and parameters: {'learning_rate': 0.047622976436035844, 'num_leaves': 40, 'max_depth': 8, 'min_child_samples': 11, 'subsample': 0.7665120241407, 'colsample_bytree': 0.709037363296323, 'n_estimators': 500}. Best is trial 13 with value: 0.6273302452030582.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 14:22:01,405] Trial 19 finished with value: 0.595980265855642 and parameters: {'learning_rate': 0.0252660207006236, 'num_leaves': 80, 'max_depth': 8, 'min_child_samples': 14, 'subsample': 0.9160925865683747, 'colsample_bytree': 0.774573986188468, 'n_estimators': 500}. Best is trial 13 with value: 0.6273302452030582.

Fold 4
Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 14:22:01,837] Trial 20 finished with value: 0.6071806808078599 and parameters: {'learning_rate': 0.010798195275905297, 'num_leaves': 80, 'max_depth': 7, 'min_child_samples': 9, 'subsample': 0.86811783143912, 'colsample_bytree': 0.6876454973942143, 'n_estimators': 500}. Best is trial 13 with value: 0.6273302452030582.

Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:22:02,281] Trial 21 finished with value: 0.6253407066059562 and parameters: {'learning_rate': 0.015297342791062919, 'num_leaves': 80, 'max_depth': 8, 'min_child_samples': 12, 'subsample': 0.8824068356519156, 'colsample_bytree': 0.7534681300149607, 'n_estimators': 500}. Best is trial 13 with value: 0.6273302452030582.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 14:22:02,748] Trial 22 finished with value: 0.627654613679062 and parameters: {'learning_rate': 0.01713416804277511, 'num_leaves': 80, 'max_depth': 8, 'min_child_samples': 11, 'subsample': 0.7883599431510695, 'colsample_bytree': 0.8460115625974576, 'n_estimators': 500}. Best is trial 22 with value: 0.627654613679062.

Fold 4
Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 14:22:03,186] Trial 23 finished with value: 0.6142199278125224 and parameters: {'learning_rate': 0.017741426318180993, 'num_leaves': 80, 'max_depth': 8, 'min_child_samples': 13, 'subsample': 0.795402935377702, 'colsample_bytree': 0.8531799774932919, 'n_estimators': 500}. Best is trial 22 with value: 0.627654613679062.

Fold 4
Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 14:22:03,551] Trial 24 finished with value: 0.6120926311824513 and parameters: {'learning_rate': 0.014622204753757907, 'num_leaves': 80, 'max_depth': 7, 'min_child_samples': 16, 'subsample': 0.7922720629429776, 'colsample_bytree': 0.8418089492848169, 'n_estimators': 500}. Best is trial 22 with value: 0.627654613679062.
[I 2025-09-04 14:22:03,553] A new study created in memory with name: no-name-52df9f21-d6fd-42fa-9af8-7d228d3af4d0

Fold 5

✅ LBM con TOA_9x9_depth_in_3_4 - Mejor R2: 0.63
📋 Parámetros: {'learning_rate': 0.01713416804277511, 'num_leaves': 80, 'max_depth': 8, 'min_child_samples': 11, 'subsample': 0.7883599431510695, 'colsample_bytree': 0.8460115625974576, 'n_estimators': 500}

Buscando mejores hiperparámetros para MLP con TOA_9x9_depth_in_3_4...

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-04 14:22:05,259] Trial 0 finished with value: 0.6126444273227178 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'sgd', 'alpha': 3.08146456789602e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00039877412108745215}. Best is trial 0 with value: 0.6126444273227178.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-04 14:22:07,598] Trial 1 finished with value: 0.5889216678254516 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.015031311896188606, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0041071236990314845}. Best is trial 0 with value: 0.6126444273227178.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-04 14:22:11,419] Trial 2 finished with value: 0.5228575236455698 and parameters: {'hidden_layer_sizes': '256_128', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.0021533117661948135, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0008933039536610537}. Best is trial 0 with value: 0.6126444273227178.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:22:12,288] Trial 3 finished with value: 0.6321097197131551 and parameters: {'hidden_layer_sizes': '256_128', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.001171169923933265, 'learning_rate': 'constant', 'learning_rate_init': 0.00459002289767478}. Best is trial 3 with value: 0.6321097197131551.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:22:13,917] Trial 4 finished with value: 0.5776889327482988 and parameters: {'hidden_layer_sizes': '256_128', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0008502478901721959, 'learning_rate': 'constant', 'learning_rate_init': 0.003687721401451709}. Best is trial 3 with value: 0.6321097197131551.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-04 14:22:15,922] Trial 5 finished with value: 0.5433299629729297 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.0073726450795708965, 'learning_rate': 'constant', 'learning_rate_init': 0.000732796115477842}. Best is trial 3 with value: 0.6321097197131551.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

[I 2025-09-04 14:22:18,544] Trial 6 finished with value: 0.6974759821420029 and parameters: {'hidden_layer_sizes': '256_128', 'activation': 'relu', 'solver': 'sgd', 'alpha': 2.8077590376445538e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0025913875289744134}. Best is trial 6 with value: 0.6974759821420029.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-04 14:22:20,211] Trial 7 finished with value: 0.6916568531589053 and parameters: {'hidden_layer_sizes': '256', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.08743308460079482, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0033795512025720964}. Best is trial 6 with value: 0.6974759821420029.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

[I 2025-09-04 14:22:21,151] Trial 8 finished with value: 0.6280192304346919 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.0019923977081826635, 'learning_rate': 'constant', 'learning_rate_init': 0.003936775076959127}. Best is trial 6 with value: 0.6974759821420029.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 14:22:21,880] Trial 9 finished with value: 0.6057700786488621 and parameters: {'hidden_layer_sizes': '128', 'activation': 'relu', 'solver': 'adam', 'alpha': 1.52477378405386e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0009486939099415064}. Best is trial 6 with value: 0.6974759821420029.

Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-04 14:22:23,487] Trial 10 finished with value: 0.6479747293928412 and parameters: {'hidden_layer_sizes': '256', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.00011748160176133896, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00010866699125556097}. Best is trial 6 with value: 0.6974759821420029.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-04 14:22:25,151] Trial 11 finished with value: 0.6527384884599164 and parameters: {'hidden_layer_sizes': '256', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.07676799244213726, 'learning_rate': 'adaptive', 'learning_rate_init': 0.009983107845203731}. Best is trial 6 with value: 0.6974759821420029.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-04 14:22:26,788] Trial 12 finished with value: 0.6332858802520375 and parameters: {'hidden_layer_sizes': '256', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.00011728656935105572, 'learning_rate': 'adaptive', 'learning_rate_init': 0.001803271387273489}. Best is trial 6 with value: 0.6974759821420029.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

[I 2025-09-04 14:22:27,937] Trial 13 finished with value: 0.5691844122664141 and parameters: {'hidden_layer_sizes': '128', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.09690515417388028, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0020758670820882033}. Best is trial 6 with value: 0.6974759821420029.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-04 14:22:29,573] Trial 14 finished with value: 0.6804801860309448 and parameters: {'hidden_layer_sizes': '256', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.00020156043495149202, 'learning_rate': 'adaptive', 'learning_rate_init': 0.009910568899661193}. Best is trial 6 with value: 0.6974759821420029.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-04 14:22:32,244] Trial 15 finished with value: 0.7098144776973133 and parameters: {'hidden_layer_sizes': '256_128', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.015492411781384838, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0019024503727906594}. Best is trial 15 with value: 0.7098144776973133.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-04 14:22:35,005] Trial 16 finished with value: 0.6384868700400993 and parameters: {'hidden_layer_sizes': '256_128', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.016311096037149718, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0004599030288109142}. Best is trial 15 with value: 0.7098144776973133.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-04 14:22:37,646] Trial 17 finished with value: 0.689982015285537 and parameters: {'hidden_layer_sizes': '256_128', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.0003495045420287112, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0017029028791042504}. Best is trial 15 with value: 0.7098144776973133.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

[I 2025-09-04 14:22:40,947] Trial 18 finished with value: 0.5555855925018509 and parameters: {'hidden_layer_sizes': '256_128', 'activation': 'tanh', 'solver': 'adam', 'alpha': 2.921846413093274e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.00021201414560693182}. Best is trial 15 with value: 0.7098144776973133.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-04 14:22:43,632] Trial 19 finished with value: 0.6961133492590235 and parameters: {'hidden_layer_sizes': '256_128', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.0055095210969903045, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0015559169991935494}. Best is trial 15 with value: 0.7098144776973133.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-04 14:22:46,275] Trial 20 finished with value: 0.7065759260555555 and parameters: {'hidden_layer_sizes': '256_128', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.028887007027378696, 'learning_rate': 'adaptive', 'learning_rate_init': 0.006268089411892848}. Best is trial 15 with value: 0.7098144776973133.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-04 14:22:49,004] Trial 21 finished with value: 0.6272767657714154 and parameters: {'hidden_layer_sizes': '256_128', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.025741974796137112, 'learning_rate': 'adaptive', 'learning_rate_init': 0.006732544907444231}. Best is trial 15 with value: 0.7098144776973133.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-04 14:22:51,670] Trial 22 finished with value: 0.6897905720578765 and parameters: {'hidden_layer_sizes': '256_128', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.03346997347047614, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0024007256397833893}. Best is trial 15 with value: 0.7098144776973133.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-04 14:22:54,360] Trial 23 finished with value: 0.4509564573931025 and parameters: {'hidden_layer_sizes': '256_128', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.00623267457968297, 'learning_rate': 'adaptive', 'learning_rate_init': 0.007088658515237641}. Best is trial 15 with value: 0.7098144776973133.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

[I 2025-09-04 14:22:55,500] Trial 24 finished with value: 0.5964894361037084 and parameters: {'hidden_layer_sizes': '128', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.03939676605670623, 'learning_rate': 'adaptive', 'learning_rate_init': 0.002592939948520951}. Best is trial 15 with value: 0.7098144776973133.
[I 2025-09-04 14:22:55,501] A new study created in memory with name: no-name-79e50046-4815-4956-b916-f30c52be837b
[I 2025-09-04 14:22:55,600] Trial 0 finished with value: 0.1081157158508006 and parameters: {'C': 0.11681647501465804, 'epsilon': 0.19347834408406575}. Best is trial 0 with value: 0.1081157158508006.
[I 2025-09-04 14:22:55,677] Trial 1 finished with value: 0.3554526086699522 and parameters: {'C': 0.4752721756416031, 'epsilon': 0.16117970227289738}. Best is trial 1 with value: 0.3554526086699522.

✅ MLP con TOA_9x9_depth_in_3_4 - Mejor R2: 0.71
📋 Parámetros: {'hidden_layer_sizes': '256_128', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.015492411781384838, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0019024503727906594}

Buscando mejores hiperparámetros para SVR con TOA_9x9_depth_in_3_4...

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2

[I 2025-09-04 14:22:55,763] Trial 2 finished with value: 0.49603518668812896 and parameters: {'C': 3.7528104337015886, 'epsilon': 0.13060932986878146}. Best is trial 2 with value: 0.49603518668812896.
[I 2025-09-04 14:22:55,850] Trial 3 finished with value: 0.4976747151288863 and parameters: {'C': 3.2513554886111202, 'epsilon': 0.0934987449968881}. Best is trial 3 with value: 0.4976747151288863.

Fold 3
Fold 4
Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:22:55,931] Trial 4 finished with value: 0.1542854479488488 and parameters: {'C': 0.17845724832549614, 'epsilon': 0.030320340886507008}. Best is trial 3 with value: 0.4976747151288863.
[I 2025-09-04 14:22:56,013] Trial 5 finished with value: 0.4716121629036294 and parameters: {'C': 1.12254073935618, 'epsilon': 0.12322139000844066}. Best is trial 3 with value: 0.4976747151288863.
[I 2025-09-04 14:22:56,093] Trial 6 finished with value: 0.47921842379543744 and parameters: {'C': 6.481218109272587, 'epsilon': 0.1544418424579864}. Best is trial 3 with value: 0.4976747151288863.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 14:22:56,175] Trial 7 finished with value: 0.34533968874243437 and parameters: {'C': 0.48226192372723614, 'epsilon': 0.0811667617682756}. Best is trial 3 with value: 0.4976747151288863.
[I 2025-09-04 14:22:56,254] Trial 8 finished with value: 0.38885815207833685 and parameters: {'C': 0.6141641528834366, 'epsilon': 0.1248087704597788}. Best is trial 3 with value: 0.4976747151288863.
[I 2025-09-04 14:22:56,337] Trial 9 finished with value: 0.5016449658288451 and parameters: {'C': 2.39820482670724, 'epsilon': 0.07822198097951961}. Best is trial 9 with value: 0.5016449658288451.

Fold 4
Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===

[I 2025-09-04 14:22:56,427] Trial 10 finished with value: 0.495906403762018 and parameters: {'C': 1.6490540806994605, 'epsilon': 0.04871356376027778}. Best is trial 9 with value: 0.5016449658288451.
[I 2025-09-04 14:22:56,518] Trial 11 finished with value: 0.49893548640499563 and parameters: {'C': 2.9827367322978176, 'epsilon': 0.08183099675111248}. Best is trial 9 with value: 0.5016449658288451.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2

[I 2025-09-04 14:22:56,609] Trial 12 finished with value: 0.5026785232849138 and parameters: {'C': 2.3205465351137087, 'epsilon': 0.06424820399555443}. Best is trial 12 with value: 0.5026785232849138.
[I 2025-09-04 14:22:56,704] Trial 13 finished with value: 0.4650062640674548 and parameters: {'C': 9.72522048889472, 'epsilon': 0.05730592708242184}. Best is trial 12 with value: 0.5026785232849138.

Fold 3
Fold 4
Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 14:22:56,797] Trial 14 finished with value: 0.5035810814124261 and parameters: {'C': 1.9860741741743726, 'epsilon': 0.023712171259654913}. Best is trial 14 with value: 0.5035810814124261.
[I 2025-09-04 14:22:56,889] Trial 15 finished with value: 0.4685551593188123 and parameters: {'C': 1.0932403067439955, 'epsilon': 0.014200210893860015}. Best is trial 14 with value: 0.5035810814124261.

Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 14:22:57,002] Trial 16 finished with value: 0.47257906702114394 and parameters: {'C': 5.655558414691991, 'epsilon': 0.05318926194922638}. Best is trial 14 with value: 0.5035810814124261.
[I 2025-09-04 14:22:57,095] Trial 17 finished with value: 0.49908455691521136 and parameters: {'C': 1.7629143020634404, 'epsilon': 0.012065329303344877}. Best is trial 14 with value: 0.5035810814124261.
[I 2025-09-04 14:22:57,181] Trial 18 finished with value: 0.44707860851765024 and parameters: {'C': 0.902095321191412, 'epsilon': 0.03434620955510924}. Best is trial 14 with value: 0.5035810814124261.

Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===

[I 2025-09-04 14:22:57,271] Trial 19 finished with value: 0.4962968187218706 and parameters: {'C': 1.670735834745327, 'epsilon': 0.060111913982903206}. Best is trial 14 with value: 0.5035810814124261.
[I 2025-09-04 14:22:57,358] Trial 20 finished with value: 0.23232411584235746 and parameters: {'C': 0.2735471296854356, 'epsilon': 0.023396855362781563}. Best is trial 14 with value: 0.5035810814124261.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2

[I 2025-09-04 14:22:57,449] Trial 21 finished with value: 0.5019697022366618 and parameters: {'C': 2.3738388624218474, 'epsilon': 0.07485514164572858}. Best is trial 14 with value: 0.5035810814124261.
[I 2025-09-04 14:22:57,540] Trial 22 finished with value: 0.4793737469956042 and parameters: {'C': 5.649694712311604, 'epsilon': 0.10923245335791061}. Best is trial 14 with value: 0.5035810814124261.

Fold 3
Fold 4
Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 14:22:57,632] Trial 23 finished with value: 0.5029736723981973 and parameters: {'C': 2.1294907357268467, 'epsilon': 0.0670931955908181}. Best is trial 14 with value: 0.5035810814124261.
[I 2025-09-04 14:22:57,726] Trial 24 finished with value: 0.4894659291987553 and parameters: {'C': 4.141138887794886, 'epsilon': 0.04045456928750427}. Best is trial 14 with value: 0.5035810814124261.
[I 2025-09-04 14:22:57,727] A new study created in memory with name: no-name-a086011a-bd9b-458b-84fc-ae84763b3b8f
[I 2025-09-04 14:22:57,794] Trial 0 finished with value: 0.6352555702304021 and parameters: {'n_neighbors': 6, 'leaf_size': 37}. Best is trial 0 with value: 0.6352555702304021.

Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

✅ SVR con TOA_9x9_depth_in_3_4 - Mejor R2: 0.50
📋 Parámetros: {'C': 1.9860741741743726, 'epsilon': 0.023712171259654913}

Buscando mejores hiperparámetros para KNN con TOA_9x9_depth_in_3_4...

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2

[I 2025-09-04 14:22:57,863] Trial 1 finished with value: 0.6274425238457273 and parameters: {'n_neighbors': 7, 'leaf_size': 31}. Best is trial 0 with value: 0.6352555702304021.
[I 2025-09-04 14:22:57,929] Trial 2 finished with value: 0.6274425238457273 and parameters: {'n_neighbors': 7, 'leaf_size': 29}. Best is trial 0 with value: 0.6352555702304021.
[I 2025-09-04 14:22:57,992] Trial 3 finished with value: 0.6180090276648802 and parameters: {'n_neighbors': 5, 'leaf_size': 21}. Best is trial 0 with value: 0.6352555702304021.

Fold 3
Fold 4
Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 14:22:58,064] Trial 4 finished with value: 0.5631889213409096 and parameters: {'n_neighbors': 3, 'leaf_size': 26}. Best is trial 0 with value: 0.6352555702304021.
[I 2025-09-04 14:22:58,134] Trial 5 finished with value: 0.5631889213409096 and parameters: {'n_neighbors': 3, 'leaf_size': 30}. Best is trial 0 with value: 0.6352555702304021.
[I 2025-09-04 14:22:58,198] Trial 6 finished with value: 0.6352555702304021 and parameters: {'n_neighbors': 6, 'leaf_size': 21}. Best is trial 0 with value: 0.6352555702304021.

Fold 4
Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 14:22:58,266] Trial 7 finished with value: 0.6216918969405106 and parameters: {'n_neighbors': 4, 'leaf_size': 23}. Best is trial 0 with value: 0.6352555702304021.
[I 2025-09-04 14:22:58,332] Trial 8 finished with value: 0.6216918969405106 and parameters: {'n_neighbors': 4, 'leaf_size': 18}. Best is trial 0 with value: 0.6352555702304021.
[I 2025-09-04 14:22:58,398] Trial 9 finished with value: 0.6180090276648802 and parameters: {'n_neighbors': 5, 'leaf_size': 19}. Best is trial 0 with value: 0.6352555702304021.

Fold 4
Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 14:22:58,471] Trial 10 finished with value: 0.6502137631332365 and parameters: {'n_neighbors': 10, 'leaf_size': 40}. Best is trial 10 with value: 0.6502137631332365.
[I 2025-09-04 14:22:58,545] Trial 11 finished with value: 0.6502137631332365 and parameters: {'n_neighbors': 10, 'leaf_size': 40}. Best is trial 10 with value: 0.6502137631332365.
[I 2025-09-04 14:22:58,615] Trial 12 finished with value: 0.6502137631332365 and parameters: {'n_neighbors': 10, 'leaf_size': 39}. Best is trial 10 with value: 0.6502137631332365.

Fold 4
Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2

[I 2025-09-04 14:22:58,692] Trial 13 finished with value: 0.6502137631332365 and parameters: {'n_neighbors': 10, 'leaf_size': 35}. Best is trial 10 with value: 0.6502137631332365.
[I 2025-09-04 14:22:58,764] Trial 14 finished with value: 0.6486022555758657 and parameters: {'n_neighbors': 9, 'leaf_size': 12}. Best is trial 10 with value: 0.6502137631332365.
[I 2025-09-04 14:22:58,836] Trial 15 finished with value: 0.6400863937050706 and parameters: {'n_neighbors': 8, 'leaf_size': 40}. Best is trial 10 with value: 0.6502137631332365.

Fold 3
Fold 4
Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1

[I 2025-09-04 14:22:58,911] Trial 16 finished with value: 0.6486022555758657 and parameters: {'n_neighbors': 9, 'leaf_size': 35}. Best is trial 10 with value: 0.6502137631332365.
[I 2025-09-04 14:22:58,983] Trial 17 finished with value: 0.6486022555758657 and parameters: {'n_neighbors': 9, 'leaf_size': 34}. Best is trial 10 with value: 0.6502137631332365.
[I 2025-09-04 14:22:59,054] Trial 18 finished with value: 0.6400863937050706 and parameters: {'n_neighbors': 8, 'leaf_size': 40}. Best is trial 10 with value: 0.6502137631332365.

Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===

[I 2025-09-04 14:22:59,128] Trial 19 finished with value: 0.6502137631332365 and parameters: {'n_neighbors': 10, 'leaf_size': 10}. Best is trial 10 with value: 0.6502137631332365.
[I 2025-09-04 14:22:59,200] Trial 20 finished with value: 0.6400863937050706 and parameters: {'n_neighbors': 8, 'leaf_size': 32}. Best is trial 10 with value: 0.6502137631332365.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:22:59,272] Trial 21 finished with value: 0.6502137631332365 and parameters: {'n_neighbors': 10, 'leaf_size': 38}. Best is trial 10 with value: 0.6502137631332365.
[I 2025-09-04 14:22:59,346] Trial 22 finished with value: 0.6502137631332365 and parameters: {'n_neighbors': 10, 'leaf_size': 38}. Best is trial 10 with value: 0.6502137631332365.
[I 2025-09-04 14:22:59,417] Trial 23 finished with value: 0.6486022555758657 and parameters: {'n_neighbors': 9, 'leaf_size': 40}. Best is trial 10 with value: 0.6502137631332365.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:22:59,489] Trial 24 finished with value: 0.6502137631332365 and parameters: {'n_neighbors': 10, 'leaf_size': 36}. Best is trial 10 with value: 0.6502137631332365.
[I 2025-09-04 14:22:59,490] A new study created in memory with name: no-name-f4608119-5d12-41c7-8e6b-e8234d5a8b3a
[I 2025-09-04 14:22:59,556] Trial 0 finished with value: 0.3359911464154939 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: 0.3359911464154939.
[I 2025-09-04 14:22:59,617] Trial 1 finished with value: 0.33599114641549377 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 0 with value: 0.3359911464154939.
[I 2025-09-04 14:22:59,679] Trial 2 finished with value: 0.33599114641549377 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 0 with value: 0.3359911464154939.

✅ KNN con TOA_9x9_depth_in_3_4 - Mejor R2: 0.65
📋 Parámetros: {'n_neighbors': 10, 'leaf_size': 40}

Buscando mejores hiperparámetros para LR con TOA_9x9_depth_in_3_4...

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1

[I 2025-09-04 14:22:59,743] Trial 3 finished with value: 0.3359911464154939 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: 0.3359911464154939.
[I 2025-09-04 14:22:59,822] Trial 4 finished with value: 0.33599114641549377 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 0 with value: 0.3359911464154939.

Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:22:59,904] Trial 5 finished with value: 0.3782291754338225 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 5 with value: 0.3782291754338225.
[I 2025-09-04 14:22:59,988] Trial 6 finished with value: 0.3359911464154939 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 5 with value: 0.3782291754338225.
[I 2025-09-04 14:23:00,077] Trial 7 finished with value: 0.3782291754338225 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 5 with value: 0.3782291754338225.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2

[I 2025-09-04 14:23:00,165] Trial 8 finished with value: 0.3359911464154939 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 5 with value: 0.3782291754338225.
[I 2025-09-04 14:23:00,249] Trial 9 finished with value: 0.3782291754338225 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 5 with value: 0.3782291754338225.

Fold 3
Fold 4
Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:23:00,342] Trial 10 finished with value: 0.3782291754338225 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 5 with value: 0.3782291754338225.
[I 2025-09-04 14:23:00,437] Trial 11 finished with value: 0.3782291754338225 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 5 with value: 0.3782291754338225.
[I 2025-09-04 14:23:00,526] Trial 12 finished with value: 0.3782291754338225 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 5 with value: 0.3782291754338225.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1

[I 2025-09-04 14:23:00,618] Trial 13 finished with value: 0.3782291754338225 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 5 with value: 0.3782291754338225.
[I 2025-09-04 14:23:00,710] Trial 14 finished with value: 0.3782291754338225 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 5 with value: 0.3782291754338225.

Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 14:23:00,803] Trial 15 finished with value: 0.3782291754338225 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 5 with value: 0.3782291754338225.
[I 2025-09-04 14:23:00,896] Trial 16 finished with value: 0.3782291754338225 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 5 with value: 0.3782291754338225.

Fold 4
Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 14:23:00,985] Trial 17 finished with value: 0.3782291754338225 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 5 with value: 0.3782291754338225.
[I 2025-09-04 14:23:01,080] Trial 18 finished with value: 0.37822917543341517 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 5 with value: 0.3782291754338225.

Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:23:01,169] Trial 19 finished with value: 0.3782291754338225 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 5 with value: 0.3782291754338225.
[I 2025-09-04 14:23:01,260] Trial 20 finished with value: 0.3782291754338225 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 5 with value: 0.3782291754338225.
[I 2025-09-04 14:23:01,349] Trial 21 finished with value: 0.3782291754338225 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 5 with value: 0.3782291754338225.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1

[I 2025-09-04 14:23:01,440] Trial 22 finished with value: 0.3782291754338225 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 5 with value: 0.3782291754338225.
[I 2025-09-04 14:23:01,533] Trial 23 finished with value: 0.3782291754338225 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 5 with value: 0.3782291754338225.

Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2

[I 2025-09-04 14:23:01,631] Trial 24 finished with value: 0.3782291754338225 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 5 with value: 0.3782291754338225.
[I 2025-09-04 14:23:01,632] A new study created in memory with name: no-name-71c25c0b-c806-450e-95e3-c6126f466db6

Fold 3
Fold 4
Fold 5

✅ LR con TOA_9x9_depth_in_3_4 - Mejor R2: 0.38
📋 Parámetros: {'fit_intercept': False, 'positive': False}

Buscando mejores hiperparámetros para RF con TOA_9x9_depth_in_3_4...

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:23:09,540] Trial 0 finished with value: 0.38419198536079324 and parameters: {'n_estimators': 300, 'max_depth': 6, 'min_samples_split': 7, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 0 with value: 0.38419198536079324.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:23:19,418] Trial 1 finished with value: 0.5813911407929171 and parameters: {'n_estimators': 500, 'max_depth': 10, 'min_samples_split': 7, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 1 with value: 0.5813911407929171.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:23:22,875] Trial 2 finished with value: 0.5650601810848347 and parameters: {'n_estimators': 100, 'max_depth': 12, 'min_samples_split': 10, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 1 with value: 0.5813911407929171.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:23:29,819] Trial 3 finished with value: 0.31302408988435004 and parameters: {'n_estimators': 300, 'max_depth': 5, 'min_samples_split': 5, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 1 with value: 0.5813911407929171.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:23:39,184] Trial 4 finished with value: 0.5966874428033891 and parameters: {'n_estimators': 500, 'max_depth': 7, 'min_samples_split': 3, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 4 with value: 0.5966874428033891.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:23:54,440] Trial 5 finished with value: 0.48692900088387503 and parameters: {'n_estimators': 500, 'max_depth': 8, 'min_samples_split': 2, 'min_samples_leaf': 4, 'bootstrap': False}. Best is trial 4 with value: 0.5966874428033891.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:24:01,074] Trial 6 finished with value: 0.6045631150459528 and parameters: {'n_estimators': 300, 'max_depth': 10, 'min_samples_split': 4, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 6 with value: 0.6045631150459528.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:24:07,899] Trial 7 finished with value: 0.6057511133403224 and parameters: {'n_estimators': 300, 'max_depth': 13, 'min_samples_split': 4, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 7 with value: 0.6057511133403224.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:24:11,046] Trial 8 finished with value: 0.44526448616315517 and parameters: {'n_estimators': 100, 'max_depth': 8, 'min_samples_split': 3, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 7 with value: 0.6057511133403224.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:24:17,112] Trial 9 finished with value: 0.6022025648597502 and parameters: {'n_estimators': 300, 'max_depth': 9, 'min_samples_split': 10, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 7 with value: 0.6057511133403224.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:24:25,112] Trial 10 finished with value: 0.6116474751566894 and parameters: {'n_estimators': 300, 'max_depth': 15, 'min_samples_split': 6, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 10 with value: 0.6116474751566894.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:24:33,086] Trial 11 finished with value: 0.6116474751566894 and parameters: {'n_estimators': 300, 'max_depth': 15, 'min_samples_split': 6, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 10 with value: 0.6116474751566894.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:24:40,913] Trial 12 finished with value: 0.6128482853531565 and parameters: {'n_estimators': 300, 'max_depth': 15, 'min_samples_split': 7, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 12 with value: 0.6128482853531565.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:24:48,604] Trial 13 finished with value: 0.6143239501381514 and parameters: {'n_estimators': 300, 'max_depth': 15, 'min_samples_split': 8, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 13 with value: 0.6143239501381514.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:24:55,730] Trial 14 finished with value: 0.6233436524195008 and parameters: {'n_estimators': 300, 'max_depth': 13, 'min_samples_split': 8, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 14 with value: 0.6233436524195008.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:24:58,095] Trial 15 finished with value: 0.6221746444434282 and parameters: {'n_estimators': 100, 'max_depth': 13, 'min_samples_split': 9, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 14 with value: 0.6233436524195008.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:25:00,451] Trial 16 finished with value: 0.6218040882413208 and parameters: {'n_estimators': 100, 'max_depth': 12, 'min_samples_split': 9, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 14 with value: 0.6233436524195008.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:25:02,813] Trial 17 finished with value: 0.6221746444434282 and parameters: {'n_estimators': 100, 'max_depth': 13, 'min_samples_split': 9, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 14 with value: 0.6233436524195008.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:25:05,204] Trial 18 finished with value: 0.6216661158255253 and parameters: {'n_estimators': 100, 'max_depth': 13, 'min_samples_split': 8, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 14 with value: 0.6233436524195008.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:25:07,524] Trial 19 finished with value: 0.6224934516860682 and parameters: {'n_estimators': 100, 'max_depth': 11, 'min_samples_split': 9, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 14 with value: 0.6233436524195008.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:25:09,878] Trial 20 finished with value: 0.6218442035064482 and parameters: {'n_estimators': 100, 'max_depth': 11, 'min_samples_split': 8, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 14 with value: 0.6233436524195008.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:25:12,230] Trial 21 finished with value: 0.6218040882413208 and parameters: {'n_estimators': 100, 'max_depth': 12, 'min_samples_split': 9, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 14 with value: 0.6233436524195008.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:25:14,583] Trial 22 finished with value: 0.6239765333786712 and parameters: {'n_estimators': 100, 'max_depth': 14, 'min_samples_split': 10, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 22 with value: 0.6239765333786712.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:25:16,939] Trial 23 finished with value: 0.6239765333786712 and parameters: {'n_estimators': 100, 'max_depth': 14, 'min_samples_split': 10, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 22 with value: 0.6239765333786712.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:25:19,145] Trial 24 finished with value: 0.6150417723888677 and parameters: {'n_estimators': 100, 'max_depth': 14, 'min_samples_split': 10, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 22 with value: 0.6239765333786712.
[I 2025-09-04 14:25:19,146] A new study created in memory with name: no-name-a0306458-8281-4624-9e0a-47a9dc57a143

✅ RF con TOA_9x9_depth_in_3_4 - Mejor R2: 0.62
📋 Parámetros: {'n_estimators': 100, 'max_depth': 14, 'min_samples_split': 10, 'min_samples_leaf': 2, 'bootstrap': True}

Buscando mejores hiperparámetros para CAT con TOA_9x9_depth_in_3_4...

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:25:26,871] Trial 0 finished with value: 0.5618273469438501 and parameters: {'iterations': 500, 'learning_rate': 0.012550183022552654, 'depth': 7, 'l2_leaf_reg': 4.306144636429554}. Best is trial 0 with value: 0.5618273469438501.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:25:31,070] Trial 1 finished with value: 0.5577508980226897 and parameters: {'iterations': 1000, 'learning_rate': 0.016919382155284778, 'depth': 5, 'l2_leaf_reg': 5.8859315806372745}. Best is trial 0 with value: 0.5618273469438501.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:25:34,434] Trial 2 finished with value: 0.5960547458073078 and parameters: {'iterations': 500, 'learning_rate': 0.029356442998696428, 'depth': 6, 'l2_leaf_reg': 1.7217779263162933}. Best is trial 2 with value: 0.5960547458073078.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:25:37,661] Trial 3 finished with value: 0.5649291615963143 and parameters: {'iterations': 500, 'learning_rate': 0.04262298665218513, 'depth': 6, 'l2_leaf_reg': 4.5848505701945035}. Best is trial 2 with value: 0.5960547458073078.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:25:46,046] Trial 4 finished with value: 0.5812193861965929 and parameters: {'iterations': 2000, 'learning_rate': 0.015228054899899535, 'depth': 5, 'l2_leaf_reg': 1.3377047053839326}. Best is trial 2 with value: 0.5960547458073078.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:28:51,976] Trial 5 finished with value: 0.6103065605788502 and parameters: {'iterations': 2000, 'learning_rate': 0.0259336605441769, 'depth': 9, 'l2_leaf_reg': 2.742550736659061}. Best is trial 5 with value: 0.6103065605788502.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:28:57,651] Trial 6 finished with value: 0.5121905067729791 and parameters: {'iterations': 2000, 'learning_rate': 0.025238822635408036, 'depth': 4, 'l2_leaf_reg': 5.103132610647103}. Best is trial 5 with value: 0.6103065605788502.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:29:37,979] Trial 7 finished with value: 0.6205161408197988 and parameters: {'iterations': 1000, 'learning_rate': 0.0678180379236064, 'depth': 8, 'l2_leaf_reg': 2.511488464786048}. Best is trial 7 with value: 0.6205161408197988.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:29:58,073] Trial 8 finished with value: 0.6008254199466707 and parameters: {'iterations': 500, 'learning_rate': 0.05943167939160031, 'depth': 8, 'l2_leaf_reg': 3.790015751320361}. Best is trial 7 with value: 0.6205161408197988.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:30:01,368] Trial 9 finished with value: 0.5991179289235233 and parameters: {'iterations': 500, 'learning_rate': 0.045102656086682534, 'depth': 6, 'l2_leaf_reg': 2.056267717367614}. Best is trial 7 with value: 0.6205161408197988.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:32:53,830] Trial 10 finished with value: 0.6013644067749948 and parameters: {'iterations': 1000, 'learning_rate': 0.07678604986124864, 'depth': 10, 'l2_leaf_reg': 2.906862119680067}. Best is trial 7 with value: 0.6205161408197988.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:34:26,530] Trial 11 finished with value: 0.6070823252855666 and parameters: {'iterations': 1000, 'learning_rate': 0.025088633031335072, 'depth': 9, 'l2_leaf_reg': 2.798721443604866}. Best is trial 7 with value: 0.6205161408197988.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:37:32,624] Trial 12 finished with value: 0.6079065110603876 and parameters: {'iterations': 2000, 'learning_rate': 0.035542619382227164, 'depth': 9, 'l2_leaf_reg': 2.65010075126944}. Best is trial 7 with value: 0.6205161408197988.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:38:12,420] Trial 13 finished with value: 0.6053110070358961 and parameters: {'iterations': 1000, 'learning_rate': 0.0189762303222789, 'depth': 8, 'l2_leaf_reg': 3.4232317106878734}. Best is trial 7 with value: 0.6205161408197988.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:43:58,148] Trial 14 finished with value: 0.6133944696854361 and parameters: {'iterations': 2000, 'learning_rate': 0.07847008979685577, 'depth': 10, 'l2_leaf_reg': 2.0962003929291235}. Best is trial 7 with value: 0.6205161408197988.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:49:43,904] Trial 15 finished with value: 0.6066642020242577 and parameters: {'iterations': 2000, 'learning_rate': 0.0779030089513596, 'depth': 10, 'l2_leaf_reg': 2.0742043431810395}. Best is trial 7 with value: 0.6205161408197988.
[I 2025-09-04 14:49:43,905] A new study created in memory with name: no-name-b7d133d8-7e64-4395-9965-e4e8e0cc508c
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.215e+01, tolerance: 4.075e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.041e+01, tolerance: 4.583e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.925e+01, tolerance: 3.985e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.739e+01, tolerance: 5.497e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.598e+01, tolerance: 4.044e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 14:49:44,027] Trial 0 finished with value: 0.4316351319258911 and parameters: {'alpha': 0.0018281094410465236, 'l1_ratio': 0.5193642478703412}. Best is trial 0 with value: 0.4316351319258911.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.695e+01, tolerance: 4.075e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.072e+02, tolerance: 4.583e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.323e+01, tolerance: 3.985e-02
  model = cd_fast.enet_coordinate_descent(

✅ CAT con TOA_9x9_depth_in_3_4 - Mejor R2: 0.62
📋 Parámetros: {'iterations': 1000, 'learning_rate': 0.0678180379236064, 'depth': 8, 'l2_leaf_reg': 2.511488464786048}

Buscando mejores hiperparámetros para ELN con TOA_9x9_depth_in_3_4...

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.209e+02, tolerance: 5.497e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.291e+01, tolerance: 4.044e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 14:49:44,163] Trial 1 finished with value: 0.4605477291645643 and parameters: {'alpha': 0.00018278796685996404, 'l1_ratio': 0.6310698589855364}. Best is trial 1 with value: 0.4605477291645643.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.031e+01, tolerance: 4.075e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.057e+02, tolerance: 4.583e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.224e+01, tolerance: 3.985e-02
  model = cd_fast.enet_coordinate_descent(

Fold 4
Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.173e+02, tolerance: 5.497e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.474e+01, tolerance: 4.044e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 14:49:44,311] Trial 2 finished with value: 0.4404692016951185 and parameters: {'alpha': 0.0007700338414114464, 'l1_ratio': 0.21197988227474585}. Best is trial 1 with value: 0.4605477291645643.
[I 2025-09-04 14:49:44,401] Trial 3 finished with value: 0.38367300948194205 and parameters: {'alpha': 0.22109348726554806, 'l1_ratio': 0.27954658211088046}. Best is trial 1 with value: 0.4605477291645643.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.024e+02, tolerance: 4.075e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.213e+02, tolerance: 4.583e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.314e+01, tolerance: 3.985e-02
  model = cd_fast.enet_coordinate_descent(

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.437e+02, tolerance: 5.497e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.041e+02, tolerance: 4.044e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 14:49:44,535] Trial 4 finished with value: 0.42095260775345456 and parameters: {'alpha': 0.022229935733524244, 'l1_ratio': 0.013785045102191473}. Best is trial 1 with value: 0.4605477291645643.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.730e+01, tolerance: 4.075e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.911e+01, tolerance: 4.583e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.370e+01, tolerance: 3.985e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.612e+01, tolerance: 5.497e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.544e+01, tolerance: 4.044e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 14:49:44,721] Trial 5 finished with value: 0.45174167394221665 and parameters: {'alpha': 0.0006263837321572532, 'l1_ratio': 0.7228610122015485}. Best is trial 1 with value: 0.4605477291645643.

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.601e+01, tolerance: 4.075e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.138e+02, tolerance: 4.583e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.964e+01, tolerance: 3.985e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.302e+02, tolerance: 5.497e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.053e+02, tolerance: 4.044e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 14:49:44,866] Trial 6 finished with value: 0.46008513569271625 and parameters: {'alpha': 0.00012170164029958029, 'l1_ratio': 0.3432070961037861}. Best is trial 1 with value: 0.4605477291645643.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.650e+01, tolerance: 4.075e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.148e+02, tolerance: 4.583e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.904e+01, tolerance: 3.985e-02
  model = cd_fast.enet_coordinate_descent(

Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.296e+02, tolerance: 5.497e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.037e+02, tolerance: 4.044e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 14:49:45,005] Trial 7 finished with value: 0.4562934328582994 and parameters: {'alpha': 0.00025728397520808716, 'l1_ratio': 0.2408707168365981}. Best is trial 1 with value: 0.4605477291645643.
[I 2025-09-04 14:49:45,092] Trial 8 finished with value: 0.3264603074677709 and parameters: {'alpha': 0.17393719544515723, 'l1_ratio': 0.8029614545973848}. Best is trial 1 with value: 0.4605477291645643.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.965e+01, tolerance: 4.075e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.058e+01, tolerance: 4.583e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.735e+01, tolerance: 3.985e-02
  model = cd_fast.enet_coordinate_descent(

Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.150e+01, tolerance: 5.497e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.423e+01, tolerance: 4.044e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 14:49:45,221] Trial 9 finished with value: 0.41682694210890925 and parameters: {'alpha': 0.012026531122033156, 'l1_ratio': 0.13835793968804866}. Best is trial 1 with value: 0.4605477291645643.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.841e+00, tolerance: 4.075e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.252e+00, tolerance: 4.583e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.773e+00, tolerance: 3.985e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.420e+00, tolerance: 5.497e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.595e+00, tolerance: 4.044e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 14:49:45,349] Trial 10 finished with value: 0.410757988642916 and parameters: {'alpha': 0.003084476400342453, 'l1_ratio': 0.9726337431582363}. Best is trial 1 with value: 0.4605477291645643.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.403e+01, tolerance: 4.075e-02
  model = cd_fast.enet_coordinate_descent(

Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.118e+02, tolerance: 4.583e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.792e+01, tolerance: 3.985e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.277e+02, tolerance: 5.497e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.025e+02, tolerance: 4.044e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 14:49:45,497] Trial 11 finished with value: 0.46072981372277466 and parameters: {'alpha': 0.00011934107331685027, 'l1_ratio': 0.48282689689606867}. Best is trial 11 with value: 0.46072981372277466.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.395e+01, tolerance: 4.075e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.117e+02, tolerance: 4.583e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.797e+01, tolerance: 3.985e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.278e+02, tolerance: 5.497e-02
  model = cd_fast.enet_coordinate_descent(

Fold 3
Fold 4
Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.034e+02, tolerance: 4.044e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 14:49:45,638] Trial 12 finished with value: 0.4612048912659015 and parameters: {'alpha': 0.00010094145044864732, 'l1_ratio': 0.5266509861480015}. Best is trial 12 with value: 0.4612048912659015.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.488e+01, tolerance: 4.075e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.126e+02, tolerance: 4.583e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.876e+01, tolerance: 3.985e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.289e+02, tolerance: 5.497e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.044e+02, tolerance: 4.044e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 14:49:45,783] Trial 13 finished with value: 0.4608419360441601 and parameters: {'alpha': 0.00010382758594970623, 'l1_ratio': 0.4448961474318054}. Best is trial 12 with value: 0.4612048912659015.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.843e+00, tolerance: 4.075e-02
  model = cd_fast.enet_coordinate_descent(

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.125e+00, tolerance: 4.583e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.539e+00, tolerance: 3.985e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.087e+01, tolerance: 5.497e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.934e+00, tolerance: 4.044e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 14:49:45,926] Trial 14 finished with value: 0.4210837864545047 and parameters: {'alpha': 0.003968327897690163, 'l1_ratio': 0.4818654492611416}. Best is trial 12 with value: 0.4612048912659015.
[I 2025-09-04 14:49:46,034] Trial 15 finished with value: 0.45976297426833157 and parameters: {'alpha': 0.05448338315155033, 'l1_ratio': 0.4159486898962399}. Best is trial 12 with value: 0.4612048912659015.

Fold 3
Fold 4
Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.651e+01, tolerance: 4.075e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.171e+01, tolerance: 4.583e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.573e+01, tolerance: 3.985e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.770e+01, tolerance: 5.497e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.524e+01, tolerance: 4.044e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 14:49:46,177] Trial 16 finished with value: 0.4451987980481482 and parameters: {'alpha': 0.0008167958547101754, 'l1_ratio': 0.6112838374967728}. Best is trial 12 with value: 0.4612048912659015.
[I 2025-09-04 14:49:46,271] Trial 17 finished with value: 0.19494728253449378 and parameters: {'alpha': 0.6265604117294031, 'l1_ratio': 0.8575433111800489}. Best is trial 12 with value: 0.4612048912659015.

Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.049e+01, tolerance: 4.075e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.767e+01, tolerance: 4.583e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.317e+01, tolerance: 3.985e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.048e+02, tolerance: 5.497e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.233e+01, tolerance: 4.044e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 14:49:46,414] Trial 18 finished with value: 0.45713371265444047 and parameters: {'alpha': 0.0003782287705483986, 'l1_ratio': 0.6083038337916482}. Best is trial 12 with value: 0.4612048912659015.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.280e+01, tolerance: 4.075e-02
  model = cd_fast.enet_coordinate_descent(

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.618e+01, tolerance: 4.583e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.390e+01, tolerance: 3.985e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.385e+01, tolerance: 5.497e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.319e+01, tolerance: 4.044e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 14:49:46,562] Trial 19 finished with value: 0.42810452604136273 and parameters: {'alpha': 0.002016567334590037, 'l1_ratio': 0.37191446957341057}. Best is trial 12 with value: 0.4612048912659015.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.535e-01, tolerance: 3.985e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.145e-02, tolerance: 5.497e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 14:49:46,691] Trial 20 finished with value: 0.4217412371087371 and parameters: {'alpha': 0.006506470235149185, 'l1_ratio': 0.7484063604977187}. Best is trial 12 with value: 0.4612048912659015.

Fold 4
Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.459e+01, tolerance: 4.075e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.123e+02, tolerance: 4.583e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.852e+01, tolerance: 3.985e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.286e+02, tolerance: 5.497e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.041e+02, tolerance: 4.044e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 14:49:46,842] Trial 21 finished with value: 0.46097238355924297 and parameters: {'alpha': 0.00010192234269066232, 'l1_ratio': 0.47157958434548974}. Best is trial 12 with value: 0.4612048912659015.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.340e+01, tolerance: 4.075e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.539e+01, tolerance: 4.583e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.669e+01, tolerance: 3.985e-02
  model = cd_fast.enet_coordinate_descent(

Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.125e+02, tolerance: 5.497e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.636e+01, tolerance: 4.044e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 14:49:46,994] Trial 22 finished with value: 0.4579369902470385 and parameters: {'alpha': 0.00032889213869300837, 'l1_ratio': 0.567911277054063}. Best is trial 12 with value: 0.4612048912659015.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.515e+01, tolerance: 4.075e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.129e+02, tolerance: 4.583e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.900e+01, tolerance: 3.985e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.293e+02, tolerance: 5.497e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.048e+02, tolerance: 4.044e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 14:49:47,152] Trial 23 finished with value: 0.46077522810076155 and parameters: {'alpha': 0.00010311390241087947, 'l1_ratio': 0.4246749648124884}. Best is trial 12 with value: 0.4612048912659015.

Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_9x9_depth_in_3_4 ===

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.607e+01, tolerance: 4.075e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.941e+01, tolerance: 4.583e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.736e+01, tolerance: 3.985e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.530e+01, tolerance: 5.497e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.681e+01, tolerance: 4.044e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 14:49:47,303] Trial 24 finished with value: 0.45641010866165976 and parameters: {'alpha': 0.00045073019090607403, 'l1_ratio': 0.6655282274386418}. Best is trial 12 with value: 0.4612048912659015.
[I 2025-09-04 14:49:47,304] A new study created in memory with name: no-name-4ad3aea5-08ac-4aa2-b7d5-228edd0aba6b

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

✅ ELN con TOA_9x9_depth_in_3_4 - Mejor R2: 0.46
📋 Parámetros: {'alpha': 0.00010094145044864732, 'l1_ratio': 0.5266509861480015}

Buscando mejores hiperparámetros para XGB con TOA_3x3_depth_in_3_4...

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:49:51,615] Trial 0 finished with value: 0.46735247034274907 and parameters: {'n_estimators': 1000, 'learning_rate': 0.0054995544716750925, 'max_depth': 5, 'min_child_weight': 1, 'subsample': 0.9224366294669406, 'colsample_bytree': 0.7754520202692887}. Best is trial 0 with value: 0.46735247034274907.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:49:53,719] Trial 1 finished with value: 0.5786954094579102 and parameters: {'n_estimators': 500, 'learning_rate': 0.006610896047698369, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.7182652021670114, 'colsample_bytree': 0.7842915329427098}. Best is trial 1 with value: 0.5786954094579102.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:50:05,426] Trial 2 finished with value: 0.5750825553055966 and parameters: {'n_estimators': 2000, 'learning_rate': 0.007987631053009309, 'max_depth': 8, 'min_child_weight': 3, 'subsample': 0.7110975968242698, 'colsample_bytree': 0.9076322858975898}. Best is trial 1 with value: 0.5786954094579102.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:50:07,733] Trial 3 finished with value: 0.6028961884929347 and parameters: {'n_estimators': 500, 'learning_rate': 0.024307025902482054, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.817018204072651, 'colsample_bytree': 0.7914760067062885}. Best is trial 3 with value: 0.6028961884929347.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:50:19,216] Trial 4 finished with value: 0.5661841079866557 and parameters: {'n_estimators': 2000, 'learning_rate': 0.012802178069024991, 'max_depth': 8, 'min_child_weight': 2, 'subsample': 0.9378029240605306, 'colsample_bytree': 0.6549351659505935}. Best is trial 3 with value: 0.6028961884929347.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:50:23,625] Trial 5 finished with value: 0.5808098556373991 and parameters: {'n_estimators': 1000, 'learning_rate': 0.016322295596710296, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.7321203440377895, 'colsample_bytree': 0.9054612133268024}. Best is trial 3 with value: 0.6028961884929347.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:50:28,039] Trial 6 finished with value: 0.48477339298939615 and parameters: {'n_estimators': 1000, 'learning_rate': 0.02262256399772201, 'max_depth': 5, 'min_child_weight': 1, 'subsample': 0.8287233414791125, 'colsample_bytree': 0.750995752621827}. Best is trial 3 with value: 0.6028961884929347.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:50:33,887] Trial 7 finished with value: 0.5558351877419574 and parameters: {'n_estimators': 1000, 'learning_rate': 0.028394958918725958, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.6891843773056386, 'colsample_bytree': 0.8751405075444725}. Best is trial 3 with value: 0.6028961884929347.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:50:35,785] Trial 8 finished with value: 0.5872073809378633 and parameters: {'n_estimators': 500, 'learning_rate': 0.017163738231210167, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.630455035130762, 'colsample_bytree': 0.7307074817215814}. Best is trial 3 with value: 0.6028961884929347.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:50:38,629] Trial 9 finished with value: 0.6224130752588616 and parameters: {'n_estimators': 500, 'learning_rate': 0.008070629169456287, 'max_depth': 8, 'min_child_weight': 4, 'subsample': 0.7372259890663841, 'colsample_bytree': 0.7264794665553103}. Best is trial 9 with value: 0.6224130752588616.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:50:41,010] Trial 10 finished with value: 0.6087508878656127 and parameters: {'n_estimators': 500, 'learning_rate': 0.044839681587725895, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.8699389207520228, 'colsample_bytree': 0.6547195770951562}. Best is trial 9 with value: 0.6224130752588616.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:50:43,348] Trial 11 finished with value: 0.6074887420093371 and parameters: {'n_estimators': 500, 'learning_rate': 0.049550597182461624, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.852341136850564, 'colsample_bytree': 0.6115641208707407}. Best is trial 9 with value: 0.6224130752588616.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:50:46,215] Trial 12 finished with value: 0.6126482598031614 and parameters: {'n_estimators': 500, 'learning_rate': 0.010129505527456813, 'max_depth': 8, 'min_child_weight': 4, 'subsample': 0.8883747938871474, 'colsample_bytree': 0.6833867744965362}. Best is trial 9 with value: 0.6224130752588616.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:50:49,083] Trial 13 finished with value: 0.6194266736988642 and parameters: {'n_estimators': 500, 'learning_rate': 0.009632259506750224, 'max_depth': 8, 'min_child_weight': 4, 'subsample': 0.7774904978274587, 'colsample_bytree': 0.69717806332018}. Best is trial 9 with value: 0.6224130752588616.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:50:52,187] Trial 14 finished with value: 0.6116729749650195 and parameters: {'n_estimators': 500, 'learning_rate': 0.009566874517821825, 'max_depth': 8, 'min_child_weight': 4, 'subsample': 0.7634546436808017, 'colsample_bytree': 0.8383724684453666}. Best is trial 9 with value: 0.6224130752588616.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:50:54,966] Trial 15 finished with value: 0.5798176803125723 and parameters: {'n_estimators': 500, 'learning_rate': 0.012360431826057401, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.6409194765115578, 'colsample_bytree': 0.9967091367760931}. Best is trial 9 with value: 0.6224130752588616.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:51:05,278] Trial 16 finished with value: 0.5943035891870516 and parameters: {'n_estimators': 2000, 'learning_rate': 0.007350617732206173, 'max_depth': 8, 'min_child_weight': 4, 'subsample': 0.7886860652250811, 'colsample_bytree': 0.7107246867007623}. Best is trial 9 with value: 0.6224130752588616.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:51:08,442] Trial 17 finished with value: 0.6020056775252558 and parameters: {'n_estimators': 500, 'learning_rate': 0.005195065728256086, 'max_depth': 8, 'min_child_weight': 3, 'subsample': 0.9975383978712318, 'colsample_bytree': 0.612096912738323}. Best is trial 9 with value: 0.6224130752588616.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:51:10,670] Trial 18 finished with value: 0.6230701314619785 and parameters: {'n_estimators': 500, 'learning_rate': 0.010024813194291299, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.6656638782278996, 'colsample_bytree': 0.7029352774714325}. Best is trial 18 with value: 0.6230701314619785.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:51:19,574] Trial 19 finished with value: 0.5679753829147646 and parameters: {'n_estimators': 2000, 'learning_rate': 0.012111819449749296, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.6007187976969421, 'colsample_bytree': 0.8295861027478302}. Best is trial 18 with value: 0.6230701314619785.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:51:21,793] Trial 20 finished with value: 0.6180469544965521 and parameters: {'n_estimators': 500, 'learning_rate': 0.0083658381287619, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.6735979496188923, 'colsample_bytree': 0.7447997651023118}. Best is trial 18 with value: 0.6230701314619785.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:51:24,283] Trial 21 finished with value: 0.6265638235837091 and parameters: {'n_estimators': 500, 'learning_rate': 0.009576598127245279, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.7615794445091003, 'colsample_bytree': 0.6930474458735117}. Best is trial 21 with value: 0.6265638235837091.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:51:26,816] Trial 22 finished with value: 0.616618011752045 and parameters: {'n_estimators': 500, 'learning_rate': 0.006108476080623529, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.7534963574035086, 'colsample_bytree': 0.6616302123127724}. Best is trial 21 with value: 0.6265638235837091.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:51:28,995] Trial 23 finished with value: 0.616301663910158 and parameters: {'n_estimators': 500, 'learning_rate': 0.013580460128286558, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.6702199811361483, 'colsample_bytree': 0.7115134499200724}. Best is trial 21 with value: 0.6265638235837091.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:51:31,534] Trial 24 finished with value: 0.6067143587088974 and parameters: {'n_estimators': 500, 'learning_rate': 0.010669283415882856, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.7398140566376801, 'colsample_bytree': 0.6356793958235228}. Best is trial 21 with value: 0.6265638235837091.
[I 2025-09-04 14:51:31,535] A new study created in memory with name: no-name-85bdf37e-463b-401c-ab4b-329ef3f5e3e0

✅ XGB con TOA_3x3_depth_in_3_4 - Mejor R2: 0.63
📋 Parámetros: {'n_estimators': 500, 'learning_rate': 0.009576598127245279, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.7615794445091003, 'colsample_bytree': 0.6930474458735117}

Buscando mejores hiperparámetros para LBM con TOA_3x3_depth_in_3_4...

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:51:32,736] Trial 0 finished with value: 0.5481945335935432 and parameters: {'learning_rate': 0.013156205202892145, 'num_leaves': 40, 'max_depth': 6, 'min_child_samples': 10, 'subsample': 0.6860452762552676, 'colsample_bytree': 0.7130189612480087, 'n_estimators': 2000}. Best is trial 0 with value: 0.5481945335935432.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:51:33,744] Trial 1 finished with value: 0.5325402210552859 and parameters: {'learning_rate': 0.027795381516607685, 'num_leaves': 80, 'max_depth': 5, 'min_child_samples': 16, 'subsample': 0.6303808275833142, 'colsample_bytree': 0.9664816096773176, 'n_estimators': 2000}. Best is trial 0 with value: 0.5481945335935432.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 14:51:34,025] Trial 2 finished with value: 0.5636491891414139 and parameters: {'learning_rate': 0.005906660561638928, 'num_leaves': 60, 'max_depth': 5, 'min_child_samples': 15, 'subsample': 0.7511518809439773, 'colsample_bytree': 0.6830103322931814, 'n_estimators': 500}. Best is trial 2 with value: 0.5636491891414139.

Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 14:51:34,739] Trial 3 finished with value: 0.578796375360155 and parameters: {'learning_rate': 0.005187588804652096, 'num_leaves': 60, 'max_depth': 7, 'min_child_samples': 14, 'subsample': 0.9496918498181869, 'colsample_bytree': 0.7286826708914593, 'n_estimators': 1000}. Best is trial 3 with value: 0.578796375360155.

Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:51:35,741] Trial 4 finished with value: 0.5631181248858638 and parameters: {'learning_rate': 0.0116226392735354, 'num_leaves': 80, 'max_depth': 5, 'min_child_samples': 14, 'subsample': 0.8271682575283531, 'colsample_bytree': 0.7577821706860829, 'n_estimators': 2000}. Best is trial 3 with value: 0.578796375360155.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 14:51:36,224] Trial 5 finished with value: 0.6150725376945254 and parameters: {'learning_rate': 0.025582700040158127, 'num_leaves': 20, 'max_depth': 8, 'min_child_samples': 4, 'subsample': 0.9360607303353214, 'colsample_bytree': 0.9727796020019702, 'n_estimators': 500}. Best is trial 5 with value: 0.6150725376945254.

Fold 4
Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:51:37,805] Trial 6 finished with value: 0.5869881902307821 and parameters: {'learning_rate': 0.028979784302184723, 'num_leaves': 80, 'max_depth': 8, 'min_child_samples': 8, 'subsample': 0.7287404768720032, 'colsample_bytree': 0.6440079429674147, 'n_estimators': 2000}. Best is trial 5 with value: 0.6150725376945254.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 14:51:38,219] Trial 7 finished with value: 0.6324480656556024 and parameters: {'learning_rate': 0.020978312598452002, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 5, 'subsample': 0.7768337614289185, 'colsample_bytree': 0.8400342872899099, 'n_estimators': 500}. Best is trial 7 with value: 0.6324480656556024.

Fold 4
Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:51:38,932] Trial 8 finished with value: 0.553392652158474 and parameters: {'learning_rate': 0.03698827396182541, 'num_leaves': 80, 'max_depth': 7, 'min_child_samples': 14, 'subsample': 0.907004739931171, 'colsample_bytree': 0.8577846252411727, 'n_estimators': 1000}. Best is trial 7 with value: 0.6324480656556024.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 14:51:39,374] Trial 9 finished with value: 0.6361776705216852 and parameters: {'learning_rate': 0.007684306527484153, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 9, 'subsample': 0.775636070014048, 'colsample_bytree': 0.9579768121064951, 'n_estimators': 500}. Best is trial 9 with value: 0.6361776705216852.

Fold 4
Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 14:51:39,766] Trial 10 finished with value: 0.6408178836066463 and parameters: {'learning_rate': 0.008224177066871348, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 8, 'subsample': 0.8433348441329972, 'colsample_bytree': 0.930197253752918, 'n_estimators': 500}. Best is trial 10 with value: 0.6408178836066463.

Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:51:40,162] Trial 11 finished with value: 0.6444711369105942 and parameters: {'learning_rate': 0.008147477556746092, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 8, 'subsample': 0.8419212052941786, 'colsample_bytree': 0.9095978233906395, 'n_estimators': 500}. Best is trial 11 with value: 0.6444711369105942.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 14:51:40,556] Trial 12 finished with value: 0.657337689990577 and parameters: {'learning_rate': 0.008401457428816336, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 6, 'subsample': 0.8509939374570139, 'colsample_bytree': 0.8982327400882761, 'n_estimators': 500}. Best is trial 12 with value: 0.657337689990577.

Fold 4
Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 14:51:40,951] Trial 13 finished with value: 0.6591067288417914 and parameters: {'learning_rate': 0.00965375252488391, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 6, 'subsample': 0.8775257963492445, 'colsample_bytree': 0.8854813351682452, 'n_estimators': 500}. Best is trial 13 with value: 0.6591067288417914.

Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:51:41,348] Trial 14 finished with value: 0.6571527566838032 and parameters: {'learning_rate': 0.011510817460007393, 'num_leaves': 40, 'max_depth': 6, 'min_child_samples': 6, 'subsample': 0.9917897826778229, 'colsample_bytree': 0.8647013789613497, 'n_estimators': 500}. Best is trial 13 with value: 0.6591067288417914.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 14:51:41,699] Trial 15 finished with value: 0.6569967187413002 and parameters: {'learning_rate': 0.018221031688215095, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 6, 'subsample': 0.8886319957145665, 'colsample_bytree': 0.7950569903189254, 'n_estimators': 500}. Best is trial 13 with value: 0.6591067288417914.

Fold 4
Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:51:42,273] Trial 16 finished with value: 0.5691249563109428 and parameters: {'learning_rate': 0.0092761742602199, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 12, 'subsample': 0.8819397448238075, 'colsample_bytree': 0.8977891625411358, 'n_estimators': 1000}. Best is trial 13 with value: 0.6591067288417914.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 14:51:42,631] Trial 17 finished with value: 0.6534586678903052 and parameters: {'learning_rate': 0.015199758878500032, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 6, 'subsample': 0.9860392895390393, 'colsample_bytree': 0.8037674261842942, 'n_estimators': 500}. Best is trial 13 with value: 0.6591067288417914.

Fold 4
Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 14:51:43,090] Trial 18 finished with value: 0.5906695993418539 and parameters: {'learning_rate': 0.04881584156743456, 'num_leaves': 60, 'max_depth': 7, 'min_child_samples': 4, 'subsample': 0.8127441066093833, 'colsample_bytree': 0.9962555082391671, 'n_estimators': 500}. Best is trial 13 with value: 0.6591067288417914.

Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:51:43,685] Trial 19 finished with value: 0.5761647900852359 and parameters: {'learning_rate': 0.006184838054948885, 'num_leaves': 40, 'max_depth': 5, 'min_child_samples': 11, 'subsample': 0.8692182447558342, 'colsample_bytree': 0.8146863418582232, 'n_estimators': 1000}. Best is trial 13 with value: 0.6591067288417914.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 14:51:44,074] Trial 20 finished with value: 0.6313126451792239 and parameters: {'learning_rate': 0.010669653870004188, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 7, 'subsample': 0.7042037754016309, 'colsample_bytree': 0.8939578976120238, 'n_estimators': 500}. Best is trial 13 with value: 0.6591067288417914.

Fold 4
Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 14:51:44,443] Trial 21 finished with value: 0.6606923348609195 and parameters: {'learning_rate': 0.01474336254464019, 'num_leaves': 40, 'max_depth': 6, 'min_child_samples': 6, 'subsample': 0.9964816945465981, 'colsample_bytree': 0.8686133786839119, 'n_estimators': 500}. Best is trial 21 with value: 0.6606923348609195.

Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:51:44,824] Trial 22 finished with value: 0.6338935401803275 and parameters: {'learning_rate': 0.01573144907684656, 'num_leaves': 40, 'max_depth': 6, 'min_child_samples': 5, 'subsample': 0.9468758380070719, 'colsample_bytree': 0.8740286729508379, 'n_estimators': 500}. Best is trial 21 with value: 0.6606923348609195.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 14:51:45,229] Trial 23 finished with value: 0.6316733050178724 and parameters: {'learning_rate': 0.007051367803739897, 'num_leaves': 40, 'max_depth': 6, 'min_child_samples': 7, 'subsample': 0.9082016958046814, 'colsample_bytree': 0.9360891224012838, 'n_estimators': 500}. Best is trial 21 with value: 0.6606923348609195.

Fold 4
Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 14:51:45,728] Trial 24 finished with value: 0.6416841458760196 and parameters: {'learning_rate': 0.009634147667187263, 'num_leaves': 40, 'max_depth': 7, 'min_child_samples': 5, 'subsample': 0.9982586995461583, 'colsample_bytree': 0.8324713153931105, 'n_estimators': 500}. Best is trial 21 with value: 0.6606923348609195.
[I 2025-09-04 14:51:45,729] A new study created in memory with name: no-name-e5444089-fe28-415a-b7c2-4dd91ca9bcd2

Fold 5

✅ LBM con TOA_3x3_depth_in_3_4 - Mejor R2: 0.66
📋 Parámetros: {'learning_rate': 0.01474336254464019, 'num_leaves': 40, 'max_depth': 6, 'min_child_samples': 6, 'subsample': 0.9964816945465981, 'colsample_bytree': 0.8686133786839119, 'n_estimators': 500}

Buscando mejores hiperparámetros para MLP con TOA_3x3_depth_in_3_4...

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 14:51:46,524] Trial 0 finished with value: 0.609090557940723 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.07924914624836353, 'learning_rate': 'constant', 'learning_rate_init': 0.0016691532818997345}. Best is trial 0 with value: 0.609090557940723.

Fold 4
Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-04 14:51:48,135] Trial 1 finished with value: 0.5425799849073025 and parameters: {'hidden_layer_sizes': '256', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 7.162111607272245e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.000885801998355323}. Best is trial 0 with value: 0.609090557940723.

Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-04 14:51:49,835] Trial 2 finished with value: 0.5065717659875378 and parameters: {'hidden_layer_sizes': '256', 'activation': 'relu', 'solver': 'sgd', 'alpha': 3.235271689200409e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0002666509833464309}. Best is trial 0 with value: 0.609090557940723.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-04 14:51:51,456] Trial 3 finished with value: 0.5947571203203572 and parameters: {'hidden_layer_sizes': '128', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.013901633506886831, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00826046736457911}. Best is trial 0 with value: 0.609090557940723.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-04 14:51:55,379] Trial 4 finished with value: 0.5490114067215544 and parameters: {'hidden_layer_sizes': '256_128', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.07978473903423465, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0060574023971701795}. Best is trial 0 with value: 0.609090557940723.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-04 14:51:56,747] Trial 5 finished with value: 0.2999786350209861 and parameters: {'hidden_layer_sizes': '128', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.009227955637296434, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00012958431690839384}. Best is trial 0 with value: 0.609090557940723.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:51:57,419] Trial 6 finished with value: 0.5206968898080482 and parameters: {'hidden_layer_sizes': '128', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.03324026434034583, 'learning_rate': 'constant', 'learning_rate_init': 0.004602145490419811}. Best is trial 0 with value: 0.609090557940723.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 14:51:58,220] Trial 7 finished with value: 0.5851099202737071 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.00026888118881872303, 'learning_rate': 'constant', 'learning_rate_init': 0.007635081321762134}. Best is trial 0 with value: 0.609090557940723.

Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:51:59,956] Trial 8 finished with value: 0.5458896343576707 and parameters: {'hidden_layer_sizes': '256_128', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.00297708904945864, 'learning_rate': 'constant', 'learning_rate_init': 0.0018766298864902483}. Best is trial 0 with value: 0.609090557940723.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:52:01,609] Trial 9 finished with value: 0.548701762009268 and parameters: {'hidden_layer_sizes': '256_128', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.00041845844328371754, 'learning_rate': 'constant', 'learning_rate_init': 0.008776291566310898}. Best is trial 0 with value: 0.609090557940723.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:52:02,547] Trial 10 finished with value: 0.6284593594584427 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0025712880712675397, 'learning_rate': 'constant', 'learning_rate_init': 0.001240739387493211}. Best is trial 10 with value: 0.6284593594584427.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:52:03,413] Trial 11 finished with value: 0.6165720476397443 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0016873060121827895, 'learning_rate': 'constant', 'learning_rate_init': 0.0010590442481567795}. Best is trial 10 with value: 0.6284593594584427.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 14:52:04,564] Trial 12 finished with value: 0.6711955342647153 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0017334416716867156, 'learning_rate': 'constant', 'learning_rate_init': 0.0005769249889113781}. Best is trial 12 with value: 0.6711955342647153.

Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 14:52:05,710] Trial 13 finished with value: 0.6672307345581006 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0034217860742433684, 'learning_rate': 'constant', 'learning_rate_init': 0.0004396584718847125}. Best is trial 12 with value: 0.6711955342647153.

Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3
Fold 4

[I 2025-09-04 14:52:07,028] Trial 14 finished with value: 0.6553204840913818 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0005143052492346392, 'learning_rate': 'constant', 'learning_rate_init': 0.00038600724212991123}. Best is trial 12 with value: 0.6711955342647153.

Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 14:52:08,175] Trial 15 finished with value: 0.6720020517227526 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.007713000032378165, 'learning_rate': 'constant', 'learning_rate_init': 0.0004289182415690576}. Best is trial 15 with value: 0.6720020517227526.

Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

[I 2025-09-04 14:52:10,218] Trial 16 finished with value: 0.6145231243511415 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.009598941759249356, 'learning_rate': 'constant', 'learning_rate_init': 0.00010361694622392736}. Best is trial 15 with value: 0.6720020517227526.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 14:52:11,282] Trial 17 finished with value: 0.6751246859378202 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 1.0185274824789504e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.0006132329575620668}. Best is trial 17 with value: 0.6751246859378202.

Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

[I 2025-09-04 14:52:12,535] Trial 18 finished with value: 0.6252608674663332 and parameters: {'hidden_layer_sizes': '256', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.00014694378381521593, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0001898483942826055}. Best is trial 17 with value: 0.6751246859378202.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:52:13,371] Trial 19 finished with value: 0.6056178585957159 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 1.0319665688595475e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.0023975741824177584}. Best is trial 17 with value: 0.6751246859378202.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 14:52:14,531] Trial 20 finished with value: 0.6760379544326066 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 1.8399498662330756e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.0005319925846193705}. Best is trial 20 with value: 0.6760379544326066.

Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 14:52:15,647] Trial 21 finished with value: 0.6639826880933568 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 1.137962828265238e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.000720965790347975}. Best is trial 20 with value: 0.6760379544326066.

Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3
Fold 4

[I 2025-09-04 14:52:17,157] Trial 22 finished with value: 0.6556554014145144 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 3.5686927059341955e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.0002907363441968331}. Best is trial 20 with value: 0.6760379544326066.

Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:52:18,394] Trial 23 finished with value: 0.6749375347456013 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 2.9377559844408608e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.0005556541504309466}. Best is trial 20 with value: 0.6760379544326066.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 14:52:19,344] Trial 24 finished with value: 0.6648565062027401 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 2.4260501602804155e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.0007573996454475217}. Best is trial 20 with value: 0.6760379544326066.
[I 2025-09-04 14:52:19,345] A new study created in memory with name: no-name-80b3c752-8829-4cf2-8a48-07ffa4c1a06c

Fold 5

✅ MLP con TOA_3x3_depth_in_3_4 - Mejor R2: 0.68
📋 Parámetros: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 1.8399498662330756e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.0005319925846193705}

Buscando mejores hiperparámetros para SVR con TOA_3x3_depth_in_3_4...

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 14:52:19,451] Trial 0 finished with value: 0.48656094337552136 and parameters: {'C': 2.7525525802207165, 'epsilon': 0.1749376505853794}. Best is trial 0 with value: 0.48656094337552136.
[I 2025-09-04 14:52:19,537] Trial 1 finished with value: 0.47544451709012836 and parameters: {'C': 1.6775578597845355, 'epsilon': 0.10687934443868721}. Best is trial 0 with value: 0.48656094337552136.
[I 2025-09-04 14:52:19,625] Trial 2 finished with value: 0.4800244266910859 and parameters: {'C': 3.7203511560845297, 'epsilon': 0.011467903438010012}. Best is trial 0 with value: 0.48656094337552136.

Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1

[I 2025-09-04 14:52:19,717] Trial 3 finished with value: 0.458629076912083 and parameters: {'C': 9.184891206688057, 'epsilon': 0.11476820116845876}. Best is trial 0 with value: 0.48656094337552136.
[I 2025-09-04 14:52:19,794] Trial 4 finished with value: 0.2857492162106925 and parameters: {'C': 0.3283598892789576, 'epsilon': 0.1870017517456954}. Best is trial 0 with value: 0.48656094337552136.

Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 14:52:19,880] Trial 5 finished with value: 0.47781064658428085 and parameters: {'C': 1.7533118594628894, 'epsilon': 0.12029400899916372}. Best is trial 0 with value: 0.48656094337552136.
[I 2025-09-04 14:52:19,960] Trial 6 finished with value: 0.4852756597568326 and parameters: {'C': 2.170616907041705, 'epsilon': 0.1981719186545555}. Best is trial 0 with value: 0.48656094337552136.
[I 2025-09-04 14:52:20,037] Trial 7 finished with value: 0.328856094636339 and parameters: {'C': 0.41984858053485746, 'epsilon': 0.19071809943541468}. Best is trial 0 with value: 0.48656094337552136.

Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2

[I 2025-09-04 14:52:20,126] Trial 8 finished with value: 0.48128615312344836 and parameters: {'C': 3.6857518296668577, 'epsilon': 0.06801529698624778}. Best is trial 0 with value: 0.48656094337552136.
[I 2025-09-04 14:52:20,209] Trial 9 finished with value: 0.3441536527711031 and parameters: {'C': 0.5138458824274608, 'epsilon': 0.06444504491195442}. Best is trial 0 with value: 0.48656094337552136.

Fold 3
Fold 4
Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 14:52:20,293] Trial 10 finished with value: 0.14682328856410454 and parameters: {'C': 0.1649320856504825, 'epsilon': 0.15257951694483374}. Best is trial 0 with value: 0.48656094337552136.
[I 2025-09-04 14:52:20,384] Trial 11 finished with value: 0.4843816892899646 and parameters: {'C': 3.966652872000574, 'epsilon': 0.15840540921205348}. Best is trial 0 with value: 0.48656094337552136.
[I 2025-09-04 14:52:20,467] Trial 12 finished with value: 0.4580481461800283 and parameters: {'C': 1.1206482631532904, 'epsilon': 0.15939545833348007}. Best is trial 0 with value: 0.48656094337552136.

Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1

[I 2025-09-04 14:52:20,556] Trial 13 finished with value: 0.4753874509548711 and parameters: {'C': 6.592860711511361, 'epsilon': 0.19451547568591376}. Best is trial 0 with value: 0.48656094337552136.
[I 2025-09-04 14:52:20,645] Trial 14 finished with value: 0.4875304139926584 and parameters: {'C': 2.2300524472066585, 'epsilon': 0.14031555174036087}. Best is trial 14 with value: 0.4875304139926584.

Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 14:52:20,731] Trial 15 finished with value: 0.42086681301923146 and parameters: {'C': 0.787201910200375, 'epsilon': 0.13926544536830152}. Best is trial 14 with value: 0.4875304139926584.
[I 2025-09-04 14:52:20,830] Trial 16 finished with value: 0.4883031454054404 and parameters: {'C': 2.4279016303695427, 'epsilon': 0.08368239687667561}. Best is trial 16 with value: 0.4883031454054404.

Fold 4
Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 14:52:20,918] Trial 17 finished with value: 0.4456176994919878 and parameters: {'C': 1.0290954454547132, 'epsilon': 0.07759459880779626}. Best is trial 16 with value: 0.4883031454054404.
[I 2025-09-04 14:52:21,005] Trial 18 finished with value: 0.05407646034274716 and parameters: {'C': 0.1036463188682594, 'epsilon': 0.08990487048908948}. Best is trial 16 with value: 0.4883031454054404.
[I 2025-09-04 14:52:21,100] Trial 19 finished with value: 0.45211872512816376 and parameters: {'C': 7.860802863969363, 'epsilon': 0.04466033108977537}. Best is trial 16 with value: 0.4883031454054404.

Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1

[I 2025-09-04 14:52:21,194] Trial 20 finished with value: 0.4713851703929174 and parameters: {'C': 5.388359120878597, 'epsilon': 0.13154838217195403}. Best is trial 16 with value: 0.4883031454054404.
[I 2025-09-04 14:52:21,294] Trial 21 finished with value: 0.4867351171629315 and parameters: {'C': 2.5270990470543833, 'epsilon': 0.1699141389158075}. Best is trial 16 with value: 0.4883031454054404.

Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2

[I 2025-09-04 14:52:21,387] Trial 22 finished with value: 0.46659772328739557 and parameters: {'C': 1.3955984549415454, 'epsilon': 0.0975773588562571}. Best is trial 16 with value: 0.4883031454054404.
[I 2025-09-04 14:52:21,477] Trial 23 finished with value: 0.4869280807970422 and parameters: {'C': 2.7478333520364835, 'epsilon': 0.13667200138620522}. Best is trial 16 with value: 0.4883031454054404.

Fold 3
Fold 4
Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 14:52:21,568] Trial 24 finished with value: 0.47480340263947884 and parameters: {'C': 5.0650412820711646, 'epsilon': 0.13534217629696124}. Best is trial 16 with value: 0.4883031454054404.
[I 2025-09-04 14:52:21,569] A new study created in memory with name: no-name-fdc8cafc-7699-4aa9-be07-03d2271b0ffc
[I 2025-09-04 14:52:21,638] Trial 0 finished with value: 0.6067971370091596 and parameters: {'n_neighbors': 9, 'leaf_size': 16}. Best is trial 0 with value: 0.6067971370091596.
[I 2025-09-04 14:52:21,702] Trial 1 finished with value: 0.5878749364366489 and parameters: {'n_neighbors': 3, 'leaf_size': 19}. Best is trial 0 with value: 0.6067971370091596.

Fold 5

✅ SVR con TOA_3x3_depth_in_3_4 - Mejor R2: 0.49
📋 Parámetros: {'C': 2.4279016303695427, 'epsilon': 0.08368239687667561}

Buscando mejores hiperparámetros para KNN con TOA_3x3_depth_in_3_4...

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 14:52:21,766] Trial 2 finished with value: 0.6052514768075414 and parameters: {'n_neighbors': 4, 'leaf_size': 13}. Best is trial 0 with value: 0.6067971370091596.
[I 2025-09-04 14:52:21,838] Trial 3 finished with value: 0.6118616135853638 and parameters: {'n_neighbors': 10, 'leaf_size': 37}. Best is trial 3 with value: 0.6118616135853638.
[I 2025-09-04 14:52:21,901] Trial 4 finished with value: 0.6155868847186117 and parameters: {'n_neighbors': 5, 'leaf_size': 34}. Best is trial 4 with value: 0.6155868847186117.

Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:52:21,967] Trial 5 finished with value: 0.6159114095417476 and parameters: {'n_neighbors': 8, 'leaf_size': 31}. Best is trial 5 with value: 0.6159114095417476.
[I 2025-09-04 14:52:22,037] Trial 6 finished with value: 0.6168853752426722 and parameters: {'n_neighbors': 6, 'leaf_size': 40}. Best is trial 6 with value: 0.6168853752426722.
[I 2025-09-04 14:52:22,102] Trial 7 finished with value: 0.5878749364366489 and parameters: {'n_neighbors': 3, 'leaf_size': 17}. Best is trial 6 with value: 0.6168853752426722.
[I 2025-09-04 14:52:22,166] Trial 8 finished with value: 0.6155868847186117 and parameters: {'n_neighbors': 5, 'leaf_size': 39}. Best is trial 6 with value: 0.6168853752426722.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1

[I 2025-09-04 14:52:22,233] Trial 9 finished with value: 0.6067971370091596 and parameters: {'n_neighbors': 9, 'leaf_size': 26}. Best is trial 6 with value: 0.6168853752426722.
[I 2025-09-04 14:52:22,305] Trial 10 finished with value: 0.6146209662765738 and parameters: {'n_neighbors': 7, 'leaf_size': 27}. Best is trial 6 with value: 0.6168853752426722.
[I 2025-09-04 14:52:22,377] Trial 11 finished with value: 0.6146209662765738 and parameters: {'n_neighbors': 7, 'leaf_size': 32}. Best is trial 6 with value: 0.6168853752426722.

Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1

[I 2025-09-04 14:52:22,450] Trial 12 finished with value: 0.6159114095417476 and parameters: {'n_neighbors': 8, 'leaf_size': 30}. Best is trial 6 with value: 0.6168853752426722.
[I 2025-09-04 14:52:22,526] Trial 13 finished with value: 0.6168853752426722 and parameters: {'n_neighbors': 6, 'leaf_size': 40}. Best is trial 6 with value: 0.6168853752426722.
[I 2025-09-04 14:52:22,596] Trial 14 finished with value: 0.6168853752426722 and parameters: {'n_neighbors': 6, 'leaf_size': 40}. Best is trial 6 with value: 0.6168853752426722.

Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===

[I 2025-09-04 14:52:22,673] Trial 15 finished with value: 0.6168853752426722 and parameters: {'n_neighbors': 6, 'leaf_size': 36}. Best is trial 6 with value: 0.6168853752426722.
[I 2025-09-04 14:52:22,749] Trial 16 finished with value: 0.6155868847186117 and parameters: {'n_neighbors': 5, 'leaf_size': 22}. Best is trial 6 with value: 0.6168853752426722.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 14:52:22,827] Trial 17 finished with value: 0.6168853752426722 and parameters: {'n_neighbors': 6, 'leaf_size': 40}. Best is trial 6 with value: 0.6168853752426722.
[I 2025-09-04 14:52:22,904] Trial 18 finished with value: 0.6052514768075414 and parameters: {'n_neighbors': 4, 'leaf_size': 10}. Best is trial 6 with value: 0.6168853752426722.
[I 2025-09-04 14:52:22,975] Trial 19 finished with value: 0.6146209662765738 and parameters: {'n_neighbors': 7, 'leaf_size': 35}. Best is trial 6 with value: 0.6168853752426722.

Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 14:52:23,049] Trial 20 finished with value: 0.6159114095417476 and parameters: {'n_neighbors': 8, 'leaf_size': 29}. Best is trial 6 with value: 0.6168853752426722.
[I 2025-09-04 14:52:23,124] Trial 21 finished with value: 0.6168853752426722 and parameters: {'n_neighbors': 6, 'leaf_size': 40}. Best is trial 6 with value: 0.6168853752426722.
[I 2025-09-04 14:52:23,196] Trial 22 finished with value: 0.6168853752426722 and parameters: {'n_neighbors': 6, 'leaf_size': 37}. Best is trial 6 with value: 0.6168853752426722.

Fold 4
Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2

[I 2025-09-04 14:52:23,272] Trial 23 finished with value: 0.6155868847186117 and parameters: {'n_neighbors': 5, 'leaf_size': 33}. Best is trial 6 with value: 0.6168853752426722.
[I 2025-09-04 14:52:23,344] Trial 24 finished with value: 0.6052514768075414 and parameters: {'n_neighbors': 4, 'leaf_size': 38}. Best is trial 6 with value: 0.6168853752426722.
[I 2025-09-04 14:52:23,345] A new study created in memory with name: no-name-2c507e51-9f77-4a5c-9cf9-273920b8e487
[I 2025-09-04 14:52:23,427] Trial 0 finished with value: 0.4003005633931548 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 0 with value: 0.4003005633931548.

Fold 3
Fold 4
Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

✅ KNN con TOA_3x3_depth_in_3_4 - Mejor R2: 0.62
📋 Parámetros: {'n_neighbors': 6, 'leaf_size': 40}

Buscando mejores hiperparámetros para LR con TOA_3x3_depth_in_3_4...

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1

[I 2025-09-04 14:52:23,576] Trial 1 finished with value: 0.4003005633931548 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 0 with value: 0.4003005633931548.

Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:52:23,661] Trial 2 finished with value: 0.3207149917432718 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: 0.4003005633931548.
[I 2025-09-04 14:52:23,729] Trial 3 finished with value: 0.3207149917432718 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: 0.4003005633931548.
[I 2025-09-04 14:52:23,819] Trial 4 finished with value: 0.40030056339319364 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 4 with value: 0.40030056339319364.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 14:52:23,913] Trial 5 finished with value: 0.32033389826347425 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 4 with value: 0.40030056339319364.
[I 2025-09-04 14:52:23,979] Trial 6 finished with value: 0.3207149917432718 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 4 with value: 0.40030056339319364.
[I 2025-09-04 14:52:24,041] Trial 7 finished with value: 0.32033389826347425 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 4 with value: 0.40030056339319364.

Fold 4
Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 14:52:24,125] Trial 8 finished with value: 0.4003005633931548 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 4 with value: 0.40030056339319364.
[I 2025-09-04 14:52:24,218] Trial 9 finished with value: 0.40030056339319364 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 4 with value: 0.40030056339319364.
[I 2025-09-04 14:52:24,308] Trial 10 finished with value: 0.40030056339319364 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 4 with value: 0.40030056339319364.

Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===

[I 2025-09-04 14:52:24,400] Trial 11 finished with value: 0.40030056339319364 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 4 with value: 0.40030056339319364.
[I 2025-09-04 14:52:24,492] Trial 12 finished with value: 0.40030056339319364 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 4 with value: 0.40030056339319364.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2

[I 2025-09-04 14:52:24,584] Trial 13 finished with value: 0.40030056339319364 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 4 with value: 0.40030056339319364.
[I 2025-09-04 14:52:24,675] Trial 14 finished with value: 0.40030056339319364 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 4 with value: 0.40030056339319364.

Fold 3
Fold 4
Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 14:52:24,770] Trial 15 finished with value: 0.40030056339319364 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 4 with value: 0.40030056339319364.
[I 2025-09-04 14:52:24,867] Trial 16 finished with value: 0.40030056339319364 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 4 with value: 0.40030056339319364.

Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:52:24,957] Trial 17 finished with value: 0.40030056339319364 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 4 with value: 0.40030056339319364.
[I 2025-09-04 14:52:25,048] Trial 18 finished with value: 0.40030056339319364 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 4 with value: 0.40030056339319364.
[I 2025-09-04 14:52:25,137] Trial 19 finished with value: 0.40030056339319364 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 4 with value: 0.40030056339319364.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1

[I 2025-09-04 14:52:25,289] Trial 20 finished with value: 0.40030056339319364 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 4 with value: 0.40030056339319364.

Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 14:52:25,395] Trial 21 finished with value: 0.40030056339319364 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 4 with value: 0.40030056339319364.
[I 2025-09-04 14:52:25,500] Trial 22 finished with value: 0.40030056339319364 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 4 with value: 0.40030056339319364.

Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:52:25,589] Trial 23 finished with value: 0.40030056339319364 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 4 with value: 0.40030056339319364.
[I 2025-09-04 14:52:25,682] Trial 24 finished with value: 0.40030056339319364 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 4 with value: 0.40030056339319364.
[I 2025-09-04 14:52:25,684] A new study created in memory with name: no-name-8a8411f3-8e5b-4571-8b00-f89dd4c2dc52

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

✅ LR con TOA_3x3_depth_in_3_4 - Mejor R2: 0.40
📋 Parámetros: {'fit_intercept': True, 'positive': False}

Buscando mejores hiperparámetros para RF con TOA_3x3_depth_in_3_4...

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:52:28,301] Trial 0 finished with value: 0.6560891182163777 and parameters: {'n_estimators': 100, 'max_depth': 15, 'min_samples_split': 5, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 0 with value: 0.6560891182163777.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:52:38,807] Trial 1 finished with value: 0.635956179308405 and parameters: {'n_estimators': 500, 'max_depth': 9, 'min_samples_split': 3, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 0 with value: 0.6560891182163777.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:52:49,771] Trial 2 finished with value: 0.6366294861357393 and parameters: {'n_estimators': 500, 'max_depth': 12, 'min_samples_split': 5, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 0 with value: 0.6560891182163777.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:52:53,256] Trial 3 finished with value: 0.6201390202256112 and parameters: {'n_estimators': 100, 'max_depth': 13, 'min_samples_split': 10, 'min_samples_leaf': 5, 'bootstrap': False}. Best is trial 0 with value: 0.6560891182163777.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:52:56,927] Trial 4 finished with value: 0.662119218134817 and parameters: {'n_estimators': 100, 'max_depth': 14, 'min_samples_split': 5, 'min_samples_leaf': 4, 'bootstrap': False}. Best is trial 4 with value: 0.662119218134817.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:53:07,022] Trial 5 finished with value: 0.6341363585548481 and parameters: {'n_estimators': 500, 'max_depth': 8, 'min_samples_split': 6, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 4 with value: 0.662119218134817.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:53:10,349] Trial 6 finished with value: 0.6248051803298513 and parameters: {'n_estimators': 100, 'max_depth': 10, 'min_samples_split': 4, 'min_samples_leaf': 5, 'bootstrap': False}. Best is trial 4 with value: 0.662119218134817.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:53:13,037] Trial 7 finished with value: 0.4749457404950921 and parameters: {'n_estimators': 100, 'max_depth': 6, 'min_samples_split': 10, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 4 with value: 0.662119218134817.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:53:33,311] Trial 8 finished with value: 0.6055345636581372 and parameters: {'n_estimators': 500, 'max_depth': 12, 'min_samples_split': 2, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 4 with value: 0.662119218134817.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:53:45,449] Trial 9 finished with value: 0.6379686508687317 and parameters: {'n_estimators': 500, 'max_depth': 14, 'min_samples_split': 9, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 4 with value: 0.662119218134817.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:53:53,262] Trial 10 finished with value: 0.6596645415380726 and parameters: {'n_estimators': 300, 'max_depth': 6, 'min_samples_split': 8, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 4 with value: 0.662119218134817.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:54:00,047] Trial 11 finished with value: 0.6395498718142625 and parameters: {'n_estimators': 300, 'max_depth': 5, 'min_samples_split': 8, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 4 with value: 0.662119218134817.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:54:08,776] Trial 12 finished with value: 0.6707562453653445 and parameters: {'n_estimators': 300, 'max_depth': 7, 'min_samples_split': 7, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 12 with value: 0.6707562453653445.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:54:17,353] Trial 13 finished with value: 0.6582589804849963 and parameters: {'n_estimators': 300, 'max_depth': 7, 'min_samples_split': 7, 'min_samples_leaf': 4, 'bootstrap': False}. Best is trial 12 with value: 0.6707562453653445.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:54:28,444] Trial 14 finished with value: 0.6792850844232076 and parameters: {'n_estimators': 300, 'max_depth': 11, 'min_samples_split': 6, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 14 with value: 0.6792850844232076.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:54:39,118] Trial 15 finished with value: 0.6722482478698235 and parameters: {'n_estimators': 300, 'max_depth': 10, 'min_samples_split': 7, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 14 with value: 0.6792850844232076.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:54:51,247] Trial 16 finished with value: 0.49573160402370164 and parameters: {'n_estimators': 300, 'max_depth': 11, 'min_samples_split': 7, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 14 with value: 0.6792850844232076.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:55:02,375] Trial 17 finished with value: 0.6441686466203738 and parameters: {'n_estimators': 300, 'max_depth': 10, 'min_samples_split': 6, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 14 with value: 0.6792850844232076.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:55:12,478] Trial 18 finished with value: 0.6510591907035235 and parameters: {'n_estimators': 300, 'max_depth': 9, 'min_samples_split': 8, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 14 with value: 0.6792850844232076.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:55:24,248] Trial 19 finished with value: 0.6060836457229541 and parameters: {'n_estimators': 300, 'max_depth': 11, 'min_samples_split': 4, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 14 with value: 0.6792850844232076.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:55:35,344] Trial 20 finished with value: 0.6792850844232076 and parameters: {'n_estimators': 300, 'max_depth': 11, 'min_samples_split': 6, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 14 with value: 0.6792850844232076.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:55:46,458] Trial 21 finished with value: 0.6792850844232076 and parameters: {'n_estimators': 300, 'max_depth': 11, 'min_samples_split': 6, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 14 with value: 0.6792850844232076.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:55:57,832] Trial 22 finished with value: 0.6806290768688597 and parameters: {'n_estimators': 300, 'max_depth': 12, 'min_samples_split': 6, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 22 with value: 0.6806290768688597.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:56:09,190] Trial 23 finished with value: 0.6806290768688597 and parameters: {'n_estimators': 300, 'max_depth': 12, 'min_samples_split': 4, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 22 with value: 0.6806290768688597.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:56:21,598] Trial 24 finished with value: 0.6101579914939911 and parameters: {'n_estimators': 300, 'max_depth': 13, 'min_samples_split': 4, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 22 with value: 0.6806290768688597.
[I 2025-09-04 14:56:21,599] A new study created in memory with name: no-name-fd110cea-dcda-4088-b9fe-f1384fc653e7

✅ RF con TOA_3x3_depth_in_3_4 - Mejor R2: 0.68
📋 Parámetros: {'n_estimators': 300, 'max_depth': 12, 'min_samples_split': 6, 'min_samples_leaf': 3, 'bootstrap': False}

Buscando mejores hiperparámetros para CAT con TOA_3x3_depth_in_3_4...

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:56:52,148] Trial 0 finished with value: 0.6062754201346299 and parameters: {'iterations': 2000, 'learning_rate': 0.03499532808356723, 'depth': 7, 'l2_leaf_reg': 3.415202698789987}. Best is trial 0 with value: 0.6062754201346299.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 14:57:38,547] Trial 1 finished with value: 0.6093359053148886 and parameters: {'iterations': 500, 'learning_rate': 0.03602902815966305, 'depth': 9, 'l2_leaf_reg': 1.0903048845949372}. Best is trial 1 with value: 0.6093359053148886.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:00:44,225] Trial 2 finished with value: 0.5879620168550391 and parameters: {'iterations': 2000, 'learning_rate': 0.02121652458899668, 'depth': 9, 'l2_leaf_reg': 4.5642440837437235}. Best is trial 1 with value: 0.6093359053148886.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:00:46,607] Trial 3 finished with value: 0.5676757129078953 and parameters: {'iterations': 500, 'learning_rate': 0.06676162983766758, 'depth': 5, 'l2_leaf_reg': 4.919609740681005}. Best is trial 1 with value: 0.6093359053148886.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:00:52,447] Trial 4 finished with value: 0.5685054655630346 and parameters: {'iterations': 2000, 'learning_rate': 0.011147184931219009, 'depth': 4, 'l2_leaf_reg': 2.728815923484885}. Best is trial 1 with value: 0.6093359053148886.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:02:23,992] Trial 5 finished with value: 0.5886991322457984 and parameters: {'iterations': 1000, 'learning_rate': 0.014615948492433641, 'depth': 9, 'l2_leaf_reg': 4.318434272336921}. Best is trial 1 with value: 0.6093359053148886.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:02:26,219] Trial 6 finished with value: 0.5515690222863574 and parameters: {'iterations': 500, 'learning_rate': 0.012913555170544606, 'depth': 5, 'l2_leaf_reg': 5.3319792387779}. Best is trial 1 with value: 0.6093359053148886.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:05:16,558] Trial 7 finished with value: 0.5926151584534736 and parameters: {'iterations': 1000, 'learning_rate': 0.03162409202668339, 'depth': 10, 'l2_leaf_reg': 4.409220719143632}. Best is trial 1 with value: 0.6093359053148886.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:05:47,280] Trial 8 finished with value: 0.606153682614418 and parameters: {'iterations': 2000, 'learning_rate': 0.025480802833381895, 'depth': 7, 'l2_leaf_reg': 3.80237074231122}. Best is trial 1 with value: 0.6093359053148886.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:06:02,700] Trial 9 finished with value: 0.6045937301784234 and parameters: {'iterations': 1000, 'learning_rate': 0.019793402463105323, 'depth': 7, 'l2_leaf_reg': 3.129325744193516}. Best is trial 1 with value: 0.6093359053148886.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:06:49,218] Trial 10 finished with value: 0.6295511161905696 and parameters: {'iterations': 500, 'learning_rate': 0.05232742477450515, 'depth': 9, 'l2_leaf_reg': 1.0235346499052462}. Best is trial 10 with value: 0.6295511161905696.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:07:35,659] Trial 11 finished with value: 0.6292350619223392 and parameters: {'iterations': 500, 'learning_rate': 0.053168630505682504, 'depth': 9, 'l2_leaf_reg': 1.055324219046876}. Best is trial 10 with value: 0.6295511161905696.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:09:01,634] Trial 12 finished with value: 0.6035327803319477 and parameters: {'iterations': 500, 'learning_rate': 0.06064213975014318, 'depth': 10, 'l2_leaf_reg': 1.0537157515185318}. Best is trial 10 with value: 0.6295511161905696.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:09:21,757] Trial 13 finished with value: 0.6092067342458491 and parameters: {'iterations': 500, 'learning_rate': 0.048444847925258536, 'depth': 8, 'l2_leaf_reg': 2.3593476707233525}. Best is trial 10 with value: 0.6295511161905696.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:09:41,990] Trial 14 finished with value: 0.6062552462914537 and parameters: {'iterations': 500, 'learning_rate': 0.047918255550871515, 'depth': 8, 'l2_leaf_reg': 2.1075455525984452}. Best is trial 10 with value: 0.6295511161905696.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:10:02,098] Trial 15 finished with value: 0.6113262794625699 and parameters: {'iterations': 500, 'learning_rate': 0.04772931719074598, 'depth': 8, 'l2_leaf_reg': 1.7061538646734515}. Best is trial 10 with value: 0.6295511161905696.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:11:27,769] Trial 16 finished with value: 0.6072931662263203 and parameters: {'iterations': 500, 'learning_rate': 0.07294071067081433, 'depth': 10, 'l2_leaf_reg': 1.6724899860399418}. Best is trial 10 with value: 0.6295511161905696.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:11:31,044] Trial 17 finished with value: 0.5925806118188743 and parameters: {'iterations': 500, 'learning_rate': 0.05566718840063277, 'depth': 6, 'l2_leaf_reg': 1.6048671541031823}. Best is trial 10 with value: 0.6295511161905696.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:12:17,132] Trial 18 finished with value: 0.6018082130684026 and parameters: {'iterations': 500, 'learning_rate': 0.0427968117644292, 'depth': 9, 'l2_leaf_reg': 2.6189075435953963}. Best is trial 10 with value: 0.6295511161905696.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:12:57,285] Trial 19 finished with value: 0.6126918964721498 and parameters: {'iterations': 1000, 'learning_rate': 0.07864766551235358, 'depth': 8, 'l2_leaf_reg': 1.0362562155399428}. Best is trial 10 with value: 0.6295511161905696.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:14:22,423] Trial 20 finished with value: 0.600787132783234 and parameters: {'iterations': 500, 'learning_rate': 0.040130247397453835, 'depth': 10, 'l2_leaf_reg': 1.9809384940431725}. Best is trial 10 with value: 0.6295511161905696.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:15:02,705] Trial 21 finished with value: 0.6043830681990379 and parameters: {'iterations': 1000, 'learning_rate': 0.07414856695458572, 'depth': 8, 'l2_leaf_reg': 1.0716758244883628}. Best is trial 10 with value: 0.6295511161905696.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:16:35,753] Trial 22 finished with value: 0.6162729654973021 and parameters: {'iterations': 1000, 'learning_rate': 0.07991915323577005, 'depth': 9, 'l2_leaf_reg': 1.4120711093117673}. Best is trial 10 with value: 0.6295511161905696.
[I 2025-09-04 15:16:35,754] A new study created in memory with name: no-name-46f03b30-db50-4822-811d-6699c0393ddb
[I 2025-09-04 15:16:35,860] Trial 0 finished with value: 0.44654301007870933 and parameters: {'alpha': 0.05501685845554097, 'l1_ratio': 0.35481355700208606}. Best is trial 0 with value: 0.44654301007870933.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.660e+01, tolerance: 4.075e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.587e+01, tolerance: 4.583e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.906e+01, tolerance: 3.985e-02
  model = cd_fast.enet_coordinate_descent(

✅ CAT con TOA_3x3_depth_in_3_4 - Mejor R2: 0.63
📋 Parámetros: {'iterations': 500, 'learning_rate': 0.05232742477450515, 'depth': 9, 'l2_leaf_reg': 1.0235346499052462}

Buscando mejores hiperparámetros para ELN con TOA_3x3_depth_in_3_4...

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.566e+01, tolerance: 5.497e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.950e+01, tolerance: 4.044e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 15:16:35,998] Trial 1 finished with value: 0.4574418185873603 and parameters: {'alpha': 0.0044498701467410315, 'l1_ratio': 0.09858908277662592}. Best is trial 1 with value: 0.4574418185873603.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.025e+02, tolerance: 4.075e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.197e+02, tolerance: 4.583e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.393e+01, tolerance: 3.985e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.345e+02, tolerance: 5.497e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.092e+02, tolerance: 4.044e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 15:16:36,134] Trial 2 finished with value: 0.4590166256177147 and parameters: {'alpha': 0.0018598586071572, 'l1_ratio': 0.03847130886417838}. Best is trial 2 with value: 0.4590166256177147.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.704e+01, tolerance: 4.075e-02
  model = cd_fast.enet_coordinate_descent(

Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.991e+01, tolerance: 4.583e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.887e+01, tolerance: 3.985e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.153e+02, tolerance: 5.497e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.002e+02, tolerance: 4.044e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 15:16:36,277] Trial 3 finished with value: 0.46512652119032816 and parameters: {'alpha': 0.0001108942740077356, 'l1_ratio': 0.5229778433501852}. Best is trial 3 with value: 0.46512652119032816.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.732e+00, tolerance: 4.075e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.522e+00, tolerance: 4.583e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.918e+00, tolerance: 3.985e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.219e+00, tolerance: 5.497e-02
  model = cd_fast.enet_coordinate_descent(

Fold 3
Fold 4
Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.328e+00, tolerance: 4.044e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 15:16:36,397] Trial 4 finished with value: 0.4344413454789421 and parameters: {'alpha': 0.004120693236522502, 'l1_ratio': 0.7770052520205538}. Best is trial 3 with value: 0.46512652119032816.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.594e+01, tolerance: 4.075e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.054e+01, tolerance: 4.583e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.704e+01, tolerance: 3.985e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.037e+02, tolerance: 5.497e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.716e+01, tolerance: 4.044e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 15:16:36,554] Trial 5 finished with value: 0.46404645721510596 and parameters: {'alpha': 0.00028523004265682385, 'l1_ratio': 0.5504053463918211}. Best is trial 3 with value: 0.46512652119032816.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.263e+00, tolerance: 4.075e-02
  model = cd_fast.enet_coordinate_descent(

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.968e+00, tolerance: 4.583e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.366e+01, tolerance: 3.985e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.509e+00, tolerance: 5.497e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.671e+00, tolerance: 4.044e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 15:16:36,731] Trial 6 finished with value: 0.4522875651608713 and parameters: {'alpha': 0.010852360806396797, 'l1_ratio': 0.1792438280872306}. Best is trial 3 with value: 0.46512652119032816.

Fold 3
Fold 4
Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 15:16:36,834] Trial 7 finished with value: 0.3401196318408798 and parameters: {'alpha': 0.1631837700370098, 'l1_ratio': 0.6788041897362563}. Best is trial 3 with value: 0.46512652119032816.
[I 2025-09-04 15:16:36,937] Trial 8 finished with value: 0.3918266192220725 and parameters: {'alpha': 0.31042891404698447, 'l1_ratio': 0.14445240454803487}. Best is trial 3 with value: 0.46512652119032816.

Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:16:37,023] Trial 9 finished with value: 0.3003681017261769 and parameters: {'alpha': 0.24291741626097985, 'l1_ratio': 0.7301779839923669}. Best is trial 3 with value: 0.46512652119032816.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.077e+01, tolerance: 4.075e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.513e+01, tolerance: 4.583e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.503e+01, tolerance: 3.985e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.001e+02, tolerance: 5.497e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.860e+01, tolerance: 4.044e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 15:16:37,170] Trial 10 finished with value: 0.4665132936231794 and parameters: {'alpha': 0.00016713575052454367, 'l1_ratio': 0.9645333441761587}. Best is trial 10 with value: 0.4665132936231794.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.183e+01, tolerance: 4.075e-02
  model = cd_fast.enet_coordinate_descent(

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.581e+01, tolerance: 4.583e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.576e+01, tolerance: 3.985e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.009e+02, tolerance: 5.497e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.946e+01, tolerance: 4.044e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 15:16:37,354] Trial 11 finished with value: 0.4664239910046488 and parameters: {'alpha': 0.00016347034950284017, 'l1_ratio': 0.9406007828571993}. Best is trial 10 with value: 0.4665132936231794.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.068e+01, tolerance: 4.075e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.943e+01, tolerance: 4.583e-02
  model = cd_fast.enet_coordinate_descent(

Fold 3
Fold 4
Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.744e+01, tolerance: 3.985e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.837e+01, tolerance: 5.497e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.462e+01, tolerance: 4.044e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 15:16:37,496] Trial 12 finished with value: 0.4660705324618015 and parameters: {'alpha': 0.0005368206678857875, 'l1_ratio': 0.9911210183504343}. Best is trial 10 with value: 0.4665132936231794.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.864e+01, tolerance: 4.075e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.177e+01, tolerance: 4.583e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.049e+01, tolerance: 3.985e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.066e+02, tolerance: 5.497e-02
  model = cd_fast.enet_coordinate_descent(

Fold 4
Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.413e+01, tolerance: 4.044e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 15:16:37,647] Trial 13 finished with value: 0.4661673478625378 and parameters: {'alpha': 0.00011823548375937393, 'l1_ratio': 0.9471888470546328}. Best is trial 10 with value: 0.4665132936231794.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.833e+01, tolerance: 4.075e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.570e+01, tolerance: 4.583e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.487e+01, tolerance: 3.985e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.744e+01, tolerance: 5.497e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.541e+01, tolerance: 4.044e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 15:16:37,790] Trial 14 finished with value: 0.4629851002840436 and parameters: {'alpha': 0.000740871834923357, 'l1_ratio': 0.877405710553245}. Best is trial 10 with value: 0.4665132936231794.

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 15:16:37,908] Trial 15 finished with value: 0.4584719653949506 and parameters: {'alpha': 0.0243539172009184, 'l1_ratio': 0.8394437563188815}. Best is trial 10 with value: 0.4665132936231794.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.826e+01, tolerance: 4.075e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.755e+01, tolerance: 4.583e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.709e+01, tolerance: 3.985e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.029e+01, tolerance: 5.497e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.668e+01, tolerance: 4.044e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 15:16:38,049] Trial 16 finished with value: 0.4577022627825911 and parameters: {'alpha': 0.0013455660558679078, 'l1_ratio': 0.636725808920682}. Best is trial 10 with value: 0.4665132936231794.

Fold 4
Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.525e+01, tolerance: 4.075e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.543e+01, tolerance: 4.583e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.704e+01, tolerance: 3.985e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.136e+02, tolerance: 5.497e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.770e+01, tolerance: 4.044e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 15:16:38,210] Trial 17 finished with value: 0.4638228617582265 and parameters: {'alpha': 0.0002389569266694533, 'l1_ratio': 0.3448335052216488}. Best is trial 10 with value: 0.4665132936231794.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.969e+01, tolerance: 4.075e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.941e+01, tolerance: 4.583e-02
  model = cd_fast.enet_coordinate_descent(

Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.407e+01, tolerance: 3.985e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.860e+01, tolerance: 5.497e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.241e+01, tolerance: 4.044e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 15:16:38,368] Trial 18 finished with value: 0.46541784769599437 and parameters: {'alpha': 0.00038136047086117494, 'l1_ratio': 0.8703225495969537}. Best is trial 10 with value: 0.4665132936231794.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.782e+01, tolerance: 4.075e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.795e+01, tolerance: 4.583e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.904e+01, tolerance: 3.985e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.376e+01, tolerance: 5.497e-02
  model = cd_fast.enet_coordinate_descent(

Fold 4
Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.322e+01, tolerance: 4.044e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 15:16:38,510] Trial 19 finished with value: 0.4589459235489761 and parameters: {'alpha': 0.0015626801107585266, 'l1_ratio': 0.37715930541856213}. Best is trial 10 with value: 0.4665132936231794.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.808e+01, tolerance: 4.075e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.323e+01, tolerance: 4.583e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.352e+01, tolerance: 3.985e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.849e+01, tolerance: 5.497e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.651e+01, tolerance: 4.044e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 15:16:38,664] Trial 20 finished with value: 0.46657951176874213 and parameters: {'alpha': 0.00018219071583212146, 'l1_ratio': 0.9794021781112037}. Best is trial 20 with value: 0.46657951176874213.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.653e+01, tolerance: 4.075e-02
  model = cd_fast.enet_coordinate_descent(

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.032e+01, tolerance: 4.583e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.864e+01, tolerance: 3.985e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.046e+02, tolerance: 5.497e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.273e+01, tolerance: 4.044e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 15:16:38,824] Trial 21 finished with value: 0.46641793673660337 and parameters: {'alpha': 0.00012629201797412045, 'l1_ratio': 0.9889149986077752}. Best is trial 20 with value: 0.46657951176874213.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.973e+01, tolerance: 4.075e-02
  model = cd_fast.enet_coordinate_descent(

Fold 3
Fold 4
Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.775e+01, tolerance: 4.583e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.625e+01, tolerance: 3.985e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.909e+01, tolerance: 5.497e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.635e+01, tolerance: 4.044e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 15:16:39,007] Trial 22 finished with value: 0.4627981514160282 and parameters: {'alpha': 0.0007445659510276386, 'l1_ratio': 0.8187984542158868}. Best is trial 20 with value: 0.46657951176874213.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.494e+01, tolerance: 4.075e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.287e+01, tolerance: 4.583e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.914e+01, tolerance: 3.985e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.452e+01, tolerance: 5.497e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.882e+01, tolerance: 4.044e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 15:16:39,149] Trial 23 finished with value: 0.46576676026330766 and parameters: {'alpha': 0.0002626203215325692, 'l1_ratio': 0.8908702410274737}. Best is trial 20 with value: 0.46657951176874213.

Fold 4
Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_3x3_depth_in_3_4 ===

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.294e+01, tolerance: 4.075e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.388e+01, tolerance: 4.583e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.678e+01, tolerance: 3.985e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.025e+02, tolerance: 5.497e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.975e+01, tolerance: 4.044e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 15:16:39,299] Trial 24 finished with value: 0.4655522334930221 and parameters: {'alpha': 0.0001992383605030144, 'l1_ratio': 0.7465031426671673}. Best is trial 20 with value: 0.46657951176874213.
[I 2025-09-04 15:16:39,301] A new study created in memory with name: no-name-4e7e5754-be2e-4f87-9cfd-1f5004d8034c

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

✅ ELN con TOA_3x3_depth_in_3_4 - Mejor R2: 0.47
📋 Parámetros: {'alpha': 0.00018219071583212146, 'l1_ratio': 0.9794021781112037}

Buscando mejores hiperparámetros para XGB con TOA_5x5_depth_in_3_4...

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:16:41,513] Trial 0 finished with value: 0.5495062732815241 and parameters: {'n_estimators': 500, 'learning_rate': 0.024363873758536447, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.7789545556009773, 'colsample_bytree': 0.6060117460550928}. Best is trial 0 with value: 0.5495062732815241.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:16:54,006] Trial 1 finished with value: 0.47734522646811217 and parameters: {'n_estimators': 2000, 'learning_rate': 0.01357212554836877, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.6576199438621543, 'colsample_bytree': 0.7338262493443032}. Best is trial 0 with value: 0.5495062732815241.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:16:58,909] Trial 2 finished with value: 0.5410043610200435 and parameters: {'n_estimators': 1000, 'learning_rate': 0.02861485962239398, 'max_depth': 6, 'min_child_weight': 1, 'subsample': 0.8816151270070449, 'colsample_bytree': 0.6001703478011794}. Best is trial 0 with value: 0.5495062732815241.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:17:02,618] Trial 3 finished with value: 0.5602990915753869 and parameters: {'n_estimators': 500, 'learning_rate': 0.012975553419066572, 'max_depth': 8, 'min_child_weight': 2, 'subsample': 0.8276637374724647, 'colsample_bytree': 0.8893365849627617}. Best is trial 3 with value: 0.5602990915753869.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:17:05,227] Trial 4 finished with value: 0.5515263100820196 and parameters: {'n_estimators': 500, 'learning_rate': 0.029618022902871764, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.7777127950518733, 'colsample_bytree': 0.884622641832854}. Best is trial 3 with value: 0.5602990915753869.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:17:10,516] Trial 5 finished with value: 0.5418806981558041 and parameters: {'n_estimators': 1000, 'learning_rate': 0.013828664738843886, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.8040418591232543, 'colsample_bytree': 0.9469301021595043}. Best is trial 3 with value: 0.5602990915753869.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:17:20,271] Trial 6 finished with value: 0.5733851004628336 and parameters: {'n_estimators': 2000, 'learning_rate': 0.03497441235729116, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.6699500063172106, 'colsample_bytree': 0.8580620098096627}. Best is trial 6 with value: 0.5733851004628336.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:17:22,441] Trial 7 finished with value: 0.5915131545964909 and parameters: {'n_estimators': 500, 'learning_rate': 0.029435123062850226, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.7120302637499668, 'colsample_bytree': 0.6114028489663821}. Best is trial 7 with value: 0.5915131545964909.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:17:24,392] Trial 8 finished with value: 0.5412152589421078 and parameters: {'n_estimators': 500, 'learning_rate': 0.02418027216522231, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.9731651694463008, 'colsample_bytree': 0.6905788099574365}. Best is trial 7 with value: 0.5915131545964909.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:17:30,016] Trial 9 finished with value: 0.5545151860132091 and parameters: {'n_estimators': 1000, 'learning_rate': 0.02954401062032281, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.9776472124420494, 'colsample_bytree': 0.8802376069599032}. Best is trial 7 with value: 0.5915131545964909.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:17:31,980] Trial 10 finished with value: 0.5878714496246992 and parameters: {'n_estimators': 500, 'learning_rate': 0.006021568206099102, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.6047157600689461, 'colsample_bytree': 0.7408209784289683}. Best is trial 7 with value: 0.5915131545964909.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:17:33,959] Trial 11 finished with value: 0.5815609450843011 and parameters: {'n_estimators': 500, 'learning_rate': 0.005286525675844326, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.6144950191696563, 'colsample_bytree': 0.741529887640455}. Best is trial 7 with value: 0.5915131545964909.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:17:35,909] Trial 12 finished with value: 0.6258079409205488 and parameters: {'n_estimators': 500, 'learning_rate': 0.04971395727107934, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.7076482686020784, 'colsample_bytree': 0.6689034611948881}. Best is trial 12 with value: 0.6258079409205488.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:17:37,892] Trial 13 finished with value: 0.5784070461894295 and parameters: {'n_estimators': 500, 'learning_rate': 0.048846267609848434, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.7130762324874481, 'colsample_bytree': 0.6639505095662201}. Best is trial 12 with value: 0.6258079409205488.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:17:39,754] Trial 14 finished with value: 0.6270250808963034 and parameters: {'n_estimators': 500, 'learning_rate': 0.04876113896916153, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.7176461215093223, 'colsample_bytree': 0.6759132844855982}. Best is trial 14 with value: 0.6270250808963034.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:17:46,684] Trial 15 finished with value: 0.6130579681704994 and parameters: {'n_estimators': 2000, 'learning_rate': 0.0493089836251644, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.726294382468282, 'colsample_bytree': 0.8020218544212447}. Best is trial 14 with value: 0.6270250808963034.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:17:49,559] Trial 16 finished with value: 0.6094836493505014 and parameters: {'n_estimators': 500, 'learning_rate': 0.009453669992826496, 'max_depth': 8, 'min_child_weight': 4, 'subsample': 0.8555237315527192, 'colsample_bytree': 0.666555098745508}. Best is trial 14 with value: 0.6270250808963034.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:17:51,471] Trial 17 finished with value: 0.613557096230168 and parameters: {'n_estimators': 500, 'learning_rate': 0.018189492517882894, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.7469912089692647, 'colsample_bytree': 0.7901582237780922}. Best is trial 14 with value: 0.6270250808963034.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:17:55,465] Trial 18 finished with value: 0.5547116479508214 and parameters: {'n_estimators': 1000, 'learning_rate': 0.04260842404745054, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.6629825823034725, 'colsample_bytree': 0.9969737296371852}. Best is trial 14 with value: 0.6270250808963034.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:18:03,041] Trial 19 finished with value: 0.5789495634948554 and parameters: {'n_estimators': 2000, 'learning_rate': 0.039649057315111896, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.9011506025933514, 'colsample_bytree': 0.6863114711854917}. Best is trial 14 with value: 0.6270250808963034.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:18:04,991] Trial 20 finished with value: 0.5859838317414383 and parameters: {'n_estimators': 500, 'learning_rate': 0.018897343421702715, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.7563135675736005, 'colsample_bytree': 0.7908796697434542}. Best is trial 14 with value: 0.6270250808963034.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:18:07,013] Trial 21 finished with value: 0.6081138795676742 and parameters: {'n_estimators': 500, 'learning_rate': 0.009207572180948202, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.7418446548112788, 'colsample_bytree': 0.7976962563462887}. Best is trial 14 with value: 0.6270250808963034.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:18:08,893] Trial 22 finished with value: 0.6187468100204544 and parameters: {'n_estimators': 500, 'learning_rate': 0.019011102004610626, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.6785357683368524, 'colsample_bytree': 0.6515251032691819}. Best is trial 14 with value: 0.6270250808963034.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:18:10,746] Trial 23 finished with value: 0.6044384207111557 and parameters: {'n_estimators': 500, 'learning_rate': 0.03856284946544071, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.6852659166224041, 'colsample_bytree': 0.6362684080205132}. Best is trial 14 with value: 0.6270250808963034.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:18:13,018] Trial 24 finished with value: 0.6147978720881925 and parameters: {'n_estimators': 500, 'learning_rate': 0.008478341971786922, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.6944390872723758, 'colsample_bytree': 0.7167018330992967}. Best is trial 14 with value: 0.6270250808963034.
[I 2025-09-04 15:18:13,020] A new study created in memory with name: no-name-b3aec762-2644-49f4-9332-e317a1d7d895

✅ XGB con TOA_5x5_depth_in_3_4 - Mejor R2: 0.63
📋 Parámetros: {'n_estimators': 500, 'learning_rate': 0.04876113896916153, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.7176461215093223, 'colsample_bytree': 0.6759132844855982}

Buscando mejores hiperparámetros para LBM con TOA_5x5_depth_in_3_4...

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:18:14,592] Trial 0 finished with value: 0.6119433999203302 and parameters: {'learning_rate': 0.008018389564981968, 'num_leaves': 20, 'max_depth': 8, 'min_child_samples': 12, 'subsample': 0.7853760537574096, 'colsample_bytree': 0.6798928042984664, 'n_estimators': 2000}. Best is trial 0 with value: 0.6119433999203302.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 15:18:15,424] Trial 1 finished with value: 0.6420942537204428 and parameters: {'learning_rate': 0.025953926973062133, 'num_leaves': 20, 'max_depth': 8, 'min_child_samples': 6, 'subsample': 0.7111952990627602, 'colsample_bytree': 0.7569096103890791, 'n_estimators': 1000}. Best is trial 1 with value: 0.6420942537204428.

Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:18:16,003] Trial 2 finished with value: 0.655429722820962 and parameters: {'learning_rate': 0.00823790103191379, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 8, 'subsample': 0.6030520699693367, 'colsample_bytree': 0.9043535106869406, 'n_estimators': 1000}. Best is trial 2 with value: 0.655429722820962.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 15:18:16,924] Trial 3 finished with value: 0.6060067816996589 and parameters: {'learning_rate': 0.01951793755194223, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 15, 'subsample': 0.7967462088917463, 'colsample_bytree': 0.6899813889666787, 'n_estimators': 2000}. Best is trial 2 with value: 0.655429722820962.

Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:18:18,560] Trial 4 finished with value: 0.6624834124309174 and parameters: {'learning_rate': 0.043092682349242205, 'num_leaves': 60, 'max_depth': 7, 'min_child_samples': 5, 'subsample': 0.8165193812513174, 'colsample_bytree': 0.9210404372794343, 'n_estimators': 2000}. Best is trial 4 with value: 0.6624834124309174.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:18:19,882] Trial 5 finished with value: 0.5631886029937809 and parameters: {'learning_rate': 0.04874852449239148, 'num_leaves': 80, 'max_depth': 7, 'min_child_samples': 12, 'subsample': 0.7414423116434796, 'colsample_bytree': 0.742103853314802, 'n_estimators': 2000}. Best is trial 4 with value: 0.6624834124309174.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:18:21,149] Trial 6 finished with value: 0.6176682176896336 and parameters: {'learning_rate': 0.00924432981482246, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 9, 'subsample': 0.8341567044404934, 'colsample_bytree': 0.8739337855308824, 'n_estimators': 2000}. Best is trial 4 with value: 0.6624834124309174.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 15:18:21,829] Trial 7 finished with value: 0.6149500637225097 and parameters: {'learning_rate': 0.0331865375158454, 'num_leaves': 40, 'max_depth': 8, 'min_child_samples': 16, 'subsample': 0.8439067315810362, 'colsample_bytree': 0.7266139452043299, 'n_estimators': 1000}. Best is trial 4 with value: 0.6624834124309174.

Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:18:22,578] Trial 8 finished with value: 0.5928418116453666 and parameters: {'learning_rate': 0.03849663961745497, 'num_leaves': 80, 'max_depth': 7, 'min_child_samples': 8, 'subsample': 0.625846506181397, 'colsample_bytree': 0.7500813192087519, 'n_estimators': 1000}. Best is trial 4 with value: 0.6624834124309174.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:18:24,050] Trial 9 finished with value: 0.6465886397185755 and parameters: {'learning_rate': 0.012197732247117015, 'num_leaves': 60, 'max_depth': 7, 'min_child_samples': 6, 'subsample': 0.6166927190762289, 'colsample_bytree': 0.7811620601819189, 'n_estimators': 2000}. Best is trial 4 with value: 0.6624834124309174.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 15:18:24,440] Trial 10 finished with value: 0.663876920332119 and parameters: {'learning_rate': 0.017601667464677048, 'num_leaves': 60, 'max_depth': 6, 'min_child_samples': 5, 'subsample': 0.9641585345004289, 'colsample_bytree': 0.9962755839821873, 'n_estimators': 500}. Best is trial 10 with value: 0.663876920332119.

Fold 4
Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 15:18:24,898] Trial 11 finished with value: 0.6612231679236787 and parameters: {'learning_rate': 0.005151738869866296, 'num_leaves': 60, 'max_depth': 6, 'min_child_samples': 4, 'subsample': 0.9811728834834733, 'colsample_bytree': 0.9991183878153083, 'n_estimators': 500}. Best is trial 10 with value: 0.663876920332119.

Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:18:25,299] Trial 12 finished with value: 0.6783912689958511 and parameters: {'learning_rate': 0.01955671466854787, 'num_leaves': 60, 'max_depth': 6, 'min_child_samples': 4, 'subsample': 0.9583671783514893, 'colsample_bytree': 0.9991128614038579, 'n_estimators': 500}. Best is trial 12 with value: 0.6783912689958511.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 15:18:25,703] Trial 13 finished with value: 0.6718890574040366 and parameters: {'learning_rate': 0.01754680023378169, 'num_leaves': 60, 'max_depth': 6, 'min_child_samples': 4, 'subsample': 0.9802392196167939, 'colsample_bytree': 0.9885641523554517, 'n_estimators': 500}. Best is trial 12 with value: 0.6783912689958511.

Fold 4
Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:18:26,008] Trial 14 finished with value: 0.6348490244137741 and parameters: {'learning_rate': 0.02299916300980899, 'num_leaves': 60, 'max_depth': 5, 'min_child_samples': 4, 'subsample': 0.9157663811507291, 'colsample_bytree': 0.6186697220211019, 'n_estimators': 500}. Best is trial 12 with value: 0.6783912689958511.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 15:18:26,401] Trial 15 finished with value: 0.6519554466558464 and parameters: {'learning_rate': 0.014735916994579674, 'num_leaves': 40, 'max_depth': 6, 'min_child_samples': 7, 'subsample': 0.9214501776186284, 'colsample_bytree': 0.9461940167597882, 'n_estimators': 500}. Best is trial 12 with value: 0.6783912689958511.

Fold 4
Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 15:18:26,761] Trial 16 finished with value: 0.59889011918472 and parameters: {'learning_rate': 0.027937278087424775, 'num_leaves': 60, 'max_depth': 6, 'min_child_samples': 11, 'subsample': 0.9110831324241404, 'colsample_bytree': 0.853524467203828, 'n_estimators': 500}. Best is trial 12 with value: 0.6783912689958511.

Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2

[I 2025-09-04 15:18:27,085] Trial 17 finished with value: 0.6185012057820707 and parameters: {'learning_rate': 0.01289391434601206, 'num_leaves': 60, 'max_depth': 5, 'min_child_samples': 10, 'subsample': 0.9935800833850046, 'colsample_bytree': 0.8292553155705187, 'n_estimators': 500}. Best is trial 12 with value: 0.6783912689958511.

Fold 3
Fold 4
Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 15:18:27,503] Trial 18 finished with value: 0.663098964395171 and parameters: {'learning_rate': 0.011150325495358946, 'num_leaves': 60, 'max_depth': 6, 'min_child_samples': 4, 'subsample': 0.8781245065597728, 'colsample_bytree': 0.9592974708403786, 'n_estimators': 500}. Best is trial 12 with value: 0.6783912689958511.

Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:18:27,950] Trial 19 finished with value: 0.6524632963040442 and parameters: {'learning_rate': 0.02051630359593618, 'num_leaves': 80, 'max_depth': 7, 'min_child_samples': 6, 'subsample': 0.9547367435778499, 'colsample_bytree': 0.9686060335701578, 'n_estimators': 500}. Best is trial 12 with value: 0.6783912689958511.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 15:18:28,253] Trial 20 finished with value: 0.6102802856443788 and parameters: {'learning_rate': 0.015317384328210518, 'num_leaves': 40, 'max_depth': 5, 'min_child_samples': 14, 'subsample': 0.8843070507926132, 'colsample_bytree': 0.8993958842904177, 'n_estimators': 500}. Best is trial 12 with value: 0.6783912689958511.

Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:18:28,644] Trial 21 finished with value: 0.6616998546787083 and parameters: {'learning_rate': 0.01788376791425415, 'num_leaves': 60, 'max_depth': 6, 'min_child_samples': 5, 'subsample': 0.9659174494148783, 'colsample_bytree': 0.9978440349029285, 'n_estimators': 500}. Best is trial 12 with value: 0.6783912689958511.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 15:18:29,026] Trial 22 finished with value: 0.6677804297330209 and parameters: {'learning_rate': 0.01770402678654449, 'num_leaves': 60, 'max_depth': 6, 'min_child_samples': 5, 'subsample': 0.9443376558927802, 'colsample_bytree': 0.9398038677365694, 'n_estimators': 500}. Best is trial 12 with value: 0.6783912689958511.

Fold 4
Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 15:18:29,396] Trial 23 finished with value: 0.6259037620989072 and parameters: {'learning_rate': 0.029555116859646558, 'num_leaves': 60, 'max_depth': 6, 'min_child_samples': 7, 'subsample': 0.9409394135496952, 'colsample_bytree': 0.9431291898644135, 'n_estimators': 500}. Best is trial 12 with value: 0.6783912689958511.

Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:18:29,789] Trial 24 finished with value: 0.659183309097177 and parameters: {'learning_rate': 0.021784184591651302, 'num_leaves': 60, 'max_depth': 6, 'min_child_samples': 4, 'subsample': 0.8887090633363477, 'colsample_bytree': 0.9222312194808412, 'n_estimators': 500}. Best is trial 12 with value: 0.6783912689958511.
[I 2025-09-04 15:18:29,790] A new study created in memory with name: no-name-5ec33605-d044-4ac7-ab10-78f00f5f0328

✅ LBM con TOA_5x5_depth_in_3_4 - Mejor R2: 0.68
📋 Parámetros: {'learning_rate': 0.01955671466854787, 'num_leaves': 60, 'max_depth': 6, 'min_child_samples': 4, 'subsample': 0.9583671783514893, 'colsample_bytree': 0.9991128614038579, 'n_estimators': 500}

Buscando mejores hiperparámetros para MLP con TOA_5x5_depth_in_3_4...

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

[I 2025-09-04 15:18:31,092] Trial 0 finished with value: 0.5398397311322216 and parameters: {'hidden_layer_sizes': '128', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.0019457627912265307, 'learning_rate': 'adaptive', 'learning_rate_init': 0.001363647901157331}. Best is trial 0 with value: 0.5398397311322216.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:18:32,821] Trial 1 finished with value: 0.5537033913095457 and parameters: {'hidden_layer_sizes': '256_128', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0004424197354035913, 'learning_rate': 'adaptive', 'learning_rate_init': 0.004423127381607736}. Best is trial 1 with value: 0.5537033913095457.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

[I 2025-09-04 15:18:35,093] Trial 2 finished with value: 0.5279259630023441 and parameters: {'hidden_layer_sizes': '256', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 3.0253469485534904e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.0001305136083975515}. Best is trial 1 with value: 0.5537033913095457.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 15:18:36,251] Trial 3 finished with value: 0.6271822525098496 and parameters: {'hidden_layer_sizes': '256_128', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.011814353008389187, 'learning_rate': 'constant', 'learning_rate_init': 0.009614210609607807}. Best is trial 3 with value: 0.6271822525098496.

Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:18:37,160] Trial 4 finished with value: 0.6196688934844288 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.001866310054888363, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0014137843135588561}. Best is trial 3 with value: 0.6271822525098496.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

[I 2025-09-04 15:18:38,430] Trial 5 finished with value: 0.527180595720679 and parameters: {'hidden_layer_sizes': '128', 'activation': 'relu', 'solver': 'sgd', 'alpha': 7.286074961037855e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0012620827996976378}. Best is trial 3 with value: 0.6271822525098496.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-04 15:18:39,408] Trial 6 finished with value: 0.43850220035352117 and parameters: {'hidden_layer_sizes': '128', 'activation': 'relu', 'solver': 'adam', 'alpha': 2.367198647793813e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.00010759040747784836}. Best is trial 3 with value: 0.6271822525098496.

Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

[I 2025-09-04 15:18:40,391] Trial 7 finished with value: 0.5618526004796547 and parameters: {'hidden_layer_sizes': '128', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.0014558225544977867, 'learning_rate': 'constant', 'learning_rate_init': 0.0017944622461381475}. Best is trial 3 with value: 0.6271822525098496.

Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-04 15:18:43,179] Trial 8 finished with value: 0.5220222771870218 and parameters: {'hidden_layer_sizes': '256_128', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.019708529670353574, 'learning_rate': 'constant', 'learning_rate_init': 0.0002071031685779521}. Best is trial 3 with value: 0.6271822525098496.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

[I 2025-09-04 15:18:45,225] Trial 9 finished with value: 0.5398228185139242 and parameters: {'hidden_layer_sizes': '256', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.055823133156757465, 'learning_rate': 'constant', 'learning_rate_init': 0.0005107625304062146}. Best is trial 3 with value: 0.6271822525098496.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:18:46,173] Trial 10 finished with value: 0.6137489134379741 and parameters: {'hidden_layer_sizes': '256_128', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.009474672456586201, 'learning_rate': 'constant', 'learning_rate_init': 0.009076128859739631}. Best is trial 3 with value: 0.6271822525098496.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:18:47,183] Trial 11 finished with value: 0.5840140287929325 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.005192309063930063, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0037027895564930736}. Best is trial 3 with value: 0.6271822525098496.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 15:18:48,466] Trial 12 finished with value: 0.6795418024187128 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0003024593285486088, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00053892320993219}. Best is trial 12 with value: 0.6795418024187128.

Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3
Fold 4

[I 2025-09-04 15:18:49,724] Trial 13 finished with value: 0.697052741789139 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.00024472909052337217, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0005084699170246252}. Best is trial 13 with value: 0.697052741789139.

Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 15:18:50,905] Trial 14 finished with value: 0.6907148098030527 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.00021424651431694702, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00046327720513102306}. Best is trial 13 with value: 0.697052741789139.

Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3
Fold 4

[I 2025-09-04 15:18:52,246] Trial 15 finished with value: 0.6877525923303729 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 9.10425447585815e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0004308983133685128}. Best is trial 13 with value: 0.697052741789139.

Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

[I 2025-09-04 15:18:53,917] Trial 16 finished with value: 0.6645574481749643 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.00028287022291447096, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00026496772507982}. Best is trial 13 with value: 0.697052741789139.

Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:18:55,046] Trial 17 finished with value: 0.6340222047648834 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 1.0088418272404604e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0007501679675904444}. Best is trial 13 with value: 0.697052741789139.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-04 15:18:56,998] Trial 18 finished with value: 0.5673619198860389 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.00010850431705765378, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00028669964393306763}. Best is trial 13 with value: 0.697052741789139.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:18:57,974] Trial 19 finished with value: 0.6911470368278663 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0005835117667204147, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0009094752781007243}. Best is trial 13 with value: 0.697052741789139.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 15:18:58,702] Trial 20 finished with value: 0.6664536353642081 and parameters: {'hidden_layer_sizes': '256', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0007520677292426273, 'learning_rate': 'adaptive', 'learning_rate_init': 0.002430438249210215}. Best is trial 13 with value: 0.697052741789139.

Fold 4
Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:18:59,703] Trial 21 finished with value: 0.6474411279221719 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0005205757287699949, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0007929092402504703}. Best is trial 13 with value: 0.697052741789139.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

[I 2025-09-04 15:19:01,368] Trial 22 finished with value: 0.6470093583340452 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.00011342732504747906, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00037911198972043864}. Best is trial 13 with value: 0.697052741789139.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:19:02,388] Trial 23 finished with value: 0.6361024684379128 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0002485182838971151, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0007379717579987876}. Best is trial 13 with value: 0.697052741789139.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

[I 2025-09-04 15:19:04,220] Trial 24 finished with value: 0.6667545539428446 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0034209441760855077, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00020159662479320948}. Best is trial 13 with value: 0.697052741789139.
[I 2025-09-04 15:19:04,221] A new study created in memory with name: no-name-9c818fd3-7642-4a97-9b5b-eee91332b788
[I 2025-09-04 15:19:04,328] Trial 0 finished with value: 0.4354086026982823 and parameters: {'C': 0.9349596713770617, 'epsilon': 0.051001163585534005}. Best is trial 0 with value: 0.4354086026982823.
[I 2025-09-04 15:19:04,406] Trial 1 finished with value: 0.30631569171315076 and parameters: {'C': 0.38394995818295785, 'epsilon': 0.11788505948269667}. Best is trial 0 with value: 0.4354086026982823.

✅ MLP con TOA_5x5_depth_in_3_4 - Mejor R2: 0.70
📋 Parámetros: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.00024472909052337217, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0005084699170246252}

Buscando mejores hiperparámetros para SVR con TOA_5x5_depth_in_3_4...

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1

[I 2025-09-04 15:19:04,486] Trial 2 finished with value: 0.15428750131915991 and parameters: {'C': 0.16581514085928228, 'epsilon': 0.18751872710652995}. Best is trial 0 with value: 0.4354086026982823.
[I 2025-09-04 15:19:04,572] Trial 3 finished with value: 0.47758015254793695 and parameters: {'C': 2.831978172349839, 'epsilon': 0.09448696741636678}. Best is trial 3 with value: 0.47758015254793695.

Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 15:19:04,657] Trial 4 finished with value: 0.43598020588429187 and parameters: {'C': 0.93572101507951, 'epsilon': 0.08375355204278252}. Best is trial 3 with value: 0.47758015254793695.
[I 2025-09-04 15:19:04,741] Trial 5 finished with value: 0.478107996772953 and parameters: {'C': 3.2885288211618766, 'epsilon': 0.1843788179258095}. Best is trial 5 with value: 0.478107996772953.
[I 2025-09-04 15:19:04,825] Trial 6 finished with value: 0.4512800843613547 and parameters: {'C': 6.471885588601558, 'epsilon': 0.1792135913090028}. Best is trial 5 with value: 0.478107996772953.

Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1

[I 2025-09-04 15:19:04,912] Trial 7 finished with value: 0.48077161303377547 and parameters: {'C': 2.659666932112974, 'epsilon': 0.0723877170764857}. Best is trial 7 with value: 0.48077161303377547.
[I 2025-09-04 15:19:04,993] Trial 8 finished with value: 0.46123480084737456 and parameters: {'C': 1.2975283707853742, 'epsilon': 0.1791198310420039}. Best is trial 7 with value: 0.48077161303377547.

Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 15:19:05,077] Trial 9 finished with value: 0.4775801315480884 and parameters: {'C': 2.7613566799058606, 'epsilon': 0.14202288083084763}. Best is trial 7 with value: 0.48077161303377547.
[I 2025-09-04 15:19:05,181] Trial 10 finished with value: 0.41732714604703813 and parameters: {'C': 8.029595311430477, 'epsilon': 0.016685204979666753}. Best is trial 7 with value: 0.48077161303377547.

Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:19:05,272] Trial 11 finished with value: 0.48207094645566717 and parameters: {'C': 2.6454982825405233, 'epsilon': 0.05827310652953446}. Best is trial 11 with value: 0.48207094645566717.
[I 2025-09-04 15:19:05,363] Trial 12 finished with value: 0.47657738240924497 and parameters: {'C': 1.7016631556788575, 'epsilon': 0.05671154614720527}. Best is trial 11 with value: 0.48207094645566717.
[I 2025-09-04 15:19:05,448] Trial 13 finished with value: 0.3428779395255863 and parameters: {'C': 0.5184657256110865, 'epsilon': 0.0538529885063006}. Best is trial 11 with value: 0.48207094645566717.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1

[I 2025-09-04 15:19:05,545] Trial 14 finished with value: 0.46159673167121706 and parameters: {'C': 4.277770108176178, 'epsilon': 0.010192155106167153}. Best is trial 11 with value: 0.48207094645566717.
[I 2025-09-04 15:19:05,638] Trial 15 finished with value: 0.4822413246809847 and parameters: {'C': 2.0192256643063637, 'epsilon': 0.07346992211329484}. Best is trial 15 with value: 0.4822413246809847.

Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2

[I 2025-09-04 15:19:05,727] Trial 16 finished with value: 0.3571937818854042 and parameters: {'C': 0.5362671799916013, 'epsilon': 0.12449299415695714}. Best is trial 15 with value: 0.4822413246809847.
[I 2025-09-04 15:19:05,821] Trial 17 finished with value: 0.47672582936174634 and parameters: {'C': 1.7006155890582682, 'epsilon': 0.03204490246714686}. Best is trial 15 with value: 0.4822413246809847.

Fold 3
Fold 4
Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 15:19:05,914] Trial 18 finished with value: 0.46699869954715234 and parameters: {'C': 4.873435786130195, 'epsilon': 0.15063214890294258}. Best is trial 15 with value: 0.4822413246809847.
[I 2025-09-04 15:19:06,016] Trial 19 finished with value: 0.06972513372135092 and parameters: {'C': 0.11431207653497129, 'epsilon': 0.07161244889351555}. Best is trial 15 with value: 0.4822413246809847.

Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 15:19:06,115] Trial 20 finished with value: 0.4143224479591656 and parameters: {'C': 9.363109128968139, 'epsilon': 0.035142485162164054}. Best is trial 15 with value: 0.4822413246809847.
[I 2025-09-04 15:19:06,210] Trial 21 finished with value: 0.48245386242505195 and parameters: {'C': 2.3734478600526887, 'epsilon': 0.07772733901784441}. Best is trial 21 with value: 0.48245386242505195.
[I 2025-09-04 15:19:06,296] Trial 22 finished with value: 0.47521833482172327 and parameters: {'C': 1.6734036568777932, 'epsilon': 0.11005700683516066}. Best is trial 21 with value: 0.48245386242505195.

Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===

[I 2025-09-04 15:19:06,389] Trial 23 finished with value: 0.4625717788174494 and parameters: {'C': 4.6561575368311425, 'epsilon': 0.09605629698721949}. Best is trial 21 with value: 0.48245386242505195.
[I 2025-09-04 15:19:06,482] Trial 24 finished with value: 0.4825442834743249 and parameters: {'C': 2.063097300418171, 'epsilon': 0.0789893324667928}. Best is trial 24 with value: 0.4825442834743249.
[I 2025-09-04 15:19:06,483] A new study created in memory with name: no-name-d4faf3cd-ea3b-4165-8b2e-c79a5f9a4dee

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

✅ SVR con TOA_5x5_depth_in_3_4 - Mejor R2: 0.48
📋 Parámetros: {'C': 2.063097300418171, 'epsilon': 0.0789893324667928}

Buscando mejores hiperparámetros para KNN con TOA_5x5_depth_in_3_4...

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2

[I 2025-09-04 15:19:06,552] Trial 0 finished with value: 0.6282937276665062 and parameters: {'n_neighbors': 7, 'leaf_size': 18}. Best is trial 0 with value: 0.6282937276665062.
[I 2025-09-04 15:19:06,618] Trial 1 finished with value: 0.636718245103097 and parameters: {'n_neighbors': 8, 'leaf_size': 33}. Best is trial 1 with value: 0.636718245103097.
[I 2025-09-04 15:19:06,682] Trial 2 finished with value: 0.5854437134421608 and parameters: {'n_neighbors': 4, 'leaf_size': 40}. Best is trial 1 with value: 0.636718245103097.

Fold 3
Fold 4
Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 15:19:06,753] Trial 3 finished with value: 0.636718245103097 and parameters: {'n_neighbors': 8, 'leaf_size': 30}. Best is trial 1 with value: 0.636718245103097.
[I 2025-09-04 15:19:06,823] Trial 4 finished with value: 0.6349148321330371 and parameters: {'n_neighbors': 9, 'leaf_size': 34}. Best is trial 1 with value: 0.636718245103097.
[I 2025-09-04 15:19:06,888] Trial 5 finished with value: 0.6052176455604728 and parameters: {'n_neighbors': 5, 'leaf_size': 13}. Best is trial 1 with value: 0.636718245103097.

Fold 4
Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 15:19:06,955] Trial 6 finished with value: 0.6378947254455116 and parameters: {'n_neighbors': 10, 'leaf_size': 18}. Best is trial 6 with value: 0.6378947254455116.
[I 2025-09-04 15:19:07,024] Trial 7 finished with value: 0.6349148321330371 and parameters: {'n_neighbors': 9, 'leaf_size': 32}. Best is trial 6 with value: 0.6378947254455116.
[I 2025-09-04 15:19:07,088] Trial 8 finished with value: 0.636718245103097 and parameters: {'n_neighbors': 8, 'leaf_size': 15}. Best is trial 6 with value: 0.6378947254455116.

Fold 4
Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 15:19:07,157] Trial 9 finished with value: 0.5854437134421608 and parameters: {'n_neighbors': 4, 'leaf_size': 35}. Best is trial 6 with value: 0.6378947254455116.
[I 2025-09-04 15:19:07,231] Trial 10 finished with value: 0.6378947254455116 and parameters: {'n_neighbors': 10, 'leaf_size': 22}. Best is trial 6 with value: 0.6378947254455116.
[I 2025-09-04 15:19:07,301] Trial 11 finished with value: 0.6378947254455116 and parameters: {'n_neighbors': 10, 'leaf_size': 22}. Best is trial 6 with value: 0.6378947254455116.

Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 15:19:07,376] Trial 12 finished with value: 0.6378947254455116 and parameters: {'n_neighbors': 10, 'leaf_size': 24}. Best is trial 6 with value: 0.6378947254455116.
[I 2025-09-04 15:19:07,451] Trial 13 finished with value: 0.6220921015202285 and parameters: {'n_neighbors': 6, 'leaf_size': 19}. Best is trial 6 with value: 0.6378947254455116.
[I 2025-09-04 15:19:07,522] Trial 14 finished with value: 0.6378947254455116 and parameters: {'n_neighbors': 10, 'leaf_size': 10}. Best is trial 6 with value: 0.6378947254455116.

Fold 4
Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2

[I 2025-09-04 15:19:07,598] Trial 15 finished with value: 0.6349148321330371 and parameters: {'n_neighbors': 9, 'leaf_size': 27}. Best is trial 6 with value: 0.6378947254455116.
[I 2025-09-04 15:19:07,698] Trial 16 finished with value: 0.5287445797208759 and parameters: {'n_neighbors': 3, 'leaf_size': 20}. Best is trial 6 with value: 0.6378947254455116.

Fold 3
Fold 4
Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:19:07,769] Trial 17 finished with value: 0.6220921015202285 and parameters: {'n_neighbors': 6, 'leaf_size': 27}. Best is trial 6 with value: 0.6378947254455116.
[I 2025-09-04 15:19:07,845] Trial 18 finished with value: 0.6282937276665062 and parameters: {'n_neighbors': 7, 'leaf_size': 16}. Best is trial 6 with value: 0.6378947254455116.
[I 2025-09-04 15:19:07,915] Trial 19 finished with value: 0.6378947254455116 and parameters: {'n_neighbors': 10, 'leaf_size': 23}. Best is trial 6 with value: 0.6378947254455116.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 15:19:07,988] Trial 20 finished with value: 0.6349148321330371 and parameters: {'n_neighbors': 9, 'leaf_size': 27}. Best is trial 6 with value: 0.6378947254455116.
[I 2025-09-04 15:19:08,066] Trial 21 finished with value: 0.6378947254455116 and parameters: {'n_neighbors': 10, 'leaf_size': 22}. Best is trial 6 with value: 0.6378947254455116.
[I 2025-09-04 15:19:08,138] Trial 22 finished with value: 0.6378947254455116 and parameters: {'n_neighbors': 10, 'leaf_size': 21}. Best is trial 6 with value: 0.6378947254455116.

Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 15:19:08,214] Trial 23 finished with value: 0.6349148321330371 and parameters: {'n_neighbors': 9, 'leaf_size': 17}. Best is trial 6 with value: 0.6378947254455116.
[I 2025-09-04 15:19:08,290] Trial 24 finished with value: 0.636718245103097 and parameters: {'n_neighbors': 8, 'leaf_size': 25}. Best is trial 6 with value: 0.6378947254455116.
[I 2025-09-04 15:19:08,291] A new study created in memory with name: no-name-595b93d1-e047-4cd8-b6f4-aa827cde763c
[I 2025-09-04 15:19:08,353] Trial 0 finished with value: 0.3130924200002867 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 0 with value: 0.3130924200002867.

Fold 4
Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

✅ KNN con TOA_5x5_depth_in_3_4 - Mejor R2: 0.64
📋 Parámetros: {'n_neighbors': 10, 'leaf_size': 18}

Buscando mejores hiperparámetros para LR con TOA_5x5_depth_in_3_4...

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 15:19:08,417] Trial 1 finished with value: 0.3130924200002867 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 0 with value: 0.3130924200002867.
[I 2025-09-04 15:19:08,482] Trial 2 finished with value: 0.31309242000029147 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 2 with value: 0.31309242000029147.
[I 2025-09-04 15:19:08,563] Trial 3 finished with value: 0.44824949663108316 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 3 with value: 0.44824949663108316.

Fold 4
Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2

[I 2025-09-04 15:19:08,660] Trial 4 finished with value: 0.44824949663123237 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 4 with value: 0.44824949663123237.
[I 2025-09-04 15:19:08,755] Trial 5 finished with value: 0.3130924200002867 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 4 with value: 0.44824949663123237.

Fold 3
Fold 4
Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 15:19:08,890] Trial 6 finished with value: 0.44824949663123237 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 4 with value: 0.44824949663123237.
[I 2025-09-04 15:19:08,998] Trial 7 finished with value: 0.31309242000029147 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 4 with value: 0.44824949663123237.

Fold 4
Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2

[I 2025-09-04 15:19:09,151] Trial 8 finished with value: 0.44824949663123237 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 4 with value: 0.44824949663123237.
[I 2025-09-04 15:19:09,248] Trial 9 finished with value: 0.44824949663108316 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 4 with value: 0.44824949663123237.

Fold 3
Fold 4
Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===

[I 2025-09-04 15:19:09,344] Trial 10 finished with value: 0.44824949663123237 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 4 with value: 0.44824949663123237.
[I 2025-09-04 15:19:09,442] Trial 11 finished with value: 0.44824949663123237 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 4 with value: 0.44824949663123237.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1

[I 2025-09-04 15:19:09,542] Trial 12 finished with value: 0.44824949663123237 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 4 with value: 0.44824949663123237.
[I 2025-09-04 15:19:09,638] Trial 13 finished with value: 0.44824949663123237 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 4 with value: 0.44824949663123237.

Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2

[I 2025-09-04 15:19:09,734] Trial 14 finished with value: 0.44824949663123237 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 4 with value: 0.44824949663123237.

Fold 3
Fold 4
Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 15:19:09,922] Trial 15 finished with value: 0.44824949663123237 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 4 with value: 0.44824949663123237.
[I 2025-09-04 15:19:10,022] Trial 16 finished with value: 0.44824949663123237 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 4 with value: 0.44824949663123237.

Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:19:10,113] Trial 17 finished with value: 0.44824949663123237 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 4 with value: 0.44824949663123237.
[I 2025-09-04 15:19:10,221] Trial 18 finished with value: 0.44824949663123237 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 4 with value: 0.44824949663123237.
[I 2025-09-04 15:19:10,311] Trial 19 finished with value: 0.44824949663123237 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 4 with value: 0.44824949663123237.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===

[I 2025-09-04 15:19:10,409] Trial 20 finished with value: 0.44824949663123237 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 4 with value: 0.44824949663123237.
[I 2025-09-04 15:19:10,508] Trial 21 finished with value: 0.44824949663123237 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 4 with value: 0.44824949663123237.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1

[I 2025-09-04 15:19:10,610] Trial 22 finished with value: 0.44824949663123237 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 4 with value: 0.44824949663123237.
[I 2025-09-04 15:19:10,710] Trial 23 finished with value: 0.44824949663123237 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 4 with value: 0.44824949663123237.

Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2

[I 2025-09-04 15:19:10,815] Trial 24 finished with value: 0.44824949663123237 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 4 with value: 0.44824949663123237.
[I 2025-09-04 15:19:10,816] A new study created in memory with name: no-name-d0b81848-62e8-4b66-ba2d-46a115f95405

Fold 3
Fold 4
Fold 5

✅ LR con TOA_5x5_depth_in_3_4 - Mejor R2: 0.45
📋 Parámetros: {'fit_intercept': True, 'positive': False}

Buscando mejores hiperparámetros para RF con TOA_5x5_depth_in_3_4...

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:19:13,396] Trial 0 finished with value: 0.6248809596928335 and parameters: {'n_estimators': 100, 'max_depth': 12, 'min_samples_split': 4, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 0 with value: 0.6248809596928335.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:19:27,206] Trial 1 finished with value: 0.5375754191255152 and parameters: {'n_estimators': 500, 'max_depth': 7, 'min_samples_split': 7, 'min_samples_leaf': 5, 'bootstrap': False}. Best is trial 0 with value: 0.6248809596928335.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:19:38,497] Trial 2 finished with value: 0.6027840931150785 and parameters: {'n_estimators': 500, 'max_depth': 14, 'min_samples_split': 9, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 0 with value: 0.6248809596928335.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:19:47,400] Trial 3 finished with value: 0.5969254559567024 and parameters: {'n_estimators': 300, 'max_depth': 14, 'min_samples_split': 2, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 0 with value: 0.6248809596928335.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:19:59,644] Trial 4 finished with value: 0.6044549972598235 and parameters: {'n_estimators': 500, 'max_depth': 13, 'min_samples_split': 7, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 0 with value: 0.6248809596928335.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:20:12,885] Trial 5 finished with value: 0.589658269379315 and parameters: {'n_estimators': 500, 'max_depth': 12, 'min_samples_split': 5, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 0 with value: 0.6248809596928335.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:20:25,611] Trial 6 finished with value: 0.5840273945379311 and parameters: {'n_estimators': 500, 'max_depth': 11, 'min_samples_split': 6, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 0 with value: 0.6248809596928335.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:20:45,325] Trial 7 finished with value: 0.5513769140897612 and parameters: {'n_estimators': 500, 'max_depth': 13, 'min_samples_split': 7, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 0 with value: 0.6248809596928335.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:20:52,220] Trial 8 finished with value: 0.5416344565900166 and parameters: {'n_estimators': 300, 'max_depth': 5, 'min_samples_split': 9, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 0 with value: 0.6248809596928335.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:21:02,057] Trial 9 finished with value: 0.5644350422008846 and parameters: {'n_estimators': 300, 'max_depth': 8, 'min_samples_split': 8, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 0 with value: 0.6248809596928335.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:21:04,052] Trial 10 finished with value: 0.574815039361644 and parameters: {'n_estimators': 100, 'max_depth': 9, 'min_samples_split': 3, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 0 with value: 0.6248809596928335.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:21:06,392] Trial 11 finished with value: 0.629786588590474 and parameters: {'n_estimators': 100, 'max_depth': 15, 'min_samples_split': 4, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 11 with value: 0.629786588590474.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:21:08,734] Trial 12 finished with value: 0.629786588590474 and parameters: {'n_estimators': 100, 'max_depth': 15, 'min_samples_split': 4, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 11 with value: 0.629786588590474.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:21:10,901] Trial 13 finished with value: 0.6071701717943285 and parameters: {'n_estimators': 100, 'max_depth': 15, 'min_samples_split': 4, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 11 with value: 0.629786588590474.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:21:13,242] Trial 14 finished with value: 0.629786588590474 and parameters: {'n_estimators': 100, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 11 with value: 0.629786588590474.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:21:15,380] Trial 15 finished with value: 0.6061128817689543 and parameters: {'n_estimators': 100, 'max_depth': 10, 'min_samples_split': 5, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 11 with value: 0.629786588590474.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:21:17,553] Trial 16 finished with value: 0.6071701717943285 and parameters: {'n_estimators': 100, 'max_depth': 15, 'min_samples_split': 4, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 11 with value: 0.629786588590474.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:21:19,892] Trial 17 finished with value: 0.6266771436301802 and parameters: {'n_estimators': 100, 'max_depth': 13, 'min_samples_split': 3, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 11 with value: 0.629786588590474.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:21:23,249] Trial 18 finished with value: 0.544210141722097 and parameters: {'n_estimators': 100, 'max_depth': 11, 'min_samples_split': 5, 'min_samples_leaf': 4, 'bootstrap': False}. Best is trial 11 with value: 0.629786588590474.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:21:24,883] Trial 19 finished with value: 0.603143551545622 and parameters: {'n_estimators': 100, 'max_depth': 5, 'min_samples_split': 3, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 11 with value: 0.629786588590474.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:21:27,125] Trial 20 finished with value: 0.6019006101181499 and parameters: {'n_estimators': 100, 'max_depth': 14, 'min_samples_split': 10, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 11 with value: 0.629786588590474.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:21:29,466] Trial 21 finished with value: 0.629786588590474 and parameters: {'n_estimators': 100, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 11 with value: 0.629786588590474.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:21:31,816] Trial 22 finished with value: 0.629786588590474 and parameters: {'n_estimators': 100, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 11 with value: 0.629786588590474.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:21:34,155] Trial 23 finished with value: 0.6284682358804347 and parameters: {'n_estimators': 100, 'max_depth': 14, 'min_samples_split': 3, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 11 with value: 0.629786588590474.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:21:36,324] Trial 24 finished with value: 0.6079141719383836 and parameters: {'n_estimators': 100, 'max_depth': 12, 'min_samples_split': 4, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 11 with value: 0.629786588590474.
[I 2025-09-04 15:21:36,326] A new study created in memory with name: no-name-28e5d701-f25d-499c-a9d7-617b88b93d64

✅ RF con TOA_5x5_depth_in_3_4 - Mejor R2: 0.63
📋 Parámetros: {'n_estimators': 100, 'max_depth': 15, 'min_samples_split': 4, 'min_samples_leaf': 3, 'bootstrap': True}

Buscando mejores hiperparámetros para CAT con TOA_5x5_depth_in_3_4...

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:23:09,450] Trial 0 finished with value: 0.5701903877952658 and parameters: {'iterations': 1000, 'learning_rate': 0.023356908377467595, 'depth': 9, 'l2_leaf_reg': 4.5130209188410015}. Best is trial 0 with value: 0.5701903877952658.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:24:29,893] Trial 1 finished with value: 0.5906555584514606 and parameters: {'iterations': 2000, 'learning_rate': 0.011458676372912696, 'depth': 8, 'l2_leaf_reg': 1.3120667615811812}. Best is trial 1 with value: 0.5906555584514606.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:30:11,175] Trial 2 finished with value: 0.5687191404974192 and parameters: {'iterations': 2000, 'learning_rate': 0.01696812209440194, 'depth': 10, 'l2_leaf_reg': 5.570428210194359}. Best is trial 1 with value: 0.5906555584514606.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:30:14,525] Trial 3 finished with value: 0.5507522778043462 and parameters: {'iterations': 500, 'learning_rate': 0.07355283813865186, 'depth': 6, 'l2_leaf_reg': 5.362793930377226}. Best is trial 1 with value: 0.5906555584514606.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:31:48,374] Trial 4 finished with value: 0.5810283486522926 and parameters: {'iterations': 1000, 'learning_rate': 0.037089553996005636, 'depth': 9, 'l2_leaf_reg': 2.70704662907929}. Best is trial 1 with value: 0.5906555584514606.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:31:49,861] Trial 5 finished with value: 0.5680431184003889 and parameters: {'iterations': 500, 'learning_rate': 0.020814200263465775, 'depth': 4, 'l2_leaf_reg': 2.3742925250249276}. Best is trial 1 with value: 0.5906555584514606.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:33:15,277] Trial 6 finished with value: 0.578586326276884 and parameters: {'iterations': 500, 'learning_rate': 0.027094635283130015, 'depth': 10, 'l2_leaf_reg': 2.3168160884249636}. Best is trial 1 with value: 0.5906555584514606.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:33:23,318] Trial 7 finished with value: 0.5670738829156763 and parameters: {'iterations': 500, 'learning_rate': 0.053472093787598755, 'depth': 7, 'l2_leaf_reg': 5.098852544229675}. Best is trial 1 with value: 0.5906555584514606.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:34:47,289] Trial 8 finished with value: 0.533592547041436 and parameters: {'iterations': 500, 'learning_rate': 0.01506221320005114, 'depth': 10, 'l2_leaf_reg': 5.0545656764328895}. Best is trial 1 with value: 0.5906555584514606.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:34:50,247] Trial 9 finished with value: 0.5495017357110783 and parameters: {'iterations': 1000, 'learning_rate': 0.03027479456346985, 'depth': 4, 'l2_leaf_reg': 1.6953566995020521}. Best is trial 1 with value: 0.5906555584514606.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:35:03,812] Trial 10 finished with value: 0.5932036038252724 and parameters: {'iterations': 2000, 'learning_rate': 0.010559051862634738, 'depth': 6, 'l2_leaf_reg': 1.211702318829953}. Best is trial 10 with value: 0.5932036038252724.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:35:17,364] Trial 11 finished with value: 0.5859261871823087 and parameters: {'iterations': 2000, 'learning_rate': 0.010880086176301849, 'depth': 6, 'l2_leaf_reg': 1.0591131504984033}. Best is trial 10 with value: 0.5932036038252724.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:35:48,071] Trial 12 finished with value: 0.593281221391937 and parameters: {'iterations': 2000, 'learning_rate': 0.01027011523144864, 'depth': 7, 'l2_leaf_reg': 1.0526076927639805}. Best is trial 12 with value: 0.593281221391937.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:36:01,836] Trial 13 finished with value: 0.5638213306979813 and parameters: {'iterations': 2000, 'learning_rate': 0.010061939615001942, 'depth': 6, 'l2_leaf_reg': 3.203801080050436}. Best is trial 12 with value: 0.593281221391937.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:36:10,482] Trial 14 finished with value: 0.5568704528234557 and parameters: {'iterations': 2000, 'learning_rate': 0.014601835654430068, 'depth': 5, 'l2_leaf_reg': 3.917918619897211}. Best is trial 12 with value: 0.593281221391937.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:36:47,361] Trial 15 finished with value: 0.5927161008804219 and parameters: {'iterations': 2000, 'learning_rate': 0.015490354921329172, 'depth': 7, 'l2_leaf_reg': 1.7887987800527672}. Best is trial 12 with value: 0.593281221391937.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:38:23,937] Trial 16 finished with value: 0.587210848887512 and parameters: {'iterations': 2000, 'learning_rate': 0.012634398810228422, 'depth': 8, 'l2_leaf_reg': 1.702174440474956}. Best is trial 12 with value: 0.593281221391937.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:38:34,962] Trial 17 finished with value: 0.5792872617851681 and parameters: {'iterations': 2000, 'learning_rate': 0.019691099611675974, 'depth': 5, 'l2_leaf_reg': 1.0250342980649343}. Best is trial 12 with value: 0.593281221391937.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:40:11,608] Trial 18 finished with value: 0.5865197740374517 and parameters: {'iterations': 2000, 'learning_rate': 0.03890866175135745, 'depth': 8, 'l2_leaf_reg': 3.409747977675239}. Best is trial 12 with value: 0.593281221391937.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:40:22,656] Trial 19 finished with value: 0.5570811067155919 and parameters: {'iterations': 2000, 'learning_rate': 0.013347938618240714, 'depth': 5, 'l2_leaf_reg': 5.999740521110702}. Best is trial 12 with value: 0.593281221391937.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:40:42,623] Trial 20 finished with value: 0.5730701283867848 and parameters: {'iterations': 1000, 'learning_rate': 0.017523620472123327, 'depth': 7, 'l2_leaf_reg': 2.800970156342241}. Best is trial 12 with value: 0.593281221391937.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:41:22,547] Trial 21 finished with value: 0.5849936517512384 and parameters: {'iterations': 2000, 'learning_rate': 0.010227388491784985, 'depth': 7, 'l2_leaf_reg': 1.629859688832643}. Best is trial 12 with value: 0.593281221391937.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:42:02,909] Trial 22 finished with value: 0.5895068366889042 and parameters: {'iterations': 2000, 'learning_rate': 0.012983927879805254, 'depth': 7, 'l2_leaf_reg': 1.9516125188548454}. Best is trial 12 with value: 0.593281221391937.
[I 2025-09-04 15:42:02,910] A new study created in memory with name: no-name-8b585e50-6e49-4b07-b3c6-c3a3116cc616
[I 2025-09-04 15:42:03,041] Trial 0 finished with value: 0.4122533090412349 and parameters: {'alpha': 0.2712182585894248, 'l1_ratio': 0.11711807953476172}. Best is trial 0 with value: 0.4122533090412349.

✅ CAT con TOA_5x5_depth_in_3_4 - Mejor R2: 0.59
📋 Parámetros: {'iterations': 2000, 'learning_rate': 0.01027011523144864, 'depth': 7, 'l2_leaf_reg': 1.0526076927639805}

Buscando mejores hiperparámetros para ELN con TOA_5x5_depth_in_3_4...

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 15:42:03,175] Trial 1 finished with value: 0.4587494706080888 and parameters: {'alpha': 0.027597340290835378, 'l1_ratio': 0.6270365860633268}. Best is trial 1 with value: 0.4587494706080888.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.831e+01, tolerance: 4.075e-02
  model = cd_fast.enet_coordinate_descent(

Fold 4
Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.047e+02, tolerance: 4.583e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.151e+01, tolerance: 3.985e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.196e+02, tolerance: 5.497e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.481e+01, tolerance: 4.044e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 15:42:03,358] Trial 2 finished with value: 0.4417614584772621 and parameters: {'alpha': 0.0006838647689195617, 'l1_ratio': 0.15589886812507492}. Best is trial 1 with value: 0.4587494706080888.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.188e+01, tolerance: 4.075e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.149e+01, tolerance: 4.583e-02
  model = cd_fast.enet_coordinate_descent(

Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.459e+01, tolerance: 3.985e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.055e+02, tolerance: 5.497e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.722e+01, tolerance: 4.044e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 15:42:03,527] Trial 3 finished with value: 0.43813487374875515 and parameters: {'alpha': 0.00021762006167748473, 'l1_ratio': 0.9873839343200314}. Best is trial 1 with value: 0.4587494706080888.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.136e+01, tolerance: 4.075e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.683e+01, tolerance: 4.583e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.036e+01, tolerance: 3.985e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.877e+01, tolerance: 5.497e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.418e+01, tolerance: 4.044e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 15:42:03,695] Trial 4 finished with value: 0.45113279929694705 and parameters: {'alpha': 0.002586458635699006, 'l1_ratio': 0.3997949829162425}. Best is trial 1 with value: 0.4587494706080888.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.029e+00, tolerance: 4.075e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.081e+00, tolerance: 4.583e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.592e+00, tolerance: 3.985e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.365e+00, tolerance: 5.497e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.856e+00, tolerance: 4.044e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 15:42:03,906] Trial 5 finished with value: 0.44697498144303105 and parameters: {'alpha': 0.042328637387412486, 'l1_ratio': 0.0433290875065776}. Best is trial 1 with value: 0.4587494706080888.

Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.786e+00, tolerance: 4.075e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.302e+00, tolerance: 4.583e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.092e+01, tolerance: 3.985e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.163e+01, tolerance: 5.497e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.540e+00, tolerance: 4.044e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 15:42:04,090] Trial 6 finished with value: 0.43271423413272336 and parameters: {'alpha': 0.0032231903180052566, 'l1_ratio': 0.6574359880318177}. Best is trial 1 with value: 0.4587494706080888.

Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.095e-01, tolerance: 3.985e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 15:42:04,241] Trial 7 finished with value: 0.4608809023746705 and parameters: {'alpha': 0.010802405973094757, 'l1_ratio': 0.7370198157681482}. Best is trial 7 with value: 0.4608809023746705.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.013e+01, tolerance: 4.075e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.050e+01, tolerance: 4.583e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.254e+01, tolerance: 3.985e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.180e+01, tolerance: 5.497e-02
  model = cd_fast.enet_coordinate_descent(

Fold 4
Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.084e+01, tolerance: 4.044e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 15:42:04,404] Trial 8 finished with value: 0.4300370834108791 and parameters: {'alpha': 0.0020742889456876012, 'l1_ratio': 0.9225747591003884}. Best is trial 7 with value: 0.4608809023746705.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:42:04,622] Trial 9 finished with value: 0.4433301135174075 and parameters: {'alpha': 0.042086867272072066, 'l1_ratio': 0.5773240638159155}. Best is trial 7 with value: 0.4608809023746705.
[I 2025-09-04 15:42:04,796] Trial 10 finished with value: 0.15062002530802132 and parameters: {'alpha': 0.9201768319232335, 'l1_ratio': 0.8264360322258447}. Best is trial 7 with value: 0.4608809023746705.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1

[I 2025-09-04 15:42:04,943] Trial 11 finished with value: 0.4678768991241923 and parameters: {'alpha': 0.017863249284638495, 'l1_ratio': 0.6873662172599657}. Best is trial 11 with value: 0.4678768991241923.

Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.951e-02, tolerance: 3.985e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 15:42:05,120] Trial 12 finished with value: 0.4634416054118847 and parameters: {'alpha': 0.011105032785913274, 'l1_ratio': 0.7765514989976754}. Best is trial 11 with value: 0.4678768991241923.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.447e-01, tolerance: 4.075e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.151e+00, tolerance: 4.583e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.979e+00, tolerance: 3.985e-02
  model = cd_fast.enet_coordinate_descent(

Fold 4
Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.406e-01, tolerance: 5.497e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.055e-02, tolerance: 4.044e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 15:42:05,302] Trial 13 finished with value: 0.4493867273894012 and parameters: {'alpha': 0.008385524688552725, 'l1_ratio': 0.40316435204758294}. Best is trial 11 with value: 0.4678768991241923.
[I 2025-09-04 15:42:05,446] Trial 14 finished with value: 0.35829272001055845 and parameters: {'alpha': 0.12059332850216806, 'l1_ratio': 0.7832765290807305}. Best is trial 11 with value: 0.4678768991241923.

Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.184e-01, tolerance: 4.075e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.438e-01, tolerance: 4.583e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.257e+00, tolerance: 3.985e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.222e-01, tolerance: 5.497e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 15:42:05,625] Trial 15 finished with value: 0.44827070919674883 and parameters: {'alpha': 0.009232909913333224, 'l1_ratio': 0.4585236571724943}. Best is trial 11 with value: 0.4678768991241923.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.276e+01, tolerance: 4.075e-02
  model = cd_fast.enet_coordinate_descent(

Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.669e+01, tolerance: 4.583e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.036e+01, tolerance: 3.985e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.259e+01, tolerance: 5.497e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.946e+01, tolerance: 4.044e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 15:42:05,790] Trial 16 finished with value: 0.4381619866409846 and parameters: {'alpha': 0.000759318338080569, 'l1_ratio': 0.8476057020041216}. Best is trial 11 with value: 0.4678768991241923.

Fold 3
Fold 4
Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:42:05,920] Trial 17 finished with value: 0.4136066565277472 and parameters: {'alpha': 0.12696888863903774, 'l1_ratio': 0.3163179224902251}. Best is trial 11 with value: 0.4678768991241923.
[I 2025-09-04 15:42:06,115] Trial 18 finished with value: 0.4674707414012478 and parameters: {'alpha': 0.01926283956951943, 'l1_ratio': 0.699290783687262}. Best is trial 11 with value: 0.4678768991241923.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===

[I 2025-09-04 15:42:06,252] Trial 19 finished with value: 0.46191122670455564 and parameters: {'alpha': 0.0251836921903143, 'l1_ratio': 0.5428150203235689}. Best is trial 11 with value: 0.4678768991241923.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 15:42:06,399] Trial 20 finished with value: 0.38480456987060163 and parameters: {'alpha': 0.08883638433330313, 'l1_ratio': 0.688604235446193}. Best is trial 11 with value: 0.4678768991241923.

Fold 4
Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:42:06,542] Trial 21 finished with value: 0.4739601111403371 and parameters: {'alpha': 0.014403901229536019, 'l1_ratio': 0.9023438654300626}. Best is trial 21 with value: 0.4739601111403371.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.950e-01, tolerance: 4.075e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.246e-01, tolerance: 4.583e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.382e-01, tolerance: 3.985e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.602e-01, tolerance: 5.497e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.045e-01, tolerance: 4.044e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 15:42:06,706] Trial 22 finished with value: 0.41891543517719243 and parameters: {'alpha': 0.004805706687527261, 'l1_ratio': 0.8947148895097525}. Best is trial 21 with value: 0.4739601111403371.

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1
Fold 2

[I 2025-09-04 15:42:06,926] Trial 23 finished with value: 0.4716809052389602 and parameters: {'alpha': 0.01844434297054011, 'l1_ratio': 0.9754611858045912}. Best is trial 21 with value: 0.4739601111403371.

Fold 3
Fold 4
Fold 5

=== Procesando TOA_5x5_depth_in_3_4 ===
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.752e+01, tolerance: 4.075e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.243e+01, tolerance: 4.583e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.117e+01, tolerance: 3.985e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.130e+01, tolerance: 5.497e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.626e+01, tolerance: 4.044e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 15:42:07,150] Trial 24 finished with value: 0.4354625408019138 and parameters: {'alpha': 0.0012010301056845775, 'l1_ratio': 0.9866381762766533}. Best is trial 21 with value: 0.4739601111403371.
[I 2025-09-04 15:42:07,151] A new study created in memory with name: no-name-80c1cc78-357f-4b62-b435-a84d1ec06d1a

Fold 2
Fold 3
Fold 4
Fold 5

✅ ELN con TOA_5x5_depth_in_3_4 - Mejor R2: 0.47
📋 Parámetros: {'alpha': 0.014403901229536019, 'l1_ratio': 0.9023438654300626}

Buscando mejores hiperparámetros para XGB con C2X-Complex_rhow_5x5_depth_in_3_4...

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:42:12,826] Trial 0 finished with value: 0.6220278406785247 and parameters: {'n_estimators': 500, 'learning_rate': 0.02014036006514745, 'max_depth': 6, 'min_child_weight': 1, 'subsample': 0.7957489556898223, 'colsample_bytree': 0.7509721027855171}. Best is trial 0 with value: 0.6220278406785247.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:42:31,437] Trial 1 finished with value: 0.6321687931535889 and parameters: {'n_estimators': 2000, 'learning_rate': 0.009625894286758554, 'max_depth': 5, 'min_child_weight': 1, 'subsample': 0.8698646293923866, 'colsample_bytree': 0.9610009188214301}. Best is trial 1 with value: 0.6321687931535889.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:42:46,762] Trial 2 finished with value: 0.6290891037493029 and parameters: {'n_estimators': 1000, 'learning_rate': 0.008699559481185334, 'max_depth': 8, 'min_child_weight': 2, 'subsample': 0.9434202814371423, 'colsample_bytree': 0.6973521857373575}. Best is trial 1 with value: 0.6321687931535889.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:43:02,387] Trial 3 finished with value: 0.6390426885240381 and parameters: {'n_estimators': 2000, 'learning_rate': 0.03815230149734243, 'max_depth': 8, 'min_child_weight': 4, 'subsample': 0.6841252468069817, 'colsample_bytree': 0.6369396162908686}. Best is trial 3 with value: 0.6390426885240381.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:43:07,563] Trial 4 finished with value: 0.6265692073648235 and parameters: {'n_estimators': 500, 'learning_rate': 0.020987844431434744, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.8262162156626323, 'colsample_bytree': 0.7883888332727915}. Best is trial 3 with value: 0.6390426885240381.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:43:20,497] Trial 5 finished with value: 0.6197918243591725 and parameters: {'n_estimators': 2000, 'learning_rate': 0.04793683272187575, 'max_depth': 8, 'min_child_weight': 2, 'subsample': 0.8343944273590326, 'colsample_bytree': 0.8748460447717683}. Best is trial 3 with value: 0.6390426885240381.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:43:34,778] Trial 6 finished with value: 0.5967608633510271 and parameters: {'n_estimators': 1000, 'learning_rate': 0.032725996688937976, 'max_depth': 8, 'min_child_weight': 1, 'subsample': 0.9740566931446839, 'colsample_bytree': 0.9553963782842247}. Best is trial 3 with value: 0.6390426885240381.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:43:49,502] Trial 7 finished with value: 0.6172525301684588 and parameters: {'n_estimators': 2000, 'learning_rate': 0.033932236971281886, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.8963954755682974, 'colsample_bytree': 0.7177556132247915}. Best is trial 3 with value: 0.6390426885240381.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:43:53,982] Trial 8 finished with value: 0.6405800083150176 and parameters: {'n_estimators': 500, 'learning_rate': 0.012166471595769864, 'max_depth': 5, 'min_child_weight': 1, 'subsample': 0.7114511972138358, 'colsample_bytree': 0.9196649279881891}. Best is trial 8 with value: 0.6405800083150176.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:44:13,704] Trial 9 finished with value: 0.6325062674150025 and parameters: {'n_estimators': 2000, 'learning_rate': 0.006497185529495719, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.8909364110737481, 'colsample_bytree': 0.8870046145409924}. Best is trial 8 with value: 0.6405800083150176.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:44:16,902] Trial 10 finished with value: 0.6472714638705724 and parameters: {'n_estimators': 500, 'learning_rate': 0.01354573443457805, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.6251756067764738, 'colsample_bytree': 0.8628876080657897}. Best is trial 10 with value: 0.6472714638705724.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:44:19,992] Trial 11 finished with value: 0.6520666230324552 and parameters: {'n_estimators': 500, 'learning_rate': 0.012425066305437937, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.6060954968627603, 'colsample_bytree': 0.8672211273195061}. Best is trial 11 with value: 0.6520666230324552.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:44:23,179] Trial 12 finished with value: 0.6442750414712853 and parameters: {'n_estimators': 500, 'learning_rate': 0.015436013243198507, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.6000922393287579, 'colsample_bytree': 0.8393196539628901}. Best is trial 11 with value: 0.6520666230324552.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:44:27,300] Trial 13 finished with value: 0.6405841418268254 and parameters: {'n_estimators': 500, 'learning_rate': 0.00540042861316593, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.6015515110399707, 'colsample_bytree': 0.8266882607481053}. Best is trial 11 with value: 0.6520666230324552.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:44:30,790] Trial 14 finished with value: 0.63625931450762 and parameters: {'n_estimators': 500, 'learning_rate': 0.014279569861865724, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.6737838329843534, 'colsample_bytree': 0.7939236138067215}. Best is trial 11 with value: 0.6520666230324552.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:44:34,986] Trial 15 finished with value: 0.6360182115677631 and parameters: {'n_estimators': 500, 'learning_rate': 0.02174464033046962, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.7453649963268976, 'colsample_bytree': 0.8864052916180507}. Best is trial 11 with value: 0.6520666230324552.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:44:42,530] Trial 16 finished with value: 0.6391891998416558 and parameters: {'n_estimators': 1000, 'learning_rate': 0.009671581987074178, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.637096503545216, 'colsample_bytree': 0.9984590070865604}. Best is trial 11 with value: 0.6520666230324552.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:44:45,977] Trial 17 finished with value: 0.6298214028748033 and parameters: {'n_estimators': 500, 'learning_rate': 0.012606290488048292, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.7616360789191685, 'colsample_bytree': 0.8338170340270173}. Best is trial 11 with value: 0.6520666230324552.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:44:51,221] Trial 18 finished with value: 0.6446204985988966 and parameters: {'n_estimators': 500, 'learning_rate': 0.006902103942025561, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.6556837750226348, 'colsample_bytree': 0.9281075224005491}. Best is trial 11 with value: 0.6520666230324552.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:44:55,282] Trial 19 finished with value: 0.6332266496047405 and parameters: {'n_estimators': 500, 'learning_rate': 0.017859471611108874, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.710856157869155, 'colsample_bytree': 0.7498486313103409}. Best is trial 11 with value: 0.6520666230324552.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:45:01,462] Trial 20 finished with value: 0.6277361958890622 and parameters: {'n_estimators': 1000, 'learning_rate': 0.02760447046067909, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.6229756504879622, 'colsample_bytree': 0.8741410782885268}. Best is trial 11 with value: 0.6520666230324552.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:45:06,968] Trial 21 finished with value: 0.6487694540008915 and parameters: {'n_estimators': 500, 'learning_rate': 0.00771198757339076, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.6509956827246697, 'colsample_bytree': 0.9224657682470877}. Best is trial 11 with value: 0.6520666230324552.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:45:12,381] Trial 22 finished with value: 0.6523037110809834 and parameters: {'n_estimators': 500, 'learning_rate': 0.007889846245071235, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.6478799909895996, 'colsample_bytree': 0.9184042139949454}. Best is trial 22 with value: 0.6523037110809834.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:45:18,492] Trial 23 finished with value: 0.6387476305269344 and parameters: {'n_estimators': 500, 'learning_rate': 0.00768425900461401, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.7011610656599601, 'colsample_bytree': 0.9177330653352216}. Best is trial 22 with value: 0.6523037110809834.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:45:24,435] Trial 24 finished with value: 0.6343576479066085 and parameters: {'n_estimators': 500, 'learning_rate': 0.005022578636955435, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.7455738585322778, 'colsample_bytree': 0.9640243692095546}. Best is trial 22 with value: 0.6523037110809834.
[I 2025-09-04 15:45:24,436] A new study created in memory with name: no-name-cb44c84f-74a3-4b33-8995-509ccbf30bb5

✅ XGB con C2X-Complex_rhow_5x5_depth_in_3_4 - Mejor R2: 0.65
📋 Parámetros: {'n_estimators': 500, 'learning_rate': 0.007889846245071235, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.6478799909895996, 'colsample_bytree': 0.9184042139949454}

Buscando mejores hiperparámetros para LBM con C2X-Complex_rhow_5x5_depth_in_3_4...

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:45:26,001] Trial 0 finished with value: 0.6175957034801325 and parameters: {'learning_rate': 0.007988927798622664, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 6, 'subsample': 0.7167583446456123, 'colsample_bytree': 0.7778242652854729, 'n_estimators': 2000}. Best is trial 0 with value: 0.6175957034801325.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:45:27,389] Trial 1 finished with value: 0.5939645907875404 and parameters: {'learning_rate': 0.026138427427233536, 'num_leaves': 40, 'max_depth': 8, 'min_child_samples': 15, 'subsample': 0.6107768897825798, 'colsample_bytree': 0.8065118486871543, 'n_estimators': 2000}. Best is trial 0 with value: 0.6175957034801325.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 15:45:27,678] Trial 2 finished with value: 0.6061186140633599 and parameters: {'learning_rate': 0.03674411195311185, 'num_leaves': 40, 'max_depth': 5, 'min_child_samples': 15, 'subsample': 0.8356412309315479, 'colsample_bytree': 0.9358127197291436, 'n_estimators': 500}. Best is trial 0 with value: 0.6175957034801325.

Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:45:28,943] Trial 3 finished with value: 0.6052837084641903 and parameters: {'learning_rate': 0.006805731416196686, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 9, 'subsample': 0.7174236818729542, 'colsample_bytree': 0.8463120402481443, 'n_estimators': 2000}. Best is trial 0 with value: 0.6175957034801325.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 15:45:29,401] Trial 4 finished with value: 0.6355647980634613 and parameters: {'learning_rate': 0.00766031449419614, 'num_leaves': 40, 'max_depth': 8, 'min_child_samples': 10, 'subsample': 0.9621316184998785, 'colsample_bytree': 0.7537888111656339, 'n_estimators': 500}. Best is trial 4 with value: 0.6355647980634613.

Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:45:30,684] Trial 5 finished with value: 0.611201405089511 and parameters: {'learning_rate': 0.010606684755836156, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 15, 'subsample': 0.7241596817001972, 'colsample_bytree': 0.95918936963422, 'n_estimators': 2000}. Best is trial 4 with value: 0.6355647980634613.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 15:45:30,983] Trial 6 finished with value: 0.6120224837700714 and parameters: {'learning_rate': 0.007863902483001112, 'num_leaves': 60, 'max_depth': 5, 'min_child_samples': 15, 'subsample': 0.8267776575591208, 'colsample_bytree': 0.7519102956927732, 'n_estimators': 500}. Best is trial 4 with value: 0.6355647980634613.

Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:45:32,734] Trial 7 finished with value: 0.6107936166121943 and parameters: {'learning_rate': 0.01571784106425972, 'num_leaves': 80, 'max_depth': 7, 'min_child_samples': 4, 'subsample': 0.6468057625732235, 'colsample_bytree': 0.6083907743443016, 'n_estimators': 2000}. Best is trial 4 with value: 0.6355647980634613.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 15:45:33,015] Trial 8 finished with value: 0.6079743103827805 and parameters: {'learning_rate': 0.017246754213398545, 'num_leaves': 80, 'max_depth': 5, 'min_child_samples': 12, 'subsample': 0.9884913003208153, 'colsample_bytree': 0.6815093753081467, 'n_estimators': 500}. Best is trial 4 with value: 0.6355647980634613.

Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:45:33,719] Trial 9 finished with value: 0.6046697989004883 and parameters: {'learning_rate': 0.016616593264643625, 'num_leaves': 60, 'max_depth': 8, 'min_child_samples': 4, 'subsample': 0.9136430774163715, 'colsample_bytree': 0.8664940336701297, 'n_estimators': 500}. Best is trial 4 with value: 0.6355647980634613.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 15:45:34,566] Trial 10 finished with value: 0.6243586464756082 and parameters: {'learning_rate': 0.005271355410819458, 'num_leaves': 40, 'max_depth': 8, 'min_child_samples': 10, 'subsample': 0.9917119230089829, 'colsample_bytree': 0.7035036386892957, 'n_estimators': 1000}. Best is trial 4 with value: 0.6355647980634613.

Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:45:35,419] Trial 11 finished with value: 0.6273735474079418 and parameters: {'learning_rate': 0.005029274815849992, 'num_leaves': 40, 'max_depth': 8, 'min_child_samples': 10, 'subsample': 0.9939245561484579, 'colsample_bytree': 0.7011966884122177, 'n_estimators': 1000}. Best is trial 4 with value: 0.6355647980634613.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:45:36,346] Trial 12 finished with value: 0.6335509349176318 and parameters: {'learning_rate': 0.005056730389719877, 'num_leaves': 40, 'max_depth': 8, 'min_child_samples': 8, 'subsample': 0.8993193050230606, 'colsample_bytree': 0.6635581834455859, 'n_estimators': 1000}. Best is trial 4 with value: 0.6355647980634613.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 15:45:37,029] Trial 13 finished with value: 0.628773915454493 and parameters: {'learning_rate': 0.011047617669136459, 'num_leaves': 40, 'max_depth': 6, 'min_child_samples': 7, 'subsample': 0.9016211289358325, 'colsample_bytree': 0.621040465443065, 'n_estimators': 1000}. Best is trial 4 with value: 0.6355647980634613.

Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:45:37,707] Trial 14 finished with value: 0.5986355537647061 and parameters: {'learning_rate': 0.01083029710103854, 'num_leaves': 40, 'max_depth': 7, 'min_child_samples': 12, 'subsample': 0.899697115550918, 'colsample_bytree': 0.6694294832426346, 'n_estimators': 1000}. Best is trial 4 with value: 0.6355647980634613.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 15:45:38,278] Trial 15 finished with value: 0.6364961321585423 and parameters: {'learning_rate': 0.006617912473095984, 'num_leaves': 40, 'max_depth': 8, 'min_child_samples': 8, 'subsample': 0.9303188839872626, 'colsample_bytree': 0.7448045774739271, 'n_estimators': 500}. Best is trial 15 with value: 0.6364961321585423.

Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 15:45:38,670] Trial 16 finished with value: 0.5639867969024168 and parameters: {'learning_rate': 0.049403550339812925, 'num_leaves': 40, 'max_depth': 8, 'min_child_samples': 12, 'subsample': 0.9493341963404065, 'colsample_bytree': 0.7458483384720981, 'n_estimators': 500}. Best is trial 15 with value: 0.6364961321585423.

Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:45:39,182] Trial 17 finished with value: 0.6211704906454099 and parameters: {'learning_rate': 0.007015724785805886, 'num_leaves': 80, 'max_depth': 6, 'min_child_samples': 6, 'subsample': 0.8498095739649082, 'colsample_bytree': 0.8310151805414833, 'n_estimators': 500}. Best is trial 15 with value: 0.6364961321585423.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 15:45:39,576] Trial 18 finished with value: 0.6051223046981821 and parameters: {'learning_rate': 0.013063716659334793, 'num_leaves': 60, 'max_depth': 7, 'min_child_samples': 13, 'subsample': 0.779044076026174, 'colsample_bytree': 0.909555560856494, 'n_estimators': 500}. Best is trial 15 with value: 0.6364961321585423.

Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 15:45:40,015] Trial 19 finished with value: 0.6225373478949879 and parameters: {'learning_rate': 0.02304996543294367, 'num_leaves': 40, 'max_depth': 8, 'min_child_samples': 8, 'subsample': 0.9428806357701247, 'colsample_bytree': 0.7308562228631088, 'n_estimators': 500}. Best is trial 15 with value: 0.6364961321585423.

Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:45:40,422] Trial 20 finished with value: 0.6277329639031176 and parameters: {'learning_rate': 0.009110959123912223, 'num_leaves': 40, 'max_depth': 7, 'min_child_samples': 11, 'subsample': 0.8628029968625335, 'colsample_bytree': 0.7848069148816984, 'n_estimators': 500}. Best is trial 15 with value: 0.6364961321585423.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 15:45:41,305] Trial 21 finished with value: 0.6317396399033146 and parameters: {'learning_rate': 0.006075989942807627, 'num_leaves': 40, 'max_depth': 8, 'min_child_samples': 8, 'subsample': 0.9408299058410515, 'colsample_bytree': 0.6460307163534486, 'n_estimators': 1000}. Best is trial 15 with value: 0.6364961321585423.

Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:45:42,196] Trial 22 finished with value: 0.622559999543932 and parameters: {'learning_rate': 0.005889128210770469, 'num_leaves': 40, 'max_depth': 8, 'min_child_samples': 9, 'subsample': 0.8807339228571411, 'colsample_bytree': 0.7279736954718194, 'n_estimators': 1000}. Best is trial 15 with value: 0.6364961321585423.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 15:45:42,797] Trial 23 finished with value: 0.6283305200491267 and parameters: {'learning_rate': 0.008416630420851992, 'num_leaves': 40, 'max_depth': 8, 'min_child_samples': 6, 'subsample': 0.7968534475208934, 'colsample_bytree': 0.6462293818798217, 'n_estimators': 500}. Best is trial 15 with value: 0.6364961321585423.

Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:45:43,711] Trial 24 finished with value: 0.6311748139996305 and parameters: {'learning_rate': 0.006399353485884704, 'num_leaves': 40, 'max_depth': 8, 'min_child_samples': 8, 'subsample': 0.9614023024928982, 'colsample_bytree': 0.7685046799602278, 'n_estimators': 1000}. Best is trial 15 with value: 0.6364961321585423.
[I 2025-09-04 15:45:43,713] A new study created in memory with name: no-name-00d0770c-de4f-4be9-9281-9cc9583740eb

✅ LBM con C2X-Complex_rhow_5x5_depth_in_3_4 - Mejor R2: 0.64
📋 Parámetros: {'learning_rate': 0.006617912473095984, 'num_leaves': 40, 'max_depth': 8, 'min_child_samples': 8, 'subsample': 0.9303188839872626, 'colsample_bytree': 0.7448045774739271, 'n_estimators': 500}

Buscando mejores hiperparámetros para MLP con C2X-Complex_rhow_5x5_depth_in_3_4...

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:45:45,936] Trial 0 finished with value: 0.5840809544747299 and parameters: {'hidden_layer_sizes': '256_128', 'activation': 'relu', 'solver': 'adam', 'alpha': 1.1612992741166721e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.008370190962587771}. Best is trial 0 with value: 0.5840809544747299.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 15:45:46,903] Trial 1 finished with value: 0.5288918783950076 and parameters: {'hidden_layer_sizes': '256', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.009830871157575574, 'learning_rate': 'constant', 'learning_rate_init': 0.0004695932981342242}. Best is trial 0 with value: 0.5840809544747299.

Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

[I 2025-09-04 15:45:50,557] Trial 2 finished with value: 0.5666313941720439 and parameters: {'hidden_layer_sizes': '256', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 2.2652626568158258e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00029138995712864714}. Best is trial 0 with value: 0.5840809544747299.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 15:45:51,933] Trial 3 finished with value: 0.5907728788951401 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0009748622874409718, 'learning_rate': 'constant', 'learning_rate_init': 0.009678259959618074}. Best is trial 3 with value: 0.5907728788951401.

Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:45:53,733] Trial 4 finished with value: 0.5994683785230219 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.050070902142473374, 'learning_rate': 'constant', 'learning_rate_init': 0.006057834322354363}. Best is trial 4 with value: 0.5994683785230219.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

[I 2025-09-04 15:45:56,340] Trial 5 finished with value: 0.5294535979248995 and parameters: {'hidden_layer_sizes': '128', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.006120946806861249, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0001713766782056353}. Best is trial 4 with value: 0.5994683785230219.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-04 15:45:57,951] Trial 6 finished with value: 0.5399324954439785 and parameters: {'hidden_layer_sizes': '128', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.0008368442834043017, 'learning_rate': 'constant', 'learning_rate_init': 0.00014079244009624462}. Best is trial 4 with value: 0.5994683785230219.

Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

[I 2025-09-04 15:46:01,679] Trial 7 finished with value: 0.5495141752211121 and parameters: {'hidden_layer_sizes': '256', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 4.0772409441779874e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00010731460730282062}. Best is trial 4 with value: 0.5994683785230219.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

[I 2025-09-04 15:46:04,071] Trial 8 finished with value: 0.573561582576988 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'adam', 'alpha': 5.7813314294973175e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.0001480511015952772}. Best is trial 4 with value: 0.5994683785230219.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

[I 2025-09-04 15:46:07,516] Trial 9 finished with value: 0.5868615358482645 and parameters: {'hidden_layer_sizes': '256', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.0001772984625522707, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0017607052609044593}. Best is trial 4 with value: 0.5994683785230219.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:46:09,234] Trial 10 finished with value: 0.5867073233111864 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.07354727782138089, 'learning_rate': 'constant', 'learning_rate_init': 0.0026813409147191294}. Best is trial 4 with value: 0.5994683785230219.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:46:10,791] Trial 11 finished with value: 0.5730476135923608 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0013975479780067432, 'learning_rate': 'constant', 'learning_rate_init': 0.008635678564211227}. Best is trial 4 with value: 0.5994683785230219.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:46:12,509] Trial 12 finished with value: 0.5737292082103216 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.08663332486701364, 'learning_rate': 'constant', 'learning_rate_init': 0.004020294646401091}. Best is trial 4 with value: 0.5994683785230219.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:46:14,294] Trial 13 finished with value: 0.5721258428569402 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.011260614542787994, 'learning_rate': 'constant', 'learning_rate_init': 0.004006283384192828}. Best is trial 4 with value: 0.5994683785230219.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:46:18,130] Trial 14 finished with value: 0.6089198464458792 and parameters: {'hidden_layer_sizes': '256_128', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0006512333797561627, 'learning_rate': 'constant', 'learning_rate_init': 0.0009560973305891154}. Best is trial 14 with value: 0.6089198464458792.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:46:21,505] Trial 15 finished with value: 0.6005880327331437 and parameters: {'hidden_layer_sizes': '256_128', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.00022095415474035303, 'learning_rate': 'constant', 'learning_rate_init': 0.0009027133410121017}. Best is trial 14 with value: 0.6089198464458792.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:46:24,350] Trial 16 finished with value: 0.610354821472201 and parameters: {'hidden_layer_sizes': '256_128', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0002929107993248779, 'learning_rate': 'constant', 'learning_rate_init': 0.0008059712275958755}. Best is trial 16 with value: 0.610354821472201.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:46:28,122] Trial 17 finished with value: 0.6244214378050149 and parameters: {'hidden_layer_sizes': '256_128', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.00022349322880297348, 'learning_rate': 'constant', 'learning_rate_init': 0.0010891925952260532}. Best is trial 17 with value: 0.6244214378050149.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:46:30,712] Trial 18 finished with value: 0.640252117037317 and parameters: {'hidden_layer_sizes': '256_128', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.00017935849868288794, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0005654534094318303}. Best is trial 18 with value: 0.640252117037317.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:46:33,234] Trial 19 finished with value: 0.6422600399542931 and parameters: {'hidden_layer_sizes': '256_128', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.00010577527300457577, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0005651942380761769}. Best is trial 19 with value: 0.6422600399542931.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:46:35,811] Trial 20 finished with value: 0.6420579874402093 and parameters: {'hidden_layer_sizes': '256_128', 'activation': 'relu', 'solver': 'adam', 'alpha': 7.584157765488026e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00046595742026147506}. Best is trial 19 with value: 0.6422600399542931.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:46:38,923] Trial 21 finished with value: 0.6566662114082427 and parameters: {'hidden_layer_sizes': '256_128', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.00010236429010965995, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0003651197409167566}. Best is trial 21 with value: 0.6566662114082427.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:46:42,115] Trial 22 finished with value: 0.6561455610693583 and parameters: {'hidden_layer_sizes': '256_128', 'activation': 'relu', 'solver': 'adam', 'alpha': 6.154927862466267e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0003161721770293714}. Best is trial 21 with value: 0.6566662114082427.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:46:45,414] Trial 23 finished with value: 0.6551810248450839 and parameters: {'hidden_layer_sizes': '256_128', 'activation': 'relu', 'solver': 'adam', 'alpha': 8.910460372753497e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0002862304092126889}. Best is trial 21 with value: 0.6566662114082427.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:46:48,784] Trial 24 finished with value: 0.6481820884004803 and parameters: {'hidden_layer_sizes': '256_128', 'activation': 'relu', 'solver': 'adam', 'alpha': 2.5408745687347432e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0002632001540165086}. Best is trial 21 with value: 0.6566662114082427.
[I 2025-09-04 15:46:48,786] A new study created in memory with name: no-name-891ab6a5-ede1-435c-9ca8-d121e5a8fae2
[I 2025-09-04 15:46:48,910] Trial 0 finished with value: 0.2668458677368917 and parameters: {'C': 0.16656416668215804, 'epsilon': 0.17777509125123864}. Best is trial 0 with value: 0.2668458677368917.

✅ MLP con C2X-Complex_rhow_5x5_depth_in_3_4 - Mejor R2: 0.66
📋 Parámetros: {'hidden_layer_sizes': '256_128', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.00010236429010965995, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0003651197409167566}

Buscando mejores hiperparámetros para SVR con C2X-Complex_rhow_5x5_depth_in_3_4...

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:46:48,995] Trial 1 finished with value: 0.38075033883571896 and parameters: {'C': 0.5707367393241335, 'epsilon': 0.15910143125613377}. Best is trial 1 with value: 0.38075033883571896.
[I 2025-09-04 15:46:49,086] Trial 2 finished with value: 0.5111401551291845 and parameters: {'C': 2.746448449682671, 'epsilon': 0.18822144380576258}. Best is trial 2 with value: 0.5111401551291845.
[I 2025-09-04 15:46:49,179] Trial 3 finished with value: 0.4520521691027519 and parameters: {'C': 1.5270368310854348, 'epsilon': 0.018051580588589668}. Best is trial 2 with value: 0.5111401551291845.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2

[I 2025-09-04 15:46:49,262] Trial 4 finished with value: 0.23483214100860417 and parameters: {'C': 0.12394838302316255, 'epsilon': 0.1874426243618914}. Best is trial 2 with value: 0.5111401551291845.
[I 2025-09-04 15:46:49,360] Trial 5 finished with value: 0.49413114795352775 and parameters: {'C': 3.1510931981515014, 'epsilon': 0.027130446334411258}. Best is trial 2 with value: 0.5111401551291845.

Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 15:46:49,447] Trial 6 finished with value: 0.28866972534630064 and parameters: {'C': 0.2215533036685858, 'epsilon': 0.1119431886887354}. Best is trial 2 with value: 0.5111401551291845.
[I 2025-09-04 15:46:49,534] Trial 7 finished with value: 0.2730900860440948 and parameters: {'C': 0.189404433144418, 'epsilon': 0.13335686207157874}. Best is trial 2 with value: 0.5111401551291845.
[I 2025-09-04 15:46:49,621] Trial 8 finished with value: 0.36050180636297824 and parameters: {'C': 0.5533261095704592, 'epsilon': 0.03554925644452005}. Best is trial 2 with value: 0.5111401551291845.

Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1

[I 2025-09-04 15:46:49,718] Trial 9 finished with value: 0.5349517332085139 and parameters: {'C': 8.114049523059164, 'epsilon': 0.13707471172834945}. Best is trial 9 with value: 0.5349517332085139.
[I 2025-09-04 15:46:49,823] Trial 10 finished with value: 0.5192580753069383 and parameters: {'C': 6.8574380180795345, 'epsilon': 0.08163066183040713}. Best is trial 9 with value: 0.5349517332085139.

Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1

[I 2025-09-04 15:46:49,932] Trial 11 finished with value: 0.5224742376191065 and parameters: {'C': 9.783847241865509, 'epsilon': 0.07087959799034832}. Best is trial 9 with value: 0.5349517332085139.
[I 2025-09-04 15:46:50,042] Trial 12 finished with value: 0.5223822946205023 and parameters: {'C': 9.181186714568799, 'epsilon': 0.07467048965156807}. Best is trial 9 with value: 0.5349517332085139.

Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1

[I 2025-09-04 15:46:50,149] Trial 13 finished with value: 0.5067981174344998 and parameters: {'C': 4.551724585618252, 'epsilon': 0.06930211086771249}. Best is trial 9 with value: 0.5349517332085139.
[I 2025-09-04 15:46:50,251] Trial 14 finished with value: 0.5373751436011396 and parameters: {'C': 9.555509499241047, 'epsilon': 0.13134472658792118}. Best is trial 14 with value: 0.5373751436011396.

Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1

[I 2025-09-04 15:46:50,344] Trial 15 finished with value: 0.4619485520571701 and parameters: {'C': 1.5253275489727467, 'epsilon': 0.13782720802676995}. Best is trial 14 with value: 0.5373751436011396.
[I 2025-09-04 15:46:50,444] Trial 16 finished with value: 0.5146295938529875 and parameters: {'C': 4.84125133760899, 'epsilon': 0.11331224056848066}. Best is trial 14 with value: 0.5373751436011396.

Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2

[I 2025-09-04 15:46:50,543] Trial 17 finished with value: 0.498201551628363 and parameters: {'C': 2.3517606742749466, 'epsilon': 0.1551298636367237}. Best is trial 14 with value: 0.5373751436011396.
[I 2025-09-04 15:46:50,661] Trial 18 finished with value: 0.5231011285697478 and parameters: {'C': 5.276462251004784, 'epsilon': 0.13431257055223517}. Best is trial 14 with value: 0.5373751436011396.

Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2

[I 2025-09-04 15:46:50,759] Trial 19 finished with value: 0.4259484813094647 and parameters: {'C': 0.9380175359326376, 'epsilon': 0.09064007687787833}. Best is trial 14 with value: 0.5373751436011396.
[I 2025-09-04 15:46:50,856] Trial 20 finished with value: 0.3406595884570348 and parameters: {'C': 0.3619337315726821, 'epsilon': 0.16032821175581025}. Best is trial 14 with value: 0.5373751436011396.

Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 15:46:50,953] Trial 21 finished with value: 0.5259500758267509 and parameters: {'C': 5.529445389093075, 'epsilon': 0.137279624217293}. Best is trial 14 with value: 0.5373751436011396.
[I 2025-09-04 15:46:51,054] Trial 22 finished with value: 0.5265949861836478 and parameters: {'C': 6.723466575401383, 'epsilon': 0.12055617573085198}. Best is trial 14 with value: 0.5373751436011396.

Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 15:46:51,160] Trial 23 finished with value: 0.525963038192274 and parameters: {'C': 7.852203921160122, 'epsilon': 0.09755127802681782}. Best is trial 14 with value: 0.5373751436011396.
[I 2025-09-04 15:46:51,261] Trial 24 finished with value: 0.5083099713872984 and parameters: {'C': 3.600967531657833, 'epsilon': 0.1193995299071052}. Best is trial 14 with value: 0.5373751436011396.
[I 2025-09-04 15:46:51,262] A new study created in memory with name: no-name-96b9d5bb-32f2-47d9-b290-9a0962fdc515

Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

✅ SVR con C2X-Complex_rhow_5x5_depth_in_3_4 - Mejor R2: 0.54
📋 Parámetros: {'C': 9.555509499241047, 'epsilon': 0.13134472658792118}

Buscando mejores hiperparámetros para KNN con C2X-Complex_rhow_5x5_depth_in_3_4...

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:46:51,332] Trial 0 finished with value: 0.5872908785487387 and parameters: {'n_neighbors': 8, 'leaf_size': 15}. Best is trial 0 with value: 0.5872908785487387.
[I 2025-09-04 15:46:51,407] Trial 1 finished with value: 0.5348633090050605 and parameters: {'n_neighbors': 4, 'leaf_size': 13}. Best is trial 0 with value: 0.5872908785487387.
[I 2025-09-04 15:46:51,476] Trial 2 finished with value: 0.588028384533924 and parameters: {'n_neighbors': 10, 'leaf_size': 40}. Best is trial 2 with value: 0.588028384533924.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:46:51,545] Trial 3 finished with value: 0.582156706443909 and parameters: {'n_neighbors': 9, 'leaf_size': 15}. Best is trial 2 with value: 0.588028384533924.
[I 2025-09-04 15:46:51,627] Trial 4 finished with value: 0.5745469605021682 and parameters: {'n_neighbors': 7, 'leaf_size': 15}. Best is trial 2 with value: 0.588028384533924.
[I 2025-09-04 15:46:51,698] Trial 5 finished with value: 0.588028384533924 and parameters: {'n_neighbors': 10, 'leaf_size': 27}. Best is trial 2 with value: 0.588028384533924.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 15:46:51,770] Trial 6 finished with value: 0.5348633090050605 and parameters: {'n_neighbors': 4, 'leaf_size': 30}. Best is trial 2 with value: 0.588028384533924.
[I 2025-09-04 15:46:51,847] Trial 7 finished with value: 0.5530991414044777 and parameters: {'n_neighbors': 5, 'leaf_size': 40}. Best is trial 2 with value: 0.588028384533924.
[I 2025-09-04 15:46:51,918] Trial 8 finished with value: 0.5530991414044777 and parameters: {'n_neighbors': 5, 'leaf_size': 17}. Best is trial 2 with value: 0.588028384533924.

Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 15:46:51,990] Trial 9 finished with value: 0.582156706443909 and parameters: {'n_neighbors': 9, 'leaf_size': 18}. Best is trial 2 with value: 0.588028384533924.
[I 2025-09-04 15:46:52,096] Trial 10 finished with value: 0.588028384533924 and parameters: {'n_neighbors': 10, 'leaf_size': 40}. Best is trial 2 with value: 0.588028384533924.

Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:46:52,172] Trial 11 finished with value: 0.588028384533924 and parameters: {'n_neighbors': 10, 'leaf_size': 30}. Best is trial 2 with value: 0.588028384533924.
[I 2025-09-04 15:46:52,253] Trial 12 finished with value: 0.5872908785487387 and parameters: {'n_neighbors': 8, 'leaf_size': 33}. Best is trial 2 with value: 0.588028384533924.
[I 2025-09-04 15:46:52,332] Trial 13 finished with value: 0.588028384533924 and parameters: {'n_neighbors': 10, 'leaf_size': 23}. Best is trial 2 with value: 0.588028384533924.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 15:46:52,416] Trial 14 finished with value: 0.5745469605021682 and parameters: {'n_neighbors': 7, 'leaf_size': 24}. Best is trial 2 with value: 0.588028384533924.
[I 2025-09-04 15:46:52,500] Trial 15 finished with value: 0.582156706443909 and parameters: {'n_neighbors': 9, 'leaf_size': 35}. Best is trial 2 with value: 0.588028384533924.
[I 2025-09-04 15:46:52,576] Trial 16 finished with value: 0.5872908785487387 and parameters: {'n_neighbors': 8, 'leaf_size': 10}. Best is trial 2 with value: 0.588028384533924.

Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===

[I 2025-09-04 15:46:52,659] Trial 17 finished with value: 0.5689933482715699 and parameters: {'n_neighbors': 6, 'leaf_size': 28}. Best is trial 2 with value: 0.588028384533924.
[I 2025-09-04 15:46:52,741] Trial 18 finished with value: 0.5058637628036635 and parameters: {'n_neighbors': 3, 'leaf_size': 36}. Best is trial 2 with value: 0.588028384533924.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 15:46:52,825] Trial 19 finished with value: 0.588028384533924 and parameters: {'n_neighbors': 10, 'leaf_size': 20}. Best is trial 2 with value: 0.588028384533924.
[I 2025-09-04 15:46:52,912] Trial 20 finished with value: 0.582156706443909 and parameters: {'n_neighbors': 9, 'leaf_size': 26}. Best is trial 2 with value: 0.588028384533924.
[I 2025-09-04 15:46:52,994] Trial 21 finished with value: 0.588028384533924 and parameters: {'n_neighbors': 10, 'leaf_size': 40}. Best is trial 2 with value: 0.588028384533924.

Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===

[I 2025-09-04 15:46:53,083] Trial 22 finished with value: 0.588028384533924 and parameters: {'n_neighbors': 10, 'leaf_size': 38}. Best is trial 2 with value: 0.588028384533924.
[I 2025-09-04 15:46:53,169] Trial 23 finished with value: 0.582156706443909 and parameters: {'n_neighbors': 9, 'leaf_size': 33}. Best is trial 2 with value: 0.588028384533924.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 15:46:53,260] Trial 24 finished with value: 0.5872908785487387 and parameters: {'n_neighbors': 8, 'leaf_size': 37}. Best is trial 2 with value: 0.588028384533924.
[I 2025-09-04 15:46:53,262] A new study created in memory with name: no-name-e16defb7-a9c5-470e-b97d-f42d217ec957
[I 2025-09-04 15:46:53,349] Trial 0 finished with value: 0.5476927875769353 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 0 with value: 0.5476927875769353.

Fold 4
Fold 5

✅ KNN con C2X-Complex_rhow_5x5_depth_in_3_4 - Mejor R2: 0.59
📋 Parámetros: {'n_neighbors': 10, 'leaf_size': 40}

Buscando mejores hiperparámetros para LR con C2X-Complex_rhow_5x5_depth_in_3_4...

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:46:53,441] Trial 1 finished with value: 0.41787477707023557 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 0 with value: 0.5476927875769353.
[I 2025-09-04 15:46:53,552] Trial 2 finished with value: 0.5476927875769353 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 0 with value: 0.5476927875769353.
[I 2025-09-04 15:46:53,639] Trial 3 finished with value: 0.41787477707023557 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 0 with value: 0.5476927875769353.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1

[I 2025-09-04 15:46:53,746] Trial 4 finished with value: 0.4178747770667727 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 0 with value: 0.5476927875769353.

Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:46:53,863] Trial 5 finished with value: 0.41787477707023557 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 0 with value: 0.5476927875769353.
[I 2025-09-04 15:46:53,963] Trial 6 finished with value: 0.5476927875769353 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 0 with value: 0.5476927875769353.
[I 2025-09-04 15:46:54,034] Trial 7 finished with value: 0.5476927875769353 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 0 with value: 0.5476927875769353.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2

[I 2025-09-04 15:46:54,156] Trial 8 finished with value: 0.4178747770667727 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 0 with value: 0.5476927875769353.
[I 2025-09-04 15:46:54,259] Trial 9 finished with value: 0.5476354440733234 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: 0.5476927875769353.

Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1

[I 2025-09-04 15:46:54,334] Trial 10 finished with value: 0.5476927875769353 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 0 with value: 0.5476927875769353.
[I 2025-09-04 15:46:54,408] Trial 11 finished with value: 0.5476927875769353 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 0 with value: 0.5476927875769353.
[I 2025-09-04 15:46:54,475] Trial 12 finished with value: 0.5476927875769353 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 0 with value: 0.5476927875769353.

Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===

[I 2025-09-04 15:46:54,545] Trial 13 finished with value: 0.5476927875769353 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 0 with value: 0.5476927875769353.
[I 2025-09-04 15:46:54,628] Trial 14 finished with value: 0.5476927875769353 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 0 with value: 0.5476927875769353.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:46:54,697] Trial 15 finished with value: 0.5476927875769353 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 0 with value: 0.5476927875769353.
[I 2025-09-04 15:46:54,787] Trial 16 finished with value: 0.5476927875769353 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 0 with value: 0.5476927875769353.
[I 2025-09-04 15:46:54,863] Trial 17 finished with value: 0.5476927875769353 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 0 with value: 0.5476927875769353.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 15:46:54,936] Trial 18 finished with value: 0.5476354440733234 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: 0.5476927875769353.
[I 2025-09-04 15:46:55,011] Trial 19 finished with value: 0.5476927875769353 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 0 with value: 0.5476927875769353.
[I 2025-09-04 15:46:55,079] Trial 20 finished with value: 0.5476927875769353 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 0 with value: 0.5476927875769353.

Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2

[I 2025-09-04 15:46:55,154] Trial 21 finished with value: 0.5476927875769353 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 0 with value: 0.5476927875769353.
[I 2025-09-04 15:46:55,226] Trial 22 finished with value: 0.5476927875769353 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 0 with value: 0.5476927875769353.
[I 2025-09-04 15:46:55,295] Trial 23 finished with value: 0.5476927875769353 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 0 with value: 0.5476927875769353.

Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1

[I 2025-09-04 15:46:55,372] Trial 24 finished with value: 0.5476927875769353 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 0 with value: 0.5476927875769353.
[I 2025-09-04 15:46:55,373] A new study created in memory with name: no-name-07a6d652-010c-4016-9c7d-4a5ff61513f3

Fold 2
Fold 3
Fold 4
Fold 5

✅ LR con C2X-Complex_rhow_5x5_depth_in_3_4 - Mejor R2: 0.55
📋 Parámetros: {'fit_intercept': False, 'positive': True}

Buscando mejores hiperparámetros para RF con C2X-Complex_rhow_5x5_depth_in_3_4...

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:46:58,191] Trial 0 finished with value: 0.5394836252424929 and parameters: {'n_estimators': 100, 'max_depth': 8, 'min_samples_split': 8, 'min_samples_leaf': 4, 'bootstrap': False}. Best is trial 0 with value: 0.5394836252424929.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:47:01,627] Trial 1 finished with value: 0.5368329651429082 and parameters: {'n_estimators': 100, 'max_depth': 15, 'min_samples_split': 8, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 0 with value: 0.5394836252424929.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:47:08,638] Trial 2 finished with value: 0.6496505298462085 and parameters: {'n_estimators': 300, 'max_depth': 9, 'min_samples_split': 3, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 2 with value: 0.6496505298462085.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:47:10,835] Trial 3 finished with value: 0.6446259659003283 and parameters: {'n_estimators': 100, 'max_depth': 10, 'min_samples_split': 8, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 2 with value: 0.6496505298462085.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:47:13,281] Trial 4 finished with value: 0.5640245293253738 and parameters: {'n_estimators': 100, 'max_depth': 6, 'min_samples_split': 6, 'min_samples_leaf': 5, 'bootstrap': False}. Best is trial 2 with value: 0.6496505298462085.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:47:15,401] Trial 5 finished with value: 0.6387880375334767 and parameters: {'n_estimators': 100, 'max_depth': 15, 'min_samples_split': 8, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 2 with value: 0.6496505298462085.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:47:26,654] Trial 6 finished with value: 0.6506706140331338 and parameters: {'n_estimators': 500, 'max_depth': 14, 'min_samples_split': 4, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 6 with value: 0.6506706140331338.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:47:37,517] Trial 7 finished with value: 0.6379560496716212 and parameters: {'n_estimators': 500, 'max_depth': 14, 'min_samples_split': 9, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 6 with value: 0.6506706140331338.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:47:48,613] Trial 8 finished with value: 0.5233345537778499 and parameters: {'n_estimators': 300, 'max_depth': 10, 'min_samples_split': 2, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 6 with value: 0.6506706140331338.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:47:56,926] Trial 9 finished with value: 0.5417065854880978 and parameters: {'n_estimators': 300, 'max_depth': 13, 'min_samples_split': 3, 'min_samples_leaf': 5, 'bootstrap': False}. Best is trial 6 with value: 0.6506706140331338.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:48:07,077] Trial 10 finished with value: 0.6468002058599931 and parameters: {'n_estimators': 500, 'max_depth': 12, 'min_samples_split': 5, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 6 with value: 0.6506706140331338.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:48:13,312] Trial 11 finished with value: 0.6466402156042503 and parameters: {'n_estimators': 300, 'max_depth': 8, 'min_samples_split': 4, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 6 with value: 0.6506706140331338.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:48:24,435] Trial 12 finished with value: 0.6510738970572885 and parameters: {'n_estimators': 500, 'max_depth': 12, 'min_samples_split': 2, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 12 with value: 0.6510738970572885.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:48:34,523] Trial 13 finished with value: 0.6468002058599931 and parameters: {'n_estimators': 500, 'max_depth': 12, 'min_samples_split': 4, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 12 with value: 0.6510738970572885.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:48:45,632] Trial 14 finished with value: 0.6510738970572885 and parameters: {'n_estimators': 500, 'max_depth': 12, 'min_samples_split': 2, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 12 with value: 0.6510738970572885.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:48:56,726] Trial 15 finished with value: 0.6510738970572885 and parameters: {'n_estimators': 500, 'max_depth': 12, 'min_samples_split': 2, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 12 with value: 0.6510738970572885.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:49:06,777] Trial 16 finished with value: 0.646914272046383 and parameters: {'n_estimators': 500, 'max_depth': 11, 'min_samples_split': 2, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 12 with value: 0.6510738970572885.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:49:16,158] Trial 17 finished with value: 0.6398768146231316 and parameters: {'n_estimators': 500, 'max_depth': 11, 'min_samples_split': 6, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 12 with value: 0.6510738970572885.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:49:24,088] Trial 18 finished with value: 0.6419804352908973 and parameters: {'n_estimators': 500, 'max_depth': 5, 'min_samples_split': 3, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 12 with value: 0.6510738970572885.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:49:34,842] Trial 19 finished with value: 0.6483620220513631 and parameters: {'n_estimators': 500, 'max_depth': 13, 'min_samples_split': 6, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 12 with value: 0.6510738970572885.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:49:43,980] Trial 20 finished with value: 0.6317471301552533 and parameters: {'n_estimators': 500, 'max_depth': 10, 'min_samples_split': 10, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 12 with value: 0.6510738970572885.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:49:55,106] Trial 21 finished with value: 0.6510738970572885 and parameters: {'n_estimators': 500, 'max_depth': 12, 'min_samples_split': 2, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 12 with value: 0.6510738970572885.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:50:06,270] Trial 22 finished with value: 0.6504901589030339 and parameters: {'n_estimators': 500, 'max_depth': 13, 'min_samples_split': 2, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 12 with value: 0.6510738970572885.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:50:17,403] Trial 23 finished with value: 0.6509476725313785 and parameters: {'n_estimators': 500, 'max_depth': 11, 'min_samples_split': 3, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 12 with value: 0.6510738970572885.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:50:27,474] Trial 24 finished with value: 0.6464807740418644 and parameters: {'n_estimators': 500, 'max_depth': 14, 'min_samples_split': 5, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 12 with value: 0.6510738970572885.
[I 2025-09-04 15:50:27,475] A new study created in memory with name: no-name-ee8c0dea-dd0d-459f-9fb5-3aa563859c6a

✅ RF con C2X-Complex_rhow_5x5_depth_in_3_4 - Mejor R2: 0.65
📋 Parámetros: {'n_estimators': 500, 'max_depth': 12, 'min_samples_split': 2, 'min_samples_leaf': 2, 'bootstrap': True}

Buscando mejores hiperparámetros para CAT con C2X-Complex_rhow_5x5_depth_in_3_4...

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:51:12,190] Trial 0 finished with value: 0.6038714145899664 and parameters: {'iterations': 2000, 'learning_rate': 0.010314614884643513, 'depth': 7, 'l2_leaf_reg': 1.7796655248928464}. Best is trial 0 with value: 0.6038714145899664.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:51:38,215] Trial 1 finished with value: 0.597097235678002 and parameters: {'iterations': 500, 'learning_rate': 0.010489150261202828, 'depth': 8, 'l2_leaf_reg': 4.631670650108396}. Best is trial 0 with value: 0.6038714145899664.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:51:42,077] Trial 2 finished with value: 0.5938972114197281 and parameters: {'iterations': 1000, 'learning_rate': 0.038494547277772524, 'depth': 4, 'l2_leaf_reg': 1.8611688178447885}. Best is trial 0 with value: 0.6038714145899664.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:51:44,888] Trial 3 finished with value: 0.6244051420102302 and parameters: {'iterations': 500, 'learning_rate': 0.019447396593227428, 'depth': 5, 'l2_leaf_reg': 4.399408221219479}. Best is trial 3 with value: 0.6244051420102302.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:58:33,580] Trial 4 finished with value: 0.5896532582997411 and parameters: {'iterations': 2000, 'learning_rate': 0.012623924149062323, 'depth': 10, 'l2_leaf_reg': 2.3185369768178328}. Best is trial 3 with value: 0.6244051420102302.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:58:41,580] Trial 5 finished with value: 0.6050981486718967 and parameters: {'iterations': 2000, 'learning_rate': 0.015768765101571873, 'depth': 4, 'l2_leaf_reg': 2.2408409651476515}. Best is trial 3 with value: 0.6244051420102302.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 15:59:03,940] Trial 6 finished with value: 0.610726418150644 and parameters: {'iterations': 1000, 'learning_rate': 0.012863840983137233, 'depth': 7, 'l2_leaf_reg': 2.3686113612740103}. Best is trial 3 with value: 0.6244051420102302.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:00:53,646] Trial 7 finished with value: 0.5976657978825426 and parameters: {'iterations': 1000, 'learning_rate': 0.04437929963125357, 'depth': 9, 'l2_leaf_reg': 4.350229457241975}. Best is trial 3 with value: 0.6244051420102302.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:01:12,892] Trial 8 finished with value: 0.6120374577925667 and parameters: {'iterations': 1000, 'learning_rate': 0.016911034861065086, 'depth': 7, 'l2_leaf_reg': 4.708906977843277}. Best is trial 3 with value: 0.6244051420102302.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:04:27,034] Trial 9 finished with value: 0.5891545040016537 and parameters: {'iterations': 1000, 'learning_rate': 0.03750095904097622, 'depth': 10, 'l2_leaf_reg': 3.9408576846540186}. Best is trial 3 with value: 0.6244051420102302.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:04:29,618] Trial 10 finished with value: 0.6052204541609323 and parameters: {'iterations': 500, 'learning_rate': 0.0729647885625355, 'depth': 5, 'l2_leaf_reg': 5.891657349409947}. Best is trial 3 with value: 0.6244051420102302.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:04:33,572] Trial 11 finished with value: 0.6169466211859387 and parameters: {'iterations': 500, 'learning_rate': 0.021187747818971765, 'depth': 6, 'l2_leaf_reg': 5.277163946385873}. Best is trial 3 with value: 0.6244051420102302.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:04:37,790] Trial 12 finished with value: 0.622365814391328 and parameters: {'iterations': 500, 'learning_rate': 0.02424314111093553, 'depth': 6, 'l2_leaf_reg': 5.607324171999528}. Best is trial 3 with value: 0.6244051420102302.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:04:40,626] Trial 13 finished with value: 0.6160167562394598 and parameters: {'iterations': 500, 'learning_rate': 0.024533547782440653, 'depth': 5, 'l2_leaf_reg': 3.1871926600594964}. Best is trial 3 with value: 0.6244051420102302.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:04:45,030] Trial 14 finished with value: 0.6133332436514687 and parameters: {'iterations': 500, 'learning_rate': 0.03102946457567138, 'depth': 6, 'l2_leaf_reg': 5.979881535614749}. Best is trial 3 with value: 0.6244051420102302.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:04:47,679] Trial 15 finished with value: 0.6206544967863731 and parameters: {'iterations': 500, 'learning_rate': 0.0204924071078201, 'depth': 5, 'l2_leaf_reg': 3.3101872578893827}. Best is trial 3 with value: 0.6244051420102302.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:04:51,968] Trial 16 finished with value: 0.6084842492199878 and parameters: {'iterations': 500, 'learning_rate': 0.02912619374465703, 'depth': 6, 'l2_leaf_reg': 5.324016107133669}. Best is trial 3 with value: 0.6244051420102302.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:05:17,469] Trial 17 finished with value: 0.5953436523469866 and parameters: {'iterations': 500, 'learning_rate': 0.06801165202390347, 'depth': 8, 'l2_leaf_reg': 5.117847083583884}. Best is trial 3 with value: 0.6244051420102302.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:05:19,254] Trial 18 finished with value: 0.6107898607965594 and parameters: {'iterations': 500, 'learning_rate': 0.055138480141741754, 'depth': 4, 'l2_leaf_reg': 1.0102184570149855}. Best is trial 3 with value: 0.6244051420102302.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:05:21,772] Trial 19 finished with value: 0.6205107246834844 and parameters: {'iterations': 500, 'learning_rate': 0.01918283174859954, 'depth': 5, 'l2_leaf_reg': 3.7760978515707757}. Best is trial 3 with value: 0.6244051420102302.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:05:38,986] Trial 20 finished with value: 0.6018942557293572 and parameters: {'iterations': 2000, 'learning_rate': 0.027799420468382338, 'depth': 6, 'l2_leaf_reg': 5.535758579721597}. Best is trial 3 with value: 0.6244051420102302.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:05:41,561] Trial 21 finished with value: 0.6187607458902644 and parameters: {'iterations': 500, 'learning_rate': 0.02205836059505413, 'depth': 5, 'l2_leaf_reg': 3.113509834984063}. Best is trial 3 with value: 0.6244051420102302.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:05:44,627] Trial 22 finished with value: 0.6180761508635857 and parameters: {'iterations': 500, 'learning_rate': 0.01703647151862119, 'depth': 5, 'l2_leaf_reg': 3.348343829506112}. Best is trial 3 with value: 0.6244051420102302.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:05:49,732] Trial 23 finished with value: 0.6132339365396189 and parameters: {'iterations': 500, 'learning_rate': 0.02515244751254787, 'depth': 6, 'l2_leaf_reg': 4.230038036886538}. Best is trial 3 with value: 0.6244051420102302.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:05:51,856] Trial 24 finished with value: 0.6303691198168628 and parameters: {'iterations': 500, 'learning_rate': 0.014143036661619373, 'depth': 4, 'l2_leaf_reg': 2.864319547628134}. Best is trial 24 with value: 0.6303691198168628.
[I 2025-09-04 16:05:51,857] A new study created in memory with name: no-name-4ebbe886-6f60-4700-807f-fe9fcb450174
[I 2025-09-04 16:05:51,977] Trial 0 finished with value: 0.5683833274192597 and parameters: {'alpha': 0.018168532334028906, 'l1_ratio': 0.7801158824898549}. Best is trial 0 with value: 0.5683833274192597.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.257e-01, tolerance: 4.876e-02
  model = cd_fast.enet_coordinate_descent(

✅ CAT con C2X-Complex_rhow_5x5_depth_in_3_4 - Mejor R2: 0.63
📋 Parámetros: {'iterations': 500, 'learning_rate': 0.014143036661619373, 'depth': 4, 'l2_leaf_reg': 2.864319547628134}

Buscando mejores hiperparámetros para ELN con C2X-Complex_rhow_5x5_depth_in_3_4...

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 16:05:52,119] Trial 1 finished with value: 0.5799655672533461 and parameters: {'alpha': 0.007007455573880731, 'l1_ratio': 0.8963183852343073}. Best is trial 1 with value: 0.5799655672533461.
[I 2025-09-04 16:05:52,249] Trial 2 finished with value: 0.5337130008318745 and parameters: {'alpha': 0.32447884382796144, 'l1_ratio': 0.10371952876393586}. Best is trial 1 with value: 0.5799655672533461.

Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.673e+01, tolerance: 4.876e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.084e+02, tolerance: 5.544e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.283e+01, tolerance: 4.561e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.238e+01, tolerance: 4.433e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.053e+02, tolerance: 5.000e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 16:05:52,397] Trial 3 finished with value: 0.5102135777551507 and parameters: {'alpha': 0.00040649548599938336, 'l1_ratio': 0.3593313368545187}. Best is trial 1 with value: 0.5799655672533461.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.268e+01, tolerance: 4.876e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.065e+02, tolerance: 5.544e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.761e+01, tolerance: 4.561e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.163e+01, tolerance: 4.433e-02
  model = cd_fast.enet_coordinate_descent(

Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.021e+02, tolerance: 5.000e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 16:05:52,559] Trial 4 finished with value: 0.5158889759295016 and parameters: {'alpha': 0.0006178108122852735, 'l1_ratio': 0.26552499858574463}. Best is trial 1 with value: 0.5799655672533461.
[I 2025-09-04 16:05:52,723] Trial 5 finished with value: 0.47280345363744847 and parameters: {'alpha': 0.47108641455980665, 'l1_ratio': 0.3886153104801653}. Best is trial 1 with value: 0.5799655672533461.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.186e+02, tolerance: 4.876e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.232e+02, tolerance: 5.544e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.003e+02, tolerance: 4.561e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.694e+01, tolerance: 4.433e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.210e+02, tolerance: 5.000e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 16:05:52,903] Trial 6 finished with value: 0.5138558073697528 and parameters: {'alpha': 0.00011276075932139139, 'l1_ratio': 0.23296266011272815}. Best is trial 1 with value: 0.5799655672533461.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.804e+00, tolerance: 4.876e-02
  model = cd_fast.enet_coordinate_descent(

Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.691e+01, tolerance: 5.544e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.042e+01, tolerance: 4.561e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.018e+01, tolerance: 4.433e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.262e+01, tolerance: 5.000e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 16:05:53,072] Trial 7 finished with value: 0.5826196840204501 and parameters: {'alpha': 0.0035493598906217415, 'l1_ratio': 0.3005766979203285}. Best is trial 7 with value: 0.5826196840204501.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.369e+01, tolerance: 4.876e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.569e+01, tolerance: 5.544e-02
  model = cd_fast.enet_coordinate_descent(

Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.650e+01, tolerance: 4.561e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.032e+01, tolerance: 4.433e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.765e+01, tolerance: 5.000e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 16:05:53,285] Trial 8 finished with value: 0.5693329708354156 and parameters: {'alpha': 0.0014287270025520591, 'l1_ratio': 0.599989464528269}. Best is trial 7 with value: 0.5826196840204501.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.278e-01, tolerance: 4.876e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 16:05:53,409] Trial 9 finished with value: 0.5800469835331072 and parameters: {'alpha': 0.006966807487093528, 'l1_ratio': 0.8939709986277515}. Best is trial 7 with value: 0.5826196840204501.

Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.705e+00, tolerance: 4.876e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.086e+00, tolerance: 5.544e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.405e+00, tolerance: 4.561e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.454e+00, tolerance: 4.433e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.030e+00, tolerance: 5.000e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 16:05:53,593] Trial 10 finished with value: 0.5645058140445749 and parameters: {'alpha': 0.03887922837163258, 'l1_ratio': 0.023834031457425908}. Best is trial 7 with value: 0.5826196840204501.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.598e-01, tolerance: 4.876e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.080e-01, tolerance: 5.544e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.086e-01, tolerance: 4.561e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.366e-01, tolerance: 4.433e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.835e-01, tolerance: 5.000e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 16:05:53,781] Trial 11 finished with value: 0.582472883052567 and parameters: {'alpha': 0.004375965875386288, 'l1_ratio': 0.6315995182717093}. Best is trial 7 with value: 0.5826196840204501.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.635e+00, tolerance: 4.876e-02
  model = cd_fast.enet_coordinate_descent(

Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.061e+01, tolerance: 5.544e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.008e+00, tolerance: 4.561e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.588e+00, tolerance: 4.433e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.796e+01, tolerance: 5.000e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 16:05:53,941] Trial 12 finished with value: 0.5836043657438965 and parameters: {'alpha': 0.0025285029727796925, 'l1_ratio': 0.5792628939321688}. Best is trial 12 with value: 0.5836043657438965.
[I 2025-09-04 16:05:54,051] Trial 13 finished with value: 0.5315858009691996 and parameters: {'alpha': 0.07864316505272752, 'l1_ratio': 0.5193770381890623}. Best is trial 12 with value: 0.5836043657438965.

Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.448e+00, tolerance: 4.876e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.061e+01, tolerance: 5.544e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.533e+01, tolerance: 4.561e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.064e+01, tolerance: 4.433e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.084e+01, tolerance: 5.000e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 16:05:54,201] Trial 14 finished with value: 0.5828540562155735 and parameters: {'alpha': 0.0020622481555637156, 'l1_ratio': 0.6842311050314371}. Best is trial 12 with value: 0.5836043657438965.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.989e+01, tolerance: 4.876e-02
  model = cd_fast.enet_coordinate_descent(

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.131e+01, tolerance: 5.544e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.636e+01, tolerance: 4.561e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.550e+01, tolerance: 4.433e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.327e+01, tolerance: 5.000e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 16:05:54,357] Trial 15 finished with value: 0.5709894610641418 and parameters: {'alpha': 0.0013513959299695033, 'l1_ratio': 0.7220603031220614}. Best is trial 12 with value: 0.5836043657438965.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.957e+01, tolerance: 4.876e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.131e+02, tolerance: 5.544e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.025e+01, tolerance: 4.561e-02
  model = cd_fast.enet_coordinate_descent(

Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.738e+01, tolerance: 4.433e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.121e+02, tolerance: 5.000e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 16:05:54,533] Trial 16 finished with value: 0.5086623457514257 and parameters: {'alpha': 0.0002087560851486554, 'l1_ratio': 0.4936473322936801}. Best is trial 12 with value: 0.5836043657438965.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.505e+01, tolerance: 4.876e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.864e+01, tolerance: 5.544e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.877e+01, tolerance: 4.561e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.282e+01, tolerance: 4.433e-02
  model = cd_fast.enet_coordinate_descent(

Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.129e+01, tolerance: 5.000e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 16:05:54,723] Trial 17 finished with value: 0.5801733066764294 and parameters: {'alpha': 0.0014003955623407567, 'l1_ratio': 0.9996342788077539}. Best is trial 12 with value: 0.5836043657438965.
[I 2025-09-04 16:05:54,923] Trial 18 finished with value: 0.5536038398467047 and parameters: {'alpha': 0.03847686398894056, 'l1_ratio': 0.7064786483716526}. Best is trial 12 with value: 0.5836043657438965.

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.623e+00, tolerance: 4.876e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.770e+01, tolerance: 5.544e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.251e+01, tolerance: 4.561e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.167e+01, tolerance: 4.433e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.049e+01, tolerance: 5.000e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 16:05:55,109] Trial 19 finished with value: 0.5831692975873897 and parameters: {'alpha': 0.002570212647008704, 'l1_ratio': 0.4886596842000389}. Best is trial 12 with value: 0.5836043657438965.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2

[I 2025-09-04 16:05:55,283] Trial 20 finished with value: 0.5744469789013448 and parameters: {'alpha': 0.012684806429866143, 'l1_ratio': 0.4831559266273321}. Best is trial 12 with value: 0.5836043657438965.

Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.785e+00, tolerance: 4.876e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.549e+01, tolerance: 5.544e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.656e+01, tolerance: 4.561e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.876e+01, tolerance: 4.433e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.277e+01, tolerance: 5.000e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 16:05:55,421] Trial 21 finished with value: 0.5820587672027973 and parameters: {'alpha': 0.0021218094840005637, 'l1_ratio': 0.5866742645478467}. Best is trial 12 with value: 0.5836043657438965.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.030e+01, tolerance: 4.876e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.021e+01, tolerance: 5.544e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.218e+01, tolerance: 4.561e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.021e+01, tolerance: 4.433e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.896e+01, tolerance: 5.000e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 16:05:55,576] Trial 22 finished with value: 0.5256722390854891 and parameters: {'alpha': 0.0007085648172781989, 'l1_ratio': 0.4127817405818149}. Best is trial 12 with value: 0.5836043657438965.

Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.951e+00, tolerance: 4.876e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.080e+00, tolerance: 5.544e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.812e+00, tolerance: 4.561e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.172e-01, tolerance: 4.433e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.252e+00, tolerance: 5.000e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 16:05:55,715] Trial 23 finished with value: 0.5822856258292909 and parameters: {'alpha': 0.0027370678524827195, 'l1_ratio': 0.7819019084856909}. Best is trial 12 with value: 0.5836043657438965.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.320e+01, tolerance: 4.876e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.392e+01, tolerance: 5.544e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.740e+01, tolerance: 4.561e-02
  model = cd_fast.enet_coordinate_descent(

Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.873e+01, tolerance: 4.433e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.081e+01, tolerance: 5.000e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 16:05:55,862] Trial 24 finished with value: 0.5180700574609283 and parameters: {'alpha': 0.000392684839779317, 'l1_ratio': 0.7006262916523842}. Best is trial 12 with value: 0.5836043657438965.
[I 2025-09-04 16:05:55,863] A new study created in memory with name: no-name-70ca3b82-69bf-4fe9-b39b-46f89bfe14d8

Fold 5

✅ ELN con C2X-Complex_rhow_5x5_depth_in_3_4 - Mejor R2: 0.58
📋 Parámetros: {'alpha': 0.0025285029727796925, 'l1_ratio': 0.5792628939321688}

Buscando mejores hiperparámetros para XGB con TOA_1x1_depth_in_3_4...

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:06:20,663] Trial 0 finished with value: 0.32158622480328536 and parameters: {'n_estimators': 2000, 'learning_rate': 0.01671925563602673, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.8708290758599806, 'colsample_bytree': 0.7013327415834717}. Best is trial 0 with value: 0.32158622480328536.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:06:27,893] Trial 1 finished with value: 0.4583596515256091 and parameters: {'n_estimators': 500, 'learning_rate': 0.0056436196453246955, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.9987417400613587, 'colsample_bytree': 0.9300361587338952}. Best is trial 1 with value: 0.4583596515256091.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:06:43,767] Trial 2 finished with value: 0.49424252188315065 and parameters: {'n_estimators': 2000, 'learning_rate': 0.029697692509299125, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.7148640789820031, 'colsample_bytree': 0.855541000331238}. Best is trial 2 with value: 0.49424252188315065.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:06:51,058] Trial 3 finished with value: 0.38101617915580666 and parameters: {'n_estimators': 1000, 'learning_rate': 0.005998266412842461, 'max_depth': 5, 'min_child_weight': 1, 'subsample': 0.9594648327977094, 'colsample_bytree': 0.7452053208059684}. Best is trial 2 with value: 0.49424252188315065.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:06:59,168] Trial 4 finished with value: 0.43613617661278303 and parameters: {'n_estimators': 500, 'learning_rate': 0.007271965696563809, 'max_depth': 8, 'min_child_weight': 1, 'subsample': 0.6659785264733028, 'colsample_bytree': 0.9590473304892475}. Best is trial 2 with value: 0.49424252188315065.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:07:03,087] Trial 5 finished with value: 0.4748328131808961 and parameters: {'n_estimators': 500, 'learning_rate': 0.01195394495901344, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.9442446040086456, 'colsample_bytree': 0.8921122633419465}. Best is trial 2 with value: 0.49424252188315065.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:07:08,688] Trial 6 finished with value: 0.5191986174251644 and parameters: {'n_estimators': 500, 'learning_rate': 0.005903889352876245, 'max_depth': 8, 'min_child_weight': 2, 'subsample': 0.781917998902364, 'colsample_bytree': 0.722278807877633}. Best is trial 6 with value: 0.5191986174251644.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:07:12,073] Trial 7 finished with value: 0.518594044809914 and parameters: {'n_estimators': 500, 'learning_rate': 0.005265319554078436, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.6976287614468654, 'colsample_bytree': 0.8529095628524815}. Best is trial 6 with value: 0.5191986174251644.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:07:29,622] Trial 8 finished with value: 0.35773534670683726 and parameters: {'n_estimators': 2000, 'learning_rate': 0.016947203785971563, 'max_depth': 6, 'min_child_weight': 1, 'subsample': 0.8744966171830828, 'colsample_bytree': 0.6287896929863855}. Best is trial 6 with value: 0.5191986174251644.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:07:42,511] Trial 9 finished with value: 0.38728603037468756 and parameters: {'n_estimators': 2000, 'learning_rate': 0.02166654295709152, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.6738486017061233, 'colsample_bytree': 0.7538649673775003}. Best is trial 6 with value: 0.5191986174251644.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:07:52,250] Trial 10 finished with value: 0.4252962952771838 and parameters: {'n_estimators': 1000, 'learning_rate': 0.04896779362189672, 'max_depth': 8, 'min_child_weight': 3, 'subsample': 0.7796937285230053, 'colsample_bytree': 0.6131106117970705}. Best is trial 6 with value: 0.5191986174251644.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:07:56,332] Trial 11 finished with value: 0.4736559849147661 and parameters: {'n_estimators': 500, 'learning_rate': 0.00933742354788186, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.7682074865061121, 'colsample_bytree': 0.8344602403483752}. Best is trial 6 with value: 0.5191986174251644.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:08:01,370] Trial 12 finished with value: 0.49849810809803274 and parameters: {'n_estimators': 500, 'learning_rate': 0.005069411342488596, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.6213721504253743, 'colsample_bytree': 0.7929311615028418}. Best is trial 6 with value: 0.5191986174251644.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:08:05,595] Trial 13 finished with value: 0.48934039540706076 and parameters: {'n_estimators': 500, 'learning_rate': 0.00928518677881234, 'max_depth': 8, 'min_child_weight': 3, 'subsample': 0.7293247203217728, 'colsample_bytree': 0.6804438009323529}. Best is trial 6 with value: 0.5191986174251644.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:08:08,915] Trial 14 finished with value: 0.48776076275855607 and parameters: {'n_estimators': 500, 'learning_rate': 0.00816318057421286, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.8481678900194836, 'colsample_bytree': 0.7981124513623161}. Best is trial 6 with value: 0.5191986174251644.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:08:12,215] Trial 15 finished with value: 0.49032519825357446 and parameters: {'n_estimators': 500, 'learning_rate': 0.011356043571622504, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.8128429420204002, 'colsample_bytree': 0.6939232303678624}. Best is trial 6 with value: 0.5191986174251644.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:08:17,433] Trial 16 finished with value: 0.4650185864658304 and parameters: {'n_estimators': 1000, 'learning_rate': 0.006787849278462565, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.6059614989801954, 'colsample_bytree': 0.9955150827003549}. Best is trial 6 with value: 0.5191986174251644.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:08:22,690] Trial 17 finished with value: 0.4763398592725212 and parameters: {'n_estimators': 500, 'learning_rate': 0.012407984648347036, 'max_depth': 8, 'min_child_weight': 2, 'subsample': 0.7299619164418288, 'colsample_bytree': 0.8559558284392448}. Best is trial 6 with value: 0.5191986174251644.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:08:25,787] Trial 18 finished with value: 0.433831952791086 and parameters: {'n_estimators': 500, 'learning_rate': 0.027005883808500938, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.6714080664379624, 'colsample_bytree': 0.7497849814599585}. Best is trial 6 with value: 0.5191986174251644.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:08:33,723] Trial 19 finished with value: 0.47180595294925953 and parameters: {'n_estimators': 1000, 'learning_rate': 0.005086977026713638, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.8162464690304425, 'colsample_bytree': 0.8929086676238478}. Best is trial 6 with value: 0.5191986174251644.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:08:38,306] Trial 20 finished with value: 0.5072843051642763 and parameters: {'n_estimators': 500, 'learning_rate': 0.006964826895068633, 'max_depth': 8, 'min_child_weight': 2, 'subsample': 0.7160804684427009, 'colsample_bytree': 0.652160718254563}. Best is trial 6 with value: 0.5191986174251644.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:08:42,735] Trial 21 finished with value: 0.5098730144918748 and parameters: {'n_estimators': 500, 'learning_rate': 0.006624854473589718, 'max_depth': 8, 'min_child_weight': 2, 'subsample': 0.7519529818778534, 'colsample_bytree': 0.6608635044928938}. Best is trial 6 with value: 0.5191986174251644.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:08:49,340] Trial 22 finished with value: 0.499619102316913 and parameters: {'n_estimators': 500, 'learning_rate': 0.0086739523330554, 'max_depth': 8, 'min_child_weight': 2, 'subsample': 0.7658281111713042, 'colsample_bytree': 0.7233050491602908}. Best is trial 6 with value: 0.5191986174251644.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:08:55,262] Trial 23 finished with value: 0.5113309871417175 and parameters: {'n_estimators': 500, 'learning_rate': 0.006301236721482218, 'max_depth': 8, 'min_child_weight': 2, 'subsample': 0.7485621964303502, 'colsample_bytree': 0.6679486440948289}. Best is trial 6 with value: 0.5191986174251644.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:08:59,713] Trial 24 finished with value: 0.5085647205271976 and parameters: {'n_estimators': 500, 'learning_rate': 0.005020305811789844, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.683010512888505, 'colsample_bytree': 0.7745663513899564}. Best is trial 6 with value: 0.5191986174251644.
[I 2025-09-04 16:08:59,714] A new study created in memory with name: no-name-6bab32f7-78ec-4a43-a797-ef2b5341ea52

✅ XGB con TOA_1x1_depth_in_3_4 - Mejor R2: 0.52
📋 Parámetros: {'n_estimators': 500, 'learning_rate': 0.005903889352876245, 'max_depth': 8, 'min_child_weight': 2, 'subsample': 0.781917998902364, 'colsample_bytree': 0.722278807877633}

Buscando mejores hiperparámetros para LBM con TOA_1x1_depth_in_3_4...

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 16:09:00,572] Trial 0 finished with value: 0.5525586306527113 and parameters: {'learning_rate': 0.022112198571712444, 'num_leaves': 20, 'max_depth': 8, 'min_child_samples': 14, 'subsample': 0.8167844313784325, 'colsample_bytree': 0.6736823255744206, 'n_estimators': 1000}. Best is trial 0 with value: 0.5525586306527113.

Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:09:01,749] Trial 1 finished with value: 0.5487658594598519 and parameters: {'learning_rate': 0.005452319420451669, 'num_leaves': 40, 'max_depth': 5, 'min_child_samples': 15, 'subsample': 0.7361337914349018, 'colsample_bytree': 0.6368629976490118, 'n_estimators': 2000}. Best is trial 0 with value: 0.5525586306527113.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:09:02,765] Trial 2 finished with value: 0.5483543702929579 and parameters: {'learning_rate': 0.024546760150093886, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 14, 'subsample': 0.6139297141494547, 'colsample_bytree': 0.6919905714858765, 'n_estimators': 2000}. Best is trial 0 with value: 0.5525586306527113.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 16:09:03,311] Trial 3 finished with value: 0.4337661125775527 and parameters: {'learning_rate': 0.028341957613518206, 'num_leaves': 80, 'max_depth': 8, 'min_child_samples': 4, 'subsample': 0.9946478911762382, 'colsample_bytree': 0.6024963830422897, 'n_estimators': 500}. Best is trial 0 with value: 0.5525586306527113.

Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:09:03,730] Trial 4 finished with value: 0.5747819540831735 and parameters: {'learning_rate': 0.006581448073917955, 'num_leaves': 40, 'max_depth': 8, 'min_child_samples': 14, 'subsample': 0.8620437210753737, 'colsample_bytree': 0.8081662246712954, 'n_estimators': 500}. Best is trial 4 with value: 0.5747819540831735.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 16:09:04,097] Trial 5 finished with value: 0.5451138064485903 and parameters: {'learning_rate': 0.04531414972402398, 'num_leaves': 40, 'max_depth': 6, 'min_child_samples': 13, 'subsample': 0.7285933264954719, 'colsample_bytree': 0.9658189611168906, 'n_estimators': 500}. Best is trial 4 with value: 0.5747819540831735.

Fold 4
Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:09:05,408] Trial 6 finished with value: 0.5191681340821568 and parameters: {'learning_rate': 0.01910049728342646, 'num_leaves': 80, 'max_depth': 6, 'min_child_samples': 10, 'subsample': 0.6548595851510074, 'colsample_bytree': 0.8207970540063153, 'n_estimators': 2000}. Best is trial 4 with value: 0.5747819540831735.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:09:06,944] Trial 7 finished with value: 0.49785723808501414 and parameters: {'learning_rate': 0.03819155436981494, 'num_leaves': 40, 'max_depth': 8, 'min_child_samples': 16, 'subsample': 0.9430024423390874, 'colsample_bytree': 0.8682461826497276, 'n_estimators': 2000}. Best is trial 4 with value: 0.5747819540831735.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 16:09:07,567] Trial 8 finished with value: 0.5102921425167664 and parameters: {'learning_rate': 0.04607999441861596, 'num_leaves': 80, 'max_depth': 5, 'min_child_samples': 9, 'subsample': 0.7685831516690402, 'colsample_bytree': 0.8148118403546933, 'n_estimators': 1000}. Best is trial 4 with value: 0.5747819540831735.

Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:09:08,834] Trial 9 finished with value: 0.47182555989004693 and parameters: {'learning_rate': 0.04964322280538557, 'num_leaves': 60, 'max_depth': 5, 'min_child_samples': 6, 'subsample': 0.9537172957265414, 'colsample_bytree': 0.8190678975355165, 'n_estimators': 2000}. Best is trial 4 with value: 0.5747819540831735.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:09:09,331] Trial 10 finished with value: 0.6031454698386589 and parameters: {'learning_rate': 0.008542009479780798, 'num_leaves': 60, 'max_depth': 7, 'min_child_samples': 12, 'subsample': 0.8564862481702243, 'colsample_bytree': 0.9333818555047773, 'n_estimators': 500}. Best is trial 10 with value: 0.6031454698386589.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:09:09,815] Trial 11 finished with value: 0.6042301700757706 and parameters: {'learning_rate': 0.007909691331534685, 'num_leaves': 60, 'max_depth': 7, 'min_child_samples': 12, 'subsample': 0.8596273191581234, 'colsample_bytree': 0.997564764727754, 'n_estimators': 500}. Best is trial 11 with value: 0.6042301700757706.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:09:10,349] Trial 12 finished with value: 0.6092444140996466 and parameters: {'learning_rate': 0.009764104906351014, 'num_leaves': 60, 'max_depth': 7, 'min_child_samples': 12, 'subsample': 0.874293421655372, 'colsample_bytree': 0.9998656579800604, 'n_estimators': 500}. Best is trial 12 with value: 0.6092444140996466.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:09:10,879] Trial 13 finished with value: 0.5863313642092542 and parameters: {'learning_rate': 0.0116116070627834, 'num_leaves': 60, 'max_depth': 7, 'min_child_samples': 11, 'subsample': 0.8875665538227453, 'colsample_bytree': 0.9977252095836601, 'n_estimators': 500}. Best is trial 12 with value: 0.6092444140996466.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:09:11,385] Trial 14 finished with value: 0.5903310467892141 and parameters: {'learning_rate': 0.011774302715444093, 'num_leaves': 60, 'max_depth': 7, 'min_child_samples': 9, 'subsample': 0.8991374490725356, 'colsample_bytree': 0.9086692402150379, 'n_estimators': 500}. Best is trial 12 with value: 0.6092444140996466.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 16:09:11,867] Trial 15 finished with value: 0.5892851919478173 and parameters: {'learning_rate': 0.009410828479471639, 'num_leaves': 60, 'max_depth': 7, 'min_child_samples': 8, 'subsample': 0.8027307573150736, 'colsample_bytree': 0.7478025003913761, 'n_estimators': 500}. Best is trial 12 with value: 0.6092444140996466.

Fold 4
Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 16:09:12,278] Trial 16 finished with value: 0.5889663925556958 and parameters: {'learning_rate': 0.014170426144151939, 'num_leaves': 60, 'max_depth': 6, 'min_child_samples': 12, 'subsample': 0.9233672305032694, 'colsample_bytree': 0.9017751473324466, 'n_estimators': 500}. Best is trial 12 with value: 0.6092444140996466.

Fold 4
Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:09:13,256] Trial 17 finished with value: 0.5344493685718379 and parameters: {'learning_rate': 0.007569435523378589, 'num_leaves': 60, 'max_depth': 7, 'min_child_samples': 7, 'subsample': 0.8544646636764724, 'colsample_bytree': 0.9865641601974992, 'n_estimators': 1000}. Best is trial 12 with value: 0.6092444140996466.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:09:13,732] Trial 18 finished with value: 0.580667813912112 and parameters: {'learning_rate': 0.005291485787290944, 'num_leaves': 60, 'max_depth': 6, 'min_child_samples': 11, 'subsample': 0.9864876538332884, 'colsample_bytree': 0.9522024140057517, 'n_estimators': 500}. Best is trial 12 with value: 0.6092444140996466.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:09:14,254] Trial 19 finished with value: 0.6055989620363389 and parameters: {'learning_rate': 0.01071013848579011, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 12, 'subsample': 0.8180634008822852, 'colsample_bytree': 0.8683288067816892, 'n_estimators': 500}. Best is trial 12 with value: 0.6092444140996466.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 16:09:14,937] Trial 20 finished with value: 0.5331173469010327 and parameters: {'learning_rate': 0.013755048049444862, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 16, 'subsample': 0.7646421077824067, 'colsample_bytree': 0.8618524730515997, 'n_estimators': 1000}. Best is trial 12 with value: 0.6092444140996466.

Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 16:09:15,367] Trial 21 finished with value: 0.6032079647561495 and parameters: {'learning_rate': 0.010524133631823022, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 12, 'subsample': 0.8310711784921884, 'colsample_bytree': 0.765851587328519, 'n_estimators': 500}. Best is trial 12 with value: 0.6092444140996466.

Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:09:15,858] Trial 22 finished with value: 0.617964804571377 and parameters: {'learning_rate': 0.007130386687415869, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 10, 'subsample': 0.8922959456502495, 'colsample_bytree': 0.9294737227298466, 'n_estimators': 500}. Best is trial 22 with value: 0.617964804571377.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 16:09:16,353] Trial 23 finished with value: 0.6172385642244433 and parameters: {'learning_rate': 0.006549690849978523, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 10, 'subsample': 0.9057272763361568, 'colsample_bytree': 0.8813529028704246, 'n_estimators': 500}. Best is trial 22 with value: 0.617964804571377.

Fold 4
Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 16:09:16,936] Trial 24 finished with value: 0.6117958550705132 and parameters: {'learning_rate': 0.006559033314105687, 'num_leaves': 20, 'max_depth': 8, 'min_child_samples': 10, 'subsample': 0.9101356194381086, 'colsample_bytree': 0.9115911586136392, 'n_estimators': 500}. Best is trial 22 with value: 0.617964804571377.
[I 2025-09-04 16:09:16,937] A new study created in memory with name: no-name-0226c44b-9b10-4acf-aaf8-b3a633e6ac4f

Fold 5

✅ LBM con TOA_1x1_depth_in_3_4 - Mejor R2: 0.62
📋 Parámetros: {'learning_rate': 0.007130386687415869, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 10, 'subsample': 0.8922959456502495, 'colsample_bytree': 0.9294737227298466, 'n_estimators': 500}

Buscando mejores hiperparámetros para MLP con TOA_1x1_depth_in_3_4...

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

[I 2025-09-04 16:09:20,268] Trial 0 finished with value: 0.5278337384325156 and parameters: {'hidden_layer_sizes': '128', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.0005399382429666402, 'learning_rate': 'adaptive', 'learning_rate_init': 0.008881762070308823}. Best is trial 0 with value: 0.5278337384325156.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:09:21,478] Trial 1 finished with value: 0.4847242030611777 and parameters: {'hidden_layer_sizes': '128', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.029544165960056688, 'learning_rate': 'constant', 'learning_rate_init': 0.0016033578130494953}. Best is trial 0 with value: 0.5278337384325156.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-04 16:09:24,876] Trial 2 finished with value: 0.470625893092528 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.0007666183042290787, 'learning_rate': 'constant', 'learning_rate_init': 0.00023604611719977753}. Best is trial 0 with value: 0.5278337384325156.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-04 16:09:28,896] Trial 3 finished with value: 0.5402069509307464 and parameters: {'hidden_layer_sizes': '256_128', 'activation': 'relu', 'solver': 'sgd', 'alpha': 1.7162016589097984e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.00029456972246932954}. Best is trial 3 with value: 0.5402069509307464.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-04 16:09:30,972] Trial 4 finished with value: 0.5175058045912195 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 1.0426050237601288e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.0035959352103188164}. Best is trial 3 with value: 0.5402069509307464.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

[I 2025-09-04 16:09:33,360] Trial 5 finished with value: 0.6353428609443685 and parameters: {'hidden_layer_sizes': '256', 'activation': 'relu', 'solver': 'sgd', 'alpha': 1.87545951688053e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.0009164943974243175}. Best is trial 5 with value: 0.6353428609443685.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-04 16:09:35,334] Trial 6 finished with value: 0.4316595123439013 and parameters: {'hidden_layer_sizes': '128', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0011466390091940612, 'learning_rate': 'constant', 'learning_rate_init': 0.00032841840669001215}. Best is trial 5 with value: 0.6353428609443685.

Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:09:39,742] Trial 7 finished with value: 0.6324419981007247 and parameters: {'hidden_layer_sizes': '256_128', 'activation': 'relu', 'solver': 'sgd', 'alpha': 5.6706294029922096e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.001375929773107827}. Best is trial 5 with value: 0.6353428609443685.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

[I 2025-09-04 16:09:42,339] Trial 8 finished with value: 0.5261534209704698 and parameters: {'hidden_layer_sizes': '256', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.0011667419750848028, 'learning_rate': 'constant', 'learning_rate_init': 0.0023332629109951526}. Best is trial 5 with value: 0.6353428609443685.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-04 16:09:45,719] Trial 9 finished with value: 0.5152454044931438 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.023046574210438885, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00017086592718345105}. Best is trial 5 with value: 0.6353428609443685.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 16:09:47,118] Trial 10 finished with value: 0.6880870112092514 and parameters: {'hidden_layer_sizes': '256', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.00010952780216623349, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0004380632528857599}. Best is trial 10 with value: 0.6880870112092514.

Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 16:09:48,492] Trial 11 finished with value: 0.6525830060762441 and parameters: {'hidden_layer_sizes': '256', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.00011635107442496292, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0005606321188589878}. Best is trial 10 with value: 0.6880870112092514.

Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 16:09:49,722] Trial 12 finished with value: 0.6528369021851601 and parameters: {'hidden_layer_sizes': '256', 'activation': 'relu', 'solver': 'adam', 'alpha': 9.944330094224335e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0006458440682639056}. Best is trial 10 with value: 0.6880870112092514.

Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 16:09:50,896] Trial 13 finished with value: 0.6716283479328213 and parameters: {'hidden_layer_sizes': '256', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.000177125878335501, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0006448588294724189}. Best is trial 10 with value: 0.6880870112092514.

Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-04 16:09:53,114] Trial 14 finished with value: 0.6318141403737896 and parameters: {'hidden_layer_sizes': '256', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0002431735044917509, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00011920969342193556}. Best is trial 10 with value: 0.6880870112092514.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 16:09:54,452] Trial 15 finished with value: 0.6856331651841333 and parameters: {'hidden_layer_sizes': '256', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.004813083338752276, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0004821471794702625}. Best is trial 10 with value: 0.6880870112092514.

Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:09:55,886] Trial 16 finished with value: 0.6758519413332258 and parameters: {'hidden_layer_sizes': '256', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.007536694503671083, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0004077754066111325}. Best is trial 10 with value: 0.6880870112092514.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-04 16:09:58,239] Trial 17 finished with value: 0.6060817506524447 and parameters: {'hidden_layer_sizes': '256', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.004520282687714943, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00010113768884914716}. Best is trial 10 with value: 0.6880870112092514.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:10:02,400] Trial 18 finished with value: 0.6475952912974219 and parameters: {'hidden_layer_sizes': '256_128', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.003990123216507993, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00019563146427330812}. Best is trial 10 with value: 0.6880870112092514.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 16:10:03,584] Trial 19 finished with value: 0.6687887237426312 and parameters: {'hidden_layer_sizes': '256', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.08392109550456876, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0010755831362402686}. Best is trial 10 with value: 0.6880870112092514.

Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:10:04,861] Trial 20 finished with value: 0.6856604699122975 and parameters: {'hidden_layer_sizes': '256', 'activation': 'relu', 'solver': 'adam', 'alpha': 4.341929352929899e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.000480677579129921}. Best is trial 10 with value: 0.6880870112092514.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 16:10:06,229] Trial 21 finished with value: 0.6883090795413813 and parameters: {'hidden_layer_sizes': '256', 'activation': 'relu', 'solver': 'adam', 'alpha': 4.763485358217016e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0004348441303622641}. Best is trial 21 with value: 0.6883090795413813.

Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 16:10:07,577] Trial 22 finished with value: 0.6725448282363324 and parameters: {'hidden_layer_sizes': '256', 'activation': 'relu', 'solver': 'adam', 'alpha': 4.456708866849877e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0008424724336656132}. Best is trial 21 with value: 0.6883090795413813.

Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:10:09,326] Trial 23 finished with value: 0.6699675955848483 and parameters: {'hidden_layer_sizes': '256', 'activation': 'relu', 'solver': 'adam', 'alpha': 3.3437904977376794e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00035889698980581336}. Best is trial 21 with value: 0.6883090795413813.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

[I 2025-09-04 16:10:12,069] Trial 24 finished with value: 0.6480335829650823 and parameters: {'hidden_layer_sizes': '256', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.00033542415915241333, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00015212270232757764}. Best is trial 21 with value: 0.6883090795413813.
[I 2025-09-04 16:10:12,070] A new study created in memory with name: no-name-d3454b4a-0ab8-457b-a574-c6390b808609
[I 2025-09-04 16:10:12,185] Trial 0 finished with value: 0.12529500462988785 and parameters: {'C': 0.17548406992957544, 'epsilon': 0.0384154564637624}. Best is trial 0 with value: 0.12529500462988785.

✅ MLP con TOA_1x1_depth_in_3_4 - Mejor R2: 0.69
📋 Parámetros: {'hidden_layer_sizes': '256', 'activation': 'relu', 'solver': 'adam', 'alpha': 4.763485358217016e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0004348441303622641}

Buscando mejores hiperparámetros para SVR con TOA_1x1_depth_in_3_4...

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:10:12,272] Trial 1 finished with value: 0.44649688931074905 and parameters: {'C': 1.5529719408425116, 'epsilon': 0.12866387640320331}. Best is trial 1 with value: 0.44649688931074905.
[I 2025-09-04 16:10:12,361] Trial 2 finished with value: 0.1506340274111947 and parameters: {'C': 0.1935794180477939, 'epsilon': 0.12066606039351746}. Best is trial 1 with value: 0.44649688931074905.
[I 2025-09-04 16:10:12,448] Trial 3 finished with value: 0.46107656006745756 and parameters: {'C': 2.601154341267247, 'epsilon': 0.11532784736192124}. Best is trial 3 with value: 0.46107656006745756.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2

[I 2025-09-04 16:10:12,538] Trial 4 finished with value: 0.3790455060602822 and parameters: {'C': 0.7197623373168911, 'epsilon': 0.08907215817610024}. Best is trial 3 with value: 0.46107656006745756.
[I 2025-09-04 16:10:12,641] Trial 5 finished with value: 0.46149526413904174 and parameters: {'C': 2.2111333817672927, 'epsilon': 0.07253326854109794}. Best is trial 5 with value: 0.46149526413904174.

Fold 3
Fold 4
Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 16:10:12,741] Trial 6 finished with value: 0.4441193042041831 and parameters: {'C': 5.653058428023974, 'epsilon': 0.03895684882921407}. Best is trial 5 with value: 0.46149526413904174.
[I 2025-09-04 16:10:12,832] Trial 7 finished with value: 0.07411962693733809 and parameters: {'C': 0.1319149909754083, 'epsilon': 0.013534922399235025}. Best is trial 5 with value: 0.46149526413904174.

Fold 4
Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 16:10:12,936] Trial 8 finished with value: 0.4227693882544421 and parameters: {'C': 9.806118668525293, 'epsilon': 0.027594254422116195}. Best is trial 5 with value: 0.46149526413904174.
[I 2025-09-04 16:10:13,047] Trial 9 finished with value: 0.29796021174456844 and parameters: {'C': 0.4394561146021712, 'epsilon': 0.026441263630944123}. Best is trial 5 with value: 0.46149526413904174.

Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 16:10:13,182] Trial 10 finished with value: 0.460691992190008 and parameters: {'C': 3.0166632880864155, 'epsilon': 0.18627090688519754}. Best is trial 5 with value: 0.46149526413904174.
[I 2025-09-04 16:10:13,339] Trial 11 finished with value: 0.46122559893732773 and parameters: {'C': 2.6217086635588336, 'epsilon': 0.08050422311361127}. Best is trial 5 with value: 0.46149526413904174.

Fold 4
Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===

[I 2025-09-04 16:10:13,450] Trial 12 finished with value: 0.43802596932863336 and parameters: {'C': 1.3148221991976234, 'epsilon': 0.07297009350413879}. Best is trial 5 with value: 0.46149526413904174.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:10:13,563] Trial 13 finished with value: 0.45970173189729635 and parameters: {'C': 3.396627985867349, 'epsilon': 0.06944121440209058}. Best is trial 5 with value: 0.46149526413904174.
[I 2025-09-04 16:10:13,671] Trial 14 finished with value: 0.39470610430776343 and parameters: {'C': 0.7545124145820528, 'epsilon': 0.1626573752929345}. Best is trial 5 with value: 0.46149526413904174.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:10:13,779] Trial 15 finished with value: 0.44512604665776934 and parameters: {'C': 5.846389652482785, 'epsilon': 0.06455263185139776}. Best is trial 5 with value: 0.46149526413904174.
[I 2025-09-04 16:10:13,886] Trial 16 finished with value: 0.46070607639819205 and parameters: {'C': 2.193161630661662, 'epsilon': 0.09570651622730324}. Best is trial 5 with value: 0.46149526413904174.
[I 2025-09-04 16:10:13,983] Trial 17 finished with value: 0.286938641020252 and parameters: {'C': 0.3875963966389637, 'epsilon': 0.14704342312780633}. Best is trial 5 with value: 0.46149526413904174.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===

[I 2025-09-04 16:10:14,087] Trial 18 finished with value: 0.44868955245613473 and parameters: {'C': 5.286039192610549, 'epsilon': 0.05845437957592016}. Best is trial 5 with value: 0.46149526413904174.
[I 2025-09-04 16:10:14,183] Trial 19 finished with value: 0.4489907440571016 and parameters: {'C': 1.6442517749276753, 'epsilon': 0.0819221442267651}. Best is trial 5 with value: 0.46149526413904174.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1

[I 2025-09-04 16:10:14,281] Trial 20 finished with value: 0.41766955217474144 and parameters: {'C': 0.9923393979598325, 'epsilon': 0.05183975006234902}. Best is trial 5 with value: 0.46149526413904174.
[I 2025-09-04 16:10:14,384] Trial 21 finished with value: 0.4611049221675724 and parameters: {'C': 2.8877689283395678, 'epsilon': 0.11090728617786139}. Best is trial 5 with value: 0.46149526413904174.

Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2

[I 2025-09-04 16:10:14,486] Trial 22 finished with value: 0.4577321265597819 and parameters: {'C': 4.080093695238751, 'epsilon': 0.11052091918134557}. Best is trial 5 with value: 0.46149526413904174.
[I 2025-09-04 16:10:14,599] Trial 23 finished with value: 0.4554760481543393 and parameters: {'C': 1.8897514191925036, 'epsilon': 0.1001648294191576}. Best is trial 5 with value: 0.46149526413904174.

Fold 3
Fold 4
Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2

[I 2025-09-04 16:10:14,701] Trial 24 finished with value: 0.43963990786611873 and parameters: {'C': 9.938227282968732, 'epsilon': 0.1438406554528852}. Best is trial 5 with value: 0.46149526413904174.
[I 2025-09-04 16:10:14,702] A new study created in memory with name: no-name-5d5470e6-e550-4820-8452-285e6a895d49
[I 2025-09-04 16:10:14,775] Trial 0 finished with value: 0.5985105756999951 and parameters: {'n_neighbors': 4, 'leaf_size': 31}. Best is trial 0 with value: 0.5985105756999951.
[I 2025-09-04 16:10:14,844] Trial 1 finished with value: 0.6025563906264737 and parameters: {'n_neighbors': 5, 'leaf_size': 16}. Best is trial 1 with value: 0.6025563906264737.

Fold 3
Fold 4
Fold 5

✅ SVR con TOA_1x1_depth_in_3_4 - Mejor R2: 0.46
📋 Parámetros: {'C': 2.2111333817672927, 'epsilon': 0.07253326854109794}

Buscando mejores hiperparámetros para KNN con TOA_1x1_depth_in_3_4...

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===

[I 2025-09-04 16:10:14,948] Trial 2 finished with value: 0.5727857490575929 and parameters: {'n_neighbors': 3, 'leaf_size': 24}. Best is trial 1 with value: 0.6025563906264737.
[I 2025-09-04 16:10:15,023] Trial 3 finished with value: 0.6110073712463202 and parameters: {'n_neighbors': 6, 'leaf_size': 33}. Best is trial 3 with value: 0.6110073712463202.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2

[I 2025-09-04 16:10:15,101] Trial 4 finished with value: 0.6064123510159782 and parameters: {'n_neighbors': 7, 'leaf_size': 37}. Best is trial 3 with value: 0.6110073712463202.
[I 2025-09-04 16:10:15,178] Trial 5 finished with value: 0.603639980417062 and parameters: {'n_neighbors': 9, 'leaf_size': 36}. Best is trial 3 with value: 0.6110073712463202.
[I 2025-09-04 16:10:15,247] Trial 6 finished with value: 0.6025563906264737 and parameters: {'n_neighbors': 5, 'leaf_size': 16}. Best is trial 3 with value: 0.6110073712463202.

Fold 3
Fold 4
Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1

[I 2025-09-04 16:10:15,323] Trial 7 finished with value: 0.603639980417062 and parameters: {'n_neighbors': 9, 'leaf_size': 40}. Best is trial 3 with value: 0.6110073712463202.
[I 2025-09-04 16:10:15,396] Trial 8 finished with value: 0.6064123510159782 and parameters: {'n_neighbors': 7, 'leaf_size': 17}. Best is trial 3 with value: 0.6110073712463202.

Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:10:15,471] Trial 9 finished with value: 0.6025563906264737 and parameters: {'n_neighbors': 5, 'leaf_size': 18}. Best is trial 3 with value: 0.6110073712463202.
[I 2025-09-04 16:10:15,566] Trial 10 finished with value: 0.6080905807332733 and parameters: {'n_neighbors': 10, 'leaf_size': 28}. Best is trial 3 with value: 0.6110073712463202.
[I 2025-09-04 16:10:15,649] Trial 11 finished with value: 0.6080905807332733 and parameters: {'n_neighbors': 10, 'leaf_size': 28}. Best is trial 3 with value: 0.6110073712463202.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2

[I 2025-09-04 16:10:15,735] Trial 12 finished with value: 0.6100788113821298 and parameters: {'n_neighbors': 8, 'leaf_size': 23}. Best is trial 3 with value: 0.6110073712463202.
[I 2025-09-04 16:10:15,816] Trial 13 finished with value: 0.6100788113821298 and parameters: {'n_neighbors': 8, 'leaf_size': 10}. Best is trial 3 with value: 0.6110073712463202.

Fold 3
Fold 4
Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:10:15,894] Trial 14 finished with value: 0.6110073712463202 and parameters: {'n_neighbors': 6, 'leaf_size': 23}. Best is trial 3 with value: 0.6110073712463202.
[I 2025-09-04 16:10:15,977] Trial 15 finished with value: 0.6110073712463202 and parameters: {'n_neighbors': 6, 'leaf_size': 32}. Best is trial 3 with value: 0.6110073712463202.
[I 2025-09-04 16:10:16,054] Trial 16 finished with value: 0.6110073712463202 and parameters: {'n_neighbors': 6, 'leaf_size': 21}. Best is trial 3 with value: 0.6110073712463202.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 16:10:16,133] Trial 17 finished with value: 0.5727857490575929 and parameters: {'n_neighbors': 3, 'leaf_size': 33}. Best is trial 3 with value: 0.6110073712463202.
[I 2025-09-04 16:10:16,235] Trial 18 finished with value: 0.6110073712463202 and parameters: {'n_neighbors': 6, 'leaf_size': 27}. Best is trial 3 with value: 0.6110073712463202.

Fold 4
Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 16:10:16,325] Trial 19 finished with value: 0.5985105756999951 and parameters: {'n_neighbors': 4, 'leaf_size': 12}. Best is trial 3 with value: 0.6110073712463202.
[I 2025-09-04 16:10:16,426] Trial 20 finished with value: 0.6064123510159782 and parameters: {'n_neighbors': 7, 'leaf_size': 20}. Best is trial 3 with value: 0.6110073712463202.

Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:10:16,514] Trial 21 finished with value: 0.6110073712463202 and parameters: {'n_neighbors': 6, 'leaf_size': 32}. Best is trial 3 with value: 0.6110073712463202.
[I 2025-09-04 16:10:16,611] Trial 22 finished with value: 0.6110073712463202 and parameters: {'n_neighbors': 6, 'leaf_size': 35}. Best is trial 3 with value: 0.6110073712463202.
[I 2025-09-04 16:10:16,700] Trial 23 finished with value: 0.6025563906264737 and parameters: {'n_neighbors': 5, 'leaf_size': 29}. Best is trial 3 with value: 0.6110073712463202.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1

[I 2025-09-04 16:10:16,786] Trial 24 finished with value: 0.6100788113821298 and parameters: {'n_neighbors': 8, 'leaf_size': 25}. Best is trial 3 with value: 0.6110073712463202.
[I 2025-09-04 16:10:16,787] A new study created in memory with name: no-name-d22bcdfd-a342-4c3f-bf1b-de5bf77575d0
[I 2025-09-04 16:10:16,861] Trial 0 finished with value: 0.32818533224776825 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: 0.32818533224776825.

Fold 2
Fold 3
Fold 4
Fold 5

✅ KNN con TOA_1x1_depth_in_3_4 - Mejor R2: 0.61
📋 Parámetros: {'n_neighbors': 6, 'leaf_size': 33}

Buscando mejores hiperparámetros para LR con TOA_1x1_depth_in_3_4...

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 16:10:16,954] Trial 1 finished with value: 0.1800142896756909 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 0 with value: 0.32818533224776825.
[I 2025-09-04 16:10:17,065] Trial 2 finished with value: 0.18001428967587163 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 0 with value: 0.32818533224776825.

Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 16:10:17,154] Trial 3 finished with value: 0.32818533224777446 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 3 with value: 0.32818533224777446.
[I 2025-09-04 16:10:17,260] Trial 4 finished with value: 0.1800142896756909 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 3 with value: 0.32818533224777446.

Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:10:17,348] Trial 5 finished with value: 0.32818533224777446 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 3 with value: 0.32818533224777446.
[I 2025-09-04 16:10:17,439] Trial 6 finished with value: 0.32818533224776825 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 3 with value: 0.32818533224777446.
[I 2025-09-04 16:10:17,515] Trial 7 finished with value: 0.32818533224776825 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 3 with value: 0.32818533224777446.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 16:10:17,688] Trial 8 finished with value: 0.1800142896756909 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 3 with value: 0.32818533224777446.
[I 2025-09-04 16:10:17,803] Trial 9 finished with value: 0.18001428967587163 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 3 with value: 0.32818533224777446.

Fold 4
Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2

[I 2025-09-04 16:10:17,907] Trial 10 finished with value: 0.32818533224777446 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 3 with value: 0.32818533224777446.
[I 2025-09-04 16:10:17,999] Trial 11 finished with value: 0.32818533224777446 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 3 with value: 0.32818533224777446.

Fold 3
Fold 4
Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 16:10:18,079] Trial 12 finished with value: 0.32818533224777446 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 3 with value: 0.32818533224777446.
[I 2025-09-04 16:10:18,169] Trial 13 finished with value: 0.32818533224777446 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 3 with value: 0.32818533224777446.
[I 2025-09-04 16:10:18,242] Trial 14 finished with value: 0.32818533224777446 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 3 with value: 0.32818533224777446.

Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2

[I 2025-09-04 16:10:18,315] Trial 15 finished with value: 0.32818533224777446 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 3 with value: 0.32818533224777446.
[I 2025-09-04 16:10:18,389] Trial 16 finished with value: 0.32818533224777446 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 3 with value: 0.32818533224777446.
[I 2025-09-04 16:10:18,457] Trial 17 finished with value: 0.32818533224777446 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 3 with value: 0.32818533224777446.

Fold 3
Fold 4
Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2

[I 2025-09-04 16:10:18,529] Trial 18 finished with value: 0.32818533224777446 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 3 with value: 0.32818533224777446.
[I 2025-09-04 16:10:18,605] Trial 19 finished with value: 0.32818533224777446 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 3 with value: 0.32818533224777446.
[I 2025-09-04 16:10:18,680] Trial 20 finished with value: 0.32818533224777446 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 3 with value: 0.32818533224777446.

Fold 3
Fold 4
Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1

[I 2025-09-04 16:10:18,776] Trial 21 finished with value: 0.32818533224777446 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 3 with value: 0.32818533224777446.
[I 2025-09-04 16:10:18,850] Trial 22 finished with value: 0.32818533224777446 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 3 with value: 0.32818533224777446.

Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 16:10:18,917] Trial 23 finished with value: 0.32818533224777446 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 3 with value: 0.32818533224777446.
[I 2025-09-04 16:10:18,992] Trial 24 finished with value: 0.32818533224777446 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 3 with value: 0.32818533224777446.
[I 2025-09-04 16:10:18,993] A new study created in memory with name: no-name-ac5d979d-05a9-45ea-93ef-4c6afe8a446e

Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

✅ LR con TOA_1x1_depth_in_3_4 - Mejor R2: 0.33
📋 Parámetros: {'fit_intercept': False, 'positive': True}

Buscando mejores hiperparámetros para RF con TOA_1x1_depth_in_3_4...

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:10:22,598] Trial 0 finished with value: 0.4059703195175963 and parameters: {'n_estimators': 100, 'max_depth': 8, 'min_samples_split': 5, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 0 with value: 0.4059703195175963.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:10:33,753] Trial 1 finished with value: 0.5140066239109848 and parameters: {'n_estimators': 300, 'max_depth': 14, 'min_samples_split': 5, 'min_samples_leaf': 4, 'bootstrap': False}. Best is trial 1 with value: 0.5140066239109848.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:10:46,550] Trial 2 finished with value: 0.5447728256655071 and parameters: {'n_estimators': 300, 'max_depth': 11, 'min_samples_split': 4, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 2 with value: 0.5447728256655071.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:10:53,150] Trial 3 finished with value: 0.5424442148346298 and parameters: {'n_estimators': 300, 'max_depth': 14, 'min_samples_split': 10, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 2 with value: 0.5447728256655071.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:11:13,119] Trial 4 finished with value: 0.45599008716184164 and parameters: {'n_estimators': 500, 'max_depth': 15, 'min_samples_split': 6, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 2 with value: 0.5447728256655071.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:11:25,478] Trial 5 finished with value: 0.5566183786579693 and parameters: {'n_estimators': 500, 'max_depth': 11, 'min_samples_split': 6, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 5 with value: 0.5566183786579693.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:11:28,998] Trial 6 finished with value: 0.5300835687589676 and parameters: {'n_estimators': 100, 'max_depth': 10, 'min_samples_split': 6, 'min_samples_leaf': 5, 'bootstrap': False}. Best is trial 5 with value: 0.5566183786579693.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:11:42,939] Trial 7 finished with value: 0.46859093361031234 and parameters: {'n_estimators': 500, 'max_depth': 6, 'min_samples_split': 3, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 5 with value: 0.5566183786579693.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:11:45,287] Trial 8 finished with value: 0.5540166950177088 and parameters: {'n_estimators': 100, 'max_depth': 15, 'min_samples_split': 7, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 5 with value: 0.5566183786579693.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:11:57,222] Trial 9 finished with value: 0.457576564710807 and parameters: {'n_estimators': 300, 'max_depth': 13, 'min_samples_split': 4, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 5 with value: 0.5566183786579693.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:12:10,702] Trial 10 finished with value: 0.4781946247535902 and parameters: {'n_estimators': 500, 'max_depth': 11, 'min_samples_split': 9, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 5 with value: 0.5566183786579693.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:12:13,030] Trial 11 finished with value: 0.5545964145080928 and parameters: {'n_estimators': 100, 'max_depth': 12, 'min_samples_split': 8, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 5 with value: 0.5566183786579693.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:12:24,403] Trial 12 finished with value: 0.556324078132689 and parameters: {'n_estimators': 500, 'max_depth': 9, 'min_samples_split': 8, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 5 with value: 0.5566183786579693.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:12:36,473] Trial 13 finished with value: 0.5346903187587857 and parameters: {'n_estimators': 500, 'max_depth': 9, 'min_samples_split': 8, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 5 with value: 0.5566183786579693.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:12:45,973] Trial 14 finished with value: 0.5462063156950272 and parameters: {'n_estimators': 500, 'max_depth': 6, 'min_samples_split': 7, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 5 with value: 0.5566183786579693.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:12:57,365] Trial 15 finished with value: 0.5268533462080279 and parameters: {'n_estimators': 500, 'max_depth': 8, 'min_samples_split': 10, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 5 with value: 0.5566183786579693.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:13:07,617] Trial 16 finished with value: 0.5393510991293593 and parameters: {'n_estimators': 500, 'max_depth': 8, 'min_samples_split': 2, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 5 with value: 0.5566183786579693.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:13:15,864] Trial 17 finished with value: 0.5406441918447102 and parameters: {'n_estimators': 500, 'max_depth': 5, 'min_samples_split': 8, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 5 with value: 0.5566183786579693.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:13:27,925] Trial 18 finished with value: 0.5549303509654131 and parameters: {'n_estimators': 500, 'max_depth': 10, 'min_samples_split': 7, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 5 with value: 0.5566183786579693.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:13:40,872] Trial 19 finished with value: 0.5333603941040486 and parameters: {'n_estimators': 500, 'max_depth': 12, 'min_samples_split': 9, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 5 with value: 0.5566183786579693.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:13:52,681] Trial 20 finished with value: 0.5565027884275482 and parameters: {'n_estimators': 500, 'max_depth': 9, 'min_samples_split': 5, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 5 with value: 0.5566183786579693.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:14:04,390] Trial 21 finished with value: 0.5565027884275482 and parameters: {'n_estimators': 500, 'max_depth': 9, 'min_samples_split': 5, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 5 with value: 0.5566183786579693.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:14:16,697] Trial 22 finished with value: 0.556056881040123 and parameters: {'n_estimators': 500, 'max_depth': 10, 'min_samples_split': 5, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 5 with value: 0.5566183786579693.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:14:27,092] Trial 23 finished with value: 0.5496067175317971 and parameters: {'n_estimators': 500, 'max_depth': 7, 'min_samples_split': 4, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 5 with value: 0.5566183786579693.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:14:39,335] Trial 24 finished with value: 0.5520760456196083 and parameters: {'n_estimators': 500, 'max_depth': 9, 'min_samples_split': 5, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 5 with value: 0.5566183786579693.
[I 2025-09-04 16:14:39,337] A new study created in memory with name: no-name-92fc41b9-99d4-42e3-9943-e61a9537dcf3

✅ RF con TOA_1x1_depth_in_3_4 - Mejor R2: 0.56
📋 Parámetros: {'n_estimators': 500, 'max_depth': 11, 'min_samples_split': 6, 'min_samples_leaf': 3, 'bootstrap': True}

Buscando mejores hiperparámetros para CAT con TOA_1x1_depth_in_3_4...

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:17:55,862] Trial 0 finished with value: 0.5221383873532519 and parameters: {'iterations': 1000, 'learning_rate': 0.03259918372556733, 'depth': 10, 'l2_leaf_reg': 5.067950806068394}. Best is trial 0 with value: 0.5221383873532519.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:19:31,944] Trial 1 finished with value: 0.5269889809308546 and parameters: {'iterations': 500, 'learning_rate': 0.026852019345258327, 'depth': 10, 'l2_leaf_reg': 4.996606788891983}. Best is trial 1 with value: 0.5269889809308546.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:19:51,691] Trial 2 finished with value: 0.5279156611512804 and parameters: {'iterations': 1000, 'learning_rate': 0.061098089731434546, 'depth': 7, 'l2_leaf_reg': 4.7944646733942315}. Best is trial 2 with value: 0.5279156611512804.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:20:40,510] Trial 3 finished with value: 0.569035184267319 and parameters: {'iterations': 1000, 'learning_rate': 0.033260444981323356, 'depth': 8, 'l2_leaf_reg': 1.12206076072196}. Best is trial 3 with value: 0.569035184267319.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:27:14,771] Trial 4 finished with value: 0.5344266531593507 and parameters: {'iterations': 2000, 'learning_rate': 0.0627600010612224, 'depth': 10, 'l2_leaf_reg': 3.0131893186430454}. Best is trial 3 with value: 0.569035184267319.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:28:49,645] Trial 5 finished with value: 0.5311338236710687 and parameters: {'iterations': 2000, 'learning_rate': 0.05577276653270756, 'depth': 8, 'l2_leaf_reg': 5.59335154860565}. Best is trial 3 with value: 0.569035184267319.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:29:05,303] Trial 6 finished with value: 0.5293880923884018 and parameters: {'iterations': 2000, 'learning_rate': 0.02008288545062884, 'depth': 6, 'l2_leaf_reg': 2.883003491842612}. Best is trial 3 with value: 0.569035184267319.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:29:10,432] Trial 7 finished with value: 0.5076136435142855 and parameters: {'iterations': 1000, 'learning_rate': 0.05915551321765933, 'depth': 5, 'l2_leaf_reg': 4.076301136542039}. Best is trial 3 with value: 0.569035184267319.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:35:49,828] Trial 8 finished with value: 0.5512164266206101 and parameters: {'iterations': 2000, 'learning_rate': 0.038381729576125886, 'depth': 10, 'l2_leaf_reg': 1.016723015436369}. Best is trial 3 with value: 0.569035184267319.
[I 2025-09-04 16:35:49,830] A new study created in memory with name: no-name-28190ec7-7ee7-47f5-93fa-089b6726a2ad
[I 2025-09-04 16:35:49,940] Trial 0 finished with value: 0.3306265013155717 and parameters: {'alpha': 0.26859354286863263, 'l1_ratio': 0.3621681711912188}. Best is trial 0 with value: 0.3306265013155717.

✅ CAT con TOA_1x1_depth_in_3_4 - Mejor R2: 0.57
📋 Parámetros: {'iterations': 1000, 'learning_rate': 0.033260444981323356, 'depth': 8, 'l2_leaf_reg': 1.12206076072196}

Buscando mejores hiperparámetros para ELN con TOA_1x1_depth_in_3_4...

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.639e-01, tolerance: 3.985e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 16:35:50,113] Trial 1 finished with value: 0.43142954048164806 and parameters: {'alpha': 0.010258435953086231, 'l1_ratio': 0.7155134411121523}. Best is trial 1 with value: 0.43142954048164806.

Fold 4
Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 16:35:50,286] Trial 2 finished with value: 0.3317471295979144 and parameters: {'alpha': 0.14227892304011452, 'l1_ratio': 0.6778704331507813}. Best is trial 1 with value: 0.43142954048164806.
[I 2025-09-04 16:35:50,414] Trial 3 finished with value: 0.19214920922955325 and parameters: {'alpha': 0.7132309373626033, 'l1_ratio': 0.761591218984509}. Best is trial 1 with value: 0.43142954048164806.

Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.351e+01, tolerance: 4.075e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.056e+02, tolerance: 4.583e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.732e+01, tolerance: 3.985e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.197e+02, tolerance: 5.497e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.608e+01, tolerance: 4.044e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 16:35:50,597] Trial 4 finished with value: 0.412463509975159 and parameters: {'alpha': 0.001315149454962733, 'l1_ratio': 0.09033606895318869}. Best is trial 1 with value: 0.43142954048164806.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.584e+01, tolerance: 4.075e-02
  model = cd_fast.enet_coordinate_descent(

Fold 3
Fold 4
Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.121e+02, tolerance: 4.583e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.787e+01, tolerance: 3.985e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.225e+02, tolerance: 5.497e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.072e+02, tolerance: 4.044e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 16:35:50,791] Trial 5 finished with value: 0.3789091471467101 and parameters: {'alpha': 0.00011762999218862108, 'l1_ratio': 0.2415430626294276}. Best is trial 1 with value: 0.43142954048164806.

Fold 4
Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 16:35:50,959] Trial 6 finished with value: 0.4212112238893926 and parameters: {'alpha': 0.09086726611570384, 'l1_ratio': 0.34623739947348187}. Best is trial 1 with value: 0.43142954048164806.

Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.565e+00, tolerance: 4.075e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.716e+00, tolerance: 4.583e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.844e+00, tolerance: 3.985e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.865e+00, tolerance: 5.497e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.085e-01, tolerance: 4.044e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 16:35:51,249] Trial 7 finished with value: 0.404810077267329 and parameters: {'alpha': 0.004337845238375941, 'l1_ratio': 0.5854931888605852}. Best is trial 1 with value: 0.43142954048164806.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.530e+00, tolerance: 4.075e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.035e+00, tolerance: 4.583e-02
  model = cd_fast.enet_coordinate_descent(

Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.815e+00, tolerance: 3.985e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.008e+00, tolerance: 5.497e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.676e-01, tolerance: 4.044e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 16:35:51,468] Trial 8 finished with value: 0.4326248320580768 and parameters: {'alpha': 0.014316590198946563, 'l1_ratio': 0.2639478884414094}. Best is trial 8 with value: 0.4326248320580768.
[I 2025-09-04 16:35:51,582] Trial 9 finished with value: 0.3316642657545287 and parameters: {'alpha': 0.12300059307281906, 'l1_ratio': 0.7796327229233522}. Best is trial 8 with value: 0.4326248320580768.

Fold 4
Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1

[I 2025-09-04 16:35:51,706] Trial 10 finished with value: 0.45080929266320957 and parameters: {'alpha': 0.028286214371931784, 'l1_ratio': 0.9300519111833095}. Best is trial 10 with value: 0.45080929266320957.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.020e+02, tolerance: 4.075e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.176e+02, tolerance: 4.583e-02
  model = cd_fast.enet_coordinate_descent(

Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.487e+01, tolerance: 3.985e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.394e+02, tolerance: 5.497e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.097e+02, tolerance: 4.044e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 16:35:51,882] Trial 11 finished with value: 0.4303692394351619 and parameters: {'alpha': 0.01845410731120165, 'l1_ratio': 0.017559039077148675}. Best is trial 10 with value: 0.45080929266320957.

Fold 4
Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:35:52,067] Trial 12 finished with value: 0.451630404008608 and parameters: {'alpha': 0.028283841413022752, 'l1_ratio': 0.9109286287993379}. Best is trial 12 with value: 0.451630404008608.
[I 2025-09-04 16:35:52,259] Trial 13 finished with value: 0.43283556152213176 and parameters: {'alpha': 0.03277520742329317, 'l1_ratio': 0.9952460595985634}. Best is trial 12 with value: 0.451630404008608.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.290e+00, tolerance: 4.075e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.280e+00, tolerance: 4.583e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.514e+01, tolerance: 3.985e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.431e+00, tolerance: 5.497e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.385e+00, tolerance: 4.044e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 16:35:52,456] Trial 14 finished with value: 0.39311576640030954 and parameters: {'alpha': 0.0021557102947445082, 'l1_ratio': 0.9489524133026748}. Best is trial 12 with value: 0.451630404008608.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2

[I 2025-09-04 16:35:52,629] Trial 15 finished with value: 0.4271677125494534 and parameters: {'alpha': 0.0376602316759635, 'l1_ratio': 0.8824443579103076}. Best is trial 12 with value: 0.451630404008608.

Fold 3
Fold 4
Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.388e+01, tolerance: 4.075e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.903e+01, tolerance: 4.583e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.370e+01, tolerance: 3.985e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.218e+01, tolerance: 5.497e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.208e+01, tolerance: 4.044e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 16:35:52,914] Trial 16 finished with value: 0.3961881702933837 and parameters: {'alpha': 0.0005096735883123992, 'l1_ratio': 0.5074011503199489}. Best is trial 12 with value: 0.451630404008608.

Fold 3
Fold 4
Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1

[I 2025-09-04 16:35:53,085] Trial 17 finished with value: 0.14196000784965823 and parameters: {'alpha': 0.9135315060160076, 'l1_ratio': 0.865779036770832}. Best is trial 12 with value: 0.451630404008608.

Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.628e+00, tolerance: 4.075e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.186e+00, tolerance: 4.583e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.464e+00, tolerance: 3.985e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.045e+01, tolerance: 5.497e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.588e+00, tolerance: 4.044e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 16:35:53,272] Trial 18 finished with value: 0.4017626682789641 and parameters: {'alpha': 0.003718383995537072, 'l1_ratio': 0.6140100564476236}. Best is trial 12 with value: 0.451630404008608.

Fold 4
Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:35:53,416] Trial 19 finished with value: 0.42373670758106796 and parameters: {'alpha': 0.04043619801742755, 'l1_ratio': 0.8608293127711376}. Best is trial 12 with value: 0.451630404008608.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.827e+01, tolerance: 4.075e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.636e+01, tolerance: 4.583e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.567e+01, tolerance: 3.985e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.736e+01, tolerance: 5.497e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.171e+01, tolerance: 4.044e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 16:35:53,585] Trial 20 finished with value: 0.3970770066358643 and parameters: {'alpha': 0.0006096259311132589, 'l1_ratio': 0.9982445154652794}. Best is trial 12 with value: 0.451630404008608.

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1

[I 2025-09-04 16:35:53,735] Trial 21 finished with value: 0.43411786997072266 and parameters: {'alpha': 0.03292970368687093, 'l1_ratio': 0.9439264204856626}. Best is trial 12 with value: 0.451630404008608.

Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 16:35:53,858] Trial 22 finished with value: 0.3863663836576884 and parameters: {'alpha': 0.06398936450960681, 'l1_ratio': 0.8268563756889481}. Best is trial 12 with value: 0.451630404008608.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.047e-01, tolerance: 4.075e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.260e-01, tolerance: 4.583e-02
  model = cd_fast.enet_coordinate_descent(

Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.144e-01, tolerance: 3.985e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.719e-01, tolerance: 5.497e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.738e-02, tolerance: 4.044e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 16:35:54,117] Trial 23 finished with value: 0.4134184951097355 and parameters: {'alpha': 0.007322327173697099, 'l1_ratio': 0.9205641742508343}. Best is trial 12 with value: 0.451630404008608.
[I 2025-09-04 16:35:54,268] Trial 24 finished with value: 0.2894533218133859 and parameters: {'alpha': 0.2681453447049023, 'l1_ratio': 0.785761102893498}. Best is trial 12 with value: 0.451630404008608.
[I 2025-09-04 16:35:54,270] A new study created in memory with name: no-name-b9c0deb6-43f8-4ede-a796-87340752b117

Fold 5

=== Procesando TOA_1x1_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

✅ ELN con TOA_1x1_depth_in_3_4 - Mejor R2: 0.45
📋 Parámetros: {'alpha': 0.028283841413022752, 'l1_ratio': 0.9109286287993379}

Buscando mejores hiperparámetros para XGB con TOA_15x15_depth_in_3_4...

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:36:02,854] Trial 0 finished with value: 0.5725701768350139 and parameters: {'n_estimators': 1000, 'learning_rate': 0.03963742087171049, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.8190914450496477, 'colsample_bytree': 0.9091367285514638}. Best is trial 0 with value: 0.5725701768350139.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:36:10,680] Trial 1 finished with value: 0.5829762947126991 and parameters: {'n_estimators': 1000, 'learning_rate': 0.012943440532253624, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.6870048330294467, 'colsample_bytree': 0.7992357694052132}. Best is trial 1 with value: 0.5829762947126991.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:36:23,054] Trial 2 finished with value: 0.5708351913159564 and parameters: {'n_estimators': 2000, 'learning_rate': 0.019682435016404216, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.8655480705853811, 'colsample_bytree': 0.7528210358009721}. Best is trial 1 with value: 0.5829762947126991.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:36:32,997] Trial 3 finished with value: 0.5674105699012293 and parameters: {'n_estimators': 1000, 'learning_rate': 0.009112325022059286, 'max_depth': 8, 'min_child_weight': 3, 'subsample': 0.9217636851556431, 'colsample_bytree': 0.871025650948734}. Best is trial 1 with value: 0.5829762947126991.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:36:41,229] Trial 4 finished with value: 0.5632428344092497 and parameters: {'n_estimators': 1000, 'learning_rate': 0.027238757150794858, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.8177208868701957, 'colsample_bytree': 0.7486069216060249}. Best is trial 1 with value: 0.5829762947126991.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:36:52,684] Trial 5 finished with value: 0.5725372800745828 and parameters: {'n_estimators': 2000, 'learning_rate': 0.027538966845956702, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.9405163450458229, 'colsample_bytree': 0.7181041445775627}. Best is trial 1 with value: 0.5829762947126991.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:36:57,697] Trial 6 finished with value: 0.603983168357872 and parameters: {'n_estimators': 1000, 'learning_rate': 0.010544059164197019, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.7538195807227366, 'colsample_bytree': 0.75229465277524}. Best is trial 6 with value: 0.603983168357872.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:37:00,693] Trial 7 finished with value: 0.5362471915415538 and parameters: {'n_estimators': 500, 'learning_rate': 0.0050022470123570325, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.838676648281961, 'colsample_bytree': 0.8190787733410047}. Best is trial 6 with value: 0.603983168357872.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:37:09,140] Trial 8 finished with value: 0.5512290510618609 and parameters: {'n_estimators': 1000, 'learning_rate': 0.00622323658797787, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.937569494783855, 'colsample_bytree': 0.7595594988547463}. Best is trial 6 with value: 0.603983168357872.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:37:31,393] Trial 9 finished with value: 0.5610271445437156 and parameters: {'n_estimators': 2000, 'learning_rate': 0.016660629292750646, 'max_depth': 8, 'min_child_weight': 2, 'subsample': 0.7264678094189794, 'colsample_bytree': 0.8115562029985631}. Best is trial 6 with value: 0.603983168357872.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:37:34,965] Trial 10 finished with value: 0.5836425385683537 and parameters: {'n_estimators': 500, 'learning_rate': 0.009508305985457498, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.6156070182284091, 'colsample_bytree': 0.9861958719914631}. Best is trial 6 with value: 0.603983168357872.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:37:38,709] Trial 11 finished with value: 0.5832101736312592 and parameters: {'n_estimators': 500, 'learning_rate': 0.009810029998395323, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.6231106656397509, 'colsample_bytree': 0.9850551805441993}. Best is trial 6 with value: 0.603983168357872.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:37:41,604] Trial 12 finished with value: 0.5965296610752248 and parameters: {'n_estimators': 500, 'learning_rate': 0.009550698483421662, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.6046732459744093, 'colsample_bytree': 0.6137199434410783}. Best is trial 6 with value: 0.603983168357872.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:37:44,993] Trial 13 finished with value: 0.5577168594802699 and parameters: {'n_estimators': 500, 'learning_rate': 0.0077112197113702674, 'max_depth': 5, 'min_child_weight': 1, 'subsample': 0.7299441537940228, 'colsample_bytree': 0.6424663356956041}. Best is trial 6 with value: 0.603983168357872.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:37:47,699] Trial 14 finished with value: 0.6069789617288579 and parameters: {'n_estimators': 500, 'learning_rate': 0.013566967402918429, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.6807531615273382, 'colsample_bytree': 0.607434439562925}. Best is trial 14 with value: 0.6069789617288579.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:37:53,823] Trial 15 finished with value: 0.6013430829531211 and parameters: {'n_estimators': 1000, 'learning_rate': 0.012762376608483995, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.7438509407488483, 'colsample_bytree': 0.6754785678342972}. Best is trial 14 with value: 0.6069789617288579.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:37:59,370] Trial 16 finished with value: 0.530014054495717 and parameters: {'n_estimators': 500, 'learning_rate': 0.02048380724020154, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.6688024860842585, 'colsample_bytree': 0.6748570162834571}. Best is trial 14 with value: 0.6069789617288579.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:38:11,412] Trial 17 finished with value: 0.593204293394989 and parameters: {'n_estimators': 1000, 'learning_rate': 0.013099370604069734, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.7682284137025172, 'colsample_bytree': 0.692068245790802}. Best is trial 14 with value: 0.6069789617288579.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:38:17,771] Trial 18 finished with value: 0.5663030680186518 and parameters: {'n_estimators': 500, 'learning_rate': 0.00709492650940301, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.6778468036338609, 'colsample_bytree': 0.6051291481883786}. Best is trial 14 with value: 0.6069789617288579.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:38:25,215] Trial 19 finished with value: 0.5767333220251026 and parameters: {'n_estimators': 500, 'learning_rate': 0.047102943522568066, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.9934763020505277, 'colsample_bytree': 0.8768847193452023}. Best is trial 14 with value: 0.6069789617288579.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:38:41,050] Trial 20 finished with value: 0.5799321340927146 and parameters: {'n_estimators': 2000, 'learning_rate': 0.015846942760138462, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.776307422557276, 'colsample_bytree': 0.6489492419941133}. Best is trial 14 with value: 0.6069789617288579.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:38:45,411] Trial 21 finished with value: 0.6040479864718824 and parameters: {'n_estimators': 1000, 'learning_rate': 0.012303572485062947, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.7308467745377782, 'colsample_bytree': 0.7021266167286054}. Best is trial 14 with value: 0.6069789617288579.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:38:50,769] Trial 22 finished with value: 0.6046082946712107 and parameters: {'n_estimators': 1000, 'learning_rate': 0.012141852344335428, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.7031722646849488, 'colsample_bytree': 0.7053871618880134}. Best is trial 14 with value: 0.6069789617288579.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:38:55,455] Trial 23 finished with value: 0.6056582466331886 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01244790597118965, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.7041366004869755, 'colsample_bytree': 0.711773827176903}. Best is trial 14 with value: 0.6069789617288579.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:39:01,227] Trial 24 finished with value: 0.5936426531721082 and parameters: {'n_estimators': 1000, 'learning_rate': 0.019590104668182923, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.6489384644695075, 'colsample_bytree': 0.6408259407612641}. Best is trial 14 with value: 0.6069789617288579.
[I 2025-09-04 16:39:01,229] A new study created in memory with name: no-name-76e6bbab-b1c6-4167-95ec-c381084c75a5

✅ XGB con TOA_15x15_depth_in_3_4 - Mejor R2: 0.61
📋 Parámetros: {'n_estimators': 500, 'learning_rate': 0.013566967402918429, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.6807531615273382, 'colsample_bytree': 0.607434439562925}

Buscando mejores hiperparámetros para LBM con TOA_15x15_depth_in_3_4...

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 16:39:01,585] Trial 0 finished with value: 0.583816088105557 and parameters: {'learning_rate': 0.006448869516002845, 'num_leaves': 40, 'max_depth': 5, 'min_child_samples': 6, 'subsample': 0.8189503809853271, 'colsample_bytree': 0.6251816502161387, 'n_estimators': 500}. Best is trial 0 with value: 0.583816088105557.

Fold 4
Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 16:39:01,939] Trial 1 finished with value: 0.48780300499250706 and parameters: {'learning_rate': 0.02560372893733057, 'num_leaves': 40, 'max_depth': 5, 'min_child_samples': 5, 'subsample': 0.7896736275255498, 'colsample_bytree': 0.9819878888641531, 'n_estimators': 500}. Best is trial 0 with value: 0.583816088105557.

Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:39:02,294] Trial 2 finished with value: 0.601999358202151 and parameters: {'learning_rate': 0.007937865492366273, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 10, 'subsample': 0.7053235826656086, 'colsample_bytree': 0.9518953088614963, 'n_estimators': 500}. Best is trial 2 with value: 0.601999358202151.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:39:03,433] Trial 3 finished with value: 0.5534828626778103 and parameters: {'learning_rate': 0.008347269462965812, 'num_leaves': 40, 'max_depth': 5, 'min_child_samples': 6, 'subsample': 0.6128035574731094, 'colsample_bytree': 0.7019345002270426, 'n_estimators': 2000}. Best is trial 2 with value: 0.601999358202151.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 16:39:03,870] Trial 4 finished with value: 0.5862189922381316 and parameters: {'learning_rate': 0.011128958847107366, 'num_leaves': 60, 'max_depth': 6, 'min_child_samples': 8, 'subsample': 0.8644184835086525, 'colsample_bytree': 0.8615488608956874, 'n_estimators': 500}. Best is trial 2 with value: 0.601999358202151.

Fold 4
Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 16:39:04,291] Trial 5 finished with value: 0.6122255138539023 and parameters: {'learning_rate': 0.021619066251164484, 'num_leaves': 80, 'max_depth': 7, 'min_child_samples': 12, 'subsample': 0.696274008124939, 'colsample_bytree': 0.8362254326236265, 'n_estimators': 500}. Best is trial 5 with value: 0.6122255138539023.

Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:39:05,036] Trial 6 finished with value: 0.6109607448364995 and parameters: {'learning_rate': 0.04388957720310936, 'num_leaves': 60, 'max_depth': 8, 'min_child_samples': 15, 'subsample': 0.9744859254523877, 'colsample_bytree': 0.6423815257408958, 'n_estimators': 1000}. Best is trial 5 with value: 0.6122255138539023.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:39:06,619] Trial 7 finished with value: 0.5625679476902163 and parameters: {'learning_rate': 0.044794195811202614, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 9, 'subsample': 0.7972471945770176, 'colsample_bytree': 0.9940034060517502, 'n_estimators': 2000}. Best is trial 5 with value: 0.6122255138539023.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 16:39:07,292] Trial 8 finished with value: 0.5948874694989128 and parameters: {'learning_rate': 0.01862595106111898, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 7, 'subsample': 0.9319362873434772, 'colsample_bytree': 0.6559423376885277, 'n_estimators': 1000}. Best is trial 5 with value: 0.6122255138539023.

Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:39:08,550] Trial 9 finished with value: 0.5893339910222851 and parameters: {'learning_rate': 0.02615787464630177, 'num_leaves': 40, 'max_depth': 6, 'min_child_samples': 12, 'subsample': 0.7721883200875607, 'colsample_bytree': 0.968832662864366, 'n_estimators': 2000}. Best is trial 5 with value: 0.6122255138539023.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 16:39:09,016] Trial 10 finished with value: 0.6200674857325003 and parameters: {'learning_rate': 0.014894077130762363, 'num_leaves': 80, 'max_depth': 8, 'min_child_samples': 13, 'subsample': 0.6116619117361499, 'colsample_bytree': 0.8065256585042461, 'n_estimators': 500}. Best is trial 10 with value: 0.6200674857325003.

Fold 4
Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 16:39:09,480] Trial 11 finished with value: 0.6257851533182208 and parameters: {'learning_rate': 0.015206822560871934, 'num_leaves': 80, 'max_depth': 8, 'min_child_samples': 13, 'subsample': 0.6078213588212668, 'colsample_bytree': 0.7992032194357178, 'n_estimators': 500}. Best is trial 11 with value: 0.6257851533182208.

Fold 4
Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 16:39:09,902] Trial 12 finished with value: 0.598247026343458 and parameters: {'learning_rate': 0.013115102461563232, 'num_leaves': 80, 'max_depth': 8, 'min_child_samples': 16, 'subsample': 0.6005602686549126, 'colsample_bytree': 0.7636952736121666, 'n_estimators': 500}. Best is trial 11 with value: 0.6257851533182208.

Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:39:10,376] Trial 13 finished with value: 0.6265984436745506 and parameters: {'learning_rate': 0.01434397773832977, 'num_leaves': 80, 'max_depth': 8, 'min_child_samples': 13, 'subsample': 0.6716607007661958, 'colsample_bytree': 0.76888063272416, 'n_estimators': 500}. Best is trial 13 with value: 0.6265984436745506.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 16:39:10,798] Trial 14 finished with value: 0.5930987125622911 and parameters: {'learning_rate': 0.010328967467326698, 'num_leaves': 80, 'max_depth': 7, 'min_child_samples': 14, 'subsample': 0.6823258648508044, 'colsample_bytree': 0.7485882151293732, 'n_estimators': 500}. Best is trial 13 with value: 0.6265984436745506.

Fold 4
Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:39:11,739] Trial 15 finished with value: 0.6152799187472113 and parameters: {'learning_rate': 0.01644442134949819, 'num_leaves': 80, 'max_depth': 8, 'min_child_samples': 11, 'subsample': 0.6559811255181761, 'colsample_bytree': 0.895711055266244, 'n_estimators': 1000}. Best is trial 13 with value: 0.6265984436745506.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 16:39:12,165] Trial 16 finished with value: 0.5632874981484293 and parameters: {'learning_rate': 0.005254047060303354, 'num_leaves': 80, 'max_depth': 7, 'min_child_samples': 14, 'subsample': 0.7298088574163639, 'colsample_bytree': 0.7392448073158826, 'n_estimators': 500}. Best is trial 13 with value: 0.6265984436745506.

Fold 4
Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 16:39:12,609] Trial 17 finished with value: 0.6051153879523873 and parameters: {'learning_rate': 0.0314511674503234, 'num_leaves': 80, 'max_depth': 8, 'min_child_samples': 16, 'subsample': 0.6481282048235214, 'colsample_bytree': 0.7049625415153848, 'n_estimators': 500}. Best is trial 13 with value: 0.6265984436745506.

Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:39:14,406] Trial 18 finished with value: 0.6209216690946847 and parameters: {'learning_rate': 0.01245996507638887, 'num_leaves': 80, 'max_depth': 8, 'min_child_samples': 11, 'subsample': 0.7306509136924104, 'colsample_bytree': 0.79259068939091, 'n_estimators': 2000}. Best is trial 13 with value: 0.6265984436745506.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 16:39:15,235] Trial 19 finished with value: 0.6322268377128871 and parameters: {'learning_rate': 0.00909468587481228, 'num_leaves': 60, 'max_depth': 7, 'min_child_samples': 13, 'subsample': 0.6536720142119191, 'colsample_bytree': 0.8953446248078664, 'n_estimators': 1000}. Best is trial 19 with value: 0.6322268377128871.

Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:39:16,128] Trial 20 finished with value: 0.6062466952077017 and parameters: {'learning_rate': 0.008711907090104595, 'num_leaves': 60, 'max_depth': 7, 'min_child_samples': 10, 'subsample': 0.8537147214328628, 'colsample_bytree': 0.896366020558454, 'n_estimators': 1000}. Best is trial 19 with value: 0.6322268377128871.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 16:39:17,028] Trial 21 finished with value: 0.6311499563287271 and parameters: {'learning_rate': 0.015432692178767984, 'num_leaves': 60, 'max_depth': 8, 'min_child_samples': 13, 'subsample': 0.6530593663477628, 'colsample_bytree': 0.9148055755369796, 'n_estimators': 1000}. Best is trial 19 with value: 0.6322268377128871.

Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 16:39:17,920] Trial 22 finished with value: 0.6101587902715223 and parameters: {'learning_rate': 0.010226505822498663, 'num_leaves': 60, 'max_depth': 7, 'min_child_samples': 14, 'subsample': 0.6628444549476523, 'colsample_bytree': 0.9027919773870086, 'n_estimators': 1000}. Best is trial 19 with value: 0.6322268377128871.

Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:39:18,872] Trial 23 finished with value: 0.5980418513115 and parameters: {'learning_rate': 0.019085779336778977, 'num_leaves': 60, 'max_depth': 8, 'min_child_samples': 12, 'subsample': 0.7412659007806766, 'colsample_bytree': 0.9362285278160049, 'n_estimators': 1000}. Best is trial 19 with value: 0.6322268377128871.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 16:39:19,661] Trial 24 finished with value: 0.5949720275568352 and parameters: {'learning_rate': 0.0066543185458980665, 'num_leaves': 60, 'max_depth': 7, 'min_child_samples': 15, 'subsample': 0.6443724195265707, 'colsample_bytree': 0.8465191035604288, 'n_estimators': 1000}. Best is trial 19 with value: 0.6322268377128871.
[I 2025-09-04 16:39:19,663] A new study created in memory with name: no-name-6bc0dd23-4dac-427f-b3f0-f0801288962e

Fold 5

✅ LBM con TOA_15x15_depth_in_3_4 - Mejor R2: 0.63
📋 Parámetros: {'learning_rate': 0.00909468587481228, 'num_leaves': 60, 'max_depth': 7, 'min_child_samples': 13, 'subsample': 0.6536720142119191, 'colsample_bytree': 0.8953446248078664, 'n_estimators': 1000}

Buscando mejores hiperparámetros para MLP con TOA_15x15_depth_in_3_4...

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:39:21,178] Trial 0 finished with value: 0.6816671881563978 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 9.28477694475083e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0004925025419308163}. Best is trial 0 with value: 0.6816671881563978.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-04 16:39:22,959] Trial 1 finished with value: 0.6034240491290237 and parameters: {'hidden_layer_sizes': '128', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0009657942461971037, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00012826673742542227}. Best is trial 0 with value: 0.6816671881563978.

Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

[I 2025-09-04 16:39:24,747] Trial 2 finished with value: 0.5215611134834199 and parameters: {'hidden_layer_sizes': '128', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.06056303406995729, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00020095996599599778}. Best is trial 0 with value: 0.6816671881563978.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:39:26,024] Trial 3 finished with value: 0.6639560994774206 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.013974972727295774, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0008034383058022506}. Best is trial 0 with value: 0.6816671881563978.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-04 16:39:27,460] Trial 4 finished with value: 0.6679048238872728 and parameters: {'hidden_layer_sizes': '256', 'activation': 'relu', 'solver': 'adam', 'alpha': 1.3246366620386508e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.0002705044283143817}. Best is trial 0 with value: 0.6816671881563978.

Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-04 16:39:33,432] Trial 5 finished with value: 0.5470726122643415 and parameters: {'hidden_layer_sizes': '256_128', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.06970687691844978, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00020813506571133047}. Best is trial 0 with value: 0.6816671881563978.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

[I 2025-09-04 16:39:36,150] Trial 6 finished with value: 0.6691390840913438 and parameters: {'hidden_layer_sizes': '256', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0003851300509647009, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00025575519533333076}. Best is trial 0 with value: 0.6816671881563978.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 16:39:37,246] Trial 7 finished with value: 0.6904999087037753 and parameters: {'hidden_layer_sizes': '256', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.00010596899110304532, 'learning_rate': 'constant', 'learning_rate_init': 0.005576659744054297}. Best is trial 7 with value: 0.6904999087037753.

Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-04 16:39:39,797] Trial 8 finished with value: 0.6363591568178885 and parameters: {'hidden_layer_sizes': '256', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.05659320262595252, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0007211804765542003}. Best is trial 7 with value: 0.6904999087037753.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-04 16:39:42,771] Trial 9 finished with value: 0.5542954835107751 and parameters: {'hidden_layer_sizes': '128', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.0005087594900950747, 'learning_rate': 'adaptive', 'learning_rate_init': 0.003374007626642089}. Best is trial 7 with value: 0.6904999087037753.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:39:46,382] Trial 10 finished with value: 0.5154017107873436 and parameters: {'hidden_layer_sizes': '256_128', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 1.0646641932363166e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.009950026592233062}. Best is trial 7 with value: 0.6904999087037753.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:39:47,618] Trial 11 finished with value: 0.6102062741112211 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 9.347089296382677e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.002597371736562526}. Best is trial 7 with value: 0.6904999087037753.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:39:48,637] Trial 12 finished with value: 0.6482418667697916 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 7.899855979962512e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.0022765220643973178}. Best is trial 7 with value: 0.6904999087037753.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 16:39:49,484] Trial 13 finished with value: 0.652080560604742 and parameters: {'hidden_layer_sizes': '256', 'activation': 'relu', 'solver': 'adam', 'alpha': 8.405407649864313e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.008425209890758352}. Best is trial 7 with value: 0.6904999087037753.

Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:39:51,595] Trial 14 finished with value: 0.5950727416872532 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.004457039344921439, 'learning_rate': 'constant', 'learning_rate_init': 0.000567280261482423}. Best is trial 7 with value: 0.6904999087037753.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:39:52,848] Trial 15 finished with value: 0.6270610277216551 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.00020074948602382314, 'learning_rate': 'constant', 'learning_rate_init': 0.001507196063827897}. Best is trial 7 with value: 0.6904999087037753.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:39:53,777] Trial 16 finished with value: 0.6946289371191103 and parameters: {'hidden_layer_sizes': '256', 'activation': 'relu', 'solver': 'adam', 'alpha': 3.4641254872155115e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.004878036398679722}. Best is trial 16 with value: 0.6946289371191103.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:39:54,562] Trial 17 finished with value: 0.7018057751528828 and parameters: {'hidden_layer_sizes': '256', 'activation': 'relu', 'solver': 'adam', 'alpha': 2.8848839247272062e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.005324276541312029}. Best is trial 17 with value: 0.7018057751528828.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-04 16:39:57,819] Trial 18 finished with value: 0.5647461434148211 and parameters: {'hidden_layer_sizes': '256', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 2.6079530854141287e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00465900214163576}. Best is trial 17 with value: 0.7018057751528828.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:39:58,749] Trial 19 finished with value: 0.6969611102533972 and parameters: {'hidden_layer_sizes': '256', 'activation': 'relu', 'solver': 'adam', 'alpha': 3.485824390122328e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.0015955210631503145}. Best is trial 17 with value: 0.7018057751528828.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:39:59,974] Trial 20 finished with value: 0.7049615499487862 and parameters: {'hidden_layer_sizes': '256', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.003654873137817294, 'learning_rate': 'constant', 'learning_rate_init': 0.0013277028760977432}. Best is trial 20 with value: 0.7049615499487862.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:40:01,026] Trial 21 finished with value: 0.7067100936658487 and parameters: {'hidden_layer_sizes': '256', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.003963386592700679, 'learning_rate': 'constant', 'learning_rate_init': 0.001370485378363497}. Best is trial 21 with value: 0.7067100936658487.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:40:02,086] Trial 22 finished with value: 0.7081781717048119 and parameters: {'hidden_layer_sizes': '256', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0034242834875374936, 'learning_rate': 'constant', 'learning_rate_init': 0.0012220669807227185}. Best is trial 22 with value: 0.7081781717048119.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:40:03,220] Trial 23 finished with value: 0.7076530523093525 and parameters: {'hidden_layer_sizes': '256', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0036731377823373094, 'learning_rate': 'constant', 'learning_rate_init': 0.0012331457298738872}. Best is trial 22 with value: 0.7081781717048119.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 16:40:05,066] Trial 24 finished with value: 0.6511219379757069 and parameters: {'hidden_layer_sizes': '256_128', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.003498761298880984, 'learning_rate': 'constant', 'learning_rate_init': 0.0011470011519462292}. Best is trial 22 with value: 0.7081781717048119.

Fold 5

[I 2025-09-04 16:40:05,068] A new study created in memory with name: no-name-fd0ec692-5814-4b20-8e74-3e9ffa9c03d1
[I 2025-09-04 16:40:05,180] Trial 0 finished with value: 0.2128410940423464 and parameters: {'C': 0.2497085151046542, 'epsilon': 0.14465177856286024}. Best is trial 0 with value: 0.2128410940423464.

✅ MLP con TOA_15x15_depth_in_3_4 - Mejor R2: 0.71
📋 Parámetros: {'hidden_layer_sizes': '256', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0034242834875374936, 'learning_rate': 'constant', 'learning_rate_init': 0.0012220669807227185}

Buscando mejores hiperparámetros para SVR con TOA_15x15_depth_in_3_4...

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:40:05,270] Trial 1 finished with value: 0.48621167126909637 and parameters: {'C': 3.8375951327615025, 'epsilon': 0.13596452940209489}. Best is trial 1 with value: 0.48621167126909637.
[I 2025-09-04 16:40:05,369] Trial 2 finished with value: 0.3648517952608683 and parameters: {'C': 0.615702775950285, 'epsilon': 0.040283639854266036}. Best is trial 1 with value: 0.48621167126909637.
[I 2025-09-04 16:40:05,468] Trial 3 finished with value: 0.46991598040680504 and parameters: {'C': 9.959807320614159, 'epsilon': 0.06897988833096362}. Best is trial 1 with value: 0.48621167126909637.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1

[I 2025-09-04 16:40:05,561] Trial 4 finished with value: 0.49081226966240055 and parameters: {'C': 3.033294962990516, 'epsilon': 0.14584413224473836}. Best is trial 4 with value: 0.49081226966240055.
[I 2025-09-04 16:40:05,676] Trial 5 finished with value: 0.49261268529180713 and parameters: {'C': 2.5440507196903432, 'epsilon': 0.10574775015768093}. Best is trial 5 with value: 0.49261268529180713.

Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1

[I 2025-09-04 16:40:05,769] Trial 6 finished with value: 0.33772591179596423 and parameters: {'C': 0.47816481384070103, 'epsilon': 0.12175057296986291}. Best is trial 5 with value: 0.49261268529180713.
[I 2025-09-04 16:40:05,868] Trial 7 finished with value: 0.479805447724446 and parameters: {'C': 4.217063218130322, 'epsilon': 0.07465131549463713}. Best is trial 5 with value: 0.49261268529180713.

Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2

[I 2025-09-04 16:40:05,965] Trial 8 finished with value: 0.48337287431209797 and parameters: {'C': 1.6174546561549805, 'epsilon': 0.07459033178540864}. Best is trial 5 with value: 0.49261268529180713.
[I 2025-09-04 16:40:06,059] Trial 9 finished with value: 0.20294909004445627 and parameters: {'C': 0.2456639470221539, 'epsilon': 0.05490793291111249}. Best is trial 5 with value: 0.49261268529180713.

Fold 3
Fold 4
Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 16:40:06,165] Trial 10 finished with value: 0.4660444426142657 and parameters: {'C': 1.2766089890798586, 'epsilon': 0.010033233787594159}. Best is trial 5 with value: 0.49261268529180713.
[I 2025-09-04 16:40:06,271] Trial 11 finished with value: 0.4927538326713956 and parameters: {'C': 2.9495946685578867, 'epsilon': 0.19309878971290145}. Best is trial 11 with value: 0.4927538326713956.

Fold 4
Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 16:40:06,382] Trial 12 finished with value: 0.4726437785379227 and parameters: {'C': 9.792503757114602, 'epsilon': 0.19584017163515352}. Best is trial 11 with value: 0.4927538326713956.
[I 2025-09-04 16:40:06,478] Trial 13 finished with value: 0.4919314566278551 and parameters: {'C': 2.2576387106446574, 'epsilon': 0.19984271515060414}. Best is trial 11 with value: 0.4927538326713956.

Fold 4
Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 16:40:06,574] Trial 14 finished with value: 0.4175325789813361 and parameters: {'C': 0.7703400898796229, 'epsilon': 0.16823231163187727}. Best is trial 11 with value: 0.4927538326713956.
[I 2025-09-04 16:40:06,672] Trial 15 finished with value: 0.06923794192519128 and parameters: {'C': 0.10936917642437397, 'epsilon': 0.10639534414064584}. Best is trial 11 with value: 0.4927538326713956.

Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:40:06,771] Trial 16 finished with value: 0.47247482311151456 and parameters: {'C': 5.162005527291065, 'epsilon': 0.09852476472330193}. Best is trial 11 with value: 0.4927538326713956.
[I 2025-09-04 16:40:06,883] Trial 17 finished with value: 0.4929187574446946 and parameters: {'C': 2.161514352200443, 'epsilon': 0.17410072279452563}. Best is trial 17 with value: 0.4929187574446946.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:40:06,983] Trial 18 finished with value: 0.47275637377793667 and parameters: {'C': 5.8877721933634515, 'epsilon': 0.17292863214056198}. Best is trial 17 with value: 0.4929187574446946.
[I 2025-09-04 16:40:07,080] Trial 19 finished with value: 0.48046483078573543 and parameters: {'C': 1.4823409010662463, 'epsilon': 0.17269559007185198}. Best is trial 17 with value: 0.4929187574446946.
[I 2025-09-04 16:40:07,171] Trial 20 finished with value: 0.444189265580732 and parameters: {'C': 0.9214368409951817, 'epsilon': 0.183399367847011}. Best is trial 17 with value: 0.4929187574446946.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1

[I 2025-09-04 16:40:07,270] Trial 21 finished with value: 0.49342521130748074 and parameters: {'C': 2.3329369161776583, 'epsilon': 0.1587162662784356}. Best is trial 21 with value: 0.49342521130748074.
[I 2025-09-04 16:40:07,364] Trial 22 finished with value: 0.493447176246252 and parameters: {'C': 2.1276469759258227, 'epsilon': 0.15940003487615143}. Best is trial 22 with value: 0.493447176246252.

Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2

[I 2025-09-04 16:40:07,467] Trial 23 finished with value: 0.4865524579683419 and parameters: {'C': 1.7173208180984751, 'epsilon': 0.15644345894331407}. Best is trial 22 with value: 0.493447176246252.
[I 2025-09-04 16:40:07,564] Trial 24 finished with value: 0.49390614548654266 and parameters: {'C': 2.15684226903379, 'epsilon': 0.12775727625293434}. Best is trial 24 with value: 0.49390614548654266.
[I 2025-09-04 16:40:07,565] A new study created in memory with name: no-name-2a1848b0-b6ed-46a3-8a10-94ee13639b21

Fold 3
Fold 4
Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

✅ SVR con TOA_15x15_depth_in_3_4 - Mejor R2: 0.49
📋 Parámetros: {'C': 2.15684226903379, 'epsilon': 0.12775727625293434}

Buscando mejores hiperparámetros para KNN con TOA_15x15_depth_in_3_4...

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 16:40:07,642] Trial 0 finished with value: 0.5950294999872832 and parameters: {'n_neighbors': 3, 'leaf_size': 24}. Best is trial 0 with value: 0.5950294999872832.
[I 2025-09-04 16:40:07,762] Trial 1 finished with value: 0.6428812798806427 and parameters: {'n_neighbors': 9, 'leaf_size': 23}. Best is trial 1 with value: 0.6428812798806427.

Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:40:07,834] Trial 2 finished with value: 0.6491292804258867 and parameters: {'n_neighbors': 7, 'leaf_size': 31}. Best is trial 2 with value: 0.6491292804258867.
[I 2025-09-04 16:40:07,913] Trial 3 finished with value: 0.6428812798806427 and parameters: {'n_neighbors': 9, 'leaf_size': 21}. Best is trial 2 with value: 0.6491292804258867.
[I 2025-09-04 16:40:07,982] Trial 4 finished with value: 0.6224887342316394 and parameters: {'n_neighbors': 5, 'leaf_size': 16}. Best is trial 2 with value: 0.6491292804258867.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 16:40:08,058] Trial 5 finished with value: 0.6491292804258867 and parameters: {'n_neighbors': 7, 'leaf_size': 24}. Best is trial 2 with value: 0.6491292804258867.
[I 2025-09-04 16:40:08,140] Trial 6 finished with value: 0.6491292804258867 and parameters: {'n_neighbors': 7, 'leaf_size': 20}. Best is trial 2 with value: 0.6491292804258867.
[I 2025-09-04 16:40:08,211] Trial 7 finished with value: 0.6208975376260835 and parameters: {'n_neighbors': 4, 'leaf_size': 37}. Best is trial 2 with value: 0.6491292804258867.

Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 16:40:08,291] Trial 8 finished with value: 0.6208975376260835 and parameters: {'n_neighbors': 4, 'leaf_size': 13}. Best is trial 2 with value: 0.6491292804258867.
[I 2025-09-04 16:40:08,369] Trial 9 finished with value: 0.6390640267564509 and parameters: {'n_neighbors': 6, 'leaf_size': 34}. Best is trial 2 with value: 0.6491292804258867.
[I 2025-09-04 16:40:08,447] Trial 10 finished with value: 0.6464343019332724 and parameters: {'n_neighbors': 10, 'leaf_size': 31}. Best is trial 2 with value: 0.6491292804258867.

Fold 4
Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1

[I 2025-09-04 16:40:08,529] Trial 11 finished with value: 0.6491292804258867 and parameters: {'n_neighbors': 7, 'leaf_size': 29}. Best is trial 2 with value: 0.6491292804258867.
[I 2025-09-04 16:40:08,642] Trial 12 finished with value: 0.637593968734208 and parameters: {'n_neighbors': 8, 'leaf_size': 29}. Best is trial 2 with value: 0.6491292804258867.

Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2

[I 2025-09-04 16:40:08,728] Trial 13 finished with value: 0.6390640267564509 and parameters: {'n_neighbors': 6, 'leaf_size': 40}. Best is trial 2 with value: 0.6491292804258867.
[I 2025-09-04 16:40:08,814] Trial 14 finished with value: 0.637593968734208 and parameters: {'n_neighbors': 8, 'leaf_size': 27}. Best is trial 2 with value: 0.6491292804258867.

Fold 3
Fold 4
Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:40:08,895] Trial 15 finished with value: 0.637593968734208 and parameters: {'n_neighbors': 8, 'leaf_size': 33}. Best is trial 2 with value: 0.6491292804258867.
[I 2025-09-04 16:40:08,988] Trial 16 finished with value: 0.6224887342316394 and parameters: {'n_neighbors': 5, 'leaf_size': 19}. Best is trial 2 with value: 0.6491292804258867.
[I 2025-09-04 16:40:09,064] Trial 17 finished with value: 0.6491292804258867 and parameters: {'n_neighbors': 7, 'leaf_size': 11}. Best is trial 2 with value: 0.6491292804258867.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2

[I 2025-09-04 16:40:09,147] Trial 18 finished with value: 0.6390640267564509 and parameters: {'n_neighbors': 6, 'leaf_size': 25}. Best is trial 2 with value: 0.6491292804258867.
[I 2025-09-04 16:40:09,232] Trial 19 finished with value: 0.6464343019332724 and parameters: {'n_neighbors': 10, 'leaf_size': 35}. Best is trial 2 with value: 0.6491292804258867.

Fold 3
Fold 4
Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:40:09,310] Trial 20 finished with value: 0.6224887342316394 and parameters: {'n_neighbors': 5, 'leaf_size': 17}. Best is trial 2 with value: 0.6491292804258867.
[I 2025-09-04 16:40:09,419] Trial 21 finished with value: 0.6491292804258867 and parameters: {'n_neighbors': 7, 'leaf_size': 22}. Best is trial 2 with value: 0.6491292804258867.
[I 2025-09-04 16:40:09,496] Trial 22 finished with value: 0.6491292804258867 and parameters: {'n_neighbors': 7, 'leaf_size': 27}. Best is trial 2 with value: 0.6491292804258867.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1

[I 2025-09-04 16:40:09,579] Trial 23 finished with value: 0.637593968734208 and parameters: {'n_neighbors': 8, 'leaf_size': 19}. Best is trial 2 with value: 0.6491292804258867.
[I 2025-09-04 16:40:09,661] Trial 24 finished with value: 0.6428812798806427 and parameters: {'n_neighbors': 9, 'leaf_size': 15}. Best is trial 2 with value: 0.6491292804258867.
[I 2025-09-04 16:40:09,662] A new study created in memory with name: no-name-bed42b44-2a92-4a9a-b55f-1112924f779c

Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

✅ KNN con TOA_15x15_depth_in_3_4 - Mejor R2: 0.65
📋 Parámetros: {'n_neighbors': 7, 'leaf_size': 31}

Buscando mejores hiperparámetros para LR con TOA_15x15_depth_in_3_4...

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:40:09,729] Trial 0 finished with value: 0.36052626332472704 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 0 with value: 0.36052626332472704.
[I 2025-09-04 16:40:09,800] Trial 1 finished with value: 0.36052626332472204 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 0 with value: 0.36052626332472704.
[I 2025-09-04 16:40:09,889] Trial 2 finished with value: 0.37972824675105876 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 2 with value: 0.37972824675105876.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 16:40:09,978] Trial 3 finished with value: 0.36052626332472204 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 2 with value: 0.37972824675105876.
[I 2025-09-04 16:40:10,052] Trial 4 finished with value: 0.36052626332472204 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 2 with value: 0.37972824675105876.
[I 2025-09-04 16:40:10,120] Trial 5 finished with value: 0.36052626332472704 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 2 with value: 0.37972824675105876.

Fold 4
Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2

[I 2025-09-04 16:40:10,191] Trial 6 finished with value: 0.36052626332472204 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 2 with value: 0.37972824675105876.
[I 2025-09-04 16:40:10,311] Trial 7 finished with value: 0.37972824675158745 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 7 with value: 0.37972824675158745.

Fold 3
Fold 4
Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2

[I 2025-09-04 16:40:10,422] Trial 8 finished with value: 0.37972824675158745 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 7 with value: 0.37972824675158745.
[I 2025-09-04 16:40:10,515] Trial 9 finished with value: 0.36052626332472704 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 7 with value: 0.37972824675158745.

Fold 3
Fold 4
Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 16:40:10,642] Trial 10 finished with value: 0.37972824675158745 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 7 with value: 0.37972824675158745.
[I 2025-09-04 16:40:10,778] Trial 11 finished with value: 0.37972824675158745 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 7 with value: 0.37972824675158745.

Fold 4
Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1

[I 2025-09-04 16:40:10,915] Trial 12 finished with value: 0.37972824675158745 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 7 with value: 0.37972824675158745.

Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 16:40:11,055] Trial 13 finished with value: 0.37972824675158745 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 7 with value: 0.37972824675158745.

Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 16:40:11,313] Trial 14 finished with value: 0.37972824675158745 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 7 with value: 0.37972824675158745.

Fold 4
Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:40:11,455] Trial 15 finished with value: 0.37972824675158745 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 7 with value: 0.37972824675158745.
[I 2025-09-04 16:40:11,574] Trial 16 finished with value: 0.37972824675158745 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 7 with value: 0.37972824675158745.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:40:11,661] Trial 17 finished with value: 0.37972824675158745 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 7 with value: 0.37972824675158745.
[I 2025-09-04 16:40:11,814] Trial 18 finished with value: 0.37972824675158745 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 7 with value: 0.37972824675158745.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 16:40:11,967] Trial 19 finished with value: 0.37972824675158745 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 7 with value: 0.37972824675158745.

Fold 4
Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2

[I 2025-09-04 16:40:12,216] Trial 20 finished with value: 0.37972824675158745 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 7 with value: 0.37972824675158745.

Fold 3
Fold 4
Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2

[I 2025-09-04 16:40:12,436] Trial 21 finished with value: 0.37972824675158745 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 7 with value: 0.37972824675158745.

Fold 3
Fold 4
Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 16:40:12,550] Trial 22 finished with value: 0.37972824675158745 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 7 with value: 0.37972824675158745.

Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:40:12,756] Trial 23 finished with value: 0.37972824675158745 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 7 with value: 0.37972824675158745.
[I 2025-09-04 16:40:12,882] Trial 24 finished with value: 0.37972824675158745 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 7 with value: 0.37972824675158745.
[I 2025-09-04 16:40:12,884] A new study created in memory with name: no-name-1bcb4eaa-5f33-4fb7-b01f-a943366d6490

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

✅ LR con TOA_15x15_depth_in_3_4 - Mejor R2: 0.38
📋 Parámetros: {'fit_intercept': False, 'positive': False}

Buscando mejores hiperparámetros para RF con TOA_15x15_depth_in_3_4...

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:40:25,267] Trial 0 finished with value: 0.5985958077765114 and parameters: {'n_estimators': 300, 'max_depth': 13, 'min_samples_split': 4, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 0 with value: 0.5985958077765114.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:40:28,769] Trial 1 finished with value: 0.5030645579187567 and parameters: {'n_estimators': 100, 'max_depth': 14, 'min_samples_split': 8, 'min_samples_leaf': 4, 'bootstrap': False}. Best is trial 0 with value: 0.5985958077765114.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:40:48,911] Trial 2 finished with value: 0.4663992364705837 and parameters: {'n_estimators': 500, 'max_depth': 15, 'min_samples_split': 9, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 0 with value: 0.5985958077765114.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:40:51,257] Trial 3 finished with value: 0.6102019004883958 and parameters: {'n_estimators': 100, 'max_depth': 9, 'min_samples_split': 9, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 3 with value: 0.6102019004883958.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:40:55,028] Trial 4 finished with value: 0.5769606164913026 and parameters: {'n_estimators': 100, 'max_depth': 11, 'min_samples_split': 8, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 3 with value: 0.6102019004883958.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:41:01,180] Trial 5 finished with value: 0.5818535591663923 and parameters: {'n_estimators': 300, 'max_depth': 14, 'min_samples_split': 4, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 3 with value: 0.6102019004883958.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:41:11,043] Trial 6 finished with value: 0.5480172922853755 and parameters: {'n_estimators': 300, 'max_depth': 13, 'min_samples_split': 3, 'min_samples_leaf': 5, 'bootstrap': False}. Best is trial 3 with value: 0.6102019004883958.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:41:13,280] Trial 7 finished with value: 0.6079322111080112 and parameters: {'n_estimators': 100, 'max_depth': 8, 'min_samples_split': 5, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 3 with value: 0.6102019004883958.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:41:28,975] Trial 8 finished with value: 0.49768513674790604 and parameters: {'n_estimators': 500, 'max_depth': 8, 'min_samples_split': 6, 'min_samples_leaf': 4, 'bootstrap': False}. Best is trial 3 with value: 0.6102019004883958.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:41:32,415] Trial 9 finished with value: 0.524324589325589 and parameters: {'n_estimators': 100, 'max_depth': 12, 'min_samples_split': 9, 'min_samples_leaf': 4, 'bootstrap': False}. Best is trial 3 with value: 0.6102019004883958.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:41:34,081] Trial 10 finished with value: 0.5809503056888314 and parameters: {'n_estimators': 100, 'max_depth': 5, 'min_samples_split': 10, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 3 with value: 0.6102019004883958.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:41:36,300] Trial 11 finished with value: 0.6102668631960425 and parameters: {'n_estimators': 100, 'max_depth': 8, 'min_samples_split': 6, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 11 with value: 0.6102668631960425.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:41:38,698] Trial 12 finished with value: 0.6052314990019854 and parameters: {'n_estimators': 100, 'max_depth': 9, 'min_samples_split': 7, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 11 with value: 0.6102668631960425.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:41:40,567] Trial 13 finished with value: 0.5931300008018291 and parameters: {'n_estimators': 100, 'max_depth': 6, 'min_samples_split': 6, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 11 with value: 0.6102668631960425.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:41:43,035] Trial 14 finished with value: 0.6166673120663069 and parameters: {'n_estimators': 100, 'max_depth': 10, 'min_samples_split': 2, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 14 with value: 0.6166673120663069.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:41:53,086] Trial 15 finished with value: 0.599537892392207 and parameters: {'n_estimators': 500, 'max_depth': 7, 'min_samples_split': 2, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 14 with value: 0.6166673120663069.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:41:55,525] Trial 16 finished with value: 0.6166673120663069 and parameters: {'n_estimators': 100, 'max_depth': 10, 'min_samples_split': 2, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 14 with value: 0.6166673120663069.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:41:57,804] Trial 17 finished with value: 0.606332379161441 and parameters: {'n_estimators': 100, 'max_depth': 10, 'min_samples_split': 2, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 14 with value: 0.6166673120663069.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:42:05,400] Trial 18 finished with value: 0.612466822994046 and parameters: {'n_estimators': 300, 'max_depth': 11, 'min_samples_split': 3, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 14 with value: 0.6166673120663069.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:42:17,702] Trial 19 finished with value: 0.6121685363439013 and parameters: {'n_estimators': 500, 'max_depth': 10, 'min_samples_split': 3, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 14 with value: 0.6166673120663069.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:42:20,136] Trial 20 finished with value: 0.6047139653567566 and parameters: {'n_estimators': 100, 'max_depth': 11, 'min_samples_split': 2, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 14 with value: 0.6166673120663069.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:42:27,967] Trial 21 finished with value: 0.612466822994046 and parameters: {'n_estimators': 300, 'max_depth': 11, 'min_samples_split': 3, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 14 with value: 0.6166673120663069.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:42:35,730] Trial 22 finished with value: 0.6121671622203144 and parameters: {'n_estimators': 300, 'max_depth': 12, 'min_samples_split': 4, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 14 with value: 0.6166673120663069.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:42:43,513] Trial 23 finished with value: 0.5970707184318955 and parameters: {'n_estimators': 300, 'max_depth': 9, 'min_samples_split': 2, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 14 with value: 0.6166673120663069.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:42:51,022] Trial 24 finished with value: 0.615126485265544 and parameters: {'n_estimators': 300, 'max_depth': 10, 'min_samples_split': 3, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 14 with value: 0.6166673120663069.
[I 2025-09-04 16:42:51,023] A new study created in memory with name: no-name-c81e4a28-cf91-4855-a899-3bc62082e63f

✅ RF con TOA_15x15_depth_in_3_4 - Mejor R2: 0.62
📋 Parámetros: {'n_estimators': 100, 'max_depth': 10, 'min_samples_split': 2, 'min_samples_leaf': 2, 'bootstrap': True}

Buscando mejores hiperparámetros para CAT con TOA_15x15_depth_in_3_4...

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:46:19,953] Trial 0 finished with value: 0.6750606348067516 and parameters: {'iterations': 2000, 'learning_rate': 0.047570884009168715, 'depth': 9, 'l2_leaf_reg': 1.0633181682760227}. Best is trial 0 with value: 0.6750606348067516.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:48:05,017] Trial 1 finished with value: 0.6776777956636133 and parameters: {'iterations': 1000, 'learning_rate': 0.06128786022816124, 'depth': 9, 'l2_leaf_reg': 1.1424059963513251}. Best is trial 1 with value: 0.6776777956636133.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:48:08,595] Trial 2 finished with value: 0.5813950891728767 and parameters: {'iterations': 1000, 'learning_rate': 0.023184584682332816, 'depth': 4, 'l2_leaf_reg': 4.350041373005388}. Best is trial 1 with value: 0.6776777956636133.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:51:27,034] Trial 3 finished with value: 0.6363272523471653 and parameters: {'iterations': 1000, 'learning_rate': 0.012641874252759654, 'depth': 10, 'l2_leaf_reg': 2.9255569959354215}. Best is trial 1 with value: 0.6776777956636133.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:53:04,983] Trial 4 finished with value: 0.6400736673208445 and parameters: {'iterations': 2000, 'learning_rate': 0.0472915536829945, 'depth': 8, 'l2_leaf_reg': 3.7969627329677307}. Best is trial 1 with value: 0.6776777956636133.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:53:22,075] Trial 5 finished with value: 0.6462192012142203 and parameters: {'iterations': 2000, 'learning_rate': 0.037800488432939656, 'depth': 6, 'l2_leaf_reg': 1.170926152519687}. Best is trial 1 with value: 0.6776777956636133.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:53:23,917] Trial 6 finished with value: 0.58666504214605 and parameters: {'iterations': 500, 'learning_rate': 0.037093872729915635, 'depth': 4, 'l2_leaf_reg': 3.4329280819087917}. Best is trial 1 with value: 0.6776777956636133.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:54:02,094] Trial 7 finished with value: 0.6378874972188093 and parameters: {'iterations': 2000, 'learning_rate': 0.010259199990997985, 'depth': 7, 'l2_leaf_reg': 5.164430023742659}. Best is trial 1 with value: 0.6776777956636133.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:54:50,140] Trial 8 finished with value: 0.6390492671218273 and parameters: {'iterations': 1000, 'learning_rate': 0.02872879236668842, 'depth': 8, 'l2_leaf_reg': 5.270339249101746}. Best is trial 1 with value: 0.6776777956636133.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:54:55,437] Trial 9 finished with value: 0.6183208582194677 and parameters: {'iterations': 1000, 'learning_rate': 0.07468391587326055, 'depth': 5, 'l2_leaf_reg': 4.056350445420447}. Best is trial 1 with value: 0.6776777956636133.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 16:56:33,948] Trial 10 finished with value: 0.6420981958093581 and parameters: {'iterations': 500, 'learning_rate': 0.06952988574580575, 'depth': 10, 'l2_leaf_reg': 2.1341393466853558}. Best is trial 1 with value: 0.6776777956636133.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:00:08,024] Trial 11 finished with value: 0.6811056601656964 and parameters: {'iterations': 2000, 'learning_rate': 0.05314326154992145, 'depth': 9, 'l2_leaf_reg': 1.0213152871705147}. Best is trial 11 with value: 0.6811056601656964.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:03:37,027] Trial 12 finished with value: 0.6617794439988038 and parameters: {'iterations': 2000, 'learning_rate': 0.05911079321032104, 'depth': 9, 'l2_leaf_reg': 2.047126521675054}. Best is trial 11 with value: 0.6811056601656964.
[I 2025-09-04 17:03:37,028] A new study created in memory with name: no-name-b167261d-46a9-4225-887e-732112d1de4d
[I 2025-09-04 17:03:37,127] Trial 0 finished with value: 0.34465682431767075 and parameters: {'alpha': 0.16945595289052712, 'l1_ratio': 0.7099139379782368}. Best is trial 0 with value: 0.34465682431767075.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.134e+01, tolerance: 4.075e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.391e+01, tolerance: 4.583e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.756e+01, tolerance: 3.985e-02
  model = cd_fast.enet_coordinate_descent(

✅ CAT con TOA_15x15_depth_in_3_4 - Mejor R2: 0.68
📋 Parámetros: {'iterations': 2000, 'learning_rate': 0.05314326154992145, 'depth': 9, 'l2_leaf_reg': 1.0213152871705147}

Buscando mejores hiperparámetros para ELN con TOA_15x15_depth_in_3_4...

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.018e+01, tolerance: 5.497e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.571e+01, tolerance: 4.044e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 17:03:37,260] Trial 1 finished with value: 0.48810842357720907 and parameters: {'alpha': 0.00048717543717062567, 'l1_ratio': 0.6063165273147392}. Best is trial 1 with value: 0.48810842357720907.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.613e+01, tolerance: 4.075e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.053e+01, tolerance: 4.583e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.746e+01, tolerance: 3.985e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.110e+01, tolerance: 5.497e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.931e+01, tolerance: 4.044e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 17:03:37,420] Trial 2 finished with value: 0.48688234204170655 and parameters: {'alpha': 0.00047561331572978303, 'l1_ratio': 0.4410687212009512}. Best is trial 1 with value: 0.48810842357720907.

Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1

[I 2025-09-04 17:03:37,548] Trial 3 finished with value: 0.45477494662026297 and parameters: {'alpha': 0.17503138721328176, 'l1_ratio': 0.14697790201153516}. Best is trial 1 with value: 0.48810842357720907.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.450e+01, tolerance: 4.075e-02
  model = cd_fast.enet_coordinate_descent(

Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.128e+02, tolerance: 4.583e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.546e+01, tolerance: 3.985e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.195e+02, tolerance: 5.497e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.027e+02, tolerance: 4.044e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 17:03:37,718] Trial 4 finished with value: 0.4776557038348158 and parameters: {'alpha': 0.0006873166379085737, 'l1_ratio': 0.119536202925002}. Best is trial 1 with value: 0.48810842357720907.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.000e+01, tolerance: 4.075e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.675e+01, tolerance: 4.583e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.081e+01, tolerance: 3.985e-02
  model = cd_fast.enet_coordinate_descent(

Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.099e+01, tolerance: 5.497e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.284e+01, tolerance: 4.044e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 17:03:37,886] Trial 5 finished with value: 0.4519088553766327 and parameters: {'alpha': 0.002705589412535743, 'l1_ratio': 0.389255448026362}. Best is trial 1 with value: 0.48810842357720907.
[I 2025-09-04 17:03:37,990] Trial 6 finished with value: 0.2652161632086367 and parameters: {'alpha': 0.5095650651227462, 'l1_ratio': 0.6637978125419373}. Best is trial 1 with value: 0.48810842357720907.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:03:38,107] Trial 7 finished with value: 0.4556794804540547 and parameters: {'alpha': 0.21531198979070523, 'l1_ratio': 0.09688894204456755}. Best is trial 1 with value: 0.48810842357720907.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.846e-01, tolerance: 5.497e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 17:03:38,298] Trial 8 finished with value: 0.46562557947338457 and parameters: {'alpha': 0.03095515134217118, 'l1_ratio': 0.515227663786355}. Best is trial 1 with value: 0.48810842357720907.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.406e+00, tolerance: 4.075e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.309e+00, tolerance: 4.583e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.507e+00, tolerance: 3.985e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.397e+00, tolerance: 5.497e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.827e+00, tolerance: 4.044e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 17:03:38,460] Trial 9 finished with value: 0.4475622666929614 and parameters: {'alpha': 0.003498826852674582, 'l1_ratio': 0.6513433338118351}. Best is trial 1 with value: 0.48810842357720907.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.233e+01, tolerance: 4.075e-02
  model = cd_fast.enet_coordinate_descent(

Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.048e+02, tolerance: 4.583e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.066e+01, tolerance: 3.985e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.195e+02, tolerance: 5.497e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.700e+01, tolerance: 4.044e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 17:03:38,662] Trial 10 finished with value: 0.5047579991984369 and parameters: {'alpha': 0.00010214130110041048, 'l1_ratio': 0.9670441992993656}. Best is trial 10 with value: 0.5047579991984369.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.177e+01, tolerance: 4.075e-02
  model = cd_fast.enet_coordinate_descent(

Fold 3
Fold 4
Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.039e+02, tolerance: 4.583e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.957e+01, tolerance: 3.985e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.189e+02, tolerance: 5.497e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.627e+01, tolerance: 4.044e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 17:03:38,885] Trial 11 finished with value: 0.5042527973861103 and parameters: {'alpha': 0.00011546841630348866, 'l1_ratio': 0.9205533304541499}. Best is trial 10 with value: 0.5047579991984369.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.116e+01, tolerance: 4.075e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.033e+02, tolerance: 4.583e-02
  model = cd_fast.enet_coordinate_descent(

Fold 3
Fold 4
Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.903e+01, tolerance: 3.985e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.181e+02, tolerance: 5.497e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.550e+01, tolerance: 4.044e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 17:03:39,072] Trial 12 finished with value: 0.5047734107420977 and parameters: {'alpha': 0.00011287578590294489, 'l1_ratio': 0.9941527400112994}. Best is trial 12 with value: 0.5047734107420977.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.849e+01, tolerance: 4.075e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.916e+01, tolerance: 4.583e-02
  model = cd_fast.enet_coordinate_descent(

Fold 4
Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.550e+01, tolerance: 3.985e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.147e+02, tolerance: 5.497e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.227e+01, tolerance: 4.044e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 17:03:39,277] Trial 13 finished with value: 0.5043701350637546 and parameters: {'alpha': 0.00014373562045966203, 'l1_ratio': 0.988144998222855}. Best is trial 12 with value: 0.5047734107420977.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.559e-01, tolerance: 5.497e-02
  model = cd_fast.enet_coordinate_descent(

Fold 4
Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:03:39,428] Trial 14 finished with value: 0.46585841716843124 and parameters: {'alpha': 0.02170426619309515, 'l1_ratio': 0.8264677774160026}. Best is trial 12 with value: 0.5047734107420977.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.230e+01, tolerance: 4.075e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.572e+01, tolerance: 4.583e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.949e+00, tolerance: 3.985e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.138e+01, tolerance: 5.497e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.854e+01, tolerance: 4.044e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 17:03:39,589] Trial 15 finished with value: 0.45828077418903534 and parameters: {'alpha': 0.002063511400492465, 'l1_ratio': 0.8305048197696698}. Best is trial 12 with value: 0.5047734107420977.

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.027e+01, tolerance: 4.075e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.073e+01, tolerance: 4.583e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.337e+01, tolerance: 3.985e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.050e+02, tolerance: 5.497e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.361e+01, tolerance: 4.044e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 17:03:39,758] Trial 16 finished with value: 0.503160113973079 and parameters: {'alpha': 0.00022396151727780192, 'l1_ratio': 0.9998227047804571}. Best is trial 12 with value: 0.5047734107420977.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.549e+01, tolerance: 4.075e-02
  model = cd_fast.enet_coordinate_descent(

Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.099e+01, tolerance: 4.583e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.866e+01, tolerance: 3.985e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.847e+01, tolerance: 5.497e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.241e+01, tolerance: 4.044e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 17:03:39,935] Trial 17 finished with value: 0.4689100978288431 and parameters: {'alpha': 0.001083210986292616, 'l1_ratio': 0.2752095203387441}. Best is trial 12 with value: 0.5047734107420977.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.425e-01, tolerance: 4.075e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.907e-01, tolerance: 4.583e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.004e-01, tolerance: 3.985e-02
  model = cd_fast.enet_coordinate_descent(

Fold 3
Fold 4
Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.512e-01, tolerance: 5.497e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 17:03:40,141] Trial 18 finished with value: 0.4494413308438434 and parameters: {'alpha': 0.006098454717416784, 'l1_ratio': 0.8213199109078118}. Best is trial 12 with value: 0.5047734107420977.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.031e+01, tolerance: 4.075e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.080e+01, tolerance: 4.583e-02
  model = cd_fast.enet_coordinate_descent(

Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.190e+01, tolerance: 3.985e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.057e+02, tolerance: 5.497e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.400e+01, tolerance: 4.044e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 17:03:40,356] Trial 19 finished with value: 0.5010807842630405 and parameters: {'alpha': 0.00024446055422175134, 'l1_ratio': 0.887108224168536}. Best is trial 12 with value: 0.5047734107420977.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.599e-01, tolerance: 4.583e-02
  model = cd_fast.enet_coordinate_descent(

Fold 4
Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.439e-02, tolerance: 3.985e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.718e-01, tolerance: 5.497e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 17:03:40,568] Trial 20 finished with value: 0.4602685179138496 and parameters: {'alpha': 0.014021363472361246, 'l1_ratio': 0.7766459604223571}. Best is trial 12 with value: 0.5047734107420977.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.880e+01, tolerance: 4.075e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.949e+01, tolerance: 4.583e-02
  model = cd_fast.enet_coordinate_descent(

Fold 4
Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.586e+01, tolerance: 3.985e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.151e+02, tolerance: 5.497e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.263e+01, tolerance: 4.044e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 17:03:40,800] Trial 21 finished with value: 0.5043504929137355 and parameters: {'alpha': 0.00014129669341702392, 'l1_ratio': 0.982050261409568}. Best is trial 12 with value: 0.5047734107420977.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.258e+01, tolerance: 4.075e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.051e+02, tolerance: 4.583e-02
  model = cd_fast.enet_coordinate_descent(

Fold 4
Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.081e+01, tolerance: 3.985e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.199e+02, tolerance: 5.497e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.729e+01, tolerance: 4.044e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 17:03:41,000] Trial 22 finished with value: 0.5044056758181623 and parameters: {'alpha': 0.00010550661367561745, 'l1_ratio': 0.9173730883524122}. Best is trial 12 with value: 0.5047734107420977.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.307e+01, tolerance: 4.075e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.058e+02, tolerance: 4.583e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.148e+01, tolerance: 3.985e-02
  model = cd_fast.enet_coordinate_descent(

Fold 4
Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.205e+02, tolerance: 5.497e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.795e+01, tolerance: 4.044e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 17:03:41,177] Trial 23 finished with value: 0.5043524645370228 and parameters: {'alpha': 0.00010208867170841066, 'l1_ratio': 0.8940591779223135}. Best is trial 12 with value: 0.5047734107420977.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.768e+01, tolerance: 4.075e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.500e+01, tolerance: 4.583e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.574e+01, tolerance: 3.985e-02
  model = cd_fast.enet_coordinate_descent(

Fold 5

=== Procesando TOA_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.013e+02, tolerance: 5.497e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.159e+01, tolerance: 4.044e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 17:03:41,429] Trial 24 finished with value: 0.4966927186535496 and parameters: {'alpha': 0.0003116536579790111, 'l1_ratio': 0.7345033356723071}. Best is trial 12 with value: 0.5047734107420977.
[I 2025-09-04 17:03:41,436] A new study created in memory with name: no-name-bea9348c-30c1-436c-aaa7-fe250b98624f

Fold 5

✅ ELN con TOA_15x15_depth_in_3_4 - Mejor R2: 0.50
📋 Parámetros: {'alpha': 0.00011287578590294489, 'l1_ratio': 0.9941527400112994}

Buscando mejores hiperparámetros para XGB con C2X-Complex_rhown_5x5_depth_in_3_4...

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:03:58,931] Trial 0 finished with value: 0.6322759901383148 and parameters: {'n_estimators': 2000, 'learning_rate': 0.00702755010432264, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.9463020471472882, 'colsample_bytree': 0.9211205977192625}. Best is trial 0 with value: 0.6322759901383148.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:04:07,712] Trial 1 finished with value: 0.6161723336297791 and parameters: {'n_estimators': 1000, 'learning_rate': 0.010635610922345173, 'max_depth': 6, 'min_child_weight': 1, 'subsample': 0.7784195709228959, 'colsample_bytree': 0.6870720546862376}. Best is trial 0 with value: 0.6322759901383148.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:04:18,964] Trial 2 finished with value: 0.6193266427333335 and parameters: {'n_estimators': 2000, 'learning_rate': 0.014236510531248268, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.9695822591999421, 'colsample_bytree': 0.7633356980028727}. Best is trial 0 with value: 0.6322759901383148.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:04:22,333] Trial 3 finished with value: 0.6201541536219216 and parameters: {'n_estimators': 500, 'learning_rate': 0.02095240029595525, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.9150136908778087, 'colsample_bytree': 0.6725103695706577}. Best is trial 0 with value: 0.6322759901383148.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:04:25,309] Trial 4 finished with value: 0.6202724868364659 and parameters: {'n_estimators': 500, 'learning_rate': 0.014254496296400136, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.9862807150375736, 'colsample_bytree': 0.634493063901818}. Best is trial 0 with value: 0.6322759901383148.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:04:36,117] Trial 5 finished with value: 0.6287994528639322 and parameters: {'n_estimators': 1000, 'learning_rate': 0.0082464598072358, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.8879347817048928, 'colsample_bytree': 0.9626955934979986}. Best is trial 0 with value: 0.6322759901383148.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:04:56,478] Trial 6 finished with value: 0.6272011574950036 and parameters: {'n_estimators': 1000, 'learning_rate': 0.006857935406579989, 'max_depth': 8, 'min_child_weight': 1, 'subsample': 0.940513022422904, 'colsample_bytree': 0.708401251195724}. Best is trial 0 with value: 0.6322759901383148.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:05:02,802] Trial 7 finished with value: 0.6139075182129622 and parameters: {'n_estimators': 1000, 'learning_rate': 0.043817216579937056, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.8749591100590856, 'colsample_bytree': 0.7377815756324276}. Best is trial 0 with value: 0.6322759901383148.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:05:14,603] Trial 8 finished with value: 0.6177162871761934 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01681703203606651, 'max_depth': 8, 'min_child_weight': 4, 'subsample': 0.9013523106608095, 'colsample_bytree': 0.9844308978290738}. Best is trial 0 with value: 0.6322759901383148.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:05:20,872] Trial 9 finished with value: 0.6276483508699005 and parameters: {'n_estimators': 1000, 'learning_rate': 0.018721490258934343, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.9077290914145558, 'colsample_bytree': 0.905989616221277}. Best is trial 0 with value: 0.6322759901383148.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:05:40,736] Trial 10 finished with value: 0.624511249417014 and parameters: {'n_estimators': 2000, 'learning_rate': 0.005664119789262023, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.6630406850311664, 'colsample_bytree': 0.8643415177184547}. Best is trial 0 with value: 0.6322759901383148.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:06:01,273] Trial 11 finished with value: 0.6322993275618343 and parameters: {'n_estimators': 2000, 'learning_rate': 0.008407531682438282, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.8127226675237711, 'colsample_bytree': 0.9952304457528169}. Best is trial 11 with value: 0.6322993275618343.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:06:22,040] Trial 12 finished with value: 0.6185771348146465 and parameters: {'n_estimators': 2000, 'learning_rate': 0.005026110265903447, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.7684054514388685, 'colsample_bytree': 0.8464563081630256}. Best is trial 11 with value: 0.6322993275618343.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:06:40,286] Trial 13 finished with value: 0.6275772057939404 and parameters: {'n_estimators': 2000, 'learning_rate': 0.009238442398455289, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.7131804411007742, 'colsample_bytree': 0.9169266930606821}. Best is trial 11 with value: 0.6322993275618343.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:07:02,791] Trial 14 finished with value: 0.6270007349220863 and parameters: {'n_estimators': 2000, 'learning_rate': 0.011298613352113192, 'max_depth': 8, 'min_child_weight': 3, 'subsample': 0.8366348121460261, 'colsample_bytree': 0.9965117147209521}. Best is trial 11 with value: 0.6322993275618343.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:07:19,687] Trial 15 finished with value: 0.6322147003308878 and parameters: {'n_estimators': 2000, 'learning_rate': 0.03041666722500581, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.8370848018932879, 'colsample_bytree': 0.9211491895800182}. Best is trial 11 with value: 0.6322993275618343.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:07:35,261] Trial 16 finished with value: 0.6132969287465729 and parameters: {'n_estimators': 2000, 'learning_rate': 0.007269426385976384, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.6388650813654989, 'colsample_bytree': 0.8034202884468641}. Best is trial 11 with value: 0.6322993275618343.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:07:51,573] Trial 17 finished with value: 0.627503568101156 and parameters: {'n_estimators': 2000, 'learning_rate': 0.00626244141433702, 'max_depth': 6, 'min_child_weight': 1, 'subsample': 0.7242905993575579, 'colsample_bytree': 0.9523746305381032}. Best is trial 11 with value: 0.6322993275618343.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:07:58,069] Trial 18 finished with value: 0.6281407466423607 and parameters: {'n_estimators': 500, 'learning_rate': 0.01006003907408119, 'max_depth': 8, 'min_child_weight': 2, 'subsample': 0.8398205178925477, 'colsample_bytree': 0.8611994520849947}. Best is trial 11 with value: 0.6322993275618343.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:08:14,280] Trial 19 finished with value: 0.6152258587818623 and parameters: {'n_estimators': 2000, 'learning_rate': 0.027356695410361356, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.7262232682311023, 'colsample_bytree': 0.9431002895638058}. Best is trial 11 with value: 0.6322993275618343.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:08:30,190] Trial 20 finished with value: 0.630448128645366 and parameters: {'n_estimators': 2000, 'learning_rate': 0.01200659912080906, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.9988932580246155, 'colsample_bytree': 0.805459360031997}. Best is trial 11 with value: 0.6322993275618343.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:08:39,901] Trial 21 finished with value: 0.6353616340858059 and parameters: {'n_estimators': 2000, 'learning_rate': 0.03991687227083739, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.8317431401127855, 'colsample_bytree': 0.9024665355449789}. Best is trial 21 with value: 0.6353616340858059.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:08:54,706] Trial 22 finished with value: 0.6372271046564586 and parameters: {'n_estimators': 2000, 'learning_rate': 0.045720937679426726, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.8049551995941774, 'colsample_bytree': 0.9077296398951732}. Best is trial 22 with value: 0.6372271046564586.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:09:09,101] Trial 23 finished with value: 0.6344382173395144 and parameters: {'n_estimators': 2000, 'learning_rate': 0.04843197630876313, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.8014881945016122, 'colsample_bytree': 0.8788621823782619}. Best is trial 22 with value: 0.6372271046564586.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:09:22,367] Trial 24 finished with value: 0.6106147312451193 and parameters: {'n_estimators': 2000, 'learning_rate': 0.04692156458193141, 'max_depth': 6, 'min_child_weight': 1, 'subsample': 0.7653095786400687, 'colsample_bytree': 0.8709241636063829}. Best is trial 22 with value: 0.6372271046564586.
[I 2025-09-04 17:09:22,369] A new study created in memory with name: no-name-859eb070-7ae8-420a-9033-7e7a903066dd

✅ XGB con C2X-Complex_rhown_5x5_depth_in_3_4 - Mejor R2: 0.64
📋 Parámetros: {'n_estimators': 2000, 'learning_rate': 0.045720937679426726, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.8049551995941774, 'colsample_bytree': 0.9077296398951732}

Buscando mejores hiperparámetros para LBM con C2X-Complex_rhown_5x5_depth_in_3_4...

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 17:09:23,035] Trial 0 finished with value: 0.5724641151819099 and parameters: {'learning_rate': 0.017565729066994905, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 15, 'subsample': 0.9202814068007715, 'colsample_bytree': 0.8336864870013209, 'n_estimators': 1000}. Best is trial 0 with value: 0.5724641151819099.

Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 17:09:23,386] Trial 1 finished with value: 0.5997188280791275 and parameters: {'learning_rate': 0.01023463227749196, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 7, 'subsample': 0.8076070561078037, 'colsample_bytree': 0.7754430671247292, 'n_estimators': 500}. Best is trial 1 with value: 0.5997188280791275.

Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:09:24,144] Trial 2 finished with value: 0.6055745216738333 and parameters: {'learning_rate': 0.03802340959240425, 'num_leaves': 80, 'max_depth': 5, 'min_child_samples': 4, 'subsample': 0.9757711617976341, 'colsample_bytree': 0.8083579720549522, 'n_estimators': 1000}. Best is trial 2 with value: 0.6055745216738333.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 17:09:24,852] Trial 3 finished with value: 0.6097540271725113 and parameters: {'learning_rate': 0.018662223489098104, 'num_leaves': 60, 'max_depth': 8, 'min_child_samples': 4, 'subsample': 0.9375510003025812, 'colsample_bytree': 0.9105926681369425, 'n_estimators': 500}. Best is trial 3 with value: 0.6097540271725113.

Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:09:25,707] Trial 4 finished with value: 0.5874898948670865 and parameters: {'learning_rate': 0.0362824307122944, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 5, 'subsample': 0.8287433113553666, 'colsample_bytree': 0.9309409007323055, 'n_estimators': 1000}. Best is trial 3 with value: 0.6097540271725113.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 17:09:26,224] Trial 5 finished with value: 0.6000720710779075 and parameters: {'learning_rate': 0.008365951857518034, 'num_leaves': 80, 'max_depth': 8, 'min_child_samples': 8, 'subsample': 0.983181307476819, 'colsample_bytree': 0.741342891287408, 'n_estimators': 500}. Best is trial 3 with value: 0.6097540271725113.

Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:09:26,587] Trial 6 finished with value: 0.5723523237267492 and parameters: {'learning_rate': 0.020012170043145847, 'num_leaves': 40, 'max_depth': 6, 'min_child_samples': 11, 'subsample': 0.9510501741658174, 'colsample_bytree': 0.9977386666854885, 'n_estimators': 500}. Best is trial 3 with value: 0.6097540271725113.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 17:09:26,977] Trial 7 finished with value: 0.600856683695794 and parameters: {'learning_rate': 0.010100105118499885, 'num_leaves': 60, 'max_depth': 7, 'min_child_samples': 11, 'subsample': 0.747201034876229, 'colsample_bytree': 0.7496831282354554, 'n_estimators': 500}. Best is trial 3 with value: 0.6097540271725113.

Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:09:27,699] Trial 8 finished with value: 0.5686861006801225 and parameters: {'learning_rate': 0.017707746761807155, 'num_leaves': 80, 'max_depth': 8, 'min_child_samples': 15, 'subsample': 0.7122952422070301, 'colsample_bytree': 0.654520553997889, 'n_estimators': 1000}. Best is trial 3 with value: 0.6097540271725113.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 17:09:28,076] Trial 9 finished with value: 0.5560325329022826 and parameters: {'learning_rate': 0.04652205305773497, 'num_leaves': 40, 'max_depth': 8, 'min_child_samples': 11, 'subsample': 0.7138682888602382, 'colsample_bytree': 0.7476263002399822, 'n_estimators': 500}. Best is trial 3 with value: 0.6097540271725113.

Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:09:29,527] Trial 10 finished with value: 0.5906096589161223 and parameters: {'learning_rate': 0.005035684117100554, 'num_leaves': 60, 'max_depth': 6, 'min_child_samples': 7, 'subsample': 0.8736698873402567, 'colsample_bytree': 0.892459710571033, 'n_estimators': 2000}. Best is trial 3 with value: 0.6097540271725113.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:09:31,063] Trial 11 finished with value: 0.6125281809580619 and parameters: {'learning_rate': 0.02826293559467091, 'num_leaves': 80, 'max_depth': 5, 'min_child_samples': 4, 'subsample': 0.9917473394145883, 'colsample_bytree': 0.8649363203489264, 'n_estimators': 2000}. Best is trial 11 with value: 0.6125281809580619.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:09:32,934] Trial 12 finished with value: 0.6123198238108156 and parameters: {'learning_rate': 0.026455765258488438, 'num_leaves': 60, 'max_depth': 6, 'min_child_samples': 4, 'subsample': 0.9166377432533526, 'colsample_bytree': 0.8858242324272001, 'n_estimators': 2000}. Best is trial 11 with value: 0.6125281809580619.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:09:34,235] Trial 13 finished with value: 0.5685499989660866 and parameters: {'learning_rate': 0.027733350610193205, 'num_leaves': 80, 'max_depth': 5, 'min_child_samples': 6, 'subsample': 0.6387790660328413, 'colsample_bytree': 0.8656765529805365, 'n_estimators': 2000}. Best is trial 11 with value: 0.6125281809580619.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:09:35,523] Trial 14 finished with value: 0.5579390130968039 and parameters: {'learning_rate': 0.027251631911019866, 'num_leaves': 60, 'max_depth': 6, 'min_child_samples': 9, 'subsample': 0.880990218701337, 'colsample_bytree': 0.9736437999367014, 'n_estimators': 2000}. Best is trial 11 with value: 0.6125281809580619.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 17:09:36,492] Trial 15 finished with value: 0.5801915213688824 and parameters: {'learning_rate': 0.025834423733376598, 'num_leaves': 80, 'max_depth': 5, 'min_child_samples': 13, 'subsample': 0.8825154249433593, 'colsample_bytree': 0.6002544723090248, 'n_estimators': 2000}. Best is trial 11 with value: 0.6125281809580619.

Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:09:37,935] Trial 16 finished with value: 0.5843170346750652 and parameters: {'learning_rate': 0.013508964498350174, 'num_leaves': 60, 'max_depth': 6, 'min_child_samples': 6, 'subsample': 0.9988069475581107, 'colsample_bytree': 0.8616061496861189, 'n_estimators': 2000}. Best is trial 11 with value: 0.6125281809580619.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:09:39,499] Trial 17 finished with value: 0.604046869760545 and parameters: {'learning_rate': 0.048966348956721244, 'num_leaves': 40, 'max_depth': 5, 'min_child_samples': 4, 'subsample': 0.9096351698103609, 'colsample_bytree': 0.9448856262345473, 'n_estimators': 2000}. Best is trial 11 with value: 0.6125281809580619.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:09:40,688] Trial 18 finished with value: 0.5596384368833622 and parameters: {'learning_rate': 0.02319720077073408, 'num_leaves': 80, 'max_depth': 6, 'min_child_samples': 9, 'subsample': 0.8317391285220304, 'colsample_bytree': 0.7012413338946164, 'n_estimators': 2000}. Best is trial 11 with value: 0.6125281809580619.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:09:41,988] Trial 19 finished with value: 0.5793701317327594 and parameters: {'learning_rate': 0.03393226528977742, 'num_leaves': 60, 'max_depth': 5, 'min_child_samples': 6, 'subsample': 0.7752250561607129, 'colsample_bytree': 0.8302115157193358, 'n_estimators': 2000}. Best is trial 11 with value: 0.6125281809580619.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:09:43,551] Trial 20 finished with value: 0.5941678940404106 and parameters: {'learning_rate': 0.012458514576659334, 'num_leaves': 60, 'max_depth': 6, 'min_child_samples': 5, 'subsample': 0.6126911312937235, 'colsample_bytree': 0.8793767063933468, 'n_estimators': 2000}. Best is trial 11 with value: 0.6125281809580619.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 17:09:44,147] Trial 21 finished with value: 0.6213276835375059 and parameters: {'learning_rate': 0.02077774406329852, 'num_leaves': 60, 'max_depth': 7, 'min_child_samples': 4, 'subsample': 0.9541042264223877, 'colsample_bytree': 0.9255057053393106, 'n_estimators': 500}. Best is trial 21 with value: 0.6213276835375059.

Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:09:45,985] Trial 22 finished with value: 0.5932738767986613 and parameters: {'learning_rate': 0.031569527795459705, 'num_leaves': 60, 'max_depth': 7, 'min_child_samples': 5, 'subsample': 0.9565095946840814, 'colsample_bytree': 0.9400510868898639, 'n_estimators': 2000}. Best is trial 21 with value: 0.6213276835375059.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 17:09:46,581] Trial 23 finished with value: 0.6230662429912213 and parameters: {'learning_rate': 0.021490317734639115, 'num_leaves': 60, 'max_depth': 7, 'min_child_samples': 4, 'subsample': 0.9171600598982209, 'colsample_bytree': 0.9060991657287198, 'n_estimators': 500}. Best is trial 23 with value: 0.6230662429912213.

Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 17:09:47,060] Trial 24 finished with value: 0.5799197020953775 and parameters: {'learning_rate': 0.02210584784457591, 'num_leaves': 60, 'max_depth': 7, 'min_child_samples': 7, 'subsample': 0.9899922809539716, 'colsample_bytree': 0.9677498098265489, 'n_estimators': 500}. Best is trial 23 with value: 0.6230662429912213.
[I 2025-09-04 17:09:47,061] A new study created in memory with name: no-name-eb2c3821-afa9-4ede-9695-34b2d02ef8b1

Fold 5

✅ LBM con C2X-Complex_rhown_5x5_depth_in_3_4 - Mejor R2: 0.62
📋 Parámetros: {'learning_rate': 0.021490317734639115, 'num_leaves': 60, 'max_depth': 7, 'min_child_samples': 4, 'subsample': 0.9171600598982209, 'colsample_bytree': 0.9060991657287198, 'n_estimators': 500}

Buscando mejores hiperparámetros para MLP con C2X-Complex_rhown_5x5_depth_in_3_4...

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:09:48,300] Trial 0 finished with value: 0.5894968189548927 and parameters: {'hidden_layer_sizes': '256', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0011961721106444538, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0006020228973067121}. Best is trial 0 with value: 0.5894968189548927.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:09:50,309] Trial 1 finished with value: 0.578250455657886 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'adam', 'alpha': 4.5511735052661396e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0006777679128372101}. Best is trial 0 with value: 0.5894968189548927.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:09:52,560] Trial 2 finished with value: 0.6130476497788557 and parameters: {'hidden_layer_sizes': '256_128', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.0009167969699107521, 'learning_rate': 'constant', 'learning_rate_init': 0.003004594527300114}. Best is trial 2 with value: 0.6130476497788557.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 17:09:53,777] Trial 3 finished with value: 0.5781116175045122 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0003591267691870524, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0035427798719828685}. Best is trial 2 with value: 0.6130476497788557.

Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:09:55,007] Trial 4 finished with value: 0.5880428780638395 and parameters: {'hidden_layer_sizes': '256', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.020466356005608227, 'learning_rate': 'constant', 'learning_rate_init': 0.0010442614304777586}. Best is trial 2 with value: 0.6130476497788557.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:09:56,237] Trial 5 finished with value: 0.6035746572233905 and parameters: {'hidden_layer_sizes': '256', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.000335059965612655, 'learning_rate': 'constant', 'learning_rate_init': 0.00026591730837681736}. Best is trial 2 with value: 0.6130476497788557.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 17:09:57,146] Trial 6 finished with value: 0.595347167353345 and parameters: {'hidden_layer_sizes': '256', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.037593370702581966, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0010230834542709214}. Best is trial 2 with value: 0.6130476497788557.

Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:09:58,201] Trial 7 finished with value: 0.6127081991984935 and parameters: {'hidden_layer_sizes': '256', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0003449508022148541, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0006795229561453779}. Best is trial 2 with value: 0.6130476497788557.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

[I 2025-09-04 17:09:59,992] Trial 8 finished with value: 0.5598041226694426 and parameters: {'hidden_layer_sizes': '128', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0001479417010760205, 'learning_rate': 'constant', 'learning_rate_init': 0.00035172164237764336}. Best is trial 2 with value: 0.6130476497788557.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 17:10:01,975] Trial 9 finished with value: 0.524900738143212 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.010490889137461388, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00015270296048208753}. Best is trial 2 with value: 0.6130476497788557.

Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:10:03,909] Trial 10 finished with value: 0.6168499713269358 and parameters: {'hidden_layer_sizes': '256_128', 'activation': 'relu', 'solver': 'sgd', 'alpha': 1.1208579328096656e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.007243500276072202}. Best is trial 10 with value: 0.6168499713269358.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:10:05,840] Trial 11 finished with value: 0.5990663633377625 and parameters: {'hidden_layer_sizes': '256_128', 'activation': 'relu', 'solver': 'sgd', 'alpha': 1.037076874991791e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.009413916569811933}. Best is trial 10 with value: 0.6168499713269358.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:10:08,030] Trial 12 finished with value: 0.6139384551942352 and parameters: {'hidden_layer_sizes': '256_128', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.0029886329362168837, 'learning_rate': 'constant', 'learning_rate_init': 0.003570184051982494}. Best is trial 10 with value: 0.6168499713269358.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:10:09,733] Trial 13 finished with value: 0.5967022719732002 and parameters: {'hidden_layer_sizes': '256_128', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.00484605709492979, 'learning_rate': 'constant', 'learning_rate_init': 0.009039241298044943}. Best is trial 10 with value: 0.6168499713269358.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:10:11,940] Trial 14 finished with value: 0.6121985748806522 and parameters: {'hidden_layer_sizes': '256_128', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.08397553623192996, 'learning_rate': 'constant', 'learning_rate_init': 0.0035733829618275767}. Best is trial 10 with value: 0.6168499713269358.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:10:14,282] Trial 15 finished with value: 0.6160448909377374 and parameters: {'hidden_layer_sizes': '256_128', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.0021057665697479543, 'learning_rate': 'constant', 'learning_rate_init': 0.00231062296497302}. Best is trial 10 with value: 0.6168499713269358.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:10:15,420] Trial 16 finished with value: 0.5855328426208358 and parameters: {'hidden_layer_sizes': '128', 'activation': 'relu', 'solver': 'sgd', 'alpha': 1.5000536839540553e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.0019037696992207811}. Best is trial 10 with value: 0.6168499713269358.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:10:17,675] Trial 17 finished with value: 0.6067612799733701 and parameters: {'hidden_layer_sizes': '256_128', 'activation': 'relu', 'solver': 'sgd', 'alpha': 5.065186028822047e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.006020862860920286}. Best is trial 10 with value: 0.6168499713269358.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:10:19,980] Trial 18 finished with value: 0.5812903788003614 and parameters: {'hidden_layer_sizes': '256_128', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.0019842027018354817, 'learning_rate': 'constant', 'learning_rate_init': 0.0019077850615955771}. Best is trial 10 with value: 0.6168499713269358.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:10:22,320] Trial 19 finished with value: 0.6059538019885327 and parameters: {'hidden_layer_sizes': '256_128', 'activation': 'relu', 'solver': 'sgd', 'alpha': 9.364053398374304e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.005800351539605221}. Best is trial 10 with value: 0.6168499713269358.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:10:23,359] Trial 20 finished with value: 0.5804741069830446 and parameters: {'hidden_layer_sizes': '128', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.007432870856903567, 'learning_rate': 'constant', 'learning_rate_init': 0.0019983116825458636}. Best is trial 10 with value: 0.6168499713269358.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:10:25,869] Trial 21 finished with value: 0.6179174245166131 and parameters: {'hidden_layer_sizes': '256_128', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.0028311644287798946, 'learning_rate': 'constant', 'learning_rate_init': 0.005228148188640056}. Best is trial 21 with value: 0.6179174245166131.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:10:28,139] Trial 22 finished with value: 0.6065922002597046 and parameters: {'hidden_layer_sizes': '256_128', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.0008103780425638206, 'learning_rate': 'constant', 'learning_rate_init': 0.005930875447132526}. Best is trial 21 with value: 0.6179174245166131.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:10:30,242] Trial 23 finished with value: 0.6145841379699064 and parameters: {'hidden_layer_sizes': '256_128', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.0034504650299052118, 'learning_rate': 'constant', 'learning_rate_init': 0.002459636655796736}. Best is trial 21 with value: 0.6179174245166131.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:10:32,699] Trial 24 finished with value: 0.616623764437005 and parameters: {'hidden_layer_sizes': '256_128', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.015184469330655618, 'learning_rate': 'constant', 'learning_rate_init': 0.005567568629970229}. Best is trial 21 with value: 0.6179174245166131.
[I 2025-09-04 17:10:32,702] A new study created in memory with name: no-name-069fb3ab-9c84-4e69-8279-8583d76f661f
[I 2025-09-04 17:10:32,832] Trial 0 finished with value: 0.4987009624580019 and parameters: {'C': 6.908798010994991, 'epsilon': 0.04638857451856215}. Best is trial 0 with value: 0.4987009624580019.

✅ MLP con C2X-Complex_rhown_5x5_depth_in_3_4 - Mejor R2: 0.62
📋 Parámetros: {'hidden_layer_sizes': '256_128', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.0028311644287798946, 'learning_rate': 'constant', 'learning_rate_init': 0.005228148188640056}

Buscando mejores hiperparámetros para SVR con C2X-Complex_rhown_5x5_depth_in_3_4...

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 17:10:32,926] Trial 1 finished with value: 0.47350748343975413 and parameters: {'C': 1.9520293301480083, 'epsilon': 0.03690448280843586}. Best is trial 0 with value: 0.4987009624580019.
[I 2025-09-04 17:10:33,032] Trial 2 finished with value: 0.3328980145054158 and parameters: {'C': 0.2518750427420378, 'epsilon': 0.15273941340871222}. Best is trial 0 with value: 0.4987009624580019.

Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 17:10:33,138] Trial 3 finished with value: 0.5018819264473535 and parameters: {'C': 9.070346177378273, 'epsilon': 0.14439044017112715}. Best is trial 3 with value: 0.5018819264473535.
[I 2025-09-04 17:10:33,241] Trial 4 finished with value: 0.41177024697943576 and parameters: {'C': 0.7231535064707577, 'epsilon': 0.027607798633339745}. Best is trial 3 with value: 0.5018819264473535.

Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:10:33,327] Trial 5 finished with value: 0.4418407985592082 and parameters: {'C': 0.9421029337093559, 'epsilon': 0.0981613120855876}. Best is trial 3 with value: 0.5018819264473535.
[I 2025-09-04 17:10:33,434] Trial 6 finished with value: 0.49789276270597715 and parameters: {'C': 7.485725716617928, 'epsilon': 0.058772247057487584}. Best is trial 3 with value: 0.5018819264473535.
[I 2025-09-04 17:10:33,529] Trial 7 finished with value: 0.4813704863660693 and parameters: {'C': 2.3059846255451206, 'epsilon': 0.050340335126586346}. Best is trial 3 with value: 0.5018819264473535.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:10:33,618] Trial 8 finished with value: 0.34157943149117787 and parameters: {'C': 0.24938360802853918, 'epsilon': 0.19552647277157967}. Best is trial 3 with value: 0.5018819264473535.
[I 2025-09-04 17:10:33,716] Trial 9 finished with value: 0.5052313122448886 and parameters: {'C': 5.582456903424291, 'epsilon': 0.1356732603869826}. Best is trial 9 with value: 0.5052313122448886.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1

[I 2025-09-04 17:10:33,820] Trial 10 finished with value: 0.49401020576303767 and parameters: {'C': 3.05139975315711, 'epsilon': 0.11065215018322144}. Best is trial 9 with value: 0.5052313122448886.
[I 2025-09-04 17:10:33,925] Trial 11 finished with value: 0.5069395412689085 and parameters: {'C': 7.09533806402807, 'epsilon': 0.14700646587042307}. Best is trial 11 with value: 0.5069395412689085.

Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1

[I 2025-09-04 17:10:34,025] Trial 12 finished with value: 0.5054035728227436 and parameters: {'C': 3.9490077809882433, 'epsilon': 0.16140386684113017}. Best is trial 11 with value: 0.5069395412689085.
[I 2025-09-04 17:10:34,122] Trial 13 finished with value: 0.5094536270682286 and parameters: {'C': 3.645085787366226, 'epsilon': 0.18516646571349163}. Best is trial 13 with value: 0.5094536270682286.

Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2

[I 2025-09-04 17:10:34,226] Trial 14 finished with value: 0.48206541285932547 and parameters: {'C': 1.5330608764687172, 'epsilon': 0.19124424331359507}. Best is trial 13 with value: 0.5094536270682286.
[I 2025-09-04 17:10:34,331] Trial 15 finished with value: 0.3934916619778681 and parameters: {'C': 0.47764355842197165, 'epsilon': 0.173637408474403}. Best is trial 13 with value: 0.5094536270682286.

Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2

[I 2025-09-04 17:10:34,439] Trial 16 finished with value: 0.49797841306593627 and parameters: {'C': 4.201601725519588, 'epsilon': 0.12302152267598881}. Best is trial 13 with value: 0.5094536270682286.
[I 2025-09-04 17:10:34,536] Trial 17 finished with value: 0.47347578407953606 and parameters: {'C': 1.3952679854232422, 'epsilon': 0.1747805116062086}. Best is trial 13 with value: 0.5094536270682286.

Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 17:10:34,641] Trial 18 finished with value: 0.48913353183091945 and parameters: {'C': 2.9935150220555324, 'epsilon': 0.08630262048653096}. Best is trial 13 with value: 0.5094536270682286.
[I 2025-09-04 17:10:34,751] Trial 19 finished with value: 0.4956054075526948 and parameters: {'C': 5.003239664969513, 'epsilon': 0.07567665337615313}. Best is trial 13 with value: 0.5094536270682286.

Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 17:10:34,846] Trial 20 finished with value: 0.2428915561788193 and parameters: {'C': 0.10710809665049546, 'epsilon': 0.17669221789313477}. Best is trial 13 with value: 0.5094536270682286.
[I 2025-09-04 17:10:34,970] Trial 21 finished with value: 0.5061102185160902 and parameters: {'C': 4.292127074567391, 'epsilon': 0.15775079245362772}. Best is trial 13 with value: 0.5094536270682286.

Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2

[I 2025-09-04 17:10:35,073] Trial 22 finished with value: 0.5025045825827552 and parameters: {'C': 8.128364494731319, 'epsilon': 0.13123757675358352}. Best is trial 13 with value: 0.5094536270682286.
[I 2025-09-04 17:10:35,173] Trial 23 finished with value: 0.5010860342675398 and parameters: {'C': 2.732338868504166, 'epsilon': 0.15970446550722017}. Best is trial 13 with value: 0.5094536270682286.

Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2

[I 2025-09-04 17:10:35,276] Trial 24 finished with value: 0.4973252739333873 and parameters: {'C': 4.127230529103395, 'epsilon': 0.11805185681939837}. Best is trial 13 with value: 0.5094536270682286.
[I 2025-09-04 17:10:35,277] A new study created in memory with name: no-name-919eb0ef-5eb7-42a1-80b9-936aa7ecd43c
[I 2025-09-04 17:10:35,355] Trial 0 finished with value: 0.5536333543214929 and parameters: {'n_neighbors': 8, 'leaf_size': 38}. Best is trial 0 with value: 0.5536333543214929.

Fold 3
Fold 4
Fold 5

✅ SVR con C2X-Complex_rhown_5x5_depth_in_3_4 - Mejor R2: 0.51
📋 Parámetros: {'C': 3.645085787366226, 'epsilon': 0.18516646571349163}

Buscando mejores hiperparámetros para KNN con C2X-Complex_rhown_5x5_depth_in_3_4...

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:10:35,428] Trial 1 finished with value: 0.551360122230719 and parameters: {'n_neighbors': 5, 'leaf_size': 13}. Best is trial 0 with value: 0.5536333543214929.
[I 2025-09-04 17:10:35,507] Trial 2 finished with value: 0.5713596087334412 and parameters: {'n_neighbors': 10, 'leaf_size': 34}. Best is trial 2 with value: 0.5713596087334412.
[I 2025-09-04 17:10:35,579] Trial 3 finished with value: 0.5505855959874446 and parameters: {'n_neighbors': 9, 'leaf_size': 19}. Best is trial 2 with value: 0.5713596087334412.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 17:10:35,653] Trial 4 finished with value: 0.5029388573430669 and parameters: {'n_neighbors': 3, 'leaf_size': 35}. Best is trial 2 with value: 0.5713596087334412.
[I 2025-09-04 17:10:35,735] Trial 5 finished with value: 0.5029388573430669 and parameters: {'n_neighbors': 3, 'leaf_size': 21}. Best is trial 2 with value: 0.5713596087334412.
[I 2025-09-04 17:10:35,809] Trial 6 finished with value: 0.5370039994825733 and parameters: {'n_neighbors': 4, 'leaf_size': 35}. Best is trial 2 with value: 0.5713596087334412.

Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 17:10:35,882] Trial 7 finished with value: 0.5029388573430669 and parameters: {'n_neighbors': 3, 'leaf_size': 34}. Best is trial 2 with value: 0.5713596087334412.
[I 2025-09-04 17:10:35,997] Trial 8 finished with value: 0.5536333543214929 and parameters: {'n_neighbors': 8, 'leaf_size': 21}. Best is trial 2 with value: 0.5713596087334412.

Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 17:10:36,069] Trial 9 finished with value: 0.5713596087334412 and parameters: {'n_neighbors': 10, 'leaf_size': 31}. Best is trial 2 with value: 0.5713596087334412.
[I 2025-09-04 17:10:36,158] Trial 10 finished with value: 0.5330846121057906 and parameters: {'n_neighbors': 6, 'leaf_size': 28}. Best is trial 2 with value: 0.5713596087334412.
[I 2025-09-04 17:10:36,235] Trial 11 finished with value: 0.5713596087334412 and parameters: {'n_neighbors': 10, 'leaf_size': 27}. Best is trial 2 with value: 0.5713596087334412.

Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1

[I 2025-09-04 17:10:36,319] Trial 12 finished with value: 0.5713596087334412 and parameters: {'n_neighbors': 10, 'leaf_size': 31}. Best is trial 2 with value: 0.5713596087334412.
[I 2025-09-04 17:10:36,409] Trial 13 finished with value: 0.5536333543214929 and parameters: {'n_neighbors': 8, 'leaf_size': 40}. Best is trial 2 with value: 0.5713596087334412.

Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 17:10:36,488] Trial 14 finished with value: 0.5713596087334412 and parameters: {'n_neighbors': 10, 'leaf_size': 30}. Best is trial 2 with value: 0.5713596087334412.
[I 2025-09-04 17:10:36,605] Trial 15 finished with value: 0.550376813162465 and parameters: {'n_neighbors': 7, 'leaf_size': 24}. Best is trial 2 with value: 0.5713596087334412.

Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:10:36,685] Trial 16 finished with value: 0.5505855959874446 and parameters: {'n_neighbors': 9, 'leaf_size': 32}. Best is trial 2 with value: 0.5713596087334412.
[I 2025-09-04 17:10:36,778] Trial 17 finished with value: 0.5505855959874446 and parameters: {'n_neighbors': 9, 'leaf_size': 37}. Best is trial 2 with value: 0.5713596087334412.
[I 2025-09-04 17:10:36,858] Trial 18 finished with value: 0.550376813162465 and parameters: {'n_neighbors': 7, 'leaf_size': 11}. Best is trial 2 with value: 0.5713596087334412.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2

[I 2025-09-04 17:10:36,945] Trial 19 finished with value: 0.5330846121057906 and parameters: {'n_neighbors': 6, 'leaf_size': 26}. Best is trial 2 with value: 0.5713596087334412.
[I 2025-09-04 17:10:37,030] Trial 20 finished with value: 0.5505855959874446 and parameters: {'n_neighbors': 9, 'leaf_size': 40}. Best is trial 2 with value: 0.5713596087334412.

Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:10:37,109] Trial 21 finished with value: 0.5713596087334412 and parameters: {'n_neighbors': 10, 'leaf_size': 28}. Best is trial 2 with value: 0.5713596087334412.
[I 2025-09-04 17:10:37,193] Trial 22 finished with value: 0.5713596087334412 and parameters: {'n_neighbors': 10, 'leaf_size': 24}. Best is trial 2 with value: 0.5713596087334412.
[I 2025-09-04 17:10:37,271] Trial 23 finished with value: 0.5713596087334412 and parameters: {'n_neighbors': 10, 'leaf_size': 32}. Best is trial 2 with value: 0.5713596087334412.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2

[I 2025-09-04 17:10:37,360] Trial 24 finished with value: 0.5505855959874446 and parameters: {'n_neighbors': 9, 'leaf_size': 28}. Best is trial 2 with value: 0.5713596087334412.
[I 2025-09-04 17:10:37,362] A new study created in memory with name: no-name-7f7aeaea-3917-4ea2-8c46-ca4d41498aba
[I 2025-09-04 17:10:37,462] Trial 0 finished with value: 0.3485450165711833 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 0 with value: 0.3485450165711833.

Fold 3
Fold 4
Fold 5

✅ KNN con C2X-Complex_rhown_5x5_depth_in_3_4 - Mejor R2: 0.57
📋 Parámetros: {'n_neighbors': 10, 'leaf_size': 34}

Buscando mejores hiperparámetros para LR con C2X-Complex_rhown_5x5_depth_in_3_4...

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 17:10:37,548] Trial 1 finished with value: 0.5372246561170152 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.5372246561170152.
[I 2025-09-04 17:10:37,638] Trial 2 finished with value: 0.5372246561170152 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.5372246561170152.
[I 2025-09-04 17:10:37,709] Trial 3 finished with value: 0.5370790221737584 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 1 with value: 0.5372246561170152.

Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1

[I 2025-09-04 17:10:37,805] Trial 4 finished with value: 0.3485450165711833 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 1 with value: 0.5372246561170152.
[I 2025-09-04 17:10:37,894] Trial 5 finished with value: 0.5372246561170152 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.5372246561170152.

Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 17:10:37,996] Trial 6 finished with value: 0.3485450165711833 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 1 with value: 0.5372246561170152.
[I 2025-09-04 17:10:38,087] Trial 7 finished with value: 0.5370790221737584 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 1 with value: 0.5372246561170152.

Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 17:10:38,178] Trial 8 finished with value: 0.3485450165711833 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 1 with value: 0.5372246561170152.
[I 2025-09-04 17:10:38,269] Trial 9 finished with value: 0.5372246561170152 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.5372246561170152.
[I 2025-09-04 17:10:38,362] Trial 10 finished with value: 0.5370790221737584 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 1 with value: 0.5372246561170152.

Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:10:38,437] Trial 11 finished with value: 0.5372246561170152 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.5372246561170152.
[I 2025-09-04 17:10:38,516] Trial 12 finished with value: 0.5372246561170152 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.5372246561170152.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 17:10:38,587] Trial 13 finished with value: 0.5372246561170152 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.5372246561170152.
[I 2025-09-04 17:10:38,667] Trial 14 finished with value: 0.5370790221737584 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 1 with value: 0.5372246561170152.
[I 2025-09-04 17:10:38,737] Trial 15 finished with value: 0.5372246561170152 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.5372246561170152.

Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 17:10:38,807] Trial 16 finished with value: 0.5372246561170152 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.5372246561170152.
[I 2025-09-04 17:10:38,897] Trial 17 finished with value: 0.5372246561170152 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.5372246561170152.

Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:10:38,986] Trial 18 finished with value: 0.34854501657758996 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 1 with value: 0.5372246561170152.
[I 2025-09-04 17:10:39,078] Trial 19 finished with value: 0.5372246561170152 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.5372246561170152.
[I 2025-09-04 17:10:39,145] Trial 20 finished with value: 0.5372246561170152 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.5372246561170152.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 17:10:39,216] Trial 21 finished with value: 0.5372246561170152 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.5372246561170152.
[I 2025-09-04 17:10:39,297] Trial 22 finished with value: 0.5372246561170152 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.5372246561170152.
[I 2025-09-04 17:10:39,367] Trial 23 finished with value: 0.5372246561170152 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.5372246561170152.

Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 17:10:39,439] Trial 24 finished with value: 0.5372246561170152 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.5372246561170152.
[I 2025-09-04 17:10:39,441] A new study created in memory with name: no-name-e5118d84-27d6-43b3-bcdd-457307a4f97b

Fold 4
Fold 5

✅ LR con C2X-Complex_rhown_5x5_depth_in_3_4 - Mejor R2: 0.54
📋 Parámetros: {'fit_intercept': False, 'positive': True}

Buscando mejores hiperparámetros para RF con C2X-Complex_rhown_5x5_depth_in_3_4...

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:10:47,886] Trial 0 finished with value: 0.5596858457033476 and parameters: {'n_estimators': 300, 'max_depth': 13, 'min_samples_split': 6, 'min_samples_leaf': 5, 'bootstrap': False}. Best is trial 0 with value: 0.5596858457033476.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:10:57,887] Trial 1 finished with value: 0.5431768252085203 and parameters: {'n_estimators': 300, 'max_depth': 13, 'min_samples_split': 10, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 0 with value: 0.5596858457033476.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:10:59,838] Trial 2 finished with value: 0.634676218599943 and parameters: {'n_estimators': 100, 'max_depth': 14, 'min_samples_split': 3, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 2 with value: 0.634676218599943.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:11:03,216] Trial 3 finished with value: 0.5347092002893927 and parameters: {'n_estimators': 100, 'max_depth': 15, 'min_samples_split': 9, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 2 with value: 0.634676218599943.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:11:05,021] Trial 4 finished with value: 0.6344819304664318 and parameters: {'n_estimators': 100, 'max_depth': 7, 'min_samples_split': 3, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 2 with value: 0.634676218599943.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:11:15,203] Trial 5 finished with value: 0.5468556378701481 and parameters: {'n_estimators': 300, 'max_depth': 13, 'min_samples_split': 5, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 2 with value: 0.634676218599943.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:11:16,796] Trial 6 finished with value: 0.6269397967183427 and parameters: {'n_estimators': 100, 'max_depth': 6, 'min_samples_split': 3, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 2 with value: 0.634676218599943.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:11:25,717] Trial 7 finished with value: 0.5426863686970047 and parameters: {'n_estimators': 300, 'max_depth': 12, 'min_samples_split': 10, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 2 with value: 0.634676218599943.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:11:34,170] Trial 8 finished with value: 0.6297362755766922 and parameters: {'n_estimators': 500, 'max_depth': 9, 'min_samples_split': 8, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 2 with value: 0.634676218599943.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:11:35,895] Trial 9 finished with value: 0.6284830080914091 and parameters: {'n_estimators': 100, 'max_depth': 6, 'min_samples_split': 8, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 2 with value: 0.634676218599943.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:11:44,922] Trial 10 finished with value: 0.6374231831579638 and parameters: {'n_estimators': 500, 'max_depth': 10, 'min_samples_split': 2, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 10 with value: 0.6374231831579638.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:11:53,954] Trial 11 finished with value: 0.6374231831579638 and parameters: {'n_estimators': 500, 'max_depth': 10, 'min_samples_split': 2, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 10 with value: 0.6374231831579638.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:12:02,906] Trial 12 finished with value: 0.6374231831579638 and parameters: {'n_estimators': 500, 'max_depth': 10, 'min_samples_split': 2, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 10 with value: 0.6374231831579638.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:12:11,872] Trial 13 finished with value: 0.6373519421112613 and parameters: {'n_estimators': 500, 'max_depth': 9, 'min_samples_split': 5, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 10 with value: 0.6374231831579638.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:12:20,876] Trial 14 finished with value: 0.6369371115509521 and parameters: {'n_estimators': 500, 'max_depth': 11, 'min_samples_split': 2, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 10 with value: 0.6374231831579638.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:12:29,831] Trial 15 finished with value: 0.6373519421112613 and parameters: {'n_estimators': 500, 'max_depth': 9, 'min_samples_split': 4, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 10 with value: 0.6374231831579638.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:12:38,682] Trial 16 finished with value: 0.6364685857314886 and parameters: {'n_estimators': 500, 'max_depth': 8, 'min_samples_split': 2, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 10 with value: 0.6374231831579638.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:12:49,251] Trial 17 finished with value: 0.64118397467917 and parameters: {'n_estimators': 500, 'max_depth': 11, 'min_samples_split': 4, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 17 with value: 0.64118397467917.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:12:59,843] Trial 18 finished with value: 0.64118397467917 and parameters: {'n_estimators': 500, 'max_depth': 11, 'min_samples_split': 4, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 17 with value: 0.64118397467917.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:13:10,091] Trial 19 finished with value: 0.6369411214345291 and parameters: {'n_estimators': 500, 'max_depth': 11, 'min_samples_split': 6, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 17 with value: 0.64118397467917.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:13:20,482] Trial 20 finished with value: 0.6398884507718563 and parameters: {'n_estimators': 500, 'max_depth': 12, 'min_samples_split': 5, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 17 with value: 0.64118397467917.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:13:31,008] Trial 21 finished with value: 0.6398884507718563 and parameters: {'n_estimators': 500, 'max_depth': 12, 'min_samples_split': 5, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 17 with value: 0.64118397467917.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:13:42,463] Trial 22 finished with value: 0.6360409144451272 and parameters: {'n_estimators': 500, 'max_depth': 11, 'min_samples_split': 4, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 17 with value: 0.64118397467917.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:13:53,087] Trial 23 finished with value: 0.6407214844594042 and parameters: {'n_estimators': 500, 'max_depth': 12, 'min_samples_split': 4, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 17 with value: 0.64118397467917.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:14:03,718] Trial 24 finished with value: 0.6409244851854656 and parameters: {'n_estimators': 500, 'max_depth': 14, 'min_samples_split': 4, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 17 with value: 0.64118397467917.
[I 2025-09-04 17:14:03,719] A new study created in memory with name: no-name-65bfbd00-574d-4d64-a94d-25ba17e435c1

✅ RF con C2X-Complex_rhown_5x5_depth_in_3_4 - Mejor R2: 0.64
📋 Parámetros: {'n_estimators': 500, 'max_depth': 11, 'min_samples_split': 4, 'min_samples_leaf': 2, 'bootstrap': True}

Buscando mejores hiperparámetros para CAT con C2X-Complex_rhown_5x5_depth_in_3_4...

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:15:53,007] Trial 0 finished with value: 0.5678794106463189 and parameters: {'iterations': 1000, 'learning_rate': 0.020076629153111814, 'depth': 9, 'l2_leaf_reg': 1.7168694648554308}. Best is trial 0 with value: 0.5678794106463189.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:15:56,768] Trial 1 finished with value: 0.5984331249352381 and parameters: {'iterations': 1000, 'learning_rate': 0.011508864841922409, 'depth': 4, 'l2_leaf_reg': 5.2846574193352}. Best is trial 1 with value: 0.5984331249352381.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:16:00,986] Trial 2 finished with value: 0.5935035913110756 and parameters: {'iterations': 500, 'learning_rate': 0.041849045517136786, 'depth': 6, 'l2_leaf_reg': 3.8300721969799407}. Best is trial 1 with value: 0.5984331249352381.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:16:49,334] Trial 3 finished with value: 0.6011486119395649 and parameters: {'iterations': 1000, 'learning_rate': 0.0177820503168831, 'depth': 8, 'l2_leaf_reg': 3.7443337177093707}. Best is trial 3 with value: 0.6011486119395649.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:18:24,256] Trial 4 finished with value: 0.5905379119809403 and parameters: {'iterations': 500, 'learning_rate': 0.01986537802479347, 'depth': 10, 'l2_leaf_reg': 3.870465099376744}. Best is trial 3 with value: 0.6011486119395649.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:18:48,874] Trial 5 finished with value: 0.5890024727678698 and parameters: {'iterations': 500, 'learning_rate': 0.05267620005941503, 'depth': 8, 'l2_leaf_reg': 2.1496491433324123}. Best is trial 3 with value: 0.6011486119395649.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:19:05,827] Trial 6 finished with value: 0.5817661330718735 and parameters: {'iterations': 2000, 'learning_rate': 0.018666331921512375, 'depth': 6, 'l2_leaf_reg': 4.5372569025564164}. Best is trial 3 with value: 0.6011486119395649.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:20:51,767] Trial 7 finished with value: 0.5926913205183952 and parameters: {'iterations': 1000, 'learning_rate': 0.011996483467620275, 'depth': 9, 'l2_leaf_reg': 4.507755960273418}. Best is trial 3 with value: 0.6011486119395649.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:20:56,076] Trial 8 finished with value: 0.601282185190646 and parameters: {'iterations': 500, 'learning_rate': 0.019779885016736977, 'depth': 6, 'l2_leaf_reg': 5.4953902811947675}. Best is trial 8 with value: 0.601282185190646.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:27:31,086] Trial 9 finished with value: 0.581222570728496 and parameters: {'iterations': 2000, 'learning_rate': 0.030925566119983802, 'depth': 10, 'l2_leaf_reg': 1.540234042644689}. Best is trial 8 with value: 0.601282185190646.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:27:32,929] Trial 10 finished with value: 0.5664488227319773 and parameters: {'iterations': 500, 'learning_rate': 0.07072143952054775, 'depth': 4, 'l2_leaf_reg': 5.403116664292401}. Best is trial 8 with value: 0.601282185190646.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:27:52,939] Trial 11 finished with value: 0.5920795507274801 and parameters: {'iterations': 1000, 'learning_rate': 0.015565394288269847, 'depth': 7, 'l2_leaf_reg': 2.851523519354779}. Best is trial 8 with value: 0.601282185190646.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:27:57,099] Trial 12 finished with value: 0.6029450970602507 and parameters: {'iterations': 500, 'learning_rate': 0.025340947072845177, 'depth': 6, 'l2_leaf_reg': 5.927927435982809}. Best is trial 12 with value: 0.6029450970602507.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:27:59,730] Trial 13 finished with value: 0.591228476288957 and parameters: {'iterations': 500, 'learning_rate': 0.03134113947612321, 'depth': 5, 'l2_leaf_reg': 5.996186542980029}. Best is trial 12 with value: 0.6029450970602507.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:28:03,970] Trial 14 finished with value: 0.6006839648932368 and parameters: {'iterations': 500, 'learning_rate': 0.02494977404686283, 'depth': 6, 'l2_leaf_reg': 5.974846555186838}. Best is trial 12 with value: 0.6029450970602507.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:28:06,822] Trial 15 finished with value: 0.5994845237086962 and parameters: {'iterations': 500, 'learning_rate': 0.039946920575755884, 'depth': 5, 'l2_leaf_reg': 5.083740939666213}. Best is trial 12 with value: 0.6029450970602507.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:28:46,774] Trial 16 finished with value: 0.5845469117679851 and parameters: {'iterations': 2000, 'learning_rate': 0.02462092142381295, 'depth': 7, 'l2_leaf_reg': 4.622808457949471}. Best is trial 12 with value: 0.6029450970602507.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:28:49,502] Trial 17 finished with value: 0.5973073016409174 and parameters: {'iterations': 500, 'learning_rate': 0.014839990671966957, 'depth': 5, 'l2_leaf_reg': 3.0533223645517933}. Best is trial 12 with value: 0.6029450970602507.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:28:53,818] Trial 18 finished with value: 0.5940463897477873 and parameters: {'iterations': 500, 'learning_rate': 0.025519722231496924, 'depth': 6, 'l2_leaf_reg': 5.607188004568734}. Best is trial 12 with value: 0.6029450970602507.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:29:17,819] Trial 19 finished with value: 0.5982052337098647 and parameters: {'iterations': 500, 'learning_rate': 0.03757058486456075, 'depth': 8, 'l2_leaf_reg': 4.961431712621442}. Best is trial 12 with value: 0.6029450970602507.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:29:58,051] Trial 20 finished with value: 0.5828527245054691 and parameters: {'iterations': 2000, 'learning_rate': 0.05323033028554541, 'depth': 7, 'l2_leaf_reg': 4.435513848823737}. Best is trial 12 with value: 0.6029450970602507.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:30:46,392] Trial 21 finished with value: 0.5888273538210821 and parameters: {'iterations': 1000, 'learning_rate': 0.015729018517072174, 'depth': 8, 'l2_leaf_reg': 2.657267575313142}. Best is trial 12 with value: 0.6029450970602507.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:31:34,963] Trial 22 finished with value: 0.5976778395559129 and parameters: {'iterations': 1000, 'learning_rate': 0.02178378406477714, 'depth': 8, 'l2_leaf_reg': 3.593438484435364}. Best is trial 12 with value: 0.6029450970602507.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:31:55,138] Trial 23 finished with value: 0.5989087617616371 and parameters: {'iterations': 1000, 'learning_rate': 0.013704248550081467, 'depth': 7, 'l2_leaf_reg': 5.639271681426446}. Best is trial 12 with value: 0.6029450970602507.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:31:58,048] Trial 24 finished with value: 0.5985710377788913 and parameters: {'iterations': 500, 'learning_rate': 0.017365073094772723, 'depth': 5, 'l2_leaf_reg': 4.003771299898803}. Best is trial 12 with value: 0.6029450970602507.
[I 2025-09-04 17:31:58,049] A new study created in memory with name: no-name-6ec9aca8-f838-400c-ac09-4ae4c6ed5bf4
[I 2025-09-04 17:31:58,159] Trial 0 finished with value: 0.5726659410951769 and parameters: {'alpha': 0.029440640009221405, 'l1_ratio': 0.9952562878940697}. Best is trial 0 with value: 0.5726659410951769.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.182e+00, tolerance: 4.876e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.690e+00, tolerance: 5.544e-02
  model = cd_fast.enet_coordinate_descent(

✅ CAT con C2X-Complex_rhown_5x5_depth_in_3_4 - Mejor R2: 0.60
📋 Parámetros: {'iterations': 500, 'learning_rate': 0.025340947072845177, 'depth': 6, 'l2_leaf_reg': 5.927927435982809}

Buscando mejores hiperparámetros para ELN con C2X-Complex_rhown_5x5_depth_in_3_4...

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.658e+00, tolerance: 4.561e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.636e+00, tolerance: 4.433e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.110e+00, tolerance: 5.000e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 17:31:58,339] Trial 1 finished with value: 0.5586121353497617 and parameters: {'alpha': 0.043179738339647354, 'l1_ratio': 0.02836187734148854}. Best is trial 0 with value: 0.5726659410951769.

Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 17:31:58,520] Trial 2 finished with value: 0.5624810836285892 and parameters: {'alpha': 0.0663330192344642, 'l1_ratio': 0.101562999394046}. Best is trial 0 with value: 0.5726659410951769.

Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:31:58,725] Trial 3 finished with value: 0.5639515728600482 and parameters: {'alpha': 0.00921654864892971, 'l1_ratio': 0.8887189302906242}. Best is trial 0 with value: 0.5726659410951769.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.869e+01, tolerance: 4.876e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.059e+01, tolerance: 5.544e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.126e+01, tolerance: 4.561e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.715e+01, tolerance: 4.433e-02
  model = cd_fast.enet_coordinate_descent(

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.646e+01, tolerance: 5.000e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 17:31:58,937] Trial 4 finished with value: 0.529748656617287 and parameters: {'alpha': 0.0005152396206227935, 'l1_ratio': 0.6287131662056219}. Best is trial 0 with value: 0.5726659410951769.
[I 2025-09-04 17:31:59,125] Trial 5 finished with value: 0.5667483768769295 and parameters: {'alpha': 0.023528922603695275, 'l1_ratio': 0.6881738350138165}. Best is trial 0 with value: 0.5726659410951769.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.099e-01, tolerance: 5.544e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.244e-01, tolerance: 4.561e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.319e+00, tolerance: 4.433e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.326e+00, tolerance: 5.000e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 17:31:59,278] Trial 6 finished with value: 0.5585808367022879 and parameters: {'alpha': 0.0075300375223693716, 'l1_ratio': 0.3530168708733119}. Best is trial 0 with value: 0.5726659410951769.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.870e+00, tolerance: 4.876e-02
  model = cd_fast.enet_coordinate_descent(

Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.844e+00, tolerance: 5.544e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.699e+00, tolerance: 4.561e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.171e+00, tolerance: 4.433e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.714e+00, tolerance: 5.000e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 17:31:59,489] Trial 7 finished with value: 0.5551440250859234 and parameters: {'alpha': 0.0025503745000901037, 'l1_ratio': 0.44714543016929587}. Best is trial 0 with value: 0.5726659410951769.

Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2

[I 2025-09-04 17:31:59,649] Trial 8 finished with value: 0.5191390340123667 and parameters: {'alpha': 0.1861838973885082, 'l1_ratio': 0.4221996719598222}. Best is trial 0 with value: 0.5726659410951769.

Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.080e+02, tolerance: 4.876e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.172e+02, tolerance: 5.544e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.145e+01, tolerance: 4.561e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.206e+01, tolerance: 4.433e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.105e+02, tolerance: 5.000e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 17:31:59,905] Trial 9 finished with value: 0.5177133562645607 and parameters: {'alpha': 0.00012033949638352292, 'l1_ratio': 0.5536797248767369}. Best is trial 0 with value: 0.5726659410951769.

Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2

[I 2025-09-04 17:32:00,131] Trial 10 finished with value: 0.19680024201453727 and parameters: {'alpha': 0.8151780356089224, 'l1_ratio': 0.8833649433766254}. Best is trial 0 with value: 0.5726659410951769.

Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2

[I 2025-09-04 17:32:00,350] Trial 11 finished with value: 0.5707018323667843 and parameters: {'alpha': 0.04088692793886775, 'l1_ratio': 0.9809539154088679}. Best is trial 0 with value: 0.5726659410951769.

Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 17:32:00,478] Trial 12 finished with value: 0.47747813047323784 and parameters: {'alpha': 0.21468630167657818, 'l1_ratio': 0.9844869686721965}. Best is trial 0 with value: 0.5726659410951769.

Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.987e-02, tolerance: 4.876e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.368e-01, tolerance: 5.544e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.096e-02, tolerance: 4.561e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.109e-01, tolerance: 4.433e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.382e-01, tolerance: 5.000e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 17:32:00,713] Trial 13 finished with value: 0.558916885341332 and parameters: {'alpha': 0.004630560277871707, 'l1_ratio': 0.770008982438992}. Best is trial 0 with value: 0.5726659410951769.

Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.507e+00, tolerance: 4.876e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.786e-01, tolerance: 5.544e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.113e-01, tolerance: 4.561e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.237e+00, tolerance: 4.433e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.132e-01, tolerance: 5.000e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 17:32:00,935] Trial 14 finished with value: 0.5532342832239965 and parameters: {'alpha': 0.0017678287871426, 'l1_ratio': 0.971590787278431}. Best is trial 0 with value: 0.5726659410951769.

Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:32:01,093] Trial 15 finished with value: 0.5197199949429746 and parameters: {'alpha': 0.11058340705178464, 'l1_ratio': 0.759414220140046}. Best is trial 0 with value: 0.5726659410951769.
[I 2025-09-04 17:32:01,275] Trial 16 finished with value: 0.4361462845821461 and parameters: {'alpha': 0.9870181681381468, 'l1_ratio': 0.25414259444864823}. Best is trial 0 with value: 0.5726659410951769.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===

[I 2025-09-04 17:32:01,452] Trial 17 finished with value: 0.5674968048618343 and parameters: {'alpha': 0.022479608048898748, 'l1_ratio': 0.8605913046567872}. Best is trial 0 with value: 0.5726659410951769.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 17:32:01,580] Trial 18 finished with value: 0.567405110397857 and parameters: {'alpha': 0.023139287960293103, 'l1_ratio': 0.778989318364669}. Best is trial 0 with value: 0.5726659410951769.
[I 2025-09-04 17:32:01,697] Trial 19 finished with value: 0.46211330084413327 and parameters: {'alpha': 0.3919442629541838, 'l1_ratio': 0.5856949725057714}. Best is trial 0 with value: 0.5726659410951769.

Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.430e+01, tolerance: 4.876e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.643e+00, tolerance: 5.544e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.290e-01, tolerance: 4.561e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.875e-01, tolerance: 4.433e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.932e+00, tolerance: 5.000e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 17:32:01,861] Trial 20 finished with value: 0.5516184361965426 and parameters: {'alpha': 0.0011435271699816799, 'l1_ratio': 0.9872282743312104}. Best is trial 0 with value: 0.5726659410951769.

Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 17:32:02,006] Trial 21 finished with value: 0.5672055488596305 and parameters: {'alpha': 0.021542678899885176, 'l1_ratio': 0.873228529278135}. Best is trial 0 with value: 0.5726659410951769.

Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:32:02,162] Trial 22 finished with value: 0.570535118113271 and parameters: {'alpha': 0.044592298176261605, 'l1_ratio': 0.8609265474344593}. Best is trial 0 with value: 0.5726659410951769.
[I 2025-09-04 17:32:02,336] Trial 23 finished with value: 0.5493970051841279 and parameters: {'alpha': 0.05962272990858728, 'l1_ratio': 0.9373385146927198}. Best is trial 0 with value: 0.5726659410951769.

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_5x5_depth_in_3_4 ===
Fold 1

[I 2025-09-04 17:32:02,530] Trial 24 finished with value: 0.5338441135223269 and parameters: {'alpha': 0.08081392667894928, 'l1_ratio': 0.8185877928099872}. Best is trial 0 with value: 0.5726659410951769.
[I 2025-09-04 17:32:02,531] A new study created in memory with name: no-name-00443b34-31d6-4488-94bf-42592e6961db

Fold 2
Fold 3
Fold 4
Fold 5

✅ ELN con C2X-Complex_rhown_5x5_depth_in_3_4 - Mejor R2: 0.57
📋 Parámetros: {'alpha': 0.029440640009221405, 'l1_ratio': 0.9952562878940697}

Buscando mejores hiperparámetros para XGB con C2X-Complex_rhow_9x9_depth_in_3_4...

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:32:13,176] Trial 0 finished with value: 0.603826735796965 and parameters: {'n_estimators': 1000, 'learning_rate': 0.04594343026150145, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.6601987547465097, 'colsample_bytree': 0.8649180879721878}. Best is trial 0 with value: 0.603826735796965.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:32:19,793] Trial 1 finished with value: 0.5901485428931343 and parameters: {'n_estimators': 500, 'learning_rate': 0.019199823501349605, 'max_depth': 8, 'min_child_weight': 3, 'subsample': 0.8170309415462883, 'colsample_bytree': 0.7883948476147957}. Best is trial 0 with value: 0.603826735796965.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:32:23,516] Trial 2 finished with value: 0.6099298308554919 and parameters: {'n_estimators': 500, 'learning_rate': 0.011197945243680282, 'max_depth': 5, 'min_child_weight': 1, 'subsample': 0.63306282985598, 'colsample_bytree': 0.6413028372198346}. Best is trial 2 with value: 0.6099298308554919.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:32:43,896] Trial 3 finished with value: 0.5914436138809802 and parameters: {'n_estimators': 2000, 'learning_rate': 0.005546384902358445, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.8088430705653044, 'colsample_bytree': 0.9465403834954988}. Best is trial 2 with value: 0.6099298308554919.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:33:01,923] Trial 4 finished with value: 0.5834349713944076 and parameters: {'n_estimators': 2000, 'learning_rate': 0.0062756905398420664, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.9670114233797587, 'colsample_bytree': 0.6748202237626212}. Best is trial 2 with value: 0.6099298308554919.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:33:05,998] Trial 5 finished with value: 0.6008618558756396 and parameters: {'n_estimators': 500, 'learning_rate': 0.017640089550745655, 'max_depth': 5, 'min_child_weight': 1, 'subsample': 0.7431099214657967, 'colsample_bytree': 0.8129391823794597}. Best is trial 2 with value: 0.6099298308554919.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:33:20,840] Trial 6 finished with value: 0.5987226000931305 and parameters: {'n_estimators': 2000, 'learning_rate': 0.0283086119677731, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.6313777463878179, 'colsample_bytree': 0.7028694324377109}. Best is trial 2 with value: 0.6099298308554919.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:33:44,944] Trial 7 finished with value: 0.5929477823063065 and parameters: {'n_estimators': 2000, 'learning_rate': 0.011165127861940675, 'max_depth': 8, 'min_child_weight': 3, 'subsample': 0.8609754755926686, 'colsample_bytree': 0.9254839109009916}. Best is trial 2 with value: 0.6099298308554919.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:34:03,099] Trial 8 finished with value: 0.5797383075875349 and parameters: {'n_estimators': 2000, 'learning_rate': 0.008522641442074779, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.9674743411466749, 'colsample_bytree': 0.6819703410612437}. Best is trial 2 with value: 0.6099298308554919.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:34:06,425] Trial 9 finished with value: 0.6051297710704395 and parameters: {'n_estimators': 500, 'learning_rate': 0.02051644945841298, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.7812969422280248, 'colsample_bytree': 0.6656793915518391}. Best is trial 2 with value: 0.6099298308554919.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:34:14,506] Trial 10 finished with value: 0.6063320071040635 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01118474806800999, 'max_depth': 5, 'min_child_weight': 1, 'subsample': 0.6924501772938999, 'colsample_bytree': 0.6097502146158172}. Best is trial 2 with value: 0.6099298308554919.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:34:22,426] Trial 11 finished with value: 0.6040755379585402 and parameters: {'n_estimators': 1000, 'learning_rate': 0.011512039698693171, 'max_depth': 5, 'min_child_weight': 1, 'subsample': 0.6932601068311909, 'colsample_bytree': 0.602683526754696}. Best is trial 2 with value: 0.6099298308554919.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:34:31,724] Trial 12 finished with value: 0.6022857608105019 and parameters: {'n_estimators': 1000, 'learning_rate': 0.011234496591662398, 'max_depth': 6, 'min_child_weight': 1, 'subsample': 0.6071694745645103, 'colsample_bytree': 0.6053564654878049}. Best is trial 2 with value: 0.6099298308554919.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:34:39,805] Trial 13 finished with value: 0.606312792662379 and parameters: {'n_estimators': 1000, 'learning_rate': 0.008554956777032694, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.7066957820735211, 'colsample_bytree': 0.7492056083892431}. Best is trial 2 with value: 0.6099298308554919.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:34:43,502] Trial 14 finished with value: 0.5984362834746431 and parameters: {'n_estimators': 500, 'learning_rate': 0.014017757090647039, 'max_depth': 5, 'min_child_weight': 1, 'subsample': 0.6706713507391155, 'colsample_bytree': 0.6308124573246813}. Best is trial 2 with value: 0.6099298308554919.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:34:53,242] Trial 15 finished with value: 0.5976543307880555 and parameters: {'n_estimators': 1000, 'learning_rate': 0.028096202623169204, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.7353679833332265, 'colsample_bytree': 0.7439922163644296}. Best is trial 2 with value: 0.6099298308554919.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:34:57,299] Trial 16 finished with value: 0.607650315394007 and parameters: {'n_estimators': 500, 'learning_rate': 0.0076752429868369885, 'max_depth': 5, 'min_child_weight': 1, 'subsample': 0.6086119953293657, 'colsample_bytree': 0.7307746629485514}. Best is trial 2 with value: 0.6099298308554919.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:35:03,921] Trial 17 finished with value: 0.6156829070781086 and parameters: {'n_estimators': 500, 'learning_rate': 0.007784242501186818, 'max_depth': 6, 'min_child_weight': 1, 'subsample': 0.6045990140239461, 'colsample_bytree': 0.9996062608334324}. Best is trial 17 with value: 0.6156829070781086.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:35:11,183] Trial 18 finished with value: 0.5669303714048037 and parameters: {'n_estimators': 500, 'learning_rate': 0.005119493132464131, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.8925973564699476, 'colsample_bytree': 0.9980482957944603}. Best is trial 17 with value: 0.6156829070781086.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:35:17,567] Trial 19 finished with value: 0.6095182012079192 and parameters: {'n_estimators': 500, 'learning_rate': 0.006936362866874648, 'max_depth': 6, 'min_child_weight': 1, 'subsample': 0.642399892496335, 'colsample_bytree': 0.8562986349649695}. Best is trial 17 with value: 0.6156829070781086.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:35:25,003] Trial 20 finished with value: 0.6055221084027445 and parameters: {'n_estimators': 500, 'learning_rate': 0.009427972164815272, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.7494901552723643, 'colsample_bytree': 0.8929352409549771}. Best is trial 17 with value: 0.6156829070781086.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:35:31,513] Trial 21 finished with value: 0.6087116505291479 and parameters: {'n_estimators': 500, 'learning_rate': 0.006808247924218286, 'max_depth': 6, 'min_child_weight': 1, 'subsample': 0.6376061107401054, 'colsample_bytree': 0.8428236553007574}. Best is trial 17 with value: 0.6156829070781086.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:35:38,662] Trial 22 finished with value: 0.6106237458734085 and parameters: {'n_estimators': 500, 'learning_rate': 0.006878539023642598, 'max_depth': 6, 'min_child_weight': 1, 'subsample': 0.6010305228168966, 'colsample_bytree': 0.9938496745689548}. Best is trial 17 with value: 0.6156829070781086.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:35:45,110] Trial 23 finished with value: 0.6091350471813387 and parameters: {'n_estimators': 500, 'learning_rate': 0.0144819286058574, 'max_depth': 6, 'min_child_weight': 1, 'subsample': 0.6009055577559369, 'colsample_bytree': 0.9970675342436082}. Best is trial 17 with value: 0.6156829070781086.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:35:53,784] Trial 24 finished with value: 0.6056351645721232 and parameters: {'n_estimators': 500, 'learning_rate': 0.009037239741975199, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.6634439832851683, 'colsample_bytree': 0.9511975589162176}. Best is trial 17 with value: 0.6156829070781086.
[I 2025-09-04 17:35:53,786] A new study created in memory with name: no-name-706c393f-c765-4367-92fe-7887a6763894

✅ XGB con C2X-Complex_rhow_9x9_depth_in_3_4 - Mejor R2: 0.62
📋 Parámetros: {'n_estimators': 500, 'learning_rate': 0.007784242501186818, 'max_depth': 6, 'min_child_weight': 1, 'subsample': 0.6045990140239461, 'colsample_bytree': 0.9996062608334324}

Buscando mejores hiperparámetros para LBM con C2X-Complex_rhow_9x9_depth_in_3_4...

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:35:54,259] Trial 0 finished with value: 0.603212325028474 and parameters: {'learning_rate': 0.02919789002006116, 'num_leaves': 60, 'max_depth': 7, 'min_child_samples': 6, 'subsample': 0.7399046380683875, 'colsample_bytree': 0.8351271685755522, 'n_estimators': 500}. Best is trial 0 with value: 0.603212325028474.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 17:35:54,960] Trial 1 finished with value: 0.5791768011466385 and parameters: {'learning_rate': 0.024142409284028082, 'num_leaves': 20, 'max_depth': 8, 'min_child_samples': 16, 'subsample': 0.6993269011387133, 'colsample_bytree': 0.8121521340484827, 'n_estimators': 1000}. Best is trial 0 with value: 0.603212325028474.

Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:35:55,974] Trial 2 finished with value: 0.5659568282217381 and parameters: {'learning_rate': 0.005834372502398222, 'num_leaves': 40, 'max_depth': 5, 'min_child_samples': 11, 'subsample': 0.914796894637772, 'colsample_bytree': 0.877322837749688, 'n_estimators': 2000}. Best is trial 0 with value: 0.603212325028474.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 17:35:56,818] Trial 3 finished with value: 0.5863675832513984 and parameters: {'learning_rate': 0.0304072239275533, 'num_leaves': 60, 'max_depth': 7, 'min_child_samples': 5, 'subsample': 0.9244175718611426, 'colsample_bytree': 0.627986604408424, 'n_estimators': 1000}. Best is trial 0 with value: 0.603212325028474.

Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:35:58,183] Trial 4 finished with value: 0.5797479924342082 and parameters: {'learning_rate': 0.005334875582773233, 'num_leaves': 60, 'max_depth': 6, 'min_child_samples': 8, 'subsample': 0.8962217811379567, 'colsample_bytree': 0.9947888735788573, 'n_estimators': 2000}. Best is trial 0 with value: 0.603212325028474.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 17:35:58,635] Trial 5 finished with value: 0.5793786871533496 and parameters: {'learning_rate': 0.02162241576996398, 'num_leaves': 60, 'max_depth': 6, 'min_child_samples': 4, 'subsample': 0.765576119369777, 'colsample_bytree': 0.8266260310428748, 'n_estimators': 500}. Best is trial 0 with value: 0.603212325028474.

Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:35:59,660] Trial 6 finished with value: 0.5667742463954728 and parameters: {'learning_rate': 0.008026916441632644, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 9, 'subsample': 0.9164981181256144, 'colsample_bytree': 0.7605338597925219, 'n_estimators': 2000}. Best is trial 0 with value: 0.603212325028474.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 17:36:00,396] Trial 7 finished with value: 0.5580260959259243 and parameters: {'learning_rate': 0.04579580283528125, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 8, 'subsample': 0.8071757052884996, 'colsample_bytree': 0.8529660463309088, 'n_estimators': 1000}. Best is trial 0 with value: 0.603212325028474.

Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:36:01,210] Trial 8 finished with value: 0.5800358490424159 and parameters: {'learning_rate': 0.008697623016471003, 'num_leaves': 80, 'max_depth': 8, 'min_child_samples': 11, 'subsample': 0.6047331181311137, 'colsample_bytree': 0.9040396467989691, 'n_estimators': 1000}. Best is trial 0 with value: 0.603212325028474.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 17:36:01,482] Trial 9 finished with value: 0.5738705403075774 and parameters: {'learning_rate': 0.028143757253246, 'num_leaves': 60, 'max_depth': 5, 'min_child_samples': 14, 'subsample': 0.8844590500449386, 'colsample_bytree': 0.6898616747523969, 'n_estimators': 500}. Best is trial 0 with value: 0.603212325028474.

Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:36:02,018] Trial 10 finished with value: 0.5892497392774452 and parameters: {'learning_rate': 0.014136826472116636, 'num_leaves': 40, 'max_depth': 7, 'min_child_samples': 6, 'subsample': 0.6697921217284619, 'colsample_bytree': 0.9700190642672393, 'n_estimators': 500}. Best is trial 0 with value: 0.603212325028474.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:36:02,520] Trial 11 finished with value: 0.5862141396933678 and parameters: {'learning_rate': 0.013555608279512892, 'num_leaves': 40, 'max_depth': 7, 'min_child_samples': 6, 'subsample': 0.6600590404308023, 'colsample_bytree': 0.9854998347931567, 'n_estimators': 500}. Best is trial 0 with value: 0.603212325028474.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:36:03,024] Trial 12 finished with value: 0.5828303613245635 and parameters: {'learning_rate': 0.015633636631205147, 'num_leaves': 40, 'max_depth': 7, 'min_child_samples': 6, 'subsample': 0.7451951068675415, 'colsample_bytree': 0.926096618733996, 'n_estimators': 500}. Best is trial 0 with value: 0.603212325028474.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 17:36:03,486] Trial 13 finished with value: 0.5863390481599242 and parameters: {'learning_rate': 0.04920182498656643, 'num_leaves': 80, 'max_depth': 8, 'min_child_samples': 7, 'subsample': 0.6715597422996668, 'colsample_bytree': 0.7410432724159741, 'n_estimators': 500}. Best is trial 0 with value: 0.603212325028474.

Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 17:36:04,023] Trial 14 finished with value: 0.5628929179929201 and parameters: {'learning_rate': 0.011662239804444374, 'num_leaves': 40, 'max_depth': 6, 'min_child_samples': 4, 'subsample': 0.8343305547886312, 'colsample_bytree': 0.9447123472265065, 'n_estimators': 500}. Best is trial 0 with value: 0.603212325028474.

Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:36:04,415] Trial 15 finished with value: 0.5781256733172901 and parameters: {'learning_rate': 0.01976021804803563, 'num_leaves': 60, 'max_depth': 7, 'min_child_samples': 10, 'subsample': 0.9808463553781975, 'colsample_bytree': 0.758399333838979, 'n_estimators': 500}. Best is trial 0 with value: 0.603212325028474.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 17:36:04,829] Trial 16 finished with value: 0.5844363164358215 and parameters: {'learning_rate': 0.03971142376519308, 'num_leaves': 40, 'max_depth': 6, 'min_child_samples': 6, 'subsample': 0.7370997197487484, 'colsample_bytree': 0.937185940483383, 'n_estimators': 500}. Best is trial 0 with value: 0.603212325028474.

Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 17:36:05,249] Trial 17 finished with value: 0.6220412676292313 and parameters: {'learning_rate': 0.010625896656703103, 'num_leaves': 80, 'max_depth': 8, 'min_child_samples': 13, 'subsample': 0.6090184771943212, 'colsample_bytree': 0.6849865134926467, 'n_estimators': 500}. Best is trial 17 with value: 0.6220412676292313.

Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:36:05,655] Trial 18 finished with value: 0.6215339916786389 and parameters: {'learning_rate': 0.010067153986943049, 'num_leaves': 80, 'max_depth': 8, 'min_child_samples': 13, 'subsample': 0.6042658087883542, 'colsample_bytree': 0.6180773202250172, 'n_estimators': 500}. Best is trial 17 with value: 0.6220412676292313.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:36:07,017] Trial 19 finished with value: 0.5752848091765648 and parameters: {'learning_rate': 0.009637868933777705, 'num_leaves': 80, 'max_depth': 8, 'min_child_samples': 13, 'subsample': 0.6041500813339191, 'colsample_bytree': 0.6047945764058814, 'n_estimators': 2000}. Best is trial 17 with value: 0.6220412676292313.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 17:36:07,473] Trial 20 finished with value: 0.6228268007994398 and parameters: {'learning_rate': 0.006582353357462178, 'num_leaves': 80, 'max_depth': 8, 'min_child_samples': 13, 'subsample': 0.6109346905731258, 'colsample_bytree': 0.6631951757691366, 'n_estimators': 500}. Best is trial 20 with value: 0.6228268007994398.

Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 17:36:07,899] Trial 21 finished with value: 0.6235475043712739 and parameters: {'learning_rate': 0.006387333436517826, 'num_leaves': 80, 'max_depth': 8, 'min_child_samples': 13, 'subsample': 0.6384425602632136, 'colsample_bytree': 0.6626794560644892, 'n_estimators': 500}. Best is trial 21 with value: 0.6235475043712739.

Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:36:08,293] Trial 22 finished with value: 0.6148526337574567 and parameters: {'learning_rate': 0.006920009428845106, 'num_leaves': 80, 'max_depth': 8, 'min_child_samples': 15, 'subsample': 0.6436125566040957, 'colsample_bytree': 0.6720951698509661, 'n_estimators': 500}. Best is trial 21 with value: 0.6235475043712739.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 17:36:08,759] Trial 23 finished with value: 0.6118985799049612 and parameters: {'learning_rate': 0.006280204084490925, 'num_leaves': 80, 'max_depth': 8, 'min_child_samples': 12, 'subsample': 0.6403354650663222, 'colsample_bytree': 0.6838742324224077, 'n_estimators': 500}. Best is trial 21 with value: 0.6235475043712739.

Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 17:36:09,179] Trial 24 finished with value: 0.6231939914647581 and parameters: {'learning_rate': 0.007342776879438683, 'num_leaves': 80, 'max_depth': 8, 'min_child_samples': 14, 'subsample': 0.6985781873919709, 'colsample_bytree': 0.7140522035308343, 'n_estimators': 500}. Best is trial 21 with value: 0.6235475043712739.
[I 2025-09-04 17:36:09,181] A new study created in memory with name: no-name-dbcf0f33-268c-460b-b402-c3eece1635a9

Fold 4
Fold 5

✅ LBM con C2X-Complex_rhow_9x9_depth_in_3_4 - Mejor R2: 0.62
📋 Parámetros: {'learning_rate': 0.006387333436517826, 'num_leaves': 80, 'max_depth': 8, 'min_child_samples': 13, 'subsample': 0.6384425602632136, 'colsample_bytree': 0.6626794560644892, 'n_estimators': 500}

Buscando mejores hiperparámetros para MLP con C2X-Complex_rhow_9x9_depth_in_3_4...

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 17:36:10,388] Trial 0 finished with value: 0.569577090704809 and parameters: {'hidden_layer_sizes': '128', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.021357654924644774, 'learning_rate': 'adaptive', 'learning_rate_init': 0.005493778370831619}. Best is trial 0 with value: 0.569577090704809.

Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:36:12,509] Trial 1 finished with value: 0.6308300013611483 and parameters: {'hidden_layer_sizes': '256_128', 'activation': 'relu', 'solver': 'adam', 'alpha': 4.605951094425392e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.009017405716517532}. Best is trial 1 with value: 0.6308300013611483.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:36:15,615] Trial 2 finished with value: 0.5602807485653687 and parameters: {'hidden_layer_sizes': '256_128', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.004286426295585343, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0061502949803140155}. Best is trial 1 with value: 0.6308300013611483.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 17:36:16,588] Trial 3 finished with value: 0.5541382648635658 and parameters: {'hidden_layer_sizes': '128', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.001418900190021927, 'learning_rate': 'constant', 'learning_rate_init': 0.001782620442092695}. Best is trial 1 with value: 0.6308300013611483.

Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

[I 2025-09-04 17:36:18,700] Trial 4 finished with value: 0.5710364030867134 and parameters: {'hidden_layer_sizes': '128', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.028099565878064316, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0007697755038485066}. Best is trial 1 with value: 0.6308300013611483.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3
Fold 4

[I 2025-09-04 17:36:20,507] Trial 5 finished with value: 0.4426737411456082 and parameters: {'hidden_layer_sizes': '256', 'activation': 'relu', 'solver': 'sgd', 'alpha': 2.7963233526179547e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.00012691835319412247}. Best is trial 1 with value: 0.6308300013611483.

Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 17:36:22,019] Trial 6 finished with value: 0.4919152191607806 and parameters: {'hidden_layer_sizes': '256', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.00012511831460626177, 'learning_rate': 'constant', 'learning_rate_init': 0.00025626972181802684}. Best is trial 1 with value: 0.6308300013611483.

Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3
Fold 4

[I 2025-09-04 17:36:23,681] Trial 7 finished with value: 0.44477229513671446 and parameters: {'hidden_layer_sizes': '256', 'activation': 'relu', 'solver': 'sgd', 'alpha': 2.8318618322598447e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.0001314493640049232}. Best is trial 1 with value: 0.6308300013611483.

Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-04 17:36:30,882] Trial 8 finished with value: 0.5512408256645689 and parameters: {'hidden_layer_sizes': '256_128', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 6.463504184128477e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0001726664499345077}. Best is trial 1 with value: 0.6308300013611483.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:36:33,725] Trial 9 finished with value: 0.5948008030123259 and parameters: {'hidden_layer_sizes': '256_128', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0002124099144057785, 'learning_rate': 'constant', 'learning_rate_init': 0.0016087626178076862}. Best is trial 1 with value: 0.6308300013611483.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 17:36:34,837] Trial 10 finished with value: 0.566145022897319 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 1.1092028696859723e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.008368303663415734}. Best is trial 1 with value: 0.6308300013611483.

Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:36:37,298] Trial 11 finished with value: 0.5960931459901888 and parameters: {'hidden_layer_sizes': '256_128', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.00033270813166858703, 'learning_rate': 'constant', 'learning_rate_init': 0.00216305923902603}. Best is trial 1 with value: 0.6308300013611483.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:36:40,032] Trial 12 finished with value: 0.5690161676011452 and parameters: {'hidden_layer_sizes': '256_128', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.000509226948964843, 'learning_rate': 'constant', 'learning_rate_init': 0.0031535362551047747}. Best is trial 1 with value: 0.6308300013611483.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:36:42,026] Trial 13 finished with value: 0.6491402324005311 and parameters: {'hidden_layer_sizes': '256_128', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0014611726954603002, 'learning_rate': 'constant', 'learning_rate_init': 0.0006912854086058073}. Best is trial 13 with value: 0.6491402324005311.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 17:36:43,538] Trial 14 finished with value: 0.6145422293787164 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0028844444920960314, 'learning_rate': 'constant', 'learning_rate_init': 0.0005749592828707585}. Best is trial 13 with value: 0.6491402324005311.

Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:36:46,047] Trial 15 finished with value: 0.6475247561012613 and parameters: {'hidden_layer_sizes': '256_128', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.009440721789003056, 'learning_rate': 'constant', 'learning_rate_init': 0.000408530165245753}. Best is trial 13 with value: 0.6491402324005311.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:36:48,674] Trial 16 finished with value: 0.6437668643858949 and parameters: {'hidden_layer_sizes': '256_128', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.07640709735474459, 'learning_rate': 'constant', 'learning_rate_init': 0.00039804157257856954}. Best is trial 13 with value: 0.6491402324005311.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:36:51,250] Trial 17 finished with value: 0.6443078968579302 and parameters: {'hidden_layer_sizes': '256_128', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.006958667976908195, 'learning_rate': 'constant', 'learning_rate_init': 0.00036974053206385827}. Best is trial 13 with value: 0.6491402324005311.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 17:36:52,453] Trial 18 finished with value: 0.5977972882524282 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.010807440111727186, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0009983240036674675}. Best is trial 13 with value: 0.6491402324005311.

Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:36:54,720] Trial 19 finished with value: 0.6459117838245558 and parameters: {'hidden_layer_sizes': '256_128', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0012556529653090236, 'learning_rate': 'constant', 'learning_rate_init': 0.0005533302016985027}. Best is trial 13 with value: 0.6491402324005311.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:36:57,565] Trial 20 finished with value: 0.6395078714542444 and parameters: {'hidden_layer_sizes': '256_128', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.07041079386149857, 'learning_rate': 'constant', 'learning_rate_init': 0.00024835488490003395}. Best is trial 13 with value: 0.6491402324005311.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:36:59,749] Trial 21 finished with value: 0.6464755195483428 and parameters: {'hidden_layer_sizes': '256_128', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0017495009500189684, 'learning_rate': 'constant', 'learning_rate_init': 0.000555913385753381}. Best is trial 13 with value: 0.6491402324005311.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:37:02,057] Trial 22 finished with value: 0.646551363941647 and parameters: {'hidden_layer_sizes': '256_128', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.002192251464502815, 'learning_rate': 'constant', 'learning_rate_init': 0.0010798626108662185}. Best is trial 13 with value: 0.6491402324005311.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:37:04,147] Trial 23 finished with value: 0.646959827205579 and parameters: {'hidden_layer_sizes': '256_128', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0008392259059009663, 'learning_rate': 'constant', 'learning_rate_init': 0.001139665694433226}. Best is trial 13 with value: 0.6491402324005311.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:37:06,240] Trial 24 finished with value: 0.6479648418825856 and parameters: {'hidden_layer_sizes': '256_128', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0006426507585262704, 'learning_rate': 'constant', 'learning_rate_init': 0.001229578411943165}. Best is trial 13 with value: 0.6491402324005311.
[I 2025-09-04 17:37:06,242] A new study created in memory with name: no-name-4f50abf9-0a23-478c-9316-f546aa3dc7b7
[I 2025-09-04 17:37:06,358] Trial 0 finished with value: 0.5861729756962331 and parameters: {'C': 4.520266591799973, 'epsilon': 0.17462450483609043}. Best is trial 0 with value: 0.5861729756962331.

✅ MLP con C2X-Complex_rhow_9x9_depth_in_3_4 - Mejor R2: 0.65
📋 Parámetros: {'hidden_layer_sizes': '256_128', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0014611726954603002, 'learning_rate': 'constant', 'learning_rate_init': 0.0006912854086058073}

Buscando mejores hiperparámetros para SVR con C2X-Complex_rhow_9x9_depth_in_3_4...

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:37:06,460] Trial 1 finished with value: 0.5894050639688215 and parameters: {'C': 8.755967385576064, 'epsilon': 0.0983082633233791}. Best is trial 1 with value: 0.5894050639688215.
[I 2025-09-04 17:37:06,570] Trial 2 finished with value: 0.5367639134833002 and parameters: {'C': 1.591533265100816, 'epsilon': 0.04512563518384907}. Best is trial 1 with value: 0.5894050639688215.
[I 2025-09-04 17:37:06,658] Trial 3 finished with value: 0.3716415965323865 and parameters: {'C': 0.3500598821913299, 'epsilon': 0.034303269553721705}. Best is trial 1 with value: 0.5894050639688215.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1

[I 2025-09-04 17:37:06,764] Trial 4 finished with value: 0.31849981150967754 and parameters: {'C': 0.17802810262863716, 'epsilon': 0.17163907507908155}. Best is trial 1 with value: 0.5894050639688215.
[I 2025-09-04 17:37:06,879] Trial 5 finished with value: 0.5804487130637782 and parameters: {'C': 5.4504421028266465, 'epsilon': 0.04595563487341442}. Best is trial 1 with value: 0.5894050639688215.

Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:37:06,986] Trial 6 finished with value: 0.5862744407622962 and parameters: {'C': 7.278345869140112, 'epsilon': 0.07675023861413931}. Best is trial 1 with value: 0.5894050639688215.
[I 2025-09-04 17:37:07,079] Trial 7 finished with value: 0.44132081126809997 and parameters: {'C': 0.6079717111145962, 'epsilon': 0.08098514920620277}. Best is trial 1 with value: 0.5894050639688215.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1

[I 2025-09-04 17:37:07,186] Trial 8 finished with value: 0.31547383371310966 and parameters: {'C': 0.20388472482791012, 'epsilon': 0.015417548658183589}. Best is trial 1 with value: 0.5894050639688215.
[I 2025-09-04 17:37:07,288] Trial 9 finished with value: 0.5868155439574512 and parameters: {'C': 6.231759277761834, 'epsilon': 0.13648826352649415}. Best is trial 1 with value: 0.5894050639688215.

Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1

[I 2025-09-04 17:37:07,393] Trial 10 finished with value: 0.5525836883896456 and parameters: {'C': 1.7792242996531173, 'epsilon': 0.12406495108079452}. Best is trial 1 with value: 0.5894050639688215.
[I 2025-09-04 17:37:07,501] Trial 11 finished with value: 0.5709602036114237 and parameters: {'C': 2.80152882446003, 'epsilon': 0.12900649791090113}. Best is trial 1 with value: 0.5894050639688215.

Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1

[I 2025-09-04 17:37:07,610] Trial 12 finished with value: 0.5894504117009884 and parameters: {'C': 7.06715643798922, 'epsilon': 0.1444567031562566}. Best is trial 12 with value: 0.5894504117009884.
[I 2025-09-04 17:37:07,722] Trial 13 finished with value: 0.5893233403055855 and parameters: {'C': 9.871488718359783, 'epsilon': 0.09070254280120973}. Best is trial 12 with value: 0.5894504117009884.

Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===

[I 2025-09-04 17:37:07,845] Trial 14 finished with value: 0.5762624110949505 and parameters: {'C': 3.0905340015727574, 'epsilon': 0.15424596877649951}. Best is trial 12 with value: 0.5894504117009884.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:37:07,953] Trial 15 finished with value: 0.48079952988706043 and parameters: {'C': 0.8351209867282682, 'epsilon': 0.10447751620873187}. Best is trial 12 with value: 0.5894504117009884.
[I 2025-09-04 17:37:08,068] Trial 16 finished with value: 0.5984726228326385 and parameters: {'C': 9.93157967401947, 'epsilon': 0.1963107857538181}. Best is trial 16 with value: 0.5984726228326385.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:37:08,158] Trial 17 finished with value: 0.26582332473559245 and parameters: {'C': 0.10438845222261652, 'epsilon': 0.19813193479406085}. Best is trial 16 with value: 0.5984726228326385.
[I 2025-09-04 17:37:08,271] Trial 18 finished with value: 0.5828102140161515 and parameters: {'C': 3.5093538242530586, 'epsilon': 0.19853169450750455}. Best is trial 16 with value: 0.5984726228326385.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:37:08,366] Trial 19 finished with value: 0.5587017779172155 and parameters: {'C': 1.8874155263927341, 'epsilon': 0.16682987101850055}. Best is trial 16 with value: 0.5984726228326385.
[I 2025-09-04 17:37:08,465] Trial 20 finished with value: 0.5252643790437629 and parameters: {'C': 1.122760632672896, 'epsilon': 0.14639254600491136}. Best is trial 16 with value: 0.5984726228326385.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:37:08,570] Trial 21 finished with value: 0.5909005270697723 and parameters: {'C': 8.818563359352849, 'epsilon': 0.11143384523456497}. Best is trial 16 with value: 0.5984726228326385.
[I 2025-09-04 17:37:08,677] Trial 22 finished with value: 0.5849095122866066 and parameters: {'C': 4.965472552789116, 'epsilon': 0.11967514374597116}. Best is trial 16 with value: 0.5984726228326385.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:37:08,777] Trial 23 finished with value: 0.5966596031649105 and parameters: {'C': 8.95476455604661, 'epsilon': 0.18282612126039016}. Best is trial 16 with value: 0.5984726228326385.
[I 2025-09-04 17:37:08,884] Trial 24 finished with value: 0.5976769696187413 and parameters: {'C': 9.413538900929609, 'epsilon': 0.18718577329703645}. Best is trial 16 with value: 0.5984726228326385.
[I 2025-09-04 17:37:08,885] A new study created in memory with name: no-name-675538b0-b9fe-4159-bced-b6c34c4dbabf
[I 2025-09-04 17:37:08,958] Trial 0 finished with value: 0.5220473286056371 and parameters: {'n_neighbors': 4, 'leaf_size': 22}. Best is trial 0 with value: 0.5220473286056371.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

✅ SVR con C2X-Complex_rhow_9x9_depth_in_3_4 - Mejor R2: 0.60
📋 Parámetros: {'C': 9.93157967401947, 'epsilon': 0.1963107857538181}

Buscando mejores hiperparámetros para KNN con C2X-Complex_rhow_9x9_depth_in_3_4...

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2

[I 2025-09-04 17:37:09,044] Trial 1 finished with value: 0.5220473286056371 and parameters: {'n_neighbors': 4, 'leaf_size': 12}. Best is trial 0 with value: 0.5220473286056371.
[I 2025-09-04 17:37:09,143] Trial 2 finished with value: 0.5113031117792455 and parameters: {'n_neighbors': 5, 'leaf_size': 39}. Best is trial 0 with value: 0.5220473286056371.

Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 17:37:09,221] Trial 3 finished with value: 0.5692771996038655 and parameters: {'n_neighbors': 8, 'leaf_size': 22}. Best is trial 3 with value: 0.5692771996038655.
[I 2025-09-04 17:37:09,307] Trial 4 finished with value: 0.5508572392672961 and parameters: {'n_neighbors': 7, 'leaf_size': 36}. Best is trial 3 with value: 0.5692771996038655.
[I 2025-09-04 17:37:09,384] Trial 5 finished with value: 0.5637710634125805 and parameters: {'n_neighbors': 3, 'leaf_size': 36}. Best is trial 3 with value: 0.5692771996038655.

Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2

[I 2025-09-04 17:37:09,461] Trial 6 finished with value: 0.5220473286056371 and parameters: {'n_neighbors': 4, 'leaf_size': 33}. Best is trial 3 with value: 0.5692771996038655.
[I 2025-09-04 17:37:09,545] Trial 7 finished with value: 0.5220473286056371 and parameters: {'n_neighbors': 4, 'leaf_size': 39}. Best is trial 3 with value: 0.5692771996038655.

Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:37:09,618] Trial 8 finished with value: 0.5637710634125805 and parameters: {'n_neighbors': 3, 'leaf_size': 16}. Best is trial 3 with value: 0.5692771996038655.
[I 2025-09-04 17:37:09,701] Trial 9 finished with value: 0.54224939423939 and parameters: {'n_neighbors': 6, 'leaf_size': 18}. Best is trial 3 with value: 0.5692771996038655.
[I 2025-09-04 17:37:09,781] Trial 10 finished with value: 0.5734812694483563 and parameters: {'n_neighbors': 10, 'leaf_size': 26}. Best is trial 10 with value: 0.5734812694483563.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 17:37:09,862] Trial 11 finished with value: 0.5734812694483563 and parameters: {'n_neighbors': 10, 'leaf_size': 27}. Best is trial 10 with value: 0.5734812694483563.
[I 2025-09-04 17:37:09,955] Trial 12 finished with value: 0.5734812694483563 and parameters: {'n_neighbors': 10, 'leaf_size': 28}. Best is trial 10 with value: 0.5734812694483563.

Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:37:10,036] Trial 13 finished with value: 0.5734812694483563 and parameters: {'n_neighbors': 10, 'leaf_size': 29}. Best is trial 10 with value: 0.5734812694483563.
[I 2025-09-04 17:37:10,127] Trial 14 finished with value: 0.578621834835771 and parameters: {'n_neighbors': 9, 'leaf_size': 27}. Best is trial 14 with value: 0.578621834835771.
[I 2025-09-04 17:37:10,208] Trial 15 finished with value: 0.5692771996038655 and parameters: {'n_neighbors': 8, 'leaf_size': 24}. Best is trial 14 with value: 0.578621834835771.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 17:37:10,293] Trial 16 finished with value: 0.578621834835771 and parameters: {'n_neighbors': 9, 'leaf_size': 31}. Best is trial 14 with value: 0.578621834835771.
[I 2025-09-04 17:37:10,434] Trial 17 finished with value: 0.5692771996038655 and parameters: {'n_neighbors': 8, 'leaf_size': 32}. Best is trial 14 with value: 0.578621834835771.

Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2

[I 2025-09-04 17:37:10,521] Trial 18 finished with value: 0.578621834835771 and parameters: {'n_neighbors': 9, 'leaf_size': 31}. Best is trial 14 with value: 0.578621834835771.
[I 2025-09-04 17:37:10,615] Trial 19 finished with value: 0.578621834835771 and parameters: {'n_neighbors': 9, 'leaf_size': 19}. Best is trial 14 with value: 0.578621834835771.

Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 17:37:10,699] Trial 20 finished with value: 0.5508572392672961 and parameters: {'n_neighbors': 7, 'leaf_size': 35}. Best is trial 14 with value: 0.578621834835771.
[I 2025-09-04 17:37:10,799] Trial 21 finished with value: 0.578621834835771 and parameters: {'n_neighbors': 9, 'leaf_size': 31}. Best is trial 14 with value: 0.578621834835771.
[I 2025-09-04 17:37:10,881] Trial 22 finished with value: 0.578621834835771 and parameters: {'n_neighbors': 9, 'leaf_size': 30}. Best is trial 14 with value: 0.578621834835771.

Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===

[I 2025-09-04 17:37:11,002] Trial 23 finished with value: 0.578621834835771 and parameters: {'n_neighbors': 9, 'leaf_size': 24}. Best is trial 14 with value: 0.578621834835771.
[I 2025-09-04 17:37:11,090] Trial 24 finished with value: 0.5692771996038655 and parameters: {'n_neighbors': 8, 'leaf_size': 34}. Best is trial 14 with value: 0.578621834835771.
[I 2025-09-04 17:37:11,091] A new study created in memory with name: no-name-4f25bf2f-7c61-47a8-8e72-9ae45d7edec2

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

✅ KNN con C2X-Complex_rhow_9x9_depth_in_3_4 - Mejor R2: 0.58
📋 Parámetros: {'n_neighbors': 9, 'leaf_size': 27}

Buscando mejores hiperparámetros para LR con C2X-Complex_rhow_9x9_depth_in_3_4...

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===

[I 2025-09-04 17:37:11,203] Trial 0 finished with value: 0.46576214156556695 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 0 with value: 0.46576214156556695.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 17:37:11,328] Trial 1 finished with value: 0.46576214156423223 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 0 with value: 0.46576214156556695.
[I 2025-09-04 17:37:11,435] Trial 2 finished with value: 0.5689822618997273 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 2 with value: 0.5689822618997273.

Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 17:37:11,544] Trial 3 finished with value: 0.46576214156423223 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 2 with value: 0.5689822618997273.
[I 2025-09-04 17:37:11,651] Trial 4 finished with value: 0.5692627087455089 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 4 with value: 0.5692627087455089.

Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 17:37:11,737] Trial 5 finished with value: 0.5692627087455089 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 4 with value: 0.5692627087455089.
[I 2025-09-04 17:37:11,858] Trial 6 finished with value: 0.46576214156556695 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 4 with value: 0.5692627087455089.

Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 17:37:11,963] Trial 7 finished with value: 0.46576214156423223 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 4 with value: 0.5692627087455089.
[I 2025-09-04 17:37:12,083] Trial 8 finished with value: 0.46576214156423223 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 4 with value: 0.5692627087455089.

Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 17:37:12,186] Trial 9 finished with value: 0.46576214156556695 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 4 with value: 0.5692627087455089.
[I 2025-09-04 17:37:12,286] Trial 10 finished with value: 0.5692627087455089 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 4 with value: 0.5692627087455089.

Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:37:12,388] Trial 11 finished with value: 0.5692627087455089 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 4 with value: 0.5692627087455089.
[I 2025-09-04 17:37:12,469] Trial 12 finished with value: 0.5692627087455089 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 4 with value: 0.5692627087455089.
[I 2025-09-04 17:37:12,542] Trial 13 finished with value: 0.5692627087455089 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 4 with value: 0.5692627087455089.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 17:37:12,616] Trial 14 finished with value: 0.5692627087455089 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 4 with value: 0.5692627087455089.
[I 2025-09-04 17:37:12,696] Trial 15 finished with value: 0.5692627087455089 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 4 with value: 0.5692627087455089.
[I 2025-09-04 17:37:12,769] Trial 16 finished with value: 0.5692627087455089 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 4 with value: 0.5692627087455089.

Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 17:37:12,843] Trial 17 finished with value: 0.5692627087455089 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 4 with value: 0.5692627087455089.
[I 2025-09-04 17:37:12,938] Trial 18 finished with value: 0.5692627087455089 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 4 with value: 0.5692627087455089.
[I 2025-09-04 17:37:13,013] Trial 19 finished with value: 0.5692627087455089 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 4 with value: 0.5692627087455089.

Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===

[I 2025-09-04 17:37:13,090] Trial 20 finished with value: 0.5692627087455089 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 4 with value: 0.5692627087455089.
[I 2025-09-04 17:37:13,164] Trial 21 finished with value: 0.5692627087455089 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 4 with value: 0.5692627087455089.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 17:37:13,236] Trial 22 finished with value: 0.5692627087455089 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 4 with value: 0.5692627087455089.
[I 2025-09-04 17:37:13,310] Trial 23 finished with value: 0.5692627087455089 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 4 with value: 0.5692627087455089.
[I 2025-09-04 17:37:13,381] Trial 24 finished with value: 0.5692627087455089 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 4 with value: 0.5692627087455089.
[I 2025-09-04 17:37:13,382] A new study created in memory with name: no-name-ca3f1e39-484f-480b-82c7-a3f6c414d522

Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

✅ LR con C2X-Complex_rhow_9x9_depth_in_3_4 - Mejor R2: 0.57
📋 Parámetros: {'fit_intercept': False, 'positive': True}

Buscando mejores hiperparámetros para RF con C2X-Complex_rhow_9x9_depth_in_3_4...

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:37:19,300] Trial 0 finished with value: 0.6195235969402293 and parameters: {'n_estimators': 300, 'max_depth': 10, 'min_samples_split': 9, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 0 with value: 0.6195235969402293.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:37:25,855] Trial 1 finished with value: 0.6232878874954504 and parameters: {'n_estimators': 300, 'max_depth': 13, 'min_samples_split': 6, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 1 with value: 0.6232878874954504.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:37:35,377] Trial 2 finished with value: 0.6142757061422522 and parameters: {'n_estimators': 500, 'max_depth': 13, 'min_samples_split': 4, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 1 with value: 0.6232878874954504.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:37:37,836] Trial 3 finished with value: 0.5108369902695786 and parameters: {'n_estimators': 100, 'max_depth': 6, 'min_samples_split': 4, 'min_samples_leaf': 5, 'bootstrap': False}. Best is trial 1 with value: 0.6232878874954504.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:37:43,154] Trial 4 finished with value: 0.6188935917883973 and parameters: {'n_estimators': 300, 'max_depth': 6, 'min_samples_split': 5, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 1 with value: 0.6232878874954504.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:38:01,811] Trial 5 finished with value: 0.4998280788431335 and parameters: {'n_estimators': 500, 'max_depth': 14, 'min_samples_split': 5, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 1 with value: 0.6232878874954504.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:38:09,627] Trial 6 finished with value: 0.612697384122006 and parameters: {'n_estimators': 500, 'max_depth': 5, 'min_samples_split': 5, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 1 with value: 0.6232878874954504.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:38:12,607] Trial 7 finished with value: 0.5376779378607404 and parameters: {'n_estimators': 100, 'max_depth': 12, 'min_samples_split': 4, 'min_samples_leaf': 4, 'bootstrap': False}. Best is trial 1 with value: 0.6232878874954504.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:38:18,332] Trial 8 finished with value: 0.6174057979935579 and parameters: {'n_estimators': 300, 'max_depth': 10, 'min_samples_split': 7, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 1 with value: 0.6232878874954504.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:38:20,812] Trial 9 finished with value: 0.6263928106152425 and parameters: {'n_estimators': 100, 'max_depth': 14, 'min_samples_split': 4, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 9 with value: 0.6263928106152425.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:38:24,931] Trial 10 finished with value: 0.5102234388801241 and parameters: {'n_estimators': 100, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 9 with value: 0.6263928106152425.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:38:27,071] Trial 11 finished with value: 0.625914742521896 and parameters: {'n_estimators': 100, 'max_depth': 12, 'min_samples_split': 7, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 9 with value: 0.6263928106152425.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:38:29,163] Trial 12 finished with value: 0.6215722530822212 and parameters: {'n_estimators': 100, 'max_depth': 11, 'min_samples_split': 9, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 9 with value: 0.6263928106152425.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:38:31,192] Trial 13 finished with value: 0.6229591587451155 and parameters: {'n_estimators': 100, 'max_depth': 8, 'min_samples_split': 7, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 9 with value: 0.6263928106152425.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:38:33,900] Trial 14 finished with value: 0.6297346797250716 and parameters: {'n_estimators': 100, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 14 with value: 0.6297346797250716.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:38:36,587] Trial 15 finished with value: 0.6297346797250716 and parameters: {'n_estimators': 100, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 14 with value: 0.6297346797250716.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:38:39,268] Trial 16 finished with value: 0.6297346797250716 and parameters: {'n_estimators': 100, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 14 with value: 0.6297346797250716.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:38:41,940] Trial 17 finished with value: 0.6297346797250716 and parameters: {'n_estimators': 100, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 14 with value: 0.6297346797250716.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:38:44,920] Trial 18 finished with value: 0.46813906789778226 and parameters: {'n_estimators': 100, 'max_depth': 8, 'min_samples_split': 3, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 14 with value: 0.6297346797250716.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:38:56,133] Trial 19 finished with value: 0.6217344149887924 and parameters: {'n_estimators': 500, 'max_depth': 13, 'min_samples_split': 3, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 14 with value: 0.6297346797250716.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:38:58,250] Trial 20 finished with value: 0.6203630872865433 and parameters: {'n_estimators': 100, 'max_depth': 9, 'min_samples_split': 10, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 14 with value: 0.6297346797250716.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:39:00,945] Trial 21 finished with value: 0.6297346797250716 and parameters: {'n_estimators': 100, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 14 with value: 0.6297346797250716.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:39:03,508] Trial 22 finished with value: 0.630264248812819 and parameters: {'n_estimators': 100, 'max_depth': 14, 'min_samples_split': 3, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 22 with value: 0.630264248812819.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:39:05,805] Trial 23 finished with value: 0.6238676388411746 and parameters: {'n_estimators': 100, 'max_depth': 14, 'min_samples_split': 3, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 22 with value: 0.630264248812819.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:39:08,378] Trial 24 finished with value: 0.630264248812819 and parameters: {'n_estimators': 100, 'max_depth': 14, 'min_samples_split': 3, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 22 with value: 0.630264248812819.
[I 2025-09-04 17:39:08,380] A new study created in memory with name: no-name-b36156e2-868f-48b7-8e72-75acd114dffd

✅ RF con C2X-Complex_rhow_9x9_depth_in_3_4 - Mejor R2: 0.63
📋 Parámetros: {'n_estimators': 100, 'max_depth': 14, 'min_samples_split': 3, 'min_samples_leaf': 1, 'bootstrap': True}

Buscando mejores hiperparámetros para CAT con C2X-Complex_rhow_9x9_depth_in_3_4...

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:39:26,670] Trial 0 finished with value: 0.5784015296313547 and parameters: {'iterations': 2000, 'learning_rate': 0.06922673981315879, 'depth': 6, 'l2_leaf_reg': 2.091270270441105}. Best is trial 0 with value: 0.5784015296313547.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:41:10,585] Trial 1 finished with value: 0.5672841339394898 and parameters: {'iterations': 2000, 'learning_rate': 0.01652005545469787, 'depth': 8, 'l2_leaf_reg': 2.1334989886510534}. Best is trial 0 with value: 0.5784015296313547.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:41:14,239] Trial 2 finished with value: 0.5943979838840332 and parameters: {'iterations': 1000, 'learning_rate': 0.03877190506062147, 'depth': 4, 'l2_leaf_reg': 2.6057937951908654}. Best is trial 2 with value: 0.5943979838840332.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:41:58,812] Trial 3 finished with value: 0.5864010545849434 and parameters: {'iterations': 2000, 'learning_rate': 0.019981020343278186, 'depth': 7, 'l2_leaf_reg': 1.6616967185066143}. Best is trial 2 with value: 0.5943979838840332.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:45:10,570] Trial 4 finished with value: 0.5620708919641489 and parameters: {'iterations': 1000, 'learning_rate': 0.012425324516914575, 'depth': 10, 'l2_leaf_reg': 3.219493177809915}. Best is trial 2 with value: 0.5943979838840332.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:45:28,626] Trial 5 finished with value: 0.5878939974423172 and parameters: {'iterations': 2000, 'learning_rate': 0.023495453459162603, 'depth': 6, 'l2_leaf_reg': 2.879525332413303}. Best is trial 2 with value: 0.5943979838840332.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:45:37,638] Trial 6 finished with value: 0.5926136768770602 and parameters: {'iterations': 1000, 'learning_rate': 0.012623524608126905, 'depth': 6, 'l2_leaf_reg': 4.663166777037787}. Best is trial 2 with value: 0.5943979838840332.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:46:03,819] Trial 7 finished with value: 0.5561160748490248 and parameters: {'iterations': 500, 'learning_rate': 0.04261867590625812, 'depth': 8, 'l2_leaf_reg': 2.1331507074729883}. Best is trial 2 with value: 0.5943979838840332.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:46:21,827] Trial 8 finished with value: 0.5917712633193142 and parameters: {'iterations': 2000, 'learning_rate': 0.013543516530835223, 'depth': 6, 'l2_leaf_reg': 5.466586894284451}. Best is trial 2 with value: 0.5943979838840332.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:47:06,249] Trial 9 finished with value: 0.5856982366025378 and parameters: {'iterations': 2000, 'learning_rate': 0.03375713946747452, 'depth': 7, 'l2_leaf_reg': 4.596953585299332}. Best is trial 2 with value: 0.5943979838840332.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:47:10,136] Trial 10 finished with value: 0.6000361715928009 and parameters: {'iterations': 1000, 'learning_rate': 0.05570987261821413, 'depth': 4, 'l2_leaf_reg': 4.051544216284191}. Best is trial 10 with value: 0.6000361715928009.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:47:13,936] Trial 11 finished with value: 0.6033105410292623 and parameters: {'iterations': 1000, 'learning_rate': 0.05597485225446561, 'depth': 4, 'l2_leaf_reg': 4.012327106821579}. Best is trial 11 with value: 0.6033105410292623.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:47:17,846] Trial 12 finished with value: 0.6027397615932694 and parameters: {'iterations': 1000, 'learning_rate': 0.07734113952600778, 'depth': 4, 'l2_leaf_reg': 4.033508464845512}. Best is trial 11 with value: 0.6033105410292623.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:47:21,807] Trial 13 finished with value: 0.6003363126254144 and parameters: {'iterations': 1000, 'learning_rate': 0.07193825474779285, 'depth': 4, 'l2_leaf_reg': 3.8462301176829734}. Best is trial 11 with value: 0.6033105410292623.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:47:24,619] Trial 14 finished with value: 0.5959010577363528 and parameters: {'iterations': 500, 'learning_rate': 0.052231663048612494, 'depth': 5, 'l2_leaf_reg': 5.884350121466246}. Best is trial 11 with value: 0.6033105410292623.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:47:30,390] Trial 15 finished with value: 0.6169208893678119 and parameters: {'iterations': 1000, 'learning_rate': 0.07521844621271666, 'depth': 5, 'l2_leaf_reg': 4.739858256733454}. Best is trial 15 with value: 0.6169208893678119.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:47:36,284] Trial 16 finished with value: 0.5882081112011975 and parameters: {'iterations': 1000, 'learning_rate': 0.05220264006584681, 'depth': 5, 'l2_leaf_reg': 4.79484783908174}. Best is trial 15 with value: 0.6169208893678119.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:47:42,184] Trial 17 finished with value: 0.6015340148335988 and parameters: {'iterations': 1000, 'learning_rate': 0.029436976725145315, 'depth': 5, 'l2_leaf_reg': 5.217433573589336}. Best is trial 15 with value: 0.6169208893678119.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:49:21,931] Trial 18 finished with value: 0.5747661585370656 and parameters: {'iterations': 500, 'learning_rate': 0.05978675935043996, 'depth': 10, 'l2_leaf_reg': 3.5305709988265184}. Best is trial 15 with value: 0.6169208893678119.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:49:27,646] Trial 19 finished with value: 0.5985887977852498 and parameters: {'iterations': 1000, 'learning_rate': 0.04357202837759797, 'depth': 5, 'l2_leaf_reg': 4.2957551830038065}. Best is trial 15 with value: 0.6169208893678119.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:50:19,691] Trial 20 finished with value: 0.559298736402027 and parameters: {'iterations': 1000, 'learning_rate': 0.07857486799566443, 'depth': 8, 'l2_leaf_reg': 5.263025073147311}. Best is trial 15 with value: 0.6169208893678119.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:50:23,429] Trial 21 finished with value: 0.6014652235099105 and parameters: {'iterations': 1000, 'learning_rate': 0.06476291026676995, 'depth': 4, 'l2_leaf_reg': 3.6441941915998224}. Best is trial 15 with value: 0.6169208893678119.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:50:27,254] Trial 22 finished with value: 0.607417369257892 and parameters: {'iterations': 1000, 'learning_rate': 0.07501737398969036, 'depth': 4, 'l2_leaf_reg': 4.219448146409115}. Best is trial 15 with value: 0.6169208893678119.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:50:33,279] Trial 23 finished with value: 0.5946657193866549 and parameters: {'iterations': 1000, 'learning_rate': 0.04755254556631887, 'depth': 5, 'l2_leaf_reg': 4.923125697410699}. Best is trial 15 with value: 0.6169208893678119.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:50:37,191] Trial 24 finished with value: 0.6063644577120235 and parameters: {'iterations': 1000, 'learning_rate': 0.061962586705389525, 'depth': 4, 'l2_leaf_reg': 4.3024393200885145}. Best is trial 15 with value: 0.6169208893678119.
[I 2025-09-04 17:50:37,192] A new study created in memory with name: no-name-31c1e4e4-21fc-4664-b41d-d926f4dc061c
[I 2025-09-04 17:50:37,320] Trial 0 finished with value: 0.5745651290239424 and parameters: {'alpha': 0.09178378654285942, 'l1_ratio': 0.032904026717227586}. Best is trial 0 with value: 0.5745651290239424.

✅ CAT con C2X-Complex_rhow_9x9_depth_in_3_4 - Mejor R2: 0.62
📋 Parámetros: {'iterations': 1000, 'learning_rate': 0.07521844621271666, 'depth': 5, 'l2_leaf_reg': 4.739858256733454}

Buscando mejores hiperparámetros para ELN con C2X-Complex_rhow_9x9_depth_in_3_4...

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 17:50:37,418] Trial 1 finished with value: 0.5036583939306349 and parameters: {'alpha': 0.08955804281381995, 'l1_ratio': 0.5607790548955892}. Best is trial 0 with value: 0.5745651290239424.
[I 2025-09-04 17:50:37,537] Trial 2 finished with value: 0.5377662342579311 and parameters: {'alpha': 0.35389487972306855, 'l1_ratio': 0.013995719524448114}. Best is trial 0 with value: 0.5745651290239424.

Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2

[I 2025-09-04 17:50:37,737] Trial 3 finished with value: 0.5891080815892664 and parameters: {'alpha': 0.01749270457055249, 'l1_ratio': 0.39945636698126474}. Best is trial 3 with value: 0.5891080815892664.

Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.137e+01, tolerance: 4.876e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.045e+02, tolerance: 5.544e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.152e+01, tolerance: 4.561e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.213e+01, tolerance: 4.433e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.220e+01, tolerance: 5.000e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 17:50:37,918] Trial 4 finished with value: 0.5704311007513905 and parameters: {'alpha': 0.0007732910261336334, 'l1_ratio': 0.23942051856812196}. Best is trial 3 with value: 0.5891080815892664.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.939e+01, tolerance: 4.876e-02
  model = cd_fast.enet_coordinate_descent(

Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.064e+02, tolerance: 5.544e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.415e+01, tolerance: 4.561e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.720e+01, tolerance: 4.433e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.075e+02, tolerance: 5.000e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 17:50:38,131] Trial 5 finished with value: 0.5648876802000874 and parameters: {'alpha': 0.0003740097738479818, 'l1_ratio': 0.37365020142264904}. Best is trial 3 with value: 0.5891080815892664.

Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:50:38,255] Trial 6 finished with value: 0.5063466920021531 and parameters: {'alpha': 0.05058069724879422, 'l1_ratio': 0.9547449467405886}. Best is trial 3 with value: 0.5891080815892664.
[I 2025-09-04 17:50:38,386] Trial 7 finished with value: 0.5816063326570886 and parameters: {'alpha': 0.03099640737791907, 'l1_ratio': 0.42147624382506954}. Best is trial 3 with value: 0.5891080815892664.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.587e+01, tolerance: 4.876e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.955e+01, tolerance: 5.544e-02
  model = cd_fast.enet_coordinate_descent(

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.192e+00, tolerance: 4.561e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.031e+00, tolerance: 4.433e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.892e+01, tolerance: 5.000e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 17:50:38,552] Trial 8 finished with value: 0.5807348980227479 and parameters: {'alpha': 0.002122116437807307, 'l1_ratio': 0.7075385634776449}. Best is trial 3 with value: 0.5891080815892664.

Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 17:50:38,766] Trial 9 finished with value: 0.48230892337581954 and parameters: {'alpha': 0.09827354665166173, 'l1_ratio': 0.8236685193661204}. Best is trial 3 with value: 0.5891080815892664.

Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.277e+00, tolerance: 4.876e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.928e+00, tolerance: 5.544e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.548e+00, tolerance: 4.561e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.411e+00, tolerance: 4.433e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.743e-01, tolerance: 5.000e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 17:50:39,010] Trial 10 finished with value: 0.5819374216749872 and parameters: {'alpha': 0.007839023882359013, 'l1_ratio': 0.23930562741260575}. Best is trial 3 with value: 0.5891080815892664.

Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.497e+01, tolerance: 4.876e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.530e+01, tolerance: 5.544e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.649e+01, tolerance: 4.561e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.425e+01, tolerance: 4.433e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.487e+01, tolerance: 5.000e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 17:50:39,179] Trial 11 finished with value: 0.5798856595166815 and parameters: {'alpha': 0.004905424168420159, 'l1_ratio': 0.22720950806868473}. Best is trial 3 with value: 0.5891080815892664.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.117e-01, tolerance: 4.876e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.182e+00, tolerance: 5.544e-02
  model = cd_fast.enet_coordinate_descent(

Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.392e+00, tolerance: 4.433e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.493e-01, tolerance: 5.000e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 17:50:39,360] Trial 12 finished with value: 0.5842833735002096 and parameters: {'alpha': 0.010309071741680621, 'l1_ratio': 0.22383851328885762}. Best is trial 3 with value: 0.5891080815892664.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.107e+02, tolerance: 4.876e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.157e+02, tolerance: 5.544e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.478e+01, tolerance: 4.561e-02
  model = cd_fast.enet_coordinate_descent(

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.192e+01, tolerance: 4.433e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.187e+02, tolerance: 5.000e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 17:50:39,611] Trial 13 finished with value: 0.5592807751240243 and parameters: {'alpha': 0.00010009984090368534, 'l1_ratio': 0.5524848816046564}. Best is trial 3 with value: 0.5891080815892664.
[I 2025-09-04 17:50:39,786] Trial 14 finished with value: 0.5891206970221463 and parameters: {'alpha': 0.015126276739043923, 'l1_ratio': 0.3433210919466816}. Best is trial 14 with value: 0.5891206970221463.

Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1

[I 2025-09-04 17:50:39,903] Trial 15 finished with value: 0.5885903269976628 and parameters: {'alpha': 0.020319203534586612, 'l1_ratio': 0.3795014790331188}. Best is trial 14 with value: 0.5891206970221463.
[I 2025-09-04 17:50:40,012] Trial 16 finished with value: 0.2597421182199041 and parameters: {'alpha': 0.8638930689644059, 'l1_ratio': 0.6179582911316923}. Best is trial 14 with value: 0.5891206970221463.

Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.739e+01, tolerance: 4.876e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.989e+01, tolerance: 5.544e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.842e+01, tolerance: 4.561e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.769e+01, tolerance: 4.433e-02
  model = cd_fast.enet_coordinate_descent(

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.100e+01, tolerance: 5.000e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 17:50:40,241] Trial 17 finished with value: 0.5813342417640461 and parameters: {'alpha': 0.0022479322827832432, 'l1_ratio': 0.4430577863787673}. Best is trial 14 with value: 0.5891206970221463.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.184e+00, tolerance: 4.876e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.223e-01, tolerance: 5.544e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.485e-02, tolerance: 4.561e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.203e+00, tolerance: 4.433e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 17:50:40,422] Trial 18 finished with value: 0.5866072613360065 and parameters: {'alpha': 0.016728520774168115, 'l1_ratio': 0.11544436241002132}. Best is trial 14 with value: 0.5891206970221463.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1

[I 2025-09-04 17:50:40,550] Trial 19 finished with value: 0.47685833548572 and parameters: {'alpha': 0.3311058547838027, 'l1_ratio': 0.3101132062057118}. Best is trial 14 with value: 0.5891206970221463.

Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.550e-01, tolerance: 4.876e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.684e-01, tolerance: 5.544e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.717e-01, tolerance: 4.561e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.596e-01, tolerance: 4.433e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.465e-01, tolerance: 5.000e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 17:50:40,822] Trial 20 finished with value: 0.5789433149051012 and parameters: {'alpha': 0.004085239697925043, 'l1_ratio': 0.6667529220609111}. Best is trial 14 with value: 0.5891206970221463.

Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 17:50:40,966] Trial 21 finished with value: 0.5858733913948877 and parameters: {'alpha': 0.024377649264331083, 'l1_ratio': 0.49206071930330053}. Best is trial 14 with value: 0.5891206970221463.

Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:50:41,123] Trial 22 finished with value: 0.5887610867500817 and parameters: {'alpha': 0.013431905031649389, 'l1_ratio': 0.3341007341004499}. Best is trial 14 with value: 0.5891206970221463.
[I 2025-09-04 17:50:41,273] Trial 23 finished with value: 0.5840551719472377 and parameters: {'alpha': 0.04389223590720113, 'l1_ratio': 0.13789514129338326}. Best is trial 14 with value: 0.5891206970221463.

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_9x9_depth_in_3_4 ===
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.792e-02, tolerance: 5.544e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.390e-01, tolerance: 4.433e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 17:50:41,479] Trial 24 finished with value: 0.586533276038746 and parameters: {'alpha': 0.010494183925487063, 'l1_ratio': 0.3352556026507659}. Best is trial 14 with value: 0.5891206970221463.
[I 2025-09-04 17:50:41,485] A new study created in memory with name: no-name-b561d6a1-5296-46fd-abee-0c4f6c5550a1

Fold 3
Fold 4
Fold 5

✅ ELN con C2X-Complex_rhow_9x9_depth_in_3_4 - Mejor R2: 0.59
📋 Parámetros: {'alpha': 0.015126276739043923, 'l1_ratio': 0.3433210919466816}

Buscando mejores hiperparámetros para XGB con C2X-Complex_rhow_15x15_depth_in_3_4...

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:50:51,839] Trial 0 finished with value: 0.4816890357308422 and parameters: {'n_estimators': 1000, 'learning_rate': 0.049635471930682726, 'max_depth': 8, 'min_child_weight': 4, 'subsample': 0.7327772437341267, 'colsample_bytree': 0.695081295602211}. Best is trial 0 with value: 0.4816890357308422.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:50:59,889] Trial 1 finished with value: 0.5100435443990698 and parameters: {'n_estimators': 500, 'learning_rate': 0.03031622716756528, 'max_depth': 8, 'min_child_weight': 2, 'subsample': 0.9487202671739489, 'colsample_bytree': 0.7565096595537357}. Best is trial 1 with value: 0.5100435443990698.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:51:07,294] Trial 2 finished with value: 0.45887071066576124 and parameters: {'n_estimators': 1000, 'learning_rate': 0.019162832634972198, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.839746703060898, 'colsample_bytree': 0.7578041108681163}. Best is trial 1 with value: 0.5100435443990698.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:51:16,302] Trial 3 finished with value: 0.510074049805282 and parameters: {'n_estimators': 1000, 'learning_rate': 0.008036788373083047, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.6703947480292756, 'colsample_bytree': 0.6182164587674691}. Best is trial 3 with value: 0.510074049805282.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:51:20,925] Trial 4 finished with value: 0.49588198736487743 and parameters: {'n_estimators': 500, 'learning_rate': 0.0328838987758377, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.8877004959102569, 'colsample_bytree': 0.6269812148979225}. Best is trial 3 with value: 0.510074049805282.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:51:26,773] Trial 5 finished with value: 0.48163036400926584 and parameters: {'n_estimators': 500, 'learning_rate': 0.03768140567390782, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.8245941923846395, 'colsample_bytree': 0.8948603924222716}. Best is trial 3 with value: 0.510074049805282.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:51:35,606] Trial 6 finished with value: 0.522691447680268 and parameters: {'n_estimators': 500, 'learning_rate': 0.009530077260976448, 'max_depth': 8, 'min_child_weight': 2, 'subsample': 0.7541795179753484, 'colsample_bytree': 0.8341213859857566}. Best is trial 6 with value: 0.522691447680268.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:51:43,385] Trial 7 finished with value: 0.5014878496732624 and parameters: {'n_estimators': 500, 'learning_rate': 0.016528076561717578, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.9127099423041561, 'colsample_bytree': 0.9957220740770832}. Best is trial 6 with value: 0.522691447680268.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:52:12,641] Trial 8 finished with value: 0.4981911737171104 and parameters: {'n_estimators': 2000, 'learning_rate': 0.005733839690209174, 'max_depth': 8, 'min_child_weight': 2, 'subsample': 0.96429017898009, 'colsample_bytree': 0.8726887831973642}. Best is trial 6 with value: 0.522691447680268.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:52:24,887] Trial 9 finished with value: 0.5416858789679058 and parameters: {'n_estimators': 1000, 'learning_rate': 0.017938506877197478, 'max_depth': 6, 'min_child_weight': 1, 'subsample': 0.6423885233266119, 'colsample_bytree': 0.9584809716371355}. Best is trial 9 with value: 0.5416858789679058.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:52:43,201] Trial 10 finished with value: 0.5369697856311473 and parameters: {'n_estimators': 2000, 'learning_rate': 0.011824771527487142, 'max_depth': 5, 'min_child_weight': 1, 'subsample': 0.6035267582004259, 'colsample_bytree': 0.9954455774898875}. Best is trial 9 with value: 0.5416858789679058.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:53:01,523] Trial 11 finished with value: 0.5337641192908622 and parameters: {'n_estimators': 2000, 'learning_rate': 0.011901612547920843, 'max_depth': 5, 'min_child_weight': 1, 'subsample': 0.6013959436573808, 'colsample_bytree': 0.9994818487776086}. Best is trial 9 with value: 0.5416858789679058.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:53:20,141] Trial 12 finished with value: 0.5241127894634591 and parameters: {'n_estimators': 2000, 'learning_rate': 0.02119033389144739, 'max_depth': 5, 'min_child_weight': 1, 'subsample': 0.6029081290943643, 'colsample_bytree': 0.9379059271847365}. Best is trial 9 with value: 0.5416858789679058.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:53:31,942] Trial 13 finished with value: 0.5353581971175363 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01224965100551475, 'max_depth': 6, 'min_child_weight': 1, 'subsample': 0.6688808946326197, 'colsample_bytree': 0.9345244572653671}. Best is trial 9 with value: 0.5416858789679058.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:53:47,469] Trial 14 finished with value: 0.4752987316383901 and parameters: {'n_estimators': 2000, 'learning_rate': 0.023764528352647245, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.6731131616551775, 'colsample_bytree': 0.9374419334072748}. Best is trial 9 with value: 0.5416858789679058.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:54:12,460] Trial 15 finished with value: 0.5343453418866395 and parameters: {'n_estimators': 2000, 'learning_rate': 0.011607062529099392, 'max_depth': 6, 'min_child_weight': 1, 'subsample': 0.7331350759078294, 'colsample_bytree': 0.9984577273925164}. Best is trial 9 with value: 0.5416858789679058.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:54:23,418] Trial 16 finished with value: 0.5186991077105381 and parameters: {'n_estimators': 1000, 'learning_rate': 0.006640371565327648, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.6423028267005149, 'colsample_bytree': 0.8447788145498858}. Best is trial 9 with value: 0.5416858789679058.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:54:41,839] Trial 17 finished with value: 0.5347488770142274 and parameters: {'n_estimators': 2000, 'learning_rate': 0.014773930343036597, 'max_depth': 5, 'min_child_weight': 1, 'subsample': 0.7024549192982981, 'colsample_bytree': 0.9130649924410679}. Best is trial 9 with value: 0.5416858789679058.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:54:54,520] Trial 18 finished with value: 0.5354526099755026 and parameters: {'n_estimators': 1000, 'learning_rate': 0.008839503911449519, 'max_depth': 6, 'min_child_weight': 1, 'subsample': 0.7921274349481879, 'colsample_bytree': 0.9657276566226466}. Best is trial 9 with value: 0.5416858789679058.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:55:02,117] Trial 19 finished with value: 0.48158653061566403 and parameters: {'n_estimators': 1000, 'learning_rate': 0.02478851663170965, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.6366529358496807, 'colsample_bytree': 0.7999318819943925}. Best is trial 9 with value: 0.5416858789679058.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:55:26,102] Trial 20 finished with value: 0.5310056784973303 and parameters: {'n_estimators': 2000, 'learning_rate': 0.015162955729555552, 'max_depth': 6, 'min_child_weight': 1, 'subsample': 0.783367577349676, 'colsample_bytree': 0.8820529962907823}. Best is trial 9 with value: 0.5416858789679058.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:55:39,503] Trial 21 finished with value: 0.517092851576816 and parameters: {'n_estimators': 1000, 'learning_rate': 0.008365214917530766, 'max_depth': 6, 'min_child_weight': 1, 'subsample': 0.9980206279693644, 'colsample_bytree': 0.9622905968962472}. Best is trial 9 with value: 0.5416858789679058.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:55:53,845] Trial 22 finished with value: 0.5454427765120002 and parameters: {'n_estimators': 1000, 'learning_rate': 0.010173984447291033, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.6315966790535736, 'colsample_bytree': 0.9627946277801724}. Best is trial 22 with value: 0.5454427765120002.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:56:08,382] Trial 23 finished with value: 0.5432331837405886 and parameters: {'n_estimators': 1000, 'learning_rate': 0.01125360316443564, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.6470636375223846, 'colsample_bytree': 0.9637900115305351}. Best is trial 22 with value: 0.5454427765120002.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:56:23,626] Trial 24 finished with value: 0.5475279005407248 and parameters: {'n_estimators': 1000, 'learning_rate': 0.010148550064538592, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.7092554975366574, 'colsample_bytree': 0.9589996114894445}. Best is trial 24 with value: 0.5475279005407248.
[I 2025-09-04 17:56:23,630] A new study created in memory with name: no-name-4bfbc7f3-6272-4a5c-b557-c6bc23d58810

✅ XGB con C2X-Complex_rhow_15x15_depth_in_3_4 - Mejor R2: 0.55
📋 Parámetros: {'n_estimators': 1000, 'learning_rate': 0.010148550064538592, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.7092554975366574, 'colsample_bytree': 0.9589996114894445}

Buscando mejores hiperparámetros para LBM con C2X-Complex_rhow_15x15_depth_in_3_4...

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 17:56:24,036] Trial 0 finished with value: 0.5124210613446539 and parameters: {'learning_rate': 0.006873497727816135, 'num_leaves': 40, 'max_depth': 6, 'min_child_samples': 8, 'subsample': 0.8863514625423581, 'colsample_bytree': 0.6119038406082714, 'n_estimators': 500}. Best is trial 0 with value: 0.5124210613446539.

Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:56:24,359] Trial 1 finished with value: 0.5081329461477331 and parameters: {'learning_rate': 0.007599595633912893, 'num_leaves': 60, 'max_depth': 5, 'min_child_samples': 9, 'subsample': 0.8126818127703795, 'colsample_bytree': 0.661094309161987, 'n_estimators': 500}. Best is trial 0 with value: 0.5124210613446539.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 17:56:25,169] Trial 2 finished with value: 0.4603348786683613 and parameters: {'learning_rate': 0.011004204329903984, 'num_leaves': 20, 'max_depth': 8, 'min_child_samples': 8, 'subsample': 0.6676551072506088, 'colsample_bytree': 0.7992201127882418, 'n_estimators': 1000}. Best is trial 0 with value: 0.5124210613446539.

Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:56:25,896] Trial 3 finished with value: 0.5044685844934154 and parameters: {'learning_rate': 0.006334862808800145, 'num_leaves': 40, 'max_depth': 8, 'min_child_samples': 16, 'subsample': 0.8505196110097892, 'colsample_bytree': 0.7367692392889852, 'n_estimators': 1000}. Best is trial 0 with value: 0.5124210613446539.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 17:56:26,748] Trial 4 finished with value: 0.4556084759459277 and parameters: {'learning_rate': 0.008096188784772626, 'num_leaves': 60, 'max_depth': 7, 'min_child_samples': 7, 'subsample': 0.9031154514599038, 'colsample_bytree': 0.8637283060756247, 'n_estimators': 1000}. Best is trial 0 with value: 0.5124210613446539.

Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:56:27,767] Trial 5 finished with value: 0.40976248319137165 and parameters: {'learning_rate': 0.014120404460025899, 'num_leaves': 80, 'max_depth': 5, 'min_child_samples': 14, 'subsample': 0.9174179561027518, 'colsample_bytree': 0.8822762407411351, 'n_estimators': 2000}. Best is trial 0 with value: 0.5124210613446539.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:56:28,645] Trial 6 finished with value: 0.41467010149240147 and parameters: {'learning_rate': 0.018537180626169898, 'num_leaves': 80, 'max_depth': 8, 'min_child_samples': 7, 'subsample': 0.6788683010364189, 'colsample_bytree': 0.740189026870527, 'n_estimators': 1000}. Best is trial 0 with value: 0.5124210613446539.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:56:30,105] Trial 7 finished with value: 0.4404910194777252 and parameters: {'learning_rate': 0.01768359162050869, 'num_leaves': 40, 'max_depth': 5, 'min_child_samples': 4, 'subsample': 0.810135212491943, 'colsample_bytree': 0.9202259473572405, 'n_estimators': 2000}. Best is trial 0 with value: 0.5124210613446539.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:56:31,146] Trial 8 finished with value: 0.37780914845776226 and parameters: {'learning_rate': 0.048540373306193214, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 12, 'subsample': 0.7671300313048626, 'colsample_bytree': 0.7261980387560445, 'n_estimators': 2000}. Best is trial 0 with value: 0.5124210613446539.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 17:56:31,522] Trial 9 finished with value: 0.47399247586031457 and parameters: {'learning_rate': 0.017463652118858794, 'num_leaves': 80, 'max_depth': 7, 'min_child_samples': 14, 'subsample': 0.8095305527625406, 'colsample_bytree': 0.9147241236554867, 'n_estimators': 500}. Best is trial 0 with value: 0.5124210613446539.

Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:56:32,144] Trial 10 finished with value: 0.5049371848051589 and parameters: {'learning_rate': 0.005240675786686173, 'num_leaves': 40, 'max_depth': 6, 'min_child_samples': 4, 'subsample': 0.991999279374026, 'colsample_bytree': 0.6166107009260987, 'n_estimators': 500}. Best is trial 0 with value: 0.5124210613446539.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 17:56:32,544] Trial 11 finished with value: 0.5027620841179812 and parameters: {'learning_rate': 0.008850500430921173, 'num_leaves': 60, 'max_depth': 6, 'min_child_samples': 9, 'subsample': 0.7582697078246681, 'colsample_bytree': 0.6127849535058165, 'n_estimators': 500}. Best is trial 0 with value: 0.5124210613446539.

Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 17:56:32,944] Trial 12 finished with value: 0.5533043668540816 and parameters: {'learning_rate': 0.00508799680186708, 'num_leaves': 60, 'max_depth': 6, 'min_child_samples': 11, 'subsample': 0.9123482364693078, 'colsample_bytree': 0.6703246002628885, 'n_estimators': 500}. Best is trial 12 with value: 0.5533043668540816.

Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:56:33,347] Trial 13 finished with value: 0.5523056237125545 and parameters: {'learning_rate': 0.005164565054139401, 'num_leaves': 40, 'max_depth': 6, 'min_child_samples': 11, 'subsample': 0.960607017980842, 'colsample_bytree': 0.6791218149476633, 'n_estimators': 500}. Best is trial 12 with value: 0.5533043668540816.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:56:33,839] Trial 14 finished with value: 0.5519985027395573 and parameters: {'learning_rate': 0.005047192974795064, 'num_leaves': 60, 'max_depth': 7, 'min_child_samples': 11, 'subsample': 0.9945484463281613, 'colsample_bytree': 0.9846713230870431, 'n_estimators': 500}. Best is trial 12 with value: 0.5533043668540816.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 17:56:34,180] Trial 15 finished with value: 0.45688881726627395 and parameters: {'learning_rate': 0.034864383426276326, 'num_leaves': 40, 'max_depth': 6, 'min_child_samples': 12, 'subsample': 0.9518908167287483, 'colsample_bytree': 0.687347255185504, 'n_estimators': 500}. Best is trial 12 with value: 0.5533043668540816.

Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:56:34,534] Trial 16 finished with value: 0.5154163568868315 and parameters: {'learning_rate': 0.010954019986582762, 'num_leaves': 60, 'max_depth': 6, 'min_child_samples': 13, 'subsample': 0.6084075295719975, 'colsample_bytree': 0.792016157880303, 'n_estimators': 500}. Best is trial 12 with value: 0.5533043668540816.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 17:56:34,886] Trial 17 finished with value: 0.450113816735189 and parameters: {'learning_rate': 0.02688504211329235, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 11, 'subsample': 0.9437102978558516, 'colsample_bytree': 0.6722561852048079, 'n_estimators': 500}. Best is trial 12 with value: 0.5533043668540816.

Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 17:56:35,246] Trial 18 finished with value: 0.5176042536661818 and parameters: {'learning_rate': 0.010202095659552497, 'num_leaves': 60, 'max_depth': 6, 'min_child_samples': 16, 'subsample': 0.857712478762166, 'colsample_bytree': 0.7585589059802311, 'n_estimators': 500}. Best is trial 12 with value: 0.5533043668540816.

Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:56:36,582] Trial 19 finished with value: 0.45767663061073327 and parameters: {'learning_rate': 0.0058650555564443456, 'num_leaves': 40, 'max_depth': 7, 'min_child_samples': 10, 'subsample': 0.9553298867330974, 'colsample_bytree': 0.7026195818324085, 'n_estimators': 2000}. Best is trial 12 with value: 0.5533043668540816.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 17:56:36,939] Trial 20 finished with value: 0.44404427898086596 and parameters: {'learning_rate': 0.013675589705882073, 'num_leaves': 60, 'max_depth': 5, 'min_child_samples': 6, 'subsample': 0.8659925001495616, 'colsample_bytree': 0.6426572661239729, 'n_estimators': 500}. Best is trial 12 with value: 0.5533043668540816.

Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 17:56:37,422] Trial 21 finished with value: 0.5457982456861075 and parameters: {'learning_rate': 0.005326079538102029, 'num_leaves': 60, 'max_depth': 7, 'min_child_samples': 11, 'subsample': 0.998327330318058, 'colsample_bytree': 0.9984242386971307, 'n_estimators': 500}. Best is trial 12 with value: 0.5533043668540816.

Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:56:37,847] Trial 22 finished with value: 0.5546628851173321 and parameters: {'learning_rate': 0.005034271791889273, 'num_leaves': 60, 'max_depth': 6, 'min_child_samples': 11, 'subsample': 0.9704198407257476, 'colsample_bytree': 0.8302542907662975, 'n_estimators': 500}. Best is trial 22 with value: 0.5546628851173321.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:56:38,292] Trial 23 finished with value: 0.5318083007170172 and parameters: {'learning_rate': 0.00678470466990524, 'num_leaves': 60, 'max_depth': 6, 'min_child_samples': 10, 'subsample': 0.937607433966966, 'colsample_bytree': 0.8363793962300715, 'n_estimators': 500}. Best is trial 22 with value: 0.5546628851173321.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 17:56:38,658] Trial 24 finished with value: 0.5333451306598861 and parameters: {'learning_rate': 0.008743251789421426, 'num_leaves': 60, 'max_depth': 6, 'min_child_samples': 13, 'subsample': 0.9675803141411153, 'colsample_bytree': 0.8255383019077173, 'n_estimators': 500}. Best is trial 22 with value: 0.5546628851173321.
[I 2025-09-04 17:56:38,659] A new study created in memory with name: no-name-cca9d5ba-1069-4b76-91cf-7d44abf771f5

Fold 4
Fold 5

✅ LBM con C2X-Complex_rhow_15x15_depth_in_3_4 - Mejor R2: 0.55
📋 Parámetros: {'learning_rate': 0.005034271791889273, 'num_leaves': 60, 'max_depth': 6, 'min_child_samples': 11, 'subsample': 0.9704198407257476, 'colsample_bytree': 0.8302542907662975, 'n_estimators': 500}

Buscando mejores hiperparámetros para MLP con C2X-Complex_rhow_15x15_depth_in_3_4...

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-04 17:56:41,742] Trial 0 finished with value: 0.5723315804734889 and parameters: {'hidden_layer_sizes': '128', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.001199015076699052, 'learning_rate': 'adaptive', 'learning_rate_init': 0.005550293355351682}. Best is trial 0 with value: 0.5723315804734889.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:56:45,066] Trial 1 finished with value: 0.5612338886837973 and parameters: {'hidden_layer_sizes': '256_128', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0004133866174204024, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0007582721747278037}. Best is trial 0 with value: 0.5723315804734889.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:56:46,336] Trial 2 finished with value: 0.63048324133286 and parameters: {'hidden_layer_sizes': '256', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.056076304987067574, 'learning_rate': 'constant', 'learning_rate_init': 0.0049478208899705264}. Best is trial 2 with value: 0.63048324133286.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:56:48,935] Trial 3 finished with value: 0.5919545972318103 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.009903439959419426, 'learning_rate': 'adaptive', 'learning_rate_init': 0.000149170421830242}. Best is trial 2 with value: 0.63048324133286.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:56:50,491] Trial 4 finished with value: 0.5833819797459571 and parameters: {'hidden_layer_sizes': '128', 'activation': 'relu', 'solver': 'adam', 'alpha': 7.210668070165248e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.0002814162022023181}. Best is trial 2 with value: 0.63048324133286.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:56:55,915] Trial 5 finished with value: 0.5850524982413277 and parameters: {'hidden_layer_sizes': '256_128', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.001317630277496221, 'learning_rate': 'constant', 'learning_rate_init': 0.00046040595153088967}. Best is trial 2 with value: 0.63048324133286.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-04 17:56:58,471] Trial 6 finished with value: 0.6031467672983446 and parameters: {'hidden_layer_sizes': '128', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.002019804046352283, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0019053671500850117}. Best is trial 2 with value: 0.63048324133286.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:57:01,826] Trial 7 finished with value: 0.5038703547419265 and parameters: {'hidden_layer_sizes': '256_128', 'activation': 'tanh', 'solver': 'adam', 'alpha': 1.1299220039482008e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.006829435878727531}. Best is trial 2 with value: 0.63048324133286.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:57:04,018] Trial 8 finished with value: 0.6031689774117531 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.00034552410598989454, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0006350968175036936}. Best is trial 2 with value: 0.63048324133286.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:57:05,095] Trial 9 finished with value: 0.5426573414995968 and parameters: {'hidden_layer_sizes': '128', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.00018339324431267424, 'learning_rate': 'constant', 'learning_rate_init': 0.009234593938226635}. Best is trial 2 with value: 0.63048324133286.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:57:06,216] Trial 10 finished with value: 0.555165113975586 and parameters: {'hidden_layer_sizes': '256', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.061618369681033354, 'learning_rate': 'constant', 'learning_rate_init': 0.002220124991134993}. Best is trial 2 with value: 0.63048324133286.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:57:07,738] Trial 11 finished with value: 0.6023024116899676 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.08591653643149201, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0015431547136671915}. Best is trial 2 with value: 0.63048324133286.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:57:09,091] Trial 12 finished with value: 0.6318564511381646 and parameters: {'hidden_layer_sizes': '256', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.01330443403369499, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0036050579503924614}. Best is trial 12 with value: 0.6318564511381646.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:57:10,401] Trial 13 finished with value: 0.6279103164644273 and parameters: {'hidden_layer_sizes': '256', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.013311048020324923, 'learning_rate': 'constant', 'learning_rate_init': 0.0034522367278206887}. Best is trial 12 with value: 0.6318564511381646.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:57:11,760] Trial 14 finished with value: 0.6284441777309648 and parameters: {'hidden_layer_sizes': '256', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.012263282052889289, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0034057030885118232}. Best is trial 12 with value: 0.6318564511381646.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:57:12,990] Trial 15 finished with value: 0.6274654826923477 and parameters: {'hidden_layer_sizes': '256', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.026983727149818178, 'learning_rate': 'constant', 'learning_rate_init': 0.00437570479294489}. Best is trial 12 with value: 0.6318564511381646.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:57:14,335] Trial 16 finished with value: 0.6195076035925777 and parameters: {'hidden_layer_sizes': '256', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.005087196392870676, 'learning_rate': 'constant', 'learning_rate_init': 0.0012232182567343106}. Best is trial 12 with value: 0.6318564511381646.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:57:15,695] Trial 17 finished with value: 0.6251830058517702 and parameters: {'hidden_layer_sizes': '256', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.031410970750443315, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0026601756523705103}. Best is trial 12 with value: 0.6318564511381646.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 17:57:16,893] Trial 18 finished with value: 0.6166526945785102 and parameters: {'hidden_layer_sizes': '256', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.004681777172482754, 'learning_rate': 'constant', 'learning_rate_init': 0.009602212608516044}. Best is trial 12 with value: 0.6318564511381646.

Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:57:18,053] Trial 19 finished with value: 0.6381925700554789 and parameters: {'hidden_layer_sizes': '256', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.03673448429184167, 'learning_rate': 'adaptive', 'learning_rate_init': 0.005512541724045937}. Best is trial 19 with value: 0.6381925700554789.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:57:19,699] Trial 20 finished with value: 0.5504226427780874 and parameters: {'hidden_layer_sizes': '256', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.003162552951810613, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00010473849424105227}. Best is trial 19 with value: 0.6381925700554789.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:57:20,942] Trial 21 finished with value: 0.6355063051477328 and parameters: {'hidden_layer_sizes': '256', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.04786529790918382, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0059948687125764176}. Best is trial 19 with value: 0.6381925700554789.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:57:22,144] Trial 22 finished with value: 0.6379980325717556 and parameters: {'hidden_layer_sizes': '256', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.04243193466651033, 'learning_rate': 'adaptive', 'learning_rate_init': 0.007704685241818652}. Best is trial 19 with value: 0.6381925700554789.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:57:23,481] Trial 23 finished with value: 0.6248513317573637 and parameters: {'hidden_layer_sizes': '256', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.029414723934369585, 'learning_rate': 'adaptive', 'learning_rate_init': 0.006614746121889969}. Best is trial 19 with value: 0.6381925700554789.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:57:24,634] Trial 24 finished with value: 0.6332037399490582 and parameters: {'hidden_layer_sizes': '256', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.03870416741422433, 'learning_rate': 'adaptive', 'learning_rate_init': 0.009136810171601756}. Best is trial 19 with value: 0.6381925700554789.
[I 2025-09-04 17:57:24,635] A new study created in memory with name: no-name-98578cdf-6e53-4b6d-bb64-688d90f86006
[I 2025-09-04 17:57:24,763] Trial 0 finished with value: 0.5641009677066338 and parameters: {'C': 5.902403850026271, 'epsilon': 0.12900564167846082}. Best is trial 0 with value: 0.5641009677066338.

✅ MLP con C2X-Complex_rhow_15x15_depth_in_3_4 - Mejor R2: 0.64
📋 Parámetros: {'hidden_layer_sizes': '256', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.03673448429184167, 'learning_rate': 'adaptive', 'learning_rate_init': 0.005512541724045937}

Buscando mejores hiperparámetros para SVR con C2X-Complex_rhow_15x15_depth_in_3_4...

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:57:24,850] Trial 1 finished with value: 0.45930632376387315 and parameters: {'C': 0.4966341936148059, 'epsilon': 0.17169200590852904}. Best is trial 0 with value: 0.5641009677066338.
[I 2025-09-04 17:57:24,955] Trial 2 finished with value: 0.33810871591096936 and parameters: {'C': 0.17944665954142905, 'epsilon': 0.017551107908368162}. Best is trial 0 with value: 0.5641009677066338.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:57:25,054] Trial 3 finished with value: 0.351689039189106 and parameters: {'C': 0.19556040755922835, 'epsilon': 0.13450680237997928}. Best is trial 0 with value: 0.5641009677066338.
[I 2025-09-04 17:57:25,146] Trial 4 finished with value: 0.4316268099923538 and parameters: {'C': 0.43644518774933216, 'epsilon': 0.07721838997717377}. Best is trial 0 with value: 0.5641009677066338.
[I 2025-09-04 17:57:25,246] Trial 5 finished with value: 0.568509370286445 and parameters: {'C': 2.137233771268577, 'epsilon': 0.021695780796625336}. Best is trial 5 with value: 0.568509370286445.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1

[I 2025-09-04 17:57:25,336] Trial 6 finished with value: 0.4466884216606327 and parameters: {'C': 0.44895212334341467, 'epsilon': 0.1575781072212223}. Best is trial 5 with value: 0.568509370286445.
[I 2025-09-04 17:57:25,440] Trial 7 finished with value: 0.5739735980813194 and parameters: {'C': 2.648443703314663, 'epsilon': 0.04597665201580987}. Best is trial 7 with value: 0.5739735980813194.

Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2

[I 2025-09-04 17:57:25,542] Trial 8 finished with value: 0.5843713460478633 and parameters: {'C': 3.2413369664629386, 'epsilon': 0.1982961712911414}. Best is trial 8 with value: 0.5843713460478633.
[I 2025-09-04 17:57:25,657] Trial 9 finished with value: 0.5765423098033591 and parameters: {'C': 3.248687019278858, 'epsilon': 0.11442424274936791}. Best is trial 8 with value: 0.5843713460478633.

Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1

[I 2025-09-04 17:57:25,761] Trial 10 finished with value: 0.565479513627684 and parameters: {'C': 6.805404098087927, 'epsilon': 0.19940188415373178}. Best is trial 8 with value: 0.5843713460478633.
[I 2025-09-04 17:57:25,867] Trial 11 finished with value: 0.5662508039733203 and parameters: {'C': 1.961913223607469, 'epsilon': 0.09122272877018826}. Best is trial 8 with value: 0.5843713460478633.

Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1

[I 2025-09-04 17:57:25,974] Trial 12 finished with value: 0.5824614838520605 and parameters: {'C': 4.015287832354313, 'epsilon': 0.1984241419322646}. Best is trial 8 with value: 0.5843713460478633.

Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:57:26,103] Trial 13 finished with value: 0.5445298718024576 and parameters: {'C': 9.576383764780166, 'epsilon': 0.189740050101531}. Best is trial 8 with value: 0.5843713460478633.
[I 2025-09-04 17:57:26,205] Trial 14 finished with value: 0.5396620414304869 and parameters: {'C': 1.1316270386618543, 'epsilon': 0.16829166550455354}. Best is trial 8 with value: 0.5843713460478633.
[I 2025-09-04 17:57:26,301] Trial 15 finished with value: 0.5747108467062105 and parameters: {'C': 4.447858175912541, 'epsilon': 0.15122884720780116}. Best is trial 8 with value: 0.5843713460478633.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===

[I 2025-09-04 17:57:26,400] Trial 16 finished with value: 0.5490774698898913 and parameters: {'C': 1.2973542007417096, 'epsilon': 0.18258803080108324}. Best is trial 8 with value: 0.5843713460478633.
[I 2025-09-04 17:57:26,502] Trial 17 finished with value: 0.5824611018157286 and parameters: {'C': 4.025334244405282, 'epsilon': 0.19912327721452022}. Best is trial 8 with value: 0.5843713460478633.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1

[I 2025-09-04 17:57:26,616] Trial 18 finished with value: 0.4791627611339798 and parameters: {'C': 0.7180602855507049, 'epsilon': 0.06582002618877342}. Best is trial 8 with value: 0.5843713460478633.
[I 2025-09-04 17:57:26,731] Trial 19 finished with value: 0.5323361102248885 and parameters: {'C': 9.962404754568583, 'epsilon': 0.1419758998040795}. Best is trial 8 with value: 0.5843713460478633.

Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===

[I 2025-09-04 17:57:26,834] Trial 20 finished with value: 0.553726353188645 and parameters: {'C': 1.4809571821235132, 'epsilon': 0.11709256316067168}. Best is trial 8 with value: 0.5843713460478633.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:57:26,945] Trial 21 finished with value: 0.5818864129247603 and parameters: {'C': 4.172191204678747, 'epsilon': 0.1978167366187412}. Best is trial 8 with value: 0.5843713460478633.
[I 2025-09-04 17:57:27,049] Trial 22 finished with value: 0.5813559309113101 and parameters: {'C': 3.6809257444791905, 'epsilon': 0.17710831586293077}. Best is trial 8 with value: 0.5843713460478633.
[I 2025-09-04 17:57:27,145] Trial 23 finished with value: 0.5668232484291122 and parameters: {'C': 6.05416522762685, 'epsilon': 0.16410177460714864}. Best is trial 8 with value: 0.5843713460478633.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===

[I 2025-09-04 17:57:27,268] Trial 24 finished with value: 0.5765475825372572 and parameters: {'C': 2.106541974137404, 'epsilon': 0.18470941427601545}. Best is trial 8 with value: 0.5843713460478633.
[I 2025-09-04 17:57:27,269] A new study created in memory with name: no-name-b28c6ef2-aeb3-4e90-b67b-787eb844e702
[I 2025-09-04 17:57:27,354] Trial 0 finished with value: 0.3492741073866964 and parameters: {'n_neighbors': 3, 'leaf_size': 37}. Best is trial 0 with value: 0.3492741073866964.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

✅ SVR con C2X-Complex_rhow_15x15_depth_in_3_4 - Mejor R2: 0.58
📋 Parámetros: {'C': 3.2413369664629386, 'epsilon': 0.1982961712911414}

Buscando mejores hiperparámetros para KNN con C2X-Complex_rhow_15x15_depth_in_3_4...

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===

[I 2025-09-04 17:57:27,440] Trial 1 finished with value: 0.43262192031108004 and parameters: {'n_neighbors': 6, 'leaf_size': 12}. Best is trial 1 with value: 0.43262192031108004.
[I 2025-09-04 17:57:27,522] Trial 2 finished with value: 0.4222676258772846 and parameters: {'n_neighbors': 4, 'leaf_size': 28}. Best is trial 1 with value: 0.43262192031108004.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 17:57:27,605] Trial 3 finished with value: 0.47166909153067993 and parameters: {'n_neighbors': 8, 'leaf_size': 39}. Best is trial 3 with value: 0.47166909153067993.
[I 2025-09-04 17:57:27,731] Trial 4 finished with value: 0.456554536451671 and parameters: {'n_neighbors': 7, 'leaf_size': 24}. Best is trial 3 with value: 0.47166909153067993.

Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 17:57:27,808] Trial 5 finished with value: 0.456554536451671 and parameters: {'n_neighbors': 7, 'leaf_size': 33}. Best is trial 3 with value: 0.47166909153067993.
[I 2025-09-04 17:57:27,891] Trial 6 finished with value: 0.4737259212496202 and parameters: {'n_neighbors': 9, 'leaf_size': 20}. Best is trial 6 with value: 0.4737259212496202.
[I 2025-09-04 17:57:27,968] Trial 7 finished with value: 0.3492741073866964 and parameters: {'n_neighbors': 3, 'leaf_size': 37}. Best is trial 6 with value: 0.4737259212496202.

Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1

[I 2025-09-04 17:57:28,048] Trial 8 finished with value: 0.48362634317982867 and parameters: {'n_neighbors': 10, 'leaf_size': 19}. Best is trial 8 with value: 0.48362634317982867.
[I 2025-09-04 17:57:28,130] Trial 9 finished with value: 0.3492741073866964 and parameters: {'n_neighbors': 3, 'leaf_size': 26}. Best is trial 8 with value: 0.48362634317982867.

Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 17:57:28,218] Trial 10 finished with value: 0.48362634317982867 and parameters: {'n_neighbors': 10, 'leaf_size': 13}. Best is trial 8 with value: 0.48362634317982867.
[I 2025-09-04 17:57:28,350] Trial 11 finished with value: 0.48362634317982867 and parameters: {'n_neighbors': 10, 'leaf_size': 14}. Best is trial 8 with value: 0.48362634317982867.

Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 17:57:28,433] Trial 12 finished with value: 0.48362634317982867 and parameters: {'n_neighbors': 10, 'leaf_size': 17}. Best is trial 8 with value: 0.48362634317982867.
[I 2025-09-04 17:57:28,524] Trial 13 finished with value: 0.4737259212496202 and parameters: {'n_neighbors': 9, 'leaf_size': 10}. Best is trial 8 with value: 0.48362634317982867.
[I 2025-09-04 17:57:28,604] Trial 14 finished with value: 0.4737259212496202 and parameters: {'n_neighbors': 9, 'leaf_size': 20}. Best is trial 8 with value: 0.48362634317982867.

Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1

[I 2025-09-04 17:57:28,688] Trial 15 finished with value: 0.41539296042239227 and parameters: {'n_neighbors': 5, 'leaf_size': 16}. Best is trial 8 with value: 0.48362634317982867.
[I 2025-09-04 17:57:28,779] Trial 16 finished with value: 0.48362634317982867 and parameters: {'n_neighbors': 10, 'leaf_size': 20}. Best is trial 8 with value: 0.48362634317982867.

Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 17:57:28,863] Trial 17 finished with value: 0.47166909153067993 and parameters: {'n_neighbors': 8, 'leaf_size': 17}. Best is trial 8 with value: 0.48362634317982867.
[I 2025-09-04 17:57:28,983] Trial 18 finished with value: 0.47166909153067993 and parameters: {'n_neighbors': 8, 'leaf_size': 23}. Best is trial 8 with value: 0.48362634317982867.

Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 17:57:29,069] Trial 19 finished with value: 0.43262192031108004 and parameters: {'n_neighbors': 6, 'leaf_size': 29}. Best is trial 8 with value: 0.48362634317982867.
[I 2025-09-04 17:57:29,163] Trial 20 finished with value: 0.4737259212496202 and parameters: {'n_neighbors': 9, 'leaf_size': 10}. Best is trial 8 with value: 0.48362634317982867.

Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:57:29,247] Trial 21 finished with value: 0.48362634317982867 and parameters: {'n_neighbors': 10, 'leaf_size': 14}. Best is trial 8 with value: 0.48362634317982867.
[I 2025-09-04 17:57:29,340] Trial 22 finished with value: 0.48362634317982867 and parameters: {'n_neighbors': 10, 'leaf_size': 14}. Best is trial 8 with value: 0.48362634317982867.
[I 2025-09-04 17:57:29,418] Trial 23 finished with value: 0.48362634317982867 and parameters: {'n_neighbors': 10, 'leaf_size': 15}. Best is trial 8 with value: 0.48362634317982867.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2

[I 2025-09-04 17:57:29,499] Trial 24 finished with value: 0.4737259212496202 and parameters: {'n_neighbors': 9, 'leaf_size': 19}. Best is trial 8 with value: 0.48362634317982867.
[I 2025-09-04 17:57:29,500] A new study created in memory with name: no-name-b0dea35a-9122-4ce3-b852-02fe20023876

Fold 3
Fold 4
Fold 5

✅ KNN con C2X-Complex_rhow_15x15_depth_in_3_4 - Mejor R2: 0.48
📋 Parámetros: {'n_neighbors': 10, 'leaf_size': 19}

Buscando mejores hiperparámetros para LR con C2X-Complex_rhow_15x15_depth_in_3_4...

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 17:57:29,692] Trial 0 finished with value: 0.40918912485049797 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 0 with value: 0.40918912485049797.
[I 2025-09-04 17:57:29,814] Trial 1 finished with value: 0.5366072863451329 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.5366072863451329.

Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:57:29,886] Trial 2 finished with value: 0.5366072863451329 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.5366072863451329.
[I 2025-09-04 17:57:29,986] Trial 3 finished with value: 0.40918912485049797 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 1 with value: 0.5366072863451329.
[I 2025-09-04 17:57:30,088] Trial 4 finished with value: 0.5366072863451348 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 4 with value: 0.5366072863451348.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:57:30,167] Trial 5 finished with value: 0.5366072863451348 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 4 with value: 0.5366072863451348.
[I 2025-09-04 17:57:30,245] Trial 6 finished with value: 0.5366072863451329 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 4 with value: 0.5366072863451348.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 17:57:30,321] Trial 7 finished with value: 0.5366072863451348 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 4 with value: 0.5366072863451348.
[I 2025-09-04 17:57:30,406] Trial 8 finished with value: 0.5366072863451329 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 4 with value: 0.5366072863451348.
[I 2025-09-04 17:57:30,495] Trial 9 finished with value: 0.40918912485049797 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 4 with value: 0.5366072863451348.

Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1

[I 2025-09-04 17:57:30,603] Trial 10 finished with value: 0.40918912485049797 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 4 with value: 0.5366072863451348.

Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:57:30,734] Trial 11 finished with value: 0.5366072863451348 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 4 with value: 0.5366072863451348.
[I 2025-09-04 17:57:30,817] Trial 12 finished with value: 0.5366072863451348 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 4 with value: 0.5366072863451348.
[I 2025-09-04 17:57:30,895] Trial 13 finished with value: 0.5366072863451348 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 4 with value: 0.5366072863451348.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 17:57:30,968] Trial 14 finished with value: 0.5366072863451348 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 4 with value: 0.5366072863451348.
[I 2025-09-04 17:57:31,051] Trial 15 finished with value: 0.5366072863451348 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 4 with value: 0.5366072863451348.
[I 2025-09-04 17:57:31,128] Trial 16 finished with value: 0.5366072863451348 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 4 with value: 0.5366072863451348.

Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1

[I 2025-09-04 17:57:31,206] Trial 17 finished with value: 0.5366072863451348 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 4 with value: 0.5366072863451348.
[I 2025-09-04 17:57:31,323] Trial 18 finished with value: 0.40918912485136927 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 4 with value: 0.5366072863451348.

Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1

[I 2025-09-04 17:57:31,416] Trial 19 finished with value: 0.5366072863451348 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 4 with value: 0.5366072863451348.
[I 2025-09-04 17:57:31,500] Trial 20 finished with value: 0.5366072863451348 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 4 with value: 0.5366072863451348.

Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 17:57:31,571] Trial 21 finished with value: 0.5366072863451348 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 4 with value: 0.5366072863451348.
[I 2025-09-04 17:57:31,651] Trial 22 finished with value: 0.5366072863451348 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 4 with value: 0.5366072863451348.
[I 2025-09-04 17:57:31,729] Trial 23 finished with value: 0.5366072863451348 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 4 with value: 0.5366072863451348.

Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 17:57:31,805] Trial 24 finished with value: 0.5366072863451348 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 4 with value: 0.5366072863451348.
[I 2025-09-04 17:57:31,806] A new study created in memory with name: no-name-875b4160-230a-4230-b81a-c000b47c6f9f

Fold 4
Fold 5

✅ LR con C2X-Complex_rhow_15x15_depth_in_3_4 - Mejor R2: 0.54
📋 Parámetros: {'fit_intercept': True, 'positive': True}

Buscando mejores hiperparámetros para RF con C2X-Complex_rhow_15x15_depth_in_3_4...

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:57:35,670] Trial 0 finished with value: 0.43480393904922177 and parameters: {'n_estimators': 100, 'max_depth': 13, 'min_samples_split': 4, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 0 with value: 0.43480393904922177.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:57:44,099] Trial 1 finished with value: 0.4629580927761806 and parameters: {'n_estimators': 300, 'max_depth': 15, 'min_samples_split': 10, 'min_samples_leaf': 5, 'bootstrap': False}. Best is trial 1 with value: 0.4629580927761806.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:57:51,159] Trial 2 finished with value: 0.4431816008551497 and parameters: {'n_estimators': 300, 'max_depth': 5, 'min_samples_split': 8, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 1 with value: 0.4629580927761806.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:58:01,921] Trial 3 finished with value: 0.556475463468634 and parameters: {'n_estimators': 500, 'max_depth': 14, 'min_samples_split': 6, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 3 with value: 0.556475463468634.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:58:11,489] Trial 4 finished with value: 0.45581952685458516 and parameters: {'n_estimators': 300, 'max_depth': 10, 'min_samples_split': 5, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 3 with value: 0.556475463468634.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:58:16,763] Trial 5 finished with value: 0.5659830786039111 and parameters: {'n_estimators': 300, 'max_depth': 15, 'min_samples_split': 4, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 5 with value: 0.5659830786039111.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:58:18,723] Trial 6 finished with value: 0.5632262811617322 and parameters: {'n_estimators': 100, 'max_depth': 11, 'min_samples_split': 9, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 5 with value: 0.5659830786039111.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:58:28,892] Trial 7 finished with value: 0.43759126383737035 and parameters: {'n_estimators': 300, 'max_depth': 11, 'min_samples_split': 6, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 5 with value: 0.5659830786039111.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:58:38,146] Trial 8 finished with value: 0.453529100792609 and parameters: {'n_estimators': 300, 'max_depth': 10, 'min_samples_split': 9, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 5 with value: 0.5659830786039111.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:58:51,907] Trial 9 finished with value: 0.46302035195480185 and parameters: {'n_estimators': 500, 'max_depth': 11, 'min_samples_split': 7, 'min_samples_leaf': 5, 'bootstrap': False}. Best is trial 5 with value: 0.5659830786039111.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:58:53,707] Trial 10 finished with value: 0.5699658323086563 and parameters: {'n_estimators': 100, 'max_depth': 7, 'min_samples_split': 2, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 10 with value: 0.5699658323086563.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:58:55,431] Trial 11 finished with value: 0.5675215990189291 and parameters: {'n_estimators': 100, 'max_depth': 6, 'min_samples_split': 2, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 10 with value: 0.5699658323086563.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:58:57,160] Trial 12 finished with value: 0.5675215990189291 and parameters: {'n_estimators': 100, 'max_depth': 6, 'min_samples_split': 2, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 10 with value: 0.5699658323086563.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:58:58,953] Trial 13 finished with value: 0.5699658323086563 and parameters: {'n_estimators': 100, 'max_depth': 7, 'min_samples_split': 2, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 10 with value: 0.5699658323086563.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:59:00,808] Trial 14 finished with value: 0.5723777606190397 and parameters: {'n_estimators': 100, 'max_depth': 8, 'min_samples_split': 3, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 14 with value: 0.5723777606190397.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:59:02,672] Trial 15 finished with value: 0.5723777606190397 and parameters: {'n_estimators': 100, 'max_depth': 8, 'min_samples_split': 3, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 14 with value: 0.5723777606190397.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:59:04,544] Trial 16 finished with value: 0.5723777606190397 and parameters: {'n_estimators': 100, 'max_depth': 8, 'min_samples_split': 4, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 14 with value: 0.5723777606190397.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:59:06,699] Trial 17 finished with value: 0.552668661606444 and parameters: {'n_estimators': 100, 'max_depth': 9, 'min_samples_split': 3, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 14 with value: 0.5723777606190397.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:59:15,370] Trial 18 finished with value: 0.5621139667710292 and parameters: {'n_estimators': 500, 'max_depth': 8, 'min_samples_split': 5, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 14 with value: 0.5723777606190397.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:59:17,250] Trial 19 finished with value: 0.5704941730766979 and parameters: {'n_estimators': 100, 'max_depth': 9, 'min_samples_split': 3, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 14 with value: 0.5723777606190397.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:59:19,313] Trial 20 finished with value: 0.5596850841007478 and parameters: {'n_estimators': 100, 'max_depth': 12, 'min_samples_split': 3, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 14 with value: 0.5723777606190397.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:59:21,148] Trial 21 finished with value: 0.5723777606190397 and parameters: {'n_estimators': 100, 'max_depth': 8, 'min_samples_split': 4, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 14 with value: 0.5723777606190397.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:59:23,016] Trial 22 finished with value: 0.5723777606190397 and parameters: {'n_estimators': 100, 'max_depth': 8, 'min_samples_split': 5, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 14 with value: 0.5723777606190397.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:59:25,021] Trial 23 finished with value: 0.557843546351361 and parameters: {'n_estimators': 100, 'max_depth': 9, 'min_samples_split': 3, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 14 with value: 0.5723777606190397.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 17:59:26,767] Trial 24 finished with value: 0.5656127872082121 and parameters: {'n_estimators': 100, 'max_depth': 7, 'min_samples_split': 4, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 14 with value: 0.5723777606190397.
[I 2025-09-04 17:59:26,768] A new study created in memory with name: no-name-8a3261ff-bfe6-45e5-aee3-16562886f64b

✅ RF con C2X-Complex_rhow_15x15_depth_in_3_4 - Mejor R2: 0.57
📋 Parámetros: {'n_estimators': 100, 'max_depth': 8, 'min_samples_split': 3, 'min_samples_leaf': 4, 'bootstrap': True}

Buscando mejores hiperparámetros para CAT con C2X-Complex_rhow_15x15_depth_in_3_4...

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:00:11,764] Trial 0 finished with value: 0.4977452309129946 and parameters: {'iterations': 2000, 'learning_rate': 0.042954558682197753, 'depth': 7, 'l2_leaf_reg': 1.2138345347102688}. Best is trial 0 with value: 0.4977452309129946.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:00:19,835] Trial 1 finished with value: 0.5000606666737002 and parameters: {'iterations': 2000, 'learning_rate': 0.043214472433099234, 'depth': 4, 'l2_leaf_reg': 5.873649792470832}. Best is trial 1 with value: 0.5000606666737002.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:00:31,376] Trial 2 finished with value: 0.5102781542623533 and parameters: {'iterations': 500, 'learning_rate': 0.030251503422762647, 'depth': 7, 'l2_leaf_reg': 2.1395177780919505}. Best is trial 2 with value: 0.5102781542623533.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:00:39,525] Trial 3 finished with value: 0.4990404021216934 and parameters: {'iterations': 2000, 'learning_rate': 0.07513917423525868, 'depth': 4, 'l2_leaf_reg': 3.5798950560294176}. Best is trial 2 with value: 0.5102781542623533.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:00:43,186] Trial 4 finished with value: 0.5039480928926383 and parameters: {'iterations': 1000, 'learning_rate': 0.04141169218716237, 'depth': 4, 'l2_leaf_reg': 3.2000762868959183}. Best is trial 2 with value: 0.5102781542623533.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:00:45,096] Trial 5 finished with value: 0.5207487278858738 and parameters: {'iterations': 500, 'learning_rate': 0.019059227523647117, 'depth': 4, 'l2_leaf_reg': 1.6396574060146376}. Best is trial 5 with value: 0.5207487278858738.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:00:54,631] Trial 6 finished with value: 0.5095112288274533 and parameters: {'iterations': 1000, 'learning_rate': 0.05990252757524612, 'depth': 6, 'l2_leaf_reg': 2.5948215198870512}. Best is trial 5 with value: 0.5207487278858738.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:00:56,711] Trial 7 finished with value: 0.5210966620121777 and parameters: {'iterations': 500, 'learning_rate': 0.02514328128854831, 'depth': 4, 'l2_leaf_reg': 4.657808696385624}. Best is trial 7 with value: 0.5210966620121777.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:01:08,543] Trial 8 finished with value: 0.5065802411558482 and parameters: {'iterations': 2000, 'learning_rate': 0.05106887326429899, 'depth': 5, 'l2_leaf_reg': 2.717412056504734}. Best is trial 7 with value: 0.5210966620121777.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:02:00,717] Trial 9 finished with value: 0.4982856908463895 and parameters: {'iterations': 1000, 'learning_rate': 0.06199141503036665, 'depth': 8, 'l2_leaf_reg': 5.898765871977736}. Best is trial 7 with value: 0.5210966620121777.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:03:39,140] Trial 10 finished with value: 0.5543646628172894 and parameters: {'iterations': 500, 'learning_rate': 0.010126948003726963, 'depth': 10, 'l2_leaf_reg': 4.601306130945918}. Best is trial 10 with value: 0.5543646628172894.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:05:16,712] Trial 11 finished with value: 0.5519180910388278 and parameters: {'iterations': 500, 'learning_rate': 0.01025160857755974, 'depth': 10, 'l2_leaf_reg': 4.423688443967358}. Best is trial 10 with value: 0.5543646628172894.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:06:55,804] Trial 12 finished with value: 0.5543126974195404 and parameters: {'iterations': 500, 'learning_rate': 0.010225059219314043, 'depth': 10, 'l2_leaf_reg': 4.47454092612169}. Best is trial 10 with value: 0.5543646628172894.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:08:33,919] Trial 13 finished with value: 0.5453412761720995 and parameters: {'iterations': 500, 'learning_rate': 0.010407528939445139, 'depth': 10, 'l2_leaf_reg': 4.750383283255852}. Best is trial 10 with value: 0.5543646628172894.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:09:28,268] Trial 14 finished with value: 0.5450129345723227 and parameters: {'iterations': 500, 'learning_rate': 0.015115058585580404, 'depth': 9, 'l2_leaf_reg': 4.036211368735856}. Best is trial 10 with value: 0.5543646628172894.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:10:21,231] Trial 15 finished with value: 0.5417486149038861 and parameters: {'iterations': 500, 'learning_rate': 0.014433560037812935, 'depth': 9, 'l2_leaf_reg': 5.28246327765471}. Best is trial 10 with value: 0.5543646628172894.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:11:16,210] Trial 16 finished with value: 0.549294154168194 and parameters: {'iterations': 500, 'learning_rate': 0.013332191163397004, 'depth': 9, 'l2_leaf_reg': 3.8177132535270615}. Best is trial 10 with value: 0.5543646628172894.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:12:48,525] Trial 17 finished with value: 0.5326574927162332 and parameters: {'iterations': 500, 'learning_rate': 0.017916990097701535, 'depth': 10, 'l2_leaf_reg': 5.09161958185736}. Best is trial 10 with value: 0.5543646628172894.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:13:14,011] Trial 18 finished with value: 0.5410178492657753 and parameters: {'iterations': 500, 'learning_rate': 0.01187179722719704, 'depth': 8, 'l2_leaf_reg': 4.202459285616513}. Best is trial 10 with value: 0.5543646628172894.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:14:05,086] Trial 19 finished with value: 0.5057973482974722 and parameters: {'iterations': 1000, 'learning_rate': 0.02345886885819282, 'depth': 8, 'l2_leaf_reg': 5.227889508597404}. Best is trial 10 with value: 0.5543646628172894.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:15:42,327] Trial 20 finished with value: 0.5297986952907237 and parameters: {'iterations': 500, 'learning_rate': 0.01818737337676941, 'depth': 10, 'l2_leaf_reg': 3.140358507769152}. Best is trial 10 with value: 0.5543646628172894.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:17:20,810] Trial 21 finished with value: 0.5492949795335529 and parameters: {'iterations': 500, 'learning_rate': 0.010085614412998514, 'depth': 10, 'l2_leaf_reg': 4.506425880532443}. Best is trial 10 with value: 0.5543646628172894.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:18:16,088] Trial 22 finished with value: 0.5506965337944171 and parameters: {'iterations': 500, 'learning_rate': 0.011710939161046175, 'depth': 9, 'l2_leaf_reg': 4.2486445262730665}. Best is trial 10 with value: 0.5543646628172894.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:19:51,518] Trial 23 finished with value: 0.5488715669246382 and parameters: {'iterations': 500, 'learning_rate': 0.01243007048424104, 'depth': 10, 'l2_leaf_reg': 4.9748118841290845}. Best is trial 10 with value: 0.5543646628172894.
[I 2025-09-04 18:19:51,520] A new study created in memory with name: no-name-a5c0b6ad-4e1b-40df-a56e-231fc00998c3
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.188e-02, tolerance: 4.007e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.128e-01, tolerance: 5.296e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 18:19:51,666] Trial 0 finished with value: 0.5982873024072815 and parameters: {'alpha': 0.012289771794620383, 'l1_ratio': 0.23389010055845305}. Best is trial 0 with value: 0.5982873024072815.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.652e+01, tolerance: 4.007e-02
  model = cd_fast.enet_coordinate_descent(

✅ CAT con C2X-Complex_rhow_15x15_depth_in_3_4 - Mejor R2: 0.55
📋 Parámetros: {'iterations': 500, 'learning_rate': 0.010126948003726963, 'depth': 10, 'l2_leaf_reg': 4.601306130945918}

Buscando mejores hiperparámetros para ELN con C2X-Complex_rhow_15x15_depth_in_3_4...

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.435e+01, tolerance: 5.138e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.080e+01, tolerance: 4.772e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.935e+01, tolerance: 5.296e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.105e+01, tolerance: 5.153e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 18:19:51,820] Trial 1 finished with value: 0.6034507650830057 and parameters: {'alpha': 0.0009883477442810273, 'l1_ratio': 0.2945496179136191}. Best is trial 1 with value: 0.6034507650830057.

Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 18:19:51,988] Trial 2 finished with value: 0.5990616141455991 and parameters: {'alpha': 0.00874793520905673, 'l1_ratio': 0.5859743302653988}. Best is trial 1 with value: 0.6034507650830057.
[I 2025-09-04 18:19:52,135] Trial 3 finished with value: 0.573620544666948 and parameters: {'alpha': 0.025116549011503203, 'l1_ratio': 0.7841700415667537}. Best is trial 1 with value: 0.6034507650830057.

Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.228e+01, tolerance: 4.007e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.233e+01, tolerance: 5.138e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.323e+01, tolerance: 4.772e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.700e+01, tolerance: 5.296e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.020e+02, tolerance: 5.153e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 18:19:52,327] Trial 4 finished with value: 0.5965637168196093 and parameters: {'alpha': 0.0003085503964219857, 'l1_ratio': 0.8678859519389356}. Best is trial 1 with value: 0.6034507650830057.

Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1

[I 2025-09-04 18:19:52,471] Trial 5 finished with value: 0.48162832860186644 and parameters: {'alpha': 0.08847432700931417, 'l1_ratio': 0.8945201393544345}. Best is trial 1 with value: 0.6034507650830057.

Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.451e+00, tolerance: 4.007e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.179e+00, tolerance: 5.138e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.758e+00, tolerance: 4.772e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.169e+01, tolerance: 5.296e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.591e+00, tolerance: 5.153e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 18:19:52,642] Trial 6 finished with value: 0.5988159207228171 and parameters: {'alpha': 0.0029097924531968546, 'l1_ratio': 0.6635069707712594}. Best is trial 1 with value: 0.6034507650830057.
[I 2025-09-04 18:19:52,780] Trial 7 finished with value: 0.5757857869951204 and parameters: {'alpha': 0.03066030703256913, 'l1_ratio': 0.6077573163774115}. Best is trial 1 with value: 0.6034507650830057.

Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1

[I 2025-09-04 18:19:52,915] Trial 8 finished with value: 0.48713650141113096 and parameters: {'alpha': 0.13952705327514617, 'l1_ratio': 0.6099527976460813}. Best is trial 1 with value: 0.6034507650830057.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.214e+01, tolerance: 4.007e-02
  model = cd_fast.enet_coordinate_descent(

Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.710e+01, tolerance: 5.138e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.862e+01, tolerance: 4.772e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.254e+01, tolerance: 5.296e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.497e+01, tolerance: 5.153e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 18:19:53,148] Trial 9 finished with value: 0.6051926272834426 and parameters: {'alpha': 0.0028389735409016697, 'l1_ratio': 0.07006642229633675}. Best is trial 9 with value: 0.6051926272834426.

Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 18:19:53,305] Trial 10 finished with value: 0.4928471707451423 and parameters: {'alpha': 0.5998372065286856, 'l1_ratio': 0.09556483000301708}. Best is trial 9 with value: 0.6051926272834426.

Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.165e+01, tolerance: 4.007e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.892e+01, tolerance: 5.138e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.771e+01, tolerance: 4.772e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.843e+01, tolerance: 5.296e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.561e+01, tolerance: 5.153e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 18:19:53,531] Trial 11 finished with value: 0.6027726704517289 and parameters: {'alpha': 0.0008703518202321497, 'l1_ratio': 0.33493902189865365}. Best is trial 9 with value: 0.6051926272834426.

Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.520e+01, tolerance: 4.007e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.178e+02, tolerance: 5.138e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.131e+02, tolerance: 4.772e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.100e+02, tolerance: 5.296e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.275e+02, tolerance: 5.153e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 18:19:53,724] Trial 12 finished with value: 0.6042994784459563 and parameters: {'alpha': 0.0012296059697895494, 'l1_ratio': 0.021116437642544297}. Best is trial 9 with value: 0.6051926272834426.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.837e+01, tolerance: 4.007e-02
  model = cd_fast.enet_coordinate_descent(

Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.215e+02, tolerance: 5.138e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.170e+02, tolerance: 4.772e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.101e+02, tolerance: 5.296e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.321e+02, tolerance: 5.153e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 18:19:53,907] Trial 13 finished with value: 0.5935043417342457 and parameters: {'alpha': 0.0001204268047730067, 'l1_ratio': 0.027561288785928117}. Best is trial 9 with value: 0.6051926272834426.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.206e+01, tolerance: 4.007e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.319e+01, tolerance: 5.138e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.638e+01, tolerance: 4.772e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.528e+01, tolerance: 5.296e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.262e+01, tolerance: 5.153e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 18:19:54,082] Trial 14 finished with value: 0.6057813048820827 and parameters: {'alpha': 0.0018309609046751555, 'l1_ratio': 0.14771546359029453}. Best is trial 14 with value: 0.6057813048820827.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.469e+00, tolerance: 4.007e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.103e+01, tolerance: 5.138e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.699e+00, tolerance: 4.772e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.590e+01, tolerance: 5.296e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.476e+01, tolerance: 5.153e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 18:19:54,248] Trial 15 finished with value: 0.5981579038792644 and parameters: {'alpha': 0.003541220774525586, 'l1_ratio': 0.42922140114865603}. Best is trial 14 with value: 0.6057813048820827.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.824e+01, tolerance: 4.007e-02
  model = cd_fast.enet_coordinate_descent(

Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.016e+01, tolerance: 5.138e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.261e+01, tolerance: 4.772e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.701e+01, tolerance: 5.296e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.025e+01, tolerance: 5.153e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 18:19:54,441] Trial 16 finished with value: 0.600346565415993 and parameters: {'alpha': 0.004045658935749279, 'l1_ratio': 0.16954675459648993}. Best is trial 14 with value: 0.6057813048820827.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.522e+01, tolerance: 4.007e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.265e+01, tolerance: 5.138e-02
  model = cd_fast.enet_coordinate_descent(

Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.870e+01, tolerance: 4.772e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.497e+01, tolerance: 5.296e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.005e+02, tolerance: 5.153e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 18:19:54,625] Trial 17 finished with value: 0.5982011777894172 and parameters: {'alpha': 0.0004325439188862599, 'l1_ratio': 0.4314444349896235}. Best is trial 14 with value: 0.6057813048820827.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.388e+01, tolerance: 4.007e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.153e+02, tolerance: 5.138e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.097e+02, tolerance: 4.772e-02
  model = cd_fast.enet_coordinate_descent(

Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.065e+02, tolerance: 5.296e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.285e+02, tolerance: 5.153e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 18:19:54,791] Trial 18 finished with value: 0.594590682366884 and parameters: {'alpha': 0.0002011181020388538, 'l1_ratio': 0.1590151930893834}. Best is trial 14 with value: 0.6057813048820827.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.320e+01, tolerance: 4.007e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.987e+01, tolerance: 5.138e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.648e+01, tolerance: 4.772e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.300e+01, tolerance: 5.296e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.986e+01, tolerance: 5.153e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 18:19:54,961] Trial 19 finished with value: 0.6052567340759609 and parameters: {'alpha': 0.001559687245861247, 'l1_ratio': 0.3618545570322611}. Best is trial 14 with value: 0.6057813048820827.

Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.698e+01, tolerance: 4.007e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.524e+01, tolerance: 5.138e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.054e+01, tolerance: 4.772e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.637e+01, tolerance: 5.296e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.891e+01, tolerance: 5.153e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 18:19:55,122] Trial 20 finished with value: 0.6005390309377359 and parameters: {'alpha': 0.0006218264365899341, 'l1_ratio': 0.3575372234630612}. Best is trial 14 with value: 0.6057813048820827.

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.817e+01, tolerance: 4.007e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.602e+01, tolerance: 5.138e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.083e+01, tolerance: 4.772e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.957e+01, tolerance: 5.296e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.616e+01, tolerance: 5.153e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 18:19:55,287] Trial 21 finished with value: 0.6055554748305513 and parameters: {'alpha': 0.0017248690366570103, 'l1_ratio': 0.19729650952434535}. Best is trial 14 with value: 0.6057813048820827.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.260e+01, tolerance: 4.007e-02
  model = cd_fast.enet_coordinate_descent(

Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.898e+01, tolerance: 5.138e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.633e+01, tolerance: 4.772e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.359e+01, tolerance: 5.296e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.565e+01, tolerance: 5.153e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 18:19:55,502] Trial 22 finished with value: 0.605416924157098 and parameters: {'alpha': 0.001735752103926817, 'l1_ratio': 0.23870257889268115}. Best is trial 14 with value: 0.6057813048820827.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.567e+00, tolerance: 4.007e-02
  model = cd_fast.enet_coordinate_descent(

Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.065e+00, tolerance: 5.138e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.707e+00, tolerance: 4.772e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.470e+00, tolerance: 5.296e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.406e+00, tolerance: 5.153e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 18:19:55,715] Trial 23 finished with value: 0.5970597174263259 and parameters: {'alpha': 0.007741917361973541, 'l1_ratio': 0.22114880648794483}. Best is trial 14 with value: 0.6057813048820827.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.525e+01, tolerance: 4.007e-02
  model = cd_fast.enet_coordinate_descent(

Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhow_15x15_depth_in_3_4 ===
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.849e+01, tolerance: 5.138e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.134e+01, tolerance: 4.772e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.209e+01, tolerance: 5.296e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.811e+01, tolerance: 5.153e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 18:19:55,899] Trial 24 finished with value: 0.6057815366938066 and parameters: {'alpha': 0.0020193370146030037, 'l1_ratio': 0.15201649129697314}. Best is trial 24 with value: 0.6057815366938066.
[I 2025-09-04 18:19:55,901] A new study created in memory with name: no-name-de5bd5c1-d8c5-4c02-bd0e-9c48b0bb8830

Fold 3
Fold 4
Fold 5

✅ ELN con C2X-Complex_rhow_15x15_depth_in_3_4 - Mejor R2: 0.61
📋 Parámetros: {'alpha': 0.0020193370146030037, 'l1_ratio': 0.15201649129697314}

Buscando mejores hiperparámetros para XGB con C2X-Complex_rhown_9x9_depth_in_3_4...

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:20:13,561] Trial 0 finished with value: 0.5831429462572488 and parameters: {'n_estimators': 2000, 'learning_rate': 0.007427646505185742, 'max_depth': 5, 'min_child_weight': 1, 'subsample': 0.7935322169362601, 'colsample_bytree': 0.8565275103363079}. Best is trial 0 with value: 0.5831429462572488.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:20:29,666] Trial 1 finished with value: 0.5918087021560248 and parameters: {'n_estimators': 2000, 'learning_rate': 0.03481123482226685, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.6991367543749017, 'colsample_bytree': 0.7449798104375945}. Best is trial 1 with value: 0.5918087021560248.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:20:35,160] Trial 2 finished with value: 0.5692772651499292 and parameters: {'n_estimators': 500, 'learning_rate': 0.017295478587551823, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.7451560075227336, 'colsample_bytree': 0.9511528952229344}. Best is trial 1 with value: 0.5918087021560248.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:20:43,654] Trial 3 finished with value: 0.5843175204854423 and parameters: {'n_estimators': 1000, 'learning_rate': 0.030068878296296515, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.72741570938852, 'colsample_bytree': 0.7577234895455522}. Best is trial 1 with value: 0.5918087021560248.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:21:04,217] Trial 4 finished with value: 0.5946231152489301 and parameters: {'n_estimators': 2000, 'learning_rate': 0.006688435041734992, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.6351159454818835, 'colsample_bytree': 0.7917070979050855}. Best is trial 4 with value: 0.5946231152489301.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:21:12,660] Trial 5 finished with value: 0.5883387651867849 and parameters: {'n_estimators': 500, 'learning_rate': 0.041234995724424336, 'max_depth': 8, 'min_child_weight': 1, 'subsample': 0.7007679101308142, 'colsample_bytree': 0.6584358680949581}. Best is trial 4 with value: 0.5946231152489301.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:21:26,615] Trial 6 finished with value: 0.5619720270047246 and parameters: {'n_estimators': 2000, 'learning_rate': 0.01256378459385151, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.9105773886914567, 'colsample_bytree': 0.8803284409193162}. Best is trial 4 with value: 0.5946231152489301.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:21:30,166] Trial 7 finished with value: 0.6030471520754459 and parameters: {'n_estimators': 500, 'learning_rate': 0.01141156978144288, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.6463891050677264, 'colsample_bytree': 0.6547999817956974}. Best is trial 7 with value: 0.6030471520754459.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:21:38,988] Trial 8 finished with value: 0.5774115084449212 and parameters: {'n_estimators': 1000, 'learning_rate': 0.007147532732721445, 'max_depth': 5, 'min_child_weight': 1, 'subsample': 0.9534690175950818, 'colsample_bytree': 0.6959529544025359}. Best is trial 7 with value: 0.6030471520754459.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:21:42,379] Trial 9 finished with value: 0.598109475420265 and parameters: {'n_estimators': 500, 'learning_rate': 0.006098170227629301, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.6886955003762981, 'colsample_bytree': 0.6813710341941893}. Best is trial 7 with value: 0.6030471520754459.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:21:45,846] Trial 10 finished with value: 0.5765343787912494 and parameters: {'n_estimators': 500, 'learning_rate': 0.013250784815036566, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.6049559605752539, 'colsample_bytree': 0.6146746665183835}. Best is trial 7 with value: 0.6030471520754459.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:21:49,477] Trial 11 finished with value: 0.5967416576304356 and parameters: {'n_estimators': 500, 'learning_rate': 0.011104024467356272, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.6523525877611352, 'colsample_bytree': 0.610642647627976}. Best is trial 7 with value: 0.6030471520754459.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:21:53,333] Trial 12 finished with value: 0.5862944694647988 and parameters: {'n_estimators': 500, 'learning_rate': 0.005093660619390002, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.8055610539679792, 'colsample_bytree': 0.6942665184566732}. Best is trial 7 with value: 0.6030471520754459.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:21:57,487] Trial 13 finished with value: 0.5712038004566471 and parameters: {'n_estimators': 500, 'learning_rate': 0.02022602111540562, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.8229315224142042, 'colsample_bytree': 0.6909339312105032}. Best is trial 7 with value: 0.6030471520754459.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:22:04,605] Trial 14 finished with value: 0.60585660602867 and parameters: {'n_estimators': 500, 'learning_rate': 0.009224722303881105, 'max_depth': 8, 'min_child_weight': 2, 'subsample': 0.6638297634191346, 'colsample_bytree': 0.654216691227688}. Best is trial 14 with value: 0.60585660602867.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:22:11,464] Trial 15 finished with value: 0.6177664075632431 and parameters: {'n_estimators': 500, 'learning_rate': 0.00895228834570386, 'max_depth': 8, 'min_child_weight': 2, 'subsample': 0.6023934306954514, 'colsample_bytree': 0.601623766010386}. Best is trial 15 with value: 0.6177664075632431.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:22:23,077] Trial 16 finished with value: 0.6032925621952279 and parameters: {'n_estimators': 1000, 'learning_rate': 0.009222433341498979, 'max_depth': 8, 'min_child_weight': 2, 'subsample': 0.6027204833337995, 'colsample_bytree': 0.6079324276331506}. Best is trial 15 with value: 0.6177664075632431.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:22:34,765] Trial 17 finished with value: 0.5767267175138657 and parameters: {'n_estimators': 500, 'learning_rate': 0.008683302297465816, 'max_depth': 8, 'min_child_weight': 1, 'subsample': 0.8679165873921, 'colsample_bytree': 0.7396054144691075}. Best is trial 15 with value: 0.6177664075632431.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:22:41,657] Trial 18 finished with value: 0.593254033263407 and parameters: {'n_estimators': 500, 'learning_rate': 0.021678889246210822, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.7672355080421308, 'colsample_bytree': 0.9919515853003117}. Best is trial 15 with value: 0.6177664075632431.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:22:58,106] Trial 19 finished with value: 0.5864018669116717 and parameters: {'n_estimators': 1000, 'learning_rate': 0.009629632836910403, 'max_depth': 8, 'min_child_weight': 1, 'subsample': 0.6725253995157541, 'colsample_bytree': 0.8442239814827159}. Best is trial 15 with value: 0.6177664075632431.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:23:04,380] Trial 20 finished with value: 0.5922967284386704 and parameters: {'n_estimators': 500, 'learning_rate': 0.0149369118822876, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.6010391027848251, 'colsample_bytree': 0.8050202587803272}. Best is trial 15 with value: 0.6177664075632431.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:23:15,847] Trial 21 finished with value: 0.597358132416961 and parameters: {'n_estimators': 1000, 'learning_rate': 0.009079392642031628, 'max_depth': 8, 'min_child_weight': 2, 'subsample': 0.604838744465636, 'colsample_bytree': 0.614744711411166}. Best is trial 15 with value: 0.6177664075632431.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:23:27,881] Trial 22 finished with value: 0.605103841904545 and parameters: {'n_estimators': 1000, 'learning_rate': 0.005101511864742656, 'max_depth': 8, 'min_child_weight': 2, 'subsample': 0.6458094591141956, 'colsample_bytree': 0.6026005818262424}. Best is trial 15 with value: 0.6177664075632431.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:23:40,381] Trial 23 finished with value: 0.603046394795939 and parameters: {'n_estimators': 1000, 'learning_rate': 0.0052179721574855545, 'max_depth': 8, 'min_child_weight': 2, 'subsample': 0.6534415130402791, 'colsample_bytree': 0.6312038433127485}. Best is trial 15 with value: 0.6177664075632431.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:23:51,281] Trial 24 finished with value: 0.5848752292450158 and parameters: {'n_estimators': 1000, 'learning_rate': 0.007719242846288589, 'max_depth': 8, 'min_child_weight': 3, 'subsample': 0.7221292161172437, 'colsample_bytree': 0.6515140185927104}. Best is trial 15 with value: 0.6177664075632431.
[I 2025-09-04 18:23:51,282] A new study created in memory with name: no-name-a6daa086-1c94-4f6b-9354-405877d33bb7

✅ XGB con C2X-Complex_rhown_9x9_depth_in_3_4 - Mejor R2: 0.62
📋 Parámetros: {'n_estimators': 500, 'learning_rate': 0.00895228834570386, 'max_depth': 8, 'min_child_weight': 2, 'subsample': 0.6023934306954514, 'colsample_bytree': 0.601623766010386}

Buscando mejores hiperparámetros para LBM con C2X-Complex_rhown_9x9_depth_in_3_4...

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 18:23:52,067] Trial 0 finished with value: 0.5252614872490687 and parameters: {'learning_rate': 0.010840727521540847, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 8, 'subsample': 0.9064763718385126, 'colsample_bytree': 0.9657870731568585, 'n_estimators': 1000}. Best is trial 0 with value: 0.5252614872490687.

Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:23:53,310] Trial 1 finished with value: 0.48794438961781783 and parameters: {'learning_rate': 0.008623047829342615, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 13, 'subsample': 0.8484243931267075, 'colsample_bytree': 0.7183185582281416, 'n_estimators': 2000}. Best is trial 0 with value: 0.5252614872490687.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 18:23:53,631] Trial 2 finished with value: 0.49474100235909224 and parameters: {'learning_rate': 0.044243363381628785, 'num_leaves': 80, 'max_depth': 6, 'min_child_samples': 13, 'subsample': 0.6116565954654786, 'colsample_bytree': 0.663147692986164, 'n_estimators': 500}. Best is trial 0 with value: 0.5252614872490687.

Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:23:55,219] Trial 3 finished with value: 0.4936146011529381 and parameters: {'learning_rate': 0.04374523170785921, 'num_leaves': 40, 'max_depth': 8, 'min_child_samples': 7, 'subsample': 0.7169820032342784, 'colsample_bytree': 0.7354395327296885, 'n_estimators': 2000}. Best is trial 0 with value: 0.5252614872490687.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 18:23:55,643] Trial 4 finished with value: 0.5252932194290241 and parameters: {'learning_rate': 0.014883210404070717, 'num_leaves': 20, 'max_depth': 7, 'min_child_samples': 5, 'subsample': 0.8937774248063377, 'colsample_bytree': 0.6454866560482712, 'n_estimators': 500}. Best is trial 4 with value: 0.5252932194290241.

Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:23:56,226] Trial 5 finished with value: 0.5082281855798563 and parameters: {'learning_rate': 0.015772441179242463, 'num_leaves': 80, 'max_depth': 8, 'min_child_samples': 6, 'subsample': 0.8443857160434283, 'colsample_bytree': 0.9489692498573856, 'n_estimators': 500}. Best is trial 4 with value: 0.5252932194290241.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:23:57,347] Trial 6 finished with value: 0.47912251263703287 and parameters: {'learning_rate': 0.013782088334905703, 'num_leaves': 40, 'max_depth': 6, 'min_child_samples': 14, 'subsample': 0.9199629244727856, 'colsample_bytree': 0.7475909685477777, 'n_estimators': 2000}. Best is trial 4 with value: 0.5252932194290241.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 18:23:57,705] Trial 7 finished with value: 0.5158523046488558 and parameters: {'learning_rate': 0.02658463693966363, 'num_leaves': 60, 'max_depth': 7, 'min_child_samples': 14, 'subsample': 0.7897111499750835, 'colsample_bytree': 0.6234619210836359, 'n_estimators': 500}. Best is trial 4 with value: 0.5252932194290241.

Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:23:59,012] Trial 8 finished with value: 0.5067558090931433 and parameters: {'learning_rate': 0.03893622782358635, 'num_leaves': 40, 'max_depth': 6, 'min_child_samples': 7, 'subsample': 0.853440944180901, 'colsample_bytree': 0.672568030963166, 'n_estimators': 2000}. Best is trial 4 with value: 0.5252932194290241.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 18:23:59,970] Trial 9 finished with value: 0.4943420422981589 and parameters: {'learning_rate': 0.01446474622933037, 'num_leaves': 80, 'max_depth': 7, 'min_child_samples': 5, 'subsample': 0.9801599773098388, 'colsample_bytree': 0.8183775080241384, 'n_estimators': 1000}. Best is trial 4 with value: 0.5252932194290241.

Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 18:24:00,335] Trial 10 finished with value: 0.5718159148664053 and parameters: {'learning_rate': 0.0064407069338170515, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 10, 'subsample': 0.7327249602077264, 'colsample_bytree': 0.8544872612508208, 'n_estimators': 500}. Best is trial 10 with value: 0.5718159148664053.

Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:24:00,701] Trial 11 finished with value: 0.5758550082065426 and parameters: {'learning_rate': 0.005449714082672363, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 10, 'subsample': 0.7155290816957319, 'colsample_bytree': 0.8519744785576098, 'n_estimators': 500}. Best is trial 11 with value: 0.5758550082065426.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 18:24:01,071] Trial 12 finished with value: 0.5740913469965577 and parameters: {'learning_rate': 0.005028418632564556, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 10, 'subsample': 0.7097600628740612, 'colsample_bytree': 0.861865761943307, 'n_estimators': 500}. Best is trial 11 with value: 0.5758550082065426.

Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:24:01,464] Trial 13 finished with value: 0.5712970417000547 and parameters: {'learning_rate': 0.006129042330952792, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 10, 'subsample': 0.6526807593921716, 'colsample_bytree': 0.8889901552241637, 'n_estimators': 500}. Best is trial 11 with value: 0.5758550082065426.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 18:24:01,843] Trial 14 finished with value: 0.5680937031484055 and parameters: {'learning_rate': 0.005349014810129091, 'num_leaves': 60, 'max_depth': 5, 'min_child_samples': 11, 'subsample': 0.7017278368922045, 'colsample_bytree': 0.8954772899831497, 'n_estimators': 500}. Best is trial 11 with value: 0.5758550082065426.

Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:24:02,167] Trial 15 finished with value: 0.5672910921578762 and parameters: {'learning_rate': 0.007965185631084898, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 16, 'subsample': 0.7811560016814914, 'colsample_bytree': 0.7963679533002194, 'n_estimators': 500}. Best is trial 11 with value: 0.5758550082065426.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 18:24:02,773] Trial 16 finished with value: 0.4995382131337254 and parameters: {'learning_rate': 0.02532581714897462, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 9, 'subsample': 0.6685878548957317, 'colsample_bytree': 0.9969612157046077, 'n_estimators': 1000}. Best is trial 11 with value: 0.5758550082065426.

Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 18:24:03,205] Trial 17 finished with value: 0.5742393245620041 and parameters: {'learning_rate': 0.005056656150420267, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 11, 'subsample': 0.7532313696810764, 'colsample_bytree': 0.8070330216757479, 'n_estimators': 500}. Best is trial 11 with value: 0.5758550082065426.

Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:24:03,610] Trial 18 finished with value: 0.5588916311447614 and parameters: {'learning_rate': 0.008542707187669935, 'num_leaves': 60, 'max_depth': 6, 'min_child_samples': 12, 'subsample': 0.7569523812181869, 'colsample_bytree': 0.8040007042976421, 'n_estimators': 500}. Best is trial 11 with value: 0.5758550082065426.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 18:24:04,220] Trial 19 finished with value: 0.5260030708123162 and parameters: {'learning_rate': 0.010842920163229955, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 16, 'subsample': 0.6000731363686335, 'colsample_bytree': 0.7681110822885788, 'n_estimators': 1000}. Best is trial 11 with value: 0.5758550082065426.

Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 18:24:04,624] Trial 20 finished with value: 0.5627272278035571 and parameters: {'learning_rate': 0.006727772332774639, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 12, 'subsample': 0.6719541167397854, 'colsample_bytree': 0.9231745951858107, 'n_estimators': 500}. Best is trial 11 with value: 0.5758550082065426.

Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:24:05,050] Trial 21 finished with value: 0.5614811925351595 and parameters: {'learning_rate': 0.005204405632607025, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 9, 'subsample': 0.7497247692758849, 'colsample_bytree': 0.8486478749090735, 'n_estimators': 500}. Best is trial 11 with value: 0.5758550082065426.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 18:24:05,422] Trial 22 finished with value: 0.5700553251675762 and parameters: {'learning_rate': 0.005094249895188813, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 11, 'subsample': 0.7033053485068829, 'colsample_bytree': 0.8510589775071311, 'n_estimators': 500}. Best is trial 11 with value: 0.5758550082065426.

Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 18:24:05,806] Trial 23 finished with value: 0.5655094270559371 and parameters: {'learning_rate': 0.007030532060532349, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 9, 'subsample': 0.7962819733803074, 'colsample_bytree': 0.8863648536684162, 'n_estimators': 500}. Best is trial 11 with value: 0.5758550082065426.

Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2

[I 2025-09-04 18:24:06,185] Trial 24 finished with value: 0.547207987982992 and parameters: {'learning_rate': 0.010735907841934114, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 11, 'subsample': 0.6462888360855394, 'colsample_bytree': 0.7852619933888827, 'n_estimators': 500}. Best is trial 11 with value: 0.5758550082065426.
[I 2025-09-04 18:24:06,187] A new study created in memory with name: no-name-bd42fd66-a1cb-4757-8633-d5992cdf5360

Fold 3
Fold 4
Fold 5

✅ LBM con C2X-Complex_rhown_9x9_depth_in_3_4 - Mejor R2: 0.58
📋 Parámetros: {'learning_rate': 0.005449714082672363, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 10, 'subsample': 0.7155290816957319, 'colsample_bytree': 0.8519744785576098, 'n_estimators': 500}

Buscando mejores hiperparámetros para MLP con C2X-Complex_rhown_9x9_depth_in_3_4...

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

[I 2025-09-04 18:24:08,158] Trial 0 finished with value: 0.591295924312318 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.05535816227805016, 'learning_rate': 'constant', 'learning_rate_init': 0.005630187306780679}. Best is trial 0 with value: 0.591295924312318.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:24:11,519] Trial 1 finished with value: 0.4983711621308524 and parameters: {'hidden_layer_sizes': '256_128', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.00012270616772651753, 'learning_rate': 'constant', 'learning_rate_init': 0.00012060370098710884}. Best is trial 0 with value: 0.591295924312318.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:24:12,795] Trial 2 finished with value: 0.6115032432551037 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0755786571932461, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0021696949019551575}. Best is trial 2 with value: 0.6115032432551037.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:24:14,854] Trial 3 finished with value: 0.4977294223546479 and parameters: {'hidden_layer_sizes': '256', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.050230127102480635, 'learning_rate': 'constant', 'learning_rate_init': 0.00014288107333132425}. Best is trial 2 with value: 0.6115032432551037.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:24:17,714] Trial 4 finished with value: 0.6141137137519983 and parameters: {'hidden_layer_sizes': '256_128', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.004634033393259053, 'learning_rate': 'constant', 'learning_rate_init': 0.00013064346290255532}. Best is trial 4 with value: 0.6141137137519983.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:24:19,877] Trial 5 finished with value: 0.5367891766991868 and parameters: {'hidden_layer_sizes': '128', 'activation': 'tanh', 'solver': 'adam', 'alpha': 1.8260781838231497e-05, 'learning_rate': 'adaptive', 'learning_rate_init': 0.00032578699330590763}. Best is trial 4 with value: 0.6141137137519983.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:24:21,189] Trial 6 finished with value: 0.5800501096360653 and parameters: {'hidden_layer_sizes': '256', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.02012525477186625, 'learning_rate': 'constant', 'learning_rate_init': 0.00042715669035273}. Best is trial 4 with value: 0.6141137137519983.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:24:23,039] Trial 7 finished with value: 0.6265871624562197 and parameters: {'hidden_layer_sizes': '256_128', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0027533127091836267, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0016464842846823679}. Best is trial 7 with value: 0.6265871624562197.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

[I 2025-09-04 18:24:26,132] Trial 8 finished with value: 0.5740672623508498 and parameters: {'hidden_layer_sizes': '128_64', 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.000995036455388553, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0001596182341159868}. Best is trial 7 with value: 0.6265871624562197.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 5

[I 2025-09-04 18:24:31,986] Trial 9 finished with value: 0.6023725261392308 and parameters: {'hidden_layer_sizes': '256_128', 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.0005727312496559981, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0005799232815151813}. Best is trial 7 with value: 0.6265871624562197.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 18:24:33,052] Trial 10 finished with value: 0.5720457708146376 and parameters: {'hidden_layer_sizes': '128', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.006363852052343215, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0020632543152095933}. Best is trial 7 with value: 0.6265871624562197.

Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:24:34,749] Trial 11 finished with value: 0.6378071861493709 and parameters: {'hidden_layer_sizes': '256_128', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.00870051916819009, 'learning_rate': 'constant', 'learning_rate_init': 0.0017133375571583465}. Best is trial 11 with value: 0.6378071861493709.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:24:36,441] Trial 12 finished with value: 0.6313558096274094 and parameters: {'hidden_layer_sizes': '256_128', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.005680633096423622, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0016598764429785501}. Best is trial 11 with value: 0.6378071861493709.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:24:38,291] Trial 13 finished with value: 0.6199239655151586 and parameters: {'hidden_layer_sizes': '256_128', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.013215305686735698, 'learning_rate': 'constant', 'learning_rate_init': 0.005130845051047454}. Best is trial 11 with value: 0.6378071861493709.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:24:40,146] Trial 14 finished with value: 0.6346375936609931 and parameters: {'hidden_layer_sizes': '256_128', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0003799770423654918, 'learning_rate': 'constant', 'learning_rate_init': 0.0010923624468436156}. Best is trial 11 with value: 0.6378071861493709.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:24:42,357] Trial 15 finished with value: 0.6382441703324324 and parameters: {'hidden_layer_sizes': '256_128', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0001694374065729583, 'learning_rate': 'constant', 'learning_rate_init': 0.0008448681961203806}. Best is trial 15 with value: 0.6382441703324324.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:24:44,412] Trial 16 finished with value: 0.6193669928357302 and parameters: {'hidden_layer_sizes': '256_128', 'activation': 'relu', 'solver': 'adam', 'alpha': 8.36066945722017e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.003783053243406058}. Best is trial 15 with value: 0.6382441703324324.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 18:24:45,625] Trial 17 finished with value: 0.5964654808781595 and parameters: {'hidden_layer_sizes': '256', 'activation': 'relu', 'solver': 'adam', 'alpha': 1.0788708966504216e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.0008041791915167718}. Best is trial 15 with value: 0.6382441703324324.

Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2025-09-04 18:24:47,031] Trial 18 finished with value: 0.5766100732428581 and parameters: {'hidden_layer_sizes': '128', 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.00017757003740379498, 'learning_rate': 'constant', 'learning_rate_init': 0.008878545433709433}. Best is trial 15 with value: 0.6382441703324324.

Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:24:49,547] Trial 19 finished with value: 0.636943912408056 and parameters: {'hidden_layer_sizes': '256_128', 'activation': 'relu', 'solver': 'adam', 'alpha': 5.6023607156793194e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.00027217777370014396}. Best is trial 15 with value: 0.6382441703324324.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:24:51,498] Trial 20 finished with value: 0.6306202842311832 and parameters: {'hidden_layer_sizes': '256_128', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0011979960865748313, 'learning_rate': 'constant', 'learning_rate_init': 0.0011844640317543477}. Best is trial 15 with value: 0.6382441703324324.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:24:54,007] Trial 21 finished with value: 0.6276992039138652 and parameters: {'hidden_layer_sizes': '256_128', 'activation': 'relu', 'solver': 'adam', 'alpha': 4.974515160771931e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.000225348254539755}. Best is trial 15 with value: 0.6382441703324324.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:24:56,199] Trial 22 finished with value: 0.6330776717577293 and parameters: {'hidden_layer_sizes': '256_128', 'activation': 'relu', 'solver': 'adam', 'alpha': 6.42524291979786e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.000670332840363345}. Best is trial 15 with value: 0.6382441703324324.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:24:58,855] Trial 23 finished with value: 0.6363423002549164 and parameters: {'hidden_layer_sizes': '256_128', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.00019418184807923016, 'learning_rate': 'constant', 'learning_rate_init': 0.0002963813224196604}. Best is trial 15 with value: 0.6382441703324324.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:25:00,924] Trial 24 finished with value: 0.6344952124321321 and parameters: {'hidden_layer_sizes': '256_128', 'activation': 'relu', 'solver': 'adam', 'alpha': 2.5033468127528294e-05, 'learning_rate': 'constant', 'learning_rate_init': 0.000470250506179668}. Best is trial 15 with value: 0.6382441703324324.
[I 2025-09-04 18:25:00,926] A new study created in memory with name: no-name-e3e55050-af05-4834-83c6-3fc517a2c955
[I 2025-09-04 18:25:01,039] Trial 0 finished with value: 0.5488255438831596 and parameters: {'C': 2.453608321615449, 'epsilon': 0.1959736824403497}. Best is trial 0 with value: 0.5488255438831596.
[I 2025-09-04 18:25:01,126] Trial 1 finished with value: 0.5019752326063369 and parameters: {'C': 1.1624862086963221, 'epsilon': 0.16824159001822367}. Best is trial 0 with value: 0.5488255438831596.

✅ MLP con C2X-Complex_rhown_9x9_depth_in_3_4 - Mejor R2: 0.64
📋 Parámetros: {'hidden_layer_sizes': '256_128', 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0001694374065729583, 'learning_rate': 'constant', 'learning_rate_init': 0.0008448681961203806}

Buscando mejores hiperparámetros para SVR con C2X-Complex_rhown_9x9_depth_in_3_4...

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:25:01,224] Trial 2 finished with value: 0.5775894551763647 and parameters: {'C': 6.217847374194713, 'epsilon': 0.1745274949725434}. Best is trial 2 with value: 0.5775894551763647.
[I 2025-09-04 18:25:01,325] Trial 3 finished with value: 0.549465622020458 and parameters: {'C': 3.453250464812779, 'epsilon': 0.0754673217028787}. Best is trial 2 with value: 0.5775894551763647.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1

[I 2025-09-04 18:25:01,424] Trial 4 finished with value: 0.5735795348953614 and parameters: {'C': 7.647513917595338, 'epsilon': 0.11397562147093059}. Best is trial 2 with value: 0.5775894551763647.
[I 2025-09-04 18:25:01,529] Trial 5 finished with value: 0.33937173546320376 and parameters: {'C': 0.20316334728355648, 'epsilon': 0.1525902594133355}. Best is trial 2 with value: 0.5775894551763647.

Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1

[I 2025-09-04 18:25:01,633] Trial 6 finished with value: 0.4960281196218621 and parameters: {'C': 1.277294889694179, 'epsilon': 0.07229147947520621}. Best is trial 2 with value: 0.5775894551763647.
[I 2025-09-04 18:25:01,728] Trial 7 finished with value: 0.2636663049394157 and parameters: {'C': 0.11957173866421324, 'epsilon': 0.04290778245666154}. Best is trial 2 with value: 0.5775894551763647.

Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2

[I 2025-09-04 18:25:01,834] Trial 8 finished with value: 0.568138082887246 and parameters: {'C': 6.261271508653781, 'epsilon': 0.08179098676572913}. Best is trial 2 with value: 0.5775894551763647.
[I 2025-09-04 18:25:01,936] Trial 9 finished with value: 0.5525456961769386 and parameters: {'C': 3.327886118677795, 'epsilon': 0.11208445833437568}. Best is trial 2 with value: 0.5775894551763647.

Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1

[I 2025-09-04 18:25:02,059] Trial 10 finished with value: 0.38046422505473443 and parameters: {'C': 0.36618792752604074, 'epsilon': 0.01232882496702499}. Best is trial 2 with value: 0.5775894551763647.
[I 2025-09-04 18:25:02,172] Trial 11 finished with value: 0.5772459452693874 and parameters: {'C': 9.383811184295066, 'epsilon': 0.1312194293554093}. Best is trial 2 with value: 0.5775894551763647.

Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===

[I 2025-09-04 18:25:02,281] Trial 12 finished with value: 0.5790360122066913 and parameters: {'C': 9.166864530451031, 'epsilon': 0.14468654362038116}. Best is trial 12 with value: 0.5790360122066913.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:25:02,383] Trial 13 finished with value: 0.4404746237510606 and parameters: {'C': 0.5401676486071049, 'epsilon': 0.18486089881699155}. Best is trial 12 with value: 0.5790360122066913.
[I 2025-09-04 18:25:02,507] Trial 14 finished with value: 0.5688398800349792 and parameters: {'C': 4.977175709007859, 'epsilon': 0.14622964397742763}. Best is trial 12 with value: 0.5790360122066913.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:25:02,604] Trial 15 finished with value: 0.5412929708980245 and parameters: {'C': 2.224144866456615, 'epsilon': 0.16895253559222143}. Best is trial 12 with value: 0.5790360122066913.
[I 2025-09-04 18:25:02,720] Trial 16 finished with value: 0.5795709938458693 and parameters: {'C': 9.359490910754335, 'epsilon': 0.14616454887647962}. Best is trial 16 with value: 0.5795709938458693.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 18:25:02,831] Trial 17 finished with value: 0.5790177424623197 and parameters: {'C': 9.923326740301917, 'epsilon': 0.14038682076129852}. Best is trial 16 with value: 0.5795709938458693.
[I 2025-09-04 18:25:02,948] Trial 18 finished with value: 0.5195460818409582 and parameters: {'C': 1.8073798838084116, 'epsilon': 0.09757018552920056}. Best is trial 16 with value: 0.5795709938458693.

Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 18:25:03,041] Trial 19 finished with value: 0.4506922363937451 and parameters: {'C': 0.6685897867022504, 'epsilon': 0.12925143276844522}. Best is trial 16 with value: 0.5795709938458693.
[I 2025-09-04 18:25:03,168] Trial 20 finished with value: 0.5616181535949865 and parameters: {'C': 3.8883913490317727, 'epsilon': 0.1564931549970369}. Best is trial 16 with value: 0.5795709938458693.

Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 18:25:03,277] Trial 21 finished with value: 0.5770853813041199 and parameters: {'C': 8.89437340224216, 'epsilon': 0.13397220436674281}. Best is trial 16 with value: 0.5795709938458693.
[I 2025-09-04 18:25:03,390] Trial 22 finished with value: 0.5782604118514512 and parameters: {'C': 9.703482574997137, 'epsilon': 0.1373653673179036}. Best is trial 16 with value: 0.5795709938458693.

Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 18:25:03,495] Trial 23 finished with value: 0.5664526256428115 and parameters: {'C': 4.874613466242629, 'epsilon': 0.12057132425454904}. Best is trial 16 with value: 0.5795709938458693.
[I 2025-09-04 18:25:03,608] Trial 24 finished with value: 0.5704110239351643 and parameters: {'C': 6.402354496521886, 'epsilon': 0.10299065007935114}. Best is trial 16 with value: 0.5795709938458693.
[I 2025-09-04 18:25:03,609] A new study created in memory with name: no-name-975caeb5-0434-4928-a347-9ef65a4d165f

Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

✅ SVR con C2X-Complex_rhown_9x9_depth_in_3_4 - Mejor R2: 0.58
📋 Parámetros: {'C': 9.359490910754335, 'epsilon': 0.14616454887647962}

Buscando mejores hiperparámetros para KNN con C2X-Complex_rhown_9x9_depth_in_3_4...

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2

[I 2025-09-04 18:25:03,702] Trial 0 finished with value: 0.5154278502148748 and parameters: {'n_neighbors': 9, 'leaf_size': 35}. Best is trial 0 with value: 0.5154278502148748.
[I 2025-09-04 18:25:03,782] Trial 1 finished with value: 0.4925308765718184 and parameters: {'n_neighbors': 4, 'leaf_size': 25}. Best is trial 0 with value: 0.5154278502148748.
[I 2025-09-04 18:25:03,858] Trial 2 finished with value: 0.5154278502148748 and parameters: {'n_neighbors': 9, 'leaf_size': 14}. Best is trial 0 with value: 0.5154278502148748.

Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===

[I 2025-09-04 18:25:03,939] Trial 3 finished with value: 0.5242497144690823 and parameters: {'n_neighbors': 6, 'leaf_size': 29}. Best is trial 3 with value: 0.5242497144690823.
[I 2025-09-04 18:25:04,023] Trial 4 finished with value: 0.5238311860719342 and parameters: {'n_neighbors': 8, 'leaf_size': 36}. Best is trial 3 with value: 0.5242497144690823.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 18:25:04,097] Trial 5 finished with value: 0.5205597752658 and parameters: {'n_neighbors': 10, 'leaf_size': 21}. Best is trial 3 with value: 0.5242497144690823.
[I 2025-09-04 18:25:04,225] Trial 6 finished with value: 0.5205597752658 and parameters: {'n_neighbors': 10, 'leaf_size': 14}. Best is trial 3 with value: 0.5242497144690823.

Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 18:25:04,306] Trial 7 finished with value: 0.5205597752658 and parameters: {'n_neighbors': 10, 'leaf_size': 21}. Best is trial 3 with value: 0.5242497144690823.
[I 2025-09-04 18:25:04,391] Trial 8 finished with value: 0.5253791674501731 and parameters: {'n_neighbors': 7, 'leaf_size': 25}. Best is trial 8 with value: 0.5253791674501731.
[I 2025-09-04 18:25:04,468] Trial 9 finished with value: 0.5253791674501731 and parameters: {'n_neighbors': 7, 'leaf_size': 28}. Best is trial 8 with value: 0.5253791674501731.

Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1

[I 2025-09-04 18:25:04,558] Trial 10 finished with value: 0.5416279208622312 and parameters: {'n_neighbors': 5, 'leaf_size': 19}. Best is trial 10 with value: 0.5416279208622312.
[I 2025-09-04 18:25:04,642] Trial 11 finished with value: 0.5416279208622312 and parameters: {'n_neighbors': 5, 'leaf_size': 20}. Best is trial 10 with value: 0.5416279208622312.

Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 18:25:04,729] Trial 12 finished with value: 0.4925308765718184 and parameters: {'n_neighbors': 4, 'leaf_size': 10}. Best is trial 10 with value: 0.5416279208622312.
[I 2025-09-04 18:25:04,865] Trial 13 finished with value: 0.5416279208622312 and parameters: {'n_neighbors': 5, 'leaf_size': 18}. Best is trial 10 with value: 0.5416279208622312.

Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2

[I 2025-09-04 18:25:04,948] Trial 14 finished with value: 0.47866491332286376 and parameters: {'n_neighbors': 3, 'leaf_size': 18}. Best is trial 10 with value: 0.5416279208622312.
[I 2025-09-04 18:25:05,044] Trial 15 finished with value: 0.5416279208622312 and parameters: {'n_neighbors': 5, 'leaf_size': 31}. Best is trial 10 with value: 0.5416279208622312.

Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 18:25:05,129] Trial 16 finished with value: 0.5242497144690823 and parameters: {'n_neighbors': 6, 'leaf_size': 21}. Best is trial 10 with value: 0.5416279208622312.
[I 2025-09-04 18:25:05,218] Trial 17 finished with value: 0.47866491332286376 and parameters: {'n_neighbors': 3, 'leaf_size': 16}. Best is trial 10 with value: 0.5416279208622312.

Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 18:25:05,337] Trial 18 finished with value: 0.5416279208622312 and parameters: {'n_neighbors': 5, 'leaf_size': 26}. Best is trial 10 with value: 0.5416279208622312.
[I 2025-09-04 18:25:05,428] Trial 19 finished with value: 0.4925308765718184 and parameters: {'n_neighbors': 4, 'leaf_size': 10}. Best is trial 10 with value: 0.5416279208622312.
[I 2025-09-04 18:25:05,509] Trial 20 finished with value: 0.5242497144690823 and parameters: {'n_neighbors': 6, 'leaf_size': 39}. Best is trial 10 with value: 0.5416279208622312.

Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1

[I 2025-09-04 18:25:05,596] Trial 21 finished with value: 0.5416279208622312 and parameters: {'n_neighbors': 5, 'leaf_size': 18}. Best is trial 10 with value: 0.5416279208622312.
[I 2025-09-04 18:25:05,684] Trial 22 finished with value: 0.5416279208622312 and parameters: {'n_neighbors': 5, 'leaf_size': 22}. Best is trial 10 with value: 0.5416279208622312.

Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 18:25:05,770] Trial 23 finished with value: 0.4925308765718184 and parameters: {'n_neighbors': 4, 'leaf_size': 18}. Best is trial 10 with value: 0.5416279208622312.
[I 2025-09-04 18:25:05,902] Trial 24 finished with value: 0.5242497144690823 and parameters: {'n_neighbors': 6, 'leaf_size': 13}. Best is trial 10 with value: 0.5416279208622312.
[I 2025-09-04 18:25:05,904] A new study created in memory with name: no-name-a3ef03c2-ab2b-4d32-a5f8-4596f788f89b

Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

✅ KNN con C2X-Complex_rhown_9x9_depth_in_3_4 - Mejor R2: 0.54
📋 Parámetros: {'n_neighbors': 5, 'leaf_size': 19}

Buscando mejores hiperparámetros para LR con C2X-Complex_rhown_9x9_depth_in_3_4...

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 18:25:06,005] Trial 0 finished with value: 0.3787470402874733 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 0 with value: 0.3787470402874733.
[I 2025-09-04 18:25:06,097] Trial 1 finished with value: 0.4764774610057416 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.4764774610057416.

Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:25:06,175] Trial 2 finished with value: 0.4764774610057393 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 1 with value: 0.4764774610057416.
[I 2025-09-04 18:25:06,256] Trial 3 finished with value: 0.4764774610057416 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.4764774610057416.
[I 2025-09-04 18:25:06,333] Trial 4 finished with value: 0.4764774610057393 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 1 with value: 0.4764774610057416.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 18:25:06,431] Trial 5 finished with value: 0.3787470402874733 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 1 with value: 0.4764774610057416.

Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 18:25:06,705] Trial 6 finished with value: 0.3787470402874733 and parameters: {'fit_intercept': True, 'positive': False}. Best is trial 1 with value: 0.4764774610057416.

Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:25:06,827] Trial 7 finished with value: 0.4764774610057416 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.4764774610057416.
[I 2025-09-04 18:25:06,906] Trial 8 finished with value: 0.4764774610057393 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 1 with value: 0.4764774610057416.
[I 2025-09-04 18:25:06,984] Trial 9 finished with value: 0.4764774610057393 and parameters: {'fit_intercept': True, 'positive': True}. Best is trial 1 with value: 0.4764774610057416.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 18:25:07,075] Trial 10 finished with value: 0.3787470402857137 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 1 with value: 0.4764774610057416.
[I 2025-09-04 18:25:07,167] Trial 11 finished with value: 0.4764774610057416 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.4764774610057416.

Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:25:07,248] Trial 12 finished with value: 0.4764774610057416 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.4764774610057416.
[I 2025-09-04 18:25:07,326] Trial 13 finished with value: 0.4764774610057416 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.4764774610057416.
[I 2025-09-04 18:25:07,397] Trial 14 finished with value: 0.4764774610057416 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.4764774610057416.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

[I 2025-09-04 18:25:07,469] Trial 15 finished with value: 0.4764774610057416 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.4764774610057416.
[I 2025-09-04 18:25:07,547] Trial 16 finished with value: 0.4764774610057416 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.4764774610057416.
[I 2025-09-04 18:25:07,623] Trial 17 finished with value: 0.4764774610057416 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.4764774610057416.

Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2

[I 2025-09-04 18:25:07,724] Trial 18 finished with value: 0.3787470402857137 and parameters: {'fit_intercept': False, 'positive': False}. Best is trial 1 with value: 0.4764774610057416.
[I 2025-09-04 18:25:07,820] Trial 19 finished with value: 0.4764774610057416 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.4764774610057416.

Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 18:25:07,916] Trial 20 finished with value: 0.4764774610057416 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.4764774610057416.
[I 2025-09-04 18:25:07,994] Trial 21 finished with value: 0.4764774610057416 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.4764774610057416.
[I 2025-09-04 18:25:08,070] Trial 22 finished with value: 0.4764774610057416 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.4764774610057416.

Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1

[I 2025-09-04 18:25:08,144] Trial 23 finished with value: 0.4764774610057416 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.4764774610057416.
[I 2025-09-04 18:25:08,221] Trial 24 finished with value: 0.4764774610057416 and parameters: {'fit_intercept': False, 'positive': True}. Best is trial 1 with value: 0.4764774610057416.
[I 2025-09-04 18:25:08,222] A new study created in memory with name: no-name-eb730144-8582-421d-a78c-839041fbcf80

Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

✅ LR con C2X-Complex_rhown_9x9_depth_in_3_4 - Mejor R2: 0.48
📋 Parámetros: {'fit_intercept': False, 'positive': True}

Buscando mejores hiperparámetros para RF con C2X-Complex_rhown_9x9_depth_in_3_4...

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:25:23,040] Trial 0 finished with value: 0.36439502093794185 and parameters: {'n_estimators': 500, 'max_depth': 10, 'min_samples_split': 4, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 0 with value: 0.36439502093794185.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:25:26,190] Trial 1 finished with value: 0.2561272068673933 and parameters: {'n_estimators': 100, 'max_depth': 9, 'min_samples_split': 2, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 0 with value: 0.36439502093794185.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:25:38,534] Trial 2 finished with value: 0.4862813541367804 and parameters: {'n_estimators': 500, 'max_depth': 7, 'min_samples_split': 5, 'min_samples_leaf': 5, 'bootstrap': False}. Best is trial 2 with value: 0.4862813541367804.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:25:46,971] Trial 3 finished with value: 0.5973814578838126 and parameters: {'n_estimators': 500, 'max_depth': 6, 'min_samples_split': 6, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 3 with value: 0.5973814578838126.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:25:54,793] Trial 4 finished with value: 0.4751859903260499 and parameters: {'n_estimators': 300, 'max_depth': 11, 'min_samples_split': 4, 'min_samples_leaf': 5, 'bootstrap': False}. Best is trial 3 with value: 0.5973814578838126.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:25:57,197] Trial 5 finished with value: 0.6014734488799789 and parameters: {'n_estimators': 100, 'max_depth': 14, 'min_samples_split': 3, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 5 with value: 0.6014734488799789.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:26:03,062] Trial 6 finished with value: 0.59935215075459 and parameters: {'n_estimators': 300, 'max_depth': 15, 'min_samples_split': 6, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 5 with value: 0.6014734488799789.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:26:22,477] Trial 7 finished with value: 0.40865380952908137 and parameters: {'n_estimators': 500, 'max_depth': 13, 'min_samples_split': 2, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 5 with value: 0.6014734488799789.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:26:35,409] Trial 8 finished with value: 0.4755354187319303 and parameters: {'n_estimators': 500, 'max_depth': 13, 'min_samples_split': 3, 'min_samples_leaf': 5, 'bootstrap': False}. Best is trial 5 with value: 0.6014734488799789.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:26:44,808] Trial 9 finished with value: 0.6001859930658897 and parameters: {'n_estimators': 500, 'max_depth': 7, 'min_samples_split': 5, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 5 with value: 0.6014734488799789.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:26:46,870] Trial 10 finished with value: 0.6028600619458704 and parameters: {'n_estimators': 100, 'max_depth': 15, 'min_samples_split': 9, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 10 with value: 0.6028600619458704.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:26:48,908] Trial 11 finished with value: 0.5977298489293912 and parameters: {'n_estimators': 100, 'max_depth': 15, 'min_samples_split': 10, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 10 with value: 0.6028600619458704.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:26:50,962] Trial 12 finished with value: 0.6024053876767497 and parameters: {'n_estimators': 100, 'max_depth': 13, 'min_samples_split': 9, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 10 with value: 0.6028600619458704.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:26:52,942] Trial 13 finished with value: 0.6018850458441827 and parameters: {'n_estimators': 100, 'max_depth': 12, 'min_samples_split': 9, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 10 with value: 0.6028600619458704.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:26:55,067] Trial 14 finished with value: 0.6020485237570478 and parameters: {'n_estimators': 100, 'max_depth': 13, 'min_samples_split': 8, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 10 with value: 0.6028600619458704.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:26:56,877] Trial 15 finished with value: 0.5934223102508955 and parameters: {'n_estimators': 100, 'max_depth': 15, 'min_samples_split': 8, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 10 with value: 0.6028600619458704.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:26:58,834] Trial 16 finished with value: 0.6005874120556158 and parameters: {'n_estimators': 100, 'max_depth': 11, 'min_samples_split': 10, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 10 with value: 0.6028600619458704.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:27:00,928] Trial 17 finished with value: 0.6025554101880379 and parameters: {'n_estimators': 100, 'max_depth': 14, 'min_samples_split': 8, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 10 with value: 0.6028600619458704.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:27:06,799] Trial 18 finished with value: 0.6026662011590456 and parameters: {'n_estimators': 300, 'max_depth': 9, 'min_samples_split': 8, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 10 with value: 0.6028600619458704.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:27:12,747] Trial 19 finished with value: 0.6009033887667592 and parameters: {'n_estimators': 300, 'max_depth': 9, 'min_samples_split': 7, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 10 with value: 0.6028600619458704.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:27:18,081] Trial 20 finished with value: 0.5936317747394335 and parameters: {'n_estimators': 300, 'max_depth': 8, 'min_samples_split': 7, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 10 with value: 0.6028600619458704.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:27:24,410] Trial 21 finished with value: 0.6039402067376276 and parameters: {'n_estimators': 300, 'max_depth': 11, 'min_samples_split': 8, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 21 with value: 0.6039402067376276.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:27:29,022] Trial 22 finished with value: 0.5934061720652095 and parameters: {'n_estimators': 300, 'max_depth': 5, 'min_samples_split': 9, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 21 with value: 0.6039402067376276.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:27:35,395] Trial 23 finished with value: 0.6028073837681912 and parameters: {'n_estimators': 300, 'max_depth': 10, 'min_samples_split': 7, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 21 with value: 0.6039402067376276.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:27:41,843] Trial 24 finished with value: 0.6022618516796082 and parameters: {'n_estimators': 300, 'max_depth': 11, 'min_samples_split': 7, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 21 with value: 0.6039402067376276.
[I 2025-09-04 18:27:41,844] A new study created in memory with name: no-name-86fd277c-ba38-4e46-8d37-bb47de80b92a

✅ RF con C2X-Complex_rhown_9x9_depth_in_3_4 - Mejor R2: 0.60
📋 Parámetros: {'n_estimators': 300, 'max_depth': 11, 'min_samples_split': 8, 'min_samples_leaf': 1, 'bootstrap': True}

Buscando mejores hiperparámetros para CAT con C2X-Complex_rhown_9x9_depth_in_3_4...

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:28:02,284] Trial 0 finished with value: 0.5879290258421956 and parameters: {'iterations': 1000, 'learning_rate': 0.028140710741203855, 'depth': 7, 'l2_leaf_reg': 4.48211719033577}. Best is trial 0 with value: 0.5879290258421956.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:28:12,815] Trial 1 finished with value: 0.5908090128669499 and parameters: {'iterations': 500, 'learning_rate': 0.03546827240927673, 'depth': 7, 'l2_leaf_reg': 1.4252431259150635}. Best is trial 1 with value: 0.5908090128669499.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:28:33,133] Trial 2 finished with value: 0.5890711058013518 and parameters: {'iterations': 1000, 'learning_rate': 0.021808239180363866, 'depth': 7, 'l2_leaf_reg': 3.5279720800428036}. Best is trial 1 with value: 0.5908090128669499.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:30:08,149] Trial 3 finished with value: 0.5882984993950022 and parameters: {'iterations': 500, 'learning_rate': 0.015589400024601014, 'depth': 10, 'l2_leaf_reg': 3.2044619011707347}. Best is trial 1 with value: 0.5908090128669499.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:30:16,727] Trial 4 finished with value: 0.5928055600692528 and parameters: {'iterations': 1000, 'learning_rate': 0.012561412090506017, 'depth': 6, 'l2_leaf_reg': 5.902614235417}. Best is trial 4 with value: 0.5928055600692528.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:32:03,483] Trial 5 finished with value: 0.5920185545939742 and parameters: {'iterations': 1000, 'learning_rate': 0.01755326942938365, 'depth': 9, 'l2_leaf_reg': 2.6606499063500664}. Best is trial 4 with value: 0.5928055600692528.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:32:56,245] Trial 6 finished with value: 0.583583163517871 and parameters: {'iterations': 500, 'learning_rate': 0.03948665074090976, 'depth': 9, 'l2_leaf_reg': 4.251220402489934}. Best is trial 4 with value: 0.5928055600692528.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:36:34,617] Trial 7 finished with value: 0.5685578290523391 and parameters: {'iterations': 2000, 'learning_rate': 0.05742307669784689, 'depth': 9, 'l2_leaf_reg': 4.619414485507004}. Best is trial 4 with value: 0.5928055600692528.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:36:38,985] Trial 8 finished with value: 0.5568071257011207 and parameters: {'iterations': 500, 'learning_rate': 0.06508965528035225, 'depth': 6, 'l2_leaf_reg': 2.1391147433929936}. Best is trial 4 with value: 0.5928055600692528.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:38:14,649] Trial 9 finished with value: 0.5668929652476229 and parameters: {'iterations': 500, 'learning_rate': 0.043293024824207674, 'depth': 10, 'l2_leaf_reg': 3.0979475044185616}. Best is trial 4 with value: 0.5928055600692528.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:38:22,144] Trial 10 finished with value: 0.6036479110093821 and parameters: {'iterations': 2000, 'learning_rate': 0.010249089235742286, 'depth': 4, 'l2_leaf_reg': 5.821207426865001}. Best is trial 10 with value: 0.6036479110093821.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:38:29,482] Trial 11 finished with value: 0.6055211206514575 and parameters: {'iterations': 2000, 'learning_rate': 0.010717210168919473, 'depth': 4, 'l2_leaf_reg': 5.896660800316832}. Best is trial 11 with value: 0.6055211206514575.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:38:36,690] Trial 12 finished with value: 0.6032181316709544 and parameters: {'iterations': 2000, 'learning_rate': 0.010231965580431858, 'depth': 4, 'l2_leaf_reg': 5.742008776243835}. Best is trial 11 with value: 0.6055211206514575.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:38:44,423] Trial 13 finished with value: 0.6035307814428575 and parameters: {'iterations': 2000, 'learning_rate': 0.010215989825815964, 'depth': 4, 'l2_leaf_reg': 5.29710270763441}. Best is trial 11 with value: 0.6055211206514575.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:38:55,293] Trial 14 finished with value: 0.5974315214486261 and parameters: {'iterations': 2000, 'learning_rate': 0.014872714427928767, 'depth': 5, 'l2_leaf_reg': 5.168420958901277}. Best is trial 11 with value: 0.6055211206514575.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:39:06,247] Trial 15 finished with value: 0.6026459124523098 and parameters: {'iterations': 2000, 'learning_rate': 0.019262543966792584, 'depth': 5, 'l2_leaf_reg': 5.987005061297865}. Best is trial 11 with value: 0.6055211206514575.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:39:14,127] Trial 16 finished with value: 0.5969686166693988 and parameters: {'iterations': 2000, 'learning_rate': 0.01260165047927919, 'depth': 4, 'l2_leaf_reg': 5.103678063075839}. Best is trial 11 with value: 0.6055211206514575.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:39:25,065] Trial 17 finished with value: 0.5907593856176518 and parameters: {'iterations': 2000, 'learning_rate': 0.02353280547646125, 'depth': 5, 'l2_leaf_reg': 3.9501782986736753}. Best is trial 11 with value: 0.6055211206514575.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:39:42,241] Trial 18 finished with value: 0.593130203090818 and parameters: {'iterations': 2000, 'learning_rate': 0.012765899349249031, 'depth': 6, 'l2_leaf_reg': 5.359110577308358}. Best is trial 11 with value: 0.6055211206514575.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:39:49,529] Trial 19 finished with value: 0.599746117475247 and parameters: {'iterations': 2000, 'learning_rate': 0.010119289808310969, 'depth': 4, 'l2_leaf_reg': 4.832047932442814}. Best is trial 11 with value: 0.6055211206514575.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:40:01,012] Trial 20 finished with value: 0.5847908124220629 and parameters: {'iterations': 2000, 'learning_rate': 0.029116589600351492, 'depth': 5, 'l2_leaf_reg': 3.9136584378839}. Best is trial 11 with value: 0.6055211206514575.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:40:08,743] Trial 21 finished with value: 0.6023647311870541 and parameters: {'iterations': 2000, 'learning_rate': 0.01133121868707659, 'depth': 4, 'l2_leaf_reg': 5.482230044961809}. Best is trial 11 with value: 0.6055211206514575.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:40:16,388] Trial 22 finished with value: 0.5972302549075208 and parameters: {'iterations': 2000, 'learning_rate': 0.01494031943103546, 'depth': 4, 'l2_leaf_reg': 5.461800940486913}. Best is trial 11 with value: 0.6055211206514575.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:40:27,319] Trial 23 finished with value: 0.5961095746691598 and parameters: {'iterations': 2000, 'learning_rate': 0.01014466720325465, 'depth': 5, 'l2_leaf_reg': 5.990299268647279}. Best is trial 11 with value: 0.6055211206514575.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:40:35,176] Trial 24 finished with value: 0.603035182168535 and parameters: {'iterations': 2000, 'learning_rate': 0.013363933419021992, 'depth': 4, 'l2_leaf_reg': 4.966405887960381}. Best is trial 11 with value: 0.6055211206514575.
[I 2025-09-04 18:40:35,177] A new study created in memory with name: no-name-1536c7ed-2b88-4a46-9bb6-e6018a6ce57a
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.639e-01, tolerance: 4.433e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 18:40:35,312] Trial 0 finished with value: 0.5803713030697943 and parameters: {'alpha': 0.01450405399597832, 'l1_ratio': 0.35955809644216175}. Best is trial 0 with value: 0.5803713030697943.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.137e+01, tolerance: 4.876e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.199e+01, tolerance: 5.544e-02
  model = cd_fast.enet_coordinate_descent(

✅ CAT con C2X-Complex_rhown_9x9_depth_in_3_4 - Mejor R2: 0.61
📋 Parámetros: {'iterations': 2000, 'learning_rate': 0.010717210168919473, 'depth': 4, 'l2_leaf_reg': 5.896660800316832}

Buscando mejores hiperparámetros para ELN con C2X-Complex_rhown_9x9_depth_in_3_4...

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.593e+01, tolerance: 4.561e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.683e+01, tolerance: 4.433e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.656e+01, tolerance: 5.000e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 18:40:35,466] Trial 1 finished with value: 0.5785907649972539 and parameters: {'alpha': 0.0026372311136592616, 'l1_ratio': 0.3409184159227341}. Best is trial 0 with value: 0.5803713030697943.

Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

[I 2025-09-04 18:40:35,610] Trial 2 finished with value: 0.3161895664402168 and parameters: {'alpha': 0.8001779406974393, 'l1_ratio': 0.6140478009987809}. Best is trial 0 with value: 0.5803713030697943.
[I 2025-09-04 18:40:35,774] Trial 3 finished with value: 0.5449447099578493 and parameters: {'alpha': 0.0403544750127087, 'l1_ratio': 0.7029447743696706}. Best is trial 0 with value: 0.5803713030697943.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1

[I 2025-09-04 18:40:35,926] Trial 4 finished with value: 0.3007676306469669 and parameters: {'alpha': 0.9757661974712982, 'l1_ratio': 0.5167031085539843}. Best is trial 0 with value: 0.5803713030697943.

Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

[I 2025-09-04 18:40:36,065] Trial 5 finished with value: 0.494841188263218 and parameters: {'alpha': 0.13491543694194966, 'l1_ratio': 0.6751892678836344}. Best is trial 0 with value: 0.5803713030697943.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.176e+02, tolerance: 4.876e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.240e+02, tolerance: 5.544e-02
  model = cd_fast.enet_coordinate_descent(

Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.017e+02, tolerance: 4.561e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.006e+02, tolerance: 4.433e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.078e+02, tolerance: 5.000e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 18:40:36,242] Trial 6 finished with value: 0.5798535422158422 and parameters: {'alpha': 0.00012624839316000735, 'l1_ratio': 0.4602209639733923}. Best is trial 0 with value: 0.5803713030697943.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.130e+02, tolerance: 4.876e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.196e+02, tolerance: 5.544e-02
  model = cd_fast.enet_coordinate_descent(

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.647e+01, tolerance: 4.561e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.684e+01, tolerance: 4.433e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.372e+01, tolerance: 5.000e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 18:40:36,451] Trial 7 finished with value: 0.5865657818946972 and parameters: {'alpha': 0.00028408584238361485, 'l1_ratio': 0.28462520155481774}. Best is trial 7 with value: 0.5865657818946972.
[I 2025-09-04 18:40:36,639] Trial 8 finished with value: 0.5558517957989154 and parameters: {'alpha': 0.12908762713044164, 'l1_ratio': 0.10904571663148033}. Best is trial 7 with value: 0.5865657818946972.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1

[I 2025-09-04 18:40:36,817] Trial 9 finished with value: 0.5276341611169704 and parameters: {'alpha': 0.6078154802278984, 'l1_ratio': 0.003341088591703345}. Best is trial 7 with value: 0.5865657818946972.

Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.659e+01, tolerance: 4.876e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.091e+02, tolerance: 5.544e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.384e+01, tolerance: 4.561e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.763e+01, tolerance: 4.433e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.823e+01, tolerance: 5.000e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 18:40:37,039] Trial 10 finished with value: 0.5837953801348075 and parameters: {'alpha': 0.00020248697871034826, 'l1_ratio': 0.957699807134083}. Best is trial 7 with value: 0.5865657818946972.

Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.101e+02, tolerance: 4.876e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.190e+02, tolerance: 5.544e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.558e+01, tolerance: 4.561e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.630e+01, tolerance: 4.433e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.517e+01, tolerance: 5.000e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 18:40:37,214] Trial 11 finished with value: 0.5791170001130824 and parameters: {'alpha': 0.00010709606090344972, 'l1_ratio': 0.9831233747331862}. Best is trial 7 with value: 0.5865657818946972.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.048e+01, tolerance: 4.876e-02
  model = cd_fast.enet_coordinate_descent(

Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.599e+01, tolerance: 5.544e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.246e+01, tolerance: 4.561e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.080e+01, tolerance: 4.433e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.165e+01, tolerance: 5.000e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 18:40:37,402] Trial 12 finished with value: 0.5919255136167619 and parameters: {'alpha': 0.0007937446266356812, 'l1_ratio': 0.8913028143575612}. Best is trial 12 with value: 0.5919255136167619.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.708e+01, tolerance: 4.876e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.301e+01, tolerance: 5.544e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.486e+01, tolerance: 4.561e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.111e+01, tolerance: 4.433e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.537e+01, tolerance: 5.000e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 18:40:37,592] Trial 13 finished with value: 0.589383901862765 and parameters: {'alpha': 0.0012201334833498664, 'l1_ratio': 0.21313772719555746}. Best is trial 12 with value: 0.5919255136167619.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.698e+01, tolerance: 4.876e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.935e+00, tolerance: 5.544e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.564e+00, tolerance: 4.561e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.015e+01, tolerance: 4.433e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.289e+01, tolerance: 5.000e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 18:40:37,790] Trial 14 finished with value: 0.5877158325368148 and parameters: {'alpha': 0.001246511426787589, 'l1_ratio': 0.797889956913017}. Best is trial 12 with value: 0.5919255136167619.

Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.745e+01, tolerance: 4.876e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.441e+01, tolerance: 5.544e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.594e+01, tolerance: 4.561e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.241e+01, tolerance: 4.433e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.408e+01, tolerance: 5.000e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 18:40:37,997] Trial 15 finished with value: 0.589090726333978 and parameters: {'alpha': 0.0012547485110894292, 'l1_ratio': 0.20345510664961852}. Best is trial 12 with value: 0.5919255136167619.

Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.313e-02, tolerance: 4.876e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.346e-01, tolerance: 5.544e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.659e-01, tolerance: 4.433e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.526e-01, tolerance: 5.000e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 18:40:38,291] Trial 16 finished with value: 0.5801312879979228 and parameters: {'alpha': 0.004577350218489365, 'l1_ratio': 0.8500025650958135}. Best is trial 12 with value: 0.5919255136167619.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.155e+01, tolerance: 4.876e-02
  model = cd_fast.enet_coordinate_descent(

Fold 2
Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.770e+01, tolerance: 5.544e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.215e+01, tolerance: 4.561e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.857e+01, tolerance: 4.433e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.684e+01, tolerance: 5.000e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 18:40:38,497] Trial 17 finished with value: 0.5917398193249561 and parameters: {'alpha': 0.000531646488368282, 'l1_ratio': 0.48939712144816805}. Best is trial 12 with value: 0.5919255136167619.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.828e+01, tolerance: 4.876e-02
  model = cd_fast.enet_coordinate_descent(

Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.549e+01, tolerance: 5.544e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.121e+01, tolerance: 4.561e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.638e+01, tolerance: 4.433e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.978e+01, tolerance: 5.000e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 18:40:38,680] Trial 18 finished with value: 0.5917401747292841 and parameters: {'alpha': 0.0005342330647038077, 'l1_ratio': 0.5309200110334428}. Best is trial 12 with value: 0.5919255136167619.

Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.219e-01, tolerance: 5.544e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.281e-01, tolerance: 4.433e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.175e-01, tolerance: 5.000e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 18:40:38,960] Trial 19 finished with value: 0.5802915854523012 and parameters: {'alpha': 0.005136275913058574, 'l1_ratio': 0.8356320701928422}. Best is trial 12 with value: 0.5919255136167619.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.792e+01, tolerance: 4.876e-02
  model = cd_fast.enet_coordinate_descent(

Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.751e+01, tolerance: 5.544e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.191e+01, tolerance: 4.561e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.797e+01, tolerance: 4.433e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.806e+01, tolerance: 5.000e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 18:40:39,174] Trial 20 finished with value: 0.5913123345479316 and parameters: {'alpha': 0.0004950406635443413, 'l1_ratio': 0.5895437147768418}. Best is trial 12 with value: 0.5919255136167619.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.899e+01, tolerance: 4.876e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.315e+01, tolerance: 5.544e-02
  model = cd_fast.enet_coordinate_descent(

Fold 3
Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.845e+01, tolerance: 4.561e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.459e+01, tolerance: 4.433e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.004e+01, tolerance: 5.000e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 18:40:39,369] Trial 21 finished with value: 0.5920042780385877 and parameters: {'alpha': 0.0005793064901784498, 'l1_ratio': 0.4713572778228997}. Best is trial 21 with value: 0.5920042780385877.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.701e+01, tolerance: 4.876e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.767e+01, tolerance: 5.544e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.385e+01, tolerance: 4.561e-02
  model = cd_fast.enet_coordinate_descent(

Fold 4
Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.012e+01, tolerance: 4.433e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.033e+01, tolerance: 5.000e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 18:40:39,530] Trial 22 finished with value: 0.5921951567857184 and parameters: {'alpha': 0.0006519825496700685, 'l1_ratio': 0.4259782426330299}. Best is trial 22 with value: 0.5921951567857184.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.360e+01, tolerance: 4.876e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.514e+01, tolerance: 5.544e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.110e+01, tolerance: 4.561e-02
  model = cd_fast.enet_coordinate_descent(
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.204e+01, tolerance: 4.433e-02
  model = cd_fast.enet_coordinate_descent(

Fold 5

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.359e+01, tolerance: 5.000e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 18:40:39,717] Trial 23 finished with value: 0.5794362072702861 and parameters: {'alpha': 0.002314283053760167, 'l1_ratio': 0.4314628852963102}. Best is trial 22 with value: 0.5921951567857184.
/home/antonio/.pyenv/versions/3.8.5/envs/nitrates/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.189e-01, tolerance: 4.433e-02
  model = cd_fast.enet_coordinate_descent(
[I 2025-09-04 18:40:39,889] Trial 24 finished with value: 0.580217444290587 and parameters: {'alpha': 0.011916205822972576, 'l1_ratio': 0.3952526893453642}. Best is trial 22 with value: 0.5921951567857184.

=== Procesando C2X-Complex_rhown_9x9_depth_in_3_4 ===
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5

✅ ELN con C2X-Complex_rhown_9x9_depth_in_3_4 - Mejor R2: 0.59
📋 Parámetros: {'alpha': 0.0006519825496700685, 'l1_ratio': 0.4259782426330299}

In [292]:
def objective(trial, df, target, model_name):
    # df = df.iloc[:,4:]
    # # Mismos splits que para el entrenamiento
    # train, test = train_test_split(df, test_size=0.2, random_state=42, stratify=df["High_Chl"]) # TEST 20% TRAIN 80%
    # target = "Chl"
    # train, val = train_test_split(train, test_size=0.25, random_state=42, stratify=train["High_Chl"])

    # X = train.drop(columns=[target, 'High_Chl'])
    # y = train[target]
    # y_class = train["High_Chl"]

    # Definimos los folds
    skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
    
    oof_preds = np.zeros(len(train))  # Almacenar las predicciones OOF

    start = time.time()
    
    if model_name == "LBM":
        params = {
            'objective': 'regression',
            'metric': 'rmse',
            'boosting_type': 'gbdt',
            'device': 'cpu',  # usa CPU/GPU
            'verbosity': -1,
            'learning_rate': trial.suggest_float('learning_rate', 0.005, 0.1, log=True),
            'num_leaves': trial.suggest_categorical('num_leaves', [20, 40, 60, 80]),
            'max_depth': trial.suggest_int('max_depth', 5, 8),
            'min_child_samples': trial.suggest_int('min_child_samples', 5, 25),
            'subsample': trial.suggest_float('subsample', 0.6, 1.0),
            'colsample_bytree': trial.suggest_float('colsample_bytree', 0.6, 1.0),
            'n_estimators': trial.suggest_categorical('n_estimators', [500, 1000, 2000])
        }

    if model_name == "XGB":
        params = {
            'n_estimators': trial.suggest_categorical('n_estimators', [500, 1000, 2000]),
            'learning_rate': trial.suggest_float('learning_rate', 0.005, 0.1, log=True),
            'max_depth': trial.suggest_int('max_depth', 5, 8),
            'min_child_weight': trial.suggest_int('min_child_weight', 1, 4),
            'subsample': trial.suggest_float('subsample', 0.6, 1.0),
            'colsample_bytree': trial.suggest_float('colsample_bytree', 0.6, 1.0),
            'device': 'cpu',
            'objective': 'reg:squarederror',
            'tree_method': 'hist',
            'enable_categorical': True,
            'eval_metric': 'rmse'
        }
    
    if model_name == "MLP":
        # Así para evitar warning de definir como tuple
        hidden_options = {
            '50': (50,),
            '100': (100,),
            '100_50': (100, 50),
            '128_64': (128, 64)
        }
        key = trial.suggest_categorical('hidden_layer_sizes', list(hidden_options.keys()))
        params = {
            'hidden_layer_sizes': hidden_options[key],
            #'hidden_layer_sizes': trial.suggest_categorical('hidden_layer_sizes', [(50,), (100,), (100, 50), (128, 64)]),
            'activation': trial.suggest_categorical('activation', ['relu', 'tanh']),
            'solver': trial.suggest_categorical('solver', ['adam', 'sgd']),
            'alpha': trial.suggest_float('alpha', 1e-5, 1e-1, log=True),
            'learning_rate': trial.suggest_categorical('learning_rate', ['constant', 'adaptive']),
            'learning_rate_init': trial.suggest_float('learning_rate_init', 1e-4, 1e-2, log=True),
            'max_iter': 200,
            'n_iter_no_change': 25,
            'early_stopping': True,
            'validation_fraction': 0.2,
            'random_state': 42,
            'verbose': False
        }

    if model_name == "SVR":
        params = {
            'kernel': trial.suggest_categorical('kernel', ['rbf', 'sigmoid']),
            'C': trial.suggest_float('C', 0.1, 10.0, log=True),
            'epsilon': trial.suggest_float('epsilon', 0.01, 0.2),
            'gamma': trial.suggest_categorical('gamma', ['scale', 'auto']),
            'shrinking': True,
            'tol': 1e-3,
            'max_iter': -1,
            'verbose': False
        }

    if model_name == "KNN":
        params = {
            'n_neighbors': trial.suggest_int('n_neighbors', 3, 15),
            'weights': trial.suggest_categorical('weights', ['uniform', 'distance']),
            'algorithm': 'auto',
            'leaf_size': trial.suggest_int('leaf_size', 10, 40),
            'p': 2,  # 1 = manhattan, 2 = euclídea
            'metric': 'minkowski',
            'n_jobs': -1
        }

    if model_name == "LR":
        # No sirve de mucho, pero por completitud
        params = {
            'fit_intercept': trial.suggest_categorical('fit_intercept', [True, False]),
            'positive': trial.suggest_categorical('positive', [True, False]),
        }

    if model_name == "RF":
        params = {
            'n_estimators': trial.suggest_categorical('n_estimators', [100, 300, 500]),
            'max_depth': trial.suggest_int('max_depth', 5, 15),
            'min_samples_split': trial.suggest_int('min_samples_split', 2, 10),
            'min_samples_leaf': trial.suggest_int('min_samples_leaf', 1, 5),
            'bootstrap': trial.suggest_categorical('bootstrap', [True, False]),
            'random_state': 42,
            'verbose': 0
        }

    if model_name == "CAT":
        params = {
            'iterations': trial.suggest_categorical('iterations', [500, 1000, 2000]),
            'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.1, log=True),
            'depth': trial.suggest_int('depth', 4, 10),
            'l2_leaf_reg': trial.suggest_float('l2_leaf_reg', 1.0, 10.0),
            'loss_function': 'RMSE',
            'eval_metric': 'RMSE',
            'random_seed': 42,
            'early_stopping_rounds': 50,
            'verbose': False,
        }

    if model_name == "EN":
        params = {
            'alpha': trial.suggest_float('alpha', 1e-4, 10.0, log=True),
            'l1_ratio': trial.suggest_float('l1_ratio', 0.0, 1.0),
            'fit_intercept': True,
            'max_iter': 1000,
            'tol': 1e-4,
            'selection': 'cyclic',
            'random_state': 42
        }

    # Cargamos el modelo correspondiente
    model = models[model_name](**params)

    
    for fold, (train_idx, val_idx) in enumerate(skf.split(X, y_class)):
        print(f"Fold {fold+1}")
        
        X_train, X_val = X.iloc[train_idx], X.iloc[val_idx]
        y_train, y_val = y.iloc[train_idx], y.iloc[val_idx]

        if model_name in ["MLP", "SVR", "KNN", "LR", "EN"]:
            scaler_X = RobustScaler()
            scaler_y = RobustScaler()
            X_train_scaled = scaler_X.fit_transform(X_train)
            X_val_scaled = scaler_X.transform(X_val)
            y_train_scaled = scaler_y.fit_transform(y_train.values.reshape(-1, 1)).ravel()
            model.fit(X_train_scaled, y_train_scaled)
            y_pred = scaler_y.inverse_transform(model.predict(X_val_scaled).reshape(-1, 1)).ravel()
        else:
            model.fit(X_train, y_train)
            y_pred = model.predict(X_val)
        
        oof_preds[val_idx] = y_pred


    print(f"Running time: {time.time() - start:.1f} sec")
    # Calculamos el RMSE OOF
    rmse_score = np.sqrt(mean_squared_error(y, oof_preds))
    r2 = r2_score(y, oof_preds)
    print(f"OOF RMSE: {rmse_score:.2f} | R2: {r2:.2f}")
    
    return r2

In [47]:
global_results

{('TOA_9x9_depth_in_3_4',
  'XGB'): {'best_params': {'n_estimators': 2000,
   'learning_rate': 0.047600594240155655,
   'max_depth': 5,
   'min_child_weight': 4,
   'subsample': 0.6049475476360661,
   'colsample_bytree': 0.8631912096943319}, 'best_score': 0.615, 'study': <optuna.study.study.Study at 0x7800b0502610>},
 ('TOA_9x9_depth_in_3_4',
  'LBM'): {'best_params': {'learning_rate': 0.01713416804277511,
   'num_leaves': 80,
   'max_depth': 8,
   'min_child_samples': 11,
   'subsample': 0.7883599431510695,
   'colsample_bytree': 0.8460115625974576,
   'n_estimators': 500}, 'best_score': 0.628, 'study': <optuna.study.study.Study at 0x7800b0502c10>},
 ('TOA_9x9_depth_in_3_4',
  'MLP'): {'best_params': {'hidden_layer_sizes': '256_128',
   'activation': 'relu',
   'solver': 'sgd',
   'alpha': 0.015492411781384838,
   'learning_rate': 'adaptive',
   'learning_rate_init': 0.0019024503727906594}, 'best_score': 0.71, 'study': <optuna.study.study.Study at 0x7800b014d100>},
 ('TOA_9x9_depth_in_3_4',
  'SVR'): {'best_params': {'C': 1.9860741741743726,
   'epsilon': 0.023712171259654913}, 'best_score': 0.504, 'study': <optuna.study.study.Study at 0x7800d80a13a0>},
 ('TOA_9x9_depth_in_3_4',
  'KNN'): {'best_params': {'n_neighbors': 10,
   'leaf_size': 40}, 'best_score': 0.65, 'study': <optuna.study.study.Study at 0x7800b03d04c0>},
 ('TOA_9x9_depth_in_3_4',
  'LR'): {'best_params': {'fit_intercept': False,
   'positive': False}, 'best_score': 0.378, 'study': <optuna.study.study.Study at 0x7800b04c3eb0>},
 ('TOA_9x9_depth_in_3_4',
  'RF'): {'best_params': {'n_estimators': 100,
   'max_depth': 14,
   'min_samples_split': 10,
   'min_samples_leaf': 2,
   'bootstrap': True}, 'best_score': 0.624, 'study': <optuna.study.study.Study at 0x7800b029aa60>},
 ('TOA_9x9_depth_in_3_4',
  'CAT'): {'best_params': {'iterations': 1000,
   'learning_rate': 0.0678180379236064,
   'depth': 8,
   'l2_leaf_reg': 2.511488464786048}, 'best_score': 0.621, 'study': <optuna.study.study.Study at 0x7800b0609370>},
 ('TOA_9x9_depth_in_3_4',
  'ELN'): {'best_params': {'alpha': 0.00010094145044864732,
   'l1_ratio': 0.5266509861480015}, 'best_score': 0.461, 'study': <optuna.study.study.Study at 0x7800d917cd00>},
 ('TOA_3x3_depth_in_3_4',
  'XGB'): {'best_params': {'n_estimators': 500,
   'learning_rate': 0.009576598127245279,
   'max_depth': 7,
   'min_child_weight': 4,
   'subsample': 0.7615794445091003,
   'colsample_bytree': 0.6930474458735117}, 'best_score': 0.627, 'study': <optuna.study.study.Study at 0x7800d930ac70>},
 ('TOA_3x3_depth_in_3_4',
  'LBM'): {'best_params': {'learning_rate': 0.01474336254464019,
   'num_leaves': 40,
   'max_depth': 6,
   'min_child_samples': 6,
   'subsample': 0.9964816945465981,
   'colsample_bytree': 0.8686133786839119,
   'n_estimators': 500}, 'best_score': 0.661, 'study': <optuna.study.study.Study at 0x7800b0557190>},
 ('TOA_3x3_depth_in_3_4',
  'MLP'): {'best_params': {'hidden_layer_sizes': '128_64',
   'activation': 'relu',
   'solver': 'adam',
   'alpha': 1.8399498662330756e-05,
   'learning_rate': 'constant',
   'learning_rate_init': 0.0005319925846193705}, 'best_score': 0.676, 'study': <optuna.study.study.Study at 0x7800a9f7a3a0>},
 ('TOA_3x3_depth_in_3_4',
  'SVR'): {'best_params': {'C': 2.4279016303695427,
   'epsilon': 0.08368239687667561}, 'best_score': 0.488, 'study': <optuna.study.study.Study at 0x7800b044be80>},
 ('TOA_3x3_depth_in_3_4',
  'KNN'): {'best_params': {'n_neighbors': 6,
   'leaf_size': 40}, 'best_score': 0.617, 'study': <optuna.study.study.Study at 0x7800b06f57f0>},
 ('TOA_3x3_depth_in_3_4',
  'LR'): {'best_params': {'fit_intercept': True,
   'positive': False}, 'best_score': 0.4, 'study': <optuna.study.study.Study at 0x7800b0187610>},
 ('TOA_3x3_depth_in_3_4',
  'RF'): {'best_params': {'n_estimators': 300,
   'max_depth': 12,
   'min_samples_split': 6,
   'min_samples_leaf': 3,
   'bootstrap': False}, 'best_score': 0.681, 'study': <optuna.study.study.Study at 0x7800b0354d30>},
 ('TOA_3x3_depth_in_3_4',
  'CAT'): {'best_params': {'iterations': 500,
   'learning_rate': 0.05232742477450515,
   'depth': 9,
   'l2_leaf_reg': 1.0235346499052462}, 'best_score': 0.63, 'study': <optuna.study.study.Study at 0x7800b02f4610>},
 ('TOA_3x3_depth_in_3_4',
  'ELN'): {'best_params': {'alpha': 0.00018219071583212146,
   'l1_ratio': 0.9794021781112037}, 'best_score': 0.467, 'study': <optuna.study.study.Study at 0x7800a9ffc9d0>},
 ('TOA_5x5_depth_in_3_4',
  'XGB'): {'best_params': {'n_estimators': 500,
   'learning_rate': 0.04876113896916153,
   'max_depth': 5,
   'min_child_weight': 4,
   'subsample': 0.7176461215093223,
   'colsample_bytree': 0.6759132844855982}, 'best_score': 0.627, 'study': <optuna.study.study.Study at 0x7800d919b280>},
 ('TOA_5x5_depth_in_3_4',
  'LBM'): {'best_params': {'learning_rate': 0.01955671466854787,
   'num_leaves': 60,
   'max_depth': 6,
   'min_child_samples': 4,
   'subsample': 0.9583671783514893,
   'colsample_bytree': 0.9991128614038579,
   'n_estimators': 500}, 'best_score': 0.678, 'study': <optuna.study.study.Study at 0x7800b02c6e20>},
 ('TOA_5x5_depth_in_3_4',
  'MLP'): {'best_params': {'hidden_layer_sizes': '128_64',
   'activation': 'relu',
   'solver': 'adam',
   'alpha': 0.00024472909052337217,
   'learning_rate': 'adaptive',
   'learning_rate_init': 0.0005084699170246252}, 'best_score': 0.697, 'study': <optuna.study.study.Study at 0x7800b004c0a0>},
 ('TOA_5x5_depth_in_3_4',
  'SVR'): {'best_params': {'C': 2.063097300418171,
   'epsilon': 0.0789893324667928}, 'best_score': 0.483, 'study': <optuna.study.study.Study at 0x7800b01fdb20>},
 ('TOA_5x5_depth_in_3_4',
  'KNN'): {'best_params': {'n_neighbors': 10,
   'leaf_size': 18}, 'best_score': 0.638, 'study': <optuna.study.study.Study at 0x7800b03aa640>},
 ('TOA_5x5_depth_in_3_4',
  'LR'): {'best_params': {'fit_intercept': True,
   'positive': False}, 'best_score': 0.448, 'study': <optuna.study.study.Study at 0x7800b029bd00>},
 ('TOA_5x5_depth_in_3_4',
  'RF'): {'best_params': {'n_estimators': 100,
   'max_depth': 15,
   'min_samples_split': 4,
   'min_samples_leaf': 3,
   'bootstrap': True}, 'best_score': 0.63, 'study': <optuna.study.study.Study at 0x7800b00a2ca0>},
 ('TOA_5x5_depth_in_3_4',
  'CAT'): {'best_params': {'iterations': 2000,
   'learning_rate': 0.01027011523144864,
   'depth': 7,
   'l2_leaf_reg': 1.0526076927639805}, 'best_score': 0.593, 'study': <optuna.study.study.Study at 0x7800b04bdaf0>},
 ('TOA_5x5_depth_in_3_4',
  'ELN'): {'best_params': {'alpha': 0.014403901229536019,
   'l1_ratio': 0.9023438654300626}, 'best_score': 0.474, 'study': <optuna.study.study.Study at 0x7800a9f6d8e0>},
 ('C2X-Complex_rhow_5x5_depth_in_3_4',
  'XGB'): {'best_params': {'n_estimators': 500,
   'learning_rate': 0.007889846245071235,
   'max_depth': 7,
   'min_child_weight': 4,
   'subsample': 0.6478799909895996,
   'colsample_bytree': 0.9184042139949454}, 'best_score': 0.652, 'study': <optuna.study.study.Study at 0x7800a9f5eb80>},
 ('C2X-Complex_rhow_5x5_depth_in_3_4',
  'LBM'): {'best_params': {'learning_rate': 0.006617912473095984,
   'num_leaves': 40,
   'max_depth': 8,
   'min_child_samples': 8,
   'subsample': 0.9303188839872626,
   'colsample_bytree': 0.7448045774739271,
   'n_estimators': 500}, 'best_score': 0.636, 'study': <optuna.study.study.Study at 0x7800b06a8d60>},
 ('C2X-Complex_rhow_5x5_depth_in_3_4',
  'MLP'): {'best_params': {'hidden_layer_sizes': '256_128',
   'activation': 'relu',
   'solver': 'adam',
   'alpha': 0.00010236429010965995,
   'learning_rate': 'adaptive',
   'learning_rate_init': 0.0003651197409167566}, 'best_score': 0.657, 'study': <optuna.study.study.Study at 0x7800b057dfa0>},
 ('C2X-Complex_rhow_5x5_depth_in_3_4',
  'SVR'): {'best_params': {'C': 9.555509499241047,
   'epsilon': 0.13134472658792118}, 'best_score': 0.537, 'study': <optuna.study.study.Study at 0x7800b0079520>},
 ('C2X-Complex_rhow_5x5_depth_in_3_4',
  'KNN'): {'best_params': {'n_neighbors': 10,
   'leaf_size': 40}, 'best_score': 0.588, 'study': <optuna.study.study.Study at 0x7800a9f3d160>},
 ('C2X-Complex_rhow_5x5_depth_in_3_4',
  'LR'): {'best_params': {'fit_intercept': False,
   'positive': True}, 'best_score': 0.548, 'study': <optuna.study.study.Study at 0x7800b06798b0>},
 ('C2X-Complex_rhow_5x5_depth_in_3_4',
  'RF'): {'best_params': {'n_estimators': 500,
   'max_depth': 12,
   'min_samples_split': 2,
   'min_samples_leaf': 2,
   'bootstrap': True}, 'best_score': 0.651, 'study': <optuna.study.study.Study at 0x7800b057f7f0>},
 ('C2X-Complex_rhow_5x5_depth_in_3_4',
  'CAT'): {'best_params': {'iterations': 500,
   'learning_rate': 0.014143036661619373,
   'depth': 4,
   'l2_leaf_reg': 2.864319547628134}, 'best_score': 0.63, 'study': <optuna.study.study.Study at 0x7800b06be1c0>},
 ('C2X-Complex_rhow_5x5_depth_in_3_4',
  'ELN'): {'best_params': {'alpha': 0.0025285029727796925,
   'l1_ratio': 0.5792628939321688}, 'best_score': 0.584, 'study': <optuna.study.study.Study at 0x7800d9079fa0>},
 ('TOA_1x1_depth_in_3_4',
  'XGB'): {'best_params': {'n_estimators': 500,
   'learning_rate': 0.005903889352876245,
   'max_depth': 8,
   'min_child_weight': 2,
   'subsample': 0.781917998902364,
   'colsample_bytree': 0.722278807877633}, 'best_score': 0.519, 'study': <optuna.study.study.Study at 0x7800b07592e0>},
 ('TOA_1x1_depth_in_3_4',
  'LBM'): {'best_params': {'learning_rate': 0.007130386687415869,
   'num_leaves': 20,
   'max_depth': 7,
   'min_child_samples': 10,
   'subsample': 0.8922959456502495,
   'colsample_bytree': 0.9294737227298466,
   'n_estimators': 500}, 'best_score': 0.618, 'study': <optuna.study.study.Study at 0x7800b0085820>},
 ('TOA_1x1_depth_in_3_4',
  'MLP'): {'best_params': {'hidden_layer_sizes': '256',
   'activation': 'relu',
   'solver': 'adam',
   'alpha': 4.763485358217016e-05,
   'learning_rate': 'adaptive',
   'learning_rate_init': 0.0004348441303622641}, 'best_score': 0.688, 'study': <optuna.study.study.Study at 0x7800b029aac0>},
 ('TOA_1x1_depth_in_3_4',
  'SVR'): {'best_params': {'C': 2.2111333817672927,
   'epsilon': 0.07253326854109794}, 'best_score': 0.461, 'study': <optuna.study.study.Study at 0x7800b025f2b0>},
 ('TOA_1x1_depth_in_3_4',
  'KNN'): {'best_params': {'n_neighbors': 6,
   'leaf_size': 33}, 'best_score': 0.611, 'study': <optuna.study.study.Study at 0x7800b01d88e0>},
 ('TOA_1x1_depth_in_3_4',
  'LR'): {'best_params': {'fit_intercept': False,
   'positive': True}, 'best_score': 0.328, 'study': <optuna.study.study.Study at 0x7800b021e070>},
 ('TOA_1x1_depth_in_3_4',
  'RF'): {'best_params': {'n_estimators': 500,
   'max_depth': 11,
   'min_samples_split': 6,
   'min_samples_leaf': 3,
   'bootstrap': True}, 'best_score': 0.557, 'study': <optuna.study.study.Study at 0x7800d8343670>},
 ('TOA_1x1_depth_in_3_4',
  'CAT'): {'best_params': {'iterations': 1000,
   'learning_rate': 0.033260444981323356,
   'depth': 8,
   'l2_leaf_reg': 1.12206076072196}, 'best_score': 0.569, 'study': <optuna.study.study.Study at 0x7800dcb5f460>},
 ('TOA_1x1_depth_in_3_4',
  'ELN'): {'best_params': {'alpha': 0.028283841413022752,
   'l1_ratio': 0.9109286287993379}, 'best_score': 0.452, 'study': <optuna.study.study.Study at 0x7800d92a9b50>},
 ('TOA_15x15_depth_in_3_4',
  'XGB'): {'best_params': {'n_estimators': 500,
   'learning_rate': 0.013566967402918429,
   'max_depth': 5,
   'min_child_weight': 4,
   'subsample': 0.6807531615273382,
   'colsample_bytree': 0.607434439562925}, 'best_score': 0.607, 'study': <optuna.study.study.Study at 0x7800b03f2220>},
 ('TOA_15x15_depth_in_3_4',
  'LBM'): {'best_params': {'learning_rate': 0.00909468587481228,
   'num_leaves': 60,
   'max_depth': 7,
   'min_child_samples': 13,
   'subsample': 0.6536720142119191,
   'colsample_bytree': 0.8953446248078664,
   'n_estimators': 1000}, 'best_score': 0.632, 'study': <optuna.study.study.Study at 0x7800a9661100>},
 ('TOA_15x15_depth_in_3_4',
  'MLP'): {'best_params': {'hidden_layer_sizes': '256',
   'activation': 'relu',
   'solver': 'adam',
   'alpha': 0.0034242834875374936,
   'learning_rate': 'constant',
   'learning_rate_init': 0.0012220669807227185}, 'best_score': 0.708, 'study': <optuna.study.study.Study at 0x7800a8debf10>},
 ('TOA_15x15_depth_in_3_4',
  'SVR'): {'best_params': {'C': 2.15684226903379,
   'epsilon': 0.12775727625293434}, 'best_score': 0.494, 'study': <optuna.study.study.Study at 0x7800a8dacc40>},
 ('TOA_15x15_depth_in_3_4',
  'KNN'): {'best_params': {'n_neighbors': 7,
   'leaf_size': 31}, 'best_score': 0.649, 'study': <optuna.study.study.Study at 0x7800a9eb7c70>},
 ('TOA_15x15_depth_in_3_4',
  'LR'): {'best_params': {'fit_intercept': False,
   'positive': False}, 'best_score': 0.38, 'study': <optuna.study.study.Study at 0x7800a9f4b820>},
 ('TOA_15x15_depth_in_3_4',
  'RF'): {'best_params': {'n_estimators': 100,
   'max_depth': 10,
   'min_samples_split': 2,
   'min_samples_leaf': 2,
   'bootstrap': True}, 'best_score': 0.617, 'study': <optuna.study.study.Study at 0x7800a8dff730>},
 ('TOA_15x15_depth_in_3_4',
  'CAT'): {'best_params': {'iterations': 2000,
   'learning_rate': 0.05314326154992145,
   'depth': 9,
   'l2_leaf_reg': 1.0213152871705147}, 'best_score': 0.681, 'study': <optuna.study.study.Study at 0x7800a8d816a0>},
 ('TOA_15x15_depth_in_3_4',
  'ELN'): {'best_params': {'alpha': 0.00011287578590294489,
   'l1_ratio': 0.9941527400112994}, 'best_score': 0.505, 'study': <optuna.study.study.Study at 0x7800a8dab1c0>},
 ('C2X-Complex_rhown_5x5_depth_in_3_4',
  'XGB'): {'best_params': {'n_estimators': 2000,
   'learning_rate': 0.045720937679426726,
   'max_depth': 7,
   'min_child_weight': 2,
   'subsample': 0.8049551995941774,
   'colsample_bytree': 0.9077296398951732}, 'best_score': 0.637, 'study': <optuna.study.study.Study at 0x7800a8d94d30>},
 ('C2X-Complex_rhown_5x5_depth_in_3_4',
  'LBM'): {'best_params': {'learning_rate': 0.021490317734639115,
   'num_leaves': 60,
   'max_depth': 7,
   'min_child_samples': 4,
   'subsample': 0.9171600598982209,
   'colsample_bytree': 0.9060991657287198,
   'n_estimators': 500}, 'best_score': 0.623, 'study': <optuna.study.study.Study at 0x7800e4412a90>},
 ('C2X-Complex_rhown_5x5_depth_in_3_4',
  'MLP'): {'best_params': {'hidden_layer_sizes': '256_128',
   'activation': 'relu',
   'solver': 'sgd',
   'alpha': 0.0028311644287798946,
   'learning_rate': 'constant',
   'learning_rate_init': 0.005228148188640056}, 'best_score': 0.618, 'study': <optuna.study.study.Study at 0x7800b018e790>},
 ('C2X-Complex_rhown_5x5_depth_in_3_4',
  'SVR'): {'best_params': {'C': 3.645085787366226,
   'epsilon': 0.18516646571349163}, 'best_score': 0.509, 'study': <optuna.study.study.Study at 0x7800a9673850>},
 ('C2X-Complex_rhown_5x5_depth_in_3_4',
  'KNN'): {'best_params': {'n_neighbors': 10,
   'leaf_size': 34}, 'best_score': 0.571, 'study': <optuna.study.study.Study at 0x7800b00b8e50>},
 ('C2X-Complex_rhown_5x5_depth_in_3_4',
  'LR'): {'best_params': {'fit_intercept': False,
   'positive': True}, 'best_score': 0.537, 'study': <optuna.study.study.Study at 0x7800b04e9340>},
 ('C2X-Complex_rhown_5x5_depth_in_3_4',
  'RF'): {'best_params': {'n_estimators': 500,
   'max_depth': 11,
   'min_samples_split': 4,
   'min_samples_leaf': 2,
   'bootstrap': True}, 'best_score': 0.641, 'study': <optuna.study.study.Study at 0x7800b06798e0>},
 ('C2X-Complex_rhown_5x5_depth_in_3_4',
  'CAT'): {'best_params': {'iterations': 500,
   'learning_rate': 0.025340947072845177,
   'depth': 6,
   'l2_leaf_reg': 5.927927435982809}, 'best_score': 0.603, 'study': <optuna.study.study.Study at 0x7800a9f92b50>},
 ('C2X-Complex_rhown_5x5_depth_in_3_4',
  'ELN'): {'best_params': {'alpha': 0.029440640009221405,
   'l1_ratio': 0.9952562878940697}, 'best_score': 0.573, 'study': <optuna.study.study.Study at 0x7800a9f92fa0>},
 ('C2X-Complex_rhow_9x9_depth_in_3_4',
  'XGB'): {'best_params': {'n_estimators': 500,
   'learning_rate': 0.007784242501186818,
   'max_depth': 6,
   'min_child_weight': 1,
   'subsample': 0.6045990140239461,
   'colsample_bytree': 0.9996062608334324}, 'best_score': 0.616, 'study': <optuna.study.study.Study at 0x7800a8d96a00>},
 ('C2X-Complex_rhow_9x9_depth_in_3_4',
  'LBM'): {'best_params': {'learning_rate': 0.006387333436517826,
   'num_leaves': 80,
   'max_depth': 8,
   'min_child_samples': 13,
   'subsample': 0.6384425602632136,
   'colsample_bytree': 0.6626794560644892,
   'n_estimators': 500}, 'best_score': 0.624, 'study': <optuna.study.study.Study at 0x7800d911cc10>},
 ('C2X-Complex_rhow_9x9_depth_in_3_4',
  'MLP'): {'best_params': {'hidden_layer_sizes': '256_128',
   'activation': 'relu',
   'solver': 'adam',
   'alpha': 0.0014611726954603002,
   'learning_rate': 'constant',
   'learning_rate_init': 0.0006912854086058073}, 'best_score': 0.649, 'study': <optuna.study.study.Study at 0x7800a8dd2790>},
 ('C2X-Complex_rhow_9x9_depth_in_3_4',
  'SVR'): {'best_params': {'C': 9.93157967401947,
   'epsilon': 0.1963107857538181}, 'best_score': 0.598, 'study': <optuna.study.study.Study at 0x7800b036ba60>},
 ('C2X-Complex_rhow_9x9_depth_in_3_4',
  'KNN'): {'best_params': {'n_neighbors': 9,
   'leaf_size': 27}, 'best_score': 0.579, 'study': <optuna.study.study.Study at 0x7800a9eb3460>},
 ('C2X-Complex_rhow_9x9_depth_in_3_4',
  'LR'): {'best_params': {'fit_intercept': False,
   'positive': True}, 'best_score': 0.569, 'study': <optuna.study.study.Study at 0x7800d8f87d90>},
 ('C2X-Complex_rhow_9x9_depth_in_3_4',
  'RF'): {'best_params': {'n_estimators': 100,
   'max_depth': 14,
   'min_samples_split': 3,
   'min_samples_leaf': 1,
   'bootstrap': True}, 'best_score': 0.63, 'study': <optuna.study.study.Study at 0x7800a8e23940>},
 ('C2X-Complex_rhow_9x9_depth_in_3_4',
  'CAT'): {'best_params': {'iterations': 1000,
   'learning_rate': 0.07521844621271666,
   'depth': 5,
   'l2_leaf_reg': 4.739858256733454}, 'best_score': 0.617, 'study': <optuna.study.study.Study at 0x7800b01b6430>},
 ('C2X-Complex_rhow_9x9_depth_in_3_4',
  'ELN'): {'best_params': {'alpha': 0.015126276739043923,
   'l1_ratio': 0.3433210919466816}, 'best_score': 0.589, 'study': <optuna.study.study.Study at 0x7800a9ecdbe0>},
 ('C2X-Complex_rhow_15x15_depth_in_3_4',
  'XGB'): {'best_params': {'n_estimators': 1000,
   'learning_rate': 0.010148550064538592,
   'max_depth': 7,
   'min_child_weight': 1,
   'subsample': 0.7092554975366574,
   'colsample_bytree': 0.9589996114894445}, 'best_score': 0.548, 'study': <optuna.study.study.Study at 0x7800a9f0bc70>},
 ('C2X-Complex_rhow_15x15_depth_in_3_4',
  'LBM'): {'best_params': {'learning_rate': 0.005034271791889273,
   'num_leaves': 60,
   'max_depth': 6,
   'min_child_samples': 11,
   'subsample': 0.9704198407257476,
   'colsample_bytree': 0.8302542907662975,
   'n_estimators': 500}, 'best_score': 0.555, 'study': <optuna.study.study.Study at 0x7800a8e6bf40>},
 ('C2X-Complex_rhow_15x15_depth_in_3_4',
  'MLP'): {'best_params': {'hidden_layer_sizes': '256',
   'activation': 'relu',
   'solver': 'adam',
   'alpha': 0.03673448429184167,
   'learning_rate': 'adaptive',
   'learning_rate_init': 0.005512541724045937}, 'best_score': 0.638, 'study': <optuna.study.study.Study at 0x7800a9f6f5b0>},
 ('C2X-Complex_rhow_15x15_depth_in_3_4',
  'SVR'): {'best_params': {'C': 3.2413369664629386,
   'epsilon': 0.1982961712911414}, 'best_score': 0.584, 'study': <optuna.study.study.Study at 0x7800d8fe5ee0>},
 ('C2X-Complex_rhow_15x15_depth_in_3_4',
  'KNN'): {'best_params': {'n_neighbors': 10,
   'leaf_size': 19}, 'best_score': 0.484, 'study': <optuna.study.study.Study at 0x7800a8e0ebb0>},
 ('C2X-Complex_rhow_15x15_depth_in_3_4',
  'LR'): {'best_params': {'fit_intercept': True,
   'positive': True}, 'best_score': 0.537, 'study': <optuna.study.study.Study at 0x7800a8e796a0>},
 ('C2X-Complex_rhow_15x15_depth_in_3_4',
  'RF'): {'best_params': {'n_estimators': 100,
   'max_depth': 8,
   'min_samples_split': 3,
   'min_samples_leaf': 4,
   'bootstrap': True}, 'best_score': 0.572, 'study': <optuna.study.study.Study at 0x7800a9ec8d30>},
 ('C2X-Complex_rhow_15x15_depth_in_3_4',
  'CAT'): {'best_params': {'iterations': 500,
   'learning_rate': 0.010126948003726963,

In [14]:
with open(f"training_results/selection_results_{depth}.pkl", "wb") as f:
    pickle.dump(global_results, f)

In [39]:
# Diccionario para agrupar parámetros por modelo
params_by_model = defaultdict(list)

# Agrupar best_params por modelo
for (df_name, model_name), result in global_results.items():
    best_params = result["best_params"]
    params_by_model[model_name].append(best_params)

# Crear DataFrames con medias y std por modelo
summary_stats = {}

for model_name, param_list in params_by_model.items():
    df_params = pd.DataFrame(param_list)

    # Filtramos solo columnas numéricas para calcular medias y std
    df_numeric = df_params.select_dtypes(include=[np.number])

    stats = pd.concat([df_numeric.mean().rename("mean"), df_numeric.std().rename("std")], axis=1)
    summary_stats[model_name] = stats

# Mostrar un ejemplo
summary_stats["LBM"]

                         mean         std
learning_rate        0.011264    0.006322
num_leaves          52.000000   21.499354
max_depth            6.800000    1.032796
min_child_samples    9.000000    3.366502
subsample            0.846105    0.135599
colsample_bytree     0.853437    0.094603
n_estimators       550.000000  158.113883

In [37]:
global_results

{('TOA_9x9_depth_in_3_4',
  'XGB'): {'best_params': {'n_estimators': 2000,
   'learning_rate': 0.047600594240155655,
   'max_depth': 5,
   'min_child_weight': 4,
   'subsample': 0.6049475476360661,
   'colsample_bytree': 0.8631912096943319}, 'best_score': 0.615, 'study': <optuna.study.study.Study at 0x7800b0502610>},
 ('TOA_9x9_depth_in_3_4',
  'LBM'): {'best_params': {'learning_rate': 0.01713416804277511,
   'num_leaves': 80,
   'max_depth': 8,
   'min_child_samples': 11,
   'subsample': 0.7883599431510695,
   'colsample_bytree': 0.8460115625974576,
   'n_estimators': 500}, 'best_score': 0.628, 'study': <optuna.study.study.Study at 0x7800b0502c10>},
 ('TOA_9x9_depth_in_3_4',
  'MLP'): {'best_params': {'hidden_layer_sizes': '256_128',
   'activation': 'relu',
   'solver': 'sgd',
   'alpha': 0.015492411781384838,
   'learning_rate': 'adaptive',
   'learning_rate_init': 0.0019024503727906594}, 'best_score': 0.71, 'study': <optuna.study.study.Study at 0x7800b014d100>},
 ('TOA_9x9_depth_in_3_4',
  'SVR'): {'best_params': {'C': 1.9860741741743726,
   'epsilon': 0.023712171259654913}, 'best_score': 0.504, 'study': <optuna.study.study.Study at 0x7800d80a13a0>},
 ('TOA_9x9_depth_in_3_4',
  'KNN'): {'best_params': {'n_neighbors': 10,
   'leaf_size': 40}, 'best_score': 0.65, 'study': <optuna.study.study.Study at 0x7800b03d04c0>},
 ('TOA_9x9_depth_in_3_4',
  'LR'): {'best_params': {'fit_intercept': False,
   'positive': False}, 'best_score': 0.378, 'study': <optuna.study.study.Study at 0x7800b04c3eb0>},
 ('TOA_9x9_depth_in_3_4',
  'RF'): {'best_params': {'n_estimators': 100,
   'max_depth': 14,
   'min_samples_split': 10,
   'min_samples_leaf': 2,
   'bootstrap': True}, 'best_score': 0.624, 'study': <optuna.study.study.Study at 0x7800b029aa60>},
 ('TOA_9x9_depth_in_3_4',
  'CAT'): {'best_params': {'iterations': 1000,
   'learning_rate': 0.0678180379236064,
   'depth': 8,
   'l2_leaf_reg': 2.511488464786048}, 'best_score': 0.621, 'study': <optuna.study.study.Study at 0x7800b0609370>},
 ('TOA_9x9_depth_in_3_4',
  'ELN'): {'best_params': {'alpha': 0.00010094145044864732,
   'l1_ratio': 0.5266509861480015}, 'best_score': 0.461, 'study': <optuna.study.study.Study at 0x7800d917cd00>},
 ('TOA_3x3_depth_in_3_4',
  'XGB'): {'best_params': {'n_estimators': 500,
   'learning_rate': 0.009576598127245279,
   'max_depth': 7,
   'min_child_weight': 4,
   'subsample': 0.7615794445091003,
   'colsample_bytree': 0.6930474458735117}, 'best_score': 0.627, 'study': <optuna.study.study.Study at 0x7800d930ac70>},
 ('TOA_3x3_depth_in_3_4',
  'LBM'): {'best_params': {'learning_rate': 0.01474336254464019,
   'num_leaves': 40,
   'max_depth': 6,
   'min_child_samples': 6,
   'subsample': 0.9964816945465981,
   'colsample_bytree': 0.8686133786839119,
   'n_estimators': 500}, 'best_score': 0.661, 'study': <optuna.study.study.Study at 0x7800b0557190>},
 ('TOA_3x3_depth_in_3_4',
  'MLP'): {'best_params': {'hidden_layer_sizes': '128_64',
   'activation': 'relu',
   'solver': 'adam',
   'alpha': 1.8399498662330756e-05,
   'learning_rate': 'constant',
   'learning_rate_init': 0.0005319925846193705}, 'best_score': 0.676, 'study': <optuna.study.study.Study at 0x7800a9f7a3a0>},
 ('TOA_3x3_depth_in_3_4',
  'SVR'): {'best_params': {'C': 2.4279016303695427,
   'epsilon': 0.08368239687667561}, 'best_score': 0.488, 'study': <optuna.study.study.Study at 0x7800b044be80>},
 ('TOA_3x3_depth_in_3_4',
  'KNN'): {'best_params': {'n_neighbors': 6,
   'leaf_size': 40}, 'best_score': 0.617, 'study': <optuna.study.study.Study at 0x7800b06f57f0>},
 ('TOA_3x3_depth_in_3_4',
  'LR'): {'best_params': {'fit_intercept': True,
   'positive': False}, 'best_score': 0.4, 'study': <optuna.study.study.Study at 0x7800b0187610>},
 ('TOA_3x3_depth_in_3_4',
  'RF'): {'best_params': {'n_estimators': 300,
   'max_depth': 12,
   'min_samples_split': 6,
   'min_samples_leaf': 3,
   'bootstrap': False}, 'best_score': 0.681, 'study': <optuna.study.study.Study at 0x7800b0354d30>},
 ('TOA_3x3_depth_in_3_4',
  'CAT'): {'best_params': {'iterations': 500,
   'learning_rate': 0.05232742477450515,
   'depth': 9,
   'l2_leaf_reg': 1.0235346499052462}, 'best_score': 0.63, 'study': <optuna.study.study.Study at 0x7800b02f4610>},
 ('TOA_3x3_depth_in_3_4',
  'ELN'): {'best_params': {'alpha': 0.00018219071583212146,
   'l1_ratio': 0.9794021781112037}, 'best_score': 0.467, 'study': <optuna.study.study.Study at 0x7800a9ffc9d0>},
 ('TOA_5x5_depth_in_3_4',
  'XGB'): {'best_params': {'n_estimators': 500,
   'learning_rate': 0.04876113896916153,
   'max_depth': 5,
   'min_child_weight': 4,
   'subsample': 0.7176461215093223,
   'colsample_bytree': 0.6759132844855982}, 'best_score': 0.627, 'study': <optuna.study.study.Study at 0x7800d919b280>},
 ('TOA_5x5_depth_in_3_4',
  'LBM'): {'best_params': {'learning_rate': 0.01955671466854787,
   'num_leaves': 60,
   'max_depth': 6,
   'min_child_samples': 4,
   'subsample': 0.9583671783514893,
   'colsample_bytree': 0.9991128614038579,
   'n_estimators': 500}, 'best_score': 0.678, 'study': <optuna.study.study.Study at 0x7800b02c6e20>},
 ('TOA_5x5_depth_in_3_4',
  'MLP'): {'best_params': {'hidden_layer_sizes': '128_64',
   'activation': 'relu',
   'solver': 'adam',
   'alpha': 0.00024472909052337217,
   'learning_rate': 'adaptive',
   'learning_rate_init': 0.0005084699170246252}, 'best_score': 0.697, 'study': <optuna.study.study.Study at 0x7800b004c0a0>},
 ('TOA_5x5_depth_in_3_4',
  'SVR'): {'best_params': {'C': 2.063097300418171,
   'epsilon': 0.0789893324667928}, 'best_score': 0.483, 'study': <optuna.study.study.Study at 0x7800b01fdb20>},
 ('TOA_5x5_depth_in_3_4',
  'KNN'): {'best_params': {'n_neighbors': 10,
   'leaf_size': 18}, 'best_score': 0.638, 'study': <optuna.study.study.Study at 0x7800b03aa640>},
 ('TOA_5x5_depth_in_3_4',
  'LR'): {'best_params': {'fit_intercept': True,
   'positive': False}, 'best_score': 0.448, 'study': <optuna.study.study.Study at 0x7800b029bd00>},
 ('TOA_5x5_depth_in_3_4',
  'RF'): {'best_params': {'n_estimators': 100,
   'max_depth': 15,
   'min_samples_split': 4,
   'min_samples_leaf': 3,
   'bootstrap': True}, 'best_score': 0.63, 'study': <optuna.study.study.Study at 0x7800b00a2ca0>},
 ('TOA_5x5_depth_in_3_4',
  'CAT'): {'best_params': {'iterations': 2000,
   'learning_rate': 0.01027011523144864,
   'depth': 7,
   'l2_leaf_reg': 1.0526076927639805}, 'best_score': 0.593, 'study': <optuna.study.study.Study at 0x7800b04bdaf0>},
 ('TOA_5x5_depth_in_3_4',
  'ELN'): {'best_params': {'alpha': 0.014403901229536019,
   'l1_ratio': 0.9023438654300626}, 'best_score': 0.474, 'study': <optuna.study.study.Study at 0x7800a9f6d8e0>},
 ('C2X-Complex_rhow_5x5_depth_in_3_4',
  'XGB'): {'best_params': {'n_estimators': 500,
   'learning_rate': 0.007889846245071235,
   'max_depth': 7,
   'min_child_weight': 4,
   'subsample': 0.6478799909895996,
   'colsample_bytree': 0.9184042139949454}, 'best_score': 0.652, 'study': <optuna.study.study.Study at 0x7800a9f5eb80>},
 ('C2X-Complex_rhow_5x5_depth_in_3_4',
  'LBM'): {'best_params': {'learning_rate': 0.006617912473095984,
   'num_leaves': 40,
   'max_depth': 8,
   'min_child_samples': 8,
   'subsample': 0.9303188839872626,
   'colsample_bytree': 0.7448045774739271,
   'n_estimators': 500}, 'best_score': 0.636, 'study': <optuna.study.study.Study at 0x7800b06a8d60>},
 ('C2X-Complex_rhow_5x5_depth_in_3_4',
  'MLP'): {'best_params': {'hidden_layer_sizes': '256_128',
   'activation': 'relu',
   'solver': 'adam',
   'alpha': 0.00010236429010965995,
   'learning_rate': 'adaptive',
   'learning_rate_init': 0.0003651197409167566}, 'best_score': 0.657, 'study': <optuna.study.study.Study at 0x7800b057dfa0>},
 ('C2X-Complex_rhow_5x5_depth_in_3_4',
  'SVR'): {'best_params': {'C': 9.555509499241047,
   'epsilon': 0.13134472658792118}, 'best_score': 0.537, 'study': <optuna.study.study.Study at 0x7800b0079520>},
 ('C2X-Complex_rhow_5x5_depth_in_3_4',
  'KNN'): {'best_params': {'n_neighbors': 10,
   'leaf_size': 40}, 'best_score': 0.588, 'study': <optuna.study.study.Study at 0x7800a9f3d160>},
 ('C2X-Complex_rhow_5x5_depth_in_3_4',
  'LR'): {'best_params': {'fit_intercept': False,
   'positive': True}, 'best_score': 0.548, 'study': <optuna.study.study.Study at 0x7800b06798b0>},
 ('C2X-Complex_rhow_5x5_depth_in_3_4',
  'RF'): {'best_params': {'n_estimators': 500,
   'max_depth': 12,
   'min_samples_split': 2,
   'min_samples_leaf': 2,
   'bootstrap': True}, 'best_score': 0.651, 'study': <optuna.study.study.Study at 0x7800b057f7f0>},
 ('C2X-Complex_rhow_5x5_depth_in_3_4',
  'CAT'): {'best_params': {'iterations': 500,
   'learning_rate': 0.014143036661619373,
   'depth': 4,
   'l2_leaf_reg': 2.864319547628134}, 'best_score': 0.63, 'study': <optuna.study.study.Study at 0x7800b06be1c0>},
 ('C2X-Complex_rhow_5x5_depth_in_3_4',
  'ELN'): {'best_params': {'alpha': 0.0025285029727796925,
   'l1_ratio': 0.5792628939321688}, 'best_score': 0.584, 'study': <optuna.study.study.Study at 0x7800d9079fa0>},
 ('TOA_1x1_depth_in_3_4',
  'XGB'): {'best_params': {'n_estimators': 500,
   'learning_rate': 0.005903889352876245,
   'max_depth': 8,
   'min_child_weight': 2,
   'subsample': 0.781917998902364,
   'colsample_bytree': 0.722278807877633}, 'best_score': 0.519, 'study': <optuna.study.study.Study at 0x7800b07592e0>},
 ('TOA_1x1_depth_in_3_4',
  'LBM'): {'best_params': {'learning_rate': 0.007130386687415869,
   'num_leaves': 20,
   'max_depth': 7,
   'min_child_samples': 10,
   'subsample': 0.8922959456502495,
   'colsample_bytree': 0.9294737227298466,
   'n_estimators': 500}, 'best_score': 0.618, 'study': <optuna.study.study.Study at 0x7800b0085820>},
 ('TOA_1x1_depth_in_3_4',
  'MLP'): {'best_params': {'hidden_layer_sizes': '256',
   'activation': 'relu',
   'solver': 'adam',
   'alpha': 4.763485358217016e-05,
   'learning_rate': 'adaptive',
   'learning_rate_init': 0.0004348441303622641}, 'best_score': 0.688, 'study': <optuna.study.study.Study at 0x7800b029aac0>},
 ('TOA_1x1_depth_in_3_4',
  'SVR'): {'best_params': {'C': 2.2111333817672927,
   'epsilon': 0.07253326854109794}, 'best_score': 0.461, 'study': <optuna.study.study.Study at 0x7800b025f2b0>},
 ('TOA_1x1_depth_in_3_4',
  'KNN'): {'best_params': {'n_neighbors': 6,
   'leaf_size': 33}, 'best_score': 0.611, 'study': <optuna.study.study.Study at 0x7800b01d88e0>},
 ('TOA_1x1_depth_in_3_4',
  'LR'): {'best_params': {'fit_intercept': False,
   'positive': True}, 'best_score': 0.328, 'study': <optuna.study.study.Study at 0x7800b021e070>},
 ('TOA_1x1_depth_in_3_4',
  'RF'): {'best_params': {'n_estimators': 500,
   'max_depth': 11,
   'min_samples_split': 6,
   'min_samples_leaf': 3,
   'bootstrap': True}, 'best_score': 0.557, 'study': <optuna.study.study.Study at 0x7800d8343670>},
 ('TOA_1x1_depth_in_3_4',
  'CAT'): {'best_params': {'iterations': 1000,
   'learning_rate': 0.033260444981323356,
   'depth': 8,
   'l2_leaf_reg': 1.12206076072196}, 'best_score': 0.569, 'study': <optuna.study.study.Study at 0x7800dcb5f460>},
 ('TOA_1x1_depth_in_3_4',
  'ELN'): {'best_params': {'alpha': 0.028283841413022752,
   'l1_ratio': 0.9109286287993379}, 'best_score': 0.452, 'study': <optuna.study.study.Study at 0x7800d92a9b50>},
 ('TOA_15x15_depth_in_3_4',
  'XGB'): {'best_params': {'n_estimators': 500,
   'learning_rate': 0.013566967402918429,
   'max_depth': 5,
   'min_child_weight': 4,
   'subsample': 0.6807531615273382,
   'colsample_bytree': 0.607434439562925}, 'best_score': 0.607, 'study': <optuna.study.study.Study at 0x7800b03f2220>},
 ('TOA_15x15_depth_in_3_4',
  'LBM'): {'best_params': {'learning_rate': 0.00909468587481228,
   'num_leaves': 60,
   'max_depth': 7,
   'min_child_samples': 13,
   'subsample': 0.6536720142119191,
   'colsample_bytree': 0.8953446248078664,
   'n_estimators': 1000}, 'best_score': 0.632, 'study': <optuna.study.study.Study at 0x7800a9661100>},
 ('TOA_15x15_depth_in_3_4',
  'MLP'): {'best_params': {'hidden_layer_sizes': '256',
   'activation': 'relu',
   'solver': 'adam',
   'alpha': 0.0034242834875374936,
   'learning_rate': 'constant',
   'learning_rate_init': 0.0012220669807227185}, 'best_score': 0.708, 'study': <optuna.study.study.Study at 0x7800a8debf10>},
 ('TOA_15x15_depth_in_3_4',
  'SVR'): {'best_params': {'C': 2.15684226903379,
   'epsilon': 0.12775727625293434}, 'best_score': 0.494, 'study': <optuna.study.study.Study at 0x7800a8dacc40>},
 ('TOA_15x15_depth_in_3_4',
  'KNN'): {'best_params': {'n_neighbors': 7,
   'leaf_size': 31}, 'best_score': 0.649, 'study': <optuna.study.study.Study at 0x7800a9eb7c70>},
 ('TOA_15x15_depth_in_3_4',
  'LR'): {'best_params': {'fit_intercept': False,
   'positive': False}, 'best_score': 0.38, 'study': <optuna.study.study.Study at 0x7800a9f4b820>},
 ('TOA_15x15_depth_in_3_4',
  'RF'): {'best_params': {'n_estimators': 100,
   'max_depth': 10,
   'min_samples_split': 2,
   'min_samples_leaf': 2,
   'bootstrap': True}, 'best_score': 0.617, 'study': <optuna.study.study.Study at 0x7800a8dff730>},
 ('TOA_15x15_depth_in_3_4',
  'CAT'): {'best_params': {'iterations': 2000,
   'learning_rate': 0.05314326154992145,
   'depth': 9,
   'l2_leaf_reg': 1.0213152871705147}, 'best_score': 0.681, 'study': <optuna.study.study.Study at 0x7800a8d816a0>},
 ('TOA_15x15_depth_in_3_4',
  'ELN'): {'best_params': {'alpha': 0.00011287578590294489,
   'l1_ratio': 0.9941527400112994}, 'best_score': 0.505, 'study': <optuna.study.study.Study at 0x7800a8dab1c0>},
 ('C2X-Complex_rhown_5x5_depth_in_3_4',
  'XGB'): {'best_params': {'n_estimators': 2000,
   'learning_rate': 0.045720937679426726,
   'max_depth': 7,
   'min_child_weight': 2,
   'subsample': 0.8049551995941774,
   'colsample_bytree': 0.9077296398951732}, 'best_score': 0.637, 'study': <optuna.study.study.Study at 0x7800a8d94d30>},
 ('C2X-Complex_rhown_5x5_depth_in_3_4',
  'LBM'): {'best_params': {'learning_rate': 0.021490317734639115,
   'num_leaves': 60,
   'max_depth': 7,
   'min_child_samples': 4,
   'subsample': 0.9171600598982209,
   'colsample_bytree': 0.9060991657287198,
   'n_estimators': 500}, 'best_score': 0.623, 'study': <optuna.study.study.Study at 0x7800e4412a90>},
 ('C2X-Complex_rhown_5x5_depth_in_3_4',
  'MLP'): {'best_params': {'hidden_layer_sizes': '256_128',
   'activation': 'relu',
   'solver': 'sgd',
   'alpha': 0.0028311644287798946,
   'learning_rate': 'constant',
   'learning_rate_init': 0.005228148188640056}, 'best_score': 0.618, 'study': <optuna.study.study.Study at 0x7800b018e790>},
 ('C2X-Complex_rhown_5x5_depth_in_3_4',
  'SVR'): {'best_params': {'C': 3.645085787366226,
   'epsilon': 0.18516646571349163}, 'best_score': 0.509, 'study': <optuna.study.study.Study at 0x7800a9673850>},
 ('C2X-Complex_rhown_5x5_depth_in_3_4',
  'KNN'): {'best_params': {'n_neighbors': 10,
   'leaf_size': 34}, 'best_score': 0.571, 'study': <optuna.study.study.Study at 0x7800b00b8e50>},
 ('C2X-Complex_rhown_5x5_depth_in_3_4',
  'LR'): {'best_params': {'fit_intercept': False,
   'positive': True}, 'best_score': 0.537, 'study': <optuna.study.study.Study at 0x7800b04e9340>},
 ('C2X-Complex_rhown_5x5_depth_in_3_4',
  'RF'): {'best_params': {'n_estimators': 500,
   'max_depth': 11,
   'min_samples_split': 4,
   'min_samples_leaf': 2,
   'bootstrap': True}, 'best_score': 0.641, 'study': <optuna.study.study.Study at 0x7800b06798e0>},
 ('C2X-Complex_rhown_5x5_depth_in_3_4',
  'CAT'): {'best_params': {'iterations': 500,
   'learning_rate': 0.025340947072845177,
   'depth': 6,
   'l2_leaf_reg': 5.927927435982809}, 'best_score': 0.603, 'study': <optuna.study.study.Study at 0x7800a9f92b50>},
 ('C2X-Complex_rhown_5x5_depth_in_3_4',
  'ELN'): {'best_params': {'alpha': 0.029440640009221405,
   'l1_ratio': 0.9952562878940697}, 'best_score': 0.573, 'study': <optuna.study.study.Study at 0x7800a9f92fa0>},
 ('C2X-Complex_rhow_9x9_depth_in_3_4',
  'XGB'): {'best_params': {'n_estimators': 500,
   'learning_rate': 0.007784242501186818,
   'max_depth': 6,
   'min_child_weight': 1,
   'subsample': 0.6045990140239461,
   'colsample_bytree': 0.9996062608334324}, 'best_score': 0.616, 'study': <optuna.study.study.Study at 0x7800a8d96a00>},
 ('C2X-Complex_rhow_9x9_depth_in_3_4',
  'LBM'): {'best_params': {'learning_rate': 0.006387333436517826,
   'num_leaves': 80,
   'max_depth': 8,
   'min_child_samples': 13,
   'subsample': 0.6384425602632136,
   'colsample_bytree': 0.6626794560644892,
   'n_estimators': 500}, 'best_score': 0.624, 'study': <optuna.study.study.Study at 0x7800d911cc10>},
 ('C2X-Complex_rhow_9x9_depth_in_3_4',
  'MLP'): {'best_params': {'hidden_layer_sizes': '256_128',
   'activation': 'relu',
   'solver': 'adam',
   'alpha': 0.0014611726954603002,
   'learning_rate': 'constant',
   'learning_rate_init': 0.0006912854086058073}, 'best_score': 0.649, 'study': <optuna.study.study.Study at 0x7800a8dd2790>},
 ('C2X-Complex_rhow_9x9_depth_in_3_4',
  'SVR'): {'best_params': {'C': 9.93157967401947,
   'epsilon': 0.1963107857538181}, 'best_score': 0.598, 'study': <optuna.study.study.Study at 0x7800b036ba60>},
 ('C2X-Complex_rhow_9x9_depth_in_3_4',
  'KNN'): {'best_params': {'n_neighbors': 9,
   'leaf_size': 27}, 'best_score': 0.579, 'study': <optuna.study.study.Study at 0x7800a9eb3460>},
 ('C2X-Complex_rhow_9x9_depth_in_3_4',
  'LR'): {'best_params': {'fit_intercept': False,
   'positive': True}, 'best_score': 0.569, 'study': <optuna.study.study.Study at 0x7800d8f87d90>},
 ('C2X-Complex_rhow_9x9_depth_in_3_4',
  'RF'): {'best_params': {'n_estimators': 100,
   'max_depth': 14,
   'min_samples_split': 3,
   'min_samples_leaf': 1,
   'bootstrap': True}, 'best_score': 0.63, 'study': <optuna.study.study.Study at 0x7800a8e23940>},
 ('C2X-Complex_rhow_9x9_depth_in_3_4',
  'CAT'): {'best_params': {'iterations': 1000,
   'learning_rate': 0.07521844621271666,
   'depth': 5,
   'l2_leaf_reg': 4.739858256733454}, 'best_score': 0.617, 'study': <optuna.study.study.Study at 0x7800b01b6430>},
 ('C2X-Complex_rhow_9x9_depth_in_3_4',
  'ELN'): {'best_params': {'alpha': 0.015126276739043923,
   'l1_ratio': 0.3433210919466816}, 'best_score': 0.589, 'study': <optuna.study.study.Study at 0x7800a9ecdbe0>},
 ('C2X-Complex_rhow_15x15_depth_in_3_4',
  'XGB'): {'best_params': {'n_estimators': 1000,
   'learning_rate': 0.010148550064538592,
   'max_depth': 7,
   'min_child_weight': 1,
   'subsample': 0.7092554975366574,
   'colsample_bytree': 0.9589996114894445}, 'best_score': 0.548, 'study': <optuna.study.study.Study at 0x7800a9f0bc70>},
 ('C2X-Complex_rhow_15x15_depth_in_3_4',
  'LBM'): {'best_params': {'learning_rate': 0.005034271791889273,
   'num_leaves': 60,
   'max_depth': 6,
   'min_child_samples': 11,
   'subsample': 0.9704198407257476,
   'colsample_bytree': 0.8302542907662975,
   'n_estimators': 500}, 'best_score': 0.555, 'study': <optuna.study.study.Study at 0x7800a8e6bf40>},
 ('C2X-Complex_rhow_15x15_depth_in_3_4',
  'MLP'): {'best_params': {'hidden_layer_sizes': '256',
   'activation': 'relu',
   'solver': 'adam',
   'alpha': 0.03673448429184167,
   'learning_rate': 'adaptive',
   'learning_rate_init': 0.005512541724045937}, 'best_score': 0.638, 'study': <optuna.study.study.Study at 0x7800a9f6f5b0>},
 ('C2X-Complex_rhow_15x15_depth_in_3_4',
  'SVR'): {'best_params': {'C': 3.2413369664629386,
   'epsilon': 0.1982961712911414}, 'best_score': 0.584, 'study': <optuna.study.study.Study at 0x7800d8fe5ee0>},
 ('C2X-Complex_rhow_15x15_depth_in_3_4',
  'KNN'): {'best_params': {'n_neighbors': 10,
   'leaf_size': 19}, 'best_score': 0.484, 'study': <optuna.study.study.Study at 0x7800a8e0ebb0>},
 ('C2X-Complex_rhow_15x15_depth_in_3_4',
  'LR'): {'best_params': {'fit_intercept': True,
   'positive': True}, 'best_score': 0.537, 'study': <optuna.study.study.Study at 0x7800a8e796a0>},
 ('C2X-Complex_rhow_15x15_depth_in_3_4',
  'RF'): {'best_params': {'n_estimators': 100,
   'max_depth': 8,
   'min_samples_split': 3,
   'min_samples_leaf': 4,
   'bootstrap': True}, 'best_score': 0.572, 'study': <optuna.study.study.Study at 0x7800a9ec8d30>},
 ('C2X-Complex_rhow_15x15_depth_in_3_4',
  'CAT'): {'best_params': {'iterations': 500,
   'learning_rate': 0.010126948003726963,

**Entrenamiento con los parámetros seleccionados**

In [318]:
results = {}

for nombre_df, df in list(dfs.items()):
    #print(nombre_df)
    df = df.iloc[:,4:]

    # Para usar solamente bandas, sin combinaciones
    # if 'TOA' in nombre_df:
    #     # TOA solamente con las bandas, parece que las combinaciones solo meten ruido
    #     df = df.iloc[:,np.r_[0:14, 58:60]]
    # if 'rhow' in nombre_df and 'rhown' not in nombre_df:
    #     df = df.iloc[:,np.r_[0:9, 53:55]]
    # if 'rhown' in nombre_df:
    #     df = df.iloc[:,np.r_[0:7, 51:53]]

    train, test = train_test_split(df, test_size=0.2, random_state=42, stratify=df["High_Chl"]) # TEST 20% TRAIN 80%
    target = "Chl"

    train, val = train_test_split(train, test_size=0.25, random_state=42, stratify=train["High_Chl"]) # TRAIN 60% VAL 20% TEST%

    X_train = train.drop(columns=[target,"High_Chl"])
    X_val = val.drop(columns=[target, "High_Chl"])
    X_test = test.drop(columns=[target, "High_Chl"])
    y_train = train[target]
    y_val = val[target]
    y_test = test[target]

    
    scaler_X = RobustScaler()
    scaler_y = RobustScaler()
    X_train_scaled = scaler_X.fit_transform(X_train)
    X_val_scaled = scaler_X.transform(X_val)
    X_test_scaled = scaler_X.transform(X_test)
    y_train_scaled = scaler_y.fit_transform(y_train.values.reshape(-1, 1)).ravel()
    
    results[nombre_df] = {name: {'RMSE': None, 'R2': None} for name in models}
    val_preds = {}
    test_preds = {}

    for name, model in models.items():
        print(f"Fitting {name} for {nombre_df}")
        if name in ["MLP", "SVR", "KNN", "LR", "EN"]:
            model.fit(X_train_scaled, y_train_scaled)
            #test_pred = model.predict(X_test_scaled)
            val_pred = scaler_y.inverse_transform(model.predict(X_val_scaled).reshape(-1, 1)).ravel()
            test_pred = scaler_y.inverse_transform(model.predict(X_test_scaled).reshape(-1, 1)).ravel()
        else:
            model.fit(X_train, y_train)
            val_pred = model.predict(X_val)
            test_pred = model.predict(X_test)

        val_preds[name] = val_pred
        test_preds[name] = test_pred

        rmse = np.sqrt(mean_squared_error(y_test, test_pred))
        r2 = r2_score(y_test, test_pred)

        results[nombre_df][name]['RMSE'] = rmse.round(2)
        results[nombre_df][name]['R2'] = r2.round(2)

    # Meta-modelo
    meta_X = np.vstack([val_preds[model] for model in models]).T
    meta_y = y_val.values
    meta_model = Ridge().fit(meta_X, meta_y)

    # Predicción final ensemble
    test_meta_X = np.vstack([test_preds[model] for model in models]).T
    ensemble_pred = meta_model.predict(test_meta_X)

    rmse_ens = np.sqrt(mean_squared_error(y_test, ensemble_pred))
    r2_ens = r2_score(y_test, ensemble_pred)

    results[nombre_df]["Ensemble"] = {
        "RMSE": round(rmse_ens, 2),
        "R2": round(r2_ens, 2)
    }

Fitting XGB for C2RCC_rhow_5x5_depth_lt_1
Fitting LBM for C2RCC_rhow_5x5_depth_lt_1
Fitting MLP for C2RCC_rhow_5x5_depth_lt_1
Fitting SVR for C2RCC_rhow_5x5_depth_lt_1
Fitting KNN for C2RCC_rhow_5x5_depth_lt_1
Fitting LR for C2RCC_rhow_5x5_depth_lt_1
Fitting RF for C2RCC_rhow_5x5_depth_lt_1
Fitting CAT for C2RCC_rhow_5x5_depth_lt_1
Fitting EN for C2RCC_rhow_5x5_depth_lt_1
Fitting XGB for C2X-Complex_rhown_3x3_depth_lt_1
Fitting LBM for C2X-Complex_rhown_3x3_depth_lt_1
Fitting MLP for C2X-Complex_rhown_3x3_depth_lt_1
Fitting SVR for C2X-Complex_rhown_3x3_depth_lt_1
Fitting KNN for C2X-Complex_rhown_3x3_depth_lt_1
Fitting LR for C2X-Complex_rhown_3x3_depth_lt_1
Fitting RF for C2X-Complex_rhown_3x3_depth_lt_1
Fitting CAT for C2X-Complex_rhown_3x3_depth_lt_1
Fitting EN for C2X-Complex_rhown_3x3_depth_lt_1
Fitting XGB for TOA_9x9_depth_lt_1
Fitting LBM for TOA_9x9_depth_lt_1
Fitting MLP for TOA_9x9_depth_lt_1
Fitting SVR for TOA_9x9_depth_lt_1
Fitting KNN for TOA_9x9_depth_lt_1
Fitting LR for TOA_9x9_depth_lt_1
Fitting RF for TOA_9x9_depth_lt_1
Fitting CAT for TOA_9x9_depth_lt_1
Fitting EN for TOA_9x9_depth_lt_1
Fitting XGB for C2X_rhow_3x3_depth_lt_1
Fitting LBM for C2X_rhow_3x3_depth_lt_1
Fitting MLP for C2X_rhow_3x3_depth_lt_1
Fitting SVR for C2X_rhow_3x3_depth_lt_1
Fitting KNN for C2X_rhow_3x3_depth_lt_1
Fitting LR for C2X_rhow_3x3_depth_lt_1
Fitting RF for C2X_rhow_3x3_depth_lt_1
Fitting CAT for C2X_rhow_3x3_depth_lt_1
Fitting EN for C2X_rhow_3x3_depth_lt_1
Fitting XGB for C2RCC_rhow_9x9_depth_lt_1
Fitting LBM for C2RCC_rhow_9x9_depth_lt_1
Fitting MLP for C2RCC_rhow_9x9_depth_lt_1
Fitting SVR for C2RCC_rhow_9x9_depth_lt_1
Fitting KNN for C2RCC_rhow_9x9_depth_lt_1
Fitting LR for C2RCC_rhow_9x9_depth_lt_1
Fitting RF for C2RCC_rhow_9x9_depth_lt_1
Fitting CAT for C2RCC_rhow_9x9_depth_lt_1
Fitting EN for C2RCC_rhow_9x9_depth_lt_1
Fitting XGB for C2X-Complex_rhown_5x5_depth_lt_1
Fitting LBM for C2X-Complex_rhown_5x5_depth_lt_1
Fitting MLP for C2X-Complex_rhown_5x5_depth_lt_1
Fitting SVR for C2X-Complex_rhown_5x5_depth_lt_1
Fitting KNN for C2X-Complex_rhown_5x5_depth_lt_1
Fitting LR for C2X-Complex_rhown_5x5_depth_lt_1
Fitting RF for C2X-Complex_rhown_5x5_depth_lt_1
Fitting CAT for C2X-Complex_rhown_5x5_depth_lt_1
Fitting EN for C2X-Complex_rhown_5x5_depth_lt_1
Fitting XGB for C2X_rhown_9x9_depth_lt_1
Fitting LBM for C2X_rhown_9x9_depth_lt_1
Fitting MLP for C2X_rhown_9x9_depth_lt_1
Fitting SVR for C2X_rhown_9x9_depth_lt_1
Fitting KNN for C2X_rhown_9x9_depth_lt_1
Fitting LR for C2X_rhown_9x9_depth_lt_1
Fitting RF for C2X_rhown_9x9_depth_lt_1
Fitting CAT for C2X_rhown_9x9_depth_lt_1
Fitting EN for C2X_rhown_9x9_depth_lt_1
Fitting XGB for TOA_3x3_depth_lt_1
Fitting LBM for TOA_3x3_depth_lt_1
Fitting MLP for TOA_3x3_depth_lt_1
Fitting SVR for TOA_3x3_depth_lt_1
Fitting KNN for TOA_3x3_depth_lt_1
Fitting LR for TOA_3x3_depth_lt_1
Fitting RF for TOA_3x3_depth_lt_1
Fitting CAT for TOA_3x3_depth_lt_1
Fitting EN for TOA_3x3_depth_lt_1
Fitting XGB for C2X-Complex_rhown_9x9_depth_lt_1
Fitting LBM for C2X-Complex_rhown_9x9_depth_lt_1
Fitting MLP for C2X-Complex_rhown_9x9_depth_lt_1
Fitting SVR for C2X-Complex_rhown_9x9_depth_lt_1
Fitting KNN for C2X-Complex_rhown_9x9_depth_lt_1
Fitting LR for C2X-Complex_rhown_9x9_depth_lt_1
Fitting RF for C2X-Complex_rhown_9x9_depth_lt_1
Fitting CAT for C2X-Complex_rhown_9x9_depth_lt_1
Fitting EN for C2X-Complex_rhown_9x9_depth_lt_1
Fitting XGB for C2X-Complex_rhow_3x3_depth_lt_1
Fitting LBM for C2X-Complex_rhow_3x3_depth_lt_1
Fitting MLP for C2X-Complex_rhow_3x3_depth_lt_1
Fitting SVR for C2X-Complex_rhow_3x3_depth_lt_1
Fitting KNN for C2X-Complex_rhow_3x3_depth_lt_1
Fitting LR for C2X-Complex_rhow_3x3_depth_lt_1
Fitting RF for C2X-Complex_rhow_3x3_depth_lt_1
Fitting CAT for C2X-Complex_rhow_3x3_depth_lt_1
Fitting EN for C2X-Complex_rhow_3x3_depth_lt_1
Fitting XGB for C2X_rhow_1x1_depth_lt_1
Fitting LBM for C2X_rhow_1x1_depth_lt_1
Fitting MLP for C2X_rhow_1x1_depth_lt_1
Fitting SVR for C2X_rhow_1x1_depth_lt_1
Fitting KNN for C2X_rhow_1x1_depth_lt_1
Fitting LR for C2X_rhow_1x1_depth_lt_1
Fitting RF for C2X_rhow_1x1_depth_lt_1
Fitting CAT for C2X_rhow_1x1_depth_lt_1
Fitting EN for C2X_rhow_1x1_depth_lt_1
Fitting XGB for C2RCC_rhown_1x1_depth_lt_1
Fitting LBM for C2RCC_rhown_1x1_depth_lt_1
Fitting MLP for C2RCC_rhown_1x1_depth_lt_1
Fitting SVR for C2RCC_rhown_1x1_depth_lt_1
Fitting KNN for C2RCC_rhown_1x1_depth_lt_1
Fitting LR for C2RCC_rhown_1x1_depth_lt_1
Fitting RF for C2RCC_rhown_1x1_depth_lt_1
Fitting CAT for C2RCC_rhown_1x1_depth_lt_1
Fitting EN for C2RCC_rhown_1x1_depth_lt_1
Fitting XGB for C2X_rhown_1x1_depth_lt_1
Fitting LBM for C2X_rhown_1x1_depth_lt_1
Fitting MLP for C2X_rhown_1x1_depth_lt_1
Fitting SVR for C2X_rhown_1x1_depth_lt_1
Fitting KNN for C2X_rhown_1x1_depth_lt_1
Fitting LR for C2X_rhown_1x1_depth_lt_1
Fitting RF for C2X_rhown_1x1_depth_lt_1
Fitting CAT for C2X_rhown_1x1_depth_lt_1
Fitting EN for C2X_rhown_1x1_depth_lt_1
Fitting XGB for C2RCC_rhown_9x9_depth_lt_1
Fitting LBM for C2RCC_rhown_9x9_depth_lt_1
Fitting MLP for C2RCC_rhown_9x9_depth_lt_1
Fitting SVR for C2RCC_rhown_9x9_depth_lt_1
Fitting KNN for C2RCC_rhown_9x9_depth_lt_1
Fitting LR for C2RCC_rhown_9x9_depth_lt_1
Fitting RF for C2RCC_rhown_9x9_depth_lt_1
Fitting CAT for C2RCC_rhown_9x9_depth_lt_1
Fitting EN for C2RCC_rhown_9x9_depth_lt_1
Fitting XGB for C2X_rhow_5x5_depth_lt_1
Fitting LBM for C2X_rhow_5x5_depth_lt_1
Fitting MLP for C2X_rhow_5x5_depth_lt_1
Fitting SVR for C2X_rhow_5x5_depth_lt_1
Fitting KNN for C2X_rhow_5x5_depth_lt_1
Fitting LR for C2X_rhow_5x5_depth_lt_1
Fitting RF for C2X_rhow_5x5_depth_lt_1
Fitting CAT for C2X_rhow_5x5_depth_lt_1
Fitting EN for C2X_rhow_5x5_depth_lt_1
Fitting XGB for C2X_rhown_5x5_depth_lt_1
Fitting LBM for C2X_rhown_5x5_depth_lt_1
Fitting MLP for C2X_rhown_5x5_depth_lt_1
Fitting SVR for C2X_rhown_5x5_depth_lt_1
Fitting KNN for C2X_rhown_5x5_depth_lt_1
Fitting LR for C2X_rhown_5x5_depth_lt_1
Fitting RF for C2X_rhown_5x5_depth_lt_1
Fitting CAT for C2X_rhown_5x5_depth_lt_1
Fitting EN for C2X_rhown_5x5_depth_lt_1
Fitting XGB for C2X_rhow_9x9_depth_lt_1
Fitting LBM for C2X_rhow_9x9_depth_lt_1
Fitting MLP for C2X_rhow_9x9_depth_lt_1
Fitting SVR for C2X_rhow_9x9_depth_lt_1
Fitting KNN for C2X_rhow_9x9_depth_lt_1
Fitting LR for C2X_rhow_9x9_depth_lt_1
Fitting RF for C2X_rhow_9x9_depth_lt_1
Fitting CAT for C2X_rhow_9x9_depth_lt_1
Fitting EN for C2X_rhow_9x9_depth_lt_1
Fitting XGB for C2X_rhown_3x3_depth_lt_1
Fitting LBM for C2X_rhown_3x3_depth_lt_1
Fitting MLP for C2X_rhown_3x3_depth_lt_1
Fitting SVR for C2X_rhown_3x3_depth_lt_1
Fitting KNN for C2X_rhown_3x3_depth_lt_1
Fitting LR for C2X_rhown_3x3_depth_lt_1
Fitting RF for C2X_rhown_3x3_depth_lt_1
Fitting CAT for C2X_rhown_3x3_depth_lt_1
Fitting EN for C2X_rhown_3x3_depth_lt_1
Fitting XGB for C2RCC_rhown_5x5_depth_lt_1
Fitting LBM for C2RCC_rhown_5x5_depth_lt_1
Fitting MLP for C2RCC_rhown_5x5_depth_lt_1
Fitting SVR for C2RCC_rhown_5x5_depth_lt_1
Fitting KNN for C2RCC_rhown_5x5_depth_lt_1
Fitting LR for C2RCC_rhown_5x5_depth_lt_1
Fitting RF for C2RCC_rhown_5x5_depth_lt_1
Fitting CAT for C2RCC_rhown_5x5_depth_lt_1
Fitting EN for C2RCC_rhown_5x5_depth_lt_1
Fitting XGB for TOA_1x1_depth_lt_1
Fitting LBM for TOA_1x1_depth_lt_1
Fitting MLP for TOA_1x1_depth_lt_1
Fitting SVR for TOA_1x1_depth_lt_1
Fitting KNN for TOA_1x1_depth_lt_1
Fitting LR for TOA_1x1_depth_lt_1
Fitting RF for TOA_1x1_depth_lt_1
Fitting CAT for TOA_1x1_depth_lt_1
Fitting EN for TOA_1x1_depth_lt_1
Fitting XGB for C2X-Complex_rhow_5x5_depth_lt_1
Fitting LBM for C2X-Complex_rhow_5x5_depth_lt_1
Fitting MLP for C2X-Complex_rhow_5x5_depth_lt_1
Fitting SVR for C2X-Complex_rhow_5x5_depth_lt_1
Fitting KNN for C2X-Complex_rhow_5x5_depth_lt_1
Fitting LR for C2X-Complex_rhow_5x5_depth_lt_1
Fitting RF for C2X-Complex_rhow_5x5_depth_lt_1
Fitting CAT for C2X-Complex_rhow_5x5_depth_lt_1
Fitting EN for C2X-Complex_rhow_5x5_depth_lt_1
Fitting XGB for C2X-Complex_rhow_9x9_depth_lt_1
Fitting LBM for C2X-Complex_rhow_9x9_depth_lt_1
Fitting MLP for C2X-Complex_rhow_9x9_depth_lt_1
Fitting SVR for C2X-Complex_rhow_9x9_depth_lt_1
Fitting KNN for C2X-Complex_rhow_9x9_depth_lt_1
Fitting LR for C2X-Complex_rhow_9x9_depth_lt_1
Fitting RF for C2X-Complex_rhow_9x9_depth_lt_1
Fitting CAT for C2X-Complex_rhow_9x9_depth_lt_1
Fitting EN for C2X-Complex_rhow_9x9_depth_lt_1
Fitting XGB for C2X-Complex_rhow_1x1_depth_lt_1
Fitting LBM for C2X-Complex_rhow_1x1_depth_lt_1
Fitting MLP for C2X-Complex_rhow_1x1_depth_lt_1
Fitting SVR for C2X-Complex_rhow_1x1_depth_lt_1
Fitting KNN for C2X-Complex_rhow_1x1_depth_lt_1
Fitting LR for C2X-Complex_rhow_1x1_depth_lt_1
Fitting RF for C2X-Complex_rhow_1x1_depth_lt_1
Fitting CAT for C2X-Complex_rhow_1x1_depth_lt_1
Fitting EN for C2X-Complex_rhow_1x1_depth_lt_1
Fitting XGB for C2X-Complex_rhown_1x1_depth_lt_1
Fitting LBM for C2X-Complex_rhown_1x1_depth_lt_1
Fitting MLP for C2X-Complex_rhown_1x1_depth_lt_1
Fitting SVR for C2X-Complex_rhown_1x1_depth_lt_1
Fitting KNN for C2X-Complex_rhown_1x1_depth_lt_1
Fitting LR for C2X-Complex_rhown_1x1_depth_lt_1
Fitting RF for C2X-Complex_rhown_1x1_depth_lt_1
Fitting CAT for C2X-Complex_rhown_1x1_depth_lt_1
Fitting EN for C2X-Complex_rhown_1x1_depth_lt_1
Fitting XGB for C2RCC_rhow_3x3_depth_lt_1
Fitting LBM for C2RCC_rhow_3x3_depth_lt_1
Fitting MLP for C2RCC_rhow_3x3_depth_lt_1
Fitting SVR for C2RCC_rhow_3x3_depth_lt_1
Fitting KNN for C2RCC_rhow_3x3_depth_lt_1
Fitting LR for C2RCC_rhow_3x3_depth_lt_1
Fitting RF for C2RCC_rhow_3x3_depth_lt_1
Fitting CAT for C2RCC_rhow_3x3_depth_lt_1
Fitting EN for C2RCC_rhow_3x3_depth_lt_1
Fitting XGB for TOA_5x5_depth_lt_1
Fitting LBM for TOA_5x5_depth_lt_1
Fitting MLP for TOA_5x5_depth_lt_1
Fitting SVR for TOA_5x5_depth_lt_1
Fitting KNN for TOA_5x5_depth_lt_1
Fitting LR for TOA_5x5_depth_lt_1
Fitting RF for TOA_5x5_depth_lt_1
Fitting CAT for TOA_5x5_depth_lt_1
Fitting EN for TOA_5x5_depth_lt_1
Fitting XGB for C2RCC_rhown_3x3_depth_lt_1
Fitting LBM for C2RCC_rhown_3x3_depth_lt_1
Fitting MLP for C2RCC_rhown_3x3_depth_lt_1
Fitting SVR for C2RCC_rhown_3x3_depth_lt_1
Fitting KNN for C2RCC_rhown_3x3_depth_lt_1
Fitting LR for C2RCC_rhown_3x3_depth_lt_1
Fitting RF for C2RCC_rhown_3x3_depth_lt_1
Fitting CAT for C2RCC_rhown_3x3_depth_lt_1
Fitting EN for C2RCC_rhown_3x3_depth_lt_1
Fitting XGB for C2RCC_rhow_1x1_depth_lt_1
Fitting LBM for C2RCC_rhow_1x1_depth_lt_1
Fitting MLP for C2RCC_rhow_1x1_depth_lt_1
Fitting SVR for C2RCC_rhow_1x1_depth_lt_1
Fitting KNN for C2RCC_rhow_1x1_depth_lt_1
Fitting LR for C2RCC_rhow_1x1_depth_lt_1
Fitting RF for C2RCC_rhow_1x1_depth_lt_1
Fitting CAT for C2RCC_rhow_1x1_depth_lt_1
Fitting EN for C2RCC_rhow_1x1_depth_lt_1

In [329]:
rows = []

for df_name, model_scores in results.items():
    row = {}
    for model_name, metrics in model_scores.items():
        for metric_name, values in metrics.items():
            if isinstance(values, list):  # Solo para los que tienen listas (folds)
                mean_val = np.mean(values)
                std_val = np.std(values)
                row[(metric_name, model_name)] = f"{mean_val:.2f} ± {std_val:.2f}"
            else:
                # Para el ensemble que tiene un único valor
                row[(metric_name, model_name)] = f"{values:.2f}"
    rows.append((df_name, row))

df_results = pd.DataFrame.from_dict(dict(rows), orient="index")
df_results.columns = pd.MultiIndex.from_tuples(df_results.columns, names=["Metric", "Model"])
df_results = df_results.sort_index(axis=1, level=0)
df_results = df_results.sort_index(axis=0)

In [330]:
df_results

Metric                                     R2                         \
Model                                     CAT           EN  Ensemble
C2RCC_rhow_5x5_depth_lt_1         0.67 ± 0.13  0.48 ± 0.07      0.61
C2X-Complex_rhown_3x3_depth_lt_1  0.66 ± 0.12  0.50 ± 0.06  -6049.03
TOA_9x9_depth_lt_1                0.78 ± 0.12  0.19 ± 0.13      0.46

Metric                                                                    \
Model                                     KNN          LBM            LR
C2RCC_rhow_5x5_depth_lt_1         0.74 ± 0.10  0.61 ± 0.24   0.31 ± 0.52
C2X-Complex_rhown_3x3_depth_lt_1  0.59 ± 0.12  0.55 ± 0.17  -1.12 ± 3.18
TOA_9x9_depth_lt_1                0.76 ± 0.13  0.70 ± 0.09   0.18 ± 0.36

Metric                                                                   \
Model                                     MLP           RF          SVR
C2RCC_rhow_5x5_depth_lt_1         0.71 ± 0.12  0.63 ± 0.18  0.66 ± 0.15
C2X-Complex_rhown_3x3_depth_lt_1  0.45 ± 0.08  0.63 ± 0.11  0.53 ± 0.09
TOA_9x9_depth_lt_1                0.65 ± 0.14  0.70 ± 0.13  0.50 ± 0.04

Metric                                                RMSE               \
Model                                     XGB          CAT           EN
C2RCC_rhow_5x5_depth_lt_1         0.65 ± 0.19  2.04 ± 0.37  2.64 ± 0.20
C2X-Complex_rhown_3x3_depth_lt_1  0.61 ± 0.17  2.08 ± 0.17  2.63 ± 0.41
TOA_9x9_depth_lt_1                0.72 ± 0.12  1.80 ± 0.49  3.58 ± 0.15

Metric                                                               \
Model                            Ensemble          KNN          LBM
C2RCC_rhow_5x5_depth_lt_1            2.97  1.81 ± 0.21  2.16 ± 0.50
C2X-Complex_rhown_3x3_depth_lt_1   370.82  2.30 ± 0.17  2.41 ± 0.25
TOA_9x9_depth_lt_1                   2.59  1.87 ± 0.37  2.15 ± 0.32

Metric                                                                   \
Model                                      LR          MLP           RF
C2RCC_rhow_5x5_depth_lt_1         2.83 ± 0.72  1.93 ± 0.27  2.14 ± 0.35
C2X-Complex_rhown_3x3_depth_lt_1  4.08 ± 2.64  2.77 ± 0.44  2.21 ± 0.17
TOA_9x9_depth_lt_1                3.49 ± 0.48  2.31 ± 0.28  2.12 ± 0.39

Metric
Model                                     SVR          XGB
C2RCC_rhow_5x5_depth_lt_1         2.08 ± 0.31  2.08 ± 0.44
C2X-Complex_rhown_3x3_depth_lt_1  2.52 ± 0.31  2.21 ± 0.28
TOA_9x9_depth_lt_1                2.84 ± 0.26  2.05 ± 0.44